### ISSUE TITLE
Trying to link GLVIS

### ISSUE THREAD

**Issue by Tdub1229** [mfem/mfem#1004]
Trying to link GLVIS to MFEM... I have followed all of the steps to make build and install MFEM. I am able to get the test and examples to run with no error. However, when I try to use glvis to play around the visualization, I get the following errors trying to follow the example on the website.

makefile:192: *** The MFEM library is not built.  Stop.

./glvis: No such file or directory

**Comment by tzanio** [comment]
What version of mfem and glvis do you use, and what are the directories you built them in. 

In particular, what's the output of `ls -a ..` from the glvis directory?

**Comment by Tdub1229** [comment]
ed@ed-MacBookAir:~/mfem/mfem-4.0$ cd glvis-3.4/
ed@ed-MacBookAir:~/mfem/mfem-4.0/glvis-3.4$ ls -a
.                           data_is_copied   makefile
..                          doc              Makefile
CHANGELOG                   examples         mesh
CMakeCache.txt              fem              MFEMConfig.cmake
CMakeDoxyfile.in            general          MFEMConfigVersion.cmake
CMakeDoxygenDefaults.cmake  glvis.cpp        mfem.hpp
CMakeFiles                  glvis-keygen.sh  mfem-performance.hpp
cmake_install.cmake         INSTALL          MFEMTargets.cmake
CMakeLists.txt              InstallHeaders   miniapps
config                      lib              README
COPYRIGHT                   libmfem.a        tests
CTestTestfile.cmake         LICENSE
data                        linalg

**Comment by v-dobrev** [comment]
It looks like you placed the GLVis directory `glvis-3.4` inside the mfem directory `mfem-4.0`. Something is not quite right, e.g. I'm not sure how files like `libmfem.a` and `mfem.hpp` got inside the GLVis directory.

Regardless of that, you should be able to build GLVis using the following command in the GLVis directory:
```console
make MFEM_DIR=/path/to/mfem
```
where you should replace "/path/to/mfem" with the actual path to the directory where you built MFEM.
