### ISSUE TITLE
How to define nonlinear model by myself?

### ISSUE THREAD

**Issue by fanronghong** [mfem/mfem#1005]
Hi all,
I want to solve a nonlinear problem(like PNP). But I don't know how to define `NonlinearForm`. 
I read ex10. But in ex10, there is a model `NeoHookeanModel` which you can use directly in your   
 program. When you define the nonlinear model, you can add a domain integrator just like `H.AddDomainIntegrator(new HyperelasticNLFIntegrator(model))`, where H is a `NonlinearForm`.

Now, if I want to solve the simple nonlinear PDE, like [diffusion-reaction](https://github.com/mfem/mfem/issues/474#issue-314380217), so how to define my nonlinear model? And then how to define nonlinear integrator on this model? So I can use `AddDomainIntegrator()` to a NonlinearForm?

Thanks a lot!

**Comment by jandrej** [comment]
Hi,

see #160 and maybe #102. The first issue describes the implementation of a nonlinear reaction term in great detail. If you have any further questions after reviewing the links, let us know.

**Comment by fanronghong** [comment]
Thank you for your reply @jandrej and sorry to reply to you late.  Actually, I already saw the above issues you suggested. But I am also confused.

In ex10, for the `NonlinearForm H`, there is already a model `NeoHookeanModel` in MFEM source code. Then below two steps
```
model = new NeoHookeanModel(mu, K);
H.AddDomainIntegrator(new HyperelasticNLFIntegrator(model));
```
define a `NonlinearForm H` and then you can obtain the Jacobian by `H->GetGradient(z)`. 
So we can see all above steps are based on `NeoHookeanModel`. But for a simple nonlinear problem, like `u.grad(u)`, do we need to define a model like `NeoHookeanModel`?

If you can show me a simple demo, like for nonlinear problem `u.grad(u)`, maybe I can understand the two issues more clearly.

**Comment by jandrej** [comment]
You don't need to define a model like `NeoHookeanModel`. This is only specific to nonlinear elasticity problems.

You can take a look at https://github.com/mfem/mfem/tree/stokes-example/miniapps/flow, specifically `vec_conv_integrator.cpp` and `vec_conv_integrator.hpp`. It defines the `NonlinearFormIntegrator` for the term `u.grad(u)`.

The driver files are a bit more involving, but it might help to take a look at them how the `NonlinearForm` is used.

**Comment by fanronghong** [comment]
Thank you @jandrej for your time. I must take some to dig the code.

**Comment by tzanio** [comment]
@fanronghong, I'm closing this issue for now but please feel free to reopen if you have further questions
