### ISSUE TITLE
Q: is `elfun` always provided in order `byNODES` to a nonlinear integrator?

### ISSUE THREAD

**Issue by jehicken** [mfem/mfem#1007]
Hi,

I am writing a nonlinear integrator for a `FiniteElementSpace` that uses `ordering::byVDIM`.  However, when the integrator is called, it seems like the `elfun` values are stored `byNODES`.  Is this correct?  If so, can I change this behavior?

I am asking because I would like to access all the state values at a node using continuous memory; for example, extracting them from a `DenseMatrix` of values using `GetColumnReference`:
```
   DenseMatrix u(elfun.GetData(), vdim, ndof);
   Vector ui;
   for (int i = 0; i < ndof; ++i)
   {
      u.GetColumnReference(i, ui);
      /// code using ui
   }
```

Thanks,
Jason

**Comment by vladotomov** [comment]
Hi Jason, see `Ordering::DofsToVDofs(...)` in fem/fespace.hpp and cpp.

Vladimir

**Comment by vladotomov** [comment]
Sorry, the above is not the correct function to use. I can see `GridFunction::ReorderByNodes(),` but I'm not sure if we have a similar function for the other direction. You might have to write a reordering loop yourself :)

Vladimir

**Comment by jehicken** [comment]
Hi Vladimir,

Thanks for the quick reply.

1. Just to be sure I understand, the function `NonlinearForm::Mult` always provides the `elfun` values to `AssembleElementVector` ordered `byNodes`? https://github.com/mfem/mfem/blob/369fc7c903398a86588788cef687596dff85d56f/fem/nonlinearform.cpp#L132

2. There is no existing function to reorder `elfun` to be `byVDIM` *inside* of a `NonlinearFormIintegrator::AssembleElementVector`, is that correct?

If the answers to the above two questions is yes, then would the best option be to provide an option that makes `NonlinearForm::Mult` choose the desired ordering to provide to `AssembleElementVector`?

Thanks again,
Jason

**Comment by vladotomov** [comment]
The default ordering can be set on the `FiniteElementSpace` level -- the constructor has an ordering parameter, which has default value of `byNodes`. The `NonlinearForms` know which is their `FiniteElementSpace`. Thus if you create your form with a space that has the `byVDIM` ordering, that's the ordering you will get in the `Vector` given to `AssembleElementVector`. In principle this should work, hopefully you won't call a function that assumes `byNodes` ordering in the `FiniteElementSpace`.

**Comment by jehicken** [comment]
I must be doing something wrong then, because I am constructing the `FiniteElementSpace` using `ordering::byVDIM`, but when I inspect the state vector passed to `AssembleElementVector` it has Node ordering.  I will keep digging tomorrow and let you know what I find...probably user error.

**Comment by jehicken** [comment]
I added some code to display the `vdofs` array immediately after this line in `NonlinearForm::Mult`:
https://github.com/mfem/mfem/blob/369fc7c903398a86588788cef687596dff85d56f/fem/nonlinearform.cpp#L127
Here is the output for the first element in the loop:
```
element i = 0 vdofs: 8, 0, 4, 44, 48, 52, 176, 9, 1, 5, 45, 49, 53, 177, 10, 2, 6, 46, 50, 54, 178, 11, 3, 7, 47, 51, 55, 179
```
This element has 7 degrees of freedom and there are 4 state variables (`dofs=7` and `vdim=4`).

The first 7 indices in the `vdofs` array are equal to 0 modulo 4, the next 7 indices are equal to 1 modulo 4, and so on.  Thus, the state variable seems to be stored using `ordering::byVDIM`, but `GetElementVDofs` is explicitly reordering the state to have node ordering instead.

Is this intentional, or am I missing something?

Thanks again,
Jason

**Comment by vladotomov** [comment]
Fine I mostly understand this, but it's somewhat complicated. Can you initialize the four functions with 1 to 4 everywhere in the domain, and see what values you get from `GetSubVector`?

**Comment by jehicken** [comment]
Maybe this will help more.  Here is a MWE that shows how the ordering is outside and inside an integrator:
```
#include "mfem.hpp"
#include <fstream>
#include <iostream>

using namespace std;
using namespace mfem;

/// Integrator that prints out ordering of each variable
class DoNothingIntegrator : public NonlinearFormIntegrator
{
public:
   virtual void AssembleElementVector(const mfem::FiniteElement &el,
                                      mfem::ElementTransformation &Trans,
                                      const mfem::Vector &elfun,
                                      mfem::Vector &elvect)
   {
      cout << "Element no. " << Trans.ElementNo << " variable values: " << endl;
      cout << "\t";
      for (int i = 0; i < elfun.Size(); ++i)
      {
         cout << elfun(i) << ", ";
      }
      cout << endl;
      elvect.SetSize(elfun.Size()); // needed to prevent seg fault
   }
};

void u0_function(const Vector &xcoord, Vector& u0)
{
   u0.SetSize(4);
   u0(0) = 1.0;
   u0(1) = 2.0;
   u0(2) = 3.0;
   u0(3) = 4.0;
}

int main(int argc, char *argv[])
{
   // Create a mesh on a square domain
   int nx = 1;
   int ny = 1;
   Mesh *mesh = new Mesh(nx, ny, Element::Type::TRIANGLE);
   int dim = mesh->Dimension();

   // Define the finite-element space (Lagrange) with vdim = 4 and ordering byVDIM
   FiniteElementCollection *fec;
   int order = 1;
   fec = new H1_FECollection(order, dim);
   int vdim = 4;
   FiniteElementSpace *fespace = new FiniteElementSpace(mesh, fec, vdim, Ordering::byVDIM);
   cout << "Number of finite element unknowns: "
        << fespace->GetTrueVSize() << endl;

   // Define the nonlinear form and add Integrator
   NonlinearForm *res = new NonlinearForm(fespace);
   res->AddDomainIntegrator(new DoNothingIntegrator());

   // Set u to be 1, 2, 3, 4 at each node
   GridFunction u(fespace);
   GridFunction v(fespace);
   VectorFunctionCoefficient ucoeff(vdim, u0_function);
   u.ProjectCoefficient(ucoeff);

   // print out the ordering in u outside of res-Mult
   cout << "Grid function values outside res-Mult:" << endl;
   cout << "\t";
   for (int i = 0; i < u.Size(); ++i)
   {
      cout << u(i) << ", ";
   }
   cout << endl;

   // Call res->Mult to display the ordering inside DoNothingIntegrator
   res->Mult(u, v);

   // Free memory
   delete res;
   delete fespace;
   delete fec;
   delete mesh;
   return 0;
}
```
And here is the output I get from this example:
```
Number of finite element unknowns: 16
Grid function values outside res-Mult:
	1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 
Element no. 0 variable values: 
	1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 
Element no. 1 variable values: 
	1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4,
```

**Comment by vladotomov** [comment]
ok this is correct -- the ordering in local vectors, obtained by `GetElementVDofs`, is always `byNodes`. I went over the construction and couldn't find an internal function that orders the local vectors differently. Sorry for the confusion. The `FiniteElementSpace` parameter only affects the global state variable.

Anyway, if reordering can give you big performance gain, you can certainly write a single O(n) loop to reorder the input in your custom `AssembleElementVector`.

**Comment by jehicken** [comment]
Sure, we can reorder the array ourselves.  Thank you for looking into this question for us.

By the way, just curious, why does mfem have this behavior?  It was a bit counter-intuitive to specify `byVDIM` ordering and find out the ordering was not preserved on the integrator.

**Comment by vladotomov** [comment]
I'm not sure why exactly, but I imagine it would be cumbersome to check every time / implement both cases for every integrator. Maybe @v-dobrev can give a better justification.

**Comment by v-dobrev** [comment]
Hi @jehicken,

The purpose of the "ordering" parameter of the `FiniteElementSpace` constructor is to allow a user to choose the global ordering of the DOFs. The local ordering is separate and not necessarily related to the global one. If we want to support both local orderings, every vector integrator will need to support both of them (if the local ordering can be set by the user). I do not see any benefit in that. That is why we fixed one local ordering, "byNODES", and every integrator uses just that.

For the integrator that you are implementing, do you think the "byVDIM" local ordering will better for some reason?

**Comment by jehicken** [comment]
Hi @v-dobrev ,

I have not done benchmarking, so I cannot claim `byVDIM` would be significantly better.  It is the ordering I am familiar with in other CFD codes, so I think that is the source of my bias.  It may help for collocation schemes since we can loop over the nodes and compute the flux as follows (this is a simplified example):
```
DenseMatrix u(elfun.GetData(), num_states, num_nodes); // if ordered byVDIM
for (int i = 0; i < el.GetDof(); ++i)
{
   u.GetColumnReference(i, ui);
   for (int di = 0; di < el.GetDim(); ++di)
   {
      calcFlux(di, ui, flux); // get flux in direction di
      // ... code to differentiation flux here
   }
}
```

However, we are more interested in implicit methods, so I am not overly concerned with the cost of assembling the element vectors.

Thanks again.
