### ISSUE TITLE
Finding volumes of elements

### ISSUE THREAD

**Issue by jxb3641** [mfem/mfem#101]
Hello,

I was wondering if there were any functions in any of the classes that I could call to compute the volumes of any of the supports of the Finite Elements? I know that I can write a function for the elements that would take the corresponding element's Nodes' x, y and z coordinates and compute the volume either using the determinant for simplices or products of the edge lengths for quadrilateral elements, but before beginning writing that function, I just wanted to make sure that there isn't a function defined in any of the relevant classes (FiniteElement, Element Transformation, etc) that does this already.

Thanks,

Juan Batista

**Comment by tzanio** [comment]
Hi Juan,

Does `Mesh::GetElementVolume(int)` meet your needs?

Its implementation applies a quadrature rule to the integral of the determinant of the Jacobian (the transformed integral of 1 over the physical element). This should work for any base geometry as well as curved elements. See

https://github.com/mfem/mfem/blob/master/mesh/mesh.cpp#L70

Hope this helps,
Tzanio

**Comment by jxb3641** [comment]
Thanks, this will do nicely.

Juan

**Comment by jxb3641** [comment]
Hello Tzanio,

Unfortunately, it appears that I resolved prematurely, as I wish to call
this function at a scope where the mesh doesn't exist (i.e. the stack is
inside the call of bilinearform.cpp line 306, so that the mesh is defined
out of scope of the corresponding Assemble() function call).  I tried to
adapt the algorithm in the given solution above (Mesh::GetElementVolume(i))
to only use a supplied FiniteElement instance and ElementTransformation
instance, but I am afraid that the line

et->SetIntPoint(&ip);

will cause future problems in later calculations; i am led to believe this
by the idea that the call

ElementTransformation *et = GetElementTransformation(i);

appears to create a new IsoparametricTransformation instance to work with
to perform the computation, then adjusts it using the corresponding ith
FiniteElement from the mesh, then performs the computation using the
Jacobian as you explained before;  Is this correct to assume?  If so, is
there a way for me to do the same thing without a mesh object to call
Mesh::GetElementTransformation() from?

Thanks again,

Juan

**Comment by tzanio** [comment]
Hi Juan,

I'm a little confused -- can you clarify what you are trying to achieve?

You can certainly call `Mesh::GetElementVolume(i)` at line 306 of `bilinearform.cpp`.

If you are inside a BilinearFormIntergrator, you can do something like this in the beginning of the AssembleElementMatrix method (assuming arguments ` const FiniteElement &el, ElementTransformation &Trans`):
```c++
double volume;
{
   const IntegrationRule &ir = IntRules.Get(el.GetGeomType(), Trans.OrderJ());
   double volume = 0.0;
   for (int j = 0; j < ir.GetNPoints(); j++)
   {
      const IntegrationPoint &ip = ir.IntPoint(j);
      Trans.SetIntPoint(&ip);
      volume += ip.weight * Trans.Weight();
   }
}
// use volume
```
You can also potentially reuse the quadrature rule inside the AssembleElementMatrix computation (depending on when you need the volume).

Hope this helps,
Tzanio

**Comment by martemyev** [comment]
Hi Tzanio,

This caught my eye:
```
double volume = 0.0;
```
You probably wanted it to be:
```
volume = 0.0; 
```

Cheers,
Mikhail

**Comment by tzanio** [comment]
Fixed, thanks @martemyev
