### ISSUE TITLE
Computing The Gradient of a Vector Field when using Vector Finite Element

### ISSUE THREAD

**Issue by mortezah** [mfem/mfem#1011]
Is there a way to compute the gradient of a vector field when using a vector finite element space? In this case the gradient is expected to be a tensor.

**Comment by vladotomov** [comment]
`GetVectorGradient` produces a `DenseMatrix` with the gradients of a multi-component function, at a quadrature point.

**Comment by v-dobrev** [comment]
@mortezah, when you say "vector finite element space" do you mean an FE space using elements derived from `VectorFiniteElement`s, like H(div)- or H(curl)-conforming elements? If that is the case, `GridFunction::GetVectorGradient` will not work.

Computing the exact gradient of such FE functions will require differentiation of the Piola transformation which, in general, is not that simple, at least on general high-order curvilinear meshes. That is why it is currently not implemented in MFEM. However, if approximate gradient is OK, you can project the H(curl)/H(div) `GridFunction` on a vector L2 space and then compute the gradient.

**Comment by mortezah** [comment]
Thanks @vladotomov and @v-dobrev for your responses.

Yes, I was specifically interested in FE spaces derived from `VectorFiniteElement`. 

I think at this point an approximation of the gradient would be enough for my purposes. Could you please point me to the APIs required to achieve the projection onto the L2 space?

**Comment by v-dobrev** [comment]
You can use the method `GridFunction::ProjectVectorFieldOn` with the first argument being the vector L2 space.
