### ISSUE TITLE
how to setup ncmesh from a gmsh file input.

### ISSUE THREAD

**Issue by ztdepztdep** [mfem/mfem#1014]
I want to read in a gmsh file  for the setup of ncmsh. 
how to setup ncmesh from a gmsh file input.

**Comment by tzanio** [comment]
The only way to use non-conforming meshes with an external mesh generator currently is to read a conforming mesh and turn it into an `NCMesh` inside MFEM.

(You can then save the mesh in MFEM format and read it that way)
