### ISSUE TITLE
Compilation errors in VS 2017

### ISSUE THREAD

**Issue by kennyweiss** [mfem/mfem#1016]
I got some compilation errors on Windows with VS 2017 and mfem@4.0.

The problem appears to be that some enum values used by mfem are ``#define``d in windows files but I had trouble tracking down the exact location.

Specifically:
* in ``general/mem_manager.hpp``, VS had a problem with ``REGISTERED``
* in ``fem/data_collection.hpp``, VS had a problem with ``NO_ERROR``

In both case, I was able to resolve the problems locally by ``#undef``-ing the problematic values before they were used by mfem.

E.g.
```cpp
// At top of general/mem_manager.hpp
#if defined(_WIN32) && defined(REGISTERED)
  // REGISTERED is defined in a Windows header, undefine it to use in Memory class
  #undef REGISTERED
#endif
```

```cpp
// At top of fem/datacollection.hpp
#if defined(_WIN32) && defined(NO_ERROR)
  // NO_ERROR is defined in a Windows header, undefine it to use in DataCollection
  #undef NO_ERROR
#endif
```
I see two ways of resolving this:
* Changing the names of these enum values in mfem
* ``#undef``-ing them in mfem, either at the top of the appropriate headers (as above), or in a central mfem location, like ``config.hpp``.

**Comment by v-dobrev** [comment]
Hmm, I'll have to take a closer look but our Appveyor CI (which uses VS 2017 as well) seems to compile and run fine. See for example the recent checks in PR #917.

**Comment by tzanio** [comment]
@kennyweiss and @v-dobrev -- were you able to resolve this?

**Comment by v-dobrev** [comment]
I have not looked more into this.

@kennyweiss, just to clarify: did you see the issue during the compilation of MFEM or when using it in code that uses MFEM? I think the conflicts may be due to header(s) which are not included by MFEM (but by your code) since the appveyor tests work fine. Is that the case?

**Comment by tzanio** [comment]
ping: @kennyweiss

**Comment by kennyweiss** [comment]
I haven't built MFEM on windows since I created the ticket.

@v-dobrev -- your suggestion makes sense.

Since this does not seem to be affecting anyone else, I'll close the ticket, and reopen in the future, if necessary.
