### ISSUE TITLE
How to know if a face is a shared face?

### ISSUE THREAD

**Issue by ztdepztdep** [mfem/mfem#1017]
Which function of Parmesh can provide this infors.

**Comment by tzanio** [comment]
Use `ParMesh::GetSharedFace()` to find the list of shared faces.

(If you instead just need to find if a particular local face is shared, you can probably use `Mesh::GetFaceElements`, but that's not gonna give you the shared face number)

**Comment by vladotomov** [comment]
See the final comments of issue #1149
