### ISSUE TITLE
error::Mesh::GetElementFaces(...) : el_to_face not generated.

### ISSUE THREAD

**Issue by ztdepztdep** [mfem/mfem#1018]
How to resolve this problem

**Comment by tzanio** [comment]
I am sorry but this is insufficient to provide help. Please describe the context.

**Comment by bfadness** [comment]
If the mesh is two-dimensional, then use `Mesh::GetElementEdges`. See this [comment](https://github.com/mfem/mfem/issues/1149#issuecomment-550508961).
