### ISSUE TITLE
Implementing nonlinear terms

### ISSUE THREAD

**Issue by juan42** [mfem/mfem#102]
Hello,

i'm a bit confused on how to approach implementing a nonlinear term in
MFEM which arises in the Navier Stokes or Euler equation for example.

There is the term in the momentum equation

u . grad(u)

for example. Am I supposed to use mfem::NonlinearForm and implement the
needed methods for the mfem::NewtonSolver? In other codes i implemented
the linearized Jacobian term like

inner(grad(du) * u, v)*dx + inner(grad(u) * du, v)*dx

where du is the trial function and u the function.

I also didn't understand in the nonlinear ex10, if there is an
implementation of a "Residual term". I could only spot that the
linearized jacobian is assembled every solving step.

Appreciate your help

Thanks
Julian

**Comment by vladotomov** [comment]
Hi Julian,

If you are solving the nonlinear equation (e.g. Euler) with an implicit method, then it will result in nonlinear terms for the unknown and you'll have to use NonlinearForm + NewtonSolver, as in ex10. That won't be the case for explicit methods.

I'm not sure what you mean by "residual term", could you be more specific?

Vladimir

**Comment by juan42** [comment]
I am used to providing formulations for SNES from PETSc which needs the nonlinear residual in the form of F(u) = 0 and the Jacobian formulation as linearized dF(u)/du for the Newton solver. So for the NS equation you would have something like that for the residual
`F(u) = inner(grad(u), grad(v)) * dx + inner(dot(grad(u), u), v) * dx - p*div(v) * dx + div(u)*q*dx`
and for the Jacobian
`J = inner(grad(du), grad(v))*dx + inner(grad(du)*u, v)*dx + inner(grad(u)*du, v)*dx - dp*div(v)*dx + div(du)*q*dx`

with u, p as functions and v, q as trial functions and du, dp as test functions. Does that make sense?

In a mixed formulation i would need to build a NonlinearForm including the ConvectionIntegrator which will be part of the blockmatrix in every iteration, is this correct?

**Comment by vladotomov** [comment]
Thanks, it's more clear now.
In ex10, the F(u) computation is in BackwardEulerOperator::Mult(), and the J computation is in BackwardEulerOperator::GetGradient().

First you need to define an Operator for your nonlinear system and Jacobian There are different ways to do it:
- Use the existing NonlinearForm class, but define new classes for the missing NonlinearFormIntegrators. These classes should define the local gradients. Then they are attached to the NonlinearForm and it takes care of the rest, you don't need to reimplement Mult() or GetGradient().
- As in ex10, create a new Operator (or NonlinearForm) class and implement Mult() and GetGradient() yourself. In this case, for GetGradient(), you can return a BilinearForm that contains a ConvectionIntegrator (was that your question?).

Both approaches result in an Operator, which is then given to a NewtonSolver. Alternatively, you can wait for the upcoming MFEM release, which will support PETSc nonlinear solvers (i.e. the Operator can be given to a PETSc solver).

I hope this helps,
Vladimir

**Comment by juan42** [comment]
Thanks, that makes it clearer.

I still do not understand if the ConvectionIntegrator would suffice as a nonlinear term (numerically it is just < grad(u)*u, v >). Would i project the old solution u to a VectorGridFunction and then use that as a Coefficient for the ConvectionIntegrator for the nonlinear term?

And for
`<grad(du)*u, v> + <grad(u)*du, v>`
with u, p as functions and v, q as trial functions and du, dp as test functions. Assembling <grad(du)*u, v> is straight forward, since it is the form the Integrator is implemented. How would i assemble the second term <grad(u)*du, v>?

**Comment by vladotomov** [comment]
Yes, you can add a ConvectionIntegrator to the NonlinearForm that represents F(u). This ConvectionIntegrator can have a VectorGridFunctionCoefficient that is linked to the current u (you want your Coefficient to change as u gets updated by the NewtonSolver).

<grad(u) du, v> can be done with VectorMassIntegrator. You'll need to create a new MatrixCoefficient class that takes a vector GridFunction and computes the gradient, see coefficient.hpp. I don't think such coefficient exists right now.

I hope this helps, good luck,
Vladimir

**Comment by juan42** [comment]
> This ConvectionIntegrator can have a VectorGridFunctionCoefficient that is linked to the current u (you want your Coefficient to change as u gets updated by the NewtonSolver).

Okay thats exactly how i understood that.

Regarding the second term which is the linearized version of the ConvectionIntegrator. I need to implement this for the Jacobian, correct?
Or does GetGradient() called on a NonlinearForm (or Operator) including the ConvectionIntegrator give me magically the Jacobian for the ConvectionIntegrator term?! I mean, you'd have to do similar things in BLAST for the Euler equations, or am i wrong?

Thanks for the help!

**Comment by vladotomov** [comment]
I see, let me align the discussion with the two approaches from my second reply.

1. Using the existing NonlinearForm class; you can attach the <grad(u)*u, v> ConvectionIntegrator as discussed and it will give the correct F(u), but that integrator won't have the correct AssembleElementGrad() method, so the GetGradient() won't give the correct J. In this case you can write a new NonLinearFormIntegrator, similar to ConvectionIntegrator, but with a different AssembleElementGrad() that computes <grad(du)*u, v> + <grad(u)*du, v> in a zone. That's probably what I would do.
2. Creating a new NonlinearForm class; again you can attach the <grad(u)*u, v> ConvectionIntegrator (and other BilinearFormIntegrators) as discussed and use them for Mult(). For your custom GetGradient(), however, you'll need to return a BilinearForm that includes the mentioned <grad(du)*u, v> ConvectionIntegrator, the <grad(u) du, v> VectorMassIntegrator, and the other BilinearFormIntegrators involved in J.

So there is no magic, both cases need the computation of grad(u) at some point.
Let me know if you have further questions.

**Comment by juan42** [comment]
Thanks again for the detailed explanations! I think i understand the process now :+1:

**Comment by jandrej** [comment]
If you have questions about implementation details you can contact me at juan [at] tf.uni-kiel.de.
