### ISSUE TITLE
GetFaceToAllElementTable()->Print() returns 3 neighbors [bug?]

### ISSUE THREAD

**Issue by ztdepztdep** [mfem/mfem#1020]
I load  a 3D mesh from gmsh with ParMesh. When i use "GetFaceToAllElementTable()->Print() ", it gives a wrong line with:
........
.......
[row 15]
    4    7
[row 16]
    5   11    2
..........
   I think in a conforming mesh, it is absolute a wrong results.

**Comment by tzanio** [comment]
Is this a serial or parallel mesh? Conforming or non-conforming? Can you attach the mesh file?

**Comment by ztdepztdep** [comment]
I still cann't find the reason. 
  The mesh on the CPU=0 still reports  an face with 3 neighbours.
   " 0 8 28"
  
    It is a parallel conforming mesh created from a serial mesh with  3 CPUs.  The serial mesh was created by    reading the FLUENT mesh file.  Attachment please fine the mesh file created with mfem. 
   Would you please have a try with the attachment.



[output.tar.gz](https://github.com/mfem/mfem/files/3638190/output.tar.gz)

**Comment by tzanio** [comment]
A quick look shows that there some issues with this mesh, e.g. some shared faces are missing).

If you are still interested, I can try to investigate further, but something must be wrong with the process that has generated it...
