### ISSUE TITLE
Elasticity using MFEM: Questions on essential BCs on single nodes and derived field quantities

### ISSUE THREAD

**Issue by anandembar** [mfem/mfem#1022]
I'm new to MFEM. I'm initially trying to solve elasticity problems (similar to example 2, but different problem and domain definitions). I have a couple of questions on modeling and post-processing.

**1.** I see that it is possible to mark any boundary with an attribute so as to apply essential BCs (on any or all available degrees-of-freedom at that boundary). However, is it possible to apply essential boundary conditions on a single node? Can you please give an example of how this can be done?

**2a.** How can derived field quantities such as as stress and strain (tensor quantities computed from the gradients of the vector displacement field) be obtained from the displacement solution? Can you please share an example?

**2b.** Once these quantities are computed at integration points, how can they be extrapolated to the nodes and plotted for viewing in GLVis? Can you share an example of how this can be done?

Thank you,
Anand

**Comment by barker29** [comment]
To answer your question 1, I have used code like the below to fix node 0 in an elasticity problem:
```c++
   Array<int> ess_tdof_list;
   const int node = 0;
   if (fespace->GetOrdering() == Ordering::byNODES)
   {
      int num_oned_dofs = fespace->GetVSize() / space_dim;
      for (int i=0; i<space_dim; ++i)
      {
         ess_tdof_list.Append(num_oned_dofs*i + node);
      }
   }
   else
   {
      for (int i=0; i<space_dim; ++i)
      {
         ess_tdof_list.Append(space_dim*node + i);
      }
   }
```
Something like this could replace section 8 in `ex2.cpp`. Note that this will not work in parallel.

**Comment by anandembar** [comment]
Thanks Andrew! 

Just so that we are not limited by actual node numbers to apply the Dirichlet boundary condition, is there a method to obtain node numbers near a given coordinate?

Thank you,
Anand

**Comment by barker29** [comment]
Unfortunately that is not easy in general - in the worst case you may have to loop over the elements of the mesh to find it.

**Comment by anandembar** [comment]
OK, thanks Andrew!

**Comment by tzanio** [comment]
Thanks Andrew!
