### ISSUE TITLE
save and restore parallel mesh

### ISSUE THREAD

**Issue by januszpigonia** [mfem/mfem#1023]
I'm trying to read (in parallel) ParMesh with the code:

```c++
      ostringstream mesh_name;
      mesh_name << "mesh." << setfill('0') << setw(6) << myid;
      ifstream mesh_ifs(mesh_name.str());
      ParMesh *pmesh = new ParMesh(MPI_COMM_WORLD,mesh_ifs);
```

and get the error:

```
Verification failed: (ident == "communication_groups") is false:
 --> input stream is not a parallel MFEM mesh
 ... in function: mfem::ParMesh::ParMesh(MPI_Comm, std::istream&, bool)
 ... in file: /home/januszk/MFEM/mfem-4.0/mesh/pmesh.cpp:913
```

I'm new in mfem. Could You help me ?
Janusz
ps.
The ParMesh was written with ex1p

**Comment by v-dobrev** [comment]
Hi @januszpigonia,

The output saved by ex1p does not use the parallel mesh format -- this is sufficient for visualization but not if you want to read back the mesh as a `ParMesh` object.

To save the  `ParMesh` using the parallel format use the method `ParMesh::ParPrint`. Then you should be able to read it with the code above to recover the `ParMesh` object.
