### ISSUE TITLE
Constness in Array

### ISSUE THREAD

**Issue by delyank** [mfem/mfem#1026]
It seems impossible to declare something like

`mfem::Array<const int> array; `

My understanding is that the compiler complains due to the lack of proper "new" and "delete" in the Memory class for the const type, even though no actual allocation is ever performed.

The usefulness of such declaration is in case the Array structure is used in conjunction with `inline void MakeRef(T *, int)`, to access some const data coming from another place.

It would be nice if this could work out of the box without the need to declare `mfem::Array<int> array; ` and use a const_cast. However, in general, this may lead to an ambiguity in the use of `MakeDataOwner()`, if no "delete" is implemented.

This can possibly be resolved by putting the const_cast-s in the Array or Memory classes, since mostly there is no difference in handling const or non-const data on memory level.

**Comment by mlstowell** [comment]
Hello, @delyank ,
The `mfem::Array` class is simply our version of an `std::vector` and these don't allow `const` elements either.  Trying to support `const` element types leads to a variety of issues the first one might be how does one assign values to such as array?  For example, if you declare an array of some length:
```
mfem::Array<const int> array(10);
array[0] = 1; // This will fail because the entries of array cannot be altered.
```

In my opinion the `const_cast` you're trying to avoid should not be avoided.  If the data you're trying to access is `const` then you need to make sure you don't alter it.  Wrapping an `Array` object around it is fine but you need to be careful.  Perhaps the following would suffice:
```
const Array<int> array(const_cast<int*>(data), size);
```
I suppose you're thinking that the following should be allowed:
```
const Array<const int> array(data, size);
```
It seems that this would disable most of what the `Array` class can do.  Perhaps there's another way to provide the functionality you need.  What methods of `Array` were you hoping to use? 

Best wishes,
Mark

**Comment by delyank** [comment]
Hi Mark,

This is an interface issue. For example, a function provides a basic array as `const int *` and another function takes an argument `Array<T>`. So the Array acts only as a container of values to be used by the function and nothing else is expected.

`Array<const int>` is to `const Array<int>` as `const int *` is to `int * const`. I have no problem to go with the const cast. It is slightly disappointing that high-level objects cannot easily imitate the behavior of basic types. E.g., it makes perfect sense for a function to be declared with a parameter of type `Array<const int>` indicating read-only access to the entries of the array, while still accepting arguments of type `Array<int>` via obvious implicit casting.

I wasn't sure if it is a C++ limitation.

Thanks!

**Comment by mlstowell** [comment]
Hello, @delyank ,

Actually, I don't believe it does make sense to declare a function parameter with a type `Array<const int>&` (I assume the reference was implied). If the function  wants read-only access to the entries of the container it should declare the argument as `const Array<int>&`.  The first option would suggest that it's okay for the function to alter the container in any way at all as long as it's entries don't change but this seems unrealistic.  The second option, `const Array<int>&`, means the function cannot change the container or its contents.

I'm curious about how an "actual container" with const type data would be used.  I don't think this is a limitation of C++.  I expect such a container could be implemented although not using `mfem::Array` or `std::vector` because these containers have different requirements (like being able to resize, for example).  How would you initialize such a container for example?  What functions would it need to support aside from element access?  Why not just use `const int *`?

By the way, I would not be at all surprised to find functions in MFEM that take `Array<int>&` arguments when they really should use `const Array<int>&`.  If you've found one of these, or if there's some other awkward interface in MFEM, please let us know.  I'd be happy to try to make things more user-friendly or const-correct.

Best wishes,
Mark

**Comment by v-dobrev** [comment]
@delyank, what is the error you get when you declare `mfem::Array<const int> array;`?

**Comment by delyank** [comment]
> @delyank, what is the error you get when you declare `mfem::Array<const int> array;`?

The compiler is gcc version 7.4.0

```
In file included from mfem-4.0/general/device.hpp:16:0,
                 from mfem-4.0/mfem.hpp:18,
                 from parelag/src/elag_typedefs.hpp:17,
                 from parelag/src/elag.hpp:19,
                 from parelag/examples/Upscaling0FormMFEM.cpp:21:
mfem-4.0/general/mem_manager.hpp: In instantiation of ‘void mfem::Memory<T>::New(int) [with T = const int]’:
mfem-4.0/general/array.hpp:59:33:   required from ‘mfem::Array<T>::Array(int) [with T = const int]’
parelag/examples/Upscaling0FormMFEM.cpp:31:24:   required from here
mfem-4.0/general/mem_manager.hpp:231:14: error: uninitialized const in ‘new’ of ‘const int’
    { h_ptr = new T[size]; capacity = size; flags = OWNS_HOST | VALID_HOST; }
              ^~~~~~~~~~~
mfem-4.0/general/mem_manager.hpp: In instantiation of ‘void mfem::Memory<T>::Delete() [with T = const int]’:
mfem-4.0/general/array.hpp:76:22:   required from ‘mfem::Array<T>::~Array() [with T = const int]’
parelag/examples/Upscaling0FormMFEM.cpp:31:24:   required from here
mfem-4.0/general/mem_manager.hpp:545:31: error: invalid conversion from ‘const void*’ to ‘void*’ [-fpermissive]
        MemoryManager::Delete_(h_ptr, flags) == MemoryType::HOST)
                               ^~~~~
mfem-4.0/general/mem_manager.hpp:414:22: note:   initializing argument 1 of ‘static mfem::MemoryType mfem::MemoryManager::Delete_(void*, unsigned int)’
    static MemoryType Delete_(void *h_ptr, unsigned flags);
                      ^~~~~~~
```

**Comment by delyank** [comment]
Thank you, Mark. Your have a good point. It really seems that the most reasonable general approach is the one you suggested:

`const Array<int> array(const_cast<int*>(data), size);`

since it involves no practical loss of "constness".

> Why not just use `const int *`?

Excellent question. I guess it is a small design weakness we have but we live with it.

I have no issue with MFEM particularly. I was just wondering if something like this might seem reasonable. The thing is that once you improved on const-correctness in MFEM 4.0 this interestingly came up in a part of another code we have, that was in a way dependent on this lack of const-correctness. Seems like bad const-correctness can propagate to the user codes.

**Comment by v-dobrev** [comment]
Hi @delyank,

I made a branch that should fix the issue and allow `Array<const int>` objetcs -- see https://github.com/mfem/mfem/tree/array_const_int_fix.

Can you try it with your original code?

**Comment by delyank** [comment]
@v-dobrev 

Yes, it works. Thanks!
