### ISSUE TITLE
GridFunction::ProjectBdrCoefficient for 3D nonconforming mesh

### ISSUE THREAD

**Issue by QikLiang** [mfem/mfem#1027]
I want to project a `PWConstCoefficient` on to the boundary of `GridFunction`. For 2D and conforming 3D meshes, the approach in https://github.com/mfem/mfem/commit/db3c027d156c39d175456459fe552e95f840a763 produces correct results. However, for a 3D nonconforming mesh, it seems that the `Coefficient` I've created will also need to handle the edges of the boundary faces. I don't see any functions in `Mesh` or `NCMesh` that does a similar thing to `Mesh::GetBdrElementAdjacentElement` for edge elements. Is there any way around this?

For the purpose of `PWConstCoefficient`, I can use `Mesh::GetVertexToElementTable` because all I need is the element attribute, but it would be nice to have a more general solution. There doesn't seem to be an easy way to transform a Segment's integration point into a tetrahedron or hexahedron's integration point.

**Comment by tzanio** [comment]
@jakubcerveny, can you help with this?

**Comment by jakubcerveny** [comment]
@QikLiang, do you have a sample code to demonstrate the problem on an NCMesh? I think I might have an idea why you need to project on edges but I would like to be sure and also have something to test on.

**Comment by QikLiang** [comment]
@jakubcerveny 

I have a `GridFunction` phi_ that contains the electric potential at each point in the mesh, and a `Coefficient*` epsCoef_ that similarly contains the dielectric coefficient. To calculate the charge on every boundary, I integrate `epsCoef * phi_ \cdot n` on the boundary using the `BoundaryNormalLFIntegrator`. To that end, I have implemented my own `BdrCoefficient` and `BdrVectorCoefficient` classes which override `Eval` to convert `ElementTransformation`s on the boundary to the boundary's adjacent mesh element. I concluded on this solution as the result of discussions in #993 .

The code for my use case:
```
GridFunction eps_(H1FESpace_);
eps_ = 0;
Array<int> bdr_attr(num_bdr);
bdr_attr = 1;
BdrCoefficient eps_bdr(epsCoef_, mesh_);
eps_.ProjectBdrCoefficient(eps_bdr, bdr_attr);
double *results = new double[num_bdr];

BdrVectorCoefficient egridfunc(new GradientGridFunctionCoefficient(phi_), mesh_);
for(int i=0; i<num_bdr; i++){
  LinearForm lf_bdr(H1FESpace_);
  bdr_attr = 0;
  bdr_attr[i] = 1;
  lf_bdr.AddBoundaryIntegrator(new BoundaryNormalLFIntegrator(egridfunc), bdr_attr);
  lf_bdr.Assemble();
  results[i] = lf_bdr(eps_);
}
```
Implementation of `BdrCoefficient::Eval` and `BdrVectorCoefficient::Eval`:
```
double BdrCoefficient::Eval(ElementTransformation &T, const IntegrationPoint &ip){
    if (mesh_->Dimension() == T.GetDimension())
    {
        return coef->Eval(T, ip);
    }
    else if (mesh_->Dimension()==3 && T.GetGeometryType() == Geometry::SEGMENT)
    {
        // (re)create vertex to element table if outdated or doesn't exist
        if(vert_to_el==NULL || mesh_sequence!=mesh_->GetSequence()){
            if(vert_to_el != NULL){
                delete vert_to_el;
            }
            vert_to_el = mesh_->GetVertexToElementTable();
            mesh_sequence = mesh_->GetSequence();
        }
        // a segment always have two vertices
        const int num_vert = 2;
        Array<int> vert(num_vert);
        mesh_->GetEdgeVertices(T.ElementNo, vert);
        int num_el[num_vert];
        int *el[num_vert];
        for(int i=0; i<num_vert; i++){
            num_el[i] = vert_to_el->RowSize(vert[i]);
            el[i] = vert_to_el->GetRow(vert[i]);
        }
        int num_shared_el = 0;
        double result = 0;
        for(int first_el=0; first_el<num_el[0]; first_el++){
            for(int second_el=0; second_el<num_el[1]; second_el++){
                if(el[0][first_el]==el[1][second_el]){
                    num_shared_el++;
                    // TODO: add integration point transformation
                    T.Attribute = mesh_->GetAttribute(el[0][first_el]);
                    result += coef->Eval(T, ip);
                    break;
                }
            }
        }
        if(num_shared_el>0){
            result /= num_shared_el;
        }
        return result;
    }
    else // Assuming T is a boundary element transformation:
    {
        int el_id, el_info;
        mesh_->GetBdrElementAdjacentElement(T.ElementNo, el_id, el_info);
        IntegrationPointTransformation loc_T;
        mesh_->GetLocalFaceTransformation(mesh_->GetBdrElementType(T.ElementNo),
                                          mesh_->GetElementType(el_id),
                                          loc_T.Transf, el_info);
        IntegrationPoint eip;
        loc_T.Transform(ip, eip);
        ElementTransformation *newT = mesh_->GetElementTransformation(el_id);
        newT->SetIntPoint(&eip);

        return coef->Eval(*newT, eip);
    }
}

void BdrVectorCoefficient::Eval(Vector &V, ElementTransformation &T,
                                const IntegrationPoint &ip){
    if (mesh_->Dimension() == T.GetDimension())
    {
        coef->Eval(V, T, ip);
    }
    else if (mesh_->Dimension()==3 && T.GetGeometryType() == Geometry::SEGMENT)
    {
        // this part, while not working, never gets called, so I don't have a problem with it
        assert(false && "Can't project to the boundary of a 3D nonconforming mesh");
    }
    else // Assuming T is a boundary element transformation:
    {
        int el_id, el_info;
        mesh_->GetBdrElementAdjacentElement(T.ElementNo, el_id, el_info);
        IntegrationPointTransformation loc_T;
        mesh_->GetLocalFaceTransformation(mesh_->GetBdrElementType(T.ElementNo),
                                          mesh_->GetElementType(el_id),
                                          loc_T.Transf, el_info);
        IntegrationPoint eip;
        loc_T.Transform(ip, eip);
        ElementTransformation *newT = mesh_->GetElementTransformation(el_id);
        newT->SetIntPoint(&eip);

        coef->Eval(V, *newT, eip);
    }
}
```

The code above works if epsCoef is type `PWConstantCoefficient`, but not if it's type `FunctionCoefficient` since I can't extract the coordinate information. Ultimately, I think this should be handled by the MFEM library itself within `GridFunction::ProjectBdrCoefficient` and `LinearForm::AddBoundaryIntegrator` instead of having users implement their own solution. However, as #993 states that "It's not exactly a bug in MFEM", I have simply tucked these two classes into my own project.

**Comment by v-dobrev** [comment]
When `epsCoef_` is a `FunctionCoefficient` you do not need to wrap it as a `BdrCoefficient` in order for the call `eps_.ProjectBdrCoefficient(eps_bdr, bdr_attr);` to work. In other words, you should be able to just call `eps_.ProjectBdrCoefficient(epsCoef_, bdr_attr);` and that should work with AMR meshes as well. If your `FunctionCoefficient` has discontinuities then the projection will pick one of the sides of the discontinuity which may vary due to numerical roundoff. Do you have such discontinuities?

Regarding the extraction of coordinate information: if you have an `ElementTransformation T;` and an `IntegrationPoint ip;` then you can compute the physical coordinates with `T.Transform(ip, x);` where `x` is a `Vector`.

**Comment by jakubcerveny** [comment]
I agree the user shouldn't have to do this.

I am also not a fan of using volume elements to get values on boundary elements, not to mention boundary edges, that is pretty ugly and slow. What about adding the methods `GridFunction::GetBdrValue` and `GridFunction::GetEdgeValue`, and calling these in case the transformation is for a lower dimensional entity? @v-dobrev?

It would also be ideal if the second half of `GridFunction::AccumulateAndCountBdrValues` didn't have to invoke evaluations on edges. To get the hidden master DOFs, maybe we could evaluate slave edge values from DOFs already obtained above in that method? Or get the inverse of the slave interpolation somehow? That's non-trivial though.

**Comment by v-dobrev** [comment]
There is a PR (#716) that extends `(Vector)GridFunctionCoefficient`s to work with boudary transformations. It also includes methods for evaluating `GridFunction`s on the boundary -- there are a few versions of those, e.g. if the space is DG, you have to go through the volume. I think the edges can be handled in a similar manner.

**Comment by jakubcerveny** [comment]
#716 looks good except the huge number of versions of GetXXXValues, even just the header file is overwhelming. Do we really need all of those combinations? Something seems wrong. And we would need to add more... (GetEdgeValue)

**Comment by tzanio** [comment]
Discussion continued in #716.
