### ISSUE TITLE
Nodes on cube / square geometries for serendipity elements

### ISSUE THREAD

**Issue by akgillette** [mfem/mfem#1029]
I’m working on the implementation of H^1-conforming serendipity elements in 3D on cubes.  As discussed in previous MFEM meetings, I need to control how nodes are associated to faces of the cube.   My understanding is that nodes are determined by the `IntegrationRule Nodes` object associated to a  `FiniteElement` object and should be defined as part of the constructor for the `FiniteElement` object.

However, I’ve found that the ability to run, e.g., ex1 does not require a definition of `Nodes` for the  `FiniteElement` objects that are created.  In particular, changing the definition of the `Nodes` for the square and cube objects seemingly has no effect on the result of the computation.

My question is this: How is MFEM getting continuity between elements without invoking the location of nodes for the relevant basis?  Is there some default assumption about node locations on objects of a given geometry?  Thanks for any guidance!

**Comment by v-dobrev** [comment]
The connectivity between elements is described by the `FiniteElementCollection` classes. The only expectation from the `FiniteElement` classes is the local ordering of the dofs/basis functions -- they need to be ordered by association: first vertex dofs, then edge dofs, then face dofs, and finally interior dofs. The "collection" classes provide information about the dofs associated with a given mesh entity -- vertex, edge, face, or interior. These are the virtual methods  `FiniteElementForGeometry`, `DofForGeometry`, and `DofOrderForOrientation` in class `FiniteElementCollection`. These methods along with the assumed local dof ordering in a `FiniteElement` class are used in the method `FiniteElementSpace::GetElementDofs` (and other similar methods) to create a global numbering (for the local dofs in an element) that ensures the global conformity of the space. This construction does not use in any way the coordinates that are defined in the `Nodes` member of `FiniteElementSpace`.

**Comment by akgillette** [comment]
Thanks - that was helpful.  In the case of an order 5 serendipity element, there are 3 DoFs per face.  Suppose I had three basis functions per face that were identically zero on every edge and identically zero on every face except one and that the functions were nodal with respect to three points on the interior of that face (e.g (.25, .5, 0), (.5, .5, 0) and (.75,.5, 0) on the bottom face).  Would this produce a conforming result?

**Comment by v-dobrev** [comment]
For general meshes, the face basis functions need to be "symmetric" in the following sense:

1) If `B1={f1,f2,f3}` is the basis for the bottom face, is it true that `span(B1)=span(B2)` where `B2={g1,g2,g3}` is the basis `B1` rotated by 90 degrees around the center of the bottom face?

If this is true, then defining a globally conforming space is, in principal, possible. In MFEM, we need an additional condition:

2) Assuming 1, the change of basis matrix from `B1` to `B2` must be a permutation matrix or a permutation matrix where some of the `1` entries are replaced with `-1`.

If 1 is true but 2 is not, then the question will be if there is a different basis choice that will also satisfy 2.

**Comment by akgillette** [comment]
Great!  To satisfy conditions 1 and 2, the easiest thing to do would be to use a hierarchical Legendre basis.  In this case, `B1` can be seen in the attached screenshot - it’s a bubble function and two Legendre-weighted bubble functions, with different orientations (note that yellow = 0 on the color scale for the right two visualizations).  In fact, when using this basis I see the correct convergence *rates* in L^2 and H^1, despite seeing very bad errors (e.g. order 10^12, when it should be something like order 10^(-6)).  This leads me to think it may just be a matter of finding the right place to replace a `1` entry with a `-1`, as you suggest.

Can you point me to where in the code the permutation matrix is effectively computed or applied?

![order5-face-basis](https://user-images.githubusercontent.com/6138873/62737975-faed0f00-b9e5-11e9-809c-bbfc331dddd0.png)
