### ISSUE TITLE
Applying non zero dirichlet in parallel

### ISSUE THREAD

**Issue by juan42** [mfem/mfem#103]
The question is somehow related to #80. When i try apply dirichlet boundary conditions for block operators in parallel, i cannot find a way to "project" them to the true dofs.

Lets say i have a mixed finite element formulation like in #80.

```c++
  FiniteElementCollection *vel_fecoll(new H1_FECollection(2, dim));
  FiniteElementCollection *pres_fecoll(new H1_FECollection(1, dim));

  ParFiniteElementSpace *V_space =
      new ParFiniteElementSpace(pmesh, vel_fecoll, dim);
  ParFiniteElementSpace *Q_space =
      new ParFiniteElementSpace(pmesh, pres_fecoll, dim - 1);
```
Then i define the block offsets
```c++
  Array<int> block_offsets(3); // number of variables + 1
  block_offsets[0] = 0;
  block_offsets[1] = V_space->GetVSize();
  block_offsets[2] = Q_space->GetVSize();
  block_offsets.PartialSum();

  Array<int> block_trueOffsets(3); // number of variables + 1
  block_trueOffsets[0] = 0;
  block_trueOffsets[1] = V_space->GetTrueVSize();
  block_trueOffsets[2] = Q_space->GetTrueVSize();
  block_trueOffsets.PartialSum();
```
where the true size is the number of vector dofs without ghosted nodes, correct?
Then i define a parallel gridfunction which projects values of a function defined in bdr_vcoeff.
```c++
  BlockVector x(block_offsets), rhs(block_offsets);
  BlockVector trueX(block_trueOffsets), trueRhs(block_trueOffsets);

  ParGridFunction x_bdr;
  x_bdr.MakeRef(V_space, x.GetBlock(0), 0);
  x_bdr.ProjectCoefficient(bdr_vcoeff);
```
Then for example i'd like to use some kind of "EliminateBC" function on the variational form
```c++
  ParBilinearForm *aVarf(new ParBilinearForm(V_space));
  aVarf->AddDomainIntegrator(new VectorDiffusionIntegrator());
  aVarf->Assemble();
  aVarf->EliminateEssentialBC(ess_bdr, x_bdr, rhs.GetBlock(0));
  aVarf->Finalize();
  HypreParMatrix *A = aVarf->ParallelAssemble();
```
After that i just assemble the B/BT operators like in the darcy example (ex5p).
The solver call uses the trueRhs and trueX BlockVectors.
```c++
  solver.Mult(trueRhs, trueX);
```
The Serial example works fine for me with non zero dirichlet. My question is now, how do i "project" the x and rhs BlockVectors to parallel trueRhs and trueX vectors? Maybe the approach i'm taking is totally out of place here.

The problem that occurs is a bunch of NaN's in the trueRhs when i naively try something like
```c++
V_space->Dof_TrueDof_Matrix()->MultTranspose(rhs.GetBlock(0), trueRhs.GetBlock(0));
```

Appreciate your help.

Regards
Julian

**Comment by juan42** [comment]
After alot of fiddling around, the following works.
```c++
  HypreParVector *X_BDR_V = x_bdr.ParallelProject();
  HypreParVector *B_BDR_V = x_bdr.ParallelProject();
  aVarf->ParallelEliminateEssentialBC(ess_dof, *A, *X_BDR_V, *B_BDR_V);

  trueX.GetBlock(0).Set(1.0, *X_BDR_V);
  trueRhs.GetBlock(0).Set(1.0, *B_BDR_V);

  HypreParVector *X_BDR_P = x_bdr_p.ParallelProject();
  HypreParVector *B_BDR_P = x_bdr_p.ParallelProject();

  trueX.GetBlock(1).Set(1.0, *X_BDR_P);
  trueRhs.GetBlock(1).Set(1.0, *B_BDR_P);
```
I found this solution in the [volta miniapp](https://github.com/mfem/mfem/blob/125ff226e4a8c50fb3aa9a77e871d41bc6b4b60b/miniapps/electromagnetics/volta_solver.cpp#L365).

Is this the intended way of handling dirichlet in parallel for block operators?

**Comment by tzanio** [comment]
Hi Julian,

Yes, this is one way to transition between parallel grid function and hypre vectors.

A more general/flexible way is the 'FormLinearSystem()/RecoverFEMSolution()` interface as in https://github.com/mfem/mfem/blob/master/examples/ex1p.cpp#L185. In the upcoming 3.3 release Volta has been updated to use that instead of the lines you mentioned.

Note that if you are solving a mixed problem you also need to eliminate the BC in the off-diagonal block. This is done with the methods `EliminateTestDofs` and/or `EliminateTrialDofs` of the `MixedBilinearForm` class as explained in #80.

Hope this helps,
Tzanio
