### ISSUE TITLE
Memory Class in Dense Matrix

### ISSUE THREAD

**Issue by artv3** [mfem/mfem#1035]
Hi all, 

Would you kindly consider adding a memory class inside dense matrix. I have an application where data stored in dense matrix objects needs to make its way to the GPU. This would greatly simplify porting. 

Thanks,
Arturo Vargas

**Comment by v-dobrev** [comment]
Class `DenseTensor` already uses `Memory<double>` for its data: https://github.com/mfem/mfem/blob/18f0cf0873d9f5c941c747e73bbdd951bba7444c/linalg/densemat.hpp#L656-L660

**Comment by artv3** [comment]
Oops! I meant the Dense Matrix class. I don't know why I wrote Dense Tensor.....

**Comment by v-dobrev** [comment]
Can you explain what is your use case for `DenseMatrix` on GPU?

Typically, in MFEM `DenseMatrix` stores a small dense matrix, so launching GPU kernels just for that small matrix does not make sense.

**Comment by artv3** [comment]
In our application we use Dense Matrices to store pre-computed basis values at quadrature points. The data in the dense matrix may then be used for assembling operators, calculating coefficients etc... 

The alternative is that I try retrieving that data using the following methods (modern MFEM)

 ``` const FiniteElement *el = FESpace.GetFE(0);```
```  maps = &el->GetDofToQuad(*ir,DofToQuad::TENSOR);``` 

but I was hoping to make the changes incrementally.

**Comment by v-dobrev** [comment]
OK, I think I understand: the idea is NOT to implement/use `DenseMatrix` operations on GPU but just to use it as a container that can store small dense matrices on host/device. The actual operations with the data will be in larger kernels, separate from class `DenseMatrix`.

With such usage in mind, I think it makes sense to update `DenseMatrix` to use `Memory<double>` for its data.

**Comment by artv3** [comment]
Great! Awesome!

**Comment by tzanio** [comment]
Will be addressed further in the PR  #1049

**Comment by camierjs** [comment]
Will come with  PR #1104
