### ISSUE TITLE
integration 

### ISSUE THREAD

**Issue by januszpigonia** [mfem/mfem#1036]

**Comment by januszpigonia** [comment]
How can i simply integrate 0-form over the whole space ?
For instance in fenics i can use the command : assemble(u*dx) where u is gridfunction.

Janusz

**Comment by vladotomov** [comment]
I don't think we have a direct function to get the integral of `u`, but you can create a simple `LinearForm` (using the space of `u`) that has a `DomainLFIntegrator` with `Coefficient` 1. Then assemble the linear form and dot it with `u` to get the integral.

**Comment by tzanio** [comment]
To add to @vladotomov's answer -- it depends what other objects do you have built already in your application. 

For example, if you have the mass matrix M, you can compute the integral as 1^T M u, where 1 is a vector of ones.

The `LinearForm` approach above is also a good one, especially if you need the integral of several fields.

If you just need the integral and don't have any other pieces available, the most efficient computation will be to use something similar to `ComputeLpNorm` in `fem/coefficient.hpp` with a `GridFunctionCoefficient` for `u`, see https://github.com/mfem/mfem/blob/master/fem/coefficient.cpp#L584-L613.

Hope this helps,
Tzanio
