### ISSUE TITLE
Functionals?

### ISSUE THREAD

**Issue by jehicken** [mfem/mfem#1040]
Hi,

Is it possible to compute functionals with MFEM?  For example, we are interested in evaluating the force on an object immersed in a fluid.

One approach that we are considering is to define a `NonlinearForm` whose output vector we can sum to get the desired functional; however, this seems inefficient, especially when we start taking derivatives of functionals (in the case of `NonlinearForm`, we would have to temporally store a sparse matrix which we then contract).

Alternatively, we will create a new class derived from `Operator` that can compute functionals.

Thanks,
Jason

**Comment by vladotomov** [comment]
Hi Jason,

Have you considered the interface of `NonlinearFormIntegrator`, in particular `GetElementEnergy()`? Won't that be sufficient?

Vladimir

**Comment by jehicken** [comment]
Hi Vladimir,

I think `GetElementEnergy` would work for some functionals we would be interested in, but for lift and drag we would prefer an API that handles boundary faces.  It looks like this is anticipated but not yet implemented, correct?

Thanks,
Jason

**Comment by vladotomov** [comment]
Right, we don't have many examples of nonlinear forms on faces. I see that `AssembleFaceVector()` is implemented in ex18, but I don't know of any `AssembleFaceGrad` examples.

**Comment by jehicken** [comment]
Hi Vladimir,

Just to make sure we are on the same page, this is how functionals and their derivatives should be implemented:
* Define a functional as a `NonlinearForm`.
* Use `NonlinearForm::GetGridFunctionEnergy` to evaluate the functional.
* Use `NonlinearForm::Mult` to evaluate the partial derivative of the functional with respect to the states.

(I would really like to see the member function `NonlinearForm::GetGridFunctionEnergy` get renamed to something like `GetFunctional`, since the energy functional that arises in structural mechanics is just a special case.)

Would you like us to try adding the code to `GetGridFunctionEnergy` to include boundary and internal face integrators?  This seems like a potential enhancement that we might be able to help implement.

Best regards,
Jason

**Comment by vladotomov** [comment]
Yes, what you describe is a valid use of `NonlinearForm` (I happen to use it in exactly this way in a project). Note that the usual convention is to call `GetEnergy` that takes into account AMR and the use of parallel true dof vectors.

Of course, it would be great to implement the face and boundary contributions to `GetGridFunctionEnergy`, which are both left as TODO there.

**Comment by jehicken** [comment]
Ok, I will create a branch and add it.

Thanks,
Jason
