### ISSUE TITLE
How to set vertices in a mesh correctly / Connect elements to boundary elements 

### ISSUE THREAD

**Issue by kvoronin** [mfem/mfem#105]
Hello,

I've got a couple questions about meshing. I would appreciate any comments.

I am trying to create a mesh object on my own and have some troubles with vertices.
1) I'm trying to create a 4d mesh from a given 3d mesh. The algorithm is based on creating 4d elements from 3d mesh, looping over 3d elements. Handling a single 3d element I call "the local procedure". It takes a 3d element and produces several 4d elements for a 4d cylinder with the 3d element as a base. 

My question relates to creating boundary elements. I think I need to know which faces of the given 3d-element are the boundary elements. Then I will be able to understand whether I get any 4d boundary elements during the local procedure and define them.

But what should data structure can I use for it? The boundary elements seem to be independent from the elements array in mfem. I don't like the idea of massively searching in the boundary elements array for a particular vertex set (face of a given 3d element). Can I avoid that?

2) In the code below I tried to add four 3-d vertices to the created mesh, and as I see in the vertex-by-vertex output (using GetVertex()) it looks fine, but using GetVertices() it is not (got all zeros). What am I missing here? Must be smth really simple but I cannot get it.

```
#include <fstream>
#include <iostream>
#include <sstream>

#include "mfem.hpp"

using namespace std;
using namespace mfem;

int main (int argc, char *argv[])
{
    const char *mesh_file = "";

    int nDimensions = 3;

    Mesh *mesh;

    std::stringstream msg;
    msg << "Mesh dimension "   <<   nDimensions<< " \n";

    if (nDimensions == 3)
    {
        //mesh = new Mesh(1,1,1,mfem::Element::TETRAHEDRON,1);
        mesh = new Mesh(3,1,1,1,3);
    }
    else
    {
        std::cerr << "Case nDimensions = " << nDimensions << " is not supported" << std::endl;
        MPI_Finalize();
        return -1;
    }

    double * temppt;
    // adding the vertices from the slab to the mesh
    for ( int vert = 0; vert < 4; ++vert)
    {
        temppt = new double[3];
        temppt[0] = vert;
        temppt[1] = vert;
        temppt[2] = vert;
        mesh->AddVertex(temppt);
    }

    Vector vert_coord3d(3 * mesh->GetNV());
    mesh->GetVertices(vert_coord3d);

    int nv = mesh->GetNV();
    for ( int i = 0; i < nv; i++ )
    {
        for ( int j = 0; j < 3; j++ )
        {
            std::cout << vert_coord3d.GetData()[i + j*nv] << " ";
            //std::cout << vert_coord3d.GetData()[i](j) << " ";
        }
        std::cout<<std::endl;
    }

    double * tempp = new double[3];
    for ( int i = 0; i < nv; i++ )
    {
        std::cout << "vertex " << i << std::endl;
        tempp = mesh->GetVertex(i);
        for ( int j = 0; j < 3; j++ )
        {
            std::cout << tempp[j] << " ";
        }
        std::cout<<std::endl;
    }

    std::stringstream fname2;
    fname2 << "mesh0_after_exslot3.mesh";
    std::ofstream ofid2(fname2.str().c_str());
    ofid2.precision(8);
    mesh->Print(ofid2);


    return 0;
}
```
Thanks,
Kirill

**Comment by martemyev** [comment]
Hi Kirill,

Here is a quick fix for your issue:
```
@@ -18,21 +18,22 @@
     std::stringstream msg;
     msg << "Mesh dimension "   <<   nDimensions<< " \n";

+    int nVert = 4;
+
     if (nDimensions == 3)
     {
         //mesh = new Mesh(1,1,1,mfem::Element::TETRAHEDRON,1);
-        mesh = new Mesh(3,1,1,1,3);
+        mesh = new Mesh(3,nVert,1,1,3);
     }
     else
     {
         std::cerr << "Case nDimensions = " << nDimensions << " is not supported" << std::endl;
-        MPI_Finalize();
         return -1;
     }

     double * temppt;
     // adding the vertices from the slab to the mesh
-    for ( int vert = 0; vert < 4; ++vert)
+    for ( int vert = 0; vert < nVert; ++vert)
     {
         temppt = new double[3];
         temppt[0] = vert;
```

The thing is - when you created the `mesh` object with 1 vertex, the internal `vertices` array was allocated to this size (even though the actual number of vertices is 0 at the beginning). Later on, when you add vertices with `AddVertex()`, the `vertices` array is not expanded. If you rebuild the MFEM lib in the debug mode (with assertion enabled), your program will abort trying to add the second vertex.

Hope this helps.

Best,
Mikhail

**Comment by kvoronin** [comment]
Thanks, Mikhail!
It does fix. I was puzzled with how the vertex-be-vertex was working because it seemed that the same memory was used.

**Comment by kvoronin** [comment]
@martemyev, hope you could help me with another thing - what is a proper way to create a mesh not from the file but knowing all the elements, vertices and boundary elements (as in mfem meshes)?

It seems that if I print these three arrays into a file and read from it calling Mesh() from the file, the code works, but simply adding vertices, elements and boundary elements is not enough because some other internal data structures are not initialized. So, in the end I cannot call mesh->UniformRefinement(), for instance, getting a segfault.

Thanks,
Kirill

**Comment by martemyev** [comment]
Hi Kirill,

If you share the code that doesn't work that would be helpful to find out why you get a segfault. You're right that there are some extra initialisations besides vertices, elements and boundary elements, which may come into play when you call UniformRefinement. On another hand, if printing the mesh to a file and then reading from it initialises the mesh object as expected - why not to stick to that scenario? It shouldn't be a bottleneck from a performance viewpoint, unless you reinitialise the mesh many times.

Cheers,
Mikhail

**Comment by kvoronin** [comment]
Hi Mikhail,

At this moment, you are right, I should be satisfied with printing a mesh to a file and then reading from it, but later, for large meshes and parallel setup I am not sure about whether it won't take too much time. I guess then I will implement something as a derived friend class for mfem Mesh with something like a Mesh::Load routine but from my data arrays, not from a stream, in order to have a proper mesh structure generated.
I found a bug in the mesh generating routine which affects some further mesh handling routines, so now refinement and other things work well.

Thanks,
Kirill
