### ISSUE TITLE
SLI requires SPD preconditioner

### ISSUE THREAD

**Issue by ben-s-southworth** [mfem/mfem#1052]
The stationary linear iteration solver, i.e., fixed-point iteration, requires an SPD preconditioner because it prints the residual/checks stopping tolerance in the preconditioned norm, $$\langle B\mathbf{r},\mathbf{r}\rangle$$. If $$\langle B\mathbf{r},\mathbf{r}\rangle < 0$$, the iteration stops immediately. This is the simplest/most general iterative method though and should not have such a constraint.

Also, in SLI and CG (maybe others too, haven't checked), each iteration prints the current residual/error in inner-product form, which is the norm squared. Because stopping tolerance is usually based on the norm (not squared), I think this is misleading and suggest changing to printing $$\|\mathbf{r}\|_B$$ as opposed to $$\langle B\mathbf{r},\mathbf{r}\rangle$$ (or in the case of SLI, either $$\|\mathbf{r}\|$$ or $$\|B\mathbf{r}\|$$. 

I'm happy to make these changes and submit PRs, but want to check w/ MFEM team first.

**Comment by pazner** [comment]
I generally agree, and have also found the squared tolerances to be a source of confusion in the past (e.g. how the PCG wrapper function sets the tolerances to be the square root of the values that are passed in).

It seems reasonable that the SLI solver should measure convergence in something like the 2-norm of the residual vector.

**Comment by tzanio** [comment]
> Also, in SLI and CG (maybe others too, haven't checked), each iteration prints the current residual/error in inner-product form, which is the norm squared. Because stopping tolerance is usually based on the norm (not squared), I think this is misleading and suggest changing to printing $$|\mathbf{r}|_B$$ as opposed to $$\langle B\mathbf{r},\mathbf{r}\rangle$$ (or in the case of SLI, either $$|\mathbf{r}|$$ or $$|B\mathbf{r}|$$.

I generally agree with this, I'm just concerned that users may forget to update all their tolerances.

> The stationary linear iteration solver, i.e., fixed-point iteration, requires an SPD preconditioner because it prints the residual/checks stopping tolerance in the preconditioned norm, $$\langle B\mathbf{r},\mathbf{r}\rangle$$. If $$\langle B\mathbf{r},\mathbf{r}\rangle < 0$$, the iteration stops immediately. This is the simplest/most general iterative method though and should not have such a constraint.

What does *hypre* do? The SPD checks can be useful for debugging, but I agree that SLI should be general.

**Comment by ben-s-southworth** [comment]
_hypre_ just uses 2-norm of the residual for stopping tolerance.

In PCG, the tolerance is actually squared too in the function. So the check is if `betanom < r0`, where `betanom = Dot(r, z);` with preconditioning, or `betanom = Dot(r, r)` without, and `r0 = std::max(nom*rel_tol*rel_tol, abs_tol*abs_tol);`. So the current stopping tolerance is not squared, it's exactly what the user asks for, it's just odd that the squared error/residuals are printed.

**Comment by ben-s-southworth** [comment]
Made PR here: https://github.com/mfem/mfem/pull/1303
