### ISSUE TITLE
Stepping an ODESolver with multiple ParGridFunctions

### ISSUE THREAD

**Issue by jwscook** [mfem/mfem#1057]
I'm attempting to adapt ex18p.cpp to solve the incompressible Navier Stokes equations.

I'd like to make use of the `ODESolver` that are available, but because of this I need to put all my state variables into one `ParGridFunction` so that I can pass it to `ODESolver.Step`. This would be fine if all my state variables are `ParFiniteElementSpace` constructed with `FECollection` of the same `order`, but this is not the case: the pressure and velocity basis functions cannot be the same order.

Is there a way to enable timestepping via an `ODESolver` but for a `TimeDepenedentOperator` that holds multiple `FiniteElementSpaces` with `FECollections` of differing `order`?

Phrased alternatively, is there a way of re-writing the Euler example, `ex18p.cpp`, such that `fes` and `dfes` are constructed with `DG_FECollection` of unique `order`, e.g. orders of 3 and 2 respectively? I think the answer to this will enable to get to where I want to be.

**Comment by Dan2997925** [comment]
Hi James, if you look at the Joule example in miniapps/electromagnetics you will see that a scalar potential, an electric field, a magnetic field, a temperature, etc. are put in to a BlockVector. These physics fields are represented by different GridFunctions an can have different order. Since a BlockVector is derived from Vector, the TimeDependentOperator will work with this.

**Comment by jandrej** [comment]
Since you mentioned

> incompressible Navier Stokes equations

I'm guessing you want to implement the strong `div u = 0` condition. This means you are not solving an ODE but rather an index-2 Differential Algebraic Equation in Hessenberg form. This formulation is not supported by `ODESolver`.

**Comment by jwscook** [comment]
Thanks Both. I'll pursue the approach taken in the `Joule` example in `miniapps/electromagnetics`.

**Comment by tzanio** [comment]
Thanks Dan and Julian!
