### ISSUE TITLE
How to define (\nabla u, \nabla v) for given u?

### ISSUE THREAD

**Issue by fanronghong** [mfem/mfem#1059]
Hi all,

I want to compute `(\nabla u, \nabla v)`, where u is a given `GridFunction` and v is a test function.
I think it's like `ConvectionIntegrator`, but it's for `BilinearForm`. Here we must use `LinearForm`, right?

**Comment by mlstowell** [comment]
Hello, @fanronghong ,

This looks like the `DiffusionIntegrator`.  You can build a `BilinearForm` using the `DiffusionIntegrator` and then use this as an operator on the `GridFunction` u.  The resulting vector will be the linear form `(\nabla u, \nabla v)`.

The relationship between `LinearForms` and `BilinearForms` is explained with a little more detail on  [this page](https://mfem.org/pri-dual-vec/#technical-details).

Bests wishes,
Mark

**Comment by fanronghong** [comment]
Hi @mlstowell , sorry to reply you so late.

What do you mean by "use this as an operator on the `GridFunction u`"?

I write a simple demo below.
```
#include <iostream>
#include "mfem.hpp"

using namespace std;
using namespace mfem;

int main()
{
    Mesh mesh(4, 1.0);
    int dim = mesh.Dimension();

    H1_FECollection h1_fec(1, dim);
    FiniteElementSpace h1_space(&mesh, &h1_fec);

    GridFunction uh(&h1_space);
    ConstantCoefficient one(1);
    uh.ProjectCoefficient(one);
    GridFunctionCoefficient u_coeff(&uh);

    LinearForm rhs(&h1_space);
    rhs.AddDomainIntegrator(new DiffusionIntegrator); // This is not right!!!
    rhs.Assemble();
}
```

**Comment by fanronghong** [comment]
Hi @mlstowell ,

After thinking, I think the below code is what you're saying. Am I right?
```
#include <iostream>
#include "mfem.hpp"

using namespace std;
using namespace mfem;

int main()
{
    Mesh mesh(4, 1.0);
    int dim = mesh.Dimension();

    H1_FECollection h1_fec(1, dim);
    FiniteElementSpace h1_space(&mesh, &h1_fec);

    GridFunction uh(&h1_space);
    ConstantCoefficient one(1);
    uh.ProjectCoefficient(one);
    GridFunctionCoefficient u_coeff(&uh);

    BilinearForm dummy(&h1_space);
    dummy.AddDomainIntegrator(new DiffusionIntegrator(one));
    dummy.Assemble();
    dummy.Finalize();
    LinearForm rhs(&h1_space);
    dummy.Mult(uh, rhs); // Now rhs is just (\nabla u, \nabla v), right?
}
```

If I am right, you can close the issue. Thank you @mlstowell .

**Comment by tzanio** [comment]
Yes, in your code example the i'th entry of the vector `rhs` will contain `(\nabla uh, \nabla phi_i)` where `phi_i` is the i'th basis function in `h1_space`.
