### ISSUE TITLE
Question for a posteriori error estimater of Maxwell’s equations with nonlinear reluctivity function

### ISSUE THREAD

**Issue by ShiyangZhang** [mfem/mfem#106]
Dear all,

I am working on the following  systems.
∇ × (ν(x, |∇ × u|)∇ × u) = f in Ω
∇ · u = g in Ω
u × n = 0 on ∂Ω,
MFEM is a wonderful tool for this problem and thanks for sharing it.
And is there  tools implementing the  a posteriori error estimate?
specifically, is there any tool for the jump  [∇ × (ν(x, |∇ × u|)∇ × u) ×  N_F ] and the jump [u* N_F] when Nedelec elements are used?  Here N_F is normal unit vector of faces and u is a GridFunction. for simplicity,   ν(x, |∇ × u|)=exp(|∇ × u|).

Best,

Shiyang

**Comment by tzanio** [comment]
Hi Shiyang,

We don't have these non-linear terms, but there is some basis error estimation support in the classes derived from `AbstractErrorEstimator`, see `fem/estimators.?pp`. See the Tesla miniapp in `miniapps/electromagnetics' for an example of using these in a simple electromagnetic application.

Hope this helps,
Tzanio

**Comment by ShiyangZhang** [comment]
Dear Tzanio and all guys,

Thanks for your reply very much and it helps me a lot.


While the zz estimator seems not to be a residual type estimator ，   how to use it for computing the jump is still a problem for me.
For the lowest order case, the curl of u_h is piecewise constant. For me, the value of u and ∇ × (ν(x, |∇ × u|)∇ × u)  is easy to compute with your MFEM.I will try to compute    [u* N_F]  and  [∇ × (ν(x, |∇ × u|)∇ × u) × N_F ]  just as in NormalTraceJumpIntegrator by integrating on all faces. I'd appreciate it very much for your  suggestion.

Sincerely,
Shiyang

**Comment by v-dobrev** [comment]
Hi Shiyang,

If I understand you correctly, you want to compute the L2 norms of [u.N_F] and [v x N_F], over all faces in the mesh, where u is H(curl) and v is H(div). To achieve this, I would use a function with the following arguments:
```c++
double ComputeFaceNormalJump(const FiniteElement &fe1,
                             const FiniteElement &fe2,
                             FaceElementTransformations &Trans,
                             const Vector &u1, const Vector &u2);
```
The loop over faces will be similar to the one used [here](https://github.com/mfem/mfem/blob/125ff22/fem/bilinearform.cpp#L357). The local vectors `u1` and `u2` can be obtained from the corresponding `GridFunction`, say `u`, using
```c++
   fes->GetElementVDofs(tr->Elem1No, vdofs1);
   u.GetSubVector(vdofs1, u1);
   // similar for u2
```

The above suggestion is just a rough sketch of an approach, so feel free to ask further questions.

Best,
Veselin

**Comment by ShiyangZhang** [comment]
Dear Veselin,

Thank you very much for your detialed advice.
I tried to write the method ComputeFaceNormalJump, while some of  the above code  are borrowed.



I did not checked the topological structure  clearly,  but did the  sentance   `  jump += (u1*shape1_n + u2*shape2_n)*(u1*shape1_n + u2*shape2_n) * ip.weight / normal.Norml2()` computed the jump  with a correct understanding of  the direction of N_F?        


```
///interior faces are considered. square of norm of jump is returned
///we only use  ND_TetrahedronElement(1) now

double ComputeFaceNormalJump(const FiniteElement &fe1,
                             const FiniteElement &fe2,
                             FaceElementTransformations &Trans,
                             const Vector &u1, const Vector &u2);
                             
{  double jump=0.0;
   int nodf1, nodf2, dim, order;
   Vector normal, shape1_n, shape2_n;
   DenseMatrix shape1, shape2;
      
   ndof1=fe1.GetDof();
   dim = fe1.GetDim();

   normal.SetSize(dim);
   shape1.SetSize(ndof1,dim);
   shape1_n.SetSize(ndof1);
   
   if (Trans.Elem2No >= 0)
   {
       ndof2 = fe2.GetDof();
       shape2.SetSize(ndof2,dim);
       shape2_n.SetSize(ndof2);
   }
   else
   {
       ndof2 = 0;
       std::cerr<<"ComputeFaceNormalJump: error:Trans.Elem2No < 0 "<<endl;  std::cin.get();    
   }
   
   if (Trans.Elem2No >= 0)
   order = max(fe1.GetOrder(), fe2.GetOrder()) - 1;
   else
   order = fe1.GetOrder() - 1; 
   //order = max(order, 2);  
     
   const IntegrationRule *ir = &IntRules.Get(Trans.FaceGeom, order);
   
   
   for (int p = 0; p < ir->GetNPoints(); p++)
   {
      const IntegrationPoint &ip = ir->IntPoint(p);
      IntegrationPoint eip1, eip2;

      // Side 1 finite element shape function
      Trans.Loc1.Transf.SetIntPoint(&ip);
      CalcOrtho(Trans.Loc1.Transf.Jacobian(), normal);
      Trans.Loc1.Transform(ip, eip1);
      fe1.CalcVShape(eip1, shape1);
      shape1.Mult(normal, shape1_n);
      
  if (ndof2)
     {   // Side 2 finite element shape function
       Trans.Loc2.Transform(ip, eip2);
       fe2.CalcVShape(eip2, shape2);
       Trans.Loc2.Transf.SetIntPoint(&ip);
       CalcOrtho(Trans.Loc2.Transf.Jacobian(), normal);
       shape2.Mult(normal, shape2_n);
       
       jump += (u1*shape1_n + u2*shape2_n)*(u1*shape1_n + u2*shape2_n) * 
ip.weight;       
     }
   else
       std::cerr<<"ComputeFaceNormalJump"<<std::endl;      
   }
     return jump / normal.Norml2();

   }       

```

Sincerely,
Shiyang

**Comment by v-dobrev** [comment]
Hi Shiyang,

The calls
```c++
   fe1.CalcVShape(*Trans.Elem1, shape1);
   // ...
   fe2.CalcVShape(*Trans.Elem2, shape2);
```
compute the shape (basis) functions on the reference element. For Nedelec elements you need to apply the transformation:
```ascii
   uh(xh) --> u(x) = J^{-t} * uh(xh)
```
whrere `uh(xh)` is the vector value of one basis function on the reference element at the reference point `xh`, and `J` is the Jacobian matrix of the transformation from reference space to physical space at the same point `xh`. The Jacobian matrices can be computed with calls like this:
```c++
   DenseMatrix &J1 = Trans.Elem1->Jacobian();
```
Other than that, your code looks correct.

Hope this helps,
Veselin

**Comment by ShiyangZhang** [comment]
Dear Veselin,
Thank you for such a detialed check very much.
I am so glad it works

I checked the method ND_TetrahedronElement::CalcVShape, it calls the following method CalcVShape_ND, which  have applied u(x) = J^{-t} * uh(xh) already.

```
  385 void VectorFiniteElement::CalcVShape_ND (
  386    ElementTransformation &Trans, DenseMatrix &shape) const
  387 {
  388    const DenseMatrix &J = Trans.Jacobian();
  389 
  390 #ifdef MFEM_THREAD_SAFE
  391    DenseMatrix vshape(Dof, Dim);
  392    DenseMatrix Jinv(J.Width(), J.Height());
  393 #else
  394    Jinv.SetSize(J.Width(), J.Height());
  395 #endif
  396 
  397    CalcInverse(J, Jinv);
  398 
  399    CalcVShape(Trans.GetIntPoint(), vshape);
  400 
  401    Mult(vshape, Jinv, shape);
  402 }
```

Sincerely,
Shiyang

**Comment by v-dobrev** [comment]
Hi Shiyang,

Yes, you are correct, my mistake. The version of `CalcVShape` that you use, does apply the necessary transformation.

Glad to hear the code works,
Veselin
