### ISSUE TITLE
Support for NURBS refinement by quadrisection/bisection of elements/edges?

### ISSUE THREAD

**Issue by davidgunderman** [mfem/mfem#1060]
The uniform refinement of nurbs meshes adds knot vectors in between existing knot vectors, i.e. (0,0,0,1,1,1)->(0,0,0,0.5,1,1,1)->(0,0,0,0.25,0.5,0.75,1,1,1). Is there native support for bisection and edge creation, i.e. (0,0,0,1,1,1)-> (0,0,0,0.5,0.5,0.5),(0.5,0.5,0.5,1,1,1) ->(0,0,0,0.25,0.25,0.25),(0.25,0.25,0.25,0.5,0.5,0.5),(0.5,0.5,0.5,0.75,0.75,0.75),(0.0.75,0.75,0.75,1,1,1). If so, how would I go about doing this?

Thank you for your help.

**Comment by tzanio** [comment]
I don't believe so, but @IdoAkkerman can confirm...

**Comment by v-dobrev** [comment]
You should be able to achieve that using `Mesh::KnotInsert`. The new input knot vectors can have repeated knots. Here is a code snippet that may be useful:
```c++
   int k;
   Array<KnotVector *> kv(mesh->NURBSext->GetNKV());
   cout << "modify which knot vector (1-" << kv.Size() << ") --> "
        << flush;
   cin >> k;
   if (k < 1 || k > kv.Size())
   {
      break;
   }
   cout << "enter knot vector " << k << " --> " << flush;
   k--;
   kv[k] = new KnotVector(cin);
   for (int i = 0; i < kv.Size(); i++)
   {
      if (i != k)
      {
         kv[i] = new KnotVector(*mesh->NURBSext->GetKnotVector(i));
      }
   }
   mesh->KnotInsert(kv);
   for (int i = 0; i < kv.Size(); i++)
   {
      delete kv[i];
   }
```
