### ISSUE TITLE
Flux Limiting in Thermal diffusion

### ISSUE THREAD

**Issue by cjoycd** [mfem/mfem#1063]
Dear All,

I was going through the example "ex16.cpp" for nonlinear thermal diffusion. I wanted to modify this example in such way that the heat flux (k grad T, where k is the conductivity and T is the temperature) at each face (3D) or edge (2D) can be limited (flux limiter) based on some physics models (e.g. a fraction of maximum physically allowed heat flux). This will help to limit the diffusion within the physically acceptable limit via flux limiting (at locations where steep temperature gradients exist). How it can be implemented, either by defining scaled edge/face conductivity (I am not sure about edge based conductivities are defined or used in this example) or limiting the edge/face flux itself. 

Regards
--Sijoy C.D.

**Comment by homijan** [comment]
Sijoy C.D.,

your desire of limiting the heat flux makes complete sense, however, why would you target the skeleton only? Also, ex16 uses H1 elements without a notion of faces.

I would suggest simply scale the \kappa coefficient according to \kappa grad T values as you said. The problem already uses a nonlinear solve, so the solution should pretty much straightforward.

Milan

**Comment by cjoycd** [comment]
Thanks Milan,

Infact I want to develop and couple an electron thermal diffusion (higher order) module with multi material hydrodynamics (modified Laghos). The energies in the hydrodynamics defined via discontinuous L2 FE space. The face/edge integrators for diffusion operators in that case makes sense. Also for discountuous L2 FE space, wouldn't make sense to have edge based conductivities (some kind of average from the shared zones) assuring flux conservation?

**Comment by homijan** [comment]
We are glad your work builds on and extends Laghos! In that case you either want to use 
1) the mixed finite element formulation for diffusion (Hdiv + L2) presented in ex5 and Joule miniapp 
2) DG diffusion formulation from ex14

Both cases will require a nonlinear iteration of the “limited” diffusion coefficient. Case 1) will work with your piece-wise continuous coefficient. You can check if the case 2) work based on the definition of DGDiffusionIntegrator.

**Comment by cjoycd** [comment]
Dear Milan,
Thank you for your suggestions..

Let me go through the examples you suggested .. 

Regards
--Sijoy

**Comment by tzanio** [comment]
Thanks Milan! 

@cjoycd -- I will close this now, please reopen if you have further questions.
