### ISSUE TITLE
Multiple duplicate commits in branch mfem-CVODESSolver

### ISSUE THREAD

**Issue by v-dobrev** [mfem/mfem#1066]
I noticed that the branch [mfem-CVODESSolver](https://github.com/mfem/mfem/tree/mfem-CVODESSolver) contains duplicates of many commits from the master branch. For example commit 638b29b4 is identical to 772f0aca. I don't know how these duplicate commits were created but they should be cleaned up (removed).

Currently, when viewing this branch, github says: "This branch is 2038 commits ahead, 300 commits behind master." -- a lot of these 2038 commit are probably duplicate commits which increase the clone size of the MFEM repository unnecessarily.

**Comment by tzanio** [comment]
@jonwong12 -- any suggestions how to address this? Can we delete this branch and move the new features in a fresh form from `master`?

**Comment by jonwong12** [comment]
If it's alright with you, can I do that merge on my side and rewrite the history here when it's all working? I'm in the process of merging with what's in master at the moment.

**Comment by tzanio** [comment]
Sure

**Comment by tzanio** [comment]
@jonwong12, what is the status of this?

**Comment by jonwong12** [comment]
I hope to submit a PR within the next week or two.

**Comment by tzanio** [comment]
@jonwong12, can you update us on the status of this issue?

**Comment by jonwong12** [comment]
Working on it this week. Should have it fixed within the next week.

**Comment by jonwong12** [comment]
@v-dobrev @tzanio Did the recent push resolve the duplicate commits?

**Comment by jonwong12** [comment]
Hmm. Even though the parent commit is from master, github says otherwise. You can delete the branch and I can push up the one I rebased off of master again.

**Comment by tzanio** [comment]
Done

**Comment by tzanio** [comment]
@jonwong12 your push has overwritten our tags and created parallel history with new commits so I have disabled your write access until we can fix that.

Can you talk to @v-dobrev or me to explain what you are trying to do.
