### ISSUE TITLE
Reading a 2D mesh generated by netgen

### ISSUE THREAD

**Issue by rhebergens** [mfem/mfem#107]
Hello,
How should one modify the 2D mesh file generated by netgen so that this can be read by MFEM?
In 3D I saw that you should export in neutral the mesh created by netgen and add NETGEN to the first line of the created mesh. This works fine for me. 
I'm doing the same in 2D. As an example, I'm just using the following 2D example from the netgen site:

https://sourceforge.net/p/netgen-mesher/git/ci/d44a05ef8a105c40c13b67797a61f22121ed8b36/tree/tutorials/square.in2d

I create the mesh and export in neutral. I saw in mesh.cpp (line 2355) that I should probably add "areamesh2" to the first line instead of NETGEN. Unfortunately the errors I'm getting are

terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted

(I'm just using MFEM example 1 and running ./ex1 -m netgenmesh.mesh)

thanks,
Sander

**Comment by tzanio** [comment]
Hi Sander, here is a quick script to do this 

```tcsh
#!/bin/tcsh

# Converts NetGen's 2D mesh from the new to the old format
# Usage: ng2d_new2old.sh test-netgen-output test.mesh

set NV = `head -n 1 $1`
set EO = `echo $NV+2 | bc`
set NE = `head -n $EO $1 | tail -n 1`
set BO = `echo $EO+$NE+1 | bc`
set NB = `head -n $BO $1 | tail -n 1`

echo "The mesh has $NV vertices, $NE elements and $NB bdr. elements"
echo "Conevrting..."

echo "areamesh2" > $2
echo ""          >> $2

set s = `echo $BO+$NB | bc`
set e = $NB
echo $NB >> $2
head -n $s $1 | tail -n $e  >> $2

set s = `echo $BO-1 | bc`
set e = $NE
echo $NE >> $2
head -n $s $1 | tail -n $e | awk '{printf("%9d%9d%9d%9d%9d\n",$1,3,$2,$3,$4);}' >> $2

set s = `echo $EO-1 | bc`
set e = $NV
echo $NV >> $2
head -n $s $1 | tail -n $e  >> $2

echo "Done."
```

It will be good if we fix the reader so we can support that natively.

**Comment by rhebergens** [comment]
Hi tzanio,

Thanks! I have it working now for triangles. 

I'm using the same script now for a grid of quads, it seems something is going wrong. All matrices are set up, and the iterative method converges (470 iterations when using quads, 100 iterations when using triangles), but glvis doesn't plot the solution (the figure is killed immediately as it's created). Do I need to set in ex1.cpp somewhere that this is a grid with quads?

Sander

**Comment by rhebergens** [comment]
I think I already see what's going on, the script ignores the last column of vertices when creating the element...

**Comment by tzanio** [comment]
Hi Sander, were you able to accomplish the conversion?

**Comment by rhebergens** [comment]
Hi Tzanio,
Yes. Using the script you sent, a netgen grid with triangles was converted to the format required by mfem and that works. For a netgen grid with quads the script did not take into account that a quad has 4 vertices. I did not modify the script, but just changed the order of the data in the grid files using copy/paste since I just quickly wanted to test some of the HDG implementations we're working on on a non-standard grid.
thanks, Sander

**Comment by tzanio** [comment]
Glad you got it working.

I'll close this issue for now, but we'll put adding support for the new 2D format on our wishlist.
