### ISSUE TITLE
Limiters

### ISSUE THREAD

**Issue by delcmo** [mfem/mfem#1070]
Hello,

I am trying to implement a flux limiter (DG) that requires for each element of the mesh, to loop over its neighbors to collect the numerical solution. I could not find anything in the mailing list related to this issue. 

To clarify, let consider a 1D example with element indices, j-1, j and j+1, and the corresponding numerical solution u_{j-1}, u_j and u_{j+1}. When on cell j, how do I compute the ratio:

r = (u_{j+1} - u_j) / (u_j - u_{j-1})

What would be the appropriate MFEM object to use that loops over all elements and for each element loops over each neighbor element while giving access to the numerical solution?

Thanks,

Marco

**Comment by v-dobrev** [comment]
This can be achieved by looping over all mesh faces. An example of such a loop (over all interior faces) is here: https://github.com/mfem/mfem/blob/3f1adff17d8865061ef643cabb11d7a49c5fd53c/fem/bilinearform.cpp#L491-L514

As an example for such DG face integrator, you can take a look at: https://github.com/mfem/mfem/blob/3f1adff17d8865061ef643cabb11d7a49c5fd53c/fem/bilininteg.cpp#L2529-L2531

The case of `NonlinearForm` is handled here: https://github.com/mfem/mfem/blob/3f1adff17d8865061ef643cabb11d7a49c5fd53c/fem/nonlinearform.cpp#L138-L165

**Comment by delcmo** [comment]
Thanks for the help. I was able to get it to work. Closing this issue.

Marco
