### ISSUE TITLE
GridFunctions on Interface spaces

### ISSUE THREAD

**Issue by ianabel** [mfem/mfem#1074]
In the intermittent series of 'theoretical physicist asks silly computational questions', if one has a GridFunction defined on an interface-only space, i.e.

coll = new DG_Interface_FECollection(Order, Dimension);
fes = new FiniteElementSpace( mesh, coll ); 
GridFunction gf( fes );
// do things that populate gf

How does one obtain the values of this GridFunction? 
Nothing that eventually calls GetValues will work, because such finite element spaces always return NULL for fes->GetFE(i), as they only have 'face' elements, not 'base' elements. 

I have whipped up a couple of functions to do this, but want to make sure i'm not duplicating functionality that's already there.

**Comment by v-dobrev** [comment]
Hi @ianabel,

You are right, MFEM does not have methods to evaluate `GridFunction`s directly on faces. The methods `GridFunction::GetFaceValues` and `GridFunction::GetFaceVectorValues` evaluate values on a given face but they do it indirectly by mapping the point on the face to a point in one of the two adjacent elements and then performing the computation of the value at that point.

**Comment by ianabel** [comment]
OK, my pull into the hdg branch adds these functions, and I think it's probably only useful for that case. 
If this is needed  for non HDG algorithms, someone can reopen this and I'll make a PR into mainline.
