### ISSUE TITLE
Migration to C++11

### ISSUE THREAD

**Issue by ianabel** [mfem/mfem#1075]
Now that MFEM requires C++11 to compile, are there projects underway to migrate to more modern C++ idioms throughout the codebase?

For instance, is there interest in extending any interface that uses a function pointer to also work with a std::function ? As a start, I have a FunctionCoefficient replacement that works with std::functions, in case that would be useful to anyone else. 

Similarly, trying to use nullptr going forward, rather than NULL?

**Comment by v-dobrev** [comment]
We do not have a specific plan to do this kind of "migration". However, we're open to consider additions that use C++11 features like `std::function` -- feel free to propose a PR.

**Comment by ianabel** [comment]
See #1078
