### ISSUE TITLE
Maximum and Dörfler Marking

### ISSUE THREAD

**Issue by ianabel** [mfem/mfem#1076]
Is there any interest in gaining some more involved refiners for AMR? 
The two refiners I've implemented are Maximum marking and Dörfler Marking.
Doerfler marking, described in [1], is often used to prove convergence and optimality of adaptive algorithms. Maximum marking is simply included for variety to demonstrate a variety of refiners in the codebase. 

[1] Willy Dörfler. A convergent adaptive algorithm for Poisson’s equation. SIAM J. Numer. Anal.,
33(3):1106–1124, 1996.

The code is at 
https://github.com/ianabel/mfem/blob/hdg/mesh/Refiners.cpp
https://github.com/ianabel/mfem/blob/hdg/mesh/Refiners.hpp
but doesn't need any hdg-branch specific stuff. 

If there's interest i'll run a bunch of tests and clean it up for a proper pull request.

**Comment by jandrej** [comment]
Is this included in #969?

**Comment by ianabel** [comment]
Err, shouldn't be. That's related to #1074 .
I don't really fathom the GitHub process, so I've probably mucked this up. If there's interest I'll make a PR from ianabel/mfem -> master with these refiners. It needs some unit tests before it hits prime-time though.

**Comment by jandrej** [comment]
I was asking because the PR includes Refiners `MaximumMarkingRefiner::MaximumMarkingRefiner` etc.

**Comment by ianabel** [comment]
Ah, I done goofed. I'll make the PR from the correct branch.

**Comment by ianabel** [comment]
PR #1079 implements this.
