### ISSUE TITLE
Mesh to ParMesh error

### ISSUE THREAD

**Issue by ztdepztdep** [mfem/mfem#1077]
I setup a mesh by hand, but when i create a new ParMesh, it gives me the following error:

>    Mesh::ElementToEdgeTable()
>    application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
> [unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1:
> system msg for write_line failure : Bad file descriptor

```
   mesh=new Mesh(Dimen, NV, NCELL, Ntri, -1);
    for(int i=0;i<Nodes.size();i++) {
    mesh->AddVertex(Vertex(Nodes[i][0],Nodes[i][1],Nodes[i][2])()) ; 
   }
    for(int i=0;i<CellConnection.size();i++) {
    int idx[4] = {CellConnection[i][0],CellConnection[i][1],CellConnection[i][2],CellConnection[i][3]}; 
    mesh->AddElement(new Tetrahedron(idx, 0));  
   }   
   mesh->Finalize(1,1);
    int *partitioning;
    pmesh=Teuchos::rcp(new ParMesh(MPI_COMM_WORLD, *mesh,partitioning, 1));
```

**Comment by tzanio** [comment]
You need to fill in the `partitioning` array.
