### ISSUE TITLE
extracting local information from a ParMesh

### ISSUE THREAD

**Issue by kvoronin** [mfem/mfem#108]
Hello everyone,

For creating a 4d mesh from a given ParMesh object which stored a 3d mesh, I need a local_to_global connectivity for vertices I think. In other words, I need to convert somehow local vertex indices into the global.
How can I get this information from a ParMesh if I am implementing my routine as a friend function for ParMesh so that I can access the protected members?

Comments about what is exactly stored in ParMesh internal arrays may help me.

Thanks,
Kirill

**Comment by v-dobrev** [comment]
Hello Kirill,

The `ParMesh` class does not create a global numbering of the vertices because it is not directly needed. However, you can create such enumeration easily by creating linear continuous FE space
(i.e. a `ParFiniteElementSpace` using `H1_FECollection` of order 1) where local degrees of freedom (DOFs) correspond to local vertices. In addition, the `ParFiniteElementSpace` class generates global enumeration for its degrees of freedom. You can access the global numbers with the method `GetGlobalTDofNumber` which converts a local degree of freedom, i.e. a local vertex index, into a global number.

Let us know if you have any further questions,
Veselin

**Comment by kvoronin** [comment]
Hello Veselin, 
Thanks for the reply, could you point out why the following code produces an MPI error (no error for serial run):
The errors appears when creating the ParFiniteElementSpace object.
```
int main (int argc, char *argv[])
{
    int num_procs, myid;

    // 1. Initialize MPI
    MPI_Init(&argc, &argv);
    MPI_Comm comm = MPI_COMM_WORLD;
    MPI_Comm_size(comm, &num_procs);
    MPI_Comm_rank(comm, &myid);

    Mesh * mesh3dbase;
    mesh3dbase = new Mesh(1,1,1,mfem::Element::TETRAHEDRON,1);

    if (myid == 0)
    {
        std::stringstream fname;
        fname << "mesh_3dbase.mesh";
        std::ofstream ofid(fname.str().c_str());
        ofid.precision(8);
        mesh3dbase->Print(ofid);
    }


    ParMesh * pmesh3dbase = new ParMesh(comm, *mesh3dbase);

    delete mesh3dbase;

    //cout << "dimension = " << mesh3dbase->Dimension() << endl;

    FiniteElementCollection * h1_coll = new H1_FECollection(1, mesh3dbase->Dimension());

    //MPI_Finalize();
    //return 0;

    ParFiniteElementSpace * pspace3d = new ParFiniteElementSpace(pmesh3dbase, h1_coll);

    MPI_Finalize();
    return 0;
}
```

Thanks,
Kirill

**Comment by martemyev** [comment]
Hi Kirill,

I didn't have a chance to look carefully or run you code, but it seems wrong to call Dimension() method after you deleted mesh3dbase.

Best,
Mikhail

**Comment by kvoronin** [comment]
@martemyev,
O, indeed. But it was a last-moment change in the code. In segfaults with 3 instead of Dimension() as well.

Thanks,
Kirill

**Comment by tzanio** [comment]
Hi Kiril, you probably want to refine the mesh before splitting it in parallel (or start with a serial mesh that has more than one element).

**Comment by kvoronin** [comment]
Hi @tzanio,
I tried to add two refinement steps for a serial mesh, and still got the same error.
The code is now
```
int main (int argc, char *argv[])
{
    int num_procs, myid;

    // 1. Initialize MPI
    MPI_Init(&argc, &argv);
    MPI_Comm comm = MPI_COMM_WORLD;
    MPI_Comm_size(comm, &num_procs);
    MPI_Comm_rank(comm, &myid);

    Mesh * mesh3dbase;
    mesh3dbase = new Mesh(1,1,1,mfem::Element::TETRAHEDRON,1);

    mesh3dbase->UniformRefinement();
    mesh3dbase->UniformRefinement();

    if (myid == 0)
    {
        std::stringstream fname;
        fname << "mesh_3dbase.mesh";
        std::ofstream ofid(fname.str().c_str());
        ofid.precision(8);
        mesh3dbase->Print(ofid);
    }


    ParMesh * pmesh3dbase = new ParMesh(comm, *mesh3dbase);

    delete mesh3dbase;

    //cout << "dimension = " << mesh3dbase->Dimension() << endl;

    FiniteElementCollection * h1_coll = new H1_FECollection(1, 3);

    //MPI_Finalize();
    //return 0;

    ParFiniteElementSpace * pspace3d = new ParFiniteElementSpace(pmesh3dbase, h1_coll);

    MPI_Finalize();
    return 0;

}
```
So, I still don't know what is wrong with it.

Thanks,
Kirill

**Comment by tzanio** [comment]
Nope. This works just fine for me.

**Comment by kvoronin** [comment]
@tzanio, 
Thanks for help, I should have tried it with pure mfem by myself earlier, sorry.
