### ISSUE TITLE
how to change the parallel pmesh to a serial mesh on the cpu 0

### ISSUE THREAD

**Issue by ztdepztdep** [mfem/mfem#1081]
Dear sir:
    I want to change the pmesh to a serial mesh on the root cpu only. which function can resolve this.
Regards.

**Comment by tzanio** [comment]
I am not sure what exactly you mean here, but `ParMesh` inherits from `Mesh`, so a `ParMesh` is already a mesh. 

If you want to change e.g. the node coordinate of the mesh (only on MPI rank 0?!) you can do that directly by modifying the nodes `GridFunction`. If you want to change the topology and still have a valid parallel mesh, I am afraid that is not possible.

Hope this helps,
Tzanio
