### ISSUE TITLE
question of boundary

### ISSUE THREAD

**Issue by fengerhan** [mfem/mfem#1083]
When there are two boundary in the question, I want to know how to define the boundary  attribute of the  joint vertex of the two boundary in mesh v1.0 format ?   Different boundary attribute of the joint vertex will give different solution. How to deal with this problem?

**Comment by mlstowell** [comment]
Hello, @fengerhan ,
There is currently no way, in MFEM, to assign boundary conditions to individual vertices.  However, there may be ways to work around this limitation if necessary.  What type of equation are you solving and what is the boundary condition?

Best wishes,
Mark

**Comment by fengerhan** [comment]
Hello Mark,
Thank you for your answer. I just want to solve a possion equation on 2D domain. On the boundary of the domain, I want to set the solution function u = 0 on part of the boundary, and u = 1 on the rest of boundary. I find my solution  on   the joint vertex of the two boundary will get wrong result. Especially when I do mesh  adaptation. I find the boundary attribute of the joint vertex of the two boundary have been change. Can you give me a way to deal with this limitation?

Best wishes,
Han

**Comment by mlstowell** [comment]
Hi, @fengerhan ,
I forget the details but I don't think an exact solution exists when the boundary condition is discontinuous like this.  I see two ways to proceed which each introduce a small transition region across the discontinuity.

The first is to write a function that is 0 on part of the boundary, 1 on the other part of the boundary, and apply this as your Dirichlet BC function.  The function could be discontinuous, using something like `if (x[0] <= 1.0) {return 0.0;} else {return 1.0;}`, or it could have a transition region with a suitable thickness.  When such a function is projected onto a continuous finite element basis you'll get an artificial transition region comparable in width to the mesh spacing.

The second option is to choose a fixed width for the transition region and build this into the mesh by creating a small portion of the boundary between the portions that should equal 0 and 1.  You then set no boundary condition on this small transition region.  The natural boundary condition on this new portion will be that the normal component of the gradient will be zero.  If this natural boundary condition creates an odd kink in the solution you can specify a desired gradient to smooth things.

Best wishes,
Mark
