### ISSUE TITLE
Parallel with BlockOperator and BlockMatrix

### ISSUE THREAD

**Issue by yantingsa** [mfem/mfem#1085]
Hi,

I'm working on a nonlinear advection-diffusion-reaction problem. It is a system with 5 unknowns. I wrote the reaction part with `BlockNonlinearFormIntegrator` to construct the Jacobian. So my Jacobian looks like `NonlinearForm->GetGradient + Diffusion + Advection`. And the Jacobian is set by blocks, for instance, `Jacobian->SetBlock(0,0) = NonlinearForm->GetGradient->GetBlock(0,0) + diffusion`. In this way, I used BlockOperator for BlockNonlinearForm and BlockMatrix for diffusion. My code works great on serial and now I'm working on parallel version. I went through the examples and found out you used BlockOperater in parallel version instead of BlockMatrix in serial version. So my question are:
1. In the Mult function of Operator class, I used `BlockNonlinearForm->Mult(k,y); BlockMatrix->AddMult(k,y);`. And in your parallel examples, you used `ParNonlinearForm->Mult(k,y); ParBlinearForm->AddTrueMult(k,y)`. I'm wondering what should I do with this. I used `ParBlockNonlinearForm->Mult(k,y); BlockOperator->Mult(k, w); y+=w;`. Is this the correct way? Or I need to construct in another way.
2. In regard to my Jacobian on the GetGradient function in Operator class, how should I construct my Jacobian in parallel version. I tried with `ParBlockNonlinearForm->GetLocalGradient(u)->GetBlock` and this did not work. Can I still construct my Jacobian by blocks? Or is there another way I need to do to construct it.

Best,
Ting

**Comment by tzanio** [comment]
@jamiebramwell or @rcarson3, do you think you can help @yantingsa?

**Comment by yantingsa** [comment]
Hi,

I've fixed this problem. But I do have new problem in [1103](https://github.com/mfem/mfem/issues/1103). It would be great if you can help me with that. Thank you so much.
