### ISSUE TITLE
config.mk linking issue for downstream users

### ISSUE THREAD

**Issue by cyrush** [mfem/mfem#1088]
We use MFEM's config.mk in downstream codes + I hit an issue with a system path undermining linking on LLNL's pascal cluster.

The issue is that in `MFEM_EXT_LIBS`, a `-L/lib64` appears before the more specific linking `-L` path to the proper HDF5. On this pascal, there happens to be a system install of HDF5 in `/lib64`

The upshot is: while the MFEM build is linking to the proper HDF5, downstream codes end up linking two versions of HDF5, causing HDF5 calls to fail in fun and mysterious ways.

Not quite sure where the `/lib64` is being injected, but if it, or other system paths are necessary they should appear last. If they aren't necessary they should be filtered out.

**Comment by jandrej** [comment]
Hi @cyrush, is this introduced from the makefile or cmake generated config.mk?

**Comment by cyrush** [comment]
makefile based generated config.mk

**Comment by v-dobrev** [comment]
@cyrush, there is no string "lib64" in mfem's makefiles. Could this flag be coming from your mfem configuration options?

**Comment by cyrush** [comment]
it possible it could be coming for from spack, I'll try look deeper.

**Comment by cyrush** [comment]
ok, looked deeper -- this is an issue with the mfem spack package:

Conduit depends on `dl`, the logic in the mfem package finds dl:

```
libs += LibraryList(find_system_libraries('libdl'))
```

Then later, the linking/libs command that describes for conduit is formulated: 

```
CONDUIT_LIB=%s' % ld_flags_from_library_list(libs)]
```
ld_flags_from_library_list() adds an `rpath` command and a `-L` for every directory in the library list.

The system libs will come before the actual dependencies.

**Comment by v-dobrev** [comment]
Oh, OK, this is in the spack mfem package. We can separate the system libraries and add them without `-L` and `rpath` options. What do you think? This is probably the right way to do it anyway. I'll make a PR for this in spack.

**Comment by cyrush** [comment]
@v-dobrev yes, that sounds like a safe path.  Another option is to provide the full path to the library  instead of using `-l`. That might be more brittle, but not 100% sure.

**Comment by tzanio** [comment]
@v-dobrev and @cyrush -- has this been addressed?

**Comment by v-dobrev** [comment]
Not yet -- it is on my todo list.

**Comment by v-dobrev** [comment]
Should be fixed in https://github.com/spack/spack/pull/15500.

**Comment by cyrush** [comment]
@v-dobrev thanks!

**Comment by tzanio** [comment]
@cyrush, can you confirm the above fix works for you?

**Comment by cyrush** [comment]
@tzanio gearing up for some spack work later this week, I'll try to test this as well

**Comment by tzanio** [comment]
@cyrush, we believe this was fixed so I'm closing this issue for now. Please feel free to reopen if there is still a problem.

**Comment by cyrush** [comment]
@tzanio got it, thanks!
