### ISSUE TITLE
Question adapting Tesla miniapp to solve a 2D magnetostatics problem

### ISSUE THREAD

**Issue by garobed1** [mfem/mfem#1089]
Hello,

I have been trying to adapt the existing Tesla miniapp to solve a test problem and compute the magnetic flux density B on a unit square mesh with structured triangle elements, specifically a circular wire (given radius R) of current flowing 'into the page', or into the center of the unit square, with uniform boundary conditions. During assembly, the discrete `curl_` operator calls `ProjectGrad_RT`, which calls `CalcDShape` for the Raviart-Thomas element. The error is thrown, predictably, that `CalcDShape` is not defined for vector finite elements, and assembly fails. This does not occur for any 3D domain I've tried.

This may be a misunderstanding of the physics on my part and, as a result, the solver components necessary for this problem. Regardless, what would be necessary to adapt the miniapp to solve 2D problems instead? Tangentially, I can define the circle in the center of the domain in the x-y plane as the wire, but would it be valid for me to define the current flowing along the z-axis? I'll provide more information for my problem if needed, I am still inexperienced with MFEM and have somewhat shaky knowledge on magnetostatics.

Thank you,
Garo Bedonian

**Comment by mlstowell** [comment]
Hello, @garobed1 ,
The trouble with magnetostatics in 2D is that we get two rather different PDEs when the current density is in the plane or perpendicular to it.  In the case that you describe the resulting equation is essentially `-Laplacian A_z = J_z` where `A_z` and `J_z` could be represented as H1 scalar fields.  This is basically the same equation solved in `ex1p.cpp` with a non-trivial right hand side.  To get the magnetic field from `A_z` you take its gradient and then rotate it by 90 degrees.

An alternative is to create a very thin 3D mesh.  One element thick is all you need in the z-direction.  You then use `tesla` with the boundary conditions set so that the tangential components of `A` are zero everywhere on the boundary.  This produces a larger linear system than necessary but the boundary conditions reduce the effective size of the system to match what `ex1p` would produce.

Best wishes,
Mark

**Comment by garobed1** [comment]
Thank you for the response.

I will try both approaches. Would the thin 3D approach also require periodic boundary conditions between the top and bottom surfaces?

**Comment by mlstowell** [comment]
Hi, @garobed1 ,
If the current density had components in the plane then the vector potential would also have components in the plane and periodic boundary conditions would indeed be necessary.  In this case the vector potential should be entirely in the z direction so we only need to set its transverse components to zero.

Incidentally the vector potential is represented using Nedelec basis functions which can be viewed as being directed along the edges of the mesh.  This means that all of the degrees of freedom on the surface of the domain correspond to the components of the field that are tangent to the surface.  This in turn implies that Dirichlet boundary conditions only effect the tangential portion of the field.

Best wishes,
Mark

**Comment by garobed1** [comment]
Hello,

Thank you again, and sorry for the current late response as I have been busy with other work. One aspect of this that I can't figure out, how do I impose vector Dirichlet boundary conditions in MFEM such that certain components are fixed while others are still degrees of freedom? As you described, I want to set x and y components of the vector potential to 0 everywhere on the boundary, but leaving the z components on them as DOFs. How is this done in the context of projecting a VectorFunctionCoefficient onto the boundary?

**Comment by mlstowell** [comment]
Hi, @garobed1 ,
If you’re working with Nedelec basis functions then you cannot do this.  In this case the only options are to set the components which are tangent to the boundary equal to some known Dirichlet values or to set the normal component of the curl to a known value.  The second option is a Neumann boundary condition.  To setup a well defined problem you typically need Dirichlet boundary conditions on much of the boundary.  Exactly how much depends on how complicated the geometry is (I’m afraid I cannot be very specific about this).

If you’re working in 2D and assuming the x and y components are zero everywhere then you would model the z component of the vector potential using H1 basis functions.  In this special case you could leave A_z unspecified on portions of the boundary (if it’s unspecified everywhere on the boundary the system does not have a unique solution). 

Best wishes,
Mark

**Comment by garobed1** [comment]
Hello,

Turns out that the origin of my last question was the result of a completely different and specific error that was causing incorrect solutions, which I have resolved. I am now getting expected answers for the wire problem. Thank you for your help.

**Comment by denislachapelle** [comment]
Dear @mlstowell,

In the above discussion you wrote "To get the magnetic field from A_z you take its gradient and then rotate it by 90 degrees.".

I successfully get the gradient of the magnetic potential but I can figure how to rotate by 90.

Can you explain how to rotate by 90 degree?

Thank you very much for your help,
Denis
