### ISSUE TITLE
Compute stress on ex10.cpp

### ISSUE THREAD

**Issue by CorporalClegg** [mfem/mfem#109]
Hi,

I try to compute the resulting stress on the example 10.
I have read issue #10 that shows a way to compute the stress on ex2 , and I try to reproduce the same things on the ex10.

We agree that the stress definition using an HyperElastic model is different than the one with the LinearElastic definition.
![stress](https://cloud.githubusercontent.com/assets/11282274/21990895/c9a0d540-dc10-11e6-97b6-443d7d1ff7c7.gif)
where j is the determinant of F,
F is the displacement gradient (it is called J in mfem::NeoHookeanModel::EvalP(const DenseMatrix &J, DenseMatrix &P) const;
and P is the first Piola-Kirchhoff stress tensor.

So I have defined the following class:
```c++
class StressCoefficient: public Coefficient {
private:
    GridFunction &u ;
    DenseMatrix S ;
    Coefficient &lambda_ ;
    Coefficient &mu_ ;
    double g ;

public:
    StressCoefficient( GridFunction &_u, Coefficient &_lambda, Coefficient &_mu )
        : u( _u ), lambda_( _lambda ), mu_( _mu ), g( 1.0 )
    {
    }

    void EvalP(
        ElementTransformation &T,
        const IntegrationPoint &ip,
        const DenseMatrix &J,
        DenseMatrix &P ) const
    {
        int dim = J.Width() ;

        double K = lambda_.Eval( T, ip ) ;
        double mu = mu_.Eval( T, ip ) ;

        DenseMatrix Z ;
        Z.SetSize( dim ) ;
        CalcAdjugateTranspose( J, Z ) ;
        double dJ = J.Det() ;
        double a = mu * pow( dJ, -2.0 / dim ) ;
        double b = K * ( dJ / g - 1.0 ) / g - a * ( J * J ) / ( dim * dJ ) ;
        P = 0.0 ;
        P.Add( a, J ) ;
        P.Add( b, Z ) ;
    }

    virtual double Eval( ElementTransformation &T, const IntegrationPoint &ip )
    {
        DenseMatrix J ;
        u.GetVectorGradient( T, J ) ;  // eps = grad(u)
        DenseMatrix P(3) ;
        P = 0.0 ;
        EvalP( T, ip, J, P ) ;
        DenseMatrix jinvF(3) ;
        jinvF = 0.0 ;
        S.SetSize(3) ;
        S = 0.0 ;
        double dj = J.Det() ;
        jinvF.Add( 1 / dj, J ) ;
        DenseMatrix tP ;
        tP.Transpose( P ) ;
        Mult( jinvF, tP, S ) ;
        return S( 0, 0 ) ;
    }
    virtual void Read( std::istream &in )
    {
    }
    virtual ~StressCoefficient()
    {
    }
} ;
```
It computes the First Piola-Kirchhoff stress tensor (it is basically a copy/past of mfem::NeoHookeanModel::EvalP(const DenseMatrix &J, DenseMatrix &P) const ) and do the product with the displacement gradient and the inverse of its determinant (as shown in the previous equation).

To retrieve the displacement and Project StressCoefficient, I have written this code at the end of the main:

```c++
    // 9. Save the displaced mesh, the velocity and elastic energy.
    {
        GridFunction *nodes = &x ;
         Vector old_nodes(3*mesh->GetNV()) ;
         mesh->GetNodes(old_nodes) ;

        GridFunction displacement( &fespace ) ;
        for( int i = 0; i < displacement.Size(); i++ ) {
            displacement[i] = nodes->operator ()( i ) - old_nodes[ i ] ;
        }
        Vector mu_vec( mesh->attributes.Max() ) ;
        mu_vec= mu ;
        Vector K_vec( mesh->attributes.Max() ) ;
        K_vec = K ;
        PWConstCoefficient mu_coeff( mu_vec ) ;
        PWConstCoefficient K_coeff( K_vec ) ;
        StressCoefficient stress_coeff( displacement, K_coeff, mu_coeff ) ;
        L2_FECollection pp_fec( order, dim ) ;
        FiniteElementSpace pp_fespace( mesh, &pp_fec ) ;
        GridFunction pp_field( &pp_fespace ) ;
        pp_field.ProjectCoefficient( stress_coeff ) ;
```
When I run the code, I have numerical error because the determinant of the displacement gradient of is null. 
My question is : Am I doing what i want right or there is something I have missed ?

Thank you in advance !

PS : some value are harcoded, so I think my code works only on 3D examples

**Comment by v-dobrev** [comment]
Hi @CorporalClegg,

One correction: the formula for the Cauchy stress should be (using latex notation)
```latex
\sigma = j^{-1} P F^T
```
where `F` is the _deformation_ (not displacement) gradient.

The simplest way to compute the stresses in example 10 is to copy the `ElasticEnergyCoefficient` class from the example and replace its `Eval` method with something like this:
```c++
double StressCoefficient::Eval(ElementTransformation &T,
                               const IntegrationPoint &ip)
{
   model.SetTransformation(T);
   x.GetVectorGradient(T, J);
   DenseMatrix P(J.Height()), S(J.Height());
   model.EvalP(J, P);
   MultABt(P, J, S);
   S *= (1.0/J.Det());
   return S(0, 0); // return the xx component of the Cauchy stress
}
```
Then you can use this coefficient in a method similar to `HyperelasticOperator::GetElasticEnergyDensity` to project the stress.

Let us know if you have any further questions.

Cheers,
Veselin

**Comment by CorporalClegg** [comment]
Hi Veselin,

Thank you for your answer ! Indeed, I have make a mistake about F, and the way you propose to Eval the stress is cleaner than mine !
I have implemented it and here is the result with
`./ex10 -m ../data/beam-hex.mesh -r 1 -o 2 -tf 1`

![screenshot from 2017-01-17 09 52 29](https://cloud.githubusercontent.com/assets/11282274/22013703/be3704f6-dc9a-11e6-9186-3a23bb42e016.png).

Again, maky thanks

Cheers,

CorporalClegg
