### ISSUE TITLE
Velocity as an independent variable in MFEM?

### ISSUE THREAD

**Issue by jjwiman** [mfem/mfem#1090]
I'm interested in solving the following linear system (well, something close enough to it):
```
i * p . [\nabla u(r, p)] + 2 * i * u(r, p)  + f(r, p) = 0
```
Here `u` is the unknown complex function and `f` is a known complex function, `r` is the spatial coordinate potentially of dimension 1 to 3, and `p` represents a velocity *direction* (so 2 angles for 3 dimensions). The key part being that `p` is an additional independent variable.

I've been interested in setting this up in a DG formulation, but the matter of handling the additional `p` dimensions in the code is not obvious to me. I was hoping someone might have some advice as to what direction would be the most sane for this.

**Comment by tzanio** [comment]
Is the direction `p` fixed, or is there another set of equations for it?

I could be off, but this looks like a problem that @tangqi or @homijan may be able to help with...

**Comment by tangqi** [comment]
So isn't your problem higher than 3d? I have not done anything beyond 3d in mfem. 

Another related question is in \nabla u(r, p), what does the gradient mean, in the p direction?

**Comment by homijan** [comment]
Hi @jjwiman,

do you want to solve for u(r_x, r_y, r_x, p_\theta, p_\phi) as the most challenging case?
Also, is it correct that your model does not contain du/dtheta or du/dphi?

If the answer is yes and yes, I would suggest to apply piece-wise constant discretization in angles (usually called SN) and solve N equations (one for each of discrete directions labeled d)
i * p_d . [\nabla u(r, p_d)] + 2 * i * u(r, p_d)  + f(r, p_d) = 0.

It looks like u(p_i) does depend on u(p_j), only as delta_ij, i.e. your SN equations are independent.

The implementation should be fairly simple following ex9.

**Comment by jjwiman** [comment]
Thanks for the responses everyone. @homijan has the right of it I think, although I neglected to mention that in general the momenta coordinates will couple through the boundary condition.

I've been traveling and haven't managed to get a prototype up and running yet, but my current strategy is to do the piecewise discretization of `p` and have it as a vdim. So far I've implemented vector versions of `ConvectionIntegrator` and `DGTraceIntegrator` to do that, but it's taking me some time to learn the mesh format and conventions in order to get things actually running.

**Comment by jjwiman** [comment]
Speaking of boundary conditions, I think I have things working to that point. I typically have "specular" boundaries `u(p) = u(p')` where `p'` is the specular reflection of `p` from the boundary. I'm guessing the way to approach this is a boundary Integrator similar to the trace integrator but containing `u(p) - A*u(pa) - B*u(pb)` where the reflected reflected p is linearly interpolated into pa and pb contributions. I'm not sure at all whether this will work, however, so onward we go.

**Comment by tzanio** [comment]
Hi @jjwiman,

I am actually not familiar with these types of boundary conditions -- is the value of `u(p')` known, or is this a "periodic"-type boundary condition? In the first case, this is just a Dirichlet (essential) BC which is imposed in `FormLinearSystem`. In the second case, the condition can be imposed either via the mesh or by variational restriction.

Since the original question was answered, do you mind closing this issue and create a new one for the Specular BCs?

Cheers,
Tzanio

**Comment by jjwiman** [comment]
Thank you @tzanio , you are correct that the initial question appears resolved, so I will close this. 

I think the boundary condition may also have been resolved by modifying the face trace integrator to map into the same element but at another vdim index. I'll probably open another question once I have a more complete implementation and some idea of accuracy and performance.
