### ISSUE TITLE
State dependent coefficient

### ISSUE THREAD

**Issue by tuckerbabcock** [mfem/mfem#1091]
Hi all, 

I'm trying to solve a non-linear magnetostatics problem on a domain with multiple materials, and so multiple reluctivities, some of which would be nonlinear functions of the state. I've written a new nonlinear curl-curl integrator, in which I need to evaluate the reluctivity depending on the current state. To keep the code fairly general, I was thinking I could define a new class `MaterialModel`, which would hold an unordered map of pairs of a mesh attribute relating material and a `Coefficient` to evaluate for that material. The `MaterialModel`'s Eval function would use the `ElementTransformation` to choose which `Coefficient` in the map to evaluate based on the mesh attribute. To make this work for state-dependent materials I think I would need to define a new `StateDependentFunctionCoefficient` class, which would evaluate a reluctivity function based on the current state. 

My questions are:
Does this approach make sense? Is there already an existing way to evaluate explicit state dependent functions?
Do I need to create a `MaterialModel` class, or is there already an existing container for coefficients? Something like `PWConstCoefficient`. I see that a `RestrictedCoefficient` could be used the same way as the pair I described above, but I'm looking for a container that would pick the appropriate `Coefficient` to evaluate based on the `ElementTransformation`.

Thanks!

**Comment by Dan2997925** [comment]
Your approach makes sense I do this in one of my MFEM-based applications. Unfortunately my code is not online for you to look at. Check out GridFunctionCoefficient http://mfem.github.io/doxygen/html/classmfem_1_1GridFunctionCoefficient.html, this is a Coefficient that has a GridFunction associated with it, in your case it could be the magnetic field. So you could just derive a new class from GridFunctionCoefficient that has whatever nonlinearity you need in your implementation of Eval.

In the Joule miniapp we use a std:mapp just like you suggest to map element attribute (1-based !!!) to material property, see http://mfem.github.io/doxygen/html/joule__solver_8hpp_source.html. The Joule example just uses constant material properties.

**Comment by tuckerbabcock** [comment]
Okay, I like the approach used by `MeshDependentCoefficient` from the Joule miniapp for the container. Is this comment old, I don't see any grid functions used? https://github.com/mfem/mfem/blob/632857c15dd10f86daa603546c98015f1da137fc/miniapps/electromagnetics/joule_solver.hpp#L45

If it's not old, is it inefficient to use a `GridFunction` in a way similar to the `JouleHeatingCoefficient`? A different (possibly naive) approach I thought of would be to implement a method in `JouleHeatingCoefficient` called `SetE()` which would set the vector `E` similar in spirit to using `SetTime()` for a time-dependent `FunctionCoefficient`. I'd have to call `SetE()` before `Eval()` every time it's called which could be impractical depending on the scope of the call to `Eval()`, since `E` at the appropriate point might not be in scope or computable without access to the `GridFunction`. Because of this it seems like the `Coefficient` having a reference to the `GridFunction` as is done in by `JouleHeatingCoefficient` would be a more appropriate and general choice unless it had some downsides I'm not seeing?
