### ISSUE TITLE
An interface to the Ginkgo library

### ISSUE THREAD

**Issue by pratikvn** [mfem/mfem#1092]
Hello all,

We are developing a high performance numerical linear algebra library called [Ginkgo](https://github.com/ginkgo-project/ginkgo). Some of its important features include:

1. Support for multi-threaded (OpenMP) and GPU (currently CUDA, HIP soon.) execution.
2. It will also be a part of latest xSDK release.
3. Support for many iterative linear solvers.
4. Support for preconditioners, especially a very well-performant adaptive precision block-jacobi preconditioner.
5. Support for various matrix formats and hence high performant SpMV's especially on GPU's. 
6. A very modular approach making it easy for new feature additions. 
7. Extensive [testing using gtest](https://codecov.io/gh/ginkgo-project/ginkgo) and [documentation using doxygen.](https://ginkgo-project.github.io/ginkgo/doc/develop/)

We would be interested in adding an interface to MFEM. We have an interface to [deal.ii](https://github.com/dealii/dealii/blob/master/include/deal.II/lac/ginkgo_solver.h) and would like to add a similar interface to MFEM.

We would like to know any requirements that you have for interfacing and any suggestions/comments you have.

@hartwiganzt is also available to clarify any subsequent questions.

**Comment by tzanio** [comment]
Hi @pratikvn and @hartwiganzt,

Yes, we will be interested in having a Ginkgo interface in MFEM and will be happy to help in developing it.

Please review our [`CONTRIBUTING.md`](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md) document and let us know if you have any questions. In particular, we prefer that new feature branch are created inside the MFEM organization. I will sent you an invitation to join.

In terms of code organization, our linear algebra components are in the [`linalg/`](https://github.com/mfem/mfem/tree/master/linalg) directory with e.g. serial sparse matrix definition in [`linalg/sparsemat.hpp`](https://github.com/mfem/mfem/blob/master/linalg/sparsemat.hpp). We use hypre to describe MPI-parallel sparse matrices and preconditioner, see e.g. [`linalg/hypre.hpp`](https://github.com/mfem/mfem/blob/master/linalg/hypre.hpp). As of MFEM-4.0 we have general device support with multiple backends, see e.g. [`general/device.hpp`](https://github.com/mfem/mfem/blob/master/general/device.hpp) and its use in [Example 1](https://github.com/mfem/mfem/blob/master/examples/ex1.cpp#L28-L34).

Let us know if you have any further questions.

Cheers,
Tzanio

**Comment by pratikvn** [comment]
Thanks @tzanio . I will create a branch from `master` and start working on the interface. As a first step I would like to add Ginkgo just as a plug-in where it would take the matrix, the solution vector and the right hand side in mfem format and give the computed solution converted back to mfem format. All the necessary paramters could be passed in when creating the ginkgo solver object within mfem. I currently envision the interface to look like this:

`linalg/ginkgo.hpp`:
1. Has a `IterativeSolverBase` class that contains the Base class that takes in the SolverControl parameters and the solver settings as parameters for its constructor. This base class would contain three methods: `initialize`, `apply` and `solve` which would convert the matrix into Ginkgo format, `apply` the solver and call the initialize and apply (user calls this) respectively.
2. The specific `XSolver` classes where `X = [CG, BICGSTAB, GMRES ... ]` which derive from the `IterativeSolverBase` class and build the actual solver factories.

`linalg/ginkgo.cpp`:
1. Implements the classes defined in the header files.

Some notes/questions:
1. The executor (`omp`, `cuda`, `reference`) which defines the execution space would be a parameter in the creation of the solver object and the user would pass it in, probably as a string. The initialize function would then explicitly convert (and copy) to the necessary execution space. I guess this is okay ? Would you have some better suggestions for this ? I could try and check if the object (matrix and vectors) are in the device memory and not copy them, but I think this could complicate things.
2. I see that you do not template for the precision formats (`double, float, int32, int64`). Do you expect this to be added some time ? I had a look and everything seems to be in `double` for the floating point types and `int32` for the integer types. So, I should just use these ?

**Comment by jandrej** [comment]
> CMake detection: We use linking through an alias target to automatically link the library to an external one. I think this is clearer than exporting specific variables through ${TPL}_LIBRARIES and ${TPL_INCLUDE_DIRS}. I currently add it when linking the mfem to each of the libraries in the main CMakeLists.txt file. Is this okay ?

If the library that you link supports it (obivously it does here), that is the correct way to do it.

**Comment by acfisher** [comment]
@pratikvn just a note on #1 for ginko.hpp.  MFEM already has an IterativeSolver base class, so it would be best to inherit from that.  You can of course still have a GinkoIterativeSolver class under it if that makes sense.

For question #3, yes we currently are using 64 bit doubles and 32 bit ints everywhere.  I don't think we are going to change this anytime soon.

**Comment by v-dobrev** [comment]
Just to add to Aaron's answer: for global indices (across all MPI ranks) we use the `HYPRE_Int` type which will be 64-bit when hypre is build with the "enable-bigint" option. In particular, if solving a problem with more than ~2 billion unknowns, that option should be enabled in hypre.

**Comment by pratikvn** [comment]
Thank you @jandrej , @acfisher and @v-dobrev . I have created a PR #1127 . We can move this discussion there.

**Comment by tzanio** [comment]
Superseded by the discussion in PR #1127.
