### ISSUE TITLE
How to obtain Interface integral?

### ISSUE THREAD

**Issue by fanronghong** [mfem/mfem#1093]
Hi all,

I want to do interface integral (not boundary integral), which is located inside the mesh and marked by interface_mark(an `Array<int>`), like an edge of 2D triangle element.
I know `AddDomainIntegrator`, `AddBoundaryIntegrator`, `AddBdrFaceIntegrator` and `NormalTraceJumpIntegrator`. But they can not be used right?
I saw these materials: 
[Evaluating surface integrals of a grid function](https://github.com/mfem/mfem/issues/599#issue-356588211),
[How to compute integral using BoundaryNormalLFIntegrator](https://github.com/mfem/mfem/issues/993#issue-463963084)
```
#include "mfem.hpp"

using namespace mfem;
using namespace std;


int main()
{
    Mesh mesh(1, 1, Element::TRIANGLE, 1.0, 1.0);
    for (int i=0; i<3; i++) mesh.UniformRefinement();
    int dim = mesh.Dimension();

    const int p_order = 1;
    H1_FECollection h1_fec(p_order, dim);
    FiniteElementSpace h1_space(&mesh, &h1_fec);

    ConstantCoefficient one(1.0);

    LinearForm lf(&h1_space);
    // here, I think there must be something like AddInterfaceIntegrator and MyInterfaceIntegrator.
    // interior face integral, not boundary face integral.
    lf.AddInterfaceIntegrator(new MyInterfaceIntegrator(one, interface_markers));
    lf.Assemble();

    return 0;
}
```

**Comment by tzanio** [comment]
One option is to mark the interior interface as boundary (the "boundary" elements do not to be physically on the boundary) and then use a linear form with an attribute restricted to just that portion.

If that is not feasible, I believe @mlstowell has been working on a subset integration capability in https://github.com/mfem/mfem/tree/entity-sets-dev and may be able to help.

**Comment by fanronghong** [comment]
Thanks @tzanio .

**Comment by NikolayYavich** [comment]
Hello,

earlier there was a suggestion  _to mark the interior interface as boundary_.
Could someone provide an example please?

Thanks  a lot,
Nikolay.
