### ISSUE TITLE
Solving Poisson equation with spatially-varying tensor coefficients

### ISSUE THREAD

**Issue by nebulaekg** [mfem/mfem#1094]
Can anyone indicate how to use mfem to solve a Poisson equation with spatially-varying tensor coefficients? 

Specifically, I want to solve the following:
![Screenshot from 2019-10-01 21-48-17](https://user-images.githubusercontent.com/10822134/66016761-390e2880-e495-11e9-8087-7715f6d9fc2d.png)
where 
![Screenshot from 2019-10-01 21-49-37](https://user-images.githubusercontent.com/10822134/66016883-cc475e00-e495-11e9-9da3-9b5055da108b.png)
with zero Dirichlet and zero Neumann boundary conditions. xs is a spatial point, and f is a scalar. 

In MFEM, how to define this spatially varying tensor C(x)? For example, from an external file consisting of (x, y, C), or from an internal array with these values. 

I also suggest MFEM can add such an example in the Examples pool. 

Thank you very much!

**Comment by fanronghong** [comment]
Hi, 
I think `class MatrixFunctionCoefficient` will be useful.
And from external file, you can form a c-function, whose function signature is `(*Function)(const Vector &, DenseMatrix &)`

**Comment by tzanio** [comment]
@fanronghong answer is correct. 

You should be able to make a simple modification to Example 1, see e.g. https://github.com/mfem/mfem/blob/master/tests/unit/fem/test_2d_bilininteg.cpp#L528-L536.
