### ISSUE TITLE
How to know the partion informations after Pmesh setup

### ISSUE THREAD

**Issue by ztdepztdep** [mfem/mfem#1095]
Dear sir:
    A new Pmesh is created from my old FVM mesh, I need to know the relationship between the index ordering of my old mesh and the new Pmesh.Which function provide this functionality.
Regards

**Comment by tzanio** [comment]
This information is available only in the `ParMesh` constructor and is generally lost once the parallel mesh is created. 

What specifically you are trying to do? There could be another way to do achieve it...

**Comment by ztdepztdep** [comment]
> This information is available only in the `ParMesh` constructor and is generally lost once the parallel mesh is created.
> 
> What specifically you are trying to do? There could be another way to do achieve it...

  I want to get the global index of ghost cell information. MFem doesn't provide this API.

**Comment by tzanio** [comment]
Can you create a piecewise-constant grid function with the element number and transfer it to the parallel mesh as discussed here: https://github.com/mfem/mfem/issues/1155#issuecomment-554138100?

**Comment by tzanio** [comment]
@ztdepztdep, were you able to resolve this?
