### ISSUE TITLE
OpenMP == parallel?

### ISSUE THREAD

**Issue by bradfc** [mfem/mfem#1098]
I am building MFEM on an Odroid N2 - a 6-core SOC with ARM architecture.  It runs Ubuntu with gcc and OpenMP installed.  I would like for MFEM to run with OpenMP, but I have no need for MPI.  From the documentation, I cannot discern the precise meaning of 'parallel' - either builds (configure, Makefile) or examples.

If I want *only* OpenMP, can I compile the serial version only?  Does that also mean that I have no need for HYPRE or METIS?

Part of my problem is that with ARM architecture I essentially have to build everything, and each package has additional dependencies that I must then satisfy, so the fewest installations I really need, the better.

**Comment by v-dobrev** [comment]
In most cases "parallel" means MPI-parallel. If you want only OpenMP, you can just use the "serial" build (serial == no MPI) which does not need hypre or metis.

Note that the OpenMP parallelism is fairly limited at this point, so if you want to take full advantage of 6 cores, you probably want to use MPI parallelism.
