### ISSUE TITLE
How to solve a linear system `Ax=b` with `A` as a DenseMatrix?

### ISSUE THREAD

**Issue by geyan3566** [mfem/mfem#1099]
Hi folks,

I constructed a linear system `Ax=b` with `A` as a Densematrix type and `x` and `b` are Vector. 
How to solve this linear system in mfem? Can I use dynamic_cast or static _cast?

Thanks,
G

**Comment by jandrej** [comment]
Hi,

you can use `DenseMatrixInverse` https://github.com/mfem/mfem/blob/master/linalg/densemat.hpp#L549 for that without converting them into a SparseMatrix. If your system is relatively small, of course.

**Comment by geyan3566** [comment]
In my case, `A` is not a square matrix. 
Is there another way to do this? The system size is small.

**Comment by mlstowell** [comment]
Hi, @geyan3566 ,
If your matrix is not square then you need a [pseudo-inverse](https://en.wikipedia.org/wiki/Moore–Penrose_inverse) .  I don't believe we currently have this in MFEM so you may need to use NumPy or LAPACK.  You can access the matrix data in a form that LAPACK expects by using the `DenseMatrix::GetData()` method.

Best wishes,
Mark

**Comment by tzanio** [comment]
There may be other options, but here are three suggestions:

1. If the matrix is 2x1, 3x1, or 3x2, use `CalcInverse(const DenseMatrix &a, DenseMatrix &inva)`

1. You can call a LAPACK function with the `DenseMatrix` data, similar to the way we do it in the `Invert()` method: https://github.com/mfem/mfem/blob/master/linalg/densemat.cpp#L667-L694

2. You can form the least-squares problem `A^T A x = A^T b` yourself using  `DenseMatrix::Transpose()` and `MultAAt(const DenseMatrix &a, DenseMatrix &aat)` and then solve it as a square system. If the original problem has a solution and the condition number of `A` is not too large, this could be an OK way to solve it.

Hope this helps,
Tzanio

**Comment by geyan3566** [comment]
Thanks for all your responses.
I solved this problem by using `LAPACK`.

Thanks,
Ge
