### ISSUE TITLE
miniapps/performance/ex1p hangs on 40 or more processors

### ISSUE THREAD

**Issue by barker29** [mfem/mfem#110]
Running `miniapps/performance/ex1p` in the default configuration works fine on 1 to 39 processors but hangs after `Assembling the preconditioning matrix ... done, 1.655e-06s.` on 40 or more processors.

I have verified this on quartz with MFEM master at the LLNL bitbucket revision d72a2f7ba3ac522ac0 using gcc 4.9.3 and mvapich2-2.2, running with processor counts 16, 32, 36, 38, and 39 (which all work fine) and 40, 41, 48, 64 (which all hang at the same place). This is with MFEM compiled in debug mode but I have seen the same error in optimized mode.

 The error persists when (default) `-pc lor` is replaced with `-pc none`. I have seen the same error somewhere between 32 and 64 processors on cab, but was less diligent about documenting the exact revision/compiler etc.

Attached is the moab script and the output for a failing run with 40 processors on quartz.

[quartz40.moab.txt](https://github.com/mfem/mfem/files/717659/quartz40.moab.txt)
[slurm-166924.out.txt](https://github.com/mfem/mfem/files/717658/slurm-166924.out.txt)

**Comment by barker29** [comment]
Hi Tzanio,

I’ve seen the same error on cab between 32 and 64 processors, but I didn’t nail it down quite as carefully so I mostly reported on quartz.

Best,

Andrew

**Comment by tzanio** [comment]
Thanks Andrew,

This was indeed a deadlock bug that we were able to reproduce on our Linux boxes. @v-dobrev fixed it with 6741c176cc6.

Tzanio
