### ISSUE TITLE
Parallel of boundary conditions and SetBlock

### ISSUE THREAD

**Issue by yantingsa** [mfem/mfem#1103]
Hi,

I'm parallel a system with Operator class. I need to set the `BlockOperater`  in the Operator construction. It works fine when I run with 1 threads, but keep giving me the error message with more threads.
Here is the error message:

> Verification failed: (row_offsets[iRow+1] - row_offsets[iRow] == opt->NumRows() && col_offsets[iCol+1] - col_offsets[iCol] == opt->NumCols()) is false:
 --> incompatible Operator dimensions
 ... in function: void mfem::BlockOperator::SetBlock(int, int, mfem::Operator*, double)
 ... at line 64 of file: linalg/blockoperator.cpp

Here is my code part, would you please give me some hint to correct it.
```c++
diff_form_v = new ParBilinearForm(fes[0]);
diff_form_v->AddDomainIntegrator(new DiffusionIntegrator());
diff_form_v->Assemble();
// diff_form_v->EliminateEssentialBC(*ess_bdr[0], u.GetBlock(0), rhs.GetBlock(0));
diff_form_v->Finalize();
diff_mat_v = diff_form_v->ParallelAssemble();

diff_form_m = new ParBilinearForm(fes[1]);
diff_form_m->AddDomainIntegrator(new DiffusionIntegrator());
diff_form_m->Assemble();
// diff_form_m->EliminateEssentialBC(*ess_bdr[1], u.GetBlock(1), rhs.GetBlock(1));
diff_form_m->Finalize();
diff_mat_m = diff_form_m->ParallelAssemble();

// ConstantCoefficient cf12(a12), cf21(a21);
reac_form_vm = new ParBlockNonlinearForm(fes);
reac_form_vm->AddDomainIntegrator(new Sys_ReactionNLFIntegrator(coeff12, coeff21));
// reac_form_vm->SetEssentialBC(ess_bdr, rhs_bdr);

Residual = new BlockOperator(block_sets);
Residual->SetBlock(0, 0, diff_mat_v);
Residual->SetBlock(1, 1, diff_mat_m);
```

And could you give me some advice how wo parallel assemble the boundary conditions?
Thanks ahead.

**Comment by tzanio** [comment]
Can you provide the rest of the code, or at least the interface of `Sys_ReactionNLFIntegrator` and the finite element spaces?

**Comment by yantingsa** [comment]
Hi,

Thank you so much for replying. I fixed that problem. But I do have new problem right now. I currently just trying on parallel for my simple test problem. It's a reaction-diffusion problem. And when I construct my Jacobian using `HypreParMatrix` and `Add`, it keeping give the error

> Verification failed: (internal::hypre_ParCSRMatrixSum(A, beta, B.A) == 0) is false:
 --> error in hypre_ParCSRMatrixSum
 ... in function: mfem::HypreParMatrix& mfem::HypreParMatrix::Add(double, const mfem::HypreParMatrix&)
 ... in file: linalg/hypre.hpp:490

I do search this error on github, and using the newest version of MFEM. I think it may related to [#885](https://github.com/mfem/mfem/pull/885) and [884](https://github.com/mfem/mfem/pull/884). ex23 passed, but my test still failed. Here is my code.

`// Test if the reaction nonlinear form integrator works

#include "mfem.hpp"
#include <fstream>
#include <iostream>

#include "sys_reaction.hpp"

#define M_PI 3.14159265358979323846

using namespace std;
using namespace mfem;

const double a12 = 1.0;
const double a21 = 1.0;


double rhs_f(const Vector &r);
double rhs_g(const Vector &r);

double analytic_v(const Vector &r);
double analytic_m(const Vector &r);


class Block_Diff_Reac_Operator : public Operator
{
private:
  // Finite element spaces
  Array<ParFiniteElementSpace *> fes;

  Array<int> &block_sets;
  Array<int> &block_true_sets;

  // linear form
  ParLinearForm *f_rhs;
  ParLinearForm *g_rhs;

  // bilinear form and nonlinear form
  ParBilinearForm *diff_form_v, *diff_form_m;
  ParBlockNonlinearForm *reac_form_vm;

  HypreParMatrix *diff_mat_v, *diff_mat_m;

  NewtonSolver newton_solver;

  Solver *j_solver;

  Solver *j_prec;

  BlockOperator *Residual;
  BlockVector rhs, true_rhs;

  Coefficient &coeff12, &coeff21;
  mutable BlockOperator *Jacobian;
  Array<int> &ess_tdof_list_v;
  Array<int> &ess_tdof_list_m;
  mutable Vector w;

public:
  Block_Diff_Reac_Operator(Array<ParFiniteElementSpace *> space, Array<Array<int> *> &ess_bdr,
                           Array<int> &block, Array<int> &block_true,
                           BlockVector &u, BlockVector &u_true,
                           Coefficient &cf12, Coefficient &cf21);

  virtual Operator &GetGradient(const Vector &vm) const;
  virtual void Mult(const Vector &k, Vector &y) const;

  void Solve(Vector &vm) const;

  virtual ~Block_Diff_Reac_Operator();
};


int main(int argc, char *argv[])
{
  // 1. Initialize MPI
  int num_procs, myid;
  MPI_Init(&argc, &argv);
  MPI_Comm_size(MPI_COMM_WORLD, &num_procs);
  MPI_Comm_rank(MPI_COMM_WORLD, &myid);

  const char *mesh_file = "../mesh/square.msh";
  int order = 1;
  int ser_ref_levels = 1;
  bool visualization = true;

  int precision = 8;
  cout.precision(precision);

  OptionsParser args(argc, argv);
  args.AddOption(&ser_ref_levels, "-rs", "--refine_serial",
                 "Number of times to refine the mesh uniformly.");
  args.AddOption(&order, "-o", "--order",
                 "Order (degree) of the finite elements.");
  args.AddOption(&visualization, "-vis", "--visualization", "-no-vis",
                 "--no-visualization",
                 "Enable or disable GLVis visualization.");

  args.Parse();
  if(!args.Good())
  {
    if(myid == 0)
    {
      args.PrintUsage(cout);
    }
    MPI_Finalize();
    return 1;
  }
  if(myid == 0)
  {
    args.PrintOptions(cout);
  }


  Mesh *mesh = new Mesh(mesh_file, 1, 1);
  int dim = mesh->Dimension();

  for(int lev=0; lev<ser_ref_levels; lev++)
  {
    mesh->UniformRefinement();
  }

  ParMesh *pmesh = new ParMesh(MPI_COMM_WORLD, *mesh);
  delete mesh;

  H1_FECollection fe_coll(order, dim);

  ParFiniteElementSpace v_space(pmesh, &fe_coll);
  ParFiniteElementSpace m_space(pmesh, &fe_coll);

  Array<ParFiniteElementSpace *> spaces(2);
  spaces[0] = &v_space;
  spaces[1] = &m_space;

  HYPRE_Int v_size = v_space.GlobalTrueVSize();
  HYPRE_Int m_size = m_space.GlobalTrueVSize();

  Array<Array<int> *> ess_bdr(2);
  Array<int> ess_bdr_v(v_space.GetMesh()->bdr_attributes.Max());
  Array<int> ess_bdr_m(m_space.GetMesh()->bdr_attributes.Max());
  ess_bdr_v = 1;                          ess_bdr_m = 1;
  ess_bdr[0] = &ess_bdr_v;                ess_bdr[1] = &ess_bdr_m;

  if(myid == 0)
  {
    std::cout << "********************************************************\n";
    std::cout << "dim(v) = " << v_size << "\n";
    std::cout << "dim(m) = " << m_size << "\n";
    std::cout << "dim(v+m) = " << v_size + m_size << "\n";
    std::cout << "********************************************************\n";
  }


  Array<int> block_offsets(3);
  block_offsets[0] = 0;
  block_offsets[1] = v_space.GetVSize();
  block_offsets[2] = m_space.GetVSize();
  block_offsets.PartialSum();

  Array<int> block_trueOffsets(3);
  block_trueOffsets[0] = 0;
  block_trueOffsets[1] = v_space.TrueVSize();
  block_trueOffsets[2] = m_space.TrueVSize();
  block_trueOffsets.PartialSum();

  BlockVector vm(block_offsets), vm_true(block_trueOffsets);

  FunctionCoefficient exact_v(analytic_v);
  FunctionCoefficient exact_m(analytic_m);

  ParGridFunction v_gf(&v_space);
  ParGridFunction m_gf(&m_space);
  v_gf.MakeRef(&v_space, vm.GetBlock(0), 0);
  v_gf.ProjectCoefficient(exact_v);
  v_gf.SetTrueVector();
  v_gf.SetFromTrueVector();
  m_gf.MakeRef(&m_space, vm.GetBlock(1), 0);
  m_gf.ProjectCoefficient(exact_m);
  m_gf.SetTrueVector();
  m_gf.SetFromTrueVector();

  ConstantCoefficient c12(1.0);
  ConstantCoefficient c21(-1.0);
  Block_Diff_Reac_Operator oper(spaces, ess_bdr, block_offsets, block_trueOffsets,
    vm, vm_true, c12, c21);
  oper.Solve(vm_true);

  v_gf = vm.GetBlock(0);
//  v_gf.Distribute(&(vm.GetBlock(0)));
  m_gf = vm.GetBlock(1);
//  m_gf.Distribute(&(vm.GetBlock(1)));

  int order_quad = max(2, 2*order+1);
  const IntegrationRule *irs[Geometry::NumGeom];
  for(int i=0; i<Geometry::NumGeom; ++i)
  {
    irs[i] = &(IntRules.Get(i, order_quad));
  }

  double err_v = v_gf.ComputeL2Error(exact_v, irs);
  double norm_v = ComputeLpNorm(2., exact_v, *pmesh, irs);
  double err_m = m_gf.ComputeL2Error(exact_m, irs);
  double norm_m = ComputeLpNorm(2., exact_m, *pmesh, irs);

  if(myid == 0)
  {
    std::cout << "||v_h - v_ex|| = " << err_v << "\n";
    std::cout << "||v_h - v_ex|| / || v_ex || = " << err_v / norm_v << "\n";
    std::cout << "||m_h - m_ex|| = " << err_m << "\n";
    std::cout << "||m_h - m_ex|| / || m_ex || = " << err_m / norm_m << "\n";
  }

  delete pmesh;

  MPI_Finalize();
  return 0;
}


Block_Diff_Reac_Operator::Block_Diff_Reac_Operator(Array<ParFiniteElementSpace *> space,
                                       Array<Array<int> *> &ess_bdr,
                                       Array<int> &block, Array<int> &block_true,
                                       BlockVector &u, BlockVector &u_true,
                                       Coefficient &cf12, Coefficient &cf21)
    : Operator(space[0]->TrueVSize() + space[1]->TrueVSize()),
      block_sets(block), block_true_sets(block_true),
      newton_solver(space[0]->GetComm()), fes(space),
      Jacobian(NULL), Residual(NULL), rhs(block), true_rhs(block_true),
      coeff12(cf12), coeff21(cf21),
      ess_tdof_list_v(*ess_bdr[0]), ess_tdof_list_m(*ess_bdr[1]), w(height)
{
  FunctionCoefficient forcing_f(rhs_f);
  f_rhs = new ParLinearForm(fes[0]);
  f_rhs->Update(fes[0], rhs.GetBlock(0), 0);
  f_rhs->AddDomainIntegrator(new DomainLFIntegrator(forcing_f));
  f_rhs->Assemble();
  f_rhs->ParallelAssemble(true_rhs.GetBlock(0));

  FunctionCoefficient forcing_g(rhs_g);
  g_rhs = new ParLinearForm(fes[1]);
  g_rhs->Update(fes[1], rhs.GetBlock(1), 0);
  g_rhs->AddDomainIntegrator(new DomainLFIntegrator(forcing_g));
  g_rhs->Assemble();
  g_rhs->ParallelAssemble(true_rhs.GetBlock(1));

  diff_form_v = new ParBilinearForm(fes[0]);
  diff_form_v->AddDomainIntegrator(new DiffusionIntegrator());
  diff_form_v->Assemble();
  diff_form_v->EliminateEssentialBC(*ess_bdr[0], u.GetBlock(0), rhs.GetBlock(0));
  diff_form_v->Finalize();
  diff_mat_v = diff_form_v->ParallelAssemble();

  diff_form_m = new ParBilinearForm(fes[1]);
  diff_form_m->AddDomainIntegrator(new DiffusionIntegrator());
  diff_form_m->Assemble();
  diff_form_m->EliminateEssentialBC(*ess_bdr[1], u.GetBlock(1), rhs.GetBlock(1));
  diff_form_m->Finalize();
  diff_mat_m = diff_form_m->ParallelAssemble();

//  ConstantCoefficient cf12(a12), cf21(a21);
  reac_form_vm = new ParBlockNonlinearForm(fes);
  reac_form_vm->AddDomainIntegrator(new Sys_ReactionNLFIntegrator(coeff12, coeff21));

  Residual = new BlockOperator(block_true_sets);
  Residual->SetBlock(0, 0, diff_mat_v);
  Residual->SetBlock(1, 1, diff_mat_m);


  // Initialize the block diagonal preconditioner
//  Block_Diagonal_Preconditioner *block_diag_prec =
//    new Block_Diagonal_Preconditioner(fes, block_sets,
//                                      diff_form_v->SpMat(),
//                                      diff_form_m->SpMat());
//  j_prec = block_diag_prec;

  // set up the Jacobian solver
  GMRESSolver *j_gmres = new GMRESSolver(fes[0]->GetComm());
  j_gmres->iterative_mode = false;
  j_gmres->SetRelTol(1e-12);
  j_gmres->SetAbsTol(1e-12);
  j_gmres->SetMaxIter(300);
  j_gmres->SetPrintLevel(1);
//  j_gmres->SetPreconditioner(*j_prec);
  j_solver = j_gmres;

  newton_solver.iterative_mode = true;
  newton_solver.SetSolver(*j_solver);
  newton_solver.SetOperator(*this);
  newton_solver.SetPrintLevel(1);
  newton_solver.SetRelTol(1e-8);
  newton_solver.SetAbsTol(1e-10);
  newton_solver.SetMaxIter(100);

}

// solve the Newton system
void Block_Diff_Reac_Operator::Solve(Vector &u) const
{
//  Vector zero;
  newton_solver.Mult(true_rhs, u);
  MFEM_VERIFY(newton_solver.GetConverged(),
              "Newton Solver did not converge.");
}

// compute: y = Dx + H(x)
void Block_Diff_Reac_Operator::Mult(const Vector &k, Vector &y) const
{
  Vector z;
  reac_form_vm->Mult(k, y);
  Residual->Mult(k, w);
  y += w;
}

Operator &Block_Diff_Reac_Operator::GetGradient(const Vector &u) const
{
  delete Jacobian;
  Jacobian = new BlockOperator(block_true_sets);

  BlockOperator *grad_R = dynamic_cast<BlockOperator *>(&reac_form_vm->GetGradient(u));

  HypreParMatrix *reac_11 = dynamic_cast<HypreParMatrix *>(&grad_R->GetBlock(0, 0));
  HypreParMatrix *reac_22 = dynamic_cast<HypreParMatrix *>(&grad_R->GetBlock(1, 1));
  HypreParMatrix *reac_12 = dynamic_cast<HypreParMatrix *>(&grad_R->GetBlock(0, 1));
  HypreParMatrix *reac_21 = dynamic_cast<HypreParMatrix *>(&grad_R->GetBlock(1, 0));

  HYPRE_Int n_row_m = diff_mat_m->M();
  HYPRE_Int n_col_m = diff_mat_m->N();
  cout << "row_m = " << n_row_m << ", col_m = " << n_col_m << "\n";

  HYPRE_Int n_row_reac = reac_11->M();
  HYPRE_Int n_col_reac = reac_11->N();
  cout << "row_reac = " << n_row_reac << ", col_reac = " << n_col_reac << "\n";

  HYPRE_Int nnz_reac = reac_11->NNZ();
  HYPRE_Int nnz_v = diff_mat_v->NNZ();
  cout << "nnz_reac = " << nnz_reac << ", nnz_v = " << nnz_v << "\n";

  Jacobian->SetBlock(0, 0, Add(1.0, *diff_mat_v, 1.0, *reac_11));
  Jacobian->SetBlock(1, 1, Add(1.0, *diff_mat_m, 1.0, *reac_22));

//  Jacobian->SetBlock(0, 0, diff_mat_v);
//  Jacobian->SetBlock(1, 1, diff_mat_m);

  Jacobian->SetBlock(0, 1, reac_12);
  Jacobian->SetBlock(1, 0, reac_21);

  return *Jacobian;

}

Block_Diff_Reac_Operator::~Block_Diff_Reac_Operator()
{
  delete f_rhs;
  delete g_rhs;
  delete Jacobian;
  delete j_solver;
  delete diff_form_v;
  delete diff_form_m;
  delete diff_mat_v;
  delete diff_mat_m;
  delete reac_form_vm;
//  delete j_prec;
}


double rhs_f(const Vector &r)
{
  double x = r(0);
  double y = r(1);

  double v = sin(x) * sin(y);
  double m = cos(x) * cos(y);

  return 2.0*v + v*m;
//  return v*m;
//  return 2.0 * v;
}

double rhs_g(const Vector &r)
{
  double x = r(0);
  double y = r(1);

  double v = sin(x) * sin(y);
  double m = cos(x) * cos(y);

  return 2.0*m - v*m;
//  return v*m;
//  return 2.0 * m;
}


double analytic_v(const Vector &r)
{
  double x = r(0);
  double y = r(1);

  return sin(x) * sin(y);
}

double analytic_m(const Vector &r)
{
  double x = r(0);
  double y = r(1);

  return cos(x) * cos(y);
}
`

And the reaction file include the Nonlinear integrator is 
`// Programmer: Ting Yan @ SMU
//
// Date: 2018-June
//
// implemented the reaction nonlinear integrator for MFEM

#include "mfem.hpp"

using namespace std;
using namespace mfem;

// extern const int num_equation;


// Integration term inner(u*v, q)
class Sys_ReactionNLFIntegrator : public BlockNonlinearFormIntegrator
{
private:
  Coefficient *q12, *q21;
  Vector shape_v, shape_m;

public:
  Sys_ReactionNLFIntegrator(Coefficient &_q12, Coefficient &_q21)
      : q12(&_q12), q21(&_q21)  { }
//  Sys_ReactionNLFIntegrator() { };

  // Perform the local action of the NonlinearFormIntegrator
  virtual void AssembleElementVector(const Array<const FiniteElement *> &el,
                                     ElementTransformation &Tr,
                                     const Array<const Vector *> &elfun,
                                     const Array<Vector *> &elvec);

  // Assemble the local gradient matrix
  virtual void AssembleElementGrad(const Array<const FiniteElement*> &el,
                                   ElementTransformation &Tr,
                                   const Array<const Vector*> &elfun,
                                   const Array2D<DenseMatrix *> &elmats);
};


void Sys_ReactionNLFIntegrator::AssembleElementVector(
     const Array<const FiniteElement *> &el,
     ElementTransformation &Tr,
     const Array<const Vector *> &elfun,
     const Array<Vector *> &elvec)
{
  int dof_v = el[0]->GetDof();
  int dof_m = el[1]->GetDof();
//  int dof_c = el[2]->GetDof();
//  int dof_t = el[3]->GetDof();
//  const int num_equation = 4;
  shape_v.SetSize(dof_v);
  shape_m.SetSize(dof_m);

  elvec[0]->SetSize(dof_v);
  elvec[1]->SetSize(dof_m);

  *elvec[0] = 0.0;
  *elvec[1] = 0.0;

  const IntegrationRule *ir =
        &IntRules.Get(el[0]->GetGeomType(), 2*el[0]->GetOrder() + Tr.OrderW());

  for(int i = 0; i < ir->GetNPoints(); i++)
  {
    const IntegrationPoint &ip = ir->IntPoint(i);

    Tr.SetIntPoint(&ip);
    el[0]->CalcShape(ip, shape_v);
    el[1]->CalcShape(ip, shape_m);

    double val_quad_pt_v = shape_v * *elfun[0];
    double val_quad_pt_m = shape_m * *elfun[1];

    double c12 = q12->Eval(Tr, ip);
    double c21 = q21->Eval(Tr, ip);

    double w_v = Tr.Weight() * c12 * val_quad_pt_v * val_quad_pt_m;
    double w_m = Tr.Weight() * c21 * val_quad_pt_m * val_quad_pt_v;

    add(*elvec[0], ip.weight*w_v, shape_v, *elvec[0]);
    add(*elvec[1], ip.weight*w_m, shape_m, *elvec[1]);
  }
}

void Sys_ReactionNLFIntegrator::AssembleElementGrad(
     const Array<const FiniteElement*> &el,
     ElementTransformation &Tr,
     const Array<const Vector*> &elfun,
     const Array2D<DenseMatrix *> &elmats)
{
  int dof_v = el[0]->GetDof();
  int dof_m = el[1]->GetDof();

  shape_v.SetSize(dof_v);
  shape_m.SetSize(dof_m);

  elmats(0, 0)->SetSize(dof_v, dof_v);
  elmats(0, 1)->SetSize(dof_v, dof_m);
  elmats(1, 0)->SetSize(dof_m, dof_v);
  elmats(1, 1)->SetSize(dof_m, dof_m);

  *elmats(0, 0) = 0.0;              *elmats(0, 1) = 0.0;
  *elmats(1, 0) = 0.0;              *elmats(1, 1) = 0.0;

  const IntegrationRule *ir =
        &IntRules.Get(el[0]->GetGeomType(), 2*el[0]->GetOrder() + Tr.OrderW());

  for(int i = 0; i < ir->GetNPoints(); ++i)
  {
    const IntegrationPoint &ip = ir->IntPoint(i);

    Tr.SetIntPoint(&ip);
    el[0]->CalcShape(ip, shape_v);
    el[1]->CalcShape(ip, shape_m);

    double val_quad_pt_v = shape_v * *elfun[0];
    double val_quad_pt_m = shape_m * *elfun[1];

    double c12 = q12->Eval(Tr, ip);
    double c21 = q21->Eval(Tr, ip);

    double a11 = Tr.Weight() * c12 *  val_quad_pt_m;
    double a12 = Tr.Weight() * c12 *  val_quad_pt_v;
    double a21 = Tr.Weight() * c21 * val_quad_pt_m;
    double a22 = Tr.Weight() * c21 * val_quad_pt_v;

    AddMult_a_VVt(ip.weight*a11, shape_v, *elmats(0, 0));
    AddMult_a_VWt(ip.weight*a12, shape_v, shape_m, *elmats(0, 1));
    AddMult_a_VWt(ip.weight*a21, shape_m, shape_v, *elmats(1, 0));
    AddMult_a_VVt(ip.weight*a22, shape_m, *elmats(1, 1));
  }
}
`

So is there any suggestion how to fix this error?

**Comment by tzanio** [comment]
This error is because the `Add` function for parallel matrices has the following restriction:

```c++
/** @brief Return a new matrix `C = alpha*A + beta*B`, assuming that both `A`
    and `B` use the same row and column partitions and the same `col_map_offd`
    arrays. */
HypreParMatrix *Add(double alpha, const HypreParMatrix &A,
                    double beta,  const HypreParMatrix &B);
```

If the two parallel matrices don't match, you may need to explicitly assemble the sum of the integrators as a separate matrix.

Maybe @jakubcerveny, @mlstowell or @jamiebramwell have other suggestions.

Tzanio
