### ISSUE TITLE
Use Cmake to builds serial cuda optimized version on windows

### ISSUE THREAD

**Issue by agathacn** [mfem/mfem#1106]
I only choose MFEM_USE_CUDA  with cmake to build the solution, while I debug the program ex1 with visual studio , some error are like below:
MSB3721	命令“"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\nvcc.exe" -gencode=arch=compute_61,code=\"sm_61,compute_61\" --use-local-env -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64" -x cu  -IF:\MFEM\metis\include -IF:\MFEM\hypre\src\hypre\include -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include"     --keep-dir x64\Debug -maxrregcount=0  --machine 64 --compile -cudart static --expt-extended-lambda -ccbin C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe -Xcompiler="-Zi -Ob0" -g   -D"MFEM_CONFIG_FILE=\"F:/MFEM/mfem-master/build/config/_config.hpp\"" -D"CMAKE_INTDIR=\"Debug\"" -D"CMAKE_INTDIR=\"Debug\"" -D_MBCS -Xcompiler "/EHsc /W1 /nologo /Od /Fdmfem.dir\Debug\mfem.pdb /FS /Zi /RTC1 /MDd " -o mfem.dir\Debug\nonlininteg.obj "F:\MFEM\mfem-master\fem\nonlininteg.cpp"”已退出，返回代码为 1。	mfem	C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\BuildCustomizations\CUDA 10.1.targets	757	
who can tell me where the problem is?
Thanks!

**Comment by tzanio** [comment]
Unfortunately this is not enough information for us to be able to help you.

Can you provide the full output of the build? Are you able to compile and run other CUDA codes?

**Comment by ggcchh1a** [comment]
did you solve it?
