### ISSUE TITLE
Access to mesh points

### ISSUE THREAD

**Issue by bradfc** [mfem/mfem#1108]
I'm trying to use MFEM to solve a set of coupled reaction-diffusion equations with non-trivial geometry.  In order to understand the results and compare to data, I need two things:

1. access to the mesh points in standard (x, y, z) format (together with the data at each point).
2. the ability to sample the data on a plane (say, z=0) passing through the 3D space.

Advice on either of these would be helpful.

**Comment by jandrej** [comment]
You can take a look at #304.
```
   Vector point(2);
   point(0) = 0.5;
   point(1) = 0.5;
   DenseMatrix points(dim, 1);
   points.SetCol(0, point);

   Array<int> elem_ids;
   Array<IntegrationPoint> ips;
   
   mesh->FindPoints(points, elem_ids, ips);
   cout << x.GetValue(elem_ids[0], ips[0]) << endl;
```
This snippet finds a point in 2d space (but is easily extended to 3d by adding `point(3)` and setting the size appropriately). It returns an array of element ids and integration points which you can pass to a `GridFunction::GetValue` method.

For the plane-sample you have to come up with a sampling set of points in the `DenseMatrix points`. It is definitely possible but I would do it in a post-processing step using you favorite visualization tool.

Let me know if that works for you.

**Comment by bradfc** [comment]
Thanks for that input. If II request mesh refinement rather than work with a set that's specified in advance, it looks like I can get an ordered list of (x,y,z) points via FindPoints().  My related question is then how to get a list of solution output data in the same order (so I can associate with the grid points).

On the visualization tool: so far I haven't gotten GLVis or VisIt to build and/or work properly, but it looks like GLVis does not provide quantitative plots as best I can tell from the documentation.

**Comment by tzanio** [comment]
If you want to compare pictures, then I will recommend getting GLVis to work, as it can produce accurate plots in any cutting plane.

If you want to compare the actual values, in say a uniform or random set of points in your plane, then `FindPoints` is a good choice -- @kmittal2 can point you to the branch and help you use it.

**Comment by bradfc** [comment]
I need the values (there's quantitative data to which to compare).  In the meantime I hope I can create a filter through FunctionCoefficient to isolate the boundary surface in question.

**Comment by kmittal2** [comment]
Hi @bradfc , we have a utility called `FindPoints` that will allow you to interpolate any `GridFunction` at arbitrary points (defined in physical space) in the domain. Check out the [gslib-dev branch](https://github.com/mfem/mfem/tree/findpts-gslib-dev) where we have an [example](https://github.com/mfem/mfem/tree/findpts-gslib-dev/examples/gslib) and a Readme that explains how to get started with FindPoints. Once you set it up, send me an [email](mailto:mittal3@llnl.gov) and I can help you use it.

**Comment by tzanio** [comment]
@bradfc -- I'm closing this issue for now, but please feel free to reopen if you have further questions.
