### ISSUE TITLE
Questions on ParMesh

### ISSUE THREAD

**Issue by kvoronin** [mfem/mfem#111]
Hello!

While implementing a parallel 4d mesh generator from a parallel 3d mesh, I'm trying to create internal ParMesh structure following the general lines from existing ParMesh constructor. Now I got several questions about the ParMesh class.

What I understand (correct me if I am wrong):
1) The groups (which are then converted to the gtopo) contain all the groups of process indices which have something shared with the local process.
2) group_sfaces is a table which for each group of processes gives indices of shared faces (as numbered from 0 and then incremented while looking for the shared faces) for this group of processes.

For example, if there are two processes, then there are two groups = {0} and {0,1}. 
3) Why then group_sfaces has only one row? Is it because we just don't consider for group_sfaces group number 0 which is the local process itself?
4) Is the ordering of process numbers in a single group important? For example, for the case of two processors groups (as table, which I got from gtopo for a 3d mesh), the second group is {0,1} for process 0 and {1,0} for process 1.
5) what is the meshgen variable, will it be used somewhere if the mesh is already created or is it just some kind of info parameter? 

I would be grateful for any comments.

Thanks,
Kirill

**Comment by tzanio** [comment]
Hi Kiril,

You are correct about 1)-3).

Regarding 4), group 0 is always the "local" group that doesn't have any shared entities, see http://mfem.github.io/doxygen/html/communication_8hpp_source.html#l00052.

Regarding 5): `meshgen` describes the type of the mesh, see http://mfem.github.io/doxygen/html/classmfem_1_1Mesh.html#ae840fd4a3a6da40bbeaa4e33ce70345f. This is used in several `Mesh` and `ParMesh` functions (grep for it).

Hope this helps,
Tzanio

**Comment by kvoronin** [comment]
Thanks, @tzanio,

Now I am looking at ParMesh contructor in MFEM. At line 353, http://mfem.github.io/doxygen/html/pmesh_8cpp_source.html, MyRank is added as one of the processor groups to local variable "groups". Then in the end "groups" are converted into a ParMesh gtopo internal structure via gtopo.Create(). 

But when I print out group_lproc from a ParMesh object as obtained by
```
    Table group_lproc; 
    group_lproc.MakeI(pmesh.gtopo.NGroups());
    for ( int row = 0; row < pmesh.gtopo.NGroups(); ++row )
    {
        group_lproc.AddColumnsInRow(row, pmesh.gtopo.GetGroupSize(row));
    }
    group_lproc.MakeJ();
```
The first group is 0 for all ranks. Is this very first element of groups (the "local" group) changed from MyRank to 0 somewhere in gtopo.Create()? Are there any other changes to the groups there?
My aim is to take given groups from already existing ParMesh and copy it to the ParMesh which I am creating. So I thought that group_lproc would be the same as local variable "groups" in ParMesh constructor.

Could you please clarify this moment?

Thanks,
Kirill

**Comment by kvoronin** [comment]
Thanks, @tzanio!

It does help. 
I've got another question - on how vertices are locally numbered in a parmesh object. 

What I want to know is:
if, say, two processes share vertices A and B which have local indices i0 and j0 for process 0 and i0 > j0, then is it true that i1 > j1 where i1 and j1 are local indices of the same vertices A and B for process 1, or not?

Thanks,
Kirill

**Comment by tzanio** [comment]
> if, say, two processes share vertices A and B which have local indices i0 and j0 for process 0 and i0 > j0, then is it true that i1 > j1 where i1 and j1 are local indices of the same vertices A and B for process 1, or not?

Nope. 

The only thing you are guaranteed is that the vertices will be numbered in the same order in the row of `group_svert` that corresponds to the group for these two processors. The actual local numbering in each processor can be very different.

**Comment by kvoronin** [comment]
Thanks, @tzanio!

**Comment by kvoronin** [comment]
Could anyone please explain to me what should be stored in group_ldof table in pfespace->gcomm if pfespace is a ParFiniteElementSpace object? The linear finite element collection is used so that ldofs are the mesh vertices.

As a background, I am looking for a bug in my mesh generator which finally leads to wrong indices appearing in pspace->ldof_ltdof (same global index for different vertices = ldofs) for pspace built for the created ParMesh and linear finite element collection. So I am trying to understand which part of the pmesh is wrong.

Thanks,
Kirill

**Comment by kvoronin** [comment]
Could anyone give me in idea what is the purpose of renumeration of local vertices in parMesh constructor: http://mfem.github.io/doxygen/html/pmesh_8cpp_source.html#l00175?
Lines:
```
  175    // re-enumerate the local vertices to preserve the global ordering
  176    for (i = vert_counter = 0; i < vert_global_local.Size(); i++)
  177       if (vert_global_local[i] >= 0)
  178       {
  179          vert_global_local[i] = vert_counter++;
  180       }
```
Is it a necessary step? I mean, can I have an arbitrary global indices for local vertices on each process (of course, consistent for the shared vertices)?
In my mesh generator I don't do any local vertex renumeration and I see that in comparison with MFEM generator for the same serial mesh and partioning, I have different local vertex ordering. And this finally lead to a slightly different computation results. 
So, I wonder whether I have generated invalid ParMesh because of the ordering.

Thanks,
Kirill

**Comment by kvoronin** [comment]
@tzanio,
Another question about your comment - is it necessary to have the same order in the rows of group_s<entity> for the corresponding groups of the processors when I am generating these tables?
> The only thing you are guaranteed is that the vertices will be numbered in the same order in the row of group_svert that corresponds to the group for these two processors. The actual local numbering in each processor can be very different.

**Comment by tzanio** [comment]
Hi Kirill,

Yes, the shared entities should be ordered the same way in their group, on each of the processors that forms that group. This way you can communicate the data directly in the group.

Hope this helps,
Tzanio

**Comment by v-dobrev** [comment]
Hi Kirill,

To answer your question about the re-enumeration at [pmesh.cpp:175](https://github.com/mfem/mfem/blob/master/mesh/pmesh.cpp#L175): there are at least two reasons we do that: 1) when running on one processor, we want to preserve the vertex ordering from the serial mesh; and 2) this ordering is important in the method [`ParMesh::ReorientTetMesh()`](https://github.com/mfem/mfem/blob/master/mesh/pmesh.cpp#L2046). There may be other parts in the code where this local vertex ordering is important but I am not sure.

The method `ParMesh::ReorientTetMesh()` needs to be called when using Nedelec elements of order `>= 2` on tetrahedral meshes - see [this description](https://github.com/mfem/mfem/blob/master/mesh/mesh.hpp#L840) for some details.

Veselin

**Comment by kvoronin** [comment]
Thank you very much for the answers, @tzanio and @v-dobrev !

**Comment by kvoronin** [comment]
Hello again!
Could someone please explain what is exactly happening in the lines 550-573 in ParMesh constructor?
```
  550             switch (shared_faces[sface_counter]->GetType())
  551             {
  552                case Element::TRIANGLE:
  553                   sface_lface[sface_counter] = (*faces_tbl)(v[0], v[1], v[2]);
  554                   // mark the shared face for refinement by reorienting
  555                   // it according to the refinement flag in the tetrahedron
  556                   // to which this shared face belongs to.
  557                   {
  558                      int lface = sface_lface[sface_counter];
  559                      Tetrahedron *tet =
  560                         (Tetrahedron *)(elements[faces_info[lface].Elem1No]);
  561                      tet->GetMarkedFace(faces_info[lface].Elem1Inf/64, v);
  562                      // flip the shared face in the processor that owns the
  563                      // second element (in 'mesh')
  564                      {
  565                         int gl_el1, gl_el2;
  566                         mesh.GetFaceElements(i, &gl_el1, &gl_el2);
  567                         if (MyRank == partitioning[gl_el2])
  568                         {
  569                            std::swap(v[0], v[1]);
  570                         }
  571                      }
  572                   }
  573                   break;
```
At the moment I am implementing construction of 3D mesh from a 2D mesh, and actually I am able to create elements, boundary elements and vertices, as well as all shared entities with proper ordering. But the ParMesh object is still incorrect for the case of several mpi processes and I think this is because I don't do anything with refinement flags. 
1) How should I set the refinement related structures in the ParMesh for a tetrahedral case?
2) What should I look at when considering parallel case? With that, the serial mesh generation works fine. So the error resides somewhere in parallel part of the structure but likely not in the shared entities.

I would appreciate any help!

Thanks,
Kirill
