### ISSUE TITLE
element ordering after uniform refinement leads to poor decompositions of ncmesh

### ISSUE THREAD

**Issue by rw-anderson** [mfem/mfem#1110]
Implementation here: https://github.com/mfem/mfem/tree/uniform-refinement-element-ordering-dev

When a mesh is refined through the UniformRefinement() interface, the existing elements are retained, and new elements are appended to the list of elements.  As a result, a numbering pattern that starts like this, for example:
![Screenshot from 2019-10-10 13-49-46](https://user-images.githubusercontent.com/11507994/66605400-e4d60900-eb64-11e9-8050-3f73bdd96df4.png) 
becomes this under a single refinement:
![Screenshot from 2019-10-10 13-51-42](https://user-images.githubusercontent.com/11507994/66605524-1e0e7900-eb65-11e9-8f1b-22373d9ecf6a.png)

When using metis to partition, this is not much of an issue.  But an ncmesh partition is sensitive to the numbering of the root nodes.  A more "compact" numbering is preferred, where points close in element id space are close in mesh topology space.  If the simple 2x2 mesh above is refined twice, the resulting ncmesh partition on two processors is:
![Screenshot from 2019-10-10 14-00-04](https://user-images.githubusercontent.com/11507994/66606104-49459800-eb66-11e9-8176-c64442df8807.png)
which is pretty suboptimal.

I took a shot at reworking the uniform refinement code for 2d conforming quads, so that the original ordering is roughly preserved.  The numbering after one refinement is then:
![Screenshot from 2019-10-10 14-03-06](https://user-images.githubusercontent.com/11507994/66606347-b2c5a680-eb66-11e9-9c88-30218437a1c7.png)

The resulting ncmesh partition on 2 processors for 2 refinements is then:
![Screenshot from 2019-10-10 14-04-29](https://user-images.githubusercontent.com/11507994/66606455-e7d1f900-eb66-11e9-841d-e7846d07f936.png)
which is much better.

The partition on 3 processors is:
![Screenshot from 2019-10-10 14-05-14](https://user-images.githubusercontent.com/11507994/66606487-fe785000-eb66-11e9-838c-201a0c21d8db.png)

While it doesn't look optimal, neither does the metis partition:
![Screenshot from 2019-10-10 14-06-16](https://user-images.githubusercontent.com/11507994/66606544-24055980-eb67-11e9-90fd-888d830f457e.png)

The partition on 4 processors makes sense as well:
![Screenshot from 2019-10-10 14-07-08](https://user-images.githubusercontent.com/11507994/66606592-40a19180-eb67-11e9-939e-bfe780865bbf.png)

On something not perfectly structured like the star mesh, the current code gives:
![Screenshot from 2019-10-10 14-09-37](https://user-images.githubusercontent.com/11507994/66606742-9c6c1a80-eb67-11e9-800d-a28b810b21f1.png)
which is pretty egregious.

The new ordering gives:
![Screenshot from 2019-10-10 14-10-33](https://user-images.githubusercontent.com/11507994/66606822-bf96ca00-eb67-11e9-9d60-df2c687c190f.png)

A big improvement.

There are some remaining questions.  I am not sure how easily what I've done extends to NURBS meshes, for example.  I think a similar idea would work just fine, but I haven't tried it nor am I familiar with the NURBS internals to quickly try it.

I will submit a branch momentarily, but I thought I would create an issue to document what I've seen playing around with this so far.

**Comment by rw-anderson** [comment]
@jakubcerveny @tzanio @rieben1

**Comment by tzanio** [comment]
We should have addressed this a long time ago... Thanks for fixing it Bob!!

**Comment by rw-anderson** [comment]
I think the issue I was seeing in ex9 actually relates to the initial mesh being a high-order mesh, rather than it being about the DG method specifically.

**Comment by rw-anderson** [comment]
ex9 and ex9p now work, once the embedding calculation was fixed to reflect the new ordering.  The embedding was important when the initial mesh was higher order, since the nodes gridfunction had to be interpolated.
All tests pass on the branch.  It still remains to fix the 3d code in the same way.

**Comment by tzanio** [comment]
Superseded by the discussion in PR #1119.
