### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by MuhammadAdilUmer** [mfem/mfem#1111]
Hello Everyone,
I have installed packages like hyper, metis, OCCA, OpenMP, RAJA except CUDA.
I don't know if I need CUDA or not but I am not using GPU.
1) I want to know the list of packages to install the MFEM 4.0 to run all examples and miniapps
2) How can I install these packages? I have to install these packages individually or is there any way to install and configure with MFEM
3) I have executed some of the commands using Build with Cmake
What is meant by mfem-source-dir? Because I try the path of my mfem directory as:
>>cmake /home/muhammad/Downlo-4.0ads/mfem 
It doesn't work.
   mkdir <mfem-build-dir> ; cd <mfem-build-dir>
   cmake <mfem-source-dir>

   make -j 4   (assuming "UNIX Makefiles" generator)

CUDA build:
   (this build requires CMake 3.8 or newer)
   mkdir <mfem-build-dir> ; cd <mfem-build-dir>
   cmake <mfem-source-dir> -DMFEM_USE_CUDA=YES
   make -j 4

Example codes (serial/parallel, depending on the build):
   make examples -j 4

Build everything (library, examples and miniapps) with current configuration:
   make exec -j 4

Quick-check the build by running Example 1/1p (optional):
   make check
   make test 
muhammad@muhammad-All-Series:~/Downloads/Build$ make -j4
[  1%] Built target gtest
[  2%] Built target blt_openmp_smoke
[  5%] Built target RAJA
[  7%] Built target gtest_main
[  9%] Built target bis
[ 10%] Built target wave-eqn
[ 11%] Built target red-black-gauss-seidel
....
....
[ 90%] Built target test-forall-view.exe
[ 91%] Built target test-reduce.exe
[ 92%] Built target test-scan.exe
[ 96%] Built target test-reductions.exe
[ 96%] Built target test-segments.exe
[ 98%] Built target test-forall.exe
[100%] Built target test-indexset.exe
muhammad@muhammad-All-Series:~/Downloads/Build$ make test
Running tests...
Test project /home/muhammad/Downloads/Build
      Start  1: blt_gtest_smoke
 1/39 Test  #1: blt_gtest_smoke ..................   Passed    0.01 sec
      Start  2: blt_openmp_smoke
 2/39 Test  #2: blt_openmp_smoke .................   Passed    0.00 sec
      Start  3: tuple
 3/39 Test  #3: tuple ............................   Passed    0.25 sec
      Start  4: tuple_out_of_range
 4/39 Test  #4: tuple_out_of_range ...............   Passed    0.28 sec
      Start  5: accumulate
 5/39 Test  #5: accumulate .......................   Passed    0.14 sec
....
....
38/39 Test #38: test-forall-view.exe .............   Passed    0.02 sec
      Start 39: test-synchronize.exe
39/39 Test #39: test-synchronize.exe .............   Passed    0.00 sec

100% tests passed, 0 tests failed out of 39

Total Test time (real) =   7.54 sec
I don't know what to do next? How to install and configure the MFEM?

**Comment by v-dobrev** [comment]
If you do not want to use MPI parallelism, you can build MFEM without any external dependencies, see https://mfem.org/building/#serial-version-of-mfem-and-glvis and https://mfem.org/serial-tutorial/.

If you want to run with MPI parallelism, MFEM requires the metis and hypre libraries, see https://mfem.org/building/#parallel-mpi-version-of-mfem and https://mfem.org/parallel-tutorial/.

**Comment by MuhammadAdilUmer** [comment]
I am trying to build hypre to install MFEM with MPI and facing the following:
muhammad@muhammad-All-Series:/media/muhammad/Data/MFEM$ ls
glvis-3.4      hypre         hypre-2.11.2.tar.gz  mfem-4.0
glvis-3.4.tgz  hypre-2.11.2  metis-5.1.0.tar.gz   mfem-4.0.tgz
muhammad@muhammad-All-Series:/media/muhammad/Data/MFEM$ cd hypre-2.11.2 
muhammad@muhammad-All-Series:/media/muhammad/Data/MFEM/hypre-2.11.2$ ls
AUTOTEST  CHANGELOG  COPYING.LESSER  COPYRIGHT  docs  INSTALL  README  src
muhammad@muhammad-All-Series:/media/muhammad/Data/MFEM/hypre-2.11.2$ cd src
muhammad@muhammad-All-Series:/media/muhammad/Data/MFEM/hypre-2.11.2/src$ make -j4
Making /media/muhammad/Data/MFEM/hypre-2.11.2/src/blas ...
make[1]: Entering directory '/media/muhammad/Data/MFEM/hypre-2.11.2/src/blas'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/media/muhammad/Data/MFEM/hypre-2.11.2/src/blas'

Making /media/muhammad/Data/MFEM/hypre-2.11.2/src/lapack ...
make[1]: Entering directory '/media/muhammad/Data/MFEM/hypre-2.11.2/src/lapack'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/media/muhammad/Data/MFEM/hypre-2.11.2/src/lapack'

Making utilities ...
make[1]: Entering directory '/media/muhammad/Data/MFEM/hypre-2.11.2/src/utilities'
cp -fR ./HYPRE_*.h /media/muhammad/Data/MFEM/hypre-2.11.2/src/hypre/include
cp -fR ./_hypre_utilities.h /media/muhammad/Data/MFEM/hypre-2.11.2/src/hypre/include
cp -fR ./hypre_hopscotch_hash.h /media/muhammad/Data/MFEM/hypre-2.11.2/src/hypre/include
cp -fR ./fortran*.h /media/muhammad/Data/MFEM/hypre-2.11.2/src/hypre/include
make[1]: Leaving directory '/media/muhammad/Data/MFEM/hypre-2.11.2/src/utilities'
....
....
Making /media/muhammad/Data/MFEM/hypre-2.11.2/src/FEI_mv ...
make[1]: Entering directory '/media/muhammad/Data/MFEM/hypre-2.11.2/src/FEI_mv'
Making femli ...
make[2]: Entering directory '/media/muhammad/Data/MFEM/hypre-2.11.2/src/FEI_mv/femli'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/media/muhammad/Data/MFEM/hypre-2.11.2/src/FEI_mv/femli'
Making SuperLU ...
make[2]: Entering directory '/media/muhammad/Data/MFEM/hypre-2.11.2/src/FEI_mv/SuperLU'
( cd SRC; make all)
make[3]: Entering directory '/media/muhammad/Data/MFEM/hypre-2.11.2/src/FEI_mv/SuperLU/SRC'
cp -fp *.h /media/muhammad/Data/MFEM/hypre-2.11.2/src/hypre/include
make[3]: Leaving directory '/media/muhammad/Data/MFEM/hypre-2.11.2/src/FEI_mv/SuperLU/SRC'
make[2]: Leaving directory '/media/muhammad/Data/MFEM/hypre-2.11.2/src/FEI_mv/SuperLU'
Making fei-hypre ...
make[2]: Entering directory '/media/muhammad/Data/MFEM/hypre-2.11.2/src/FEI_mv/fei-hypre'
cp -fR ./cfei-hypre.h /media/muhammad/Data/MFEM/hypre-2.11.2/src/hypre/include
cp -fR ./cfei_hypre.h /media/muhammad/Data/MFEM/hypre-2.11.2/src/hypre/include
cp -fR ./hypre_cfei.h /media/muhammad/Data/MFEM/hypre-2.11.2/src/hypre/include
cp -fR ./HYPRE_LinSysCore.h /media/muhammad/Data/MFEM/hypre-2.11.2/src/hypre/include
cp -fR ./HYPRE_FEI*.h /media/muhammad/Data/MFEM/hypre-2.11.2/src/hypre/include
cp -fR ./LLNL_FEI*.h /media/muhammad/Data/MFEM/hypre-2.11.2/src/hypre/include
cp -fR /media/muhammad/Data/MFEM/hypre-2.11.2/src/FEI_mv/fei-base/fei_Data.hpp /media/muhammad/Data/MFEM/hypre-2.11.2/src/hypre/include
cp -fR /media/muhammad/Data/MFEM/hypre-2.11.2/src/FEI_mv/fei-base/fei_Lookup.hpp /media/muhammad/Data/MFEM/hypre-2.11.2/src/hypre/include
cp -fR /media/muhammad/Data/MFEM/hypre-2.11.2/src/FEI_mv/fei-base/fei_LinearSystemCore.hpp /media/muhammad/Data/MFEM/hypre-2.11.2/src/hypre/include
cp -fR /media/muhammad/Data/MFEM/hypre-2.11.2/src/FEI_mv/fei-base/cfei.h /media/muhammad/Data/MFEM/hypre-2.11.2/src/hypre/include
cp -fR /media/muhammad/Data/MFEM/hypre-2.11.2/src/FEI_mv/fei-base/fei_bool.h /media/muhammad/Data/MFEM/hypre-2.11.2/src/hypre/include
cp -fR /media/muhammad/Data/MFEM/hypre-2.11.2/src/FEI_mv/fei-base/fei_defs.h /media/muhammad/Data/MFEM/hypre-2.11.2/src/hypre/include
cp -fR /media/muhammad/Data/MFEM/hypre-2.11.2/src/FEI_mv/fei-base/fei_mpi.h /media/muhammad/Data/MFEM/hypre-2.11.2/src/hypre/include
make[2]: Leaving directory '/media/muhammad/Data/MFEM/hypre-2.11.2/src/FEI_mv/fei-hypre'
make[1]: Leaving directory '/media/muhammad/Data/MFEM/hypre-2.11.2/src/FEI_mv'

Making lib ...
make[1]: Entering directory '/media/muhammad/Data/MFEM/hypre-2.11.2/src/lib'
cp -fR libHYPRE* /media/muhammad/Data/MFEM/hypre-2.11.2/src/hypre/lib
make[1]: Leaving directory '/media/muhammad/Data/MFEM/hypre-2.11.2/src/lib'

**Comment by v-dobrev** [comment]
I don't see any errors in the output posted above. It looks like normal output from building hypre.
