### ISSUE TITLE
Build HypreParMatrix from SparseMatrix

### ISSUE THREAD

**Issue by e-aranda** [mfem/mfem#1114]
Hello,

I am trying to do the following: I have a mesh, and I have built some SparseMatrix associated to that mesh. Then, I build a ParMesh from my mesh, and I would like to "translate" my sparsematrix in a HypreParMatrix. Is it that possible?

**Comment by v-dobrev** [comment]
This should be possible by wrapping the `SparseMatrix` data as a `HYPRE_CSRMatrix` and then calling the hypre function:
```c++
HYPRE_Int HYPRE_CSRMatrixToParCSRMatrix(
   MPI_Comm comm,
   HYPRE_CSRMatrix A_CSR,
   HYPRE_BigInt *row_partitioning,
   HYPRE_BigInt *col_partitioning,
   HYPRE_ParCSRMatrix *matrix);
```
Then you can wrap the `HYPRE_ParCSRMatrix` as a `mfem::HypreParMatrix` using the constructor:
https://github.com/mfem/mfem/blob/632857c15dd10f86daa603546c98015f1da137fc/linalg/hypre.hpp#L239
since `HYPRE_ParCSRMatrix` is the same as `hypre_ParCSRMatrix *`.

The tricky part may be the partitioning arrays `row_partitioning` and `col_partitioning` depending on what your rows and columns in the `SparseMatrix` correspond to and how that is related to `Mesh`.

**Comment by e-aranda** [comment]
I am trying to create a `HYPRE_CSRMatrix` from my `SparseMatrix` but I don't know how to do it. The function

    HYPRE_CSRMatrixCreate(HYPRE_Int num_rows,HYPRE_Int num_cols,HYPRE_Int *row_sizes)

asks for a `row_sizes` array, but I don't know how to get that information from my `SparseMatrix`. 

Instead, I have been able to create a `hypre_CSRMatrix` in the following way:

    SparseMatrix *K; // this is my sparse matrix (built in some way)
    hypre_CSRMatrix *csr_a;
    csr_a = hypre_CSRMatrixCreate(K->Height(), K->Width(),K->NumNonZeroElems());
    hypre_CSRMatrixI(csr_a) = K->GetI();
    hypre_CSRMatrixJ(csr_a) = K->GetJ();
    hypre_CSRMatrixData(csr_a) = K->GetData();
    hypre_CSRMatrixSetRownnz(csr_a);

Now, I am trying to create the `hypre_ParCSRMatrix` using `hypre_CSRMatrixToParCSRMatrix` function, but I don't know the meaning of `row_partitioning` and  `col_partitioning`. I guess that they are related to a `partitioning` array generated with
  
    partitioning = mesh->GeneratePartitioning(num_procs);

but I have no found information about these two arrays. Can you give me a hint about these arrays? Thanks a lot!

**Comment by v-dobrev** [comment]
The partitioning arrays describe how you want the rows and columns of the serial matrix to be partitioned among the MPI ranks. In a standard hypre build these arrays have 2 entries: the first is the starting row/column index that will be given to the current MPI rank; the second entry is the starting index for the next MPI rank. This way each rank knows which portion of the rows/columns of the matrix it is responsible for.

**Comment by e-aranda** [comment]
I keep trying to build a `HypreParMatrix` from a `SparseMatrix` but I think I am missing something. 
So I have written a simple example where, first, I build a `HypreParMatrix`using a `DiffusionIntegrator` and print the result, and second, I create the same `SparseMatrix` by hand and  build the `HypreParMatrix`using the partitioning arrays from the previously created `HypreParMatrix`. 

Using only one processor, I have the same result, but when I use two processors the results are different. The numbering of the second parts of the matrices are not the same. 

I attach a zip file with the code and the mesh
[example.zip](https://github.com/mfem/mfem/files/3743645/example.zip)

**Comment by e-aranda** [comment]
Something in the partitioning arrays is not clear to me. I have been trying to figure out what's going on and here is an example:

	#include "mfem.hpp"
	#include <fstream>
	#include <iostream>

	using namespace std;
	using namespace mfem;

	int main(int argc, char *argv[])
	{

	  int num_procs, myid;
	  MPI_Init(&argc, &argv);
	  MPI_Comm_size(MPI_COMM_WORLD, &num_procs);
	  MPI_Comm_rank(MPI_COMM_WORLD, &myid);

	  int kki[19] = {0, 3, 6, 9, 11, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 45, 47, 50};

	  int kkj[50] = {0,  1,  2,  1,  2,  0,  2,  1,  0,  3,  5,  4,  5,  5,  4,  3,  6,
	        7,  8,  7,  8,  6,  8,  7,  6,  9, 10, 11, 10, 11,  9, 11, 10,  9,
	       12, 13, 14, 13, 14, 12, 14, 13, 12, 15, 17, 16, 17, 17, 16, 15};

	  double kkd[50] = {2.08859694, -0.98811599, -1.10048095,  2.78685005, -1.79873406,
	       -0.98811599,  2.899215  , -1.79873406, -1.10048095,  2.02561153,
	       -2.02561153,  2.39149175, -2.39149175,  4.41710328, -2.39149175,
	       -2.02561153,  1.92605086, -0.94324855, -0.98280231,  2.97705071,
	       -2.03380216, -0.94324855,  3.01660447, -2.03380216, -0.98280231,
	        1.19861914,  1.10048095, -2.29910009,  5.05188959, -6.15237054,
	        1.10048095,  8.45147063, -6.15237054, -2.29910009,  1.78498599,
	       -0.62281002, -1.16217598,  2.93118579, -2.30837577, -0.62281002,
	        3.47055175, -2.30837577, -1.16217598,  4.14801946, -4.14801946,
	        1.16784246, -1.16784246,  5.31586192, -1.16784246, -4.14801946};

	 // Building partitioning arrays for 2 processors
	  HYPRE_Int *row;
	  HYPRE_Int *col;
	  row = new HYPRE_Int[2];
	  col = new HYPRE_Int[2];
	  if (myid == 0){
	    row[0] = 0;	
	    row[1] = 9;
	    row[2] = 18;
	    col[0] = 0;
	    col[1] = 9;
	    col[2] = 18;
	  }

	  if (myid == 1){
	    row[0] = 9;	
	    row[1] = 18;
	    row[2] = 18;
	    col[0] = 9;
	    col[1] = 18;
	    col[2] = 18;
	  }
	 
	  // building a hypre_CSRMatrix
	  hypre_CSRMatrix *csr_a;
	  csr_a = hypre_CSRMatrixCreate(18, 18, 50);
	  hypre_CSRMatrixI(csr_a) = kki;
	  hypre_CSRMatrixJ(csr_a) = kkj;
	  hypre_CSRMatrixData(csr_a) = kkd;
	  hypre_CSRMatrixSetRownnz(csr_a);

	  // building a hypre_ParCSRMatrix
	  hypre_ParCSRMatrix *aa;
	  aa = hypre_CSRMatrixToParCSRMatrix(MPI_COMM_WORLD, csr_a, row, col);
	  
	  // Checking partitioning arrays
	  HYPRE_Int *newrow;
	  HYPRE_Int *newcol;
	  newrow = aa->row_starts;
	  newcol = aa->col_starts;

	  for (int i=0;i<3;i++)
	     cout << "Processor: " << myid << "  newrow[" << i << "] = " << newrow[i] << endl;  	

	  for (int i=0;i<3;i++)
	     cout << "Processor: " << myid << "  newcol[" << i << "] = "<< newcol[i] << endl;  	

	  MPI_Finalize();

	  return 0;
	}

I have created the partitioning arrays for 2 processors, but there have been overwritten. The result of this code is

    Processor: 0  newrow[0] = 0
    Processor: 0  newrow[1] = 9
    Processor: 0  newrow[2] = 18
    Processor: 0  newcol[0] = 0
    Processor: 0  newcol[1] = 9
    Processor: 0  newcol[2] = 18
    Processor: 1  newrow[0] = 0
    Processor: 1  newrow[1] = 9
    Processor: 1  newrow[2] = 18
    Processor: 1  newcol[0] = 0
    Processor: 1  newcol[1] = 9
    Processor: 1  newcol[2] = 18

What am I doing wrong?

**Comment by e-aranda** [comment]
Finally, I have figured out what was happening. It has to be with something it was commented at #67. As hypre was not built with `HYPRE_NO_GLOBAL_PARTITION` the function `hypre_CSRMatrixToParCSRMatrix` calls `hypre_GeneratePartitioning` which overwrites my partitioning arrays. 

I have used the `DistributeGloballyReplicatedMatrix` function in #67, with a minor correction, and now I can built my `HypreParMatrix`, using partitioning arrays obtained from `hypre_GenerateLocalPartitioning`.

My problem now is that `hypre_GenerateLocalPartitioning` generates different partitioning arrays than the partition associated to my ParMesh (which assigns non sequential indices to the different processes). Is there a way to define these partitioning arrays according to the indices of the ParMesh?

**Comment by e-aranda** [comment]
Well, finally I found a way to solve my problem and I would like to share the solution here in case anyone is interested.

I had a `SparseMatrix` built from some computations with a serial mesh. The i,j entry of my matrix is related to the elements i and j of the mesh, and I needed to perform some computations with that matrix in parallel, so I needed to build a `HypreParMatrix` from my `SparseMatrix`. 

As I mentioned in some comment above I have used the `DistributeGloballyReplicatedMatrix` function in #67 with a partitioning arrays built from the distribution of mesh elements in each processor. But, as the numbering of elements in `ParMesh` and the original numbering in the serial `Mesh` are different, I have had to sort the arrays from the `SparseMatrix` in (I think) not very elegant way. But it works!

    #include <HYPRE.h>
    #include <_hypre_parcsr_mv.h>
    #include <iostream>
    #include "mfem.hpp"

    using namespace std;
    using namespace mfem;

    hypre_ParCSRMatrix* DistributeGloballyReplicatedMatrix(
        MPI_Comm comm,
        HYPRE_Int* serial_I, HYPRE_Int* serial_J, HYPRE_Complex* serial_Data,
        HYPRE_Int* my_row_starts, HYPRE_Int* my_col_starts)
      {

        const HYPRE_Int global_num_rows = my_row_starts[2],
            global_num_cols = my_col_starts[2];

        const HYPRE_Int my_first_row = my_row_starts[0],
            my_last_row = my_row_starts[1];

        const HYPRE_Int my_first_col = my_col_starts[0],
            my_last_col = my_col_starts[1];

        const HYPRE_Int my_num_rows = my_last_row - my_first_row;


        // Create the offd_col_map first
        HYPRE_Int * global_idx_marker =
            (HYPRE_Int *) malloc(global_num_cols*sizeof(HYPRE_Int));

        for (int i=0;i<global_num_cols;i++)
            global_idx_marker[i] =  0;    

        HYPRE_Int num_shared_cols = 0, diag_nnz = 0, offd_nnz = 0;
        for (HYPRE_Int index = serial_I[my_first_row];
             index < serial_I[my_last_row];
             ++index)
        {
            const HYPRE_Int& the_global_column_index = serial_J[index];

            if ( (the_global_column_index < my_first_col) ||
                 (the_global_column_index >= my_last_col) )
            {
                // The index is outside my owned range; mark and up count
                if (!global_idx_marker[the_global_column_index])
                    global_idx_marker[the_global_column_index] = ++num_shared_cols;

                // Up nnz count
                offd_nnz++;
            }
            else
                diag_nnz++;
        }
       
        // Create the new matrix
        hypre_ParCSRMatrix * parallel_matrix = hypre_ParCSRMatrixCreate(
            comm,global_num_rows,global_num_cols,
            my_row_starts,my_col_starts,
            num_shared_cols,diag_nnz,offd_nnz);

        // In my case, I keep the partitioning arrays
        hypre_ParCSRMatrixOwnsRowStarts(parallel_matrix) = 0;
        hypre_ParCSRMatrixOwnsColStarts(parallel_matrix) = 0;

        // Initialize the matrix -- allocates Diag and Offd
        hypre_ParCSRMatrixInitialize(parallel_matrix);

        // Fill col_map_offd
        HYPRE_Int * col_map_offd = hypre_ParCSRMatrixColMapOffd(parallel_matrix);
        num_shared_cols = 0;
        for (size_t global_idx = 0;
             global_idx < global_num_cols;
             ++global_idx)
        {
            if (global_idx_marker[global_idx] > 0)
            {
                col_map_offd[num_shared_cols] = global_idx;
                global_idx_marker[global_idx] = ++num_shared_cols;
                // Note: this will mark each shared global idx with a
                // positive number, so
                //
                // local_idx = global_idx_marker[global_idx] - 1.
            }
        }
       

        // Copy the matrix data
        hypre_CSRMatrix * diag = hypre_ParCSRMatrixDiag(parallel_matrix),
            * offd = hypre_ParCSRMatrixOffd(parallel_matrix);

        HYPRE_Int * diag_i = hypre_CSRMatrixI(diag),
            * diag_j = hypre_CSRMatrixJ(diag);
        HYPRE_Complex * diag_data = hypre_CSRMatrixData(diag);

        HYPRE_Int * offd_i = hypre_CSRMatrixI(offd),
            * offd_j = hypre_CSRMatrixJ(offd);
        HYPRE_Complex * offd_data = hypre_CSRMatrixData(offd);

        diag_nnz = 0; offd_nnz = 0;
        for (HYPRE_Int global_row = my_first_row, local_row = 0;
             global_row < my_last_row;++global_row,++local_row)
        {
            diag_i[local_row] = diag_nnz;
            offd_i[local_row] = offd_nnz;

            for (HYPRE_Int j_idx = serial_I[global_row];
                 j_idx < serial_I[global_row+1]; ++j_idx)
            {
                const HYPRE_Int& global_idx = serial_J[j_idx];

                if ((global_idx < my_first_col) || (global_idx >= my_last_col))
                {
                    // Column is shared, add to offd
                    offd_j[offd_nnz] = global_idx_marker[global_idx] - 1;
                    offd_data[offd_nnz++] = serial_Data[j_idx];
                }
                else
                {
                    // Column is owned, add to diag
                    diag_j[diag_nnz] = global_idx - my_first_col;
                    diag_data[diag_nnz++] = serial_Data[j_idx];
                }
            }
        }
        diag_i[my_num_rows] = diag_nnz;
        offd_i[my_num_rows] = offd_nnz;

        // Hypre wants the diagonal entry to come first.
        HYPRE_Complex tmp_data;
        for (HYPRE_Int local_row=0; local_row < my_num_rows; ++local_row)
        {
            HYPRE_Int first_col = diag_i[local_row];
            for (HYPRE_Int j_idx = first_col; j_idx < diag_i[local_row+1]; ++j_idx)
            {
                if (diag_j[j_idx] == local_row)
                {
                    // Swap the column indices
                    diag_j[j_idx] = diag_j[first_col];
                    diag_j[first_col] = local_row;

                    // Swap the data
                    tmp_data = diag_data[j_idx];
                    diag_data[j_idx] = diag_data[first_col];
                    diag_data[first_col] = tmp_data;
                    break;
                }
            }
        }

        // Now the hypre_ParCSRMatrix should be built. Create the commpkg:
        hypre_MatvecCommPkgCreate(parallel_matrix);

        free(global_idx_marker);

        return parallel_matrix;
      }


    // example
    int main(int argc, char *argv[])
      {

        int num_procs, myid;
        MPI_Init(&argc, &argv);
        MPI_Comm_size(MPI_COMM_WORLD, &num_procs);
        MPI_Comm_rank(MPI_COMM_WORLD, &myid);
        // this example only works with 4 processors
        if (num_procs != 4)
        {
          if (myid == 0)
            cout << "Sorry, this example only works with 4 processors" << endl;
          MPI_Finalize();
          exit(0);
        }

        // the following data represents a sparsematrix build from a serial mesh
        // the i,j entry of the matrix is related with elements i and j from the 
        // mesh

        // partitioning of mesh elements for processors
        int partition[12] = {1, 1, 0, 0, 1, 2, 0, 3, 2, 2, 3, 3};
        
        // CSR SparseMatrix data
        int kki[13] = {0, 2, 5, 7, 10, 13, 16, 19, 22, 25, 27, 30, 32};

        int kkj[32] = {0, 1, 0, 1, 4, 2, 3, 2, 3, 6, 1, 4, 5, 4, 5, 8, 3, 6, 7, 6,
          7,10, 5, 8, 9, 8, 9, 7, 10, 11, 10, 11};

        double kkd[32] = {0.7505787040477184, 0.2494212959522815,
        0.23628426362779137, 0.7110456855879185, 0.05267005078429017,
        0.7505787040477184, 0.2494212959522816, 0.2362842636277914,
        0.7110456855879183, 0.052670050784290316, 0.05267005078429018,
        0.7110456855879185, 0.23628426362779134, 0.23628426362779134,
        0.7110456855879185, 0.05267005078429018, 0.05267005078429032,
        0.7110456855879184, 0.23628426362779134, 0.2362842636277913,
        0.7110456855879183, 0.052670050784290316, 0.052670050784290164,
        0.7110456855879185, 0.23628426362779145, 0.24942129595228155,
        0.7505787040477184, 0.0526700507842903, 0.7110456855879183,
        0.23628426362779148, 0.24942129595228166, 0.7505787040477184};

        int ne = 12; // number of elements in the mesh
        int size = 32; // number of nonzero elements 

        // We need to build a vector with the element numbers of all subdomains
        vector<int> parts;
        for (int i=0;i<ne;i++)
        if (myid == partition[i]) parts.push_back(i);

        int psize = parts.size();
        MPI_Barrier(MPI_COMM_WORLD);

        // dimensions of densities in each process
        int *array_psizes = new int[num_procs];
        MPI_Allgather(&psize,1,MPI_INT, array_psizes, 1, MPI_INT,MPI_COMM_WORLD);
        // strides
        int *disp = new int[num_procs];
        disp[0] = 0;
        for (int i=1;i<num_procs;i++)
          disp[i] = disp[i-1] + array_psizes[i-1];

        // the reorder array collects the numbering of elements of the serial mesh
        // distributed in each processor
        int *reorder = NULL;
        if (myid == 0)
          reorder = new int[ne];
        MPI_Gatherv(parts.data(),psize,MPI_INT, reorder, array_psizes, disp,
            MPI_INT,0,MPI_COMM_WORLD);

        // the invre array is the inverse permutation of reorder
        int *invre = NULL;
      

        // we now need to reorder arrays of the sparsematrix (in master process)
        
        // arrays for new sparsematrix
        int *newI = new int[ne+1];
        int *newJ = new int[size];
        double *newD = new double[size];
        
        if (myid == 0)
        {
          invre = new int[ne];
          for (int i=0;i<ne;i++)
          {
          	for (int j=0;j<ne;j++)
          		if (reorder[j] == i)
          		{
          			invre[i] = j;
          			break;
          		}
          }
          int *RJ = new int[size];
          double *RD = new double[size];

          // reorder kkj
          for (int i=0;i<size;i++)
           	RJ[i] = invre[kkj[i]];

          // sorting and newI
          newI[0] = 0;
          int k = 0;
          for (int i=0;i<ne; i++)
          {
            for (int j=kki[reorder[i]];j<kki[reorder[i]+1];j++)
        	  {
        	    newJ[k] = RJ[j];
        		  newD[k] = kkd[j];
              k++;
            }
        	newI[i+1] = newI[i] + kki[reorder[i]+1] - kki[reorder[i]];
          }     		


        }

        MPI_Barrier(MPI_COMM_WORLD);

        // sharing data to all processes
        MPI_Bcast(newI, ne+1, MPI_INT, 0, MPI_COMM_WORLD);
        MPI_Bcast(newJ,size, MPI_INT, 0, MPI_COMM_WORLD);
        MPI_Bcast(newD,size, MPI_DOUBLE, 0, MPI_COMM_WORLD);
           

        // row partitioning
        int *collect = new int[num_procs];

        MPI_Allgather(&psize, 1, MPI_INT, collect, 1, MPI_INT, MPI_COMM_WORLD);

        
        for (int i=1;i<num_procs;i++)
          collect[i] += collect[i-1];

        HYPRE_Int *row;
        row = new HYPRE_Int[3];
        if (myid == 0)
        {
          row[0] = 0;
          row[1] = collect[0];
        }
        else
        {
          row[0] = collect[myid-1];
          row[1] = collect[myid];
        }

        row[2] = ne;

        // hypre_ParCSRMatrix  is built
        hypre_ParCSRMatrix * aa;
        aa = DistributeGloballyReplicatedMatrix(MPI_COMM_WORLD,
        newI, newJ,newD, row,row);

        // finally, the HypreParMatrix
        HypreParMatrix *B = new HypreParMatrix(aa);


        string file_prefix = "testmatrix"; 
        B->Print(file_prefix.c_str());

        delete [] array_psizes;
        delete [] disp;
        delete [] reorder;
        delete [] invre;
        delete [] newI;
        delete [] newJ;
        delete [] newD;
        delete B;

        MPI_Finalize();

        return 0;
      }

**Comment by tzanio** [comment]
Thank you Ernesto!
