### ISSUE TITLE
Adjacency Information in MFEM

### ISSUE THREAD

**Issue by SamiullahMalik** [mfem/mfem#1115]
For a given 3D tetrahedral mesh, is it possible to perform the following
operations in MFEM:
1) iterate over all edges in the mesh
2) given an edge e, get all faces (triangles in this case) connected to
the edge
3) given an edge e, get all regions (tets in this case) connected to the
edge

**Comment by fanronghong** [comment]
Hi,

I know how to solve question 1 and 2, but not 3. Below is my solution.
```
#include "mfem.hpp"
#include <iostream>

using namespace mfem;
using namespace std;

void EdgeInfo(Mesh& mesh)
{
    const Table& edge2facet = *(mesh.GetFaceEdgeTable()); // Returns the face-to-edge Table (3D)
    Array<int> e2f;
    for (size_t i=0; i<mesh.GetNEdges(); i++)
    {
        cout << i+1 << "-th edge, facet indices: ";
        edge2facet.GetRow(i, e2f);
        for (size_t j=0; j<e2f.Size(); j++) {
            cout << e2f[j] << ", ";
        }
        cout << endl;
    }
}

int main()
{
    Mesh* mesh = new Mesh(5, 5, 5,Element::TETRAHEDRON, true, 1.0, 1.0, 1.0);

    EdgeInfo(*mesh);
    mesh->PrintInfo(cout << "mesh information:\n");
}
```

**Comment by v-dobrev** [comment]
Here is a code snippet illustrating this:
```c++
   // Determine edge-to-face connections
   Table &face_edge = *mesh.GetFaceEdgeTable();
   Table edge_face;
   Transpose(face_edge, edge_face);

   // Determine edge-to-element connections
   const Table &elem_edge = mesh.ElementToEdgeTable();
   Table edge_elem;
   Transpose(elem_edge, edge_elem);

   const int nedges = mesh.GetNEdges();
   for (int i = 0; i < nedges; i++)
   {
      const int nf = edge_face.RowSize(i);
      const int *fi = edge_face.GetRow(i);
      for (int j = 0; j < nf; j++)
      {
         // edge 'i' is an edge in face 'fi[j]'
      }
      const int ne = edge_elem.RowSize(i);
      const int *ei = edge_elem.GetRow(i);
      for (int j = 0; j < ne; j++)
      {
         // edge 'i' is an edge in element 'ei[j]'
      }
   }
```

**Comment by Samiullah-Malik** [comment]
Thanks for your help earlier.
I have a follow up question: For parallel meshes, can I get all the elements and faces connected to an edge (including those across a part boundary) with ElementToEdgeTable() and GetFaceEdgeTable()? 
I basically want to perform the same operations, as mentioned in my previous post, on parallel meshes.

I also saw a method GetFaceToAllElementTable() but I don't understand what exactly it returns.

Regards,
Sami

**Comment by v-dobrev** [comment]
The short answer is no. The methods `ElementToEdgeTable()` and `GetFaceEdgeTable()` will only return the local (to the MPI rank) connectivity in terms of the local element-, face-, and edge-indices.

It is probably not too difficult to emulate the serial code for transposing the local `Table`s by converting them first to `HypreParMatrix` and then transposing the resulting matrix which will take care of the necessary parallel communications. If you are interested in this approach, I can provide you with further details -- just let me know.

**Comment by Samiullah-Malik** [comment]
Hi @v-dobrev , thank you for your response. 
For my problem, I am using Nedelec elements. I want to build a patch around each edge (obtain all faces and elements connected to an edge) and then perform several computations on these patch entities. For example, I would like to
a) access the `ParGridFunction` and get vector field and curl values on each element in the patch.
b) compute flux integrals on each face in the patch.
Currently, in serial, I also reorder the faces connected to an edge ( obtained from `edge_face.GetRow(i)` ) in a clockwise/counter-clockwise direction. So, I would like to do that for parallel meshes as well. 

Will these operations be possible with the HypreParMatrix approach? Or is it possible to migrate the required elements to a local part and then perform these operations just as in serial?

**Comment by tzanio** [comment]
I'm not sure this "loop" perspective is the correct approach for this. While in some case (for DG) we keep face-neighbor elements in parallel, edge-neighbors are certainly not available, so the loops can not be just local.

Wouldn't it be easier to consider this a kind of `LinearForm` which is automatically assembled in parallel?

**Comment by tzanio** [comment]
This issues has been dormant for a while, so I'm closing it. Feel free to reopen if you still have questions.
