### ISSUE TITLE
Build CUDA for MFEM

### ISSUE THREAD

**Issue by MuhammadAdilUmer** [mfem/mfem#1116]
Hello Everyone,
I am trying to build CUDA for MFEM but getting errors.
>>cmake /home/muhammad/Downloads/mfem-4.0 -DMFEM_USE_CUDA=YES

muhammad@muhammad-All-Series:~/Downloads/Build$ cmake /home/muhammad/Downloads/mfem-4.0 -DMFEM_USE_CUDA=YES
-- (optional) USER_CONFIG = /home/muhammad/Downloads/mfem-4.0/config/user.cmake
-- USE_XSDK_DEFAULTS = 'OFF'
-- The CUDA compiler identification is unknown
CMake Error at CMakeLists.txt:92 (enable_language):
  No CMAKE_CUDA_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CUDACXX" or the CMake cache entry CMAKE_CUDA_COMPILER to the full
  path to the compiler, or to the compiler name if it is in the PATH.

-- Configuring incomplete, errors occurred!
See also "/home/muhammad/Downloads/Build/CMakeFiles/CMakeOutput.log".
See also "/home/muhammad/Downloads/Build/CMakeFiles/CMakeError.log".
Please kindly someone help.

**Comment by v-dobrev** [comment]
As the CMake message suggests, you need to tell CMake where the CUDA compiler is. To do that add the following option to the `cmake` command line: `-DCMAKE_CUDA_COMPILER=<path-to-nvcc>` where `<path-to-nvcc>` is the absolute path to the CUDA compiler, `nvcc`.
