### ISSUE TITLE
building problem

### ISSUE THREAD

**Issue by ShiyangZhang** [mfem/mfem#112]
Dear guys,
i got some problem when tried to run ex1p on HPC
It gives the following information:

$ make ex1p 
mpicxx  -O3 -I..  -I../../hypre-2.10.0b/src/hypre/include ex1p.cpp -o ex1p -L.. -lmfem -L../../metis-4.0 -lmetis -L../../hypre-2.10.0b/src/hypre/lib -lHYPRE -lrt
../../hypre-2.10.0b/src/hypre/lib/libHYPRE.a(mpistubs.o): In function `hypre_MPI_Address':
mpistubs.c:(.text+0x242): undefined reference to `MPI_Get_address'
../../hypre-2.10.0b/src/hypre/lib/libHYPRE.a(mpistubs.o): In function `hypre_MPI_Type_hvector':
mpistubs.c:(.text+0x7a2): undefined reference to `MPI_Type_create_hvector'
../../hypre-2.10.0b/src/hypre/lib/libHYPRE.a(mpistubs.o): In function `hypre_MPI_Type_struct':
mpistubs.c:(.text+0x82f): undefined reference to `MPI_Type_create_struct'
make: *** [ex1p] Error 1

and:

$which mpicxx
/usr/local/mpich-1.2.7p1-gnu2/bin/mpicxx

and

[syzhang@wave mfem-3.2]$ make status
MFEM_USE_MPI         = YES
MFEM_USE_METIS_5     = NO
MFEM_DEBUG           = NO
MFEM_USE_LAPACK      = NO
MFEM_THREAD_SAFE     = NO
MFEM_USE_OPENMP      = NO
MFEM_USE_MEMALLOC    = YES
MFEM_TIMER_TYPE      = 2
MFEM_USE_MESQUITE    = NO
MFEM_USE_SUITESPARSE = NO
MFEM_USE_SUPERLU     = NO
MFEM_USE_GECKO       = NO
MFEM_USE_GNUTLS      = NO
MFEM_USE_NETCDF      = NO
MFEM_CXX             = mpicxx
MFEM_CPPFLAGS        = 
MFEM_CXXFLAGS        = -O3
MFEM_INCFLAGS        = -I$(MFEM_INC_DIR)  -I$(MFEM_DIR)/../hypre-2.10.0b/src/hypre/include
MFEM_FLAGS           = $(MFEM_CPPFLAGS) $(MFEM_CXXFLAGS) $(MFEM_INCFLAGS)
MFEM_LIBS            = -L$(MFEM_LIB_DIR) -lmfem -L$(MFEM_DIR)/../metis-4.0 -lmetis -L$(MFEM_DIR)/../hypre-2.10.0b/src/hypre/lib -lHYPRE -lrt
MFEM_LIB_FILE        = $(MFEM_LIB_DIR)/libmfem.a
MFEM_BUILD_TAG       = Linux wave.math._removed-personal-information_.edu. x86_64
MFEM_PREFIX          = ./mfem
MFEM_INC_DIR         = $(MFEM_DIR)
MFEM_LIB_DIR         = $(MFEM_DIR)

How can I fix it?
Thank you.
Sincerely,
Shiyang

**Comment by jakubcerveny** [comment]
Hi Shiyang,

Just a quick guess, is HYPRE built with the same MPI framework as MFEM? I
would clean and rebuild HYPRE.

Jakub

**Comment by ShiyangZhang** [comment]
Dear Jakub,
Thanks for your answer, you are right.

hypre use mpiicc:
```

$ ./configure --disable-fortran
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for mpxlc... no
checking for mpixlc... no
checking for mpiicc... mpiicc
checking for mpxlC... no
checking for mpixlcxx... no
checking for mpiicpc... mpiicpc
checking whether make sets $(MAKE)... yes
checking for ranlib... ranlib
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether mpiicc accepts -g... yes
checking for mpiicc option to accept ISO C89... none needed
checking whether we are using the GNU C++ compiler... yes
checking whether mpiicpc accepts -g... yes
checking for MPI_Init... yes
checking for mpi.h... yes
checking for MPI_Comm_f2c... no
checking how to run the C preprocessor... mpiicc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking whether MPI_Comm_f2c is a macro... yes
checking for __gxx_personality_v0 in -lstdc++... yes
checking for cabs in -lm... yes
checking the hostname... wave.math.cuhk.edu.hk
checking the architecture... ./configure: line 7949: ./tarch: Permission denied
x86_64
configure: creating ./config.status
config.status: creating config/Makefile.config
config.status: creating HYPRE_config.h

```
mfem use mpiCC.

I tried to compile hypre with mpiCC but do not know how to do it:



I tried to compile hypre with mpiicc, but it failed:


```
compilation aborted for general/error.cpp (code 4)
make[1]: *** [general/error.o] Error 4
make[1]: *** Waiting for unfinished jobs....
/usr/local/intel/impi/4.0.1.007/intel64/include/mpicxx.h(45): catastrophic error: #error directive: "SEEK_SET is #defined but must not be for the C++ binding of MPI. Include mpi.h before stdio.h"
  #error "SEEK_SET is #defined but must not be for the C++ binding of MPI. Include mpi.h before stdio.h"

```

I am grateful for your help.

Sincerely,
Shiyang

**Comment by jakubcerveny** [comment]
Shiyang,

If you do ./configure --help in HYPRE you should see how to set your own
compiler, I'd start with something basic and use it for both HYPRE and MFEM.

Something like CXX=xxxxxx ./configure --disable-fortran

Jakub

**Comment by v-dobrev** [comment]
The compilers and options for building hypre can be configured with something like this:
```sh
./configure CXX="mpicxx" CC="mpicc" CFLAGS="-O3" CXXFLAGS="-O3" --disable-fortran --without-fei
```
Actually, when using the option `--without-fei`, I think, the C++ compiler is not used.

Veselin

**Comment by ShiyangZhang** [comment]
Dear guys,
Thank you so much and now it works!

Sincerely,
Shiyang
