### ISSUE TITLE
BilinearFormIntegrator using device memory

### ISSUE THREAD

**Issue by davidherreroperez** [mfem/mfem#1121]
Hi all,

I see device memory functionality is not implemented for bilinear form integrators. 

https://github.com/mfem/mfem/blob/master/fem/bilininteg.cpp

Is there any plan to introduce this functionality in the coming releases? I would appreciate it if you indicate to me if some branch is dealing with this issue.

Thank you in advance.

**Comment by v-dobrev** [comment]
Device support for bilinear form integrators (mass and diffusion, for now) is in separate files:

   https://github.com/mfem/mfem/blob/master/fem/bilininteg_mass.cpp
   https://github.com/mfem/mfem/blob/master/fem/bilininteg_diffusion.cpp

> Is there any plan to introduce this functionality in the coming releases?

Yes, we will be extending the device support to other integrators in the near future.

**Comment by tzanio** [comment]
I am closing this now, but please don't hesitate to reopen if you have further questions.
