### ISSUE TITLE
Face integral

### ISSUE THREAD

**Issue by fanronghong** [mfem/mfem#1122]
Hi all,

Suppose I have a mesh, which has only two tetrahedrons (denoted by `tet 1` and `tet 2`) shared with one triangle face `F`. The tetrahedron attributes are 1 and 2, respectively.
I have a `GridFunction w`, which is zero in tet with attribute 2.

I want to do face integral `\int_F (\nabla w \cdot n) v dS`, where `n` must be outward normal direction of `tet 1` and `v` is a test function. 
Below is about assembling on the face, but I don't know where is wrong (I checked with analytic integral and it's wrong)
```c++
void selfAssembleRHSElementVect1(FaceElementTransformations &Trans, Vector &elvect)
{        
    const Element* e1  = mesh->GetElement(Trans.Elem1No); 
    const Element* e2  = mesh->GetElement(Trans.Elem2No);
    int attr1 = e1->GetAttribute();
    int attr2 = e2->GetAttribute();
    const FiniteElement* fe1 = fes->GetFE(Trans.Elem1No);
    const FiniteElement* fe2 = fes->GetFE(Trans.Elem2No);

    int ndofs1 = fe1->GetDof();
    int ndofs2 = fe2->GetDof();
    shape1.SetSize(ndofs1);
    shape2.SetSize(ndofs2);
    elvect.SetSize(ndofs1 + ndofs2);
    elvect = 0.0;

    int dim = fe1->GetDim();
    normal.SetSize(dim);
    gradw.SetSize(dim);

    // Compute normal direction of face at center
    Geometry::Type geo_type = mesh->GetFaceGeometryType(Trans.Face->ElementNo);
    const IntegrationPoint *center = &Geometries.GetCenter(geo_type); // center of face
    Trans.Face->SetIntPoint(center);
    CalcOrtho(Trans.Face->Jacobian(), normal); // compute normal direction

    const IntegrationRule *ir = &IntRules.Get(Trans.FaceGeom, 2 * fe1->GetOrder());

    for (int i=0; i<ir->GetNPoints(); i++)
    {
        const IntegrationPoint& ip = ir->IntPoint(i);
        Trans.Face->SetIntPoint(&ip);
        IntegrationPoint eip;

        if (attr1 == 1 && attr2 == 2)
        {
            Trans.Loc1.Transform(ip, eip); 
            fe1->CalcShape(eip, shape1);
            
            Trans.Elem1->SetIntPoint(&eip);
            w.GetGradient(*(Trans.Elem1), gradw); // compute grad(w), error!!! how to fix it?

            //double val = Trans.Face->Weight() * ip.weight * (gradw * normal); // wrong!
            double val = ip.weight * (gradw * normal); // correct
            for (int j=0; j<ndofs1; j++)
            {
                elvect[j] += val*shape1[j]; // shape2 = 0.0; in tet with attribute 2, GridFunction w is zero
            }
        }
    }
}
```

**Comment by vikramsg** [comment]
It seems fine to me except I think ```Trans.Face->Weight()``` should not be present in the expression for val. Other than that,  I think one check that you can do is to see whether the gradients you get in gradw match with the analytic gradient.

**Comment by fanronghong** [comment]
Thanks for your reply @vikramsg ,

Yes, I need to delete `Trans.Face->Weight()` because the `normal` is not unit and its length is just the `Trans.Face->Weight()`.

I have checked `gradw` with the analytic gradient and it's wrong. I don't know why and how to compute gradient correctly for a given `GridFunction`?

**Comment by fanronghong** [comment]
Hi, I have another question.

Because the faces on which I want to do integral are interior faces, how to decide the direction of the face normal?

For example, I have a mesh which has 2 tetrahedrons shared with 1 face. Now I have to know the face normal direction is pointing to which tet.

**Comment by YohannDudouit** [comment]
The normal is oriented from `elem1` to `elem2`, as given by the `FaceElementTransformations` in `fem/eltrans.hpp`.

**Comment by fanronghong** [comment]
Hi @YohannDudouit , thanks for your reply.

Yes, the normal is oriented from `Elem1No` to `Elem2No`. But for a given interior face, how do you know which element is `Elem1No`?

**Comment by YohannDudouit** [comment]
I know two ways to access this information, either by the `mesh` class and the method `void GetFaceElements (int Face, int *Elem1, int *Elem2) const`. This method returns `Elem1` and `Elem2` by their index corresponding to the face of index `Face`.
Or with the `FaceElementTransformations`, the `Elem1No` and `Elem2No` are the index of each element on the face.

**Comment by fanronghong** [comment]
Hi @YohannDudouit ,

Sorry not to express my question clearly. Yes, with `FaceElementTransformations`, we can know the `Elem1` index (i.e., `Elem1No`) and `Elem2` index (i.e., `Elem2No`) and the face normal is from `Elem1` to `Elem2`. But how does MFEM decide which element is 1 and which element is 2?

**Comment by YohannDudouit** [comment]
@v-dobrev might be able to give more details about this, but I believe that this is done arbitrarily when the mesh is read. Basically, I think that the first element (by its index) that contains the face `f` is `Elem1`.

**Comment by fanronghong** [comment]
Hi @YohannDudouit ,

Maybe it is arbitrary. And I know the face normal direction is from the smaller index of element(`Elem1`) to the bigger index of element(`Elem2`) in some other FEM package. But I don't know which way MFEM uses.

**Comment by v-dobrev** [comment]
Currently, the first element, `Elem1`, is the element with the smaller index, so the face normals point from the element with the smaller index into the element with the larger index. At least this is the case when the normal vector is computed as in the following code: https://github.com/mfem/mfem/blob/c55c80d17b82d80de04b849dd526e17044f8c99a/fem/bilininteg.cpp#L2457-L2464

In particular, for faces on the boundary, the normal will point outside of the domain.

**Comment by fanronghong** [comment]
Thank you very much for your explanation @v-dobrev . For interior faces, I understand its normal direction clearly.

Sorry to bother you again. I have another question. From [here](https://github.com/mfem/mfem/blob/c55c80d17b82d80de04b849dd526e17044f8c99a/mesh/mesh_readers.cpp#L1237), we can see that for 3D tet Gmsh mesh all triangles become boundary elements in MFEM even if the triangle face is an interior face.

Now I know the usual boundary faces'(located on the boundary of the whole domain) normal directions are outward. But how about the interior boundary faces? Are their normals also pointing from the element with the smaller index into the element with the larger index?

Because I want to use 
```
    LinearForm lf(&h1_space);
    lf.AddBoundaryIntegrator(new BoundaryNormalLFIntegrator(sin_func), marker);
    lf.Assemble();
```
I must be sure the interior face (here be treated as some marked boundary elements) normal direction.

**Comment by v-dobrev** [comment]
In 3D, the orientations of face elements that are read from a file (becoming "boundary" elements in MFEM) are not modified, unless they are on the boundary and point in the wrong direction, i.e. inside the domain.

Regarding the gradient computation: I don't see a problem with the code. What type of space is `w` defined on?

**Comment by fanronghong** [comment]
Thanks @v-dobrev .

For 3D mesh, the orientations of "boundary" (read from a file, not physical boundary) face elements are decided by the right-hand rule, right?

About the gradient computation, `w` is in `H1 finite element space`. I think the problem may be caused by numerical accuracy, right?

**Comment by v-dobrev** [comment]
In MFEM, the normal direction on a face is determined like this: if you look at the face so that its vertices are ordered counterclockwise then the normal points toward you.

Regarding the gradient, yes, it is possible that the error you see is due to numerical approximation.

**Comment by fanronghong** [comment]
Thanks @v-dobrev .

I understand all the above questions. Thank all of you again.
