### ISSUE TITLE
Support for distinct formulations (physics) in different spatial regions?

### ISSUE THREAD

**Issue by MPhysXDev** [mfem/mfem#1124]
Dear MFEM team,

first we want to state that we are truly impressed by the scope and amazing quality of your library, which has already established itself as a major framework for the development, at high level of abstraction, of massively scalable high performance physical simulation codes.

However, while in the process to learn and start using MFEM, we have been **struggling to locate a proper abstraction for specifying different physics (meaning different set of equations controlling different fields) in different (possibly overlapping) spatial regions of a mesh**. 

To give a first (non-overlapping case) example for this class of problem, let say that we would like to solve a simple steady state fluid-structure interaction problem, considering (pressure, velocity) fields obeying Stokes equation in the exterior region with appropriate BCs at the outer boundary, coupled at an inner boundary with an anchored solid region supporting a  displacement field obeying linear elasticity equations.

A second more involved (spatially overlapping case) example, would be to solve an EM wave scattering problem on a metallic region whose (conduction) electron gas dynamic is described by a fluid like type equation. Now we have some formulation of Maxwell equations (time or frequency domain) to solve everywhere (surrounding vacuum + metal region) with some absorbing BC at the outer vacuum boundary, coupled in the inner metallic region with electron gas fields (density, velocity) obeying some forced electron gas hydrodynamics.

Other FEM platforms that we are aware of, for instance **GetDP** (http://getdp.info/), **deal.ii** (https://www.dealii.org/ - see in particular https://www.dealii.org/current/doxygen/deal.II/step_46.html), **libMesh** (https://libmesh.github.io/index.html - see in particular https://libmesh.github.io/examples/subdomains_ex1.html) or **DUNE** (https://www.dune-project.org/ -  see in particular https://www.dune-project.org/modules/dune-pdelab/), all provide some level of support for this broad class of problems; while of course presenting some limitations in other areas better supported by MFEM.

Without any preconception about the best possible design choices/implementation, and purely from a (naive ?) user perspective, we were somewhat expecting MFEM finite element space and(or?) form integrator classes to have domain of definition/integration optionally restricted to a (list of) subset(s) of the mesh, as tagged by volume/boundary cell attributes naturally inherited through mesh refinement/coarsening/deformation and/or parallel partitioning. Nothing of that nature or functionally equivalent appears available.

****- Are we missing something obvious?**
**- Is this currently somewhere to be found in the latest released or development versions?**
**- If not there directly, would it be easily achievable with some tricks or minor extension to the code, and if yes, could you outline an avenue for enabling it?**
**- If none of the above, is this on your road map at some time horizon you can share with us ?****

We are looking forward to learn more about MFEM capabilities in relation with what is, in our opinion, an absolutely core requirement for multi-physics FE solver development.

Best regards,

MPhysX development team.

**Comment by tzanio** [comment]
Dear MPhysX development team,

Thank you for your interest in MFEM.

We are certainly interested and have been discussing supporting different physics in different domains for some time now, but we have not found a way to implement an efficient abstraction for it without significant development effort.

If you are willing to have global variables that are zero in the physics domain where they are not present, then in principle a "coupling" could be implemented now by providing `Coefficient`s to the different `BilinearForm`s that are nonzero only in their physics domain. That will be quite inefficient though, especially if some variables live only in small portion of the domain.

A better approach will be to have variables that are local to their physics domain and there is some sort of coupling on the domain interfaces. Currently MFEM does not support `GridFunction`s on subdomains of the mesh, so handling this on a single mesh will require significant changes.

An alternative could be to use different `Mesh` objects for the different physics domains where somehow you provide the coupling operator between the different fields on the different meshes.

Hope this helps. We are open to other suggestions how to handle this.

Tzanio

**Comment by MPhysXDev** [comment]
Dear Tzanio,

thanks for your in depth answer and confirmation that you are actively interested in this feature.

We understand the possibility of a work around by using Heaviside type factors in `Coefficient`s, but concur with your assessment of inefficiency.

As you mention that you are open to other potential suggestions as how to handle this, may we point you again to the way the deal.ii (https://www.dealii.org) library is dealing with this, see in particular https://www.dealii.org/current/doxygen/deal.II/step_46.html.

As far as we understand it, it seems to be an approach allowing to add an abstraction for multiple physics in different regions of the mesh in a rather general way, while being also possibly minimally disruptive to the overall framework architecture. In their approach this appears unified with the abstraction of local p-refinement, since all function spaces are defined over the whole mesh but are interpolated with "zero order" (and no associated dofs) in regions where they are not intended to be physically defined. The treatment of surface integrals over inner boundaries between regions supporting distinct physics (something which is often, but not always, required to define coupling terms in `BilinearForm`s) seems however a bit more "ad hoc"... 

It is our understanding that local p-refinement is not currently supported by MFEM (we are writing under your control here). However, it may well be already in your roadmap, and the above outlined approach could then be a way to kill two birds with (almost) the same stone...and possibly warrant accelerated development ? ;)

We are looking forward reading your further thoughts on this.

Best regards,

MPhysX development team.

**Comment by tzanio** [comment]
Thank you, this is an interesting suggestion and we will consider it. General p-refinement is indeed on our roadmap, but not in the immediate future.

I will leave this issue open for a while in case folks have additional comments or suggestions.

Tzanio
