### ISSUE TITLE
Missing  class member in code documentation

### ISSUE THREAD

**Issue by geyan3566** [mfem/mfem#1131]
In the documentation of `PetscPreconditionerFactory`, the private member `std::string name`  is not listed.
http://mfem.github.io/doxygen/html/classmfem_1_1PetscPreconditionerFactory.html#acc06fdb06059d317eea3b77a5f3fbfd0

**Comment by v-dobrev** [comment]
Yes, this is the default behavior of doxygen -- only public and protected members are listed in the generated documentation.
