### ISSUE TITLE
MPI communicator limit

### ISSUE THREAD

**Issue by dylan-copeland** [mfem/mfem#1133]
This is more of an MPI issue than an mfem issue, but it is still relevant for mfem development. MPI crashes (without any error messages) if too many communicators are created using MPI_Comm_split. My experiments show that about 2000 communicators is the limit, although it varies with each run (and probably the compiler, etc.). In order to make certain types of mfem applications scalable, e.g. domain decomposition solvers, it seems necessary to use different communicators for different ParMesh and ParFiniteElementSpace instances. For large 3D problems, it is easy to exceed 2000 communicators. 

Does anyone have experience with such challenges for large parallel problems? Is there a good solution or workaround?

**Comment by tzanio** [comment]
I know that [XBraid](https://computing.llnl.gov/projects/parallel-time-integration-multigrid) uses `MPI_Comm_split`.

@jbschroder or @rfalgout do you have any experience with the limit that @dylan-copeland is mentioning?

**Comment by rfalgout** [comment]
We have had a related issue in hypre with communicator limits.  Apparently, some (all?) of the MPI implementations also do not free up the communicators when the user frees them up, so if you create/destroy communicators too many times, MPI also crashes (even though it shouldn't).  We only create new communicators in one particular BoomerAMG coarse-grid solver approach, which is currently the default, but it is causing so many problems lately that we may change it.

Braid only creates two communicators at the very beginning of a run, so we have not had an issue with that (as far as I know).

**Comment by dylan-copeland** [comment]
The solution I have come up with is simply to create one communicator, which has required significant code changes to ensure that processes are partitioned into disjoint sets. For example, the process partition {0,1}, {2,3}, {4,5}, ... is disjoint and can use just one communicator, whereas the overlapping partition {0,1}, {1,2}, {2,3}, ... would require a communicator for each pair of processes. For a geometric domain decomposition, this means each subdomain should have its own set of processes, disjoint from other subdomains, and the interfaces cannot be on processes shared by neighboring subdomains.
