### ISSUE TITLE
Using Tetrahedral Meshes in Laghos

### ISSUE THREAD

**Issue by Samiullah-Malik** [mfem/mfem#1135]
Hi,
We are trying to run the Sedov blast problem in Laghos on a simple tetrahedral mesh. However, the problem terminates in the first time step with the following output:
![SedovBlastOutput_TetMesh](https://user-images.githubusercontent.com/39503305/67887815-64327900-fb22-11e9-880e-d80efdb27797.png)

Similarly, we ran the Taylor-Green Vortex (smooth) on a tetrahedral mesh. The results were not consistent with the solution on the hexahedral (cube01_hex.mesh) mesh. In fact, the mesh deforms inwardly. Please see the following GLvis output: [for hex mesh: t = 2.2 secs, for tet mesh: t = 0.008 secs]
![initial_TetMesh](https://user-images.githubusercontent.com/39503305/67889571-7a8e0400-fb25-11e9-8731-0dd3583a2bc4.png)
![Initial_HexMesh](https://user-images.githubusercontent.com/39503305/67889588-82e63f00-fb25-11e9-975a-3f18603cc23f.png)
![TaylorGreen_HexGlvis](https://user-images.githubusercontent.com/39503305/67889329-00f61600-fb25-11e9-89cc-1801ce209b6c.png)
![TaylorGreen_TetGlvis](https://user-images.githubusercontent.com/39503305/67889333-03f10680-fb25-11e9-81d1-582e879d90d8.png)

Is there an example problem in Laghos solved on tetrahedral meshes? And what else to consider when running a problem on tet meshes? 

Kind Regards,
Sami

**Comment by vladotomov** [comment]
Hi Sami,

The meshes need to have correct boundary attributes, otherwise the code won't be able to impose boundary conditions correctly (in Laghos the material velocity must be tangential to the boundary). If you are willing to send me your tet mesh, I can take a look.

Thanks,
Vladimir

**Comment by MarkShephard** [comment]
Vladimir,

Sorry that the students sent this issue in before more carefully working with the people here. Before we bother you with what may be a pretty straight forward issue, we will more carefully coordinate internally.

Thank you.

Mark

**Comment by tzanio** [comment]
Closing for now, but please don't hesitate to reopen if there are still questions.
