### ISSUE TITLE
Hypre solvers with NewtonSolver?

### ISSUE THREAD

**Issue by tuckerbabcock** [mfem/mfem#1136]
Is it not possible to use a HypreSolver with MFEM's NewtonSolver, since the Newton solver calls `SetOperator()`, which HypreSolvers do not support? I'm trying to write a nonlinear magnetostatics code, and was hoping to use the HypreSolvers to solve the linear system as was done in the Tesla miniapp. Will I have to use a different solver than a HypreSolver?

Thanks,

Tucker

**Comment by vladotomov** [comment]
Yes, this is correct, a `HypreSolver` would currently abort inside the Newton.

@v-dobrev , can we implement `HypreSolver::SetOperator` to work as the `HypreSolver` constructor, if the given Operator is a `HypreParMatrix`?

**Comment by mlstowell** [comment]
Hi, @tuckerbabcock ,

I've run into this exact issue using Hypre's AMG preconditioner inside a Newton solver.  I believe I have an implementation of this in the plasma-dev branch.  I can try to peel this off into its own pull request.

Best wishes,
Mark

**Comment by mlstowell** [comment]
I have a first draft of this extension in PR #1137.  Unfortunately, I suspect you're most interested in the `HypreAMS` preconditioner and this does not yet have a `SetOperator` method.  This preconditioner requires a more elaborate setup which can be seen in its constructor.  We'll need to move these setup procedures into a private member function and call this from the existing constructor and the new `SetOperator` method.

**Comment by tuckerbabcock** [comment]
Hi Mark,

Thank you for your quick response and pull request! I am most interested in the `HypreAMS` preconditioner, but this progress is very helpful. Is moving the setup procedures into a new private member function something I could do? I'd be happy to implement the changes and submit them for a pull request if you don't have the time.

Thanks,

Tucker

**Comment by mlstowell** [comment]
Hi, @tuckerbabcock ,

That would be great!  Feel free to add your changes to the existing pull request or create your own, whichever you prefer.

Thanks,
Mark

**Comment by tzanio** [comment]
Great suggestions, thanks @tuckerbabcock, @mlstowell and @vladotomov.

Lets continue the discussion in PR #1137.
