### ISSUE TITLE
testing mesh with integral over sub-volume

### ISSUE THREAD

**Issue by bradfc** [mfem/mfem#1139]
I have a mesh for a rectangular box with an embedded cylinder, and would like to test the configuration by evaluating the volume of the cylinder using the mesh, as I will need such a discontinuous r.h.s in the model I have.  I used the exchange of Issue #599 as a guide.

The mesh accounts for the embedded cylinder.

I've attached a sample code.  The weight is 1.0 inside the cylinder, 0.0 outside.  A second code evaluates the integral with unit weight outside the cylinder.

I tried various FES and collections.  In all cases they gave the correct *total* volume of 4000., but not for the cylinder or its complement. The file attached here gave the following:

dimension: 3
mesh vertex total: 4658
mesh element total: 22216
FE space size: 88864
FE vertex total: 4658
FE element total: 22216
GF size: 88864
Weighted volume: 3824.76
Exact: 392.699

Running the code for the complement gives
...
Weighted volume: 176.008
Exact: 3607.3

The results sum to 4000 but they are qualitatively off from the exact values.  I checked many times to verify that I had not reversed the test for inside/outside the embedded cylinder.  Of the three different combinations of FES and collections I tried, I got the following results:

- weights that sum to 4000 but are qualitatively far off (attached code)
- weights that are approximately correct but do not sum to 4000 (more primitive FES/collections)
- NAN (trying to follow ex5.cpp)

I realize that this is an integral over a discontinuous weight.  I wasn't surprised to see slow convergence, but I was to see an exact pair of (wrong) complements using DG.  I have not been able to navigate the examples and class documentation to see what's wrong.

[volume2.pdf](https://github.com/mfem/mfem/files/3799209/volume2.pdf)

**Comment by mlstowell** [comment]
Hi, @bradfc ,

This is an interesting test but I see a couple issues with the implementation.

First, in the loop which assigns values to the `GridFunction` 'x' the code makes an incorrect assumption.  Specifically, the degrees of freedom stored in a `GridFunction` are not directly related to the nodes of the mesh.  In particular there is no reason to assume that the number of nodes in the mesh is the same as the number of degrees of freedom.  This may be the case in special circumstances e.g. a first order H1 basis on a conforming mesh has one degree of freedom per node, but in general such a correspondence will not hold.

Another small issue is that you use `x` in the `DomainLFIntegrator` and also in the computation `vol(x)`.  The result of this computation is actually equal to the integral of x^2 over the volume.  In this particular case x^2=x so you might get the correct value but technically you only need x in one place or the other.

Now, to fix the first issue, setting values in x, you could create a function which returns 0 or 1 when evaluated outside or inside the cylinder respectively.  Then project this function onto x.  This function would look like:
```
double CylMaskFunc(const Vector &R)
{
   double radsq = 5 * 5;
   double halfhght = 2.5;
   double rhosq = (R[0] * R[0] + R[1]* R[1]);
   if ((rhosq <= radsq) && (abs(R[2]) <= halfhght))
      return 1.0;
   else
      return 0.0;
}
```
Use this function to define a coefficient and project this onto x:
```
FunctionCoefficient CylMaskCoef(CylMaskFunc);
x.ProjectCoefficient(CylMaskCoef);
```
The second issue can be addressed by simply not passing an argument to the `DomainLFIntegrator`.  If it isn't given a coefficient it assumes a coefficient equal to one.

Best wishes,
Mark

**Comment by bradfc** [comment]
Mark,

Thanks very much for your comments.  Those are the distinctions I was looking for.

When I implement this the results are within a percent (for the mesh I used) of the exact values.

Brad
