### ISSUE TITLE
Serial eigenvalue solver

### ISSUE THREAD

**Issue by sithpz** [mfem/mfem#114]
As I understand, the library does not contain serial eigenvalue solver(s). Is there are any plans to adding this functionality into library?

**Comment by juan42** [comment]
I cannot answer for the developers, but it should be trivial to use [SLEPc](http://slepc.upv.es/) with the recent additions of PETSc as a linear algebra backend. Or do you want to avoid compiling the parallel libraries at all?

**Comment by sithpz** [comment]
Hi, juan42. Yes, i need only serial functionality. I work on small (and generally educational) projects, so I don't need any level of parallelization (maybe only OpenMP). Also we works primarily on Win platform, so compilation of PETSc/SLEPc libraries is little tricky procedures.

**Comment by martemyev** [comment]
Hi @sithpz,

Please, check out [this thread](https://github.com/mfem/mfem/issues/72).
@mlstowell [mentioned](https://github.com/mfem/mfem/issues/72#issuecomment-233444597) that he had an ARPACK wrapper - I wonder if it's available.

Cheers,
Mikhail

**Comment by jedbrown** [comment]
For what it's worth, I hear PETSc builds out of the box with WSL (no
need for cygwin or other non-Microsoft product).

**Comment by tzanio** [comment]
To add to the excellent answers of @juan42, @martemyev and @jedbrown -- we do have an internal version with ARPACK support... will that work for you @sithpz?

**Comment by v-dobrev** [comment]
Another option, if the problems you want to solve are not that big, is to use the dense matrix methods `DenseMatrix::Eigenvalues()` which require MFEM to be built with LAPACK support: `MFEM_USE_LAPACK=YES`.

**Comment by sithpz** [comment]
Problems, which typically occur in our work, have 70-100  thousands dofs, so using dense matrix may not be appropriate aproach. I think, that ARPACK will be good choice for us. By the way, I found Spectra library, which enhance Eigen with some eigenvalue solvers functionality, have a good OOP design and (as author write) is a C++ ARPACK's fork. I'll try to write an adapter to this library.

**Comment by mlstowell** [comment]
I just committed a work-in-progress branch to demonstrate the use of ARPACK in serial (the branch name is arpack-dev).  The parallel version of ARPACK is also wrapped but there are some problems with my example problem so that one is not available yet.

**Comment by tzanio** [comment]
Hi @sithpz were you able to use one of the proposed solutions above (the arpack-dev branch, PETSc or `DenseMatrix::Eigenvalues()`)?

**Comment by nash169** [comment]
Hi,
I'm facing a bit the same problem discussed in this issue. I would like to extract the eigenfunction of the Laplacian (as shown in example 11) without getting involved in the complication of using MPI. I was wondering if there is any progress on the topic or if you can give me some hint of how to work that out. The arpack-dev seems quite dated and petsc as shown in the example makes use of slepc that in turn uses MPI.

Thanks a lot

**Comment by jedbrown** [comment]
Technically it's SLEPc that uses PETSc, and they can be built without MPI (configure PETSc `--with-mpi=0` and it will use internal stubs). I don't know to what extent this meets your needs.

**Comment by v-dobrev** [comment]
Hi @nash169, I just merged the `master` branch in `arpack-dev`. Can you give that a try? Let us know if you run into problems with that.

@jedbrown, the problem with using PETSc+SLEPc with serial MFEM is that the PETSc integration with MFEM is available *only* when MPI is enabled in MFEM.

**Comment by nash169** [comment]
@jedbrown as @v-dobrev said PETSc+SLEPc is available just with MPI but also SLEPc itself just uses MPI as parallelization. I would like to stick to shared memory parallelization for now. @v-dobrev thanks for merging the branch. Sure. I'll test it and I'll let you know.

**Comment by nash169** [comment]
The example seems to work fine. Although there a couple of adjustments to do in order to make it run. The variables MFEM_USE_ARPACK and ARPACK_LIB are not defined in the default config file (using GNU make right now). The arpack header in linalg.hpp is included just if MPI is active; it should be moved outside the MPI conditional.

I was also wondering if ARPACK without MPI is really parallelizing over the threads or not. I'll create some more "demanding" mesh in order to see it clearer. The parallel version of ARPACK requires MPI for sure. I'm not an expert at all in eigenvalue problems solution but wouldn't be good to have an interface with something like EIGEN that support shared memory paralellization like OpenMP (or even something supporting CUDA)?

**Comment by v-dobrev** [comment]
@nash169, thanks for testing the branch. We will fix the issues you noticed.

cc: @mlstowell

Regarding support for other non-MPI eigensolvers: at this point, I'm not aware of any plans to add support for that. However, if you are interested to work on adding something like that to MFEM, we are definitely open to such contributions.

**Comment by nash169** [comment]
Yes. I would like to add it. Although for the next month or so I'll be quite busy and I can't really promise anything.

In the meanwhile thanks a lot for the help with ARPACK.

**Comment by v-dobrev** [comment]
> Yes. I would like to add it. Although for the next month or so I'll be quite busy and I can't really promise anything.

Okay great, no rush. I'll send you an invite to the mfem/collaborators team, so that you can create your branch directly in the mfem repo.

**Comment by nash169** [comment]
Hi there,
with (a lot of) delay I created a branch for the Eigen integration (eigen-dev). I noticed that Eigen default methods (like EigenSolver or SelfAdjointEigenSolver) do not perform any partial spectrum extraction based on power methods or similar... so I figured that it does not really make a lot of sense to use these implementations for (even small) FEM problems. Nevertheless I found this library:

https://github.com/yixuan/spectra

It is based on Eigen and they claim to have re-implemented some ARPACK method achieving comparable/better performance than ARPACK. So the integration of Eigen is basically inside linalg/eigen.hpp while the eigensolver is in spectra.hpp. I've coded it quickly and kind of hackly just to see if it works properly. I'll make it clean exposing all the options of the Spectra solver.

At the moment you can set one or two operators for generalized eigenvalue problems and the solver extracts the k smallest eigenvalues. For relatively small problems (few thousands of nodes) it seems to work properly yielding the same results of Slepc. The examples is in examples/spectra/ex11.cpp. For bigger problems there is really no comparison with Slepc (even with one process). Slepc is not only faster but the modes always converge while in Spectra is really difficult to achieve that. I'm no expert in large sparse eigenvalue problems so it might easily be that I'm setting some param wrongly (like Krilov space dimension for instance), so if somebody can give me some tip about that it is really welcome.

I also added the integration with ARPACK from arpack-dev branch for comparison. Although ARPACK never gives me the same solution of Slepc or other solvers.

P.S.
I'm testing ex11 using the Gmsh mesh of the sphere that I added under data. There is also the .geo file in case it is necessary to regenerate the mesh.

**Comment by v-dobrev** [comment]
Thank you @nash169 for the update on your work.

I'm also not an expert on eigensolvers, so I cannot give you any tips about setting up parameters. Maybe @jetremblay, or @mlstowell have some ideas.

Overall, if I understand you correctly, it seems your experience is that SLEPc is a better choice for the cases you tried -- is that correct?

Link to the `eigen-dev` branch: https://github.com/mfem/mfem/tree/eigen-dev
Link to the `arpack-dev` PR: #1734

**Comment by nash169** [comment]
Hi @v-dobrev. Sorry for the delay.. I had completely missed the answer.

Yes. SLEPc seems to be definitely faster and more robust than Spectra. I'll restart to work on that in a short so I can test a bit more the parameters setting as well as complete the integration.

I'll let you know
