### ISSUE TITLE
How and where does mfem distinguish CG vs DG in terms of DOF

### ISSUE THREAD

**Issue by geyan3566** [mfem/mfem#1145]
Hi,

I'm constructing another discontinuous finite element collection other than `L2_FECollection`. I followed example 9, but I couldn't get where and how MFEM introduces the extra degrees of freedom on the element interfaces? Does it start at mesh construction or finite element space construction?

Thanks,
Ge

**Comment by tzanio** [comment]
It is part of the finite element space, and specifically the finite element collection. 

Specifically, `FiniteElementSpace::Construct()` calls `FiniteElementCollection::DofForGeometry` with the various geometric entities (`Geometry::POINT`, `Geometry::SEGMENT`, etc.) to figure out how many degrees of freedom are associated with each geometric entities.

For the `L2_FECollection`, no dofs associated with shared entities are returned.

**Comment by geyan3566** [comment]
> It is part of the finite element space, and specifically the finite element collection.
> 
> Specifically, `FiniteElementSpace::Construct()` calls `FiniteElementCollection::DofForGeometry` with the various geometric entities (`Geometry::POINT`, `Geometry::SEGMENT`, etc.) to figure out how many degrees of freedom are associated with each geometric entities.
> 
> For the `L2_FECollection`, no dofs associated with shared entities are returned.

Thanks for your reply. It solved my problem.
