### ISSUE TITLE
Minus signs in examples 10 and 16

### ISSUE THREAD

**Issue by bradfc** [mfem/mfem#1148]
I hate to ask such a trivial question, but I'm having stability issues with my code and I'm trying to track down all possible sources.

Examples 10 and 16 are both time dependent problems of the form

d/dt f = O f

where O is some operator.  In FE language, this leads to

M d/dt u = K u

...in which case

d/dt u = M^-1 K

That is, no minus sign on the r.h.s.  But the Mult() codes in these examples have an extra K.Neg() in them and a minus sign in the comment.  If the original equation had both terms on one side with a plus sign, then I can see the minus sign.

But maybe there are minus signs buried in the definitions of one or more of these quantities.  I ask this because I'm trying to develop a pair of coupled equations, one of which uses a diffusion integrator and the other a mixed scalar mass integrator, on their respective right-hand sides.

If I remove the .Neg() lines, then at least one of my variables has the right d/dt sign, but the code crashes, probably for other reasons.

I note that example 9 has a similar l.h.s vs r.h.s structure but no .Neg() in the Mult() module.

I'm clearly missing something.

**Comment by jandrej** [comment]
Have you considered the minus sign from the `BilinearIntegrator` e.g. the weak form?

**Comment by bradfc** [comment]
There's a minus sign associated with integrating a diffusion term by parts, but the minus sign in these examples appears to be associated with the mass matrix, i.e. it appears whether the r.h.s. has a diffusion operator or simply the product of two functions.

**MassIntegrator** and **MixedScalarIntegrator** are both derived from the base class BilinearFormIntegrator, so I would think they share a common overall sign, which will drop out if they are respectively on opposite sides of the dynamical equation.

Also, I realized that example 9 solves an equation that's expressed in the documentation with both terms on the l.h.s., so examples, 9, 10 and 16 are consistent with each other, but that just means that I have a consistent problem.

If I keep the .Neg() statements in the code, as per examples 10 and 16, a key variable has the wrong time derivative sign at small times.  If I comment out those statements, the initial time dependence looks right, but then the code crashes.  I'm worried that I haven't used the time integrator correctly, though that part of the code matches that portion of examples 10 and 16.

**Comment by bradfc** [comment]
A fix and a comment:

After finding an unrelated error in my code, I find that its output now matches that of another code using a fixed rectangular grid (instead of FE) if I assume the following:

- The Laplacian is replaced in FE code by -K (due to integration by parts) with a DiffusionIntegrator.
- There are no other minus signs.

So I'm in agreement with examples 9 and 16, but not example 10, which has the following line in the comments section:

dv/dt = -M^{-1}*(H(x) + S*v)

since it has no Laplacian in it.

**Comment by tzanio** [comment]
Hi @bradfc,

To clarify, we replace the strong form of the equation 

    -Δu = 1

by the weak variational formulation

    (∇u, ∇v) = (1, v)

which in Example 1 is discretized as

     A x = b

where `A_ij = (∇ϕ_j, ∇ϕ_i)` corresponds to `DiffusionIntegrator(one)` and `b_j = (1, ϕ_j)` corresponds to `DomainLFIntegrator(one)`. In other words, the stiffness matrix `A` corresponds to a discretization of the continuous operator `-Δ`, not `Δ`.

Regarding ex10, @v-dobrev can confirm, but the minus sign comes again from the fact that both the `H` and `S` operators are in week form. Maybe we can improve the comments to make this more clear.

Hope this helps,
Tzanio

**Comment by bradfc** [comment]
Hello Tzanio,

Thanks for your note.

I think I understand the strong-weak connection as follows: in physics language, one inserts a complete set of states into the Laplacian operator, then integrates by parts, leaving the weak form - with a minus sign when integrating by parts - and the surface boundary terms.  If the operator in the dynamical equation does not have derivates, then the weak form does not acquire a minus sign.

I have now successfully gotten MFEM to work with a model for which I also have a separate time dependent code that simply uses a rectangular grid.  I get quantitative agreement between the two approaches ONLY if I keep the minus sign for the weak form of the Laplacian, but not the other terms that have no derivatives.  If derivatives of the unknown function are buried in the definitions of the H and S operators in Example 10, then I understand the minus sign, but not if they are multiplicative only.

Brad

**Comment by tzanio** [comment]
>  If the operator in the dynamical equation does not have derivates, then the weak form does not acquire a minus sign.

Correct, or more precisely -- if there is no integration by parts, there is no minus sign. For example the weak form of the problem `u = f` is just `(u, v) = (f, v)` i.e. L2 projection in the finite element space, and the continuous identity operator is discretized as a mass matrix (with no minus sign).

> I get quantitative agreement between the two approaches ONLY if I keep the minus sign for the weak form of the Laplacian, but not the other terms that have no derivatives.

Correct.

> If derivatives of the unknown function are buried in the definitions of the H and S operators in Example 10, then I understand the minus sign, but not if they are multiplicative only.

They indeed are. The continuous form of `S` is just a Laplacian.

**Comment by bradfc** [comment]
That resolves it.  Thanks!
