### ISSUE TITLE
Parameter-based FunctionCoefficient

### ISSUE THREAD

**Issue by bradfc** [mfem/mfem#1151]
[related to issue #143]
Attached below is a draft module for using functions with a parameter set as an extension of FunctionCoefficient.  I find that the functions I want to use for FunctionCoefficient typically have run-time parameters that live in a class.  Unfortunately, C++ rules don't allow invoking FunctionCoefficient with a pointer-to-member-function, only a pointer-to-function.  This means that one has to hard-code the function f(const Vector&) for each set of parameter values.

The code below inherits FunctionCoefficient, but it's a bit clumsy because it requires a dummy function for the base constructor, and it requires rewriting the inherited class for each type of parameter list.

```c++
struct ParameterList
{
  double radius;
};

double dummyfunction(const Vector& X) {return 0;}
class PFunctionCoefficient : public FunctionCoefficient
{
protected:
  double (*PFunction)(const Vector&, const ParameterList&);
  ParameterList PList;
  
public:
  PFunctionCoefficient(double(*f)(const Vector&, const ParameterList&),
		       const ParameterList& L)
    : FunctionCoefficient(dummyfunction),
      PFunction(f),
      PList(L) {}
  double Eval(ElementTransformation &T,
	      const IntegrationPoint &ip, double t)
  {
    double x[3];
    Vector transip(x, 3);

    T.Transform(ip, transip);
    return ((*PFunction)(transip, PList));
  }
};
```

**Comment by ianabel** [comment]
I have a PR (#1078)  that allows you to use a std::function to create a FunctionCoefficient, so then you can either use std::bind, or implement operator() in your parameter class, and create a coefficient off of the class object. 

If you want to try this out, my fork of mfem (ianabel/mfem) has StdFnCoeffs.cpp/hpp which you could drop in.

**Comment by ianabel** [comment]
So, the following would be a minimal example. 

`class PFunction {`
`    int _p;`
`    public:`
`        PFunction( int Parameter ) : _p( Parameter ) {};`
`        void SetParam( int Parameter ) { _p = Parameter };`

`        double operator()( const mfem::Vector & point ) {`
`                  Do Something with the point depending on the parameter`
`        };`

`}`

`PFunction F( 10 ); // Initialise the function with a given parameter.`
`StdFunctionCoefficient MyFunctionCoeff( F );`
`// Now you can use this function coefficient, and change the parameter between uses by calling F.SetParam.`

**Comment by bradfc** [comment]
Got it - thanks!

**Comment by tzanio** [comment]
Thanks for the helpful answer @ianabel!
