### ISSUE TITLE
Get nodal value from GridFunction

### ISSUE THREAD

**Issue by AndromathArcanitus** [mfem/mfem#1152]
Dear MFEM Team,

I was trying to restore nodal values from a gridfunction. As we know, gridfunctions hold the value of coefficients. Suppose I am using Nedelec elements of order 1 to solve a 3D problem and get a gridfunction E. E is a vector whose dimension is exactly the same as E's_space.GetVSize();. 

Could you please give me some instructions on how to get nodal values on the mesh? I tried the function 

> void GridFunction::GetVectorFieldNodalValues(Vector &val, int comp) const 

and I didn't think I have got meaningful results. Moreover, I saw a lot of functions take the argument "comp" but I can not guess its meaning.

I will be very grateful to see your comments.

Thank you,
Yu

**Comment by v-dobrev** [comment]
In this method, the `comp` parameter is short for "component" -- the first vector component (x-component) will be `comp = 1`, the second -- `comp = 2`, etc. In particular, this mean that the returned `Vector` will correspond to the one requested component.

Another option is to use the method `GridFunction::ProjectVectorFieldOn`. In this case, before calling the method, you will need to create a linear FE space, e.g. something like this:
```c++
   H1_FECollection lin_fec(1);
   FiniteElementSpace lin_fes(mesh, &lin_fec, mesh->SpaceDimension());
   GridFunction lin_gf(&lin_fes);
   // Assuming 'nd_gf' is your Nedelec grid function:
   nd_gf.ProjectVectorFieldOn(lin_gf);
```
The resulting linear grid function, `lin_gf`, will correspond to the values at the vertices of the mesh. Also, it will contain all components in of the vector field -- first all x-components, then all y-components, etc.

**Comment by AndromathArcanitus** [comment]
Dear MFEM Members,

Thank you for helping me. Now I read the outputs.
