### ISSUE TITLE
Seg fault on Assemble() [follow-on to #239]

### ISSUE THREAD

**Issue by bradfc** [mfem/mfem#1153]
I would like to integrate some scalar results over a boundary surface, and have used the codes in issue #599 as a guide.  Those codes work correctly, but in the application I'm developing I get a Seg fault at the Assemble() stage.  I use constant coefficients.  The model has natural boundary conditions.

I've traced the problem to the choice of finite element collection.  The sample code in #599 uses LinearFECollection, whereas I use L2_FECollection.  If I use the latter, I get a Seg fault.  If I use the former, the code runs, but the results are poor.

I also tried using a LinearForm and the () function to compute a norm.  I don't get a Seg fault, but I do get essentially zero.

I also get a Seg fault with L2_FECollection and BoundaryMassIntegrator() initialized to a constant.

Is there a list of what combinations support AddBoundaryIntegrator?

**Comment by v-dobrev** [comment]
In the DG case (i.e. with `L2_FECollection`) you should add the `BoundaryMassIntegrator` with the method `AddBdrFaceIntegrator` instead of `AddBoundaryIntegrator`.

**Comment by bradfc** [comment]
Thanks - that worked!
