### ISSUE TITLE
Recover GridFunction defined in serial mesh from ParGridFunction defined in a ParMesh

### ISSUE THREAD

**Issue by e-aranda** [mfem/mfem#1155]
I read a serial mesh from a file, then build a ParMesh and get a ParGridFunction. Is it possible to get the corresponding GridFunction associated to my serial mesh?

**Comment by tzanio** [comment]
To clarify -- you split the serial mesh in several pieces (one per MPI rank) and do not perform parallel refinement?

**Comment by e-aranda** [comment]
No, I am not performing refinement. Is that relevant?

**Comment by v-dobrev** [comment]
It is possible to convert a serial *global* `GridFunction` to a `ParGridFunction` using the following constructor:
https://github.com/mfem/mfem/blob/c55c80d17b82d80de04b849dd526e17044f8c99a/fem/pgridfunc.hpp#L73-L77

Copying data back, from `ParGridFunction` to a global `GridFunction` is not currently implemented but it should be easy to do that using code similar to the above constructor.

**Comment by e-aranda** [comment]
Ok, I have implemented a method for copying data back in my own `ParGridFunction` class.  In case anyone is interested, here it is

    class MyParGridFunction : public ParGridFunction
	    {
	    public:
	        // MyParGridFunction() : ParGridFunction() {}
	        MyParGridFunction(ParFiniteElementSpace *_f) : ParGridFunction(_f) {}
	        GridFunction *Globalize(Mesh *, const int *);
	        ~MyParGridFunction(){ }
	    };

	GridFunction *MyParGridFunction::Globalize(Mesh *mesh, const int *partitioning)
	{
		ParFiniteElementSpace *par_fes = this->ParFESpace();
		// duplicate the FiniteElementCollection from 'this'
		FiniteElementCollection *fec;
		fec = FiniteElementCollection::New(par_fes->FEColl()->Name());
		// create a global FiniteElementSpace from the local one:
		FiniteElementSpace *fes;
		fes = new FiniteElementSpace(mesh, fec);
		// create GridFunction
		GridFunction *gf;
		gf = new GridFunction(fes);
	 	const int myid = par_fes->GetMyRank();
	 	const int ne = fes->GetNE();

		Array<int> gvdofs, lvdofs;
	        Vector lnodes;
	        int element_counter = 0;
		MPI_Status status;
		// data to send and received
		int *index;
		double *nodes;
		int size;
		for (int i = 0; i < ne ; i++)
		{
		    if (partitioning[i] == myid)
		    {     
		        par_fes->GetElementVDofs(element_counter, lvdofs);
		        this->GetSubVector(lvdofs, lnodes);
		        fes->GetElementVDofs(i, gvdofs);
		        // process 0, set values
		        if (myid == 0)
		        	gf->SetSubVector(gvdofs, lnodes);
		        // other process, send values to process 0
		    	else
		   	{
		        	size = gvdofs.Size();
			        index = new int[size];
			        index = gvdofs.GetData();
		    	    nodes = new double[size];
		        	nodes = lnodes.GetData();
		        	MPI_Send(&size, 1, MPI_INT, 0, 10, MPI_COMM_WORLD);
		   			MPI_Send(index, size, MPI_INT, 0, 0, MPI_COMM_WORLD);
		    		MPI_Send(nodes, size, MPI_DOUBLE, 0, 1, MPI_COMM_WORLD);
		    	}
		        element_counter++;   
		     }   
		     if (myid == 0 && partitioning[i]!= 0)
			{
			    MPI_Recv(&size, 1, MPI_INT, partitioning[i], 10, MPI_COMM_WORLD,&status);
			    index = new int[size];
			    nodes = new double[size];
			    MPI_Recv(index, size, MPI_INT, partitioning[i], 0, MPI_COMM_WORLD, &status );
		  	    MPI_Recv(nodes, size, MPI_DOUBLE, partitioning[i] ,1, MPI_COMM_WORLD, &status);
		  	    gvdofs = Array<int>(index,size);
		  	    lnodes = Vector(nodes,size);
			    gf->SetSubVector(gvdofs, lnodes);
		  	}
		}   

		return gf;
	}

**Comment by tzanio** [comment]
Thank you for sharing this @e-aranda!

**Comment by tepperly** [comment]
@e-aranda, I think this modification to your `MyParGridFunction` class will do the same thing without leaking memory, but I haven't test it.
```c++
class MyParGridFunction : public ParGridFunction
{
public:
   // MyParGridFunction() : ParGridFunction() {}
   MyParGridFunction(ParFiniteElementSpace *_f) : ParGridFunction(_f) {}
   GridFunction *Globalize(Mesh *, const int *);
   ~MyParGridFunction(){ }
};

GridFunction *MyParGridFunction::Globalize(Mesh *mesh, const int *partitioning)
{
   ParFiniteElementSpace *par_fes = this->ParFESpace();
   // duplicate the FiniteElementCollection from 'this'
   FiniteElementCollection *fec;
   fec = FiniteElementCollection::New(par_fes->FEColl()->Name());
   // create a global FiniteElementSpace from the local one:
   FiniteElementSpace *fes;
   fes = new FiniteElementSpace(mesh, fec);
   // create GridFunction
   GridFunction *gf;
   gf = new GridFunction(fes);
   const int myid = par_fes->GetMyRank();
   const int ne = fes->GetNE();

   Array<int> gvdofs, lvdofs;
   Vector lnodes;
   int element_counter = 0;
   MPI_Status status;
   int size;
   for (int i = 0; i < ne ; i++)
   {
      if (partitioning[i] == myid)
      {
         par_fes->GetElementVDofs(element_counter, lvdofs);
         this->GetSubVector(lvdofs, lnodes);
         fes->GetElementVDofs(i, gvdofs);
         // process 0, set values
         if (myid == 0)
            gf->SetSubVector(gvdofs, lnodes);
         // other process, send values to process 0
         else
         {
            size = gvdofs.Size();
            MPI_Send(&size, 1, MPI_INT, 0, 10, MPI_COMM_WORLD);
            MPI_Send(gvdofs.GetData(), size, MPI_INT, 0, 0, MPI_COMM_WORLD);
            MPI_Send(lnodes.GetData(), size, MPI_DOUBLE, 0, 1, MPI_COMM_WORLD);
         }
         element_counter++;
      }
      if (myid == 0 && partitioning[i]!= 0)
      {
         MPI_Recv(&size, 1, MPI_INT, partitioning[i], 10, MPI_COMM_WORLD,&status);
         gvdofs.SetSize(size);
         lnodes.SetSize(size);
         MPI_Recv(gvdofs.GetData(), size, MPI_INT, partitioning[i], 0, MPI_COMM_WORLD, &status );
         MPI_Recv(lnodes.GetData(), size, MPI_DOUBLE, partitioning[i] ,1, MPI_COMM_WORLD, &status);
         gf->SetSubVector(gvdofs, lnodes);
      }
   }

   return gf;
}
```

**Comment by tepperly** [comment]
In the approach above, `MyParGridFunction::Globalize` needs the serial mesh and partition as input parameters `mesh` and `partition`. Can one do the analogous thing, convert a n-rank ParGridFunction to either a GridFunction or a 1-rank ParGridFunction, without these arguments? I would like to do the conversion in a library that doesn't know the initial serial mesh or user specified partition.
