### ISSUE TITLE
Ownership of bilinear forms

### ISSUE THREAD

**Issue by ben-s-southworth** [mfem/mfem#1158]
I have a class where I need to reassemble lots of different Bilinear forms for every iteration/time step. Due to memory, I cannot keep the fully assembled Bilinearforms and Hypre matrices, but I do want to keep the underlying integrators. E.g., loop over the following:
```
        // Form the bilinear form for one index
        ParBilinearForm *blform = new ParBilinearForm(pfes_);
        blform -> AddDomainIntegrator(mass_integrator_);
        blform -> AddDomainIntegrator(transpose_integrators_[i]);
        blform -> AddInteriorFaceIntegrator(trace_integrators_[i]);
        blform -> AddBdrFaceIntegrator(trace_integrators_[i]);
        blform -> Assemble();
        blform -> Finalize();
```
For memory I need to delete the bilinear form when it goes out of scope (or just not use a pointer), but then it deletes all of my class variable integrators `mass_integrator_`, `transpose_integrators_`, and `trace_integrators_`. This ownership appears to be set by `extern_bfs`, but that variable is protected and there does not appear to be a way to modify it. 

This is related to https://github.com/mfem/mfem/issues/793 -- it would be very helpful if the user had some way to access ownership for variables within BilinearForms. 

I'm not sure the best option. I added a simple public function to BilinearForm.cpp
```
   /** Call to avoid deleting external parbilinear forms. */ 
   void KeepExternalBfs() {extern_bfs = true; }
```
but this must account for all added forms. Another option is for each integrator you add there is an option boolean that defaults to True on whether to assume ownership.

**Comment by jandrej** [comment]
I am aware of this "issue". I added a similar function to self-handle the allocation/deallocation of BilinearForms. It should be merged with a wave of other PRs.

**Comment by tzanio** [comment]
Julian, which PR are you referring to above?

**Comment by jandrej** [comment]
I kinda slipped this into #1164. See https://github.com/mfem/mfem/pull/1164/files#diff-a5bba7c091679db16533fcd0d321ad6fR535.

**Comment by tzanio** [comment]
Okay, lets continue the discussion of this issue in #1164 then.

**Comment by tzanio** [comment]
Ben, please add further comments in #1164 (and in particular if the proposed solution there works for you).
