### ISSUE TITLE
PA for NonlinearForm and dealing with Essential BCs

### ISSUE THREAD

**Issue by rcarson3** [mfem/mfem#1160]
So for my application, we currently make use of a ```ParNonlinearForm``` and and a class derived from the ```NonlinearFormIntegrator``` within a Newton Raphson solver in order to solve our PDEs. In particular, we make use of the ```ParNonlinearForm::Mult``` and ```ParNonlinearForm::GetGradient``` operators to build our RHS vector and `A` matrix. I'm currently working on a PA form of the above, and lately I've been working with @YohannDudouit on what on a PA formulation for my system should look like using ```libCEED```.

Now, I've been paying attention to the ```pa-vector-divergence``` class and now PR #1159 since they appear a good path forward for me and my code. I was wondering what might be the best way to handle dealing with essential boundary conditions for the PA style code when making use of a ```NonlinearForm``` form derived class. It appears to me that potentially the easiest would be to have the ```NonlinearForm::GetGradient``` return a pointer to the ```PANonlinearFormExtension``` class. Then once you have that you could make a call to the FormLinearSystem() operator potentially similar to what's found in the ```BilinearFormExtension``` class

```
   Operator *oper;
   Operator::FormLinearSystem(ess_tdof_list, x, b, oper, X, B, copy_interior);
   A.Reset(oper); // A will own oper
```

which as far as I can tell is what is done for the ```BilinearForm``` class when PA is used. You can then use the operator passed back to you in your Krylov solver. However, I really don't have any experience using the ```BilinearForm``` class, so I'm not too sure if I'm missing something else that might be needed as well when doing this for a ```NonlinearForm``` class instead.

**Comment by stefanozampini** [comment]
@rcarson3 You may also want to take a look at how it is done in the PETSc classes. See PetscBCHandler https://github.com/mfem/mfem/blob/master/linalg/petsc.cpp#L2169 and how the essential dof handler is used in the Jacobian setup (GetGradient) https://github.com/mfem/mfem/blob/master/linalg/petsc.cpp#L4085 and  function evaluation https://github.com/mfem/mfem/blob/master/linalg/petsc.cpp#L4148

**Comment by rcarson3** [comment]
@stefanozampini thanks for pointing those functions out to me, so it looks like PETSc is doing something fairly similar to what the NonlinearForm is doing to apply the essential BCs. The function evaluator or the ```ParNonlinearForm::Mult``` sets the DOF that are essential to 0. Then within the ```NonlinearForm::GetGradient``` function the ```OperatorHandle::EliminateRowsCols``` is also called which for a SparseMatrix object goes through and calls the ```SparseMatrix::EliminateRowCol``` function which zeros out the row and cols but preserves the diagonal value. 

Now the ```Operator::FormLinearSystem``` differs from the above by internally creating a ```ConstrainedOperator``` object, and then it makes a call to the ```ConstrainedOperator::EliminateRHS``` function which fixes the RHS terms by doing the following:
```C++
   /** @brief Eliminate "essential boundary condition" values specified in @a x
       from the given right-hand side @a b.
       Performs the following steps:
           z = A((0,x_b));  b_i -= z_i;  b_b = x_b;
       where the "_b" subscripts denote the essential (boundary) indices/dofs of
       the vectors, and "_i" -- the rest of the entries. */
void EliminateRHS(const Vector &x, Vector &b) const;
```
It's just not entirely clear to me what would be the best choice for a PA operation where we never actually construct the full sparse matrix. I'm leaning towards the ```Operator::FormLinearSystem``` being the correct approach, since it only needs to be applied once, while I feel the current method used in  ```NonlinearForm::GetGradient``` would probably need to be applied every time the PA operator is applied within your krylov solver. I could be missing something since this is based on my search of the code trying to figure out what each class ```NonlinearForm``` and ```BilinearForm``` is performing.

If it turns out that ```BilinearForm``` way of doing things is the better choice I would like to make sure with those more familiar with that class that these lines of code from the ```PABilinearFormExtension``` class :
```c++
void PABilinearFormExtension::FormLinearSystem(const Array<int> &ess_tdof_list,
                                               Vector &x, Vector &b,
                                               OperatorHandle &A,
                                               Vector &X, Vector &B,
                                               int copy_interior)
{
   Operator *oper;
   Operator::FormLinearSystem(ess_tdof_list, x, b, oper, X, B, copy_interior);
   A.Reset(oper); // A will own oper
}
```
could more or less be ported over to what's being done with the ```PANonlinearFormExtension``` class that exists in PR #1159 . However like I said earlier I'm really not familiar with the internals of the ```BilinearForm```  and ```PABilinearFormExtensionclass``` class, so I'm not sure if I'm missing something else that should be included.

**Comment by stefanozampini** [comment]
If you use a `PetscNonlinearSolver`, and wrap the Gradient operator you return with a MATSHELL matrix in PETSc (see SetJacobianType below), then PETSc will take care of zeroing out values before and after the Jacobian application, which will be performed through your PA Mult method. Below is a pseudo-code you may want to try. You can send me an email if you want to discuss more in details, or ask @jandrej (he knows some of these details related to supporting  matrix-free preconditioning in PETSc through MFEM)

```
MyNonlinearOp::Mult(x,y) -> just apply the nonlinear operator (do it as if there are no essential dofs)
MyNonlinearOp::GetGradient(x) -> return the mfem::Operator which applies the PA form (again, this operator does not need to know about essential_dofs)

...

MyNonlinearOp op;
PetscNonlinearSolver solver(op)
solver.SetBCHandler(see PetscBCHandler class on how you construct it)
solver.SetJacobianType(Operator::ANY_TYPE) // this will instruct PETSc to just wrap the action of your operator in a PETSc MATSHELL object which also takes care of zeroed out rows and columns
....
/* if you then want to construct a preconditioner for the PA operator, you can use the PetscPreconditionerFactory class (see examples/petsc/ex10p) */
solver.SetPreconditionerFactory(...)
```

**Comment by tangqi** [comment]
Hi @stefanozampini I am also interested in `bchandler`, which appears to be very useful.  If I have multiple unknowns in my Vec x, could I set the essential_dofs for each unknown through `PetscBCHandler::Eval`? Another questions is, if I have a time-independent essential boundary condition, which means I assume my first Vec x satisfies it, is there a simple way to enforce it in the nonlinear solver (like the linear case in ex1) or is it safer to still use `bchandler` in each Newton iteration? Thanks again.

**Comment by rcarson3** [comment]
@stefanozampini I'll take a look at closer look at PETSc then as a potential optional dependency for my users. If I run into any issues I might bug @jandrej first, since I can just talk with him in person. 

I'm also going to start working on a native MFEM solution for the ```NonlinearForm``` class.

**Comment by v-dobrev** [comment]
@jandrej, @pazner, can you comment on the handling of essential b.c. in #1159?

**Comment by jandrej** [comment]
For my purpose, there is no need to handle essential bc in the PA. The proper solution for mfem would be to handle it the same way as we do in the `::Mult` for the FA form aka zero out the tdof indices in the resulting vector. This only applies to the MatVec case of course!

**Comment by v-dobrev** [comment]
OK, I see. This is something we should work to add either as part of #1159 or in a follow-on PR. I think it will be fairly straightforward and it should not require any interface changes.

**Comment by stefanozampini** [comment]
> I am also interested in `bchandler`, which appears to be very useful. If I have multiple unknowns in my Vec x, could I set the essential_dofs for each unknown through `PetscBCHandler::Eval`?

@tangqi What do you mean by multiple unknowns? the Eval method is supposed to populate the local part of the true dof vector that corresponds to true essential dofs. See the comment here https://github.com/mfem/mfem/blob/master/linalg/petsc.hpp#L472 

> Another questions is, if I have a time-independent essential boundary condition, which means I assume my first Vec x satisfies it, is there a simple way to enforce it in the nonlinear solver (like the linear case in ex1) or is it safer to still use bchandler in each Newton iteration? 

The point of having the BCHandler is to forget about BC in residual/jacobian computation. What do you mean by safer? If you have essential BCs, you always want to eliminate those dofs

Here is how it works down the hood for the residual evaluation of a TimeDependentOperator https://github.com/mfem/mfem/blob/master/linalg/petsc.cpp#L3644

**Comment by tangqi** [comment]
Thanks @stefanozampini for explaining. I think I made some mistakes in my current way of forcing the essential boundary condition in my implicit code. I "zero out" those tdof indices in the return vector of `ReducedSystemOperator::Mult`, but I did not impose the essential boundary condition on some components. I will impose my boundary condition explicitly through `bchandler`. Thanks!

Here I  mean I have multiple components including streamfunction, vorticity and magnetic potential as a block vector, but I think I should be able to apply the boundary condition through `Eval` by a simple for loop among different components, unless there is an easier way to do so I miss.

**Comment by tangqi** [comment]
`PetscBCHandler` interface works well for me. Thanks!

**Comment by tzanio** [comment]
@rcarson3, is this resolved?

**Comment by rcarson3** [comment]
@tzanio I'd like to see #1159 add in a function to do this as @v-dobrev suggested, but for all intents and purposes we can close this discussion and move the discussion of the addition of such a function over to #1159.
