### ISSUE TITLE
API for Petsc GMRES linear solver or ILU preconditioner

### ISSUE THREAD

**Issue by geyan3566** [mfem/mfem#1162]
Hi,
I'm trying to solve a nonlinear problem with `NewtonSolve`, in which I hope there will be a GMRES linear solver with ILU preconditioner available. I couldn't find such API either in `hypre.hpp` or `petsc.hpp`. Is there any other option except developing, say, a `PetscGMRESSolver` API? 

Thanks,
Ge

**Comment by v-dobrev** [comment]
One option is to use `GMRESSolver` (or `HypreGMRES`) with the preconditioner being either `HypreEuclid` or `HypreParaSails` -- you'll need to use #1137 for now (it will be merged in the master branch soon). Examples 10/10p and 19/19p may be helpful in this regard (setting up a `NewtonSolver`).

It should be possible to do that with PETSc as well -- @stefanozampini or @jandrej can give you more details. Looking at the PETSc version of example 10p may be helpful as well.

**Comment by stefanozampini** [comment]
If you create a PetscLinearSolver you will get GMRES + ILU (sequential) or GMRES+BJACOBI + ILU on blocks (parallel) by default with PETSc.

**Comment by geyan3566** [comment]
> If you create a PetscLinearSolver you will get GMRES + ILU (sequential) or GMRES+BJACOBI + ILU on blocks (parallel) by default with PETSc.

Thank you, I'll try that.

**Comment by tzanio** [comment]
@geyan3566, I'm closing this now, but feel free to reopen if you have further questions.
