### ISSUE TITLE
How to add boundary vertex to mesh

### ISSUE THREAD

**Issue by amir90** [mfem/mfem#1170]
Hi,

In example 2 (linear static analysis) the essential boundary conditions are faces of the mesh.

1. I need to run a simple tetrahedral linear static analysis where I need to fix nodes. 
However, there is no addbdrVertex to the mesh. I found AdjustVDofs, but I am unsure how to use it, and have not found any examples of it. 

2. I also need the forces to act on a few known nodes, How do I select individual nodal DOFs for the forces to act on? 

Thanks.

**Comment by jakubcerveny** [comment]
Hi @amir90, in FEM it's incorrect to prescribe BCs or loads on zero measure sets (single nodes). It may look like it's working but when you refine the mesh, you get a different BC or load. In fact, as you keep refining, your stresses will go to infinity. You should fix (or load) boundary elements, i.e., edges in 2D and faces in 3D.

**Comment by tzanio** [comment]
To add to @jakubcerveny's answer -- if you really need to, you can use the `EliminateVDofs` method of `BilinearForm` to eliminate a list of Dirichlet degrees of freedom.

See https://github.com/mfem/mfem/blob/18f0cf0873d9f5c941c747e73bbdd951bba7444c/fem/bilinearform.hpp#L478-L487 as well as #35, https://github.com/mfem/mfem/issues/80#issuecomment-274750401 and #737.
