### ISSUE TITLE
Runtime error with CUDA version of code

### ISSUE THREAD

**Issue by bradfc** [mfem/mfem#1171]
I have my code compiled and running properly with/without openmp.  I have also built a CUDA-enabled version of the MFEM library on an NVIDIA Jetson nano, and successfully run the example codes with the "-d cuda" option.  When I attempt to build and run a CUDA version of my code (I put the source code in the examples folder and build it there), it builds an executable without error messages, but at runtime, I get the following:

Verification failed: (alias == false) is false:
 --> cannot register an alias!
 ... in function: static void* mfem::MemoryManager::Register_(void*, void*, std::size_t, mfem::MemoryType, bool, bool, unsigned int&)
 ... in file: general/mem_manager.cpp:362

Apart from not knowing what this means, I'm not sure how my code differs from the example files in terms of CUDA use, since CUDA capability is buried in the library.

**Comment by v-dobrev** [comment]
At this time, the only integrators that will benefit from CUDA are the `DiffusionIntegrator` and `MassIntegrator`. Are you using either of those in your code?

In terms of tracking the above issue, this error may appear if you are using block vectors (with CUDA device) in your code. Is that the case?

**Comment by bradfc** [comment]
Yes to both.  For the purposes of this thread, my code draws upon Examples 10 and 16: coupled equations with diffusion.

**Comment by v-dobrev** [comment]
If some of the integrators you use do not support CUDA, the overall effect of using CUDA may be that your code will run slower because of the memory transfers to/from the GPU. So in your case, it seems like it may be detrimental to the overall performance.

When using block vectors with GPUs, one thing you need to do is to allocate block vectors using the constructor
https://github.com/mfem/mfem/blob/b6d50d0b4bb5ea4cd393edf384ef5c291be95cfe/linalg/blockvector.hpp#L60-L61

with the second parameter being `mfem::Device::GetMemoryType()`. In addition to that, keeping the current memory location (host or device) of the block vector and its sub-vectors synchronized and up-to-date may be tricky. The methods `Vector::SyncMemory` and `Vector::SyncAliasMemory` are meant to help with maintaining this synchronization. This process should be managed by the application.

**Comment by bradfc** [comment]
Per your previous comment, I'm **only** using MassIntegrator and DiffusionIntegrator, so I will look into managing block vectors - unless it's simpler to code the coupled equations explicitly by hand.

In the best of all worlds, I don't have a feel for when a mesh size is large enough that there's a performance benefit using GPUs.  That's partly what I'm trying to learn with this code.

**Comment by bradfc** [comment]
A followup: I coded the constructor as per the format above - again, built OK, but I got the same error message.

So 2 questions:

1. Can I get this error message due to synchronization issues?
2. Is there an example of code that uses SyncMemory and SyncAliasMemory?

**Comment by bradfc** [comment]
An addendum: I'm not sure what's different but the program now runs without crashing (I presume thanks to the right constructor) but vectors that start out with zero elements never acquire non-zero values as they should.

To make the question more concrete: where would one insert sync instructions in ex10.cpp under the assumption that the integrators used there did support CUDA?  My code is like ex10.cpp in that it has coupled equations (hence the use of a block vector), but uses only MassIntegrator and DiffusionIntegrator.

**Comment by v-dobrev** [comment]
Generally, if all components of the operator are on the GPU then no synchronization is needed -- it is only needed when the data needs to be moved between the CPU and the GPU memory.

One potential issue is the assembly of r.h.s. vectors and the application of essential b.c. -- those are currently done on CPU so synchronization is probably necessary. Typically, if one wants to perform an operation on CPU on a vector sub-block, one would first request access to that sub-vector on host using either `Vector::HostWrite` or `Vector::HostReadWrite`; then perform the initialization/update of the sub-vector; and finally sync with the full block vector using something like
```c++
   block_vec.GetBlock(0).SyncAliasMemory(block_vec);
```

Regarding what modifications will be needed in ex10.cpp -- I don't know the precise answer (I'll need to test it myself). I would start with the modifications described above and go from there.

**Comment by bradfc** [comment]
Thanks...to sharpen this, the only place I can see where the block vector in the ex10.cpp sample code is examined separately is in the Mult() and ImplicitSolve() modules, where the components are extracted from block vectors vx and dvx_dt via

   Vector v(vx.GetData() +  0, sc);
   Vector x(vx.GetData() + sc, sc);
   Vector dv_dt(dvx_dt.GetData() +  0, sc);
   Vector dx_dt(dvx_dt.GetData() + sc, sc);

After that, dv_dt and dx_dt are assigned separate expressions.  So I'm assuming that the GetData call is replaced by something like Vector::HostReadWrite, and then the sync call is made after the assignment?

**Comment by bradfc** [comment]
addendum:

In ex10.cpp (and in my code), the call Mult() or ImplicitSolve() passes a Vector.

- I can invoke a BlockVector constructor with the final result after updating the two sub-blocks, and then apply the sync function.
- I don't know how to use Read() or ReadWrite() to extract a sub-block out of a Vector, since those two functions are member functions of Vector.  In any event I don't see the difference between that and the code above using GetData().

But something is not right because I'm getting zero vectors in the CUDA version of the code.  Apart from the initial setup, the Mult() module is the only one where I write to the sub-blocks separately.  

-

**Comment by bradfc** [comment]
Another installment...

I've isolated a section of code whereby I create/update a bilinear form [F] (with MassIntegrator) and then compute
F.Mult(A);
where A is a plain vector (a sub-vector of a block).  When I set A = 0 (and verify this by computing A.Norml2() to be zero), the outcome of F.Mult(A) is non-zero.  I don't see how any matrix can multiply a null vector and get a non-zero outcome unless some pointers have gone astray.  The odd thing is that I print out A.Norml2() immediately before the Mult() command, and print the result immediately afterward.

I'm also a GPU novice, and what I get from the NVIDIA pages is that different generations have quite different memory management.  I have a Jetson Nano, which uses Maxwell GPUs that do not have unified memory.  I presume that the MFEM library carries out Mult() on the GPUs, but I don't know how it handles memory management, especially for a bilinear form.

**Comment by camierjs** [comment]
Hi @bradfc, would there be a way for us to take a look at the code?

**Comment by bradfc** [comment]
Happy to attach the code.  As noted above, it solves a set of coupled reaction-diffusion equations.  I use ex10.cpp to guide the coupled equations, and ex16.cpp to guide the time-dependent diffusion piece.  The non-CUDA version appears to run OK (results agree with another code that uses a rectangular grid and not finite elements).  I've concentrated on the SetParameters() and Mult() sections of code (and left some diagnostic output calls intact).


[code.zip](https://github.com/mfem/mfem/files/3946893/code.zip)

**Comment by bradfc** [comment]
It has occurred to me that a workaround is to invoke one Solver for each of the coupled equations (for my case at hand, 2, though the more interesting case has 4).  Each equation will have a Step() command, whose LHS output would be a temporary vector (so as not to update any RHS quantities until all the Step() functions are executed.  After that the temporary vectors become the 'official' vectors.

The overhead of this is a vector copy operation for each equation, but this may be more efficient than what may be more copies back and forth between GPU and CPU as well as the sync problems.  I'm not an expert on CUDA to know how many of such copies are required when synchronizing blocks.  If synchronizing pointers is all that's needed, then of course the block method is better, but synchronization means that one object loses its 'identity' in favor of the other, and I can't tell from the MFEM commands which way this goes (GPU -> CPU or the reverse) and which way it's needed.  All this is to say that doing the block vector algebra by hand retains the coded efficiency of MFEM CUDA support without introducing extra headaches...

Looking through the MFEM code, it looks like the CUDA support centers on the vector dot product (plus matrix times vector).

**Comment by bradfc** [comment]
Sorry for the serial comments...

I just found this in the version 4.0 release notes:

 * Only constant coefficients are currently supported on GPUs.

That's unrelated to block vectors, and I think is fatal to my application, if I understand it correctly.

**Comment by tzanio** [comment]
There is a PR addressing more general coefficients that is about to be merged: https://github.com/mfem/mfem/pull/1107
