### ISSUE TITLE
BlockNonlinearForm interior face integrator example?

### ISSUE THREAD

**Issue by jjwiman** [mfem/mfem#1173]
I was wondering if any project has an example of implementing an interior face integrator for BlockNonlinearForm. I'm running into a segfault somewhere in GetGradientBlocked prior to the boundary face integrator but after the domain integrator is run. Boundary face integrators run fine (if there is no interior face integrator). The AssembleFaceGrad method on the interior face integrator is never even called.

I'd prefer to debug further, but it's taking me a while to get a working debug build of mfem (as I was using spack). So I thought I'd ask first while still trying to set things up.

**Comment by jjwiman** [comment]
And there's the problem: it needs to check if the FaceTransformation is NULL at
https://github.com/mfem/mfem/blob/b6d50d0b4bb5ea4cd393edf384ef5c291be95cfe/fem/nonlinearform.cpp#L804

**Comment by jamiebramwell** [comment]
I'm unfortunately not aware of anyone using an interior face integrator in a BlockNonlinearForm. Have you used this @jandrej ? I imagine this is a bug that needs to be fixed.

**Comment by jandrej** [comment]
I have never used internal face integrators, so I guess I can't help here.

**Comment by jjwiman** [comment]
I think the serial version is fixed with just the null check added. Unfortunately, I noticed the parallel versions of both nonlinear and blocknonlinear forms are missing parts of the implementation for interior face integrators. So currently I'm trying to implement to implement GetGradient for them.

**Comment by tzanio** [comment]
@v-dobrev and @mlstowell -- can you take a look at this?
