### ISSUE TITLE
MFEM OpenMP Parallelism

### ISSUE THREAD

**Issue by ianabel** [mfem/mfem#1175]
When adding OpenMP parallelism to a part of MFEM (in this case, I want to add it to the HDG stuff), is this designed to be stand-along OpenMP or should MPI+OpenMP also be supported? If MPI + OpenMP is not yet a feature of MFEM, I'ld suggest keeping OpenMP for just single-node operations, and skipping straight to MPI 3 for heterogenous parallelism.

Ideally, I'ld like to have a configuration option I can set to go from one core to one-node many-core without retooling the entire underlying code for MPI.

**Comment by jakubcerveny** [comment]
In the code there are remnants of old OpenMP functionality, marked by `MFEM_USE_LEGACY_OPENMP`, but these are due for removal. If I understand it correctly, the new approach is to use OpenMP as one of the "backends" to execute computation kernels (see `OmpWrap`). There will always be MPI, and orthogonally, within a node, you can choose from CUDA, RAJA, OpenMP, etc., even in run-time (see `forall.hpp`).

**Comment by jakubcerveny** [comment]
In other words, you probably want to use `MFEM_FORALL` in your code and configure the library to use the OpenMP backend.

**Comment by tzanio** [comment]
As @jakubcerveny said, please use the `MFEM_FORALL` approach which will allow you to use OpenMP and other backends.
