### ISSUE TITLE
Using BLAS in MFEM DenseMatrix / Vector operations

### ISSUE THREAD

**Issue by ianabel** [mfem/mfem#1176]
Is there a reason that MFEM uses LAPACK to accelerate certain operations, but not BLAS?
I guess this could be done function by function as and when we find particularly lethargic ones.
This would also allow us to take advantage of the Intel MKL / AMD math libraries. 

As a completely different approach -- how hard would it be to write a wrapper layer and replace mfem::DenseMatrix with Eigen's matrix class? This is probably a horrifically large amount of work though, but then we get all the performance tweaks they have.

**Comment by jandrej** [comment]
I think @v-dobrev has some graphs that shows a comparison of a few different matrix libraries as backends. I can't find the graphs now, but they show why we don't use a TPL.

**Comment by v-dobrev** [comment]
Generally speaking, to get real benefit from BLAS/LAPACK one needs to have relatively large matrices. The dense matrices in MFEM that are most important are local (e.g. per mesh element) which are not that large unless one uses high-order basis. One the other hand, when using high-order, matrix-free algorithms are faster than forming the local dense matrices.

What has been of interest to us is the extension of BLAS to small batched dense matrix operations. There are implementations of such kernels, e.g. in the MAGMA library. Even with batched operations, one may not get the best performance, e.g. in the context of fast operator evaluation for operators like mass or diffusion. In that case one has to fuse a sequence of small dense matrix operations on each element in addition to batching over elements. This makes the best kernels quite specific to PDE discretization and general purpose dense linear algebra libraries become not that efficient.

**Comment by tzanio** [comment]
I agree with @v-dobrev. Unless you need large dense matrices, the algorithms in MFEM will not really benefit from such libraries. There is also the issue of GPU support.
