### ISSUE TITLE
Newton solver with PetscLinearSolver

### ISSUE THREAD

**Issue by geyan3566** [mfem/mfem#1180]
Hi,

I'm trying to solve a nonlinear problem using the `NewtonSolver` with `PetscLinearSolver` as the inside linear solver. The linear solver is Petsc GMRES solver with lu preconditioner given a small problem. But the GMRES doesn't converge in 1 iteration after the first Newton iteration. Does it mean I need to reset the preconditioner for the PetscLinearSolver for every Newton iteration or I did something wrong?

Thanks,
Ge

The structure of my code is (HypreParMatrix is used here) :

```
NewtonSolver *newtonsolver = new NewtonSolver(fes->GetComm());
PetscLinearSolver *petsclinsol = new PetscLinearSolver(fes->GetComm(), "solver_", 0);
PetscPreconditioner *prec = new PetscPreconditioner(fes->GetComm(), "prec_"));
   (some parameters setting)
petsclinsol->SetPreconditioner(*prec);
newtonsolver->SetOperator(*res);   // res is a pointer to my nonlinear form
newtonsolver->SetSolver(*petsclinsol);
newtonsolver->Mult(b, u);
```
The petscrc_file is simpily given by:
```
-solver_ksp_type  gmres
-prec_pc_type lu
```

Here is the snapshot the output:
```
Newton iteration  0 : ||r|| = 0.0015575
  0 KSP Residual norm 9.420487153547e-02 % max 1.000000000000e+00 min 1.000000000000e+00 max/min 1.000000000000e+00
  1 KSP Residual norm 1.345137142898e-15 % max 1.000000000000e+00 min 1.000000000000e+00 max/min 1.000000000000e+00
Newton iteration  1 : ||r|| = 6.85679e-06, ||r||/||r_0|| = 0.00440244
  0 KSP Residual norm 7.875621645521e-04 % max 1.000000000000e+00 min 1.000000000000e+00 max/min 1.000000000000e+00
  1 KSP Residual norm 8.205639860783e-06 % max 9.924573352893e-01 min 9.924573352893e-01 max/min 1.000000000000e+00
  2 KSP Residual norm 1.983690671377e-07 % max 9.935702147291e-01 min 9.872261161606e-01 max/min 1.006426185921e+00
  3 KSP Residual norm 1.957717768242e-09 % max 1.003652189066e+00 min 9.729500998411e-01 max/min 1.031555666863e+00
  4 KSP Residual norm 1.720200670219e-11 % max 1.003719914383e+00 min 9.711498607947e-01 max/min 1.033537618552e+00
Newton iteration  2 : ||r|| = 5.26414e-10, ||r||/||r_0|| = 3.37987e-07
  0 KSP Residual norm 3.539178393972e-08 % max 1.000000000000e+00 min 1.000000000000e+00 max/min 1.000000000000e+00
  1 KSP Residual norm 5.600657654118e-10 % max 9.924416749143e-01 min 9.924416749143e-01 max/min 1.000000000000e+00
  2 KSP Residual norm 1.376578300984e-11 % max 9.939709615481e-01 min 9.771388946639e-01 max/min 1.017225869297e+00
Newton iteration  3 : ||r|| = 1.65022e-13, ||r||/||r_0|| = 1.05953e-10
(Newton iteration converged.)
```

**Comment by v-dobrev** [comment]
I'm not 100% sure but it seems like `PetscLinearSolver::SetOperator` does not update the operator of the preconditioner, as is the expected behavior of the `SetOperator` method.

@stefanozampini, is there an easy way to do that at the end of `PetscLinearSolver::SetOperator`?

**Comment by jandrej** [comment]
If you don't set the preconditioner explicitly and skip the prefix settings, you can just use `pc_type lu` in your options file. This will set the `PC` of your `KSP` to the desired one and update accordingly.

**Comment by stefanozampini** [comment]
@v-dobrev You are right. I added the current behaviour to `PetscLinearSolver::SetOperator` on a request from @jandrej months ago (before he was at LLNL I thnk). I don't remember what was the specific context though.

By reading the code, it was to preserve any Pmat operator already set (explicitly through the KSP interface? @jandrej). And it's clear then if called at the second Newton iteration, it will only update the Amat and not the Pmat (hence the wrong LU). 

I'm not happy with the current misalignment between MFEM linear solvers and the PetscLinearSolver class and we should find a solution which makes everyone happy. I would propose that SetOperator(op&) overwrites both Amat and Pmat, while SetOperator(op,&,op&) gives more freedom (as it is now). @jandrej ?

@geyan3566 If you use the `PetscNonlinearSolver` class, your code will not need to create explicitly the linear solver object

**Comment by geyan3566** [comment]
Thanks for all your answers!
@stefanozampini Actually I've written an inexact Newton method with globalization and validation check, so maybe I can use `SetOperator(mfem::Operator &, mfem::Operator &)`  to fix this problem.

**Comment by jandrej** [comment]
> I'm not happy with the current misalignment between MFEM linear solvers and the PetscLinearSolver class and we should find a solution which makes everyone happy. I would propose that SetOperator(op&) overwrites both Amat and Pmat, while SetOperator(op,&,op&) gives more freedom (as it is now). @jandrej ?

I'm fine with that. I can't remember why I preferred the other behavior besides manually lagging the preconditioner.

**Comment by tzanio** [comment]
Discussion continued in #1186.
