### ISSUE TITLE
Change of element dof numbering possible?

### ISSUE THREAD

**Issue by Wolbecker1** [mfem/mfem#1181]
I have an H1 FiniteElementSpace of arbitrary order. I would like to have the element-wise degrees of freedom numbered in lexicographical order, as in the case of L2 FESpace. Is this possible?

**Comment by jakubcerveny** [comment]
I'm afraid not. In an H1 space, the DOFs are first enumerated for vertices, then for edges, then for faces and finally for element interiors.

**Comment by v-dobrev** [comment]
At the level of the `FiniteElementSpace`, there is the method `GetElementRestriction` that you can call with `ElementDofOrdering::LEXICOGRAPHIC`. Applying the returned `Operator` to a `GridFunction` will give you an E-vector (i.e. a vector where the degrees of freedom are given element by element) where within each element the dofs are ordered lexicographically.
