### ISSUE TITLE
Shared elements in two specific processors

### ISSUE THREAD

**Issue by e-aranda** [mfem/mfem#1184]
In a `ParMesh` I need to locate the elements with a face on the shared boundary between processors. I know I can get with `Mesh::GetSharedFace` and `Mesh::GetFaceElements` but `GetSharedFace` provides all faces shared by one processor with all the others. Is there a way to find the shared faces between two specific processors?

**Comment by tzanio** [comment]
Hi @e-aranda,

This information is relatively "low-level" but is available from the *communication groups* associated with the mesh.

Each group is a set of processors that share geometric entities (vertices, edges, faces) so you want to find the group that contains exactly the two processors you need. Then you can use `GroupTriangle` and `GroupQuadrilateral` to get the faces. The groups themselves are described by the `GroupTopology` class.

One useful piece of code to review in this regard could be `ParMesh::ParPrint`:

https://github.com/mfem/mfem/blob/master/mesh/pmesh.cpp#L5140-L5214

Hope this helps,
Tzanio

**Comment by e-aranda** [comment]
Ok, thanks
