### ISSUE TITLE
Multiple DirichletBC in different marked boundaries

### ISSUE THREAD

**Issue by balborian** [mfem/mfem#1187]
I am solving a simple Laplace problem with Lagrange elements and my boundary conditions are 10 at boundary region with marker 1 and 100 at boundary region with marker 2. From what I have read, the way to go is to use `BilinearForm::EliminateEssentialBC`. I tried to use it as follows, but it is not working

```c++
   a->Assemble();
   ConstantCoefficient cold(10.0), hot(100.0);
   GridFunction u0(fespace);
   ess_bdr[0] = 1;
   u0.ProjectBdrCoefficient(cold, ess_bdr);
   a->EliminateEssentialBC(ess_bdr, u0, *b);
   ess_bdr[0] = 2;
   u0.ProjectBdrCoefficient(hot, ess_bdr);
   a->EliminateEssentialBC(ess_bdr, u0, *b);
   a->Finalize();
```

Is this approach correct? Thanks.

**Comment by balborian** [comment]
Issue #881 seems to respond mine, but it seems very strange to me that the boundary conditions are implicitly imposed through the initial estimation of the solution, instead of some other explicit way.

**Comment by jandrej** [comment]
Can you try running
```c++
   a->Assemble();
   ConstantCoefficient cold(10.0), hot(100.0);
   GridFunction u0(fespace);
   ess_bdr[0] = 1;
   u0.ProjectBdrCoefficient(cold, ess_bdr);
   a->EliminateEssentialBC(ess_bdr, u0, *b);
   ess_bdr = 0;
   ess_bdr[1] = 1;
   u0.ProjectBdrCoefficient(hot, ess_bdr);
   a->EliminateEssentialBC(ess_bdr, u0, *b);
   a->Finalize();
```
which changes the attributes appropriately to your description.

**Comment by v-dobrev** [comment]
Here is another way to achieve what you want by modifying Example 1:

Replace section 6:
https://github.com/mfem/mfem/blob/55dbce3d70dd91c04582b41c69221d984ce02cbb/examples/ex1.cpp#L136-L146

with the following code:
```c++
   const int max_bdr_attr = mesh->bdr_attributes.Max();
   Array<int> ess_bdr(max_bdr_attr), ess_tdof_list;
   ess_bdr = 0;
   ess_bdr[0] = 1;
   ess_bdr[1] = 1;
   fespace->GetEssentialTrueDofs(ess_bdr, ess_tdof_list);

   PWConstCoefficient bc_coeff(max_bdr_attr);
   bc_coeff(1) = 10.;
   bc_coeff(2) = 100.;
```
Then replace section 8:
https://github.com/mfem/mfem/blob/55dbce3d70dd91c04582b41c69221d984ce02cbb/examples/ex1.cpp#L156-L160

with the following:
```c++
   GridFunction x(fespace);
   x = 0.0;
   x.ProjectBdrCoefficient(bc_coeff, ess_bdr);
```
I tested this with the following command:
```console
./ex1 -m ../data/inline-quad.mesh
```

**Comment by balborian** [comment]
@v-dobrev 's approach works, whereas @jandrej 's does not. This is what I am doing:

```cpp
   a->Assemble();
   ConstantCoefficient cold(10.0), hot(100.0);
   GridFunction u0(fespace);
   ess_bdr[0] = 1;
   u0.ProjectBdrCoefficient(cold, ess_bdr);
   a->EliminateEssentialBC(ess_bdr, u0, *b);
   ess_bdr = 0;
   ess_bdr[1] = 1;
   u0.ProjectBdrCoefficient(hot, ess_bdr);
   a->EliminateEssentialBC(ess_bdr, u0, *b);
   a->Finalize();

   SparseMatrix & A = a->SpMat();
   Vector B, X;
   B.SetSize(b->Size());
   B.SetVector(*b, 0);
   X.SetSize(b->Size());

   cout << "Size of linear system: " << A.Height() << endl;

   // 11. Solve the linear system A X = B.
   // Use a simple symmetric Gauss-Seidel preconditioner with PCG.
   GSSmoother M((SparseMatrix&)(A));
   PCG(A, M, B, X, 1, 1000, 1e-12, 0.0);
```
Not sure if this is correct. In any case, this can be closed.
