### ISSUE TITLE
Question on mesh refinement

### ISSUE THREAD

**Issue by kvoronin** [mfem/mfem#119]
Hello!

I am trying to implement a ParMesh constructor which extends a given mesh to higher dimensions. The serial version works fine. The current problem is when going from 2D into 3D with tetrahedrons. 

I have some ordering of vertices and can create the shared entities based on this. But then at some point afterwards I call MarkForRefinement which changes the vertex numbers stored in edges, i.e. shared edges and sedge_ledge remain the same but the edges themselves store different vertices now.

What is the best approach to overcome this difficulty? Can I somehow get the refinement structures set in another way?

**What I have tried now**: Calling MarkForRefinement right after I got elements, boundary and vertices and generated faces, edges, etc. And the mesh is created then in parallel, but in call to UniformRefinement() it looks like the somewhere around RefineGroups shared_faces are changes so that finally the code
```
   int temp = 0;
   for (int i = 0; i < shared_faces.Size(); i++)
   {
      v = shared_faces[i]->GetVertices();
      temp = (*faces_tbl)(v[0], v[1], v[2]);
   }
```
produces an error as if there is no more face containing vertices v[0], v[1], v[2]. But if I check with the same code right in the first line of UniformRefinement, it is ok.
Btw, I failed to add the code like this
```
  550             switch (shared_faces[sface_counter]->GetType())
  551             {
  552                case Element::TRIANGLE:
  553                   sface_lface[sface_counter] = (*faces_tbl)(v[0], v[1], v[2]);
  554                   // mark the shared face for refinement by reorienting
  555                   // it according to the refinement flag in the tetrahedron
  556                   // to which this shared face belongs to.
  557                   {
  558                      int lface = sface_lface[sface_counter];
  559                      Tetrahedron *tet =
  560                         (Tetrahedron *)(elements[faces_info[lface].Elem1No]);
  561                      tet->GetMarkedFace(faces_info[lface].Elem1Inf/64, v);
  562                      // flip the shared face in the processor that owns the
  563                      // second element (in 'mesh')
  564                      {
  565                         int gl_el1, gl_el2;
  566                         mesh.GetFaceElements(i, &gl_el1, &gl_el2);
  567                         if (MyRank == partitioning[gl_el2])
  568                         {
  569                            std::swap(v[0], v[1]);
  570                         }
  571                      }
  572                   }
  573                   break;
```
(from pmesh.cpp, http://mfem.github.io/doxygen/html/pmesh_8cpp_source.html)
into creating shared faces (it gives segfault). Maybe this is crucial.

Can this shed some light on what is my problem?

I would appreciate any comments.

Thanks,
Kirill

**Comment by v-dobrev** [comment]
Hi Kirill,

The method `MarkForRefinement()` changes the local ordering of the vertices in the `elements`, `boundary`, and `shared_faces`. This, in turn, means that the mesh connectivity is different, and in particular, the local edge indices have to be regenerated. For example, this is done automatically, if you call the method `Finalize(true, false)` instead of `MarkForRefinement()`.

However, the method `Finalize(true, false)` does not update the `ParMesh` data members `sedge_ledge` and `sface_lface`. To update these, you can use the same code as the one used [here](https://github.com/mfem/mfem/blob/master/mesh/pmesh.cpp#L988) and [here](https://github.com/mfem/mfem/blob/master/mesh/pmesh.cpp#L1002).

Let us know if this solves the issue you encountered.

Thanks,
Veselin

**Comment by kvoronin** [comment]
@v-dobrev , thanks for the reply!

After some tryings, I've come up with the following:
I generate faces and edges, then call MarkForRefinement() and then regenerate faces and edges (as it is done in ParMesh constructor), and then create the shared entities.  Now all of them look fine and are ordered consistently.

If I understand you correctly, the problem is that I call MarkForRefinement() before setting the shared_faces. But if I don't call MarkForRefinement() before setting shared faces, I cannot have the following code from ParMesh constructor:
```
  550             switch (shared_faces[sface_counter]->GetType())
  551             {
  552                case Element::TRIANGLE:
  553                   sface_lface[sface_counter] = (*faces_tbl)(v[0], v[1], v[2]);
  554                   // mark the shared face for refinement by reorienting
  555                   // it according to the refinement flag in the tetrahedron
  556                   // to which this shared face belongs to.
  557                   {
  558                      int lface = sface_lface[sface_counter];
  559                      Tetrahedron *tet =
  560                         (Tetrahedron *)(elements[faces_info[lface].Elem1No]);
  561                      tet->GetMarkedFace(faces_info[lface].Elem1Inf/64, v);
  562                      // flip the shared face in the processor that owns the
  563                      // second element (in 'mesh')
  564                      {
  565                         int gl_el1, gl_el2;
  566                         mesh.GetFaceElements(i, &gl_el1, &gl_el2);
  567                         if (MyRank == partitioning[gl_el2])
  568                         {
  569                            std::swap(v[0], v[1]);
  570                         }
  571                      }
  572                   }
  573                   break;
```
Now the code does not produce an error but the pmesh is invalid (the result depends on the number of processes). 

**What I have tried**: I converted my pmesh to mesh, printed it out, then read from the file, create a new ParMesh using standard mfem ParMesh constructor and compared the old pmesh with the newer. The newer mesh produces correct result so I assume it is correct.
What i see is that elements, faces and shared entities are all the same in terms of vertex indices but indices[4] (protected members of Tetrahedron) are different in the meshes for proc 1( for proc 0 are the same).
Can this fact indicate where the problem is?

Thanks,
Kirill

**Comment by v-dobrev** [comment]
Hi Kirill,

Let me see if I understand what you are implementing: you have a 2D ParMesh and you are writing a ParMesh constructor that extrudes the 2D ParMesh in Z direction. Also, your 2D ParMesh consists of triangles, so when you extrude them you get triangular prisms that you represent as 3 (?) tets. Is this correct? If not, what exactly is the input to your constructor?

-Veselin

**Comment by kvoronin** [comment]
@v-dobrev,

Yes, I am doing exactly that. 
My constructor first creates local (to processor) parts of the 3d mesh, including elements, boundary and vertices. 
Then I create shared entities using the information which I get from 2D ParMesh and my new elements, boundary and vertices. The generated shared entities have consistent ordering and orientation across processes.
After I set all the shared entities and gtopo, I initialize the internal mesh structure - as it is done in Mesh constructor with minor modifications. 

All this stuff works in 4D, so the problem is specific to the tetrahedron case. 
I am sorry, my description is messy. Probably I need to compare my pmesh with the pmesh which I can create from the serial mesh. They must be the same w.r.t to vertex renumeration and the do have the same main data arrays but apparently they are not  the same since they lead to different results. I will ask then something more precise.

Thanks,
Kirill

**Comment by kvoronin** [comment]
Hi Veselin @v-dobrev,
Finally I have got a precise question:
1) When I am creating shared faces, I have already generate faces and call MarkForRefinement.
2)**Case with no refinements.** When I generate shared faces, in order to have consistent ordering of vertices across processes, I reorder vertices locally the following way - I say that the ordering of vertices which respects the order of vertices (vertex A is more than vertex B if x-coordinate of A is more than x-coordinate of B, or they are equal and y-coordinate is more, etc) has sign +, and I swap (change the first two vertices) the face if the sign of vertex ordering is the opposite.
And then I am able to get correct result.

3) But when I want to do the **refinement** , my reordering contradicts to what is done in 
```
                     Tetrahedron *tet =
                        (Tetrahedron *)(elements[faces_info[lface].Elem1No]);
                     int re[2], type, flag, *tv;
                     tet->ParseRefinementFlag(re, type, flag);
                     tv = tet->GetVertices();
                     switch (faces_info[lface].Elem1Inf/64)
                     {
                        case 0:
                           switch (re[1])
                           {
                              case 1: v[0] = tv[1]; v[1] = tv[2]; v[2] = tv[3];
                                 break;
                              case 4: v[0] = tv[3]; v[1] = tv[1]; v[2] = tv[2];
                                 break;
                              case 5: v[0] = tv[2]; v[1] = tv[3]; v[2] = tv[1];
                                 break;
                           }
                           break;
                        case 1:
                           switch (re[0])
                           {
                              case 2: v[0] = tv[2]; v[1] = tv[0]; v[2] = tv[3];
                                 break;
                              case 3: v[0] = tv[0]; v[1] = tv[3]; v[2] = tv[2];
                                 break;
                              case 5: v[0] = tv[3]; v[1] = tv[2]; v[2] = tv[0];
                                 break;
                           }
                           break;
                        case 2:
                           v[0] = tv[0]; v[1] = tv[1]; v[2] = tv[3];
                           break;
                        case 3:
                           v[0] = tv[1]; v[1] = tv[0]; v[2] = tv[2];
                           break;
```
(which is in the loop for creating shared faces in mfem 3.2, as I see, this part was changed in mfem 3.3) 
4) So if I keep my ordering, it is not the correct ordering for refinement routines so it is changed in RefineGroups() and the code crashes with bad element to face connectivity. 
If I don't do my ordering, I have inconsistent shared faces across processes (orientation of faces is different for same shared face entry on different processes). Maybe this is because I don't do the flip
```
                     // flip the shared face in the processor that owns the
                     // second element (in 'mesh')
                     {
                        int gl_el1, gl_el2;
                        mesh.GetFaceElements(i, &gl_el1, &gl_el2);
                        if (MyRank == partitioning[gl_el2])
                        {
                           const int t = v[0]; v[0] = v[1]; v[1] = t;
                        }
                     }
```
which follows in mfem 3.2 the previous code with refinement flags. But I don't know how to do that in case when I am having only local mesh parts at that moment and don't know which process would be the first in future pmesh.GetFaceElements.

How should I deal with it?

Thanks,
Kirill

**Comment by kvoronin** [comment]
I managed to make the flip, and with one refinement the code seems to work correct with the ordering from ParMesh constructor (which uses refinement flags). However, for the second refinement I got an error
```
Error in Bisection(...) of tetrahedron!
redge[0] = 2   redge[1] = 4   type = 1   flag = 3
```
What should I look at?

Thanks,
Kirill

**Comment by kvoronin** [comment]
I figured out what was the problem now. After the mesh construction, I print some mesh info and use GetEdgeVertices() which calls GetEdgeVertexTable() which changed the edges. Actually, it seems strange that a function which outputs info, changed the mesh structure.
As I guess, usually it doesn't change anything, but in my mesh generator the vertex ordering in edges is different.
Anyway, now I don't get any error and the results seems to be correct.

Thanks,
Kirill

**Comment by v-dobrev** [comment]
Hi Kirill,

Since you are writing a new constructor you have to deal with the internals of the `Mesh` and `ParMesh` objects, which is not an easy task especially for someone new to the code - there are many things going on there that are not obvious and require good knowledge of the internals.

Your last post suggests that you resolved most, if not all, of the issues. Is that correct?

Thanks,
Veselin

**Comment by kvoronin** [comment]
Hi Veselin @v-dobrev ,

Almost, I can get some cases working. Could you give a hint what is happening when I call GetEdgeVertexTable()? How exactly can this change the mesh?
As I see, there edge_vertex is created and then Finalized, can it be that afterwards in refinement new edges cannot be created because of that?
Right now if I call this before refinement, I got an error
```
MFEM abort: STable4D::operator(): (r,c,f,t) = (17,18,21,23)
```
if I have 2+ refinements steps afterwards.

I don't know why but I cannot call "delete edge_vertex" after GetEdgeVertexTable(), just getting a segfault there.

Thanks,
Kirill

**Comment by v-dobrev** [comment]
Hi Kirill,

The method `Mesh::GetEdgeVertexTable()` creates a mapping from the edges to the vertices. The returned `Table` object is essentially a Boolean matrix in CSR format. More precisely, each row in the `Table` contains an ordered list of vertex indices (in this case 2 indices per row) that are associated with the edge. This table represents the enumeration of the mesh edges that class `Mesh` uses - it is derived from the element-to-vertex map. So, in order to maintain consistency, any method of class `Mesh` or `ParMesh` that modifies the element-to-vertex map, has to delete the object stored in the data member `Table *edge_vertex` of class `Mesh` and set `edge_vertex` to `NULL`. This way, the next time `Mesh::GetEdgeVertexTable()` is called - it will regenerate the `edge_vertex` `Table`.

Does this make sense?

Veselin

**Comment by kvoronin** [comment]
Thanks for help!
