### ISSUE TITLE
Broken Raviart-Thomas space?

### ISSUE THREAD

**Issue by rhebergens** [mfem/mfem#1192]
Hello,

MFEM has the RT_FECollection and can apply hybridization. For the hybridization, you require the broken Raviart-Thomas space. Is there something like a broken RT_FECollection?
I've been searching through the documentation, but was not able to find it. I was hoping to have something like:

`FiniteElementCollection *fec = new BROKEN_RT_FECollection(order-1, dim);`

Thanks,
Sander

**Comment by v-dobrev** [comment]
Hi @rhebergens,

We have the class `Local_FECollection` for this purpose: https://github.com/mfem/mfem/blob/69b4ed5399545036d0eb3b2b31b4d22ad2136ad7/fem/fe_coll.hpp#L864

which can be extended to support RT_FECollection with the proper string for the `fe_name` parameter. Also, it should be relatively simple add a constructor that takes any `FiniteElementCollection` and creates the "broken" version.

**Comment by rhebergens** [comment]
Thanks - that's what I was looking for!

**Comment by issabass** [comment]
Hi,
Dear @v-dobrev, how to extend any FiniteElementCollection to its "broken" version?
When I look at the implemented version of Local_FECollection, the available choices are: L2_, H1_, H1Pos_, Quad_Q3. Hex_ND1... How to have Tet_RT, Tri_RT, for instance? 
Thank you much,
zaq

**Comment by v-dobrev** [comment]
Hi @issabass, you can add the cases you need in class `Local_FECollection` and create a PR if you want. You can also create a custom `FiniteElementCollection` class, without changing MFEM, however visualizing / reading `GridFunction`s using that collection may be a problem -- to support these operations, the new collection will have to be added in the factory method: https://github.com/mfem/mfem/blob/0f067d41393943fbabc76fd62a9ed76c8e9a48e5/fem/fe_coll.cpp#L47

**Comment by issabass** [comment]
Many thanks for the reply.
In the link, I see the RTk_2D and RTk_3D among the options.

**Comment by v-dobrev** [comment]
Yes, these are the conforming `RT` spaces. The broken RT spaces that you are asking about will be handled by this check: https://github.com/mfem/mfem/blob/0f067d41393943fbabc76fd62a9ed76c8e9a48e5/fem/fe_coll.cpp#L264-L267

if you add support for them in the `Local_FECollection` class. For the `fe_name` in the constructor https://github.com/mfem/mfem/blob/0f067d41393943fbabc76fd62a9ed76c8e9a48e5/fem/fe_coll.cpp#L2712

you can use strings of the form "RT_dD_Pp" where `d` is the dimension and `p` is the order of the space.
