### ISSUE TITLE
How to formulate shell elements?

### ISSUE THREAD

**Issue by floli** [mfem/mfem#12]
Hello,

We are currently evaluating mfem with regard to shell elements, i.e. 2 dimensional elements that live in 3 dimensional space. What is the canonical way to describe that problem within mfem?

We've made experience that using 2d elements on a 3d mesh essentially makes the mesh 2d by ignoring the z coordinate.

In our mesh file we have
```
dimension
3
elements
N
1 2 0 1 2
[...]
```
In this case mfem just crashes.

Another case we tried is to set dimension to 2 and use element type triangle with 3d vertices, but mfem ignores the third coordinate.

Is there an example for this type of problem?
Is this the right place to ask or is there any mailing list for discussion?

Thanks in advance!

**Comment by v-dobrev** [comment]
Here is an example of a mesh with 2 triangles in 3D space:

    MFEM mesh v1.0
    
    dimension
    2
    
    elements
    2
    1 2 0 1 2
    1 2 3 1 2
    
    # zero boundary elements triggers auto-generation of boundary
    boundary
    0
    
    # the first number after "vertices" is the number of vertices, and
    # the second number is the space dimension in which the mesh is embedded
    vertices
    4
    3
    
    0 0 0
    1 0 0
    0 1 0
    0 0 1

In this example, the mesh is linear, i.e. the edges are straight lines. It is possible to define curved surface meshes as well: see [star-surf.mesh](https://github.com/mfem/mfem/blob/master/data/star-surf.mesh) and [square-disc-surf.mesh](https://github.com/mfem/mfem/blob/master/data/square-disc-surf.mesh) from the `data/` directory in mfem.

**Comment by tzanio** [comment]
Hi @floli,

You may also want to check [Example 7](https://github.com/mfem/mfem/blob/master/examples/ex7.cpp) where a surface mesh on the sphere is defined on-the-fly.

Tzanio
