### ISSUE TITLE
Noise on Gradient of a GridFunction of H1 fes

### ISSUE THREAD

**Issue by S-Villar** [mfem/mfem#1200]
Hello all, 
After solving a block system, I have obtained the degrees of freedom associated with two `GridFunction` s `Et` and `En` created on finite element spaces that use the `ND_FECollection` and the `H1_FECollection`, respectively and on a 2D triangular mesh. I have computed the curl of `Et` (ND) and the gradient of `En` (H1), using `GridFunction::GetCurl` and `GridFunction::GetGradient` as:
```
ofstream OSCurlERet("mypath.txt");
Vector CurlEt,GradEn;
if (OSCurlERet.is_open())
{
   OSCurlEt.setf(ios::fixed);
   OSCurlEt.precision(17);
   for (int i=0;i<mesh->GetNE();i++)
   {
      ElementTransformation *Tr = mesh->GetElementTransformation(i);
      Et.GetCurl(*Tr,CurlEt);
      CurlEt.Print(OSCurlEt,1);
    }
}
```
Similarly, for the gradient:

`                  En.GetGradient(*Tr,GradEn); 
`
Although I would expect errors to rise as we are taking the derivative on the values computed already, I find the gradient extremely noisy, much higher than the noise noticed on the curl of the ND based GridFunction.

Did I use your functions incorrectly to compute the Gradient? Would you expect the solution to be much more noisy for the gradient of H1 than for the curl of a ND fes?

Thanks in advance.

Alvaro

**Comment by mlstowell** [comment]
Hello, @S-Villar ,
There are two things that I notice.

First, if the `H1` and `ND` spaces are of the same order then the gradient of `En` will be a higher order polynomial than the curl of `Et` so you might simply be seeing more variation within the elements. For example, if you're using order=1 then the curl of `Et` will be constant within each element whereas the gradient of `En` will vary linearly.

Second, and probably more importantly, you don't seem to be specifying exactly where to evaluate your derivatives within the element.  This could lead to an appearance of randomness as different locations are chosen perhaps based on orientation of the elements.  The methods `GetCurl` and `GetGradient` evaluate the functions at the integration point that is set within the `ElementTransformation` object, `Tr`.  If you don't set this point explicitly using `Tr->SetIntPoint(&ip);` then the last point, whatever that was, will be reused.  Normally the integration points are obtained from integration rules but you may just want the element centers.  If this is the case you can use:
``Tr->SetIntPoint(&Geometries.GetCenter(Geometry::TRIANGLE));``

Best wishes,
Mark

**Comment by S-Villar** [comment]
Thank you @mlstowell. In fact that solved the issue perfectly. I was not choosing the `integrationPoint` and it was taking a random point. Thanks a lot and happy new year :D
