### ISSUE TITLE
Fix building instructions on mfem.org/building page

### ISSUE THREAD

**Issue by tzanio** [mfem/mfem#1202]
See https://github.com/mfem/mfem/issues/1196#issuecomment-566425089.

Make sure there are no other issues.

Source here: https://github.com/mfem/web/edit/master/src/building.md

**Comment by alastora54** [comment]
https://www.great-knowledge.com/

**Comment by tzanio** [comment]
Fixed in https://github.com/mfem/web/commit/116c932d1707caad9409fc3778e762373ab4bb0b
