### ISSUE TITLE
Tangential Boundary condition

### ISSUE THREAD

**Issue by MuhammadAdilUmer** [mfem/mfem#1205]
Hi,
I want to learn the implementation of tangential boundary condition for electromagnetic problem.
1) Is there any examples or mini-project with implementation of tangential boundary condition?
2) If yes; please suggest me 
3) If not; give me some hint how can I implement the tangential boundary condition
4) How can I learn the implementation of functions in the examples because I did not see any documentation about the functions?
Thank you

**Comment by mlstowell** [comment]
Hello, @MuhammadAdilUmer ,
I expect you've found our electromagnetic miniapp documentation [here](https://mfem.org/electromagnetics/) .  The `tesla`, `joule`, and `maxwell` miniapps all use H(curl) (also called Nedelec) elements.  When these codes apply Dirichlet boundary conditions to H(curl) fields it is only the tangential part of the field that is constrained.   These codes can be a little difficult to navigate but `ex3p` demonstrates how to apply Dirichlet boundary conditions to an H(curl) field in a very concise manner.

To implement such a boundary condition in MFEM you'll need a `VectorCoefficient` which evaluates the boundary values that you want.  Note that only the tangential components of this field will be used, the normal component is ignored.  We have a few `VectorCoefficients` that might be useful or you can write your own.  However, the most common way to implement your own coefficient is to write a simple function of the form:
```
void your_vector_func(const Vector &x, Vector &v)
{
   v.SetSize(3);
   // Implement your function here using the position vector 'x' if needed.
   v[0] = ...;
   v[1] = ...;
   v[2] = ...;
}
```
You can then create the necessary `VectorCoefficient` like this:
```
VectorFunctionCoefficient yourCoef(3, your_vector_func);
```
Where the first argument is the dimension of the vector values returned by the function and the second is the function pointer.  For more details you can look at `ex3p.cpp` which follows this pattern.

Best wishes,
Mark
