### ISSUE TITLE
How to compute GridFunction and Coefficient at arbitrary point?

### ISSUE THREAD

**Issue by fanronghong** [mfem/mfem#1210]
Hi all,

I want to compute a **GridFunction** and a **Coefficient** at an arbitrary point. I have checked [this](https://github.com/mfem/mfem/issues/957) and [this](https://github.com/mfem/mfem/issues/23#issuecomment-148512864). But my situation is a little different.

For any given edge (3D mesh), I get the midpoint of the edge and I want to compute the values of the given **GridFunction** and **Coefficient**.

Through reading the source code, it seems like I should use **ElementTransformation** and **IntegrationRule** to compute the values. Is this correct? Or are there some simple ways?

**Comment by vladotomov** [comment]
Hi @fanronghong,

If you know the position of the point you need, you can create an `IntegrationPoint` (by setting the reference space coordinates). Then you can use `GridFunction::GetValue()` to evaluate the `GridFunction` or `ElementTransformation::SetIntPoint()` to call `Coefficient::Eval().` You don't need an `IntegrationRule` to do the evaluation.

**Comment by fanronghong** [comment]
Hi @vladotomov ,

Thanks for your reply. I tried your suggestion but something is not right. How do I fix the below MWC.
```
#include <iostream>
#include "mfem.hpp"
using namespace mfem;
using namespace std;

double func(Vector& x)
{
    return x[0] + x[1];
}

int main()
{
    Mesh mesh(10, 10, Element::TRIANGLE, true, 1.0, 1.0);

    int p_order = 1;
    H1_FECollection h1_fec(p_order, mesh.Dimension());
    FiniteElementSpace h1_space(&mesh, &h1_fec);

    GridFunction gf(&h1_space);
    FunctionCoefficient coeff(func);
    gf.ProjectCoefficient(coeff);

    IntegrationPoint ip;
    ip.Set2w(0.3, 0.7, 1.0);

    ElementTransformation* tran;
    tran->SetIntPoint(&ip);

    // Below 2 ways throw segmentation errors.
    cout << gf.GetValue(1, ip) << endl; // arbitrary element?
    cout << coeff.Eval(*tran, ip) << endl;
}
```

**Comment by vladotomov** [comment]
I think you must initialize the `ElementTransformation` before using it, see `Mesh::GetElementTransformation()`.

**Comment by vladotomov** [comment]
And keep in mind that the coordinates of the `IntegrationPoint` are assumed to be in reference space.

**Comment by fanronghong** [comment]
Hi @vladotomov ,

Yes, I know that way: find the `Element` which the physical point belongs to, then find the `IntegrationPoint` in reference space corresponding to the physical point, finally use `Eval()` to compute the value.

But here, I don't know which `Element` the physical point belongs to. I don't know the `IntegrationPoint`, and I only know the physical point.

**Comment by fanronghong** [comment]
Hi @vladotomov ,

I miss some details in reference links. Now the code works well. I put the complete code here.
```
#include <iostream>
#include "mfem.hpp"
using namespace mfem;
using namespace std;

double func(Vector& x)
{
    return x[0] + x[1];
}

int main()
{
    Mesh mesh(10, 10, Element::TRIANGLE, true, 1.0, 1.0);

    int p_order = 1;
    H1_FECollection h1_fec(p_order, mesh.Dimension());
    FiniteElementSpace h1_space(&mesh, &h1_fec);

    GridFunction gf(&h1_space);
    FunctionCoefficient coeff(func);
    gf.ProjectCoefficient(coeff);

    Vector phy_point(2);
    phy_point(0) = 0.15;
    phy_point(1) = 0.25;
    phy_point.Print(cout << "physical point: ");

    IntegrationPoint ip;
    int elem_idx;
    ElementTransformation* tran;
    for (int i=0; i<mesh.GetNE(); ++i)
    {
        tran = mesh.GetElementTransformation(i);
        InverseElementTransformation invtran(tran);
        int ret = invtran.Transform(phy_point, ip);
        if (ret == 0)
        {
            elem_idx = i;
            break;
        }
    }

    cout << elem_idx << "-th element\n"
         << "reference point: " << ip.x << ", " << ip.y << endl;

    DenseMatrix phy_point_mat(2, 1);
    phy_point_mat(0, 0) = 0.15;
    phy_point_mat(1, 0) = 0.25;
    Array<int> elem_ids;
    Array<IntegrationPoint> ips;
    mesh.FindPoints(phy_point_mat, elem_ids, ips);

    elem_ids.Print(cout << "element ids: ");

    for (int i=0; i<ips.Size(); ++i)
    {
        cout << i << "-th integration point: " << ips[i].x << ", " << ips[i].y << endl;
    }

    return 0;
}
```
