### ISSUE TITLE
Potential namespace conflict with a RAJA dependency

### ISSUE THREAD

**Issue by rcarson3** [mfem/mfem#1212]
I just noticed while refactoring parts of my app ```ExaConstit``` that a namespace conflict can exist between the ```camp/tuple.hpp``` header file used within ```RAJA``` and the ```mfem/general/hash.hpp``` header file. It appears that both of them declare a ```namespace internal``` within the file.  

Now this might be an issue on my end with how some of my header files are either ordered or something to that effect, since I only started running into this issue after I moved some classes into their own header files. So, I might be able to fix this by reordering how the headers are ordered, but I figured it be a good thing to bring up since others might run into similar issues.

I would imagine one simple fix to this issue would be to rename the ```namespace internal``` to ```namespace mfem_internal```.

**Comment by tzanio** [comment]
This should be a nested namespace (inside the `mfem` namespace) so the full name should be `mfem::internal` and in principle there shouldn't be a conflict.

Can you post the error you see with the relevant code?

Do you by any chance have `using namespace mfem;` and `using namespace raja;` in the same file?

**Comment by rcarson3** [comment]
So, I'm seeing the following error while compiling:

```
In file included from /test_dir/raja/install_dir/include/RAJA/util/camp_aliases.hpp:28:0,
                 from /test_dir/raja/install_dir/include/RAJA/RAJA.hpp:33,
                 from /test_dir/exacmech/install_dir/include/ECMech_util.h:18,
                 from /test_dir/exacmech/install_dir/include/ECMech_evptn.h:9,
                 from /test_dir/exacmech/install_dir/include/ECMech_cases.h:5,
                 from /test_dir/ExaConstit/src/mechanics_ecmech.hpp:7,
                 from /test_dir/ExaConstit/src/mechanics_operator.hpp:9,
                 from /test_dir/ExaConstit/src/mechanics_driver.cpp:60:
/test_dir/raja/install_dir/include/camp/tuple.hpp: In function 'std::ostream& operator<<(std::ostream&, const camp::tuple<Args ...>&)':
/test_dir/raja/install_dir/include/camp/tuple.hpp:506:3: error: reference to 'internal' is ambiguous
   internal::print_tuple(os, t, camp::make_idx_seq_t<sizeof...(Args)>{});
   ^~~~~~~~
/test_dir/raja/install_dir/include/camp/tuple.hpp:492:11: note: candidates are: namespace internal { }
 namespace internal
           ^~~~~~~~
In file included from /test_dir/mfem/install_dir/include/mfem/mfem.hpp:21:0,
                 from /test_dir/mfem/install_dir/include/mfem.hpp:2,
                 from /test_dir/ExaConstit/src/mechanics_driver.cpp:56:
/test_dir/mfem/install_dir/include/mfem/general/hash.hpp:231:11: note:                 namespace mfem::internal { }
 namespace internal
```

The new ```mechanics_ecmech.hpp``` file that I've defined which is causing errors:
```C++
#include "mfem.hpp"
#include "mechanics_coefficient.hpp"
#include "mechanics_integrators.hpp"
#include "ECMech_cases.h"
#include "ECMech_evptnWrap.h"
                                                                                     
using namespace ecmech;
```

```mechanics_integrator.hpp``` file now:

```C++
#include "mfem.hpp"
#include "mechanics_coefficient.hpp"                                                                     
using namespace mfem;
```

Old ```mechanics_integrator.hpp``` file that worked:

```C++
#include "mfem.hpp"
#include "mechanics_coefficient.hpp"
#include "userumat.h"
#include "ECMech_cases.h"
#include "ECMech_evptnWrap.h"
                                                                                                       
using namespace mfem;
```

Now within ```ExaCMech``` we don't have ```using namespace raja;``` defined anywhere. Although, we are making use of the library within there. It might be that for these files I'll just need to remove the offending ```using namespace mfem;``` and just explicitly define all of the mfem types with the ```mfem::``` namespace.

**Comment by tzanio** [comment]
Something is wrong, there shouldn't be a conflict...

Do you know which versions of RAJA and camp are you using?

Can you grep for `using namespace RAJA` and `using namespace camp` in all the headers included by `mechanics_operator.hpp` (including any headers they include)?

**Comment by mlstowell** [comment]
It's generally considered bad practice to place `using namespace ...` within header files because it can lead to unexpected name clashes.  It's not obvious that this is the cause of this particular error but it may be best to move this directive into a source file.  In your header files you will then need to specify `mfem::` but in the source files you should be able to use the shorter names.

**Comment by tzanio** [comment]
I do agree with Mark on that ^^^

Very likely the issue is that there are two "using" clauses: one in your headers (that you may want to consider removing) and one in RAJA and/or camp which could be a bug

**Comment by rcarson3** [comment]
I wasn't able to find any ```using namespace raja``` or ```using namespace camp``` in either  ```ExaConstit``` or ```ExaCMech``` header files. However, I can definitely remove the ```using namespace mfem;``` from the headers, since it appears to be most likely causing issues with how I've now split up the ```mechanics_integrator.hpp``` header file now.

**Comment by rcarson3** [comment]
@tzanio It looks like removing the ```using namespace mfem;``` and specifying mfem types with ```mfem::``` within those headers worked. I'm no longer receiving those compilation errors. I'm going to go ahead and close this as I believe as @mlstowell  put it I was running into unexpected name clashing.
