### ISSUE TITLE
Issue in building mfem-hertz-dev on Windows

### ISSUE THREAD

**Issue by TangLaoya** [mfem/mfem#1214]
Dear all,

I am trying to build mfem-hertz-dev by Windows 7 64bit + VS2013 + Intel MPI 4.1.3.047 + HYPRE 2.11.2. I selected
MFEM_ENABLE_EXAMPLES
MFEM_ENABLE_MINIAPPS
MFEM_USE_MEMALLOC
MFEM_USE_MPI

after generated projects by CMake, the following errors displayed when I build x64 projects by VS2013:
fatal error C1189: #error :  "SEEK_SET is #defined but must not be for the C++ binding of MPI. Include mpi.h before stdio.h"

Could anyone help me to take a look at it?

Thanks,
Tang Laoya

**Comment by v-dobrev** [comment]
The issue seems to be with the MPI C++ bindings which are not used by MFEM. You should be able to disable them by defining a macro in your code. For example, for OpenMPI/MPICH you can `#denife` `OMPI_SKIP_MPICXX`/`MPICH_SKIP_MPICXX`. I'm not sure what the macro for Intel MPI is.

**Comment by TangLaoya** [comment]
Thanks. I will try it latter.
Another question: after I added HYPRE 2.11.2 into the project, I noticed that the subfolders such as 'parcsr_ls', 'parcsr_mv' are not included in the path so that the header files of HYPRE can't be found. Is this a bug of Cmakelists.txt or FindHYPRE.cmake?

Thanks,
Tang Laoya

**Comment by v-dobrev** [comment]
When hypre is built, all necessary headers are copied in one directory, e.g. `hypre/src/hypre/include`. Directories like `parcsr_mv` and `parcsr_ls` (subdirectories of `hypre/src`) are not needed.

**Comment by TangLaoya** [comment]
Thanks. But I didn't find there headers are copied in this folder after I built HYPRE (both 2.11.2 and 2.15.1) by CMake + Visual Studio 2013 in Windows 7 64bit machine. Should I copy these files manually?

Thanks,

Tang Laoya

**Comment by v-dobrev** [comment]
I've never build hypre with cmake so I don't know how the cmake build works. Maybe you need to build __and install__ hypre to some directory?

**Comment by TangLaoya** [comment]
I added '/DMPI_CXX_SKIP_MPICXX' option in Cmake but the errors are still here.

Thanks,
Tang Laoya

**Comment by tzanio** [comment]
You can ask the hypre team directly about their CMake installation here: https://github.com/hypre-space/hypre

**Comment by tzanio** [comment]
According to [FindMPI.cmake](https://github.com/Kitware/CMake/blob/master/Modules/FindMPI.cmake#L1042-L1048) you `MPICH_SKIP_MPICXX` should work with Intel MPI.

It looks also that you can specify `MPI_CXX_SKIP_MPICXX` [directly in CMake](https://cmake.org/cmake/help/v3.10/module/FindMPI.html).

**Comment by TangLaoya** [comment]
At last it works after I added 'MPICH_IGNORE_CXX_SEEK' and 'MPICH_SKIP_MPICXX':

# MPI -> hypre; PETSc (optional)
if (MFEM_USE_MPI)
  if(MSVC)
		add_definitions(-DMPICH_IGNORE_CXX_SEEK)
		add_definitions(-DMPICH_SKIP_MPICXX)
  endif(MSVC)
  find_package(MPI REQUIRED)


Thanks,

Tang Laoya

**Comment by TangLaoya** [comment]
However, when I built latest version mfem-master from github after the same modification to CMakelists.txt, hundreds of errors displayed, for example:
Error	440	error C2039: 'int64_t' : is not a member of 'std'	X:\mfem\mfem-master\mesh\pmesh.cpp	2501	1	mfem
Error	268	error C2039: 'RefCoord' : is not a member of 'mfem::NCMesh'	x:\mfem\mfem-master\mesh\ncmesh_tables.hpp	91	1	mfem
Error	13	error C2061: syntax error : identifier 'RefCoord'	x:\mfem\mfem-master\mesh\ncmesh.hpp	679	1	mfem_miniapps_common

Could you please help me to take a look at it?

Thanks,
Tang Laoya

**Comment by tzanio** [comment]
This is a standard type in C++11.

Can you enable C++11 support in your compiler, or if that's not possible, replace it with `int` in `pmesh.cpp` and `ncmesh.hpp`?

**Comment by TangLaoya** [comment]
Thanks for your kindly reply. Could you please tell me how to enable C++11 support for VS2013 in Cmakelists.txt, or other configure files?

Thanks,
Tang Laoya

**Comment by TangLaoya** [comment]
I noticed that you have enabled C++11 in cmake:
# Require C++11 and disable compiler-specific extensions
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

So it could be the problem that VS2013 doesn't totally support C++11?

On the other hand, after I replaced the 'int64_t' with 'int', the errors except 'int64_t' are still displayed. 

Thanks,
Tang Laoya

**Comment by tzanio** [comment]
As of version 4.0, mfem requires C++11. Can you attach the log with all the compile errors?

**Comment by TangLaoya** [comment]
Dear @tzanio ,
Thank you very much for your kindly reply. The log file is attached, please check it.

Thanks,
Tang Laoya
[mfem_build_err_VS2013.log](https://github.com/mfem/mfem/files/4028219/mfem_build_err_VS2013.log)

**Comment by tzanio** [comment]
Hi @TangLaoya,

I am afraid that the C++11 support in VS13 is [incomplete](https://docs.microsoft.com/en-us/previous-versions/hh567368(v=vs.140)) and these errors are simply C++11 features we use that are not supported.

You can try reverting to an older MFEM release (3.4) or remove the unsupported parts such as the move constructor in `general\mem_manager.hpp`, line 139; the `int64_t` in mesh/ncmesh.hpp, etc. Note however, that in we have officially switched to the new standard and it is likely that other things will break for you in the future if you take the latter route.

Hope this helps,
Tzanio

**Comment by TangLaoya** [comment]
Thanks. I can use the version mem-hertz-dev.
