### ISSUE TITLE
Parallel essential bc for mixed problems (Darcy, Stokes, etc.)

### ISSUE THREAD

**Issue by lephlaux** [mfem/mfem#1216]
Dear all:

I recently started exploring MFEM and I am currently stuck on implementing the essential bc for saddles such as the one given in `ex5p.cpp` (Darcy), and I would very much appreciate some help.  Essential bc were discussed in https://github.com/mfem/mfem/issues/80, which was helpful, however, my implementation only works properly in serial.

In order to extend `ex5p.cpp` for essential bc, consider

ku +∇p = f in Ω
−∇ ⋅u = g in Ω
−p = f_nat on Γ_nat
u ⋅n = f_ess on Γ_ess

where I consider the homogeneous case f_ess = 0 only.  First, I mark the boundary attributes essential and natural.  I defined a 2D grid (see below) with boundary attributes 1 and 2 only.

```c++
  mfem::Array<int> mark_bdr_attr_ess(2);
  mark_bdr_attr_ess[0] = 0;
  mark_bdr_attr_ess[1] = 1; // Mark attribute 2 essential.
  mfem::Array<int> mark_bdr_attr_nat(2);
  mark_bdr_attr_nat[0] = 1; // Mark attribute 1 natural.
  mark_bdr_attr_nat[1] = 0;
```

I initialize the solution `x` and `trueX` by zero, since it will be used to elimite the essential tdofs (well, at least one of them).  The natural boundary markers are passed to `AddBoundaryIntegrator` in the linear form for f:

```c++
   mfem::BlockVector x(block_offsets), rhs(block_offsets);
   mfem::BlockVector trueX(block_trueOffsets), trueRhs(block_trueOffsets);
   x = 0.0;     // This holds the information of trueX with overlap, i.e. x.Size() >= trueX.Size().
   trueX = 0.0; // The sum of trueX.Size() over all processes is equal to dim(Vh) + dim(Wh).
   
   mfem::ParLinearForm *fform(new mfem::ParLinearForm);
   fform->Update(V_space, rhs.GetBlock(0), 0);
   fform->AddDomainIntegrator(new mfem::VectorFEDomainLFIntegrator(fcoeff));
   fform->AddBoundaryIntegrator(new mfem::VectorFEBoundaryFluxLFIntegrator(fnatcoeff), mark_bdr_attr_nat);
   fform->Assemble();
   fform->ParallelAssemble(trueRhs.GetBlock(0));

   mfem::ParLinearForm *gform(new mfem::ParLinearForm);
   gform->Update(W_space, rhs.GetBlock(1), 0);
   gform->AddDomainIntegrator(new mfem::DomainLFIntegrator(gcoeff));
   gform->Assemble();
   gform->ParallelAssemble(trueRhs.GetBlock(1));
```

The essential boundary markers are passed to `EliminateEssentialBC` in the bilinear form for the mass matrix and to `EliminateTrialDofs` in the mixed bilinear form:

```c++
   mfem::ParBilinearForm *mVarf(new ParBilinearForm(V_space));
   mVarf->AddDomainIntegrator(new VectorFEMassIntegrator(k));
   mVarf->Assemble();
   mVarf->EliminateEssentialBC(mark_bdr_attr_ess, trueX.GetBlock(0), trueRhs.GetBlock(0));
   mVarf->Finalize();
   mfem::HypreParMatrix *M;
   M = mVarf->ParallelAssemble();

   mfem::ParMixedBilinearForm *bVarf(new ParMixedBilinearForm(V_space, W_space));
   mfem::ConstantCoefficient minus_one(-1.0);
   bVarf->AddDomainIntegrator(new VectorFEDivergenceIntegrator(minus_one));
   bVarf->Assemble();
   bVarf->EliminateTrialDofs(mark_bdr_attr_ess, trueX.GetBlock(0), trueRhs.GetBlock(1));
   bVarf->Finalize();
   mfem::HypreParMatrix *B;
   B = bVarf->ParallelAssemble();
   
   mfem::HypreParMatrix *BT = B->Transpose();
```

In the MFEM code comments, I found that `EliminateEssentialBC` (and possibly `EliminateTrialDofs`) use tdofs. For the serial case (`-np 1`), I verified the tdof elimination via Octave. As a side note: The elimination procedure can supposably also be performed on the linear algebra level, as there is a function `HypreParMatrix::ParallelEliminateEssentialBC`. However, I seems like it doesn't work for rectangular matrices.

For the scenario, I use an L-shaped domain with boundary attribute 1 (natural bc) on the left-most and right-most vertical boundary and boundary attribute 2 (essential bc) elsewhere. Coefficients are k = 1, g = f = e_ess = 0, f_nat = x(0), yielding a pressure gradient between the outer vertical boundaries and impermeable walls on other boundaries with no external sources/sinks. Finite element spaces are (RT(1), P(1)).

Calling the executable via `mpirun -np 1 ...` (solver converges) and running `glvis -np 1 -m mesh -g sol_u -k "ffRjaaevvA" & glvis -np 1 -m mesh -g sol_p -k "ffRjaammA" &` yields

![p1](https://user-images.githubusercontent.com/807224/71771205-bd11f980-2f37-11ea-8a26-538d91a57fb5.png) ![v1](https://user-images.githubusercontent.com/807224/71771206-c0a58080-2f37-11ea-8bd7-e12a61f3f000.png)

From the physical perspective, this is the expected behavior (I will also run a convergence test against a manufactured solution soon).  On the other hand, running the scenario with `-np 8' gives

![p8](https://user-images.githubusercontent.com/807224/71771208-c4d19e00-2f37-11ea-890e-45b12452b713.png) ![v8](https://user-images.githubusercontent.com/807224/71771209-c8652500-2f37-11ea-96fb-9f6356f482bf.png)

Notice the perturbation in the lower right corner and the nonmatching contour lines between the pressure plots.

I suspect that the transpose of the rectangular matrix, i.e., `mfem::HypreParMatrix *BT = B->Transpose();` is the troublemaker, since `B` (to my understanding) has nonoverlapping/true dof in the trial space (#columns = true dof of `V_space`) and _overlapping_ dof in the test space (#rows = dof of `W_space`).  `BT` on the other hand _should_ have the true dof in the trial space with respect to `W_space`, which is not true when constructed via `*BT = B->Transpose();`.  If my assumption is right, then the question is how to assemble `BT`.  Instead of transposing `B`, I tried defining the adjoint mixed bilinear form via

```c++
   mfem::ParMixedBilinearForm *bTVarf(new ParMixedBilinearForm(V_space, W_space));
   bTVarf->AddDomainIntegrator(new mfem::TransposeIntegrator(new mfem::VectorFEDivergenceIntegrator(minus_one)));
   bTVarf->Assemble();
   bTVarf->EliminateTestDofs(mark_bdr_attr_ess, trueX.GetBlock(0), trueRhs.GetBlock(1));
   bTVarf->Finalize();
   mfem::HypreParMatrix *BT;
   BT = bTVarf->ParallelAssemble();
```
but the transpose integrator is not implemented yet (code compiles but executing throws error with `FiniteElement::CalcDivShape (ip, ...) is not implemented for this class!`). 

Can someone confirm my suspicion and/or point me to a solution?

**Comment by uvilla** [comment]
Dear @lephlaux,

From the code snapshots you reported, the issue seems to be in the following line of codes:

```
mVarf->EliminateEssentialBC(mark_bdr_attr_ess, trueX.GetBlock(0), trueRhs.GetBlock(0));
```
and
```
bVarf->EliminateTrialDofs(mark_bdr_attr_ess, trueX.GetBlock(0), trueRhs.GetBlock(1));
```
`ParBilinearForm::EliminateEssentialBC` and `ParMixedBilinearForm::EliminateTrialDofs` expects as input vectors of `dofs` not of `trueDofs`. That is, the code should read:
```
mVarf->EliminateEssentialBC(mark_bdr_attr_ess, x.GetBlock(0), rhs.GetBlock(0));
```
and
```
bVarf->EliminateTrialDofs(mark_bdr_attr_ess, x.GetBlock(0), rhs.GetBlock(1));
```

Then you can cast each block of `x` and `rhs` as `ParGridFunction` and use `x.GetBlock(i).ParallelAverage(trueX.GetBlock(i))` (i=0,1) and `rhs.GetBlock(i).ParallelAssemble(thrueThs.GetBlock(i))` (i=0,1) to obtain the correct true-Dfos right hand side and initial guess.

> Did you compile mfem without debugging flags, corrects? In the debug mode I would expect `mVarf->EliminateEssentialBC(mark_bdr_attr_ess, trueX.GetBlock(0), trueRhs.GetBlock(0));` and 
`bVarf->EliminateTrialDofs(mark_bdr_attr_ess, trueX.GetBlock(0), trueRhs.GetBlock(1));` to raise a out-of-bound error.

Please let me know if this helps.

**Comment by lephlaux** [comment]
Dear Umberto:

Thank you for your fast response—the assignment of the tdofs _was_ my mistake.  You are also right with MFEM throwing an error when compiled with debug flags, of which I was not aware.  For future readers, compile the library (root directory) via

```
make pdebug -j8
```

Thanks again & best regards.
