### ISSUE TITLE
Loading newer Trelis (Cubit) generated meshes doesn't work

### ISSUE THREAD

**Issue by juan42** [mfem/mfem#122]
Using a recent Trelis version 16.1 (which is basically the only Cubit version for us Europeans) doesn't work with exported Genesis/Exodus files.

The issue is present in https://github.com/mfem/mfem/blob/master/mesh/mesh.cpp#L2615 which assumes  four "magic bytes" in the first line of the file containing "CDF". This has changed in some version of netCDF (i don't know which exactly) to "HDF" plus character code 211.

```
od -N 4 -c projects/nmpc_mfem/data/cyl.e
0000000 211   H   D   F
```

Providing the new magic bytes to the mesh reading process
```
else if (mesh_type.size() > 2 &&
            (mesh_type[0] == 'C' && mesh_type[1] == 'D' && mesh_type[2] == 'F') |
	    (mesh_type[1] == 'H' && mesh_type[2] == 'D' && mesh_type[3] == 'F'))
```
solves the issue and both versions can be opened correctly.

I can setup a PR if this is desired.

Regards

**Comment by tzanio** [comment]
Hi Julian,

This definitely sounds like something we'd like to add, please do submit a PR :)

Maybe something like:
```c++
else if 
  ((mesh_type.size() > 2 && mesh_type[0] == 'C' && mesh_type[1] == 'D' && mesh_type[2] == 'F') ||
   (mesh_type.size() > 3 && mesh_type[1] == 'H' && mesh_type[2] == 'D' && mesh_type[3] == 'F'))
```

Thanks!
Tzanio
