### ISSUE TITLE
Second order mesh

### ISSUE THREAD

**Issue by LeilaSalomon** [mfem/mfem#1221]
Hello,

I have a question regarding the order of the mesh and the library MFEM. Can MFEM read a second order mesh (with gmsh for example), with curved elements ?

Cordially,

Leïla

**Comment by barker29** [comment]
Hi Leïla,

MFEM can read a mesh with curved elements in `.vtk` format - one example is `mfem/data/star-q2.vtk`. I don't know enough about gmsh to answer about that specifically.

**Comment by tzanio** [comment]
Currently we do not support higher-order Gmsh meshes (though we will like to).

To add to @barker29's answer, we do support Quadratic meshes in VTK and CUBIT formats as well as arbitrary order meshes in the MFEM format.
