### ISSUE TITLE
MFEM-4.0 with CUDA and HYPRE 2.18.2

### ISSUE THREAD

**Issue by jwp3** [mfem/mfem#1228]
Hi MFEM team,

I am attempting to combine MFEM's CUDA capabilities with Hypre's (latest release 2.18.2 has GPU support).  Is this possible?  When running ex1p with multiple MPI processes using the suggested input (i.e., ./ex1p -d cuda -pa), the program crashes.

**Comment by tzanio** [comment]
We do not have official support for mfem + hypre on the GPU yet, thought this is something we plan to fix in the near future. Please stay tuned...

**Comment by jwp3** [comment]
I'll keep an eye out, thanks!
