### ISSUE TITLE
Bug in ProjectDiscCoefficient with NCMESH and HDIV/HCURL spaces

### ISSUE THREAD

**Issue by stefanozampini** [mfem/mfem#1230]
Attached is an MWE that, when run with 4 processes, exercises the bug

![BUG](https://user-images.githubusercontent.com/5121281/72243641-7ee29d00-35fd-11ea-8a1b-8c63b4f7df82.png)

Note that, if I don't call EnsureNCMesh, the output is fine.
[test.cpp.txt](https://github.com/mfem/mfem/files/4052748/test.cpp.txt)
[test.mesh.txt](https://github.com/mfem/mfem/files/4052749/test.mesh.txt)

**Comment by tzanio** [comment]
@jakubcerveny, can you take a look at this?

**Comment by jakubcerveny** [comment]
Sure!

**Comment by stefanozampini** [comment]
@jakubcerveny Any update on this issue?

**Comment by jakubcerveny** [comment]
I plan to take a look this week.

**Comment by tzanio** [comment]
Discussion continued in #1274.
