### ISSUE TITLE
Ownership in ParMult()

### ISSUE THREAD

**Issue by ben-s-southworth** [mfem/mfem#1237]
When you construct a HypreParMatrix using ParMult, `HypreParMatrix * mfem::ParMult(const HypreParMatrix *A, const HypreParMatrix *B)` the returned matrix, say C, does not own the col/row starts, so if you delete A or B, you get a seg fault if you try to use C. I think this should be documented and, preferably, at least have an option to make C the owner. This can be done w/ hypre functions. I am looking into if there is an option to deepcopy the row and col starts so that A, B, and C are independent.

**Comment by v-dobrev** [comment]
You can call `HypreParMatrix::CopyRowStarts()` and (if needed) `HypreParMatrix::CopyColStarts()` for the `C` matrix.

**Comment by tzanio** [comment]
This is really a property of `hypre_ParMatmul`, but I agree that it should be documented.

Do you want to a create a small PR for that?

**Comment by themisthemis** [comment]
Arkadaşlar bi konuda banada yardımcı olurmusunuz güzel insanlar

**Comment by iranpump** [comment]
for buying a air compressor silent lets go to 
irancompressor.com
برای خرید انواع [پمپ باد](irancompressor.com) میتوانید به بزرگترین مرجع کمپرسور باد با ادرس ایران کمپرسور مراجعه نمایید.

**Comment by ben-s-southworth** [comment]
Sure, but what are the thoughts on adding a flag or something that allows for a new matrix to be formed using CopyRowStarts and/or CopyColStarts? Could leave the current behavior as default, but allow for a boolean flag to be passed in so that C doesn't depend on A and B.

**Comment by v-dobrev** [comment]
Adding optional argument to `ParMult` sounds fine to me.

**Comment by tzanio** [comment]
@ben-s-southworth, are you interested in proposing a simple PR for this that includes documentation and the optional argument for `ParMult`?

**Comment by ben-s-southworth** [comment]
Yes, I will work on this shortly

**Comment by ben-s-southworth** [comment]
https://github.com/mfem/mfem/pull/1297
