### ISSUE TITLE
Periodic BC Mesh with Sinusoidal mesh distortion

### ISSUE THREAD

**Issue by nickwhitman1993** [mfem/mfem#1240]
Not sure if this has been asked before. If so, please let me know and I can try to go through a previous post.

I am trying to run a pseudo-1D simulation using a periodic mesh, and was wondering if there is any way to distort the mesh sinusoidally (or really otherwise). Really, my main concern is that I can perform a calculation on a mesh with curved surfaces, or rather, distorted. Any thoughts? 

Thanks again for all your help.

**Comment by jandrej** [comment]
Does "curved" mean higher order mesh elements? If yes, you can do the following

```c++
   Mesh *mesh = new Mesh(...);

   mesh->EnsureNodes();
   GridFunction *nodes = mesh->GetNodes();
```
This gives you the `GridFunction` that represents the nodes of the mesh. You can then programmatically go through them and "distort" it however you like. E.g. add random perturbations etc.

Does that answer your question?

**Comment by v-dobrev** [comment]
You can distort the mesh with the `Mesh::Transform` methods. The argument is the mapping from original coordinates to new coordinates, expressed either as a c-function or as a vector coefficient.

**Comment by tzanio** [comment]
Take a look also at the mesh-explorer miniapp in `miniapps/meshing`. You can use it to curve and distort a mesh among other things.
