### ISSUE TITLE
Add convergence rate tests

### ISSUE THREAD

**Issue by gillette7** [mfem/mfem#1254]
There was discussion of adding a convergence rate test as part of the automated testing suite (e.g. compute L2 and H1 error rates for a Poisson problem on a sequence of refined meshes for order r elements and confirm that error decay rates are order r+1 and r).   See files `test/convergence/convergence.cpp` and `test/convergence/makefile` in commit 8d17c9d under #1032, which were developed as a first pass at this.

**Comment by tzanio** [comment]
In addition to the above files (from #1032), convergence tests have also been implemented in the

- https://github.com/mfem/mfem/compare/tests-convergence-dev branch
- the #1218 pull request

We should compare the three versions and decide how we want to unify them.

**Comment by psocratis** [comment]
We could add a simple tool in the library which would take a sequence of numerical and exact solution GridFunctions and output the rate, just for the user to utilize it in an easy fashion. Do you think that would suffice or do we need something more elaborate?

**Comment by tzanio** [comment]
We plan to address this issue in https://github.com/mfem/mfem/pull/1561.

**Comment by tzanio** [comment]
Discussion continued in #1561.
