### ISSUE TITLE
Programmatically generate periodic mesh

### ISSUE THREAD

**Issue by tuckerbabcock** [mfem/mfem#1256]
How do you mark boundaries as periodic with a mesh generated programmatically? Specifically a mesh constructed using:
```language=c++
Mesh(int nx, int ny, int nz, Element::Type type, bool generate_edges = false,
     double sx = 1.0, double sy = 1.0, double sz = 1.0,
     bool sfc_ordering = true)
```

Thanks!

**Comment by v-dobrev** [comment]
Take a look at the 2 miniapps that do this for a 2D mesh: `mobuis-strip.cpp` and `klein-bottle.cpp` in the subdirectory `miniapps/meshing`.

If you just need a cube that is periodic in all 3 directions, you can use the file `data/periodic-cube.mesh`.

**Comment by tzanio** [comment]
I believe @sshiraiwa also has some tools for this in https://github.com/mfem/PyMFEM or https://github.com/piScope/PetraM_Base

**Comment by mlstowell** [comment]
We also have code that can do this in the `stix-dev` branch.  Have a look at `IdentifyPeriodicMeshVertices` and `MakePeriodicMesh` in the `miniapps/common/mesh_extras.?pp`.  See `miniapps/plasma/stix2d.cpp` for an example of the use of `MakePeriodicMesh`.  This function takes as an argument an array which maps slave vertices to their master vertices.  The function `IdentifyPeriodicMeshVertices` can produce this mapping by searching the boundary of the mesh for vertices that line up properly.  However, this search is expensive for large meshes so if you have another way to produce the mapping you should do so.

**Comment by tuckerbabcock** [comment]
Hi all,

Thanks for your help. @mlstowell, both `MakePeriodicMesh` and `IdentifyPeriodicMeshVertices` look like exactly what I'm looking for. Is there a way to specify the wanted periodic dimensions? For example, I'm looking for a mesh that is periodic in `x` and `z`, but not `y`. Will `IdentifyPeriodicMeshVertices` be able to produce the mapping for that, or will I need to do it myself?

Thanks so much,

Tucker

**Comment by mlstowell** [comment]
Hi, @tuckerbabcock ,

Yes, `IdentifyPeriodicMeshVertices` takes a `std::vector` of `mfem::Vectors` as its second argument.  This is a set of translation vectors that translate vertices on one surface to their counterparts on the opposite surface of the mesh. You could pass something like (a,0,0) and (0,0,c) to produce your mapping.

Best wishes,
Mark
