### ISSUE TITLE
Incorrect number of non-zeros after calling ParMult for HypreParMatrix 

### ISSUE THREAD

**Issue by chakshinglee** [mfem/mfem#126]
I found that after calling ParMult, the number of non-zeros (NNZ) of the return HypreParMatrix is not correct. Should there be a call to the function hypre_ParCSRMatrixSetNumNonzeros after hypre_ParMatmul inside ParMult?

**Comment by tzanio** [comment]
See PR #128

**Comment by tzanio** [comment]
Merged in a058165e1
