### ISSUE TITLE
ZZ error with hardcoded settings

### ISSUE THREAD

**Issue by salazardetroya** [mfem/mfem#1269]
In [gridfunc.cpp ZZErrorEstimator](https://github.com/mfem/mfem/blob/1c629d61c60d5463f523abbbfbf84cab8db77074/fem/gridfunc.cpp#L2905), the fluxes never take into account if the integrator has a coefficient because `with_coeff` is hardcoded to 0. Is there any math reason behind? It seems to me that in that case the error would be calculated just for the gradient instead of the flux. If there is no math reason for hardcoding this value, is it okay for me to do a PR to pass this option down from `ZienkiewiczZhuEstimator` constructor?

**Comment by v-dobrev** [comment]
I think adding this option to the function `ZZErrorEstimator` is fine. It can also be added to the class `ZienkiewiczZhuEstimator` which calls `ZZErrorEstimator`. Feel free to propose a PR.

**Comment by tzanio** [comment]
Fixed by #1271.
