### ISSUE TITLE
Directional Flux

### ISSUE THREAD

**Issue by salazardetroya** [mfem/mfem#1272]
Given two vector functions **n** and **p** , is there a way to perform the dot product between both in a fast way? 

I am basically looking at getting a directional derivative \nabla u \cdot \mathbf{n} where I can obtain \nabla u from `GridFunction::ComputeFlux()` and the second could be a `Coefficient` type. \mathbf{n} is not related to any boundary or element normal, it is just a constant vector function. The result would be a `GridFunction` of scalar type.

This would be a pointwise operation, something like taking the value of \nabla u at the gaussian point, perform the dot product with \mathbf{n} and save it in a new `GridFunction` at the same gaussian point (assuming they are in the same finite element space)

**Comment by mlstowell** [comment]
Hi, @salazardetroya ,

There are a number of ways this could be done and some may be more accurate or more quick than others.

The quickest way might be to create a pair of `VectorGridFunctionCoefficient` objects around __n__ and __p__, then create an `InnerProductCoefficient` using these.  You can then project this coefficient onto a scalar grid function.  If the `GridFunction` you project onto is discontinuous e.g. in L2, then this should work fine.  If the scalar field is H1 then the `InnerProductCoefficient` will be evaluated on the interfaces between elements where your derivative may be discontinuous.  This will lead to ambiguous results which depend on the order that the elements are traversed during projection.  Using `ComputeFlux`, as you mentioned, may eliminate the discontinuity so it could work well.

Best wishes,
Mark

**Comment by salazardetroya** [comment]
Thanks to @jandrej  for this code snippet. I ended up implementing it directly accessing the dofs (assuming the functions share the same `FiniteElementCollection`)
```cpp
// Directional flux
ParGridFunction flux_directional(fespace);
std::vector<double> direction = {0.1, 0.5};
for (int i = 0; i < flux_directional.ParFESpace()->GetNDofs(); i++)
{
  for (int j = 0; j < 2; j++)
  {
    flux_directional[i] += flux_func[flux_func.ParFESpace()->DofToVDof(i, j)] * direction[j];
   }
}
```
