### ISSUE TITLE
ParNonlinearForm::GetGradient(x)

### ISSUE THREAD

**Issue by geyan3566** [mfem/mfem#1273]
Hi,

I'm working on a nonlinear problem that uses the DG method with face nonlinear form integrator and it turns out some part of the `GetGradient(x)` has not been implemented. Is there a plan to implement it recently?

Thanks,
Ge

**Comment by tzanio** [comment]
Can you clarify which nonlinear form integrator are you referring to? If you are implementing a new one, you should also implement the Gradient yourself.

**Comment by geyan3566** [comment]
Yes, I implemented a new interface integrator and added it to the `fnfi`, as well as the `AsseembleFaceGrad` function of that integrator. So how different is the procedure that assemble the contributions from `fnfi` between `NonlinearForm` and `ParNonlinearForm`? Sorry that I'm not quite familiar with the DG method, maybe a little heads up will help me to implement it.
Thank you very much.

```
f (fnfi.Size() == 0)
   {
      dA.MakeSquareBlockDiag(pfes->GetComm(), pfes->GlobalVSize(),
                             pfes->GetDofOffsets(), Grad);
   }
   else
   {
      MFEM_ABORT("TODO: assemble contributions from shared face terms");
   }

   // TODO - construct Dof_TrueDof_Matrix directly in the pGrad format
   Ph.ConvertFrom(pfes->Dof_TrueDof_Matrix());
   pGrad.MakePtAP(dA, Ph);
```

**Comment by tzanio** [comment]
I see, you are referring  to https://github.com/mfem/mfem/blob/master/fem/pnonlinearform.cpp#L112-L120

@v-dobrev or @jamiebramwell, can you help?

**Comment by tzanio** [comment]
ping: @jamiebramwell, @jandrej

**Comment by jandrej** [comment]
If you can, please provide more information what you are trying to do.

The `GetGradient(x)` method is for forming the first variation of the nonlinear functional. Element contributions are the same in serial and parallel. There is a difference in the assembly process. If you want to use interior face Integrators in a ParNonlinearForm right now, this won't work.

**Comment by tzanio** [comment]
This issues has been dormant for a while, so I'm closing it. Feel free to reopen if you still have questions.

**Comment by v-dobrev** [comment]
Adding support for face integrators in `ParNonlinearForm::GetGradient` will require some work. It should be very similar to the things we do to support face integrators in `ParBilinearForm::Assemble` for the case of `fbfi.Size() > 0` (`fbfi` stands for "face bilinear form integrator"):
https://github.com/mfem/mfem/blob/4134e9496a77ebccde0819438e050de20480ffb8/fem/pbilinearform.cpp#L233-L247

and in `ParBilinearForm::ParallelAssemble(OperatorHandle &, SparseMatrix *)`, again for the case of `fbfi.Size() > 0`:
https://github.com/mfem/mfem/blob/4134e9496a77ebccde0819438e050de20480ffb8/fem/pbilinearform.cpp#L124-L180

This is definitely something we want to support, it just has not been a priority.

**Comment by miaodi** [comment]
Is there any plan on supporting this feature?

**Comment by v-dobrev** [comment]
See PR #2974.
