### ISSUE TITLE
Parallel anisotropic refinement support

### ISSUE THREAD

**Issue by stefanozampini** [mfem/mfem#1277]
I need anisotropic refinement (conforming) in 3D with hexahedral meshes, and this has to happen on a `ParMesh()`

I tried running `GeneralRefinement()` on a `ParMesh()` obtained after distributing a Mesh (inline-hex) with `EnsureNCMesh()` called (this seems mandatory to be called, otherwise the code ends up doing Bisection on hexas) and I get the error "anisotropic parallel refinement not supported yet in 3D"
However, If I comment out the MFEM_VERIFY checks at beginning of `ParNCMesh::Refine()`, the code runs to completion and the mesh seems fine. @jakubcerveny Thoughts?

**Comment by jakubcerveny** [comment]
Anisotropic nonconforming refinement currently only works correctly in serial. In parallel I'm having trouble synchronizing the propagation of forced refinements. It works to some extent in #422 but not completely. This is still work in progress, unfortunately.

The only thing that works now is refining the mesh anisotropically in serial, then constructing a ParMesh and keeping it as it is. The conforming interpolation works fine and the mesh is usable, but cannot be refined furher. If you disable the checks, you will run into trouble very soon, either the program will crash or some of the nonconforming interfaces will not be interpolated correctly.

**Comment by stefanozampini** [comment]
Thanks for the explanation.
However, I don't need non-conforming refinement, I need anisotropic refinement of a conforming ParMesh.

**Comment by jakubcerveny** [comment]
Oh, you mean uniform anisotropic refinement? I'm afraid the Mesh/ParMesh doesn't support that.

**Comment by stefanozampini** [comment]
How difficult would be to implement it?

**Comment by jakubcerveny** [comment]
I think we could just extend the current UniformRefinement2D_base and UniformRefinement3D_base, add more coarse-fine tables, add an optional argument to Mesh::UniformRefinement(), it's some work but not a huge project, I think it could be done.

**Comment by tzanio** [comment]
This is somewhat specialized and I'm not sure what it means for a general unstructured mesh. I am not sure we want it in the library...
