### ISSUE TITLE
Time-dependent velocity in example 9

### ISSUE THREAD

**Issue by LeilaSalomon** [mfem/mfem#1280]
Hello,

Currently, I'm working on the exemple 9 and I would like to change the initial velocity, so I changed the void velocity_function(const Vector &x, Vector &y). Now, I would like to use a time-dependent velocity, so I use a time-dependent VectorFunctionCoefficient. I call a void velocity_function(const Vector &x, double t, Vector y) and in my function, I declare a time-dependent velocity.

But, when the code is running, the time in the void velocity_function(const Vector &x, double t, Vector y) remains to 0... 

How make it clear that the time in this function is the same that the time called "t" in the main {} ?

I hope you can help me,

Cordially,

Leïla

**Comment by v-dobrev** [comment]
Example 9 does not support a time-dependent velocity.

To enable such support, the use of a time-dependent velocity coefficient is the right first step, however, one also needs to modify the `FE_Evolution` class. When the velocity changes, the advection matrix `K` needs to be re-assembled. This can be done inside the `Mult` method but one needs to have access to both the `BilinearForm` that defines `K` and the time-dependent velocity coefficient (to set its current time via `SetTime`). The simplest way is probably to modify the constructor of the `FE_Evolution` class to accept and store references to the advection `BilinearForm` and its time-dependent `VectorFunctionCoefficient` and then use those in the `Mult` method to update the `K` matrix.

Let us know if you need more specific details about these modifications.

**Comment by LeilaSalomon** [comment]
Thanks a lot for your answer !
