### ISSUE TITLE
ParaViewDataCollection does not respect SetPrefixPath appropriately

### ISSUE THREAD

**Issue by jandrej** [mfem/mfem#1284]
Using `SetPrefixPath` only saves the data in the prefix, but not the `pvd` file.

**Comment by tzanio** [comment]
@bslazarov, can you please address this?

**Comment by bslazarov** [comment]
I will fix it.

**Comment by jandrej** [comment]
It will be addressed by https://github.com/mfem/mfem/tree/paraview-improvements along with other enhancements.

**Comment by tzanio** [comment]
@jandrej, thanks for the clarification. Please add @bslazarov when a PR for `paraview-improvements` is ready.

**Comment by tzanio** [comment]
Addressed in #1296
