### ISSUE TITLE
DG Advection : Conservative form

### ISSUE THREAD

**Issue by LeilaSalomon** [mfem/mfem#1291]
Hello !!

            I'm working on an advection equation. To help me, I'm using exemple 9. My goal is to use the conservative form of the equation and this is not the case for exemple 9. Originally, we have :
   
   BilinearForm m(&fes);
   m.AddDomainIntegrator(new MassIntegrator); 

   BilinearForm k(&fes);
   **k.AddDomainIntegrator(new ConvectionIntegrator(velocity, -1.0));**
   k.AddInteriorFaceIntegrator(
   new TransposeIntegrator(new DGTraceIntegrator(velocity, 1.0, -0.5)));
   k.AddBdrFaceIntegrator(
   new TransposeIntegrator(new DGTraceIntegrator(velocity, 1.0, -0.5)));

   LinearForm b(&fes);
   b.AddBdrFaceIntegrator(
   new BoundaryFlowIntegrator(inflow, velocity, -1.0, -0.5));

   m.Assemble();
   m.Finalize();
   int skip_zeros = 0;
   k.Assemble(skip_zeros);
   k.Finalize(skip_zeros);
   b.Assemble();

So, to have the conservative form I  thought about using an other matrix k ( k = k1 (MixedBilinearForm) + k2 (BiliniearForm) ) : 

   **MixedBilinearForm k1(&dfes, &fes);
   k1.AddDomainIntegrator(new MixedScalarWeakDivergenceIntegrator(velocity));

   BilinearForm k2(&fes);
   k2.AddInteriorFaceIntegrator(
   new TransposeIntegrator(new DGTraceIntegrator(velocity, 1.0, -0.5)));
   k2.AddBdrFaceIntegrator(
   new TransposeIntegrator(new DGTraceIntegrator(velocity, 1.0, -0.5)));**

   int skip_zeros = 0;
   k1.Assemble(skip_zeros);
   k1.Finalize(skip_zeros);
   k2.Assemble(skip_zeros);
   k2.Finalize(skip_zeros);

(I keep the same matrix m and b).

After that, I change the Mult() function :

void FE_Evolution::Mult(const Vector &x, Vector &y) const
{ 
   // y = M^{-1} (K1+K2) x 

   K1.Mult(x, z);
   K2.Mult(x, z2);

  z += z2;

M_solver.Mult(z, y);

}

(In my case, I don't use the b term )

Unfortunately, I don't have correct results with this scheme,  I think I can't understand how MixedScalarWeakDivergenceIntegrator() works...

I hope you can help me,

Cordially,

Leïla

**Comment by HennesHajduk** [comment]
Hi Leila,

since you don't need inflow boundaries, you just need to change the 'BilinearForm k' to the following:

`k.AddDomainIntegrator(new ConvectionIntegrator(velocity));
k.AddInteriorFaceIntegrator(
      new TransposeIntegrator(new DGTraceIntegrator(velocity, -1.0, -0.5)));
k.AddBdrFaceIntegrator(
      new TransposeIntegrator(new DGTraceIntegrator(velocity, -1.0, -0.5)));`

The ConvectionIntegrator now has the opposing sign to incorporate integration by parts, and the face terms are handled appropriately. If you want to gain deeper understanding of this issue, please look at the definition of these classes.

Best
Hennes

**Comment by LeilaSalomon** [comment]
Hello Hennes,

So, to have the conservative form, I just need to change the sign in ConvectionIntegrator() and DGTraceIntegrator() ??

Best,
Leïla
________________________________
De : Hennes Hajduk <notifications@github.com>
Envoyé : mercredi 12 février 2020 07:50
À : mfem/mfem <mfem@noreply.github.com>
Cc : LeilaSalomon <leila.salomon@hotmail.fr>; Author <author@noreply.github.com>
Objet : Re: [mfem/mfem] DG Advection : Conservative form (#1291)


Hi Leila,

since you don't need inflow boundaries, you just need to change the 'BilinearForm k' to the following:

k.AddDomainIntegrator(new ConvectionIntegrator(velocity)); k.AddInteriorFaceIntegrator( new TransposeIntegrator(new DGTraceIntegrator(velocity, -1.0, -0.5))); k.AddBdrFaceIntegrator( new TransposeIntegrator(new DGTraceIntegrator(velocity, -1.0, -0.5)));

The ConvectionIntegrator now has the opposing sign to incorporate integration by parts, and the face terms are handled appropriately. If you want to gain deeper understanding of this issue, please look at the definition of these classes.

Best
Hennes

**Comment by HennesHajduk** [comment]
Yes, because this leads exactly to the assembly of the operator that you get from the conservative form with upwinding for interior faces. Does it work for you?

**Comment by LeilaSalomon** [comment]
I don't really understand why...

Non conservative form is given by :
∂u∂t + v⋅∇u = 0, 

Exemple 9 uses a ConvectionIntegrator  (λ ⋅∇u,v), I think it's used to solve the second term of the above equation.

Now, the conservative form is given by :
∂u∂t + ∇⋅(uv) = 0, 

So, I thought we could no longer use ConvectionIntegrator because now we have the term ∇⋅(uv). Even reversing the sign, like you told me to do, I don't see how ConvectionIntegrator can solve the term ∇⋅(uv). That's why I thought of MixedScalarWeakDivergenceIntegrato, because it gives ∇⋅(λ u), as the second term of the conservative form.

**Comment by HennesHajduk** [comment]
I made a mistake above. The key to getting the conservative form is actually transposition. The correct Integrators and coefficients are as follows:

`k.AddDomainIntegrator(new TransposeIntegrator(new ConvectionIntegrator(velocity)));`
`k.AddInteriorFaceIntegrator(new DGTraceIntegrator(velocity, -1.0, -0.5));`
`k.AddBdrFaceIntegrator(new DGTraceIntegrator(velocity, -1.0, -0.5));`

For the DomainIntegrator, originally in ex9 you have

- <\Lambda \nabla u, v>

and now you get (change of sign and transposition)

<\Lambda \nabla v, u>

which is the volume term that you get from the conservative form, when you do integration by parts and put the matrix in the right hand side. It works similarly for the trace terms, just more tedious.

Sorry for my mistake, I corrected it in my previous comment to avoid confusion.

**Comment by LeilaSalomon** [comment]
I agree, but what about the surface term? To solve ∇⋅(uv) we use an integration by part, as you said, but just the volume term appears in :

k.AddDomainIntegrator(new TransposeIntegrator(new ConvectionIntegrator(velocity)));
k.AddInteriorFaceIntegrator(new DGTraceIntegrator(velocity, -1.0, -0.5));
k.AddBdrFaceIntegrator(new DGTraceIntegrator(velocity, -1.0, -0.5));

Something is missing right?

**Comment by HennesHajduk** [comment]
The interior faces are handled by AddInteriorFaceIntegrator, the contributions on outflow boundaries by AddBdrFaceIntegrator. You can work out the math of how to chose the coefficients by looking at the comment starting at 
[DGTraceIntegrator](http://mfem.github.io/doxygen/html/bilininteg_8hpp_source.html#l02211). 

What I did to work it out was consider the upwind and downwind cases separately and compare the integrals that I want to have with the ones that are provided by DGTraceIntegrator. The only cases known to me use combinations with
![|\alpha| = 2 |\beta|](https://render.githubusercontent.com/render/math?math=%7C%5Calpha%7C%20%3D%202%20%7C%5Cbeta%7C).

**Comment by LeilaSalomon** [comment]
Hennes, thank you very much for your help !
