### ISSUE TITLE
Periodic tetrahedral mesh

### ISSUE THREAD

**Issue by gsosajones** [mfem/mfem#1292]
Hello,

I am trying to create a periodic tetrahedral mesh starting from a periodic triangular mesh. I first extruded the triangular mesh to a prismatic mesh using MFEM's extruder functionality, and then I am cutting each prism into three tetrahedrons. I am able to visualize the mesh on GLVIS and it seems correct, but when I try to use it to run example 1, I get the following error message:

MFEM abort: Tetrahedron elements (L2_T1_3D_P1 FE collection) are not supported yet!
 ... in function: void mfem::Mesh::DoNodeReorder(mfem::DSTable*, mfem::Table*)
 ... in file: mesh/mesh.cpp:1947

Do you have any idea of what could be going wrong here? I am attaching the mesh so that it is easier to see.

Thank you!

Best,
Giselle 
[periodic-tets.txt](https://github.com/mfem/mfem/files/4193327/periodic-tets.txt)

**Comment by v-dobrev** [comment]
I was able to get example 1 working by loading the mesh using
```c++
   Mesh *mesh = new Mesh(mesh_file, 1, 0, false);
```
instead of
```c++
   Mesh *mesh = new Mesh(mesh_file, 1, 1);
```
You may have problems if you want to perform local refinement of the mesh but uniform refinement should be OK.

**Comment by mlstowell** [comment]
Hi, @gsosajones ,

I just a created PR #1306 to address this limitation in MFEM.  We should be able to merge this into master within the next few weeks but feel free to try out the branch `ho-tet-ori-dev` in the mean time.

Thanks for bringing this to our attention.
Best wishes,
Mark

**Comment by gsosajones** [comment]
Thanks a lot. I'll keep an eye out for the pull request.

Best,
Giselle
