### ISSUE TITLE
CMake build with MFEM_USE_SUNDIALS=ON is broken

### ISSUE THREAD

**Issue by cjvogl** [mfem/mfem#1295]
This was discovered by @homijan.  It looks like moving the include of `sparsemat.hpp` in `solvers.hpp` inside an `ifdef` block broke the CMake build with the SUNDIALS interface enabled.

More specifically, there are various compiler errors complaining that `SparseMatrix` and `DenseTensor` are not defined in `solvers.hpp`:
1) line 545 (`SparseMatrix`)
2) line 569 (`DenseTensor`)
3) line 572 (`DenseTensor`)

Seems like the quick fix is to move the include outside of the `ifdef` block, while the proper fix is to updated the CMake lists.

**Comment by pazner** [comment]
This has been addressed in the latest master by #1275.

**Comment by cjvogl** [comment]
Thanks @pazner
