### ISSUE TITLE
suitesparse

### ISSUE THREAD

**Issue by ludmil02** [mfem/mfem#13]
The newest version of SuiteSparse did not work for me. I have both SuiteSparse 5.7.1 installed from source and downloaded from the suite sparse website and also SuiteSparse 4.2.1 installed with macports on macbookpro. The mfem configures and compiles (gcc-mp-4.8) with both versions with no problem. The mfem examples as well. Executing "ex1", however works with SuiteSp4.2.1 and does not with SuiteSp5.7.1. The output is below, have a look and see if you can fix. 

===================OUTPUT of mfem (SuiteSparse 5.7.1)
[machine~]./ex1 -m ../data/fichera.mesh 
Options used:
   --mesh ../data/fichera.mesh
   --order 1
   --visualization
Mesh Characteristics:
Number of vertices : 31841
Number of edges    : 92256
Number of faces    : 89088
Number of elements : 28672
Number of bdr elem : 6144
Euler Number       : 1
h_min              : 0.0625
h_max              : 0.0625
kappa_min          : 1
kappa_max          : 1

NumOfBdrVertices=6146 NumberOfBdrElements=6144
Number of unknowns: 31841

UMFPACK V5.7.1 (Oct 10, 2014): ERROR: ordering failed

UMFPackSolver::SetOperator : umfpack_di_symbolic() failed!
Abort trap: 6
==============================end output mfem(suitesparse 5.7.1)
====================OUTPUT mfem(Suitesparse 4.2.1)
[machine ~]./ex1 -m ../data/fichera.mesh 
Options used:
   --mesh ../data/fichera.mesh
   --order 1
   --visualization
Mesh Characteristics:
Number of vertices : 31841
Number of edges    : 92256
Number of faces    : 89088
Number of elements : 28672
Number of bdr elem : 6144
Euler Number       : 1
h_min              : 0.0625
h_max              : 0.0625
kappa_min          : 1
kappa_max          : 1

NumOfBdrVertices=6146 NumberOfBdrElements=6144
Number of unknowns: 31841
===============================end of output mfem(suitesparse 4.2.1)

**Comment by v-dobrev** [comment]
I tested the example with SuiteSparse 4.4.5 (which comes with UMFPACK version 5.7.1) and I did not encounter any issues.

The issue you see seems to be related to the reordering. Can you try commenting out the line
```
   umf_solver.Control[UMFPACK_ORDERING] = UMFPACK_ORDERING_METIS;
```
to see if that will help - this line assumes that SuiteSparse was compiled with METIS.

**Comment by ludmil02** [comment]
ok, I will try. I do not remember whether I compiled Suitesparse with Metis, I think I did, but not sure. so I will try your suggestion. 

—
Ludmil T Zikatanov
ludmil@zsolvers.net

**Comment by ludmil02** [comment]
Commenting this line or compiling Suite Sparse with Metis. Compiling mfem with libmetis and compiling SuiteSparse without libmetis crashes some of the examples because of 

umf_solver.Control[UMFPACK_ORDERING] = UMFPACK_ORDERING_METIS (in ex1.cpp for example)

but this is no issue at all, commenting this line fixes the problem (if it exists at all).
