### ISSUE TITLE
Discontinuous Galerkin (DG) discretization

### ISSUE THREAD

**Issue by LeilaSalomon** [mfem/mfem#1300]
Hello !!

If I take a triangular mesh, with a DG discretization (order 1), I noticed that the solution is solved on 3 nodes positioned inside each element. I would like to know, how the solution is solved on the extremity of the elements (initial mesh nodes) ?

Best,

Leïla

**Comment by tzanio** [comment]
Not sure I understand the question -- the solution is piece-wise linear in each element and generally discontinuous between elements. The linear function for each element is defined by 3 degrees of freedom. These could be located in the vertices, but don't have to be. (Even when they are located at the vertices, each element has its own degree of freedom for the same vertex).
