### ISSUE TITLE
L1xRT0 - incorrect system matrix ?

### ISSUE THREAD

**Issue by Marshdweller** [mfem/mfem#1301]
Dear MFEM developers,

I have been trying to get a piece of code working for several weeks - I will really appreciate if you could tell me in what direction to look.

The problem is a saddle-point one (I simplified it greatly):

Find (u,P) \in VxW such that 
Int grad u * grad v - Int P * grad v =0, for all v \in V0
-Int grad u * Q + Int (P*Q+ divP div Q) = 0, for all Q \in W
where 
V = {v \in  H1 : v at a part of boundary equals g_D},
W={Q \in H(div) : Q at a part of boundary equals 0}
V0 = {v \in  H1 : v at a part of boundary equals 0),

That is, we know u=g_D and P=0, on a part of the boundary and want to reconstruct u and P from incomplete BCs. This system does not have a solution unless I use some regularization (g_D does not cover the entire boundary). The problem is I end up with a system matrix , which is solvable - I do not understand why.

I am using L1xRT0 FE spaces on a tetrahedral mesh. My implementation is this one:

`FiniteElementSpace *H_space = new FiniteElementSpace(mesh, h1_coll,1);`
`FiniteElementSpace *R_space = new FiniteElementSpace(mesh, hdiv_coll,1);`
`...`
 `BilinearForm *blf_a(new BilinearForm(H_space));`
`blf_a->AddDomainIntegrator(new DiffusionIntegrator);`
`blf_a->Assemble();`
`...`
`blf_a->EliminateVDofs(H_ess_dofs, x.GetBlock(0), rhs.GetBlock(0), DIAG_ONE);`
`blf_a->Finalize();`
`SparseMatrix &A(blf_a->SpMat());`
`...`
`MyMixedBilinearForm * blf_b(new MyMixedBilinearForm(H_space, R_space)); // This class adds a single method -- see below`
`ConstantCoefficient mone(-1.0);`
`blf_b->AddDomainIntegrator(new MixedVectorGradientIntegrator(mone) );`
`blf_b->Assemble();`
`blf_b->EliminateTrialAndTestDofs(dirichlet_markers,x.GetBlock(0), rhs.GetBlock(1) ,									,neumann_markers  ,x.GetBlock(1), rhs.GetBlock(0)); //<-- This is my method to eliminate simultaneously rows from B and columns from B^T working on the LIL matrix` 
`blf_b->Finalize();`
`SparseMatrix & B(blf_b->SpMat()); // (1,0) block`
`SparseMatrix *BT = Transpose(B); //(0,1) block`
`...`
`BilinearForm *blf_c(new BilinearForm(R_space));`
`blf_c->AddDomainIntegrator(new VectorFEMassIntegrator());`
`blf_c->AddDomainIntegrator(new DivDivIntegrator() );`
`blf_c->Assemble();`
`blf_c->EliminateVDofs(R_ess_dofs, x.GetBlock(1), rhs.GetBlock(1), DIAG_ONE); 	blf_c->Finalize();`
`SparseMatrix &C(blf_c->SpMat());`

This gives me the system matrix which is of full rank and has low condition number, but why? The problem is physically undetermined. So far I have checked that MFEM correctly assembles element matrices in my case. Also I have tried to use MixedVectorWeakDivergenceIntegrator to form B^T, but to no avail. Please, help.

**Comment by mlstowell** [comment]
Hi, @Marshdweller ,

My guess is that the natural boundary conditions are adding constraints that make your system full rank. These are related to the boundary integrals that arise during integration by parts which is used to compute some bilinear forms.  For example, the `DiffusionIntegrator` gives rise to a boundary integral of `(n.grad u,v)`, where `n` is the unit surface normal vector. 
Ignoring this term leads to the "natural boundary condition" which in this case is the homogeneous Neumann constraint `n.grad u=0`.  The `DivDivIntegrator` leads to `div P=0`.  These natural BCs are implicitly imposed on all portions of the boundary where Dirichlet BCs are not explicitly imposed.

If this sounds like the culprit, I may be able to help you find the correct way to account for these boundary integrals.

Best wishes,
Mark

**Comment by Marshdweller** [comment]
Hi Mark @mlstowell 

Thank you very much for your time. 

It sounds perfectly reasonable. My biggest concern about those implied boundary integrals is that they are implemented through LinearForms in MFEM. For example,  `n.grad u,g_D`, where `g_D` is a known grid function. In my case, however, they should act as bilinear forms contributing to the system matrix. For example let's take form  `(n.grad u, v)` - "unspecified" boundary DOFs contribute to the matrix, whereas essential DOFs give rise rhs terms. But I am not sure if such non-conventional computations can be implemented.

Also it seems that in the original formulation there are boundary integrals in form `Int u v` and `Int n.grad P n.grad Q` (not related to Green's identity)  and the boundary data are considered simply  in `L^2 (\Gamma)`. May be I made the mistake here by identifying `\Gamma` with the known part of the boundary ignoring the rest.

**Comment by mlstowell** [comment]
Hi, @Marshdweller ,

You are correct, of course, we normally use these implicit integrals with known functions and therefore compute them with `LinearForms`. However, implementing them as `BilinearForms` is not without precedent.  For example, this is how impedance boundary conditions are imposed when modeling wave equations.  Unfortunately, I don't think we currently have the appropriate integrator for the `n.grad u` term or `div P`.  We should be able to write them, perhaps using the corresponding linear form integrators as an example.   You seem quite capable.  Would you like to give it a try?  I'd be happy to offer guidance.

Best wishes,
Mark

**Comment by Marshdweller** [comment]
Mark @mlstowell,

Sure, I can try.

**Comment by Marshdweller** [comment]
Mark  @mlstowell , please let me know when you are ready to get some input.

Regards, 
M

**Comment by tangqi** [comment]
(n.grad u, v) you need has been implemented in this discussion https://github.com/mfem/mfem/issues/792
I have been using it in my applications.

**Comment by mlstowell** [comment]
Hi, @Marshdweller ,
I'm ready but it looks like @tangqi has the solution to the `(n.grad u, v)` term.  We should be able to do something similar for the `(div.P,w)` term.

Best wishes,
Mark

**Comment by Marshdweller** [comment]
Dear Mark and Qi @mlstowell @tangqi 

It seems that this is what I need. If I am correct, Qi's/Tzanio's implementation is similar to BoundaryMassIntegrator::AssembleFaceMatrix. I will try and report later. Thank you! 

M
