### ISSUE TITLE
HypreEuclid::SetOperator()

### ISSUE THREAD

**Issue by geyan3566** [mfem/mfem#1308]
Hi,

I'm solving a nonlinear problem in parallel with `NewtonSolver` in which the linear solver is `HypreGMRES` with `HypreEuclid` preconditioner. A message about MPI appeared:
```
Fatal error in PMPI_Comm_size: Invalid communicator, error stack:
PMPI_Comm_size(114): MPI_Comm_size(comm=0x0, size=0x7ffd62d5002c) failed
PMPI_Comm_size(71).: Invalid communicator
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=738810629
:
system msg for write_line failure : Bad file descriptor
```
After commenting out 
```
   if (A)
   {
      MPI_Comm comm;
      HYPRE_ParCSRMatrixGetComm(*A, &comm);
      ResetEuclidPrecond(comm);
   }
```
in function `HypreEuclid::SetOperator()`, it worked. 
Is it necessary to reset the Euclid preconditioner if `A` is set? 

Thanks,
Ge

**Comment by v-dobrev** [comment]
The method `SetOperator` is called when one wants to reuse the same solver object with a different matrix (or operator, in general). Resetting the `HypreEuclid` preconditioner this way ensures that the preconditioner is rebuild for the `new_A`. We can definitely add an option to `HypreEuclid` that allows you to tell it how often to rebuild the preconditioner, e.g. every k-th call to `SetOperator`, with some convention to never rebuild it, e.g. setting k=-1.

From the error you posted, it is not clear to me where this crash happens -- if you can provide us with a simple reproducer, we can try to debug it.

**Comment by geyan3566** [comment]
Thanks for helping me with this problem.
This error can be easily reproduced by changing a few lines in the original `ex10p.cpp`.
1. Replace code from line 558 to 561 by:
```
HypreEuclid *J_euclid = new HypreEuclid(f.GetComm());
```

2. Replace code from line 563 to 569 by:
```
   HypreGMRES *J_gmres = new HypreGMRES(f.GetComm());
   J_gmres->SetTol(1e-10);
   J_gmres->SetMaxIter(100);
   J_gmres->SetPrintLevel(1);
   J_gmres->SetPreconditioner(*J_euclid);
   J_solver = J_gmres;
```

3. I ran it with `mpirun -np 4 ./euclidtest -m ../data/beam-quad.mesh -s 3 -rs 2 -dt 3 -tf 1`, then I got the following run-time error right after the first newton iteration:
```
Newton iteration  1 : ||r|| = 0.000765269, ||r||/||r_0|| = 0.0154039
Fatal error in PMPI_Comm_size: Invalid communicator, error stack:
PMPI_Comm_size(114): MPI_Comm_size(comm=0x0, size=0x7ffc5a6254ec) failed
PMPI_Comm_size(71).: Invalid communicator
Fatal error in PMPI_Comm_size: Invalid communicator, error stack:
PMPI_Comm_size(114): MPI_Comm_size(comm=0x0, size=0x7ffcabab0c8c) failed
PMPI_Comm_size(71).: Invalid communicator
```

Is it because of my usage of Euclid preconditioner is wrong? Thank you very much.
Ge

**Comment by v-dobrev** [comment]
This is a bug in
https://github.com/mfem/mfem/blob/29d59ce94db097256c39179b02daaaa9ffbaf31f/linalg/hypre.cpp#L2716

The parameter `*A` should be replaced by `*new_A`.

Also, in your modifications above, I had to add
```c++
   J_prec = J_euclid;
```
otherwise I was getting a crash during `delete J_prec;`.

Thanks for reporting this issue! I'll make a PR to fix it.

**Comment by geyan3566** [comment]
Thanks for fixing that problem!
I found another problem with `HypreEuclid()`. Again the same example, and this time I ran with more unknows with 'mpirun -np 4 ./ex10p -m ../data/beam-quad.mesh -s 3 -rs 2 -dt 3 -rp 3' (3 level of mesh refinement). Then I got this error message on each processor:
```
============= error stack trace ====================
[0] ERROR: HYPRE_ParCSRMatrixGetDims() returned 256
       EuclidGetDimensions (HYPRE)  file= getRow_dh.c  line= 66

[0] called from: Euclid_dhSetup  file= Euclid_dh.c  line= 173
[0] called from: HYPRE_EuclidSetup  file= HYPRE_parcsr_Euclid.c  line= 278

application called MPI_Abort(MPI_COMM_WORLD, -1) - process 0
```

Because I'm using `HypreGMRESSolver()` instead of `MINRESSolver()` so it's ok to omit 
```
J_prec = J_euclid;
```
and set the preconditioner with
```
J_gmres->SetPreconditioner(*J_euclid);
```
Thank you very much!
Ge

**Comment by tzanio** [comment]
I'm not sure about this one, it could be a problem in *hypre*...

**Comment by geyan3566** [comment]
I'll post this issue in hypre repo.
