### ISSUE TITLE
Computation of higher-order Nedelec shape functions in MFEM

### ISSUE THREAD

**Issue by Samiullah-Malik** [mfem/mfem#1311]
Hi @v-dobrev @tzanio @mlstowell ,
I am trying to understand how the higher-order Nedelec shape functions are computed in MFEM. Is there a reference that you could point me to which explains this approach? 

From reading @v-dobrev 's response in #566 on the construction of RT spaces, I understand that 1D basis functions can be any hierarchical basis (default in MFEM is to use Chebyshev polynomials). However, I do not understand the role of change of basis from "simple to evaluate basis" to finite element basis "for which we do not have explicit formulas". 
Also, I am not sure what are the `for` loops in `CalcVShape` computing and what is the role of `DenseMatrix T` & `DenseMatrixInverse Ti` in `CalcVShape`. 

If you could provide an explanation of ND spaces similar to that of RT spaces in #566 or point me to a reference, it would be tremendously helpful.

Kind Regards,
Sami

**Comment by dylan-copeland** [comment]
Hi Sami,

Fortunately RT and ND spaces are quite similar, so Issue #566 should be helpful along with some notes on the differences between RT and ND. The roles of `T` and `Ti` are explained in Issue #566, so I would recommend reading it carefully and asking specific questions if it is still unclear.

1) The Piola transformation in H(curl) is u = J^{-T} \hat{u}. For example, see Monk's book on Finite Element Methods for Maxwell's Equations. The transformation for curl u can also be found there. 

2) The ND polynomial space and DOF definitions can be found Monk's book or the 1980 paper by Nedelec.

I hope this helps,
Dylan

**Comment by Samiullah-Malik** [comment]
Hi Dylan, 

Thank you for your response. I have consulted the references you mentioned above. However, I am still a bit unclear about the computation of the Nedelec basis in `CalcVShape`. 

From Monk's book, I see that the Nedelec elements are based on the following polynomial space
`R_k = P_{k-1}^d + S_k` where `k` is the order of the polynomial and `d` is the dimension (for e.g. d=2 for the case of a triangle). After looking at the code for `ND_TriangleElement::CalcVShape` and issue #566, my understanding is that the first two `for` loops are computing the polynomial space `P_{k-1}^d` and the last `for` loop is computing `S_k`. Dobrev refers to it as the second part of 'simple to evaluate basis' in #566. I would like to understand the role of `ip.x - c` and `ip.y - c` here. I can't make the connection between this and the polynomial space `S_k`. 

Please correct if I am wrong in any of my explanations  above.

Kind Regards,
Sami

<img width="502" alt="Screen Shot 2020-03-14 at 7 13 49 PM" src="https://user-images.githubusercontent.com/39503305/76692092-f47fdf00-6627-11ea-8cc0-9f633cb5ee29.png">

**Comment by v-dobrev** [comment]
This is just a shift to the center of the triangle. It does not change the final space. Using this shift helps a little with the conditioning of the change of basis matrix.

**Comment by auhoss** [comment]
Hello,

Thank you for the explanation.  I have a few additional questions about Nedelec shape functions.

1) The line ND_TriangleElement::tk[8] appears to contain the unit triangle tangent vectors (oriented CCW) for the first 6 fields.  Is this correct?  What are the last two fields tk[6],tk[7] containing 0,1?

2) How is the dof2tk used?  What do the values it takes on represent 0,1,2,3?

3) In the discussion from #566, what is u in the LocalInterpolation_ND function?  I am most trying to figure out the which is Psi and which is phi from that discussion.

Thank you.

**Comment by tzanio** [comment]
@dylan-copeland and @v-dobrev, can you help @auhoss ?

**Comment by dylan-copeland** [comment]
@auhoss The `tk` array stores tangent vectors with certain orientations. The last 4 entries are 2 tangent vectors in the `y` direction, with opposite orientations. The orientation to be used is specified by the index in `tk`, from 0 to 3, stored in `dof2tk`. Only one tangent is used with different orientations (y direction).

I am not sure how issue 566 relates to `LocalInterpolation_ND`, which is a function that sets the interpolation matrix from reference to target elements. This function has the comment
`// I_k = vshape_k.J.t_k, k=1,...,Dof`
which shows that it evaluates the dot product of reference basis functions and transformed basis functions.

**Comment by adam-sim-dev** [comment]
Could someone explain to me the meaning of  

https://github.com/mfem/mfem/blob/899a96b7699096c994bf64a375421c9084915141/fem/fe/fe_nd.cpp#L1024-L1025

and 

https://github.com/mfem/mfem/blob/899a96b7699096c994bf64a375421c9084915141/fem/fe/fe_nd.cpp#L1030

It looks like `[1,-1,0], [1,0,-1],[0,1,-1]` without the shift `ip-c`. What did they do exactly?

Thanks.
Adam

**Comment by v-dobrev** [comment]
The Nedelec space of order $k$, $ND_k$, on tets is given by (note that in the code we use $p$ for the order, not $k$)

$$ND_k = \left(P_{k-1}\right)^3 \oplus \left[\vec{x} \times \tilde{P}_{k-1}\right]$$

where $P_{k-1}$ is the space of polynomials of $(x,y,z)$ of degree less than or equal to $k-1$; $\tilde{P}_{k-1}$ is the space of homogeneous polynomials of $(x,y,z)$ of degree $k-1$; and $\vec{x}=(x,y,z)$; in the code we actually use $\vec{x}=(x-c,y-c,z-c)$ which is just a shift to the center of the reference tet.

The part of the code you are asking about is the evaluation of a basis for the second term in the definition: $\vec{x} \times \tilde{P}_{k-1}$.

**Comment by adam-sim-dev** [comment]
I did not see the term $\vec{x} \times $ in Monk's book (2003). Does $\vec{x} \times (\tilde{P}_{k-1})^3 = (\tilde{P}_{k})^3$?

**Comment by v-dobrev** [comment]
There are two families of Nedelec elements on tets. What I described above is the first kind which is implemented in MFEM. The second kind uses the space $\left(P_k\right)^3$ and this second kind is not implemented in MFEM. Monk's book describes both kinds I think, so maybe you are looking at the definition of the second kind.
