### ISSUE TITLE
HypreSmoother::Type vs. int

### ISSUE THREAD

**Issue by ben-s-southworth** [mfem/mfem#1318]
In the HypreSmoother class, the constructor takes a relaxation type `int _type`, but if you call the function `void HypreSmoother::SetType(HypreSmoother::Type _type, int _relax_times)` you need to declare `HypreSmoother::Type` and it doesn't seem to automatically cast. Is there any reason for not using int? 

E.g., calling `smoother -> SetType(1, 1);` results in the error
```
error: invalid conversion from 'int' to 'mfem::HypreSmoother::Type' [-fpermissive]
             smoother -> SetType(0, 1);
```

**Comment by v-dobrev** [comment]
The use of specific enum gives better clarity: `HypreSmoother::l1Jacobi` is easier to understand than just `1`. I'd recommend using the former even when the parameter is just an `int` (any enum is implicitly convertible to `int`). If you prefer to use `1` in `SetType`, you will need to explicitly cast it: `HypreSmoother::Type(1)`.

I think the reason for the difference between the constructor and the `SetType` method is that the constructor was originally implemented with `int` and it was not changed later (when the enum and `SetType` were added) just to be backward compatible.
