### ISSUE TITLE
GridFunction::AccumulateAndCountZones device-related bug

### ISSUE THREAD

**Issue by rcarson3** [mfem/mfem#1322]
As per parts of the comments in #1296, I noticed while testing that PR that I was running into issues related to data that I had projected from quadrature data to an L2 finite element space using the ```ParGridFunction::ProjectDiscCoefficient()``` function was causing errors. Using gdb I've tracked it down to the following line of code  [line 1391](https://github.com/mfem/mfem/blob/master/fem/gridfunc.cpp#L1391) ```(*this)(ldof) += isign*vals[j];``` Whenever this line is run an invalid host-pointer assertion is thrown. 

I'll see if I can't come up with a minimal working example that'll show the problem rather having to use my app to debug this.

@v-dobrev If it helps any when stepping through that line it appears it's specifically throwing the invalid host-pointer assertion at ```mfem::Vector::operator()``` [line 497](https://github.com/mfem/mfem/blob/master/linalg/vector.hpp#L495-L497)

**Comment by rcarson3** [comment]
Here's a minimal example where I've gotten it to fail. It should make debugging this a bit easier:

```c++
#include "mfem.hpp"
#include <fstream>
#include <iostream>

using namespace std;
using namespace mfem;

int main(int argc, char *argv[])
{

   // 1. Parse command-line options.
   const char *device_config = "cpu";

   OptionsParser args(argc, argv);
   args.AddOption(&device_config, "-d", "--device",
                  "Device configuration string, see Device::Configure().");

   args.Parse();
   if (!args.Good())
   {
      args.PrintUsage(cout);
      return 1;
   }
   args.PrintOptions(cout);

   // 2. Enable hardware devices such as GPUs, and programming models such as
   //    CUDA, OCCA, RAJA and OpenMP based on command line options.
   Device device(device_config);
   device.Print();

   // Set-up mesh and finite element space

   int dim = 3;
   Mesh *mesh;
   // Making this mesh and test real simple with 8 elements and then a cubic element
   mesh = new Mesh(2, 2, 2, Element::HEXAHEDRON, 0, 1.0, 1.0, 1.0, false);
   int order = 1;
   int order_0 = 0;
   H1_FECollection fec(order, dim);
   L2_FECollection l2_fec(order_0, dim);

   FiniteElementSpace l2_fes(mesh, &l2_fec, dim);
   GridFunction grid_test(&l2_fes);

   Vector coeff(3);
   coeff[0] = 0.0;
   coeff[1] = 1.0;
   coeff[2] = 2.0;

   //This line is needed or else it fails when the fes->fe(i)->Project method is called
   coeff.HostReadWrite();

   VectorConstantCoefficient vec_coeff(coeff);
   //grid_test.HostReadWrite(); // This line doesn't appear to help any.
   grid_test.ProjectDiscCoefficient(vec_coeff, mfem::GridFunction::ARITHMETIC);

   delete mesh;
}
```

**Comment by tzanio** [comment]
Discussion continued in #1327.
