### ISSUE TITLE
Parallel matrix multiplication

### ISSUE THREAD

**Issue by e-aranda** [mfem/mfem#1324]
Hi, I don't know what I am doing wrong but I don't understand why I get wrong results if I use more than one processor. Defining a `ParBilinearForm` and multiplying for a `ParGridFunction` I get different results for 1 or 2 processors.

```c++
u_gf = new ParGridFunction(fespace);
u_gf->ProjectCoefficient(coeff);
ConstantCoefficient one(1.0);
ParBilinearForm *a = new ParBilinearForm(fespace);
a->AddDomainIntegrator(new DiffusionIntegrator(one));
a->Assemble();
  
ParGridFunction X(fespace);
a->Mult(*u_gf,X);
X.Print();

a->Finalize();
HypreParMatrix *A;
A = a->ParallelAssemble();
A->Mult(*u_gf,X);
X.Print();
```

**Comment by tzanio** [comment]
You can't do `A->Mult(*u_gf,X)` the assembled matrix operates on `HypreParVector` objects:

```c++
HypreParVector vecU, vecX;
u_gf->ParallelAverage(vecU);
A->Mult(vecU,vecX);
X=vecX;
```

A lot of this is automatically handled by the `FormLinearSystem`/`RecoverFEMSolution` interface. See also Figure 4 in https://arxiv.org/pdf/1911.09220.pdf.

**Comment by e-aranda** [comment]
Ok, thank you.
