### ISSUE TITLE
How to solve PDE on subset of mesh?

### ISSUE THREAD

**Issue by tuckerbabcock** [mfem/mfem#1331]
Hi,

Is there a straightforward way to solve a given problem on a subset of the mesh (i.e. exclude elements that have a specific attribute)?

For a concrete example, consider something similar to the Joule miniapp; solving low-frequency EM and thermal problems on a domain of a metal rod, and some surrounding air. I want to solve the EM problem on the entire domain (rod + air), but then solve the thermal problem on just the rod. It seems to make more sense to solve the thermal problem on the subset of the mesh, as the surface of the rod is a more natural location to prescribe thermal boundary conditions, and there would be some wasted computation solving the thermal problem in the air region (though I'm more concerned with boundary conditions than cost).

A solution might be to have two distinct meshes kept in memory, and project the solution from the full EM mesh to the smaller thermal mesh, but I expect transferring the solution from one mesh to the next would be difficult if the rod region of these meshes are not identical.

Thanks as always,
Tucker

**Comment by tuckerbabcock** [comment]
@tzanio have you gotten a change to look at this?

**Comment by tzanio** [comment]
Hi Tucker,

There is no easy solution to this, but one option could be to have different meshes for the two regions and use the new findpts functionality in MFEM to get values from one of the mesh in the other. That is designed to work even if the meshes are not the same.

@kmittal2 is the expert on this, and can probably provide some help.

Tzanio

**Comment by kmittal2** [comment]
Hi Tucker, we have a miniapp in the works for exactly this. See [PR#1293](https://github.com/mfem/mfem/pull/1293).
This PR adds field-interp.cpp which provides the capability of transferring the solution from one mesh onto another mesh. Check it out and let me know if you have any questions (here or via email).

**Comment by tuckerbabcock** [comment]
Thanks @tzanio and @kmittal2. The miniapp looks like a template for exactly what I’m looking for.

**Comment by tuckerbabcock** [comment]
Hi @tzanio and @kmittal2,
I'm revisiting this, and hoping to transfer a solution in an H(div) space to another mesh, however, it seems it does not support vector finite elements: `FindPointsGSLIB::GetNodeValues` calls `GridFunction::GetValues` which does not support elements with a `MapType` other than `VALUE`. Is there a way to transfer an H(div) gridfunction?

Thanks,
Tucker

**Comment by tzanio** [comment]
@kmittal2 may have further suggestions, but I'm afraid we can currently transfer only H1 fields with `FindPoints`.

It should be possible to extend that to other spaces, including H(div), we just haven't done it yet. Ketan, what do you think?

**Comment by tzanio** [comment]
I am closing this for now, but we have taken note and plan to add support for non-H1 spaces to findpts in the future.
