### ISSUE TITLE
NCMesh saving

### ISSUE THREAD

**Issue by januszpigonia** [mfem/mfem#1332]
How can I in example 6p save the configuration (ncmesh and solution) after a few refinement steps and then restore the results and continue ?

Janusz

**Comment by jakubcerveny** [comment]
This is something that's high on my TODO list. We need to extend the MFEM 1.1 mesh format to allow for saving a parallel NC mesh, which is unfortunately not possible right now.

**Comment by tzanio** [comment]
Please see #1392 and provide feedback there on the new NCMesh format.
