### ISSUE TITLE
Applying loads and fixed boundary conditions on a node.

### ISSUE THREAD

**Issue by rajpradi** [mfem/mfem#1334]
Hello Sir,

I have started using MFEM recently. I found it very helpful in my research. I am having a question about the boundary condition section.

I could not able to figure out how should I apply loads on a particular node. In one of the issue you have suggested a code to apply fixed boundary condition on nodes but I could not able to understand completely. Can you please tell me how we use this approach to apply loads on nodes and also what changes do we need to do in mesh file for this? (I.e., where should we define the locations about nodes?)
 

Your suggested code is pasted below:
```c++
   Array<int> ess_tdof_list;
   const int node = 0;
   if (fespace->GetOrdering() == Ordering::byNODES)
   {
      int num_oned_dofs = fespace->GetVSize() / space_dim;
      for (int i=0; i<space_dim; ++i)
      {
         ess_tdof_list.Append(num_oned_dofs*i + node);
      }
   }
   else
   {
      for (int i=0; i<space_dim; ++i)
      {
         ess_tdof_list.Append(space_dim*node + i);
      }
   }
```
Something like this could replace section 8 in `ex2.cpp`. Note that this will not work in parallel.

_Originally posted by @barker29 in https://github.com/mfem/mfem/issues/1022#issuecomment-523676351_

Thank you.

Regards,
Raj

**Comment by barker29** [comment]
Hi Raj,

I am not sure I understand fully what you are asking. Generally it makes sense to apply loads on surfaces, not nodes, and this is done in MFEM using `LinearForm` and `BoundaryIntegrator` objects as in `ex2`. Do you really want to apply a load in the RHS on a single node or do you have a collection of nodes that make up some kind of surface?

**Comment by rajpradi** [comment]
Thank you very much for your response. 

Yes, I was looking to add loads in the RHS on a single node. 
Sir, basically I am working on topology optimization pipeline and I need MFEM to obtain deflection values. Looking into the published work of topology optimization, people have implemented point load in their analysis. 

Furthermore, I found a comment (mentioned in the previous message) to apply a fixed boundary condition on a single node, but I could not able to figure out how can I use it to apply load. If you have any suggestion please let me know.

Or can you suggest me any way to convert a nodal load on edges or faces mathematically?

Thanks. 
Raj

**Comment by barker29** [comment]
If you really want to apply a load to a single node, you would put appropriate values in the right-hand side of the linear system corresponding to the node. Something like `B(dof_number) = val;` where `B` is the `Vector` on the right-hand side of the linear system.

**Comment by rajpradi** [comment]
Thank you Very much Sir for your help. 

Just one small question, can you please tell me how can I print or get the values of GridFunction x and SparseMatrix A?
I want these values so that I can directly save the GridFunction values to another vector and use it in loop instead of saving it in sol.gf  file.

Thanks,
Raj

**Comment by tzanio** [comment]
You can just index the values, e.g. `x(i)` and `A(i,j)` or save them with `Vector::Print` and `SparseMatrix::Print`.
