### ISSUE TITLE
Normal derivative on boundary of  NURBS mesh

### ISSUE THREAD

**Issue by IdoAkkerman** [mfem/mfem#1336]
I am trying to implement weak dirichlet BCs for a laplace problem using `DGDiffusionIntegrator`. 
For NURBS meshes I get the error: 

> NURBSFECollection::DofForGeometry

I have tried to figure out what is missing, but I am getting lost in the Face/Boundary semantics, particularly related with the element transforms.
Does any body have any ideas at this stage? I will try to formulate  more precise questions in the near future.

**Comment by IdoAkkerman** [comment]
To create the issue look    branch` weakbc-nurbs-dev` in  miniapps/nurbs and run for instance:

> ./nurbs_ex1 -m square-nurbs.mesh --weak-bc

**Comment by IdoAkkerman** [comment]
I think I need modify:
`void FiniteElementSpace::GetFaceDofs(int i, Array<int> &dofs) const` on fespace line 1742
and add an` if ( elem_dof)` similar to the GetElementDofs and GetBdrElementDofs routines.


Does `FiniteElementSpace::GetFaceDofs` provide the full list of all dofs defined on the element attached to a boundary? So would translating the face-id to an element-id and then extract the dofs of that element do the trick?

**Comment by tzanio** [comment]
@mlstowell or @v-dobrev, can you help Ido with this?

**Comment by mlstowell** [comment]
Hi, @IdoAkkerman ,

Sorry for the delay.  I was on travel and missed this when it was first raised.

`FiniteElementSpace::GetFaceDofs()` returns only those degrees of freedom which are shared by any elements which share that face.  Consequently, in a DG context this method should not return any degrees of freedom.

Best wishes,
Mark

**Comment by IdoAkkerman** [comment]
Hi @mlstowell,

thank you for your answer. I am struggling a bit with the boundary/face stuff.
I would like to implement a Nitsche BC for a NURBS mesh. For this I need a normal gradient.
In order to get a normal derivative, you would need in principle all functions active at a boundary, not just the non-zero functions. So which call do I need to make to get the correct DOFS?

**Comment by mlstowell** [comment]
Hi, @IdoAkkerman ,

I was not familiar with Nitsche BCs but from what I could find they look very similar to what we do for Discontinuous Galerkin methods.  Have a look at the [`DGDiffusionIntegrator`](https://github.com/mfem/mfem/blob/cd4de7abab2c9df2e22b812c4fe77debe57b5d83/fem/bilininteg.hpp#L2546) which seems to have three of the four terms you might need.

The basic idea behind these DG integrators is that the `BilinearForm` or `LinearForm` loops over the boundary elements and requests a `FaceElementTransformations` object from the mesh using `Mesh::GetBdrFaceTransformations(int bdr_elem_no)`.  This object contains pointers to the `ElementTransformation` objects associated with the boundary face and its neighboring volume element (normally there are two neighboring volume elements but at the boundary one of these is NULL).  These transformations are then passed into an integrator such as `DGDiffusionIntegrator`.  Inside the integrator the `ElementTransformation` for the boundary face is used to compute the surface integral while the `ElementTransformation` for the neighboring element is used to compute the basis functions or their derivatives.  The DoFs don't appear inside the integrator itself but they are the DoFs associated with the neighboring element not just the face (this is only true in a DG context).

Best wishes,
Mark

**Comment by v-dobrev** [comment]
The main issue here is that with NURBS meshes, the face transformation, in general, may depend on dofs that are associated with the interior of elements, and not just adjacent elements but even neighbors of neighbors. That is why we do not have support for DG on NURBS meshes, at least for now.

However, the boundary faces are very similar to the standard case and I think they can be supported with small additions. I'm not sure modifying `FiniteElementSpace::GetFaceDofs` will be sufficient but it is worth looking into. Maybe the simplest approach is to try to reuse the boundary elements which are defined for the NURBS mesh. To do that we just need to create a map (or just an array) that tells us what boundary index a given face index corresponds to. Another thing to keep in mind is the potential difference in the orientation of the face element and the respective boundary element -- the vertex indices may be permuted between the two. I think they are the same but I'm not 100% sure. This is important when we define the `Loc1` transformation in the `FaceElementTransformations` class -- `Loc1` tells us how to transform quadrature points from the reference face to the reference element (for element 1).

**Comment by IdoAkkerman** [comment]
@v-dobrev you are right: 

>  the face transformation, in general, may depend on dofs that are associated with the interior of elements, and not just adjacent elements but even neighbors of neighbors. 

I did not know how to phrase this. thank you for phrasing it so clearly.

I tried to get it working with quick and dirty hacking, but it did not work. Part because the distinction bnd/face was entirely clear to me. Because when the transformation enter the seen I lose track of what is what. So I tried to ease my way into it.

I think I can devote 50% of my time to get this working form next week on, till end of "lock-down" which is not before April 6.

**Comment by v-dobrev** [comment]
@IdoAkkerman, sounds good. Let us know if you run into any issues.

**Comment by IdoAkkerman** [comment]
I have been looking a bit closer, and have the following idea. 
The routines 

```
   virtual void GetElementDofs(int i, Array<int> &dofs) const;
   virtual void GetBdrElementDofs(int i, Array<int> &dofs) const;
   virtual void GetFaceDofs(int i, Array<int> &dofs) const;
```
in fespace due something analogues. However, in the implementation of the first 2 routines, there is an if-statement at the beginning, using a Table it it is there instead of generate the dof indices on the fly. See below:

```
   if (elem_dof)
   {
      elem_dof -> GetRow (i, dofs);
   }
```
and
```
   if (bdrElem_dof)
   {
     bdrElem_dof->GetRow(i, dofs);
   }

```
In the case of NURBS the Table is used, as the standard dof association does not work.
So I will need to make a similar diversion for the faces, that is e.g.:
```
   if (faceElem_dof)
   {
     faceElem_dof->GetRow(i, dofs);
   }

```

Do you think this should work?

**Comment by IdoAkkerman** [comment]
The difference between the fespace functions:
   virtual void GetFaceDofs(int i, Array<int> &dofs) const;

**Comment by IdoAkkerman** [comment]
I have some issues with understanding the subte difference between
`FiniteElementSpace::GetBdrElementDofs()` and
`FiniteElementSpace::GetFaceDofs()`

If I understand correctly, "face" refers to all the boundaries of the interior elements, while a "bdr" refers to a subset of faces that are on the "boundary" of the domain.

But there seems to be a different dof ordering in both routines? Is this correct? Why? What is the purpose/goal? 

I tried to implement an alternative `FiniteElementSpace::GetBdrElementDofs()`  by bootstrapping from `FiniteElementSpace::GetFaceDofs()`  by adding an alternative means of obtaining the dof indices, namely:
```
else if (mesh)
   {
     GetFaceDofs(mesh->be2face(i),dofs);
   }
```

`be2face `is a hacked-function. This method seems to _almost_ work: when running th unit_test the indices are always correct, but sometimes (10% of time) the ordering is incorrect.

What am I missing ? Why is the ordering different?

**Comment by v-dobrev** [comment]
I'll start by answering the last question.

The main difference between the boundary and face elements is that the first one is read from the mesh file and the second one is auto-generated. Because of that the ordering of the vertices that describe them may be different. We could rotate the boundary elements to match the auto-generated face elements but this may disrupt certain workflows, so we do not do it.

Because of this, when we generate the dofs for a boundary element, we need to find its orientation w.r.t. the auto-generated face/edge and permute the dofs to match the auto-generated face/edge.

This permutation is applied, for example, here: https://github.com/mfem/mfem/blob/4134e9496a77ebccde0819438e050de20480ffb8/fem/fespace.cpp#L1720-L1736

The local permutation array `ind` of the dofs is obtained from the `FiniteElementCollection`, here:
https://github.com/mfem/mfem/blob/4134e9496a77ebccde0819438e050de20480ffb8/fem/fespace.cpp#L1724-L1725

based on the orientation `oF` obtained from the `Mesh`, here:
https://github.com/mfem/mfem/blob/4134e9496a77ebccde0819438e050de20480ffb8/fem/fespace.cpp#L1687

This is also the call where we obtain the index `iF` of the respective face element.

Note that this dof permutation is not necessary in the method `GetFaceDofs` because the enumeration of the dofs on a face uses the orientation of the auto-generated face element.

**Comment by v-dobrev** [comment]
Regarding the diversion:
```c++
   if (faceElem_dof)
   {
     faceElem_dof->GetRow(i, dofs);
   }
```
I think this will work for the NURBS case. I believe these diversions for the elements and the boundary were originally added (by you) to support the NURBS case. Now these `Table`s are generated for all mesh types.

Since you are interested only in face elements that are on the boundary, you only need to generate the rows of `faceElem_dof` corresponding to those. You can leave the other rows empty, at least for now.

Looking back at the place where you encountered the error, I think the method `FiniteElementSpace::GetFaceElement`, called here: https://github.com/mfem/mfem/blob/4134e9496a77ebccde0819438e050de20480ffb8/mesh/mesh.cpp#L497

may need to be modified to support the NURBS case too. There is a comment in that method that hints how this may be done (probably left by you 😄):
```c++
   // if (NURBSext)
   //    NURBSext->LoadFaceElement(i, fe);
```

**Comment by IdoAkkerman** [comment]
Thanks for the clear answers. 
You are right about the LoadFaceElement call. I tried getting this to work 2 months before, but did not get it to work due to subtle issues and trail-and-error gives to many combinatorial options.

**Comment by IdoAkkerman** [comment]
I think I have something working!!! Needs mayor cleaning and checking, but good news anyway!

**Comment by IdoAkkerman** [comment]
Yes, for the serial implementation everything seems to work.

There are 2 potential "issues" though:

1) My approach: Instead of defining a `face_dof` table, I am using the `bdrElem_dof` table  and a mapping from face to bdr.

2) I have added some face2bdr routines to the mesh class:
```
   int GetBdrFace(int i)const;      
   void GenerateFaceBdrMap();
   int GetFaceBdr(int i) { return face_to_be[i]; }
```
Where `GetFaceBdr()` is the transpose (inverse?) of  `GetBdrFace()` which is computed in `GenerateFaceBdrMap()`. This last routine needs to be called before `GetBdrFace()` makes sense. This makes it important to put `GenerateFaceBdrMap()` on the right location, and/or add (debug) checks.

I have an other comment/question:
the routine   `int GetBdrFace(int i)const;` does the same as `int GetBdrElementEdgeIndex(int i)`, but the later has an incorrect/non-descriptive name.  Should I change that?

**Comment by IdoAkkerman** [comment]
Perhaps I should use the procedures described above to generate a partial `face_dof` table.

Conceptually it is the same as above, but it will make the runtime code robust and clean(simple face_dof check and usage if available), and isolates the more (NURBS) specific, potentially fragile, items to the initialization. 

I will first work on the parallel stuff and see what is necessary on that front.

**Comment by IdoAkkerman** [comment]
Parallel also seems to work with minimal effort.
Going the `face_dof` route will lead to more "symmetry" in the code. Will work on that tomorrow.

**Comment by IdoAkkerman** [comment]
I implemented the `face_dof` route in the branch **nurbs-face-dev**  . I already submitted a PR #1414
