### ISSUE TITLE
Visualizing per-element det(J) w/ mesh-explorer?

### ISSUE THREAD

**Issue by xjrc** [mfem/mfem#1339]
The `mesh-explorer` meshing mini-app has a very handy feature that allows the user to query a source mesh's minimum and maximum det(J) values, which makes it very easy to determine whether or not a mesh has inverted elements. However, once a mesh is known to be inverted, it's difficult to use the top-level quality metric visualizations (i.e. element sizes, element ratios) to track down the offending elements. Is there any way to visualize each element's det(J) metric directly, or to otherwise make this tracking process more robust? Thanks in advance for any advice/guidance you can provide!

**Comment by tzanio** [comment]
Hi Joe,

Mesh Explorer also has the option `x`, which checks the determinant of the Jacobian in a given lattice of points. You can easily modify the code:

https://github.com/mfem/mfem/blob/master/miniapps/meshing/mesh-explorer.cpp#L526-L585

to output the element number and the coordinates of any point where the mesh is invalid.

Hope this helps,
Tzanio

**Comment by v-dobrev** [comment]
For 2D meshes you can view `det(J)` directly -- pressing the `e` key toggles what is visualized:
```
e - Toggle the "elements" state (see below for vector functions)
    The options are: -> show surface elements (corresponding to the function)
                     -> show no surface elements
                     -> show element attributes (2D)
                     -> show element det(J) (2D)
                     -> show element 1/det(J) (2D)
                     -> show element kappa (2D)
                     -> show element kappa + 1/kappa (2D)
```
(this is an exerpt from the [GLVis README](https://github.com/GLVis/glvis/blob/ab82359a9b8adb548369a9514c183703140bd7b2/README#L79-L86))

As usual, the `i/I` keys allow you to control the subdivision factor to get a better representation of the current field.

Also note that when pressing `e`, GLVis will print on the terminal which field is currently visualized.

**Comment by xjrc** [comment]
> Hi Joe,
> 
> Mesh Explorer also has the option `x`, which checks the determinant of the Jacobian in a given lattice of points. You can easily modify the code:
> 
> https://github.com/mfem/mfem/blob/master/miniapps/meshing/mesh-explorer.cpp#L526-L585
> 
> to output the element number and the coordinates of any point where the mesh is invalid.
> 
> Hope this helps,
> Tzanio

Apologies for being unclear; the `x` option is actually what I've been using to find inverted elements! I hadn't considered modifying its source to extract the information I need, but that's a great idea; thank you for the suggestion and for pointing me in the right direction!

> For 2D meshes you can view `det(J)` directly -- pressing the `e` key toggles what is visualized:
> 
> ```
> e - Toggle the "elements" state (see below for vector functions)
>     The options are: -> show surface elements (corresponding to the function)
>                      -> show no surface elements
>                      -> show element attributes (2D)
>                      -> show element det(J) (2D)
>                      -> show element 1/det(J) (2D)
>                      -> show element kappa (2D)
>                      -> show element kappa + 1/kappa (2D)
> ```
> 
> (this is an exerpt from the [GLVis README](https://github.com/GLVis/glvis/blob/ab82359a9b8adb548369a9514c183703140bd7b2/README#L79-L86))
> 
> As usual, the `i/I` keys allow you to control the subdivision factor to get a better representation of the current field.
> 
> Also note that when pressing `e`, GLVis will print on the terminal which field is currently visualized.

Thank you, Veselin, and I apologize for having you repeat something from the GLVis manual. I've been referring to that manual very regularly to figure out the commands I need (e.g. cycling through materials), but it looks like I didn't search for the right keywords for the det(J) visualization (foolishly, I believe I only searched for "jacobian" and "inverted" instead). Nevertheless, this should do wonders, so thanks again for the tip!
