### ISSUE TITLE
Build error related to debug builds

### ISSUE THREAD

**Issue by rcarson3** [mfem/mfem#1350]
So, I ran into this issue while building a typical debug build in ```ExaConstit``` and noticing that the build was failing after migrating to the v4.1 release.

It appears that the culprit was a ```-DDEBUG``` flag being added for debug builds which appears to clash with the ```Id``` enum defined in ```device.hpp``` having the same name. Also to make things more interesting, it turns out this only fails to build on non-CUDA builds. 

I don't need this flag directly within ```ExaConstit```, but it does come into play for one of our libraries we depend on, ```ExaCMech```, which for the most part is an all-headers library. I should be able to change these flags on my end, but I figured I'd bring it up as a potential issue people might run into.

**Comment by tzanio** [comment]
Can you provide more details so we can reproduce it?

**Comment by rcarson3** [comment]
Sorry about that wrote that up just before leaving work...

If you run the below cmake invocation and then make this should reproduce the same set of errors that I was seeing when compiling ```ExaConstit``` in debug mode. I don't think this should matter much, but I was using a gcc/7.3.1 compiler.

```
cmake ../ -DMFEM_USE_MPI=ON \
  -DMETIS_DIR=${METIS_DIR} \
  -DHYPRE_DIR=${HYPRE_DIR} \
  -DCMAKE_INSTALL_PREFIX=../install_dir/ \
  -DCMAKE_BUILD_TYPE=Debug \
  -DCMAKE_CXX_FLAGS_DEBUG="-DDEBUG"
```

I don't specifically use  ``` -DCMAKE_CXX_FLAGS_DEBUG="-DDEBUG"``` in my cmake call, but one of our CMakeList files appends the ```-DDEBUG``` flag to that variable.

**Comment by v-dobrev** [comment]
I think this is an issue that has to be addressed by `ExaCMech` -- using a generic macro as `DEBUG` in their headers is not a good idea when you expect to work with other libraries. I'd recommend using something like `EXACMESH_DEBUG`. MFEM has its own version of that callled `MFEM_DEBUG`.

**Comment by rcarson3** [comment]
@v-dobrev that's the plan to fix it in ```ExaCMech```. I wouldn't expect y'all to fix something like this.  I just wanted to bring this to light just in-case others run happen to run into it down the road. I can go ahead and close this now.
