### ISSUE TITLE
Applying boundary conditions according to mesh node numbering

### ISSUE THREAD

**Issue by garobed1** [mfem/mfem#1355]
Hello,

I am implementing a mesh motion algorithm through linear elasticity analogy. Essentially, I am first finding updated boundary node locations for the mesh, then applying the displacements of those nodes as essential boundary conditions for a linear elasticity problem, to move the interior nodes. I have the list of boundary node displacements that I need, in an array numbered according to the mesh node numbering. I'm not sure how to actually apply these node-wise boundary conditions. 

My first instinct was to create a derived node-wise `Coefficient` class that evaluates as a function of mesh node numbering and project onto the solution gridfunction, since `Eval` takes the integration point as an argument. However, I can't find a way to get a mesh node number from an integration point, and I figure that such a  thing is not likely possible since it would only really work for H1 elements of order 1, since the integration points are at the mesh nodes, assuming non-curved elements.

Is there some capability for coefficients that would help with this, or is there a better way to apply boundary conditions according to mesh node numbering? To make things easier, the surface nodes  on the mesh I'm using are ordered before the interior nodes. 

As an aside, the geometry has interior surfaces as well, and I want to apply similar 'boundary' conditions to those as well. I want to think that I can simply mark those surfaces as 'essential boundaries' and apply similar conditions there, but what will that entail otherwise?

Thanks,
Garo

**Comment by vladotomov** [comment]
Hi Garo,

What exactly do you mean by "mesh node numbering". The `Mesh` class has a field `Nodes`, which is a `GridFunction` storing the node positions. Is your "mesh node numbering" related to `Nodes` or is it something else?

Vladimir

**Comment by garobed1** [comment]
I'm personally not referring specifically to the `Nodes` gridfunction, I'm referring to the ordering of the nodes when I query the mesh (using PUMI) for the displacement information. I imagine that the ordering when I convert from the PUMI mesh to the MFEM mesh would remain consistent, and that would be reflected in `Nodes`.

In any case, I think my solution will be to use the associated `FiniteElementSpace` to apply specific nodal boundary conditions using `DofToVDof, similar to how `ProjectCoefficient` works, but without the coefficient evaluation. I'll see if it works myself.

**Comment by tzanio** [comment]
> In any case, I think my solution will be to use the associated FiniteElementSpace to apply specific nodal boundary conditions using DofToVDof, similar to how ProjectCoefficient` works, but without the coefficient evaluation. I'll see if it works myself.

This sounds right. You impose Dirichlet condition on a bilinear form in a given finite element space by specifying a grid function in the space and the set of degrees of freedom where the conditions should be imposed. See example 1 and 2.

**Comment by cpolindara** [comment]
Hi to all,

@garobed1  have you figured out the solution to the problem yet? If you, could you please share a brief outline of your solution? I am really interested in this problem.

Much appreciated :)


Cheers,
