### ISSUE TITLE
Output IGA results to new VTK cell: Bezier

### ISSUE THREAD

**Issue by GregVernon** [mfem/mfem#1356]
A recent addition to VTK was to add Bezier cells, which are the building blocks of B-splines (and NURBS).  I saw the recent MFEM release notes  

> Added support for output in the ParaView XML format. Both low-order and high-order Lagrange elements are supported.

and was wondering whether MFEM writes Bezier elements?  The latest version of ParaView (v5.8) supports Bezier elements as specified in the below VTK merge request and attached PDF.  

https://gitlab.kitware.com/vtk/vtk/-/merge_requests/6055

https://gitlab.kitware.com/vtk/vtk/uploads/99926ecad9ce008bcc7e2b1b7ca57784/vtk_bezier_cells_v2.pdf
![image](https://user-images.githubusercontent.com/868479/76694979-03be5700-663f-11ea-9496-6a9722e72a48.png)

**Comment by pazner** [comment]
Currently, Bezier output in the ParaView format is not supported. Right now, ParaView output of a NURBS mesh in MFEM will use Lagrange elements.

This could be an interesting feature to add. It would be helpful to have some example files and more complete format documentation (I guess that will come with time, since this feature is brand new in ParaView...)

**Comment by tzanio** [comment]
I haven't looked carefully yet -- is this more about supporting NURBS meshes, see e.g. the [MFEM NURBS mesh format](https://mfem.org/mesh-formats/#nurbs-meshes), or is it about representing the mesh nodes in the [positive Bernstein basis](https://github.com/mfem/mfem/blob/d9c4909da3766e49e66187ee063b8504e9d5138b/fem/fe.hpp#L35)?

**Comment by pazner** [comment]
My understanding was that this is about supporting NURBS meshes.

**Comment by GregVernon** [comment]
>  is this more about supporting NURBS meshes or is it about representing the mesh nodes in the positive Bernstein basis?

@tzanio I believe the new addition to VTK / ParaView requires a NURBS result to have its (non)rational Bezier components extracted and each Bezier cell described via Bernstein basis.

In general my question was related to the support of high-order MFEM IGA results in ParaView.  Whether they were supported at all (which it sounds like they do, via approximation as Lagrange elements), and whether it would make sense to use the new Bezier cell definition to represent the results.

**Comment by tzanio** [comment]
Discussion continued offline
