### ISSUE TITLE
How to compute nodal finite-element (Tetrahedron) matrix by myself, rather than use the BilinearForm?

### ISSUE THREAD

**Issue by yaohongbo-geophysics** [mfem/mfem#1358]
Hi, Dear Jed @jedbrown and other developers:
    I recently started learning mfem and I have to say that it's an excellent tool! But I'd like to compute element matrix integration (Tetrahedron) by myself, rather than use the BilinearForm. The integral form is: \iiint_{\Omega} N_i N_j dv, where N is the scalar(nodal) shape function of a  Tetrahedron. I have tried the following codes:

` FiniteElementCollection* fec = new H1_FECollection(order, dim);
   FiniteElementSpace* fespace = new FiniteElementSpace(mesh, fec, vdim);
   for (int e=0; e<fespace->GetNE(); ++e) {
      const FiniteElement* fe = fespace->GetFE(e);
      const IntegrationRule& ir = fe->GetNodes();
      ElementTransformation* eltrans = fespace->GetElementTransformation(e);

      DenseMatrix N_N(4, 4);
      for (int q=0; q<ir.GetNPoints(); ++q) {
         const IntegrationPoint& ip = ir.IntPoint(q);
         eltrans->SetIntPoint(&ip);

         Vector N(4); // shape functions of a scalar finite element, 4
         fe->CalcPhysShape(*eltrans, N);

         for (int i=0; i<4; ++i) {
			   for (int j=0; j<4; ++j) {
               N_N(i,j) += N(i)*N(j);     // I'm confused with this place
            }
         }
      }
   `

I'm really not sure how to do the integral sum, so can you give me some suggestions using some easy ways? 

Best wishes,
Hongbo

**Comment by mlstowell** [comment]
Hello, @yaohongbo-geophysics ,

Probably the best place to start is to look at our `MassIntegrator`: https://github.com/mfem/mfem/blob/506d975c37bfe868de97a918b5ee37d5527ca2d7/fem/bilininteg.cpp#L786
This does precisely what you are trying to accomplish.  There are only a few small differences separating the way we do it from the way you have implemented it.  First, you're using the interpolation points (by calling `fe->GetNodes()`) rather than an integration rule.  This is done sometimes and I believe it's called "mass lumping" but it leads to a less accurate integration.  Next, you call `fe->CalcPhysShape(*eltrans, N)` where we call `fe->CalcShape(*eltrans, N)`.  For H1 basis functions these will return the same results.  Finally, when performing the sum you need to account for the integration weights and the determinant of the Jacobian of the coordinate transformation.  If you use an integration rule it will specify the appropriate weights, if you really want to stick with the interpolation points you probably want the weights to be 1/num_points.  The Jacobian determinant is obtained using `eltrans->Weight()`.

If you need any further clarification, we'd be happy to explain the specifics in more detail.

Best wishes,
Mark

**Comment by yaohongbo-geophysics** [comment]
> Hello, @yaohongbo-geophysics ,
> 
> Probably the best place to start is to look at our `MassIntegrator`:
> 
> https://github.com/mfem/mfem/blob/506d975c37bfe868de97a918b5ee37d5527ca2d7/fem/bilininteg.cpp#L786
> 
> 
> This does precisely what you are trying to accomplish. There are only a few small differences separating the way we do it from the way you have implemented it. First, you're using the interpolation points (by calling `fe->GetNodes()`) rather than an integration rule. This is done sometimes and I believe it's called "mass lumping" but it leads to a less accurate integration. Next, you call `fe->CalcPhysShape(*eltrans, N)` where we call `fe->CalcShape(*eltrans, N)`. For H1 basis functions these will return the same results. Finally, when performing the sum you need to account for the integration weights and the determinant of the Jacobian of the coordinate transformation. If you use an integration rule it will specify the appropriate weights, if you really want to stick with the interpolation points you probably want the weights to be 1/num_points. The Jacobian determinant is obtained using `eltrans->Weight()`.
> If you need any further clarification, we'd be happy to explain the specifics in more detail.
> 
> Best wishes,
> Mark

Hi Mark, Thank you for the explanation, It will be useful! I will think more later!
Have a nice day!
Best wishes, 
Hongbo

**Comment by tzanio** [comment]
@uvilla, do you mind sharing your simple code for direct assembly here?

**Comment by yaohongbo-geophysics** [comment]
Hi, @mlstowell :
Following your advices, I did some tries as the codes (there still exists several problems):
`// Way 1: using IntegrationPoint
for (int e=0; e<fespace->GetNE(); ++e) {
   const FiniteElement* fe = fespace->GetFE(e);
   ElementTransformation* eltrans = fespace->GetElementTransformation(e);
   const IntegrationRule& ir = fe->GetNodes();

   int nd = fe->GetDof();
   Vector N(nd);
   DenseMatrix N_N(nd, nd);
   for (int q=0; q<ir.GetNPoints(); ++q) {
      const IntegrationPoint& ip = ir.IntPoint(q);
      fe->CalcShape(ip, N);

      eltrans->SetIntPoint(&ip);
      double ipw = 1.0/ir.GetNPoints();
      double w = eltrans->Weight()*ipw;

      for (int i=0; i<4; ++i) {
         for (int j=0; j<4; ++j) {
            N_N(i,j) += w*N(i)*N(j);
         }
      }

   }

   if(e==1) N_N.Print();   // show the results
   // The right solution should be (which has been verified in my hand-code):
   // 1.19121e+17	0	0	0	
   // 0	1.19121e+17	0	0	
   // 0	0	1.19121e+17	0	
   // 0	0	0	1.19121e+17

   // but this way's result is
   // +7.147266e+17 +0.000000e+00 +0.000000e+00 +0.000000e+00
   // +0.000000e+00 +7.147266e+17 +0.000000e+00 +0.000000e+00
   // +0.000000e+00 +0.000000e+00 +7.147266e+17 +0.000000e+00
   // +0.000000e+00 +0.000000e+00 +0.000000e+00 +7.147266e+17

   // as you said, since the weight of ip is not accurate, the result is not very good

}


// Way 2: Using IntegrationRule
for (int e=0; e<fespace->GetNE(); ++e) {
   const FiniteElement* fe = fespace->GetFE(e);
   ElementTransformation* eltrans = fespace->GetElementTransformation(e);

   // In line 800 of bilininteg.cpp, I'm confused about 'IntRule', I cannot find the definition of it 
   // const IntegrationRule *ir = IntRule ? IntRule : &GetRule(fe, fe, eltrans);
   // so I tried the follwing codes:
   const int order = fe->GetOrder() + fe->GetOrder() + eltrans->OrderW();
   const IntegrationRule ir = IntRules.Get(fe->GetGeomType(), order);

   Vector N(fe->GetDof()); 
   DenseMatrix N_N(4, 4);
   for (int q=0; q<ir.GetNPoints(); ++q) {
      const IntegrationPoint& ip = ir.IntPoint(q);
      fe->CalcShape(ip, N);

      eltrans->SetIntPoint(&ip);
      double ipw = ip.weight;
      double w = eltrans->Weight()*ipw;
      for (int i=0; i<4; ++i) {
         for (int j=0; j<4; ++j) {
            N_N(i,j) += w*N(i)*N(j);
         }
      }
   }

   if(e==1) N_N.Print();
   // but this way's result is
   // +4.764844e+16 +2.382422e+16 +2.382422e+16 +2.382422e+16
   // +2.382422e+16 +4.764844e+16 +2.382422e+16 +2.382422e+16
   // +2.382422e+16 +2.382422e+16 +4.764844e+16 +2.382422e+16
   // +2.382422e+16 +2.382422e+16 +2.382422e+16 +4.764844e+16
   // which is not right (the components are non-zero only in diagonal)
}

`

Last, I have read your project's paper (MFEM: A MODULAR FINITE ELEMENT METHODS LIBRARY
) and several Integrator code such as 'void DiffusionIntegrator::AssembleElementMatrix' in line 475 of bilininteg.cpp, I noticed that the tansform ways are different (not all are double w = eltrans->Weight()*ipw;), I'm not feel very clear about the map type (section 4.1 of the paper), so maybe I'm not sure how to choose approporiate Transformation weight when I change to another problems.

Thank you for your patience!

Have a nice day!
Hongbo

**Comment by yaohongbo-geophysics** [comment]
Hi @mlstowell ,
Following your advices and I made some effort to read and understand the source code of BilinearFormIntegrator and LinearFormIntegrator, I think the problem has been solved! Here is my code, just in case someone may meets the same problem.
`for (int e=0; e<fespace->GetNE(); ++e) {
      const FiniteElement* fe = fespace->GetFE(e);
      ElementTransformation* eltrans = fespace->GetElementTransformation(e);

      int nd = fe->GetDof();
      Vector shape(nd);
      DenseMatrix elmat(nd, nd); elmat = 0.0;

      const IntegrationRule* ir = &IntRules.Get(fe->GetGeomType(), 2*fe->GetOrder());
      for (int q=0; q<ir->GetNPoints(); ++q) {
         const IntegrationPoint& ip = ir->IntPoint(q);
         fe->CalcShape(ip, shape);
         
         eltrans->SetIntPoint(&ip);
         double w = eltrans->Weight()*ip.weight;

         for (int i=0; i<nd; ++i) {
            for (int j=0; j<nd; ++j) {
               elmat(i,j) += w*shape(i)*shape(j);
            }
         }
      }
   }`

And again, thank you for your help!
Best wishes,
Hongbo

**Comment by uvilla** [comment]
@yaohongbo-geophysics ,

I'm happy to hear you were able to debug your code.

I am also working with finite element assembly of functionals and their variations in MFEM.

In particular, I created a branch `adla-dev` (https://github.com/uvilla/mfem/tree/adla-dev), where I  can experiment with finite element assembly from scratch.

The example `mfem_poisson.cpp` (https://github.com/uvilla/mfem/blob/adla-dev/miniapps/adla/mfem_poisson.cpp) consider a functional related to a diffusion operator with lognormal diffusivity.

[TestCase.pptx](https://github.com/mfem/mfem/files/4350057/TestCase.pptx)

Hope this helps.

**Comment by tzanio** [comment]
Thanks @uvilla!

**Comment by yaohongbo-geophysics** [comment]
@uvilla ,Thanks for your work! It can actually help me understand the assembly process better！
