### ISSUE TITLE
Boundary integrator, boundary face integrator

### ISSUE THREAD

**Issue by fanronghong** [mfem/mfem#1359]
Hi all,

I've been always confusing about the difference between `AddBoundaryIntegrator` and `AddBdrFaceIntegrator` that both are member functions of class `BilinearForm`. Are they both OK for computing $\int_{\partial\Omega} u v dx$ ?

Thanks in advance!

**Comment by tzanio** [comment]
For  $\int_{\partial\Omega} u v dx$ you want `AddBoundaryIntegrator`.

The `AddBdrFaceIntegrator` is for DG methods where computation on the face requires access to the two elements that contain that face.

**Comment by fanronghong** [comment]
Thanks for your reply @tzanio ,

For DG methods, is it right that `AddBdrFaceIntegrator` is for boundary faces and `AddInteriorFaceIntegrator` is for interior faces?

If it's right, then `AddBoundaryIntegrator` is also for boundary faces, so what's the difference with `AddBdrFaceIntegrator`?

**Comment by tzanio** [comment]
The difference is that the `AddBoundaryIntegrator` requires information only on the face, while `AddBdrFaceIntegrator` requires information also from the element containing the face, see e.g. `DGTraceIntegrator`

**Comment by fanronghong** [comment]
Thanks @tzanio , I understand it.
