### ISSUE TITLE
Missing ParGridFunction in a ParMesh constructor

### ISSUE THREAD

**Issue by kennyweiss** [mfem/mfem#1361]
I am using the ``ParMesh`` constructor that creates a refined mesh for an LOR <--> HO reconstruction application that uses mfem's ``GridTransfer`` class. This class requires the domain and range FES to either both be serial or both be parallel.

The constructor that creates a refined mesh does not set a ``ParGridFunction`` for the nodes, and ``ParMesh`` does not expose a utility function to set a ``ParFiniteElementSpace`` for the nodes (e.g. ``ParMesh`` versions of ``Mesh::EnsureNodes()``, ~~``Mesh::SetCurvature()``~~).

This issue was not a blocker for me, but it was (from my perspective) unexpected.
I was able to work around this as follows:
```cpp
// ensure that nodes have a ParGridFunction / ParFiniteElementSpace
{
   auto* pfes = ...
   auto* pNodes = new mfem::ParGridFunction(pfes);
   lor_mesh->NewNodes(*pNodes, true);
   *pNodes = 0.;  // geometry is projected in a separate function
}
```

@tzanio suggested that:
> We should probably add something like https://github.com/mfem/mfem/blob/master/mesh/pmesh.cpp#L241 in that constructor.

Links: 
* ``GridTransfer`` class -- https://github.com/mfem/mfem/blob/b584a1a82dc17a0e46b5e3c760f8edcb3107ab8d/fem/fespace.hpp#L715
* ``ParMesh`` constructor -- https://github.com/mfem/mfem/blob/b584a1a82dc17a0e46b5e3c760f8edcb3107ab8d/mesh/pmesh.hpp#L224

**Correction:** ``ParMesh::SetCurvature`` does exist. I crossed it out from my comment above.

**Comment by pazner** [comment]
@kennyweiss can you check if the change in [this branch](/mfem/mfem/tree/lor-pargridfunction) does what you need?

**Comment by kennyweiss** [comment]
Thanks @pazner -- that worked!

Also, it looks like I missed ``ParMesh::SetCurvature``.

**Comment by pazner** [comment]
`ParMesh::SetCurvature` was only added very recently. This seems like a very reasonable change to make (it makes sense for the nodes of a `ParMesh` to be a `ParGridFunction`). What do you think, @tzanio?

**Comment by tzanio** [comment]
Yes, I agree, this is a nice fix. Shouldn't the second argument be `false`?

**Comment by pazner** [comment]
It is `true` to support periodic meshes (in the serial version since PR #1156, addressing issue #1067).

An alternative would be to set this to be true only if the nodes of the original mesh are discontinuous.

**Comment by tzanio** [comment]
> An alternative would be to set this to be true only if the nodes of the original mesh are discontinuous.

I think this will be better, because unless the mesh is periodic the L2 nodes will store much more than necessary. We already have checks like that, e.g. in https://github.com/mfem/mfem/blob/master/fem/fespace.cpp#L836.

**Comment by v-dobrev** [comment]
> **Correction:** `ParMesh::SetCurvature` does exist. I crossed it out from my comment above.

Actually `Mesh::EnsureNodes()` also should work fine for both serial and parallel meshes because it calls the (now virtual) method `SetCurvature()`.

**Comment by pazner** [comment]
> > **Correction:** `ParMesh::SetCurvature` does exist. I crossed it out from my comment above.
> 
> Actually `Mesh::EnsureNodes()` also should work fine for both serial and parallel meshes because it calls the (now virtual) method `SetCurvature()`.

The problem in this particular case is that the nodes already existed (as a `GridFunction` rather than `ParGridFunction`), so `EnsureNodes()` would be a no-op.

**Comment by v-dobrev** [comment]
My point was that calling `EnsureNodes()` should work fine with both serial and parallel meshes. If a parallel mesh has `GridFunction` as its nodes before that, the problem (if that is a problem) is elsewhere.

Using a `GridFunction` for the nodes of a `ParMesh` is fine in many cases. In some places in the code, where we **need** to have `ParGridFunction` for the nodes, we explicitly check for that, e.g. in `ParMesh::GetFaceNbrElementTransformation`.

@kennyweiss, where in the `GridTransfer` code did you encounter this issue? Maybe we can add a check for `ParGridFunction` there as well.

**Comment by kennyweiss** [comment]
@v-dobrev -- this is where the error was tripped:
https://github.com/mfem/mfem/blob/b584a1a82dc17a0e46b5e3c760f8edcb3107ab8d/fem/fespace.cpp#L2365-L2371

**Comment by v-dobrev** [comment]
OK, there is already a check there.

**Comment by kennyweiss** [comment]
@v-dobrev -- I am on a recent mfem  (https://github.com/mfem/mfem/tree/8dbbcfc25629ac7612fe31afd5b511752ff0e69b).

I just checked and the following **does not** work for me:
```cpp
   lor_mesh     = new mfem::ParMesh(hydro_mesh, lor_factor, lor_type);
   lor_fes_coll = new FESpaceCollection(*lor_mesh, dg_basis_type);

   lor_mesh->EnsureNodes();
```

But the following **does** work:
```cpp
   lor_mesh     = new mfem::ParMesh(hydro_mesh, lor_factor, lor_type);
   lor_fes_coll = new FESpaceCollection(*lor_mesh, dg_basis_type);

   lor_mesh->SetCurvature(1,true, space_dim);
```

**Comment by v-dobrev** [comment]
@kennyweiss, yes, this is the case that @pazner mentioned -- `lor_mesh` already has `GridFunction` nodes, so `EnsureNodes` will be no-op (the nodes are already defined). On the other hand, `SetCurvature` will replace the nodes with a new `ParGridFunction` even if the nodes are already defined.

I guess when I said "`EnsureNodes` works in parallel", I meant "works as intended". 😄  In particular, it is no-op when the nodes are defined.

**Comment by kennyweiss** [comment]
Thanks for the explanation @v-dobrev -- that makes sense.
