### ISSUE TITLE
Discontinuous Galerkin with findpts (in GSLIB) ?

### ISSUE THREAD

**Issue by LeilaSalomon** [mfem/mfem#1371]
Hello, 

From what I understand, findpts.cpp is not compatible with a discretisation DG, is it true?

Best,

Leïla

**Comment by jandrej** [comment]
What you can do is to project your solution to an H1 space and then use findpts for your computations. The H1 space can be higher order than the DG space to ensure a more resolved transition in certain regions.

**Comment by kmittal2** [comment]
@LeilaSalomon, can we close this issue?

**Comment by LeilaSalomon** [comment]
> What you can do is to project your solution to an H1 space and then use findpts for your computations. The H1 space can be higher order than the DG space to ensure a more resolved transition in certain regions.

How can I project my solution? Just by creating a second space?

**Comment by kmittal2** [comment]
You can use [ProjectDiscCoefficient](https://github.com/mfem/mfem/blob/master/fem/gridfunc.hpp#L254) to project your DG gridfunction to H1. Something like this will work:

`H1_FECollection *fec=new H1_FECollection(order, dim); `
`FiniteElementSpace *fespace=new FiniteElementSpace(mesh, fec);`
`GridFunction h1_gf(fespace);`
`GridFunctionCoefficient cdg(dg_gf);`
`h1_gf.ProjectDiscCoefficient(cdg, mfem::GridFunction::ARITHMETIC);`

where `dg_gf` is your DG gridfunction.

**Comment by LeilaSalomon** [comment]
> You can use [ProjectDiscCoefficient](https://github.com/mfem/mfem/blob/master/fem/gridfunc.hpp#L254) to project your DG gridfunction to H1. Something like this will work:
> 
> `H1_FECollection *fec=new H1_FECollection(order, dim); `
> `FiniteElementSpace *fespace=new FiniteElementSpace(mesh, fec);`
> `GridFunction h1_gf(fespace);`
> `GridFunctionCoefficient cdg(dg_gf);`
> `h1_gf.ProjectDiscCoefficient(cdg, mfem::GridFunction::ARITHMETIC);`
> 
> where `dg_gf` is your DG gridfunction.

Hello,

Thank you for your help but I have an error when I use GridFunctionCoefficient cdg(dg_gf). 

I think I'm not declare it well !  I tried using GridFunctionCoefficient cdg(dg_gf,1) but it doesn't work either...

**Comment by v-dobrev** [comment]
The argument to the `GridFunctionCoefficient` constructor should be a pointer to `GridFunction`:
https://github.com/mfem/mfem/blob/491e65388ba31eedb6bacec926bb04186c65f65e/fem/coefficient.hpp#L174-L175

 so maybe you need to use `&dg_gf` instead of `dg_gf`.

**Comment by tzanio** [comment]
@LeilaSalomon and @kmittal2, can you update us on this issue?

**Comment by kmittal2** [comment]
@LeilaSalomon had mentioned in her email that she will continue the discussion here.

**Comment by LeilaSalomon** [comment]
When I use ProjectDiscCoefficient, in fact, I solve again the solution in this new space : I get a solution in space h1, which is not the same as in space DG. Only, I'm just interested by the results obtained by the resolution in the DG space, because this is the one I use for my simulation
 
Leïla

**Comment by tzanio** [comment]
Ok, I believe I understand now, but just as in https://github.com/mfem/mfem/issues/1331#issuecomment-616683881, we don't have support for L2 spaces with `FindPoints` yet.

**Comment by tzanio** [comment]
I am closing this for now, but we have taken note and plan to add support for non-H1 spaces to findpts in the future.
