### ISSUE TITLE
Negative element transformation jacobian while using `ParPumiMesh`

### ISSUE THREAD

**Issue by geyan3566** [mfem/mfem#1373]
Hi,

I tried to load a `pumi` mesh  and convert it into a parallel `mfem` mesh with:
```
pumi_mesh = apf::loadMdsMesh(model_file.c_str(), mesh_file.c_str());
mfem_mesh = ParPumiMesh(MPI_COMM_WORLD, pumi_mesh);
```
But all the elements in `mfem_mesh` have element transformation of negative jacobian.
Is there a way to check the mesh orientation while loading MDS mesh?  It happened to me that pumi warned me about wrong orientation elements and fixed it.

Here are the model file and the mesh file.
[model_mesh.zip](https://github.com/mfem/mfem/files/4377727/model_mesh.zip)

I'm running it parallel with only 1 processor here.
Code that loads the mesh:
```
      PCU_Comm_Init();
#ifdef MFEM_USE_SIMMETRIX
      Sim_readLicenseFile(0);
      gmi_sim_start();
      gmi_register_sim();
#endif
      gmi_register_mesh();
      pumi_mesh = apf::loadMdsMesh(model_file.c_str(), mesh_file.c_str());
      pumi_mesh->verify();
      /// convert this apf mesh to mfem mesh
      mesh.reset(new ParPumiMesh(comm, pumi_mesh));
      PCU_Comm_Free();
#ifdef MFEM_USE_SIMMETRIX
      gmi_sim_stop();
      Sim_unregisterAllKeys();
#endif
```
Code that check the jacobian:
```
      ElementTransformation *T;
      for (int i = 0; i < fes->GetNE(); i++)
      {
         T = fes->GetElementTransformation(i);
         std::cout << "element " << i << ": T-Weight is " << T->Weight() << '\n';
      }
```

Thanks,
Ge

**Comment by tzanio** [comment]
@MarkShephard, can someone at RPI take a look at this?

**Comment by cwsmith** [comment]
looks like a cross/double post https://github.com/SCOREC/core/issues/297

**Comment by tzanio** [comment]
The SCOREC/core#297 is a better place to discuss this...
