### ISSUE TITLE
LOR for tet meshes

### ISSUE THREAD

**Issue by mclarsen** [mfem/mfem#1382]
I was trying to do a low-order refine of a tet mesh and encountered and abort:

```
MFEM abort: Geometry type Tetrahedron is not implemented
 ... in function: const int *mfem::H1_FECollection::GetDofMap(mfem::Geometry::Type) const
 ... in file: /mfem-8dbbcfc/fem/fe_coll.cpp:1770
```

This is a feature request to implement this capability.

**Comment by v-dobrev** [comment]
Yes, LOR is not implemented for tet meshes yet.

I think @pazner may have something like this implemented in branch -- I remember we had a related discussion about tets at some point but I'm not sure it was specifically for LOR.

I think the main missing part is the function where you got the error and that is not too hard to implement.

**Comment by pazner** [comment]
I agree this would be a great feature to have.

I haven't implemented anything like this, but I do have an interest in generating simplicial LOR meshes from tensor-product meshes to use for preconditioning.

**Comment by tzanio** [comment]
This was recorded as a desirable feature and we will consider implementing it in the near future.
