### ISSUE TITLE
Tracing mfem verification

### ISSUE THREAD

**Issue by ben-s-southworth** [mfem/mfem#1384]
Is there a simple way to trace MFEM verification problems? E.g., I get an error along the lines of 
```
Verification failed: (op(i,j)) is false:
 --> 
 ... in function: mfem::Operator& mfem::BlockOperator::GetBlock(int, int)
 ... in file: /g/g19/bs/Plasma/mhd-mfem/local/include/mfem/linalg/blockoperator.hpp:78
```
but it's not clear where in my source code this actually arises if I am calling GetBlock() in many locations. I have compiled in debug and tried valgrind as well, but neither provide a more detailed trace.

**Comment by pazner** [comment]
You can set a breakpoint e.g. at `error.cpp:155` and then run in the debugger. It should hit the breakpoint right before aborting, and then you can get a backtrace.

**Comment by tzanio** [comment]
What @pazner said ☝️

Set a breakpoint in `mfem_error`.
