### ISSUE TITLE
Material Modeling

### ISSUE THREAD

**Issue by samanseifi** [mfem/mfem#1385]
So ultimately I am interested in modeling electro-elasticity problems using mfem capabilities. I used to implement these in Tahoe (http://tahoe.sourceforge.net/), great platform for material models. But I want to make a switch to mfem. As I can see, there is a neo-Hookean model in the mfem, but I'm interested in coding Arruda-Boyce or Gent models. Is there anyway perhaps to override a general nonlinear material models? My secondary interest is to implement various hyperelastic models for mfem.

**Comment by rcarson3** [comment]
@samanseifi yes you can easily derive / create new nonlinear material models. Here are two different applications that use MFEM that do so [ExaConstit ](https://github.com/LLNL/ExaConstit) and [Serac](https://github.com/LLNL/serac). Within ExaConstit, we've got a few examples of this [UMAT class](https://github.com/LLNL/ExaConstit/blob/exaconstit-dev/src/mechanics_umat.hpp) and [crystal plasticity class](https://github.com/LLNL/ExaConstit/blob/exaconstit-dev/src/mechanics_ecmech.hpp). These classes share a common base class which is then used within our ```NonlinearFormIntegrator``` [derived class](https://github.com/LLNL/ExaConstit/blob/exaconstit-dev/src/mechanics_integrators.hpp#L275-L315) which allows us to solve our system. I'm not as familiar with Serac but @jamiebramwell could probably speak a bit more about how they handle such things in their code base.

**Comment by samanseifi** [comment]
These are really great works and very similar to what I had in mind. Serac only supports 3D, how about ExaConstit? Is there any plane-strain formulation?

I'm curious to know what type of benchmark you ran on these? Verification simulations, tensile test maybe?

**Comment by jamiebramwell** [comment]
@samanseifi Serac is a very new project. Although we mostly run 3D problems, it should be fully compatible with 2D meshes. One of our goals for this summer is to write a validation suite based on the [Abaqus benchmark guide](http://dsk.ippt.pan.pl/docs/abaqus/v6.13/books/bmk/default.htm). ExaConstit is a much more developed project, so @rcarson3 probably has more to offer on that front.

**Comment by rcarson3** [comment]
ExaConstit currently only supports 3D. Later down the road, we might add 2D support, but we would still require our constitutive models to be run fully within 3D.

Verification of ExaConstit of the UMAT part of the code was originally done by comparing the stress output of a linear elastic and neo-hookean material vs the analytical solution. The crystal plasticity code has been compared against other code-bases that use the same constitutive models for simple tension tests.

Outside of the initial verification, I only have a few small test problems that are run to make sure our results don't change when new formulations are added. I definitely need to add more unit tests here as well, but I've been primarily up till now focused on building capabilities and getting a GPU formulation for it put together.

@samanseifi  it sounds like you're interested in multi-physics type problems which is outside of the scope of ```ExaConstit```. So, ```Serac``` as it matures might ultimately be of more interest to you as a useful tool to use.

**Comment by samanseifi** [comment]
@jamiebramwell that's great. Like @rcarson3 mentioned I'm more interested in multi-physics type problem and right now much like thermo-elasticity they are "same domain" coupling so `serac` seems to be the tool. 

Thanks guys. I'll get back with more questions soon :)

**Comment by jamiebramwell** [comment]
@samanseifi Great! My first multiphysics application will be thermo-plasticity, but I expect to add EM and generic advection/reaction/diffusion soon!
