### ISSUE TITLE
Shared build of mfem on Windows

### ISSUE THREAD

**Issue by kennyweiss** [mfem/mfem#1396]
Is ``mfem`` interested in being able to build as a shared library (i.e. a ``dll``) on Windows/``msvc``?

The [axom](https://github.com/LLNL/axom) project has been working on automating its Windows build, which requires building its third-party libraries, including ``mfem``, in shared mode.

#### Details:

One of the main differences between ``gcc``/``clang`` and ``msvc`` in their treatment of shared libraries has to do with how symbols are exported.  ``gcc``/``clang`` export all symbols by default, while ``msvc`` exports none of the symbols by default.

The CMake flag -- [WINDOWS_EXPORT_ALL_SYMBOLS](https://cmake.org/cmake/help/latest/prop_tgt/WINDOWS_EXPORT_ALL_SYMBOLS.html) -- gets you most of the way there, but it does not export symbols for global variables, e.g. ``extern`` variables or ``static const`` class members.
I think this flag is available in ``CMake@3.7+``

I've developed a partial solution for this in https://github.com/LLNL/axom/pull/213 in the form of a patch to get ``mfem@4.0`` to link to axom (see https://github.com/LLNL/axom/blob/aaac337f2e6d3168d550c92094d633fc9864cb9b/scripts/uberenv/vcpkg_ports/mfem/export-extern-vars.patch ).  This solution requires very few changes to ``mfem``. I think this only covers the symbols that are currently used by ``axom``, and I haven't tried building ``mfem``'s examples or tests, so there is likely more work to be done.

My understanding is that shared mode is also required for Python support, so this might have relevance to a Windows build of https://github.com/mfem/PyMFEM, or it might already be a solved issue (?)

**Comment by tzanio** [comment]
I believe @acfisher and maybe @v-dobrev have some experience with this.

**Comment by v-dobrev** [comment]
I've never tried this -- configuring cmake with `-DBUILD_SHARED_LIBS=ON` on windows with msvc. Also, I don't remember any issues on github about that.

@kennyweiss, if you want we can make a PR with the changes you have in the patch and do some testing. Maybe we can setup an appveyor test for a shared build?

**Comment by acfisher** [comment]
I haven't tried it with msvc, but I've built DLLs on intel/windows using both cmake and a hand rolled nmake file.  I had to do some contortions to get the nmake solution to work.  It's probably worth having a look at your changes to see if we can generalize it and test it like @v-dobrev  suggested.

**Comment by kennyweiss** [comment]
Thanks @v-dobrev  and @acfisher.

I created #1401 which builds and links the ``exec`` target and passes all tests locally.  I was able to build and test locally on linux, but ran into an issue with the ``travis`` job related to the new auto-generated file `mfem_export.h`

**Comment by tzanio** [comment]
@kennyweiss, do you want us to merge #1401? If so, can you mark it with the `ready-for-review` label?

**Comment by kennyweiss** [comment]
@tzanio -- I ran into a problem testing this on windows through azure in early April, and unfortunately haven't had a chance to get back to it.

It worked with the current azure script in mfem@master (using static builds on Windows), but had errors when I tried to add a shared library build to the CI.  Maybe I was doing something wrong in the CI script?
https://github.com/mfem/mfem/pull/1401/files#diff-11c909939117928998b102a1fff7d363R40-R55

The shared windows build worked for me on my local system. 
Perhaps someone else with a windows machine can try to build this?

**Comment by tzanio** [comment]
@acfisher, can you give ☝️ a try by any chance on your Windows machine?

**Comment by tzanio** [comment]
ping: @acfisher

**Comment by acfisher** [comment]
Yeah, I'll give it a spin.
