### ISSUE TITLE
Displacement boundary conditions on linear elastic model (ex2)

### ISSUE THREAD

**Issue by rajpradi** [mfem/mfem#1399]
Hello Developers,

First of all, thank you very much for creating such an efficient FEA library.

I am facing difficulties while applying displacement boundary condition on required faces/nodes. 
(Displacement BC means, initially assigning some fixed non-zero values for Ux or Uy). 
Currently, I am trying to use ex2 (linear elastic model). I have directly tried to impose some values to the GridFunction 'x' to give initial displacement before PCG solver step, but it doesn't give correct results. I want to use H1- nodal elements that is why I chose ex2 over ex17.

Later, I also tried using ex17 (linear elastic - discontinuous Galerkin) to understand the process of implementation of different Dirichlet boundary condition which ex17 has implemented using InitialDisplacement function. But still I did not get clear, how you have implemented displacement BC and how can we used same technique for H1-nodal elements (for example, how can we use it in ex2)?

**Thus, my main question is how can we apply the displacement boundary condition in ex2 (linear elastic model)?**

Just to give you an idea about my work, I am creating Topology Optimization pipeline and in that I need to implement two types of Dirichlet BC's - i) fixed BC on one side and ii) displacement BC on the other side to perform compression, tension and shear.

I am very much thankful to your help.

Best Regards, 
Raj

**Comment by mlstowell** [comment]
Hello, @rajpradi ,

It sounds like `ex2` was the correct choice.  Applying Dirichlet BCs in this problem involves two pieces of information. First you need the boundary values themselves and it sounds like you have this piece.  The second piece is the portion of the boundary on which to apply those values.  Perhaps this second piece is missing.  In example 2, this piece is defined in the following lines:
```
   Array<int> ess_tdof_list, ess_bdr(mesh->bdr_attributes.Max());
   ess_bdr = 0;
   ess_bdr[0] = 1;
   fespace->GetEssentialTrueDofs(ess_bdr, ess_tdof_list);
```
These lines activate the Dirichlet BC only on the boundary elements with attribute number equal to '1'.  The opposite end of the mesh in that example happens to have attribute number '2' so you would need to add `ess_bdr[1]=1;` to activate the other end (note that attribute numbers are 1-based but the indices into `ess_bdr` are 0-based so you need to use `ess_bdr[attr-1]=1;` to activate boundary elements with attribute number `attr`.) 

Best wishes,
Mark

**Comment by rajpradi** [comment]
Hello Mark,

Thank you very much for your prompt response. Now I got clear how to assign/add the portion of the of the boundary on which I will apply displacement boundary conditions. 

Sorry to disturb you once again, but I am not clear how can we add boundary values to it. For example, if I want to add any non-zero initial displacement (Dirichlet BC) to the faces of boundary elements with attribute '2', where should I add/give non-zero initial displacement value? Do I need to create separate vector and linked it with ess_tdof_list/GridFunction 'x'?

Once again thank you for taking your time.

Kind Regards,
Raj

**Comment by tzanio** [comment]
The boundary values are specified by the (ess_tdof_list) values of the grid function `x` in the call to `FormLinearSystem`.

**Comment by mlstowell** [comment]
Hi, @rajpradi ,

To expand on what @tzanio said, putting values into the `GridFunction` is done by creating a `VectorCoefficient` which reproduces the desired boundary values and projecting this onto `x` using `x.ProjectBdrCoefficient`.  You can find an example of this in `ex21`.  You can use a sequence of `VectorConstantCoefficients` on different portions of the boundary or you can write a single position dependent `VectorFunctionCoefficient` and apply it only once on the entire boundary.  Either choice should work fine.

Best wishes,
Mark

**Comment by rajpradi** [comment]
Thank you very much @tzanio and @mlstowell for your detailed explanation. I was able to implement the displacement boundary condition expectedly.

Kind Regards,
Raj

**Comment by rajpradi** [comment]
Hi Sir,

I am Sorry to bother you again.
Can you please tell me how can we apply displacement boundary condition (initial displacement) on a particular node instead of face boundary?

I want this to use in Topology Optimization code. Earlier, I asked you about displacement boundary condition on faces, but from that I could not figure it out out how can I implement on nodes.

I have tried with previously suggested technique, but it's giving me segmentation fault when I use x.ProjectCoefficient. Can you please suggest me where I am making mistake?

ess_tdof_list.Append(NodeNumber);

   Array<int> nodeDispX(int (1));
   nodeDispX[0] = NodeNumber;

disp_X_value[0] = 0.5; // Assigned values for disp. BC. in X direction.
   VectorConstantCoefficient disp_X_value_coeff(disp_X_value);

x.ProjectCoefficient(disp_X_value_coeff,nodeDispX);

Thank you vary much for your time.

Sincerely,
Raj Khawale.

**Comment by mlstowell** [comment]
This project method requires that you first call `FiniteElementSpace::BuildDofToArrays()` for the finite element space in `x`.

**Comment by rajpradi** [comment]
Thank you very much Sir. It's working well. 

Sincerely,
Raj
