### ISSUE TITLE
Open results in VisIt

### ISSUE THREAD

**Issue by martemyev** [mfem/mfem#14]
Dear all,

I've got some issues trying to open results produced by MFEM in VisIt. For example, after running Example5 and trying to open the file Example5_000000.mfem_root, I've got the following:

>VisIt could not read from the file "/u/artemyev/software/mfem-3.0.1/examples/Example5_000000.mfem_root".
>The generated error message was:
>There was an error opening /u/artemyev/software/mfem-3.0.1/examples/Example5_000000.mfem_root. It may be an invalid file.
>VisIt tried using the following file format readers to open the file: Silo
>If you know the specific format reader VisIt should use to read this data, you can use Open As... (GUI) or '-o <file>,<plugin> (CL arg.) and identify that specific reader for VisIt to try. This will possibly give more information on the exact error.

MFEM results are represented not in Silo format, obviously. But I didn't find any JSON support (plugin) in VisIt (I tried version 2.9.2 on Linux Mint 64bit).

So, how should I do that?

Thank you,
Mikhail

**Comment by acfisher** [comment]
Hi Mikhail,

It looks like Visit is guessing that it is a Silo file.  If you select Open File from the File Menu, there should be an open file as type drop down menu.  You should be able to select MFEM in there which will fix your problem.

Cheers,
Aaron Fisher

**Comment by martemyev** [comment]
Hi Aaron,

Thank you for the reply. Actually, I have tried this approach, but I haven't found MFEM in the list of the supported types. I'm looking at the list right now, and there are M3DC1, M3D, MFIXCDF, MFIX, MM5, MatrixMarket and Miranda types started with 'M' (the list is ordered alphabetically). No MFEM, though.

Best,
Mikhail

**Comment by acfisher** [comment]
Hi Mikhail,

Hmm, can you doublecheck your version of Visit in the Help->About page?  I believe the MFEM support arrived at version 2.9, so it should be in there.

Cheers,
Aaron

**Comment by martemyev** [comment]
Aaron,

Yes, it is the version 2.9.2. But I finally found where I was wrong - I installed VisIt incorrectly: I just unpacked an archive which contained executable files, while I was supposed to run a special script for unpacking and installing, and that, turns out, is crucial.
Now, I see the MFEM file type in that list.
Thank you!
Best,
Mikhail

**Comment by acfisher** [comment]
Mikhail,

Ahh, good catch.  I'm glad it's working for you now.  Happy computing.

Cheers,
Aaron
