### ISSUE TITLE
How to use block matrix for a Jacobian in PETSc?

### ISSUE THREAD

**Issue by fanronghong** [mfem/mfem#1405]
Hi all,

I have a nonlinear operator `op`, which I will use in 
` PetscNonlinearSolver* pnewton_solver = new PetscNonlinearSolver(MPI_COMM_WORLD, *op);
`

The `op` will be used to compute Jacobian `op->GetGradient()` and compute Residual `op->Mult()`. 

Here the Jacobian is a BlockMatrix whose every sub-block is a `PetscParMatrix`, but in MFEM the sub-block must be `SparseMatrix`, not `PetscParMatrix`. 

So how to fix it?

**Comment by fanronghong** [comment]
Sorry, I want to add another question based on the above question.

In `example/petsc/ex10p.cpp`, there is a piece of code below. 
As you can see, when I solve Jacobi linear system `Jacobian * u = Residual` in every newton iteration, I can give any `IterativeSolver` for `newton_solver` by `newton_solver.SetSolver()`.
But how can I choose `PetscLinearSolver` for `pnewton_solver` ?
```
   if (!use_petsc)
   {
      HypreSmoother *J_hypreSmoother = new HypreSmoother;
      J_hypreSmoother->SetType(HypreSmoother::l1Jacobi);
      J_hypreSmoother->SetPositiveDiagonal(true);
      J_prec = J_hypreSmoother;

      MINRESSolver *J_minres = new MINRESSolver(f.GetComm());
      J_minres->SetRelTol(rel_tol);
      J_minres->SetAbsTol(0.0);
      J_minres->SetMaxIter(300);
      J_minres->SetPrintLevel(-1);
      J_minres->SetPreconditioner(*J_prec);
      J_solver = J_minres;

      newton_solver.iterative_mode = false; // newton_solver is an object of class NewtonSolver
      newton_solver.SetSolver(*J_solver);
      newton_solver.SetOperator(*reduced_oper);
      newton_solver.SetPrintLevel(1); // print Newton iterations
      newton_solver.SetRelTol(rel_tol);
      newton_solver.SetAbsTol(0.0);
      newton_solver.SetMaxIter(10);
   }
   else
   {
      // if using PETSc, we create the same solver (NEWTON+MINRES+Jacobi)
      // by command line options (see rc_ex10p)
      J_solver = NULL;
      J_prec = NULL;
      pnewton_solver = new PetscNonlinearSolver(f.GetComm(),
                                                *reduced_oper);
      pnewton_solver->SetPrintLevel(1); // print Newton iterations
      pnewton_solver->SetRelTol(rel_tol);
      pnewton_solver->SetAbsTol(0.0);
      pnewton_solver->SetMaxIter(10);
   }
```

**Comment by tzanio** [comment]
@stefanozampini or @jandrej, can you take a look at this?
