### ISSUE TITLE
KINSolver default settings problematic with linear or nearly-linear problems

### ISSUE THREAD

**Issue by jandrej** [mfem/mfem#1406]
The nonlinear solver from the Sundials library KINSol has the following default behavior:

KINSol limits the maximum Newton update if 
```
|| scale * update ||_2 > max(1000 * || scale * u0 ||_2, 1).
```
This forces KINSol to take more steps than necessary in the linear case.

Providing the option `KINSetMaxNewtonStep(kin_mem, max_step)` changes the default behavior to
```
|| scale * update ||_2 > max_step
```
This leaves the user with two options. The first and simple one, not using an initial guess that is zero (e.g. use a random initial guess). The second one is for us to expose `KINSetMaxNewtonStep` and document this behavior.

Either way, it should be documented.

**Comment by tzanio** [comment]
ping: @jandrej

**Comment by jandrej** [comment]
I'm still not sure what the best solution for this is right now as I don't completely understand why the automatically computed tolerance in `KINSolver::Mult(x, y)` doesn't mitigate the effect.

**Comment by tzanio** [comment]
Still an (unresolved) issue?

**Comment by jandrej** [comment]
This is a good case for "wont fix" since the purpose of the nonlinear solver is a nonlinear problem, not a linear equation. I think we should close it.
