### ISSUE TITLE
Segmentation error when trying to obtain PointMat from IsoparametricTransformation class

### ISSUE THREAD

**Issue by samadritakarmakar** [mfem/mfem#1407]
What I basically need is the nodal coordinates for each node of each element. I try to obtain the PointMat data from the IsoparametricTransformation class. The mesh type is Gmsh.
I try below code to obtain the same but receive a Segmentation fault when trying to do so using the below code.  ElementTransformation class does not give the same error.

```
for (int elmnt =0; elmnt<noOfElmnts; elmnt++)  
    {  
        const FiniteElement *el_dsp = fe_dsp->GetFE(elmnt);  
        //*******Some random code*********************  
        ElementTransformation *Trans=fe_dsp->GetElementTransformation(elmnt);  //No error for this line.  
        IsoparametricTransformation *IsoTransform;  
        fe_dsp->GetElementTransformation(elmnt, IsoTransform); //Segmentation error for this line.   
        DenseMatrix &PointMat=IsoTransform->GetPointMat();  
        //*******Some random code*********************  
}
```

Thank you in advance for your help.

**Comment by vladotomov** [comment]
Hi @samadritakarmakar, the input IsoparametricTransformation must be allocated by the user, see the comment in fespace.hpp:

```
   /** Returns the transformation defining the @a i-th element in the
       user-defined variable @a ElTr. */
   void GetElementTransformation(int i, IsoparametricTransformation *ElTr)
```

**Comment by samadritakarmakar** [comment]
Ok. Issue solved. Thanks a lot for your response.
