### ISSUE TITLE
Number of CG iterations in HypreSmoother

### ISSUE THREAD

**Issue by aschaf** [mfem/mfem#1408]
Hi,

can we add a way to set the number of CG iterations used in `HypreSmoother` to estimate the eigenvalues? E.g., change 
```
void SetPolyOptions(int poly_order, double poly_fraction);
```
to
```
void SetPolyOptions(int poly_order, double poly_fraction, double poly_cg_iterations = 10);
```
and if `poly_cg_iterations == 0`, then use hypre's `hypre_ParCSRMaxEigEstimate` to estimate the largest eigenvalue.

Best regards,
Andreas

**Comment by v-dobrev** [comment]
Sounds like a reasonable thing to add.

I didn't know about the hypre function `hypre_ParCSRMaxEigEstimate` -- maybe it can be useful for #1097 as well.

**Comment by tzanio** [comment]
This is fine with me too. Do you want to propose a PR?

**Comment by aschaf** [comment]
I will do it, yes.

**Comment by tzanio** [comment]
ping @aschaf

**Comment by tzanio** [comment]
Discussion continued in https://github.com/mfem/mfem/pull/1473
