### ISSUE TITLE
PA for simplex elements

### ISSUE THREAD

**Issue by tuckerbabcock** [mfem/mfem#1409]
Can meshes with simplex elements take advantage of partial assembly? Based on this line from the libCEED documentation on [partial assembly](https://libceed.readthedocs.io/en/latest/libCEEDapi/#partial-assembly):
> Critically for performance, we take advantage of the tensor-product structure of the degrees of freedom and quadrature points on _quad_ and _hex_ elements to perform the action of **B** without storing it as a matrix.

It seems to me like simplex elements could support partial assembly, but with less efficiency than tensor product elements since **B** would need to be stored as a matrix. However, the [README](https://github.com/CEED/Laghos) for the Laghos miniapp says
> triangular and tetrahedral elements can also be used, but with the less efficient full assembly option

Which sounds like it's not possible. I'd love to be able to take advantage of the GPU acceleration that has been added to MFEM, but I'm somewhat tied to simplex meshes. 

Thanks!

**Comment by YohannDudouit** [comment]
There is indeed no theoretical limitation to take advantage of partial assembly for simplices, depending on what problem you want to solve, libCEED integration in MFEM might already offer partial assembly support for your problem using simplices.
Because of the very significant performance gap between tensor and non-tensor elements, in MFEM we focused on supporting partial assembly for tensor elements first.
Therefore, MFEM does not currently support partial assembly for simplices, however we are planning to support non-tensor elements (without libCEED) in the future.

**Comment by tuckerbabcock** [comment]
@YohannDudouit I'm a bit confused by what you've said...
> libCEED integration in MFEM might already offer partial assembly support for your problem using simplices

seems to be contradicted by 
> MFEM does not currently support partial assembly for simplices

When you mention you're planning to support partial assembly for non-tensor elements without libCEED in the future, may I ask why without libCEED? Will their interface not support non-tensor elements?

I'd love to make contributions to speed the development of partial assembly for simplex elements, but I'm not sure exactly where the best place to make such contributions would be.

**Comment by rcarson3** [comment]
@tuckerbabcock if you really want to try and get your problem up on the GPU in the near future while the MFEM team is working on adding the non-tensor approach you could do something like what I did for my PA formulation in ```ExaConstit``` here: https://github.com/LLNL/ExaConstit/blob/exaconstit-dev/src/mechanics_integrators.cpp#L1235-L1675 

I wouldn't call it the most performant method, but it doesn't care about the element type, and you'll be able to get your problem up on the GPU. The relevant part is probably https://github.com/LLNL/ExaConstit/blob/exaconstit-dev/src/mechanics_integrators.cpp#L1414-L1427 where I physically store all the shape function gradients to be used within my partial assembly operations.

**Comment by YohannDudouit** [comment]
@tuckerbabcock libCEED is an optional dependency, libCEED supports non-tensor elements (simplices). If you use `MFEM_USE_CEED=YES` then you can have access to partial assembly on simplices for Mass and Diffusion operators, see [ex1](https://github.com/mfem/mfem/blob/master/examples/ex1.cpp). However, without this optional dependency there is no support in MFEM currently for partial assembly on simplices.
When I said MFEM plans on supporting non-tensor elements, this is in addition to the support for non-tensor elements provided by libCEED (i.e. directly in the MFEM library without any dependency).

Any contribution is welcomed, which Integrators are you planning to implement non-tensor partial assembly for?

**Comment by tuckerbabcock** [comment]
@rcarson3 thank you for those links, I'll take some time to digest them.

@YohannDudouit I see, thanks for the clarification.

I'm interested in trying to accelerate the `CurlCurlIntegrator`, `VectorFECurlIntegrator`, all of the components of the `DivergenceFreeProjector` from the elctromagnetics miniapp, which I believe includes the `VectorFEWeakDivergenceIntegrator` and`GradientInterpolator`, and a few nonlinear form integrators I've developed for my own code.

**Comment by YohannDudouit** [comment]
@tuckerbabcock I think that the `PACurlCurlSetup` functions in [bilininteg_hcurl.cpp](https://github.com/mfem/mfem/blob/master/fem/bilininteg_hcurl.cpp) can easily be adapted to work with non-tensor elements (it almost already does), the `PACurlCurlApply` functions can mostly be copy/pasted and then simplified to work for non-tensor elements.  You'll also have to detect in `AssemblePA` and `AddMultPA` if you have a tensor or non-tensor elements using the `UsesTensorBasis` function.
Similarly `PAHcurlMassSetup` and `PAHcurlMassApply` should require the exact same kind of changes.

**Comment by tzanio** [comment]
> I'd love to make contributions to speed the development of partial assembly for simplex elements, but I'm not sure exactly where the best place to make such contributions would be.

Thank you for your offer to help @tuckerbabcock. @YohannDudouit and @dylan-copeland are experts in these topics and I'm sure will be happy to help!

**Comment by tuckerbabcock** [comment]
While it shouldn't hinder my ability to work on implementing partial assembly for the integrators I mentioned, I'm also curious about solving/preconditioning when using partial assembly. Based on the parallel version of example 3, it seems like the Hypre solvers/preconditioners cannot yet be used when taking advantage of partial assembly. Is there a timeline for Hypre solver/preconditioner support?

**Comment by jandrej** [comment]
> While it shouldn't hinder my ability to work on implementing partial assembly for the integrators I mentioned, I'm also curious about solving/preconditioning when using partial assembly. Based on the parallel version of example 3, it seems like the Hypre solvers/preconditioners cannot yet be used when taking advantage of partial assembly. Is there a timeline for Hypre solver/preconditioner support?

This is an ongoing research topic. A majority of existing preconditioning concepts are based on the knowledge of an assembled matrix structure (e.g. classical AMG). There are approaches like p-Multigrid or h-Multigrid that work as long as you have a smoother on the coarse grid that is either matrix free, or can work with a very small matrix.

We currently support low-order-refined assembly of a high order operator on quads and hexes. But, as stated, this involves assembly of a large matrix at least for the preconditioner.

**Comment by dylan-copeland** [comment]
It is correct that Hypre preconditioners are not available for PA. This is not only an issue of implementation but also research, to find good preconditioners without access to matrices. In particular, AMG cannot be used. There is some research being done in this area, but as usual the starting place is H^1, and H(curl) will be a long-term goal. Matrix-free preconditioning is a new area where you could make significant contributions that would be appreciated, if you are interested.

**Comment by tzanio** [comment]
Closing this for now, but please reopen if you have any questions or updates.
