### ISSUE TITLE
Mean curvature, normal vectors

### ISSUE THREAD

**Issue by samanseifi** [mfem/mfem#1424]
In my application I need to impose boundary conditions depend on the boundary's mean curvature. This rises to operators of surface divergence of the normal vectors. These are the type of weak form I have:

`\int \gamma(\nabla\cdot w^{h}) da - \int n(u^{h})\otimes n(u^{h})\nabla\cdot w^h da `

where `\gamma` is the scalar `n(u^{h})` is the normal vector which is the function of displacement `u^{h}` . Any idea of how to handle such a thing?

**Comment by v-dobrev** [comment]
The first step would be to write these surface integrals as integrals on the reference face (triangle or quad) element. This transformation of the integral is essentially a change of variables. This change of variables is given by the mapping T from the reference element to the surface element -- maps a subset of R^2 to a subset of R^3. In particular the Jacobian of this map is a 3x2 matrix. This mapping is provided to integrators as the second argument, `Trans`, of the assembly method: https://github.com/mfem/mfem/blob/dcd2ed5c413695113d0cee8767de2ed9a7df47bd/fem/bilininteg.hpp#L78-L81
As part of this change of variables one needs to express the trial and test functions and their derivatives in terms of the trial and test functions on the reference element and their derivatives with respect to the new reference variables. The FE space for these reference functions is expressed in the above assembly method through the first argument, `el`.

Does this make sense?

**Comment by tzanio** [comment]
ping: @samanseifi

**Comment by samanseifi** [comment]
I think that makes sense. But I changed my mind on my formulation of the problem I'm working righ now. These integrals come from calculating geometrical entities such as normal vectors and curvatures in FE context. I'm trying to see if I can export the geometry in a computational geometry library and do the geometrical calculations there and get the information I want and send them back to my FE formulation. That's why I asked how to get vertices information at #1443.

**Comment by tzanio** [comment]
Ok, then I'll close this for now. Feel free to reopen later.
