### ISSUE TITLE
Working with mesh nodes and their FiniteElementSpace in parallel

### ISSUE THREAD

**Issue by jehicken** [mfem/mfem#1425]
Hello,

I hope everyone is faring well during this difficult time.

We have a nonlinear form that should input and output GridFunctions that are consistent with the space used by the mesh nodes.  The problem is that, if we are solving the problem in parallel, it does not look like there is a way of obtaining the parallel finite element space corresponding to the nodes.   In particular `Mesh::GetNodalFESpace()` does not appear to be virtual.  Is there a way to proceed in this case?  Should we build local nonlinear forms that use (serial) `GridFunction`s and then merge them afterward (somehow)?

Any advice would be appreciated.

Thanks,
Jason

**Comment by vladotomov** [comment]
I'm not familiar with the context, but an easy thing to do is to have the `ParFESpace` in advance, like it's done here:https://github.com/mfem/mfem/blob/579de51a3790e27d5de2820b4bec50b4e8c204ad/miniapps/meshing/pmesh-optimizer.cpp#L397

**Comment by jehicken** [comment]
Oh.  I thought the nodes' finite-element space was defined by the mesh, not imposed on it.  I will have to dig into this some more, obviously.

Regarding the context: we need to get the derivative of, for example, a functional with respect to the mesh nodes in order to do design optimization.

**Comment by pazner** [comment]
You can also use `dynamic_cast` to recover the parallel finite element space:
```c++
const ParFiniteElementSpace *nodal_pfes = dynamic_cast<const ParFiniteElementSpace *>(pmesh->GetNodalFESpace());
```
As long as the nodal space really is a `ParFiniteElementSpace` this should work (and you can check that the result is not `NULL` to be sure).

**Comment by tzanio** [comment]
Hi Jason, good to hear from you :)

To add to @vladotomov and @pazner's answers:

- If the mesh has nodes (i.e. it is not a linear mesh defined only by vertices) then it indeed defines its own finite element space. The `SetNodalFESpace` call is a way to override or set that in first place.

- You can also query the finite element collection for the nodes and define the appropriate space from it, see e.g. Example 1p, https://github.com/mfem/mfem/blob/master/examples/ex1p.cpp#L149-L160

Hope this helps,
Tzanio

**Comment by jehicken** [comment]
Thanks for the suggestion @pazner.

More context: part of our problem is that we are trying to have both parallel and serial versions of the code.  As a result, we are starting to get define guards all over the place, and I was hoping to keep the code generic by using pointers to base classes in this particular case.

That said, we are considering refactoring the code to just use the parallel classes, so this problem will likely go away when we do that.

**Comment by jehicken** [comment]
Thanks @tzanio.  We will take a look at the parallel example 1.

**Comment by jehicken** [comment]
Quick related question: what do we do if the mesh does not define nodes?  Can we use `Mesh::EnsureNodes()`?  If so, will this work for parallel meshes as well?

**Comment by pazner** [comment]
> Quick related question: what do we do if the mesh does not define nodes? Can we use `Mesh::EnsureNodes()`? If so, will this work for parallel meshes as well?

Yes, you can use `EnsureNodes`, which will create a (linear, continuous) nodal grid function if one doesn't exist, and do nothing if the nodes already exist.

You can also use `SetCurvature` if you need more control over the polynomial degree of the nodes, H1 or L2 space, etc.

These will both work in parallel, and the resulting nodal finite element space will be a `ParFiniteElementSpace`.

**Comment by jehicken** [comment]
Great, thanks @pazner.
