### ISSUE TITLE
When to convert to true dofs?

### ISSUE THREAD

**Issue by jehicken** [mfem/mfem#1426]
Hi,

Is there a general rule of thumb we should follow regarding when to use/extract the true dofs from a `ParGridFunction`?  Do we need to use the true dofs for all parallel forms?  And all solvers?

Thanks, and sorry for two questions in one day,
Jason

**Comment by v-dobrev** [comment]
I think a good rule of thumb is: try to use true dofs (aka T-vector) unless some method that you need to call requires a `(Par)GridFunction` (aka L-vector). Regarding the meaning of the terms T-vector and L-vector, take a look at the diagrams here: https://ceed.exascaleproject.org/bps/#terminology-and-notation.

Regarding the connections between T- and L-vectors and ways to convert between the two, take a look at this webpage: https://mfem.org/pri-dual-vec.

**Comment by jehicken** [comment]
Thanks @v-dobrev .  That helps.
