### ISSUE TITLE
HIP support with CMake

### ISSUE THREAD

**Issue by v-dobrev** [mfem/mfem#1428]
We can probably "steal" the `FindHIP.cmake` from OCCA: https://github.com/libocca/occa/blob/master/cmake/FindHIP.cmake contributed by @noelchalmers.

**Comment by tzanio** [comment]
@dmed256, @camierjs, @YohannDudouit or @adrienbernede -- do you want to take on this?

**Comment by adrienbernede** [comment]
Or use BLT: https://github.com/LLNL/blt/blob/develop/cmake/thirdparty/FindHIP.cmake

**Comment by rcarson3** [comment]
The BLT one is just taken from https://github.com/ROCm-Developer-Tools/HIP/blob/develop/cmake/FindHIP.cmake . Although, the BLT one isn't quite up to date with the one in the HIP repository now as of ROCM v3.8.0.

**Comment by tzanio** [comment]
Should we just borrow the ones from the official HIP repo then?

**Comment by tzanio** [comment]
Addressed by https://github.com/mfem/mfem/pull/1906
