### ISSUE TITLE
PCG gives NaN

### ISSUE THREAD

**Issue by amir90** [mfem/mfem#1429]
Hello, 
I want to perform a linear static analysis on a surface mesh.
I used ex2 as the basis of my attempt.

Everything seems to work up until the Gauss-Seidel preconditioner, which gives Nan(ind) in each iteration..

I have visualized the mesh using libigl (red is fixed boundary element vertices,  yellow is boundary element vertices with a force.

![image](https://user-images.githubusercontent.com/8117439/79671944-94f09280-81d6-11ea-8018-5e16367762ce.png)

I tried running with no force and still get Nan.

the mesh file I used
[test_mesh.txt](https://github.com/mfem/mfem/files/4497824/test_mesh.txt)

and the code (minor changes due to the boundary attribute numbering being:
1 - default
2 - essential fixed BC boundary
3 - force BC boundary

```
mfem::FiniteElementCollection *fec;
	mfem::FiniteElementSpace *fespace;
	fec = new mfem::H1_FECollection(1, dim);
	fespace = new mfem::FiniteElementSpace(femMesh, fec, dim);

	mfem::Array<int> ess_tdof_list, ess_bdr(femMesh->bdr_attributes.Max());
	std::cout << femMesh->bdr_attributes.Max() << std::endl; //OK
	ess_bdr = 0;
	ess_bdr[1] = 1;
	fespace->GetEssentialTrueDofs(ess_bdr, ess_tdof_list);

	mfem::VectorArrayCoefficient f(dim);
	for (int i = 0; i < dim - 1; i++)
	{
		f.Set(i, new mfem::ConstantCoefficient(0.0));
	}
	{
		mfem::Vector pull_force(femMesh->bdr_attributes.Max());
		pull_force = 0.0;
		pull_force(2) = 0;//-1.0e-2;
		f.Set(dim - 1, new mfem::PWConstCoefficient(pull_force));
	}

	mfem::LinearForm *b = new mfem::LinearForm(fespace);
	b->AddBoundaryIntegrator(new mfem::VectorBoundaryLFIntegrator(f));
	std::cout << "r.h.s. ... " << std::flush;
	b->Assemble();

	mfem::GridFunction x(fespace);
	x = 0.0;

	mfem::Vector lambda(femMesh->attributes.Max());
	lambda = 1.0;
	mfem::PWConstCoefficient lambda_func(lambda);
	mfem::Vector mu(femMesh->attributes.Max());
	mu = 1.0;
	mfem::PWConstCoefficient mu_func(mu);

	mfem::BilinearForm *a = new mfem::BilinearForm(fespace);
	a->AddDomainIntegrator(new mfem::ElasticityIntegrator(lambda_func, mu_func));

	std::cout << "matrix ... " << std::flush;
	//if (static_cond) { a->EnableStaticCondensation(); }
	a->Assemble();

	mfem::SparseMatrix A;
	mfem::Vector B, X;
	a->FormLinearSystem(ess_tdof_list, x, *b, A, X, B);
	std::cout << "done." << std::endl;
	std::cout << "Size of linear system: " << A.Height() << std::endl;

#ifndef MFEM_USE_SUITESPARSE
	// 11. Define a simple symmetric Gauss-Seidel preconditioner and use it to
	//     solve the system Ax=b with PCG.
	mfem::GSSmoother M(A);
	PCG(A, M, B, X, 1, 500, 1e-8, 0.0);
#else
	// 11. If MFEM was compiled with SuiteSparse, use UMFPACK to solve the system.
	UMFPackSolver umf_solver;
	umf_solver.Control[UMFPACK_ORDERING] = UMFPACK_ORDERING_METIS;
	umf_solver.SetOperator(A);
	umf_solver.Mult(B, X);
#endif

	a->RecoverFEMSolution(X, *b, x);

	if (!femMesh->NURBSext)
	{
		femMesh->SetNodalFESpace(fespace);
	}

	{
		mfem::GridFunction *nodes = femMesh->GetNodes();
		*nodes += x;
		x *= -1;
		std::ofstream mesh_ofs("displaced.mesh");
		mesh_ofs.precision(8);
		femMesh->Print(mesh_ofs);
		std::ofstream sol_ofs("sol.gf");
		sol_ofs.precision(8);
		x.Save(sol_ofs);
	}

```

and what i am getting is:

   Iteration :   0  (B r, r) = -nan(ind)
   Iteration :   1  (B r, r) = nan
   Iteration :   2  (B r, r) = -nan(ind)
   Iteration :   3  (B r, r) = nan
   Iteration :   4  (B r, r) = -nan(ind)
   Iteration :   5  (B r, r) = nan
   Iteration :   6  (B r, r) = -nan(ind)
   Iteration :   7  (B r, r) = nan
   Iteration :   8  (B r, r) = -nan(ind)
   Iteration :   9  (B r, r) = nan
   Iteration :  10  (B r, r) = -nan(ind)
   Iteration :  11  (B r, r) = nan
   Iteration :  12  (B r, r) = -nan(ind)
   Iteration :  13  (B r, r) = nan
   Iteration :  14  (B r, r) = -nan(ind)
   Iteration :  15  (B r, r) = nan
   Iteration :  16  (B r, r) = -nan(ind)
...

Thanks.

**Comment by psocratis** [comment]
Hi @amir90 , it seems like the given text mesh file is the cause of this. Take a look at the nodes defined at the end of the file
