### ISSUE TITLE
Coefficient with user data

### ISSUE THREAD

**Issue by juan42** [mfem/mfem#143]
At the moment the FunctionCoefficient can take a raw function pointers which points to a function with the arguments (const Vector &, double). Thus, besides global state, there is no possibility for the user to access external data.

I have a proposal and a question regarding usage. First, i'd like to explain a simple example use case.

Suppose you want to use an external library which computes input functions for your FEM simulation, this could be an optimization library which generates trajectories etc. Let us assume that you are able to access a double array which has the data of the computed input values which can depedent on time and space. Now you want to run the simulation using that data, thus accessing user provided data in a Coefficient.

Is the user supposed to inherit from Coefficient and provide a self built mechanism of providing the data?

Would a FunctionCoefficient callback with a void pointer be useful to provide an easy way of accessing user data without using global scope?

**Comment by mlstowell** [comment]
Yes, the expected solution to this type of problem is that the developer will write a customized class derived from Coefficient.  Objects of this new class can then be initialized with all of the necessary data in whatever form is most convenient.

Just to make sure I understand your suggestion.  Our FunctionCoefficient class currently takes two types of function pointers:
double(*f)(const Vector&)
double(*f)(const Vector&, double)

Your proposal is to add two more with signatures:
double(*f)(const Vector&, void*)
double(*f)(const Vector&, double, void*)
as a means of providing function parameters without needing to add derived classes.

This certainly sounds reasonable (and useful) to me.  Let's see if the other members of the team have any concerns or suggestions.

**Comment by v-dobrev** [comment]
I think the most natural way is to derive a new coefficient class from any of the coefficient classes in mfem (not necessarily the base class `Coefficient`).

Of course, if you want to add to mfem a new class or functionality that will be generally useful, then I'm all for that.

**Comment by juan42** [comment]
> This certainly sounds reasonable (and useful) to me. Let's see if the other members of the team have any concerns or suggestions.

I tried a custom implementation as inherited Coefficient and think that is the way to go. It is not too much boilerplate and leaves the user with every freedom which might be needed. Although adding another FunctionCoefficient with user data seemed the way to go in my first thought, i might be wrong :)

**Comment by tzanio** [comment]
Either option is fine with me.

A user-derived class is probably the most natural and flexible.

On the other hand one can certainly consider extending `FunctionCoefficient` with something like:
```c++
class FunctionCoefficient : public Coefficient
{
protected:
   void* UserData;
   double (*Function)(const Vector &);
   double (*TDFunction)(const Vector &, double);
   double (*FunctionWithUserData)(void*, const Vector &);
   double (*TDFunctionWithUserData)(void*, const Vector &, double);

public:
   /// Define a time-independent coefficient from a C-function
   FunctionCoefficient(double (*f)(const Vector &))
   {
      Function = f;
      TDFunction = NULL; FunctionWithUserData = NULL; TDFunctionWithUserData = NULL;
   }

   /** Define a time-independent coefficient with additional user data from a C-function.
         The additional data should be set by calling SetUserData() before Eval(). */
   FunctionCoefficient(double (*f)(void*, const Vector &))
   {
      FunctionWithUserData = f;
      Function = NULL; TDFunction = NULL; TDFunctionWithUserData = NULL;
   }

   // ...

   SetUserData(void* data) { UserData = data; }

   // ...
}
```
which could also be useful for other users.

**Comment by tzanio** [comment]
Hi Julian, were you able to resolve this? -Tzanio

**Comment by juan42** [comment]
For our specific case i just reimlpemented a Coefficient, which is what i would recommend to others, thus it would be redundant providing an extension for FunctionCoefficient. Resolved ;)
