### ISSUE TITLE
Read Gmsh mesh in PyMFEM 

### ISSUE THREAD

**Issue by Pratikk17** [mfem/mfem#1438]
Dear Sir,

I have a mesh generated using GMSH (in .msh) format. I can view it using glvis. But I do not understand how to import it into PyMFEM. What changes need to be done in the statement
"mesh=mfem.Mesh(meshfile,1,1) ? 
Sorry for the basic question.
Thank you very much.
Best,
Pratik

**Comment by sshiraiwa** [comment]
It should recognize the file extension automatically. According to this
https://github.com/mfem/mfem/blob/master/mesh/mesh.cpp#L3201

It switches to GMSH when a file starts with $MeshFormat. We don't need to do anything
on the Python side. In fact, here, for example, I am passing just a file path. 

https://github.mit.edu/shiraiwa/PetraM_Base/blob/master/petram/mesh/mesh_model.py#L198

**Comment by hongbo-yao** [comment]
Hi @Pratikk17 ,

I also use gmsh's .msh file for my work, In MFEM, I just use:

`const char *mesh_file = "file_name.msh";
Mesh *mesh = new Mesh(mesh_file, 1, 1);`
or
`const char *mesh_file = "file_name.msh";
Mesh mesh(mesh_file, 1, 1);`

It works, Have you installed the code help documentation？ I have learned from them a lot 

Hongbo

**Comment by Pratikk17** [comment]
Hi @hongbo-yao and @sshiraiwa ,

Thank you to both of you. I will check this and let you know.

Best,
Pratik
