### ISSUE TITLE
Nonconforming triangular mesh

### ISSUE THREAD

**Issue by Pratikk17** [mfem/mfem#1439]
Hi,

I started using MFEM since yesterday with the main goal to solve Poisson equation on a nonconforming triangular mesh on a square domain. But just now, I found out that MFEM supports non-conforming mesh refinement (quadrilateral/hexahedral meshes), including anisotropic refinement. I just need to use this mesh. I will not refine it.

I wanted to know if MFEM can solve Poisson problem on nonconforming triangular mesh? I have attached the image of mesh for the reference. 

Thank you in advance.
Best regards,
Pratik
![nonconforming](https://user-images.githubusercontent.com/63018176/80126288-26735200-8593-11ea-8024-14c99679eb6a.jpg)

**Comment by jakubcerveny** [comment]
Hi @Pratikk17, 

MFEM does support nonconforming refinement of triangles, but normally we do "red" refinement (a triangle is refined into four similar triangles). However, if you won't be refining the mesh further, you can define a mesh exactly as in the picture, by hand.

You can start by creating a standard MFEM v1.0 mesh as described in https://mfem.org/mesh-formats/, just define all the vertices, elements and boundaries. This mesh should work, except at the hanging vertices the solution will be disconnected.

Now you can change the version to MFEM v1.1 and add the new section "vertex_parents" (https://mfem.org/mesh-formats/#mfem-mesh-v11), where you will mark the hanging vertices as midpoints of two "parent" vertices. In your case you will add four lines in the vertex_parents section.

I can help you with the second step if you get stuck.

**Comment by Pratikk17** [comment]
Hi @jakubcerveny,
Thank you for your quick reply. I did this. But I have a minor problem in the visualization of mesh and solution. I have uploaded files regarding this. Can you please have a quick look? Nonconforming_triangular.pdf contains mesh labeling.

[Nonconforming_triangular.pdf](https://github.com/mfem/mfem/files/4527698/Nonconforming_triangular.pdf)
#=================== Mesh file
MFEM mesh v1.1

dimension
2

elements
32
1 2 0 1 4
1 2 1 2 4
1 2 2 3 4
1 2 3 0 4
1 2 3 2 7
1 2 2 5 7
1 2 5 6 7
1 2 6 3 7
1 2 8 9 12
1 2 9 10 12
1 2 10 11 12
1 2 11 8 12
1 2 11 10 15
1 2 10 13 15
1 2 13 14 15
1 2 14 11 15
1 2 1 8 18
1 2 8 16 18
1 2 16 17 18
1 2 17 1 18
1 2 17 16 19
1 2 16 11 19
1 2 11 2 19
1 2 2 17 19
1 2 2 11 22
1 2 11 20 22
1 2 20 21 22
1 2 21 2 22
1 2 21 20 23
1 2 20 14 23
1 2 14 5 23
1 2 5 21 23

boundary
10
1 1 0 1
2 1 1 8
3 1 8 9 
4 1 9 10
4 1 10 13
5 1 13 14
6 1 14 5
7 1 5 6
8 1 6 3
8 1 3 0 

vertex_parents
4
17 1 2
21 2 5
16 8 11
20 11 14

vertices
24
2
0 0 
0.4 0 
0.4 0.5 
0 0.5 
0.2 0.25 
0.4 1 
0 1 
0.2 0.75 
0.6 0 
1 0 
1 0.5 
0.6 0.5 
0.8 0.25 
1 1 
0.6 1 
0.8 0.75 
0.6 0.25 
0.4 0.25 
0.5 0.125 
0.5 0.375 
0.6 0.75 
0.4 0.75 
0.5 0.625 
0.5 0.875 

#============== Refined mesh by solving ex1
MFEM mesh v1.1

dimension
2

elements
32
1 2 0 1 4
1 2 1 2 4
1 2 2 3 4
1 2 3 0 4
1 2 3 2 7
1 2 2 5 7
1 2 5 6 7
1 2 6 3 7
1 2 8 9 12
1 2 9 10 12
1 2 10 11 12
1 2 11 8 12
1 2 11 10 15
1 2 10 13 15
1 2 13 14 15
1 2 14 11 15
1 2 1 8 18
1 2 8 16 18
1 2 16 17 18
1 2 17 1 18
1 2 17 16 19
1 2 16 11 19
1 2 11 2 19
1 2 2 17 19
1 2 2 11 22
1 2 11 20 22
1 2 20 21 22
1 2 21 2 22
1 2 21 20 23
1 2 20 14 23
1 2 14 5 23
1 2 5 21 23

boundary
10
1 1 0 1
2 1 1 8
3 1 8 9
4 1 9 10
4 1 10 13
5 1 13 14
6 1 14 5
7 1 5 6
8 1 6 3
8 1 3 0

vertex_parents
4
16 8 11
17 1 2
20 11 14
21 2 5

coarse_elements
32

vertices
24
2
0 0
0.4 0
0.4 0.5
0 0.5
0.2 0.25
0.4 1
0 1
0.2 0.75
0.6 0
1 0
1 0.5
0.6 0.5
0.8 0.25
1 1
0.6 1
0.8 0.75
0.6 0.25
0.4 0.25
0.5 0.125
0.5 0.375
0.6 0.75
0.4 0.75
0.5 0.625
0.5 0.875

**Comment by Pratikk17** [comment]
Hi @jakubcerveny ,

Thank you very much for your suggestion. It worked. However, I realised that along with adding a section "vertex_parents", I also need to add a section "coarse_elements". 

Thank you again.
Best,
Pratik

**Comment by jakubcerveny** [comment]
Yes, I also noticed the `coarse_elements` section is required. This may be a bug. I'll resolve it in #1392

**Comment by Pratikk17** [comment]
Hi @jakubcerveny,

I realized that the coarse_elements section is in fact not necessary. Just need to add these two lines
"coarse_elements
0"
This worked for all the cases I considered. All these cases are similar to the ones I  discussed on the top. 

Best,
Pratik
