### ISSUE TITLE
Face elements and vertices

### ISSUE THREAD

**Issue by samanseifi** [mfem/mfem#1443]
Is there any fast way of getting the matrix of fall ace elements and their coordinates and connectivity from a mesh objects?

**Comment by fanronghong** [comment]
Hi,

If I understand your question correctly, maybe the below codes can give you some help.
```
void FacetInfo2(Mesh& mesh)
{
    const Table& element2facet = mesh.ElementToFaceTable();
    Array<int> e2f;
    for (size_t i=0; i<mesh.GetNE(); i++)
    {
        element2facet.GetRow(i, e2f);
        for (int j=0; j<e2f.Size(); j++)
        {
            const Element* face = mesh.GetFace(j);
        }
    }
}
```
or
```
void FacetInfo(Mesh& mesh)
{
    const Table& face2element = *(mesh.GetFaceToElementTable());
    Array<int> f2e;
    for (size_t i=0; i<mesh.GetNumFaces(); i++)
    {
        face2element.GetRow(i, f2e);
        if (f2e.Size() == 1) // facet is on boundary 
        {
        }
        else // interior facet
        {
            int attr1 = mesh.GetElement(f2e[0])->GetAttribute();
            int attr2 = mesh.GetElement(f2e[1])->GetAttribute();
        }
    }
}
```
And there are many other functionality in `mesh/mesh.hpp`, like `GetElementToEdgeTable()`, `ElementToFaceTable`...

**Comment by v-dobrev** [comment]
@samanseifi, I'm afraid I don't quite understand your question: what matrix are you referring to? Also, what specific connectivity do you need?

**Comment by samanseifi** [comment]
@v-dobrev Let's say I have a 3D Tet mesh. Now I want to collect all the coordinates of surface vertices. These coordinates represent a triangular surface mesh, now I want to get a connectivity matrix of all these surface triangles. I hoped there might be a quick way of doing it.

**Comment by v-dobrev** [comment]
It looks like you want to access what we call in mfem the "boundary" elements. Depending on the input mesh format, the boundary elements may consist precisely of the face elements that have exactly one adjacent element (tet element in your case). If specified by the input mesh file, these boundary elements can include interior faces, or the may not describe all real boundary elements. The easiest way to check what the boundary elements are is to open the mesh in GLVis -- at the start it will plot precisely the boundary elements. If your mesh file does not contain explicitly any boundary elements, mfem will generate them after reading the file.

Boundary elements can be queried with methods like `Mesh::GetBdrElementVertices` -- this returns the indices of the vertices that describe the boundary element. The coordinates of the vertices can then be obtained using the method `Mesh::GetVertex`. The number of boundary elements is returned by the method `Mesh::GetNBE`. Is this the type of information you need?

**Comment by tzanio** [comment]
ping: @samanseifi

**Comment by samanseifi** [comment]
Yes these are what I need and I'm making progress.  Thanks.

**Comment by tzanio** [comment]
I'm closing this for now, but feel free to reopen if you have further questions.
