### ISSUE TITLE
Compilation error -- gnu make

### ISSUE THREAD

**Issue by cjoycd** [mfem/mfem#1445]
Dear All,
I am getting following error while compiling the version 4.1. Can someone suggest what could be the possible reason. I am using the defaults.mk with CXX = g++ and MPICXX = mpicxx. This was working for the old version.

mesh/pncmesh.cpp: In member function ‘void mfem::ParNCMesh::RedistributeElements(mfem::Array<int>&, int, bool)’:
mesh/pncmesh.cpp:2095:55: error: ‘MPI_Ibarrier’ was not declared in this scope
                int err = MPI_Ibarrier(MyComm, &barrier);
                                                       ^
make[1]: *** [mesh/pncmesh.o] Error 1
make[1]: *** Waiting for unfinished jobs....

Thanks in advance

**Comment by v-dobrev** [comment]
It looks like `MPI_Ibarrier` requires MPI implementation that supports the MPI v3.0 standard. What MPI implementation are you using? Maybe you need a newer version.

cc: @jakubcerveny

**Comment by cjoycd** [comment]
Yes, it was due to an older version.. It is getting compiled now with new MPI.

Thank you very much
