### ISSUE TITLE
Mismatch in node data

### ISSUE THREAD

**Issue by vikramsg** [mfem/mfem#145]
I have been trying to do some initial familiarization with the mfem code. The following is based on the advection code and I am just trying to see where the nodes are and how data is being assigned, and how to calculate derivatives. So the u0_function clearly shows there are 36 dofs and I can see the x, y locations. But when I do the mesh->GetNodes and print it, there are only 36 entries as against 72. And printing it suggests it contains only the x locations of all nodes. Please tell me what I am doing wrong here?

```c++
#include "mfem.hpp" 
#include <fstream>
#include <iostream>
#include <algorithm>

using namespace std;
using namespace mfem;

// Choice for the problem setup. The fluid velocity, initial condition and
// inflow boundary condition are chosen based on this parameter.
int problem;

// Velocity coefficient
void velocity_function(const Vector &x, Vector &v);

// Initial condition
double u0_function(const Vector &x);

// Mesh bounding box
Vector bb_min, bb_max;



int main(int argc, char *argv[])
{
   // 1. Parse command-line options.
   problem = 0;
   const char *mesh_file = "periodic-square.mesh";
   int order = 1;
   double t_final = 0.02;
   double dt = 0.01;
   bool visit = true;
   int vis_steps = 5;

   int precision = 8;
   cout.precision(precision);

   Mesh *mesh = new Mesh(mesh_file, 1, 1);
   int dim = mesh->Dimension();

   mesh->GetBoundingBox(bb_min, bb_max, max(order, 1));

   DG_FECollection fec(order, dim);
   FiniteElementSpace fes(mesh, &fec);

   cout << "Number of unknowns: " << fes.GetVSize() << endl;

   FunctionCoefficient u0(u0_function);

   GridFunction u(&fes);
   u.ProjectCoefficient(u0);

   //Get derivatives
   GridFunction u_grad(&fes);
   u.GetDerivative(1, 0, u_grad);

   u.Print();

   // Print all nodes in the finite element space 
   GridFunction nodes(&fes);
   mesh->GetNodes(nodes);

   nodes.Print();
}


// Velocity coefficient
void velocity_function(const Vector &x, Vector &v)
{
   int dim = x.Size();

   // map to the reference [-1,1] domain
   Vector X(dim);
   for (int i = 0; i < dim; i++)
   {
      double center = (bb_min[i] + bb_max[i]) * 0.5;
      X(i) = 2 * (x(i) - center) / (bb_max[i] - bb_min[i]);
   }

   v(0) = sqrt(2./3.); v(1) = sqrt(1./3.);
}


// Initial condition
double u0_function(const Vector &x)
{
   int dim = x.Size();

   // map to the reference [-1,1] domain
   Vector X(dim);
   for (int i = 0; i < dim; i++)
   {
      double center = (bb_min[i] + bb_max[i]) * 0.5;
      X(i) = 2 * (x(i) - center) / (bb_max[i] - bb_min[i]);
   }

   double fn = cos(M_PI*X(0))*sin(M_PI*X(1));

   cout << x(0) << '\t' << x(1) << '\t' << fn << endl;

   return fn;
}
```

**Comment by tzanio** [comment]
Hi @vikramsg,

The problem is that `nodes` is a vector continuous function, while `u` is a scalar discontinuous function -- their finite element spaces are different.

Try the following:

```c++
H1_FECollection nodes_fec(1, dim);
FiniteElementSpace nodes_fes(mesh, &nodes_fec, dim);
GridFunction nodes(&nodes_fes);
mesh->GetNodes(nodes);
nodes.Print();
```

Notice that we use `H1` collection (finite element type) and specify a vector space in the last argument of the `FiniteElementSpace` constructor.

Hope this helps,
Tzanio

**Comment by vikramsg** [comment]
Hi @tzanio,

Thanks a lot for the reply. Now its clear. I am not sure that this is where I should post this but while looking at how gradients are calculated I saw the following three lines at the end of GetGradients. Shouldn't the last line have grad as an argument instead of gcol? Thanks. 

```
grad.GetColumnReference(i, gcol);
CalcInverse(Tr->Jacobian(), Jinv);
Jinv.MultTranspose(gh, gcol);
```

**Comment by v-dobrev** [comment]
Hi @vikramsg,

The second argument of `MultTranspose` has to be a Vector, and `grad` is a `DenseMatrix`. That is why we create a `Vector gcol` that references the i-th column of `grad` (we use column-major storage in class `DenseMatrix`). Essentially, after the `GetColumnReference` call, `gcol`'s data pointer is set to the beginning of the i-th column of `grad`.

**Comment by vikramsg** [comment]
Hi @v-dobrev,

Thanks for the clarification. Sorry for the confusion.
