### ISSUE TITLE
AMR: Tetrahedron element is not marked for refinement

### ISSUE THREAD

**Issue by aasivas** [mfem/mfem#1453]
We are trying to use AMR for a paper we are working on. We want to use tetrahedral meshes and we want to test the convergence rates of a FEM, the runtime and the scalability. For these reasons, we start from an initial mesh, serially refine it few times, create a parallel mesh and do parallel refinement few times before switching to AMR. However, if we do any sort of serial refinement we encounter the error below.
 
```
Verification failed: (tet->GetRefinementFlag() != 0) is false:
 --> TETRAHEDRON element is not marked for refinement.
 ... in function: void mfem::Mesh::Bisection(int, mfem::HashTable<mfem::Hashed2> &)
 ... in file: mesh/mesh.cpp
```

This issue might seem similar to #947, #1028 and #1119. However, it still exists in MFEM 4.1.1. The error can be reproduced by taking the steps below;

1. Modify ex6p.cpp slightly, move `mesh->UniformRefinement();` to the line above the `if (mesh->NURBSext)`  condition.
2. Compile ex6p and run using any of the inline-tet or beam-tet.

Two interesting observations:
- MFEM does not throw analogous errors if ex6p is used with 2-dimensional meshes of any kind (beam-quad, beam-tri, inline-quad, inline-tri and star.mesh are the ones I tried) or 3-dimensional hexahedral meshes (beam-hex, inline-hex).
- After the modification inline-wedge does not even throw an error, ex6p segfaults when AMR is attempted.

**Comment by aasivas** [comment]
It looks like I do not have the good habit of reading documentation. Sorry for bothering you. In case any one else encounters this problem, there are currently two uniform refinement algorithms implemented for tetrahedral meshes. They are called Algorithm A and Algorithm B. The default is Algorithm A, however, if used mesh has to be finalized before local refinement can be attempted (this is stated in the doxygen pages). If Algorithm B is used, there is no issue, no need for finalization.

So what is the solution? Either the line 
```
mesh->UniformRefinement();
```
can be replaced with  
```
mesh->UniformRefinement(1); // Use Algorithm B
```
or the line
```
mesh->FinalizeTopology(); // According to the documentation this is necessary but
                          // everything works okay if it is not there for this example.
mesh->Finalize(true); // refine parameter is set to true
```
can be added after `mesh->EnsureNCMesh()`.

`FinalizeTopology` is also called at the end of `Finalize` if `may_change_topology` is `TRUE` so it seems to me that there is some redundancy in some cases. But I guess it is an implementation choice. The important thing seems to be the function `MarkForRefinement` and/or `MarkTetMeshForRefinement` which are called during `Finalize` if the parameter `refine` is set to true which explains the error we got. Because we never marked any of those elements for refinement to begin with.

Obviously this is not a bug and obviously it is my fault as I did not read the documentation/code properly. However, I also didn’t expect this exceptional case for tetrahedral meshes. In my mind, it wasn’t any different than a hexahedral mesh. So the average user will very likely encounter this problem. That is why I wrote this long explanation.

Thanks a lot for your time and sorry for any inconvenience I caused.

**Comment by v-dobrev** [comment]
Hi @aasivas, sorry about the confusion.

Let me add a few comments about tet refinement in mfem which may help explain some of the issues you encountered:
* There are two ways to refine individual tets: using octa-section (a tet is directly split into 8 small tets), and using bisection (the tet is split into 2 tets three times to get 8 small tets).
* Restricted to the faces, octa-section and bisection produce the following triangle refinements, respectively:
```ascii
    *          *
   / \	      /|\
  *---*	     * | *
 / \ / \    / \|/ \
*---*---*  *---*---*
```
* Octa-section will typically give rise to better shaped refined tets than bisection will.
* For uniform refinement, octa-section is used by algorithm A (the default) and bisection is used by algorithm B.
* Local conforming refinement uses bisection and needs tets to be marked for refinement (this marking is lost if one uses algorithm A). Algorithm B is basically this local refinement algorithm applied to all elements.
* Local non-conforming refinement uses octa-section.
* Tet bisection cannot be used with mixed meshes, e.g meshes with tets and prisms.
