### ISSUE TITLE
Usage of Prolongation operators in FiniteElementSpace class

### ISSUE THREAD

**Issue by jmartfrut** [mfem/mfem#1457]
Hi all,

I am using a FiniteElementSpaceHierarchy with two FiniteElementSpaces and I'd like to get back the nodal coordinates of the coarse space from the nodal coordinates of the fine space using prolongation operators. I've coded the following example but unfortunately I dont know what I'm doing wrong. Am I using the operators correctly?

thank you very much,

```
int main(int argc, char **argv)
{
    const char *mesh_file = "3d-cubeh8.msh";
    Mesh *mesh = new Mesh(mesh_file, 1, 1);

    FiniteElementCollection *fec = new H1_FECollection(1, 3);
    FiniteElementSpace *coarse_fespace = new FiniteElementSpace(mesh, fec,3);
    FiniteElementSpaceHierarchy fespaces(mesh, coarse_fespace, true, true);

    fespaces.AddUniformlyRefinedLevel();

    fespaces.GetFinestFESpace().GetMesh()->SetNodalFESpace(&(fespaces.GetFinestFESpace()));
    fespaces.GetFESpaceAtLevel(0).GetMesh()->SetNodalFESpace(&(fespaces.GetFESpaceAtLevel(0)));

    Vector *xcoarse= fespaces.GetFESpaceAtLevel(0).GetMesh ()->GetNodes();
    Vector *xfine= fespaces.GetFESpaceAtLevel(1).GetMesh ()->GetNodes();
    cout<<"xfine"<<endl;
    xfine->Print();
    cout<<"xcoarse"<<endl;
    xcoarse->Print();
    Vector xcoarse_new(xcoarse->Size());
    fespaces.GetProlongationAtLevel(0)->MultTranspose(*xfine,xcoarse_new);
    cout<<"xcoarse_new"<<endl;
    xcoarse_new.Print();

    return 0;
}

```

This is the 3d-cubeh8.msh

$MeshFormat
2.2 0 8
$EndMeshFormat
$Nodes
8
1 0 0 0
2 1 0 0
3 0 1 0
4 1 1 0
5 1 1 1
6 1 0 1
7 0 1 1
8 0 0 1
$EndNodes
$Elements
4
1 3 2 2 16 2 4 3 1
2 3 2 1 20 6 5 7 8
3 5 2 1 26 8 6 2 1 7 5 4 3
4 3 2 3 22 1 3 7 8
$EndElements

**Comment by v-dobrev** [comment]
The prolongation operator allows you to compute the fine coordinates from the coarse coordinates. Applying the transpose to the fine coordinates will not give you the coarse coordinates -- written in matrix form: `P^T P != I`. What you need is a restriction operator, `R` such that `R P = I`. Typically, `R` will have the form (up to some permutation of the rows/columns) `R = (I 0)` whereas `P` has the form `P = (I W^T)^T` where `W` contains the interpolation weights of the new fine nodes (in terms of the coarse nodes).

Currently, in the context of mesh refinement, mfem does not provide a method to construct `R`, however, implementing such a method is not very hard.

**Comment by jmartfrut** [comment]
thank you for the information Veselin,

my misunderstanding comes from the fact that inside Multigrid class the restriction operations are performed in this way

// Restrict residual
fespaces.GetProlongationAtLevel(level - 1)->MultTranspose(*R[level], *X[level - 1]);

so I though I could do the restriction of the spatial configuration in the same vein.  I'm implementing a geometric multigrid to be used inside a NewtonSolver so I need to restrict x through all the levesl in order to update the operator oper->GetGradient(x) in the coarse solver and the smoothers. Do you think It is requiered to implement a new restriction operator or there is another approach in MFEM to circunvent this issue. 

Thank you very much,

**Comment by v-dobrev** [comment]
Typically in multigrid, one is applying `P` to solutions or solution increments, whereas `P^T` is applied to residuals (residual = b - A.solution) or residual increments. In this typical case, it is never necessary to restrict solutions. This is an important distinction to make. If the multigrid algorithm you want to implement involves restrictions of solutions then the algorithm should specify what these restriction operators look like -- they may involve some averaging instead of simply picking the coarse dofs.

**Comment by jmartfrut** [comment]
Thanks @v-dobrev
