### ISSUE TITLE
Face neighbor element number is ambiguous in interior face integrators in parallel

### ISSUE THREAD

**Issue by pazner** [mfem/mfem#1458]
An interior face integrator has access to the element numbers of the two neighboring elements through `Trans.Elem1No` and `Trans.Elem2No`. Many DG integrators check e.g. `Trans.Elem1No >= 0` to verify that the face is interior rather than boundary.

An ambiguity is introduced in parallel, where the index `Trans.Elem2No` could refer to a local (on-processor) element, or to a "face neighbor" element, and so if the integrator needs information about the finite element, it does not appear possible to decide whether to call `ParFiniteElementSpace::GetFE` or `ParFiniteElementSpace::GetFaceNbrFE`.

As far as I can tell, there is currently no way to resolve this ambiguity.

One potential solution is to modify `ParBilinearForm::AssembleSharedFaces`, for example by passing an element index such that `Trans.Elem2No` is greater than or equal to the number of elements, indicating that the element is a face neighbor element (and then the face neighbor element index can be recovered by subtracting the number of on-processor elements in the mesh).

**Comment by v-dobrev** [comment]
The integrator methods get the necessary FEs as parameters. Do you need the FE for `Elem2No` for some other FE space?

Actually, looking at the code, I think you can get this shifted "face-neighbor" element index from `Trans.Elem2` -- this is the transformation used to evaluate `Coefficient`s like `GridFunctionCoefficient` where this shifted index is used in the parallel override of the method `GridFunction::GetValue`, here: https://github.com/mfem/mfem/blob/11f3414929bae8917923595c70245896ab88b14f/fem/pgridfunc.cpp#L263-L299

Maybe for consistency we can set `Trans.Elem2No` to the same shifted index. On the other hand, I'm not sure if this will not break some other part of the code (probably not). I guess all DG integrators now use that number just to check if it is `>= 0` to know if there is an actual second side.

**Comment by pazner** [comment]
I am working on an integrator that uses elementwise precomputed "lifting" operators on the faces, i.e. for each element a local matrix is precomputed, and then these operators are accessed on each face. With the information currently given to the integrator (the FE and corresponding ElementTransformation), it is possible to recompute this operator, but that is relatively expensive. It is natural to access these elementwise operators by their element indices.

I think using a shifted index could be a good solution (if I understand correctly, this is also what I was proposing). It seems very unlikely that changing this will break existing code, because integrators cannot currently reliably depend on `Trans.Elem2No` in parallel (except for checking `>= 0`).

**Comment by v-dobrev** [comment]
Let me clarify: the shifted index is already available in `Trans.Elem2->ElementNo`, so you should be able to work with `master` as it is.

Updating the code to put the same number in `Trans.Elem2No` seems reasonable but it is not strictly necessary.

**Comment by pazner** [comment]
Ah, thanks for the clarification! Yes, working with `Trans.Elem2->ElementNo` will do what I need. I will admit that it is a bit confusing that `Trans.Elem2->ElementNo` and `Trans.Elem2No` can be different, but it might not be worth changing the code to address this.

**Comment by v-dobrev** [comment]
I don't mind changing `Trans.Elem2No` to be the same as `Trans.Elem2->ElementNo`. However, looking at the code, there are a few places where the current setting of `Trans.Elem2No` matters, e.g. here: https://github.com/mfem/mfem/blob/0f067d41393943fbabc76fd62a9ed76c8e9a48e5/fem/pbilinearform.cpp#L202

and here: https://github.com/mfem/mfem/blob/0f067d41393943fbabc76fd62a9ed76c8e9a48e5/fem/pbilinearform.cpp#L218-L220

There's also the possibility that some dependent codes use the current setting as well.

**Comment by tzanio** [comment]
Can we add documentation that clarifies this for other developers in the future?

**Comment by tzanio** [comment]
Discussion continued in #1491
