### ISSUE TITLE
L2 error in example 23

### ISSUE THREAD

**Issue by Pratikk17** [mfem/mfem#1459]
Hi,

I have a quick question on how to find the L2 error at the final time. I defined final solution as
double FinalSolution(const Vector &x)
{
   return ..............;
}
and then projected this solution on grid using
FunctionCoefficient u_exact(FinalSolution);
uex_gf.ProjectCoefficient(u_exact);

In line 380, the solution at final time is calculated : ode_solver->Step(u, dudt, t, dt);

Which command gives us the L2 error between final solution and solution at final time? I tried using u_gf.ComputeL2error(uex_gf) but it gave me error.

Thank you very much.
Best regards,
Pratik

**Comment by mlstowell** [comment]
Hi, @Pratikk17 ,
The method `GridFunction::ComputeL2Error` expects a `Coefficient` not a `GridFunction` so `u_gf.ComputeL2Error(u_exact)` should work.
Best wishes,
Mark

**Comment by Pratikk17** [comment]
Thank you very much @mlstowell
