### ISSUE TITLE
Curved boundary mesh

### ISSUE THREAD

**Issue by rhebergens** [mfem/mfem#146]
Hello,
We are looking at the curved element examples, in particular, we are looking at an example with quadratic triangular meshes, see http://mfem.org/mesh-formats/#curvilinear-vtk-meshes
If we run the example `glvis -m square-disc-p2.vtk -k "Am"` we see indeed quadratic elements in the interior. Say we want linear elements in the interior and only curved edges near the disc, how would we create such a grid?
Sander

**Comment by MarkShephard** [comment]
In our work we use the Simmetrix mesh generator. It has options to 
create quadratic curved meshes where it curves the element entities on 
the curved boundaries and only curves interior ones as needed to keep 
elements valid. Thus for simple geometries, the only edges that would be 
curved would be ones on the curved boundaries. We also started some work 
that takes that as a starting mesh and improves the geometric 
approximation of the curved mesh entities on the boundary.

We could try so test cases to see if you like the meshes and if yet, we 
can get stuff integrated to feed them into MFEM (poerions of that are 
already underway).

Mark

**Comment by tzanio** [comment]
Hi Sander,

To add to Mark's answer -- mfem does not support currently mesh elements of different order (this has to do with the representation of the nodes as a grid function, and the fact that we don't have finite element spaces of varying p). It will certainly be a good feature to add though...

Tzanio

**Comment by MarkShephard** [comment]
I would like to more clearly understand the answer here.

In particular, I do not know exactly what you mean when you say: "mfem 
does not support currently mesh elements of different order".

I see question at two level, but I first need to start with what to me 
tends to be a basic: when saying the order to me there is the order of 
geometric representation of the element and the other is the order of 
the finite element basis. Some comments related to this issues:

  * I do look at them as two different things.
  * If you geometry order can be low (like element well insider material
    regions being straight sided - the geometric Jacobians are simpler
    (constant for simplex elements, and if I recall pretty much needed
    for pyramids) so you could take advantage of that.
  * Basic theory says that one should be iso- or sub-parametric, but
    p-version it is not that uncommon for p-version people to go
    super-parametric when you get to high order.
  * In the interior of material domains one has lots of freedom on shape
    and may want to simplify it as much as possible.
  * On fixed curved boundaries you have to track your level of geometric
    approximation to be sure you are not loosing convergence rate due to
    geometric approximation error. On evolving geometric boundaries you
    want to also consider the level of geometric representation you
    want, although I am not sure there is any specific theory on what
    one should do - I would assume the safe bet of an equal order.
  * We have found it is often desirable to use different basis for the
    element geometric shape than that used for the finite element basis

The other aspect of the different order question is the variation of 
order from element to element in the domain. One can go to all sorts of 
options. The attached paper has one pretty extreme option (I am not 
specifically recommending this - just pointing it out.)

Mark

**Comment by rhebergens** [comment]
Thanks for the responses. Our goal is similar to the points pointed out by Mark. We want to use a high order polynomial approximation for flow around curved boundaries (e.g. airfoils) and as mentioned by Mark, the approximation of the boundary should probably be of equal order as the FEM polynomial approximation. We want to combine this with evolving geometric boundaries. Due to the time-dependent meshes we want to use standard simplices on interior elements and just use curved elements near the boundary.
We don't have the Simmetrix mesh generator - we're currently using either gmsh or netgen.

Sander

**Comment by MarkShephard** [comment]
In addition to having superior curved meshing capabilities, the 
Simmetrix mesh generators have very powerful boundary layer (including 
prismatic elements in the boundary layer) capabilities - Many of the 
boundary layer capabilities have been developed to meet Ken Jansen 
requirements and we have done curved boundary layer creation (see attached).

Universities can get Simmetrix lincenses for free and labs can get them 
for a very low price. I should they can also generate very large meshes 
in parallel and we have mesh CAD modes on up to 2000 cores of Blue 
Gene/Q. Their tools are API driven components  so we have integrated 
lots of stuff with combinations of their tools and ours.

**Comment by tzanio** [comment]
Hi @MarkShephard,

We are totally in agreement about separating the order of the mesh (geometry mapping) from the order of the approximation space (finite element basis). In fact we can have many finite element spaces of different orders and types (H1, H(curl), H(div), L2) on the same mesh.

My statement was about _variation of order from element to element in the domain_. We can certainly have high-order elements that happen to be low-order in the interior, etc. but the code is not currently optimized for that and will perform the same operations as for a generic high-order element... 

Sander is your question about performance (saving work on the linear element in the interior) or about how to setup a mesh that transitions from linear to curved elements (regardless of the cost)?

Tzanio

**Comment by rhebergens** [comment]
Hi Tzanio,

Currently we are interested in how to set up the mesh, for example, flow past a cylinder. 

I'm happy to hear that it is possible to have linear elements on the interior and curved elements only at the boundary (even though not optimal). We are working on how to deform the grid in a time dependent domain and only really want to deal with curved edges near a boundary. Eventually we'll want performance when going to 3D, but currently we're still only in 2D trying to figure out the algorithms.

Simmetrix looks interesting. Unfortunately the attachments haven't been coming through. Mark, do you maybe have links to the papers?

Sander

**Comment by MarkShephard** [comment]
papers can be found at https://www.scorec.rpi.edu/~shephard/mesh/

**Comment by gsosajones** [comment]
Hi Tzanio.

I'm currently working with Sander. It's good to know that we can have linear elements on the interior and curved elements at the boundary.
What we would like to know is how set up the mesh file in one of mfem's formats for a mesh with the characteristics we have described. 

Thank you!

Giselle

**Comment by tzanio** [comment]
Hi Giselle,

I hope we are talking about the same thing... as I said if the elements are linear we will still describe them as high-order (the same way a linear function can be represented as a high-order polynomial), so it is not clear to me what the benefit will be...

In terms of defining the mesh -- you can use NetGEN for 2nd order tets or CUBIT for 2nd order hexes. Maybe we can help with this if you describe the geometry to us?

Hope this helps,
Tzanio

**Comment by tzanio** [comment]
Hi Giselle, were you able to make any progress on this issue?

**Comment by rhebergens** [comment]
Hi Tzanio,
We are still trying to figure some things out in our own codes, separate from MFEM. With the term just finishing we hope to make more progress now during the summer and combine our codes with MFEM.
Thanks, Sander

**Comment by tzanio** [comment]
Sounds good Sander, let us know if you need any help. -Tzanio

**Comment by tzanio** [comment]
I'm closing this issue. Feel free to reopen if you have any further questions.
