### ISSUE TITLE
GridFunction::SaveVTK and L2 fields

### ISSUE THREAD

**Issue by mortezah** [mfem/mfem#1461]
By looking at the code for `GridFunction::SaveVTK`, it seems that the grid function's data will always be saved as point-data in vtk format (independent of the finite element space). I know that ParaView supports cell data. Is there functionality to choose how the output vtk is made? 

For example, if I have a grid function of L2 type with order 0, can I get a vtk file with cell data (where each cell's value is the dof value associated with the corresponding element in my grid function)?

**Comment by pazner** [comment]
I don't believe that MFEM has an option to output cell data instead of point data. However, you can use ParaView's "Point Data to Cell Data" filter to convert point data to cell data. This should give the desired results for L2 finite element space with order 0.
