### ISSUE TITLE
Remove embedded elements and update mesh

### ISSUE THREAD

**Issue by Aerokaur** [mfem/mfem#1464]
Hello,
I am trying to implement an immersed-boundary/cut-element method.  For example, I have a circle embedded in a square domain. Since the mesh is needed only on a subset of the square domain, is there a way to find mesh elements that completely lie inside the circle and delete them? (with the mesh connectivity and element numbering being updated appropriately).
Thanks
Sharan

**Comment by tzanio** [comment]
Hi Sharan,

Unfortunately there is no such functionality in the master branch.

One could hack it by creating a parallel mesh on two processors where the circle elements belong to processor 0 and the rest to processor 1. The local mesh on processor 1 is what you want.

You can examine the parallel mesh constructor code and add the functionality yourself. Maybe one of our users or developers have already done so? cc: @mlstowell, @sshiraiwa 

Tzanio

**Comment by Aerokaur** [comment]
Thanks @tzanio 
Currently, we have a workaround that sets identity bilinear form for immersed elements. Let's see how it ends up. However, I would love to know if someone has already done what you proposed. 
Sharan

**Comment by mlstowell** [comment]
Hi, @Aerokaur ,

The closest thing I have is [trimmer](https://github.com/mfem/mfem/blob/mesh-trimmer-dev/miniapps/meshing/trimmer.cpp) which removes elements tagged with a certain set of attribute numbers.  It would be convenient to have a small group of tools to edit meshes in this way but we don't have this yet.

Best wishes,
Mark

**Comment by Aerokaur** [comment]
Thanks @mlstowell 
That's helpful. I will give it a try.
Sharan
