### ISSUE TITLE
Segmentation Fault With Multiple Runs Using ProjectCoefficient 

### ISSUE THREAD

**Issue by dustin-bielecki** [mfem/mfem#1465]
Hey,

I am using MFEM in a topology optimization framework but am running into a segmentation fault error after many iterations of calling MFEM. This will happen for a different number of iterations given different cases we are trying to solve but will always happen even if I call the same case many times. Below is a short section of the code..

Note that I'm applying a displacement at a node.

```c++
   if (YDisp.size() != 0)               //displacement in Y Direction.  
   {  
       Vector disp_Y_value(dim);  
       Array<int> NodeDispYProj(int (1));  
       //int num_oned_dofs = fespace->GetVSize() / dim;  
       for (int i=0; i < (YDisp.size()); i++)  
       {  
           NodeDispYProj[0] = NodeDispY[i];  
           disp_Y_value[1] = YDisp[i];  // Assigned values for disp. BC. in Y direction.  
           VectorConstantCoefficient disp_Y_value_coeff(disp_Y_value);  
           x.ProjectCoefficient(disp_Y_value_coeff,NodeDispYProj);  
           // Appending Disp. BC node numbers to ess_tdof_list.  
           ess_tdof_list.Append(NodeDispY[i]);  
       }  
   }  
```

The segmentation fault always occurs on this line:
```c++
   x.ProjectCoefficient(disp_Y_value_coeff,NodeDispYProj);
```

**Comment by mlstowell** [comment]
Hi, @dustin-bielecki ,
A segmentation fault on that line would seem to indicate that the degree of freedom number passed via `NodeDispYProj` may be invalid.  Do you have a stack trace which might show if the segfault is occurring in `GridFunction::ProjectCoefficient` or perhaps deeper within MFEM?

One other issue, which probably wouldn't lead to a segfault, is that the vector `disp_Y_value` is not being fully initialized.  Its `y` component is being set but its other entries could be anything.  You should explicitly include `disp_Y_value = 0.0;` before your loop.

Best wishes,
Mark

**Comment by tzanio** [comment]
To add to Mark's answer, another possible source of problem could be that the finite element space for `x` got updated or some of its components (e.g. the mesh) got deleted.

What changes between the different calls to these code? Do you use for example adaptive mesh refinement?

**Comment by tzanio** [comment]
@dustin-bielecki, were you able to resolve this issue?
