### ISSUE TITLE
Did the DOI for MFEM change?

### ISSUE THREAD

**Issue by delyank** [mfem/mfem#1466]
Because the one posted on the website (10.11578/dc.20171025.1248) doesn't seem to be valid.

**Comment by rcarson3** [comment]
Based on the [DOE CODE website](https://www.osti.gov/doecode/biblio/34658), it looks like it's now doi: 10.11578/dc.20200303.5

**Comment by tzanio** [comment]
Dang it! This was not intentional 😟 

@acfisher, I think it is probably because of the review we needed to do for mfem-4.1 in our internal system.

You can use 10.11578/dc.20200303.5 for mfem-4.1 specifically, but let me see if I can get DOE CODE to restore 10.11578/dc.20171025.1248...

Tzanio

**Comment by tzanio** [comment]
The original DOI is back at https://www.osti.gov/doecode/biblio/35738

Thanks for reporting this.
