### ISSUE TITLE
CalcHessian for H1_SegmentElement, H1_QuadrilateralElement, and H1_HexahedronElement

### ISSUE THREAD

**Issue by aschaf** [mfem/mfem#1467]
Hi,

I implemented `CalcHessian` for said finite elements, however only for `Basis::Barycentric`. Is this enough for a pull request or should we also implement it for `Basis::Positive` and `Basis::ChangeOfBasis`?

Best regards,
Andreas

**Comment by v-dobrev** [comment]
I think the `Barycentric` case is a good start. The other cases can be added later when needed.

**Comment by tzanio** [comment]
Agreed.

**Comment by tzanio** [comment]
Discussion continued in #1474
