### ISSUE TITLE
Unexpected behavior when using 1D elements

### ISSUE THREAD

**Issue by termi-official** [mfem/mfem#1469]
Hi guys,

I am trying to setup a minimum working example for solving PDEs on networks in 3D space, i.e. elements are segments with 3D coordinates. However, I am constantly running into weird error messages and have trouble tracking them down.

I stripped my test program down to the following one:
```cpp
#include <mfem.hpp>

int main(int argc, char** argv)
{
    using namespace mfem;

    // 1. Initialize MPI.
    MPI_Session mpi(argc, argv);

    if (mpi.Root())
    {
#ifdef MFEM_DEBUG
        std::cout << "Debug mode on." << std::endl;
#endif
    }

    // 2. Read options from command line
    int order                  = 1;
    const char* mesh_file_name = "";

    OptionsParser args(argc, argv);
    args.AddOption(&mesh_file_name, "-m", "--mesh", "Mesh file.");
    args.AddOption(&order, "-o", "--order",
                   "Finite element order (polynomial degree).");
    args.Parse();

    if (!args.Good())
    {
        if (mpi.Root())
        {
            args.PrintUsage(std::cout);
        }
        return 1;
    }
    if (mpi.Root())
    {
        args.PrintOptions(std::cout);
    }

    // 3. Setup mesh
    auto mesh  = new Mesh(mesh_file_name, 1, 1);
    auto pmesh = new ParMesh(MPI_COMM_WORLD, *mesh);

    // 4. Setup FE space
    auto fec      = new H1_FECollection(order, 1);
    auto pfespace = new ParFiniteElementSpace(pmesh, fec);

    // 5. Print the global vector size
    auto vsize = pfespace->GlobalVSize();
    if (mpi.Root())
    {
        std::cout << "Global VSize: " << vsize << std::endl;
    }

    // 6. Cleanup
    delete pfespace;
    delete fec;
    delete pmesh;
    delete mesh;

    return 0;
}
```

My first test mesh is a simple tree with one fork at the third vertex
```
  |
  |
 / \
 |
```
for which I wrote the following mesh file (network-test-1.mesh)
```
MFEM mesh v1.0

dimension
1

elements
5
1 1 0 1
1 1 1 2
1 1 2 3
1 1 2 4
1 1 4 5

boundary
3
1 0 0
2 0 3
2 0 5

vertices
6
3
0 0 0
1.0 0 0
2.0 0 0
3.0 1.0 0
3.0 -1.0 0
4.0 -1.0 0
```

Now, running my program with one process gives the expected output for any order, but trying the same with two processes gives yields in a strange METIS error:
```bash
mpirun -np 2 src/network-test -m ../data/meshes/network-test-1.mesh -o 2
```
```
Debug mode on.
Options used:
   --mesh ../data/meshes/network-test-1.mesh
   --order 2
METIS Error: A contiguous partition is requested for a non-contiguous input graph.



Mesh::GeneratePartitioning:  error in METIS_PartGraphKway!
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 1 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
METIS Error: A contiguous partition is requested for a non-contiguous input graph.



Mesh::GeneratePartitioning:  error in METIS_PartGraphKway!
[...] [[56991,0],0] ORTE_ERROR_LOG: Data unpack had inadequate space in file util/show_help.c at line 513
```

Trying to understand what is going wrong I also tried to go one step back to simply having a line mesh (network-test-2.mesh) 
```
MFEM mesh v1.0

dimension
1

elements
4
1 1 0 1
1 1 1 2
1 1 2 3
1 1 3 4

boundary
2
1 0 0
2 0 4

vertices
5
3
0 0 0
1.0 0 0
2.0 0 0
3.0 0.0 0
4.0 0.0 0
```

~~Here again, using one process seem to work, but using two processes the program seem to get stuck in an infinite loop.~~
```bash
mpirun -np 2 src/test-purkinje -m ../data/meshes/network-test-2.mesh -o 2
```
```
Debug mode on.
Options used:
   --mesh ../data/meshes/network-test-2.mesh
   --order 2
Mesh::GeneratePartitioning(...): edgecut = 1
```
_Edit: This was an issue with the code sample above, which I have fixed now._

Is this some known issue?

Best regards,
Dennis

**Comment by tzanio** [comment]
I don't believe we currently support 1D meshes in 3D... @v-dobrev, can you confirm?

**Comment by termi-official** [comment]
Hi tzanio, 
I just finished implementing a serial version of my reaction diffusion solver on the meshes above and they seem to work. So, at least the numerical entries of the solution vector look reasonable, since glvis crashes when loading the mesh (mesh-explorer as well).

Imposing a manual partitioning allows me to run the program above with the mesh with the branch.

```cpp
    // [...]
    // 3. Setup mesh
    auto mesh  = new Mesh(mesh_file_name, 1, 1);
    int partitioning[] = {0,0,0,1,1};
    auto pmesh = new ParMesh(MPI_COMM_WORLD, *mesh, partitioning);
    // [...]
```
via 
```bash
mpirun -np 2 src/test-purkinje -m ../data/meshes/network-test-1.mesh -o 2
```

**Comment by termi-official** [comment]
Tracking down the problem I figured out that some faces in this "weird" meshes are ignored in the current mesh class implementation. Note that when the dimension of the finite element is strictly smaller than the dimension of the physical space,  e.g. 1D elements in 3D space, then we can can have some weird faces, e.g. on branching points. Since  faces are modeled 1-to-1 between elements, the number of faces may exceed the number of vertices for the embedded 1D elements. This renders the following computations problematic 
* https://github.com/mfem/mfem/blob/e559d93b5faa1b0fd75cd6fd630af0dd4aa4f990/mesh/mesh.cpp#L3970-L3979
* https://github.com/mfem/mfem/blob/e559d93b5faa1b0fd75cd6fd630af0dd4aa4f990/mesh/mesh.cpp#L5132-L5138
Now, since the element to element table is computed from the faces, the element to element topology is also wrong, disconnecting the domain, which leads to the error messages above. Having 2D elements in 3D can lead to the same problem, as well as having 1D elements in 2D, for the same reasons as stated above. 

Fixing the element to element table in the Mesh before constructing the ParMesh resolves the error message and solving a reaction diffusion problem on with this ParMesh converges to something at least plausible, i.e. the solution is a traveling wave from one boundary to every other boundary, no matter how many processes I throw at the program. 
Since the testing infrastructure is not yet setup up completely for the mesh classes, I have not found a proper way to test how good this hotfix works (the face table is still broken). So, is the face information for 1D elements at some point explicitly necessary, when simply solving a diffusion problem (similar to ex1p) on this weird mesh?

**Comment by v-dobrev** [comment]
Yes, some parts of MFEM do not work correctly with branching meshes like this, i.e. meshes where (d-1)-dimensional "faces" are adjacent to more than two d-dimensional elements in a d-dimensional mesh embedded in a higher-dimensional space.

I think example 1/1p may be okay, except for the element-element table issue you encountered. This table (used mainly for partitioning the mesh using METIS) can be constructed without using the `faces_info` array in the `Mesh` (this array is one of the data structures that assumes at most 2 adjacent elements for each face). For example, in 1D, one can multiply the element-vertex table with the vertex-element table (removing the diagonal, as needed by METIS).

An example of something that will not work with such meshes is any DG method.

**Comment by termi-official** [comment]
Thanks for the info!

Not the most elegant or performant solution, but I just rewired the complete element to element table. I leave my hotfix here for future references.
```cpp

class NetworkMesh : public Mesh
{
public:
    NetworkMesh(const char* filename)
        : Mesh(filename, 1, 1)
    {}

    void FixTables()
    {
        // This one seems to be fine, so we use it for reconstructing the the
        // element to element topology
        auto v2el = Mesh::GetVertexToElementTable();

        // Delete broken element to element table if it exists
        if (el_to_el)
        {
            delete el_to_el;
        }

        // This serves as the new element to element table. Start by allocating
        // some data to prevent excessive allocations while constructing the
        // connectivity.
        Array<Connection> conn;
        conn.Reserve(2 * faces_info.Size());

        // Just go over the vertices and store the element to element
        // connections.
        for (int v = 0; v < GetNV(); v++)
        {
            Array<int> v2el_row;
            v2el->GetRow(v, v2el_row);

            for (auto e1 : v2el_row)
            {
                // Skip non-owned elements
                if (e1 == -1)
                {
                    continue;
                }

                for (auto e2 : v2el_row)
                {
                    // Skip non-owned elements
                    if (e2 == -1)
                    {
                        continue;
                    }

                    // Do not connect to itself
                    if (e1 == e2)
                    {
                        continue;
                    }

                    conn.Append(Connection(e1, e2));
                }
            }
        }

        // Setup the fixed table.
        conn.Sort();
        conn.Unique();
        el_to_el = new Table(NumOfElements, conn);
    }
};
```
I call FixTables right before constructing the ParMesh.

Since my problem seem to be solved by this I close this issue and may open it again when running into something which I cannot track down on my own. Thanks again!
