### ISSUE TITLE
Use BlockLowerTriangularPreconditioner for HypreSolver

### ISSUE THREAD

**Issue by William-byte365** [mfem/mfem#1470]
Hello, 

The `HypreSolver` like `HypreGMRES` only accepts a `HypreSolver` as the `precond.`  How to 
use `BlockLowerTriangularPreconditioner` for `HypreSolver` . Currently, `BlockLowerTriangularPreconditioner` can only be applied with MFEM `IterativeSolver`.

William

**Comment by tzanio** [comment]
Hi William,

Hypre does not support general preconditioners like this, so you can not use a lower triangular one with a hypre solver.

That being said, the MFEM iterative methods are essentially the same, so I'd recommend just using `GMRESSolver`.

Hope this helps,
Tzanio

**Comment by William-byte365** [comment]
Ok, I will use MFEM solvers.
