### ISSUE TITLE
Parallel difference 

### ISSUE THREAD

**Issue by yantingsa** [mfem/mfem#1471]
Hi mfem works,

I'm testing a simple diffusion reaction problem. And the weird thing is I'm using the exact same code running on both my laptop and workstation, the code running correct on workstation while they keep having '-nan' on my laptop. Wondering do you guys have any ideas?

Best,
Ting

**Comment by tzanio** [comment]
Can you provide more details about the code and how you build it and run it on the two machines?

Are you able to run similar MFEM examples succesfully?

**Comment by mlstowell** [comment]
Hi, @yantingsa ,

The usual cause of this type of behavior is failure to initialize vectors to 0.  The MFEM `Vector`, `GridFunction`, and `LinearForm` classes do not initialize themselves to zero.  Some compilers will initialize newly allocated memory to zero for you, others will not. Some MFEM member functions will initialize these objects to zero before performing their task but others will not.  For example, `LinearForm::Assemble` will first initialize the object to zero, `GridFunction::ProjectCoefficient` will initialize to zero but `GridFunction::ProjectBdrCoefficient` will not.

Best wishes,
Mark

**Comment by yantingsa** [comment]
Hi @tzanio 

Here is my code

`#include "mfem.hpp"
#include <fstream>
#include <iostream>

#include "sys_reaction.hpp"
//#include "par_sys_precond.hpp"

using namespace std;
using namespace mfem;

const double a12 = 1.0;
const double a21 = -1.0;
const double chi = 0.0;


double rhs_f(const Vector &r);
double rhs_g(const Vector &r);

double analytic_v(const Vector &r);
double analytic_m(const Vector &r);


class Block_Diff_Reac_Operator : public Operator
{
private:
  // Finite element spaces
  Array<ParFiniteElementSpace *> fes;

  Array<int> &block_sets;
  Array<int> &block_true_sets;

  // linear form
  ParLinearForm *f_rhs;
  ParLinearForm *g_rhs;

  // bilinear form and nonlinear form
  ParBilinearForm *diff_form_v, *diff_form_m;
  ParBlockNonlinearForm *reac_form_vm;
  ParMixedBilinearForm *chemo;

  HypreParMatrix *diff_mat_v, *diff_mat_m;
  HypreParMatrix *chemo_mat;

  NewtonSolver newton_solver;

  Solver *j_solver;

  Solver *j_prec;

  BlockOperator *Residual;
  BlockVector rhs, true_rhs;

  Coefficient &coeff12, &coeff21;
  mutable BlockOperator *Jacobian;
  Array<int> &ess_tdof_list_v;
  Array<int> &ess_tdof_list_m;
  mutable Vector w, z;

public:
  Block_Diff_Reac_Operator(Array<ParFiniteElementSpace *> space, Array<Array<int> *> &ess_bdr,
                           Array<int> &block, Array<int> &block_true,
                           BlockVector &u, BlockVector &u_true,
                           Coefficient &cf12, Coefficient &cf21);

  virtual Operator &GetGradient(const Vector &vm) const;
  virtual void Mult(const Vector &k, Vector &y) const;

  void Solve(Vector &vm) const;

  virtual ~Block_Diff_Reac_Operator();
};


int main(int argc, char *argv[])
{
  // 1. Initialize MPI
  int num_procs, myid;
  MPI_Init(&argc, &argv);
  MPI_Comm_size(MPI_COMM_WORLD, &num_procs);
  MPI_Comm_rank(MPI_COMM_WORLD, &myid);

//  const char *mesh_file = "../mesh/square.msh";
  const char *mesh_file = "../mesh/box.msh";
  int order = 1;
  int ser_ref_levels = 1;
  int par_ref_levels = 0;
  bool visualization = true;

  int precision = 8;
  cout.precision(precision);

  OptionsParser args(argc, argv);
  args.AddOption(&ser_ref_levels, "-rs", "--refine_serial",
                 "Number of times to refine the mesh uniformly.");
  args.AddOption(&par_ref_levels, "-rp", "--refine_parallel",
                 "Number of times to refine the mesh uniformly.");
  args.AddOption(&order, "-o", "--order",
                 "Order (degree) of the finite elements.");
  args.AddOption(&visualization, "-vis", "--visualization", "-no-vis",
                 "--no-visualization",
                 "Enable or disable GLVis visualization.");

  args.Parse();
  if(!args.Good())
  {
    if(myid == 0)
    {
      args.PrintUsage(cout);
    }
    MPI_Finalize();
    return 1;
  }
  if(myid == 0)
  {
    args.PrintOptions(cout);
  }


  Mesh *mesh = new Mesh(mesh_file, 1, 1);
  int dim = mesh->Dimension();

  for(int lev=0; lev<ser_ref_levels; lev++)
  {
    mesh->UniformRefinement();
  }

  ParMesh *pmesh = new ParMesh(MPI_COMM_WORLD, *mesh);
  delete mesh;

  for (int l = 0; l < par_ref_levels; l++)
  {
     pmesh->UniformRefinement();
  }

  H1_FECollection fe_coll(order, dim);

  ParFiniteElementSpace v_space(pmesh, &fe_coll);
  ParFiniteElementSpace m_space(pmesh, &fe_coll);

  Array<ParFiniteElementSpace *> spaces(2);
  spaces[0] = &v_space;
  spaces[1] = &m_space;

  HYPRE_Int v_size = v_space.GlobalTrueVSize();
  HYPRE_Int m_size = m_space.GlobalTrueVSize();

  Array<Array<int> *> ess_bdr(2);
  Array<int> ess_bdr_v(v_space.GetMesh()->bdr_attributes.Max());
  Array<int> ess_bdr_m(m_space.GetMesh()->bdr_attributes.Max());
  ess_bdr_v = 1;                          ess_bdr_m = 1;
  ess_bdr[0] = &ess_bdr_v;                ess_bdr[1] = &ess_bdr_m;

  if(myid == 0)
  {
    std::cout << "********************************************************\n";
    std::cout << "dim(v) = " << v_size << "\n";
    std::cout << "dim(m) = " << m_size << "\n";
    std::cout << "dim(v+m) = " << v_size + m_size << "\n";
    std::cout << "********************************************************\n";
  }


  Array<int> block_offsets(3);
  block_offsets[0] = 0;
  block_offsets[1] = v_space.GetVSize();
  block_offsets[2] = m_space.GetVSize();
  block_offsets.PartialSum();

  Array<int> block_trueOffsets(3);
  block_trueOffsets[0] = 0;
  block_trueOffsets[1] = v_space.TrueVSize();
  block_trueOffsets[2] = m_space.TrueVSize();
  block_trueOffsets.PartialSum();

  BlockVector vm(block_offsets), vm_true(block_trueOffsets);

  FunctionCoefficient exact_v(analytic_v);
  FunctionCoefficient exact_m(analytic_m);

  ParGridFunction v_gf(&v_space);
  ParGridFunction m_gf(&m_space);
  v_gf.MakeRef(&v_space, vm.GetBlock(0), 0);
  v_gf.ProjectCoefficient(exact_v);
  v_gf.SetTrueVector();
  v_gf.SetFromTrueVector();
  m_gf.MakeRef(&m_space, vm.GetBlock(1), 0);
  m_gf.ProjectCoefficient(exact_m);
  m_gf.SetTrueVector();
  m_gf.SetFromTrueVector();

  ConstantCoefficient c12(1.0);
  ConstantCoefficient c21(-1.0);
  Block_Diff_Reac_Operator oper(spaces, ess_bdr, block_offsets, block_trueOffsets,
    vm, vm_true, c12, c21);
  oper.Solve(vm_true);

  v_gf = vm.GetBlock(0);
//  v_gf.Distribute(&(vm.GetBlock(0)));
  m_gf = vm.GetBlock(1);
//  m_gf.Distribute(&(vm.GetBlock(1)));

  int order_quad = max(2, 2*order+1);
  const IntegrationRule *irs[Geometry::NumGeom];
  for(int i=0; i<Geometry::NumGeom; ++i)
  {
    irs[i] = &(IntRules.Get(i, order_quad));
  }

  double err_v = v_gf.ComputeL2Error(exact_v, irs);
  double norm_v = ComputeLpNorm(2., exact_v, *pmesh, irs);
  double err_m = m_gf.ComputeL2Error(exact_m, irs);
  double norm_m = ComputeLpNorm(2., exact_m, *pmesh, irs);

  if(myid == 0)
  {
    std::cout << "||v_h - v_ex|| = " << err_v << "\n";
    std::cout << "||v_h - v_ex|| / || v_ex || = " << err_v / norm_v << "\n";
    std::cout << "||m_h - m_ex|| = " << err_m << "\n";
    std::cout << "||m_h - m_ex|| / || m_ex || = " << err_m / norm_m << "\n";
  }

  delete pmesh;

  MPI_Finalize();
  return 0;
}


Block_Diff_Reac_Operator::Block_Diff_Reac_Operator(Array<ParFiniteElementSpace *> space,
                                       Array<Array<int> *> &ess_bdr,
                                       Array<int> &block, Array<int> &block_true,
                                       BlockVector &u, BlockVector &u_true,
                                       Coefficient &cf12, Coefficient &cf21)
    : Operator(space[0]->TrueVSize() + space[1]->TrueVSize()),
      block_sets(block), block_true_sets(block_true),
      newton_solver(space[0]->GetComm()), fes(space),
      Jacobian(NULL), Residual(NULL), rhs(block), true_rhs(block_true),
      coeff12(cf12), coeff21(cf21),
      ess_tdof_list_v(*ess_bdr[0]), ess_tdof_list_m(*ess_bdr[1]),
      w(height), z(height)
{
  FunctionCoefficient forcing_f(rhs_f);
  f_rhs = new ParLinearForm(fes[0]);
  f_rhs->Update(fes[0], rhs.GetBlock(0), 0);
  f_rhs->AddDomainIntegrator(new DomainLFIntegrator(forcing_f));
  f_rhs->Assemble();
  f_rhs->ParallelAssemble(true_rhs.GetBlock(0));

  FunctionCoefficient forcing_g(rhs_g);
  g_rhs = new ParLinearForm(fes[1]);
  g_rhs->Update(fes[1], rhs.GetBlock(1), 0);
  g_rhs->AddDomainIntegrator(new DomainLFIntegrator(forcing_g));
  g_rhs->Assemble();
  g_rhs->ParallelAssemble(true_rhs.GetBlock(1));

  diff_form_v = new ParBilinearForm(fes[0]);
  diff_form_v->AddDomainIntegrator(new DiffusionIntegrator());
  diff_form_v->Assemble(0);
  diff_form_v->EliminateEssentialBC(*ess_bdr[0], u.GetBlock(0), rhs.GetBlock(0));
  diff_form_v->Finalize();
  diff_mat_v = diff_form_v->ParallelAssemble();

  diff_form_m = new ParBilinearForm(fes[1]);
  diff_form_m->AddDomainIntegrator(new DiffusionIntegrator());
  diff_form_m->Assemble(0);
  diff_form_m->EliminateEssentialBC(*ess_bdr[1], u.GetBlock(1), rhs.GetBlock(1));
  diff_form_m->Finalize();
  diff_mat_m = diff_form_m->ParallelAssemble();

  // chemotaxis term
  ParGridFunction m_coeff(fes[1]);
  m_coeff.SetFromTrueDofs(u.GetBlock(1));
  for(int i = 0; i < m_coeff.Size(); i++)
  {
    m_coeff(i) *= 1.0*chi;
  }
  GridFunctionCoefficient chemo_coeff(&m_coeff);
  chemo = new ParMixedBilinearForm(fes[1], fes[0]);
  chemo->AddDomainIntegrator(new DiffusionIntegrator(chemo_coeff));
  chemo->Assemble(0);
  chemo->Finalize();
  chemo_mat = chemo->ParallelAssemble();

//  ConstantCoefficient cf12(a12), cf21(a21);
  reac_form_vm = new ParBlockNonlinearForm(fes);
  reac_form_vm->AddDomainIntegrator(new Sys_ReactionNLFIntegrator(coeff12, coeff21));

  Residual = new BlockOperator(block_true_sets);
  Residual->SetBlock(0, 0, diff_mat_v);
  Residual->SetBlock(1, 1, diff_mat_m);
//  Residual->SetBlock(1, 0, chemo_mat);


  // Initialize the block diagonal preconditioner
  Block_Diagonal_Preconditioner *block_diag_prec =
    new Block_Diagonal_Preconditioner(fes, block_sets,
                                      *diff_mat_v, *diff_mat_m);
  j_prec = block_diag_prec;

  HypreSolver *inv_v, *inv_m;
  inv_v = new HypreBoomerAMG(*diff_mat_v);
  inv_m = new HypreBoomerAMG(*diff_mat_m);

  inv_v->iterative_mode = false;
  inv_m->iterative_mode = false;


  BlockDiagonalPreconditioner *block_prec = new BlockDiagonalPreconditioner(
    block_true);
  block_prec->SetDiagonalBlock(0, inv_v);
  block_prec->SetDiagonalBlock(1, inv_m);

  // set up the Jacobian solver
  GMRESSolver *j_gmres = new GMRESSolver(fes[0]->GetComm());
  j_gmres->iterative_mode = false;
  j_gmres->SetRelTol(1e-12);
  j_gmres->SetAbsTol(1e-12);
  j_gmres->SetMaxIter(300);
  j_gmres->SetPrintLevel(1);
  j_gmres->SetPreconditioner(*block_prec);
  j_solver = j_gmres;

  newton_solver.iterative_mode = true;
  newton_solver.SetSolver(*j_solver);
  newton_solver.SetOperator(*this);
  newton_solver.SetPrintLevel(1);
  newton_solver.SetRelTol(1e-8);
  newton_solver.SetAbsTol(1e-10);
  newton_solver.SetMaxIter(100);

}

// solve the Newton system
void Block_Diff_Reac_Operator::Solve(Vector &u) const
{
//  Vector zero;
  newton_solver.Mult(true_rhs, u);
  MFEM_VERIFY(newton_solver.GetConverged(),
              "Newton Solver did not converge.");
}

// compute: y = Dx + H(x)
void Block_Diff_Reac_Operator::Mult(const Vector &k, Vector &y) const
{
//  Vector z;
  reac_form_vm->Mult(k, y);
  Residual->Mult(k, w);
  y += w;
}

Operator &Block_Diff_Reac_Operator::GetGradient(const Vector &u) const
{
  delete Jacobian;
  Jacobian = new BlockOperator(block_true_sets);

  BlockOperator *grad_R = dynamic_cast<BlockOperator *>(&reac_form_vm->GetGradient(u));

  HypreParMatrix *reac_11 = dynamic_cast<HypreParMatrix *>(&grad_R->GetBlock(0, 0));
  HypreParMatrix *reac_22 = dynamic_cast<HypreParMatrix *>(&grad_R->GetBlock(1, 1));
  HypreParMatrix *reac_12 = dynamic_cast<HypreParMatrix *>(&grad_R->GetBlock(0, 1));
  HypreParMatrix *reac_21 = dynamic_cast<HypreParMatrix *>(&grad_R->GetBlock(1, 0));


  BlockOperator grad_localR = (reac_form_vm->GetLocalGradient(u));

  SparseMatrix *localJ00 = dynamic_cast<SparseMatrix *>(&grad_localR.GetBlock(0, 0));
  localJ00->Add(1.0, diff_form_v->SpMat());
  HypreParMatrix *J_00 = diff_form_v->ParallelAssemble(localJ00);
  Jacobian->SetBlock(0, 0, J_00);

  SparseMatrix *localJ11 = dynamic_cast<SparseMatrix *>(&grad_localR.GetBlock(1, 1));
  localJ11->Add(1.0, diff_form_m->SpMat());
  HypreParMatrix *J_11 = diff_form_m->ParallelAssemble(localJ11);
  Jacobian->SetBlock(1, 1, J_11);

  Jacobian->SetBlock(0, 1, reac_12);
  Jacobian->SetBlock(1, 0, reac_21);

  return *Jacobian;

}

Block_Diff_Reac_Operator::~Block_Diff_Reac_Operator()
{
  delete f_rhs;
  delete g_rhs;
  delete Jacobian;
  delete j_solver;
  delete diff_form_v;
  delete diff_form_m;
  delete diff_mat_v;
  delete diff_mat_m;
  delete reac_form_vm;
 // delete j_prec;
}


double rhs_f(const Vector &r)
{
  double x = r(0);
  double y = r(1);
  double z = r(2);

  double v = sin(x) * sin(y) * sin(z);
  double m = cos(x) * cos(y) * cos(z);

//  return 2.0*v + v*m;
//  return v*m;
  return 3.0 * v + v*m;
}

double rhs_g(const Vector &r)
{
  double x = r(0);
  double y = r(1);
  double z = r(2);

  double v = sin(x) * sin(y) * sin(z);
  double m = cos(x) * cos(y) * cos(z);

//  return 2.0*m - v*m;
//  return v*m;
//  double chemo_cf = -6*v*m;

//  return 3.0 * m - v*m + chi*chemo_cf;
  return 3.0 * m - v*m;
}


double analytic_v(const Vector &r)
{
  double x = r(0);
  double y = r(1);
  double z = r(2);

//  return sin(x) * sin(y);
  return sin(x) * sin(y) * sin(z);
}

double analytic_m(const Vector &r)
{
  double x = r(0);
  double y = r(1);
  double z = r(2);

//  return cos(x) * cos(y);
  return cos(x) * cos(y) * cos(z);
}
`

My laptop and workstation are install mfem@4.0.1-xsdk via spack and built with same makefile. I use mpi with openmpi@3.1.4 to run the code.

**Comment by yantingsa** [comment]
Hi @tzanio @mlstowell 

I initialized my `vm` and `vm_true` with 0 and I got it worked on my laptop. Thank you so much for help. It really helpful.
