### ISSUE TITLE
Visualizing quadrature space using VisItDataCollection

### ISSUE THREAD

**Issue by IdoAkkerman** [mfem/mfem#1477]
I am able add a quadrature space to the data collection using` RegisterQField` and at save an associated file is generated, however the mfem_root does not include a reference to the field.

Even after attempting to add the mfem_root entry manually I am not able to visualize the field in VisIt.
Any tips?? I don't mind implementing this feature, but just wanted to check if this was necessary?

**Comment by tzanio** [comment]
@kennyweiss was working on visualizing quadrature functions as point clouds, but I don't think that's currently available.

One thing you can do is to visualize the L2 grid function with the same degrees of freedom, or to L2 project in a different space.

**Comment by IdoAkkerman** [comment]
I think it would work best to subdivide the element in subdomain with a constant value on those subdomains. The size of the subdomain should be related to the integration weight.

I am just making an inventory of what is already there. I will try to have a look at the point cloud solution.

**Comment by tzanio** [comment]
That sounds reasonable.

For a Gauss-Legendre quadrature with `q` points, one can use the Gauss-Lobatto subdivision with p+1 points (the two sets of points are interleaved).

**Comment by v-dobrev** [comment]
For this to make sense on non-tensor product elements (where quadrature rules do not coincide with the nodes of an L2 FE), it will be best to visualize quadrature data by projecting onto an L2 space. For tensor product elements, the projection could be identity as long as the quadrature rule points coincide with the L2 FE nodes.

There was such projection capability in PR #1281 but we decided to postpone the projection part. In any case, I believe @rcarson3 (the author of #1281) is also interested in saving and visualizing quadrature data using one of the `DataCollection` sub-classes.

For visualization, it should be simple and relatively fast to compute a local projection matrix (from quadrature points to dofs) on the reference element and use that to transfer the data on all elements. This projection matrix can be computed similarly to this (ignoring the transformation, or using the identity transformation): https://github.com/mfem/mfem/blob/261fd7adcd8312fbe05906eb40ca87a1f9c34132/fem/fe.cpp#L820-L829

and then used to perform the projections like in this method: https://github.com/mfem/mfem/blob/261fd7adcd8312fbe05906eb40ca87a1f9c34132/fem/gridfunc.cpp#L1511

For the `mixed_mass` matrix, we can add a special method in class `MassIntegrator` that takes one `FiniteElement` and one `QuadratureRule`.

Once we have this in MFEM, I think visualization in VisIt will be relatively simple to add -- the plugins will need to be updated to read the `QuaddratureFunction`s and  convert them to `GridFunction`s.

Visualization as a point cloud may be even simpler but I don't know how this will work exactly. Maybe @cyrush or @kennyweiss can comment on that.

**Comment by kennyweiss** [comment]
Thanks @IdoAkkerman  -- this is something I have been hoping to look into for some time. It would also be really nice to be able to visualize `QFields` in glvis....

I can look into adding this capability to the `SidreDataCollection` and perhaps the `ConduitDataCollection` as well.  I'll try to find some time in the next few weeks (?)

I think the best way to get this to work would be to add a point mesh corresponding to the quadrature points, with registered `QField` values.  This will either require updating the (physical) positions of the quadrature points before writing out the file (less ideal), or having `VisIt` generate the positions of the points when it loads the file (more ideal).
Thoughts, @cyrush?

**Comment by cyrush** [comment]
I think the fastest path would be to create and provide a point mesh to VisIt. It should be quite  easy to do even as a one off - writing blueprint files or adding the point mesh to sidre. 

That said, I suspect that @v-dobrev's path to project and present the data might be yield a more usable result. 

Longer term we can think about what Visit can leverage using MFEM in our reader.

**Comment by rcarson3** [comment]
@kennyweiss I'd very much be appreciative of being able to save ```QuadratureFunction```s off within the ```SidreDataCollection``` or ```ConduitDataCollection``` as a means for restart capabilities within my own code. Although, I'm not sure if this would be different than what you have planned save the data to visualize the data sets.

**Comment by IdoAkkerman** [comment]
PR has been accepted.
