### ISSUE TITLE
Support for SLEPc eigenvalue solver

### ISSUE THREAD

**Issue by jetremblay** [mfem/mfem#1479]
Hi,
I am interested in the 2D Maxwell eigenvalue problem in dielectric waveguides (e.g. [Full-wave analysis of dielectric waveguides using tangential vector finite elements](https://ieeexplore.ieee.org/document/85399)). For this I use the SLEPc eigenvalue solver instead of LOBPCG since the matrices are not positive definite.

I currently use the existing PETSc code and then call SLEPc directly. Would there be any interest if I work on implementing a dedicated SLEPc class?

**Comment by v-dobrev** [comment]
This definitely sounds like a very useful addition. Do you have in mind support for SLEPc through PETSc or independently of PETSc? Either way, your contribution will be welcome. Feel free to create a branch directly in the MFEM repo (I'll send you an invite in a moment). Thanks!

**Comment by jetremblay** [comment]
I was thinking of creating a new class which will have the current PETSc code as a dependency (reusing PetscParMatrix and so on). I will probably start with the linear eigensolver and the spectral transformation objects.

Regarding the interface, since there is no generic eigensolver class (like there is for the regular solvers), should I take inspiration from HypreLOBPCG?

I will create a new branch and should have an example in a few days.

**Comment by v-dobrev** [comment]
If you want to, start with a separate eigensolver class trying to make it similar to HypreLOBPCG where it makes sense. Once you have that, it maybe easier to create a general eigensolver interface. However, if you prefer to start with the generic eigensolver class, that's fine too.

I think @stefanozampini (who is the author of the PETSc integration classes) and @mlstowell (who wrote the HypreLOBPCG class) may be interested to follow this new contribution as well.

Let us know if you have any questions.

**Comment by stefanozampini** [comment]
@v-dobrev SLEPc is based on PETSc.
@jetremblay It would be nice to have such an interface, and I think not so hard to implement reusing the PetscParMatrix class functionalities. I can take a look at the development once you have something working

**Comment by v-dobrev** [comment]
> @v-dobrev SLEPc is based on PETSc.

Ah, OK, I did not realize that.

**Comment by jetremblay** [comment]
I created a new branch [slepc-dev](https://github.com/mfem/mfem/tree/slepc-dev). This is still work in progress.
- There is a new `SlepcEigenSolver` class, and I added it to the build system. I tested with `cmake`, but not regular `make` yet.
- I ported ex11p.
- I created an new examples (ex28p) for the 2D maxwell eigenproblem, which is not ready yet.
- I have not finished the functionality to add an option file (similar to PETSc).

Can you let me know what you think?

**Comment by jetremblay** [comment]
https://github.com/mfem/mfem/blob/7b314b6ac9932ef7b8774afaad3b0321f368701b/linalg/petsc.cpp#L1090-L1096

Does this break anything? SLEPc seems unhappy with MatNest, which is what I get when using a `BlockOperator`.

**Comment by jandrej** [comment]
You can convert it or use the `SetGradientType` method to set it to an AIJ matrix before assembly.

**Comment by jetremblay** [comment]
OK, I will try that and revert my changes to petsc.cpp.

**Comment by stefanozampini** [comment]
I know they have recently fixed a few things in SLEPc related with MatNest; anyway, you should not force conversions to fix issues of other libraries. If people will use the eigensolver, they will notice and find the solution that best fits their frameworks. Also, if you think something is off or that should be fixed, send them an email (or to petsc-dev).

**Comment by tzanio** [comment]
Do you mind creating a WIP PR from `slepc-dev` for discussion purposes?

That will be easier to more people to follow.

**Comment by jetremblay** [comment]
Yes! I am cleaning up the branch and will create the the WIP PR soon.

**Comment by jetremblay** [comment]
Please see https://github.com/mfem/mfem/pull/1487

**Comment by tzanio** [comment]
Discussion continued in https://github.com/mfem/mfem/pull/1487
