### ISSUE TITLE
Face Integrator for Euler equations

### ISSUE THREAD

**Issue by vikramsg** [mfem/mfem#148]
Hi,

I am trying to progress towards solving the Euler fluid equations using MFEM and DG. I went through example 9 and I (hopefully) understand how the implementation works. 

To solve the Euler equations, I would need to implement an upwind flux at all faces. But, the upwinding depends on the local face velocity. The way I see it, first, the matrices would need to be recreated each time. 

But, second, what I don't understand right now is how to do the upwinding. The DG face integrators have only one way right now to call another function and that is through a vector coefficient, but that does not accept a grid function. 

Is my understanding of this correct? And please advise on how I should move forward.

**Comment by vladotomov** [comment]
Hi Vikram,

I'm not sure what exactly your question is, could you be more specific. It might be helpful to examine the classes VectorGridFunctionCoefficient and GridFunctionCoefficient.

Vladimir

**Comment by vikramsg** [comment]
Hi @vladotomov ,

Sorry about that. I'll try to clarify what I meant. 

In example 9, the equation being solved is du/dt + vdu/dx = 0. It is solved using DG. Now, the vd/dx term is converted into K. Here, v is defined either as constant or a function of x and not a function of u. The DGTraceIntegrator at interior faces, with beta = -0.5 means the face contribution is taken as the upwinded flux of the defined velocity by evaluating it at the face. 

Now, for my problem, suppose instead of vdu/dx, I have udu/dx. So now ud/dx has to be converted into K. And that is where I don't understand how to use the DGTraceIntegrator since we only pass a function that is a function of x. How do we pass u so that it is evaluated at the face and the face contribution is taken based on the sign of u at that specific face. 

Thanks.

**Comment by vladotomov** [comment]
Both v and u are functions of x, the difference is that v is defined pointwise (through velocity_function), while u is a finite element function. You can certainly create a VectorGridFunctionCoefficient that references u, and give this to the DGTraceIntegrator. In this case you have K = K(u), while in ex9 we have K = K(v). Then your (explicit) rhs would be [K(u) u] instead of [K(v) u] (in ex9). Let me know if I'm missing something.

**Comment by vladotomov** [comment]
You should also take into account that u is a vector unknown, while the DGTraceIntegrator in ex9 is defined for a scalar equation. Using the ex9 code, in 3D you can define K(u) u_1, K(u) u_2, K(u) u_3, which is fine if you solve for each component independently. You would need to make some additional changes to define a big block system for all velocity components.

**Comment by vladotomov** [comment]
Another thing to keep in mind is that the DGTraceIntegrator assumes continuous normal component of the flux. So if you are planning to use discontinuous u in Euler, you might need to define a different face integrator.

**Comment by vikramsg** [comment]
Thanks so much for the clarifications. What I didn't get was how I would pass a VectorGridFunction to DGTraceIntegrator since it only has vector as argument type. 

While I assumed that the flux component would be discontinuous. i wanted to ask how the Integrator uses the assumption. Each face has two elements adjoining it. So, will the function that would do the evaluation, say Q, to get the flux at the face would be called only once? I am guessing the change I would have to do would be to call the function once for each element. Is that correct?

Thanks again.

**Comment by vladotomov** [comment]
Yes, u.n is computed using the velocity from element 1. The integrator computes something even with discontinuous velocity, but it's probably not what you want (the result depends on the numbering of the elements). Here's a paper describing a DG method with discontinuous flux:
[http://www.math.tamu.edu/~guermond/PUBLICATIONS/guermond_morel_popov_zingan_CMAME_2013.pdf](url)

**Comment by vikramsg** [comment]
Thanks Vladimir,

I realize now that what I need is a Riemann flux at all faces. The way this needs to be implemented is to do 0.5*(f(u_1)+f(u_2)-s*(u_2 - u_1)) at all faces. where 1 and 2 denote the left and right cell contributions. s is a function of u_1 and u_2. It seems to me the way to do it would be to have a term like Ku+b, where b is a linear term. I can see a DGDirichletLFIntegrator that does it for the boundary, and I would need a similar way to construct the vector considering both elements bordering the face. Do you think it would be enough if I modify the terms to do the following

```
elvect.SetSize(ndof1 + ndof2);
...
el1.CalcDShape(eip, dshape1);
el2.CalcDShape(eip, dshape2);
...
dshape1.Mult(nh, dshape_dn1);
dshape2.Mult(nh, dshape_dn2);
...
elvect.Add(sigma, dshape_dn1);
elvect.Add(sigma, dshape_dn1);
```

Will elvect be correctly constructed and be put into b? Thanks for all the clarifications.

**Comment by vladotomov** [comment]
I'm not quite sure what this code is expected to do and what b is, but you should go ahead and try things. I would probably start by defining a custom face integrator.

**Comment by vikramsg** [comment]
Hi Vladimir,

Thanks for the reply. 

b is a linear form and would be similar to the boundary face integrator except in boundary face integrator the cell on only one side has terms. What I wanted to know was that if I made a custom face integrator that took cells on both side into account will the vector created be correctly constructed.
