### ISSUE TITLE
CodeDocumentation.html symbolic link works in firefox but not chrome browser

### ISSUE THREAD

**Issue by rw-anderson** [mfem/mfem#1480]
In the doxygen documentation directory, there is a convenient symbolic link to the top level html file.

In the firefox browser, opening this link seems to reset the base path to the target of the link for the relative paths used in the rest of the documentation, so everything works correctly.

In the chrome browser (81.0.4044.129) on linux, it does not, and the links are all broken.

**Comment by tzanio** [comment]
On Mac the following works fine with Chrome:

```
cd mfem/doc
make
open CodeDocumentation.html
``` 

I can't check it now, but my recollection is that the equivalent worked also on Linux... Does it not work for you @rw-anderson?

**Comment by rw-anderson** [comment]
> On Mac the following works fine with Chrome:
> 
> ```
> cd mfem/doc
> make
> open CodeDocumentation.html
> ```
> 
> I can't check it now, but my recollection is that the equivalent worked also on Linux... Does it not work for you @rw-anderson?

If you are launching a new instance of chrome from the command line, it works.  If you have an instance of chrome already running and do ctrl-o to open it, it doesn't.  I think I have a solution which should work for all of these scenarios, which I'll push in a branch in a minute.

**Comment by tzanio** [comment]
Discussion continued in #1481
