### ISSUE TITLE
Spack package debug variant doesn't add debug symbols

### ISSUE THREAD

**Issue by white238** [mfem/mfem#1483]
The combination of adding flags to CXXFLAGS in your spack package and your makefile not adding DEBUG_FLAGS to CXXFLAGS if its not empty (line 200 of your base Makefile), you end up with no "-g -O0" in your debug variant.

The following is one example of a fix is to change the following in your spack package from:

```
        if cxxflags:
            cxxflags = [(xcompiler + flag) for flag in cxxflags]
```

to:

```
        if cxxflags:
            cxxflags = [(xcompiler + flag) for flag in cxxflags]
            if '+debug' in spec:
                cxxflags.extend(['-g', '-O0'])
```

**Comment by white238** [comment]
If this fix is acceptable I can push the fix to Spack repo in a PR I am doing soon for Axom and Conduit.

**Comment by v-dobrev** [comment]
This is the intended behavior -- if you set the `cxxflags` in Spack they replace the default values in MFEM, regardless of the `debug` variant. If using `+debug`, just set the `cxxflags` to the desired combination of flags.

Note that `+debug` does more than just switch the flags. For example, it is sometimes useful to enable `+debug` and still use `-O3` optimization -- which will not be possible with your suggestion.

**Comment by white238** [comment]
I just saw the bug that was causing it in my version of spack was fixed.  The C++11 flag was always being added in my version and can update to the newer one that doesn't.

This is more of a philosophical argument at this point and if you expect your users to set the optimization/debug flags in their global flags that's fine, I can work around it.  The problem is I am needing to add a default flag ("--gcc-toolchain=/newer/gcc") across the board and that causes both the debug and opt flags to never be set.

You can feel free to close this issue.

**Comment by white238** [comment]
After thinking about this more and consulting @becker33 on the Spack team, I may have snippet of code that should work for both of our needs.  Basically, if cxxflags is set by the user, it tries to find debug or opt flags and if they are missing adds them.  This requires a fix on Spack's side and injecting this (tentative) code after line 368 in your current mfem/package.py:

`
            opt_flag_found = any(f in self.compiler.opt_flags for f in cxxflags)
            debug_flag_found = any(f in self.compiler.debug_flags for f in cxxflags)

            if '+debug' in spec:
                if debug_flag_found:
                    cxxflags.append('-g')
                if opt_flag_found:
                    cxxflags.append('-O0')
            else:
                if opt_flag_found:
                    cxxflags.append('-O2')
`

I would really like to find a solution that both of us are happy with so I can stop keeping a copy of your package in my project's repositories (Axom and Serac).  This just causes us to become out of date with your current package as well as pushes our shared solutions to the rest of the Spack community.

**Comment by tzanio** [comment]
Absolutely, we want to avoid custom copies too and other users are probably running into the same issues as you.

Will it help if we have a short telecon.

**Comment by white238** [comment]
Let me test out the branch @becker33 just created and get back to you.  It actually requires two branches and one should be approved soon.

**Comment by white238** [comment]
https://github.com/spack/spack/pull/17121

Sorry this was a very long running set of fixes to get to this point (thanks @becker33)!  I have created a PR in the spack repo for this fix
