### ISSUE TITLE
Makefile inclusion order affects certain symbols

### ISSUE THREAD

**Issue by jdahm** [mfem/mfem#149]
My build workflow thus far has been to keep a config/user.mk from which I generate the config.mk file with 'make config'. There is a dependency issue when doing this: when certain combinations of symbols are YES, for example MFEM_USE_MPI and MFEM_USE_SUNDIALS, there are a sections in defaults.mk (for that example, lines 124-127) that execute and add to other symbols that do not execute. This is because user.mk is included after defaults.mk in the top-level makefile and those symbols were not yet marked as YES by that point. However, when passing the MFEM_USE_* arguments on the command line with 'make config MFEM_USE_*=YES ...' then these get executed correctly.

A way to get around this would be to move these sort of "post-config hooks" out of defaults.mk and into another .mk file that gets included after user.mk. If developers generally agree that this is OK, I can go ahead and put together a quick pull request.

**Comment by v-dobrev** [comment]
I think issues similar to what you describe arise when you create a "clean" `user.mk` where you put only modification (relative to `defaults.mk`) you want/need. Such a "clean" `user.mk` file does not always work as expected, as you pointed out. I've run into this issue a few times myself. :-)

That is why we usually recommend to copy `defaults.mk` to `user.mk` and then edit it - that way lines like [`defaults.mk:123-127`](https://github.com/mfem/mfem/blob/master/config/defaults.mk#L123-L127) will remain in `user.mk` unless they are explicitly removed.

Anyway, I think what you propose, can work but I feel that separating parts of `default.mk` into another file will hide part of the configuration logic from the user, and that will be more confusing.

Let's see what others think about this issue.

**Comment by jdahm** [comment]
Oh, ok - I missed that portion of the INSTALL file, but I see now. If that is the usual workflow then it's best to keep it that way, since as you said it simplifies the process and makes it clearer to everyone. It could be changed to something like the code below, since it is then a duplicated effort to include first defaults.mk and user.mk if the latter exists, but I suppose it's safest to include both.

```
ifeq ($(shell test -r$(BLD)config/user.mk && echo -n yes),yes)
  CONFIG_IN=$(BLD)config/user.mk
else
  CONFIG_IN=$(SRC)config/defaults.mk
endif
include $(CONFIG_IN)
```

Unless you feel strongly that this should go in, we can probably close this issue. Apologies for my confusion.

**Comment by tzanio** [comment]
I don't have a strong opinion on this, except that I will prefer not to split the `defaults.mk` file -- some (most?) users actually just modify that directly instead of creating a `user.mk` so we don't want to break that workflow.

@jdahm, I'll leave it up to you if you'd like to close the issue or pursue it further in a PR.

**Comment by jdahm** [comment]
I always prefer fewer 'if' statements, so I'm closing this.
