### ISSUE TITLE
DG for Laplace Problem in First order Formulation

### ISSUE THREAD

**Issue by Pratikk17** [mfem/mfem#1490]
Hi,

I would like to implement MFEM code to solve the Laplace problem (in the first-order formulation) in 2D using DG formulation. I use zero Dirichlet boundary conditions. This code will be similar to the example 5 with some changes. I defined \sigma=grad(u) and hence the couple equations are 
**\sigma-grad(u)=0
-div(sigma)=f.**

For this I use MixedBilinear form. I do not know how to add the DGTraceIntegrator for the MIxedBilinearFOrm. The important lines are:

   FiniteElementCollection *fec_sigma = new DG_FECollection(order, dim);
   FiniteElementCollection *fec_u = new DG_FECollection(order, dim);

   FiniteElementSpace *sigma_space = new FiniteElementSpace(mesh, fec_sigma);
   FiniteElementSpace *u_space = new FiniteElementSpace(mesh, fec_u);

  //     C   = -\int_\Omega \grad u_h v1_h d\Omega   u_h \in u_space, v1_h \in sigma_space
   
   MixedBilinearForm *cVarf(new MixedBilinearForm(sigma_space,u_space));

    cVarf->AddDomainIntegrator(new GradientIntegrator(mone));
    **cVarf->AddBdrTraceFaceIntegrator(new DGTraceIntegrator(velocity, alpha, beta));**
    cVarf->Assemble();
    cVarf->Finalize();
    SparseMatrix & C(cVarf->SpMat());
   
Can you please help me out. I get error in the line "cVarf->AddBdrTraceFaceIntegrator(new TransposeIntegrator(new DGTraceIntegrator(velocity, alpha, beta)))".
The error is "FEM abort: AssembleFaceMatrix (mixed form) is not implemented for this Integrator class." Here velocity is just a vector of ones, alpha=1.0 and beta=-0.5.

Thank you very much. 
Best regards,
Pratik

**Comment by Pratikk17** [comment]
Hi @tzanio ... Can you please help me out?

**Comment by tzanio** [comment]
Hi @Pratikk17,

Do you really want to use mixed + DG discretization?

I'm asking because people usually choose mixed CG (Example 5) or DG (Example 18) and it is not clear to me if mixing them will be beneficial for the Laplace problem.

If that's really your objective, then the first thing you need to figure out on continuous level is what are the spaces for `u` and `sigma` and what are the mixed integrators you will need.

@psocratis has experience with DPG and ultra-weak formulations and may be able to help, though it is likely that you may have to implement some new integrators.

Cheers,
Tzanio

**Comment by Pratikk17** [comment]
Hi @tzanio ,

Thank you for your reply. I want to implement Leapfrog scheme for linear wave equation with DG space discretization and hence I chose to first write a code for the Laplace equation. I had to go to use MIxedBilinear form since u is scalar while sigma=grad(u) is vector.  I will check code 18 again to see if I can manage to write the code else I will ask again.

Thank you very much.
Best,
Pratik

**Comment by pazner** [comment]
Hi @Pratikk17,

Is there a reason that you would like to specifically use the first-order DG formulation for the Laplace equation?

If you eliminate the auxiliary variable sigma, then you can obtain a reduced system for the solution u. This is the approach used in example 14 (DG diffusion) using the `DGDiffusionIntegrator`.

**Comment by Pratikk17** [comment]
Hi @pazner ,

The ultimate aim is to apply and compare time integrators for linear wave equations and Maxwell's equations, whose space discretization is done by dG methods. These time integrators are in the form which suits first order formulation. So as an initial step, I would first see if everything works good for Laplace problem and then extend to wave.

I checked example 14 and understood it. I could extend it to wave equation. But I think I need to implement new integrators for the first order formulation (since there are no integrators available in mfem library). I would contact you if I face some problems.

Best,
Pratik
