### ISSUE TITLE
Fix Travis CI to catch when make check returns a 0 ( fail )

### ISSUE THREAD

**Issue by aaroncblack** [mfem/mfem#150]
Reported by @v-dobrev:
We need to fix the travis ci file - make check failed but it was not reported properly because it exited with code 0.

**Comment by tzanio** [comment]
See https://travis-ci.org/mfem/mfem/jobs/209589765

**Comment by v-dobrev** [comment]
I think the issue is actually that the makefiles ignore the exit codes from the test runs, so that all tests get run even if some fail. We need to propagate the error back up to the parent makefile that can re-raise any errors that were ignored.

This is handled differently in the CMake build system and that may work better, but I still think we should fix the makefiles.

**Comment by aaroncblack** [comment]
If you have multiple commands in a Travis yaml section, only the exit code of the last command will be reported.  The level of granularity that Travis will catch errors in is:

-    If before_install, install or before_script return a non-zero exit code, the build is errored and stops immediately.
-    If script returns a non-zero exit code, the build is failed, but continues to run before being marked as failed.
- The exit code of after_success, after_failure, after_script and subsequent stages do not affect the build result. However, if one of these stages times out, the build is marked as a failure.

We can fix our 'script' section by combining the make targets into a single line.

   # Build and check/test MFEM, its examples and miniapps
   - cd $TRAVIS_BUILD_DIR \
    && make config MFEM_USE_MPI=$MPI MFEM_DEBUG=$DEBUG MFEM_CXX=$MYCXX \
    && make all -j 4 \
    && make $MFEM_TEST_TARGET

I'll do this and verify it works as expected.

http://blog.tgrrtt.com/exploring-the-travisci-configuration-file

**Comment by aaroncblack** [comment]
In addition to the travis script update, I also need to fix out our 'make check' makefile logic.  It doesn't propagate up the error code after running a test.

**Comment by tzanio** [comment]
Given #169, can we close this issue?

**Comment by aaroncblack** [comment]
Fixed, see PR #169 for more information.
