### ISSUE TITLE
Add an option to Mesh::DeleteGeometricFactors() to avoid memory re-allocation

### ISSUE THREAD

**Issue by v-dobrev** [mfem/mfem#1500]
We want to have an option to avoid de-allocating the memory for the geometric factors in `Mesh::DeleteGeometricFactors()` -- it should just mark the factors for re-computation.

This should help with slow GPU memory allocation/de-allocation.

cc: @artv3, @tomstitt

**Comment by tomstitt** [comment]
Another option could be to make the temporaries grab memory from a temporary pool of the memory manager, that way more than just this function could benefit. I'm not sure the state or capabilities of the memory manager though, would this be possible?

**Comment by tzanio** [comment]
ping: @camierjs

**Comment by tzanio** [comment]
Discussion continued in #1517.
