### ISSUE TITLE
Link error when building with Spack (static libs)

### ISSUE THREAD

**Issue by mclarsen** [mfem/mfem#1501]
I have run into an issue building with spack when using `~shared+mpi`. The source of the linking errors are the fortran symbols coming in from blas(choose your implementation). Anyone run into this and have a workaround?

**Comment by v-dobrev** [comment]
Are you using `+lapack` variant of MFEM or some other package used LAPACK/BLAS?

Can you post one example of the linking errors?

**Comment by mclarsen** [comment]
Here is the exact spec:

```
^mfem@4.0.0%gcc@7.3.1+conduit~debug~examples~gnutls+gzstream+hypre~lapack~libunwind+metis~miniapps~mpfr+mpi~netcdf~occa~openmp patches=7f582bd8b418ffbd4cc37b73cb0e861efc0cf0dd332ae726e18e306f975b0310 ~petsc~pumi~raja~shared+static~suite-sparse~sundials~superlu-dist~threadsafe timer=auto arch=linux-rhel7-power9le
        ^hypre@2.18.2%gcc@7.3.1~complex~debug~int64~internal-superlu~mixedint+mpi~openmp~shared~superlu-dist arch=linux-rhel7-power9le
            ^openblas@0.3.7%gcc@7.3.1+avx2~avx512 cpu_target=auto ~ilp64+pic~shared threads=none ~virtual_machine arch=linux-rhel7-power9le
        ^metis@5.1.0%gcc@7.3.1 build_type=Release ~gdb~int64 patches=4991da938c1d3a1d3dea78e49bbebecba00273f98df2a656e38b83d55b281da1,b1225da886605ea558db7ac08dd8054742ea5afe5ed61ad4d0fe7a495b1270d2 ~real64~shared arch=linux-rhel7-power9le
```

**Comment by mclarsen** [comment]
The error is:
```
>> 243    dormlq.f:(.text+0x37c): undefined reference to `_gfortran_concat_string'
```

**Comment by mclarsen** [comment]
I fixed it by using logic similar to what is in the strumpack stuff:

```
      if '+mpi' in spec:
            options += ['MPICXX=%s' % spec['mpi'].mpicxx]
            hypre = spec['hypre']
            # The hypre package always links with 'blas' and 'lapack'.
            all_hypre_libs = hypre.libs + hypre['lapack'].libs + \
                hypre['blas'].libs
            if '~shared' in hypre:
                if os.path.basename(env['FC']) == 'gfortran':
                    all_hypre_libs += ['gfortran']
                if '^mpich' in hypre:
                    all_hypre_libs += ['mpifort']
                elif '^openmpi' in hypre:
                    all_hypre_libs += ['mpi_mpifh']
```

I am not sure if the is 100% the correct way to fix it, but it is a way.

**Comment by v-dobrev** [comment]
I see. In the fix, you probably don't need the `^mpich` and `^openmpi` parts.

It looks like this dependency on `-lgfortran` comes from `openblas`, so the correct solution should be to update the `openblas` package to add `-lgfortran` when asked for the `libs` property. Ultimately, the right way might be a bit different, according to https://github.com/spack/spack/pull/15500#discussion_r413560773.

**Comment by mclarsen** [comment]
I agree that it should be the responsibility of the dependent library to tell you about the libraries it need to link. As a note, i tried building with netlib-blas and encountered the same error.

Feel free to close this. I just wanted to put some information out there for others who might experience the same issue.

**Comment by tzanio** [comment]
Thanks for reporting this Matt.

Other folks that are building through Spack may be running into similar issues, so this is useful.
