### ISSUE TITLE
New user question about boundary conditions for structural mechanics

### ISSUE THREAD

**Issue by thelfer** [mfem/mfem#1509]
Dear `MFEM` users,

I recently start evaluating in `MFEM` for non linear structual mechanics applications.

I have a few questions about how Dirichlet' boundary conditions are handled in MFEM. For what I have seen so far, they are eliminated by default. Are other treatments of the Dirichlet boundary conditions available (Nitshe, Lagrange multipliers, for example) ? Would it be possible to implement a condition of type "a plane remains a plane", i.e. all the nodes of a plane have the same normal displacement ?

I would also be interested to know if
-  some works on contact already exists in `MFEM`
- if would be possible to mix shell elements and 3D elements in the same computation and link the degree of freedoms of those elements to "attach" shell on 3D elements

Thanks for any help, link in the documentation, etc..

**Comment by barker29** [comment]
Unfortunately much of what you're asking about is not currently well supported in MFEM.

For Nitsche conditions, the place to start is `ex17p`, which uses a DG formulation for linear elasticity and imposes boundary conditions in a Nitsche-like way, see the `DGElasticityDirichletLFIntegrator` object. Something like this could also be used in a non-DG formulation but it might take some work.

Something like Lagrange multipliers or the "plane remains a plane" condition would have to be implemented at the linear algebra level, that is, you would have to formulate the constraints on the dofs and put it in a linear system that MFEM could then solve. 

We have just started some work on contact and other constraints of this type, but it is in very early stages. Shell elements are currently not supported.

**Comment by thelfer** [comment]
@barker29, thanks for your help. At least, it matches my initial assumptions.

I plan to perform my investigations of MFEM by coupling it with `MFront` which provides some non linear behaviours (BTW, I am the main developper of `MFront`). Do you know if such non linear mechanical behaviours *with* state variables (living at the integration points) has already been used in MFEM simulations ?

In particular, I would be interested to know if there already exists some supports of values at integration points and if they could be defined on part of the whole mesh (i.e. for multi-material simulations).

**Comment by rcarson3** [comment]
@thelfer to answer your question related to nonlinear mechanical behaviors with state variables one such example is the [ExaConstit app](https://github.com/LLNL/ExaConstit). It's a nonlinear solid mechanics velocity-based code built on MFEM. It's been primarily developed for crystal plasticity models.

Then the ```QuadratureFunction``` class is designed to hold data that lives at quadrature points, but it's defined over the entire mesh. You could make use of the ```DenseTensor``` class as a more efficient way of storing this quadrature data for multi-material simulations, but you would need to write your own code mapping the indices from that class to where it lives in the global mesh and vice versa.

**Comment by thelfer** [comment]
@rcarson3 Thanks for this kind answer. I did not know the `ExaConstit` app and it seems a very interesting starting point.

Concerning the storage at quadrature points, that probably implies that there is currently no built-in features to project values at integration points during adaptative remeshing, right?

P.S. We have an UMAT interface in `MFront` which is working quite well and single crystal behaviour have been actively developed the `MFront` users. If interested, let me know.

**Comment by rcarson3** [comment]
@thelfer I haven't interacted  with the AMR aspect of things, but maybe @v-dobrev could help answer that question.

If you have users who might be interested in making use or trying out ExaConstit we could open an issue on its repo and discuss what might needed to interface MFront with ExaConstit.

**Comment by thelfer** [comment]
@rcarson3 Would you consider that `ExaConstit` could be a good starting point for me to explore `MFEM` ? Would I be able to use standard finite strain behaviours (taking the gradient and returning the Cauchy stress for example) ?

**Comment by rcarson3** [comment]
@thelfer It may not be the best code to dive into right away to get a feel for MFEM. Starting off I'd say Example 2 (linear elasticity) and Example 19 (incompressible neo-hookean model) are good starting points for just getting familiar with MFEM. Next, Serac might not be a bad choice as well, since it's a smaller code than ExaConstit and is a displacement based thermomechanic code, so it would be just as easy to perform finite strain problems in there as well.

Once you've gotten a feel for how MFEM works, I'd say ExaConstit is then a good example for how to translate these codes over to run on the GPU.

**Comment by v-dobrev** [comment]
A correction:

> Shell elements are currently not supported.

This is not true, if by "shell elements" you mean surface elements like quads mapped in 3D space. An example using such elements is example 7/7p (surface Laplacian). Linking the surface elements to volume elements (and their dofs) is not too hard if the surface elements are given as what we call in MFEM the "boundary" elements in the mesh file.

Regarding:

> Concerning the storage at quadrature points, that probably implies that there is currently no built-in features to project values at integration points during adaptative remeshing, right?

Performing interpolation of `QuadratureFunction`s after refinement is currently not supported but it can be fairly simple once we add projection of `QuadratureFunction`s to `GridFunction`s (there are discussions about this in #1281 and #1477). The simple approach is to interpolate the `QuadratureFunction` to a `GridFunction` then interpolate that to the new mesh and then evaluate the new refined `GridFunction` at the points of the new refined `QuadratureFunction`.

Regarding multi-material quadrature data: if all materials use the same number of scalar quantities at quadrature points, then a single `QuadratureFunction` will be sufficient. If the quadrature data size per point varies with the material, the simplest approach right now is to store the data with overhead -- using the maximum number of scalar quantities per quadrature point everywhere. Is this a big limitation for the use cases you have in mind?

Another example that may be of interest to you is the time-dependent Neo-Hookean elasticity, example 10/10p.

**Comment by thelfer** [comment]
@v-dobrev Thanks for those answers.

>  Is this a big limitation for the use cases you have in mind?

No for my first tests. But in general it is.

> Another example that may be of interest to you is the time-dependent Neo-Hookean elasticity, example 10/10p.

Ok, i'll have a look at this one too.

**Comment by thelfer** [comment]
Thank you all for your answer. I have more or less the information that I needed and some interesting tracks to explore.
