### ISSUE TITLE
Usage of GlobalVector()

### ISSUE THREAD

**Issue by kvoronin** [mfem/mfem#151]
Hello everyone,

I am getting a segfault for some MPI configurations (not for all, mostly for 2 nodes with 8 mpi procs per node) with the following piece of code, where my idea was to compute the euclidean norm of the ParGridFunction as a vector: 
```
   ConstantCoefficient onecoeff(1.0);

    ParGridFunction ProjuTEST(H_space);
    ProjuTEST = 0.0;
    ProjuTEST.ProjectCoefficient(onecoeff);

    HypreParVector * ProjupvTEST = ProjuTEST.ParallelAssemble();
    Vector * ProjuvTEST = ProjupvTEST->GlobalVector();
```
Here H is a correctly defined ParFiniteElementSpace, H1 for order 1 in 3D, the mesh is small so everything should fit in memory.
I am absolutely sure that the segfault happens during the call to GlobalVector().

Is there anything wrong about this way of using the function GlobalVector()? 

Thanks,
Kirill

**Comment by v-dobrev** [comment]
Hi Kirill,

You need to use `ParallelProject` instead of `ParallelAssemble`. To compute the Euclidian norm of a `ParGridFunction`, I'd use something like this:
```c++
ParGridFunction f(fespace);
// ...
HypreParVector hf(fespace);
f.ParallelProject(hf);
double f_norm = sqrt(InnerProduct(hf, hf));
```

I'm not sure why `GlobalVector` segfaults, I'll try some configurations to see if I can reproduce this issue.

**Comment by tzanio** [comment]
Also, if you goal is to compute the l2 norm of `ProjuTEST` you can do it more directly, by using that `ParGridFunction` inherits `Vector` plus an MPI reduction, see e.g. PR #138.

**Comment by kvoronin** [comment]
Thanks for the answers, it does help.
I would guess now that the segfault was happening when I was accidentally requesting more mpi processes than there were computational cores available. (Not sure whether about whether hyperthreading was enabled and whether it can affect the behavior). 
So probably it was just mpi communication routines which stuck because of de-facto sequential processing.
