### ISSUE TITLE
Question about hypre's interface

### ISSUE THREAD

**Issue by hongbo-yao** [mfem/mfem#1511]
Hi,
I'd like to test different options of hypre's BoomerAMG and AMS solvers and I have two questions. 

(1) HypreBoomerAMG only has a private SetDefaultOptions function, do you have any plan to add some public functions to set AMG options (or AMS)?  It is easy to implement through modifying MFEM's hypre files, but I prefer to keep consistent with the official version. Or any other ways?

(2) I noticed that when using AMG as preconditioner, the hypre reference doc tells us to set MaxIter to be 1 and Tol to be 0.0, but I'm not quite sure about the reason.  Even though used as preconditioner, we still need to solve one linear equation to approximate the product between the inverse of preconditioning matrix and a vector, how does hypre control the iterations and tolerance? 

Thanks

**Comment by tzanio** [comment]
For (1), see the discussion here: https://github.com/mfem/mfem/pull/1053#discussion_r402389386.

Basically, we try to expose collection of options that seem to be useful for particular purposes. If you want to set other options, you can use the `HYPRE` functions directly on the MFEM object.

For (2), the overall system is solved by a Krylov method, e.g. PCG. The goal of the hypre preconditioning is to provide a cheap approximation to the inverse, hence we fix it to exactly one V-cycle (that's the effect of these options).

Hope this helps,
Tzanio

**Comment by hongbo-yao** [comment]
> For (1), see the discussion here: [#1053 (comment)](https://github.com/mfem/mfem/pull/1053#discussion_r402389386).
> 
> Basically, we try to expose collection of options that seem to be useful for particular purposes. If you want to set other options, you can use the `HYPRE` functions directly on the MFEM object.
> 
> For (2), the overall system is solved by a Krylov method, e.g. PCG. The goal of the hypre preconditioning is to provide a cheap approximation to the inverse, hence we fix it to exactly one V-cycle (that's the effect of these options).
> 
> Hope this helps,
> Tzanio

Hi @tzanio, Thank you for your quick reply

(1) would be helpful and for (2), I may just need more time to learn the details of AMG and AMS approaches

Thanks again!
