### ISSUE TITLE
Fail to build mfem.

### ISSUE THREAD

**Issue by tuanhtrng** [mfem/mfem#1512]
Broke [here](https://github.com/mfem/mfem/blob/21401db8faf855fcb080649a04dd209f75f79b06/general/mem_manager.hpp#L460) despite Travis success.

Should line 453 be `static inline T *New(std::size_t size)` instead?

**Comment by v-dobrev** [comment]
Yes, absolutely. This bug slipped through the cracks -- we actually do not test building in `C++17` or newer mode (that portion of the code is used only in that case).
