### ISSUE TITLE
Too much Vector data on GPU

### ISSUE THREAD

**Issue by dylan-copeland** [mfem/mfem#1516]
GPU "out of memory" failures can be caused by having too many vectors using device memory. A possible solution might be a smaller collection of GPU data globally available for vectors as needed.

For simple codes such as the MFEM examples (e.g. ex1p, ex3p), there are only a few vectors using device memory (e.g. via `UseDevice(true)`). For example, there may be RHS and solution vectors `B` and `X`, a diagonal vector for Jacobi preconditioning, and a `CGSolver` with 3 auxiliary vectors on device, for a total of 6 vectors on device. In such simple cases, most of the GPU memory is used by `BilinearFormIntegrator` instances, which store data at the quadrature points. The portion of GPU data used by auxiliary vectors on device depends on the finite element order, and the problem is worse for low order. For example, the GPU memory used by ex3p for order 3 seems empirically (on one machine) to be doubled when allocating about 30 extra vectors on device. 

To illustrate how a complex code can use so many extra vectors on device, consider a domain decomposition solver for a complex-valued block system with mixed finite element spaces (e.g. ex5p), with each subdomain having an iterative solver preconditioned by multigrid with Jacobi smoothers. Then the usage of device vectors might be nested as follows:

1. Global RHS and solution vectors (2 Vectors)
2. Global iterative solver, e.g. CGSolver (3 Vectors)
3. Operator sum (1 Vector on device)
4. Product operator  (1 Vector on device)
5. Block operators (2*NSD Vectors)?
6. TripleProductOperator for some DOF maps (2 Vectors)
7. User-defined subdomain solver (2 block vectors)
8. Local CGSolver (3 Vectors)
9. Local BlockOperator (2*4 Vectors, with 4 blocks)
10. User-defined block multigrid (3 + 2*numGrids Vectors)
11. Diagonals for Jacobi smoothers (1 Vector)

Here NSD is the number of subdomains, and there are 4 blocks for real and imaginary parts of two spaces. As an extra complication, there is uncertainty about how `BlockOperator` will be implemented. Currently, `BlockOperator` in the master branch does not support GPU computations, but I have a branch that copies to and from subvectors on device. PR #1468 is still a WIP, but hopefully it will implement reuse of the input and output data so that extra vectors are no longer necessary. Depending on the discretization, solver, and preconditioners, there could be more user-defined operators that use vectors. The point is that it is possible for a complex code to have 30 or more extra vectors allocated on the GPU, although they are not all used simultaneously. 

The question is how to reduce GPU memory usage without sacrificing much performance. Fixing `BlockOperator` would help but not be sufficient in general. Allocating and deallocating vectors each time they are used would reduce memory usage, but that seems too slow (and code-invasive), although that has not been confirmed experimentally yet. 

One possible idea, which may be difficult to implement, is based on the assumption that only a few vectors are actually used simultaneously on the device, as in the example of nested operators and solvers described above. Instead of allocating all vectors on device, just a few could be allocated, and that memory could be reused by all the vectors. This could be implemented with a global instance of a class that contains a small array of vectors allocated on device. Then the vectors that would normally be on device could wrap the data of those global vectors when needed, using flags to mark when vectors are in use on GPU (in which case they wrap available data) or not (in which case the data is available to be wrapped). This would require copying data between the host and device each time a vector is used, as the data should be stored on host when not in use (so that the device memory is available to be used by another vector). In summary, vectors would be permanently stored on CPU and temporarily moved to GPU using a limited amount of recycled data. A disadvantage of this approach is that it is still code-invasive, requiring vectors to be flagged as in use or not. Another complication is that vectors could be of different sizes, and finding the optimal way to reuse a limited amount of GPU memory may be complicated depending on the application code. There is also the question of whether the copying of data between host and device would destroy performance. If there is only a modest loss of performance, then it may be desirable to trade some performance for memory savings.

A possible view is that it is not a serious problem worth fixing, if the memory is only doubled in the worst case. Perhaps if the BlockOperator issue is resolved, doubling the memory would be the worst case. Even so, if someone has an idea for a simple fix, it may be worthwhile.

One more idea applicable to the case of BlockOperators is that it is not necessary to have memory for the entire vector on device, just enough for the subvectors. The blocks are multiplied sequentially (one operator and one integrator in one space at a time), so we are not saturating the GPU with more computation by putting the entire vector on device. However, reducing the memory to just the size of one block is tricky, since there is probably an iterative solver calling `BlockOperator::Mult` with full-sized vectors. If the performance bottleneck is the PA `Mult` calls for each integrator, rather than the iterative solver vector algebra, then maybe it would not hurt performance to use memory for one block at a time. This is something to consider for PR #1468.

Perhaps there are other ways to reduce the amount of memory each vector uses (dividing into blocks or subsets of local elements?), which would be preferable to the ideas described so far.

These are just ideas, and determining what is optimal in practice may require empirical data on the timing of various operations, e.g. allocations on GPU, copying between host and device, performing PA `Mult` calls, vector algebra, etc. Also, such data would vary depending on the finite element space and order. This is intended to be the start of a discussion or investigation, rather than a proposal. Hopefully someone has a better solution.

**Comment by tzanio** [comment]
This discussion has continued internally at LLNL, but we will keep the issue open for another week to solicit input from the MFEM community...
