### ISSUE TITLE
DG for Maxwell's equations

### ISSUE THREAD

**Issue by Pratikk17** [mfem/mfem#1518]
Hi, 

I am back with some problems. I would like to solve Maxwell's equation using DG  discretization for space. So I defined 
   FiniteElementCollection *fec_H = new DG_FECollection(order, dim);
   FiniteElementCollection *fec_E = new DG_FECollection(order, dim);
   FiniteElementSpace *H_space = new FiniteElementSpace(mesh, fec_H,3);     // H=(Hx,Hy,0)
   FiniteElementSpace *E_space = new FiniteElementSpace(mesh, fec_E,3);     // E=(0,0,Ez) 

The problem arises when I want to calculate the matrix or bilinear form corresponding to curl operators. I chose Bilinear form since DG trace operators are defined for bilinear form. To calculate curl operators, I defined a new class DGVectorCurlIntegrator which is very similar to VectorFECurlIntegrator. However, I realised that **CalcCurlShape is not defined for DG elements.** 

Can you please help me out in explaining how and where can I define them? 

I am really stuck since 2 weeks. Thank you in advance.

Best regards,
Pratik

**Comment by v-dobrev** [comment]
In your integrator, you can compute the curl using the gradient. For example, this is done here: https://github.com/mfem/mfem/blob/42207dbfed968464212ae0d04573d3faeac4020f/fem/bilininteg.cpp#L1706-L1752

**Comment by Pratikk17** [comment]
Hi @v-dobrev ,

Thank you very much for your suggestion. I split the equations and then used DerivativeIntegrator to find the curl. For example, for the equation dHx/dt= -partial Ez/dy, I defined the binear form as follows:

BilinearForm *Ez_y(new BilinearForm(Hx_space));
   Ez_y->AddDomainIntegrator(new DerivativeIntegrator(one,1));
   Ez_y->AddInteriorFaceIntegrator(new DGTraceIntegrator(ny_coeff, 1.0, 0));  
   Ez_y->Assemble();
   Ez_y->Finalize();  
   SparseMatrix &CEz_y(Ez_y->SpMat());

However, I ended up in small issues regarding treating fluxes at the edges. I need the y component of the normal vector and hence I defined a new function: 

void ny_function(const Vector &x, Vector &ny)
{    ny(0)=0.0;
     ny(1)=1.0;
}
and then
VectorFunctionCoefficient ny_coeff(dim, ny_function);

I want to verify whether
 AddInteriorFaceIntegrator(new DGTraceIntegrator(ny_coeff, 1.0, 0))
will calculate ny{v}[w], where v is trial and w is test function.

Can you please suggest if this is good approach or does MFEM has better way of dealing with the terms ny{v}[w] at the interface?

Thank you again.
Best regards,
Pratik

**Comment by v-dobrev** [comment]
Sorry if this was not clear: my suggestion was to modify your integrator, `DGVectorCurlIntegrator`, to use `CalcDShape` instead of `CalcCurlShape`. In the code I linked above as an example, `CalcDShape` is used to assemble the form `(curl u, curl v)` in 2D/3D in a vector H1 or L2 (i.e. DG) space. I'm assuming in `DGVectorCurlIntegrator` you want to assemble the form `(curl u, v)` in 2D/3D where both `u` and `v` are vector DG spaces -- is that correct?

Regarding the face/edge terms, what exactly is the term you are trying to assemble?

**Comment by Pratikk17** [comment]
Hi @v-dobrev ,

I got your suggestion. But I realised that I need to then also define a new curl integrator for treating the faces. So I decided to write them as unknowns u=(Hx,Hy,Ez), where Hx, Hy and Ez are functions of x and y only. The curl operators E and H then reduces to 
dHx/dt = -dEz/dy;  dHy/dt= dEz/dx and dEz/dt=dHy/dx-dHx/dy;
The weak formulation of this system is then
M dHx/dt = - Cey Ez;   M dHy/dt= -Cex  ; and M dEz/dt = Chxy*Hx +  Chyx*Hy, where
M is mass matrix, and Cey, Cex, CHxy, CHyx corresponds to curl operators. Their reduction in 2D will be
Cey= sum_{elements} (-v, dw/dy) - sum_{interior faces} (ny {{v}} [[w]]) 
Cex= sum_{elements} (v, dw/dy) + sum_{interior faces} (nx {{v}} [[w]]) 
Chxy= sum_{elements} (v, dw/dy) + sum_{interior faces} (ny {{v}} [[w]]) - sum_{boundary_faces} (ny v,w)
Chyx= sum_{elements} (-v, dw/dy) - sum_{interior faces} (nx {{v}} [[w]])+ sum_{boundary_faces} (nx v,w)

I do not know exactly how to include the terms nx{{v}}[[w]] on interior and boundary faces. I guess I need to use DGTraceIntegrators. So I defined two functions ny_function and nx_function and then added in the bilinaear form as follows

   VectorFunctionCoefficient nx_coeff(dim, nx_function);
   VectorFunctionCoefficient ny_coeff(dim, ny_function);

   BilinearForm *Hx_y(new BilinearForm(Ez_space));
   Hx_y->AddDomainIntegrator(new DerivativeIntegrator(one,1));
   Hx_y->AddInteriorFaceIntegrator(new DGTraceIntegrator(ny_coeff, 1.0, 0));  
   Hx_y->AddBdrFaceIntegrator(new DGTraceIntegrator(ny_coeff, -1.0, 0));      
   Hx_y->Assemble();
   Hx_y->Finalize();  
   SparseMatrix &CHx_y(Hx_y->SpMat());
   BilinearForm *Hy_x(new BilinearForm(Ez_space));
   Hy_x->AddDomainIntegrator(new DerivativeIntegrator(minusone,0));
   Hy_x->AddInteriorFaceIntegrator(new DGTraceIntegrator(nx_coeff, -1.0, 0));  
   Hy_x->AddBdrFaceIntegrator(new DGTraceIntegrator(nx_coeff, 1.0, 0));       
   Hy_x->Assemble();
   Hy_x->Finalize();  
   SparseMatrix &CHy_x(Hy_x->SpMat());


where 
void nx_function(const Vector &x, Vector &nx)
{    nx(0)=1.0;
     nx(1)=0.0;
     nx(2)=0.0;
}

void ny_function(const Vector &x, Vector &ny)
{    ny(0)=0.0;
     ny(1)=1.0;
     ny(2)=0.0;
}

Can you please have a look. There is something wrong with how I deal with terms concerning interior faces.

Thank you in advance.
Best,
Pratik

**Comment by v-dobrev** [comment]
One potential issue could be that the derivative in `DerivativeIntegrator` is on the trial variable and in the forms, as written above, you want that derivative on the test variable. You should be able to achieve this by simply transposing the `DerivativeIntegrator` by wrapping it in a `TransposeIntegrator`.

Let us know if this does not resolve the problem.

**Comment by Pratikk17** [comment]
Thank you for your suggestion and for pointing out one of the errors. There is some problem at the boundary elements.The terms `nx{{v}}[[w]]` on boundary elements are not correct. Can you please have a look.

Thanks

**Comment by v-dobrev** [comment]
In the cases I've seen, the coefficients `alpha` and `beta` in `DGTraceIntegrator` (called `a` and `b` in the constructor) are the same for the interior and the boundary terms -- you can try using the same values in these two calls:
```c++
   Hx_y->AddInteriorFaceIntegrator(new DGTraceIntegrator(ny_coeff, 1.0, 0));
   Hx_y->AddBdrFaceIntegrator(new DGTraceIntegrator(ny_coeff, -1.0, 0));
```
and then the same values in these two calls:
```c++
Hy_x->AddInteriorFaceIntegrator(new DGTraceIntegrator(nx_coeff, -1.0, 0));
Hy_x->AddBdrFaceIntegrator(new DGTraceIntegrator(nx_coeff, 1.0, 0));
```

**Comment by tzanio** [comment]
This issue has been inactive for more than 2 weeks, so I'll close it for now. Feel free to reopen if there are further questions.
