### ISSUE TITLE
Linking issue: SuperLU_DIST v. 6.3.0

### ISSUE THREAD

**Issue by stefanhenneking** [mfem/mfem#1522]
On my personal machine, MFEM ‘make’ fails when linking to SuperLU_DIST v. 6.3.0.
For example,
```
linalg/superlu.cpp:235:4: error: unknown type name 'ScalePermstruct_t'; did you mean 'dScalePermstruct_t'?
   ScalePermstruct_t * SPstruct     = (ScalePermstruct_t*)ScalePermstructPtr_;
   ^~~~~~~~~~~~~~~~~
   dScalePermstruct_t
```
or
```
linalg/superlu.cpp:236:4: error: unknown type name 'LUstruct_t'; did you mean 'dLUstruct_t'?
   LUstruct_t        * LUstruct     = (LUstruct_t*)LUstructPtr_;
   ^~~~~~~~~~
   dLUstruct_t
```
etc.
I’m compiling MFEM from the current Master branch, and the SuperLU version was installed via PETSc v. 3.13.1.

**Comment by stefanhenneking** [comment]
See also the following related issue in hypre: https://github.com/hypre-space/hypre/issues/105

**Comment by tzanio** [comment]
Hi @pghysels,

Did the SuperLU interface change recently? Can you help us fix the build issues in MFEM?

Thanks in advance!
Tzanio

**Comment by pghysels** [comment]
I will look into it.

**Comment by tzanio** [comment]
Discussion continued in #1528
