### ISSUE TITLE
MFEM_USE_METIS_5 not correctly set with Cmake

### ISSUE THREAD

**Issue by stefanhenneking** [mfem/mfem#1523]
Compiling MFEM (from the current Master branch) and linking to METIS 5.1.0 with CMake (version 3.17.2), I obtained the following error when `cmake --build . --target check` after building:
```
Undefined symbols for architecture x86_64:
  "_METIS_PartGraphVKway", referenced from:
      mfem::Mesh::GeneratePartitioning(int, int) in libmfem.a(mesh.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [examples/ex1p] Error 1
make[2]: *** [examples/CMakeFiles/ex1p.dir/all] Error 2
make[1]: *** [CMakeFiles/check.dir/rule] Error 2
make: *** [check] Error 2
```
It appears the `MFEM_USE_METIS_5` variable is not set correctly and the code attempts linking for the functions in `mesh.cpp` such as `void METIS_PartGraphVKway` not defined in METIS 5.

I was able to solve the issue by adding `option(MFEM_USE_METIS_5 "Enable METIS 5" ON)` to `user.cmake` (or, equivalently, `defaults.cmake`). 

However, according to `INSTALL` the option `MFEM_USE_METIS_5` should be auto-detected.

**Comment by v-dobrev** [comment]
Can you try this: run the CMake config step where metis 5 is not auto-detected correctly and then take a look inside the file `CMakeFiles/CMakeError.log`. There should be a line like this:
```ascii
Performing C++ SOURCE FILE Test METIS_VERSION_5 failed with the following output:
```
with some errors reported after it -- these should explain why auto-detection failed.

**Comment by stefanhenneking** [comment]
In the `CMakeError.log` is no statement about METIS.
However, in `CMakeCache.txt`, the following lines are generated:
```
//Path to the METIS library.
METIS_DIR:PATH=/Users/stefan/LLNL/LIBS/parmetis-4.0.3

//METIS was found.
METIS_FOUND:BOOL=TRUE

//Path to the METIS include dir.
METIS_INCLUDE_DIRS:PATH=/Users/stefan/LLNL/LIBS/parmetis-4.0.3/metis/include

//Path to libmetis.
METIS_LIBRARIES:PATH=/Users/stefan/LLNL/LIBS/parmetis-4.0.3/build/Darwin-x86_64/libmetis/libmetis.a

//Is METIS version 5?
METIS_VERSION_5:BOOL=
```
Note that I set the `METIS_INCLUDE_DIRS` and `METIS_LIBRARIES` myself in `user.cmake`.

**Comment by v-dobrev** [comment]
Oh, okay. If you set `METIS_INCLUDE_DIRS` and/or `METIS_LIBRARIES` directly the auto-detection is not run, so you have to define `METIS_VERSION_5` manually as well.

**Comment by stefanhenneking** [comment]
I see... Setting `METIS_DIR` and `ParMETIS_DIR` to the ParMETIS directory didn't work (it wouldn't automatically find the paths to the library and include files within `/Users/stefan/LLNL/LIBS/parmetis-4.0.3`) so I set the include path and libraries directly, but I wasn't aware it would disable this auto-detection for the METIS version. Thank you for the clarification! I'll close this issue for now and hope that anybody who runs into the same problem will consult the github search in the repo and find your answer. Many thanks!

**Comment by v-dobrev** [comment]
You are welcome.

Just to clarify: `METIS_DIR` is expected to point to an **installation** of the library, so it searches paths like `${METIS_DIR}/include` for `metis.h` and `${METIS_DIR}/lib` for the library file. As a backup, it searches a few other places but not the one used by the cmake build process for METIS 5. Similar rule applies to `ParMETIS_DIR`. Therefore, I'll just recommend you install the libraries in some directory and give that path to mfem's cmake.
