### ISSUE TITLE
Example of activating the reference volumetric scaling in the NeoHookean model

### ISSUE THREAD

**Issue by tengzhang48** [mfem/mfem#1525]
Dear all,

I am new to MFEM and learning it through a few examples. I noticed that there is a parameter "g" in the NeoHookean model to represent the reference volumetric scaling. I tried to modify the example (ex10p.cpp) to activate it, but had some errors. I also attached the modified file in .txt file. 

I can run ex10p without modifying it. Can someone help me take a look at the modified code? I think I miss some set up, but am not very familiar with MFEM now. 

Thanks.

Best,
Teng

[ex10p_volume.txt](https://github.com/mfem/mfem/files/4741101/ex10p_volume.txt)

**Comment by rcarson3** [comment]
@tengzhang48 looking over your code it looks like your just passing the ```g``` parameter into the ```NeoHookean``` model, so I didn't see anything wrong with that part. I did find that I had to change the default dt to be 1.0 rather than 3.0 to run with the ```g = 1.01``` when I modified the default example 10.

**Comment by tengzhang48** [comment]
@rcarson3 Thanks for checking it. I had compiling errors before and did not see it after I re-compiled the MFEM. Now I can run the example. Since g will cause deformation as well, it is reasonable that the time step is smaller. Thanks for your help.

**Comment by rcarson3** [comment]
@tengzhang48 it sounds like things are now working on your end. So, I'm going to close this issue. If you run into any other issues related to this feel free to reopen it.
