### ISSUE TITLE
How can I obtain the coordinates of the mesh ?

### ISSUE THREAD

**Issue by LeilaSalomon** [mfem/mfem#1530]
Hello !

I'm interested to know the simplest way to obtain the coordinates of the nodes of the mesh?

Best,

Leïla

**Comment by rw-anderson** [comment]
Take a look at the GetVertex() method in the mesh class.  There's an example usage in ex25.cpp.

Does that do what you want?

**Comment by LeilaSalomon** [comment]
Yes !!! Thank you :D
