### ISSUE TITLE
Please make native optimizations conditional on a cmake variable

### ISSUE THREAD

**Issue by yurivict** [mfem/mfem#1532]
Here: https://github.com/mfem/mfem/blob/master/miniapps/performance/CMakeLists.txt#L15

This is required for packaging.

**Comment by v-dobrev** [comment]
I'm not sure I understand: this directory is not installed (by CMake), so for packaging it is not necessary to build it.

Maybe you are enabling `MFEM_ENABLE_EXAMPLES` and/or `MFEM_ENABLE_MINIAPPS` and that is causing the problem? These options enable the examples/miniapps to be built but they will not be installed by CMake.

**Comment by yurivict** [comment]
Sorry, I think I made a mistake.

Now I can't find -march=native in build logs.
