### ISSUE TITLE
How can deal with the  advection–diffusion equation

### ISSUE THREAD

**Issue by fengerhan** [mfem/mfem#1534]
hello,  for Variational formulation of the advection–diffusion equation
(K∇u, ∇v) − (wu, ∇v) + (ru, v) = (f, v) ∀v ∈ H1
I know that I can use DiffusionIntegrator to deal with  (K∇u, ∇v).
But who can tell me how to deal with (wu, ∇v) ?

please send reply to email:hanfenger@126.com

Thanks !

**Comment by mlstowell** [comment]
That would be the `MixedScalarWeakDivergenceIntegrator` found on the [Scalar Field Operators](https://mfem.org/bilininteg/#scalar-field-operators) page.

We really prefer to keep all communication within GitHub's issue tracker for various reasons.
