### ISSUE TITLE
Contact mechanics and "developer" documentation

### ISSUE THREAD

**Issue by jfauque** [mfem/mfem#1535]
Good morning,
I'm interested in MFEM to resolve mechanical problems with FE method. 
If I well understood there is nothing in the last versions to solve contact problems but I saw on issue [#1509](https://github.com/mfem/mfem/issues/1509) that some people are currently working on it. Thus what kind of method do you plan to develop in MFEM to treat contact ?
I read some documentations about MFEM but it looks for me "users" oriented, do you have some documentation (other than doxygen) for people who want to develop new features ? 
Thanks in advance

**Comment by barker29** [comment]
The work on contact in MFEM is still in very early stages. One example of the kind of thing we're looking at is mortar methods, but we are hoping to implement contact on the linear algebra level rather than the finite element level. That is, whatever contact formulation the user has they will be responsible for implementing, but the constrained linear system that results will be our responsibility to solve efficiently.

Does that answer your question?

**Comment by jfauque** [comment]
Thanks for the response. You clearly answered my first question. 
What about the second one ? Do you use only doxygen as documentation ? Or maybe you have an unofficial one just for people developing in MFEM ?
I think if you don't have it, it would help people who want to contribute to the code.

**Comment by tzanio** [comment]
Hi @jfauque,

In addition to the Doxygen documentation of the code, we also have some developer-oriented description in https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md. A good place to start is to review what is available in the examples and miniapps.

If you are interested in developing new features, I will suggest that you open an issues where we can discuss what you are trying to achieve and what is the best design for that.  Some finite element documentation is also available on this page: https://mfem.org/fem/ and the pages it links to.

Finally, there is also this paper: https://arxiv.org/abs/1911.09220, which provides a broad overview of the library.

Hope this helps,
Tzanio

**Comment by jfauque** [comment]
Thank you very much to both of you for your reactivity.
