### ISSUE TITLE
`BilinearFormIntegrator` on part of the mesh

### ISSUE THREAD

**Issue by thelfer** [mfem/mfem#1536]
Dear all,

I wanted to know if I can create a bilinear form integrator only on part of the mesh.

The rationale behind this is to support multi-material non linear mechanics simulations.

My idea is to create a bilinear for each material. That would allow mixing finite strain behaviours and small strain behaviours.

I did the following attempt:

- Create a copy of the `ElasticityIntegrator` class which takes the Lamé coefficients as arguments and a mesh attribute (the material id)
- Modify the implementation of the methods `AssembleElementMatrix`, `ComputeElementFlux` and `ComputeFluxEnergy` to return immediatly of the element is not part of the material. For example:

~~~~{.cxx}
  void MGISIntegrator::AssembleElementMatrix(const mfem::FiniteElement &el,
                                             mfem::ElementTransformation &Trans,
                                             mfem::DenseMatrix &elmat) {
   int dof = el.GetDof();
    int dim = el.GetDim();
    elmat.SetSize(dof * dim);


    if (Trans.Attribute != this->material_id) {
      elmat = 0.;
      return;
    }
~~~~

I then modified the second example to add one bilinear for integrator per material, as follows:

~~~~{.cxx}
  BilinearForm *a = new BilinearForm(fespace);
  a->AddDomainIntegrator(new mfem_mgis::MGISIntegrator(*fespace, 0, 50, 50));
  a->AddDomainIntegrator(new mfem_mgis::MGISIntegrator(*fespace, 1, 1, 1));
~~~~

And .... this currently fails.

For the moment, I would just like to know if my initial idea is good (and that there is just a bug somewhere in my code, but that woud my problem) or totally dumb. If anyone has an better idea to do what I need, please let me know.

**Comment by psocratis** [comment]
Hi @thelfer , 

You can use the RestrictedCoefficient class. It does exactly what you need. You can take a look on how it's used in ex25/ex25p. 

Hope this helps. 

Socratis

**Comment by thelfer** [comment]
@psocratis Thanks for the link. However, it does not seem obivious how `RestrictedCoefficient` could solve my initial request.

> My idea is to create a bilinear for each material.
> That would allow mixing finite strain behaviours and small strain behaviours.

I really wish to have distinct *bilinear forms* on each material. Have I missed something ?

I'll also have a closer look at example 25 anyway.

**Comment by psocratis** [comment]
> @psocratis Thanks for the link. However, it does not seem obivious how `RestrictedCoefficient` could solve my initial request.
> 
> > My idea is to create a bilinear for each material.
> > That would allow mixing finite strain behaviours and small strain behaviours.
> 
> I really wish to have distinct _bilinear forms_ on each material. Have I missed something ?
> 
> I'll also have a closer look at example 25 anyway.

The example 25 deals with a PML implementation for Maxwell equations. The domain is separated into two regions, one in the computational domain and the other is the PML region where the wave is absorbed. The distinction between the two is done using element attributes. 
Using the element attributes and the restricted coefficient, Bilinear form integrators are constructed only inside the 1st or the 2nd region. 

Isn't this something similar to what you need? In your case each material will define a different element attribute/ different region. 

Thanks, 
Socratis

**Comment by thelfer** [comment]
@psocratis I guess I will need to study closely this example. Thanks for your time and patience.

**Comment by psocratis** [comment]
> @psocratis I guess I will need to study closely this example. Thanks for your time and patience.

Sure, no problem. 

Let us know how it goes...

Thanks,

Socratis

**Comment by thelfer** [comment]
@psocratis As I understand Example 25, the idea is to set some coefficients to zero so that the contributions to the stiffness matrix is 0 outside the considered material. 

This is not exactly what I need, because I am interested to non linear mechanics which require a considerable amount of work at each integration point. The equivalent of the what is done with the `RestrictedCoefficient` trick  would be to perform a dummy behaviour integration with a zero time step and a zero strain increment.

I finally found my (stupid) mistake in my example, so this code indeed work:

~~~~{.cxx}
void MGISIntegrator::AssembleElementMatrix(const mfem::FiniteElement &el,
                                             mfem::ElementTransformation &Trans,
                                             mfem::DenseMatrix &elmat) {
   int dof = el.GetDof();
    int dim = el.GetDim();
    elmat.SetSize(dof * dim);


    if (Trans.Attribute != this->material_id) {
      elmat = 0.;
      return;
    }

~~~~

I do prefer this solution. But I do thank you for your help :+1:

**Comment by psocratis** [comment]
That it's correct (about the RestrictedCoefficient). 

I am glad it works!

Socratis
