### ISSUE TITLE
Interface Inconsistencies

### ISSUE THREAD

**Issue by termi-official** [mfem/mfem#1541]
Hi again,

is there some central place where inconsistencies (e.g. in the naming) are tracked?

To clarify, I mean for example these three method names are inconsistent with the underlying semantics

* https://github.com/mfem/mfem/blob/657c64ac2432905d9ea779734daf8e090fd46f04/mesh/mesh.hpp#L716-L717
* https://github.com/mfem/mfem/blob/657c64ac2432905d9ea779734daf8e090fd46f04/mesh/pmesh.hpp#L298-L299
* https://github.com/mfem/mfem/blob/657c64ac2432905d9ea779734daf8e090fd46f04/mesh/mesh.hpp#L719-L720

or some simpler things like mixing "Bdr" and "Boundary" in the mesh (so, consistent semantics with inconsistent naming), e.g.

* https://github.com/mfem/mfem/blob/657c64ac2432905d9ea779734daf8e090fd46f04/mesh/mesh.hpp#L529
* https://github.com/mfem/mfem/blob/657c64ac2432905d9ea779734daf8e090fd46f04/mesh/mesh.hpp#L523

Since I run into such inconsistencies from time to time, I just wondered if there is a tracker where I could report these. I should also ask in the first place, whether there is interest in tracking such minor issues.

Best regards,
Dennis

**Comment by rw-anderson** [comment]
I feel like I have seen a list of very similar issues before.  Maybe @mlstowell was leading the charge on that if memory serves?

**Comment by barker29** [comment]
Hi @termi-official , I had maintained an informal list of such issues, and your comments have motivated us to clean it up a little and make it public as #1557 . We would be happy to see your additions to the list there.

**Comment by termi-official** [comment]
Hi @barker29 , great to read this. 
So, I guess we should close this one and move the discussion to the new issue? Or should we keep this one open and devote it to semantic/feature issue (like my first example with the face number)?

**Comment by tzanio** [comment]
Lets move the discussion to the new issue. It will be easier to keep track in one place.
