### ISSUE TITLE
How to import GMSH file in the multi-domain problem such as ex2?

### ISSUE THREAD

**Issue by diliu1994** [mfem/mfem#1544]
I have tried the GMSH input file to import to the MFEM ex2. However, I have met the problem shown below:
"Input mesh should have at least two materials and two boundary attributes! (See schematic in ex2.cpp)"
The attached file is my mesh file. Could anyone help me solve this problem?
[tst_mfem.msh.txt](https://github.com/mfem/mfem/files/4775613/tst_mfem.msh.txt)

**Comment by sshiraiwa** [comment]
Hi @diliu1994,
The attached mesh defines only the surface mesh (triangles) but not volume (tetrahedra). I think you need to mesh 3D first and then you need to define physical domain for volumes.

**Comment by diliu1994** [comment]
Hi @sshiraiwa 
Now, I have tried saving all the meshes options. But still there is problem:
 "MFEM abort: Non-positive element attribute in Gmsh mesh!
 ... in function: void mfem::Mesh::ReadGmshMesh(std::basic_istream<char, std::char_traits<char>> &)
 ... in file: mesh/mesh_readers.cpp:1172"

The attached file is the new mesh file.
[tst_mfem_1.msh.txt](https://github.com/mfem/mfem/files/4775720/tst_mfem_1.msh.txt)

**Comment by diliu1994** [comment]
Also, I have attached my .geo file to see if there is anything wrong in this file.
[tst.geo.txt](https://github.com/mfem/mfem/files/4775752/tst.geo.txt)

**Comment by sshiraiwa** [comment]
@diliu1994,
I don't use .geo file anymore, and can not help much in terms of how to change it. But, opening your .geo file, it seems you have too many elements. For example, there is 39 curves. For this geometry, you need only 20 curves, don't you. Probably you have many duplicate entities in the geometry. You can perhaps either clean it or use fragment.

**Comment by mlstowell** [comment]
Hello, @diliu1994 ,

I think @sshiraiwa was on the right track.  Your `Extrude` command was creating extra entities which were not be assigned physical tags.  These entities appeared with their tags equal to zero and MFEM does not support this (partly to help track down issues like this).  I think another issue is the use of `+=` when declaring your physical volumes.  These physical volumes weren't created yet so this lead to an error message when I ran the file in Gmsh.  I believe the following modified `.geo` file may work for you.
```
// Gmsh project created on Wed Jun 10 15:14:52 2020
SetFactory("OpenCASCADE");
//+
Point(1) = {0, 0, 0, 1.0};
//+
Point(2) = {5.5, 0, 0, 1.0};
//+
Point(3) = {5.5, 0, 5.5, 1.0};
//+
Point(4) = {0, 0, 5.5, 1.0};
//+
Point(5) = {0, 0, 5, 1.0};
//+
Point(6) = {5.5, 0, 5, 1.0};
//+
Line(1) = {3, 6};
//+
Line(2) = {6, 2};
//+
Line(3) = {2, 1};
//+
Line(4) = {1, 5};
//+
Line(5) = {5, 4};
//+
Line(6) = {4, 3};
//+
Line(7) = {6, 5};
//+
Curve Loop(1) = {2, 3, 4, -7};
//+
Plane Surface(1) = {1};
//+
Curve Loop(2) = {6, 1, 7, 5};
//+
Plane Surface(2) = {2};
//+
Extrude {0, 5.5, 0} {
  Surface{2}; Surface{1};
}

//+
Transfinite Curve {18, 5, 1, 21} = 2 Using Progression 1;
//+
Physical Surface("left",1) = {9, 4};
//+
Physical Surface("right", 2) = {7, 6};
//+
Physical Surface("other BC", 3) = {14, 18, 3, 2, 1, 8};

//+
Physical Volume("toplayer", 1) = {1};
//+
Physical Volume("botlayer", 2) = {2};

//+ Generate 3D mesh
Mesh 3;

Mesh.MshFileVersion = 2.2;
Save "tst_mod.msh";
```

Best wishes,
Mark

**Comment by Sladewilson-arrow** [comment]
Hello, @diliu1994,
Use the following file and save with vesion 4.0 ASCII. Input that generated mesh to ex2.cpp
// Gmsh project created on Wed Jun 10 15:14:52 2020
SetFactory("OpenCASCADE");
//+
Point(1) = {0, 0, 0, 1.0};
//+
Point(2) = {5.5, 0, 0, 1.0};
//+
Point(3) = {5.5, 0, 5.5, 1.0};
//+
Point(4) = {0, 0, 5.5, 1.0};
//+
Point(5) = {0, 0, 5, 1.0};
//+
Point(6) = {5.5, 0, 5, 1.0};
//+
Line(1) = {3, 6};
//+
Line(2) = {6, 2};
//+
Line(3) = {2, 1};
//+
Line(4) = {1, 5};
//+
Line(5) = {5, 4};
//+
Line(6) = {4, 3};
//+
Line(7) = {6, 5};
//+
Curve Loop(1) = {2, 3, 4, -7};
//+
Plane Surface(1) = {1};
//+
Curve Loop(2) = {6, 1, 7, 5};
//+
Plane Surface(2) = {2};
//+
Extrude {0, 5.5, 0} {
  Surface{2}; Curve{6}; Point{4}; Curve{5}; Point{5}; Curve{7}; Point{6}; Curve{1}; Point{3}; Surface{1}; Curve{2}; Point{2}; Curve{3}; Point{1}; Curve{4}; 
}

//+
Transfinite Curve {18, 5, 1, 21} = 10 Using Progression 1;
//+
Physical Surface("left",1) = {9, 4};
//+
Physical Surface("right", 2) = {7, 6};
//+
Physical Surface("other BC", 3) = {14, 18, 3, 2, 1, 8};

//+
Physical Volume("v1") = {2};
//+
Physical Volume("v2") = {1}; 

Export the mesh to *.msh of version 4.0 ASCII.

(in mfem) Run : ./ex2.cpp -m $(path to mesh file )

Best regards,
Slade.

**Comment by diliu1994** [comment]
@mlstowell Hi, I have tried your method and modified the physical domain part. Now it works for MFEM.

Best regards,
Di

**Comment by diliu1994** [comment]
@Sladewilson-arrow 
Hi, I have tried your method and import the ASII version4 for GMSH input. However, it occurs another problem that it says the vertices number is not unique. However, I can import the GMSH with modified ASII version2. So I think this problem is solved. Thanks for replying.

Best,
Di
