### ISSUE TITLE
Parallel mesh cut where some of the elements belong to the same process

### ISSUE THREAD

**Issue by thorvath12** [mfem/mfem#1547]
Hi,

In #406 I asked for help to create a parallel mesh when I know exactly the partitioning and I was pointed out that one of the constructors can do that.

Now I have a problem that is one step further: I want to keep some of the elements on the same process, but the rest of the mesh can be partitioned arbitrarily. Is there a way to do that?

Thanks in advance.
Tamas

**Comment by tzanio** [comment]
You can take a look at the implementation of `Mesh::GeneratePartitioning` and maybe modify it to your needs?

https://github.com/mfem/mfem/blob/b8ab8fce47d9081a3a7bf311b1025f64af9ce54d/mesh/mesh.cpp#L5531

Basically we just create the element connectivity graph and call a METIS function to partition it. In your case, you may want to exclude the elements you fix from the graph, and partition the rest?

**Comment by thorvath12** [comment]
Thanks @tzanio, this might help.

In some of the cases, if I exclude the elements I want to fix, I will end up with 2 disjoint meshes. Do you think that could cause a problem?

**Comment by tzanio** [comment]
Disjoint meshes should not be a problem.

**Comment by thorvath12** [comment]
That's excellent, thank you! I'll close this issue for now, I might reopen if I run into any trouble.
