### ISSUE TITLE
Generate parallel mesh files from a single process

### ISSUE THREAD

**Issue by Andr00dz** [mfem/mfem#1549]
Hi,

I encountered a similar problem as describes in #934. I have a large mesh file that cannot be loaded in parallel from all ranks simultaneously for memory reasons. The pre processing method, which was introduced there seemed appropriate for my purposes.

My question is now the following: Is there an easy way to generate ParMesh files for a given number of processes in a serial way with one single large mesh load? With ParMesh files I mean files that are created from the ParPrint method and can be loaded afterwards from the ParMesh constructor.

I'm looking for a mesh function that creates for a given partition and number i, the corresponding ParMesh file of the i-th part corresponding to the partition. The mesh function PrintWithPartitioning produces files that are different from the files generated by ParPrint.

Thanks in advance,
Andreas

**Comment by tzanio** [comment]
If I understand correctly, this will be covered by https://github.com/mfem/mfem/issues/1540#issuecomment-645652511.

If that's the case, can we consolidate to that issue?

**Comment by Andr00dz** [comment]
Yes, the miniapp you describe in https://github.com/mfem/mfem/issues/1540#issuecomment-645652511 is exactly what I'm looking for. A miniapp that reads the large mesh only once and then partitions the mesh for a given number `P` into `P` files, which can be later read in parallel by the ParMesh constructor.

**Comment by tzanio** [comment]
Discussion continued in #1540.

**Comment by v-dobrev** [comment]
See https://github.com/mfem/mfem/pull/2669.
