### ISSUE TITLE
parallel norm/dot computation and Krylov

### ISSUE THREAD

**Issue by ben-s-southworth** [mfem/mfem#1552]
In the Krylov methods, there are calls along the lines of
```
double beta = Norm(r);  // beta = ||r||
H(k,i) = Dot(w, *v[k]);  // H(k,i) = w * v[k]
```
But these are using (non-parallel) MFEM vectors. If, say, GMRES is applied in parallel, shouldn't the orthogonalization be global in nature? I imagine if the dot product and norm are computed locally (on processor) this would yield different results than a global orthogonalization. Am I missing something here?

**Comment by pazner** [comment]
Yes, of course the orthogonalization has to be global. Notice that `IterativeSolver::Dot` (defined in `solvers.cpp`) ends up calling `inline double InnerProduct(MPI_Comm comm, const Vector &x, const Vector &y)` which in turn calls `MPI_Allreduce` to compute the global reduction.

**Comment by ben-s-southworth** [comment]
My bad, thanks @pazner - I was looking at the definitions in the Vector class.
