### ISSUE TITLE
Quasi-periodic boundary condition

### ISSUE THREAD

**Issue by PanuLappalainen** [mfem/mfem#1553]
Dear MFEM team,

We are interested in implementing quasi-periodic (Bloch) boundary condition on the two opposing face pairs on a 3D rectangular domain:
![GLVis_s01(1)](https://user-images.githubusercontent.com/66424587/84903786-3309b780-b0b7-11ea-9421-ef8805ac1cf0.png)
![CodeCogsEqn(3)](https://user-images.githubusercontent.com/66424587/84905241-153d5200-b0b9-11ea-9981-d91c9956d8c9.gif)
where _kx,ky_ are the wave vector components in the x-y direction.

Is it possible to implement this boundary condition using existing Bilinear and Linear Integrators in MFEM? (The solution _u_ is assumed to be complex valued here.)

Many thanks,
Panu

**Comment by mlstowell** [comment]
Hello, @PanuLappalainen ,

Yes, this is certainly possible.  As I'm sure you know, the Bloch wave assumption is that your solution `u` can be written as the product of a short wavelength periodic solution `v` and a longer wavelength sinusoidal term `exp(i k.x)`.  In MFEM we can solve for the short wavelength field `v` by imposing periodic boundary conditions on your mesh and then modifying your PDE.  The trick is to substitute `u=v exp(i k.x)` into your PDE to obtain a modified PDE for `v`.

Best wishes,
Mark
