### ISSUE TITLE
Trouble with compiling MFEM with CUDA

### ISSUE THREAD

**Issue by sshiraiwa** [mfem/mfem#1555]
Hi all,
I am trying to compile MFEM with GPU, and getting an error (below).  I am doing this on TRAVERSE cluster at Princeton Univ. (https://researchcomputing.princeton.edu/systems-and-services/available-systems/traverse). 
It seems like the error is coming from somewhere around autosimd, and in fact,  workaround I found so far is to use MFEM_USE_SIMD=OFF. I have two question.

1) My hope is to test GPU on this cluster. Does MFEM_USE_SIMD=OFF impact the performance?
If so, is there other option?
2) This cluster uses Power9. Does this relate to the error?

Thank you for your help

[shiraiwa@traverse cmbuild]$ cmake .. -DCMAKE_VERBOSE_MAKEFILE=1 -DCMAKE_INSTALL_PREFIX=${HOME}/sandbox/mfem/ser -DMFEM_USE_CUDA=1
-- (optional) USER_CONFIG = /home/shiraiwa/src/mfem/config/user.cmake
-- USE_XSDK_DEFAULTS = 'OFF'
-- The CXX compiler identification is GNU 4.8.5
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The CUDA compiler identification is NVIDIA 10.2.89
-- Check for working CUDA compiler: /usr/local/cuda-10.2/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda-10.2/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Using CUDA architecture: sm_60
-- Looking for POSIXClocks ...
--    checking library: <standard c/c++>
-- Found POSIXClocks: TRUE  
-- MFEM: using package POSIXCLOCKS
-- MFEM build type: CMAKE_BUILD_TYPE = Release
-- MFEM version: v4.1.1
-- MFEM git string: heads/master-0-gb8ab8fce47d9081a3a7bf311b1025f64af9ce54d
-- Writing substitute header --> "mfem.hpp"
-- Writing substitute header --> "mfem-performance.hpp"
-- performance_ex1: add flags "-Xcompiler=-mcpu=native -Xcompiler=-mtune=native -Xcompiler=-Wall"
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.5") found components:  doxygen dot 
-- CMAKE_INSTALL_PREFIX = /home/shiraiwa/sandbox/mfem/ser
-- Configuring done
-- Generating done
-- Build files have been written to: /home/shiraiwa/src/mfem/cmbuild

[shiraiwa@traverse cmbuild]$ make -j 4
/usr/bin/cmake3 -S/home/shiraiwa/src/mfem -B/home/shiraiwa/src/mfem/cmbuild --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake3 -E cmake_progress_start /home/shiraiwa/src/mfem/cmbuild/CMakeFiles /home/shiraiwa/src/mfem/cmbuild/CMakeFiles/progress.marks

.... (long successful compile. and this file fails)

[ 25%] Building CUDA object CMakeFiles/mfem.dir/linalg/matrix.cpp.o
/usr/local/cuda-10.2/bin/nvcc  -DMFEM_CONFIG_FILE=\"/home/shiraiwa/src/mfem/cmbuild/config/_config.hpp\"  -arch=sm_60 --expt-extended-lambda -ccbin /usr/bin/c++ -O3 -DNDEBUG   -std=c++11 -x cu -c /home/shiraiwa/src/mfem/linalg/matrix.cpp -o CMakeFiles/mfem.dir/linalg/matrix.cpp.o
/home/shiraiwa/src/mfem/linalg/../linalg/simd/vsx128.hpp(55): error: identifier "__builtin_vec_splats" is undefined

/home/shiraiwa/src/mfem/linalg/../linalg/simd/vsx128.hpp(61): error: identifier "__builtin_vec_add" is undefined

/home/shiraiwa/src/mfem/linalg/../linalg/simd/vsx128.hpp(67): error: identifier "__builtin_vec_splats" is undefined

/home/shiraiwa/src/mfem/linalg/../linalg/simd/vsx128.hpp(67): error: identifier "__builtin_vec_add" is undefined

/home/shiraiwa/src/mfem/linalg/../linalg/simd/vsx128.hpp(73): error: identifier "__builtin_vec_sub" is undefined

/home/shiraiwa/src/mfem/linalg/../linalg/simd/vsx128.hpp(79): error: identifier "__builtin_vec_splats" is undefined

/home/shiraiwa/src/mfem/linalg/../linalg/simd/vsx128.hpp(79): error: identifier "__builtin_vec_sub" is undefined

/home/shiraiwa/src/mfem/linalg/../linalg/simd/vsx128.hpp(85): error: identifier "__builtin_vec_mul" is undefined

/home/shiraiwa/src/mfem/linalg/../linalg/simd/vsx128.hpp(91): error: identifier "__builtin_vec_splats" is undefined

/home/shiraiwa/src/mfem/linalg/../linalg/simd/vsx128.hpp(91): error: identifier "__builtin_vec_mul" is undefined

/home/shiraiwa/src/mfem/linalg/../linalg/simd/vsx128.hpp(97): error: identifier "__builtin_vec_div" is undefined

/home/shiraiwa/src/mfem/linalg/../linalg/simd/vsx128.hpp(103): error: identifier "__builtin_vec_splats" is undefined

/home/shiraiwa/src/mfem/linalg/../linalg/simd/vsx128.hpp(103): error: identifier "__builtin_vec_div" is undefined

/home/shiraiwa/src/mfem/linalg/../linalg/simd/vsx128.hpp(110): error: identifier "vec_neg" is undefined

/home/shiraiwa/src/mfem/linalg/../linalg/simd/vsx128.hpp(117): error: identifier "__builtin_vec_add" is undefined

/home/shiraiwa/src/mfem/linalg/../linalg/simd/vsx128.hpp(124): error: identifier "__builtin_vec_splats" is undefined

/home/shiraiwa/src/mfem/linalg/../linalg/simd/vsx128.hpp(124): error: identifier "__builtin_vec_add" is undefined

/home/shiraiwa/src/mfem/linalg/../linalg/simd/vsx128.hpp(131): error: identifier "__builtin_vec_sub" is undefined

/home/shiraiwa/src/mfem/linalg/../linalg/simd/vsx128.hpp(138): error: identifier "__builtin_vec_splats" is undefined

/home/shiraiwa/src/mfem/linalg/../linalg/simd/vsx128.hpp(138): error: identifier "__builtin_vec_sub" is undefined

/home/shiraiwa/src/mfem/linalg/../linalg/simd/vsx128.hpp(145): error: identifier "__builtin_vec_mul" is undefined

/home/shiraiwa/src/mfem/linalg/../linalg/simd/vsx128.hpp(152): error: identifier "__builtin_vec_splats" is undefined

/home/shiraiwa/src/mfem/linalg/../linalg/simd/vsx128.hpp(152): error: identifier "__builtin_vec_mul" is undefined

/home/shiraiwa/src/mfem/linalg/../linalg/simd/vsx128.hpp(159): error: identifier "__builtin_vec_div" is undefined

/home/shiraiwa/src/mfem/linalg/../linalg/simd/vsx128.hpp(166): error: identifier "__builtin_vec_splats" is undefined

/home/shiraiwa/src/mfem/linalg/../linalg/simd/vsx128.hpp(166): error: identifier "__builtin_vec_div" is undefined

/home/shiraiwa/src/mfem/linalg/../linalg/simd/vsx128.hpp(172): error: identifier "__builtin_vec_madd" is undefined

/home/shiraiwa/src/mfem/linalg/../linalg/simd/vsx128.hpp(178): error: identifier "__builtin_vec_splats" is undefined

/home/shiraiwa/src/mfem/linalg/../linalg/simd/vsx128.hpp(178): error: identifier "__builtin_vec_madd" is undefined

/home/shiraiwa/src/mfem/linalg/../linalg/simd/vsx128.hpp(184): error: identifier "__builtin_vec_splats" is undefined

/home/shiraiwa/src/mfem/linalg/../linalg/simd/vsx128.hpp(184): error: identifier "__builtin_vec_madd" is undefined

/home/shiraiwa/src/mfem/linalg/../linalg/simd/vsx128.hpp(190): error: identifier "__builtin_vec_mul" is undefined

/home/shiraiwa/src/mfem/linalg/../linalg/simd/vsx128.hpp(196): error: identifier "__builtin_vec_splats" is undefined

/home/shiraiwa/src/mfem/linalg/../linalg/simd/vsx128.hpp(196): error: identifier "__builtin_vec_mul" is undefined

/home/shiraiwa/src/mfem/linalg/../linalg/simd/vsx128.hpp(202): error: identifier "__builtin_vec_splats" is undefined

/home/shiraiwa/src/mfem/linalg/../linalg/simd/vsx128.hpp(202): error: identifier "__builtin_vec_mul" is undefined

/home/shiraiwa/src/mfem/linalg/../linalg/simd/vsx128.hpp(212): error: identifier "__builtin_vec_splats" is undefined

/home/shiraiwa/src/mfem/linalg/../linalg/simd/vsx128.hpp(212): error: identifier "__builtin_vec_add" is undefined

/home/shiraiwa/src/mfem/linalg/../linalg/simd/vsx128.hpp(221): error: identifier "__builtin_vec_splats" is undefined

/home/shiraiwa/src/mfem/linalg/../linalg/simd/vsx128.hpp(221): error: identifier "__builtin_vec_sub" is undefined

/home/shiraiwa/src/mfem/linalg/../linalg/simd/vsx128.hpp(230): error: identifier "__builtin_vec_splats" is undefined

/home/shiraiwa/src/mfem/linalg/../linalg/simd/vsx128.hpp(230): error: identifier "__builtin_vec_mul" is undefined

/home/shiraiwa/src/mfem/linalg/../linalg/simd/vsx128.hpp(239): error: identifier "__builtin_vec_splats" is undefined

/home/shiraiwa/src/mfem/linalg/../linalg/simd/vsx128.hpp(239): error: identifier "__builtin_vec_div" is undefined

/home/shiraiwa/src/mfem/linalg/densemat.cpp(1955): error: cannot overload functions distinguished by return type alone

/home/shiraiwa/src/mfem/linalg/densemat.cpp(2865): error: declaration is incompatible with "__nv_bool mfem::LUFactors::Factor(int, double)"
/home/shiraiwa/src/mfem/linalg/../fem/../linalg/densemat.hpp(541): here

46 errors detected in the compilation of "/tmp/tmpxft_0001db59_00000000-6_densemat.cpp1.ii".
make[2]: *** [CMakeFiles/mfem.dir/linalg/densemat.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory `/home/shiraiwa/src/mfem/cmbuild'
make[1]: *** [CMakeFiles/mfem.dir/all] Error 2
make[1]: Leaving directory `/home/shiraiwa/src/mfem/cmbuild'

**Comment by camierjs** [comment]
You are right: some compilers (`gcc@power`) re-define `bool` as vectors which breaks the compilation.

The workaround you found is the good one for now, until we push the correction.

It won't impact the performance unless you try to use the `templated` code in `miniapps/performance`.

**Comment by sshiraiwa** [comment]
@camierjs Thank you for the prompt response.
