### ISSUE TITLE
Contribution workflow for minor changes (update/fixes) to the code

### ISSUE THREAD

**Issue by mortezah** [mfem/mfem#1559]
While there are detailed instructions on how to contribute in regards to new features, I was not able to find any instructions on how minor changes to the code should be handled. Should I just treat them as new features and submit a pull request for those as well?

**Comment by v-dobrev** [comment]
Yes, please follow the same workflow.

We typically try to expedite the review process for small updates and bugfixes so the overall time should be shorter.

**Comment by mortezah** [comment]
Thanks. Will do.
