### ISSUE TITLE
Compute local conservation

### ISSUE THREAD

**Issue by fanronghong** [mfem/mfem#1562]
Hi all,

I want to verify local conservation which is a post-process. So I need to compute $\int_{\partial K} q \nabla\phi \cdot \mathbf{n}$ for every element $K$.

I have two questions:
1. Is there an elegant way to compute the quantity? If 'yes', please give me a demo.
2. If use the below way, how to compute the gradient of `gf`?

Thanks in advance!
```
void ComputeLocalConservation(Coefficient& q, const GridFunction& gf, Vector& error)
{
    const FiniteElementSpace* fes = gf.FESpace();
    Mesh* mesh = fes->GetMesh();
    const FiniteElement* fe;
    int dim = mesh->Dimension();

    Vector grad, nor;
    grad.SetSize(dim);
    nor.SetSize(dim);

    error.SetSize(fes->GetNE());
    error = 0.0;

    const Table& element2face = mesh->ElementToFaceTable();
    Array<int> e2f;
    
    for (int i=0; i<fes->GetNE(); ++i) // loop over for all elements
    {
        fe = fes->GetFE(i);

        element2face.GetRow(i, e2f);
        for (int j=0; j<e2f.Size(); ++j) // loop over for all edges for each element
        {
            FaceElementTransformations* Trans = mesh->GetFaceElementTransformations(e2f[j]);
            const IntegrationRule* ir = &(IntRules.Get(Trans->GetGeometryType(), 2*fe->GetOrder()+3));

            for (int k=0; k<ir->GetNPoints(); ++k)
            {
                const IntegrationPoint& ip = ir->IntPoint(k);
                Trans->SetIntPoint(&ip);

                gf.GetGradient(*Trans, grad); // error!
                double q_val = q.Eval(*Trans, ip);
                CalcOrtho(Trans->Jacobian(), nor);

                error[i] += ip.weight * q_val * (grad * nor);
            }
        }
    }
}
```
I think the error may be because `Trans` is `FaceElementTransformations`, instead of `ElementTransformation`.

**Comment by v-dobrev** [comment]
You need to evaluate both the gradient of `gf` and `q` through either `*Trans->Elem1` or `*Trans->Elem2`. Which of the two to use will depend on their indices: if `(i == Trans->Elem1No)` then use `*Trans->Elem1`, otherwise use `*Trans->Elem2` -- in the latter case `(i == Trans->Elem2No)` should be true.

Also, you'll need to use the corresponding volume quadrature point in the call to `q.Eval(...)`: either `q.Eval(*Trans->Elem1, Trans->Elem1->GetIntPoint())` or similarly with `Elem2`.

The simplest change will be to do something like this:
```c++
   // ...
   ElementTransformation &VolTrans = (i == Trans->Elem1No) ? *Trans->Elem1 : *Trans->Elem2;
   gf.GetGradient(VolTrans, grad);
   double q_val = q.Eval(VolTrans, VolTrans.GetIntPoint());
   // ...
```

**Comment by fanronghong** [comment]
Thanks @v-dobrev , 

It works.
