### ISSUE TITLE
Force warnings to be errors in Travis CI

### ISSUE THREAD

**Issue by v-dobrev** [mfem/mfem#1566]
This came up in the following discussion: https://github.com/mfem/mfem/pull/1529#discussion_r440983510

I think we can add the following extra options to catch some common warnings: `-pedantic -Wall -Werror`. The simplest way to do this (independent of the debug option) is to set the makefile variable `CPPFLAGS`.

**Comment by tzanio** [comment]
That's fine with me

**Comment by adrienbernede** [comment]
I understand the context correctly, you would like this flag in Travis only, right?

Then I suggest an extra job in the check phase that builds with these flags, and thus check for warnings. Does it make sense to both of you?

**Comment by v-dobrev** [comment]
@adrienbernede, I was thinking of adding it to all GNU make builds, e.g. by adding `CPPFLAGS += " -pedantic -Wall -Werror"` before this https://github.com/mfem/mfem/blob/36c7d5f973bc089374b53c9550b5d60566537f76/.travis.yml#L389-L390

However, it makes sense to add it in the "checks" phase too, e.g. here https://github.com/mfem/mfem/blob/36c7d5f973bc089374b53c9550b5d60566537f76/.travis.yml#L68

to prevent unnecessary runs of all "tests".

Using these options in the "tests" phase too is still a good idea, since those test different builds and compilers, so they may fail even if the build in the "checks" phase works fine.

**Comment by tzanio** [comment]
Discussion continued in #1600
