### ISSUE TITLE
Solve subsystem from a big global system

### ISSUE THREAD

**Issue by fanronghong** [mfem/mfem#1570]
Hi all,

I want to extract a subsystem from a very big global system. And after solving the subsystem, I want to go back to the global system with the solution. I have seen this [issue](https://github.com/mfem/mfem/issues/484#issue-320372901).
The global system looks like
![Screenshot from 2020-06-24 12-17-30](https://user-images.githubusercontent.com/24132779/85502600-33a3d000-b61a-11ea-9080-ec7616f5d996.png)
Because the global system is big (the identity matrix `I` is very big, which will affect krylov solver and preconditioner), I only want to solve the subsystem `A p = f`. And the type of the global system is `PetscParMatrix` and `PetscParVector`.

Is there an elegant way to do this? Thanks in advance.

**Comment by tzanio** [comment]
In MFEM it will be most natural to describe the global system as a `BlockMatrix` see e.g. Example 5.

@stefanozampini can comment about the best way to do that in PETSc.

**Comment by fanronghong** [comment]
Thanks for your reply @tzanio ,

The global linear system is formed by a `ParBilinearForm`, so its type is not a `BlockMatrix` and I must extract the subsystem. I don't know how to extract it.

**Comment by aasivas** [comment]
I think you are looking for fieldsplit preconditioner (https://www.mcs.anl.gov/petsc/petsc-current/docs/manualpages/PC/PCFIELDSPLIT.html), also see petsc version of example 5 and rc_ex5p_fieldsplit. This does not technically require you to have a `BlockMatrix`, however, you need to define fields in your configuration file, e.g. rc_ex5p_fieldsplit. Again Prof. Zampini is much more knowledgeable than I am. He may have a better idea.

**Comment by stefanozampini** [comment]
your system is equivalent to solving `A p = f ` and `u = 0`. Why do you need a large system though? Anyway, you can extract submatrices via https://github.com/mfem/mfem/blob/master/linalg/petsc.hpp#L251. There is no `PetscParVector` counterpart, you can call PETSc for that https://www.mcs.anl.gov/petsc/petsc-current/docs/manualpages/Vec/VecGetSubVector.html

**Comment by stefanozampini** [comment]
> I think you are looking for fieldsplit preconditioner (https://www.mcs.anl.gov/petsc/petsc-current/docs/manualpages/PC/PCFIELDSPLIT.html), also see petsc version of example 5 and rc_ex5p_fieldsplit. This does not technically require you to have a `BlockMatrix`, however, you need to define fields in your configuration file, e.g. rc_ex5p_fieldsplit. Again Prof. Zampini is much more knowledgeable than I am. He may have a better idea.

I'm not Professor, thanks anyway

**Comment by fanronghong** [comment]
Thanks @aasivas and @stefanozampini ,

I solved this problem in terms of stefanozampini's idea.
