### ISSUE TITLE
Derefiner does not respect element attributes in NC meshes

### ISSUE THREAD

**Issue by termi-official** [mfem/mfem#1572]
Hi,

I am not sure if this is intended, but in nc meshes with varying attributes (on the elements) in its current state the derefiner may merge elements with different attributes, which may lead to nasty bugs. My current hotfix is to use a custom derefiner which ignores derefinement candidates, if their current depth (in the ncmesh data structure) is the same as some fixed initially chosen one. 
I did it this way, because I could not find out how to properly traverse the ncmesh tree to determine whether attributes may get "lost" in the derefinement by checking if all children of the candidate's parent have the same attribute. 

To elaborate the use-case, I have a preprocessing step which generates a nc mesh, refining the material interfaces according to measurements or an analytical descriptions to a desired level of detail. Attributes are used to assign different materials to different elements, so I can reuse the `RestrictedCoefficient` class in my simulation to handle subdomains differetly in my integrators. I guess this is how it is intended to do? Now having a time-dependent simulation with AMR enabled (because on most part of the mesh almost nothing happends for most of the time), using the `ThresholdDerefiner` leads to over-derefinement at "boring" material interfaces in the beginning of the simulation. 

Best regards,
Dennis

**Comment by rw-anderson** [comment]
Hi Dennis,

I think in the current state, if "you" (or ThresholdDerefiner) asks for a derefinement, mfem obliges without checking anything about consistency of attributes.  So if children have different attributes than the parent, they can be "lost".  Depending on use case, I think this may or may not be what you want.

There's a few different options here I think.  One is to build in an option that checks for inconsistent attributes and inhibits derefinement independently of what is requested.  Another is to make sure the API is convenient for doing the traversal you were trying to do, so you could build this into  your custom derefiner easily.  A third is to provide a different interface for making derefinement decisions that provides the user the sets of coarse and fine elements needed to interrogate whatever they want to, to arrive at a derefinement decision for each possible derefinement.  This is something I was working on previously.

I didn't follow your second paragraph as well.  Why does your ThresholdDerefiner over-derefine?  Is the quantity provided for the thresholding not indicating the material interfaces you'd like to remain refined?

**Comment by jakubcerveny** [comment]
This was never an issue because the assumption was (at least in NCMesh) that a child element always inherits the parent attribute, so the shape of the material domains of the initial coarse mesh does not change. I even contemplated saving some RAM by only storing attributes for the root (coarse) elements in NCMesh. 

If you assign attributes differently in the fine mesh then this is a scenario we had not anticipated and we need to think about it a bit...

**Comment by v-dobrev** [comment]
This can probably be added as an option to the `ThresholdDerefiner` that is then passed down to `Mesh::DerefineByError` and eventually down to `(Par)Mesh::NonconformingDerefinement`. Basically one can skip any derefinements that combine elements with different attributes.

**Comment by termi-official** [comment]
First, thanks for the responses. 
@rw-anderson that second paragraph was really ambiguous formulated, sorry. Regarding the over-derefinement I was referring to the built in ThresholdDerefiner https://github.com/mfem/mfem/blob/d9c4909da3766e49e66187ee063b8504e9d5138b/mesh/mesh_operators.hpp#L268
As a hotfix I track some minimal element depth through a grid function and simply reject elements having this depth in derefinemen, i.e.
```cpp
class RootedThresholdDerefiner : public MeshOperator
{
protected:
    // [...]
    // This is necessary to track the threshold after rebalancing and 
    // (de-)refinement.
    L2_FECollection  depth_fec;
    ParFiniteElementSpace depth_fes;
    ParGridFunction element_depth_bound;
    
    int ApplyImpl(Mesh &mesh) override
    {
        if (mesh.Conforming()) { return NONE; }

        Vector local_err = estimator.GetLocalErrors();

        MFEM_ASSERT(mesh.Nonconforming(), "");
        for(int e=0;e<mesh.GetNE();e++)
        {
             // prevent a possible refinement.
            if( local_err(e) <= threshold && 
                mesh.ncmesh->GetElementDepth(e) == static_cast<int>(element_depth_bound(e)))
            {
                local_err(e) = std::numeric_limits<double>::infinity();
            }
        }

        bool derefs = mesh.DerefineByError(local_err, threshold, 0, op);

        return derefs ? CONTINUE + DEREFINED : NONE;
    } 

public:
    RootedThresholdDerefiner(ErrorEstimator &est, ParMesh* root_mesh_)
    {
        if(root_mesh_->Nonconforming())
        {
            for(int e=0; e<root_mesh_->GetNE(); e++)
            {
                element_depth_bound(e) = root_mesh_->ncmesh->GetElementDepth(e);
            }
        }
    // [...]
    }
    // [...]
};
```
but I think this approach is dangerous and far from optimal for various reasons. Your suggestions sound quite useful and I think if I must choose, the second one seems the best here, because it decouples the code a bit and can help when customizing things. But let me take a closer look on these through the next days.

@jakubcerveny @v-dobrev I think my application is so special, that no one should bother about modifing the attribute management of the ncmesh. That assumption of yours really looks perfectly fine to me. It is more the design of the of the derefinement interface which bites me here, because the interface is a bit too simplistic right now. Which I can also understand, as it looks like this simple interface emerges from the tight coupling beween Mesh and NCMesh.

**Comment by rw-anderson** [comment]
I think your use case will probably not be uncommon, really.  I think people will probably often try to use the attributes as material id's, will define these directly on finer grids rather than always inherit them from parent elements, and then run into difficulties when they try to coarsen.  One potential new feature that might be useful is to allow the user to define a coarsening function for their integer attributes.  Then, if someone is doing something like modeling multi-material elements, they could do something like set the attribute to a special "mixed" attribute upon coarsening.

**Comment by termi-official** [comment]
Really? I chose the combination of nc-refinement and element ids on the fine level approach mainly for two reasons. First, I failed to automate generating meshes with a reasonable amount of elements using readily available tools, so I fell back to an approach similar to the one in the Shaper miniapp. Second, at the time I started my project I was unable to figure out how to properly couple the physics on the boundaries of two mesh instances (with some matching faces), i.e. implementing some kind of "coupling operator". I still think these "coupling operators" would be a more efficient and clean way to implement multi-material (and thinking further especially multi-physics) models. I agree on your point, that, If the material model just differs in the coefficient on the subdomains like in example 2, then having one mesh with different attributes for the subdomains would also be efficient and clean.
But even without this argument, if I understand Jakub correctly then this is issue only appears when we change attributes on refined levels in a non-conforming refinement (like in the Shaper miniapp), right? I think this the real unusual thing I do. At least from my experience the "common" workflow is to use a meshing tool to construct conforming meshes and use these as a starting point for (AMR) simulations.

**Comment by rw-anderson** [comment]
I think it is standard process to start with a conforming mesh generated somehow, and then iteratively refine this mesh while re-applying the initial conditions to create an initial mesh, just like the shaper mini-app does.  This is how every AMR code I've worked with has been implemented.  If you are using attributes as material id's, then you are going to run into this scenario.  It could be argued that the element attributes aren't the right data structure for material id's in such a use case.

**Comment by termi-official** [comment]
Now I am curious. I am totally with you on the point, that the initial conforming mesh should be adapted to match the initial conditions properly (via nc-refinements), but is it really common to adapt the material id/attributes at this stage?

**Comment by rw-anderson** [comment]
I guess I can't speak for "common" in general, only what I'm familiar with, but I don't see how anything else can be very general.  If you want to represent arbitrary material boundary geometries accurately, there is no way around it.  However, typically this is managed with more involved data structures than a simple integer attribute.

**Comment by tzanio** [comment]
@rw-anderson and @termi-official is there an outstanding todo item, or should we close this issue?

**Comment by rw-anderson** [comment]
I think I'd like to hear from @jakubcerveny first before deciding where to go with this.  At a minimum we should probably add an option to warn when coarsening elements with inconsistent attributes.

**Comment by jakubcerveny** [comment]
I would make sure at least these two simple things work:
1. Mesh::SetAttribute is propagated into NCMesh elements. This way the user can set material attributes correctly at each refinement level of the mesh and they will be remembered.
2. When derefining, the coarse element will get its old attribute, as presumably it is still valid. If not, the user can update it after derefinement.

We could also add an option (true/false) to the Derefiner that would control whether it is OK or not to derefine elements with different attributes. This should be a simple check of each row of the derefinement table.

**Comment by jakubcerveny** [comment]
@termi-official could you take a look at #1610 if this is what you need? It doesn't fully work in parallel yet (synchronizing the ghost element attributes in NCMesh will not be trivial), I'd like to hear what you think first.
