### ISSUE TITLE
Parallel Assembly Broken (see Example 1p)

### ISSUE THREAD

**Issue by wcdawn** [mfem/mfem#1574]
A recent merge broke the assembling of ParBilinearForm.
The error message is:
```
Verification failed: (p_mat.Ptr() == NULL && p_mat_e.Ptr() == NULL) is false:
 --> The ParBilinearForm must be updated with Update() before re-assembling the ParBilinearForm.
 ... in function: virtual void mfem::ParBilinearForm::FormSystemMatrix(const mfem::Array<int>&, mfem::OperatorHandle&)
 ... in file: $MFEMPATH/fem/pbilinearform.cpp:376
```

This can be demonstrated by trying to compile and run `ex1p`.

This worked with commit `cc3a447` and has been broken since then.

**Comment by tzanio** [comment]
The following works fine for me (as well as in our tests) with the current master:
```
make distclean
make parallel 
cd examples/
make ex1p
mpirun -np 4 ex1p
```

Can you provide more details about your system and your build where you see this error?

**Comment by wcdawn** [comment]
I can no longer replicate this. Must have been something unique on my system.
Sorry!
