### ISSUE TITLE
SIA multi-dimensional case

### ISSUE THREAD

**Issue by sshiraiwa** [mfem/mfem#1577]
Hi all,  I have a question about SIA integrator in ex20. p and q in this example is a scalar value. How can we use or extend it in multiple-dimensional case? For example in 2D,  it is as follows

dp_x/dt =  -dH/dq_x
dp_y/dt =  -dH/dq_y
dq_x/dt =  dH/dp_x
dq_x/dt =  dH/dp_y

note the dH/d is partial.

**Comment by mlstowell** [comment]
Hi, @sshiraiwa ,

To use this integrator for higher dimensional systems you should be able to simply redefine the `GradT` and `NegGradV` operators.  I just noticed that this example doesn't reference the paper that inspired the `SIASolver`.  I believe the test cases shown in this example came straight from that paper so I really should have referenced it.

If you're interested in seeing this integrator used in a more typical finite element context you can look at the `maxwell` mini app in the `miniapps/electromagnetics` subdirectory.

If you have something else in mind I'd be happy to hear more about it.

Best wishes,
Mark

**Comment by tzanio** [comment]
Closing this issue for now. @sshiraiwa, please feel free to reopen if you have further questions.
