### ISSUE TITLE
Coordinates of points corresponding to DOFs of DG_Interface space

### ISSUE THREAD

**Issue by aasivas** [mfem/mfem#1581]
This question is very similar to issue #63, but the approach there does not work for me. I need to obtain the coordinates of points corresponding to DOFs of `fes` for
```
fec = new DG_Interface_FECollection(order, dim);
ParFiniteElementSpace *fes(new ParFiniteElementSpace(pmesh, fec));
```
As far as I can see, there are no MFEM functions I can use. But I still wanted to ask before I go down the rabbit hole of looping over nodes in the reference element and applying element transformations.

**Comment by tzanio** [comment]
Hi @aasivas,

One way could be to `Project` the `Coefficient`s `x`, `y` and `z` to `GridFunction`s in this space. 

Does this work for you?

Tzanio

**Comment by aasivas** [comment]
That is an interesting suggestion, but wouldn't that give me the coefficients of the basis functions. Depending on the basis used, that coefficient does not necessarily equal to the function value at the node. As far as I know, Gauss-Legendre is one of those bases. I am testing it now, I will let you know if I can get it work for some base.

**Comment by tzanio** [comment]
Good point @aasivas, the basis is not always interpolatory (nodal). 

That is certainly the case for H(curl) and H(div) spaces, but there it is not so clear why you would want the dof location. Let me know if that's you use case.

For H1 and L2 spaces all bases except the positive/Bernstein basis are interpolatory and the above should work.

**Comment by aasivas** [comment]
I need the coordinates to do some visualization (AMG coarsening path), but it is also useful to plot trace solutions from hybridizable DG methods. Maybe there are other uses, but I imagine this functionality is rather niche.

Thanks @tzanio. The idea works except calling `ProjectCoefficient` on the `fes` described above causes a segmentation fault. If anyone needs to do same thing, you can use `ProjectCoefficientSkeletonDG` from [hdg](https://github.com/mfem/mfem/tree/hdg) branch.
