### ISSUE TITLE
LinearForm Assemble() Gives Wrong RHS

### ISSUE THREAD

**Issue by jxb3641** [mfem/mfem#159]
Hello again!

I have run into a problem that I cannot figure out with the script I am running.  I am trying to adapt example 5 into a Biot solver with perturbation in the pressure for added stability.  As such, I want to first solve the FE discretization in space first, so i am checking that I have set up the script correctly with non-zero constant solutions u (a d-dimensional vector representing displacement) and p (scalar, pressure of the intermittent fluid) as a preliminary example.  This makes both source terms on the RHS 0, and all that is left on the RHS are boundary integrations of the pressure and displacement.

More specifically, we get the following weak form:

for all (v, q) \in V \times Q,
\int_{\Omega} \sigma(u) : \nabla v - \int_{\Omega} p \div v = - \int_{\partial\Omega}pv \cdot n
\int_{\Omega} u \cdot \nabla q - \int_{\Omega} \nabla p \cdot \nabla q = \int_{\partial\Omega}qu \cdot n 

(Note that the other terms from the integration by parts for both equations go to 0 because u and p are constants; also, sorry if the text above is unsightly, I have no other way of writing the equation than writing it in tex.)

For our discretization, we use d copies of H^1(\Omega) for V, and H^1(\Omega) for Q.  

For the RHS, I added both corresponding DomainLFIntegrators for the 0 RHS gotten by computing by hand, and a VectorBoundaryFluxLFIntegrator with FunctionCoefficient -p for the linear form corresponding to the first equation, and a BoundaryNormalLFIntegrator with FunctionCoefficient u for the linear form corresponding to the second equation RHS. For this simple case, I have also just projected the exact solution onto GridFunctions for each of u and p; assuming a correct set up of the bilinearforms and linearforms, this should immediately solve the equations.
  
I believe that there is an error when the linear forms are assembled, however.  In my particular example, I am using the mesh described by "inline-tri-mesh.mesh", and I have "ref_levels" = 1; this gives me the unit square split into 64 mini squares, with 81 vertices, 32 of which are on the boundary; thus for the RHS of the first equation, I should get 64 non-zero entries (d=2 for "inline-tri.mesh"), and for the second RHS, I should get 32 non-zero entries.  

I mention this because upon debugging, I find that the number of non-zero entries in either vector does not match up to this.  For the RHS of the equation for p, I get 30 non-zero entries, and for the RHS of the equation for u, I get 36 non-zero entries.  I have yet to do the math to see if the actual values are correct, but when I change the values of the constants, the numbers seem to change accordingly.  Is this what is supposed to happen, or is there an error in how I am adding the boundary integrators?  I believe this is what is leading everything else in the code astray, as eliminating the Dirichlet data in the BilinearForms later on in the code is also affected by this incorrect RHS.

Thanks in advance for the help!

Juan Batista

**Comment by vladotomov** [comment]
The number of non zeros depends on the spaces / their orders / the constants you are using for u and p. Could you specify these?

**Comment by jxb3641** [comment]
So right now, I have set the constants u = (10, 10)^t, p = 50.  

The space for u is a 2-dimensional space with each component being H^1(\Omega), each of order 1.  
The space for p is a 1-dimensional space, H^1(\Omega) of order 1.

After speaking with my adviser just now, he told me that since I am imposing Dirichlet Boundary Conditions and eliminating them, this would force both rhs boundary integrals to 0; thus, I have removed them, so the rhs should be (and are) 0 for each equation before eliminating.

However, when I check the rhs after eliminating the Dirichlet data in each bilinear form using EliminateEssentialBC(), we agree that the rhs is still off.  In particular, we are now using the same mesh with 0 refinements to make debugging easier, meaning that we now have 25 vertices in the mesh, with 16 boundary points.  In the case of the rhs associated with the second equation, we should be getting only one zero entry (corresponding to the innermost point that has no boundary nodes adjacent to it), and yet there are 3 zero entries in this rhs, as shown below:

1.   10.8333
2.   10.4167
3.   0     <-- 0 entry
4.   19.1667
5.   9.58333
6.   11.25
7.   31.25
8.   0   <-- 0 entry
9.   28.75
10. 8.75
11. 11.25
12. 31.25
13. 0   <-- 0 entry
14. 28.75
15. 8.75
16. 10.4167
17. 40
18. 8.75
19. 28.3333
20. 8.75
21. 10
22. 9.58333
23. 8.75
24. 8.75
25. 9.16667

The first rhs also has this problem: it has 7 zero entries when I think it should only have 2.

To ensure that I am giving  as much information as possible, I will include the part of my script that creates and assembles the linear forms and the bilinear forms, and eliminates the prescribed boundary data from the bilinear forms.  

I have created two arrays to track the list of boundary dofs for each of u and p that i have called u_ess_tdof_list and p_ess_tdof_list, and I have marked All boundary vertices as essential:

Array<int> u_ess_tdof_list, p_ess_tdof_list;
   if (mesh->bdr_attributes.Size())
   {
      Array<int> ess_bdr(mesh->bdr_attributes.Max());
      ess_bdr = 1;
      u_space->GetEssentialTrueDofs(ess_bdr, u_ess_tdof_list);
      p_space->GetEssentialTrueDofs(ess_bdr, p_ess_tdof_list);  
   }

I then proceed to construct GridFunctions for u and p and initialize the rhs with the proper offsets defined earlier:
   BlockVector rhs(block_offsets);
 
   //For now, project u_exact, p_exact everywhere so that the solver instantly solves the problem.
   GridFunction u(u_space);
   u.ProjectCoefficient(ucoeff);
   
   GridFunction p(p_space);
   p.ProjectCoefficient(pcoeff);
   
Then, I construct the LinearForms for each equation, giving functioncoeffs 0 to each:
   LinearForm *fform(new LinearForm);
   fform->Update(u_space, rhs.GetBlock(0), 0);
   fform->AddDomainIntegrator(new VectorDomainLFIntegrator(fcoeff));
   
   fform->Assemble();

   LinearForm *gform(new LinearForm);
   gform->Update(p_space, rhs.GetBlock(1), 0);
   
   gform->Assemble();
  
I then construct the 4 different bilinearforms for the LHS, using the arrays of boundary dofs as inputs into the corresponding Eliminate() methods to eliminate the Dirichlet data given by u and p:
   //Make ElasticityForm:
   
   BilinearForm *stressForm(new BilinearForm(u_space));
   stressForm->AddDomainIntegrator(new ElasticityIntegrator(lambda_func,mu_func));//\lambda, \mu=1
   stressForm->Assemble();
   stressForm->EliminateEssentialBC(u_ess_tdof_list, u, *fform);
   
   //Make DivForm:
   MixedBilinearForm *divForm(new MixedBilinearForm(u_space, p_space));
   divForm->AddDomainIntegrator(new VectorDivergenceIntegrator);
   divForm->Assemble();
   divForm->EliminateTrialDofs(u_ess_tdof_list, u, *fform);

   //Make BilinearForm for Ap (Diffusion for p):

   BilinearForm *darcyForm(new BilinearForm(p_space));  
   darcyForm->AddDomainIntegrator(new DiffusionIntegrator(k));
   darcyForm->Assemble();
   darcyForm->EliminateEssentialBC(p_ess_tdof_list, p, *gform);

   //Make BilinearForm for Sb (BubbleDiffusion for p):

   BilinearForm *bubbleForm(new BilinearForm(p_space));
   bubbleForm->AddDomainIntegrator(new BubbleDiffusionIntegrator(k));
   bubbleForm->Assemble();
   bubbleForm->EliminateEssentialBC(p_ess_tdof_list, p, *gform); 

I then proceed to build a BlockMatrix with structure

                             P = [ Al           Gl        ]
                                   [ Gl^T   -(Ap + Sb) ]

Where Al is the elasticity form, Gl is the div form, Ap is the diffusion form and Sb is a diffusion form whose local stiffness matrix is of form a*L*( I + b*L)^{-1}, with a and b being constants that depend on the size of the element and the dimension (I have checked the construction of this local stiffness matrix thoroughly, and I know that my script does it right, so I don't think this last formulation is the source of the error). 

I then finalize the forms, negate Gl to give it the correct sign, transpose the SparseMatrix corresponding to Gl, and construct a block preconditioner out of the diagonal elements of this matrix, and use GMRES to solve the system. (Note, i have also tried using PCG solver to solve, and it also doesn't work).  

I think it is also worth mentioning that the relative errors are different:

|| u_h - u_ex || / || u_ex || = 0.225357
|| p_h - p_ex || / || p_ex || = 1.82181

Where the norms are computed just like in example 5 (L^2).

Sorry for a long response, but I thought the more information I gave to you, the better!

**Comment by vladotomov** [comment]
Some things I noticed:
- I don't see any integrators added to gform.
- In your first post you have face integrals on the RHS, but here fform adds a domain integrator.
- Make sure that block_offsets correspond to the sizes of u_space and p_space.

**Comment by jxb3641** [comment]
Sorry about that, I messed up copying over the script when I wrote that reply, I was deleting comments I wrote to make the code clearer for you.  My code does have a DomainIntegrator for the gform, corresponding to the 0 rhs for that equation.  

As for the face integrals I have included in my first post, me and Ludmil (my adviser) discussed this, and because I have Dirichlet data that will be eliminated later on in the script, those boundary integrals go to 0 because the test functions are defined to be 0 on the boundary; this is compensated for by calling the Eliminate() calls in each bilinear form to move over the non-zero Dirichlet data given by GridFunctions u and p to the rhs.  Am I correct in assuming this is what those eliminate calls do?

One other thing: are the matrices specified by the Assemble() calls for the bilinear forms in lexicographical order before finalizing? Because I remember importing the finalized matrices into matlab at some point and being frustrated that the matrices were not in lexicographical order for meshes that have been refined at least once, and yet while debugging step by step, it seems that the linear forms are assembled in lexicographical order, at least for order 1 H^1 spaces, but after calling the eliminate() methods, they seem not to match up to a rhs I would expect...

block_offsets is correctly calibrated as in example 5, I just didn't include the initialization because it was unchanged from that example and is working as expected.

**Comment by vladotomov** [comment]
Do you need all these structures do debug the RHS? I would probably use 1x1 or 2x2 mesh with one BilinearForm and one LinearForm. This will also help you to define a more specific question.

I'm not sure what you mean by lexicographical order. The sparsity of the matrix depends on the numbering of the FE degrees of freedom. Are you asking about bilinear forms (finalized or not) or linear forms; please be more specific.

**Comment by jxb3641** [comment]
After working on it yesterday, I have an idea as to why the rhs is not
matching up like i expect, and am attempting a solution that may fix this
problem.  I will spend the rest of today attempting to implement this
solution, and will update you with what I find.

As for the clarification of the ordering of the forms, I was just asking
for an explanation of that sparsity pattern, in both the bilinear forms and
the linear forms before and after they are finalized.  Am I correct in
assuming that if the mesh is uniformly refined, the ordering of the degrees
of freedom no longer corresponds to lexicographical ordering?

By lexicographical ordering, i mean that if we start with, for instance,
"inline-tri.mesh" and do not refine the mesh, the degrees of freedom for an
H^1 space on this mesh correspond to the actual vertices on the mesh, and
the ordering of the dofs are matched up with the vertices on the mesh, i.e.
the first dof corresponds to point (0,0), the second dof corresponds to
(0.25,0), the third corresponds to (0.5,0), the 6th corresponds to
(0,0.25), etc...

However, when the mesh is refined, does this pattern still hold? i.e. if we
refine the mesh uniformly once, we go from a 5 x 5 mesh to a 9 x 9 mesh; is
it now the case that the ordering of the dofs are not matched up with the
lexicographical ordering of the vertices on the mesh?  For certain
parallelizable smoothers, for instance GS-RB, it makes sense to order the
dofs in alternating order, so that, for this example, the first dof
corresponds to point (0,0), the second dof corresponds to (0.25,0), ...,
and then the 26th dof corresponds to point (0.125,0), the 27th point
corresponds to (0.375,0), etc... is this the way the dofs are ordered for
refined meshes?

Thanks for your time in explaining this, it helps me a lot.

**Comment by vladotomov** [comment]
I think that might hold only for first order H1 spaces on structured grids (I'm not 100% sure). The numbering of the dofs depends on the space and its order. Here's the local numbering we use for H1. Also, note that the global numbering might not be the same, e.g., because of different cell orientations.

![quad](https://cloud.githubusercontent.com/assets/17843342/24263671/135d5b62-0fbb-11e7-9705-cb4276d24377.jpeg)
![tri](https://cloud.githubusercontent.com/assets/17843342/24263681/187a00d2-0fbb-11e7-96dd-ca745c2abd27.jpeg)

**Comment by jxb3641** [comment]
Hello Vladimir,

Sorry for disappearing! Just wanted to inform you that I have resolved the issue with this problem; more specifically, I had to write some custom methods in the SparseMatrix cpp file to eliminate submatrices of the SparseMatrices of the MixedBilinearForm above, and add the eliminated rhs of each block in the BlockOperator above to the BlockVector rhs in a certain way to make the equations consistent.  The script is working for order 1 H1 spaces in two dimensions for constant exact solutions and linear exact solutions; I am now rewriting the script to see how it does for quadratic exact solutions.  I have yet to see how it works for higher order H1 spaces, and will let you know how that goes after fully testing the order 1 discretization in 2 and 3 dimensions.

**Comment by tzanio** [comment]
Hi Juan,

Glad to hear you got it working. Please let us know if you have any other questions in the future.

Tzanio

**Comment by Hemanta822** [comment]
I am working on the Biot model. I am having difficulty imposing Dirichlet boundary conditions for both u and p for the mixed bilinear term. In the code mentioned above by @jxb3641, he seems to be handling only the u part of the mixed term:

//Make DivForm:
MixedBilinearForm *divForm(new MixedBilinearForm(u_space, p_space));
divForm->AddDomainIntegrator(new VectorDivergenceIntegrator);
divForm->Assemble();
divForm->EliminateTrialDofs(u_ess_tdof_list, u, *fform);

I would be grateful if anyone could help me understand it. Thank you.
