### ISSUE TITLE
How to set one degree of freedom boundary condition

### ISSUE THREAD

**Issue by diliu1994** [mfem/mfem#1590]
Hi All,

I am trying one problem with example 10p. The boundary setting in the code is: 
`   Array<int> ess_bdr(fespace.GetMesh()->bdr_attributes.Max());
   ess_bdr = 0;
   ess_bdr[0] = 1; // boundary attribute 1 (index 0) is fixed `

In this example, the degrees of freedom of the boundary are all fixed. I am considering if I can just fix one degree of freedom in the boundary condition such as the z direction displacement. 

Best,
Di

**Comment by tzanio** [comment]
This has been discussed previously, for example in https://github.com/mfem/mfem/issues/1334.

You have to create a list of the dofs you want to eliminate and pass that to `FormLinearSystem`.

**Comment by diliu1994** [comment]
Hi @tzanio ,

I have read the previous discussion, however, I am still confused on how to eliminate the dofs. For the code I am trying to modify is the ex10p. I have attached the file. Could you please tell me how to modify the code in detail?
[ex10p_expansion_subdomain.cpp.txt](https://github.com/mfem/mfem/files/4854592/ex10p_expansion_subdomain.cpp.txt)

Best regards,
Di

**Comment by diliu1994** [comment]
Hi All,

I have found that add the degree of freedom you want to fix in the function: `GetEssentialTrueDofs` can solve this problem. For example, if you want to fix the velocity in x direction, you can change the code to be: `fespace.GetEssentialTrueDofs(ess_bdr, ess_tdof_list,0);`. 

Best Regards,
Di
