### ISSUE TITLE
How to export the parallel result in ParaView format

### ISSUE THREAD

**Issue by diliu1994** [mfem/mfem#1591]
Hi All,

I am trying to export the result in paraview format. However, I have met the error messege that:
"ex10p_expansion_subdomain.cpp(462): error: no suitable conversion function from "mfem::ParGridFunction" to "mfem::GridFunction *" exists
     paraview_dc.RegisterField("elastic_energy",w_gf);"

I have attached the code and input file. 
[ex10p_expansion_subdomain.cpp.txt](https://github.com/mfem/mfem/files/4852883/ex10p_expansion_subdomain.cpp.txt)
[multi-layer-beam.msh.txt](https://github.com/mfem/mfem/files/4852889/multi-layer-beam.msh.txt)

And the running command line is:"mpirun -np 16 ./ex10p_expansion_subdomain -m ../data/multi-layer-beam.msh -s 2 -rs 1 -tf 20 -dt 0.5"
Can anyone help me with this problem?

Best regards,
Di

**Comment by pazner** [comment]
The data collection expects a pointer to a grid function, so I think you just need to pass the address of the grid function like this:
`paraview_dc.RegisterField("elastic_energy", &w_gf);`

**Comment by diliu1994** [comment]
Hi @pazner ,

Thanks so much. Now it works well.

Best,
Di
