### ISSUE TITLE
Interpolation from coarse interface finite element space to fine interface finite element space

### ISSUE THREAD

**Issue by aasivas** [mfem/mfem#1595]
Hi,

I am trying to interpolate a coarse solution to a fine space, similar to #1072, but for DG_Interface finite element spaces. The code below, adapted from the same issue, does not work but explains what I want to achieve.

```c++
#include "mfem.hpp"
using namespace mfem;
using namespace std;
 
double pi = 3.141592653589793e0;
double sin_cfunc(const Vector& x) { return sin(pi * x[0]) * sin(pi * x[1]); }
 
int main()
{
    Mesh mesh_coarse(15, 15, Element::TRIANGLE, 1.0, 1.0, 1.0);
    Mesh mesh_fine(mesh_coarse);
    mesh_fine.UniformRefinement();
 
    int dim = mesh_coarse.Dimension();
    const int p_order = 1;
 
    DG_Interface_FECollection ske_fec(p_order, dim);
    FiniteElementSpace ske_coarse(&mesh_coarse, &ske_fec);
    FiniteElementSpace ske_fine(&mesh_fine, &ske_fec);
 
    FunctionCoefficient sin_coeff(sin_cfunc);
 
    GridFunction ub_c(&ske_coarse);
    ub_c.ProjectCoefficientSkeletonDG(sin_coeff);
 
    GridFunction ub_c2f(&ske_fine);
 
//     GridTransfer *gt = new InterpolationGridTransfer(ske_coarse, ske_fine);
    GridTransfer *gt = new L2ProjectionGridTransfer(ske_coarse, ske_fine);
    const Operator &R = gt->ForwardOperator();
//     const Operator &P = gt->BackwardOperator();
 
    R.Mult(ub_c, ub_c2f);
}
```

You need `ProjectCoefficientSkeletonDG` from hdg branch. The code fails at the line `const Operator &R = gt->ForwardOperator();`. I believe this is because the forward operator is not constructed at all for this pairing of finite element spaces.

Is it possible to do this in MFEM? The approach doesn't have to be as above, I am open to all suggestions.

**Comment by v-dobrev** [comment]
If I understand your question correctly, such interpolation operation is not well defined, since after refinement the interface/skeleton contains new faces that are not children of the faces of the coarse interface.

**Comment by aasivas** [comment]
Thanks a lot, Veselin. So the data structure for meshes does not keep track of that relationship, if I understood it correctly. Or is it more of a theoretical issue?

**Comment by tzanio** [comment]
@aasivas, can you clarify what do you expect this transfer to do in this simple case:
```
+-------+     +---+---+
|       |     |   |   |
|       | --> +---+---+
|       |     |   |   |
+-------+     +---+---+
```
Since interfacial functions are not defined in the element interiors, there are no "natural" values to assign to the interior faces created during refinement... I believe that's Veselin's point.

**Comment by aasivas** [comment]
I am working with simplices, but for sake of simplicity let's discuss in terms of quads and hexahedra. Assuming the data structure supports it, intuitively, the simplest thing would be injection and averaging, i.e.;
```
+---------+     +----+----+
a         b     a (a+b)/2 b
a         b --> +----+----+
a         b     a (a+b)/2 b
+---------+     +----+----+
```
However, I am aware that this does not necessarily work well. A more sophisticated approach would have to take the element values, if they exist, into consideration; something like [this paper](https://arxiv.org/abs/1811.09909), particularly subsection 3.2.1. This one is too specific though, it depends on the element finite element space and the problem. So it is not a great solution. Also, probably, it won't be useful if you are solving a PDE on a surface -not my application, but something to keep in mind-.

For my purposes though, even having access to the existing dof (coarse) and new dof (fine) information is sufficient. Then I could simply inject values if the face exists on the coarse mesh and set to zero if not. That is what I got from Veselin's original answer: MFEM simply does not keep track of that information, hence, it is not possible. But, as you said, there is also lack of theory and ambiguity about values of the new faces.

**Comment by psocratis** [comment]
If I may add a comment here... I agree with @v-dobrev , such a map is not well defined for the new vertices/edges/faces that don't belong on the coarse mesh skeleton. I had the same issue in the past when working on a multigrid solver for the interface system resulting from a DPG discretization. One possible solution (that we used) is to use the harmonic extension (Schur complement)  for these dofs.

**Comment by aasivas** [comment]
My purpose is pretty much the same. I want to pass a decent initial guess for the iterative solver at each AMR step rather than zero guess. It would be great even if I could preserve the values of the dofs unchanged from the coarse level. All the new dofs introduced can be just set to zero for now.

**Comment by v-dobrev** [comment]
One option is to extend the grid-function from the interface space to a grid-function on a regular volume space. Since your interface space uses `DG_Interface_FECollection`, the natural volume space will use `RT_FECollection`. After extension with zeros (see below), one can interpolate that grid-function to the refined volume space and then extract just the interface dofs (see below).

The "extension with zeros" is trivial, because in the volume `GridFunction`, all dofs corresponding to the interiors of the elements are at the end of the vector, so:
```
f_vol = | f_interface |
        | 0           |
```
For the same reason, after the interpolation to the fine volume space, one can "restrict to the interface" by simply removing the element-interior dofs from the end.

**Comment by aasivas** [comment]
I am going to implement this idea tomorrow and let you know how it goes. Is this true for `ParGridFunction`s too? Does each process have interior dofs at the end of their local `GridFunction`s?

**Comment by v-dobrev** [comment]
> I am going to implement this idea tomorrow and let you know how it goes. Is this true for `ParGridFunction`s too? Does each process have interior dofs at the end of their local `GridFunction`s?

Yes.

**Comment by aasivas** [comment]
Hi again Veselin,

Thanks a lot for your help. The code below seems to work: 
```
#include "mfem.hpp"
using namespace mfem;
using namespace std;

double pi = 3.141592653589793e0;
double sin_cfunc(const Vector& x) { return sin(pi * x[0]) * sin(pi * x[1]); }

int main()
{
    Mesh mesh_coarse(15, 15, Element::TRIANGLE, 1.0, 1.0, 1.0);
//    Mesh mesh_coarse(1, 1, Element::TRIANGLE, 1.0, 1.0, 1.0);
    Mesh mesh_fine(mesh_coarse);
    mesh_fine.UniformRefinement();

    int dim = mesh_coarse.Dimension();
    const int p_order = 1;

    DG_Interface_FECollection ske_fec(p_order, dim);
    FiniteElementSpace ske_coarse(&mesh_coarse, &ske_fec);
    FiniteElementSpace ske_fine(&mesh_fine, &ske_fec);
    
    RT_FECollection vol_fec(p_order, dim);
    FiniteElementSpace vol_coarse(&mesh_coarse, &vol_fec);
    FiniteElementSpace vol_fine(&mesh_fine, &vol_fec);

    FunctionCoefficient sin_coeff(sin_cfunc);

    GridFunction ub_c(&ske_coarse);
    ub_c.ProjectCoefficientSkeletonDG(sin_coeff);
    
    GridFunction vol_c(&vol_coarse);
    for(int i=0; i< ub_c.Size(); i++)
    {
      vol_c(i) = ub_c(i);
//      printf("ub_c(%d) = %g \n",i, ub_c(i));
    }

    GridFunction vol_c2f(&vol_fine);
     GridTransfer *gt = new InterpolationGridTransfer(vol_coarse, vol_fine);
    const Operator &R = gt->ForwardOperator();

    R.Mult(vol_c, vol_c2f);
    GridFunction ub_r(&ske_fine);
    for(int i=0; i< ub_r.Size(); i++)
    {
      ub_r(i) = vol_c2f(i);
//      printf("ub_r(%d) = %g \n",i, ub_r(i));
    }
}
```
There is some averaging going on rather than injection and RT is a vector FEM while I am using DG_Interface for a scalar unknown so there is some redundancy there but it looks like it is going to serve my purposes. I am sharing the code in case it helps someone else.

Note: L2ProjectionGridTransfer, on July 10, 2020, only supports a few FEMs so InterpolationGridTransfer is necessary. But, when L2ProjectionGridTransfer is available for RT, it is better to use that.

**Comment by aasivas** [comment]
I am closing the issue, because the approach is satisfactory for me and I think that my question has been answered. Feel free to reopen if there are any further considerations.
