### ISSUE TITLE
Ex 16 and nonlinear iteration

### ISSUE THREAD

**Issue by ben-s-southworth** [mfem/mfem#1597]
How is the nonlinearity being resolved in Ex 16? The diffusion coefficient nonlinearly depends on u, but it seems to be treated more or less explicitly. The Implicit Solve function calls
```
// Solve the equation:
   //    du_dt = M^{-1}*[-K(u + dt*du_dt)]
   // for du_dt
   if (!T)
   {
      T = Add(1.0, Mmat, dt, Kmat);
      current_dt = dt;
      T_solver.SetOperator(*T);
   }
   MFEM_VERIFY(dt == current_dt, ""); // SDIRK methods use the same dt
   Kmat.Mult(u, z);
   z.Neg();
   T_solver.Mult(z, du_dt);
```
but this is just a linear update based on u from the previous time step (which was used to construct Kmat). This doesn't solve the nonlinear equation du_dt = M^{-1}*[-K(u + dt*du_dt) though, some kind of nonlinear iteration would be needed to do that.

Am I missing something here?

**Comment by jandrej** [comment]
From my understanding the formulation uses `kappa(u_{n-1})` instead of `kappa(u_{n})`, e.g. the previous time step and you can view it as a fixed point iteration.

**Comment by ben-s-southworth** [comment]
@jandrej Sure it's *one* Picard iteration, but if you don't iterate on the Picard iteration to some tolerance it's like applying one AMG iteration to a linear problem and moving on to the next time step.

**Comment by barker29** [comment]
Hi @ben-s-southworth , we've been discussing this on our internal Slack which isn't very helpful to you since you can't see it. You are right that the problem is linearized based on the previous timestep, there is no nonlinear solve. The description on the [website](https://mfem.org/examples/) is more helpful but the in-example documentation should be improved.

**Comment by ben-s-southworth** [comment]
@barker29 Got it, yea the website explanation is more clear. That being said, is this theoretically sound for observing even first-order accuracy (I think it's probably not for higher order SDIRK schemes)?

Part II: I added Anderson Acceleration in a branch. I was going to use this as a nonlinear test problem, but that's when I realized that a nonlinear iteration wasn't even used. Thoughts from the MFEM team on modifying this example so that it actually converges the Picard iteration and potentially using Anderson Acceleration?

**Comment by v-dobrev** [comment]
@ben-s-southworth, regarding part II: it is probably best to make that a new example, just to keep ex16/16p simple.

**Comment by ben-s-southworth** [comment]
@v-dobrev sounds good. What about converging the nonlinear iteration for this example? Turns out it only takes 3-4 iterations even if you crank up alpha and set the constant coefficient kappa to be small. Only about 15 lines of code too, just a small while loop within the implicit solve. Can also just do add Anderson acceleration to a more difficult problem and ignore this.

**Comment by ben-s-southworth** [comment]
Added a PR with a Picard iteration https://github.com/mfem/mfem/pull/1602.
