### ISSUE TITLE
Clarification for NonlinearFormIntegrator

### ISSUE THREAD

**Issue by juan42** [mfem/mfem#160]
I'm still unsure about a few points regarding a NonlinearFormIntegrator. Consider the equation 
```
H(u) = f
```
with H(u) = u^2, for which i'd need to implement an element vector and gradient assemble. Looking at DomainLFIntegrator, i could basically copy the assemble and modify the coefficient to be the actual function at the element (the argument is already there but i'm not sure if its intended for that). This looks like
```cpp
void ReactionNLFIntegrator::AssembleElementVector(const FiniteElement &el,
                                                  ElementTransformation &Tr,
                                                  const Vector &elfun,
                                                  Vector &elvect) {
  int dof = el.GetDof();
  shape.SetSize(dof);
  elvect.SetSize(dof);
  elvect = 0.0;

  const IntegrationRule *ir =
      &IntRules.Get(el.GetGeomType(), 2 * el.GetOrder() + Tr.OrderW());

  for (int i = 0; i < ir->GetNPoints(); i++) {
    const IntegrationPoint &ip = ir->IntPoint(i);
    el.CalcShape(ip, shape);
    Tr.SetIntPoint(&ip);

    double w = Tr.Weight() * elfun(i) * elfun(i);

    add(elvect, ip.weight * w, shape, elvect);
  }
}
```
Is elfun the function value at the current newton step?

The next part would be the Jacobian. If i use the Gateaux derivative i arrive at
```
J(u, du, v) = limit((H(u+epsilon*du,v)-H(u,v))/epsilon, epsilon, 0)
J(u, du, v) = 2 * u * du * v
```
with v being the test function. So i would use the structure of the MassIntegrator (Bilinearform) and get
```cpp
void ReactionNLFIntegrator::AssembleElementGrad(const FiniteElement &el,
                                                ElementTransformation &Tr,
                                                const Vector &elfun,
                                                DenseMatrix &elmat) {
  int dof = el.GetDof();
  shape.SetSize(dof);
  elmat.SetSize(dof);
  elmat = 0.0;

  const IntegrationRule *ir =
      &IntRules.Get(el.GetGeomType(), 2 * el.GetOrder() + Tr.OrderW());

  for (int i = 0; i < ir->GetNPoints(); i++) {
    const IntegrationPoint &ip = ir->IntPoint(i);
    el.CalcShape(ip, shape);
    Tr.SetIntPoint(&ip);

    double w = Tr.Weight() * 2.0 * elfun(i);

    AddMult_a_VVt(ip.weight * w, shape, elmat);
  }
}
```
Using the resulting Integrator with the NewtonSolver doesn't converge, so i'm assuming i made an error in defining the element vector and/or gradient.

For reference, this is how i call the newton solver. forcing_coeff is a function callback which returns a sin(pi*x), which fits into the setting regarding boundary conditions (0 on the ends on a 1D line from 0 to 1).
```cpp
  GridFunction forcing(h1_fespace);
  forcing.ProjectCoefficient(forcing_coeff);

  newton_solver->Mult(forcing, u_gf);
```

**Comment by stefanozampini** [comment]
If you're unsure of the Jacobian, you can use PetscNonlinearSolver and
compute the Jacobian from finite differencing for comparison. See
http://www.mcs.anl.gov/petsc/petsc-current/docs/manualpages/SNES/SNESComputeJacobian.html

Il 21 Mar 2017 9:18 PM, "Julian Andrej" <notifications@github.com> ha
scritto:

**Comment by vladotomov** [comment]
In the Assemble...() functions, elfun are the values at the degrees of freedom, not at the quadrature points.

**Comment by juan42** [comment]
Thanks for the clarification. So for the residual/gradient assemble i would need the values at the quadrature points? Or do i have to do some different operation with the elfun values?

**Comment by vladotomov** [comment]
Yes, you need to use the function values at the quadrature points (you iterate over quadrature points). In the above code, these values would be the inner products (shape * elfun).

**Comment by juan42** [comment]
Would this be correct? (I didn't understand the part with the inner product in your last message)
```cpp
  Vector fun_val(dof);
  fun_val = shape * elfun;
  double w = Tr.Weight() * fun_val(i) * fun_val(i);
  add(elvect, ip.weight * w, shape, elvect);
```
I proceeded similarly with the gradient and the residual decreases
```
Newton iteration  7 : ||r|| = 0.255388
Newton iteration  8 : ||r|| = 0.0244531
Newton iteration  9 : ||r|| = 0.00552096
Newton iteration 10 : ||r|| = 0.0188555
```
But still doesn't converge

**Comment by vladotomov** [comment]
From the definition of a finite element function, you need to compute
u(q_i) = sum_{j=1..#dofs} elfun_j shape_j(q_i).
That's the inner product part.
So try double fun_val = shape * elfun;
[ I'm not sure why you aren't getting segfaults for that indexing ]

**Comment by juan42** [comment]
Sure that makes more sense. I just checked and the code is valgrind clean (after the change). There is still the problem with the oscillating and non converging residual of the newton solver. The inner solves seem to be just fine
```
MINRES: iteration  18: ||r||_B = 2.87843e-10
```

**Comment by vladotomov** [comment]
Try it with H(u) = u.

**Comment by juan42** [comment]
That won't converge either. The solution somehow looks like if it is going in the right direction with huge oscillations on top. If that does help :-/

![image](https://cloud.githubusercontent.com/assets/5412886/24170115/1cca858a-0e80-11e7-93c4-7d805d23b3a6.png)

**Comment by vladotomov** [comment]
Is this H(u) = u? The screenshot shows that the gradient is still 2u :)

**Comment by juan42** [comment]
You are right, the screenshot is again the H(u) = u^2 case. The H(u) = u converges better but also oscillates somehoe.

![image](https://cloud.githubusercontent.com/assets/5412886/24170879/a14a9f8c-0e82-11e7-8c5c-714d92ff8381.png)

**Comment by vladotomov** [comment]
Now the Newton solver is behaving correctly, but something is wrong with your visualization. What are you plotting?

**Comment by juan42** [comment]
I intend to plot the solution from the gridfunction (u_gf)

```cpp
  GridFunction u_gf(h1_fespace);
  // u_gf.Randomize();
  u_gf = 1.0;

  FunctionCoefficient forcing_coeff(MMS);
  GridFunction forcing(h1_fespace);
  forcing.ProjectCoefficient(forcing_coeff);

  newton_solver->Mult(forcing, u_gf);

  double err = u_gf.ComputeL2Error(exact_sol_coeff);
  std::cout << "\nL2 norm of error: " << err << std::endl;

  socketstream sol_sock;
  char vishost[] = "localhost";
  int visport = 19916;
  sol_sock.open(vishost, visport);
  sol_sock.precision(8);
  sol_sock << "solution\n" << *mesh << u_gf << std::flush;
  sol_sock << "keys "
	   << "ac" << std::endl;
```

**Comment by vladotomov** [comment]
Plot forcing and see it it's correct.

**Comment by juan42** [comment]
The forcing is correct (perfect sin(a*x) or whatever i choose it to be)

**Comment by vladotomov** [comment]
I think you should do RHS_i = integral ( f(x) phi_i(x) ) instead of RHS_i = f(x_i).

**Comment by juan42** [comment]
Isn't that what ProjectCoefficient is doing? Otherwise it wouldn't display a smooth curve in glvis when plotting "forcing".
Also ProjectCoefficient calls FiniteElement::Project which is most of the time an inner product.
