### ISSUE TITLE
Solution discontinuous at process boundaries in parallel NC meshes

### ISSUE THREAD

**Issue by termi-official** [mfem/mfem#1601]
Hi guys,

I currently try to understand why some of my simulations result in highly discontinuous solutions. It seems to only happen that continuity is lost when a process boundary coincides with an non-conforming face. A minimal setup to reproduce the issue is to  augment example 6 (parallel) with random refinements. It does not matter whether the mesh or the pmesh is randomly refined, as long as enough non-conforming faces are created to increase the chance of coinciding with a process boundary.

For example using the provided Fichera mesh with 5 rounds of random refinement with 10% chance on the "mesh" (not the pmesh) and second order Ansatz gives me the following solution:

![Screenshot from 2020-07-03 00-23-28](https://user-images.githubusercontent.com/9196588/86414519-686ff100-bcc4-11ea-9337-5139824cbee8.png)

This might be related to #1326 and is not covered in #1392.

Here are two meshes I produced (old and new format)
* MFEM Format v1.1 [fichera-nc.mesh](https://github.com/mfem/mfem/files/4866936/fichera-nc.mesh.txt)
* MFEM NC Format v1.0 [fichera-nc-new.mesh](https://github.com/mfem/mfem/files/4866937/fichera-nc-new.mesh.txt)

Best regards,
Dennis

**Comment by jakubcerveny** [comment]
I'm not able to reproduce this, neither in `master` nor in `par-ncmesh-saving-dev`. I suspect this might be just a visualization artifact: as the solution gets more complex, GLVis starts skimping on triangles. Can you try pressing the `o` key to increase "resolution"?

**Comment by termi-official** [comment]
This way the visualization definitely starts to "grow together". Just to really confirm that this is just a visualization artifact, I will write a tool to check continuity of the solution field at the element interfaces. This also might help in future debugging sessions.

**Comment by tzanio** [comment]
@termi-official did you make any progress on this?

**Comment by termi-official** [comment]
Sorry @tzanio  I could not work on this one (and the other issues) the last days because I am running into some deadlines which keep me busy. I also cannot promise that I will be able to finish this one before the 25th. But at latest after the 25th I try to finish the above mentioned implementation and the associated PR asap.

**Comment by tzanio** [comment]
Nor rush, just checking

**Comment by tzanio** [comment]
Ping: @termi-official

**Comment by termi-official** [comment]
Hi @tzanio , I am still somewhat stuck with this one. 
I am pretty confident, that this is really just a visualization artifact, as Jakub pointed out, but I still have no "proof". The tool to check for continuity is currently blocked by the loading bug for nc meshes (see #1392 ). I have pushed my current progress into new branch https://github.com/mfem/mfem/tree/tool-check-continuity-dev . Integrating this tool into ex6p works and checks positive for continuity. Still, i was unable to test the tool properly yet.
The basic idea in this tool is to iterate over each face, where the grid function is evaluated at the integration points on each half face. The absolute difference (L1 distance) between the values at matching integration points is then used as an error measure for discontinuity (i.e. if the error is larger than some tolerance).

**Comment by tzanio** [comment]
Lets continue the discussion in #1392.
