### ISSUE TITLE
Integrator with coefficient varied by time.

### ISSUE THREAD

**Issue by HyeonjunLee** [mfem/mfem#1603]
Hello,

I’m a beginner using the MFEM library. I am developing a code to solve plasma Fokker-Planck equation in cylindrical coordinates. I referred to examples/ex9 and cyl-coordinates-dev/ex11p-cyl but I have not achieved my goal yet.

In my code, briefly attached below, the process that sets up the bilinear form and forms the linear algebra systems performs in each time step. Because the solution f is changed in each time step and the coefficients of integrator dependent on solution f (the coefficients of integrator are integral values of some functions about f), the code do repetitively that process. I think it is too inefficient and I want to reduce the process more efficiently.

Is this method unavoidable? Or are there any good ideas?

Thank you for your answers, in advance.

```c++
bool done = false;
for (int ti = 0; !done;)
{

   prevf.ProjectGridFunction(f);
   VectorFunctionCoefficient VFC_K(2, analytic_K);
   MatrixFunctionCoefficient MFC_D(2, analytic_D);
   MixedBilinearForm *k = new MixedBilinearForm(&fespace, &fespace_test);
   BilinearForm *m = new BilinearForm(&fespace);
   LinearForm *b = new LinearForm(&fespace);

   k->AddDomainIntegrator(new MixedScalarWeakDivergenceIntegrator(VFC_K));
   m->AddDomainIntegrator(new MassIntegrator(FC_2pir));
   k->AddDomainIntegrator(new MixedGradGradIntegrator(MFC_D));
   b->AddDomainIntegrator(new DomainLFIntegrator(FC_source));

   m->Assemble();
   m->Finalize();
   int skip_zeros = 0;
   k->Assemble(skip_zeros);
   k->Finalize(skip_zeros);
   b->Assemble();

   FE_Evolution adv(*m, *k, *b);
   if (ti == 0)
   {
      double t = 0.0;
      adv.SetTime(t);
      ode_solver->Init(adv);
   }
   double dt_real = min(dt, t_final - t);
   ode_solver->Step(f, t, dt_real);

        ti++;
}
```

**Comment by vikramsg** [comment]
Hi,

Its not clear to me which forms depend on f.  Regardless of that, you can take most of the initialisation out of the for loop, which should reduce time by a lot. Also, you can only update the forms that change with f. For the other forms you do not have to repeatedly assemble. 

```

            prevf.ProjectGridFunction(f);
            VectorFunctionCoefficient VFC_K(2, analytic_K);
            MatrixFunctionCoefficient MFC_D(2, analytic_D);
            MixedBilinearForm *k = new MixedBilinearForm(&fespace, &fespace_test);
            BilinearForm *m = new BilinearForm(&fespace);
            LinearForm *b = new LinearForm(&fespace);

            k->AddDomainIntegrator(new MixedScalarWeakDivergenceIntegrator(VFC_K));
            m->AddDomainIntegrator(new MassIntegrator(FC_2pir));
            k->AddDomainIntegrator(new MixedGradGradIntegrator(MFC_D));
            b->AddDomainIntegrator(new DomainLFIntegrator(FC_source));

            m->Assemble();
            m->Finalize();
            int skip_zeros = 0;
            k->Assemble(skip_zeros);
            k->Finalize(skip_zeros);
            b->Assemble();

            FE_Evolution adv(*m, *k, *b);
    for (int ti = 0; !done;)
    {
        m->Assemble();
        k->Assemble(skip_zeros);
       b->Assemble();
            if (ti == 0)
            {
                    double t = 0.0;
                    adv.SetTime(t);
                    ode_solver->Init(adv);
            }
            double dt_real = min(dt, t_final - t);
            ode_solver->Step(f, t, dt_real);

            ti++;
    }
```

**Comment by v-dobrev** [comment]
The right place to re-assemble the bilinear and/or linear forms is in the `TimeDependentOperator` (in the above code this is the `FE_Evolution` class). The reason is that the method `ode_solver->Step(f, t, dt_real);` will generally perform evaluation of the `TimeDependentOperator` not just at the time `t` but at other times as well.

Generally, a good option is to itimplement the virtual methods `Mult`, `ImplicitMult`, etc (depending on the time integrator used) to do the re-assembly, when needed.

As an optimization, if the action of a bilinear form needs to be applied just once for a given time `t`, it is possible to use a matrix-free implementation which will generally be faster than assembling a matrix and applying its action once.

**Comment by HyeonjunLee** [comment]
Thank you for the advice. My question has been solved.
