### ISSUE TITLE
SetTrueVector(), SetFromTrueVector()

### ISSUE THREAD

**Issue by fanronghong** [mfem/mfem#1605]
Hi all,

I have two simple questions. When and where should I use `SetTrueVector()` and `SetFromTrueVector()` ?

**Comment by tzanio** [comment]
In MFEM there is a difference between a `GridFunction`, which is a *finite element* object, and a corresponding vector of `true dofs`, which is a *linear algebra* object -- see this page for more details: https://mfem.org/pri-dual-vec/.

If you are running in serial without non-conforming AMR there is no difference between those two, and you shouldn't be calling the two functions you listed.

However, if you running in parallel or are using non-conforming meshes you should be aware of the difference -- the `GridFunction` is used for finite element operations (Projection, norm computation, visualization), while the vector of `true dofs` is needed to solve the global linear system.

Most of the time you have separate objects for the `GridFunction` and  the vector of `true dofs` and you transition between them using methods like `FormLinearSystem` or `RecoverFEMSolution`.

In some cases though, it could be convenient not to introduce an extra vector of `true dofs` and instead keep one internally in the `GridFunction` -- that's what the functions you listed are for.  `SetTrueVector()` performs restriction to from the `GridFunction` to the internal vector while `SetFromTrueVector()` performs an interpolation in the opposite direction.

One use case, see Example 24, is to ensure that a `GridFunction` is conforming after projection:

```c++
ParGridFunction gf(&fes);
gf.ProjectCoefficient(exact_coef);
gf.SetTrueVector();
gf.SetFromTrueVector();
```

The effect of the last two calls is to replace the values in the constrained nodes with interpolated values from the masters.

Hope this helps,
Tzanio

**Comment by fanronghong** [comment]
Thanks @tzanio ,

Your explanation is very detailed. I have a further question below.
```
// x_ is a Vector, u is a GridFunction.
u.MakeTRef(h1_space, x_, 0); 
u.SetTrueVector(); // Do I need this?
u.SetFromTrueVector(); // Do I need this?
cout << "L2 norm of u: " << u.ComputeL2Error(zero) << endl;
```

**Comment by v-dobrev** [comment]
After `u.MakeTRef(h1_space, x_, 0)` you need to call `u.SetFromTrueVector()` if you want to use `u` as a `Vector`, e.g. to read its entries.

When modifying `u`, as in the `for`-loop above, one needs to call `u.SetTrueVector()` or `u.SetFromTrueVector()` only when the internal T-vector is explicitly used in some way before or after that manipulation.

Basically, treat this internal T-vector as a separate `Vector` that uses a different memory pointer. The convenience is that this T-vector does not need to be explicitly defined if you already have a `GridFunction` -- it is implicitly defined (empty by default) for any `GridFunction`. However, its use is completely optional.

**Comment by fanronghong** [comment]
Thanks @v-dobrev , I understand it.
