### ISSUE TITLE
Wrong behavior at Neumann, Dirichlet corner

### ISSUE THREAD

**Issue by Andr00dz** [mfem/mfem#1607]
Hello,

I want to solve the Stokes equation with Neumann and homogeneous Dirichlet boundary conditions. In my code, the boundary conditions are included in the VectorDiffusion operator A, VectorDivergence operator B, and in the linear form of the velocity equation. This is done in the following lines 

`aVarf->EliminateEssentialBC(mark_bdr_attr_ess, x.GetBlock(0), rhs.GetBlock(0));`
`bVarf->EliminateTrialDofs(mark_bdr_attr_ess, x.GetBlock(0), rhs.GetBlock(1));`

```
mfem::ParLinearForm *fform(new mfem::ParLinearForm);
fform->Update(Vh_space, rhs.GetBlock(0), 0);
fform->AddDomainIntegrator(new mfem::VectorDomainLFIntegrator(f_coeff));
fform->AddBoundaryIntegrator(new mfem::VectorBoundaryLFIntegrator(f_nat_stress_coeff), mark_bdr_attr_nat);
fform->Assemble();
fform->ParallelAssemble(trueRhs.GetBlock(0)); 
```
`mark_bdr_attr_nat` and `mark_bdr_attr_ess` are vectors, where the boundary attributes are assigned to the corresponding boundary conditions.
The picture shows a solution of my code. The top, bottom, and inner edges are homogeneous Dirichlet egdes. The left and right side are Neumann boundary edges.
![bc](https://user-images.githubusercontent.com/56828429/86765038-e7f51b80-c048-11ea-8979-c94b3fb108ff.png)
At the four corners, where the Neumann and Dirichlet boundary condition edges meet, I would expect that the solution should be zero. It seems to me, that the corner DOF are not counted to the homogeneous Dirichlet boundary condition. How can it be fixed, such that the corners are counted to the Dirichlet boundary condition exlusively?
![cornerbug](https://user-images.githubusercontent.com/56828429/86761314-289f6580-c046-11ea-8417-6e98800615cf.png)

**Comment by jandrej** [comment]
From the look of your solution it seems you are using triangles. Maybe this is just a visualization artifact in paraview. Can you try to solve the same problem on quadrilaterals? The reason I'm saying this is, the orientation might play a role here. If you look at the top left triangle (this is just an assumption, since I can't see the mesh) we have
```
1               
+---+ 3
|  /
| /
|/
+ 
2
```
Dof 1 and 3 are really 0 but due to the value at dof 3 paraview shows an interpolated field on the whole element. This is just a guess, I'm not sure what causes this.

You can try to uniformly refine the mesh and see if the issue still persists.

**Comment by Andr00dz** [comment]
The same behavior appears on a unit square mesh where the boundary conditions are the same as above. Homogeneous Dirichlet for the velocity on the top and bottom. And Neumann boundary condition on the left and right side of the domain.
The Neumann boundary condition is set to du/dn - n*p = [1, 0]^T, where du/dn is the normal derivative of the velocity u and p is the pressure.

> quadratic elements with one refinement
> ![quad1](https://user-images.githubusercontent.com/56828429/87248707-419b8280-c45b-11ea-8f3d-762ee93faada.png)

> quadratic elements with two refinements
> ![quad2](https://user-images.githubusercontent.com/56828429/87248731-698ae600-c45b-11ea-933e-8555fb592957.png)

> quadratic elements with three refinements
> ![quad3](https://user-images.githubusercontent.com/56828429/87248738-7f001000-c45b-11ea-9f7b-66bb5d37e1ff.png)

> triangle elements with one refinement
> ![tri1](https://user-images.githubusercontent.com/56828429/87248753-a0f99280-c45b-11ea-900f-3af89a75ecb5.png)

> triangle elements with two refinements
> ![tri2](https://user-images.githubusercontent.com/56828429/87248762-aa82fa80-c45b-11ea-845e-fbb26ffdcc1d.png)

> triangle elements with three refinements
> ![tri3](https://user-images.githubusercontent.com/56828429/87248766-b5d62600-c45b-11ea-92fe-48611c66b505.png)

This effect is clearly visible for quadratic and triangle elements at just one mesh refinement. The velocity at the top and bottom corners is not zero. It should be zero there too.  Refining the mesh reduces this effect, but convergence tests show that for Taylor-Hood elements Q2/Q1, this effect seems to prevent the pressure to converge with O(h^2). Instead,  a convergence rate slightly higher than 1 which then converges toward 1 is observed.

**Comment by jandrej** [comment]
Are those meshes generated by mfem? If not, is there a possibility that the corner dof is in multiple attributes? Although this shouldn't matter if you are imposing Dirichlet on top.

It looks like you are missing elimination of certain dofs in your block system. Looking at the block structure
```
A B
C 0
```
Do you eliminate
- rows/cols on A
- _only_ rows on B
- _only_ columns on C?

Do you do the appropriate modifications in your rhs?

**Comment by Andr00dz** [comment]
> Are those meshes generated by mfem? If not, is there a possibility that the corner dof is in multiple attributes? Although this shouldn't matter if you are imposing Dirichlet on top.

The mesh is generated by mfem and the boundary attributes of the edges are set via a loop over the boundary egdes and setting the attribute of the edge via  `bdr_elem->SetAttribute(...);', where the attribute is determined via the position of the edge center.


The block A is created with the following lines:
```
  mfem::HypreParMatrix *A;
  mfem::ParBilinearForm *aVarf(new mfem::ParBilinearForm(Vh_space));
  aVarf->AddDomainIntegrator(new mfem::VectorDiffusionIntegrator(k_coeff));
  aVarf->Assemble();
  aVarf->EliminateEssentialBC(mark_bdr_attr_ess, x.GetBlock(0), rhs.GetBlock(0)); // eliminate rows and cols
  aVarf->Finalize();
  A = aVarf->ParallelAssemble();
```
The block C is created with 
```
  mfem::HypreParMatrix *B;
  mfem::ParMixedBilinearForm *bVarf(new mfem::ParMixedBilinearForm(Vh_space, Wh_space));
  mfem::ConstantCoefficient minus_one(-1.0);
  bVarf->AddDomainIntegrator(new mfem::VectorDivergenceIntegrator(minus_one));
  bVarf->Assemble();
  bVarf->EliminateTrialDofs(mark_bdr_attr_ess, x.GetBlock(0), rhs.GetBlock(1)); // eliminate cols
  bVarf->Finalize();
  B = bVarf->ParallelAssemble();
```
The block B is created with 
`  mfem::HypreParMatrix *BT = B->Transpose(); // rows are eliminated since cols are eliminated already above?`

> Do you do the appropriate modifications in your rhs?

The rhs for the velocity equation is created with these lines of code
```
  mfem::ParLinearForm *fform(new mfem::ParLinearForm);
  fform->Update(Vh_space, rhs.GetBlock(0), 0);
  fform->AddDomainIntegrator(new mfem::VectorDomainLFIntegrator(f_coeff));
  fform->AddBoundaryIntegrator(new mfem::VectorBoundaryLFIntegrator(f_nat_stress_coeff), mark_bdr_attr_nat); // inlcude Neumann data
  fform->Assemble();
  fform->ParallelAssemble(trueRhs.GetBlock(0)); 
```
After that, the different operators are put together into one BlockOperator that is passed to the solver.

**Comment by jandrej** [comment]
If I understand correctly, you are not modifying the rhs on the dofs where you apply Dirichlet boundary conditions.

**Comment by Andr00dz** [comment]
I thought this was already done with 
`aVarf->EliminateEssentialBC(mark_bdr_attr_ess, x.GetBlock(0), rhs.GetBlock(0));` and
`bVarf->EliminateTrialDofs(mark_bdr_attr_ess, x.GetBlock(0), rhs.GetBlock(1));`
since there `rhs` is required. Is there a command for linear forms similar to EliminateEssentialBC for bilinear forms to eliminate the Dirichlet DOFs? At https://mfem.github.io/doxygen/html/classmfem_1_1LinearForm.html I did not find any command related to that

**Comment by jandrej** [comment]
What you can try is using https://mfem.github.io/doxygen/html/classmfem_1_1MixedBilinearForm.html#ab5e9b0ff5dc7fa7063fbce7a5b5816e5
and see if that helps.

We wrote this in the process of implementing similar physics that result in a block system.

**Comment by chakshinglee** [comment]
Just to double check: 
1. did you assemble your `rhs` before you apply the elimination step?
```aVarf->EliminateEssentialBC(mark_bdr_attr_ess, x.GetBlock(0), rhs.GetBlock(0));```
This should set the values of essential dofs in `rhs` to the values of the corresponding essential dofs in `x`.
But if you assemble your `fform` after the elimination step above, values in `rhs` will be overwritten.
2. did you assemble the "true right hand side" after the elimination step?
```fform->ParallelAssemble(trueRhs.GetBlock(0)); ```
`ParallelAssemble` is based on the current value of `fform`, so if you perform the elimination step after the true rhs is assembled, the true rhs will NOT be updated automatically.

So the sequence of actions should be, sequential assemble of `fform` (or `rhs`) -> elimination -> parallel assemble.

**Comment by Andr00dz** [comment]
> 
> 
> Just to double check:
> 
>     1. did you assemble your `rhs` before you apply the elimination step?
>        `aVarf->EliminateEssentialBC(mark_bdr_attr_ess, x.GetBlock(0), rhs.GetBlock(0));`
>        This should set the values of essential dofs in `rhs` to the values of the corresponding essential dofs in `x`.
>        But if you assemble your `fform` after the elimination step above, values in `rhs` will be overwritten.
> 
>     2. did you assemble the "true right hand side" after the elimination step?
>        `fform->ParallelAssemble(trueRhs.GetBlock(0)); `
>        `ParallelAssemble` is based on the current value of `fform`, so if you perform the elimination step after the true rhs is assembled, the true rhs will NOT be updated automatically.
> 
> 
> So the sequence of actions should be, sequential assemble of `fform` (or `rhs`) -> elimination -> parallel assemble.

These two tipps solved my issue. Thank you! Now I get the correct behavior of the solution.
![correctCorner](https://user-images.githubusercontent.com/56828429/87546170-62f1ae00-c6a9-11ea-9605-2d716e46f039.png)
