### ISSUE TITLE
Problem with Trimmer miniapp

### ISSUE THREAD

**Issue by e-aranda** [mfem/mfem#1608]
I am trying to use the miniapps trimmer but I find an error. I use the simple mesh showing at the end with attributes 2 and 3, and run as:

    /trimmer -m  ~/Escritorio/mimalla-mfem.mesh -a '2'

and the result is:

     Options used:
      --mesh /home/earanda/Escritorio/mimalla-mfem.mesh
      --attr '2'
      --bdr-attr ''
      --visualization
    Number of Elements:          18 -> 9
    Number of Boundary Elements: 17 -> 11

    Verification failed: (boundary.Size() == NumOfBdrElements) is false:
     --> incorrect number of boundary elements: preallocated: 11, actually added: 14
     ... in function: void mfem::Mesh::FinalizeCheck()
     ... in file: mesh/mesh.cpp:1382

    Abortado (`core' generado)

Any hints?

    ###################### mesh file
    MFEM mesh v1.0
    
    #
    # MFEM Geometry Types (see mesh/geom.hpp):
    #
    # POINT       = 0
    # SEGMENT     = 1
    # TRIANGLE    = 2
    # SQUARE      = 3
    # TETRAHEDRON = 4
    # CUBE        = 5
    #
    
    dimension
    2
    
    elements
    18
    2 2 0 1 5
    2 2 0 5 4
    3 2 1 2 6
    2 2 1 6 5
    3 2 2 3 7
    3 2 2 7 6
    2 2 4 5 9
    2 2 4 9 8
    3 2 5 6 10
    2 2 5 10 9
    3 2 6 7 11
    3 2 6 11 10
    2 2 8 9 13
    2 2 8 13 12
    3 2 9 10 14
    2 2 9 14 13
    3 2 10 11 15
    3 2 10 15 14
    
    boundary
    17
    2 1 0 1
    2 1 1 2
    2 1 2 3
    3 1 3 7
    3 1 7 11
    3 1 11 15
    4 1 13 12
    4 1 14 13
    4 1 15 14
    5 1 4 0
    5 1 8 4
    5 1 12 8
    1 1 6 1
    1 1 6 5
    1 1 10 5
    1 1 10 9
    1 1 14 9
    
    vertices
    16
    2
    0 0
    0.333333333333 0
    0.666666666667 0
    1 0
    0 0.333333333333
    0.333333333333 0.333333333333
    0.666666666667 0.333333333333
    1 0.333333333333
    0 0.666666666667
    0.333333333333 0.666666666667
    0.666666666667 0.666666666667
    1 0.666666666667
    0 1
    0.333333333333 1
    0.666666666667 1
    1 1
    ###################### end mesh file

**Comment by rw-anderson** [comment]
It's not immediately obvious to me why there's an error, but maybe these pictures will help someone else identify the issue:

Original mesh:
![mesh1](https://user-images.githubusercontent.com/11507994/86831084-4e7b3900-c04b-11ea-9b2d-4ae1dc7c0387.png)

Mesh after toggling off attribute 2 in glvis:
![mesh1-trim](https://user-images.githubusercontent.com/11507994/86831096-520ec000-c04b-11ea-8df4-8a97e72f87f1.png)

**Comment by rw-anderson** [comment]
Your mesh seems to have internal boundary elements:

![Screenshot from 2020-07-07 12-37-42](https://user-images.githubusercontent.com/11507994/86833682-b67f4e80-c04e-11ea-8267-eceebe5d4c6d.png)

This confuses the trimming algorithm, because it assumes that faces that are created by dropping elements are new faces that need to be added to the mesh. But in your case, those boundaries are already copied from the original mesh, creating redundant boundary elements, leading to the error.

The trimmer should work if you remove the internal boundary elements.  The new boundary elements will be automatically created.

**Comment by e-aranda** [comment]
ok, I see. is there any way to remove these nternal boundaries from MFEM?

**Comment by mlstowell** [comment]
There is a member function that might do this: `Mesh::RemoveInternalBoundaries()`.  I don't think I've tried it myself but it should work.

**Comment by rw-anderson** [comment]
You could remove them using the member function shown above, or you could not insert them in the first place, depending on how the mesh file was created.

**Comment by e-aranda** [comment]
Thank you! Now it is working fine! 

I have another question related with trimmer but I am opening a new thread
