### ISSUE TITLE
Evaluate kinematic gradients at scalar quadrature points

### ISSUE THREAD

**Issue by mosawe** [mfem/mfem#1609]
Hello, 

What is the available API for computing say velocity gradients at L2 quadrature points from its originating kinematic quadrature points? Effectively reducing say the 16 quadrature points for velocity to 9 quadrature points for density so that some other quantities can evaluated in a collocated fashion at L2. Suggestions, or pointers to accomplish this and vice-versa will be much appreciated. Is Example 24 the way to go in this case?

Thanks.
Maxwell

**Comment by tzanio** [comment]
Hi Maxwell,

Just to clarify -- you are asking how to compute velocity gradient at quadrature points (e.g. 3x3 Gauss-Legendre points in 2D) from velocity values in degrees of freedom (e.g. 4x4 Gauss-Lobatto points in 2D), correct?

Tzanio

**Comment by mosawe** [comment]
Hi Tzanio,

That’s correct.

Thanks,
Maxwell

**Comment by tzanio** [comment]
@camierjs or @v-dobrev may be able to provide further details, but you can use the `QuadratureInterpolator` class for that, see for example these lines in the Laghos miniapp:

https://github.com/CEED/Laghos/blob/master/laghos_solver.cpp#L1072-L1074

If you are not looking at GPU / partial assembly, then you can use `GridFunction::GetVectorGradient`.

**Comment by mosawe** [comment]
Thanks for your response. l will give it a try.

Maxwell

**Comment by tzanio** [comment]
Closing this for now. Feel free to reopen if you have additional questions.

**Comment by mosawe** [comment]
Ok, thanks.
Maxwell
