### ISSUE TITLE
Array append another Array

### ISSUE THREAD

**Issue by fanronghong** [mfem/mfem#1613]
Hi all,

I find something confusing. Why are `block[0]` and `block[1]` the same? Is this a bug or something I don't understand?

```
#include "mfem.hpp"
#include <iostream>

using namespace std;
using namespace mfem;

int main(int argc, char *argv[])
{
    // scope 1
    Array<Array<int>> block;

    {   // scope 2: I want to insert Array<int> into block in other scope.
        Array<int>* arr1 = new Array<int>;
        for (int i=0; i<3; ++i)
        {
            arr1->Append(i);
        }
        block.Append(*arr1);
        delete arr1;

        Array<int>* arr2 = new Array<int>;
        for (int i=0; i<3; ++i)
        {
            arr2->Append(i*10);
        }
        block.Append(*arr2);
        delete arr2;
    }

    // get back to scope 1
    block[0].Print(cout << "block[0]:\n"); // output: 0 10 20
    block[1].Print(cout << "block[1]:\n"); // output: 0 10 20
}
```

**Comment by rw-anderson** [comment]
I looked at this briefly.  I can confirm your result, and add a few observations.

Your test code not only gives unexpected results, but also shows double frees when run under valgrind.

Adding ````block.Reserve(2)```` fixes both issues.  This strongly implies that the trouble occurs within the resizing process of the outer Array.

**Comment by v-dobrev** [comment]
The `Array` class only supports POD (plain-old-data) types. The class `Array` itself is not a POD type, so `Array`s of `Array`s are NOT supported. However, you can always use `std::vector<Array<int>>`.

**Comment by rw-anderson** [comment]
I think the documentation should be updated, since it says that T is a "generic type", which suggests a more general implementation than POD data.

**Comment by psocratis** [comment]
@v-dobrev this can be done also with pointers I guess? 
Something like 

````cpp
   Array<Array<int> * > block;
   Array<int>* arr1 = new Array<int>;
   for (int i=0; i<3; ++i)
   {
      arr1->Append(i);
   }
   block.Append(arr1);

   Array<int>* arr2 = new Array<int>;
   for (int i=0; i<3; ++i)
   {
      arr2->Append(i*10);
   }
   block.Append(arr2);

   block[0]->Print(cout << "block[0]:\n");
   block[1]->Print(cout << "block[1]:\n");
   delete arr1;
   delete arr2;
````
This gives 
````
block[0]:
0 1 2
block[1]:
0 10 20
````

**Comment by tzanio** [comment]
Yes, `Array<int> *` is POD, but `Array<int>` is not.

**Comment by rw-anderson** [comment]
Documentation update suggested in #1615 .

**Comment by fanronghong** [comment]
Thanks all.
It works.
