### ISSUE TITLE
Displayed MFlops always 0

### ISSUE THREAD

**Issue by yadielis** [mfem/mfem#1614]
When running Example 2 with the hex-beam mesh, the line "Wall MFLOPS:" always seems to be 0. Increasing the resolution and scale of the mesh increases the wallclock time but doesn't seem to affect the MFLOPS in any way. Can someone explain this? Am I doing something wrong?

**Comment by tzanio** [comment]
There is no `Wall MFLOPS:` line in the output of `examples/ex2.cpp`. Can you clarify what exactly are you running?

**Comment by v-dobrev** [comment]
I think this is output from hypre, not sure if you need to enable some hypre option to get actual numbers.

**Comment by yadielis** [comment]
This is my command line for ex2p

mpirun --mca btl tcp,self -np 4 ./ex2p -m ../data/beam-quad.mesh

And then Solve phase times:
wall clock time = 0.02s
wall MFLOPS = 0.00s
cpu clock time = 0.03s
cpu MFLOPS = 0.00s

**Comment by tzanio** [comment]
As @v-dobrev suggested, this output comes from hypre. You can try asking about it at https://github.com/hypre-space/hypre/issues.
