### ISSUE TITLE
ADIOS2 data collection leaves out element attributes

### ISSUE THREAD

**Issue by rcarson3** [mfem/mfem#1616]
Guess this is partially my fault for not noticing this while reviewing the original ADIOS2 PR but I just noticed that the data collection doesn't save off the element attributes. I'm starting to need that value as part of some my post-processing to associate certain data with a given attribute. So, it would be nice if this could be added into that data collection.

In the mean time, I've got a temporary fix where I should just be able to create a ```GridFunction``` using an L2 ```FiniteElementSpace``` and just save the element attributes off that way.

**Comment by tzanio** [comment]
@williamfgc can you take a look at this when you get a chance?

**Comment by rcarson3** [comment]
So, I've been playing around this data collection a bit more, and my temporary fix worked quite well. Also, it appears to me that there could be a potential storage space savings to be had if you have a gridfunction with an L2 FiniteElementSpace of order 0.  Then you could save the data off using the element tag in VTK xml scheme rather than saving off number of element nodes  times as much data associated with point data. Depending on how many variables you're saving off like this, you could see a pretty nice space savings from such an optimization especially once you start using higher order elements or just really large meshes.

**Comment by williamfgc** [comment]
@tzanio @rcarson3 apologies for the late reply, I'll set up a meeting with @rcarson3 to work on this. Thanks for the feedback!

**Comment by williamfgc** [comment]
@rcarson3 I see the `ParaviewCollection` is assigning the element attribute [always as "material"](https://github.com/mfem/mfem/blob/master/fem/datacollection.cpp#L909). Is this the preferred name rather than the more generic "element attribute"? Please let me know, so I can add it to the schema like this:
```
  <CellData>
        <DataArray Name="material" />
  </CellData>
```

**Comment by rcarson3** [comment]
@williamfgc if that's what the ParaviewCollection is using it might not be a bad thing to keep that consistent across the data collections as long as it's documented that the mesh element attribute = material output variable name.

**Comment by pnorbert** [comment]
@rcarson3 @williamfgc Do you need any help from the ADIOS2 team to progress on this issue? Is #1704 fixing your issue?

**Comment by rcarson3** [comment]
@pnorbert sorry for the delayed response. So #1704 partially addresses the above issues. It does add the element attribute to the output. However, it appears that the current ADIOS2 reader in ParaView v5.8.1 does not recognize the outputted cell data as something that can be visualized.

The other concern I had regarding space savings for gridfunctions of an L2 finite element space with an order 0 (essentially element/cell data rather than point data but is currently outputted as point data) is also not addressed in that PR. However, you would need to ask @williamfgc to see if he'll need help from the ADIOS2 to implement this feature into MFEM.

Also on another note, I didn't notice this until I started deforming my mesh quite a bit, but the mesh is constant through out time, which doesn't follow with the rest of the data collections which output the mesh at each time step. I'd imagine if this was updated then the ADIOS2 collection could also support AMR meshes as well. Now if you have the displacement field outputted then this is fine because you can just use the warp filter with the displacement field to get out the current mesh. However, I don't believe there is any documentation that states this which should probably be added in either #1704 or a future PR with ADIOS2.

**Comment by rcarson3** [comment]
@pnorbert just wanted to ping you to see if you'd had a chance to look over my last comment about this issue.

**Comment by pnorbert** [comment]
Hi, I thought @williamfgc addressed your issues with #1757

**Comment by rcarson3** [comment]
@pnorbert so #1757 addressed the element attribute part of the issue. However, the space-saving optimization wasn't addressed in that PR, and it'd be nice to have that one addressed in-order to make use of ADIOS2 with large simulations with tens of millions of elements and saving off any appreciable number of time steps and state variables/fields.

**Comment by williamfgc** [comment]
@rcarson3 let's make a separate PR as the work is very different and required cell centered visualization support in VTK which is work in progress. Let me know what you think. There is also the moving mesh issue.

**Comment by rcarson3** [comment]
@williamfgc a separate PR or PRs is fine. I just wanted to make sure this doesn't end up getting forgotten about now that all of the end of the FY madness has calmed down.

**Comment by williamfgc** [comment]
@rcarson3 thanks, I just want to make sure at least one piece is done. Yes, it's been madness. We also have a related issue related to linking [adios2 v2.6.0 and VTK](https://github.com/ornladios/ADIOS2/issues/2449). Thanks for pushing this, it won't be forgotten from my side :)

**Comment by benzwick** [comment]
> @rcarson3 I see the `ParaviewCollection` is assigning the element attribute [always as "material"](https://github.com/mfem/mfem/blob/master/fem/datacollection.cpp#L909). Is this the preferred name rather than the more generic "element attribute"?

> @williamfgc if that's what the ParaviewCollection is using it might not be a bad thing to keep that consistent across the data collections as long as it's documented that the mesh element attribute = material output variable name.

The `PrintVTU` function (but not yet ParaviewCollection) is now using `attribute` instead of `material` as discussed here: https://github.com/mfem/mfem/pull/1825#issuecomment-713868907

**Comment by williamfgc** [comment]
@benzwick thanks for pointing it out! I just did a PR. @rcarson3 I'll be doing a PR on ParaView in the next few days for cell data visualization, I'll let you know when it's merged. Thanks!

**Comment by williamfgc** [comment]
@rcarson3 just following up on ParaView support I did a [merge request](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/7401) related to this issue. I'll keep you posted for when this is merged.

**Comment by williamfgc** [comment]
It took a while, but the [VTK/#7401](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/7401) got merged. Hopefully, this is soon available on ParaView nightly :)
