### ISSUE TITLE
Double integral problem

### ISSUE THREAD

**Issue by HyeonjunLee** [mfem/mfem#1619]
Hello,
I am developing a code to solve the plasma Fokker-Planck equation with the MFEM library.

The system that I want to solve can be written simply as df/dt=-del ⋅ (D del f) in cylindrical coordinates (r, z). 
The weak formulation is written as follows:
2*pi*\int_\Omega{drdz r df/dt} = \int_\Omega{drdz r -del ⋅ (D(r,z) del f)}
which the D is \int_\Omega {drbar dzbar rbar U(r,z,rbar,zbar)*fbar}.

The key point of my question is that the coefficient D needs to be taken an integral of the function U in the bar coordinates (rbar, zbar), not (r, z).
I am doing this process like below:

        FunctionCoefficient FC_D(analytic_D);
        FunctionCoefficient FC_U(analytic_U);
        BilinearForm *D = new BilinearForm(&fespace, &fespace_test);
        BilinearForm *m = new BilinearForm(&fespace);
        LinearForm *b = new LinearForm(&fespace);

        D->AddDomainIntegrator(new DiffusionIntegrator(FC_D));
        m->AddDomainIntegrator(new MassIntegrator(FC_2pir));
        b->AddDomainIntegrator(new DomainLFIntegrator(FC_source));

The following is \int_\Omega {drbar dzbar rbar U(r,z,rbar,zbar)*fbar}.

        double analytic_D(const Vector &x)
        {
                r = x(1), z = x(0);
                GridFunctionCoefficient GFC_f(&f);
                LinearForm u(&fespace);
                u.AddDomainIntegrator(new DomainLFIntegrator(FC_U));
                u.Assemble();
                return -r * u(GFC_f);
        }

        double analytic_U(const Vector &x)
        {
                double rbar = x(1), zbar = x(0);
                double s = 2. * rbar * r / (pow(rbar, 2) + pow(r, 2) + pow(zbar - z, 2));
                double U = fourpi * rbar * pow(pow(rbar, 2) + pow(r, 2) + pow(zbar - z, 2), -1.5) * (pow(r, 2) * varI(s, 1) + pow(zbar - z, 2) * varI(s, 2));
                return U;
        }

Is this a right way to calculate the double integral? or is there anything to refer?
If possible, I want to know how to calculate double integrals in other cases.

**Comment by homijan** [comment]
Hi @HyeonjunLee,

thank you for your interest in using MFEM for Fokker-Planck.

Could you provide more details about your approach such as: 
1) Is your goal to use an explicit time discretization?
2) Do you plan to use Piccard for the nonlinear solve (maybe just one-step)?
If the answers are yes, I believe that your approach is correct. The use of coefficient suits well to address the double integral evaluation. I would suggest to define a "smart" coefficient, which uses the distribution function. This coefficient can calculate the "bar" integral and provide its result in Eval(...) member function.
I would just point out, that the double integral involves different dimensions namely 2D in rz spatial coordinates and 2D in rbarzbar velocity coordinates.
Do not hesitate to reach out to us with more questions if needed.

**Comment by HyeonjunLee** [comment]
Thank you for the reply. I`m a beginner so your advice will help a lot.
 
1. Yes. for now, I use an explicit time discretization.

2. Actually, I haven`t consider about it. Should my approach be modified if I use another method for the nonlinear solve?

2 - 1, Assuming I use Picard, does your suggestion (define a "smart" coefficient) mean that I define a new Coefficient class like as the 'ElasticEnergyCoefficient' in 'ex17.cpp'?

2 - 2. Also, as I mentioned earlier, D is \int_\Omega {drbar dzbar rbar U(r,z,rbar,zbar)*fbar}.
U is a function that does not change over time and fbar is a variable that changes over time. I want to save coefficients of rbar * U and to use them to do an integral with fbar each time step. Can I do this technically?

**Comment by v-dobrev** [comment]
Hi @HyeonjunLee,

Looking at the definitions of `analytic_U` and `analytic_D`, the variables `r` and `z` are defined globally, right? This is how you propagate their values from `analytic_D` to `analytic_U`, I assume.

Now, since you want to integrate `rbar U(r,z,rbar,zbar)*fbar`, in your code you need to include the scaling with `rbar` in your `analytic_U` function, or create a separate function called `analytic_rbar_U` and use that in the `DomainLFIntegrator` inside `analytic_D`. I assume `fbar` is represented by the (global?) `GridFunction` `f`.

Another remark: the `Mesh` of the `fespace` used in `analytic_D` should represent a mesh of your `(zbar,rbar)` domain. If the domain for `(z,r)` is different from the one for `(zbar,rbar)` then you probably need two separate meshes.

Other than that, it looks like `analytic_D` should work properly. Of course, the cost of each evaluation of `analytic_D` is not cheap but I don't know if there is anything that can be done about that.

**Comment by HyeonjunLee** [comment]
Hi, @v-dobrev.
Thank you for the comment.

Yes, the variables `r`, `z`, and `f` are defined globally.

Your comment helped it working well but the calculation time of `analytic_D` is too long so I think I need to find whether there are other ways to do double integral efficiently.
