### ISSUE TITLE
Parallel efficiency

### ISSUE THREAD

**Issue by lephlaux** [mfem/mfem#1624]
Dear all:

This concerns benchmarking an MFEM program that builds on MFEM examples.  Built and solved is a saddle-point problem in 3D on a domain with complex geometry, the total number of DOFs is about 5E7.  The test for strong scaling yields

![Screenshot from 2020-07-16 11-31-03](https://user-images.githubusercontent.com/807224/87655615-c981d500-c758-11ea-99e9-a2cc491086af.png)

Can someone tell me if this result is reasonable and if so, why the parallel efficiency of the assembly exceeds one?

Some notes:
- Each time was taken only once (I know that I should average over multiple measurements), however, repeated calls revealed similar computation times in the sense that the trend stays the same.
- The **meshing** obviously does not scale.  The mesh file (vtk, 1.2 GB, UNSTRUCTURED_GRID, legacy format with ASCII encoding) is loaded by one or up to ten processes and then the chunks are sent to all other processes.  
- The **assembly** consists of just standard integrators and DOF eliminators from the FEM library.
- The **solver** is MINRES with an AMG-V-cycle as the preconditioner.
- The computation time for each of the three items is measured via
```
mfem::StopWatch chrono;
chrono.Clear();
chrono.Start();
// [performance critical code]
mpiwrapper::barrier();
chrono.Stop();
```

**Comment by v-dobrev** [comment]
One typical reason for efficiency > 1 in strong scaling is the following: as the per-processor problem size gets smaller, the data becomes small enough to fit in cache, causing the code to run faster.

In your results, however, there must be something else going on too, because you see this greater-than-1 efficiency right away -- going from 1 to 2 nodes. My guess is that on 2 nodes the problem is still not small enough to fit in cache, so there must be something else going on.

**Comment by tzanio** [comment]
I agree with @v-dobrev -- something doesn't seem quite right for the assembly. Maybe you need a barrier before the computations too? Note also that for high-orders the default assembly can be very inefficient and you should really use *partial assembly* if possible.

For the solve phase, is the time per iteration or for the full solve? In the latter case, you also want to report the number of MINRES iterations, which likely will increase.

**Comment by lephlaux** [comment]
Thank you for your comments.  I will add a barrier also before the computations, as proposed by @tzanio, and will report back when I have the results.

I'd like to comment on the other mentioned topics:

@tzanio: We measure the time for the full solve. The **number of iterations** does increase _on average_ (not monotonically) with the numbers of cores, mainly due to round-off errors in the matrix-vector product in the Krylov solver.  Recall that we test for strong scaling—hence the condition number is constant in all runs.  This behavior was documented in the publication http://dx.doi.org/10.1108/02644400610644522 by the way (thanks @Andr00dz for the reference).  The following table was taken from a different run (with hyperthreading, which is useless here due to memory-boundedness), but for the same benchmark problem:

#procs | #nodes | #iterations
-- | -- | --
1 | 1 | 785
2 | 1 | 791
4 | 1 | 792
10 | 1 | 795
20 | 1 | 798
40 | 1 | 812
80 | 2 | 807
120 | 3 | 801
160 | 4 | 821
200 | 5 | 823
240 | 6 | 818
280 | 7 | 812
320 | 8 | 821
800 | 20 | 847

@v-dobrev: The cluster we used for benchmarking is an older one, https://www.anleitungen.rrze.fau.de/hpc/emmy-cluster/ —"560 compute nodes, each with two Xeon 2660v2 „Ivy Bridge“ chips (10 cores per chip + SMT) running at 2.2 GHz with 25 MB Shared Cache per chip and 64 GB of RAM".  I'm no expert in low-level stuff, but maybe this helps to understand the situation: 5E7 global DOFs (and these are the "true DOF", the actual DOF are more) correspond to 5E7*8 Bytes = 400 MB.  And that's just the primal vector—we also got a RHS, an operator, and the preconditioner.

**Comment by lephlaux** [comment]
I repeated the runs with barriers added before each `chrono.Start()`, but it did not change the trend:

![Screenshot from 2020-07-21 10-03-44](https://user-images.githubusercontent.com/807224/88029501-5e5e4700-cb3a-11ea-9cf3-1780eb3bb45f.png)

Here is the raw data:

#procs | #nodes | #mesh loads | wt mesh gen | wt assembly | wt solver | #iterations
-- | -- | -- | -- | -- | -- | --
20 | 1 | 1 | 790.771 | 608.631 | 838.093 | 831
40 | 2 | 2 | 763.39 | 274.991 | 426.033 | 845
80 | 4 | 4 | 748.597 | 133.849 | 214.615 | 839
120 | 6 | 6 | 745.823 | 86.0347 | 144.652 | 833
160 | 8 | 8 | 744.721 | 64.1313 | 112.889 | 854
200 | 10 | 10 | 740.791 | 50.3933 | 91.1315 | 855
240 | 12 | 10 | 846.209 | 42.1571 | 76.7121 | 851
280 | 14 | 10 | 976.301 | 35.7715 | 66.1272 | 845
320 | 16 | 10 | 1067.17 | 31.1186 | 59.0644 | 855
400 | 20 | 10 | 1281.27 | 24.8023 | 48.5946 | 856
600 | 30 | 10 | 1820.71 | 16.4405 | 35.0569 | 874

(**wt** is wall time in seconds, **#mesh loads** denote the number of processes that load the (serial) mesh file and that distribute mesh chunks across the network).

The parallel efficiency of the assembly asymptotically approaches a constant value here (which is fine to me).  Due to the discussion above, I would go with @v-dobrev's answer, in particular, as I believe the problem is big enough: 

> One typical reason for efficiency > 1 in strong scaling is the following: as the per-processor problem size gets smaller, the data becomes small enough to fit in cache, causing the code to run faster.
