### ISSUE TITLE
Compiling examples & miniapps broken with CUDA+PETSc

### ISSUE THREAD

**Issue by wcdawn** [mfem/mfem#1625]
When building the MFEM library with CUDA+PETSc, the miniapps cannot be compiled.
(Note this also affects SLEPc as it depends on PETSc.)
If MFEM is configured without CUDA or without PETSc, the compilation is fine.
It seems the problem is the parsing of Xlinker flags (`-Wl`) by `nvcc`.
This is with CUDA version 10.2.89.

The command used to configure MFEM is:
```
make config MFEM_USE_MPI=YES MFEM_USE_METIS_5=yes MPICXX=/opt/mpich/bin/mpicxx METIS_DIR=@MFEM_DIR@/../metis MFEM_USE_CUDA=YES MFEM_USE_PETSC=YES PETSC_DIR=PETSC_DIR=/home/wcdawn/projects/petsc/arch-linux-c-debug/
```

Then, in the examples directory, executing `make ex1p` generates the command
```
nvcc  -O3 -std=c++11 -x=cu --expt-extended-lambda -arch=sm_60 -ccbin /opt/mpich/bin/mpicxx -I.. -I../../hypre/src/hypre/include -I../../metis/include -I/home/wcdawn/projects/petsc/include -I/home/wcdawn/projects/petsc/arch-linux-c-debug/include -I/opt/cuda/include -I/opt/mpich/include ex1p.cpp -o ex1p -L.. -lmfem -L../../hypre/src/hypre/lib -lHYPRE -L../../metis/lib -lmetis -Wl,-rpath,/home/wcdawn/projects/petsc/arch-linux-c-debug/lib -L/home/wcdawn/projects/petsc/arch-linux-c-debug/lib -lpetsc -Wl,-rpath,/opt/cuda/lib -L/opt/cuda/lib -llapack -lblas -lpthread -lX11 -lm -lcufft -lcublas -lcudart -lcusparse -lcusolver -lcuda -lquadmath -lstdc++ -ldl -lrt
```
Which fails with error
```
nvcc fatal   : Unknown option '-Wl,-rpath,/home/wcdawn/projects/petsc/arch-linux-c-debug/lib'
```

`ex1p` can be successfully compiled using `--compiler-options` and `-Xlinker` options as
```
nvcc  -O3 -std=c++11 -x=cu --expt-extended-lambda -arch=sm_60 -ccbin /opt/mpich/bin/mpicxx -I.. -I../../hypre/src/hypre/include -I../../metis/include -I/home/wcdawn/projects/petsc/include -I/home/wcdawn/projects/petsc/arch-linux-c-debug/include -I/opt/cuda/include -I/opt/mpich/include ex1p.cpp -o ex1p -L.. -lmfem -L../../hypre/src/hypre/lib -lHYPRE -L../../metis/lib -lmetis --compiler-options -Xlinker --compiler-options -rpath --compiler-options -Xlinker --compiler-options /home/wcdawn/projects/petsc/arch-linux-c-debug/lib -L/home/wcdawn/projects/petsc/arch-linux-c-debug/lib -lpetsc --compiler-options -Xlinker --compiler-options -rpath --compiler-options -Xlinker --compiler-options /opt/cuda/lib -L/opt/cuda/lib -llapack -lblas -lpthread -lX11 -lm -lcufft -lcublas -lcudart -lcusparse -lcusolver -lcuda -lquadmath -lstdc++ -ldl -lrt
```

It's pretty terse but can be simplified in the Makefile similar to the solution [here](https://codereview.stackexchange.com/questions/161157/avoid-compiler-options-in-makefile-using-nvcc).

Editing the compiler command is simple for the examples but makes compiling the miniapps (e.g. navier) nearly impossible.

**Comment by stefanozampini** [comment]
Or strip out the `rpath` options? Anyway, why MFEM needs `nvcc` for linking executables?

**Comment by stefanozampini** [comment]
Another solution inside MFEM makefiles? (not sure what are the actual names of the variables)

```
NVCCFLAGS := $(addprefix -Xcompiler ,$(CXXFLAGS))
NVCCFLAGS += $(addprefix -Xlinker ,$(LDFLAGS))
```

**Comment by v-dobrev** [comment]
We have not looked in details at the CUDA+PETSc build behavior mainly because we do not support any CUDA capabilities from PETSc.

Unless you build PETSc as a static library, you can probably just link with `-lpetsc`, ignoring any flags read from the `petscvariables` file. For example, try replacing the definition of `PETSC_LIB` in your `config/user.mk` file (which can be created by just copying the file `config/defaults.mk`):
```makefile
PETSC_LIB = $(XLINKER)-rpath,$(abspath $(PETSC_DIR))/lib\
 -L$(abspath $(PETSC_DIR))/lib -lpetsc
```
This should work both with and without CUDA since `XLINKER` is properly set in either case.

**Comment by tzanio** [comment]
@wcdaw, is any of the above workarounds work for you?

**Comment by wcdawn** [comment]
Thanks for following up!

None of these options work directly, but combining them together I figured it out.
I agree with @stefanozampini that `nvcc` isn't really necessary for linking, but this would be a bigger change.

Simply using the `$(XLINKER)` variable will not work. The `-Wl` and `-Xlinker` options use different syntaxes and are not interchangeable. `-Wl` uses comma delimiters whereas `-Xlinker` must proceed each command or argument and is space separated. This variable should probably be removed because it cannot be used as a drop-in replacement.

What did work was removing the `Xlinker` and `rpath` options entirely. If these are necessary for some other use case, then another workaround may be needed. I created a `config/user.mk` as recommended by @v-dobrev and replaced the line to read

```Makefile
PETSC_LIB := -L$(abspath $(PETSC_DIR))/lib -lpetsc $(PETSC_LIB)
```

A similar change should be made for SLEPc.
```Makefile
SLEPC_LIB := -L$(abspath $(SLEPC_DIR))/$(PETSC_ARCH)/lib -lslepc $(SLEPC_LIB)
```

The examples then compile and link as intended. If the `Xlinker` arguments are truly unnecessary, it would be nice if this were changed in `config/defaults.mk` as well.

**Comment by v-dobrev** [comment]
Once again, I'd recommend you try the solution I suggested -- we use the `$(XLINKER)` approach with other libraries and it works fine. See, e.g. https://github.com/mfem/mfem/blob/5457d033d457db5b3543fa47e97b69566baad21e/config/defaults.mk#L355
and https://github.com/mfem/mfem/blob/5457d033d457db5b3543fa47e97b69566baad21e/config/defaults.mk#L360

If you don't include the rpath in the link line, linking will go through fine but you'll have issues at runtime. The shared library loader will not be able to find `libpetsc.so` unless you add the path to it to your `LD_LIBRARY_PATH`, or you install PETSc in a system directory.

Regarding updating the `defaults.mk` file -- yes, we can definitely update it to support more external libraries when building with cuda.

**Comment by wcdawn** [comment]
It seems that the `$(XLINKER)` variable is not set in `defaults.mk`. Using `$(CUDA_XLINKER)` works properly. Alternatively, a block should be included to set `$(XLINKER)`.

```
ifeq ($(MFEM_USE_CUDA),YES)
XLINKER = $(CUDA_XLINKER)
else
XLINKER = $(CXX_XLINKER)
endif
```

Thanks!

**Comment by v-dobrev** [comment]
Just to clarify why using `$(XLINKER)` works  correctly in `user.mk`:

In makefiles, the assignment `VAR = $(XLINKER)...` defines `VAR` as a _recursively expanded variable_ (see https://www.gnu.org/software/make/manual/make.html#Flavors), so the variable `XLINKER` can be defined later. In the MFEM GNU make build system, `XLINKER` is defined in the following sections: https://github.com/mfem/mfem/blob/bba973db7339a99a1a920f27a27cbd4341f907a9/makefile#L218-L235
and, in particular, after `config/user.mk` is included here: https://github.com/mfem/mfem/blob/bba973db7339a99a1a920f27a27cbd4341f907a9/makefile#L156

In particular, this mean that `$(XLINKER)` should not be used in `user.mk` in variables defined with `VAR := ...` (_simply expanded variables_) which are expanded immediately, and since `XLINKER` is not defined, `$(XLINKER)` will be expanded as the empty string.
