### ISSUE TITLE
Best example to start with for time-dependent conduction problem?

### ISSUE THREAD

**Issue by ericman314** [mfem/mfem#1634]
I am new to MFEM. I'm trying to figure out how to create a time-dependent heat simulation with Neumann boundary conditions. My input is a 2D tri-mesh. The initial condition is constant temperature throughout, and then there should be a period of constant non-zero heat flux through the boundary, followed by a period of no heating (insulated boundary).

I've looked at ex16.cpp, since it seemed like it was pretty similar to my problem. I got it to compile and run, and even modified it to add Dirichlet boundary conditions following ex1.cpp. But I can't figure out how to add the Neumann boundary conditions. I also don't need the temperature-dependent conduction coefficient, and I think the problem should be much simpler than what's implemented in ex16.

I'm really impressed by what this library can do. I'm just frustrated because this is one of the simplest problems and I just can't figure out where to start. Thanks in advance.

**Comment by v-dobrev** [comment]
You can take a look at example 27 which illustrates different types of boundary conditions. Specifically, the Neumann b.c. is applied here: https://github.com/mfem/mfem/blob/0effa7abffb019f087ef4a84a9ae0c917c29e6da/examples/ex27.cpp#L243-L244

In a time-dependent setting, if the coefficient `m_nbcCoef` depends on time, the linear form will need to be re-assembled when time changes.

**Comment by ericman314** [comment]
Oh thanks, I didn't see that example before.

How then do we use that in a time-dependent problem? So far, example 16 is the closest I found to what I would like to do. But there is no LinearForm to add the boundary integrator to--that's where I'm getting stuck.

**Comment by vladotomov** [comment]
Hi Eric,

For explicit time integration, the RHS in ex 16 is constructed here:
https://github.com/mfem/mfem/blob/0effa7abffb019f087ef4a84a9ae0c917c29e6da/examples/ex16.cpp#L331-L332
If you create a LinearForm (as in ex 27), you can `Assemble` it and add its contribution to the RHS at that point.

For implicit time integration, if your BC doesn't depend on `u`, you can do the same, but here:
https://github.com/mfem/mfem/blob/0effa7abffb019f087ef4a84a9ae0c917c29e6da/examples/ex16.cpp#L349-L350

Hope this helps,
Vladimir

**Comment by vladotomov** [comment]
Try `z.Add(1.0, n);` or simply `z += n;`

The class `LinearForm` inherits from class `Vector`, thus it can be treated as a `Vector`.

**Comment by ericman314** [comment]
Oh, gotcha! I got it working. Thank you so much!

I'm simulating local heating of a metal part from laser cutting. The results are looking brilliant. Thanks for this terrific software.

![image](https://user-images.githubusercontent.com/6345617/88010841-0c360b00-cad3-11ea-9632-770b435da577.png)
