### ISSUE TITLE
Modifying Euler equations for solving Sod shocktube problem

### ISSUE THREAD

**Issue by sayantan-96** [mfem/mfem#1636]
Hello everyone, I'm quite new to the mfem library. I have been working on solving the sod shocktube problem using Discontinuous Galerkin method. I started off with ex18 and have defined an inline 1D segment mesh for the problem and suitable initial conditions for the density discontinuity.
I wish impose Dirichlet boundary conditions on the two ends. I understood so far I have to make an array of the boundary elements ess_bdr and mark it with 1. Then I tried to add a A.AddBdrFaceIntegrator(new boundaryfaceintegrator(riemansolver, dim), ess_bdr)

I'm stuck at the implementation of the boundaryfaceintegrator. I tried making it similar to the interiorfaceintegrator defined in the example with some changes like Ur=2D-Ul. (D is the Dirichlet boundary values, U are the left and right states) before passing the states to the riemansolver but so far its not working. The state value at the boundaries flare up immediately and the simulation stops after few timesteps which I diagnosed due to the propagation speed becoming zero
![15952263544748332242208045651533](https://user-images.githubusercontent.com/63455348/87906318-0e22ae80-ca80-11ea-8a16-395d85db370c.jpg)

How should I try to fix this problem. I'm still confused how to add boundary conditions to the nonlinear form.

**Comment by vikramsg** [comment]
Yes, your approach makes sense. That is how I would do it, except there are two different boundaries, one on the left and one on the right. The boundary condition for both would be different. 

Make sure you are using the correct boundary conditions as well .

**Comment by tzanio** [comment]
Thanks for responding @vikramsg.

@sayantan-96, feel free to reopen if you have further questions.
