### ISSUE TITLE
System of Diffusion-like Equations (Multigroup Neutron Diffusion)

### ISSUE THREAD

**Issue by wcdawn** [mfem/mfem#1637]
Background
---

I'm working to solve the multigroup neutron diffusion equations.
It is essentially a coupled system of diffusion equations that represents an eigenvalue problem for eigenvalue <img src="https://i.upmath.me/svg/%5Clambda" alt="\lambda" /> and eigenvector <img src="https://i.upmath.me/svg/%5Cphi_g(%5Cmathbf%7Br%7D)" alt="\phi_g(\mathbf{r})" />.

<img src="https://i.upmath.me/svg/%20%5Cnabla%20%5Ccdot%20%5Cleft(%20D_g(%5Cmathbf%7Br%7D)%20%5Cnabla%20%5Cphi_g(%5Cmathbf%7Br%7D)%20%5Cright)%20%2B%20%5CSigma_%7Bt%2Cg%7D(%5Cmathbf%7Br%7D)%20%5Cphi_g(%5Cmathbf%7Br%7D)%20%3D%20%5Cfrac%7B%5Cchi_g(%5Cmathbf%7Br%7D)%7D%7B%5Clambda%7D%20%20%5Csum_%7Bg'%3D1%7D%5E%7BG%7D%20%5Cnu%20%5CSigma_%7Bf%2Cg'%7D(%5Cmathbf%7Br%7D)%20%5Cphi_%7Bg'%7D(%5Cmathbf%7Br%7D)%20%2B%20%5Csum_%7Bg'%3D1%7D%5E%7BG%7D%20%5CSigma_%7Bs%2C%20g'%20%5Crightarrow%20g%7D(%5Cmathbf%7Br%7D)%20%5Cphi_%7Bg'%7D(%5Cmathbf%7Br%7D)%20%5Cquad%20%5Ctext%7Bfor%20%7D%20g%20%3D%201%2C2%2C3%2C%20%5Cldots%2C%20G" alt=" \nabla \cdot \left( D_g(\mathbf{r}) \nabla \phi_g(\mathbf{r}) \right) + \Sigma_{t,g}(\mathbf{r}) \phi_g(\mathbf{r}) = \frac{\chi_g(\mathbf{r})}{\lambda}  \sum_{g'=1}^{G} \nu \Sigma_{f,g'}(\mathbf{r}) \phi_{g'}(\mathbf{r}) + \sum_{g'=1}^{G} \Sigma_{s, g' \rightarrow g}(\mathbf{r}) \phi_{g'}(\mathbf{r}) \quad \text{for } g = 1,2,3, \ldots, G" />

This system can be rewritten as a generalized eigenvalue problem.

<img src="https://i.upmath.me/svg/%20%5Cmathbf%7BA%7D%20%5CPhi%20%3D%20%5Cfrac%7B1%7D%7B%5Clambda%7D%20%5Cmathbf%7BM%7D" alt=" \mathbf{A} \Phi = \frac{1}{\lambda} \mathbf{M}" />

I am only interested in the eigenmode with largest eigenvalue <img src="https://i.upmath.me/svg/%5Clambda" alt="\lambda" />. It has been shown elsewhere that the most efficient and robust solution method for this class of equations is the Generalized Davidson eigensolver and I'm currently using the implementation in SLEPc (for a one-group, <img src="https://i.upmath.me/svg/G%3D1" alt="G=1" />, problem). A Power Iteration algorithm has been simple to implement for the multigroup problem (<img src="https://i.upmath.me/svg/G%5Cge1" alt="G\ge1" />) but the method itself is rather inefficient.

Problem
---

The <img src="https://i.upmath.me/svg/%5Cmathbf%7BA%7D" alt="\mathbf{A}" /> and <img src="https://i.upmath.me/svg/%5Cmathbf%7BM%7D" alt="\mathbf{M}" /> matrices from above have dimensions <img src="https://i.upmath.me/svg/%5Cmathbf%7BA%7D%2C%20%5Cmathbf%7BM%7D%20%5Cin%20%5Cmathbb%7BR%7D%5E%7BNG%20%5Ctimes%20NG%7D" alt="\mathbf{A}, \mathbf{M} \in \mathbb{R}^{NG \times NG}" /> where <img src="https://i.upmath.me/svg/N" alt="N" /> is the DOF of the mesh and <img src="https://i.upmath.me/svg/G" alt="G" /> is the total number of energy groups. Essentially, each grid position has <img src="https://i.upmath.me/svg/G" alt="G" /> functions associated with it.

To minimize bandwidth, it is favorable to arrange the matrix so that the matrix index is <img src="https://i.upmath.me/svg/i%3Dg%20%2B%20Gn" alt="i=g + Gn" /> where <img src="https://i.upmath.me/svg/n" alt="n" /> is the index for the original DOF (as possible by `Ordering::byVDIM`). This seemed like a great candidate for the `Vector*` classes (e.g. `VectorCoefficient`, `VectorMassIntegrator`, etc.) in MFEM as there is a vector of functions associated with each grid location. However, this did not seem to work as I imagined, particularly the `VectorDiffusionIntegrator`.

It seems it may be possible to write my own `BilinearIntegrator` but I would like to leverage the existing code if possible. Especially as this will be scaling to very large supercomputers.

How should I go about building these <img src="https://i.upmath.me/svg/%5Cmathbf%7BA%7D" alt="\mathbf{A}" /> and <img src="https://i.upmath.me/svg/%5Cmathbf%7BM%7D" alt="\mathbf{M}" /> matrices in MFEM?

Thank you in advance!

**Comment by vladotomov** [comment]
Hi @wcdawn,

MFEM has been used to solve similar problems, although we don't have any public examples about them. You're right that our `FiniteElementSpace` supports `Ordering::byVDIM`. If you assemble a `SparseMatrix` from a `BilinearForm` that uses such space, then this matrix would be consistent with the `Ordering::byVDIM`. However, most `Assemble` functions of the integrators, assume that the local vectors are extracted in `Ordering::byNODES`.

For what operations do you need `Ordering::byVDIM`? Is it needed only on the linear algebra level, or for the local operations as well (in the integrators)? Are you looking at standard (eg obtaining `SparseMatrix`) assembly or partial assembly? What finite element spaces are you planning to use? One can certainly define a version of an integrator that uses local `byVDIM` vectors, but will have to be careful with standard operations like dot and matrix products.

**Comment by wcdawn** [comment]
Thanks for the response!

I think part of the problem is I need to eventually access a `PETSC_MATAIJ` matrix to pass to the SLEPc eigensolvers. If I could work with `SparseMatrix` directly, I could (at least for prototyping) reorder the matrix myself using things like `GetRow` and `SetRow`.

To answer your questions:
- We want `Ordering::byVDIM` to reduce the bandwidth of the matrices. We want all energy groups at a particular position stored near each other. So yes, it is only needed on the linear algebra level.
- Standard assembly is fine for now. But we do need to be able to obtain a `PETSC_MATAIJ` matrix which (to my understanding) means calling `ParallelAssemble()` at some point.
- We're only interested in FE spaces using linear and curvilinear elements with polynomial basis functions of arbitrary order. I think this is an H_1 space but maybe L_2. My FEM is a bit rusty.

A pseudo-code version that currently works for G=1 follows.
```cpp
ParBilinearForm a{fespace}, m{fespace};
// populate a & m using PWConstCoefficient, MassIntegrator, and DiffusionIntegrator
a.Assemble();
m.Assemble();
// apply boundary conditions
a.Finalize();
m.Finalize();
SlepcEigenSolver slepc{MPI_COMM_WORLD};
// slepc settings
PetscParMatrix* A{nullptr}, M{nullptr};

OperatorHandle Ah{Operator::PETSC_MATAIJ}, Mh(Operator::PETSC_MATAIJ};
a.ParallelAssemble(Ah);
Ah.Get(A);
Ah.SetOperatorOwner(false);
m.ParallelAssemble(Mh);
Mh.Get(M);
Mh.SetOperatorOwner(false);
slepc.SetOperators(*A,*M);
slepc.Solve();

```

Thanks again!

**Comment by vladotomov** [comment]
If `fespace` is with G components and has `Ordering::byVDIM`, then I believe that the result of `a.Assemble` and `m.Assemble` should be what you want. I would expect that the conversion to `PetscParMatrix` would still respect that ordering, but @stefanozampini is the person to verify this.

**Comment by jandrej** [comment]
The conversion to PETSc does not change ordering. All of the hypre data gets wrapped in a MAT_HYPRE in PETSC.

**Comment by wcdawn** [comment]
I have updated the `fespace` to have the proper dimensions.
```cpp
ParFiniteElementSpace fespace{&pmesh, fec, G, Ordering::byVDIM};
```

I can use `VectorConstantCoefficient` and `VectorMassIntegrator` to handle most of the terms (I think). I may need a `MatrixCoefficient` but `VectorMassIntegrator` can handle this as well.

I'm still confused about how to handle the diffusion term. `VectorDiffusionIntegrator` cannot be constructed with a `VectorCoefficient`. For each equation g=1...G, the coefficient for the diffusion term is different. Is there a different integrator I should use?

**Comment by mlstowell** [comment]
Hi, @wcdawn,

It may be worth pointing out that BilinearForm integrators compute a single dense matrix for each element of the mesh.  If you have isotropic multi-species diffusion with no coupling between species then your diffusion coefficient can indeed be viewed as a vector of scalar diffusion coefficients.  However, in this case the dense matrix computed by the integrator will contain zeros in all of the off-diagonal blocks corresponding to the non-existent couplings.  It would actually be more efficient to compute the diagonal blocks of this operator separately using something like `DiffusionIntegrator` with each scalar diffusion coefficient in turn.  This could be done using separate `BilinearForm` objects and then combine the operators using a `BlockOperator` or it could be done by implementing a custom `VectorDiffusionIntegrator` which calls `DiffusionIntegrator` multiple times and copies the results into a larger dense matrix leaving the off-diagonal blocks set to zero.

Best wishes,
Mark

**Comment by wcdawn** [comment]
I really and truly appreciate the help, but I'm more confused now than ever.

I've setup what I think should work but it doesn't seem to do what I think it should.
The system of equations is rewritten.

<img src="https://i.upmath.me/svg/%20%5Cnabla%20%5Ccdot%20%5Cleft(%20%5Cmathbf%7BD%7D%20%5Cnabla%20%5CPhi(%5Cmathbf%7Br%7D)%20%5Cright)%20%2B%20%5Cmathbf%7BR%7D%20%5CPhi(%5Cmathbf%7Br%7D)%20%3D%20%5Cfrac%7B1%7D%7B%5Clambda%7D%20%5Cmathbf%7BF%7D%20%5CPhi(%5Cmathbf%7Br%7D)%20" alt=" \nabla \cdot \left( \mathbf{D} \nabla \Phi(\mathbf{r}) \right) + \mathbf{R} \Phi(\mathbf{r}) = \frac{1}{\lambda} \mathbf{F} \Phi(\mathbf{r}) " />

Where <img src="https://i.upmath.me/svg/%5Cmathbf%7BD%7D" alt="\mathbf{D}" />, <img src="https://i.upmath.me/svg/%5Cmathbf%7BR%7D" alt="\mathbf{R}" />, and <img src="https://i.upmath.me/svg/%5Cmathbf%7BF%7D%20%5Cin%20%5Cmathbb%7BR%7D%5E%7BG%20%5Ctimes%20G%7D" alt="\mathbf{F} \in \mathbb{R}^{G \times G}" /> and <img src="https://i.upmath.me/svg/%5CPhi(%5Cmathbf%7Br%7D)" alt="\Phi(\mathbf{r})" /> is a vector of functions with length <img src="https://i.upmath.me/svg/G" alt="G" />. <img src="https://i.upmath.me/svg/%5Cmathbf%7BD%7D" alt="\mathbf{D}" /> is a diagonal matrix of diffusion coefficients. <img src="https://i.upmath.me/svg/%5Cmathbf%7BR%7D" alt="\mathbf{R}" /> and <img src="https://i.upmath.me/svg/%5Cmathbf%7BF%7D" alt="\mathbf{F}" /> will be mostly sparse but will have off-diagonal entries. I can provide more detail about the population of the matrices if it would be helpful.

For testing, I'm working on a problem where <img src="https://i.upmath.me/svg/%5Cmathbf%7BD%7D" alt="\mathbf{D}" />, <img src="https://i.upmath.me/svg/%5Cmathbf%7BR%7D" alt="\mathbf{R}" />, and <img src="https://i.upmath.me/svg/%5Cmathbf%7BF%7D" alt="\mathbf{F}" /> are constant (not spatially dependent). I have setup these as `MatrixConstantCoefficient`. I have setup `Ordering::byVDIM` so I think that the <img src="https://i.upmath.me/svg/g%3D1%20%5Cldots%20G" alt="g=1 \ldots G" /> indexing in the matrix coefficients should correspond to the appropriate elements in the <img src="https://i.upmath.me/svg/%5CPhi(%5Cmathbf%7Br%7D)" alt="\Phi(\mathbf{r})" /> vector.

I perform the bilinear integration using `DiffusionIntegrator` (which does support `MatrixCoefficient`) and `MassIntegrator`. The linear system works for <img src="https://i.upmath.me/svg/G%3D1" alt="G=1" /> but fails for <img src="https://i.upmath.me/svg/G%20%3E%201" alt="G &gt; 1" />.

Am I using the coefficients and integrators properly here? Does @vladotomov comment imply that integrators cannot be used with a `fespace` that has `Ordering::byVDIM`?

I think I understand the comment from @mstowell and it should be useful for eliminating multiply-by-zero operations. Unfortunately, I cannot get the code to work with dense matrix math yet so optimization is currently "Future Work."

**Comment by vladotomov** [comment]
> Does @vladotomov comment imply that integrators cannot be used with a `fespace` that has `Ordering::byVDIM`?

It doesn't imply this. It means that if you write your own integrator, the local `Vector` that is received as input, is ordered `byNODES`. But since you're using the built-in integrators, you should not worry about this.

What do you mean by "fails"? Does something segfault, or doesn't the solver converge?

I would try to decouple the groups, and get the same solution for all groups, as the solution obtained for G=1 (since that's known to be correct).

**Comment by stefanozampini** [comment]
@wcdawn You cannot use `DiffusionIntegrator`, since it works for scalar problems only https://github.com/mfem/mfem/blob/master/fem/bilininteg.cpp#L504. Likewise, I also think you cannot use `VectorDiffusionIntegrator` https://github.com/mfem/mfem/blob/master/fem/bilininteg.cpp#L2166 as I presume it assumes a `Vector` dimension equal to the geometrical dimension, https://github.com/mfem/mfem/blob/master/fem/bilininteg.cpp#L2214
With that said,  I guess you can extend the `VectorDiffusionIntegrator` by working as you wish,  by computing the `Vector` dimension (your G) out of the size of the coefficient matrix and the spatial dimension of the finite element.
However, note that you need to code up support for matrix coefficients since the `VectorDiffusionIntegrator` now works for constant coefficients only.

**Comment by wcdawn** [comment]
My use of "fails" was definitely not clear. The problem solves for some meshes but the matrices are assembled incorrectly. When the solver does converge, the matrix is wrong as boundary conditions are not enforced and the result is not "smooth" though material properties are constant. Refining the mesh for a problem that does converge, causes the problem to not converge. It just seems wrong.

I don't know about decoupling the groups. They're inherently coupled through the **R** and **F** matrix coefficients (above). Also, there is a single eigenvalue for the system described by all of these groups so I'm not sure how the result could be interpreted.

I went ahead and used `BlockOperator` to assemble the matrices myself, essentially in the `Ordering::byNODES` order. I populated the `BlockOperator` using `SparseMatrix` generated from different bilinear forms. The code works and gives the right answer. Sparsity plots below. This is a G=2, N=36 problem. As you can see, this has bandwidth approximately equal to N*G.
<img src="https://user-images.githubusercontent.com/20099247/88863827-fc987f80-d1c0-11ea-8c80-dd91bb5fd2b9.png" width=400 /> <img src="https://user-images.githubusercontent.com/20099247/88863829-fdc9ac80-d1c0-11ea-9ab9-b3c01bdbb535.png" width=400 />

I'm still interested in implementing a `Vector` implementation.

**Comment by wcdawn** [comment]
@stefanozampini It would seem you're right. `VectorDiffusionIntegrator` does seem to use the spatial dimension instead of the dimension of the vector FE space from some preliminary results.

For your second point, my understanding is that `VectorDiffusionIntegrator` currently returns (space_dim*local_dof) matrix but I will need to make it return (vector_dim*local_dof) matrix. Is this correct?

Yes, I will also need to add support for `MatrixCoefficient`. I may be able to get by with only `VectorCoefficient` but if I'm adding one, I could pretty easily add both.

**Comment by v-dobrev** [comment]
Hi @wcdawn,

Currently, `VectorDiffusionIntegrator` only supports a scalar coefficient, however, it is definitely possible to extend it to support vector coefficients with any number of components.

The vector dimension of the FE space is typically not directly known in the integrators because they only get the `FiniteElement` object and not the whole FE space. For that reason, for the `VectorMassIntegrator` we have different ways of informing the integrator about the vector dimension: 1) by using a `VectorCoefficient` from which we can extract its vector dimension using `VectorCoefficient::GetVDim()`; 2) by using a `MatrixCoefficient` and its method `MatrixCoefficient::GetVDim()`; or 3) when using a scalar coefficient, we can set the vector dimension explicitly by calling `VectorMassIntegrator::SetVDim(int)`. The same approach can be used with the `VectorDiffusionIntegrator` class.

> For your second point, my understanding is that VectorDiffusionIntegrator currently returns (space_dimlocal_dof) matrix but I will need to make it return (vector_dimlocal_dof) matrix. Is this correct?

Yes, the expected result is `(vdim * num_local_dofs) x (vdim * num_local_dofs)` (`vdim` is the vector dimension of the FE space) where the matrix is locally ordered `byNODES`, i.e. it is `vdim x vdim` block matrix where each block is `num_local_dofs x num_local_dofs`.

Let us know if you need help with extending the `VectorDiffusionIntegrator` for the vector and/or matrix coefficient cases.

If you are interested in contributing this addition to MFEM, let me know and I can add you to the `Collaborators` team, so that you can create your branch directly in the MFEM repo.

**Comment by wcdawn** [comment]
@v-dobrev Thank you for your explanation.
I am interested in adding support for `VectorCoefficient` and `MatrixCoefficient` for `VectorDiffusionIntegrator` and I have enough info to get started using your explanation.

Either being added to `Collaborators` and making a branch in MFEM or working from a fork. Whichever works best for your workflow.

**Comment by v-dobrev** [comment]
@wcdawn, I added you to the Collaborators team, so now you should be able to create your branch in the mfem repo -- let me know if you run into any issues. We typically prefer this over merging from forks -- it is a bit easier for us to make small adjustments.

**Comment by vladotomov** [comment]
@wcdawn, `VectorDiffusionIntegrator::AssembleElementMatrix` performs the local action of the `VectorDiffusionIntegrator`. It is used, for example, when an integrator is added to a `NonLinearForm`, in which case there is no global `SparseMatrix`, but only the local actions are computed.

**Comment by wcdawn** [comment]
@vladotomov I assume you meant `AssembleElementVector`.

I'm still confused because the currently implemented routine for `VectorDiffusionIntegrator` reassigns the memory of the input and output vectors to a set of `dim*dof` matrices. Also, the `BilinearForm::AssembleElementVector` is only implemented for `DiffusionIntegrator` and `VectorDiffusionIntegrator` but it is called in none of the unit tests, examples, or minapps. I'm not sure how to implement it and there are no tests that I can use.

I'm going to open the Pull Request and the discussion can probably be moved there.

**Comment by vladotomov** [comment]
Yes I meant `AssembleElementVector`.

The `dim*dof` matrices are just a different representation of the input / output `Vectors`, so that it's easier to do operations with the components.

`BilinearForm::AssembleElementVector` is used in one of our internal applications, but you're right, MFEM does not contain examples or tests for them. If you have a PR, that would be a good place to add unit tests.
