### ISSUE TITLE
Creating a user-defined "matvec" preconditioner for CGSolver in MFEM

### ISSUE THREAD

**Issue by kvoronin** [mfem/mfem#164]
Hello,

What is the right way to use a user-defined preconditioner for, say, CGSolver in MFEM?

For the preconditioner I'd like to input something like matvec routine which computes the action of the preconditioner on a vector. The preconditioner will not be available as a matrix.
The idea is to use an external direct solver with approximate factorization as a preconditioner, so I thought about using the solve() function for this external direct solver as a preconditioner matvec function.
In documentation I see that a preconditioner should be defined as a Solver object. Should I proceed and use a class for Petsc preconditioners? As far as I remember, user-defined preconditioners are allowed in Petsc, but maybe there is an easier way.

Thanks,
Kirill

**Comment by tzanio** [comment]
Hi Kirill,

In principle any `Operator` can be a preconditioner. You can derive a class with whatever data you need, and all you have to do is implement the `Mult` method. If your preconditioner depends can be setup for a variety of input operators and/or supports iterations, a more appropriate class to derive from will be `Solver`.

This class can be as simple as `IdentityOperator` https://github.com/mfem/mfem/blob/master/linalg/operator.hpp#L280, or `BlockDiagonalPreconditioner` https://github.com/mfem/mfem/blob/master/linalg/blockoperator.hpp#L135

Hope this helps,
Tzanio

**Comment by kvoronin** [comment]
Thanks, @tzanio, now I got it!

Another question - how to get usual CSR format arrays  (ia, ja, values) from a HypreParMatrix object?

Thanks,
Kirill

**Comment by tzanio** [comment]
`HypreParMatrix` is just a wrapped for _hypre_'s `ParCSR` structure, which defined two CSR matrices per processor: a diagonal one, `diag` (rows and cols owned by the processor) and an off-diagonal one, `offd` (rows owned by the processor, cols owned by other processors).

You can get these with the `GetDiag()` and `GetOffd()` methods.

**Comment by tzanio** [comment]
Hi Kiril, were you able to resolve this issue?

**Comment by kvoronin** [comment]
Hi @tzanio,
Thanks for your clarifications! Actually I freezed the code for some time, but the converter between matrix formats should not be complicated.
