### ISSUE TITLE
How to unsubscribe?

### ISSUE THREAD

**Issue by BobObara** [mfem/mfem#1643]
Hi, I've unsubscribed from the project's GitHub (in fact it says I'm unsubscribed to the different threads) but I am still getting emails.  How do I stop receiving emails?

Thanks in advance!
Bob

**Comment by tzanio** [comment]
Hi Bob,

I am sorry you are receiving mfem emails that you are not interested in. This is certainly not our intention, and I don't believe we have done anything on our end to cause this.

Do you see any mfem repositories on this page: https://github.com/watching? You should be able to "unwatch" them if you do.

You may also want to check https://github.com/notifications/subscriptions. 

Hope this helps,
Tzanio

**Comment by BobObara** [comment]
Thanks so much - that was what I was missing!
