### ISSUE TITLE
Norm2 of right-hand-side gives NAN after parallel adaptive mesh refinement

### ISSUE THREAD

**Issue by hongbo-yao** [mfem/mfem#1654]
Hi dear developers,

I'm trying to solve a complex-valued problem which reads the form:
Curl Curl A + i*beta*A = J,  results in right-hand-side (real part)d_r= \iiint_{\Omega} \mathbf{N} \cdot \mathbf{J} dv, (imag part)d_i=0.  \mathbf{J} is non-zero J=[1,1,1]  only in some elements that should be found in the code.

Since J is not easy to be written as a coordinate function, I assemble the right-hand-side by myself  through:
`ParSesquilinearForm* a;
ParComplexGridFunction* x;

ParComplexLinearForm* d;
d = new ParComplexLinearForm(pfes, ComplexOperator::BLOCK_SYMMETRIC);
d->Vector::operator=(0.0);
// Loop all Tet elements and find that J is not zero
int tet_id = Tet id which J is not zero
const FiniteElement* fe = pfes->GetFE(tet_id);
const IntegrationRule* ir = &IntRules.Get(fe->GetGeomType(), 2*fe->GetOrder());
ElementTransformation* eltrans = pfes->GetElementTransformation(tet_id);

const int ndof = fe->GetDof();
const int dim = fe->GetDim();
DenseMatrix shape(ndof, dim);
Vector elemvect(ndof);
elemvect = 0.0;
for (int q=0; q<ir->GetNPoints(); ++q) 
{
   const IntegrationPoint& ip = ir->IntPoint(q);
   eltrans->SetIntPoint(&ip);
   double WJ = eltrans->Weight()*ip.weight;
   fe->CalcPhysVShape(*eltrans, shape);
   for (int l=0; l<ndof; l++) // loop all dofs
   {
      elemvect[l] += WJ*(shape(l,0)*1.0+shape(l,1)*1.0+shape(l,2)*1.0);
   }
}

// assemble
Array<int> vdofs;
pfes->GetElementVDofs(tet_id, vdofs);
d->real().AddElementVector(vdofs, elemvect);`

After solving the linear system ax=d, I call
`pfes->Update();
x->Update();
a->Update();
d->Update();`

Then I refine the mesh, assemble and solve again. The problem comes:
(1) when run in one processor, the value of d->Norm2() is normal;
(2) when run in parallel, e.g., 6 processors, the value of d->Norm2() for some processors is NAN or 1.98193e-307

Is this caused by the pmesh refinement process? or caused by the above assemble process?

Thanks,
Sincerely,
Hongbo

**Comment by psocratis** [comment]
Hi @hongbo-yao , can you share the whole file so that I can try to reproduce the issue? 

Thanks.

**Comment by hongbo-yao** [comment]
Hi @psocratis,

Thank you for your quick reply and help.

The cpp code and corresponding attached data are given as follows:

[ex22p.cpp.txt](https://github.com/mfem/mfem/files/4970342/ex22p.cpp.txt)
[Jpoint.dat.txt](https://github.com/mfem/mfem/files/4970343/Jpoint.dat.txt)
[tets.msh.txt](https://github.com/mfem/mfem/files/4970344/tets.msh.txt)

Please run this code with:
(1) delete .txt of these files's name;
(2) move this files into mfem's examples  path (may cover the original ex22p.cpp);
(3) make ex22p, then
(4.1) mpirun -np 1 ex22p, the results are normal;
(4.2) mpirun -np 4 ex22p, you should see NAN outputs (This happened in my test)

By the way, my installed mfem is just the master version updated on 2020-07-23;
openmpi-2.1.6, hypre-2.16.0, and metis-4.0.3.

Best wishes,
Hongbo

**Comment by psocratis** [comment]
Hi @hongbo-yao , thanks for sharing the files. 

Unfortunately I can't reproduce the issue. Here is what I get

```mpirun -np 4 test_ex22p

************** Loop 1 **************
myid = 3, b->Norml2()= 0
myid = 2, b->Norml2()= 0
myid = 0, b->Norml2()= 3.42887e+11
myid = 1, b->Norml2()= 3.22237e+11
Number of finite element unknowns: 319141
   Pass :  1   Iteration :   0  || r || = 4.76208e+11
   Pass :  1   Iteration :   1  || r || = 4.76208e+11
   Pass :  1   Iteration :   2  || r || = 2.94529e+10
   Pass :  1   Iteration :   3  || r || = 2.94529e+10
   Pass :  1   Iteration :   4  || r || = 5.61842e+09
   Pass :  1   Iteration :   5  || r || = 5.61842e+09
   Pass :  1   Iteration :   6  || r || = 8.74737e+08
   Pass :  1   Iteration :   7  || r || = 8.74737e+08
   Pass :  1   Iteration :   8  || r || = 1.24577e+08
   Pass :  1   Iteration :   9  || r || = 1.24577e+08
   Pass :  1   Iteration :  10  || r || = 2.6763e+07
   Pass :  1   Iteration :  11  || r || = 2.6763e+07
   Pass :  1   Iteration :  12  || r || = 5.10795e+06
   Pass :  1   Iteration :  13  || r || = 5.10795e+06
   Pass :  1   Iteration :  14  || r || = 735695
   Pass :  1   Iteration :  15  || r || = 735695
   Pass :  1   Iteration :  16  || r || = 126760

************** Loop 2 **************
myid = 3, b->Norml2()= 0
myid = 2, b->Norml2()= 0
myid = 1, b->Norml2()= 8.0851e+11
myid = 0, b->Norml2()= 1.00313e+12
Number of finite element unknowns: 347557
   Pass :  1   Iteration :   0  || r || = 1.39036e+12
   Pass :  1   Iteration :   1  || r || = 1.39036e+12
   Pass :  1   Iteration :   2  || r || = 1.65699e+11
   Pass :  1   Iteration :   3  || r || = 1.65699e+11
   Pass :  1   Iteration :   4  || r || = 3.1835e+10
   Pass :  1   Iteration :   5  || r || = 3.1835e+10
   Pass :  1   Iteration :   6  || r || = 6.89261e+09
   Pass :  1   Iteration :   7  || r || = 6.89261e+09
   Pass :  1   Iteration :   8  || r || = 1.62747e+09
   Pass :  1   Iteration :   9  || r || = 1.62747e+09
   Pass :  1   Iteration :  10  || r || = 3.65791e+08
   Pass :  1   Iteration :  11  || r || = 3.65791e+08
   Pass :  1   Iteration :  12  || r || = 8.46584e+07
   Pass :  1   Iteration :  13  || r || = 8.46584e+07
   Pass :  1   Iteration :  14  || r || = 1.93075e+07
   Pass :  1   Iteration :  15  || r || = 1.93075e+07
   Pass :  1   Iteration :  16  || r || = 4.20498e+06
   Pass :  1   Iteration :  17  || r || = 4.20498e+06
   Pass :  1   Iteration :  18  || r || = 852532

************** Loop 3 **************
myid = 2, b->Norml2()= 0
myid = 0, b->Norml2()= 4.26168e+09
myid = 3, b->Norml2()= 216.48
myid = 1, b->Norml2()= 3.62075e+09
Number of finite element unknowns: 366240
   Pass :  1   Iteration :   0  || r || = 5.59212e+09
   Pass :  1   Iteration :   1  || r || = 5.59212e+09
   Pass :  1   Iteration :   2  || r || = 2.42315e+08
   Pass :  1   Iteration :   3  || r || = 2.42314e+08
   Pass :  1   Iteration :   4  || r || = 4.42889e+07
   Pass :  1   Iteration :   5  || r || = 4.42888e+07
   Pass :  1   Iteration :   6  || r || = 8.10813e+06
   Pass :  1   Iteration :   7  || r || = 8.10812e+06
   Pass :  1   Iteration :   8  || r || = 1.44147e+06
   Pass :  1   Iteration :   9  || r || = 1.44147e+06
   Pass :  1   Iteration :  10  || r || = 295118
   Pass :  1   Iteration :  11  || r || = 295118
   Pass :  1   Iteration :  12  || r || = 56811.4
   Pass :  1   Iteration :  13  || r || = 56811.3
   Pass :  1   Iteration :  14  || r || = 13055.3
   Pass :  1   Iteration :  15  || r || = 13055.3
   Pass :  1   Iteration :  16  || r || = 2971.74
````

Can you make sure you do a library clean and a fresh compilation? Can you post the failing output you are getting? 

Thanks, 

Socratis

**Comment by hongbo-yao** [comment]
Hi @psocratis ,
I have recompiled mfem, metis, hypre and I have also tested this on my the other computer.
Firstly, I have to state that this issue is random! can you run mpirun -np 4 ex22p several more times?

The following are my tests:
(1) Ubuntu18.04, compiled with: make parallel -j (In this case, the issue is random, sometimes I got right results)
************** Loop 1 **************
myid = 1, b->Norml2()= 1.38287e+11
myid = 2, b->Norml2()= 0
myid = 3, b->Norml2()= 0
myid = 0, b->Norml2()= 4.54761e+11
Number of finite element unknowns: 319141
   Pass :  1   Iteration :   0  || r || = 4.76208e+11
   Pass :  1   Iteration :   1  || r || = 4.76208e+11
   Pass :  1   Iteration :   2  || r || = 1.53457e+10
   Pass :  1   Iteration :   3  || r || = 1.53457e+10
   Pass :  1   Iteration :   4  || r || = 2.33118e+09
   Pass :  1   Iteration :   5  || r || = 2.33118e+09
   Pass :  1   Iteration :   6  || r || = 3.02166e+08
   Pass :  1   Iteration :   7  || r || = 3.02166e+08
   Pass :  1   Iteration :   8  || r || = 3.61881e+07
   Pass :  1   Iteration :   9  || r || = 3.61881e+07
   Pass :  1   Iteration :  10  || r || = 5.86033e+06
   Pass :  1   Iteration :  11  || r || = 5.86033e+06
   Pass :  1   Iteration :  12  || r || = 719653
   Pass :  1   Iteration :  13  || r || = 719653
   Pass :  1   Iteration :  14  || r || = 129526

************** Loop 2 **************
myid = 3, b->Norml2()= 0
myid = 2, b->Norml2()= 0
myid = 1, b->Norml2()= -nan
myid = 0, b->Norml2()= 3.03334e+10
Number of finite element unknowns: 347557
   Pass :  1   Iteration :   0  || r || = -nan
   Pass :  1   Iteration :   1  || r || = nan
   Pass :  1   Iteration :   2  || r || = nan
   Pass :  1   Iteration :   3  || r || = nan
   Pass :  1   Iteration :   4  || r || = nan
   Pass :  1   Iteration :   5  || r || = nan
   Pass :  1   Iteration :   6  || r || = nan
   Pass :  1   Iteration :   7  || r || = nan
   Pass :  1   Iteration :   8  || r || = nan
   Pass :  1   Iteration :   9  || r || = nan
   Pass :  1   Iteration :  10  || r || = nan
   Pass :  1   Iteration :  11  || r || = nan
   Pass :  1   Iteration :  12  || r || = nan
   Pass :  1   Iteration :  13  || r || = nan
   Pass :  1   Iteration :  14  || r || = nan
   Pass :  1   Iteration :  15  || r || = nan
   Pass :  1   Iteration :  16  || r || = nan
   Pass :  1   Iteration :  17  || r || = nan
   Pass :  1   Iteration :  18  || r || = nan
   Pass :  1   Iteration :  19  || r || = nan
   Pass :  1   Iteration :  20  || r || = nan
   Pass :  1   Iteration :  21  || r || = nan
   Pass :  1   Iteration :  22  || r || = nan
   Pass :  1   Iteration :  23  || r || = nan
   Pass :  1   Iteration :  24  || r || = nan
   Pass :  1   Iteration :  25  || r || = nan
   Pass :  1   Iteration :  26  || r || = nan
   Pass :  1   Iteration :  27  || r || = nan
   Pass :  1   Iteration :  28  || r || = nan
   Pass :  1   Iteration :  29  || r || = nan
   Pass :  1   Iteration :  30  || r || = nan
   Pass :  1   Iteration :  31  || r || = nan
   Pass :  1   Iteration :  32  || r || = nan
   Pass :  1   Iteration :  33  || r || = nan
   Pass :  1   Iteration :  34  || r || = nan
   Pass :  1   Iteration :  35  || r || = nan
   Pass :  1   Iteration :  36  || r || = nan
   Pass :  1   Iteration :  37  || r || = nan
   Pass :  1   Iteration :  38  || r || = nan
   Pass :  1   Iteration :  39  || r || = nan
   Pass :  1   Iteration :  40  || r || = nan
   Pass :  1   Iteration :  41  || r || = nan
   Pass :  1   Iteration :  42  || r || = nan
   Pass :  1   Iteration :  43  || r || = nan
   Pass :  1   Iteration :  44  || r || = nan
   Pass :  1   Iteration :  45  || r || = nan
   Pass :  1   Iteration :  46  || r || = nan
   Pass :  1   Iteration :  47  || r || = nan
   Pass :  1   Iteration :  48  || r || = nan
   Pass :  1   Iteration :  49  || r || = nan
   Pass :  1   Iteration :  50  || r || = nan
Restarting...
FGMRES: No convergence!

************** Loop 3 **************
myid = 3, b->Norml2()= 0
myid = 2, b->Norml2()= -nan
myid = 1, b->Norml2()= 1.57858e+09
myid = 0, b->Norml2()= 5.36469e+09
Number of finite element unknowns: 366240
   Pass :  1   Iteration :   0  || r || = -nan
   Pass :  1   Iteration :   1  || r || = nan
   Pass :  1   Iteration :   2  || r || = nan
   Pass :  1   Iteration :   3  || r || = nan
   Pass :  1   Iteration :   4  || r || = nan
   Pass :  1   Iteration :   5  || r || = nan
   Pass :  1   Iteration :   6  || r || = nan
   Pass :  1   Iteration :   7  || r || = nan
   Pass :  1   Iteration :   8  || r || = nan
   Pass :  1   Iteration :   9  || r || = nan
   Pass :  1   Iteration :  10  || r || = nan
   Pass :  1   Iteration :  11  || r || = nan
   Pass :  1   Iteration :  12  || r || = nan
   Pass :  1   Iteration :  13  || r || = nan
   Pass :  1   Iteration :  14  || r || = nan
   Pass :  1   Iteration :  15  || r || = nan
   Pass :  1   Iteration :  16  || r || = nan
   Pass :  1   Iteration :  17  || r || = nan
   Pass :  1   Iteration :  18  || r || = nan
   Pass :  1   Iteration :  19  || r || = nan
   Pass :  1   Iteration :  20  || r || = nan
   Pass :  1   Iteration :  21  || r || = nan
   Pass :  1   Iteration :  22  || r || = nan
   Pass :  1   Iteration :  23  || r || = nan
   Pass :  1   Iteration :  24  || r || = nan
   Pass :  1   Iteration :  25  || r || = nan
   Pass :  1   Iteration :  26  || r || = nan
   Pass :  1   Iteration :  27  || r || = nan
   Pass :  1   Iteration :  28  || r || = nan
   Pass :  1   Iteration :  29  || r || = nan
   Pass :  1   Iteration :  30  || r || = nan
   Pass :  1   Iteration :  31  || r || = nan
   Pass :  1   Iteration :  32  || r || = nan
   Pass :  1   Iteration :  33  || r || = nan
   Pass :  1   Iteration :  34  || r || = nan
   Pass :  1   Iteration :  35  || r || = nan
   Pass :  1   Iteration :  36  || r || = nan
   Pass :  1   Iteration :  37  || r || = nan
   Pass :  1   Iteration :  38  || r || = nan
   Pass :  1   Iteration :  39  || r || = nan
   Pass :  1   Iteration :  40  || r || = nan
   Pass :  1   Iteration :  41  || r || = nan
   Pass :  1   Iteration :  42  || r || = nan
   Pass :  1   Iteration :  43  || r || = nan
   Pass :  1   Iteration :  44  || r || = nan
   Pass :  1   Iteration :  45  || r || = nan
   Pass :  1   Iteration :  46  || r || = nan
   Pass :  1   Iteration :  47  || r || = nan
   Pass :  1   Iteration :  48  || r || = nan
   Pass :  1   Iteration :  49  || r || = nan
   Pass :  1   Iteration :  50  || r || = nan
Restarting...
FGMRES: No convergence!


(2) Ubuntu18.04, compiled with: make pdebug -j
Boundary elements with wrong orientation: 3198 / 19288 (fixed)
Boundary elements with wrong orientation: 3198 / 19288 (fixed)
Boundary elements with wrong orientation: 3198 / 19288 (fixed)
Boundary elements with wrong orientation: 3198 / 19288 (fixed)
Mesh::GeneratePartitioning(...): edgecut = 7280

************** Loop 1 **************
myid = 3, b->Norml2()= 0
myid = 2, b->Norml2()= 0
myid = 1, b->Norml2()= 1.38287e+11
myid = 0, b->Norml2()= 4.54761e+11
Number of finite element unknowns: 319141
   Pass :  1   Iteration :   0  || r || = 4.76208e+11
   Pass :  1   Iteration :   1  || r || = 4.76208e+11
   Pass :  1   Iteration :   2  || r || = 1.53457e+10
   Pass :  1   Iteration :   3  || r || = 1.53457e+10
   Pass :  1   Iteration :   4  || r || = 2.33118e+09
   Pass :  1   Iteration :   5  || r || = 2.33118e+09
   Pass :  1   Iteration :   6  || r || = 3.02166e+08
   Pass :  1   Iteration :   7  || r || = 3.02166e+08
   Pass :  1   Iteration :   8  || r || = 3.61881e+07
   Pass :  1   Iteration :   9  || r || = 3.61881e+07
   Pass :  1   Iteration :  10  || r || = 5.86033e+06
   Pass :  1   Iteration :  11  || r || = 5.86033e+06
   Pass :  1   Iteration :  12  || r || = 719653
   Pass :  1   Iteration :  13  || r || = 719653
   Pass :  1   Iteration :  14  || r || = 129526

************** Loop 2 **************
myid = 3, b->Norml2()= 0
myid = 2, b->Norml2()= 0
myid = 1, b->Norml2()= 4.13801e+11
myid = 0, b->Norml2()= 3.03334e+10
Number of finite element unknowns: 347557
   Pass :  1   Iteration :   0  || r || = 4.14898e+11
   Pass :  1   Iteration :   1  || r || = 4.14898e+11
   Pass :  1   Iteration :   2  || r || = 2.83664e+10
   Pass :  1   Iteration :   3  || r || = 2.83664e+10
   Pass :  1   Iteration :   4  || r || = 4.49122e+09
   Pass :  1   Iteration :   5  || r || = 4.49122e+09
   Pass :  1   Iteration :   6  || r || = 9.31417e+08
   Pass :  1   Iteration :   7  || r || = 9.31417e+08
   Pass :  1   Iteration :   8  || r || = 1.72506e+08
   Pass :  1   Iteration :   9  || r || = 1.72506e+08
   Pass :  1   Iteration :  10  || r || = 3.70817e+07
   Pass :  1   Iteration :  11  || r || = 3.70817e+07
   Pass :  1   Iteration :  12  || r || = 8.21497e+06
   Pass :  1   Iteration :  13  || r || = 8.21497e+06
   Pass :  1   Iteration :  14  || r || = 1.58595e+06
   Pass :  1   Iteration :  15  || r || = 1.58595e+06
   Pass :  1   Iteration :  16  || r || = 336087

************** Loop 3 **************
myid = 2, b->Norml2()= nan
myid = 3, b->Norml2()= 0
myid = 1, b->Norml2()= nan
myid = 0, b->Norml2()= 3.07766e+10
Number of finite element unknowns: 366240


Assertion failed: (IsFinite(beta)) is false:
 --> beta = -nan
 ... in function: virtual void mfem::FGMRESSolver::Mult(const mfem::Vector&, mfem::Vector&) const
 ... in file: linalg/solvers.cpp:1005



Assertion failed: (IsFinite(beta)) is false:
 --> beta = -nan
 ... in function: virtual void mfem::FGMRESSolver::Mult(const mfem::Vector&, mfem::Vector&) const
 ... in file: linalg/solvers.cpp:1005



Assertion failed: (IsFinite(beta)) is false:
 --> beta = -nan
 ... in function: virtual void mfem::FGMRESSolver::Mult(const mfem::Vector&, mfem::Vector&) const
 ... in file: linalg/solvers.cpp:1005



Assertion failed: (IsFinite(beta)) is false:
 --> beta = -nan
 ... in function: virtual void mfem::FGMRESSolver::Mult(const mfem::Vector&, mfem::Vector&) const
 ... in file: linalg/solvers.cpp:1005

--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 3 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
[yaohongbo-Precision-3630-Tower:08754] 3 more processes have sent help message help-mpi-api.txt / mpi-abort
[yaohongbo-Precision-3630-Tower:08754] Set MCA parameter "orte_base_help_aggregate" t


(3) MacBook Pro, compiled with: make parallel -j

**Comment by fanronghong** [comment]
Hi @hongbo-yao ,

I think errors may be because of not initializing  some variables, like `B` or `U`. I dont install openmpi, so I cannot run the example for debugging.

**Comment by hongbo-yao** [comment]
> Hi @hongbo-yao ,
> 
> I think errors may be because of not initializing some variables, like `B` or `U`. I dont install openmpi, so I cannot run the example for debugging.

Hi @fanronghong ,

Thank you for your reply.

The issue is strange, and I need more time to fix it.

Best wishes,
Hongbo

**Comment by hongbo-yao** [comment]
> Hi @hongbo-yao ,
> 
> I think errors may be because of not initializing some variables, like `B` or `U`. I dont install openmpi, so I cannot run the example for debugging.

Hi @fanronghong ,

Inspired by your thought, I tried to check it more closely.

Yes, you are right! This is caused by not initializing some variables, not  `B` or `U`, but the ParComplexLinearForm b itself.
I only initialize b before the refinement loop,  in fact, it should be initialized within the loop.

And @psocratis, thank you for your help.

I'll close this issue.

Best wishes
