### ISSUE TITLE
Gmsh ASCII and binary formats 

### ISSUE THREAD

**Issue by mpanesi** [mfem/mfem#1668]
Hello,

I have been trying to import  a grid done with Gmsh (all versions). I have problems even with Version 2, which is supposed to work. Can you advise? I am using the latest version of Gmsh (version 4.6.0, 22 June 2020).

I am able to read the $Nodes correctly, but I have problems with $Elements. Did anybody run into this issue?

Thank you,

**Comment by mlstowell** [comment]
Hi, @mpanesi ,

I think we'll need more information.  Are you seeing an error message?  Any more details about the issue would be helpful.

Best wishes,
Mark

**Comment by mpanesi** [comment]
Hi all,

I cannot see my response here, so i am going to respond again: 

I am adding the error message and the mesh file:

MFEM abort: Gmsh file : vertex index doesn't exist
 ... in function: void mfem::Mesh::ReadGmshMesh(std::istream&)
 ... in file: mesh/mesh_readers.cpp:1181

Also, I have asked Pointwise to implement the MFEM format, it seams that for the linear case they are going to do that.
// directly to vertices describing the mesh element
const int n_elem_nodes = nodes_of_gmsh_element[type_of_element-1];
               vector<int> vert_indices(n_elem_nodes);
               int index;
               for (int vi = 0; vi < n_elem_nodes; ++vi)
               {
		 input >> index;
		 cout<< "index " << index << "\n "; 
		 map<int, int>::const_iterator it = vertices_map.find(index);
		 if (it == vertices_map.end())
		   {
                     MFEM_ABORT("Gmsh file : vertex index doesn't exist");
		   } //// MARCO HACK 
		 vert_indices[vi] = it->second;
               }
	       
[MeshNew2.zip](https://github.com/mfem/mfem/files/4998262/MeshNew2.zip)

**Comment by sshiraiwa** [comment]
Hi @mpanesi 
The uploaded mesh file saves parametric nodes. In other words, there is $ParametricNodes in the file. Please try Mesh.SaveParametric=0, so that GMSH save a regular $Nodes information.

**Comment by mpanesi** [comment]
Hi Sshiraiwa
It worked. I used gmsh version 2 format with no option and that made the tricks. 
Thank you
