### ISSUE TITLE
Update Travis testing to gcc 4.9?

### ISSUE THREAD

**Issue by aaroncblack** [mfem/mfem#167]
Gnu 4.9 is a more stable compiler version than gnu 4.8.

I would like to update our Travis testing to use it instead of 4.8 (assuming there is an apt package for it on Travis). 

Any team members want to stay on 4.8?

**Comment by tzanio** [comment]
Either one is fine with me.

**Comment by tzanio** [comment]
@aaroncblack, is this PR still outstanding?

**Comment by aaroncblack** [comment]
I added PR#173, should be able to close when that is merged.
