### ISSUE TITLE
Comboing TMOP metrics with GridFunctionCoefficient weighting

### ISSUE THREAD

**Issue by timrlaw** [mfem/mfem#1671]
Hello,

As the title suggests I'm trying to use a GridFunction to modify the weighting of a TMOP metric across the mesh. The mesh-optimizer mini-app demonstrates using FunctionCoefficients to do this, so I assume using a pre-constructed GridFunction should not be a problem from an algorithmic point of view.

However when I try altering mesh-optimizer.cpp in the following way:

```
...
FunctionCoefficient fcoeff2(weight_fun);
GridFunction test(fespace);
test.ProjectCoefficient(fcoeff2);
GridFunctionCoefficient coeff2(&test);

if (combomet > 0)
{
...
```

I get this runtime error:

```
MFEM abort: GridFunction::GetValue: Unsupported element type "0"
 ... in function: virtual double mfem::GridFunction::GetValue(mfem::ElementTransformation&, const mfem::IntegrationPoint&, int, mfem::Vector*) const
 ... in file: /home/timrlaw/repos/mfem/fem/gridfunc.cpp:791
```

Digging into fem/tmop.cpp the root cause seems to be the IsoparametricTransformation set up around line 2141, for which the ElementType property does not get set. If I apply the following diff, it appears to work fine.

```
diff --git a/fem/tmop.cpp b/fem/tmop.cpp
index 55d218285..2026616b5 100644
--- a/fem/tmop.cpp
+++ b/fem/tmop.cpp
@@ -2144,6 +2144,7 @@ void TMOP_Integrator::AssembleElementVectorExact(const FiniteElement &el,
       Tpr = new IsoparametricTransformation;
       Tpr->SetFE(&el);
       Tpr->ElementNo = T.ElementNo;
+      Tpr->ElementType = ElementTransformation::ELEMENT;
       Tpr->Attribute = T.Attribute;
       Tpr->GetPointMat().Transpose(PMatI); // PointMat = PMatI^T
       if (exact_action)
```

However I'm unsure if I'm actually missing a step required to make this work without changing MFEM. Could anyone comment?

Thanks

**Comment by kmittal2** [comment]
Hi @timrlaw

You are right. It seems like ElementType property was being set until recently when we accidentally removed it in a PR where we refactored the TMOP code.  Can you please add it manually for now and we will fix this soon.

Thanks,
Ketan

**Comment by timrlaw** [comment]
Sure thing, thanks for the quick response @kmittal2

**Comment by vladotomov** [comment]
Hi @timrlaw, thanks for reporting the error. We will re-add the missing line in `master` today or tomorrow.

> The mesh-optimizer mini-app demonstrates using FunctionCoefficients to do this, so I assume using a pre-constructed GridFunction should not be a problem from an algorithmic point of view.

Actually there is an issue with this. A pre-constructed `GridFunction` is defined with respect to the initial mesh elements (i.e. in logical space). Once the positions of the elements change, the `GridFunction` will "move" with them. In order to get correct values, one has to transfer the pre-computed `GridFunction` from the initial mesh to the new one. We have methods to do this, but they are not implemented for `GridFunctionCoefficients`. This is not a problem for `FunctionCoefficients`, because they are evaluated in physical space.

Support for `GridFunctionCoefficient` can be added, but it will take time.

Why do you want to use a `GridFunctionCoefficient`? Can you use a `FunctionCoefficient` instead?

Vladimir

**Comment by timrlaw** [comment]
Hi @vladotomov 

The idea is to influence the mesh optimisation process based on various criteria defined with respect to the original (pre-optimisation) mesh, not just position/time. The exact manner in which the weights are computed is also not known at compile-time (it is user-defined in some sense), so it would seem very awkward/inefficient (at least to me) to try and use a FunctionCoefficient for this.

After the mesh has been moved, the weights are no longer required, so it is not a problem that they are defined wrt logical space. Unless you are saying that this movement will interfere with the optimisation process itself?

**Comment by timrlaw** [comment]
I see, thanks that is good to know. Yes adaptivity is the goal, really looking to understand the extent of TMOP's capabilities in this regard. I'm aware of the adaptive limiting and the target constructors, although have yet to dig into the more complex examples of the latter in the mesh-optimizer mini-app.

> In order to get correct values, one has to transfer the pre-computed `GridFunction` from the initial mesh to the new one. We have methods to do this, but they are not implemented for `GridFunctionCoefficients`.

Would you be able to point these out so I can have a look?

**Comment by vladotomov** [comment]
I recommend starting with the following example
`./mesh-optimizer -m square01.mesh -o 2 -rs 2 -mid 7 -tid 5 -ni 200 -ls 2 -li 100 -bnd -qt 1 -qo 8`
where we use a `GridFunction` that adapts the local mesh size. This size adaptivity is triggered by `-tid 5`, implemented 
[here](https://github.com/mfem/mfem/blob/bba973db7339a99a1a920f27a27cbd4341f907a9/miniapps/meshing/mesh-optimizer.cpp#L362). The transition of the` GridFunction` between different meshes is handled internally, s.t. the user only has to specify it on the initial mesh.

Adaptation of other geometric parameters (aspect ratio, rotation) is also possible

**Comment by timrlaw** [comment]
Okay great. Thanks for your help Vladimir.

**Comment by rkevis** [comment]
Hi, so we are investigating TMOP's capabilities in comparison to current methods we have implemented. Some of the options we provide our users include quality, weights (ie. r-refinement) and restrictions which I think maps nicely to TMOP Combined  metrics, adaptability and limiting, all of which we are investigating. In terms of the differences between GridFunctionCoefficients and FunctionCoefficients, our indicators are either genuine functions of the mesh, or functions of space. For the latter, some could be expressed as FunctionCoefficients whilst others have been discretised onto the mesh. For example in Volume-Of-Fluid ALE, to update one indicator between iterations would require an advective update and interface reconstruction. I would be very interested to understand your transfer methods for discrete functions between meshes in the iterative update. Currently we would use limits to guard against this error and effectively iterate around the entire ALE update.
Many thanks, Rob.

**Comment by kmittal2** [comment]
Hi @rkevis , we currently support two different options for transferring discrete functions between meshes. The first method is based on an advection-based approach (see section 4.2 of [Towards Simulation-Driven Optimization of High-Order Meshes by the Target-Matrix Optimization Paradigm](https://link.springer.com/chapter/10.1007/978-3-030-13992-6_16)) where we solve a PDE to "advect" the discrete function from the initial mesh to the optimized mesh. The second method is based on interpolation (see section 2.3 of [Nonconforming Schwarz-spectral element methods for incompressible flow](https://www.sciencedirect.com/science/article/pii/S0045793018308326)) where we find the degrees of freedom of the optimized mesh with respect to the reference space of the initial mesh and then interpolate the desired GridFunction. Take a look at these two methods and let us know if you have any questions.

**Comment by timrlaw** [comment]
Closing this as the fix has been merged.
