### ISSUE TITLE
ProjectBdrCoefficient() causes segmentation fault

### ISSUE THREAD

**Issue by fanronghong** [mfem/mfem#1675]
Hi all,

I want to set boundary conditions for two `ParGridFunction`, which one is in CG space and the another is in DG space.
But I got segmentation fault for DG, like below MWE. Thanks in advance.

```c++
#include <iostream>
#include "mfem.hpp"
using namespace std;
using namespace mfem;

int Wx = 0, Wy = 0;            // window position
int Ww = 350, Wh = 350;        // window size
int offx = Ww+5, offy = Wh+25; // window offsets
void Visualize(VisItDataCollection& dc, string field, string title="No title", string caption="No caption", int x=Wx, int y=Wy)
{
    int w = Ww, h = Wh;

    char vishost[] = "localhost";
    int  visport   = 19916;

    socketstream sol_sockL2(vishost, visport);
    sol_sockL2.precision(10);
    sol_sockL2 << "solution\n" << *dc.GetMesh() << *dc.GetField(field)
               << "window_geometry " << x << " " << y << " " << w << " " << h
               << "window_title '" << title << "'"
               << "plot_caption '" << caption << "'" << flush;
}

double sin_cos(const Vector& x)
{
    return sin(x[0]) * cos(x[1]);
}

int main(int argc, char *argv[])
{
    int num_procs, myid;
    MPI_Init(&argc, &argv);
    MPI_Comm_size(MPI_COMM_WORLD, &num_procs);
    MPI_Comm_rank(MPI_COMM_WORLD, &myid);

    Mesh *mesh = new Mesh(4, 4, Element::TRIANGLE, true, 1.0, 1.0);
    ParMesh* pmesh = new ParMesh(MPI_COMM_WORLD, *mesh);
    int dim = pmesh->Dimension();
    Array<int> Dirichlet;
    {
        int bdr_size = pmesh->bdr_attributes.Max();
        Dirichlet.SetSize(bdr_size);
        Dirichlet = 1;
    }

    H1_FECollection* cg_fec = new H1_FECollection(1, dim);
    DG_FECollection* dg_fec = new DG_FECollection(1, dim);
    ParFiniteElementSpace* cg = new ParFiniteElementSpace(pmesh, cg_fec);
    ParFiniteElementSpace* dg = new ParFiniteElementSpace(pmesh, dg_fec);

    FunctionCoefficient sin_cos_coeff(sin_cos);

    ParGridFunction gf1(cg), gf2(dg);

    gf1 = 0.0;
    gf1.ProjectCoefficient(sin_cos_coeff); // OK
//    gf1.ProjectBdrCoefficient(sin_cos_coeff, Dirichlet); // OK

    gf2 = 0.0;
    gf2.ProjectCoefficient(sin_cos_coeff); // OK
//    gf1.ProjectBdrCoefficient(sin_cos_coeff, Dirichlet); // Seg fault

    VisItDataCollection* dc = new VisItDataCollection("data collection", pmesh);
    dc->RegisterField("gf1", &gf1);
    dc->RegisterField("gf2", &gf2);
    Visualize(*dc, "gf1", "CG");
    Visualize(*dc, "gf2", "DG");

    MPI_Finalize();
    return 0;
}

```

**Comment by psocratis** [comment]
Hi @fanronghong , 

Let's take the H1 space first. In the constructor I see above 
````cpp
ParFiniteElementSpace* cg = new ParFiniteElementSpace(pmesh, cg_fec, dim);
````
you are creating a Vector H1 space (dim number of copies of H1 space). Is this actually what you want or the just the scalar H1 one space? 
a) If you indeed need a Vector H1 space ( with dimension = dim ) then when you project the BdrCoefficient you need to use a VectorCoefficient because any degree of freedom would have dim number of variables associated with it.. for example 
for a constant coefficient this would look like something this: 
````cpp
Vector t(dim); t = 1.0;
VectorConstantCoefficient coeff(t);
gf1.ProjectBdrCoefficient(coeff, Dirichlet); 
````

b) if you just need the scalar H1 space  all you need to do is to remove the dim in the constructor above. 

Now... for the DG space, there is no notion of boundary degrees of freedom, since the trace of an L2 function is not well defined. I believe that ProjectBdrCoefficient is not meant to be called for a DG function. In mfem, Dirichlet BCs are handled by special boundary integrators (for example see ex14)...

I am no DG expert so I'll ping @pazner for this, in case you got more questions regarding the DG case. 

Thanks, 

Socratis

**Comment by fanronghong** [comment]
Hi @psocratis ,

Thanks for your reply. 
a) I just want to create scalar H1 space and DG1 space. How can I make such a stupid mistake?

b) If I want to impose boundary conditions weakly, I just follow with ex14. But here, I am using Newton nonlinear iteration and I want to the initial value satisfying the boundary conditions strongly.

**Comment by psocratis** [comment]
Hi @fanronghong , 
Can you provide more details on the problem? What exactly is the problem/formulation you want to solve? 

Thanks,

Socratis

**Comment by psocratis** [comment]
Hi @fanronghong , 

One thing you can do is to create the H1 GridFunction and then project onto the DG space. This looks something like this: 

````cpp
    gf1 = 0.0;
    gf1.ProjectBdrCoefficient(sin_cos_coeff, Dirichlet); 
    gf2 = 0.0;
    gf2.ProjectGridFunction(gf1);
````

For your example this is how the H1 and DG GridFunctions look like respectively.

![image](https://user-images.githubusercontent.com/14336752/89337356-ac516f80-d64f-11ea-8c53-318ecd907dec.png)
![image](https://user-images.githubusercontent.com/14336752/89337391-b7a49b00-d64f-11ea-9fa4-4d2e2ea30c56.png)

I hope this helps. 

Thanks, 

Socratis

**Comment by fanronghong** [comment]
Hi @psocratis ,

Sorry about not offering more details. The whole project source code is very big.

For example, if `u1` is a `ParGridFunction` in `CG`, I can set boundary condition for `u1` by `u1.ProjectBdrCoefficient()`. But now, I have a `ParGridFunction` `u2` in `DG`, and I cannot use `u2.ProjectBdrCoefficient()` which causes a segmentation fault.

Yes, your approach can solve my problem. Thanks again.

**Comment by psocratis** [comment]
Hi @fanronghong , 

I think this is an elegant and the easiest way to do it. 

Thanks, 
Socratis

**Comment by mlstowell** [comment]
Hi, @fanronghong ,

I also think @psocratis 's suggestion is the easiest you'll find and it's certainly elegant in its simplicity although elegance is in the eye of the beholder.  I'll defer to @pazner on this but I don't think it will be possible for the initial value to "strongly" satisfy the boundary conditions in general when using DG.  As an alternative you might consider initializing the Newton iteration with an approximate solution based on a similar linear problem.  Such a solution would still not satisfy the boundary conditions in a strong sense but it would approximate a smooth function on the entire domain which weakly satisfies the boundary conditions and this might be a good alternative.

Best wishes,
Mark

**Comment by fanronghong** [comment]
Thanks @psocratis and @tzanio ,

I will follow your suggestions. Thanks again.
