### ISSUE TITLE
Problem about implicit ODESolver

### ISSUE THREAD

**Issue by HyeonjunLee** [mfem/mfem#1677]
Hi, I am developing a code by modifying examples/ex9.cpp and mesh for my system.
When the code run with implicit ODESolver options, higher than certain refinement level, it aborts at 'BlockILU' .
Following is a log.

MFEM abort: BlockILU: block size must evenly divide the matrix size
 ... in function: void mfem::BlockILU::CreateBlockPattern(const mfem::SparseMatrix&)
 ... in file: linalg/solvers.cpp:2211

This abort dose not occurs at low refinement level.
How can I resolve this?

Thank you in advance.

**Comment by v-dobrev** [comment]
Can provide some more detail -- when the code fails, how many unknowns do you have? What is the block-size you use in the `BlockILU` constructor?

**Comment by tzanio** [comment]
This issue hasn't been active for more than 3 weeks, so I will close it now. Feel free to re-open if you have not been able to resolve it.
