### ISSUE TITLE
Improve error message in DenseMatrix::Eigensystem

### ISSUE THREAD

**Issue by benzwick** [mfem/mfem#1678]
Attempting to compute the eigensystem of a dense matrix without LAPACK results in the following error:
```
DenseMatrix::Eigensystem
Aborted
```
which is not very informative.

Could we add some extra information to this line in [densemat.cpp](https://github.com/mfem/mfem/blob/ba51fe2c53862699eadf465537a6a66a290ea909/linalg/densemat.cpp#L1086):
```
   mfem_error("DenseMatrix::Eigensystem");
```
e.g. like this:
```
   mfem_error("DenseMatrix::Eigensystem: requires MFEM built with LAPACK");
```
to make it immediately obvious why this failed?

Maybe the instructions for using LAPACK could also be added to the instructions on the [website](https://mfem.org/building/).

**Comment by benzwick** [comment]
On [line 1167](https://github.com/mfem/mfem/blob/ba51fe2c53862699eadf465537a6a66a290ea909/linalg/densemat.cpp#L1167) there is also this one:
```
   mfem_error("DenseMatrix::Eigensystem for generalized eigenvalues");
```

On [line 3372](https://github.com/mfem/mfem/blob/ba51fe2c53862699eadf465537a6a66a290ea909/linalg/densemat.cpp#L3372) (and a few other places) there is this message which could be used for the similar errors above:
```
   mfem_error("DenseMatrixEigensystem::Eval(): Compiled without LAPACK");
```
There are also some other errors in `densemat.cpp` that could output more information like "incorrect matrix dimensions" or "dimension mismatch", for example [here](https://github.com/mfem/mfem/blob/ba51fe2c53862699eadf465537a6a66a290ea909/linalg/densemat.cpp#L2399):
```
   if (A.Height() != ABt.Height() || B.Height() != ABt.Width() ||
       A.Width() != B.Width())
   {
      mfem_error("MultABt(...)");
   }
```

**Comment by barker29** [comment]
In my view these suggestions are very reasonable. Could you collect them in a pull request and submit it?

**Comment by benzwick** [comment]
Yes, I will create a PR for this.

Somewhat related, can someone please explain to me what the `MFEM_CONTRACT_VAR` macro is used for. It is defined [here](https://github.com/mfem/mfem/blob/b9a40daf5b3b6b5338907c3936941415abd5e4b4/general/error.hpp#L113) as:
```
#define MFEM_CONTRACT_VAR(x) if (false && (&x)+1){}
```
and used a lot in densemat.cpp.

**Comment by barker29** [comment]
If I understand correctly, `MFEM_CONTRACT_VAR` is a hack to suppress an unused variable warning in optimized build. If you use a variable in asserts but nothing else, the preprocessor will strip out all the uses and you get the warning, but if you use `MFEM_CONTRACT_VAR` then the optimizer will still remove the statement (it doesn't do anything) but not trigger the warning.

**Comment by tzanio** [comment]
Discussion continued in #1685.
