### ISSUE TITLE
Support for CUDA + SIMD?

### ISSUE THREAD

**Issue by wcdawn** [mfem/mfem#1689]
I'm compiling MFEM on a HPC cluster with VSX instructions and CUDA (Summit at ORNL).
I've seen recent PRs (e.g. #1627, #1642, #1555) but I'm still a bit confused.
Does MFEM support using both CUDA and SIMD at the same time? Or do I need to choose only one (CUDA)?
Is there a plan to support this in the future?

**Comment by camierjs** [comment]
The idea is to support builds where both CUDA and intrinsics (only in the `templated` code) are used, but is has been disabled by default because of some compiler combinations `nvcc` + `X` that bring issues.

**Comment by wcdawn** [comment]
I see that from #1627.
Using `nvcc` with the IBM compiler `xc++` seems to have errors with this.
Is there a plan to support this in the future?

**Comment by camierjs** [comment]
You can try #1695 with `xlc`: `make distclean && make cuda MFEM_USE_SIMD=YES CUDA_ARCH=sm_70 CXX=xlc++ -j`

**Comment by wcdawn** [comment]
Branch `simd` from #1695 seems to be working on Summit with the instructions you provided. Thanks!
