### ISSUE TITLE
Parallel version of Trimmer miniapp

### ISSUE THREAD

**Issue by enjoh** [mfem/mfem#1696]
Will there be a parallel version of the trimmer miniapp functionality?
So one could then extract parts of a mesh and perform calculations on this sub-mesh in parallel.

**Comment by v-dobrev** [comment]
@mlstowell can correct me, but I don't think anyone is working on such parallel functionality -- that will probably require parallel re-balancing as well for proper distribution of the computations.

**Comment by tzanio** [comment]
As @v-dobrev, we are not currently working on a parallel version of Trimmer. That will not be that easy to do, due to the shared faces, edges and vertices that have to be (re-)defined in parallel. We will certainly welcome a PR with such functionality if you decide to work on it though.
