### ISSUE TITLE
mfem::Mesh::Make1D, mfem::Mesh::Make2D, mfem::Mesh::Make3D lack error checks on invalid argument values

### ISSUE THREAD

**Issue by goxberry** [mfem/mfem#1698]
Specifically, these methods do not check whether the number of elements along any dimension is strictly positive. Presumably, the bounding boxes must have nonzero edge lengths as well, but I haven't bothered to try to trace through the meshing code to figure out the consequences. It looks like negative edge length values are legal and kind of sensible, if not necessarily intended.

Also, why did MFEM choose to implement `VTX` as a macro instead of a (presumably inline-able) function with internal linkage (i.e., `static` or enclosed in an anonymous namespace)?

**Comment by v-dobrev** [comment]
@goxberry, all these suggestions seem reasonable to me. Would you like to create a PR?

**Comment by tzanio** [comment]
ping: @goxberry
