### ISSUE TITLE
Reorder dofs on a process

### ISSUE THREAD

**Issue by jehicken** [mfem/mfem#1699]
Hi,

**Short version:** is it possible to reorder the mfem DOFs on each process?

I am using Hypre's parallel ILU, and I need finer grain control over the ordering of unknowns to improve the effectiveness of the preconditioner.  The available reorderings provided by this preconditioner are RCM and natural.  Since RCM does not always work well for me, the Hypre developers suggested changing the natural ordering.

Therefore, is it possible to reorder the DOFs on each process within MFEM?  For example, suppose I am using a CG discretization of the compressible Navier-Stokes equations, and I want the nodal degrees of freedom to be randomly ordered.

Thank you.
Jason

**Comment by jandrej** [comment]
Maybe https://github.com/mfem/mfem/blob/master/linalg/solvers.cpp#L2262 helps. It implements MDF reordering and gives you an ordering vector.

**Comment by jehicken** [comment]
Thanks; however, I don't believe I can use `MinimumDiscardedFillOrdering` with `HypreParMatrix`, at least not directly.

**Comment by pazner** [comment]
One possible way of achieving this would be to form the permutation matrix as a `HypreParMatrix` and then use `RAP` to create the renumbered matrix.

**Comment by jehicken** [comment]
Thanks @pazner, that might work.  If we are using Newton solvers, we would need to modify the parallel nonlinear form, correct?

**Comment by pazner** [comment]
It's probably easiest to just reorder the input vector before computing the nonlinear form, and then reorder the residual vector afterwards. You could perhaps create an `Operator` object that wraps the nonlinear form together with the permutation.

**Comment by jehicken** [comment]
I will have to give this approach some thought.  Thanks again.

**Comment by v-dobrev** [comment]
It should be possible (with a some additions to MFEM) to reorder the dofs in the FE space directly. Essentially, in the `FiniteElementSpace`, one has to apply the permutation to the element-to-dof `Table` and other similar `Table` objects. There may be issues, though, with some methods that do not use the `Tables` -- probably `GetVertexDofs`, `GetEdgeDofs`, `GetElementInteriorDofs`, etc. For these, we may need to store a copy of the permutation array and apply it on-the-fly, if given. In parallel, this will probably have other implications as well.

Overall, full support for this in MFEM will require some work but trying out some specific use cases may not be too hard -- only modifying things in the `(Par)FiniteElementSpace` that are actually needed in the specific case.

**Comment by jehicken** [comment]
Thanks for the suggestion @v-dobrev.  The ordering I would like to try is relatively straightforward, so I may try to implement it in Hypre directly.
