### ISSUE TITLE
Right hand side of PDE

### ISSUE THREAD

**Issue by mparkgit** [mfem/mfem#17]
Hi,
   In MFEM, I saw examples in which right hand sides of Partial Differential Equations (PDE)
are added by imposing exact solutions.
When you compute numerical solutions of coupled PDE in which the solution of first PDE is
the right hand side (as input) of second one, how do you write the "main" function?
For example, Poisson-Nernst-Planck equation is one example of this case.

Thank you.

mp

**Comment by tzanio** [comment]
Hi @mparkgit,

You can use a GridFunctionCoefficient, https://github.com/mfem/mfem/blob/master/fem/coefficient.hpp#L132

The GridFunction class represent discrete (finite element) functions and GridFunctionCoefficient interprets these as function on continuous level, which could be used as PDE coefficients in linear and bilinear forms. For example, in Example 1, you can replace the coefficient "one" in the definition of the LinearForm "b", https://github.com/mfem/mfem/blob/master/examples/ex1.cpp#L106, with a GridFunctionCoefficient defined from a previously computed GridFunction.

Hope this helps,
Tzanio

**Comment by mparkgit** [comment]
Hi Tzanio,

   Thank you.
mp
