### ISSUE TITLE
Extract submatrix and subvector from PetscParMatrix and PetscParVector

### ISSUE THREAD

**Issue by chang-yiyi** [mfem/mfem#1707]
Hi all,

I'm considering a multi-domain model just like [this](https://github.com/mfem/mfem/issues/788#issue-420274536). And I want to try the expensive but simple way proposed by @tzanio [here](https://github.com/mfem/mfem/issues/788#issuecomment-472480579).

For example, the mesh have two kinds of element attributes, such as 1 and 2. There are two unknown variables `u` and `p`, where `u` is defined on all elements and `p` is defined on the elements marked by 2. After I assemble the whole system, I get below linear system (assume there are 100 dofs for all elements and 50 dofs for elements marked by 2).
![Screenshot from 2020-08-15 21-12-46](https://user-images.githubusercontent.com/24132779/90313091-48c31e00-df3c-11ea-9834-a4f7791b4b9d.png)

, where `B` has many zero columns, `A` has many zero rows and `D` has many zero columns and rows. I want to reduce the system to below linear system by eliminate many columns and rows respectively. The types of `A`, `B`, `C` and `D` are `PetscParMatrix`, and the types of `u`, `p`, `f` and `g` are `PetscParVector`
![Screenshot from 2020-08-15 21-15-20](https://user-images.githubusercontent.com/24132779/90313112-7b6d1680-df3c-11ea-9a52-be401f1c304f.png)

After I solve the above smaller linear system, I want to obtain `p` from $\tilde{p}$ for computing errornorm.

Finally, I have below questions:
1. How to extract DOFs corresponding to elements marked by 2?
2. How to extract subsystem from the original big system?
3. Because MFEM cannot define finite element space on a subdomain, is this a correct way to solve multi-domain problems?
Many thanks in advance!

For convenience, I build the below dummy code
```c++
#include <iostream>
#include "mfem.hpp"
using namespace mfem;
using namespace std;

int main(int argc, char *argv[])
{
    int num_procs, myid;
    MPI_Init(&argc, &argv);
    MFEMInitializePetsc(NULL, NULL, NULL, NULL);
    MPI_Comm_size(MPI_COMM_WORLD, &num_procs);
    MPI_Comm_rank(MPI_COMM_WORLD, &myid);

    Mesh* mesh = new Mesh("./inline-tri-modify.mesh");
    ParMesh* pmesh = new ParMesh(MPI_COMM_WORLD, *mesh);
    delete mesh;

    DG_FECollection* dg_fec = new DG_FECollection(1, 2);
    ParFiniteElementSpace* dg_space = new ParFiniteElementSpace(pmesh, dg_fec);

    Array<int> null_array;

    ParBilinearForm* a = new ParBilinearForm(dg_space);
    a->AddDomainIntegrator(new MassIntegrator);
    a->Assemble();

    ParBilinearForm* b = new ParBilinearForm(dg_space);
    b->AddDomainIntegrator(new MassIntegrator);
    b->Assemble();

    ParBilinearForm* c = new ParBilinearForm(dg_space);
    c->AddDomainIntegrator(new MassIntegrator);
    c->Assemble();

    ParBilinearForm* d = new ParBilinearForm(dg_space);
    d->AddDomainIntegrator(new MassIntegrator);
    d->Assemble();

    {
        PetscParMatrix A, B, C, D;

        a->SetOperatorType(Operator::PETSC_MATAIJ);
        a->FormSystemMatrix(null_array, A);

        b->SetOperatorType(Operator::PETSC_MATAIJ);
        b->FormSystemMatrix(null_array, B);

        c->SetOperatorType(Operator::PETSC_MATAIJ);
        c->FormSystemMatrix(null_array, C);

        d->SetOperatorType(Operator::PETSC_MATAIJ);
        d->FormSystemMatrix(null_array, D);
    }

    ParLinearForm* f = new ParLinearForm(dg_space);
    ParLinearForm* g = new ParLinearForm(dg_space);

    delete pmesh;
    delete dg_fec, dg_space;
    delete a, b, c, d, f, g;

    MFEMFinalizePetsc();
    MPI_Finalize();
    return 0;
}
```
[inline-tri-modify.mesh.txt](https://github.com/mfem/mfem/files/5078767/inline-tri-modify.mesh.txt)

**Comment by kmittal2** [comment]
Hi @chang-yiyi 
We are in the process of adding miniapps that show how multi-domain problems can be solved in MFEM. As it stands, PR #1462 solves example 1 using multiple overlapping domains (`miniapps/gslib/ex1p`). For this example, we do simultaneous Schwarz iterations to solve the PDE of interest in each subdomain and boundary conditions at the interior/artificial boundaries are interpolated from the overlapping mesh before each Schwarz iteration. This same methodology can likely be extended to your problem where a mesh is setup to model each material and suitable transmission/boundary conditions are imposed at the interface and updated after each PDE solve.

Ketan

**Comment by psocratis** [comment]
Hi @chang-yiyi,

Let's for now deal with the serial case and no hanging nodes etc. I am assuming the elements of the mesh are marked by attributes. Suppose you want to find out the dof indices of the mesh that do not belong in elements with attribute number = 2 you could do something like this 

```cpp
   for (int iel = 0; iel<mesh->GetNE(); ++iel)
   {
      int attr = fespace->GetAttribute(iel);
      if (attr == 2) continue;
      Array<int> elem_dofs;
      fespace->GetElementDofs(iel,elem_dofs);
      ..... (save the indices to a list)

   }
````

You can then construct a list of the dofs you actually need. Say the list is of size m. From that list you could construct an mfem::SparseMatrix P of size (n x m) ( where n is the size of the original matrix A). Each column would have only 1 non-zero entry equal to 1.0 corresponding to the dofs indices of the precomputed list. Then, to extract the sub-matrix you just need to compute the RAP, i.e, P^T A P. 

I hope this helps. 

Socratis

**Comment by chang-yiyi** [comment]
Thanks @kmittal2 , I will dig into the `miniapps/gslib/ex1p`.

Thanks @psocratis , following your suggestions I can obtain dof indices of the mesh that belong in elements with attribute number=2, like below
```
    // Obtain DOFs indices of mesh that belong in elements with attribute number = 2
    Array<int> attr2_dofs;
    for (int iel=0; iel<pmesh->GetNE(); ++iel)
    {
        int attr = dg_space->GetAttribute(iel);

        if (attr != 2) continue;
        Array<int> elem_dofs;
        dg_space->GetElementDofs(iel, elem_dofs);
        for (auto itm: elem_dofs) {
            attr2_dofs.Append(dg_space->GetGlobalTDofNumber(itm));
        }
    }
```
And one more question, if I use `H1` finite element space, after I get `attr2_dofs`, I must do
```
    attr2_dofs.Sort();
    attr2_dofs.Unique();
```
Am I right?

**Comment by psocratis** [comment]
Hi @chang-yiyi , 

Sorry, I think I was not careful before... here is how I would do it for the H1 case 

````cpp
   int tsize = h1_space->GetTrueVSize();
   Array<int> dof_marker(tsize);
   dof_marker = 0;
   Array<int> attr2_dofs;
   for (int iel=0; iel<pmesh->GetNE(); ++iel)
   {
      int attr = h1_space->GetAttribute(iel);

      if (attr != 2) continue;
      Array<int> elem_dofs;
      h1_space->GetElementDofs(iel, elem_dofs);
      for (int i = 0; i<elem_dofs.Size(); ++i) 
      {
         // This takes care of dof orientation
         int edof_ = elem_dofs[i];
         int edof = (edof_ >= 0) ? edof_ : - 1 - edof_ ;

         // Get the "global index" of the true dof
         int tdof = h1_space->GetGlobalTDofNumber(edof);
         
         // Skip if tdof is not owned by the processor
         int mytdofoffset = h1_space->GetMyTDofOffset();
         if (tdof < mytdofoffset || tdof >= mytdofoffset+tsize) continue;

         // Get the "local index" of the true dof
         int ldof = tdof - mytdofoffset;
         
         // Skip if the ldof is already in the list
         if (dof_marker[ldof]) continue;

         // Add to the list 
         // Here, depending of what you need, you can save 
         // either the local or the global index
         attr2_dofs.Append(ldof);
         dof_marker[ldof] = 1;
      }
    }

````

For the dg space you can do the same but there is no need to use the dof_marker.  And yes you can always avoid using the marker and do a sort and unique at the end.

Hope this is more clear.

Best,
Socratis

**Comment by chang-yiyi** [comment]
Hi @psocratis , this is a little for me to understand. I will use 
```
    attr2_dofs.Sort();
    attr2_dofs.Unique();
```
Thanks again.

**Comment by chang-yiyi** [comment]
Does anyone use [this expensive way](https://github.com/mfem/mfem/issues/788#issuecomment-472480579) to obtain linear system but only solve the linear sub-system?

Because the whole system has lots of rows each of which has only one nonzero entry (1.0) at diagonal, I only want to solve the subsystem.

**Comment by tzanio** [comment]
Last question was answered in #1739.
