### ISSUE TITLE
MFEM does not compile with the latest libCEED code

### ISSUE THREAD

**Issue by ajemcov** [mfem/mfem#1708]
The signature of the function CeedQFunctionSetContext in ceed.cpp (MFEM library) and ceed.h (libCEED library) no longer match. Here is the full error report:

mpicxx   -O3 -std=c++11 -I./../hypre/src/hypre/include  -I/Users/ajemcov/worx/petsc/include -I/Users/ajemcov/worx/petsc/arch-darwin-c-opt/include -I/opt/X11/include -I./../occa/include -I./../libCEED/include  -c fem/libceed/diffusion.cpp -o fem/libceed/diffusion.o
fem/libceed/ceed.cpp:361:4: error: no matching function for call to
      'CeedQFunctionSetContext'
   CeedQFunctionSetContext(ceedData.build_qfunc, &ceedData.build_ctx,
   ^~~~~~~~~~~~~~~~~~~~~~~
./../libCEED/include/ceed.h:496:17: note: candidate function not viable:
      requires 2 arguments, but 3 were provided
CEED_EXTERN int CeedQFunctionSetContext(CeedQFunction qf,
                ^
fem/libceed/ceed.cpp:402:4: error: no matching function for call to
      'CeedQFunctionSetContext'
   CeedQFunctionSetContext(ceedData.apply_qfunc, &ceedData.build_ctx,
   ^~~~~~~~~~~~~~~~~~~~~~~
./../libCEED/include/ceed.h:496:17: note: candidate function not viable:
      requires 2 arguments, but 3 were provided
CEED_EXTERN int CeedQFunctionSetContext(CeedQFunction qf,
                ^
mpicxx   -O3 -std=c++11 -I./../hypre/src/hypre/include  -I/Users/ajemcov/worx/petsc/include -I/Users/ajemcov/worx/petsc/arch-darwin-c-opt/include -I/opt/X11/include -I./../occa/include -I./../libCEED/include  -c fem/libceed/mass.cpp -o fem/libceed/mass.o
2 errors generated.

**Comment by jeremylt** [comment]
See #1701, a PR for this is already in review.

**Comment by ajemcov** [comment]
Thanks for your quick reply. I was not aware that the issue was already spotted. Sorry for the duplication and thanks one more time.


-- 
Aleksandar Jemcov, Ph.D.
Research Assistant Professor, 
Aerospace and Mechanical Engineering (AME),
Associate Director for Computational Science,
Notre Dame Turbomachinery Laboratory (NDTL),
University of Notre Dame
email 
ajemcov@nd.edu

phone (574) 631 7576 (AME)

**Comment by tzanio** [comment]
No worries @ajemcov, thank you for reporting it!

**Comment by tzanio** [comment]
Discussion continued in #1701
