### ISSUE TITLE
Hypre Vector operations

### ISSUE THREAD

**Issue by vikramsg** [mfem/mfem#172]
I completed a 2D Euler solver and extended it to 2D compressible Navier Stokes using MFEM with DG. Now I am trying to figure out how to use the parallel Hypre vectors and matrices to do the same operations. So I started by doing a simple matrix vector multiplication.

```
   ParFiniteElementSpace *fes_op = new ParFiniteElementSpace(pmesh, &fec);
   ParBilinearForm *k_inv_x      = new ParBilinearForm(fes_op);
   k_inv_x->AddDomainIntegrator(new ConvectionIntegrator(x_dir, -1.0));

   HypreParMatrix *K = k_inv_x->ParallelAssemble();

   ParGridFunction *u_sol = new ParGridFunction(fes);
   u_sol->ProjectCoefficient(u0);
   ParGridFunction *u_grad = new ParGridFunction(fes);

   HypreParVector *U = u_sol->GetTrueDofs();
   HypreParVector *V = u_grad->GetTrueDofs() ;

   K->Mult(*U, *V);

   for (int i = 0; i < U->Size(); i++)
   {
       int offset = U->Size()/dim;
       int sub1 = i, sub2 = offset + i, sub3 = 2*offset + i, sub4 = 3*offset + i;
       cout << i << '\t' <<  U[0](sub1) << '\t' << V[0](sub1) << endl;
   }
```

First I am not sure whether the above method is the correct way to print U. It seems to me that U[0] has current process values, but I don't know what the subscript is supposed to represent. Second, the Mult step seems to do nothing. ```V[0](sub1)``` prints 0. 

Also, in the serial case I could print nodes

```
 GridFunction nodes(&fes_nodes);
 mesh->GetNodes(nodes);

 cout << nodes(sub1) << '\t' << nodes(sub2) << endl;

```

I couldn't find a similar way to print nodes with the parallel mesh function.

**Comment by vladotomov** [comment]
Hi Vikram, this is impressive progress, congratulations!
Sorry for taking so long to look at this.
You still need to call k_inv_x->Assemble() and Finalize() to actually assemble the local parts; the ParallelAssemble() is used only to connect the mpi tasks.
Also make sure that k_inv_x->Size() == u_sol->Size().
I'm not sure why you want to print the vector on the true dofs as there is the local dofs -> true dofs mapping that affects the indexing. It's probably easier to distribute V back to a ParGridFunction and the print v_sol and u_sol for each task.

**Comment by vikramsg** [comment]
Hi @vladotomov,

Thanks for the comments. Actually I do in fact do k_inv_x->Assemble and Finalize. I had just forgotten to paste it here. This is the code. 

```
   ParFiniteElementSpace *fes_op = new ParFiniteElementSpace(pmesh, &fec);
   ParBilinearForm *k_inv_x      = new ParBilinearForm(fes_op);
   k_inv_x->AddDomainIntegrator(new ConvectionIntegrator(x_dir, -1.0));
   k_inv_x->Assemble(skip_zeros);
   k_inv_x->Finalize(skip_zeros);

   HypreParMatrix *K = k_inv_x->ParallelAssemble();

   ParGridFunction *u_sol = new ParGridFunction(fes);
   u_sol->ProjectCoefficient(u0);
   ParGridFunction *u_grad = new ParGridFunction(fes);

   HypreParVector *U = u_sol->GetTrueDofs();
   HypreParVector *V = u_grad->GetTrueDofs() ;

   K->Mult(*U, *V);

   for (int i = 0; i < U->Size(); i++)
   {
       int offset = U->Size()/dim;
       int sub1 = i, sub2 = offset + i, sub3 = 2*offset + i, sub4 = 3*offset + i;
       cout << i << '\t' <<  u_sol[0](sub1) << '\t' << u_grad[0](sub1) << endl;
   }
```

As before I get zeros for u_grad.


Regarding the second part. If I print u_sol, I have to use u_sol[0]. Is this the correct way of printing it?

**Comment by vladotomov** [comment]
I'm confused by your K->Mult(...) -- do you have the same sizes, i.e., are fes and fes_op the same space? Seems like fes_op has dim components, while fes has just one?
Also note that U->Size() may not be the same as u_sol->Size(), you should fix the last loop.
Yes, printing _sol[0] should be fine, don't you see the correct initial values when you print this?

**Comment by vikramsg** [comment]
Hi @vladotomov ,

Sorry for all the confusion. Yes, it was purely a mismatched size thing. 

Thanks for the help.

Vikram
