### ISSUE TITLE
Surface integral over an interface

### ISSUE THREAD

**Issue by NikolayYavich** [mfem/mfem#1721]
Dear All,

Earlier in issue #1093 @tzanio  suggested "to mark the interior interface as boundary"
to compute a surface integral over an interface between subdomains.

Could someone provide an example please?
And what will be the direction of the normal vector in `BoundaryNormalLFIntegrator`?

My modeling domain is partitioned into several non-overlapping subdomainns marked
with the respective attributes, i.e. the interface is formed by two subdomains with different
attributes.

Thanks a lot,
Nikolay.

**Comment by chang-yiyi** [comment]
Hi @NikolayYavich ,

Is the interface matched between two subdomains?

**Comment by NikolayYavich** [comment]
Yes, the interface is formed by two subdomains with different
attributes.

I would like to use `BoundaryNormalLFIntegraton` (or similar) acting on H1 nodal finite elements.

**Comment by mlstowell** [comment]
Hi, @NikolayYavich ,

It's a little hard to know what to suggest.  What is the goal?  Are you trying to create a source term on a thin sheet in this interface or are you trying to make a measurement of the integral of an existing field (stored as a `GridFunction`) on a particular interface, or perhaps something else entirely?

Best wishes,
Mark

**Comment by NikolayYavich** [comment]
> measurement of the integral of an existing field (stored as a GridFunction) on a particular interface, 
Yes, exactly, a numerical solution is stored GridFunction and I would like to integrate
it over an interface, multiplied by VectorCoefficient.

Thanks a lot!
Nikolay

**Comment by mlstowell** [comment]
Hi, @NikolayYavich ,

Okay, @tzanio was correct that this is exactly the sort of thing that the `entity-sets-dev` branch hopes to address (but this feature is not implemented yet).  You also mentioned the surface normal. I'm curious how this fits in. Just to be specific, what type of basis functions are you using for your `GridFunction`?  Are you hoping to integrate the inner product of the `VectorCoefficient`  with the surface normal and the scalar-valued `GridFunction`, or something else?

I think we may be able to put together a simple class, based on a `LinearForm` object, to compute this and produce the value of the integral as a single `double`.

Best wishes,
Mark

**Comment by NikolayYavich** [comment]
Yes, I want to compute
[<a href="https://www.codecogs.com/eqnedit.php?latex=\int_\Gamma&space;p&space;~\overrightarrow{v}&space;\cdot&space;\overrightarrow{\nu}&space;~dS" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\int_S&space;p&space;~\overrightarrow{v}&space;\cdot&space;\overrightarrow{n}&space;~dS" title="\int_S p ~\overrightarrow{v} \cdot \overrightarrow{n} ~dS" /></a>](url)
where p is scalar H1 nodal finite element GridFunction, and v is a VectorCoefficient, n is normal to S.

Thanks!

**Comment by NikolayYavich** [comment]
Let me add one other detail.
Actually, I am interested in two possibilities:
* p is scalar H1 nodal finite element grid function
* p face-based scalar grid function 

Evidently, in both cases, I can make loop over the faces, 
apply quadratures on each triangle, sum everything up, and this
will give me the value to the integral. But I assumed MFEM may
have functionality for this operation. 

Thanks again,
Nikolay.

**Comment by v-dobrev** [comment]
The first step will be to pre-process your mesh to add the interface as "boundary" elements with some special attribute. I put "boundary" in quotes because in mfem these can include interior face elements, e.g. the interface you want to describe.

The pre-processing will be simply reading the mesh and then saving it with a customized (slightly modified) version of the method `Mesh::PrintWithPartitioning`. This method replaces all "boundary" elements in the mesh with the boundaries of all subdomains defined by the `partitioning` array. This way, interior boundaries are actually described two times. We use this method, for example, to visualize in GLVis the subdomains defined by the element attributes -- this is done by menu option `m` in the `mesh-explorer` miniapp, `miniapps/meshing/mesh-explorer.cpp`.

Let me know if you need help customizing the code in `Mesh::PrintWithPartitioning`.

**Comment by v-dobrev** [comment]
Once you have the interface added, you can compute the integral by defining a linear form (with an integrator restricted to the interface attribute), assemble it, and then dot it with the grid-function representing `p`.

A direct implementation (without the need to explicitly introduce the interface) is also possible but that will use a lower-level mfem functionality.

**Comment by NikolayYavich** [comment]
Hi @v-dobrev 
Thanks a lot for the hint! I'll try implement this suggestion.
