### ISSUE TITLE
The Problem when run ex1p with cuda

### ISSUE THREAD

**Issue by nghiakvnvsd** [mfem/mfem#1728]
Hello everyone! When I run: mpirun -np 4 ex1p -pa -d cuda -m ../data/square-disc.mesh . It doesn't work. I have no idea about it. May you help me. Thank you!

**Comment by hongbo-yao** [comment]
Hi @nghiakvnvsd,

Have you built MFEM with cuda corretly? e.g. make cuda -j 4

Maybe you can give your build/compile command and the ex1p's running information here, so anyone know it can give you some advices.

**Comment by nghiakvnvsd** [comment]
> Hi @nghiakvnvsd,
> 
> Have you built MFEM with cuda corretly? e.g. make cuda -j 4
> 
> Maybe you can give your build/compile command and the ex1p's running output information here, so anyone know it can give you some advices.

Thank you for replying. I use :"make cuda -j 4" and when I use: make ex1p it returns:

nvcc  -O3 -std=c++11 -x=cu --expt-extended-lambda -arch=sm_60 -ccbin mpicxx -I.. -I../../hypre/src/hypre/include ex1p.cpp -o ex1p -L.. -lmfem -L../../hypre/src/hypre/lib -lHYPRE  -L../../metis-4.0 -lmetis  -lrt
../libmfem.a(mesh.o): In function `mfem::Mesh::GeneratePartitioning(int, int)':
tmpxft_00001d0f_00000000-5_mesh.cudafe1.cpp:(.text+0x35c95): undefined reference to `METIS_PartGraphVKway'
collect2: error: ld returned 1 exit status
makefile:65: recipe for target 'ex1p' failed
make: *** [ex1p] Error 1

**Comment by hongbo-yao** [comment]
Hi @nghiakvnvsd ,

Can you rebuild mfem with: make pcuda -j 4 instead of: make cuda -j 4 ?

I don't have an NVIDIA GPU so I can't reproduce the problem,  other person may help.

Best wishes

**Comment by camierjs** [comment]
Hi @nghiakvnvsd,
As @hongbo-yao said, you should switch to a **parallel** build if you want to compile **parallel** examples.
The error you reported tells that the `metis` library is missing, which will be used if you do a `make pcuda -j 4` for example.
Tell us if you are able to build `ex1`.
