### ISSUE TITLE
New features for the libCEED integration in MFEM

### ISSUE THREAD

**Issue by YohannDudouit** [mfem/mfem#1736]
# Merged in master
- Support for Vectorial Mass and Vectorial Diffusion: #1713 
- Support for fully Matrix-free Mass and Diffusion: #1670 
- Support for all types of Scalar `Coefficient`: #1716 
- Support Vectorial Mass and Vectorial Diffusion fully matrix-free: #1719 
- Add tests for all the libCEED features: #1719 
- Support periodic meshes: #1719 

# In review:
- Support Convection, Vectorial NL Convection, with PA and MF: #1766 
- Support all `VectorCoefficient` types: #1766 

# WIP:

# TODO:
- Support all `MatrixCoefficient` types
- Support `MixedBilinearForm`
- Support p-adaptivity and mixed meshes
- Replace global maps by integrating the Ceed objects in the MFEM objects.
- Add Element Assembly (EA) using libCEED.

**Comment by tzanio** [comment]
@YohannDudouit, do you want to update this?
