### ISSUE TITLE
Mesh::Mesh(const char *filename, ...) fails with cryptic error message if the mesh file does not exist

### ISSUE THREAD

**Issue by cervenal** [mfem/mfem#1742]
When loading a mesh with the Mesh constructor, a user-friendly error message should be shown if the mesh file doesn't exist (at least that seems to be the intent). Instead, the program aborts deep inside `ifgzstream` with this error:
```
terminate called after throwing an instance of 'std::length_error'
terminate called after throwing an instance of '  what():  basic_string::_M_replace_aux
```
This is very confusing and one has to start a debugger just to figure out such a trivial problem...

![Screenshot from 2020-09-03 11-30-22](https://user-images.githubusercontent.com/47257375/92098917-235a5f00-edda-11ea-8844-cf8fcd83fd1e.png)

**Comment by v-dobrev** [comment]
This was an issue some time ago, see https://github.com/mfem/mfem/issues/1412#issuecomment-614330245, however, I think it was resolved in #1502.

Can you check if this is still an issue for you in the `master` branch? If `master` works fine, you can merge it in your branch to resolve the issue.

**Comment by tzanio** [comment]
@cervenal, did you get a chance to try `master` as @v-dobrev suggested above?

**Comment by jakubcerveny** [comment]
I can no longer reproduce this with both MFEM+Laghos master. We must have had an older version of MFEM...
