### ISSUE TITLE
How to plot boundary attributes?

### ISSUE THREAD

**Issue by benzwick** [mfem/mfem#1746]
Is there a way to plot the boundary attribute numbers of a mesh using GLVis or by saving them to a file and using e.g. ParaView to visualize them?

**Comment by tzanio** [comment]
See the "b) View boundary" option in the Mesh Explorer miniapp (in `miniapps/meshing`)

**Comment by benzwick** [comment]
Thanks @tzanio, this works very well for 3D meshes but it does not appear to show the boundary attributes for 2D meshes. For example, for the 3D `beam-hex.mesh` I get the following:

![image](https://user-images.githubusercontent.com/33216696/92551067-b1798e00-f28f-11ea-84e4-cee09d00749e.png)

But, for the 2D `beam-quad.mesh` I get:
 
![image](https://user-images.githubusercontent.com/33216696/92550991-8b53ee00-f28f-11ea-8e16-173f07bff751.png)

Also, for the 3D mesh the material attributes are saved to the VTK file. Is it possible to save the boundary attributes as well?

**Comment by v-dobrev** [comment]
In 2D, to see the different boundary attributes do this: press `m` to hide the mesh and then press `Shift+F9` or `Shift+F10` to switch the boundary attribute that is drawn (as a black line) -- the currently shown boundary attribute will be printed in the terminal. If you do not see the boundary, press `b`/`B`. This behavior and the keys should also work by just opening a mesh directly with GLVis, e.g. with `./glvis -m ../mfem/data/beam-quad.mesh`.

Regarding saving the boundary attributes to VTK: currently we do not save them but if there is a clear convention in VTK how to do that, then I adding this will not be too hard. Is this for visualization purposes, or for recovering the same boundary attributes when saving and then reading a mesh in VTK format?

**Comment by benzwick** [comment]
> Regarding saving the boundary attributes to VTK: currently we do not save them but if there is a clear convention in VTK how to do that, then I adding this will not be too hard. Is this for visualization purposes, or for recovering the same boundary attributes when saving and then reading a mesh in VTK format?

I am using it only for visualization but it could be used for recovering the attributes from a VTK file as well. This would be useful if the mesh was generated using software that can write VTK files, for example as done in FEniCS: https://fenicsproject.org/docs/dolfin/2019.1.0/python/demos/subdomains/documentation.html. The output in ParaView for that example looks like this:
![image](https://user-images.githubusercontent.com/33216696/93043996-12d1a080-f686-11ea-91b4-31fb296e298f.png)

Is it possible to do something similar in MFEM? For example, could I assign the boundary attributes to a grid function with integer values and write that to a file? If yes, what would be the best way to do this assignment?

**Comment by tzanio** [comment]
We certainly have the data, but I'm not sure what's the best way to pass it to ParaView... @pazner do you happen to know?

**Comment by pazner** [comment]
One possibility is to use something like what was proposed in #1779, and output the resulting surface mesh to a VTK file.

**Comment by pazner** [comment]
A preliminary implementation of this feature is available in #1825.

**Comment by tzanio** [comment]
@benzwick, can you take a look at #1825 and let us know if that works for you?

**Comment by benzwick** [comment]
Awesome! This is exactly what I was looking for, thanks @pazner. I tested it with example 21 by adding the following line
```
mesh.PrintBdrVTU("ex21_reference_bdr");
```
and the output for tet, hex and quad meshes is as expected:
![image](https://user-images.githubusercontent.com/33216696/96540739-0e298900-12d1-11eb-8f90-186ff0562d52.png)
![image](https://user-images.githubusercontent.com/33216696/96540928-7bd5b500-12d1-11eb-8b50-39c7098b8360.png)
![image](https://user-images.githubusercontent.com/33216696/96541029-b8a1ac00-12d1-11eb-959a-8278a29d7ba3.png)

**Comment by tzanio** [comment]
Discussion continued in #1825
