### ISSUE TITLE
How to use ConvectionIntegrator() without using a velocity determined by a Void Function ?

### ISSUE THREAD

**Issue by L29430** [mfem/mfem#1748]
Hello ! 

I would like to solve an equation similar to example 9 : d(u)/dt + v.∇u = 0

In this example, the operator to solve (v.∇u) is ConvectionIntegrator(velocity), it uses a velocity determined by a Void Function. In my case, I would like to use a velocity that I solve at each time step in my code. I have v_x and v_y determined in a GridFunction and I would like to use it in ConvectionIntegrator (). Is it possible ?

I thank you in advance for your help,

Kind regards,

LS

**Comment by pazner** [comment]
Yes, this is possible. The velocity can be any `VectorCoefficient`. In particular, you can use `VectorGridFunctionCoefficient` with a grid function that represents the velocity vector field. You will just need to make sure to update and re-assemble your bilinear form every time the velocity changes.

**Comment by L29430** [comment]
Ok thank you, I have two GridFunction : one for v_x and one for v_y. How can I create a VectorGridFunctionCoefficient with both v_x and v_y GridFunction ?

**Comment by pazner** [comment]
I would create a FiniteElementSpace with `vdim` equal to the number of spatial dimensions (i.e. 2 in your case), and then loop over every element and use `GetElementVDofs` to get the DOF indices and then assign the DOFs from `v_x` and `v_y` to the corresponding components of the vector grid function.

**Comment by L29430** [comment]
I may have found another solution, but I have a problem...
I would like to use GradientGridFunctionCoefficient, which is a vector that can go into ConvectionIntegrator().

I originally solve a solution, which I write Ф, the next idea is to solve Grad(Ф) to get my velocities v_x and v_y (Grad(Ф) = V). So I use GradientGridFunctionCoefficient **velocity**(Ф) ----> ConvectionIntegrator(**velocity**). Until then I'm happy !! But... I noticed that according to the Finite Element Space which one uses (Galerkin or Discontinuous Galerkin), the solution is not solved in the same way. In my case, in the Galerkin space, the solved solution is quadratic by élément, and in DG space, it is linear. I don't understand why...

**Comment by pazner** [comment]
Ok, I'm glad you found a solution. Yes, if the components of the velocity are the gradient of a potential function, then you can use `GradientGridFunctionCoefficient`.

I'm afraid I don't understand your second problem. You should be able to use any order elements with both DG and CG.

**Comment by L29430** [comment]
I declare two FiniteElementSpace : 

- FiniteElementCollection *fec_DG = new DG_FECollection(order, dim);   // Discontinuous Galerkin
  FiniteElementSpace *fes = new FiniteElementSpace(mesh, fec_DG); 

  and : 

- FiniteElementCollection *fec_Galerkin = new H1_FECollection(order, dim); // Galerkin
  FiniteElementSpace *fespace = new FiniteElementSpace(mesh, fec_Galerkin);

I solve and I get Ф in Galerkin space. Only I need to get my velocity field on the DG nodes, so I project my Ф solution in the DG space with :   

  GridFunctionCoefficient cdg(&phi_Galerkin);  
  phi_DG.ProjectCoefficient(cdg);


So far I don't seem to have a problem. Now, I want to check if the gradient is solved correctly. I extract my velocities v_x and v_y into two GridFunction (one for values in Galerkin space and the other for DG space). When I visualize v_x or v_y on GLVis, I notice that I don't have the same solution in the DG space as in the Galerkin space.

I tried to send you a screenshot of my results but it doesn't seem to work here. Did you understand my problem ?

**Comment by L29430** [comment]
Another solution might be to solve Grad(Ф) in Galerkin space, with  GradientGridFunctionCoefficient **velocity_G**(Ф) , and then project into DG space to obtain a new GradientGridFunctionCoefficient : **velocity_DG**.  Do you know how can I do this?

**Comment by pazner** [comment]
Generally speaking, the gradient of a grid function in an H1 finite element space will be discontinuous, and so the answer you compute for the gradient in the discontinuous space should be correct. You can of course project this gradient to the H1 space, but that will just be an approximation.

I believe that the `GradientGridFunctionCoefficient` corresponding to `phi_Galerkin` and `phi_DG` in your case should be the same.

**Comment by L29430** [comment]
Well, the GradientGridFunctionCoefficient corresponding to phi_Galerkin and phi_DG is not the same. When I visualize v_x and v_y on GLVIS, I don't have the same result for the H1 space and DG space.

I recall that on the one hand I solve grad(phi) in the H1 space, and on the other hand in the DG space. The results obtained are different. I have the impression that in one case grad(phi) is linear on each element, and in the other case is quadratic.

**Comment by pazner** [comment]
> Well, the GradientGridFunctionCoefficient corresponding to phi_Galerkin and phi_DG is not the same. When I visualize v_x and v_y on GLVIS, I don't have the same result for the H1 space and DG space.

If I understand correctly, you are extracting the gradients of `phi_Galerkin` and `phi_DG` into two grid functions, `v_x` and `v_y`, and these grid functions look different depending on if `v_x` and `v_y` belong to an H1 space or a DG space. This is expected, because the gradient of the grid function will not lie in H1, so it will have to be approximates by a continuous function (on the other hand, the gradient should be recovered exactly in the DG space).

However, visualizing `v_x` and `v_y` in GLVis is not the same thing as visualizing the corresponding `GradientGridFunctionCoefficient`. I don't believe there is a way to visualize a coefficient like that in GLVis. The coefficients corresponding to `phi_Galerkin` and `phi_DG` should be the same, given the information you have provided.

**Comment by L29430** [comment]
Quite the opposite, in fact. Grad (phi) appears to be calculated correctly in H1 space, and it appears to be approximated in DG space. But why don't I get the same values? I do two different operations : 
-  GradientGridFunctionCoefficient **velocity_H1**(&phi_H1) 
-  GradientGridFunctionCoefficient **velocity_DG**(&phi_DG) 

Originally phi is solved in the H1 space and then, I project the solution on the DG nodes. 

When I visualize phi_H1 and phi_DG, the solutions look the same, so why does GradientGridFunctionCoefficient not give the same values in H1 and DG?

The problem : on the one hand I need **velocity_DG** for ConvectionIntegrator(**velocity_DG**) in the DG space. And on the other hand I need to get v_x and v_y for other calculations in the H1 space. So I need **velocity_H1** and **velocity_DG** to be the same.

**Comment by pazner** [comment]
- If you obtain `phi_DG` by projecting `phi_H1`, and if the DG space has order at least as high as the H1 space, then the resulting `GradientGridFunctionCoefficient` will be the same for both. If you would like, I can share a short code that verifies that this is indeed the case.
- There is no restriction that you have to use `velocity_DG` if the `ConvectionIntegrator` is defined on a DG space. You can use `velocity_H1` (or any other vector coefficient), and it should work fine.

You could try to attach your screenshots by either dragging and dropping into the comment field or pasting them.

**Comment by L29430** [comment]
DG space has the same order as the H1 space, that's why I don't understand why I don't get the same results with  GradientGridFunctionCoefficient. Oh yes, I would like the code, thank you ! Impossible to share screenshot with you, it does not work.... 
Do you mean I can use ConvectionIntegrator(velocity_H1) (and not  ConvectionIntegrator(velocity_DG)) while I'm solving the equation in DG space?

**Comment by pazner** [comment]
Yes, you should be able to use any type of vector coefficient, regardless of whether you are solving the equation in DG or H1 spaces.

Here is the code. It shows me that the difference between the two versions of `GradientGridFunctionCoefficient` are of size machine epsilon.
```c++
#include "mfem.hpp"

using namespace mfem;

int main()
{
   Mesh mesh("../data/star-q3.mesh", 1, 1);
   int dim = mesh.Dimension();
   int order = 3;

   DG_FECollection fec_dg(order, dim);
   FiniteElementSpace fes_dg(&mesh, &fec_dg);

   H1_FECollection fec_h1(order, dim);
   FiniteElementSpace fes_h1(&mesh, &fec_h1);

   GridFunction phi_h1(&fes_h1), phi_dg(&fes_dg);
   phi_h1.Randomize();
   phi_dg.ProjectGridFunction(phi_h1);
   // Equivalently:
   //   GridFunctionCoefficient phi_h1_coeff(&phi_h1);
   //   phi_dg.ProjectCoefficient(phi_h1_coeff);

   GradientGridFunctionCoefficient d_phi_h1(&phi_h1), d_phi_dg(&phi_dg);

   double error = 0.0;

   for (int i=0; i<mesh.GetNE(); ++i)
   {
      const IntegrationRule &ir = IntRules.Get(mesh.GetElementBaseGeometry(i), order);
      ElementTransformation &T = *mesh.GetElementTransformation(i);

      for (int j=0; j<ir.Size(); ++j)
      {
         Vector d1(dim), d2(dim);

         d_phi_h1.Eval(d1, T, ir[j]);
         d_phi_dg.Eval(d2, T, ir[j]);

         d1 -= d2;
         error = std::max(error, d1.Normlinf());
      }
   }

   std::cout << error << '\n';

   return 0;
}
```

**Comment by L29430** [comment]
Hello Will,

Thank you very much for your help ! I understood my mistake. 

To sum up : I'm using GradientGridFunctionCoefficient **velocity**(&phi) to get a VectorCoefficient containing the v_x and v_y velocities. I give this vector to ConvectionIntegrator(**velocity**), and I think to update and re-assemble my bilinear for each time step.

I just have one more question, what do lines 393 and 394 in Example 9 mean?

 **adv.SetTime(t);
 ode_solver->Init(adv);**

Do I have to add these two lines in my time loop after each new **FE_Evolution adv (m, k, b)** ?

**Comment by L29430** [comment]
Hello Will,

Thank you very much for your help ! I understood my mistake.

To sum up : I'm using GradientGridFunctionCoefficient **velocity**(&phi) to get a VectorCoefficient containing the v_x and v_y velocities. I give this vector to ConvectionIntegrator(**velocity**), and I think to update and re-assemble my bilinear form for each time step.

I just have one more question, what do lines 393 and 394 in Example 9 mean?

**adv.SetTime(t);
ode_solver->Init(adv);**

Do I have to add these two lines in my time loop after each new **FE_Evolution adv (m, k, b)** ?

**Comment by pazner** [comment]
> Thank you very much for your help ! I understood my mistake.

You're welcome, I'm glad you got it working!

> I just have one more question, what do lines 393 and 394 in Example 9 mean?
> 
> **adv.SetTime(t); ode_solver->Init(adv);**

`adv.SetTime(t)` sets the value of the time variable in the time-dependent system of equations. This is useful if you have, for example, a time dependent coefficient or something similar. By default, the time starts at 0, so this may not be necessary in your case.

`ode_solver->Init(adv)` associates your time-dependent operator with the given ODE integrator. This needs to be called **once**, **before** your time loop.

I would not create a new `FE_Evolution` object every time you update the velocity, I would just add functionality to update and reassemble the bilinear form when the velocity changes. If your velocity changes every step, then you can add `K.Update(); K.Assemble(0);` to the beginning of `FE_Evolution::Mult`.

**Comment by L29430** [comment]
I'm not sure I understand what you mean with K.Update(); K.Assemble(0); to the beginning of FE_Evolution::Mult.

**Comment by pazner** [comment]
Every time the velocity changes, you will have to reassemble the matrix `K` representing the advection operator. This is done by calling `K.Update(); K.Assemble(0);` on the bilinear form `K`.

I don't know how your code is structured, but it may make sense to do this reassembly in `FE_Evolution::Mult`.

**Comment by L29430** [comment]
I have an error message :
'class mfem::SparseMatrix' has no nember named 'Update' / 'Assemble'

**Comment by pazner** [comment]
`K` should be the `BilinearForm` object representing the advection operator, and not the `SparseMatrix`.

**Comment by L29430** [comment]
Oh .. I'm using the old version of the example 9. So these are SparseMatrix...

**Comment by L29430** [comment]
Is it a problem for you if I put :

Fe_Evolution adv(m.SpMat(), k.SpMat())
adv.SetTime(t);
ode_solver->Init(adv); 

in each time step, after giving a new velocity to the matrix K representing the advection operator ?

**Comment by tangqi** [comment]
I have a similar problem. Will reassembly generally be faster than delete the old advection operator and create a new one? @pazner 

My current code looks like (every time when the velocity is updated)
```
gf.SetFromTrueDofs(z);
MyCurlCoefficient velocity(&gf); //a 2D curl
delete Nv;
Nv = new ParBilinearForm(&fespace);
Nv->AddDomainIntegrator(new ConvectionIntegrator(velocity));
Nv->Assemble();
```
I have an implicit scheme with a very large time step. So velocity can be updated maybe 100 times per time step for some hardest problems. It would be nice to know other tricks to accelerate the solver.

Sorry @L29430 for asking questions in this issue. I am only using H1. But the approach described by Will works fine in my code.

**Comment by pazner** [comment]
> Is it a problem for you if I put :
> 
> Fe_Evolution adv(m.SpMat(), k.SpMat())
> adv.SetTime(t);
> ode_solver->Init(adv);
> 
> in each time step, after giving a new velocity to the matrix K representing the advection operator ?

@L29430, I believe this should work, but I haven't tested it myself.

> I have a similar problem. Will reassembly generally be faster than delete the old advection operator and create a new one? @pazner 

The main cost here will be assembly, so I imagine the cost should be relatively comparable.

> I have an implicit scheme with a very large time step. So velocity can be updated maybe 100 times per time step for some hardest problems. It would be nice to know other tricks to accelerate the solver.

@tangqi, in your implicit scheme, do you need access to the advection matrix, or do you just need to apply its action? For explicit methods, you can can get very large speed-ups by using "partial assembly", i.e. not forming the advection matrix (which is expensive), and just computing its action on the fly.

**Comment by tangqi** [comment]
I see the issue. I need to assemble all the matrices and pass them into the Petsc solver to do "physics-based" preconditioning by myself, which takes the majority of the cost anyway. I guess it will not gain me much by accelerating the assembly part. But it is good to know the partial assembly option. Thanks.

**Comment by jandrej** [comment]
@tangqi you need to assemble all matrices that you need for preconditioning. If you decide to drop off diagonal blocks and it works for your physics, you can do that too in the PETSc interface.

**Comment by tangqi** [comment]
@jandrej Thanks a lot for the suggestion, but I do not get what you mean. Can you elaborate it a bit? I am doing all my assembly in Operator->GetGradient, and pass all the matrices to petsc through a giant BlockOperator. 

Thinking about it a bit more, I probably should give partial assembly a try. I am doing a matrix free nonlinear solver. So my F can be evaluated 100 times per time step for some hard cases. I assemble 5-10 operators in each F including a few SUPG operators. The SUPG operators are not easy to do partial assembly by myself.

**Comment by jandrej** [comment]
You can just use JFNK in SNES (`-snes_mf_operator`) and for the preconditioner, you assemble some approximation of your Jacobian. E.g. neglect terms where you know are not important to the Jacobian, or you trial and error.

**Comment by tangqi** [comment]
I see, thanks. The first JFNK and preconditioning part is what I am doing. I will work on optimizing my F then.

**Comment by L29430** [comment]
> > Is it a problem for you if I put :
> > Fe_Evolution adv(m.SpMat(), k.SpMat())
> > adv.SetTime(t);
> > ode_solver->Init(adv);
> > in each time step, after giving a new velocity to the matrix K representing the advection operator ?
> 
> @L29430, I believe this should work, but I haven't tested it myself.

Ok, thank you, but I don't understand how the code can figure out that we need to update and re-assemble k, without re-calling the FE_Evolution function. Is it not enough to add this two lines in FE_Evolution::Mult ? Must a link be needed in the
**int main()** ??

> 
> > I have a similar problem. Will reassembly generally be faster than delete the old advection operator and create a new one? @pazner
> 
> The main cost here will be assembly, so I imagine the cost should be relatively comparable.
> 
> > I have an implicit scheme with a very large time step. So velocity can be updated maybe 100 times per time step for some hardest problems. It would be nice to know other tricks to accelerate the solver.
> 
> @tangqi, in your implicit scheme, do you need access to the advection matrix, or do you just need to apply its action? For explicit methods, you can can get very large speed-ups by using "partial assembly", i.e. not forming the advection matrix (which is expensive), and just computing its action on the fly.

**Comment by pazner** [comment]
> Ok, thank you, but I don't understand how the code can figure out that we need to update and re-assemble k, without re-calling the FE_Evolution function. Is it not enough to add this two lines in FE_Evolution::Mult ? Must a link be needed in the
> **int main()** ??

You shouldn't have to do anything in `main`, but you might need to make some changes so that `FE_Evolution` contains the `BilinearForm` object. This is required to reassemble the matrix. You can look at the new version of ex9 to see how this could work.
