### ISSUE TITLE
Cannot build examples with static PETSC + Makefile

### ISSUE THREAD

**Issue by joshessman-llnl** [mfem/mfem#1755]
Attempting to link an executable when PETSC is enabled results in the following (abbreviated) link command:

```
mpicxx -I/path/to/hypre-2.18.2/include ex1p.cpp -o ex1p -L.. -lmfem -Wl,-rpath,/path/to/hypre-2.18.2/lib -L/path/to/hypre-2.18.2/lib -lHYPRE ... -Wl,-rpath,/path/to/petsc-3.13.4/lib -L/path/to/petsc-3.13.4/lib -lpetsc -lrt -lz
```

Because HYPRE precedes PETSC in the link command, this fails when PETSC is built with HYPRE support - dependencies must follow the things they depend on when linking statically.

From my understanding this is because the [Makefile](https://github.com/mfem/mfem/blob/master/makefile#L213-L214) adds the HYPRE paths/link flag to the link command before the rest of the libraries (including PETSC) are [added to the link line](https://github.com/mfem/mfem/blob/master/makefile#L303).

**Comment by v-dobrev** [comment]
The default value for the PETSc link flags, `PETSC_LIB`, are read from a PETSc config file: https://github.com/mfem/mfem/blob/a40523a7cfe6bb0037311cd46200e2a5eddfc180/config/defaults.mk#L268-L280

Is hypre not exported in the variable `PETSC_EXTERNAL_LIB_BASIC` defined in `$(PETSC_DIR)/lib/petsc/conf/petscvariables`?

**Comment by joshessman-llnl** [comment]
Thanks for clarifying!  It looks like the issue is actually that `PETSC_LIB` is being overwritten here:

https://github.com/spack/spack/blob/e7040467f22e919b3954b8f43f09d37165bd8bf0/var/spack/repos/builtin/packages/mfem/package.py#L476-L480

In the snippet you linked it looks like it would be sufficient to just set `PETSC_DIR`, as `PETSC_OPT` and `PETSC_LIB` are determined from it.

**Comment by v-dobrev** [comment]
Oh, you did not mention that you are using Spack in your first post, so I assumed you are building directly using GNU make.

In the mfem Spack package, yes, I'd expect a static petsc build to have link issues with mfem. The property `spec['petsc'].libs` returns only the petsc library itself without any dependencies, hence the issue. In spack, there is no direct way to query a package for all its dependencies, so we do the simplest thing (link with just what `spec['petsc'].libs` returns) which works with the default shared petsc build.

One think that can be tried, as you said, is to set just `PETSC_DIR` to `spec['petsc'].prefix` and see if that works with the static petsc build. However, I'm not sure `$(PETSC_DIR)/lib/petsc/conf/petscvariables` is always installed in that location, so there's a chance this may not work. If it works, we can update the mfem spack package to support the static petsc build as well.

**Comment by tzanio** [comment]
@joshessman-llnl, were you able to resolve this?

**Comment by joshessman-llnl** [comment]
Yes, the switch to setting `PETSC_DIR` worked, so I opened a spack PR: https://github.com/spack/spack/pull/19326

**Comment by tzanio** [comment]
Alright, I'll close this then. Feel free to reopen if there are related questions.
