### ISSUE TITLE
Add option to output continuous fields in ParaView data collection without duplicate points

### ISSUE THREAD

**Issue by benzwick** [mfem/mfem#1757]
How difficult would it be to add an option to output the mesh and fields in ParaView format without duplicate points? I assume that the duplicate points are only required when using a discontinuous space. The model I am solving has about 6M nodes and the ParaView output has nearly 50M points. This is a lot of duplication and my .vtu binary file is 3GB. Removing the duplicated nodes and data might reduce the file size to about 400MB which would be very nice. I also cannot open the current file without crashing ParaView because the file size is too big.

Alternatively, is there a more suitable output format for very large models that can be opened in ParaView?

Related issues:
- https://github.com/mfem/mfem/issues/1398

**Comment by williamfgc** [comment]
@benzwick I put the adios2 data collection in #1188 which can be visualized in ParaView for constant mesh and nodal fields (I'm working on enabling cell/element centered data in VTK from #1616). It targets large data in MPI cases. Let me know if you have any questions.

**Comment by pazner** [comment]
Adding such a feature is possible, but would certainly require some work (it would, for example, complicate the process of saving both a continuous and discontinuous field defined on the same mesh).

@benzwick, did you enable compression of the data (compiling MFEM with zlib enabled)? You could also try saving in single precision rather than double (using `VTKFormat::BINARY32`).

ParaView should in principle be able to handle files that are gigabytes in size.

**Comment by benzwick** [comment]
@williamfgc that sounds like a good alternative. I tried to use the adios2 output but I had some trouble with installing the required dependencies. I will try to spend some more time on this to get it working and compare it with the ParaView output.

@pazner enabling compression made a huge difference: the file size is now under 400MB. Saving in single precision reduces the file size even further to just under 300 MB.

Thank you very much for these suggestions!

> Adding such a feature is possible, but would certainly require some work (it would, for example, complicate the process of saving both a continuous and discontinuous field defined on the same mesh).

I think that adding a continuous field option would be a useful feature for many applications. For problems that contain both continuous and discontinuous fields users could use two separate data collections instead of saving both types of fields on the same mesh.

**Comment by pazner** [comment]
> I think that adding a continuous field option would be a useful feature for many applications. For problems that contain both continuous and discontinuous fields users could use two separate data collections instead of saving both types of fields on the same mesh.

It could definitely be a useful feature. I don't think there are concrete plans to work on this immediately, but we would definitely be happy to see a PR for this :)
