### ISSUE TITLE
Symmetric Hypre relaxation

### ISSUE THREAD

**Issue by bensworth** [mfem/mfem#1758]
I believe all of the GS Types in the HypreSmoother types,
```
   enum Type { Jacobi = 0, l1Jacobi = 1, l1GS = 2, l1GStr = 4, lumpedJacobi = 5,
               GS = 6, Chebyshev = 16, Taubin = 1001, FIR = 1002
             };
```
in particular types 2, 4, and 6 are all symmetric relaxation schemes. If this is correct, it would be good to specify that because sometimes a symmetric scheme is or is not desirable, and it can be important to know (e.g., necessary for CG).

**Comment by tzanio** [comment]
That is correct, in general Gauss-Seidel in MFEM means symmetric Gauss-Seidel (unless specified otherwise).

Do you want to propose a simple PR to update the documentation?

**Comment by bensworth** [comment]
Sure thing, I will put this on the TODO list,
