### ISSUE TITLE
Assemble Parallel Given Element Matries	

### ISSUE THREAD

**Issue by nghiakvnvsd** [mfem/mfem#1759]
Hi everyone! I have a question when I try to run my project with parallel mesh. When I assemble element matries (serial) with the given matries I can code:
```
for (int i=0; i<TotalElement; i++){
 mfem::BilinearForm::AssembleElementMatrix(i, elmat)
}
```
But ParBilinearForm does not have the function AssembleElementMatrix like it. I would like to ask whether there is a good way to do it with Parallel mesh. 
Thank you!!!

**Comment by wcdawn** [comment]
I don't quite understand your syntax because `AssembleElementMatrix` is a member function of `BilinearForm` so you would need to do something like
```cpp
ParBilinearForm a(fespace);
for (int i=0; i < TotalElement; ++i)
{
  a.AssembleElementMatrix(i, elmat);
}
```

Also, `ParBilinearForm` is inherited from `BilinearForm` so you can call it just them same.

All this being said, if you just want the full parallel matrix, you should us `ParBilinearForm::ParallelAssemble()`.

**Comment by nghiakvnvsd** [comment]
I mean: for examples, I have some dense matries K_1, K_2, ... K_n; I want to assemble them. With FiniteElementSpace, I can code:
BilinearForm a(fespace);
```
for (int i=0; i < n; ++i)
{
  a.AssembleElementMatrix(i,K_i);
}
```
but with ParFiniteElementSpace, when I code like above, It's wrong because it seems to have divided into many parallel parts and each parts include some shared faces. So the result when finishing assemble is wrong. I have no idea about it. May you recommend me a good way to parrallelly assemble n matries?

**Comment by wcdawn** [comment]
Yes. Each parallel process only solves part of the mesh so the mesh has been partitioned using `metis`.

You shouldn't be assembling the global matrix yourself, even for the serial problem. For some problems, you'll use `BilinearForm::Assemble()` and others you'll use `ParBilinearForm::ParallelAssemble()`. You'll want to take a look at `ex1` and `ex1p`.  For parallel, look at [these lines](https://github.com/mfem/mfem/blob/master/examples/ex1p.cpp#L187-L217). For serial, look at [these lines](https://github.com/mfem/mfem/blob/master/examples/ex1.cpp#L162-L189).

You'll then use a parallel solver like the `CGSolver` to solve the problem.

**Comment by nghiakvnvsd** [comment]
> Yes. Each parallel process only solves part of the mesh so the mesh has been partitioned using `metis`.
> 
> You shouldn't be assembling the global matrix yourself, even for the serial problem. For some problems, you'll use `BilinearForm::Assemble()` and others you'll use `ParBilinearForm::ParallelAssemble()`. You'll want to take a look at examples `ex1` and `ex1p`. For parallel, look at [these lines](https://github.com/mfem/mfem/blob/master/examples/ex1p.cpp#L187-L217). For serial, look at [these lines](https://github.com/mfem/mfem/blob/master/examples/ex1.cpp#L162-L189).
> 
> You'll then use a parallel solver like the `CGSolver` to solve the problem.

Thank you for your supporting. I have read the examples you mentioned. I have a question: How can I set another test function. From the examples, the used test function is a basic function. But I want to change it.

**Comment by nghiakvnvsd** [comment]
Thanks for your support
