### ISSUE TITLE
Integrating Directionally Dependent Diffusion-like Term

### ISSUE THREAD

**Issue by wcdawn** [mfem/mfem#1760]
I'm working on solving the even-parity discrete-ordinates neutron transport equation.
The "diffusive" term is not the standard Laplacian. Instead, the following quantity is computed.

<img src="https://i.upmath.me/svg/%20%5Cint_%7BV_e%7D%20a_%7Bij%7D%20%5Cfrac%7B%5Cpartial%20u%7D%7B%5Cpartial%20x_i%7D%20%5Cfrac%7B%5Cpartial%20v%7D%7B%5Cpartial%20x_j%7D%20%5C%3B%20dV%20" alt=" \int_{V_e} a_{ij} \frac{\partial u}{\partial x_i} \frac{\partial v}{\partial x_j} \; dV " />.

<img src="https://i.upmath.me/svg/a_%7Bij%7D" alt="a_{ij}" /> is some constant coefficient (related to an angular quadrature).

Eventually, this is summed up for all spatial dimensions.

<img src="https://i.upmath.me/svg/%20%5Csum_%7Bi%7D%5E%7B%5Cmathrm%7BDIM%7D%7D%20%5Csum_%7Bj%7D%5E%7B%5Cmathrm%7BDIM%7D%7D%20a_%7Bij%7D%20%5Cint_%7BV_e%7D%20%5Cfrac%7B%5Cpartial%20u%7D%7B%5Cpartial%20x_i%7D%20%5Cfrac%7B%5Cpartial%20v%7D%7B%5Cpartial%20x_j%7D%20%5C%3B%20dV" alt=" \sum_{i}^{\mathrm{DIM}} \sum_{j}^{\mathrm{DIM}} a_{ij} \int_{V_e} \frac{\partial u}{\partial x_i} \frac{\partial v}{\partial x_j} \; dV" />.

How should I go about implementing this in MFEM?
It looks similar to a `DerivativeIntegrator` but not quite.

Thanks!

**Comment by rcarson3** [comment]
Maybe I'm missing something but why couldn't you just use the `DiffusionIntegrator` instantiated with a `MatrixConstantCoefficient` if `a_{ij}` is constant across all elements or some child class of `MatrixCoefficient` if that isn't the case, and it does vary across elements?

**Comment by wcdawn** [comment]
Is that so? Maybe I'm missing something. This term includes cross-derivative terms which is different from my typical use of `DiffusionIntegrator` but maybe this would work with a `MatrixCoefficient`. Does this mean that the default use of the `DiffusionIntegrator` would be the same a with a `MatrixCoefficient` with a constant scalar value on the diagonal?

The coefficient does vary across elements but I have already written a `MatrixPWConstCoefficient`.

**Comment by rcarson3** [comment]
Here's the code for the [DiffusionIntegrator::AssembleElementMatrix](https://github.com/mfem/mfem/blob/master/fem/bilininteg.cpp#L507-L556). It by default just does <img src="https://render.githubusercontent.com/render/math?math=\nabla\phi^T"><img src="https://render.githubusercontent.com/render/math?math=\nabla\phi"> at each quadrature point where <img src="https://render.githubusercontent.com/render/math?math=\nabla\phi">  is your shape function gradient term. If you add a `MatrixCoefficient` class to the initialization then it will do <img src="https://render.githubusercontent.com/render/math?math=\nabla\phi^T">**M**<img src="https://render.githubusercontent.com/render/math?math=\nabla\phi"> where M can vary at each quadrature point if you'd like it to. If you passed in a `Coefficient` class then it would just be something like: <img src="https://render.githubusercontent.com/render/math?math=\nabla\phi^T"><img src="https://render.githubusercontent.com/render/math?math=\nabla\phi">_c_

I don't know if this helps any and maybe you already knew this. I'm not at all familiar with your set of PDEs, but they sort of reminded me of some PDEs I was working on which had a form like <img src="https://render.githubusercontent.com/render/math?math=\int_\Omega\nabla\phi^T\mathbf{M}\nabla\phi\Omega">.

**Comment by wcdawn** [comment]
Thanks for the great explanation! It looks like I was definitely over thinking it.

In my PDEs, M is a set of quadrature values for a discrete angular direction. I suppose it is similar to a space metric sense in the space-angle phase space.
