### ISSUE TITLE
How to load ParGridFunction from file?

### ISSUE THREAD

**Issue by benzwick** [mfem/mfem#1767]
I am trying to load some grid functions from files to use as coefficients. So far I can load the data into a `GridFunction` in serial but I am having some trouble parallelizing the code.

I have text files for each grid function where each line corresponds to the value at a vertex of the mesh which I generate using the built-in MFEM mesh generator (I assume the ordering of vertices is the same as my input data which appears to be the case at least for the serial mesh). I then load the data like this:
```
mfem::GridFunction source(fespace);
std::ifstream f("data/source.dat", std::ifstream::in);
source.Load(f, source.Size());
f.close();
```
In parallel, I tried first loading the data in serial using a `GridFunction` and creating a `ParGridFunction` from this as follows:
```
mfem::ParGridFunction psource(pfespace, ssource);
```
where `pfespace` is a `ParFiniteElementSpace` and `ssource` is a `GridFunction` but this does not work.

How can I load data from a text file in a parallel simulation using a `ParGridFunction`?

**Comment by pazner** [comment]
Perhaps the following constructor could be useful for you:
```c++
/** @brief Construct a local ParGridFunction from the given *global*
       GridFunction. If @a partitioning is NULL (default), the data from @a gf
       is NOT copied. */
   ParGridFunction(ParMesh *pmesh, const GridFunction *gf,
                   const int *partitioning = NULL);
```

You can also look at how GLVis loads parallel meshes and grid functions in the function `ReadParMeshAndGridFunction`: https://github.com/GLVis/glvis/blob/95aecd8cf3e3038a36366cef14d5d2986a6a8c1a/glvis.cpp#L1942.

**Comment by benzwick** [comment]
Thanks @pazner that fixed my problem. The constructor I was using (see above) assumes the grid functions are local whereas the one you suggested uses a global grid function which is what I needed.

This [comment](https://github.com/mfem/mfem/issues/1432#issuecomment-623808355) was also helpful.
