### ISSUE TITLE
Read in from a text file to initialize diffusion term

### ISSUE THREAD

**Issue by delcmo** [mfem/mfem#1768]
Hello,

I need to initialize a turbulent diffusion term with values read from a text file both in serial and in parallel. I have one value per element of the mesh (a mesh with 100 elements will have to read in 100 values). Is there a class I can use in MFEM or should I rely on C++ capabilities?

**Comment by vladotomov** [comment]
Can you read it as a 0th-order L2 `GridFunction`?

**Comment by delcmo** [comment]
Answer is in #1767

**Comment by delcmo** [comment]
@vladotomov, what do you mean by a 0th-order L2 `GridFunction`? Is that one diffusion coefficient per mesh element, e.g. all degree of freedoms within an mesh element have the same value?

**Comment by vladotomov** [comment]
Yes, it's a `GridFunction` with 1 dof per element.
