### ISSUE TITLE
Typo in Mesh::AddElement

### ISSUE THREAD

**Issue by dclenz** [mfem/mfem#1769]
There appears to be a typo in the definition of Mesh::AddElement which leads to problematic behavior.  In the check against the element array size, line 1397 of Mesh.cpp is
`   CheckEnlarge(boundary, NumOfBdrElements);
`

This should probably instead be
`   CheckEnlarge(elements, NumOfElements);
`

The code as is breaks periodic meshes, where NumOfBdrElements is always 0.  In this case, CheckEnlarge always increments the boundary element array size, which subsequently causes FinalizeCheck() to fail.

**Comment by tzanio** [comment]
See #1764
