### ISSUE TITLE
A Type of BilinearFormIntegrator

### ISSUE THREAD

**Issue by nghiakvnvsd** [mfem/mfem#1771]
Hello everyone! I'm a newbie using MFEM. I have two questions when I try to solve my problem. 
1.  I have read some type of Type of BilinearFormIntegrator but I don't see the Bilinear form like:
![image](https://user-images.githubusercontent.com/68639058/93706790-deb61e00-fb64-11ea-8d08-d7e0c86ff8fd.png)

where,

![image](https://user-images.githubusercontent.com/68639058/93706488-a234f300-fb61-11ea-8fbb-34351fef775e.png)

and 

![image](https://user-images.githubusercontent.com/68639058/93706509-e0321700-fb61-11ea-95be-c4007216e9a3.png)

Or in 3D:
 
![image](https://user-images.githubusercontent.com/68639058/93707194-656bfa80-fb67-11ea-8ac5-e6a9ce8a1f13.png)

and 

![image](https://user-images.githubusercontent.com/68639058/93707259-c693ce00-fb67-11ea-9de1-84c52bd8b17f.png)

with E and \nu are constants (The Young's modulus and The Poisson's ratio respectively)

Maybe It's available but I do not have enough knowledge. May you help me to point out it? And if it is not available, may you help me to build it?

2. When I have already implemented the question 1, How can I change the value of each element by a matrix? For examples:

Assume that I have the mesh nelx * nely (rectangle), elements K_0, ... K_(nelx*nely-1) and the matrix A(nelx, nely).
I want to change the elements by:   A(0,0)*K_0, A(0,1)*K_1, ... A(nelx-1,nely-1)*K_(nelx*nely-1).

My English is so bad and I hope you guys can understand my question. Thank youuuuu!

**Comment by nghiakvnvsd** [comment]
I have just resolved the question 1. It is a consequence of ElasticityIntegrator. The question 2 is very important for me and I have no idea to solve it. Actually, it is a part of topology optimization problem. Is there everyone to help me?

**Comment by barker29** [comment]
If I understand your question correctly, I think what you're looking for are the `Coefficient` arguments to the `ElasticityIntegrator`. If you look at `examples/ex2.cpp` around line 178 you can see how we set this up for piecewise constant Lame coefficients lambda and mu. It is also possible to have more complicated varying or even anisotropic coefficients. Is this what you are looking for or did I misunderstand your question?

**Comment by nghiakvnvsd** [comment]
> If I understand your question correctly, I think what you're looking for are the `Coefficient` arguments to the `ElasticityIntegrator`. If you look at `examples/ex2.cpp` around line 178 you can see how we set this up for piecewise constant Lame coefficients lambda and mu. It is also possible to have more complicated varying or even anisotropic coefficients. Is this what you are looking for or did I misunderstand your question?

You are right. I have done it. Thank you for support!!!

**Comment by nghiakvnvsd** [comment]
> If I understand your question correctly, I think what you're looking for are the `Coefficient` arguments to the `ElasticityIntegrator`. If you look at `examples/ex2.cpp` around line 178 you can see how we set this up for piecewise constant Lame coefficients lambda and mu. It is also possible to have more complicated varying or even anisotropic coefficients. Is this what you are looking for or did I misunderstand your question?

Sorry but I haven't resolved in this problem yet. Can you tell me briefly about the matter you said. What Coefficient do I have to use to solve my problem? I try to use  PWConstCoefficient but it doesn't change.

**Comment by nghiakvnvsd** [comment]
Maybe I have to change the number of attributes, right? from my question, the number of attributes have to be nelx*nely? Sorry to bother you.

**Comment by hedashua** [comment]
dear author, I meet with the same problems, could you tell me how do you solve it?

**Comment by hedashua** [comment]
@barker29 do you know how to have varying or even anisotropic coefficients? I just want to set lame=vE/((1+v)(1-2v))，E is calculated as the inverse of the distance between the interior node 
and the nearest boundary，v=0.5

**Comment by hedashua** [comment]
@v-dobrev ,it's helpful for me, thank you for your detailed reply!
