### ISSUE TITLE
How to get the element to edge dofs for quadratic triangular element?

### ISSUE THREAD

**Issue by kailaix** [mfem/mfem#1772]
I am working with a 2D quadratic triangular finite element mesh. I want to get the corresponding element to edge DOF map for each triangle. The order should correspond to the shape function values calculated by `CalcPhysShape`. How can I do that? Thank you.

**Comment by tzanio** [comment]
Can you clarify what are you ultimately trying to achieve?

Typically you don't need such local operations...

**Comment by kailaix** [comment]
I am developing a package that reuses some codes in MFEM for assembling stiffness matrices (basically I looped over elements and calculated contributions myself, and used shape functions from MFEM). Currently, I manually assign the DOF map as a workaround but it's guesswork (which may break for newer versions of MFEM). I'm not sure if there is a better way to do that.

**Comment by tzanio** [comment]
I see.

If you are using MFEM only for the local element matrices and have you own local element DOF to global DOF mapping, then it should be enough to know the numbering of DOFs on the reference element.

In MFEM we number the reference element DOFs as follows: first all DOFs associated with vertices (according to the reference vertex numbering); then all DOFs associated with vertices (according to the reference edge numbering and in the direction of the edge); then all DOFs associated with faces (according to the reference face numbering and in the direction determined by the face normal); and finally all DOFs associated with the element interior.

You can find the numbering of reference vertices, edges and faces in `fem/geom.cpp`. Here it is for example, for triangular edges: https://github.com/mfem/mfem/blob/master/fem/geom.cpp#L768

Hope this helps,
Tzanio

**Comment by kailaix** [comment]
That's exactly what I need. I guess you mean "...then all DOFs associated with ~~vertices~~ **edges** (according to the...".
Thanks!
