### ISSUE TITLE
Error when removing dirichlet nodes in convection matrix

### ISSUE THREAD

**Issue by F3dR19** [mfem/mfem#1775]
Hi all,

I'm trying to solve a simple advection-reaction-diffusion equation which includes dirichlet BC, and noticed that the code crashes with error `SparseMatrix::EliminateRowCol #4` for some specific combinations of parameters.
The error seems to be triggered by the [omonimous function](https://mfem.github.io/doxygen/html/sparsemat_8cpp_source.html#l01789), invoked during the linear system assembly, and specifically when the row/cols corresponding to the Dirichlet nodes are being simplified. I created a simple MWE reproducing the error: [MWE_bug.zip](https://github.com/mfem/mfem/files/5256931/MWE_bug.zip).

Reverse-engineering the code, it seems to me that in order to work _this function implicitly relies on the sparsity pattern of the underlying matrix being symmetric_, which if I'm not mistaken is not safe, when using non-symmetric operators?

Indeed the error is only triggered when the parameters makes it so that this assumption doesn't hold (the full matrix can be printed by uncommenting a few lines on the code: a quick look at its sparsity shows that three of its entries are not mirrored). In all fairness, these rogue entries are ~1e-16, so the problem can be circumvented by dropping small entries in the matrix. Still, since the target application is such a basic problem, I thought it would be worth pointing out the possible issue.

I'm also very much new to MFEM, so I might have made the silliest mistakes / ignored common practices when implementing my code? In which case I apologise, and thank you in advance for any advice on how to improve it!

**Comment by tzanio** [comment]
I'm posting your example here for easier reference:

```c++
#include "mfem.hpp"
#include <string>
//---------------------------------------------------------------------------
using namespace std;
using namespace mfem;
//---------------------------------------------------------------------------
// velocity field
void wFun(const Vector & x, const double t, Vector & w){
   double xx(x(0));
   double yy(x(1));
   w(0) = - 10*t * 2.*(2*yy-1)*(4*xx*xx-4*xx+1); // (-t*2.*yy*(1-xx*xx) mapped from -1,1 to 0,1)
   w(1) =   10*t * 2.*(2*xx-1)*(4*yy*yy-4*yy+1); // ( t*2.*xx*(1-yy*yy) mapped from -1,1 to 0,1)
}
//---------------------------------------------------------------------------
int main(int argc, char *argv[])
{
   // Pb parameters
   const int ordU = 2;
   const int refLvl = 2;
   const double dt = 0.5;
   const double Pe = 1.;
   const std::string meshName = "./tri-square-mod.mesh";


   // Import and refine mesh
   Mesh *mesh = new Mesh( meshName.c_str(), 1, 1 );
   for (int i = 0; i < refLvl; i++)
      mesh->UniformRefinement();
   const int dim = mesh->Dimension();

   // Initialise FE info
   FiniteElementCollection *VhFEColl  = new H1_FECollection( ordU, dim );
   FiniteElementSpace      *VhFESpace = new FiniteElementSpace( mesh, VhFEColl );

   // Extract nodes corresponding to Dirichlet BC (whole boundary)
   Array<int> essVhTDOF;
   if ( mesh->bdr_attributes.Size() > 0 ) {
      Array<int> essBdrV( mesh->bdr_attributes.Max() );
      essBdrV = 0;
      for ( int i = 0; i < mesh->bdr_attributes.Max(); ++i ){
         if( mesh->bdr_attributes[i] == 1 )
            essBdrV[i] = 1;
      }
      VhFESpace->GetEssentialTrueDofs( essBdrV, essVhTDOF );
   }


   // Assemble bilinear form: dt*Pe*(w,grad(u))
   BilinearForm* wVarf =  new BilinearForm( VhFESpace);
   VectorFunctionCoefficient wFuncCoeff( dim, wFun );
   wFuncCoeff.SetTime( dt*7 );						// only this instant gives issues
   double PeDt = Pe*dt;
   wVarf->AddDomainIntegrator(new ConvectionIntegrator( wFuncCoeff, PeDt ));
   wVarf->Assemble();
   wVarf->Finalize();

   // Print full matrix
   // std::ofstream myfile;
   // std::string myfilename = "./bugMatrix.dat";
   // myfile.open( myfilename );
   // (wVarf->SpMat()).PrintMatlab(myfile);
   // myfile.close( );


   // Assemble reduced system
   GridFunction dummyBC(VhFESpace);
   dummyBC = 0.;

   SparseMatrix W;
   Vector dummy1(wVarf->NumRows()), dummy2(wVarf->NumRows()), dummy3(wVarf->NumRows());
   dummy1 =0.; dummy2 =0.; dummy3 =0.;
   wVarf->FormLinearSystem( essVhTDOF, dummyBC, dummy1, W, dummy2, dummy3 );


   delete wVarf;
   delete VhFESpace;
   delete VhFEColl;
   delete mesh;

   return 0;
}
```

**Comment by barker29** [comment]
I suspect if you replace `wVarf->Assemble()` with `wVarf->Assemble(0)` in your code this error will go away, as then the integrator will include explicit zeros in the matrix so that it will be structurally symmetric. Another possible solution is to do the elimination "manually", something like this:
```C++
   mfem::Array<int> cols(jac.Height());
   cols = 0;
   for (int i = 0; i < ess_tdof_list.Size(); ++i)
   {
      cols[ess_tdof_list[i]] = 1;
   }
   jac.EliminateCols(cols, &boundary_values, &rhs);
   for (int i = 0; i < ess_tdof_list.Size(); ++i)
   {
      jac.EliminateRow(ess_tdof_list[i], mfem::Matrix::DIAG_ONE);
      rhs(ess_tdof_list[i]) = boundary_values(ess_tdof_list[i]);
   }
```
where `jac` is the assembled `SparseMatrix` without boundary conditions applied.
