### ISSUE TITLE
trouble building parallel version of mfem-3.4

### ISSUE THREAD

**Issue by pkgudla** [mfem/mfem#1778]
Hi,

I'm trying to install mfem-3.4 on a university cluster.

Following the instructions on mfem.org/building

Serial version (i.e mfem-3.4 & glvis-3.4) is installed
hypre-2.16.0 is installed 
metis-4.0.3 is installed

when I execute following command to install parallel version of mfem using the command;
~/mfem-3.4> make parallel -j

installation fails and the output is pasted below. Any help troubleshooting this will be greatly appreciated.

Thank you

_______________________________________
Output on terminal
________________________________________

make parallel -j
make -f makefile config MFEM_USE_MPI=YES MFEM_DEBUG=NO \
   
make[1]: Entering directory `/users/PYS0404/com0720/MFEM/MPI/mfem-3.4'
make -C config all
make[2]: Entering directory `/users/PYS0404/com0720/MFEM/MPI/mfem-3.4/config'
mpicxx -I../../hypre-2.10.0b/src/hypre/include get_hypre_version.cpp -o get_hypre_version
get_hypre_version.cpp(12): catastrophic error: cannot open source file "HYPRE_config.h"
  #include "HYPRE_config.h"
                           ^

compilation aborted for get_hypre_version.cpp (code 4)
make[2]: *** [get_hypre_version] Error 4
make[2]: Leaving directory `/users/PYS0404/com0720/MFEM/MPI/mfem-3.4/config'
make[1]: *** [local-config] Error 2
make[1]: Leaving directory `/users/PYS0404/com0720/MFEM/MPI/mfem-3.4'
make: *** [parallel] Error 2

**Comment by camierjs** [comment]
It seems that even if `hypre-2.16.0` and `metis-4.0.3` are installed on the cluster, you should make sure that the directory structure is valide, as described in the [Building MFEM](https://mfem.org/building/) page or in the [INSTALL](https://raw.githubusercontent.com/mfem/mfem/master/INSTALL) file.

By default `MFEM` (from `config/defaults.mk`) will use the `../hypre` directory. You can use the cluster one by pointing to it with by setting the `HYPRE_DIR` variable: `make parallel -j HYPRE_DIR=/usr/local/hypre/2.16.0` for example if it was installed there.

**Comment by tzanio** [comment]
As @camierjs pointed out, please follow the building instructions above and let us know if you are still having trouble.
