### ISSUE TITLE
Extracting a surface mesh from an existing volume mesh

### ISSUE THREAD

**Issue by jehicken** [mfem/mfem#1779]
Hello,

**Background**: I plan to use an `mfem` surface mesh to represent a geometry (e.g. for design optimization, but also for other tasks).  There are two constructions I will need: i) build the surface mesh from scratch and ii) extract it from an existing volume mesh.

**Question**: Before I write a bunch of code for case ii), _is there existing code for extracting a surface mesh from an existing volume mesh_ (perhaps on a development branch)?  Note that I will need both the linear mesh and the high-order nodes.

Thank you.

**Comment by tzanio** [comment]
I believe @mlstowell wrote something for ii) in the Mesh Explorer miniapp. See

https://github.com/mfem/mfem/blob/master/miniapps/meshing/mesh-explorer.cpp#L143

**Comment by jehicken** [comment]
This looks to be exactly what I need.  Thanks @tzanio!
