### ISSUE TITLE
Segmentation fault for shared face with master

### ISSUE THREAD

**Issue by vikramsg** [mfem/mfem#1780]
Hi,

I seem to be having an issue with master that I did not have before. I isolated it to a particular line and I am sharing the relevant parts here. 

```
for (int i = 0; I < pmesh->GetNSharedFaces(); i++) 
{
  T  = pmesh->GetSharedFaceTransformations(i);
  el = fes.GetFaceNbrFE(T -> Elem2No);
}
```

This used to work fine with MFEM 3.4 and 4.0, but not with master. Any pointers on what might be the issue.

**Comment by pazner** [comment]
Hi Vikram,

This is probably caused by the change in numbering from #1491. It should be now that `T->Elem2No >= mesh.GetNE()`, and (assuming this is the case), you can get the face neighbor index by subtracting the number of (local) mesh elements.

**Comment by vikramsg** [comment]
Hi Will,
Thanks. For now I am using older versions, but if I face this issue again, I will check based on what you suggested.
