### ISSUE TITLE
How to use Example 1 - Laplace Problem - in DG?

### ISSUE THREAD

**Issue by L29430** [mfem/mfem#1782]
Hello !

I would like to solve the Laplace problem (Example 1) in a DG space. Is it possible ?
The problem appears on the following lines :

    Array <int> ess_tdof_list;
    if (mesh.bdr_attributes.Size ())
    {
       Array <int> ess_bdr (mesh.bdr_attributes.Max ());
       ess_bdr = 1;
       fespace.GetEssentialTrueDofs (ess_bdr, ess_tdof_list);
    }

In a DG space, there are no nodes at the boundaries, so how to impose boundary conditions?

Kind regards,

LS

**Comment by psocratis** [comment]
Hi @L29430 , 

For a DG space, special integrators are used to impose essential BCs (see `DGDirichletLFIntegrator` ). 
You can also find a DG implementation for the Poisson problem in `/tests/convergence/rates.cpp` (for prob = 3).

Best, 

Socratis

**Comment by L29430** [comment]
Hi Socratis,

I can't find the following path : /tests/convergence/rates.cpp.

Effectively, I I tried to help myself from example 14, but I have a problem. I would like to impose a Dirichlet condition on an edge of my domain. But I don't want to impose a constant, but a function depending on x, y. This boundary condition is modified at each time step. On the other edges of the domain, I would like to impose a homogeneous Neumann condition.
I don't know how to do that with DGDirichletLFIntegrator...

**Comment by tzanio** [comment]
> I can't find the following path : /tests/convergence/rates.cpp.

Please pull the latest version of the `master` branch.

**Comment by pazner** [comment]
> Effectively, I I tried to help myself from example 14, but I have a problem. I would like to impose a Dirichlet condition on an edge of my domain. But I don't want to impose a constant, but a function depending on x, y. This boundary condition is modified at each time step.

`DGDirichletLFIntegrator` takes a `Coefficient` which represents the Dirichlet BC as a parameter. This coefficient can be a spatially varying function (e.g. `FunctionCoefficient`). If you change the BC, you will just have to reassemble the RHS linear form.

 > On the other edges of the domain, I would like to impose a homogeneous Neumann condition. I don't know how to do that with DGDirichletLFIntegrator...

Homogeneous Neumann BCs are imposed "naturally" by omitting the `DGDirichletLFIntegrator` and `DGDiffusionIntegrator` terms on the Neumann boundaries. You can do this by passing a `bdr_marker` array (with 1 indicating Dirichlet boundaries, and 0 indicating Neumann boundaries) to `AddBdrFaceIntegrator` when constructing the linear and bilinear forms.

**Comment by L29430** [comment]
Thank you for your help. I would like to use BCs solved at each time step in my main{}, so I can't use FunctionCoefficient. I tried to use GridFunctionCoefficient but I have an error : 

Verification failed: (i < mesh->GetNE()) is false:
---> Invalid element id 9, maximum allowed 3
... in function: const mfem//FiniteElement* mfem//FiniteElementSPace::GetFE(int) const
... in file: fem/fespace.cpp:1646

Abandon(core dumped)

**Comment by chang-yiyi** [comment]
Hi @L29430 ,

Maybe you got the same situation with me [here](https://github.com/mfem/mfem/issues/1801#issue-714688724), but I am not sure.

**Comment by tzanio** [comment]
@L29430, were you able to resolve this?
