### ISSUE TITLE
Couldn't run case with large mesh (~8 mln cells) in parallel mode 

### ISSUE THREAD

**Issue by vkorchagova** [mfem/mfem#1783]
Hello everyone,

I try to run MFEM examples (9 and 18)  with a big mesh (near 8 mln hexagonal cells). When I run a code, after several minutes I see an error: one of the processes has been killed. I see that the process has been killed during mesh reading. I haven't any problem with 1 mln cells or less. Where should I find a source of this problem? How to deal with big meshes correctly? 
Mesh format is .msh

--
Best regards, Victoria

**Comment by tzanio** [comment]
Hi @vkorchagova,

You may be running out of memory. Can you start with a coarser mesh and refine in parallel? Alternatively, can you run on a machine with more RAM?

Tzanio
