### ISSUE TITLE
How to use non-linear model

### ISSUE THREAD

**Issue by oren186** [mfem/mfem#1786]
Hi,
I am new to MFEM and a bit new to C++, and I would like to ask for help or guidance for a start.
I am trying to solve a simple case of a cantilever beam with force. However unlike in ex2 I am trying to use neo-hookean model (non-linear).
I tried to use issues: #526, #109, and #10, but  I couldn't make it work. I tried to work on ex. 10, but maybe I need to insert the neo-hookeam model on ex 2 (if it simpler)?

I can upload what I did until now if it will help.

Oren

**Comment by tzanio** [comment]
It sounds like Example 10 is exactly what you are trying to do. Can you clarify why it is not working for you?

Unlike the case of linear elasticity in Example 2, the Neo-Hookean model is nonlinear, and so it requires more complicated machinery...

**Comment by oren186** [comment]
Thank you for the fast response,

Yes, I will try to clarify,

Inorder to insert the force I used:
```C++   
VectorArrayCoefficient ff(dim);
    for (int i = 0; i < dim - 1; i++) {
        ff.Set(i, new ConstantCoefficient(0.0));
    }
    {
        Vector pull_force(mesh->bdr_attributes.Max());
        pull_force = 0.0;
        pull_force(1) = 1.0; // the force works on boundary 2
        ff.Set(2, new PWConstCoefficient(pull_force));
    }
    LinearForm *bb = new LinearForm(&fespace);
    bb->AddBoundaryIntegrator(new VectorBoundaryLFIntegrator(ff));
    bb->Assemble();
Vector BB;
```

and adding vector BB to the HyperelasticOperator 
```C++ 
 HyperelasticOperator oper(fespace, ess_bdr, visc, mu, K, BB, bb);
```
 and in the function i added:
```C++    
 GridFunction xx(&fespace); //temp
    xx = 0.0; //values for the essential b.c
    Vector XX; //temp
    M.FormSystemMatrix(ess_tdof_list, tmp);
    M.FormLinearSystem(ess_tdof_list, xx, *bb, tmp, XX, BB);
```
and
```C++ 
z += _BB;
```

For representing the stress I did as "v-dobrev" said in #109

and this is the results:
![image](https://user-images.githubusercontent.com/65160738/94428747-f3646880-0199-11eb-8688-1a709f02b301.png)

as you can see something is wrong, the stress is not right and I don't have representation of the force. (I tried different force values to see if it is a problem in the limits, but I get the same result every time.

This is the full file (if i missed something)
[learn_ex10.txt](https://github.com/mfem/mfem/files/5292102/learn_ex10.txt)

Oren

**Comment by v-dobrev** [comment]
Your modifications seem fine.

Did you try pressing "space" in the GLVis windows? Initially they are paused at `t=0`.

**Comment by tzanio** [comment]
Hi @oren186, were you able to resolve this?

**Comment by oren186** [comment]
Unfortunately no.
I tried pressing space, it wrote "running" in the command line but nothing happened.

**Comment by tzanio** [comment]
It is not clear what's the source of the problem... 

Can you maybe post your full code and sample runs that don't work?

**Comment by oren186** [comment]
yes, I have already uploaded it on my previous comments as a txt file, and it runs with the simple mesh in 3d (hex mesh from examples) (if I need to upload different file format I will)
Thank you very much
Oren

**Comment by bslazarov** [comment]
Hi Oren,

Did you try to set the coefficient to be 1 in direction 0(1) instead of
1(2)? It seems that the RHS of the problem is zero.

**Comment by oren186** [comment]
Hi, Thank you for responding :)
Can you point me more directly? I think I got confused on which coefficient you meant.
Oren

**Comment by bslazarov** [comment]
Try to change the force in directions x (direction 0), y(direction 1), or
z(direction 2).
