### ISSUE TITLE
Example 9 : How can I recover the vector **y** of the function FE_Evolution :: Mult ().

### ISSUE THREAD

**Issue by L29430** [mfem/mfem#1791]
Hello everyone !

In example 9, I'm trying to code my own RK2 scheme, for that I need to get the values: du / dt = - v.Grad (u).

So, the idea would be to recover the **y** vector of the function FE_Evolution :: Mult (). How can I do this ?

I can't use a simple FunctionCoefficient (FE_Evolution :: Mult) in the main {}.

Kind regards,

LS

**Comment by vladotomov** [comment]
Hi LS,

The easiest way to do this would be to create a class that inherits `ODESolver`, and define you custom time integration scheme inside its virtual `Step(...)` function, similar to the implementations in `linalg/ode.cpp`. Then you can use the `FE_Evolution` object from example 9 (called `adv` there) by calling `my_ode_solver.Init(adv)`. By doing this, every call to `f->Mult(...)` inside your ODESolver would be using the `TimeDependentOperator` `FE_Evolution`.

I hope this helps,
Vladimir

**Comment by LeilaSalomon** [comment]
Hi Vladimir,

Thank you for your answer but my question is as follows : 

How can I retrieve the **y** vector values (du/dt) obtained in FE_Evolution :: Mult () ? I would like use these values in my **int main{ }**.

**Comment by vladotomov** [comment]
Hi Leila,

I'm not sure what you mean by that. For example in a RK3 time integrator, the `FE_Evolution::Mult()` will get called 3 times, producing three different `y` values.

You can probably write your own `ODESolver` that's very similar to the existing ones,  but has additional mechanism for saving / extracting these values.

I hope this helps,
Vladimir

**Comment by LeilaSalomon** [comment]
Hi Vladimir,

The idea is to stay with a first-order method (ode_solver_type = 1) :  FE_Evolution::Mult() will get called just one time, producing one y value.

I would just like to get the y values of FE_Evolution::Mult() to use them in my code. The idea is to code my RK2 in my main{} code to solve a coupled system. I don't know if you know what I mean?

**Comment by vladotomov** [comment]
Hi Leila,

If you are sure that you'll always use a fixed first-order method, the easiest thing is to simply copy the code from the corresponding `ODESolver::Step()` function into your `main()`, which would give you access to all temporary `Vectors`.

But if you need a more flexible interface, you probably need to do what I wrote in the previous comment.

I hope this helps,
Vladimir

**Comment by LeilaSalomon** [comment]
> Hi Leila,
> 
> If you are sure that you'll always use a fixed first-order method, the easiest thing is to simply copy the code from the corresponding `ODESolver::Step()` function into your `main()`, which would give you access to all temporary `Vectors`.
> 
> But if you need a more flexible interface, you probably need to do what I wrote in the previous comment.
> 
> I hope this helps,
> Vladimir

Hi Vladimir,

But, I would like to access to FE_Evolution::Mult() vectors.
