### ISSUE TITLE
How to make two boundaries periodic 

### ISSUE THREAD

**Issue by makrandak** [mfem/mfem#1793]
Hello all, 

This might be a trivial question, but I did not find something on this.  I am using the `inline-quad.mesh`  mesh from the data folder and I think it has default boundary attributes `0` for bottom `1` for right `2` for top and `3` for left boundaries.  Is there a way I can make the `top` and `bottom` boundaries periodic? I am trying to solve sod shock problem using this mesh and it is essentiall 1D so I want the top and bottom boundaries to be periodic. 

Also, how are the simple meshes in `/data` folder generated. Is there a standard script for generating the `.mesh` files ? Are they hand coded?

**Comment by pazner** [comment]
> This might be a trivial question, but I did not find something on this. I am using the `inline-quad.mesh` mesh from the data folder and I think it has default boundary attributes `0` for bottom `1` for right `2` for top and `3` for left boundaries. Is there a way I can make the `top` and `bottom` boundaries periodic? I am trying to solve sod shock problem using this mesh and it is essentiall 1D so I want the top and bottom boundaries to be periodic.

This can be accomplished using some functions that @mlstowell has written (`IdentifyPeriodicMeshVertices` and `MakePeriodicMesh`). They are available in a branch of MFEM, not in master. See [his comment here](https://github.com/mfem/mfem/issues/1256#issuecomment-578533108).

It would be great it this functionality could make it into master.

**Comment by makrandak** [comment]
Hello Will, 

Sorry I could not reply earlier, I was trying multiple approaches.  I was able to just manually create a mesh, by replicating the structure in the fully periodic mesh.  Although, I will look at the code in #issue1256, I will keep that in mind for the future.  Thanks for your help.

I am pasting the mesh file here if someone else wants to use it.  And I am closing the issue. 

```
MFEM mesh v1.0

# Periodic top and bottom boundaries, left and right boundaries have attributes 1 and 2
#
# MFEM Geometry Types (see mesh/geom.hpp):
#
# POINT       = 0
# SEGMENT     = 1
# TRIANGLE    = 2
# SQUARE      = 3
# TETRAHEDRON = 4
# CUBE        = 5
#

dimension
2

# format: <attribute> <geometry type> <vertex 0> <vertex 1> ...
elements
9
1 3 0 1 5 4
2 3 1 2 6 5
3 3 2 3 7 6
4 3 4 5 9 8
5 3 5 6 10 9
6 3 6 7 11 10
7 3 8 9 1 0
8 3 9 10 2 1
9 3 10 11 3 2

boundary
6
1 1 0 4
1 1 4 8
1 1 8 0
2 1 3 7
2 1 7 11
2 1 11 3

vertices
12

nodes
FiniteElementSpace
FiniteElementCollection: L2_T1_2D_P1
VDim: 2
Ordering: 1

-1 -1
-0.333333333 -1
-1 -0.333333333
-0.333333333 -0.333333333

-0.333333333 -1
+0.333333333 -1
-0.333333333 -0.333333333
+0.333333333 -0.333333333

+0.333333333 -1
+1 -1
+0.333333333 -0.333333333
+1 -0.333333333

-1 -0.333333333
-0.333333333 -0.333333333
-1 +0.333333333
-0.333333333 +0.333333333

-0.333333333 -0.333333333
+0.333333333 -0.333333333
-0.333333333 +0.333333333
+0.333333333 +0.333333333

+0.333333333 -0.333333333
+1 -0.333333333
+0.333333333 +0.333333333
+1 +0.333333333

-1 +0.333333333
-0.333333333 +0.333333333
-1 +1
-0.333333333 +1

-0.333333333 +0.333333333
+0.333333333 +0.333333333
-0.333333333 +1
+0.333333333 +1

+0.333333333 +0.333333333
+1 +0.333333333
+0.333333333 +1
+1 +1
```
