### ISSUE TITLE
Reusing HypreSmoother with lumped Jacobi option

### ISSUE THREAD

**Issue by v-dobrev** [mfem/mfem#1795]
Changing the type to 1 from 5 in this section: https://github.com/mfem/mfem/blob/bf3f1f1327f064baae40693256c9559feae1a99a/linalg/hypre.cpp#L2265-L2272

will switch the smoother type from "lumped Jacobi" to "l1-scaled Jacobi" after the first call to `SetOperator`. This is not the right behavior when the same `HypreSmoother` object is reused with different matrices.

**Comment by tzanio** [comment]
See #1802

**Comment by tzanio** [comment]
Discussion continued in #1802
