### ISSUE TITLE
Evaluating GridFunctionCoefficient on a boundary face of a low order refined mesh 

### ISSUE THREAD

**Issue by smsolivier** [mfem/mfem#1797]
I am trying to implement a low order refined (LOR) preconditioner where the coefficients in the bilinear and linear forms are complicated `Coefficient` objects involving operations on `GridFunctionCoefficient` objects. I'm hoping to directly use the high order interpolation in the evaluations instead of making approximations such as projecting the HO function onto the LOR space. Since `GridFunctionCoefficient` evaluations are used, a mapping between the LOR and parent *reference* spaces is required. 

My goal is to create a `LORCoefficient` that wraps calls to `Coefficient::Eval` with transforms from the LOR reference space to the parent reference space. Wrapping the coefficients avoids having to re-implement the complicated coefficients to have a LOR version. I have accomplished this for elements (`ElementTransformation::ELEMENT`) by using `Mesh::GetRefinementTransforms` and a suitably defined `IntegrationPointTransformation`. However, I also have boundary bilinear and linear forms and am not sure how to implement the LOR mapping for boundary elements (`ElementTransformation::BDR_ELEMENT`). As in MFEM, "boundary element" refers to elements on the boundary of the domain that are one dimension lower than the mesh's dimension and "element" is the usual full dimensional element. 

Is there a way in MFEM to evaluate a `GridFunctionCoefficient` defined on the original high-order space from a *boundary* element of a low order refined space? This would involve: 
1. Identifying the parent boundary element corresponding to the LOR boundary element, 
2. Transform an integration point in the LOR boundary element's reference space to the parent's reference space (using `IntegrationPointTransformation`), 
3. Transform the parent's boundary integration point to an elemental integration point and interpolate using the shape functions (using `GridFunction::GetValue`). 

2 and 3 are already implemented but I'm not sure the best way to accomplish 1. I think modifying `CoarseFineTransformations` to also store the relationship between the LOR boundary element and the parent boundary element in addition to the LOR element and parent element would be the cleanest solution. How difficult would this be to implement? I'm imagining it might be complicated by face orientations and supporting all the different geometries. Is this functionality something the MFEM team would like to have? I'm sure I can hack something together through re-implementing the coefficient and/or integrator but I think this would be unnecessary code duplication. Any advice would be great. 

Thanks, 
Sam

**Comment by tzanio** [comment]
@pazner did you get a chance to look at this? Do you think it is something we should support?

**Comment by pazner** [comment]
Hi Sam,

Sorry it took so long to respond. This fell between the cracks.

Perhaps another way to achieve the same effect would be to transform the point from the LOR boundary element to the LOR volume element. Then, you can identify the parent high-order element, and treat this case just like `ElementTransformation::ELEMENT`. Do you think that would work?

**Comment by smsolivier** [comment]
Hey Will, 
No worries! That is a possibility but it is a bit complicated since the boundary coefficients are functions of the normal vector. Ideally, I could pass in the boundary element to the coefficient and use `CalcOrtho` on the rectangular Jacobian matrix to get the normal. I could however add a `SetNormal` function to the coefficient and then pass in the volumetric transformation by modifying the integrator. This would at least make the calls to the HO and LOR versions the same. An issue might be that this would effectively compute the normal on the LOR mesh. I think with the way MFEM does the refinements for LOR the normal for LOR and HO will be the same though? 

Access to the parent boundary transformation I think would still be the nicest method. But I'm thinking hacking it together with the `SetNormal` function and using the volumetric LOR mapping is easy enough.

**Comment by pazner** [comment]
Yes, I see that if you need the normal vectors, then the situation becomes a little bit more complicated. I think that storing the relationship between the original high-order boundary elements and the LOR boundary elements could also be a good solution. This could involve modifying `CoarseFineTransformations`, or perhaps just adding an additional `CoarseFineTransformations` object to the mesh class, which stores the boundary element relationships.

**Comment by smsolivier** [comment]
Ok thanks! If I have time I'll give that a shot.
