### ISSUE TITLE
Run mfem examples with hypre GPU build

### ISSUE THREAD

**Issue by liruipeng** [mfem/mfem#1798]
Hi, MFEM developers,
I was able to successfully compile mfem and link with hypre 2.20 with CUDA GPU support. The configure options for hypre and mfem were `./configure --with-cuda --enable-unified-memory HYPRE_CUDA_SM=70` and `make pcuda -j CUDA_ARCH=sm_70`, respectively. When I tried to run `mpirun -n 1 ./ex1p  -d cuda`, I got seg-fault, which seemed to be related to some memory issue. Your help will be appropriated.

Thanks

-Ruipeng

**Comment by dylan-copeland** [comment]
Hi Ruipeng, support for hypre with CUDA in mfem is currently under development in PR #1492 (branch `hypre-cuda-dev`). I assume you are testing with the `master` branch of mfem. The `ex1p` sample run you referenced works in this branch. I just tested successfully with the latest hypre version (2.20) built with `sm_70` and mfem built with `sm_60`.

**Comment by liruipeng** [comment]
@dylan-copeland It works now. Thank you!
