### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by mparkgit** [mfem/mfem#18]
Hi,
   I'm testing example 5 by changing the coefficient k to a function.

The error message is as follows:
ex25.cpp: In function ‘int main(int, char**)’:
ex25.cpp:159: error: no matching function for call to ‘mfem::VectorFEDomainLFIntegrator::VectorFEDomainLFIntegrator(mfem::FunctionCoefficient&)’
../fem/lininteg.hpp:179: note: candidates are: mfem::VectorFEDomainLFIntegrator::VectorFEDomainLFIntegrator(mfem::VectorCoefficient&)
../fem/lininteg.hpp:172: note:                 mfem::VectorFEDomainLFIntegrator::VectorFEDomainLFIntegrator(const mfem::VectorFEDomainLFIntegrator&)
make: *** [ex25] Error 1

Can you explain how to fix it?
mp

**Comment by mlstowell** [comment]
Hi,

I believe changing 'k' to a FunctionCoefficient should work.  The compilation error that you show indicates that your code is trying to pass a FunctionCoefficient to a vector-valued linear form.   This should not work because we need a vector function to initialize a vector-valued linear form.  The question becomes why are we seeing this error?

The coefficient 'k' should be passed to the VectorFEMassIntegrator in section 8 of ex5.cpp.  The error shown above appears to come from section 7 of ex5.cpp.  Is it possible that you accidentally changed the vector-valued coefficients being used in section 7?  Or perhaps you accidentally changed the VectorFEMassIntegrator used in section 8 into a linear form integrator of some sort.

The only change that should have been necessary was to change the "ConstantCoefficient k(1.0);" into
"FunctionCoefficient k(your_k_function);".

I hope this helps!
Mark

**Comment by mparkgit** [comment]
Thank you.   
I compiled it successively.  But I have the error in run-time:

Options used:
   --mesh ../data/square-disc.mesh
   --order 1
   --visualization
***********************************************************
dim(R) = 49664
dim(W) = 29568
dim(R+W) = 79232
***********************************************************


Verification failed: (j != end) is false: Couldn't find diagonal in row. i = 0, j = 0, I[i+1] = 0
 ... at line 1401 in void mfem::SparseMatrix::DiagScale(const mfem::Vector&, mfem::Vector&, double) const of file sparsemat.cpp.
Abort (core dumped)

What is wrong?
mp

**Comment by mlstowell** [comment]
Hi, mp,

The coefficient 'k' needs to be positive everywhere.  Could it be that the function you chose is zero in some elements?  Or perhaps the function is not being passed into the integrator successfully.

Mark

**Comment by mparkgit** [comment]
Hi,

  What if the k in example 5 is a (2 by 2) matrix?
How do you change example 5?
mp

**Comment by mlstowell** [comment]
Hello,

You can define k as a MatrixFunctionCoefficient rather than a ConstantCoefficient.    We don't seem to have a MatrixConstantCoefficient (which I admit is odd) but you can certainly define a constant function and use it with the MatrixFunctionCoefficient.

Mark

**Comment by mparkgit** [comment]
Great !   Thank you.

**Comment by mparkgit** [comment]
Hi,
   I got the following error for using MatrixFunctionCoefficient:

 error: call of overloaded ‘MatrixFunctionCoefficient(int&, void (&)(mfem::Matrix&))’ is ambiguous
../fem/../mesh/../fem/coefficient.hpp:386: note: candidates are: mfem::MatrixFunctionCoefficient::MatrixFunctionCoefficient(int, void (*)(const mfem::Vector&, double, mfem::DenseMatrix&)) <near match>
../fem/../mesh/../fem/coefficient.hpp:378: note:                 mfem::MatrixFunctionCoefficient::MatrixFunctionCoefficient(int, void (*)(const mfem::Vector&, mfem::DenseMatrix&)) <near match>

How do I fix it?
mp

**Comment by martemyev** [comment]
Hi mp,
A piece of relevant code would be helpful, but I guess you're creating a MatrixFunctionCoefficient object like this:
`MatrixFunctionCoefficient mfc(dim, your_func);`
where you defined `your_func` as
`void your_func(Matrix&);`
while you should've defined it as
`void your_func(const Vector& x, DenseMatrix& m); // for stationary function`
or
`void your_func(const Vector& x, double t, DenseMatrix& m); // for time-dependant function`
where `x` is a point for computing the matrix coefficient 'm'.

**Comment by mparkgit** [comment]
Hi,
  I wrote as follows:

   MatrixFunctionCoefficient CIKcoeff(dim, IKC); 
    ... 
My function is
void IKC (const Vector & x, DenseMatrix & IK)
{  ... }
I tried just a constant 2 by 2 matrix
Still I have the same error.
mp

**Comment by mparkgit** [comment]
Hi,
   I found my mistake for it.
mp

**Comment by mparkgit** [comment]
Hi,
   When I run compiled example 5, each step is printed on screen.
How do I stop showing the detail?
mp

**Comment by mlstowell** [comment]
Hello,

The output can be adjusted using the 'SetPrintLevel' method on the solver.  If you want no output except error messages you can pass a zero.

Mark

**Comment by mparkgit** [comment]
Hi,
   How are  mesh files, "periodic-square.mesh" and "periodic-hexagon.mesh"
organized?   
In "periodic-square.mesh"   the number of vertices is 9
But the actual number of vertices is 36.  
What does it mean?
mp

**Comment by jakubcerveny** [comment]
Hi mp,

Periodic meshes are a special case of curvilinear meshes (see http://mfem.org/mesh-formats/#curvilinear-and-more-general-meshes). Curvilinear meshes are defined as pure topology (elements and vertices without coordinates) plus a vector grid function that positions all nodes of the mesh (hence the name of the section, "nodes"). 

Periodic meshes use discontinuous grid functions to "unwrap" the cyclic topology. In periodic-square.mesh, there are 3x3 elements but only 9 vertices. The vertices on the "boundary" are repeated so topologically the mesh is a torus.

The grid function however, which in this case is a 2-component discontinuous linear function, assigns planar positions to the 4 vertices of each of the 9 elements. 

Jakub
