### ISSUE TITLE
Implementation of new nonlinearform integrator

### ISSUE THREAD

**Issue by brightzhang91** [mfem/mfem#1800]
Hi :)

I'm trying to define my own `NonlinearFormIntegrator` for material modelling. 
After reading some cases, I think I'll need to implement my nonlinear equation into `NonlinearFormIntegrator::AssembleElementVector` and its Jacobian into `AssembleElementGrad.`  My nonlinear PDE is a Curl_Curl operation with the nonlinear coefficient, so that I'm trying to build it by modifying the `CurlCurlIntegrator.` (in ND space as well).  However I cannot find the  `AssembleElementVector`  defined for `CurlCurlIntegrator`, and many other BilinearFormIntegrators  (except `DiffusionIntegrator).` My questions are:
Have the AssembleElementVector been defined for other BilinearFormIntegrators ? if not, how are the local actions performed?
What is the general rule to define the `AssembleElementVector` and `AssembleElementMatrix` with respect to the mapping Jacobian  ? I cannot understand how the following rules matched in the existing `BilinearFormIntegrator` :
VALUE       u(x) = uh(xh)
INTEGRAL    u(x) = (1/w) * uh(xh)
H_DIV       u(x) = (J/w) * uh(xh)
H_CURL      u(x) = J^{-t} * uh(xh)           (square J)
H_CURL      u(x) = J*(J^t*J)^{-1} * uh(xh)   (general J)

Sorry for so many questions.  I really appreciate your help. Thanks !

Bright

**Comment by tzanio** [comment]
Hi Bright,

With this recent merge: https://github.com/mfem/mfem/pull/1765, there is now a default implementation of `AssembleElementVector` that is not efficient, but should work for any integrator that has `AssembleElementMatrix`.

We can provide more details how to implement specific integrators, but the short answer is that you 1) take the weak form of the operator; 2) discretize it with a FE space; 3) map each element integral to reference space using the corresponding mapping of the FE functions, their gradients, curls etc. and 4) apply a quadrature rule.

The different mapping types you list correspond to the step 3) above. For example Nedelec elements map from physical `u(x)` to reference space `uh(xh)` using the Piola transformation `u(x) = J^{-t} * uh(xh)`. This is the same transformation used for mapping the gradients of H1 functions BTW.

Hope this helps,
Tzanio

**Comment by brightzhang91** [comment]
Hi Tzanio
Many thanks for your explanation !
However I'm still confused about some questions .

> With this recent merge: #1765, there is now a default implementation of `AssembleElementVector` that is not efficient, but should work for any integrator that has `AssembleElementMatrix`.
 
How was the local actions performed in the BilinearformIntegrators before this default implementation ?

And as for the mapping type, I'm still confused how it works according to the Jacobian.  Such as the `DivDivIntegrator::AssembleElementMatrix` in RT space

`for` (int i = 0; i < ir -> GetNPoints(); i++)
    {
       const IntegrationPoint &ip = ir->IntPoint(i); 
       el.CalcDivShape (ip, divshape); 
       Trans.SetIntPoint (&ip);
       c = ip.weight / Trans.Weight();  
        if (Q)
       {
          c *= Q -> Eval (Trans, ip);
        }  
        // elmat += c * divshape * divshape ^ t
        AddMult_a_VVt (c, divshape, elmat);
    }`
It seems the Jacobian is not used in this implementation as for RT finite element : H_DIV u(x) = (J/w) * uh(xh). 
I think I must have some problems in the understanding. Thanks very much for your help !

**Comment by tzanio** [comment]
> How was the local actions performed in the BilinearformIntegrators before this default implementation ?

There was no default implementation for `AssembleElementVector` before.

> It seems the Jacobian is not used in this implementation as for RT finite element : H_DIV u(x) = (J/w) * uh(xh).

If `u` is `H(div)` then `div u` is in `L2` and so it maps with the `INTEGRAL` mapping. That's why in the code you posted we divide and not multiply with the determinant of the Jacobian

**Comment by brightzhang91** [comment]
Thanks Tzanio ! 
 I understand it now.  That's very helpful !
