### ISSUE TITLE
Compute advection velocity from a previous solution.

### ISSUE THREAD

**Issue by tbgalois** [mfem/mfem#1808]
Hi everyone,

I am trying to solve a coupled system of eqs, constituted by a heat conduction eq and by an advection equation (conservative form) on a scalar quantity. In this problem, the advection velocity is depending in a nasty way on the temperature field, something like
v = A/T grad(T)

After solving the heat equation and getting the temperature field, I need to update the velocity with the new temperature.

My initial thought was to define `GradientGridFunctionCoefficient` getting the grid function of the temperature, in order to have a vector-derived class to feed into the convection operator. But since I have to further manipulate such quantity (i.e., dividing by temperature and multiplying by the constant A), I got a bit stacked. Do you have any advice on how can I proceed?

BR,
Tommaso

**Comment by kmittal2** [comment]
Hi @tbgalois 
I was recently working on a similar problem where the temperature was dependent on the gradient of the velocity, with each of the solutions defined on different meshes. To resolve this, I computed the gradient of the velocity on the velocity mesh, set up a vector `GridFunction` on the temperature mesh, and interpolated the gradient of the velocity from velocity mesh to temperature mesh using [`FindPointsGSLIB`](https://github.com/mfem/mfem/blob/master/fem/gslib.cpp). Once I had the vector GridFunction on the temperature mesh with the interpolated values, I setup a `VectorGridFunctionCoefficient` to construct the BilinearForm with a `MixedDirectionalDerivativeIntegrator`. 
Do you think you could use an approach like this for your problem?

Ketan

**Comment by tbgalois** [comment]
Hey @kmittal2 thanks for the hint, I think it might actually work also for me. I will try and keep you posted. Thanks!

**Comment by tbgalois** [comment]
Hi @kmittal2,
sorry for the delay from my previous post. 
I am actually struggling with the Setup method of FindPointsGSLIB: I am using a parallel mesh - which has no nodes as I understand from the documentation. Therefore the Setup method raises an exception because it cannot find nodes. How am I supposed to workaround this issue? I checked the example [here](https://github.com/mfem/mfem/blob/master/miniapps/gslib/pfindpts.cpp) but it is not fitting properly my case, since I don't need to curve my mesh (maybe I misunderstood the principle of "curving the mesh").

thanks in advance!
tommaso

**Comment by kmittal2** [comment]
Hi @tbgalois 

These `nodes` are needed by `FindPoints` to generate the information needed by the `gslib` library. For sake of convenience, you can use `mesh.SetCurveature(order)` where you can set `order=1` to introduce `nodes` before calling `FindPointsGSLIB::Setup`. Introducing nodes like this should not impact your mesh adversely in any way and you should be able to use it as usual.

Ketan

Ketan

**Comment by tbgalois** [comment]
Thanks @kmittal2, it works fine! I will close the issue and get in touch in case something else would pop up.

BR
Tommaso
