### ISSUE TITLE
Link with petsc

### ISSUE THREAD

**Issue by bensworth** [mfem/mfem#1812]
I am trying to install Petsc and link MFEM with Petsc, Hypre, and sundials. Petsc tests runs fine with hypre, and installing MFEM with hypre and sundials, but without Petsc, works fine. But when I try to compile MFEM with Petsc, I get strange vector-errors. MFEM compiles fine, but when I try to compile `make unit_tests` (or `make examples`), I get errors
```
[100%] Linking CXX executable unit_tests
Undefined symbols for architecture x86_64:
  "_N_VGetVectorID", referenced from:
      __ZN4mfem6VectorC1EP17_generic_N_Vector in libmfem.a(vector.cpp.o)
      __ZN4mfem6Vector9ToNVectorERP17_generic_N_Vectorl in libmfem.a(vector.cpp.o)
  "_N_VMake_Parallel", referenced from:
      __ZN4mfem14HypreParVector9ToNVectorEv in libmfem.a(hypre.cpp.o)
  "_N_VMake_Serial", referenced from:
      __ZN4mfem6Vector9ToNVectorEv in unit_test_main.cpp.o
      __ZN4mfem6Vector9ToNVectorEv in test_mem.cpp.o
      __ZN4mfem6Vector9ToNVectorEv in test_text.cpp.o
      __ZN4mfem6Vector9ToNVectorEv in test_zlib.cpp.o
      __ZN4mfem6Vector9ToNVectorEv in test_complex_operator.cpp.o
      __ZN4mfem6Vector9ToNVectorEv in test_ilu.cpp.o
      __ZN4mfem6Vector9ToNVectorEv in test_matrix_block.cpp.o
      ...
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[3]: *** [tests/unit/unit_tests] Error 1
make[2]: *** [tests/unit/CMakeFiles/unit_tests.dir/all] Error 2
make[1]: *** [tests/unit/CMakeFiles/unit_tests.dir/rule] Error 2
make: *** [unit_tests] Error 2
```
I believe the undefined symbols, e.g., `_N_VGetVectorID` are Sundials objects. It's weird that this runs fine without Petsc but not with petsc, when Sundials is not connected to Petsc in the first place (I did not compile them together).

Update: I managed to compile with Petsc and without Sundials and everything works. There seems to be conflicts between sundials and petsc. Any ideas what these may be? If not that is okay, I can work around it.

**Comment by jandrej** [comment]
You have to make sure that petsc uses the same hypre and sundials that you have in your local install directory during the installation of petsc. To reconfigure without Sundials you have to remove the cache (best to remove all of the build directory from cmake).
