### ISSUE TITLE
Documentation and parameter names for SecondOrderTimeDependentOperator::ImplicitSolve

### ISSUE THREAD

**Issue by samuelpmishLLNL** [mfem/mfem#1813]
I ran into some issues when implementing a type derived from SecondOrderTimeDependentOperator, and it appears that there may be a discrepancy between its documentation and implementation.

[The documentation](https://mfem.github.io/doxygen/html/classmfem_1_1SecondOrderTimeDependentOperator.html#a7ded10bcd22b63dee506309bd002c8da) for `SecondOrderTimeDependentOperator::ImplicitSolve` currently reads:

```cpp
void mfem::SecondOrderTimeDependentOperator::ImplicitSolve (const double dt0, 
                                                            const double dt1, 
                                                            const Vector & x, 
                                                            const Vector & dxdt, 
                                                            Vector & k)  

Solve the equation: k = f(x + 1/2 dt0^2 k, dxdt + dt1 k, t), for the unknown k at the current time t. 
```

but the implementation seems to require `k` to be determined by `k = f(x + dt0 k, dxdt + dt1 k, t)`. For example, the two use cases of a SecondOrderTimeDependentOperator in mfem are given below and are consistent with the update `x + dt0 k` rather than `x + 1/2 dt0^2 k`.

```cpp
test_ode2.cpp:      
virtual void ImplicitSolve(const double fac0, const double fac1,
                                 const Vector &u, const Vector &dudt,
                                 Vector &d2udt2)
      {
         double T = 1.0 + a*fac0 + fac1*b;  <-------
         d2udt2[0] = (-a*u[0] - b*dudt[0])/T;
      }
----------------------------------------------------------------
ex23.cpp:

void WaveOperator::ImplicitSolve(const double fac0, const double fac1,
                                 const Vector &u, const Vector &dudt, Vector &d2udt2)
{
   // Solve the equation:
   //    d2udt2 = M^{-1}*[-K(u + fac0*d2udt2)]   <-------
   // for d2udt2
...
}
```
Likewise, the parameter names `dt0, dt1` that appear in the function signature of `SecondOrderTimeDependentOperator::ImplicitSolve` are misleading since `dt0` does not actually have the same dimension as `t`.

**Comment by tzanio** [comment]
@IdoAkkerman, do you think you can help @samuelpmishLLNL ?

**Comment by tzanio** [comment]
ping: @IdoAkkerman

**Comment by IdoAkkerman** [comment]
You are correct the comment in operator.hpp is incorrect.

**Comment by tzanio** [comment]
Discussion moved to #1892.
