### ISSUE TITLE
Bilinear form on surface between two domains

### ISSUE THREAD

**Issue by carramba** [mfem/mfem#1816]
I would like to compute a bilinear form defined on the internal surface between two physical domains. `BilinearForm::AddInteriorFaceIntegrator` seems the right method, but it seems that the bilinear form gets integrated on all the internal faces of the mesh.

How could I restrict the integration only on certain faces? In other words, is there a method like `BilinearForm::AddBoundaryIntegrator`, but for non-boundary surfaces?

Many thanks.

**Comment by chang-yiyi** [comment]
Hi @carramba ,

I have some ideas but it's for linear form, instead of bilinear form. I think it's also OK for bilinear form. Hope this can help you.

You only want to restrict the integration on certain faces, so you must have marked these faces. In your self-defined BilinearFormIntegrator, you can only integrate on the marked faces, like below my LinearFormIntegrator
```
class SelectInterfaceIntegrator: public LinearFormIntegrator
{
protected:
    Coefficient* q;
    VectorCoefficient* w;
    Mesh* mesh;
    int protein_marker, water_marker;

    Vector shape1, shape2, normal, w_val;

public:
    SelectInterfaceIntegrator(Coefficient* q_, VectorCoefficient* w_, Mesh* mesh_, int protein, int water)
            : q(q_), w(w_), mesh(mesh_), protein_marker(protein), water_marker(water) {}
    ~SelectInterfaceIntegrator() {}

    virtual void AssembleRHSElementVect(const FiniteElement &el,
                                        ElementTransformation &Tr,
                                        Vector &elvect)
    {
        MFEM_ABORT("not support!");
    }

    virtual void AssembleRHSElementVect(const FiniteElement& fe1,
                                        const FiniteElement& fe2,
                                        FaceElementTransformations &Trans,
                                        Vector &elvect)
    {
        const Element* e1 = mesh->GetElement(Trans.Elem1No);
        const Element* e2 = mesh->GetElement(Trans.Elem2No);
        int attr1 = e1->GetAttribute();
        int attr2 = e2->GetAttribute();

        int dim = fe1.GetDim();
        normal.SetSize(dim);
        w_val.SetSize(dim);

        int ndof1 = fe1.GetDof();
        int ndof2 = fe2.GetDof();
        int ndofs = ndof1 + ndof2;
        shape1.SetSize(ndof1);
        shape2.SetSize(ndof2);

        elvect.SetSize(ndofs);
        elvect = 0.0;

        if (attr1 == attr2)
            return; // only integrate on interface of protein and water
    }
};
```

**Comment by carramba** [comment]
Many thanks, @chang-yiyi! This is very interesting. I will try to come up with a solution for the bilinear form and post my code here.

**Comment by carramba** [comment]
At the end, I opted for an alternative solution:
As my code already relies on Gmsh for meshing, I export nodes and vertices of elements forming one physical domain to an `mfem::Mesh`. In this way, the internal surface becomes a boundary, where I can use `BilinearForm::AddBoundaryIntegrator`.

**Comment by tzanio** [comment]
Thanks for helping @chang-yiyi!
