### ISSUE TITLE
Using hybridization 

### ISSUE THREAD

**Issue by kvoronin** [mfem/mfem#182]
Hello!

I am trying to use hybridization in MFEM (version 3.2) for solving a problem in H(div). Without hybridization it works, but when enabled (hybridization = true in the attached example) I got the error in EnableHybridization():
** On entry to DGETRF parameter number  4 had an illegal value
When writing the code I was looking at the example ex4p which works fine both with and without hybridization, so what have I missed?

I would be grateful for any suggestions.
[exDebug.cpp.zip](https://github.com/mfem/mfem/files/936788/exDebug.cpp.zip)

Thanks,
Kirill

**Comment by tzanio** [comment]
Hi Kirill,

I will suggest that you switch to the `FormLinearSystem` interface. 

You can alternatively form the system yourself by consulting https://github.com/mfem/mfem/blob/master/fem/pbilinearform.cpp#L299, but I wouldn't recommend that.

Hope this helps,
Tzanio

**Comment by kvoronin** [comment]
Thanks, @tzanio,

It does help. May I also ask if the implemented hybridization should also work in 4D case?

Thanks,
Kirill

**Comment by tzanio** [comment]
The general idea should work, but my guess is that the implementation, e.g. `NormalTraceJumpIntegrator` may need to be updated? 

Once the constraint matrix is specified, the process is algebraic and should work in 4d.

**Comment by kvoronin** [comment]
I see,
so the first step then should be to implement DG_Interface_FECollection in 4D case. I guess I should open another question for that.

Thanks,
Kirill
