### ISSUE TITLE
New limiter for DG solver for Euler equations

### ISSUE THREAD

**Issue by makrandak** [mfem/mfem#1821]
Hello all, 

I am trying to implement a new limiter for the DG discretization of Euler equations.  I need to loop over the element neighbors and compute the max and min and averages on the neighbors.  I know that there is a function on gridfunction to calculate the element averages.  Are there similar methods for computing max and min on DG elements ? 
I have a couple of more questions
1) Also, how do I find and loop over neighbor elements ?
2) How do I change the solution within the timestepper at every stage?  As the limiter needs to be applied at every Runge-Kutta stage. Thanks for your help. I really appreciate it.

**Comment by pazner** [comment]
Hi @makrandak,

I don't believe similar methods exist for max and min. Do you want the maximum and minimum values at nodal points? Or at certain quadrature points?

1. You can use the "element-to-element table" (given by `Mesh::ElementToElementTable`) to find the neighbors of a given element. Be careful in parallel, because the neighbor element may belong to a different processor (indicated by an index that is greater than the number of mesh elements).
2. The `TimeDependentOperator::Mult` function is called at every Runge-Kutta stage. Can you write your scheme in terms of a modified RHS function? If so, then you can apply your limiter here. Otherwise, you might want to create a new subclass of `ODESolver` that implements your specific method.

**Comment by vladotomov** [comment]
Hi @makrandak,

There are some methods for both 1. and 2. in [Remhos](https://github.com/CEED/Remhos), it might be useful to check it out. For example, a function for computing DG max/min taking into account the neighbors is given [here](https://github.com/CEED/Remhos/blob/c3ca88eac250e8cb2e700a270946b631993bf1df/remhos_tools.cpp#L376-416).

**Comment by makrandak** [comment]
Thank you very much both @pazner  and @vladotomov  for your replies.  
> Do you want the maximum and minimum values at nodal points? Or at certain quadrature points?
This is adjustable in the method.  Ideally both of these set of points.  The reason is that evaluation of `max` and `min` on an element depends on how much you sample the function. It is always just an approximate `max` and `min`.  If I am able to sample the function more with both quadrature points and nodes the estimate will be better. 

>You can use the "element-to-element table" (given by Mesh::ElementToElementTable) to find the neighbors of a given element. Be careful in parallel, because the neighbor element may belong to a different processor (indicated by an index that is greater than the number of mesh elements).

I don't quite understand what this means (indicated by an index that is greater than the number of mesh elements)? Index greater than the total no of mesh elements or the no of neighbors?

> The TimeDependentOperator::Mult function is called at every Runge-Kutta stage. Can you write your scheme in terms of a modified RHS function? If so, then you can apply your limiter here. Otherwise, you might want to create a new subclass of ODESolver that implements your specific method.

If I understand correctly `Mult` is essentially calculating RHS by multiplying Operator to the current `state`.  I just want to limit the state before this `Mult` happens, this probably could be done inside `Mult` if I have access to which element I am in when inside `Mult` and the element neighbors. Maybe there is a different more efficient way, which you may suggest. 

Thanks for pointing me to Remhos @vladotomov, Could you please point me to the code for these examples especially for the loop over neighbor elements in Remhos, and the limiting of the solution on RK stages ?

>For example, a function for computing DG max/min taking into account the neighbors is given here.
This is a CG element it seems but the computation should not be much different I imagine for the DG element. 

Thanks again both of you for your help.

**Comment by vladotomov** [comment]
Remhos is not the best example as it has grown quite complicated, but you can use it to see the basic principles.

The limiting is done at every RK stage with this [function call](https://github.com/CEED/Remhos/blob/559d7eaa1a42303920563271939e969ad2e2c001/remhos.cpp#L1128). It uses the non-limited solution `du_HO` and a low-order solution `du_LO` to compute the limited `d_u`. This `d_u` corresponds to the second argument (i.e. the output) of `Mult()`.

The bounds for `d_u` are computed in the previous two [lines](https://github.com/CEED/Remhos/blob/559d7eaa1a42303920563271939e969ad2e2c001/remhos.cpp#L1126-L1127). First we compute minimum and maximum over each cell, using the DG function. Then we use auxiliary continuous functions (CG) that take the max/min over overlapping dofs on the faces. Finally we make another pass over the elements and define the bounds for the DG function through the local max/min of the CG function. This is a way to take into account neighbor elements.

I hope this helps,
Vladimir

**Comment by pazner** [comment]
> > You can use the "element-to-element table" (given by Mesh::ElementToElementTable) to find the neighbors of a given element. Be careful in parallel, because the neighbor element may belong to a different processor (indicated by an index that is greater than the number of mesh elements).
> 
> I don't quite understand what this means (indicated by an index that is greater than the number of mesh elements)? Index greater than the total no of mesh elements or the no of neighbors?

If the element-to-element table indicates that `el2` is a neighbor of `el1`, and `el2 >= mesh.GetNE()`, then that means that `el2` is a "face neighbor" of `el1`, i.e. it belongs to a different processor.

**Comment by makrandak** [comment]
Hello Will @pazner,  

I am struggling to understand the usage of `Mesh::ElementToElementTable`.  I understand that it is a `Table` datastructure containing the connectivity.  But, I am not sure on how to use it.  I have been looking at the doxygen documentation but I did not find any notes on usage.  If I am in an element how do I access the neighbors using this? Sorry if this seems naive, but I did not find usage notes in doxygen. 
Are there any examples where it is used and I could look at ? 

Thanks for your help.

**Comment by chang-yiyi** [comment]
Hi @makrandak ,

Maybe the below code can help you understand all `Table` datastructure.
```
#include <iostream>
#include "mfem.hpp"

using namespace std;
using namespace mfem;

int main(int argc, char *argv[])
{
    Mesh mesh(2, 2, Element::TRIANGLE, true);

    const Table& element2edge = mesh.ElementToEdgeTable();
    Array<int> el2e;
    for (size_t i=0; i<mesh.GetNE(); i++)
    {
        element2edge.GetRow(i, el2e);
        Element* el = mesh.GetElement(i); //打印出element的attribute就可以知道这些element确实不包括boundary element
        el2e.Print(cout << i+1 << "-th element, attribute: " << el->GetAttribute() << ", edge indices: ", el2e.Size());
    }

    const Table& element2element = mesh.ElementToElementTable();
    Array<int> el2el;
    for (size_t i=0; i<mesh.GetNE(); i++)
    {
        element2element.GetRow(i, el2el);
        el2el.Print(cout << i << "-th element's neighbor element indices: ");
    }
}
```

**Comment by makrandak** [comment]
Hello all, 

Thank you Will @pazner for introducing me to the `Table` datastructure and thank you @chang-yiyi  for clarifying it's usage.  It is very useful and versatile, because I have access to it within the `Mult` function inside the Time dependent operator class.  I wrote my own max and min evaluation functions.  
I now understand what Remhos is doing for limiting (combining low order and higher order solutions appropriately), I am using a different strategy with a bound preserving limiter but the place of application is the same if I understand correctly, i.e `Mult()` method, instead of changing the output I modify the input `x`  (to limit it) and then let the operator multiply the modified `x`.  Thanks for your help in pointing these codelines.  

I am still working on a general implementation of all this, which is why I am not closing the issue right now.  I will ask if I need some more help.  Thanks for the guidance till now.  
-Makrand

**Comment by makrandak** [comment]
Hello all, 

I think I have implemented the limiter correctly at least in serial.  I have two questions

1) How do I handle neighbour elements which are on a different processor? If the `ElementToElementTable` called on an object of  `ParMesh`, is the neighbour index correctly identified ? (that it is not greater than the total no of elements) ? 

2) I implemented the limiter to limit the solution which is the input to `Mult(x, y)`  i.e. `x` is limited inside `Mult` (so I just modified x inside Mult) and then the operators are used to calculated `y`.  However, this does not allow me to limit the solution after the step is done. e.g. for RK solver see below line 16 below.   
```
0 void RK2Solver::Step(Vector &x, double &t, double &dt)
1 {
2     //  0 |
3     //  a |  a
4     // ---+--------
5     //    | 1-b  b      b = 1/(2a)
6
7     const double b = 0.5/a;
8
9     f->SetTime(t);
10   f->Mult(x, dxdt);   ///// Here x is limited 
11   add(x, (1. - b)*dt, dxdt, x1);
12   x.Add(a*dt, dxdt);
13
14   f->SetTime(t + a*dt);
15   f->Mult(x, dxdt); ///// Here x is limited 
16   add(x1, b*dt, dxdt, x);  /// Here x is not limited, how do I limit x here ? 
17   t += dt;
}
``` 
Is there a way to get a hook to the solution of the ode at various stages ? Or do I have to write a new odeSolver derived ?

-Makrand

**Comment by pazner** [comment]
> 1. How do I handle neighbour elements which are on a different processor? If the `ElementToElementTable` called on an object of  `ParMesh`, is the neighbour index correctly identified ? (that it is not greater than the total no of elements) ?

Hi @makrandak, if the neighbor element is on a different processor, the entry of the table will be the *shifted element index*, which is greater than or equal to the number of local mesh elements. Denote this index by `shifted_idx`. We have `shifted_idx >= pmesh.GetNE()`. We can compute the *face neighbor index* by subtracting the number of local elements:
```c++
int face_nbr_idx = shifted_idx - pmesh.GetNE();
```
This face neighbor index can be used to get information about this element (e.g. `ParMesh::GetFaceNbrElementTransformation`, `ParFiniteElenentSpace::GetFaceNbrFE`, etc.).

> 2. I implemented the limiter to limit the solution which is the input to `Mult(x, y)`  i.e. `x` is limited inside `Mult` (so I just modified x inside Mult) and then the operators are used to calculated `y`.  However, this does not allow me to limit the solution after the step is done. e.g. for RK solver see below line 16 below.
> Is there a way to get a hook to the solution of the ode at various stages ? Or do I have to write a new odeSolver derived ?

One option would be to write a new ODESolver. As you can see from the examples built-in to MFEM, this is fairly straightforward. Another option that would work in this case is just to apply one more step of limiting after the time step (since at each RK stage the limiter is already applied). If you use a SSP RK method, perhaps it is not necessary to apply the limiter at the end, because the solution will be written as a convex combination of forward Euler steps.

**Comment by makrandak** [comment]
Hello all, 

I was able to get the limiter working in both serial and parallel.  I wanted to limit the solution near the boundary, I was curious if there is a method which returns whether the given element is on the boundary?

-Makrand

**Comment by makrandak** [comment]
Hello all, 

On closer look, it seems that the limiter gives different results compared to serial.  My suspicion is that the calculation of bounds and averages on neighbours on other processes is incorrect.  

Here is what I am doing to deal with neighbour index of the element
```
int neighbourFaceIndex = el2el[neighbourIterator] - parMesh_.GetNE();
neighbourIndex = parMesh_.GetFaceNbrElementTransformation(neighbourFaceIndex)->ElementNo;
```
I don't think this is correct because it turns out `el2el[neighbourIterator]` and `neighbourIndex` calculated as above is exactly the same and `>= parMesh_.GetNE()`. But I am not sure how to fix this.  I am seeking an element index I can use to query gridfunctions to get corresponding elemental quantities like min, max, avgs. 

This is a simple sketch of the calculation I am doing. 

1) Calculate ParGridFunctions containing averages and minimas and maximas of each element.   This is done inside the Evolution class.  This is called before the limiting step inside the custom ODE solver.  

2) I access these gridfunctions using block vectors as follows, e.g.
	ParGridFunction avgs(&fes_avg_, u_block_avg_.GetData());
	ParGridFunction elemMin(&fes_avg_, u_block_min_.GetData());
	ParGridFunction elemMax(&fes_avg_, u_block_max_.GetData());
```
for (int numEq = 0; numEq < inputData_->num_equation; numEq++) {
  elementalAvgPrimitive_i(numEq) = u_block_avg_.GetBlock(numEq).Elem(neighbourIndex);
   elementalMinPrimitive_i(numEq) = u_block_min_.GetBlock(numEq).Elem(neighbourIndex);
  elementalMaxPrimitive_i(numEq) = u_block_max_.GetBlock(numEq).Elem(neighbourIndex);
}
```
Where `u_block_min` and `u_block_max` are `BlockVectors` which are external data for `ParGridFunctions` containing max, min and averages. 

3) Calculate the limiter based on these sampled Min, max and averages.  This all happens inside the Evolution class where if I understand correctly vectors are already domain decomposed. 

The calculation inside the ODESolver is as follows for example for RK2SSP scheme. 
```
void RK2SolverLimited::Step(Vector &x, double &t, double &dt) {
	//  0 |
	//  a |  a
	// ---+--------
	//    | 1-b  b      b = 1/(2a)

	const double b = 0.5 / a;

	f->SetTime(t);
	f->Mult(x, dxdt);
	add(x, (1. - b) * dt, dxdt, x1);
	x.Add(a * dt, dxdt);

	///Limiting step
	f->calcAveragesAndBounds(x);
	MPI_Barrier(MPI_COMM_WORLD);
	//std::cout<< "Limiting solution Stage 1" <<std::endl;
	f->limitVector(x, x);

	f->SetTime(t + a * dt);
	f->Mult(x, dxdt);
	add(x1, b * dt, dxdt, x);

	///Limiting step
        f->calcAveragesAndBounds(x);
	MPI_Barrier(MPI_COMM_WORLD);
	//std::cout<< "Limiting solution Stage 2" <<std::endl;
	f->limitVector(x, x);

	t += dt;
}
```

I have noticed that the limiter is different on the processor boundaries and it triggers instabilities.  I am not sure what is wrong with my setup.  I am more confident that the algorithm works fine in serial.  Any help in this regard is much appreciated.  

-Makrand

**Comment by makrandak** [comment]
Update:   

I still cannot figure out how to sample the gridfunction in parallel with elementToelement Table.  I am now trying to use @mlstowell 's approach in #1700.  I am still getting different results in parallel compared to serial.  It works fine in serial.  Here is the snapshot of the loop I implemented

```
        ///call for populating ghost elements
	elemMin_.ExchangeFaceNbrData();
	elemMax_.ExchangeFaceNbrData();

        /// local to shared faces mapping lf2sf_ is a member variable
	for (int sf=0; sf< vfes.GetParMesh()->GetNSharedFaces(); sf++)
	{
		int lf = parMesh_.GetSharedFace(sf);
		lf2sf_[lf] = sf;
	}

	ElementTransformation* Tr = nullptr;
	ElementTransformation* TrNbr_it = nullptr;
	for (int i = 0; i < vfes.GetNE(); i++)
	{
		Tr = parMesh_.GetElementTransformation(i);
		IntegrationPoint ip = Geometries.GetCenter(Tr->GetGeometryType());

		avgs_.GetVectorValue(i, ip, elementalAveragesPrimitive);
		avgs_consv_.GetVectorValue(i, ip, elementalAveragesConservative);
		

		/// Loop over neighbour elements to calculate min and max
		Array<int> faces, ori;
		if (dim == 3) {
			parMesh_.GetElementFaces(i, faces, ori);
		} else if (dim == 2) {
			parMesh_.GetElementEdges(i, faces, ori);
		}
		DenseMatrix elem_min (inputData_->num_equation, faces.Size() + 1);
		DenseMatrix elem_max (inputData_->num_equation, faces.Size() + 1);
		
                ///----------------------------------For current element -----------------------------------------------------///
		Vector elementalMinPrimitive_0(inputData_->num_equation);
                Vector elementalMaxPrimitive_0(inputData_->num_equation);
		elemMin_.GetVectorValue(i, ip, elementalMinPrimitive_0);
		elemMax_.GetVectorValue(i, ip, elementalMaxPrimitive_0);

		elem_min.SetCol(0, elementalMinPrimitive_0);
		elem_max.SetCol(0, elementalMaxPrimitive_0);

		///------------------------------------------------------------------------------------------------------------///


		FaceElementTransformations *FETrans = nullptr;
		for (int neighbourIterator = 0; neighbourIterator < faces.Size(); neighbourIterator++) {
			Vector elementalMinPrimitive_i(inputData_->num_equation);
			Vector elementalMaxPrimitive_i(inputData_->num_equation);
			FETrans = vfes.GetParMesh()->GetFaceElementTransformations(faces[neighbourIterator]);
			if (FETrans->Elem2) {
				const IntegrationPoint &ip_nbr = Geometries.GetCenter(FETrans->Elem2->GetGeometryType());
				FETrans->Elem2->SetIntPoint(&ip_nbr);
				
				elemMin_.GetVectorValue(*FETrans->Elem2, FETrans->GetIntPoint(), elementalMinPrimitive_i);
				elemMax_.GetVectorValue(*FETrans->Elem2, FETrans->GetIntPoint(), elementalMaxPrimitive_i);
				
				//elemMin_.Print(std::cout << i << " " << neighbourIterator << " face neighbor value from other proc ");
			} else {
				std::map<int, int>::iterator mit = lf2sf_.find(faces[neighbourIterator]);
				if (mit != lf2sf_.end()) {
					int sf = mit->second;
					FETrans = vfes.GetParMesh()->GetSharedFaceTransformations(sf);
					const IntegrationPoint &ip_nbr = Geometries.GetCenter(FETrans->Elem2->GetGeometryType());
					FETrans->Elem2->SetIntPoint(&ip_nbr);
					//avgs_.GetVectorValue(*FETrans->Elem2, FETrans->GetIntPoint(), val);
					elemMin_.GetVectorValue(*FETrans->Elem2, FETrans->GetIntPoint(), elementalMinPrimitive_i);
					elemMax_.GetVectorValue(*FETrans->Elem2, FETrans->GetIntPoint(), elementalMaxPrimitive_i);
					//elemMin_.Print(std::cout << i << " " << neighbourIterator << " face neighbor value from other proc ");
				}
			}
			elem_min.SetCol(neighbourIterator + 1, elementalMinPrimitive_i);
			elem_max.SetCol(neighbourIterator + 1, elementalMaxPrimitive_i);
		}
		///-----------------------------------------------------------------------------------------------------------///

		double limiter = calcLimiterPerElem(i, elementalAveragesPrimitive, elem_min, elem_max);

		DenseMatrix xmatCurrentElemLimited(dof, inputData_->num_equation);/// Limited elemental vectors
		///-----------------------------------Get elemental vectors-------------------------------------------------////
		vfes.GetElementVDofs(i, vdofsLim);
		xLim.GetSubVector(vdofsLim, xvalLimited);
		xmatCurrentElem.UseExternalData(xvalLimited.GetData(), dof, inputData_->num_equation);

		///--------------------------------------------------------------------------------------------------------////
		for (int numEq = 0; numEq < inputData_->num_equation; numEq++) {
			///-------------------------------- limiter corrections----------------------------------------------------///
			Vector col(dof);
			for (int d = 0; d < dof; d++) {
				//col(d) = (1.0 - limiter) * col(d) + elementalAveragesConservative(numEq) * (limiter);
				xmatCurrentElemLimited(d, numEq) = elementalAveragesConservative(numEq)
						+ (limiter * (xmatCurrentElem(d, numEq) - elementalAveragesConservative(numEq)));
			}
			///--------------------------------------------------------------------------------------------------------////
		}
		xLimited.SetSubVector(vdofsLim, xmatCurrentElemLimited.GetData()); /// constructing full vector
	}
``` 

`avgs_`, `avgs_consv_`, `elemMin_`, `elemMax`  are `ParGridFunctions` which are calculated in a separate function and stored as member variables of the class.  

Am I missing something in this setup ?  I am seeing correct behaviour in serial, but I see weird behaviour near the processor boundaries in parallel.

**Comment by pazner** [comment]
> ```
> int neighbourFaceIndex = el2el[neighbourIterator] - parMesh_.GetNE();
> neighbourIndex = parMesh_.GetFaceNbrElementTransformation(neighbourFaceIndex)->ElementNo;
> ```
> 
> I don't think this is correct because it turns out `el2el[neighbourIterator]` and `neighbourIndex` calculated as above is exactly the same and `>= parMesh_.GetNE()`. But I am not sure how to fix this. I am seeking an element index I can use to query gridfunctions to get corresponding elemental quantities like min, max, avgs.

Hi @makrandak, to access values, etc. of ParGridFunctions on neighboring processors, you have to use the `Vector` returned from `ParGridFunction::FaceNbrData` (making sure to call `ParGridFunction::ExchangeFaceNbrData` before. You can get the degrees of freedom associated with a face neighbor element by indexing into this vector using the DOF array returned from `ParFiniteElementSpace::GetFaceNbrElementVDofs`.

**Comment by makrandak** [comment]
Hello Will @pazner  Thanks for your reply.  I do call `ParGridFunction::ExchangeFaceNbrData`.  I don't think I understand, Is FaceNbrData elemental  or local to all the elements in process ?  I am looping through elements and trying to find data of neighbours for each element.   

If I understand correctly, you are suggesting something like this 
```
Vector neighbourData = elemMax_.FaceNbrData();
for (int i = 0; i < vfes.GetNE(); i++)
{
             Array <int> nbrDofs;
             vfes.GetFaceNbrElementVDofs(i, nbrDofs);
             Vector dataOfNeighboursOfElement_i;
             neighbourData.GetSubVector(nbrDofs, dataOfNeighboursOfElement_i);
}
```

Is this correct?  

Does this pruned vector `dataOfNeighboursOfElement_i` contain the data from all neighbours? In that case how do I distinguish between which neighbours data is index where in `dataOfNeighboursOfElement_i` ? 

Thanks for your help and advice. 

Makrand

**Comment by mlstowell** [comment]
Hi, @makrandak ,

I see one potential issue with your implementation above.  When you call `GetVectorValue` the integration point that you're using as an argument, `FETrans->GetIntPoint()`, is a point on the face and not the center of the element.  The `FETrans` object has three `ElementTransformation` objects within it; one for the face itself and one for the elements on each side of that face.  Each of these transformation objects could be evaluated at separate locations.  I believe the integration point you want here is `ip_nbr` or you could use `FETrans->Elem2->GetIntPoint()`.  These should be the same since you just set this.

Incidentally, providing the integration point both within the `ElementTransformation` object and as a separate argument to calls like `GetVectorValue` is an unfortunate source of confusion.  We do this for backward compatibility because, apparently, at one time the `ElementTransformation` didn't have the integration point.

I expect this will change your results, at least by a small amount, both in serial and parallel.  However, I doubt it will bring the two into agreement.

Best wishes,
Mark

**Comment by pazner** [comment]
> If I understand correctly, you are suggesting something like this
> 
> ```
> Vector neighbourData = elemMax_.FaceNbrData();
> for (int i = 0; i < vfes.GetNE(); i++)
> {
>              Array <int> nbrDofs;
>              vfes.GetFaceNbrElementVDofs(i, nbrDofs);
>              Vector dataOfNeighboursOfElement_i;
>              neighbourData.GetSubVector(nbrDofs, dataOfNeighboursOfElement_i);
> }
> ```
> 
> Is this correct?

No, this isn't quite right. `vfes.GetFaceNbrElementVDofs` returns the DOFs associated with a given "face neighbor" element, i.e. a single element that is owned by a difference MPI rank. The index you pass should be the "face neighbor index", i.e. what you compute as `int neighbourFaceIndex = el2el[neighbourIterator] - parMesh_.GetNE();` You can do something like:
```c++
int neighbourFaceIndex = el2el[neighbourIterator] - parMesh_.GetNE();
Array <int> nbrDofs;
vfes.GetFaceNbrElementVDofs(neighbourFaceIndex, nbrDofs);
Vector nbrData;
elemMax_.FaceNbrData().GetSubVector(nbrDofs, nbrData);
```
At this point `nbrData` will contain the DOFs associated with the specified face neighbor element.

**Comment by makrandak** [comment]
Hello Will @pazner,  I understand now, I implemented this logic, I think because there are 4 unknowns in the flux vector the `nbrData` has to be reshaped into a matrix.  I select the first column from this matrix as these `ParGridFunctions` are piecewise constants so they should be the same whereever within the element they are sampled.   
```
for (int neighbourIterator = 0; neighbourIterator < el2el.Size(); neighbourIterator++) {
			Vector elementalMinPrimitive_i(inputData_->num_equation);
			Vector elementalMaxPrimitive_i(inputData_->num_equation);
			int neighbourIndex;
			bool onDifferentMPIProc;
			if (el2el[neighbourIterator] > parMesh_.GetNE()) {
				onDifferentMPIProc = true;
				int neighbourFaceIndex = el2el[neighbourIterator] - parMesh_.GetNE();
				neighbourIndex = neighbourFaceIndex;
			} else{
				onDifferentMPIProc = false;
				neighbourIndex = el2el[neighbourIterator];
			}
			if (onDifferentMPIProc) {
				Array <int> nbrDofs;
				vfes.GetFaceNbrElementVDofs(neighbourIndex, nbrDofs);
				Vector nbrDataMax;
				Vector nbrDataMin;
				elemMax_.FaceNbrData().GetSubVector(nbrDofs, nbrDataMax);
				elemMin_.FaceNbrData().GetSubVector(nbrDofs, nbrDataMin);
				DenseMatrix neighbourDofDataComnbinedMax(dof, inputData_->num_equation);
				DenseMatrix neighbourDofDataComnbinedMin(dof, inputData_->num_equation);
				neighbourDofDataComnbinedMax.UseExternalData(nbrDataMax.GetData(), dof, inputData_->num_equation);
				neighbourDofDataComnbinedMin.UseExternalData(nbrDataMin.GetData(), dof, inputData_->num_equation);
				elementalMinPrimitive_i = neighbourDofDataComnbinedMin.GetColumn(0);
				elementalMaxPrimitive_i = neighbourDofDataComnbinedMax.GetColumn(0);
			} else {
				TrNbr_it = parMesh_.GetElementTransformation(neighbourIndex);
				IntegrationPoint ipNbr_it = Geometries.GetCenter(TrNbr_it->GetGeometryType());
				elemMin_.GetVectorValue(neighbourIndex, ipNbr_it, elementalMinPrimitive_i);
				elemMax_.GetVectorValue(neighbourIndex, ipNbr_it, elementalMaxPrimitive_i);
			}
			elem_min.SetCol(neighbourIterator + 1, elementalMinPrimitive_i);
			elem_max.SetCol(neighbourIterator + 1, elementalMaxPrimitive_i);
``` 

When I run this I run into an assert
```
Assertion failed: (i>=0 && i<size) is false:
 --> Access element 3328 of array, size = 3328
 ... in function: const T& mfem::Array<T>::operator[](int) const [with T = mfem::Element*]
 ... in file: /home/makrand/Packages/blastfemdg/external/mfem/mesh/../general/array.hpp:718

application called MPI_Abort(MPI_COMM_WORLD, 1) - process 10
```

Not sure what sampling is going out of range. Do you have any ideas ?

**Comment by makrandak** [comment]
Hello @mlstowell 
Thanks for taking a look.  

> I see one potential issue with your implementation above. When you call GetVectorValue the integration point that you're using as an argument, FETrans->GetIntPoint(), is a point on the face and not the center of the element. The FETrans object has three ElementTransformation objects within it; one for the face itself and one for the elements on each side of that face. Each of these transformation objects could be evaluated at separate locations. I believe the integration point you want here is ip_nbr or you could use FETrans->Elem2->GetIntPoint(). These should be the same since you just set this.

These are piecewise constant `ParGridFunction` so it should not matter where I am sampling the Vector. But thanks for this tip, it is very useful. 

But is the logic for the rest of the loop correct ? Do I need to do anything special for elements on Dirichlet boundaries ? 
-Makrand

**Comment by pazner** [comment]
I haven't looked at your code in detail, but I do notice that `el2el[neighbourIterator] > parMesh_.GetNE()` should be replaced with `el2el[neighbourIterator] >= parMesh_.GetNE()`.

It may also help to debug your code to get a full backtrace to see where the error is occurring.

**Comment by mlstowell** [comment]
Hi @makrandak,

I didn't notice any other issues with the loop.  The faces on Dirichlet boundaries in MFEM are no different than any other boundary faces so they should require no special care in such a loop.

Best wishes,
Mark

**Comment by makrandak** [comment]
Hello Will @pazner ,

Yes, that was the issue, I forgot to add the edge case in the comparison.  It is running now.  I am testing both strategies one with shared faces from #1700 by @mlstowell and the other suggested by you. I will get back to both of you on whether it succeeds.  
Thanks for your help, really appreciate it. 

-Makrand

**Comment by makrandak** [comment]
Hello Mark @mlstowell 

Thanks for looking into it. I will test it further. Thanks for your help, really appreciate it. 
-Makrand
-Makrand

**Comment by makrandak** [comment]
Hello Will @pazner , 

I implemented both the approaches and I still see different results in parallel and serial in both of them.  The difference mainly comes on the boundaries of the processors.  I think the sampling the pargridfunction for elements not on the same process is still incorrect.  This is what I am trying.  The results in serial are correct.  I am using a Reimann 2D case to test this.  I can see the shocks are different for parallel compared to serial, I see weird patterns near the shock which align with the boundary of the processors, triggering extra instabilities. 

```
element2element.GetRow(i, el2el);
///----------------------------------------For neighbour elements----------------------------------------------///
for (int neighbourIterator = 0; neighbourIterator < el2el.Size(); neighbourIterator++) {
	Vector elementalMinPrimitive_i(inputData_->num_equation);
	Vector elementalMaxPrimitive_i(inputData_->num_equation);
	int neighbourIndex;
	bool onDifferentMPIProc;
	if (el2el[neighbourIterator] >= parMesh_.GetNE()) {
		onDifferentMPIProc = true;
		int neighbourFaceIndex = el2el[neighbourIterator] - parMesh_.GetNE();
		neighbourIndex = neighbourFaceIndex;
		Array <int> nbrDofs;
		vfes.GetFaceNbrElementVDofs(neighbourIndex, nbrDofs);
		Vector nbrDataMax(dof * inputData_->num_equation);
		Vector nbrDataMin(dof * inputData_->num_equation);
		elemMax.FaceNbrData().GetSubVector(nbrDofs, nbrDataMax);
		elemMin.FaceNbrData().GetSubVector(nbrDofs, nbrDataMin);
		for (int numEqIt = 0; numEqIt < inputData_->num_equation; numEqIt ++) {
			elementalMinPrimitive_i(numEqIt) = nbrDataMin(numEqIt);
			elementalMaxPrimitive_i(numEqIt) = nbrDataMax(numEqIt);
		}
	} else{
		onDifferentMPIProc = false;
		neighbourIndex = el2el[neighbourIterator];
		TrNbr_it = parMesh_.GetElementTransformation(neighbourIndex); ///  should this is be shared face index
		IntegrationPoint ipNbr_it = Geometries.GetCenter(TrNbr_it->GetGeometryType());
		elemMin.GetVectorValue(neighbourIndex, ipNbr_it, elementalMinPrimitive_i);
		elemMax.GetVectorValue(neighbourIndex, ipNbr_it, elementalMaxPrimitive_i);
	}
	elem_min.SetCol(neighbourIterator + 1, elementalMinPrimitive_i);
	elem_max.SetCol(neighbourIterator + 1, elementalMaxPrimitive_i);
}
```

**Comment by makrandak** [comment]
Hello all, 

Thanks for Will @pazner , we found the problem in the data sampling in the case where the elements are on a different processor. 

the correct piece of code is as follows,

```
///----------------------------------------For neighbour elements------------------------------------------------///
for (int neighbourIterator = 0; neighbourIterator < el2el.Size(); neighbourIterator++) {
	Vector elementalMinPrimitive_i(inputData_->num_equation);
	Vector elementalMaxPrimitive_i(inputData_->num_equation);
	int neighbourIndex;
	if (el2el[neighbourIterator] >= parMesh_.GetNE()) {
		int neighbourFaceIndex = el2el[neighbourIterator] - parMesh_.GetNE();
		Array <int> nbrDofs;

		elemMax_.ParFESpace()->GetFaceNbrElementVDofs(neighbourFaceIndex, nbrDofs);

		Vector nbrDataMax(inputData_->num_equation);
		Vector nbrDataMin(inputData_->num_equation);
		elemMax_.FaceNbrData().GetSubVector(nbrDofs, nbrDataMax);
		elemMin_.FaceNbrData().GetSubVector(nbrDofs, nbrDataMin);

		for (int numEqIt = 0; numEqIt < inputData_->num_equation; numEqIt ++) {
			elementalMinPrimitive_i(numEqIt) = nbrDataMin(numEqIt);
			elementalMaxPrimitive_i(numEqIt) = nbrDataMax(numEqIt);
		}
	} else{
		neighbourIndex = el2el[neighbourIterator];
		TrNbr_it = parMesh_.GetElementTransformation(neighbourIndex);
		IntegrationPoint ipNbr_it = Geometries.GetCenter(TrNbr_it->GetGeometryType());
		elemMin_.GetVectorValue(neighbourIndex, ipNbr_it, elementalMinPrimitive_i);
		elemMax_.GetVectorValue(neighbourIndex, ipNbr_it, elementalMaxPrimitive_i);
	}
	elem_min.SetCol(neighbourIterator + 1, elementalMinPrimitive_i);
	elem_max.SetCol(neighbourIterator + 1, elementalMaxPrimitive_i);
}
///--------------------------------------------------------------------------------------------------------------///
```

where `elemMax_`, `elemMin_`, are `ParGridFunctions` and `ExchangeFaceNbrData` has been called on them before the above sampling.  

Thanks all who wrote to help. Closing this issue. 

-Makrand
