### ISSUE TITLE
Evaluating "incoming" Boundary Faces

### ISSUE THREAD

**Issue by wcdawn** [mfem/mfem#1823]
I have a unit direction vector <img src="https://i.upmath.me/svg/%5Cbf%20%5Chat%20%5COmega" alt="\bf \hat \Omega" />.
I need to separate the boundary DOF into "incoming" and "outgoing" directions.
That is, for <img src="https://i.upmath.me/svg/%5Cbf%20%5Chat%20n" alt="\bf \hat n" /> being the outward normal direction, <img src="https://i.upmath.me/svg/%5Cbf%20%5Chat%20n%20%5Ccdot%20%5Cbf%20%5Chat%20%5COmega%20%3C%200" alt="\bf \hat n \cdot \bf \hat \Omega &lt; 0" /> (incoming) and <img src="https://i.upmath.me/svg/%5Cbf%20%5Chat%20n%20%5Ccdot%20%5Cbf%20%5Chat%20%5COmega%20%3E%200" alt="\bf \hat n \cdot \bf \hat \Omega &gt; 0" /> (outgoing).
Only "outgoing" directions will be solved for and "incoming" directions will be treated as a boundary condition.
I'd like to implement something like the following procedure.

1. Loop through all boundary faces and determine if <img src="https://i.upmath.me/svg/%5Cbf%20%5Chat%20%5COmega%20%5Ccdot%20%5Cbf%20%5Chat%20n%20%3C%200" alt="\bf \hat \Omega \cdot \bf \hat n &lt; 0" />. If this is in fact an incoming direction/face pair, mark it as such and add all DOF on the face to a set.
1. Remove all incoming directions from the `mfem::BilinearForm` using `mfem::BilinearForm::EliminateEssentialBCDiag()` and set the diagonal to unity.
1. Set the appropriate boundary condition value for incoming directions in the `mfem::LinearForm` somehow.

So far, I'm still struggling to loop through all boundary face elements.
I have found
```cpp 
int mfem::mesh::GetNFbyType(mfem::FaceType::Boundary);
```
but I don't know how to access a list of only boundary faces. Here is what I have written so far.
```cpp
for (int i=0; i < pmesh->GetNumFace(); ++i)
{
  int info1, info2;
  int element1, element2;
  
  pmesh->GetFaceElements(i, &element1, &element2);
  pmesh->GetFaceInfos(i, &element1, &element2);
  
  // determine if this is a boundary face
  if ((element2 < 0) && (info2 < 0))
  {
    // this is, in fact, a boundary face
    // calculate the outward normal (nhat)
    
    // if (omega*nhat<0)
    // {
    //    add all DOF in the face to a set of "incoming" directions
    // }
  }
}
```

Any help is appreciated. Thank you!

**Comment by wcdawn** [comment]
I have been able to obtain `nhat` so my pseudo-code is now as follows.
```cpp
for (int i=0; i < pmesh->GetNumFace(); ++i)
{
  int info1, info2;
  int element1, element2;
  
  pmesh->GetFaceElements(i, &element1, &element2);
  pmesh->GetFaceInfos(i, &element1, &element2);
  
  // determine if this is a boundary face
  if ((element2 < 0) && (info2 < 0)) // this is the criteria from mfem::mesh::GetNFbyType()
  {
    // this is, in fact, a boundary face
    // calculate the outward normal (nhat)
    ElementTransformation* const T{pmesh->GetFaceTransformation(i)};
    Vector nhat(3);
    nhat = 0.0;
    CalcOrtho(T->Jacobian(), nhat);
        
    if (omega*nhat < 0.0)
    {
      // TODO
      // this is an incoming space-angle-face combination
      // add all DOF in this face to a set of "incoming" directions
    }

  }
}
```

**Comment by wcdawn** [comment]
Another update, it looks like I will be using `mfem::BilinearForm::EliminateEssentialBCFromDofsDiag()` but I still need to figure how how to obtain a list of all DOF on a face, not simply all vertices on a face.

**Comment by v-dobrev** [comment]
For problems with inflow boundary conditions, it is better (more stable) to use a weak formulation instead of fixing inflow dofs. This is what we use in Example 9/9p. The way this works is that you add a boundary face term to the bilinear form: https://github.com/mfem/mfem/blob/2d62a136d0262be7689eb134524b81c180026047/examples/ex9.cpp#L296-L297
and a boundary face term (with the inflow b.c.) to the linear form: https://github.com/mfem/mfem/blob/2d62a136d0262be7689eb134524b81c180026047/examples/ex9.cpp#L300-L301
In both cases, the `velocity` is your `\Omega` direction. These integrators automatically find which boundary faces are inflow or outflow and handle them appropriately.

Does this sound like something you can use in your code?

**Comment by wcdawn** [comment]
This looks like it would be useful.

I'm using continuous FE. Would I still be able to use the `DGTraceIntegrator` as long as I set the `rho` parameter to one (as in example 9)? I also don't understand the purpose of the `TransposeIntegrator`.

I have some work to do to figure out how to rearrange terms. Are `alpha` and `beta` set such that the direction is "incoming" or "outgoing" or are there other numerical properties as well?

**Comment by v-dobrev** [comment]
Yes, this approach should work fine with continuous elements. In your case, you don't need to set `rho` which will be treated as setting it to `1`.

The role of the `TransposeIntegrator` is to switch the arguments in the given `BilinearFormIntegrator` which corresponds to transposing the matrix.

The `alpha` and `beta` in the Example 9 correspond to specifying inflow (or incoming) b.c. as determined by the given `velocity` field.

**Comment by wcdawn** [comment]
This can be closed. We have reevaluated the structure of the equations in our model, in part to avoid some of these boundary condition problems.

Thank you to @v-dobrev to your helpful response!
