### ISSUE TITLE
Parallel Assemble Linear Form

### ISSUE THREAD

**Issue by vikramsg** [mfem/mfem#183]
To solve the Euler or NS equations, I created a linear form for all interior faces like this. 

``` 
  ParLinearForm *b = new ParLinearForm(fes);
  b->AddFaceIntegrator(
      new DGEulerIntegrator(u_vec, f_vec, var_dim, -1.0));
```

What this does is that for all faces it takes the left value at the face from Elem 1 and the right value from Elem 2 and does a Riemann solve to get the common value which is a non-linear operator. Then the common value is extrapolated back to the nodal values. Since it is a non-linear operation I can't use the bilinear form and so have to use the linear form and assemble at each time step. 

This works fine in the serial case. But I see now that in the parallel case, faces don't know anything about their global neighbors when we do Assemble in the linear form. In pbilinearform.cpp, on the other hand, it seems to me that the overloaded Assemble actually sends the global neighbours, whereas the plinearform.cpp does not have an overloaded assemble but has a parallel assemble (I don't really understand what it does).

Is this correct. To correct this do I need to write a similar overloaded Assemble and AssembleSharedFaces as pbilinearform.cpp?

EDIT: I am doing it in the following manner. But inside AssembleRHSElementVect, it segfaults at 
```
Trans.Loc1.Transform(ip, eip1);
```
Is there some kind of data exchange step I need to do first?

```
void ParLinearForm::AssembleSharedFaces()
{
   ParMesh *pmesh = pfes->GetParMesh();
   FaceElementTransformations *T;
   Array<int> vdofs, vdofs2;
   Vector elemvect;

   int nfaces = pmesh->GetNSharedFaces();
   for (int i = 0; i < nfaces; i++)
   {
       T = pmesh->GetSharedFaceTransformations(i);
       pfes->GetElementVDofs(T->Elem1No, vdofs);
       pfes->GetFaceNbrElementVDofs(T->Elem2No, vdofs2);

       vdofs.Append(vdofs2);

       for (int k = 0; k < ilfi.Size(); k++)
       {
          ilfi[k] -> AssembleRHSElementVect (*pfes->GetFE(T -> Elem1No),
                                             *pfes->GetFE(T -> Elem2No),
                                             *T, elemvect);

//          AddElementVector (vdofs, elemvect);
       }

   }
}
void ParLinearForm::Assemble()
{
   LinearForm::Assemble();

   if (ilfi.Size() > 0)
   {
      pfes->ExchangeFaceNbrData();
      AssembleSharedFaces();
   }
}

```

**Comment by vikramsg** [comment]
I had a re-look at this and wanted to do this a different way. I looked at DGTraceIntegrator and I see that there is in-fact a non-linear coefficient there. The problem I see is that all co-efficients used are essentially either function co-efficient or constant co-efficient. I looked at example 14p, and instead of 

```
a->AddInteriorFaceIntegrator(new DGDiffusionIntegrator(one, sigma, kappa)); 
```

I did

```
FunctionCoefficient u_init(u0_function);
ParGridFunction *u = new ParGridFunction(fespace);
u->ProjectCoefficient(u_init);
GridFunctionCoefficient u_coeff(u);

a->AddInteriorFaceIntegrator(new DGDiffusionIntegrator(u_coeff, sigma, kappa));
```

And I get the same segfaults if I used more than 1 processor. If I can get pointers in how to solve this, I think I can solve my original problem. 

Vikram

**Comment by vladotomov** [comment]
Hi Vikram,
I was able to run ex14p with the code below, but indeed it segfaults without the ExchangeFaceNbrData( ).

`
   ParGridFunction *u = new ParGridFunction(fespace);
   *u = 1.0;
   GridFunctionCoefficient u_coeff(u);
   u->ExchangeFaceNbrData();
   ...
   a->AddInteriorFaceIntegrator(new DGDiffusionIntegrator(u_coeff, sigma, kappa));
`

**Comment by vikramsg** [comment]
Thanks Vladimir,

While my idea to use Bilinear Form did not work out, your pointer was enough for me to implement the plinearform to make it work. It now works in parallel as well. 

I do have another question though. When I setup the evolution class I do 

```
FE_Evolution::FE_Evolution(HypreParMatrix &_M, HypreParMatrix &_K_inv_x, ..... , HypreParVector &_B)
```

I setup b using

```
ParLinearForm *b = new ParLinearForm(fes);
b->AddFaceIntegrator(
         new DGEulerIntegrator(u_vec, f_vec, var_dim, -1.0));
u_sol->ExchangeFaceNbrData();
f_inv->ExchangeFaceNbrData();
b->Assemble(); 

HypreParVector *B       = b->ParallelAssemble();
```

The problem is that at each time step I do b->Assemble(), but b does not update inside FEEvolution. I have replaced 

```
FE_Evolution::FE_Evolution(HypreParMatrix &_M, HypreParMatrix &_K_inv_x, ..... , HypreParVector &_b)
```
with 
```
FE_Evolution::FE_Evolution(HypreParMatrix &_M, HypreParMatrix &_K_inv_x, ..... , Vector &_b)
```
for now, but I hope it is not a problem somewhere down the line.

**Comment by vladotomov** [comment]
This will update b in FE_Evolution, but it doesn't allow you to call b.ParallelAssemble( ) at every time step. It might not be needed, depending on your assembly in DGEulerIntegrator. Still, make sure that giving the Vector b (instead of the HypreParVector B) to the solver is the same.
Vladimir

**Comment by vikramsg** [comment]
Thanks Vladimir.
