### ISSUE TITLE
How can I change the values of a VectorCoefficient ?

### ISSUE THREAD

**Issue by LeilaSalomon** [mfem/mfem#1831]
Hello !

I'm using a GradientGridFunctionCoefficient to solve a linear system.

I have a Grid that I denote A. I get the gradient of A in the following way :
GradientGridFunctionCoefficient  **Grad_A** (&A).

I would like to be able to change values of the VectorCoefficient **Grad_A** before using it for the resolution of my system. Is it possible ?

**Comment by mlstowell** [comment]
Hi, @LeilaSalomon ,

There are many possibilities depending on what types of changes the values need.  In MFEM `Coefficient` and `VectorCoefficient` classes don't typically precompute the values they return.  Instead they just contain instructions on how to compute those values.  In the case of the `GradientGridFunctionCoefficient` it only knows how to extract the gradient from `A` and return it. If the `GridFunction`, `A`, changes its values during the course of a simulation the values returned by `GradientGridFunctionCoefficient` will automatically change the next time this `VectorCoefficient` is used.

It's also possible to write a custom `VectorCoefficient` which performs some sort of operation on the values returned by `Grad_A` before returning the altered values.  I'm not sure if this is the type of change you had in mind but we could go into more detail if that would help.

Another possibility is to compute the gradient of `A` as a separate `GridFunction` whose values can be reused, or perhaps manipulated, if that's what you had in mind.

Best wishes,
Mark
