### ISSUE TITLE
GridfunctionCoefficient for VectorDiffusionIntegrator using partial assembly

### ISSUE THREAD

**Issue by Jxt1** [mfem/mfem#1836]
Dear Developers of MFEM,

Right now I'm working with the navier-stokes mini-app and I'm trying to implement a non-constant viscosity. The current viscosity is a constant and I'm planning to replace it with a ``` GridFunctionCoefficient```. The current code is the following:

```c++
      ConstantCoefficient H_lincoeff;
      ConstantCoefficient H_bdfcoeff;

      H_lincoeff.constant = kin_vis;
      H_bdfcoeff.constant = 1.0 / dt;
      H_form = new ParBilinearForm(vfes);
      H_form->AddDomainIntegrator(new VectorMassIntegrator(H_bdfcoeff));
      H_form->AddDomainIntegrator(new VectorDiffusionIntegrator(H_lincoeff));
      if (partial_assembly)
      {
         H_form->SetAssemblyLevel(AssemblyLevel::PARTIAL);
      }
      H_form->Assemble();
      H_form->FormSystemMatrix(vel_ess_tdof, H);

```
If I change ```ConstantCoefficient``` to ```GridFunctionCoefficient```, due to the partial assembly condtion of the navier miniapp, the ```VectorDiffusionIntegrator``` calls a ```AssemblePA``` from fem/bilininteg_vecdiffusion.cpp and it specifically requires all coefficient to be constant.

```c++
   if (Q)
   {
      ConstantCoefficient *cQ = dynamic_cast<ConstantCoefficient*>(Q);
      MFEM_VERIFY(cQ != NULL, "only ConstantCoefficient is supported!");
      coeff = cQ->constant;
   }
```
My question is the following:

Under the parallel partial assembly setting, can ```VectorDiffusionIntegrator``` use gridfunction as coefficient? If it cannot, can we use other operators to achieve same result?

Thanks for your time,

**Comment by jandrej** [comment]
You are correct, it is currently not possible to use any other coefficient than `ConstantCoefficient` for the viscosity in the navier miniapp due to the limitation in the `VectorDiffusionIntegrator` integrator.

**Comment by v-dobrev** [comment]
It looks like in the latest `master` this is possible by using the libCEED library. @YohannDudouit, is this correct?

**Comment by Jxt1** [comment]
> You are correct, it is currently not possible to use any other coefficient than `ConstantCoefficient` for the viscosity in the navier miniapp due to the limitation in the `VectorDiffusionIntegrator` integrator.

Thank you for the reply. In this case I have a followup question. Based on my understanding of VectorDiffusionIntegrator, it is possible to use GridfunctionCoefficient in the full assembly setting. Can navier miniapp work if the partial assembly is switched to full assembly?

In fact, the program runs in full assembly.

**Comment by jandrej** [comment]
You can use `GridfunctionCoefficient` in full assembly, yes.

It is also possible to implement `GridfunctionCoefficient ` support for `VectorDiffusionIntegrator` in the partial assembly setting. Contributions are always welcome and we can support you in the process when needed.

**Comment by YohannDudouit** [comment]
Using MFEM with the libCEED library also provides support for `VectorDiffusionIntegrator`, and #1766 adds support for `ConvectionIntegrator` and `VectorConvectionNLFIntegrator`, so the mini-app can fully run with libCEED, is it correct @jandrej ?

**Comment by jandrej** [comment]
It should, but it requires a separate branch and the libceed third party library.
