### ISSUE TITLE
Python Post-processing tools

### ISSUE THREAD

**Issue by varchasgopalaswamy** [mfem/mfem#1838]
Hi,

First off, this is a really nice library and I've been enjoying working with it so far. 

I am trying to check the results of some modifications I've made to the Laghos mini-app. So far I have the application producing output using the VisItDataCollection or the ConduitDataCollection helpers, and I can view it in VisIt and confirm that the results are qualitatively reasonable. However, I would also like to check that my modifications are quantitatively correct. For example, a nice check would be evaluating the GridFunction corresponding to the internal energy along some line and comparing with the analytic solution. 

I guess this is something that would be easy enough to accomplish in C++, using the code in the `GetValues` miniapp as a starting point for loading in the solution and evaluating the relevant grid functions. 

My questions are: 
1) Is the `GetValues` miniapp approach the correct way to do something like this? 
2) Are there existing tools or wrappers to to do this with python? I have a rather large existing post-processing codebase already in python, which I'd like to leverage if possible. I noticed that pyMFEM exists, but it didn't seem like there were any wrappers for the `DataCollection` classes. 

Thanks,
Varchas

**Comment by mlstowell** [comment]
Hi, @varchasgopalaswamy,

I'm glad to hear that your initial impression of MFEM is a good one.  I hope you'll continue to find it useful.

This is precisely what the `get_values` mini app was written to accomplish.  The use case was to extract field values from an existing set of VisIt output files and pass these to Matlab or Python for plotting or comparison without altering the original simulation code.

I'm not aware of existing Python wrappers for this type of post-processing, @sshiraiwa would be the expert on this.  

There are, of course, other ways to post process data which may be more efficient in the long run but `get_values` should provide a reasonable first step. For example, pyMFEM could provide a way to streamline the process by avoiding the use of intermediate ascii data files.  Also, if you have an analytic solution it would be possible to compute a global L^2 error either within your simulation code or as a post-processing step ([`ex3p.cpp`](https://github.com/mfem/mfem/blob/master/examples/ex3p.cpp) preforms such an error calculation, for example).

Best wishes,
Mark

**Comment by varchasgopalaswamy** [comment]
Aha! That ex3p example is pretty neat. I'll look more into both - it's definitely nice to have inline error estimate calculations when running test programs. 

Does `ComputeL2Error` already call an MPI_REDUCE, or do I have to do that afterwards? I'm guessing it already does by how ex3p is written.

**Comment by mlstowell** [comment]
Yes, `ComputeL2Error` calls `MPI_Allreduce` and returns the same result on all processors.

**Comment by sshiraiwa** [comment]
I will take a look at DataCollectionn whem MFEM 4.2 is out (supposedly it is very soon).
Normally, since I use MFEM from GUI  on Python (see for example, https://piscope.psfc.mit.edu/index.php/TE10_mode_in_Rectangular_Waveguide), I didn't pay much attention on DataCollection part. This will be a good motivation for me.
Also, I think we should be able to do pip install mfem (or PyMFEM), for which I will like to discuss with other people off-line.

**Comment by rw-anderson** [comment]
+1 for 'pip install pymfem'. That would be very useful.

**Comment by tzanio** [comment]
MFEM 4.2 is out now 😁

**Comment by sshiraiwa** [comment]
Congratulations. 
 
While working on PyMFEM 4.2, it looks like following two are defined in header
but not implemented anywhere???
   CrossCrossCoefficient(double A, VectorCoefficient &K);
   MassIntegrator::SetupPA

**Comment by tzanio** [comment]
@mlstowell and @YohannDudouit, can you take a look at these two methods?

**Comment by mlstowell** [comment]
I just created a small PR (#1872 ) to implement the missing `CrossCrossCoefficient` constructor.  Sorry for the delay.

**Comment by tzanio** [comment]
Discussion continued in #1872
