### ISSUE TITLE
Transpose of HypreSmoother

### ISSUE THREAD

**Issue by chakshinglee** [mfem/mfem#1846]
Currently `HypreSmoother::MultTranspose` is not defined. I am writing some multigrid that assumes the application of transpose of some solver/smoother during the multigrid cycle. So the code breaks when `HypreSmoother::MultTranspose` is called.

Is it because all the smoothers are symmetric so `Mult` is sufficient? Or the transposes of some of the smoothers are not easy to define? Can we at least redirect `MultTranspose` to `Mult` whenever the smoother is symmetric?

**Comment by barker29** [comment]
Looking at the code for `hypre_ParCSRRelax` it looks to me like all the Hypre smoothers are symmetric, so I recommend just adding a `HypreSmoother::MultTranspose` method that calls `Mult`. But I'm not entirely sure I'm right about hypre so maybe we should ask an expert?

**Comment by v-dobrev** [comment]
I think redirecting `MultTranspose` to `Mult` makes sense when the corresponding operator is symmetric. When it is not symmetric, or unknown, we can through an error, for now.

**Comment by tzanio** [comment]
Currently all the smoother options in `HypreSmoother` are symmetric

**Comment by v-dobrev** [comment]
> Currently all the smoother options in `HypreSmoother` are symmetric

This is probably assuming (at least in some cases) that the `HypreParMatrix` is also symmetric.

**Comment by tzanio** [comment]
@chakshinglee, do you want to propose a PR for this?

I think there is generally no assumption for symmetry in the hypre smoothers, but we can discuss that in the PR...

**Comment by chakshinglee** [comment]
Yes, I will submit a PR. Briefly, I am thinking to just add a flag to indicate symmetry so that the users can turn it on in the case when symmetry of the operator/smoother is known to them.

**Comment by tzanio** [comment]
Thanks Chak. Discussion continued in #1879.
