### ISSUE TITLE
link broken for Navier: solver for the incompressible time-dependent Navier-Stokes equations

### ISSUE THREAD

**Issue by QiangWei-Wade** [mfem/mfem#1849]
Looks like the link (http://mfem.github.io/doxygen/html/navier_solver_8cpp_source.html) to [Navier: solver for the incompressible time-dependent Navier-Stokes equations] is broken.

From page https://mfem.org/features/

**Comment by jandrej** [comment]
Thank you for pointing this out. The doxygen documentation is only updated after a release. So it will be available with mfem 4.2.

**Comment by tzanio** [comment]
The `Navier` link should be OK now.
