### ISSUE TITLE
ParMixedBilenearForm system matrix and linear system

### ISSUE THREAD

**Issue by alecampos2009** [mfem/mfem#1850]
I see that the class ParBilinearForm includes the two functions
```using BilinearForm::FormLinearSystem;```
```using BilinearForm::FormSystemMatrix;```
whereas ParMixedBilinearForm does not.

Seems like those two functions allow the ParBilinearForm class to form the linear system and system matrix using an operator type, rather than just an operator handle, as input. Since ParMixedBilenearForm does not include
```using MixedBilinearForm::FormRectangularLinearSystem;```
```using MixedBilinearForm::FormRectangularSystemMatrix;```
the linear system and system matrix can only be formed using an operator handle, rather than operator type, as input. Is there a reason for why this functionality of ParBilinearForm and ParMixedBilinearForm is not consistent? If not, could they be made consistent? I would like to form a rectangular system matrix using an operator type as input, rather than an operator handle.

**Comment by v-dobrev** [comment]
The versions of `FormSystemMatrix`/`FormLinearSystem` that work with a given `Operator` type are basically a thin convenience wrapper around the `OperatorHandle` version, as can be seen here: https://github.com/mfem/mfem/blob/de4a24b0ff7e723dfbdd7f6c0920ed372b98995b/fem/bilinearform.hpp#L436-L450

 Adding similar wrappers for `FormRectangularSystemMatrix`/`FormRectangularLinearSystem` should be fairly straightforward, I think.

**Comment by alecampos2009** [comment]
Great, thanks, having those wrappers would be quite useful to me.

**Comment by tzanio** [comment]
Hi @alecampos2009, are you comfortable proposing a PR with  the above modification?

**Comment by alecampos2009** [comment]
Yes, supposedly it is just a couple of lines so I can go ahead a propose a PR with the above modification, as well as test it with the case that sparked my interest in these wrappers.

**Comment by alecampos2009** [comment]
I added the wrappers but run into some difficulties. 

I added the lines
```using MixedBilinearForm::FormRectangularSystemMatrix;```
```using MixedBilinearForm::FormRectangularLinearSystem;```
in the ParMixedBilinearForm class, so as to be consistent with the wrappers in the ParBilinearForm class. I also had to change the function 
```void FormRectangularSystemMatrix(const Array<int> &trial_tdof_list, cost Array<int> &test_tdof_list, OperatorHangle &A)``` in the MixedBilinearForm class, so that the appropriate definition is used by ParMixedBilinearForm. I then tested this new functionality in my own code as well as in ex5p.cpp, by including the following lines
```
HypreParMatrix test;
bVarf->FormRectangularSystemMatrix(Array<int>(), Array<int>(), test);
```
This unfortunately gave me a seg fault. I'm not quite sure I've implemented things correctly, or how one would go about tracking this segfault.

**Comment by cjvogl** [comment]
>  Seems like I'm unable to push my branch to the repo to share and discuss the changes I've made. The error I get has code 403. Is this because I am a member of mfem/users only and not mfem/collaborators?

Yes, that sounds like the reason: I believe @tzanio or @v-dobrev have to add you to the mfem/collaborators group to have push access to the repo.  I suppose an alternative would be to create a fork of the mfem repo and open a PR from a branch in that fork.

**Comment by tzanio** [comment]
Sorry for the delay @alecampos2009, you should be able to push now.

**Comment by tzanio** [comment]
@alecampos2009, were you able to resolve this?

**Comment by alecampos2009** [comment]
Yes, we were able to figure out the issue (see PR https://github.com/mfem/mfem/pull/1940). Will wrap this up after I get back from my holiday vacation.

**Comment by tzanio** [comment]
Excellent, I'll close this issue then. Feel free to reopen if necessary.
