### ISSUE TITLE
Additional method in GridFunction class

### ISSUE THREAD

**Issue by makrandak** [mfem/mfem#1853]
Hello all, 

I wrote a simple method which should be part of `GridFunction` class, it calculates `min` and `max` over the deg of freedom in an element.  I was wondering what is the best way to incoporate it in the `GridFunction` class?  

One idea was to write a derived `GridFunction` class and have it in that class.  But, that seemed a bit excessive to me for only one method.  
THe method is as follows: 
```
void GridFunction::GetElementBounds(GridFunction &Min, GridFunction &Max) const {
	Array<int> dofs, dofsbounds;
	Vector loc_this;

	Min = 0.0;
	Max = 0.0;
	for (int i = 0; i < fes->GetNE(); i++) {
		fes->GetElementDofs(i, dofs);
		Min.FESpace()->GetElementDofs(i, dofsbounds);
		GetSubVector(dofs, loc_this);
		double min = numeric_limits<double>::infinity();
		double max = -numeric_limits<double>::infinity();
		for (int d = 0; d < dofs.Size(); d ++) {
			min = std::min( min, loc_this(d) );
			max = std::max( max, loc_this(d) );
		}
		Min.SetSubVector(dofsbounds, min);
		Max.SetSubVector(dofsbounds, max);
	}
}
```
Do you have any suggestions ? 

-Makrand

**Comment by tzanio** [comment]
Hi Makrand,

Is there an issue with modifying your local clone of MFEM to add this method (possibly in a branch)?

Alternatively, you can create a free function that could be just in your application without modifying mfem, something like:

```c++
void GetElementBounds(const GridFunction &gf, GridFunction &Min, GridFunction &Max);
```

Hope this helps,
Tzanio

**Comment by makrandak** [comment]
Hello Tzanio, 

I am reluctant to change my local clone of mfem as I have set it up as git submodule in my library and I want to keep it as close to master branch of mfem as much as possible. 

Creating a local function is a great idea, will try that and get back to you how it goes. Thanks for your help. 

-Makrand
