### ISSUE TITLE
Static analysis

### ISSUE THREAD

**Issue by xianyu-gao** [mfem/mfem#1860]
I want to use MFEM to solve Static analysis,but i don't know how to load Force.May be neumann boundary condition?

**Comment by tzanio** [comment]
Can you elaborate? Are you trying to solve an elasticity problem like Example 2?

**Comment by xianyu-gao** [comment]
I want to I want to load force and fixed constraints on an object, and solve for displacement and equivalent stressload force on

**Comment by xianyu-gao** [comment]
I want to load force and fixed constraints on an object, and solve for displacement and equivalent stress

**Comment by tzanio** [comment]
This is what Example 2 does: https://github.com/mfem/mfem/blob/master/examples/ex2.cpp

Can you try it and let us know if it works for you?

**Comment by xianyu-gao** [comment]
do you have Wechat,i want to chat with you on Wechat

**Comment by tzanio** [comment]
Sorry, but we only provide support via this GitHub issue tracker.
