### ISSUE TITLE
Poor parallel assembly efficiency when using 2 cores

### ISSUE THREAD

**Issue by hongbo-yao** [mfem/mfem#1863]
Hi everyone:

I tested the parallel assembly efficiency using  ex22p (minor modified), I found that the assembly MPI_Wtime (Assemble() + FormLinearSystem()) for np=2 is much more than that of np=1. The following are run commands and outputs:

**mpirun -np 1 ./ex22p**
Number of finite element unknowns: 14889600

System matrix Assembly...
System matrix Assembly (Assemble+FormLinearSystem) MPI_Wtime: 186.349 (s)
Size of linear system: 29779200

Preconditioning matrix Assembly...
Preconditioning matrix Assembly (Assemble+FormLinearSystem) MPI_Wtime: 140.29 (s)

Completed

**mpirun -np 2 ./ex22p**
Number of finite element unknowns: 14889600

System matrix Assembly...
System matrix Assembly (Assemble+FormLinearSystem) MPI_Wtime: 404.09 (s)
Size of linear system: 29779200

Preconditioning matrix Assembly...
Preconditioning matrix Assembly (Assemble+FormLinearSystem) MPI_Wtime: 142.744 (s)

Completed

**mpirun -np 4 ./ex22p**
Number of finite element unknowns: 14889600

System matrix Assembly...
System matrix Assembly (Assemble+FormLinearSystem) MPI_Wtime: 130.681 (s)
Size of linear system: 29779200

Preconditioning matrix Assembly...
Preconditioning matrix Assembly (Assemble+FormLinearSystem) MPI_Wtime: 71.3651 (s)

Completed

As we can see, the poor parallel assembly efficiency happened when np=2, please note that the larger the problem size, the  greater the difference. 

One possible reason for this may be the exchange between two cores, but I guess something else also contribute to this since the time difference is too large, especially when we increase the problem size. Do you have any idea about this?  

Here are all materials (Please also note that the problem size may be too large to run on a personal computer):
[beam-tet.mesh.txt](https://github.com/mfem/mfem/files/5481717/beam-tet.mesh.txt)
[ex22p.cpp.txt](https://github.com/mfem/mfem/files/5481718/ex22p.cpp.txt)
[makefile.txt](https://github.com/mfem/mfem/files/5481720/makefile.txt)
[np1.log.txt](https://github.com/mfem/mfem/files/5481723/np1.log.txt)
[np2.log.txt](https://github.com/mfem/mfem/files/5481725/np2.log.txt)
[np4.log.txt](https://github.com/mfem/mfem/files/5481726/np4.log.txt)

Thank you for your discussions and helps

**Comment by tzanio** [comment]
Some slowdown is expected when going from serial to MPI parallel execution, but to be sure, can you try a similar test with `ex1p`? 

Also, can you provide details about your parallel environment?

**Comment by hongbo-yao** [comment]
Hi @tzanio,
Thank you for your reply

My **parallel environment** is listed as follows:
**Parallel environment**: 2*Intel Xeon Platinum 8270 CPU，576GB memory, 52 cores in total
**Software**: openmpi-4.0.5, mfem-4.2, metis-5.1.0, hypre-2.19

I just did  a similar test with ex1p, similar results were obtained:

**mpirun -np 1 ./ex1p**
Number of finite element unknowns: 17057025
System matrix Assembly...
System matrix Assembly (Assemble+FormLinearSystem) MPI_Wtime: 106.08 (s)

**mpirun -np 2 ./ex1p**
Number of finite element unknowns: 17057025
System matrix Assembly...
System matrix Assembly (Assemble+FormLinearSystem) MPI_Wtime: 284.467 (s)

**mpirun -np 4 ./ex1p**
Number of finite element unknowns: 17057025
System matrix Assembly...
System matrix Assembly (Assemble+FormLinearSystem) MPI_Wtime: 95.6098 (s)

As you said: '_Some slowdown is expected when going from serial to MPI parallel execution_'
Yes, I can't agree with you more. But, I have to report similar test with ex22p for a larger problem size:

![ex22p_large_scale_assembly_time](https://user-images.githubusercontent.com/44011619/98056347-b0717100-1e7a-11eb-855e-0595e1a05114.png)

The time difference is too large, can we just simply attribute this  to the additional parallel overhead?

**Comment by v-dobrev** [comment]
Can you try separating the assembly times into two parts: one for `a->Assemble()` and second one for `a->FormLinearSystem(...)`? I expect the first one to scale very well and the second one to have big overhead going from 1 to 2 processors. One big part of the call to `a->FormLinearSystem(...)` is a triple parallel sparse matrix multiplication (`A = P^t A_local P`) which may be the reason for the big jump from 1 to 2 processors.

**Comment by hongbo-yao** [comment]
Hi, @v-dobrev 
Yes, you are right. The _Assemble()_ function  scales very well, but the function _FormLinearSystem(...)_ doesn't. Please see outputs for details:

**mpirun -np 1 ./ex22p**
Number of finite element unknowns: 14889600

Calling Assemble()...
MPI_Wtime for Assemble(): 75.9384 (s)

Calling FormLinearSystem()...
MPI_Wtime for FormLinearSystem(): 51.5885 (s)


**mpirun -np 2 ./ex22p**
Number of finite element unknowns: 14889600

Calling Assemble()...
MPI_Wtime for Assemble(): 38.1217 (s)

Calling FormLinearSystem()...
MPI_Wtime for FormLinearSystem(): 164.404 (s)

To my understanding, the main reason for separating  finite element concepts from linear algebra concepts is to better handle non-conforming hexahedral meshes, so we can add constraint to eliminate some dofs. However, this may cause additional computations for some cases, e.g., tetrahedral meshes.

As we can see from the above table (see figure in my previous comments),  the problem size is 25,670,659, and the **system matrix assembly time**  is about 3 min for np=1, but that is about 41 min for np=2!

So is it possible to add one  **_if-else_** statement, when the TDOF is equals to DOF, we can avoid this triple parallel sparse matrix multiplication (A = P^t A_local P) ?

It's only a suggestion, but I think is would be very useful, especially for large-scale problems.
