### ISSUE TITLE
Import SALOME mesh to MFEM

### ISSUE THREAD

**Issue by vkorchagova** [mfem/mfem#1867]
Good evening,

Could MFEM import mesh generated in the SALOME platform?
SALOME could export mesh in DAT, MED, UNV, CGNS, STL, GMF, SAUV formats. Could MFEM read some of these formats?

--
Best regards,
Victoria Korchagova

**Comment by v-dobrev** [comment]
We do not support any of these formats directly. However, you may be able to convert it to one of the formats that MFEM can read, e.g. VTK, Gmsh, or NetCDF/Genesis (the NetCDF format requires MFEM built with the NetCDF library). One option for doing the conversion is to use VisIt (https://visit.llnl.gov) and convert from CGNS to VTK. See https://wci.llnl.gov/simulation/computer-codes/visit/faqs/faq04 for a list of the data formats supported by VisIt. Another option may be to use Gmsh (https://gmsh.info/).

**Comment by benzwick** [comment]
Another option is to create a SALOME plugin like this one: https://gitlab.com/benzwick/abqmesh

Please feel free to fork and modify it to export MFEM files...

**Comment by vkorchagova** [comment]
Many thanks for answers; I would try to use VisIt to convert SALOME mesh to VTK format!

**Comment by vkorchagova** [comment]
Hello again, 
VTK writer in VisIt gives me vtk file v.4.2. MFEM couldn't read this file and writes to me about unknown mesh format. The same story with the "XML" vtk. Which converters or tools should I use for successful mesh reading?..

**Comment by v-dobrev** [comment]
Can you try replacing the string "4.2" in the first line of the `.vtk` file with "3.0"? This worked for a few simple meshes I tried.

You can also try the new VTK reader from PR #975 -- it should be able to read both the ASCII and XML VTK files without having to change "4.2" to "3.0". If you run into any issues with the PR, let us know and we'll try to fix it.

**Comment by vkorchagova** [comment]
I tried to replace 4.2 to 3.0; it read ASCII files (not binary) and could not support cell type 42.
New VTK reader also checked VTK version and didn't work with v. 4.2. I tried to read XML but it was the error `MFEM abort: Unknown input mesh format: <?xml version="1.0"?>` When I tried to remove the first line in the mesh file, I got `MFEM** abort: Unknown input mesh format: <VTKFile type="UnstructuredGrid" version="0.1" byte_order="LittleEndian" header_type="UInt32">`

**Comment by v-dobrev** [comment]
Cell type 42 is (see https://vtk.org/doc/nightly/html/vtkCellType_8h_source.html)
```c++
   // Polyhedron cell (consisting of polygonal faces)
   VTK_POLYHEDRON = 42,
```
and general polyhedra are not supported in MFEM. This may be just a conversion artifact though. What types of elements do you have in the original mesh?

Do you have a small sample mesh in the format that you open in VisIt? For example in CGNS format, if that is what you use. If you can post it here, I can try to figure out a way to convert it to a format that MFEM can read.

**Comment by vkorchagova** [comment]
Hmm. Polyhedral cells could be marked by OpenFOAM - it was only my trick to create a mesh by another tool (not in SALOME) and save it into VTK format. In fact, it was a box with one refinement region. All cells were hexahedrons and prisms, but OpenFOAM could mark them as general polyhedral cells.

I've tried to create a simple mesh. OpenFOAM could convert mesh to VTK format, but this format is not supported by MFEM. I tried to open it in VisIt and resave it in other VTK. You can find this mesh attached.
[VTK.tar.gz](https://github.com/mfem/mfem/files/5659210/VTK.tar.gz)

**Comment by bslazarov** [comment]
Hi,

Perhaps an easier way would be to export the mesh in MED format and convert it to native GMSH format with GMSH. When writing it out from GMSH it is important to define physical volumes and surfaces and to write in the old 2.2 text format.

**Comment by v-dobrev** [comment]
@vkorchagova, did the above suggestion by @bslazarov work for you?

**Comment by vkorchagova** [comment]
The best way is to save SALOME mesh to UNV format, convert UNV mesh to MSH by gmsh; then read MSH mesh by MFEM.

**Comment by tzanio** [comment]
ping: @thelfer, @latug0

**Comment by thelfer** [comment]
Hi @vkorchagova,
my colleagues at CEA have developped direct support for MED in a private fork of MFEM.
We want to make a PR soon. If interested for testing, let us know.
Best,
Thomas

**Comment by emorell96** [comment]
@thelfer any update on that? Any chance you could share the code required for supporting MED? Thanks.

**Comment by thelfer** [comment]
@emorell96 Unfortunately, this development is stalled...
