### ISSUE TITLE
Rationale of `NonlinearForm` and `NonlinearFormIntegrator` design and guidance for non linear mechanics

### ISSUE THREAD

**Issue by thelfer** [mfem/mfem#1868]
Dear `MFEM`  developpers,
I am working a non linear mechanics solid mechanics on top of `MFEM`. We are in the very early stage of development.
I am focused on linear consistitutive equations.
Following the hyperelastic examples, I derived a new `NonlinearFormIntegrator` class. I think that the only methods that I have to implement are the `AssembleElementVector` (inner forces) and `AssembleElementGrad` (stiffness matrix). My trouble is to know when to call my non linear constitutive equations which compute both the stress (used in  `AssembleElementVector`) and the consistent tangent operator (used in  `AssembleElementGrad`). In the hyperelastic cases, those two steps can be efficiently separated, but this is suitable for my needs.
I already mentionned that on a previous Issue. @rcarson3 kindly informed me on the `ExaConstit` project which is a great source of inspiration for me.
However, the choice made in `ExaConstit` is to overload the `NonlinearForm` class to introduce a `SetUp` method called before `AssembleElementVector` and `AssembleElementGrad` which takes the displacement field as its argument (which is not the case of the `SetUp` method of the `NonlinearForm` class if I am not mistaken). @rcarson3 kindly gives me some insights about this choice here: https://github.com/LLNL/ExaConstit/issues/23. 
However, I still have difficulties to understand the rationale of the `NonlinearForm` and `NonlinearFormIntegrator` design. Is there any documentation about it somewhere ?
Also, I would appreciate some guidance on how to solve my issue, as the `ExaConstit` solution is much more ambitious than what I currently intend to do. Indeed, deriving `NonlinearFormIntegrator` seems much easier. More precisely, I would only need a guarantee of the kind: `AssembleElementVector`  is always called before `AssembleElementGrad`... Any chance that this statement is true (and will remain true in the future) ?
Any help would be greatly appreciated.
Thomas

**Comment by v-dobrev** [comment]
Let me see if I understand the issue correctly: in your derived `NonlinearFormIntegrator` there are expensive computations that are needed in both `AssembleElementVector` and in `AssembleElementGrad` and, because of this high cost, you don't want to repeat them in both methods. Is this correct?

**Comment by chang-yiyi** [comment]
Hi @thelfer ,

Maybe [this](https://github.com/mfem/mfem/issues/1064#issue-490584972) can help you understand the rational.

**Comment by thelfer** [comment]
> Let me see if I understand the issue correctly: in your derived `NonlinearFormIntegrator` there are expensive computations that are needed in both `AssembleElementVector` and in `AssembleElementGrad` and, because of this high cost, you don't want to repeat them in both methods. Is this correct?

Yes. That exactly the point.

**Comment by thelfer** [comment]
> Hi @thelfer ,
> 
> Maybe [this](https://github.com/mfem/mfem/issues/1064#issue-490584972) can help you understand the rationale. By the way, you can run this example step by step in debug mode so you will be clear the rationale.

@chang-yiyi This example is very nice and very readable .It  indeed shows that the only required thing to do when implementing a `NonlinearFormIntegrator` is to implement `AssembleElementVector` and `AssembleElementGrad`. And in this case, I can figure out how the work is separated between the `NonlinearFormIntegrator`  and `NonlinearForm` classes. I don't remember that any official non linear example to be as simple and straightforward to understand. Thanks for the link. However, even if run in debug mode:

-  it would not help to understand what is to be modified for my specific case and if the whole design still holds
- it does not guarantee that the order of the calls to `AssembleElementVector` and `AssembleElementGrad` will not change in the future and that kind of invariant behaviour.
- it shows that the important methods of `NonlinearFormIntegrator` are `AssembleElementVector` and `AssembleElementGrad` and the important methods of `NonlinearForm` are `Mult` and `GetGradient`. But those classes have many other methods that can be overloaded. 

Thus, I still thing that a short description of the different steps involed in the resolution of a non linear problem is missing to my proper understanding of the rationale of the design of those classes. I did not find one so far. That would explain the role of each member function of the `NonlinearFormIntegrator`  and `NonlinearForm` classes.

If such document does not exist, I could try to write it, but I need a least someone for the core team to review it. Anyone interested ?

Regards,

Thomas

**Comment by thelfer** [comment]
@v-dobrev Sorry to be a bit insistant. As I haven't get an answer yet, shall I conclude that the current design does not match my need ? If so, would you advice me to override the `NonlinearForm` class ? Thanks in advance.

**Comment by v-dobrev** [comment]
Hi @thelfer,

Yes, the current implementation of `(Par)NonlinearForm` generally assumes that the local `Mult` and `GetGradient` computations are done separately. That said, a custom integrator can work around this. For example, if you are using the `(Par)NonlinearForm` with a `NewtonSolver` then evaluations needed from the `(Par)NonlinearForm` consist of two calls per iteration -- `Mult` followed by `GetGradient` where the input vector in both cases is the same. This allows the integrator implementation to try to cache data during the local `Mult` operations which can then be used during the local `GetGradient` computations. To enable this caching you need to know the mesh element index with which the methods `AssembleElementVector` (the method performing the local `Mult` action) and `AssembleElementGrad` (the method assembling the local matrix for `GetGradient`) are called. This index can be extracted in both cases from the `ElementTransformation` parameter -- this is the public field `ElementNo`.

There are various choices of what data to cache, e.g. one can compute and cache the local gradient matrices (typically this will use more memory), or you can compute and store physical quantities at quadrature points and finish the local gradient computation during the `AssembleElementGrad` call.

If you store the local input vectors as part of the cache, you can also check the assumption that is made -- that the input to `AssembleElementGrad` is the same as the input to the previous `AssembleElementVector` call for the given mesh element index.

Does this approach sound reasonable for your application?

**Comment by thelfer** [comment]
@v-dobrev This is exactly what I was looking for. The only issue would be if the order of the calls to those those methods changes. But I guess that I can live with it.

> Thus, I still thing that a short description of the different steps involed in the resolution of a non linear problem is missing to my proper understanding of the rationale of the design of those classes. I did not find one so far. That would explain the role of each member function of the NonlinearFormIntegrator and NonlinearForm classes.
> 
> If such document does not exist, I could try to write it, but I need a least someone for the core team to review it. Anyone interested ?

What do you think of this proposal, would it be useful ?

Thanks for you anwers.

**Comment by v-dobrev** [comment]
> What do you think of this proposal, would it be useful ?

Yes, absolutely, it will be useful. It can be added as either part of the doxygen documentation, or as a page on the mfem website (see https://github.com/mfem/web) -- whichever you prefer.

Thank you!

**Comment by thelfer** [comment]
@v-dobrev Let's do this then. Best.
