### ISSUE TITLE
DG_Interface_FECollection implementation

### ISSUE THREAD

**Issue by kvoronin** [mfem/mfem#187]
Hello,

In my project, in order to use mfem's hybridization in 4D, I might need to implement a 4d version of DG_Interface_FECollection.
I would be grateful if someone explains me several things about the 2D/3D implementation:
The main routine seems to be RT_FECollection::InitFaces() which uses some protected data members. What are they: RT_Elements, RT_dof, TriDofOrd and how they are set? 

Thanks,
Kirill

**Comment by tzanio** [comment]
Hi Kirill,

We haven't dived into the 4d implementation yet, so maybe @marneum is the best person to help you with this. `RT_FECollection` are just the regular Raviart-Thomas H(div)-conforming elements.

Tzanio
