### ISSUE TITLE
QuadratureFunction operator= size assertion

### ISSUE THREAD

**Issue by gauthier12** [mfem/mfem#1871]
I think there is a bug in the size check assertion when trying to assign values of a `QuadratureFunction` from a `Vector` in `fem/gridfunc.cpp`

```
QuadratureFunction & QuadratureFunction::operator=(const Vector &v)
 {
    MFEM_ASSERT(qspace && v.Size() == qspace->GetSize(), "");
    Vector::operator=(v);
    return *this;
 }
```

The `qspace->GetSize()` does not take into account a possible `vdim != 1` of the `QuadratureFunction`.
The correction would be

```
QuadratureFunction & QuadratureFunction::operator=(const Vector &v)
 {
    MFEM_ASSERT(qspace && v.Size() == this->Size(), "");
    Vector::operator=(v);
    return *this;
 }
```
I would be willing to make a PR with the correction but it seems that I can't push a branch to follow the workflow described in CONTRIBUTING.md.

Regards,

**Comment by v-dobrev** [comment]
You are right. The doxygen documentation should be fixed too. I'll send you an invite in a moment so that you can push your fix.

Thank you!

**Comment by tzanio** [comment]
Discussion continued in #1873. Thanks @gauthier12.
