### ISSUE TITLE
ReorientTetMesh and NC meshes

### ISSUE THREAD

**Issue by jakubcerveny** [mfem/mfem#1874]
There is some problem with shared face orientation that is not resolved by `ParMesh::ReorientTetMesh` if the mesh is an NC mesh.

How to reproduce: in `ex3p.cpp`, add `mesh->EnsureNCMesh(true)` right after the serial mesh is loaded. Then run 
```
mpirun -n 2 ./ex3p -m ../data/inline-tet.mesh -o 2
```
Output:
```
MFEM abort: triangle face orientation 1 is not supported! Use Mesh::ReorientTetMesh to fix it.
 ... in function: virtual const int* mfem::ND_FECollection::DofOrderForOrientation(mfem::Geometry::Type, int) const
 ... in file: fem/fe_coll.cpp:2649
```

**Comment by tzanio** [comment]
This should be resolved by the work in https://github.com/mfem/mfem/pull/1046

cc: @mlstowell

**Comment by tzanio** [comment]
Now that #1046 is merged, can we check if this is still an issue, @jakubcerveny ?

**Comment by jakubcerveny** [comment]
I can no longer reproduce the orientation error, so I think this issue can be closed.

However I do observe a problem on the processor boundary if the mesh is an NC tet mesh. The solution is wrong and takes a long time to "converge". I will continue looking into this in #2492.
