### ISSUE TITLE
Evaluate Domain Integral

### ISSUE THREAD

**Issue by wcdawn** [mfem/mfem#1875]
I'm interested in evaluating an integral of the form

<img src="https://i.upmath.me/svg/%20%5Cint_%7B%5Cmathcal%7BD%7D%7D%20f(%5Cmathbf%7Br%7D)%20%5C%2C%20%5Cphi(%5Cmathbf%7Br%7D)%20%5C%3B%20d%5Cmathbf%7Br%7D%20" alt=" \int_{\mathcal{D}} f(\mathbf{r}) \, \phi(\mathbf{r}) \; d\mathbf{r} " />

where <img src="https://i.upmath.me/svg/f(%5Cmathbf%7Br%7D)" alt="f(\mathbf{r})" /> is some function specified by a `mfem::Coefficient` and <img src="https://i.upmath.me/svg/%5Cphi(%5Cmathbf%7Br%7D)" alt="\phi(\mathbf{r})" /> is a `mfem::GridFunction` and the integral is evaluated over the entire domain, <img src="https://i.upmath.me/svg/%5Cmathcal%7BD%7D" alt="\mathcal{D}" />. This is a metric for convergence and used in an iterative algorithm.

Currently, I use a `mfem::LinearForm` with `mfem::GridFunctionCoefficient` and sum the vector in the linear form. This doubles the memory requirement (a second `mfem::LinearForm`) and seems inefficient.

**Comment by tzanio** [comment]
Do you need to do this only once, or you do it many times?

If you need to do it several times with different grid functions ϕ, thenstroing the `LinearForm` and computing the dot products with the different ϕ can be more efficient, see `LinearForm::operator()`

You may also happen to have the `LinearForm` already from other computations, e.g. maybe it was in the right-hand side.

If none of these addresses your needs, then the best thing to do may be to write a new method in `LinearForm` that accumulates the integral element by element without forming a global vector.

Hope this helps,
Tzanio

**Comment by tzanio** [comment]
See also https://github.com/mfem/mfem/issues/1839#issuecomment-718766067

**Comment by wcdawn** [comment]
This needs to be evaluated many times.
The `LinearForm::operator()` for the inner product will be helpful and I will have to create fewer `Coefficient` objects.
An accumulation routine could be useful but I'm going to make due with the inner product operator for now and revisit this if necessary.

Thank you!
