### ISSUE TITLE
MFEM does not build from spack as a shared library with CUDA enabled

### ISSUE THREAD

**Issue by MPhysXDev** [mfem/mfem#1880]
When trying to install MFEM (either v4.1 or v4.2) from spack, as a shared library (+shared -static) with cuda enabled (+cuda cuda_arch=sm_xx) the build stage fails almost immediately.

It appears that the -fPIC flag gets applied directly to the NVCC command line (which does not support the -fPIC option), instead of being forwarded to the host compiler properly. The calls to the compiler look like:

`nvcc -fPIC [...]`

while they should be something like:

`nvcc -Xcompiler -fPIC [...]`

Thanks in advance for your help with this issue.

Best regards,

MPhysX Development Team

**Comment by v-dobrev** [comment]
Thank you for reporting this issue. I also noticed it when doing some testing recently. I will push a fix for this and other updates to the following WIP branch/PR in Spack: https://github.com/spack/spack/pull/19748.

**Comment by v-dobrev** [comment]
Actually, I now realize, I did not fix the bug you pointed out. The one I fixed was for `-fopenmp`, not `-fPIC`. I'll add the fix for the latter in a moment.

**Comment by tzanio** [comment]
Resolved in spack/spack#19748.
