### ISSUE TITLE
How to deal with the Dirichlet boundary conditions in ex16?

### ISSUE THREAD

**Issue by fengerhan** [mfem/mfem#1881]
Hello,  a time dependent nonlinear heat equation  problem is solved in ex16. But there is no Dirichlet boundary conditions in the problem. It  deals with the pure Neumann b.c. Who can tell me how to deal with the Dirichlet boundary conditions in ex16 or give me an example ? Thanks !

**Comment by fengerhan** [comment]
hello, I have read #1720, but I am sorry that I can not understand how to add Nonhomogeneous Dirichlet Boundary in ex16. May be someone can give an example code to show how to do it.

**Comment by tzanio** [comment]
@jamiebramwell and @acfisher, can you help @fengerhan with Example 16?
