### ISSUE TITLE
problem at builiding glvis (undefined reference to symbol 'XGetWindowAttributes')

### ISSUE THREAD

**Issue by cshoyo** [mfem/mfem#1885]
Hello.

I got the message 

/usr/bin/ld: lib/libglvis.a(aux_vis.o): undefined reference to symbol 'XGetWindowAttributes'

easily solved by adding "-lX11" after "-lGLU" in GL_LIBS in makefile.

Ubuntu 20.04.

Regards

**Comment by v-dobrev** [comment]
Hi @cshoyo, did you encounter this issue with GLVis v3.4 or the `master` branch?

I just want to make sure this is not a new issue -- if you used v3.4, similar issue was resolved in #63 (reported in #62).
