### ISSUE TITLE
VTK prism orientation: example 1 doesn't work with beam-wedge.vtk

### ISSUE THREAD

**Issue by pazner** [mfem/mfem#1887]
Running `ex1` with the mesh `beam-wedge.vtk`, I get the following output:

```
% ./ex1 -m ../data/beam-wedge.vtk
Options used:
   --mesh ../data/beam-wedge.vtk
   --order 1
   --no-static-condensation
   --no-partial-assembly
   --device cpu
   --visualization
Device configuration: cpu
Memory configuration: host-std
Elements with wrong orientation: 8 / 8 (NOT FIXED)
Number of finite element unknowns: 19737
Size of linear system: 19737
   Iteration :   0  (B r, r) = -0.010132
PCG: The preconditioner is not positive definite. (Br, r) = -0.010132
```

It seems like this is an orientation issue. The VTK mesh reader does have a permutation for the prism vertex ordering, but perhaps it is not properly fixing the orientations?

**Comment by mlstowell** [comment]
According to the VTK documentation the first three vertices form the base of the wedge and the normal to the base, using the right hand rule, should point away from the opposite face of the wedge.  The documentation agrees with the image:
![35021239-dbb37d7a-fae4-11e7-8534-167726495bd8](https://user-images.githubusercontent.com/6109571/99464176-58138800-28ec-11eb-8aa5-dc9613587796.png)

On the other hand the first element of our vtk file is:
```6 0 9 18 1 10 19```
With nodes 0, 9, and 18 given by:
```
0 0 0
...
0 1 0
...
0 0.5 1
...
```
Consequently, the normal for this face points in the positive x direction which is into the element i.e. towards the opposite face.  It seems to me that our `beam-wedge.vtk` does not contain valid VTK_WEDGE elements.

**Comment by tzanio** [comment]
Yes, can you please fix it @mlstowell?

I don't remember doing it, but GitHub claims that I added this mesh and a few others in https://github.com/mfem/mfem/commit/bdc5415de918862c06085ac65dc765fdbef042a0.

Maybe I opened the `*.mesh` and used `Mesh::PrintVTK()` to save them. Shouldn't that work?

**Comment by mlstowell** [comment]
I'd be happy to.  I'll check `Mesh::PrintVTK` as well.

**Comment by tzanio** [comment]
Thank you Mark!

**Comment by tzanio** [comment]
Discussion continued in #1888.
