### ISSUE TITLE
NSE convective and skew-symmetric form of nonlinear term

### ISSUE THREAD

**Issue by nnpp-schneier** [mfem/mfem#1889]
Hi all,

I was hoping to get some advice on how to implement the convective and skew symmetric form of the advection term of the Navier-Stokes equations in MFEM in a linearized sense.

Just to be clear for a given u_h^n, unknown u_h^{n+1}, and test function v_h I would like to evaluate the forms

(u_h^n \cdot \nabla u_h^{n+1},v_h)

and

(u_h^n \cdot \nabla v_h,u_h^{n+1})

I thought the first of the above forms would just work with ConvectionIntegrator i.e. something like

conv_NSE->AddDomainIntegrator(new ConvectionIntegrator(u0));

but it seems (unless I am misunderstanding something) that this is only implemented for the case where u_h^{n+1} is a scalar quantity. I also took a look at the VectorConvectionNLFIntegrator, which seems like it would be able to give me the Gateaux derivative, but does not seem like it could be used to produce the above forms (unless I'm again not realizing something).

If this isn't already implemented within MFEM is there any reasons I wouldn't be able to just implement these forms myself? It seems to me like it would just be some modifications to what already exists in ConvectionIntegrator.

Thank You

**Comment by jandrej** [comment]
`VectorConvectionNLFIntegrator` only provides the "action" of what you described to a vector valued quantity when you use what we call Partial Assembly. It does provide the Gateaux derivative in the common case, see https://github.com/mfem/mfem/blob/master/fem/nonlininteg.cpp#L740.

**Comment by nnpp-schneier** [comment]
Hi jandrej,

Thank you for the quick response. In that case, I believe I will implement versions of the convective and skew symmetric form  myself in order to have the option of not using partial assembly. Would you recommend further overloading VectorConvectionNLFIntegrator or doing it as separate forms?

**Comment by jandrej** [comment]
I don't see an issue with inheriting from `VectorConvectionNLFIntegrator` and overloading `AssembleElementGrad`, based on an option to either do the convective or skew symmetric form.

**Comment by nnpp-schneier** [comment]
Hi Jandrej,

I've been working on this a bit, but am having some issues getting this implemented. I know you recommended overloading AssembleElementGrad, but was wondering if there is a reason I would not be able to do it as a bilinear form rather than a nonlinear form? So far I modified ConvectionIntegrator to VectorConvectionIntergator in the code below, which I believe is just the vector implementation of ( Q \grad u, v). Is there any reason I would not be able to add a definition of elfun, remove Q and incorporate elfun in the loop over elmat at the end? 


```
void VectorConvectionIntegrator::AssembleElementMatrix(
   const FiniteElement &el, ElementTransformation &Trans, DenseMatrix &elmat)
{
   int nd = el.GetDof();
   int dim = el.GetDim();
   const int sdim = Trans.GetSpaceDim();


   elmat.SetSize(nd * sdim);
   dshape.SetSize(nd,dim);
   adjJ.SetSize(dim);
   shape.SetSize(nd);
   vec2.SetSize(dim);
   BdFidxT.SetSize(nd);
   pelmat.SetSize(nd);

   Vector vec1;

   const IntegrationRule *ir = IntRule;
   if (ir == NULL)
   {
      int order = Trans.OrderGrad(&el) + Trans.Order() + el.GetOrder();
      ir = &IntRules.Get(el.GetGeomType(), order);
   }

   Q->Eval(Q_ir, Trans, *ir);

   elmat = 0.0;
   pelmat = 0.0;

   for (int i = 0; i < ir->GetNPoints(); i++)
   {
      const IntegrationPoint &ip = ir->IntPoint(i);
      el.CalcDShape(ip, dshape);
      el.CalcShape(ip, shape);

      Trans.SetIntPoint(&ip);
      CalcAdjugate(Trans.Jacobian(), adjJ);
      Q_ir.GetColumnReference(i, vec1);
      vec1 *= alpha * ip.weight;

      adjJ.Mult(vec1, vec2);
      dshape.Mult(vec2, BdFidxT);

      AddMultVWt(shape, BdFidxT, pelmat);
   }

   for (int d = 0; d < sdim; d++)
   {
      for (int k = 0; k < nd; k++)
      {
         for (int l = 0; l < nd; l++)
         {
            elmat(nd*d+k, nd*d+l) = pelmat(k, l);
         }
      }
   }
}
```

**Comment by jandrej** [comment]
Sorry for the late reply. There is nothing that would prevent that I believe. If I understand correctly this would do the same as implementing the `NonlinearForm`, or am I missing something?

I could recommend more specific concepts if you can give more information on what you are trying to do in general. E.g. are you trying to setup an implicit solver for the Navier-Stokes equation or just need the assembled form for a Preconditioner.

**Comment by nnpp-schneier** [comment]
I'd like to be able to assemble the form to be able to implement my own Picard iteration or semi-implicit timestepping for the NSE. I agree that this would be the same as implementing the NonLinearForm and decided to go back and try that instead. I have the following code based on the existing nonlinear form below with comments on how I think it is working (however it does not appear to be working).

`void ConvectiveVectorConvectionNLFIntegrator::AssembleElementGrad(
   const FiniteElement &el,
   ElementTransformation &trans,
   const Vector &elfun,
   DenseMatrix &elmat)
{
   int nd = el.GetDof();
   int dim = el.GetDim();

   shape.SetSize(nd);
   dshape.SetSize(nd, dim);
   dshapex.SetSize(nd, dim);
   elmat.SetSize(nd * dim);
   elmat_comp.SetSize(nd);
   gradEF.SetSize(dim);

   EF.UseExternalData(elfun.GetData(), nd, dim);

   elfun.Print();

   double w;
   Vector vec1(dim), vec2(dim), vec3(nd);

   const IntegrationRule *ir = IntRule;
   if (ir == nullptr)
   {
      int order = 2 * el.GetOrder() + trans.OrderGrad(&el);
      ir = &IntRules.Get(el.GetGeomType(), order);
   }

   elmat = 0.0;
   for (int i = 0; i < ir->GetNPoints(); i++)
   {
      const IntegrationPoint &ip = ir->IntPoint(i);
      trans.SetIntPoint(&ip);

      el.CalcShape(ip, shape);
      el.CalcDShape(ip, dshape);

      Mult(dshape, trans.InverseJacobian(), dshapex);

      w = ip.weight;

      if (Q)
      {
         w *= Q->Eval(trans, ip);
      }

      //MultAtB(EF, dshapex, gradEF);
      EF.MultTranspose(shape, vec1); // u^n

      trans.AdjugateJacobian().Mult(vec1, vec2);

      vec2 *= w;
      dshape.Mult(vec2, vec3); // (u^n \cdot \ grad u^{n+1})
      MultVWt(shape, vec3, elmat_comp); // (u^n \cdot \ grad u^{n+1},v)

      for (int i = 0; i < dim; i++)
      {
         elmat.AddMatrix(elmat_comp, i * nd, i * nd);
      }

      
   }
}`

My impression on the way this would work is that I could generate the matrix corresponding to the form 

(u_h^n \cdot \nabla u_h^{n+1},v_h) 

using something like

`N_NSE->AddDomainIntegrator(new ConvectiveVectorConvectionNLFIntegrator());
SparseMatrix *Non = dynamic_cast<SparseMatrix*>(&N_NSE->GetGradient(un));
`

**Comment by jandrej** [comment]
Ok, your approach makes sense in terms of how the mfem interface is setup. `GetGradient` is also the right method to retrieve the linearized version of your integrator.

Your implementation of the kernel looks reasonable, although I haven't checked it thoroughly.

By "I do not seem to be getting the correct output" you mean that the Jacobian you are expecting is not correct or the solution you are getting is not correct?

**Comment by nnpp-schneier** [comment]
Sorry, I meant that the solution to the steady state NSE I'm getting is not correct. I'm unsure if the form being returned by the above code is working properly, but I suspect there is a small bug. The only other problem I can think of is the handling of the boundary conditions for the returned form or the sparse matrix addition (I am just adding it to the velocity block, with the stiffness matrix pre assembled see the code below).

```
N_NSE->AddDomainIntegrator(new ConvectiveVectorConvectionNLFIntegrator()); 
SparseMatrix *Non = dynamic_cast<SparseMatrix*>(&N_NSE->GetGradient(un));

for (int i = 0; i < ess_tdof_list.Size(); i++)
            {
               Non->EliminateRowColDiag(ess_tdof_list[i], 0.0); //Set boundary values to 0 
            }

A.Add(1.0,*Non); // A is the stifness matrix with boundary conditions applied
```

**Comment by jandrej** [comment]
This means your sparse matrix contains zeros on the rows columns of ess_tdof_list[i], even on the diagonal. Is that your intention?

You can also call
```
N_NSE->SetEssentialBCs(ess_tdof_list);
SparseMatrix *Non = dynamic_cast<SparseMatrix*>(&N_NSE->GetGradient(un));
A.Add(1.0,*Non);
```
Then the dirichlet bc's are handled for you in the nonlinear form and your sparse matrix `Non` has zeroed out rows and columns but contains a `1` on the diagonal. This also handles the residual coming from `N_NSE` correctly. E.g. evaluates to `R(u_e) = 0 for e in ess_tdof_list`.

Hope this helps.

**Comment by nnpp-schneier** [comment]
Thank you for the help. Everything appears to be working for me now. I will go ahead and close this issue and submit a PR with the new forms in the near future.
