### ISSUE TITLE
2D elasticity problem: Non homogeneous Dirichlet boundary conditions on a single DOF

### ISSUE THREAD

**Issue by cpolindara** [mfem/mfem#1893]
Hi to all,

i have a problem imposing non homogeneous Dirichlet boundary conditions. The search on the open/closed issues had shed some light into the solution but still i cannot solve the problem, so, here it is.

Say i have a rectangular domain (L x H) and want to solve the elasticity problem (find u(x,y)) under the following BCs:

**- u_x = 0 at (x=0)**
**- u_y = 0 at (x=0)**
**- u_x = u_imposed at (x=L)**

How do i impose them?

Following [ex2.cpp](https://github.com/mfem/mfem/blob/master/examples/ex2.cpp), [ex21.cpp](https://github.com/mfem/mfem/blob/master/examples/ex21.cpp) and issue [#1399](https://github.com/mfem/mfem/issues/1399) i have done the following (variable names follow from ex2.cpp):

`Array<int> ess_tdof_list, ess_bdr(mesh->bdr_attributes.Max());`
`ess_bdr = 0;`
`ess_bdr[0] = 1;`
`ess_bdr[1] = 1;`
`fespace->GetEssentialTrueDofs(ess_bdr, ess_tdof_list);`

`Vector u_imposed(mesh->bdr_attributes.Max());`
`u_imposed = 0.0;`
`u_imposed(1) = 1.0;`
`u.Set(0, new PWConstCoefficient(u_imposed));`
`x.ProjectBdrCoefficient(u,ess_bdr);`

But, as expected, u_y = 0 at x=L (see attached figure). I don't want that, nodes should be allowed a vertical displacement there.

Do you have any ideas?

Any comment/hint will be truly appreciated.

Bets,

César.

![rectangular_domain](https://user-images.githubusercontent.com/64557756/99719045-19c4c700-2aac-11eb-8fb4-d6859758f7ca.png)

**Comment by tzanio** [comment]
Hi César,

Ultimately what you want is to determine the set of essential (Dirichlet) degrees of freedom in the `ess_tdof_list` array.

For vector spaces, the call to `GetEssentialTrueDofs(ess_bdr, ess_tdof_list)` will mark all the vector components on the `ess_bdr` boundary elements i.e. both the `x` and `y` in your case. You can provide an optional third parameter to pick a specific vector component.

Therefore, one way to handle separate x/y boundary conditions is to determine the essential x/y degrees of freedom separately and then take the union in `ess_tdof_list`.

You can do this as follows:

```c++
Array<int> ess_bdr(mesh->bdr_attributes.Max());

Array<int> ess_tdof_list, 
ess_bdr = 0; ess_bdr[0] = 1; ess_bdr[1] = 1;
fespace->GetEssentialTrueDofs(ess_bdr, ess_tdof_list, 0); // x-component

Array<int> ess_tdof_list_y, 
ess_bdr = 0; ess_bdr[0] = 1;
fespace->GetEssentialTrueDofs(ess_bdr, ess_tdof_list_y, 1); // y-component

ess_tdof_list.Append(ess_tdof_list_y);
```

Hope this helps,
Tzanio

**Comment by cpolindara** [comment]
Thank you, Tzanio! That's what i needed.

A small comment though. Care must be taken when setting the values of `ess_bdr` more than once, as you suggest, since this mfem::Array is used when imposing the solution on the boundary x=L by means of `x.ProjectBdrCoefficient(u,ess_bdr);`

Cheers,

César.
