### ISSUE TITLE
Constructing a Tensor Product DG operator

### ISSUE THREAD

**Issue by vikramsg** [mfem/mfem#1895]
Hi all,

I wanted to know whether it is possible to decompose the DG operators into tensor product operations. For example if we did example 9 DG advection, I want to be able to construct the advection operator using a tensor product structure. Are there examples of this. If not, any pointers?

Vikram

**Comment by tzanio** [comment]
Can you clarify what you mean by "tensor product structure"? Is it [partial assembly](https://mfem.org/performance/#finite-element-operator-decomposition)? If so, Example 9 already supports that.

**Comment by vikramsg** [comment]
As I understand, partial assembly has more to do with assembling a global matrix or a local matrix. 

My requirement is different, although I maybe wrong. Let me try to explain. Suppose we want to apply the 2D DG advection operator. First, we decompose the operator into the purely local operator that acts locally on each element, and the other part is the one that handles inter element boundary values.

If we only look at the first part which is purely local to the element then for the operator is basically a tensor product, that is, it is a series of 1D operations, repeated for each row of nodes. I want to do this operation and then adapt it for my purpose, so in essence I want to know if there's a way by which I can do DG advection for a 2D problem via a series of 1D operations.

**Comment by pazner** [comment]
Hi @vikramsg, MFEM's partial assembly algorithms automatically use the tensor decomposition you mention on quad/hex meshes. For example, the volume term for the advection operator is implemented in `bilininteg_convection_pa.cpp`. The kernels are a bit complicated, but they apply the operator as a series of 1D tensor contractions (`b` is the 1D basis evaluation matrix, and `g` is the 1D differentiation matrix).

I would suggest reading some of the code for these PA kernels (mass is probably the simplest to start), and then seeing how they could be extended for your purposes.

**Comment by vikramsg** [comment]
Hi @pazner,

Thanks. I had a look and I can somewhat understand it. Is there some documentations that lists out how the steps are done?

**Comment by pazner** [comment]
> Thanks. I had a look and I can somewhat understand it. Is there some documentations that lists out how the steps are done?

Unfortunately, at this stage I believe the code is the best documentation. There is some high-level information in the page that was linked earlier in this issue, but it doesn't go into details. If you have specific questions, you can feel free to post them here.

**Comment by vikramsg** [comment]
Thanks. For now I will just come and reopen if I have questions.
