### ISSUE TITLE
Implementation of boundary condition based on boundary attribute

### ISSUE THREAD

**Issue by Sladewilson-arrow** [mfem/mfem#1898]
Dear all,

I am trying to implement Dirichlet boundary conditions on a mesh based on boundary attribute. Lets say the input mesh is a square with sides B1, B2, B3 and B4 as boundaries.
Now i would like to apply different Dirichlet boundary conditions on the above boundaries based on boundary attribute. 
I have explored following methods
1. PWConstCoefficient class is used but it is implementing BC's based on element attribute. (Ref: coefficient.cpp lines:24-28 )
2. A coefficient class derived from GridFunctionCoefficient is used, hoping GetBdrAttribute method can be helpful.
   The Eval method with
   "this->GetGridFunction()->FESpace()->GetBdrAttribute(T.ElementNo) "
   is giving segment fault 
   since GetBdrAttribute(index) where index>GetNBE()
   is accessing array out of index range.

Is there any way to access bdr_attribute with ElementNo() as input or 
 
Thanks in advance
Slade Wilson

**Comment by wcdawn** [comment]
I'm a bit confused by your implementation. Typically for essential Derichlet BCs you would eliminate them from the system and then you could use `GridFunction::ProjectBdrCoefficient()` to set them to an appropriate value based on the boundary attribute. Alternatively, you could use something like `BilinearForm::EliminateEssentialBC()` to set the diagonal of the bilinear form and the corresponding value in the linear form to appropriate values.

Does this sound like something you could use?

**Comment by tzanio** [comment]
Hi Slade,

To add to @wcdawn's answer -- have you looked at Example 2? There we have different types of boundary conditions based on different mesh (boundary) attributes.

Note that the essential (Dirichlet) dofs are just determined from `FiniteElementSpace::GetEssentialTrueDofs(ess_bdr, ess_tdof_list);` where `ess_bdr` is a marker array over the mesh boundary attributes.

Note also that whe `PWConstCoefficient` is used in boundary integrators, the attribute is the one of the boundary element.

Hope this helps,
Tzanio
