### ISSUE TITLE
Installation Problems

### ISSUE THREAD

**Issue by dsellers94** [mfem/mfem#1899]
I am fairly new to both FEM and C++ (I have used FEM in SolidWorks and C++ for a couple of projects) and I am hoping to use MFEM for an existing Computational Astrophysics Project.

I am unable to install even using the simple "straightforward" serial build instructions available on the MFEM webpage.

I have downloaded mfem-4.2 and glvis3.4 and run the command:

`make serial -j`

which seems to work, but when I run:

`make MFEM_DIR=../mfem-4.2 -j`

I get a series of fatal errors, such as `openglvis.cpp:12:10: fatal error: 'GL/gl.h' file not found`

simply typing `make` or any other make command results in `makefile:192: *** The MFEM library is not built.  Stop.`

I have no idea what I'm doing wrong. I have hit many dead ends trying to get a usable FEM library for C++ operational.

Sorry if this is not the place to ask for help. Any advice or direction appreciated.

**Comment by tzanio** [comment]
Hi @dsellers94,

GLVis is our native visualization tool, but you do not need to use MFEM (you can use other visualization tools, such as VisIt and ParaView).

If `make serial` worked, you should be able for example to build and run the example codes:

```
cd examples
make -j
./ex1
```

That being said if you want to use GLVis you will need OpenGL development libraries on your system, see https://github.com/GLVis/glvis/blob/master/INSTALL#L117.

Hope this helps,
Tzanio

**Comment by dsellers94** [comment]
Thanks @tzanio !

running `./ex1` in examples returns nothing at all in the terminal shell (after running `make all -j`).

I guess this is because I don't have any visualization tools operational yet? I will work on getting GLVis running unless there is something simpler to get started with.

Thanks again for your help!

**Comment by tzanio** [comment]
Hmm... you should see something like:

```
> ./ex1
Options used:
   --mesh ../data/star.mesh
   --order 1
   --no-static-condensation
   --no-partial-assembly
   --device cpu
   --visualization
Device configuration: cpu
Memory configuration: host-std
Number of finite element unknowns: 20801
Size of linear system: 20801
   Iteration :   0  (B r, r) = 0.00113865
   Iteration :   1  (B r, r) = 0.00700883
   Iteration :   2  (B r, r) = 0.0123246
   Iteration :   3  (B r, r) = 0.0126492
   Iteration :   4  (B r, r) = 0.0123827
...
   Iteration : 111  (B r, r) = 1.10523e-15
Average reduction factor = 0.882852
```

in the terminal

**Comment by dsellers94** [comment]
I see output similar to that for any example except for ex1. Which is strange? 

Anyway I am now working on getting a GLVis running but I am not sure how to install it's dependencies. Homebrew will not find `libGLU-dev, libpng-dev, and fontconfig-dev`

**Comment by tzanio** [comment]
Are you on a Mac? Do you have XQuartz installed?

**Comment by dsellers94** [comment]
Yes I am on a Mac and I now have XQuarts installed.

**Comment by tzanio** [comment]
The warnings are (unfortunately) expected. Glad it works

**Comment by dsellers94** [comment]
Yes, thank you very much for your help!

I'm sure I will be back here when actually trying to use MFEM, but this is an encouraging start.
