### ISSUE TITLE
How to copy a SparseMatrix

### ISSUE THREAD

**Issue by martemyev** [mfem/mfem#19]
Dear all,

I can't figure out how I can create a copy of an existing SparseMatrix.
I am solving the following equation:
`(M+D)*u_0 = M*(2u_1 - u_2) - <other stuff> + D*u_2`,
where `M` and `D` are sparse matrices obtained with different bilinear forms corresponding to the same FE space.
I denote the matrix `(M+D)` as `A`, and I need it to be different from both `M` and `D`, because I need those on the right hand side of the equation.
Doing this:
`SparseMatrix A = M; A += D;`
copies all internals of the `M` matrix to the `A` including pointers (because the `SparseMatrix::operator=(const SparseMatrix&)` doesn't exist, and the compiler creates its own - a primitive one), so changing the matrix `A` with `A += D;` changes the `M` matrix as well (even if `const SparseMatrix &M = m->SpMat();`, i.e. the `M` is supposed to stay const).

Could you please give me a hint how to create a new matrix `A=M+D`, or is there any other solution for my problem?

Thank you,
Mikhail

**Comment by tzanio** [comment]
Hi Mikhail,

If you add two BilinerFormIntegrators the corresponding BilinearForm will assemble their sum, see for example

https://github.com/mfem/mfem/blob/master/examples/ex3.cpp#L126

Does this address your use case?

You should be able to write

M += D 

for sparse matrices M and D, as long as the sparsity patter on D is a subset of the sparsity patter of M (which very likely is true), see

https://github.com/mfem/mfem/blob/master/linalg/sparsemat.hpp#L279

Hope this helps,
Tzanio

**Comment by martemyev** [comment]
Hi Tzanio,

> If you add two BilinerFormIntegrators the corresponding BilinearForm will assemble their sum

I think this is indeed possible in my case, but I thought that since I already computed M and D as separate matrices there should be any easy way to add them up, and creating a new bilinear form didn't look as the one.

> You should be able to write M += D

I can't because in this case I change M, but I need the original one for the right hand side (the same is true for D).

> for sparse matrices M and D, as long as the sparsity patter on D is a subset of the sparsity patter of M

I think I can add them up even if the patterns are completely different, but the height and width are the same, and both are not finalized. Please, let me know if I'm wrong.

As for the copying sparse matrices (just to close the topic) - there is no way to do that as far as I understood. Correct?

Best regards,
Mikhail

**Comment by v-dobrev** [comment]
Hi Mikhail,

Copying a SparseMatrix can be achieved with something like this:
```
// Assume we have a SparseMatrix A that is finalized, i.e. in csr format.
int nnz = A.NumNonZeroElems();
SparseMatrix B(A.GetI(), A.GetJ(), new double[nnz], A.Height(), A.Width(),
               false, true, A.areColumnsSorted());
```
The new SparseMatrix B has the same sparsity pattern as A without duplicating the "I" and "J" arrays of the csr format, only the "data" double array is different and it will be owned by the newly created SparseMatrix B, i.e. B will delete its "data" array when it is destroyed.

An actual copy constructor for SparseMatrix will be available in the next release of MFEM.

Veselin

**Comment by martemyev** [comment]
Hi Veselin,

That looks like a solution! Thank you!

Best,
Mikhail
