### ISSUE TITLE
Adjacency list

### ISSUE THREAD

**Issue by tarikdzanic** [mfem/mfem#1902]
Hi everyone! I'm trying to form a vector of the indices of the elements physically adjacent to a certain element in a 2D mesh. I've been able to work this out for certain meshes using GetVertexToElementTable, but I am having trouble with non-conforming meshes. When the refinement level of an element is >1 higher than its neighboring element, they won't share any vertices even though they're physically adjacent. Is there any functionality in MFEM to do this task?

**Comment by pazner** [comment]
If you only need face neighbors and not vertex neighbors, I believe `Mesh::ElementToElementTable` should work with nonconforming meshes.

If you need vertex/edge/face neighbors, perhaps `NCMesh::FindNeighbors` does what you need.

**Comment by tarikdzanic** [comment]
Thanks @pazner, I was able to get it working with those functions!
