### ISSUE TITLE
Question: multiphysics in mfem

### ISSUE THREAD

**Issue by cshoyo** [mfem/mfem#1905]
Hello

I have seen that MFEM have different application areas (fluid, electromagnetics)? It is possible to couple fluid mechanics and electromagnetics? It is certainly possible because  there are projects based on MFEM that must use that coupling (https://www.rfscidac4.org/), but I do not know if this possibility is already included in MFEM or it must be coded by the user. 

Thank you.

**Comment by rw-anderson** [comment]
Generally speaking this is something that would be done at the application level, combining the lower level, more general abstractions of the MFEM library in the desired way.

**Comment by tzanio** [comment]
To add to Bob's answer -- we provide the building blocks and it is up to apps to build whatever multiphysics infrastructure suits them best. One example that could be useful to check is the Joule miniapp in the `miniapps/electromagnetics` directory.
