### ISSUE TITLE
How to apply an elasticity Dirichlet boundary conditions and load in a single degree of freedom

### ISSUE THREAD

**Issue by nghiakvnvsd** [mfem/mfem#1908]
Hi everybody. I have a question when I try coding my problem. How to apply an elasticity Dirichlet boundary conditions and load in a single degree of freedom? This is very important in mechanical problems. I totally did it by hand before. For examples, I want to apply in to the problem (the problem has rectangle mesh,  nelx x nely):

![image](https://user-images.githubusercontent.com/68639058/100538325-6493cb00-3272-11eb-9a90-d4558f463495.png)

I code:
```
   Array<int> ess_tdof_list, ess_bdr(mesh->bdr_attributes.Max());
   ess_bdr = 0; 
   ess_bdr[0] = 1; 
   fespace->GetEssentialTrueDofs(ess_bdr, ess_tdof_list, 0);
   ess_tdof_list.Append(2*(nelx+1)*(nely+1)-1);
```
and apply load by:
```
......................
a->FormLinearSystem(ess_tdof_list, x, *b, A, X, B);
B(1)=-1;
......................
```

However, I think these ways are not good when I try to apply into parallel problem. May you recommend me that way to implement effectively? Thank you very much!!!

**Comment by tzanio** [comment]
Hi @nghiakvnvsd,

This is all doable, the only question is what should be the user interface.

Specifically, how do you want to identify the single degree of freedom?

1. It could be defined as the intersection of the bottom and the right boundary element attributes. This is something that could be done now -- just define separate `ess_tdof_list`s for the two boundary element attributes and find their intersections.

2. It could be defined through its physical coordinates. This can also be done now, e.g. by looping and checking the dofs.

3. It could be defined by a point attribute in the input mesh file. This is not currently supported but may be supported in the future with @mlstowell's `entity-set` work.

Does this make sense? Which option will you prefer?

Tzanio

**Comment by nghiakvnvsd** [comment]
> Hi @nghiakvnvsd,
> 
> This is all doable, the only question is what should be the user interface.
> 
> Specifically, how do you want to identify the single degree of freedom?
> 
> 1. It could be defined as the intersection of the bottom and the right boundary element attributes. This is something that could be done now -- just define separate `ess_tdof_list`s for the two boundary element attributes and find their intersections.
> 2. It could be defined through its physical coordinates. This can also be done now, e.g. by looping and checking the dofs.
> 3. It could be defined by a point attribute in the input mesh file. This is not currently supported but may be supported in the future with @mlstowell's `entity-set` work.
> 
> Does this make sense? Which option will you prefer?
> 
> Tzanio

Hi! @tzanio the case 1 seems not good for all problems. For examples, sometimes, in machenics, we have the model (MBB beam problem):

![image](https://user-images.githubusercontent.com/68639058/100701605-51543d00-33e3-11eb-9f81-f91a48e4a428.png)

as you see, the load applied is not the intersection of the bottom and the right boundary element attributes.

With case 2, it is something I do, when I code my parallel problems and sometimes, I have to draw by hand in my notebook and run some tests to make sure everything ok.

So, I think the case 3 is the best. Actually, I have tried by myself before but it doesn't work. I tried to change the file mesh such that the boundary parameter has the point boundary and in my code I apply the load in that boundary. Thank you for your advice.

**Comment by tzanio** [comment]
Unless someone else has other suggestions, I'm afraid approach 2 is the best we can offer you currently.

Can you clarify why you need to check things by hand? The loop I had in mind is

```
loop over local dofs
   mark the dof as essential if its physical coordinates correspond to an essential BC vertex
```

which should be pretty general if the coordinates of the ssential BC vertices are known in advance.

**Comment by nghiakvnvsd** [comment]
> Unless someone else has other suggestions, I'm afraid approach 2 is the best we can offer you currently.
> 
> Can you clarify why you need to check things by hand? The loop I had in mind is
> 
> ```
> loop over local dofs
>    mark the dof as essential if its physical coordinates correspond to an essential BC vertex
> ```
> 
> which should be pretty general if the coordinates of the ssential BC vertices are known.

Hmm. I mean I want to use Metis to create the parallel mesh and I do not know how to set the load exactly. In order to be easy, I usually dont use metis to create the mesh. I usually create the mesh by:

`ParMesh *pmesh = new ParMesh(MPI_COMM_WORLD, *mesh, partitioning);`

Create the mesh folow this way help me easily determine the exact point I want to add the load.

Or maybe, I dont know the way to specify the DOFs in parallel mesh when I apply the load. May you help me? Thank you very much!

**Comment by sshiraiwa** [comment]
Once I ran into a situation where I needed a point constraint, and source in a heat equation. 
There is a Delta function in Coefficient and GridFunction. 
Admittedly. I ended up using a Lagrange multiplier at that time. But I kind of remember that 
it looked like to me that ProjectDeltaCoefficient could be used to find the DoFs to be enforced.
Hope this partial information may be useful.

**Comment by benzwick** [comment]
I need to set some values at nodes inside a mesh (not on the boundary) based on their physical coordinates. Could someone please give me some clues on how to implement the following approach (as suggested above by @tzanio) in parallel:
>```
>loop over local dofs
>   mark the dof as essential if its physical coordinates correspond to an essential BC vertex
>```
I tried to implement this based on a few other issues but so far it is not working for me and I'm having some trouble figuring out which methods to use to get the correct index to add to `ess_tdof_list` and the coordinates of each node. Each node should have a different value so I also need to set this in the correct location in the `x` ParGridFunction.

**Comment by tzanio** [comment]
Apologies for the delayed response @benzwick.

Can you clarify how you identify the dof where you want to impose the BC?

Tzanio

**Comment by benzwick** [comment]
I have the physical coordinates of a point and I would like to impose the BC at the node that is closest to this point. Currently I do this with PyMFEM and NumPy but this is not very efficient and only works in serial. I am now trying to implement this in parallel in C++.

I guess I can split the problem into two parts:
1. Find the index of the node closest to the physical point.
2. Set the BC in (for Dirichlet-type BC) the A matrix and the solution vector or (for Neumann-type BC) the right hand side vector (I need to do both in two separate problems).

Once I have the index can I just do this to set the RHS in parallel?
```
   int index = 0;
   ParLinearForm b(&fespace);
   b.Assemble();
   b[index] = 1.0;
```
and this for the Dirichlet BC?
```
   ess_tdof_list.Append(index);
   x[index] = 1.0;
```
It appears to work in serial but I think this is not correct in parallel because it will be applied on each process to the local index.

**Comment by tzanio** [comment]
I see.

@kmittal2, can we use `findpts` to find the MPI task and the corresponding local DOF that is closest to a given point in physical space?

**Comment by kmittal2** [comment]
> @kmittal2, can we use `findpts` to find the MPI task and the corresponding local DOF that is closest to a given point in physical space?

Yes, it is possible. One way to do is as follows:

1. Start with a list of `all` the points on each MPI rank.
2. Use `FindPointsGSLIB::FindPoints(xyz)` to find these points.
3. For all the points that are found on the current MPI rank, get the element number return by `FindPointsGSLIB::GetElem` and loop over the DOFs of that element to find the DOF that is closest to the sought point.

@benzwick  If this solution sounds reasonable, checkout the `FindPoints` miniapp in the gslib folder. If you have any questions about how to setup the steps mentioned above, let me know and I can try to setup a MWE for this.

Ketan

**Comment by benzwick** [comment]
Thank you for the suggestions @tzanio and @kmittal2. The FindPoints miniapp looks very useful.

If I already know the global index (e.g. from looking at the mesh and getting the vertex number) can I apply a BC or load at this point in parallel? Is there a mapping between local and global vertices or nodes?

I am guessing that #2308 and  #2311 will be helpful as well.

**Comment by benzwick** [comment]
See also:
- https://github.com/mfem/mfem/issues/2380#issuecomment-873515996
- https://github.com/mfem/mfem/issues/2277#issuecomment-849741199
