### ISSUE TITLE
How do I use SetIntRule for mixed mesh?

### ISSUE THREAD

**Issue by sshiraiwa** [mfem/mfem#1909]
Hi I would like to increase the integration order when filling the linear system. I saw SetIntRule
is there for this purpose, but I  am wondering how we can use it if I have a mixed, say triangle
and quad, element mesh. 

For example, here ( https://github.com/mfem/mfem/blob/d9c4909da3766e49e66187ee063b8504e9d5138b/miniapps/common/pfem_extras.cpp#L122)
```
    int geom = H1FESpace_->GetFE(0)->GetGeomType();
   const IntegrationRule * ir = &IntRules.Get(geom, irOrder);
```
is used to get ir to pass SetIntRule. But since the mesh is mixed,  I suppose I should pass different ir for each elements.

**Comment by vladotomov** [comment]
To have this example working for mixed meshes, you need to call `GetFE(i)`(to get the correct geometry) and increase `irOrder` to get the expected accuracy for each element type. The `IntRules` is a global object storing Gauss-Legendre quadrature rules for each element type.

Calling `SetIntRule` is not appropriate for mixed meshes, as it assumes that all elements are of the same type. If you need to use different rules (say Gauss-Legendre nodes) for the different elements, you'll have to add a new method. One example is [here](https://github.com/mfem/mfem/blob/9a1616ac3feae43ea00348464163889a0ab1b277/fem/tmop.hpp#L1188-L1194`).

**Comment by tzanio** [comment]
To add to Vladimir's answer -- there is a TODO item in the `BilinearFormIntegrator` comments that says:

```c++
   // TODO: for mixed meshes the quadrature rules to be used by methods like
   // AssemblePA() can be given as a QuadratureSpace, e.g. using a new method:
   // SetQuadratureSpace().
``` 

This will require some work, but you can add a method like this can and then use it in the integrators. @YohannDudouit and @camierjs may have thought more about this and have other suggestions.

Alternatively, we can consider adding a method `SetIntOrder` that overrides the internal `order` argument to `IntRules.Get`. This can automatically work on mixed meshes.

**Comment by tzanio** [comment]
@sshiraiwa any further thoughts on this?
