### ISSUE TITLE
Undefined symbol: mfem::MemoryManager::Delete_(void*, mfem::MemoryType, unsigned int)

### ISSUE THREAD

**Issue by dsellers94** [mfem/mfem#1910]
As I said in previous posts I am new to MFEM and C++

I have followed the serial tutorial and have built and run several examples and produced the results with GLVis.

I am attempting to use (mess around and learn) the MFEM libraries with Xcode using this stub as a test (after adding my entire mfem-4.2 directory to the header search paths):

```
#include "mfem.hpp"
#include <fstream>
#include <iostream>

using namespace std;
using namespace mfem;
```

and it fails to build with this error:

`Undefined symbol: mfem::MemoryManager::Delete_(void*, mfem::MemoryType, unsigned int)`

I don't know what this means or how to fix it. Is using Xcode the wrong approach? My limited understanding is that any C++ code will ned to be run through a compiler and Xcode is the only one I'm currently familiar with. Thanks

**Comment by dsellers94** [comment]
UPDATE: I had neglected to actually link the libmfem.a library in my Xcode project. Apparently adding my mfem-4.2 directory to the search paths was not sufficient.

**Comment by v-dobrev** [comment]
Note that it is possible to create an Xcode project for mfem using `cmake`, e.g.:
```
cd mfem
mkdir build
cd build
cmake .. -G "Xcode"
open mfem.xcodeproj
```
