### ISSUE TITLE
Example of implementing custom linear or nonlinear form?

### ISSUE THREAD

**Issue by rogeraubert** [mfem/mfem#1913]
I am considering to use MFEM as a replacement for MOOSE, which has some limitations.

Now I am trying to find out, how to implement my own linear or nonlinear form with MFEM. Is there an example or tutorial that shows the necessary steps? I found a similar question at https://github.com/mfem/mfem/issues/1005, the answers mentioning vec_conv_integrator.cpp being part of https://github.com/mfem/mfem/tree/stokes-example/miniapps/flow. But none of those mentioned files or links exists.

Thanks,
Roger

**Comment by tzanio** [comment]
Hi Roger,

You have probably seen the list of integrators in https://mfem.org/fem.

If those are not sufficient for you, we will be happy to help you write new ones. Can you please describe the problem you are trying to solve, ideally in weak form?

Regarding the example in #1005, @jandrej can correct me, but I believe he was referring to `VectorConvectionNLFIntegrator`, which is in `fem/nonlininteg.cpp` and the Navier miniapp in `miniapps/navier`.

Cheers,
Tzanio

**Comment by rogeraubert** [comment]
Thank you, Tzanio,
but I cannot ask for help and wait for an indefinite time until someone implements new forms as they become necessary for my work. I thought the process how to implement and link a new integrator would be documented somewhere to enable users to write their own integrators, since similar questions had been asked before.
So, I'm also leaving mfem behind and switch to Fenics.

Cheers,
Roger

**Comment by tzanio** [comment]
Good luck Roger. I'm sorry we couldn't help you.

Tzanio
