### ISSUE TITLE
How to get the element number ?

### ISSUE THREAD

**Issue by thelfer** [mfem/mfem#1917]
Hi,
Probably a dummy question, sorry for that.
I need to get access to the element number during the assembly of a non linear form. I just did not find how to retrieve this information while reading the doxygen documentation.
Thanks for help.
Regards

**Comment by thelfer** [comment]
Just to be sure, there is a public member called `ElementNo` in the `ElementTransformation` class. Obviously, this shall answer my question, but it is not documented, so I prefer to be sure.

**Comment by rcarson3** [comment]
Hi @thelfer, yes you can use the `ElementTransformation::ElementNo` member to get the element number associated with that object.

**Comment by thelfer** [comment]
Perfect ! Thank you. While obvious, it would deserve to be documented.
