### ISSUE TITLE
Example 2

### ISSUE THREAD

**Issue by xianyu-gao** [mfem/mfem#1919]
Dear MFEM Team
        I am testing example 2,but i can't understand the meaning of lamda and mu.if they are  Elastic modulus and Poisson's ratio?
what's i need to change if i ues one material? I try use one sample model which has four elements and six nodes,but the SparseMatrix A not 12X12.Can you help me?
![test](https://user-images.githubusercontent.com/57609268/101112112-93fe5b00-3617-11eb-99c9-3874900af9dd.jpg)
why they are not 12 Column ?

**Comment by tzanio** [comment]
Hi @xianyu-gao,

`Lambda` and `mu` are the [Lame coefficients](https://en.wikipedia.org/wiki/Lam%C3%A9_parameters) they can be converted to and from the Elastic modulus `E` and Poisson's ratio `nu`.

The unknowns in linear elasticity are the displacement vector field, so in 2D you have two unknowns per node.

Hope this helps,
Tzanio

**Comment by xianyu-gao** [comment]
when i use the beam-tri.vtk file,there will many error occur.What should to change or set up?I try to write "SetBdroundryattribute" fcuntion ,but ess_tdof_list will change so that the B also change  different from using beam-tri.mesh.Can you help me?

**Comment by tzanio** [comment]
The `beam-tri.vtk` file doesn't have the boundary attributes expected by Example 2.

Does the following work for you: `ex2 -m ../data/beam-tri.mesh`?
