### ISSUE TITLE
Mesh copy constructor leaving "sequence" and "last_operation" unassigned

### ISSUE THREAD

**Issue by mlstowell** [mfem/mfem#192]
The copy constructor located at line 2273 of mesh/mesh.cpp does not appear to set the member data "sequence" or "last_operation".  While this should be an easy thing to fix, I'm not sure of the best choice for these.  Should they simply be copied from the parent mesh, which might require copying information about the history of the parent mesh, or should they be set as if this is a newly created mesh?

**Comment by jakubcerveny** [comment]
I am not completely sure myself, but I think the safer option is to initialize these as if the mesh was brand new. It is a copy, but it also is a new instance, which we should assume is unrelated to the original object.

**Comment by mlstowell** [comment]
Sounds reasonable to me.  Thanks, Jakub!  I'll put together a small bug fix branch with this change.

**Comment by tzanio** [comment]
Fixed in #196.
