### ISSUE TITLE
VectorFEMassIntegrator vs VectorMassIntegrator

### ISSUE THREAD

**Issue by saisan7973** [mfem/mfem#1925]
What is the difference between Vector Finite Element Operators and Vector Field Operators, e.g. VectorFEMassIntegrator vs VectorMassIntegrator? Thank you!

Sai

**Comment by psocratis** [comment]
Hi @saisan7973 , 

VectorFEM operators are intended for Vector FEM spaces such as Nedelec (ND) and Raviart Thomas (RT) which correspond to H(curl) and H(div) spaces respectively. Vector Field Operators are intended for spaces that are multiple copies of scalar spaces, i.e., `H1^d` or `L2^d`. More details can be found at the following link: https://mfem.org/bilininteg/. 

Thanks, 

Socratis
