### ISSUE TITLE
OperatorPtr not working with MixedBilinearForm?

### ISSUE THREAD

**Issue by QiangWei-Wade** [mfem/mfem#1926]
The following code would not compile unless I change OperatorPtr into Operator*. However, OperatorPtr works fine with BilinearForm in the examples. There seems to be some differences (discrepancies?) in implementation.

**********
   OperatorPtr BLF;
...
   blf->FormLinearSystem(ess_tdof_list2, F, rhs, BLF, X2, RHS);
**********
test11.cpp:235:62: error: no matching function for call to ‘mfem::MixedBilinearForm::FormLinearSystem(mfem::Array<int>&, mfem::GridFunction&, mfem::LinearForm&, mfem::OperatorPtr&, mfem::Vector&, mfem::Vector&)’
    blf->FormLinearSystem(ess_tdof_list2, F, rhs, BLF, X2, RHS);
../linalg/operator.hpp:144:9: note:   no known conversion for argument 4 from ‘mfem::OperatorPtr {aka mfem::OperatorHandle}’ to ‘mfem::Operator*&’

**Comment by v-dobrev** [comment]
With `MixedBilinearForm` you should probably use the methods `FormRectangularSystemMatrix` and `FormRectangularLinearSystem`.

**Comment by QiangWei-Wade** [comment]
I see. Even if the trial space and test space are the same?

> With `MixedBilinearForm` you should probably use the methods `FormRectangularSystemMatrix` and `FormRectangularLinearSystem`.

**Comment by QiangWei-Wade** [comment]
> I see. Even if the trial space and test space are the same? @v-dobrev 
> 
> > With `MixedBilinearForm` you should probably use the methods `FormRectangularSystemMatrix` and `FormRectangularLinearSystem`.

**Comment by v-dobrev** [comment]
If the test and trial spaces are the same, then, of course, the matrix will be square and you can still use the "rectangular" methods. Typically, however, when the spaces are the same, one will use `BilinearForm` instead of `MixedBilinearForm`.

**Comment by QiangWei-Wade** [comment]
> If the test and trial spaces are the same, then, of course, the matrix will be square and you can still use the "rectangular" methods. Typically, however, when the spaces are the same, one will use `BilinearForm` instead of `MixedBilinearForm`.

That makes sense. Thanks Veselin!
