### ISSUE TITLE
Reading bi- or tri-periodic meshes with GMSH input format

### ISSUE THREAD

**Issue by latug0** [mfem/mfem#1928]
I encountered issues to use bi or tri-periodic meshes using the GMSH input format and corresponding reader. The test case considered that shows the problem uses an homogenization method for elastic materials with two materials within a cube (3D) or a square (2D). 

The MFEM input format leads to good results for this test case (meshes with .mesh extension), whereas the mesh generated through gmsh (with extension .msh) does not work properly because the final result is wrong and is also not periodic. 

In the attached files, you will find the input meshes (2D and 3D) in GMSH and MFEM input formats. Also, I join the scripts to generate the meshes. If ones compiles/launches the test program test_full_periodic, it fails with meshes coming from GMSH formats, and wors well with MFEM input meshes.

[periodicity_gmsh.zip](https://github.com/mfem/mfem/files/5659580/periodicity_gmsh.zip)

I will submit a pull request in a few minutes which should fix the issue.

Remark: with a single periodic dimension for GMSH input meshes, there is no problem of this kind. It comes with bi or tri-periodic meshes.

**Comment by tzanio** [comment]
Discussion continued in https://github.com/mfem/mfem/pull/1929
