### ISSUE TITLE
Problem with block matrix

### ISSUE THREAD

**Issue by gauthier12** [mfem/mfem#1930]
I found several problems with the block matrix illustrated with the following example : 

```c++
#include "mfem.hpp"
#include <fstream>
#include <iostream>
using namespace std;
using namespace mfem;

int main(int argc, char *argv[])
{
    SparseMatrix *matA = new SparseMatrix(2, 2);
    matA->Set(0,0,11.);    matA->Set(0,1,12.);
    matA->Set(1,0,13.);    matA->Set(1,1,14.);

    SparseMatrix *matB = new SparseMatrix(2, 2);
    matB->Set(0,0,21.);    matB->Set(0,1,22.);
    matB->Set(1,0,23.);    matB->Set(1,1,24.);

    SparseMatrix *matC = new SparseMatrix(2, 2);
    matC->Set(0,0,31.);    matC->Set(0,1,32.);
    matC->Set(1,0,33.);    matC->Set(1,1,34.);

    SparseMatrix *matD = new SparseMatrix(2, 2);
    matD->Set(0,0,41.);    //matD->Set(0,1,42.);
    matD->Set(1,0,43.);    matD->Set(1,1,44.);

    Array<int> block_offsets(3);
    block_offsets[0] = 0;    block_offsets[1] = 2;    block_offsets[2] = 4;

    BlockMatrix *block_mat = new BlockMatrix(block_offsets,block_offsets);
    block_mat->SetBlock(0, 0, matA);    block_mat->SetBlock(0, 1, matB);
    block_mat->SetBlock(1, 0, matC);    block_mat->SetBlock(1, 1, matD);
    block_mat->Finalize();
    block_mat->Print();
}
```

I create a 2x2 block matrix formed by 2x2 elements sparse matrices.
First, the null block check in blockmatrix.cpp line 150 is using the element index instead of block index and throws an error when accessing the third row because there is only 2 blocks. The first problem is easy to fix :
`blockmatrix.cpp` :
```c++
const double& BlockMatrix::Elem (int i, int j) const
{
   int iloc, iblock;
   int jloc, jblock;

   findGlobalRow(i, iblock, iloc);
   findGlobalCol(j, jblock, jloc);

   if (IsZeroBlock(i, j)) // <<<<<<<    IsZeroBlock(iblock, jblock) should be used 
   {
      mfem_error("BlockMatrix::Elem");
   }

   return Aij(iblock, jblock)->Elem(iloc, jloc);
}
```

Then, the BlockMatrix::Print() method tries to access every element as if it was a dense matrix but if an element is missing (in my example, I removed matD(0,1)), the method throws an error because matD is really sparse and the element does not exist.
I don't know if this cause problems elsewhere and I'm not sure how to fix it.
Does it make sense to return the value 0 when trying to access an undefined sparse matrix element in the SparseMatrix::Elem(i,j) method ?
An other possibility could be to loop over the block, then loop over the block's row instead of a global loop.
Best regards
Gauthier

**Comment by gauthier12** [comment]
I've created a branch 35608066621eba687a55c2e6fed45c32550182eb for the fix

**Comment by dylan-copeland** [comment]
Hello @gauthier12, thank you for finding this issue and suggesting a bug fix. I agree that your proposed fix solves one issue (it should be in both `Elem` functions). I was actually not familiar with `BlockMatrix`, and it looks like it is not used much in MFEM, which may explain why it has these bugs. While searching for its usage, I found that examples ex5/ex5p both mention `BlockMatrix` incorrectly, which should be updated as `BlockOperator`.

For the other bug, in which a zero should be returned for a `SparseMatrix` entry not found, one fix I found is in
`const double& BlockMatrix::Elem (int i, int j) const`
to replace
`return Aij(iblock, jblock)->Elem(iloc, jloc);`
with
`const SparseMatrix& AijSM = *Aij(iblock, jblock);`
`return AijSM.Elem(iloc, jloc);`

This ends up calling 
`const double &SparseMatrix::operator()(int i, int j) const`
which returns zero when not found. This is clumsy but it works. Typically, I think `SparseMatrix` entries are looked up not in this dense manner (over all entries) but sparsely, by using `GetRowEntries` and `GetRowColumns`, for example. Printing the entire matrix as a dense matrix is not very common, so I would not worry too much about making a more elegant fix.

Please let us know if you find other issues, and feel free to make a PR for these fixes or ask us to make a PR. Thanks!
Dylan

**Comment by gauthier12** [comment]
Thank you for your response. I didn't realize the "const" version of `SparseMatrix::operator()` was different than the non-const and this was what I was looking for.
I'm doing the PR with the correction.

In the other hand, I wanted to used blockmatrix but your comment about the usages of blockmatrix make me think twice about it.
If it is not very used, it can have compatibility issues with other MFEM functionnalities, can't it ?

**Comment by dylan-copeland** [comment]
@gauthier12 Whether or not to use `BlockMatrix` depends on your intended usage. This class does not have many capabilities, but there should not be compatibility issues with other MFEM functionalities (if there are, we can debug them). If you just want to form serial matrices from smaller blocks, this class should be adequate. You can also use its `CreateMonolithic` function to create a `SparseMatrix` (also serial) which is more commonly used in MFEM (e.g. the direct serial solvers work on a `SparseMatrix`).

**Comment by gauthier12** [comment]
@dylan-copeland I am trying to couple several bilinear forms (issue #1666)  so, for me, it was making sense to define the matrix by block, the diagonal ones being the standard matrix of the coupled bilinear forms and the extra diagonal, the coupling blocks.
I hesitated between BlockMatrix and BlockOperator but BlockMatrix seemed simpler in a first approach.
I haven't seen the "CreateMonolithic" so thank you, I was afraid not to be able to use the blockMatrix in the solvers.
I will make a PR if I found other problems.
Cheers 
Gauthier

**Comment by dylan-copeland** [comment]
@gauthier12 For a problem solved in serial with direct solvers, `BlockMatrix` should be adequate and simple as a first approach. In general, I would recommend using `BlockOperator` as in `examples/ex5p.cpp`, which will work for parallel computations with hypre. By the way, in your PR 1935, please feel free to change `BlockMatrix` to `BlockOperator` in the comments for ex5.cpp and ex5p.cpp. Thanks!

**Comment by uvilla** [comment]
@gauthier12 ,

Thank you for reporting this issue.

Just to provide a bit of background, the class `BlockMatrix` is widely used by the [`ParElag`](https://github.com/LLNL/parelag).

Compared to `BlockOperator`, `BlockMatrix` offers two additional features:

1. As @dylan-copeland mentioned, the ability to transform a `BlockMatrix` in a standard _csr_ sparse matrix that can then be used within a direct solver, such as `umfpack`.

2. It also offers some functionality to easily eliminate essential boundary conditions from a `BlockMatrix` using a single simple command.

I believe that the method `Elem` in `BlockMatrix` was added at a later time. The issue you reported with `IsZeroBlock` being called using `i` and `j` rather `iblock` and `jblock` is clearly a copy & past bug from the method `BlockMatrix::GetBlock(int i, int j)`.

Also, I was not aware that the non-const version of `SparseMatrix::Elem` behaves differently from its const version. 
`BlockMatrix::Elem` should then also follow the suite of `SparseMatrix::Elem`.

That is, the non-const version should like

```
double& BlockMatrix::Elem (int i, int j)
{
   int iloc, iblock;
   int jloc, jblock;

   findGlobalRow(i, iblock, iloc);
   findGlobalCol(j, jblock, jloc);

   if (IsZeroBlock(iblock, jblock))
   {
      mfem_error("BlockMatrix::Elem");
   }

   return Aij(iblock, jblock)->Elem(iloc, jloc);
}
```

while the `const` version should be something like:

```

const double& BlockMatrix::Elem (int i, int j) const
{
   static const double val = 0.;
   int iloc, iblock;
   int jloc, jblock;

   findGlobalRow(i, iblock, iloc);
   findGlobalCol(j, jblock, jloc);

   if (IsZeroBlock(iblock, jblock))
   {
      return val
   }

   return dynamic_cast<const SparseMatrix *>(Aij(iblock, block))->Elem(iloc, jloc);
}
```

Also, in the PR it would be a good idea to refactor the method `BlockMatrix::GetBlock(int i, int j)` as `BlockMatrix::GetBlock(int iblock, int jblock)`.

**Comment by uvilla** [comment]
@gauthier12 ,

Another warning regarding `BlockMatrix`.

This code was written before the CUDA support in MFEM. I am not sure whether `BlockMatrix` will work correctly if its blocks live on the GPU.

**Comment by gauthier12** [comment]
I will make the modifications both of you suggested in the PR.
@uvilla indeed, being able to eliminate row/col in a blockMatrix was the original reason I chose BlockMatrix instead of BlockOperator in the first place ! Thanks for your comments.
I think I will continue with BlockMatrix for the moment and keep BlockOperator in mind for later.

**Comment by tzanio** [comment]
Discussion continued in https://github.com/mfem/mfem/pull/1935.
