### ISSUE TITLE
Get node coordinates for entire mesh in parallel or nearest neighbor search

### ISSUE THREAD

**Issue by benzwick** [mfem/mfem#1932]
Is it possible to get all of the nodal coordinates of a `ParMesh` in a single `GridFunction` that is available on all MPI processes? In serial I use `mesh.GetNodes()` but I cannot find a way to get this to work in parallel. All my attempts so far only gave me the local nodes. My application is to find the nearest neighbors (from the global mesh) for each node in the (local) mesh but when I try to run in parallel I cannot find the neighbors across different processes.

**Comment by psocratis** [comment]
Hi @benzwick , 

I don't think there is such a functionality readily available. You can always produce the information locally on each processor and then communicate it to all the others. 

Something like the snippet below should do the work (although it could become expensive). Do you really want the information about all nodes to be available on all processors? If not there could be much easier and cheaper way to do this. What kind of neighbors are you interested in ? Vertex, edge,  face or really all the nodes neighbors ? 

````cpp
   pmesh.EnsureNodes();
   GridFunction * nodes = pmesh.GetNodes();
   int lsize = nodes->Size();
   double * ldata = nodes->GetData();

   Array<int> recv_count(num_procs);  recv_count = 0;
   Array<int> displs(num_procs);  displs = 0;

   // compute receive counts
   MPI_Allgather(&lsize,1,MPI_INT,recv_count,1,MPI_INT,MPI_COMM_WORLD);
   for (int k=0; k<num_procs-1; k++)
   {
      displs[k+1] = displs[k] + recv_count[k];
   }
   int gsize = recv_count.Sum();
   Vector global_nodes(gsize);
   double * gdata = global_nodes.GetData();
   // Gather local nodes vector to a global nodes vector on all procs
   MPI_Allgatherv(ldata,lsize,MPI_DOUBLE,gdata,recv_count,displs,MPI_DOUBLE,MPI_COMM_WORLD);

  // Note: This produces duplicated nodes since the shared nodes exist on multiple processors
````

Hope this helps!

Best,
Socratis

**Comment by benzwick** [comment]
Thanks @psocratis that is definitely helpful. I think the duplicated nodes might cause some problems though. Would it be easier to create the serial mesh first on one process, get the nodes, and send those to each other process?

I only need the node coordinates (and possibly the mapping from the global to local node number). I'm implementing a meshless method so, unlike in FEM where each element's nodes are strictly within each element and the mesh can be partitioned by finite elements, the meshless "elements" overlap and therefore a node's neighbors may be on a different process than the node itself. If I could get only the nodes within a certain radius that would be even better.

**Comment by psocratis** [comment]
> Thanks @psocratis that is definitely helpful. I think the duplicated nodes might cause some problems though. Would it be easier to create the serial mesh first on one process, get the nodes, and send those to each other process?

Hi @benzwick , you can skip the duplicate nodes when you compute the send buffer by doing something like below

````cpp
   // Get the ParFiniteElementSpace
   pmesh.EnsureNodes();
   const ParFiniteElementSpace *pfes = dynamic_cast<const ParFiniteElementSpace *>(pmesh.GetNodalFESpace());
   MFEM_VERIFY(pfes, "null pointer");

   int nldofs = pfes->GetVSize();
   int ntdofs = pfes->GetTrueVSize();
   int mytdofoffset = pfes->GetMyTDofOffset();

   for (int i = 0; i< nldofs; i++)
   {
      int tdof = pfes->GetGlobalTDofNumber(i);
      if (tdof < mytdofoffset || tdof >= mytdofoffset+ntdofs)
      {
         // Skip the tdof
         // ....         
      }
   }

````

I am not sure how you can get the nodes within a certain radius without communicating them first. I'll have to give it some more thought. 

Cheers, 

Socratis
