### ISSUE TITLE
diff two solutions on two meshes

### ISSUE THREAD

**Issue by tangqi** [mfem/mfem#1933]
Is there a simple way to diff two solutions on two non conforming meshes? For instance, one is a refined solution on a uniform mesh and one is an AMR solution. I found the field-diff app. The example is very simple, but will that work in parallel AMR meshes (quad)? Thanks.

If that's not possible, other suggestions are also welcome. I am trying to do convergence study for problems with no exact solutions.

Qi

**Comment by vladotomov** [comment]
Hi Qi,

Yes `field-diff` should work with AMR meshes, but we don't have a parallel version yet. You can use the `PrintAsOne` and `SaveAsOne` methods of `ParMesh` and `ParGridFunction` and use `field-diff` on the resulting files.
