### ISSUE TITLE
Problem reading GMSH meshes with Periodic boundary conditions

### ISSUE THREAD

**Issue by latug0** [mfem/mfem#1937]
Dear MFEM maintainer,

   I encountered some problems reading periodic meshes with GMSH format. Hence, sometimes the `Affine` keyword appears in the `$Periodic` section of the GMSH file, sometimes the keyword is missing. Well, in the GMSH reader that is provided by MFEM, there is the assumption that the `Affine`  keyword is really mandatory in this section. It leads to wrong loading of the mesh whenever the GMSH file does not include the lines with the `Affine` keyword.
 
   I provide in attached file, a mesh that has been generated wih gmsh (4.4.1 or 4.6 versions give the same output file). In these file, the `Affine` keyword does not appear in the `Periodic` section of `periodic_no_affine.msh`.

[periodic_no_affine.zip](https://github.com/mfem/mfem/files/5666836/periodic_no_affine.zip)

   I will submit a pull request in a few minutes to solve this issue.

   Regards.
Guillaume.

**Comment by tzanio** [comment]
Discussion continued in #1938.
