### ISSUE TITLE
Problems that occured when installing on Gentoo

### ISSUE THREAD

**Issue by Petross404** [mfem/mfem#1941]
Hello, I found out your library and wanted to try it on my Gentoo. I wrote an ebuild in order to install it properly with portage and I found out some issues.

First of all, cmake tries to install the final library to path `/usr/lib` ignoring the fact that in a 64bit system, 64bit libraries end up in `/usr/lib64/`, causing portage to fail during install phase because of this violation. This can easily been fixed by including `GNUInstallDirs` module like [here](https://github.com/Petross404/mfem/commit/8d5085d0e765572d2cea49797d24690b09b77c0b.patch).

While this patch uses the correct paths for installing [libs, headers, data](https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html) etc, portage gave me this warning:

```
 * QA Notice: Package triggers severe warnings which indicate that it
 *            may exhibit random runtime failures.
 * /mnt/Volume_3/Gentoo/temp/portage/sci-libs/mfem-9999/work/mfem-9999/fem/intrules.cpp:1132:11: warning: function may return address of local variable [-Wreturn-local-addr]

 * Please do not file a Gentoo bug and instead report the above QA
 * issues directly to the upstream developers of this software.
 * Homepage: https://mfem.org/
strip: x86_64-pc-linux-gnu-strip --strip-unneeded -N __gentoo_check_ldflags__ -R .comment -R .GCC.command.line -R .note.gnu.gold-version
   /usr/lib64/libmfem.so.4.2.1
```
I am not that experienced in C++ but it seems like something GCC reported for a reason.

Last, when installing I noticed this:
```
--- /usr/lib64/
>>> /usr/lib64/libmfem.so.4.2.1
--- /usr/lib64/cmake/
>>> /usr/lib64/cmake/mfem/
>>> /usr/lib64/cmake/mfem/MFEMTargets-gentoo.cmake
>>> /usr/lib64/cmake/mfem/MFEMTargets.cmake
>>> /usr/lib64/cmake/mfem/MFEMConfigVersion.cmake
>>> /usr/lib64/cmake/mfem/MFEMConfig.cmake
>>> /usr/lib64/libmfem.so -> libmfem.so.4.2.1
>>> sci-libs/mfem-9999 merged.
>>> Regenerating /etc/ld.so.cache...
```
The only thing that is installed inside `/usr/lib64` is `libmfem.so.4.2.1`. Every other package I 've seen so far uses a symlink to the library like:
```
$  sudo equery f qtcore
....
/usr/lib64/libQt5Core.so -> libQt5Core.so.5.15.2
/usr/lib64/libQt5Core.so.5 -> libQt5Core.so.5.15.2
/usr/lib64/libQt5Core.so.5.15 -> libQt5Core.so.5.15.2
/usr/lib64/libQt5Core.so.5.15.2
```

I guess the last one is something that can be fixed from CMakeLists.txt. I can search this one if you want me to.

Thank you for your time.

**Comment by Petross404** [comment]
Update: I updated the [patch](https://github.com/Petross404/mfem/commit/6266a6e38050ce246ee1daa3ef4b2339e72d4ee5.patch) and it now solves both the installation on `lib64` and the SONAME symlink:
```
sudo equery f sci-libs/mfem
...
/usr/lib64/libmfem.so -> libmfem.so.4
/usr/lib64/libmfem.so.4 -> libmfem.so.4.2.1
/usr/lib64/libmfem.so.4.2.1
...
```

I will create a PR for this.

**Comment by jandrej** [comment]
Hello,

the GCC warning is interesting and we're going to investigate (or maybe this is already known). Can you state which GCC version you are using?

From my understanding cmake should create the soname symlinks by default and only neglect them when explicitly disabled. This may be a bug in mfem's cmake configuration.

**Comment by Petross404** [comment]
I am using gcc 10.2.0-r3
```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-pc-linux-gnu/10.2.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /mnt/Volume_3/Gentoo/temp/portage/sys-devel/gcc-10.2.0-r3/work/gcc-10.2.0/configure --host=x86_64-pc-linux-gnu --build=x86_64-pc-linux-gnu --prefix=/usr --bindir=/usr/x86_64-pc-linux-gnu/gcc-bin/10.2.0 --includedir=/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include --datadir=/usr/share/gcc-data/x86_64-pc-linux-gnu/10.2.0 --mandir=/usr/share/gcc-data/x86_64-pc-linux-gnu/10.2.0/man --infodir=/usr/share/gcc-data/x86_64-pc-linux-gnu/10.2.0/info --with-gxx-include-dir=/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/g++-v10 --with-python-dir=/share/gcc-data/x86_64-pc-linux-gnu/10.2.0/python --enable-languages=c,c++,go,fortran --enable-obsolete --enable-secureplt --disable-werror --with-system-zlib --enable-nls --without-included-gettext --enable-checking=release --with-bugurl=https://bugs.gentoo.org/ --with-pkgversion='Gentoo Hardened 10.2.0-r3 p4' --enable-esp --enable-libstdcxx-time --with-build-config=bootstrap-lto --disable-libstdcxx-pch --enable-shared --enable-threads=posix --enable-__cxa_atexit --enable-clocale=gnu --enable-multilib --with-multilib-list=m32,m64 --disable-fixed-point --enable-targets=all --enable-libgomp --disable-libssp --disable-libada --disable-systemtap --enable-vtable-verify --with-zstd --enable-lto --with-isl --disable-isl-version-check --enable-default-pie --enable-default-ssp
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.0 (Gentoo Hardened 10.2.0-r3 p4)
```

According to this SO [answer](https://stackoverflow.com/a/45843676/8174056), one has to explicity state the SONAME number like this : 
```
set_target_properties(mylib PROPERTIES SOVERSION 1)
```
You can find my change in this [PR](https://github.com/mfem/mfem/pull/1942) and please let me know if I can do something better. I want this library to be available for more Gentoo users :)

**Comment by v-dobrev** [comment]
Hi @Petross404,

The CMake file allows you to set the library path via `INSTALL_LIB_DIR`, e.g. replace the default `lib` with `lib64`. Did you try that? I know that one can use `GNUInstallDirs` but I personally think that using `lib` as the default in all cases is actually more convenient for most MFEM users who do not typically install in `/usr`. In any case, using `INSTALL_LIB_DIR` should allow you the replace `lib` with `lib64` when needed.

The warning from `intrules.cpp`: I've seen it before and it is a false warning (the function never returns the address of the local variable), so it can be ignored.

The link `libmfem.so -> libmfem.so.4.2.1` is intentionally done like that since there is no guarantee that different versions of MFEM with the same major number will be fully compatible. We always try to keep things backward compatible but sometimes there are changes that require applications to be re-compiled against the new version.

**Comment by Petross404** [comment]
> The CMake file allows you to set the library path via INSTALL_LIB_DIR, e.g. replace the default lib with lib64. Did you try that? I know that one can use GNUInstallDirs but I personally think that using lib as the default in all cases is actually more convenient for most MFEM users who do not typically install in /usr. In any case, using INSTALL_LIB_DIR should allow you the replace lib with lib64 when needed.

`INSTALL_LIB_DIR` should point either to `lib` or `lib64` based on the OS architecture. This is automatically resolved from CMake when `GNUInstallDirs` and it's variables are used.

Aren't mfem users installing in `/usr`? Don't their distibutions (correctly) install mfem to `/usr`? Or the users install on their own ignoring their package manager? If so one more reason for the build system to obey the [FHS](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard) so mfem can be packaged by even more distros and more people learn about it.

> The link libmfem.so -> libmfem.so.4.2.1 is intentionally done like that since there is no guarantee that different versions of MFEM with the same major number will be fully compatible. We always try to keep things backward compatible but sometimes there are changes that require applications to be re-compiled against the new version.
I would argue that breaking the compatibility when using the same major number isn't the greatest of the ideas, but again it's your choice. Packagers should be informed about this and handle the situation accordingly based on  the tools a package manager provides.

In the end of the day I (and every user that needs to create a package for their distro) will patch heavily the build system and continue like that. Thank you for your time.

**Comment by v-dobrev** [comment]
@Petross404, is there an issue to package the library files (`libmfem.so.4.2.1` and the link `libmfem.so`) as they are installed now by the CMake build system, as it is in the MFEM repo? I realize this is not standard but is it a problem to package it that way?

One clarification regarding the MFEM version numbers: when the last number in the version (i.e. the patch number) is odd (e.g. the 1 in 4.2.1) that signifies a "development" version which remains unmodified as commits are added to the git repository. The actual releases will end with an even number and those correspond to a fixed tagged commit in the repo. In particular, the latest release of MFEM at the moment is 4.2 (or 4.2.0) and 4.2.1 is the current development version.
