### ISSUE TITLE
How to project ParBilinearForm onto ParGridFunction?

### ISSUE THREAD

**Issue by saisan7973** [mfem/mfem#1943]
Hello everyone,

I am wondering how I can project `ParBilinearForm` onto `ParGridFunction` to get `ParLinearForm`.

Additionally, what is the R required to convert `ParGridFunction` into `HypreParVector` what what would be the command to do that?

![20201213161109](https://user-images.githubusercontent.com/75665905/102006787-c5390280-3d5e-11eb-9d0e-a606a450c49b.png)

Thank you,
Sai

**Comment by tzanio** [comment]
Can you clarify what are you trying to achieve?

The diagram above just states that bilinear forms map grid functions (primal vectors) to linear forms (dual vectors).

Given a `ParGridFunction` there several `HypreParVector` objects you can derive from it, depending on if you want to assemble it (`ParGridFunction::ParallelAssemble`), average it (`ParGridFunction::ParallelAverage`) or just keep the true dof values (`ParGridFunction::ParallelProject`).

Hope this helps,
Tzanio
