### ISSUE TITLE
PCG: No convergence!

### ISSUE THREAD

**Issue by QiangWei-Wade** [mfem/mfem#1944]
I wrote a small piece of code based on ex3 and Mark's idea to compute `\integral_b^z (h(x,y,Z)-Z) dZ` where h is a scalar-valued field and z is the vertical coordinate. Unfortunately it would not converge with CG and GSSmother returned an error as well -- clear indicator that something was wrong.

To my disappointment, I stared at it for a few days without progress. Any help, literally any, is appreciated. It's a very short code I assure you.

Thank you and happy holidays.

[test15.cpp.txt](https://github.com/mfem/mfem/files/5690078/test15.cpp.txt)
[iceblock.mesh.txt](https://github.com/mfem/mfem/files/5689698/iceblock.mesh.txt)

Best regards,
Wade

> Another idea just came to mind. Use a calculus trick. Let this integral be `F(x,y,z)`. By the fundamental theorem of calculus `dF/dz = h(x,y,z)-z`. Build an FEM weak form of this equation by multiplying by the H1 basis functions and integrating. For the left hand side use the `MixedDirectionalDerivativeIntegrator` with a vector coefficient equal to the constant vector (0,0,1). For the right hand side you just need an H1 `MassIntegrator` multiplied by `ParGridFunctions` representing `h` and `z`. Apply Dirichlet boundary conditions on the z=b surface and solve for `F`. Unless I've missed something, this should work.

**Comment by mlstowell** [comment]
Hello, @QiangWei-Wade ,

I was looking at your previous iteration of this test code a bit on Friday but I hadn't really come to any conclusions.  However, this non-convergence issue is a bit more clear.  The system matrix in this case will not be symmetric so `CG` is not an appropriate choice.  I would suggest `GMRES` or a sparse direct solver such as `UMFPack` (see `ex1.cpp`).

I'll try to take a closer look at this version of the code later today.

Bests wishes,
Mark

**Comment by QiangWei-Wade** [comment]
Good morning Mark,

Thank you for your response. I tried both options without success so far.

`GMRES` with `GSSmother`:
Number of H1 finite element unknowns: 37281
terminate called after throwing an instance of 'std::out_of_range'
  what():  _Map_base::at
Aborted (core dumped)

`UMFPack`
Verification failed: (mat) is false:
 --> not a SparseMatrix
 ... in function: void mfem::UMFPackSolver::SetOperator(const mfem::Operator &)
 ... in file: /home/wade/pkuism/mfem-prism/linalg/solvers.cpp:2740

Aborted (core dumped)

[test16.cpp.txt](https://github.com/mfem/mfem/files/5697797/test16.cpp.txt)

[iceblock.mesh.txt](https://github.com/mfem/mfem/files/5697796/iceblock.mesh.txt)


By the way, what's the difference between `Operator*` and `OperatorPtr`? #1926 
Operator* BLF;
...
umf_solver.SetOperator((SparseMatrix&)(*BLF));

Cheers,
Wade

**Comment by QiangWei-Wade** [comment]
Hi @mlstowell,

I followed @v-dobrev 's suggestion in #1926 and changed `FormLinearSystem` into `FormRectangularLinearSystem`. This seemed to solve some problems but not all of them. Updated test16.cpp.txt and current error messages in the post above.

**Comment by mlstowell** [comment]
Hello, @QiangWei-Wade ,

I was able to solve this linear system with GMRES without a preconditioner using the following:
```
   GMRESSolver gmres;
   gmres.SetOperator(*BLF);
   gmres.SetRelTol(1e-10);
   gmres.SetMaxIter(1000);
   gmres.SetPrintLevel(3);
   gmres.Mult(RHS, F);
```

Convergence is poor but it does produce a result.  Unfortunately, it doesn't produce the accuracy I would have expected.

Regarding the use of `FormRectangularLinearSystem`, this should have worked.  It should also be possible to build this operator with the `BilinearForm` class and use its `FormLinearSystem` method.  It is not clear to me why these approaches are not working as expected.  This test case seems to have exposed a few of MFEM's dusty corners.

Best wishes,
Mark

**Comment by QiangWei-Wade** [comment]
Good Morning @mlstowell ,

At least it solves now:-)

Let me play around with it for a bit, add real numbers to the test and try to modify it into a parallel one. Meanwhile please let me know if you find anything.

On a side note, can I use `DerivativeIntegrator` or `ConvectionIntegrator` instead of `MixedDirectionalDerivativeIntegrator`?

Best regards,
Wade

> Convergence is poor but it does produce a result. Unfortunately, it doesn't produce the accuracy I would have expected.
> 
> Regarding the use of `FormRectangularLinearSystem`, this should have worked. It should also be possible to build this operator with the `BilinearForm` class and use its `FormLinearSystem` method. It is not clear to me why these approaches are not working as expected. This test case seems to have exposed a few of MFEM's dusty corners.

**Comment by mlstowell** [comment]
Hi, @QiangWei-Wade ,

One of my colleagues and I were looking at this earlier today.  We still have concerns about the trouble we have producing a usable matrix for this problem.  We'll need to track down those issues.  However, I did want to mention that I implemented an exact solution so that I could trace the error convergence.  I had judged the poor accuracy too quickly.  The convergence study actually showed convergence to the exact solution with an error which dropped as the mesh spacing squared for first order basis functions.  For quadratic basis functions the error was only limited by the solver tolerance since the exact solution itself is quadratic in z.

Thank you for bringing this issue to our attention.  We appreciate your feedback and I hope we can make these classes a bit more user-friendly.

Best wishes,
Mark

**Comment by QiangWei-Wade** [comment]
Hi @mlstowell ,

I would say it's a fun ride, although the learning curve is somewhat steep at first.

Now, when I try to piece the whole problem together which, if you still remember, is `VV=V ∙ F`, where `V=C∙(∇h)^3∙∂h/∂x` and `F=\integral_b^z (h(x,y,Z)-Z) dZ`. 

Now that we have have both parts of the right hand side computed as vector Gridfunction `v` and scalar GridFunction `f` respectively, I tried to form a `ScalarVectorProductCoefficient` and solve for vv. It works but feels kind of redundant. What in your opinion would be a good way to multiply them to get VV?

Thank you! 
Best wishes,
Wade

`   VectorGridFunctionCoefficient v_coef(v);
   GridFunctionCoefficient f_coef(&f);
   ScalarVectorProductCoefficient mult_coef(f_coef,v_coef);

   LinearForm *b3 = new LinearForm(&fes_nd);
   b3->AddDomainIntegrator(new VectorFEDomainLFIntegrator(mult_coef));
   b3->Assemble();
//   Create a solution vector to store vv
   GridFunction *vv = new GridFunction(&fes_nd);
   BilinearForm *a3 = new BilinearForm(&fes_nd);
   a3->AddDomainIntegrator(new VectorFEMassIntegrator(one));`

>The reason I ignored T(x,y,z) was that we can always just create a coefficient which returns the product of T and (h(x,y)-Z) and tabulate those values rather than (h(x,y)-Z).
