### ISSUE TITLE
make install broken with CUDA

### ISSUE THREAD

**Issue by stefanozampini** [mfem/mfem#1945]
I was testing for the first time the CUDA build to add support from PETSc.
I noticed that make install is broken when using SHARED libraries. 

This looks wrong (usage of BUILD_FLAGS instead of LINK_FLAGS) to me https://github.com/mfem/mfem/blob/master/makefile#L539. And it is also kind of redundant, since we have this rule here https://github.com/mfem/mfem/blob/master/makefile#L458.

Why do we need a special command to be issued here https://github.com/mfem/mfem/blob/master/makefile#L547? Why using   `install` is not enough at this point in the makefile?

**Comment by v-dobrev** [comment]
When installing the shared library, we re-link it to get the right `-install_name` on Mac; on Linux that is not necessary but it should not be a problem.

I'll try to reproduce the issue on one of LLNL's machines. Just to make sure we see the same issue: what is the error you get?

**Comment by adam-sim-dev** [comment]
Dear developers, since you begin to work with CUDA build and PETSc support, I am wondering if you can solve this issue #1625. Some users, like me, want to build mfem with CUDA, and PETSc (CUDA support in PETSc is not required.)

**Comment by v-dobrev** [comment]
@stefanozampini, I was able to reproduce the issue. Now I see what you meant: in this definition: https://github.com/mfem/mfem/blob/33dfee978b9915fa0a3c0a357f737f3dd1aefc7d/makefile#L539-L541

the `MFEM_BUILD_FLAGS` needs to be replaced to omit `-x=cu` -- one way is to use `MFEM_LINK_FLAGS` which has other flags but it works.

I'll make a PR to fix this.


> Dear developers, since you begin to work with CUDA build and PETSc support, I am wondering if you can solve this issue #1625. Some users, like me, want to build mfem with CUDA, and PETSc (CUDA support in PETSc is not required.)

@adam-sim-dev, thanks for the reminder. I'll include a fix for CUDA+PETSc in the new PR for the shared linking issue.

**Comment by tzanio** [comment]
Discussion continued in #1950. 

@stefanozampini and @adam-sim-dev -- please test and comment there.
