### ISSUE TITLE
Unsolicited Emails

### ISSUE THREAD

**Issue by wcdawn** [mfem/mfem#1952]
This isn't a problem with MFEM per se but is related. I've been receiving unsolicited emails from "jenkins ring" which seems to be run by [this organization](https://www.ring-team.org/). I get an email every time that their compilation fails. What's worse, this is not the email associated with my GitHub account but has been taken by someone from the bio in my GitHub profile.

I understand this is not an official MFEM email but I was hoping you all may have a contact in this organization.
My spam filter has not figured this one out yet.
The email is attached here.
[mfem_email.pdf](https://github.com/mfem/mfem/files/5697301/mfem_email.pdf)

**Comment by tzanio** [comment]
I have also been receiving these emails and have no idea who or why is sending them. They are definitely not associated with the mfem team at LLNL.

If someone has more information, or knows anyone at the Research for Integrative Numerical Geology group (part of Université de Lorraine) -- please speak up.

Tzanio

**Comment by tzanio** [comment]
@AntoineMazuyer -- do you know why we receive these emails, could it be Jenkings misconfiguration?

**Comment by AntoineMazuyer** [comment]
Hello everyone,

I am no longer in the organization since 2018 but I am still in touch with them. It's probably due to a configuration problem with Jenkins. I am very sorry to see that Jenkins spammed you, I will see with the RING Team to remove that.

Sorry again :/ 

Antoine

**Comment by tzanio** [comment]
No worries, thanks for checking Antoine.

**Comment by tzanio** [comment]
@AntoineMazuyer, were you able to learn more about this?

**Comment by AntoineMazuyer** [comment]
@tzanio yes It should have stopped, isn't ?

**Comment by tzanio** [comment]
These emails were sent on the 1st and the 15th of each month, and I did not receive another one on Jan 1st.

Looks like this is resolved... thanks for your help @AntoineMazuyer !
