### ISSUE TITLE
Calculate the RHS for Maxwell's equations

### ISSUE THREAD

**Issue by adam-sim-dev** [mfem/mfem#1953]
Hello, for the following Maxwell's equations:

\nabla \times [\frac{1}{\mu} \nabla \times \mathrm{E}] + \mathrm{i} \omega \sigma \mathrm{E} = - \mathrm{i} \omega (\sigma - \sigma_{\mathrm{p}}) \mathrm{E}_{\mathrm{p}}

how can I compute the RHS? If it could help understand the problem, `\sigma` and `\sigma_{\mathrm{p}}` are the conductivities with the unit of `S/m`, and `\mathrm{E}_{\mathrm{p}}` is the electric field. In the practical implementation, `\sigma - \sigma_{\mathrm{p}}` is known as a `PWConstCoefficient`,  `\mathrm{E}_{\mathrm{p}}` is also known and can be calculated for each edge (Is it a `ParComplexGridFunction`?).

Thanks.
Adam

**Comment by psocratis** [comment]
Hi @adam-sim-dev , 

One way I see doing what you need is the following. Assuming `E_p` is given as a `ParComplexGridFunction`,  you can produce a `VectorGridFunctionCoefficient`, one for the real and one for the imaginary part of E_p. Then you can create the product coefficient using `ScalarVectorProductCoefficient` and use the resulting coefficient to compute the RHS of the weak form. 

I hope this helps.

Best, 

Socratis

**Comment by adam-sim-dev** [comment]
Hi @psocratis ,

Thanks for your suggestions. I have implemented the code, however I have not obtained correct results. 

The problem may be I did not provide `Ep` as a correct `ParComplexGridFunction`. To prepare a `ParComplexGridFunction`, I first calculate the (x,y,z) components of `Ep` at the center of each edge, and then project Ep(x,y,z) onto this edge. The following is the code:

    for (int i = 0; i < pmesh->GetNEdges(); i++)
    {
        Array<int> vertices;
        pmesh->GetEdgeVertices(i, vertices);

        const double* xyz = nullptr;
        int           k;
        k         = vertices[0];
        xyz       = pmesh->GetVertex(k);
        double ax = xyz[0];
        double ay = xyz[1];
        double az = xyz[2];
        k         = vertices[1];
        xyz       = pmesh->GetVertex(k);
        double bx = xyz[0];
        double by = xyz[1];
        double bz = xyz[2];
        // Center of this edge
        double rx = 0.5e0 * (ax + bx);
        double ry = 0.5e0 * (ay + by);
        double rz = 0.5e0 * (az + bz);

        // Calculate ex, ey and ez
        complex<double> ex, ey, ez;

        double dx, dy, dz;

        // Direction of this edge??????
        if (vertices[0] > vertices[1])
        {
            dx = bx - ax;
            dy = by - ay;
            dz = bz - az;
        }
        else
        {
            dx = ax - bx;
            dy = ay - by;
            dz = az - bz;
        }
        
        // Length of this edge
        double length = sqrt(pow(dx, TWO) + pow(dy, TWO) + pow(dz, TWO));

        // Project the E field
        gf.real()[i] = ex.real() * dx / length + ey.real() * dy / length + ez.real() * dz / length;
        gf.imag()[i] = (ex.imag() * dx / length + ey.imag() * dy / length + ez.imag() * dz / length);
    }


Can somebody explain to me the the easiest way to obtain the center and direction for each vector dof for Nedelec elements in mfem?

For the first-order case, is the i-th vector dof corresponding to the i-th edge? How is its direction defined? From the first vertex to the second vertex, or from the vertex which has a smaller global index to the vertex which has a large global index? 

For high-order cases, there are both vertices and nodes, so it's much more complicated. 

Any comments are appreciated.

Best,
Adam

**Comment by psocratis** [comment]
Hi @adam-sim-dev ,  let me take a step back and ask something because this might be a lot easier than what you are trying to do.  Can you describe in more detail how is E_p given? Is there an analytic expression? Given a point in the physical space (x,y,z) can you provide the value of E_p? If that's the case, all you need to do is to provide such a function and then mfem can lift that function to the ND space using the ParComplexGridFunction::Project method. 

To answer your earlier question the ordering of dofs in mfem for a grid function is given by a vertices-edges-faces-element ordering. You can extract the dofs  from a GridFunction associated with an element by `fespace->GetElementDofs(ElemNo, elem_dofs)` of with an edge using `fespace->GetEdgeDofs(EdgeNo, edge_dofs)`.  Lastly, in the above code snippet, where are `ex, ey, ez` defined? 

Best, 

Socratis

**Comment by adam-sim-dev** [comment]
Hi @psocratis , 

I can provide the value of `Ep` at a point in the physical space `(x,y,z)`. For some kinds of problems, there is an analytic solution, however for other problems, `Ep` is calculated using more complicated external functions. Anyway, the following function is always available:

`void Calculate_Ep(other_parameters, const double& x, const double& y, const double& z, complex<double>& Ex, complex <double>& Ey, complex<double>& Ez)`

How can I use the `ParComplexGridFunction::Project` method? I would like to have a try.

Best,

Adam

**Comment by psocratis** [comment]
Hi @adam-sim-dev , 

Ok that's good. You would need to create void functions for real and imaginary parts of Ep  
````cpp
void Calulate_Ep_Re(const Vector &x, Vector &E_Re);
void Calulate_Ep_Im(const Vector &x, Vector &E_Im);
````
where `Vector x` has `size = dimension`.  From there you can create `VectorFunctionCoefficient`s, i.e, 

````cpp
 VectorFunctionCoefficient Ep_Re(dim, Calulate_Ep_Re);
 VectorFunctionCoefficient Ep_Im(dim, Calulate_Ep_Im);
````
Now you can use the above coefficients and compute the products we discussed before, i.e, there is no need to construct a `ParComplexGridFunction`. If all you need is to compute the RHS, you use the coefficients when constructing the `ParComplexLinearForm`. If for any reason you want to represent it in the solution space  (e.g. visualize it) you can project it to the space by 

````cpp
ParComplexGridFunction Ep(fespace);
Ep.ProjectCoefficient(Ep_Re, Ep_Im);
````

You can also take a look at the provided examples (ex3p, ex22p, ex25p). 

Hope this helps. 

Best, 

Socratis

**Comment by adam-sim-dev** [comment]
Hi @psocratis ,

In `void Calulate_Ep_Re(const Vector &x, Vector &E_Re);`, is E_Re for Ex_Re, Ey_Re and Ez_Re?

I will have a try. This will make my implementation much easier! Thanks!

Best,

Adam

**Comment by psocratis** [comment]
> In `void Calulate_Ep_Re(const Vector &x, Vector &E_Re);`, is E_Re for Ex_Re, Ey_Re and Ez_Re?

Yes, that is correct.
