### ISSUE TITLE
How to apply PA for Elasticity problem.

### ISSUE THREAD

**Issue by nghiakvnvsd** [mfem/mfem#1954]
Hi everybody! 

I try to apply PA for Elasticity problem (ex2). I read this on the website (https://mfem.org/performance/) and I know this is not implement on the triangles or tetrahedra elements. I just want to apply for quadrilaterals. So I try coding the ex2 using the quadrilaterals mesh but it doesn't work. It returns: BilinearFormIntegrator::AssemblePA(...) is not implemented for this class. That does seem like PA currently does not support for Elasticity, right? Or I do not know. I hope someone will give me an answer. Thank you very much!!!

**Comment by tzanio** [comment]
Hi @nghiakvnvsd,

We do not have a partial assembly formulation for linear elasticity in the library yet. We plan to add that in the future, so you can wait for that. Alternatively, you can try to develop it yourself, it should be doable once you familiarize yourself with other PA code, e.g. the one for diffusion.

I have copies @YohannDudouit and @dylan-copeland in case they have additional comments and suggestions.

Cheers,
Tzanio
