### ISSUE TITLE
Acquiring z coordinate of upper- and lower-most layer in a vertically aligned mesh

### ISSUE THREAD

**Issue by QiangWei-Wade** [mfem/mfem#1957]
Hi everyone,

Suppose I have a layered prism mesh (or tetrahedral one if they are vertically aligned) that represents an ice sheet, which has a base and surface elevation represented by the z coordinate of its lower-most and upper-most layer's points respectively. I would like to get these values and store them as two `gridfunction`s. What would be the best way to index them in MFEM?

As an example, there are a number of m=3 points every layer and n=3 layers total. Can I construct a `GridFunction surf`  and a `GridFunction base` out of this mesh containing such information?

Also, on a slightly different topic, how do I reference the coordinates in main()?

For example I have
```
double z_n_value(const Vector &x, double n)
{
   return pow(x(2),n);
}
```
My rookie c++ skills are preventing me from correctly understanding and referencing `x`. How should I call `z_n_value`?

Thanks,
Wade

(x,y,z)=
(0,0,-1)
(0,1,0)
(1,0,0)
(0,0,0)
(0,1,1)
(1,0,1)
(0,0,1)
(0,1,2)
(1,0,2)

**Comment by QiangWei-Wade** [comment]
Also, on a slightly different topic, how do I reference the coordinates in main()?

For example I have
```
double z_n_value(const Vector &x, double n)
{
   return pow(x(2),n);
}
```
My rookie c++ skills are preventing me from correctly understanding and referencing `x`. How should I call `z_n_value`?

**Comment by tzanio** [comment]
Hi @QiangWei-Wade,

One thing you can do is mark the surfaces you want with a special boundary element attribute in the mesh file and then use `FiniteElementSpace::GetEssentialTrueDofs` to find the corresponding degrees of freedom.

Regarding your second questions, `x` is a vector, typically of size 3, with `(X,Y,Z)` coordinates `(x(0),x(1),x(2))`.

Hope this helps,
Tzanio

**Comment by QiangWei-Wade** [comment]
Hi @tzanio  ,

`FiniteElementSpace::GetEssentialTrueDofs` does return a list of corresponding degrees of freedom. However, although my input mesh file provides vertices in a layered manner, i.e. bottom-most layer first and upper-most last, it seems that the the dofs returned after calling `mesh->UniformRefinement()` are no longer grouped in a layered manner. Therefore, although I can extract through `GetSubVector` the z-coordinate of all base vertices by marking `bdr_attributes`, it's still difficult to create a gridfunction h_base that represents the base elevation of every vertex. Any suggestion?

I believe I can avoid this problem by not using refinement feature, but that may be a huge loss for me in the future for not being able to utilize AMR as well..

Thank you and happy holidays!

Cheers,
Wade
```
   int n=3;
   Vector xyz(dim);
   Vector z_coord(fes_h1.GetVSize());

   mesh->GetVertices(xyz);

   Array<int> tdof_base;
   Array<int> ess_bdr_base(mesh->bdr_attributes.Max());
   ess_bdr_base = 0;
   ess_bdr_base[4] = 1; //bdr attributes for base is 5
   fes_h1.GetEssentialTrueDofs(ess_bdr_base, tdof_base);
   int numofvertices2d=tdof_base.Size();
   Vector xyz_i(dim);

// double h_value(const Vector &x)
// h_value(xyz) does not work, why?
   for (int i = 0; i < mesh->GetNV(); i++){
        xyz_i(0)     = xyz(i);
        xyz_i(1)     = xyz(i+xyz.Size()/dim);
        xyz_i(2)     = xyz(i+xyz.Size()/dim*2);
        z_coord.Elem(i)      = xyz_i(2);
        h3(i)=h_value(xyz_i,n);
   }
   
   Vector h_base_2d,h_base(fes_h1.GetVSize());
   z_coord.GetSubVector(tdof_base,h_base_2d);
   cout<<"tdof_base.Size="<<numofvertices2d<<endl;
   for (int i = 0; i < mesh->GetNV()/numofvertices2d; i++){
      for (int j = 0; j < numofvertices2d; j++){
         h_base(i*numofvertices2d+j)=h_base_2d(j);
      }
   }
   cout<<"h_base.Size="<<h_base.Size()<<endl;
   GridFunction test(&fes_h1);
   test =h_base;
```
