### ISSUE TITLE
Incorrect interpolation using AMR

### ISSUE THREAD

**Issue by makrandak** [mfem/mfem#1959]
Hello all, 

I am trying to implement non-conforming adaptive meshing for DG discretization of Euler equations.  

I have implemented an custom error estimator based on the gradient of the density, (Lp norm of the gradient of density normalized by the volume of the element).  The error estimate looks correct but when I update the function spaces and gridfunctions the interpolation on the refined mesh is incorrect. 

Here is what I am trying to do 

```
/// Setup the estimator
GradientErrorEstimator estimator(density);
estimator.SetLocalErrorNormP(1);

double max_elem_error = 1.0e-2;
int nc_limit = 3;         // maximum level of hanging nodes
ThresholdRefiner refiner(estimator);
refiner.SetTotalErrorFraction(0.0); // use purely local threshold
refiner.SetLocalErrorGoal(max_elem_error);
refiner.SetNCLimit(nc_limit);

for (int ref_it = 1; ref_it < 2; ref_it++)
{
	refiner.Reset();
	refiner.Apply(pmesh);


	// Update the space: recalculate the number of DOFs and construct a matrix
	// that will adjust any GridFunctions to the new mesh state.
	vfes.Update();
	fes.Update();
	dfes.Update();

	// Interpolate the solution on the new mesh by applying the transformation
	// matrix computed in the finite element space. Multiple GridFunctions could
	// be updated here.
	sol.Update();
	density.Update();

	if (pmesh.Nonconforming())
	{
		// Update the space again, this time a GridFunction redistribution matrix
		// is created. Apply it to the solution.
		//std::cout << "in here: " << std::endl;

		vfes.Update();
		sol.Update();
		fes.Update();
		
		// Load balance the mesh.
		pmesh.Rebalance();

		// Update the space again, this time a GridFunction redistribution matrix
		// is created. Apply it to the solution.
		vfes.Update();
		sol.Update();


		fes.Update();
		density.Update();
		
                dfes.Update();

	}

	// Free any transformation matrices to save memory.
	vfes.UpdatesFinished();
	fes.UpdatesFinished();
	dfes.UpdatesFinished();
}
```
Here I am only doing one level of refinement and updating the spaces after I refine.  

Here are some images of what I see. 

Density field before refinement 
![density_beforeRefine](https://user-images.githubusercontent.com/46409271/102643515-03e70800-4125-11eb-9dbb-a4e83c320259.png)

Calculated error estimate for threshold refiner
![errorEstimate](https://user-images.githubusercontent.com/46409271/102643517-03e70800-4125-11eb-8a76-b37762538593.png)

Density field after the refinement and updates of spaces and gridfunctions (refinement is correct but interpolation is messed up)
![density after refinement](https://user-images.githubusercontent.com/46409271/102643513-034e7180-4125-11eb-8629-5a9d030e0901.png)

**Comment by jakubcerveny** [comment]
My guess would be that you need to rebalance first (in your innermost `if` block), then update spaces, and finally update the grid-functions.

**Comment by jakubcerveny** [comment]
(Otherwise the space updates are no-ops, since the mesh didn't change from last time).

**Comment by rw-anderson** [comment]
Is dfes your density FE space?  If so, it looks like the space update and gridfunction update are in the wrong order.

**Comment by makrandak** [comment]
@jakubcerveny ,

I tried flipping the rebalance call in the if block
```
	for (int ref_it = 1; ref_it < 2; ref_it++)
	{
		refiner.Reset();
		//std::cout << "numElements inside ref Loop:" << pmesh.GetNE() << std::endl;
		refiner.Apply(pmesh);


		// Update the space: recalculate the number of DOFs and construct a matrix
		// that will adjust any GridFunctions to the new mesh state.
		vfes.Update();
		fes.Update();
		dfes.Update();


		// Interpolate the solution on the new mesh by applying the transformation
		// matrix computed in the finite element space. Multiple GridFunctions could
		// be updated here.
		sol.Update();
		density.Update();

		if (pmesh.Nonconforming())
		{

			// Load balance the mesh.
			pmesh.Rebalance();

			// Update the space again, this time a GridFunction redistribution matrix
			// is created. Apply it to the solution.
			//std::cout << "in here: " << std::endl;

			vfes.Update();
			sol.Update();
			fes.Update();
			density.Update();
			dfes.Update();


			// Update the space again, this time a GridFunction redistribution matrix
			// is created. Apply it to the solution.
			vfes.Update();
			sol.Update();


			fes.Update();
			density.Update();

			dfes.Update();
		}

		// Free any transformation matrices to save memory.
		vfes.UpdatesFinished();
		fes.UpdatesFinished();
		dfes.UpdatesFinished();
	}

```
It does not change the results. The interpolation still looks incorrect.  Also I do not understand why the balance call should be flippled.  I am following example 15 where the rebalance method is called after space update, maybe I am missing something.  

@rw-anderson, dfes is a momentum space, `fes` is the density space so I think the order for that update is correct, maybe I am missing something.  Thanks you both of you for your help. 
-Makrand

**Comment by makrandak** [comment]
Do I have to somehow update the `BlockVector`  ? I am using blockvector to create references to individual variables in the `sol` GridFunction which contains all convervative variables --> density, momentum_x, momentum_y, Energy

**Comment by jakubcerveny** [comment]
Well a space depends on a mesh, and a grid-function depends on space. If a mesh changes (de/refined or rebalanced), you need to tell the space to update itself and to construct an update matrix, which is then used on the grid-functions. The update sequence is always mesh--space--GF. 

If your space changes you may in turn need to update your BlockVectors.

**Comment by makrandak** [comment]
@jakubcerveny Thank you for that explanation I understand that now.  What I was confused about was why the order is different in example 15 inside the if block?

How do I update the corresponding BlockVectors?

**Comment by tangqi** [comment]
Here is my blockvector AMR update:
https://github.com/mfem/mfem/blob/tds-mhd-dev/miniapps/mhd/imAMRMHDp.cpp
One is for VSize and one is for TureVSize.

**Comment by jakubcerveny** [comment]
@makrandak, in example 15p there are two updates taking place. The first is done after refinement (which happens right before `UpdateAndRebalance` is called, this may be confusing). Then the mesh is rebalanced (if it is an NC mesh) and the space and GF need updating again. In both cases the sequence is always mesh--space--GF.

Refinement, derefinement and rebalancing are distinct operations, each of which requires a different update matrix/operator. We are unfortunately unable to combine these and do a single update after multiple mesh modifications, so the updates need to be done iteratively.

**Comment by makrandak** [comment]
Okay I think the problem was the way I was referencing to the different variables in the solution GridFunction and I was not updating the blockVectors.  I think rest of the sequence for the updates was correct. 

I don't know why but this worked 
```
	ParGridFunction u_0, u_1, u_2, u_3;
	u_0.MakeRef(&fes, sol, offsets[0]);
	u_1.MakeRef(&fes, sol, offsets[1]);
	u_2.MakeRef(&fes, sol, offsets[2]);
	u_3.MakeRef(&fes, sol, offsets[3]);
```
instead of 
```
ParGridFunction u_0(&fes, u_block.GetBlock(0));
ParGridFunction u_1(&fes, u_block.GetBlock(1));
ParGridFunction u_2(&fes, u_block.GetBlock(2));
ParGridFunction u_3(&fes, u_block.GetBlock(3));
```
Thanks for your help.

**Comment by vkorchagova** [comment]
Hello everyone,

The problem of synchronization of AMR, BlockVectors and GridFunctions became actual for me too.

I have the similar idea for implementation of AMR with DG: the solution stores in `BlockVector` and have a reference onto `ParGridFunction x`; and ParGridFunctions `rhok, mom, energy` are used for the VTK visualisation.
I read the discussion and created the following update function:

```
void UpdateAndRebalance(
    ParMesh &pmesh, 
    ParFiniteElementSpace &fes,
    ParFiniteElementSpace &dfes, 
    ParFiniteElementSpace &vfes, 
    ParGridFunction &x, 
    MixedBilinearForm &a, /* Aflux */
    ParNonlinearForm &b,  /* A */
    ParGridFunction &rhok,
    ParGridFunction &mom,
    ParGridFunction &energy,
    BlockVector &u_block,
    Array<int> &offsets
)
{
    x.SetFromTrueDofs(u_block);
    rhok.SetFromTrueDofs(u_block.GetBlock(0));
    mom.SetFromTrueDofs(u_block.GetBlock(1));
    energy.SetFromTrueDofs(u_block.GetBlock(num_equation-1));

    cout << "IN Update 1 x = " << endl;
    x.Print(cout);
    
    fes.Update();
    dfes.Update();
    vfes.Update();

    x.Update();

    cout << "IN Update 2 x = " << endl;
    x.Print(cout);
   
    rhok.Update();
    mom.Update();
    energy.Update();

    if (pmesh.Nonconforming())
    {
        // Load balance the mesh.
        pmesh.Rebalance();

        // Update the space again, this time a GridFunction redistribution matrix
        // is created. Apply it to the solution.
        fes.Update();
        dfes.Update();
        vfes.Update();

        x.Update();
        
        rhok.Update();
        mom.Update();
        energy.Update();
    } 

    // Compute new offsets
    for (int k = 0; k <= num_equation; k++) 
        offsets[k] = k * vfes.GetNDofs();

    u_block.Update(offsets);

    cout << "IN Update 3 u_block = " << endl;
    u_block.Print(cout);

    rhok.GetTrueDofs(u_block.GetBlock(0));
    mom.GetTrueDofs(u_block.GetBlock(1));
    energy.GetTrueDofs(u_block.GetBlock(num_equation-1));

    x.GetTrueDofs(u_block);

    cout << "IN Update 4 x = " << endl;
    x.Print(cout);

   // Free any transformation matrices to save memory.
   fes.UpdatesFinished();
   dfes.UpdatesFinished();
   vfes.UpdatesFinished();
   fes_const.UpdatesFinished();
   
   // Inform the nonlinear and bilinear forms that the space has changed.
   a.Update();
   b.Update();
   a.Assemble();   
}
```
When I run my computations I see `x` contains only zeros after `x.GetTrueDofs(u_block);` line. I guess something went wrong with some reference.

BlockVectors and ParGridFunctions were created at the main function as follows:
```
    Array<int> offsets(num_equation + 1);
    for (int k = 0; k <= num_equation; k++) 
        offsets[k] = k * vfes.GetNDofs();
    BlockVector u_block(offsets);
    ParGridFunction sol(&vfes, u_block.GetData());
    ParGridFunction rhok, mom, energy;
    rhok.MakeTRef(&fes, sol, offsets[0]);
    mom.MakeTRef(&dfes, sol, offsets[1]);
    energy.MakeTRef(&fes, sol, offsets[dim+1]);
```
I tried to use `MakeTRef` or `MakeRef` but it had't have any effect.
Also, if I comment all `SetFromTrueDofs` and `GetTrueDofs` lines, zero values appears after `u_block.Update` operation only in case of mesh refinement.

I'd appreciate any help!

--
Best regards, Victoria

**Comment by v-dobrev** [comment]
There is one important detail about using `ParGridFunction::Update` -- it will resize its data array automatically which in most cases means that the new data array will not be allocated as a block/sub-vector of a bigger block vector allocation.

One possible solution, which works well when all blocks use the same scalar FE space, is to only call `ParGridFunction::Update` for the `ParGridFunction` that represents all solution components, `sol`:
```c++
   vfes.Update(); // FE space of 'sol'

   sol.Update();
```
 Then the `BlockVector` can be updated to use the data of `sol` (after updating `offsets`):
```c++
   // update 'offsets' ...
   u_block.Update(sol, offsets);
```
It is also good to do this at initialization -- allocate `sol` and define `u_block` to point to `sol`'s data (instead of the other way around):
```c++
   ParGridFunction sol(&vfes);
   // initialize 'offsets' ...
   BlockVector u_block(sol, offsets);
```
After updating `sol` and `u_block`, all other component`ParGridFunctions` can be updated to point inside `sol` at the respective offsets with something like:
```c++
   const bool want_transform = false;
   dfes.Update(want_transform);

   mom.MakeRef(&dfes, sol, offsets[1]);
   // or
   // mom.MakeRef(&dfes, u_block.GetBlock(1));
```
When doing two updates (one for refinement, one for rebalancing), `u_block`, `rhok`, `mom`, `energy` can be updated only once -- after the second update. However, all FE spaces, `fes`, `dfes`, and `vfes`, and the `ParGridFunction` `sol` need to be updated after each mesh modification: refinement and rebalancing.
