### ISSUE TITLE
About the unit of elastic modulus

### ISSUE THREAD

**Issue by xianyu-gao** [mfem/mfem#1961]
Now I know the modulus of elasticity and Poisson's ratio. According to the formula, we can calculate the Lame constants, but what is the unit of elastic modulus?

**Comment by tzanio** [comment]
Hi @xianyu-gao,

Generally, there are no physics units in MFEM, we just implement the PDE with user-provided coefficients.

For the ElasticityIntegrator, that's just linear elasticity in displacement formulation, see https://en.wikipedia.org/wiki/Linear_elasticity#Displacement_formulation.

Depending on the meaning of your mesh, the units of length will be different...

Maybe @jamiebramwell can provide further details.

Tzanio

**Comment by benzwick** [comment]
If you are using meters (m) as units of length and Newtons (N) as units of force the elastic modulus (which in the examples is the Young's modulus) will have units of N/m^2.

See also:
- https://en.wikipedia.org/wiki/Elastic_modulus
- https://en.wikipedia.org/wiki/Young%27s_modulus
- https://en.wikipedia.org/wiki/Pascal_(unit)
- http://www.dhondt.de/ccx_2.17.pdf#section.3
