### ISSUE TITLE
The SLEPc type 'EPS' conflicts with a variable 'EPS' defined in 'pminimal-surface.cpp'

### ISSUE THREAD

**Issue by v-dobrev** [mfem/mfem#1962]
The global SLEPc type `EPS` is defined here:
https://github.com/mfem/mfem/blob/9974c0c6a9d70a50561b356e1dd9396f3678da14/linalg/slepc.hpp#L23

The conflict is here:
https://github.com/mfem/mfem/blob/9974c0c6a9d70a50561b356e1dd9396f3678da14/miniapps/meshing/pminimal-surface.cpp#L75

and also here:
https://github.com/mfem/mfem/blob/9974c0c6a9d70a50561b356e1dd9396f3678da14/miniapps/meshing/minimal-surface.cpp#L75

Here are two possible resolutions:

1. Change the variable names in `(p)minimal-surface.cpp`. A drawback here is that `EPS` is too generic as a name and keeping it may cause similar issues in other codes.
2. Rename the type from `EPS` to `slepc_EPS` in MFEM's header `slepc.hpp`. No changes are needed in `slepc.cpp` because it includes `slepc.h` (the main SLEPc header) where `EPS` is defined. This way `slepc_EPS` and `EPS` are aliases to the same type. Small drawback is that users who use `EPS` in their code will now need to include `slepc.h` in addition to `mfem.hpp`, or they can define `EPS` themselves.

Any thoughs @jetremblay, @camierjs, @tzanio?

**Comment by tzanio** [comment]
I don't think `EPS` is appropriate name for a globally exposed type. I vote for 2.

**Comment by jetremblay** [comment]
I also think option 2 makes sense. I can work on it.

**Comment by jandrej** [comment]
I think 2) is a viable option. A majority of use cases require to include `slepc.h` anyways.

**Comment by v-dobrev** [comment]
A small improvement on 2) is to put the definition of `EPS` inside `mfem::slepc` namespace and use `slepc::EPS` in the header. That way a user can just do `using namespace mfem::slepc;` to get `EPS` exposed at the global level, if they want.

**Comment by v-dobrev** [comment]
Proposed solution in #1967.

**Comment by tzanio** [comment]
☝️ looks good to me, @jetremblay what do you think?

**Comment by stefanozampini** [comment]
I prefer solution 1), using `eps` all lowercase in the example. For the same reason, one may think that `Vec` and `Mat` are too common to be exposed from petsc.hpp. This introduces inconsistency between the way native PETSc and SLEPc types are used within MFEM code.

**Comment by tzanio** [comment]
> one may think that Vec and Mat are too common to be exposed from petsc.hpp

I don't disagree with that actually. It is just a matter of time before we run into user that has decided to use these names. It has happened in the past.

**Comment by v-dobrev** [comment]
@stefanozampini, I don't think using a different type-name in `slepc.hpp` will cause any issues (it is just an alias for the same type as `EPS`). For example, if you want to extract the original `EPS` handle from the MFEM wrapper to use it with some SLEPc function, you already **need** to have `#include <sleps.h>` in that source file, so you'll have the `EPS` definition you want. For example, in #1967, I did not need to change anything in `slepc.cpp`.

If we want, I think, we can do the same in `petsc.hpp` with the types like `Vec`, `Mat`, `PC`, etc (e.g. hide them in namespace `mfem::petsc`), and that will not create any issues for existing code inside MFEM or based on MFEM.

**Comment by tzanio** [comment]
Other folks are running into this. Can we move forward with #1967?

**Comment by tzanio** [comment]
Discussion continued in #1967.
