### ISSUE TITLE
Use GetGradient to provide an analytical Jacobian while using PetscPreconditionerFactory

### ISSUE THREAD

**Issue by tangqi** [mfem/mfem#1964]
Is it possible to still use GetGradient to provide an analytical Jacobian for PetscNonlinearSolver while using PetscPreconditionerFactory to provide my own preconditioner. 

My understanding is the current petsc interface use GetGradient to communicate mfem matrices with petsc inside PetscPreconditionerFactory. So it naturally uses JFNK. But in my very refined simulations, the JFNK struggles to provide a good matrix vector product. So I want to provide Jacobian by myself. Matrix manipulation ("physics-based" preconditioning) can be done when initializing `PetscPreconditionerFactory::NewPreconditioner`. Thus, I only need to provide one GetGradient for both Jacobian and preconditioner. Is this possible in the current interface? Or does PetscPreconditionerFactory require JFNK being called, so it will skip GetGradient in Newton solve?

**Comment by tzanio** [comment]
I will let the experts answer, but have you looked at `examples/petsc/ex10p.cpp`?

**Comment by stefanozampini** [comment]
The factory is not limited to JFNK: it is a small layer in between MFEM and PETSc that is able to return control to the user's  code, which may setup the solver the way they prefer. The factory creates preconditioners using the pmat passed to PETSc, see here https://github.com/mfem/mfem/blob/master/linalg/petsc.cpp#L4511, which is the one obtained from GetGradient, see here https://github.com/mfem/mfem/blob/master/linalg/petsc.cpp#L4187.

**Comment by tangqi** [comment]
Great. That's good news! So if I want to use both analytical Jacobian and pcshell preconditioner, I should remove the flag `-snes_mf_operator` in rc_ex10p_jfnk and still use the original flag for jfnk:
`-m ../../data/beam-quad.mesh --usepetsc --petscopts rc_ex10p_jfnk -jfnk -tf 6 -s 3 -rs 0 -dt 3`
Is that right?

It does report `linear system matrix = precond matrix` instead of `mffd` while the `_jfnk` shell preconditioner is still called.
