### ISSUE TITLE
Unexpected setting of boundary condition behavior

### ISSUE THREAD

**Issue by nnpp-schneier** [mfem/mfem#1968]
I wanted to see if anyone had insight into (what I think is) strange behavior when trying to set boundary conditions on my own. My use case is a bit non-standard, I am trying to add one matrix generated by a bilinear form (let's call this matrix A) to another matrix generated by a nonlinear form (lets call this matrix N). 

The first implementation I tried was to assemble A with the boundary conditions applied, and then to assemble N and eliminate the rows and columns corresponding to the boundary conditions, while placing a 0 on the diagonals. The code I have to do that looks something like this.

   ```c++
    aVar->AddDomainIntegrator(new VectorDiffusionIntegrator());
    aVar->Assemble();
    aVar->EliminateEssentialBC(ess_bdr, x_bdr, rhs.GetBlock(0));
    aVar->Finalize();  
    SparseMatrix &A(aVar->SpMat());

    NonlinearForm *Non(new NonlinearForm(Xh_space));
    Non->AddDomainIntegrator(new MyNonLinearForm());
    SparseMatrix *N = dynamic_cast<SparseMatrix*>(&Non->GetGradient(u));

    for (int i = 0; i < ess_tdof_list.Size(); i++)
           {
              Non->EliminateRowColDiag(ess_tdof_list[i], 0.0); 
           }


*N += A; 
```
However, this appears to be giving me the wrong the solution (although it is close to being correct). On the other hand when I add them both and then apply the boundary conditions I get the correct answer

  ```c++
    aVar->AddDomainIntegrator(new VectorDiffusionIntegrator());
    aVar->Assemble();
    aVar->Finalize();  
    SparseMatrix &A(aVar->SpMat());

    NonlinearForm *Non(new NonlinearForm(Xh_space));
    Non->AddDomainIntegrator(new MyNonLinearForm());
    SparseMatrix *N = dynamic_cast<SparseMatrix*>(&Non->GetGradient(u));

    *N += A; 

     for (int i = 0; i < ess_dof.Size(); i++)
            if (ess_dof[i] < 0)
            {
                N -> EliminateRowCol(i, x_bdr(i), rhs.GetBlock(0));
            }

```
Based on my reading of the documentation both of these approaches should have yielded the same answer. Am I missing something and it is obvious why they do not?

**Comment by tzanio** [comment]
Hi @nnpp-schneier,

I will let @jandrej comment if this setup is the best way to accomplish your goals, but I can comment and hopefully clarify the handling of boundary conditions.

Borrowing from https://github.com/mfem/mfem/issues/1720#issuecomment-684174484, lets say `A`, `N` the solution `x`, and the `rhs.GetBlock(0)` vector `b` have the interior/boundary form

```
A = | A_I  A_IB |   N = | N_I  N_IB |   x = | x_I |   b = | b_I |
    | A_BI A_B  |       | N_BI N_B  |       | x_B |       | b_B |
```

Then in the **first** approach, ` aVar->EliminateEssentialBC(ess_bdr, x_bdr, rhs.GetBlock(0));` transforms

```
A = | A_I  A_IB | -->  A = | A_I  0 |
    | A_BI A_B  |          |  0   I |
```

and

```
b = | b_I | --> b = | b_I - A_IB x_B |
    | b_B |         | x_B            |
```

while  `Non->EliminateRowColDiag(ess_tdof_list[i], 0.0);` transforms

```
N = | N_I  N_IB | -->  N = | N_I  0 |
    | N_BI N_B  |          |  0   0 |
```

Therefore the final matrix and vector are

```
| A_I + N_I  0 |   | b_I - A_IB x_B |
|     0      I | , | x_B            |
```

In the **second** approach, the call `N -> EliminateRowCol(i, x_bdr(i), rhs.GetBlock(0));` produces final matrix and vector

```
| A_I + N_I  0 |   | b_I - (A_IB + N_IB) x_B |
|     0      I | , | x_B                     |
```

which has the additional `N_IB x_B` component in the interior portion of the right-hand side.

This is a small difference that only matters for nonzero essential boundary conditions.

Hope this helps,
Tzanio

**Comment by tzanio** [comment]
I believe the question was answered, so I am closing this issue for now. Feel free to reopen if you have further questions.
