### ISSUE TITLE
Custom refiner for AMR: Data struture maintaining the refinement level of an element

### ISSUE THREAD

**Issue by makrandak** [mfem/mfem#1970]
Hello all, 

I am trying to modify the Threshold refiner for the Euler equations.  I am looking for a data structure in the mesh which will allow me to check whether the element has been refined to the maximum refinement level (specified by the user not by a global norm as in Threshold refiner).  So there will be no extra refinement after the elements have reached the finest refinement level specified by the user.  Is there a datastructure in the mesh which maintains the refinement level of an element ? 

The idea is to replace this logic 
```
for (int el = 0; el < NE; el++) {
		if (local_err(el) > threshold) {
			marked_elements.Append(Refinement(el));
		}
	}
```
by something like this 

```
for (int el = 0; el < NE; el++) {
		if (local_err(el) > threshold  && refine_level(el) < user_specified_level ) {
			marked_elements.Append(Refinement(el));
		}
	}
```
This will only allow the refinement till the level specified by the user `user_specified_level` .  This is important because one cannot use a global norm for these potentially discontinuous solutions to Euler equations.  The local error estimate here is just the elemental L_p norm of the density gradients normalized by the element volume.  

Thanks for your help. 

-Makrand

**Comment by jakubcerveny** [comment]
We don't have a proper interface for this right now, but if your mesh is an NC mesh (you're using hanging nodes), you can call the  method `NCMesh::GetElementDepth`, which has been used for a similar purpose here: https://github.com/CEED/Laghos/blob/cba6a8b65444479c93f76b9c16b0ac28a76da8bc/amr/laghos.cpp#L642 You can also take a look at `NCMesh::GetElementSizeReduction`. (Note that calling NCMesh directly is unofficial and we may change the interface in the future.)

**Comment by makrandak** [comment]
Hello @jakubcerveny, 

Thanks for your quick reply.  I will ensure that that the mesh is NC mesh I think there is a method for that `pmesh->ensureNCmesh`.   Is the interface work in progress? in that case I can write a comment in my code referring future developers to the PR. 

`GetElementDepth` should work for now.  Let me try and understand the usage and come back if I have problems.  

Also, is there a function based refinement interface ? This is useful for initial conditions, for example if I have intersection of 4 shocks defined by a discontinuous function, is there an interface which will refine near the shock?  

The idea here would be pass a `std::function` to the interface and it should essentially construct a binary map using the function, and use that to refine the mesh (maybe using the `RefineByVertex` methods).  I could implement this but, my experience has been with NCmeshes only (that is my PhD), and I don't know what extra things I would have to implement to make it consistent with all the support in mfem. 

Appreciate your reply during the holiday season. 

With sincere regards,
Makrand

**Comment by tangqi** [comment]
I added my own maximum refinement levels, refinement ranges and so on in my app. See https://github.com/mfem/mfem/blob/3623f093c82250d510364d30b7b8afc7430477ca/mesh/mesh_operators.cpp#L187
for instance

**Comment by makrandak** [comment]
Hello @tangqi, 

Did you have any trouble using the `GetElementDepth(el)` method ? Anything special other than ensuring NCmesh ? 
-Makrand

**Comment by tangqi** [comment]
No. One interesting thing is after calling `EnsureNCMesh()`, all the current levels become 0. (So one cannot derefine further). For instance, see https://github.com/mfem/mfem/blob/3623f093c82250d510364d30b7b8afc7430477ca/miniapps/mhd/imAMRMHDp.cpp#L338

**Comment by makrandak** [comment]
Hello @tangqi,

Thanks for that tip, that is useful, so one can do a bunch of uniform refinements and then call `EnsureNCMesh()`  and then start counting the refinement levels from there on.  Thanks for this. 
-Makrand

**Comment by jakubcerveny** [comment]
Hello @makrandak,

I'm not aware of an effort to make GetElementDepth or similar official. Perhaps we should think about it, as there seems to be interest. I think "depth" is actually not a good measure because it only makes sense for NC meshes with isotropic refinements. A general API should probably work with element size in the X, Y, Z reference directions.

Regarding your question about function-based refinement interface, we don't have that out of the box either, but something similar was done in the `shaper` miniapp (`miniapps/meshing/shaper.cpp`). A generalization of that could perhaps be added as an API in the future too.

Jakub
