### ISSUE TITLE
How to determine term specific boundary term in MFEM

### ISSUE THREAD

**Issue by kolotinsky1998** [mfem/mfem#1972]
Hi, dear community!

I use MFEM to solve a 3D electromagnetic problem for a waveguide geometry. I need to add specific term in belinear form to consider absorbing boundary conditions:  

<img src="https://render.githubusercontent.com/render/math?math=\iint_{\delta\Omega} (\overline{E} \times \overline{n})\cdot(\overline{v} \times \overline{n}) \,d\delta\Omega">, <img src="https://render.githubusercontent.com/render/math?math=\overline{E}"> - unknown function of electric field, and <img src="https://render.githubusercontent.com/render/math?math=\overline{v}"> - test function. Both are defined in Nedelec complex functional space.

The problem is I can not find a way to add that bilinear form to my MFEM code. Could you help me with that issue?

Thanks in advance,
Danil

**Comment by psocratis** [comment]
Hi @kolotinsky1998

The `BoundaryIntegrator` you need is not currently in `master`. 
However, I implemented it over the last weekend ( I need to test impedance boundary conditions for Maxwell too). I am doing some final tests and I will open a PR by the end of the day. In the meantime, you might want to take a look at ex25/ex25p where there is already an example of a waveguide with a PML.

Best, 

Socratis

**Comment by sshiraiwa** [comment]
Hi @psocratis]. I am wondering if we can simply use VectorFEMassIntegrator for this purpose, when the element  is ND.

**Comment by psocratis** [comment]
> Hi @psocratis]. I am wondering if we can simply use VectorFEMassIntegrator for this purpose, when the element is ND.

Actually, yes, you are right! I hadn't realized that before. I just tested it and works fine. 

Thanks, 

@kolotinsky1998 you want to give it a try and let us know if it works for you? 

Best, 

Socratis

**Comment by kolotinsky1998** [comment]
Thank you very much for your help! A have tried your approach, it works for me :)
