### ISSUE TITLE
May I ask a question about example 2 of mfem?

### ISSUE THREAD

**Issue by HFH104864** [mfem/mfem#1973]
In example 2, is there a solution for the stress?If not, could you please inform me where the example does 

I would appreciate it if you would let me know in time

Thank you !

**Comment by tzanio** [comment]
Hi @HFH104864,

Example 2 computes the displacements for a linear elasticity problem.

Regarding stress computation from these, have you looked at https://github.com/mfem/mfem/issues/10 and https://github.com/mfem/mfem/issues/109?

Hope this helps,
Tzanio

**Comment by HFH104864** [comment]
not yet , and I have no idea about what the #10 and #109 mean

**Comment by HFH104864** [comment]
It really help  , thank you !
