### ISSUE TITLE
Use of VectorDomainLFIntegrator and MatrixVectorProductCoefficient

### ISSUE THREAD

**Issue by robert-chiodi** [mfem/mfem#1976]
Hello,

I believe there is an issue with using `MatrixVectorProductCoefficient` with `VectorDomainLFIntegrator`, specifically that `VectorDomainLFIntegrator` does not `SetSize` for its private variable `Qvec`. With `Qvec` not set to a proper size (of `Q.GetVDim()`), the `DenseMatrix::Mult(const Vector& x, Vector& y)` method used in `MatrixVectorProductCoefficient::Eval` fails since the vector `V` (`Qvec`) is not of the appropriate size.

I am not sure what the preferred way to fix this would be, but calling `Qvec.SetSize(vdim);` after setting the size of `shape` in `VectorDomainLFIntegrator::AssembleRHSElementVec` would work I think.

Please let me know if this is not an issue and I am just using the coefficients improperly.

**Comment by mlstowell** [comment]
Hi, @robert-chiodi ,

This is a bug in `MatrixVectorProductCoefficient`.  The documentation for the `VectorCoefficient::Eval` method does not explicitly state that the output vector will be resized by this call but this is what happens in most, hopefully all, other such calls.

Thanks for catching this and sorry for the trouble.  I'll create a quick bug fix.

Best wishes,
Mark

**Comment by robert-chiodi** [comment]
Not a problem, and thanks for the quick bug fix!
