### ISSUE TITLE
Get a value that is not on a mesh node

### ISSUE THREAD

**Issue by LeilaSalomon** [mfem/mfem#1979]
Hello everybody ! :)

I solve a Laplace equation : Laplacian(phi) = 0. After solving this equation, I get phi values on the nodes of the mesh.
I'm wondering if there is a simple way to get phi on coordinates which don't correspond to nodes, without use IntegrationPoint ?

Hoping you can help me :)

Best wishes

**Comment by tzanio** [comment]
Hi @LeilaSalomon,

To clarify -- you want to evaluate a `GridFunction` in a physical point for which does not necessarily corresponds to a known integration point in a known element, is that correct?

If that's the case, @kmittal2 can help you, see e.g. the Find Points Miniapp in `miniapps/gslib`.

Tzanio

**Comment by LeilaSalomon** [comment]
Not necessarily a GridFunction, for example I would like to know phi at x = 0.13 y = 0.67 (coordinates which don't correspond to a node).If I decide to use GetValues, am I forced to utilise an IntegrationPoint?

**Comment by tzanio** [comment]
> If I decide to use GetValues, am I forced to utilise an IntegrationPoint?

Yes

**Comment by pazner** [comment]
> Not necessarily a GridFunction, for example I would like to know phi at x = 0.13 y = 0.67 (coordinates which don't correspond to a node).If I decide to use GetValues, am I forced to utilise an IntegrationPoint?

Note that an `IntegrationPoint` is really little more than xyz coordinates, and there is no reason that I can see to avoid using one.

The proper algorithm for what you need will depend on whether you know which element the point (0.13, 0.67) lies in or not.

**Comment by LeilaSalomon** [comment]
Let's imagine that I don't know which element it is in, how can I do it?

**Comment by kmittal2** [comment]
Hi @LeilaSalomon,

The [findpts](https://github.com/mfem/mfem/blob/master/miniapps/gslib/findpts.cpp) miniapp demonstrates how a `GridFunction` can be interpolated at arbitrary points (not coincident with mesh nodes) in physical space. We have recently added support for functions in H1/L2/H(div)/H(curl).

I am not sure what you mean by "Not necessarily a GridFunction". What else are you trying to interpolate? Is your solution, phi, not a `GridFunction`?

Ketan

**Comment by LeilaSalomon** [comment]
Hi, I wanted to know if there is an easier way than installing Gslib, but it can be my solution!

**Comment by LeilaSalomon** [comment]
Hello !

I installed gslib. When I go to miniapps/gslib, I can compile findpts.cpp well. On the other hand, if I move find.cpp in my personal file where I compile my other codes, it doesn't work. There must be some problem to link mfem and gslib, after a lot of trying, I can't find the solution.
![capture](https://user-images.githubusercontent.com/40572513/103813241-0e2f5e80-5060-11eb-8c7d-bfa1f4066bef.png)

**Comment by kmittal2** [comment]
Hi @LeilaSalomon,

Not quite sure why you are getting this error. I tried on my machine and I am able to build and run findpts.cpp from another folder. Can you make sure you are setting up your CMakeLists.txt properly? Did you follow the instructions in MFEM INSTALL for building using CMake?

Ketan

**Comment by LeilaSalomon** [comment]
Hi Ketan :) 

Yes I think I configured my CMakeList.txt wrong but I don't see the error again. I'm going to find a solution.

Simultaneously, I just got a new error with using gslib to find points. I am using findptd every time step in my code, I think I have a memory allocation problem, but I don't really know what. 

![capt](https://user-images.githubusercontent.com/40572513/104356030-bf743f80-550b-11eb-8927-695804728a3c.png)

Does this problem tell you something?

**Comment by kmittal2** [comment]
Can you please share part of your code where you use `findpts`? Do you get this error the first time you use `findpts` or after a certain number of time steps?

**Comment by LeilaSalomon** [comment]
FindPointsGSLIB finder;
     finder.Setup(*mesh);
     finder.SetL2AvgType(FindPointsGSLIB::NONE);
     finder.Interpolate(Coord_SL, pressure, interp_vals);

I get this error after a certain number of time steps

**Comment by kmittal2** [comment]
If the code snippet that you have shared is within a loop, then the error that you are getting is probably because you are running out of memory. You can resolve that by adding `finder.FreeData()` after the call to `Interpolate`.

**Comment by kmittal2** [comment]
@LeilaSalomon did that resolve the issue?
On a quick note, if your mesh is static and does not change with time, then you can move the call to `Setup` outside the loop since `Setup` needs to be called only once for a given mesh. Additionally, if the points that you are interpolating your solution at are also fixed, you can make one additional optimization by calling `FindPoints` outside the loop as well.
```
FindPointsGSLIB finder;
finder.Setup(*mesh); // This needs to be called only once for a given mesh
finder.FindPoints(Coord_SL) // This needs to be called only once for a given set of points to be found on a given mesh. If Coord_SL is changing with time, move this inside the loop.
for (int i = 0; i < total_steps; i++) {
     .
     .
     .
     finder.Interpolate(pressure, interp_vals); 
}
finder.FreeData()
```

Hope this helps,
Ketan

**Comment by LeilaSalomon** [comment]
I just tried finder.FreeData () and it works! Thank you very much for your help and for your advice!! :)

**Comment by kmittal2** [comment]
Glad to hear that @LeilaSalomon. I will close this issue for now but feel free to open it if you have any more questions.

**Comment by TobiasDuswald** [comment]
Dear MFEM Team,

I'm working on hybrid modelling, a method that combines discrete agents and a continuum model. A prominent example is, for instance, the combination of biological cells and a reactio-diffusion equation (e.g. MFEM example 16). One of the challenges is to have an efficient interface between the discrete and continuum model. Staying with the example, cells need to be able to read the nutrient/oxygen concentration at their respective position (x,y,z). I had the intention to use MFEM for the continuum model. Basically, that leads me to the same problem that has been discussed in this thread. In a simulation, I need to determine the value of the grid function `u_gf` (continuum model) at the position of the cells (x_i, y_i, z_i). I'd like to integrate it into a larger software project ([BioDynaMo](https://github.com/BioDynaMo/biodynamo)) and `GSLIB` might be a dependency that I'd like to avoid for this project. So basically I wondered the following. Does MFEM support (or plan to support in the near future) the following:

- Identifying the closest node/integration point to a given vector 
- Identifying the element to which a given vector belongs to
- Evaluating the `GridFunction` at a certain position x,y,z

I'd be very happy if you get back to me. If you have any other suggestions about how to interact with the GridFunction or similar classes to extract the values of the continuum with MFEM I'd also be very happy to hear about them.

Kind regards & thank you very much, Tobias

**Comment by v-dobrev** [comment]
Hi @TobiasDuswald,

You can use the method `(Par)Mesh::FindPoints`: https://github.com/mfem/mfem/blob/9f7d5736d3518d2a665d15dde5efcc782f2269e8/mesh/mesh.hpp#L1504-L1531

To evaluate a `GridFunction` in a given element at a given reference `IntegrationPoint` you can use methods like `(Par)GridFunction::GetValue`, and `(Par)GridFunction::GetVectorValue`: https://github.com/mfem/mfem/blob/9f7d5736d3518d2a665d15dde5efcc782f2269e8/fem/gridfunc.hpp#L154-L173

**Comment by TobiasDuswald** [comment]
Thank you for your quick response @v-dobrev, I tried it and I believe for a first attempt it's precisely what I need. That's great, makes my day! Thank you very much again!
