### ISSUE TITLE
How to change a Neumann boundary condition ?

### ISSUE THREAD

**Issue by LeilaSalomon** [mfem/mfem#1980]
Hello,

I'm solving the following equation: Laplacian (p) = 0

My domain is rectangular, I would like to impose a Dirichlet boundary condition on the upper wall of the domain, and Neumann conditions on the 3 other walls. On the side walls I would like dp/dn = 0, but on the bottom I would like dp/dn = f (x, y).

I initialize a GridFunction with p values corresponding to the desired Dirichlet condition on the top wall of the domain.

Then, I use a ess_bdr vector of size 4 (the number of walls) in which I attribute 1 or 0 to specify the boundary condition. If I put 1 -> Dirichlet, if I put 0 -> Neumann : dp/dn = 0. 

It works well except for the back wall. How can I indicate dp/dn = f (x, y) not dp/dn = 0 ?

Have a lovely day :)

Best wishes,

Leïla Salomon

**Comment by tzanio** [comment]
Inhomogeneous Neumann boundary conditions result in adding another linear form to the right-hand side. 

You can see how this is done e.g. in Example 27, https://github.com/mfem/mfem/blob/master/examples/ex27.cpp#L242-L243
