### ISSUE TITLE
How to apply traction Neumann boundary condition given analytical stress tensor

### ISSUE THREAD

**Issue by benzwick** [mfem/mfem#1982]
I am trying to solve the infinite plate with hole problem using MFEM and I have some questions about how to apply the traction Neumann boundary condition.

Here are some descriptions of the problem:
- https://en.wikiversity.org/wiki/Introduction_to_Elasticity/Plate_with_hole_in_tension
- http://solidmechanics.org/Text/Chapter5_3/Chapter5_3.php#Sect5_3_5
- https://en.wikipedia.org/wiki/Kirsch_equations

As I am modelling a finite part of the infinite plate I need to apply the analytical solution for stress on its boundary.

I have considered a few different options but it would great to have some guidance on the best approach for how to do this. Basically I have a known stress tensor `T` and the traction vector `g` to be applied on the boundary is defined by `g = T*n` with `n` being the unit normal vector.

1. Should I define the complete stress tensor `T` as a `MatrixFunctionCoefficient` or would it be better to define each component (`Txx,Txy,Tyy`) separately as `FunctionCoeffient`s?

2. Once I have the stress tensor, how can I evaluate `T*n` and apply it on the boundary as a traction vector?

**Comment by barker29** [comment]
I think what you want to do here is apply the known `g` on the boundary as the usual type of Neumann boundary condition using `VectorBoundaryLFIntegrator`. I recommend following what is in `ex2.cpp` step 7, where `f` corresponds to what you've written as `g` above. Instead of the `PWConstCoefficient` in `ex2` you probably want a `VectorFunctionCoefficient` to evaluate your known `g`.

Does that help?

**Comment by benzwick** [comment]
@barker29 Yes that helps. Is it possible to compute the vector function `g` using the matrix function `T` through the dot product `T*n` and apply this to the entire Neumann boundary? Maybe something like `BoundaryNormalLFIntegrator` but using a `MatrixCoefficient` instead of a `VectorCoefficient`, i.e. a `VectorBoundaryNormalLFIntegrator` (which does not exist in MFEM yet)?

This is the analytical function for the stress tensor/matrix `T`:
```
void exact_stress(const Vector &x, DenseMatrix T)
{
   double r = sqrt(x[0]*x[0] + x[1]*x[1]);
   double t = atan2(x[1], x[0]);
   double a = 1;
   double s = 5;
   double T_0 = 1;

   T(0,0) =  T_0/2. * (1 - (a*a)/(r*r) * (3./2. * cos(2*t) + cos(4*t)) + (3*pow(a,4))/(2*pow(r,4)) * cos(4*t));
   T(1,1) = -T_0/2. * (    (a*a)/(r*r) * (1./2. * cos(2*t) - cos(4*t)) - (3*pow(a,4))/(2*pow(r,4)) * cos(4*t));
   T(0,1) = -T_0/2. * (    (a*a)/(r*r) * (1./2. * sin(2*t) + sin(4*t)) + (3*pow(a,4))/(2*pow(r,4)) * sin(4*t));
   T(1,0) = T(0,1);
}
```

**Comment by barker29** [comment]
Something like you suggest is certainly possible, but you are right that it doesn't exist. It should be a pretty minor modification of `BoundaryNormalLFIntegrator`, where `Qvec` is replaced with the result of `T.Mult(nor, y);` where `T` is what comes out of your `exact_stress` above. I would recommend writing your own custom `LinearFormIntegrator` after the model of `BoundaryNormalLFIntegrator`.
