### ISSUE TITLE
How to solve plastic problem with MFEM?

### ISSUE THREAD

**Issue by successor-of-communist** [mfem/mfem#1985]
Hi all
I am a beginner of fem. I want to know if this software MFEM can solve an elastic plastic problems. 
If yes, how? Can you give me some examples?

Thanks.

**Comment by tzanio** [comment]
In general MFEM provides the building blocks you will need for that, but we don't have any examples for it. The closest is simple linear elasticity (ex2) and nonlinear hyperelastic model (ex10).
