### ISSUE TITLE
Transfer from H1_Trace <-> DG_Interface

### ISSUE THREAD

**Issue by bensworth** [mfem/mfem#1988]
Hi MFEM team, I am trying to map between two ParFiniteElementSpaces defined on a DG_Interface_FECollection() and an H1_Trace_FECollection(), on the same mesh. In principle, I expect this would be similar to mapping between H1 and L2/DG. It seems that neither of the built in GridTransfer operators permit this, L2ProjectionGridTransfer and InterpolationGridTransfer, as they both require `(GetLastOperation() == Mesh::REFINE)`, and are more designed for mesh refinement than different finite element spaces?

I also tried to sketch out something that would do it manually, but found that FiniteElements in either the DG_Interface_FECollection or H1_Trace_FECollection do not support several of the main Finite element functions, including `GetDof()`, `GetDim()`, `GetGeomType()`, or `GetOrder()`. I also looked at the `GetFaceDofs()` as suggested by @pazner to get DOFs associated with trace spaces, but this is only defined for `Linear3DFiniteElement`.

Any help on mapping between these spaces would be greatly appreciated.

**Comment by pazner** [comment]
> I also looked at the `GetFaceDofs()` as suggested by @pazner to get DOFs associated with trace spaces, but this is only defined for `Linear3DFiniteElement`.

I think the relevant function is `FiniteElementSpace::GetFaceDofs` (and not `FiniteElement::GetFaceDofs`).

Something like this should probably do the trick to map from H1 to DG (but someone with better knowledge of the trace spaces should confirm...)
```c++
#include "mfem.hpp"
#include <fstream>
#include <iostream>

using namespace std;
using namespace mfem;

int main(int argc, char *argv[])
{
   const char *mesh_file = "../data/star.mesh";
   int order = 1;

   OptionsParser args(argc, argv);
   args.AddOption(&mesh_file, "-m", "--mesh", "Mesh file to use.");
   args.AddOption(&order, "-o", "--order", "Polynomial degree.");
   args.Parse();
   if (!args.Good())
   {
      args.PrintUsage(cout);
      return 1;
   }
   args.PrintOptions(cout);

   Mesh mesh(mesh_file, 1, 1);
   int dim = mesh.Dimension();

   H1_Trace_FECollection h1_fec(order, dim);
   DG_Interface_FECollection dg_fec(order, dim);

   FiniteElementSpace h1_fes(&mesh, &h1_fec);
   FiniteElementSpace dg_fes(&mesh, &dg_fec);

   cout << "Number of H1 trace DOFs:     " << h1_fes.GetTrueVSize() << endl;
   cout << "Number of DG interface DOFs: " << dg_fes.GetTrueVSize() << endl;

   GridFunction h1_gf(&h1_fes), dg_gf(&dg_fes);
   h1_gf.Randomize(1);
   dg_gf = 0.0;

   int nf = mesh.GetNumFaces();
   Array<int> h1_dofs, dg_dofs;
   for (int f=0; f<nf; ++f)
   {
      // Maps from lexicographic (Cartesian) ordering to H1 ordering
      const int *h1_dofmap = h1_fec.GetDofMap(mesh.GetFaceBaseGeometry(f));

      h1_fes.GetFaceDofs(f, h1_dofs);
      dg_fes.GetFaceDofs(f, dg_dofs);
      MFEM_VERIFY(h1_dofs.Size() == dg_dofs.Size(), "");
      for (int i=0; i<h1_dofs.Size(); ++i)
      {
         dg_gf[dg_dofs[i]] = h1_gf[h1_dofs[h1_dofmap[i]]];
      }
   }

   return 0;
}
```

**Comment by bensworth** [comment]
Thanks @pazner, think this does what we need!
