### ISSUE TITLE
Generating higher order mesh.

### ISSUE THREAD

**Issue by Krishna-Dutt** [mfem/mfem#1993]
Do you have an example or a sample code to generate a higher-order mesh, for example, the quadratic triangular mesh given in square-disc-p2.vtk

**Comment by tzanio** [comment]
Hi @Krishna-Dutt,

The `square-disc-p2.vtk` mesh in particular was generated from the `square-disc.mesh` using the Mesh Explorer miniapp (`miniapps/meshing/mesh-explorer`) by giving it curvature (key `c`) and applying a random perturbation (key `j`). This miniapp can be used to define other simple high-order meshes e.g. by applying a transformation to a simple domain.

If you are looking for a more general high-order mesh generator, we currently support high-order meshes produced by Gmsh and Cubit.

Hope this helps,
Tzanio

**Comment by Krishna-Dutt** [comment]
Hi, 
Yes, that answers my question. Thanks!
