### ISSUE TITLE
Integration over the boundary in parallel

### ISSUE THREAD

**Issue by kolotinsky1998** [mfem/mfem#1996]
Hi, dear community!

I have a question about the postprocessing step. I have used MFEM to solve a 3D electromagnetic problem for a waveguide geometry #1972. Now I need to calculate S-parameters for this waveguide. For that purpose, I need to calculate the following integral over the waveguide port boundaries:

<img src="https://render.githubusercontent.com/render/math?math=\iint_{\delta\Omega_{port}} \sqrt{\overline{E}\cdot\overline{E}} \,d\delta\Omega">, <img src="https://render.githubusercontent.com/render/math?math=\overline{E}"> - obtained solotuion of Maxwell's equations for electric field, and <img src="https://render.githubusercontent.com/render/math?math=\delta\Omega_{port}"> - boundary of the port. 

I know how to calculate this boundary integral when <img src="https://render.githubusercontent.com/render/math?math=\overline{E}"> - is initial electric field on the waveguide port determined in mfem through a customized function. There is my code for that purpose and it works:

`InnerProductCoefficient E_imag_2(E_imag, E_imag)`  - <img src="https://render.githubusercontent.com/render/math?math=\overline{E}_{imag} \cdot \overline{E}_{imag}">

`InnerProductCoefficient E_real_2(E_real, E_real)`  - <img src="https://render.githubusercontent.com/render/math?math=\overline{E}_{real} \cdot \overline{E}_{real}">

`SumCoefficient E_imagreal_2(E_real_2, E_imag_2)`  - <img src="https://render.githubusercontent.com/render/math?math=\overline{E} \cdot \overline{E}">

`PowerCoefficient E_imagreal(E_imagreal_2, 0.5)` - <img src="https://render.githubusercontent.com/render/math?math=\sqrt{\overline{E} \cdot \overline{E}}">

`fec = new H1_FECollection(order, dim)`
`fespace = new ParFiniteElementSpace(pmesh, fec)`
`PartLinearForm In1(fespace); `

`In1.AddBoundaryIntegrator(new BoundaryLFIntegrator(E_imagreal), port);`
`In1.Assemble();`
`ParGridFunction ones(fespace);`
`ones = 1.`
`double in1 = In1(ones);` - <img src="https://render.githubusercontent.com/render/math?math=\iint_{\delta\Omega_{port}} \sqrt{\overline{E}\cdot\overline{E}} \,d\delta\Omega">

However, at this moment I use
`VectorFunctionCoefficient E_real(dim, port_exitate_real_custom_function);` - port_exitate_real_custom_function - defined custom function
`VectorFunctionCoefficient E_imag(dim, port_exitate_imag_custom_function);` - defined custom function

And I want to use ParGridFunction which are the image and real part of solution for my electromagnetic problem.

`a->RecoverFEMSolution(U, b, u);`
`E_real = u.real();` - ParGridFunction
`E_imag = u.imag();` - ParGridFunction

With that step I am confused. Could you help me with that issue?

Thank you in advance
Daniil

**Comment by sshiraiwa** [comment]
How about using GridFunctionCoefficient?

**Comment by kolotinsky1998** [comment]
I know how it works with GridFunction, but do not how with the ParGridFunction. Is it possible?

**Comment by kolotinsky1998** [comment]
I tried this:

`GridFunctionCoefficient E_imag(u.imag())` - u.imag - ParGridFunction
`GridFunctionCoefficient E_real(u.real())` - u.real - ParGridFunction

That gives an error during compilation.

**Comment by psocratis** [comment]
> I tried this:
> 
> `GridFunctionCoefficient E_imag(u.imag())` - u.imag - ParGridFunction
> `GridFunctionCoefficient E_real(u.real())` - u.real - ParGridFunction
> 
> That gives an error during compilation.

I believe you are missing a "&", i.e.,  `GridFunctionCoefficient E_real(&u.real())`. I also think you would need a `VectorGridFunctionCoefficient`.

Best, 

Socratis
