### ISSUE TITLE
GridFunction::ProjectBdrCoefficient for L2-space

### ISSUE THREAD

**Issue by robert-chiodi** [mfem/mfem#1997]
Hello,

I am trying to project a coefficient onto the boundary of a `GridFunction` defined for an L2 finite element space. My plan is to then use this grid function in a `GridFunctionCoefficient` to weakly enforce Dirichlet boundary conditions in my solver, where I can just update the underlying grid function and re-assemble my `LinearForm`. Currently, `ProjectBdrCoefficient` leads to a segfault when used for a `GridFunction` defined on a L2-space. I am very new to finite-element (and DG), so if I am trying to do something that makes no sense, please just let me know. 

I've been able to track the segfault to the method `void GridFunction::AccumulateAndCountBdrValues`, where it occurs due to `fdof = fe->GetDof();`, where `fe` is actually a `nullptr` returned via the previous line `fe = fes->GetBE(i);`. I noticed in the construction of `L2_FECollection`, `L2_Elements[Geometry::SEGMENT]` is indeed not set for dim != 1, so it makes sense that it would segfault. Ultimately, I guess my question is if the construction of the `L2_FECollection` should be using if statements like in the `H1_FECollection` where inclusion of segments is done for `if (dim >= 1)`, or if there is indeed a limitation for returning border elements in L2 spaces that I am not aware of.

In case this is something that might be worth adding, I have included a minimal example below as well, which uses the beam-quad.mesh from MFEM's data directory.

```
#include <mfem/mfem.hpp>

int main(void) {
  mfem::Mesh mesh("beam-quad.mesh", 1, 1);
  mfem::L2_FECollection fe_collection(2, 2);
  mfem::FiniteElementSpace fespace(&mesh, &fe_collection);

  mfem::GridFunction gf(&fespace);

  mfem::Array<int> bdr_marker(mesh.bdr_attributes.Size());
  bdr_marker = 0;
  bdr_marker[0] = 1;
  mfem::ConstantCoefficient one(1.0);
  gf.ProjectBdrCoefficient(one, bdr_marker);

  return 0;
}
```

**Comment by psocratis** [comment]
Hi @robert-chiodi , 

Let me just start by saying that the `ProjectBdrCoefficient` is designed to work for the `H1` space where the trace is mathematically well defined. For the `L2` space this is not the case. For an `L2` space you can weakly enforce Dirichlet boundary conditions using `DGDirichletLFIntegrator`. A simple example for DG diffusion with non-homogeneous Dirichlet BCs can be found here: https://github.com/mfem/mfem/blob/1155c003a8e8c6eeaa1287414db4f0df0c63748c/tests/convergence/rates.cpp#L192-L200

I hope this helps. 

Best, 
Socratis

**Comment by robert-chiodi** [comment]
Yes, it does, thank you very much. I have been really enjoying MFEM but still have much to learn!
