### ISSUE TITLE
Mesh size definition

### ISSUE THREAD

**Issue by raphaelzanella** [mfem/mfem#1998]
Hello,
I am using a triangular mesh defined with the "inline" format, with nx = ny = 10 and sx = sy = 1.0.
All triangles therefore have sides of length 0.1, 0.1 and sqrt(2)*0.1.
The pmesh.GetCharacteristics(h_min, h_max, kappa_min, kappa_max) command provides h_min = h_max = 0.107457 (if no mistake).
How is the mesh size defined?
Thank you.

**Comment by tzanio** [comment]
Hi @raphaelzanella,

This is a good question, and I agree that the output can be confusing.

First,  note that`Mesh::GetCharacteristics` provides a pretty simple estimate for the "element size" of each element and returns the min and max over the whole mesh. This estimate can certainly be improved depending on you needs.

Second, as you can see in https://github.com/mfem/mfem/blob/master/mesh/mesh.cpp#L212, the mesh size for each element is computed as the `det(J)^{1/dim}` where `J` is the Jacobian in the center of the element.

Third, this Jacobian corresponds to a mapping from a "perfect" reference element, i.e. equilateral triangle in your case, https://github.com/mfem/mfem/blob/master/mesh/mesh.cpp#L58.

Putting all of this together, for linear triangles in 2D, the formula for each element is `h = sqrt(A/Â)` where `A` is the area of the element while `Â` is the area of the reference element. In your case `A = 0.005`, `Â = sqrt(3)/4 = 0.4330127019` and `h = sqrt(0.02/sqrt(3)) = 0.1074569932`.

Hope this helps.
Tzanio

**Comment by raphaelzanella** [comment]
It helps, thank you. I was missing missing the info that the reference element is equilateral.

**Comment by tzanio** [comment]
Ok, then I'll close this issue. Feel free to reopen if you have further questions.
