### ISSUE TITLE
winsock usage

### ISSUE THREAD

**Issue by wo80** [mfem/mfem#2000]
Before using any winsock functions, `WSAStartup` has to be called:
https://docs.microsoft.com/en-us/windows/win32/api/winsock/nf-winsock-wsastartup

Adding the following code to [socketstream.cpp](https://github.com/mfem/mfem/blob/master/general/socketstream.cpp#L58) solved the problem for me:
```c
int socketbuf::open(const char hostname[], int port)
{
   // ...
#ifdef _WIN32
   WSADATA wsaData;
   WSAStartup(MAKEWORD(2, 2), &wsaData);
#endif
   hp = gethostbyname(hostname); // <- will always be null without WSAStartup
   if (hp == NULL)
   // ...
}
```

EDIT: calling `WSAStartup` in the constructor and `WSACleanup` in the destructor of the `socketstream` class would be cleaner .

**Comment by wo80** [comment]
Some additional thoughts:

When running the examples I was suprised that my server didn't receive any data and adding the above code to `socketbuf::open` was a quick fix for all examples. In general, it's the responsibility of the calling process to call `WSAStartup` and `WSACleanup`, so I think this not a bug of MFEM and the fix should probably be applied to the examples code.

**Comment by tzanio** [comment]
Thanks for reporting this and suggesting a fix @wo80.

We don't usually run on Windows, so this is very useful. Can you tell us more about how you build and run mfem (and glvis)?

**Comment by wo80** [comment]
Using cmake to build mfem works without any problems in Visual Studio (both serial and MPI).

Building glvis is rather painful. I had to edit both the cmake generated project files and some source code. Additionally, I had to disable all `multi_session` code path, since I'm not sure how to replace `fork()` on a Windows platform. This leads to the glvis server hanging after receiving mesh data, so it's not really useful.

But I've written my own visualization server in C# using [OpenTK](https://github.com/opentk/opentk). It's very limited (only 2D) but works well for me.

**Comment by tzanio** [comment]
Thanks for the details.

What do you think will be the best solution? 

Is there any downside to put `WSAStartup` and `WSACleanup` in the constructor and destructor of `socketstream`?

Or should we just document this for the users?

**Comment by wo80** [comment]
Putting the code into `socketstream` will work, but is problably not the way it's supposed to be used and might have an impact on performance:
https://stackoverflow.com/questions/396484/what-is-the-cost-of-wsastartup-and-wsacleanup

So, since glvis isn't an option for Windows users anyway, I'd suggest to just add some documentation (maybe to the **Building MFEM** page) telling that the cmake build works fine on Windows (and the recent version of Visual Studio), but if sockets are used, the user is responsible to initialize the winsock2 dll using the above code.

Feel free to close this issue.

**Comment by kanye-quest** [comment]
Hi @wo80, can you check that #2009 fixes the issue?

**Comment by wo80** [comment]
@kanye-quest Yes, neat solution!

**Comment by tzanio** [comment]
@kanye-quest, do you want to mark #2009 as `ready-for-review`?

**Comment by tzanio** [comment]
Discussion continued in #2009.
