### ISSUE TITLE
VTK reader

### ISSUE THREAD

**Issue by wcdawn** [mfem/mfem#2001]
There are a couple errors with the VTK reader. These are all with the ASCII VTK format.

1. The ASCII format should allow arbitrary blank lines but if there is a blank line after `ASCII` (i.e. if line 4 is blank), the reader crashes and an error is thrown.
```
MFEM abort: VTK mesh is not UNSTRUCTURED_GRID!
 ... in function: void mfem::Mesh::ReadVTKMesh(std::istream&, int&, int&, bool&)
 ... in file: /home/wcdawn/work/microreactor/mfem/mesh/mesh_readers.cpp:400
```

2. The `CELL_DATA` array `material` **must** be the first array on the file. If any `POINT_DATA` or other `CELL_DATA` arrays are specified, the material is treated as homogeneous. The VTK reader should simply skip over any other arrays besides the `material` array.

I realize this may not be a much used feature but it would be nice to have these bugs fixed. I can provide an example VTK if that would help.

**Comment by wcdawn** [comment]
I've proposed an initial fix to this in PR #2028. I'm open to other fixes as well.
Thanks!

**Comment by tzanio** [comment]
@mlstowell, @pazner and @bslazarov -- what do you think about #2028? Should we start a formal review for it?

**Comment by pazner** [comment]
> @mlstowell, @pazner and @bslazarov -- what do you think about #2028? Should we start a formal review for it?

Yes, I took a quick look and it looks good to me. Let's review it.

**Comment by tzanio** [comment]
Discussion continued in @2028.
