### ISSUE TITLE
Warning: overloaded virtual function

### ISSUE THREAD

**Issue by adam-sim-dev** [mfem/mfem#2003]
fem/bilininteg.cpp(3679): warning: overloaded virtual function "mfem::VectorCoefficient::Eval" is only partially overridden in class "VCrossVShapeCoefficient"

**Comment by tzanio** [comment]
This should be resolved by adding 

```c++
using VectorCoefficient::Eval;
```

as done in a few other places in the code. We have not seen that warning in our tests... can you provide more details on your platform, compiler, etc?

**Comment by tzanio** [comment]
Thank you @adam-sim-dev.

Can you check if https://github.com/mfem/mfem/tree/2003-fix fixes the issue for you?

**Comment by adam-sim-dev** [comment]
@tzanio , 2003-fix branch fixes the warning. The other two warnings are:

fem/bilininteg_diffusion_pa.cpp(1554): warning #125: expected a "("
  #pragma unroll MD1
                 ^
fem/bilininteg_mass_pa.cpp(942): warning #125: expected a "("
  #pragma unroll MD1
                 ^

**Comment by tzanio** [comment]
@camierjs, have you seen this error?

**Comment by tzanio** [comment]
Hi @adam-sim-dev,

I pushed a change in `2003-fix` can you try it again>

Tzanio

**Comment by adam-sim-dev** [comment]
Hi @tzanio , I can confirm that the new commit silences the warnings.

Adam

**Comment by tzanio** [comment]
Thanks, see https://github.com/mfem/mfem/pull/2012
