### ISSUE TITLE
Eliminate rows and cols with diagonal zero

### ISSUE THREAD

**Issue by tangqi** [mfem/mfem#2004]
Is there a function for HypreParMatrix to eliminate the essential boundary condition but set the diagonal to zero?

I use `HypreParMatrix::EliminateRowsCols` but it gives me diagonal of 1. The matrix I have is through ParMult and ParAdd, so I cannot use `DIAG_ZERO` in bilinearform. The matrix appears as an off-diagonal block matrix in a block system, which is why I hope I can eliminate it to zero. There is an `EliminateRowsCols` in `PetscParMatrix` but it does not support `MATNEST`, so I have to do it in mfem before passing it to petsc.

The equation for the essential boundary condition is redundant, so I believe in principle setting the off-diagonal entries to 0 or 1 should not matter. But it will be good if there is a simple solution. Thanks

Qi

**Comment by jandrej** [comment]
Do you need the functionality of the modified RHS? If not you could use `hypre_CSRMatrixEliminateRowsCols` directly with `diag = 0`.

**Comment by tangqi** [comment]
Thanks. I do not need the modified RHS. I also do not need the `Ae` matrix. 

To use  `hypre_CSRMatrixEliminateRowsCols` properly, should I modify `hypre_ParCSRMatrixEliminateAAe`? It looks like I can simply replace `diag=0` in the place calling `hypre_ParCSRMatrixEliminateAAe`

**Comment by jandrej** [comment]
I would call `hypre_CSRMatrixEliminateRowsCols` with the `diag` argument set to `0` and then deleting the pointer you get for `Ae`.

**Comment by tzanio** [comment]
Let me add that we do have an enum to describe how to handle the diagonal during elimination called `DiagonalPolicy` in the `Operator` class:

```c++
/// Defines operator diagonal policy upon elimination of rows and/or columns.
enum DiagonalPolicy
{
   DIAG_ZERO, ///< Set the diagonal value to zero
   DIAG_ONE,  ///< Set the diagonal value to one
   DIAG_KEEP  ///< Keep the diagonal value
};
```
This can be specified for example in `SparseMatrix::EliminateRowCol` and `BilinearForm::EliminateEssentialBC`.

**Comment by tangqi** [comment]
That's the part I was confused about. I read `HypreParMatrix::EliminateRowsCols`, and it calls `hypre_ParCSRMatrixEliminateAAe`, which only works to set diag being 1. I could not find a function to set diag 0. I guess the `DiagonalPolicy` only works before `HypreParMatrix` is formed?

The matrix I am trying to eliminate is defined as A+N*M^{-1}*K, which are all HypreParMatrix. It looks like I have to modify `hypre_ParCSRMatrixEliminateAAe`, unless I misunderstood @jandrej

**Comment by jandrej** [comment]
There are two version you are talking about here. One is `HypreParMatrix::EliminateRowsCols` and I recommended the internal version `hypre_CSRMatrixEliminateRowsCols`.

**Comment by tangqi** [comment]
Yes, `hypre_CSRMatrixEliminateRowsCols` is the one I thought I should use. But the only place I found to use `hypre_CSRMatrixEliminateRowsCols` is in `hypre_ParCSRMatrixEliminateAAe`, which is a bit confusing to me since it needs to create the proper Ae matrix and then eliminate. So I was thinking to replace that diag by 1 in those places and delete Ae afterwards. Let me know if there is a simpler way to use `hypre_CSRMatrixEliminateRowsCols`

**Comment by tangqi** [comment]
It works well. thanks
