### ISSUE TITLE
HYPRE_Int needed in hypre.hpp/hypre.cpp

### ISSUE THREAD

**Issue by robert-chiodi** [mfem/mfem#2006]
Hi all,

I believe I have found two locations in the current master branch that currently use `int` but should use `HYPRE_Int`. These are:

hypre.hpp - line 1280/1281: Call to function should use `HYPRE_Int`, as in the similar `HyprePCG::GetNumIterations`
hypre.cpp - line 1002: `CF_marker` should be of type `Array<HYPRE_Int>`

This is using the current hypre master branch, commit 2186a8fb343f84f109405eed3e298cb1a2615e95.
I believe it was introduced by mfem #1053 .

Hope this helps

**Comment by tzanio** [comment]
Thanks for reporting this @robert-chiodi!

Do you mind proposing a simple PR to fix it?

Tzanio

**Comment by robert-chiodi** [comment]
Not at all! I will get one posted in the next day or two and reference it here.

**Comment by tzanio** [comment]
Thanks!

**Comment by robert-chiodi** [comment]
Hi @tzanio ,

I have made the fixes following [CONTRIBUTING.md](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md), but I am not sure I have adequate permissions to push the new branch to mfem to create the pull-request. Should I just go ahead and do one from a fork of the code?

Thanks

**Comment by tzanio** [comment]
Can you try now?

**Comment by robert-chiodi** [comment]
Yep, that seemed to do the trick! Pull-request #2015 should implement the small changes necessary to fix this issue.

**Comment by tzanio** [comment]
Thanks!

**Comment by tzanio** [comment]
Discussion continued in #2015.
