### ISSUE TITLE
Local Time Stepping

### ISSUE THREAD

**Issue by lmdiazangulo** [mfem/mfem#2007]
FIrst of all, congratulations for the awesome work that you are doing, I wish that I had this tool some years ago when I started my PhD. 

My question: Does MFEM support any form of local time stepping to advance the explicit linear systems? I have checked the documentation and examples but I could not find any.

Thanks for your great work!

**Comment by tzanio** [comment]
Hi @lmdiazangulo,

There is currently no explicit support for local time stepping in the MFEM releases.

In principle all the tools are there, so maybe someone in the community has implemented it for their application...

Tzanio
