### ISSUE TITLE
About ex2p

### ISSUE THREAD

**Issue by nghiakvnvsd** [mfem/mfem#2013]
Hi everyone! I'm using MFEM. When I learn the ex2p, I have a problem that I cannot resolve this myself.
I want to apply a force vector only one node
eg:
 
![image](https://user-images.githubusercontent.com/68639058/105690459-619a1b80-5f3f-11eb-85a6-4b9710c41efe.png)

I want to apply the force vector at the last node (y-axis)

How can I change the code ex2p? If you have the code to resolve this, I really appreciate that. Thank you very much !!!

**Comment by tzanio** [comment]
Hi @nghiakvnvsd,

Does the following version of Example 2 work for you?

[ex2p.cpp.txt](https://github.com/mfem/mfem/files/5882433/ex2p.cpp.txt) (rename to `ex2p.cpp`)

You need to run it with this mesh 

[beam-quad-4attr.mesh.txt](https://github.com/mfem/mfem/files/5882436/beam-quad-4attr.mesh.txt) (rename to `beam-quad-4attr.mesh)

which has 4 boundary attributes so we can identify the corner as the intersection of two of them.

Hope this helps,
Tzanio

**Comment by nghiakvnvsd** [comment]
> Hi @nghiakvnvsd,
> 
> Does the following version of Example 2 work for you?
> 
> [ex2p.cpp.txt](https://github.com/mfem/mfem/files/5882433/ex2p.cpp.txt) (rename to `ex2p.cpp`)
> 
> You need to run it with this mesh
> 
> [beam-quad-4attr.mesh.txt](https://github.com/mfem/mfem/files/5882436/beam-quad-4attr.mesh.txt) (rename to `beam-quad-4attr.mesh)
> 
> which has 4 boundary attributes so we can identify the corner as the intersection of two of them.
> 
> Hope this helps,
> Tzanio

Thank you very much for your help. It worked for me. But that does seem depend on the intersection of 2 boundary attributes. Assume that I have the model (MBB beam). 

![image](https://user-images.githubusercontent.com/68639058/106092556-dd7baa00-6171-11eb-9d07-46a418844585.png)

Can I divide the model like it

![image](https://user-images.githubusercontent.com/68639058/106092895-97731600-6172-11eb-8f5e-599a62c69958.png)

the force vector is the intersection of attr 3 and 5? or 4 and 5?

**Comment by tzanio** [comment]
Yes, you can divide it that way.

For that problem you don't need a vertical attribute 5, and the whole bottom can be one attribute, say 6.

You will have the force vector on the intersection of attr 3 and 5.

**Comment by nghiakvnvsd** [comment]
Hi @tzanio  Thank you for your advice. Sorry to bother you again. I have a question that I also have not resolve it. 

My project seem like:

```
....
while (...){
  ...
  Vector lambda(pmesh->attributes.Max());
   lambda = 1.0;
   lambda(0) = lambda(1)*50;
   PWConstCoefficient lambda_func(lambda);
   Vector mu(pmesh->attributes.Max());
   mu = 1.0;
   mu(0) = mu(1)*50;
   PWConstCoefficient mu_func(mu);

   ParBilinearForm *a = new ParBilinearForm(fespace);
   a->AddDomainIntegrator(new ElasticityIntegrator(lambda_func, mu_func));

....
 
 **update lambda and mu**
....
}
```
I want to update mu and lambda parrallely after each iteration but I dont know how to update, because the algorithm metis give me a way divide the mesh that I cannot understand. May you recommend me that way to update lambda and mu? Thank you very much!

**Comment by tzanio** [comment]
If `lambda` and `mu` continue to be piecewise-constant functions over the same mesh attributes (and just their values in each attribute change) then there should be no issues with just using the new values when defining `lambda_func` anf `mu_func`.

**Comment by nghiakvnvsd** [comment]
> If `lambda` and `mu` continue to be piecewise-constant functions over the same mesh attributes (and just their values in each attribute change) then there should be no issues with just using the new values when defining `lambda_func` anf `mu_func`.

I mean, after each interations, lambda and mu are changed based on each processor. For examples, I have the mesh rectangle 20*10, each element I define one lambda and one mu => pmesh->attributes.Max() = 200, Vector lambda and mu have 200 components. When I run the while loop, I want to change the vector lambda and mu. Each processor, some of components of lambda and mu are changed. If I want to change like it, I have to know relationship between dof (not parallel) and dof (parallel). Currently to solve this problem. I don't implement metis to segment the meshes. I am doing by hand to segment the parallel mesh. But that's not really optimal (I think).

**Comment by tzanio** [comment]
Hi @nghiakvnvsd,

If lambda and mu are piecewise-constant (i.e. a constant on each element) the relationship between parallel and serial dofs is just the identity.

Otherwise, you should have both a parallel vector and a local grid function for each of them, e.g. `Lambda` and `lambda` and in that case the relationship is (see https://mfem.org/pri-dual-vec/)

```c++
lambda = Lambda; // scatter parallel -> local
lambda.ParallelAverage(Lambda) // gather local -> parallel
```

Hope this helps.
Tzanio
