### ISSUE TITLE
CUDA Error

### ISSUE THREAD

**Issue by wcdawn** [mfem/mfem#2026]
I'm trying to use CUDA to solve my problem and get the following errors on my terminal
```
 ** On entry to cusparseSpMV_bufferSize() parameter number 1 (handle) had an illegal value: NULL pointer

 ** On entry to cusparseSpMV() parameter number 1 (handle) had an illegal value: NULL pointer

```

I've traced it back to something happening in `ParBilinearForm::FormLinearSystem()` but I'm not sure where else to look.

**Comment by tzanio** [comment]
@wcdawn can you provide more details about your code?

Is it based on one of the examples? What assembly level you are using? What device, cuda?

**Comment by wcdawn** [comment]
Sorry for the missing details. It is similar to `ex1` (diffusion-like) but I cannot recreate this error using `ex1`. I am using the cuda device and the default assembly level. I am using CUDA v11.2. I'm trying to further narrow down why this is happening.

**Comment by artv3** [comment]
It sounds like the sparse matrix didn't get formed and a null pointer is being passed into the CUSparse methods. Could you post the backtrace?

**Comment by wcdawn** [comment]
I don't know why, but the program itself doesn't crash and actually converges to the correct solution. Maybe it falls back to the CPU code? As such, there is no backtrace.

**Comment by wcdawn** [comment]
The error is actually raised during `mfem::SparseMatrix::Mult()`. It's called with the restriction matrix [here](https://github.com/mfem/mfem/blob/08b339303b11b98a1aa3db5e04369a6405d4ca5a/fem/pbilinearform.cpp#L342).

**Comment by wcdawn** [comment]
I found the error! It was my fault but I think there may be a change to make to help with the headache in the future. I had created some `SparseMatrix` before setting up the device so they were generated for the CPU. Currently, if the first `SparseMatrix` is not setup for CUDA, no subsequent matrices will be CUDA enabled.

I propose changing [this](https://github.com/mfem/mfem/blob/08b339303b11b98a1aa3db5e04369a6405d4ca5a/linalg/sparsemat.cpp#L43):
```cpp
   if (SparseMatrixCount == 1 && Device::Allows(Backend::CUDA_MASK))
   {
      cusparseCreate(&handle);
   }
```
to this
```cpp
   if (!handle && Device::Allows(Backend::CUDA_MASK))
   {
      cusparseCreate(&handle);
   }
```

While this would fix my problem, it would also allow others to make a similar mistake in the future of having some `SparseMatrix` on CPU and some on CUDA. I understand why this would be undesirable for some.

I can create a PR for this change if desired.
Thanks!

**Comment by YohannDudouit** [comment]
Hi @wcdawn,
I'm glad you found your bug and thank you for your suggestion. I like your suggestion and I think we could completely remove the `SparseMatrixCount` variable in the same time. Would you be interested to propose a short PR to resolve this issue?
However, in general I think we expect users to set the device with `Device device(device_config);` at the beginning of a MFEM code (@v-dobrev correct me if I'm wrong).

**Comment by wcdawn** [comment]
I created a PR for this (#2031) but I don't think we can remove `SparseMatrixCount` entirely. It is used in the destructor to see if this is the last `SparseMatrix` instance and if the CUDA handle can be deleted.

I agree users should set the device at the beginning, but an error message may be better than a null pointer error in that case.

**Comment by artv3** [comment]
An alternative to the matrix count could be to use ``std::atexit``

**Comment by YohannDudouit** [comment]
Hi @wcdawn ,

We talked about your issue today and were wondering how this problem came up. As I was mentioning we expect users to initialize the `Device` at the beginning of their code, was there a specific reason why you decided to initialize it later in your code?

Thank you,

**Comment by wcdawn** [comment]
Not particularly. I was able to reorder things to use the expected method.

The reason it arose is that I have a lot of input so it is read from an external input file. The user can specify the device in the input file so this means that the first thing done while parsing input must be to set the device.

An alternate option to prevent things like this in the future would be something like
```cpp
   if (!handle && SparseMatrixCount > 1 && Device::Allows(Backend::CUDA_MASK))
   {
      MFEM_ABORT(/* ... */);
   }
```

**Comment by YohannDudouit** [comment]
If you were to initialize the `Device` at the beginning of your code, would the issue still have showed up? Would there have been any performance issue? (I am trying to figure out if there is legitimate reason to not initialize the `Device` at the beginning of your code)

**Comment by wcdawn** [comment]
No, then this issue would not show up. I was able to reorder my code to get it to work on `master` with no changes necessary. The only reason I was doing it in a different order was because I had not yet parsed the input file at that point in the code. After reordering, everything works fine.

**Comment by YohannDudouit** [comment]
Thank you for the clarification, we will still review your PR as it is an improvement over the current code. I will close this issue but feel free to reopen it if you need.
