### ISSUE TITLE
Question: XFEM Implementation for Fissure Initiation and Propagation

### ISSUE THREAD

**Issue by bkolade** [mfem/mfem#203]
Is there an implementation of XFEM within the MFEM library? Is there any good reference for a project that adapted the MFEM library for fissure initiation and propagation simulation? I am interested in developing a geomechanics-hydrodynamics simulation tool.

Thanks,

**Comment by tzanio** [comment]
Hi @bkolade, unfortunately there is no XFEM capability currently in MFEM. Some of our applications are interested in it, so this may change in the future.
