### ISSUE TITLE
Segmentation Fault while using HypreParMatrix::Threshold() function.

### ISSUE THREAD

**Issue by Jxt1** [mfem/mfem#2036]
My code is:
```c++
int main(int argc, char *argv[]) {
   int order = 1;
   MPI_Session mpi(argc, argv);
   Mesh *mesh = new Mesh("square_tri.mesh");
   auto *pmesh = new ParMesh(MPI_COMM_WORLD, *mesh);
   Array<int> empty;
   FiniteElementCollection* fec = new H1_FECollection(order);
   ParFiniteElementSpace* fes = new ParFiniteElementSpace(pmesh, fec);

   OperatorHandle Mmat;
   ParBilinearForm M(fes);
   M.AddDomainIntegrator(new MassIntegrator());
   M.Assemble();
   M.Finalize();
   M.FormSystemMatrix(empty, Mmat);
   Mmat.As<HypreParMatrix>()->Threshold(1e-10);

   return 0;
}
```

The mesh file is:
```
MFEM mesh v1.0

dimension
2

elements
2
1 2 0 1 2
1 2 0 2 3

boundary
4
1 1 0 3
3 1 0 1
3 1 2 3
2 1 1 2

vertices
4
2
0 0
1 0
1 1
0 1

```

The error occurs in calling *GenerateDiagAndOffd* function, when variable *csr_A_wo_z* is *nullptr*.

**Comment by tzanio** [comment]
I can reproduce by just adding

```c++
   A.As<HypreParMatrix>()->Threshold(1e-24);
```

after the call to `FormLinearSystem` in Example 1p.

@barker29, if I recall correctly you had issues with `Threshold` in the past, have you used it recently?

**Comment by tzanio** [comment]
@Jxt1, with the latest `mfem:master` and hypre v2.14 or higher, you can replace `Threshold` with `DropSmallEntries`, which is the prefered function in the future.

**Comment by Jxt1** [comment]
Thanks for your help. I will try replace `Threshold` with `DropSmallEntries`.

**Comment by adrienbernede** [comment]
@Jxt1 did that work for you?

**Comment by Jxt1** [comment]
It works well in my program. Thanks a lot.

**Comment by adrienbernede** [comment]
You are welcome!
