### ISSUE TITLE
Impose a weak Dirichlet condition

### ISSUE THREAD

**Issue by L29430** [mfem/mfem#2039]
Hello !

I'm solving a Laplace/Poisson equation, I would like to know if it's possible to impose weakly a Dirichlet boundary condition on a wall of my domain, as for example, with a Nitsche formulation ?

Kind regards, 

LS

**Comment by vladotomov** [comment]
See https://github.com/mfem/mfem/issues/1912#issuecomment-741111083

**Comment by L29430** [comment]
Thank you for your answer, do you know Nitsche's formulation for weakly imposing a Dirichlet condition? It's currently this formulation that I wanted to code.

**Comment by vladotomov** [comment]
Yes, you can find an MFEM implementation of the Nitsche's method in `miniapps/nurbs/nurbs_ex1.cpp`.

**Comment by L29430** [comment]
Thank you !!

If I understood correctly : For the Nitsche's method, I need **DGDirichletLFIntegrator** for the linear form and **DGDiffusionIntegrator** for the bilinear form ?

I use H1_FECollection as finite element space to solve the equations, is it a problem with  **DGDirichletLFIntegrator** and **DGDiffusionIntegrator** ?

Another question, what is Diffusion2Integrator ? I'm not sure I understood.

**Comment by vladotomov** [comment]
Yes, I believe in this case `DGDirichletLFIntegrator` and `DGDiffusionIntegrator` will work with `H1`. They are only added on the boundary faces, so the assumption is that they are only active on one side of the faces.

`Diffusion2Integrator` is not part of the library, but some custom integrator only defined in this example. It doesn't integrate the Laplace term by parts.
