### ISSUE TITLE
First second order time derivative

### ISSUE THREAD

**Issue by AFourmont** [mfem/mfem#2042]
Dear mfem developers,
I want solve a pde involving first and second order time derivative terms, typically of the form 
<a href="https://www.codecogs.com/eqnedit.php?latex=\alpha&space;\frac{\partial^2}{\partial&space;t^2}&space;u&plus;&space;\beta&space;\frac{\partial}{\partial&space;t}&space;u&plus;&space;\gamma&space;u&space;&plus;&space;\epsilon&space;\Delta&space;u&space;&plus;&space;\zeta&space;\frac{\partial&space;}{\partial&space;t}&space;\Delta&space;u&space;=&space;f&space;\text&space;{&space;;&space;with&space;}&space;\alpha,&space;\beta,&space;\gamma,&space;\epsilon,&space;\zeta&space;\in&space;\mathbb{R}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\alpha&space;\frac{\partial^2}{\partial&space;t^2}&space;u&plus;&space;\beta&space;\frac{\partial}{\partial&space;t}&space;u&plus;&space;\gamma&space;u&space;&plus;&space;\epsilon&space;\Delta&space;u&space;&plus;&space;\zeta&space;\frac{\partial&space;}{\partial&space;t}&space;\Delta&space;u&space;=&space;f&space;\text&space;{&space;;&space;with&space;}&space;\alpha,&space;\beta,&space;\gamma,&space;\epsilon,&space;\zeta&space;\in&space;\mathbb{R}" title="\alpha \frac{\partial^2}{\partial t^2} u+ \beta \frac{\partial}{\partial t} u+ \gamma u + \epsilon \Delta u + \zeta \frac{\partial }{\partial t} \Delta u = f \text { ; with } \alpha, \beta, \gamma, \epsilon, \zeta \in \mathbb{R}" /></a>

I followed the different examples, I consulted mfem methods for the first order and second order time derivatives. Do you have an mfem method to solve this kind of problem with mixed first and second order terms?

Thank you for your help.

Best regards,
Axel

**Comment by pguthrey** [comment]
What temporal discretization did you have in mind?  Can you recast your equation as a first order system?

**Comment by pguthrey** [comment]
Also I'd be willing to bet you'll need different solvers for different regions of your parameter space...

**Comment by cjvogl** [comment]
I would also be interested in the answers to @pguthrey's questions.  My first inclination is, as I believe @pguthrey is suggesting, introduce an auxiliary variable like v = du/dt to obtain the first-order system (and detangle the time and space derivatives):
du/dt - v = 0
\alpha dv/dt + \beta v + \gamma u + \epsilon \Delta u + \zeta \Delta v = f
assuming things are smooth enough for (d/dt) \Delta u = \Delta (d/dt) u.  Would that work for your application?
