### ISSUE TITLE
Mesh Explorer miniapp attribute inconsistency

### ISSUE THREAD

**Issue by termi-official** [mfem/mfem#2062]
Hi together,

I found an inconsistency in the mesh explorer when running the mesh explorer "serial", i.e. via
```bash
miniapps/meshing/mesh-explorer -m mesh
```
then "m" shows the actual attributes. However, if we run it in "parallel", i.e. via
```
miniapps/meshing/mesh-explorer -np 16 -m mesh
```
then for "m" instead of the attributes the partitioning is presented, which is also a nice to have, but we cannot actually check for attributes with the miniapp anymore.

**Comment by v-dobrev** [comment]
Thanks for reporting the issue. It should be easy to fix with a command-line option that allows you to specify if you want attributes based on the rank, see here: https://github.com/mfem/mfem/blob/3c407ebf79fc16a2977a48fceee41b44cce74dc6/miniapps/meshing/mesh-explorer.cpp#L120-L130

In GLVis, we have already have a command-line option for this: https://github.com/GLVis/glvis/blob/50013926aeee14364e742a5a38a303f6c2ddde16/glvis.cpp#L946-L949

**Comment by tzanio** [comment]
@termi-official, are you interested in proposing a fix for this?

**Comment by termi-official** [comment]
Sure, I can do this, but this may take a bit time, because I currently have not time to implement stuff due to upcoming deadlines. 

My proposal would be to introduce a new menu item "show partitioning" if we start with the parallel option and refactor the code accordingly, because I think it is nice to have both available.

**Comment by tzanio** [comment]
Discussion continued in #2081.
