### ISSUE TITLE
Higher Order Meshing Results (Example 2)

### ISSUE THREAD

**Issue by jhoy97** [mfem/mfem#2063]
Hi there, I am completing a 2D convergence study for example 2 and am using 3 sample meshes; coarse (45 elements), medium (1002 elements)  fine (1724 elements).  I have created the mesh in Gmsh and have therefore commented out (//) section 4 of ex2.cpp.  I am trying each mesh with increasing order from 1-5 and have encountered a problem for the finer meshes at a high order. 
When testing the medium mesh, order 1-4 showed converging results (ideal answer is 0.375) and order 5 was showing this:
![Order 5](https://user-images.githubusercontent.com/78260282/108704129-77313f80-7503-11eb-92df-9cf265dbc314.jpg)
 
Why is this answer so small? 
Is the mesh too fine for the higher order equations?  
When testing the fine mesh I could only get accurate results for order 1-3.
I can send in the .msh files or the ex2.cpp files if needed.

Any help would be great. Thanks!

**Comment by tzanio** [comment]
Did the linear solve converge for the larger problems?

The serial version, `ex2.cpp` does only 500 iterations with diagonal preconditioner. Try using the parallel version, `ex2p.cpp` (even on 1 MPI rank) which has much more robust AMG preconditioner.

**Comment by jhoy97** [comment]
Here are my results for the max deflection. The ideal value is 0.375. I used 3 meshes; coarse, medium and fine and used 5 orders to get results for the convergence study. For mesh 1 (coarse mesh, t1.msh) the answers converge with increasing order.  For mesh 2 (medium) the first four orders get very close to the answer but then the deflection becomes 0.04456 for order 5. The first 3 orders for the fine mesh are converging then order 4 and 5 are very small.
![Inital results](https://user-images.githubusercontent.com/78260282/109140889-fe292680-7754-11eb-9921-658c491161de.jpg)

I tried running the parallel version, ex2p.cpp and this error report came up when I tried to make ./ex2p:
![Error report 1](https://user-images.githubusercontent.com/78260282/109141284-7abc0500-7755-11eb-9324-35f45597fd89.jpg)
![Error report 2](https://user-images.githubusercontent.com/78260282/109141287-7b549b80-7755-11eb-846d-3afc6aef64ed.jpg)

**Comment by tzanio** [comment]
I think it is very likely that the high-resolution serial results are not converged. You can increase the number of PCG iterations (from the default 500) to check that.

For the parallel version you need to rebuild mfem with `make parallel`, see https://mfem.org/building/#parallel-mpi-version-of-mfem
