### ISSUE TITLE
Building Parallel Version, Directory paths

### ISSUE THREAD

**Issue by jhoy97** [mfem/mfem#2067]
Hi,

When downloading the parallel version of mfem I have encountered this error.

```
~/Desktop/MFEM NEW/mfem-4.2$ make parallel -j
make -f makefile config MFEM_USE_MPI=YES MFEM_DEBUG=NO \
   
make[1]: Entering directory '/home/osboxes/Desktop/MFEM NEW/mfem-4.2'
make -C config all
make[2]: Entering directory '/home/osboxes/Desktop/MFEM NEW/mfem-4.2/config'
mpicxx -I../../hypre-2.20.0/include get_hypre_version.cpp -o get_hypre_version
get_hypre_version.cpp:12:10: fatal error: HYPRE_config.h: No such file or directory
   12 | #include "HYPRE_config.h"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [makefile:48: get_hypre_version] Error 1
make[2]: Leaving directory '/home/osboxes/Desktop/MFEM NEW/mfem-4.2/config'
make[1]: *** [makefile:594: local-config] Error 2
make[1]: Leaving directory '/home/osboxes/Desktop/MFEM NEW/mfem-4.2'
make: *** [makefile:470: parallel] Error 2
```

I seen in the install file that I had to change my path to the hypre relative to mfem in defaults.mk but I am unsure as to what to change the HYPRE_DIR variable to as both hypre and mfem are in the same directory.

![directory](https://user-images.githubusercontent.com/78260282/109172962-3ba0aa80-777b-11eb-984e-9dd2d0aa8697.jpg)

Any help would be great!

**Comment by jakubcerveny** [comment]
Try creating a symbolic link to your hypre directory: `ln -s hypre-2.20.0/ hypre`

**Comment by jhoy97** [comment]
I thought the second folder from the left was the symbolic link created when following the parallel building instructions.  I tried changing the defaults.mk file 

`> HYPRE_DIR = @MFEM_DIR@/../hypre/src/HYPRE_config.h`

which got rid of the initial error but gave me this one instead 

![cc1](https://user-images.githubusercontent.com/78260282/109176197-78ba6c00-777e-11eb-884b-2c338a592d26.jpg)

**Comment by jakubcerveny** [comment]
Oops, sorry, I overlooked that you already had the link...

**Comment by jakubcerveny** [comment]
`HYPRE_DIR` should be a directory, not a path to the config, IMO. I tried downloading, unpacking and building all the tarballs, and it seems to work for me. My directory with metis, hypre and mfem looks like this:
```
jakub@aorus ~/tmp/mfem-build $ ll
total 12
lrwxrwxrwx  1 jakub jakub   13 Feb 25 16:55 hypre -> hypre-2.20.0/
drwxrwxr-x  4 jakub jakub 4096 Sep 24 19:56 hypre-2.20.0
lrwxrwxrwx  1 jakub jakub   12 Feb 25 16:56 metis-4.0 -> metis-4.0.3/
drwxrwxr-x  7 jakub jakub 4096 Feb 25 16:57 metis-4.0.3
drwx--x--x 14 jakub jakub 4096 Feb 25 16:58 mfem-4.2
```
I'm wondering if the space in your path (`MFEM NEW`) could be causing trouble somewhere in the makefile. What happens if you rename the directory to `MFEM-NEW`?

**Comment by jakubcerveny** [comment]
I see a difference: after running `make parallel` you have:
```
mpicxx -I../../hypre-2.20.0/include get_hypre_version.cpp -o get_hypre_version
```
and I have
```
mpicxx -I../../hypre/src/hypre/include get_hypre_version.cpp -o get_hypre_version
```
Somehow you're missing the "src", what is your `HYPRE_DIR`?

**Comment by jhoy97** [comment]
`HYPRE_DIR = @MFEM_DIR@/../hypre/src/HYPRE_config.h` is my HYPRE_DIR in defaults.mk

**Comment by tzanio** [comment]
These days it probably doesn't matter, but I will avoid using directory names with spaces with them.

`HYPRE_DIR` should be ideally `../hypre`

**Comment by jhoy97** [comment]
Ok, took out the spaces in the directory name, also changed `HYPRE_DIR =  ../hypre` but still error message:
![cc2](https://user-images.githubusercontent.com/78260282/109184274-bae7ab80-7786-11eb-9e29-5e71d181d301.jpg)

**Comment by jakubcerveny** [comment]
This is the default from the tarball, can you please try that:
`HYPRE_DIR = @MFEM_DIR@/../hypre/src/hypre`

**Comment by jhoy97** [comment]
That was the original code in the file, when changed back to `HYPRE_DIR = @MFEM_DIR@/../hypre/src/hypre` it is giving the same error

**Comment by jakubcerveny** [comment]
> That was the original code in the file, when changed back to HYPRE_DIR = @MFEM_DIR@/../hypre/src/hypre it is giving the same error

Then I don't understand how you can get the line
```
mpicxx -I../../hypre-2.20.0/include get_hypre_version.cpp -o get_hypre_version
```
How does the `../hypre/src/hypre` disappear and you get `../hypre-2.20.0` instead of it? The `-I` parameter needs to be `-I../../hypre/src/hypre/include`.

**Comment by jhoy97** [comment]
I am not sure either, although thank you very much for your help! Am I able to change the `-I` parameter in defaults.mk?

**Comment by jakubcerveny** [comment]
> Am I able to change the -I parameter in defaults.mk?

Yes, indirectly through `HYPRE_DIR`. But you shouldn't need to change anything, your setup with hypre-2.20.0 and metis-4.0.3 should just work. I'd try unpacking everything again in a clean directory and try to build without any configuration changes.

**Comment by adrienbernede** [comment]
@jhoy97, were you able to get MFEM to build?

**Comment by jhoy97** [comment]
@adrienbernede I did not unfortunately

**Comment by adrienbernede** [comment]
OK, let me try to help then:

From the last screenshot you sent, it seems you still had `HYPRE_DIR=../hypre`.

I suggest we try again:
- First, run `make clean` in MFEM dir.
- Then make sure you have no local changes in `config/defaults.mk`. (`git status config/defaults.mk`). If you do, revert those changes (unless you want them, and are sure of yourself). In particular, by default this file should have `HYPRE_DIR = @MFEM_DIR@/../hypre/src/hypre`.
- `hypre-<version>` should be installed next to MFEM dir (seems OK per your screenshots), the final installation directory is typically in `hypre-<version>/src/hypre` (default hypre install).
- You apparently already have the link from `hypre` to `hypre-<version>`. That’s good. From MFEM dir in the terminal, you should be able to `ls ../hypre/src/hypre`.
- Now run `make parallel -j` again.

Let me know how it goes.

**Comment by jhoy97** [comment]
Thanks! 

OK so when in the MFEM dir and RUN `ls ../hypre/src/hypre`, the terminal replies with `ls: cannot access '../hypre/src/hypre': No such file or directory`.  This is what is in my `hypre/src` file contains.
![HYpe](https://user-images.githubusercontent.com/78260282/109789727-881b3880-7c08-11eb-9ffa-c0eb32c39e10.jpg)

**Comment by adrienbernede** [comment]
Did you install Hypre? (from `hypre-<version>` dir: `./configure`, `make`, `make install`).

**Comment by jhoy97** [comment]
I didn't even realize it had to be installed, apologies. 
I installed it, thank you!
I tried `make parallel -j` but this error came up again.  Although I'm not sure how, because there is now a `../hypre/src/hypre` DIR.

 ![Hypre confi](https://user-images.githubusercontent.com/78260282/109839075-ad2a9e00-7c3e-11eb-8943-7ee8803d36ce.jpg)

**Comment by adrienbernede** [comment]
We can see MFEM is still looking for hypre in `../../hypre/include`, meaning `HYPRE_DIR` is set to `@MFEM_DIR@/../hypre/` instead of `@MFEM_DIR@/../hypre/src/hypre`. Are you sure you did not change that in `config/defaults.mk`?

Try following the steps in https://github.com/mfem/mfem/issues/2067#issuecomment-789241615.

**Comment by jakubcerveny** [comment]
(I don't think hypre needs to be installed in the system, at least I never needed that. The paths in the makefiles/configs are set up for MFEM to work with hypre's directory just beside MFEM's directory. )

**Comment by adrienbernede** [comment]
@jakubcerveny I think you may be right insisting on the _install_ part. But it still needs to be built.

**Comment by jhoy97** [comment]
I followed the steps above, the `config/defaults.mk`, shown here, is reset to it's original inputs.

![dirri](https://user-images.githubusercontent.com/78260282/109842656-3394af00-7c42-11eb-993d-05cd29076d93.jpg)

**Comment by jhoy97** [comment]
I just realized that mfem wasn't built, although I'm not sure why as I followed the steps.  I will try and re-build and let you guys know.

**Comment by jhoy97** [comment]
Apologies for that last comment I tried deleting it.  Yeah, the same error code is coming up, I'm not sure. Thanks for the help @adrienbernede

**Comment by adrienbernede** [comment]
The screen shots with errors are in `MFEM1` dir, the source you are showing are those of `MFEM NEW`.

**Comment by jhoy97** [comment]
I changed the dir name to `MFEM1` just to avoid having a space in the dir name

**Comment by adrienbernede** [comment]
I know, and that's what we suggested. But you said:
> the config/defaults.mk, shown here, is reset to it's original inputs.
And you showed `MFEM NEW`. It is not clear to me that `MFEM1` was reset.

**Comment by jhoy97** [comment]
Believe it or not, that's what was causing the issue, my bad, thank you @adrienbernede, @tzanio, and @jakubcerveny!!
