### ISSUE TITLE
Fill matrix rows with vectors in MFEM

### ISSUE THREAD

**Issue by brightzhang91** [mfem/mfem#2071]
Hi 
I'm trying to fill some rows of a matrix with some given vectors, however I'm not clear how it is done in MFEM.   So far I have just found the `SetRow()` funciton of `DenseMatrix`, but not other matrix forms such as `HypreParMatrix` or `PetscParMatrix`.  I want to produce a blocked matrix           where A is a HypreParMatrix and B is a matrix with only a few rows (act as constraints). 
                                              [A  Bt]  
                                              [B  D]
I'm confused if B can be a DenseMatrix  as for the dimension issues.  
The other question is: can this block matrix constructed with `BlockOperator`  be used as the preconditioner for the PETSc JFNK nonlinear solution? 

Thanks very much !
best regards
Bright

**Comment by wcdawn** [comment]
I've done something similar with a `BlockOperator` and passed to SLEPc (with a `PetscParMatrix`) so this should be doable. Here's how I did it:

* Create a `ParBilinearForm` for A, B, & D.
* Call `ParBilinearForm::Assemble()` and `ParBilinearForm::Finalize()` on each.
* Use the following snippet to create a `PetscParMatrix` for each of A, B, & D. Probably hide it in a function or an object.
```cpp
OperatoHandle oh{Operator::PETSC_MATAIJ};
A.ParallelAssemble(oh); // A is the ParBilinearForm
PetscParMatrix* Appm{nullptr};
oh.Get(Appm);
oh.SetOperatorOwner(false);
```
* Create a `PetscParMatrix` for B^T.
* Set the entries in the `BlockOperator` using the `PetscParMatrix`. For example, `my_block_operator.SetDiagonalBlock(0, Appm);`.
* Convert to a big `PetscParMatrix`. This is messy because of how the different types of `Mat` objects are handled between MFEM/PETSc. If you find a cleaner way, please let me know!
```cpp
PetscParMatrix big_tmp{MPI_COMM_WORLD, &my_block_operator, Operator::PETSC_MATAIJ};
PetscParMatrix big{&big_tmp, Operator::PETSC_MATAIJ};
```

Don't forget to delete you're memory!
Hope this helps!

**Comment by brightzhang91** [comment]
Thanks very much wcdawn !
Your example is great and very helpful. This is close to what I seek, a `PetscParMatrix` or `HypreParMatrix` constructed from a `BlockOperator`, to be used as the preconditioner for nonlinear solver. However unfortunately, my B and Bt matrix are not produced from `ParBilinearForm`. Instead, I used `ParLinearForm` to produce several vector-form constraints and I want to fill these vector-form constraints into the B (and Bt) matrix, as a part of the block matrix. 
Do you know how to specify some rows of `PetscParMatrix` or `HypreParMatrix`  with some vectors ? Or can you produce a BlockOperator with both `PetscParMatrix` and `DenseMatrix`, then to be converted to a big `PetscParMatrix` ?

Thanks 
Bright

**Comment by wcdawn** [comment]
I see. Could you create a `SparseMatrix` for B and populate the rows using `SparseMatrix::AddSubMatrix`? You could specify the rows as 1xN dense matrices. Once you had the `SparseMatrix`, you could then convert it to a `PetscParMatrix`. There may be a better idea but this seems like a possibility.

**Comment by brightzhang91** [comment]
My one-row constraints are generated in the `HypreParVector` form, using the `ParallelAssemble()` method of `ParLinearForm`. To convert the vectors into a matrix, it seems I'll need to go though `Vectors` -> `DenseMatrix` - > `SparseMatrix `- > `HypreParMatrix` or `PetscParMatrix` . Is there a easier way to do this ? such as directly from `HypreParVector` to `HypreParMatrix` ?
Thanks !
best regards
Bright

**Comment by brightzhang91** [comment]
Hi 
I created the one-row `SparseMatrix`, and use it as a part of my `BlockOperator`. However the one-row `SparseMatrix` cannot be converted into a `PetscParMatrix` , except in the PETSC_MATSHELL form. I can only convert a square `SparseMatrix`  into a PETSC_MATAIJ  or PETSC_MATHYPRE `PetscParMatrix`.
		
  It seems the PETSC_MATSHELL `PetscParMatrix` cannot be used as Jacobian or preconditioner in JFNK solution, so that I need to convert my `BlockOperator` into PETSC_MATHYPRE form. 
Can anyone advise me how to obtain my `PetscParMatrix` preconditioner from my `BlockOperator` with the one-row matrix ? Or if the conversion from non-square `SparseMatrix` to `PetscParMatrix` can be fixed ?

Sorry it may seem confusing.

Thanks very much !
Bright

**Comment by wcdawn** [comment]
It sounds like you may want something like `HypreParMatrixFromBlocks()` but for PETSc. I will say that from my experience, it is sometimes to obtain a HYPRE matrix and then convert to a PETSc matrix as MFEM makes extensive use of the HYPRE objects. You could construct the block HYPRE matrix and then convert to PETSc at the last instant.

I'm not sure about non-square matrices in PETSc. I've only used them in the context of bilinear forms which are square.

A snippet to convert a HYPRE matrix to a PETSc matrix that I have used looks like this
```cpp
HypreParMatrix* Ahypre = bilinear_form.ParallelAssemble();
PetscParMatrix Apetsc(Ahypre, Operator::PETSC_MATAIJ);
delete Ahypre;
```
You can see [here](https://mfem.github.io/doxygen/html/classmfem_1_1PetscParMatrix.html#aebfbf4b309fba5e1c500dff670e76726) for some more info about creating a PETSc matrix from a HYPRE matrix.

FYI you're probably better off opening a new issue for this if you want to get the attention of someone more knowledgeable than me :)

**Comment by brightzhang91** [comment]
> It sounds like you may want something like `HypreParMatrixFromBlocks()` but for PETSc. I will say that from my experience, it is sometimes to obtain a HYPRE matrix and then convert to a PETSc matrix as MFEM makes extensive use of the HYPRE objects. You could construct the block HYPRE matrix and then convert to PETSc at the last instant.
> 
Hi Wcdawn

Thanks very much for the advice. This is exactly what I needs, to convert a `BlockOperator` into PETSc matrix. My  current `BlockOperator` is in the form of `SparseMatrix`, which has some non-square subblocks so that unable to be converted into PETSc matrix. I'm trying to find an alternative way to produce the "Block" PETSc matrix I need. 
One way is to try to convert my SparseMatrix into HYPRE matrix and then to PETSc matrix, as you suggested. Or I can try to abandon the "Block" system and directly create a bigger `SparseMatrix` and fill it with subblocks via `SparseMatrix::AddSubMatrix`. I think the latter at least eliminates the presence the non-square matrix.

Thanks 
Bright
