### ISSUE TITLE
Question: multi-body analysis with Multiple Point Constraints(MPC) or constraint equations

### ISSUE THREAD

**Issue by liangcheng** [mfem/mfem#2072]
Hello MFEM staff and community, 

I checked out the ex2, 6, and 21, and they look great. My question is can MFEM solve the multi-body problems using the same scheme for the problems illustrated below? The body boundaries are not aligned exactly, only a portion of the boundaries are bonded. If it is an electrostatic/magnetostatic analysis, do I need to create a new integrator rather than using the existing ElasticityIntegrator? 

```
                    +----------+
        +----------+| material |
        | material ||     2    |+----------+
        |    1     ||          || material |
        |          |+---------+||    3     |
        +----------+            |          |
                                +----------+
```

Look forward to hearing from you. Thank you.

Best regards,
Liang

**Comment by liangcheng** [comment]
Hello Barker29,

Thank you for your answers. 
Yes, my question is about the similar contact condition between bodies, but no separation or sliding occurs. The bodies are just simply bonded from the beginning to the end of the simulation. No shared nodes or elements on the boundary between bodies. Nowadays, MPC condition has many applications in structural, thermal, and electromagnetic analyses. So I really look forward to seeing and using this feature in MFEM. 

I will look into #1842 and the relevant source code, and try to understand the algorithms implemented in MFEM. Forgive me that I may have some questions (could be dummy) in the future.

Best regards,
Liang

**Comment by tzanio** [comment]
I will close this for now, but please feel to re-open if you have further questions.
