### ISSUE TITLE
No convergence in Example 2

### ISSUE THREAD

**Issue by xianyu-gao** [mfem/mfem#2084]
I use one Minimal surface element model to test example 2,but show PCG:No convergence. I don’t know if it’s the problem with the model or the wrong solver

**Comment by tzanio** [comment]
Hi @xianyu-gao,

I am not sure what "Minimal surface element model" means, can you clarify?

Example 2 solves a (simple) linear elasticity problem. We have a separate minimal surface miniapp, see https://github.com/mfem/mfem/blob/master/miniapps/meshing/minimal-surface.cpp.

In general "PCG:No convergence" means that the linear system was not solved, and so you should either  increase the number if iterations in PCG (500 by default), or use a better preconditioner e.g. by switching to the parallel version, ex2p, which uses AMG.

Hope this helps,
Tzanio
