### ISSUE TITLE
gzstream seek and tell broken

### ISSUE THREAD

**Issue by termi-official** [mfem/mfem#2094]
I catched another minor bug, but this time I am not sure how to fix it, therefore the issue. Turns out ``ifgzstream``, ``named_ifgzstream``, ... do not correctly implement seeking and telling. Seek and tell is used when loading VTU meshes.

The issue should be reproducible by using GlVis to load any VTU mesh. If not, then it may be related to using clang with libc++ (instead of gcc with libstdc++).

**Comment by jandrej** [comment]
Can you point it to our interface or the used library?

**Comment by termi-official** [comment]
Sure. I talk about the streams defined in this file

https://github.com/mfem/mfem/blob/8af351185c1e7a81e8241534ed7ff7d52f04f172/general/zstr.hpp

where the following two lines cause problems.

https://github.com/mfem/mfem/blob/8af351185c1e7a81e8241534ed7ff7d52f04f172/mesh/mesh.cpp#L3546-L3547

Debugging this I could find out that the call to seekg does not affect the interal io pointer, such that the first read in ``ReadXML_VTKMesh`` reads the wrong line (i.e. the "header tag" is skipped).

**Comment by markcmiller86** [comment]
@tzanio probably best to assign someone else on the team. I can't recall who now by my orig. gzstream stuff was replaced (with maybe zstr???) in MFEM about 2 yrs ago now I think.

**Comment by markcmiller86** [comment]
or, maybe don't use gzstream for VTK ascii files.

**Comment by markcmiller86** [comment]
The wrapper class names were kept but the underelying implementation was replaced.

**Comment by jandrej** [comment]
Thanks for reporting this. I'm working on it.

**Comment by jandrej** [comment]
It seems to be an issue in multiple instances here.

The XML reader complains on a perfectly valid XML VTU file that I can open in Paraview. E.g. an mfem build without zlib doesn't work either.

The second issue is with zlib activated, the seekg/tellg methods are not implemented for the ifstream wrappers.

**Comment by v-dobrev** [comment]
> The XML reader complains on a perfectly valid XML VTU file that I can open in Paraview.

Hmm, this is strange -- I think @pazner tested this when he added tinyxml2 in #1894. Maybe the specific file you have, uses some feature that is not supported by tinyxml2? I think ParaView itself uses `libexpat` for XML parsing so there definitely can be differences.

> The second issue is with zlib activated, the seekg/tellg methods are not implemented for the ifstream wrappers.

One option could be to use re-open for this type of input instead of `seekg` here: https://github.com/mfem/mfem/blob/f71a028ffcc7e3db50ae06f5feb828584ccabda8/mesh/mesh.cpp#L3543-L3548

assuming the input is a `named_ifgzstream` like here: https://github.com/mfem/mfem/blob/f71a028ffcc7e3db50ae06f5feb828584ccabda8/mesh/mesh.cpp#L3568-L3569

**Comment by jandrej** [comment]
I agree that this might be the only non-intrusive fix right now. Especially to support compressed inputs.

**Comment by pazner** [comment]
> > The XML reader complains on a perfectly valid XML VTU file that I can open in Paraview.
> 
> Hmm, this is strange -- I think @pazner tested this when he added tinyxml2 in #1894. Maybe the specific file you have, uses some feature that is not supported by tinyxml2? I think ParaView itself uses `libexpat` for XML parsing so there definitely can be differences.

I believe @jandrej was trying to load a VTU file with "appended binary data", which is not supported in MFEM's reader (neither is inline binary data, for that matter). A better error message would probably be helpful (Julian, if you send me the file I can find where in the code the error message should be placed).

**Comment by tzanio** [comment]
Discussion continued in #2017.
