### ISSUE TITLE
Element transformation defined in MFEM seems not universal

### ISSUE THREAD

**Issue by OliiLee** [mfem/mfem#2099]
Hi,

when I read the paper [MFEM: A modular finite element methods library](https://doi.org/10.1016/j.camwa.2020.06.009), I find that in MFEM, points in physical element are transformed from the reference element by ![](http://latex.codecogs.com/svg.latex?x=\Phi(\hat{x})), and expressed in terms of the linear combination of local nodes with coefficients defined as the evaluation of shape functions at corresponding points in reference element. In the library, method `mfem::IsoparametricTransformation::Transform()` does this job. I realize that this approach could improve the versatility of the class `mfem::IsoparametricTransformation` so that it can handle different geometric types of elements. 
However, when it comes to some finite elements in which we may not be able to define such nodes(e.g. the Hermite element), this method may be failure. I believe this problem could be solved if I write a derived class of `mfem::IsoparametricTransformation` or `mefm::ElementTransformation` with the transformation being implemented as in the usual textbook(the transformation has nothing to do with the finite element). But I'm wondering if such implementation would be incompatible with other modules in MFEM library?

Thanks,
Ziyi

**Comment by tzanio** [comment]
Hi Ziyi,

By definition `IsoparametricTransformation` means transformation specified by a nodal basis. You can absolutely derive another class from `ElementTransformation` and everything in MFEM should just work with it.

Hope this helps,
Tzanio

**Comment by OliiLee** [comment]
> Hi Ziyi,
> 
> By definition `IsoparametricTransformation` means transformation specified by a nodal basis. You can absolutely derive another class from `ElementTransformation` and everything in MFEM should just work with it.
> 
> Hope this helps,
> Tzanio

Thank you so much for your help!
