### ISSUE TITLE
Multiplication of HypreParMatrix objects

### ISSUE THREAD

**Issue by kvoronin** [mfem/mfem#210]
Hello everyone,

Is multiplication of two HypreParMatrix objects implemented currently? I have two HypreParMatrix objects - one from parallel assembling a bilinear form in MFEM, and another obtained in a different way and I want to multiply them (to put as a block in the resulting linear block system's operator), but I didn't find anything implemented which would make it. Is it really so or have I mislooked?

Thanks,
Kirill

**Comment by mlstowell** [comment]
Hi, Kirill,

Have a look around line 480 of "mfem/linalg/hypre.hpp" and you should find a function called "ParMult".  This takes pointers to two HypreParMatrix objects and returns a pointer to a new HypreParMatrix object which contains the product of the two inputs.  As long as the matrices have compatible shapes this should work correctly regardless of how the matrices were constructed.

Best wishes,
Mark

**Comment by kvoronin** [comment]
Hi Mark, 

Thank you for the hint, this is what I needed. I wonder why there are no mentions of this function in the documentation for HypreParMatrix class.

Best,
Kirill

**Comment by tzanio** [comment]
Feel free to add documentation, @kvoronin :)

**Comment by mlstowell** [comment]
Hi, Kirill,

Well, it's a standalone function and not a class member so it is harder to find.  Your point is well taken though.  We should probably add something to the comment block at the start of the HypreParMatrix class to list related functions.

Thanks,
Mark

**Comment by kvoronin** [comment]
Thanks for the replies!
