### ISSUE TITLE
[WIP] Improvements for Github Actions CI

### ISSUE THREAD

**Issue by adrienbernede** [mfem/mfem#2102]
- [ ] There is no use of artifacts for now. This is to keep things simple for a first implementation, but limits our possibilities. Using artifact will help improve reusability of some steps.
- [ ] Just two workflows: the separation between 'build-test' and 'build-analysis' is mostly due to the use of a large matrix, instead of a multi-stage workflow (see previous task).
- [ ] Better naming: a bit too long and not straight to the point (e.g. cmake config could just be name 'cmake').

_Originally posted by @tzanio in https://github.com/mfem/mfem/pull/2041#discussion_r584022435_

_Partially answered by @adrienbernede in https://github.com/mfem/mfem/pull/2041#issuecomment-788141750_

The coverage is operational. That could can use some improvements:

- [x] Coverage of the tests code (examples and unit directories) is not useful.
- [ ] We could categorize coverage: unit testing / example testing. Giving a better view of the type of test we lack and where.

_Originally posted by @adrienbernede in https://github.com/mfem/mfem/pull/2041#issuecomment-800493085

**Comment by adrienbernede** [comment]
Will be working on that this week.

**Comment by tzanio** [comment]
A lot of these were addressed in https://github.com/mfem/mfem/pull/2558
