### ISSUE TITLE
win10 ex1 running

### ISSUE THREAD

**Issue by Haikuana** [mfem/mfem#2103]
Hi,

I built this project via cmake 3.15 on win10, it compiles successfully, however, when I run the ex1, it shows some errors:
mfem::Memory<mfem::IntegrationRule * __ptr64>::operator[](...) returned nullptr.

It breaks down when >	ex1.exe!mfem::`dynamic initializer for 'IntRules''() Line 877 in intrules.cpp, could you please help figure out what happened?

Thanks

**Comment by tzanio** [comment]
Did you use WLS, Visual Studio or something else?

**Comment by Haikuana** [comment]
yes, I use Visual Studio 2015.

**Comment by liangcheng** [comment]
I just tried ex1 on Win10 for you and cannot reproduce this issue. Did you select the /machine:x64 at CMake configuration?

**Comment by Haikuana** [comment]
I run this project on my laptop without any installed libraries, it works (vs 2019). However, it still crashes down when I turn to my desktop.
Maybe interrupted with other libraries?
It seems weird.

**Comment by ajithvallabai** [comment]
@Haikuana  were u able to run paralle version in windows by linking hypre and metis libraries ?

**Comment by Haikuana** [comment]
@ajithvallabai I used default openmp, I recommend you can try linux to link these libs. it should be easier!

**Comment by v-dobrev** [comment]
We test the build with Visual Studio with MPI+hypre+metis in the appveyor CI, see the commands we use in https://github.com/mfem/mfem/blob/master/.appveyor.yml. We only run the serial examples on appveyor, so it is possible there maybe some runtime issues with the parallel build that we do not catch.
