### ISSUE TITLE
unexpected behavior from GetGeometricFactors 

### ISSUE THREAD

**Issue by samuelpmishLLNL** [mfem/mfem#2106]
`mfem::Mesh::GetGeometricFactors` appears to have an early exit condition if it detects the input IntegrationRule matches the one already there. However, it detects IntegrationRule equality by comparing pointers rather than comparing the actual contents. In practice, this means that if a user creates an IntegrationRule in a function scope, subsequent calls to that function can produce IntegrationRules with identical addresses. This results in GetGeometricFactors incorrectly concluding the integration rules are the same, returning incorrect values. A short example of this problem is given below:

```cpp
#include "mfem.hpp"

auto get_quadrature_point_positions(mfem::Mesh & mesh, const mfem::FiniteElementSpace & fes) {

  const mfem::FiniteElement& el = *(fes.GetFE(0));

  const mfem::IntegrationRule ir = mfem::IntRules.Get(el.GetGeomType(), el.GetOrder() * 2);

  std::cout << "integration rule with " << ir.Size() << " points, &ir = " << &ir << std::endl;

  auto geom = mesh.GetGeometricFactors(ir, mfem::GeometricFactors::COORDINATES);

// const GeometricFactors* Mesh::GetGeometricFactors(const IntegrationRule& ir,
//                                                   const int flags)
// {
//    for (int i = 0; i < geom_factors.Size(); i++)
//    {
//       GeometricFactors *gf = geom_factors[i];
//       if (gf->IntRule == &ir && (gf->computed_factors & flags) == flags)
//                       ^^
//                        | 
//                       pointer equality does not imply integration rule equality
//
//       {
//          return gf;
//       }
//    }
// 
//    this->EnsureNodes();
// 
//    GeometricFactors *gf = new GeometricFactors(this, ir, flags);
//    geom_factors.Append(gf);
//    return gf;
// }

  return geom->X;

}

int main() {

  const char * mesh_file = "path/to/meshes/star.mesh";

  mfem::Mesh mesh(mesh_file, 1, 1);

  std::cout << "mesh has " << mesh.GetNE() << " elements" << std::endl;

  // expected behavior: 
  // different polynomial orders should change the integration rule 
  // and GetGeometricFactors should return new coordinates for each rule
  // 
  // actual behavior: 
  // different polynomial orders DO change the integration rule 
  // but GetGeometricFactors only computes the coordinates the first time,
  // and just returns those values on subsequent calls (with different integration rules)
  for (int order = 1; order < 5; order++) {
    auto fec = mfem::H1_FECollection(order, mesh.Dimension());
    mfem::FiniteElementSpace fespace(&mesh, &fec);
    mfem::Vector X = get_quadrature_point_positions(mesh, fespace);
    std::cout << "order " << order << ", X.size() = " << X.Size() << std::endl;
  }

}
```

actual output (GetGeometricFactors incorrectly concludes that different integration rules are the same). 
Ubuntu 20.04, clang 10.0.0
```
mesh has 20 elements
integration rule with 4 points, &ir = 0x7ffc30105800
order 1, X.size() = 160
integration rule with 9 points, &ir = 0x7ffc30105800
order 2, X.size() = 160
integration rule with 16 points, &ir = 0x7ffc30105800
order 3, X.size() = 160
integration rule with 25 points, &ir = 0x7ffc30105800
order 4, X.size() = 160
```

expected output 
```
mesh has 20 elements
integration rule with 4 points, &ir = 0x7ffc30105800
order 1, X.size() = 160
integration rule with 9 points, &ir = 0x7ffc30105800
order 2, X.size() = 360
integration rule with 16 points, &ir = 0x7ffc30105800
order 3, X.size() = 640
integration rule with 25 points, &ir = 0x7ffc30105800
order 4, X.size() = 1000
```

**Comment by v-dobrev** [comment]
This was a compromise -- the `IntegrationRule` used with `Mesh::GetGeometricFactors` needs to remain valid while the internally stored `GeometricFactors` objects are destroyed (by either calling `Mesh::DeleteGeometricFactors` or the `Mesh` destructor). In most cases the `IntegrationRule` is obtained using `IntRules.Get` which is a global container for `IntegrationRule` objects, so this should not be a problem unless one uses local custom `IntegrationRule`. In your example, you simply need to use a reference to the returned `IntegrationRule`:
```c++
  const mfem::IntegrationRule &ir = mfem::IntRules.Get(el.GetGeomType(), el.GetOrder() * 2);
```
instead of creating a copy.

**Comment by v-dobrev** [comment]
One more note: we can implement actual comparison, if really needed, but the lifetime of the `IntegrationRule` used in `Mesh::GetGeometricFactors` should remain the same as now.

**Comment by samuelpmishLLNL** [comment]
Thank you for the feedback. I'm happy to learn that a simple workaround exists, but still concerned that unusual lifetime requirements like

> the IntegrationRule used with Mesh::GetGeometricFactors needs to remain valid while the internally stored GeometricFactors objects are destroyed (by either calling Mesh::DeleteGeometricFactors or the Mesh destructor).

are not being effectively communicated to the user. 

There are no inline comments for `Mesh::GetGeometricFactors`, its type signature does not reveal any hints about the lifetime of the first argument, nor does its Doxygen entry.

Oversights like these can hurt the new user experience by making it difficult to discover ownership/lifetime requirements without spending hours of debugging or posting an issue to GitHub.

**Comment by v-dobrev** [comment]
I agree, we should update the doxygen comments to document this requirement. Will that be sufficient?

**Comment by acfisher** [comment]
@YohannDudouit are you game for putting finger to keyboard on this in the next day or two?  If not I'll take it.

**Comment by tzanio** [comment]
Discussion continued in #2198
