### ISSUE TITLE
Diffusion integrator for 2D problem on 3D mesh

### ISSUE THREAD

**Issue by sshiraiwa** [mfem/mfem#2111]
I am solving a diffusion equation on a surface. Since the source term and diffusion coefficient are eventually
evaluated using another simulation done in 3D and the surface is not necessarily on the X-Y plane, I am using 
a mesh file which has SpaceDimension=3, and testing with div c grad phi = 1. Everything seems to work fine whichever
way I orient the surface, and the result agrees with the case using a mesh file with SpaceDimension=2... until
the coefficient c becomes a Matrix. With a matrix, even if it is diagonal, the result is incorrect.

Looking at the code section around https://github.com/mfem/mfem/blob/master/fem/bilininteg.cpp#L712, for nd=2
spaceDim=3, invdfdx becomes 2x3. So, it seems I am supposed to give 2x3 matrix? If so how do I define it if I 
have 3x3 matrix? Also, since dshape is nd x 2 and dshapedxt is nd x 3, I am not sure how this line in L732 works.

   AddMultABt(dshape, dshapedxt, elmat);

If I change  invdfdx to 3x3, and  receive a result of Mult in L731 in a new DenseMatrix with the same size as
dshapedxt, it seems fix the problem. 

Please let me know what you think. Thank you.

**Comment by mlstowell** [comment]
Hi, @sshiraiwa ,

I think you are correct.  This integrator was probably not tested with a `MatrixCoefficient` on an embedded surface. In fact we may not have unit tests involving embedded surfaces. We should certainly add such tests.

Would you like to add a PR to address this or shall I?

Thanks for catching this and we're sorry for the trouble.
Best wishes,
Mark

**Comment by sshiraiwa** [comment]
Hi @mlstowell, thank you for confirming this. Let me clean up what I have and make a PR. 
I saw a similar issue in mixed version. Let me address both.

**Comment by sshiraiwa** [comment]
Hi @mlstowell, I made a PR. May I ask to add a test, since I am not familiar with that part of machinery. Thank you.

**Comment by mlstowell** [comment]
I'd be happy to look into adding a suitable unit test. Thanks, @sshiraiwa!

**Comment by tzanio** [comment]
Discussion continued in #2125.
