### ISSUE TITLE
Implementing Uzawa Solver

### ISSUE THREAD

**Issue by mschneier91** [mfem/mfem#2112]
Hi,

I'm interested in implementing an Uzawa solver for the Stokes equations using PN/PN-1 finite elements for the velocity and pressure space respectively. This method decouples the block structure of the problem. The portion of the weak form that arises from this iterative scheme which I'm having some issues with looks like: given a previous pressure iterate (p^n) solve

nu*(grad u^n+1, grad v) = (f,v) + (p^n, div(v))

Is there currently a way to do this in MFEM using Lagrange finite elements? it seems to me that p^n can just be treated as a grid function coefficient for a linear form integrator, but from what I can see of the current linear form options (div(v), p^n) would only be possible for RT elements via VectorFEDomainLFDivIntegrator as of right now? 

Would the simplest thing be to write a VectorDomainLFDivIntegrator class?

**Comment by pazner** [comment]
This is very similar to what is implemented in the bilinear integrator `VectorDivergenceIntegrator`. One simple option would be to create a bilinear form with `VectorDivergenceIntegrator`, and apply its transpose to `p^n`, which should give you `(p^n, div(v))`. You can then add the resulting vector to the RHS.

I think this is likely to be more straightforward than creating a new linear integrator with a gird function coefficient, but that route is also possible (you can mimic what is done in `VectorDivergenceIntegrator` to create the linear integrator).

**Comment by mschneier91** [comment]
Great, that is very straight forward. Thank you!
