### ISSUE TITLE
Navier-Stokes solver in MFEM

### ISSUE THREAD

**Issue by KazemKamran** [mfem/mfem#212]
We at SCOREC are interested to use **MFEM** for a EFRC project about hazardous waste material. 
As a first step we need to have a **Navier-Stokes** solver and coupled it with **Cahn-Hilliard** for the phase change. 

We would like to know:

1. How feasible it is to implement it in MFEM?

2. Has any part of it (i.e. NS or Cahn-Hilliard solver)  been implemented in MFEM or if anyone has experience doing it?

 From what I see in the MFEM website, BLAST code is probably the closest example, however I am not sure if the implementation is accessible. 

Thank you

**Comment by tzanio** [comment]
@KazemKamran and @MarkShephard:

A **Navier-Stokes** solver should be relatively easy to implement -- we probably already have all the integrators you need, and adding missing integrators shouldn't be hard. I suspect some of our users may already have done the NS part, see for example https://github.com/mfem/mfem/pull/186 by @vikramsg and https://github.com/mfem/mfem/issues/40 by @Watchmojo. We also have experience with the compressible flow terms in BLAST, but that code is not open-source, sorry.

The **Cahn-Hilliard** solver will be more challenging. My understanding is that it requires C1 spaces, which we currently don’t support in MFEM. Adding C1 support is doable, but will require some refactoring of the MFEM internals. (If you can do Cahn-Hillard with C0 spaces, then most of the difficulty will go away.)

Cheers,
Tzanio

**Comment by KazemKamran** [comment]
@tzanio @v-dobrev @MarkShephard 
Please have a look to the attached file.
[NS_MFEM.pdf](https://github.com/mfem/mfem/files/1053225/NS_MFEM.pdf)

**Comment by juan42** [comment]
@kazemkamran in the attached PDF you use the coupled formulation for NS. The nonlinear term is only implemented as a residual form ("for the right hand side") and not as a bilinear form. Which is of course not a problem if you treat the advection explicitly.

**Comment by tzanio** [comment]
@KazemKamran:

Out of the forms listed in the PDF, we have integrators for all of the bilinear forms. For the non-linear term, the best example we have is indeed ex10, so why not implement the whole of the l.h.s. as one `NonlinearForm`? It will be a lot of code, but you don't have to put everything in the same file :).

I'm not sure about coupling with Cahn-Hilliard... I don't have experience with that, hopefully somebody else does and can chime in.

I don't quite follow what you mean by the last paragraph. All computations are ultimately done on an element level.

**Comment by juan42** [comment]
The coupling should be relatively easy. Although having a coupling from NS to CH and vice versa you just need to assemble a block system (not explicitly a BlockOperator, you can form every matrix on its own if you use Schur complement techniques) The key class here is the ParMixedBilinearForm which enables coupling of two variables.

**Comment by KazemKamran** [comment]
@tzanio @juan42 
I will most probably do so and put everything in a `NonlinearForm`. 

Coupling with CH is going to be weak coupling so no need to build a system. I do, however, need to build a block system for NS as it is going to be mixed u-p, and I see sth similar in ex5 that answered most of my questions.

Overall with ex5, ex9, ex10 and electromagnetic miniapp, I have enough material to start. 
I will probably bug you as needed on the way :). 

Thanks
P.S. By the last paragraph in the pdf I meant sth like this 
https://github.com/KratosMultiphysics/Kratos/blob/master/applications/incompressible_fluid_application/custom_elements/asgs_3d.cpp

**Comment by tzanio** [comment]
Hi @KazemKamran, I know you've made quite a bit of progress on this. Should we close this issue or should we keep it open for future discussions? -Tzanio

**Comment by KazemKamran** [comment]
Hi @tzanio, yes I think I know enough to keep implementing by now, If I have more queations I will open a new one.
