### ISSUE TITLE
Some problems with load application in ex2

### ISSUE THREAD

**Issue by HFH104864** [mfem/mfem#2126]
In the following code : 

```c++
 VectorArrayCoefficient f(dim); 
    for (int i = 0; i < dim - 1; i++)
    {
        f.Set(i, new ConstantCoefficient(0.0));  
    }
    {
        Vector pull_force(mesh->bdr_attributes.Max());//3 
        pull_force = 0.0;
        pull_force(1) = -1.0e-2;   
        f.Set(dim - 1, new PWConstCoefficient(pull_force));  
    }
```

In this line of code  **pull_force(1) = -1.0e-2**    What does the number 1 in pull_force represent . I thought 0,1,2 represented forces in X,Y, and Z, but they didn't.If I need to apply a load in the X,Y, and Z directions, what should I do?

**Comment by tzanio** [comment]
Hi @HFH104864,

The array `pull_force` is used as an argument for a `PWConstCoefficient` which is a piecewise-constant coefficient on the boundary attributes. Here `1` referrers to the second boundary attribute (counting from `0`).

The X,Y, and Z directions are the indices used in `f.Set(`. For example the first loop makes all components of the force vector zero, while the following block sets the last one, i.e. Y in 2D, to be 0 on boundary attribute 1 and -0.01 on boundary attribute 2.

Hope this helps,
Tzanio

**Comment by HFH104864** [comment]
thank you . it helps me a lot!!
