### ISSUE TITLE
Warnings when building on Cygwin

### ISSUE THREAD

**Issue by Samue1l** [mfem/mfem#2128]
I was trying to build MFEM+GLvis with Cygwin and i ran into errors when building with the base config: 

```sh
general/tinyxml2.cpp: In member function ‘tinyxml2::XMLError tinyxml2::XMLDocument::LoadFile(FILE*)’:
general/tinyxml2.cpp:110:22: error: ‘fseeko64’ was not declared in this scope; did you mean ‘_fseeko_r’?
  110 |  #define TIXML_FSEEK fseeko64
      |                      ^~~~~~~~
general/tinyxml2.cpp:2325:5: note: in expansion of macro ‘TIXML_FSEEK’
 2325 |     TIXML_FSEEK( fp, 0, SEEK_SET );
      |     ^~~~~~~~~~~
general/tinyxml2.cpp:111:22: error: ‘ftello64’ was not declared in this scope; did you mean ‘_ftello_r’?
  111 |  #define TIXML_FTELL ftello64
      |                      ^~~~~~~~
general/tinyxml2.cpp:2335:44: note: in expansion of macro ‘TIXML_FTELL’
 2335 |         const long long fileLengthSigned = TIXML_FTELL( fp );
```

After some tests i solved this by using the `-std=gnu++11` flag in a user.mk makefile and by modifying the file `general/tinyxml2.cpp` to check for a `__CYGWIN__` flag and then use fseeko/ftello since they seem to exist contrary to fseeko64/ftello64:

```cpp
#if defined(_WIN64)
        #define TIXML_FSEEK _fseeki64
        #define TIXML_FTELL _ftelli64
#elif defined(__APPLE__) || (__FreeBSD__)
        #define TIXML_FSEEK fseeko
        #define TIXML_FTELL ftello
#elif defined(__CYGWIN__)
        #define TIXML_FSEEK fseeko
        #define TIXML_FTELL ftello
#elif defined(__unix__) && defined(__x86_64__)
        #define TIXML_FSEEK fseeko64
        #define TIXML_FTELL ftello64
#else
        #define TIXML_FSEEK fseek
        #define TIXML_FTELL ftell
#endif
```
 
MFEM and GLvis now build and the few examples i tried seem to match however the building of MFEM outputs a bunch of Wstringop-overflow warnings:
```sh
fem/bilininteg_hcurl.cpp:4476:26: warning: ‘void* __builtin_memcpy(void*, const void*, long unsigned int)’ writing between 8 and 34359738368 bytes into a region of size 0 overflows the destination [-Wstringop-overflow=]
 4476 |                sBc[d][q] = Bc(q,d);
      |                ~~~~~~~~~~^~~~~~~~~
fem/../general/forall.hpp:59:43: note: in definition of macro ‘MFEM_FORALL_3D’
   59 |                  [&] MFEM_LAMBDA (int i) {__VA_ARGS__},\
      |                                           ^~~~~~~~~~~
fem/bilininteg_hcurl.cpp:4477:26: warning: ‘void* __builtin_memcpy(void*, const void*, long unsigned int)’ writing between 8 and 34359738368 bytes into a region of size 0 overflows the destination [-Wstringop-overflow=]
```

Are those normal ? Is there some way, that i missed, to natively use fseeko64/ftello64 on Cygwin that you're aware of ? 
Thanks

**Comment by pazner** [comment]
I think we generally encourage windows users to use WSL instead of Cygwin. `fseeko64` and `ftello64` are only required if you are reading XML VTK meshes that are over 2 GB in size. Maybe this small modification would allow you to compile with `-std=c++11` instead of `-std=gnu++11`, but I haven't tested to be sure:
```c++
#elif defined(__CYGWIN__)
        #define TIXML_FSEEK fseek
        #define TIXML_FTELL ftell
```
(i.e. just use `fseek` and `ftell` instead of `fseeko` and `ftello`).

**Comment by Samue1l** [comment]
Yes i eventually gave up on Cygwin and switched to WSL. 
Just for anyone reading this and to answer your suggestion, i tried to switch for `fseek` and `ftell` and it indeed compiled with `-std=c++11` as you said. But eventually i ran into trouble with the building of GLvis which required `-std=gnu++11` to build correctly on my Cygwin.
