### ISSUE TITLE
CMake target property not found

### ISSUE THREAD

**Issue by jdumas** [mfem/mfem#213]
Hi,

I have noticed that the [`MFEM_TPL_INCLUDE_DIRS`](https://github.com/mfem/mfem/blob/master/CMakeLists.txt#L427) variable is not properly defined on my computer, when I try to compile MFEM with CMake. This happens with the latest version from the git (running an up-to-date `archlinux` and `cmake 3.8.0`). This poses a problem when installing the library locally on the computer and using the `MFEMConfig.cmake` file, which produces an error because of a `MFEM_TPL_INCLUDE_DIRS-NOTFOUND`.

**Comment by v-dobrev** [comment]
Thanks for reporting this issue - it should be resolved in #214.

**Comment by tzanio** [comment]
Resolved by 2f1ab15a.
