### ISSUE TITLE
dofs ordering in ParMesh

### ISSUE THREAD

**Issue by geyan3566** [mfem/mfem#2138]
Hi,

I'm developing a new parallel FEM method using parallel mesh where I need to construct a `HypreParMatrix`.
The `HypreParMatrix` interface in `mfem` might be inadequate for me.
However, `hypre` only provides `HYPRE_IJMATRIX` API to construct the underline `HYPRE_PARCSR` matrix.
(For your reference, [GitHub](https://github.com/hypre-space/hypre/issues/311))
The `HYPRE_IJMATRIX` will construct an `HYPRE_PARCSR` matrix following a "row block" fashion.

My problem is:
1. Does `mfem` has the functionality that reorders the dofs such that the global dofs are clustered for each processor?
2. or is there any direct instruction on `hypre_parcsr` API?

Thank you very much,
Ge

**Comment by tzanio** [comment]
MFEM includes a number of methods to construct parallel matrices in *hypre* format in the `hypre.?pp` and `hypre_parcsr.?pp` files. I will strongly advise to use those than the direct `IJ` interface in *hypre*.

Can you explain what you are trying to achieve and why you believe the current interface is not sufficient?

Tzanio

**Comment by geyan3566** [comment]
Thanks. To be more specific, let's say I get a parallel mesh that has a total of 50 elements and are distributed on 3 processor.

My questions are:
1. How to get the global element and local element index of a single element?
2. How to get the element dofs' global ordering (if exists) and local ordering?
3. If the parallel mesh (`mfem::ParMesh`) is constructed from a `pumi` mesh, are those ordering mentioned above the same?

Thanks,
Ge

**Comment by tzanio** [comment]
1 is easy, and 2 is doable but if you really need them you may be using MFEM in a non-standard way.

In general details like this are needed only in the internal assembly routines and you shouldn't need them if use Linear and Bilinear forms.

I am not sure about 3, @mortezah may know.

**Comment by mortezah** [comment]
I am not sure if this answers questions 3, but when a `ParMesh` is constructed from a parallel `pumi` mesh, the elements would have the same order locally. For example, element 4 on part 2 of the pumi mesh is the same as element 4 on part 2 of the mfem mesh.
