### ISSUE TITLE
Support petsc-3.15.0

### ISSUE THREAD

**Issue by adam-sim-dev** [mfem/mfem#2140]
Hello, when I upgrade to petsc-3.15.0, I found the following warnings and errors:

linalg/petsc.cpp(1861): warning #1478: function "KSPMonitorDefault" (declared at line 385 of "/petsc-3.15.0/include/petscksp.h") was declared deprecated
           ierr = KSPMonitorSet(ksp,(myMonitor)KSPMonitorDefault,vf,
                                               ^

linalg/petsc.cpp(1875): warning #1478: function "KSPMonitorTrueResidualNorm" (declared at line 386 of "/petsc-3.15.0/include/petscksp.h") was declared deprecated
              ierr = KSPMonitorSet(ksp,(myMonitor)KSPMonitorTrueResidualNorm,vf,
                                                  ^

linalg/petsc.cpp(2890): error #165: too few arguments in function call
                 ierr = PetscSFBcastBegin(sf,MPIU_SCALAR,garray,larray); CCHKERRQ(comm,ierr);
                                                                      ^

linalg/petsc.cpp(2891): error #165: too few arguments in function call
                 ierr = PetscSFBcastEnd(sf,MPIU_SCALAR,garray,larray); CCHKERRQ(comm,ierr);
                                                                    ^

**Comment by stefanozampini** [comment]
It's already in a PR https://github.com/mfem/mfem/pull/1963 ;-)

**Comment by stefanozampini** [comment]
@adam-sim-dev You can cherry-pick this commit while waiting for the PR to be merged https://github.com/mfem/mfem/pull/1963/commits/488e3f02a34e428ca6cbc4d20b128485341a80bd
