### ISSUE TITLE
Inconsistent node ordering when using boundary face integrators?

### ISSUE THREAD

**Issue by F3dR19** [mfem/mfem#2144]
Hi all,

When assembling a `BlockNonlinarForm` including some face boundary integrators, there are some issues in the way the contribution in the assembled local element matrices gets mapped to the global one (often triggering segfaults).
After some digging in the code, I reckon the culprit lies in `BlockNonlinearForm::ComputeGradientBlocked`, specifically [at line 949](https://github.com/mfem/mfem/blob/05ee2aaa8b76a44c07bc779f923d2676792b1eed/fem/nonlinearform.cpp#L949) of `nonlinearform.cpp`. I report a snippet of the code for ease of reference:
```
      for (int i = 0; i < mesh->GetNBE(); ++i)
      {
         const int bdr_attr = mesh->GetBdrAttribute(i);
         if (bdr_attr_marker[bdr_attr-1] == 0) { continue; }

         tr = mesh->GetBdrFaceTransformations(i);
         if (tr != NULL)
         {
            for (int s = 0; s < fes.Size(); ++s)
            {
               fe[s] = fes[s]->GetFE(tr->Elem1No);
               fe2[s] = fe[s];

               fes[s]->GetElementVDofs(i, *vdofs[s]);     // <---------- Incriminated line

            [...]
```
I think the problem is that `i` is an arbitrary index, which doesn't "see" the mesh internal ordering of the faces.
Checking against [some similar code](https://github.com/mfem/mfem/blob/05ee2aaa8b76a44c07bc779f923d2676792b1eed/fem/nonlinearform.cpp#L887), it seems like substituting that line with `fes[s]->GetElementVDofs(tr->Elem1No, *vdofs[s]);` should do the trick, but I just wanted to double-check this with you in case I was missing something.

Thank you in advance!
Fede

**Comment by jandrej** [comment]
This code path in the second link should be called when assembling integrators which are discretized on an L2 space (hence the term face-nonlinear-form-integrator -> `fnfi`). So there is a notion of "element 1" and "element 2". 

The first code link shows the code path for a boundary face integrator `bnfi`.

Can you provide a minimal failing example to reproduce the issue?

**Comment by F3dR19** [comment]
Sorry for the confusion: the question is not about when to use face integrators vs _boundary_ face integrators; rather, I wanted to point out that I think there is an issue in the way boundary face integrators are handled by block non linear forms. Particularly, in the way the contributions from the (local) element matrices are mapped to the global matrix during assembly.
This issue only occurs for _boundary_ face integrators, while face integrators are fine, and I believe the reason behind this lies in the difference between the two lines of code I linked.

I cooked up a MWE (see below) to illustrate the problem. I'm considering a simple mesh with 2 triangular elements, one associated to the nodes with indices (0,1,3), and the other with (0,3,2). When integrating along the face (2,3), the final matrix shows contributions to node 1, which shouldn't happen (1 belongs to the other element, which doesn't contain that face, hence the basis function associated to 1 shouldn't have support on (2,3)). When integrating along the face (0,1), instead, a segfault is triggered.


Hope this helps,
Fede

[bug_MWE.zip](https://github.com/mfem/mfem/files/6264109/bug_MWE.zip)


```
#include "mfem.hpp"

using namespace std;
using namespace mfem;

// Just a dummy integrator that turns on contributions only to the (0,0) block
class dummyIntegrator : public BlockNonlinearFormIntegrator{

public:

  virtual void AssembleFaceGrad ( const Array< const FiniteElement * > &  el1,
                                  const Array< const FiniteElement * > &  el2,
                                  FaceElementTransformations &  Trans,
                                  const Array< const Vector * > &   elfun,
                                  const Array2D< DenseMatrix * > &  elmats ){
    elmats(0,0)->SetSize(el1[0]->GetDof(), el1[0]->GetDof());   *elmats(0,0) = 1.;
    elmats(0,1)->SetSize(el1[0]->GetDof(), el1[1]->GetDof());   *elmats(0,1) = 0.;
    elmats(1,0)->SetSize(el1[1]->GetDof(), el1[0]->GetDof());   *elmats(1,0) = 0.;
    elmats(1,1)->SetSize(el1[1]->GetDof(), el1[1]->GetDof());   *elmats(1,1) = 0.;

  }

};





int main(int argc, char *argv[]){

	// read mesh
  string mesh_file = "./tri-square-bug.mesh";

  Mesh *mesh = new Mesh( mesh_file.c_str(), 1, 1 );

  int ordA = 1;
  int dim = mesh->Dimension();

  // create FE spaces
  FiniteElementCollection* AhFEColl = new H1_FECollection( ordA, dim );
  FiniteElementSpace* AhFESpace = new FiniteElementSpace(  mesh, AhFEColl );

  // identify dirichlet nodes on various faces
  Array<int> essTagsN(1); essTagsN[0] = 1; // North
  Array<int> essTagsE(1); essTagsE[0] = 2; // East
  Array<int> essTagsS(1); essTagsS[0] = 3; // South
  Array<int> essTagsW(1); essTagsW[0] = 4; // West

  int numAtt = mesh->bdr_attributes.Max();
  Array<int> essBdrN( numAtt ); essBdrN = 0;
  Array<int> essBdrE( numAtt ); essBdrE = 0;
  Array<int> essBdrS( numAtt ); essBdrS = 0;
  Array<int> essBdrW( numAtt ); essBdrW = 0;
  if ( mesh->bdr_attributes.Size() > 0 ) {
    for ( int i = 1; i <= mesh->bdr_attributes.Max(); ++i ){
      if( essTagsN.Find( i ) + 1 )
        essBdrN[i-1] = 1;
      if( essTagsE.Find( i ) + 1 )
        essBdrE[i-1] = 1;
      if( essTagsS.Find( i ) + 1 )
        essBdrS[i-1] = 1;
      if( essTagsW.Find( i ) + 1 )
        essBdrW[i-1] = 1;
    }
  }

  Array<int> essTDOFN, essTDOFE, essTDOFS, essTDOFW;
  AhFESpace->GetEssentialTrueDofs( essBdrN, essTDOFN );
  AhFESpace->GetEssentialTrueDofs( essBdrE, essTDOFE );
  AhFESpace->GetEssentialTrueDofs( essBdrS, essTDOFS );
  AhFESpace->GetEssentialTrueDofs( essBdrW, essTDOFW );

  std::cout << "***********************************************************\n";
  std::cout << "Nodes on N face: "; essTDOFN.Print(mfem::out, essTDOFN.Size() );
  std::cout << "Nodes on S face: "; essTDOFS.Print(mfem::out, essTDOFS.Size() );
  std::cout << "Nodes on E face: "; essTDOFE.Print(mfem::out, essTDOFE.Size() );
  std::cout << "Nodes on W face: "; essTDOFW.Print(mfem::out, essTDOFW.Size() );
  std::cout << "***********************************************************\n";


  // initialise dummy block non-linear form
  Array< FiniteElementSpace* > feSpaces(2);
  feSpaces[0] = AhFESpace;
  feSpaces[1] = AhFESpace;
  BlockNonlinearForm NLform;
  NLform.SetSpaces( feSpaces );
  NLform.AddBdrFaceIntegrator( new dummyIntegrator(), essBdrN ); // ----------> This adds contributions to the wrong element (3,0,1 which doesn't contain north face 2,3)
  // NLform.AddBdrFaceIntegrator( new dummyIntegrator(), essBdrE ); // ----------> This adds contributions to the wrong element (2,3,0, which doesn't contain east face 1,3)
  // NLform.AddBdrFaceIntegrator( new dummyIntegrator(), essBdrS ); // ----------> This triggers segfault
  // NLform.AddBdrFaceIntegrator( new dummyIntegrator(), essBdrW ); // ----------> This triggers segfault

  // compute its gradient
  Array<int> offsets(3);
  offsets[0] = 0;
  offsets[1] = AhFESpace->GetTrueVSize();
  offsets[2] = AhFESpace->GetTrueVSize();
  offsets.PartialSum();
  BlockVector dummy(offsets); dummy = 0.;
  Operator* J = &NLform.GetGradient( dummy );
  BlockOperator* Jb = dynamic_cast<BlockOperator*>(J);
  // print it
  SparseMatrix K  = *( dynamic_cast<SparseMatrix*>( &Jb->GetBlock(0,0) ) );
  K.Print();

  delete AhFESpace;
  delete AhFEColl;
  delete mesh;

  return 0;
}

```

**Comment by jandrej** [comment]
I don't think `AddBdrFaceIntegrator` is supported for `BlockNonlinearForm`.

**Comment by jandrej** [comment]
@F3dR19 your suggested fix seems reasonable. Do you want to setup a PR for it? We would also appreciate if you turn your nicely prepared example above into a unit test.

**Comment by v-dobrev** [comment]
This is a bug: `i` is an index of a boundary element and cannot be used in `GetElementVDofs` which expects an element index. As pointed out already, the correct element index is the index of the element adjacent to the boundary element `i` which can be obtained from `tr->Elem1No`.

**Comment by jandrej** [comment]
ping @F3dR19

**Comment by tzanio** [comment]
discussion continued in #2191
