### ISSUE TITLE
Periodic mesh with GMSH

### ISSUE THREAD

**Issue by vikramsg** [mfem/mfem#215]
I am trying to generate meshes using GMSH to use. I started by trying to replicate the periodic-square.mesh in data. This is the mesh I came up with.

```
$MeshFormat
2.2 0 8
$EndMeshFormat
$Nodes
16
1 -1 -1 0
2 1 -1 0
3 -1 1 0
4 1 1 0
5 1 -0.33333333333 0
6 1 0.33333333333 0
7 0.33333333333 1 0
8 -0.33333333333 1 0
9 -1 0.33333333333 0
10 -1 -0.33333333333 0
11 -0.33333333333 -1 0
12 0.33333333333 -1 0
13 -0.33333333333 0.33333333333 0
14 0.33333333333 0.33333333333 0
15 -0.33333333333 -0.33333333333 0
16 0.33333333333 -0.33333333333 0
$EndNodes
$Elements
9
1 3 2 5 9 3 9 13 8
2 3 2 5 9 8 13 14 7
3 3 2 5 9 7 14 6 4
4 3 2 5 9 9 10 15 13
5 3 2 5 9 13 15 16 14
6 3 2 5 9 14 16 5 6
7 3 2 5 9 10 1 11 15
8 3 2 5 9 15 11 12 16
9 3 2 5 9 16 12 2 5
$EndElements
```
The problem is that unlike the MFEM mesh format, the mesh reader forces all boundaries to be treated as physical boundaries even though I did not define any boundaries in GMSH. So, it is not treated as periodic boundaries. 

How can I fix this?

**Comment by tzanio** [comment]
Hi @vikramsg, 

I'm not sure if GMsh supports periodic meshes. That requires separation of mesh topology and geometry, as well as support for discontinuous spaces for the geometry part.

An example of how this is done in MFEM is here: https://github.com/mfem/mfem/issues/205

Tzanio

**Comment by vikramsg** [comment]
I just naively assumed that giving no boundary would make the code assume that the boundaries are periodic. On the other hand, it turns out GMSH actually supports periodic meshes.

[http://onelab.info/pipermail/gmsh/2016/010652.html](url)

But I don't think the gmshreader in MFEM understands the periodic tags. So at least for now I think I would have to convert the gmsh file to MFEM mesh format. The output of the periodic tags in GMSH seems to provide the periodic nodes.

But I am not yet sure I get how the periodic mesh works. Here's a sample mesh file I created of 4 elements.

```
dimension
2

# format: <attribute> <geometry type> <vertex 0> <vertex 1> ...
elements
4
1 3 0 1 3 2
2 3 1 0 2 3
3 3 2 3 1 0
4 3 3 2 0 1

boundary
0

vertices
4

nodes
FiniteElementSpace
FiniteElementCollection: L2_T1_2D_P1
VDim: 2
Ordering: 1

-1 -1
0 -1
-1 0
0 0

0 -1
1 -1
0 0
1 0

-1 0
0 0
-1 1
0 1

0 0
1 0
0 1
1 1
```

This is similar to periodic-square.mesh but with 4 elements. To me, it seems to be the correct format, but MFEM does not seem to understand it. 

Any pointers. Thanks.

**Comment by tzanio** [comment]
Hi @vikramsg, you need at least 3x3 elements to have a periodic mesh. Otherwise I think your example looks good.

**Comment by tzanio** [comment]
Hi @vikramsg, were you able to get things working?

**Comment by vikramsg** [comment]
Sorry I got sidetracked with something else. I haven't yet tested it, but based on your comments I am assuming it is fine. If I encounter problems maybe I can open this again. 

Thanks,
Vikram

**Comment by MarkShephard** [comment]
I know that Ken Jansen does a number of problems that require periodic meshes and used Simmetrix mesh generator to get various cases. We can get team members a license for us on the project if desired. (They also create curved meshes, mixed meshes, boundary layers, etc.)
