### ISSUE TITLE
 FiniteElementSpace::BuildDofToArrays(): Suspected memory issue.

### ISSUE THREAD

**Issue by woutertonnon** [mfem/mfem#2152]
Hello all,

I am using a finite-element space based on first-order `ND_FECollection` on a simple mesh in 2D. I noticed that `FiniteElementSpace::GetElementForDof()` returns `-1` for certain DoF's. I tracked this back through the code and noticed that in `FiniteElementSpace::BuildDofToArrays()`, there is a loop over all the elements in the mesh. Using the ElementToDofTable, the DoF's associated to each element are found and used to define the DofToElementTable, i.e. `dof_elem_array[dofs[j]]` is used. However, in the case of the above-specified FiniteElementSpace, ElementToDofTable can return negative values for the DoFs, which seems to be associated to the orientation of the edge with respect to the element. This means that the behaviour of `dof_elem_array[dofs[j]]` is undefined as I understand. An easy solution would be to replace all `dofs[j]` in `FiniteElementSpace::BuildDofToArrays()` by `abs(dofs[j])`. Let me know what you think.

**Comment by mlstowell** [comment]
Hello, @woutertonnon,

This was a good catch. I don't know how this bug has persisted for so long. I suppose this method hasn't been tested with ND and RT spaces. The correct fix is to replace `dofs[j]` with `-dofs[j]-1` when `dofs[j]` is negative.

Thanks for pointing this out.
Best wishes,
Mark

**Comment by tzanio** [comment]
Discussion continued in #2153
