### ISSUE TITLE
Missing DenseMatrix::Swap

### ISSUE THREAD

**Issue by ebchin** [mfem/mfem#2157]
There currently isn't a `DenseMatrix::Swap()` function implemented.  This leads to an issue when e.g. `DenseTensor::Swap()` is called:
https://github.com/mfem/mfem/blob/9676e98f8977801c8475da46c46ea0b68df0a9fc/linalg/densemat.hpp#L884-L888

In `DenseTensor::Swap()`, `tdata` and `nk` are swapped, but `Mk` (a `DenseMatrix`) is not.  Subsequently, when e.g. `DenseTensor::SizeI()` or `DenseTensor::SizeJ()` are called on the swapped `DenseTensor`s, they can return the wrong sizes (since they depend on the size of `Mk`).

Is there a reason `DenseMatrix::Swap()` isn't implemented?  If not, I'd be happy to put one together and create a pull request.

**Comment by v-dobrev** [comment]
Hi @ebchin,

It looks like `DenseTensor::Swap` was a recent addition in #2016 and the issue you pointed out was not noticed during review. Thank you for bringing it to our attention. Feel free to propose a fix in a PR.

cc: @pazner.

**Comment by tzanio** [comment]
Discussion continued in #2165.
