### ISSUE TITLE
Report on building MFEM 4.2 under CYGWIN

### ISSUE THREAD

**Issue by Marshdweller** [mfem/mfem#2158]
This is a report on building MFEM 4.2 under CYGWIN 2.11.2(0.329/5/3).
I noticed that the same building errors persist comparing to previous versions of MFEM.
See related issues
[https://github.com/mfem/mfem/issues/984](https://github.com/mfem/mfem/issues/984)
[https://github.com/mfem/mfem/pull/1828](https://github.com/mfem/mfem/pull/1828)
I use CMake building system.

The two fixes are needed.

1. Change std++11 to gnu++11

In CMakeLists.txt replace 

```
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
```

with 

`set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=gnu++11")`

Otherwise, CYGWIN's g++ will complain about 'strdup' and other functions.

2. Disable definitions from CYGWIN's ctypes.h (e.g. '_B'), which spread to user code. It looks like a CYGWIN bug.
The typical error is that
```
/cygdrive/c/home/dev/mfem-4.2/fem/coefficient.hpp:1204:28: error: expected ‘,’ or ‘...’ before numeric constant
    void SetB(const Vector &_B) { B = _B; BCoef = NULL; }
```
                            ^
I include the following file

```
#ifndef DISABLE_CYGWIN_DEFS
#define DISABLE_CYGWIN_DEFS

#undef _U
#undef _L
#undef _N
#undef _S
#undef _P
#undef _C
#undef _X
#undef _B

#endif 
```

to

bilininteg_vecmass.cpp
coefficient.cpp
(maybe a couple of others, I don't remember)

I hope this helps someone.

P.S. I wonder if it is possible to detect CYGWIN and do it automatically.

P.P.S. 
Cygwin's mpicxx is broken. This is a symlink to mpic++, which calls something like 'g++ [... ] -lmpic -lmpi_cxx [..]'. The thing is that mpi_cxx is not in the Cygwin distro anymore, 
[see here](http://cygwin.1069669.n5.nabble.com/libmpi-cxx-dll-a-missing-td142324.html). So I removed -lmpi_cxx from mpic++. 

FindMPI failed during CMake configuration. I could not figure out the reason and just commented it out. All needed libraries come with mpicxx anyway.

Regards,
M

**Comment by tzanio** [comment]
Addressed (at least partially) in #2236
