### ISSUE TITLE
Getting element attribute based on index into GridFunction

### ISSUE THREAD

**Issue by rmvega1025** [mfem/mfem#2159]
So I am doing something like this:

for ( int i = 0; i < gf.Size(); i++ )
{
   ...
}

where gf is a GridFunction. Within each iteration of the loop, I was wondering if there was a way to get the element index associated with the GridFunction index (i in the loop above). The reason is that I need to set some other parameter inside the loop depending on the element attribute, which I could easily get if I had the element index.

**Comment by psocratis** [comment]
Hi @rmvega1025 , 

Would it work if instead of a loop through the dofs you do a loop through the elements and get the dofs like this? 

````cpp
   // loop through elements
   for (int iel = 0; iel<mesh.GetNE(); iel++)
   {
      Array<int> elem_dofs;
      fespace.GetElementDofs(iel,elem_dofs);
      for (int i = 0; i<elem_dofs.Size(); i++)
      {
         int dof = elem_dofs[i];
         // handle possible negative orientation
         int j = (dof >= 0) ? dof : -dof - 1; 
         // value of the gridfunction 
         double value = gf(j);
         // ......  
      }
   }
````

Hope this helps. 

Socratis

**Comment by rmvega1025** [comment]
Yes. I suppose that would work, but for reasons I cannot remember at the moment, I think I was trying to avoid that.

**Comment by v-dobrev** [comment]
Generally, a degree of freedom (dof) `i` can belong to multiple elements (e.g. dofs associated with mesh vertices). If you only want to look at the first element that contains a dof, you can use `gf.FESpace()->GetElementForDof(i)`; to use this method, you'll need to call `gf.FESpace()->BuildDofToArrays` once before the `i` loop.
