### ISSUE TITLE
-march=native option not supported on powerpc

### ISSUE THREAD

**Issue by lee218llnl** [mfem/mfem#216]
It looks like mfem's build system automatically sets -march=native for the GNU compilers. However, this is an x86-specific option and give an error on PowerPC systems:

'''[lee218@ray23:Crandom]$ uname -a
Linux ray23 3.10.0-514.2.2.2chaos.ch6.ppc64le #1 SMP Wed Jan 11 16:59:26 PST 2017 ppc64le ppc64le ppc64le GNU/Linux
[lee218@ray23:blueos_3_ppc64le_ib]$ gcc -march=native -Q --help=target
gcc: error: unrecognized command line option '-march=native'
'''

Here are a few relevant links:

https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html
https://gcc.gnu.org/onlinedocs/gcc/RS_002f6000-and-PowerPC-Options.html#RS_002f6000-and-PowerPC-Options

Can the build system be updated such that -march=native is only set when building for x86?

**Comment by v-dobrev** [comment]
I believe on PowerPC you can use `-mcpu=native -mtune=native` instead. The options in that makefile ([`miniapps/performance/makefile`](https://github.com/mfem/mfem/blob/master/miniapps/performance/makefile)) are meant to be just an illustration for the specific case of GCC compiler and Intel processor.

**Comment by lee218llnl** [comment]
The problem that I see is that this option is not just an illustration, it is actually set and will be thrown at g++ by default. That said, no one will be able to just download mfem and build it on PowerPC without tripping on this error and having to modify the makefile. My suggestion here is to not set this option for all g++ invocations, either removing it entirely or only setting it when run on x86.

**Comment by tzanio** [comment]
@lee218llnl, please see and comment on PR #219.

**Comment by lee218llnl** [comment]
#219 looks good to me, thanks!

**Comment by tzanio** [comment]
Resolved by cbb74a91f99b69a6f6672497652ab42cd468d7b7.
