### ISSUE TITLE
Question: sending keystrokes for GLVis from MFEM

### ISSUE THREAD

**Issue by kmittal2** [mfem/mfem#217]
Hi All,

I see that in MFEM we use an osockstream to send data to a running instance of glvis and plot mesh and solution. Is there a way to add keystrokes to this so that I can automatically plot it with desired attributes? 
For example: I would like to add the four keystrokes: JREM, which I can manually do right now from the terminal by using:
glvis -m dummy.mesh -k "JREM"

Thanks,
Ketan

**Comment by tzanio** [comment]
Yes, see 

https://github.com/mfem/mfem/blob/1569425857975d7c961b97d09c300da09aad9f82/examples/ex17.cpp#L299

or more generally:

https://github.com/mfem/mfem/search?utf8=%E2%9C%93&q=KEYS

**Comment by kmittal2** [comment]
Thanks Tzanio
