### ISSUE TITLE
How to get trial_tdof_list, test_tdof_list?

### ISSUE THREAD

**Issue by Andr00dz** [mfem/mfem#2170]
Hi all, 

I want to use the function `mfem::ParMixedBilinearForm::FormRectangularLinearSystem` [(link to documentation)](https://mfem.github.io/doxygen/html/classmfem_1_1ParMixedBilinearForm.html#a363104e5c29307af9860bfcdcce98faf).
It requires a `trial_tdof_list` and `test_tdof_list`. In the documentation, I did not find any hints on how to generate these lists and what size or entries are expected in these lists.

I have an array `bdr_attr_is_ess`, which marks some attributes on the boundary as essential on the trial space. On the test space, there is no essential boundary. Is there a simple function, similar to `mfem::ParFiniteElementSpace::GetEssentialTrueDofs` which creates a `trial_tdof_list` / `test_tdof_list` for a given `bdr_attr_is_ess`?

If there is not such a function, how can the lists be generated manually?

Thanks in advance,
Andreas

**Comment by pazner** [comment]
If there are no essential test DOFs, you can just use an empty array:
```c++
Array<int> test_tdof_list; // empty list since no essential test dofs
```
Then, you can get the essential trial DOFs using `ParFiniteElementSpace::GetEssentialTrueDofs` just as you mention:
```c++
Array<int> trial_tdof_list;
trial_fes.GetEssentialTrueDofs(bdr_attr_is_ess, trial_tdof_list);
```
The resulting arrays `test_tdof_list` and `trial_tdof_list` should do you what you want.

**Comment by Andr00dz** [comment]
Thanks for the fast reply!  

> ```c++
> Array<int> test_tdof_list; // empty list since no essential test dofs
> ```
> ```c++
> Array<int> trial_tdof_list;
> trial_fes.GetEssentialTrueDofs(bdr_attr_is_ess, trial_tdof_list);
> ```
This solved my problem. I was not aware that with `test_tdof_list` the essential tdofs are ment. Now its clear.
