### ISSUE TITLE
Make check failed on macOS 11.2.3

### ISSUE THREAD

**Issue by jediyoda36** [mfem/mfem#2171]
I just cloned the master branch of this repo, and try to install serial version on my macbook pro (with intel cpu).  It was built successfully.

But when I run `make check` command, it failed. And all make test was failed too.
![image](https://user-images.githubusercontent.com/13287220/114731796-9a92a100-9d74-11eb-9822-31f587e9eed2.png)
![image](https://user-images.githubusercontent.com/13287220/114731953-b7c76f80-9d74-11eb-885b-fd3ec6378bfd.png)

The older version of mfem (maybe cloned 3 or 4 months ago) is running well on my mac.

**Comment by v-dobrev** [comment]
I cannot reproduce these errors. The numbers on your screenshots look the same as what I get. If you run the example like this:
```console
./ex1 && echo "exit code = $?"
```
do you get a non-zero exit code? If you get 0, then you can just ignore the errors -- I suspect it has something to do with how we run the examples from inside `make` and that is probably due to recent changes in `make`, `/bin/sh`, or `time` commands.

**Comment by jediyoda36** [comment]
@v-dobrev the exit code is 0.
![image](https://user-images.githubusercontent.com/13287220/114740460-733fd200-9d7c-11eb-9f53-67474ffd9a38.png)

**Comment by v-dobrev** [comment]
Okay, then you can just ignore these errors. I don't have a machine with this macOS version, so I cannot debug this at the moment. I'm not sure if someone else on the team has this macOS version.

Thanks for reporting this issue. We'll try to resolve it in the near future.

**Comment by jediyoda36** [comment]
@v-dobrev ok, thanks for the reply!

**Comment by jediyoda36** [comment]
@v-dobrev one more question, does mfem now support Apple M1 chip?

**Comment by tzanio** [comment]
> does mfem now support Apple M1 chip?

Yes, cc: @jandrej

**Comment by tzanio** [comment]
@jediyoda36, I believe we fixed the original issue you reported.

Can you please try https://github.com/mfem/mfem/pull/2276?

**Comment by jediyoda36** [comment]
@tzanio 
Ok, I'll try it later!
