### ISSUE TITLE
Trimmer miniapp and curved meshes

### ISSUE THREAD

**Issue by sebastiangrimberg** [mfem/mfem#2177]
Hi MFEM team, big fan of the library so first off wanted to thank you all on that front. 

I'm trying to trim elements from an existing serial mesh using the [trimmer](https://github.com/mfem/mfem/blob/f4a99fa854c55554c1a48879077ef34ff69f6188/miniapps/meshing/trimmer.cpp) miniapp but it appears that after trimming I'm losing the curvature information (the Nodes GridFunction does not get transferred to the new mesh). It seems like this might be a relatively small fix, so I'm wondering if anyone has suggestions on how to handle this? It would be nice if something along the lines of 

```
trimmed_mesh.SetCurvature(mesh.GetNodalFESpace()->GetMaxElementOrder(),
                          mesh.GetNodalFESpace()->IsDGSpace(),
                          mesh.SpaceDimension(),
                          mesh.GetNodalFESpace()->GetOrdering());
VectorGridFunctionCoefficient NodesCoef(mesh.GetNodes());
trimmed_mesh.GetNodes->ProjectCoefficient(NodesCoef);
```

might work but I think this requires that the two grid functions are defined on the same mesh which is not the case here. Thanks for your help!

**Comment by kmittal2** [comment]
Hi @sebastiangrimberg,

I have encountered this in the past and I have used something like the code below to copy nodal gridfunction values from the original mesh (`x_mesh`) to the trimmed mesh (`x_mesh_trim`):
```
int recv = 0;
Array<int> vdofs_donor, vdofs_recv;
for (int i = 0; i < mesh.GetNE(); i++) {
    if (trim_flag[i] == 1) { //if element from original mesh was trimmed
        Vector x_donor;
        x_mesh.FESpace()->GetElementVDofs(i, vdofs_donor);
        x_mesh.GetSubVector(vdofs_donor, x_donor);
        x_mesh_trim.FESpace()->GetElementVDofs(recv, vdofs_recv);
        x_mesh_trim.SetSubVector(vdofs_recv, x_donor);
        recv++;
    }
}
```
Note `trim_flag` is an Array that indicates which elements from the initial mesh were trimmed.

**Comment by sebastiangrimberg** [comment]
Thank you @kmittal2! Exactly what I was looking for, thank you for the quick response. There is no need to do the same thing for the boundary elements as well right?

**Comment by kmittal2** [comment]
I think this should cover the dofs for the boundary elements.

**Comment by sebastiangrimberg** [comment]
I agree, since they're attached to the domain elements. Thanks again!

**Comment by psocratis** [comment]
Hi, 

I am just going to through it out there. I needted something similar too in the past and I used the following,

````cpp
   mesh.EnsureNodes();
   GridFunction * nodes = mesh.GetNodes();
   VectorGridFunctionCoefficient gf_nodes(nodes);
   int order = nodes->FESpace()->GetOrder(0);
   if (order > 1)
   {
      trimmed_mesh.SetCurvature(order, true, 3, Ordering::byVDIM);
   }
   trimmed_mesh.Transform(gf_nodes);
````
which is probably doing the same thing as above, however, I haven't tested it thoroughly. @kmittal2 maybe it would be good if we add this in trimmer? 

Thanks, 

Socratis

**Comment by mlstowell** [comment]
It looks like we all jumped on this at once. I had already implemented something similar to @kmittal2 's suggestion but mine used additional memory which was not necessary. This PR #2179 is quite similar to @kmittal2 's algorithm but without the `trim_flag` array.

**Comment by kmittal2** [comment]
oh wow! Thanks for making a PR for this so quick @mlstowell

**Comment by mlstowell** [comment]
Thank you, @kmittal2 , I was caching the local vectors initially which needed much more memory and was totally unnecessary. I like your solution.

**Comment by tzanio** [comment]
Discussion continued in  #2179
