### ISSUE TITLE
Axisymmetric simulation using wedge geometry with periodic surfaces

### ISSUE THREAD

**Issue by sanjeev1407** [mfem/mfem#2180]
Hi,

I want to solve Maxwell equations (similar to the one in "Joule" miniapp) for an axisymmetric problem. I wanted to know if we can use for example a 5 degree wedge geometry with periodic surface constraint to simulate the entire cylindrical problem?

-> I know we can apply periodic boundaries in MFEM by defining it in the mesh. But for vector fields(say Electric field), does MFEM takes care of the rotation needed to be applied on the vectors at the periodic surfaces?
-> Do we need to do anything else besides defining periodic surfaces?

**Comment by mlstowell** [comment]
Hello, @sanjeev1407,

If your 5 degree wedge geometry will include the axis of rotation then you may have trouble. Unfortunately, MFEM does not yet support Nedelec basis functions on wedge elements. If the axis will not be part of the domain you can use hexahedral elements without any problems. In this case the periodic boundary conditions will automatically ensure that the vectors do match properly even though the periodic surfaces are rotated with respect to each other.

Another option is to perform the simulation in 2D. If you don't expect any field variation in the angular direction this might be the best option. The only trick is to place factors of 'r' in the proper locations and everything should go smoothly. This scheme is particularly useful if you expect your electric field to either remain confined to the rz plane or to be directed parallel to the angular direction. You can certainly support both polarizations in 2D but the equations become a little more difficult to setup.

I'd be happy to advise you further if you can give me a few more details.

Best wishes,
Mark

**Comment by sanjeev1407** [comment]
Hello Mark,

Thanks for the detailed explanation. I am attaching a snapshot of the 3D geometry that works well and I am getting the expected results. The geometry has a number of parallel coils surrounding a cylindrical conductor. I am also attaching a snapshot of the governing equations that I am solving for E and B. For the setup, E is purely in azimuthal direction while B is in r-z plane. The electro-magnetic field is driven by a source current density Jc which is applied in the coil volumes in the azimuthal direction.

Our main objective in future is to do 3D simulations with actual helical coil configuration. But we thought it would be nice to have a 2D axisymmetric capability to have quicker results, provided it does not require too much work.

For the 2D axisymmetric setup, It would be helpful if you could advise on : 1) how to modify the operators that I need for my equations (curl curl operator and curl operator)?
2) which elements to select for E and B? (Since E would be in angular direction, so it would be basically a scalar. While B would be a vector)

![governing_eqn](https://user-images.githubusercontent.com/71282454/115276377-8d750980-a108-11eb-95ca-df7f5481e131.png)

![parallel_coil_mesh](https://user-images.githubusercontent.com/71282454/115276398-95cd4480-a108-11eb-80a8-f7f63923b918.JPG)


Thanks,
Sanjeev

**Comment by mlstowell** [comment]
Hi, @sanjeev1407 ,

Sorry for the delay. I was pull away to other projects. I have a couple of example codes that demonstrate the use of cylindrical coordinates systems in MFEM. The curl curl example just came together today. Have a look at [ex13p-cyl-3d.cpp](https://github.com/mfem/mfem/blob/cyl-coords-dev/examples/ex13p-cyl-3d.cpp) in the `cyl-coords-dev` branch. This program computes the electromagnetic eigenmodes in a 2D geometry by setting up separate eigenvalue problems for two possible polarizations. It is not the same equation that you will be solving but it does involve the same operators. Specifically, have a look at lines 242-254 (shown here as well):
```
   ParBilinearForm *aphi = new ParBilinearForm(&fespace_ndp);
   aphi->AddDomainIntegrator(new MassIntegrator(rhoInvCoef));
   aphi->AddDomainIntegrator(new DiffusionIntegrator(rhoCoef));
   aphi->Assemble();
   aphi->EliminateEssentialBCDiag(ess_bdr_phi, 1.0);
   aphi->Finalize();

   ParBilinearForm *mphi = new ParBilinearForm(&fespace_ndp);
   mphi->AddDomainIntegrator(new MassIntegrator(rhoCoef));
   mphi->Assemble();
   // shift the eigenvalue corresponding to eliminated dofs to a large value
   mphi->EliminateEssentialBCDiag(ess_bdr_phi, numeric_limits<double>::min());
   mphi->Finalize();
```
These are essentially the same operators you'll need. I'd be happy to discuss this further to clarify anything you might be curious about.

Best wishes,
Mark

**Comment by sanjeev1407** [comment]
Hello,

Thanks for your suggestions. I managed to solve the 2D axi-symmetric formulation of my governing equations on the line of your suggestions. Everything seems to be working fine and the results match with the 3D code that I had written earlier.

Thanks so much!

Regards,
Sanjeev
