### ISSUE TITLE
Memory manager errors when using FormLinearSystem

### ISSUE THREAD

**Issue by artv3** [mfem/mfem#2193]
When forming the linear system using `FormLinearSystem` methods; objects such as X/B  may have different lifespans than x/b. The different lifespans can cause errors within the memory manager when X/B are destroyed before x/b. 

Also: The verify at mem_manager.cpp:1255 needs to allow d_mt == MemoryType::DEFAULT

**Comment by tzanio** [comment]
Addressed in #2203
