### ISSUE TITLE
MFEM new capability: energy shifted eigenmode calculation

### ISSUE THREAD

**Issue by cekim7** [mfem/mfem#2199]
Dear MFEM developers, 

I would like to learn a prospect of having this new module in MFEM. 
The attached snapshot is from COMSOL Semiconductor module, Schrödinger equation solver. 

![image](https://user-images.githubusercontent.com/60420458/116140465-38973d00-a68c-11eb-8fa3-ed5d20de4ae2.png)

It allows to compute energy-shifted eigenmodes thru an arbitrary potential landscape in 3D.
I am curious if MFEM currently support this capability. 

I look forward to hearing about this. Thank you for the nice development effort!

Best regards,
CE

**Comment by cekim7** [comment]
Hi Mark,

The eigenmode solution is one thing, but how can we set the boundary
condition of incoming wave, in terms of kinetic energy of the particle
(let's say it is a bosonic particle influx).
Could you shed some light on how to modify ex11p.cpp to set the contant
energy of incoming wave-particle?


Best regards,
CE

**Comment by mlstowell** [comment]
Hi, @cekim7,

Eigenvalue problems would only be appropriate for bound systems and in such cases the only suitable boundary conditions would be for the probability density to or its normal derivative to be zero.

It sounds like you're thinking of a scattering problem. This would be more like ex25p. However, I would probably recommend a scattered field formulation with a PML boundary condition similar to that in ex25p. If you're not familiar with the scattered field formulation you start with a known solution in a simple domain such as a plane wave in empty space. Then you add your potential as if it is a perturbation to empty space and solve for the difference between the known solution and the full solution. In this formulation the source is produced by the known solution interacting with the potential and the computed solution appears as a wave propagating away from the potential. I don't think we have an example of this in MFEM at the moment but it wouldn't be hard to setup.

Best wishes,
Mark
