### ISSUE TITLE
Legendre polynomials as basis for H1 space

### ISSUE THREAD

**Issue by martemyev** [mfem/mfem#22]
Dear all,

I was recently trying to switch from Lagrange basis that is used for H1 to Legendre, and I seem to understand how to do that, but it looks like I need to change MFEM code for that and rebuild the library - some changes in `Poly_1D` would be needed, and `H1_(Segment|Quadrilateral|Hexahedron)Element` classes are heavily based on it, so I can't, for example, inherit from `Poly_1D` and then feed `H1_*Element` object with an instance of my `Poly_1D` derived class. One solution would be to pass a pointer to a `Poly_1D` (or derived class) object to the `H1_*Element` constructor - the same way it's done for many other functions in MFEM. It doesn't seem hard, but before I start doing that for my project, I am wondering if there is a better solution, and, maybe, I am just wasting time. So the question is - how to get Legendre basis functions in H1 spaces on Segment, Quadrilateral and Hexahedron elements?

Thank you,
Mikhail

**Comment by martemyev** [comment]
I think I might mixed something up trying to make Legendre finite elements work. I just figured that I most likely need Lagrange basis computed at Gauss-Lobatto-Legendre points - not the Legendre polynomials (or at least, not in H1 space).

Thanks,
Mikhail

**Comment by tzanio** [comment]
Hi Mikhail,

You probably know that, but Gauss-Lobatto is the default basis for H1 in mfem :)

Tzanio

**Comment by martemyev** [comment]
Hi Tzanio,

Yes, I figured that, but thanks for mentioning anyway. I managed to implement some version of the spectral element method with Gauss-Lobatto Lagrange basis and Gauss-Lobatto quadrature rule for assembling matrices, and it seems to work well so far. So, thank you again!

Best,
Mikhail

**Comment by tzanio** [comment]
Hi Mikhail,

I'm glad you got it working. Please let us know if you have any further questions.

Tzanio

**Comment by vryy** [comment]
Hello, is there plan to integrate Legendre basis to MFEM soon?

**Comment by pazner** [comment]
Do you mean a nodal basis using Gauss-Legendre points, or a modal basis with Legendre polynomials?

In case you mean the former, that is already available in MFEM for DG (and can be used to construct tensor-product bases for RT and ND spaces).

**Comment by vryy** [comment]
Hi @pazner I mean the modal, hierarchic basis with Legendre polynomials, like what is typically used in the p-version of FEM

**Comment by tzanio** [comment]
Hi @vryy, 

We don't have immediate plans to add hierarchical basis to MFEM (that will require some work).

Can you share what would you like to use them for?

Tzanio

**Comment by vryy** [comment]
@tzanio I just want to know the status, because this question is initiated 7 years ago. In my own opinion, raising order with hierarchic basis is not better than IGA, it might be easier on the side of implementation. Besides, it works with unstructured mesh :)

**Comment by tzanio** [comment]
To clarify -- using a hierarchic basis is not a requirement for $p$- or $hp$-adaptivity. MFEM can do those with the nodal bases we use.
