### ISSUE TITLE
How to construct a preconditioner P*x := a*M*x+ Ainv*x

### ISSUE THREAD

**Issue by Andr00dz** [mfem/mfem#2201]
Hi,

I want to construct a preconditioner for `GMRES` with the action `P*x := a*M*x+ Ainv*x` , where `a`  is a scalar, `M` is a mass matrix, and `Ainv*x` is the action stemming from `HypreBoomerAMG`.  Since `Ainv` does not exist explicitly, I cannot use `ParAdd(aM, Ainv)` to constuct `P`.

How can I construct this kind of precondtioner?

**Comment by pazner** [comment]
When I have implemented similar things in the past, my approach has been to create a class that derives from `Solver` and overrides the `Mult` function, which computes the action of `P`.

**Comment by Andr00dz** [comment]
This is my current derived class from `Solver`
```
class SumSolver : mfem::Solver
{
  private:
    const mfem::Operator *A;
    const mfem::Operator *B;
    double a;
    double b;

  public:
    SumSolver(const mfem::Operator *A_, const mfem::Operator *B_, double a_, double b_)
      : mfem::Solver(A_->Height(), A_->Width(), false)
      {
        MFEM_VERIFY(A_->Height() == B_->Height(),
                    "incompatible Operators: A->Height() = " << A_->Height()
                    << ", invB->Height() = " << B_->Height());
        MFEM_VERIFY(A_->Width() == B_->Width(),
                    "incompatible Operators: A->Width() = " << A_->Width()
                    << ", invB->Width() = " << B_->Width());
        A = A_;
        B = B_;
        a = a_;
        b = b_;
      };

    void Mult(const mfem::Vector &x, mfem::Vector &y) const
    { // y = a * Ax + b * Bx
      y = 0.0;
      mfem::Vector Ax(A->Height());
      mfem::Vector Bx(B->Height());
      A->Mult(x,Ax);
      B->Mult(x,Bx);
      y.Add(a, Ax);
      y.Add(b, Bx);
    };
    void SetOperator(const Operator &op) { A = &op;};
    ~SumSolver();
};
```
Building my code produces now the follwoing error: 
`In function SumSolver::SumSolver(mfem::Operator const*, mfem::Operator const*, double, double): undefined reference to vtable for SumSolver`. I think, there is still something missing.

**Comment by pazner** [comment]
The error is because you have `~SumSolver();` without defining the destructor. You can delete that line and it should work.

For efficiency, you may also want to change `Ax` and `Bx` to be mutable data members of the class so that they are not reallocated every iteration.

**Comment by Andr00dz** [comment]
It's working now. Thanks for the help!
