### ISSUE TITLE
compilation error with HIOP

### ISSUE THREAD

**Issue by e-aranda** [mfem/mfem#2204]
Hi,

I am trying to build mfem with HiOP and there is a compilation error in hiop.cpp

    In member function 'virtual void mfem::HiopNlpOptimizer::SetOptimzationProblem(const mfem::OptimizationProblem&)': 
    hiop.cpp:281:62 error: invalid new-expression of abstract class type 'mfem::HiopOptimizationProblem'
       281 |     hiop_problem = new HiopOptimizationProblem(comm_, *problem);
              |                                                                                                             ^ 

I have build HiOP without problem.

**Comment by tzanio** [comment]
Discussion continued in @2235.
