### ISSUE TITLE
Update the sample-runs script to run any new examples and miniapps

### ISSUE THREAD

**Issue by v-dobrev** [mfem/mfem#2213]
Script: https://github.com/mfem/mfem/blob/master/config/sample-runs.sh

Also, update the `sample-runs` script in the internal tests.

**Comment by tzanio** [comment]
Currently missing:

**Miniapps**
- [ ] adjoint
- [ ] gslib
- [ ] navier
- [ ] nurbs
- [ ] shifted
- [ ] solvers
- [ ] tools
- [ ] toys

**Examples**
- [ ] amgx
- [ ] caliper
- [ ] ginkgo
- [ ] hiop
- [ ] pumi
- [ ] superlu

**Comment by v-dobrev** [comment]
Let's use this issue to keep track of some problems with sample runs uncovered in #2224: https://github.com/mfem/mfem/pull/2224#issuecomment-840012326

We should re-open this issue when it is auto-closed by merging #2224.
