### ISSUE TITLE
Floating point exception Error in PETSc for matrix free solution 

### ISSUE THREAD

**Issue by brightzhang91** [mfem/mfem#2220]
Hi :)
I encountered a problem when using `PetscNonlinearSolver` to do the matrix-free solution of a constrained nonlinear problem. I implemented my own `NonlinearFormIntegrator` for the nonlinear material properties, with self-defined `AssembleElementGrad()` and` AssembleElementVector()`.  I created my code in a similar structure as ex10p, except the the block system in the Operator taken by `PetscNonlinearSolver` where `Operator::Mult()` returns a `BlockVector `and` Operator::GetGradient()` returns a `BlockOperator`.  And the `BlockOperator` consists of 2 non-square matrix (such as single-row matrix), which I created as constraints. 

The following error appears  for all matrix-free solutions, with PETSc files rc_ex10p_mf, rc_ex10p_mfop and rc_ex10p_jfnk.  The error message appears after calls to `Operator::Mult()`, ` Operator::GetGradient()` and another  `Operator::Mult()`.
The error is not present with option rc_ex10p (-snes_monitor   -ksp_type minres  -pc_type jacobi ), although still no convergence.

Can anyone advise what could be the possible causes for the problem ? 
Thanks very much ! Bright.
![image](https://user-images.githubusercontent.com/67397441/116998690-81777300-acd6-11eb-83ea-1ba505c418d3.png)

**Comment by stefanozampini** [comment]
Can you run under valgrind and make sure you do not have uninitialized values in the vector computed by the `Nonlinearform::Mult()` method? It is strange it does not happen when solving without matrix free, since also in that case PETSc will use the Mult method to assemble the Newton rhs

**Comment by stefanozampini** [comment]
Another question. If you run using MFEM's nonlinear solver, does it converge?

**Comment by brightzhang91** [comment]
> Can you run under valgrind and make sure you do not have uninitialized values in the vector computed by the `Nonlinearform::Mult()` method? It is strange it does not happen when solving without matrix free, since also in that case PETSc will use the Mult method to assemble the Newton rhs

Hi thanks for replying. I run it with Valgrind and this is the only error message returned.
 I think I always ensure the vector returned from `Nonlinearform::Mult()` doesn't have uninitialized values
by printing    `cout << "residual norm " << Residual.Norml2() <<endl;` to the screen in every call to `Mult()`. 
And this error message appears after the second call to `Mult()`, the first call to `Mult()` looks fine. There is one call to `GetGradient()` between the two.

Bright

**Comment by brightzhang91** [comment]
I'll try to use the MFEM's nonlinear solver.

My `BlockOperator`  for Jacobian has two non-square `SparseMatrix` which I created to impose Lagrange Multipliers. I think this is causing problems and limits scalability. 
My plan is to create two square matrix instead, containing the non-square matrix and filling the rest of entries with zero. So that all subblocks of the `BlockOperator`  are square matrices of the same dimension. Do you think this approach make sense?

Thanks !
Bright

**Comment by stefanozampini** [comment]
Can you try upgrading to the latest PETSc version? Also, which version of MFEM are you using?

>  My plan is to create two square matrix instead, containing the non-square matrix and filling the rest of entries with zero. So that all subblocks of the BlockOperator are square matrices of the same dimension. Do you think this approach make sense?

No

**Comment by brightzhang91** [comment]
> Can you try upgrading to the latest PETSc version? Also, which version of MFEM are you using?
> 
> > My plan is to create two square matrix instead, containing the non-square matrix and filling the rest of entries with zero. So that all subblocks of the BlockOperator are square matrices of the same dimension. Do you think this approach make sense?
> 
> No

Thanks very much for the advice. My PETSc version is 3.13.0 and MFEM version is 4.2.  I'll upgrade to the latest version.

You think I can keep using the non-square constraint matrix in the` BlockOperator` ?
My confusion is with the parallel version, if all subblocks are square matrices of the same dimension , my `Mult()` is like : 
```
void H_Operator::Mult(const Vector &k, Vector &Residual) const
{ 
   int sc = height/2;
   Vector k1(k.GetData() +  0, sc);
   Vector k2(k.GetData() +  sc, sc);
   Vector y1(Residual.GetData() +  0, sc);
   Vector y2(Residual.GetData() +  sc, sc);
   
   L_nonlinear->Mult(k1, y1);  
   L_linear->TrueAddMult(k1, y1, 1.0);
   L_mass->TrueAddMult(k1, y1, 1.0/dt);    
   y1.SetSubVector(ess_tdof_list, 0.0);   
   y2 = k2;
   constraint_.AddMult(k1, y2,1.0);// constraint_ is the subblock  for Lagrange multiplier 
}
```
If my `constraint_ ` is non-square with only 3 rows (then the Operator size is `FESpace()->TrueVSize()+3`),  how do I know the size of k1 and k2 on each processor ? 
And how to assemble the SparseMatrix of `constraint_ ` to form a `HypreParMatrix` , to be a subblock of the ` BlockOperator` ?
like in  `ReducedSystemOperator::GetGradient()`  of ex10p:
 `Jacobian = M->ParallelAssemble(localJ);  // M is the ParBilinearForm with a MassIntegrator`

Sorry for so many questions as I don't have enough understanding of the parallelization in MFEM. Thanks !
Bright
