### ISSUE TITLE
Is it possible to call a function within MFEM_FORALL?

### ISSUE THREAD

**Issue by marc-85** [mfem/mfem#2221]
Hello MFEM community,

I am trying to implement some of operators to support GPU. In order to avoid duplicating code I wanted to call a function within an `MFEM_FORALL` loop but I do not seem to be able to. Is this even possible?

I have tried defining the function to be called with and without `MFEM_DEVICE` specifier. If I don't use it the compiler complains that a host function can't be called from a device function; and if I use it the compiler complains that a device function can't be called from a host function. 

For reference I am using version 4.2 of MFEM and a cuda compiler version 11.2

As an example of what I had in mind I attach the following code:

```cpp
#include "mfem.hpp"
#include <fstream>
#include <iostream>
#include "../src/mfem-4.2/general/forall.hpp"

using namespace std;
using namespace mfem;

MFEM_DEVICE double func(const int i);

int main(int argc, char *argv[])
{
   // 1. Initialize MPI.
   int num_procs, myid;
   MPI_Init(&argc, &argv);
   MPI_Comm_size(MPI_COMM_WORLD, &num_procs);
   MPI_Comm_rank(MPI_COMM_WORLD, &myid);

   // 2. Parse command-line options.
   int blocks = 10;
   const char *device_config = "cpu";
   
   OptionsParser args(argc, argv);
   args.AddOption(&blocks, "-b", "--blocks",
                  "Number of blocks");
   args.AddOption(&device_config, "-d", "--device",
                  "Device configuration string, see Device::Configure().");
   
   args.Parse();
   if (!args.Good())
   {
      if (myid == 0)
      {
         args.PrintUsage(cout);
      }
      MPI_Finalize();
      return 1;
   }
   if (myid == 0)
   {
      args.PrintOptions(cout);
   }

   // 3. Enable hardware devices such as GPUs, and programming models such as
   //    CUDA, OCCA, RAJA and OpenMP based on command line options.
   Device device(device_config);
   if (myid == 0)  device.Print(); 

   int Nblocks = blocks;
   int Ni = 5*5;
   int N = Ni*Nblocks;

   tic_toc.Clear();
   tic_toc.Start();

   Vector u; u.UseDevice(true);
   u.SetSize(N);{auto kk = u.Write();}
   Vector reducedU; reducedU.UseDevice(true);
   reducedU.SetSize(Nblocks);reducedU = 0.;
   
   // set u in device memory
   {
     auto d_u = u.Write();
     MFEM_FORALL_2D(el,Nblocks,Ni,1,1,
     {
       MFEM_FOREACH_THREAD(i,x,Ni)
       {
         if(i+el*Ni==0) d_u[i+el*Ni] = 0.;
	       if(i+el*Ni!=0) d_u[i+el*Ni] = 1./func(i+el*Ni);
       }
     });

     auto d_reducedU = reducedU.Write();
     MFEM_FORALL_2D(el,Nblocks,Ni,1,1,
     {
       MFEM_SHARED double sum;
       sum = 0.;
       MFEM_FOREACH_THREAD(i,x,Ni)
       {
         if( i==0 ) for(int k=0;k<Ni;k++) sum += d_u[k+el*Ni];
       }
       d_reducedU[el] = sum;
     });
   }
   

cout<<"=== Print sum GPU ==="<<endl;
{
  auto h_reducedU = reducedU.HostRead();
  double sum = 0.;
  for(int i=0;i<Nblocks;i++) sum += h_reducedU[i];
  tic_toc.Stop();
  cout<<"Sum: "<<sum<<endl;
  cout<<"It took "<<tic_toc.RealTime()<<" s."<<endl;
}
   MPI_Finalize();

   return 0;
}


MFEM_DEVICE double func(const int i)
{
	return (double)i;
}
```

**Comment by joshessman-llnl** [comment]
Can you try using `MFEM_HOST_DEVICE` instead of `MFEM_DEVICE`?  This will make the function callable from both host and device code.

**Comment by marc-85** [comment]
Hi @joshessman-llnl ,
This worked, many thanks!
I am assuming `MFEM_HOST_DEVICE`  will also work with AMD devices, right? We'd like to make this vendor agnostic.
Thanks, again

**Comment by joshessman-llnl** [comment]
You are correct, see [the AMD HIP docs](https://rocmdocs.amd.com/en/latest/Programming_Guides/HIP-GUIDE.html#function-type-qualifiers) for the corresponding section on execution space annotations

**Comment by marc-85** [comment]
Hi @joshessman-llnl ,
I have another issue with a GPU implementation. During the execution I have a call to a `BilinearForm::AddMult(Vector&, Vector&)`. Both those vectors have memory in device before I call `AddMult` but the output is returned with `MemoryType=HOST`. I assumed that the `BilinearForm:AddMult` would perform the operations on device memory and return it on device too. Is there anything I should specify for that?

I include the bit of code where it happens as an example:
```cpp
  Vector fk,zk; fk.UseDevice(true);zk.UseDevice(true);
  fk.SetSize(dim*vfes->GetNDofs());
  zk.SetSize(vfes->GetNDofs());
  const double *d_flux = flux.Read();
  const double *d_z = z.Read();
  double *d_fk = fk.ReadWrite();
  double *d_zk = zk.ReadWrite();
    
  for(int eq=0;eq<num_equation;eq++)
  {
    MFEM_FORALL_2D(n,dof,dim,1,1,
    {
      MFEM_FOREACH_THREAD(d,x,dim)
      {
        d_fk[n + d*dof] = d_flux[n + d*dof + eq*dof*dim];
        d_zk[n] = d_z[n + eq*dof ];
      }
    });
    // MemoryType(fk) = DEVICE
    // MemoryType(zk) = DEVICE
    Aflux->AddMult(fk, zk);
    // MemoryType(fk) = DEVICE
    // MemoryType(zk) = HOST
  }
```

**Comment by YohannDudouit** [comment]
Hi @marc-85 ,
`BilinearForm::AddMult(Vector&, Vector&)` is `virtual`, so the code in `Aflux->AddMult` probably doesn't compute on device. You should be careful that it doesn't also use invalid host memory for `fk`.

**Comment by marc-85** [comment]
Hi @YohannDudouit,
Thanks for your answer. If I understand correctly, this is not a pure virtual function, and so there is a default definition within MFEM. From `bilinearform.hpp` I can see
```cpp
   /// Add the matrix vector multiple to a vector:  \f$ y += a M x \f$
   virtual void AddMult(const Vector &x, Vector &y, const double a = 1.0) const
   { mat -> AddMult (x, y, a); }
```

and in `bilinearform.cpp`
```cpp
void MixedBilinearForm::AddMult(const Vector & x, Vector & y,
                                const double a) const
{
   if (ext)
   {
      ext->AddMult(x, y, a);
   }
   else
   {
      mat->AddMult(x, y, a);
   }
}
```

What you are saying is that I should implement my own `AddMult`? Should I expect the same behavior with the `NonlinearForm::Mult`?

Very many thanks for all the help. It is really appreciated.

**Comment by YohannDudouit** [comment]
@marc-85 You're right, this is indeed unexpected, one possible explanation is that your `SparseMatrix` is not `Finalized` resulting in the following `HOST` code being run:

https://github.com/mfem/mfem/blob/master/linalg/sparsemat.cpp#L627-L645

**Comment by marc-85** [comment]
@YohannDudouit Calling `BilinearForm::Finalize()` after `BilinearForm::Assemble()` does prevent the operation from happening on host memory. Thank you so much for your help

**Comment by YohannDudouit** [comment]
@marc-85 You're welcome, I'll close the issue for now, feel free to reopen if you need more help.

**Comment by marc-85** [comment]
Hi @YohannDudouit,
I have a similar doubt as with the `BilinearForm` except now on a `NonLinearForm`. Before I make the call, the input `Vector x` and output `Vector y` have `DEVICE` memory type. However, when I call `NonLinearForm::Mult(Vector &x, Vector &y)` the `NonlinearFormIntegrator` performing the operations receives `Vector &elfunc` and `&elvec` with memory type `HOST`. Is there anything I can do to move the whole thing onto device space? Or is this not supported for `NonLinearForm`?

**Comment by marc-85** [comment]
Thank you very much @YohannDudouit 
I am developing a DG method based on example 18, where the `NonLinearFormIntegrator` has its own implementation of `NonLinearFormIntegrator::AssembleFaceVector`. I am assuming this means I need to implement my own `AddMultPA`. Are there any `AddMultPA` in MFEM I could use as reference?

**Comment by YohannDudouit** [comment]
Hi @marc-85 ,
Currently I think the only DG face integrator is `DGTraceIntegrator` (`fem/bilininteg_dgtrace_pa.cpp`), hopefully your integrator's implementation won't be too different.
You will also have to mimic most of the code from `PABilinearFormExtension` into `PANonlinearFormExtension` for supporting face integrators, this should be fairly straightforward.
If you're interested to implement this, you should create a branch and open a WIP PR, this will be easier for me to assist you on a PR if you need further help.
