### ISSUE TITLE
get "submesh"/discretization in (d-1)-dimensions

### ISSUE THREAD

**Issue by bensworth** [mfem/mfem#2222]
Suppose I have a 3d mesh that is orthogonal to some vector field. In the simplest case, this could just be a 3d structured mesh with the mesh orthogonal to the z-dimension. I.e., if (x0,y0,z0) is a point in the mesh, (x0,y0,z) is also a point in the mesh for all other discrete z, like time stepping with z=t. I then want to discretize a simple PDE on the 2d hyperplanes orthogonal to this vector (in the example, the xy-planes at each z-point). These discretizations could be performed independently or all together. Is this feasible in MFEM? Something like a structured 2d or 3d mesh is a fine starting place, although eventually I would like to try problems with 2d slabs orthogonal to some non-Euclidean vector field.

**Comment by tzanio** [comment]
Hi Ben,

I am not sure I follow exactly. In the structured case things are clear, but in  the unstructured case these "hyperplanes" could be tricky and maybe not even well/uniquely defined?

Either way, we do not have an easy way to extract a family of such 2D meshes. Extracting a 2D mesh e.g. based on attributes is something we are interested in, see https://github.com/mfem/mfem/discussions/2136, but with that you will still be responsible to identify the separate "planes".

Am I missing something?
Tzanio
