### ISSUE TITLE
Help with replicating mesh using Gmsh and ex2 

### ISSUE THREAD

**Issue by ddkn** [mfem/mfem#2223]
Hello,

I am trying to get a feel for using Gmsh v4.5.6 and serial ex2, and in particular I am unsure how to set up the mesh to mimic the example data set `beam-tet.mesh`, using a triangular mesh. I could use some guidance.

I was looking at other issues such as #1544, and I was able to create a mesh that had the right components (seemingly so), where we have a physical surface boundary on the left (attribute 1), and a physical surface boundary on the right (attribute 2), with a physical surface boundary around the whole piece, with two physical volumes. It *works*, but the beam bend from attribute 1 to attribute 2, is quite exaggerated. And the final product has 5 attributes, 3 surface and 2 volumes.

As I am trying to learn and build with this, and this is quite different from the `beam-tet.mesh` which only has 3 boundary attributes. My mesh below from `mybeam.msh`,

![image](https://user-images.githubusercontent.com/13819239/117154483-4470b680-ad92-11eb-81e1-e9d4dce1cf0b.png)

And the expected 'beam-tet.mesh'

![image](https://user-images.githubusercontent.com/13819239/117154194-01164800-ad92-11eb-9be9-8595ec3d8fd2.png)

You can also note that the beam squeezes in slightly in `mybeam.msh`. I am assuming the material properties are not being set correctly, due to some indexing, but does that mean I need to do BC of `lambda` and `mu` for both the attribute 1 and 2, and the corresponding volumes, which have labels 4 and 5? Or am I completely on the wrong direction here? Would netgen/NGsolve be a better tool for creating meshes?

For context, here is what the mesh looks like under GLVis,

![image](https://user-images.githubusercontent.com/13819239/117154929-b943f080-ad92-11eb-9163-b7577449fb72.png)

I am also attaching my `mybeam.geo` file in case. Prior to saving using MSH version 2 with ascii, I click Mesh > 3D and do a visual inspection.

~~~
// Gmsh project created on Wed May  5 10:26:41 2021
SetFactory("OpenCASCADE");
//+
Point(1) = {0, 0, 0, 1.0};
//+
Point(2) = {10, 0, 0, 1.0};
//+
Point(3) = {20, 0, 0, 1.0};
//+
Point(4) = {20, 2.5, 0, 1.0};
//+
Point(5) = {10, 2.5, 0, 1.0};
//+
Point(6) = {0, 2.5, 0, 1.0};
//+
Line(1) = {6, 1};
//+
Line(2) = {1, 2};
//+
Line(3) = {2, 3};
//+
Line(4) = {3, 4};
//+
Line(5) = {4, 5};
//+
Line(6) = {5, 6};
//+
Line(7) = {5, 2};
//+
Curve Loop(1) = {6, 1, 2, -7};
//+
Plane Surface(1) = {1};
//+
Curve Loop(2) = {5, 7, 3, 4};
//+
Plane Surface(2) = {2};
//+
Extrude {0, 0, 2.5} {
  Surface{1}; Surface{2};
}
//+
Physical Surface(1) = {4};
//+
Physical Surface(2) = {10};
//+
Physical Surface(3) = {7, 3, 5, 1, 2, 9, 8, 11};
//+
Physical Volume(4) = {1};
//+
Physical Volume(5) = {2};
~~~

Any direction and assistance would be greatly appreciated!

Cheers,

**Comment by pazner** [comment]
I believe ex2 is expecting the two parts of the volume to have attributes 1 and 2, and in your case, they have attributes 4 and 5, which will cause lambda and mu to have values of 1 in the entire volume, rather than 50 on the left and 1 on the right.

Changing the physical tags in your `Physical Volume` statements should fix the issue.

Also, note that in gmsh you can use the return value from the `Extrude` statement to avoid hard-coding the generated entity numbers:

```
left_extrusion[] = Extrude {0, 0, 2.5} {
  Surface{1};
};

right_extrusion[] = Extrude {0, 0, 2.5} {
   Surface{2};
};

// Extrude returns the indices of the generated entities according to the
// following indices:
//  * indices 0, 2, 4 are the "sides" of the extruded volume
//  * index 1 is the extruded volume
//  * index 3 is the left face, index 5 is the right face

Physical Surface("Left face", 1) = { left_extrusion[3] };
Physical Surface("Right face", 2) = { right_extrusion[5] };
Physical Surface("Body", 3) = { 1, left_extrusion[0], left_extrusion[2], left_extrusion[4],
                                2, right_extrusion[0], right_extrusion[2], right_extrusion[4] };

Physical Volume("Left volume", 1) = { left_extrusion[1] };
Physical Volume("Right volume", 2) = { right_extrusion[1] };
```

**Comment by ddkn** [comment]
Hi @pazner,

Thanks for getting back to me. I wasn't aware of this, as I am using the GUI of Gmsh to build the mesh, so the *.geo output I gave was from there, but I see that is quite handy for referencing.  One question I have now, does that not cause issues when trying to reference the specific surfaces or volumes? Or they are just grouped together now?

I modified my original *.geo file to the following based on what you said above (or so I think), and it gives this result, a 2D piece of stressed paper, which doesn't look correct to me:

![image](https://user-images.githubusercontent.com/13819239/117213654-478b9700-add2-11eb-8968-1bdd4a47b99e.png)

From GLVis the structure looks fine, all I did was input the mesh into the script from before,

![image](https://user-images.githubusercontent.com/13819239/117213700-58d4a380-add2-11eb-9c48-37cf0d0adcb0.png)

The corresponding correctedbeam.geo,

~~~
// Gmsh project created on Wed May  5 10:26:41 2021
SetFactory("OpenCASCADE");
//+
Point(1) = {0, 0, 0, 1.0};
//+
Point(2) = {10, 0, 0, 1.0};
//+
Point(3) = {20, 0, 0, 1.0};
//+
Point(4) = {20, 2.5, 0, 1.0};
//+
Point(5) = {10, 2.5, 0, 1.0};
//+
Point(6) = {0, 2.5, 0, 1.0};
//+
Line(1) = {6, 1};
//+
Line(2) = {1, 2};
//+
Line(3) = {2, 3};
//+
Line(4) = {3, 4};
//+
Line(5) = {4, 5};
//+
Line(6) = {5, 6};
//+
Line(7) = {5, 2};
//+
Curve Loop(1) = {6, 1, 2, -7};
//+
Plane Surface(1) = {1};
//+
Curve Loop(2) = {5, 7, 3, 4};
//+
Plane Surface(2) = {2};
//+
left_extrusion[] = Extrude {0, 0, 2.5} {
  Surface{1};
};
//+
right_extrusion[] = Extrude {0, 0, 2.5} {
   Surface{2};
};
//+
// Extrude returns the indices of the generated entities according to the
// following indices:
//  * indices 0, 2, 4 are the "sides" of the extruded volume
//  * index 1 is the extruded volume
//  * index 3 is the left face, index 5 is the right face
//+
Physical Surface("Left face", 1) = { left_extrusion[3] };
Physical Surface("Right face", 2) = { right_extrusion[5] };
Physical Surface("Body", 3) = { 1, left_extrusion[0], left_extrusion[2], left_extrusion[4],
                                2, right_extrusion[0], right_extrusion[2], right_extrusion[4] };
//+
Physical Volume("Left volume", 1) = { left_extrusion[1] };
Physical Volume("Right volume", 2) = { right_extrusion[1] };
//+
~~~

I did add in the extra `//+` to be consistent with the rest of the file output from the GUI.

**Comment by ddkn** [comment]
Hm, going back to what you said,

> I believe ex2 is expecting the two parts of the volume to have attributes 1 and 2, and in your case, they have attributes 4 and 5, which will cause lambda and mu to have values of 1 in the entire volume, rather than 50 on the left and 1 on the right.

Which confirms what I was gauging earlier, but I was moving to many things around to notice it. If I continue to use my original file `mybeam.msh` and adjust the ex2 script as such (I am actually using PyMFEM, but the example should be the same),

~~~
lamb = mfem.Vector(mesh.attributes.Max())
lamb.Assign(1.0)
-lamb[0] = lamb[1]*50
+lamb[0] = lamb[3] = lamb[1]*50
lamb_func = mfem.PWConstCoefficient(lamb)

mu = mfem.Vector(mesh.attributes.Max())
mu.Assign(1.0)
-mu[0] = mu[1]*50
+mu[0] = mu[3] = mu[1]*50
mu_func = mfem.PWConstCoefficient(mu)
~~~

I do get,

![image](https://user-images.githubusercontent.com/13819239/117215184-43607900-add4-11eb-9f2e-d270fce93b59.png)

Which, does *look* correct. Keeping the volumes make sense to me pragmatically, but they are clearly not operating as expected using the same id for *Physical Surface* and *Physical Volume*. There must be some subtly I am missing, or the PyMFEM has some issue that the C++ variant doesn't have.

Do you have any thoughts on this?

**Comment by ddkn** [comment]
And another interesting issue. Trying to use more building blocks tools to make meshing quicker, I tried using the Box command (only available in OpenCASCADE mode), which visually gives something similar just less elements, seen in GLVis,

![image](https://user-images.githubusercontent.com/13819239/117217537-e6ff5880-add7-11eb-9641-19ea7d073923.png)

and the output of the same file using separate volumes for `mu` and `lambda`,

![image](https://user-images.githubusercontent.com/13819239/117217627-0eeebc00-add8-11eb-9b61-44cb84d44f0f.png)

It gives another 2D sheet, but on an angle, here is another view,

![image](https://user-images.githubusercontent.com/13819239/117217703-30e83e80-add8-11eb-8c7a-0c1147486d83.png)

The corresponding geo file,

~~~
// Gmsh project created on Wed May  5 19:20:38 2021
SetFactory("OpenCASCADE");
//+
Box(1) = {0, 0, 0, 10, 2.5, 2.5};
//+
Box(2) = {10, 0, 0, 10, 2.5, 2.5};
//+
Physical Surface(1) = {1};
//+
Physical Surface(2) = {8};
//+
Physical Surface(3) = {1, 3, 6, 4, 5, 11, 9, 10, 12, 8};
//+
Physical Volume(4) = {1};
//+
Physical Volume(5) = {2};
~~~

So it looks like you can't use some features, and need to build meshes from the ground up for MFEM to work correctly with Gmsh? Do others have this issue as well? (Sorry for the tirade of posts)

**Comment by pazner** [comment]
The issue with the `.geo` file that you posted is that the OpenCASCADE engine will not automatically connect the two extruded volumes (since I split the extrusion into two in order to get the entity indices).

You can use the command `Coherence;` to make sure the geometry is properly connected. You could also try commenting out the line `SetFactory("OpenCASCADE");`, which should also work.

**Comment by pazner** [comment]
This `.geo` file works fine for me with `ex2` with no modifications:
```
SetFactory("OpenCASCADE");
Box(1) = {0, 0, 0, 10, 2.5, 2.5};
Box(2) = {10, 0, 0, 10, 2.5, 2.5};
Physical Surface(1) = {1};
Physical Surface(2) = {7};
Physical Surface(3) = {1, 3, 6, 4, 5, 11, 9, 10, 12, 8};
Physical Volume(1) = {1};
Physical Volume(2) = {2};
Coherence;
Mesh.MshFileVersion = 2.2;
```

Regarding reusing the same "physical tag" for volumes and surfaces: there is no risk of ambiguity in this case. *Volumes* with physical tags 1 and 2 are used to determine the coefficients, and the *surface* with physical tag 1 is used for essential boundary conditions. That the same numbers are used in these two cases will not cause a conflict.

That being said, if you prefer to use distinct physical tags, you certainly can do that, you will just need to adjust your script as you wrote.

**Comment by ddkn** [comment]
I was just adding the `Coherence;` as you suggested to all the problematic files, before you posted. You are right, every file that I had a problem with is **fixed**! 

I guess this was something I may have missed while going through some tutorials. Yeah, now that I know both are options, using coherence and keeping attributes separate are fine it isn't an issue. But going through the motions to make sure I was doing things correctly, I was worried I was not understanding something about the mesh creation.

I will mark this as closed, thanks again for the help @pazner!
