### ISSUE TITLE
MFEM_ASSERT causing incorrect failure

### ISSUE THREAD

**Issue by v-dobrev** [mfem/mfem#2231]
The `MFEM_ASSEERT` here
https://github.com/mfem/mfem/blob/bb2a80ed0af870a3f1a861d94f3d4fc6561bb663/mesh/mesh.cpp#L4101
will cause a failure for parallel meshes with interior "boundary" elements, when such "boundary" element is between two elements on different processors.

**Comment by pazner** [comment]
Is the correct fix here just to remove the `MFEM_ASSERT`?

Perhaps it would be useful to tag such fictitious boundary elements in some way so that they can be skipped in checks like this (and potentially other place)?

**Comment by v-dobrev** [comment]
It is probably good to keep the assert commented out with the explanation why it is disabled.

**Comment by tzanio** [comment]
Addressed in b1461d87b
