### ISSUE TITLE
Question about mfem::ParFiniteElementSpace::GetFaceRestriction()

### ISSUE THREAD

**Issue by samuelpmishLLNL** [mfem/mfem#2239]
I'm trying to use `mfem` to perform integration over a mesh boundary. I'm using `mfem::ParFiniteElementSpace::GetFaceRestriction(mfem::ElementDofOrdering::LEXICOGRAPHIC, mfem::FaceType::Boundary)` to get an operator that sets up the boundary dofs for an elementwise calculation. For the case of a Nedelec ParFiniteElementSpace defined on a mesh of quadrilateral elements, mfem emits the following error message when calling `GetFaceRestriction`:

"Finite element not suitable for lexicographic ordering"

After checking the source, it appears to check if the face element type is a "TensorBasisElement", and if not, it emits this error.

I understand that simplex elements, pyramids, etc. might be more difficult to order lexicographically, but it doesn't seem like there should be a problem for a 1D element. `mfem::H1_SegmentElement` and `mfem::L2_SegmentElement` are `TensorBasisElement`s, but not `ND_SegmentElement`. Is this exception intentional, or is it safe to expand the definition of "lexicographical-suitability" to include all the segment-type elements?

**Comment by tzanio** [comment]
@YohannDudouit, can you help with this one too?

**Comment by pazner** [comment]
Note that all nodal H1 elements support `NodalFiniteElement::GetLexicographicOrdering`, including simplices and prisms.

I also noticed that `ND_SegmentElement` is not a tensor element, and this means that 1D ND elements don't work with the current LOR solvers (#2089). Personally I agree with @samuelpmishLLNL that all elements defined on `[0,1]^d` should be considered tensor elements. The one wrinkle in the case of ND segment is that it only has an "open basis" and no "closed basis", and `VectorTensorFiniteElement` requires both basis types. I don't think this is unsolvable though.

**Comment by pazner** [comment]
Does this issue require action on our end?

Should we change `ND_SegmentElement` so it inherits from `VectorTensorFiniteElement`? (cc: @v-dobrev, @mlstowell)

**Comment by v-dobrev** [comment]
> Should we change `ND_SegmentElement` so it inherits from `VectorTensorFiniteElement`? (cc: @v-dobrev, @mlstowell)

It think it makes sense. This will require some small changes like removing `obasis1d` from the class because it will be inherited from `VectorTensorFiniteElement`.

**Comment by tzanio** [comment]
Discussion continued in #2372.
