### ISSUE TITLE
No convergence! How to make original MFEM mesh file?

### ISSUE THREAD

**Issue by random2000** [mfem/mfem#2246]
I wrote a code based on ex2.cpp for applying different material each element
(partitioning all tetrahedron elements and applied different attribute numbers).
When I calculate for sample data, "beam-tet.mesh", it can successfully calculate.

However, I couldn't calculate a elastic deformation of attached file "original.mesh". 
It returns the message "PCG: No convergence!".

I guess there are some problems for mesh file.
I also checked issue number #1944.

Could you tell me what is the problem in mesh file?

Original mesh file is generated with matlab script code.
Shape is thin circular membrane.

"./ex2.exe -m ./original.mesh" returns below.
Options used:
   --mesh ./original.mesh
   --order 1
   --no-static-condensation
   --visualization
   --paraview-datafiles
Elements with wrong orientation: 1073 / 1755 (fixed)
Number of finite element unknowns: 1890
Assembling: r.h.s. ... matrix ... done.
Size of linear system: 1890
   Iteration :   0  (B r, r) = -nan(ind)
	...
   Iteration : 500  (B r, r) = -nan(ind)
PCG: No convergence!
Average reduction factor = -nan(ind)

Thank you.

(Please change file name extension.)
[original.txt](https://github.com/mfem/mfem/files/6493929/original.txt)
[ex2_a.txt](https://github.com/mfem/mfem/files/6493923/ex2_a.txt)

**Comment by tzanio** [comment]
Yes, something in the mesh is incorrect, this is what I see with `glvis -m original.txt`:

<img width="672" alt="GLVis_s01" src="https://user-images.githubusercontent.com/1278247/118700021-07abb300-b7c7-11eb-8b5f-f3ef53ded5a5.png">

Something in your mesh generation script is off, it could be indexing or something else... it is difficult to tell without additional information.

**Comment by random2000** [comment]
Dear tzanio

Thank you for your advice.

I have confirmed that the mesh is not correct.
I was able to open the Gmsh file ( .msh ASCII format ) successfully.

However, I would like to convert the stl or step files output from CAD to mesh files and load them into mfem.
I could not figure out how to correctly line up the nodes, edges, and faces in the .mesh file.
To find out how to generate a correct mesh file, I read the general mesh file format page ( https://mfem.org/mesh-format-v1.x/ ) and fem/geom.cpp, and wrote a simple mesh file manually, but it did not load.

"(ident == "boundary") is false"

At least, I don't understand the meaning of the following content.

"Face orientation however includes not just the normal direction, but also any rotation of the vertices compared to the base, i.e. orientation here means permutation of vertices."

In what order should I place the nodes, edges, and faces (especially the tetrahedron mesh)?

random2000


## manually made mesh file
MFEM mesh v1.0

#
# MFEM Geometry Types (see mesh/geom.hpp):
#
# POINT       = 0
# SEGMENT     = 1
# TRIANGLE    = 2
# SQUARE      = 3
# TETRAHEDRON = 4
# CUBE        = 5
#

dimension
3

elements
5
1 4 3 5 6 7
2 4 1 6 3 5
3 4 3 2 6 1
4 4 3 4 6 2
5 4 3 8 6 4
6 4 3 7 6 8

boundary
12
1 2 3 7 5
3 2 7 6 5
1 2 1 3 5
3 2 1 5 6
3 2 1 6 2
3 2 1 2 3
3 2 3 2 4
2 2 2 6 4
2 2 4 6 8
3 2 3 4 8
3 2 3 8 7
3 2 7 8 6

vertices
8
0 0 0
0 1 0
0 0 1
0 1 1
1 0 1

**Comment by tzanio** [comment]
Hi @random2000,

I see multiple issues in this file:

- number of elements is `6` not `5` (that's the number on the line below `elements`)
- vertex numbers in the `elements` description should start from `0` not `1`
- vertex numbers in the `boundary` description should start from `0` not `1`
- after `vertices` you need two numbers: the number of vertices `8` followed by the space dimension `3`, which is currently missing
- there should be `8` vertex coordinates listed, currently there are only `5`

For reference, here is a minimal tet mesh:

```
MFEM mesh v1.0

dimension
3

elements
1
1 4 0 1 2 3

boundary
4
1 2 1 2 3
2 2 0 3 2
3 2 0 1 3
4 2 0 2 1

vertices
4
3
0 0 0
1 0 0
0 1 0
0 0 1
```

**Comment by random2000** [comment]
Dear @tzanio

I succeeded to generate correct MFEM mesh file from STL file.

I fixed vertex number, and it works.
Cause of problem was lack of vertex number 0.
Minimal tet mesh example is very helpful to understand.

Thank you for giving me  kind advice.

**Comment by tzanio** [comment]
I am glad you were able to resolve this @random2000.

FYI, there are simple meshes for all reference elements now in the repository (thanks to @mlstowell) -- see the `ref-*mesh` files in the [data/](https://github.com/mfem/mfem/tree/master/data) directory.

Tzanio
