### ISSUE TITLE
ParComplexLinearForm does not derive from ComplexLinearForm

### ISSUE THREAD

**Issue by mdeuse** [mfem/mfem#2248]
Hello MFEM community,
I noticed that `ParComplexLinearForm` does not derive from `ComplexLinearForm`, which does not seem to be in line with the usual convention (i.e. `ParMesh` derives from `Mesh`, `ParFiniteElementSpace` from `FiniteElementSpace`, `ParGridFunction` from `GridFunction`, etc). Is there a specific reason behind this, or should that be changed?
Regards,
Mathieu

**Comment by psocratis** [comment]
Hi @mdeuse, I honestly don't see a strong reason why this is the case (the same goes for `ParComplexGridFunction` and `ParSesquilinearForm`). I am assuming it was a design choice by @mlstowell, that made the implementation simpler. Does this cause any particular issue in any of your use cases?

**Comment by mlstowell** [comment]
Hi, @mdeuse and @psocratis,
If I recall correctly, I did try to follow the usual MFEM model but I decided it wasn't the best choice in this case. The primary issue is the `real()` and `imag()` member functions on these classes. The serial and parallel versions of these functions differ only in their return types and C++ doesn't support this type of polymorphism.
Best wishes,
Mark
