### ISSUE TITLE
Parallelism of BlockOperator (and BlockVector)

### ISSUE THREAD

**Issue by brightzhang91** [mfem/mfem#2250]
Dear developers and users

I'm working on a constrained nonlinear problem. One issue I don't understand is how MFEM distributes the BlockOperator and BlockVector in multiple processors, especially when the sub-blocks have different dimensions.
I have a blocked system with matrices B and Bt  used as constraints (Lagrange Multiplier), which are non-square with only a few rows, e.g. A(n,n)  B(3,n)  and Bt(n,3). 
[A Bt]
[B D]
I created an `Operator` class with this blockmatrix and implemented my `Mult()` and `GetGradient()`. This Operator is taken by the `PetscNonlinearSolver ` .
My confusion is with the parallelism, if all sub-blocks are square matrices of the same dimension ( Operator size is 2*FESpace()->TrueVSize()) , my `Mult() `is like :

```
void H_Operator::Mult(const Vector &k, Vector &Residual) const
{ 
   int sc = height/2;
   Vector k1(k.GetData() +  0, sc);
   Vector k2(k.GetData() +  sc, sc);
   Vector y1(Residual.GetData() +  0, sc);
   Vector y2(Residual.GetData() +  sc, sc);
   
   L_nonlinear->Mult(k1, y1);  
   L_linear->TrueAddMult(k1, y1, 1.0);
   L_mass->TrueAddMult(k1, y1, 1.0/dt);    
   y1.SetSubVector(ess_tdof_list, 0.0);   
   y2 = k2;
   constraint_.AddMult(k1, y2,1.0);// constraint_ is the subblock  for Lagrange multiplier 
}
```
If my `constraint_ `is non-square with only 3 rows (then the Operator size is FESpace()->TrueVSize()+3), how do I know the size of `k1` and `k2` on each processor ?

Thanks very much.
Bright

**Comment by v-dobrev** [comment]
It is up to you to decide how to partition the 3 rows in B among the MPI ranks. I assume there are 3 rows total, not 3 rows per rank? One option is to assign all 3 rows to rank 0 and give 0 rows to all other ranks.

**Comment by brightzhang91** [comment]
> It is up to you to decide how to partition the 3 rows in B among the MPI ranks. I assume there are 3 rows total, not 3 rows per rank? One option is to assign all 3 rows to rank 0 and give 0 rows to all other ranks.

Thanks for your explanation. Yes, there are in total 3 rows for the constraint matrix. Your suggestion is to specify a processor only for the the constraint multiplication. My understanding is on that specific processor, the height of the Operator is 3, while the size of solution vector `k` should still be `FESpace()->TrueVSize()` . However it seems both the constraint matrix and solution vector `k` are automatically partitioned and distributed to different processors.  How do I specify one processor and make it receive the non-partitioned `k` and the constraint matrix  ?
Can you suggest some examples of how to do it in MFEM ? 

Thanks !
Bright

**Comment by brightzhang91** [comment]
I received some very useful discussions in #1859 . I'll close this issue now.
