### ISSUE TITLE
Solve + Laplace(u) = 0 and not - Laplace(u) = 0

### ISSUE THREAD

**Issue by L29430** [mfem/mfem#2251]
Hello,

I would like to solve the following equation :   **+** Laplace(u) = 0.

My domain is rectangular. I put inhomogeneous Dirichlet boundary condition on the top wall and homogeneous Neumann boundary condition on the other walls. I woulk like to be able to use the strong and weak forms, for the Dirichlet condition.

My question is : Can I use the example 27 to do this ? Even if the exemple solve :   **-** Laplace(u) = 0 and not  **+** Laplace(u) = 0 ?
Is it the same equation solving ? Even with the weak Dirichlet condition ?

Kind regards.

**Comment by tzanio** [comment]
If the right-hand side is zero, there is no difference between the **+** and  **-** versions 😁.

If the right-hand side is nonzero, the easiest thing is to flip its sign instead of the operator.

**Comment by L29430** [comment]
Thank you !!! :)
