### ISSUE TITLE
Why the cor given by GetElementFaces(i,  fcs, cor)  equals to 0 or 3 or 7 ?

### ISSUE THREAD

**Issue by fengerhan** [mfem/mfem#2254]
Hello, everyone,
When I use  the function  Mesh::GetElementFaces(  i,  fcs, cor) to get the number and the orientations  of all faces of a CUBE, I get cor equal 0 or  3 or 7. What is it mean?  Why the cor is not equal to 1 or -1? In two dimension,  the cor  given by GetElementEdges(  i,  fcs, cor)  are all equal to 1 or -1. Why there is a difference in three dimension?
Who can tell me ?

**Comment by pazner** [comment]
In 2D, there are only two possible orientations for edges (an edge defined by vertices `v0` and `v1` can either be oriented `(v0, v1)` or `(v1, v0)`). These two possibilities are indicated by 1 or -1.

On the other hand, in 3D, the faces are either triangles or quadrilaterals, and so there are more possible orientations: the vertices can be rotated or flipped. These orientations correspond to the symmetries of the face, of which are are 6 for the triangle, and 8 for the quadrilateral. The returned orientation in an index into the `Orient` array corresponding to your face geometry, defined [here for the triangle](https://github.com/mfem/mfem/blob/e42c5e721165f33ba9b563a115f90d96fe26d55b/fem/geom.cpp#L776) and [here for the quadrilateral](https://github.com/mfem/mfem/blob/e42c5e721165f33ba9b563a115f90d96fe26d55b/fem/geom.cpp#L794).
