### ISSUE TITLE
Help needed for gmsh input format

### ISSUE THREAD

**Issue by jiangzhongshi** [mfem/mfem#2259]
Hello, 

I am want to try out mfem on my meshes, but I cannot seem to import a simple mesh generated from `https://github.com/nschloe/meshio`. The simplest example is as follows,
```
import mfem.ser as mfem
import meshio
import numpy as np
meshio.write('temp.msh', 
             meshio.Mesh(points=np.random.rand(20,3), 
                         cells=[('tetra', np.arange(20).reshape(-1,4))]),
              file_format='gmsh22',
             binary=False)

mfem.Mesh('temp.msh')
```
With error
```
RuntimeError: PyMFEM error (mfem::ErrorException): MFEM abort: Non-positive element attribute in Gmsh mesh!
 ... in function: void mfem::Mesh::ReadGmshMesh(std::istream&, int&, int&)
 ... in file: /__w/PyMFEM/PyMFEM/PyMFEM/external/mfem/mesh/mesh_readers.cpp:1579
```
Or (if fileformat is specified as  41)
```
RuntimeError: PyMFEM error (mfem::ErrorException): MFEM abort: Gmsh file : vertex index doesn't exist
 ... in function: void mfem::Mesh::ReadGmshMesh(std::istream&, int&, int&)
 ... in file: /__w/PyMFEM/PyMFEM/PyMFEM/external/mfem/mesh/mesh_readers.cpp:1571
```

What are the requirements of the msh file for mfem? And would high order `tetra35` be supported?

**Comment by mlstowell** [comment]
Hi, @jiangzhongshi,

The most common issue with importing Gmsh meshes is that MFEM requires all Gmsh Physical Volumes and Physical Surfaces to be assigned positive integer identifiers. Gmsh, on the other hand, starts numbering these from 0 by default. This would explain the first error you mentioned. I'm not sure about the second error.

As far as I know `tetra35` has not been tested but I believe the code is in place to support these. If you do run into trouble please let us know.

Best wishes,
Mark

**Comment by jiangzhongshi** [comment]
Hi Mark,

Thanks for the prompt response and explanation. I will follow up if encounter problems with simulations.

For future reference,
```
meshio.write('temp.msh', 
             meshio.Mesh(points=np.random.rand(70,3), 
                         cells=[('tetra35', np.arange(70).reshape(-1,35))],
                        cell_data={'gmsh:physical': [np.ones(2)]}),
              file_format='gmsh22')
              
```
this is enough to make it work.
