### ISSUE TITLE
Memory issue while using `Array<Vector>`

### ISSUE THREAD

**Issue by geyan3566** [mfem/mfem#2262]
Hi,

I created a `mfem::Array<mfem::Vector> my_array` object and push back the individual vector to it within a loop, but I got some memory error after a few iterations:
```
rbf_prolong.bin(4423,0x10ee79e00) malloc: Incorrect checksum for freed object 0x7fd201e04178: probably modified after being freed.
Corrupt value: 0x300000000
rbf_prolong.bin(4423,0x10ee79e00) malloc: *** set a breakpoint in malloc_error_break to debug
```

Here is the sudo code:
```
Array<Vector> my_array; // this is outside the function and it's passed into the function by a reference


// inside function
my_array.LoseData();
int dim = 2;
Vector coord(dim);
for (int i = 0; i < mesh->GetNE(); i++)
{
  coord = // something;
  my_array.Append(coord);
}

```

**Comment by pazner** [comment]
The `Array` class is only intended for so-called [trivial types](https://en.cppreference.com/w/cpp/types/is_trivial), and `Vector` is not trivial. In fact, with the latest master, that code should give a compilation error
```
../mesh/../fem/../general/array.hpp:57:7: error: static_assert failed due to
      requirement 'std::is_trivial<mfem::Vector>::value'
      "type T must be trivial"
      static_assert(std::is_trivial<T>::value, "type T must be trivial");
```
since #2214 was merged.

**Comment by pazner** [comment]
I should add that an alternative approach that could work for your purposes is to use `std::vector<Vector>`.

**Comment by geyan3566** [comment]
Thank you very much. Let me try that
