### ISSUE TITLE
Parallelize for loop, where MPI communication is done, with OpenMP

### ISSUE THREAD

**Issue by Andr00dz** [mfem/mfem#2263]
Hello,

in each time step of my MPI-parallelized Navier Stokes solver, I need to do a "inner" Monte Carlo simulation, which yields necessary information for the next time step of the "outer" Navier Stokes simulation. The Monte Carlo simulation is currently of the following type:

For given `HypreParMatrix A` and `N` vectors `Vector x_i`, `Vector b_i`, `i=1,..,N` do the following:
```
for ( i = 0; i<N; i++)
{
 x_i = A*x_i + b_i  // Update x_i
}
```
and after this, a matrix of the form `T = 1 / N * \sum_{i=1}^N x_i * (x_i)^T`, is constructed.

The vector size depends on the underlying mesh resolution and number of MPI ranks. As the length `N` of the for loop can be set arbitrarily large, it might be not the best idea to increase the number of MPI ranks, in order to reduce the computation time of the for loop.

I parallelized the for loop with `#pragma omp parallel for num_threads(2)` and found out that as soon a matrix-vector multiplication (with MPI communication) is done, the program breaks down with segfault errors.

Is it even possible to combine OpenMP with MPI for my purposes or is better to just increase the MPI ranks?

**Comment by tzanio** [comment]
Others may chime in with there experience, but in general I'll recommend to just increase the number of MPI ranks.
