### ISSUE TITLE
Open boundary condition in mfem

### ISSUE THREAD

**Issue by gzict** [mfem/mfem#2269]
Dear developer,

We are trying to develop a pressure correction based NS solver based on MFEM, and I have a question regarding to the implementation of open boundary for flow simulation.

My problem is the following:

Assume we have a time dependent stokes equation on a pipe:

u_ t - \laplace (u) + \grad(p) = f
div(u) = 0

on the inlet we have Dirichlet boundary condition u = u_in
on the wall we have no slip boundary condition u = 0
on the outlet we have open boundary, namely \grad(u) n  = p n, here p is the outgoing normal vector

In pressure correction method, inlet and wall are standard Dirichlet boundary conditions. The outlet boundary can be treated as the nonhomogeneous Neumann boundary condition when solving velocity diffusion:

(u^(k+1) - u^(k))/dt - \laplace (u^(k+1)) + \grad(p^(k)) = f

My question is for the implementation of this step in mfem. 

More specifically, to implement \grad(u^{k+1}) n  = p^{k} n on boundary, I think the best way in mfem is using

`b->AddBoundaryIntegrator(new VectorBoundaryLFIntegrator(f));`

here f = p^{k} n

Here comes the problem: based on the iterative pressure correction method, p^{k} is a scalar gridfunction on whole domain and boundary. However,  the input of VectorBoundaryLFIntegrator() should be a vector valued function defend only on boundary. To simplify the problem let's say we know exactly what n is on the outlet boundary. How can I construct my boundary condition using mfem?

Thanks.

**Comment by jandrej** [comment]
If I understand correctly you are probably looking for a (not yet existing) `VectorBoundaryNormalLFIntegrator`. 

You can modify `VectorBoundaryLFIntegrator` to multiply you input, in this case `p^{k}`, with the normal vector. The source of `BoundaryNormalLFIntegrator` should help accomplishing that.

**Comment by gzict** [comment]
> If I understand correctly you are probably looking for a (not yet existing) `VectorBoundaryNormalLFIntegrator`.
> 
> You can modify `VectorBoundaryLFIntegrator` to &multiply you input, in this case `p^{k}`, with the normal vector. The source of `BoundaryNormalLFIntegrator` should help accomplishing that.

@jandrej Thank you for the reply. I would like to clarify my question a bit. At the moment the main problem is not finding the normal vector on the boundary. In my case it is a known constant vector. My main problem is the API of VectorBoundaryLFIntegrator.

Please correct me if I'm wrong, the input of vectorboundaryintegrator cannot be a gridfunction defined on the domain. Its input has to be a vector valued function defined on the boundary. As the result 
'VectorBoundaryLFIntegrator(p^{k} n)' is not correct.

The same restriction applied to boundarynormallfintegrator as well. 'BoundaryNormalLFIntegrator(p^{k})' is also wrong.

Thus from coding perspective, I think my question is: how can I construct a vector valued function from a gridfunction by only using its boundary points.

**Comment by tzanio** [comment]
Hi @gzict,

If I understand you need the boundary linear form integrator `(p, v.n)` where `p` is a scalar `GridFunction` and `v` is an `H1` vector test function. Does `VectorBoundaryFluxLFIntegrator` work for you? 

(See https://mfem.org/lininteg/#vector-field-operators)

Tzanio
