### ISSUE TITLE
HowTo Article:  Utilizing periodic boundary conditions

### ISSUE THREAD

**Issue by acfisher** [mfem/mfem#2275]
We could use an article describing how to use periodic boundary conditions.  For the meantime put it in this branch of the web repo:

https://github.com/mfem/web/tree/searchable-articles/src/howto

Examples can be found in that folder.

**Comment by pazner** [comment]
I added a draft [how-to article](https://github.com/mfem/web/blob/searchable-articles/src/howto/periodic-boundaries.md).

**Comment by acfisher** [comment]
Brilliant, thank you!
