### ISSUE TITLE
ParMesh to Mesh vertex index identification

### ISSUE THREAD

**Issue by mdeuse** [mfem/mfem#2277]
Hello,

When creating a ParMesh from a serial Mesh, the numbering of the vertices is changed. Given a vertex in the ParMesh (on an arbitrary proc), is there a way to obtain the index of this vertex in the original serial Mesh?

I had a look at the `GetGlobalVertexIndices` function from ParMesh, but this is not what I am looking for. This function provide a unique global index for each vertex, but this global index does not match the index in the original serial Mesh, I guess because there is a re-numbering of the vertices due to the partitioning.

At the moment, my workaround solution is to compute a mapping table by comparing the coordinates of each vertex of the ParMesh to all the vertices of the serial Mesh, to identify the identical coordinates. Although this workaround produces what I expect, it is obviously very slow.

**Comment by v-dobrev** [comment]
The global (serial) to local (parallel) vertex mapping is constructed in the `ParMesh` constructor but then it is discarded. The algorithm for constructing this mapping is fairly simple, so you can just copy that part in a function outside the `ParMesh` constructor if you want to re-create and keep that. See here: https://github.com/mfem/mfem/blob/71a6fa151425fed7207da265ad6d0228da142f19/mesh/pmesh.cpp#L170

You only need the first two loops in that method.

**Comment by mdeuse** [comment]
That is indeed what I was looking for, thank you for the indication.
