### ISSUE TITLE
Certain Configure-time variables are effectively hard-coded

### ISSUE THREAD

**Issue by Jacobfaib** [mfem/mfem#2281]
A selection of `makefile` variables defined in `config/defaults.mk` are defined using the `:=` operator, and thus expanded on *definition* rather than use. These include `MPI_DIR` and almost all of the relevant PETSc and SLEPc variables. Even the indicator variables are defined this way, e.g. `PETSC_FOUND`:
```
PETSC_ARCH := arch-linux2-c-debug
PETSC_DIR  := $(MFEM_DIR)/../petsc/$(PETSC_ARCH)
PETSC_VARS := $(PETSC_DIR)/lib/petsc/conf/petscvariables
PETSC_FOUND := $(if $(wildcard $(PETSC_VARS)),YES,) 
```
Which is what is ultimately checked for existence of PETSc in the main makefile:
```
PETSC_ERROR_MSG = $(if $(PETSC_FOUND),,. PETSC config not found: $(PETSC_VARS)) 
```
So overriding anything but `$(PETSC_LIB)` (which is the only variable not given this treatment for PETSc for example) in `user.mk` will have no effect since any dependent make variables will already have been expanded.

**Comment by Jacobfaib** [comment]
As a follow-up perhaps the makefile variable `PETSC_DIR` should be renamed in order to avoid a namespace clash. Users with a PETSc install will almost always have `$PETSC_DIR` defined in their environment as the directory containing `$PETSC_ARCH` so in the above that would be `$(MFEM_DIR)/../petsc`

**Comment by v-dobrev** [comment]
The intended way of creating `user.mk` is to copy it from `defaults.mk` and then edit what's needed, see here: https://github.com/mfem/mfem/blob/45f85e7980760ddb62fc82b1377fc050b28cddd9/config/defaults.mk#L14-L15 and here: https://github.com/mfem/mfem/blob/45f85e7980760ddb62fc82b1377fc050b28cddd9/INSTALL#L137-L142

If you do that, I don't expect any of the above to be a real problem.

The supported ways of setting `PETSC_DIR` (or any other makefile variable) in MFEM's build system are two: set it in `defaults.mk`/`user.mk` or at the command line during configuration: `make config PETSC_DIR=/path/to/petsc ...`. Setting `PETSC_DIR` through the environment should be considered unsupported -- in particular, any value that the makefile variable `PETSC_DIR` gets initially from the environment is overwritten in `defaults.mk`/`user.mk`.

**Comment by pazner** [comment]
Could some of these assignments be changed to use `=` instead of `:=` or would that cause other problems?

**Comment by Jacobfaib** [comment]
> The intended way of creating user.mk is to copy it from defaults.mk and then edit what's needed

Right. And `INSTALL` does note that `PETSC_LIB` and `PETSC_OPT` are the only two variables whose overriding in `user.mk` are supported but setting all of `PETSC_LIB` is a bit heavy-handed. I think this be simplified and conformal to all the other library configuration methods.

Currently in order to couple petsc and mfem you need to redefine all of the following in your `user.mk`
```
PETSC_ARCH = arch-blabla
PETSC_DIR = /path/to/petsc
PETSC_VARS := $(PETSC_DIR)/lib/petsc/conf/petscvariables                                                                                                                           
PETSC_FOUND := $(if $(wildcard $(PETSC_VARS)),YES,)
PETSC_INC_VAR = PETSC_CC_INCLUDES
PETSC_LIB_VAR = PETSC_EXTERNAL_LIB_BASIC
ifeq ($(PETSC_FOUND),YES)
   PETSC_OPT := $(shell sed -n "s/$(PETSC_INC_VAR) = *//p" $(PETSC_VARS))
   PETSC_DEP := $(shell sed -n "s/$(PETSC_LIB_VAR) = *//p" $(PETSC_VARS))
   PETSC_LIB = $(XLINKER)-rpath,$(abspath $(PETSC_DIR))/lib\
      -L$(abspath $(PETSC_DIR))/lib -lpetsc\
      $(subst $(CXX_XLINKER),$(XLINKER),$(PETSC_DEP))
endif
```
or redefine `PETSC_LIB` by hand yourself (in an of itself fairly error-prone thing to do) when simply having
```
PETSC_ARCH = arch-blabla
PETSC_DIR = /path/to/petsc
```
in `user.mk` and moving the petsc and slepc configuration to the root `makefile` would suffice. This wouldn't be without precedence; MPI, CUDA, HIP, and OpenMP all have configuration logic there as well.
