### ISSUE TITLE
error in hiop test

### ISSUE THREAD

**Issue by e-aranda** [mfem/mfem#2287]
Hello,

make test at example/hiop gives the following error

make[2]: *** No hay ninguna regla para construir el objetivo 'ex9p-test-par', necesario para 'test-par-YES'.
make[2]: *** No hay ninguna regla para construir el objetivo 'ex9-test-seq', necesario para 'test-par-YES'.

**Comment by vladotomov** [comment]
Fixed in #2290, thanks for reporting.

**Comment by tzanio** [comment]
Discussion continued in #2290.
