### ISSUE TITLE
A possible bug in HypreParMatrix::LeftDiagMult

### ISSUE THREAD

**Issue by chakshinglee** [mfem/mfem#229]
In the function `HypreParMatrix::LeftDiagMult(const SparseMatrix &D, HYPRE_Int* row_starts)`, the output `HypreParMatrix` will use the same 'RowStarts' array of `this` if the number of rows of the input matrix `D` and the number of rows of `this` are the same. This makes sense because this somehow means the row and column 'starts' of D (if we think of it as a `HypreParMatrix`) are the same. 

However, the function checks the above condition by checking the local number of rows only:
`const bool same_rows = (D.Height() == hypre_CSRMatrixNumRows(A->diag));`

If this is true in some processors, but not the others, then different processors will use different definitions for `row_starts` and `global_num_rows`, which may result in some mismatch (even if `row_starts` is not `NULL`). 

This can happen if globally D is a rectangular matrix, but locally it is a square matrix in some processor (although this may be rare, I have encountered this situation). 

To fix the issue, I think either do a 'MPI_LAND' to `same_rows` or change the if statement
`if (same_rows)` to `if (same_rows && !row_starts)`

**Comment by v-dobrev** [comment]
Hi Chak,

I see your point, and I think we should fix this.

I suggest the following simple logic to keep this method communication-free:
* If `row_starts == NULL`, each processor checks that `D` is square and has the right size and uses the row starts of `this` as row starts for the new matrix. Here, it is natural to assume that `row_starts == NULL` returns the same result on every processor.
* If `row_starts != NULL`, check if `row_starts` is the same pointer as the row starts pointer for `this` (this condition should give the same result on all processors unless `row_starts` or the row starts of `this` are created in some non-standard way); if the pointers are the same, then treat this case as the case when `row_starts == NULL`. If the pointers are different, then treat this as the general rectangular case: check that the dimensions of `D` are correct and use `row_starts` as the row starts for the new matrix and the column starts of `this` as the column starts for the new matrix.

What do you think about this solution?

**Comment by chakshinglee** [comment]
Hi Veselin, 

Yes, your suggestion makes a lot of sense to me, and it's nice that it does not require communication.

**Comment by tzanio** [comment]
Resolved by 3c6b857e768fe9b42e13fd7c42ca0f0c4e8297e0.
