### ISSUE TITLE
Mesquite support: Depreciated

### ISSUE THREAD

**Issue by a-jp** [mfem/mfem#2291]
Hi, 

I note that you mark mesquite as depreciated:
> The Mesquite support is deprecated and will be removed in the future.

I was trying to use MFEM as a guide to incorporate mesquite into my own code.  The question I have is, what library do you plan to replace Mesquite with that has similar features? 

 I'm looking for vertex-position-based mesh smoothing and quality-based mesh improvement libraries for 3D unstructured moving (ALE) meshes; I couldn't really find an alternative to Mesquite for this. 

I'm asking as it may be prudent for me to begin development using the library you plan to move too as opposed to one that others are moving away from.

Mesquite appears to be no longer developed or supported, is that correct, or am I not looking in the right place?

Thanks,
Andy

**Comment by tzanio** [comment]
The plan for replacement is MFEM itself :)

**Comment by a-jp** [comment]
Thanks. What I really need is a third party lib just to handle mesh quality improvement for my ALE code, I think calling MFEM for that is probably a bit overkill and doesn't really fit with MFEM being a full blown ALE itself 😄.  One question; do you have any information as to the status of mesquite as a library itself in terms of its continued development?

**Comment by tzanio** [comment]
>  I think calling MFEM for that is probably a bit overkill and doesn't really fit with MFEM being a full blown ALE itself

That's what MFEM is designed for (it provides tools for ALE, as e.g. used in the BLAST application, but it is not ALE itself). Take a look at the API in the optimizer miniapps and if that is not sufficient, we can work with you to accomodate your needs.

> Do you have any information as to the status of mesquite as a library itself in terms of its continued development?

I believe it is no longer developed or supported.

**Comment by a-jp** [comment]
> That's what MFEM is designed for (it provides tools for ALE,

Ok, that's interesting, that's a fundamental miss-understanding on my part. Thanks for the clarity. 

So if I'm developing a finite volume based (second order) ALE code on unstructured 3D meshes, but I'm struggling to get decent smoothed meshes after I move a portion of the domain, I can use MFEM to smooth the 'free' vertices to obtain a good mesh?

**Comment by tzanio** [comment]
> I can use MFEM to smooth the 'free' vertices to obtain a good mesh?

Yes

**Comment by a-jp** [comment]
better look at that mini-app then....  I have my own data structures etc for my mesh and my field data, do I need to move my code fully to MFEM data structures, or can I provide a wrapper/proxy class that can reach back into my existing data structures so I can make use of MFEM without a partial re-write?

**Comment by tzanio** [comment]
Currently you need to use an MFEM mesh. 

Hopefully the conversion is not too bad, the miniapps for example can read VTK, Gmsh and [other mesh formats](https://mfem.org/meshing/).

**Comment by a-jp** [comment]
Ok thanks
