### ISSUE TITLE
Visualizing trace jumps for discontinuous solution

### ISSUE THREAD

**Issue by sebastiangrimberg** [mfem/mfem#2294]
If I've computed a discontinuous solution in an L2 or RT space, is there a good way to compute and output the jumps on the interfaces as a `GridFunction`, for example using an H1 or ND space? Hopefully that question makes sense, but I'm stuck as to how to get a projection of the jumps represented in some trace space of the elements onto a full domain representation in the element interiors. This seems similar to a questions in #1288 or #106. 

Perhaps it's not a well posed question, but this would be a common thing for example to compute surface currents from the magnetic field in an electromagnetics code.

**Comment by tzanio** [comment]
In the scalar L2 case, one option is to use the jumps as the dofs of RT_0 and visualize the corresponding grid function.  It may take some time to interpret the plot, but it is relatively simple to try.

Another option can be to subdivide each element into subelements such that each original face belongs to two face-specific subelements. For example you can split a triangle into 3 sub-triangles using the element center. Then you can plot a piecewise-constant field over the sub-elements with the value of the jump for the original face belonging to each sub-element.

There may be other/better to do this... I'm curious to hear what other MFEM developers and users think.

Tzanio

**Comment by sebastiangrimberg** [comment]
Thanks for the quick response. I'll have to think a bit more about your ideas but in the mean time it may help if I am more specific since perhaps I'm over complicating things.

I want to compute something like `X = n x [B]`, where B is in a vector L2 space of the same dimension as `n` and thus X is continuous on each element interface (and tangent to the face) and it's value doesn't really matter inside the element. I was thinking maybe you could just get the projection by assuming X is in an H1 or ND space and ending up with a system where the system matrix is just a vector mass matrix and the RHS looks like the inner product `(n x [b], v)`. Maybe this is the wrong direction to go in but thanks as always for your help and suggestions MFEM community.

**Comment by sebastiangrimberg** [comment]
@tzanio I think I've come up with a better statement of my problem and a potential solution, and would like to hear any feedback you might have.

Instead of visualizing the jumps I'm content with just looking at the quantity `J = n x H` on boundaries of the domain where `H` is discontinuous (though in general `n x H` is continuous across elements). I think the way to do this is just to use a `VectorGridFunctionCoefficient` for the DG field `H`, and solve the linear system resulting from the surface integrals `(u, v) = (n x H, v)` where the solution is `J` in an ND space and the RHS can be computed using a `VectorFEBoundaryTangentLFIntegrator`.

There is an issue when the boundary of interest is internal to the domain (two sided), in which case the call to `GetBdrFaceTransformations` inside of `GridFunction::GetVectorValue` called by the integrator for the discontinuous field coefficient will return NULL since the face attached to the boundary element is an interior face. However if I just comment out lines 1032-1036 in `mesh.cpp` I think I can force the quantity `n x H` just be evaluated in a one-sided fashion on an interior surface which still works since `n x H` should be continuous across elements based on the problem.

I've tested this out and it seems to be doing the right thing, though I'm not 100% convinced that it's the best way to accomplish what I want. Since the `VectorFEBoundaryTangentLFIntegrator` is only available for ND spaces, I am forced to represent `J` in an ND space and get some weird out of plane components even though the quantity `n x H` should always lie tangent to the surface. Maybe I need to project the final solution onto a fully continuous space, perhaps using `GridFunction::ProjectDiscCoefficient` to average out the discontinuities? 

I'd be very interested if anyone else has encountered this type of problem and how they have approached it in their own applications!

**Comment by tzanio** [comment]
Hi @sebastiangrimberg, 

I've never had to do anything like this myself, but maybe Mark (@mlstowell) has experience with similar problems and can offer advice. 

Tzanio

**Comment by sebastiangrimberg** [comment]
Hi @mlstowell, any chance you've had to think about similar postprocessing problems? Would love your input whenever you get a chance.

Sebastian

**Comment by mlstowell** [comment]
Hi, @sebastiangrimberg, 

Sorry for the delay. I must have missed this when it first arose.

I have done something like this in the past although I typically start with ND or RT spaces. If you're transferring a field from one representation to another and the target representation can exactly capture the source field then you can avoid solving a linear system and just use a projection. It sounds like this will work in your case if you're certain that `n x H` is continuous.

There are two ways to accomplish this. The first is to write a custom loop over the relevant faces and project `n x H` onto the corresponding degrees of freedom. The second is to create a `DiscreteLinearOperator` which can be reused multiple times. The second option would be more complicated but more efficient if you need to reuse this operation several times in your simulation.

One thing to keep in mind is that on interior faces `n` is not uniquely defined. There is a normal direction for each face but its sign is arbitrary. To resolve this you'll need to define a vector field, `v` for example, which everywhere points in the direction you've chosen. This allows you to check the sign of `v . n` on each face and correct the sign of `n` when necessary.

I assume you need to compute `n x H` on a small subset of interior faces and perhaps on most or all of the outer boundary. If you choose the second option we may be able to reuse `DiscreteLinearOperator::AddTraceFaceInterpolator` but we'd need to write a custom `DiscreteInterpolator`. If you choose the first option it might be easiest to just write your own loop over interior faces and compute the projection at a fairly low level.

Let me know what you think would work best and I'd be happy to guide you through the necessary steps.

Best wishes,
Mark

**Comment by sebastiangrimberg** [comment]
Hi Mark, thanks for the fast follow up. I think starting with the first option just for clarity would help and if performance becomes an issue then I can try out the second.

Indeed as you can imagine I have a solution E in an ND space and B in an RT space and am going from there like the Maxwell miniapp. I don't think H can be in an ND space because of internal boundaries where the tangential component is discontinuous. In this case looping over the relevant faces (for example they may be all labeled as boundary elements), I would need to choose the neighboring element that is somehow consistent with the chosen normal orientation (for example, always compute `n x H` using the element on the side of an internal surface into which `n` points). Or maybe if I am confident that `n x H` will be continuous even though `H` is not tangentially continuous there is a way to average the results from both neighboring elements. How to do this over the boundary elements isn't immediately clear to me, so maybe the first method isn't actually that simple?

Am I just overly complicating things or do internal boundaries with two neighboring elements make  things a bit harder?

Sebastian

**Comment by mlstowell** [comment]
Hi, Sebastian,

Things do get complicated quickly. If `B` is in RT then we cannot guarantee that `n x B` is continuous. However, this is often an artifact of the numerical approximation. If the magnetic permeability is the same on both sides of the interface and there are no surface currents imposed on the interface then the true `B` field should be entirely continuous.

I'm curious, what type of physics are you interested in near these internal boundaries?

Best wishes,
Mark

**Comment by sebastiangrimberg** [comment]
For an example using Maxwell miniapp, consider a metal box with some current source inside as well as some other internal metal surface on which we impose a PEC BC. I would be interested in viewing the induced currents both on the external box boundaries (one sided) as well as the internal surface (which are two sided). If the internal surface is infinitely thin, then I'm pretty sure the tangential components of B will point in opposite directions on either side of the surface which is the kind of issue I'm struggling with.

Does that make sense? Could be that I'm just not anticipating this correctly.

Sebastian

**Comment by mlstowell** [comment]
I see. To accurately see surface currents on metal surfaces the PEC boundaries should be one sided. Applying PEC BCs to double sided surfaces should work fine but you won't have enough degrees of freedom to see the surface currents correctly. You could compute the averaged currents but I doubt these would be physically meaningful. On the one hand if the metal surface is much thicker than the skin depth then the two currents don't interact so their average is not relevant. On the other hand if the metal is thin compared to the skin depth then the currents interact strongly and their average could be relevant but the PEC BC is probably not an adequate representation of the physics on such a thin sheet so the fields won't be reliable.

I had a similar situation arise recently and I chose to split the interior surface in to two separate surfaces. In most cases these two surfaces can lie directly on top of each other as long as they use different vertices so that topologically they form a cut in the mesh. In rare cases the vertices might need unique coordinates but this can be handled by shifting the vertices on one side of the cut by a very small number. Clearly this scheme has the advantage that all of your PEC surfaces are now on the outer boundary so `n x H` will be single valued everywhere.

I hate to complicate things further but I have to mention this. If the accuracy of your `n x H` values are paramount then you may want to consider using an DH formulation of the Maxwell equations. What I mean by this is rewriting the Maxwell equations so that you solve for `H` and `D` rather than `E` and `B`. This formulation would produce more accurate values for `H` at the boundaries whereas the EB formulation approximates the flux of `B` through the interior of the elements.

**Comment by sebastiangrimberg** [comment]
I totally agree and was thinking that going the route of fixing at the mesh level would be the best approach. I think that this will be possible to add at the preprocessing stage and the tricky use of double sided internal surfaces probably wasn't a great idea.

Regarding the `EB` vs. `HD` formulations, I agree with your points and thanks for bringing it up. For the most part accuracy in `E` is what we are looking for which was the motivation for going this direction. Postprocessing for `B` and `J` is just a nice added feature.

Closing this now, thanks again so much!

Sebastian

**Comment by mlstowell** [comment]
Glad to help!
