### ISSUE TITLE
Calcluating "maximum vertex distance" within an element

### ISSUE THREAD

**Issue by wcdawn** [mfem/mfem#2295]
I am implementing some stabilization methods that rely on the "maximum vertex distance" of an element. I'm implementing this within a `Coefficient` so I have access to the element data, but it seems like an element with N vertices would require calculating N*(N-1) distances for each call to `Coefficient::Eval()`.

For now, I'm using the "effective diameter" as an analog.
```cpp
const double volume = pmesh->GetElementVolume(T.ElementNo);
double h;
if (pmesh->Dimension() == 3)
  h = std::cbrt(6.0/M_PI*volume);
else if (pmesh->Dimension() == 2)
  h = std::sqrt(4.0/M_PI*volume);
```

However, I'd like to evaluate the maximum vertex distance so I can compare to literature. Maybe using a `QuadratureFunction` since that loops through elements?

Thanks!

**Comment by vladotomov** [comment]
Hi @wcdawn,

You can use `pmesh->GetElementVertices()` and `pmesh->GetVertices()` to obtain the vertex coordinates of an element.

Vladimir

**Comment by wcdawn** [comment]
Thanks!

The code I came up with looks like
```cpp
    double h{0.0};
    Array<int> vertices;
    pmesh->GetElementVertices(T.ElementNo, vertices);
    for (int i{0}; i < vertices.Size(); ++i)
    {
      const double *v1{pmesh->GetVertex(vertices[i])};
      for (int j{0}; j < vertices.Size(); ++j)
      {
        if (i == j) continue;
        const double *v2{pmesh->GetVertex(vertices[j])};
        double dist = 0.0;
        for (int d{0}; d < pmesh->Dimension(); ++d)
          dist += std::pow(v1[d] - v2[d], 2);
        dist = std::sqrt(dist);
        h = std::max(h, dist);
      }
    }
```

It is painfully slow but I guess calculating the maximum vertex distance may be doomed from the start.
I'll definitely be looking to replace this using the effective diameter or a similar metric.
