### ISSUE TITLE
link error with PETSc

### ISSUE THREAD

**Issue by brightzhang91** [mfem/mfem#2299]
Hi ;)
I just upgraded PETSc from 3.13 to 3.15 and tried to link with MFEM 4.2 . The following errors appeared after the input:
make parallel  MFEM_USE_PETSC=YES MFEM_USE_MPI=YES
![image](https://user-images.githubusercontent.com/67397441/120942720-a706fa80-c722-11eb-8fdc-d5c3d239f22f.png)

The configure options of PETSc are :
--download-f2cblaslapack --with-hypre-dir=../hypre-2.20.0/src/hypre --with-fc=0 --with-shared-libraries=0 --with-cc=mpicc --with-cxx=mpicxx

Can anyone advise what's wrong with the compilation ? It works well with the previous PETSc 3.13, which was deleted for the upgrade to 3.15.

Thanks !
Bright

**Comment by tzanio** [comment]
Bright, can you try using the `master` branch of mfem?

**Comment by v-dobrev** [comment]
You can also try this patch: https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/mfem/mfem-4.2-petsc-3.15.0.patch.

**Comment by stefanozampini** [comment]
There was a change in PETSc API since the latest MFEM release. You should use MFEM's `master`  to use PETSc 3.15 or fix the calls yourself (basic)

**Comment by brightzhang91** [comment]
The compilation and build is successful from the master branch. 
Thanks for the advices !

Bright

**Comment by brightzhang91** [comment]
Hi
Since the upgrade to PETSc-3.15, the error was reported by `PetscNonlinearSolver` for the problem with 70292 unknowns (Nedelec), which was not encountered before the upgrade.  Any ideas why this happens with the new PETSc ? Thanks !
![image](https://user-images.githubusercontent.com/67397441/121438909-c13c1500-c97c-11eb-9fd4-2ff281e8a125.png)

**Comment by stefanozampini** [comment]
Hi @brightzhang91. This is strange, the stack trace seems corrupted. Can you provide a reproducer?

**Comment by brightzhang91** [comment]
> Hi @brightzhang91. This is strange, the stack trace seems corrupted. Can you provide a reproducer?

Thanks stefanozampini  for your support !
Please see the MFEM code and the mesh file produced with Gmsh.
The `Out of memory` error was encountered in the serial run, and non-convergence was encountered in the parallel run. 
[https://github.com/brightzhang91/EM-solvers/blob/main/magnetodynamic_inductive.cpp](url)
[https://github.com/brightzhang91/EM-solvers/blob/main/torus2.msh](url)

Thanks very much ;)
Bright

**Comment by stefanozampini** [comment]
Can you try using https://github.com/mfem/mfem/commit/30da55f38fdd9fcd3686de6b826b98c619629ec8?
I have run your code using the patch in https://github.com/mfem/mfem/commit/30da55f38fdd9fcd3686de6b826b98c619629ec8 and the error goes away. I have opened an issue in PETSc https://gitlab.com/petsc/petsc/-/issues/940.

However, if I run sequentially, I'm getting software errors from failing line search though, not sure about that.
```
[szampini@localhost petsc]$ cat rc_ex10p_jfnk
# matrix-free Jacobian action, preconditioner constructed using PetscPreconditionerFactory
-snes_linesearch_monitor
-snes_converged_reason
-snes_monitor
-snes_mf_operator
-ksp_type minres
-jfnk_pc_type jacobi


[szampini@localhost petsc]$ mpiexec -n 1 ./ex1p --petscopts rc_ex10p_jfnk
Options used:
   --mesh ../torus2.msh
   --petscopts rc_ex10p_jfnk
Number of local H(Curl) unknowns: 70292
Number of global H(Div) unknowns: 508791
Creating Magnet Solver
Number of domains 2
Number of boundaries 4
essential true dofs num 11172
Creating Coefficients
Creating bilinear objects
Hcurl true size every process70292
Hform started 
Hform constructed 
H form Operator created
comm is 1140850688
Start initialization Magnet solver.
Number of H(Curl) unknowns: 70292
Number of H(Div)  unknowns: 508791
H field initialized 
Initialization ODE solver finished.
Writing VisIt files ... done.
Time t= 0.2
H norm 0
H_rhs norm0
BC values initialized 
PETSC
Mult start
nonlinear Mult updated
residual norm 0
 Mult finished
  0 SNES Function norm 0.000000000000e+00 
 Jacobain started 
Jacobian finished 
 use PCfactory 
      Line search: Initial direction and size is 0
Mult startlinesearch
nonlinear Mult updated
residual norm 0.000386108
 Mult finished
Nonlinear  solve did not converge due to DIVERGED_LINE_SEARCH iterations 0


Verification failed: (petsc_solver->GetConverged()) is false:
 --> Newton solver did not converge.
 ... in function: virtual void MagnetodynamicSolver::ImplicitSolve(double, const mfem::Vector&, mfem::Vector&)
 ... in file: /home/szampini/Devel/petsc/arch-h2opus/externalpackages/git.mfem/examples/petsc/ex1p.cpp:635

application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0

```

In parallel instead 
```
[szampini@localhost petsc]$ mpiexec -n 2 ./ex1p --petscopts rc_ex10p_jfnk
Options used:
   --mesh ../torus2.msh
   --petscopts rc_ex10p_jfnk
METIS Error: A contiguous partition is requested for a non-contiguous input graph.



Mesh::GeneratePartitioning:  error in METIS_PartGraphKway!
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0

```

**Comment by brightzhang91** [comment]
> Can you try using 30da55f?
I have run your code using the patch in 30da55f and the error goes away. I have opened an issue in PETSc https://gitlab.com/petsc/petsc/-/issues/940.

Thanks Stefano for this patch !
I run in parallel with this patch and the new `rc_ex10p_jfnk`, the following messages disappeared :
```
==14619== Warning: set address range perms: large range [0x25ecaa028, 0x484374bac) (noaccess)
==14616== Warning: set address range perms: large range [0x2a919c028, 0x518d5894c) (noaccess)
==14617== Warning: set address range perms: large range [0x283a94028, 0x4cdf48b2c) (noaccess)
==14618== Warning: set address range perms: large range [0x28df38028, 0x4e289070c) (noaccess)
```
However convergence is still not achieved, with the message:
`Line search: Initial direction and size is 0`

and 
`Nonlinear  solve did not converge due to DIVERGED_LINE_SEARCH iterations 0`
Why does the Newton solver report non-convergence so early, without doing more iterations ? Parallel run is more important to me so I can abandon serial run if parallel convergence can be achieved.

Thanks ;)
Bright

**Comment by stefanozampini** [comment]
I don't know why it is failing, you should double-check your code to find the cause. Was it running with PETSc 3.14? and with 3.13?
Can you use the same MFEM branch and use an older version of PETSc to confirm?

**Comment by brightzhang91** [comment]
> I don't know why it is failing, you should double-check your code to find the cause. Was it running with PETSc 3.14? and with 3.13?
Can you use the same MFEM branch and use an older version of PETSc to confirm?

 I just changed PETSc 3.15 to 3.14 and ran with the same branch, it shows the same non-convergence problem in the parallel run.  I'm confused if this early termination caused by non-convergence (without iterations) is due to problems in my code or some other problems?
The MFEM examples (such as ex10p) work well.
Thanks !
Bright

**Comment by stefanozampini** [comment]
Again, I don't know what to answer since I have not written the code. Here is what I would do:
- use MFEM 4.2 and PETSc 3.13 . Does it work?
- use MFEM 4.2 and PETSc 3.14 . Does it work?
- use the new branch and PETSc 3.14. Does it work? (answer no)
- use the new branch and PETSc 3.15. Does it work? (answer no)

**Comment by brightzhang91** [comment]
Hi Stefano
After the testing I think the problem is within my code, as neither of the four options work without the non-convergence problem. 
Thanks very much for your support ! It'll be great if you can help think of  some possible causes for the error:

`Nonlinear solve did not converge due to DIVERGED_LINE_SEARCH iterations 0`

Thanks ;)
Bright

**Comment by stefanozampini** [comment]
The only help I can give you is to wish you good luck
