### ISSUE TITLE
Interpolate a grid function at an arbitrary point

### ISSUE THREAD

**Issue by martemyev** [mfem/mfem#23]
Dear all,

I need to compute the value of my solution (a grid function) at a point which may or may not coincide with a dof point, so I need to interpolate it. I didn't find any existing functions for that, so I'm wondering what is best way to do that within MFEM.

Thank you,
Mikhail

**Comment by tzanio** [comment]
Hi Mikhail,

From finite element perspective, it is most natural to evaluate on the reference element, so the physical point where you want the value is represented by the pair `ElementTransformation` (for the mesh element containing the physical point) + `IntegrationPoint` (the point in reference space).

This is our interface for example in the `Eval` method of the `Coefficient` classes (which abstract the idea of a general spatial function), see `FunctionCoefficient::Eval()`.

We have a similar interface for grid functions. The method you are looking for is probably
```
double GridFunction::GetValue(int i, const IntegrationPoint &ip, int vdim)
```
Here `i` is the number of the mesh element, `ip` is the point in reference space, and optionally `vdim` is the vector component you are interested in, see also `GridFunctionCoefficient::Eval()`.

Note that there are other similar methods of `GridFunction`, for vector-valued functions, or for simultenuous evaluation at multiple points.

Hope this helps,
Tzanio

**Comment by martemyev** [comment]
Hi Tzanio,

Thank you for your reply! So, the question is - how do I find the mesh element containing my point?

Thank you,
Mikhail

**Comment by tzanio** [comment]
Hi Mikhail,

This is not a typical operation with finite elements. Can you provide more details in what context do you need it?

In the most general case, you will have to find a set of nearby elements (e.g. by looking if the point is in their bounding boxes) and invert the mapping for each of them to see if the point is an image of a point inside the reference element (e.g. using Newton). This general algorithm is expensive and we don�t have it in the release. We have all the tools for it though, and we�ll be happy to help you implement it if that�s what you need.

Cheers,
Tzanio

**Comment by martemyev** [comment]
Tzanio,

Thank you for your suggestion, I appreciate that! I'm solving a geophysical problem of a seismic wave propagation, and I need to compute the solution at the so-called 'geophones' - a set of points in the domain which are set up independently of the mesh. What I have seen in other programs - people just look for the dof points closest to the real 'geophones' and get the solution from there. That might work for me as well, so there is no need to implement the finite element search.
But for the sake of interest, could you please look at the minimal code example below, and say where I'm wrong in the computation of the solution at the vertices of the mesh:

```c
#include "mfem.hpp"
#include <fstream>
#include <iostream>
#include <stdexcept>

using namespace std;
using namespace mfem;

const int NX = 10;
const int NY = 10;
const int ORDER = 1;

void get_nodal_values_my_way(Mesh &mesh, const GridFunction &x, 
                             Vector &x_at_nodes);

int main(int argc, char *argv[])
{
   Mesh mesh(NX, NY, Element::QUADRILATERAL);
   int dim = mesh.Dimension();

   FiniteElementCollection *fec = new H1_FECollection(ORDER, dim);
   FiniteElementSpace fespace(&mesh, fec);
   cout << "Number of unknowns: " << fespace.GetVSize() << endl;

   LinearForm b(&fespace);
   ConstantCoefficient one(1.0);
   b.AddDomainIntegrator(new DomainLFIntegrator(one));
   b.Assemble();

   GridFunction x(&fespace);
   x = 0.0;

   BilinearForm a(&fespace);
   a.AddDomainIntegrator(new DiffusionIntegrator(one));
   a.Assemble();
   Array<int> ess_bdr(mesh.bdr_attributes.Max());
   ess_bdr = 1;
   a.EliminateEssentialBC(ess_bdr, x, b);
   a.Finalize();
   const SparseMatrix &A = a.SpMat();

   GSSmoother M(A);
   PCG(A, M, b, x, 1, 200, 1e-12, 0.0);
   
   Vector x_at_nodes;
   x.GetNodalValues(x_at_nodes);
   
   Vector x_at_nodes_my_way;
   get_nodal_values_my_way(mesh, x, x_at_nodes_my_way);
   
   cout << "\nSolution at nodes\n";
   for (int i = 0; i < x_at_nodes.Size(); ++i)
      cout << i << " " << x_at_nodes(i) 
           << " " << x_at_nodes_my_way(i) << "\n";

   delete fec;
}

// Auxiliary function printing coordinates of all vertices of the cell 'i' in
// the std::cout, and checking that the vertex 'vertex' belongs to this cell
void show_vertices(const Mesh &mesh, int i, const double *vertex)
{
   const Element *cell = mesh.GetElement(i);
   Array<int> vert_indices;
   cell->GetVertices(vert_indices);
   cout << "vert: ";
   for (int v = 0; v < vert_indices.Size(); ++v)
   {
      const double *vert = mesh.GetVertex(vert_indices[v]);
      cout << "(" << vert[0] << ", " << vert[1] << ") ";
   }
   const double tol = 1e-12;
   const double *vert0 = mesh.GetVertex(vert_indices[0]); // min coords
   const double *vert2 = mesh.GetVertex(vert_indices[2]); // max coords
   if (vert0[0] > vertex[0]+tol || vert0[1] > vertex[1]+tol ||
       vert2[0] < vertex[0]-tol || vert2[1] < vertex[1]-tol)
     throw runtime_error("Didn't pass the test");
}

// Compute the values of the grid function 'x' at the vertices of the mesh
void get_nodal_values_my_way(Mesh &mesh, const GridFunction &x, 
                             Vector &x_at_nodes)
{
   x_at_nodes.SetSize(mesh.GetNV());
   cout << "\nVertices of the mesh\n";
   for (int v = 0; v < mesh.GetNV(); ++v)
   {
      const double *vert = mesh.GetVertex(v); // coordinates of the vertex
      int cellx = vert[0]*NX; if (cellx) --cellx;
      int celly = vert[1]*NY; if (celly) --celly;
      const int cell  = celly*NX + cellx; // index of the cell containing the vertex
      cout << v << " (" << vert[0] << ", " << vert[1] 
           << ") cell " << cell << " ";
      show_vertices(mesh, cell, vert); // to check that we found it correctly
      
      ElementTransformation *T = mesh.GetElementTransformation(cell);
      
      IntegrationPoint ip;
      ip.Set2(vert); // original vertex
      Vector transip;
      T->Transform(ip, transip); // the corresponding reference point
      ip.Set2(transip);
      cout << " -> ref point: (" << ip.x << ", " << ip.y << ") ";
      
      x_at_nodes(v) = x.GetValue(cell, ip);
      cout << endl;
   }
}
```

**Comment by tzanio** [comment]
Hi Mikhail,

I see. Are the meshes you use Cartesian? If they have some structure, it might be much easier to determine the element in which the point is.

The issue I see with the code is that ElementTransformation transforms from *reference* to *physical* coordinates. Also, it is generally better to loop over the elements, compute the values at local vertices and set them in the global vector. So the following may work better for you:

```c++
// Compute the values of the grid function 'x' at the vertices of the mesh
void get_nodal_values_my_way(Mesh &mesh, const GridFunction &x,
                             Vector &x_at_nodes)
{
   x_at_nodes.SetSize(mesh.GetNV());
   cout << "\nVertices of the mesh\n";

   // Array with the coordinates of the vertices of the reference element
   const IntegrationRule *rv = Geometries.GetVertices(Geometry::SQUARE);
   for (int i = 0; i < mesh.GetNE(); i++)
   {
      Array<int> v;
      mesh.GetElementVertices(i, v); // global vertex numbers for current element
      for (int j = 0; j < v.Size(); j++)
         x_at_nodes[v[j]] = x.GetValue(i, rv->IntPoint(j));
   }
}
```

Hope this helps,
Tzanio

**Comment by martemyev** [comment]
Tzanio,

Thank you for the code. It indeed works for the vertices. But the comparison of solution at nodes was just for an example and to help better understand how it works in MFEM. Therefore, I have the following question: how do I get a point in a reference space, if I know the physical point, and the mesh element it belongs to?

> The issue I see with the code is that ElementTransformation transforms from reference to physical coordinates.

I disagree. If I set up a domain with sx and sy (size!=1) parameters of the Mesh constructor, the vertices over which I’m looping are clearly physical. The “reference” points that I get in this case are weird, though. So, in general I agree that I’m doing wrong things here. And, this just pushes me further in asking - how to get the reference point right.

Thank you,
Mikhail

**Comment by tzanio** [comment]
Hi Mikhail,

What I meant is that in `T->Transform(ip, transip)`, the argument `ip` should be in reference space, i.e. `T->Transform` maps reference to physical points. In the code above, the call `Geometries.GetVertices(Geometry::SQUARE)` gets the coordinates of the vertices of the reference square, i.e. `[0,1]^2`. You can call this with other geometries to get their reference element vertices.

If you know a physical point, `transip`, and the ElementTransofrmation, `T`, of the mesh element it belongs to, then to get the corresponding point in reference space, `ip`, you have to invert the mapping `T->Transform(ip, transip)`. In general this mapping is non-linear so the inversion requires a non-linear solver, e.g. Newton. If the mapping is linear, e.g. `ip = (hatx, haty) -> transip = (x0 + hatx hx, y0 + haty hy)`, then the inversion is much easier: `transip = (x,y) -> ip = ((x-x0)/hx, (y-y0)/hy)`.

Hope this helps,
Tzanio

**Comment by martemyev** [comment]
Hi Tzanio,

Thanks a lot! Now I got that `Transform` does the opposite thing.
Your suggestion of the inverse transformation for Cartesian grids is quite enough for me right now, so I'm going to use it.

Best regards,
Mikhail
