### ISSUE TITLE
SparseMat error with skip_zeros=2

### ISSUE THREAD

**Issue by wcdawn** [mfem/mfem#2302]
I recently implemented `skip_zeros=2` behavior to skip all zeros regardless of symmetry in the matrix #2087. It's leading to some weird behavior in `SparseMatrix::EliminateRowCol()`.

```
SparseMatrix::EliminateRowCol() #3
Abort(1) on node 0 (rank 0 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
```

The error comes from [here](https://github.com/mfem/mfem/blob/e56071003a7fc6f85211730ddaa0903346621566/linalg/sparsemat.cpp#L1733). I'm not really sure what this code is supposed to be doing.
The code runs as expected with `skip_zeros=1` (the default option).

**Comment by v-dobrev** [comment]
This method can work only when the sparse matrix has a symmetric sparsity pattern -- it uses that symmetry to avoid searching all rows for the column `rc` that it needs to eliminate.

**Comment by wcdawn** [comment]
I'm surprised I didn't encounter this error sooner then! Would it be feasible to implement a general/unsymmetric version or is that going to be to slow/expensive?

For a quick fix, I can just check if I need to do `EliminateRowCol` and if I do, preserve symmetry.

**Comment by v-dobrev** [comment]
For the non-symmetric sparsity pattern case, one can implement a method that takes a Boolean array that indicates which rows/columns need to be eliminated -- with such input the elimination can be done in a single pass over the whole sparse matrix.

**Comment by tzanio** [comment]
@wcdawn, were you able to resolve this?

**Comment by wcdawn** [comment]
No. My large problems do not have essential BCs so it isn't a problem for the very largest problems.
As a quick patch for now, in my routines I have something like
```cpp
const int skip_zeros = if_any_bc_is_essential ? 1 : 2;
```

I haven't had time to implement a better solution in MFEM.
The easiest thing would be to introduce a private member variable to store the user-specified value for `skip_zeros` but that would add more data to track.
