### ISSUE TITLE
list of supported AMD GPUs

### ISSUE THREAD

**Issue by koomie** [mfem/mfem#2307]
Any chance there is a known list of AMD GPUs that are currently being tested with MFEM (or that should be known to work)?  We have a wimpy Radeon PRO WX 3200 with HIP 4.2 installed just to have a sandbox test environment (not for performance), but can't seem to get thru an MFEM build.  We see stack size limits exceeded so assuming this card is probably not supported and wondering if there is a list with cards that are known to work?

Example build errors...
 ```
error: stack size limit exceeded (143376) in _ZN4mfemL11HipKernel1DIZNS_26FaceQuadratureInterpolator6Eval3DILi1ELi64ELi216EEEviiRKNS_9DofToQuadERKNS_5ArrayIbEERKNS_6Vector
ERSA_SD_SD_SD_iEUliE_EEviT_
error: stack size limit exceeded (143376) in _ZN4mfemL11HipKernel2DIZNS_26FaceQuadratureInterpolator6Eval3DILi1ELi64ELi216EEEviiRKNS_9DofToQuadERKNS_5ArrayIbEERKNS_6Vector
ERSA_SD_SD_SD_iEUliE_EEviT_i
error: stack size limit exceeded (143376) in _ZN4mfemL11HipKernel3DIZNS_26FaceQuadratureInterpolator6Eval3DILi1ELi64ELi216EEEviiRKNS_9DofToQuadERKNS_5ArrayIbEERKNS_6Vector
ERSA_SD_SD_SD_iEUliE_EEviT_
error: stack size limit exceeded (250032) in _ZN4mfemL11HipKernel1DIZNS_26FaceQuadratureInterpolator6Eval3DILi1ELi125ELi125EEEviiRKNS_9DofToQuadERKNS_5ArrayIbEERKNS_6Vecto
rERSA_SD_SD_SD_iEUliE_EEviT_
error: stack size limit exceeded (250032) in _ZN4mfemL11HipKernel2DIZNS_26FaceQuadratureInterpolator6Eval3DILi1ELi125ELi125EEEviiRKNS_9DofToQuadERKNS_5ArrayIbEERKNS_6Vecto
rERSA_SD_SD_SD_iEUliE_EEviT_i
error: stack size limit exceeded (250032) in _ZN4mfemL11HipKernel3DIZNS_26FaceQuadratureInterpolator6Eval3DILi1ELi125ELi125EEEviiRKNS_9DofToQuadERKNS_5ArrayIbEERKNS_6Vecto
rERSA_SD_SD_SD_iEUliE_EEviT_
error: stack size limit exceeded (341024) in _ZN4mfemL11HipKernel1DIZNS_26FaceQuadratureInterpolator6Eval3DILi1ELi125ELi216EEEviiRKNS_9DofToQuadERKNS_5ArrayIbEERKNS_6Vecto
rERSA_SD_SD_SD_iEUliE_EEviT_
error: stack size limit exceeded (341024) in _ZN4mfemL11HipKernel2DIZNS_26FaceQuadratureInterpolator6Eval3DILi1ELi125ELi216EEEviiRKNS_9DofToQuadERKNS_5ArrayIbEERKNS_6Vecto
rERSA_SD_SD_SD_iEUliE_EEviT_i
error: stack size limit exceeded (341024) in _ZN4mfemL11HipKernel3DIZNS_26FaceQuadratureInterpolator6Eval3DILi1ELi125ELi216EEEviiRKNS_9DofToQuadERKNS_5ArrayIbEERKNS_6Vecto
rERSA_SD_SD_SD_iEUliE_EEviT_
hipcc   -O3 -std=c++11 --amdgpu-target=gfx803   -c fem/lininteg.cpp -o fem/lininteg.o
```

Thanks for any pointers.

**Comment by artv3** [comment]
I've actually encountered the same issue with HIP 4.1. I've been able to build MFEM with HIP 4.0 and below.

**Comment by v-dobrev** [comment]
Thank you for reporting this issue. This type of errors seem to be related to the ROCm version -- they started to appear with ROCm v4.1. We are aware of the issue and will try to address it in the near future.

In the mean time you can try commenting out some of the higher-order `Eval3D` kernels instantiated in `FaceQuadratureInterpolator::Mult`, and other places where such an error is generated.

**Comment by artv3** [comment]
Actually could this PR help https://github.com/mfem/mfem/pull/2301 ? I think the FaceQuadratureInterpolator was templated on rather high dof/quad values --- not the 1D variants.

**Comment by v-dobrev** [comment]
> Actually could this PR help #2301 ? It lowers the template value in some of the methods.

Good point, you maybe right. We should test that.

**Comment by artv3** [comment]
It might be that we will need to lower the `max_Q1D/D1D` values. I don't think those kernels use shared memory

**Comment by koomie** [comment]
Probably not new information, but if I disable the following two calls after applying PR #2301, I can then complete the build. 

```
diff --git a/fem/bilininteg_convection_pa.cpp b/fem/bilininteg_convection_pa.cpp
index 84e772a05..9cd381e34 100644
--- a/fem/bilininteg_convection_pa.cpp
+++ b/fem/bilininteg_convection_pa.cpp
@@ -862,7 +862,7 @@ static void PAConvectionApply(const int dim,
          case 0x67: return SmemPAConvectionApply3D<6,7>(NE,B,G,Bt,Gt,op,x,y);
          case 0x78: return SmemPAConvectionApply3D<7,8>(NE,B,G,Bt,Gt,op,x,y);
          case 0x89: return SmemPAConvectionApply3D<8,9>(NE,B,G,Bt,Gt,op,x,y);
-         default:   return PAConvectionApply3D(NE,B,G,Bt,Gt,op,x,y,D1D,Q1D);
+        // default:   return PAConvectionApply3D(NE,B,G,Bt,Gt,op,x,y,D1D,Q1D);
       }
    }
    MFEM_ABORT("Unknown kernel.");
diff --git a/fem/bilininteg_hcurl.cpp b/fem/bilininteg_hcurl.cpp
index 522ba47b4..967731daf 100644
--- a/fem/bilininteg_hcurl.cpp
+++ b/fem/bilininteg_hcurl.cpp
@@ -2502,11 +2502,13 @@ void CurlCurlIntegrator::AssembleDiagonalPA(Vector& diag)
                                                                 pa_data, diag);
          }
       }
+      #if 0
       else
          PACurlCurlAssembleDiagonal3D(dofs1D, quad1D, symmetric, ne,
                                       mapsO->B, mapsC->B,
                                       mapsO->G, mapsC->G,
                                       pa_data, diag);
+      #endif
    }
    else if (dim == 2)
    {
``` 

If there are lower values for D1D you want me to try locally, I'm happy to give it a whirl.

**Comment by artv3** [comment]
I would be guessing for which values would work, but the idea would be to lower the values from this file: 

https://github.com/mfem/mfem/blob/6785e1d1afd7400ac1bbef975daa2d7cad412f92/general/forall.hpp#L26-L27

**Comment by koomie** [comment]
Ok, just by trial and error the largest value I can use for those constants is `MAX_D1D=11` to successfully build bilininteg_convection_pa.cpp.  Unfortunately, there is no impact on the resulting stacksize errors generated when changing these constants for the `PACurlCurlAssembleDiagonal3D()` call. 

Here is a quick summary of running test cases:

#### Runs with MAX_D1D/MAX_Q1D=14; two offending calls in bilininteg_convection_pa.cpp and bilininteg_hcurl.cpp commented out.

```
$ grep -i fail test.log 
    Unit tests [ unit_tests ... ]: FAILED  (1.39s 48224kB)
/home/karl/downloads/mfem/clone/mfem/tests/unit/fem/test_assemblediagonalpa.cpp:493: FAILED:
/home/karl/downloads/mfem/clone/mfem/tests/unit/fem/test_assembly_levels.cpp:129: FAILED:
test cases:  58 |  56 passed | 2 failed
assertions: 802 | 800 passed | 2 failed
Some tests failed.
```

#### Runs with MAX_D1D/MAX_Q1D=11;  one offending call in bilininteg_hcurl.cpp commented out.
```
$ grep -i fail test-d1d-11.log 
    Unit tests [ unit_tests ... ]: FAILED  (20.42s 101528kB)
/home/karl/downloads/mfem/clone/mfem/tests/unit/fem/test_assemblediagonalpa.cpp:493: FAILED:
test cases:    146 |    145 passed | 1 failed
assertions: 233087 | 233086 passed | 1 failed
Some tests failed.
```

**Comment by artv3** [comment]
Thanks! I Looking at the hcurl kernel I think its the following two allocations: 

https://github.com/mfem/mfem/blob/master/fem/bilininteg_hcurl.cpp#L2142

and 

https://github.com/mfem/mfem/blob/master/fem/bilininteg_hcurl.cpp#L2175

Which use the following max/mins: 

https://github.com/mfem/mfem/blob/25e59797c1e07b1de42937fac8acb641abba2a1f/fem/bilininteg.hpp#L23-L24

**Comment by koomie** [comment]
Bingo!

Local build worked for me if I dialed down `HCURL_MAX_Q1D = 5`. With that additional change,  all tests passed with a local `make test`.

**Comment by artv3** [comment]
> Bingo!
> 
> Local build worked for me if I dialed down `HCURL_MAX_Q1D = 5`. With that additional change, all tests passed with a local `make test`.

Yes!!! would you be interested in making a PR?

**Comment by koomie** [comment]
> 
> Yes!!! would you be interested in making a PR?

Sure thing. Will try to submit something a bit later today...

**Comment by tzanio** [comment]
Discussion continued in #2319
