### ISSUE TITLE
HowTo Article: Using findpts 

### ISSUE THREAD

**Issue by acfisher** [mfem/mfem#2308]
We could use an article describing the ins and outs of using findpts to get the element and local coordinate of a given point in global coordinates.

**Comment by acfisher** [comment]
For the meantime put it in this branch of the web repo:
https://github.com/mfem/web/tree/searchable-articles/src/howto
Examples can be found in that folder.

@kmittal2 can you handle this?

**Comment by kmittal2** [comment]
Yes, I will start working on this.

**Comment by acfisher** [comment]
We now have an article, thanks @kmittal2 .
