### ISSUE TITLE
HowTo:  Using a spack install of MFEM

### ISSUE THREAD

**Issue by acfisher** [mfem/mfem#2310]
We could use an article describing how to use a spack install of MFEM. For the meantime put it in this branch of the web repo:

https://github.com/mfem/web/tree/searchable-articles/src/howto

Examples can be found in that folder.

**Comment by acfisher** [comment]
@adrienbernede can you put this together?

**Comment by adrienbernede** [comment]
OK, OK, I’ll do it :D

**Comment by adrienbernede** [comment]
@acfisher Do we agree that what you meant with the title was "install MFEM using Spack", or are you looking for something specific?

**Comment by tzanio** [comment]
Discussion continued in https://github.com/mfem/web/pull/118
