### ISSUE TITLE
Howto:  Map between local element numbering and parallel global element numbering

### ISSUE THREAD

**Issue by acfisher** [mfem/mfem#2311]
We could use an article describing how to working with local and global element numbering. For the meantime put it in this branch of the web repo:

https://github.com/mfem/web/tree/searchable-articles/src/howto

Examples can be found in that folder.

**Comment by acfisher** [comment]
@rw-anderson Can you put this together?

**Comment by rw-anderson** [comment]
The facility that I know about (that I wrote in a few lines of code) is almost trivial, and likely doesn't cover a broad range of use cases that people might want to have, but I can provide a code snippet or two if that will be helpful.

**Comment by psocratis** [comment]
This is already addressed by some recently added methods in the `pmesh` class, not only for elements but for all geometric entities. I believe @dylan-copeland did this. 

````cpp
   void GetGlobalVertexIndices(Array<HYPRE_Int> &gi) const;
   /// AMR meshes are not supported.
   void GetGlobalEdgeIndices(Array<HYPRE_Int> &gi) const;
   /// AMR meshes are not supported.
   void GetGlobalFaceIndices(Array<HYPRE_Int> &gi) const;
   /// AMR meshes are supported.
   void GetGlobalElementIndices(Array<HYPRE_Int> &gi) const;
````

**Comment by rw-anderson** [comment]
Maybe @dylan-copeland is a more natural assignee to this one then.

**Comment by dylan-copeland** [comment]
I can write this article. How soon should it be done?

**Comment by acfisher** [comment]
@rw-anderson yeah I saw you wrote those lines of code a while back which is how you got tagged.  I did miss the new methods being added.  @dylan-copeland thanks for stepping in, the next week or two would be fine.  Don't let it get in the way of your work on enabling the latest version of Hypre in MFEM.

**Comment by dylan-copeland** [comment]
This is done in commit 3334b405efdda6007bcc2d72b89bf815c0e4b713

**Comment by dylan-copeland** [comment]
@acfisher It took me a while to figure out that `python -m mkdocs serve` is necessary. It would be helpful to comment on this in the `README.md`.

**Comment by tzanio** [comment]
@dylan-copeland, can you clarify -- for me `mkdocs serve` works on both my Mac and tux boxes

**Comment by dylan-copeland** [comment]
@tzanio `mkdocs serve` does not work on my Mac. Also on my tux box, it is necessary, because there `python` is python 2.7. The README could just say that on some machines or environments, `python3 -m mkdocs serve` may be needed.

**Comment by tzanio** [comment]
OK, lets add that addition.

It probably depends what's the default python on your system and how did you install mkdocs.

**Comment by acfisher** [comment]
Yes, the later versions of mkdocs want python3.  I'll put that in the readme.  Thanks for getting the article in.
