### ISSUE TITLE
Calculation of surface integrals with vector-valued integrand

### ISSUE THREAD

**Issue by chikitkin** [mfem/mfem#2316]
Dear MFEM community,

Can I compute a surface integral from terms which are not dot products? For example:
![image](https://user-images.githubusercontent.com/7203771/121325635-6f62a300-c91a-11eb-9e11-53521f45cb19.png)
where E is the solution (vector), G is scalar Green's function. 
This integral is used for far-field computation in EM simulations.
I understand that it can be implemented by replicating the interior of Assemble functions with some modifications, but I wonder if this can be done with high-level MFEM API?

Thank you in advance.

**Comment by mlstowell** [comment]
Hello, Aleksandr (@chikitkin),

The short answer is yes, as long as the integral is linear in the solution vector. Of course, the details can get complicated. You would need a `LinearFormIntegrator` which computes the necessary integrals using `G` and `Grad(G)`. This would integrate the above integral replacing `E` with the basis functions used to approximate `E`. When this `LinearFormIntegrator` is added to a `ParLinearForm` object and assembled you'll have a vector which is the same length as the `ParGridFunction` `E`. Finally, when you compute the inner product of this `ParLinearForm` object with `E` the result will be the value of the surface integral.

Our collection of `LinearFormIntegrators` is bit limited, see [Linear Form Integrators](https://mfem.org/lininteg/). It looks like many of pieces you would need are there but you would probably need to create a custom integrator (or three) which combines the necessary pieces.

Best wishes,
Mark

**Comment by chikitkin** [comment]
Thank you, Mark @mlstowell, I see. 
I checked **Linear Form Integrators** carefully, but it seems that there are no suitable integrators there.

**Comment by mlstowell** [comment]
Hello, @chikitkin,

Sorry, my mistake. I ignored the fact that you called `G` a Green's function. In theory you could use a `ParLinedarForm` to compute these integrals but it would be completely impractical because you would need to form a separate linear form for each value of `r`.

We don't work with Green's functions in the finite element method, at least not that I've seen.

Best wishes,
Mark
