### ISSUE TITLE
Preconditioners for Partial Assembly?

### ISSUE THREAD

**Issue by wcdawn** [mfem/mfem#2317]
I've been struggling to store my matrix operator in memory so I'm trying to look into partial assembly.
From what I can tell from the examples, it looks like my only options for a preconditioner are `ceed::AlgebraicSolver` or `OperatorJacobiSmoother` (e.g. `ex1p` [here](https://github.com/mfem/mfem/blob/48435d9570c47e6e5b0bdd9adbeb8a043b117b3d/examples/ex1p.cpp#L228-L241)).
Both of these preconditioners require `UsesTensorBasis(fespace)==true`.

I don't really want to restrict myself to tensor basis finite elements (e.g. quads in 2d). I'd like to be able to use triangular elements.
Is this possible?

This could also be a nice addition to the recently opened #2313.
Thanks!

**Comment by v-dobrev** [comment]
Unfortunately, triangles and tets are not currently supported even just for the bilinear form action. At least most of the integrators that have support for `AssemblyLevel::PARTIAL`, only support quads and hexes.

Depending on what integrators you need, it may be possible to use the template code for partial assembly -- its use is demonstrated in `miniapps/performance` for the diffusion integrator. This version supports triangles and tets but it is not currently available through the `(Par)BilinearForm` classes.

**Comment by v-dobrev** [comment]
One remark: if you are not using high-order solution spaces, e.g. order >=3 in 2D or order >= 2 in 3D, the use of partial assembly may not be that beneficial for both speed and memory consumption.

**Comment by v-dobrev** [comment]
Going back to your original question about preconditioners for partial assembly: the best choice at this point is probably to use the so-called LOR (or FEM-SEM) preconditioner -- it is enabled by the option `-pc lor` in `ex1p.cpp` in `miniapps/performance`. However, I'm not sure this has been tested with triangles and tets. Support for these elements for LOR preconditioning was added recently by @pazner -- he can give you more details about the right way to set it up. You can also take a look at the new LOR solvers miniapp: `miniapp/solvers/{lor,plor}_solvers.cpp`.

**Comment by nbeams** [comment]
Do the preconditioners require tensor basis if libCEED is enabled?  Some of the libCEED backends allow triangles and tetrahedrons, but I don't know about their use with the mentioned preconditioners.

**Comment by pazner** [comment]
Regarding the LOR preconditioners, they should work (but might not be particularly effective) with all element types. If they don't, then this is a bug that I can try to fix. The main issue is that the preconditioners are only robust with respect to the polynomial degree for quads and hexes, so for high order simplex elements the iteration counts could be quite large.

**Comment by YohannDudouit** [comment]
Triangles and tets are actually supported through libCEED, you might have to specify the backend since the default CUDA backend `/gpu/cuda/gen` does not support triangles and tets currently, suing `-d ceed-cuda:/gpu/cuda/shared` for instance. The `OperatorJacobiSmoother` should work in that case since it will use the diagonal computation from libCEED.

**Comment by wcdawn** [comment]
Thanks to everyone for the input.
It sounds like using Partial Assembly with triangles is possible using the CEED backend. Additionally, LOR may offer some opportunities.

Unfortunately for our problem, we're having trouble storing first-order linear finite elements in memory so it sounds like Partial Assembly may not be that helpful, even if it doesn't suffer from being ineffective.

Thanks!
