### ISSUE TITLE
HowTo article:  Navigating AMR meshes

### ISSUE THREAD

**Issue by acfisher** [mfem/mfem#2321]
We could use a high level article describing how to use the group communicators. For the meantime put it in this branch of the web repo:

https://github.com/mfem/web/tree/searchable-articles/src/howto

Examples can be found in that folder.

**Comment by acfisher** [comment]
Looking for someone to write this one.  Maybe @jakubcerveny if he is not too busy working on others.

**Comment by tzanio** [comment]
Discussion continued in https://github.com/mfem/web/pull/123
