### ISSUE TITLE
On the problem of solving beam element

### ISSUE THREAD

**Issue by HFH104864** [mfem/mfem#2324]
Dear MFEM  
  Now I have a mesh model with a beam element of type,I wonder if MFEM can solve the linear elasticity problem of beam element?
And If so, are there any hints or examples of what I should do

**Comment by v-dobrev** [comment]
Example 2 (serial) and example 2p (parallel) illustrate how to solve a linear elasticity problem.

**Comment by HFH104864** [comment]
Yes I know that . But if for a mesh model, its mesh element is beam element, I am not sure whether ex2 works

**Comment by tzanio** [comment]
Can you clarify what you mean by "beam element"? 

We support (standard) volume nodal elements for elasticity, see for example Chapter 5 in [Numerical Solution of Partial Differential Equations by the Finite Element Method](https://www.amazon.com/Numerical-Solution-Differential-Equations-Mathematics/dp/048646900X) by Claes Johnson.

**Comment by HFH104864** [comment]
the mean is that My model is discrete into a finite number of beam elements (just like tetrahedral elements).

**Comment by HFH104864** [comment]
In other words, for a statically indeterminate truss structure composed of one-dimensional beam elements, does MFEM have a method to solve it?

**Comment by tzanio** [comment]
I think I understand what you mean, but it will help if you can attach a picture.

If you indeed want to model a 3D beam with only 1D elements that e.g. the edges of a 3D mesh, then I'm not sure how easy/effective it will be to use MFEM. It is probably possible, but what we would typically do in this case is to use volume elements in the 3D mesh.

**Comment by HFH104864** [comment]
Actually, it's just an idea of mine. I don't have a real model of this type .It might look something like this.

![model](https://user-images.githubusercontent.com/69201217/122175069-e87f6e80-ceb5-11eb-8763-9e25b721d6f6.png)

Or a two dimensional truss as follows.

![model2](https://user-images.githubusercontent.com/69201217/122175886-95f28200-ceb6-11eb-8407-115e6671e57f.png)

In this model, its beam will include some parameters, such as cross-sectional area, length, etc., and whether MFEM can process these parameters and conduct finite element analysis on them

**Comment by tzanio** [comment]
If it was me, I'd discretize the first image as a volume mesh, because there are clearly some 3D effects with non-trivial thickness.

This is not exactly my area though, maybe @bslazarov or @Dan2997925 can help?

**Comment by HFH104864** [comment]
Unfortunately, I have a reason to use beam element. Therefore, my idea is to discretize the model in the first figure into beam elements, that is, to add nodes and one-dimensional line segments to each beam.In ANSYS, applying boundary conditions to a beam element is done by adding boundary conditions to a one-dimensional line segment (that is, the beam element), and I'm not sure if MFEM can do the same

**Comment by tzanio** [comment]
ping: @bslazarov, @Dan2997925

**Comment by bslazarov** [comment]
Hi,

MFEM does not work with beam elements. Such elements can be implemented; however, the development would require quite many changes in the code.  


What I can see in the second picture is a standard truss-like structure. If you do not have bending moments/rotations in the nodes, I recommend using Matlab directly to handle the discretization and the solution. If you do have bending DOFs, it will be a bit more tedious but still possible to be implemented and solved in Matlab. It is worth googling for free academic codes and examples for solving such problems. I had many implementations for solving beam/truss problems for computational mechanics courses - unfortunately, I do not keep them around.

**Comment by HFH104864** [comment]
well , thank you for your suggestions . But obviously I need to learn more about it . Anyway , thank you for your help , and I will close it.
