### ISSUE TITLE
"CUSPARSE_SPMV_CSR_ALG1" is undefined

### ISSUE THREAD

**Issue by Jacobfaib** [mfem/mfem#2336]
Compiling mfem with cuda support on ORNL Summit using the cuda 11.2.0 module. 

Full error mssage
----
```
$ nvcc -Xcompiler=-fPIC  -g -Xcompiler=-Wall -std=c++14 -x=cu --expt-extended-lambda -arch=sm_70 -ccbin mpicxx \
-I/ccs/home/jfaibussow/petsc/arch-olcf-summit-streams-debug/include \
-I/ccs/home/jfaibussow/petsc/arch-olcf-summit-streams-debug/include  -I/ccs/home/jfaibussow/petsc/include \
-I/ccs/home/jfaibussow/petsc/arch-olcf-summit-streams-debug/include -I/sw/summit/cuda/11.2.0/include  \
-c linalg/complex_operator.cpp -o linalg/complex_operator.o

linalg/sparsemat.cpp(694): error: identifier "CUSPARSE_SPMV_CSR_ALG1" is undefined
```

Version info
-----
Output of `make info`:  [mfemInfo.txt](https://github.com/mfem/mfem/files/6666100/mfemInfo.txt)

```
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Nov_30_19:09:01_PST_2020
Cuda compilation tools, release 11.2, V11.2.67
Build cuda_11.2.r11.2/compiler.29373293_0

$ echo $CUDA_DIR
/sw/summit/cuda/11.2.0
```

**Comment by Jacobfaib** [comment]
As a workaround I plopped
```
#define CUSPARSE_SPMV_CSR_ALG1 CUSPARSE_CSRMV_ALG1
```
at the top of `linalg/sparsemat.cpp` and everything compiled cleanly.

**Comment by YohannDudouit** [comment]
I'm confused we're supposed to have addressed this in: https://github.com/mfem/mfem/pull/2200

**Comment by YohannDudouit** [comment]
Could you check if replacing `#if CUDA_VERSION >= 11020` with `#if CUDA_VERSION >= 11021` in `linalg/sparsemat.cpp` solves this issue?

**Comment by Jacobfaib** [comment]
> Could you check if replacing `#if CUDA_VERSION >= 11020` with `#if CUDA_VERSION >= 11021` in `linalg/sparsemat.cpp` solves this issue?

This works.

**Comment by YohannDudouit** [comment]
I just tried on Lassen, the problem is that if I change for `#if CUDA_VERSION >= 11021`, and use `cuda-11.2.0`, then I get the following warning:
```
linalg/sparsemat.cpp:724:119: warning: 'CUSPARSE_CSRMV_ALG1' is deprecated: please use CUSPARSE_SPMV_CSR_ALG1 instead [-Wdeprecated-declarations]
cusparseSpMV(handle, CUSPARSE_OPERATION_NON_TRANSPOSE, &alpha, matA_descr, vecX_descr, &beta, vecY_descr, CUDA_R_64F, CUSPARSE_CSRMV_ALG1, dBuffer); 
                                                                                                                      ^
/usr/tce/packages/cuda/cuda-11.2.0/nvidia/bin/../targets/ppc64le-linux/include/cusparse.h:6314:1: note: 'CUSPARSE_CSRMV_ALG1' has been explicitly marked deprecated here
CUSPARSE_CSRMV_ALG1 __attribute((deprecated("please use CUSPARSE_SPMV_CSR_ALG1 instead"))), 
```
That confuses me about what version of cuda Summit is actually using, it doesn't seem to behave the same...

**Comment by Jacobfaib** [comment]
Yeah it does seem like summits version is a bit wonky. When loading the cuda module on summit one is met with:
```
---------------------------------------------------------------------------------------------------
There are messages associated with the following module(s):
---------------------------------------------------------------------------------------------------

cuda/11.2.0:
  This modulefile is provided for testing purposes only. If you encounter
  issues, please report them to help@olcf.ornl.gov.

---------------------------------------------------------------------------------------------------
```
I figured this might refer to some experimental backend implementations not missing features... I will send mail to the ornl help desk about this. Maybe they have more insight.

**Comment by Jacobfaib** [comment]
Alrighty so after getting in touch with the ORNL folks they mentioned that:
> Cuda 11.3.0 documentation, where CUSPARSE_CSRMV_ALG1 was deprecated. In the 11.2.0 documentation (https://docs.nvidia.com/cuda/archive/11.2.0/cusparse/index.html#cusparse-generic-function-spmv) you can see that CUSPARSE_CSRMV_ALG1 is the only one present and CUSPARSE_SPMV_CSR_ALG1 is not defined at all. That missing definition is probably what you are running into in this case.

With that I inspected the respective `$CUDA_[HOME|DIR]/include/cusparse.h` for both Lassen and Summit and lo and behold

Lassen:
```
#define CUSPARSE_VER_MAJOR 11
#define CUSPARSE_VER_MINOR 4
#define CUSPARSE_VER_PATCH 1
#define CUSPARSE_VER_BUILD 1152
```

Summit:
```
#define CUSPARSE_VER_MAJOR 11
#define CUSPARSE_VER_MINOR 3
#define CUSPARSE_VER_PATCH 1
#define CUSPARSE_VER_BUILD 68
```
So maybe its not the cuda version that needs checking but the cusparse version.

**Comment by YohannDudouit** [comment]
@Jacobfaib Would you have an idea of what would be the correct value to check for CuSparse?
Also did you see that [comment](https://github.com/mfem/mfem/issues/2164#issuecomment-826440946) by @adam-sim-dev

**Comment by Jacobfaib** [comment]
> @Jacobfaib Would you have an idea of what would be the correct value to check for CuSparse?
Also did you see that comment by @adam-sim-dev

Yeah which is why I am doubly confused as to why summits cusparse doesn't have this value defined. In fact, it does not even throw a deprecation warning for `CUSPARSE_CSRMV_ALG1`! I'm starting to think that maybe the summit cusparse build is defective. I grepped the whole of the cuda directory for `CUSPARSE_SPMV_CSR_ALG1` and it came up completely empty.

**Comment by YohannDudouit** [comment]
I was thinking that replacing `#if CUDA_VERSION >= 11020` with something like `#if CUSPARSE_VER_MAJOR >= 11 && CUSPARSE_VER_MINOR >= 4` could be the answer, but I'm not sure...

**Comment by tzanio** [comment]
Hey guys, do we have a clear resolution for this? Is it something that should be in mfem-4.3?

**Comment by YohannDudouit** [comment]
Not completely, the cusparse documentation suggests that 11.2.1 (see https://github.com/mfem/mfem/issues/2164#issuecomment-826440946) should be the right cusparse version, but https://github.com/mfem/mfem/issues/2336#issuecomment-863297380 suggests that 11.4 is the right version in the case of Summit...

**Comment by YohannDudouit** [comment]
I might be confusing the cuda version and the cusparse version though.
I think we could try replacing `#if CUDA_VERSION >= 11020` with `#if CUSPARSE_VER_MAJOR >= 11 && CUSPARSE_VER_MINOR >= 4`, this will work for Lassen and Summit, but I don't find any documentation on the cusparse versions to be sure it's the right condition.

**Comment by v-dobrev** [comment]
I'd say use the condition `CUSPARSE_VERSION >= 11400` where `CUSPARSE_VERSION` is defined in `cusparse.h` as
```c++
#define CUSPARSE_VERSION (CUSPARSE_VER_MAJOR * 1000 + \
                          CUSPARSE_VER_MINOR *  100 + \
                          CUSPARSE_VER_PATCH)
```
Judging by the posts above, this should work on both Lassen and Summit with their respective installs of CUDA 11.2.0.

If this is not the exact cutoff version, we can adjust again later, if this comes up again.

**Comment by tzanio** [comment]
@Jacobfaib do you want to propose a PR with the above suggested change?

**Comment by Jacobfaib** [comment]
> @Jacobfaib do you want to propose a PR with the above suggested change?

Yeah sure, I'll check that the cusparse version check works on the machines I've got access to.

**Comment by stefanozampini** [comment]
What is the status of this issue? Just met the same error on a local machine, with cuda11.2 and this configuration for cusparse

```
#define CUSPARSE_VER_MAJOR 11
#define CUSPARSE_VER_MINOR 3
#define CUSPARSE_VER_PATCH 1
#define CUSPARSE_VER_BUILD 68
#define CUSPARSE_VERSION (CUSPARSE_VER_MAJOR * 1000 + \
                          CUSPARSE_VER_MINOR *  100 + \
                          CUSPARSE_VER_PATCH)
```

**Comment by tzanio** [comment]
ping: @Jacobfaib, @YohannDudouit

**Comment by Jacobfaib** [comment]
I'll open a PR tomorrow morning (for real this time!).

**Comment by tzanio** [comment]
Discussion continued in #2445.
