### ISSUE TITLE
parallel/per-domain NURBS file support?

### ISSUE THREAD

**Issue by xjrc** [mfem/mfem#2337]
Is it possible to output an MFEM NURBS mesh (like the [ball-nurbs.mesh](https://github.com/mfem/mfem/blob/master/data/ball-nurbs.mesh) example) that spans multiple files (e.g. one domain per file)? Support for such a capability would be ideal for a parallel application outputting meshes in this format. Thanks in advance for your input and guidance!

**Comment by v-dobrev** [comment]
Unfortunately, the answer at the moment is no.

**Comment by xjrc** [comment]
Thanks, @v-dobrev. We can get around this for the time being by funneling all of the data back to rank 0 and publishing the mesh to a single file, but it would be great to remove this reduction step when a parallel format is available in the future!
