### ISSUE TITLE
Create ParGridFunction from GridFunction

### ISSUE THREAD

**Issue by e-aranda** [mfem/mfem#2340]
Sorry if this question is already answered, but I have not found it. This is the situation: 
I have a mesh previously built, `intmesh` and the parallel mesh and spaces:
```
   FiniteElementCollection *fec;
   fec = new H1_FECollection(1, 2);
   // Global space
   FiniteElementSpace *interior = new FiniteElementSpace(&intmesh,fec);
   // Parallel
   ParMesh *pmesh = new ParMesh(MPI_COMM_WORLD, intmesh);
   ParFiniteElementSpace *fespace = new ParFiniteElementSpace(pmesh, fec);
```
and now, I define a GridFunction in `interior` space, and I want the corresponding `ParGridFunction` in `fespace`
```
   GridFunction *rhoint;
   rhoint = new GridFunction(interior);
   ... // definition of rhoint
   
   ParGridFunction *Rhobar;
   Rhobar = new ParGridFunction(fespace,rhoint);
```
and running with 1 process, the `ParGridFunction` is correctly set, but running with more than 1 process gives a wrong `ParGridFunction`

What am I doing wrong?

**Comment by tzanio** [comment]
Wasn't this discussed in https://github.com/mfem/mfem/issues/1155?

**Comment by e-aranda** [comment]
That was the inverse situation: get a GridFunction from a ParGridFunction. Indeed, what I am trying is what @v-dobrev commented  at https://github.com/mfem/mfem/issues/1155#issuecomment-554138100. However in this way:
```
    ParGridFunction *Rhobar; 
    Rhobar = new ParGridFunction(pmesh,rhoint);
``` 
it does not work, even with only 1 process. It seems data is not copied. And doing as:
```  
   ParGridFunction *Rhobar;
   Rhobar = new ParGridFunction(fespace,rhoint);
```
works with 1 processor but no with more than one, because data is messy.

**Comment by v-dobrev** [comment]
The documentation here: https://github.com/mfem/mfem/blob/8923656d477be5f42271af92e5c4eb5008c947f0/fem/pgridfunc.hpp#L78-L82

states that you need to provide the 3rd argument in order to be able to transfer the data.

**Comment by e-aranda** [comment]
Ok, thanks. That was my mistake.
