### ISSUE TITLE
Laplace(u) + Au + **lambda**.Grad(u) = 0 , from example 7.

### ISSUE THREAD

**Issue by LeilaSalomon** [mfem/mfem#2342]
Hello everybody,

I would like to solve the following equation :

Laplace(u) + Au + **lambda**.**Grad**(u) = 0     ,    with u the solution to be determined, A a GridFunctionCoefficient and **lambda** a VectorGridFunctionCoefficient.

I was planning to start from example 7, so the idea is to add the term **lambda**.**Grad**(u), and take f = 0.

Is it possible to do this by adding to the bilinear form:

a->AddDomainIntegrator(new ConvectionIntegrator(lambda))??

Or is it much more complicated than that?

Best,

Leïla

**Comment by jandrej** [comment]
Your approach of using the `ConvectionIntegrator` form should work as long as `lambda` is divergence free, e.g. `\nabla \cdot \lambda = 0`.

Keep in mind that example 7 uses a continuous Galerkin finite element space. Therefore, without going into to much detail, you have to be careful how large the `lambda` coefficient makes the convection term compared to the diffusion.

**Comment by v-dobrev** [comment]
Do you want to solve the equation on a surface, as in Example 7?

If that is the case, it will be a good idea to double-check if the other integrators (besides `DiffusionIntegrator`) work properly with surface meshes.

**Comment by LeilaSalomon** [comment]
> Your approach of using the `ConvectionIntegrator` form should work as long as `lambda` is divergence free, e.g. `\nabla \cdot \lambda = 0`.
> 
> Keep in mind that example 7 uses a continuous Galerkin finite element space. Therefore, without going into to much detail, you have to be careful how large the `lambda` coefficient makes the convection term compared to the diffusion.

Hello, `lambda` is not divergence free...
Which integrator you would have used to add the term `lambda.Grad(u)` ?

**Comment by jandrej** [comment]
In my previous comment I made the assumption that you stated the strong form and still need to derive the weak form of your equation e.g., multiply by a test function and integrate by parts. Therefore I also assumed you want to apply integration by parts to the convective term in order to retrieve a boundary term.

It would help if you can provide more details about the weak form and its derivation that you try to discretize. See also the other response/question regarding your problem. If you want to solve the equation on a surface mesh, this is not trivial and most likely only implemented for the integrators used in example 7.

**Comment by LeilaSalomon** [comment]
> In my previous comment I made the assumption that you stated the strong form and still need to derive the weak form of your equation e.g., multiply by a test function and integrate by parts. Therefore I also assumed you want to apply integration by parts to the convective term in order to retrieve a boundary term.
> 
> It would help if you can provide more details about the weak form and its derivation that you try to discretize. See also the other response/question regarding your problem.
> 
> If you want to solve the equation on a surface mesh, this is not trivial and most likely only implemented for the integrators used in example 7.

Hello, 

I attach you a presentation of my problem so that it will be more clear :) 

<img width="472" alt="problem_presentation" src="https://user-images.githubusercontent.com/40572513/123127682-cacc7f00-d44a-11eb-8a54-fb3c53094993.PNG">

**Comment by jandrej** [comment]
Based on your description, yes, it looks like you can use `ConvectionIntegrator`.

**Comment by LeilaSalomon** [comment]
> Based on your description, yes, it looks like you can use `ConvectionIntegrator`.

Hey, thank you,

Example 7 solves  `delta(u) + u = f`. Here, I have `delta(u) + Au + lambda.nabla(u)= 0`. A first idea would be to modifie the constant coefficient in `DiffusionIntegrator` :

BilinearForm *a = new BilinearForm(fespace);
ConstantCoefficient CC1(-1.0);
a->AddDomainIntegrator(new DiffusionIntegrator(CC1));

A second idea is to keep : 

BilinearForm *a = new BilinearForm(fespace);
ConstantCoefficient one(1.0);
a->AddDomainIntegrator(new DiffusionIntegrator(one));

and change the sign of A and lambda.

These two ways don't seem to work, I have an error : "PCG: The preconditioner is not positive definite."

**Comment by tzanio** [comment]
Are you sure about the sign of `A`?

If the continuous level operator is indeed `\Delta u + Au ...` where `A` is positive, then the problem is indefinite (specifically indefinite Helmholtz).

This is much more challenging than the definite case and requires special solvers. cc: @psocratis

**Comment by LeilaSalomon** [comment]
> Are you sure about the sign of `A`?
> 
> If the continuous level operator is indeed `\Delta u + Au ...` where `A` is positive, then the problem is indefinite (specifically indefinite Helmholtz).
> 
> This is much more challenging than the definite case and requires special solvers. cc: @psocratis

Hello,

I will check my equation again, to see if there is an error. Normally, the equation is written in the following strong form: `delta(u) + Au + lambda.nabla(u)= 0`.

I don't understand why the sign of A is problematic. If I start from this strong form, can't I use the solver from example 7?

**Comment by psocratis** [comment]
@LeilaSalomon , 

As @tzanio mentioned, if your A is positive definite your linear system would be indefinite `-(grad u, grad v) + (Au,v) ...` and solvers based on CG preconditioned with AMG would not work. Example 7 solves `-\Delta u + u = f`, which after integration by parts it gives a symmetric positive definite system `(grad u, grad v) + (u, v) = (f,v)` . If indeed you have an idefinite system, I would recommend a direct solver (UMFPack in serial, SuperLU/MUMPS/PARDISO in parallel).

Thanks,

Socratis

**Comment by LeilaSalomon** [comment]
> @LeilaSalomon ,
> 
> As @tzanio mentioned, if your A is positive definite your linear system would be indefinite `-(grad u, grad v) + (Au,v) ...` and solvers based on CG preconditioned with AMG would not work. Example 7 solves `-\Delta u + u = f`, which after integration by parts it gives a symmetric positive definite system `(grad u, grad v) + (u, v) = (f,v)` . If indeed you have an idefinite system, I would recommend a direct solver (UMFPack in serial, SuperLU/MUMPS/PARDISO in parallel).
> 
> Thanks,
> 
> Socratis

Hello,

I'm trying to use the UMFPack solver. I installed the SuiteSparse library, then, I recompile the mfem library with MFEM_USE_SUITESPARSE = YES. 
So far it seems to work. But as soon as I run my code I have the following error: 
error: umfpack.h : no such file or folder #include <umfpack.h>

Do you know where it can come from? I can't find the answer in the INSTALL file.

**Comment by psocratis** [comment]
@LeilaSalomon ,

Can you make sure that the SuiteSparse include directory indeed contains that header file, and it's the same directory that is given to MFEM user.mk file? 

Thanks,

Socratis

**Comment by LeilaSalomon** [comment]
> @LeilaSalomon ,
> 
> Can you make sure that the SuiteSparse include directory indeed contains that header file, and it's the same directory that is given to MFEM user.mk file?
> 
> Thanks,
> 
> Socratis

Hello Socratis,

I don't have the user.mk file.

SuiteSparse library contains several sub-libraries, no? If I understood correctly, I just need the umfpack library? So I just have to give the path of umfpack  in my CMakeList.txt?

**Comment by psocratis** [comment]
@LeilaSalomon , 

What built system are you using? `make` or `cmake`? If you are using `make` we recommend copying the file `./config/defaults.mk` to `./config/user.mk` and inside the new file modify the path of SuiteSparse. Likewise if you are using cmake you can do the same with the file `./config/defaults.cmake`. 

I hope this helps,

Socratis

**Comment by LeilaSalomon** [comment]
> @LeilaSalomon ,
> 
> What built system are you using? `make` or `cmake`? If you are using `make` we recommend copying the file `./config/defaults.mk` to `./config/user.mk` and inside the new file modify the path of SuiteSparse. Likewise if you are using cmake you can do the same with the file `./config/defaults.cmake`.
> 
> I hope this helps,
> 
> Socratis

Hello,

There is a problem, I don't have the file `user.mk`.

**Comment by psocratis** [comment]
@LeilaSalomon , if you don't have it you must create one by copying the file './config/defaults.mk'. 
to a new file with the name 'user.mk' and place it in './config/'. Then edit the path of SuiteSparse library in that file. 

Socratis

**Comment by LeilaSalomon** [comment]
It doesn't seem to be working. I'm not sure where to put the path in the file, I may not have edited it correctly.

But, the error maybe comes upstream, when I install the libraries.
I cannot find any indication in the INSTALL file to build SuitesParse. While browsing the file, I helped myself by the installation of GSLIB library, which is detailed, so I proceeded in this way to install SuiteSpare:

```
GSLIB (optional), used when MFEM_USE_GSLIB = YES. The gslib library must be
built prior to the MFEM build, as follows: download gslib-1.0.7, untar it at
the same level as MFEM and create a symbolic link: "ln -s gslib-1.0.7 gslib".
Build gslib in parallel or in serial based on the desired MFEM build: "make
clean; make CC=mpicc" or "make clean; make CC=gcc MPI=0". Build MFEM with
MFEM_USE_GSLIB=YES.
URL: https://github.com/gslib/gslib/archive/v1.0.7.tar.gz
Options: GSLIB_OPT, GSLIB_LIB.
Versions: GSLIB >= 1.0.7.
```

I use the the SuiteSpare-4.5.3- version.

Further down you will find my CMakeLists.txt file :

![CMakeLists](https://user-images.githubusercontent.com/40572513/125265461-2761e200-e305-11eb-8d2d-a2e68a723bfe.png)

Do you think there is a mistake in my way of doing things?

**Comment by psocratis** [comment]
@LeilaSalomon, after compiling MFEM with `MFEM_USE_SUITESPARSE = YES`, can you confirm that you can run successfully  MFEM's example 1 in examples/ex1.cpp? Did you modify MFEM's user.mk or user.cmake file (in ./config) so that MFEM knows the path to the SUITESPARSE library? 

Socratis

**Comment by LeilaSalomon** [comment]
But, before I'm building MFEM with `MFEM_USE_SUITESPARSE=YES`, I have to build SuiteSparse no?

If I understood correctly, I have to create a copy of defaults.mk or defaults.cmake in `./config`, that I rename user.ck or user.cmake? (In these new files, I indicate the path to the SuiteSParse library). How do I know which one to use? To run my code, I use the two commands cmake and make.

**Comment by psocratis** [comment]
> But, before I'm building MFEM with `MFEM_USE_SUITESPARSE=YES`, I have to build SuiteSparse no?
> 
> If I understood correctly, I have to create a copy of defaults.mk or defaults.cmake in `./config`, that I rename user.ck or user.cmake? (In these new files, I indicate the path to the SuiteSParse library). How do I know which one to use? To run my code, I use the two commands cmake and make.

@LeilaSalomon, yes you have to build SuiteSparse before building mfem. Inside SuiteSparse top directory, (or wherever else you build SuiteSparse) you will see the directories `./include` and `./lib`. After installing SuiteSparse, check inside these 2 directories and confirm that the header and the *.a (or *.so) files are in there. After that, you can move on to build mfem, following the above. In order to build MFEM you can either use make or cmake (your choice).  
After mfem is built can you try compiling and running ex1.cpp and report back what you get? 

Thanks, 

Socratis

**Comment by LeilaSalomon** [comment]
Ok, I can run the ex1.cpp now, thanks!

Now, when I go back to my directory to run my own codes, there is an error again. I think I'm not editing my CMakeLists.txt file correctly... I'm attaching my file here. How can I declare the links of my last lines correctly?

![Sreen](https://user-images.githubusercontent.com/40572513/125764318-0ed060e6-3ca4-40ef-863f-ddd75a946fb0.png)

**Comment by psocratis** [comment]
Hi @LeilaSalomon, It's hard just by looking at this to pin down the issue. Can you try putting your example in `mfem/examples` and try running from within this directory. Basically, the same way you run any other mfem example. 

Thanks, 

Socratis
