### ISSUE TITLE
AdamsMoulton increase t+=dt twice

### ISSUE THREAD

**Issue by bensworth** [mfem/mfem#2343]
I'm looking at the `AdamsMoultonSolver::Step` function, and it has this fragment:
```
   if (s >= smax-1)
   {
      f->SetTime(t);
      for (int i = 1; i < smax; i++)
      {
         x.Add(a[i]*dt, k[idx[i]]);
      }
      f->ImplicitSolve(a[0]*dt, x, k[idx[0]]);
      x.Add(a[0]*dt, k[idx[0]]);
   }
   else
   {
      RKsolver->Step(x,t,dt);
      f->Mult(x,k[idx[0]]);
   }
   t += dt;
```
The first if section is most time steps, and the else to initialize solutions for the multistep method with appropriate HO accuracy. But by calling `RKsolver->Step(x,t,dt)`, this should already increase `t+=dt`, and then after the if-statement, this is called again. As far as I understand, this is increasing dt twice for the initialization time steps, and `t += dt;` shoudl be moved inside of the if statement.

**Comment by v-dobrev** [comment]
It does look like a bug. @IdoAkkerman, any thoughts?

On the other hand, the unit tests (https://github.com/mfem/mfem/blob/master/tests/unit/linalg/test_ode.cpp) seem to work fine.

**Comment by bensworth** [comment]
One other comment: I believe these multistep methods assume a fixed dt over multiple time steps. So something like the common MFEM syntax inside a time-stepping loop
```
      double dt_real = min(dt, tf - t);
      ode->Step(u, t, dt_real);
```
would break this if dt doesn't perfectly divide tf (i.e., if you change dt), and you could lose accuracy on your final step.

**Comment by tzanio** [comment]
ping: @IdoAkkerman

**Comment by bensworth** [comment]
One other thing I noticed which I am confused about here is the use of implicit solve. Take trapezoid rule, 
`y_{n+1} = y_n + 0.5*dt*( f(y_n,t_n) + f(y_{n+1},t_{n+1}) )`    (1)
Here, the implicit solve takes the form
`y_{n+1} - 0.5*dt*f( y_{n+1}, t_{n+1} ) = b`      (2)
But the `TimeDependentOperator` `ImplicitSolve` function solves `k = f(x + dt*k, t)`. So in AdamsMoulton, when we call
`f->ImplicitSolve(a[0]*dt, x, k[idx[0]]);`
we are solving 
`k = f(x + a[0]*dt*k)`    (3)
where we have defined x as a sum over previous k, and then finish with the additive update `x += a[0]*dt*k`. 

Is this a different way to write Adams Moulton methods than (1)? It's not clear to me how (3) and (2) are equivalent for a general nonlinear function. But, if there is a way to write multistep methods like this, it may be beneficial for a BDF implementation using the same functions as RK (https://github.com/mfem/mfem/pull/2474).

**Comment by tzanio** [comment]
ping: @IdoAkkerman

**Comment by IdoAkkerman** [comment]
Sorry.. I still have to learn how to use github and the notification system.

**Comment by IdoAkkerman** [comment]
@bensworth I think you are right on the first 2 issues, 3 issue I do not know.
1) There is likely a doubling up of dt initially, I 'll check.
2) I am not  and AM/AB specialist, so my understanding is the integrator works for constant time steps. Perhaps  a check needs to be added.
3) I need to check you question regarding nonlinear functions. I do remember the time stepper is a bit odd as you solve for the rate, not the solution. This has to do with a uniform handling of implicit/explicit integrator, but makes everything slightly different then usual.

**Comment by IdoAkkerman** [comment]
I think the idea is as follows.

 Take trapezoid rule,
`y_{n+1} = y_n + 0.5*dt*( f(y_n,t_n) + f(y_{n+1},t_{n+1}) )` (1)
Define
`k[0] = f(y_{n+1},t_{n+1})` (2a)
`k[1] = f(y_{n},t_{n})` (2b)
This translates (1) directly into
`y_{n+1} = y_n  + 0.5*dt*k[1] + 0.5*dt*k[0]` (3)

In the loop
```
 for (int i = 1; i < smax; i++)
{
      x.Add(a[i]*dt, k[idx[i]]);
}
```
we compute
`x = y_n  + 0.5*dt*k[1] ` (4)

Using this `x` eq (3) can be written as
`y_{n+1} = x + 0.5*dt*k[0]` (5)
Using this in eq (2a) can be written as
`k[0] = f(x + 0.5*dt*k[0],t_{n+1})` (6)
Which is what is solve in
`f->ImplicitSolve(a[0]*dt, x, k[idx[0]]);`


I hope that explains it? And does not have any errors...
I think it is just a reshuffling of terms, it does not rely on the function being linear.

**Comment by IdoAkkerman** [comment]
In short: we do not solve for `y_{n+1}`. Instead we solve for `k[0]`, which requires some rewriting.
This rewriting does **not** invoke linearity of the underlying problem.

**Comment by bensworth** [comment]
Great, that makes sense, I just hadn't seen the multistep methods written in that way. Will move discussion to the PR https://github.com/mfem/mfem/pull/3466.

**Comment by tzanio** [comment]
Thanks @IdoAkkerman
