### ISSUE TITLE
How to add another mesh into MFEM

### ISSUE THREAD

**Issue by nghiakvnvsd** [mfem/mfem#2347]
Hi everybody! I tried to add another mesh to MFEM but it returns an error. Maybe I do not know how to create the mesh following MFEM type or something?  My mesh like:

![image](https://user-images.githubusercontent.com/68639058/123040173-4a982080-d42e-11eb-98cd-aa8e689a2c9e.png)

and this is my mesh file: 
https://drive.google.com/file/d/1mAh-89-pY6aE9o-2LV2wXPvM7j18DIUv/view?usp=sharing

thank you very much!

**Comment by pazner** [comment]
It looks like our mesh uses VTK format version 5.1, which MFEM does not support. Trying to load your mesh, I see that it fails with the error
```
Verification failed: (major_vtk_version >= 2 && major_vtk_version <= 4) is false:
 --> Unsupported VTK format
 ... in function: void mfem::Mesh::Loader(std::istream &, int, std::string)
 ... in file: mesh/mesh.cpp:3617
```
You could try converting your mesh to another format supported by MFEM (e.g. ASCII VTK version 4, or XML VTK).

**Comment by nghiakvnvsd** [comment]
> It looks like your mesh uses VTK format version 5.1, which MFEM does not support. Trying to load your mesh, I see that it fails with the error
> 
> ```
> Verification failed: (major_vtk_version >= 2 && major_vtk_version <= 4) is false:
>  --> Unsupported VTK format
>  ... in function: void mfem::Mesh::Loader(std::istream &, int, std::string)
>  ... in file: mesh/mesh.cpp:3617
> ```
> 
> You could try converting your mesh to another format supported by MFEM (e.g. ASCII VTK version 4, or XML VTK).

Thanks for your support. May you give me some tool to convert? Thank you very much!

**Comment by pazner** [comment]
> Thanks for your support. May you give me some tool to convert? Thank you very much!

You can open your file in ParaView, and then select "Save Data", choose format "VTK UnstructuredGrid Files(*.vtu)" and save the file e.g. as "bracket.vtu". Set "Compressor Type" to be "None (fastest write)". This procedure worked for me and I was able to use your mesh in MFEM.

![bracket](https://user-images.githubusercontent.com/11493037/124154746-9fe5ba80-da4a-11eb-80b2-5c6981ffb655.png)

**Comment by nghiakvnvsd** [comment]
> > Thanks for your support. May you give me some tool to convert? Thank you very much!
> 
> You can open your file in ParaView, and then select "Save Data", choose format "VTK UnstructuredGrid Files(*.vtu)" and save the file e.g. as "bracket.vtu". Set "Compressor Type" to be "None (fastest write)". This procedure worked for me and I was able to use your mesh in MFEM.
> 
> ![bracket](https://user-images.githubusercontent.com/11493037/124154746-9fe5ba80-da4a-11eb-80b2-5c6981ffb655.png)

Hi @pazner . I have changed like you said but GLVIS returns:

```
MFEM abort: Unknown input mesh format: <VTKFile type="UnstructuredGrid" version="1.0" byte_order="LittleEndian" header_type="UInt64">
 ... in function: void mfem::Mesh::Loader(std::istream&, int, std::__cxx11::string)
 ... in file: mesh/mesh.cpp:3277
```
May you help me? Thank you very much!

**Comment by pazner** [comment]
Can you try pulling the latest master of MFEM and GLVis and recompiling them both?

**Comment by tzanio** [comment]
There has not been activity on this issue for a while now, and this should work with `mfem-4.3`, so I'm closing it.

Please feel free to reopen if you still have outstanding questions.
