### ISSUE TITLE
CUDA library linking for HYPRE+CUDA

### ISSUE THREAD

**Issue by wcdawn** [mfem/mfem#2349]
When using HYPRE+CUDA, the default options use `cusparse` and `curand`. The user also has the option to enable `cublas`.

Interestingly, even if HYPRE is compiled with `--disable-curand`, there is still a dependency on `curand`. This may be a bug with their build system but it still doesn't work with MFEM.

The real problem that I encountered was when trying to compile the examples. By default, MFEM links with `cusparse` but when using HYPRE+CUDA, the examples need to (at a minimum) link with `curand` and maybe also `cublas`.

I use the GNU Make build system so I am able to work around this for now with
```sh
CUDA_LIB='-lcusparse -lcurand -lcublas'
```

It would be nice if the default build system linked with `curand`. Maybe also `cublas`.

**Comment by v-dobrev** [comment]
Support for hypre build with cuda is not available yet in MFEM's `master` branch. It is being developed and tested in PR #1492 which will be part of MFEM v4.3.

**Comment by tzanio** [comment]
@wcdawn you are welcome to help us test and provide feedback in #1492.

**Comment by tzanio** [comment]
Discussion continued in #1492.
