### ISSUE TITLE
Error when using HYPRE+CUDA

### ISSUE THREAD

**Issue by wcdawn** [mfem/mfem#2350]
I encounter the following error running `ex1p` with HYPRE built with CUDA.
```
CUDA ERROR (code = 1, invalid argument) at memory.c:557
```
Interestingly,  I get the same error whether I run with the `-d cuda` command line option or not so HYPRE is calling CUDA routines regardless of the MFEM device setting.

Here is my HYPRE configuration:
```
CUDA_HOME=/opt/cuda \
  HYPRE_CUDA_SM=60 \
  CC=/opt/mpich/bin/mpicc \
  CXX=/opt/mpich/bin/mpicxx \
  ./configure \
  --disable-fortran \
  --with-cuda \
  --enable-unified-memory \
  --enable-device-memory-pool \
  --enable-cusparse \
  --enable-cublas \
  --enable-curand
```

Here is my MFEM configuration:
```
make config \
  MFEM_USE_MPI=YES CXX=/opt/mpich/bin/mpicxx MPICXX=/opt/mpich/bin/mpicxx \
  HYPRE_DIR=@MFEM_DIR@/../hypre/src/hypre \
  MFEM_USE_METIS_5=YES METIS_DIR=@MFEM_DIR@/../metis \
  MFEM_USE_CUDA=YES CUDA_LIB='-lcusparse -lcurand -lcublas'
```

**Comment by wcdawn** [comment]
It looks like this may not be supported yet. I thought this had been merged in already.
I'll give it a try with branch `hypre-cuda-dev`. Looks like #1492 needs to be merged to enable this.

**Comment by v-dobrev** [comment]
Yes, support for hypre build with cuda is under development in PR #1492.

**Comment by tzanio** [comment]
Discussion continued in #1492.
