### ISSUE TITLE
GLVis X connection failure

### ISSUE THREAD

**Issue by brightzhang91** [mfem/mfem#2362]
Hi :)
I just reinstalled my Ubuntu (due to corruption) and therefore the GLVis and its dependencies. However I cannot display the meshes through Xming, with the following problem:  
![image](https://user-images.githubusercontent.com/67397441/123558941-13f53980-d791-11eb-9ade-c760f0f3b445.png)
However the xclock test works , which indicates  X forwarding and SSH connection should be alright ?
![image](https://user-images.githubusercontent.com/67397441/123559040-a4cc1500-d791-11eb-89cc-9d3f1505d9ae.png)
 GLVis works well for me until this recent reinstallation. I have been trying the recommended solutions regarding the "X connection to :0 broken" problem. But none of them works. Any ideas for the fix?

Thanks !
Bright

**Comment by tzanio** [comment]
Hi @brightzhang91,

Can you confirm you are using `mfem-4.2` with `glvis-4.0`, and no other modifications?

Also, what is the operating system?

Tzanio

**Comment by brightzhang91** [comment]
> Hi @brightzhang91,
> 
> Can you confirm you are using `mfem-4.2` with `glvis-4.0`, and no other modifications?
> 
> Also, what is the operating system?
> 
> Tzanio

Hi Tzanio
Yes I'm using `mfem-4.2` with ` glvis-4.0`, which were downloaded and installed in this week without modification. The operating system is Linux based Ubuntu 20.04.LTS installed on windows.

**Comment by kanye-quest** [comment]
Hi @brightzhang91,

Could you perform the following steps and post the output?
- Build and run glvis in debug mode, with `make GLVIS_DEBUG=YES` - this should provide some additional error information during window initialization.
- Run `glxinfo` to confirm that OpenGL is working through X

Another thing you might be able to try out is using [VcXsrv](https://sourceforge.net/projects/vcxsrv/) instead of Xming for the X server. VcXsrv should support a newer version of OpenGL, and seems to be more actively developed compared to Xming.

**Comment by brightzhang91** [comment]
Hi @kanye-quest 

Thanks for the advices. So far I have tried :

> Build and run glvis in debug mode, with make GLVIS_DEBUG=YES - this should provide some additional error information during window initialization.
> Run glxinfo to confirm that OpenGL is working through X
![image](https://user-images.githubusercontent.com/67397441/123674044-11e6b580-d839-11eb-91d5-0101de5b1dd4.png)
It seems there is problem with OpenGL:
![image](https://user-images.githubusercontent.com/67397441/123675274-70f8fa00-d83a-11eb-85e9-b4cbf85ca154.png)

 However I tested the display with OpenGL, following the advice here [:](http://www.codebind.com/linux-tutorials/install-opengl-ubuntu-linux/)
![image](https://user-images.githubusercontent.com/67397441/123675426-9a198a80-d83a-11eb-8feb-1399d1885793.png)

**Comment by kanye-quest** [comment]
What happens when you run `DISPLAY=:0 glxinfo`? If `glxinfo` isn't running, that's definitely concerning.

Also, is there anything that looks off inside Xming's logs wrt the broken X connection?

**Comment by brightzhang91** [comment]
Ok  :), `DISPLAY=:0 glxinfo` can show all the information, such as some parts as follows:
![image](https://user-images.githubusercontent.com/67397441/123709602-41131c00-d865-11eb-8e6f-52adfe417d81.png)
![image](https://user-images.githubusercontent.com/67397441/123709699-66a02580-d865-11eb-8383-c33dcfa0aa26.png)

Xming doesn't look like strange and xclock test works.

**Comment by jamiebramwell** [comment]
I was able to compile and run glvis v4.0 successfully on my WSL2/Ubuntu 20.04 machine. However, I am using [VcXsrv](https://sourceforge.net/projects/vcxsrv/) as recommended by @kanye-quest . I am not an X or GL power user, but I am happy to help debug this if you would like me to query my build or system parameters.

**Comment by tzanio** [comment]
thanks for helping @jamiebramwell !

**Comment by brightzhang91** [comment]
> I was able to compile and run glvis v4.0 successfully on my WSL2/Ubuntu 20.04 machine. However, I am using [VcXsrv](https://sourceforge.net/projects/vcxsrv/) as recommended by @kanye-quest . I am not an X or GL power user, but I am happy to help debug this if you would like me to query my build or system parameters.

Thanks. I'll try to use VcXsrv instead of Xming and see if it works. I'll be back when it works or still have problems.

Bright

**Comment by brightzhang91** [comment]
Hi 
The display with VcXsrv  is successful :)
Thanks very much for the support and I'm closing this issue. 

Best
Bright
