### ISSUE TITLE
Bug in AssembleSharedFaces for ParLinearForm

### ISSUE THREAD

**Issue by robert-chiodi** [mfem/mfem#2363]
Hi all,

I believe there is a bug in the line below of `plinearform.cpp`. The index should be incrementing as `iflfi` is iterated over (index `k` instead `0`). 
https://github.com/mfem/mfem/blob/c1485a49edfd48b089fd5139611b7100704dbf6d/fem/plinearform.cpp#L76

On a related note, I believe a getter method for the new `InteriorFace` LinearFormIntegrators in the `LinearForm` is missing, meaning that
```
   /// Access all integrators added with AddInteriorFaceIntegrator().
   Array<LinearFormIntegrator*> *GetIFLFI() { return &iflfi; }
```
should be added to `linearform.hpp`.

I would lastly like to float the idea that the variable name for interior face integrators in `LinearForm` be changed to `flfi` to match the prefix (`f`) used in `BilinearForm`. I do not believe it will break the public API (since the getter method is currently missing) but it will affect code-bases that inherited `LinearForm` and are directly using the interior face integrators. Perhaps if warranted, this last point could be included during a major release if deemed worth changing at all.

**Comment by kmittal2** [comment]
Glad you caught this @robert-chiodi, thanks!

I agree that `flfi` fits better but right now `flfi` is used for `BdrFaceIntegrators` in `LinearForm`. We could change to `bflfi` for  `BdrFaceIntegrators` and `flfi` for `InteriorFaceIntegrators` to match `BilinearForm` but this will lead to some backwards incompatibilities. What do you think @tzanio @v-dobrev?

Ketan

**Comment by v-dobrev** [comment]
> I agree that `flfi` fits better but right now `flfi` is used for `BdrFaceIntegrators` in `LinearForm`. We could change to `bflfi` for `BdrFaceIntegrators` and `flfi` for `InteriorFaceIntegrators` to match `BilinearForm` but this will lead to some backwards incompatibilities. What do you think @tzanio @v-dobrev?

These are protected data members, so I'm okay to change the names.

**Comment by pazner** [comment]
May I be so bold as to suggest a name such as `interior_face_integrators` or `interior_face_integs`?

**Comment by v-dobrev** [comment]
> May I be so bold as to suggest a name such as `interior_face_integrators` or `interior_face_integs`?

No objections from me. My IDE will auto-complete these for me, so I don't need to worry about the extra typing. 😄

**Comment by tzanio** [comment]
Discussion continued in  #2375.
