### ISSUE TITLE
Convection-diffusion equation solved using DG 

### ISSUE THREAD

**Issue by sashank-srinivasan-13** [mfem/mfem#2364]
Hello All,
I am a beginner in using mfem and am trying to use mfem to solve a convection-diffusion equation as a precursor to my actual project. I had focussed on combining ex9.cpp, with the diffusion operators used in example 14 (taking care to not include the source term on the RHS, and use periodic boundary conditions for both the convection and diffusion terms). This approach seems to be incorrect and was hoping to get some advice on how to go about it.

Thanks!

**Comment by pazner** [comment]
Hi @sashank-srinivasan-13,

The approach you describe (combining the integrators from ex9 and ex14) is the correct one. Adding the following integrators to example 9 should work (with periodic boundary conditions):
```c++
   double diffusion_coefficient = 1e-2;
   ConstantCoefficient minus_diff_coeff(-diffusion_coefficient);
   double sigma = -1.0, kappa = 10*(order+1)*(order+1);
   k.AddDomainIntegrator(new DiffusionIntegrator(minus_diff_coeff));
   k.AddInteriorFaceIntegrator(new DGDiffusionIntegrator(minus_diff_coeff, sigma, kappa));
```
Note that the diffusion term may result in a restrictive CFL condition, so you might want to try running with implicit time stepping (e.g. flag `-s 23` or similar).

**Comment by helloworldooo** [comment]
Hello, I am trying to solve such a conservative problem with a flux boundary condition. It's not easy for me to choose integrators. Could you give me some advices?
∂u/∂t+∇∙(vu-a∇u)=f in Ω
n ∙(vu-a∇u) = b  on Γ


> Hi @sashank-srinivasan-13,
