### ISSUE TITLE
Questions on Shared Faces and Face Neighbors

### ISSUE THREAD

**Issue by xjrc** [mfem/mfem#2371]
I have a few questions about the concepts of shared faces and face neighbors as they appear in the `mfem::ParMesh` class:

1. What exactly is a face neighbor (referred to by `mfem::ParMesh::GetNFaceNeighbors()`, `mfem::ParMesh::GetFaceNbrGroup`, etc.)? Is this just a term for a parallel group that spans one or more faces?
2. What exactly is a shared face (referred to by `mfem::ParMesh::GetNSharedFaces()` and `mfem::ParMesh::GetSharedFace(int)`)? Does this term refer to faces that lie on abutment surfaces between domains?
3. Does each shared face correspond to a local face on a particular local domain? If not, what are some cases where a domain knows about a shared face with no local corresponding local face?

To make these questions a bit more concrete, consider the following 4-domain problem:

```
Y
 
^ (0, 2)        vvsf23
|   +-----------++-----------+
|   |    face20>||<face30    |
|   |           ||           |
|   |  domain2  ||  domain3  |
|   |           ||           |
|   |vface21    ||    face31v|
| s>+-----------++-----------+<s
| f>+-----------++-----------+<f
| 0 |^face01    ||    face11^| 1
| 2 |           ||           | 3
|   |  domain0  ||  domain1  |
|   |           ||           |
|   |    face00>||<face10    |
|   +-----------++-----------+
|           sf01^^         (2, 0)
+----------------------------->  X
```

1. For `domain0`, are the face neighbors `domain1` and `domain2`?
2. For `domain0`, are the shared faces `sf01` and `sf02`?
3. In this scenario, `domain0`'s local faces have a one-to-one relationship with "shared faces" (i.e. `face00` corresponds to `sf01` and `face01` corresponds to `sf02`). When would this not be the case?

Thanks in advance for your thoughts and responses!

**Comment by pazner** [comment]
> 1. What exactly is a face neighbor (referred to by `mfem::ParMesh::GetNFaceNeighbors()`, `mfem::ParMesh::GetFaceNbrGroup`, etc.)? Is this just a term for a parallel group that spans one or more faces?

A "face neighbor" is an MPI rank corresponding to a mesh partition that shares a face with the local mesh partition.

In the example you include, each domain should have two face neighbors, since each domain borders two other domains with shared faces.

> 2. What exactly is a shared face (referred to by `mfem::ParMesh::GetNSharedFaces()` and `mfem::ParMesh::GetSharedFace(int)`)? Does this term refer to faces that lie on abutment surfaces between domains?

Yes, that is correct. A shared face is a face that lies on the boundary of elements contained in two different mesh partitions.

> 3. Does each shared face correspond to a local face on a particular local domain? If not, what are some cases where a domain knows about a shared face with no local corresponding local face?

I believe that every shared face should correspond to a local face.

> To make these questions a bit more concrete, consider the following 4-domain problem:
> 
> ```
> Y
>  
> ^ (0, 2)        vvsf23
> |   +-----------++-----------+
> |   |    face20>||<face30    |
> |   |           ||           |
> |   |  domain2  ||  domain3  |
> |   |           ||           |
> |   |vface21    ||    face31v|
> | s>+-----------++-----------+<s
> | f>+-----------++-----------+<f
> | 0 |^face01    ||    face11^| 1
> | 2 |           ||           | 3
> |   |  domain0  ||  domain1  |
> |   |           ||           |
> |   |    face00>||<face10    |
> |   +-----------++-----------+
> |           sf01^^         (2, 0)
> +----------------------------->  X
> ```
> 
>  1. For `domain0`, are the face neighbors `domain1` and `domain2`?

Yes.

> 2. For `domain0`, are the shared faces `sf01` and `sf02`?

Yes.

> 3. In this scenario, `domain0`'s local faces have a one-to-one relationship with "shared faces" (i.e. `face00` corresponds to `sf01` and `face01` corresponds to `sf02`). When would this not be the case?

In general, there will be more local faces than shared faces. In your example, `domain0` has two shared faces, and two faces that are not shared (left and bottom). That being said, every shared face should correspond to a local face. Note, however, that each domain might have a different numbering of the shared faces (e.g. `sf01` could be shared face `i` on domain 0, and shared face `j` on domain 1).

**Comment by xjrc** [comment]
Excellent explanation, @pazner; thank you! On point (3), I've been reviewing some client code that had checks for cases when a shared face had no local equivalent, which is why I asked the question. Your statements of (1) "all shared faces correspond to a local face" and (2) "not all local faces correspond to a shared face" makes much more sense to me. Thanks again!

**Comment by acfisher** [comment]
@pazner Can you find the time to turn this into an article?  If not I can get to it sooner or later as you already did most of the work.

**Comment by pazner** [comment]
> @pazner Can you find the time to turn this into an article? If not I can get to it sooner or later as you already did most of the work.

It would fit under the umbrella of #1740, which keeps getting pushed further down the to-do list…
