### ISSUE TITLE
Array error, "static assertion failed: type T must be trivial"

### ISSUE THREAD

**Issue by bensworth** [mfem/mfem#2374]
I am trying to compile MFEM on a new cluster. The library compiles and the examples compile and run, but when I try to compile my own script and link I get the following strange error. Has anybody seen this? Since the examples run I expect the problem is on my side, but I'm not sure where to look. Using modules `  1) gcc/9.4.0               2) mpich/3.4.2-gcc_9.4.0   3) cuda/11.1               4) cmake/3.17.3`.

```
In file included from /home/southworth/c_libs/mfem/mfem.hpp:19,
                 from /home/southworth/c_libs/mfem/bens_build/mfem.hpp:3,
                 from IRK_utils.hpp:5,
                 from IRK_utils.cpp:1:
/home/southworth/c_libs/mfem/general/array.hpp: In instantiation of ‘static void mfem::Array<T>::TypeAssert() [with T = mfem::Vector]’:
/home/southworth/c_libs/mfem/general/array.hpp:92:32:   required from ‘mfem::Array<T>::~Array() [with T = mfem::Vector]’
/home/southworth/c_libs/mfem/general/array.hpp:350:7:   required from here
/home/southworth/c_libs/mfem/general/array.hpp:57:41: error: static assertion failed: type T must be trivial
   57 |       static_assert(std::is_trivial<T>::value, "type T must be trivial");
      |                                         ^~~~~
```

**Comment by v-dobrev** [comment]
You are trying to create an `mfem::Array<mfem::Vector>` and that is not allowed since `mfem::Vector` is not a trivial type. You can use `std::vector<mfem::Vector>` instead or something similar.

**Comment by bensworth** [comment]
Ohh thanks Veselin. Is this compiler specific? I've been using this code for 6 months on other machines and my laptop without an issue

**Comment by YohannDudouit** [comment]
This is an old implicit requirement that has been made explicit.
