### ISSUE TITLE
Mesh size limit in serial and parallel

### ISSUE THREAD

**Issue by Maatinski** [mfem/mfem#2377]
Hi all,
I have recently been trying to increase the number of mesh elements in our simulations (see [1432](https://github.com/mfem/mfem/issues/1432)) but I very quickly run into segmentation faults. This occurs for mesh element numbers (hex meshes) somewhere between 150M and 200M. The simulations are run on a fairly powerful server (>700GB memory) so I don't think memory limits are the issue.
Initially I thought the problem was in my own mesh reader function (I read the mesh from a binary file to reduce the file size) but it also happens using the native MFEM ASCII file format. Another guess would be that this this is due to the `integer` limit, but I would've expected the limit to be greater than that.
I searched through the MFEM Github but wasn't able to find answers (apologies if I missed a thread discussing this).

A couple of specific questions:
1. What is the limit for the number of first-order hex mesh elements in serial and parallel? I realize this question may depend some more specifics but maybe someone has a rough ball-park number.
2. If the limit is mostly a per-node limit: is there a way to "pre-partition" the mesh outside of MFEM and import the already partitioned mesh?

Thanks a lot and warm regards,
Maatinski

**Comment by v-dobrev** [comment]
Can you load your mesh with `mesh-explorer`? You can try this:
```console
cd miniapps/meshing
make mesh-explorer
./mesh-explorer -m <your-mesh-file>
```
If that segfaults too, can you try building mfem in debug mode and posting a stack trace from a debugger when the code crashes?

One possibility is that either the number of faces or edges is more than 2^31 so there's an `int` overflow. On the other hand, in a hex mesh the number of edges and faces is typically ~3x the number of elements, so with 200M elements you should still be fine.
