### ISSUE TITLE
How to impose essential BC on a single node in parallel

### ISSUE THREAD

**Issue by HaoWangCase** [mfem/mfem#2380]
Hi guys,
Currently, I would like to impose an essential BC on a single node. In serial code, it is easy since I know the nodal ID, and I can add the corresponding dof id into the essential BC list by hand. However, in parallel code, I haven't found the connectivity table between the global nodal ID and local nodal ID. Would you please tell me where the connectivity table is stored, or is there another way to impose such BCs? Thanks.

**Comment by v-dobrev** [comment]
Are you using a linear continuous FE space? If so, nodal ids are the same as vertex ids, so you can use the answer here: https://github.com/mfem/mfem/issues/2277#issuecomment-849741199.

For higher order spaces, such mapping is not explicitly constructed, however it can reconstructed similar to here: https://github.com/mfem/mfem/blob/598a5994bcc91d08adc78c1ba5ab3f1694d911bf/fem/pgridfunc.cpp#L47-L68

**Comment by wanglucifer** [comment]
@v-dobrev Thanks for your reply. I see that is what I want. I just wonder that whether we can get the same partitioning once the original mesh, the number of processors and the partitioning method keep unchanged. Thanks.

**Comment by wanglucifer** [comment]
@v-dobrev Meanwhile, I see that the method you provided can only get the map from the global vertex index to the local vertex index. In the parallelization, I found that the shared vertexes can only remain as true DOFs in several partitions. If you are willing to give me some clue on how to reduce the local vertexes to the true DOFs, that would be very helpful. Thanks again for your kind reply.

**Comment by v-dobrev** [comment]
You can use `ParFiniteElementSpace::GetLocalTDofNumber` to determine which local dofs are true and their local true-dof indices.
