### ISSUE TITLE
Updating solvers in transient block-problems correctly

### ISSUE THREAD

**Issue by termi-official** [mfem/mfem#2382]
Hi again,

I want to solve a very simple linear PDAE with MFEM with time adaptivity, which I model as a block problem. However it seems like I do something wrong when updating the linear operator for my solver, as changing the time step results in divergence at some random timepoint. As a side-note, the linear PDAE results from an operator splitting of a degenerate reaction-diffusion system. After discretizing the system with an implicit Euler I obtain the following linear problem:

```
|    T     Δt*K1 |  |  V2 | = | M V1 |
|  Δt*K1   Δt*KK |  | φe2 |   |   0  |
```
where K1 and KK are discretizations of diffusion operators and T is the mass matrix and another discretization of a diffusion operator, so everything is symmetric (utilizing linear Lagrange elements).

With constant Δt I do not run into much issues solving the problem with CG or PCG (with a block diagonal preconditioner).  However if Δt is perturbated in each timestep, then neither CG or PCG converge, sometimes. For testing purposes I have a very small Δt=0.005 and my perturbation is randomly sampled from the uniform distribution [-0.001, 0.005].

Here the relevant lines of my Euler step
```cpp
if (Δt_prev != Δt)
{
    // Assemble atomar matrices
    T = std::unique_ptr<mfem::HypreParMatrix>(Add(1.0, M, Δt / (model->χ * model->Cₘ), K1_V));

    ΔtK1_V = std::unique_ptr<mfem::HypreParMatrix>(
        Add(Δt / (model->χ * model->Cₘ), K1_V, 0.0, K1_V));
    ΔtK1_φe = std::unique_ptr<mfem::HypreParMatrix>(
        Add(Δt / (model->χ * model->Cₘ), K1_φe, 0.0, K1_φe));

    KK = std::unique_ptr<mfem::HypreParMatrix>(
        Add(Δt / (model->χ * model->Cₘ), K1_φe, Δt / (model->χ * model->Cₘ), K2));

    // Set preconditioner - removed for CG run
    invP->SetOperator(*T);
    invE->SetOperator(*KK);
    LPEB_prec->SetDiagonalBlock(0, invP.get());
    LPEB_prec->SetDiagonalBlock(1, invE.get());
    LPEB_solver.SetPreconditioner(*LPEB_prec);
    // End of set preconditioner - removed for CG run

    LPEBOp->SetBlock(0, 0, T.get());
    LPEBOp->SetBlock(0, 1, ΔtK1_φe.get());
    LPEBOp->SetBlock(1, 0, ΔtK1_V.get());
    LPEBOp->SetBlock(1, 1, KK.get());
}

// Assemble RHS Block Vector
mfem::BlockVector rhs = u;
M.Mult(u.GetBlock(0), rhs.GetBlock(0));
rhs.GetBlock(1) = 0.0;

// Solve.
LPEB_solver.SetOperator(*LPEBOp);
LPEB_solver.iterative_mode = true;
LPEB_solver.Mult(rhs, u_new);
if(!LPEB_solver.GetConverged())
{
    if(fespace.GetMyRank() == 0)
    {
        std::cout << "BackwardEuler did not converge. Norm: " << LPEB_solver.GetFinalNorm() << std::endl;
    }
    MPI_Abort(MPI_COMM_WORLD, -1);
}

Δt_prev = Δt;
```

I do not understand what is going wrong. I append two runs with the iterative solver output (level 1).

[CG.log](https://github.com/mfem/mfem/files/6756176/CG.log)
[PCG.log](https://github.com/mfem/mfem/files/6756175/PCG.log)

**Comment by v-dobrev** [comment]
If the block system is symmetric, then `K1_V` and `K1_φe` must be transpose of each other. On the other hand, they are also added to the diagonal blocks, so the must be symmetric as well. Therefore, it looks like `K1_V` and `K1_φe` must be the same which does not seem right. Is this correct?

**Comment by termi-official** [comment]
Thanks for the quick response! Indeed, I applied Dirichlet BCs to `K1_φe`, while I do not apply any BCs to `K1_V`, which seems to be the culprit. Interesting that this did not crash the solver earlier. Substituting the CG with GMRES works like a charm. Thanks for the pointer, I should have noticed earlier.

My follow up question relating to the code snippet would be: Is there a more efficient way to update the matrices and BoomerAMG? All I want to do is to rescale my matrices (to conform to the new time step length) without allocating new matrices and especially without rebuilding the AMG (what happens when SetOperator is called, if I understand correctly).

**Comment by v-dobrev** [comment]
You may be okay just reusing the preconditioner built for some fixed dt, even when the actual dt is changing. Another option is to only rebuild the preconditioner when dt changes (increases or decreases) more than some factor, say 10.

**Comment by termi-official** [comment]
Good point, that should do it too. Thanks for the help!
