### ISSUE TITLE
How to use SuperLU solver with a BlockOperator

### ISSUE THREAD

**Issue by cdelv** [mfem/mfem#2384]
Hi, I Have a BlockOperator and want to pass it to the SuperLUSolver. The problem is that it only accepts Operators. 

How can I split the BlockOperator into Operators or convert it to  HypreParMatrix to pass it to the Solver?

**Comment by psocratis** [comment]
@cdelv , 
Does your `Blockoperator` contain blocks of `HypreParMatrix` ? If yes you can use 
````cpp
HypreParMatrix * HypreParMatrixFromBlocks(Array2D<HypreParMatrix*> &blocks,
                                          Array2D<double> *blockCoeff=NULL);
````

I hope this helps.

Best,
Socratis

**Comment by cdelv** [comment]
@psocratis Actually it is
```
    A = new BlockOperator(block_true_offsets);
    A->SetBlock(0, 0, M);
    A->SetBlock(0, 1, C);
    A->SetBlock(1, 0, Ct);
    A->SetBlock(1, 1, D);
```
M, C, Ct, D are HypreParMatrix.

The question is now, how do I do that array? How do I create the new matrix?

I have another question out of pure curiosity, I found a way to convert the BlockOperator into a PetscParMatrix with `PetscParMatrix::PetscParMatrix(MPI_Comm comm, const Operator *op, Operator::Type tid)`, Is there a way to convert a PetscParMatrix into a HypreParMatrix

**Comment by psocratis** [comment]
Hi @cdelv , 

You can create a `Array2D<HypreParMatrix*>` of size `(2,2)` and assign accordingly the pointers to your `HypreParMatrices`. You might want to take a look at `./tests/unit/linalg/test_matrix_rectangular.cpp` for a simple demonstration on how to use this method. 

Regarding your second question, I am not sure if such a conversion is readily available in MFEM (I don't think so). @jandrej do you know more about this? 

Thanks, 

Socratis

**Comment by cdelv** [comment]
Thanks, That's It, It worked.
