### ISSUE TITLE
Problem with SparseMatrix

### ISSUE THREAD

**Issue by e-aranda** [mfem/mfem#2387]
I don't understand why the following minimal example is not working properly. I have built an SparseMatrix in a function, and the main program does not see it. 

```
#include "mfem.hpp"
#include <fstream>
#include <iostream>

using namespace std;
using namespace mfem;

SparseMatrix * adjacent()
{
  int np = 9;
  int kki[10] = {0, 2, 5, 7, 10, 14, 17, 19, 22, 24};
  int kkj[24] = {1, 3, 0, 2, 4, 1, 5, 0, 4, 6, 1, 3, 5, 7, 2, 4, 8, 3, 7, 4, 6, 8, 5, 7 };

  double kkd[24] = {1.,2.,3.,4.,5.,6.,7.,8.,9.,10.,11.,12.,13.,14.,15.,16.,17.,18.,19.,
		     20.,21.,22.,23.,24.};
  SparseMatrix *adjacentmatrix = new SparseMatrix(kki,kkj,kkd,np,np);
  
  adjacentmatrix->Print();
  return adjacentmatrix;
 
}

int main(int argc, char *argv[])
{
  SparseMatrix * MyMatrix = adjacent();
  MyMatrix->Print();
  return 0;
}
```

**Comment by psocratis** [comment]
@e-aranda , 

What exactly is the problem? I don't see any issues when running the above. 

Socratis

**Comment by e-aranda** [comment]
The matrix is correctly printed inside the function but the print inside the main gives me a Segmentation fault. Do you get the matrix printed twice?

**Comment by pazner** [comment]
Hi @e-aranda,

The problem is that your data arrays `kki`, `kkj`, and `kkd` are stack-allocated, and go out of scope at the end of the function `adjacent`. When the SparseMatrix is created, it takes "ownership" of the data arrays (i.e. it promises to deallocate them when it is destroyed), however it *does not* copy the data, and so when they go out of scope, the pointers in SparseMatrix are no longer valid.

One alternative is to use `Array`, which will allocate the data on the heap. Then, to make sure that the data does not get deallocated when they go out of scope, you can use `LoseData`:

```c++
SparseMatrix * adjacent()
{
  int np = 9;
  Array<int> kki({0, 2, 5, 7, 10, 14, 17, 19, 22, 24});
  Array<int> kkj({1, 3, 0, 2, 4, 1, 5, 0, 4, 6, 1, 3, 5, 7, 2, 4, 8, 3, 7, 4, 6, 8, 5, 7 });

  Array<double> kkd({1.,2.,3.,4.,5.,6.,7.,8.,9.,10.,11.,12.,13.,14.,15.,16.,17.,18.,19.,
		     20.,21.,22.,23.,24.});
  SparseMatrix *adjacentmatrix = new SparseMatrix(kki,kkj,kkd,np,np);

  kki.LoseData();
  kkj.LoseData();
  kkd.LoseData();

  adjacentmatrix->Print();
  return adjacentmatrix;
}
```

**Comment by psocratis** [comment]
just to add to @pazner 's comments, you can also use 
````cpp
  int * kki = new int [10] { 0, 2, 5, 7, 10, 14, 17, 19, 22, 24 };
  int * kkj = new int [24] { 1, 3, 0, 2, 4, 1, 5, 0, 4, 6, 1, 3, 5, 7, 2, 4, 8, 3, 7, 4, 6, 8, 5, 7 };
  double * kkd = new double [24] { 1.,2.,3.,4.,5.,6.,7.,8.,9.,10.,11.,12.,13.,14.,15.,16.,17.,18.,19., 20.,21.,22.,23.,24. };
````
By the way, I was not getting the segfault before using an optimized built. Only in a debug built I was able to reproduce the error. 

Thanks, 

Socratis

**Comment by e-aranda** [comment]
Thanks @pazner and @psocratis for your help. Both solutions work fine.
