### ISSUE TITLE
Error while building parallel version of Mfem with ADIOS2 being used

### ISSUE THREAD

**Issue by prathamgit** [mfem/mfem#2388]
Not sure if this is the correct place to ask, but I couldn't find anything on this elsewhere on the web.
While building mfem's parallel version, the compiler throws the following error
```
mpicxx   -O3 -std=c++11 -I./../hypre/src/hypre/include -I/home/pratham/fem_packs/metis-5.1.0/installDir/include  -I/home/pratham/fem_packs/petsc/installDir/include  -c general/adios2stream.cpp -o general/adios2stream.o
general/adios2stream.cpp: In constructor ‘mfem::adios2stream::adios2stream(const string&, mfem::adios2stream::openmode, MPI_Comm, std::string)’:
general/adios2stream.cpp:118:34: error: use of deleted function ‘adios2::ADIOS::ADIOS(int)’
  118 |      adios(new adios2::ADIOS(comm)),
      |                                  ^
In file included from /usr/local/include/adios2.h:27,
                 from general/adios2stream.hpp:32,
                 from general/adios2stream.cpp:16:
/usr/local/include/adios2/cxx11/ADIOS.h:90:5: note: declared here
   90 |     ADIOS(int define_ADIOS2_USE_MPI_to_use_MPI_constructor) = delete;
      |     ^~~~~
make[1]: *** [makefile:436: general/adios2stream.o] Error 1
make[1]: Leaving directory '/home/pratham/fem_packs/mfem'
make: *** [makefile:478: parallel] Error 2
```
I have edited the config/default.mk file to use ADIOS2, and ADIOS2 is installed in the default paths so the compiler can easily find it. Is there any error in the code or did I do something wrong ?
Please let me know if additional info is required.

**Comment by tzanio** [comment]
It is possible that something in a recent version of ADIOS2 changed.

@williamfgc can you help by any chance?

**Comment by williamfgc** [comment]
@tzanio sure, let me take a look. Sounds about right, the `int` vs `void` comm that different MPI implementations use gets mixed with a recent API change. @prathamgit which adios2 version are you targeting? Are you using MPICH  Also, adios2 should have a `adios2-config` binary to fill the appropriate CFLAGS, LDFLAGS for non-cmake linking (e.g. make), please see [here](https://adios2.readthedocs.io/en/latest/setting_up/setting_up.html#from-non-cmake-build-systems).

**Comment by tzanio** [comment]
Thanks @williamfgc !

**Comment by prathamgit** [comment]
@williamfgc I am using mpich, and the adios2 is the latest one. I had just cloned it from the adios2 repo. I see that the constructor `adios(new adios2::ADIOS(comm))`  being used in mfem's adios2stream class is deleted in [adios2/adios.h](https://github.com/ornladios/ADIOS2/blob/master/source/adios2/core/ADIOS.h) file 
```
/**
     * Delete copy constructor explicitly. Objects shouldn't be allowed to be
     * redefined. Use smart pointers if this is absolutely necessary.
     * @param adios reference to another adios object
     */
    ADIOS(const ADIOS &adios) = delete;
```
I am a beginner in cpp programming and in using mfem and other packages api, so I don't understand much of what's going on. Do you think linking might be an issue? If so, could you point me to what I should be looking for ?

**Comment by williamfgc** [comment]
@prathamgit thanks for the reply, it's helpful. I'm able to reproduce. Are you compiling adios2 with OpenMPI by any chance? It seems that the symbols don't recognize `typedef int MPI_Comm;` in MPICH. Please try recompiling adios2 with MPICH and see if it works (FYI, hypre built with OpenMPI doesn't work with MPICH MFEM builds). What happens is that OpenMPI uses a `void` pointer instead for the `MPI_Comm` type, while MPICH uses `int` that's why ADIOS2 delete those constructors explicitly. I might report this upstream.

No worries, the best way to learn is to go through open-source codes like MFEM developed by an awesome community 👍

**Comment by prathamgit** [comment]
I rebuilt hypre, metis and adios2 making sure i was only using mpich. I still get the same error. Am I doing anything wrong or does the code need any changes ?

**Comment by rcarson3** [comment]
@prathamgit would you be able to try either version 2.5 or 2.6 of ADIOS2? I'd just be curious to see if the issue is with the develop/master branch of ADIOS2, since it seems that's what you're using. I've used ADIOS2 v2.5 and v2.6 builds for my own MFEM-based code on Summit and my own personal ubuntu desktop with success when using mpich.

**Comment by prathamgit** [comment]
> @prathamgit would you be able to try either version 2.5 or 2.6 of ADIOS2? I'd just be curious to see if the issue is with the develop/master branch of ADIOS2, since it seems that's what you're using. I've used ADIOS2 v2.5 and v2.6 builds for my own MFEM-based code on Summit and my own personal ubuntu desktop with success when using mpich.

Ya that's what I was going to do next. I'll let you know if it works.

**Comment by prathamgit** [comment]
> @prathamgit would you be able to try either version 2.5 or 2.6 of ADIOS2? I'd just be curious to see if the issue is with the develop/master branch of ADIOS2, since it seems that's what you're using. I've used ADIOS2 v2.5 and v2.6 builds for my own MFEM-based code on Summit and my own personal ubuntu desktop with success when using mpich.

It worked with adios2 V2.5

**Comment by williamfgc** [comment]
@rcarson3 @prathamgit thanks for verifying. I tried with the latest branch of adios2 building HYPRE and METIS (and adios2) with MPICH and I wasn't able to reproduce. I put a `Dockerfile` in my [local branch](https://github.com/williamfgc/mfem/blob/dockerfile-ubuntu20-mpich/config/docker/ubuntu20-mpich/Dockerfile) if you're interested for reproducibility. If you're not familiar with docker just ask here.  The only time I see it is when adios2 is built with OpenMPI. Hope it helps. Thanks for bringing this up.

**Comment by williamfgc** [comment]
@prathamgit please let me know if this is still an issue.

**Comment by prathamgit** [comment]
@williamfgc I am sorry for the super late reply. I had recently switched from mpich to openmpi, and to my surprise the mfem compilation worked even with master version of adios2( without pulling latest code for either mfem or adios2).
I pulled the latest code for both adios2 and mfem, and everything works fine.
It may work with mpich too, but I'm afraid I cant switch back to mpich

**Comment by tzanio** [comment]
Thanks for your help @williamfgc!

**Comment by rcarson3** [comment]
@williamfgc I ran into this issue as well while using a v2.7.1 build with a cmake build of mfem. I found I had to add the following to my cmake invocation to get things to work:
`-DCMAKE_CXX_FLAGS=-DADIOS2_USE_MPI` . I was able to compare the v2.5.0 and v2.7.1 branches and found that sometime between the two that `ADIOS(int define_ADIOS2_USE_MPI_to_use_MPI_constructor) = delete;` definition was added and hidden behind some macro defines.

It would be nice if these sorts of defines were automatically generated by cmake during y'all's build process and were kept in something like a `adios2_config.h` file that way we wouldn't have to pass in these sorts of defines to our build process.

**Comment by williamfgc** [comment]
@rcarson3 thanks for reporting this. Which adios2 distribution? I remember you used conda at some point. A typical adios2 installation ships with all the cmake relevant configuration under (`adios2/lib/cmake/adios2`).  ADIOS2 v2.6 moved to a unified distribution for MPI and non-MPI libraries, so there are some changes in the API constructors to avoid conflicts (or it might have introduced one). Hope it helps. If this still doesn't work, feel free to open an issue on the adios2 repo, thanks!

**Comment by rcarson3** [comment]
@williamfgc I'm currently using a spack build for this as I've run into issues trying to install it manually. I'm using the below spack install command:

`spack install adios2@2.7.1+hdf5~fortran~python ^mvapich2@2.3%gcc@10.2.1 ^hdf5@1.8.21` this is with the master branch of spack and its running on one of our CTS machines here at LLNL. The spack compiler and package yaml files are based on the ones here: https://github.com/mfem/mfem-uberenv/tree/master/spack_configs/toss_3_x86_64_ib .

I will mention that I have not run into this issue with the ORNL install of adios2, which I know also uses spack to install it, but I'm not quite too sure what options are being used there, but it might be nice to try and reproduce there commands on our machines as I still can't get it installed on Lassen even using spack...

I will also mention at least with the builds on the LLNL machines I'm also running into an issue where Paraview v5.9.1 appears to be crashing with this version of adios2 when I advance a time step and a variable that was defined in a previous time step is no longer available. For example, I define one variable during time step 0 to see the element attribute defined with the mesh and then turn that  off in later steps to save hard drive memory. I could open an issue related to this on the adios2 github repo, and send y'all a small reproducer if that would help.

**Comment by rcarson3** [comment]
@williamfgc so I can't seem to open ADIOS2 files using paraview 5.9.1 on ORNL's Andes platform. However, data I've generated on Summit and saved off using ADIOS2 also crashed in Paraview when moving to the next frame on my home desktop. So, I'll work on a small reproducer data set and open an issue, but  this will probably won't be until next week.

**Comment by prathamgit** [comment]
> @williamfgc I ran into this issue as well while using a v2.7.1 build with a cmake build of mfem. I found I had to add the following to my cmake invocation to get things to work: `-DCMAKE_CXX_FLAGS=-DADIOS2_USE_MPI` . I was able to compare the v2.5.0 and v2.7.1 branches and found that sometime between the two that `ADIOS(int define_ADIOS2_USE_MPI_to_use_MPI_constructor) = delete;` definition was added and hidden behind some macro defines.
> 
> It would be nice if these sorts of defines were automatically generated by cmake during y'all's build process and were kept in something like a `adios2_config.h` file that way we wouldn't have to pass in these sorts of defines to our build process.

Thank you @rcarson3.
I went into the same issue(original in this post) and `-DCMAKE_CXX_FLAGS=-DADIOS2_USE_MPI` flag while building mfem with cmake worked like magic.
(I am using everything (hypre, adios2) built with OpenMPI btw)
