### ISSUE TITLE
pre-defined element and boundary attributes

### ISSUE THREAD

**Issue by dbgarlisch** [mfem/mfem#2389]
We are adding an MFEM importer and exporter to Cadence Pointwise. If supported, we need a list of supported Volume Condition (VC) and Boundary Condition (BC) types.

I have searched the source code looking for any notion of pre-defined element (VC) or boundary (BC) attribute values. I could find none.

Are there any attributes we should add to to our exporter. For instance:
* A `Wall`, `Inlet`, or `X-Symmetry` BC type
* A `Fluid` or `Solid` VC type.

If these do not exist, that is fine. I just want to be sure. In Pointwise, the user can define boundary patches (BC) or volume regions (VC) of "Unspecified" type. These BCs and VCs have a user-defined id value that will be written to the file as the attribute.

![image](https://user-images.githubusercontent.com/4324473/124669747-842e4a00-de78-11eb-93e3-fcb63f44c092.png)

Sample output:
```
MFEM mesh v1.0

# Created by: Pointwise V18.5A1

# MFEM Geometry Types:
#
# POINT       = 0
# SEGMENT     = 1
# TRIANGLE    = 2
# SQUARE      = 3
# TETRAHEDRON = 4
# CUBE        = 5

dimension
3

elements
270
1 4 88 48 92 94
1 4 4 44 33 29
   ...SNIP...
1 4 59 47 88 93
1 4 7 47 43 59

boundary
168
2 2 26 84 82
2 2 25 81 84
   ...SNIP...
2 2 39 27 82
2 2 25 24 81
2 2 80 79 78
3 2 17 19 3
3 2 19 16 2
   ...SNIP...
3 2 16 1 2
3 2 13 14 15
1 2 33 37 29
1 2 37 34 28
   ...SNIP...
1 2 70 10 57
1 2 11 69 12

vertices
98
3
1 0 1.540743955509789e-33
1 0.3333333333333333 1.540743955509789e-33
   ...SNIP...
0.7498750000000001 0.2501250000000001 0.5
0.250125 0.250125 0.5
```

Also, is there a supporting attribute file that defines the BC and VC information?

Something like:
```
# <number of element zones>
# <zone attribute> <zone type> <zone name>
element_zones
1
1 Unspecified Fluid


# <number of boundary zones>
# <zone attribute> <zone type> <zone name>
boundary_zones
3
1 Unspecified BcWall
2 Unspecified BcIn
3 Unspecified BcOut
```

**Comment by tzanio** [comment]
Hi @dbgarlisch,

MFEM meshes do not have exactly VC and BC types as you describe them, but we have something close.

Each volume element and each boundary element in the file have a respective element and boundary attributes. These are the first integers on the element/boundary rows, see also https://mfem.org/mesh-formats/#curvilinear-and-more-general-meshes.

It is up to the user/application to associate VC and BC with these attributes.

For example, one can take the volume/element attributes and associate different materials with them. That is done e.g. in Example 2, https://github.com/mfem/mfem/blob/master/examples/ex2.cpp#L27-L30.

You can similarly use the boundary attributes to impose different type of boundary conditions, see again the above example.

The reason for these choices is that MFEM provides the building blocks for many different types of simulations, and the types of BCs for example differ between the fluid and electromagnetic application.

Hope this makes sense. Please let us know if we can be of any help.

Tzanio

**Comment by dbgarlisch** [comment]
Thanks for the feedback. I expected there were no pre-defined attributes. Had to ask.

I will leave all as is. Pointwise users will be able to specify the attribute id written out to the volume and boundary elements using the 'ID' column (red arrow in image above). These IDs can be seen in the sample file listed above.
