### ISSUE TITLE
Element topo connectivity

### ISSUE THREAD

**Issue by dbgarlisch** [mfem/mfem#2390]
Is there a diagram defining the topological connectivity index numbering used by 2-D and 3-D elements in MFEM?

Something like [these diagrams](http://www.pointwise.com/plugins/html/d5/d06/group__DOXGRP__APIPWGM__CELL__TOPO.html)

**Comment by pazner** [comment]
I don't know if a diagram exists, but this information is all defined in `geom.cpp`.

For example, the vertices of the reference tetrahedron are defined [here](https://github.com/mfem/mfem/blob/bf542247e8057edbcdbadb14f035a2b5252c8ee6/fem/geom.cpp#L65-L79). The edges of the tetrahedron (in terms of vertex indices) are defined [here](https://github.com/mfem/mfem/blob/bf542247e8057edbcdbadb14f035a2b5252c8ee6/fem/geom.cpp#L802-L804). The faces of the tetrahedron (in terms of vertex indices) are defined [here](https://github.com/mfem/mfem/blob/bf542247e8057edbcdbadb14f035a2b5252c8ee6/fem/geom.cpp#L811-L813).

You can find similar information for all element types in the same file. This should be enough information to recreate those kinds of diagrams.

**Comment by dbgarlisch** [comment]
Thank you. I will study these modules.

**Comment by tzanio** [comment]
@dbgarlisch if you end up generating diagrams like these, please do share them, we will be happy to add them to our documentation.

**Comment by dbgarlisch** [comment]
It turns out MFEM is using the exact same element vertex ordering used in Pointwise. That means the corner point numbers are the same as in the images I linked to above. However, the edge and face numbering is different. Fortunately, that difference did not impact the exporter (or importer).

If I generate an MFEM connectivity image, I will definitely send it your way.

FYI, we have added the MFEM exporter to our production code. Barring any unforeseen obstacles, it should be available in the upcoming V18.5 release of Pointwise. The MFEM importer is still in work. It should be done soon.

**Comment by tzanio** [comment]
Awesome, thanks @dbgarlisch !

**Comment by tzanio** [comment]
Did the exporter (or importer) support high-order meshes? Is there a way for our team to test it?

**Comment by dbgarlisch** [comment]
At this time only linear meshes are exported. Adding HO support requires another feature request.

We have a customer that is using MFEM for HO via Gmsh. However, the customer is reporting MFEM is not reading the Gmsh file exported by Pointwise. We are investigating. I suspect the customer mesh includes pyramid elements. :(

**Comment by mlstowell** [comment]
Pyramids would certainly be a showstopper at this point. You're probably aware of this but our most common issue with Gmsh meshes is that by default Gmsh starts numbering Physical Curves/Surfaces/Volumes at 0. These numbers are used as attribute numbers by MFEM but MFEM requires attributes to be greater than or equal to 1.
