### ISSUE TITLE
Output solution data to .dat file

### ISSUE THREAD

**Issue by sashank-srinivasan-13** [mfem/mfem#2393]
Is there a straightforward way to output solution data vs position to a .dat file or equivalent file? If not, can I know how I can compare solutions I get from mfem to analytical solutions?

**Comment by jandrej** [comment]
Hello,

you can look at the following example https://github.com/mfem/mfem/blob/a4f5cc53ca87d60795f85f36401789932c98409c/miniapps/navier/navier_mms.cpp#L204-L208.

The coefficients are created here https://github.com/mfem/mfem/blob/a4f5cc53ca87d60795f85f36401789932c98409c/miniapps/navier/navier_mms.cpp#L166-L167

The analytical solution function (defined as a callback here) is defined here
https://github.com/mfem/mfem/blob/a4f5cc53ca87d60795f85f36401789932c98409c/miniapps/navier/navier_mms.cpp#L44-L51

Let me know if that helps.

**Comment by mlstowell** [comment]
Hello, @sashank-srinivasan-13,

I agree with @jandrej that `ComputeL2Error` produces the most reliable comparison to an analytic function. To answer the first part of your question there is also a straightforward way to produce a data file containing positions and field values. Have a look at the [get-values](https://github.com/mfem/mfem/blob/master/miniapps/tools/get-values.cpp) mini app. This tool produces exactly this type of output file from a set of points. The points can be supplied on the command line or through an input file. You could also write something similar which computes a grid of points for example. Some projects have written python scripts to produce an input file of points and then call `get-values` on this input file.

Best wishes,
Mark
