### ISSUE TITLE
Pyramid/Pentahedral Elements

### ISSUE THREAD

**Issue by dbgarlisch** [mfem/mfem#2395]
With the addition of an MFEM exporter to Pointwise, we are very interested in the status of Pyramid/Pentahedral elements.

Is there a timeline for the addition of Pyramid support? There has been some discussion in other issues (e.g. Pentahedral element #856) but no resolution.

Pyramids are always generated by some of the more powerful Pointwise meshing tools (e.g. T-Rex boundary layer mesher, and the Voxel mesher). Until pyramids are supported, grids will be restricted to blocks containing only hex, tet, and extruded prism cells which excludes these tools.

Also, Pointwise can export high order (HO) meshes (up to Q4) to several formats including Gmsh.

**Comment by tzanio** [comment]
We are working on adding pyramids. I'll let @mlstowell address that.

> Pointwise can export high order (HO) meshes (up to Q4) to several formats

Is MFEM one of those formats? I suspect the answer is "no" as that's more involved, but MFEM supports arbitrary order meshes and it will be really nice if there is a mesh generator that can provide them to our users. See https://mfem.org/mesh-formats/#curvilinear-and-more-general-meshes

**Comment by dbgarlisch** [comment]
At this time only linear meshes are exported by pointwise to MFEM. Mesh elevation is independent of the export format, so adding HO support is doable. However, it requires another feature request.

We have a customer that is using MFEM for HO via Gmsh. However, the customer is reporting MFEM is not reading the Gmsh file exported by Pointwise. We are investigating. I suspect the customer mesh includes pyramid elements. :(

**Comment by tzanio** [comment]
> We have a customer that is using MFEM for HO via Gmsh. However, the customer is reporting MFEM is not reading the Gmsh file exported by Pointwise. We are investigating. I suspect the customer mesh includes pyramid elements. :(

We are happy to help debug. Note that we currently support only Gmsh v2.2

**Comment by mlstowell** [comment]
Unfortunately, we don't have a specific timeline for adding pyramid support. We do have pyramids partially implemented in the [pyramid-dev](https://github.com/mfem/mfem/tree/pyramid-dev) branch. We could probably get this working for scalar fields without too much effort. If I recall correctly the code in this branch can display pyramid meshes properly but trying to solve Poisson problems leads to trouble.

This is something I have been eager to add to MFEM but time pressures have been the issue.

**Comment by mlstowell** [comment]
Hi, @dbgarlisch,

We now have more functional examples of prism and pyramid support in PR #2400. This PR adds the lowest order basis functions for H1, Nedelec, Raviat-Thomas, and L2 functions spaces on wedges and pyramids. It also includes a few temporary example codes (examples/ex1_o1.cpp, ex3_o1.cpp, ex4_o1.cpp, and ex11p_o1.cpp) so that reviewers can see how to access and test these new basis functions.

The goal is to support arbitrary order basis functions but these provide a starting point.

Best wishes,
Mark

**Comment by tzanio** [comment]
As mentioned above, support for 1st order pyramids will soon be available in `master` via #2400.

We will work on support for higher-order pyramids in the next year.
