### ISSUE TITLE
How to build the map from global nodal index to local true DOF index in parallel code

### ISSUE THREAD

**Issue by HaoWangCase** [mfem/mfem#2398]
Hi guys, right now I would like to find how to build the connectivity table from the global nodal index to the local true DOF index (assuming that we have a scalar unknown). I already know how to build the map from global nodal index to local nodal index, but in parallel, the shared nodes are only considered as true DOFs in some of the processors. How to figure out whether a local node is included in the local true DOFS or not? Thanks.

**Comment by pazner** [comment]
Perhaps what you are looking for is `ParFiniteElementSpace::GetLocalTDofNumber`, which will return a non-negative number if the local DOF is a true DOF, and -1 otherwise.

https://github.com/mfem/mfem/blob/bf542247e8057edbcdbadb14f035a2b5252c8ee6/fem/pfespace.hpp#L354-L356

**Comment by HaoWangCase** [comment]
Thanks, @pazner ! It's really what I need!
