### ISSUE TITLE
an error when calcualte the time of UMFPACK solver

### ISSUE THREAD

**Issue by nghiakvnvsd** [mfem/mfem#2401]
Hi everyone! I try to calculate the time for UMFPACK solver like the following code (ex1):

```
const clock_t time_solver = clock();
UMFPackSolver umf_solver;
umf_solver.Control[UMFPACK_ORDERING] = UMFPACK_ORDERING_METIS;
umf_solver.SetOperator(*A);
umf_solver.Mult(B, X);
std::cout <<"time_solver = "<< double( clock () - time_solver ) /  CLOCKS_PER_SEC <<"\n";
```
But it returns the wrong time result. May you help me to calculate the time when using UMFPACK? Thank you very much

**Comment by jwang125** [comment]
Hi, can you elaborate why you think the result is wrong? I did what you did and obtained time_solver = 0.23. Using std::chrono functions returned nearly identical result.
