### ISSUE TITLE
DerivativeIntegrator in embeded geometry

### ISSUE THREAD

**Issue by sshiraiwa** [mfem/mfem#2402]
I noticed that DerivativeIntegrator ( \lambda dv/dx_xi u) does not work well when
my 1D geometry is embedded in a higher dim. For example, if my geometry is a line segment
oriented in the y direction, I suppose passing 1 in the second argument of the constructor
should allows for evaluating the gradient. But, it gives all zero. 

Sizing properly mfem::DenseMatrix used in DerivativeIntegrator::AssembleElementMatrix2 seems
to address this.

Is this a known issue and being fixed in the next release? Or shall I make a PR?

**Comment by tzanio** [comment]
Discussion continued in #2403.
