### ISSUE TITLE
Re-partition a ParGridFunction?

### ISSUE THREAD

**Issue by trevilo** [mfem/mfem#2404]
Hi all,

Is it possible to re-partition a `ParGridFunction` using built-in MFEM
functionality?

The use case I have in mind is restarting jobs using different numbers
of MPI processes.  I am working with an MFEM-based flow code where we
have a restart capability that saves a single HDF5 file per MPI
process.  We read these files to restart simulations, but this only
works when restarting using the same parallel decomposition.  This is
analogous to the Save/Load functionality in, for instance,
`VisItDataCollection`.  For flexibility with changing order and
mesh resolutions, we are trying to develop a capability to restart a
job with a different number of MPI processes.

While it would be best to avoid constructing a serial `GridFunction`, if
it is not possible to re-partition directly, as a workaround, I was
considering constructing a serial `GridFunction` and then constructing
the `ParGridFunction` from that and the new desired partitioning array.
To do this though I would need to be able to construct a serial
`GridFunction` from a `ParGridFunction`, which I do not see how to do.  I
have looked at the `ParGridFunction::SaveAsOne` method, but this does
not seem to do quite what I need (although I might be misunderstanding
that function).

Any advice would be much appreciated.  Thanks.

**Comment by v-dobrev** [comment]
Hello @trevilo,

Unfortunately, re-partitioning parallel meshes and grid-functions is not implemented in MFEM yet.

Adding such capability is on our todo list, probably later this year.

**Comment by trevilo** [comment]
Hi @v-dobrev,

Good to know.  Thanks for your reply.
