### ISSUE TITLE
nonlinear mass integrator

### ISSUE THREAD

**Issue by bensworth** [mfem/mfem#2405]
I am working on some IMEX integration schemes and testing on an advection-diffusion reaction with nonlinear reaction term. Everything is working well without the reaction term, but when I add the reaction term, the accuracy w.r.t. an analytical solution is not what it should be. For large reaction, I get a sort of accuracy barrier where the solution will not get above a certain accuracy, even for small h and dt. It is possible this is a "true"/natural behavior, but it is certainly surprising.

EDIT: removed initial code that was not a good way to do this; tagged @vladotomov in case you have done something similar to this with T^4 terms in transport problems.

**Comment by v-dobrev** [comment]
One issue I see (for more than one processor or non-conforming meshes) is that the vector `u` is a T-vector while the `reaction` is an L-vector -- you need to apply the FE space prolongation to `u` before calling `SetReaction`.

Also, I don't see any boundary conditions being applied to `m_nl` or `NL` -- is that correct?

**Comment by bensworth** [comment]
Thanks Veselin, I didn't apply BCs because they are naturally enforced pointwise by the SetReaction function, but with the mass integrator, do I still need to apply them?

Perhaps a better question than my original post is how would *you* add a pointwise nonlinear reaction to a discretization? Even in the simplest case, u_t = N(u) + f(x,t), where N(u) is a pointwise nonlinear function. This is somewhat artificial because all of the equations should be decoupled, but informative in principle. It seems like mass matrices would add some form of coupling to this otherwise decoupled problem?

**Comment by jandrej** [comment]
You create a linearized matrix `NL` from `m_nl` and apply it to your residual. Is that really what you want to do? Since the method is named `ExplicitMult`, I'd expect you want to multiply `m_nl` directly.

Regarding boundary conditions, you have to set them on the nonlinear form as well, if they are Dirichlet. This way you get ```
N(u_ess) = 0
```
which is only correct if you solve a

**Comment by bensworth** [comment]
@jandrej great point; I started by using m_nl.Mult(), but wasn't getting accurate results, so I tried turning it into a matrix. But even with m_nl.Mult(), would that have the same problem that you mention? I.e., is my using a ParBilinearform and custom "nonlinear" coefficient mass matrix functional, or do I need to use the NonlinearForm?

Also, re my previous post, if you have a better suggestion than what I tried, happy to hear it. I just want to add a reaction term for explicit time stepping, e.g., add a `+u(1-u)` reaction term to ex9p.

**Comment by jandrej** [comment]
If I'd have to implement a reaction term that is nonlinear I would use a `NonlinearForm`. You can be sure that on every evaluation you are recomputing the result and if you need a Jacobian it gets evaluated at the correct solution. Your described term will be 95% boilerplate and 5% custom equation :)

**Comment by bensworth** [comment]
Sounds good. So next: should I use a nonlinear (mass) integrator added to the NonlinearForm? This would just require an implementation of `AssembleElementVector`, and `AssembleElementGrad` if I end up wanting a Jacobian. These should follow closely `AssembleElementVector` for a standard `MassIntegrator`, but thought it may make sense to include the coefficient, Q, inside of this nonlinear integrator class to be re-evaluated during each Mult(), while being a bit hidden from the user. Does this make sense, and/or am I overthinking it and could just use a linear mass integrator with the coefficient I posted originally?

**Comment by jandrej** [comment]
What I have in mind is a `NonlinearForm` with the `AssembleElementVector` loop looking like
```
elvect = 0.0;
for each quadrature point do
   Vector u(elfunc_transformed);
   elvect += test_function * u * (1.0 - u) * weight
end do
```
`elfunc` is the name of `u` in the function signature. Then `Mult()` would take care of everything imho.

Does that make sense? You can also shoot me an email if you want more hands on help.

**Comment by bensworth** [comment]
Update: with Julian's help, I implemented a `NonlinearFormIntegrator` that we thought would do what was expected, but it does not seem to work. I simplified the setting to considering a reaction problem with explicit time stepping. The example is completely artificial to narrow down what's going on. It's not even a PDE, just a bunch of independent ODEs that are
coupled within each element due to the DG mass matrix.

I made a simple time-dependent reaction script, which should be an independent ODE for each spatial point. I set the IC to
    `u0(x,y) = sin(2pi*x(1-y))sin(2pi*y(1-x))`
on the inline quad mesh and solve the equation
    `u_t = eta*u(1-u), u(0) = u0.`
This is a separable equation with solution
       `u0*e^(Ct) / (1 + u0(e^(Ct)-1)). `
I made two scripts, each with two examples (one example with nonzero forcing function and one example with zero forcing function, hard coded with a `#define forcing`; both have analytical solutions):
1. A pointwise definition of functions (i.e., no real FEM infrastructure, just propagating ODEs on the mesh vertices). This one is able to get high-order accuracy, has no stability issues, and gets expected order with various explicit time stepping on both examples.
2. A DG FEM definition of functions. This involves a `ParLinearForm` for the forcing function, a DG mass matrix and inverse, and a `NonlinearForm` for the nonlinear reaction term. The DG mass struct and inverse have been confirmed on a DG adv-diff example to give HO accuracy without the reaction term, so there is no issue with the inverse. Here, I am unable to get reasonable accuracy. Regardless of time step size, things start off okay, then elements start to split (solution looks discontinuous within element), and eventually about half of the domain explodes to NAN. Below is a Paraview plot of the solution right before it explodes, with all of the "split" elements, as well as a matplotlib plot of the solution. Script (1) confirms we should not have any stability issues here, so the exploding is coming somewhere from the use of FEMs.

![mfem_sol_t2 57](https://user-images.githubusercontent.com/8642948/126223763-a04fc0ce-18dd-4fc6-a917-7affd62596a7.png)
![sol_eta0 5_t2 5](https://user-images.githubusercontent.com/8642948/126223889-7b0e1127-4512-44b0-a487-a9f9ad25ee78.png)

So, how should this nonlinear form be defined in the FEM context? Clearly something is not working correctly. I have also added the same nonlinear form to a more complex adv-diff-reaction code. There I do not get exploding solutions, but I do not get accurate solutions either. Is there something subtle where this disc. does not make sense? 

I attached the two scripts, -mfem denoting the FEM context and -ODE the pointwise context. Below is also the `NonlinearFormIntegrator` class that seems the likely culprit. Any help is greatly appreciated; I didn't realize a reaction term would be so complicated to add correctly,
```
// Nonlinear integrator for reaction term eta*u*(1-u)
class NonlinearReaction : public NonlinearFormIntegrator
{
public:

   const IntegrationRule &GetRule(const FiniteElement &trial_fe,
     const FiniteElement &test_fe, ElementTransformation &Trans)
   {
      const int order = trial_fe.GetOrder() + test_fe.GetOrder() + Trans.OrderW();
      return IntRules.Get(trial_fe.GetGeomType(), order);
   }

   virtual void AssembleElementVector (const FiniteElement &el,
      ElementTransformation &Tr, const Vector &elfun, Vector &elvect)
   {
      int nd = el.GetDof();
      double w;
      Vector test_fun;
      elvect.SetSize(nd);
      test_fun.SetSize(nd);

      const IntegrationRule *ir = IntRule ? IntRule : &GetRule(el, el, Tr);

      elvect = 0.0;
      for (int i = 0; i < ir->GetNPoints(); i++)
      {
         const IntegrationPoint &ip = ir->IntPoint(i);
         Tr.SetIntPoint(&ip);
         w = Tr.Weight() * ip.weight;
         el.CalcPhysShape(Tr, test_fun); // size nd

         // Take inner product with ith test function
         double fx_qp = 0.0;
         for (int j=0; j<nd; j++) {
            fx_qp += eta*test_fun[j]*elfun[j]*(1 - elfun[j]);
         }
         elvect[i] += w * fx_qp;
      }
   }
};
```

**Comment by bensworth** [comment]
It would not let me upload .cpp files to an issue, so the two scripts are attached as .txt files. They should run by default with no command line parameters.

[reaction-test-mfem.txt](https://github.com/mfem/mfem/files/6843828/reaction-test-mfem.txt)
[reaction-test-ODE.txt](https://github.com/mfem/mfem/files/6843829/reaction-test-ODE.txt)

**Comment by jandrej** [comment]
post release bump

**Comment by bensworth** [comment]
Hi guys, any thoughts here? It seems like conceptually this shouldn't be so hard, so either there is a simple bug in what I am doing (more likely) or something funny with MFEM integrators (less likely, but I can't find a bug)

**Comment by pazner** [comment]
Hi @bensworth,

Try the following nonlinear integrator and let me know if it works better for you:
```cpp
// Nonlinear integrator for reaction term eta*u*(1-u)
class NonlinearReaction : public NonlinearFormIntegrator
{
public:

   const IntegrationRule &GetRule(const FiniteElement &trial_fe,
     const FiniteElement &test_fe, ElementTransformation &Trans)
   {
      const int order = trial_fe.GetOrder() + test_fe.GetOrder() + Trans.OrderW();
      return IntRules.Get(trial_fe.GetGeomType(), order);
   }

   virtual void AssembleElementVector (const FiniteElement &el,
      ElementTransformation &Tr, const Vector &elfun, Vector &elvect)
   {
      int nd = el.GetDof();
      Vector shape(nd);
      elvect.SetSize(nd);

      const IntegrationRule *ir = IntRule ? IntRule : &GetRule(el, el, Tr);

      elvect = 0.0;
      for (int i = 0; i < ir->GetNPoints(); i++)
      {
         const IntegrationPoint &ip = ir->IntPoint(i);
         Tr.SetIntPoint(&ip);
         double w = Tr.Weight() * ip.weight;

         el.CalcShape(ip, shape);
         double el_value = shape*elfun;
         // Take inner product with jth test function, eta=reaction coeff
         for (int j=0; j<nd; j++)
         {
            elvect[j] += w*shape[j]*eta*el_value*(1 - el_value);
         }
      }
   }
};
```

**Comment by bensworth** [comment]
Hey Will, think this is doing what it's supposed to. It works for my super simple ODE example. I still don't get good accuracy on a nonlinear adv-diff-reaction system, but I am using IMEX integration and learning that DG can be very sensitive to splittings; treating a strong reaction term explicitly seems to cause pretty serious degradation in accuracy. Will add an implicit solver at some point to make sure the discretization is right, but seems like it is and will close for now.
