### ISSUE TITLE
multi-domain nonlinear problem

### ISSUE THREAD

**Issue by brightzhang91** [mfem/mfem#2408]
Dear developer and users : )

I'm working on a problem with both linear and nonlinear material properties in different domains. I have produced my own `NonlinearFormIntegrator` for the nonlinear materials.  The problem will be solved by a `NewtonSolver` (and then perhaps a `PetscNonlinearSolver` ). I wonder if the nonlinear domains and linear domains can be specified with PWConstCoefficient ? such as the following :

```
Vector domain_L(ess_domain.Size()),   domain_NL(ess_domain.Size());// ess_domain.Size()=2,  with 0 for linear domain, 1 for nonlinear domain
domain_L = 0.0;
domain_L(0) =1.0;        // linear domain
domain_NL = 0.0;
domain_NL(1) = 1.0;    // nonlinear domain
Coef_L = new PWConstCoefficient(domain_L);   // define PWConstCoefficient to specify linear domains
Coef_NL = new PWConstCoefficient(domain_NL);  //   define PWConstCoefficient to specify nonlinear domains

LHS_linear = new ParBilinearForm(HCurlFESpace); // define BilinearForm
LHS_linear->AddDomainIntegrator(new CurlCurlIntegrator(*Coef_L));

LHS_nonlinear = new ParNonlinearForm (HCurlFESpace); //  define  NonlinearForm 
LHS_nonlinear->AddDomainIntegrator(new SelfdefinedNLIntegrator(*Coef_NL)); 
```
And in the `Mult()` and `GetGradient()` of the Operator, as required by the `NewtonSolver` , are defined similarly with ex10p.

In `Mult()` 
   ```
  LHS_nonlinear->Mult(k, residual); 
  LHS_linear->TrueAddMult(k, residual, 1.0);
  residual.SetSubVector(ess_tdof_list, 0.0);
```
In `GetGradient()` 

```
SparseMatrix  *localJ = LHS_linear->SpMat(); 
localJ->Add(1.0, LHS_nonlinear->GetLocalGradient(k));
Jacobian = LHS_massH->ParallelAssemble(localJ);
delete localJ; 
HypreParMatrix *Je = Jacobian->EliminateRowsCols(ess_tdof_list);  
delete Je;
return *Jacobian;
```

Do you think this is a correct approach to deal with a multi-domain problem with both linear and nonlinear domains ?  The simulation does not give me the correct results yet but I'm not sure if it is due to this approach.
Thanks very much !

Bright

**Comment by jandrej** [comment]
From what you are explaining about your implementation the domains do not exchange information, due to the PWConstCoefficient.

Regarding the coupling, when you compute the Jacobian, all contributions of the linear terms are zero on the block of the nonlinear terms and vice versa. I'm not sure if that is what you want or expect.

I hope that makes sense.

**Comment by brightzhang91** [comment]
> Regarding the coupling, when you compute the Jacobian, all contributions of the linear terms are zero on the block of the nonlinear terms and vice versa. I'm not sure if that is what you want or expect.
> 
Hi jandrej

Yes this is what I expect,  to make nonlinear terms zero on linear material domains, and linear terms zero on nonlinear material domains. It's like of superposition method to calculate both residual and Jacobian. 
Do you think this approach is correct ? Or if there is other ways to deal with different materials in different domains ?
Thanks

**Comment by brightzhang91** [comment]
> From what you are explaining about your implementation the domains do not exchange information, due to the PWConstCoefficient.
> 
Yes, but I'm not clear if this can cause problems.
