### ISSUE TITLE
Differences between ParGridFunction::GetValue and GridFunction::GetValue

### ISSUE THREAD

**Issue by stefanozampini** [mfem/mfem#241]
Why there is this discrepancy between the two methods?
GridFunction::Eval(i,....) tests for fe->GetMapType(), see here https://github.com/mfem/mfem/blob/master/fem/gridfunc.cpp#L361

instead, ParGridFunction does not, see https://github.com/mfem/mfem/blob/master/fem/pgridfunc.cpp#L266

**Comment by v-dobrev** [comment]
It certainly makes sense to have the `MFEM_ASSERT` in both places. We should add the check to the ParGridFunction version of the method. Or, if you need it, we can add support for `INTEGRAL` MapType as well.

**Comment by stefanozampini** [comment]
I don't need INTEGRAL I guess, I just noticed the discrepancy while playing around with the GridFunctionCoefficient.
I need a mesh dependent, L2 coefficient for the bilinear form integrators.
So, I'm fine with the current support of VALUE MapType.

**Comment by stefanozampini** [comment]
See #261
