### ISSUE TITLE
Straight .mesh File Section Ordering

### ISSUE THREAD

**Issue by dbgarlisch** [mfem/mfem#2410]
All the examples of [straight meshes][1] have the same section ordering:
```
MFEM mesh v1.0
dimension
elements
boundary
vertices
```

I understand that `MFEM mesh v1.0` must be the first non-empty/non-comment line in the file. However, I cannot find any definitive statement that requires a particular section ordering.

Q: **Is there a section order requirement for the `dimension`, `elements`, `boundary`, or `vertices`?**

And on a related note,

Q: **Is it valid to write other *proprietary* sections in the file? That is, should an MFEM reader just ignore any sections it does not recognize?**

Thanks!

-----------
FYI, we just finished adding the MFEM straight mesh reader to Cadence Pointwise. The reader *will* handle the sections in any order and *will* ignore any unknown sections. For example, a file with section order as shown below will import correctly into Pointwise.
```
# leading comments and empty lines

# another comment

MFEM mesh v1.0
vertices
custom_section_1
boundary
custom_section_2
elements
dimension
custom_section_3
```
![image](https://user-images.githubusercontent.com/4324473/126003755-5c60eb91-f9dc-4db4-8b5a-36d6cdeb8775.png)

[1]: https://mfem.org/mesh-formats/#straight-meshes

**Comment by mlstowell** [comment]
Hi, @dbgarlisch,

The MFEM mesh v1.0 format does indeed require this particular section order. Any custom sections inserted between these primary sections will cause an error in our mesh reader. However, you can include as many comment lines (starting with #) as you like between sections (but not within the data). After the "vertices" section there is an optional "nodes" section which provides information used to define high order elements. I believe anything after "nodes", if it is present, would be ignored by our mesh reader. If there is no "nodes" section immediately following the "vertices" section I believe our mesh reader would stop reading at that point.

Best wishes,
Mark

**Comment by tzanio** [comment]
To add to Mark's answer -- we could add the flexibility to use different order and/or ignore proprietary sections if that is really important for you.

Also -- it is awesome to see the MFEM reader in Pointwise. _Thank you for that!_  🎉 🎉 🎉

**Comment by dbgarlisch** [comment]
My motivation is to add a `materials` section to the file so I can preserve information we have in Pointwise in the MFEM file. 

Something like:
```
conditions
[element | boundary] <element attribute> <condition type> <user id> <user name>
<number of key-value pairs>
<key>=<value>
         ...
<key>=<value>
```
There would be an [element | boundary] row  for each unique `<element attribute>` refenced in the `elements` or `boundary` sections.

I have forked the mfem repo. I may be able to find time to redo the importer code to be order agnostic and ignore unknown sections. No promises.

**Comment by tzanio** [comment]
>I have forked the mfem repo. I may be able to find time to redo the importer code to be order agnostic and ignore unknown sections. No promises.

Thanks @dbgarlisch, we happy to help if you decide to do this.

> My motivation is to add a `conditions` section to the file so I can preserve information we have in Pointwise in the MFEM file.
> 
> Something like:
> 
> ```
> conditions
> [element | boundary] <element attribute> <condition type> <user id> <user name>
> <number of key-value pairs>
> <key>=<value>
>          ...
> <key>=<value>
> ```
> 
> There would be an [element | boundary] row for each unique `<element attribute>` referenced in the `elements` or `boundary` sections.

Another option could be to have this section in potentially a separate file, either associated with the mesh one, or maybe more generally independent of it (e.g. the boundary conditions on a box-like domain may be independent of exact meshing of the box).

Somewhat related to this are the `DataCollection` classes, which are generally meant to save the simulation state -- a mesh + associated fields on it. A derived class, e.g. `PointwiseDataCollection` could potentially additionally read/write these boundary attribute files.

**Comment by dbgarlisch** [comment]
Many formats store the boundary and volume element condition data in a separate file. Others like ansys fluent, store this information in the mesh file. I will need to look into the DataCollection class.

No matter the approach, the attribute id is tagged per entity in the mesh file. So, unless I am missing something, that is the level of independence available.

IMHO, making the reader section-order independent and able to handle or ignore proprietary sections would just be an overall plus and lend itself to the general, application specific nature of mfem.

**Comment by tzanio** [comment]
@dbgarlisch, can we help with anything else, or should we close this issue?

**Comment by dbgarlisch** [comment]
I've been busy at work. I am still hoping to take a stab at this soon. Hi ahead and close it. I will get back to you when I have time.
