### ISSUE TITLE
Visual Studio 2019 + CUDA 11.4 produces compilation errors due to internal linkage of lambdas

### ISSUE THREAD

**Issue by antonhudym** [mfem/mfem#2411]
Hello,

I'm trying to build MFEM with VS 2019 and CUDA 11.4 and see a lot of compilation errors mostly saying something like this:
"On Windows, the enclosing parent function ("Values3D") for an extended __device__ lambda cannot have internal or no linkage"

NVidia documentation says the following:
With Visual Studio 2013 and later Visual Studio host compilers, the enclosing function must have external linkage. The restriction is present because this host compiler does not support using the address of non-extern linkage functions as template arguments, which is needed by the CUDA compiler transformations to support extended lambdas.

I also noticed a couple of errors related to "asm" instructions - they are also not allowed in VS2019 due to security concerns.

Could you please fix this issue?

Also, could you provide some information about version of VS + CUDA that are tested together and stable with MFEM?

Thanks.

**Comment by tzanio** [comment]
Hi @antonhudym,

Unfortunately we don't have the means to easily test the VS build of MFEM (most of the developers use Linux) but the code should work, so we will appreciate your help debugging the issue.

Can you attach the full error log and provide more details about your installation?

Thanks,
Tzanio

**Comment by BernardoCovas** [comment]
Hi! I had the same issue. I will leave a CMake config log + the build log up until it fails. This seems to be caused because of a feature related to lambdas in device code which is unavailable in windows. I am unaware of any options to enable this. Would love to have this working! Let me know if I can help further.

CMake log:
[msvc_cmake_log.txt](https://github.com/mfem/mfem/files/7034495/msvc_cmake_log.txt)

Ninja log:
[msvc_ninja_log.txt](https://github.com/mfem/mfem/files/7034494/msvc_ninja_log.txt)

Regards

**Comment by tzanio** [comment]
Thank you @BernardoCovas, this is useful!

**Comment by BernardoCovas** [comment]
@tzanio no problem, I actually missed the cuda version being 11.2, will try the newer 11.4

**Comment by tzanio** [comment]
@camierjs, @YohannDudouit and @v-dobrev -- it looks like we are getting the following error for essentially all our kernels:

```
../fem/bilininteg_mass_pa.cpp(685): error: On Windows, the enclosing parent function ("SmemPAMassApply2D") for an extended __device__ lambda cannot have internal or no linkage
          detected during instantiation of "void mfem::SmemPAMassApply2D(int, const mfem::Array<double> &, const mfem::Array<double> &, const mfem::Vector &, const mfem::Vector &, mfem::Vector &, int, int) [with T_D1D=2, T_Q1D=2, T_NBZ=16]" 
(1183): here

...

../fem/bilininteg_mass_pa.cpp(590): error: On Windows, the enclosing parent function ("PAMassApply2D") for an extended __device__ lambda cannot have internal or no linkage
          detected during instantiation of "void mfem::PAMassApply2D(int, const mfem::Array<double> &, const mfem::Array<double> &, const mfem::Vector &, const mfem::Vector &, mfem::Vector &, int, int) [with T_D1D=0, T_Q1D=0]" 
(1199): here
```

Do you know what this means?

@BernardoCovas, I am not sure about this, but can you maybe try building with `--expt-extended-lambda`, see https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#nvcc-identification-macro.

**Comment by BernardoCovas** [comment]
I tried it... Same issue, nevertheless it seems to already be in all nvcc calls by default (see FLAGS):
```
build CMakeFiles\mfem.dir\general\array.cpp.obj: CUDA_COMPILER__mfem_Release ..\general\array.cpp || cmake_object_order_depends_target_mfem
  DEFINES = -DMFEM_CONFIG_FILE=\"C:/Users/berna/source/mfem/build/config/_config.hpp\"
  DEP_FILE = CMakeFiles\mfem.dir\general\array.cpp.obj.d
  FLAGS = --expt-extended-lambda -Xcompiler="-MD -O2 -Ob2" -DNDEBUG --generate-code=arch=compute_60,code=[compute_60,sm_60] -std=c++17
  OBJECT_DIR = CMakeFiles\mfem.dir
  OBJECT_FILE_DIR = CMakeFiles\mfem.dir\general
  TARGET_COMPILE_PDB = CMakeFiles\mfem.dir\mfem.pdb
  TARGET_PDB = mfem.pdb
```

**Comment by BernardoCovas** [comment]
@tzanio unfortunately CUDA 11.4 did not help

**Comment by BernardoCovas** [comment]
I managed. In Windows, all functions need to drop the static linkage

**Comment by BernardoCovas** [comment]
So as I understand it, this is just a cuda limitation, and the only way to fix it is to remove all `static` keywords from every function in which this error exists (every function containing a lambda `__device__` function. This will enable external linkage and allow it to compile. I tested it in 1 file and that single file compiles OK after removing the `static` keywords from every troubling functions. Is this a possibility?

**Comment by antonhudym** [comment]
@BernardoCovas forgot to answer to this thread. I made this change locally several weeks ago and it helped. Not sure whether MFEM team is good to go with such change.. @tzanio I can create a pull request for review.

**Comment by antonhudym** [comment]
@tzanio , I'm trying to push changes to my branch (to create a pull request with a fix), but looks like I don't have permissions for this. Could you please provide a "write" permissions, so I can push changes? Thank you.

**Comment by tzanio** [comment]
Thank you. Please try now.

**Comment by antonhudym** [comment]
Hi @tzanio ,
I created a pull-request and noticed that some tests failed. I'll take a look tomorrow to fix those issues. Also, please let me know if you think that changes can be added in general.

Regards,
Anton

**Comment by tzanio** [comment]
See https://github.com/mfem/mfem/pull/2504

**Comment by tzanio** [comment]
Hi @antonhudym, when you get a chance, can you please clean-up #2504 and mark it as `ready-for-review`?
