### ISSUE TITLE
Segmentation Fault Error

### ISSUE THREAD

**Issue by jhoy97** [mfem/mfem#2412]
Hi, 

I am doing a mesh for a simple cantilever beam and my quad mesh was working fine but it now returns an error `Segmentation fault (core dumped)`.  The example works for other meshes of the same model (such as the 3D version of the problem shown in the top image below), however I am not sure how this happened.  Both the `.geo` and `.msh` files are attached in the zip folder.
Any help would be greatly appreciated, thanks.

[drive-download-20210719T190120Z-001.zip](https://github.com/mfem/mfem/files/6843262/drive-download-20210719T190120Z-001.zip)
![hex6](https://user-images.githubusercontent.com/78260282/126212826-c6dcbb9f-16a7-4c06-b004-2cbd279405fc.jpg)

![quad1 msh](https://user-images.githubusercontent.com/78260282/126212777-ae384eb5-ef07-41eb-b8e2-596a3289fbab.jpg)

**Comment by wcdawn** [comment]
In the mesh you provided, there are no quads, only two lines. This seems to be a problem with your Gmsh input. I've never seen `Transfinite Curve` before.  Using your same basic file, here is what I wrote that works.

```
// Gmsh project created on Tue Oct 27 21:01:25 2020
SetFactory("OpenCASCADE");
Mesh.MshFileVersion = 2.2;
//+
h1=1/8;
L=5;
top=(L/h1)+1;
sides=(top/5)+1;
Mesh.CharacteristicLengthMin = h1;
Mesh.CharacteristicLengthMax = h1;

Point(1) = {0, 0, 0, h1};
Point(2) = {5, 0, 0, h1};
Point(3) = {10, 0, 0, h1};
Point(4) = {0, 1, 0, h1};
Point(5) = {5, 1, 0, h1};
Point(6) = {10, 1, 0, h1};
//+
Line(1) = {1, 2};
Line(2) = {2, 5};
Line(3) = {5, 4};
Line(4) = {4, 1};
Line(5) = {5, 6};
Line(6) = {6, 3};
Line(7) = {3, 2};
//+
Curve Loop(1) = {3,4,1,2};
Curve Loop(2) = {5,6,7,2};
Plane Surface(1) = {1};
Plane Surface(2) = {2};

Physical Surface(1) = {1}; // Left
Physical Surface(2) = {2}; // Right
```

I didn't label the `Physical Curve` since I couldn't tell what you were doing there but presumably you'll need those for boundary conditions.

**Comment by jhoy97** [comment]
Thank you for your response, I have a tri/unstructured mesh version of the problem.  The transfinite command allows for a quad mesh to be discretized, I used the same method on a 3D hex version of the problem as shown above.  In the statistics window in Gmsh, the mesh does have quadrangles although when testing it out in MFEM it can't read the mesh.

![stats](https://user-images.githubusercontent.com/78260282/126339605-7aedcaf6-b301-439d-94d3-b738815005dd.jpg)

**Comment by wcdawn** [comment]
I'm not sure what Gmsh is showing you in the GUI but if you look at the .msh file (or a .vtk file written by Gmsh), you'll see that the mesh contains only 1D lines. There is something wrong with the Gmsh output. I suspect it is something with the transfinite stuff.

I use Gmsh as well. For debugging meshes, I find it helpful to write to a `vtk` format and visualize with ParaView before writing the `msh22` format for use with MFEM. There is a way to compile ParaView to read `msh22` files but you must compile the code yourself.

**Comment by wcdawn** [comment]
Here's a Gmsh file that works with the Transfinite Surfaces. If you take a look at the Gmsh [tutorial](https://gmsh.info/doc/texinfo/gmsh.html#t6), you'll see that Transfinite Surface takes the corner points as input, not lines like a typical Plane Surface.

```
// Gmsh project created on Tue Oct 27 21:01:25 2020
SetFactory("OpenCASCADE");
Mesh.MshFileVersion = 2.2;
//+
h1=1/8;
L=5;
top=(L/h1)+1;
sides=(top/5)+1;
Mesh.CharacteristicLengthMin = h1;
Mesh.CharacteristicLengthMax = h1;

Point(1) = {0, 0, 0, h1};
Point(2) = {5, 0, 0, h1};
Point(3) = {10, 0, 0, h1};
Point(4) = {0, 1, 0, h1};
Point(5) = {5, 1, 0, h1};
Point(6) = {10, 1, 0, h1};
//+
Line(1) = {1, 2};
Line(2) = {2, 5};
Line(3) = {5, 4};
Line(4) = {4, 1};
Line(5) = {5, 6};
Line(6) = {6, 3};
Line(7) = {3, 2};
//+
Curve Loop(1) = {4, 1, 2, 3};
Curve Loop(2) = {5, 6, 7, 2};
Plane Surface(1) = {1};
Plane Surface(2) = {2};

node_per_top_bot_edge = 11;
node_per_side_edge = 6;

Transfinite Curve{1} = node_per_top_bot_edge;
Transfinite Curve{2} = node_per_side_edge;
Transfinite Curve{3} = node_per_top_bot_edge;
Transfinite Curve{4} = node_per_side_edge;
Transfinite Curve{5} = node_per_top_bot_edge;
Transfinite Curve{6} = node_per_side_edge;
Transfinite Curve{7} = node_per_top_bot_edge;
Transfinite Surface{1} = {1, 2, 5, 4};
Transfinite Surface{2} = {2, 3, 6, 5};

Physical Surface(1) = {1};
Physical Surface(2) = {2};

Recombine Surface {:};
```

**Comment by jhoy97** [comment]
Excellent, thank you for your help!
