### ISSUE TITLE
How to get data from neighboring element on another processor?

### ISSUE THREAD

**Issue by aaronskinner** [mfem/mfem#2417]
I'm currently using `mesh->GetFaceElements(faces[f], &elem1, &elem2);` to get the element indices on either side of a given face, but `elem2` is -1 on both processor and physical boundaries.  Is there a way to get the face neighbor index if the neighbor is on another processor?  Also, if I have that index, can I access the dofs of that face-neighbor element even if it's owned by another proc?

**Comment by vladotomov** [comment]
Yes, it can be done. For example see the use of `ParFiniteElementSpace::GetFaceNbrElementVDofs` in `ParBilinearForm::AssembleSharedFaces`. Let us know if you have further questions.
