### ISSUE TITLE
Partial assembly support for ParBilinearForm::TrueAddMult

### ISSUE THREAD

**Issue by artv3** [mfem/mfem#2421]
I am interested in the global action of a ParBilinearForm via partial assembly; however there seems to be missing support for certain integrators:

 --> the case of interior face integrators is not implemented
 ... in function: void mfem::ParBilinearForm::TrueAddMult(const mfem::Vector &, mfem::Vector &, const double) const

**Comment by v-dobrev** [comment]
Actually, this looks like incorrect placement of the `MFEM_VERIFY` here: https://github.com/mfem/mfem/blob/c528f79c9fc2f92612660ccf0f98cd1fe95879dc/fem/pbilinearform.cpp#L320-L322

This should be moved inside the `else` case when `ext == NULL`. Not all `BilinearFormExtension` sub-classes support face integrators but the PA one does. The check should be also performed inside the `Mult` methods of the other `BilinearFormExtension` sub-classes.

**Comment by tzanio** [comment]
Resolved by #2447.
