### ISSUE TITLE
Bad Termination Of One Of Your Application Processes Error 

### ISSUE THREAD

**Issue by jhoy97** [mfem/mfem#2426]
Hi, I am getting this error message when running the parallel version of `example 2` for a bracket.  The model works when running the serial version of the problem (glvis window on left) but I am unsure why the parallel is not, was wondering if it was MFEM related or mesh/geometry related.  Any help would be greatly appreciated. 

[bracket.zip](https://github.com/mfem/mfem/files/6869361/bracket.zip)

![wrenche](https://user-images.githubusercontent.com/78260282/126794654-f3245ed6-9403-4923-becc-cc917a4d8b72.jpg)

**Comment by tzanio** [comment]
Can you post also your modified version of Example 2?
