### ISSUE TITLE
VectorArrayCoefficient and MatrixArrayCoefficient

### ISSUE THREAD

**Issue by stefanozampini** [mfem/mfem#243]
These classes take ownership of the Coefficient used to evaluate the i-th direction or the (i,j) matrix entry.
Suppose you want to use zero for some direction or matrix entry. As it is right now, you are forced to create fake constant coefficients as CostantCoefficient(0.). I would rather prefer to have the eval methods testing for NULL and set the corresponding entry in the Vector or the DenseMatrix to zero.
This can be handle with quite easily, except for the Coefficient& GetCoefficient()  method that returns a reference instead of a pointer. Is there any specific/historical reason why one wants a reference instead of a pointer?

A note aside: since we assume that these classes take ownership of the single Coefficients used, it should be reasonable to add a call to delete the previous Coefficient used in the SetCoeff calls (which are public). Thoughts? If we agree on the modifications, I would be happy to provide a PR.

**Comment by v-dobrev** [comment]
I think treating NULL pointers as the zero function is quite natural. Also, allowing multiple calls to `SetCoeff()` by deleting the previous pointer is a good addition as well. Regarding the dereferencing of potential NULL pointers by `GetCoeff()` - I prefer to keep the interface the same, i.e. the method should still return `Coefficient &`. To deal with the NULL case, we can simply add a new method that checks if the pointer is NULL, e.g. `IsCoeffSet()`. Another option is to add a method that returns a `Coefficient *`, e.g. `GetCoeffPtr()` or something like that.

How does this sound to you?

**Comment by stefanozampini** [comment]
See PR #260
