### ISSUE TITLE
Higher Order Convergence

### ISSUE THREAD

**Issue by jhoy97** [mfem/mfem#2431]
Hi, 

I am testing a wrench using MFEM to calculate its maximum deflection, however, when increasing the order (order 3 in this case), the solution is very small in comparison to the converging result.   The image below shows the problem being ran in increasing order approximation from left to right (mesh density shown on left for reference), as you can see the first two results are increasing towards the analytical solution. The third however, is significantly less, is this a problem with my mesh/boundary conditions?  This occurs when attempting third order approximation on very coarse meshes, hence raising the issue. Any help/info would be great, thanks!

[Wrench-20210727T212944Z-001.zip](https://github.com/mfem/mfem/files/6888856/Wrench-20210727T212944Z-001.zip)

![order](https://user-images.githubusercontent.com/78260282/127229461-dd6c8d13-24b4-4c5a-9aaa-1c8238deaa53.jpg)

**Comment by mlstowell** [comment]
Hi, @jhoy97,

Can you please post your mesh. I'm having trouble working with the tet.geo file.

Thanks,
Mark

**Comment by jhoy97** [comment]
Hi @mlstowell,

The mesh file is in this .zip folder, thanks for your quick response!
John

[drive-download-20210727T220739Z-001.zip](https://github.com/mfem/mfem/files/6888989/drive-download-20210727T220739Z-001.zip)

**Comment by mlstowell** [comment]
I cannot seem to reproduce your results. These show my results from your example using orders 1-4. Incidentally the mesh does not appear to match the one in your images so I'm sure we're doing something different.
<img width="490" alt="Wrench_o1" src="https://user-images.githubusercontent.com/6109571/127234770-494dbd4d-a58f-4290-9ba1-706a5d0b9127.png">
<img width="492" alt="Wrench_o2" src="https://user-images.githubusercontent.com/6109571/127234773-fb682e13-1cfb-4219-bf35-d541fc72d7ad.png">
<img width="491" alt="Wrench_o3" src="https://user-images.githubusercontent.com/6109571/127234782-e58f2a11-40d0-4f37-b0f5-ed361223ee2c.png">
<img width="492" alt="Wrench_o4" src="https://user-images.githubusercontent.com/6109571/127234788-752561a7-d3a3-4623-8f0d-c58c9df618e1.png">

**Comment by psocratis** [comment]
@jhoy97,  

It seems to be a solver convergence issue. When using the direct solver I get the same results as @mlstowell. When switching to the PCG solver with GS preconditioner the solver does not reach the required tolerance in 500 iterations. 
You might need to increase the maximum number of iterations or use a different solver. 

Socratis

**Comment by psocratis** [comment]
Result after 1038 PCG iterations:
![image](https://user-images.githubusercontent.com/14336752/127241624-88a672cf-169c-4d2a-8efb-d61ff877f683.png)

Result after 500 iterations

![image](https://user-images.githubusercontent.com/14336752/127241699-fb490dfd-5de6-4b4a-88b2-35ea956708f4.png)

**Comment by jhoy97** [comment]
Apologies guys, the mesh used was the one attached in this post but thank you for your responses.  I am unsure how to change/use different solvers - does this mean changing the `.cpp` file?   I am relatively new to the software, thanks again for your help!

[drive-download-20210728T065904Z-001.zip](https://github.com/mfem/mfem/files/6890974/drive-download-20210728T065904Z-001.zip)

**Comment by psocratis** [comment]
> Apologies guys, the mesh used was the one attached in this post but thank you for your responses. I am unsure how to change/use different solvers - does this mean changing the `.cpp` file? I am relatively new to the software, thanks again for your help!

Hi @jhoy97, 

You have a few options. One is to just increase the maximum number of CG iterations: you can do that by modifying the 6th argument in the PCG call (line 206). A second option would be to link MFEM with SUITESPARSE and use the UMFPackSolver instead (lines 209-212). Finally, and probably the best option, if you want to solve larger problems, is to use a parallel (MPI) version of MFEM. You would need to link MFEM with hypre and modify your code like ex2p. With this option, you have access to better solvers/preconditioners through hypre.  

Hope this helps. 

Best, 

Socratis
