### ISSUE TITLE
Hypre update will affect MFEM

### ISSUE THREAD

**Issue by victorapm** [mfem/mfem#2434]
Hello MFEM developers,

I recently merged a PR (https://github.com/hypre-space/hypre/pull/392) into hypre's master that will affect MFEM. Among other changes, it  removes functions such as `hypre_ParCSRMatrixSet[Row,Col]StartsOwner` and `hypre_ParVectorSetPartitioningOwner` that control ownership of certain internal pointers in hypre. Before, those variables were stored on the heap memory, while now they are stored on the stack. That's why those functions aren't needed anymore. 

I wanted to offer help for updating the hypre interface in MFEM in case you need :)

Thanks!
Victor

**Comment by tzanio** [comment]
This seems like a potentially significant change and we will have to take a careful look.

We will do that after the mfem-4.3 release though, so give us a week.

**Comment by tzanio** [comment]
Discussion continued in #2452

See also #2449, #2458 and #2459.
