### ISSUE TITLE
Reading in a mesh file in parallel

### ISSUE THREAD

**Issue by kmittal2** [mfem/mfem#244]
Is there a way to read in a parallel mesh file on any given number of processors?

I am refining a large mesh, so I start with a single mesh in serial and refine it once on 24 processors. This gives me 24 dummy.000* files. Now I want to read this parallel mesh into 48 processors and refine it further. Is it possible to do that? I am unable to do all the refinements in 1 go because I run out of memory.

**Comment by v-dobrev** [comment]
At this mfem does not support reading a parallel on a different number of processors - you can only read a parallel mesh on the same number of processor as the number used when saving the mesh.

Here's what you can do in your code, without the need to write the mesh to a file  (see e.g. `examples/ex16p.cpp`):
* Start with your serial mesh - every MPI rank reads from the same file - using the constructor of class `Mesh`.
* Optionally, refine (on each MPI rank) the mesh in serial, using `Mesh::UniformRefinement()`, until you get the number of elements to be somewhere in the range of >10-100 times the number of processors, e.g. if you want to use 1,000 processors, refine until you have ~ 10,000-100,000 (or more) elements in the serial mesh. Each MPI rank will have the same mesh but this should not be a problem unless you are using on the order of >10^5-10^6 processors and the available memory per MPI rank is very limited.
* Transition from the `Mesh` object to a `ParMesh` object; delete the Mesh object.
* Refine the `ParMesh` in parallel, as many times as you need by calling `ParMesh::UniformRefinement()`. Here, you are limited only by the memory available to each MPI rank.

How big is you initial mesh (in terms of number of elements)? And how big is the mesh you want to create?

**Comment by kmittal2** [comment]
Thanks Veselin.. I found this to be helpful. I also realized that my original mesh was a nurbs mesh so refining that was not as memory consuming, and I was able to do that on my machine (went from 448 elements to 14 million elements).
