### ISSUE TITLE
HYPRE functions deleted in latest push

### ISSUE THREAD

**Issue by wcdawn** [mfem/mfem#2449]
In the latest HYPRE commit [here](https://github.com/hypre-space/hypre/commit/ffe4f7384bc9cb95195c04ae0aec1f3609237147), `hypre_ParCSRMatrixOwnsRowStarts()` and `hypre_ParCSRMatrixOwnsColStarts()` have been removed from the library.

The first time these are called in MFEM is in `linalg/complex_operator.cpp` line [792 and 793](https://github.com/mfem/mfem/blob/c528f79c9fc2f92612660ccf0f98cd1fe95879dc/linalg/complex_operator.cpp#L792).

More generally, does MFEM intend to support the HYPRE `master` branch? Or only minor releases? I'd like to use the newest version possible to take advantage of the newest GPU features.

**Comment by tzanio** [comment]
This was reported in https://github.com/mfem/mfem/issues/2434.

We will try to address it next week.

**Comment by wcdawn** [comment]
Sorry for the duplicate!
Thanks!
