### ISSUE TITLE
HYPRE+GPU Runtime Error

### ISSUE THREAD

**Issue by wcdawn** [mfem/mfem#2451]
I have compiled MFEM minimally using METIS, HYPRE (with CUDA), and CUDA.
When I run `mpirun -np 1 ./ex1p -d cuda`, I get the following error.
```
CUDA error: (cudaGetLastError()) failed with error:
 --> invalid device function
 ... in function: void mfem::CuWrap1D(int, DBODY&&) [with int BLCK = 256; DBODY = __nv_dl_wrapper_t<__nv_dl_tag<mfem::Vector& (mfem::Vector::*)(double), &mfem::Vector::operator=, 1>, double*, double>&]
 ... in file: linalg/../general/forall.hpp:309
```

I can provide the scripts I used to configure each of the libraries if that would be helpful.
I suspect this may be because I'm using CUDA 11.

**Comment by wcdawn** [comment]
Running on Summit with CUDA 10, I get a different error.
```
Options used:
   --mesh star.mesh
   --order 1
   --no-static-condensation
   --no-partial-assembly
   --device cuda
   --visualization
Device configuration: cuda,cpu
Memory configuration: host-std,cuda
Number of finite element unknowns: 82561
[e34n17:151048] *** Process received signal ***
[e34n17:151048] Signal: Segmentation fault (11)
[e34n17:151048] Signal code: Address not mapped (1)
[e34n17:151048] Failing at address: 0x30
[e34n17:151048] [ 0] [0x2000000504d8]
[e34n17:151048] [ 1] ./ex1p[0x10a1dca4]
[e34n17:151048] [ 2] ./ex1p[0x10a1e0ac]
[e34n17:151048] [ 3] ./ex1p[0x10abf3f0]
[e34n17:151048] [ 4] ./ex1p[0x10ce2d88]
[e34n17:151048] [ 5] ./ex1p[0x10b0ca10]
[e34n17:151048] [ 6] ./ex1p[0x10b04574]
[e34n17:151048] [ 7] ./ex1p[0x10a70c38]
[e34n17:151048] [ 8] ./ex1p[0x10a449b8]
[e34n17:151048] [ 9] ./ex1p[0x100dbb90]
[e34n17:151048] [10] ./ex1p[0x100e498c]
[e34n17:151048] [11] ./ex1p[0x100f3cc0]
[e34n17:151048] [12] ./ex1p[0x1001d234]
[e34n17:151048] [13] /lib64/libc.so.6(+0x25200)[0x20000f495200]
[e34n17:151048] [14] /lib64/libc.so.6(__libc_start_main+0xc4)[0x20000f4953f4]
[e34n17:151048] *** End of error message ***
```

It looks really weird that the address is `0x30`. Could an integer be passed somewhere where a pointer is expected?

**Comment by tzanio** [comment]
Thanks for reporting this, @wcdawn.

Can you provide more details on your environment (compiler, CUDA version, etc.) and the exact commands with which you build both hypre and MFEM?

Tzanio

**Comment by wcdawn** [comment]
I'll provide the Summit example since that uses CUDA 10. I wouldn't be too surprised if there were unsupported parts of CUDA 11 yet.

I installed HYPRE v 2.22.0 from a tarball.
Here's my HYPRE configuration script.
```
CUDA_HOME=${OLCF_CUDA_ROOT} \
  HYPRE_CUDA_SM=70 \
  CC=mpixlc \
  CXX=mpixlC \
  ./configure \
  --disable-fortran \
  --with-cuda \
  --enable-unified-memory \
  --enable-device-memory-pool \
  --enable-cusparse \
  --enable-cublas \
  --enable-curand
```

I installed MFEM from the `master` branch (SHA c528f79c9fc2f92612660ccf0f98cd1fe95879dc). 
Here's my MFEM configuration script.
```
make config \
  MFEM_USE_OPENMP=YES MFEM_USE_MPI=YES CC=mpixlc CXX=mpixlC \
  MPICC=mpixlc MPICXX=mpixlC \
  HYPRE_DIR=${DIR}/hypre-2.22.0/src/hypre \
  METIS_DIR=${DIR}/metis-5.1.0 MFEM_USE_METIS_5=YES \
  MFEM_USE_CUDA=YES CUDA_CXX=nvcc \
  CUDA_FLAGS='-x=cu -arch=sm_70 --expt-extended-lambda --compiler-options -O3' \
  CUDA_LIB='-lcusparse -lcurand -lcublas'
```

**Comment by wcdawn** [comment]
I tried compiling with `MFEM_DEBUG=YES` but I didn't get any line numbers or other information.

**Comment by v-dobrev** [comment]
Can you try running this in a debugger (with `MFEM_DEBUG=YES`) and post the stack trace after the segfault?

Also, what is the exact CUDA version you use? For example, what does `nvcc --version` show?

**Comment by wcdawn** [comment]
CUDA Version.
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:52_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
```

GDB ouptput.
[gdb.txt](https://github.com/mfem/mfem/files/6947866/gdb.txt)

Looks like it's actually somewhere inside of HYPRE but I'm not totally sure. I can try rebuilding HYPRE with debug options too if that would help.

**Comment by v-dobrev** [comment]
It looks like this maybe due to the use of `--enable-device-memory-pool`. Can you try building hypre without that option? Also, there is no need to use `--enable-unified-memory`, I'd recommend removing that as well.

**Comment by wcdawn** [comment]
Removing `--enable-device-memory-pool` did fix this problem. I'm not sure how to fix this in MFEM but if MFEM is only compatible with certain HYPRE options, it would be nice to document these.

Using CUDA 11.4 produces a different runtime error but I can document that in a different ticket if that would be useful.

**Comment by v-dobrev** [comment]
I'm not sure if this an issue in MFEM or in HYPRE.

@liruipeng, can you take a quick look at the `gdb.txt` output posted above: https://github.com/mfem/mfem/issues/2451#issuecomment-894503003 -- could this be an issue in HYPRE with the option `--enable-device-memory-pool`?

**Comment by liruipeng** [comment]
Can you please try this branch https://github.com/hypre-space/hypre/tree/cub-fix, and let me know if works? Thanks!

**Comment by wcdawn** [comment]
@liruipeng I cannot test this branch. MFEM does not yet support the removal of the "owner" functions from HYPRE. I tried using the branch from #2452 but this does not seem to fix the problem.

**Comment by tzanio** [comment]
@wcdawn, can you try https://github.com/mfem/mfem/pull/2476?

**Comment by tzanio** [comment]
I believe this is now resolve with the merge of #2476. Please reopen if there are still issues.

**Comment by wcdawn** [comment]
Sorry for the delay, but this is still broken. As it's been so long, Summit has undergone an OS upgrade so the new `nvcc --version` is:
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Wed_Jul_22_19:08:50_PDT_2020
Cuda compilation tools, release 11.0, V11.0.221
Build cuda_11.0_bu.TC445_37.28845127_0
```

The same error still happens in MFEM. @v-dobrev suggested that it was an error with HYPRE. @liruipeng suggested using a branch of HYPRE that no longer exists.

I tried using the `master` branch of HYPRE. I was able to compile the MFEM library but compiling `ex1p` resulted in the following:
```
nvcc  -O3 -std=c++11 -x=cu -arch=sm_70 --expt-extended-lambda --compiler-options -O3 -ccbin mpixlC -I.. -I/ccs/proj/csc404/wcdawn/container/hypre/src/hypre/include -I/ccs/proj/csc404/wcdawn/container/metis-5.1.0/include -Xcompiler=-fopenmp ex1p.cpp -o ex1p -L.. -lmfem -L/ccs/proj/csc404/wcdawn/container/hypre/src/hypre/lib -lHYPRE -lcusparse -lcurand -L/ccs/proj/csc404/wcdawn/container/metis-5.1.0/lib -lmetis  -lcusparse -lcurand -lcublas -lrt
/ccs/proj/csc404/wcdawn/container/hypre/src/hypre/lib/libHYPRE.a(par_relax_device.obj): In function `hypre_BoomerAMGRelaxHybridGaussSeidelDevice':
tmpxft_003cf231_00000000-6_par_relax_device.cudafe1.cpp:(.text+0x414): undefined reference to `hypre_CSRMatrixTriLowerUpperSolveDevice'
tmpxft_003cf231_00000000-6_par_relax_device.cudafe1.cpp:(.text+0x4d0): undefined reference to `hypre_CSRMatrixTriLowerUpperSolveDevice'
tmpxft_003cf231_00000000-6_par_relax_device.cudafe1.cpp:(.text+0x51c): undefined reference to `hypre_CSRMatrixTriLowerUpperSolveDevice'
collect2: error: ld returned 1 exit status
make: *** [makefile:78: ex1p] Error 1
```

I'm using the same configuration as earlier but I'll repeat.
HYPRE:
```
CUDA_HOME=${OLCF_CUDA_ROOT} \
  HYPRE_CUDA_SM=70 \
  CC=mpixlc \
  CXX=mpixlC \
  ./configure \
  --disable-fortran \
  --with-cuda \
  --enable-unified-memory \
  --enable-device-memory-pool \
  --enable-cusparse \
  --enable-cublas \
  --enable-curand
```

MFEM:
```
make config \
  MFEM_USE_OPENMP=YES MFEM_USE_MPI=YES CC=mpixlc CXX=mpixlC \
  MPICC=mpixlc MPICXX=mpixlC \
  HYPRE_DIR=${HYPRE_DIR} \
  METIS_DIR=${METIS_DIR} MFEM_USE_METIS_5=YES \
  MFEM_USE_CUDA=YES CUDA_CXX=nvcc \
  CUDA_FLAGS='-x=cu -arch=sm_70 --expt-extended-lambda --compiler-options -O3' \
  CUDA_LIB='-lcusparse -lcurand -lcublas'
```

**Comment by tzanio** [comment]
Thanks for reporting this, I really thought it was resolved 😞 

Just to confirm -- is this with the `master` branches of both hypre and MFEM? If that's the case, can you try `mfem:master` with `hypre-2.22.1`?

**Comment by wcdawn** [comment]
@tzanio Thanks for the quick reply!

Using `hypre-2.22.1` with `mfem:master` seems to work with `ex1p`.
It does look like there is a new HYPRE API break in the latest commit [here](https://github.com/hypre-space/hypre/commit/e53b5a0270e1d493a050fe4c37f6922ac72dda19) that affects triangular solvers but this should probably be in a different issue.
