### ISSUE TITLE
Visit does not recognize files with different number of digits

### ISSUE THREAD

**Issue by vikramsg** [mfem/mfem#246]
I changed the number of digits in file name extension for Visit in example 9. I need this since I will be doing more time steps than 6 digits allow. 

```
dc->SetPadDigits(8);
```

Unfortunately it seems that VisIt fails to read anything that is not 6 digits and gives me an error

```
Mesh:  ()
viewer: There was an error opening Failed to open MFEM mesh: mesh name: main domain: 0 mesh path: mfem/examples/Example9_00000000/mesh.%08d. It may be an invalid file.
```

I am using version 2.12.0 of Visit.

**Comment by v-dobrev** [comment]
@cyrush, do you have any suggestions?

I the `.mfem_root` file, the mesh path is set to `"Example9-Parallel_00000000/mesh.%08d"` when the number of digits is set to 8. With the default 6 digits, the path is set to `"Example9-Parallel_000000/mesh.%06d"`. Is this the right format?

I also tried with the newest VisIt version, 2.12.3, and I get the same error message.

**Comment by cyrush** [comment]
Yes -- it currently only supports %06d and %05d as the cycle pattern,  here is a link to the code:

http://visit.ilight.com/svn/visit/trunk/src/databases/MFEM/JSONRoot.C

(search for JSONRootPath::Expand)

If desired, we can support more general cases in a future version of VisIt.

**Comment by v-dobrev** [comment]
Actually, the patterns `%05d` and `%06d` are applied to the processor id, not the cycle - the cycle is just in the name of the sub-directory without any pattern in it. So, a simple solution will be to support in class `DataCollection` a separate number of digits for the cycle and the processor id. This should work fine with the current version of VisIt too.

I'll make a small PR for this.

**Comment by cyrush** [comment]
sorry for the confusion, yes, thats not the `cycle` that is the pattern for the processor id (or domain id)

We read the `cycle` directly from the mfem root file.

**Comment by vikramsg** [comment]
I can see that if the cycle number is more than 6 digits then the file is still written with the greater number of digits. So it seem that it is not really a problem.
