### ISSUE TITLE
Omitting attribute values for elements/boundaries?

### ISSUE THREAD

**Issue by xjrc** [mfem/mfem#2463]
Is it possible to omit attribute values for the elements/boundaries specified in MFEM's NURBS mesh format (e.g. [ball-nurbs.mesh](https://github.com/mfem/mfem/blob/master/data/ball-nurbs.mesh))? Given the structured nature of the format, my guess is that this isn't possible; however, perhaps a special value (e.g. 0) indicates that the attribute is unspecified?

Thanks in advance for any guidance that you can provide!

**Comment by v-dobrev** [comment]
Is there a problem if you just use attribute 1 everywhere?

**Comment by xjrc** [comment]
> Is there a problem if you just use attribute 1 everywhere?

Based on a recent discussion with @rieben1, this strategy sounds fine for elements, but is generally undesirable for boundaries. We can use an alternative value with analogous (in)significance (e.g. 999), but something indicating "undefined" would be preferred (if it exists).

**Comment by v-dobrev** [comment]
All `mfem::Mesh`/`mfem::ParMesh` objects have to have some value (> 0) for all their element and boundary element attributes. MFEM does not have a special attribute value that means "undefined".

**Comment by xjrc** [comment]
Understood, @v-dobrev; thanks for clarifying!
