### ISSUE TITLE
Convergence rates of the global ZZ error estimate appear to depend on the parity of the polynomial order

### ISSUE THREAD

**Issue by brendankeith** [mfem/mfem#2464]
I am using `total_error` computed with a  `ZZErrorEstimator` object as stopping criteria in an adaptive mesh refinement project. Although the refinement patterns the estimator produces appear reasonable, I noticed the following suspicious behaviour: When the polynomial order is _even_, the convergence rate is one degree higher than the true H^1_0 error. When the polynomial order is _odd_ the convergence rate of the error estimate agrees with the convergence rate of the true H^1_0 error.

I have verified this behaviour with two independent implementations of the same L-shaped domain benchmark problem, which has its solution in H^{3/2}. Attached are a number of convergence plots demonstrating the behaviour.

[ConvergencePlotOrder1.pdf](https://github.com/mfem/mfem/files/6958017/ConvergencePlotOrder1.pdf)
[ConvergencePlotOrder2.pdf](https://github.com/mfem/mfem/files/6958018/ConvergencePlotOrder2.pdf)
[ConvergencePlotOrder3.pdf](https://github.com/mfem/mfem/files/6958019/ConvergencePlotOrder3.pdf)
[ConvergencePlotOrder4.pdf](https://github.com/mfem/mfem/files/6958020/ConvergencePlotOrder4.pdf)

**Comment by brendankeith** [comment]
The issue appears with uniform refinements as well. Here are the convergence rates when the exact solution is u(x,y) = sin(πx) sin(πy).
[ConvergencePlotOrder1.pdf](https://github.com/mfem/mfem/files/6958078/ConvergencePlotOrder1.pdf)
[ConvergencePlotOrder2.pdf](https://github.com/mfem/mfem/files/6958080/ConvergencePlotOrder2.pdf)
[ConvergencePlotOrder3.pdf](https://github.com/mfem/mfem/files/6958081/ConvergencePlotOrder3.pdf)
[ConvergencePlotOrder4.pdf](https://github.com/mfem/mfem/files/6958082/ConvergencePlotOrder4.pdf)

**Comment by v-dobrev** [comment]
For completeness, was this with a quad mesh or triangles? If using triangles, was this conforming or nonconforming refinement? Also, what was the flux FE space? Was it vector H1? It will be interesting to see what the behavior looks like with an RT flux space.

From theoretical point of view, I'm not sure what theory exists for this setup and what it says. In any case, this is an interesting study.

**Comment by brendankeith** [comment]
Hi @v-dobrev, it was with quads. The flux FE space is vectorial H^1 of space order of the potential field (this is as in the original papers).  I tried with RT but I believe that is only supported in the parallel implementation. Part 2 of the original pair of papers considers order p=2 conforming quads and shows asymptotic exactness.

I am willing to try to add RT support to the ZZ routine, but I don't understand the code well enough yet. I'm also not sure if that is the issue here, as the results in the original paper already seem to conflict with what I am seeing.

**Comment by brendankeith** [comment]
If anyone would like to experiment, I wrote a script to reproduce the issue here: https://github.com/mfem/mfem/tree/zz_test/ZZ_test

**Comment by v-dobrev** [comment]
It is possible that the implementation in MFEM does not exactly match the algorithm from the paper(s). Can you post links to the papers you mentioned?

**Comment by brendankeith** [comment]
https://doi.org/10.1002/nme.1620330702
https://doi.org/10.1002/nme.1620330703

**Comment by tzanio** [comment]
This is now being discussed internally.
