### ISSUE TITLE
Hypre ownership errors

### ISSUE THREAD

**Issue by goinea** [mfem/mfem#2465]
Hello @tzanio, I have checked out the odl branch in mfem and am still having the hypre ownership based errors. What branch should I git checkout in order to have the resolved issue?

_Originally posted by @goinea in https://github.com/mfem/mfem/issues/2452#issuecomment-896082861_

**Comment by tzanio** [comment]
See #2434 and #2452

**Comment by tzanio** [comment]
Please switch to https://github.com/mfem/mfem/pull/2476 and post any further comment there.
