### ISSUE TITLE
CUDA compatibitiy

### ISSUE THREAD

**Issue by justAPhDStudent** [mfem/mfem#2473]
Hello,
I'm on Ubuntu 20 (CUDA 11) trying to install mfem with CUDA. My nividia driver capability is 5.2 (-arch=sm_52). It seems there is problem for compilation for these architectures. 
__________________________________________________________________________________________________
fem/../mesh/../fem/../linalg/../general/backends.hpp(66): error: no instance of overloaded function "atomicAdd" matches the argument list
            argument types are: (double *, const double)
          detected during instantiation of "T AtomicAdd(T &, T) [with T=double]" 
fem/restriction.cpp(1395): here
__________________________________________________________________________________________________

It seems the atomicAdd() is supported only from sm_60 for CUDA 11.0 onwards. (not sure, only seems as from a webpage on internet)
Does this mean I need a CUDA capability of 6.0 for using mfem with CUDA 11. The Ubuntu 20 doesn't allow easy installation of earlier version of CUDA Toolkit.
Thanks in advance

**Comment by camierjs** [comment]
To make it working on older devices, you can follow this [advice](https://stackoverflow.com/questions/37566987/cuda-atomicadd-for-doubles-definition-error) and drop the following code in `general/backends.hpp`:
```
__device__ double atomicAdd(double* address, double val)
{
    unsigned long long int* address_as_ull = (unsigned long long int*)address;
    unsigned long long int old = *address_as_ull, assumed;
    do {
        assumed = old;
        old = atomicCAS(address_as_ull, assumed,
                __double_as_longlong(val + __longlong_as_double(assumed)));
    } while (assumed != old);
    return __longlong_as_double(old);
}
```

I'll follow up and create a PR that will fix it - thank you for reporting!

**Comment by camierjs** [comment]
#2475 now addresses this issue.
