### ISSUE TITLE
NCMesh visualization crash

### ISSUE THREAD

**Issue by stefanozampini** [mfem/mfem#249]
I'm getting the error below when loading a mesh with a vertex_parents section.
The mesh [error-ncmesh.txt](https://github.com/mfem/mfem/files/1185537/error-ncmesh.txt) is generated from a parallel run using p4est refinement in a PETSc code.
The total number of vertices in the mesh is 20: 2 of them (vertex 18 and 19, counting from 0) are hanging nodes and lie on an edge which is shared by different processes. There's also another hanging node (vertex no 17) which instead is considered part of the mesh, since it's not an hanging node of the process.
The issue arises since the check is performed on the active vertices.
It seems to me that the mesh I'm passing in is a valid NCMesh.

Assertion failed: (index >= 0 && index < size) is false: Out of bounds access: 18, size = 18
 ... in function: void mfem::BlockArray<T>::CheckIndex(int) const [with T = mfem::NCMesh::Node]
 ... at line 477 of file: /home/szampini/src/mfem/mesh/../general/array.hpp

Backtrace:
0) [0x48c95d]: mfem::mfem_error(char const*)
1) [0x50f0a1]: mfem::BlockArray<mfem::NCMesh::Node>::CheckIndex(int) const
2) [0x50c553]: mfem::BlockArray<mfem::NCMesh::Node>::At(int) const
3) [0x509533]: mfem::HashTable<mfem::NCMesh::Node>::IdExists(int) const
4) [0x5042c2]: mfem::NCMesh::LoadVertexParents(std::istream&)
5) [0x4f0244]: mfem::NCMesh::NCMesh(mfem::Mesh const*, std::istream*)
6) [0x4e01d0]: mfem::Mesh::ReadMFEMMesh(std::istream&, bool, int&)
7) [0x4b4688]: mfem::Mesh::Loader(std::istream&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)
8) [0x4d41ac]: mfem::Mesh::Load(std::istream&, int, int, bool)
9) [0x4b311c]: mfem::Mesh::Mesh(char const*, int, int, bool)
10) [0x431e8e]: ReadSerial()
11) [0x431593]: main
12) [0x7f2170f87400]: __libc_start_main
13) [0x42b569]: _start

Lookup backtrace source lines:
addr2line -C -e glvis_dbg 0x48c95d 0x50f0a1 0x50c553 0x509533 0x5042c2 0x4f0244 0x4e01d0 0x4b4688 0x4d41ac 0x4b311c 0x431e8e 0x431593
addr2line -C -e /lib64/libc.so.6 0x7f2170f87400
addr2line -C -e glvis_dbg 0x42b569

Aborted (core dumped)
[szampini@localhost tutorials]$ addr2line -C -e `which glvis_dbg` 0x48c95d 0x50f0a1 0x50c553 0x509533 0x5042c2 0x4f0244 0x4e01d0 0x4b4688 0x4d41ac 0x4b311c 0x431e8e 0x431593
/home/szampini/src/mfem/general/error.cpp:118
/home/szampini/src/mfem/mesh/../general/array.hpp:476 (discriminator 40)
/home/szampini/src/mfem/mesh/../general/array.hpp:361
/home/szampini/src/mfem/mesh/../general/hash.hpp:109
/home/szampini/src/mfem/mesh/ncmesh.cpp:3148
/home/szampini/src/mfem/mesh/ncmesh.cpp:100
/home/szampini/src/mfem/mesh/mesh_readers.cpp:66
/home/szampini/src/mfem/mesh/mesh.cpp:2586
/home/szampini/src/mfem/mesh/mesh.hpp:564 (discriminator 2)
/home/szampini/src/mfem/mesh/mesh.cpp:2393
/home/szampini/src/glvis/glvis.cpp:1747
/home/szampini/src/glvis/glvis.cpp:1573

**Comment by jakubcerveny** [comment]
Hi Stefano,

The NCMesh loading code contains a lot of checks, for example, in
LoadVertexParents it is assumed that all vertices being assigned parents
have already been mentioned in the 'elements' section. Whether this is
strictly necessary is a question. A mesh file produced by the NCMesh class
always meets this.

I guess it depends on what you are trying to achieve. Perhaps the checks
could be relaxed. A new, unused vertex maybe could be created in
LoadVertexParents. Normally the class doesn't create unused vertices though.

Jakub

**Comment by v-dobrev** [comment]
Hi Stefano,

Just to clarify: at this point mfem does not have a parallel format for nonconforming meshes - `ParMesh::ParPrint` simply calls `ParMesh::Print` which writes the processor mesh without any data describing the connection with neighbor processors. This is good enough for visualizing the mesh and solutions (GLVis treats the mesh pieces as separate and simply reconstructs a mesh consisting of disconnected pieces) but you cannot load that mesh as a `ParMesh`.

So my question is: are you just trying to visualize parallel nonconforming meshes or do you need to load such meshes as `ParMesh` objects?

If you just want to visualize the mesh, then small modification in the `vertex_parents` section should be sufficient - simply remove the hanging vertices that are not used by local elements:
```ascii
vertex_parents
1
17 3 4
```
The `vertices` section may remain unmodified.

**Comment by tzanio** [comment]
Hi @stefanozampini, as @v-dobrev said there is no currently implmented parallel nonconforming mesh file format, so the file you provided is being read as a serial mesh which doesn't actually have hanging nodes.  Given that, can we close this issue, or do you still have questions?

**Comment by stefanozampini** [comment]
Thanks for your answers. You can close the issue. I already fixed the PETSc code to not dump the vertex-parent section if the mesh is distributed
