### ISSUE TITLE
Compiling with MINGW (Windows)

### ISSUE THREAD

**Issue by wo80** [mfem/mfem#2494]
I tested building MFEM with MINGW (msys2 on Windows 10)
```
Christian@CHRISTIAN-PC MINGW64 ~/mfem/build
$ cmake -G "MinGW Makefiles" ../
$ cmake --build .
```
There are two errors:
```
isockstream.cpp:26:13: error: conflicting declaration 'typedef int ssize_t'
socketstream.cpp:31:13: error: conflicting declaration 'typedef int ssize_t'
```
I think the `typedef` should be enabled only for VC compiler, so a possible fix could be to use
```c
#ifdef _MSC_VER
typedef int ssize_t;
#endif
```
in both files. That fixes the error for me and compiling with Visual Studio 2019 still works fine.

**Comment by tzanio** [comment]
Thanks for reporting this @wo80. 

Do you mind proposing a PR with the fix?

Tzanio

**Comment by wo80** [comment]
@tzanio I'll do the PR later this day.

**Comment by wo80** [comment]
Building the tests I get two additional compilation errors:
```
/mfem/tests/unit/fem/test_datacollection.cpp:309:4:   required from here
/mfem/tests/unit/catch.hpp:2311:98: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]

/mfem/tests/unit/fem/test_inversetransform.cpp:63:4:   required from here
/mfem/tests/unit/catch.hpp:2322:96: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]
```
Those can be fixed comparing to `nullptr` instead of `NULL`.

@tzanio Should this go into the same PR?

**Comment by tzanio** [comment]
> @tzanio Should this go into the same PR?

Yes, please.

**Comment by wo80** [comment]
I also have one test failing, but I don't think it's relevant here (at least, it's not related to the above changes):
```
-------------------------------------------------------------------------------
ParaView restart mode
-------------------------------------------------------------------------------
E:\data\Projekte\mfem\mfem\tests\unit\fem\test_datacollection.cpp:247
...............................................................................

E:\data\Projekte\mfem\mfem\tests\unit\fem\test_datacollection.cpp:294: FAILED:
  REQUIRE( xml.ErrorID() == XML_SUCCESS )
with expansion:
  6 == 0
```

**Comment by wo80** [comment]
The reason the test fails is because the generated `ParaView.pvd` has some weird formatting, see picture below. I don't know why this happens, maybe something with my MinGW setup. Compiling with Visual Studio all tests pass fine.

![paraview](https://user-images.githubusercontent.com/1840402/131368252-10ce1fbc-096d-4fcc-bea7-3eebb04f1681.png)

**Comment by pazner** [comment]
> The reason the test fails is because the generated `ParaView.pvd` has some weird formatting, see picture below. I don't know why this happens, maybe something with my MinGW setup. Compiling with Visual Studio all tests pass fine.

In the first line, `0D 0D 0A` is CR CR LF. I know that with Visual Studio, the line
```c++
pvd_stream << "<?xml version=\"1.0\"?>\n";
```
will actually output `<?xml version="1.0"?>\r\n` because the file is open in text mode, and so `\n` is translated to `\r\n`.

It looks like what is happening is that somehow `\r\r\n` is being written to the file. Maybe the conversion from `\n` to `\r\n` is happening twice? I don't know why this would be the case, but I have no familiarity with MinGW.

Something similar is probably causing the truncation seen later in the file.

**Comment by wo80** [comment]
@pazner
https://github.com/mfem/mfem/blob/12c7976b2ef7ee800efa81370aa3b7f47d32eeda/fem/datacollection.cpp#L830
The `Save` method will produce weird output for any system that uses `\r\n` as new line. The code looks rather fragile anyway.

Visual Studio also produces wrong line endings (`0D 0D 0A`) in `ParaView.pvd`, but it doesn't mess up the actual XML, that's why the test doesn't fail.

Flushing the buffer before reading the current position on line 976 will make the test pass:
```c++
pvd_stream << fname << "\"/>\n";
pvd_stream.flush(); // <-- workaround
std::fstream::pos_type pos = pvd_stream.tellp();
pvd_stream << "</Collection>\n";
```
 It does not fix the problem of weird line endings.

Should a new issue opened?

**Comment by tzanio** [comment]
Discussion continued in #2497
