### ISSUE TITLE
HYPRE Triangular Solver API Break

### ISSUE THREAD

**Issue by wcdawn** [mfem/mfem#2499]
It looks like the latest HYPRE commit to the master branch [here](https://github.com/hypre-space/hypre/commit/e53b5a0270e1d493a050fe4c37f6922ac72dda19) has an API break that breaks compiling the examples. This could also be related to HYPRE+CUDA.

MFEM configuration:
```
make config \
  MFEM_USE_OPENMP=YES MFEM_USE_MPI=YES CC=mpixlc CXX=mpixlC \
  MPICC=mpixlc MPICXX=mpixlC \
  HYPRE_DIR=${HYPRE_DIR} \
  METIS_DIR=${METIS_DIR} MFEM_USE_METIS_5=YES \
  MFEM_USE_CUDA=YES CUDA_CXX=nvcc \
  CUDA_FLAGS='-x=cu -arch=sm_70 --expt-extended-lambda --compiler-options -O3' \
  CUDA_LIB='-lcusparse -lcurand -lcublas'
```

HYPRE configuration:
```
CUDA_HOME=${OLCF_CUDA_ROOT} \
  HYPRE_CUDA_SM=70 \
  CC=mpixlc \
  CXX=mpixlC \
  ./configure \
  --disable-fortran \
  --with-cuda \
  --enable-unified-memory \
  --enable-device-memory-pool \
  --enable-cusparse \
  --enable-cublas \
  --enable-curand
```

Trying `make ex1p` in the `examples` directory produces:
```
/ccs/proj/csc404/wcdawn/container/hypre/src/hypre/lib/libHYPRE.a(par_relax_device.obj): In function `hypre_BoomerAMGRelaxHybridGaussSeidelDevice':
tmpxft_003cf231_00000000-6_par_relax_device.cudafe1.cpp:(.text+0x414): undefined reference to `hypre_CSRMatrixTriLowerUpperSolveDevice'
tmpxft_003cf231_00000000-6_par_relax_device.cudafe1.cpp:(.text+0x4d0): undefined reference to `hypre_CSRMatrixTriLowerUpperSolveDevice'
tmpxft_003cf231_00000000-6_par_relax_device.cudafe1.cpp:(.text+0x51c): undefined reference to `hypre_CSRMatrixTriLowerUpperSolveDevice'
collect2: error: ld returned 1 exit status
make: *** [makefile:78: ex1p] Error 1
```

I'm not sure if this is may be as simple as changing function names.

**Comment by tzanio** [comment]
@liruipeng, is there a recommended way to handle this change?

**Comment by liruipeng** [comment]
@tzanio Should I use the master branch of mfem to reproduce? BTW, building mfem (with the config above) is super slow. Is this normal? Thanks!

**Comment by liruipeng** [comment]
I build `ex1p` with the master of mfem and the master of hypre, which seemed fine
```
li50@ray59:~/workspace/mfem/master/examples$ make ex1p
nvcc  -O0 -std=c++11 -x=cu -arch=sm_70 --expt-extended-lambda -ccbin mpixlC -I.. -I/g/g92/li50/workspace/hypre/test/src/hypre/include  -Xcompiler=-fopenmp ex1p.c
pp -o ex1p -L.. -lmfem -L/g/g92/li50/workspace/hypre/test/src/hypre/lib -lHYPRE -lcusparse -lcurand -L/g/g92/li50/workspace/metis-4.0.3/ -lmetis  -lcusparse -lcu
rand -lcublas -lrt
```

**Comment by wcdawn** [comment]
@liruipeng 

> Should I use the master branch of mfem to reproduce? BTW, building mfem (with the config above) is super slow. Is this normal? 

Yes, I built with `mfem:master`. Yes, it takes a while to build MFEM like this. I'm building on Summit and I built with 32 cores and it took 252 seconds.

I still get the same error. I think you may have a different configuration because your compiler ran with `-O0` but mine ran with `-O3`.  Summit recently underwent an OS upgrade so there could be something new that is causing this. Specifically, there is a new version of `nvcc`.
```
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Wed_Jul_22_19:08:50_PDT_2020
Cuda compilation tools, release 11.0, V11.0.221
Build cuda_11.0_bu.TC445_37.28845127_0
```

**Comment by liruipeng** [comment]
> @liruipeng
> 
> > Should I use the master branch of mfem to reproduce? BTW, building mfem (with the config above) is super slow. Is this normal?
> 
> Yes, I built with `mfem:master`. Yes, it takes a while to build MFEM like this. I'm building on Summit and I built with 32 cores and it took 252 seconds.
> 
> I still get the same error. I think you may have a different configuration because your compiler ran with `-O0` but mine ran with `-O3`. Summit recently underwent an OS upgrade so there could be something new that is causing this. Specifically, there is a new version of `nvcc`.
> 
> ```
> nvcc --version
> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2020 NVIDIA Corporation
> Built on Wed_Jul_22_19:08:50_PDT_2020
> Cuda compilation tools, release 11.0, V11.0.221
> Build cuda_11.0_bu.TC445_37.28845127_0
> ```

Found the error. Stay tuned. Thanks!

**Comment by tzanio** [comment]
Thanks @liruipeng !

**Comment by tzanio** [comment]
@wcdawn can you confirm that `mfem:master` works for you now with `hypre:master`?

Thanks again for the quick report.

**Comment by wcdawn** [comment]
Works for me now. Thanks!

**Comment by tzanio** [comment]
Resolved by change in hypre, https://github.com/hypre-space/hypre/pull/469
