### ISSUE TITLE
Using and adapting "inline" mesh files

### ISSUE THREAD

**Issue by jxb3641** [mfem/mfem#251]
Hello,

I am looking to adapt the "inline" family of mesh files (specifically, "inline_tri.mesh" and "inline_tet.mesh") to add more attributes for the elements of the mesh. I am trying to create a PWConstCoefficient k for a DiffusionIntegrator that changes values in some subset of the original domain, and it seems to me that the simplest way to do this is to have a Vector of size mesh->attributes.Max() with different values of k for each entry, and then feed this into the PWConstantCoefficient constructor.

However, that set of mesh files is not written in the standard mesh v1.0 format, so there is no marking  of any attributes.  Is there any way to either:

1.) Change the "inline-tri.mesh" file itself to assign attributes for the mesh?

or 

2.) Change the attributes of the elements in my example file before the mesh is refined to mark the elements I need to with the given attribute,

Of course, I could also define a piecewise constant function defining k on the different parts of the domain and feed it into a FunctionCoefficient to feed into the DiffusionIntegrator, or create my own mesh file with the desired attributes, but I figured I should at least ask, since editing this file would be the easiest way to adjust for what I need.

Thanks in advance!

**Comment by v-dobrev** [comment]
You can set the attributes of the elements (or boundary element) in a `Mesh` using:
```c++
   mesh.GetElement(elem_id)->SetAttribute(attr);
   mesh.GetBdrElement(bdr_elem_id)->SetAttribute(bdr_attr);
```
or in the current development version of mfem you can use:
```c++
   mesh.SetAttribute(elem_id, attr);
```
After updating the attributes of the elements (and/or boundary elements), you should call:
```c++
   mesh.SetAttributes();
```
which will update the arrays `mesh.attributes` and `mesh.bdr_attributes`.

You can also take a look at the new [shaper.cpp](https://github.com/mfem/mfem/blob/master/miniapps/meshing/shaper.cpp) miniapp which performs some attribute modifications among other things.

**Comment by jxb3641** [comment]
Hello,

Just wanted to let you know, this works just fine; I was able to define the PWConstCoefficient correctly using this, and it works even after refining.  

Now I am wondering which is better to use: a PWConstCoefficient or a FunctionCoefficient?  I have been testing the two just now and I find that when the rhs is 0 (i.e, I solve for a linear or constant function), the FunctionCoefficient performs better (i.e, the error is less), but when I try to solve for exact solution with nonzero rhs (quadratic), they both perform around the same, with FunctionCoefficient having bigger error for some dofs, but PWConstCoefficient having bigger error for others.

It should be noted that due to the piecewise constant nature of the coefficient, neither solves well, since the rhs I compute isn't exact (I just pull out the K(x) and multiply by div(\grad p(x))), so the error is larger than expected on DOFs on the boundary where K changes.

**Comment by v-dobrev** [comment]
I'd expect that both `PWConstCoefficient` and `FunctionCoefficient` to give the same result, if they define the same function with jumps aligned with the mesh. I'm not sure why you get different solutions. Regardless, I don't have a recommendation which one is better to use - it is a matter of personal preference, I guess. However, it may be good to understand why they give you different results - that may tip the scales one way or the other.

**Comment by jxb3641** [comment]
Hello!

Just wanted to let you know, you were correct, they give the same result; the difference was from my implementation of the right hand side.  When I looked at the the global stiffness matrix itself though, the two were identical (at least, in the coarsest 2D case (no refinements).  I haven't checked the global stiffness matrix on more refined meshes, but if they're the same on the coarsest, I see no reason why the finer ones would differ.

**Comment by tzanio** [comment]
Glad you got it working @jxb3641. I'm closing this issue now. Feel free to reopen if you have any further questions.
