### ISSUE TITLE
Project vector field into another FEspace

### ISSUE THREAD

**Issue by brightzhang91** [mfem/mfem#2512]
Dear developers and users ;)

I just met the following problem when building my nonlinear application. I want to make the solution of a `GridFunction` into a  `VectorGridFunctionCoefficient`, and use the `VectorGridFunctionCoefficient` in my self-defined `NonlinearformIntegrator`.  However the `ParNonlinearForm`  is defined in a different `FiniteElementSpace` from the the  `GridFunction`. This is causing the incorrect mapping of`GridFunction` values to the `ParNonlinearForm`,  due to the different numberings of Dofs of two `FiniteElementSpace` (on the same mesh).

```
ParGridFunction J_(HDivFESpace);
........      solving for J_
J_coeff = new VectorGridFunctionCoefficient(&J_);
nonlinear = new ParNonlinearForm (HCurlFESpace);
nonlinear->AddDomainIntegrator(new my_NLIntegrator(*J_coeff ));

```
Which method should I use to project the solution values from one `FiniteElementSpace` into another ? 
I tried the `GridFunction::ProjectVectorFieldOn` #1152 and `GridFunction::ProjectGridFunction`. But it seems they both generate errors.
Or if there is a way to produce a `Coefficient` from a `GridFunction` without using `VectorGridFunctionCoefficient` /`GridFunctionCoefficient`?

Thanks very much!
Bright

**Comment by brightzhang91** [comment]
In other words, how to produce the "mesh-dependent" `Coefficient` like `PWConstCoefficient`  with values from a `GridFunction`, which is not associated with a `FiniteElementSpace`  but only associated with the mesh?
I found the `electromagnetics::MeshDependentCoefficient ` class, however it seems it only deals with the attributes of the mesh, but sill relies on a `FiniteElementSpace`.

**Comment by tzanio** [comment]
I am sorry but I can't quite understand the question.

Do you have two finite element spaces on the same mesh or different meshes? What is common or different between them? Is the projection exact (the spaces are embedded) or an approximation?

**Comment by brightzhang91** [comment]
> I am sorry but I can't quite understand the question.
> 
> Do you have two finite element spaces on the same mesh or different meshes? What is common or different between them? Is the projection exact (the spaces are embedded) or an approximation?

Hi tzanio

Thanks for your reply. The two/three finite element spaces are on the same mesh. They are defined in HCurl, HDiv and L2 respectively.  I want to have the following procedures in my implementation :
1.  Calculate the values for `GridFunction  J_(HDivFESpace);`
2.  Calculate the  the 3rd power of norml2 values of each element of ` J_`  pow(J_[i].Norml2(),3), and store it in a  `GridFunction J_L2(L2FESpace)`; // through a self-defined NonliearIntegrator
3. Define a `GridFunctionCoefficient` with `J_L2`, and used by `BilinearForm/NonlinearForm` defined in `HCurlFESpace`. 

However in MFEM, a scalar `GridFunctionCoefficient`  cannot be used in the vector finite element space. So that I need a way to project the `GridFunction J_L2' into a `GridFunction `defined in `HCurlFESpace`. Or can I just make the original `GridFunctionCoefficient` to an mesh-dependent Coefficient like `FunctionCoefficient` .The projection can be an approximation(but still hope for high accuracy in magnitude).

Thanks
Bright

**Comment by tzanio** [comment]
What do you mean by:

> However in MFEM, a scalar GridFunctionCoefficient cannot be used in the vector finite element space. So that I need a way to project the GridFunction J_L2' into a GridFunction defined in HCurlFESpace`.

`CurlCurlIntegrator` and `VectorFEMassIntegrator` certainly support scalar-valued Coefficients.

**Comment by brightzhang91** [comment]
> What do you mean by:
> 
> > However in MFEM, a scalar GridFunctionCoefficient cannot be used in the vector finite element space. So that I need a way to project the GridFunction J_L2' into a GridFunction defined in HCurlFESpace`.
> 
> `CurlCurlIntegrator` and `VectorFEMassIntegrator` certainly support scalar-valued Coefficients.

They support scalar Coefficients like `PWConstCoefficient`, but not scalar `GridFunctionCoefficient`.  I need to create a `Coefficient` from the solution stored in a `GridFunction` defined in another FEspace. 
Bright

**Comment by tzanio** [comment]
I believe the following should work regardless of the fact that the finite element spaces for `J_L2` and `a` are different:

```c++
GridFunction J_(HDivFESpace);
... // compute J_

GridFunction J_L2(L2FESpace);
... // fill in the dofs of J_L2 to be equal to  ||J_||^3

GridFunctionCoefficient *coeff = new GridFunctionCoefficient(&J_L2);
BilinearForm *a = new BilinearForm(HCurlFESpace);
a->AddDomainIntegrator(new CurlCurlIntegrator(*coeff));
a->AddDomainIntegrator(new VectorFEMassIntegrator(*coeff));
```

Am I missing something, or are you saying you are getting a segfault in one of the steps above?

**Comment by brightzhang91** [comment]
Yes I did similar and there were faults from it. The problem I met when using `GridFunctionCoefficient` by  `BilinearForm` defined in different FEspaces.
1. `GridFunctionCoefficient` in H1, and `BilinearForm`  in Hcurl. The error says a scalar `GridFunctionCoefficient` cannot be used in the vector finite element space. 
2.  `VectorGridFunctionCoefficient` in HDiv and `BilinearForm`  in Hcurl. The elements of the two FEspaces don't match.  The   `VectorGridFunctionCoefficient` didn't return the correct values of the right geometric position to the `BilinearForm` . 
So it seems to me that MFEM only works correctly when `BilinearForm` and `GridFunctionCoefficient` are in the same FEspace.

**Comment by mlstowell** [comment]
Hello, @brightzhang91,

We may need more information to really understand this problem. For example in point 1 of your previous message which `BilinearFormIntegrator` produced this error? The `BilinearForm` class itself does not use coefficients directly so the error did not originate in the `BilinearForm` code.

Your second point suffers from the same ambiguity. It should certainly be possible to use a `VectorGridFunctionCoefficient` based on an HDiv field with any class that requires an `VectorCoefficient` regardless of which other finite element spaces are involved. If the values are not correct there must be another explanation for that.

In a much earlier post you mentioned computing `pow(J_[i].Norml2(),3)` where `J_` is declared as an HDiv grid function i.e. `GridFunction J_(HDivFESpace);`. This actually doesn't make sense. I suspect you want the norm of the vector values represented by `J_` not the entries of `J_[I]`. Perhaps you are using `J_` to represent two different quantities in that post.

Best wishes,
Mark

**Comment by brightzhang91** [comment]
Thanks Mark
Yes I checked my implementation that it is not due to the matching problem between FEspaces. There is no problem with the `GridFunctionCoefficient` for returning the values to a `BilinearForm` in a different FEspace. Sorry for making the confusion. 

> In a much earlier post you mentioned computing pow(J_[i].Norml2(),3) where J_ is declared as an HDiv grid function i.e. GridFunction J_(HDivFESpace);. This actually doesn't make sense. I suspect you want the norm of the vector values represented by J_ not the entries of J_[i]. Perhaps you are using J_ to represent two different quantities in that post.

Yes,  I still need a way to produce a scalar `GridFunctionCoefficient` using  the vector values of `J_`, so that I tried the following:

```
GridFunction J_(HDivFESpace);
... // compute J_
GridFunction J_L2(L2FESpace);
VectorGridFunctionCoefficient J_coeff(&J_);
   ParMixedBilinearForm *DivL2_Mass = new ParMixedBilinearForm(&HDivFESpace, &L2FESpace);
   DivL2_Mass ->AddDomainIntegrator(new MixedDotProductIntegrator(J_coeff));
   DivL2_Mass ->Assemble();
   DivL2_Mass ->Finalize();
   DivL2_Mass  ->Mult(J_, J_L2 );
```
I used the `MixedDotProductIntegrator` to calculate the dot product of  `J_ `and `J_,` then the values in  J_L2 should be |J_|^2. However the result shows that's not the case.  

Bright

**Comment by mlstowell** [comment]
Hello, @brightzhang91, 

There are two possible reasons for this. One is that the field varies too rapidly and the `J_L2` representation of |J_|^2 is simply inaccurate. Refining the mesh or using higher order basis functions should improve the accuracy in this case. The second possibility is that there is a subtle misunderstanding of `J_L2`. Your code shows this to be a `GridFunction` but that is not correct. Technically when you use a bilinear form in this way the resulting field is a `LinearForm` not a `GridFunction`. This means that, when calculated in this manner, `J_L2` is not the field you should be comparing to |J_|^2. You need an additional step to convert `J_L2` into a proper `GridFunction`. You need to solve for such a `GridFunction` using your `J_L2` as the right-hand-side vector and an L2 mass matrix as the operator to solve.

That being said I would not compute this quantity in the above manner. Since an L2 field can be computed locally within each element from the HDiv degrees of freedom you can use an interpolator rather than an integrator and this will avoid the need to compute the solve I mentioned above.
```
ParGridFunction J_(HDivFESpace);
... // compute J_
ParGridFunction J_L2(L2FESpace);
VectorGridFunctionCoefficient J_coeff(&J_);
ParDiscreteLinearOperator*DotL2 = new ParDiscreteLinearOperator(&HDivFESpace, &L2FESpace);
DotL2->AddDomainInterpolator(new VectorInnerProductInterpolator(J_coeff));
DotL2->Assemble();
DotL2->Finalize();
DotL2->Mult(J_, J_L2 );
```

Best wishes,
Mark

**Comment by brightzhang91** [comment]
Thanks Mark ! I tried to use the Interpolator than an BilinearFormIntegrator and it returned me the correct |J_|^2 to a L2 `GridFunction`.
