### ISSUE TITLE
Differences between GetFaceVDofs and GetBdrElementVDofs

### ISSUE THREAD

**Issue by thorvath12** [mfem/mfem#2514]
Hi,

When we loop over the boundary elements there are two ways to collect the VDofs:

`fespace.GetBdrElementVDofs(bdr, vdofs_bdr);`
`int face_nr = mesh.GetBdrFace(bdr);`
`fespace.GetFaceVDofs(face_nr, vdofs_face);`

`vdofs_bdr` and `vdofs_face` contain the same entries, but not in the same order for some 3D meshes. For 2D meshes, the two arrays are the same. In my initial tests, `fespace` came from H1_Trace_FECollection and DG_Interface_FECollection, but later I found the same behavior with H1_FECollection.

Should not those two arrays be identical for all of the boundary elements? Could you please help me to understand where the difference is coming from?

Any help is appreciated.

Regards,
Tamas

**Comment by v-dobrev** [comment]
The intent of these methods is to return the `vdofs` in ordering that is consistent with the orientation (i.e. the vertex ordering) of the boundary element and the face element, respectively. Typically, the boundary element orientation is defined in the mesh file. On the other hand the face elements (interior and boundary) are auto-generated by the `Mesh` class and their orientations may be different from the one of the respective boundary element (if it exists).

When performing assembly, one has to be careful to use an `ElementTransformation` which is consistent with the boundary or face element orientation. If using `GetBdrElementVDofs`, use `Mesh::GetBdrElementTransformation` and when using `GetFaceVDofs`, use `Mesh::GetFaceTransformation`. For example, see the implementation of `BilinearForm::Assemble`, here https://github.com/mfem/mfem/blob/1e94f9c8a3993600caafd827990cf61d7cb9142a/fem/bilinearform.cpp#L512-L513 and the implementation of `DiscreteLinearOperator::Assemble` here: https://github.com/mfem/mfem/blob/1e94f9c8a3993600caafd827990cf61d7cb9142a/fem/bilinearform.cpp#L1913-L1915

**Comment by thorvath12** [comment]
Thank you, @v-dobrev, this clears it up. I did not know that it is related to the orientation, which might be different. I learnt it the hard way to be consistent with the `ElementTransformation` for the boundary elements.
