### ISSUE TITLE
Request for Serialize and De-Serialize functionality

### ISSUE THREAD

**Issue by obrien20** [mfem/mfem#2523]
MFEM is now being used for particle transport and a very useful technique there is to "replicate" the mesh and grid functions across many MPI processors and divide the particles among the processors.
A key requirement of this is to be able to broadcast your data structures to all processors in an MPI communicator.
One nice way to accomplish this is via a "Serialize" and "De-Serialize" feature.
Serialize means take your data structure and flatten it into a big buffer of bytes.
De-serialize is the opposite of that, given a buffer of data, re-construct the original object.

very roughly something like this:

```c++
char *buffer = nullptr;
size_t num_bytes = 0;

if ( rank == 0 ) {
  buffer = mfem_mesh.serialize(&num_bytes);
}
// broadcast the num_bytes and allocate space for it if rank != 0

MPI_Bcast(buffer, num_bytes, MPI_CHAR, 0, some_communicator);

if ( rank != 0 ) {
   mfem_mesh.deserialize(buffer, num_bytes);
}
```

and it is nice if this works "recursively" where if you have some giant data structure that has many data structures within it, you can serialize/deserialize at any level and it all works.

Can you please implement Serialize and De-Serialize functionality so we can use it for particle transport applications?  Thanks!

**Comment by tzanio** [comment]
Hi @obrien20,

Do I understand correctly that you have a serial `Mesh` and `GridFunction` that you wanted broadcasted?

Besides those two types, do you have any other object types that you will like to serialize?

I could be wrong, but I believe @jakubcerveny already did something similar in his ParNCMesh work.

Tzanio

**Comment by obrien20** [comment]
Hi @tzanio ,
I'm not exactly sure which mfem objects we have, I think @rmvega1025 can answer this question.
Note we use this technique in combination with domain decomposition, so each domain can be replicated a different number of times (that's how the load balancing works).  So any data structure that is needed while particle tracking will probably need to be serialized and de-serialized.
Thanks.

**Comment by rmvega1025** [comment]
Yes. Just GridFunction and Mesh should be sufficient.

**Comment by tzanio** [comment]
And just to confirm -- serial ones, not `ParMesh` and `ParGridFunction`?

**Comment by obrien20** [comment]
I would think we would also need the parallel ones for the domain decomposed case, right @rmvega1025 ?

**Comment by tzanio** [comment]
Ok, how about the following:

1. Use `Mesh::Print(std::ostream &out)` with a stream `out` that is just a string in memory
2. Communicate that string
3. Use `Mesh(std::istream &input)` to reconstruct the mesh

**Comment by obrien20** [comment]
that is possible, but you would have to write 16 decimal digits for floating point data: 
-1.234567890123456e-100
so that is 23 bytes for each 8 byte double.  For really large meshes we have exceeded the 2GB signed int MPI bcast length limit, so this is kind of a factor of 3 "bloat" in the data size, but this is a good start.
This should work for small problems.

**Comment by obrien20** [comment]
or can you just write a binary stream of data instead of "printing" the doubles, just write the bytes?

**Comment by lindstro** [comment]
This sounds like the perfect job for [Conduit](https://github.com/LLNL/conduit), possibly coupled with the grid function compression work we are doing at LLNL.

**Comment by obrien20** [comment]
is it lossless compression?  we have to make sure the reconstructed copy is exactly the same as the original.

**Comment by lindstro** [comment]
Our work primarily targets lossy (but error bounded) compression, though we also support lossless compression with one caveat.  In both compression modes, the grid functions have to be converted to a different polynomial basis, which may introduce double-precision floating-point roundoff error.  That said, we already expect such errors in the finite element computations themselves.  Moreover, other sources of error tend to dominate.

By "exactly the same," do you mean bit-for-bit identical?  If so, is the reason for this reproducibility?

**Comment by obrien20** [comment]
With Monte Carlo, debugging can be very difficult.  Ideally we would like to get the same answer when running on 1 or any number of processors.  If rank 0 has a slightly different mesh than the other ranks, this can make debugging very challenging.  So debugging is the main reason for this.  But if we could do something like round to 7 digits and guarantee all processors would round to the same answer, that should be fine.

**Comment by lindstro** [comment]
In either case, compression is deterministic, so if you replicate the same mesh or grid function across processors, it will appear identical on all processors, i.e., the same input to the compressor results in the same output.  Just to be sure, when discussing compression of the mesh, we're referring to its geometry, not connectivity?  The work we're currently doing does not address mesh connectivity, though we have developed other compressors for that.

**Comment by obrien20** [comment]
yeah, that sounds reasonable.  so in the 1 processor case we will still have to push it through this machinery to be consistent with num_procs > 1.

**Comment by lindstro** [comment]
I suppose so, if you require consistent answers regardless of number of processors.  There might be some subtleties with replicated DOFs across partition boundaries, but I am confident that we can address those kinds of issues.

Regarding redundant computations on a single processor, the good news is that compression is very fast (up to 500 GB/s on an NVIDIA V100 GPU).  So that ought not be a significant concern.  In fact, you'll most likely improve performance if you communicate the data in compressed form.

My understanding is that MFEM already uses Conduit for serialization (e.g., for I/O), though I don't know if de-serialization is also implemented.  @tzanio?  We expect compression to be insertable in different places, but one use case would be to take an existing Conduit tree describing a grid function and map it to another Conduit tree that represents a compressed grid function as an opaque stream of bytes that could be shared among processors.  Decompression would perform these steps in reverse.

**Comment by tzanio** [comment]
The cleanest solution will be if the `Mesh` and `GridFunctions` are added to a `DataCollection` that can `Save` to a memory buffer and `Load` from a memory buffer.

We have the `ConduitDataCollection`, but I think that assumes file I/O. @cyrush -- Is that correct? Easy it easy to extended to support memory buffers instead?

**Comment by cyrush** [comment]
Hi All,

We can wrap Mfem meshes + Grid Functions into Conduit nodes.  From here, Conduit can already serialize to an in memory buffer, along with string that provides a schema description so we can reconstruct the data and then unwrap back into mfem. 

There are a few options that this serialize / serialize workflow.

Also, Conduit Relay MPI supports shipping around Conduit Nodes via MPI (send, recv, isend, irecv, gathers, reductions, etc)

It can handle the serialization for you and there are fast paths if both sides know the schema of the data.

Lots of things to make tasks like this much much easier.

**Comment by camierjs** [comment]
What about an adaptation (+GPU) of [gslib](https://ceed.exascaleproject.org/gslib/)'s gather-scatter on arbitrary vector fields functionality ?

**Comment by tzanio** [comment]
@obrien20 and @rmvega1025 -- I think we should go forward with @cyrush's suggestion

**Comment by obrien20** [comment]
@tzanio , I think it sounds reasonable. 
One question for @cyrush : is there any (substantial) overhead of this method?  Like are you sending doubles as printed strings or anything like that?  Or just creating a big buffer of bytes?

**Comment by cyrush** [comment]
All the bulk data is packed into a compact buffer of bytes.

There is also a json description (which is a string) that is sent to provide context for how to de-serialize it. 

That metadata should be small compared to the bulk data as you scale up in mesh size.

**Comment by obrien20** [comment]
@cyrush , that sounds really good.  @tzanio , this method sounds great, thanks!
