### ISSUE TITLE
Reading Large Mesh in Parallel

### ISSUE THREAD

**Issue by wcdawn** [mfem/mfem#2542]
I have a very large mesh (>6.5 GB on disk) that I generated with Gmsh and would like to use with a parallel run of MFEM.
It seems like each MPI rank is reading the full mesh in the `mfem::Mesh` constructor and then METIS is called afterwards in the `mfem::ParMesh` constructor. This quickly overwhelms the available memory when each rank reads the full mesh.

I suspect part of my problem may be using the Gmsh ASCII format. Is there a way I need to otherwise convert/prepare my mesh?
It looks like SIDRE or ADIOS have some capabilities for this. Should I be using those? I will need restart capabilities soon as well.

Thanks!

**Comment by tzanio** [comment]
Hi William,

The ASCII vs Binary format matters for size on disc and the I/O time, but I don't think it should not affect the memory requirements -- you mesh may be just too big.

You have several options, depending on the problem:

1. You start directly with a parallel instead of a serial mesh. That will be the best, but requires a parallel mesh generator and I assume is not feasible with Gmsh.

2. The Gmsh is as coarse as possible to just capture the geometry, and any additional refinement is performed in MFEM after the parallel splitting. That's what we typically do. Using initial NURBS meshes in particular can save a lot of memory as long as the geometry is well described by them (mostly conic sections).

3. The initial mesh could be read by 1 rank on a node but not by all ranks on a node. That's a pretty special case that we don't support directly, but adding support for it is feasible -- the rank that reads the mesh just needs to perform the work for the other ranks and communicate the results to them.

4. There may be other options that I am missing -- _folks please chime in if you have suggestions_

Tzanio

**Comment by wcdawn** [comment]
> 1. You start directly with a parallel instead of a serial mesh. That will be the best, but requires a parallel mesh generator and I assume is not feasible with Gmsh.

Would this be feasible to do by running my Gmsh mesh through the meshing miniapp to generate the partitioning? I can feasibly load the mesh into memory if I run in serial. It's large but not impossible (~17 GB to store mesh & all data). The problem comes when each rank tries to load the entire mesh into memory.

**Comment by tzanio** [comment]
> Would this be feasible to do by running my Gmsh mesh through the meshing miniapp to generate the partitioning?

Unfortunately no. 

We are planning to add such a "partitioning" miniapp, and it is useful to know that it is important for you.

The difficulty is not in the partitioning itself, but in the generating of shared vertices, edges and faces and their communication groups that will have to be encoded in the ParMesh files.

**Comment by cwsmith** [comment]
@wcdawn PUMI provides a couple options.

1) PUMI has GMSH 'reader' (via an implementation of our mesh api and utilities using gmsh apis) for partitioning and converting into a format that MFEM understands.  This could be done as either a pre-processing step or in-memory.  The partitioning tool loads the mesh on one rank, uses geometric or graph based methods to compute the partition, then switches to a larger communicator and migrates elements to their destination process to create the distributed mesh instance.
  - This utility calls the gmsh reader and writes a pumi mesh (.smb): https://github.com/SCOREC/core/blob/b07bec1bfae28574088d7d2681ec9934b8bc94d0/test/gmsh.cc
  - This is one of the partitioning utilities that uses zoltan graph methods (via parmetis):
https://github.com/SCOREC/core/blob/b07bec1bfae28574088d7d2681ec9934b8bc94d0/test/zsplit.cc

2) Alternatively, we have a utility (see that can load a serial set of node and connectivity information in parallel.  This tool has been used with 'serial' meshes (a single file on disk) with over a billion elements.
  - This is the test utility for the 'construct(...)' method described above:
https://github.com/SCOREC/core/blob/b07bec1bfae28574088d7d2681ec9934b8bc94d0/test/construct.cc

From either path we will have a pumi mesh object (or file) that we can use to populate the MFEM's ParMesh object. An example of that is in the MFEM repo here https://github.com/mfem/mfem/blob/master/examples/pumi/ex1p.cpp. This example loads a parallel pumi mesh and then fills in the ParMesh object in MFEM and does a solve.

**Comment by sebastiangrimberg** [comment]
@wcdawn I have implemented approach #3 from @tzanio, so if you're interested in going that route I can show you how I did it.

It requires a little modification to the ParMesh class to make the ParMesh constructor asynchronous, so then you can read the serial mesh on one rank and do a staggered sending of the mesh data (coordinates + element nodes + partitioning) to the other ranks in batches. For each batch the ranks will receive the data, reconstruct the serial mesh, create the ParMesh, finally delete the serial mesh data, freeing up space for the next batch of ranks on that node.

Not sure if this is an optimal way to do it but it seems to work. Also this is all for non-curved meshes, but you can handle curvature by broadcasting the Nodes GridFunction as a final step once everyone has finished the ParMesh construction.

**Comment by wcdawn** [comment]
@sebastiangrimberg This sounds very promising to me. Are you willing to share code or diffs?
All of my meshes so far are linear finite elements so curvature is not a concern.

**Comment by sebastiangrimberg** [comment]
Sure! I'll post it here for visibility to everyone.

Here are the changes to `mesh/pmesh.cpp` and `mesh/pmesh.hpp`. I am just moving the construction of the `GroupTopology` member to after the constructor when it is called with `create_gtopo = false` since it has a global communication.

```
diff --git a/mesh/pmesh.cpp b/mesh/pmesh.cpp
index 57fb2e5ee..41b049cbe 100644
--- a/mesh/pmesh.cpp
+++ b/mesh/pmesh.cpp
@@ -105,7 +105,7 @@ ParMesh& ParMesh::operator=(ParMesh &&mesh)
 }
 
 ParMesh::ParMesh(MPI_Comm comm, Mesh &mesh, int *partitioning_,
-                 int part_method)
+                 int part_method, bool create_gtopo)
    : face_nbr_el_to_face(NULL)
    , glob_elem_offset(-1)
    , glob_offset_sequence(-1)
@@ -199,7 +199,6 @@ ParMesh::ParMesh(MPI_Comm comm, Mesh &mesh, int *partitioning_,
 
       GenerateFaces();
 
-      ListOfIntegerSets  groups;
       {
          // the first group is the local one
          IntegerSet group;
@@ -217,7 +216,7 @@ ParMesh::ParMesh(MPI_Comm comm, Mesh &mesh, int *partitioning_,
       int nsvert = FindSharedVertices(partitioning, vert_element, groups);
 
       // build the group communication topology
-      gtopo.Create(groups, 822);
+      if (create_gtopo) { gtopo.Create(groups, 822); }
 
       // fill out group_sface, group_sedge, group_svert
       int ngroups = groups.Size()-1, nstris, nsquads;
@@ -298,6 +297,12 @@ ParMesh::ParMesh(MPI_Comm comm, Mesh &mesh, int *partitioning_,
    have_face_nbr_data = false;
 }
 
+void ParMesh::CreateGroupTopology()
+{
+   // build the group communication topology
+   MFEM_VERIFY(groups.Size() > 0, "Shared groups have not been correctly set up");
+   gtopo.Create(groups, 822);
+}
 
 int ParMesh::BuildLocalVertices(const mfem::Mesh &mesh,
                                 const int* partitioning,
diff --git a/mesh/pmesh.hpp b/mesh/pmesh.hpp
index 2e9506af7..cb08b4b36 100644
--- a/mesh/pmesh.hpp
+++ b/mesh/pmesh.hpp
@@ -236,7 +236,7 @@ public:
        meshes (elements of nonconforming meshes should ideally be ordered as a
        sequence of face-neighbors). */
    ParMesh(MPI_Comm comm, Mesh &mesh, int *partitioning_ = NULL,
-           int part_method = 1);
+           int part_method = 1, bool create_gtopo = true);
 
    /** Copy constructor. Performs a deep copy of (almost) all data, so that the
        source mesh can be modified (e.g. deleted, refined) without affecting the
@@ -278,6 +278,10 @@ public:
        See @a Mesh::MakeSimplicial for more details. */
    static ParMesh MakeSimplicial(ParMesh &orig_mesh);
 
+   /** Explicitly create the group topology from the shared entities if not
+       done in the constructor (when constructed with create_gtopo = false). */
+   void CreateGroupTopology();
+
    virtual void Finalize(bool refine = false, bool fix_orientation = false);
 
    virtual void SetAttributes();
@@ -306,6 +310,7 @@ public:
    /// AMR meshes are supported.
    void GetGlobalElementIndices(Array<HYPRE_Int> &gi) const;
 
+   ListOfIntegerSets groups;
    GroupTopology gtopo;
 
    // Face-neighbor elements and vertices
```

Then here is what my code looks like to read a serial mesh. This is cut and pasted in chunks from a larger piece of code so may not work exactly, but hopefully gets the point across (namely I have this `comm` wrapper for `MPI_COMM_WORLD`).

```
mfem::Mesh *smesh;
int *partitioning;

int geo_data[5] = {0};
HYPRE_BigInt geo_size[3];
double *verts;
int *elems, *bdr_elems;
int batch_size;

if (comm.Root())
{
  smesh = new mfem::Mesh(iodata.model.mesh.c_str(), 1, 0, true);  // Don't mark for refinement yet

  const int part_method = 1;
  partitioning = smesh->GeneratePartitioning(comm.Size(), part_method);

  // Prepare data for broadcast.
  geo_data[0] = smesh->Dimension();
  geo_data[1] = smesh->SpaceDimension();
  geo_data[2] = smesh->GetNV();
  geo_data[3] = smesh->GetNE();
  geo_data[4] = smesh->GetNBE();

  // Each vertex has [x_1, ..., x_SpaceDim]
  int &sdim = geo_data[1];
  geo_size[0] = smesh->GetNV()*(HYPRE_BigInt)sdim;
  verts = new double[geo_size[0]];
  for (int v = 0; v < smesh->GetNV(); v++)
  {
    const double *xv = smesh->GetVertex(v);
    std::copy(xv, xv+sdim, verts+v*sdim);
  }

  // Elements (domain and boundary) are passed such that each element has
  // [geom, attr, v_1, ... v_Nv] contiguously.
  HYPRE_BigInt &esize = geo_size[1];
  esize = 0;
  for (int e = 0; e < smesh->GetNE(); e++)
  {
    esize += 2+smesh->GetElement(e)->GetNVertices();
  }
  elems = new int[esize];
  esize = 0;
  for (int e = 0; e < smesh->GetNE(); e++)
  {
    int nv, *v;
    mfem::Element *el = smesh->GetElement(e);
    elems[esize++] = (int)el->GetGeometryType();
    elems[esize++] = el->GetAttribute();
    nv = el->GetNVertices();
    v = el->GetVertices();
    std::copy(v, v+nv, elems+esize);
    esize += nv;
  }

  HYPRE_BigInt &bdr_esize = geo_size[2];
  bdr_esize = 0;
  for (int be = 0; be < smesh->GetNBE(); be++)
  {
    bdr_esize += 2+smesh->GetBdrElement(be)->GetNVertices();
  }
   bdr_elems = new int[bdr_esize];
  bdr_esize = 0;
  for (int be = 0; be < smesh->GetNBE(); be++)
  {
    int nv, *v;
    mfem::Element *el = smesh->GetBdrElement(be);
    bdr_elems[bdr_esize++] = (int)el->GetGeometryType();
    bdr_elems[bdr_esize++] = el->GetAttribute();
    nv = el->GetNVertices();
    v = el->GetVertices();
    std::copy(v, v+nv, bdr_elems+bdr_esize);
    bdr_esize += nv;
  }

  // Batch size info for staggered reads.
  batch_size = 1;  // Can also set this using ratio of node memory to serial mesh size
}

// Broadcast the serial mesh info to everyone.
comm.Broadcast(5, geo_data, 0);
comm.Broadcast(3, geo_size, 0);
comm.Broadcast(1, &batch_size, 0);

int node_rank, node_size;
{
  MPI_Comm node_comm;
  MPI_Comm_split_type(comm.Comm(), MPI_COMM_TYPE_SHARED, 0,
                                          MPI_INFO_NULL, &node_comm);
  MPI_Comm_rank(node_comm, &node_rank);
  MPI_Comm_size(node_comm, &node_size);
  MPI_Comm_free(&node_comm);
  comm.GlobalMax(1, &node_size);
}

mfem::ParMesh *pmesh = NULL;
for (int i = 0; i < node_size; i += batch_size)
{
  MPI_Comm batch_comm;
  int color = (comm.Root() || (node_rank >= i && node_rank < i+batch_size)) ? 1 : MPI_UNDEFINED;
  MPI_Comm_split(comm.Comm(), color, comm.Rank(), &batch_comm);  // Global root is still root

  if (comm.Root())
  {
    MPI_Bcast(verts,             (int)geo_size[0], MPI_DOUBLE, 0, batch_comm);
    MPI_Bcast(elems,            (int)geo_size[1], MPI_INT,          0, batch_comm);
    MPI_Bcast(bdr_elems,    (int)geo_size[2], MPI_INT,          0, batch_comm);
    MPI_Bcast(partitioning,         geo_data[3], MPI_INT,          0, batch_comm);
    MPI_Comm_free(&batch_comm);
 
    // Construct the root's part of the parallel mesh.
    if (!pmesh)
    {
      pmesh = new mfem::ParMesh(comm.Comm(), *smesh, partitioning, 0, false);
    }
  }
  else if (color != MPI_UNDEFINED)
  {
    verts            = new double[geo_size[0]];
    elems           = new int[geo_size[1]];
    bdr_elems   = new int[geo_size[2]];
    partitioning = new int[geo_data[3]];
    MPI_Bcast(verts,             (int)geo_size[0], MPI_DOUBLE, 0, batch_comm);
    MPI_Bcast(elems,            (int)geo_size[1], MPI_INT,          0, batch_comm);
    MPI_Bcast(bdr_elems,    (int)geo_size[2], MPI_INT,          0, batch_comm);
    MPI_Bcast(partitioning,         geo_data[3], MPI_INT,         0, batch_comm);
    MPI_Comm_free(&batch_comm);
 
    // Construct the serial mesh.
    int &dim = geo_data[0], &sdim = geo_data[1];
    int &Nv  = geo_data[2], &Ne   = geo_data[3], &Nbe = geo_data[4];
    smesh = new mfem::Mesh(dim, Nv, Ne, Nbe, sdim);
    for (int v = 0; v < Nv; v++)
    {
      smesh->AddVertex(verts+v*sdim);
    }
    HYPRE_BigInt esize = 0;
    while (esize < geo_size[1])
    {
      mfem::Element *el = smesh->NewElement((mfem::Geometry::Type)elems[esize++]);
      MFEM_VERIFY(el, "Unsupported element type!");
      el->SetAttribute(elems[esize++]);
      el->SetVertices(&elems[esize]);
      esize += (HYPRE_BigInt)el->GetNVertices();
      smesh->AddElement(el);
    }
    HYPRE_BigInt bdr_esize = 0;
    while (bdr_esize < geo_size[2])
    {
      mfem::Element *el = smesh->NewElement((mfem::Geometry::Type)bdr_elems[bdr_esize++]);
      MFEM_VERIFY(el, "Unsupported boundary element type!");
      el->SetAttribute(bdr_elems[bdr_esize++]);
      el->SetVertices(&bdr_elems[bdr_esize]);
      bdr_esize += (HYPRE_BigInt)el->GetNVertices();
      smesh->AddBdrElement(el);
    }
    delete[] verts;
    delete[] elems;
    delete[] bdr_elems;
    smesh->FinalizeTopology(false);
    smesh->Finalize(false, false);

    pmesh = new mfem::ParMesh(comm.Comm(), *smesh, partitioning, 0, false);
    delete smesh;
    delete[] partitioning;
  }
}
if (comm.Root())
{
  delete[] verts;
  delete[] elems;
  delete[] bdr_elems;
}
pmesh->CreateGroupTopology();
pmesh->Finalize(true, false);
```

Hope this is useful to you! I would be very thankful for any feedback from the other MFEM developers so please chime in here if you see anything that could be improved. I'm not sure how this compares to the PUMI approach that @cwsmith suggested, but would be very interested in hearing if that would be a better solution.

**Comment by tzanio** [comment]
Thanks @cwsmith and @sebastiangrimberg!

**Comment by wcdawn** [comment]
I got something working. It is admittedly pretty hacky. It uses `ParMesh::ParPrint()` which is typically used for restarting problems like in `ex6p`. I'm not sure that this is something that should be incorporated into MFEM in general. The only modifications I made are similar to those by @cwsmith.

This method would write a series of partitioned meshes that could then be used in a subsequent run. I tested this with the `mesh-explorer`.

```diff
diff --git a/mesh/pmesh.cpp b/mesh/pmesh.cpp
index 57fb2e5ee..fee3b8f8c 100644
--- a/mesh/pmesh.cpp
+++ b/mesh/pmesh.cpp
@@ -1,3 +1,4 @@
+// vim: set ts=3 sw=3 sts=3 expandtab:
 // Copyright (c) 2010-2021, Lawrence Livermore National Security, LLC. Produced
 // at the Lawrence Livermore National Laboratory. All Rights reserved. See files
 // LICENSE and NOTICE for details. LLNL-CODE-806117.
@@ -105,7 +106,7 @@ ParMesh& ParMesh::operator=(ParMesh &&mesh)
 }

 ParMesh::ParMesh(MPI_Comm comm, Mesh &mesh, int *partitioning_,
-                 int part_method)
+                 int part_method, int nrank_, int myrank_)
    : face_nbr_el_to_face(NULL)
    , glob_elem_offset(-1)
    , glob_offset_sequence(-1)
@@ -115,8 +116,16 @@ ParMesh::ParMesh(MPI_Comm comm, Mesh &mesh, int *partitioning_,
    Array<bool> activeBdrElem;

    MyComm = comm;
-   MPI_Comm_size(MyComm, &NRanks);
-   MPI_Comm_rank(MyComm, &MyRank);
+
+   if (nrank_ == -1)
+     MPI_Comm_size(MyComm, &NRanks);
+   else
+     NRanks = nrank_;
+
+   if (myrank_ == -1)
+     MPI_Comm_rank(MyComm, &MyRank);
+   else
+     MyRank = myrank_;

    if (mesh.Nonconforming())
    {
@@ -217,7 +226,8 @@ ParMesh::ParMesh(MPI_Comm comm, Mesh &mesh, int *partitioning_,
       int nsvert = FindSharedVertices(partitioning, vert_element, groups);

       // build the group communication topology
-      gtopo.Create(groups, 822);
+      if ((nrank_ == -1) && (myrank_ == -1))
+         gtopo.Create(groups, 822); // TODO necessary for "virtual" MPI

       // fill out group_sface, group_sedge, group_svert
       int ngroups = groups.Size()-1, nstris, nsquads;
diff --git a/mesh/pmesh.hpp b/mesh/pmesh.hpp
index 2e9506af7..8a5a358de 100644
--- a/mesh/pmesh.hpp
+++ b/mesh/pmesh.hpp
@@ -236,7 +236,7 @@ public:
        meshes (elements of nonconforming meshes should ideally be ordered as a
        sequence of face-neighbors). */
    ParMesh(MPI_Comm comm, Mesh &mesh, int *partitioning_ = NULL,
-           int part_method = 1);
+           int part_method = 1, int nrank_=-1, int myrank_=-1);

    /** Copy constructor. Performs a deep copy of (almost) all data, so that the
        source mesh can be modified (e.g. deleted, refined) without affecting the
```

And the MFEM program itself:
```cpp
#include "mfem.hpp"

#include <iostream>
#include <fstream>
#include <string>
#include <memory>

using namespace mfem;

void print_partitioning(const char *fname, int *partitioning, int num_element, int num_part);

int main(int argc, char *argv[])
{

  const std::string fname_part{"partitioning.txt"};
  const std::string fname_mesh_prefix{"part"};
  constexpr int part_method = 1;

  int num_rank;
  int myid;
  MPI_Init(&argc, &argv);
  MPI_Comm_size(MPI_COMM_WORLD, &num_rank);
  MPI_Comm_rank(MPI_COMM_WORLD, &myid);

  MFEM_VERIFY((num_rank == 1) && (myid == 0), "this program must be run in serial!");

  const char *mesh_file = "../mfem/data/star.mesh";
  int np{1}; // number of processors/mesh parts

  OptionsParser args(argc, argv);
  args.AddOption(&mesh_file, "-m", "--mesh", "Mesh file to use.");
  args.AddOption(&np, "-n", "--np", "Numter of processors for mesh partition.");
  args.ParseCheck();

  Mesh mesh{mesh_file};

  std::unique_ptr<int[]> partitioning{mesh.GeneratePartitioning(np, part_method)};
  print_partitioning(fname_part.c_str(), partitioning.get(), mesh.GetNE(), np);

  for (int i = 0; i < np; ++i)
  {
    ParMesh pmesh{MPI_COMM_WORLD, mesh, partitioning.get(), part_method, np, i};
    std::ofstream ofs{MakeParFilename(fname_mesh_prefix + ".", i)};
    pmesh.ParPrint(ofs);
  }

  MPI_Finalize();
  return 0;
}

void print_partitioning(const char *fname, int *partitioning, int num_element, int num_part)
{
  std::ofstream ofs{fname};
  ofs << "number_of_elements " << num_element << '\n'
      << "number_of_processors " << num_part << '\n';
  for (int i = 0; i < num_element; ++i)
    ofs << partitioning[i] << '\n';
  return;
}
```

**Comment by cwsmith** [comment]
@wcdawn Try the following:

- Generate a serial gmsh mesh
- Run `gmsh.cc` in serial to convert the serial gmsh to a serial pumi mesh (`.smb`)
- Partition from 1 to `T` ranks.  There are two options ([as listed above](https://github.com/mfem/mfem/issues/2542#issuecomment-921055152)):
   1. Run `zsplit` (parmetis part k-way) on `T` ranks.  The run command should be something like `mpirun -np T ./zsplit .null <mesh> T`.  The memory overhead of this approach is described here: https://github.com/SCOREC/core/wiki/Partitioning#memory-usage . 
   2. If the memory usage from `zsplit` on rank 0 (the rank that reads the serial mesh and hits the peak memory usage due to element replication prior to migration) is too high, then we should discuss the distributed reading approach (no rank loads all the mesh elements).  Below I've roughly outlined the required steps to implement this.
      1. Create 'exporter' utility/binary by modifying the `construct` utility to read the pumi mesh and write the arrays produced by [`extractCoords` and `destruct` APIs](https://github.com/SCOREC/core/blob/b07bec1bfae28574088d7d2681ec9934b8bc94d0/test/construct.cc#L27-L28) to disk.
      2. Create the 'parallel loader' utility/binary by reading the arrays from disk (details omitted for now) and then calling the [construction APIs](https://github.com/SCOREC/core/blob/b07bec1bfae28574088d7d2681ec9934b8bc94d0/test/construct.cc#L32-L42).  A specialized version of this process for a matched mesh of a simple domain (topologically a cube) is here: https://github.com/SCOREC/core/blob/f739597386af6de172bd6162b10aca2f0760c140/test/matchedNodeElmReader.cc#L827-L925
      
I'd be happy to go over these options on WebEx/Zoom if you'd like.

**Comment by wcdawn** [comment]
For posterity, PUMI seems to be the correct answer for my question. Using the info from @cwsmith, I have been able to split my mesh before running MFEM and run some test problems so far.

**Comment by sebastiangrimberg** [comment]
@wcdawn Just out of curiosity I was playing around with your approach using `ParMesh::ParPrint()` but had issues reading the printed mesh back in for the simulation. It seems like it will always print `number_of_groups -1` in the parallel mesh footer because the `GroupTopology` member isn't created during the serial preprocessing run. Is there a way around this, or how did you get this to work, if you don't mind me asking?

**Comment by wcdawn** [comment]
@sebastiangrimberg in case you couldn't guess, I didn't make it too far with that above snippet :)

I tried two different methods. The first resembled your diff above to explicitly create the topology. The problem I had there was that MFEM uses MPI calls to "probe" the topology and I was trying to run on a single rank to split the mesh. An alternative may be some sort of input file with topology data. My second attempt was to just write that part of the mesh file myself. Since these were test cases, I was only trying to split into two pieces so it was just adding a couple of lines.

PUMI requires running with the appropriate number of ranks to split the mesh before it could be loaded into MFEM. It may be possible to replace PUMI with MFEM if you use your method to read in the mesh, create the `GroupTopology`, and then use `ParPrint`.

**Comment by sebastiangrimberg** [comment]
Perfect, thanks so much for following up. I'm going to tinker around with constructing the `GroupTopology` on the serial process locally before using `ParPrint`, will let you know how it goes.

**Comment by v-dobrev** [comment]
Hi all, I started a branch and PR to address this issue, see https://github.com/mfem/mfem/pull/2669.

If you can give it a try and provide any feedback, that will be great.
