### ISSUE TITLE
Solve complex mixed finite element problems

### ISSUE THREAD

**Issue by NjJu1** [mfem/mfem#2545]
Hi, I am trying to use MFEM to solve a finite element problem where equations have the form like:
nabla x (nabla x u) + j * omega * nabla p = 0,
where u,p are (complex) unknowns and j is the unit imaginary number. Thus a mixed finite element needs to be used.

I have found in example 5 that we can use the following codes for generating mixed finite element:
`   BilinearForm *mVarf(new BilinearForm(R_space));
   MixedBilinearForm *bVarf(new MixedBilinearForm(R_space, W_space));
`
Since here the unknowns are complex, the `BilinearForm` in the first sentence needs to replaced with `SesquilinearForm.` However, I have searched the codes document, and have not found the class named `MixedSesquilinearForm.`

Thus how could I write the equation in MFEM? Could I just use MixedBilinearForm for the term  j * omega * nabla p?

Thanks a lot!

**Comment by mlstowell** [comment]
Hi, @NjJu1,

You are absolutely correct. We don't have this yet. However, it should not be difficult to put together.  I'll take a closer look at the issue and get back to you.

Best wishes,
Mark

**Comment by mlstowell** [comment]
Hi, @NjJu1, 

I just added a first draft of a `MixedSesquilinearForm` class. It seems to compile without issue but I haven't tested it yet. You can find it in the [mixed-slf-dev](https://github.com/mfem/mfem/tree/mixed-slf-dev) branch. If you can have a look and test it in your application that would be great.

I'll also try to add a parallel version soon. I'll also try to come up with a unit test and/or an example code to make sure it works as expected.

Thanks for pointing this out.

Best wishes,
Mark

**Comment by NjJu1** [comment]
Hi, Mark. Thanks very much for your kindly reply and quick response! I will try this branch! Thanks a lot!

Best regards,
Ju
