### ISSUE TITLE
Finite element calculation of 3D surface

### ISSUE THREAD

**Issue by HFH104864** [mfem/mfem#2547]
Dear MFEM Maintainer 

  I have a finite element model of 3D curved surface, and I wonder if MFEM can solve it.

  I input the mesh model into the EX2 of MFEM and try to solve it, but it seems that the EX2 of MEFM only solves the problems of 2D  plane model and 3D solid model.I input my model into the EX2 solution, but the node displacement is only in the X and Y directions, which is obviously not what I want.

For this 3D surface model, if it is in ANSYS, a thickness parameter needs to be specified, I would like to ask if MFEM can do the same.

If possible, please let me know what I need to know, I would be very grateful!

**Comment by tzanio** [comment]
Hi @HFH104864,

We can solve PDEs on surface, see the `*surf.mesh` files in the `data/` directory and e.g. this sample run: ` ex1 -m ../data/star-surf.mesh`.

The first step should be to export your 3D surface in the MFEM-compatible 3D surface mesh format. What mesh generator do you use?

Tzanio

**Comment by HFH104864** [comment]
Dear Tzanio


 I use Gmsh as the mesh generator .  

I used Gmsh to generate a VTK format quadrangular grid file, then I imported the VTK file into MFEM EX1 and ran it to get a GF file.I wonder what the meaning of this GF file is. And I looked at EX1, and there's no way to find code that applies boundary conditions like EX2.

Could you please help me , thank you !

**Comment by tzanio** [comment]
Can you attach the VTK mesh you are using by any chance?

The GF file is the "GridFunction" solution, i.e. the vector of degrees of freedom of the finite element approximation.

**Comment by HFH104864** [comment]
This is my VTK file, and the GF file generated by running EX1 from this VTK file.

[file.zip](https://github.com/mfem/mfem/files/7215484/file.zip)


I looked at the GF file and found that there was only an approximation of one degree of freedom, and I didn't know which one

**Comment by pazner** [comment]
It looks like there was a bug in the VTK mesh reader when loading surface meshes (meshes that are topologically 2D embedded in 3D space). Thanks for reporting this. It is fixed in #2566.

Using the fixed version, I can use your mesh with ex1 to solve the Laplace problem on the surface.

<img width="700" alt="Screen Shot 2021-09-23 at 9 43 53 AM" src="https://user-images.githubusercontent.com/11493037/134554022-d06167c3-0c96-41a2-9c3d-7cfe2eab7bd5.png">

**Comment by tzanio** [comment]
Thanks Will!

**Comment by HFH104864** [comment]
It really seems to work and I can't wait to try it out.

My MFEM version is 4.2, so I need to compile 4.3 to modify the code.

But when I compiled 4.3, it wasn't as smooth as when I compiled 4.2.I compiled MFEM4.3 using VS2019 on Windows and the error occurred.When I generated the project MFEM, C2644,C2065,C2530 and C3536 errors occured.They are

`C2664 "void mfem: : IntegrationPointTransformation: : Transform (const mfem: : IntegrationPoint &, mfem: : IntegrationPoint &)" :cannot  convert parameter 1 from "int" to "const mfem::IntegrationPoint &"`

`C2065 "i" : undeclared identifier`

`C2530 “fip”: reference variable must be initialized `

`C3536 “fip": cannot be used before initialization`

respetively

I tried  Project ->Properties -> Configuration Properties -> General -> Projectdefaults -> Character Set->multi-byte character sets , but it didn't work . 

any help will be appreciated.d.

**Comment by pazner** [comment]
Are these error messages when you download the 4.3 release, or the latest commits on the master branch? Could you try cloning the repo and compiling with the latest master? Also, what are the files and line numbers associated with these errors?

**Comment by HFH104864** [comment]
I downloaded 4.3 Release and compiled it using Cmake to generate a project file `mfem.sln.` I opened the `mfem.sln` and tried to generate ALL_BUILD and these errors occurred.

These errors occur under project `mfem`,` Estimators. CPP`, line 241 `Auto &fip = int_rule-intpoint (I);`

There are other related errors that occur in this file.

![1632539874(1)](https://user-images.githubusercontent.com/69201217/134756158-e5c3c288-d903-4b5a-9db9-35da555822ef.png)

**Comment by pazner** [comment]
Could you try with a clone of master instead of the release?

And that error is interesting. It complains about `"i" : undeclared identifier` on line 242, but clearly `i` is defined on line 239. Our CI also builds and tests with Visual Studio, so it really should compile.

Maybe it's a file encoding issue, and something goes wrong because of the unicode characters in the comment on line 238. Just a guess…

**Comment by HFH104864** [comment]
Thank you ! 

Oddly enough, after I deleted the comments, the compilation succeeded !!!

And using the fix version , my problem can be solved !!!
