### ISSUE TITLE
Obtain a HypreParMatrix where diagonal entries are 1 for boundary dofs

### ISSUE THREAD

**Issue by adam-sim-dev** [mfem/mfem#2548]
Hello everyone,

For a `ParFiniteElementSpace,` I want to obtain a `HypreParMatrix,` which only has values on its diagonal entries. If the j-th global dof is on the boundary, the corresponding j-th `HypreParMatrix` diagonal entry is 1, otherwise it's 0.  Any ideas?

Thanks in advance.
Adam

**Comment by tzanio** [comment]
Hi Adam,

You can use `FiniteElementSpace::GetEssentialTrueDofs` to get a vector of the boundary dofs, and then make that into a diagonal matrix. If you just need the action though, it will be more efficient to define a diagonal operators that just uses the vector.

Hope this helps,
Tzanio

**Comment by adam-sim-dev** [comment]
Hi Tzanio,

I have difficulty in creating a `HypreParMatrix` after I obtain the boundary dofs. Sorry, not familiar with the data structure of the parallel CSR matrix. Which `HypreParMatrix` constructor should I use? Now I am using the following:

   HypreParMatrix(MPI_Comm comm, HYPRE_BigInt glob_size,
                  HYPRE_BigInt *row_starts,
                  SparseMatrix *diag); // constructor with 4 arguments, v1

where I set row_starts[0] = 0. ros_starts[1] = glob_size. It could run in serial, but the parallel run fails. 

Best,
Adam

**Comment by tzanio** [comment]
Yes, you can use that constructor.

The `row_starts` should be  the global indices of the first and last rows owned by each MPI task.

Hope this helps.

**Comment by pazner** [comment]
The functions `ParFiniteElementSpace::GetTrueDofOffsets` and `ParFiniteElementSpace::GlobalTrueVSize` will probably be useful for this purpose.

**Comment by adam-sim-dev** [comment]
Hi @pazner and @tzanio, thanks for your kind reply. My problem has been solved now. I will close this issue.
