### ISSUE TITLE
Document the difference between LinearFormIntegrator::AssembleRHSElementVect methods L2 vs H1

### ISSUE THREAD

**Issue by bslazarov** [mfem/mfem#2550]
Mixing together several discretizations, i.e. H1 and L2, requires either implementation of the two versions of LinearFormIntegrator::AssembleRHSElementVect, or a single version with FaceElementTransformations. The documentation does not provide any guidance how the different versions are used in the code. The method with FaceElementTransformations is more general and can be used with H1 and L2 fields.

**Comment by tzanio** [comment]
I added the main authors of `fem/lininteg.cpp` and `fem/lininteg.hpp` (according to GitHub).

Lets discuss here what documentation will be most useful and who is available to help with it.

**Comment by tzanio** [comment]
Discussion continued in https://github.com/mfem/web/issues/165
