### ISSUE TITLE
HYPRE API Change with hypre_IntArray

### ISSUE THREAD

**Issue by wcdawn** [mfem/mfem#2551]
HYPRE introduced `hypre_IntArray` which wraps `HYPREInt` and contains data about memory location and size.

[Here](https://github.com/hypre-space/hypre/commit/001d4fe2c7fe49d35ab9810d92ba1ec0a3034d11) is the commit.

This breaks the MFEM/HYPRE interface in several places.
HYPRE v 2.22.1 remains the newest, usable version.

**Comment by tzanio** [comment]
Thanks for reporting this @wcdawn

**Comment by tzanio** [comment]
@rfalgout, any recommendations what we should do to address this?

**Comment by rfalgout** [comment]
> @rfalgout, any recommendations what we should do to address this?

@tzanio , I will create a hypre issue pointing to this and we'll help you get it resolved.  Unfortunately, you can't take advantage of the new variables in [hypre PR #472](https://github.com/hypre-space/hypre/pull/472) quite yet.  Related to this, I would like to discuss a bit more with you how we deal with compatibility issues and testing going forward.

**Comment by tzanio** [comment]
Thank  you @rfalgout. Yes, let's discuss testing.

**Comment by tzanio** [comment]
Discussion continued in #2553.
