### ISSUE TITLE
New functions for Finding points in mesh and Gradient functions for Raviart-Thomas spaces. 

### ISSUE THREAD

**Issue by pratyuksh** [mfem/mfem#2554]
Hi, while working on a project using MFEM earlier, I implemented a few routines which I think might be useful in the library:

1) For locating a list of points on a given, when we expect the points to be in the vicinity of one another. This routine was useful to compute the solution error between two arbitrary meshes. It uses the connectivity between vertices and cell elements, which requires more memory than the current "FindPoints" implementation, but it is much faster.

1) I also implemented some routines for computing the gradients of Raviart-Thomas basis functions, see:
 mfem/mfem#769 (comment)

If you feel they can be useful, I can create a pull request and add them. Thanks!

**Comment by tzanio** [comment]
@kmittal2 and @mlstowell, what do you think?

**Comment by kmittal2** [comment]
Hi @pratyuksh, 

I am interested in learning more about your `FindPoints` implementation: Did you build upon the existing implementation to make it more efficient for certain cases or is it a new method to find points. If it is a new method, does it work for high-order meshes and in parallel? Also, did you compare your implementation with MFEM's [FindPoints](https://github.com/mfem/mfem/blob/master/mesh/mesh.hpp#L1552) method in `Mesh` class or with [FindPointsGSLIB](https://github.com/mfem/mfem/blob/master/fem/gslib.hpp#L47)? 

It will be helpful if you can share your implementation through a PR and mark it for discussion. 

Cheers,
Ketan

**Comment by mlstowell** [comment]
Hi, @pratyuksh,

The post you linked certainly got a lot of attention so I think it would be useful. If you could put together a PR with a simple test problem that we could use as a unit test that would be great.

Best wishes,
Mark

**Comment by pratyuksh** [comment]
Hi @kmittal2 ,

1) It does not use the existing implementation, it is a new and uses the connectivity from vertices to elements.
2) The new implementation is serial, and I compared it with MFEM's FindPoints method in Mesh class.

@kmittal2  @mlstowell  I will create the pull requests and share the code in the next days.

Best wishes,
Pratyuksh

**Comment by tzanio** [comment]
Discussion continued in https://github.com/mfem/mfem/pull/2599
