### ISSUE TITLE
mfem::ParFiniteElementSpace::GetEssentialTrueDofs

### ISSUE THREAD

**Issue by bslazarov** [mfem/mfem#2559]
I am not completely sure what is the issue, however, for NCMesh the checks do not pass and the code generates an error. An example file with mesh is attached. 
[tst.cpp.gz](https://github.com/mfem/mfem/files/7207933/tst.cpp.gz)
[manifold.msh.gz](https://github.com/mfem/mfem/files/7207936/manifold.msh.gz)

A run on a single process works fine. The issue have been observed on 2, 4 and 8 processes.

**Comment by v-dobrev** [comment]
A potential workaround/solution is to comment out the `if` line here: https://github.com/mfem/mfem/blob/9a73c2d94c5ecff6dd64c9f7f575e55da0b250cf/fem/pfespace.cpp#L1013 or in other words to call `Synchronize` for NC meshes as well.

**Comment by v-dobrev** [comment]
This should be resolved by #2722. I tried the code and mesh posted above and they seem to work fine with that PR.
