### ISSUE TITLE
Parallel unit test failure with CUDA enbaled

### ISSUE THREAD

**Issue by v-dobrev** [mfem/mfem#2562]
When both MFEM and HYPRE are build with CUDA, `make test` fails in the unit test
```console
mpirun -np 1 punit_tests
```
The error is in a new test added after MFEM v4.3 in PR #1046, here: https://github.com/mfem/mfem/blob/9a73c2d94c5ecff6dd64c9f7f575e55da0b250cf/tests/unit/fem/test_eigs.cpp#L261

Note: if HYPRE is build without CUDA, `make test` works fine.

**Comment by tzanio** [comment]
Is this test not supported, or should the tolerance be modified?

**Comment by v-dobrev** [comment]
The failure is because `err` is `nan`.

**Comment by v-dobrev** [comment]
It looks like the problem is not just in the test but with `HypreLOBPCG` -- `make test` does not show `ex11p` as failing, however the output is wrong:
```ascii
> mpirun -np 1 ex11p -no-vis
Options used:
   --mesh ../data/star.mesh
   --refine-serial 2
   --refine-parallel 1
   --order 1
   --num-eigs 5
   --seed 75
   --no-visualization
Number of unknowns: 1361
Error in LOBPCG:
Bad initial vectors: orthonormalization failed

Solving generalized eigenvalue problem with preconditioning

block size 5

No constraints

DPOTRF INFO = 1

Eigenvalue lambda                    nan
Eigenvalue lambda                    nan
Eigenvalue lambda                    nan
Eigenvalue lambda                    nan
Eigenvalue lambda                    nan
Residual   0.00000000000000e+00
Residual   0.00000000000000e+00
Residual   0.00000000000000e+00
Residual   0.00000000000000e+00
Residual   0.00000000000000e+00

0 iterations
```
and the exit code is 0.

Maybe this example never actually worked correctly with HYPRE built with CUDA.

**Comment by v-dobrev** [comment]
@liruipeng, should we expect HYPRE's LOBPCG to work when HYPRE is built with CUDA?

**Comment by v-dobrev** [comment]
Another observation: it looks of the three examples using `HypreLOBPCG`, `ex{11,12,13}p`, both `ex11p` and `ex12p` fail in a similar manner, however `ex13p` seems to work correctly. That leads me to believe that HYPRE's LOBPCG should work fine when HYPRE is built with CUDA, and the issue that makes `ex{11,12}p` fail is somewhere in MFEM.

**Comment by liruipeng** [comment]
Hi @v-dobrev , LOBPCG should work fine. We have regression tests on it (but with small problems). Please let me know if I can help further more.
