### ISSUE TITLE
Anisotropic refinement in MFEM

### ISSUE THREAD

**Issue by kvoronin** [mfem/mfem#257]
Hello,

I'd like to ask how one should do a anisotropic refinement in MFEM.
I've found Mesh::GeneralRefinement() but I didn't find a function argument anywhere nearby so that I can set something different from the default type = 7 which is isotropic refinement.
It seems that all refinement types are drawn from the refinement flag for the first mesh element which is set to be isotropic by default.
Am I missing something? Certainly I can add a method similar to Mesh::GeneralRefinement() with additional parameter, but I don't want to add redundant routines if there exists already.

Thanks,
Kirill

**Comment by jakubcerveny** [comment]
Hi Kirill,

You can refine a mesh anisotropically for example like this (I'm refining
elements 0-6):

Array<Refinement> refs;
refs.Append(Refinement(0, 1)); // X split
refs.Append(Refinement(1, 2)); // Y split
refs.Append(Refinement(2, 4)); // Z split
refs.Append(Refinement(3, 3)); // XY split
refs.Append(Refinement(4, 5)); // XZ split
refs.Append(Refinement(5, 6)); // YZ split
refs.Append(Refinement(6, 7)); // isotropic split (default)

mesh.GeneralRefinement(refs);

Note that anisotropic refinement in parallel is not finished yet. You
should be able to initialize a ParMesh with an anisotropic serial mesh but
you won't be able to refine it further.

Hope that helps,
Jakub

**Comment by kvoronin** [comment]
@jakubcerveny,
Thanks for the reply!
May I also follow up with the question if this works with hexahedral meshes? As far as I see, GeneralRefinement() calls LocalRefinement which is using Bisection() in 3D which works for  tetrahedrons (and triangles). Am I right?

Thanks,
Kirill

**Comment by jakubcerveny** [comment]
No problem. The answer is yes. For hexahedra and quads there is a separate
code path that goes into the class NCMesh, which supports nonconforming
refinement with hanging nodes. This is completely different from the
bisection of triangles and tets.

Jakub
