### ISSUE TITLE
How to perform a least squares approximation with MFEM

### ISSUE THREAD

**Issue by pmguilcher** [mfem/mfem#2585]
Hello,

I would like to perform a least squares approximation of a function f, within a FEM framework.
This is an extension of a polynomial regression over a set of points.
The idea is to minimize the global classical squared error of least squares, which is based on the local error (difference between f and its FEM approximation) integrated over the all domain.
Differenciation of the global error provides a set of linear equations with unkowns corresponding to the FEM DoFs.

I tried to set up the linear system by hand, using a BilinearForm for the matrix, and a LinearForm for the RHS. The LinearForm corresponds to the integral of the function f (to be approximated) and the basis function associated to one DoF.

I managed to solve the linear system, but it appears that my solution on each DoF is exactly equal to the provided f function. So at the end, I just get a kind of FEM interpolator: the solution on each node is exactly equal the provided function, and I can interpolation in between.

This is not a "best" approximation in the sense of an average through an integral of f on each element. Looking more precisely at the LinearForm, I give the function f as a FunctionCoefficient. So I think that during the integration (rule) process, f is only evaluated at integration points, and the quadrature order is the same as the basis function order on each element. So even if my function f is very complexe, or oscillating, I just get a p-order approximation on each element, and the information on f is "lost" during integration.
Am I right?

And if I want to increase the accuracy on the integration of f on each element (for my RHS), what would you suggest to do? Increase the order of the test space?

Thank you
Pierre

**Comment by pazner** [comment]
Hello @pmguilcher,

If I understand correctly, what you want to do is equivalent to the L2 projection of the function f onto your finite element space (i.e. find the element u of your space V such that the L2 norm of (u-v) is minimized).

This can be accomplished by solving the system Mu = b, where M is the mass matrix, and b is the RHS you describe. As you mention, the RHS is computed using quadrature, and if your function f is very complex, it may require a quadrature rule with a high degree of precision to integrate accurately.

You can try something like the following:

```c++
// Given finite element space `fespace`, construct the mass matrix
BilinearForm m(&fespace);
m.AddDomainIntegrator(new MassIntegrator);
m.Assemble();
m.Finalize();

// Define an integration rule for the RHS
int quadrature_precision = 10;
Geometry::Type geom = mesh.GetElementGeometry(0);
const IntegrationRule &ir = IntRules.Get(geom, quadrature_precision);

// Make a "coefficient" given the function `f`
FunctionCoefficient f_coeff(f);
// Create the right-hand side
LinearForm b(&fespace);
b.AddDomainIntegrator(new DomainLFIntegrator(f_coeff, &ir)); // <-- here we give the integration rule to the RHS integrator
b.Assemble();

GridFunction x(&fespace);
x = 0.0;

SparseMatrix &M = m.SpMat();
DSmoother D(M);
PCG(M, D, b, x, 1, 200, 1e-12, 0.0);
```

**Comment by pmguilcher** [comment]
Hello @pazner 

You understood well! Indeed, I performed my least squares (or projection) approximation through the mass matrix.
I tried your solution, and it works very well.

Thank you so much for your help.

Pierre

**Comment by petr-henys** [comment]
Hello,
let me extend the question a bit more. Consider a function f which looks for some neighbourhood points around an actual point (integration point) in some point cloud representing discrete values of a scalar field and makes interpolation from those neighbourhoods. How this can be implemented with FunctionCoefficient?

**Comment by pazner** [comment]
> let me extend the question a bit more. Consider a function f which looks for some neighbourhood points around an actual point (integration point) in some point cloud representing discrete values of a scalar field and makes interpolation from those neighbourhoods. How this can be implemented with FunctionCoefficient?

The best way to implement what you describe probably depends on the specifics of your problem. It is definitely possible to construct such a `Coefficient`, but `FunctionCoefficient` is not the right way to do it. `FunctionCoefficient` is usually designed for functions that are evaluated pointwise (e.g. using analytical formulas).

Perhaps you could use `QuadratureFunctionCoefficient` or something similar. If it is unclear how to proceed, feel free to open an issue with the details of your problem.
