### ISSUE TITLE
Mfem with sequential solvers

### ISSUE THREAD

**Issue by hbadi** [mfem/mfem#2591]
Hi,

I'm looking to compile mfem with visual studio/intel compiler using a sequential multithreaded solver like MKL Pardiso, MUMPS or Petsc, but it seems that all solvers need MPI/Hypre.

Best regards.

**Comment by psocratis** [comment]
Hi @hbadi, 

You are right that PETSC, MUMPS and PARDISO interfaces in MFEM require MPI/Hypre. One alternative option is to use UMFPack from SuiteSparse package which is a serial direct solver. MFEM provides this interface as well (see ex1.cpp). 

Hope this helps. 

Best, 

Socratis
