### ISSUE TITLE
Implementation of ParNonlinearForm::GetGradient()

### ISSUE THREAD

**Issue by geyan3566** [mfem/mfem#2593]
Hi,

I'm running some nonlinear simulation with implicit time marching. Running all problem in serial limits me from going to large scale simulations.

I'm wondering if there is a plan to implement the `ParNonlinearForm::GetGradient()`, so that all the community will be benefited from this.

Thanks,
GE

**Comment by jandrej** [comment]
To clarify, you are defining an L2 integrator? If that is the case then yes, the assembly of gradients from nonlinearforms is not supported.

**Comment by geyan3566** [comment]
Yes, I'm using an L2 integrator.
So is there any plan to implement this method?
