### ISSUE TITLE
How to form linear system for a block operator when there are several unknown variables with Dirichlet BC to be solved?

### ISSUE THREAD

**Issue by NjJu1** [mfem/mfem#2596]
Hi, I am now using MFEM to solve a PDE where there are several unknown variables in different finite element space and contains Dirichlet BC. According to example 5, I define a block operator and set up each block using the corresponding (Par)(mixed)bilinear form. By using FormSystemMatrix and FormRectangularSystemMatrix, the dofs corresponding to the Dirichlet BC can be eliminated for the operator.

However, those dofs should also be eliminated for the righthand terms rhs. However, I have not found a convenient way to do so. In example 5, no essential Dirichlet BC exists, thus nothing to be performed for the rhs. 

A seemingly feasible way is by using the member method FormLinearSystem of blockOperator inherited from the Operator class. This way needs to define an Array<int> of ess_tdof_list. A possible way to obtain this is to combine the separate ess_tdof_list from each finite element space. E.g., assume ess_tdof_list1 = [1,2,3,6], ess_tdof_list2 = [1,2,3,4] and fes1.GetVSize=100. Then ess_tdof_list = [1,2,3,6,101,102,103,104].

Is this feasible? And, is there any more elegant way to achieve this? Furthermore, when I use parallel, does it still work?

Thanks very much for any possible advice!

**Comment by NjJu1** [comment]
@bslazarov Thanks very much for your advice. However, I am new to MFEM and do not quite understand how to implement your suggestions. To be specific, my current method is like as follows:
`_fespaceu->GetEssentialTrueDofs(bdr_attr_is_ess_u, ess_tdof_listu);`
`_fespacev->GetEssentialTrueDofs(bdr_attr_is_ess_v, ess_tdof_listv);`
`ess_tdof_list.SetSize(ess_tdof_listu.Size()+ess_tdof_listv.Size());`
`for ... loop to copy the data in ess_tdof_listu and ess_tdof_listv to ess_tdof_list with shift`
`x.SetSize(u.Size()+v.Size());`
`for ... loop to copy the data in u,v to Vector x`
`for ... loop to obtain Vector b from the linearForms`
`darcyOp->FormLinearSystem(ess_dof_list, x, b, MatLeft, trueX, trueRhs);`
where u, v are the ParGridFunction after the projection of boundary condition, trueX, trueRhs are vectors of length equals to the sum of u,v' s TrueVSize().

Do you mean that here x, b should be block vectors and ess_dof_list should also be some block form? But I have not found a way to block a Array<int> and apply GetEssentialTrueDofs to it which automatically adds the shift.

**Comment by bslazarov** [comment]
Hi,

I don't use FormLinearSystem.

I am using something like:
//get the true dof list

vfes->GetEssentialTrueDofs(ess_bdr,ess_tdofv);
pfes->GetEssentialTrueDofs(ess_bdr,ess_tdofp);

//get the block operator - in your case this will be the block matrix

mfem::BlockOperator& A=nf->GetGradient(sol);


//extract the matricesmfem::HypreParMatrix*
A00=static_cast<mfem::HypreParMatrix*>(&(A.GetBlock(0,0)));mfem::HypreParMatrix*
A01=static_cast<mfem::HypreParMatrix*>(&(A.GetBlock(0,1)));mfem::HypreParMatrix*
A10=static_cast<mfem::HypreParMatrix*>(&(A.GetBlock(1,0)));mfem::HypreParMatrix*
A11=static_cast<mfem::HypreParMatrix*>(&(A.GetBlock(1,1)));


//eliminate Rows/Colsmfem::HypreParMatrix*
A00elim=A00->EliminateRowsCols(ess_tdofv);mfem::HypreParMatrix*
A11elim=A11->EliminateRowsCols(ess_tdofp);mfem::HypreParMatrix*
A01elim=A01->EliminateCols(ess_tdofp);
A01->EliminateRows(ess_tdofv);mfem::HypreParMatrix*
A10elim=A10->EliminateCols(ess_tdofv); A10->EliminateRows(ess_tdofp);


//set BC to RHS
for(int ii=0;ii<ess_tdofv.Size();ii++){
    rhs.GetBlock(0)[ess_tdofv[ii]]=0.0; //block 0!!!}

//same goes for the pressure space tdofp however it will be for GetBlock(1)


The above is copy paste from my code - so you will have to adapt it
for your needs.


//Do not forget to delete the *elim matrices
//you can use them for setting the rhs side for Dirichlet bc different
than zero delete A00elim; delete A11elim; delete A10elim; delete
A01elim;

**Comment by NjJu1** [comment]
@bslazarov Hi, thanks for your sharing your method. It is very clear and is also a very good method.
