### ISSUE TITLE
linalg/hypre.cpp line 1548: cannot convert

### ISSUE THREAD

**Issue by goinea** [mfem/mfem#2597]
The error claims that there cannot be a conversion from ‘mfem::Array<int>’ to ‘hypre_IntArray*’
 specifically for CF_marker which is still identified as mfem::Array<int> even though it was initialized as hypre_IntArray. The updated code in https://github.com/mfem/mfem/blob/1361e3907d00583b42bff44997c5b70f56b47c4c/linalg/hypre.cpp works for me when compiling in serial except for this line. Is there a fix?
Thanks,
Adam

**Comment by goinea** [comment]
> This issue should be resolved in the `master` branch of MFEM.

I cloned into the master and still had issues. I was able to get most things to function until attempting to "make  parallel" and continue to get: linalg/superlu.cpp:20:10: fatal error: superlu_defs.h: No such file or directory
   20 | #include "superlu_defs.h"
When searching for the file, I do not see anything but https://github.com/mfem/mfem/blob/a4f5cc53ca87d60795f85f36401789932c98409c/config/cmake/modules/FindSuperLUDist.cmake . Any tips?

**Comment by v-dobrev** [comment]
It looks like you are enabling the external library SuperLU_DIST which is disabled by default. Check the config files `config/defaults.mk` and `config/user.mk` (optional, if you created it) if you accidentally set `MFEM_USE_SUPERLU` to `YES`. Here is where the default value is set: https://github.com/mfem/mfem/blob/4bcbff0a57bde835bdc3d65a7c1d97e0893db200/config/defaults.mk#L127

**Comment by goinea** [comment]
Got it, thanks.
