### ISSUE TITLE
Compilation error with SuiteSparse

### ISSUE THREAD

**Issue by maxenceR** [mfem/mfem#26]
Hello,

I am trying to compile MFEM with the flag MFEM_USE_SUITESPARSE ?= YES.
The SUITESPARSE_DIR variable is set to the right directory. I am using the last SuiteSparse sources (v4.4.5), available at http://faculty.cse.tamu.edu/davis/suitesparse.html

The compilation error is (using make serial) : 

> In file included from linalg.hpp:33:0,
>                 from solvers.cpp:12:
> solvers.hpp:23:21: fatal error: umfpack.h: No such file or directory
> #include < umfpack.h >

MFEM is looking for headers in SuiteSparce_DIR/include but there is no such folder in my SuiteSparse directory. The headers for UMFPACK are in SuiteSparse/UMFPACK, the headers for AMD are in SuiteSparce/AMD etc...

One "working" solution I have found is to add many symlinks in my SuiteSparse directory but this is not really clean.

Am I doing something wrong or the current MFEM makefile was designed to work with other or older versions of the SuiteSparse library ?

Thank you for your help, and thank you for providing MFEM, this is an awsome FEM library !

**Comment by martemyev** [comment]
Hi maxenceR,
The typical practice for the libraries is to collect all the header files in one 'include' directory after you 'install' the library. I believe this is the case for SuiteSparse as well. Here is a paragraph from the README.txt:
```
(6) To install, type "sudo make install".  This will place copies of all 
    libraries in /usr/local/lib, and all include files in /usr/local/include.
    You can change the install location by editting SuiteSparse_config.mk.
    These directories must already exist.
```
So, you might want to set up the proper install locations in the SuiteSparse_config.mk and 'make install'.

Best,
Mikhail

**Comment by maxenceR** [comment]
Yes you are right I did not install SuiteSparse. Now it works perfectly, thank you !
Maxence
