### ISSUE TITLE
Neumann Condition in the Example 8

### ISSUE THREAD

**Issue by LeilaSalomon** [mfem/mfem#2604]
Hello :)

I would like to use the Discontinuous Petrov-Galerkin (DPG) method, explained in Example 8, to solve `Div.(1/A*Grad(p)) = 0`. 

My main problem at the moment is the boundary conditions, I have not the same as the Example 8. In my case, I apply a homogeneous Dirichlet condition on one of the boundary, a non-homogeneous Neumann condition on another, and finally homogeneous Neumann conditions on the others.

I tried to modify the next line :

`ess_bdr = 1` to `ess_bdr = 0; ess_brd[0] = 1` to determine the boundary with the Dirichlet condition.

And I add on the `LinearForm`:

`F.AddBdrFaceIntegrator`(new BoundaryLFIntegrator(m_nbcCoef), nbc_bdr);

With `nbc_bdr` that indicate the  boundary with non-homogeneous Neumann condition, and `m_nbcCoef` the value.

By modifying in this way, I don't have the desired results.

**Comment by pazner** [comment]
Thanks for the answer, @psocratis! @LeilaSalomon, feel free to re-open if you have any other issues.
