### ISSUE TITLE
Debug the source code

### ISSUE THREAD

**Issue by BEMfreshman** [mfem/mfem#262]
Hi,
I am a new comer and student who want to learn FEA programming.
I consider that MFEM is lightweight FEM library and want to debug the example code to find out how it works.Of course, it will extremely help me understand the FE formulation,boundary condition and so on.
Can anybody give me some advice to achieve this goal?
PS: My OS is arch linux 64 bit.
Thanks.

**Comment by BEMfreshman** [comment]
Now, I have compiled library and get libmfem.a.
But I want to debug the MFEM source code directly without any library archive.

**Comment by jakubcerveny** [comment]
Hi,

First you need to have some idea about the basic theory, there's many great
books on that (e.g., Claes Johnson: Numerical Solution of Partial
Differential Equations by the Finite Element Method; or, Pavel Solin:
Partial Differential Equations and the Finite Element Method).

Then you can compile the serial debug version of MFEM (make debug) and run
Example 1 (examples/ex1.cpp) in a debugger like gdb (I personally prefer
cgdb or even the gdb front-end inside QtCreator).

Good luck!

Jakub

**Comment by BEMfreshman** [comment]
Thanks for your reply.
I have tried and it works well.
I think your advice and solution will help me a lot.
Thanks again.
