### ISSUE TITLE
Configurations in the hyperelasticity formulation unclear

### ISSUE THREAD

**Issue by termi-official** [mfem/mfem#2624]
I have some questions on the utilized formulation in the hyperelastic integrators. If you have a reference here I am happy to read it - if not here my questions (I will leave some references to "Aubram, Daniel. Differential geometry applied to continuum mechanics. Shaker, 2009." in the case something might not be clear, because the utilized formulation and notation seems to be different from the standard one in continuum mechanics)

Three configurations appear in the nonlinear form integrators: reference, target and physical (https://github.com/mfem/mfem/blob/9d8043b9e78dcdcd86639bbb28d3bd7b514fb5e2/fem/nonlininteg.hpp#L293-L296). I think the reference configuration is clear as being the undeformed state. For the target and physical configuration, I am not sure what they refer to, but I assume that the physical configuration is the deformed state and we utilize the target configuration for some (stress-free?) intermediate configurations (https://github.com/mfem/mfem/blob/9d8043b9e78dcdcd86639bbb28d3bd7b514fb5e2/fem/nonlininteg.hpp#L308-L309) ? Or is the reference configuration more something like the material configuration, the physical configuration what is usually called the "reference" configuration and the target configuration the "deformed" configuration? (c.f. "Aubram, Daniel. Differential geometry applied to continuum mechanics. Shaker, 2009.", page 66, figure 4.1).

Depending on the answer I have another question on the NeoHookean formulation. Refering to the lines https://github.com/mfem/mfem/blob/9d8043b9e78dcdcd86639bbb28d3bd7b514fb5e2/fem/nonlininteg.hpp#L261 and https://github.com/mfem/mfem/blob/9d8043b9e78dcdcd86639bbb28d3bd7b514fb5e2/fem/nonlininteg.cpp#L291-L294 what exactly is the reference volume scaling `g`?

**Comment by termi-official** [comment]
Thanks for the response @jamiebramwell and @rcarson3 ! I also took a look into the serac implementation for hyperelasticity and it is really nice. 

So, by reference coordinate/master element you mean simply the element with its coordinates in the input mesh and "target" is the configuration in which we start to deform our object?

**Comment by vladotomov** [comment]
I believe these are as follows:

- Reference coordinates - coordinates of the reference finite element (like `[0,1]x[0,1]` for a ref quad).
- Target coordinates - coordinates of the current mesh, given by the `ElementTransformation &Ttr` argument  in all methods.
- Physical coordinates - coordinates given by `const Vector &elfun` in all methods.
