### ISSUE TITLE
User defined source term for the Navier-Stokes solver

### ISSUE THREAD

**Issue by Watchmojo** [mfem/mfem#2630]
Hi,

In the current implementation of NS solver, simple source term in the form of a constant pressure gradient is added. However, for the turbulence model in the context of LES/RANS, a more complex source term needs to be used. 

Is it possible to provide an interface/functionality for user to add source term for the Navier-Stokes (NS) solver? In this interface/functionality, the velocity and velocity gradient in physical space are better to be provided, so that the user can construct different forms of source terms for the NS solver. 

Thanks

**Comment by jandrej** [comment]
Can you provide an example what kind of source term you'd want to use? Then I can check if it is already possible or if there is an interface restriction.

**Comment by Watchmojo** [comment]
> Can you provide an example what kind of source term you'd want to use? Then I can check if it is already possible or if there is an interface restriction.

For instance, in the momentum equation of u_i in LES, the source term is \nu_t |S_{ij}| \partial (S_{ij}}/ \partial x_j, where \nu_t is a user-specified field variable and S_{ij} = (\partial u_i/\partial x_j + \partial x_j / \partial x_i)/2

**Comment by jandrej** [comment]
You can get the current velocity as a `GridFunction`. You can then specify your own `Coefficient` to compute `S_{ij}`. I don't see restrictions of the interface that won't allow that.
