### ISSUE TITLE
How to optimise a MFEM based implementation for OpenMP parallelism?

### ISSUE THREAD

**Issue by TobiasDuswald** [mfem/mfem#2635]
**Dear MFEM team,**

we're working on a software project called [BioDynaMo](https://github.com/BioDynaMo/biodynamo) which can be used for agent based modelling. We wanted to extend our support for continuum modelling, e.g. diffusion equations, and we decided to try with MFEM because of the great flexibility it offers. BioDynaMo is currently parallelised with OpenMP and scales well on the node level. I see that MFEM scales to significantly larger systems by leveraging MPI. However, combining an OpenMP parallelised BioDynaMo and a MPI parallelised MFEM sounds problematic and will probably give me a headache . (In case you think this is a rather trivial problem, please correct me.)

## Application example

One possible application is to simulate a simple diffusion equation (e.g nutrients) and having cells interacting with the continuum. For the continuum, we'd use MFEM & the method of lines (similar to ex16) to compute a nutrient concentration over time. The agent-based model for the cells is handled by BioDynaMo fully parallel with OpenMP and every few time steps we'd update the continuum. We'd like these updates to be as efficient as possible. 

## Current understanding

To my current understanding, MFEM can be compiled with `MFEM_USE_LEGACY_OPENMP` but from other posts (e.g #1175) and the flag's name I conclude that this is legacy code and not the ideal way to use it. I also saw that MFEM can interface with `Ginko` and `hyper` that feature OpenMP based solvers and preconditioners to my understanding. The remaining solvers and preconditioners seem to be either serial or MPI parallelised. **So from my perspective, the natural choice seems to be to set `MFEM_USE_LEGACY_OPENMP` and use solvers from the `Ginko` or `hyper` library.**

## Question:

Anyways, all of this leads me to the following question. **How would I optimise an implementation based on MFEM to efficiently use a full compute node (NUMA node) without using MPI?** Does my reasoning above make sense or not? Since you certainly know your software environment significantly better than I do I'd be very happy about any other further comments regarding that issue. :)

Thank your, greatly appreciate your help!
Tobias

**Comment by v-dobrev** [comment]
The best approach is probably to enable `MFEM_USE_OPENMP=YES` when configuring MFEM, and (at runtime) configure a `Device` using the `"omp"` backend (similar to the way we handle the `-d`/`--device` option in examples, e.g. in `ex1.cpp`). If you don't need to reassemble the diffusion matrix many times, you can use default `AssemblyLevel::LEGACY` of the `BilinearForm` (can be switched with `BilinearForm::SetAssemblyLevel`). This way the assembly is not parallelized but that is just a setup cost. If you do need to reassemble many times, then one can enable `AssemblyLevel::FULL` which will use OpenMP parallelism, however, it has limitations at the moment -- e.g. it only supports quad and hex meshes.

For solving, as a first step, you can use PCG + Jacobi preconditioning as illustrated in `ex1.cpp`: https://github.com/mfem/mfem/blob/167ff72edccc4e5b0a642ae3392ccaf50f455b9e/examples/ex1.cpp#L228-L229

Beyond that you can try Ginkgo (see `examples/ginkgo/ex1.cpp`), UMFPACK (see `examples/ex1.cpp` and `mfem::UMFPackSolver` -- I've never used it with OpenMP but I believe it is possible), or HYPRE (to use MFEM's interface to HYPRE you'll need to build MFEM with MPI and then just run with 1 MPI rank).

**Comment by TobiasDuswald** [comment]
Thank you very much @v-dobrev, that was very very helpful. I'll try the different options that you suggested, and once I'm done (might take a while) I'll report my experiences here.
