### ISSUE TITLE
Dirichlet BCs for 3D displacement field

### ISSUE THREAD

**Issue by srwopschall** [mfem/mfem#264]
1. Are homogeneous Dirichlet BCs automatically enforced for all boundary attributes set to 1 in an attribute list? (i.e. condensed out of the system of equations?)

2. My problem uses a NewtonSolver object, for which a solution Vector x is passed to the Mult routine. What happens if this vector is pre-populated, including vector entries associated with essential dofs? Are these condensed out and assumed to be homogeneous essential dofs?

3. I want to enforce a time dependent vector valued function for nonzero Dirichlet BCs on a part of the boundary. How is this best accomplished?

**Comment by tzanio** [comment]
Thanks for the questions @srwopschall, here are some answers:

1. In principle yes, with two caveats: 
   - First, there is not condensation -- the degrees of freedom are _eliminated_ by deleting rows/columns, setting 1 on the diagonal and modifying the r.h.s ; 
   - Second, there are different ways to do this, but we recommend the `FormLinearSystem` interface, see e.g. `examples/ex1.cpp`, you _eliminate_ dofs obtained from `FiniteElementSpace::GetEssentialTrueDofs` based on marked array of boundary attributes.

2. The vector `x` will be passed to the `Mult()` and `GetGradient()` routines of the `Operator` you have set with `SetOperator`, see [Example 10](https://github.com/mfem/mfem/blob/master/examples/ex10.cpp).

3. See [Example 15](https://github.com/mfem/mfem/blob/master/examples/ex15.cpp), and in particular the objects involved in `x.ProjectBdrCoefficient(bdr, ess_bdr);`.

Hope this helps,
Tzanio

**Comment by srwopschall** [comment]
Tzanio,

Per your first bullet point in item 1, is the r.h.s. modified using the nonzero elements of the Vector x passed to, for example, FormLinearSystem() or in my case Mult()? Based on what I am seeing in Example 15 this appears to be the case, since the entire boundary has a specified nonzero Dirichlet BC per some analytic scalar value function (if I'm not mistaken). 

If the above is true, it would seem as though a dof with a homogeneous Dirichlet BC should have an entry of 0 in x that is passed to, e.g. FormLinearSystem(). 

Ultimately, I'm trying to distinguish how zero and nonzero Dirichlet BCs are distinguished. Per Example 15, it would seem as though the projection of the boundary function onto "x", which is then passed onto FormLinearSystem() is how this is achieved for nonzero homogeneous. Of course, I have both in my problem.

**Comment by tzanio** [comment]
> Per your first bullet point in item 1, is the r.h.s. modified using the nonzero elements of the Vector x passed to, for example, FormLinearSystem() or in my case Mult()? Based on what I am seeing in Example 15 this appears to be the case, since the entire boundary has a specified nonzero Dirichlet BC per some analytic scalar value function (if I'm not mistaken).

Yes

> If the above is true, it would seem as though a dof with a homogeneous Dirichlet BC should have an entry of 0 in x that is passed to, e.g. FormLinearSystem().

Yes

> Ultimately, I'm trying to distinguish how zero and nonzero Dirichlet BCs are distinguished. Per Example 15, it would seem as though the projection of the boundary function onto "x", which is then passed onto FormLinearSystem() is how this is achieved for nonzero homogeneous. Of course, I have both in my problem.

Yes. The distinction is between Dirichlet (essential) and non-Dirichler (natural) degrees of freedom. You can encode them with different boundary attributes if you want, but there is no distinction between zero and nonzero Dirichlet BCs.

**Comment by stefanozampini** [comment]
@srwopschall an alternative to the `FormLinearSystem` interface is to use `PetscNonlinearSolver` with  a `PetscBCHandler` object. The PetscNonlinearSolver will handle the entire process of eliminating rows and cols, sampling jacobians with the correct Dirichlet values etc, see https://github.com/mfem/mfem/blob/master/linalg/petsc.cpp#L3114

If you have a time-dependent nonlinear problem, you can use a `PetscODESolver` with a `PetscBCHandler`

**Comment by tzanio** [comment]
Resolving after speaking with @srwopschall in person.
