### ISSUE TITLE
Evaluate surface integral over periodic boundary

### ISSUE THREAD

**Issue by Andr00dz** [mfem/mfem#2640]
Hi,

I have a velocity stored in a `GridFunction` and want to evaluate a surface integral over a periodic "boundary" in each time step of my simulation. I did a similar things before in a non-periodic setting with `BoundaryNormalLFIntegrator`, but there I had access to boundary attributes.

MFEM removes the boundary attribute flags on periodic boundaries.
My current approach to solve this issue (motivated in https://github.com/mfem/mfem/issues/1721#issuecomment-685988891) looked like this:

- Mark faces that lie on the periodic boundary and then use later `BoundaryNormalLFIntegrator`:

```
 mfem::Array<int> faceVertices(0);
 for(int i = 0; i < pmesh->GetNumFaces(); i++)
 {
    pmesh->GetFaceVertices(i,faceVertices);
    // check if face is on periodic boundary (x==0)
    const double* v0Coords = pmesh->GetVertex(faceVertices[0]);
    const double* v1Coords = pmesh->GetVertex(faceVertices[1]);
    if ((v0Coords[0]+v1Coords[0])/2.0 < 1e-5)
      pmesh->SetBdrAttribute(i,3);
}
```
It seems that the faces I'm looking for do not even appear for np=1 in the above mentioned for-loop.
When I loop over the vertices of the mesh with 
```
for(int i = 0; i<pmesh->GetNV(); i++)
{
   const double* v0Coords = pmesh->GetVertex(i);
   std::cout << "(" << v0Coords[0] << ",\t" << v0Coords[1] << ")" << std::endl;
}
```
some vertices are listed twice and vertices on the periodic "boundary" do not appear for np=1.
However, looking at my simulation results in ParaView, the periodic "boundary" is still there.

Currently I use this [mesh](https://pastebin.com/raw/aKADpSVT) for debugging. 
Is my approach even correct or are there better ways for integrating over the periodic "boundary"?

**Comment by Andr00dz** [comment]
I seems that commenting out the following section, fixes all my problems.
https://github.com/mfem/mfem/blob/d6924d1b3f9a758f0f828c9512379a575b9e6a9e/mesh/mesh_readers.cpp#L2744-L2747
I compared my simulation with and without this section and the results were the same.

Is it safe to leave this commented out or can it result in unintended behavior in mfem?

**Comment by v-dobrev** [comment]
Hi @Andr00dz, I think you may be right -- calling `this->RemoveInternalBoundaries()` is probably unnecessary -- we do want to be able to preserve such internal "boundaries" when they are defined in the mesh file.

@mlstowell, it looks like you added this call initially in commit 80d15335 and later modified it in 9a6954b9. Do you remember if this was really necessary for some reason?

**Comment by mlstowell** [comment]
> Hi @Andr00dz, I think you may be right -- calling `this->RemoveInternalBoundaries()` is probably unnecessary -- we do want to be able to preserve such internal "boundaries" when they are defined in the mesh file.
> 
> @mlstowell, it looks like you added this call initially in commit [80d1533](https://github.com/mfem/mfem/commit/80d1533590b4a966758462bf989b0ebd78a2ebbf) and later modified it in [9a6954b](https://github.com/mfem/mfem/commit/9a6954b9578012b8d41498529bce2db7f5103e31). Do you remember if this was really necessary for some reason?

I believe this was done so that periodic meshes could be used with some of the example codes (ex1p, ex11p, etc.) which apply homogeneous Dirichlet BCs on "all" boundaries.  We could have altered these examples to allow the boundaries to be assigned on the command line but we wanted to keep them as simple as possible.

I wouldn't say this removal is "really necessary" but it does have broader impact. 

I think the correct long term solution would be to distinguish between boundaries and internal surfaces in the mesh class. In such cases the mesh reader could be altered to reassign internal "boundaries" as "internal surfaces" rather than simply removing them.

**Comment by v-dobrev** [comment]
I think a simple solution for the examples will be to add a call to a new mesh method that un-marks internal boundaries from a given boundary-attribute-marker array. This should be simple 1-line addition to the relevant examples.

**Comment by Andr00dz** [comment]
Thanks for the comments. An "internal surface"-feature in the future would be great. From my perspective, this issue can be closed now.
