### ISSUE TITLE
Channel Flow: (IsFinite(nom)) is false:

### ISSUE THREAD

**Issue by goinea** [mfem/mfem#2641]
@jandrej I am running on an HPC with 10 nodes on 400 cores and after about t =6 I get an:
Assertion failed: (IsFinite(nom)) is false:
--> nom = inf
... in function: virtual void mfem::CGSolver::Mult(const mfem::Vector&, mfem::Vector&) const
... in file: /gpfs/u/home/ODLC/ODLCgnsd/barn/dcs/mfem/linalg/solvers.cpp:643

This was the first version of the turb_channel code sent, would using the newest one fix this? Did you get this error?

**Comment by jandrej** [comment]
I think using the newest version should fix it, yes. It is probably just the timestep that you have to reduce.
