### ISSUE TITLE
Build failure on macOS 11.6

### ISSUE THREAD

**Issue by TobiasDuswald** [mfem/mfem#2642]
Dear MFEM team,

as recommended in #2635, I tried to build MFEM with `-DMFEM_USE_OPENMP=YES` but it failed on macOS 11.6.

## Steps to replicate 

```bash
git clone https://github.com/mfem/mfem.git
cd mfem 
mkdir build
cd build
cmake -DMFEM_USE_OPENMP=ON ..
make -j8
```

## Error message 

```bash
[ 21%] Building CXX object CMakeFiles/mfem.dir/linalg/vector.cpp.o
/usr/bin/clang++ -DMFEM_CONFIG_FILE=\"/Users/usr/mfem/build/config/_config.hpp\"  -Xclang -fopenmp -g -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk -mmacosx-version-min=11.6 -std=c++11 -MD -MT CMakeFiles/mfem.dir/linalg/vector.cpp.o -MF CMakeFiles/mfem.dir/linalg/vector.cpp.o.d -o CMakeFiles/mfem.dir/linalg/vector.cpp.o -c /Users/usr/mfem/linalg/vector.cpp
/Users/usr/mfem/linalg/vector.cpp:26:10: fatal error: 'omp.h' file not found
#include <omp.h>
         ^~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/mfem.dir/linalg/vector.cpp.o] Error 1
make[1]: *** [CMakeFiles/mfem.dir/all] Error 2
make: *** [all] Error 2
```

## System Info

- macOS 11.6 (Apple silicon / M1)
- Xcode 13.1
- `libomp` installed via brew

## Possible Fix

In `CMakeLists.txt:255`, I just added one line marked here with `(+)`

```cmake
# OpenMP
if (MFEM_USE_OPENMP OR MFEM_USE_LEGACY_OPENMP)
  if (NOT MFEM_THREAD_SAFE AND MFEM_USE_LEGACY_OPENMP)
    message(FATAL_ERROR " *** MFEM_USE_LEGACY_OPENMP requires MFEM_THREAD_SAFE=ON.")
  endif()
  find_package(OpenMP REQUIRED)
  set(OPENMP_LIBRARIES ${OpenMP_CXX_LIBRARIES})
  include_directories(${OpenMP_CXX_INCLUDE_DIRS})   (+)
endif()
```

Introducing the single line above solved the issue for me and MFEM compiled fine. I also ran `ex1.cpp` with the different device options `cpu` and `omp` with the latter being faster. This leads me to the assumption that it works fine. Anyways, I'm not so familiar with your build system so I'm not sure if this has any unwanted side effects or if further modifications have to be made at different places as well.

## Misc information

- I tried the original version (without `(+)` modification) on Ubuntu 20.04 (inside docker) and everything worked fine, no issues with building MFEM with `-DMFEM_USE_OPENMP=YES` at all.
- I embedded MFEM in our build system via Cmake's `ExternalProject_Add` requesting `-DMFEM_USE_OPENMP=YES` as well using MFEM's `v4.3` release. It worked fine on Ubuntu 18.04, Ubuntu 20.04, CentOS 7 but failed on macOS (11.6 - intel based) in the GitHub Actions. 

Let me know if I can help somehow.

**Comment by v-dobrev** [comment]
Typically, just adding the flag `-fopenmp` (or equivalent) is sufficient since the compiler knows it needs to add the paths to OpenMP headers.

In the case of Apple's Clang, I did not know you can even use OpenMP -- I thought it is not supported. I guess you found a way. 😁 

In any case, I think your solution makes sense and it won't break other configurations, so feel free to submit a PR to add it. Thanks!

**Comment by TobiasDuswald** [comment]
Maybe the lack of OpenMP support is the reason for the compiler having a hard time finding the header(s). On my machine they are located in `/opt/homebrew/include` after `brew install libomp` - probably this is not a path that the compiler uses by default. I submitted a PR #2645 addressing this issue.

**Comment by tzanio** [comment]
Discussion continued in #2645
