### ISSUE TITLE
2D periodic mesh from Gmsh

### ISSUE THREAD

**Issue by tangqi** [mfem/mfem#2644]
Hi, 
I am trying to create a 2D periodic mesh for testing. I use the following simple geometry:
SetFactory("OpenCASCADE");
Rectangle(1) = {0, 0, 0, 1, 1, 0};
Periodic Curve {2} = {1} Translate {1, 0, 0};

But it complains about the mesh:
```
MFEM abort: Gmsh file : vertices indices are not unique
 ... in function: void mfem::Mesh::ReadGmshMesh(std::istream &, int &, int &)
 ... in file: mesh/mesh_readers.cpp:1593
```
Is there a mistake in this gmsh geometry? Basically, I want to get a periodic boundary condition in one direction (but in triangular). 

If there is a simple work-around, please let me know. Thanks.

Qi

**Comment by pazner** [comment]
The following works for me (Gmsh version 4.8.4). The issue2644.geo file is:
```
SetFactory("OpenCASCADE");
Rectangle(1) = {0, 0, 0, 1, 1, 0};
Periodic Curve {3} = {1} Translate {0, 1, 0};
Mesh.MshFileVersion = 2.2;
Mesh 2;
```
(note that the periodic curve indices are slightly different from yours). I generate the issue2644.msh file with `gmsh -save issue2644.geo`.

Running `ex1` with the resulting mesh works, and the y=0 and y=1 boundaries are periodic:

![GLVis_s01](https://user-images.githubusercontent.com/11493037/140426797-2860834c-73df-410a-9335-cb3413350a25.png)
:

**Comment by tangqi** [comment]
Thanks a lot. It looks like I had an error in my gmsh file. This works well.
