### ISSUE TITLE
Possible issue with BilinearForm::AddDomainIntegrator with marker

### ISSUE THREAD

**Issue by sebastiangrimberg** [mfem/mfem#2646]
I ran into an issue using a mesh with non-contiguous domain attribute tags and think the culprit is this check in `BilinearForm::Assemble`:

```
 if (domain_integs_marker[k] != NULL)
 {
    MFEM_VERIFY(mesh->attributes.Size() ==
                domain_integs_marker[k]->Size(),
                "invalid element marker for domain integrator #"
                << k << ", counting from zero");
 }
```

I think the correct behavior would be to check `mesh->attributes.Max()`. 

The boundary integrators with marker have a correct check that works with non-contiguous attributes, see the code starting at [this line](https://github.com/mfem/mfem/blob/167ff72edccc4e5b0a642ae3392ccaf50f455b9e/fem/bilinearform.cpp#L485).

**Comment by v-dobrev** [comment]
I think you are right, there is an inconsistency in how `domain_integs_marker[k]` is used here (A): https://github.com/mfem/mfem/blob/167ff72edccc4e5b0a642ae3392ccaf50f455b9e/fem/bilinearform.cpp#L438-L439 and the check here (B): https://github.com/mfem/mfem/blob/167ff72edccc4e5b0a642ae3392ccaf50f455b9e/fem/bilinearform.cpp#L418-L421 and also the documentation here (C): https://github.com/mfem/mfem/blob/167ff72edccc4e5b0a642ae3392ccaf50f455b9e/fem/bilinearform.hpp#L94-L98
Basically, (B) and (C) are wrong and the size of `domain_integs_marker[k]` (when not `NULL`) should be `mesh->attributes.Max()` or 0 if `mesh->attributes` is empty.

There is a similar issue in `LinearForm`, here: https://github.com/mfem/mfem/blob/167ff72edccc4e5b0a642ae3392ccaf50f455b9e/fem/linearform.cpp#L123-L126 and in the documentation here: https://github.com/mfem/mfem/blob/167ff72edccc4e5b0a642ae3392ccaf50f455b9e/fem/linearform.hpp#L36-L40

Thank you for reporting this issue. Would you like to propose a PR to fix it?

**Comment by sebastiangrimberg** [comment]
Great, that's what I thought. Happy to go and make a PR, I should be able to do this next week. Thanks for checking those other spots!

**Comment by tzanio** [comment]
Discussion continued in #2648
