### ISSUE TITLE
Use MatrixFreeAMS for nonlinear problems

### ISSUE THREAD

**Issue by tuckerbabcock** [mfem/mfem#2653]
Hi all,

I'm wondering what it would take to be able to use the `MatrixFreeAMS` preconditioner for nonlinear problems? 

After taking a quick look, it seems like the parts of the preconditioner unique to linear problems are constructing the `OperatorJacobiSmoother` with a `BilinearForm` and the assumption that the `Operator` will not change. It also looks like the `MatrixFreeAuxiliarySpace` constructors also use `BilinearForm`s, so I suspect those would need to change too since the diffusion coefficient would depend on the ND state for the nonlinear problem.

Have I missed anything?

Thanks!

**Comment by tzanio** [comment]
Hi Tucker,

Do you want to define a non-linear preconditioner for your problem? If not, you should need AMS only to precondition the linearization during Newton, which is just a regular linear system for the Jacobian... Am I missing something?

Tzanio

**Comment by tuckerbabcock** [comment]
No, you're right that I just want to precondition the linearization during a Newton step. My concerns are that the `MatrixFreeAMS::SetOperator` doesn't so anything meaningful, so the operator it preconditions would not be updated during the Newton steps. I know that sometimes you can get away with that, but I believe I saw degraded performance in a quick experiment I did testing that (where I made it so the linear solver didn't call `SetOperator` on its preconditioner). Also, there is the practical concern of the constructor taking a `BilinearForm` which I don't have in my nonlinear problem. 

I'm still a ways away from trying to use the `MatrixFreeAMS` since I haven't written any nonlinear integrators that support partial assembly or matrix free assembly, so I'm just trying to understand what it would take to get me to that point where I could use it.

**Comment by tzanio** [comment]
If the operator changes, you will have to rebuild the preconditioner.

Currently that means destroying and recreating the `MatrixFreeAMS` object, but we can add an `Update` method that reuses some of its components, e.g. the `G` and `Pi` operators if the mesh doesn't change.

**Comment by tuckerbabcock** [comment]
I see. Thanks! I'll have to think more about this.
