### ISSUE TITLE
Linear Form Integrators

### ISSUE THREAD

**Issue by L29430** [mfem/mfem#2654]
Hello :)

In my equation that I solve, I have a source term `alpha`.

I would like to use a linear domain integrator, with the following continue form: `lambda*d(alpha)/dx`. Is it possible ?

Best,

LS

**Comment by wcdawn** [comment]
Does `alpha` have a derivative you can compute by hand? That would obviously be your best option.
Otherwise, I'm not sure I understand the question. In general space, this would be something like `grad(alpha)` which is a vector quantity. Maybe you need something like a `DomainLFGradIntegrator` and an inner-product?

**Comment by L29430** [comment]
Hello, yes you are right ! I will solve `grad(alpha)`, thank you !! Huum, `DomainLFGradIntegrator` calculate the divergence of alpha no ?

**Comment by wcdawn** [comment]
`DomainLFGradIntegerator` evaluates the integral

<img src="https://i.upmath.me/svg/%20%5Cint%20%5Cmathbf%7Bf%7D%20%5Ccdot%20%5Cnabla%20u%20%5C%3B%20dx%20" alt=" \int \mathbf{f} \cdot \nabla u \; dx " />

where <img src="https://i.upmath.me/svg/%5Cmathbf%7Bf%7D" alt="\mathbf{f}" /> is a `VectorCoefficient` and <img src="https://i.upmath.me/svg/u" alt="u" /> is a `GridFunction` that you are solving for.

What is the form of `alpha`? Is it a `GridFunction`? A `Coefficient`? Is `alpha` scalar valued or vector valued?

**Comment by L29430** [comment]
`alpha` is a Gridfunction and it is a scalar. I'm not sure to understand, f is the test function ?

**Comment by wcdawn** [comment]
Sorry for the confusion. Yes,

**Comment by L29430** [comment]
Why wouldn't I use `VectorDomainLFIntegrator` instead? :

```
LinearForm lf{/*fespace*/};
GridFunction alpha{/*fespace*/};
GradientGridFunctionCoefficient grad_alpha_coeff{&alpha};
lf.AddDomainIntegrator(new VectorDomainLFIntegrator{grad_alpha_coeff});
```

**Comment by wcdawn** [comment]
`VectorDomainLFIntegrator` would be for a vector test function. You would have `vdim > 1` when declaring the `FiniteElementSpace`.

<img src="https://i.upmath.me/svg/%20%5Cint%20%5Cnabla%20%5Calpha%20%5Ccdot%20%5Cmathbf%7Bv%7D%20%5C%3B%20d%5Cmathbf%7Bx%7D%20" alt=" \int \nabla \alpha \cdot \mathbf{v} \; d\mathbf{x} " />

`DomainLFGradIntegrator` would be for integrating the gradient of the test function. This would be if both `alpha` and your `FiniteElementSpace` are scalars.

<img src="https://i.upmath.me/svg/%20%5Cint%20%5Cnabla%20%5Calpha%20%5Ccdot%20%5Cnabla%20v%20%5C%3B%20d%5Cmathbf%7Bx%7D%20" alt=" \int \nabla \alpha \cdot \nabla v \; d\mathbf{x} " />

**Comment by L29430** [comment]
Ok, my unknown is a vector, so I'm working with a vector space, so I have to use `VectorDomainLFIntegrator` no ?

**Comment by wcdawn** [comment]
Sounds like it but it really depends on what you're trying to calculate.
Your weak form either has a derivative on the test function or not.

**Comment by wcdawn** [comment]
Is unrelated to the original question but you can see how `VectorDivergenceIntegrator` is used in the Navier miniapp in `miniapps/navier/navier_solver.cpp`. You need to use a `MixedBilinearForm` as the trial and test functions are in different spaces. If you have other questions, you can open a new issue.

**Comment by L29430** [comment]
Thank you for you help ! :)
