### ISSUE TITLE
Is it possible to compile the codes on Windows 10?

### ISSUE THREAD

**Issue by SamaHans** [mfem/mfem#2662]
Or MFEM can only be used on Linux?

**Comment by v-dobrev** [comment]
Yes, you can build MFEM on Windows in various ways: with Visual Studio, cygwin, MINGW, or under WSL. For example with Visual Studio you can use the CMake build system: https://github.com/mfem/mfem/blob/0843a87d7953cf23e556dcfd426d27bd9cfb3e21/INSTALL#L787-L788 https://github.com/mfem/mfem/blob/0843a87d7953cf23e556dcfd426d27bd9cfb3e21/INSTALL#L820 https://github.com/mfem/mfem/blob/0843a87d7953cf23e556dcfd426d27bd9cfb3e21/INSTALL#L833 https://github.com/mfem/mfem/blob/0843a87d7953cf23e556dcfd426d27bd9cfb3e21/INSTALL#L841 https://github.com/mfem/mfem/blob/0843a87d7953cf23e556dcfd426d27bd9cfb3e21/INSTALL#L852-L853 https://github.com/mfem/mfem/blob/0843a87d7953cf23e556dcfd426d27bd9cfb3e21/INSTALL#L865
