### ISSUE TITLE
How can I get the ID of nodes in an element

### ISSUE THREAD

**Issue by HaoWangCase** [mfem/mfem#2665]
Hi guys,

Right now I am confused about how to get the ID of all the nodes in an element. I understand that for an element with the order of 1, we can use the function Element::GetVertices to obtain the ID of the vertices in an element. However, when the element is refined and has more nodes than the vertices, how can  I get the IDs of all the nodes (including the vertices) in a specific element?

Thanks.

**Comment by pazner** [comment]
You can use `FiniteElementSpace::GetElementVDofs` to get the DOF numbers associated with the element.

If you are specifically interested in the nodes of a mesh (i.e. defining the element curvature), you should call `Mesh::GetNodalFESpace` to get the relevant `FiniteElementSpace`. The mesh coordinates are stored in the nodal `GridFunction` that can be accessed with `Mesh::GetNodes`.

**Comment by HaoWangCase** [comment]
Hi @pazner,

Thanks for your clarification. I still have further thoughts. If the mesh is refined, do the original vertices in the mesh still have the same ID in the DOF numbers when you use the FiniteElementSpace::GetElementVDofs?

Thanks.

**Comment by pazner** [comment]
What do you mean "when the mesh is refined"? Do you mean if a high-order (curved) mesh is used, or do you mean actually refining the mesh (splitting elements into several smaller elements)? In either case, I don't believe it is guaranteed that the DOF numbers corresponding to the vertices will be the same as the vertex numbers.

Can you explain what you are trying to accomplish?
