### ISSUE TITLE
Questions about IntegrationPoint

### ISSUE THREAD

**Issue by Watchmojo** [mfem/mfem#2671]
I am trying to develop a simple function that integrates a ParGridFunction over the entire pmesh. 
Yes, ParLinearForm can be used to accomplish this simple task. I am developing some simple functions to get familiar with MFEM. 

The following function gives correct integral results, however, I do not understand:
1. why does the `IntegrationRule` of order `2 * fe->GetOrder() - 1`, instead of `fe->GetOrder()`; 
2. why `const IntegrationPoint &ip = ir->IntPoint(dof);` instead of `const IntegrationPoint &ip = fe->GetNodes().IntPoint(dof);`
3. why does `const IntegrationPoint &ip = fe->GetNodes().IntPoint(dof);` give 0 value for `ip.weight`

Thank you very much for your help. 
-----------------
>    double integ = 0.0;
   const FiniteElement *fe;
   ElementTransformation *T;
   Array<int> dofs;
   int elndofs;
   Vector vel;
   FiniteElementSpace *fes = u.FESpace();
   for (int i = 0; i < fes->GetNE(); i++){
      fes->GetElementVDofs(i, dofs);
      fe = fes->GetFE(i);
      T  = fes->GetElementTransformation(i);
      elndofs = fe->GetDof();
      const IntegrationRule *ir = &(gll_rules.Get(fe->GetGeomType(), 2 * fe->GetOrder() - 1));
      for (int dof = 0; dof < elndofs; dof++){
         const IntegrationPoint &ip = ir->IntPoint(dof);
//       const IntegrationPoint &ip = fe->GetNodes().IntPoint(dof);
         T->SetIntPoint(&ip);
         integ += u(dofs[dof]) * ip.weight * T->Weight();
      }
   }
   double global_integral = 0.0;
   MPI_Allreduce(&integ,
                 &global_integral,
                 1,
                 MPI_DOUBLE,
                 MPI_SUM,
                 u.ParFESpace()->GetComm());

**Comment by YohannDudouit** [comment]
Hi @Watchmojo ,
I think you are confused between the nodes of the basis functions associated to the [Lagrange polynomials](https://en.wikipedia.org/wiki/Lagrange_polynomial), and the quadrature points and weights associated with the [quadrature rule](https://en.wikipedia.org/wiki/Gaussian_quadrature).

**Comment by Watchmojo** [comment]
> Hi @Watchmojo , I think you are confused between the nodes of the basis functions associated to the [Lagrange polynomials](https://en.wikipedia.org/wiki/Lagrange_polynomial), and the quadrature points and weights associated with the [quadrature rule](https://en.wikipedia.org/wiki/Gaussian_quadrature).

Thank you for the clarification. I thought that the basis function
