### ISSUE TITLE
Noob question: How to get value of sim result (voltage in electrostatic sim) for a surface/element with known GMesh attr. ID

### ISSUE THREAD

**Issue by aalavi** [mfem/mfem#2672]
Hello,

I am using electromagnetic miniapp , specifically volta.cpp and used it to do an electrostatic sim. My mesh was generated with GMesh and sim was run successfully. I can load result and visualize it using GLVis or Paraview (.pvu generated also). 

All I need now is to extract values (voltages) on a particular surface with a known gmesh's attribute ID, preferably from data structures within the C++ sim. I don't have FE background and deciphering C++ library is not straightforward when I tried.

Any example or hint that you could point me to would be really appreciated.
Regards.

**Comment by mlstowell** [comment]
Hello, @aalavi, 

This is a good question but its answer is perhaps more complicated than it would appear. 

If you need voltages at a fixed number of locations which you know in advance then you can extract these voltages using code similar to that found in [get-values](https://github.com/mfem/mfem/blob/master/miniapps/tools/get-values.cpp).  This tool does not use the boundary attributes it simply searches the mesh for the elements containing the coordinates you provide. Clearly this can be expensive on a large mesh.

The more complicated answer involves looking at the problem as a finite element field. In the `volta` mini app the voltage is a continuous field so its precise value at any given point may not be that important. Certainly point-wise values will change as you refine your mesh and the solution becomes more accurate but such values will also be different on different meshes which use the same mesh spacing.  Perhaps the average voltage over some region would be more useful.

To compute the average voltage on a surface you can use a `LinearForm` object to integrate your solution field over the surface. You can use the same `LinearForm` to compute the area of the surface. The ratio of the two would then be the average voltage. Something very similar is done, in a more complicated manner, in [ex27p.cpp](https://github.com/mfem/mfem/blob/0843a87d7953cf23e556dcfd426d27bd9cfb3e21/examples/ex27p.cpp#L663).

I can probably give more details on either approach if these sound useful.

Best wishes,
Mark

**Comment by aalavi** [comment]
Thank you Mark for your response! 

The first approach I guess might suffice in my case. I have a floating (not connected to a voltage source) surface (sensing metal electrode) with Neumann boundary condition imposed on it in sim on which I would like to get the induced voltage on. It is metal so the whole surface should have identical voltage readout (or similar).

Simplified example would be a two-plate capacitor model with plates connected to voltages 0 and 100V, and I have my sense small metal plate somewhere to sense the induced voltage on it.

Would this example possibly help you elaborate a bit on proper method that I could pursue? I am going to study both approaches regardless out of curiosity.  I will study LinearForm structure, and try to understand ex27p as well. 

Thank you in advance for helping out.
Regards
