### ISSUE TITLE
Change the index of stiffness matrix

### ISSUE THREAD

**Issue by miaodi** [mfem/mfem#2675]
Hi,

I have a minor question. Is it possible to change the way how unknows are indexed? Currently, the stiffness matrix is indexed as:
N1_x N2_x ... Nn_x N1_y N2_y ... Nn_y.

Is it possible to change it to N1_x N1_y N2_x N2_y ... Nn_x Nn_y?

Regards,
Di

**Comment by vladotomov** [comment]
Hi Di, yes it is.
Check the variable `ordering` in `FiniteElementSpace`. It can be specified to `Ordering::byVDIM` in the constructors.
Vladimir
