### ISSUE TITLE
How to get stiffness matrix?

### ISSUE THREAD

**Issue by random2000** [mfem/mfem#2676]
I tried to get stiffness matrix with a method of "FormLinearSystem( ... )".
I thought A matrix of linear system without constraint is stiffness matrix.
However, acquired A matrix was same size from constrained system, therefore I think it is not a stiffness matrix.

How can I get stiffness matrix from elastic linear system (like eg. 2)?

**Comment by v-dobrev** [comment]
If you want to construct the stiffness matrix without imposing any essential boundary conditions on it, you can use `FormSystemMatrix` or `FormLinearSystem` with an empty `ess_tdof_list` array.

Note also that, in MFEM, when we impose essential boundary conditions, we do not shrink the matrix size. Instead we perform the following transformation:
```
A_{no b.c.} = / A_{ii}   A_{ib} \  -->  A_{with b.c.} = / A_{ii}   0 \
              \ A_{bi}   A_{bb} /                       \   0      I /
```
where the "b"-subscript rows and columns are the essential boundary dofs. When calling `FormLinearSystem`, the vector `x` is expected to contain an initial guess and the vector `b` is expected to be the assembled linear form defining the r.h.s.
```
x = / x_i \    b = / b_i \
    \ x_b /        \ b_b /
```
where `x_b` has the required essential boundary conditions; the `b_b` sub-vector will be ignored. The method `FormLinearSystem` will transform `x` in the following way:
```
x = / x_i \  -->  x = /  0  \
    \ x_b /           \ x_b /
```
if the parameter `copy_interior = 0`, and `x` will remain unmodified if `copy_interior != 0`. The r.h.s. vector `b` is modified in the following way:
```
b = / b_i \  -->  b = / b_i - A_{ib} x_b \
    \ b_b /           \       x_b        /
```
This type of transformation ensures that the initial residual of this system is 0 on the essential dofs:
```
b - A x = / b_i - A_{ib} x_b \ - / A_{ii} 0 \ / x_i \ = / ... \
          \       x_b        /   \   0    I / \ x_b /   \  0  /
```
and therefore the iterations for any Krylov sub-space iterative method (like the conjugate gradients method) will be exactly the same as if we removed the rows and columns corresponding to the essential dofs.

**Comment by random2000** [comment]
Thank you for reply, v-dobrev.

So, the method "LinearFormSystem( ess_tdof_list, x, b, A, X, B )" generate a stiffness matrix as A matrix with or without essential constraint, is it right?

I need to get both A_{no b.c.} and A_{with b.c.}.
How to get A_{with b.c.} under essential boundary condition?
Can I get A_{ib}, A_{bi}, A_{bb} and manually assemble A_{with b.c.}?
( Is A_{ii} a stiffness matrix? )

Additionally, is it right?
A_{with b.c.} = / A_{ii}   A_{ib} \  
                       \ A_{bi}   A_{bb} /
                       
random2000

**Comment by v-dobrev** [comment]
To clarify: in order to simplify the notation and the expressions above, I wrote the "interior", `*_i`, and "boundary", `*_b` blocks (matrix- or vector-blocks) as contiguous, i.e. the indices `*_i` corresponding to the range `0,1,...,n_i-1` and the indices `*_b` corresponding to `n_i,...,n_i+n_b-1` where `n_i` and `n_b` are the number of "interior" and "boundary" indices, respectively.

In the actual code, these index ranges are not necessarily contiguous, and we do not rearrange them when imposing b.c. Basically, the above expressions are valid with the understanding that there is a hidden permutation of the columns/rows.
