### ISSUE TITLE
Source Term Linearization

### ISSUE THREAD

**Issue by mosawe** [mfem/mfem#2679]
One option for the treatment of source/sink term in a scalar transport equation is to employ a negative linearization procedure. The end result of the linearization process is an enhancement of the so-called M-type matrix property to strictly diagonal dominance. Is there is away to carry out such operation using the MFEM library?

**Comment by jandrej** [comment]
Hello @mosawe, can you point us to a reference that explains this method and has some equations? It will be easier to determine if something like this is possible through the current interface.

**Comment by mosawe** [comment]
Hello Julian,

One reference on the idea is:

R.J. MacKinnon and G.F. Carey, Positivity preserving flux-limited
finite-difference and finite-element methods for reactive transport. Int.
J. Numer. Methods Fluids 41 (2003) 151– 183.

Dmitri Kuzmin outlines the key ideas in his book - A Guide to Numerical
Methods for Transport Equations. I believe the PDF of this book is freely
available online. Read section 1.6.3.4. Or better still search for Patankar
in the book and read entire section where the name is mentioned. This
should provide you a quick summary, and additional references.

A detailed coverage of the method can be found in the book by the inventor:

S.V.Patankar,Numerical Heat Transfer and Fluid Flow.
McGraw-Hill,NewYork,1980.

Thanks for your quick response.

**Comment by jandrej** [comment]
Thank you for the references. Let me recap what I think you want to do.

You have a source term that is nonlinear e.g. `R(C)` and want to split it in a certain way e.g. `F(R_1(C), R_2(C))` s.t. you preserve positivity.

If this is correct, then yes, it is possible to do in MFEM. The remaining question is the bigger picture of your formulation. Do you solve explicitly or do you need those term in a linearization? The answer will determine recommendations if you should implement a "LinearForm" (misleading name in this case), or a "NonlinearForm". There are of course more approaches due to the flexibility of MFEM.

**Comment by mosawe** [comment]
I need the terms in a linearization. A directly relevant example will be
very helpful.

Thanks.

**Comment by mosawe** [comment]
And yes, you surmised my intent correctly in terms of the decomposition,
and the preservation of positivity.

Maxwell

**Comment by jandrej** [comment]
> I need the terms in a linearization. A directly relevant example will be
very helpful.

That means you are solving a nonlinear problem in an implicit formulation for e.g. a Newton type method?

**Comment by mosawe** [comment]
What I envisage is that the user linearizes the source term using say a
Taylor series expansion with say the first-order derivative term, and which
the user evaluates at a known previous state. The evaluated gradient is
then the implicit coefficient that gets added to the diagonal of the LHS
matrix for the discretized point (row). The RHS for same point is then made
up of the first term of the series and the product of the gradient and the
value at the known state. As I see it, the onus is on the user to supply
these terms. The RHS  via Linear form. An interface only needs to provide a
means to add to to the LHS diagonal.

From your earlier response - and I guessed that that may well be  the case
- it appears there may be useful examples in the examples suite? I  am new
to using the library so it is very possible that I am blind to things that
are fairly obvious.

**Comment by jandrej** [comment]
I would advice to look more into the NonlinearForm. It would provide an interface for the user to provide a residual term as well as a linearization (Jacobian) for the LHS matrix. If NonlinearForm is not exactly what you need, you can always cherry pick functionality from it and roll your own. At least it is a good starting point.

https://github.com/mfem/mfem/blob/master/examples/ex10p.cpp is an example that shows the described behavior, but also includes a lot of unnecessary code for your question.

Let us know if that helped. You can also email or call me through my LLNL handle.

**Comment by mosawe** [comment]
Thanks, will take a look, and give it a try.
