### ISSUE TITLE
Exact mesh bounding box

### ISSUE THREAD

**Issue by rmvega1025** [mfem/mfem#2680]
Referring to the Mesh method:

void | GetBoundingBox (Vector &min, Vector &max, int ref=2)

It seems possible to get a bounding box that does not enclose the mesh entirely if the boundaries are highly curved and if ref is too low. Is there a way to find the exact bounding box?

Also, is there a similar method for getting the bounding box of a single element?

**Comment by pazner** [comment]
If the mesh transformation is given in the Bernstein basis, then the mesh will be contained in the convex hull of the Bernstein control points. In other words, you could represent the nodal grid function in Bernstein basis, and then take the min/max of the components to get the bounding box.

This will not be an "exact" bounding box in the sense that it may be pessimistic, but it should always contain the entire mesh, even in highly curved cases.

If you degree-elevate the Bernstein basis, you may get a better approximation for the bounding box using this method.

**Comment by rmvega1025** [comment]
Aside from making a 1 zone mesh, and repeating the above, is there a built in way to get the bounding box of a single element of the mesh?

**Comment by kennyweiss** [comment]
We have some functionality to convert to a positive (Bernstein) basis and compute element bounding boxes in Axom's `PointInCell` query.

See: 
https://github.com/LLNL/axom/blob/afea7ee7f245aca45405d1bcebc77b2f2838f799/src/axom/quest/detail/PointInCellMeshWrapper_mfem.hpp#L284-L342
