### ISSUE TITLE
special case 3D cross product of 2D space?

### ISSUE THREAD

**Issue by M8kmyday** [mfem/mfem#2681]
I have a 2D vector field in the x-y plane, and I need to calculate the cross product with zhat (the unit vector in the z-direction).  I set this up with VectorCrossProductInterpolator(*zhat), but I get errors that are not unexpected.  If I set the dimension of the VectorCoefficient zhat to 3, I get an error that this is not equal to the mesh dimension, which is 2.  If I set the dimension of zhat to 2, then I get an error that the zhat dimension is not 3.  VectorCrossProductInterpolator seems to only support 3D operations.

It is generally valid to do the zhat cross product with a 2D x-y field since the result remains in the x-y plane, and this is what my math requires.  Is there a way to set this up?

**Comment by mlstowell** [comment]
Hi, @M8kmyday, 

This is clearly a very special case and `VectorCrossProductInterpolator` does not support it. The trouble is that in general the vector coefficient provided to this interpolator could be non-zero in any of its components. This would lead to results which are not contained in the 2D plane. We would need to verify that these components are indeed zero at every interpolation point which would not be very efficient (and we try to avoid testing doubles for equality whenever possible).

You could write a custom interpolator based on the `VectorCrossProductInterpolator` which does this. It would not need a vector coefficient if you want to assume that this coefficient is always `zhat`. This would avoid the verification that I spoke of. The `MatrixCoefficient` defined inside `VectorCrossProductInterpolator` could then be replaced with a 2x2 `MatrixCoefficient` which would probably work with call to `ProjectMatrixCoefficient`.

Best wishes,
Mark

**Comment by M8kmyday** [comment]
Ok.  Thanks for the details on an approach.

**Comment by M8kmyday** [comment]
With Mark's feedback on an approach, I have something working using this code:

class zHatCrossProduct2D : public DiscreteInterpolator
{
   public:
   zHatCrossProduct2D() {}
   void AssembleElementMatrix2(const FiniteElement &nd_fe,
                               const FiniteElement &rt_fe,
                               ElementTransformation &Trans,
                               DenseMatrix &elmat);
};

void zHatCrossProduct2D::AssembleElementMatrix2(
   const FiniteElement &dom_fe,
   const FiniteElement &ran_fe,
   ElementTransformation &Trans,
   DenseMatrix &elmat)
{
   // Vector coefficient product with vector shape functions
   struct VCrossVShapeCoefficient : public MatrixCoefficient
   {
      const FiniteElement &fe;
      DenseMatrix vshape;

      VCrossVShapeCoefficient(const FiniteElement &fe_, int dim)
         : MatrixCoefficient(fe_.GetDof(),dim), fe(fe_),
           vshape(height, width)
      {
         MFEM_ASSERT(width == 2, "");
      }

      virtual void Eval(DenseMatrix &M, ElementTransformation &T,
                        const IntegrationPoint &ip)
      {
         M.SetSize(height, width);
         fe.CalcPhysVShape(T, vshape);
         for (int k = 0; k < height; k++)
         {
            M(k,0) = -vshape(k,1);
            M(k,1) =  vshape(k,0);
         }
      }
   };

   int dim=2;
   VCrossVShapeCoefficient dom_shape_coeff(dom_fe,dim);

   if (ran_fe.GetRangeType() == FiniteElement::SCALAR)
   {
      // ToDo - VQ has been taken out, so this line needs to be fixed up.
      // However, a SCALAR result would never show up in this code, so it should
      // not be a problem to just leave it.
      //elmat.SetSize(ran_fe.GetDof()*VQ->GetVDim(),dom_fe.GetDof());
   }
   else
   {
      elmat.SetSize(ran_fe.GetDof(),dom_fe.GetDof());
   }

   Vector elmat_as_vec(elmat.Data(), elmat.Height()*elmat.Width());

   ran_fe.ProjectMatrixCoefficient(dom_shape_coeff, Trans, elmat_as_vec);
}

Then:

         DiscreteLinearOperator Ht_re(fespace_Et, fespace_Ht);
         Ht_re.AddDomainInterpolator(new zHatCrossProduct2D());
         Ht_re.Assemble();
         Ht_re.Finalize();
         ParGridFunction grid_Ht_re(fespace_Ht);
         Ht_re.Mult(grid_Et_im,grid_Ht_re);

This seems to be working and giving the right result [still needs the right scaling and the imaginary part].  Here is the electric field for a microstrip line with the fields properly fringing from the trace to the ground plane:
![Screenshot from 2021-12-01 16-03-49](https://user-images.githubusercontent.com/90462987/144322081-fe4b78c5-2c32-4723-97f0-838a4f754130.png)
and here is the magnetic field using the new zHatCrossProduct2D interpolator with the fields properly circling around the trace:
![Screenshot from 2021-12-01 16-01-33](https://user-images.githubusercontent.com/90462987/144322238-4cd1c66c-5110-4df0-9e6b-3bf9ec1a3894.png)

If anyone has the time to look at the code, I would appreciate feedback on what might be wrong.

**Comment by mlstowell** [comment]
This looks good to me.

**Comment by M8kmyday** [comment]
Thanks!
