### ISSUE TITLE
Non-linear terms in a Nedelec vector space

### ISSUE THREAD

**Issue by LeilaSalomon** [mfem/mfem#2686]
Hello !

I would like to solve the following equation : 

<img width="153" alt="Equation" src="https://user-images.githubusercontent.com/40572513/144274581-22f9350b-ac06-4510-9284-bcda857b5056.PNG">

in a Nedelec vector space.

Do you have any idea of an example that can help me? At first glance I don't really see a similar example.

**Comment by tzanio** [comment]
Hi @LeilaSalomon,

Can you clarify what the weak formulation is? 

Typically you would not use H(curl) elements for `u`.

Tzanio
