### ISSUE TITLE
Initialization of a NURBS GridFunction

### ISSUE THREAD

**Issue by marc-85** [mfem/mfem#2687]
Hi all,

I am trying to initialize a NURBS GridFunction with a function that is space-dependent. Particularly, I'd like to solve the Euler vortex problem. However, when I try to use `GridFunction::ProjectCoefficient()` it fails with the message: `MFEM abort: method is not overloaded`

Any suggestions as to how I could do this?

Many thanks,
marc

**Comment by tzanio** [comment]
ping: @IdoAkkerman

**Comment by v-dobrev** [comment]
Apologies for the late reply.

My suggestion will be to use a global L2 projection onto the NURBS space, i.e. solve the variational problem
```
   (u_h, v_h) = (u, v_h), for all v_h
```
where `u` is the coefficient you want to project, `u_h` is the desired projection, and both `u_h` and `v_h` are in the NURBS FE space. Let us know if you need more details about implementing this.

**Comment by marc-85** [comment]
Hi @v-dobrev. Thanks for the reply.
I believe that is what we ended up doing.
