### ISSUE TITLE
Static assertion error inside of mfem when linking??

### ISSUE THREAD

**Issue by bensworth** [mfem/mfem#2690]
Hi, I just pulled MFEM master for the first time in a while. I kept the same build directory and user.cmake file I used previously. I called `make -j install` and everything compiled and installed fine. Then I tried to compile a script outside of MFEM, which previously worked, and get the error:
```
In file included from /g/g19/bs/mfem/mfem.hpp:19,
                 from /g/g19/bs/mfem/bens_build/mfem.hpp:3,
                 from vort_irk.hpp:4,
                 from vort_irk.cpp:1:
/g/g19/bs/mfem/general/array.hpp: In instantiation of 'static void mfem::Array<T>::TypeAssert() [with T = mfem::Vector]':
/g/g19/bs/mfem/general/array.hpp:96:32:   required from 'mfem::Array<T>::~Array() [with T = mfem::Vector]'
/g/g19/bs/mfem/general/array.hpp:358:7:   required from here
/g/g19/bs/mfem/general/array.hpp:57:21: error: static assertion failed: type T must be trivial
       static_assert(std::is_trivial<T>::value, "type T must be trivial");
```

What is going on here? It seems to be inside of MFEM, but that doesn't make sense. I am using
```
Currently Loaded Modulefiles:
  1) gcc/9.4.0               2) mpich/3.4.2-gcc_9.4.0   3) cmake/3.17.3
```

@pazner this is the vorticity repo, as well as the IRK code. None of it seems to compile for me anymore, but I didn't change anything there or in my makefiles.

**Comment by pazner** [comment]
The issue is using `Array<T>` or `Array2D<T>` where the type `T` is ["non-trivial"](https://en.cppreference.com/w/cpp/types/is_trivial). This never worked properly in MFEM, but in recent versions it is now checked at compile time so that you get compiler errors rather than run-time bugs.

One solution would be to replace `T` with a pointer, or perhaps use a different container like `std::vector`. This will of course require changes to your code.

If you just want to compile in the mean-time, you can comment out the assertions here:
https://github.com/mfem/mfem/blob/539f663fe6ad3738b6de9615f6c74dfa44927578/general/array.hpp#L57

**Comment by bensworth** [comment]
Ohh it's in the IRK code. Why didn't the stacktrace point to our code where this happens? I see what's going on now anyways, thanks.

**Comment by pazner** [comment]
If the compiler was helpful, it would point towards the line in your code where you actually define the `Array<T>`, I think clang (and maybe new versions of gcc?) do this. My guess is that older versions of the compiler just have bad error messages.

**Comment by bensworth** [comment]
Ya, I'm using gcc 9.4, which should be 2021 (https://gcc.gnu.org/releases.html). Interesting that this isn't picked up on.

**Comment by pazner** [comment]
On clang version 12, this is the error:
```
In file included from ex0.cpp:15:
In file included from ../mfem.hpp:19:
../mesh/../fem/../general/array.hpp:57:7: error: static_assert failed due
      to requirement 'std::is_trivial<mfem::Mesh>::value' "type T must be
      trivial"
      static_assert(std::is_trivial<T>::value, "type T must be trivial");
      ^             ~~~~~~~~~~~~~~~~~~~~~~~~~
../mesh/../fem/../general/array.hpp:96:22: note: in instantiation of
      member function 'mfem::Array<mfem::Mesh>::TypeAssert' requested
      here
   inline ~Array() { TypeAssert(); data.Delete(); }
                     ^
ex0.cpp:28:16: note: in instantiation of member function
      'mfem::Array<mfem::Mesh>::~Array' requested here
   Array<Mesh> tmp;
```
It points to the actual location in the "note" at the bottom.
