### ISSUE TITLE
Initial guess for iterative solver

### ISSUE THREAD

**Issue by Watchmojo** [mfem/mfem#2693]
Hi,

When an iterative solver is solved repeatedly, is the initial guess always set to zero for each solve? If yes, is there a way to use the previous solution as the initial guess? 

Thanks

**Comment by jandrej** [comment]
Each solver should use the vector you give it as initial guess. If you look at the GMRES code https://github.com/mfem/mfem/blob/master/linalg/solvers.cpp#L899-L906, each iterative solver has a flag called "iterative mode" - which means if you turn it off, your initial guess is automatically set to zero. This flag is _on_ by default and uses `x` as initial guess.

**Comment by Watchmojo** [comment]
The iterative_mode is set to true. I did try to initialize x using zero, and the iteration number increased by 4. Thanks.
