### ISSUE TITLE
Meshing examples

### ISSUE THREAD

**Issue by adigitoleo** [mfem/mfem#2694]
Hello, I like the mesh formats you have, but I'm quite out of my depth with c++, so I wonder if anyone can help with a few simple examples on how to use the meshing API. What I'm talking about here are some .cpp files that can be used to generate meshes.

My immediate use cases are a 3D box with origin in the centre, and a 2D rectangle with origin in the middle of the top boundary and downward decreasing element size. But any kind of simple examples would be welcome. Maybe the mesh generation step could be added to some of the tutorial examples?

Cheers

**Comment by vladotomov** [comment]
Hi @adigitoleo,

MFEM can perform some basic meshing operations like in the `trimmer`, `extruder`, `toroid` and `twist` miniapps in `/miniapps/meshing`, but MFEM does not have general mesh generation capabilities or a meshing API. We usually start with an existing mesh and focus on PDEs and their finite element discretization. We support most of the standard formats, see [here](https://mfem.org/mesh-formats/), and import meshes created by external packages for general meshing.

For the 3D box mesh you can use `/data/ref-cube.mesh`, you just have to change the coordinates by editing the file. I'm not sure what you need in 2D, but you might be able to do the same with `/data/ref-square.mesh`.

Thanks,
Vladimir

**Comment by adigitoleo** [comment]
I see, thanks. I'll have a look at the examples again but I'll probably stick to gmsh for meshing in that case. It's unfortunate that gmsh doesn't have something like your `Mesh::MakeCartesian3D` for example, which seems very convenient for simple meshes. Maybe I'll eventually write some Python scripts on top of gmsh for that.

**Comment by pazner** [comment]
Just FYI, Gmsh's constructive geometry features using Open Cascade let you construct these types of meshes pretty easily. It wasn't completely clear to me exactly what kind of mesh you wanted to generate, but here is a short geo file that creates a cube with element sizes increasing downwards:
```
SetFactory("OpenCASCADE");
Box(1) = {0, 0, 0, 1, 1, 1};
MeshSize {3, 7, 8, 4} = 0.025;
MeshSize {1, 5, 6, 2} = 0.25;
```
<img width="329" alt="image" src="https://user-images.githubusercontent.com/11493037/145072538-8381dcf7-bbb4-45a9-863a-4fc0218b05c8.png">

If you want a structured mesh, you could use the transfinite features.
