### ISSUE TITLE
Can't link to the library: undefined references

### ISSUE THREAD

**Issue by adigitoleo** [mfem/mfem#2695]
So, I'm not a C++ guy and this is most likely due to my incompetence, but I can't get the linker to find this library.

I built the library as per [the instructions](https://mfem.org/building/) using METIS 5.1 and hypre 2.16 (parallel build). All tests passing. But I am trying to use the library from my own code, in another folder. So, I ran `make install PREFIX=/home/admin/opt/mfem/mfem-4.3`, where `admin` would be the name of the user. However, when I try to compile a copy of `ex0.cpp` in some other folder, I get a lot of linker errors. Here are the first few lines, it continues with lots of `undefined reference to mfem::Foo` stuff.

```
mpicxx -L/home/admin/opt/mfem/mfem-4.3/lib -lmfem -L/home/admin/srcbuilds/mfem/mfem-4.3/../hypre/src/hypre/lib -lHYPRE -L/home/admin/srcbuilds/mfem/mfem-4.3/../metis-5.1.0/lib -lmetis -lrt  -O3 -std=c++11 -I/home/admin/opt/mfem/mfem-4.3/include -I/home/admin/srcbuilds/mfem/mfem-4.3/../hypre/src/hypre/include -I/home/admin/srcbuilds/mfem/mfem-4.3/../metis-5.1.0/include ex0.cpp -o ex0
/usr/bin/ld: /tmp/ccTm0vEL.o: warning: relocation against `_ZTVN4mfem4MeshE' in read-only section `.text._ZN4mfem4MeshD2Ev[_ZN4mfem4MeshD5Ev]'
/usr/bin/ld: /tmp/ccTm0vEL.o: in function `mfem::Vector::ReadWrite(bool)':
ex0.cpp:(.text._ZN4mfem6Vector9ReadWriteEb[_ZN4mfem6Vector9ReadWriteEb]+0x17): undefined reference to `mfem::Device::device_singleton'
...
```

I was using a simple makefile to get the correct flags from `config.mk`:

```
include /home/admin/opt/mfem/mfem-4.3/share/mfem/config.mk

MFEM_COMPILE_FLAGS = $(MFEM_LIBS) $(MFEM_FLAGS)

ex0: ex0.cpp
	$(MFEM_CXX) $(MFEM_COMPILE_FLAGS) $(<) -o $(@)
```

I thought the include from the top level `mfem.hpp` should grab all the necessary headers, but it seems that isn't happening? I'm surely doing something wrong...

I'm using GCC 11.1 and openmpi 4.1.2 if it helps.

**Comment by v-dobrev** [comment]
I think you just need to put `$(MFEM_LIBS)` at the end of the compile line:
```makefile
	$(MFEM_CXX) $(MFEM_FLAGS) $< -o $@ $(MFEM_LIBS)
```

**Comment by adigitoleo** [comment]
Thanks so much, it's working!
