### ISSUE TITLE
[USAGE]: How do I check conformity while displacing the mesh?

### ISSUE THREAD

**Issue by cbritopacheco** [mfem/mfem#2697]
Say I want to displace the nodes in my mesh so that it remains conforming after the displacement, without actually moving the nodes. How do I do this?

"Conforming" here is quite a strong word. In fact I would be satisfied if I could ensure, before doing the displacement, that each of my triangles have a minimum area of `tmin`, i.e. no triangle has flipped over. Now from the Doxygen page, the function `CheckDisplacements` seems to return the _maximum_ triangle area for the given displacements which is not really useful to me. 
Is there a way to do this?

**Comment by vladotomov** [comment]
Hi @cbritopacheco,

Can you explain a little more what you mean by "displace the mesh nodes without actually moving the nodes". Are you working with linear or curved meshes?

**Comment by vladotomov** [comment]
If you only want to check validity, `CheckDisplacements` will be sufficient, as it exits with `tmax = 0` when the displacements invert the mesh. But I think it works only for linear meshes.

**Comment by cbritopacheco** [comment]
Hi @vladotomov ,
Thank you for your response it is exactly what I needed. Just one more question, Wwat does the `tmax` parameter represent?

**Comment by vladotomov** [comment]
Whoever wrote the function can correct me, but it seems to be the maximum `t > 1`, so that `x + t dx` still produces a mesh with no inverted elements.

**Comment by cbritopacheco** [comment]
This answers my question. I will be closing the issue.
