### ISSUE TITLE
Dofs vs True dofs in Parallel classes

### ISSUE THREAD

**Issue by martemyev** [mfem/mfem#27]
Dear all,

I don't quite understand what is the difference between dofs and true dofs when a problem is being solved in parallel. What makes true dofs true? Why do we need them?

Thank you,
Mikhail

**Comment by v-dobrev** [comment]
Hi Mikhail,

The difference is in the shared dofs: in a parallel setting these are the dofs that belong to elements on different processors. A vector on the "true dofs" (usually represented by a HypreParVector or just a Vector) has only one copy of each shared dof (in the processor that is assigned to be master for that shared dof). On the other hand a vector on the "dofs" (usually represented by a ParGridFunction) has a copy of the shared dofs on each processor that shares that dof. In other words, the difference between "true dof" and "dof" vector is the decomposition of the all dofs to multiple processors: non-overlapping (true dofs) vs overlapping (dofs).

The reason we need to use both types of vectors is convenience and sometimes necessity: depending on the operation we are performing it may be easier to work with one or the other. For example, if you want to compute the value of a finite element function at a quadrature point in an element, you need to know all dofs in that element including the shared dofs - that is why such operation is natural for a "dof" vector, i.e. a ParGridFunction. One the other hand, when solving the global linear system it is easier to remove the duplication of the shared dofs in a "dofs" vector and therefore we use a "true dof" vector.

Veselin

**Comment by martemyev** [comment]
Hi Veselin,
Thank you for the explanation. It was very helpful!

Best regards,
Mikhail
