### ISSUE TITLE
How do you define a domain for mesh in first place? 

### ISSUE THREAD

**Issue by olekhov** [mfem/mfem#270]
Hello everyone.
I am looking through examples and wonder, how do you define an initial mesh, e.g. square-disc.mesh ?
It contains 154 elements and 101 vertices.  I can hardly believe someone entered their coords and connections by hand.

Say, I need to define a following domain:
![rk-domain](https://user-images.githubusercontent.com/2698890/29962916-8faf728c-8f0d-11e7-926d-8e94f1db2b1b.png)

I can define borders and circle inclusions. But I have trouble defining initial elements, can't see through examples how to do this. I need triangular elements to begin with.

I have another question about mesh refinement.
As I can observe in examples, Mesh::UniformRefinement() just splits existing elements into smaller parts. Newly formed elements are similar to previous generation elements.
I think the form of elements affects the computational errors and convergence rate.
Isn't it better to shift vertices during refinement so newly formed elements are more regular?
Say, too long sharp triangular elements will be far worse than regular triangles. 
Bad:
![mfem-orig](https://user-images.githubusercontent.com/2698890/29987144-604d5f2e-8f6f-11e7-94ee-aabd7e8f3ae3.png) 
![mfem-refined](https://user-images.githubusercontent.com/2698890/29987310-3ab45d98-8f70-11e7-8ea6-ec2275dc1434.png)

Good:
![b1-original](https://user-images.githubusercontent.com/2698890/29987148-6b8a935c-8f6f-11e7-9e38-9bb44899a53e.png)
![b1-refined](https://user-images.githubusercontent.com/2698890/29987154-701558a8-8f6f-11e7-9dc2-56db4fda540c.png)

Am I wrong?

The latter results are from my mesher, I am now considering new tools for FEM.

**Comment by v-dobrev** [comment]
The mesh `square-disc.mesh` was created with a mesh generator - [Netgen](https://sourceforge.net/projects/netgen-mesher/) in this case. The mesh was then imported in mfem and saved in the mfem native mesh format. The list of all supported formats can be found  [here](http://mfem.org/meshing/#mesh-formats).

Improving the quality of the mesh elements is definitely a topic we are interested in. In fact, there is currently a pull request, #193, that will add a miniapp that performs mesh optimization using an extensive set of mesh quality metrics. This work will be merged in the main mfem branch soon and it will be part of the next release.

**Comment by tzanio** [comment]
To add to Veselin's answer -- we support input from many other mesh generators, including [Gmsh](http://gmsh.info/) and [CUBIT](https://cubit.sandia.gov/). 

Simple meshes of the types you included can also be directly generated in our NURBS format, see http://mfem.org/mesh-formats/#nurbs-meshes. 

Finally, @tmmcmanus has some meshing tools in the [mixed-elements-dev](https://github.com/mfem/mfem/tree/mixed-elements-dev) branch and may be able to offer additional advice.

**Comment by tzanio** [comment]
@olekhov, I will close this issue now, but please feel free to reopen it if you have any other questions.
