### ISSUE TITLE
Will not build with hypre

### ISSUE THREAD

**Issue by bensworth** [mfem/mfem#2703]
Hi MFEM team, I was having a memCpy error/warning from hypre today in a code that used to run, so I decided to update my hypre and MFEM repos and start from there. I pulled hypre master, installed, then pulled MFEM master and tried to install and got a bunch of errors.

UPDATE: removed my build directory and started from scratch. Most of the errors went away, but I still have the error:
```
/home/southworth/c_libs/mfem/linalg/hypre.cpp: In member function ‘mfem::HypreParMatrix* mfem::HypreParMatrix::ExtractSubmatrix(const mfem::Array<int>&, double) const’:
/home/southworth/c_libs/mfem/linalg/hypre.cpp:1614:48: error: cannot convert ‘HYPRE_BigInt**’ {aka ‘int**’} to ‘HYPRE_BigInt’ {aka ‘int*’}
 1614 |                               CF_marker, NULL, &cpts_global);
      |                                                ^~~~~~~~~~~~
      |                                                |
      |                                                HYPRE_BigInt** {aka int**}
In file included from /home/southworth/c_libs/mfem/linalg/hypre.hpp:27,
                 from /home/southworth/c_libs/mfem/linalg/complex_operator.hpp:18,
                 from /home/southworth/c_libs/mfem/linalg/linalg.hpp:21,
                 from /home/southworth/c_libs/mfem/linalg/hypre.cpp:16:
/home/southworth/c_libs/hypre/src/hypre/include/_hypre_parcsr_ls.h:2021:92: note:   initializing argument 7 of ‘HYPRE_Int hypre_BoomerAMGCoarseParms(MPI_Comm, HYPRE_Int, HYPRE_Int, hypre_IntArray*, hypre_IntArray*, hypre_IntArray**, HYPRE_BigInt*)’
 2021 |                                        hypre_IntArray **coarse_dof_func_ptr, HYPRE_BigInt *coarse_pnts_global );
      |                                                                              ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/mfem.dir/linalg/hypre.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....

```

**Comment by bensworth** [comment]
Okay, pretty sure there is an & in the wrong spot? Currently:
```
#else
   HYPRE_BigInt *cpts_global;
   hypre_BoomerAMGCoarseParms(MPI_COMM_WORLD, local_num_vars, 1, NULL,
                              CF_marker, NULL, &cpts_global);
#endif
```
If I change to
```
#else
   HYPRE_BigInt *cpts_global;
   hypre_BoomerAMGCoarseParms(MPI_COMM_WORLD, local_num_vars, 1, NULL,
                              CF_marker, NULL, cpts_global);
#endif
```
everything compiles and installs. Still puzzled why this wouldn't show up in all the testing modules though?

**Comment by tzanio** [comment]
Looks like this is due to https://github.com/mfem/mfem/pull/2652

@victorapm, can you take a look?

**Comment by victorapm** [comment]
Hi @bensworth,

Assuming that `hypre-master` is being used, then MFEM should take the first code path in

https://github.com/mfem/mfem/blob/7e8d8b1d55adecfb46f971300f820bd7e48bdc67/linalg/hypre.cpp#L1606-L1615

but it seems from your error message that the second path is being taken. Can you verify the values of the macros `MFEM_HYPRE_VERSION` and `HYPRE_DEVELOP_NUMBER`? The last one can be found at hypre's `src` directory on the file `HYPRE_config.h`

**Comment by tzanio** [comment]
@bensworth, can you check your version of `git`? 

Hypre is using `git describe` which doesn't work in older git versions.

**Comment by tzanio** [comment]
I opened an issue about this: https://github.com/hypre-space/hypre/issues/540

**Comment by tzanio** [comment]
@bensworth, can you confirm if the git version was the issue?

**Comment by bensworth** [comment]
Hi guys sorry for the delay, this is on a LANL cluster, git version 2.27.0

**Comment by tzanio** [comment]
Hmm... then can you go to the top-level mfem directory and check the output of

```
grep HYPRE config/_config.hpp
```

and

```
grep NUMBER ../hypre/src/HYPRE_config.h
```

**Comment by bensworth** [comment]
```
$ grep HYPRE config/_config.hpp
grep: config/_config.hpp: No such file or directory
```

Note, I have no _config.hpp file, if I try it on config.hpp I don't find anything

```
$ grep NUMBER ../hypre/src/HYPRE_config.h
/* #undef HYPRE_DEVELOP_NUMBER */
#define HYPRE_RELEASE_NUMBER 22300
```

**Comment by tzanio** [comment]
This is the problem: `/* #undef HYPRE_DEVELOP_NUMBER */`  ◀️  ping: @victorapm 

Just for completeness, if you do `make parallel` in MFEM, what is the `HYPRE version` that gets printed?

```
> make parallel 
make -f makefile config MFEM_USE_MPI=YES MFEM_DEBUG=NO \
	   
make -C config all
mpicxx -I../../hypre/src/hypre/include get_hypre_version.cpp -o get_hypre_version
./get_hypre_version > get_hypre_version.out
HYPRE version: 22200
```

**Comment by bensworth** [comment]
where does this file `get_hypre_version.cpp` come from? I do not see that in my hypre repo or mfem repo?

**Comment by tzanio** [comment]
it is in `mfem/config` should be build and run automatically by `make parallel`

**Comment by bensworth** [comment]
Ah, I am using cmake, it doesn't like `make parallel` as a command:
```
$ make parallel
make: *** No rule to make target 'parallel'.  Stop.
```
I just made the script in the config folder directly and get
```
[southworth@cn200 config]$ ./get_hypre_version
22300
```

**Comment by v-dobrev** [comment]
Is your hypre directory from a release (no `.git` directoory) or from a clone? If you cloned the latest hypre, make sure you have the `.git` directory -- otherwise hypre cannot export properly `HYPRE_DEVELOP_NUMBER`.

**Comment by v-dobrev** [comment]
Judging by the prototype of `hypre_BoomerAMGCoarseParms` you posted earlier, you are using a commit after 2.23.0. In v2.23.0 the prototype is: https://github.com/hypre-space/hypre/blob/v2.23.0/src/parcsr_ls/_hypre_parcsr_ls.h#L1782 i.e. the last argument is `HYPRE_BigInt **coarse_pnts_global_ptr`.

So it looks like you don't have the `.git` directory since `HYPRE_DEVELOP_NUMBER` is undefined.

**Comment by bensworth** [comment]
Hi Veselin, I do have the .git directory and am up to date with master,

**Comment by bensworth** [comment]
Okay, a fresh clone of hypre and clean make of mfem with the new hypre seems to fix the issue. Not sure where it came from, but everything seems to be working now!
