### ISSUE TITLE
Compressible real-gas large eddy simulations in MFEM?

### ISSUE THREAD

**Issue by okcfdlab** [mfem/mfem#2706]
Hello MFEM community, I am investigating the blending of hydrogen into natural gas pipelines. One of the important questions is of course safety associated with the hydrogen gas. High-pressure releases of hydrogen into an oxygen-rich environment has the potential to result in an explosive detonation of the hydrogen. This can occur when the release occurs through an orifice due to a puncture of a gas system component. The released hydrogen gas produces a shock wave in the air driven by the piston action of the expanding hydrogen jet, compressing and heating the air. The diffused interface between the hot air and hydrogen may lead to a local spontaneous ignition (auto-ignition) without any external sources. To date, there has been no research into the auto-ignition risk of hydrogen-enriched natural gas. Although the storage pressures in natural gas lines are typically below the pressures required for pure hydrogen auto-ignition (close to 200 atm), sufficiently large storage pressures will be expected if the hydrogen-enriched natural gas is used in compressed natural gas (CNG) cylinders e.g. in automotive applications, where pressures exceeding 300 atm may be expected.

In addition to detonation risk, understanding the flammability zones of the gas following an accidental release of hydrogen-enriched natural gas is critical for ensuring safety. While natural gas has a relatively narrow flammability range in air, hydrogen has a much broader range, meaning that current flame safety zones may need to be altered in response to an accidental release. To evaluate this risk, we require a better understanding of how a blended mixture of hydrogen and natural gas will disperse following accidental release. Prior studies have shown that the shape of the puncture orifice, the jet orientation, and buoyancy effects can significantly alter the trajectories of subsonic and supersonic hydrogen jets. Real-gas effects may also influence the flammability region, such as Joule-Thomson cooling of the methane during expansion, which may alter the buoyancy forces and affect the gas dispersion. As no studies to date have investigated these effects in the context of mixed hydrogen-methane jets, the impact of hydrogen-enrichment on the flammability safety envelope following accidental release is unclear.

I'm investigating the suitability of MFEM for developing a bespoke CFD tool for conducting simulations of this problem. I think the following features will be important:

- High-order discretization to ensure numerical accuracy and scalability
- Accurate resolution of shock waves
- Incorporation of real-gas effects through a non-ideal EOS
- A miscible mixture of independent gas species
- At present, I will ignore combustion reactions, though that will needed in the future
- Turbulent dispersion will be important but the Reynolds numbers will be large, thus necessitating large eddy simulation (LES) approach

My questions:

1. Is MFEM suitable for such a problem?
2. Have others used MFEM for developing real-gas compressible LES solvers?
3. Where does the community think I should begin in terms of learning? I notice that Laghos miniapp has some of the desired features--is that a reasonable starting point?

Thank you!

**Comment by v-dobrev** [comment]
Re-created as a discussion: #2707.
