### ISSUE TITLE
HypreBoomerAMG Memory Management

### ISSUE THREAD

**Issue by wcdawn** [mfem/mfem#2708]
I have a unique use of MFEM and HYPRE and I am having trouble managing the amount of memory required by `HypreBoomerAMG`. I am running with HYPRE on GPUs (with CUDA) so memory is precious.

I have a series of matrices `A_g` with `g=1...24`. Each matrix has the exact same sparsity pattern (geometry dependent) and only the coefficients of the matrices differ. The matrices are SPD and solved with `HyprePCG`. I know that for this system of equations, as `g` increases, the condition number of the system grows and can become very large. Each matrix `A_g` represents a system of PDEs so I am using `HYPRE_BoomerAMGSetNumFunctions()`.

The problem I am encountering is that even though all matrices have the same sparsity pattern, the memory required by `g>=21` is large enough to cause the code to crash. Generally, there exists some set of coefficients such that `A_{g'}` requires more memory than all other `A_g` and overwhelms the available memory.

My question is: what tuning parameters can I use with `HypreBoomerAMG` to better manage the memory used? I have tried aggressive coarsening (i.e. `HYPRE_BoomerAMGSetAggNumLevels()`) which helps some but not much. Maybe @liruipeng has some insight?

Alternatively, is there some way to estimate the amount of memory required for a given setup of `HypreBoomerAMG`?

In the interim, I have had some success using `HypreDiagScale` (Jacobi preconditioner) but it is obviously far from ideal.

P.S. aggressive coarsening should probably be added for HYPRE with CUDA in `mfem::HypreBoomerAMG::SetDefaultOptions()` now that it is supported by HYPRE.
https://github.com/mfem/mfem/blob/39022bce0ff56dedc20a1778ef688ec16c60bbeb/linalg/hypre.cpp#L4481

**Comment by tzanio** [comment]
This really is a question for the hypre team, I am not sure how much could be saved in memory if you have 24 matrices. Maybe nodal coarsening can help, but I am not sure.

Regarding `agg_levels` if it indeed works on the GPU and the convergence is acceptable, I agree we should make the change. Do you mind proposing a small PR?

**Comment by wcdawn** [comment]
@tzanio I agree that this is probably a HYPRE question. I can open an issue in the HYPRE repo if that is preferable. I'll look into comparing the performance when increasing `agg_levels` on the GPU.

I have been working on this over the last week. I rewrote my code so that only one matrix is stored in memory at a time and is constructed & deleted each time it is used. Still, there is a particular matrix that causes HypreBoomerAMG to crash. The problem will run fine until a certain matrix is encountered and then crash for `g>=22` (increased by one). I could be using HypreBoomerAMG wrong, but this is starting to sound like a bug to me.

Again, each of these matrices has the exact same sparsity pattern. The only difference is there is an increasing condition number as the index `g` increases.
