### ISSUE TITLE
Report a few warnings

### ISSUE THREAD

**Issue by adam-sim-dev** [mfem/mfem#2723]
Compiler: g++ 9.3.0
MPI: mpich 3.3.2
OS: Ubuntu 20.04.3
CUDA: 11.5.1

In function ‘void mfem::SmemPAHcurlL2Apply3DTranspose(int, int, int, int, const mfem::Array<double>&, const mfem::Array<double>&, const mfem::Array<double>&, const mfem::Vector&, const mfem::Vector&, mfem::Vector&) [with int MAX_D1D = 2; int MAX_Q1D = 3]’:
cc1plus: warning: ‘void* __builtin_memcpy(void*, const void*, long unsigned int)’ writing between 8 and 34359738368 bytes into a region of size 0 overflows the destination [-Wstringop-overflow=]

In function ‘void mfem::SmemPAHcurlL2Apply3D(int, int, int, int, const mfem::Array<double>&, const mfem::Array<double>&, const mfem::Array<double>&, const mfem::Vector&, const mfem::Vector&, mfem::Vector&) [with int MAX_D1D = 2; int MAX_Q1D = 3]’:
cc1plus: warning: ‘void* __builtin_memcpy(void*, const void*, long unsigned int)’ writing between 8 and 34359738368 bytes into a region of size 0 overflows the destination [-Wstringop-overflow=]

In function ‘void mfem::SmemPACurlCurlApply3D(int, int, bool, int, const mfem::Array<double>&, const mfem::Array<double>&, const mfem::Array<double>&, const mfem::Array<double>&, const mfem::Array<double>&, const mfem::Array<double>&, const mfem::Vector&, const mfem::Vector&, mfem::Vector&) [with int MAX_D1D = 2; int MAX_Q1D = 3]’:
cc1plus: warning: ‘void* __builtin_memcpy(void*, const void*, long unsigned int)’ writing between 8 and 34359738368 bytes into a region of size 0 overflows the destination [-Wstringop-overflow=]

**Comment by adam-sim-dev** [comment]
Compiler: icpc version 2021.4.0
MPI:  Intel OneAPI 2021.4
OS: Ubuntu 18.04
CUDA: 11.5.1

fem/bilininteg_diffusion_pa.cpp(1559): (col. 8) remark: Loop with pragma of unroll = 8 ignored due to unroll factors mismatched
fem/bilininteg_diffusion_pa.cpp(1559): (col. 8) remark: Loop with pragma of unroll = 9 ignored due to unroll factors mismatched
fem/tmop/tmop_pa_h3d.cpp(42): (col. 1) remark: Loop with pragma of unroll = 14 ignored due to unroll_and_jam pragma expected
fem/tmop/tmop_pa_h2d.cpp(72): (col. 1) remark: Loop with pragma of unroll = 14 ignored due to unroll_and_jam pragma expected

**Comment by tzanio** [comment]
Thanks for reporting this @adam-sim-dev.

These warnings have been present for a while... @camierjs, @dylan-copeland, @mlstowell -- any ideas how to fix them?

**Comment by YohannDudouit** [comment]
This is the solution I have in a branch:
https://github.com/mfem/mfem/pull/2626/files?show-viewed-files=true&file-filters%5B%5D=#diff-b4caa5528a75d84967ad6e2421fd298446d780e44edb57dca79147e61c88cc98R1694
I will open a PR containing only this change.

**Comment by tzanio** [comment]
Discussion continued in #2788
