### ISSUE TITLE
PUMI Mesh with Multiple Materials

### ISSUE THREAD

**Issue by wcdawn** [mfem/mfem#2726]
Currently, the PUMI mesh reader for `ParPumiMesh` does not support multiple materials. Instead of reading the tag/material number, the reader in MFEM fixes the value to 1. This can be seen in the line below.

https://github.com/mfem/mfem/blob/8a565cad67b456bedc4b6c906226c66c2eddb79d/mesh/pumi.cpp#L523

It looks like we need a function call to `getTag(ent)` but I am not familiar enough with PUMI to know the function syntax/signature.

This was originally found and reported in the SCOREC (PUMI) repo after support for Gmsh meshes with multiple materials was added to PUMI. Original issue [here](https://github.com/SCOREC/core/issues/355).

**Comment by tzanio** [comment]
Thanks for reporting this @wcdawn.

@cwsmith, do you think you can help?

**Comment by cwsmith** [comment]
@tzanio Certainly.  I'll talk with @mortezah and we'll put something in place.

**Comment by mortezah** [comment]
@wcdawn @cwsmith @tzanio I usually update the attributes in my application code right after I create my MFEM mesh from a PUMI mesh (see the example code below, which updates the attributes for boundary faces and volume regions)

```
   ParMesh *mesh = new ParPumiMesh(PCU_Get_Comm(), pumi_mesh);   
   
   //Add attributes based on reverse classification
   //Boundary faces
   int dim = mesh->Dimension();
   apf::MeshIterator* itr = pumi_mesh->begin(dim-1);
   apf::MeshEntity* ent ;
   int ent_cnt = 0;
   while ((ent = pumi_mesh->iterate(itr)))
   {   
      apf::ModelEntity *me = pumi_mesh->toModel(ent);
      if (pumi_mesh->getModelType(me) == (dim-1))
      {   
         //Get tag from model by  reverse classification
         int tag = pumi_mesh->getModelTag(me);
         (mesh->GetBdrElement(ent_cnt))->SetAttribute(tag);
         ent_cnt++;
      }   
   }   
   pumi_mesh->end(itr);  
   
   //Volume Regions
   itr = pumi_mesh->begin(dim);
   ent_cnt = 0;
   while ((ent = pumi_mesh->iterate(itr)))
   {   
       apf::ModelEntity *me = pumi_mesh->toModel(ent);
       int tag = pumi_mesh->getModelTag(me);
       mesh->SetAttribute(ent_cnt, tag);
       ent_cnt++;
   }   
   pumi_mesh->end(itr);
   
   //Apply the attributes
   mesh->SetAttributes();
```


I was not part of the orginal developers of the `ParPumiMesh` calss and I don't know what was the logic (if any) to not include the above code in that class. That is certainly a possibility, and by having a quick look at the code, I don't see any reason why that cannot be done.

**Comment by cwsmith** [comment]
Thank you @mortezah.
If we consider the GMesh 'physical_type' tags being transferred [here](https://github.com/SCOREC/core/issues/355) as model classification then the conversion becomes cleaner.  I'll revisit that part of the pumi code and see what I can do.

**Comment by cwsmith** [comment]
@wcdawn The pumi branch ([cws/gmshTags](https://github.com/SCOREC/core/tree/cws/gmshTags)) has been updated and when used with the [cws/pumi-gmsh-phys-ents](https://github.com/SCOREC/mfem/tree/cws/pumi-gmsh-phys-ents) branch will set the element attribute from the gmsh 'physical entity'.  A screenshot from a quick sanity check with `glvis` and `pumi_ex1` is below:

![glvisAttributes](https://user-images.githubusercontent.com/1024438/147278551-de6a1389-bba6-4bbe-b0d8-18435d1105ea.jpg)

**Comment by tzanio** [comment]
@wcdawn can you confirm if @cwsmith's fixes work for you?

**Comment by wcdawn** [comment]
Sorry for the delay. The fixes from @cwsmith do, in fact allow attributes to be read, but only for `PumiMesh`, not for `ParPumiMesh`. In `PumiMesh`, the mesh is loaded with `PumiMesh::ReadSCORECMesh()` but in `ParPumiMesh`, the mesh is simply loaded in the constructor `ParPumiMesh::ParPumiMesh()`.

Similar changes need to be made to the `ParPumiMesh` constructor to allow this to be used with parallel mesh objects. This can be tested with `examples/pumi/ex1p`.

**Comment by cwsmith** [comment]
@wcdawn This [commit](https://github.com/SCOREC/mfem/commit/bf3b040c9d95b0c396fe06b5a5f08bddd254adf5) (followed by a cleanup [commit](https://github.com/SCOREC/mfem/commit/6a9c53e8dddabdcb56e39811b0024bc04cbd94c3)) enables attribute transfer from gmsh for the partitioned meshes.  Running `./glvis -m /path/to/parallel/mfem/mesh -np 8 -a` on an eight part mesh produced by `pumi/ex1p.cpp` (which loads an eight part pumi mesh) results in the following figure.

![gmshAttr_p8](https://user-images.githubusercontent.com/1024438/150400437-d95812d8-2d97-40d0-babe-e4814729a45f.png)

**Comment by wcdawn** [comment]
Thanks @cwsmith! I've been able to replicate your results and use PUMI to pre-partition a mesh in my own MFEM based program.

**Comment by cwsmith** [comment]
@wcdawn You're welcome.  I'm glad that worked.  
 
The PUMI changes should be merged into PUMI master tomorrow morning.  Once that goes through I'll submit a PR to merge the MFEM changes.

**Comment by tzanio** [comment]
thanks @cwsmith !

**Comment by tzanio** [comment]
Discussion continued in #2782.
