### ISSUE TITLE
Finite-volume method?

### ISSUE THREAD

**Issue by Marshdweller** [mfem/mfem#2728]
Hello,

Is there an example of building an FVM solver with MFEM? MFEM does not promote the FVM, but it seems (?) that many building blocks are in there. I want to build a basic solver for a non-linear parabolic problem on Voronoi mesh. What can be possible caveats?

Thank you.

**Comment by jandrej** [comment]
While not officially supported, it is probably very likely that formulating a DG method with polynomial order equal to zero and implementing it in MFEM might just work. You can try and see if running `Example 9: DG Advection` works when using `ex9 -m ../data/periodic-square.mesh -p 0 -r 2 -dt 0.01 -tf 10 -o 0`

**Comment by Marshdweller** [comment]
Thank you for the suggestion!
