### ISSUE TITLE
Question about ScaledOperator

### ISSUE THREAD

**Issue by sshiraiwa** [mfem/mfem#2729]
Both ScaleOpeator and TransposeOperator called BaseClass using A->Width() A->Height()).
Should we swap Width and Height for ScaledOperator?
```
explicit ScaledOperator(const Operator *A, double a)
      : Operator(A->Width(), A->Height()), A_(*A), a_(a) { }
```
```
   TransposeOperator(const Operator *a)
      : Operator(a->Width(), a->Height()), A(*a) { }
```

**Comment by v-dobrev** [comment]
Yes, this looks like a copy-paste bug. The dimensions of the `ScaledOperator` should be the same as the dimensions of the `Operator` `A`, so the base class constructor should be called with `Operator(A->Height(), A->Width())`.

**Comment by sshiraiwa** [comment]
Thank for your confirmation. I'll make a PR soon.

**Comment by tzanio** [comment]
Discussion continued in https://github.com/mfem/mfem/pull/2730
