### ISSUE TITLE
Resizing of vectors which don't own data arrays

### ISSUE THREAD

**Issue by mlstowell** [mfem/mfem#273]
I started this issue because I'm not sure if this should be characterized as a bug or a feature.

I noticed today that Vector objects which don't own data arrays, i.e. Vectors created using the Vector(double * _data, int _size) constructor, will allocate data arrays for themselves if Vector::SetSize is called with a size that is greater then their current size.  This seems counterintuitive to me.  I'd make the argument that when this constructor is used the developer is taking responsibility for providing a suitable data array even in the event that resizing becomes necessary.

I propose we add the following 'if' statement to Vector::SetSize:
if ( allocsize < 0)
{
   size = s;
   allocsize = -s;
   return;
}

I bring this up as an "Issue" because other developers may be relying on this feature and I'd hate to break things without opening a dialog.

**Comment by v-dobrev** [comment]
The current implementation of `Vector::SetSize` is consistent with its (doxygen) documentation, and this is the intended behavior.

I think the documentation of `SetSize` clearly explains what will happen in the case you describe.

Compared to what you propose, I prefer the current behavior.

What do other people think?

**Comment by vladotomov** [comment]
Either way the developer must be careful with the ownership. I'm ok with both. Another option is to put an assert about this case.

**Comment by mlstowell** [comment]
Thanks, Veselin, I missed that in the Vector::SetSize comments.

Let me explain how this came up.  I want to use AMR in the context of an elasticity problem where the solution field is a vector valued H1 displacement field.  Unfortunately, the ElasticityIntegrator does not implement the ComputeElementFlux() and ComputeFluxEnergy() methods needed by the L2ZienkiewiczZhuEstimator.  As an alternative I wanted to approximate the error using this same error estimator three times on the x, y, and z components of the displacement field using the DiffusionIntegrator.

The L2ZienkiewiczZhuEstimator requires access to the solution as a ParGridFunction but in this case that means accessing one portion of the entire solution vector.  The natural way to accomplish this is to create a ParGridFunction which shares a portion of the displacement field and pass this ParGridFunction to the error estimator.  The error estimation seems to work adequately but when I call Update on all of my ParGridFunctions the one in the error estimator allocates its own data array which I don't need.  If I don't call Update on this ParGridFunction it will have the wrong size and the error estimator will fail.  I can't use ParGridFunction::SetSpace because this will also call SetSize and allocate an unneeded data array.  I could resize the ParGridFunction using SetDataAndSize but this would leave GridFunction::sequence with an incorrect value.

I only see three viable options.  The first is to delete this ParGridFunction and the error estimator and recreate them after each refinement but this seems contrary to the spirit of the various Update methods.  The second is to create a ParGridFunction with a data array and copy the data from the solution vector into this temporary space but this is a waste of time and space.  The third is to implement the necessary methods in the ElasticityIntegrator but this is non-trivial and only solves the problem for this one use case.

**Comment by v-dobrev** [comment]
Can't you just call `GridFunction::MakeRef` for the solution `GridFunction` that you gave to the estimator - do that just before the call that performs the error estimation, i.e. before the call to `MeshOperator::Apply`. I have not checked carefully but this seems a simple thing to try.

You can also implement the methods required for estimation - `ComputeElementFlux()` and `ComputeFluxEnergy()`, e.g. you can derive a new class from `ElasticityIntegrator` and implement the two methods using a `DiffusionIntegrator` on each of the components. That shouldn't be too difficult to try.

The first suggestion may be easier but I'm not sure it's that easy to combine the estimates from the different components. Maybe one can use 3 (in 3D) separate `ThresholdRefiner`s? Or maybe one can create a new composite `ErrorEstimator` that combines the errors from any number of `ErrorEstimator`s - in this case from 3 estimators for the 3 components.

**Comment by stefanozampini** [comment]
I'd rather prefer to raise an error if we try to resize (with a larger size) a vector with user-provided data array, as it may happen that the user will change directly the entries in the `data` array.

**Comment by tzanio** [comment]
I agree with @vladotomov on this one -- if `SetSize()` is being called in this case, the user is either not being careful or knows exactly what they are doing. 

We can improve the documentation, adding an explicit warning about the switching of storage, but folks may miss it (given that `SetSize()` is called under the hood by other methods). 

The other option is to raise an error. What are the downsides to that?

**Comment by v-dobrev** [comment]
One use case when raising an error is not appropriate is something like this:
```
   double x_data[16];
   Vector x(x_data, 16);
   x.SetSize(p); // p is not known at compile time
   // ...
```
This way one avoids heap memory allocation for small-size Vectors which may be the most common case. I'm not sure but I may have used this trick in some places in the library.

One the other hand, this case can be handled also with a new constructor, e.g.
```
   double x_data[16];
   // Use x_data as x.data if p <= 16, otherwise allocate x.data on the heap:
   Vector x(p, x_data, 16); // p is not known at compile time
   // ...
```
The drawback of this approach is that `p` has to be known when the constructor is called. In the first case above, the call `x.SetSize(p)` can be in another function called from the scope where 'x' is defined.

At the end I think it comes down to what do you prefer: more flexibility - with the current behavior of `SetSize`; or better detection of errors or misuse - if `SetSize` raises an error when a Vector (with an external data array) is resized beyond its current capacity. I prefer the first choice but I'll be OK with the second one as well.

**Comment by mlstowell** [comment]
It looks like GridFunction::MakeRef is the correct method to be using in my current situation.  I was not familiar with this method, thanks for pointing it out.

**Comment by tzanio** [comment]
I added a comment in https://github.com/mfem/mfem/pull/336/commits/1681a52cb6ef052b2d57c84f07f47a9820e91cca which is good enough for me to resolve this issue.

Any objections?
