### ISSUE TITLE
Construct Coefficient from device memory

### ISSUE THREAD

**Issue by logantm2** [mfem/mfem#2734]
I'm working on an app where we're interested in a pretty straightforward Poisson/Laplace solve. When our app is compiled with CUDA (we use Kokkos for portability, I believe a lot of the semantics are similar to raja), we'll be constructing the rhs directly on device. Presumably, if CUDA is enabled for MFEM, it needs this rhs on device anyway, so I'm wondering if we can avoid copying it from device to host and instead give the `DomainLFIntegrator` a `Coefficient` that's a shallow copy of an existing array on device.

I noticed that there's a [`(Par)GridFunction` ctor](https://mfem.github.io/doxygen/html/classmfem_1_1ParGridFunction.html#a627e4c20381a8dba125115e6392ef509) that accepts a pointer to data. I wondered if this was similar to CUDA-aware MPI or hypre in that it'll accept a device pointer, but MFEM appears to eventually fail at assembly with an error indicating an invalid pointer.

I figured I should ask if there's some existing infrastructure or an example for doing this that I missed before I dive too deep. If this isn't the proper forum for this sort of question, let me know and I'll repost elsewhere and close this issue.

I also have the same question, but for the solution -- we'll only ever need the solution on device as well, so if there's a version of `RecoverFEMSolution` that returns a device array, that'd be perfect.

**Comment by logantm2** [comment]
In the meantime I can just copy device arrays to host before giving them to mfem

**Comment by v-dobrev** [comment]
In the current `master` branch, assembly of `(Par)LinearForm`s is done on host only. However, there is a branch and PR under review to do this on devices: #2568. You can try that if you want.

In #2568, if you are using `DomainLFIntegrator`, you need to convert its `Coefficient` to a `QuadratureFunctionCoefficient` (with data on the device) and then there will be no host-to-device transfers during the r.h.s. assembly (you just need to set the `LinearAssemblyLevel` to `FULL` by calling `LinearForm::SetAssemblyLevel`). If your r.h.s. data is given in the form of a `(Par)GridFunction`, you can evaluate it (on device) at the required quadrature points using a suitable `QuadratureInterpolator` operator which can be accessed using the method `FiniteElementSpace::GetQuadratureInterpolator`. The resulting data can be stored in a `QudratureFunction` (which is a `Vector`) which, in turn, can be wrapped as a `QuadratureFunctionCoefficient`.

I realize this description is not very detailed, so let me know if you have any questions.

Regarding the use of an existing device pointer with a `(Par)GridFunction`: we have not added yet a convenient constructor/method for that, so you need a few more lines to achieve that:
```c++
   double *device_ptr;
   // allocate and set 'device_ptr'
   ParFiniteElementSpace pfes(...);
   ParGridFunction f(&pfes, nullptr);
   {
      int s = pfes.GetVSize();
      Memory<double> mem(device_ptr, s, MemoryType::DEVICE, false);
      mem.UseDevice(true);
      f.NewMemoryAndSize(mem, s, true);
   }
```
We should probably add a constructor to simplify this, maybe something like this:
```c++
   ParGridFunction(ParFiniteElementSpace *pf, double *data, MemoryType mt);
```
The constructor we have now:
```c++
   ParGridFunction(ParFiniteElementSpace *pf, double *data) :
```
assumes that `data` is a host pointer, i.e. its `MemoryType` is `Device::GetHostMemoryType()` which is typically `MemoryType::HOST`.

Regarding `RecoverFEMSolution`: the result should be on device unless that could not be avoided for some reason in a particular situation. You can check if the result is available on device without the need to copy it to device using `x.GetMemory().DeviceIsValid()`. To access the data on device, you can simply call `x.Read()` which will do a host-to-device copy automatically, if the data is not valid on device already.

**Comment by logantm2** [comment]
That seems to work perfectly, thanks!
