### ISSUE TITLE
Sedov unit test question

### ISSUE THREAD

**Issue by mlstowell** [mfem/mfem#2745]
I may be missing something but it looks like `Mrho` and `rhs` are not being used in the following lines. Also `rho_z` is not set so the result of line 1862 might be undefined.

https://github.com/mfem/mfem/blob/0f239c22e03b8e3b7d8e3311597ca6d809e8f5c2/tests/unit/miniapps/test_sedov.cpp#L1856-L1863

I think we should fix these issues and perhaps add a comment explaining the need for this method.

**Comment by mlstowell** [comment]
ping: @camierjs

**Comment by camierjs** [comment]
I think it's mainly used for `visualization` purposes - it should be removed from this tests here.

**Comment by mlstowell** [comment]
> I think it's mainly used for `visualization` purposes - it should be removed from this tests here.

Thanks, @camierjs, do you mean the entire function or just the unused variables?

**Comment by camierjs** [comment]
The entire function can be removed in the test, yes.
