### ISSUE TITLE
Nonlinear solver+ODE solver: continuity equation

### ISSUE THREAD

**Issue by jontateixeira** [mfem/mfem#2755]
Hi everyone and happy new year!

I am new to MFEM and a little bit new in C++, and I would like to ask for help or guidance. I am trying to solve a simple case of a single phase flow (continuity) equation:

<img src="https://latex.codecogs.com/png.image?\dpi{100}&space;\bg_white&space;\frac{\partial\phi\rho(u)}{\partial&space;t}-\nabla(\rho(u)\frac{\bf&space;K}{\mu}\nabla&space;u)&space;=&space;f" title="\bg_white \frac{\phi\partial\rho(u)}{\partial t}-\nabla(\rho(u)\frac{\bf K}{\mu}\nabla u)=f" />

where: <img src="https://latex.codecogs.com/png.image?\dpi{100}&space;\bg_white&space;\inline&space;\rho(u)" /> is a nonlinear function w.r.t <img src="https://latex.codecogs.com/png.image?\dpi{100}&space;\bg_white&space;\inline&space;u" /> (something like: <img src="https://latex.codecogs.com/png.image?\dpi{100}&space;\bg_white&space;\inline&space;\rho(u)=\rho_{0}&space;e^{\beta&space;(u-u_{0})}" title="\bg_white \inline \rho(u)=\rho_{0} e^{\beta (u-u_{0})}" /> , where: <img src="https://latex.codecogs.com/png.image?\dpi{100}&space;\bg_white&space;\inline&space;\rho_{0},&space;\beta,&space;u_{0}" title="\bg_white \inline \rho_{0},&space;\beta,&space;u_{0}" /> are const.). The weak form of the above equation, using H1 space, is:

`(phi*drho/dt, v) + (rho*K/mu*grad(u), grad(v)) = (f,v) + <gN, v>`

with `-rho*K/mu*grad(u)*normal = gN`, and `u` and `v` as trial and test functions, respectively.

To solve this problem, I am trying merging features of ex10 (newton solver) and ex16 (ODE solver). Right now, I am just focusing on how to deal with the l.h.s. of the weak form (only Dirichlet b.c.).

I followed issues [#102](https://github.com/mfem/mfem/issues/102), [#1064](https://github.com/mfem/mfem/issues/1064) and [#1091](https://github.com/mfem/mfem/issues/1091). So I defined new classes for the missing `NonlinearFormIntegrator`s (`MassNLFIntegrator` and `DiffusionNLFIntegrator`), to compute the local residue (method `AssembleElementVector`):

`F(u) = (phi*drho/dt, v)_K + (rho*K/mu*grad(u), grad(v))_K`
 
and local Jacobian/gradients (method `AssembleElementGrad`):

`F'(du,u) = (phi*rho'*du/dt, v)_K + (rho'*K/mu*grad(u)*du, grad(v))_K + (rho*K/mu*grad(du), grad(v))_K`

To evolve the equation, I tried to follow ex16 and derive a new Operator from `TimeDependentOperator` class and implement `ImplicitSolve()`, which is called by an implicit `ODESolver` into `Step()`. However, I haven't managed to get it working because the ode solver solve:  `du/dt = f(u,t)` but the equation is `drho(u)/dt = f(u,t)`... So I'm not too sure if I'm missing something else that might be needed as well when doing this for the `ODESolver` class.

My questions are:

* When I followed issue [#1091](https://github.com/mfem/mfem/issues/1091), I can't find how to evaluate `rho' @ ip`, when assembling term `(rho'*K/mu*grad(u)*du, grad(v))_K`. Is there any class like `NonlinearGridFunctionCoefficient` or need to implement some derived/interface class?

* How to include the `ODESolver`s in this problem, maybe I need to insert just the unknown evolve into the newton solver and at the end compute the `du/dt`? like this:

```c++
void SinglePhaseOperator::ImplicitSolve(const double dt,
                                         const mfem::Vector &x, mfem::Vector &dx_dt)
{
   // storage u_old
   nl_oper->SetParameters(dt, &x);
   mfem::Vector zero, x_new(x);
   newton_solver.Mult(zero, x_new); // maybe set iterative_mode=false?
   MFEM_VERIFY(newton_solver.GetConverged(), "Newton solver did not converge.");
   subtract(1/dt, x_new, x, dx_dt);
}
```

If yes, How to handle the `NonlinearFormIntegrator` that assemble the term `(phi*drho/dt, v)_K`?

Thank you in advance for any help or guidance you can give.

Jonathan.

**Comment by jandrej** [comment]
Can you elaborate on the physics you are trying to implement? I can't identify the equation as a continuity equation for conservation of mass.

**Comment by jontateixeira** [comment]
Hello, 

Thank you @jandrej  for helping me!. So the equation, in the first post, is the combination of Darcy's equation[^1] with the law of conservation of fluid mass and using these assumptions:

* no gravity effects;
* the solid matrix is incompressible (for now...);
* porosity <img src="https://latex.codecogs.com/png.image?\dpi{120}&space;\bg_white&space;\inline&space;\phi" title="\bg_white \inline \phi" /> and permeability <img src="https://latex.codecogs.com/png.image?\dpi{100}&space;\bg_white&space;\inline&space;\mathbf{K}" title="\bg_white \inline \mathbf{K}" /> are constants (for now...);
* the fluid is compressible.
* isothermal flow (i.e. <img src="https://latex.codecogs.com/png.image?\dpi{100}&space;\bg_white&space;\inline&space;\rho&space;=&space;\rho\left&space;(&space;p,&space;T&space;\right&space;)&space;=&space;\rho\left&space;(&space;p\right&space;)" title="\bg_white \inline \rho = \rho\left ( p, T \right ) = \rho\left ( p\right )" />)

In that way, from fluid mass conservation in a porous medium:

<img src="https://latex.codecogs.com/png.image?\dpi{100}&space;\bg_white&space;\frac{\partial\phi\rho}{\partial&space;t}&space;&plus;&space;\nabla\cdot\left(\rho\mathbf{v_D}&space;\right)&space;=&space;f" title="\bg_white \frac{\partial\phi\rho}{\partial t} + \nabla\cdot\left(\rho\mathbf{v_D} \right) = f" />

using the Darcy equation: <img src="https://latex.codecogs.com/png.image?\dpi{100}&space;\bg_white&space;\inline&space;\mathbf{v_D}&space;=&space;-\frac{\mathbf{K}}{\mu}\nabla&space;p" title="\bg_white \inline \mathbf{v_D} = -\frac{\mathbf{K}}{\mu}\nabla p" />

produces ...

<img src="https://latex.codecogs.com/png.image?\dpi{120}&space;\bg_white&space;\inline&space;\frac{\partial\phi\rho(p)}{\partial&space;t}&space;-&space;\nabla\cdot(\rho(p)\frac{\bf&space;K}{\mu}\nabla&space;p)&space;=&space;f" title="\bg_white \inline \frac{\partial\phi\rho(p)}{\partial t} - \nabla\cdot(\rho(p)\frac{\bf K}{\mu}\nabla p) = f" />

where `p` is the fluid pressure (**u**nknown), and `rho` is fluid density <img src="https://latex.codecogs.com/png.image?\dpi{100}&space;\bg_white&space;\inline&space;\rho(p)&space;=&space;\rho_o&space;e^{\beta(p&space;-&space;p_o)}" title="\bg_white \inline \rho(p) = \rho_o e^{\beta(p - p_o)}" />, with `beta` as the isothermal compressibility.


[^1]: The constitutive relation that describes the flow of a fluid through a porous medium, see this [link](https://echo2.epfl.ch/VICAIRE/mod_3/chapt_6/main.htm).

**Comment by jandrej** [comment]
I still don't follow how you plan to solve
<img src=
"https://render.githubusercontent.com/render/math?math=%5Cdisplaystyle+%5Cbegin%7Balign%2A%7D%0A%5Cfrac%7B%5Cpartial+%5Crho%28p%29%7D%7B%5Cpartial+t%7D+%3D+f%28p%29%0A%5Cend%7Balign%2A%7D%0A" 
alt="\begin{align*}
\frac{\partial \rho(p)}{\partial t} = f(p)
\end{align*}
">
when the ODE solver uses a different formulation.

**Comment by jontateixeira** [comment]
Hi @jandrej,

My question is exactly this! I know that ODE solver need that the formulation must be write in this form:

<img src="https://latex.codecogs.com/svg.image?\bg_white&space;\frac{\partial&space;p}{\partial&space;t}&space;=&space;f\left&space;(&space;p&space;\right&space;)" title="\bg_white \frac{\partial p}{\partial t} = f\left ( p \right )" />

I would like to known if there is a way (or hackway) to solve this:

<img src="https://latex.codecogs.com/svg.image?\bg_white&space;\frac{\partial&space;\rho(p)}{\partial&space;t}&space;=&space;f\left&space;(&space;p&space;\right&space;)" title="\bg_white \frac{\partial \rho(p)}{\partial t} = f\left ( p \right )" />

I thought about doing this:

<img src="https://latex.codecogs.com/svg.image?\bg_white&space;\frac{\partial&space;p}{\partial&space;t}&space;=&space;M^{-1}&space;f\left&space;(&space;p&space;\right&space;)" title="\bg_white \frac{\partial p}{\partial t} = M^{-1} f\left ( p \right )" />

where `M=(phi*drho/dp, v)` using the known state (i.e. using `p` at time step `n-1`), with `v` as test functions.  Yet that form seems awkward to me

**Comment by v-dobrev** [comment]
Hi @jontateixeira,

Given your assumptions, it seems possible to write `p` as a function of `\rho` and then eliminate `p` from the equation. Have you considered this option?
