### ISSUE TITLE
Geometric multigrid for Nedelec spaces

### ISSUE THREAD

**Issue by sebastiangrimberg** [mfem/mfem#2758]
This might have been a silly idea, but I was interested in testing out a modification of `ex26`, which uses a `GeometricMultigrid` solver, for solving the problem from `ex3` in an H(curl) space. In testing I'm just applying AMS at the coarsest geometric level and have experimented with a few different smoothers. Things compile and run, but the iteration counts are very large compared to just applying AMS to the original assembled operator on the finest level when using either `h` or `p` refinement (even just a single level), in serial or parallel.

Maybe it's naive but I would hope the performance wouldn't be so bad, but correct me if I'm wrong to think this. Looking back at the initial Multigrid PR #1097, it says that only H1 spaces are supported. Is this still true? It looks like from #2668 that the `TransferOperator` and `TrueTransferOperator` may actually work with ND spaces. I am just wondering if anyone has any information if I should expect this to work given the current MFEM features or if this isn't possible at the moment. If it should work and doesn't, it could be a bug in my code or could be pointing to something in the implementation which had not been previously tested.

**Comment by pazner** [comment]
Can you elaborate on the type of smoothers you have tried? You won't get good multigrid convergence on Maxwell problems with the standard smoothers you would use for Poisson.

Some of the multigrid features may not work properly with ND spaces (I'm thinking of the tensor-product p-multigrid transfer operators, in particular). I think h-multigrid should work fine though…

**Comment by sebastiangrimberg** [comment]
Ah yes of course, I was hoping that because I was only coarsening for a small number of levels I would be able to get away with standard smoothers and the coarse solve would be good enough to "get around" the typical Maxwell issues. This was probably a dumb assumption.

I only tried the Chebyshev from MFEM used in `ex26` as well as a Chebyshev and GS from Hypre, so all pretty standard approaches. Maybe I can implement or test out some fine level smoothers which are designed more particularly for curl-curl problems, though what I imagine I will find out is the best option is to just use a LOR solver.

**Comment by pazner** [comment]
`LORSolver<HypreAMS>` could be worth checking out (illustrated in the `plor_solvers` miniapp). You might also be interested in `MatrixFreeAMS` (or more generally the `GeneralAMS` class), which would allow you to use geometric multigrid for the related Poisson solves.

**Comment by sebastiangrimberg** [comment]
Yep! Those were the next steps. Thanks a lot!

**Comment by sebastiangrimberg** [comment]
Hi @pazner, I just wanted to ask a follow up question here with something I’ve seen that I’m not too familiar with. I played around with some special curl-curl specific smoothers and actually got this geometric MG to work quite nicely. However I notice a big change in convergence when dealing with problems with (homogeneous) Dirichlet BCs depending on how I build the coarse operators. 

If I explicitly multiply P^T A P out for coarse levels using the P transfer operator as an assembled matrix and the A matrix with rows/columns eliminated corresponding to fine space Dirichlet dofs, everything works well for both h- and p-refinement (I just threshold the resulting matrix to drop the near-zeros from the sparsity pattern). However if I instead construct the coarse operator by assembling the bilinear form on the coarse FE space, followed by eliminating rows/columns corresponding to the coarse boundary dofs, the convergence of the solver is really poor. Again this only shows up for problems with Dirichlet BCs, if BCs are not Dirichlet then the performance with either assembly method is similarly good.

I’m just wondering if there is a best practice or suggestion for this issue here. In `ex26/26p` they handle the BC elimination the latter way for an H1 space so I’m not sure if it should be more tricky when using a vector space.

Feel free to just close this again if you don’t know, but I’d appreciate any suggestions you or anyone else might have!

**Comment by psocratis** [comment]
Hi @sebastiangrimberg, 

Can you test that the entries in the residual vector corresponding to the essential dofs are zero at every stage of the v-cycle. The issue might be related to a couple of things. One could be the diagonal policy you are using, the second could be that the smoother you are using couples the boundary dofs with the interior. 

I'll be happy to look at a sample code that this happens. 

Thanks, 

Socratis

**Comment by sebastiangrimberg** [comment]
Hi @psocratis,

Thanks for the response. I've tried zeroing out the essential dofs at each prolongation or as part of the smoothers at each stage and it didn't seem to change results. Regarding the other points:

- I am just using the default diagonal policy for `HypreParMatrix` elimination which I believe just sets the diagonal entries to 1. Maybe this is incorrect at the coarser levels? Indeed if I look at the matrix P^T A P the rows/columns corresponding to essential coarse degrees of freedom have some non-diagonal entries, so it's almost like in order to get the same coarse matrix I would need to apply some different method to constrain the coarse essential dofs.
- I think the smoother is definitely doing this interior/boundary coupling since I'm using a hybrid smoother based on point smoothers for A and G^T A G at each level, where G is the discrete gradient matrix (first introduced [here](https://epubs.siam.org/doi/abs/10.1137/S0036142997326203?journalCode=sjnaam) I believe).

**Comment by psocratis** [comment]
> Thanks for the response. I've tried zeroing out the essential dofs at each prolongation or as part of the smoothers at each stage and it didn't seem to change results. Regarding the other points:

What I was suggesting is to check if they are already zero ...

**Comment by sebastiangrimberg** [comment]
Sorry for misunderstanding! Yup, indeed looking at the residual values they are do become nonzero for some essential dofs.

However some good news is that in my testing it looks like I hadn't totally accounted for the various ways to zero out the entries of the solution/residual at different levels to account for the BC, and by always zeroing out at the end of a restriction/prolongation I got things to work and converge. I think I was expecting before that the smoother on each level would fix this but didn't consider that the residual would be wrong. Anyway, this certainly works now and not sure why I hadn't tried this before! Thanks a lot for your help!

**Comment by psocratis** [comment]
I am glad it works. I am going to close this issue. Feel free to reopen it if anything else comes up. 

Best, 

Socratis
