### ISSUE TITLE
Product of two VectorCoefficient 

### ISSUE THREAD

**Issue by LeilaSalomon** [mfem/mfem#2762]
Hello,

I know :

- ProductCoefficient to obtain the product of two Coefficient.

- ScalarVectorProductCoefficient to obtain the product of a Coefficient and a VectorCoefficient. 

For 2  VectorCoefficient named **A** and **B**, I would like to know if there is an operator (seems to those mentioned above) able to solve the product : **A**x * **B**x + **A**y * **B**y ?

**Comment by mlstowell** [comment]
Hello, @LeilaSalomon, 

There is the [InnerProductCoefficient](https://github.com/mfem/mfem/blob/0f239c22e03b8e3b7d8e3311597ca6d809e8f5c2/fem/coefficient.hpp#L1484).

Best wishes,
Mark

**Comment by LeilaSalomon** [comment]
Thank you for your answer :)

Now if I had 3 VectorCoefficient named **A**, **B** and **C**. I woulk like to obtain an other VectorCoefficient (with 2 components) : 

First component : **A**x * **B**x + **A**y * **B**y 
Second component : **A**x * **C**x + **A**y * **C**y 

Is it possible without using GridFunction ?

**Comment by Andr00dz** [comment]
Hi @LeilaSalomon,

[VectorArrayCoefficient](https://mfem.github.io/doxygen/html/classmfem_1_1VectorArrayCoefficient.html) might be the coefficient you are looking for.

**Comment by LeilaSalomon** [comment]
> Hi @LeilaSalomon,
> 
> [VectorArrayCoefficient](https://mfem.github.io/doxygen/html/classmfem_1_1VectorArrayCoefficient.html) might be the coefficient you are looking for.

Hi @Andr00dz ! 

How can I build this VectorArrayCoefficient with the two InnerProductCoefficient ?

**Comment by Andr00dz** [comment]
When you have `AB = InnerProductCoefficient(A,B)` and `AC = InnerProductCoefficient(A,C)`,
you can create the VectorArrayCoefficient via:

```
VectorArrayCoefficient vCoeff(2) and use
vCoeff.Set(0, AB)
vCoeff.Set(1, AC) 
```

**Comment by LeilaSalomon** [comment]
> When you have `AB = InnerProductCoefficient(A,B)` and `AC = InnerProductCoefficient(A,C)`, you can create the VectorArrayCoefficient via:
> 
> ```
> VectorArrayCoefficient vCoeff(2) and use
> vCoeff.Set(0, AB)
> vCoeff.Set(1, AC) 
> ```

**Comment by LeilaSalomon** [comment]
> > When you have `AB = InnerProductCoefficient(A,B)` and `AC = InnerProductCoefficient(A,C)`, you can create the VectorArrayCoefficient via:
> > ```
> > VectorArrayCoefficient vCoeff(2) and use
> > vCoeff.Set(0, AB)
> > vCoeff.Set(1, AC) 
> > ```

**Comment by LeilaSalomon** [comment]
> When you have `AB = InnerProductCoefficient(A,B)` and `AC = InnerProductCoefficient(A,C)`, you can create the VectorArrayCoefficient via:
> 
> ```
> VectorArrayCoefficient vCoeff(2) and use
> vCoeff.Set(0, AB)
> vCoeff.Set(1, AC) 
> ```

The previous lines must be written like this :

```
 VectorArrayCoefficient vCoeff(2) 
 vCoeff.Set(0, &AB)
 vCoeff.Set(1, &AC) 
```

no ?

I have an error.. I can't understand what is wrong : 

![Error](https://user-images.githubusercontent.com/40572513/149522777-0df31123-0f73-4b4a-a42f-7c2b9da72876.png)

**Comment by Andr00dz** [comment]
You are right. Can you try the following: 
```
 VectorArrayCoefficient vCoeff(2) 
 vCoeff.Set(0, &AB, false)
 vCoeff.Set(1, &AC, false) 
```

**Comment by LeilaSalomon** [comment]
Ah yes I no longer have an error message!
What does `false` mean?

**Comment by Andr00dz** [comment]
With the additional `false`, you tell the `VectorArrayCoefficient vCoeff` that it is not the `owner` of the inserted coefficients `AB` and `AC`. This ensures that during the destruction of `vCoeff`, `AB` and `AC` will be not deleted and no double free errors occure. 
`AB` and `AC` will be destroryed afterwards, when their corresponding destructor is called.

In the [documentation](https://mfem.github.io/doxygen/html/classmfem_1_1VectorArrayCoefficient.html#ad16186ea72b057b4f9046bf32e580112), you can see that the ownership of inserted coefficients is per default `true`. 



Alternatively, the following should also work:

```
VectorArrayCoefficient vCoeff(2) 
vCoeff.Set(0, new InnerProductCoefficient(A,B))
vCoeff.Set(1, new InnerProductCoefficient(A,C)) 
```
This leads to the behavior that the inserted coefficients get automatically deleted when `vCoeff` gets destroyed.

**Comment by LeilaSalomon** [comment]
Ok, thank you very much for your help ! And informations !

Best wishes,

Leila

**Comment by mlstowell** [comment]
I'll close this now but feel free to reopen it if needed. Also, thanks @Andr00dz for your clear explanations.

Best wishes
