### ISSUE TITLE
VectorConvection for a source term 

### ISSUE THREAD

**Issue by LeilaSalomon** [mfem/mfem#2763]
Hello ! 

I would like to solve : 

![image](https://user-images.githubusercontent.com/40572513/149303863-aad1aecb-8ebc-4ddf-be1d-2e36492bd71e.png)

With **u** a know vector (source terme) **x** my unknow and omega my test function. 

I can't use VectorConvectionNLFIntegrator because  **u** in my case is a source term, and not a unknow.

Best wishes,

Leila

**Comment by v-dobrev** [comment]
If `u` is a FE function (e.g. a `(Par)GridFunction`) you can still use a `(Par)NonlinearForm` with a `VectorConvectionNLFIntegrator` -- to assemble the r.h.s, create the `(Par)NonlinearForm` and apply its action to `u` (to its true-vector representation, to be more precise) using `Mult`.

If `u` is given analytically (e.g. as a `VectorCoefficient`) then you can either:
1. project it to a vector `(Par)GridFunction` and then use the above, or
2. assuming you have two coefficients defining `u` and `∇u`, then you can form the product coefficient using a `MatrixVectorProductCoefficient`, and then use that in a `VectorDomainLFIntegrator` to assemble the r.h.s.; of course, if you know `u` analytically, then you can also just evaluate `f=(u⋅∇)u` analytically and then define a `VectorFunctionCoefficient` with this `f`.

**Comment by LeilaSalomon** [comment]
Hello @v-dobrev,

Thank you very much for your help !
