### ISSUE TITLE
Navigating ParMesh shared face connectivity

### ISSUE THREAD

**Issue by logantm2** [mfem/mfem#2768]
Is it possible to grab info from a `ParMesh` about how faces are shared between MPI ranks? Specifically, I'd like to loop through all the shared faces on an MPI rank and figure out, for each one, which MPI rank shares it, and the global element indices of the elements on either side of the face (or better yet, local element indices according to whichever MPI rank owns them). I noticed that `ExchangeFaceNbrData` seems to do something similar, but I'm not sure if the info I need is gathered there.

This is related to #2751: as particles move across MPI process boundaries, they need to be communicated to new ranks, and the element that they're in needs to be tracked.

**Comment by dylan-copeland** [comment]
Hi @logantm2, thanks for the question. Coincidentally, I have been working on this issue this week, for the general case of non-conforming AMR meshes. There seems to be no straightforward to get this information. I have had some ideas, but the best implementation may depend on some recent work by @YohannDudouit, see https://github.com/mfem/mfem/pull/2195. If you are only interested in the case of conforming meshes, there may be a simpler solution. In any case, I will keep this issue updated with any progress in supporting the non-conforming case.

**Comment by logantm2** [comment]
Actually that works out perfectly, we're restricting our purview to conforming meshes.

**Comment by dylan-copeland** [comment]
For the conforming case, the linked minimal example does what is needed (thanks to @pazner and @v-dobrev for helping with this).
[https://gist.github.com/pazner/5f2da685314dcd369f85da4e1aa5314d](url)

**Comment by logantm2** [comment]
Awesome, that does exactly what we need. That's a clever trick, using 0th order DG. Thanks!
