### ISSUE TITLE
Modify integration rule for bilinear forms

### ISSUE THREAD

**Issue by pmguilcher** [mfem/mfem#2773]
Hello,

I would like to give a specific integration rule to bilinear forms (MixedScalarMassIntegrator, MixedDirectionalDerivativeIntegrator) and linear forms (DomainLFGradIntegrator).

I know it is possible for DomainLFGradIntegrator. Could you please give me some advice to do it? I have to declare a new constructor for each form, with an integration rule as parameter, but I'm not sure of the way to call the base class then.

Pierre

**Comment by pazner** [comment]
Hello Pierre,

Just call `SetIntegrationRule` on the integrator after you create it — no need for a custom constructor, e.g.
```c++
MixedScalarMassIntegrator *integ = new MixedScalarMassIntegrator;
integ->SetIntegrationRule(ir);
a.AddDomainIntegrator(integ);
```

**Comment by pmguilcher** [comment]
Thank you very much, it works perfectly!

Thank you also for your quick answers, the helpdesk is always very fast with pertinent propositions.

Pierre
