### ISSUE TITLE
Integration points and shapes pre-computation

### ISSUE THREAD

**Issue by vkorchagova** [mfem/mfem#2774]
Good evening!

I'm working on the Discontinuous Galerkin solver based on MFEM. When I've profiled the code by gperftools, I saw that I should compute values of shape functions every time step several times (for face flux computation, for average values used in limiter and for unlimited solution values on faces in limiter procedure). Is it possible to store pre-computed values for shapes and integration points and use standard MFEM functions with these values? I'm sure it could make my solver rather faster...

Many thanks in advance,
Victoria

**Comment by YohannDudouit** [comment]
Hi Victoria,

Could you send us the gperftools trace here to help us understand better what is happening.

Thanks,
Yohann
