### ISSUE TITLE
Possible memory leak in ParaViewDataCollection->Save()

### ISSUE THREAD

**Issue by vkorchagova** [mfem/mfem#2783]
Hello everyone!

I've found an overflow of memory on cluster nodes when I compute problems with large meshes. I checked a memory consumption by `htop` command, and I saw a step-like increase of memory usage in moments of data writing by function `ParaViewDataCollection->Save()`.
To reproduce a problem, I added ParaViewDataCollection into Example 18; here, you can find pieces of code:
```
   args.AddOption(&vis_steps, "-vs", "--visualization-steps",
                  "Visualize every n-th timestep.");
   **args.AddOption(&paraview, "-paraview", "--paraview-data", "-no-paraview",
                  "--no-paraview-data",
                  "Enable or disable ParaView visu.");**

   args.Parse();
``` 
 .....
```
  **ParaViewDataCollection *pd = NULL;
    if (paraview)
    {
        pd = new ParaViewDataCollection("PV", &pmesh);
        pd->RegisterField("mom", &mom);

        pd->SetLevelsOfDetail(1);
        pd->SetCycle(0);
        pd->SetTime(0.0);
        pd->Save();

        if (myRank == 0) cout << "Paraview OK" << endl;
    }**

   // 9. Set up the nonlinear form corresponding to the DG discretization of the
   //    flux divergence, and assemble the corresponding mass matrix.
   MixedBilinearForm Aflux(&dfes, &fes);
```
   ....
```
   if (done || ti % vis_steps == 0)
      {
         **if (paraview)
            {
                pd->SetCycle(ti);
                pd->SetTime(t);
                pd->Save();
                if (mpi.Root()) {cout << "ParaView OK\n";}
            }**
```
I've run an application by the following command line (ParaView visualisation is switched on by default):
`./ex18par -m ../../data/periodic-square.mesh -o 1 -rs 5 -rp 0 -s 2 -vs 1 -tf 1 -dt 0.01 -c -1`
There were 100 time steps; I've saved ParaView frame every time step; in the end, I've seen near 40 Mb extra memory usage by `htop`.
When I didn't write ParaView frames, memory usage was the constant value.
The problem exists both in serial and parallel mode.

Therefore, it can be two ways: some memory leak in ParaviewDataCollection->Save() function or some wrong usage of ParaviewDataCollection. What can we do?

I'll be very-very thankful for help!

--
Best regards, Victoria

**Comment by pazner** [comment]
Hello @vkorchagova,

I am not able to reproduce this problem. I tried profiling the code with `valgrind --tool=massif`, but the memory usage appeared roughly constant over time.

ParaView output will require some memory overhead, but it shouldn't increase meaningfully as you run the code for more time steps.

If you have valgrind, could you try profiling a minimal example with [massif](https://valgrind.org/docs/manual/ms-manual.html) and seeing if `ms_print` shows an increase? This is what I am seeing:
```
    MB
42.85^        #
     |        #@::::@::::::::::::::::::::::@:::@:::@@:::@:::@::::::@::::::@::::::@:::
     |       :#@::: @::: ::::::::::: :::: :@:::@:::@ : :@:::@::::::@::::::@::::::@:::
     |       :#@::: @::: ::::::::::: :::: :@:::@:::@ : :@:::@::::::@::::::@::::::@:::
     |       :#@::: @::: ::::::::::: :::: :@:::@:::@ : :@:::@::::::@::::::@::::::@:::
     |       :#@::: @::: ::::::::::: :::: :@:::@:::@ : :@:::@::::::@::::::@::::::@:::
     |       :#@::: @::: ::::::::::: :::: :@:::@:::@ : :@:::@::::::@::::::@::::::@:::
     |     @@:#@::: @::: ::::::::::: :::: :@:::@:::@ : :@:::@::::::@::::::@::::::@:::
     |    @@ :#@::: @::: ::::::::::: :::: :@:::@:::@ : :@:::@::::::@::::::@::::::@:::
     |::@:@@ :#@::: @::: ::::::::::: :::: :@:::@:::@ : :@:::@::::::@::::::@::::::@:::
   0 +------------------------------------------------------------------------------>Gi
     0                                                                          190.7
```

**Comment by vkorchagova** [comment]
Hello @pazner,

I'm so sorry -- the problem was in hardware on my cluster. When remedied works were carried out, Valgrind gave me the roughly constant memory usage too.

Many thanks for your patience!
