### ISSUE TITLE
Segfault in GetVectorGradient on an interior boundary element

### ISSUE THREAD

**Issue by cbritopacheco** [mfem/mfem#2789]
# Goal
Dear MFEM team and community,
I would like to compute the Jacobian matrix of a `GridFunction` on a boundary element which is in the interior. For example, given the following mesh, I would like to calculate it on the boundary with attribute 4.

<img width="623" alt="Screenshot 2022-01-26 at 10 43 29 AM" src="https://user-images.githubusercontent.com/6352283/151140005-fadc71ef-f402-478e-9a59-fb404c6497cf.png">

# Problem

Unfortunately, `GetVectorGradient` results in a seg fault since the `FaceElementTransformation` is `NULL` at the interior boundary and I am unable to get the gradient matrix.

```c++
case ElementTransformation::BDR_ELEMENT:
{
   // In order to capture the normal component of the gradient we
   // must evaluate it in the neighboring element.
   FaceElementTransformations * FET =
      fes->GetMesh()->GetBdrFaceTransformations(T.ElementNo); // <------------- Will return NULL because it is in the interior

   // Boundary elements and Boundary Faces may have different
   // orientations so adjust the integration point if necessary.
   int o = 0;
   if (fes->GetMesh()->Dimension() == 3)
   {
      int f;
      fes->GetMesh()->GetBdrElementFace(T.ElementNo, &f, &o);
   }

   IntegrationPoint fip;
   be_to_bfe(FET->GetGeometryType(), o, T.GetIntPoint(), fip); // <----------- Seg fault here

   // .............
}
```

Is there any workaround to achieve this? Thank you in advance for any response.

**Comment by cbritopacheco** [comment]
After a bit of thinking, I think I could solve the problem by doing the interior boundary check in my own code and perform some sort of interpolation/averaging of the (domain) element vector gradients at their integration points. Something along the lines of #733, where I could get the integration points of my boundary element and perform the averaging.

```c++
   // Get the ElementTransformation pointer Tr
   // ...

   Geometry::Type geom = Tr->GetGeometryType();
   const IntegrationPoint &center = Geometries.GetCenter(geom);
   // use center

   const IntegrationRule &vert_ir = *Geometries.GetVertices(geom);
   for (int vi = 0; vi < vert_ir.GetNPoints(); vi++)
   {
      const IntegrationPoint &vert = vert_ir.IntPoint(vi);
      // use vert
   }
```

 However, I'm unsure if this is the correct approach or maybe if there is something that is already implemented in the library?

**Comment by cbritopacheco** [comment]
I have changed the title since the more I look at this, the more I think it's a bug. I have tried this on other FEM software with succesful results so I am surprised MFEM would not be able to handle such a case.

**Comment by v-dobrev** [comment]
Hi @cbritopacheco,

The method `GridFunction::GetVectorGradient()` cannot be used to compute the gradient on an interior "boundary" element or interior face -- the gradient is not well defined there, because there are two different values on the two sides of the face. You can compute the values on both sides and then combine them any way you want. This can be achieved with code like this:
```c++
   // Mesh *mesh = ...;
   // GridFunction *sol = ...;
   int be_id = 5; // boundary element id
   int face_id = mesh->GetBdrFace(be_id); // face id corresponding to be_id
   FaceElementTransformations *FT =
      mesh->GetFaceElementTransformations(face_id);
   // initialize face_ip with the reference face point where you want to compute
   // the two gradients:
   const IntegrationPoint &face_ip =
      Geometries.GetCenter(FT->GetGeometryType());
   FT->SetAllIntPoints(&face_ip);
   DenseMatrix grad1, grad2;
   sol->GetVectorGradient(FT->GetElement1Transformation(), grad1);
   if (FT->Elem2No >= 0) // check if the face is interior
   {
      sol->GetVectorGradient(FT->GetElement2Transformation(), grad2);
      // combine grad1 and grad2 into grad1 ...
   }
   // use grad1 ...
```
If you are running in parallel, the interior "boundary" element may happen to be between two different processors and  in such case one needs to perform communication to get the gradient on the other side. Let me know if you need more details about handling this case in parallel.

**Comment by cbritopacheco** [comment]
Ho @v-dobrev, thank you for your answer. Indeed the gradient will not be necessarily defined. 

I am now wondering how the edge orientation works in MFEM for interior boundaries. This way I could specify which is the interior domain (either left or right element) so I can use the element's gradient as used for the exterior boundary case.

Is there some kind of orientation defined on interior boundaries?

Best
