### ISSUE TITLE
Nonlinear Poisson/Laplace solve

### ISSUE THREAD

**Issue by logantm2** [mfem/mfem#2791]
I'm working on a modified version of the Poisson equation for what we're calling an adiabatic or Boltzmann approximation:
![image](https://user-images.githubusercontent.com/53028846/151257896-5a2c79f1-a4e7-4f19-86dc-8068416a5070.png)

where q, n, k, T are all known constants. The laplacian and rho terms were pretty straightforward to handle, but I'm wondering how to incorporate the nonlinear term using MFEM APIs. After looking a bit through the source code, it looks like we'll have to write a class that inherits from `NonlinearFormIntegrator` that overrides the virtual methods needed to integrate it. Then we can construct a `ParNonlinearForm` and add our custom NLF integrator to it, then just hand it over to a `NewtonSolver`. Is this the recommended approach for this?

**Comment by jandrej** [comment]
That is the recommended approach, yes. You also want to create your own `Operator` s.t. you can combine the linear part (Laplacian) with the nonlinear part.

**Comment by logantm2** [comment]
Gotcha, I'm working through the integrator now. It makes sense to me that `GetElementEnergy` in our case would just be the integral of the usual electric field density 
![image](https://user-images.githubusercontent.com/53028846/151421314-0c1ca3c8-5ca1-444e-85bd-18eea0cdd664.png)

and `AssembleElementVector` fills in `elvect` with 
![image](https://user-images.githubusercontent.com/53028846/151421405-253086d2-1dd4-4fea-9dc9-4236f75ef21c.png)
for each element dof v_i, where I'm just using f(u) in place of the exponential term above. I have some initial implementations for these. But what should `AssembleElementGrad` be doing?

**Comment by jandrej** [comment]
I don't think you need `GetElementEnergy` at all for your purpose. You also have the integrator for the linear Poisson part already. You need to implement `AssembleElementVector` 
<img src="https://latex.codecogs.com/svg.image?-qn\exp{\left(\frac{-qu}{kT_e}\right)}" title="-qn\exp{(\frac{-qu}{kT_e})}" />
and `AssembleElementGrad` for the linearization of this term.

**Comment by logantm2** [comment]
Cool, I'll just 86 the `GetElementEnergy` override then. 

I guess I'm confused about `AssembleElementGrad` because I would have expected it to be outputting
![image](https://user-images.githubusercontent.com/53028846/151428974-431050e1-f97a-4cb6-9d49-c55c24ed643c.png)

which would be a `DenseMatrix` with size (number of dofs, number of dimensions) (or the transpose of that or whatever). But looking at other implementations, the output has size (number of dofs, number of dofs), for example here:
https://github.com/mfem/mfem/blob/9d8043b9e78dcdcd86639bbb28d3bd7b514fb5e2/miniapps/shifted/dist_solver.cpp#L495-L506
I don't know enough about the physical model here to reverse engineer what `elmat` actually is.

Does this question make sense? Sorry, I'm picking up the finite element method as I go along

**Comment by logantm2** [comment]
@dcurreli was something similar involved in writing FEMPIC?

**Comment by dcurreli** [comment]
Need to see how MFEM sets up a Newton solver for a NL problem

**Comment by logantm2** [comment]
Returning to this after putting out some fires. I found [this](https://mfem.org/nonlininteg/) which implies that `AssembleElementGrad` integrates the Gateaux derivative of the nonlinear functional. That's pretty straightforward for us, so I have the nonlinear form integrator done.

Moving on now to the custom `Operator`. I'm using example 19 as a guide, but since most of the meat is in the custom preconditioner, and I'm not very familiar with the problem it's solving, it'll take me a hot second to figure out how to rewire it for our problem. @jandrej are there any other examples that might be more useful? I get the sense our problem is much simpler

**Comment by dcurreli** [comment]
Thanks @pazner, this is really helpful!

**Comment by logantm2** [comment]
@pazner this is a massive help, thanks!

This got me most of the way there, but there's one last roadblock. I can't seem to get it to converge with a nonzero RHS. [This gist](https://gist.github.com/logantm2/e919f8f6bce9089b485544db525d54e8) is an example -- the only significant changes are adding a unit domain integrator to the `LinearForm b` and switching from UMFPack to the built-in CG solver.

Interestingly this problem fails to converge even when line 113 (where the nonlinear term is added to `n`) is commented out, so evidently I'm just missing a step. Maybe something to do with eliminating BCs on `b`?

**Comment by jandrej** [comment]
Yea, this is due lacking treatment of Dirichlet in your "RHS". I'd move it to the LHS into the `NonlinearMassIntegrator`. In general I like to have a form of `R(U) = 0` for nonlinear problems. But it's not required, just more convenient.

**Comment by pazner** [comment]
The issue is that your grid function `x` has zero values at the boundary, however the RHS `b` has non-zero values. For the solve to work, the RHS boundary values have to be compatible.

You can achieve this as follows:
```c++
ConstantCoefficient one(1.0);
b.AddDomainIntegrator(new DomainLFIntegrator(one));
b.Assemble();
b.SetSubVector(boundary_dofs, 0.0);
```

Note that with this RHS, the solution is trivial:

<img width="441" alt="-_Delta_u_+_exp(" src="https://user-images.githubusercontent.com/11493037/154334678-0d9dbfe0-5861-4b85-9451-b34a5c876414.png">

You can try with a different coefficient e.g. `ConstantCoefficient coeff(5.0);` to get a non-trivial solve.

**Comment by pazner** [comment]
You can also do this more conveniently using `NonlinearForm::SetEssentialBC` like this:
```diff
    // 6. Set up the nonlinear form n(u,v) = (grad u, grad v) + (f(u), v)
    NonlinearForm n(&fespace);
    n.AddDomainIntegrator(new NonlinearMassIntegrator(fespace));
    n.AddDomainIntegrator(new DiffusionIntegrator);
-   n.SetEssentialTrueDofs(boundary_dofs);
 
    // 7. Set up the the right-hand side.
    LinearForm b(&fespace);
    if (nonzero_rhs) {
        ConstantCoefficient one(1.0);
        b.AddDomainIntegrator(new DomainLFIntegrator(one));
        b.Assemble();
    }
    else {
        b = 0.0;
    }
 
+   n.SetEssentialBC(boundary_dofs, &b);
```

**Comment by jandrej** [comment]
Careful with that. You need the attribute list as the first argument, not the dof list.

**Comment by logantm2** [comment]
Ahh, yep, that makes sense. Using the `SetSubVector` method works great for us, and it now works fine in serial.

One last hiccup: I'm getting the following error when attempting to run a parallel version:
```
Verification failed: (x.Size() == Width()) is false:
 --> invalid input Vector size
 ... in function: const mfem::Vector& mfem::NonlinearForm::Prolongate(const mfem::Vector&) const
 ... in file: fem/nonlinearform.cpp:133
```
In this case, `x` is a `ParLinearForm`. This error appears to pop up because it has length `GetVSize` whereas the `NonLinearForm`'s underlying `Operator` has width `GetTrueVSize`. I'm guessing this didn't happen to me before because `FormLinearSystem` eliminates the "false" dofs from the stiffness matrix, but since we're sidestepping that here, I'm not sure how best to proceed.

[Here's my current attempt](https://gist.github.com/logantm2/983b7dc68c170eb5375cce00afe73961)

**Comment by pazner** [comment]
Yes, the operator acts on a "true DOF vector", and the grid function and linear form are "DOF vectors", and so the sizes are incompatible.

The difference is that in parallel, a "DOF vector" will contain duplicated entries, since two MPI ranks with a common interface will both have copies of the "shared DOFs". In contrast, a "true DOF vector" will only have one copy of each DOF (a particular MPI rank is considered the owner of each DOF, and the other ranks are just borrowing). Furthermore, in the AMR setting, a DOF vector may contain "constrained DOFs" that are not really degrees of freedom (they are completely determined by the AMR constraints), whereas a true DOF vector does not contain these entries.

These concepts are described in greater detail in the [primal-dual vector documentation](https://mfem.org/pri-dual-vec/) and the [MFEM paper](http://dx.doi.org/10.1016/j.camwa.2020.06.009).

You can obtain the true DOF vectors for your problem like this:

```c++
// x is the ParGridFunction, b is the ParLinearForm
Vector B(fespace.GetTrueVSize()), X(fespace.GetTrueVSize());
b.ParallelAssemble(B);
x.ParallelProject(X);
```

Then, after the solve `newton.Mult(B, X);`, you can get the result in the form of a DOF vector by calling `x.Distribute(X);`.

**Comment by pazner** [comment]
By the way, for larger/more difficult problems, you will definitely want to configure your CG solver and use a preconditioner, e.g.
```c++
HypreBoomerAMG amg;
amg.SetPrintLevel(0);

CGSolver solver(MPI_COMM_WORLD);
solver.SetMaxIter(20);
solver.SetRelTol(1e-8);
solver.SetPreconditioner(amg);
solver.SetPrintLevel(IterativeSolver::PrintLevel().FirstAndLast());
```

**Comment by logantm2** [comment]
Awesome, working well now!
