### ISSUE TITLE
SEM and non-blocky diffusion matrix

### ISSUE THREAD

**Issue by vasily-golubev** [mfem/mfem#2792]
Hello, I am trying to implement trivial solver based on the spectral element method using MFEM library. As far as I understand, the key idea of SEM is to use the same points for interpolation iside the element and for integration. It must give us diagonal matrix mass and blocky diffusion matrix in 1D case. Firstly, I realized, that by default MassIntegrator uses polynomials with the higher degree that I expect using BasisType::GaussLobatto. I fixed it manually with SetIntegrationRule call. Now mass matrix is diagonal, but: 1) the order of values in it is not the same as I expected theoretically 2) the diffusion matrix is non-blocky as expected. As far as I understand the reason is the difference in DoF enumeration or basis function enumeration or smth. that is close to it. Is it possible to set the enumeration manually? Or maybe I do smth. other wrong? I prepares example for demonstration. Thank you in advance.
```c++
#include "mfem.hpp"
#include <fstream>
#include <iostream>

using namespace std;
using namespace mfem;


int main(int argc, char *argv[]) {
	const int dim = 1;
	const double Sx = 2;
	const unsigned int Nx = 2;
	const int order = 2;
	Mesh mesh = Mesh::MakeCartesian1D(Nx, Sx);
	H1_FECollection fe_coll(order, dim, BasisType::GaussLobatto);
	FiniteElementSpace fespace(&mesh, &fe_coll);
	// Now we integrate using the same points in element!!!
	IntegrationRules lobatto_intrules(0, Quadrature1D::GaussLobatto);
	const int exact = 2 * order - 1;
	const IntegrationRule *ir = &lobatto_intrules.Get(Geometry::SEGMENT, exact);
	for (int i = 0; i < ir->GetNPoints(); i++)
		cout << "Point " << i << " with coordinate " << ir->IntPoint(i).x << " and weight " << ir->IntPoint(i).weight << endl;
	// Diagonal mass matrix
	BilinearForm M(&fespace);
	MassIntegrator *mi = new MassIntegrator();
	mi->SetIntegrationRule(*ir);
	M.AddDomainIntegrator(mi);
	M.Assemble();
	M.Finalize();
	const SparseMatrix Mmat = M.SpMat();
	Mmat.PrintMatlab();
	// Blocky diffusion matrix
	BilinearForm K(&fespace);
	DiffusionIntegrator *di = new DiffusionIntegrator();
	di->SetIntegrationRule(*ir);
	K.AddDomainIntegrator(di);
	K.Assemble();
	K.Finalize();
	const SparseMatrix Kmat = K.SpMat();
	Kmat.PrintMatlab();
	return 0;
}
```

**Comment by pazner** [comment]
Hello @vasily-golubev,

Yes, you are correct, the correct way to implement SEM in MFEM is to set the integration rules to use collocated quadrature like you have done. Your implementation looks correct to me.

Why do you expect the entries of the mass matrix to be different?

Also, what do you mean by a "blocky diffusion matrix"? The DOF ordering is not customizable, but you can multiply by a permutation if you need a different ordering.

**Comment by vasily-golubev** [comment]
Thanks a lot for your answer!

According to the Igel book (https://www.researchgate.net/publication/283566366_Computational_Seismology_A_Practical_Introduction) I expected to obtain the global diffusion matrix in the form, when it contains local diffusion matrixes on it's diagonal (slightly modified at element intersections). And zeroes at the other positions.

Can you point me where to look for "but you can multiply by a permutation if you need a different ordering" ?

If possible, I would like to ask more questions.
After the spatial discretization I obtain the standard equation like:
Mu'' + Ku = f,
where M is diagonal matrix, u and f depend on the time and symbol ' means the time derivative. I want to use the trivial explicit second order scheme for solving it. Currently I do manually smth like:
U_new = dt^2M^(-1)[F_current-K*U_current] + 2*U_current - U_old.
I uderstand the limit on the time step occured, but I agree with it (wave problem is considered).
Is it possible to use some internal time-stepping method from MFEM library? I found smth. for first-order problem, but I think it is not efficient to reduce my second-order problem to the first-order system. Or maybe I am wrong?

Many thanks for your support.

**Comment by pazner** [comment]
Yes, in general you will get something that looks like copies of the local diffusion matrix, with modifications for the shared degrees of freedom. It might just be hard to identify this structure because of the matrix orderings.

If I use your code to assemble one element with length 1, I obtain the matrix
```
  2.33333    0.333333  -2.66667
  0.333333   2.33333   -2.66667
 -2.66667   -2.66667    5.33333
```
and if I use your code to assemble two elements, with total length 2, I obtain:
```
  2.33333    0.333333    ⋅        -2.66667    ⋅ 
  0.333333   4.66667    0.333333  -2.66667  -2.66667
   ⋅         0.333333   2.33333     ⋅       -2.66667
 -2.66667   -2.66667     ⋅         5.33333    ⋅ 
   ⋅        -2.66667   -2.66667     ⋅        5.33333
```

You should be able to identify that many of the matrix entries from the local matrix appear in the global matrix.

For solving second-order ODE problems, you can take a look at the abstract base class `SecondOrderODESolver`, and the specific methods `NewmarkSolver` and `GeneralizedAlpha2Solver` (and its subclasses).

**Comment by vasily-golubev** [comment]
Thanks a lot! Now I am trying to look through recent articles about effective time-stepping algorithm in acoustic problems. It looks like people use explicit solvers to reduce the computational time. In general, NewmarkSolver in this case is equal to the same procedure: U_new = dt^2M^(-1)[F_current-KU_current] + 2U_current - U_old.
I can't find if I can easily apply PML conditions in MFEM for acoustic case. Maybe you can point me some related examples?
Thank you in advance.

**Comment by pazner** [comment]
> I can't find if I can easily apply PML conditions in MFEM for acoustic case. Maybe you can point me some related examples?

MFEM's [example 25](https://mfem.org/examples/#ex25) uses a PML for a Maxwell problem. Maybe this would be helpful for you. @psocratis would know the most about implementing PMLs.

**Comment by pazner** [comment]
> I found that in https://github.com/mfem/mfem/blob/master/linalg/ode.cpp at line 1045 "f->SetTime(t + dt);" doesn't influence on the further compuation process. Maybe it is better to leave only the same code in line 1051?

Indeed, that line looks like it is unnecessary.

> The second question is related to the NewmarkSolver theory. If gamma ==1/2, betta == 0 and no dx/dt dependence in the right side of the equation - shouldn't the method be conditionally stable? I am in doubt because of the check at line 1022 (https://github.com/mfem/mfem/blob/master/linalg/ode.cpp).

Perhaps @IdoAkkerman would be able to answer this question — I think the second-order ODE implementation is due to him.
