### ISSUE TITLE
Prolongation matrix on non-conforming meshes with tdof size

### ISSUE THREAD

**Issue by davidherreroperez** [mfem/mfem#2793]
Hi,

I am trying to set up the restriction and interpolation operators for a geometric multigrid using AMR.
I can obtain the prolongation matrix after refinement using [FiniteElementSpace::GetUpdateOperator](https://mfem.github.io/doxygen/html/classmfem_1_1FiniteElementSpace.html#ab7e045bc3c8591eedb503e631ff846e2) but the dimension of the operator is the finite element dofs (VSize). Can I obtain this operator with the dimension of the tdofs (TrueVSize)?. Is it possible to modify this operator using [FiniteElementSpace::GetProlongationMatrix](https://mfem.github.io/doxygen/html/classmfem_1_1FiniteElementSpace.html#ad478970de28d32875b2f964faf3cd62a) to obtain the prolongation matrix with tdof dimension? I would appreciate it if you could indicate to me some similar operations in the code.

Thanks in advance.

**Comment by psocratis** [comment]
Hi @davidherreroperez, 

Yes, you can use the `TrueTransferOperator`. You can also take a look in ex26.cpp/ex26p.cpp for an example of geometric multrigrid. 

Best, 

Socratis
