### ISSUE TITLE
Is it dicouraged to use SuiteSparse with METIS5?

### ISSUE THREAD

**Issue by sshiraiwa** [mfem/mfem#2795]
I started to use UMPFACK and I notice CMAKE show the warning
'''
  *** Warning: using SuiteSparse with METIS v5!
'''
Is there any risk to continue using METIS v5 or it would be better to use an old version?

**Comment by v-dobrev** [comment]
As long as you use the same version of METIS when you build both SuiteSparse and MFEM, there should be no problem.

I think this warning is from around the time when SuiteSparse was dependent on METIS v4 and if MFEM was built with METIS v5 that could cause issues.

At this point we can probably just remove the warning.

**Comment by sshiraiwa** [comment]
Okay. Thank you for the confirmation.
