### ISSUE TITLE
Invalid mesh topology error

### ISSUE THREAD

**Issue by Andr00dz** [mfem/mfem#2798]
Hi,

I constructed the following mesh in GMSH 4.8.2:
![grafik](https://user-images.githubusercontent.com/56828429/151986754-ccf0c574-a0b4-4e09-a245-2ae03192900c.png)

Unfortunately, MFEM/GLVIS is not able to process this mesh.
Calling `glvis -m mesh.msh`, produces the following error
```
Elements with wrong orientation: 276 / 324 (NOT FIXED)
Boundary elements with wrong orientation: 14 / 88 (fixed)


Verification failed: (faces_info[i].Elem2No < 0 || faces_info[i].Elem2Inf%2 != 0) is false:
 --> Invalid mesh topology. Interior face with incompatible orientations.
 ... in function: virtual void mfem::Mesh::Finalize(bool, bool)
 ... in file: mesh/mesh.cpp:2671

Aborted (core dumped)
```

The domain consists of only five parts, which are created via simple `Curve Loops` and `Plane Surface` commands.
It seems, that there are some interior faces with wrong orientations in this mesh and I dont know why. Is there a way to fix this problem, or is this type of mesh construction not supported?

The `.msh` file is created from the `.geo` with the following command:
`gmsh mesh.geo -1 -2 -format msh2 -o mesh.msh`

My `.geo` file is linked here https://pastebin.com/4NRcfMxF
The corresponding `.msh` file https://pastebin.com/j0rA975S

**Comment by sshiraiwa** [comment]
Hmmm... I got this with GMSH 4.5.6 and  4.9.3  ![image](https://user-images.githubusercontent.com/1929159/151994668-c00c2fa0-0c78-48d4-8f66-2194777aded9.png)

**Comment by Andr00dz** [comment]
Switching to `GMSH 4.9.3` solved my problem. Thank you for helping!
