### ISSUE TITLE
kappa value for penalizing term in Discontinuous Galerkin

### ISSUE THREAD

**Issue by pmguilcher** [mfem/mfem#2806]
Hello,

I am using a DG formulation which relies on a stabilizing kappa coefficient for the bilinear and linear forms.
The kappa value is set automatically to (p+1)^2 but I can't find any publication confirming that particular choice.

Could you send me a reference where I could look at that?

Thank you
Pierre

**Comment by jandrej** [comment]
Most references mention "the SIPG method is stable for sufficiently large \kappa". If you are using NIPG, this changes to "the method is stable for any \kappa > 0". So it depends which type of stabilization you choose and then you are left with the freedom (or burden) of choice.

**Comment by pmguilcher** [comment]
Yes I agree totally with your statements. 
In my case, it is SIPG. Nitsche says in its paper that we can find a sufficiently large value to get a stable method.
However, relating \kappa to the order of the method is not given.

**Comment by pazner** [comment]
Hello @pmguilcher, you can look at this paper:

Shahbazi, K. (2005).  An explicit expression for the penalty parameter of the interior penalty method, Journal of Computational Physics, 205(2), 401--407. http://dx.doi.org/10.1016/j.jcp.2004.11.017

I can provide you with more references if you are interested.

**Comment by pmguilcher** [comment]
Hello @pazner,

Thank you very much, I think that it totally corresponds to the value used in mfem lib.

Best regards

**Comment by tuckerbabcock** [comment]
Hi @pazner,

I'd like to use Shahbazi's algorithm for computing the penalty parameter for a SIPG discretization. Did your comment indicate that it's already implemented somewhere? If not, I can implement it, but I'm unsure how to compute some of the terms in the numerator of Eq. (7) from his paper. Specifically, I mean the face area that does not intersect the boundary, and the face area that does intersect the boundary. Is there an easy way to get the information needed from the `ElementTransformation` (or `FaceElementTransformation`)?

**Comment by pazner** [comment]
I suppose what you need to do is loop over each face of the element, and determine whether the face is in the interior or on the boundary (i.e., does it have one neighboring element or two), and then compute the surface area (by summing the Jacobian determinant weighted by the quadrature weights).

I don't anticipate that this penalty term will differ significantly from what MFEM currently implements.

Can I ask what your motivation is for optimizing the penalty parameter?

**Comment by tuckerbabcock** [comment]
@pazner I had been seeming some issues with convergence rates for a particular problem of mine, that were resolved when I went to very large penalty parameter (~10^8). I'm now more suspecting that there is something else wrong that is forcing the use of such a large parameter. I'll come back here if I can't figure it out, thank you!

**Comment by pazner** [comment]
Sounds good. Closing for now… re-open if needed.

Generally speaking, if you just supply MFEM's `DGDiffusionIntegrator` with a moderate O(1) kappa value, it should be stable.

The rates of convergence for IP-DG shouldn't depend on the penalty parameter — if the parameter is large enough so that the method is stable, you should get $h^p$ in the broken $H^1$ norm and $h^{p+1}$ in the $L^2$ norm.
