### ISSUE TITLE
Missing target Threads::Threads when building with CMake 3.21.1

### ISSUE THREAD

**Issue by adayton1** [mfem/mfem#2807]
I get many errors like the following when configuring MFEM 4.3 with CMake 3.21.1:

```
CMake Error at config/cmake/modules/MfemCmakeUtilities.cmake:60 (add_library):
   Target "mfem" links to target "Threads::Threads" but the target was not
   found.  Perhaps a find_package() call is missing for an IMPORTED target, or
   an ALIAS target is missing?
Call Stack (most recent call first):
   CMakeLists.txt:474 (mfem_add_library)
```

Adding a call to `find_package(Threads REQUIRED)` in the top level CMakeLists.txt file fixed it for me.

**Comment by v-dobrev** [comment]
The `Threads` package is not directly needed by MFEM, there must be an optional package you are using that needs that. Can you post the full `cmake` command you are using?
