### ISSUE TITLE
VectorCoefficient to two Coefficient 

### ISSUE THREAD

**Issue by LeilaSalomon** [mfem/mfem#2813]
Hello,

I have a `VectorCoefficient(dim = 2)`, I would like to know how can I split this `VectorCoefficient` into two `Coefficient` : 

<img width="179" alt="Coef" src="https://user-images.githubusercontent.com/40572513/153034332-8a876631-a3e8-4bdf-b58b-343f96909933.PNG">

Best wishes,

Leila

**Comment by Andr00dz** [comment]
You could use [InnerProductCoefficient](https://mfem.github.io/doxygen/html/classmfem_1_1InnerProductCoefficient.html) combined with [0,1] and [1,0] vectors.

**Comment by LeilaSalomon** [comment]
Yes ! It's a good idea ! Thank you !
