### ISSUE TITLE
Derefinement interpolation on non-conforming meshes

### ISSUE THREAD

**Issue by davidherreroperez** [mfem/mfem#2817]
Hello,
I'd like to have some guidance on how to perform derefinement interpolation on non-conforming meshes.
The following example derefines the mesh and the gridfunction u, but the resulting gridfunction provides
the first value of the group of derefined elements. It is possible to construct a transfer operator
performing a mean of such values?

Thanks in advance.

```c++
#include "mfem.hpp"

using namespace mfem;
using namespace std;

int Wx = 0, Wy = 0;
int Ww = 350, Wh = 350;
int offx = Ww+5, offy = Wh+25;
void Visualize(VisItDataCollection& dc, const string &title, const string& caption, int x, int y);

double pi = 3.141592653589793e0;
double sin_cfunc(const Vector& x) { return sin(pi * x[0]) * sin(pi * x[1]); }

void Visualize(VisItDataCollection& dc, const string &title, const string& caption, int x, int y)
{
    int w = Ww, h = Wh;

    char vishost[] = "localhost";
    int  visport   = 19916;

    socketstream sol_sockL2(vishost, visport);
    sol_sockL2.precision(10);
    sol_sockL2 << "solution\n" << *dc.GetMesh() << *dc.GetField("value")
               << "window_geometry " << x << " " << y << " " << w << " " << h
               << "window_title '" << title << "'"
               << "plot_caption '" << caption << "'" << flush;
}

int main(int argc, char *argv[])
{
    Mesh mesh(Mesh::MakeCartesian2D(8, 16, Element::QUADRILATERAL, true, 1.0, 2.0, true));
    mesh.EnsureNCMesh();

    int dim = mesh.Dimension();
    L2_FECollection l2_fec(0,dim,BasisType::GaussLegendre);
    FiniteElementSpace l2_fespace(&mesh, &l2_fec, 1);
    
    mesh.UniformRefinement();
    l2_fespace.Update();
    
    FunctionCoefficient sin_coeff(sin_cfunc);
    GridFunction u(&l2_fespace);
    u.ProjectCoefficient(sin_coeff);
    
    //std::cout << std::endl;
    //u.Print(std::cout);
    
    VisItDataCollection u_dc("u", &mesh);  u_dc.RegisterField("value", &u);

    // Visualization
    Visualize(u_dc, "u_fine", "u on fime mesh", Wx, Wy); Wx += offx;
    
    // Derefinement by error
    Vector deref_elem_error(mesh.GetNE());
    deref_elem_error = 1.0;
    int deref_elem = mesh.GetNE()/2;
    for(int i = 0; i < deref_elem; i++)
     deref_elem_error[i] = 1e-3;
    mesh.DerefineByError(deref_elem_error, 0.5);
    
    l2_fespace.Update();
    u.Update();
    
    // Visualization
    Visualize(u_dc, "u_dref_coarse", "u on derefined coarse mesh", Wx, Wy); Wx += offx;
    
    //std::cout << std::endl;
    //u.Print(std::cout);
}
```

**Comment by tzanio** [comment]
@rw-anderson and @jakubcerveny, can you help David?

**Comment by davidherreroperez** [comment]
This comment is to remove the stale mark. I have to comment that I am not sure that derefinement operations are correct using only one value of derefined elements.

**Comment by rw-anderson** [comment]
You're right, something is wrong here. Investigating.

**Comment by rw-anderson** [comment]
There are multiple issues here to resolve which I am attempting to address in #3007.

I have rewritten some of the derefinement code for L2 spaces in mind, where local, elementwise L2 projection is the natural approach. This will have to be rethought for continuous spaces.

But for now, with the changes committed there so far, I can get a correct L2 projection in simple cases akin to your test case. Here I've projected f(x,y) = x+y onto a single refined element, and then coarsened back to the single element, and the correct averaging/projection occurs:

![coarsen](https://user-images.githubusercontent.com/11507994/168462247-90ee347a-c15d-4607-b911-afab92054496.png)

Here's the result with your test case:
![l2-proj](https://user-images.githubusercontent.com/11507994/168486870-fb9bb709-4e8c-45cf-b28e-0c56759b22eb.png)

Another goal of this PR is to have a comprehensive set of tests for derefinement. The existing tests passed, but weren't quite detailed enough to surface the issues.

**Comment by rw-anderson** [comment]
I think I have this worked out in the PR in serial. My sense of satisfaction was brief, however, when I looked at the parallel case, which looks significantly more intricate (noticing the warning at the top of ParFiniteElementSpace::ParallelDerefinementMatrix) to adapt to the local L2 method.

**Comment by rw-anderson** [comment]
I think this works in parallel now as well. Any additional testing of the branch welcome.

**Comment by tzanio** [comment]
Thanks for resolving this @rw-anderson. Discussion continued in #3007.
