### ISSUE TITLE
parallel partition of BlockOperator (and BlockVector) for problem with constraints 

### ISSUE THREAD

**Issue by brightzhang91** [mfem/mfem#2818]
Hi, I'm working on a constrained finite element problem which requires a global constraint (Lagrange Multiplier) covering multiple elements and multiple processors. So that I suppose the constraints solvers like `EliminationSolver` in issue #1842 may not apply as the constraints need to come in small invertible blocks and not cross processor boundaries.(please correct if I understood incorrectly).
Therefore I produced a block matrix, making the constraints a subblock of the `BlockOperator`, with A as the main `SparseMatrix` from the `ParBilinearform` ,  and B and (Bt) as the constraint matrix  with the same width (height) as the `SparseMatrix` but with just a few rows(columns) e.g. A(m,m) B(3,m) and Bt(m,3). The constraint matrix is the combination of several one-row matrix produced by several `ParLinearForm`.  I is an identity matrix. 
[A  Bt]
[B   I]
I was suggested to specify a single processor #1859 to contain all the rows of the constraint matrix, and the main `SparseMatrix` are distributed as normal in MFEM. However it seems this is not supported by MFEM. The constraint matrix has to be distributed evenly among the processors. Errors were reported for the following actions.
To specify Operator size on each processor:
`Operator((myid_ == 0)? A_->ParFESpace()->TrueVSize()+3: A_->ParFESpace()->TrueVSize());`
It seems the Operator size should be the same for all processors, e.g  ParFESpace()->TrueVSize()+3 for each one.
And define the BlockOperator size on each processor:
   ```
Array<int> block_trueOffsets(3); 
   block_trueOffsets[0] = 0;
   block_trueOffsets[1] = A_->ParFESpace()->TrueVSize();
   block_trueOffsets[2] = (myid_ == 0)? 3  :  0 ; // the 3 rows in the constraint matrix
   block_trueOffsets.PartialSum();
   BlockOperator constrained_Jacobian(block_trueOffsets);
```
Can you take a look at the problem and maybe fix this issue in MFEM?
Thanks !
Bright

**Comment by mlstowell** [comment]
Hi, @brightzhang91, 

The offsets you show seem correct to me. The `Operator` size you show before that, however, does not. Which `Operator` are you referring to here? The `BlockOperator` will set its own size based on the offsets. How are you defining `B` and `Bt`? Are you using one operator for both of these or are they separate?

Best wishes,
Mark

**Comment by brightzhang91** [comment]
The code is as follows:

```
My_Operator::My_Operator( )
: Operator(A_->ParFESpace()->TrueVSize()+3: A_->ParFESpace()->TrueVSize())
{
}
My_Operator::Mult(const Vector &k, Vector &Residual) const 
{
return a BlockVector ; // with subblock A, B, Bt. I
}
Operator My_Operator::GetGradient(const Vector &k, Vector &Residual) const 
{
return a BlockMatrix ; //  with subblock A, B, Bt. I
}
// subblock A, B, Bt. I are defined separately as Operators with its Mult() 
```

**Comment by mlstowell** [comment]
Okay, that makes sense. What are the errors you're seeing?

**Comment by mlstowell** [comment]
Hi, @brightzhang91, 

I put together a draft of a class for using a set of vectors as an operator. See [ParVectorOperator](https://github.com/mfem/mfem/blob/linearform-op-dev/linalg/vector_operator.hpp).

You can also see how to use it in [ex1p_vo](https://github.com/mfem/mfem/blob/linearform-op-dev/examples/ex1p_vo.cpp). I just use this to compute the center of mass for a `ParGridFunction` but this operator should also work in a `BlockOperator`.

Did you implement something like this for your `B` operator?

Best wishes,
Mark

**Comment by brightzhang91** [comment]
> Okay, that makes sense. What are the errors you're seeing?

The error I see for the 
```
My_Operator::My_Operator( )
 : Operator((myid_ == 0)? A_->ParFESpace()->TrueVSize()+3: A_->ParFESpace()->TrueVSize())
  {}
```
is "Conditional jump or move depends on uninitialised value(s)" after initialization of My_Operator.
And 
![image](https://user-images.githubusercontent.com/67397441/159121513-1c8ff8da-b195-4808-8c57-70982d277ed7.png)
when using the `Mult()` and `GetGradient()` of My_Operator in the `NewtonSolver`.

**Comment by brightzhang91** [comment]
> Hi, @brightzhang91,
> 
> I put together a draft of a class for using a set of vectors as an operator. See [ParVectorOperator](https://github.com/mfem/mfem/blob/linearform-op-dev/linalg/vector_operator.hpp).

> Did you implement something like this for your `B` operator?
> 
> Best wishes, Mark

Many thanks Mark for making this.  I did something similar for B and Bt but I think it was in the incorrect way. I'll try to make use of your `ParVectorOperator`  for the B and Bt Operators. Can you add more details how the ParVectorOperator.Mult() is defined and what's the function of `SetVector` ?

> but this operator should also work in a BlockOperator.

As you can see from my errors above, `My_Operator` is based on a BlockOperator,  returning a `BlockVector` in `Mult()` and a `BlockOperator` in `GetGradient()`. The difficulty lies in defining the Operator size on each processor for `My_Operator`, which only accepts :
Operator(A_->ParFESpace()->TrueVSize())
but not
Operator((myid_ == 0)? A_->ParFESpace()->TrueVSize()+3: A_->ParFESpace()->TrueVSize()).

Sorry for the late reply as I didn't have access to my computer cluster in last days. Thanks very much for your support !

Best regards
Bright

**Comment by mlstowell** [comment]
Hi, @brightzhang91,

The error you are showing appears to be from valgrind and not MFEM. It seems that the `mfem::Operator` is accepting the size that you're passing. If the MFEM operator or vectors have incompatible sizes the `Mult` methods should print an error if you built MFEM with `MFEM_DEBUG=YES`. If you're not seeing these error messages from MFEM then perhaps the error is in the custom `Mult` method of your `B` or `Bt` operator.

Regarding the `ParVectorOperator`: the `SetVector` method is used to set each row of the `B` operator.  The assumption is that each row is created separately by assembling a `ParLinearForm` object (or perhaps by some other means) and the vectors are then combined together to form the `B` operator. The `ParVectorOperator::Mult` method computes the inner product of each row of the operator with the input vector `x`. The vectors are distributed across all processors so these inner products are partially computed using the local portions of the rows and the input vector `x` then these partial inner products are summed together using `MPI_Reduce` and the result is only computed on processor 0 and finally stored in the output vector `y`. On processors other than 0 the `y` vector should have zero length and we must be sure not to write anything to it.

Best wishes,
Mark

**Comment by brightzhang91** [comment]
Hi Mark,

Many thanks for your guidance on how to build the `B` and `Bt` Operator with the new class `ParVectorOperator`. I'll try to use it to rebuild my constraint operators.
However,  I deleted my  `B` and `Bt` (to exclude their effects )and used `cout` to print out the execution of `My_Operator`.  It seems the error "Conditional jump or move depends on uninitialised value(s)" appears right after defining the Operator size in the constructor, before calling any custom method  `Mult()`.
Have you defined the Operator size in this way, by assigning a specific int number to it than automatic partition ?
Thanks.
Bright

**Comment by mlstowell** [comment]
Hi, @brightzhang91,

Yes, the `ParVectorOperator` specifies the size of the `mfem::Operator` using a very similar conditional argument. Perhaps your `myid_` variable is not set before this conditional? In my class I passed this integer as an argument to the constructor because the `mfem::Operator` does need to be initialized before any of the member data in the `ParVectorOperator` object is available.

Best wishes,
Mark

**Comment by brightzhang91** [comment]
> Hi, @brightzhang91,
> 
>  Perhaps your `myid_` variable is not set before this conditional? In my class I passed this integer as an argument to the constructor because the `mfem::Operator` does need to be initialized before any of the member data in the `ParVectorOperator` object is available.
> 
> Best wishes, Mark

You are right. My failure with defining the Operator size was due to the undefined `myid_`. Now the problem was resolved following your method. I'll rebuild and test my constraint Operators as in `ParVectorOperator` and then update it here when it works. Thanks very much for the support !
Best regards
Bright
