### ISSUE TITLE
 Calculate precisely a divergence term

### ISSUE THREAD

**Issue by LeilaSalomon** [mfem/mfem#2819]
Hello,

I have a `GridFunction(dim=2)`, named **f**, I would like to calculate precisely `div(f)`.

Here are the two components of  **f** (fx,fy) : 

<img width="632" alt="f" src="https://user-images.githubusercontent.com/40572513/153239198-a5f4cfc0-0833-4d30-a97d-51ec1fddf050.PNG">

I use : 

`DivergenceGridFunctionCoefficient divergence_f(&f)`. When I visualize my solution, I have a problem : 

<img width="314" alt="Divf" src="https://user-images.githubusercontent.com/40572513/153239962-7dca2036-b578-4c30-9a18-79484af99ee8.PNG">

How can I solve properly `div(f)` ?

Best wishes,

Leila

**Comment by tzanio** [comment]
Can you clarify -- what is the problem?

Unless f is C^1, the divergence will generally be discontinuous.
