### ISSUE TITLE
Direct solvers for block operators

### ISSUE THREAD

**Issue by kvoronin** [mfem/mfem#282]
Hello,

what is the best approach to call a direct solver (e.g., SuperLU) for a block operator? As far as I see in ex11p, SuperLU can be called for a HypreParMatrix. Is there any standard routine which can create a single HypreParMatrix from a block operator filled with HypreParMatrices?

Thanks,
Kirill

**Comment by tzanio** [comment]
I'm not aware of such a function, but writing it may actually not be that difficult.

**Comment by stefanozampini** [comment]
If you can pay the price of conversion, you can convert a BlockOperator into PetscParMatrix via `PetscParMatrix::PetscParMatrix(MPI_Comm comm, const Operator *op, Operator::Type tid)` with `tid = PETSC_MATAIJ`, and then create a PetscLinearSolver, selecting a direct solver by command line, if you configured PETSc with MUMPS (i.e. using --download-mumps) or SuperLU (--download-superlu) support. Note that the blocks in the BlockOperator can be either `HypreParMatrix` or `PetscParMatrix`.

**Comment by kvoronin** [comment]
Thanks, @stefanozampini,
it looks like a good way to do that (except for the fact that it requires PETSC in addition to SuperLU).
I think, @tzanio, the function will have to a lot of low-level MPI communication, exchanging blocks of different size, because each block as HypreParMatrix is already distributed among processors, and the global block matrix viewed as a single matrix will be obviously distributed differently (unless we reorder the matrix so that each process stores the same rows in the global matrix as in all the blocks).

**Comment by stefanozampini** [comment]
You definitely want to keep the same row distribution of the global block
operator

Il 22 Set 2017 8:38 PM, "kvoronin" <notifications@github.com> ha scritto:
