### ISSUE TITLE
Inquiry about the ordenation of Mass Matrix for H1 and DG spaces.

### ISSUE THREAD

**Issue by AlejandroMunozManterola** [mfem/mfem#2823]
Good morning to all,

my team has written a simple test to understand mass matrixes and verify that they are (or should be) the same no matter the space they're built on with the following code.

```c++

namespace mfem {

	TEST(DG, checkMassMatrixIsSameForH1andDG)
	{
		const int maxOrder = 5;
		const int dimension = 1;
		Mesh mesh = Mesh::MakeCartesian1D(1);

		for (int order = 1; order < maxOrder; order++) {

			std::cout << "Checking order: " << order << std::endl;

			FiniteElementSpace* fesH1 = new FiniteElementSpace(
				&mesh, new H1_FECollection(order, dimension, BasisType::ClosedUniform));

			FiniteElementSpace* fesDG = new FiniteElementSpace(
				&mesh,new DG_FECollection(order, dimension, BasisType::ClosedUniform));

			BilinearForm massMatrixH1(fesH1);
			massMatrixH1.AddDomainIntegrator(new MassIntegrator);
			massMatrixH1.Assemble();
			massMatrixH1.Finalize();

			BilinearForm massMatrixDG(fesDG);
			massMatrixDG.AddDomainIntegrator(new MassIntegrator);
			massMatrixDG.Assemble();
			massMatrixDG.Finalize();

			ASSERT_EQ(massMatrixH1.NumRows(), massMatrixDG.NumRows());
			ASSERT_EQ(massMatrixH1.NumCols(), massMatrixDG.NumCols());

			for (std::size_t i = 0; i < massMatrixDG.NumRows(); i++) {
				for (std::size_t j = 0; j < massMatrixDG.NumCols(); j++) {
					EXPECT_NEAR(massMatrixDG(i, j), massMatrixH1(i, j), 1e-5);
				}
			}
		}
	}
}
```

For order 1 and order 2, the test works without issue, but when it reaches order 3 or higher, the mass matrix for H1 has the same values as the DG Mass Matrix, but they are disordered or "shifted". We were wondering why this might be and if you could add some clarity behind the shifting.

An output for Order 3 can be seen here:
```

Checking order: 3

(H1 Mass Matrix)

[row +0]
+7.619048e-02 +1.130952e-02 +5.892857e-02 -2.142857e-02

[row +1]
+1.130952e-02 +7.619048e-02 -2.142857e-02 +5.892857e-02

[row +2]
+5.892857e-02 -2.142857e-02 +3.857143e-01 -4.821429e-02

[row +3]
-2.142857e-02 +5.892857e-02 -4.821429e-02 +3.857143e-01

(DG Mass Matrix)

[row +0]
+7.619048e-02 +5.892857e-02 -2.142857e-02 +1.130952e-02

[row +1]
+5.892857e-02 +3.857143e-01 -4.821429e-02 -2.142857e-02

[row +2]
-2.142857e-02 -4.821429e-02 +3.857143e-01 +5.892857e-02

[row +3]
+1.130952e-02 -2.142857e-02 +5.892857e-02 +7.619048e-02
```

Thank you very much for any kind answers,
Alejandro M.

**Comment by pazner** [comment]
Generally speaking, the DOF orderings for different types of spaces will not be the same. For DG spaces, the DOFs are ordered element-by-element, and within each element, they are ordered lexicographically. For H1 spaces, this ordering is not possible, because there are shared DOFs between elements.

In your case, since you have only one element, you can permute the DOFs of that element so that they match in both cases. The easiest way to do that is using the lexicographic ordering given by the function `NodalFiniteElement::GetLexicographicOrdering`.
https://github.com/mfem/mfem/blob/256bb5627fade2380ca51d08b7b908d8fe71feaa/fem/fe/fe_base.hpp#L751-L772

**Comment by AlejandroMunozManterola** [comment]
Thank you very much for your answer, Pazner.

I hope you don't mind if I follow with a related answer.

Is there a way to obtain the position of the nodes (associated to the dof) when using Nodal basis, by asking the FiniteElementSpace or the BilinealForm? I am afraid I cannot find a way to do it.

Again, thank you for any answer you might offer, it is very welcome.
Alejandro M.

**Comment by pazner** [comment]
I think you should be able to use `Mesh::GetNodes`, e.g.
```c++
FiniteElementSpace nodal_fes(&mesh, &fec, mesh.Dimension());
GridFunction nodal_coordinates(&nodal_fes);
mesh.GetNodes(nodal_coordinates);
```

**Comment by AlejandroMunozManterola** [comment]
Thank you very much for your suggestion, Pazner.

Thanks to it, I can finally understand the ordering behind the different spaces, as I thought that the GetNodes() function would get nodes from the mesh, not from the spaces, and as I used the same mesh, I had the misconception they would be the same.
