### ISSUE TITLE
ElementTransformation *  mesh::GetElementTransformation(int i) misleading

### ISSUE THREAD

**Issue by michi002** [mfem/mfem#2824]
Hello,

I am currently writing a Code where I have to evaluate shapefunctions of other elements while using linear form integrators. My function coefficent is dependent on them - I know it is maybe not the most efficient implementation, but it is only for testing purposes.

However I need the ElementTransformation of said other element and I used the routine mesh::GetElementTransformation(int i) to acquire it. Here is where the unexpected part happens:
The routine does not yield a pointer to a position in a Container of Elementtransformations, nor does it construct a new Transformation and returns its pointer. It constructs a new Transformation, saves it as a member variable of the mesh and only returns the member variable. I find the name of the routine very misleading.
I am far from having full insight, why this way of implementation is chosen, but I think it would be nice to change the behavior of that function (maybe introduce a container of all transformations and return a pointer to the position) or at least add a comment to make the routines behavior more obvious.

I am currently very time limited, but if there is anything I can do to help: let me know.

**Comment by v-dobrev** [comment]
You can just use the following version of `GetElementTransformation`: https://github.com/mfem/mfem/blob/256bb5627fade2380ca51d08b7b908d8fe71feaa/mesh/mesh.hpp#L1104-L1106 with an `IsoparametricTransformation` that you construct.

**Comment by v-dobrev** [comment]
Regarding the documentation: yes, I agree that the doxygen comment for `GetElementTransformation(int)` and other similar methods can be be improved to clarify that the returned pointer points to an internal objects which is invalidated by other calls to the same method (with a different index) or by calls to some other methods.

**Comment by michi002** [comment]
> You can just use the following version of `GetElementTransformation`:
> 
> https://github.com/mfem/mfem/blob/256bb5627fade2380ca51d08b7b908d8fe71feaa/mesh/mesh.hpp#L1104-L1106
> with an `IsoparametricTransformation` that you construct.

Thank you. :)
This is exactly the routine I discovered and used then. I just wanted to open an issue so that no one else falls into this pitfall.
