### ISSUE TITLE
Navier Miniapp

### ISSUE THREAD

**Issue by L29430** [mfem/mfem#2827]
Hi !

I would like to understand this miniapp, can I have a reference for this code ? I would like to know the weak formulation of the problem, for example.

Best wishes,

**Comment by jandrej** [comment]
See https://mfem.org/fluids and the references therein.

**Comment by L29430** [comment]
Hello,

If I understand correctly you use a projection methods to solve equations. In this method, I don't uderstand when you solve div(u) = 0 ?

Best wishes,

LS

**Comment by jandrej** [comment]
Like described in the references, the incompressibility condition, `div(u) = 0`, is imposed weakly by replacing terms during the derivation.

**Comment by L29430** [comment]
So you never solve `div(u) = 0` directly?

**Comment by markusrenoldner** [comment]
No, it is implicitely being solved, as the term `div(u) = 0` was being used while deriving the formulation that is implemented. That means, the implemented formulation also satisfies `div(u) = 0`.
