### ISSUE TITLE
Will variable-order space break the symmetry of bilinearform?

### ISSUE THREAD

**Issue by adam-sim-dev** [mfem/mfem#2830]
Hello,

Recently, I have been testing ex3 with variable-order space. I simply increase the FE order of some elements as follows:

   ```
mesh->EnsureNCMesh(true);

   for (int i = 0; i < 100; i++)
   {
      fespace->SetElementOrder(i, 2);
   }

   fespace->Update(false);
```

I found that assembled operator A becomes nonsymmetric, while for order=1, it's symmetric. 

`std::cout << "matrix is symmetric :" << A.As<SparseMatrix>()->IsSymmetric() << std::endl;`

So I am wondering, is the result expected or am I doing something wrong?

I have another question, does the initial (serial) support for variable-order FiniteElementCollection and FiniteElementSpace work for the common H1, L2, ND and RT spaces, or only some of them? Thanks for the clarification.

Are there any examples now of using variable-order space? I only see a test code `test_var_order` in the unit tests.

Best,
Adam

**Comment by tzanio** [comment]
@jakubcerveny and @rw-anderson, can you help Adam?

**Comment by adam-sim-dev** [comment]
Can anybody help me?

**Comment by tzanio** [comment]
Hi @adam-sim-dev,

The variable-order space support in mfem is currently for H1 elements so we don't expect Example 3 to work. Sorry if this was not clear, it is something we'd like to fix in the future.

Tzanio

**Comment by adam-sim-dev** [comment]
Hi @tzanio , thanks for the clarification. Is it on the roadmap for mfem-5.0, or versions later?

**Comment by tzanio** [comment]
We don't have anyone currently working on it, but we can prioritize it if it is really important for you and other users.

My understanding is that adding the H(curl) and H(div) support is probably not that much work.

**Comment by adam-sim-dev** [comment]
It will be very appreciated if someone continues working on it. I want to try the variable-order H(curl) space because high-order elements lead to too many dofs.

**Comment by tzanio** [comment]
The original question was answered (symmetry is not broken), so I will close this issue.

Continued work on hp-FEM is on our todo list.
