### ISSUE TITLE
Internal Essential Boundary Condition

### ISSUE THREAD

**Issue by wcdawn** [mfem/mfem#2845]
I am solving the heat conduction equation in an unstructured mesh with a variety of materials, each with a unique thermal conductivity. The problem has two boundary conditions: a fixed temperature at the periphery and a fixed temperature for a cooling system (heat pipe).

I would like to implement this in MFEM by treating all DOFs associated with a particular attribute as essential (Dirichlet) BCs. For example, I would like to loop through the mesh and for all DOFs in an element with `attribute==4`, I would eliminate the row/column from the bilinear form, set the diagonal to unity, and apply the fixed temperature boundary condition in the linear form.

I was able to make this work in serial (see #2097), but I'm having trouble indexing the DOFs and implementing this in a reasonable manner in parallel. It seems like if I could collect an `ess_tdof_list` I could use `ParBilinearForm::FormLinearSystem()` and `ParBilinearForm::RecoverFEMSolution()`.

How can I go about collecting an `ess_tdof_list` for all DOF associated with a particular attribute number?
Thanks!

**Comment by tzanio** [comment]
Take a look at `GetEssentialTrueDofs` in `ParFiniteElementSpace`:

https://github.com/mfem/mfem/blob/master/fem/pfespace.cpp#L1032-L1060

and `FiniteElementSpace`:

https://github.com/mfem/mfem/blob/master/fem/pfespace.cpp#L1032-L1060

If I understand correctly, you just want a version of these that works with element instead of boundary attributes?

**Comment by wcdawn** [comment]
@tzanio Thanks! This seems to be it. The key piece I was missing was
```cpp
parfespace->GetRestrictionMatrix()->BooleanMult(ess_dofs, true_ess_dofs);
```
