### ISSUE TITLE
Access specific dof attributes from ComputeElementMatrix

### ISSUE THREAD

**Issue by pmguilcher** [mfem/mfem#2847]
Dear all,

I think it is a very simple question, but I'm not sure it is truly possible.
Can I access some attributes or markers associated to degrees of freedom, directly inside the routines and functions associated to the Bilinear/Linear Form computations? I was thinking to ComputeElementMatrix or AssembleRHSElementVect.

My objective is to have 2 bilinear forms for 2 differents regions of the mesh. But the boundary is embedded in some elements, with (inside 1 element) some dofs from one region, and other dofs from the second region. I think that RestrictedCoefficient will not work in that case.

Thank you
Pierre

**Comment by termi-official** [comment]
If your interface is conforming, then you could use the vertex or face connectivity, depending on your use-case. For example some patch can be applied with vertex connectivity with this template:

```cpp
class PatchedBilinearFormIntegrator : public mfem::BilinearFormIntegrator
{
private:
    mfem::BilinearFormIntegrator* bfi;
    mfem::Mesh* mesh = nullptr;
    mfem::FiniteElementSpace* fes = nullptr;
    bool own_bfi;
    mfem::Table* v2e;

public:
    PatchedBilinearFormIntegrator(BilinearFormIntegrator* _bfi, mfem::FiniteElementSpace* _fes,
                                  bool _own_bfi = true)
        : bfi(_bfi)
        , mesh(_fes->GetMesh())
        , fes(_fes)
        , own_bfi(_own_bfi)
    {
        v2e = mesh->GetVertexToElementTable();
    }

    virtual void AssembleElementMatrix(const mfem::FiniteElement& el,
                                       mfem::ElementTransformation& Trans,
                                       mfem::DenseMatrix& elmat) override
    {
        mfem::Array<int> vertices, aels;

        const auto ei = Trans.ElementNo;
        bfi->AssembleElementMatrix(el, Trans, elmat);
        if (identify_subdomain_1(mesh->GetAttribute(ei)))
        {
            // Find adjacent elements and their dofs
            mesh->GetElementVertices(ei, vertices);
            for(auto vi : vertices)
            {
                v2e->GetRow(vi, aels);
                for(auto aei : aels)
                {
                    // If we are at the interface ...
                    if (identify_subdomain_2(mesh->GetAttribute(aei)))
                    {
                        // Do stuff...
                    }
                }
            }
        }
    }

    virtual ~PatchedBilinearFormIntegrator()
    {
        if (own_bfi)
        {
            delete bfi;
        }
        delete v2e;
    }
};

```

where you can access the dof information via the `FiniteElementSpace` (see e.g. `GetVertexDofs`). Regarding the markers, AFAIK they are directly associated with dofs. 'hope I could help a little.
