### ISSUE TITLE
Flux-limiting a thermal diffusion problem

### ISSUE THREAD

**Issue by varchasgopalaswamy** [mfem/mfem#2848]
Hi,

I'm trying to figure out how to modify Ex 16 to incorporate flux-limiting in the thermal transport. Physically, this is used as a simple 'hack' to model thermal transport in plasmas where the mean-free path of the energy-carrying particles is larger than the gradient scale length of the temperature, and the diffusion approximation isn't valid. This modifies the transport equation from 

𝝏𝒕 𝑻 = -𝛁⋅(𝑸(𝑻)) + S
to 
𝝏𝒕 𝑻 = -𝛁⋅(𝑸'(𝑻)) + S
where
𝑸=𝜿(𝑻)𝛁𝐓, 
𝑸'= min(𝑸,𝑸_max) 
and S is modeling some external heat source/sink  

I'm still new to FEM in general and MFEM in particular, so I'm not sure if what I'm thinking of doing is right. I'd appreciate any pointers! 

Ex. 16 shows how to deal with the case where the conductivity is a function of temperature by linearizing the problem, but it's not clear how to flux limit it from there. Based on https://github.com/mfem/mfem/issues/1063, it seems like the right thing to do is follow the way the temperature equation is solved in the Joule miniapp, and have both T in L2 and Q in H-div. I guess this should proceed as follows:

1. Solve for 𝑸=𝜿(𝑻)𝛁𝐓
2.  Create a new `GridFunction Q_prime` that's a limited version of `Q`.
3. Solve 𝝏𝒕 𝑻 = -𝛁⋅(𝑸') + S 

To solve 1, I think this section from the Joule miniapp should be appropriate https://github.com/mfem/mfem/blob/0f4bd5925a7b8e5036f0709bb518c193adf83c2c/miniapps/electromagnetics/joule_solver.cpp#L556-L599 I guess one modification here would be that the BilinearForm `a2` would need to be modified to have 𝜿 vary every time step, yes? 

To solve 2, it's easy for me to find 𝑸_max at every DOF. Is there a straightforward way to then calculate min(𝑸,𝑸_max)? 

To solve 3, I  guess I just need to plug in 𝑸' from 2 into this section from the Joule miniapp https://github.com/mfem/mfem/blob/0f4bd5925a7b8e5036f0709bb518c193adf83c2c/miniapps/electromagnetics/joule_solver.cpp#L612-L639 

Is there anything I'm missing? How would I enable Partial Assembly in this scenario? The Joule Miniapp only seems to have static condensation. I would be using all quads/hexes for the mesh. 

Thanks!

**Comment by varchasgopalaswamy** [comment]
I managed to get at least part of the problem resolved by solving the diffusion problem for temperature defined on L2 by following the DG example in PR https://github.com/mfem/mfem/pull/867 (and in the process I think I've gotten a better idea of how MFEM works!) 

However, I'm not sure how I'd get started with limiting the flux. In practice, it would need to be limited proportional to Q_max ~ density * temperature^1.5, where both density and temperature are defined on an L2 space. Any tips on how I might get started with that?

**Comment by vladotomov** [comment]
If you have everything available per DOF in the same space, why don't you just enforce it per DOF?
Since it's a vector I guess you want to preserve the directions at the quadrature points, so you should probably use the same correction scaling for all DOFs in a given cell.

**Comment by varchasgopalaswamy** [comment]
Vladimir, 

I'm still learning about FEM so if I get something wrong in what follows please correct me! 
In an FVM code with square elements (which is what I have experience with), I guess that's sort of what I'd do. 
Imagine a 2D grid of squares, with temperature/conductivity defined at the cell centers. The  normal flux to the surface between cell `(i,j)` and `(i+1,j)` would be calculated as 
``` Q_perp = 0.5 (k(i,j) + k(i+1,j)) * (T(i+1,j) - T(i,j)) / dx```
and the surface parallel flux as 
``` Q_par = 0.25 (k(i,j) + k(i+1,j)) * (T(i+1,j+1) + T(i+1,j) - T(i+1,j-1) - T(i,j-1)) / (2dy)```
(i.e. interpolating the temperature onto the interface at the j+ and j- cells, and then calculating the gradient across j)
The flux limit would be the maximal limit from either side of the interface, i.e. `Q_max_interface = max(Q_max(i,j), Q_max(i+1,j))`
Now the flux at the interface is a vector, and can be appropriately limited. The process repeated for each interface.  

The reason I'd want to do something like this is to deal with sharp gradients. Imagine a case where T = 1 for x < 1/2 and T = 1e5 for x > 1/2, with the grid chosen so that x = 1/2 is an interface and the conductivity = 1 everywhere. If I represent T with an L2 basis, then the gradient at each DOF should be zero, right? And then no flux limitation would be applied, whereas in reality there's a gigantic flux that would end up being unphysical. If I didn't have the interface at x = 1/2, then I get gradients, but if I have the L2 order > 0, I get unphysical oscillations in the initial condition. 

Further, I guess if I apply the flux limitation to all the DOFs in an element that's, say, order 4, relatively large and is near a large gradient only on one face, that might unfairly limit the DOFs on the other three faces? But maybe that suggests I've under-resolved the problem.

Maybe the right way to think of it is to generalize the approach I'd use in FVM to a higher order FEM context? I guess I could modify `DGDiffusionIntegrator` when its applied to the interior faces?

**Comment by vladotomov** [comment]
The issue you're describing (the constant `T`) should be resolved in step 1, when you solve for the gradient. If your DG jumps are correct, the resulting `Q` gradients won't be constant in the zones around the interface. Note that when Q is in H-div, you don't have to worry about such jump terms.

**Comment by varchasgopalaswamy** [comment]
Hi Vladimir,

Sorry - I think I miscommunicated what I'm doing. I had initially tried the mixed approach I mentioned when I opened this issue, but found that I was getting oscillations in the flux in H-div that gave unphysical solutions for a simple problem. So I switched to solving it using a DG formulation as in https://github.com/mfem/mfem/pull/867, and found that worked well in the simple case of unlimited flux. So I guess there are two issues
1. Why is my original attempt to solve this problem with mixed FE not working? 
2. How do I flux limit the DG formulation?

Perhaps I can open a new issue for #2, and can continue discussing the original issue of mixed FE here?

**Comment by vladotomov** [comment]
Hi Varchas,

Yes, having separate threads for these issues would be better.

About the mixed FE - I have some past experience with the Hdiv formulation and it was working ok for simple problems. I wasn't solving the same thing (I had a nonlinear term in addition to the divergence on the RHS), but I'd encourage you to revisit your code and search bugs in the `Q`-solve.

About the DG - have you tried the DOF-based limiting / what do you see? As I said, for
```Imagine a case where T = 1 for x < 1/2 and T = 1e5 for x > 1/2```
you should still see a nonzero flux, if the `Q`-solve is done properly with DG.
