### ISSUE TITLE
Perfect Conducting boundary condition in  MixedBilinearForm(&Nedelec, &Raviart);

### ISSUE THREAD

**Issue by Asadanees** [mfem/mfem#285]
Dear @tzanio  and @v-dobrev  and meber
              FiniteElementCollection *HDiv_Coll(new RT_FECollection(order, dim));
		FiniteElementCollection *HCurl_Coll(new ND_FECollection(order, dim));
		
	/// choose the Nedele FiniteElementSpace  Curl conforming finite elment space 
		
		FiniteElementSpace *NEDELEC_space(new FiniteElementSpace (mesh, HCurl_Coll));
		
	/// choose the Raviart Thomas FiniteElementSpace div conforning finite element space
		
		FiniteElementSpace *RAVIART_space(new FiniteElementSpace(mesh, HDiv_Coll));
      MB= new MixedBilinearForm(&Nedelec, &Raviart);
	
	MB->AddDomainIntegrator(new VectorFECurlIntegrator);
	
	MB->Assemble();
	
	// essentil tdof is not defied in the mixed bilinear form
	//MB->FormSystemMatix(ess_tdof_list, MBmat);
	
	MB->Finalize();
	
	MB->Assemble();
	
	MBmat=MB->SpMat()

Could you please help to to implement the essential or Perfect Conducting boundary condition in the mixed Bilinear form>
Thanks and best wishes.

**Comment by tzanio** [comment]
Hi @Asadanees, if I understand correctly you have the form `(curl E, B)` and want to eliminate some of the `E` degrees of freedom?

You can use `MixedBilinearForm::EliminateEssentialBCFromTrialDofs` for that, see https://github.com/mfem/mfem/blob/7f725c14d938e3639705825045a4559d5ff165dc/fem/bilinearform.hpp#L424-L430

**Comment by Asadanees** [comment]
Dear Tzanio,
awesome, Thanks for your cooperation. I tried than I report you. is it work ?. Now I am closing the issue.
Have a nice weekend 
Yours Sincerely 
Asad anees
