### ISSUE TITLE
Boundary attribute question re: wedge elements & mfem::Mesh::MakeCartesian3D

### ISSUE THREAD

**Issue by goxberry** [mfem/mfem#2850]
I am not a meshing or FEM expert, but in looking at how boundary element attributes are assigned in 3D Cartesian meshes for wedge elements, the line https://github.com/mfem/mfem/blob/722d8fa57531e748f75ff39cbd59d48f0a211390/mesh/mesh.cpp#L3221 looked sort of strange to me. Should that line read `AddBdrQuadAsTriangles(ind, 6);` instead, or is there something I'm missing?

**Comment by mlstowell** [comment]
Good catch, @goxberry! Looks like a copy-and-paste error to me. I can make a small bug fix PR to resolve this.

**Comment by tzanio** [comment]
Addressed in #2851
