### ISSUE TITLE
Is this a function for calculating matrix condition number in MFEM?

### ISSUE THREAD

**Issue by liuzg-23** [mfem/mfem#2853]
Hi,
I want to know if this is a function for calculating matrix condition number in MFEM. Thanks very much.

**Comment by psocratis** [comment]
@liuzg-23, 

There is no out-of-the-box function to use in mfem but there are some things you can do. What kind of matrix is it? dense or sparse? how big is it? if it's dense and relatively small you can use some of the MFEM interfaces to LAPACK to calculate singular values. If it's Sparse and/or really big you can use power / Inverse power iterations to estimate the largest and smallest singular values. 

Best,

Socratis

**Comment by liuzg-23** [comment]
@psocratis ，

Thanks very much for your advice. The matrix is a sparse matrix. The matrix scale is about 10,000,000*10,000,000.
