### ISSUE TITLE
Save or convert MFEM mesh as Gmsh mesh (PrintMSH)

### ISSUE THREAD

**Issue by benzwick** [mfem/mfem#2858]
I am using MFEM as a mesh generator but now I need to use this mesh in some different software that cannot read MFEM files. Is there a way to convert the MFEM mesh to Gmsh format? If not, how hard would it be to create a `PrintMSH` function (similar to `PrintVTK` and `PrintVTU`) for this and would it be something that could be added to MFEM in the future?

**Comment by benzwick** [comment]
```
# This script converts linear hexahedral mesh from MFEM to Gmsh v2.2 format.

import numpy as np
import mfem.ser as mfem

ifile = "/home/ben/projects/EEG/mesh/brain/case131/warped/mesh.mesh.gz"
ofile = "test.msh"

mesh = mfem.Mesh(ifile)
nnode = mesh.GetNV()
nelem = mesh.GetNE()
points = np.array(mesh.GetVertexArray())

with open(ofile, 'w') as f:
    # Header
    f.write("$MeshFormat\n")
    f.write("2.2 0 8\n")
    f.write("$EndMeshFormat\n")

    # Nodes
    f.write("$Nodes\n")
    f.write(f"{nnode}\n")
    for i in range(nnode):
        f.write(f"{i+1} {points[i,0]}  {points[i,1]} {points[i,2]}\n")
    f.write("$EndNodes\n")

    # Elements
    f.write("$Elements\n")
    f.write(f"{nelem}\n")
    for i in range(nelem):
        # increment node ids by 1 because Gmsh index starts from 1 not 0
        vert = [v + 1 for v in mesh.GetElementVertices(i)]
        attr = mesh.GetAttribute(i)
        f.write(f"{i+1} 5 2 {attr} {attr}")
        for v in vert:
            f.write(f" {v}")
        f.write("\n")
    f.write("$EndElements\n")
```

**Comment by sshiraiwa** [comment]
@benzwick Are you interested in adding this to PyMFEM? How about putting it under PyMFEM/mfem/common?

**Comment by benzwick** [comment]
@sshiraiwa I would rather add a function to MFEM that saves the mesh in Gmsh format (similar to PrintVTK, PrintVTU, PrintXG) because I need to do this in a C++ code. We could then add Python bindings in PyMFEM.

**Comment by sshiraiwa** [comment]
Yes. That is even better!

**Comment by tzanio** [comment]
We will welcome such contribution @benzwick
