### ISSUE TITLE
Gradient of an L2 space 

### ISSUE THREAD

**Issue by cdelv** [mfem/mfem#2867]
I have a solution of an L2 space. I know that because the space is discontinuous I can't use the gradient interpolator of MFEM. I thought about interpolating first to an H1 space and then applying the gradient but on this page https://mfem.org/lininterp/, it says that doing so requires a linear solve.  I tried to do the interpolation with `IdentityInterpolator `and with `ScalarProductInterpolator` functions but failed to understand the documentation. 

What would be the best way to obtain the gradient of an L2 space? What would the code look like?

**Comment by vladotomov** [comment]
The simplest way to get something is to use `GridFunction::GetDerivative` - it constructs a new `GridFunction` for each component by computing the `x/y/z` derivatives in each element.

**Comment by cdelv** [comment]
@vladotomov  I see. I was worried that `GridFunction::GetDerivative` wouldn't work because L2 is a discontinuous field. Also on the page, I linked it appear as if L2 spaces dint have derivative operations.

**Comment by vladotomov** [comment]
L2 spaces have derivative operations, on element level.

Interpolating `L2` field to `H1` is not well-defined. But inside each element the L2 functions are smooth polynomials, and derivatives can be computed. That's what the `GridFunction::GetDerivative` does.
