### ISSUE TITLE
Potential bug in ND_DofTransformation classes

### ISSUE THREAD

**Issue by sebastiangrimberg** [mfem/mfem#2878]
I noticed after pulling the most up to date MFEM that my code now fails with the following error:

```
Verification failed: (Fo.Size() >= 1) is false:
 --> Face orientations are unset in ND_TriDofTransformation
 ... in function: virtual void mfem::ND_TriDofTransformation::TransformDual(double*) const
```

I believe this was introduced by #1051, and occurs when trying to define ND spaces on triangles of order `p = 1`. In this case there are no face degrees of freedom and `Fo.Size()` is zero, which I think should still be OK because it isn't used in this case. When I use an order `p > 1` for the ND space, everything works fine as previously using the `master` branch from ~mid-Februrary. @mlstowell can you confirm if I am on the right track here? If so, I'm not sure what the best way to fix this would be but perhaps changing the condition to `(!nfdofs || Fo.Size() >= 1)` would work if this is indeed the expected behavior.

**Comment by sebastiangrimberg** [comment]
Indeed, to reproduce this behavior, I modified this line in ex3p

https://github.com/mfem/mfem/blob/1378774bef32fc947ceb257d9c21a1d8f1fefd6e/examples/ex3p.cpp#L204

to read

```
a->AddDomainIntegrator(new VectorFEMassIntegrator(*sigma));
a->AddBoundaryIntegrator(new VectorFEMassIntegrator(*sigma));
```

Then the matrix assembly will fail when using `data/beam-tet.mesh` with the same error when using `-o 1`, but the error does not appear for `-o 2` or higher.

**Comment by sshiraiwa** [comment]
@sebastiangrimberg, I am running into the same issue since yesterday, and I agree your observation. The fix you suggested works for me.

**Comment by mlstowell** [comment]
@sebastiangrimberg and @sshiraiwa, thanks for bringing this to our attention.

I found similar potential issues in each of the DofTransformation classes. The fix I chose was to immediately return from the relevant methods if the number of face DoFs is too low.

Thanks again!

**Comment by tzanio** [comment]
Resolved in https://github.com/mfem/mfem/pull/2880
