### ISSUE TITLE
Clarification on DGTraceIntegrator (and/or the Discontinuous Galerkin scheme) in MFEM

### ISSUE THREAD

**Issue by AlejandroMunozManterola** [mfem/mfem#2882]
Good day to all Mfem members and users.

We've been working on steadily understanding MFEM, mainly the Discontinuous Galerkin scheme.

When it comes to Discontinuous Galerkin, DGTraceIntegrator is a crucial part when it comes to the Flux term.

I'd like to request a clarification or pointing us to understand how to arrive at the α⟨ρu(u⃗ ⋅n^){v},[w]⟩+β⟨ρu|u⃗ ⋅n^|[v],[w]⟩ term. The norm term in the beta side is something we don't understand how to reach it, if you've based this development on some documentation, could we know which papers or books you've used?

When it comes to the discretization of the equation, do you only perform one step of the integration by parts (what Hesthaven refers to as "Weak Form"), or do you perform it twice to arrive at what Hesthaven refers to as "Strong Form"?

Any pointer would be truly helpful.

Thank you very much for any help.

Have a pleasant day.

**Comment by AlejandroMunozManterola** [comment]
Good day @pazner,

This is very informative, I appreciate it as it will help us understand the process more.

Have a pleasant day.

**Comment by AlejandroMunozManterola** [comment]
My apologies for re-opening the issue but a question dawned on me and I thought it'd be wiser to use this thread as it's related.

In your answer, you mention I can achieve both strong and weak forms by using the combinations `ConservativeConvectionIntegrator` and `ConservativeDGTraceIntegrator` or `ConvectionIntegrator` and `NonconservativeDGTraceIntegrator`.

But what if I am not solving a convection problem so that my equations are not `alpha (q . grad u, v)`?

I am actually solving Maxwell equations through discretising the curl operator, for now in 1D. Even if I have two unknowns, I can group them into the form:

<img src="https://render.githubusercontent.com/render/math?math=\materialMatrix \frac{\partial \unknownFieldsVec}{\partial t} + \frac{\partial \fluxFunctionVec}{\partial t} = 0 ">

with Q being a matrix holding the epsilon and mu coefficients, **u** being a vector holding the E and H components and **f** being the components vector too, but starting with the H and then the E components.

Summarising, I am not solving `alpha (q . grad u, v)`, do you have an operator that I could use while staying in DG?

Thank you very much for your answer.

**Comment by AlejandroMunozManterola** [comment]
[](https://render.githubusercontent.com/render/math?math=\materialMatrix%20\frac{\partial%20\unknownFieldsVec}{\partial%20t}%20+%20\frac{\partial%20\fluxFunctionVec}{\partial%20t}%20=%200)My apologies for re-opening the issue but a question dawned on me and I thought it'd be wiser to use this thread as it's related.

In your answer, you mention I can achieve both strong and weak forms by using the combinations ConservativeConvectionIntegrator and ConservativeDGTraceIntegrator or ConvectionIntegrator and NonconservativeDGTraceIntegrator.

But what if I am not solving a convection problem so that my equations are not alpha (q . grad u, v)?

I am actually solving Maxwell equations through discretising the curl operator, for now in 1D. Even if I have two unknowns, I can group them into the form:

with Q being a matrix holding the epsilon and mu coefficients, u being a vector holding the E and H components and f being the components vector too, but starting with the H and then the E components.

Summarising, I am not solving alpha (q . grad u, v), do you have an operator that I could use while staying in DG?

Thank you very much for your answer.

**Comment by pazner** [comment]
The documentation you linked to is unfortunately somewhat unclear — you can use `ConvectionIntegrator` with L2 spaces, but it will apply the operator element-wise. In a DG formulation, you would also need a numerical flux function that will couple the elements through surface integrals. The choice of numerical flux is typically problem-specific. An example is shown for the Euler equations in ex18. I don't know offhand what the correct flux is for your particular problem. Implementing it in MFEM may require writing a custom face integrator.

**Comment by AlejandroMunozManterola** [comment]
Greetings,

we've been analysing the problem and we consider we might indeed need to expand DGTraceIntegrator.

As it is right now, its form is α⟨ρ(u⃗ ⋅n){v},[w]⟩+β⟨ρ|u⃗ ⋅n|[v],[w]⟩,

But our flux would require a term similar to the following expression

α⟨ρ(u⃗ ⋅n){v},[w]⟩ + β ⟨ρ|u⃗ ⋅n|[v],[w]⟩ + γ ⟨ρ(u⃗ ⋅n)[v],[w]⟩

So that the gamma term contains the jump operator for the trial function (similar to beta) but does not contain the absolute term.

We'd need to expand the DGTraceIntegrator class (and its functions) by adding the relevant term. Any pointers you could give us? Is it a possible modification?

**Comment by jandrej** [comment]
You can always add two `DGTraceIntegrator`? One with `α != 0` and `β != 0` and the other one with  `α == 0` and `γ != 0`. Is that not feasible?

**Comment by jandrej** [comment]
You can always add a `DGTraceIntegrator` with either alpha or beta set to zero.
