### ISSUE TITLE
Some vector finite element PA issues

### ISSUE THREAD

**Issue by pazner** [mfem/mfem#2884]
If I change the test "Hcurl/Hdiv pa_coeff" to use a non-Cartesian mesh it fails:
```diff
--- a/tests/unit/fem/test_pa_coeff.cpp
+++ b/tests/unit/fem/test_pa_coeff.cpp
@@ -296,8 +296,7 @@ TEST_CASE("Hcurl/Hdiv pa_coeff",
       const int ne = 3;
       if (dimension == 2)
       {
-         mesh = Mesh::MakeCartesian2D(
-                   ne, ne, Element::QUADRILATERAL, 1, 1.0, 1.0);
+         mesh = Mesh::LoadFromFile("../../data/star.mesh");
       }
       else
       {
```
```
Testing 2D ND x RT partial assembly with coeffType 3 and integrator 0
  order: 1, pa error norm: nan
FAILED: pa_error < 1.e-10 for: nan < 1e-10
Failed 1 test case, failed 1 assertion.
```

Also, this line looks somewhat suspicious: https://github.com/mfem/mfem/blob/def8aee025bf65f55c9edc305ec7aebfa9ca743b/fem/bilininteg_vectorfe.cpp#L343

**Comment by tzanio** [comment]
`/ (J11*J22) - (J21*J12)` definitely looks like a bug... @dylan-copeland can you take a look and fix in the `mfem-4.4-dev` branch?

**Comment by dylan-copeland** [comment]
Thanks @pazner. I will fix this, and change the unit tests to use non-Cartesian meshes. This bug was introduced in 2020 in this commit: https://github.com/mfem/mfem/commit/e00be4f28ea2d22ec866677a11ff2cf27ef914dc

**Comment by dylan-copeland** [comment]
This issue (which is actually the tip of the iceberg) is fixed in https://github.com/mfem/mfem/pull/2898.

**Comment by tzanio** [comment]
Addressed in https://github.com/mfem/mfem/pull/2898
