### ISSUE TITLE
Project Coefficient onto a component of a vectorial GridFunction on the boundary

### ISSUE THREAD

**Issue by cbritopacheco** [mfem/mfem#2889]
# Environment

|             |                           |
|--------| ---------------|
|    OS     | macOS Big Monterey |
| Compiler | AppleClang 13.0.0.13000029 |
| mfem   |  c6425db3da406d1053606a627774fcf2479be658 |
| Build | Debug |

Error is not reproduced in the Release build.

# Problem

I seek to project an `mfem::Coefficient` onto one of the components of a vectorial `mfem::GridFunction` (ie. vdim > 1) on the boundary.

However I am met with the following error:

```c++
Assertion failed: (bool(values_counter[i]) == bool(ess_vdofs_marker[i])) is false:
 --> internal error
 ... in function: virtual void mfem::GridFunction::ProjectBdrCoefficient(mfem::Coefficient **, Array<int> &)
 ... in file: /Users/carlos/Projects/rodin/third-party/mfem/fem/gridfunc.cpp:2639

Abort trap: 6
```

The following reduced test case may be used to reproduce the problem:

[test.mesh.txt](https://github.com/mfem/mfem/files/8246901/test.mesh.txt)

```c++
#include <mfem.hpp>

int main()
{
  const char* mesh_file = "test.mesh";

  // Build finite element space (sdim = 2, vdim = 2)
  int d = 2;
  int order = 1;
  mfem::Mesh mesh(mesh_file);
  mfem::H1_FECollection fec(order, d);
  mfem::FiniteElementSpace fespace(&mesh, &fec, d);

  // A coefficient will be projected to one of the vectorial grid function's component
  std::vector<mfem::Coefficient*> coeffs(d, nullptr);
  mfem::ConstantCoefficient value;
  coeffs[0] = &value;

  // I want to project it on one attribute (attr = 2)
  mfem::Array<int> marker(mesh.bdr_attributes.Max());
  marker = 0;
  marker[1] = 1;

  // Attempt the projection
  mfem::GridFunction u(&fespace);
  u = 0;
  u.ProjectBdrCoefficient(coeffs.data(), marker);

  return 0;
}

```

# Source of the problem

The error occurs in `gridfunc.cpp` inside `mfem::GridFunction::ProjectBdrCoefficient`:

```c++
frame #4: 0x00000001004639d0 bdrbug`mfem::GridFunction::ProjectBdrCoefficient(this=0x000000016fdfda08, coeff=0x0000600000010290, attr=0x000000016fdfda78) at gridfunc.cpp:2638:7
   2635	   fes->GetEssentialVDofs(attr, ess_vdofs_marker);
   2636	   for (int i = 0; i < values_counter.Size(); i++)
   2637	   {
-> 2638	      MFEM_ASSERT(bool(values_counter[i]) == bool(ess_vdofs_marker[i]),
   2639	                  "internal error");
   2640	   }
   2641	#endif
(lldb) p values_counter[i]
(int) $0 = 0
(lldb) p ess_vdofs_marker[i]
(int) $1 = -1
```

In this case the error arises due to the failed comparison between `bool(values_counter[i]) = bool(0) = 0` and `bool(ess_vdofs_marker[i]) =  bool(-1) = 1`.

# Notes

I am unsure if this is a bug or if I am misusing the library. Also, the comparison leads me to believe that the check should succeed since both -1 and 0 are typically used to mean "false" values. Anyways, commenting the code leads me to a somewhat expected result in my use case.

**Comment by psocratis** [comment]
Hi @cbritopacheco, 

Thanks for reporting this. Can you try #2944 ? 

Best,

Socratis

**Comment by psocratis** [comment]
I am closing this now. See #2944
