### ISSUE TITLE
Issue with MixedVectorIntegrator after recent merge of #1989

### ISSUE THREAD

**Issue by sebastiangrimberg** [mfem/mfem#2890]
I am assembling a MixedBilinearForm which has only boundary integrators on a 3D mesh. After merging #1989, this no longer works and I get the following incompatible dimensions error and backtrace:

```
Assertion failed: (a.Height() == b.Height() && a.Width() == c.Width() && b.Width() == c.Height()) is false:
 --> incompatible dimensions
 ... in function: void mfem::Mult(const mfem::DenseMatrix&, const mfem::DenseMatrix&, mfem::DenseMatrix&)
 ... in file: /Users/sjg/Documents/Repositories/qht-cem/build/extern/mfem/src/mfem/linalg/densemat.cpp:1984

Backtrace:
0) [0x10dc84a1e]: mfem::mfem_error(char const*)
1) [0x10dcc4993]: mfem::Mult(mfem::DenseMatrix const&, mfem::DenseMatrix const&, mfem::DenseMatrix&)
2) [0x10e082c83]: mfem::FiniteElement::CalcPhysDShape(mfem::ElementTransformation&, mfem::DenseMatrix&) const
3) [0x10dbbf48f]: mfem::MixedVectorWeakDivergenceIntegrator::CalcTestShape(mfem::FiniteElement const&, mfem::ElementTransformation&, mfem::DenseMatrix&)
4) [0x10ded92a2]: mfem::MixedVectorIntegrator::AssembleElementMatrix2(mfem::FiniteElement const&, mfem::FiniteElement const&, mfem::ElementTransformation&, mfem::DenseMatrix&)
5) [0x10debb0fa]: mfem::MixedBilinearForm::Assemble(int)
```

It seems the issue is inside `CalcPhysDShape`, the inverse Jacobian is 2 x 3 but the `dshape` matrix (`trial_shape` in `MixedVectorIntegrator::AssembleElementMatrix2`) is now only allocated with 2 columns (`trial_vdim = 2`), whereas it used to always have `spaceDim` columns. The `test_shape` matrix is still constructed with `test_vdim = 3`. I'm not using any of the new ND or RT collections, in this case the test space is a 3D ND space and the trial space is a 3D H1 space.

**Comment by sebastiangrimberg** [comment]
Just as a follow-up or potential solution, it looks like elsewhere like in `VectorFEMassIntegrator::AssembleElementMatrix2`, `trial_vdim` and `test_vdim` are computed as:

```
int trial_vdim = std::max(spaceDim, trial_fe.GetVDim());
int test_vdim = std::max(spaceDim, test_fe.GetVDim());
```

Maybe this is all that is required in this case too. Also tagging @mlstowell, thank you Mark!

**Comment by tzanio** [comment]
Thanks for the quick bug report, @sebastiangrimberg!

**Comment by mlstowell** [comment]
Hi, @sebastiangrimberg,

Being a generalized bilinear form integrator I don't think we can use `set::max` in the same way here. The gradient of a scalar basis function will always be the space dimension so we should simply use that. We can make this change in `MixedVectorWeakDivergenceIntegrator::GetTestVDim`.

I'm concerned that similar changes may be necessary in other integrators which are based on the three generalized bilinear form integrators. I'll take a closer look this afternoon and create a PR to, hopefully, catch any similar bugs.

Best wishes,
Mark

**Comment by tzanio** [comment]
thanks @mlstowell !

**Comment by mlstowell** [comment]
@sebastiangrimberg, if you get a chance, could you verify that PR #2895 resolves this issue in your code?

**Comment by sebastiangrimberg** [comment]
Thanks @mlstowell, I can confirm that this fixes the issue!

Closing this now, discussion continued in #2895.
