### ISSUE TITLE
Modify entities in `SparseMatrix`

### ISSUE THREAD

**Issue by geyan3566** [mfem/mfem#2894]
Hi,

I created a FIniteElementSpace which containing a prolongation matrix (`SparseMatrix *cP`)

Is there a way to modify the sparse matrix after calling `Finalize()` ?

Thanks,
G

**Comment by geyan3566** [comment]
Problem fixed.

**Comment by v-dobrev** [comment]
For future reference: most (if not all) SparseMatrix methods should work after Finalize() as long as they do not try to extend the existing sparsity pattern.
