### ISSUE TITLE
Assembly of non-diagonal blocks in HypreParMatrix

### ISSUE THREAD

**Issue by J-Pi** [mfem/mfem#2900]
Hello everybody!

I am trying to implement an unfitted finite element method using level sets for extrapolation of solution values (an alternative method to the shifted boundary method). I have an working serial version and an working version with pure explicit treatment in parallel. Now I want to implement the implicit version (which is working in serial) in parallel. Therefore I have to assemble non-diagonal blocks (a block of which the rows belong to elements in rank A and the columns belong to elements in rank B), since the sparsity pattern has changed due to the extrapolation. Since I do not know a-priori from which points I have to extrapolate and the points also change within time, it is not possible to choose a mesh partition to avoid the assembly of these non-diagonal blocks.

Is there any way in MFEM to assemble those blocks or do I need to use functions of hypre?

Thanks in advance for any help! If you have any questions about what I am doing, please fell free to ask.

Best,

Jan-Phillip

**Comment by vladotomov** [comment]
Probably it can be done, as long as your extrapolation only comes from nearest face neighbors.
See `ParBilinearForm::AssembleSharedFaces()` which assembles the local `SparseMatrix` by considering MPI neighbors.
See `ParBilinearForm::ParallelAssemble()` to see how local `SparseMatrix` are used to form the `HypreParMatrix`.

**Comment by J-Pi** [comment]
First of all, thank you Vladimir, for your answere.
The problem is, that the extrpolation does not only come from direct neighbours, but I do know the local (and global) element number of the element I have to extrapolate from, and the rank of this element. As far as I have understood the assembly of shared faces, this might also work in my case in a similiar way. 
Currently my assembly for the HypreParMatrix is the following, where Mat is the HypreParMatrix and mat is the local SparseMatrix
```
OperatorHandle MatH(Operator::Hypre_ParCSR);
MatH.Clear();
OperatorHandle dMatH(MatH.Type()), Ph(MatH.Type());
dMatH.MakeSquareBlockDiag(MPI_COMM_WORLD, FESpace.GlobalVSize(), FESpace.GetDofOffsets(), mat);
Ph.ConvertFrom(FESpace.Dof_TrueDof_Matrix());
MatH.MakePtAP(dMatH, Ph);
MatH.SetOperatorOwner(false);
Mat = new HypreParMatrix(*(MatH.As<HypreParMatrix>()));
```
Since for the Operator Handle there is no function for an other parallel type then Block-Diagonal, I assume this way won't work anymore. Instead I think I have to use the else-alternative in `ParBilinearForm::ParallelAssemble(OperatorHandle &A, SparseMatrix *A_local)`. For this, I think I have to assemble A_local in the form `(Diag|OffDiag)`, where in the `Off-Diag`-Part, the column-index should be something like global DoF plus number of local DoFs. Then I have to adjust the `globJ` Array and it should work...
I will try this out as soon as I can and keep you updated.

My other idee then would be to assemble the HypreParMatrix directly from global SparseMatrices, but the only available opportunity would then be to first get the matrix as an SparseMatrix on processor 0 (that is a lot of communication...).

Thanks again for your help.

Best,

Jan-Phillip

**Comment by J-Pi** [comment]
And finally, here is the update.
Assembly of the local Matrix in the form `(Diag|OffDia)` in the form I suggested above works fine with an adjustment of the `glob_J` Array of the ParallelAssemble function.
Thanks again for your help.

Best,

Jan-Phillip
