### ISSUE TITLE
vtu mesh file nodal number reordered

### ISSUE THREAD

**Issue by ChaoW95** [mfem/mfem#2901]
Hello everybody!

I am trying to read the mesh in the `vtu` format and do some FEA with it.
The FEA process goes smoothly. However, I found that the nodal number of the mesh is reordered.
I was wondering if there is a way to prevent the reordering and just use the given node number instead.

Thank you!

**Comment by ChaoW95** [comment]
Here is how I read the mesh:
`Mesh *mesh = new Mesh(mesh_file1, 0, 0, false);`
I have already turned off the `refine` and `fix_orientation`.

**Comment by pazner** [comment]
Hello @ChaoW95,

Is your mesh high-order or straight-sided? Typically MFEM does not reorder the vertices of a straight-sided mesh. It might be useful, if possible, to attach your mesh file here.

**Comment by ChaoW95** [comment]
Hi @pazner,

I modified the ex2.cpp in the mfem. I used two methods to save the results.
One is the given method:
```
      ofstream mesh_ofs("displaced");    
      mesh_ofs.precision(8);    
      mesh->Print(mesh_ofs);    
```
Another one is the ParaViewDataCollection:
```   ParaViewDataCollection paraview_dc("displaced_test", mesh); 
    paraview_dc.SetLevelsOfDetail(0);
    paraview_dc.SetDataFormat(VTKFormat::BINARY);
    paraview_dc.SetHighOrderOutput(false);
    paraview_dc.Save();
```

Those two methods give different mesh numbering.
[ex2.zip](https://github.com/mfem/mfem/files/8338770/ex2.zip)

**Comment by ChaoW95** [comment]
Then I try to use the Paraview to check the results. It turns out the result saved by the `ParaViewDataCollection` has 48 points some of them are duplicate.
![image](https://user-images.githubusercontent.com/38391416/159852375-5460aab9-42e7-44f3-9dea-14ee7300ab1c.png)

**Comment by pazner** [comment]
The ParaView output is just intended for visualization, not for further analysis. There will be duplicated points because of how MFEM handles the visualization, see https://github.com/mfem/mfem/issues/2906#issuecomment-1074157376

**Comment by benzwick** [comment]
See also #1757
