### ISSUE TITLE
Divergence calculation

### ISSUE THREAD

**Issue by LeilaSalomon** [mfem/mfem#2902]
Hello !

I solve this equation : 

![image](https://user-images.githubusercontent.com/40572513/159027161-003729e2-bb92-4d50-88f8-024c45f53239.png)

For that, I use example 1.

A is a continuous function, represented here:

![A](https://user-images.githubusercontent.com/40572513/159020519-946527ca-8960-4388-a5d3-baea0917cefa.png)

After calculating the solution `u`, I would like to recover the term `AGrad(u)`, I use : ScalarVectorProductCoefficient AGradU(GradU_coef,A_coef).

1 - I project AGradU on a Nedelec grid, the results are below :  

![image](https://user-images.githubusercontent.com/40572513/159023928-3cda81d9-9ec3-4e24-a8cd-b4839587b0d9.png)

`du/dy` is not correctly calculated, numerical oscillations are observed. Moreover, Div.(AGrad(u)) is no longer equal to 0 !

2 - I solve the term `AGrad(u)` using the finite elements formalism, in a Nedelec space, the results are below :  

![image](https://user-images.githubusercontent.com/40572513/159026002-da3beac8-a386-4deb-9f3e-e73768bbf684.png)

`du/dx` and `du/dy` are well calculated, but Div.(AGrad(u)) is not equal to 0 ! I don't understand why. Do you know how can I retrieve the term `AGrad(u)` such that its divergence is always zero like the equation (1)?

**Comment by mlstowell** [comment]
Hi, @LeilaSalomon,

These are interesting images. Problems like this are often more difficult than they appear.

I would suggest using a `DiscreteLinearOperator` with a `GradientInterpolator` to compute `Grad(u)` in Nedelec space. This should be an exact gradient of the H1 solution `u`. Of course, `u` is not an exact solution of then original PDE so the resulting gradient won't be perfect either but it is the best that can be done. If further improvement is needed in `u` and `Grad(u)` we can refine the mesh or use higher order polynomials in the basis functions.

The next step is to compute the flux `A Grad(u)` from `Grad(u)`.It sounds like you have tried at least two different methods for this but my first choice would have been a third option. Compute `A Grad(u)` in a Raviart-Thomas space using a second linear solve. You already have `Grad(u)` in a Nedelec space, next compute a rectangular matrix, mapping Nedelec to Raviart-Thomas, which I will call `m12(A)` using a `MixedBilinearForm` and a `VectorFEMassIntegrator` build with the coefficient `A`. Also, compute a square matrix, in the Raviart-Thomas space, using `BilinearForm` and the `VectorFEMassIntegrator` with no coefficient (it defaults to 1) we can call this `m2`.

Once you have these pieces solve for `flux=A Grad(u)`:
```
flux = m2^{-1} m12(A)du
```
where `du` is the Nedelec `GridFunction` approximating `Grad(u)`. If you have any knowledge of normal component of the flux along the boundary you can apply that as a Dirichlet BC when preforming this solve. Any such knowledge would improve the fit. Keep in mind that any boundaries of the original problem where you did not impose Dirichlet BCs would lead to boundary conditions on this flux. Specifidally the natural boundary conditions of the original problem correspond to `n.flux=0`.

Best wishes,
Mark

**Comment by LeilaSalomon** [comment]
I forgot to specify that `A` is a continuous function represented on a GridFunction.
