### ISSUE TITLE
Install mumps using the lapack and scalapack of intel mkl.

### ISSUE THREAD

**Issue by liuzg-23** [mfem/mfem#2905]
Hello,
Because I install mumps using the lapack and scalapack libraries of intel mkl. I set the configure of lapack and scalapack in defaults.mk using the following commands:
LAPACK = $(if $(NOTMAC),-lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core -framework Accelerate)
SCALAP = -L$(MKLROOT) -lmkl_scalapack_lp64 $(LAPACK)
MUMPS_DIR = @MFEM_DIR@/../MUMPS_5.3.5
MUMPS_OPT = -I$(MUMPS_DIR)/include
MUMPS_LIB = $(XLINKER)-rpath,$(MUMPS_DIR)/lib -L$(MUMPS_DIR)/lib -ldmumps\
 -lmumps_common -lpord $(SCALAP) $(LAPACK) $(MPI_FORTRAN_LIB)
 
I can successfully compile and generate the “libmfem.a” file. However, when compiling the example, the error occurs.
ld: ana_AMDMF.F:(.text+0x327c): undefined reference to `for_write_seq_lis_xmit'
 ld: ../../MUMPS_5.3.5/lib/libmumps_common.a(estim_flops.o): in function `mumps_print_still_active_':
estim_flops.F:(.text+0x66d): undefined reference to `for_write_seq_fmt'
ld: ../../MUMPS_5.3.5/lib/libmumps_common.a(sol_common.o): in function `mumps_sol_rhsmapinfo_':
sol_common.F:(.text+0x77b): undefined reference to `for_check_mult_overflow64'
ld: sol_common.F:(.text+0x80c): undefined reference to `for_alloc_allocatable'

......
Can you help me solve this problem?
Thanks very much!
Zhengguang.

**Comment by sshiraiwa** [comment]
There are routines in Fortran library. I am wondering if you are using (or can use) ifort as a linker?
```
$ nm ../compiler/lib/intel64/libifcore.so.5  | grep for_write_seq
00000000000a8aa0 T for_write_seq
00000000000af1c0 T for_write_seq_fmt
00000000000b0f30 T for_write_seq_fmt_xmit
00000000000b3bb0 T for_write_seq_lis
00000000000b5960 T for_write_seq_lis_xmit
00000000000ba8b0 T for_write_seq_nml
00000000000aa2c0 T for_write_seq_xmit
```
Another thing to look is to take the ldd of example program in MUMPS, and see how they are linked. @psocratis, how are you using MUMPS from MFEM build system?

**Comment by liuzg-23** [comment]
@sshiraiwa Thanks for your reply. You are right. The problem is caused by the FORTRAN compiler. I have solved this problem.
