### ISSUE TITLE
Is it possible to assign essential bc in different directions for each boundary?

### ISSUE THREAD

**Issue by adantra** [mfem/mfem#2907]
Consider a linear elasticity problem. How do I assign a different component to each boundary? 
I tried the following:
ess_bdr_west_list = [0] * (n_bdr_attr)
ess_bdr_north_list = [0] * (n_bdr_attr)
ess_bdr_bottom_list = [0] * (n_bdr_attr)
ess_bdr_west_list[nwest] = 1
ess_bdr_north_list[nnorth] = 1
ess_bdr_bottom_list[nbottom] = 1
ess_bdr_west = mfem.intArray(ess_bdr_west_list)
ess_bdr_north = mfem.intArray(ess_bdr_north_list)
ess_bdr_bottom = mfem.intArray(ess_bdr_bottom_list)
fespace.GetEssentialTrueDofs(ess_bdr_west, ess_tdof_list,0)
fespace.GetEssentialTrueDofs(ess_bdr_north, ess_tdof_list,1)
fespace.GetEssentialTrueDofs(ess_bdr_bottom, ess_tdof_list,2)

But only the last one is taken. Any suggestions. 

Adolfo

**Comment by rcarson3** [comment]
Hi @adantra, so you currently would want a temporary array which you'd pass into the `fespace.GetEssentialTrueDofs(...)` calls. Then between each call you'd want to add the information from there to your `ess_tdof_list`.

I will mention that I currently have a PR open #2849  which should eventually make this process easier in future versions of MFEM.

**Comment by adantra** [comment]
Thanks, Robert. That's exactly what I need.
