### ISSUE TITLE
Vector version of DGDiffusionIntegrator

### ISSUE THREAD

**Issue by rhebergens** [mfem/mfem#2909]
I'm implementing a DG discretization for (Navier-)Stokes. The code is working well based on using the ElasticityIntegrator on cells and DGElasticityIntegrator on faces. However, I'd like to use the vector Laplacian as the diffusion term instead of the divergence of the symmetric gradient formulation. On the cells I can use VectorDiffusionIntegrator, but there is no VectorDGDiffusionIntegrator on faces. I was thinking of the following two approaches to address this:

1. Modify the DGElasticityIntegrator. The DGElasticityIntegrator on the faces implements mu*(grad(u) + grad(u)^T) + lambda*div(u)*I, but I just need mu*grad(u). I had a look at the implementation of DGElasticityIntegrator and I was thinking I just need to comment out that part of DGElasticityIntegrator where mu*grad(u)^T is added to elmat. If it's indeed just a matter of commenting out a few lines, could someone point me to which lines I would need to comment out?
2. An alternative is to modify the scalar DGDiffusionIntegrator. The way I was thinking of doing this is DGDiffusionIntegrator gives us elmat for a scalar. It's of size ndof1 + ndof 2. Changing the size of elmat to dim*(ndof1+ndof2), the current implementation of DGDiffusionIntegrator fills the first diagonal (ndof1+ndof2) block. I thought I could just copy this block also to the second and maybe third diagonal blocks, but I think the ordering I'm using is incorrect. 

Any help on which approach to use and how to continue is much appreciated.

**Comment by pazner** [comment]
Hello @rhebergens,

Option 2 sounds like a reasonable thing to try. I'm not sure why it wasn't working for you. It should actually be possible to wrap *any* scalar integrator in another integrator that "vectorizes" it, i.e. repeats its element matrix as blocks along the diagonal. Note that for the ordering, the vector dimension should be the "slow" dimension, and the DOF index should be the "fast" dimension.

**Comment by rhebergens** [comment]
Thanks for the response. Regarding option 2, in the DGDiffusionIntegrator at the end once we have elmat, I added 

```
   for (int k = 0; k < dim; k++)
     {
       velmat.AddMatrix(elmat, ndofs*k, ndofs*k);
     }

```
where velmat is size dim*ndofs. I then return velmat instead of the scalar elmat. The code compiles, but I get nan as solution. Please let me know if I misunderstood the ordering.

**Comment by pazner** [comment]
I think the issue you are encountering is that *all* the degrees of freedom for the "second" element come after all the degrees of freedom for the fist element, they are not interleaved. You can try doing something like this:

```c++
for (int d=0; d<dim; ++d)
{
   for (int j=0; j<ndofs; ++j)
   {
      int jj = (j < ndof1) ? j + d*ndof1 : j - ndof1 + d*ndof2 + dim*ndof1;
      for (int i=0; i<ndofs; ++i)
      {
         int ii = (i < ndof1) ? i + d*ndof1 : i - ndof1 + d*ndof2 + dim*ndof1;
         velmat(ii, jj) += elmat(i, j);
      }
   }
}
```

**Comment by rhebergens** [comment]
Perfect, that worked - thank you!

**Comment by bfadness** [comment]
I made a picture to describe the code that fills `velmat` in the [comment](https://github.com/mfem/mfem/issues/2909#issuecomment-1076666625) above. Suppose `dim = 2` and `ndof2 < ndof1`. Then `velmat` looks like

![elemat](https://github.com/mfem/mfem/assets/29881379/ae5d52c6-cba9-46aa-98ab-0dd4954df8d4)

where blue and cyan are different dimensions.

**Comment by bfadness** [comment]
I made a picture to describe the code that fills `velmat` in the [comment](https://github.com/mfem/mfem/issues/2909#issuecomment-1076666625) above. Suppose `dim = 2` and `ndof2 < ndof1`. Then `velmat` looks like

![elemat](https://github.com/mfem/mfem/assets/29881379/cf389ff4-d8d1-4d03-8b85-ddc296be60dd)


where blue and cyan are different dimensions.
