### ISSUE TITLE
Install location for .dll in mingw (msys2)

### ISSUE THREAD

**Issue by 3rav** [mfem/mfem#2913]
How can i force install .dll in "bin" folder, it is currently installed in "lib" folder (and simultaneous installation of dll.a in "lib" folder)?

**Comment by wo80** [comment]
I can confirm the behavior.

@3rav From command line, you could set `CMAKE_RUNTIME_OUTPUT_DIRECTORY`:
```console
Christian@CHRISTIAN-PC MINGW64 /d/projects/mfem/build
$ cmake .. -G "MinGW Makefiles" -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX="/c/msys2/mingw64" -DCMAKE_RUNTIME_OUTPUT_DIRECTORY="/c/msys2/mingw64/bin"
$ cmake --build . -- -j 4
[  0%] Building CXX object CMakeFiles/mfem.dir/general/array.cpp.obj
[ ...  ]
[100%] Linking CXX shared library C:\msys2\mingw64\bin\libmfem.dll
[100%] Built target mfem
$ mingw32-make install
Consolidate compiler generated dependencies of target mfem
[100%] Built target mfem
Install the project...
-- Install configuration: "Release"
-- Installing: C:/msys2/mingw64/lib/libmfem.dll
-- Installing: C:/msys2/mingw64/lib/libmfem.dll.a
...
```
This will copy the dll to the specified location with the build command. The install command will still copy both the `.dll` and the `.dll.a` to the lib folder.

@tzanio To enable the correct behavior in `CMakeLists.txt`, you could explicitly set the `RUNTIME DESTINATION`, see CMake help [Install.html#installing-targets](https://cmake.org/cmake/help/book/mastering-cmake/chapter/Install.html#installing-targets).

https://github.com/mfem/mfem/blob/master/CMakeLists.txt#L662-L665
```cmake
# Install the library
install(TARGETS ${PROJECT_NAME}
  EXPORT ${PROJECT_NAME_UC}Targets
  DESTINATION ${INSTALL_LIB_DIR}
  RUNTIME DESTINATION bin)
```
This will correctly copy the `.dll` to the bin dir and the `.dll.a` to the lib folder. Tested only with MINGW. Not sure if there are any impacts on linux builds.

**Comment by tzanio** [comment]
Thanks for the help @wo80 !

**Comment by tzanio** [comment]
@3rav do you want to add this to this list: https://github.com/mfem/mfem/blob/master/INSTALL#L56-L62
