### ISSUE TITLE
undefined RTSegmentFE in fem/fe/fe_rt.cpp in version 4.4

### ISSUE THREAD

**Issue by brechtsanders** [mfem/mfem#2914]
In mfem version 4.4 in file `fem/fe/fe_rt.cpp` there is a reference to `RTSegmentFE` which is not defined anywhere.

If I replace it with `H1SegmentFE` the build succeeds, but I have no idea if that's the right thing to do.

**Comment by mlstowell** [comment]
Good catch, @brechtsanders! It looks like we're not testing enough with the thread safe option turned on. I'll put together a quick PR to fix this.

**Comment by tzanio** [comment]
Discussion continued in  #2919
