### ISSUE TITLE
Bug in ex2

### ISSUE THREAD

**Issue by BBBBBbruce** [mfem/mfem#2915]
Hello, I noticed a little bug in the ex2 code.

In section 9, when setting the lame parameters,

Since material 1 is fixed and material 2 is free to move, lambda and mu should be changed in lambda(1).

the code below seems not to do anything.
```
Line 171: lambda(0) = lambda(1)*50;
Line 175: mu(0) = mu(1)*50;
```

**Comment by tzanio** [comment]
Hi @BBBBBbruce,

I am not sure I understand the question. After these two lines

```c++
   lambda = 1.0;
   lambda(0) = lambda(1)*50;
```
the vector `lambda` should be `50, 1`.

This means `lambda_func` will be `50` in material 1 and `1` in material 2. Why do you think this is an issue?

Tzanio

**Comment by BBBBBbruce** [comment]
Ok, but why assign 50 to material 1 and 1 to material 2? so material 2 would be more elastic. Ah I see, sorry, it was my problem. Originally, I was only changing lambda of material 1, but nothing changed... so I thought it was a mistake.
