### ISSUE TITLE
Navier Mini-app Units and adaptive time step

### ISSUE THREAD

**Issue by cdelv** [mfem/mfem#2917]
While reading the Navier Mini-app documentation I noticed that it needs the time step to initialize. But also, for the Step, you have to provide de time step. Then I was wondering, do I have to call setup every time I perform a time step in case my dt is variable?

```
void NavierSolver::Setup(double dt)
void NavierSolver::Step  (double & time, double dt, int cur_step, bool  provisional = false)
```
The documentation mentions that depending on the values of provisional and cur_step the time is updated or not, but it's not clear for me if I have to call Setup every time I change the dt or what values should cur_step and provisional have.

My second question is about the units. The constructor of the solver is

`NavierSolver::NavierSolver ( ParMesh * mesh, int  order, double  kin_vis)`

But the equation displayed on the MFEM documentation has the Raynolds number instead of the viscosity. https://mfem.org/fluids/#navier-stokes-mini-application. Also, the equation seems to be dimensionless, and the documentation of the constructor says:

 "Kinematic viscosity (dimensionless) is set using kin_vis and automatically converted to the Reynolds number. If you want to set the Reynolds number directly, you can provide the inverse". 

Reynolds number should also have the characteristic length and velocity, therefore it's not clear for me if they are assumed as 1. 

What is the conversion between real word units of length, time, and velocity and the values of the computer?
	
Thanks.

**Comment by jandrej** [comment]
You do not have to call `::Setup(double dt)` to choose a new timestep. Just take your `::Step(...)` with the desired `dt` and check if the solution is feasible. Rinse repeat.

Here is a little more explanation on the non-dimensionalization of the equations http://nek5000.github.io/NekDoc/theory.html#non-dimensional-navier-stokes.

The code assumes the density `rho = 1` and it is best to encapsulate all your physical measures in `Re`. What analysts generally do is to describe the problem and then use the equations described in the link to determine the appropriate Reynolds number for the simulation.

**Comment by cdelv** [comment]
@jandrej Thanks. Would be great if you could implement that feature. Now I understand better how to use the mini-app. 
To recap, the way the solver is made assumes characteristic length, velocity, and density equal to 1. Or directly apply the conversion from the Re number. to get the units.
