### ISSUE TITLE
Interpolating GridFunction values between domains through the shared boundary

### ISSUE THREAD

**Issue by kvoronin** [mfem/mfem#292]
Hi all,

Suppose I have a GridFunction defined on some f.e. space on one domain. I want to extract its values on the fixed part of the boundary (say, Gamma) and transfer them to another GridFunction defined on a different mesh in a different domain which also has Gamma as a part of its boundary (assume we know the bdr attributes which defines Gamma).

Could someone advise me how to do that in MFEM? I believe I can extract values at dofs at the boundary from the input GridFunction, but what is a good way to convert them into the dofs for the output GridFunction?

I will appreciate any comments.

Thanks,
Kirill

**Comment by tzanio** [comment]
Hi Kirill,

There are different options, but they all depend on your settings and require some synchronization between the two domains on Gamma.

For example, maybe you start with a single domain, where Gamma is an internal boundary and then  you split in two? If that's the case, you can piggyback on the ParMesh and ParFiniteElementSpace code.

If you can relate the numbering and orientations of the elements on Gamma, e.g. by using boundary element attributes, then you should be able to use `GetBdrElementDofs` on both sides to identify the sub-vector of dofs on Gamma.

Finally, it may be beneficial/more convenient to have a surface mesh and surface space on Gamma and relate that individually to each domain.

Hope this helps,
Tzanio

**Comment by kvoronin** [comment]
Thanks for sharing the ideas @tzanio!
