### ISSUE TITLE
A posteriori error estimator for Maxwell eddy current problem

### ISSUE THREAD

**Issue by edwardt9** [mfem/mfem#2922]
Hello, this is Thomas. 

Thanks for your excellent work on this finite element library!

I want to implement an adaptive finite element modeling algorithm for
the Maxwell eddy current model. My problem is quite similar to ex3 and ex22. While I see
there are only ZienkiewiczZhuEstimator and KellyErrorEstimator currently available in mfem.
So how can I change them to be a posteriori error estimator for Maxwell eddy current problem?
I start from https://epubs.siam.org/doi/10.1137/080713112 as a reference, the error estimator looks like:

$$
\\| \nabla \times (E-E_h) \\| _ {L^2(\Omega)} + \alpha \\|E-E_{h}\\| _ {L^2(\Omega)}
$$

where the first part is for the tangential magnetic field, and the second part is for
the normal current density. In this equation, only $E_{h}$ is the input from the finite element solution,
while the accurate solution $E$ is unknown. Has anyone worked on this type of problem before?

Any suggestions would be appreciated!

Best,
Thomas.

**Comment by edwardt9** [comment]
Reopen this issue...

**Comment by edwardt9** [comment]
How can I reopen this issue?

**Comment by edwardt9** [comment]
@tzanio @mlstowell Can you please help me?

**Comment by v-dobrev** [comment]
An error estimator cannot depend on an unknown quantity (like E in the expression you have above).

Typically, an error estimator will depend on the current discrete solution (like E_h in the expression you have above) and other know quantities like r.h.s. of the PDE, boundary conditions, and/or coefficients in the PDE operator.

What is the specific form of the error estimator that you want to implement?

**Comment by edwardt9** [comment]
> An error estimator cannot depend on an unknown quantity (like E in the expression you have above).
> 
> Typically, an error estimator will depend on the current discrete solution (like E_h in the expression you have above) and other know quantities like r.h.s. of the PDE, boundary conditions, and/or coefficients in the PDE operator.
> 
> What is the specific form of the error estimator that you want to implement?

@v-dobrev Thanks for your kind reply. Sorry for the unclear mathematical formula. The interested error estimator is the following:

\begin{equation}
\eta_{F}^{2}=\frac{1}{2} h_{F}(|| (\mathbf{n} \cdot \mathbf{J})|_{F_{+}} - (\mathbf{n} \cdot \mathbf{J})|_{F_{-}}||_{F}^{2} + || (\mathbf{n} \times \mathbf{H})|_{F_{+}} - (\mathbf{n} \times \mathbf{H})|_{F_{-}}||_{F}^{2})
\end{equation}
where, $\mathbf{n}$ is the unit normal vector of the face $F$, $F_{+}$ and $F_{-}$ are two sides of the face
\begin{equation}
\mathbf{H}=\frac{1}{\mu} (\nabla \times \mathbf{E}_{h})
\end{equation}
\begin{equation}
\mathbf{J}=\sigma \mathbf{E}_{h}
\end{equation}

**Comment by v-dobrev** [comment]
Hi @edwardt9,

There is an old branch that illustrates how to write an error estimator based on computing norms of jumps of discrete quantities across all interior faces. Take a look at the additions in this branch: https://github.com/mfem/mfem/compare/elast-resid-estimator and in particular the implementation of `ElasticityResidualErrorEstimator::ComputeEstimates()`. As the name suggests, the code is for elasticity where one computes norms of the jump of the normal stress. In your case, I assume `E_h` will be in a Nedelec space, so to evaluate its values and its curls on both sides of the face, you can use the methods `CalcPhysShape` and `CalcPhysCurl` of the `fe1` and `fe2` `FiniteElements`. These methods will apply the appropriate transformation to map values/curls from reference to physical space. In the example code (which needs to compute the gradients on both sides) the computation is done first in reference space with `CalcDShape` and then mapped to physical space by multiplying with `J^{-T}`; here `J` is the Jacobian of the element transformation on the respective side of the face at the respective quadrature point, `eip1` or `eip2`. This is an older code which can be updated to use `CalcPhysDShape` which will compute the gradient in physical space directly and that will simplify a little the code.

Let us know if you need more details about the code in the branch or have any other questions.

**Comment by edwardt9** [comment]
Thanks, @v-dobrev . 

I start from `KellyErrorEstimator::ComputeEstimates()` because I have to implement a parallel estimator. After some days' of coding, I still have additional questions about `IntegrationPoint` and the integration weight. Below are my code pieces:


```
// Evaluate electric field E at IP;
// IntegrationPoint from reference coordinates;
auto& ip = integrationrule.IntPoint(i);
// IntegrationPoint from physical coordinates;
IntegrationPoint eip;
// Transform the IntegrationPoint from reference coordinates to physical coordinates;
facetrans->Loc1.Transform(ip, eip);
// Set the IntegrationPoint to the element transform;
facetrans->Elem1->SetIntPoint(&eip);
// Get the FiniteElement;
const FiniteElement* fe = fespace->GetFE(facetrans->Elem1No);
// The shape function;
mfem::DenseMatrix shape;
shape.SetSize(fe->GetDof(), mesh->Dimension());
// Calculate the shape functions;
fe->CalcVShape(*facetrans->Elem1, shape);
// Calculate E=shape*solution
shape.MultTranspose(solution, e);
```

// Build scalar product of the shape functions with normal;
Vector normal(mesh->SpaceDimension());

```
if (mesh->Dimension() == mesh->SpaceDimension())
 {
   CalcOrtho(facetrans->Face->Jacobian(), normal);
 }
else
{
   Vector ref_normal(mesh->Dimension());
   facetrans->Loc1.Transf.SetIntPoint(&ip);
   CalcOrtho(facetrans->Loc1.Transf.Jacobian(), ref_normal);
   auto& eletrans = facetrans->GetElement1Transformation();
   eletrans.AdjugateJacobian().MultTranspose(ref_normal, normal);
   normal /= eletrans.Weight();
 }
```

`jumps(i) = e * normal * ip.weight * facetrans->Face->Weight();`

Should I multiply ```ip.weight``` or ```eip.weight```? Do I need to multiply ```J^{-T}``` here?  Is  ```facetrans->Face->Weight()``` necessary (taken from code in KellyErrorEstimator)?

Best,
Thomas.

**Comment by v-dobrev** [comment]
As far as understand the code snippets, you should use `ip.weight`, not `eip.weight`.

Regarding `facetrans->Face->Weight()`: multiplying by that seems unnecessary because the `normal` computed by `CalcOrtho` is not unit -- it has length equal to `facetrans->Face->Weight()`.
