### ISSUE TITLE
When the number of threads increases will the Average reduction factor increase or decrease

### ISSUE THREAD

**Issue by ajithkumarmcw** [mfem/mfem#2924]
I need to know if the Average reduction factor will increase or decrease when number of thread increases in mfem examples (ex0, ex1, ex2.. etc).

I have done some runs of parallel examples, to study the scalability i need info

**Comment by tzanio** [comment]
Hi @ajithkumarmcw,

In general the number of iterations for an AMG solver like BoomerAMG will increase a little when more parallelism is added, e.g. when more MPI tasks are used.

The increase is small though, and in practice AMG solvers are typically "optimal" for the problems they are designed for, i.e. the simulation time increases only slightly when you scale the problem up.

Hope this helps,
Tzanio

**Comment by ajithkumarmcw** [comment]
1. okay you told about iterations but what about average reduction factor ? 
2. which parameter will be better for scaling(i.e when no of threads are increased from 1 to 128) ?

**Comment by tzanio** [comment]
Hi @ajithkumarmcw,

Convergence will generally get worse with more parallelism, and the average reduction of the residual norm in particular will go up with more iterations.

The AMG solvers have many parameters, and while we have reasonable defaults in MFEM, you may want to consult the hypre documentation for all available optons.

Tzanio
