### ISSUE TITLE
Bug: Mesh::PrintVTK does not work correctly for pyramid elements

### ISSUE THREAD

**Issue by mdeuse** [mfem/mfem#2926]
Hi,
I have noticed that with mfem4.4, the Mesh::PrintVTK does not work correctly for pyramid elements. Essentially, it seems that it does not write the correct CELL_TYPES in the .vtk file for the pyramids. Apparently, the files vtk.hpp and vtk.cpp have not been adapted to handle pyramids in mfem4.4.

**Comment by pazner** [comment]
Does it work for you with #2932?

**Comment by mdeuse** [comment]
Hi @pazner , yes it is working fine for me with your fix, thank you!
