### ISSUE TITLE
Get access to eliminated entries from nonlinear form gradient assembly

### ISSUE THREAD

**Issue by tuckerbabcock** [mfem/mfem#2928]
To solve for the discrete adjoint that corresponds to my nonlinear form, I need access to the rows/cols that were eliminated from the Jacobian when imposing essential boundary conditions on the Jacobian (so that I may correctly set the RHS for the adjoint problem).

Currently there is no way to get access to these entries, so I've written a simple draft implementation that would give access to the `pGrad_e` (just for the `ParNonlinearForm`) as an out-parameter in `GetGradient` in #2927. I'm not at all tied to the draft implementation (I just needed to get a working example going), so I'm hoping to discuss other potential approaches that might be more palatable to the MFEM team that will extend the nonlinear form API.

One thought I had was that I could use `GetLocalGradient` and parallel assemble that myself, and then eliminate the rows/cols myself. My concerns with that approach were that if/when the `ParNonlinearForm` supports `GetGradient` with DG interior face integrators, I would not automatically get that support.

Please let me know any thoughts you have!

Thanks,

Tucker

**Comment by rcarson3** [comment]
@tuckerbabcock if you copied the essential true DOFs from `(Par)NonlinearForm::GetEssentialTrueDOFs()` into an array, and then did something like:

```c++
// nlf here is our (Par)NonlinearForm
// Something like this to copy the dofs
Array<int> copied_ess_tdofs(nlf.GetEssentialTrueDOFs());
Array<int> zeros;
// Setting our essential true dofs to zero
nlf.SetEssentialTrueDOFs(zeros);
// get our gradient with everything preserved
auto gradient = nlf.GetGradient(x);
// do what we need with the essential boundary condition portion of things with the full gradient
// reset our essential BCs to what they used to be
nlf.SetEssentialTrueDOFs(copied_ess_tdofs);
```

Would this pattern work for your problem?

**Comment by tuckerbabcock** [comment]
@rcarson3 thanks for the suggestion! I'm not sure why I didn't think to do that. That pattern seems to work great for me.
I'll go ahead and close this issue and that PR since that approach works.
