### ISSUE TITLE
Issues of "brew install mfem"

### ISSUE THREAD

**Issue by MollyRaver** [mfem/mfem#293]
Hi, I installed mfem through:
>> brew install hypre
>> brew link hypre
>> brew install metis
>> brew link metis
>> brew install mfem
>> brew link mfem

All of them are located at "/usr/local/Cellar/".

But the library of MFEM is not linked so when I try to run the examples in mfem-3.3/examples by
>> make ex1

It shows "makefile:76: *** The MFEM library is not built.  Stop."

It must be a pretty easy problem, please let me know how to resolve it. Thank you!

**Comment by tzanio** [comment]
@goxberry: can you take a look at this?

**Comment by v-dobrev** [comment]
Hi @MollyRaver,

I see that you also install hypre and metis so I think you want to install the parallel (MPI) mfem version. You should be able to do that with
```sh
brew install mfem --with-mpi
```
If you do not need the parallel version, then you do not need neither hypre nor metis.

Regarding building the examples: try building with the following options
```sh
make ex1 MFEM_DIR=`brew --prefix mfem` CONFIG_MK=`brew --prefix mfem`/config.mk SRC=
```

As an alternative to using homebrew (especially if you want to build and run examples and miniapps and view the results) is to follow the instructions for [building MFEM with GLVis](http://mfem.org/building/). Building GLVis is optional so you can skip that part at first and build GLVis later if you want to look at the results from the examples or miniapps.

Let us know if you encounter any further issues.

Hope this helps,
Veselin

**Comment by MollyRaver** [comment]
Hi, @v-dobrev 

Thank you for your answer! I have fixed this problem.

Best,
