### ISSUE TITLE
Cubit mesh reader reads wrong number of boundary attributes

### ISSUE THREAD

**Issue by juan42** [mfem/mfem#294]
If you define 1 sideset in an exodus mesh and give it "100" as id, the mesh reader thinks it has 100 boundary attributes.

Maybe the cubit reader needs an overhaul in general. If i get some free time in the office i will try to work on that.

**Comment by tzanio** [comment]
The boundary attributes are set here:

https://github.com/mfem/mfem/blob/1569425857975d7c961b97d09c300da09aad9f82/mesh/mesh_readers.cpp#L1490-L1495

see also

https://github.com/mfem/mfem/blob/1569425857975d7c961b97d09c300da09aad9f82/mesh/mesh_readers.cpp#L1701-L1710

From MFEM perspective it should be fine to have just one attribute with id "100".

@Dan2997925, do you have any suggestions for @juan42?

**Comment by tzanio** [comment]
@juan42, just wondering if you had any further thoughts on this issue?

**Comment by juan42** [comment]
I will take another look when #207 is ready and merged. If everything else in MFEM does not depend on iterating through the ids from 0 to the corresponding ID this should be easy.

**Comment by juan42** [comment]
I don't know if something happened, but as i worked on the issue today, i had no problems using a mesh with two boundary attributes (ids are 100 and 200). mesh->bdr_attributes.Size() returned 2. So i think this is resolved?

**Comment by tzanio** [comment]
Excellent, thanks @juan42!
