### ISSUE TITLE
Fix GSLIB tests

### ISSUE THREAD

**Issue by v-dobrev** [mfem/mfem#2940]
Running `make test` in `miniapps/gslib` fails for one of the tests:
```console
    GSLIB miniapp [ mpirun -np 4 schwarz_ex1p ... ]: FAILED  (0.78s 11916kB)
```
with the message
```console
Verification failed: (np_list.Sum() == num_procs) is false:
 -->  The individual mpi ranks for each of the meshes do not add up to the total ranks specified.
 ... in function: int main(int, char **)
 ... in file: schwarz_ex1p.cpp:163
```

Another small deficiency: the CMake file in `miniapps/gslib` does define any tests -- ideally, it will define the same tests as the makefile.

**Comment by tzanio** [comment]
Discussion continued in @2945
