### ISSUE TITLE
Debugging lambdas in the `MFEM_FORALL` macro

### ISSUE THREAD

**Issue by v-dobrev** [mfem/mfem#2958]
Currently, kernels written using the `MFEM_FORALL` macro are collapsed into a single line in the debug info. This makes it impossible to step through such lambdas or get accurate line information during crashes.

One suggestion that came up in a discussion with @artv3 and @samuelpmishLLNL is to define an alternative, non-macro version of `MFEM_FORALL`, e.g. `mfem::forall`, that will use a single `__host__ __device__` version of the lambda which will have better debug info. This is different from the `MFEM_FORALL` macro which generates two separate lambdas for host and device (which may be more performant?) but on the other hand, it collapses the whole lambda into a single line.

**Comment by v-dobrev** [comment]
cc: @camierjs, @YohannDudouit, @tzanio

**Comment by tzanio** [comment]
Discussion continued in https://github.com/mfem/mfem/pull/3454
