### ISSUE TITLE
Hessian for 3D Finite Element

### ISSUE THREAD

**Issue by KazemKamran** [mfem/mfem#296]
I am working on a stabilized Navier Stokes solver in MFEM and  for the viscous term stabilization in higher order, I need to compute the second derivatives. For which an extension of  the `CalcHessian` method, that is already implemented for some [2D](http://mfem.github.io/doxygen/html/classmfem_1_1Cubic2DFiniteElement.html#a149a9fc5099a00ed71a8e8d228e51de1) Finite Elements, to 3D is desired. Something like` mfem::Cubic3DFiniteElement`. 

Following the notation that is already there for the 2D case, i.e. each row of the Hessian contains the derivatives in **{u_xx, u_xy, u_yy}** order, I suggest the following order in 3D:
**{u_00, u_01, u_02, u_12, u_22, u_11}**, assuming 0, 1 and 2 represents x, y and z respectively. 
The reason for this choice of ordering is, first it is compatible with the 2D case and second the summation of the indices for each component gives the position of that component in the vector, except for u_11 albeit, which I think is helpful in implementing matrix-free form of terms like **J^-T H J^-1**.  

I can implement it for `Quadratic3DFiniteElement` and `Cubic3DFiniteElement` cases and I am  wondering if there is a  recursive formula to compute it for the more general case like `H1_FiniteElement`.

Cheers,
Kazem

**Comment by v-dobrev** [comment]
Hi Kazem,

I'm not sure I understand your argument about the ordering of the second derivatives in 3D. To me it is more natural to follow lexicographical ordering: `{u_xx, u_xy, u_xz, u_yy, u_yz, u_zz}`.

Implementing this for some `H1` elements may not be too hard - e.g. for tensor product elements in 2D and 3D, i.e. quads and hexes. The approach I'd use is to add a version of `Poly_1D::Basis::Eval()` that computes the values of the polynomial, its first derivative and its second derivative. Then use that to implement `CalcHessian()`.

For simplex elements, the default nodal basis that we use is not based on uniform node locations, so I don't think there is a simple formula. We should be able to use a general approach though - similar to what we do for the `CalcDShape()` method. The approach there is to compute the derivatives in a basis which is a function of the barycentric coordinates, `\lambda_i`, `i=1,2,3,4` and then apply a change a basis transformation to the actual nodal basis. The complexity of this approach with respect to the order, `p` is not great - `O(p^6)` - but this is what we use for `CalcShape()` and `CalcDShape()` as well.

Another option for simplices is to use the positive basis implemented in class `H1Pos_TetrahedronElement` where evaluating the basis is faster - `O(p^4)` - but the conditioning of the assembled matrices, with respect to `p` is worse, I think.

Anyway, if you do not need the general case (i.e. arbitrary order) - don't worry about it. We can add that later.

This will be a nice addition to MFEM, let us know if we can help with anything.

Thanks,
Veselin

**Comment by IdoAkkerman** [comment]
I am working on stabilised finite elements for NS as well and at some point would like to compute Hessians as well. Is there a branch you are working so I can have a look?

**Comment by KazemKamran** [comment]
I will soon make the commit and let you know. Although I haven't done any contribution to the Hessian calculation yet.

**Comment by tzanio** [comment]
Hi @KazemKamran, any progress on this? Should we leave this issue open?

**Comment by KazemKamran** [comment]
Hi, well I have upñoaded the branch with NS stationary stabilized VMS and Veselin comment is quiet extensive, I haven’t implemented the Hessian though but I got my answer, So I think we could close it.

**Comment by tzanio** [comment]
The branch is: [pumi-NS](https://github.com/mfem/mfem/tree/pumi-NS)
