### ISSUE TITLE
I can't get the correct global index of the local element with the "GetGlobalElementNum()" or "GetGlobalElementIndices " function.

### ISSUE THREAD

**Issue by liuzg-23** [mfem/mfem#2964]
Hello,
Please see my code as following:

```c++
Mesh* mesh = new Mesh(mesh_file.c_str(), 1, 1);
ParMesh* pmesh = new ParMesh(MPI_COMM_WORLD, *mesh);
Array<HYPRE_Int> gi(pmesh->GetNE());
pmesh->GetGlobalElementIndices(gi);
if(myid==0)
{
  std::cout<<"v1: "<<pmesh->GetElementVolume(1000)<<std::endl;
  std::cout<<"v2: "<<mesh->GetElementVolume(gi[1000])<<std::endl;
}
```

In the output result, the v1 and v2 is different. So I want to know that how can I
get the correct global index of the local element. Thanks very much!

Zhengguang.

**Comment by psocratis** [comment]
Hi @liuzg-23, 

The way that you are getting the global element numbers by `pmesh->GetGlobalElementIndices()` seems fine to me.

I am assuming by `GetElementVolume()` you are referring to `mesh::GetElementVolume()` right? The `mesh::GetElementVolume()` is intented to work only with a local element number as an input. 

Best,

Socratis

**Comment by liuzg-23** [comment]
Hi @psocratis,

Thanks for your reply. I want to confirm one thing that if the global indices of the local mesh got with the function "pmesh->GetGlobalElementIndices()" are the same as the global indices in global mesh before domain decomposition.

Regards,
Zhengguang.

**Comment by psocratis** [comment]
Hi @liuzg-23, 

That's not nessessarily true. New global numbers are assigned during the partition stage. For example see below 

<img width="459" alt="image" src="https://user-images.githubusercontent.com/14336752/162851488-66d1ad8a-0e8f-4fd8-93d1-c45ccf5ce25a.png">
<img width="459" alt="image" src="https://user-images.githubusercontent.com/14336752/162851580-a02927af-3001-437d-94a2-0523839242e9.png">

**Comment by liuzg-23** [comment]
Hi @psocratis,

Thanks very much. I got you. However, I want to know if there are some method in MFEM that can find the old global index of the element in local mesh. Because I want to map some physical quantities from the local grid to the global grid before domain decomposition.

Regards,
Zhengguang.

**Comment by liuzg-23** [comment]
Hi @psocratis,

Maybe there are another method can solve my problem, which is that getting a new global mesh from all local mesh. Do you know if there is a method in MFEM can do that?

Regards,
Zhengguang.

**Comment by psocratis** [comment]
@liuzg-23,

One easy way I can think of for constructing the map from the local mesh to the old global mesh is to use attributes. You can assign element attributes to the old global (serial) mesh, with something like this 
````cpp
   for (int i = 0; i<mesh.GetNE(); i++)
   {
      mesh.SetAttribute(i,i+1);
   }
   mesh.SetAttributes();
````
After the partitioning these attributes are propagated to the `pmesh` and you can read them. For example you can get them with 
````cpp
for (int i = 0; i< pmesh.GetNE(); i++)
{
   mfem::out << "local element no: " << i << ", global elem num: " << pmesh.GetGlobalElementNum(i) 
             << ", old global elem no: "  << pmesh.GetAttribute(i)-1 << endl;
}
````
Note that an attribute cannot be zero so you can shift by one during assignment and shift back when reading them.

Would something like the above work for you? 

For the example meshes I posted above here is the output 

processor 0. 
````
local element no: 0, global elem num: 0, old global elem no: 3
local element no: 1, global elem num: 1, old global elem no: 4
local element no: 2, global elem num: 2, old global elem no: 17
local element no: 3, global elem num: 3, old global elem no: 18
local element no: 4, global elem num: 4, old global elem no: 19
````

processor 1

````
local element no: 0, global elem num: 5, old global elem no: 0
local element no: 1, global elem num: 6, old global elem no: 5
local element no: 2, global elem num: 7, old global elem no: 6
local element no: 3, global elem num: 8, old global elem no: 7
local element no: 4, global elem num: 9, old global elem no: 8
````

processor 2
````
local element no: 0, global elem num: 10, old global elem no: 12
local element no: 1, global elem num: 11, old global elem no: 13
local element no: 2, global elem num: 12, old global elem no: 14
local element no: 3, global elem num: 13, old global elem no: 15
local element no: 4, global elem num: 14, old global elem no: 16
````
processor 3

````
local element no: 0, global elem num: 15, old global elem no: 1
local element no: 1, global elem num: 16, old global elem no: 2
local element no: 2, global elem num: 17, old global elem no: 9
local element no: 3, global elem num: 18, old global elem no: 10
local element no: 4, global elem num: 19, old global elem no: 11
````

**Comment by liuzg-23** [comment]
Hi @psocratis,

That's a great idea. I will try it. Thanks very much for your help. 

Best wishes,
Zhengguang.

**Comment by psocratis** [comment]
@liuzg-23, closing this now. Feel free to reopen it if something related comes up.
