### ISSUE TITLE
Nedelec space 

### ISSUE THREAD

**Issue by salomole** [mfem/mfem#2967]
Hi ! 

I solve a first system to obtain a variable called `p`.

Then, I want to calculate `A*Grad(p)`, with `A` a `GridFunctionCoefficient` (the solution is continuous). I calculate `A*Grad(p)` in Nedelec space. My question : By passing through this space H(Curl), do I ensure `Curl[A*Grad(p)] = 0`?

Best,

salomole

**Comment by mlstowell** [comment]
Hi, @salomole, 

No, not in general. In fact there is no guarantee that `Curl[A*Grad(p)] = 0` when everything is continuous and infinitely differentiable. This depends on whether or not `Grad(A)` is perpendicular to `Grad(p)`.

In the discrete case you may need to compute `A*Grad(p)` carefully (we can discuss your options if that would be useful). And even then you may only find `Curl[A*Grad(p)] = 0` in the limit as your mesh size goes to zero.

Best wishes,
Mark

**Comment by salomole** [comment]
Hello Mark,

Ok, I thought that the Raviart-Thomas space ensured a zero divergence and the Nedelec space ensured a zero rotational, but am I mistaken? After solving `p` in a H1 space, I calculate `A*Grad(p)` in the Nedelec space in this way :

```
GridFunction A_Grad_P(fespace_nd);

Vector pn;
pn.SetSize(fespace_truevsize);
pn = 0.0;
p.GetTrueDofs(pn);

Vector G_vec;
G_vec.SetSize(fespace_nd_truevsize);
G_vec = 0.0;

Vector A_Grad_P_vec;
A_Grad_P_vec.SetSize(fespace_nd_truevsize);
A_Grad_P_vec = 0.0;

SparseMatrix G;
SparseMatrix M;

BilinearForm *M_form= new BilinearForm(fespace_nd);
M_form->AddDomainIntegrator(new VectorFEMassIntegrator);

MixedBilinearForm *G_form= new MixedBilinearForm(fespace, fespace_nd);
G_form->AddDomainIntegrator(new MixedVectorGradientIntegrator(COEF_A)); 

M_form->Assemble();
M_form->FormSystemMatrix(empty, M);

G_form->Assemble();
G_form->FormRectangularSystemMatrix(empty, empty, G);

// A_Grad_P_vec = M^{-1} (G_vec)

G.Mult(pn, G_vec);

DSmoother M_pre; 
CGSolver M_sol;

M_sol.SetPreconditioner(M_pre);
M_sol.SetOperator(M);

M_sol.iterative_mode = false;
M_sol.SetRelTol(1e-9);
M_sol.SetAbsTol(0.0);
M_sol.SetMaxIter(100);
M_sol.SetPrintLevel(0);

M_sol.Mult(G_vec, A_Grad_P_vec);

A_Grad_P.SetFromTrueDofs(A_Grad_P_vec);

With `fespace_nd` the Nedelec space and `fespace` a H1 space.
```
