### ISSUE TITLE
Resolve C4819 warnings for building on Windows using Visual Studio

### ISSUE THREAD

**Issue by adam-sim-dev** [mfem/mfem#2976]
Hello,

There are some C4819 warnings when building on Windows using Visual Studio. The long list of warnings is annoying when users try to find the build outputs for their codes in the build log.

`The file contains a character that cannot be represented in the current code page (number). Save the file in Unicode format to prevent data loss.`

Most of them are in the comments, for example https://github.com/mfem/mfem/blob/master/fem/estimators.cpp#L249, so resolving them won't affect the codes. I am glad to open a PR to address some of them in the sequential mfem code files, by using the latex equations. However, before doing that I need to ask the code owners about their choices.

Best,
Adam

**Comment by tzanio** [comment]
We don't have policy against unicode characters in comments, and generally have found those to be useful in several places.

Is this really not allowed in typical Windows systems? 

I  don't see it in our [Windows CI builds](https://github.com/mfem/mfem/runs/6242166201?check_suite_focus=true). (I do see [C4244](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-2-c4244), [C4250](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-2-c4250?view=msvc-170), [C4267](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-3-c4267), [C4805](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-3-c4580) and [C4996](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-3-c4996)).

**Comment by v-dobrev** [comment]
What version of MSVC are you using? This warning does not show up in our Appveyor CI either (e.g. here https://ci.appveyor.com/project/mfem/mfem/builds/43337614) which uses Visual Studio 15 2017.

When I open that file with VS Code, it does say "UTF-8" encoding, so I'm not sure what the compiler is complaining about. Maybe it expects the file to have BOM (https://en.wikipedia.org/wiki/Byte_order_mark)? Unfortunately, other compilers do not like BOM to the extend that they just crash if they encounter one. (some details can be found here: https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-1-c4819)

I suspect that there is a flag you can add to suppress this particular warning -- see https://docs.microsoft.com/en-us/cpp/build/reference/compiler-option-warning-level. Maybe we can add this flag by default in our CMake file(s) when building with MSVC.

**Comment by adam-sim-dev** [comment]
Hi @v-dobrev , I am using Visual Studio 2022.

**Comment by v-dobrev** [comment]
According to the log, the Windows CI that @tzanio linked above, https://github.com/mfem/mfem/issues/2976#issuecomment-1114350140, used the following:
* `-- Building for: Visual Studio 17 2022`,
* `-- The CXX compiler identification is MSVC 19.31.31107.0`,
* `-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.31.31103/bin/Hostx64/x64/cl.exe - skipped`

I'm not sure what to make of all these different version numbers. I assume, in your setup, something is different?

In any case, does adding the flag `/wd4819` (to suppress this specific warning) work for you?

**Comment by adam-sim-dev** [comment]
Hi @v-dobrev , I think the flag /wd4819 is the simplest way to suppress the warnings.

**Comment by v-dobrev** [comment]
> Hi @v-dobrev , I think the flag /wd4819 is the simplest way to suppress the warnings.

Okay. @tzanio what do you think about adding the flag `/wd4819` to CMake when using MSVC? I'm fine with such addition.

@adam-sim-dev, if @tzanio is also fine with adding this to CMake, do you want to create a small PR for that?

**Comment by adam-sim-dev** [comment]
@v-dobrev , should I add the following scripts to mfem/CMakeLists.txt?

```
if (WIN32)
  set_target_properties(${PROJECT_NAME} PROPERTIES COMPILE_FLAGS "/wd4819")
endif()
```

Which exact line do you expect it to appear in the CMakeLists.txt? Then I can open a PR.

**Comment by tzanio** [comment]
> what do you think about adding the flag `/wd4819` to CMake when using MSVC? I'm fine with such addition.

sounds good to me

**Comment by v-dobrev** [comment]
Hi @adam-sim-dev,

It is better to use `target_compile_options` (https://cmake.org/cmake/help/v3.8/command/target_compile_options.html) instead of `set_target_properties` and also check `if (MSVC)` instead of `if (WIN32)`.

A good place to add this is after these lines: https://github.com/mfem/mfem/blob/343480ff18492f2d328986699f023bd75724ac2b/CMakeLists.txt#L546-L548

Thanks for taking care of this addition!

**Comment by tzanio** [comment]
Discussion continued in #3004
