### ISSUE TITLE
hang in hypre_MatvecCommPkgCreate()

### ISSUE THREAD

**Issue by ptsuji** [mfem/mfem#2978]
I've posted this on the Hypre Github page, but I figured it should be here as well, since I'm using the MFEM HypreParMatrix interface.

With Hypre 2.24.0 and MFEM 4.4, I'm trying to construct a rectangular HypreParMatrix using the generic CSR interface in MFEM (https://github.com/mfem/mfem/blob/fef1928708bb455f46aa611ddf73a4fd3d1c1974/linalg/hypre.cpp#L1176), but the code hangs indefinitely upon calling hypre_MatvecCommPkgCreate() when running on more than one process (https://github.com/mfem/mfem/blob/fef1928708bb455f46aa611ddf73a4fd3d1c1974/linalg/hypre.cpp#L1312). I was able to print out the matrices right before, and have attached the files for a 2 processor decomposition here.

[hypre_ParCSRMatrix.00000.txt](https://github.com/mfem/mfem/files/8565080/hypre_ParCSRMatrix.00000.txt)
[hypre_ParCSRMatrix.00001.txt](https://github.com/mfem/mfem/files/8565081/hypre_ParCSRMatrix.00001.txt)

I didn't see this interface being exercised in any of the examples/tests. Should we be using another interface for general rectangular matrices?

For context, it occurs when trying to construct the constraint matrices which I'm giving to the SchurConstrainedHypreSolver class. On a single process, the problem runs as expected, but on two or more processes, it hangs (as described above).

**Comment by tzanio** [comment]
Hi @ptsuji,

Can you provide a few additional details: 

- how do you configure and build hypre?
- how do you configure and build MFEM?
- is this a CPU or a GPU run?

In other similar context, e.g. when creating the discrete gradient operator for electromagnetic problems, we use `MakeRectangularBlockDiag` to build `A`, followed by `R A P` with the trial interpolation `P` and test restriction `R`

https://github.com/mfem/mfem/blob/5308d285f732c45f3c381bcee415581fd34b1cb2/fem/pbilinearform.cpp#L620-L638 

In this context, `A` is the local constraint matrix on each processor (in local numbering), `P` is the parallel interpolation for input variables, and `R` is the restriction for output variables.

Tzanio

**Comment by ptsuji** [comment]
Hi @tzanio,

This is a CPU build, using the Intel OneAPI 2021.4 compiler on rzgenie. We configure Hypre using the configure script and build with their makefiles, since we're using the FEI and that is not fully supported with the CMake build (a comment in the main CMakeLists.txt file says this). We build MFEM with CMake. I've attached the config.log file for Hypre and CMakeCache.txt file for MFEM here.

[config.log](https://github.com/mfem/mfem/files/8612492/config.log)
[CMakeCache.txt](https://github.com/mfem/mfem/files/8612495/CMakeCache.txt)

I'll take a look at the MakeRectangularBlockDiag stuff, but my guess is that it might not be fully applicable for contact problems; we may or may not have contact constraints on some processors, and we need to be able to specify an arbitrary number of rows on each process. That's why I went with the most generic rectangular interface I could find.

-Paul

**Comment by tzanio** [comment]
OK, maybe another option then is to directly use hypre's [IJ interface](https://hypre.readthedocs.io/en/latest/ch-ij.html).

The matrix produced by that could be then just type casted to `HyperParMatrix`.

Will this be more convenient?

**Comment by ptsuji** [comment]
The IJ interface looks like a good path forward, I can try putting that into our code and see if it works. I'll still have to convert it to a mfem::HypreParMatrix afterwards, but it looks like there are functions to do that.

**Comment by tzanio** [comment]
Here is a simple example of using the IJ interface: https://github.com/hypre-space/hypre/blob/master/src/examples/ex5.c

Once you have the `parcsr_A` object, you can use  `HypreParMatrix(hypre_ParCSRMatrix *parcsr_A, bool owner = true)`.

**Comment by tzanio** [comment]
👋 @ptsuji, were you able to make progress on this?

**Comment by ptsuji** [comment]
@tzanio the original issue was that I was using GlobalVSize() to set the number of columns (https://docs.mfem.org/html/pfespace_8hpp_source.html#l00283). However, this number seems to not give the number of columns when running on more than one process, which is why it worked in serial but not parallel (I guess I should have been using GlobalTrueVSize()). I've fixed the error by getting the number of columns directly from the stiffness matrix.
