### ISSUE TITLE
HypreParMatrix printed format details

### ISSUE THREAD

**Issue by M8kmyday** [mfem/mfem#2992]
### Discussed in https://github.com/mfem/mfem/discussions/2984

<div type='discussions-op-text'>

<sup>Originally posted by **M8kmyday** April 28, 2022</sup>
I am saving multiple HypreParMatrix matrices using the Print() method, then reading the results into a c-language program for further processing using complex Petsc and Slepc with Petsc matrices.  For a sequential Print(), the format is
row column value
and reading this and placing the values into Petsc Mat's is working fine and giving correct results.  I am now working on using more than one rank, and the Print() method is breaking the HypreParMatrix  into multiple files.  The format is
i j value
but the i and j do not directly indicate the row and column.  For example, here is a snippet writing with a single rank:
      0 2735 0 2735
      0 0 1.08466983310771e-01
      0 2356 1.05181854614385e-02
      0 2355 -7.42156317001008e-02
      0 2354 7.97578195137156e-02
      0 2353 -4.11964569354750e-02
      0 2352 -2.66776234624309e-02
      0 927 -8.04891801767019e-04
      0 928 -2.93152666654374e-02
      0 929 -2.26686555987002e-02
      0 926 -8.26071976800703e-03
      0 925 1.09895109549185e-02
      0 924 -2.07156019880894e-02
      0 1205 2.35306230243572e-02
      0 1204 -1.20511309124902e-02
      0 1203 2.31517936846435e-03
      0 1202 1.59511656150841e-02
      0 1201 -1.37900224493088e-02
      0 1200 -1.43602114243132e-02
      0 6 1.77192030824521e-03
      0 7 -2.79368876023576e-03
      0 8 -2.37459349809672e-03
      0 5 -4.44239253034057e-03
      0 4 -7.89813175095653e-04
      0 3 3.69250178797575e-03
      0 2 -6.48006743608447e-04
      0 1 -2.73559079331549e-02
      0 2357 1.24736675681853e-02
and here it the same HypreParMatrix written with 2 ranks with the snippet from file *.00000:
      0 1391 0 1391
      0 0 1.08466983310771e-01
      0 1210 1.05181854614385e-02
      0 1209 -7.42156317001008e-02
      0 1208 7.97578195137156e-02
      0 1207 -4.11964569354750e-02
      0 1206 -2.66776234624309e-02
      0 480 -8.04891801767019e-04
      0 481 -2.93152666654374e-02
      0 482 -2.26686555987002e-02
      0 479 -8.26071976800703e-03
      0 478 1.09895109549185e-02
      0 477 -2.07156019880894e-02
      0 629 2.35306230243572e-02
      0 628 -1.20511309124902e-02
      0 627 2.31517936846435e-03
      0 626 1.59511656150841e-02
      0 625 -1.37900224493088e-02
      0 624 -1.43602114243132e-02
      0 6 1.77192030824521e-03
      0 7 -2.79368876023576e-03
      0 8 -2.37459349809672e-03
      0 5 -4.44239253034057e-03
      0 4 -7.89813175095653e-04
      0 3 3.69250178797575e-03
      0 2 -6.48006743608447e-04
      0 1 -2.73559079331549e-02
      0 1211 1.24736675681853e-02
So the data is the same, but the i j indices are different.  Farther down the files, the i j become quite different between the two files.  I cannot figure out how to get the actual row and column numbers from the multi-rank *.xxxxx files.  I have reviewed the source code for hypre_ParCSRMatrixReadIJ and hypre_ParCSRMatrixPrintIJ, but so far, I'm not able to reverse-engineer the needed algorithm.

If someone could provide hints or information on any one of the following, I can get going again:
1. The algorithm to calculate the row and column from the i j indices in the multi-rank *.xxxxx files.
2. A pointer to a routine that imports a multi-rank HypreParMatrix matrix into a Petsc Mat.  [I have searched, but no luck.]
3. Documentation on the structure and operation of a HypreParMatrix so that I can reverse engineer hypre_ParCSRMatrixReadIJ to get the needed algorithm.  [No luck with a search.]
4. Some other idea about how to read a multi-rank HypreParMatrix file set into a Petsc Mat.

</div>

**Comment by M8kmyday** [comment]
Printing out some data from hypre_ParCSRMatrixPrintIJ, I get for a sequential run:

         rank=0  i=0  first_row_index=0  base_i=0  I=0  j=0  first_col_diag=0  diag_j[j]=0  base_j=0  J=0  diag_data[j]=0.108467
         rank=0  i=0  first_row_index=0  base_i=0  I=0  j=1  first_col_diag=0  diag_j[j]=2356  base_j=0  J=2356  diag_data[j]=0.0105182
         rank=0  i=0  first_row_index=0  base_i=0  I=0  j=2  first_col_diag=0  diag_j[j]=2355  base_j=0  J=2355  diag_data[j]=-0.0742156
         rank=0  i=0  first_row_index=0  base_i=0  I=0  j=3  first_col_diag=0  diag_j[j]=2354  base_j=0  J=2354  diag_data[j]=0.0797578

then re-running with 2 ranks, I get:

         rank=0  i=0  first_row_index=0  base_i=0  I=0  j=0  first_col_diag=0  diag_j[j]=0  base_j=0  J=0  diag_data[j]=0.108467
         rank=0  i=0  first_row_index=0  base_i=0  I=0  j=1  first_col_diag=0  diag_j[j]=1210  base_j=0  J=1210  diag_data[j]=0.0105182
         rank=0  i=0  first_row_index=0  base_i=0  I=0  j=2  first_col_diag=0  diag_j[j]=1209  base_j=0  J=1209  diag_data[j]=-0.0742156
         rank=0  i=0  first_row_index=0  base_i=0  I=0  j=3  first_col_diag=0  diag_j[j]=1208  base_j=0  J=1208  diag_data[j]=0.0797578

I see diag_j having different column numbers as an integral part of the HypreParMatrix.  For one of the constructors for HypreParMatrix, there is a comment that "The local matrix should be of size (local) nrows by (global) glob_ncols."  From this, I would expect that the rows for any number of ranks would go from 0 to 2356.  However, with 2 ranks, it goes from 0 to 1210 on rank 0.  With 3 ranks, it is a smaller number still.

I'm trying to find some method or methods that provide the necessary information to get the global column from the local HypreParMatrix.

I do not see useful methods for the ParMesh, but then, the ParMesh does not know anything about the elements.  For ParBilinearForm, there are some methods that look useful, such as GetTrueDofOffsets(), GetDofOffsets(), GetLocalTDofNumber(), and GetGlobalTDofNumber(), but in coding these up to view what they have to offer, I still just see the row_start/col_start information.

**Comment by M8kmyday** [comment]
My basic code sequence is

      fec_ND=new ND_FECollection(order,pmesh->Dimension());
      fespace_ND=new ParFiniteElementSpace(pmesh,fec_ND);

      ParBilinearForm Tt_eps_re=ParBilinearForm(fespace_ND);
      Tt_eps_re.AddDomainIntegrator(new VectorFEMassIntegrator (*ko2Re_e));
      Tt_eps_re.Assemble();
      Tt_eps_re.Finalize();
      saveMat (Tt_eps_re,"Tt_eps_re_mat",temporaryDirectory,projData->project_name,false);

Then

      void saveMat (ParBilinearForm &blf, string name, string directory, char *uniquifier, bool transpose) {
         stringstream ss;
         ss << directory << "/" << name << "." << uniquifier;

         HypreParMatrix *mat=blf.ParallelAssemble();
         if (transpose) mat=mat->Transpose();
         mat->Print(ss.str().c_str());

         delete mat;
      }
This is working well for sequential operation with one rank, but with multiple ranks, the columns in the saved files [and even rows, sometimes, I think] do not align with the values for the global matrix.  The local to global transformation is needed for when I read the output files with a companion C-program to load into complex Petsc matrices to solve for the complex eigenvalues/eigenvectors using Slepc.

**Comment by mlstowell** [comment]
Hello, @M8kmyday, 

We don't pay much, if any, attention to the row and column indices of our matrices. Clearly, we need to assign these indices in a consistent manner but their values are not particularly important. The drawback of this is that we are tied to a particular mesh partitioning i.e. a matrix and vector must be constructed using the same mesh partitioning in order for them to be used together.

Consequently, the row and column indices appearing in your matrix files can probably be assumed to be correct. If you need to read your matrices into a different program then you must ensure that all of your matrices were build using the same mesh partitioning. If this has been done then the eigenvectors computed by your separate program should be compatible with GridFunctions defined using the same mesh partitioning that was used to generate the matrices.

We do not currently have any way to produce a mapping between degrees of freedom from one partitioning to another. Of course, this could be useful and we have been discussing how to generate such a mapping but it does not currently exist. Also it doesn't sound like this mapping is necessary in this particular case.

Best wishes,
Mark

**Comment by M8kmyday** [comment]
The eigenvalues I am getting with rank=1 are correct, but with rank>1, the eigenvalues are incorrect.  In debugging, I saw the change in the matrix entries in the output files and continued debugging from there assuming that there was a problem.  Perhaps that was just a distraction.  Given your comment that the orderings are very likely correct, I will debug down stream in my code where the data from the multiple files are loaded into a single matrix.  Thanks for the background and tip.

**Comment by M8kmyday** [comment]
Well, that didn't take long.  File import seems fine, but I do have to manually set the boundary conditions, so that is a strong candidate for a problem.  The eigenvalues are the same for the perfect electric conductor (PEC) boundaries as for the perfect magnetic conductor (PMC) boundary, and the PMC is the natural boundary condition.  I commented out the PEC boundary condition code, and I then get the correct eigenvalue.  I need to debug what I am doing wrong in collecting the info and setting the PEC boundary, but the problem lies there.  Thanks again for the help.
