### ISSUE TITLE
Crash with memory manager and aliases (debug device)

### ISSUE THREAD

**Issue by pazner** [mfem/mfem#2997]
The following code is crashing for me with error
```
An illegal memory access was made!

MFEM abort: Error while accessing address 0x10e850000!
 ... in function: void mfem::internal::MmuError(int, siginfo_t *, void *)
 ... in file: general/mem_manager.cpp:318
```

```c++
#include "mfem.hpp"

using namespace mfem;

int main()
{
   Device device("debug");
   int n = 512;
   Vector v(n);
   v.UseDevice(true);
   v = 1.0;
   Array<int> offsets({0, n});
   BlockVector V(offsets);
   V.GetBlock(0) = v;
   V.Read();
   return 0;
}
```

Curiously, this crashes for n >= 512, but not for n < 512.

**Comment by pazner** [comment]
Note that in the above example, inserting `V.GetBlock(0).HostRead();` before `V.Print(…);` does give the correct output, but:

* I don't believe this should be semantically necessary (`Vector::Print` will call `HostRead` on the base vector, calling `HostRead` explicitly on the alias shouldn't be required).
* If instead of `V.GetBlock(0) = v;` I have `V.GetBlock(0) = 42.0;`, then the additional `HostRead` is not required — something different is happening when the right-hand side of the assignment is a `Vector`.

**Comment by camierjs** [comment]
Synchronizing the memories help in both code you provided: `V.SyncMemory(V.GetBlock(0));`.
`V` is definitely left out of sync otherwise.

**Comment by v-dobrev** [comment]
I think @camierjs is right: after you modify one, or few, or all sub-vectors in a `BlockVector`, you generally want to sync the sub-vectors to the big monolithic `BlockVector`. This is the purpose of the method `BlockVector::SyncFromBlocks()`.

**Comment by v-dobrev** [comment]
The first sentence above should've finished with: "... the big monolithic `BlockVector`, if you want to use the monolithic `BlockVector`, e.g. by calling its `Print()` method as in the code above."

**Comment by pazner** [comment]
Got it — essentially this is expected behavior, and I should be sure to call `V.SyncFromBlocks()` before using the monolithic one.
