### ISSUE TITLE
file dated before 1/1/1970 can't be built by VS 2015

### ISSUE THREAD

**Issue by TangLaoya** [mfem/mfem#30]
Dear administrator,

I found that mfem can't be built by VS 2015 for the following errors:
fatal error C1073: Internal error involving incremental compilation

I googled and found the errors:
https://connect.microsoft.com/VisualStudio/feedback/details/1576822/file-from-year-1601-causes-fatal-error-c1073-internal-error-involving-incremental-compilation

Although it is a bug of VS 2015, but if you can update the files' date it could be better.

Thanks,
Tang Laoya

**Comment by tzanio** [comment]
Hi @TangLaoya,

Thanks for the feedback. Which file has the old date that you are referring to? The files in the tarball should be dated Jan 29th, 2015.

Cheers,
Tzanio

**Comment by TangLaoya** [comment]
Dear Prof. Tzanio,

Thanks for your quick reply. I noticed that I still used the source files
from google site instead of GitHub. Just now I checked that the files
downloaded from GitHub are all dated 12/02/2015. Sorry for my careless.

Is there any bug fixed in the version from GitHub compared to the version
from google?

Thanks,
Tang Laoya

**Comment by tzanio** [comment]
Hi @TangLaoya,

Glad you got it working. The two versions should be the same, but you should definitely switch to GitHub from now on.

Cheers,
Tzanio
