### ISSUE TITLE
MFEM implementation Question

### ISSUE THREAD

**Issue by henryprescott** [mfem/mfem#3003]
Hello,

I’m looking for some potential methods for simulating how different materials deform, and don’t have any prior experience with FEA.  So I was wondering, before I do a deep dive into FEA, could someone tell me if MFEM/FEA can provide a workable solution for the following please?

In it’s simplists terms, taking 2 meshes (labelled starting point below).  Assuming a 1-1 relationship between two surfaces.

When moving the outer surface and knowing the resultant mesh, is it possible to calculate the inner surface mesh? Something like ‘A' or 'B’.

Ultimately the aim is, given the resulting outer & inner mesh and the original inner mesh, to calculate the difference between the two inner mesh versions.

<img src="https://user-images.githubusercontent.com/9204776/167846612-ae31e8c2-70e0-486e-83d6-b02f36e690e9.png" width="400">

Above is a massive simplification, in reality the geometry or surfaces we will be dealing with are more complex, a more realistic example of the sort of scenario we’re dealing with is the following:

<img src="https://user-images.githubusercontent.com/9204776/167846662-21938af4-6b59-4afb-9021-79dcd7492d07.png" width="400">

Unfortunately, it is possible for the inner surface and outer surface to have different typology, so where you might be able to use a simple spring joint system to figure out the result for the 2D example above, the 3D geometry version is a lot more complicated.

Is there an MFEM example or further reading that anyone could point me to, to find a solution for the above problem, or do I need to search for another solution other than FEA?

Any information would be much appreciated, thank you!

**Comment by vladotomov** [comment]
Hi @henryprescott,

This problem doesn't sound like a finite element thing, but more like a topology / meshing question.

When you say 1:1 between the meshes, how is this represented on discrete level? For example if the inner mesh is described with `n` discrete node positions, and other with `m`, how does the mapping structure work?

When the orange mesh is moved, do the corresponding blue nodes get exactly the same displacement vectors? Is mesh tangling a consideration here?

Best,
Vladimir

**Comment by henryprescott** [comment]
Hi @vladotomov,

Thanks for your quick response!

I guess that is part of what I am trying to figure out.

I have seen FEA simulations performed where modification to bone can simulate the resulting tissue displacement - [For Example](https://www.researchgate.net/publication/249955329_Finite-Element_Simulation_of_Soft_Tissue_Deformation/download).

This sort of thing seems quite common, but I guess what I am asking is, is it possible to work backwards?

Instead of providing something like a change to the underlying bone and simulating the resulting movement, can you provide the new surface and the displacement vectors and calculate the change in bone?

**Comment by vladotomov** [comment]
Yes, it can be done if you know the backwards relation. Or if only the forward PDE is known, one can use some inverse problem approach. I'm not in this field, but I've certainly seen FE talks that do such things.
