### ISSUE TITLE
Visualization of mfem example result or execution flow of any example

### ISSUE THREAD

**Issue by saikrishna2893** [mfem/mfem#3005]
Hi,
I would like to know if there is any possibility of viewing the solution at every step of  discretization for any sample like example1p. Want to visualize the process of discretization to finite space given the mesh.

I have referred to example22p and example25p, observed that after computation is complete, the solution is passed to glvis server through socket to visualized in form of time series. Instead of that approach, is there a way to visualize the solution or output at every step of solving the equations.

**Comment by v-dobrev** [comment]
Take a look at examples 9/9p and 10/10p -- they display (i.e. send to GLVis) the solutions in time dependent simulations right after each time step (or every n-th time step) is computed.

**Comment by saikrishna2893** [comment]
Sure, will have a look at them and will test it. Thanks for your response.
