### ISSUE TITLE
Streamlines of the thermal flux

### ISSUE THREAD

**Issue by hbadi** [mfem/mfem#3008]
Hello,

I'd like to visualize the streamlines of a given 2d thermal vector field F=(Fx,Fy) as isoline of a scalar field psi. Litterature indicates psi satisfies laplacian(psi)=curl(F)[z] since
![image](https://user-images.githubusercontent.com/1440055/168551137-a6648cec-a46f-4793-810c-0424144f0814.png)

 
First I solve the thermal problem as follow : 
![image](https://user-images.githubusercontent.com/1440055/168471678-99b80405-d0c1-4f2d-bec4-c63966957a9c.png)
with some boundary conditions 
![image](https://user-images.githubusercontent.com/1440055/168471347-92c4c859-e959-4f30-8cfc-98072dc5cecc.png)
![image](https://user-images.githubusercontent.com/1440055/168471413-ffadbe0a-8abc-4c0c-8069-44b91eb9514b.png)

Next I use the weak formulation for psi : 
![image](https://user-images.githubusercontent.com/1440055/168471216-f3b1c037-0693-4fb2-992e-09eca404141b.png)
![image](https://user-images.githubusercontent.com/1440055/168471482-3f070e8b-d04f-47f3-ba3c-e1742352b643.png)
![image](https://user-images.githubusercontent.com/1440055/168551034-31181ea7-a65d-4bc5-b6d0-80fd21026841.png)

I used a P2 interpolation for T but unfortunatly isolines of psi are not orthogonal to thoses of T.
Maybe i'm wrong somewhere in the weak formation ?

Thnaks for your help.

**Comment by v-dobrev** [comment]
It seems like you want `\nabla\psi = (F_y, -F_x)` and not `\nabla\psi = (-F_x, F_y)`.
