### ISSUE TITLE
Parallel running DGDiffusionIntegrator with a GridFunctionCoefficient

### ISSUE THREAD

**Issue by helloworldooo** [mfem/mfem#3010]
I defined a GridFunctionCoefficient, and add as a coefficient in DGDiffusionIntegrator in ex14p, replacing the original ConstantCoefficient one(1.0), then the program failed to run and there's the error "job aborted". The serial runing is OK. Is it a bug of MFEM?

    ParGridFunction De(fespace);

    GridFunctionCoefficient* De_e = new GridFunctionCoefficient(&De);

    for (int i = 0; i < De.Size(); i++)
    {
        De(i) = 1.0;
    }
    a->AddDomainIntegrator(new DiffusionIntegrator(*De_e));

    a->AddInteriorFaceIntegrator(new DGDiffusionIntegrator(*De_e, sigma, kappa));

    a->AddBdrFaceIntegrator(new DGDiffusionIntegrator(*De_e, sigma, kappa));

**Comment by vladotomov** [comment]
Hi @helloworldooo,

Since the `DGDiffusionIntegrator` needs to obtain values from MPI-neighbors at shared faces, you must call `ExchangeFaceNbrData()` for the `ParGridFunction` before the assembly is done.

Vladimir

**Comment by helloworldooo** [comment]
> Hi @helloworldooo,
> 
> Since the `DGDiffusionIntegrator` needs to obtain values from MPI-neighbors at shared faces, you must call `ExchangeFaceNbrData()` for the `ParGridFunction` before the assembly is done.
> 
> Vladimir

Cool! Thank you! By the way, similarly when I add a `VectorGridFunctionCoefficient` in `DGTraceIntegrator` in ex9p, it seems the parallel running is OK without the need to call `ExchangeFaceNbrData()` for the `ParGridFunction`?

**Comment by helloworldooo** [comment]
> I defined a GridFunctionCoefficient, and add as a coefficient in DGDiffusionIntegrator in ex14p, replacing the original ConstantCoefficient one(1.0), then the program failed to run and there's the error "job aborted". The serial runing is OK. Is it a bug of MFEM?
> 
> ```
> ParGridFunction De(fespace);
> 
> GridFunctionCoefficient* De_e = new GridFunctionCoefficient(&De);
> 
> for (int i = 0; i < De.Size(); i++)
> {
>     De(i) = 1.0;
> }
> a->AddDomainIntegrator(new DiffusionIntegrator(*De_e));
> 
> a->AddInteriorFaceIntegrator(new DGDiffusionIntegrator(*De_e, sigma, kappa));
> 
> a->AddBdrFaceIntegrator(new DGDiffusionIntegrator(*De_e, sigma, kappa));
> ```

Following this, I want to update the ParGridFunction De. Then I find it failed to update. For example, the following code cannot run successfully. In a serial version, this is OK.

    for (int i = 0; i < De.Size(); i++)
    {
        De(i) = 1.0;
    }

    De.ExchangeFaceNbrData();

    a->Assemble();

    a->Finalize();

    for (int i = 0; i < De.Size(); i++)
    {
        De(i) = 1.0e5;
    }

    De.ExchangeFaceNbrData();

    a->Assemble();

    a->Finalize();

What function do I need to call when I want to update the ParGridFunction, which at the same time updates the GridFunctionCoefficient* De_e?

**Comment by vladotomov** [comment]
You need `a->BilinearForm::operator=(0.0)` before the 2nd assembly, and also the second `a->Finalize()` is not needed. Otherwise it should work, let me know.

**Comment by vladotomov** [comment]
About your question for ex9: the `DGTraceIntegrator`'s `VectorCoefficient` is assumed to be continuous across faces, so it's evaluated only on the local side of the face. The other optional `Coefficient rho` is evaluated on both sides, so that would need communication.

**Comment by helloworldooo** [comment]
> You need `a->BilinearForm::operator=(0.0)` before the 2nd assembly, and also the second `a->Finalize()` is not needed. Otherwise it should work, let me know.

Hello! This function does not make it work. The error is
Verification failed: (j != -1) is false:
 --> Entry for column 50 is not allocated.
 ... in function: double &__cdecl mfem::SparseMatrix::SearchRow(const int)
 ... in file: C:\02_Windows\mfem-4.3\linalg\sparsemat.hpp:812

**Comment by vladotomov** [comment]
I can't say what's wrong from the above. If you give me a short reproducer, I can take a look.

In principle changing the `GridFunction` will influence the `Coefficient` automatically, no further function calls are needed.

**Comment by helloworldooo** [comment]
[ex14p.zip](https://github.com/mfem/mfem/files/8718668/ex14p.zip)


> I can't say what's wrong from the above. If you give me a short reproducer, I can take a look.
> 
> In principle changing the `GridFunction` will influence the `Coefficient` automatically, no further function calls are needed.
[ex14p.zip](https://github.com/mfem/mfem/files/8718670/ex14p.zip)
Hello, here is the file. Yes, the Coefficient automatically but if "a" does not reassemble, we could not get the right result.

**Comment by vladotomov** [comment]
This code works fine on my mac, both serial and parallel. Results with 4 tasks with `De=1` (left) an `De=1e-5` (right):

<img width="1410" alt="Screen Shot 2022-05-19 at 11 44 57 AM" src="https://user-images.githubusercontent.com/17843342/169377009-19f2e08e-55f1-4965-9be1-512e47629110.png">

**Comment by helloworldooo** [comment]
> This code works fine on my mac, both serial and parallel. I built with the current `master` and compiled your example in parallel. Results with 4 tasks with `De=1` (left) an `De=1e-5` (right):
> 
> <img alt="Screen Shot 2022-05-19 at 11 44 57 AM" width="1410" src="https://user-images.githubusercontent.com/17843342/169377009-19f2e08e-55f1-4965-9be1-512e47629110.png">

I find that the error occurs when I change finite element orders. For example, `mpirun -np 4 ex14p -m ../data/inline-quad.mesh -o 1` is not fine. Running with "beam-quad.mesh" also failed when the order is one. Why is that?

**Comment by vladotomov** [comment]
It's because you're getting some zeros in the matrix, and they are not assembled by default. Then the 2nd assembly tries to access non-existing entries in the `SparseMatrix`. Try with
```
a->Assemble(0);
a->Finalize(0);
```
to include the zeros in the first assembly.

**Comment by helloworldooo** [comment]
> It's because you're getting some zeros in the matrix, and they are not assembled by default. 

My problems are solved. Thank you very much!

**Comment by helloworldooo** [comment]
> It's because you're getting some zeros in the matrix, and they are not assembled by default. Then the 2nd assembly tries to access non-existing entries in the `SparseMatrix`. 

Hello, I may want to ask another question. In fact I may want to redefine the `Coefficient` and reassemble the matrix after `HypreParMatrix* A = a->ParallelAssemble();` is done. And I find it does not work. Is there a way to achieve that? Something like updating the `HypreParMatrix* A`?

**Comment by vladotomov** [comment]
Unfortunately not, the `HypreParMatrix` must be reconstructed if you change the coefficients.
