### ISSUE TITLE
Weak formulation of the Example 9 : DG Advection

### ISSUE THREAD

**Issue by salomole** [mfem/mfem#3011]
Hi ! 

I searched in your various publications the weak formulation of the time-dependent advection equation (Ex 9), I found the conservative form, but I woulk like to know the non-conservative form. Where can I find that ?

I don't understand very well the difference between `NonconservativeDGTraceIntegrator` and `ConservativeDGTraceIntegrator`. What does `TransposeIntegrator ` do in `NonconservativeDGTraceIntegrator` ?

Best wishes.

**Comment by pazner** [comment]
With exact integration, the two formulations are equivalent. With approximate integration (because of variable coefficients, curvature, quadrature, etc.), they are not exactly equivalent.

The `TransposeIntegrator` corresponds to an integration-by-parts.

In the variational form, the derivative can either be on the test function or trial function. If the derivative is on the test function, the method is automatically conservative. If the derivative is on the trial function, the method is automatically constant-preserving. If the quadrature is exact, both of the above properties hold.

**Comment by salomole** [comment]
> With exact integration and divergence-free velocity field, the two formulations are equivalent. With approximate integration (because of variable coefficients, curvature, quadrature, etc.), they are not exactly equivalent.
> 
> The `TransposeIntegrator` corresponds to an integration-by-parts.
> 
> In the variational form, the derivative can either be on the test function or trial function. If the derivative is on the test function, the method is automatically conservative. If the derivative is on the trial function, the method is automatically constant-preserving. If the quadrature is exact, both of the above properties hold.

Thank you for your answer ! But what is the difference between `NonconservativeDGTraceIntegrator `and `ConservativeDGTraceIntegrator` in the weak formulation ?

**Comment by pazner** [comment]
Integration by parts over each element will give rise to additional face terms, that are taken into account in each of the integrators. The specific forms represented by each of `ConservativeDGTraceIntegrator` and NonconservativeDGTraceIntegrator` are described in the comments/documentation:

https://github.com/mfem/mfem/blob/aef972353a0cd18d58d73fda666c8226fa727d17/fem/bilininteg.hpp#L2907-L2932

https://github.com/mfem/mfem/blob/aef972353a0cd18d58d73fda666c8226fa727d17/fem/bilininteg.hpp#L2992-L2993

https://github.com/mfem/mfem/blob/aef972353a0cd18d58d73fda666c8226fa727d17/fem/bilininteg.hpp#L2995-L3002

**Comment by salomole** [comment]
Yes I saw this documentation, and I don't understand, the only difference I see between the two forms is the sign of alpha

**Comment by pazner** [comment]
It looks like there may be a typo in the comment, since `NonconservativeDGTraceIntegrator` uses the transpose of `DGTraceIntegrator`, it should probably be
```
-alpha < rho_u (u.n) [v],{w} > + beta < rho_u |u.n| [v],[w] >
```

**Comment by salomole** [comment]
Hum, I don't see how to find a upwind flux with this formulation...

Normally it must remain at the end : v1(u.n) or v2(u.n)

**Comment by pazner** [comment]
`DGTraceIntegrator` will reduce exactly to the upwind flux in the case of specific values of alpha and beta. `NonconservativeDGTraceIntegrator` will have an additional face term that comes from the integration by parts.

**Comment by salomole** [comment]
Which integration by part?

- Conservative form : dv/dt + div(uv) = 0
- Non-Conservative form : dv/dt + u.gradv = 0

The weak form for conservative form is (I think) : 

 <dv/dt , w> -  <u .grad(w),v> + (0.5<(u.n)v, w> - 0.5<|u.n|v, w>) + (<(u.n) {v},[w]> + 0.5<|u.n| [v],[w]>) = 0

The weak form for non-conservative (Ex 9) would be : 

<dv/dt , w> + <u.grad(v) ,w> + (0.5<(u.n)v, w> - 0.5<|u.n|v, w>) + (-<(u.n) [v],{w}> + 0.5<|u.n| [v],[w]>) = 0   ??

**Comment by pazner** [comment]
The conservative form for the steady problem is the following (from [this paper](http://dx.doi.org/10.1142/S0218202504003866))

<img width="986" alt="image" src="https://user-images.githubusercontent.com/11493037/168866185-68c108fe-b1c6-411b-982a-5e117d9b0ac7.png">

where in the above, beta is the velocity field, u is the trial function, and v is the test function (g is the inflow condition, and f is the forcing function). There is also a reaction term gamma, you can take gamma = 0.

Under the condition <img width="177" alt="image" src="https://user-images.githubusercontent.com/11493037/168867147-99a99ca7-09d4-4de3-851f-5b70682ca0a3.png"> this is equivalent to using the upwind flux.

This is exactly the formulation that is obtained using `ConservativeConvectionIntegrator` and `ConservativeDGTraceIntegrator` with alpha = 1 (and beta = 1/2) — it should be possible to see this by matching terms with what is listed in the documentation.

The non-conservative form is obtained by integrating the first volume integral by parts over each element, which will change `-(u*velocity, grad(v))` into `(div(u*velocity), v)` and also give rise to new face terms. Under the condition that the velocity is divergence free, the volume term will be `(velocity*grad(u), v)`, which is given by the `NonconservativeConvectionIntegrator`. The appropriate face integrals will be given by `NonconservativeDGTraceIntegrator` with alpha = 1 and beta = 1/2. This can be seen using the following identity

<img width="562" alt="image" src="https://user-images.githubusercontent.com/11493037/168870536-14f13875-49eb-4f7e-8823-96483626385b.png">

**Comment by salomole** [comment]
Sorry but I don't understand very well the second part of the answer. Unfortunately, I don't have access to the cited paper...

With `NonconservativeDGTraceIntegrator ` we take alpha = -1 and not alpha = 1 no ??

I don't understant the terms in the last equation

**Comment by salomole** [comment]
Sorry but I don't understand very well the second part of the answer. Unfortunately, I don't have access to the cited paper...

With `NonconservativeDGTraceIntegrator ` we take alpha = -1 and not alpha = 1 no ??

I don't understand the terms in the last equation

**Comment by salomole** [comment]
Sorry but I don't understand very well the second part of the answer. Unfortunately, I don't have access to the cited paper...

With `NonconservativeDGTraceIntegrator ` we take alpha = -1 and not alpha = 1 no ??

I don't understant the terms in the last equation

**Comment by pazner** [comment]
> With NonconservativeDGTraceIntegrator we take alpha = -1 and not alpha = 1 no ??

You can take alpha = 1. The reason the sign is flipped in ex9 is because that term is moved to the RHS for time integration, so you pick up a minus sign on the differential operator.
