### ISSUE TITLE
PositiveFiniteElement::Project

### ISSUE THREAD

**Issue by rw-anderson** [mfem/mfem#3014]
The PositiveFiniteElement::Project method which takes a coefficient performs interpolation of the dofs:

https://github.com/mfem/mfem/blob/5308d285f732c45f3c381bcee415581fd34b1cb2/fem/fe/fe_pos.cpp#L23-L32

This gives rise to somewhat surprising behavior, at least to me. For example, if you are using an order 2 Bernstein basis in an L2 space and project a quadratic, this should be exactly representable, but you get something quite far from exact in this case.

A local L2 projection is more expensive, but I think it would at least make a good option, if not the default behavior here for discontinuous spaces. Maybe that's why the interpolation is default, because it will work for both continuous and discontinuous spaces?

**Comment by v-dobrev** [comment]
@rw-anderson, this "projection" is the monotone approximation operator and we do want to have access to this version. Currently, if one wants to recover high-order approximation and reproduce exactly functions in the discrete space, then one can perform the projection in the same space using a nodal basis and then convert to the positive basis. We can make this an option in the positive FiniteElement classes and the respective FiniteElementCollection classes -- basically an `if` statement in the `Project` method. This will avoid the need to create the separate nodal basis version of the same space just to do the accurate projection.

**Comment by rw-anderson** [comment]
Good point that the interpolation of dofs is monotone.

I put up a WIP of one way to implement this as an option in #3105. I added a default argument to ProjectCoefficient which can select the local L2 behavior. This is then propagated down to the element level projection. This seemed like one of the least intrusive ways to add the functionality without disturbing too much existing code.

If this seems like the right way to do it, it should be made consistent across Coefficient, VectorCoefficient, and maybe some other interfaces.

Also, someone should look at my implementation for how to perform the local L2 projection.

**Comment by tzanio** [comment]
Discussion continued in #3015
