### ISSUE TITLE
Getting surface normal and tangent vectors in Ex. 18 

### ISSUE THREAD

**Issue by varchasgopalaswamy** [mfem/mfem#3020]
Hi,

I'm trying to extend ex. 18 to use a more accurate Riemann solver, e.g. HLLC. In order  to do so, I need to rotate all vector-valued conserved quantities from the original coordinate system to be in the surface normal and surface tangent space, solve the Riemann problem to get the fluxes, and then rotate back. (see e.g. what Hesthaven & Warburton have in Sec. 6.6). Then, I guess to get the total flux at each DOF, I would sum over each quadrature point for each DOF. 

Two questions: 

1. In `FaceIntegrator::AssembleFaceVector`, the loop seems to be over each quadrature point for all the DOFs simultaneously. The normal vector is calculated for each quadrature point via `CalcOrtho(Tr.Jacobian(), nor)` and seems to be shared (and identical) for all the DOFs.  However, if the surface is a higher order surface, wouldn't the surface normal be different for each quadrature point of each DOF? Is the example just keeping things  simple by assuming linear surface elements? 

2. Clearly I can get the normal vector via `CalcOrtho(Tr.Jacobian(), nor)`. However, to rotate the vector valued conserved quantities, I need to also find the tangent vectors (1 in a 2D domain, 2 in a 3D domain). How do I go about finding those? 

Thanks!

**Comment by vladotomov** [comment]
Hi Varchas,

1. The output of `AssembleFaceVector` is #dof integrals. With numerical quadrature, every integral gets a contribution from each quadrature point. At a given quadrature point, the normal is the same for all integral contributions. The normal is recomputed at each quadrature point. That's what the loop does, thus the curvature is taken into account.
2. `CalcOrtho` gives a geometric vector. Can't you use that to compute tangent vectors and planes?

**Comment by varchasgopalaswamy** [comment]
> With numerical quadrature, every integral gets a contribution from each quadrature point. 
I see! That was the source of my confusion, I thought each DOF had separate quadrature points. 

> Can't you use that to compute tangent vectors and planes?
Yes, almost as soon as I posted I realized you can just use an orthonormalization procedure to pull out the 1/2 tangent plane vectors.

Thanks!
