### ISSUE TITLE
`Operator::Mult` or `Solver::Mult` with multiple RHS

### ISSUE THREAD

**Issue by sebastiangrimberg** [mfem/mfem#3021]
I'm wondering if there is any interest from others in an interface for solving linear systems with multiple right-hand sides? In particular, this seems like it would be particularly useful for the interfaces to direct solvers like MUMPS or SuperLU_DIST, etc. 

One way to do so would be to have an overloaded virtual `Mult` method in `Operator` which has a default behavior of calling `Mult` on each column of the input matrix, and alternatively can be overridden by derived `Operator` or `Solver` classes if desired. There are probably several options for how the input/output RHS vectors are provided, they could each be a `DenseMatrix`, an `Array` of `Vector` objects, or a `BlockVector` with equally sized blocks, to name a few.

This would be useful for me as I am often looping over columns to solve systems with multiple RHS and I have noticed that the forward/backward solve of MUMPS is much faster when directly calling with `id->nrhs > 1`, for example. Curious if this is of interest to other developers/users before I go ahead an open a PR.

**Comment by adam-sim-dev** [comment]
Hi @sebastiangrimberg , I think this feature is very useful.

**Comment by tzanio** [comment]
I agree that this will be useful. As a first step, I will suggest providing the RHS as `Array` of `Vector` objects.

**Comment by tzanio** [comment]
Discussion continued in #3075
