### ISSUE TITLE
appveyor queue behavior

### ISSUE THREAD

**Issue by rw-anderson** [mfem/mfem#3025]
The appveyor ci seems to not dequeue things when a superceding push happens on a PR.

Scenario: You notice a failure in one of the other ci tests, fix it, and push the fix. appveyor will continue to build/test the prior version first, even though it's now outdated, which takes something like 30-ish minutes.

I don't know if this can be fixed, but I thought I'd mention it as it seems like potentially a significant waste of ci cycles and ci turnaround time. I fixed a few bugs this way today and the appveyor build is now several pushes behind, needlessly grinding away on old, known bad revisions.

**Comment by rw-anderson** [comment]
This section from the appveyor docs may be helpful:

![rolling-builds](https://user-images.githubusercontent.com/11507994/169435342-06e35309-5e26-4892-884f-6bfb434ec262.png)

**Comment by tzanio** [comment]
Hi @rw-anderson, I added this in the Appveyor configuration. Hopefully it works as intended.

(Note that we are transitioning from Appveyor to GH Actions for Windows builds)

**Comment by rw-anderson** [comment]
Thanks!
