### ISSUE TITLE
Problem with GetValue

### ISSUE THREAD

**Issue by jchan192** [mfem/mfem#3026]
Hi MFEM community,

I am writing a 3d crank-nicolson code with MFEM on adaptive meshes. 
I have been using `GetValues` to obtain the values at the nodes,
but the resulting data are not correct. As shown below, i expect a simple gaussian wave, 
but we can see erroneous values on the right. 
![image](https://user-images.githubusercontent.com/95039916/169435497-992c3452-4353-4032-817a-f77b42c2f76b.png)

I want to figure out if there is a problem with `GetValues`, or actually a problem with the CrankNicolson method itself.
Using `L2ComputeError`, I checked the L2 error of uniform mesh (err = 0.032627106) and refined mesh ( err = 0.035812087).
The error are pretty similar, so I believe `GetValues` is the problem here, which is not obtaining the true values.

 Is it possible that the interpolation performed within `GetValues` may produce incorrect values in certain cases?
Thank you for your time.

**Comment by jandrej** [comment]
You should try to project the solution you are expecting onto a mesh and without using the time stepping method do the sampling with `GetValues`. Without information about the problem (physics) we can't judge if CN in combination with the discretization you're using is adequate.

**Comment by jchan192** [comment]
Thanks for the reply. As you suggested, here I show the initial solution without using the CN method on uniform grid.
Below is a short code of how I project the initial gaussian wave function to the `GridFunction`, obtain the values with `GetValue`, and compare with analytical.
```
   FunctionCoefficient u0_r(Init_GWP_real)
   FunctionCoefficient u0_i(Init_GWP_imag)                                                                                                                                                                                                                   
   u_gfR.ProjectCoefficient(u0_r);
   u_gfI.ProjectCoefficient(u0_i);
   
   for (int i = 0; i<NE;i++){ 
             pmesh.GetElementCenter(i,temp);                                                                                                                                                                       
                                                                                                                                                                                                                   
             // for 3d mesh                                                                                                                                                                                        
             ip.Set3(temp[0],temp[1], temp[2]);                                                                                                                                                                                                                                                                                                                                                                                               
             saverho[i]       = u_gfR.GetValue(i,ip);                                                                                                                                                              
             savephi[i]       = u_gfI.GetValue(i,ip);                                                                                                                                                              
             analytical[i]    = Init_GWP_real(temp)*Init_GWP_real(temp) +                                                                                                                                          
                                Init_GWP_imag(temp)*Init_GWP_imag(temp);   
  }
```
Here are the plots (left has 32 elements, right 64 elements). I noticed some small deviations. 
Is the small deviation expected because of the interpolation?
![image](https://user-images.githubusercontent.com/95039916/169729412-85577b24-6352-4e1f-87c7-82d645ed466d.png)

**Comment by jandrej** [comment]
To me, this looks normal behavior of GetValue.

**Comment by jchan192** [comment]
Sorry for comng back so late, but I managed to solve the issues.
If I get values at the element ceneter using `GetElementCenter`, the solutions do not look correct.
but if I get values at the vertices, the solution is more accurate to the analytical solution, without erroneous values on the right boundary (Figure at the top of this post). 

Here is the code for people who may face similar issue
```

           for (int i = 0; i < NE; i++){ /* loop over elements */
             Element *e = pmesh.GetElement(i); /* get element i */
             int *v = e->GetVertices(); /* get list of vertices */
             int nv = e->GetNVertices(); /* get number of vertices */
             Array<IntegrationPoint> ip(8); /* set integration points in local coordinates */
             ip[0].Set3(0,0,0);
             ip[1].Set3(1,0,0);
             ip[2].Set3(1,1,0);
             ip[3].Set3(0,1,0);
             ip[4].Set3(0,0,1);
             ip[5].Set3(1,0,1);
             ip[6].Set3(1,1,1);
             ip[7].Set3(0,1,1);
             for (int j = 0; j < nv; j++){ /* loop over vertices for element i */
               double *coords = pmesh.GetVertex(v[j]); /* get global coordinates of vertex j of element i */
               saverho[i] = u_gfR.GetValue(i, ip[j]);  /* get solution at vertex */
               savephi[i] = u_gfI.GetValue(i, ip[j]);  
```
