### ISSUE TITLE
Example 3, dim in fespace declaration and error with ProjectBdrConditions

### ISSUE THREAD

**Issue by jrubianom** [mfem/mfem#3046]
Dear all,

I have a few questions about the example ex3.cpp (https://github.com/mfem/mfem/blob/master/examples/ex3.cpp) .

**Issue 1)** In this code section:

```
- 121 FiniteElementCollection *fec = new ND_FECollection(order, dim);
- 122 FiniteElementSpace *fespace = new FiniteElementSpace(mesh, fec);
```

I don't understand why an error appears and the code doesn't work anymore if I replace the line 122 with :

`FiniteElementSpace *fespace = new FiniteElementSpace(mesh, fec,dim); // as in example ex2.cpp`

I get:

```
SparseMatrix::Gauss_Seidel_forw(...) #2
make: *** [Makefile:29: ex3.x] Aborted
make: *** Deleting file 'ex3.x

```

I don't know why with this modification I am getting that error.

**Issue 2)** Starting again with the originnal file of example 3,  ex3.cpp:
I deleted the braces in lines 132,136 (https://github.com/mfem/mfem/blob/master/examples/ex3.cpp) .

```
Array<int> ess_tdof_list;
Array<int> ess_bdr(mesh->bdr_attributes.Max());
ess_bdr = 1;
fespace->GetEssentialTrueDofs(ess_bdr, ess_tdof_list);
```

and I change the line 154 ( the commented one) implementing ProjectBdrCoefficient in line 155:

```
152 GridFunction x(fespace);
153 VectorFunctionCoefficient E(sdim, E_exact);
154 //x.ProjectCoefficient(E);
155 x.ProjectBdrCoefficient(E,ess_bdr);
```

When I run it I get the following results:

>    Iteration : 153  (B r, r) = 3.11718e-12
> Average reduction factor = 0.91358
> || E_h - E ||_{L^2} = 1.78018

Unlike when I run the original file:

> Iteration : 136  (B r, r) = 1.3429e-10
> Average reduction factor = 0.903118
> || E_h - E ||_{L^2} = 0.391631

Why is it not equivalent? It seems that with ProjectBdrCoefficient doesn't work because the error is high.

Thanks in advance for your help!!!!! :)

**Comment by psocratis** [comment]
Hi @jrubianom, 

Issue 1: 

Example 3 uses an ND space which is a vector-valued (not a scalar) space. The third argument in the constructor of the `FiniteElementSpace` makes sense only in the case of a scalar space (H1 or L2) when one wants to use multiple copies or them. 

Issue 2: Since this is an ND space you need to use `ProjectBdrCoefficientTangent` since the Dirichlet BC is defined as `n x E = E_0` on the boundary. 

Hope this helps. 

Best, 

Socratis

**Comment by jrubianom** [comment]
@psocratis Thank you very much. Now it is clearer.
And with `ProjectBdrCoefficientTangent`  the results are correct   :)
