### ISSUE TITLE
Finding the shared face index or boundary face index of an edge

### ISSUE THREAD

**Issue by thorvath12** [mfem/mfem#3053]
For a given edge, I can use the `Mesh::FaceInformation` to find out whether the face is shared. But is there a way to find out the shared face index? I need to use `GetSharedFaceTransformations(int sf)`, but I do not know how to find sf.

I have a very similar question for boundary faces. `Mesh::FaceInformation` can tell me that the face is a boundary face, but is there an easy way to find the boundary face index?

In the hdg branch, I have a workaround for both, but I was wondering if there is a better solution.

I would appreciate any help.

Best,
Tamas

**Comment by YohannDudouit** [comment]
I believe only the mapping from "shared index"/"boundary index" to "local index" currently exists: https://github.com/mfem/mfem/blob/master/mesh/pmesh.hpp#L432-L433
https://github.com/mfem/mfem/blob/master/mesh/mesh.hpp#L1253-L1254

We were discussing adding such functions with @acfisher : https://github.com/mfem/mfem/pull/2951#discussion_r860130457

**Comment by thorvath12** [comment]
Thank you, @YohannDudouit. I close this for now, and keep an eye on https://github.com/mfem/mfem/pull/2951
