### ISSUE TITLE
Interpolation operator to a discrete set of points

### ISSUE THREAD

**Issue by thartland** [mfem/mfem#3058]
@cnpetra and I are working on a project, involving solving PDE and bound constrained optimization problems and are hoping to develop an `MFEM` implementation. 

I have a brief mathematical description of one of our computational needs [here](https://github.com/mfem/mfem/files/8836600/MFEM_question.pdf).

We are seeking an interpolation operator $B$ that maps a vector representation of a finite element function $u$ to the function values at a collection of points $u(x_{1}), u(x_{2}),\dots, u(x_{m})$. A routine for computing the action of $B$ on a vector is described in [MFEM field-interp](https://github.com/mfem/mfem/blob/master/miniapps/gslib/field-interp.cpp) and in parallel [MFEM pfindpts](https://github.com/mfem/mfem/blob/master/miniapps/gslib/pfindpts.cpp).

Are lines 292-344 of [MFEM field-interp](https://github.com/mfem/mfem/blob/master/miniapps/gslib/field-interp.cpp), showing a means to apply $B^{\top}$ to vectors? Is there anything that would prevent this from being successfully used in an parallel setting with `MPI`?

**Comment by kmittal2** [comment]
Hi @thartland, 

Yes, lines 292-344 of the MFEM field-interp miniapp show a means to apply the $B^T$ operator, and I can't think of anything that would stop it from being used in a parallel setting. Is there something in particular that you are concerned about?

Ketan

**Comment by kmittal2** [comment]
Had some discussions with @thartland. Since we don't support the capability of interpolating nodal values **from** a random set of points, @thartland will try the approach of defining a `Mesh` using the set of points along with a gridfunction based on the values at those points. We should then be able to map this gridfunction to any desired mesh using the approach in `field-interp` miniapp.

**Comment by thartland** [comment]
Thanks again for the helpful discussions.
