### ISSUE TITLE
Parallel mixed matrices give errors due to bug(?) in Hypre

### ISSUE THREAD

**Issue by IdoAkkerman** [mfem/mfem#307]
When solving mixed problems where different spaces have the same global DOF count Hypre assumes the matrix is square (which it is...) but apparently assumes a bit more (regarding fill-in patterns?) leading to errors when running in parallel.

This can be fixed by a slight mod in Hypre namely in
src/parsrc_ls/par_rap.c 
after line 395 
square = 0;

This way hypre does not assume the matrix is "square" which should fix this.

I think this is a bug in Hypre, but it might also improper use of the hypre_BoomerAMGBuildCoarseOperator routine.

**Comment by tzanio** [comment]
This is being discussed in the hypre issue tracker: https://github.com/LLNL/hypre/issues/18

**Comment by tzanio** [comment]
Hi @IdoAkkerman and @ulrikeyang, is there a verdict on this issue?

Should we ensure a presence of diagonal element for square matrices in MFEM, is this an issue in _hypre_, or is it something else? Will having a simple reproducer help?

Thanks,
Tzanio

**Comment by IdoAkkerman** [comment]
I think it is a small over simplification in hypre. It checks whether the matrix is square and then falsely assumes there will be diagonal entries. The opposite is true though, if the matrix is non-square the notion of a "diagonal" is meaning less, therefore no diagonal. 

I encountered this when solving a mixed problem where the dof count of the different spaces where coincidentally equal.

I don't know if they accepted my patch though...

**Comment by tzanio** [comment]
Ok, thanks for the clarification. This is something that should be addressed in _hypre_. I'll take it offline with the team, so I'm closing this issue.
