### ISSUE TITLE
issue with Convection MixedBilinearForm

### ISSUE THREAD

**Issue by thartland** [mfem/mfem#3079]
Is it expected that one cannot add a `ConvectionIntegrator` to a `ParMixedBilinearForm`?

Is it expected that one cannot use `NONE` or `PARTIAL` assembly levels for a `ParBilinearForm` with a `ConvectionIntegrator`?

-- A more mathematically complete problem description --  ![Problem Description](https://user-images.githubusercontent.com/22107593/174403586-68eda63e-6b46-4502-8219-41a914769798.png)

-- [A parallel MFEM application code ](https://github.com/mfem/mfem/files/8931441/convectionFormIssue.txt) in which one can
1. build a `ConvectionIntegrator` in a `ParBilinearForm` with the default assembly level with command line argument `-opt 0` 
2. attempt to build a `ConvectionIntegrator`  in a `ParBilinearForm`  with `PARTIAL`  assembly level, with command line argument `-opt 1`
3. attempt to build a `ConvectionIntegrator` in a `ParBilinearForm`  with `NONE` assembly level, with command line argument `-opt 2`
4. attempt to build a `ConvectionIntegrator` in a `ParMixedBilinearForm` with default assembly level, with command line argument `-opt 3`

A last detail -- I have modified the `type` to `quad` in `inline-tri.mesh` as I understand that `MFEM` does not support `PARTIAL` assembly with element types such as `tri`.  
@cnpetra

**Comment by YohannDudouit** [comment]
I added support for mixed bilinear forms through libCEED, I think this would be the most straightforward if using libCEED is an option. It would need to be "activated" for the integrators of interest though.

**Comment by YohannDudouit** [comment]
@thartland You also have support for triangles and tetrahedron through libCEED.

**Comment by thartland** [comment]
Ok, looks like I should work on ensuring libCEED integration through MFEM. Thanks so much for the help!
