### ISSUE TITLE
How to compute H1 error?

### ISSUE THREAD

**Issue by MollyRaver** [mfem/mfem#308]
I am still in learning how to use mfem. I have the following two questions.

1. I looked all the examples and try to follow the simplest example (ex1.cpp) to simulate Poisson equation. I have one question for ex1 and I am wondering to know how to calculate the H1error by x.ComputeH1Error. In the "gridfunc.hpp", I found the usage should be as follows:

ComputeH1Error (Coefficient *exsol, VectorCoefficient *exgrad, Coefficient *ell_coef, double Nu, int norm_type)

But do you have examples to show that how to define exsol, exgrad, ell_coef? I can understand that "exsol" should be the analytical solution, "exgrad" denotes the gradient of analytical solution. However, from the words I cannot guess "ell_coef". Also, could you provide a sample of how to use "ComputeH1Error"?

2. For ex3, I try edge element on the tet and hex mesh for beam (beam-tet.mesh and beam-hex.mesh) and try to explore the numerical performance accordingly. I found the results show that for edge element with order 1, tet element only has convergence rate O(h), but hex element converges at order O(h^2). Why the convergence rate is different for tet mesh and hex mesh? 

Thank you very much for providing this useful tool and it is really helpful in my research. I am looking forward to the reply for my questions. Thanks again.

**Comment by tzanio** [comment]
Hi @MollyRaver,

There is an example of H1 error computation here:

- https://github.com/mfem/mfem/blob/atpesc-dev/examples/atpesc/mfem/convergence.cpp

See also the corresponding [ATPESC](https://extremecomputingtraining.anl.gov/) lesson developed by @jamiebramwell: 

- https://xsdk-project.github.io/HandsOnLessons/lessons/mfem_convergence/lesson.html\

Regarding your second question, there may be some super-convergence for hexes (in this case the elements are cubes), though I'm not sure if that's the case here. Easiest way to check will be to run on unstructured mesh, e.g. the higher-order Fischera meshes.

Hope this helps,
Tzanio

**Comment by MollyRaver** [comment]
@tzanio Thank you for your reply. 

1. I have tested the example for H1 error computation and it works very well! But I still do not understand about the parameter ell_coef. Is this coefficient we have to assign as "element local coefficient" in the energy norm? as \int_T \kappa_T\nabla e_h\cdot\nabla e_h dT where \kappa_T is the diffusion coefficient? (-\nabla\cdot \kappa \nabla u=f)??

2. I checked about the unstructured mesh "Fischera meshes" and the hex mesh has the same convergence rate for linear element. Because we are checking the L2 error, and I believe O(h^2) should be the correct order (not superconvergence). But the tex mesh has different performance. I will do more numerical test and then come back to update more results.

Thanks again for kindly help!

**Comment by tzanio** [comment]
@MollyRaver, were you able to make any progress on this?

The parameter you are asking about is for weighted H1 norm, you probably one to set it to a constant coefficient of 1.0.

**Comment by MollyRaver** [comment]
Thank you very much!

**Comment by raphaelzanella** [comment]
Using `x.ComputeH1Error(&ue, &gradue, &one, 1.0, 1)`,  where `x` is the solution, `ue` is the exact solution and `gradue` is the exact solution gradient, computes the H1 semi-norm in my case.
I couple the result with `x.ComputeL2Error(ue)` to obtain the full norm.
I tried to use `x.ComputeH1Error(&ue, &gradue, irs)`, where `irs` is pointer on an integration rule, but I have different results depending on the number of MPI processes.

**Comment by psocratis** [comment]
Hi @raphaelzanella , 

Can you provide more details on the problem you are running?  If I understand correctly the `x.ComputeH1Error(&ue, &gradue, &one, 1.0, 1)` interface coupled with the L2 computation is consistent when varying the number of processors but 
`x.ComputeH1Error(&ue, &gradue, irs)` is not? 

Thanks, 

Socratis

**Comment by raphaelzanella** [comment]
Hi,
Yes exactly.
I am solving a Laplacian equation -Delta u = f with homogeneous Dirichlet conditions. The code is based on example 1.
I can share the error computation part if needed.

**Comment by psocratis** [comment]
@raphaelzanella , yes please if you can share the whole file that would be best. In the meantime, you can also take a look at 
`tests/convergence/prates.cpp` which also includes error computation for the Laplace problem. I just tried that and I don't any inconsistencies when changing the number of processors.  

Thanks, 

Socratis

**Comment by raphaelzanella** [comment]
This code for instance.
[test_ComputeH1Error_nb_procs.tar.gz](https://github.com/mfem/mfem/files/5955432/test_ComputeH1Error_nb_procs.tar.gz)

**Comment by psocratis** [comment]
Hi @raphaelzanella , 

Thanks for reporting this. There was indeed a bug. Please see https://github.com/mfem/mfem/pull/2046 for the fix. 

Best, 

Socratis

**Comment by raphaelzanella** [comment]
Ok it works now thanks'
