### ISSUE TITLE
Debug of Mumps solver: Segmentation fault: address not mapped to object at address 

### ISSUE THREAD

**Issue by liuzg-23** [mfem/mfem#3093]
Hello,
I solved the real system of linear equations using mumps solver on a computer clusters. When I solved a small-scale (1000,000 unknowns), it worked. However, when I solved a large-scale (9000,000 unknowns), the code reported an error:

@.....
Calling MUMPS direct solver
Step 3: Solving primal problem...
[cdr2459:238884:0:238884] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x11cc8e00c)
[cdr2344:54672:0:54672] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x11dbe5c6c)
[cdr2404:39251:0:39251] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x11e56fc4c)
......
==== backtrace (tid: 54674) ====
0 0x000000000001f093 ucs_debug_print_backtrace() /tmp/ebuser/avx2/UCX/1.9.0/GCCcore-10.2.0/ucx-1.9.0/src/ucs/debug/debug.c:656
1 0x00000000000130f0 funlockfile() :0
2 0x00000000011fd34f dmumps_init_root_ana() ???:0
3 0x00000000012868ba dmumps_ana_driver() ???:0
4 0x00000000011ef6ee dmumps_() ???:0
5 0x0000000001125eb6 dmumps_f77_() ???:0
6 0x0000000001123aef dmumps_c() ???:0
7 0x00000000004b03ec mfem::MUMPSSolver::SetOperator() ???:0
8 0x000000000042c039 GOAFEM::solve() ???:0
9 0x0000000000419419 main() ???:0
10 0x0000000000023e1b __libc_start_main() /cvmfs/soft.computecanada.ca/gentoo/2020/usr/src/debug/sys-libs/glibc-2.30-r8/glibc-2.30/csu/../csu/libc-start.c:308
11 0x0000000000411c6a _start() ???:0
...

Can you help me solve these problems? Thanks very much.

Best wishes,
Zhengguang.

**Comment by v-dobrev** [comment]
Hi @liuzg-23,

Sorry for the late reply.

I suspect a 32-bit integer overflow may be the issue. Is MUMPS build with 32-bit or 64-bit integers? I'm not sure if there is such an option actually and if there is, if our MUMPS wrapper class supports the 64-bit version. I think @psocratis will know best.

**Comment by psocratis** [comment]
Hi @liuzg-23, 

MUMPS uses a default "Percentage increase of estimated workspace (default = 20%)". I've seen similar issues in the past which were resolved by increasing this percentage. Please see https://github.com/mfem/mfem/blob/641078645f6eb2762ce7d9b05050a247e74aafb2/linalg/mumps.cpp#L294-L295

That is, if you don't need 64-bit integers. Can you print how many non-zero entries your matrix has? If you do need 64-bit integers then we might need to modify the interface a bit and make sure you compile MUMPS with 64-bit integer support as well. 

Best, 

Socratis

**Comment by adam-sim-dev** [comment]
FYI, MUMPS-5.2.1 works. @psocratis

**Comment by adam-sim-dev** [comment]
FYI, mumps-5.2.1 works. The possible bugs may be in the MFEM_MUMPS_VERSION >= 530 code part. @psocratis

**Comment by psocratis** [comment]
Thanks @adam-sim-dev, I'll investigate and report back soon.

**Comment by psocratis** [comment]
@adam-sim-dev , can you give me the stack trace from ex25p? Thanks

**Comment by adam-sim-dev** [comment]
Yes, but just give me some time

**Comment by adam-sim-dev** [comment]
I cannot reproduce the problem on a small workstation using Intel and GCC compilers. I have some difficulty obtaining the stack trace on that cluster because I am not so familiar with GDB or other tools...

**Comment by adam-sim-dev** [comment]
mumps.cpp Line 213

213	   id->job = 3;
(gdb) 
214	   dmumps_c(id);
(gdb) 

Thread 1 "ex25p" received signal SIGSEGV, Segmentation fault.
__memcpy_generic () at ../sysdeps/aarch64/multiarch/../memcpy.S:198
198	../sysdeps/aarch64/multiarch/../memcpy.S: No such file or directory.

**Comment by tzanio** [comment]
ping: @psocratis

**Comment by v-dobrev** [comment]
I tried the following runs with MFEM's `master` branch (42e979eb) and MUMPS 5.5.1:
```
mpirun -np 4 ex25p -o 2 -f 1.0 -rs 1 -rp 1 -prob 0 -mumps
mpirun -np 4 ex25p -o 3 -f 10.0 -rs 1 -rp 1 -prob 1 -mumps
mpirun -np 4 ex25p -o 3 -f 5.0 -rs 3 -rp 1 -prob 2 -mumps
mpirun -np 4 ex25p -o 2 -f 1.0 -rs 1 -rp 1 -prob 3 -mumps
```
and all of them worked fine. This was on an Intel-based MacBook.

What is the command line that fails for you?

**Comment by adam-sim-dev** [comment]
I forget the specific command lines. I also can not reproduce the problem on my shared-memory workstation but on a distributed-memory cluster.

**Comment by v-dobrev** [comment]
Without a way to reproduce the issue, I'm not sure how to debug it.

One thing I can suggest is running with `valgrind`, or building and running with ASan, e.g. by adding the flags`-fsanitize=address -fno-omit-frame-pointer -g` when building MUMPS and MFEM.

> I also can not reproduce the problem on my shared-memory workstation but on a distributed-memory cluster.

This makes it sound like the issue is with the MPI library, not with MUMPS or MFEM.
