### ISSUE TITLE
DOF ordering for MFEM v1.x mesh files

### ISSUE THREAD

**Issue by sethwatts** [mfem/mfem#3094]
I am trying to write MFEM v1.x mesh files for second order tetrahedral meshes, for meshes that may or may not be periodic. Per the discussion at [mfem.org](https://mfem.org/mesh-format-v1.x/), I understand that the node coordinates for both cases are defined by providing a GridFunction definition once the mesh topology is defined. For the non-periodic case, I can define conforming node locations using a GridFunction defined on an H1_3D_P2 FiniteElementSpace. For the periodic case, I use an L2_T1_3D_P2 FiniteElementSpace. 

I am able to successfully define first-order (_P1) periodic and non-periodic tetrahedral meshes. The issue comes when defining the order of DOFs in high-order elements to write the GridFunction  - order in the sense of node numbering, rather than in sense of vector components set as byVDIM / byNODES. This isn't an issue in the first-order case since the DOFs follow the vertex ordering in both the H1 and L2 spaces. 

In the second-order case, the documentation on DOF numbering at mfem.org linked above appears to be incorrect. It states that DOFs are numbered first by vertex number, then by edge number, then by face number, and then by element number, where for edges and faces the numbering is performed by

> loop over edges and faces inside each element (clock-wise)
> number currently the edges and faces that have not been numbered yet

After some experimentation, this appears to be incorrect; instead, the numbering within each element proceeds in lexicographic order, i.e. for tetrahedron with vertices (i, j, k, l) the edges appear to be numbered as (ij, ik, il, jk, jl, kl), which is consistent with the edge definitions in geom.cpp: `Constants<Geometry::TETRAHEDRON>::Edges[6][2] = {{0, 1}, {0, 2}, {0, 3}, {1, 2}, {1, 3}, {2, 3}};`

I had naively assumed that the DOFs within an element would be numbered consistently for an L2 space, but this is not the case. If I am not mistaken, the DOF numbering for tets is instead defined in the constructor for the `L2_FECollection` in fe_coll.cpp. I am basing this assumption on the fact that ints `i`, `j`, `k`, and `l` loop from `0` through the element order `p` (inclusive) . However, I don't understand how these loops relate to expected DOF ordering within the element, if indeed that is what they are defining; based on a proximate comment in the code, this may be defining tetrahedral orientation instead (although the two are closely related). This leads me to my request:

**For tetrahedron (i, j, k, l), how are the ten DOFs arranged for a second order L2 FiniteElementSpace?**

I would also like to suggest that the Mesh v1.x documentation for curvilinear meshes be updated for both the H1 and L2 cases so that users can appropriately define higher-order meshes in this format.

**Comment by sethwatts** [comment]
Working through the dof ordering logic for different permutations of the tet vertices as contained in the `L2_FECollection` constructor, I was able to deduce that for a second order tetrahedron (i, j, k, l) are ordered (i, ij, j, ik, jk, k, il, jl, kl, l), which satisfies my immediate need. I believe it would be worth documenting this on the mfem.org webpage and/or the L2_FECollection header.

**Comment by sethwatts** [comment]
As an exercise, I worked through the permutation logic for a cubic tetrahedron. If I've done everything correctly, the ordering of the dofs within an element is (i, ij1, ij2, j, ik1, ijk, jk1, ik2, jk2, k, il1, 1jl, jl1, ikl, jkl, kl1, il2, jl2, kl2, l) where single indices are the dofs associated with vertices, double indices are dofs associated with edges and the numeral is the number of the dof on that edge (presumably following the edge orientation convention) and triple indices are the dofs associated with triangular faces.

**Comment by v-dobrev** [comment]
The ordering of the dofs in the L2 tetrahedron finite element is essentially a Cartesian ordering. When using (closed) uniform nodes, the `(i, j, k)` dof in the loop https://github.com/mfem/mfem/blob/fc1a8776bab319d28f1fcac295082521c2a5ddfe/fem/fe/fe_l2.cpp#L716-L722

will have coordinates `(i/p, j/p, k/p)`. You can think of the bounds for `(i, j, k)` as derived from the respective bounds for `(x, y, z)` defining the reference tetrahedron: `0 <= z <= 1`, `0 <= y <= 1-z`, `0 <= x <= 1-y-z`.

When the nodes are not uniform, we simply apply a stretching to make the locations rotationally invariant.

Regarding the incorrect documentation at https://mfem.org/mesh-format-v1.x, I'll start a PR with some edits and I'll ping you to take a look and make additional changes if you want. Thanks for pointing out these issues.

**Comment by v-dobrev** [comment]
Note: the local node ordering for the H1 tetrahedral element is different from the L2 tetrahedral element.

When enumerating dofs globally for an H1 space, the local ordering of the dofs is not that important. What's important is the ordering of the dofs within the interior of each edge (excluding vertices), face (excluding vertices and edges) and volume/element (excluding vertices, edges, and faces). All these use lexicographic/Cartesian-like ordering with respect to the global orientation of the mesh entity (edge/face/volume).

The same logic is applied to the L2 spaces with the understanding that in that case the dofs are associated only with the volume elements (in a 3D mesh) -- simply there no dofs associated with vertices, edges, or faces.

**Comment by sethwatts** [comment]
@v-dobrev, thank you for the explanation. I will take a look at the PR updating the web documentation. I believe this resolves my issue, so I will mark it closed.
