### ISSUE TITLE
mfem with subdomain meshes

### ISSUE THREAD

**Issue by dserino** [mfem/mfem#3095]
Hello,

I'm a new user of mfem. I'm looking to see if there is any advice on how to best set up my problem in mfem.

I'm looking to solve the Grad-Shafranov equation, corresponding to the following nonlinear equation for \psi
![problem](https://user-images.githubusercontent.com/14815476/176532127-b84940f7-1da7-431a-b4be-efe263e8482f.PNG)
The problem is nonlinear due to the second term. Both the plasma domain, \Omega_p, and the nonlinear function f depend on \psi. Furthermore, the plasma domain must be contained by limiter geometry (corresponding to the orange domain below).

![geom](https://user-images.githubusercontent.com/14815476/176535813-82da3993-a87d-4ce0-8753-4ddd529dbff4.PNG)

Additionally this problem has source terms on the RHS that only arise in the coil geometry (corresponding to green/blue/yellow rectangular domains above).

I'm applying Newton's method and this results in a set of linear equations to be solved for each Newton iteration. My main question concerns the geometry. My current idea is to create 'separate' meshes for the coil and limiter domains and give attributes to the elements within that help associate them with their respective domains. Here's a gmsh file and corresponding msh file that I created.

[gs_mesh_geo.txt](https://github.com/mfem/mfem/files/9013671/gs_mesh_geo.txt)
[gs_mesh_msh.txt](https://github.com/mfem/mfem/files/9013672/gs_mesh_msh.txt)

Am I on the right path? Or do you suggest an alternative approach. Any advice would be greatly appreciated.

**Comment by tangqi** [comment]
@jandrej @pazner @tzanio Could you please help Dan, who is a new member of TDS? Thanks a lot!

**Comment by jandrej** [comment]
This is the right approach. You will soon have the option to create function spaces on those subdomains with https://github.com/mfem/mfem/pull/2920.

**Comment by dserino** [comment]
Thank you! Good to know I can use SubMesh in the future. For now I'm using PWConstCoefficient for the coils (as demonstrated in example 2) and it seems to be working fine.
