### ISSUE TITLE
Support higher order derivatives

### ISSUE THREAD

**Issue by miaodi** [mfem/mfem#3099]
Hi,

I would like to use mfem to solve biharmonic equation (4th order problem) by the dG method. 

However, in the DG formulation there is a term [(Page 53, equation 4.30)](https://web.nims.edu.gh/sites/default/files/Dissertations/Discontinuous%20Galerkin%20Isogeometric%20Analysis%20For%20The%20Biharmonic%20Problem.pdf) $\int_{\partial \Omega}  \\{\mathbf{n}\cdot\nabla\Delta u \\} \left[ v  \right] d\partial \Omega$ that requires the third order derivatives of $u$. I investigated the code, it seems 2nd order derivative (CalcHessian) is the highest order I can obtain.

Is there any possibilities to add higher order derivatives to mfem?

**Comment by cdelv** [comment]
Hi @miaodi 
What you could do is define a new variable and split your 4rth order equation into 2 second-order equations as described here https://mfem.org/fem_weak_form/ in the section Other Types of Terms.

Hope this helps.
