### ISSUE TITLE
Bug in Lagrange1DFiniteElement::CalcShape()

### ISSUE THREAD

**Issue by kennyweiss** [mfem/mfem#310]
There appears to be a bug in ``Lagrange1DFiniteElement::CalcShape()`` (and also ``Lagrange1DFiniteElement::CalcDShape()``) when given an isoparametric coordinate outside the unit interval.

The problem appears to be with the ``k`` variable in  ``Lagrange1DFiniteElement::CalcShape()``  which is used to index into vectors with ``m+1`` elements, where ``m`` is the order.  Specifically:
```cpp
   k = (int) floor ( m * x + 0.5 );  // m is the order, x is the isoparametric coord
   ...
   w = wk * ( rxxk(k) = x - (double)(k) / m );  // problem: accessing the k^th element of rxxk
```
``k`` can be an arbitrary value, but it is later used to index into an array with ``m+1`` elements.

A simple fix which clamps the value of ``k`` to be in the range of ``[0,m]`` appears to resolve this issue.
```cpp
   k = (int) floor ( m * x + 0.5 );
   k = k > m ? m : k < 0? 0 : k; // clamp k to [0,m]   // <-- one line fix here
```

### Details

The bug appeared when I called ``IsoparametricTransformation::Transform()`` with out-of-range isoparametric coordinates on a hexahedral element with ``"Quadratic"`` nodes.  This uses ``LagrangeHexFiniteElement``, and its ``CalcShape()`` function is implemented in terms of ``Lagrange1DFiniteElement::CalcShape()``.

If I switch the nodal finite element collection to ``"H1_D*_P2"``, which uses a different ``CalcShape()`` implementation, the code works as expected with out-of-range isoparametric coordinates.  

The code also worked properly with out-of-range isoparametric coordinates on a 2D ``"Quadratic"`` quadrilateral element, where the underlying finite element class  is ``BiQuad2DFiniteElement``, and whose ``CalcShape()`` has its own implementation.

**Comment by tzanio** [comment]
Addressed in #311.
