### ISSUE TITLE
Discretization of 2D (bounded) x 2D (unbounded) 

### ISSUE THREAD

**Issue by JonasBeddrich** [mfem/mfem#3100]
Hello everyone, 

I'm working on a numerical scheme applicable to domains of the shape $\Omega \times R^2$. My current plan is to discretize the unbounded part using Hermite polynomials as part of the offline processing and then to solve the resulting $N^2$ equations in 2D. Since this is essentially different to what I've been doing with MFEM so far, it would be great if someone could point me in the right direction or provide me with some hints. 

- What would be the best way to handle such a large number of equations? 
- Is there a smarter way to discretize the unbounded dimension in MFEM than offline precalculation? 
- Are there code examples regarding such problems e.g. the Fokker-Plank equation? 

Best wishes, 
Jonas

**Comment by tzanio** [comment]
Hi @JonasBeddrich,

I am not aware of any other such applications but your plan sounds reasonable to me. 

Maybe other MFEM users have experience with similar problems and can chime in?

Tzanio

**Comment by JonasBeddrich** [comment]
Hi @tzanio, 

One application would be the Fokker Plank equation. Let  $\Omega \subset \mathbb{R}^d$, $\psi:[0,T] \times \Omega \times \mathbb{R}^d \rightarrow \mathbb{R}, \psi = \psi(t,\mathbf{x}, \mathbf{R})$. Then the equation reads as: 
$$\partial_t \psi + \mathbf{u} \cdot \nabla_x \psi -\epsilon \Delta_x \psi = -\nabla_R \cdot (\nabla_x \mathbf{u} \cdot \mathbf{R} \psi + \xi \mathbf{R} \psi) + \chi \Delta_R \psi$$
Here, solving for $\psi$ with $d=2$, I end up with a 4D equation. 

Best wishes, Jonas

**Comment by tzanio** [comment]
Unfortunately there hasn't been activity on this for several months, so I will close it, but please feel free to reopen if you have additional information.
