### ISSUE TITLE
Finding extremal values of a solution on a mesh

### ISSUE THREAD

**Issue by dserino** [mfem/mfem#3101]
Hello,

I was wondering if anyone had any tips for finding a maximal point in the solution on a mesh in mfem. Apart from a brute force approach, are there any current capabilities/examples of using something like Newton, gradient ascent, or similar?

**Comment by dserino** [comment]
@tzanio, @jandrej: was wondering if I can please get your help. 

I'm currently using a linear finite element space on triangles. This probably rules out a Newton-type search. However, I can probably devise some gradient ascent-like scheme if I had access to the values on neighboring vertices. I'm still looking at what's currently available in GridFunction, but I'm still early on the mfem learning curve and you might be able to point me in the right direction quicker.

**Comment by tzanio** [comment]
Maybe I am missing something, but for linear elements you can just take the min/max of the degrees of freedom...

**Comment by dserino** [comment]
Here's some more details on my problem. I'm trying to locate a max point (red x on blue region below) and the saddle point closest to it that both lie inside some region of the mesh (marked by an attribute value).
![image](https://user-images.githubusercontent.com/14815476/178289640-45d0297b-b637-4df6-be9f-b5f55b3f7317.png)

I am tracking the solution and these extremum points as part of an iteration to solve a nonlinear problem. I'm not sure how well behaved the solution will be over successive iterations (there may be multiple local maximums or the maximum might lie on the boundary of the mesh).

My first pass at this will probably be your suggestion - taking the min/max of the degrees of freedom within the region of interest. However, for the saddle point I need a slightly different approach. I found one paper that defines saddle points for piecewise linear functions in the following way:

![image](https://user-images.githubusercontent.com/14815476/178293699-6fc10505-1e16-41c5-8ff1-b3f54fe71a10.png)
![image](https://user-images.githubusercontent.com/14815476/178293762-9e4bfeec-4734-4053-9090-3f79a7b2ec90.png)

For this, I was thinking of using `GetVertexToElementTable()` to find neighboring vertices and check for sign changes of discrete gradients. Does this sound like a reasonable approach?
