### ISSUE TITLE
Incorrect solution for linear vectorvalued ODEs using VectorMassIntegrator 

### ISSUE THREAD

**Issue by JonasBeddrich** [mfem/mfem#3111]
Dear all, 

I get incorrect solutions solving vectorvalued ODEs as soon as the vector is longer than the mesh dimension. 

One of my projects includes solving $\partial_t \phi = A \phi$, where $\phi:\mathbb{R}^d \rightarrow \mathbb{R}^n$ with $d = 2,3$ and $n \approx 400$. So basically just some linear vectorvalued ODE. It works perfectly fine for $d \leq n$. For $n>d$ the solutions looked odd to me. 

I solved the problem using the VectorMassIntegrator on both sides and solving the time derivative as in example 9. The problem persist for different solvers, preconditioners, finite elements etc. 

Is it simply the wrong approach to use VectorMassIntegrators ? What would be the correct approach to solve the linear ODE ? 

I created a minimal example (attached) solving $\partial_t \phi = \phi$ over the time of 1 second. For $d=2$ and $n=3$ it already creates non-sense. Surprisingly the first $d$ components get solved correctly. 

Best wishes, 

Jonas
[minimal_example.txt](https://github.com/mfem/mfem/files/9147780/minimal_example.txt)
[l-shape.txt](https://github.com/mfem/mfem/files/9147807/l-shape.txt)

**Comment by jandrej** [comment]
`VectorFunctionCoefficient` and `VectorMassIntegrators` are spatial operations. Given that `l-shape.mesh` is a 2D mesh, of course `n=3` doesn't make sense. See [documentation](https://mfem.org/bilininteg/).

**Comment by JonasBeddrich** [comment]
Thank you jandrej for your fast answer. 

Do you know whether a generalization for $n>d$ exist? If not, I assume one would solve the problem using block operators? 

Is there use case why the VectorMassIntegrator allows this configuration or could one implement an assertion to avoid such confusions? Other inexperienced users might make the same mistake as me and give VectorFieldOperators a shot for vectors $n>d$. I mean, the solution would be quite elegant, if it would work.

**Comment by jandrej** [comment]
> Thank you jandrej for your fast answer.
> 
> Do you know whether a generalization for n>d exist? If not, I assume one would solve the problem using block operators?


> 
> Is there use case why the VectorMassIntegrator allows this configuration or could one implement an assertion to avoid such confusions? Other inexperienced users might make the same mistake as me and give VectorFieldOperators a shot for vectors n>d. I mean, the solution would be quite elegant, if it would work.

**Comment by JonasBeddrich** [comment]
In the following, $\phi_i:\mathbb{R^2}\rightarrow \mathbb{R}, i \in \{1,...,N^2\}$ and let's assume that $\mathbf{u}$ is known. For my problem one has to solve for $\phi_i$ alternating between problem 1 and problem 2: 
1. Solve for all $i$: $\partial_t \phi_i = \sum_{j} \alpha_{ij} \phi_j$  
2. Solve for all $i$: $\partial_t \phi_i = \nabla \phi_i \cdot \mathbf{u} + \epsilon \Delta \phi_i $

Now, I'm looking for the best way to implement this. Basically, (1.) are just $N^2$ linear ODEs (that's why I was interested in these long vectors). 

The 2 step formulation is derived from a space splitting approach following Chauviere and Lozinski (2004) or Knezevic and Süli (2009).

**Comment by JonasBeddrich** [comment]
I solved problem 1. using large blockvectors and blockoperators. The creation of the blockoperator is a bit tedious but straight forward. 
I used example 5 for the creation of the blockvector and blockoperator, and examples 10 and 16 for the rest.
