### ISSUE TITLE
How to impose Dirichlet boundary conditions for saddle point problem

### ISSUE THREAD

**Issue by huidong80** [mfem/mfem#3114]
Hi, for a saddle point structure, 

D = [ M  B^T ]
       [ B   -C   ]

I would like to impose Dirichlet boundary conditions for block M and -C.  
To impose symmetric of D,  B and B^T need to be modified by setting zeros in 
rows and columns of B and B^T.  

Are there routines in MFEM provided for such operations in the parallel version. 

Thanks

**Comment by tzanio** [comment]
Hi @huidong80,

Assuming `M`, `B` and `-C` are `HypreParMatrix` objects, you want to call `EliminateRowsCols` on `M` and `C` and `EliminateRows` for `B`.

Hope this helps,
Tzanio

**Comment by huidong80** [comment]
Thanks a lot, Tzanio,  this helps me a lot.  

Huidong

**Comment by pazner** [comment]
Just to add on to what Tzanio already mentioned, if the matrices come from something like a `ParMixedBilinearForm` object, then `FormRectangularSystemMatrix` takes as an input the indices that you need to eliminate, so you don't need to modify the matrix yourself.

**Comment by huidong80** [comment]
Hi,  thanks a lot.  Actually,  this was my first attempt.  Unfortunately, it fails to run in parallel.  For this,  I add the -pa (partial assembling) in the command line, but, it seems to me I  got memory leak issues.   I will try to give more descriptions on the exact problem as soon as possible...  Properly it is not only the problem with boundary assignment, but something else.  I have tried to run ex5p.cpp with modification to my particular applications.   Thanks

**Comment by huidong80** [comment]
> 

Hi. To learn how to use FormRectangularSystemMatrix object to incorporate Dirichlet boundary conditions for off diagonal block.  I tested the example ex5p.cpp using mpirun -np 4 ex5p -m ../data/beam-tet.mesh -pa. Unfortunately, it produces the running error: 

Verification failed: (trial_el != NULL) is false:
 --> Only VectorTensorFiniteElement is supported!
 ... in function: virtual void mfem::VectorFEMassIntegrator::AssemblePA(const mfem::FiniteElementSpace&, const mfem::FiniteElementSpace&)
 ... in file: fem/bilininteg_vectorfe.cpp:752

Does this mean FormRectangularSystemMatrix only works for tensor product mesh?  

Without -pa in the command line, it runs well.


Thanks

**Comment by huidong80** [comment]
Hi,  it seems to me the running error comes earlier, at the place SetAssemblyLevel,,   I am not sure what  are the correct arguments for this function call if we use the command line with -pa.. 

Thanks

**Comment by pazner** [comment]
Hi @huidong80, MFEM's matrix-free/partial assembly capabilities are only fully supported on tensor-product elements. Do you need to enable partial assembly, or could you try running without `-pa`?

**Comment by huidong80** [comment]
Oh,  thanks a lot  for pointing out this issue.  No, I can live without partial assembly since most of the time, I use tetrahedral elements.  I was confused that FormRectangularSystemMatrix object has to be with the partial assembly (exp5p)..   If I understand it correctly, this object shall be independent of partial assembly?

**Comment by pazner** [comment]
That is correct, `MixedBilinearForm::FormRectangularSystemMatrix` will work independently of partial assembly (PA). If you have PA enabled, this will return a matrix-free operator, if not, this will return a matrix with the BCs eliminated.

**Comment by huidong80** [comment]
Hi, unfortunately,  it is still now working well to impose the symmetry for the saddle point structure.  Would it be possible to add some details here:

Following the structure:
D = [ M  B^T ]
       [ B    --C ].

and the example exp5.cpp, the main steps are the following:

define and get boundary dof list:
Array<int> u_ess_tdof_list;
Array<int> p_ess_tdof_list;
ufespace->GetBoundaryTrueDofs(u_ess_tdof_list);
pfespace->GetBoundaryTrueDofs(p_ess_tdof_list);


define linear and bilinear form:
ParBilinearForm *mVarf(new ParBilinearForm(ufespace));
ParMixedBilinearForm *bVarf(new ParMixedBilinearForm(ufespace, pfespace));
ParBilinearForm *pVarf(new ParBilinearForm(pfespace));

assemble linear and bilinear forms for M block , including essential bcs:
mVarf->AddDomainIntegrator(...)
mVarf->Assemble();
mVarf->EliminateEssentialBCDiag(u_ess_tdof_list, 1.0);

assemble linear and bilinear forms for B block , including essential bcs:
 OperatorPtr opB;
 bVarf->AddDomainIntegrator(...);
 bVarf->Assemble();
 bVarf->FormRectangularSystemMatrix(u_ess_tdof_list, p_ess_tdof_list, opB);


assemble linear and bilinear forms for C block , including essential bcs:
pVarf->AddDomainIntegrator(...);
pVarf->Assemble(); 
pVarf->EliminateEssentialBCDiag(p_ess_tdof_list, 1.0);

parallel assembling:
M = mVarf->ParallelAssemble();
B = bVarf->ParallelAssemble();
C = pVarf->ParallelAssemble();
Bt = new TransposeOperator(B);

.....

Unfortunately,  I got the errors during running time:

Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 0 on node clover exited on signal 11 (Segmentation fault).

it looks to me the boundary conditions are not assigned properly, but,  I simply cannot figure it out... 

Thank you in advance.
Huidong
