### ISSUE TITLE
Minor correction in Mfem_Assert call in sparsrMat class

### ISSUE THREAD

**Issue by prathamgit** [mfem/mfem#3116]
Should it be `B.width` in the line `<< B.height << ", B.width = " << width` in SparseMatric class ?
https://github.com/mfem/mfem/blob/670b7b1ae32f2126df8f4539a238b0aa4b8e33fe/linalg/sparsemat.cpp#L3059

**Comment by tzanio** [comment]
Looks correct to me, the full line with some reformatting is essentially

```c++
cerr << "Mismatch of this matrix size and rhs. "
     << "This height = " << height 
     << ", width = " << width 
     << ", B.height = " << B.height 
     << ", B.width = " << width;
```

**Comment by v-dobrev** [comment]
@tzanio, I think the point is to replace `", B.width = " << width` --> `", B.width = " << B.width`.

**Comment by tzanio** [comment]
Oh, that makes sense, sorry.

It should be indeed `<< ", B.width = " << B.width` in the last line.

@prathamgit, do you want to propose a simple PR to fix it?

**Comment by prathamgit** [comment]
@tzanio i did not understand what is "simple PR fix" ?

**Comment by tzanio** [comment]
Oh I just meant you can put the fix in a branch and issue a pull request to fix it in `master`.

**Comment by prathamgit** [comment]
Oh okay. Yes I can do that. Thanks!

**Comment by tzanio** [comment]
Hi @prathamgit, do you still plan to make a pull request for this?

**Comment by prathamgit** [comment]
Oh I have, a few days ago.

**Comment by tzanio** [comment]
Can you post a link to it here?

**Comment by prathamgit** [comment]
Right sorry. Here is the link.
https://github.com/mfem/mfem/pull/3161
I hope this link works.

**Comment by tzanio** [comment]
Addressed in https://github.com/mfem/mfem/pull/3161
