### ISSUE TITLE
Obtain config.mk in CMAKE builds

### ISSUE THREAD

**Issue by stefanozampini** [mfem/mfem#312]
Would it be possible to install a config.mk file out of a CMAKE build?
The reason is that at present if you build MFEM with CMAKE, you are also forced to build other codes that depend on MFEM (in this case, a library) with CMAKE. I'm not aware of any tool that permits to include and use  XXX.cmake configuration files with a standard makefile.

**Comment by juan42** [comment]
> Would it be possible to install a config.mk file out of a CMAKE build?
Absolutely. Someone needs to write a config.mk template that cmake has to fill.

**Comment by KazemKamran** [comment]
We are having the same problem installing Laghos.
