### ISSUE TITLE
question about the boundary condition

### ISSUE THREAD

**Issue by Kuloss** [mfem/mfem#3120]
hi, I'm a noob of the MFEM and github
I have a question about the boundary condition in Maxwell problem, when I simulate the scattering problem in ND space, the boundary condition formula is written as:  

$$
\vec{n} \times(\nabla \times \vec{E})+j k_{0} \vec{n}\times(\vec{n}  \times \vec{E})=\vec{n} \times\left(\nabla \times \vec{E} _{inc}\right)+j k_{0}\vec{n} \times\left(\vec{n}\times \vec{E} _{inc}\right)     
$$

$\vec{E} _{inc}$ is a Known vector, $\vec{n}$ is the normal vector on the boundary. So if I choose the `Linear Form Integrator` to make conforming with the right hand side of the equation, which Integrator should I chose. Is there only one boundary Integrators in ND space: `VectorFEBoundaryTangentLFIntegrator`.  And is there a big difference between `Domain Integrator` and `Boundary Integrator` in `Linear Form Integrator`? Once I have tried to use a `VectorDomainLFIntegrator` for the above boundary condition in ND space, but it doesn't work.

**Comment by tzanio** [comment]
@Kuloss, I formatted your post to use LaTeX. Can you double-check everything is correct?

**Comment by Kuloss** [comment]
> @Kuloss, I formatted your post to use LaTeX. Can you double-check everything is correct?
Sorry, first to use that, now I have double-checked.

**Comment by sshiraiwa** [comment]
@Kuloss. do you know the curl of E_inc, too? If so two terms on RHS can be done by  VectorFEBoundaryTangentLFIntegrator. n x ( curl E_inc) and n x (n x E_inc) needs to expanded
by hand.

**Comment by Kuloss** [comment]
> @Kuloss. do you know the curl of E_inc, too? If so two terms on RHS can be done by VectorFEBoundaryTangentLFIntegrator. n x ( curl E_inc) and n x (n x E_inc) needs to expanded by hand.

thanks for your advice, it makes help. As for your question, I know curl of E_inc, may be，using ' CurlGridFunctionCoefficient'. Now my problem is mostly the second item of RHS, Im not sure about how to quickly get $\vec{n}\times \vec{E} _{inc}$, is 'ProjectBdrCoefficientTangent'? 

Another question, if the second item on RHS was not $\vec{n} \times\left(\vec{n}\times \vec{E} _{inc}$, but just $\vec{E} _{inc}$. Which 'Integrator' I can chose, or I need to define my own Integrator? Seems in MFEM documentation, it has introduce the content of 'Writing Custom Integrators'

**Comment by sshiraiwa** [comment]
$n \times (n \times E )$ is the tangential component of - Einc.  I think you can use ProjectBdrCoefficientTangent with -j k0 as a coefficient.

**Comment by Kuloss** [comment]
> n×(n×E) is the tangential component of - Einc. I think you can use ProjectBdrCoefficientTangent with -j k0 as a coefficient.

For a long time, I was thinking the same thing before going here for the help，like $\vec{n} \times\left(\vec{n}\times \vec{E} _{inc}\right)= - \vec{E}$. My math tutor think it's workable only if $\vec{E}$ orthogonal in $\vec{n}$, I think he is right. Now, according your reply, the variable field calculated in ND space seem was a tangential vector parallel to edges, which actually different from the values gotten by `getVectorValue` method (the plot vector by glvis is not parallel to the edge),  is that you mean? 

But a little confused,   `ProjectBdrCoefficientTangent` have done $\vec{n} \times\left(\vec{n}\times \vec{E} _{inc}\right)$,  Whether or not need to write the corresponding item on RHS? And still the question, which `Linear Form Integrator` to input the coefficient gotten from `ProjectBdrCoefficientTangent`? (I know 'GridFunction' change to 'Coefficient' )

**Comment by sshiraiwa** [comment]
Sorry, I misspoke. What i meant is to use j k_0 E_inc as a coefficient and use VectorFEBoundaryTangentLFIntegrator for the integrator. My understanding is that since the test function is tangential to the boundary, the normal component of  E_inc does not contribute to the integration.

**Comment by sshiraiwa** [comment]
Wait a second, I think I got your point. I guess you need to have a coefficient to give n x E_inc at integration point. This can be done by using CalcOrtho of element transformation. (Will post a sample later)

**Comment by Kuloss** [comment]
> Wait a second, I think I got your point. I guess you need to have a coefficient to give an ex E_inc at integration point. This can be done by using CalcOrtho of element transformation.  (Will post a sample later)

@sshiraiwa Yes, I need a coefficient to give all $\vec{n}\times \vec{E} _{inc}$ at every integration point at one time, but it's still hard for me. I see the statement of `CalcOrtho` function is：


      /** For a given Nx(N-1) (N=2,3) matrix J, compute a vector n such that
      n_k = (-1)^{k+1} det(J_k), k=1,..,N, where J_k is the matrix J with the
      k-th row removed. Note: J^t.n = 0, det([n|J])=|n|^2=det(J^t.J). */
      void CalcOrtho(const DenseMatrix &J, Vector &n);


I have done some trying  to use `CalcOrtho` before. Seems `CalcOrtho` of element transformation only get one normal vector to one boundary element one by one, and the normal vectors to the integration points in one bdrElement  are the same. I'm not sure if something wrong with the following code to get the same normal vector in one bdrElement? 

       for (int j = 0; j < mesh->GetNBE(); j++)
       {
       int bdrgeom = mesh->GetBdrElementBaseGeometry(j);
       ElementTransformation* Trans3;
       Trans3 = fespace->GetBdrElementTransformation(j);
       GridFunction* x_real = &x.real();
       int intorder_test = 4;
       const IntegrationRule* ir_bdr;
       ir_bdr = &(IntRules.Get(bdrgeom, intorder_test));
       for (int NPionts = 0; NPionts < ir_bdr->GetNPoints(); NPionts++) {
           IntegrationPoint ip_int;
           ip_int = ir_bdr->IntPoint(NPionts);
           Vector normal(dim);
           Trans3->SetIntPoint(&ip_int);
           CalcOrtho(Trans3->Jacobian(), normal);
           normal.Print();
       }
       }

And thanks for your reply, I just notice the `Dirichlet (Essential) Boundary Conditions` was written as $\left(\vec{n}\times \vec{u} \right) \times\vec{n}=\vec{f}$ in MEFM documentation, in other books it was written as $\vec{n} \times\vec{E}= - \vec{n} \times\vec{E_{inc}}$. Actually, something different from what I thought at the beginning.  

now I get what you said, I can directly use `ProjectBdrCoefficientTangent` with the coefficient $jk_{0} \vec{E_{inc}}$ input to get the tangent component of $\vec{E_{inc}}$ and this component is written as $\left(\vec{n}\times \vec{E_{inc}} \right) \times\vec{n}$. But is the same `ProjectBdrCoefficientTangent` and `VectorFEBoundaryTangentLFIntegrator` ? I mean the later seems was $\int_{\partial \Omega }^{} \left (\widehat{n} \times \vec{f}   \right ) \cdot \vec{v_{i} }$ rather than $\int_{\partial \Omega }^{} \left (\widehat{n} \times\left ( \widehat{n}\times \vec{f} \right )  \right ) \cdot \vec{v_{i} } $, , Im not sure still about it.

**Comment by Kuloss** [comment]
> Wait a second, I think I got your point. I guess you need to have a coefficient to give an ex E_inc at integration point. This can be done by using CalcOrtho of element transformation.  (Will post a sample later)

@sshiraiwa Yes, I need a coefficient to give all $\vec{n}\times \vec{E} _{inc}$ at every integration point at one time, but it's still hard for me. I see the statement of `CalcOrtho` function is：


      /** For a given Nx(N-1) (N=2,3) matrix J, compute a vector n such that
      n_k = (-1)^{k+1} det(J_k), k=1,..,N, where J_k is the matrix J with the
      k-th row removed. Note: J^t.n = 0, det([n|J])=|n|^2=det(J^t.J). */
      void CalcOrtho(const DenseMatrix &J, Vector &n);


I have done some trying  to use `CalcOrtho` before. Seems `CalcOrtho` of element transformation only get one normal vector to one boundary element one by one, and the normal vectors to the integration points in one bdrElement  are the same. I'm not sure if something wrong with the following code to get the same normal vector in one bdrElement? 

       for (int j = 0; j < mesh->GetNBE(); j++)
       {
       int bdrgeom = mesh->GetBdrElementBaseGeometry(j);
       ElementTransformation* Trans3;
       Trans3 = fespace->GetBdrElementTransformation(j);
       GridFunction* x_real = &x.real();
       int intorder_test = 4;
       const IntegrationRule* ir_bdr;
       ir_bdr = &(IntRules.Get(bdrgeom, intorder_test));
       for (int NPionts = 0; NPionts < ir_bdr->GetNPoints(); NPionts++) {
           IntegrationPoint ip_int;
           ip_int = ir_bdr->IntPoint(NPionts);
           Vector normal(dim);
           Trans3->SetIntPoint(&ip_int);
           CalcOrtho(Trans3->Jacobian(), normal);
           normal.Print();
       }
       }

And thanks for your reply, I just notice the `Dirichlet (Essential) Boundary Conditions` was written as $\left(\vec{n}\times \vec{u} \right) \times\vec{n}=\vec{f}$ in MEFM documentation, in other books it was written as $\vec{n} \times\vec{E}= - \vec{n} \times\vec{E_{inc}}$. Actually, something different from what I thought at the beginning.  

now I get what you said, I can directly use `ProjectBdrCoefficientTangent` with the coefficient $jk_{0} \vec{E_{inc}}$ input to get the tangent component of $\vec{E_{inc}}$ and this component is written as $\left(\vec{n}\times \vec{E_{inc}} \right) \times\vec{n}$. But is the same `ProjectBdrCoefficientTangent` and `VectorFEBoundaryTangentLFIntegrator` ? I mean the later seems was $\int_{\partial \Omega }^{} \left (\widehat{n} \times \vec{f}   \right ) \cdot \vec{v_{i} }$ rather than $\int_{\partial \Omega }^{} \left (\widehat{n} \times\left ( \widehat{n}\times \vec{f} \right )  \right ) \cdot \vec{v_{i} } $, , Im not sure still about it.

**Comment by Kuloss** [comment]
The boundary condition is taken from the book" Theory and Computation of Electromagnetic Fields", written by Jian-Ming Jin, and there is a shortcut about it 


![image](https://user-images.githubusercontent.com/90549077/182085067-d4713993-edd5-4589-b29b-4fbb3844aa43.png)

**Comment by sshiraiwa** [comment]
Your routine to get normal looks okay. With the mesh attached, I got the following (order =4, and NPoints = 6). Is use mesh a curved mesh?
```
0.0346926 -0.0831267 0.277973
0.0247344 -0.0107851 0.289836
0.188636 -0.0117516 0.251093
0.101471 -0.0154737 0.272154
0.105485 -0.0456653 0.267272
0.0339255 -0.0460172 0.283336
0.354691 0.0454541 0.475198
0.0470251 0.0405831 0.545353
```
[sphere.msh.gz](https://github.com/mfem/mfem/files/9234402/sphere.msh.gz)

**Comment by Kuloss** [comment]
@sshiraiwa 
Thanks to your mesh. It helps me understand more about MFEM.

I guess I may find the way to get $\int_{\partial \Omega }^{} \left (\widehat{n} \times\left ( \widehat{n}\times \vec{f} \right )  \right ) \cdot \vec{v_{i} } $, how about adding some line In the following code
 You are the professional, looking forward to your advice.


      void VectorFEBoundaryTangentLFIntegrator::AssembleRHSElementVect(
      const FiniteElement &el, ElementTransformation &Tr, Vector &elvect)
      {
         int dof = el.GetDof();
         int dim = el.GetDim();
         int vdim = el.GetVDim();
         DenseMatrix vshape(dof, vdim);
         Vector f_loc(3);
         Vector f_hat(2);
         MFEM_VERIFY(vdim == 2, "VectorFEBoundaryTangentLFIntegrator "
               "must be called with vector basis functions of dimension 2.");
         elvect.SetSize(dof);
         elvect = 0.0;
         const IntegrationRule *ir = IntRule;
         if (ir == NULL)
         {
            int intorder = oa * el.GetOrder() + ob;  // <----------
            ir = &IntRules.Get(el.GetGeomType(), intorder);
         }
         for (int i = 0; i < ir->GetNPoints(); i++)
         {
            const IntegrationPoint &ip = ir->IntPoint(i);
            el.CalcVShape(ip, vshape);
            Tr.SetIntPoint(&ip);
            f.Eval(f_loc, Tr, ip);      
            if (dim == 2)
            {
               Tr.Jacobian().MultTranspose(f_loc, f_hat);
            }
            else if (dim == 1)
            {
               const DenseMatrix & J = Tr.Jacobian();
               f_hat(0) = J(0,0) * f_loc(0) + J(1,0) * f_loc(1);
               f_hat(1) = f_loc(2);
            }
            else
            {
               f_hat(0) = f_loc(1);
               f_hat(1) = f_loc(2);
            }
           Swap<double>(f_hat(0), f_hat(1));
           f_hat(0) = -f_hat(0);
          


            //The location I add my assumed codes, The location I add my assumed codes, The location I add my assumed codes
           //The location I add my assumed codes, The location I add my assumed codes, The location I add my assumed codes
           //The location I add my assumed codes, The location I add my assumed codes, The location I add my assumed codes
           Swap<double>(f_hat(0), f_hat(1));
           f_hat(0) = -f_hat(0);
            


           f_hat *= ip.weight;
           vshape.AddMult(f_hat, elvect);
         }
     }

**Comment by sshiraiwa** [comment]
I think you could create a coefficient which returns the normal of boundary triangles.
A sample below compares the RHS filled using n x E computed using n from the mesh and
from the ideal n. (the mesh is sphere, and thus n is known... at least within the accuracy of
mesh..)

```   
#include "mfem.hpp"
#include <fstream>
#include <iostream>

using namespace std;
using namespace mfem;

// Exact solution, E, and r.h.s., f. See below for implementation.
void E_exact(const Vector &, Vector &);
void n_x_E_exact(const Vector &, Vector &);
class SurfaceNormCoefficient : public VectorCoefficient
{
public:
  SurfaceNormCoefficient(int vd)
    : VectorCoefficient(vd) { }
  virtual void Eval(Vector &V, ElementTransformation &T,
                       const IntegrationPoint &ip);
};

int main(int argc, char *argv[])
{

   const char *mesh_file = "./sphere2.msh";
  
   Mesh *mesh = new Mesh(mesh_file, 1, 1);
   int dim = mesh->Dimension();
   int sdim = mesh->SpaceDimension();
   int order = 1;
   
   FiniteElementCollection *fec = new ND_FECollection(order, dim);
   FiniteElementSpace *fespace = new FiniteElementSpace(mesh, fec);

   GridFunction x(fespace);
   VectorFunctionCoefficient E(sdim, E_exact);
   x.ProjectCoefficient(E);

   VectorGridFunctionCoefficient Ecoeff(&x);
   SurfaceNormCoefficient norm(3);
   VectorCrossProductCoefficient n_x_E(norm, Ecoeff);

   LinearForm *b1 = new LinearForm(fespace);
   b1->AddBoundaryIntegrator(new VectorFEBoundaryTangentLFIntegrator(n_x_E));
   b1->Assemble();
   b1->Print();

   std::cout << "-----------------\n";

   VectorFunctionCoefficient n_x_E_coeff(sdim, n_x_E_exact);
   LinearForm *b2 = new LinearForm(fespace);
   b2->AddBoundaryIntegrator(new VectorFEBoundaryTangentLFIntegrator(n_x_E_coeff));
   b2->Assemble();
   b2->Print();
   
}

void E_exact(const Vector &x, Vector &E)
{
  E(0) = 1;
  E(1) = 0;
  E(2) = 0;
}

void n_x_E_exact(const Vector &x, Vector &n_x_E)
{

  Vector E(3);  
  E_exact(x, E);

  //  n x E
  n_x_E(0) = x[1]*E[2] - x[2]*E[1];
  n_x_E(1) = x[2]*E[0] - x[0]*E[2];
  n_x_E(2) = x[0]*E[1] - x[1]*E[0];  
}


void SurfaceNormCoefficient::Eval(Vector &V, ElementTransformation &T,
                      const IntegrationPoint &ip) {
  double x[3];
  Vector transpip(x, 3);
  
  T.SetIntPoint(&ip);    
  CalcOrtho(T.Jacobian(), V);
  V /= V.Norml2();

}  
```
[sphere2.zip](https://github.com/mfem/mfem/files/9262636/sphere2.zip)

**Comment by Kuloss** [comment]
@sshiraiwa 
Thanks for your codes, It works better and the result looks more sensible. 
I know this may be an unreasonable request again, I realize it's more difficulty to deal with $j k_{0} \vec{n}\times(\vec{n}  \times \vec{E})$ in  LHS.  My last figure is actually plot based on a coarse boundary condition
 
$$
\vec{n} \times\left(\nabla \times \vec{E}\right)-j k_{0} \vec{E}=\vec{n} \times\left(\nabla \times \vec{E} _{inc}\right)+j k_{0}\vec{n} \times\left(\vec{n}\times \vec{E} _{inc}\right)
$$

rather than

$$
\vec{n} \times(\nabla \times \vec{E})+j k_{0} \vec{n}\times(\vec{n}  \times \vec{E})=\vec{n} \times\left(\nabla \times \vec{E} _{inc}\right)+j k_{0}\vec{n} \times\left(\vec{n}\times \vec{E} _{inc}\right)     
$$

So, the result I got is still not correct. I want to use 'MixedWeakCurlCrossIntegrator' with the `j*k0*norm` coefficient to get $\int_{\partial \Omega }^{} \hat{n} \times\left ( jk_{0} \hat{n}\times\overrightarrow{u}  \right )$, and `norm`  is the coefficient you given. But in Example 22 and 25, the program has defined `SesquilinearForm* a` due to the complex Coefficients exist in the equation:

$$
\nabla \times\left(a\nabla \times \vec{u}\right)-{\omega}^{2}b\vec{u}+i{\omega}c \vec{u}=0    
$$

The difficulty is that I can't find a way to use `MixedWeakCurlCrossIntegrator` in a such defined `SesquilinearForm`, at the same time, I can's find a similar `SesquilinearForm` for `MixedBilinearForm`.

**Comment by Kuloss** [comment]
@sshiraiwa 
maybe the problem described above is not detailed, I upload the program and mesh file.  The boundary condition setting in the program is still not right, leaving $j k_{0} \vec{n}\times(\vec{n}  \times \vec{E})$ in LHS not realized actually.
[ex22g_And_Mesh.zip](https://github.com/mfem/mfem/files/9280479/ex22g_And_Mesh.zip)
