### ISSUE TITLE
questions about MFEM

### ISSUE THREAD

**Issue by liangLL888** [mfem/mfem#3124]
Hi, I'm a noob of the MFEM
I want to solve a waveguide discontinuity problem with MFEM, and I have several questions：
1. How to specify different materials for different regions？
2. Does MFEM implement the nonoverlapping Schwartz DDM？If I want to use Robin type transmission conditions in the nonoverlapping DDM to communicate between subdomains, what should I do? Do I need to get the boundary of each subdomain and apply Robin type transmission conditions on the boundary?

I would appreciate it if you could give me some examples or tutorials.

**Comment by tzanio** [comment]
Hi @liangLL888,

1. You can specify different materials by providing a piece-wise `Coefficient` to the bilinear/linear form integrators. See for example https://github.com/mfem/mfem/blob/master/examples/ex2.cpp#L166-L176.

2. It depends what you want to do with DDM. For example, MFEM automatically does that for the MPI decomposition and parallel assembly. If you want to develop e.g. a DD solver or multi-physics coupling, than take a look at the recent SubMesh PR, https://github.com/mfem/mfem/pull/2920.

Hope this helps,
Tzanio
