### ISSUE TITLE
Conversion from conservative variables to primitive variables, Example 18

### ISSUE THREAD

**Issue by ThinkingMarmot** [mfem/mfem#3128]
Hello, 

I am learning the example 18 of DG Euler Equations, and want to know if MFEM has a method or class for converting the conservative variables to primitive variables. I searched in the code and Issues and didn't find one. 

Thanks.

**Comment by pazner** [comment]
Hi @ThinkingMarmot,

To convert to primitive variables, you just need to divide momentum by density to get the velocity, and you can use the function `ComputePressure` from `ex18.hpp` to compute the pressure.

**Comment by ThinkingMarmot** [comment]
OK, I will try it. Thanks.
