### ISSUE TITLE
Run pcuda mfem with mpi and multiple GPUs

### ISSUE THREAD

**Issue by tangqi** [mfem/mfem#3129]
Hi,
How could I run mfem with mpi and multiple GPUs? 

I compiled through `make pcuda` successfully on a A100 HPC (Perlmutter). I tried the following example, which works fine:
`srun -n 4 ex9p -pa -m ../data/periodic-cube.mesh -rs 3 -rp 1 -d cuda`
But when I try `nvidia-smi`, it indicates I am only using one GPU of the four it allocated. Is this expected? If so, what's the right way to use multiple GPUs?

Thanks,
Qi

**Comment by v-dobrev** [comment]
On LLNL's Lassen this happens automatically. On Perlmuter, it seems, you need to do it explicitly, see here: https://docs.nersc.gov/performance/readiness/#running-applications.

**Comment by tangqi** [comment]
Thanks a lot. I am missing `--gpus-per-task ` indeed. It works well now!

One question before I close the issue: I run the following two cases
`srun -n 4 ex1p -d cuda`
`srun -n 4 ex1p -fa -d cuda`
they give me slightly different residuals and reduction factor from hypre. I think one is `LEGACY` and one is `FULL`. What makes the small difference here? Is that related to where the matrix is assembled (host vs device)?

Qi

**Comment by v-dobrev** [comment]
> What makes the small difference here? Is that related to where the matrix is assembled (host vs device)?

Yes, the difference is from the assembled matrix and, yes, `LEGACY` performs assembly on CPU (and then it is moved to GPU for the solve) while `FULL` performs the assembly on GPU.

**Comment by tangqi** [comment]
Is there a simple way to make sure the mpi used to compile mfem is gpu-aware ? I know my mpi should be gpu-aware. However, this would be the case if I use the wrapper `CC`.  But the flag is messed up if I just use `CUDA_CXX=CC`. 

Instead, I used `nvcc` and the default flags, which can compile mfem on perlmutter. But it is unclear if mpi is "gpu-aware". On petsc, it will produce a warning during the run if mpi is not gpu-aware. I am wondering if there is something similar on mfem or if it matters at all.

**Comment by tzanio** [comment]
@camierjs is an expert on this, but I don't think there is a "standard" way to ensure this -- it depends on the machine (and of course, the hardware).

**Comment by tangqi** [comment]
I am curious if gpu-aware MPI will make much difference with the current version of mfem. If it does not make much difference at the moment, I can just use nvcc with a MPI library on Perlmutter for now.

**Comment by v-dobrev** [comment]
The way MFEM is compiled when CUDA and MPI are enabled is that we tell `nvcc` (defined by `CUDA_CXX`) to call the MPI compiler (defined by `MPICXX`) for host compilation via the `-ccbin` flag. Thus, if you set `MPICXX=CC` then `nvcc` will call `CC` for host compilation.

That said, to make use of the GPU-aware MPI in MFEM, you need to call `mfem::Device::SetGPUAwareMPI()` after defining and configuring an `mfem::Device`. Note that in most cases we do not check `Device::GetGPUAwareMPI()` and move the data to host instead, so enabling GPU-aware MPI in MFEM may not make a noticeable difference at the moment. Of course, the current behavior can be improved to take advantage of the GPU-aware MPI.
