### ISSUE TITLE
Implementing DG discretization for the Stokes Equation

### ISSUE THREAD

**Issue by ryanblack129** [mfem/mfem#3130]
Hello,

I am new to MFEM and trying to implement a DG discretization for the Stokes equation

$-\nabla^2 \underline{u} + \nabla p = \underline{f} \quad\in\Omega$
$\nabla\cdot \underline{u} = g \quad\in\Omega$
$\underline{u} =\underline{0} \quad\in\partial\Omega$

where f and g are source terms corresponding to a manufactured solution
$u_x = (1 - x^{2})(1-y^{2})$
$u_y = (1 - x^{2})(1-y^{2})$
$p = x$

The problem is solved on a square [-1,1]x[-1,1] and so the average pressure is 0. For the DG discretization, I am following B. Rivière DG Methods for Solving Elliptic and Parabolic Equations Chp 6.

$a(\underline{u},\underline{v}) + b(\underline{v},p) = c(\underline{v}) \quad\forall \underline{v}$
$b(\underline{u},q) = d(q) \quad\forall q$

where
$a(\underline{u},\underline{v}) = \sum_E \int_E \nabla\underline{u} \cdot \nabla\underline{v} \ d\Omega - \sum_e \int_e \set{ \nabla\underline{u} } \underline{n}_e \cdot [\underline{v}] \ d\Gamma + \sigma\sum_e \int_e \set{ \nabla\underline{v} } \underline{n}_e \cdot [\underline{u}] \ d\Gamma  + \sum_e \int_e\frac{\kappa}{|e|} [\underline{v}]\cdot[\underline{v}] \ d\Gamma $

$b(\underline{v},p) = -\sum_E \int_E p\nabla\cdot\underline{v} \ d\Omega + \sum_e \int_e \set{ p }[\underline{v}] \cdot \underline{n}_e \ d\Gamma $

$c(\underline{v}) =  \sum_E \int_E \underline{f} \cdot \underline{v} \ d\Omega$

$d(q) =  \sum_E \int_E g \cdot q \ d\Omega$

and the sums over E correspond to all elements in the domain, while the sums over e correspond to all edges (interior and boundary) in the domain.

I can use existing integrators for most of the terms, however for the edge terms in bilinear form $a(\underline{u},\underline{v})$ I am following issue #2909 to create a vector version of DGDiffusionIntegrator. And for the face terms in bilinear form $b(\underline{v},p)$, I implemented a custom integrator (DGAvgNormalJumpIntegrator) using the examples in PR #2613 as a guide. In addition, I added face integrator support for MixedBilinearForms following the same PR #2613.

To setup the block system and solve, I am following example 5 and using MINRES. For now as a check, I take my initial guess for the iterative solver as the exact solution. Interestingly, I can accurately solve for pressure but am unable to get the velocity correct (see below plots after 1 iteration)

-Velocity
![image](https://user-images.githubusercontent.com/56736259/182901419-d1acabb5-f55d-443d-bafb-b1e4ca61c730.png)

-Pressure
![image](https://user-images.githubusercontent.com/56736259/182901847-3ee66a34-460c-437b-a6f1-00d1cb922517.png)

![image](https://user-images.githubusercontent.com/56736259/182889484-7657452f-7830-4235-94bd-8a6980d9b1f5.png)

I’ve attached my code and mesh file, any help implementing this discretization would be greatly appreciated. I suspect I have done something wrong in one of the custom face integrators.

Thanks,
Ryan

[Stokes.zip](https://github.com/mfem/mfem/files/9278401/Stokes.zip)

**Comment by jandrej** [comment]
#2613 aren't reviewed changes. There was no thorough process to check if those changes actually work like intended. The approach that you took seems reasonable. The "discontinuous look" in your velocity indicates an error in the integrator though. It seems like the interior and exterior face terms are not properly contributing to the residual. I know this isn't much input, but we probably need a while to take a deeper look at the problem.

**Comment by pazner** [comment]
I will second what @jandrej has said, based on the plot of the velocity, it does look like there is a problem with a face integrator. In particular, I remember that I had some issues with the `DGJumpJumpIntegrator` from @2613 at some point. You could try debugging by comparing with `DGDiffusionIntegrator` with the non-jump-jump terms deleted.

**Comment by ryanblack129** [comment]
Thanks for pointing me to the face integrators, I was able to find some bugs in $\sum_e \int_e \set{ p }[\underline{v}] \cdot \underline{n}_e \ d\Gamma$ and in the vector version of `DGDiffusionIntegrator` that fixed the issue. I ended up changing the problem slightly so the velocity field was divergence free that way I could switch between the symmetric gradient formulation (and use existing integrators `ElasticityIntegrator`, `DGElasticityIntegrator`) and the laplace formulation of Stoke's equations for debugging. 

The new manufactured solution was

$u = (1 - y^{2})$ 
$v = (1 - x^{2})$ 
$p = x$

and below are plots of the predicted velocity magnitude and pressure
![Screenshot from 2022-08-31 11-21-04](https://user-images.githubusercontent.com/56736259/187716156-e1371a98-55be-46b8-acf5-edaa6caf20e2.png)

**Comment by jandrej** [comment]
Sounds great! If you want you can share your effort with others and submit a PR with this as an example?

**Comment by ryanblack129** [comment]
I'd be happy to, I will need some time to clean up the code but will open a PR for this soon

**Comment by tzanio** [comment]
@ryanblack129, I'll close this now, but please feel free to reopen if you had any further questions.

**Comment by ryanblack129** [comment]
My apologies for the delay, the semester just started for me.

I finished cleaning up the code and have added comments following the MFEM examples. Please let me know if there is anything else that should be added/edited in the code/comments. I also wanted to note again that this code depends on PR 2613, specifically face integrator support for `MixedBilinearForm`.

Also, I am new github and was wondering what is the procedure for opening a PR? It looks like I may need to create a new branch?

[ex_Stokes.zip](https://github.com/mfem/mfem/files/9579166/ex_Stokes.zip)

**Comment by tzanio** [comment]
No worries @ryanblack129.

Yes, you need to create a new branch, push it and then create a PR.

Here is one example from a quick Google search: https://opensource.com/article/19/7/create-pull-request-github

Tzanio

**Comment by ryanblack129** [comment]
Thank you, I just opened a PR for this

Best,
Ryan
