### ISSUE TITLE
How to impose Dirichlet boundary conditions for saddle point problem

### ISSUE THREAD

**Issue by huidong80** [mfem/mfem#3135]
Hi, unfortunately,  it is still now working well to impose the symmetry for the saddle point structure.  I am sorry to create this issue again....

I try to give a bit more details on the problem:

Following the structure:
D = [ M  B^T ]
       [ B    --C ].

and the example exp5.cpp, the main steps are the following:

........

define and get boundary dof list:
Array<int> u_ess_tdof_list;
Array<int> p_ess_tdof_list;
ufespace->GetBoundaryTrueDofs(u_ess_tdof_list);
pfespace->GetBoundaryTrueDofs(p_ess_tdof_list);

define linear and bilinear form:
ParBilinearForm *mVarf(new ParBilinearForm(ufespace));
ParMixedBilinearForm *bVarf(new ParMixedBilinearForm(ufespace, pfespace));
ParBilinearForm *pVarf(new ParBilinearForm(pfespace));

assemble linear and bilinear forms for M block , including essential bcs:
mVarf->AddDomainIntegrator(...)
mVarf->Assemble();
mVarf->EliminateEssentialBCDiag(u_ess_tdof_list, 1.0);

assemble linear and bilinear forms for B block , including essential bcs:
 OperatorPtr opB;
 bVarf->AddDomainIntegrator(...);
 bVarf->Assemble();
 bVarf->FormRectangularSystemMatrix(u_ess_tdof_list, p_ess_tdof_list, opB);

assemble linear and bilinear forms for C block , including essential bcs:
pVarf->AddDomainIntegrator(...);
pVarf->Assemble(); 
pVarf->EliminateEssentialBCDiag(p_ess_tdof_list, 1.0);

parallel assembling:
M = mVarf->ParallelAssemble();
B = bVarf->ParallelAssemble();
C = pVarf->ParallelAssemble();
Bt = new TransposeOperator(B);

.....

Unfortunately,  I got the errors during running time:

Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 0 on node clover exited on signal 11 (Segmentation fault).

it looks to me the boundary conditions are not assigned properly, but,  I simply cannot figure it out... 

Thank you in advance.
Huidong

_Originally posted by @huidong80 in https://github.com/mfem/mfem/issues/3114#issuecomment-1207469246_

**Comment by pazner** [comment]
Here is an example of imposing boundary conditions for a saddle-point system.

The key is to use `FormSystemMatrix` and `FormRectangularSystemMatrix` instead of calling `ParallelAssemble` and the various `Eliminate[…]` routines.

```c++
H1_FECollection h1_fec(order, dim);
ND_FECollection nd_fec(order, dim);

ParFiniteElementSpace h1_fes(&pmesh, &h1_fec);
ParFiniteElementSpace nd_fes(&pmesh, &nd_fec);

// Assemble the finite element matrices for the block operator
//     D = [ A  B^T ]
//         [ B   C  ]
ParBilinearForm a(&h1_fes);
a.AddDomainIntegrator(new MassIntegrator);
a.Assemble();
a.Finalize();

ParMixedBilinearForm b(&h1_fes, &nd_fes);
b.AddDomainIntegrator(new MixedVectorGradientIntegrator);
b.Assemble();
b.Finalize();

ParBilinearForm c(&nd_fes);
c.AddDomainIntegrator(new VectorFEMassIntegrator);
c.Assemble();
c.Finalize();

// Eliminate the boundary conditions
Array<int> h1_ess_dofs, nd_ess_dofs;
h1_fes.GetBoundaryTrueDofs(h1_ess_dofs);
nd_fes.GetBoundaryTrueDofs(nd_ess_dofs);

OperatorHandle A, B, C;
a.FormSystemMatrix(h1_ess_dofs, A);
b.FormRectangularSystemMatrix(h1_ess_dofs, nd_ess_dofs, B);
c.FormSystemMatrix(nd_ess_dofs, C);

OperatorHandle Bt(B.As<HypreParMatrix>()->Transpose());

// We can combine the blocks into a monolithic HypreParMatrix
Array2D<HypreParMatrix*> blocks(2,2);
blocks(0,0) = A.As<HypreParMatrix>();
blocks(1,0) = B.As<HypreParMatrix>();
blocks(0,1) = Bt.As<HypreParMatrix>();
blocks(1,1) = C.As<HypreParMatrix>();
OperatorHandle D(HypreParMatrixFromBlocks(blocks));
```

**Comment by huidong80** [comment]
Hi,  Will,  thanks a lot for this great help, especially for a new MFEM user like me.  I will give another try following the above example from you,  will report the result shortly..

**Comment by huidong80** [comment]
HI Will.  After setting up the system matrix.  I tried to use preconditioned minres to solve the system:

MINRESSolver solver(MPI_COMM_WORLD);
solver.SetOperator(D);

but D is a OperatorHandle object, it seems not to be accepted as argument by solver.setoperator().  

Would it be possible to use some other object keeping the block structure?

Thanks a lot.

**Comment by pazner** [comment]
Given an `OperatorHandle`, you can assess the underlying `Operator` with `operator*`, for example:
```c++
solver.SetOperator(*D);
```
(`OperatorHandle` is an object that behaves kind of like a pointer to an `Operator`, and so this is similar to what you would do if `D` was declared as `Operator *D;`).

**Comment by huidong80** [comment]
Thanks Will.  In the last step, to add the block diagonal preconditioner (diagonal of A,   minus diagonal of C), I set the following:

// basically,  both matrices A and C have size m*m, where m is the number of grid points

HypreParMatrix *M = A.As<HypreParMatrix>();
HypreParMatrix *P = C.As<HypreParMatrix>();
(*P) *= -1;
   
 HypreParVector *MdU = NULL;
 HypreParVector *MdP = NULL;
 Solver *invUM, *invPM;

 MdU = new HypreParVector(MPI_COMM_WORLD, M->GetGlobalNumRows(), M->GetRowStarts());
 M->GetDiag(*MdU);
   
 MdP = new HypreParVector(MPI_COMM_WORLD, P->GetGlobalNumRows(), P->GetRowStarts());
 P->GetDiag(*MdP);
   
 invUM = new HypreDiagScale(*M);
 invPM = new HypreDiagScale(*P);
   
 invUM->iterative_mode = false;
 invPM->iterative_mode = false;

   Array<int> block_trueOffsets(3); // number of variables + 1
   block_trueOffsets[0] = 0;
   block_trueOffsets[1] = ufespace->TrueVSize();
   block_trueOffsets[2] = pfespace->TrueVSize();
   block_trueOffsets.PartialSum();


   BlockDiagonalPreconditioner *L2ElliptOptConPr = new BlockDiagonalPreconditioner(block_trueOffsets);
   L2ElliptOptConPr->SetDiagonalBlock(0, invUM);
   L2ElliptOptConPr->SetDiagonalBlock(1, invPM);

solver.SetPreconditioner(*L2ElliptOptConPr);

It seems to compile smoothly,  just produce the results with a lot of minres iterations.   I hope at least,  grammatically, it is correctly now. 

Is it possible to get preconditioned residual in the minres iterations?  It seems to me it outputs the residual of the original system.

Thanks a lot for your help.

**Comment by pazner** [comment]
It looks roughly OK to me. Keep in mind you're just using a diagonal preconditioner for both blocks, which may be why you're getting so many iterations (if one of your blocks is mass-equivalent this should be OK, you might want to use a Schur complement preconditioner for the 2,2 block, and maybe AMG would be better than diagonal scaling then?). I believe the residual output by MINRES is already in the preconditioner norm.

**Comment by huidong80** [comment]
Thanks a lot Will for your suggestions and comments.  I will go through the code carefully, and will report soon if any problems pop up.  I am very sorry that I am quite slow in coding.  Please do not close this issue for the moment being...  Thank you very much.

**Comment by huidong80** [comment]
Hi Will.  It seems  the minres check the norm of the unpreconditioned  residual, see, e.g., ex5p.cpp:  

 // 13. Solve the linear system with MINRES.
 //     Check the norm of the unpreconditioned residual.

Thanks a lot.

**Comment by tzanio** [comment]
> // 13. Solve the linear system with MINRES. 
> // Check the norm of the unpreconditioned residual.

@uvilla, am I missing something, or is this comment in Example 5p incorrect?

**Comment by uvilla** [comment]
@tzanio The very first implementation of MINRES for MFEM was a direct porting of Saunder’s Matlab code:

https://web.stanford.edu/group/SOL/software/minres/

There indeed they used the unpreconditioned norm of the residual as stopping criterion (although it adds some computational overhead).
From their documentation 

> The main stopping rule requires the residual \(r = b-Ax\) to be small enough 
(not the residual for the preconditioned system). This is as the user expects, and remains efficient even though only the 
preconditioned residual norm can be updated cheaply. The rule \( \|r_k\| \le (\|A\| \|x_k\| + \|b\|)*rtol \) shuts down earlier than the common rule \( \|r_k\| \le \|b\|*rtol \), but is justified by the backward error.

However, I’m not sure if that version of MINRES ever made it to the master branch, since another version of MINRES was implemented by Veselin (I believe). 
In sum, the comment in example 5p is probably wrong as it refers to my original implementation that never made it to the realease of mfem.

**Comment by tzanio** [comment]
Thanks @uvilla!

**Comment by huidong80** [comment]
Hi all,  thank you very much for clarification.  Did I understand it correctly that the residual by MINRES is indeed in the preconditioner norm, as pointed out by you ?

**Comment by huidong80** [comment]
Hi, Will.  It seems still no convergence in the FEM discretization.  Would it be possible to help check my rhs assembly (basically from exp5p.cpp), where ufespace and pfespace are standard nodal basis: 

Array<int> block_offsets(3); // number of variables + 1
   block_offsets[0] = 0;
   block_offsets[1] = ufespace->GetVSize();
   block_offsets[2] = pfespace->GetVSize();
   block_offsets.PartialSum();

   Array<int> block_trueOffsets(3); // number of variables + 1
   block_trueOffsets[0] = 0;
   block_trueOffsets[1] = ufespace->TrueVSize();
   block_trueOffsets[2] = pfespace->TrueVSize();
   block_trueOffsets.PartialSum();

   ParLinearForm *fform(new ParLinearForm);
   fform->Update(ufespace, rhs.GetBlock(0), 0);
   fform->AddDomainIntegrator(new DomainLFIntegrator(fcoeff));
   fform->Assemble();
   fform->SyncAliasMemory(rhs);
   fform->ParallelAssemble(trueRhs.GetBlock(0));
   trueRhs.GetBlock(0).SyncAliasMemory(trueRhs);

   ParLinearForm *gform(new ParLinearForm);
   gform->Update(pfespace, rhs.GetBlock(1), 0);
   gform->AddDomainIntegrator(new DomainLFIntegrator(gcoeff));
   gform->Assemble();
   gform->SyncAliasMemory(rhs);
   gform->ParallelAssemble(trueRhs.GetBlock(1));
   trueRhs.GetBlock(1).SyncAliasMemory(trueRhs);

   Thank you in advance.

**Comment by huidong80** [comment]
Hi,  a strange thing is even when I change fcoeff, it produce almost the same results, which is a sin(pi x) sin (pi y) sin (pi z) in 3D. Most likely, I made some mistakes in the right hand side assembly,  just could figure it out.  Thanks

**Comment by huidong80** [comment]
Hi all,  it start to run well now.  I got convergence with refined mesh size.  However,   the minres iterations change a lot with respect to mesh refinement:  115, 145, 132, 114, 85, ....   I am not sure if it uses the residual of the original system or the preconditioned one as the stopping criterion.  The output is 

MINRES: iteration  *** :  ||r||_B = ****

Thank you in advance.

**Comment by uvilla** [comment]
Hi @huidong80, Is the number of iterations decreasing as the mesh gets finer?

This is definitely an interesting behavior, however it is often the case to observe some mild dependence in the number of iterations with respect to mesh size.

**Comment by huidong80** [comment]
Hi @uvilla , i used the right preconditioner for our particular problem.  I have observed similar thing in the sequential version.  However, here I am not sure if the minres uses the residual of the original system or the preconditioned one. This may change a bit the iteration numbers.  It looks to me it uses the residual of the original one, but,  I am not so sure.  Is it possible to confirm this (to check the minres implemenation)?   thanks
