### ISSUE TITLE
Tesla miniapp: Customizing integration rule and order

### ISSUE THREAD

**Issue by sebastiangrimberg** [mfem/mfem#3139]
Is there any chance that anyone can comment on the customization of the `IntegrationRule` order in the Tesla miniapp ([code](https://github.com/mfem/mfem/blob/master/miniapps/electromagnetics/tesla_solver.cpp#L77))?

```
int irOrder = H1FESpace_->GetElementTransformation(0)->OrderW()
              + 2 * order;
int geom = H1FESpace_->GetFE(0)->GetGeomType();
const IntegrationRule * ir = &IntRules.Get(geom, irOrder);
```

Is there a general recommendation when not to use the defaults set by the particular integrators used? What happens here for mixed meshes?

Similarly, the `DivergenceFreeProjector` requires as input a specified integration rule order. What's the reason for not just using the integrator defaults?

Thanks a lot, hoping someone with more experience might have some helping wisdom here.

**Comment by mlstowell** [comment]
Hi, @sebastiangrimberg,

Sorry for the long delay. This is an area where MFEM needs a bit of improvement. For starters the various integrators set their own default integration orders perhaps based upon different assumptions. For this reason it is sometimes advisable to not accept the defaults and instead choose your own order. For example this is necessary when performing divergence cleaning in the Tesla mini app where the integration rule used to modify the right hand side must match that used in the matrix on the left hand side to ensure that the right hand side does indeed fall in the range of the operator on the left hand side.

When choosing an integration rule order for an MFEM integrator there are basically three things that should be considered; polynomial degree of the basis functions, polynomial degree of the mesh element, and variation of the user-defined coefficient (if present). When thinking of the basis function you must also consider whether or not derivatives will be taken and whether there is one or two basis functions present (obviously). When considering the order of the mesh element you must also consider how the Jacobian appears in the integrand. For H1 fields the Jacobian determinant is used for other basis function types the inverse of the Jacobian may appear in different forms. For many basis function types this dependence on the Jacobian will lead to non-polynomial integrands (often rational polynomials are present). The user-defined coefficients can introduce virtually any type of functional dependence on the coordinates but typically these vary slowly across an element and can often be adequately approximated by low order polynomials (but I'm sure there are notable exceptions when high order polynomial basis functions are used on larger elements). Clearly choosing an appropriate integration rule order can be complicated therefore predefined defaults are not always the best choice.

As you noticed this does create an issue with mixed meshes. In such meshes it is not possible to pass in a single custom integration rule which will work with all element types. I remember @tzanio and I discussing this issue a few years ago when mixed meshes were reintroduced to MFEM. Unfortunately, I don't think we have yet decided upon a general solution. One possibility is to have integrators compute their default order based on a linear combination of the orders of the basis functions, mesh element, and an approximate representation of the coefficient. The user could then supply the coefficients in this linear combination to alter the resulting integration rule order for any element type. It may also be possible to consider adaptive integration rules but this seems like a much larger task.

Best wishes,
Mark

**Comment by sebastiangrimberg** [comment]
Thank you very much for the detailed response Mark. This all makes sense to me. Indeed, an interface where the user can specify order in a particular way that is consistent across integrators would be much cleaner, but I imagine this isn't a high priority item.
