### ISSUE TITLE
Get ParMesh from loading a VisItDataCollection object

### ISSUE THREAD

**Issue by chvillanuevap** [mfem/mfem#3140]
I'm trying to get the underlying ParMesh from a VisItDataCollection object. I was provided with a VisIt file that was the output of a parallel run. The file is named `collection_name__000XXX.mfem_root`. Its accompanying directory has multiple files for the fields, one per processor (e.g. `field_name.000001`, `field_name.000002`, `field_name.000003`, etc).

Here is the code I'm using:

```
mfem::VisItDataCollection dc(MPI_COMM_WORLD, collection_name);
dc.Load(cycle);
mfem::ParMesh *pmesh = dynamic_cast<mfem::ParMesh *>(dc.GetMesh());
```

I'm running the code with the same number of processors as the original run that generated the VisIt file. However, after running my code above, `pmesh` is `NULL`.  I looked at issues #2785 and #389, and tried using `dc.SetFormat(mfem::DataCollection::PARALLEL_FORMAT);`, but that didn't make a difference.

I also tried doing the following:

```
mfem::ParGridFunction *pgrid_func = dc.GetParField(field_name);
mfem::ParFiniteElementSpace *pfe_space = pgrid_func->ParFESpace();
mfem::ParMesh *pmesh = pfe_space->GetParMesh();
```

But `ParFiniteElementSpace::GetParMesh` returns `NULL` as well because `ParFiniteElementSpace::pmesh` is never set. And calling  `ParFiniteElementSpace::GetMesh` and doing a `dynamic_cast` to `ParMesh` also returns `NULL`.

I'm guessing perhaps the way the VisIt file was written prohibits me from loading the `ParMesh` object. Or am I doing something else wrong? Thanks!

**Comment by tzanio** [comment]
@v-dobrev can confirm, but I believe if the parallel mesh was saved with 

```c++
visit_dc.SetFormat(DataCollection::PARALLEL_FORMAT);
```

then you should be able to read it back with

```c++
pmesh = dynamic_cast<ParMesh*>(visit_dc.GetMesh());
```

See for example [tests/par-mesh-format/ex1p.cpp](https://github.com/mfem/mfem/blob/master/tests/par-mesh-format/ex1p.cpp).

**Comment by chvillanuevap** [comment]
I'm not sure how the original VisIt file was saved. Is it safe to assume that if my `dynamic cast` returns `null` that the VisIt file was saved with `DataCollection::SERIAL_FORMAT`?

**Comment by v-dobrev** [comment]
> I'm not sure how the original VisIt file was saved. Is it safe to assume that if my `dynamic cast` returns `null` that the VisIt file was saved with `DataCollection::SERIAL_FORMAT`?

Yes, that's what it means. You can also look in the `.mfem_root` file which is a json file -- there should be a filed called "format", 0 meaning serial format, and 1 -- parallel format. If "format" is missing, then it is assumed to be 0.

Note that parallel meshes and fields can be saved as "serial" which means each processor saves its mesh without the data describing the mesh connections between processors. This is usually sufficient for visualization, however, it means that we cannot recover the `ParMesh` since some data is missing.

**Comment by chvillanuevap** [comment]
I can see in the `.mfem_root` file that the data was saved in serial format. Is there a workaround to recover the `mfem::ParMesh` without running again the original simulation that created the VisIt file? I have the original mesh, so could partition it. Something like (pseucode):
```
mfem::VisItDataCollection dc(MPI_COMM_WORLD, collection_name); // saved in serial format
...
mfem::GridFunction *grid_func = dc.GetField(field_name);
...
mfem::Mesh mesh(original_unpartitioned_mesh);
mfem::ParMesh pmesh(dc.comm(), original_unpartitioned_mesh);
...
// Project grid function from VisIt onto a ParGridFunction build using pmesh?
```

**Comment by v-dobrev** [comment]
I think there are various way to do this.

One way is update the mesh files to the parallel format: save the `ParMesh` using the `ParPrint()` method:
```c++
   ofstream ofs(MakeParFilename("pmesh.", my_rank));
   ofs.precision(8);
   pmesh->ParPrint(ofs);
```
and copy these new files to the same directory where the original mesh files are (the old mesh files should have names like `mesh.000000`); with these new mesh files, just update the "format" in the `.mfem_root` file and that should let you load the collection in the parallel format. You may need to change the mesh "path" pattern from "mesh" to "pmesh" but that is not strictly necessary (I think) when loading the collection using `mfem::VisItDataCollection`.

**Comment by chvillanuevap** [comment]
Sounds good. I'll give that a shot. I'll close this ticket for now, since my initial query has been answered. Thanks a lot!
