### ISSUE TITLE
Block size of a PETSc matrix

### ISSUE THREAD

**Issue by prj-** [mfem/mfem#3142]
I'm trying to extract the PETSc matrix from a linear elasticity problem by using `examples/petsc/ex2p.cpp` and running `mpirun -n 2 ./ex2p -m ../../data/beam-quad.mesh`. The call to `MatIncreaseOverlap()` from the below diff in debug mode reveals that the matrix does not have a 2x2 block structure even though this is a 2D problem with 2 components and I'm using `Ordering::byVDIM`.
```
[0]PETSC ERROR: --------------------- Error Message --------------------------------------------------------------
[0]PETSC ERROR: Invalid argument
[0]PETSC ERROR: Block size 2 is incompatible with the indices: non consecutive indices 4001 3057
```
Indeed, dumping the matrix in MATLAB format reveals that the (1618, 4001) coefficient is missing.
```
[...]
1618 3057  -5.0000000000000000e-01
1618 3058  -6.6666666666666652e-01
1618 4002  3.3333333333333193e-01
1619 19  -4.1666666666666664e+01
1619 20  3.0198066269804258e-14
[...]
```
Do you know what is going on? Any way to insert this coefficient in the PETSc matrix even though it is 0?
```diff
diff --git a/examples/petsc/ex2p.cpp b/examples/petsc/ex2p.cpp
index e57e220a6..02f82cc33 100644
--- a/examples/petsc/ex2p.cpp
+++ b/examples/petsc/ex2p.cpp
@@ -38,3 +38,3 @@
 //               We recommend viewing Example 1 before viewing this example.
-
+#include "petsc.h"
 #include "mfem.hpp"
@@ -168,3 +168,3 @@ int main(int argc, char *argv[])
    ParFiniteElementSpace *fespace;
-   const bool use_nodal_fespace = pmesh->NURBSext && !amg_elast;
+   const bool use_nodal_fespace = false;// pmesh->NURBSext && !amg_elast;
    if (use_nodal_fespace)
@@ -291,2 +291,10 @@ int main(int argc, char *argv[])
       a->FormLinearSystem(ess_tdof_list, x, *b, A, X, B);
+      mfem::petsc::Mat D = A.operator Mat();
+      IS is;
+      Mat E;
+      PetscCall(MatViewFromOptions(D, NULL, "-A"));
+      PetscCall(MatSetBlockSize(D, 2));
+      PetscCall(MatGetOwnershipIS(A, &is, NULL));
+      PetscCall(MatIncreaseOverlap(A, 1, &is, 1));
+      PetscCall(ISDestroy(&is));
       if (myid == 0)
```

**Comment by jandrej** [comment]
> the matrix does not have a 2x2 block structure even though this is a 2D problem with 2 components and I'm using 

Ordering::byVDIM
This is expected. The library doesn't block _global_ matrices by VDIM.

> Indeed, dumping the matrix in MATLAB format reveals that the (1618, 4001) coefficient is missing.

You're trying to get the form to conform to a 2x2 block size right? Can you try this without adding Dirichlet boundary conditions? The `DiagonalPolicy` or some other method might erase this entry because it's zero.

**Comment by prj-** [comment]
> You're trying to get the form to conform to a 2x2 block size right?

Yes, that's exactly what I want.

> Can you try this without adding Dirichlet boundary conditions?

I had guessed that something could come from essential boundary conditions, but even with none, this generates the same failure with the same missing coefficient. Do you have any other suggestion, please?

**Comment by stefanozampini** [comment]
> This is expected. The library doesn't block global matrices by VDIM. 

Shouldn't be difficult to add. @tzanio @v-dobrev any objection to introduce block distribution of dofs?

**Comment by tzanio** [comment]
No objections.

**Comment by stefanozampini** [comment]
@prj- I have run some tests, and it seems that dofs are initially split correctly. What is not clear to me, is why zeroes disappear from the final matrix, probably an "optimization" of the PtAP operation, I don't know. But this is what is causing issues to the overlap computation.

When the final overlap `IS` is constructed, all the required indices seem there, but not in the correct order, for example, the indices may look like

```...
170
230
231
171
...
```

which is not valid from a blocksize point of view, but both 170 and 171 are there, only at different locations.

If you change the way PETSc computes the overlap,  using `MatMPIAIJSetUseScalableIncreaseOverlap`, then I can run your code. I know it is not a perfect solution, but it may be good for your test cases. What do you think?

**Comment by prj-** [comment]
Thanks, I believe that should do the trick, it's also working in 3D (with a bs of 3). Out of curiosity, do you know of a way to deactivate the "optimization"? Trying to convert from AIJ to BAIJ gives the following error.
```
[1]PETSC ERROR: --------------------- Error Message --------------------------------------------------------------
[1]PETSC ERROR: Argument out of range
[1]PETSC ERROR: New nonzero at (0,563) caused a malloc
Use MatSetOption(A, MAT_NEW_NONZERO_ALLOCATION_ERR, PETSC_FALSE) to turn off this check
[...]
```

**Comment by stefanozampini** [comment]
@prj-  It is MFEM doing the optimization since we call `a->Assemble()`. By default zero entries are skipped, which results in a matrix with a not PETSc-compliant block size structure. Switching to `a->Assemble(1)` fixes the problem. Can you try using https://github.com/mfem/mfem/pull/3179?

**Comment by prj-** [comment]
It works as expected, thank you!

**Comment by tzanio** [comment]
Discussion continued in #3179
