### ISSUE TITLE
How to calculate the shape function of a random point

### ISSUE THREAD

**Issue by HaoWangCase** [mfem/mfem#3150]
I am coupling a meshless method with MFEM. The MFEM is used as a background mesh. I would like to calculate the finite element shape functions of the meshless point in a particular mesh. 

I notice that maybe I can generate an integration point at the location of the meshless point. However, the method "CalcShape" can only calculate the shape functions in the reference element. I can only get the physical coordinates of the meshless point, is there a way to transfer the physical point into the reference element, or I can directly calculate the shape functions based on physical locations?

Thanks.

**Comment by vladotomov** [comment]
See `Mesh::FindPoints` or the classes in `fem/gslib.hpp`. These methods return the element that has the point and the corresponding `IntegrationPoint` in reference space. There are some examples in `miniapps/gslib`.

**Comment by HaoWangCase** [comment]
I do not want to find the integration point in a mesh. Actually, I am introducing another point on top of the finite element mesh, and want to use the introduced point as an integration point. I know the physical location of the introduced point and I can find which element the point is in, but I do not know the location of the point in reference space. 

I am wondering how I can transfer this introduced point into reference space. 

Thanks.

**Comment by vladotomov** [comment]
You need to invert the `reference -> physical` mapping. I believe this is done as part of `Mesh::FindPoints`, see the code there.

**Comment by tzanio** [comment]
See also the class `InverseElementTransformation` in `fem/eltrans.?pp`.

**Comment by HaoWangCase** [comment]
I have figured this out using ElementTransformation -> TransformBack. Thanks for all the advice. Please close this issue. 

Thanks!
