### ISSUE TITLE
Low-order refined classes for spaces of vector dimension > 1

### ISSUE THREAD

**Issue by nmnobre** [mfem/mfem#3153]
Hi,

This may be a foolish question but are the LOR discretizations and solvers in MFEM prepared to work with spaces of vector dimension greater than one?

Cheers!

**Comment by pazner** [comment]
Hi @nmnobre, in principle everything should work fine, but it looks like this case wasn't fully supported in the code. This should be fixed in #3154.

**Comment by nmnobre** [comment]
Perfect, I'll test and report.

Thank you very much :)

**Comment by nmnobre** [comment]
I can confirm #3154 does indeed fix the problems I was encountering.
This issue may now be closed (I just don't know if you'd rather wait for the PR to be merged).

Thank you. 🎉

**Comment by tzanio** [comment]
Thanks for reporting the issue and checking the fix @nmnobre!
