### ISSUE TITLE
MFEM in web search results

### ISSUE THREAD

**Issue by jdahm** [mfem/mfem#316]
I noticed the other day that MFEM's description in the search results is cut short with the ASCII art at the top of the README. ![This image](https://user-images.githubusercontent.com/68032/31734899-0190bf80-b3f5-11e7-9809-cc03afde1673.png)
This is very minor, but it would be nice to have it read something like "A Finite Element Discretization Library MFEM is a modular parallel C++ library for finite element methods..." without this interruption.

**Comment by tzanio** [comment]
I'm not sure why Google generates the preview this way. Other search engines use the short description instead of the README content, which I think is better:

- [Bing](https://www.bing.com/search?q=mfem&qs=n&form=QBLH&sp=-1&pq=mfem)
- [DuckDuckGo](https://duckduckgo.com/?q=mfem&t=hf&ia=web)

Any suggestions what can we do about it (besides modifying the README)?

**Comment by tzanio** [comment]
BTW, did you know that MFEM also stands for:

- [Multi-Factor Emerging Markets Equity](http://www.pimcoetfs.com/Funds/Pages/MFEM.aspx?WT.svl=fund_nav), an ETF fund on the stock market
- [Ministry of Finance and Economic Management](http://www.mfem.gov.ck/oldsite/index.php/ministry-of-finance-and-economic-management-mfem) in the Cook islands
- as well as "mixed" and "moving" finite elements

**Comment by jdahm** [comment]
I looked around a bit today thinking there would be more information about this online, as I'm sure many developers would like their GitHub repos featured well, but unfortunately there isn't. For example, why does it not just use the description?

I'm surprised that Google doesn't index GitHub pages as it does e.g. with recipes like this excellent [snack cake](https://www.google.com/search?q=chocolate+snack+cake+with+strawberry+frosting+recipe) (shameless plug). Duckduckgo does a much better job of serving content in that way.

If no one else has ideas I'll close this issue in a few days.

**Comment by jdahm** [comment]
There doesn't seem to be anything on the web written about this, so I'll close this for now until we have more information.
