### ISSUE TITLE
How to get eigen values and eigen vectors in serial mode?

### ISSUE THREAD

**Issue by ruihuasun** [mfem/mfem#3164]
I noticed that in the examples where the solution for eigenvalues was presented only in parallel mode, and the function GetEigenvalue() only exists in mfem::SlepcEigenSolver, mfem::HypreLOBPCG.
Is it possible to solve eigen values and eigen vectors in serial mode? which means no other third-party modules(mpi, hypre) are needed.

**Comment by ruihuasun** [comment]
A simple example would be greatly appreciated if there has the solution to this issue😊

**Comment by ruihuasun** [comment]
Oh by the way, the linear system is a complex linear system.

**Comment by tzanio** [comment]
@mlstowell and @jetremblay can correct me if I am wrong, but I don't think we have currently a serial eigensolver in MFEM.

Of course, you can always run the parallel version on 1 core 😁

**Comment by mlstowell** [comment]
Hello, @ruihuasun,

I believe @tzanio is correct. MFEM itself does not have an eigenvalue solver. We rely on third party libraries for this functionality and merely "wrap" functions that exist in those libraries.

That being said we might have an option for you. We have an older branch which has not been touched in at least a couple years which had wrappers for ARPACK including a serial eigenvalue solver. You might be able to grab the files [arpack.hpp and arrack.cpp](https://github.com/mfem/mfem/blob/a0b8427774cc3b9df6cb6d6df458bd47806d153b/linalg/arpack.hpp#L77)  from this branch and bring them up to date enough to be useful.

Best wishes,
Mark

**Comment by jetremblay** [comment]
Hello, I am not too familiar with ARPACK but it seems to support complex problems.

I noticed a simple [power method](https://github.com/mfem/mfem/blob/be8eaf6900d0a0029cb08c5cf9b8ac562e2c7798/linalg/operator.cpp#L632) is implemented, would that be good enough?

**Comment by ruihuasun** [comment]
@jetremblay I think the PowerMethod::EstimateLargestEigenvalue() may not help. What I want is to get the eigen values and eigen  vectors of a Helmholtz problem, they are all complex numbers.
Maybe I can solve this by introducing some other libraries like Eigen, but that is not compatible with current mfem parbilinearform.
Isn't there any way to solve for complex eigenvalues and eigenvectors under the mfem framework?

**Comment by tzanio** [comment]
ping: @psocratis
