### ISSUE TITLE
GetVDofs implementation doesn't match its documented behavior

### ISSUE THREAD

**Issue by mlstowell** [mfem/mfem#3166]
According to the header file: https://github.com/mfem/mfem/blob/641078645f6eb2762ce7d9b05050a247e74aafb2/fem/fespace.hpp#L674
This method should return "all" degrees of freedom associated with the specified vector dimension. However, according to the implementation:
https://github.com/mfem/mfem/blob/641078645f6eb2762ce7d9b05050a247e74aafb2/fem/fespace.cpp#L195
The number of returned `vdofs` is determined by the length of the `dofs` array which is provided as an argument. If "all" dofs are to be returned the `dofs` array should be resized to match `ndofs_` inside the method. This would be more consistent with other methods which fill arrays of `dofs` associated with mesh entities.

**Comment by tzanio** [comment]
This looks like an inaccuracy to me too.

I agree that we should resize the `dofs` array inside the method.

**Comment by v-dobrev** [comment]
I seems like there is some misunderstanding here: `dofs` is both input and output parameter here and its size should remain the same. We are simply converting "scalar" dofs to "vector" dofs for a given vector component `vd` (typically, `0 <= vd < vdim`.)

The word "all" in the doxygen comment refers to all entries in the input `dofs` array -- maybe that is creating the confusion.
