### ISSUE TITLE
Face normal in reference configuration

### ISSUE THREAD

**Issue by barreracruz** [mfem/mfem#3169]
Is there an easy way to compute the normal of a face in the reference configuration within the `AssembleRHSElementVect` call for an `InteriorFacentegrator`? Something like `CalcOrtho` but that returns one of six options, i.e., in 3D for hexes: [+/- 1, 0, 0], [0, +/- 1, 0], [0, 0,+/- 1, 0] depending on where the face is in the reference element.

**Comment by pazner** [comment]
Hello @barreracruz,

In `AssembleRHSElementVect`, you have the `FaceElementTransformations &Tr` as one of the arguments. The "face number" of the face is given by `Tr.ElementNo`. You can then get lots of information about the face by calling `Mesh::GetFaceInformation`.

In particular, `FaceInformation::element` contains the `local_face_id` for each of the neighboring elements. This will be a number identifying one of the six faces of the reference element. The meaning of the faces is defined here:
https://github.com/mfem/mfem/blob/5150ab71e9b2a6d999cf68e5186ef8c8312a9308/fem/geom.cpp#L989-L994

You can then use that number to figure out the normal in reference coordinates.

**Note**, however, that for each of the two neighboring elements, there will be a different reference normal vector, and these two normal vectors do not need to agree — it is completely dependent on the configuration of the mesh.

**Comment by barreracruz** [comment]
Thank you, @pazner. I'll give that a try. I may also need the `local_face_id` for other computations so this was helpful in more than one way.

**Comment by barreracruz** [comment]
How can I access the local/reference coordinates of the face vertices in this case? I would like my implementation to be agnostic of the element type so I was thinking of generating a couple vectors from three vertices, then do a cross product and normalize the resulting vector (which should be orthogonal to the face).

**Comment by pazner** [comment]
`Geometries.GetVertices(geom)` will return the reference coordinate vertices for the given `geom` type. The vertices of the face are in `Geometry::Constants::FaceVert`. You will probably need a switch statement since the geometry type is a template parameter.

**Comment by barreracruz** [comment]
Thanks again, @pazner. I do not have any further questions regarding this issue so I will close it now.

**Comment by barreracruz** [comment]
Ok, probably I closed it too soon. For 2D elements, `FaceVert` has only one face, but the `local_face_id` from `FaceInformation` still provides different IDs. Do these IDs correspond to edges? If so, can I access the vertex ID by using `Edges` instead of `FaceVert` in the `Geometry` struct?

**Comment by pazner** [comment]
Yes, that's exactly right. It is a bit unfortunate that the term "face" has a bit overloaded meaning. Sometimes "face" can mean a dimension-2 geometric entity (e.g. the triangular faces of a tetrahedron), and sometimes "face" can mean a codimension-1 geometric entity (e.g. a quadrilateral element has four faces). In 3D they coincide, but in 2D this can cause some confusion.

**Comment by barreracruz** [comment]
Yes, that seemed to work. Thanks again!
