### ISSUE TITLE
BlockMatrix doesn't own the offsets

### ISSUE THREAD

**Issue by kvoronin** [mfem/mfem#317]
Hi all,

I cannot understand why the BlockMatrix doesn't take the ownership (or simply copies) the offsets.
It seems to me that for now I have to care about the offsets used in the BlockMatrix constructor so that they are not deleted before the end of lifetime of the BlockMatrix instance. 
Isn't it inconvenient?

Best,
Kirill

**Comment by tzanio** [comment]
Offsets are shared between the BlockMatrix, BlockVector, BlockDiagonalPreconditioner etc. objects defined for the same block structure. We don't want a copy in each of these objects.

**Comment by jakubcerveny** [comment]
The offsets are really small. Perhaps an actual copy wouldn't really matter
and it would simplify the code.

Jakub

**Comment by kvoronin** [comment]
Thanks for the explanation
