### ISSUE TITLE
Simulating ion trajectories in DC and RF electric fields, with additionnal pressure gradients.

### ISSUE THREAD

**Issue by MidnightBiscuit** [mfem/mfem#3180]
Hello, I have a question about the capabilities of mfem regarding a problem I want to solve.
I want to design a device to guide molecular ions with electrodes (as in ion optics), I would like to know if mfem allows me to render the trajectories of charged particules in electric fields ?
I will reproduce a design in mfem, and then try to optimize the ion throughput by trying several voltages, fields, geometries etcetc. The fields are mostly DC with one quadrupole having RF field. I can get rid of the RF if it is a problem.
Also, is it possible to combine the electric problem with a pressure problem ? My apparatus has gradient pressure, air at atmospheric pressures enters and through appertures the pressure goes down to 10^-6 mbar, I would like to render this properly. Is it possible to render the dynamics of charged particles in such problems with mfem ?
Don't hesitate to require more detail if required.
Regards.

**Comment by tzanio** [comment]
Hi @MidnightBiscuit,

I could be wrong, but I don't think there is an example or miniapp in MFEM that can directly help with your problem. If I understand correctly, I believe you can build such a miniapp with MFEM, but that may require some work. 

Maybe @mlstowell or other folks in the community can offer additional advice.

Tzanio
