### ISSUE TITLE
question about ReadVTKMesh

### ISSUE THREAD

**Issue by tarinma** [mfem/mfem#3184]
Should “POINT_DATA” in line 1256 here be "CELL_DATA"?

 1152 void Mesh::ReadVTKMesh(std::istream &input, int &curved, int &read_gf,
 1153                        bool &finalize_topo)
 1154 {
 1155    // VTK resources:
 1156    //   * https://www.vtk.org/doc/nightly/html/vtkCellType_8h_source.html
 1157    //   * https://www.vtk.org/doc/nightly/html/classvtkCell.html
 1158    //   * https://lorensen.github.io/VTKExamples/site/VTKFileFormats
 1159    //   * https://www.kitware.com/products/books/VTKUsersGuide.pdf
 1160 
 1161    string buff;
 1162    getline(input, buff); // comment line
 1163    getline(input, buff);
 1164    [filter_dos](https://docs.mfem.org/html/namespacemfem.html#aa86d6a80802a82927066e9a0e012cb2f)(buff);
 1165    if (buff != "ASCII")
 1166    {
 1167       MFEM_ABORT("VTK mesh is not in ASCII format!");
 1168       return;
 1169    }
 1170    do
 1171    {
 1172       getline(input, buff);
 1173       [filter_dos](https://docs.mfem.org/html/namespacemfem.html#aa86d6a80802a82927066e9a0e012cb2f)(buff);
 1174       if (!input.good()) { MFEM_ABORT("VTK mesh is not UNSTRUCTURED_GRID!"); }
 1175    }
 1176    while (buff != "DATASET UNSTRUCTURED_GRID");
 1177 
 1178    // Read the points, skipping optional sections such as the FIELD data from
 1179    // VisIt's VTK export (or from Mesh::PrintVTK with field_data==1).
 1180    do
 1181    {
 1182       input >> buff;
 1183       if (!input.good())
 1184       {
 1185          MFEM_ABORT("VTK mesh does not have POINTS data!");
 1186       }
 1187    }
 1188    while (buff != "POINTS");
 1189 
 1190    [Vector](https://docs.mfem.org/html/classmfem_1_1Vector.html) points;
 1191    int np;
 1192    input >> np >> ws;
 1193    getline(input, buff); // "double"
 1194    points.[Load](https://docs.mfem.org/html/classmfem_1_1Vector.html#a9194a2c0e24782bea05303c02fb5bfce)(input, 3*np);
 1195 
 1196    //skip metadata
 1197    // Looks like:
 1198    // METADATA
 1199    //INFORMATION 2
 1200    //NAME L2_NORM_RANGE LOCATION vtkDataArray
 1201    //DATA 2 0 5.19615
 1202    //NAME L2_NORM_FINITE_RANGE LOCATION vtkDataArray
 1203    //DATA 2 0 5.19615
 1204    do
 1205    {
 1206       input >> buff;
 1207       if (!input.good())
 1208       {
 1209          MFEM_ABORT("VTK mesh does not have CELLS data!");
 1210       }
 1211    }
 1212    while (buff != "CELLS");
 1213 
 1214    // Read the cells
 1215    [Array<int>](https://docs.mfem.org/html/classmfem_1_1Array.html) cell_data, cell_offsets;
 1216    if (buff == "CELLS")
 1217    {
 1218       int ncells, n;
 1219       input >> ncells >> n >> ws;
 1220       cell_offsets.[SetSize](https://docs.mfem.org/html/classmfem_1_1Array.html#a566edbabee3d4f0d7ce15cbc638021ca)(ncells);
 1221       cell_data.[SetSize](https://docs.mfem.org/html/classmfem_1_1Array.html#a566edbabee3d4f0d7ce15cbc638021ca)(n - ncells);
 1222       int offset = 0;
 1223       for (int i=0; i<ncells; ++i)
 1224       {
 1225          int nv;
 1226          input >> nv;
 1227          cell_offsets[i] = offset + nv;
 1228          for (int j=0; j<nv; ++j)
 1229          {
 1230             input >> cell_data[offset + j];
 1231          }
 1232          offset += nv;
 1233       }
 1234    }
 1235 
 1236    // Read the cell types
 1237    input >> ws >> buff;
 1238    [Array<int>](https://docs.mfem.org/html/classmfem_1_1Array.html) cell_types;
 1239    int ncells;
 1240    MFEM_VERIFY(buff == "CELL_TYPES", "CELL_TYPES not provided in VTK mesh.")
 1241    input >> ncells;
 1242    cell_types.[Load](https://docs.mfem.org/html/classmfem_1_1Array.html#a1ed472e110a519517d0f85cbc2e55b5a)(ncells, input);
 1243 
 1244    while ((input.good()) && (buff != "CELL_DATA"))
 1245    {
 1246       input >> buff;
 1247    }
 1248    getline(input, buff); // finish the line
 1249 
 1250    // Read the cell materials
 1251    // bool found_material = false;
 1252    [Array<int>](https://docs.mfem.org/html/classmfem_1_1Array.html) cell_attributes;
 1253    while ((input.good()))
 1254    {
 1255       getline(input, buff);
 1256       if (buff.rfind("**POINT_DATA**") == 0)
 1257       {
 1258          break; // We have entered the POINT_DATA block. Quit.
 1259       }
 1260       else if (buff.rfind("SCALARS material") == 0)
 1261       {
 1262          getline(input, buff); // LOOKUP_TABLE default
 1263          if (buff.rfind("LOOKUP_TABLE default") != 0)
 1264          {
 1265             MFEM_ABORT("Invalid LOOKUP_TABLE for material array in VTK file.");
 1266          }
 1267          cell_attributes.[Load](https://docs.mfem.org/html/classmfem_1_1Array.html#a1ed472e110a519517d0f85cbc2e55b5a)(ncells, input);
 1268          // found_material = true;
 1269          break;
 1270       }
 1271    }
 1272 
 1273    // if (!found_material)
 1274    // {
 1275    //    MFEM_WARNING("Material array not found in VTK file. "
 1276    //                 "Assuming uniform material composition.");
 1277    // }
 1278 
 1279    CreateVTKMesh(points, cell_data, cell_offsets, cell_types, cell_attributes,
 1280                  curved, read_gf, finalize_topo);
 1281 } // end ReadVTKMesh

**Comment by pazner** [comment]
I don’t believe so. Is it causing problems reading a specific mesh file?

**Comment by tarinma** [comment]
I'm wondering why "// Read the cell materials", but "buff.rfind("POINT_DATA") == 0". It seems that we want to read CELL_DATA but actually read POINT_DATA.

**Comment by tarinma** [comment]
> I don’t believe so. Is it causing problems reading a specific mesh file?

Yes. I'm reading a mesh with both POINT_DATA and CELL_DATA, but I want to know the 
 Mesh::ReadVTKMesh reads POINTS_DATA or CELL_DATA or both. So I traced back to this function to figure out what the ReadVTKMesh was doing. But I am confused about the section // Read the cell materials.

**Comment by pazner** [comment]
MFEM will read in a `CELL_DATA` field with name `material` to use for the element attributes. This field has to come before any `POINT_DATA`. The `POINT_DATA` in the mesh file will be ignored.

**Comment by tarinma** [comment]
Thank you for your explanation.

**Comment by pazner** [comment]
Closing for now. Please re-open if you run into more issues.
