### ISSUE TITLE
Basis function use Gauss-Legendre-Lobatto nodes

### ISSUE THREAD

**Issue by EMinsight** [mfem/mfem#3187]
Hello,

Does FEM support samping basis function on Gauss-Legendre-Lobatt nodes?

How can I use three one-dimensional basis functions as a set of basis functions like below? $g_i^\left(N_1\right)$ is Lagrange
interpolation polynomials.
![image](https://user-images.githubusercontent.com/3355778/188073656-a1cf882a-6770-4f03-861b-68e062f8accb.png)

Thank you!

**Comment by pazner** [comment]
When you create the finite element collection and space, you can specify the basis. The one you want is `BasisType::GaussLobatto`. This is done in example 9:
https://github.com/mfem/mfem/blob/4edfc95acc2a300ff3344b8c947bf451bdf19d5d/examples/ex9.cpp#L264-L267

**Comment by EMinsight** [comment]
Hi @pazner ,

Thanks for your answer.

I have another question. Does MFEM support using curvilinear coordinates to represent the curved elements?

**Comment by tzanio** [comment]
HI @EMinsight,

We support (arbitrary order) curved elements through isoparametric mapping. This mapping changes from element to element and is specified by the locations of the (high-order) mesh nodes.

Here for example is a 2nd order (Q2) element in 2D specified by the coordinates of its 9 nodes.

<img width="229" alt="q2" src="https://user-images.githubusercontent.com/1278247/188278349-3a1b8ed7-3052-423c-b612-ab7ccfc55dd7.png">

Hope this helps,
Tzanio

**Comment by EMinsight** [comment]
@tzanio ,

That's cool. I think MFEM can map the curved elements to the cubic elements using Gauss-Legendre-Lobatto nodes in curvilinear coordinates.

BTW, May I get the Jacobian matrix for coordinate transformation in each element?

Best,
James

**Comment by tzanio** [comment]
> May I get the Jacobian matrix for coordinate transformation in each element?

Yes, but we also have APIs at high-level where the integration, Jacobian evaluation, etc. are automatically taken care of for the user.

**Comment by EMinsight** [comment]
Does MFEM APIs use the same order for the element and basis function?  If I set the order<1 during finite element collection, the basis function order is determined by the element?

**Comment by pazner** [comment]
You can use arbitrary (and different) orders for the mesh geometry and finite element spaces, they don't need to be the same.

**Comment by EMinsight** [comment]
In the TensorBasisElement class, All tensor components share same order. Is it possible different component has different order?

**Comment by tzanio** [comment]
> Is it possible different component has different order?

No, that is not currently possible in MFEM. It could be added, but it will require some effort.

**Comment by EMinsight** [comment]
Thanks for your reply. The feature different component has different order will change many APIs. It seems a long term work. I will try myself first.

BRs
James
