### ISSUE TITLE
Weblink to METIS in INSTALL is dead (as far as I can see)

### ISSUE THREAD

**Issue by DavidLeipold** [mfem/mfem#3188]
From several computers in various networks (in germany) the link given in the INSTALL file 

- METIS (a family of multilevel partitioning algorithms)
  http://glaros.dtc.umn.edu/gkhome/metis/metis/overview

leads to nowhere.

**Comment by tzanio** [comment]
Hi @DavidLeipold,

We have a mirror here: https://github.com/mfem/tpls which you can use for now.

It looks like the METIS team is no longer supporting that (long-standing) URL and we will have to decide how to address that in MFEM.

This is not straightforward, because the relative recent GitHub version https://github.com/KarypisLab/METIS has changes that are breaking.

Tzanio

**Comment by DavidLeipold** [comment]
Hi Tzanio,
thank you for your answer. 
The mirror will work for me right now. At some point, the Install file should be updated, if some procedure is established.

Best wishes,
David

**Comment by tzanio** [comment]
We discussed this yesterday and decided to update all docs to point to our mirror.

I will do so today.

**Comment by sshiraiwa** [comment]
Hi @tzanio. Can you explain me "changes that are breaking"? In Python wrapper setup.py, I use  https://github.com/KarypisLab/METIS  and points to specific SHAs as follows. 
```
       "gklib": "a7f8172703cf6e999dd0710eb279bba513da4fec",
       "metis": "94c03a6e2d1860128c2d0675cbbb86ad4f261256"
```
It passes all examples (both C++ and Python wrapped versions). But, do you think it is not a good choice?

**Comment by tzanio** [comment]
Hi @sshiraiwa, see the discussion here: https://github.com/mfem/mfem/issues/698.

We didn't feel that https://github.com/KarypisLab/METIS is ready for prime time, and unfortunately old/stable versions don't seem to be available anywhere.

**Comment by tzanio** [comment]
Discussion continued in #3196
