### ISSUE TITLE
Compute parallel vector norm

### ISSUE THREAD

**Issue by jchan192** [mfem/mfem#3189]
Hi MFEM community,

I am trying to compute the relative error which || U - c|| / || c ||.
Assuming U and c are vectors, in MFEM I can do the following

```
subtract(c,U,res);
err = res.Norml2()/c.Norml2();
 std::cout << " err=" << err <<"\n";
```
The above code does work when using 1 core,
but when multiple cores are used, different `err` are printed out from different proccesses, where I expect them to be the same.

I think I am missing something simple here, but what would you recommend in order to compute the relative error in parallel runs. 
Thank you for the help

**Comment by vladotomov** [comment]
`Vector::Norml2()` is a serial function, try with `inline double InnerProduct(MPI_Comm comm, const Vector &x, const Vector &y)` from `vector.hpp`, or do the reductions yourself.

Or if these are `ParGridFunctions` you can use `ComputeLpError`.
