### ISSUE TITLE
When mfem is linked with superlu-dist mfem installs an invalid MFEMConfig.cmake file

### ISSUE THREAD

**Issue by yurivict** [mfem/mfem#3191]
It has the line:
```
set(MFEM_INCLUDE_DIRS "${PACKAGE_PREFIX_DIR}/include;/usr/local/include;/usr/local/include/superlu")
```
with the directory ```/usr/local/include/superlu``` that doesn't exist.

mfem-4.4
superlu-dist-8.1.0
clang-14
FreeBSD 13.1

**Comment by v-dobrev** [comment]
I'm unable to reproduce this issue. What does the CMake output line containing `SuperLUDist_INCLUDE_DIRS` look like in your case?

**Comment by yurivict** [comment]
not stale
