### ISSUE TITLE
Parallel Build of MFEM fails in Ubuntu 22.04.1 LTS

### ISSUE THREAD

**Issue by ricgross** [mfem/mfem#3192]
Hi!

I am moving my first steps within MFEM, and I have encountered a build problem with Ubuntu 22.04.1 LTS (note that I'm running the OS on a virtual machine, in case it has any relevance).  I have successfully managed to build the serial version of MFEM (and GLVis), as well as running the example codes. However, if I follow the parallel build instructions provided in the documentation, i.e.
```
cd mfem-4.4 
make parallel -j 4
```
The following processes and errors appear in the Linux terminal:
   
```
...
In file included from fem/../linalg/../general/mem_manager.hpp:16:0,
                 from fem/../linalg/../general/array.hpp:16,
                 from fem/../linalg/vector.hpp:15,
                 from fem/../linalg/operator.hpp:15,
                 from fem/restriction.hpp:15,
                 from fem/prestriction.cpp:16:
fem/prestriction.cpp: In member function 'void mfem::ParNCL2FaceRestriction::ComputeScatterIndicesAndOffsets(mfem::ElementDofOrdering, mfem::FaceType)':
fem/prestriction.cpp:1034:66: error: could not convert '(mfem::FaceType)type' from 'mfem::FaceType' to 'bool'
                (type==FaceType::Interior? "interior" : "boundary") <<
                                                                  ^
fem/../linalg/../general/error.hpp:88:24: note: in definition of macro '_MFEM_MESSAGE'
       mfemMsgStream << msg << MFEM_LOCATION;                            \
                        ^
fem/prestriction.cpp:1033:4: note: in expansion of macro 'MFEM_VERIFY'
    MFEM_VERIFY(f_ind==nf, "Unexpected number of " <<
    ^
fem/prestriction.cpp: In member function 'void mfem::ParNCL2FaceRestriction::ComputeGatherIndices(mfem::ElementDofOrdering, mfem::FaceType)':
fem/prestriction.cpp:1077:66: error: could not convert '(mfem::FaceType)type' from 'mfem::FaceType' to 'bool'
                (type==FaceType::Interior? "interior" : "boundary") <<
                                                                  ^
fem/../linalg/../general/error.hpp:88:24: note: in definition of macro '_MFEM_MESSAGE'
       mfemMsgStream << msg << MFEM_LOCATION;                            \
                        ^
fem/prestriction.cpp:1076:4: note: in expansion of macro 'MFEM_VERIFY'
    MFEM_VERIFY(f_ind==nf, "Unexpected number of " <<
    ^
make[1]: *** [makefile:438: fem/prestriction.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/riccardo/MFEM/mfem-4.4'
make: *** [makefile:480: parallel] Error 2
```
Note that I am using HYPRE 2.25.0 and METIS 4.0.3. 

Any suggestions on how I could solve the issue?

In advance, thanks!

**Comment by camierjs** [comment]
Hi @ricgross,

Thank you for reporting this issue you are encounting.

Could you try to add some parenthesis around the ternary operator in fem/prestriction.cpp:1034:
`(type==FaceType::Interior? "interior" : "boundary")` => `((type==FaceType::Interior)? "interior" : "boundary")`.

Can you tell us also with which compiler you are working with?

**Comment by ricgross** [comment]
Hi @camierjs 

Thank you for your prompt reply. I have tried to add the parentheses around the ternary operator, but the terminal shows me the same error messages.

In terms of compiler, I am using the following:
```
riccardo@riccardo-mfem:~/MFEM/mfem-4.4$ mpicxx --version
g++-5 (Homebrew GCC 5.5.0_8) 5.5.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by camierjs** [comment]
Just to double-check, is the error on the same line, or on line `1077`?
There is another such ternary operator that could trigger the same error.

**Comment by tzanio** [comment]
Hi @ricgross, two questions:

1. Can you try newer version of gcc, we've had issues with some older compilers in the past.
2. Can you try older versions of mfem, e.g. mfem-4.3 or mfem-4.0?

**Comment by ricgross** [comment]
Hi @tzanio 

Thank you for your reply. 

I managed to build and compile the parallel version of MFEM thanks to your suggestion of trying a newer version of gcc. It turns out that HOMEBREW (which I used to install the open-mpi package) had set g++ 5 as its default compiler for open-mpi.
By switching to g++ 11, the issue disappeared.

Thank you very much!
