### ISSUE TITLE
Parallel runing the examples  wrong

### ISSUE THREAD

**Issue by utah2015** [mfem/mfem#3197]
Hi,
   I am using mfem-4.4 with HYPRE 2.25.0. When I was testing the examples the errors occured as the following,
   
    
![image](https://user-images.githubusercontent.com/113109669/189118811-38c8d226-48b7-4f24-b8ef-eb5f9471bbca.png)

I checked  hypre, the same error occured when I test the hypre examples.
Any suggestions on how I solve the problem?
Thanks!

**Comment by utah2015** [comment]
I debug the code and find the error occurs at ex1p:HYPRE_BigInt size = fespace.GlobalTrueVSize();->pfespace: P = new HypreParMatrix->hypre:hypre_CSRMatrixSetDataOwner(A->offd,0)
![image](https://user-images.githubusercontent.com/113109669/189264137-bed7e140-6eac-4090-8f53-a6ae91693ce3.png)

**Comment by tzanio** [comment]
Hi @utah2015,

Thank you for reporting this.

I tried fresh builds with `mfem-4.4`, `hypre-2.25.0` and `metis-4.0` and I can't reproduce it.

Can you provide more details about your case: what os, compiler and build commands did you use exactly?

Cheers,
Tzanio

**Comment by utah2015** [comment]
@tzanio 
Thanks for your reply. 
I have fixed the problem by configuring hypre with intel compiler like this :

./configure --disable-fortran --prefix="/usr/local/bin" CC=/opt/intel/compilers_and_libraries_2018.3.222/linux/bin/intel64/icc  CXX=/opt/intel/compilers_and_libraries_2018.3.222/linux/bin\intel64/icpc
