### ISSUE TITLE
Open out of source build failing 

### ISSUE THREAD

**Issue by jcwright77** [mfem/mfem#3198]
on centos 7 with icc 2020

When building out of source using either option in the INSTALL.md file, I find certain paths do no get properly sent resulting in certain includes not being found.

does not set MFEM_BUILD_DIR used to find mfem includes,
    MFEM_INSTALL_DIR is set though. MFEM_INC should probably be using this
    _config.hpp is included but no include path is provided.
    MFEM_BUILD_DIR defaults to ../.. by rule MFEM_BUILD_DIR ?= ../.. in subdir makefiles

    maybe make BUILD_DIR=<mfem-build-dir> config works better?

This has been shown through 'make info' and well as observing builds. the mfem library builds, this seems mainly an issue with other targets.

**Comment by jcwright77** [comment]
Seems to be fixed by the following lines in user.mk in the build dir:

MFEM_INC_DIR  = $(MFEM_INSTALL_DIR)/include
MFEM_BUILD_DIR  = $(MFEM_INSTALL_DIR)/../
MFEM_INCFLAGS  = -I$(MFEM_INC_DIR) $(MFEM_TPLFLAGS) -I$(MFEM_INSTALL_DIR)/../config/

Note using the MFEM_INSTALL_DIR to point to config dir is fragiile and will break if the install dir in not in the build dir top level. But unfortunately the CONFIG_MK and BUILD_REAL_DIR doesnt keep its value in recursive defs.

**Comment by jcwright77** [comment]
any ideas? This seems to be a fundamental issue with the makefile setup. Hard to believe this would not be an issue for everyone using the make out of source build?? It can be tested very easily with "make info" w.o even doing a build to verify certain paths like to the include config directory are not being set.

**Comment by tzanio** [comment]
Hi @jcwright77,

Do I understand correctly that you run into problems with an out-of-source build?

As described in the [INSTALL file](https://github.com/mfem/mfem/blob/master/INSTALL#L150-L159) there are two ways to do that:

```
   mkdir <mfem-build-dir> ; cd <mfem-build-dir>
   make -f <mfem-source-dir>/makefile config [OPTIONS] ...
   make
```

or

```
   cd <mfem-source-dir>
   make BUILD_DIR=<mfem-build-dir> config [OPTIONS] ...
   cd <mfem-build-dir>
   make
```

I believe both of them should work. Is that not the case?

Tzanio

**Comment by jcwright77** [comment]
Both have the same problem. MFEM build but the miniapps fail. The issue is as described above MFEM_BUILD_DIR is not defined and many paths depend on it in the miniapps.

**Comment by tzanio** [comment]
Hi @jcwright77,

Can you post all the steps in your build including the mfem version/branch and the specific miniapps?

For example the following works fine for me:

```
git clone git@github.com:mfem/mfem.git
cd mfem
mkdir build
make BUILD_DIR=build config
cd build
make -j12
make test-miniapps
```

**Comment by jcwright77** [comment]
ok was doing this now. note this I guess is a serial compile.

**Comment by tzanio** [comment]
>  this I guess is a serial compile

the parallel build works for me too

**Comment by jcwright77** [comment]
unrelated, but can the serial and parallel builds coexist in a single build directory?

**Comment by v-dobrev** [comment]
> unrelated, but can the serial and parallel builds coexist in a single build directory?

No. Different configurations should be built in different directories in order to coexist.

**Comment by v-dobrev** [comment]
> and what is the difference between
> make MFEM_USE_MPI=YES
> and
> make parallel
> ?

The command `make parallel` calls `make config` with `MFEM_USE_MPI=YES` and `MFEM_DEBUG=NO` while also passing down any additional command line settings given to `make parallel`. After `make config ...` it also calls `make ...` to build the library.

On the other hand `make MFEM_USE_MPI=YES` just tries to build the library with the current configuration (i.e. it assumes `make config ...` has already been called) while explicitly overriding the setting for `MFEM_USE_MPI` (stored in the config make file `config/config.mk` and the generated include file `config/_config.hpp`) which may lead to issues if the current configuration was different.

One can check the current configuration with `make info`. Running `make config ...` again will override the existing configuration without using any on the options set in the current configuration, using built-in default values instead.

Note also that settings from `config/user.mk` will always be used by `make config ...` as long as that file exists in the build tree. Alternative location and filename can be set on the `make config ...` command line with `USER_CONFIG=/path/to/my/user.mk`.

**Comment by jcwright77** [comment]
Note I realized this build was in a recent branch and  not in master, though I don't believe there are any changes relative to master in the  build process. Tzanio's instructions result in use of the gnu compiler, mpicxx, not the intel compiler. Even so, this fails in the mini apps build:

git checkout master
git pull
mkdir master
make BUILD_DIR=master config
cd master
make -j12 parallel MFEM_USE_METIS5=YES
# Succeeds, as it did for my build before that include MUMPS and SuperLU
make test-miniapps
# FAILS in volta miniapp build.
mpicxx -O3 -std=c++11 -I../.. -I/nfs/software001/home/software/psfc/pkg/mfem/mfem/../hypre/src/hypre/include -I/nfs/software001/home/software/psfc/pkg/mfem/mfem/../metis-5.0/include -o volta volta.o volta_solver.o -L../../miniapps/common -lmfem-common  \
  -L../.. -lmfem -L/nfs/software001/home/software/psfc/pkg/mfem/mfem/../hypre/src/hypre/lib -lHYPRE -L/nfs/software001/home/software/psfc/pkg/mfem/mfem/../metis-5.0/lib -lmetis -lrt
/nfs/software001/home/software/psfc/pkg/mfem/mfem/../metis-5.0/lib/libmetis.so: undefined reference to `gk_randint32'

So in this case a simple problem, it does not link in the metis5 dependency of GKlib. Perhaps it assumes a static build of libmetis/libparmetis? Redoing above after manually adding -lGKlib to library list in config/config.mk . Hmm ok that doesn't transfer to the build and there seems no way to specify METIS libraries directly, so one had to define all of MFEM_EXT_LIBS.


I wonder how you got this to work? was your metis library static?

note the parallel build assumes hypre src tree is in ../hypre rather than an install directory. IE  it looks for ../hypre/src/hypre/lib instead of ../hypre/lib

**Comment by v-dobrev** [comment]
This looks like an issue with the METIS 5 build. Are you using METIS from https://github.com/KarypisLab/METIS? This new repo does not work out-of-the-box with the default settings for METIS in MFEM (the variables `METIS_OPT` and `METIS_LIB`) -- probably one has to add the link flags for `libgk*` to `METIS_LIB`.

Since the original METIS webpage has now been down for some time, we have a mirror of the original v5.1 tarballs at https://github.com/mfem/tpls -- using these should work "out-of-the-box" as described here: https://mfem.org/building/#parallel-build-using-metis-5.

Regarding HYPRE: yes, the default assumption in the MFEM GNU make build system is that HYPRE is used from its build tree. If that is not the case, you can set `HYPRE_DIR` to be the HYPRE install dir which should contain `include` and `lib` subdirectories. Alternatively, can set directly the variables `HYPRE_OPT` (compile options, typically `-I...` flags) and `HYPRE_LIB` (link options, typically `-L...` and `-l...` flags).

**Comment by v-dobrev** [comment]
Note that to modify the values of variables like `METIS_LIB`, one has to set their content either in `config/user.mk` in the build tree or on the `make config ...` command line.  In your case above, this config call is done when you call `make parallel ...`, so you can add it to that command line: `make parallel METIS_LIB="..." ...`, if you prefer to not use the `config/user.mk` file.

**Comment by jcwright77** [comment]
For GKlib (horrible name choice by the way, I realize its not your choice), I do what you mention, set METIS_LIB is user.mk.  But user.mk has lots of other logic and I was trying to do the simplest possible build so see if it would work. 

For hypre, I just made a soft link from the expected path to my original build try - though this is fragile should I build a new version from that directory. I will just set  HYPRE_DIR (as I did when using user.mk, but of course the same concerns about what triggered the original error apply)

Thanks for all the help and testing the builds. I can see that your successful builds were  not using metis5 ? I see your build instructions for metis5 do indeed build a static version to avoid the GKlib dependency when building mfem.

Regarding MPI vs parallel, yes I indeed use user.mk and set USE_MPI to YES. And so make info does show MPI on. Nevertheless, make parallel seems to build additional files even though make was run with MPI set on in user.mk after make config was run. I'll have to look closer at what is being done differently. But I have to say haveing the MPI flag and the paralle target is very confusing. I had assumed the 'make' with the MFEM_USE_MPI=YES in user.mk was indeed a parallel build. It seems from  your comments above, this should actually be the case and that 'make parallel' is just a convenience target. Looking at the target in the makefile confirms this. I'll have to see again why after a successful build with MPI=YES in user.mk, make parallel builds more.

**Comment by v-dobrev** [comment]
Maybe it looks like `make parallel ...` builds more because of the following:

Note that `make parallel ...` calls `make config ...` which will always update the configuration files and that, in turn, forces a rebuild of the library by design -- all object files are defined to depend on the generated file `config/config.mk` to enable this behavior.

**Comment by jcwright77** [comment]
Makes sense.
On Fri, September 9, 2022 10:43 pm, Veselin Dobrev wrote:
> Maybe it looks like `make parallel ...` builds more because of the following:
>
> Note that `make parallel ...` calls `make config ...` which will always update
> the configuration files and that, in turn, forces a rebuild of the library by
> design -- all object files are defined to depend on the generated file
> `config/config.mk` to enable this behavior.
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/mfem/mfem/issues/3198#issuecomment-1242600282
> You are receiving this because you were mentioned.
>
> Message ID: ***@***.***>


-- 
Principal Research Scientist John Wright
Office 617-253-9612
zoom: https://mit.zoom.us/my/jcwright

**Comment by jcwright77** [comment]
OK I'll try that. I hadn't realized before that would work since METIS_LIB is
only used in config/default.mk in the main distribution or config/user.mk in
the build directory and it is not referenced in config/config.mk in the build
tree. So I assumed it was just internal usage and wouldn't do anything without
user.mk present.

On Fri, September 9, 2022 10:20 pm, Veselin Dobrev wrote:
> Note that to modify the values of variables like `METIS_LIB`, one has to set
> their content either in `config/user.mk` in the build tree or on the `make
> config ...` command line.  In your case above, this config call is done when
> you call `make parallel ...`, so you can add it to that command line: `make
> parallel METIS_LIB="..." ...`, if you prefer to not use the `config/user.mk`
> file.
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/mfem/mfem/issues/3198#issuecomment-1242597232
> You are receiving this because you were mentioned.
>
> Message ID: ***@***.***>


-- 
Principal Research Scientist John Wright
Office 617-253-9612
zoom: https://mit.zoom.us/my/jcwright

**Comment by tzanio** [comment]
@jcwright77, were you able to resolve this?

**Comment by jcwright77** [comment]
Yes. Build issues for miniapps are resolved by using mfem distributed metis which eliminates external GKlib linkage. This should be put in the README.md of the distribution. 

thanks.

**Comment by tzanio** [comment]
We just added this to `INSTALL`: https://github.com/mfem/mfem/blob/master/INSTALL#L18-L23 and will modify the website accordingly.

**Comment by jcwright77** [comment]
Thanks,
I relied on the INSTALL in the source distribution which is quite helpful. May
I suggest mentioning https://mfem.org/building/ in the INSTALL as well which
has some more detailed build instructions for a vanilla build.

thanks for the help,
-john

On Sun, September 18, 2022 5:13 pm, Tzanio Kolev wrote:
> We just added this to `INSTALL`:
> https://github.com/mfem/mfem/blob/master/INSTALL#L18-L23 and will modify the
> website accordingly.
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/mfem/mfem/issues/3198#issuecomment-1250388166
> You are receiving this because you were mentioned.
>
> Message ID: ***@***.***>


-- 
Principal Research Scientist John Wright
Office 617-253-9612
zoom: https://mit.zoom.us/my/jcwright

**Comment by tzanio** [comment]
> May I suggest mentioning https://mfem.org/building/ in the INSTALL as well which has some more detailed build instructions for a vanilla build.

Done in https://github.com/mfem/mfem/pull/3199/commits/ae597b46a04a43cf684996bcb7fc076bfac9e5b5.

I will update [mfem.org/building/](https://mfem.org/building/) later this week.
