### ISSUE TITLE
Propose moving mfem repo to llnl organization

### ISSUE THREAD

**Issue by IanLee1521** [mfem/mfem#32]
Hi @tzanio --  I'd like to propose moving the MFEM organization into the [LLNL](https://github.com/llnl) organization. I can create an mfem team for you there to duplicate the mfem organization access.

Additionally, GitHub will handle page redirects from the old organization to the new if we do it as a transfer of the repositories.

Thoughts? Concerns?

**Comment by tzanio** [comment]
Moving this discussion to internal email.
