### ISSUE TITLE
Add codespell as a github action

### ISSUE THREAD

**Issue by luzpaz** [mfem/mfem#3203]
> Thanks again @luzpaz! If you can help us with adding this as an action in `.github/workflows/repo-check.yml`, we will appreciate it.

_Originally posted by @tzanio in https://github.com/mfem/mfem/issues/3134#issuecomment-1242236631_

https://github.com/codespell-project/actions-codespell

**Comment by luzpaz** [comment]
@tzanio there should be a streamlined way to do this through github, see [codespell-project/actions-codespell](https://github.com/codespell-project/actions-codespell)

![image](https://user-images.githubusercontent.com/4140247/189486736-aa4c7f88-c545-4c55-b005-e84ff19bf108.png)

**Comment by tzanio** [comment]
I tried the above ☝️ quickly in #3205, but it doesn't seem to work.

@luzpaz, any ideas what is wrong?

**Comment by v-dobrev** [comment]
Discussion continued in #3205.
