### ISSUE TITLE
Convergence study for complex geometry

### ISSUE THREAD

**Issue by karthichockalingam** [mfem/mfem#3209]
Hello,

I would like to study the convergence order for h and p refinement for linear elasticity problem with a complex geometry. 
I want to take the solution obtained from using a highly refined mesh as the benchmark solution to study the convergence order. 

From the below link 
https://github.com/mfem/mfem/blob/atpesc-dev/examples/atpesc/mfem/convergence.cpp
I understand how to performance convergence analysis provided there is an analytical solution.

But here I basically want to read the solutions obtained using two different meshes to compute the L2 and H1 error norm.

I am relatively new to mfem, if there is an existing example or a sample code, from which I can build on that would be great.

Thank you.

**Comment by psocratis** [comment]
@karthichockalingam, 

One way you can do this is to prolong your current solution to the highly refined mesh and compute the error there. 
As long as the highly refined mesh can be obtained by refining the current mesh (the one where you solve the problem) then this should be relatively straightforward. 

I hope this helps.

Best,

Socratis

**Comment by vladotomov** [comment]
For general meshes see `/miniapps/gslib/field-diff.cpp`.

**Comment by karthichockalingam** [comment]
@psocratis,

Thank you for your response. This is precisely what I want to accomplish. I have the solution from the highly refined mesh (which was obtained by refining the current mesh). Now, I have solutions from two difference meshes, the highly refined one and the other coarse mesh, for which I want to compute the L2 and H1 error norm. 

You mentioned once I have those two solutions (which I do), it would be relatively straight forward to compute the error. How I proceed next?

**Comment by karthichockalingam** [comment]
@psocratis,

Continuing from a earlier message:

**Comment by karthichockalingam** [comment]
@psocratis Sorry, by mistake I closed the issue:

I tried the following to pass the solution of coarse problem (order 1 polynomial) on the current mesh

```
    ifstream mat_stream_1(sltn_file_1);
    GridFunction coarse_function(&coarse_mesh, mat_stream_1);
  
   VectorGridFunctionCoefficient CoarseMeshSol(&coarse_function);
   double error = x.ComputeL2Error(CoarseMeshSol);
```

while trying to solve for the order 4 polynomial problem to compute the L2 error

```
double GridFunction::ComputeL2Error(
   VectorCoefficient &exsol, const IntegrationRule *irs[],
   const Array<int> *elems) const
{
   double error = 0.0;
   const FiniteElement *fe;
   ElementTransformation *T;
   DenseMatrix vals, exact_vals;
   Vector loc_errs;

   for (int i = 0; i < fes->GetNE(); i++)
   {
      if (elems != NULL && (*elems)[i] == 0) { continue; }
      fe = fes->GetFE(i);
      int intorder = 2*fe->GetOrder() + 3; // <----------
      const IntegrationRule *ir;
      if (irs)
      {
         ir = irs[fe->GetGeomType()];
      }
      else
      {
         ir = &(IntRules.Get(fe->GetGeomType(), intorder));
      }
      T = fes->GetElementTransformation(i);
      GetVectorValues(*T, *ir, vals);
      exsol.Eval(exact_vals, *T, *ir);
      vals -= exact_vals;
      loc_errs.SetSize(vals.Width());
      vals.Norm2(loc_errs);
      for (int j = 0; j < ir->GetNPoints(); j++)
      {
         const IntegrationPoint &ip = ir->IntPoint(j);
         T->SetIntPoint(&ip);
         error += ip.weight * T->Weight() * (loc_errs(j) * loc_errs(j));
      }
   }
```
But it failed with following error
```
Verification failed: (GetLastOperation() == Mesh::REFINE) is false:
 --> 
 ... in function: const mfem::CoarseFineTransformations& mfem::Mesh::GetRefinementTransforms()
 ... in file: mesh/mesh.cpp:9871
```

Can you please help me to compute the L2 error for polynomial order 1  while keeping solution of the polynomial order 4 as the  highly refined mesh?

Many thanks!

**Comment by karthichockalingam** [comment]
@vladotomov thank you for your response. It was definitely useful but it didn't provide a path to compute the L2 error. Can you please elaborate? 
/miniapps/gslib/field-diff.cpp was only diffing the solution and projecting onto the higher order polynomial.

**Comment by psocratis** [comment]
@karthichockalingam, 

Given the 2 `FiniteElementSpace`s, say `fespace_order1` and `fespace_order4` which are defined on the SAME mesh, you can get the prolongation operator by 
````cpp
 PRefinementOperator P(fespace_order1, fespace_order4)
````
Then you can prolong your low order solution to the high order space by applying P, i.e, 
````cpp 
  P.Mult(coarse_function, prolonged_coarse_function)
````

Now both GridFunctions are defined on the high order space and you can compute the error either by subtracting the dofs and calculating the norm of the difference or by declaring a `GridFunctionCoefficient` (say ho_gf_cf) with the original high-order solution and calling
````cpp
  prolonged_coarse_function.ComputeL2Error(ho_gf_cf)
````

Best,

Socratis

**Comment by karthichockalingam** [comment]
@psocratis I tried your suggestion but could not find `PRefinementOperator` instead used `PRefinementTransferOperator`. I copied the relevant pieces of code here for your reference. 

```
Mesh *mesh_higher_order = new Mesh(higher_order_mesh_file, 1, 1, false);
Mesh *mesh = new Mesh(mesh_file, 1, 1);

ParMesh *pmesh = new ParMesh(MPI_COMM_WORLD, *mesh);
ParMesh *hmesh = new ParMesh(MPI_COMM_WORLD, *mesh);
delete mesh;

FiniteElementCollection *fec, *higher_order_fec;
ParFiniteElementSpace *fespace, *higher_order_fespace;

fec = new H1_FECollection(order, dim);
higher_order_fec = new H1_FECollection(higher_order, dim);

fespace = new ParFiniteElementSpace(pmesh, fec, dim, Ordering::byVDIM);
higher_order_fespace = new ParFiniteElementSpace(hmesh, higher_order_fec, dim, Ordering::byVDIM);

. . . .

a->RecoverFEMSolution(X, *b, x);

PRefinementTransferOperator P(*fespace, *higher_order_fespace);
GridFunction prolonged_coarse_function(higher_order_fespace);
P.Mult(x, prolonged_coarse_function);

ifstream mat_stream(solution_file);

GridFunction solution_function(mesh_higher_order, mat_stream);
GridFunctionCoefficient MeshSol(&solution_function);

double error = prolonged_coarse_function.ComputeL2Error(MeshSol);
```

I believe `prolonged_coarse_function.ComputeL2Error(MeshSol)` threw the below error

```
Verification failed: (GetLastOperation() == Mesh::REFINE) is false:
 --> 
 ... in function: const mfem::CoarseFineTransformations& mfem::Mesh::GetRefinementTransforms()
 ... in file: mesh/mesh.cpp:9871
```

The program was run using the following command

```
./ex2p_plate_prolongation_error -m plateandhole.msh  -s2 h0_p4_sol.000000 -m2 h0_p4_mesh.000000
```
Below you can locate the files if you wanted to reproduce the error

[source code](https://github.com/karthichockalingam/mfem-linear-elasticity/blob/main/prolongation/ex2p_plate_prolongation_error.cpp)
[base mesh](https://github.com/karthichockalingam/mfem-linear-elasticity/blob/main/prolongation/plateandhole.msh)
[higher order solution](https://github.com/karthichockalingam/mfem-linear-elasticity/blob/main/prolongation/h0_p4_sol.000000)
[higher order mesh](https://github.com/karthichockalingam/mfem-linear-elasticity/blob/main/prolongation/h0_p4_mesh.000000)

I guess `GridFunction solution_function(mesh_higher_order, mat_stream)` is the right way to copy the solution into a GridFunction. I am not sure if the problem is related to the issue [3181](https://github.com/mfem/mfem/issues/3181)

Please let me know how I may resolve the issue. Many thanks.

**Comment by psocratis** [comment]
@karthichockalingam, 

Is  the high-order mesh different than the mesh? If they are the same and only the `FiniteElementSpace` is different then you should use a single mesh. The `PRefinementTransferOperator` assumes that the underlying mesh of the two FiniteElementSpaces is the same. I believe the error you see is because the 2 mesh pointers, one from the `GridFunctionCoefficient` and one from the `GridFunction` are not the same, and in that case the `GridFunctionCoefficient::Eval` assumes a Low-Order-Refined setting which is not relevant to your case. See https://github.com/mfem/mfem/blob/361c32362bff4bdcf570c420a3113c0cdb7bad55/fem/coefficient.cpp#L122-L136

Best,

Socratis

**Comment by karthichockalingam** [comment]
@psocratis, 

I believe higher-order mesh and mesh is different because the former has more nodes. The grid is essentially the SAME if that makes sense. 

The FiniteElementSpace is only different by order. For example both the below commands are equivalent. 

```
./ex2p_plate_prolongation_error -m plateandhole.msh  -s2 h0_p4_sol.000000 -m2 h0_p4_mesh.000000
```

```
./ex2p_plate_prolongation_error -m h0_p1_mesh.000000  -s2 h0_p4_sol.000000 -m2 h0_p4_mesh.000000 
```

The input mesh file is essentially `h0_p1_mesh.000000`. I pass `h0_p4_sol.000000 -m2` and `h0_p4_mesh.000000` just to construct the higher order solution `ho_gf_cf` for computing the L2 error.

When you say that `GridFunction ` and `GridFunctionCoefficient` are pointing to two different meshes - 

```
prolonged_coarse_function.ComputeL2Error(ho_gf_cf)
```
are you referring to `prolonged_coarse_function` and `ho_gf_cf`?

The former is constructed as  `GridFunction prolonged_coarse_function(higher_order_fespace).

How is `ho_gf_cf` constructed? Does it not use the higher order mesh i.e. the mesh that has more nodes than the order one mesh? 

Thank you again!

**Comment by psocratis** [comment]
@karthichockalingam, 
You don't really need the high-order mesh, (unless you want to account for the errors from the mesh approximation). You can have a high-order FEspace defined on the low-order (linear) mesh. You can basically use one single mesh, but 2 FiniteElementSpaces one low and one high-order. This way the L2Error computation will go through. 

If you really want to use 2 different meshes, you would need to construct the map from 1 mesh to the other. 

Best,

Socratis

**Comment by karthichockalingam** [comment]
@psocratis,

Thank you. I have it working in serial.

https://github.com/karthichockalingam/mfem-linear-elasticity/blob/7860e536e291b5ca2c76f1378f22c13fcc015165/ex2p_multi_geom.cpp#L360-L370

It is not working in parallel - maybe because I am not reading in the solution to construct `ho_gf` correctly?

I would like to study L2 error for h-refinement. Now, I will be dealing with two different meshes of the same order. How should I proceed?

Cheers!

**Comment by psocratis** [comment]
@karthichockalingam, 

You will need to compute and save (or compose together) the h-refinement transfer operators for each refinement step. I am attaching an implementation that would compute the error with respect to both order and mesh refinement for Ex1p. This computed the reference solutions along with the solution on the mesh of interest., it's not reading from a file. If you want to read it from a file make sure you use the same mpi-partitioning for all the solutions.

[reference_error.txt](https://github.com/mfem/mfem/files/9587047/reference_error.txt)

Best,

Socratis

**Comment by karthichockalingam** [comment]
@psocratis,

The p-refinement analysis worked out fine (even running parallel) but I have trouble understanding h-refinement.  From the below code, I understand `refinement_mesh` is uniformly refined three times (l=0, l=1 & l=2) on top of pmesh (l=0). 

(1) Is 'Th' some transfer operation from l=1 to l=2, since `refined_pmesh_copy` is uniformly refined at the end of the loop?

```
   for (int l = 0; l < 3; l++)
   {
      refined_pmesh.UniformRefinement();
      refined_fes.Update();
      OperatorHandle Op;
      refined_fes.GetTransferOperator(refined_fes_copy,Op);
      if (l==0)
      {
         Th = new SparseMatrix(*Op.As<SparseMatrix>());
      }
      else
      {
         T = Th;
         Th = Mult(*Op.As<SparseMatrix>(),*T);
         delete T; T = nullptr;
      } 
      if (l == l-1 )
      {
         if (T) Th = T;
         break;
      }
     refined_pmesh_copy.UniformRefinement();
     refined_fes_copy.Update();
   }
```

If I comment out the below two lines, I get segmentation fault:
```
     refined_pmesh_copy.UniformRefinement();
     refined_fes_copy.Update();
```

(2) Am I right in saying `ref_error` is between l=0 to l=2, since `x` is a solution corresponding to pmesh (l=0)? So, I don't quite understand the role of Th which is from l=1 to l=2.

```
   ParGridFunction Thx(&refined_fes);

   Th->Mult(x,Thx);
   Tp.Mult(x,Tpx);

   GridFunctionCoefficient refined_x_cf(&refined_x);
   double ref_error = Thx.ComputeL2Error(refined_x_cf);
```

(3) I feel `refined_mesh` is inextricably linked to `pmesh`. Lets say, I refine for 5 h-levels - I set 'l=5' in the for loop to get `refined_mesh` uniformly refined 5 times. But I am not quite sure how do I go about increasing my refinement levels on `pmesh` up to 5 to see if my error convergences to ZERO?

Many thanks for your help.

**Comment by psocratis** [comment]
@karthichockalingam,

 I am using the `refined_pmesh copy` to compute the prolongation operator at each level, and I combine (multiply) all the prolongations together to get the prolongation from the coarse mesh to the last mesh (after 3 levels). MFEM can't compute the prolongation between more than one consecutive refinement at once. So the `refined_pmesh_copy` is a mesh that "follows" the refined mesh (it's always one level behind) so that I can compute the 1-level transfer. 

Is this a bit more clear?

**Comment by karthichockalingam** [comment]
@psocratis, 

Yes, now it is clear to me.

I made some minor changes to the code. Now, `refined_mesh` is a copy of `mesh` instead of `pmesh`. That way refinement levels on `pmesh` and `refined_mesh` are independent of each other.

Now all three problems are solving exactly the same problem - the l2 error for p-refinemnt goes to zero but for h-refinement it does not? 
```
./reference_error -o 1 -ho 1 -ref 3 -hr 3
```
[reference_error.txt](https://github.com/mfem/mfem/files/9601214/reference_error.txt)

Thank you.

**Comment by karthichockalingam** [comment]
@psocratis,

I realised the mistake I was making. In order to handle same h-level transfer I made the following modification and it works when `Th` is pointing to `null`:

```
   if (Th)
      Th->Mult(x,Thx);
   else
   {
      IdentityOperator *I = new IdentityOperator(refinedsize);
      I->Mult(x,Thx);
   }
```

But is there a better way to struct an identity matrix using SparseMatrix type instead? 

Moreover what does below lines in your code achieve - perhaps there is a mistake?
```
      if (l == l-1 )
      {
         if (T) Th = T;
         break;
      }
```

Thank you.

**Comment by nmnobre** [comment]
> @psocratis,
> 
> I realised the mistake I was making. In order to handle same h-level transfer I made the following modification and it works when `Th` is pointing to `null`:
> 
> ```
>    if (Th)
>       Th->Mult(x,Thx);
>    else
>    {
>       IdentityOperator *I = new IdentityOperator(refinedsize);
>       I->Mult(x,Thx);
>    }
> ```
> 
> But is there a better way to struct an identity matrix using SparseMatrix type instead?
> 

Just to clarify, we realise the identity operator is redundant here and we could just as well have computed the error directly on `x` as `double ref_error = x.ComputeL2Error(refined_x_cf);` but that would have required the if statement anyway. Ideally we'd like to initialise `Thx` to the identity operator, also avoiding the if statement on the refinement loop.

**Comment by psocratis** [comment]
@karthichockalingam, 

yes `if (T) Th = T;` is probably some leftover from a previous attempt of mine. In the above implementation, it's never true so you can remove it. As far as the identity matrix you can construct an Identity `SparseMatrix` manually by just setting its diagonal entries manually, however, I don't see why you want to compute errors on the same level. The error would just be zero. 

Best, 

Socratis

**Comment by karthichockalingam** [comment]
@psocratis Thank you for your help. The issue is resolved.
