### ISSUE TITLE
How to figure out if a FiniteElementCollection is a trace collection

### ISSUE THREAD

**Issue by thorvath12** [mfem/mfem#3211]
Hello,

In #303, I updated how I eliminate the boundary conditions for HDG. I created a `ProjectCoefficientSkeleton` function in the `GridFunction` class. It is very similar to `ProjectCoefficient` except that it loops over the faces of the mesh and not the elements. I would like to combine the two functions, but in order to do that, I would need to know if a `FiniteElementCollection` is a trace collection (`DG_Interface_FECollection` or `H1_Trace_FECollection`) or not. Is there any way to figure it out? I do not see any options.

For me, it would make sense to add a `bool IsTrace()` function to the `FiniteElementCollection` class. What do you think?

Thank you in advance!

Best,
Tamas

**Comment by psocratis** [comment]
@thorvath12, 

One way would be to cast the `FiniteElementCollection` to a `Trace_FECollection` and check if the pointer is valid. For example a similar thing is done in HypreAMS/HypreADS. See https://github.com/mfem/mfem/blob/361c32362bff4bdcf570c420a3113c0cdb7bad55/linalg/hypre.cpp#L5275

Best,

Socratis

**Comment by thorvath12** [comment]
Thanks a lot, @psocratis it might work. I am not too familiar with dynamic_cast, so I have a question: which of the following two options is safer inside the `GridFunction` class?

`bool hdg_space;`
`const FiniteElementCollection *fe_coll = fes->FEColl();`
`hdg_space = dynamic_cast<const DG_Interface_FECollection*>(fe_coll);`

or

`bool hdg_space;`
`hdg_space = dynamic_cast<DG_Interface_FECollection*>(fec);`

I would think the first one, but I do not know if the second could cause any issues.

Best,
Tamas

**Comment by thorvath12** [comment]
Thanks a lot, @psocratis; it might work. I deleted a question because I realized that it was irrelevant. I close this for now and reopen it if something goes sideways.
