### ISSUE TITLE
Compare difference of solutions on uniformly refined meshes and on a very refined mesh 

### ISSUE THREAD

**Issue by huidong80** [mfem/mfem#3214]
Hi,  May I ask if it is possible in MFEM to compute the differences in a chosen norm 
between different fem solutions on uniformly refined meshes with the fem solution 
on a very refined one (as a reference solution)..  Are there any examples that 
provide such a guidance?

Thank you in advance.

**Comment by nmnobre** [comment]
Hi @huidong80,

Apologies if I'm wrong, but it sounds like you are asking for something very similar to #3209.
Would you mind checking if what's there answers your query?

**Comment by huidong80** [comment]
Hi @nmnobre , thanks a lot for the hints,  I need bit more time to check it carefully,  will come back as soon as possible.

**Comment by huidong80** [comment]
Sorry for late reply.  I still need some more time to go through the code, but the solution is exactly in  https://github.com/mfem/mfem/issues/3209 pointed out by  @nmnobre.  Thanks again for your patience.
