### ISSUE TITLE
METIS on MacBook M1

### ISSUE THREAD

**Issue by bslazarov** [mfem/mfem#3216]
The documentation for installing METIS 5.1.0 should be modified to reflect the build platform.
The line: ~/metis-5.1.0> ln -s ../build/Linux-x86_64/libmetis/libmetis.a lib 
is valid only for Linux-x86_64.

For MacBook M1 it should be Darwin-arm64

**Comment by tzanio** [comment]
I will address this in https://github.com/mfem/web/issues/154

**Comment by tzanio** [comment]
Addressed in https://github.com/mfem/web/pull/183
