### ISSUE TITLE
MFEM  installation 

### ISSUE THREAD

**Issue by shani9383** [mfem/mfem#3218]
Hi,  

I have a few questions regarding the installation of MFEM: 
1. I have an ADM 16 cores computer. Which version should I install, the serial or MPI-based parallel? 
2. My graphic card is NVIDIA RTX™ A2000 12GB. Does it meet the CUDA requirements? 
3. I'm working with a windows operating system. Do I need to change to a Linux OS or I can use a Linux emulator? 

Thanks 
Shani

**Comment by tzanio** [comment]
Hi Shani,

You probably want to install the parallel version with CUDA support.

Maybe that could be accomplished just fine under WSL (I am not sure about the CUDA support), but if there are issues, everything should work fine under Linux.

Tzanio
