### ISSUE TITLE
Dof ordering in DG

### ISSUE THREAD

**Issue by logantm2** [mfem/mfem#3219]
We use MFEM to solve the Euler equations using DG. Right now, we're looking to add the artificial viscosity scheme from [this](http://web.stanford.edu/group/ctr/ResBriefs/2014/13_lv.pdf) paper. The important part is that they define an element-wise indicator (Eq. 2.4)
$$S_e = \frac{\left( U_h^e - \hat{U}_h^e, U_h^e - \hat{U}_h^e \right)_e}{\left( U_h^e, U_h^e \right)_e}$$
where $U_h^e$ is the DG approximation of the solution in element $e$ and $\hat{U}_h^e$ is a "truncated" solution, which is just $U_h^e$ but with all the highest-order terms thrown out (Eq 2.5).

Are DG basis functions listed in order of increasing polynomial order? I.e., will something like this work to get the "truncated" solution at quadrature points?:
```c++
using namespace mfem;

Vector shapef(ndofs);
Vector shapef_trunc(shapef.GetData(), ndofs - ndofs_max_order);
Vector elfun; // Set elsewhere
Vector elfun_trunc(elfun.GetData(), ndofs - ndofs_max_order);
for (int i=0; i<IntRule->GetNPoints(); i++) {
    const IntegrationPoint &ip = IntRule->IntPoint(i);
    trans.SetIntPoint(&ip);

    el.CalcPhysShape(trans, shapef);

    double soln = shapef * elfun;
    double soln_trunc = shapef_trunc * elfun_trunc;
}
```

**Comment by tzanio** [comment]
Hi @logantm2,

The basis in MFEM is not hierarchical, so you can't associate highest-order terms with particular basis functions.

A filtering like that can still be performed by temporarily switching to a basis like the polynomial one: $\mathrm{span} \\{ 1, x, x^2, \ldots \\}$ or the Legendre polynomial basis. 

@jandrej was performing an operation like that, but I don't have the code and he is not available for several weeks.

Given the DG nodes, Gauss-Legendre points by default, the filtering can be implemented in 1D as $B^{-1} D B$ where e.g. for the polynomial basis $B_{ij} = x_i^j$ and $D$ is a diagonal matrix with $0$ in the last diagonal and $1$ on the rest.

**Comment by logantm2** [comment]
Gotcha. I'll dig a bit into the source code to see if it'll be easy to construct the change-of-basis transformation to a hierarchical basis (or if you have a reference handy for the basis used by MFEM, I could just look at that). If not, we'll look into a different AV scheme.
