### ISSUE TITLE
Array<Array<int>>

### ISSUE THREAD

**Issue by kvoronin** [mfem/mfem#323]
Hello,

I'd like to ask about possible usage of Array<Array<int>>. It seems to me that this thing doesn't work. 
For example, I tried
```
    // creating an Array<Array<int>> object which is intended to store two 
    // Array<int> objects of size 2 each
    Array<Array<int> > arr(2);
    arr[0].SetSize(2);
    arr[0][0] = 1;
    arr[0][1] = 2;

    arr[1].SetSize(2);
    arr[1][0] = 10;
    arr[1][1] = 20;
```
with no success. So if I need a group of Array<int> instances, I should create a C dynamic array Array<int> [N], am I right? 
Array2D seems not to be an option since I cannot get Array<int> from it as a column.

Thanks,
Kirill

**Comment by tzanio** [comment]
Hi Kiril,

Array is designed to be a container for simple types. The type could be a struct, see e.g.

https://github.com/mfem/mfem/blob/125ff226e4a8c50fb3aa9a77e871d41bc6b4b60b/general/sort_pairs.hpp#L22-L28

and

https://github.com/mfem/mfem/blob/282dd3894dbf57fc2b9c16b9a5800d1463b7c5fa/general/communication.cpp#L391

but currently that should be a [POD (plain-old-data)](http://en.cppreference.com/w/cpp/concept/PODType) type.

Hope this helps.
Tzanio

**Comment by gelever** [comment]
On the topic of Arrays: Why is copying Arrays explicitly not supported? 
https://github.com/mfem/mfem/blob/b99adf3ca9324a2564fb8e0be829fe1f973e0627/general/array.hpp#L242-L245

This makes it impossible to return an array from a function without using pointers.

**Comment by jdahm** [comment]
@glever yes that makes it difficult to construct arrays at times. It seems strange to allow resizing arrays after creation, transferring ownership, and even allowing empty arrays but not equating or copy-constructing. Though, I admit that if they were allowed this would become difficult to handle correctly.

This gets to a bigger question of the Array, Vector, DenseMatrix, and DenseTensor framework in MFEM. the latter three do not even use an Array<double> under the hood, electing to use a raw pointer and duplicating the logic of ownership of the underlying data. Others will know more but I believe that was done in a time when that was probably necessary for speed. Check out and review my related pull request #284 if you have time! Perhaps this transfer of ownership only complicates the programming and we should move toward a general array and tensor class. + @YohannDudouit

**Comment by tzanio** [comment]
@kvoronin: Were you able to resolve your issue?

@gelever, @jdahm: These comments in Array are really old and maybe no longer relevant. Feel free to propose a PR if you really need that, but there needs to be a convention what happens e.g. if you copy an array that doesn't own its data.

**Comment by kvoronin** [comment]
@tzanio: I didn't come up with something better than using Array<Array<int>*>. By the way, the fact that the copy constructor is private, as far as I understand, makes it also impossible to use anything like std::vector<Array<int> >. For example, the following will give a compiler error:
```
    std::vector<Array<int> > test(2);
    test.resize(3);
```
because such thing as resize() require a copy constructor.
Actually, I don't like how the code looks when pointers are used, it is easier to miss a star or misplace the brackets and compiler might not notice that something is wrong. But this is the way it is with Array so I believe I should use pointers in such constructions.

**Comment by tzanio** [comment]
Closing this issue - the original question was answered and the issue of allowing copying of Arrays should be addressed in a separate PR.
