### ISSUE TITLE
Is there a workaround for multiplying FunctionsCoefficients with something? 

### ISSUE THREAD

**Issue by JonasBeddrich** [mfem/mfem#3231]
Hello everyone, 

For my current project, I need a large number of different FunctionCoefficients (n = ~400) of the form u(x) * z * k, where u is a prescribed function and z and k are integers that are different for the different FunctionCoefficients. As far as I understand there is no possibility to combine Coefficients, multiply them with something etc.
 
Does anyone know a smart way to deal with this problem? n the number of FunctionCoefficients is given as an argument, so I would need a dynamic solution ... 

It would be great if someone has an idea or could point me in the right direction. 

Best wishes, 
Jonas

**Comment by JonasBeddrich** [comment]
My current workaround looks as follows: 

I created a class for all coefficients needed. The objects are initialized with the respective values for z,k, while all parameters etc. are defined within the class. The function has eval function, which takes the Vector and returns the value in question. I then use std::bind on the eval function with the respective element to create the Function Coefficient. This works, but I'm not sure whether there's a better way. 

Since the constructor for FunctionCoefficient is overloaded (to enable time dependent functions), the workaround only works for the eval function to take arguments (const Vector &, double). That's not problematic, since I can simply ignore the double argument for the time, but it's not nice. Does anyone know how to avoid the ambiguity here? 

Best wishes, 
Jonas

**Comment by vladotomov** [comment]
Hi Jonas,

I don't quite understand what you're trying to do.

Surely you can define your own `Coefficient` that combines other `Coefficients` or multiplies them with anything. Why don't you define a `Coefficient` that changes `z` and `k` dynamically, assuming `u(x)` is fixed?

**Comment by dylan-copeland** [comment]
In addition to a class derived `Coefficient`, note that there is also `ProductCoefficient`. This class has very little memory, so you could have a `FunctionCoefficient` for the function and then 400 instances of `ProductCoefficient`. The derived class sounds like the best option, but I just wanted to point out `ProductCoefficient` since it may not be clear that there are ways to combine coefficients (see also `SumCoefficient` etc.).

**Comment by JonasBeddrich** [comment]
I was basically looking for `ProductCoefficient`. I'm not sure why I missunderstood it looking at the documentation ... 
Thanks for the help.
