### ISSUE TITLE
Question about quadrature rules and metric for 3d tet mesh optimization

### ISSUE THREAD

**Issue by joshia5** [mfem/mfem#3244]
Hello,
Regarding the mesh-optimizer's 3d untangling case (metric id 313) for order 3 tetrahedron mesh and order 4 quadrature, I understand that Gauss-lobatto quadrature is used and the rule is defined for 1d in this function: 
QuadratureFunctions1D::GaussLobatto(const int np, IntegrationRule* ir),
I am wondering if it would be possible to know how the values of weights and integration points are defined for 3d tetrahedron that are used to evaluate the objective function and its derivatives?

I'm also looking to understand at which point in the source code the local quality metric is evaluated at the quadrature points? (if i understand correctly the target
representing ideal-shape-unit-size is constructed in a manner similar to constructing ((1, cos 60), (0, sin 60)) the target for equilateral triangles)

Any help is appreciated.
Thank you

**Comment by vladotomov** [comment]
Hello @joshia5,

The tet integration rules are generated [here](https://github.com/mfem/mfem/blob/a97923ed621886a3ecefde38bccfe71abb2adeb8/fem/intrules.cpp#L1553). The 1D quadratures are used to construct quadratures for tensor-product elements (quads, hexes).

Example of metric evaluation is this [line](https://github.com/mfem/mfem/blob/a97923ed621886a3ecefde38bccfe71abb2adeb8/fem/tmop.cpp#L2637), but there are other places as well, depending on the TMOP setup.

Yes, the target in this case would be a regular tet; the construction is done [here](https://github.com/mfem/mfem/blob/a97923ed621886a3ecefde38bccfe71abb2adeb8/fem/tmop.cpp#L1209-L1220).

**Comment by joshia5** [comment]
Hello @vladotomov,
Thank you.
I have another related question. When I run this 3d untangling case with a coarser (8 tetrahedron) mesh of a ball-like model with a part of the boundary curving inwards, the optimizer diverges. The mesh and tangled edges are as shown in attached pictures. 
![GLVis_s01](https://user-images.githubusercontent.com/56453280/194644544-22af6870-6abc-4e3d-8e5e-c2462e5a4267.png)
![GLVis_s01](https://user-images.githubusercontent.com/56453280/194627882-ce602388-8be5-40c0-a091-54f9764723e6.png)
I have tried increasing order of quadrature till 10 without any luck.
Am i doing something incorrectly here, or is this the expected behavior for such an input mesh and a target of regular tet? Is it possible to untangle such a mesh using different input parameters?

my mfem source is at this commit: https://github.com/mfem/mfem/commit/a97923ed621886a3ecefde38bccfe71abb2adeb8

**Comment by vladotomov** [comment]
Hi @joshia5,

To untangle this, the optimizer must move the boundary nodes. But it does not move boundary nodes, because it has no knowledge where they should be, i.e., what is the correct position of the boundary. Thus by default we optimize with fixed boundary nodes.

One option is to let the boundary nodes free to move and untangle, but it might produce something that does not agree with the desired boundary. I can try this if you send me the mesh. If you give us an analytic boundary description, we can try to be close to that, but there will be some small numerical error.

**Comment by joshia5** [comment]
Thank you @vladotomov .
Optimization with fixed boundary is the desired behavior.
I'll email the mesh file to you. (Github comments does not support the file type)

**Comment by v-dobrev** [comment]
Some of the tet quadrature rules have negative weights which may be causing issues.

**Comment by joshia5** [comment]
The command that you mentioned worked for this case. Thank you @vladotomov, @v-dobrev for your help.
