### ISSUE TITLE
Interpolate degrees-of-freedom on edge

### ISSUE THREAD

**Issue by chvillanuevap** [mfem/mfem#3249]
Hi!

I have an `mfem::GridFunction` that describes a level set function on an `mfem::Mesh`. I wish to extract the points where the level set function is zero. To do so, I loop over all the edges and then do a linear interpolate of the nodal values of the edge to find any possible zero values. The code looks something like this:
```
// Get level set values at the nodes.
mfem::Vector phi;
_phi->GetNodalValues(phi);

// Get edge-to-vertex map.
mfem::Table const *edge2node = _mesh->GetEdgeVertexTable();

// Loop over the edges to compute the set of zeros of the level set function.
for (int ie = 0; ie < num_edges; ++ie) {

    // Get the edge vertices.
    int const *ev = edge2node->GetRow(ie);

    // Get the edge level set values.
    std::array<double, 2> const edge_phi = {phi[ev[0]], phi[ev[1]]};

    // Check if the level set function cuts this edge.
    if (edge_phi[0] * edge_phi[1] < 0.0) {

        // Interpolate the location of the intersection point.
        double phictr = edge_phi[0] / (edge_phi[0] - edge_phi[1]);

        // Coordinates at the edge vertices.
        double const *evX_0 = _mesh->GetVertex(ev[0]);
        double const *evX_1 = _mesh->GetVertex(ev[1]);

        // Store global coordinates of this intersection point.
        mfem::Array<double> intersection_X(dim);
        intersection_X[0] = evX_0[0] + phictr * (evX_1[0] - evX_0[0]);
        intersection_X[1] = evX_0[1] + phictr * (evX_1[1] - evX_0[1]);

    }

}
```
Now, I would like to use quadratic elements rather than linear. I don't think the edge-to-vertex table gives me the number for the nodes in the middle of the edge. Do you guys have any suggestions on how to interpolate that?

**Comment by vladotomov** [comment]
Hi @chvillanuevap,

You can loop over faces, and get the values of the `GridFunction` for all dofs that are on the face. I'm guessing your `GridFunction` is H1. Something like this:
```
      Array<int> vdofs;

      int nfaces = mesh->GetNumFaces();
      for (int i = 0; i < nfaces; i++)
      {
         phi_fes->GetFaceVDofs(i, vdofs);
         phi.GetSubVector(vdofs, values);
      }
```
Then you'd have to find the zeros of a high-order polynomial. And depending what you need, you might have to do it on the volumetric elements, as the LS will be a general curve.

**Comment by chvillanuevap** [comment]
@vladotomov Thank you! This is a good starting point. One more thing. What function could I use to find the coordinates of the face nodes? Would `mesh::GetFaceVertices` return that, or just the endpoints of my edge? My mesh is 2D.

**Comment by vladotomov** [comment]
Similar to above (this is pseudocode):
```
      Array<int> vdofs;
      int nfaces = mesh->GetNumFaces();
      for (int i = 0; i < nfaces; i++)
      {
         mesh.GetNodes().FiniteElementSpace()->GetFaceVDofs(i, vdofs);
         mesh.GetNodes.GetSubVector(vdofs, dof_positions);
      }
```

**Comment by chvillanuevap** [comment]
Thanks, @vladotomov. I'll give this a shot! I'll go ahead and close this issue for now.
