### ISSUE TITLE
const versions of EliminateCols and GetSubMatrix

### ISSUE THREAD

**Issue by kvoronin** [mfem/mfem#325]
Hello,

I am just wondering why in SparseMatrix::EliminateCols the input Array<int> cols is not a const&, and why SparseMatrix::GetSubMatrix is not a const method? It seems natural to me to have the const keyword there. 

Thanks,
Kirill

**Comment by jakubcerveny** [comment]
Hi Kirill,

You are right, they should both be const. Some older parts of MFEM are not
const correct, we should fix those.

Jakub

**Comment by tzanio** [comment]
@kvoronin, feel free to propose a pull request, see e.g. https://github.com/mfem/mfem/pull/309.
