### ISSUE TITLE
How to solve Time Independent PDEs with u^n terms

### ISSUE THREAD

**Issue by cdelv** [mfem/mfem#3250]
Hi, I was experimenting a bit with MFEM and wondered how I can solve PDEs with nonlinear terms. For example

$$ \nabla^2 u + \nabla\cdot (\vec{\lambda} u^2)=0 $$

Where $\vec{\lambda}$ is a constant vector, let's say (0,-1,0). I tried to write this equation as an advection-diffusion equation defining $\vec{v}=\vec{\lambda}u$ resulting in

$$ \nabla^2 u + \nabla\cdot (\vec{v} u)=0 $$

Then, To assemble the bilinear form I created a coefficient in the following way

```
    ParBilinearForm a(&fespace);

    ConstantCoefficient k(1.);
    a.AddDomainIntegrator(new DiffusionIntegrator(k));

    Vector lmd = {0,-1};
    VectorConstantCoefficient F(lmd);
    GridFunctionCoefficient uu(&u);
    ScalarVectorProductCoefficient FF(uu,F);
    a.AddDomainIntegrator(new ConvectionIntegrator(FF,1.0));
    a.Assemble(); 
```

However, I found that when the solver iterates to find the solution, the `ScalarVectorProductCoefficient` doesn't update, and the solution kind of ignores the nonlinear term in the  `ConvectionIntegrator` and regards it as a normal one. 

How can I update the `ScalarVectorProductCoefficient` during the solver iterations? What is a good way to solve this equation?

I attached the complete code below with a .txt extension so I can post it here. 

[Non-Linear-Convection.txt](https://github.com/mfem/mfem/files/9751091/Non-Linear-Convection.txt)

**Comment by vladotomov** [comment]
Hi @cdelv,

To solve a nonlinear PDE, you must to setup a `NonlinearForm` by creating a `NonlinearFormIntegrator`, compute gradients, use a nonlinear solver, etc. You should go over example 10 to see the usual approach in MFEM.

Good luck,
Vladimir
