### ISSUE TITLE
mfem-4.4 compilation fails to complete on "tmop_pa_w3.cpp"

### ISSUE THREAD

**Issue by denislachapelle** [mfem/mfem#3259]
I have Ubuntu "ubuntu-22.04.1-desktop-amd64.iso" installed in Virtualbox installed in Windows 10. When I compile mfem with this command "make serial -j" the compilation start properly up to the file "tmop_pa_w3.cpp"; then it takes a lot of time up to a moment when the screen becomes black and Unbuntu restart. Using the rescources monitor, I saw that the swap memory was constantly growing while compiling "tmop_pa_w3.cpp".

I an stuck there and dont know what to do.

Thank you for your help.

**Comment by tzanio** [comment]
Can you try the latest release, `mfem-4.5`?

That file may take a while to compile in a virtual machine, I will also suggest specifying `-j 4` or whatever is appropriate in terms of how many hardware cores are available.

**Comment by denislachapelle** [comment]
I may try later with version 4.5, but for now I succeed compiling and executing few examples using WSL. The only issue I have now is with the viewing. I have GLVIS-4.2 properly compiled but I get the following message:

Waiting for data on port 19916 ...
FATAL: Failed to initialize SDL: No available video device
Thank you for using GLVIS.

I have installed Xming and get the xterm working so this prove the X windows server works, but still glvis display the error shown above.

**Comment by denislachapelle** [comment]
The following setup works fine for me now.

mfem-4.5 installed in WSL under windows 10.
glvis 4.2 installe for windows (not under WSL).

As example for example 0, I do the following:
In WSL shell in mfem examples directory ./ex0 -m ../data/square-disc.mesh -o 2
in CMD shell in glvis directory •	glvis -m ..\mfem-4.5\examples\mesh.mesh -g ..\mfem-4.5\examples\sol.gf  
and GLVIS is properly showing the solution.

**Comment by denislachapelle** [comment]
Finally I end-up with the following setup that works better for me.

1-install a VMWARE virtual machine on my window 10 computer.
2-implement a ubuntu linux VM.
3-install mfem 4.5 and glvis 4.2.

**Comment by ccc112233ccc** [comment]
I use wsl too. when I use "make serial -j" wsl will failed, but it successed when i use "make serial -j 4"
