### ISSUE TITLE
Which C++ standard version does MFEM comply with? 

### ISSUE THREAD

**Issue by agrayver** [mfem/mfem#326]
I couldn't find any statement on that. Is MFEM restricted to C++03 or newer features (specifically from C++11) are allowed in the library code-base? In case a user wants to propose some new features or improvements for the existing functional, this constraint should be known from the beginning.

**Comment by jakubcerveny** [comment]
AFAIK C++11 is not allowed in MFEM (at least not yet). My guess would be
C++03.

Jakub

On Tue, Oct 24, 2017 at 3:23 PM, Alexander Grayver <notifications@github.com

**Comment by tzanio** [comment]
Here is a quote from our internal Developer's guide:

 > Introduction of language constructions not currently used in MFEM should be
    justified and generally avoided (so we can build on cutting-edge systems).

C++11 features could be allowed, but there should be a good technical reason for that.

**Comment by agrayver** [comment]
Thank you. The reasons to use C++11 have been extensively discussed elsewhere, I guess there is no need to repeat. I just wanted to know the current status. 

For the record: deal.II, libMesh and Trilinos have already allowed C++11.

**Comment by dylan-copeland** [comment]
Has there been a change of policy since October 2017? The current master branch builds with the flag -std=c++11 by default. Clearly a user can develop new applications using C++11 features, but would C++11 code be allowed to be merged into master? Does mfem already contain any C++11 code?

**Comment by tzanio** [comment]
Yes, we now support C++11: https://github.com/mfem/mfem/blob/master/CHANGELOG#L14. This is needed for the GPU support via lambda-capturing and will become official in the 4.0 release.

That being said, 

> We prefer basic C++ and the C++03 standard, to keep the code readable by a large audience and to make sure it compiles anywhere.

see https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#developer-guidelines.
