### ISSUE TITLE
MATTRANSPOSEMAT unknown warning specifier for PETSc 3.18.0

### ISSUE THREAD

**Issue by adam-sim-dev** [mfem/mfem#3260]
linalg/petsc.cpp(1327): warning #1028: unknown warning specifier
        ierr = PetscObjectTypeCompare((PetscObject)(pA->A),MATTRANSPOSEMAT,&istrans);
                                                           ^

**Comment by v-dobrev** [comment]
With gcc I get the warning
```console
linalg/petsc.cpp:1327:13: warning: MATTRANSPOSEMAT macro is deprecated use MATTRANSPOSEVIRTUAL (since version 3.18)
       ierr = PetscObjectTypeCompare((PetscObject)(pA->A),MATTRANSPOSEMAT,&istrans);
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~           
```
which is a deprecation warning from PETSc v3.18.0.

With what compiler did you get the above?

In any case, I think you can safely ignore this for now.

We can keep this open to remind us to add a `#if` switch for the new name in the new version of PETSc.

**Comment by adam-sim-dev** [comment]
I am using icpc from Intel oneAPI 2022.2

**Comment by v-dobrev** [comment]
Oops, I didn't mean to close this.
