### ISSUE TITLE
customization of MFEM for Maxwell's equations

### ISSUE THREAD

**Issue by InfinityHub** [mfem/mfem#3261]
Hello, I am trying to understand how to use MFEM for my own problems. My PDE is diffusive Maxwell's equations. I wonder how I can use the high-order FE modules in MFEM (e.g., discretization of curl-curl operator on tetrahedral meshes)  to solve my equations with my own:
1. initial tetrahedral mesh, since the models to be meshed are quite problem specific;
2. boundary conditions, e.g., the E & H field values will be known at the boundaries of the problem domain;
3. linear system solver. 

The 3rd one is less important than the first 2, as I know there are already some solvers linked to or implemented in MFEM. Any suggestions about how I can achieve this or where should I start ? 

Thanks !

**Comment by dylan-copeland** [comment]
Hello @InfinityHub, thank you for your interest in using MFEM for Maxwell's equations. I recommend starting with the example `mfem/examples/ex3p.cpp`, which discretizes and solves the type of equation you mentioned, with support for tetrahedral meshes (among other types). The supported mesh types and tools to generate them are documented on the MFEM webpage:
https://mfem.org/mesh-formats
