### ISSUE TITLE
Exodus QUAD mesh is dumped as TRI mesh in VisIt and ParaView data collectors

### ISSUE THREAD

**Issue by chvillanuevap** [mfem/mfem#3263]
I have a 3D surface mesh (topologically 2D) made of QUAD elements. All points have `x`, `y`, and `z` coordinates because this mesh is a slice of a larger 3D volumetric mesh.

<img width="928" alt="Screen Shot 2022-10-19 at 8 58 42 PM" src="https://user-images.githubusercontent.com/3827771/196846046-292bd043-6e87-46c6-b741-eaa6fba94580.png">

I read the mesh in MFEM using:
```
mfem::Mesh mymesh("slice_1_middle_fromcubit.gen");
```
Then, I dump it using:
```
mfem::ParaViewDataCollection slice_pv_dc("somename", &mymesh);
slice_pv_dc.SetPrefixPath("someprefix");
slice_pv_dc.SetCycle(0);
slice_pv_dc.Save();
```
I do something similar for VisIt. However, when I dump it in ParaView or VisIt, I get a triangular mesh. From ParaView:
<img width="479" alt="Screen Shot 2022-10-19 at 9 03 04 PM" src="https://user-images.githubusercontent.com/3827771/196846539-cc2df33e-8308-4cdc-a1ed-6ed4359595be.png">
From VisIt:

![Screen Shot 2022-10-19 at 10 34 04 PM](https://user-images.githubusercontent.com/3827771/196857390-f48af8de-4300-4a63-b66f-f6d58d121b40.jpg)

At first, I thought that perhaps the 3D mesh with 2D topology was confusing the writer, so I converted the mesh to a QUAD mesh myself using:
```
mfem::Mesh newmesh(2, mymesh.GetNV(), mymesh.GetNE(), 0, 3);

for (int ip = 0; ip < mymesh.GetNV(); ip++) {
	double *coord = mymesh.GetVertex(ip);
	newmesh.AddVertex(coord);
}

for (int it = 0; it < mymesh.GetNE(); it++) {
	mfem::Array<int> element;
	mymesh.GetElementVertices(it, element);
	newmesh.AddQuad(element[0], element[1], element[2], element[3]);
}

newmesh.FinalizeQuadMesh(1);
```
I'm guessing something about using dimension 2 and spatial dimension 3 is confusing the writer. I had used this combination with a slice mesh made of triangles in the past without issues though. This problem with QUADs is new to me. Could it be that my initial mesh is corrupt perhaps?

**Comment by v-dobrev** [comment]
Is it clear that the issue is not in the reader? One way to check that is to open the file in GLVis with `./glvis -m slice_1_middle_fromcubit.gen` and see if everything looks good.

**Comment by chvillanuevap** [comment]
I tried running GLVIS on my Mac, but I got an error about NetCDF. I'll have to install it on Linux, since my MFEM there does support NetCDF. However, I opened the mesh on ParaView, Cubit, MATLAB, and VisIt, and it looks okay.

VisIt:
<img width="936" alt="Screen Shot 2022-10-20 at 10 41 03 AM" src="https://user-images.githubusercontent.com/3827771/197008565-b21e1655-c95b-4f14-80aa-7aa93c2a8e28.png">
Cubit:
<img width="324" alt="Screen Shot 2022-10-20 at 10 40 12 AM" src="https://user-images.githubusercontent.com/3827771/197008575-35d80017-1768-4355-90fb-d9f2bdd30ea5.png">

**Comment by chvillanuevap** [comment]
It seems at some point in the process, the nodes get flipped for the quads.
<img width="781" alt="Screen Shot 2022-10-20 at 11 30 37 AM" src="https://user-images.githubusercontent.com/3827771/197018262-0e330f51-0b5e-4151-9755-423e4ba28cc7.png">

**Comment by chvillanuevap** [comment]
Sorry for all the messages but I think I'm getting close to the error. MFEM thinks the mesh is made of TETs.

<img width="1141" alt="Screen Shot 2022-10-20 at 11 54 12 AM" src="https://user-images.githubusercontent.com/3827771/197022658-410dc2d1-cd8d-49cf-99d4-b135daf0c3ef.png">

But Cubit, ParaView, etc. recognize it is QUADs.

<img width="351" alt="Screen Shot 2022-10-20 at 11 55 09 AM" src="https://user-images.githubusercontent.com/3827771/197022745-0ec68c1e-cc63-4181-a7c2-de4bfedef467.png">

**Comment by chvillanuevap** [comment]
I think I found the "bug". The problem is in the `mfem::Mesh::ReadCubit` function.
```
if (num_dim == 2)
   {
      switch (num_node_per_el)
      {
         case (3) :
         {
            cubit_element_type = ELEMENT_TRI3;
            cubit_face_type = FACE_EDGE2;
            num_element_linear_nodes = 3;
            break;
         }
         case (6) :
         {
            cubit_element_type = ELEMENT_TRI6;
            cubit_face_type = FACE_EDGE3;
            num_element_linear_nodes = 3;
            break;
         }
         case (4) :
         {
            cubit_element_type = ELEMENT_QUAD4;
            cubit_face_type = FACE_EDGE2;
            num_element_linear_nodes = 4;
            break;
         }
         case (9) :
         {
            cubit_element_type = ELEMENT_QUAD9;
            cubit_face_type = FACE_EDGE3;
            num_element_linear_nodes = 4;
            break;
         }
         default :
         {
            MFEM_ABORT("Don't know what to do with a " << num_node_per_el <<
                       " node 2D element\n");
         }
      }
   }
   else if (num_dim == 3)
   {
      switch (num_node_per_el)
      {
         case (4) :
         {
            cubit_element_type = ELEMENT_TET4;
            cubit_face_type = FACE_TRI3;
            num_element_linear_nodes = 4;
            break;
         }
         case (10) :
         {
            cubit_element_type = ELEMENT_TET10;
            cubit_face_type = FACE_TRI6;
            num_element_linear_nodes = 4;
            break;
         }
         case (8) :
         {
            cubit_element_type = ELEMENT_HEX8;
            cubit_face_type = FACE_QUAD4;
            num_element_linear_nodes = 8;
            break;
         }
         case (27) :
         {
            cubit_element_type = ELEMENT_HEX27;
            cubit_face_type = FACE_QUAD9;
            num_element_linear_nodes = 8;
            break;
         }
         default :
         {
            MFEM_ABORT("Don't know what to do with a " << num_node_per_el <<
                       " node 3D element\n");
         }
      }
   }
```
In my case, I have a 3D mesh (a slice) formed of `QUAD4` elements. Even if `QUAD4` should exclusively used be used for 2D, the function should be able to handle 3D `SHELL4` elements. The function is mixing geometry with topology. `num_dim` should indicate the spatial dimension, whereas the element type (`QUAD4`, `TRI3`, etc.) should set the (topological) dimension of the mesh.

For example, in a MATLAB Exodus reader I coded I have:
```
% Get number of geometrical dimensions.
if find(strcmp(ddim, 'num_dim'))
    [~, gdim] = netcdf.inqDim(ncid, netcdf.inqDimID(ncid, 'num_dim'));
end
...
% Get element type in block 1.
type = netcdf.getAtt(ncid, netcdf.inqVarID(ncid, 'connect1'), netcdf.inqAttName(ncid, netcdf.inqVarID(ncid, 'connect1'), 0));

% Get topological dimension.
switch type
    case {'TRI3', 'TRISHELL3'}
        tdim = 3;
    case {'QUAD4', 'SHELL4', 'QUAD', 'quad'}
        tdim = 3;
    case {'HEX8', 'HEXA8'}
        tdim = 4;
    otherwise
        error('This function cannot handle this element type yet. Add switch statement.');
end
```
where `gdim` is the spatial dimension of the mesh, and `tdim` is the topological dimension of the mesh. It would be equivalent to using `mfem::Mesh::Mesh(int Dim_, int NVert, int NElem, int NBdrElem=0, int spaceDim_=-1)` with `Dim_ = tdim` and `spaceDim_ = gdim`.

**Comment by chvillanuevap** [comment]
It seems, based on issue #2547, that MFEM only supports 3D surface meshes when they are in VTK format 4.2. ParaView exported my mesh to VTK 5.1 format, I converted it to 4.2 using meshio, and the code seems to run now. Thanks!

**Comment by v-dobrev** [comment]
Okay, that makes sense -- our Cubit mesh reader does not support surface meshes (it shouldn't be too hard to add support though). I wasn't sure if it does, and that's why I asked you to try opening the mesh in GLVis. GLVis uses the MFEM mesh readers, so it basically tests the MFEM mesh readers.

**Comment by chvillanuevap** [comment]
Hi there!

I'm reopening this issue because I found another problem with loading surface meshes. 

I'm able to create an `mfem::mesh` from a VTK file. The problem now is that MFEM always sets the spatial dimension to 2, rather than 3. This is odd because the function `Mesh::ReadVTKMesh` defaults to reading vertices in 3D. If I call `mesh->GetVertex(i)` after I have read the mesh, the x, y, and z coordinates are there. So it's always reading a 3D mesh, but `mesh->SpaceDimension()` is always set to 2.

**Comment by pazner** [comment]
Do all of the vertices in your mesh lie in a single z-plane? Since the VTK format doesn't really distinguish between 2D and 3D meshes, the following logic is used to set the space dimension:

https://github.com/mfem/mfem/blob/b09cc38df9f1da182a5625c92660737ca02e710a/mesh/mesh_readers.cpp#L428-L448

**Comment by chvillanuevap** [comment]
They all lie in the same X-plane. It seems though that the memory allocation is always 3 x number-of-points?
```
void Mesh::ReadVTKMesh(std::istream &input, int &curved, int &read_gf,
                       bool &finalize_topo)
...
   Vector points;
   int np;
   input >> np >> ws;
   getline(input, buff); // "double"
   points.Load(input, 3*np); <---- SEE HERE
```

And the data is stored as 3D as well. From my script:
```
std::cout << "vertex = [..." << "\n";

for (int iv = 0; iv < num_vertices; iv++) {

	double const *vertex = mesh.GetVertex(iv);

	// Output flags = scientific + show sign.
	std::cout << std::scientific << std::showpos;

	for (int id = 0; id < 3; id++) { <-- THIS DOES NOT LEAD TO A SEGFAULT
		std::cout << vertex[id] << " ";
	}

	std::cout << std::endl;

}

std::cout << "];" << std::endl;
```
Output:
```
vertex = [...
+5.347921e+01 +4.560000e+00 +2.822189e+01 
+5.347921e+01 +4.431168e+00 +2.822395e+01 
+5.347921e+01 +4.560000e+00 +2.822664e+01 
```
Even though the space dimension is set to 2, the memory allocation is always 3. So shouldn't the spatial dimension always default to 3?

**Comment by pazner** [comment]
In MFEM, a 1D or 2D mesh will still allocate 3D vertices. A `Vertex` object always has member data `double coord[3]` (similarly, an `IntegrationPoint` object has members `x`, `y`, and `z` even if the integration rule is 1D or 2D).

For a mesh with spatial dimension 2, accessing the z-coordinate of a vertex will not crash, but it generally will not give meaningful results (it could return uninitialized data, for example).

The VTK format doesn't distinguish between 1D, 2D, or 3D meshes. The vertices are always given as coordinates of length 3. So when MFEM loads these meshes, it has to decide what the space dimension actually is. It does this by looking to see if there is variation e.g. in the z-coordinate.

**Comment by chvillanuevap** [comment]
Then, would it break stuff to assume all VTK meshes are spatially 3D and topologically 1D, 2D, or 3D depending on the element type? In my case, I have a 3D mesh in a topologically 2D space.

**Comment by pazner** [comment]
Yes, always setting the space dimension to 3 would break other things.

Is there a reason you need to treat your mesh as a 3D mesh if it is planar?

**Comment by chvillanuevap** [comment]
I need the 3D coordinates of the vertices to postprocess some stuff. For now, I'm hardcoding the spatial dimension to be 3 in my script when I read the coordinates of the vertices. It seems that doing so shouldn't break anything in my workflow.

Thank you guys for the help! This has been very informative!
