### ISSUE TITLE
Glvis Build Error 1

### ISSUE THREAD

**Issue by goinea** [mfem/mfem#3264]
Hello, 
I've been trying to install Glvis for a while and sway between errors when building serial version. Currently I am getting the error below and am not sure how to fix it:
`/home/linuxbrew/.linuxbrew/bin/ld: cannot find -lglvis: No such file or directory
collect2: error: ld returned 1 exit status
make: *** [makefile:258: glvis] Error 1 `
I am using Glvis-4.0 and mfem-4.2 on GNU make since those are the versions used in the example: https://glvis.org/building/

**Comment by tzanio** [comment]
Can you try the latest releases, i.e. glvis-4.2 and mfem-4.5?

**Comment by goinea** [comment]
I did and get this error continually:
'error: XDG_RUNTIME_DIR not set in the environment.
FATAL: Failed to initialize SDL: No available video device
Thank you for using GLVis.
Waiting for data on port 19916 ...'
