### ISSUE TITLE
Restricted H(curl)/rotational symmetry 

### ISSUE THREAD

**Issue by AntonIatcenko** [mfem/mfem#3265]
Hello Everyone, 

I am solving a Maxwell eigenvalue problem $$\nabla \times \nabla \times \mathbf{E} = \lambda \mathbf{E}$$
on a domain that is a body of revolution. The eigenfunctions (in cylindrical basis) have the form of $\mathbf{E}(r, \phi, z) = \mathbf{E}_m(r, z) e^{im\phi}$. I'd like to be able to solve for a single given $m$ by discretizing the 2D problem for $\mathbf{E}_m$. I am guessing this is related to the reduced Nedelec spaces from example 31, but it is not clear to me what exactly is meant by "reduced". Is it just solving the problems assuming $\partial_z \equiv 0$ for all components of the fields?

**Comment by tzanio** [comment]
In the axisymmetric case, there are additional coefficients in the two bilinear forms above to account for the restriction from 3D to a meridian plane.

I believe @mlstowell already has some code for that, see [this comment](https://github.com/mfem/mfem/issues/2180#issuecomment-828076232).

@dylan-copeland also has experience with axisymmetric Maxwell problems and may be able to provide additional advice.
