### ISSUE TITLE
Create a group of finite element with different dofs

### ISSUE THREAD

**Issue by miaodi** [mfem/mfem#3267]
I would like to try a mixed formulation in mfem. The linearized formulation in the block form is given as:
[K L^T][dv]=[f]
[L  H   ][da]  [h]

where dv is discretized by normal hex H1 elements. For da, it is scalar and is discontinuous (in L2). It is discretized by elements whose shape functions are a subset of $\xi_1, \xi_2, \xi_3,\xi_1\xi_2, \dots, \xi_1^i\xi_2^j\xi_3^k,\dots$ (I would like to try different combinations of $\xi_1^i\xi_2^j\xi_3^k$). 

Could you give me some suggestions on how to easily create elements with different dofs?
For example, 3-dof element $\xi_1, \xi_2, \xi_3$, 4-dof element $\xi_1, \xi_2, \xi_3,\xi_1\xi_2$ and 5-dof element $\xi_1, \xi_2, \xi_3,\xi_1\xi_2,\xi_2\xi_3$.

Thank you.

**Comment by v-dobrev** [comment]
You can define a custom finite element e.g. by deriving from `ScalarFiniteElement` or even directly from `FiniteElement`. For example, you can look at the definition of class `L2_HexahedronElement` or the simpler fixed order class `TriLinear3DFiniteElement`.

Once the custom element is defined, you can create a corresponding custom `FiniteElementCollection` class similar to `LinearDiscont3DFECollection`. You do not need to define elements for all 3D geometries -- if you use just hex meshes, you only need to define the `FiniteElement` for `Geometry::CUBE` to be your custom `FiniteElement`.

For visualization, you will probably want to interpolate your solution to a larger FE space, e.g. Q1 DG space.

Let us know if you have any further questions beyond this general guidance.
