### ISSUE TITLE
Parameters/Statistics for HypreAME

### ISSUE THREAD

**Issue by AntonIatcenko** [mfem/mfem#3269]
Hello Everyone, 

I am using HypreAME for a Maxwell eigenvalue problem (pretty much example 13 on a hemispherical domain), and I am having issues with computing higher-order eigenvalues. Usually, I can get between 110 and 115 eigenvalues, and beyond that the solver fails with "Error in LOBPCG: Bad initial vectors: orthonormalization failed". 

1. Is it possible to check if the solver converged? So that I am not saving "solutions" if it didn't
2. I think LOBPCG allows for more parameters than I can readily set from MFEM, like the block size. Is it possible to get access to those? Maybe I will be able to find a combination that works for my problem, like computing the eigenvalues in blocks of 50 instea of all at once. 
3. Is it possible to compute eigenvalues in the neighbourhood of a given value or above a given value? (Simple shifting does not work for that.)
4. Is it possible to run it without the preconditioner?

**Comment by tzanio** [comment]
Good questions, @AntonIatcenko. I am afraid some of them may not have good answers.

1. There is no lobpcg function that I am aware of for this. You can print and monitor the convergence with `HypreAME::SetPrintLevel` and potentially check the norm of $\\| A x - \lambda M x \\|$ for eigenpairs before safint them.

2. The call to LOBPCG in hypre's src/parcsr_ls/ame.c is below. I don't really see much more parameters that will be useful to provide. Note that the lobpcg block size is set by `HypreAME::SetNumModes`.

```
   blap_fn.dsygv  = hypre_dsygv;
   blap_fn.dpotrf = hypre_dpotrf;
   lobpcg_tol.relative = ame_data -> rtol;
   lobpcg_tol.absolute = ame_data -> atol;
   residuals = hypre_TAlloc(HYPRE_Real,  ame_data -> block_size, HYPRE_MEMORY_HOST);

   lobpcg_solve((mv_MultiVectorPtr) ame_data -> eigenvectors,
                esolver, hypre_AMEMultiOperatorA,
                esolver, hypre_AMEMultiOperatorM,
                esolver, hypre_AMEMultiOperatorB,
                NULL, blap_fn, lobpcg_tol, ame_data -> maxit,
                ame_data -> print_level, &nit,
                ame_data -> eigenvalues,
                NULL, ame_data -> block_size,
                residuals,
                NULL, ame_data -> block_size);
```

3. I am not aware of a simple way to do that, sorry.

4. You can in principle provide an `IdentityOperator` to `HypreAME::SetPreconditioner` but I don't think that is a good idea. First, AME has really been designed to work with AMS and may not even converge. Second, even if it does converge, it will take many iterations for large problems.

Two additional comments:

- The error you listed means that the initial LOBPCG vectors were not random enough (i.e. they were linearly dependent). This randomization should be easier if the vector size is larger relative to the number of eigenvectors. In hypre, it is done by the call to `mv_MultiVectorSetRandom (eigenvectors, seed);` in `hypre_AMESetup`, there are similar calls in MFEM's `HypreLOBPCG`. Maybe a better seed or random number generator can help?

- I was wrong yesterday -- @mlstowell wrote the `HypreAME` wrapper in MFEM and may have additional comments and suggestions for you.

**Comment by AntonIatcenko** [comment]
Thank you for your response @tzanio!

1. This is very strange... I guess I'll try to "intercept" what the function prints to the output and process it. Will use your suggestion for checking the norm if that does not work, thanks!
2. Here is what it says in the documentation for hypre's LOBPCG: "The LOBCPG also allows one to impose constraints on the eigenvectors of the form $x^T B y_i = 0$ for a set of vectors $y_i$ given to LOBPCG as input parameters. This makes it possible to compute, e.g., 50 eigenpairs by 5 subsequent calls to LOBPCG with the blockSize=10, using deflation." It sounds like the block size can be the same as the number of eigenvalues, but it doesn't have to be. Currently, the deflation happens automatically as the iterations progress, but in the cases when the solver fails it happens before any deflation. If the MFEM could take the maximum block size $mb$ (an array of block sizes?) and then run the LOBPCG $\lceil nev/mb \rceil$ times, making use of the constraints feature (I suspect one of the NULLs you are passing to lobpcg_solve is for $\{y_i\}$), then the user would have better control over deflation, which might fix my problem. Your additional comment also makes it seem like a good idea, as we would be computing fewer eigenvectors at a time and thus being sufficiently "random" would be easier.

Do I understand correctly that MFEM's HypreAME is a wrapper around ame.c, which is itself a wrapper around 
lobpcg written by Andrew Knyazev? From looking at ame.c, it seems like the changes I require would have to be made there rather than in MFEM code. 

Seems like quite a rabbit hole...

**Comment by tzanio** [comment]
> Do I understand correctly that MFEM's HypreAME is a wrapper around ame.c, which is itself a wrapper around
lobpcg written by Andrew Knyazev? 

This is correct, but AME is a special eigensolver. As discussed in the [research note](https://www.osti.gov/servlets/purl/900179) for it, in addition to providing a preconditioner for the curl-curl operator (for AME this is AMS), one also needs to enforce a divergence-free constraint for the LOBPCG subspace in each iteration.

That being said, the AME code is 16 years old at this point and maybe could be updated for new LOBPCG features (I don't recall the constraint option being available in hypre before).
