### ISSUE TITLE
Which MUMPS and PETSC versions are supported under LINUX

### ISSUE THREAD

**Issue by MarijaI** [mfem/mfem#3272]
Hello MFEM friends,

Once again, thank you for the effort and time invested to develop such a powerful program. 

Can you tell me which versions of the `MUMPS `and `PETSC `are supported for `MFEM `under `LINUX `(if there are any limitations).
I am solving Helmholtz equation and need to switch to `LINUX` version. So, now I need to reinstall everything and it would be great if you have any suggestion about program versions that are supported or more suitable than others.

Thanks in advance and best regards,
Marija

**Comment by tzanio** [comment]
Hi Marija,

The version requirements are listed in the `INSTALL` file, for example

- https://github.com/mfem/mfem/blob/master/INSTALL#L711-L712 for PETSc
- https://github.com/mfem/mfem/blob/master/INSTALL#L661 for MUMPS

Hope this helps,
Tzanio

**Comment by MarijaI** [comment]
Thank you a lot. 
Best,
Marija
