### ISSUE TITLE
Complex Eigenvalues for Maxwell Equations

### ISSUE THREAD

**Issue by AntonIatcenko** [mfem/mfem#3279]
Hello Everyone, 

I am working on finding resonant modes of a Maxwell system, and I would like to make part of the domain (slightly) conducting. This would introduce a loss mechanism in the physical system, so the eigenpairs should be complex.

1.  Does MFEM have the functionality for this? I've modified example 13, but I get a Segmentation fault (11) with Invalid permissions (2). Is it because HypreAME can not handle complex problems in the real-block way used by MFEM? Or just me doing something wrong elsewhere? 
2. What is the complex-valued analog of `m->EliminateEssentialBCDiag(ess_bdr, numeric_limits<double>::min());`?

**Comment by mlstowell** [comment]
Hello, @AntonIatcenko,

Unfortunately I don't believe MFEM currently has support for problems with complex eigenvalues. HypreAME is based on LOBPCG which requires real symmetric positive definite linear systems.

I think some users have solved eigenvalue problems with SLEPc which may support complex linear systems. This would probably require translating our sparse matrices to something SLEPc could process.

Another possibility is ARPACK-NG. I know this supports the types of problems you're interested in and I've used this in the past. Again this would require writing some of your own translation code to tie the two packages together. One thing that might help is an old MFEM branch of mine which contains ARPACK wrappers for their real-valued eigenvalue solver. This can be found [here](https://github.com/mfem/mfem/blob/a0b8427774cc3b9df6cb6d6df458bd47806d153b/linalg/arpack.hpp#L197). 

I'm sure @psocratis and I would be interested in adding MFEM support for a complex Maxwell eigensolver. If you can come up with a promising solution perhaps we can help incorporate it into MFEM.

Best wishes,
Mark

**Comment by AntonIatcenko** [comment]
I was hoping to try SLEPc's CISS eigensolver via the direct integration of SLEPc into MFEM, but when I am try to build mfem 4.5 I get 
linalg/hypre.hpp:32:2: error: "MFEM does not work with HYPRE's complex numbers support"
linalg/petsc.hpp:34:2: error: "MFEM does not work with PETSc compiled with complex numbers support"

Could it be an issue specific to my build? Or does MFEM indeed not support complex linear algebra? Its seems very strange since examples 22p and 25p use complex numbers and hypre(?).

**Comment by ruihuasun** [comment]
@AntonIatcenko Hi, do u have any progress on this isssue? I want to solve complex eigen value too. It's hard to believe that a library that's been around for years doesn't support solving complex eigenvalues. (Consider that all wave problems are described by complex value)

**Comment by lobpcg** [comment]
LOBPCG as an algorithm does support complex arithmetic, e.g., as implemented in PETSc, but is limited to Hermitian systems. Other solvers in PETSc support general systems and in complex arithmetic.

**Comment by AntonIatcenko** [comment]
@ruihuasun I have some progress there, but in a pretty roundabout way. 

I have built a complex-valued PETSc (without linking it to MFEM), with download hypre = true. In effect, I have two hypres now: the real-valued one that MFEM uses and the complex-valued one that PETSc is linked with. 

Then within the code I make PETSc matrixes from MFEM matrixes, and use PETSc Matrix  Z = A + PETSC_I*B, where A and B are real matrixes that I got from MFEM; this lets me use PETSc/SLEPc solvers. 

I tried the CISS eigenvalue solver with hypre's ams solver inside, but it's much slower than MFEM's AME and not very stable: it converges with a tight contour around an eigenvalue, but I often lose that eigenvalue when the contour is extended. I tried the two Davidson methods, but with even less success (likely because I'm not coding it up correctly). 

@lobpcg, in the description of lobpcg it says that it computes n smallest eigenvalues; is it inherent to the method? or is possible to get it to compute n eigenvalues closest to a given value? (The simple shifting of the spectrum does not do the trick, I just get the same eigenvalues+shift).

**Comment by lobpcg** [comment]
To compute other eigenvalues, one needs to implicitly transform the original problem into a different one preserving the eigenvectors, where the seeking eigenvalues become largest or smallest. The transformed problem must still be Hermitian. E.g. transform A into (A-aI) squared, not just the shift alone
