### ISSUE TITLE
Cubit mesh reader mismatched new / delete

### ISSUE THREAD

**Issue by juan42** [mfem/mfem#328]
I'm trying to get a valgrind clean run but got stuck when i open a mesh using the netcdf reader. There are a few mismatched new / deletes.

The Cubit mesh reader function also https://github.com/mfem/mfem/blob/master/mesh/mesh_readers.cpp#L1266 never closes the opened netCDF file.

My next idea is to just use the mesh-explorer app to circumvent the issue. I will take a deeper look on that on monday.

**Comment by gelever** [comment]
Is this the same memory leak from #207?

**Comment by juan42** [comment]
I bet it is, yes.
