### ISSUE TITLE
Building MFEM with SUNDIALS

### ISSUE THREAD

**Issue by mariobendra** [mfem/mfem#3280]
Hello,

I am just about to try your SUNDIAL solver with MFEM. Unfortunately, I cannot configure the library successfully with MFEM.
SUNDIALS is built with the following -flags: 
-DEXAMPLES_ENABLE_CXX:BOOL="1" -DHYPRE_INCLUDE_DIR:PATH="/home/bendra/CLion/hypre/src/hypre/include" -DHYPRE_DIR: PATH="/home/bendra/CLion/hypre/src/hypre" -DENABLE_OPENMP:BOOL="1" -DHYPRE_LIBRARIES:STRING="/home/bendra/CLion/hypre/src/hypre/lib/libHYPRE. a" -DHYPRE_LIBRARY_DIR:PATH="/home/bendra/CLion/hypre/src/hypre/lib" -DENABLE_MPI:BOOL="1" -DENABLE_HYPRE:BOOL="1" -DBUILD_SHARED_LIBS:BOOL="0" -DEXAMPLES_INSTALL_PATH: PATH="/home/bendra/CLion/sundials/instdir" -DCMAKE_CXX_STANDARD:STRING="14" -DSUNDIALS_INSTALL_CMAKEDIR:STRING="/home/bendra/CLion/sundials/instdir" -DCMAKE_INSTALL_PREFIX:PATH="/home/bendra/CLion/sundials/instdir"
The MFEM -flags are:
make parallel -j $1 MFEM_USE_OPENMP=YES MFEM_USE_METIS_5=YES METIS_DIR=@MFEM_DIR@/../metis MFEM_USE_SUNDIALS=YES MFEM_USE_SUNDIALS=YES SUNDIALS_OPT=/home/bendra/CLion/sundials/instdir/include SUNDIALS_LIB=/home/bendra/CLion/sundials/instdir/lib

The error is way too long to post. Here is just a short snippet of it.
(g++: warning: /home/bendra/CLion/sundials/instdir/include: linker input file unused because linking not done)  & (`mfem::Vector::ToNVector()':
/home/bendra/CLion/ViennaMag/../mfem-4.2/linalg/vector.hpp:402: undefined reference to `N_VMake_Serial'
/usr/bin/ld: /usr/bin/ld: ../../mfem-4.2/libmfem.a(hypre.o): in function `mfem::HypreParVector::ToNVector()':
hypre.cpp:(.text+0x138): undefined reference to `N_VMake_Parallel'
/usr/bin/ld: ../../mfem-4.2/libmfem.a(vector.o): in function `mfem::Vector::Vector(_generic_N_Vector*)':
vector.cpp:(.text+0x8918): undefined reference to `N_VGetVectorID'
/usr/bin/ld: ../../mfem-4.2/libmfem.a(vector.o): in function `mfem::Vector::ToNVector(_generic_N_Vector*&, long)':
vector.cpp:(.text+0x8d83): undefined reference to `N_VGetVectorID'
collect2: error: ld returned 1 exit status
)

I appreciate your help!
Best regards,
Mario

**Comment by cjvogl** [comment]
@mariobendra, which versions of MFEM and SUNDIALS are you using?

**Comment by mariobendra** [comment]
@cjvogl I am using MFEM 4.2, SUNDIALS 6.4.0, and HYPRE 2.20.0.

**Comment by cjvogl** [comment]
@mariobendra, thank you for the additional info.  SUNDIALS 6.x support was only just added in MFEM 4.5.  You can either build your current version of MFEM with SUNDIALS 5.x or build MFEM 4.5 with your current version of SUNDIALS.

Assuming this adequately resolves the problem, I'm closing the issue... but please feel free to reopen if you have additional questions or if using the suggested versions doesn't solve the problem!

**Comment by mariobendra** [comment]
@cjvogl Thank you! However, I still get an error when using SUNDIALS5.8.0.
I add my building/cmake comands:

##############################################
#        Fetching and building METIS         #
##############################################
  
git clone --depth 1 https://github.com/scivision/METIS.git metis
cd metis
cmake -B build
cmake --build build --parallel
mkdir lib 
ln -s ../build/libmetis.a lib
ln -s src/include include
cd ..
    
##############################################
#        Fetching and building HYPRE         #
##############################################
  
git clone --depth 1 --branch v2.20.0 https://github.com/hypre-space/hypre
cd hypre/src/
./configure --disable-fortran
make -j $1 
cd ../..

##############################################
#       Fetching and building SUNDIALS       #
##############################################

git clone --branch v5.8.0 https://github.com/LLNL/sundials.git
cd sundials
mkdir instdir
cmake -B builddir -DENABLE_MPI:BOOL="1" -DENABLE_HYPRE:BOOL="1" -DEXAMPLES_INSTALL_PATH:PATH="/home/bendra/CLion/sundials/instdir/examples" -DHYPRE_LIBRARIES:STRING="/home/bendra/CLion/hypre/src/hypre;/home/bendra/CLion/hypre/src/hypre/lib/libHYPRE.a" -DEXAMPLES_ENABLE_CXX:BOOL="1" -DBUILD_SHARED_LIBS:BOOL="0" -DSUNDIALS_INSTALL_CMAKEDIR:STRING="/home/bendra/CLion/sundials/instdir" -DCMAKE_CXX_STANDARD:STRING="14" -DHYPRE_LIBRARY_DIR:PATH="/home/bendra/CLion/hypre/src/hypre/lib" -DHYPRE_INCLUDE_DIR:PATH="/home/bendra/CLion/hypre/src/hypre/include"
cd builddir
make -j $1
make install
cd ../..

###############################################
##        Fetching and building MFEM          #
###############################################

wget https://mfem.github.io/releases/mfem-4.2.tgz
tar -xvf mfem-4.2.tgz
rm mfem-4.2.tgz
cd mfem-4.2
make parallel -j $1 MFEM_USE_OPENMP=YES MFEM_USE_METIS_5=YES METIS_DIR=@MFEM_DIR@/../metis MFEM_USE_SUNDIALS=YES SUNDIALS_OPT=/home/bendra/CLion/sundials/include SUNDIALS_LIB=/home/bendra/CLion/sundials/instdir/lib

The error I get is the file attached.

Thank you!
[building.txt](https://github.com/mfem/mfem/files/9960214/building.txt)

**Comment by cjvogl** [comment]
@mariobendra, your error output looks porentially better: it now indicates an include directory problem rather than version incompatibility:

``` bash
In file included from general/optparser.cpp:13:
general/../linalg/vector.hpp:23:10: fatal error: nvector/nvector_serial.h: No such file or directory
   23 | #include <nvector/nvector_serial.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

the include directory that contains `nvector/nvector_seriah.h` is not be properly identified.  Based on the flags you are passing to the `make` command in building mfem, I assume the missing directory is `/home/bendra/CLion/sundials/include`.  What I suggest is
1. verify that `/home/bendra/CLion/sundials/include/vector/nvector_serial.h` exists
2. try using `make parallel -j $1 MFEM_USE_OPENMP=YES MFEM_USE_METIS_5=YES METIS_DIR=@MFEM_DIR@/../metis MFEM_USE_SUNDIALS=YES SUNDIALS_DIR=/home/bendra/CLion/sundials`

the latter suggestion is because the `SUNDIALS_OPT` and `SUNDIALS_LIB` variables are meant to have the compiler flags in them (e.g., `-I` and `-L`).  If you instead set `SUNDIALS_DIR` and not `SUNDIALS_OPT` and `SUNDIALS_LIB`, the values for the latter will be deduced from `SUNDIALS_DIR`

**Comment by mariobendra** [comment]
@cjvogl Thanks a lot. Now the building process finishes fine without errors. See the file attached. 
[build_file.txt](https://github.com/mfem/mfem/files/9980843/build_file.txt)
[build.txt](https://github.com/mfem/mfem/files/9980858/build.txt)


However, the linking to the library/file nvector/nvector_serial.h is still missing.
I am not sure, why it tries to find the library in mfem, while it is located in the folder sundials/instdir/include/
Error message:
In file included from /home/bendra/CLion/ViennaMag/../mfem-4.2/linalg/linalg.hpp:17,
/home/bendra/CLion/ViennaMag/../mfem-4.2/linalg/vector.hpp:23:10: fatal error: nvector/nvector_serial.h: No such file or directory
   23 | #include <nvector/nvector_serial.h>

I can veryfiy that /home/bendra/CLion/sundials/instdir/include/nvector/nvector_serial.h exists.
Should the linking be done through the building process?

Thanks a lot!

**Comment by mariobendra** [comment]
I have to add building it without SUNDIALS, links everything properly.

**Comment by cjvogl** [comment]
@mariobendra, the only thing that comes to mind to check is to ensure the value of `installation_folder` in 

``` bash
wget https://mfem.github.io/releases/mfem-4.2.tgz
tar -xvf mfem-4.2.tgz
rm mfem-4.2.tgz
cd mfem-4.2
make parallel -j $1 MFEM_USE_OPENMP=YES MFEM_USE_METIS_5=YES METIS_DIR=@MFEM_DIR@/../metis MFEM_USE_SUNDIALS=YES SUNDIALS_DIR=$installation_folder/sundials/instdir
```

is `/home/bendra/CLion`.  As an example, you might add the line

``` bash
echo $installation_folder/sundials/instdir
```

to the end of your build script to verify that `SUNDIALS_DIR` is being set properly.  If it is being set properly, I will rope in someone else on the MFEM team who is more familiar with the inner workings of the MFEM make system.

**Comment by mariobendra** [comment]
@cjvogl Thanks a lot!

Yes, I can confirm that the "$installation_folder" is set to be the folder containing mfem metis sundials and hyper "/home/bendra/CLion".

**Comment by cjvogl** [comment]
@tzanio, do we have someone more familiar with the MFEM native make build system who can diagnose why the internal flags are not being set correctly?

In the meantime, you can try using the CMake build system, which I am more familiar with:
``` bash
wget https://mfem.github.io/releases/mfem-4.2.tgz
tar -xvf mfem-4.2.tgz
rm mfem-4.2.tgz
cd mfem-4.2
mkdir build
cd build
cmake -D MFEM_USE_MPI=ON -D MFEM_ENABLE_EXAMPLES=ON -D MFEM_ENABLE_MINIAPPS=ON -D MFEM_USE_OPENMP=ON -D SUNDIALS_DIR=$installation_folder/sundials/instdir ../
make
```

**Comment by tzanio** [comment]
@mariobendra, can you try changing `MFEM_USE_SUNDIALS` and `SUNDIALS_DIR` in `config/defaults.mk` followed by `make distclean` and new build?

**Comment by mariobendra** [comment]
@tzanio Thank you.
I changed `MFEM_USE_SUNDIALS = NO` to `MFEM_USE_SUNDIALS = YES` as well as `SUNDIALS_DIR = @MFEM_DIR@/../sundials-5.0.0/instdir` to `SUNDIALS_DIR = @MFEM_DIR@/../sundials/instdir`
The error remains the same.

**Comment by tzanio** [comment]
Can you check that the following directories exist?

```
/home/bendra/CLion/sundials/instdir/include
/home/bendra/CLion/sundials/instdir/lib
/home/bendra/CLion/sundials/instdir/lib64
```

If they don't, where under `/home/bendra/CLion/sundials` are the `/include` and `/lib` subdirectories?

**Comment by v-dobrev** [comment]
@mariobendra, just one point to be careful about: when you modify `config/defaults.mk`, you need to re-configure MFEM (with `make config [additional options]`) in order for those changes to take effect. If you did not run `make distclean` and just ran `make` then the new settings from `defaults.mk` were not used. If you used `make parallel [options]` then that does MFEM re-configuration and the problem is something else.

Also, if you used the `make parallel [options]` command similar to what you posted above, then make sure to remove the options `SUNDIALS_OPT=...` and `SUNDIALS_LIB=...` -- setting these on the command line will overwrite the values defined in `defaults.mk` (which are based on `SUNDIALS_DIR`).

**Comment by mariobendra** [comment]
@tzanio & @v-dobrev Thank you!
I managed to build it. However, when running some examples, I get the error:
´...../../sundials/instdir/lib/libsundials_cvode.a(cvode_ls.c.o):cvode_ls.c:(.text+0x1356): first defined here
/usr/bin/ld: ../../sundials/instdir/lib/libsundials_cvodes.a(cvodes_ls.c.o): in function `CVodeGetNumLinRhsEvals':
cvodes_ls.c:(.text+0x13c8): multiple definitions of `CVodeGetNumLinRhsEvals'...´
I have attached the entire error file as well as the building script.
[script.txt](https://github.com/mfem/mfem/files/10066663/script.txt)
[error.txt](https://github.com/mfem/mfem/files/10066667/error.txt)

**Comment by v-dobrev** [comment]
Probably the issue is that you are linking with both `../../sundials/instdir/lib/libsundials_cvode.a` and  `../../sundials/instdir/lib/libsundials_cvodes.a`. Try linking with just one of the two -- e.g. MFEM links just with `cvodes`.
