### ISSUE TITLE
PETSc usage in MFEM

### ISSUE THREAD

**Issue by thorvath12** [mfem/mfem#3282]
Hello,

I ran into an issue when using PETSc in MFEM. I have a good initial guess for the solution to the linear system, so I would like to start GMRES from a nonzero initial guess. I was experimenting with the hdg_poissonp example (hdg branch), where the solver is set up as

```
PetscLinearSolver *petsc_solver;
petsc_solver = new PetscLinearSolver(MPI_COMM_WORLD, "solver_");
```

I tried the following two-line long PETSc input file

```
-solver_ksp_type minres
-solver_ksp_initial_guess_nonzero true
```

but the second line seems to be ignored. The number of iterations is the same even if it is set to "false".

Any help would be appreciated.

Best,
Tamas

**Comment by jandrej** [comment]
Does `Lambda` include your initial guess satisfying boundary conditions?

**Comment by thorvath12** [comment]
The ParGridFunction `lambda` satisfies the BC. The projection `lambda.ProjectCoefficientSkeleton(ucoeff);` should take care of that. I just pushed my experimental version, where I have a few added lines

```
HypreParVector *Lambda =  new HypreParVector(M_space);
*Lambda = 0.0;
Lambda->Add(1.0, lambda);
```

With these lines, `Lambda` should be fine.

**Comment by thorvath12** [comment]
If I set the problem up such that u = 1, so the projection contained in `Lambda` is the exact solution, I would expect 0 iterations, and it does more than that. (Again, the same number independently of the second line).

**Comment by jandrej** [comment]
Got it. That seems suspicious. @stefanozampini do you have a gut feeling about this?

**Comment by stefanozampini** [comment]
@thorvath12 Yep, the option was always superseeded by the value of `iterative_mode`. https://github.com/mfem/mfem/pull/3309 should fix your problem. let me know

**Comment by tzanio** [comment]
Discussion continued in #3309.
