### ISSUE TITLE
Output file of paraview_dc of example5 can not opened  by the  program Paraview

### ISSUE THREAD

**Issue by fengerhan** [mfem/mfem#3286]
Hi all.

I find when I change the output file format of `paraview_dc` of example5 to `VTKFormat::ASCII`,
```c++
paraview_dc.SetDataFormat(VTKFormat::ASCII);
```
the output file Example5.pvd can not opened  by the  program Paraview.  But when I the `VTKFormat::BINARY` format, the output file can opened  by the  program Paraview correctly.
Who can tell me how to fix the problem?
My version of  mfem is 4.4.

**Comment by pazner** [comment]
This is working for me (I tried running `./ex5` with no arguments). What are the exact arguments you are using? Also, what version of ParaView are you using? Example 5 calls `paraview_dc.SetHighOrderOutput(true)` which will enable output using the arbitrary-order Lagrange elements, which are supported in ParaView 5.5 and newer.

**Comment by fengerhan** [comment]
I want to use the function of paraview_dc to save my result. So I run ./ex5 with no arguments to learn how to use the  paraview_dc.
My Paraview version is 5.9.

**Comment by pazner** [comment]
Maybe you are running into the issue resolved in PR #3145 since you are using MFEM 4.4. Can you try with 4.5 or master?

**Comment by pazner** [comment]
Closing under the assumption that #3145 fixes this issue. Please re-open if there are other problems.
