### ISSUE TITLE
Which integrator to use when coefficient is a function of surface normal?

### ISSUE THREAD

**Issue by amit112amit** [mfem/mfem#3289]
I am new to MFEM. This is not an issue but a question.

I am trying to solve a PDE on a 3D surface $\Omega$ which has a term
$$\int_{\Omega}\nabla \cdot \left(\vec{g}(\vec{n}(x))\ u\right) v$$
where $\vec{n}(x)$ is the surface normal.
After carrying out integration by parts, I shifted the derivative to the test function $v$ as follows:
$$-\int_{\Omega} \vec{g}(\vec{n}(x))u \cdot \nabla v $$
From the list of `BilinearFormIntegrators`, I found the `MixedScalarWeakDivergenceIntegrator` to be the most appropriate. I also found [how to calculate normals](https://mfem.org/howto/outer_normals/) in MFEM. My question is do I need to write a custom integrator for this case, or is there some existing function already implementing this?

**Comment by mlstowell** [comment]
Hello, @amit112amit,

It looks like you _will_ need a custom integrator. This is mainly because your vector-valued coefficient `g` seems to be a function of the surface normal. This is not common so we don't have any integrators, as far as I know, with such coefficients.

I'll be happy to offer more specific advice if needed.

Best wishes,
Mark

**Comment by amit112amit** [comment]
Thank you, for the reply @mlstowell.
I will attempt to write a custom integrator for this case. Then, I will be able to ask more specific questions.
Once I get the code working, I will close this issue.

**Comment by amit112amit** [comment]
I went through the documentation https://mfem.org/integration/. As of now, I think I have enough information about how to implement the custom integrator. I will ask another question if I face any difficulty. Thank you for the prompt response!
