### ISSUE TITLE
Periodic mesh with other boundaries

### ISSUE THREAD

**Issue by vikramsg** [mfem/mfem#329]
This is with reference to what I posted here [205](https://github.com/mfem/mfem/issues/205#issuecomment-339367993). Please tell me if you want me to delete that comment. 

The issue was with reference to the following mesh. Think of it as two cylinders. The inside cylinder is a wall and the outside cylinder is say freestream, meaning two different boundary conditions for the two. In addition I want the z = 0 and z = Lz surfaces to be periodic (I hope the axis makes them clear). 

![per_ch](https://user-images.githubusercontent.com/13407380/32006838-7dabcc16-b9b0-11e7-9def-74a112c96754.png)

I generated the mesh using GMSH. I have two boundaries "lo" and "hi" which I want to convert to the periodic format. This is a simpler version with only the wall boundary condition.
[per_ch.txt](https://github.com/mfem/mfem/files/1419123/per_ch.txt)

So, first I convert it to MFEM format. 

[ch.txt](https://github.com/mfem/mfem/files/1419130/ch.txt)

And then use a script to convert lo and hi to periodic and the vertices in the other boundaries are also changed to only have the corresponding periodic vertices. The periodic boundary elements are removed from the boundary definition. 

[new_ch.txt](https://github.com/mfem/mfem/files/1419187/new_ch.txt)

So, does this make sense, especially in terms of changing vertices of other boundary elements.

**Comment by tzanio** [comment]
Hi @vikramsg,

This may or may not be an issue, but there are no boundary elements defined on the outer loop of the mesh you attached, so to MFEM it looks like this:
![glvis_s01](https://user-images.githubusercontent.com/1278247/32356777-c8bbd328-bff4-11e7-9df0-d1bc7ec396bb.png)

Regarding the periodic mesh -- the `new_ch.txt` file doesn't quite seem right. If I understand correctly you should have 48 vertices and 8 z-aligned + 12 inner-loop + 48 outer-loop boundary faces (that are currently missing).

All you have to do is pick one of the z surfaces as slave, e.g. z=0, and the other one as master, e.g. z = Lz, delete the boundary elements on z=0 and use replace the vertices on z=0 with the indices of their z=Lz periodic vertex in the description of the volume elements. (Ideally you will renumber the vertices so you have a tight packing of 48, but you can also keep the 64 indices and just not use some of them).

Hope this helps,
Tzanio

**Comment by mlstowell** [comment]
Hi, @vikramsg,

It may interest you to know that we have a function that can create a periodic mesh from a valid starting mesh (in serial).  It's not in the master branch of MFEM but you could certainly copy it into your application.  You can find this function in the bravais-dev branch in the files miniapps/common/bravais.?pp.  The function name is MakePeriodicMesh.  It returns a pointer to a new periodic MFEM mesh object.  Its arguments are a standard mesh and a std::vector containing translation vectors (as well as an optional verbosity flag).  The translation vectors are used to identify pairs of nodes where one node lies on a master surface and the other is its counterpart on the slave surface.

Best wishes,
Mark

**Comment by tzanio** [comment]
Direct link to Mark's source: https://github.com/mfem/mfem/blob/bravais-dev/miniapps/common/bravais.cpp#L6864-L7148

**Comment by vikramsg** [comment]
Hi @tzanio ,

Thanks for looking it over. I don't know how the outer boundary faces were deleted but sorry for that. Your explanation of picking a face as slave etc was exactly what I did. I just did not renumber the vertices. 

I will have a look at the @mlstowell mentioned code. Thanks for that.

**Comment by tzanio** [comment]
Hi @vikramsg, were you able to figure this out? -Tzanio

**Comment by vikramsg** [comment]
Hi @tzanio. I used code from the branch suggested by @mlstowell . I want to close this but just wanted to know whether there is a good test to figure out whether the periodic boundaries have been placed correctly.

**Comment by mlstowell** [comment]
Hi, @vikramsg, you can use the Euler number of the mesh to verify a necessary but not sufficient condition.  Specifically, if all of the mesh boundaries are periodic then the Euler number should be zero.

**Comment by tzanio** [comment]
Another test could be to run Example 9 transporting a "bump" over the periodic boundaries.

**Comment by vikramsg** [comment]
Thanks, @mlstowell and @tzanio. I will close this.
