### ISSUE TITLE
Mixed boundary conditions for static linear elastic problem

### ISSUE THREAD

**Issue by vasily-golubev** [mfem/mfem#3291]
Hello, everyone.

Thanks a lot for MFEM.
I try to solved the static problem of linear elasticity.
If I want to fix the horizontal component of the displacement (on the boundary) and set tangential stress (Sigma_xy)  to zero, I should use the code like:
```
GridFunction x(fespace);
x = 0.0;
Array<int> ess_tdof_list, ess_bdr(mesh->bdr_attributes.Max());
ess_bdr = 0;
ess_bdr[1] = 1;
ess_bdr[3] = 1;
fespace->GetEssentialTrueDofs(ess_bdr, ess_tdof_list, 0);
VectorArrayCoefficient f(dim);
Vector pull_force(mesh->bdr_attributes.Max());
pull_force = 0.0;
f.Set(0, new PWConstCoefficient(pull_force));
f.Set(dim - 1, new PWConstCoefficient(pull_force));
LinearForm *b = new LinearForm(fespace);
b->AddBoundaryIntegrator(new VectorBoundaryLFIntegrator(f));
b->Assemble();
a->FormLinearSystem(ess_tdof_list, x, *b, A, X, B);
```
Am I right? The full example I posted here: https://github.com/vasily-golubev/mfem_static_example/blob/main/static_elasticity.cpp

**Comment by tzanio** [comment]
This looks correct to me.

In particular the call `fespace->GetEssentialTrueDofs(ess_bdr, ess_tdof_list, 0);` will extract the degrees of freedom corresponding to the `x`-components on boundary attributes `2` and `4` and then `FormLinearSystem` will make impose zero Dirichlet b.c. on them.

**Comment by vasily-golubev** [comment]
Great, many thanks.

I used the ElasticityIntegrator to solve 2D static elastic problem. However, as far as I understand, this class implicitly implies the plain strain problem (Dz==0, D-displacement). If I want to describe the plate behaviors (plain stress problem, Sigma_zz==0, Sigma - stress tensor), I have to change mechanical properties as: https://fenics-solid-tutorial.readthedocs.io/en/latest/2DPlaneStrain/2D_Elasticity.html (the end of "Governing equations" section).
Am I right?
Maybe it is usefull to add the other constructor like ElasticityIntegrator(lambda, mu, true\false for stress\strain problem)?

**Comment by vasily-golubev** [comment]
Sorry, if it is not important, the issue can be closed. @tzanio
