### ISSUE TITLE
Micro finite element generated from micro CT

### ISSUE THREAD

**Issue by shani9383** [mfem/mfem#3295]
Hi,
Do you have any knowledge to share regarding Micro finite element (micro-FE) generated from micro CT. Micro-FE models are generated from the segmented micro CT scans using conversion of the scans voxels to equally sized 8 node HEX elements. This conversion process generates models with million elements deriving huge number of DOF.  I wish to conduct a simple linear-elastic analyses using MFEM code. 
1. Are there mesh generation tools that work with MFEM that I can use? 
2. Any information on conducting micro FE (generated from micro CT scans) by using MFEM  code will be helpful.

Tnx 
Shani

**Comment by jandrej** [comment]
> Are there mesh generation tools that work with MFEM that I can use?
GMSH, Cubit (Coreform) and Pointwise can output mesh formats that can be directly read by MFEM.

**Comment by tzanio** [comment]
I am not sure if this is directly relevant, but @benzwick has the [MVox Mesh Voxelizer](https://github.com/benzwick/mvox)
