### ISSUE TITLE
Normal traction boundary conditions for linear elasticity

### ISSUE THREAD

**Issue by queen333597** [mfem/mfem#3296]
I have a problem with a cylindrical geometry. I know how to apply force in x, y, or z direction (below). But how can I apply force (displacement) normal to the surface (in radial direction)?

```
VectorArrayCoefficient f(dim);
Vector pull_force(mesh->bdr_attributes.Max());
pull_force = 0.0;
f.Set(0, new PWConstCoefficient(pull_force));
f.Set(dim - 1, new PWConstCoefficient(pull_force));
LinearForm *b = new LinearForm(fespace);
b->AddBoundaryIntegrator(new VectorBoundaryLFIntegrator(f));
b->Assemble();
```
Thank you.

**Comment by tzanio** [comment]
Is this an axisymmetric problem, or is it a 3D problem where the geometry is just cylindrical?

**Comment by queen333597** [comment]
The loading is axisymmetric, but the problem is not, so it has to be treated as a 3D problem.

**Comment by tzanio** [comment]
In that case, imposing boundary conditions that mix different x/y/z components is not straightforward.

@vladotomov, can you help with that?

**Comment by vladotomov** [comment]
@queen333597 for strong enforcement, you should check example 28.

The other option is to enforce the BC weakly by adding face integrators, but these would depend on the equations, would involve penalty constants, etc (Nitsche's method). Our expert for this is @atallah727.

**Comment by queen333597** [comment]
Thank you. I'm trying to apply traction, so I was looking at example 27 where Neumann boundary condition is applied on boundary with attribute 4. However, I can't understand how the direction of the load is provided.

**Comment by queen333597** [comment]
Thank you. I'm trying to apply traction, so I was looking at example 27 where Neumann boundary condition is applied on boundary with attribute 4:  `b.AddBoundaryIntegrator(new BoundaryLFIntegrator(m_nbcCoef), nbc_bdr); `. However, I can't understand how the direction of the load is provided. 
In example 2 the direction of the applied load is given using: `f.Set(dim-1, new PWConstCoefficient(pull_force));` but I don't see anything similar to that in example 27. I'm wondering how we ensure that load is applied normal to surface with attribute 4.

**Comment by queen333597** [comment]
Is there a way to access/update each of the entities in `f ` as above? So instead of setting all entities at once by: `f.Set(dim - 1, new PWConstCoefficient(pull_force));`, loop over entities and set values one by one.

**Comment by vladotomov** [comment]
Hi @queen333597,

If you want `f` to contain space-dependent vectors that depend on the normal direction to the boundary element, you'd have to create your own `VectorCoefficient` for `f`. Its implementation will be using the example normal calculation you wrote above. Is this what you need?

**Comment by queen333597** [comment]
Thank you for your response. I tried defining a new `Coefficient` class for `f` using the example code above and in the corresponding `Eval` method I try to return `n(i)`, where `i` indicates the direction that the load is applied. However, I get a convergence error when trying this: `Newton solver did not converge`. Do you have any suggestions on how I could resolve that?

**Comment by nma20** [comment]
Hello queen333597, can you try defining an analytical solution on a square with a zero traction condition to see if the solver converges? Then try the same thing but with a non-zero constant traction condition.

**Comment by atallah727** [comment]
Hello queen333597, can you try defining an analytical solution on a square with a zero traction condition to see if the solver converges? Then try the same thing but with a non-zero constant traction condition.

**Comment by queen333597** [comment]
I was able to resolve the convergence issue by starting with a simple problem as your suggested. Thank you very much!

**Comment by QibangLiu** [comment]
> Thank you for your response. I tried defining a new `Coefficient` class for `f` using the example code above and in the corresponding `Eval` method I try to return `n(i)`, where `i` indicates the direction that the load is applied. However, I get a convergence error when trying this: `Newton solver did not converge`. Do you have any suggestions on how I could resolve that?

Hello, May I know how to define this type of coefficient? Thanks.
