### ISSUE TITLE
Any example of Discontinuous Galerkin (DG)/Discontinuous Petrov-Galerkin (DPG) in electromagnetic field?

### ISSUE THREAD

**Issue by TangLaoya** [mfem/mfem#3299]
Dear all,
I found there are some DG/DPG examples, but didn't find any DG/DPG example applied in electromagnetic field calculation, could anyone provide such kind of examples?

Thanks,
Tang laoya

**Comment by psocratis** [comment]
@TangLaoya, 

There is a PR in review about DPG, including time-harmonic Maxwell equations. Please see `./miniapps/dpg/pmaxwell.cpp` in #3234.

Best,

Socratis

**Comment by TangLaoya** [comment]
That's great, thank you very much!
