### ISSUE TITLE
Is mfem suitable for CFD? 

### ISSUE THREAD

**Issue by Watchmojo** [mfem/mfem#33]
Hi, 

Thank you for sharing this nice library. 

I have three questions here:
1. Is it possible for mfem to do CFD? 
2. I know that spectral-element/hp method commonly uses GLL collection nodes. Is it possible add GLL collection nodes in mfem?
3. Is Neumann boundary condition implemented in mfem?

Thank you,
Frank

**Comment by tzanio** [comment]
Hi @XFangUM,

You can certainly use MFEM to develop various CFD applications, and several projects have done this in the past, for example

- http://etna.mcs.kent.edu/volumes/2011-2020/vol41/abstract.php?vol=41&pages=42-61
- http://epubs.siam.org/doi/abs/10.1137/120884109
- http://llnl.gov/casc/blast/

We have native support for high-order methods throughout the library, and we do use the Gauss-Lobatto points for the degrees of freedom of continuous finite element spaces defined on quad/hex meshes. We do support both Dirichlet and Neumann boundary conditions in several different contexts, see http://mfem.org/examples.

Hope this helps. Please let us know if you have any further questions,

Tzanio

**Comment by Watchmojo** [comment]
Hi, Tzanio,

Thank you for your prompt reply. 

My research interests are mainly on the direct numerical simulation (DNS) and large eddy simulation (LES) of incompressible turbulent flows. Writing a high-order FEM code for turbulent simulation has been one of my interests for a long time. I know some other open source codes, such as Nektar++ and Nek5000, are written for turbulent flows. However, I found them too bulky and different to learn. It appears that MFEM can be a good starting point for me. 

Thank you very much. 
Frank

**Comment by Watchmojo** [comment]
Hi, Tzanio,

Because I am intended to simulate transitional turbulent flows, computational efficiency is of great importance for my research. 

I have written a FVM code using Hypre, which works like magic. Using 200 cores for 10 million cells, it takes about 1 second for each time step, which solves the Poisson equation twice. 

I want to confirm the speed before looking into mfem and write an NS solver. 

When I tried to run your ex4p with different cores in my personal computer, the parallel efficiency seems to be not so good. 
"mpirun -np 4 ./ex4p -m ../data/periodic-square.mesh -o 3" gives PCG wall clock time = 3.340000 s
"mpirun -np 1 ./ex4p -m ../data/periodic-square.mesh -o 3" gives PCG wall clock time = 4.830000 s

Could you please give me some information about the speed of this library based on your own experience? Like, what is the most massive case you have run? How many degree of freedom? How many cores were you using? How long does it take to solve one Poisson equation?

**Comment by tzanio** [comment]
Hi Frank,

Large-scale parallel scalability is absolutely one of our main goals, and that's the reason why we are so tightly integrated with the _hypre_ library. For example, in parallel we directly assemble in _hypre_'s parallel matrix format, so we can naively call its algebraic multigrid (AMG) solvers with minimal overhead. (Another advantage is that we can also provide _hypre_ with discretization-specific information as in the AMS and ADS solvers.)

MFEM-based applications have been scaled to 100K cores and billions of unknowns. Here is one example: https://computation.llnl.gov/project/blast/images/NewBLASTScaling.png

Note that Example 4p, is not exactly representative since H(div) is quite a challenging problem for AMG, and the performance of the _hypre_ solvers in general deteriorates with the order. (The PCG wall clock time mostly measures _hypre_ performance here.)

Cheers,
Tzanio

**Comment by Watchmojo** [comment]
Hi, Tzanio,

Indeed, Helmholtz/Poisson equation takes up 90% of the computational time when simulating incompressible flow. 

Could you please give me some suggestions, if I want to learn MFEM and then write an NS solver? Like, where to begin? which books/papers should I read? I have some experiences with hypre and spectral-element method. Surprisingly, I have never heard of Raviart-Thomas finite elements in spectral-element method before. 

Thank you very much,
Frank

**Comment by tzanio** [comment]
Hi Frank,

I suggest starting with the MFEM examples, reading through them and making sure you understand how the math concepts translate to C++ objects. Example 5 is probably the closest thing we have to an incompressible flow solver.

I'll list a few books below, but I hope that other users or members of the team have additional suggestions:

- Johnson, Claes, _Numerical Solution of Partial Differential Equations by the Finite  Element Method_
- Chen, Zhangxin, _Finite Element Methods and their Applications_
- Huertra, Antonio and Donea, Jean, _Finite Element Methods for Flow Problems_
- Braess, Dietrich, _Finite elements: theory, fast solvers, and applications in elasticity theory_
- Ciarlet, Philippe G. _Finite Element Method For Elliptic Problems_

Hope this helps,
Tzanio

**Comment by Watchmojo** [comment]
Hi, Tzanio,

Thank you very much for your help. 

Frank
