### ISSUE TITLE
Too low order of integration for VectorDomainLFIntegrator

### ISSUE THREAD

**Issue by thorvath12** [mfem/mfem#330]
Hello,

We've noticed that the order of integration for VectorDomainLFIntegrator::AssembleRHSElementVect in line 174 in liniteg.cpp is set as
`int intorder = el.GetOrder() + 1;`

while for DomainLFIntegrator::AssembleRHSElementVect in line 41 it is
`ir = &IntRules.Get(el.GetGeomType(), oa * el.GetOrder() + ob);`

with oa = 2, ob = 0 for default. Similiarly for VectorFEDomainLFIntegrator::AssembleRHSElementVect   in line 291
`int intorder = 2*el.GetOrder();`

We had to increase the order in VectorDomainLFIntegrator::AssembleRHSElementVect to obtain the right solution to our problem.

Is there any reason why the order is set lower for the vector valued case? Or why don't we have the chance to set something like oa and ob in the scalar care?

The same applies for BoundaryLFIntegrator::AssembleRHSElementVect and VectorBoundaryLFIntegrator::AssembleRHSElementVect.

Thanks
Tamas

**Comment by tzanio** [comment]
Hi Tamas,

Admittedly these default values are somewhat ad hoc, and for historical reasons we may have ended up with different choices in closely related integrators. I am open to unifying these defaults, @v-dobrev may provide more details why these particular values were chosen.

That being said, you can always overwrite the quadrature rule with the `LinearFormIntegrator:: SetIntRule` method. This gives you full control of the order and type of integration used.

Tzanio

**Comment by tzanio** [comment]
I'm closing this issue now. Feel free to re-open if you'd like to discuss it further (or better yet propose a PR :)).
