### ISSUE TITLE
Applying force in example 10 (nonlinear elasticity)

### ISSUE THREAD

**Issue by queen333597** [mfem/mfem#3300]
In example 2, a force is applied on one the boundaries, and it contributes to the linear form b, as below. 
I am wondering how a similar boundary condition can be applied for a nonlinear elastic problem (e.g. example 10). Where should the pull_force be added in the nonlinear form?

```
   // 7. Set up the linear form b(.) which corresponds to the right-hand side of
   //    the FEM linear system. In this case, b_i equals the boundary integral
   //    of f*phi_i where f represents a "pull down" force on the Neumann part
   //    of the boundary and phi_i are the basis functions in the finite element
   //    fespace. The force is defined by the VectorArrayCoefficient object f,
   //    which is a vector of Coefficient objects. The fact that f is non-zero
   //    on boundary attribute 2 is indicated by the use of piece-wise constants
   //    coefficient for its last component.
   VectorArrayCoefficient f(dim);
   for (int i = 0; i < dim-1; i++)
   {
      f.Set(i, new ConstantCoefficient(0.0));
   }
   {
      Vector pull_force(mesh->bdr_attributes.Max());
      pull_force = 0.0;
      pull_force(1) = -1.0e-2;
      f.Set(dim-1, new PWConstCoefficient(pull_force));
   }

   LinearForm *b = new LinearForm(fespace);
   b->AddBoundaryIntegrator(new VectorBoundaryLFIntegrator(f));
   cout << "r.h.s. ... " << flush;
   b->Assemble();
```

Thank you.

**Comment by vladotomov** [comment]
Hi @queen333597,

If the force depends on the unknown, it should be added to the `NonlinearForm` as a `NonlinearFormIntegrator`. Otherwise, it can go to the right-hand side as above.

**Comment by queen333597** [comment]
Thank you for your answer. My force is independent of the unknown, so I created a `LinearForm *F` that includes the force (similar to `LinearFrom *b`above). I tried adding it to the right-hand side by adding `z.Add(1.0, F);` to either the `HyperelasticOperator` class or `HyperelasticOperator::Mult` (in example 10), but none of those affects the results. Would you guide me more about where `F` must be added?
Thank you

**Comment by vladotomov** [comment]
Hi @queen333597,

Looking at ex10, the RHS contribution should be added in `HyperelasticOperator::ImplicitSolve`, replacing the `zero` vector. Note that `HyperelasticOperator::Mult` is used only for explicit time integration, i.e., it doesn't perform a nonlinear solve.

**Comment by queen333597** [comment]
I added force to the `zero` vector by `zero.Add(1.0, F)`; and it's working perfectly. Thank you very much!
