### ISSUE TITLE
Calculating gradients on GPU

### ISSUE THREAD

**Issue by ivhak** [mfem/mfem#3310]
Hello,

I am working on a problem where I need to solve a Laplace equation with four different sets of boundary conditions, the solutions of which are $\phi_{\text{lv}}$, $\phi_{\text{rv}}$, $\phi_{\text{epi}}$ and $\psi_{\text{ab}}$. For the algorithm I am using, I also need the gradients for each of these: $\nabla\phi_{\text{lv}}$, $\nabla\phi_{\text{rv}}$, $\nabla\phi_{\text{epi}}$ and $\nabla\psi_{\text{ab}}$.

The algorithm that uses the Laplace solutions and their gradients is implemented with `MFEM_FORALL` to run on a GPU. I am also using BoomerAMG and HyprePCG to solve the Laplace equations on GPU. So, the solutions are already in device memory when I need them for the final algorithm. However, I have not found a way to compute the gradients on the GPU.

The gradients  are computed as in the following listing (only $\nabla\phi_{\text{epi}}$ is shown, but the approach is exactly the same for the other gradients).

```cpp
H1_FECollection fec(1, pmesh.Dimension());

ParFiniteElementSpace fespace_scalar_h1(&pmesh, &fec);
ParFiniteElementSpace fespace_vector_h1(&pmesh, &fec, 3, mfem::Ordering::byVDIM);

ParGridFunction x_phi_epi(&fespace_scalar_h1);
x_phi_epi.UseDevice(true);
// Goes on to solve the Laplace equation, result in x_phi_epi

// Compute gradients for phi_epi
ParGridFunction grad_phi_epi(&fespace_vector_h1);
grad_phi_epi.UseDevice(true);
{
    GradientGridFunctionCoefficient ggfc(&x_phi_epi);
    grad_phi_epi.ProjectCoefficient(ggfc);
}
```
From what I can see in the profiler (`rocprof` on an AMD GPU), the following currently happens
1. `x_phi_epi` is copied from device back to host
2. `grad_phi_epi` is computed on the host
3. `grad_phi_epi` is copied from host to device

Ideally, the following would happen instead
1. Space for `grad_phi_epi` is allocated on device
2. Gradients are computed on device

Is there any way to do this?

**Comment by ivhak** [comment]
I found a workaround that works in my specific problem. I know that the mesh is tetrahedral, and that the elements are first order $H^1$, so I can simply calculate the gradients directly using the method outlined in Section 3.1 of "A comparison of methods for gradient field estimation on simplicial meshes" (Mancinelli et.al., 2019):

$$
\begin{align*}
    \nabla f_{\tau} 
         =& (f_j - f_i)\frac{(v_i - v_k) \times (v_h -v_k)}{2V_{\tau}} \\
         +& (f_k - f_i)\frac{(v_i - v_h) \times (v_j -v_h)}{2V_{\tau}} \\
         +& (f_h - f_i)\frac{(v_k - v_i) \times (v_j -v_i)}{2V_{\tau}}
\end{align*}
$$

In my case $f_i$, $f_j$, $f_k$ and $f_h$ are solutions to the Laplace-Equation in each DoF of the element. 

This is straightforward to compute on the GPU by using an element-to-DoF table (`mfem::FiniteElementSpace::GetElementToDofTable()`) for both finite element spaces ( $H^1$ and $L^2$) and the coordinate of each vertex:
```cpp
Vector local_vertices;
pmesh.GetVertices(local_vertices);
const double *vert = local_vertices.Read();

const Table& h1_element_to_dof = fespace_scalar_h1.GetElementToDofTable();
const Table& l2_element_to_dof = fespace_vector_l2.GetElementToDofTable();

const int *h1_I = h1_element_to_dof.ReadI();
const int *h1_J = h1_element_to_dof.ReadJ();

const int *l2_I = l2_element_to_dof.ReadI();
const int *l2_J = l2_element_to_dof.ReadJ();

const int num_elements = pmesh.GetNE();
const int num_vertices = pmesh.GetNV();

const double *epi_vals = x_phi_epi->Read();
double *epi_grads = grad_phi_epi->Write();

ParGridFunction *grad_phi_epi = new ParGridFunction(&fespace_vector_l2);
grad_phi_epi->UseDevice(true);

compute_gradient(epi_grads, epi_vals, vert,
                 num_elements, num_vertices,
                 h1_I, h1_J, l2_I, l2_J);
```
Then if I need the gradients in $H^1$, an averaging of the gradients in the elements surrounding each node seems to suffice.

**Comment by v-dobrev** [comment]
Hi @ivhak,

Computing the gradient of a scalar L2 or H1 `GridFunction`, as a vector L2 or H1 `GridFunction`, on GPU can be done using the `QuadratureInterpolator` and "ElementRestriction" operators of the two FE spaces. For example (note that this code is not tested and it may have issues in the case when `grad` is in vector H1 space on quad or hex meshes):
```c++
void compute_grad(GridFunction &phi, GridFunction &grad)
{
   // Assuming all elements are the same type

   const FiniteElementSpace *phi_fes = phi.FESpace();
   const FiniteElementSpace *grad_fes = grad.FESpace();

   const Operator *grad_elem_restr =
      grad_fes->GetElementRestriction(ElementDofOrdering::NATIVE);

   // Temporary Q-vector and E-vector for gradients
   Vector grad_e_vec(grad_elem_restr->Height());

   // Convert phi (L-vector) --> phi_e_vec (E-vector)
   const bool use_tensor_products = UsesTensorBasis(*phi_fes);
   const ElementDofOrdering e_ordering = use_tensor_products ?
                                         ElementDofOrdering::LEXICOGRAPHIC :
                                         ElementDofOrdering::NATIVE;
   const Operator *phi_elem_restr = phi_fes->GetElementRestriction(e_ordering);
   Vector phi_e_vec(phi_elem_restr->Height());
   phi_elem_restr->Mult(phi, phi_e_vec);

   // Compute gradiants: phi_e_vec (E-vector) --> grad_e_vec (Q-vector and
   // E-vector)
   const FiniteElement *grad_fe = grad_fes->GetFE(0);
   const QuadratureInterpolator *qi =
      phi_fes->GetQuadratureInterpolator(grad_fe->GetNodes());
   // Set the output layout to be NQPT x SDIM x NE which is compatible with
   // the E-vector layout for the gradient.
   qi->SetOutputLayout(QVectorLayout::byNODES);
   qi->DisableTensorProducts(!use_tensor_products);
   qi->PhysDerivatives(phi_e_vec, grad_e_vec);
   phi_e_vec.Destroy();

   // Accumulate/permute the E-vector gradients into the L-vector gradients
   grad_elem_restr->MultTranspose(grad_e_vec, grad);

   // If the gradient FE space is not discontinuous, perform averaging.
   if (!grad_fes->IsDGSpace())
   {
      Vector grad_overlap(grad.Size());
      grad_e_vec = 1.0;
      grad_elem_restr->MultTranspose(grad_e_vec, grad_overlap);
      grad /= grad_overlap;
   }
}
```
We definitely need to provide a simpler interface for doing this on GPU. One approach could be to ensure the code you tried first works:
```c++
    GradientGridFunctionCoefficient ggfc(&x_phi_epi);
    grad_phi_epi.ProjectCoefficient(ggfc);
```
after proper extensions of `GradientGridFunctionCoefficient` and `GridFunction::ProjectCoefficient`.

**Comment by ivhak** [comment]
Thank you for the answer, @v-dobrev.

Since I know I only will be using tetrahedral meshes with first-order $H^1$ elements, and was able to get the exact same results when using the formula for $\nabla f_\tau$ as I did with `GradientGridfunctionCoefficient`, I will stick to that. But it is very good to know that is possibly to do on GPU in the general case!
