### ISSUE TITLE
Development of New Example

### ISSUE THREAD

**Issue by como2099** [mfem/mfem#3311]
@Jeff-Hadley @Mateus-A-R-Braga and I will be developing a new example. It will solve the incompressible Navier-Stokes equations for a two-dimensional stagnation flat plate geometry, with a comparison study to the incompressible Blasius flat plate solution (time permitting). We will build off of existing examples 9, 14, 17, 18 and the Navier miniapp. This is a project for a class at CU Boulder this fall semester, so we plan to have this "issue" resolved by 11/28/2022 via a pull request that will introduce our new example (in order to fit into the timeline necessitated by the class).

@jedbrown

**Comment by tzanio** [comment]
Welcome @como2099, @Jeff-Hardley and @Mateus-A-R-Braga!

Please let us know if you have any questions.
