### ISSUE TITLE
Conjugate Gradient Solver in example 9

### ISSUE THREAD

**Issue by salomole** [mfem/mfem#3312]
Hello everyone,

I would like to know the Conjugate Gradient Method which is used to solve the advection equation of example 9. On line 469 it is noted: `M_solver.iterative_mode = false;`, it means that we don't use an iterative method, am I wrong? In this case, why define a preconditioner, a tolerance and a maximum number of iterations?

Best wishes,

SL

**Comment by pazner** [comment]
`iterative_mode = false` just tells the CG solver to use zero initial guess (instead of using the second argument to `Mult` as an initial guess):
https://github.com/mfem/mfem/blob/40c49ed9922c0a739d01c8c4ffd038a537614eb8/linalg/operator.hpp#L654-L659
