### ISSUE TITLE
How to form a multiple right-hand side linear system.

### ISSUE THREAD

**Issue by utah2015** [mfem/mfem#3318]
Hi,
I am working to solve an electromagnetic problem with multiple point sources.  I would like to obtain all solutions with multiple sources by solving the linear system once.  How to  form a multiple right-hand side linear system?  Does the BilinearForm::FormLinearSystem() provide the functionality?
Thanks for your help.

**Comment by sebastiangrimberg** [comment]
Hi @utah2015, this is something that is not currently available in MFEM but there is a PR in progress for adding this functionality (https://github.com/mfem/mfem/pull/3075). There are also some follow-on PRs which upgrade interfaces to some commonly used sparse direct solver packages to take advantage of this (https://github.com/mfem/mfem/pull/3082, https://github.com/mfem/mfem/pull/3081, https://github.com/mfem/mfem/pull/3083).

**Comment by utah2015** [comment]
@sebastiangrimberg ，
I will try it by  following the steps you said.
Thanks for answering my question quickly.
