### ISSUE TITLE
Non-Linear Geometric Analysis Question

### ISSUE THREAD

**Issue by ajos6183** [mfem/mfem#332]
Hi There,

I realize this is not the right place to ask this. But i am finding that it is difficult to get some assistance in this matter and i believe there will be many experts here who can help me.

I tried looking through this code but i don't understand C++ code as i am not a programmer by training.

I am writing a Non-Linear Geometric Analysis package for 3D beams in C# to handle small strains and small or moderate displacements. I have progressed well with it but i still have some issues that i am having a hard time to resolve. This is my pseudo-code:

```
Define Analysis Nodes and Members
Calculate Coordinates and Transformations
For Each Load Steps
	Update Load Vectors and Calculate Starting Residual
	Calculate Structure Tangent Stiffness Matrix
	Perform Full Newton Raphson Method: While ResidualNorm > tolerance
		Solve for displacement of this iteration
		Update Incremental Displacement
		Calculate Axial
		Update Structure Tangent Stiffness Matrix
		Calculate Residual
		Calculate ResidualNorm
	End Newton Raphson Method
	Update Total Displacements
	Calculate Member Displacements
	Update Coordinates and Transformations
	Increment Member Nodal Forces
	Increment Reactions
End Load Step
Calculate Member Forces
```
I am not exactly sure if the coordinates should be updated every iteration or every increment only and whether the Member displacements and forces (using an interpolation) should be done at every iteration, every increment or only once at the end.

I can share my code with anyone willing to help me (because this is for work).

Any help will be greatly appreciated,
Anthony

**Comment by tzanio** [comment]
Hi Anthony,

I will leave this open for a while, but it may be difficult to get help without additional details. Are you trying to solve a problem similar to Example 10? Will it be sufficient for you to understand how that example works?

Cheers,
Tzanio

**Comment by ajos6183** [comment]
Hi Tzanio,

Thanks, i'm implementing a geometrically non-linear static analysis for 3D beams. 
I am using the Euler-Bernoulli theory and then adding a geometric stiffness matrix such as the one on page 257 of this book [http://digitalcommons.bucknell.edu/books/7/](url). This theory does not account for large deformations. However, i am trying to make it account for large deformations by running many load steps and updating the geometry with every increment at the moment. 

My questions were:
1- Whether anyone is familiar with such an approach? and whether it is sound?
2- Whether the geometry should be updated every iteration or every increment?
3- Whether member displacements and forces (using an interpolation) should be done at every iteration, every increment or only once at the end?

Thanks again,
Anthony

**Comment by tzanio** [comment]
Hi Anthony,

If I understand correctly you are trying to use multiple steps of a linear elasticity solver, that's valid for small displacements, to model an elasticity problem with large displacements?

My guess is that you really need a non-linear elasticity formulation for that (as in Example 10), but I'm not an expert on this. Maybe @jamiebramwell or @v-dobrev can help.

Cheers,
Tzanio

**Comment by ajos6183** [comment]
Yes, this is what i was trying to do without using a non-linear formulation! Maybe it's not a good idea!

**Comment by tzanio** [comment]
Hi Anthony, unfortunately it doesn't look like the team can help so I'm closing this issue. Feel free to reopen if you have further questions. Cheers, -Tzanio
