### ISSUE TITLE
Incompatibility with SUNDIALS 3.0.0

### ISSUE THREAD

**Issue by juan42** [mfem/mfem#333]
I tried to compile with the new SUNDIALS release 3.0.0 and recognized an incompatibility.

It should be mentioned somewhere that we are compatible up to version 2.7.0

**Comment by tzanio** [comment]
This is being addressed as we speak in https://github.com/mfem/mfem/pull/295 :)

**Comment by juan42** [comment]
So much stuff going on that i overlook that.
