### ISSUE TITLE
Possible bug in SubMeshUtils::BuildVdofToVdofMap

### ISSUE THREAD

**Issue by mlstowell** [mfem/mfem#3332]
The following block of code would seem to access the `DenseMatrix` `T` incorrectly on line 145. If `parentfes.GetVDim() > 1` this must produce column values larger than the width of `T`.

https://github.com/mfem/mfem/blob/b09cc38df9f1da182a5625c92660737ca02e710a/mesh/submesh/submesh_utils.cpp#L141-L150

**Comment by jandrej** [comment]
Yea, this is the retro-fitted "L2 on boundary extraction" case. We should just remove the `*  T.Width()` right?

**Comment by mlstowell** [comment]
I think it may be more complicated than that. Particularly  if we want to support different vdim ordering types. I've been looking at it and I think I'm getting close to a solution. I'll post more if I find an answer.

**Comment by mlstowell** [comment]
I think I have a solution (the ordering types were not relevant after all). I'll try to put together a PR later today.
