### ISSUE TITLE
Periodic boundary conditions. 

### ISSUE THREAD

**Issue by barreracruz** [mfem/mfem#3338]
I am trying to set periodic boundary conditions but it seems that I am not using them correctly. The mesh I am using was generated in cubit: 
![image](https://user-images.githubusercontent.com/102010127/203472593-0d0944f1-810c-41b4-8b1a-4090e3993599.png)
and I want to apply periodicity along planes parallel to the the XZ and YZ planes at the ends of the domain. I am doing the following:

 ` mfem::Vector x_translation({lx, 0.0, 0.0});`
  `mfem::Vector y_translation({0.0, ly, 0.0});`
  `std::vector<mfem::Vector> translations = {x_translation, y_translation};`
  `double tol = 1e-6;`
  `auto periodic_mesh = mfem::Mesh::MakePeriodic(initial_mesh, initial_mesh.CreatePeriodicVertexMapping(translations, tol));`

but it seems that only the nodes at the top of the domain (along Zmax) get affected:
![image](https://user-images.githubusercontent.com/102010127/203474050-4dbf592f-6492-4fde-a050-fac85e41d04b.png)
Is there an example in 3D other than the one in the `test_periodic_mesh.cpp` file that I could use as a reference to make sure that I am using this capability appropriately?

**Comment by pazner** [comment]
Your usage looks correct to me. Could it be that the vertices on the periodic faces are not exactly `lx` or `ly` translations of each other? It won’t work if the vertices are not within your specified tolerance. You could try looking at the output of `CreatePeriodicVertexMapping` to check that the correct vertices are identified.

**Comment by barreracruz** [comment]
They are not exact. You are correct. But isn't that why I can use the tolerance parameter? what would be a good tolerance in lx and ly are in the order of `0.1-0.2`? I will take a look at the output of `CreatePeriodicVertexMapping`.

**Comment by barreracruz** [comment]
Ok, I looked at the output of `CreatePeriodicVertexMapping` using the simpler setup in the following code:

`auto initial_mesh = buildMeshFromFile("rectangularTruss.g");

  double lx = 0.18;

  mfem::Vector x_translation({lx, 0.0, 0.0});
 
  std::vector<mfem::Vector> translations = {x_translation};

  double tol = 1e-4;

  std::vector<int> periodicMap = initial_mesh.CreatePeriodicVertexMapping(translations, tol);

 for(int i = 0; i < static_cast<int>(periodicMap.size()); i++) 
 {
  if(i!=periodicMap[i])
  {
    std::cout<<"... periodicMap["<<i<<"] = "<<periodicMap[i]<<std::endl;
  }
 }`

and got this output when I ran it in serial:
![image](https://user-images.githubusercontent.com/102010127/204328848-76106824-bbf9-479a-9008-3e8f2fc68686.png)

which is clearly not all the nodes that should be flagged as periodic. The mesh used here is the same one showed above, i.e., an Exodus II format (.g) mesh that was generated in Cubit. I am adding it here as a zip file for your reference: [rectangularTruss.g.zip](https://github.com/mfem/mfem/files/10105609/rectangularTruss.g.zip)

Can you please reproduce the issue or let me know if you see a way to fix this based on the shared code?

Thanks.

**Comment by pazner** [comment]
Yes, the tolerance parameter can be used if the vertices are not exactly collocated. If the differences just come from round-off errors, then the default value is fine.

Another thing to check: `CreatePeriodicVertexMapping` only looks for vertices that belong to boundary elements. Does your mesh have boundary elements defined on all of the periodic surfaces?

**Comment by barreracruz** [comment]
Oh, I see. That should be the problem! I do not generate side sets for those boundaries in Cubit so MFEM does not generate any boundary elements on those boundaries. I will test this later and report back if doing that solves this issue.

**Comment by pazner** [comment]
You can also try calling `Mesh::GenerateBoundaryElements()` to rebuild the boundary elements for all faces, but if you have specific boundary attributes that you care about that might mess them up.

**Comment by barreracruz** [comment]
Yes, that was the issue. Thank you very much for your help!
