### ISSUE TITLE
Opinions on switching from `astyle` to `clang-format`?

### ISSUE THREAD

**Issue by sebastiangrimberg** [mfem/mfem#3339]
PETSc and libCEED moved recently to use `clang-format` for more consistent code styling (see https://github.com/CEED/libCEED/issues/1047, https://github.com/CEED/libCEED/pull/1051), and it seems like with more an more contributing developers MFEM could also benefit from this. Are there any opinions on making a similar switch in MFEM? That is, assuming there is a `.clang-format` style which satisfy everyone close enough to the current Artistic Style guidelines.

**Comment by tzanio** [comment]
Code formatting has been raised multiple times in the past and [the last time](https://github.com/mfem/mfem/pull/2506) we needed to change (from `astyle-2.05.1`) we considered three options: `clang-format`, `astyle-3.1` and `uncrustify`. At the end we chose `astyle-3.1`, but it was not an easy decision.

We can revisit it again if folks feel strongly about it (or things have changed).

For reference, here are some of the requirements for the code formatting tool we considered in the last discussion:

- Easy to install and use on a variety of hardware (e.g. early-access systems with limited software stack)
- Everyone on the team is willing to adopt it (or at least accept the style it enforces)
- Doesn’t change a lot of source code (the style should be close to the current one)
- Supports C++11, macros, lambdas, etc.
- Supports consistent formatting, i.e. the same style for C++ constructs by default
- Allows for semantic formatting, i.e. hand-tuned layout that help users/new developers understand the code

**Comment by tzanio** [comment]
ping: @mfem/developers

**Comment by termi-official** [comment]
I also already wondered why astyle has been chosen over clang-format - what were the arguments against clang-format? No strong opinion here btw, I always take whatever works.

**Comment by jandrej** [comment]
The most breaking argument was `Easy to install`. If you need to build from source, you need to build llvm/clang which can be a little demanding.

I'm still pro clang-format.

**Comment by tzanio** [comment]
There were other concerns -- maintaining `git blame` history, having to update a significant number of branches, and losing "semantic formatting". 

Please correct me if I'm wrong, but if I recall correctly `clang-format` does not take into account the original source code, so any careful arrangements there can't be preserved.

**Comment by termi-official** [comment]
Polluting the history is indeed a good point. If you do not want style rules to be enforce on specific lines, then you can guard these (https://clang.llvm.org/docs/ClangFormatStyleOptions.html#disabling-formatting-on-a-piece-of-code), but I do not think this is a great option. IIRC then clang-format does not allow to skip rules to prevent inconsistent formatting.

**Comment by goxberry** [comment]
> There were other concerns -- maintaining git blame history, having to update a significant number of branches, and losing "semantic formatting".

re: `git blame`,  [`git hyper-blame`](https://commondatastorage.googleapis.com/chrome-infra-docs/flat/depot_tools/docs/html/git-hyper-blame.html), can be configured to ignore certain commits. It can be installed via the Chromium project's ["depot_tools"](https://commondatastorage.googleapis.com/chrome-infra-docs/flat/depot_tools/docs/html/depot_tools_tutorial.html#_setting_up) repo.

re: branches, a risk mitigation would be to phase in formatting individual source files.

re: "semantic formatting", in other contexts (e.g., Python's `black`, `rustfmt`), formatting customization is viewed as an anti-pattern that discourages new contributors and power users -- decreasing project impact -- by forcing them to learn a bespoke style.

**Comment by TobiasDuswald** [comment]
Big fan of `clang-format`. Mainly because it is integrated very well into VS Code, making it very convenient. :)

**Comment by v-dobrev** [comment]
+1 for sticking with AStyle.

**Comment by sebastiangrimberg** [comment]
I realize I also never really offered an explanation to why `clang-format` might be preferred over `astyle`. One case is that it seems like Artistic Style doesn't really seem to enforce a lot of whitespace standards around function calls, operators, reference `&` and pointer `*`, etc. leading to differences in style throughout the codebase. One particular example (no offense intended) might be [`superlu.hpp/cpp`](https://github.com/mfem/mfem/blob/master/linalg/superlu.hpp) which follows a very different whitespace syntax than a lot of the rest of the code with pointers written as `const SuperLURowLocMatrix * APtr_;` and member functions as `void Mult( const Vector & x, Vector & y ) const;`. I realize this might be a nitpicky example but in practice it makes the code less readable and it means that any added contributions can result in large `diffs` according to different whitespace styles which hurts maintainability I feel. Uniform column width limits is another benefit I see of `clang-format`.

While these are just particular examples, I think the additional data points that large libraries like PETSc and deal.II have moved to `clang-format` and discussions in those libraries about pros and cons are also good references.

Regarding the concerns, I echo @goxberry's comments. `git blame` history can be viewed prior to the offending formatting commit to reveal the actual code blame, so this history isn't lost but I agree is less clean to look at. Hand-tuning of formatting for certain examples is relatively straightforward depending how much we want to use `// clang-format off` and `// clang-format on` blocks.

**Comment by pazner** [comment]
> re: `git blame`, [`git hyper-blame`](https://commondatastorage.googleapis.com/chrome-infra-docs/flat/depot_tools/docs/html/git-hyper-blame.html), can be configured to ignore certain commits. It can be installed via the Chromium project's ["depot_tools"](https://commondatastorage.googleapis.com/chrome-infra-docs/flat/depot_tools/docs/html/depot_tools_tutorial.html#_setting_up) repo.

I just learned that as of git 2.23, `git blame` supports `--ignore-rev` and `--ignore-revs-file`. That way it is possible to check in a `.git-blame-ignore-revs` file with a list of formatting commits that should be ignored by `git blame`. This is even [supported](https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view) by GitHub's blame view. It's not a completely perfect solution, but it somewhat mitigates the issue of polluting `git blame`.
