### ISSUE TITLE
SubMesh Transfer method crashing

### ISSUE THREAD

**Issue by JeremiahDBrown** [mfem/mfem#3340]
I'm trying to do some processing in a submesh to reduce overall computation time, since the particular calculations only need to take place in a portion of the grid.  However, I'm getting segfaults when the program completes execution.  This only occurs if I have used the Transfer method, and it doesn't happen at the time I call the method, but only as the various destructors are being called.

Here's a simple demo that works with the attached mesh (generated in Cubit):
```
int main(int argc, char *argv[]) {
  Mpi::Init();
  Mesh locmesh("testmesh.g");
  ParMesh mesh(MPI_COMM_WORLD, locmesh);

  FiniteElementCollection *fec_nd = new ND_FECollection(2, mesh.Dimension());
  ParFiniteElementSpace *fespace_nd = new ParFiniteElementSpace(&mesh, fec_nd);

  Array<int> dom_attrs(1);
  dom_attrs[0] = 2;

  ParSubMesh subm = ParSubMesh::CreateFromDomain(mesh, dom_attrs);
  ParFiniteElementSpace *fespace_nd_sub = new ParFiniteElementSpace(&subm, fec_nd);
  cout << "Mesh elements: " << mesh.GetNE() << " : Submesh elements: " << subm.GetNE() << "\n";

  ParGridFunction _from(fespace_nd_sub);
  _from = 0.0;
  ParGridFunction _to(fespace_nd);
  subm.Transfer(_from, _to);
  cout << "Transfer executed.\n";

  delete fespace_nd;
  delete fespace_nd_sub;
  delete fec_nd;

  return 0;
}
```
[testmesh.zip](https://github.com/mfem/mfem/files/10079794/testmesh.zip)

**Comment by jandrej** [comment]
Only H1 and L2 spaces on SubMeshes are supported in the current release.

**Comment by JeremiahDBrown** [comment]
Well, that's disappointing.  Is support for other spaces in the near-term plan?

On a somewhat related noted, the implementation of the SubMesh constructor is a little challenging to work with.  The static methods used to call the private constructor make it much more difficult to store a SubMesh as a class member for later references.  I got around that limitation using a container class and calling the SubMesh creation method in the container class constructor.  I can see the challenges with the domain vs. boundary SubMesh differences, but surely there is a more flexible way to deal with this (making SubMesh an abstract base class and deriving DomainSubMesh and BoundarySubMesh from it comes to mind, except that it breaks functionality in the current release).

**Comment by mlstowell** [comment]
I have an RT implementation undergoing testing as we speak. I have a vague plan for implementing ND support but this is more of a departure from the current implementation so it requires more thought. However, ND support is something I need rather soon so this is a priority for me.

**Comment by M8kmyday** [comment]
Throwing in some support, I'm having the same issues that JeremiahDBrown is having:
1. Need support for ND.
2. Static definition with no public constructor is very challenging to deal with.  JeremiahDBrown seems to be a better programmer than me, so I'll investigate his solution when ND is available.

I've read through the documentation on SubMesh and lots of the SubMesh source code.  The limitation to H1 and L2 is a big surprise to me.  After several days of trying to get to get the SubMesh infrastructure to work, from this thread, I'll have to drop it for a while.  I think that means my work is dead in the water for now, but I'll see if there is some other way to get the 2D solution on ports applied to a 3D space.  So far, my best result results in some scrambling of the dofs, and I do not have an idea about how to properly insert the solved 2D boundary dofs into the 3D dof vector to then solve the 3D problem.
