### ISSUE TITLE
Multi-Point constraint crossing processors

### ISSUE THREAD

**Issue by CodingDrRui** [mfem/mfem#3341]
Dear developers,

I would like to impose a constraint like " u_{node1} = u_{node2}" in an elasticity example, where node1 is on processor 0 and node2 is on processor 1. Could you please share some information about how to realize it?

I have tried with the normal constraints used in ex28p, however it seems that the constraints can only be imposed on nodes which are on the same sub-mesh (the same processor).
I also tried to read the constraints for hanging nodes in the nonconforming mesh, ex21p. I am not sure if the nonconforming constraints work for the case I am dealing with. I guess a hanging node and its master/slave nodes share a same sub-mesh.

Best regards,
Rui

**Comment by vladotomov** [comment]
Hi @CodingDrRui,

Could you explain a little more - what is the FE space? Are the two nodes on the processor boundary? What is the physical motivation for such a constraint?

**Comment by CodingDrRui** [comment]
> Hi @CodingDrRui,
> 
> Could you explain a little more - what is the FE space? Are the two nodes on the processor boundary? What is the physical motivation for such a constraint?

Ok. Let's take a look at ex2p in the H1 space. If now I have 2 beams (or more), named beam A and beam B, respectively, I want to bound them (because beam A and beam B work together in a realistic problem). Then I will do this by setting constraints like: u_{node_A1} = u_{node_B1}, u_{node_A2} = u_{node_B2}, ....., u_{node_An} = u_{node_Bn}...
In parallel computing, beam A and beam B may be distributed in different processors. Node_An and Node_Bn may be on the boundary, or not. I don't know...

**Comment by CodingDrRui** [comment]
If the constraints used for hanging nodes in the nonconforming mesh can also constraint "tdofs" on different processor, I will try to implement my targeted master/slave dofs into the matrix P (interpolation from true dof to dof) and the (block-diagonal) matrix R (restriction of dof to true dof).

**Comment by vladotomov** [comment]
Why don't you put both beams on one big mesh, with different material properties for the beam regions? Then using H1 will give you the constraints immediately. You also won't have to do anything special for the parallel case.

**Comment by CodingDrRui** [comment]
> 

I am not sure if I have followed you. There is a gap between the beams, which have no shared nodes nor boundaries. Could you please show me more details?

**Comment by vladotomov** [comment]
Sorry I can't comprehend what you're trying to do. How is there a gap, but at the same time the beams are bounded with the same displacement? Some kind of visual sketch of the setup would be helpful.

**Comment by jtristano** [comment]
I'd like to reopen this thread @vladotomov  as I'm interested in the same thing

Here's a picture of what @CodingDrRui  is talking about.   You have a finite element mesh with a remote load that is transferred by many rigid (infinitley stiff spars or 1d elements)

When performing structural analysis this trick is used to simplify modeling.



![image](https://github.com/mfem/mfem/assets/136379293/3552ede7-4549-4fce-b346-18af44fc47ba)

I tried to create sample mesh
```
MFEM mesh v1.0

#
# MFEM Geometry Types (see mesh/geom.hpp):
#
# POINT       = 0
# SEGMENT     = 1
# TRIANGLE    = 2
# SQUARE      = 3
# TETRAHEDRON = 4
# CUBE        = 5
#

dimension
3

elements
11
1 5 0 1 10 9 18 19 28 27
1 5 1 2 11 10 19 20 29 28
1 5 2 3 12 11 20 21 30 29
1 5 3 4 13 12 21 22 31 30
2 5 4 5 14 13 22 23 32 31
2 5 5 6 15 14 23 24 33 32
2 5 6 7 16 15 24 25 34 33
2 5 7 8 17 16 25 26 35 34
3 1 35 36
3 1 36 37
4 0 37

boundary
34
3 3 9 10 1 0
3 3 0 1 19 18
3 3 10 9 27 28
1 3 9 0 18 27
3 3 18 19 28 27
3 3 10 11 2 1
3 3 1 2 20 19
3 3 11 10 28 29
3 3 19 20 29 28
3 3 11 12 3 2
3 3 2 3 21 20
3 3 12 11 29 30
3 3 20 21 30 29
3 3 12 13 4 3
3 3 3 4 22 21
3 3 13 12 30 31
3 3 21 22 31 30
3 3 13 14 5 4
3 3 4 5 23 22
3 3 14 13 31 32
3 3 22 23 32 31
3 3 14 15 6 5
3 3 5 6 24 23
3 3 15 14 32 33
3 3 23 24 33 32
3 3 15 16 7 6
3 3 6 7 25 24
3 3 16 15 33 34
3 3 24 25 34 33
3 3 16 17 8 7
3 3 7 8 26 25
2 3 8 17 35 26
3 3 17 16 34 35
3 3 25 26 35 34


vertices
38
3
0 0 0
1 0 0
2 0 0
3 0 0
4 0 0
5 0 0
6 0 0
7 0 0
8 0 0
0 1 0
1 1 0
2 1 0
3 1 0
4 1 0
5 1 0
6 1 0
7 1 0
8 1 0
0 0 1
1 0 1
2 0 1
3 0 1
4 0 1
5 0 1
6 0 1
7 0 1
8 0 1
0 1 1
1 1 1
2 1 1
3 1 1
4 1 1
5 1 1
6 1 1
7 1 1
8 1 1
-2 0 0
-1 0 0

```
And mesh explorer blew up since the mesh did not contain all solid elements.

How would you do this in MFEM and still allow to use the matrix free operator in the hooke mini app?

**Comment by v-dobrev** [comment]
Currently, MFEM and the Hooke miniapp do not support such meshes -- all `elements` have to be of the same reference dimension and all `boundary` elements have to be one dimension less than the `elements`.

In principle, it should be possible to extend MFEM meshes to support such lower-dimensional spars, however, they will have to be handled explicitly in any miniapp that wants to use them.

**Comment by joetristano** [comment]
Thank you for the response!  This is what I assumed the case was but wanted to be sure that I didnt miss anything.
