### ISSUE TITLE
Does MFEM /Glvis support VTK Data File Version 5.1

### ISSUE THREAD

**Issue by shani9383** [mfem/mfem#3344]
Hi,
Does MFEM /Glvis support VTK Data File Version 5.1? If not how can I solve this issue?
I’m using Simpleware software to generate and export my mesh to a vtk file. However, when trying to upload the file I get the following message:
Verification failed: (major_vtk_version >= 2 && major_vtk_version <= 4) is false:
 --> Unsupported VTK format
 ... in function: void mfem::Mesh::Loader(std::istream&, int, std::string)
 ... in file: mesh/mesh.cpp:4063

**Comment by pazner** [comment]
I don’t think the VTK 5.1 format is well-documented (see: https://gitlab.kitware.com/vtk/vtk/-/issues/17989). If we had a spec, we could implement support for a VTK 5.1 mesh reader. Can you export your mesh in a different format (e.g. XML VTK)?

**Comment by shani9383** [comment]
Unfortunately the only matching format between simple ware and MFEM is vtk
(and the versions are not conforming).
you probably sew this ... but I have to try :) Maybe this can help to
allow MFEM support of vtk version 5.0:
 https://discourse.vtk.org/t/upcoming-changes-to-vtkcellarray/2066

Tnxs
Shani

**Comment by pazner** [comment]
Hello @shani9383,

Could you please share the mesh file here? The changes in the file format from version 4 to 5 might not be relevant for MFEM's mesh reader.

Also, another option would be to add another conversion step, e.g. using something like [meshio](https://pypi.org/project/meshio/).

**Comment by shani9383** [comment]
My mesh is a huge file so I'm
 output_c3_g20_raw.vtk
<https://drive.google.com/file/d/1q6_dPddHfa0dHnow1LOygZBwabxmNPBE/view?usp=drive_web>
 attaching it and also just a small sample from it. Both files were
generated by Simpleware.
I tried using meshio but didn't succeed to convert the file. I'll keep on
playing with it.
Any help will be appreciated
Thanks
Shani

**Comment by pazner** [comment]
I was able to open your mesh in ParaView and then save it as a VTU (XML) format and then read it into MFEM/solve on it. That is probably the easiest solution for now.

![image](https://user-images.githubusercontent.com/11493037/205169555-c0c79818-7d14-4bf7-b82d-227fe0962511.png)

**Comment by shani9383** [comment]
Woooow thank you so much .Amazing !!!!

**Comment by pazner** [comment]
Closing for now. Please re-open if you run into other issues.

**Comment by shani9383** [comment]
Hi Will,
Can you please share with me the format you ran my analysis? It's my first
time not using a commercial FEA software and I'm a bit lost. I'm trying to
understand how to define the material properties and
boundary conditions (now that I have a vtu mesh file)? are they part of the
mesh file? and if so how do I define them?

Thanks
Shani

**Comment by shani9383** [comment]
If it's relevant my goal is to run a linear elastic analysis with
homogeneous material properties where Dirichlet BC (fixture) are defined on
the bottom surface and Neumann BC (traction) are defined on the upper
surface.
Tnx
Shani

**Comment by pazner** [comment]
Hello @shani9383,

The best way to run a linear elasticity analysis on your mesh with MFEM is by modifying [example 2](https://mfem.org/examples/#ex2) (or example 2p, the parallel version).

This example is set up for a two-material cantilever beam, with Dirichlet and Neumann boundary conditions on different parts of the boundary. I suggest you adapt this code to fit your problem specifications.

The main requirement you will need for materials and boundary conditions is to tag the elements and boundary elements with [attributes](https://mfem.org/fem_bc/). These attributes are just integers that by themselves have no particular meaning, but are given an interpretation in your code (e.g. in your code, you define that elements with attribute 1 have particular material properties, whereas elements with attribute 2 have different material properties). Likewise, in your code, you will do something like "enforce Dirichlet conditions on boundary attribute 1" and "enforce Neumann condition on boundary attribute 2". The element attributes and boundary attributes are defined in the mesh file (the element attributes and boundary attributes are numbered separately).

**Comment by shani9383** [comment]
Thank you for the explanation. I still don't understand how I actually tag
the material elements and boundary elements with attributes. My vtk mesh
file is derived by Simpleware ScanIP (commercial software) and then, as you
advised, converted in paraview to a vtu file.
1. Where and how do I extract the boundary elements and provide them
the relevant attributes?
2. Where and how do I extract the material elements and provide them
the relevant attributes?
3. How can I view the data of the mesh written in the vtu file?

Tnx
Shani

**Comment by pazner** [comment]
Hi Shani,

Typically tagging the different elements and boundaries is the job of the mesh generator. I am not familiar with Simpleware, so I don't know if it has this functionality or how to access it. Often one tags the different parts of the geometric/CAD model with attributes, and then the mesh generator will put these tags on the mesh elements and boundary elements.

If you can define the different boundaries or materials analytically (e.g. with a function or mathematical expression) then you can do this in your code in a relatively straightforward way. For example, you mentioned different BCs on the lower and upper surfaces. If these surfaces are defined in terms of a simple plane (i.e. the lower surface corresponds to all points with $z < z_0$, and the upper surface to all points with $z \geq z_0$) then this is easy to do in the code once you load the mesh.
