### ISSUE TITLE
Some questions about coefficients in GeneralizedAlpha2Solver

### ISSUE THREAD

**Issue by shih15** [mfem/mfem#3346]
Hi.
In class `GeneralizedAlpha2Solver`, the coefficients $\beta$ and $\gamma$ is defined as: $\beta = \frac{1}{4}(1.0+\alpha_m - \alpha_f)^2$ and $\gamma =0.5+\alpha_m -\alpha_f$. However, in paper ["A Time Integration Algorithm for Structural Dynamics With Improved Numerical Dissipation: The Generalized-α Method"](https://doi.org/10.1115/1.2900803),  the coefficients $\beta = \frac{1}{4}(1.0-\alpha_m + \alpha_f)^2$ and $\gamma =0.5-\alpha_m +\alpha_f$. 
Why are there differences between code and reference article?

**Comment by IdoAkkerman** [comment]
If I remember correctly the definition of both \alpha_m and \alpha_f in the original paper of Hulbert and Chung is awkward -- it goes in the other direction then usual. 

I choose to use the standard convention: \alpha = 0 corresponds with t=t^n and \alpha =1 corresponds with t=t^n+1.
Consequently the formulas for \beta and \gamma.
