### ISSUE TITLE
BlockMatrix::Mult is not checking the input sizes

### ISSUE THREAD

**Issue by kvoronin** [mfem/mfem#335]
Hello,

I'd like to suggest adding dimension checks to BlockMatrix::Mult function.
I think it is reasonable to have at least the same checks for BlockMatrix::Mult as for SparseMatrix::Mult, i.e.:
```
void BlockMatrix::Mult(const Vector & x, Vector & y) const
{
   if (x.GetData() == y.GetData())
   {
      mfem_error("Error: x and y can't point to the same datas \n");
   }

   MFEM_ASSERT(width == x.Size(),
               "Input vector size (" << x.Size() << ") must match matrix width (" << width
               << ")");
   MFEM_ASSERT(height == y.Size(),
               "Output vector size (" << y.Size() << ") must match matrix height (" << height
               << ")");
   y = 0.;
   AddMult(x, y, 1.0);
}
```
(MFEM_ASSERT added).
As it is now, there will be no complaints if the input matrix for the Mult() will be of sizes which doesn't match those of the BlockMatrix.

Thanks,
Kirill

**Comment by tzanio** [comment]
Sounds good, please propose a pull request.
