### ISSUE TITLE
New field in class Vector

### ISSUE THREAD

**Issue by v-dobrev** [mfem/mfem#3350]
Hmm, this does not look right: https://github.com/mfem/mfem/blob/8591e38a71df36fca747670a5e77df4ed96346c8/linalg/vector.hpp#L66

Why was it added to the class? Just to be used in one very special case?

If the simple `Vector::Randomize` does not do what you want, just use a custom function instead.

cc: @psocratis

**Comment by psocratis** [comment]
Indeed this should have made it to master. Thank you @v-dobrev. Fixed in #3352
