### ISSUE TITLE
Parallel Version of DG Stokes Example

### ISSUE THREAD

**Issue by ryanblack129** [mfem/mfem#3354]
Hello,

I am working on a parallel version of the DG Stokes Example (PR #3215). I was following the changes going from ex5 to ex5p and I'm running into an issue where the code gives the correct answer when run on 1 processor but not on multiple processors. See plots below (velocity on left, pressure on right)

1 processor case
![image](https://user-images.githubusercontent.com/56736259/205978213-0f52e4bc-db27-4d4f-bb63-376f2eb7f1cd.png)
![image](https://user-images.githubusercontent.com/56736259/205982518-0ac4b511-d0af-46ed-87a7-77216b2d53f1.png)

4 processor case
![image](https://user-images.githubusercontent.com/56736259/205978720-f812650e-ff4d-41be-bba6-4a6eabcd380e.png)
![image](https://user-images.githubusercontent.com/56736259/205982348-844ab704-48bc-4519-b94c-05fa6e49d876.png)

I am very new to parallel programming, and so I suspect I am not using the library correctly to setup the parallel version of the code. I’ve attached my code and mesh file, any help implementing the parallel version would be greatly appreciated.

Best,
Ryan Black

[parallel_stokes_ex.zip](https://github.com/mfem/mfem/files/10168839/parallel_stokes_ex.zip)

**Comment by atallah727** [comment]
Hello @ryanblack129, I typically use the L2_FECollection for running a DG calculation. Can you try that? Also make you are initializing your variables to zero.

**Comment by atallah727** [comment]
Ok, I see. Thank you for that. Are you running with quads or triangles? Do you see any difference between the two? Also, can you try with 2 processors instead of 4?

**Comment by atallah727** [comment]
One additional thing to try, instead of using the BlockOrthoWrapper, can you try adding a traction condition at one of the boundaries and try again.

**Comment by ryanblack129** [comment]
Thanks for the help and quick reply.

I went back through and made sure to initialize all variables to zero. I am running on quads, but will try triangles and report back.

On 2 processors, the solution is better
![image](https://user-images.githubusercontent.com/56736259/206009837-25075ea7-ab07-467d-9eac-739fdd40ab41.png)
![image](https://user-images.githubusercontent.com/56736259/206009948-d1e57b28-0cc3-4d36-b6a2-2a0083397be3.png)

On 3 processors, similar error as 4
![image](https://user-images.githubusercontent.com/56736259/206010517-d0fb918b-c45f-42f9-a303-066e4dc58450.png)
![image](https://user-images.githubusercontent.com/56736259/206010720-9699e40c-50d4-4c39-90d9-04db2c1f651c.png)

I also ran the case with a traction bc on one boundary, unfortunately I see the same behavior.

**Comment by atallah727** [comment]
Ok, I see. Try running without a preconditioner and also you can also switch some terms in the weak form. For example, you try with just keeping the penalty terms across internal boundaries and the outer boundary. Just to see if a bug resides on any one of those terms.

**Comment by ryanblack129** [comment]
4 processors without preconditioner
![image](https://user-images.githubusercontent.com/56736259/206017391-12599047-7887-498a-a6b4-158d88579f6e.png)
![image](https://user-images.githubusercontent.com/56736259/206017436-c97a67bf-4985-406c-b797-80f21dfe636b.png)

Looks like there is a small change in error comparing with the 4 processor case above.




Also, for a triangular mesh, 1 processor. I don't get the correct pressure with pure dirichlet bcs
![image](https://user-images.githubusercontent.com/56736259/206016833-b09c4e61-4ff2-4203-9244-71e45232e442.png)
![image](https://user-images.githubusercontent.com/56736259/206019230-623172cd-f82f-4490-a47a-5af988803a28.png)

However, when I set one boundary to a traction bc, I get the correct answer on 1 processor, triangular mesh
![image](https://user-images.githubusercontent.com/56736259/206019996-454e0fb2-726c-4dcc-8f3b-665a6a688b55.png)
![image](https://user-images.githubusercontent.com/56736259/206020063-4955a778-2c18-4bf0-85b4-602c9ced5017.png)

But then on multiple processors for the triangular mesh, same issue as above.

I will also try switching some terms in the weak form

**Comment by atallah727** [comment]
Can you also try with a zero rhs and see if you get a zero output for both pressure and velocity.

**Comment by ryanblack129** [comment]
Yes, I do get a zero output for both pressure and velocity for 1 processor and multiple processors

**Comment by atallah727** [comment]
Ok, let me know what happens when you switch off some terms at a time.

**Comment by ryanblack129** [comment]
My apologies, I just noticed that I was using a version of MFEM that did not include updates to `ParMixedBilinearForm` to handle `interior_face_integs` (see above PR). After switching to that version, I am able to get the parallel version working on multiple processors for quad meshes.
4 processor case
![image](https://user-images.githubusercontent.com/56736259/206031909-af2a1ded-e3f4-4a1a-8717-7ef22a06e43f.png)
![image](https://user-images.githubusercontent.com/56736259/206031961-da24dc6c-b62e-4c5c-884f-ffcca2007afb.png)

I really appreciate the help debugging, thanks so much.

Just one last thing I want to try to resolve before closing the issue. I still do not get the correct pressure solution on triangle meshes with pure dirichlet bcs.

**Comment by atallah727** [comment]
Excellent. Most welcome. So, you mean pure Dirichlet with zero averaging?

**Comment by ryanblack129** [comment]
Yes that case. Thinking the same thing, taking a look

**Comment by atallah727** [comment]
If you don't use it even for pure Dirichlet bc, do you get right result?

**Comment by nma20** [comment]
So, if you don't use the OrthoSolver for getting a zero pressure average, the output is still incorrect?

**Comment by atallah727** [comment]
So, if you don't use the OrthoSolver for getting a zero pressure average, the output is still incorrect?

**Comment by atallah727** [comment]
That is the case for serial, correct?

**Comment by ryanblack129** [comment]
Gotcha, sorry let me outline what I'm seeing

Triangle Mesh:
-pure dirichlet bcs and zero mean pressure
Pressure approximation is incorrect in serial and parallel

-mix of dirichlet bc on velocity and traction bc
Pressure approximation is correct in serial and parallel

**Comment by atallah727** [comment]
Can you try without the preconditioner again?

**Comment by ryanblack129** [comment]
Thanks again for the help. I think since the original issue with the parallel implementation has been resolved this thread should be closed and a new issue should be opened to further look into the dependence of the results on the mesh used.

I will open a new issue shortly, with some initial debugging results.

Thanks,
Ryan
