### ISSUE TITLE
Swapping vector components

### ISSUE THREAD

**Issue by astrobl85** [mfem/mfem#3356]
I have a 2D vector field in a ParGridfunction in an HCurl space given by lets say **w** = _(u,v)_ where _u_ and _v_ vary as a function of position in a 2D plane. If I want to construct the vector **w'** = _(v,u)_ by swapping the components and possibly multiplying each component by a scalar, how would I go about doing so?

1) Method 1 - Brute Force Iteration
```
int npt = WGrid->Size()/2;
for (int index = 0; index < npt; ++index)
   {
      if (Ordering::byNODES == WGrid->FESpace()->GetOrdering())
      {
         ix = index + 0*npt;
         iy = index + 1*npt;

         std::cout << WGrid->Elem(ix) << " " << WGrid->Elem(iy) << std::endl;

         std::swap(WGrid->Elem(ix),WGrid->Elem(iy));

         std::cout << WGrid->Elem(ix) << " " << WGrid->Elem(iy) << std::endl;
      }
}
```
The swapping of values happens, but the output field is incorrect. If I do not do this swap inside the loop above, then swap the output field when post-processing in python later on, it's correct. I believe this tells me that I am indexing into the arrays incorrectly with _ix_ and _iy_. What is the underlying storage ordering here? Is it different for a GridFunction versus ParGridFunction? The method above is 
 analogous to how it is done serially inside the function FindPointsGSLIB::InterpolateGeneral(...) ?

2) Method 2 - Matrix Multiply
```
DenseMatrix Swapper(2,2);
 Swapper.Elem(0,0) = 0.0;
 Swapper.Elem(0,1) = 1.0;
 Swapper.Elem(1,0) = 1.0;
 Swapper.Elem(1,1) = 0.0;
```
How would I apply the matrix multiplication **Swapper** * **w** for each location on the 2D plane?

Thank you

**Comment by vladotomov** [comment]
Hi @astrobl85,

In MFEM the DOFs of HCurl `GridFunctions` do not represent single `x/y/z` components. Instead the basis functions are vectors. So `WGrid->Size()/2` would be half of the function, not the size of one component.

You can get a split of the `x/y` components with `GridFunction::ProjectVectorFieldOn()` and then do one of the above approaches.

**Comment by mlstowell** [comment]
Hi, @astrobl85,

Just to add to what @vladotomov said. The thing to remember about Nedelec fields is that they are not entirely continuous. Only their tangential components are continuous across element interfaces. What continuity do you require in your result vector with swapped components? 

In general such a swap could lead to a completely discontinuous vector field which would best be described using a vector L2 finite element space. There is also a special case in 2D if you want `w'=(-v,u)`. This field has a continuous normal component at element interfaces (there's a simple trick to produce this swapping using an HDiv space).

If you require different continuity than what was discussed above you will need to setup and solve a simple linear system to find the field which most closely matches the correct swapped components.

Best wishes,
Mark

**Comment by vladotomov** [comment]
Also note that `ParGridFunction::ProjectVectorFieldOn` is not implemented, so you'd get the serial version in every partition, and MPI boundaries won't be treated as the global serial call would.

**Comment by astrobl85** [comment]
I appreciate the responses. @mlstowell w'=(-v,u) is exacly what I need. What is your simple trick to do this swapping in HDiv space? :)

**Comment by astrobl85** [comment]
Hey @mlstowell just checking in on my question above about the simple trick for vector component swap in HDiv space. Thank you!!

**Comment by mlstowell** [comment]
Hi, @astrobl85,

Sorry for the delayed reply. I was offline for a couple weeks. In 2D the HDiv basis functions are related to the HCurl basis functions by $\vec{F}\_i = \hat{z}\times\vec{W}\_i$. So, the trick is to simply copy the data from the HCurl `GridFunction` into an HDiv `GridFunction` as if they were standard vectors. If you want to avoid performing the copy or using the extra memory you can even share a single data vector between the two `GridFunction` objects. There are two ways (at least) to do this which differ in based on what info you have available when the HDiv `GridFunction` is created. The following code snippet shows both options:
```
ND_FECollection fec_nd(order, dim);
RT_FECollection fec_rt(order - 1, dim);

ParFiniteElementSpace fes_nd(&pmesh, &fec_nd);
ParFiniteElementSpace fes_rt(&pmesh, &fec_nd);

ParGridFunction gf_nd(&fes_nd);
gf_nd.ProjectCoefficient(VCoef);

// Define an HDiv field sharing the data with an HCurl field
ParGridFunction gf1_rt(&fes_rt, gf_nd, 0);

// Define an empty HDiv field without a FiniteElementSpace to avoid allocation
ParGridFunction gf2_rt;
gf2_rt.MakeRef(&fes_rt, gf_nd, 0);
```

Best wishes,
Mark
