### ISSUE TITLE
Issue with custom DG FaceIntegrator

### ISSUE THREAD

**Issue by ryanblack129** [mfem/mfem#3360]
Continuing the discussion from issue #3354 related to the dependence of the results on the mesh used. The results below are for the case with pure Dirichlet boundary conditions and a zero mean condition on pressure. I am seeing the following behavior

On a mesh of uniform quad elements, correct answer
![image](https://user-images.githubusercontent.com/56736259/207142264-a759c4d3-a111-41fc-8bfa-8512b125391f.png)
![image](https://user-images.githubusercontent.com/56736259/207142293-65e78777-a4d4-44e5-b21e-fb5d315a0917.png)

Triangular elements, wrong answer 
![image](https://user-images.githubusercontent.com/56736259/207142510-7fef988c-d2dd-4bbc-9eab-0547996e428d.png)
![image](https://user-images.githubusercontent.com/56736259/207142561-f4b77f02-b1bd-4dc1-ad37-aaf731696faf.png)

Distorted quad elements, wrong answer 
![image](https://user-images.githubusercontent.com/56736259/207143009-21210a2a-7e9b-4d0c-ba65-69d95b14d186.png)
![image](https://user-images.githubusercontent.com/56736259/207143137-92637f74-69aa-41b9-8b47-d4ab92034076.png)

Distorted quad elements on interior only, correct answer
![image](https://user-images.githubusercontent.com/56736259/207143844-1fe14a73-7aaf-4782-901c-ec7bf9b5f857.png)
![image](https://user-images.githubusercontent.com/56736259/207143884-81aee8cf-9fb1-4514-8b5d-568dbfa3b713.png)

Same mesh as previous, except distort two quads on the boundary, wrong answer 
![image](https://user-images.githubusercontent.com/56736259/207144080-8f5e0400-23ed-4eaa-8112-69f38632680c.png)
![image](https://user-images.githubusercontent.com/56736259/207144122-065f4d00-40c2-494b-9138-0cc3c85f9f67.png)

I was able to isolate the issue to my implementation of the term (I will post the code below in separate post)
$\sum_e \int_e \set{ p }[\underline{v}] \cdot \underline{n}_e \ d\Gamma $
which is used on both interior and boundary edges.

For debugging, I ran the same sequence of meshes for ex18 and observed the same behavior of getting the right answer only with the uniform quad mesh and the mesh with distorted elements on the interior only.

Is there something special being done in ex18? I had used this as a reference to write my custom term.

Thanks for the help,
Ryan

**Comment by ryanblack129** [comment]
Code for $\sum_e \int_e \set{ p }[\underline{v}] \cdot \underline{n}_e \ d\Gamma $

```
void DGAvgNormalJumpIntegrator::AssembleFaceMatrix(const FiniteElement &tr_fe1,
                                                   const FiniteElement &tr_fe2,
                                                   const FiniteElement &te_fe1,
                                                   const FiniteElement &te_fe2,
                                                   FaceElementTransformations &T,
                                                   DenseMatrix &elmat)
{
   // test space here is the velocity (vector space), trial space is pressure (scalar space)
   int dim = tr_fe1.GetDim();
   int tr_ndof1, te_ndof1, tr_ndof2, te_ndof2, tr_ndofs, te_ndofs;
   tr_ndof1 = tr_fe1.GetDof();
   te_ndof1 = te_fe1.GetDof();

   if (T.Elem2No >= 0)
   {
      tr_ndof2 = tr_fe2.GetDof();
      te_ndof2 = te_fe2.GetDof();
   }
   else
   {
      tr_ndof2 = 0;
      te_ndof2 = 0;
   }

   tr_ndofs = tr_ndof1 + tr_ndof2;
   te_ndofs = te_ndof1 + te_ndof2;
   elmat.SetSize(te_ndofs*vdim, tr_ndofs);
   elmat = 0.0;

   Vector nor(dim);
   Vector tr_s1(tr_ndof1);
   Vector tr_s2(tr_ndof2);
   Vector te_s1(te_ndof1);
   Vector te_s2(te_ndof2);
   tr_s1 = 0.0;
   tr_s2 = 0.0;
   te_s1 = 0.0;
   te_s2 = 0.0;
   nor = 0.0;

   const IntegrationRule *ir = IntRule;
   if (ir == NULL)
   {
      int order;
      if (tr_ndof2)
      {
         order = 2*(max(tr_fe1.GetOrder(), tr_fe2.GetOrder()) + max(te_fe1.GetOrder(),
                                                                    te_fe2.GetOrder())) + 2;
      }
      else
      {
         order = 2*(tr_fe1.GetOrder() + te_fe1.GetOrder()) + 2;
      }
      ir = &IntRules.Get(T.GetGeometryType(), order);
   }

   // elmat = [ A11   A12 ]
   //         [ A21   A22 ]
   // where the blocks corresponds to the terms in the face integral < {p},[v]*nor > from
   // the different elements and trial/test space, i.e.
   // A11 : terms from element 1 test and element 1 trial space
   // A21 : terms from element 2 test and element 1 trial space
   DenseMatrix A11(te_ndof1*vdim, tr_ndof1);
   DenseMatrix A12(te_ndof1*vdim, tr_ndof2);
   DenseMatrix A21(te_ndof2*vdim, tr_ndof1);
   DenseMatrix A22(te_ndof2*vdim, tr_ndof2);
   A11 = 0.0;
   A12 = 0.0;
   A21 = 0.0;
   A22 = 0.0;
   double w;
   for (int n=0; n<ir->GetNPoints(); n++)
   {
      const IntegrationPoint &ip = ir->IntPoint(n);
      T.SetAllIntPoints(&ip);
      const IntegrationPoint &eip1 = T.GetElement1IntPoint();
      const IntegrationPoint &eip2 = T.GetElement2IntPoint();

      // normal
      if (dim == 1)
      {
         nor(0) = 2*eip1.x - 1.0;
      }
      else
      {
         CalcOrtho(T.Jacobian(), nor);
      }
      // note nor = nor*detJ

      // below if statement needed so on the boundary {p} = p (definition of {} operator)
      if (T.Elem2No >= 0)
      {
         w = ip.weight;
      }
      else
      {
         w = ip.weight*2;
      }
      nor *= w;

      // calc shape functions in element 1 at current integration point
      tr_fe1.CalcShape(eip1, tr_s1);
      te_fe1.CalcShape(eip1, te_s1);

      // form A11
      for (int d = 0; d<vdim; d++)
      {
         for (int i = 0; i < te_ndof1; i++)
         {
            for (int j = 0; j < tr_ndof1; j++)
            {
               A11(i + te_ndof1*d,j) += 0.5*tr_s1(j)*(te_s1(i)*nor(d));
            }
         }
      }

      // if element 2 exists form the rest of the blocks
      if (tr_ndof2)
      {
         // calc shape functions in element 2 at current integration point
         tr_fe2.CalcShape(eip2, tr_s2);
         te_fe2.CalcShape(eip2, te_s2);

         // form A12
         for (int d = 0; d<vdim; d++)
         {
            for (int i = 0; i < te_ndof1; i++)
            {
               for (int j = 0; j < tr_ndof2; j++)
               {
                  A12(i + te_ndof1*d,j) += 0.5*tr_s2(j)*(te_s1(i)*nor(d));
               }
            }
         }

         // form A21
         for (int d = 0; d<vdim; d++)
         {
            for (int i = 0; i < te_ndof2; i++)
            {
               for (int j = 0; j < tr_ndof1; j++)
               {
                  A21(i + te_ndof2*d,j) += -1.0*0.5*tr_s1(j)*(te_s2(i)*nor(d));
               }
            }
         }

         // form A22
         for (int d = 0; d<vdim; d++)
         {
            for (int i = 0; i < te_ndof2; i++)
            {
               for (int j = 0; j < tr_ndof2; j++)
               {
                  A22(i + te_ndof2*d,j) += -1.0*0.5*tr_s2(j)*(te_s2(i)*nor(d));
               }
            }
         }
      }
   }

   // populate elmat with the blocks computed above
   elmat.AddMatrix(A11,0,0);
   if (tr_ndof2)
   {
      elmat.AddMatrix(A12, 0, tr_ndof1);
      elmat.AddMatrix(A21, vdim*te_ndof1, 0);
      elmat.AddMatrix(A22, vdim*te_ndof1, tr_ndof1);
   }
} 
```

**Comment by atallah727** [comment]
Hello @ryanblack129, do you observe the same behavior in serial and parallel? Would it be possible for you to write two implementations of this term, one for boundaries and the other for interior faces? If they work separately then you can debug this term that can handle both cases.

**Comment by v-dobrev** [comment]
Hi Ryan,

One reason this may be happening is the following: the error estimate for the pressure includes (semi-)norms other than the semi-norms $| u |\_{k+1}$ and $| p |\_k$ when using $P_k^d$ for $u_h$ and $P_{k-1}$ for $p_h$. This often is the case for mixed formulations, and that basically says that there is no guarantee that one will exactly recover the pressure $p$ even if it is in the space $P_{k-1}$ and $u$ is in $P_k^d$. Do you know what the error estimate for this discretization method is?

The results you posted above seem to indicate that the velocity is exactly recovered in all cases even if the pressure is not, so I suspect that the error estimate for that is of the form $C h^k | u |\_{k+1}$ for the $H^1$ norm of the velocity error and possibly $C h^{k+1} |u|\_{k+1}$ for the $L_2$ norm of the same error.

**Comment by ryanblack129** [comment]
Hi @v-dobrev 

Unless I am misunderstanding something, it appears from what is given in Riviere's book on pg 128-129 that the error estimates depend only on semi-norms of u and p for this method.

But for the above, I thought I was running a test case where the solution was in the finite element space. I am not sure why there is a loss of accuracy on distorted meshes. 

Also, the above tests were all run on mfem v4.4. When I updated to mfem v4.5, on the triangle mesh the velocity and pressure errors are now O(10^-13) and O(10^-12) respectively, while on the distorted quad mesh the velocity and pressure errors are now O(10^-7) and O(10^-5) respectively. (L2 norm of error)

**Comment by ryanblack129** [comment]
Thank you very much. Ah yes now I understand you can’t reproduce exactly in physical space. 

Is there some minimal polynomial order that has to be reproduced exactly on all meshes for convergence of the method? Here I’m thinking like in solid mechanics, where I learned that you need to be able to reproduce exactly linear and constant polynomials for convergence of the method.

**Comment by v-dobrev** [comment]
Actually, I was wrong about the $P_2$ velocity not being in the discrete space -- I just did not see it right away. (If you consider general curvilinear $Q_2$ quad meshes then the claim is true.)

In order verify that it is always possible to reproduce a $P_2$ velocity on general $Q_1$ quad mesh with $Q_2$ solution space, one needs to verify that the composition of $Q_1: \hat{x}\to x$ and $P_2: x \to \mathbb{R}$ is in the solution space, $Q_2: \hat{x} \to \mathbb{R}$. This is fairly easy to check.

So, there is something else going on in the case of general $Q_1$ quad meshes.

One thing that comes to mind is that, in this case, the gradient term $(\nabla u, \nabla v)$ is not evaluated exactly with quadrature because, when mapped to the reference element, it is not a polynomial expression -- it is a polynomial divided by $det(J)$ which for $Q_1$ transformations is, generally, linear. This maybe part of the explanation but I'm not sure.

**Comment by v-dobrev** [comment]
It looks like if I set the quadrature rules to be the same for the following DG face integrators
```
VectorDGDiffusionIntegrator [interior and boundary]
VectorDGDirichletLFIntegrator
```
then the solution in `ex34` is exactly recovered on general $Q_1$ quad meshes.

This seems to be the case regardless of the fact that the integrals in the r.h.s. of the equality
$$- \int_T \Delta u \\, v = \int_T \nabla u \cdot \nabla v - \int_{\partial T} (\nabla u \cdot n_T) \\, v$$
are not computed exactly with quadrature. Without that, I'm not sure why we're actually able to recover the exact solution.

**Comment by ryanblack129** [comment]
Thank you so much for looking into this

Ryan
