### ISSUE TITLE
Link errors when using caliper configured with adiak and/or gotcha

### ISSUE THREAD

**Issue by kennyweiss** [mfem/mfem#3361]
My mfem configuration uses `caliper` (`MFEM_USE_CALIPER=YES`) where caliper is configured with [`adiak`](https://github.com/LLNL/Adiak) and [`gotcha`](https://github.com/LLNL/gotcha).

Since mfem is not adding `adiak` and `gotcha` on the link line, I get "undefined reference" link errors, e.g.:
```
libcaliper.a(AdiakExport.cpp.o): In function `(anonymous namespace)::export_globals_to_adiak(cali::Caliper*, cali::Channel*)':
AdiakExport.cpp:(.text+0x2b7): undefined reference to `adiak_numerical_from_type'
AdiakExport.cpp:(.text+0x2e0): undefined reference to `adiak_get_basetype'
...
libcaliper.a(wrappers.c.o): In function `curious_apply_wrappers':
wrappers.c:(.text+0x1f): undefined reference to `gotcha_wrap'
libcaliper.a(wrappers.c.o): In function `wrapped_read':
wrappers.c:(.text+0x97): undefined reference to `gotcha_get_wrappee'
...
```

I was able to get past this (in the make-based build system) by adding a few lines for the adiak and gotcha configuration, e.g.
```
ADIAK_DIR = @MFEM_DIR@/../adiak
ADIAK_OPT = -I$(ADIAK_DIR)/include
ADIAK_LIB = $(XLINKER)-rpath,$(ADIAK_DIR)/lib -L$(ADIAK_DIR)/lib -ladiak

GOTCHA_DIR = @MFEM_DIR@/../gotcha
GOTCHA_OPT = -I$(GOTCHA_DIR)/include
GOTCHA_LIB = $(XLINKER)-rpath,$(GOTCHA_DIR)/lib -L$(GOTCHA_DIR)/lib -lgotcha
```

Would it be ok to add `MFEM_USE_ADIAK` and `MFEM_USE_GOTCHA` as additional optional TPLs to mfem?

**Comment by v-dobrev** [comment]
If I understand correctly, these are indirect dependencies through Caliper, right?

We typically do not add such as MFEM_USE_* options -- these are only used for direct dependencies.

That said, we do have some dependencies of dependencies options in `defaults.mk`, so adding the snippet with `ADIAK_DIR` and `GOTCHA_DIR` is fine. By default, however, it is best to add these to `CALIPER_OPT`/`CALIPER_LIB` only when `ADIAK_DIR`/`GOTCHA_DIR` are set by the user -- by default they should be empty. This is how `CAMP_DIR` and `CUB_DIR` are used with RAJA.

Ideally, we would have `defaults.mk` read the needed values for `CALIPER_OPT`/`CALIPER_LIB` from a file exported by Caliper as part of its installation -- e.g. from a pkg-config file or something like that.

In the CMake build system we can probably import the exported CMake config files from Caliper -- I assume Caliper does export at least CMake config files.

**Comment by kennyweiss** [comment]
Thanks for the pointers @v-dobrev -- I'll check out the `camp` and `cub` setup.

It looks like `caliper` has a `pkg-config` file, but, it does not include information about `adiak` and `gotcha`.
```
>cat caliper-a2f911a/lib/pkgconfig/caliper.pc 

Name: caliper
Description: Caliper is a generic context annotation system.
Version: 2.9.0-dev
prefix=<root>/caliper-a2f911a
includedir=<root>/caliper-a2f911a/include
libdir=<root>/caliper-a2f911a/lib
Libs: -L${libdir} -lcaliper
Cflags: -I${includedir}
```

It doesn't look like `adiak` or `caliper` (currently) have pkg-config files. 

Tag @daboehme

**Comment by v-dobrev** [comment]
An alternative, that does not require changes to MFEM, is to specify all the needed options when configuring MFEM by setting the `CALIPER_OPT` and `CALIPER_LIB` variables on the config command line:
```console
make config \
   CALIPER_OPT=<caliper+dependencies-compile-flags> \
   CALIPER_LIB=<caliper+dependencies-link-flags> \
   ...
```
In that sense, the addition of `ADIAK_*` and `GOTCHA_*` variables will be just a convenience tool to facilitate the definition of `CALIPER_OPT` and `CALIPER_LIB` in `defaults.mk`. As I mentioned earlier, we already have this type of convenience variables for other packages, so adding these Caliper-related variables is absolutely fine.

**Comment by kennyweiss** [comment]
Thanks for the help @v-dobrev! 
PR https://github.com/mfem/mfem/pull/3369 is my proposed solution for the two build systems.

**Comment by tzanio** [comment]
Thanks @kennyweiss !
