### ISSUE TITLE
Building with algoim

### ISSUE THREAD

**Issue by ryanblack129** [mfem/mfem#3365]
I am trying to build mfem with the algoim library. I am using gcc-9.4.0, ubuntu 20.04, and the cmake build system.

Everything seems to build ok and the package ALGOIM is found

![image](https://user-images.githubusercontent.com/56736259/207421140-8c8b849e-bad3-4846-b3b0-885fe7a94f4c.png)

But when I run the example `lsf_integral.cpp` in the shifted miniapp, the code outputs only the MFEM volume calculation
![image](https://user-images.githubusercontent.com/56736259/207421946-da7174ad-4735-4f74-8bda-497bff1df4b0.png)

Looking at the example, I think the option `MFEM_USE_BLITZ` hasn't been set
https://github.com/mfem/mfem/blob/e6ba86462c0db85732c1ac33ce7615d79b555bfd/miniapps/shifted/lsf_integral.cpp#L183-L247

Where should I set this option? I did not see it in the defaults.cmake

**Comment by bslazarov** [comment]
The ALGOIM package requires BLITZ. If you open the defaults.cmake in the config directory you will find the following line:

set(ALGOIM_REQUIRED_PACKAGES "BLITZ" CACHE STRING
    "Packages that ALGOIM depends on.")

I am usually using user.cmake in the config directory and there I set the following lines:

set(BLITZ_DIR "/PATH/blitz" CACHE PATH "Path to Blitz")
set(BLITZ_INCLUDE_DIRS  "/PATH/blitz/include" CACHE PATH "Path to Blitz headers.")
set(BLITZ_LIBRARIES "/PATH/blitz/lib/libblitz.a" CACHE PATH "Path to Blitz library.")

You can try to set them in the command line if you prefer to work without configuration file.

**Comment by ryanblack129** [comment]
Thanks for the quick reply.

Yes, I saw that in the defaults.cmake file and have built blitz-1.0.2. I set the options like above in my user.cmake file:

```
set(BLITZ_DIR "${MFEM_DIR}/../blitz" CACHE PATH "Path to Blitz")
set(BLITZ_INCLUDE_DIRS "${MFEM_DIR}/../blitz/include" CACHE PATH "Path to Blitz headers.")
set(BLITZ_LIBRARIES "${MFEM_DIR}/../blitz/lib/libblitz.a" CACHE PATH "Path to Blitz library.")
```
Unfortunately I am still running into the same issue.

**Comment by ryanblack129** [comment]
Yes, just double checked it is installed there. Thanks for taking a look into this.

**Comment by v-dobrev** [comment]
`ALGOIM_REQUIRED_PACKAGES` should be spelled as `Algoim_REQUIRED_PACKAGES` and the contents should be `"Blitz"`, not `"BLITZ"`. This is because of the naming of the files `FindAlgoim.cmake` and `FindBlitz.cmake` and the way they call `mfem_find_package` -- the first argument is `Algoim`/`Blitz` (this should be consistent with the filename, `Find*.cmake`). The second argument (`ALGOIM`/`BLITZ`, respectively) determines the names of the output variables: like `ALGOIM_FOUND`, `ALGOIM_INCLUDE_DIRS`, `ALGOIM_LIBRARIES`, etc.

These requirements are documented here: https://github.com/mfem/mfem/blob/e6ba86462c0db85732c1ac33ce7615d79b555bfd/config/cmake/modules/MfemCmakeUtilities.cmake#L231-L248

**Comment by ryanblack129** [comment]
Thanks for letting me know. I made those changes to my user.cmake:

```
set(BLITZ_DIR "${MFEM_DIR}/../blitz" CACHE PATH "Path to Blitz")
set(ALGOIM_DIR "${MFEM_DIR}/../algoim/src" CACHE PATH "Path to Algoim")
set(Algoim_REQUIRED_PACKAGES "Blitz" CACHE STRING
    "Packages that ALGOIM depends on.")
```
And now it is able to find blitz
![image](https://user-images.githubusercontent.com/56736259/207654630-fded36bb-2496-479b-8140-f6a2801d2b5b.png)

But it still only outputs the volume calculation from MFEM

**Comment by ryanblack129** [comment]
If I remove the lines

`#if defined(MFEM_USE_ALGOIM) && defined(MFEM_USE_BLITZ)`

from lsf_integral.cpp and integ_algoim.*pp, the example now outputs the volume calculation using both MFEM and Algoim

![image](https://user-images.githubusercontent.com/56736259/207658137-8e2ee090-fa9a-49fe-9ea4-554d207292c6.png)

**Comment by bslazarov** [comment]
I will prepare a PR for fixing it. Thank you! 

You should remove only the "&& defined(MFEM_USE_BLITZ)" part.

**Comment by ryanblack129** [comment]
Sounds good, and no problem! Thanks again

**Comment by tzanio** [comment]
Thanks @bslazarov !
