### ISSUE TITLE
Error and confusion in CalcPhysHessian  

### ISSUE THREAD

**Issue by chunyu79** [mfem/mfem#3367]
Dear MFEM developers,
  Thank you for opening the great piece of code. We are using MFEM to develop a strain gradient model which uses the Hessian and the Laplaican of each component of the strain tensor. Both the documentation and the previous issue  [https://github.com/mfem/mfem/issues/296](https://github.com/mfem/mfem/issues/296) explain that the components of the Hessian matrix are stored in the order {u_xx, u_xy, u_xz, u_yy, u_yz, u_zz}. However, it seems CalcPhyLaplacian get the Laplacian by collecting the components u_xx(0), u_yz(4) and u_zz(5) [Definition at line [202](https://docs.mfem.org/html/fe__base_8cpp_source.html#l00202) of file [fe_base.cpp](https://docs.mfem.org/html/fe__base_8cpp_source.html)] , rather than u_xx(0), u_yy(3) and u_zz(5). 
    I am not sure whether the ordering of the components in the Hessian matrix changes or not.
   
  One more quesion: I use a simple code to test  CalcPhysHessian and CalcPhyLaplacian. The code passes the compilation but fails on execution if triangle element, tethedron element or Hex element are used.But interestingly, the quarilateral element works. The errors read "
  MFEM abort: method is not overloaded
 ... in function: virtual void mfem::FiniteElement::CalcHessian(const mfem::IntegrationPoint&, mfem::DenseMatrix&) const
 ... in file: /home/chunyu/CorrectFEM/mfem-git/mfem/fem/fe/fe_base.cpp:103"
   It seems the virtual functions are not properly bound for the H1_HexahedronElement, H1_TetrahedronElement 
 and the H1_TriangleElement (very unlikely but ...). The finite element spaces are defined as, 
   FiniteElementCollection *fecU,*fecUd,*fecL;
   FiniteElementSpace *fespaceU,*fespaceUd,*fespaceL;   
   fecU = new H1_FECollection(order, dim);  
   fecUd = new H1_FECollection(order, dim); 
   fecL = new H1_FECollection(order, dim); 
   fespaceU = new FiniteElementSpace(mesh, fecU, dim); 
   fespaceUd = new FiniteElementSpace(mesh, fecUd, dim==3?6:3); 
   fespaceL= new FiniteElementSpace(mesh, fecL, dim==3?6:3);    
   The elements should belong to the class of H1_**Element but only the H1_QuadrilateralElement work.
  Thank you for your help.

**Comment by chunyu79** [comment]
For the second question, we have found the error is caused by calling Trans.Hessian(). The element type is properly bound to H1_***element and thus el.CalcHessian() is OK. However, in el.CalcPhysHessian() ,Trans.Hessian() is called which calls fe.CalcHessian . However, the fe is bound to the fixed-order-elements (say, Linear2DElement(triangleelement), Linear3DElment(Tet), Bilinear2DElement(quad) or Trilinear3DElement(Hex)) and only the Bilinear2DElement(quad) is equipped with the CalcHessian() method. The problem can be solved by providing CalcHessian() for these elements. 
The first question still remains to be clarified. The ordering of the components of the Hessian seems to be different for Nurbs elements and H1_***Elements.

**Comment by chunyu79** [comment]
We have supplemented the needed functions in the fixed order elements and slightlly modified the CalcPhysHessian and the CalcPhysLaplacian. The new version works in our application but we are not completely sure whether the modifications are correct or not. The files are attached for your review.
[Modifications.zip](https://github.com/mfem/mfem/files/10253628/Modifications.zip)

**Comment by mlstowell** [comment]
Hi, @chunyu79, 
Thanks for bringing this to our attention. I agree that there seems to be an inconsistency in the ordering of the Hessian. In particular the H1 and NURBS Hessians are ordered differently and the Laplacian seems to follow the NURBS ordering. However, the H1 ordering agrees with the symmetric matrix ordering used in symmetric matrix coefficients, for example. 

I'm not very familiar with the NURBS implementation so I'll ask @IdoAkkerman.  Ido, do you happen to know the reason for the ordering used for the Hessian in the `NURBS3DFiniteElement`? Would it be acceptable to change the NURBS implementation to conform with the ordering {u_xx, u_xy, u_xz, u_yy, u_yz, u_zz} ?

Best wishes,
Mark

**Comment by mlstowell** [comment]
Also, @chunyu79,
I've looked briefly at the suggested modifications. The additions to the fixed order finite elements look good to me. We should wait to hear back from @IdoAkkerman regarding the ordering before deciding exactly what to do about that inconsistency.

We have added your GitHub handle to our list of contributors so you can create a branch and related pull request if you like. This would give you a chance to interact with our reviewers and settle on a good solution to this issue. However, if you don't want to create a pull request for whatever reason I would be happy to create one using your modifications as a   starting point. Whatever you prefer is fine with me just let me know.

Best wishes,
Mark

**Comment by chunyu79** [comment]
@mlstowell Thank you, Mark. We are happy we can contribute to MFEM.  I plan to make a tutorial on solving higher order PDEs (>=3) by using MFEM with the Augmented Lagrangian Method(ALM).

**Comment by mlstowell** [comment]
That sounds interesting. Please be sure to share a link to it when you're ready.

**Comment by IdoAkkerman** [comment]
I remember that I was not happy with the ordering myself. I beleive the reason was probably that in the current ordering allows the easy extraction of the Laplacian.
Perhaps the "best" solution is to just go for the full tensor. This circumvents any disambuiguity, particularly when going to 4D (or higher??) for instance. Or is the performance hit  deemed to much?
