### ISSUE TITLE
mfem overwrites global flags in its cmake build

### ISSUE THREAD

**Issue by samuelpmishLLNL** [mfem/mfem#3376]
If I have a CMake project that uses mfem, and I include it in the build by doing

```cmake
# my own project's CMakeLists.txt
cmake_minimum_required(VERSION 3.16)
project(my_project LANGUAGES CXX CUDA)

...

message("CMAKE_CUDA_FLAGS before mfem: ${CMAKE_CUDA_FLAGS}")
add_subdirectory(mfem)
message("CMAKE_CUDA_FLAGS after mfem: ${CMAKE_CUDA_FLAGS}")
```
and configure with something like

```
$ cmake . -DMFEM_USE_CUDA=YES -DCMAKE_CUDA_FLAGS=--ptxas-options=-v
[cmake] CMAKE_CUDA_FLAGS before mfem: --ptxas-options=-v
...
[cmake] CMAKE_CUDA_FLAGS after mfem: --expt-extended-lambda
```

mfem clobbers the global flags I'm trying to apply to the rest of my project.

-----

This throws a wrench in the works of any CMake project that uses mfem like this. Presently, mfem is forcing projects that use it to prophylactically cache global variables (which other ones is mfem overwriting?) before adding mfem to the build, and restore them afterward. 

It also appears that mfem does not document this practice of clobbering global CMake variables, so the user not only has to implement the unpleasant workaround, but also actively debug the build to find out where the problem is coming from (which is not obvious, because this is an unconventional thing for a library to do).

This really hurts the experience of using mfem, and adds unnecessary complexity. Conventional CMake best practices[^1] strongly discourage this behavior (for many reasons, like the ones listed above):

> Where possible, prefer to use the target_…() commands to describe relationships between
targets and to modify compiler and linker behavior.

> Prefer to avoid modifying the various CMAKE_…_FLAGS variables and their configuration specific
counterparts. Consider these to be reserved for the developer who may wish to change them
locally at will. If changes need to be applied on a whole-of-project basis, consider using a few
strategic directory property commands at the top level of the project instead, but consider
whether such settings really should be unilaterally applied.

Please consider updating the CMake build of mfem to prefer using local variables to build its targets, and stop mutating global variables.

[^1]: https://crascit.com/professional-cmake/

**Comment by jwang125** [comment]
Hi Sam, I agree target would be better. And we plan to move to that. But I can't seem to reproduce the problem you gave. Did you do something other than `add_subdirectory` ? From my test with mfem/hiop and this page https://levelup.gitconnected.com/cmake-variable-scope-f062833581b7, it seems CMAKE_CUDA_FLAGS in the parent project shouldn't be affected. According to this post, https://stackoverflow.com/questions/6891447/cmake-variable-scope-add-subdirectory, it's a problem only if 
`PARENT_SCOPE` is enforced. Thanks.

**Comment by jwang125** [comment]
Also, if you don't mind, please try to see if the branch cmake-global-flag-fix resolves this issue. Thanks.

**Comment by samuelpmishLLNL** [comment]
> But I can't seem to reproduce the problem you gave. Did you do something other than add_subdirectory?

Here's a minimal reproducer (unzip and configure with `cmake . -Bbuild -DCMAKE_CXX_FLAGS=-O3`): 
[parent_project.zip](https://github.com/mfem/mfem/files/10437576/parent_project.zip)

```
parent_project % cmake . -Bbuild -DCMAKE_CXX_FLAGS=-O3
...
FOO before: FOO
CMAKE_CXX_FLAGS before: -O3
FOO after: FOO
CMAKE_CXX_FLAGS after: BAR
```

The problem shows up (tested on `cmake` 3.22 and 3.23) when creating the cache entry from the command line `-DCMAKE_CUDA_FLAGS=...`. I don't know why that makes a difference, perhaps it places the variable at an even higher scope than the parent project, so `PARENT_SCOPE` doesn't apply? Regardless of the technical reason, specifying cache entries from the command line is a common practice, so it should be supported.

> please try to see if the branch cmake-global-flag-fix resolves this issue.

That branch does resolve this particular issue, although a quick grep of mfem's CMakeLists.txt files shows a few other places where mfem overwrites `CMAKE_CXX_FLAGS`, which likely results in a similar problem.

**Comment by jwang125** [comment]
Thank you. I will take a look at the command line input. Yes, currently only changed CMAKE_CUDA_FLAGS in CMakeList.txt in the cmake-global-flag-fix . Will do the remaining flags soon.

**Comment by samuelpmishLLNL** [comment]
the CUDA flags do not appear to be overwritten by mfem when using the `cmake-global-flag-fix` branch

**Comment by jwang125** [comment]
Thanks Sam. We will do a PR then.

**Comment by tzanio** [comment]
Discussion continued in #3462
