### ISSUE TITLE
Inquire on FindPoints() for a Discontinuous Galerkin FES

### ISSUE THREAD

**Issue by AlejandroMunozManterola** [mfem/mfem#3383]
Good day,

I am currently implementing some tests for a project with the aim to understand how to locate some relevant DoF ID or position value in a GridFunction initialised with a DG FES by giving the Physical Coordinates as an input.

The setup for the test is quite simple, with the following form:

```
	   0      1      2      3      4
	|-----||-----||-----||-----||-----|
	0     12     34     56     78     9 

```

Where the mesh is a 1D simple mesh with 5 elements and a length of 5.0, in such a way the internal faces would land on 1.0, 2.0... 

There's no trouble when it comes to using the FindPoints method the following way:

```
	/* Node positions for...     1    2        7       8 */
	DenseMatrix pointMat({ {1.0}, {1.00001}, {4.0}, {4.00001} });
	pointMat.Transpose();
	mesh_.FindPoints(pointMat, elArray_, ipArray_);
```

This code returns an element Array with the correct element ID on where these physical coordinates 'land at', {0,1,3,4}.

It is already noticeable I had to add certain decimal values to the DoF which reside on the right side of the interface, if I'd used 1.0 instead of 1.00001, the returned element Array would've been {0,0,3,3}, which is not what I am looking for.

If I retrieve the position of the nodes thorugh the use of the GetNodes method such as:

```
	GridFunction positions(fes_.get());
	mesh_.GetNodes(positions);
```

The returned vector has the following positions (for simplicity I am cutting some of the decimal, but do consider all of them are zeroes) {0.0000, 1.0000, 1.0000, 2.0000, 2.0000, .....}

As you can see, the GetNodes method correctly identifies the DoF positions as 1.0 sharp, but if I were to input that in the FindPoints function, I'd get the incorrect element ID output.

Is this due to the nature of the DG FES I'm using?

I figure out it's because on the event of finding several DoF residing on the same physical position, the FindPoints() method can only return one of them so it chooses the one with the smallest index. Is there a way around it which would still allow me to use an input such as {1.0, 1.0, 4.0, 4.0} for the DenseMatrix and would still return the correct {0,1,3,4} element ID Array?

Thank you very much.

**Comment by vladotomov** [comment]
Hi @AlejandroMunozManterola,

It seems you are expecting the code to return different answers for the same input (you search `x=1.0` two times and want to get element `0` the first time, and then element `1`). What do you want to happen when the physical location is on the element boundary?

**Comment by AlejandroMunozManterola** [comment]
Good morning @vladotomov,

The issue I mention is most probably due to the discontinuous nature of the Finite Element Space. For Discontinuous Galerkin methods, on the boundaries between the elements, instead of sharing the same node, each element has their own node which is shares its physical location with the other. Thus, having two nodes on the very same physical position.

Considering the FindPoints() method only allows me to use the physical location as an argument, if nodes 1 and 2 are on the same physical location, lets say 1.0, and this physical location is a boundary, then the FindPoints() method will only find node 1 and ignore node 2, while node 2 would still be a valid return.

I'd like to know if there's another way to make it so when using the FindPoints() method on a DG element boundary, if multiple nodes reside in that physical locaiton, all of the nodes and the elements they belong to are returned, instead of the one with the lowest index.

**Comment by vladotomov** [comment]
@AlejandroMunozManterola we don't have an interface that returns more than one element per point. In principle all functionality is there, see the code comments in `Mesh::FindPoints()`, and it can be implemented. For example, after finding the point in one element, one can keep searching the neighbors for more matching elements where `InverseElementTransformation::Transform()` returns that the point is inside. Probably the easiest way to try it would be to create an additional version of `FindPoints` in the `Mesh` class.

**Comment by AlejandroMunozManterola** [comment]
@vladotomov I kindly appreciate your answer.

I will look into thinking what's the best way to proceed here if that's the case, maybe thinking about implementing a FindPoints() that could work for Discontinuous Galerkin element spaces too.

Have a good day!
