### ISSUE TITLE
Convection integrator for DG velocity field

### ISSUE THREAD

**Issue by tkarna** [mfem/mfem#3391]
I'm implementing 2D shallow water equations on MFEM. In the momentum equation the advection term is

```
du/dt + (u . grad) u + ... = 0
```

where `u` is a 2D DG vector field.

Is there an existing integrator that can be used for this term?

The NS miniapp uses `VectorConvectionNLFIntegrator` for continuous H1 elements. I'd need a DG version with upwind flux at the interior facets. For the time being I do not need boundary conditions.

**Comment by vladotomov** [comment]
For explicit time integration, you should check example 9. The forms there are for scalar fields - you can extend it to vector fields, or solve for one component at a time.

**Comment by vladotomov** [comment]
> For the generic case, should I implement a `NonlinearFormIntegrator`?

Yes.

**Comment by tkarna** [comment]
OK, I have the DG advection term sorted out. Now if velocity is in Raviart-Thomas HDiv space instead, I need to make another nonlinear integrator? I.e. there's no existing integrator that would fit the bill? In that case, I could modify `VectorConvectionNLFIntegrator` to make it work with HDiv elements?

**Comment by v-dobrev** [comment]
Gradients of H(div) spaces are not supported currently. There is a PR under review for this: #2599, however, it needs some more work to be completed before merging.

**Comment by tkarna** [comment]
OK, I see. Thanks for the info. I'm closing this issue as the original DG question has been addressed.
