### ISSUE TITLE
ParBilinearForm::Update question

### ISSUE THREAD

**Issue by tangqi** [mfem/mfem#3406]
Do we need to update `Xaux` and `Yaux` in the `ParBilinearForm::Update`?

Somehow my code has the following in the `ParBilinearForm::Update`
```
   if (Xaux.ParFESpace() != NULL)
   {
       Xaux.Update();
       Yaux.Update();
   }
```
Maybe that is not necessary any more? I thought we always need to update the ParGridFunction after fespace is updated.

**Comment by v-dobrev** [comment]
Looking at the current code in `master`, the update of `Xaux`, `Yaux`, and `Ytmp` happens here: https://github.com/mfem/mfem/blob/f00eb000ed2142a6d0242656fbf6581825bbfde4/fem/pbilinearform.cpp#L350-L355

However, this `if` check is not handling correctly the case where the FE space was modified in-place, i.e. the `pfes` pointer did not change but the underlying FE space changed (e.g. its mesh was refined). To handle this case we should modify the `if` statement to be
```c++
   if (Xaux.ParFESpace() != pfes || Xaux.GetSequence() < pfes->GetSequence())
```
where we need to define the new method `GridFunction::GetSequence` to return the `GridFunction::fes_sequence` field.

**Comment by v-dobrev** [comment]
I ended up fixing the issue in a slightly different way in #3417.

@tangqi, can test #3417 with your code (removing your modification in `ParBilinearForm::Update`) if it's not too much trouble?

Thanks!

**Comment by tangqi** [comment]
Thanks a lot. It works well with my code.
