### ISSUE TITLE
Add "boundary" face integrator for an internal face.

### ISSUE THREAD

**Issue by lmdiazangulo** [mfem/mfem#3408]
Hi everyone,

I am working with a DG collection and would like to assign a boundary condition to an internal face with certain attribute markers. I have considered the following options:

1. Using AddInteriorFaceIntegrator to do this, but there is no way to pass an array of attributes to identify the faces in which I would like to apply it.
2. I have tried with AddBdrFaceIntegrator, which allows passing attributes.  To do this, I have "manually" created an internal boundary using AddBdrPoint in the mesh. The problem is that during assemble when it locates the boundary with the attribute, the GetBdrFaceTransformation returns NULL because it is an internal face. Therefore, it does not add anything to the operator during assembling.

I am considering two possible solutions:

1.  Create a new method for assembly which assembles interior boundaries. It would be a mix between AddInteriorFaceIntegrator and AddBdrFaceIntegrator.
2. Possibly use submeshes?

Does anyone know if there is an easier way to do this? 

Thanks a lot for your time and work. 

Best regards,
  Luis

**Comment by vladotomov** [comment]
@lmdiazangulo if you're implementing the integrator yourself, you can just do the attribute check inside the integrator.

**Comment by lmdiazangulo** [comment]
We have attempted the modified assembling approach (https://github.com/OpenSEMBA/dgtd/blob/30add2d4f58b0e07a47a383e3c9380fbef0cb118/src/maxwell/mfemExtension/BilinearForm.cpp#L208-L263). 
And it seems to work for a simple test case: https://github.com/OpenSEMBA/dgtd/blob/30add2d4f58b0e07a47a383e3c9380fbef0cb118/test/maxwell/BilinearFormTest.cpp

However, we were wondering if there was a more "standard" way of doing this inside MFEM. This problem would be common for any internal boundary condition. In the context of electrodynamics they show up very often: PEC, PMC, Surface Impedances, etc.

**Comment by v-dobrev** [comment]
Discussion continued in #3422.
