### ISSUE TITLE
Extracting Dof_TrueDof for a sequence of meshes

### ISSUE THREAD

**Issue by kvoronin** [mfem/mfem#341]
Hello everyone,

Suppose I want to extract several Dof_TrueDof matrices from a single ParFiniteElementSpace whose ParMesh is refined several times. How should I do that?
For example,
```
    FiniteElementCollection * hdivfree_coll = new ND_FECollection(feorder + 1, nDimensions);
    ParFiniteElementSpace * C_space = new ParFiniteElementSpace(pmesh.get(), hdivfree_coll);

    pmesh->UniformRefinement();

    C_space->Update();

    HypreParMatrix * mat1 = C_space->Dof_TrueDof_Matrix();

    pmesh->UniformRefinement();

    C_space->Update();

    HypreParMatrix * mat2 = C_space->Dof_TrueDof_Matrix();
```
leaves corrupted mat1 after C_space passes the second C_space->Update(). As far as I understand, the reason is the ownership of the dof_truedof data which belongs to the C_space and gets destroyed during the second update.
How exactly should I resolve this? I couldn't figure out the right way to use  C_space->Lose_Dof_TrueDof_Matrix().

Thanks,
Kirill

**Comment by mlstowell** [comment]
Hi, Kirill,

I have not tried this but I think the correct way to use Lose_Dof_TrueDof_Matrix() is to call it immediately after both of your calls to Dof_TrueDof_Matrix().

I imagine you already tried this and it failed.  Is this correct?

Best wishes,
Mark

**Comment by kvoronin** [comment]
@mlstowell,

I have a failing assertion in the proposed scenario, during the first Lose_Dof_TrueDof_Matrix() because the ownerships flags are wrong
```
Assertion failed: (diagOwner == -1 && offdOwner == -1 && colMapOwner == -1) is false: 
 ... in function: hypre_ParCSRMatrix* mfem::HypreParMatrix::StealData()
 ... at line 781 of file: linalg/hypre.cpp
```
and calling SetOwnerFlags() before or after didn't help either.

**Comment by stefanozampini** [comment]
You can use

`PetscParMatrix * mat1 = new PetscParMatrix(C_space->Dof_TrueDof_Matrix(),Operator::PETSC_MATAIJ);`

this will create a new matrix in PETSc's AIJ format (copying the values). Alternatively, you can also specify `Operator::PETSC_MATHYPRE` if you then wish to access the underlying PETSc Mat Object and use its HyprePARCSR structure, i.e. something like

` hypre_ParCSRMatrix *pcsr; `
`MatHYPREGetParCSR(*mat1,&pcsr); `

**Comment by kvoronin** [comment]
@stefanozampini, 
Thanks for suggesting a work-around!
I rebuilt MFEM with PETSc and tried to use your suggestion but got undefined reference to 'MatHYPREGetParCSR'. Have you done something additional to make the compiler find the definition of it? 
What I tried, is just plugging the three lines 
```
PetscParMatrix * mat;
hypre_ParCSRMatrix *pcsr;
MatHYPREGetParCSR(*mat1,&pcsr);
```
into examples/petsc/ex1p.cpp inside MFEM and tried to run make ex1p in that directory. Somehow the definition was not found be the compiler.

**Comment by stefanozampini** [comment]
MatHYPREGetParCSR is a PETSc call that is available only if PETSc has been compiled with support for HYPRE by specifying -- download-hypre or --with-hypre-dir at configure time. Run ./configure —help to see how to configure PETSc.
Also, MatHYPREGetParCSR access the ParCSR of a Mat object of type MATHYPRE, not MATAIJ.
If you don’t need to access the ParCSR, then simply create a PetscParMatrix with Operator::PETSC_MATAIJ.

**Comment by kvoronin** [comment]
@stefanozampini, 
Thanks again. Now I managed to get it all compiling! Could you also clarify the following? As MFEM's documentation is saying, PETSC_MATAIJ and PETSC_MATIS are only supported. But if I do PETSC_MATAIJ, I get a null as a result of MatHYPREGetParCSR(). 
And if I do  PETSC_MATHYPRE instead, then _mat1_ is somehow interfering with the rest of the routines, e.g.
```
// and nothing else is ever happening to mat1 after this line
PetscParMatrix * mat1 = new PetscParMatrix(C_space->Dof_TrueDof_Matrix(),Operator::PETSC_MATHYPRE);

HypreParMatrix * Dof_TrueDof = C_space->Dof_TrueDof_Matrix();
```
leads to a failure in some complicated way (LeftDiagMult and PartMult involved, called for Dof_TrueDof) but without that line which defines mat1, the code works fine.

Thanks,
Kirill

**Comment by v-dobrev** [comment]
Hi Kirill,

I'll try to answer you original question: you should create copies of the ParMesh as you refine it and keep the coarse-level copies; also, build your coarse ParFiniteElementSpaces based on the copied ParMesh objects and preserve the coarse-level spaces too. On the finest level you do not need to copy the ParMesh that you've been refining.

Hope this helps,
Veselin

**Comment by stefanozampini** [comment]
You cannot get NULL when calling MatHYPREGetPARCSR on a AIJ matrix. PETSc should error in that case.
Regarding your second question: The call with PETSC_MATHYPRE just uses the hypre_PARCSR data inside a PETSc Mat. So, since object ownership is not very well managed under HYPRE (and I would sadly say that this is true also in MFEM :-( ) everything can happen. You have two options: either use PETSC_MATAIJ in the constructor, or do like Vesely is proposing.
