### ISSUE TITLE
Cmake generate error when link mfem in another project on windows

### ISSUE THREAD

**Issue by ruihuasun** [mfem/mfem#3413]
A basic folder struct is
_project
--main.cpp
--CMakeLists.txt
--mfem(folder)
--hypre(folder, contains include and compiled lib)_

And in cmake
```
PROJECT(solvertest)
add_executable(${PROJECT_NAME} main.cpp)
target_include_directories(${PROJECT_NAME} PUBLIC ${PROJECT_SOURCE_DIR})
add_subdirectory(mfem)
target_link_libraries(${PROJECT_NAME} mfem)
```

Then run cmake and choose MFEM_USE_MPI on, then choose hypre include and lib.

**Configure** is ok, but **Generate** error:
```
CMake Error in mfem/CMakeLists.txt:
  Target "mfem" INTERFACE_INCLUDE_DIRECTORIES property contains path:

    "C:/project/hypre/include"

  which is prefixed in the source directory.
```
It seems like a cmakelist problem. I found some references [url](https://stackoverflow.com/questions/25676277/cmake-target-include-directories-prints-an-error-when-i-try-to-add-the-source),[url](https://stackoverflow.com/questions/62348945/cmake-error-target-foo-interface-sources-property-contains-path-which-is-prefi)

**Comment by ruihuasun** [comment]
I have found the solution based on [https://stackoverflow.com/questions/44425257/how-to-properly-use-target-include-directories-with-lists-of-includes](url). I tried to start a pr but seems that I don't have access.

**Comment by v-dobrev** [comment]
Hi @ruihuasun, I just added you the the Collaborators team, so now you should be able to create branches in the MFEM repo. Let us know if you encounter any issues.

**Comment by v-dobrev** [comment]
A solution for this was explored in PR #3418 -- for more details see the discussion there.
