### ISSUE TITLE
Cmake flag MFEM_ENABLE_EXAMPLES not work on windows

### ISSUE THREAD

**Issue by ruihuasun** [mfem/mfem#3414]
I noticed that MFEM_ENABLE_EXAMPLES default is off, and I did not change anything.

The folder struct is same as #3413 

However ex0-ex33p still exsited in the VS solution explorer.

**Comment by v-dobrev** [comment]
Yes, the build targets for the examples are always defined. `MFEM_ENABLE_EXAMPLES` simply controls if these build targets are part of the default build target.

**Comment by v-dobrev** [comment]
See also the discussion #3182 and feel free to add comments or suggestions there.

I'll close this -- further discussion can continue in #3182.
