### ISSUE TITLE
Two domains coupling

### ISSUE THREAD

**Issue by miaodi** [mfem/mfem#3415]
I would like to use mfem to validate some cohesive zone models. The cohesive zone method is a simple technique to simulate debonding. The structure I would like to generate is shown below:

<img width="718" alt="Screenshot 2023-01-11 225200" src="https://user-images.githubusercontent.com/9312314/211999066-d78cbd23-e0c6-4571-9d4c-b2fdd8e26cc4.png">

The top layer and bottom layer are both H1 space. The intersection between two layers is discontinuous and a face integrator should be used to apply the coupling constraint. 

I could not find a way to generate such mesh. My work around is to use L2 space for the entire mesh. The downside of such work-around is that the cohesive zone model is applied to all interior faces.

Does anyone know how to create such mesh in mfem?

Regards,
Di

**Comment by atallah727** [comment]
Hello @miaodi, you can still do a L2 space for the entire mesh and concurrently create an attribute that checks whether an interior edge fractured or not in the face integrator assembly. If the attribute indicates that the edge fractured, you would activate the cohesive zone model integrals, otherwise you would enforce the standard jump and average terms similar to any DG algorithm.

**Comment by miaodi** [comment]
Thank you for your reply. Seems it is the only feasible way now. Could you provide me with some examples on how to add attributes to interior faces? 

Another question is will mfem support multiple mesh coupling in the future?

Thank you!

**Comment by atallah727** [comment]
I don't think there examples on that, but you can check the Get/SetBdrAttribute in the mesh.hpp file and do something similar for the interior faces. Be careful to call pmesh->ExchangeFaceNbrNodes()to make the marking is communicated to the processors that share edges. In regards to you second question, this is something we are considering, but so far there are no initiatives in that direction.
