### ISSUE TITLE
Deformable 2D mesh in 3D and compilation as a shared library

### ISSUE THREAD

**Issue by medvedeg** [mfem/mfem#342]
Dear all,

We want to couple MFEM with our Discrete Element code in order to model flexible walls. I am just wondering, if it is possible to model deformation of a surface defined as 2D mesh in 3D?
In this case, a force be applied not only at the surface border, but also inside. Examples 2 and 10 provide something similar, but in case of 2D mesh, its motion remains 2D.
And the second question, by default "make serial" compiles MFEM librariy as static. If I want to compile as shared library, I can add -fPic to MFEM_CXXFLAGS and compile all object files in a shared library. Maybe there is a quicker solution for compiling for this, some flag or option in make file?

Thanks!
Sincerely,
Alexander Podlozhnyuk,
DCS Computing GmbH

**Comment by AntoineMazuyer** [comment]
Hello @medvedeg 
I use mfem as a shared library, using a CMake option.
I am used to build mfem in a "build" directory:
```

mkdir build
cd build
cmake .. -DBUILD_SHARED_LIBS=1
make
```
Then you got a shared library !

**Comment by tzanio** [comment]
Hi Alexander,

As @AntoineMazuyer said, you can use CMake to build shared version of the library. Alternatively, you can do it manually through the makefiles (e.g. compiling with `-fPIC` and linking with `-fPIC -shared`).

Regarding your first question: I'm not an elasticity expert, but I think what you are trying to do requires shell element formulations which we currently don't have an example of in the library. Maybe @jamiebramwell or one of our users can provide additional help regarding this...

Cheers,
Tzanio

**Comment by v-dobrev** [comment]
I'll look into adding a makefile target that builds a shared library instead of (or in addition to) static - it should be relatively easy.

Just to add to @tzanio's answer: MFEM already supports 2D meshes embedded in 3D but only some differential operators work in that case, e.g. Laplace-Beltrami - this is the integrator [`DiffusionIntegrator`](https://github.com/mfem/mfem/blob/bc6b48421ac6506db6fea2f9d6222f145427f8c8/fem/bilininteg.hpp#L1579)  when used on a surface mesh, as in [example 7](https://github.com/mfem/mfem/blob/master/examples/ex7.cpp) and its parallel version, [example 7p](https://github.com/mfem/mfem/blob/master/examples/ex7p.cpp).

**Comment by v-dobrev** [comment]
Pull request #357 adds support for building a shared version of the library with GNU make.

**Comment by jamiebramwell** [comment]
To expand on @v-dobrev's answer, yes it is possible to model deformable plates and beams. However, a new integrator is needed. A combination of manifold integration techniques (look at the implementation of [`DiffusionIntegrator`](https://github.com/mfem/mfem/blob/f3fbd9765dad23651687a55c6e6a07687b443a0c/fem/bilininteg.cpp#L364) and the variable [`square`](https://github.com/mfem/mfem/blob/f3fbd9765dad23651687a55c6e6a07687b443a0c/fem/bilininteg.cpp#L371) as an example) and either linear ([`ElasticityIntegrator`](https://github.com/mfem/mfem/blob/f3fbd9765dad23651687a55c6e6a07687b443a0c/fem/bilininteg.hpp#L2014)) or nonlinear ([`HyperelasticNLFIntegrator`](https://github.com/mfem/mfem/blob/f3fbd9765dad23651687a55c6e6a07687b443a0c/fem/nonlininteg.hpp#L181)) elasticity would be a good start. [Example 18](https://github.com/mfem/mfem/blob/master/examples/ex18.cpp) shows how to implement a user-defined integrator. 

An important note is that standard structural elements such as [Kirchoff-Love plates](https://en.wikipedia.org/wiki/Kirchhoff%E2%80%93Love_plate_theory) and [Euler-Bernoulli beams](https://en.wikipedia.org/wiki/Euler%E2%80%93Bernoulli_beam_theory) require C1 elements, which we currently do not support (@tzanio and @v-dobrev, please correct me if I am wrong). However, H1-based structural elements such as [Mindlin-Reissner plates](https://en.wikipedia.org/wiki/Mindlin%E2%80%93Reissner_plate_theory) and [Timoshenko beams](https://en.wikipedia.org/wiki/Timoshenko_beam_theory) are possible.

**Comment by tzanio** [comment]
I'm closing this issue now. Feel free to reopen if you have further questions.

**Comment by yw5aj** [comment]
@jamiebramwell Thank you for the pointer! 

In case anyone find this in the future - even for C0 elements I think we can potentially do MITC elements or higher order displacement-based elements that defines the shear deformation as a separate DOF, and those are practically extremely useful already. The most commonly used shell elements in both ABAQUS (S4) and ADINA (MITC4) are exactly derivatives of the elements above.
