### ISSUE TITLE
mpirun noticed that process rank 10 with PID 0 on node yosibash-pc exited on signal 9 (Killed).

### ISSUE THREAD

**Issue by shani9383** [mfem/mfem#3424]
Hi,

I’m trying to run example2p:  `mpirun -np 16 ex2p -m ../data/TEST17JAN.mesh` on a mesh file i generated (from an Ansys output file).
I receive an error message (see below). A google search on "mpirun signal 9" leads me to guess that I’m running out of memory. Is this correct or do I have a problem with the mesh file I generated? How can I solve the problem?  
My computer specifications are:
Processor: AMD Ryzen 9 5950X 16-Core Processor               3.40 GHz
Installed RAM 128 GB
System type 64-bit operating system, x64-based processor

Thanks Shani

Error message:

```console
Options used:
   --mesh ../data/TEST17JAN.mesh
   --order 1
   --amg-for-systems
   --no-static-condensation
   --visualization
   --by-vdim
   --device cpu
Device configuration: cpu
Memory configuration: host-std
Number of finite element unknowns: 125389080
Assembling: r.h.s. ... matrix ... --------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 10 with PID 0 on node yosibash-pc exited on signal 9 (Killed).
```

**Comment by tzanio** [comment]
You very likely are indeed running out of memory.

Part of it is that is the global matrix. Assuming uniform hex mesh, you have about 27 non zeroes per row, which already is about 25GB. For a more unstructured mesh, where you can have ~100 nonzeros per row this could be significantly more.

Another part is the BoomerAMG preconditioner, which likely uses twice the matrix memory (potentially more). You can replace that with diagonal scaling, which will save memory but increase (significantly) the time to solution.

The best thing to do, if you can is parallelize and use more machines with about 1M elements / machine. This should scale with BoomerAMG allowing you to solve larger problems in similar amount of time.

Hope this helps,
Tzanio
