### ISSUE TITLE
Extra factor of face weight in penalty term of `DGDiffusionIntegrator`?

### ISSUE THREAD

**Issue by smsolivier** [mfem/mfem#3432]
Hi, 
I noticed that my linear solvers were struggling for an interior penalty discretization of diffusion on a mesh with high anisotropy/poor aspect ratios. I saw better performance by modifying the calculation for the characteristic mesh length in the penalty term of `DGDiffusionIntegrator`.  

Currently, the variables `nor` and `ni` both implicitly include a scaling of the normal vector by the face element transformation's weight due to the way `CalcOrtho` computes the normal such that `|n| = sqrt(det(J^T J))`. The variable `wq = nor * ni` is then scaled by `det(J^T J)` when I believe it should be proportional to the face's weight: `sqrt(det(J^T J))`. My fix was to scale the variable `wq` by `1/sqrt(nor*nor)` before it is used to compute the penalty term. This led to better solver performance and did not change the accuracy of the IP discretization. I believe this fix is in line with the comment in `DGDiffusionIntegrator` saying it is desirable to have the penalty term scale by the ratio of the face element transformation's weight to the volumetric element transformation's weight. It's hard to tell though given how optimized the code for `DGDiffusionIntegrator` is. 

Please let me know what you think! I can make a PR if you agree that there is a bug. 
Thanks, 
Sam

**Comment by pazner** [comment]
Hi Sam,

I think the code is OK the way it is.

The penalty term is of the form $\int_e h^{-1} [u] [v] ds$.

Let's simplify, and consider just $\int_e h^{-1} ds$ (for example, if we're on the boundary, and the basis functions are piecewise constants). The mesh size $h$ in this expression should be the perpendicular element size, i.e. the ratio of the face measure to the element measure.

If you consider a rectangular element of size $[h_x, h_y]$, then on e.g. the horizontal edges, we have the perpendicular element size $h$ = $h_y$, and
$$\int_{e} h^{-1} ds = \int_{e} h_y^{-1} ds = h_x / h_y$$

The face normal will be scaled like the face measure, i.e. $nor = (0, \pm h_x)$, and $w$ will scale like the reciprocal of the element measure, $w = 1/(h_x h_y)$. So the vector $n_i$ will be given by $n_i = w \times nor = (0, \pm 1 / h_y)$, and finally the weight $w_q$ is set to $n_i \cdot nor$, which gives $h_x / h_y$ as desired.

Does that make sense to you?

It can be helpful to modify `ref-square.mesh` to create arbitrary elements of size $[h_x, h_y]$, and then you can run ex14 with no refinements and polynomial degree 0 to print out the weight $w_q$ on each face, and I believe it should match up with the definition above.

**Comment by smsolivier** [comment]
Yes, you are right! I was forgetting about the factor of `|nor|` from changing variables from physical to reference space. So it sounds like I'm effectively setting $\kappa \propto 1/h^2$ in my implementation. Oops... 

Thanks for the help @pazner. 
Sam
