### ISSUE TITLE
mfem.lib file for window share libs install?

### ISSUE THREAD

**Issue by cyrush** [mfem/mfem#3439]
Hi All,

I am building and installing mfem (4.4) on windows using cmake.

The `lib/mfem.dll` is installed -  but the `lib/mfem.lib` (info how to use the dll for other projects is missing)

The cmake exported files also reference `lib/mfem.lib`.

And the .lib file is missing from the build dir. 

Any idea how to make sure it's created & installed?

Thanks!

**Comment by cyrush** [comment]
Here is an excerpt from the script that is building mfem:
```
echo "**** Configuring MFEM ${mfem_version}"
cmake -S ${mfem_src_dir} -B ${mfem_build_dir} \
  -DCMAKE_VERBOSE_MAKEFILE:BOOL=${enable_verbose}\
  -DCMAKE_BUILD_TYPE=${build_config} \
  -DBUILD_SHARED_LIBS=${build_shared_libs} \
  -DMFEM_USE_CONDUIT=ON \
  -DCMAKE_PREFIX_PATH="${conduit_install_dir}" \
  -DCMAKE_INSTALL_PREFIX=${mfem_install_dir}

echo "**** Building MFEM ${vtkm_version}"
cmake --build ${mfem_build_dir} --config ${build_config} -j${build_jobs}
echo "**** Installing MFEM ${mfem_version}"
cmake --install ${mfem_build_dir}
```

**Comment by kennyweiss** [comment]
In case it's helpful, here's how axom configures/builds mfem@4.5 on Windows via `vcpkg`: 
https://github.com/LLNL/axom/blob/develop/scripts/vcpkg_ports/mfem/portfile.cmake

I don't see anything about `.lib` files, perhaps because we build with `-DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=ON` (?)

Notes: 
* `vcpkg` imposes requirements on the structure of the install directory, so there's a bunch of minor reorganizations and fixups in that recipe
* Axom has a few patches in support of dll import/export -- https://github.com/LLNL/axom/blob/develop/scripts/vcpkg_ports/mfem/export-extern-vars.patch
    * I opened a PR a while back to merge these into mfem, but it looks like I didn't complete it -- 
    https://github.com/mfem/mfem/pull/1401

**Comment by cyrush** [comment]
Thanks @kennyweiss !

```
-DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=ON
```

Is what was required.

**Comment by tzanio** [comment]
Thanks @kennyweiss !

**Comment by tzanio** [comment]
@cyrush, should we make any changes to the CMake files in MFEM?

**Comment by cyrush** [comment]
If you could automatically set `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=ON` when an windows and building shared libs, that would save a step for folks trying to build.

**Comment by cyrush** [comment]
@tzanio @kennyweiss  When linking a mfem smoke test I am seeing some missing symbols.

Usually this means things are declared - but not implemented (or are implemented with a different signature on accident) 

This is mfem 4.5. Any ideas of how to resolve this?

```
       "C:\Users\cyrus\Documents\GitHub\ascent\build-no-dray\ALL_BUILD.vcxproj" (default target) (1) ->
       "C:\Users\cyrus\Documents\GitHub\ascent\build-no-dray\tests\thirdparty\t_mfem_smoke.vcxproj" (default target) (83) ->
       (Link target) ->
         t_mfem_smoke.obj : error LNK2001: unresolved external symbol "private: static enum mfem::MemoryType mfem::MemoryManager::host_mem_type" (?host_mem_type@MemoryManager@mfem@@0W4MemoryType@2@A) [C:\Us 
       ers\cyrus\Documents\GitHub\ascent\build-no-dray\tests\thirdparty\t_mfem_smoke.vcxproj]
         t_mfem_smoke.obj : error LNK2001: unresolved external symbol "private: static class mfem::Device mfem::Device::device_singleton" (?device_singleton@Device@mfem@@0V12@A) [C:\Users\cyrus\Documents\Gi 
       tHub\ascent\build-no-dray\tests\thirdparty\t_mfem_smoke.vcxproj]
         t_mfem_smoke.obj : error LNK2001: unresolved external symbol "public: static int const (* mfem::Geometry::Constants<4>::Edges)[2]" (?Edges@?$Constants@$03@Geometry@mfem@@2QAY01$$CBHA) [C:\Users\cyr 
       us\Documents\GitHub\ascent\build-no-dray\tests\thirdparty\t_mfem_smoke.vcxproj]
         t_mfem_smoke.obj : error LNK2001: unresolved external symbol "public: static int const (* mfem::Geometry::Constants<4>::FaceVert)[3]" (?FaceVert@?$Constants@$03@Geometry@mfem@@2QAY02$$CBHA) [C:\Use 
       rs\cyrus\Documents\GitHub\ascent\build-no-dray\tests\thirdparty\t_mfem_smoke.vcxproj]
         C:\Users\cyrus\Documents\GitHub\ascent\build-no-dray\bin\Debug\t_mfem_smoke.exe : fatal error LNK1120: 4 unresolved externals [C:\Users\cyrus\Documents\GitHub\ascent\build-no-dray\tests\thirdparty\ 
       t_mfem_smoke.vcxproj]

```

**Comment by v-dobrev** [comment]
The first "missing" symbol, `mfem::MemoryManager::host_mem_type`, is defined and initialized here: https://github.com/mfem/mfem/blob/v4.5/general/mem_manager.cpp#L1710

`mfem::Device::device_singleton` is here: https://github.com/mfem/mfem/blob/v4.5/general/device.cpp#L64

`mfem::Geometry::Constants<4>::Edges` (`4 = Geometry::TETRAHEDRON`) is here: https://github.com/mfem/mfem/blob/v4.5/fem/geom.cpp#L935-L937

`mfem::Geometry::Constants<4>::FaceVert` is here: https://github.com/mfem/mfem/blob/v4.5/fem/geom.cpp#L944-L946

I'm not sure why you see this error. We don't see such an issue in our GitHub actions testing on Windows. We test static builds, could the shared build be (part of) the issue?

**Comment by cyrush** [comment]
Yes -- for shared libs windows, all exported symbols have to be resolved (even if they aren't used)

``Device Device::device_singleton;`` in the CPP file defined in the `mfem::internal::`` namespace instead of  the ``mfem::`` namespace -- so that's the reason for that one. 

I'll run the others down as well. `host_mem_type` is an enum class, not sure if there is something funny about exporting those on windows.

**Comment by cyrush** [comment]
Hmm maybe internal is closed, let me keep looking.

**Comment by cyrush** [comment]
Thank you Kenny!!! I was just staring to tie this to externs and the fact there were multiple compilation units.

**Comment by tzanio** [comment]
@kennyweiss and @cyrush we plan to release `mfem-4.5.2` next week. 

Is it important for you to have the changes mentioned here and in #3451 in the release?

@kennyweiss, how close is #1401 to be ready for review?

**Comment by cyrush** [comment]
It would be very helpful to have both changes in. 

For #3451: Happy to help make the changes, but I need guidance on what folks think the proper way to avoid the macro conflict  should be. 

For #1401, We don't need to use CMake GenerateExportHeader`, we could use a simple header that is included regardless of cmake vs makefile case. That way it won't need to be auto generated. 
That may solve some of the hang up.

**Comment by kennyweiss** [comment]
@tzanio -- I'll look at it today and try to resolve the export header issue in the make system. It might not be too difficult (per @cyrush's comment).

**Comment by cyrush** [comment]
@kennyweiss I am going to take a pass at the new header strategy tomorrow (Thurs 2/23) when I have better Windows access.  I will test both export changes and the macro defense changes in #3501.

**Comment by cyrush** [comment]
Update: 

I solved a few of the cases w/o using the export header, then got excited and tried to avoid the header all together.

That wasn't fruitful:

 `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS` doesn't help us with globals and it doesn't help us with static const member vars. 

https://www.kitware.com//create-dlls-on-windows-without-declspec-using-new-cmake-export-all-feature/

So I am working on the export header again.

**Comment by kennyweiss** [comment]
@cyrush -- I updated my branch last week to add an auto-generated export header in CMake and a simple one in make. 
I think it's pretty close to working and was able to manually test the build in cmake and make, but haven't had a chance to more thoroughly test it, e.g. by running it through axom's uberenv.
There was also a failure in mfem's CI related to doxygen that I haven't had a chance to dig into.

See #1401

**Comment by cyrush** [comment]
@kennyweiss thanks, I will try your branch combined with the macro changes  in #3501 and see how things go.

**Comment by cyrush** [comment]
@kennyweiss your branch with the macro changes is working for me!

**Comment by tzanio** [comment]
@cyrush, can we close this now?

**Comment by cyrush** [comment]
Yes: CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS is in the build system along with the other export changes. 


https://github.com/mfem/mfem/blob/92bf531fab08deff5d6ba687e26bc276a33e1650/CMakeLists.txt#L193
