### ISSUE TITLE
Small misconfiguration in coverall

### ISSUE THREAD

**Issue by IdoAkkerman** [mfem/mfem#344]
When clicking on a particular file the following error pops up:

SOURCE NOT AVAILABLE
The file "general/array.cpp" isn't available on github. Either it's been removed, or the repo root directory needs to be updated.

**Comment by tzanio** [comment]
Can you provide more details?

When I click on the files at https://coveralls.io/github/mfem/mfem I do see the annotated source, e.g. https://coveralls.io/builds/14120977/source?filename=fem%2Fstaticcond.cpp.

**Comment by IdoAkkerman** [comment]
Apparently it is fixed...?
For build 1398 ( [https://coveralls.io/builds/14056760](https://coveralls.io/builds/14056760) ) the error does occur
For instance: [https://coveralls.io/builds/14056760/source?filename=general%2Farray.cpp](https://coveralls.io/builds/14056760/source?filename=general%2Farray.cpp)

**Comment by tzanio** [comment]
Weird. Lets assume it is fixed :)
