### ISSUE TITLE
Error: MPI_ABORT was invoked on rank 11 in communicator MPI_COMM_WORLD with errorcode 1.

### ISSUE THREAD

**Issue by shani9383** [mfem/mfem#3442]
Hi, 

When I use local MFEM (locally build parallel MFEM and GLVis libraries) to solve EX2P with a mesh I generated I succeed to get results and the process finishes without any errors. 
However, while using the browser-based MFEM (by running the MFEM Docker container with the VS Code and GLVis window) for the same problem and the same mesh file as before, I receive an error and the process aborts.  How can I fix this error?
Thanks
Shani

```console
euler@eeffd1fa6087:~/mfem/examples$ mpirun -np 16 ./ex2p -m ../data/1M-ELEMENTS.mesh
Options used:
   --mesh ../data/1M-ELEMENTS.mesh
   --order 1
   --amg-for-systems
   --no-static-condensation
   --visualization
   --by-vdim
   --device cpu
Device configuration: cpu
Memory configuration: host-std
METIS Error: A contiguous partition is requested for a non-contiguous input graph.



Mesh::GeneratePartitioning:  error in METIS_PartGraphKway!
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 11 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
```

**Comment by pazner** [comment]
Is your mesh non-contiguous?

This was fixed relatively recently in #3303. Maybe the MFEM version in your container is out of date?

**Comment by shani9383** [comment]
Thanks for your response.
1. Where can I find the container with the most updated MFEM version?
2. What does non contiguous mesh mean?

Thanks
Shani

**Comment by pazner** [comment]
1. The Dockerfile to build the container is [here](https://github.com/mfem/containers/blob/main/developer/Dockerfile)
2. Non-contiguous means that the mesh has multiple non-connected parts

**Comment by shani9383** [comment]
Hi,

1. I checked and this is the container I'm using
2. I'm running the same mesh file locally on my computer and it runs
without any errors. I think that if there were non-connected parts in the
mesh file , when using MFEM locally I would except to get the same errors
and I would not receive results.  I need to use the container to run huge
mesh file with a server (due to lacking memory of my computer) .

I would really appreciate your help
I'm attaching the mesh file that I'm trying to run  with the container (it
is a fifth slice of the full model) but it gives an error  (when running it
locally on my computer there are no errors).

Thanks
Shani
 1M-ELEMENTS.mesh
<https://drive.google.com/file/d/1CL8T5q5sBntLIZH1k3pwe0Vx3HgSFjRB/view?usp=drive_web>

**Comment by pazner** [comment]
> 1. I checked and this is the container I'm using

Right, but is the container image up-to-date? If not, try rebuilding the container image. The image available on GHCR was built some time ago, and so it does not include recent improvements.

> 2. I'm running the same mesh file locally on my computer and it runs without any errors. I think that if there were non-connected parts in the mesh file , when using MFEM locally I would except to get the same errors and I would not receive results.

Presumably the local version of MFEM is more recent. PR #3303 handles properly the case of non-contiguous meshes, which would explain why you are not getting the errors locally.

**Comment by shani9383** [comment]
Thank you. this issue is solved
