### ISSUE TITLE
Overflow in GenerateOffsets

### ISSUE THREAD

**Issue by Dan2997925** [mfem/mfem#3446]
Hey folks, I am getting "overflow in offsets" from ParMesh:GenerateOffsets. This is probably user error, but I don't know what these offsets are, or what is happening. Suggestions?

**Comment by pazner** [comment]
Are you solving really huge problems (more than 2e9 unknowns)? If so, you should configure hypre with big int or mixed int mode.

If not, then some more information will be needed to diagnose the problem.

**Comment by Dan2997925** [comment]
Is "offsets" a mesh thing? I certainly don't have 2e9 mesh element or nodes.

**Comment by pazner** [comment]
The offsets have to do with the parallel partitioning of the degrees of freedom. You could get overflow when your finite element space very many DOFs.

**Comment by tzanio** [comment]
@Dan2997925 is the *hypre* you used configured with "assumed partitioning" and 64-bit int support (these should be the default in recent *hypre* versions)?

An overflow in this function will suggest a total number of unknowns in a finite element space greater than 2B, using hypre configured with 32-bit integers.

**Comment by tzanio** [comment]
@Dan2997925 I'll close this now, but please feel free to reopen (or reach out directly) if the source of the overflow is still unclear.
