### ISSUE TITLE
How to multiply constant value to mass matrix (bilinear form)?

### ISSUE THREAD

**Issue by sungho91** [mfem/mfem#3449]
Hello. I have a quick question about how to scale the mass matrix using constant scalar value.
In mfem, a linear form (vector) can be multiplied by a scalar but I can't find ways to do that to a bilinear form.
Any comment can be helpful to me. 

Best

Sungho

**Comment by pazner** [comment]
Easiest is probably to pass in a `ConstantCoefficient` when you construct the `MassIntegrator`
```c++
ConstantCoefficient coeff(3.0);
a.AddDomainIntegrator(new MassIntegrator(coeff));
```

**Comment by sungho91** [comment]
Thank you!
