### ISSUE TITLE
compile error with datacollection.hpp on windows 

### ISSUE THREAD

**Issue by cyrush** [mfem/mfem#3451]
On Windows, inside Ascent, I see the following compile error:
```
 C:\Users\cyrus\Documents\GitHub\ascent\scripts\build_ascent\install\mfem-4.5\include\mfem\fem\datacollection.hpp(380,11): error C2059: syntax error: 'constant'
```

The related code is an enum def:

https://github.com/mfem/mfem/blob/d5f46a61bc77df5692527bf827a3829f512cd28c/fem/datacollection.hpp#L381

Even though this is an enum which is inside a class and a namespace -- I suspect I have some include that brings in a macro that conflicts with one of these names. I am going to try to track the include issue down - but if you are open to using a name unique to MFEM (`MFEM_NO_ERROR` ?) that should solve the issue.

**Comment by cyrush** [comment]
I pinged Kathleen Biagas (VisIt's Windows expert) and she said that she does have to change the following:

```
REGISTERED
NO_ERROR
```

To avoid compile issues.

@tzanio  @v-dobrev  -- I would be happy to add a PR to address this if we can identify the changes the MFEM team would support. 

If we are worried about backward compatibility, we could keep old names for non windows case for a time.

**Comment by v-dobrev** [comment]
Shouldn't this be addressed in the packages that define these un-scoped macros?

**Comment by cyrush** [comment]
Based on what I can tell, it's system headers on windows -- I believe I asw these errors even if I included MFEM first.

I can try to confirm this again using a less complicated smoke test.

**Comment by v-dobrev** [comment]
FWIW, we don't see issues with that enum in the Windows tests on Github Actions or in Appveyor CI.

**Comment by jandrej** [comment]
See https://stackoverflow.com/questions/49237883/macro-no-error-conflict

**Comment by v-dobrev** [comment]
One option for fixing this may be to add the following somewhere before our declaration of `mfem::DataCollection::NO_ERROR` in `datacollection.hpp`:
```c++
#ifdef NO_ERROR
#undef NO_ERROR
#define MFEM_REDEFINE_NO_ERROR
#endif
```
And then add the following after the last use of `mfem::DataCollection::NO_ERROR` in `datacollection.hpp`:
```c++
#ifdef MFEM_REDEFINE_NO_ERROR
#define NO_ERROR 0L // as defined in winerror.h
#endif
```
Here's one place where one can see the definition  of `NO_ERROR` in `winerror.h`: http://web.archive.org/web/20110225033028/http://msdn.microsoft.com/en-us/library/ms819773.aspx

Also, we can add another identifier (e.g. `NO_ERROR_`, `MFEM_NO_ERROR`, or something like that) in the enum with the same value as `mfem::DataCollection::NO_ERROR`. This way users can use the new identifier when `NO_ERROR` is defined as a macro, e.g. when they include both `mfem.hpp` and `winerror.h` in the same file.

**Comment by v-dobrev** [comment]
Another simpler solution may be to define the enum this way:
```c++
   enum
   {
      // Workaround for use with headers that define NO_ERROR as a macro,
      // e.g. winerror.h:
#ifndef NO_ERROR
      NO_ERROR = 0,
#endif
      // Use the following identifier if NO_ERROR is defined as a macro,
      // e.g. by winerror.h:
      NO_ERROR_ = 0,
      READ_ERROR = 1,
      WRITE_ERROR = 2
   };
```
And also redefine:
```c++
   void ResetError(int err_state = NO_ERROR_) { error = err_state; }
```
Other uses of `NO_ERROR` inside MFEM are in `.cpp` files, so they should be fine.

**Comment by cyrush** [comment]
For the second one, outside of mfem internal cpp -- users would have to change to `NO_ERROR_` to do their checks?

**Comment by cyrush** [comment]
I guess that would only impact Windows folks, so likely a small set of folks. 

I think we also have to do this for `Memory::FlagMask::REGISTERED`, would you be ok with the same type of fix?

**Comment by v-dobrev** [comment]
> I think we also have to do this for `Memory::FlagMask::REGISTERED`, would you be ok with the same type of fix?

Yes, I think that's a reasonable solution.

**Comment by v-dobrev** [comment]
I found that `REGISTERED` is defined in the windows header file `nb30.h`. Both `winerror.h` and `nb30.h` are included by `Windows.h`.
