### ISSUE TITLE
Serial bottleneck in `ParNCMesh`

### ISSUE THREAD

**Issue by hughcars** [mfem/mfem#3455]
Hi mfem developers,

Thanks for the work on the library, it's been very helpful and is much appreciated. I'm currently working on using the `ParNCMesh` structure, and noticed in the comments (and the paper describing the algorithm) that each rank essentially stores a copy of the root mesh (the original unrefined serial mesh). The issue is, this introduces a serial bottleneck that I'm running into.

For context:
* Loading a large serial mesh onto each processor then cutting it up and throwing away all but the rank specific piece, can run out of memory. This can be addressed by [this pr](https://github.com/mfem/mfem/issues/2542), so is a surmountable issue
* A mesh needs to be marked NC before being partitioned (a ParNCMesh can't be built off of a ParMesh). This can kind of being circumvented with the above `MeshPartitioner` by having rank 0 make the NCMesh, then send a copy via bytestream to every rank and then (after exposing some protected methods) constructing a `ParNCMesh` on each processor, and attaching this to `ncmesh` and `pncmesh` of the generated `ParMesh`. 

This strategy is ultimately limited however, in that every rank has to hold the original serial mesh (in the reduced form of the `NCMesh` structure, but still a large chunk). My question is: in the eyes of the mfem developers, how should this serial bottle neck be removed? For cases with non-trivial initial geometries (namely not a box) where geometry resolution requires a large number of elements, this is basically a show stopper for using AMR.

**Comment by jakubcerveny** [comment]
The initial geometry definitely does not need to be a box, the only requirement is that the coarse mesh is small enough to fit on each rank. It would be interesting to see your geometry, is it really impossible to mesh coarsely, so that the geometry is captured by at most tens of thousands of elements? Would curved elements help here? 

Please also note that the serial Mesh can be freed once the ParNCMesh is generated. In the NC mode the Mesh is regenerated to only represent the fine refinements of a particular partition. More here: https://mfem.org/howto/ncmesh/

It is not impossible to extend the current implementation so that portions of the root mesh are thrown away, and include the root elements in the rebalancing messages, it's just a large project that we have not undertaken yet.

**Comment by hughcars** [comment]
Thanks for the reply Jakub. In many cases you are correct the geometries are simple enough to be captured in a few thousand. However we also have a few cases where we have required in the circa 1-5 million elements, see fig 1.e from [this paper](https://arxiv.org/pdf/2206.12803.pdf) for an example. It is also these complex cases that end up being the most computationally taxing, and thus would benefit most from AMR, so we're trying to design to that.

It is quite likely better results might be achievable with a better mesher able to generate coarser initial meshes. However, it's for electromagnetism, with lots and lots of waveguides essentially, so the initial element quality is kind of important too. So there's a limit to quite how anisotropic the elements in the initial mesh could be. You could likely get coarser initially by using a mesh connecting all corners to other visible corners in a linear simplex mesh, but the element quality is going to plummet, and without anisotropic refinement, you're doomed to that initial shape factor.

Re curving: This particular example curved wouldn't help, but there are also meshes I can't show you where curved does help (and we're already leaning on it a lot). Ultimately though, we're getting into geometries that are very difficult to reduce, and users are asking for ever larger geometries, so it's a matter of time.

Communicating the root mesh elements was the approach I had been thinking about undertaking, but after going through the ncmesh/parncmesh classes for a while, had begun to realize is a pretty big undertaking as the presence of those elements seems to be quite a basic assumption in the class. I take then that this isn't something in the mfem developer pipeline?

**Comment by tzanio** [comment]
@hughcars, thanks for bringing this up. I think it will be good to add it, but I am not sure we currently have the resources to work on it. How critical it is for your application?

**Comment by hughcars** [comment]
We have changed our plans presently to work around it. Our previous parallelism strategy has been pure MPI, (64 ranks on a 64 processor node), whereas this has given us the push to start thinking more about heterogenous parallelism (mixing openmp and mpi), as that would circumvent this somewhat. It also works towards another goal of accelerator usage. So in summary, I would say not critical to our application.
