### ISSUE TITLE
undefined references despite adding libmfem

### ISSUE THREAD

**Issue by Nick-Seinsche** [mfem/mfem#3460]
I am trying to compile a simple fem program and essentially everything is an undefined reference during compilation. Is it enough to run make install after building (i did make serial -j) and give the include directory and the libary libmfem.a to the compiler?

Sorry for the basic question.
Best Regards

**Comment by jandrej** [comment]
Usually this is enough. Can you provide more information like what command you are using to compile a minimal example and what the output is?

**Comment by Nick-Seinsche** [comment]
the command I am using is:
`g++ -I../Libraries/mfem-4.5/mfem/include -L../Libraries/mfem-4.5/mfem/lib -lmfem main.cpp -o main.out`
All of the paths are valid. In my simple code example, I just create a mesh. An error I get is e.g. this:
`main.cpp:(.text+0x2c2): undefined reference to mfem::Mesh::Mesh(char const*, int, int, bool)`

**Comment by tzanio** [comment]
Hi @Nick-Seinsche, what is your version of `g++`?

**Comment by Nick-Seinsche** [comment]
Hi, I am using g++ version 7.5.0.

**Comment by tzanio** [comment]
Can you try adding `-std=c++11` to the build line?

**Comment by Nick-Seinsche** [comment]
I already tried adding `-std=c++11`. I also tried different versons of mfem. Still I run into the same problem.

**Comment by Nick-Seinsche** [comment]
@sebastiangrimberg You are completely right. It works fine now using the correct oder.
Thanks for the quick help. I guess CMake will make things easier.

**Comment by tzanio** [comment]
Thanks @sebastiangrimberg !
