### ISSUE TITLE
Mesh refinement ex2p

### ISSUE THREAD

**Issue by shani9383** [mfem/mfem#3464]
Hi,

I’m using the code provided for ex2p to solve a linear elastic problem with about 5 million liner HEX elements (~126 million DOF). I would like MFEM to solve the problem for the original mesh I’m providing without refining\modifying it.
1.	I would appreciate your help with the required modifications needed in the ex2p code to use the original provided mesh for the analysis (without refinement). I tried making changes to section 6 and 7 in the code, but I received many errors.
2.	I used the miniapp mesh explorer to evaluate the elements size. Is there a better way to get data regarding the mesh of the solution?
3.	Can you please explain how the refinement level is defined in the code?
```cpp
	   {
	      int ref_levels =
	         (int)floor(log(1000./mesh->GetNE())/log(2.)/dim);
	      for (int l = 0; l < ref_levels; l++)
	      {
	         mesh->UniformRefinement();
	      }
	   }
	
	   ParMesh *pmesh = new ParMesh(MPI_COMM_WORLD, *mesh);
	   delete mesh;
	   {
	      int par_ref_levels = 1;
	      for (int l = 0; l < par_ref_levels; l++)
	      {
	         pmesh->UniformRefinement();
	      }
	   }
```
Thanks
Shani

**Comment by pazner** [comment]
Hi @shani9383,

1. Just comment out (or delete) the lines with `mesh->UniformRefinement();` and `pmesh->UniformRefinement();`.
2. `Mesh::GetCharacteristics` will give you the min/max element sizes, aspect ratios, etc. You can also use this function to get all the sizes of the elements. There is also `Mesh::GetElementSize` for a single element.
3. The "refinement level" is the number of times to perform uniform refinement (splitting each hex element into 8 hexes by splitting at the midpoints). The logic for computing the serial refinement level in this example is to refine the mesh to have approximately 1000 elements (in your case, the serial refinement level should evaluate to zero). In ex2p, it is hard-coded to refine the mesh one more time after the parallel decomposition.

**Comment by shani9383** [comment]
Thanks.

Where can I find data and examples how to
use GetCharacteristics and GetElementSize ?only in other examples?

Is there a place where function as you suggested are written and
explained?  I mean additional tools that can help with the post processing
of the results.

**Comment by pazner** [comment]
`Mesh::GetElementSize` is documented in the [Doxygen documentation](https://mfem.org/dox/) (specific link [here](https://docs.mfem.org/html/classmfem_1_1Mesh.html#a8af9265879c7a3e684171b503757cfd9)).

Unfortunately, `Mesh:: GetCharacteristics` does not look like it is documented, but it should be easy to use.

What specific type of postprocessing are you trying to do?
