### ISSUE TITLE
Conversion other mesh formats to mfem

### ISSUE THREAD

**Issue by Dourghost** [mfem/mfem#3470]
Hi, 

Can anyone guide me about the easiest way to convert a vtk file to mfem v1.0 mesh ? I am working on a project which requires mfem v1.0 meshes.

**Comment by pazner** [comment]
You can use the `mesh-explorer` miniapp to load your VTK mesh, and choose the `S` option to save in MFEM format.

**Comment by tzanio** [comment]
To add to @pazner's answer -- you can also write a simple program that creates an MFEM mesh from a file (this is general and supports VTK meshes in particular) and then saves it to a file (by default this will be done in the mfem v1.0 format).

Something like:

```c++
   Mesh mesh("input.vtk");
   ofstream mesh_ofs("output.mesh");
   mesh_ofs.precision(8);
   mesh.Print(mesh_ofs);
```

**Comment by Dourghost** [comment]
Hey. Thanks a lot for the reply. I tried the above method by running the mesh-explorer.cpp code , but it seems to work only for Unstructured Grids. Does the method mentioned above, i.e. writing this piece of code, work with all other types of vtk meshes ? Also, it would be really helpful if you can elaborate on the program part, like where is the code supposed to be written and run ?

**Comment by pazner** [comment]
No, MFEM only supports unstructured VTK meshes. Maybe you can use [meshio](https://github.com/nschloe/meshio) to convert to a [format supported by MFEM](https://mfem.org/mesh-formats/) (e.g. Gmsh 2.2)

**Comment by Dourghost** [comment]
Thanks for the help. Just to be sure, I have somehow converted the mesh I need into a unstructured vtk grid and trying to run mesh-explorer.cpp. Does the mesh-explorer.cpp only work on linux machines as I am getting some weird errors when I run the code in a windows machine ?

**Comment by pazner** [comment]
I believe it should work on Windows as well, but I don't have a Windows machine to test. Without the specific error message it will be impossible to diagnose the problem.

If mesh-explorer is giving you issues, I suggest @tzanio's answer: put that code in the main function (e.g. by modifying something simple like ex0.cpp) and run the compiled executable.
