### ISSUE TITLE
Question: `HashTable` vs `std::unordered_map`?

### ISSUE THREAD

**Issue by hughcars** [mfem/mfem#3471]
I'm looking at the `HashTable` presently, as I am attempting to add move semantics into the `NCMesh` class and a few other places. However the more I look, the more I am wondering why not use a `std::unordered_map` instead? This kind of thinking occurs in a few places in the library, where there's an stl implementation of a given type/class that is being reimplemented. My question is: why the bias against the stl? There's already `<vector>` `<map>` [included](https://github.com/mfem/mfem/blob/master/mesh/ncmesh.hpp#L24-L25), and c++11 is the minimum standard version, which begs the question of why roll another hashtable?

**Comment by jakubcerveny** [comment]
It's mostly historical reasons. At the time NCMesh was created, C++11 was not allowed in MFEM and `unordered_map` didn't exist in C++03. Overall, the C++ style in MFEM is still rather conservative, where "simple" C++ features are preferred. The STL is now accepted, I think.

**Comment by hughcars** [comment]
Makes sense, thanks.
