### ISSUE TITLE
subclass is virtual, why not virtual here, otherwise base pointer or reference call this func always get ANY_TYPE?

### ISSUE THREAD

**Issue by zhuyidong-YP** [mfem/mfem#3476]
https://github.com/mfem/mfem/blob/61b394409bca6a9ecd3319c5a42d7eaedd5de5e6/linalg/operator.hpp#L307

**Comment by v-dobrev** [comment]
This is intentional, as mentioned in the Doxygen comment.

**Comment by zhuyidong-YP** [comment]
> This is intentional, as mentioned in the Doxygen comment.

What is the purpose of providing this function? when i call,I don't get what I want.

**Comment by v-dobrev** [comment]
If you need the dynamic type, we can add another (virtual) method. Alternatively, you can probably use `dynamic_cast` to check the real type of an `Operator`. We do that in some places where only specific sub-classes of `Operator` can be used. For example, here: https://github.com/mfem/mfem/blob/1f89a8884430fb6cd41d9b094aeedaa4f6c7a067/linalg/hypre.cpp#L3976-L3977

What is your use case? Is `dynamic_cast` not sufficient?

**Comment by zhuyidong-YP** [comment]
> 

how do you know op`s type? It may be SparseMatrix or ComplexSparseMatrix, if you do not know type, how to dynamic_cast?

**Comment by v-dobrev** [comment]
For completeness: here one way to use `dynamic_cast`:
```c++
void my_func(Operator *op)
{
   SparseMatrix *sm = dynanic_cast<SparseMatrix *>(op);
   if (sm != nullptr)
   {
      // 'op' points to a SparseMatrix object
      // use 'sm' to access SparseMatrix-specific (non-virtual) methods or data
   }
   else
   {
      // 'op' does not point to a SparseMatrix
      // try another dynamic_cast ...
   }
```

**Comment by zhuyidong-YP** [comment]
> For completeness: here one way to use `dynamic_cast`:
> 
> ```c++
> void my_func(Operator *op)
> {
>    SparseMatrix *sm = dynanic_cast<SparseMatrix *>(op);
>    if (sm != nullptr)
>    {
>       // 'op' points to a SparseMatrix object
>       // use 'sm' to access SparseMatrix-specific (non-virtual) methods or data
>    }
>    else
>    {
>       // 'op' does not point to a SparseMatrix
>       // try another dynamic_cast ...
>    }
> ```

thanks,
