### ISSUE TITLE
DG advection equation (ex 9)

### ISSUE THREAD

**Issue by L29430** [mfem/mfem#3479]
Hello everybody,

I would like to solve the following equation with a Discontinuous Galerkin formalism:

![image](https://user-images.githubusercontent.com/67911538/220325501-6922e4ac-a0bb-4c30-81e9-8237de081af1.png)

Considering that the velocity **v** of the advection equation is a vector field computed in a previous step in a discontinuous space. I would like to know how the solutions 'u' and '**v**' are solved on the faces? What value do we take?

Best wishes

**Comment by v-dobrev** [comment]
Currently, the implementation assumes that the velocity `v`  has continuous normal component across faces and it computes `v` through the first element adjacent to the current face (in the code the velocity coefficient is denoted by `u`): https://github.com/mfem/mfem/blob/5a0414146c00b7ae8d9526265c81080a503cfd6a/fem/bilininteg.cpp#L3280

I have not carefully considered the case of `v` where `v.n` has jumps across faces -- I suspect that it may cause conservation issues on continuous level. If the jump of `v.n` converges to zero under refinement, one can probably just use the average `{v.n}` on the face to enforce discrete conservation.

**Comment by L29430** [comment]
Hello,

Thank you for your answer,

I would also like to understand how the solution u and the velocity **v** are computed on the faces of the elements?

**Comment by v-dobrev** [comment]
Basically, the quadrature points, `ip`, on the reference face element are mapped to the volume reference element: `ip` is mapped to `eip1` and `eip2` where 1 and 2 denote the two adjacent volume elements, respectively. After that the basis functions are evaluated at these points for face integration. The velocity is computed on the face by evaluating the coefficient `u` on element 1 at the quadrature point `eip1`, as mentioned above.

**Comment by L29430** [comment]
Hello,

Thank you for your answer,

How can I know the position of the quadrature points?

**Comment by jandrej** [comment]
You should be able to query each quadrature points coordinates by it's member variables `x, y, z` e.g. `ip1.x` etc.
