### ISSUE TITLE
When I call Assemble() to do integrate RHS, the number of calls Assemble() increases by +1 time.

### ISSUE THREAD

**Issue by sungho91** [mfem/mfem#3504]
Hi all.

I try to introduce the body force term as an RHS vector.

So, I wrote code this way,

std::cout << "before Assemble" <<  std::endl;
BodyForceIntegrator *bi = new BodyForceIntegrator(data);
bi->SetIntRule(&ir);
Body_Force.AddDomainIntegrator(bi);
Body_Force.Assemble();
std::cout << "after Assemble" <<  std::endl;

But, I realized the number of assemble increased with time step being.

The result of the printout is following below.
"assembling ... : " should be printed out once but it increases by +1.

Unfortunately, body force is linearly accumulated in my code.
Any comments can be helpful to me.

Many thanks

Sungho

**************************************************************************
Printout on my prompt

simulation starts
before Assemble
assembling ... : 
after Assemble
before Assemble
assembling ... : 
assembling ... : 
after Assemble
before Assemble
assembling ... : 
assembling ... : 
assembling ... : 
after Assemble
before Assemble
assembling ... : 
assembling ... : 
assembling ... : 
assembling ... : 
after Assemble
before Assemble
assembling ... : 
assembling ... : 
assembling ... : 
assembling ... : 
assembling ... : 
after Assemble

....... continue

**Comment by atallah727** [comment]
Hello @sungho91 , it seems you have the AddDomainIntegrator inside your time integrator. Can you call AddDomainIntegrator before you time step loop?

**Comment by sungho91** [comment]
Oh my goodness, your expectation is perfect. I solved this problem according to your suggetion. Thank you so much.

By the way, why this is happening?

**Comment by atallah727** [comment]
Glad to hear that @sungho91 . The Body_Force is of LinearForm which is a child of the Vector class. Every time you call AddDomainIntegrator it just pushes back the integrator into a list which assemble later loops over.

**Comment by sungho91** [comment]
@atallah727 Thank you so much I fully understood it.
