### ISSUE TITLE
How to set up a product interlation operator in the linear form?

### ISSUE THREAD

**Issue by baigm11** [mfem/mfem#3507]
Dear all,

I'm trying to use the following expression in my linear form

$$\int \nabla f\cdot \nabla I_h(g\phi_h)dx$$

, but I didn't find a suitable way to do it. Do you have any idea? Thank you!

**Comment by v-dobrev** [comment]
Hi @baigm11,

Sorry for the late reply. Can you elaborate: how are $f$ and $g$ given (e.g. are they analytic expressions?), what is $I_h$, and is $\phi_h$ the test function?
