### ISSUE TITLE
How to get the matrix of the gradient for a ParBlockNonlinearForm? 

### ISSUE THREAD

**Issue by AdrainT** [mfem/mfem#3509]
Hi. I am new to mfem. I want to extract a submatrix of the gradient for a ParBlockNonlinearForm. I find that the gradient is returned in ParBlockNonlinearForm::GetGradient(const Vector &x). However, it is a BlockOperator class which I could not find a method that could directly extract its submatrix. Although I could achieve my purpose by multiply this BlockOpeartor with some vectors ei which have only one nonzero element using Mult(), it seems inefficient. Is there any elegant way to achieve my purpose?

Thanks for any advice!

**Comment by pazner** [comment]
You can get the blocks of the gradient using `BlockOperator::GetBlock`. This will return an `Operator &`, which can be cast to the appropriate matrix type (e.g. `dynamic_cast<HypreParMatrix&>(block_gradient.GetBlock(i,j));`). By default, the matrix type will be `HypreParMatrix`, but you can change this with `ParBlockNonlinearForm::SetGradientType`.

**Comment by AdrainT** [comment]
Dear pazner, thanks very much for your reply! It is very clear and I will use this!
On the other hand, I would like to ask another related question. In my application, I need to solve a nonlinear system. In the calculation, I need to calculate the Schur complement of a large mfem::HypreParMatrix matrix A = [A00,A01;A10,A11], i.e., calculating S = A00-A01*A11^{-1}*A10. Here A is large scale, sparse and in HypreParMatrix format, A00 is small and in fact dense. I will use S for later calculation.

For this purpose, I first solve system A11X = A10. Then calculate A01X columns by columns. At last, I calculate S = A00-A01X.

My question is, if I want to convert S to be mfem::Densematrix, is there any elegant way to do this?
And what's the best recommended way for this calculation?
