### ISSUE TITLE
Cleanup and new "next" branch

### ISSUE THREAD

**Issue by v-dobrev** [mfem/mfem#351]
This is repository maintenance issue. TODO:

- [x] Rename the current (as of 2017-11-13) `next` branch to `next-pre-v3.3.2`.
- [x] Create a new `next` branch starting from the `v3.3.2` release.

Local copies of `next` can be updated with
```
git checkout -B next origin/next
```

**Comment by tzanio** [comment]
This seems to be working fine for me.
