### ISSUE TITLE
Using HiOp NLP optimizer in topology optimization problem

### ISSUE THREAD

**Issue by ricgross** [mfem/mfem#3511]
Hi everyone!

I am trying to use MFEM in combination with HiOp to solve a topology optimization problem, where the target is to minimize the compliance while being subjected to a volume constraint. I noticed that there is a PR related to a similar issue (#3400), where the same optimization problem was solved using a mirror descent algorithm. However, I would like to use a more standard method (using the pre-implemented classes and functions within `OptimizationProblem`) in order to being able to further expand the optimization problem, e.g. introducing for instance a stress constraint.

I looked at the example `ex9.cpp` within the HiOp folder. I am still though a bit confused on how to pass the value of the objective function and the calculation of the sensitivities to the `OptimizationProblem` routine. 

Ideally, what could help me a lot would be a version of `ex35.cpp` (from #3400) solved instead with the `HiOpNlpOptimizer` and `OptimizationProblem` classes.

Can anyone guide me towards the correct direction? Maybe @brendankeith?

Furthermore, while playing around with the script in `ex35.cpp`, I noticed that the script does not provide the expected results if linear elements are used (standard practice in TO problems to reduce the computational cost). The only changes I made to the original code are in line 176 (`int order = 1`) and lines 259-261:
```
H1_FECollection filter_fec(order, dim); // space for ρ̃
L2_FECollection control_fec(order, dim, BasisType::Positive); // space for ρ
```

What might be the cause of this issue?

In advance, thanks.
Riccardo

**Comment by brendankeith** [comment]
Hi Riccardo,

Thanks for the comments.

@jwang125 is an expert on HiOp. Perhaps, he can help you out there.

Regarding your modifications to the code, it appears that you are using a broken linear finite element space for the control variable and a continuous linear space for the fields. That would mean that the control has more dofs than the first PDE constraint, which is likely going to lead to numerical instability. Can you please elaborate on what you would like your modification to do? Maybe I can still help.

As a rule, MFEM are designed to run without installing external packages. @jwang125 and @bslazarov, perhaps we should add some optional support for other optimizers to ex35.cpp?

**Comment by ricgross** [comment]
Hi @brendankeith,

Thank you for your prompt reply. 

What I wanted to achieve by modifying the code of ex35 was solving the TO problem using first order finite elements (as opposed to second order elements). There was no other purpose than simply testing, given that if the problem is to be expanded in 3D, using second order elements become computationally expensive.

What changes to the code are required to make this possible?

I hope @jwang125 can contribute w.r.t. the HiOp part. 

In advance, thanks.
Riccardo

**Comment by brendankeith** [comment]
@ricgross I looked again at this once I got to the office. I think your problem may be that you didn't run on a fine enough mesh. Generally, you will need a finer mesh if you want to use a lowest-order discretization. Also, keep in mind that many MFEM features are designed for high-order discretizations, so it is possible that you will see better performance with high-order topology optimization in MFEM than you are used to in other codes. If you see any performance issues with high-order TO in MFEM please let me know.

Try the following:
```
   H1_FECollection state_fec(order, dim); // space for u
   H1_FECollection filter_fec(order, dim); // space for ρ̃
   L2_FECollection control_fec(order, dim, BasisType::Positive); // space for ρ
```
and then run on a fine enough mesh. For example, try
```
./ex35 -r 5 -o 1 -alpha 5.0 -epsilon 0.01 -mi 50 -mf 0.5 -tol 1e-5
```

This worked for me. See the attached screenshot. It also works if you use a second-order discretization for the physics, e.g.,
```
   H1_FECollection state_fec(order+1, dim);
```
<img width="800" alt="Screenshot 2023-02-27 at 9 59 06 AM" src="https://user-images.githubusercontent.com/11756601/221598350-937c82c2-7087-4243-9b32-79d647752a76.png">

**Comment by ricgross** [comment]
Hi @brendankeith,

Thank you for your prompt reply once again. I have modified the inputs as you described, and I managed to obtain the same results as you did. 

However, I have also tried to modify the dimensions of the beam and the point of application of the force, such that the load case resembles the one presented in Figure 5 of the paper "Efficient topology optimization in MATLAB using 88 lines of code" (Andreassen, E., Clausen, A., Schevenels, M., Lazarov, B. S., & Sigmund, O.) . It is a cantilever beam discretized by 80 elements (160 in the paper) along the x-direction and 50 (100 in the paper) along the y-direction. The point force is applied on the lower corner of the free end of the beam. 

The result obtained from your script seems to differ quite largely w.r.t. the one in the paper and I am unsure what the cause might be. 

On a side note, are there any other examples where optimization problems (and their related classes and functions within MFEM) are utilized? There seems to be only one, which is the same where the HiOp implementation is shown.

In advance, thanks.
Best regards,
Riccardo

**Comment by brendankeith** [comment]
@ricgross, I’m glad to read that the code is now running for you. :)

There are several reasons why the results may differ from the MATLAB paper. Please note that this is a non-convex optimization problem, so there is no reason to expect only one unique solution. The solution you converge to will depend on the initial guess as well as the optimization algorithm and it’s parameters. Also, there are subtle differences between the MFEM implementation and the MATLAB one.

@bslazarov is one of the coauthors of the MATLAB paper you are referring to and has also reviewed and approved the MFEM PR you are concerned about.

@bslazarov do you have any advice for @ricgross?

**Comment by ricgross** [comment]
Hi @brendankeith,

Thank you for your help. 

I actually have another small question related to the discretization choices. You decided to use a discontinuous L2 space for the control variable (i.e. the unfiltered density), which is in theory constant within each element. The `TrueVSize` is equal to four times the total number of elements, which makes sense, as the L2 space is linear, and a linear quadrilateral element has 4 nodes.

The question is: would it be possible to define a FE space, whose size is equal to the number of elements?  

One of the reasons why I am asking is because I am planning to re-write the problem as a mass minimization with a stress constraint. The stress constraint is to be formulated as an aggregate function (P-norm), where (usually) one stress value per element (e.g. Von Mises) is used, and it is calculated in the center of the element itself (as it is a superconvergent point for a linear element).

Do you see it as a feasible approach? Or would I need to define a L2 space, calculate the stress in its center and then copy the value to the element nodes?

**Comment by brendankeith** [comment]
Happy to help, @ricgross.

The quick answer to your question is that running with control variable order = 0 is possible. I updated the PR to do this by default when you use the flag `-o 1`.

I also added a new sample run for users interested in running with the lowest order setting you want to use.

Finally, I must emphasize that running at the lowest order setting requires a very fine mesh. Because the discretization is not positivity preserving, you can get in the density field on coarse meshes that make the Young's modulus negative. If this happens, it will cause the code to crash in the conjugate gradient solver. You can fix this problem using a higher-order discretization, refining the mesh, or increasing `rho_min`.
