### ISSUE TITLE
Issue with destructor of BlockOperator

### ISSUE THREAD

**Issue by aschaf** [mfem/mfem#3516]
Hi,

I noticed a small bug in the destructor of BlockOperator at 

https://github.com/mfem/mfem/blob/ea5c4664864cb84c0a453f527d6befec05a8b8a9/linalg/blockoperator.cpp#L133-L145

where it seems that `iRow` and `jCol` have been mixed up. I did not find any mention of it so I opened a new issue.

Best regards,
Andreas

**Comment by v-dobrev** [comment]
Thanks for reporting this, Andreas! I'll add a fix for this directly to #3384.

**Comment by tzanio** [comment]
Addressed in #3384.
