### ISSUE TITLE
How to get global solution from ParGridfunction?

### ISSUE THREAD

**Issue by luowen765** [mfem/mfem#3521]
Firstly thanks to authors for providing the open code MFEM, I use it for the first time to solve a nodal finite element problem. After  solving the ParGridFuntion,  I can not find a rapid way to get global solutions. I need to add a value of analytic function for the global nodal values. Is there a quick way to  manipulate the obtained solutions on Parmesh?

Any response would be appreciated！

**Comment by pazner** [comment]
If you want to add an analytic function to a `ParGridFunction`, you can create a `FunctionCoefficient`, project it onto a second `ParGridFunction`, and then just add them together. There is no need to do anything special in parallel.
