### ISSUE TITLE
Global TDof indexing

### ISSUE THREAD

**Issue by JeremiahDBrown** [mfem/mfem#3528]
We are working on a good way to write out ParGridFunctions to H5 files.  This is meant to allow both the ability to restart a simulation, as well as to store results for post-processing.  This leads to a couple questions:
1. Is the global TDof index dependent on the mpi world size?  In other words, will Global TDof 123 always be 123 whether the simulation is serial or parallel with an arbitrary number of processes?  If it's not constant, I suspect there is no easy way to re-use a given grid function in different world sizes.
2. For a given local process are the global TDof indices corresponding to the local TDofs a contiguous set?  In other words, if a given process has 10 TDofs present, should we expect them to be e.g. 1-10, or could they be 1, 2, 25, 29, 135, etc...?

**Comment by jandrej** [comment]
Any particular reason why the current DataCollection formats are not sufficient for you restart mechanisms? See also https://axom.readthedocs.io/en/develop/axom/sidre/docs/sphinx/mfem_sidre_datacollection.html

**Comment by v-dobrev** [comment]
Note that both `ConduitDataCollection` (requires `MFEM_USE_CONDUIT=YES`) and `SidreDataCollection` (requires `MFEM_USE_SIDRE=YES`, i.e. MFEM build with Axom) support HDF5 I/O with the added benefit that they can be open in VisIt for visualization. This I/O functionality is illustrated in the miniapp `convert-dc.cpp` in `miniapps/tools`.

Regarding your questions:
1. The global true-dof (TDof) enumeration depends on the mesh partitioning, so, in general, it will depend on the number of MPI ranks too. To use a given parallel mesh and grid-function on a different number of processors, one has to re-partition and re-distribute the data -- this is currently not implemented in MFEM, however, we plan to add this capability in the near future.
2. The global TDof id is assigned as a rank-specific offset plus the local TDof id. Basically, rank 0's TDofs are first in the global TDof numbering, then rank 1, etc.
