### ISSUE TITLE
Constructing rigid body modes

### ISSUE THREAD

**Issue by pasquadambra** [mfem/mfem#353]
Dear friends,
is it a simple way to generate the vectors corresponding to the rigid body modes for the linear elasticity examples both in 2d and in 3d. I used the ex2.cpp and ex3.cpp to generate matrices for some testing needs. Could you give me some hints to generate r.g.m.?
Thanks a lot, Pasqua D'Ambra

**Comment by jakubcerveny** [comment]
Hi, not sure if this is what you are looking for, but have you seen the
modal analysis that is done examples 12 and 13?

Jakub

**Comment by pasquadambra** [comment]
Thank you Jakub,
I would like to generate the vectors without using eigensolvers, considering geometrical information.
For example, in the 2d case, we know that r.b.m are 2 costants vectors (related to translation w.r.t. to the axis) and 1 vector of the type (-y,x), so it is related to the grid. I used triangularization and I have access to the vertices of the mesh but I am not sure that these vertices can be used to generate my divergence free vector. Thanks

**Comment by juan42** [comment]
Yes this is simple and done in
https://github.com/mfem/mfem/blob/master/linalg/hypre.cpp#L2512

Those are just the rotations.

**Comment by tzanio** [comment]
Hi Pasqua,

To add to @juan42's answer, here is the simplest serial 2D case:

```c++
static void func_rxy(const Vector &x, Vector &y)
{
   y = 0.0; y(0) = x(1); y(1) = -x(0);
}

VectorFunctionCoefficient coeff_rxy(2, func_rxy);

ParGridFunction rbms_rxy(fespace);

rbms_rxy.ProjectCoefficient(coeff_rxy);
```

Hope this helps,
Tzanio

**Comment by pasquadambra** [comment]
Thanks a lot Julian,

since I am not so expert in C++ and in main data structures and functions of mfem, could you so kind to explain me the meaning of the following lines?

      VectorFunctionCoefficient coeff_rxy(2, func_rxy);

      ParGridFunction rbms_rxy(fespace);

      rbms_rxy.ProjectCoefficient(coeff_rxy);

 

I see that func_rxy initialize y to zero and applies rotation with angle pi/2 in 2d to a 2 components vector, but I am not sure to understand the above 3 lines.

Thanks a lot, Pasqua

 

 

Da: Julian Andrej [mailto:notifications@github.com] 
Inviato: martedì 14 novembre 2017 13:38
A: mfem/mfem
Cc: pasquadambra; Author
Oggetto: Re: [mfem/mfem] rigid body modes (#353)

 

Yes this is simple and done in
https://github.com/mfem/mfem/blob/master/linalg/hypre.cpp#L2512

Those are just the rotations.

**Comment by pasquadambra** [comment]
I ran the command
make serial -j 4
on my iMac, but I had the following error:

ranlib -no_warning_for_no_symbols libmfem.a
ranlib: unknown option character `n' in: -no_warning_for_no_symbols
Usage: ranlib [-sactfqLT] [-] archive [...]
make[1]: *** [libmfem.a] Error 1
make: *** [serial] Error 2

Do you have some hints for avoiding it?
Thanks

**Comment by mlstowell** [comment]
Hello, Pasqua,

The "-no_warning_for_no_symbols" option to ranlib should not be used on a Mac. The file "config/defaults.mk" checks if it's running on a Mac and then defines which options to use.  This choice can be overridden in "config/user.mk".  Is it possible that your defaults.mk or user.mk files have altered this check?  The check is based on the output of "uname -s".  If this command returns "Darwin" then the configuration scripts should recognize the computer as a Mac.   On the other hand, if any other string comes back the check will fail.  We should verify that your computer does indeed return this string.

It would be best if we fix the automatic check for running on a Mac but if all else fails you can simply define "RANLIB = ranlib" in your "config/user.mk" file.

Best wishes,
Mark

**Comment by jakubcerveny** [comment]
Hi Pasqua,

> VectorFunctionCoefficient coeff_rxy(2, func_rxy);

The various coefficient classes in MFEM hold constants or functions to be
used by weak form integrators, or they can be projected to GridFunctions.
This line creates an object of the class VectorFunctionCoefficient. You
need to specify the vector dimension and a function that will be called by
MFEM to obtain the actual values, when needed.

> ParGridFunction rbms_rxy(fespace);

This is a GridFunction on a parallel mesh. A grid function is basically a
vector within the specified FiniteElementSpace ('fespace' here). You can
think of it as a solution vector.

> rbms_rxy.ProjectCoefficient(coeff_rxy);

The GridFunction can hold a solution or you can explicitly project a
function to it. The method ProjectCoefficient will do nodal interpolation
of the supplied coefficient.

Hope that helps,
Jakub

**Comment by v-dobrev** [comment]
Just to add to Mark's answer: you can try building MFEM with the following commands:
```sh
make config
make -j 4 RANLIB=ranlib
```
Also, just to clarify why you get this issue, can you post the results from the following two commands:
```sh
uname -a
g++ -v
```
Thanks!

**Comment by pasquadambra** [comment]
Hi Veselin,

in the following the output of the commands:

uname -a

>Darwin iMac-di-Pasqua-DAmbra.local 12.5.0 Darwin Kernel Version 12.5.0: Sun Sep 29 13:33:47 PDT 2013; root:xnu-2050.48.12~1/RELEASE_X86_64 x86_64

g++ -v

> Using built-in specs.

>Target: i686-apple-darwin11

>Configured with: /private/var/tmp/llvmgcc42/llvmgcc42-2336.11~182/src/configure --disable-checking --enable-werror --prefix=/Applications/Xcode.app/Contents/Developer/usr/llvm-gcc-4.2 >mandir=/share/man --enable-languages=c,objc,c++,obj-c++ --program-prefix=llvm- --program-transform-name=/^[cg][^.-]*$/s/$/-4.2/ --with-slibdir=/usr/lib --build=i686-apple-darwin11 --enable->llvm=/private/var/tmp/llvmgcc42/llvmgcc42-2336.11~182/dst-llvmCore/Developer/usr/local --program-prefix=i686-apple-darwin11- --host=x86_64-apple-darwin11 --target=i686-apple-darwin11 --with->gxx-include-dir=/usr/include/c++/4.2.1

>Thread model: posix

>gcc version 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00)

 

I ran also the command to build the library:

make config
make -j 4 RANLIB=ranlib

 

and I have the library libmfem.a, however I see the following output:

ranlib libmfem.a

ranlib: file: libmfem.a(communication.o) has no symbols

ranlib: file: libmfem.a(hypre.o) has no symbols

ranlib: file: libmfem.a(hypre_parcsr.o) has no symbols

ranlib: file: libmfem.a(petsc.o) has no symbols

ranlib: file: libmfem.a(strumpack.o) has no symbols

ranlib: file: libmfem.a(sundials.o) has no symbols

ranlib: file: libmfem.a(superlu.o) has no symbols

ranlib: file: libmfem.a(mesquite.o) has no symbols

ranlib: file: libmfem.a(pmesh.o) has no symbols

ranlib: file: libmfem.a(pncmesh.o) has no symbols

ranlib: file: libmfem.a(pbilinearform.o) has no symbols

ranlib: file: libmfem.a(pfespace.o) has no symbols

ranlib: file: libmfem.a(pgridfunc.o) has no symbols

ranlib: file: libmfem.a(plinearform.o) has no symbols

ranlib: file: libmfem.a(pnonlinearform.o) has no symbols

ranlib: file: libmfem.a(sidredatacollection.o) has no symbols

 

Thanks a lot, Pasqua 

Da: Veselin Dobrev [mailto:notifications@github.com] 
Inviato: mercoledì 15 novembre 2017 23:14
A: mfem/mfem
Cc: pasquadambra; Author
Oggetto: Re: [mfem/mfem] Constructing rigid body modes (#353)

 

Just to add to Mark's answer: you can try building MFEM with the following commands:

make config
make -j 4 RANLIB=ranlib

Also, just to clarify why you get this issue, can you post the results from the following two commands:

uname -a
g++ -v

Thanks!

**Comment by pasquadambra** [comment]
Thanks Mark,

I put in a previous email the output of the commands related to the environment.

Regards, Pasqua

Da: Mark L. Stowell [mailto:notifications@github.com] 
Inviato: mercoledì 15 novembre 2017 17:52
A: mfem/mfem
Cc: pasquadambra; Author
Oggetto: Re: [mfem/mfem] Constructing rigid body modes (#353)

 

Hello, Pasqua,

The "-no_warning_for_no_symbols" option to ranlib should not be used on a Mac. The file "config/defaults.mk" checks if it's running on a Mac and then defines which options to use. This choice can be overridden in "config/user.mk". Is it possible that your defaults.mk or user.mk files have altered this check? The check is based on the output of "uname -s". If this command returns "Darwin" then the configuration scripts should recognize the computer as a Mac. On the other hand, if any other string comes back the check will fail. We should verify that your computer does indeed return this string.

It would be best if we fix the automatic check for running on a Mac but if all else fails you can simply define "RANLIB = ranlib" in your "config/user.mk" file.

Best wishes,
Mark

**Comment by tzanio** [comment]
Those warnings are OK. Can you try linking one of the examples?

**Comment by pasquadambra** [comment]
Thank you Jakub,

I will try to use these classes in example2 to print the corresponding rotation for the (2d) beam test case. I have to adapt an old version of that example in which I download also matrix and rhs.

I hope to have success.

Regards, Pasqua

Da: Jakub Červený [mailto:notifications@github.com] 
Inviato: mercoledì 15 novembre 2017 20:57
A: mfem/mfem
Cc: pasquadambra; Author
Oggetto: Re: [mfem/mfem] Constructing rigid body modes (#353)

 

Hi Pasqua,

> VectorFunctionCoefficient coeff_rxy(2, func_rxy);

The various coefficient classes in MFEM hold constants or functions to be
used by weak form integrators, or they can be projected to GridFunctions.
This line creates an object of the class VectorFunctionCoefficient. You
need to specify the vector dimension and a function that will be called by
MFEM to obtain the actual values, when needed.

> ParGridFunction rbms_rxy(fespace);

This is a GridFunction on a parallel mesh. A grid function is basically a
vector within the specified FiniteElementSpace ('fespace' here). You can
think of it as a solution vector.

> rbms_rxy.ProjectCoefficient(coeff_rxy);

The GridFunction can hold a solution or you can explicitly project a
function to it. The method ProjectCoefficient will do nodal interpolation
of the supplied coefficient.

Hope that helps,
Jakub

**Comment by pasquadambra** [comment]
Compilation and linking of the examples ran successfully.  I also ran ex2 with beam-tri.mesh and I got results.

Thanks, P.

 

Da: Tzanio Kolev [mailto:notifications@github.com] 
Inviato: giovedì 16 novembre 2017 17:49
A: mfem/mfem
Cc: pasquadambra; Author
Oggetto: Re: [mfem/mfem] Constructing rigid body modes (#353)

 

Those warnings are OK. Can you try linking one of the examples?

**Comment by v-dobrev** [comment]
Judging by the output of `uname -a` and `g++ -v`, it looks like the build issue with `ranlib` was caused by an old version of `ranlib` which does not support the option `-no_warning_for_no_symbols`. You can continue building with the `RANLIB=ranlib` option (ignoring the warning messages), or you can try updating to a newer version of XCode which comes with a newer version of `ranlib`.

**Comment by pasquadambra** [comment]
Dear Jakub,
I modified the mfem code ex2.cpp for my aims. I need to dump matrices and rhs as well as rbm related to rotations.
I put (in the lines from 250 till end) a similar code I found in the hypre.ccp to build and dump rbm vectors, but unfortunately I have some problems in using ParGridFunction and I was not able to compile. On the other hand, I am not sure that it is right to use ParGrdiFunction in a sequential code.
Could you give  a look to my code (here attached) for advising me on the right way to write the code I need?
Sorry for disturb.
I will appreciate a lot if you have time to give me some feedback.
Thanks a lot, Pasqua
-------------------------------------------------
Pasqua D'Ambra, PhD
Senior Research Scientist
National Research Council of Italy (CNR)
Istituto per le Applicazioni del Calcolo (IAC)
Via Pietro Castellino 111, I-80131 Naples, Italy 
voice: +39-081-6139516; fax: +39-081-6139531
e-mail: pasqua.dambra@cnr.it
URL: dambra.na.iac.cnr.it

Il giorno 15/nov/2017, alle ore 20:57, Jakub Červený <notifications@github.com> ha scritto:

**Comment by jakubcerveny** [comment]
Pasqua, I don't see any attachments. Please send the code to jakub.cerveny@gmail.com, I will try to take a look. Do I understand it correctly that you need to generate the r.b.m. in serial and just dump the vectors to files? 

Jakub

**Comment by jakubcerveny** [comment]
Resolved. Parallel classes cannot be used in serial. We downgraded the RBM projection code to serial classes.

**Comment by pasquadambra** [comment]
Ok! Thanks

Inviato da iPhone
