### ISSUE TITLE
Results from serial and parallel calculation are too different.

### ISSUE THREAD

**Issue by sungho91** [mfem/mfem#3534]
Hello everyone,

I am currently working on testing the implementation of body force using an 8-m tall column structure (refer to Figure 1 or 2).
The bottom surface is fixed and the side walls can only move in the vertical direction. The top surface is free of constraints. I used 10 m/sec2 of gravitational acceleration and 2800 kg/m3 of density. To get static deformation, I applied damping from total force as much as -1* 0.8 * sign (velocity_i) * abs(force _i).

After some time, the static solution exhibits smooth displacement, density, and stress (refer to Figure 1). Additionally, I have verified that all solutions agree well with the analytical solution.

However, a problem has arisen during parallel calculations (with 2 cores). Specifically, a strange discontinuity appears in the middle of the domain (refer to Figure 2). The middle discontinuity corresponds to the interface determined by Metis.

Have any of you faced this problem before, or do you have any ideas? Please leave any comments on this post.

Thank you very much.

Best regards,
Sungho

![serial_result](https://user-images.githubusercontent.com/40257026/224824315-6a66f0eb-f0e0-4e43-bb29-eb770bed422f.png)
**Figure 1.** Results from the serial calculation (the number for cores = 1). (left panel) displacement, (middle panel) density, (right panel) vertical stress.

![parallel_result](https://user-images.githubusercontent.com/40257026/224824556-c8391f41-5a4f-42b5-8e10-23303cbf3bf3.png)
**Figure 2.** Results from the parallel calculation (the number for cores = 2). (left panel) displacement, (middle panel) density, (right panel) vertical stress.

**Comment by vladotomov** [comment]
Of course we've faced it a million times. A good approach to find parallel bugs is to isolate the inconsistency to a small problem and reproduce it on 2 tasks (as you have done, but you can probably go even smaller). Then you can print some numbers and see which elements get wrong contributions in parallel, etc.

**Comment by sungho91** [comment]
Thank you for your comment. I'm playing with 2 elements now. I have no idea where the bug happens. 
Do you have any further comments?

**Comment by sungho91** [comment]
Thank you @vladotomov! I think my problem arises from shared nodes resulting from parallel calculations. I added source terms equal to the number of degrees of freedom. In parallel mode, I believe the source term is being used twice. Therefore, I attempted to reduce the number of source terms by half for shared nodes. Do you have any suggestions on how to identify the shared nodes between processors?

**Comment by vladotomov** [comment]
If you want to add a source vector to the vector of DOFs, you should do this operation on the true-dof level. The true-dofs are unique (not duplicated). If this is not clear, see https://mfem.org/pri-dual-vec/#true-degree-of-freedom-vectors.

**Comment by sungho91** [comment]
Thank you @vladotomov 
I have identified the problem that was causing issues in my calculations. I was attempting to obtain the static deformation responsible for the body force using dynamic calculations. In order to do this, I applied damping to dampen out the dynamic stress. I calculated the magnitude of the total force and took the opposite sign of the velocity. As you can see, the results from the serial calculation were great, but a problem occurred in parallel mode.

To investigate, I turned off the damping and conducted another simulation in both serial and parallel modes. The solutions were identical. Based on these observations, I concluded that my problem arises from shared nodes associated with damping algolithm resulting from parallel calculations.

I checked the force vector at the interface node in serial mode and at shared nodes in parallel mode, respectively. I found that the amount of force checked in serial was partitioned into shared nodes in the parallel mode. The problem occurs when the force has a different sign at shared nodes, even if their sum is the same as the magnitude of the serial one.

If I apply damping in this situation, the situation becomes abs(a) + abs(b) ≠ abs(a+b). This means that one node can be amplified while another can be damped.

Therefore, I am looking for ways to synchronize the values of each shared node. Do you have any suggestions?

**Comment by vladotomov** [comment]
@sungho91
The force being partitioned sounds correct, but at what point of the calculation do you take absolute values? Do you do it on each task and then add them? I don't understand why this operation is needed.

**Comment by sungho91** [comment]
@vladotomov 

Regarding my observation about the sum of partitioned forces at different MPI tasks being the same as the value of the serial one, this must be the principle of conservation of forces. In an isolated system, the total amount of force remains constant, so the sum of forces acting on each partitioned section must be equal to the force acting on the system as a whole.

Regarding the different signs at share nodes, I don't exactly know it. it just seems like forces at share nodes may cancel each other out, resulting in the same direction as serial one.

If forces are not partitioned at share nodes but shared, this problem might be resolved but I don't know how to control that. I take the damping equation from FLAC (Fast Lagrangian Analysis of Continua), but  I have to think about another damping algorithm applicable to MPI.

**Comment by sungho91** [comment]
@vladotomov 

I can say damping vector is computed at each DOF of H1 space. I am working on implementing solid mechanics into Laghos, which is a miniapp of MFEM, in order to develop a geodynamic solver. Like Laghos, my modified code assembles an external force vector after numerical integration, which is stored in the RHS vector. Then, I add the assembled body force vector to the RHS vector to obtain the total force vector. Before solving the linear system, I calculate the damping portion using the total force vector and the previous velocity vector from its grid function.

**Comment by vladotomov** [comment]
@sungho91 

Good, I happen to have some familiarity with `Laghos`. Looking at `SolveVelocity`, try to compute the damping portion using the vector `B` instead of `rhs`. The `B` vector is on the true DOFs, i.e., it has your RHS vector without MPI duplication. It is structured similarly to `rhs` - first it has all `x` components, then all `y` components, etc. But it has different size. Then you add the damping to `B`, before the `cg.Mult(B, X)` call.

You can compare the `B` vector with your serial RHS, they should have the same entries.

**Comment by sungho91** [comment]
@vladotomov 

This suggestion is very helpful. I will try using the **B** vector instead of the **rhs** vector. However, to dampen the total force out, I need to use the opposite sign of the current or previous velocity. Since grid function is different size with true degrees of freedom (DOFs), is there a way to obtain the true DOFs of velocity?

**Comment by sungho91** [comment]
@vladotomov 

Thank you so much. I resolved the problem. I got true DOFs from gridfunction using SetTrueVector() and GetTrueVector().
Also, I checked the results from serial and parallel calculation are identical.
