### ISSUE TITLE
Calculating all stress components ex2p

### ISSUE THREAD

**Issue by shani9383** [mfem/mfem#3535]
Hi, 
Sorry if it’s a stupid question but I want to use the code written in “https://github.com/mfem/mfem/issues/10#issue-87510033" to receive the stress and strain components solutions (in addition to the displacement field). I’m using the parallel version, ex2p. In issue-87510033 'MyCoefficient' returns only one component of the stress (sigma_xx). How should I modify the code if I want the output off all six sigma and all six eps components? I would appreciate your help.
Shani
I tried the following but it looks like Eval does not return a vector:
class MyCoefficient : public Coefficient
{
private:
   GridFunction &u;
   Coefficient &lambda, &mu;
   DenseMatrix eps, sigma;

public:
   MyCoefficient(GridFunction &_u, Coefficient &_lambda, Coefficient &_mu)
      : u(_u), lambda(_lambda), mu(_mu) { }
   virtual void Eval(ElementTransformation &T, const IntegrationPoint &ip, Vector &s)
   {
      u.GetVectorGradient(T, eps);  // eps = grad(u)
      eps.Symmetrize();             // eps = (1/2)*(grad(u) + grad(u)^t)
      double l = lambda.Eval(T, ip);
      double m = mu.Eval(T, ip);
      sigma.Diag(l*eps.Trace(), eps.Size()); // sigma = lambda*trace(eps)*I
      sigma.Add(2*m, eps);          // sigma += 2*mu*eps

      // Store the components of the stress tensor sigma in the output vector v
      s(0) = sigma(0,0); // sigma_xx
      s(1) = sigma(1,1); // sigma_yy
      s(2) = sigma(2,2); // sigma_zz
      s(3) = sigma(0,1); // sigma_xy
      s(4) = sigma(0,2); // sigma_xz
      s(5) = sigma(1,2); // sigma_yz
   }
   virtual void Read(istream &in) { }
   virtual ~MyCoefficient() { }
};

**Comment by vladotomov** [comment]
You should probably use `VectorCoefficient` instead of `Coefficient`.
