### ISSUE TITLE
How to assemble lumped mass matrix?

### ISSUE THREAD

**Issue by YHD17** [mfem/mfem#3537]
Hi, 

may I sincerely ask,  how to assemble lumped mass matrix in mfem? 

For the full mass matrix: 

 mVarf->AddDomainIntegrator(new MassIntegrator(one));

 mVarf->FormSystemMatrix(u_ess_tdof_list, A);

Is there any similar function in MFEM like LumpedMassIntegrator 
that put all off-diagonal entries on the diagonal ?

Thank you in advance

**Comment by vladotomov** [comment]
@YHD17 you can try
`AddDomainIntegrator(new LumpedIntegrator(new MassIntegrator));`

**Comment by YHD17** [comment]
Thanks a lot.  It works now !
