### ISSUE TITLE
Get error when objects detroy.

### ISSUE THREAD

**Issue by changlichun** [mfem/mfem#3547]
Dear all
I am new to MFEM, and I am trying to get familier with the code. I got confused while running the following code.  It seem that the code got error when objects detroyed. But it is weird that the code passed when `IntRules` order = 1 or 5, but failed when order = 3 

Could anyone give me some clues?

```

#include "mfem.hpp"
#include <memory>
#include <iostream>
#include <fstream>

using namespace std;
using namespace mfem;

int main(int argc, char *argv[])
{
    Mpi::Init(argc, argv);

    int num_procs = Mpi::WorldSize();
    int myid = Mpi::WorldRank();

    Hypre::Init();

    
    const char *mesh_file = "../data/beam-quad.mesh";
    int order = 1;
    Mesh *mesh = new Mesh(mesh_file, 1, 1);
    int dim = mesh->SpaceDimension();
                        
    mesh->EnsureNodes();
    ParMesh pmesh(MPI_COMM_WORLD, *mesh);
    mesh->Clear();

    H1_FECollection fe_coll(order, dim);
    ParFiniteElementSpace fespace(&pmesh, &fe_coll, dim);
    
    
    IntegrationRule *ir_ = nullptr;
    ir_ = const_cast<IntegrationRule *>(
        &IntRules.Get(mfem::Element::HEXAHEDRON,  3 ));//The code passed when order = 1 or 5, but failed when order = 3 

                    
    const GeometricFactors *geometric_factors_ = pmesh.GetGeometricFactors(*ir_, GeometricFactors::JACOBIANS | GeometricFactors::DETERMINANTS);
                    
    return 0;
}

```

**Comment by v-dobrev** [comment]
One problem I see is that you are not deleting the `mesh` -- you can replace `mesh->Clear();` with `delete mesh;`.

Another issue is that the first argument of `IntRules.Get` should be `mfem::Geometry::Type` and not `mfem::Element::Type` -- even though currently both `mfem::Element::HEXAHEDRON` and `mfem::Geometry::CUBE` have the value `5`.

The main issue, however, seems to be that the code snippet is using `IntegrationRule` for the `CUBE` with a mesh that uses quad elements -- `../data/beam-quad.mesh`. To make this work with any mesh that uses a single type of elements, you can use `mesh->GetElementGeometry(0)` as the first argument in `IntRules.Get`.

Another minor point is that there is no need to use `const_cast` -- it is better to just declare `ir_` as `const IntegrationRule *ir_ = nullptr;`. This way you can still change the pointer `ir_` but the object that it points to is `const` and cannot be changed.

**Comment by changlichun** [comment]
Thank you very much for your comments!
I can understand that the error may be caused by a mismatch between the `mesh` and the `IntRules` type. But I am still curious:
1. could I use `CUBE` type `IntRules` in a 3-D 'SQUARE` mesh?
2. could I define `IntRules` with different orders in different directions, for example 2\*2\*3, 12 `IntegrationPoint` in total?

**Comment by v-dobrev** [comment]
> 1. could I use `CUBE` type `IntRules` in a 3-D 'SQUARE` mesh?

Yes, if by "3-D SQUARE mesh" you mean a 3D mesh consisting of hex elements. Or do you mean 2D quad mesh embedded in 3D, i.e. a surface mesh?

> 2. could I define `IntRules` with different orders in different directions, for example 2\*2\*3, 12 `IntegrationPoint` in total?

Yes, you can create `IntegrationRule` objects with such anisotropic orders, for example using the following constructor: https://github.com/mfem/mfem/blob/701870a7daea3f846613feb296b2f71a6afd007e/fem/intrules.hpp#L235-L237
The container object `IntRules`, however, does not currently support such anisotropic `IntegrationRule` objects.

**Comment by changlichun** [comment]
Thank you very much for your suggestions, they have been very useful to me.
