### ISSUE TITLE
inverse matrix multiplication with a vector

### ISSUE THREAD

**Issue by YHuiDong** [mfem/mfem#3549]
Hi, 

is there an operator like:

M->invMult(x,b)

for a lumped mass matrix M in mfem?

**Comment by v-dobrev** [comment]
If `M` is a `SparseMatrix` you can use this: https://github.com/mfem/mfem/blob/701870a7daea3f846613feb296b2f71a6afd007e/linalg/sparsemat.hpp#L529-L531

**Comment by YHDAUT** [comment]
Thank you Dobrev,

unfortunately,  I have a matrix type:

 HypreParMatrix

class mfem::HypreParMatrix’ has no member named ‘DiagScale'

Does  HypreParMatrix have something similar to DiagScale ?

Thanks a lot.

**Comment by v-dobrev** [comment]
For `HypreParMatrix` you can use the `HypreSmoother` class, e.g. like this:
```c++
void test(const HypreParMatrix &M, const Vector &x, Vector &y)
{
   HypreSmoother D_inv(M, HypreSmoother::Jacobi);
   D_inv.Mult(x, y);
}
```

**Comment by YHDAUT** [comment]
Thank you Dobrev.   

If I understand it correctly, by setting type=HypreSmoother::Jacobi  in HypreSmoother constructor,  does it mean the rest of parameters in constructor will not play a role  for Jacobi case?

double omega = 1.0, 
int poly_order = 2,
double poly_fraction = .3, 
int eig_est_cg_iter = 10

Thank you in advance.

**Comment by v-dobrev** [comment]
> If I understand it correctly, by setting type=HypreSmoother::Jacobi in HypreSmoother constructor, does it mean the rest of parameters in constructor will not play a role for Jacobi case?

Yes, I think that's correct: for `type=HypreSmoother::Jacobi`  as long as you set `relax_times = 1` and `relax_weight = 1.0` you should get pure Jacobi smoother which is what you want.
