### ISSUE TITLE
Possible bug in Sparse Matrix creation

### ISSUE THREAD

**Issue by vikramsg** [mfem/mfem#355]
I came across this while trying to figure out why 3D was so much slower than 2D for me. It seems to me that when you do AddSubMatrix in SparseMatrix, the logic searches for 0 using a == 0.0. Now this makes sense when we are using integers but when using double it does not work. So I observed that there were far too many entries being put into the matrix which were E-18, E-19. They should really have been 0. So I changed the condition to 

```
if (skip_zeros && (a == 0.0 || (std::abs(a) <  std::numeric_limits<double>::epsilon()) ))
{
       if (&rows != &cols || (subm(j, i) == 0.0 || (std::abs(subm(j, i)) <  std::numeric_limits<double>::epsilon()) ))
        {
               continue;
        }
}
```

and it is indeed much faster. Is there a reason for not doing this?

**Comment by tzanio** [comment]
Hi @vikramsg,

Matrices can be scaled in weird ways, so I'm not sure if such a check is a good idea in general. If you want to filter small entries, you can use `DenseMatrix::Threshold` on the element matrices, or `HypreParMatrix::Threshold` in parallel.

Cheers,
Tzanio

**Comment by v-dobrev** [comment]
I think a more flexible solution will be to add a data field, e.g. `double zero_threshold` to class `SparseMatrix` and use that in methods that check for zeroes. The default should be `zero_threshold = 0.0` and the comparison should use `<=`, that way the current behavior will be preserved.

**Comment by vikramsg** [comment]
I didn't know about ```HypreParMatrix::Threshold``` but I think @v-dobrev solution should work better.

**Comment by tzanio** [comment]
I'm closing this issue. We will be interested in a PR following @v-dobrev's suggestion if you'd like to propose one.
