### ISSUE TITLE
Can I use single precision float?

### ISSUE THREAD

**Issue by changlichun** [mfem/mfem#3554]
Can I use single precision floating point numbers to speed up my calculations and save memory? I found that many data types like `Vector`, `SparseMatrix`, `DenseMatrix` all use `Memory<double>` type.

**Comment by v-dobrev** [comment]
No, at the moment MFEM supports only double precision.

**Comment by changlichun** [comment]
So, are there any plans to add single-precision support?

**Comment by v-dobrev** [comment]
There are no concrete plans at the moment, as far as I know.

**Comment by tzanio** [comment]
To add to @v-dobrev's answer -- there are external libraries that MFEM is integrated with, like Gingkom that could use lower precision, but there is no immediate plans to add single precision support to the MFEM internals.
