### ISSUE TITLE
MUMPS with mfem, error can not find scalapack

### ISSUE THREAD

**Issue by sp3c333** [mfem/mfem#3558]
Hello,

I have installed mumps5.5.1.11 on windows through "Intel oneAPI command prompt for Intel 64 for Visual Studio" as required. It uses "mkl_scalapack_ilp64" that is situated at : C:\Program Files (x86)\Intel\oneAPI\mkl\2023.0.0\lib\intel64
I have this error when I try to do MFEM_USE_MUMPS=yes in CMAKE GUI (generator is "Visual Studio 17 2022") :

(optional) USER_CONFIG = C:/Users/XXXX/MFEM_Windows/mfem-4.5-new/mfem-4.5/config/user.cmake
Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.22000.
USE_XSDK_DEFAULTS = 'OFF'
Looking for MUMPS ...
   in MUMPS_DIR = C:/Users/XXXX/MFEM_Windows/mfem-4.5-new/mumps-5.5.1.11/buildP
MUMPS: mumps_common: C:/Users/XXXX/MFEM_Windows/mfem-4.5-new/mumps-5.5.1.11/buildP/mumps_common.lib
MUMPS: pord: C:/Users/XXXX/MFEM_Windows/mfem-4.5-new/mumps-5.5.1.11/buildP/pord.lib
MUMPS: looking for required package: MPI
MUMPS: looking for required package: BLAS
MUMPS: looking for required package: METIS
MUMPS: looking for required package: ScaLAPACK
Could NOT find ScaLAPACK (missing: ScaLAPACK_DIR)
Could NOT find scalapack (missing: scalapack_DIR)
CMake Error at config/cmake/modules/MfemCmakeUtilities.cmake:459 (message):
   --------- INTERNAL ERROR
Call Stack (most recent call first):
  config/cmake/modules/FindMUMPS.cmake:18 (mfem_find_package)
  CMakeLists.txt:316 (find_package)
Configuring incomplete, errors occurred!
See also "C:/Users/XXXX/MFEM_Windows/mfem-4.5-new/mfem-4.5/buildP/CMakeFiles/CMakeOutput.log".
See also "C:/Users/XXXX/MFEM_Windows/mfem-4.5-new/mfem-4.5/buildP/CMakeFiles/CMakeError.log".

I have tried to give the parth to the lib directory but without success.
After looking at the file : "C:\Users\XXXX\MFEM_Windows\mfem-4.5-new\mfem-4.5\config\defaults.mk" where scalapack is searched, I tryied to replace (without success) with : 

#SCALAPACK_DIR = @MFEM_DIR@/../scalapack-2.0.2
#SCALAPACK_OPT = -I$(SCALAPACK_DIR)/SRC
#SCALAPACK_LIB = -L$(SCALAPACK_DIR)/lib -lscalapack $(LAPACK_LIB)
SCALAPACK_DIR = "C:/Program Files (x86)/Intel/oneAPI/mkl/2023.0.0"
SCALAPACK_OPT = -I$(SCALAPACK_DIR)/include
SCALAPACK_LIB = -L$(SCALAPACK_DIR)/lib/intel64 -lmkl_scalapack_ilp64 $(LAPACK_LIB)

Could you please help me to use mumps in mfem on windows ? If you need other informations, just ask :) 

(PS: is it possible to use mumps serial in mfem or will it be possible ?)

**Comment by v-dobrev** [comment]
The file `config/defaults.mk` is used by the GNU make build system. The CMake build system uses the file `config/defaults.cmake`. You can either edit that file directly or you can copy `config/defaults.cmake` to `config/user.cmake` and then edit the latter.

I suspect MKL's ScaLAPACK does not provide `scalapack-config.cmake` file (as does netlib's scalapack), so you'll probably need to set the following variables:
```cmake
set(ScaLAPACK_FOUND TRUE CACHE)
set(ScaLAPACK_INCLUDE_DIRS "C:/Program Files (x86)/Intel/oneAPI/mkl/2023.0.0/include" CACHE)
set(ScaLAPACK_LIBRARIES "C:/Program Files (x86)/Intel/oneAPI/mkl/2023.0.0/lib/intel64/mkl_scalapack_ilp64.lib" CACHE)
```

> (PS: is it possible to use mumps serial in mfem or will it be possible ?)

Currently, you need to build MFEM with MPI to be able to use MUMPS.

**Comment by sp3c333** [comment]
Thank you very much for your quick response.

I tried what you proposed but I had to do a small modification in order to make it work, here is what I had to write in default.cmake: 
#set(ScaLAPACK_DIR "${MFEM_DIR}/../scalapack-2.0.2/lib/cmake/scalapack-2.0.2"
#    CACHE PATH "Path to the configuration file scalapack-config.cmake")
#set(ScaLAPACK_TARGET_NAMES scalapack)

set(ScaLAPACK_FOUND TRUE CACHE BOOL "")
set(ScaLAPACK_INCLUDE_DIRS "C:/Program Files (x86)/Intel/oneAPI/mkl/2023.0.0/include" CACHE PATH "")
set(ScaLAPACK_LIBRARIES "C:/Program Files (x86)/Intel/oneAPI/mkl/2023.0.0/lib/intel64/mkl_scalapack_ilp64.lib" CACHE PATH "")

Then I had a small problem at the execution : libircmt.lib missing when using mfem -> set the library path in visual studio : Project Properties -> Configuration Properties -> Linker -> General -> Additional Library Directories and add the path C:\Program Files (x86)\Intel\oneAPI\compiler\2023.0.0\windows\compiler\lib\intel64_win

Now I can use mumps in parallel.

However I still have a strange error occuring when I try to solve problems with more unknows (example 25p with inline-hex.mesh with 40 points in each directions). It seems that I "run out of memory". I also have this problem with UMFPACK in serial for similar condition (I solve problems with complex numbers or matrices I dont know if it could be related). 

Could you help me please?

**Comment by v-dobrev** [comment]
The example should print the number of unknowns, the line looks like this:
```console
Number of finite element unknowns: 2112
```
How many unknowns do you have when the solver crashes?

**Comment by v-dobrev** [comment]
When using `UMFPackSolver` you can try setting the option `use_long_ints_` to `true` (default is `false`). This will allow you to solve bigger systems. It may be possible to do something similar with MUMPS but I don't think we support this in MFEM at the moment.

Note that the amount of needed memory does not depend just on the size of system (the number of unknowns) but also on the number of non-zeros in the sparse matrix, as well as how these non-zeros are connected. For example, smaller system from a 3D PDE (compared to a system from a 2D PDE) can require more memory because its sparse matrix has more non-zeros and produces more fill-in during the solution process.

**Comment by v-dobrev** [comment]
Just to clarify, `use_long_ints_` is an option in the constructors of class `UMFPackSolver`.

**Comment by sp3c333** [comment]
Hello,

Thank you foryour response.

If I want to use UMFPACK. 
And if I use : "assemble()" then I get the error message : 
Verification failed: (mat->real().NumNonZeroElems() == mat->imag().NumNonZeroElems()) is false:
 --> Real and imag Sparsity pattern mismatch: Try setting Assemble (skip_zeros = 0)
 ... in function: void __cdecl mfem::ComplexUMFPackSolver::SetOperator(const class mfem::Operator &)
 ... in file: C:\Users\XXXX\MFEM_Windows\mfem-4.5-new\mfem-4.5\linalg\complex_operator.cpp:295

If I use "assemble(0)" and use_long_ints_ then the computation works but it takes 3h to solve a simple wave equation in the void considering the mesh "inline-hex" with 40 points in each directions which makes this option un-usable.


Mumps on the contrary gives better performance on my laptop.

**Comment by v-dobrev** [comment]
There is a PR in review that adds support for 64-bit indices in the MUMPS solver wrapper in MFEM -- PR #3082.

If you want, give it a try, and post there if you encounter any issues.
