### ISSUE TITLE
SuperLUSolver solve complex matrices use function 'pdgssvx' instead of 'pzgssvx', dose it will affect efficiency?

### ISSUE THREAD

**Issue by zhuyidong-YP** [mfem/mfem#3560]
Does the size of the assembled matrix affect LU factorization efficiency?

![屏幕截图 2023-03-27 140337](https://user-images.githubusercontent.com/27136662/227898045-d425778f-4104-42f3-a46e-a37c98d865a9.png)

**Comment by v-dobrev** [comment]
I think constructing the 2x2 block real form of the complex system takes roughly 2x more memory and I suspect it reduces the overall speed of the factorization and the solve, when compared to using the complex-valued solve.

I suspect it may not be too hard to actually assemble the complex-valued system and use that instead -- one has to merge the sparsity patterns of the real and imaginary parts and create the appropriate complex-valued SuperLU_DIST matrix structure.

**Comment by zhuyidong-YP** [comment]
> I think constructing the 2x2 block real form of the complex system takes roughly 2x more memory and I suspect it reduces the overall speed of the factorization and the solve, when compared to using the complex-valued solve.
> 
> I suspect it may not be too hard to actually assemble the complex-valued system and use that instead -- one has to merge the sparsity patterns of the real and imaginary parts and create the appropriate complex-valued SuperLU_DIST matrix structure.

Thanks for your suggestion，
I will actually assemble the complex-valued system to statistical time consuming.
I'm not familiar with factoring，so come here to ask and learn.

Thanks ！！
