### ISSUE TITLE
from mfem::vector to HypreParVector

### ISSUE THREAD

**Issue by YHuiDong** [mfem/mfem#3561]
Hi, 

may I ask is there anyway to transfer from  mfem::vector  to HypreParVector?

thanks a lot !

**Comment by mlstowell** [comment]
Hi, @YHDAUT,

The short answer is "yes, of course". A `HypreParVector` is an `mfem::Vector` so  if they have compatible lengths data can be easily copied between them or they can be added, subtracted, etc..  However, I suspect you have a more complicated transfer in mind.

If you can give us more details we can probably give you a more helpful answer.  

Best wishes,
Mark

**Comment by YHDAUT** [comment]
Hi, @mlstowell 

my question is actually from example5.cpp, where I got 

trueRhs.GetBlock(1),  a mfem::Vector type, 

now I want to change this to HypreParVector type for  a solver with HypreParMatrix and HypreParVector as input argument. 

Most likely,  I just need to copy from mfem::Vector to HypreParVector.  Is there easy way to make such a copy?

thanks a lot.

**Comment by mlstowell** [comment]
Hi, @YHDAUT,

The easiest thing may be to start from `ex5p.cpp` rather than `ex5.cpp`. The reason for this is that the HYPRE solvers all require MPI. They can be run in serial but, for the HYPRE wrappers in MFEM, this means using MPI on a single processor. If you're willing to go that route it should be fairly easy to create a HypreParVector from the other parallel objects available in that example.

If you prefer to work from the serial example for some reason you'll need to do something like this:
```
Vector &p_vec = trueRhs.GetBlock(1);

/// Setup necessary MPI objects
Mpi::Init(argc, argv);
HYPRE_BigInt col[2];
col[0] = 0; col[1] = p_vec.Size();

/// To copy the data to a newly allocated HypreParVector
HypreParVector p_copy(MPI_COMM_WORLD, p_vec.Size(), col);
p_copy = p_vec;

/// or share the data pointer from the existing mfem::Vector
HypreParVector p_share(MPI_COMM_WORLD, p_vec.Size(), p_vec.GetData(), col);
``` 

Best wishes,
Mark

**Comment by YHDAUT** [comment]
Hi Mark @mlstowell 

thanks a lot for your kind help.  It is my mistake that I actually work on ex5p.cpp, the parallel version, not the series version. 

In this case, I would like to transfer from  trueRhs.GetBlock(1) and trueX.GetBlock(1) to HypreParVector types in order to provide them as arguments for the Hypre solvers.

May I ask sincerely,  is it correct to make this by sharing the data pointer:

Vector &p_vec = trueRhs.GetBlock(1);
HYPRE_BigInt col[2];
col[0] = 0; col[1] = p_vec.Size();
HypreParVector p_share(MPI_COMM_WORLD, p_vec.Size(), p_vec.GetData(), col);

as you specified above?

Thank you in advance and best wishes

**Comment by YHDAUT** [comment]
Hi Mark @mlstowell ,

is it also possible to transfer from HypreParVector to mfem::vector after applying the solving the system using Hypre, like
trueRhs.GetBlock(1)=p_share ??

Thanks a lot in advance.

**Comment by mlstowell** [comment]
Hi, @YHDAUT,

If you're working in parallel (and I'm glad to learn that you are) then a little more care should be taken with the `col` array. There are two possible formats for this array but on a single processor these formats happen to match. This can be done in your code or you can let MFEM do the hard work for you.

Our Hypre solvers will accept `mfem::Vector` arguments and wrap them in `HypreParVector` objects before passing them to Hypre. I would suggest using this feature if you can. If not you can reproduce the code, or a portion of it, which accomplishes this wrapping. Have a look at [this](https://github.com/mfem/mfem/blob/92bf531fab08deff5d6ba687e26bc276a33e1650/linalg/hypre.cpp#L3829-L3878) to see how this is done.

If you are able to share data pointers there may be no reason to copy the result vector but something like ``trueRhs.GetBlock(1)=p_share`` should work (although you probably don't want to overwrite the RHS vector with a solution vector but perhaps you do...).

Best wishes,
Mark

**Comment by YHDAUT** [comment]
Hi, @mlstowell ,

thanks a lot for details.  This helps a lot, will report the test results as soon as possible. 

Best wishes

**Comment by YHuiDong** [comment]
Hi,  @mlstowell , 

Unfortunately,   it seems not to work well for more than one cpus:

  First,  I declare HypreParMatrix:

  OperatorHandle A, B, C;

  ......

   Array2D<HypreParMatrix*> blocks(2,2);
   blocks(0,0) = A.As<HypreParMatrix>();
   blocks(1,0) = B.As<HypreParMatrix>();
   blocks(0,1) = Bt.As<HypreParMatrix>();
   blocks(1,1) = C.As<HypreParMatrix>();

  Second,  I transfer the vector on the right hand side  to   HypreParVector: 
 
  Vector &p_vec = trueRhs.GetBlock(1);
   HYPRE_BigInt col[2];
   col[0] = 0; col[1] = p_vec.Size();
   HypreParVector trueRhs_g(MPI_COMM_WORLD, p_vec.Size(), p_vec.GetData(), col);

   Vector &x_vec = trueX.GetBlock(1);
   HYPRE_BigInt colx[2];
   colx[0] = 0; colx[1] = x_vec.Size();
   HypreParVector truex_g(MPI_COMM_WORLD, x_vec.Size(), x_vec.GetData(), colx);
   
  Then,  I call  a pcg schur complement solver with preconditioned given as blocks(1,1) :

 schur_pcg(blocks(0,0), 
                   blocks(1,0), 
                   blocks(1,1), 
                   blocks(1,1),
                  &trueRhs_g,
                  &truex_g);

that has HypreParMatrix and HypreParVector as input arguments..

In fact, in my schur_pcg implementation,  I have only used MultTranspose, Mult of matrix-vector multiplications in parallel, and some operations with HypreParVectors.. 

I properly made some errors in the parallel implementations...

Thanks and best wishes..

**Comment by mlstowell** [comment]
Hi, @YHuiDong,

Yes, the code snippet I posted to create these `HypreParVector` objects will only work in serial. In parallel you need to implement something closer to the code in the link I posted. Something like:
```
HypreParVector trueRhs_g(blocks(1,1)->GetComm(), blocks(1,1)->GetGlobalNumRows(),
                             p_vec.GetData(), blocks(1,1)->GetRowStarts());
HypreParVector truex_g(blocks(1,1)->GetComm(), blocks(1,1)->GetGlobalNumCols(),
                             x_vec.GetData(), blocks(1,1)->GetColStarts());
```  

If you plan to use GPU things get more complicated but the link I send before shows the details.

Best wishes,
Mark

**Comment by YHuiDong** [comment]
Hi, 

thanks a lot for your kind support.  It is still not working for more than one cpus.  I will need more time to look to the given example . 

One error  might come from the Schur Complement   S=BA^{-1}B^T.  Since all the matrices and vectors are now in a distributed version:

 I make a matrix-vector multiplication Sv=BA^{-1}B^Tv by the following steps in the SchurComplement PCG Solver:

      B->MultTranspose(v, v1, 1.0, 0.0);
      HypreSmoother A_inv(*A, HypreSmoother::Jacobi);
      A_inv.Mult(v1, r1);
      B->Mult(r1, r2);

This seems to be wrong. 

After each multiplication, I properly need to make an accumulation for the resulting vectors, then it will make sense to multiple the accumulated vector with the distributed matrix.   This might be the reason for more than one cpu,  it fails...

There is something concerning SchurComplement in ex19p.cpp, which might help a bit..

It seems there is no direct Schur Complement PCG Solver implemented in MFEM with a prescribed precondtioner.

Thank you very much.
Best wishes

**Comment by mlstowell** [comment]
Hi, @YHuiDong,

The accumulation is done as part of the `Mult` operation within Hypre so nothing more should be necessary. If I recall correctly PCG requires inner products. If you are using `u * v` where `u` and `v` are `HypreParVector` objects this may be a problem. I believe such an operation would compute the inner products separately on each processor using only the local portion of the vectors. I don't think MFEM will identify this as an error. If this is the problem try using `InnerProduct(u, v)` instead.

Best wishes,
Mark

**Comment by YHuiDong** [comment]
Hi, @mlstowell ,

thanks a lot.  This is really a great point.  I have used u*v for the inner product.  After switch to InnerProduct(u,v),  it produces almost the same results on both one and more than one cpus.  Although there are still some other issues to be fixed in the code,  but I am more than happy that, at least this issue is solved. 

Best wishes and thanks.

**Comment by mlstowell** [comment]
That's great news! I'm glad I could help.

**Comment by YHuiDong** [comment]
Hi, @mlstowell ,

finally, I find a mistake in my code, that instead of C in the block matrix, I assembled -C  which causes strange errors in the results.  Now, it works well. 

Thanks.
