### ISSUE TITLE
Use hypre LOBPCG to solve eigenvalue problem in shift-invert mode?

### ISSUE THREAD

**Issue by sampotter** [mfem/mfem#3565]
Hopefully fairly straightforward question. I'm new to MFEM so a bit lost as to where to start.

I'd like to adapt ex11p to solve the same eigenvalue problem but in shift-invert mode. Specifically, my intended outcome is to recover eigenpairs clustered around some shift mu in increasing order of |lam - mu|.

Alternatively, if there's some way to compute all eigenpairs with lam in a given interval [lam0, lam1], for instance using SLEPc or EVSL, that would also be great, but I'll settle for the first option if it's simple. For the latter, I'd probably need some example code to get started. :-)

**Comment by tzanio** [comment]
@mlstowell, can you help @sampotter?

**Comment by mlstowell** [comment]
Hi, @sampotter,

Sorry for the delay. Unfortunately the implementation of LOBPCG that we use is only capable of computing the eigenvalues with lowest real part i.e. the left end of the spectrum. To implement the shift-invert scheme or an interval scheme the largest magnitude eigenvalues are needed.

For a more full-featured eigenvalue solver I would recommend [SLEPc](https://slepc.upv.es). This can be coupled with MFEM by building MFEM with PETSc support and PETSc with SLEPc support. I'm afraid I don't know of any example codes which demonstrate this coupling.

If this sounds like a viable option for you, we would be happy to offer any advice that we can.

Best wishes,
Mark
