### ISSUE TITLE
Leaks in serial and parallel unit tests

### ISSUE THREAD

**Issue by camierjs** [mfem/mfem#3566]
Some unit tests are leaking, both in serial (BilinearFormIntegrator, BuildDofToArrays, Chebyshev symmetry, Coarsen, DataCollection, LinearFECollection, MixedScalarIntegrator, PAIdentityInterp, SubMesh, Transfer) and parallel (ParSubMesh).

Even though they aren't very important, tracking problems and other leaks cause a lot of output that needs to be filtered.

If users could get a sanitized run output, it might be easier to catch them.

**Comment by v-dobrev** [comment]
This is good suggestion -- if we can add a test that builds MFEM with ASan and then runs all MFEM tests checking for any ASan issues, that will be great.
