### ISSUE TITLE
Question regarding to the H1 linear basis and corresponding bilinear operator matrix

### ISSUE THREAD

**Issue by gzict** [mfem/mfem#3572]
Dear Saff,

I'm developing a customized mfem bilinearform and I'm trying to make a deeper understanding of the mfem finite element spaces and integration rules. And I have some questions regarding to the assemble of the bilinear operator matrix.

I would like to post a related case in my ex0 experiments. In issue #1839 (How to use ComputeElementFlux and ComputeFluxEnergy?)  @v-dobrev mentioned the following:

>If you just want to compute the energy from the FE formulation, E(u) = (1/2) a(u,u) - b(u) then you can use the methods BilinearForm::FullInnerProduct and LinearForm::operator()(const GridFunction &). Since the LinearForm is typically modified when eliminating boundary conditions, then it will be easier to copy the LinearForm to a Vector after assembly but before elimination of b.c. and then later compute b(u) by using the InnerProduct with the solution GridFunction.

I repeated a similar energy calculation on ex0. And I discovered the following:

For the homogeneous Dirichlet boundary condition, the energy works just fine. Its value is consistent with different refinement.

For the nonhomogeneous Dirichlet boundary condition, however, the value of energy began to show dependence on the refinement. When mesh gets finer (more triangles), the energy becomes larger. Of course, one could point out that nonhomogeneous Dirichlet boundary should be evaluated separately.  But the problem is that nonhomogeneous Dirichlet boundary's contribution is a boundary integral with a value independent of mesh refinements. Thus if the a.fullinnerproduct cannot get a fixed value, I cannot find E(u) = (1/2) a(u,u) - b(u).   

For those who interested in repeating my issue, here is my modified code of ex0  with the triangular mesh :

```c++
#include "mfem.hpp"
#include <fstream>
#include <iostream>

using namespace std;
using namespace mfem;

int main(int argc, char *argv[])
{
   // 1. Parse command line options
   const char *mesh_file = "./square_tri.mesh";
//   const char *mesh_file = "../data/star.mesh";
   int order = 1;

   OptionsParser args(argc, argv);
   args.AddOption(&mesh_file, "-m", "--mesh", "Mesh file to use.");
   args.AddOption(&order, "-o", "--order", "Finite element polynomial degree");
   args.ParseCheck();

   // 2. Read the mesh from the given mesh file, and refine once uniformly.
   Mesh mesh(mesh_file);
   for (int i = 0; i<1; i++)
   {
           mesh.UniformRefinement();
   }

   // 3. Define a finite element space on the mesh. Here we use H1 continuous
   //    high-order Lagrange finite elements of the given order.
   H1_FECollection fec(1, mesh.Dimension());
   FiniteElementSpace fespace(&mesh, &fec);
   cout << "Number of unknowns: " << fespace.GetTrueVSize() << endl;

   // 4. Extract the list of all the boundary DOFs. These will be marked as
   //    Dirichlet in order to enforce zero boundary conditions.
Array<int> dir1_tdof_list,boundary_dofs;
   Array<int> dir1_ess_bdr(4);
   Array<int> ess_bdr(4);

   dir1_ess_bdr = 0;
   dir1_ess_bdr[0] = 1;
   ess_bdr = 1;

   fespace.GetEssentialTrueDofs(dir1_ess_bdr,  dir1_tdof_list);
   fespace.GetEssentialTrueDofs(ess_bdr, boundary_dofs);

   // 5. Define the solution x as a finite element grid function in fespace. Set
   //    the initial guess to zero, which also sets the boundary conditions.
   GridFunction x(&fespace);
   x = 0.0;
   x.SetSubVector(dir1_tdof_list, 1.0);

  // x.SetSubVector(boundary_dofs, 1.0);

   // 6. Set up the linear form b(.) corresponding to the right-hand side.
   ConstantCoefficient one(1.0);
   LinearForm b(&fespace);
   b.AddDomainIntegrator(new DomainLFIntegrator(one));
   b.Assemble();
   Vector b_dup;
   b_dup = b;

   // 7. Set up the bilinear form a(.,.) corresponding to the -Delta operator.
   BilinearForm a(&fespace);
   a.AddDomainIntegrator(new DiffusionIntegrator);
   a.Assemble();

   // 8. Form the linear system A X = B. This includes eliminating boundary
   //    conditions, applying AMR constraints, and other transformations.
   SparseMatrix A;
   Vector B, X;
   a.FormLinearSystem(boundary_dofs, x, b, A, X, B);

//   A.Print();
//   B.Print();


   // 9. Solve the system using PCG with symmetric Gauss-Seidel preconditioner.
   GSSmoother M(A);
   PCG(A, M, B, X, 1, 200, 1e-12, 0.0);

   // 10. Recover the solution x as a grid function and save to file. The output
   //     can be viewed using GLVis as follows: "glvis -m mesh.mesh -g sol.gf"
                                                        
a.RecoverFEMSolution(X, b, x);
   double innerproda = a.FullInnerProduct(x,x);
   double innerprodb = InnerProduct(b,x);
   double energy = 0.5*innerproda - innerprodb;
   cout << innerproda <<endl;
   cout << innerprodb <<endl;
   cout << energy <<endl;
//   X.Print();
//   x.Print();
   x.Save("sol.gf");
   mesh.Save("mesh.mesh");

   return 0;
}
```

```txt
elements
18
1 2 0 1 4
1 2 4 5 8
1 2 8 9 12
1 2 1 2 5
1 2 5 6 9
1 2 9 10 13
1 2 2 3 6
1 2 6 7 10
1 2 10 11 14
1 2 1 5 4
1 2 5 9 8
1 2 9 13 12
1 2 2 6 5
1 2 6 10 9
1 2 10 14 13
1 2 3 7 6
1 2 7 11 10
1 2 11 15 14


boundary
12
1 1 0 1
1 1 1 2
1 1 2 3
4 1 3 7
4 1 7 11
4 1 11 15
2 1 15 14
2 1 14 13
2 1 13 12
3 1 12 8
3 1 8 4
3 1 4 0


vertices
16
2
0.000 0.000
0.333 0.000
0.667 0.000
1.000 0.000
0.000 0.333
0.333 0.333
0.667 0.333
1.000 0.333
0.000 0.667
0.333 0.667
0.667 0.667
1.000 0.667
0.000 1.000
0.333 1.000
0.667 1.000
1.000 1.000
```

 P.S. I figured out the matrix issue, but the innerproduct issue remains.

**Comment by gzict** [comment]
For clarification, the actual bilinear operator matrix A is more complicated than (-1, .. -1, .., 4, ..., -1, ... -1), which is only a row for interior points. For boundary points the form is different since in ex0 the Dirichlet boundary condition is used. But my point is that it somehow missed a coefficient of triangle elment size, and this also applies to matrix rows related to boundary points.

**Comment by gzict** [comment]
I would also like to post a related case in my ex0 experiments. In issue #1839 (How to use ComputeElementFlux and ComputeFluxEnergy?)  @v-dobrev mentioned the following:

>If you just want to compute the energy from the FE formulation, E(u) = (1/2) a(u,u) - b(u) then you can use the methods BilinearForm::FullInnerProduct and LinearForm::operator()(const GridFunction &). Since the LinearForm is typically modified when eliminating boundary conditions, then it will be easier to copy the LinearForm to a Vector after assembly but before elimination of b.c. and then later compute b(u) by using the InnerProduct with the solution GridFunction.

I repeated a similar energy calculation on ex0. And I discovered the following:

For the homogeneous Dirichlet boundary condition, the energy works just fine. Its value is consistent with different refinement.

For the nonhomogeneous Dirichlet boundary condition, however, the value of energy began to show dependence on the refinement. When mesh gets finer (more triangles), the energy becomes larger. Of course, one could point out that nonhomogeneous Dirichlet boundary should be evaluated separately.  But the problem is that nonhomogeneous Dirichlet boundary's contribution is a boundary integral with a value independent of mesh refinements. Thus if the a.fullinnerproduct cannot get a fixed value, I cannot find E(u) = (1/2) a(u,u) - b(u).   

For those who interested in repeating my issue, here is my modified code of ex0 (works with the mesh I provided above):


#include "mfem.hpp"
#include <fstream>
#include <iostream>

using namespace std;
using namespace mfem;

int main(int argc, char *argv[])
{
   // 1. Parse command line options
   const char *mesh_file = "./square_tri.mesh";
//   const char *mesh_file = "../data/star.mesh";
   int order = 1;

   OptionsParser args(argc, argv);
   args.AddOption(&mesh_file, "-m", "--mesh", "Mesh file to use.");
   args.AddOption(&order, "-o", "--order", "Finite element polynomial degree");
   args.ParseCheck();

   // 2. Read the mesh from the given mesh file, and refine once uniformly.
   Mesh mesh(mesh_file);
   for (int i = 0; i<1; i++)
   {
           mesh.UniformRefinement();
   }

   // 3. Define a finite element space on the mesh. Here we use H1 continuous
   //    high-order Lagrange finite elements of the given order.
   H1_FECollection fec(1, mesh.Dimension());
   FiniteElementSpace fespace(&mesh, &fec);
   cout << "Number of unknowns: " << fespace.GetTrueVSize() << endl;

   // 4. Extract the list of all the boundary DOFs. These will be marked as
   //    Dirichlet in order to enforce zero boundary conditions.
Array<int> dir1_tdof_list,boundary_dofs;
   Array<int> dir1_ess_bdr(4);
   Array<int> ess_bdr(4);

   dir1_ess_bdr = 0;
   dir1_ess_bdr[0] = 1;
   ess_bdr = 1;

   fespace.GetEssentialTrueDofs(dir1_ess_bdr,  dir1_tdof_list);
   fespace.GetEssentialTrueDofs(ess_bdr, boundary_dofs);

   // 5. Define the solution x as a finite element grid function in fespace. Set
   //    the initial guess to zero, which also sets the boundary conditions.
   GridFunction x(&fespace);
   x = 0.0;
   x.SetSubVector(dir1_tdof_list, 1.0);

  // x.SetSubVector(boundary_dofs, 1.0);

   // 6. Set up the linear form b(.) corresponding to the right-hand side.
   ConstantCoefficient one(1.0);
   LinearForm b(&fespace);
   b.AddDomainIntegrator(new DomainLFIntegrator(one));
   b.Assemble();
   Vector b_dup;
   b_dup = b;

   // 7. Set up the bilinear form a(.,.) corresponding to the -Delta operator.
   BilinearForm a(&fespace);
   a.AddDomainIntegrator(new DiffusionIntegrator);
   a.Assemble();

   // 8. Form the linear system A X = B. This includes eliminating boundary
   //    conditions, applying AMR constraints, and other transformations.
   SparseMatrix A;
   Vector B, X;
   a.FormLinearSystem(boundary_dofs, x, b, A, X, B);

//   A.Print();
//   B.Print();


   // 9. Solve the system using PCG with symmetric Gauss-Seidel preconditioner.
   GSSmoother M(A);
   PCG(A, M, B, X, 1, 200, 1e-12, 0.0);

   // 10. Recover the solution x as a grid function and save to file. The output
   //     can be viewed using GLVis as follows: "glvis -m mesh.mesh -g sol.gf"
                                                        
a.RecoverFEMSolution(X, b, x);
   double innerproda = a.FullInnerProduct(x,x);
   double innerprodb = InnerProduct(b,x);
   double energy = 0.5*innerproda - innerprodb;
   cout << innerproda <<endl;
   cout << innerprodb <<endl;
   cout << energy <<endl;
//   X.Print();
//   x.Print();
   x.Save("sol.gf");
   mesh.Save("mesh.mesh");

   return 0;
}

**Comment by mlstowell** [comment]
Hi, @gzict,

I'm not sure about this but it may fit the symptoms. If we look at:
```
double FullInnerProduct(const Vector &x, const Vector &y) const
   { return mat->InnerProduct(x, y) + mat_e->InnerProduct(x, y); }
```
This seems to make the assumption that `full_mat = mat + mat_e`. However, I'm not sure this is true. Once boundary conditions are used to modify the system matrix `mat` has had some diagonal entries changed to 1 (by default). The first inner product will then contain $\sum I_{ii} x_i y_i$ (where $I_{ij}$ is equal to zero unless $i=j$ and $i$ is a Dirichlet index). This additional sum will grow as the mesh is refined unless $x$ and $y$ are zero on the Dirichlet boundary. In fact since you're setting $x=1$ on the Dirichlet boundary the excess should equal `dir1_tdof_list.Size()`.

Best wishes,
Mark

**Comment by gzict** [comment]
@mlstowell 

Hi Mark,

Thank you very much for the reply.

> The first inner product will then contain $\sum I_{ii} x_i y_i$ (where $I_{ij}$ is equal to zero unless $i=j$ and $i$ is a Dirichlet index). This additional sum will grow as the mesh is refined unless $x$ and $y$ are zero on the Dirichlet boundary. In fact since you're setting $x=1$ on the Dirichlet boundary the excess should equal `dir1_tdof_list.Size()`.

This insight is very useful, and I will verify it in some experiments. On the other hand, however, I'm afraid quantify or removing excess does not solve my problem of calculating FE energy. 

I did suspect that the excess comes from the boundary condition, so I tried to modify the solution gridfunction x's value on Dirichlet boundary points to 0 (lets call it x_m). It effectively removes the excess as showed in your formula, as the result, a.FullInnerProduct(x_m,x_m) is 0. As the result, FE energy 0.5*a(u,u)-b(u) becomes -b(u). 

Now lets set the rhs of laplace problem in ex0 to be 0 (b = 0) with nonhomogeneous dirichlet bc. If we calculate FE and remove boundary excess, the whole energy becomes 0. On the other hand, this is not true both physically and numerically. The diffusion system has energy and its source is the boundary condition. But I have trouble evaluate it using tools provided by mfem.

In fact, the reason I raise this question is that it may reflect some deeper properties in the bilinear operator. First, the correct evaluation of FE energy depends on forming AX=B, and we should be able to calculate it using some form of inner product. Second, FE energy is also used in error estimators and flux calculations. I'm wondering if they share the same issue like fullinnerproduct.

If you and your colleague could help me to solve this issue, it would be very appreciate.

Best,

zhen

**Comment by gzict** [comment]
At the moment I have a temporary solution, but I'm not sure if it make sense.

In the case of dirichlet b.c. finite element method does not construct whole bilinear matrix. It only construct a smaller matrix using interior points, and the boundary condition is transered to the r.h.s.

I think mfem is doing the same thing, although in an indirect fashion. In short, after FormLinearsystem, bilinear matrix a.mat and linear form vector b is the same as the construction I mentioned above if we only consider true d.o.fs. Although I'm not certain, since eliminate process in the formlinearsystem is very general to include different FE methods.

Based on my assumption of mfem, I calculate the FE energy as the following (for simplicity, r.h.s b=0): 

1 obtain a vector y by multiply solution x to a.mat (after FormLinearsystem, not full mat ). 

2 set 0s on dirichlet bc points of y.

3 Find inner product of x and y.

The result still depends on mesh, but I think it is almost consistent if we multiply the result by sqrt(average element volume) in 2D.

It seems messy and very different to the original solution posted by @v-dobrev in issue #1839, but this is the closest thing I can get.

**Comment by mlstowell** [comment]
Hi, @gzict,

I think the first step is to confirm that `FullInnerProduct` is computing an incorrect result for the reason I mentioned. If this is the case then I would call this a bug and we should correct it. The fix should be fairly simple. Once that is resolved we can investigate other potential issues if the computed FE energy still seems to be incorrect

Also, you asked if the error estimator calculations might have similar issues. I don't believe so. They are computed using local element matrices without applying Dirichlet BCs.

Best wishes,
Mark

**Comment by gzict** [comment]
Hi Mark,

I did a couple tests based on your formula for ex0. It seems it does not exactly match your formula. Here are some results:


Problem:

$\Delta u = 1;

Nonhomogeneous Dirichlet BC

Result:
a.FullInnerProduct(x,x): (x^T a.mat x + x^T a.mat_e x)

3.16827
4.05533
4.93911
5.82196
6.70456
7.5871

a.InnerProduct(x,x): (x^T a.mat x)

15.2494
32.4457
67.6141
138.776
281.952
569.171

dir1_tdof_list.Size() (Dirichlet BC, u = 1)
7
13
25
49
97
193

boundary_dofs.Size() (All Dirichlet BC)
24
48
96
192
384
768

This is the code if it helps:

int main(int argc, char *argv[])
{
   // 1. Parse command line options
   const char *mesh_file = "./square_tri.mesh";
//   const char *mesh_file = "../data/star.mesh";
   int order = 1;

   OptionsParser args(argc, argv);
   args.AddOption(&mesh_file, "-m", "--mesh", "Mesh file to use.");
   args.AddOption(&order, "-o", "--order", "Finite element polynomial degree");
   args.ParseCheck();

   // 2. Read the mesh from the given mesh file, and refine once uniformly.
   Mesh mesh(mesh_file);
   double fix_const = 1.0;
   int num_step = 6;
   double innerprodb[num_step];
   double area[num_step];
   double length[num_step];
   for (int step = 0; step<num_step; step++)
   {
           mesh.UniformRefinement();
           fix_const = fix_const*0.5;


   double area_average = 0.0;
   double neres = 0.0;
   for (int i = 0; i<mesh.GetNE(); i++)
   {
           area_average += mesh.GetElementVolume(i);
           neres = neres + 1.0;
   }
   area_average = area_average/neres;
   area[step]=area_average;
cout << "area_average" << area_average <<endl;

   // 3. Define a finite element space on the mesh. Here we use H1 continuous
   //    high-order Lagrange finite elements of the given order.
   H1_FECollection fec(1, mesh.Dimension());
   FiniteElementSpace fespace(&mesh, &fec);
   cout << "Number of unknowns: " << fespace.GetTrueVSize() << endl;

   // 4. Extract the list of all the boundary DOFs. These will be marked as
   //    Dirichlet in order to enforce zero boundary conditions.
   Array<int> dir1_tdof_list,boundary_dofs;
   Array<int> dir1_ess_bdr(4);
   Array<int> ess_bdr(4);

   dir1_ess_bdr = 0;
   dir1_ess_bdr[0] = 1;
   ess_bdr = 1;

   fespace.GetEssentialTrueDofs(dir1_ess_bdr,  dir1_tdof_list);
   fespace.GetEssentialTrueDofs(ess_bdr, boundary_dofs);

   // 5. Define the solution x as a finite element grid function in fespace. Set
   //    the initial guess to zero, which also sets the boundary conditions.
   GridFunction x(&fespace);
   x = 0.0;
//   double length_average = sqrt(2.0*area_average);
//   length[step]=length_average;
//   fix_const = area_average;
   x.SetSubVector(dir1_tdof_list, 1.0);
//   x.Print();
  // x.SetSubVector(boundary_dofs, 1.0);

   // 6. Set up the linear form b(.) corresponding to the right-hand side.
   ConstantCoefficient one(1.0);
   ConstantCoefficient lambda(1.0);
   LinearForm b(&fespace);
   b.AddDomainIntegrator(new DomainLFIntegrator(one));
   b.Assemble();
   Vector b_dup;
   b_dup = b;

   // 7. Set up the bilinear form a(.,.) corresponding to the -Delta operator.
   BilinearForm a(&fespace);
   a.AddDomainIntegrator(new DiffusionIntegrator(lambda));
   a.Assemble();

   // 8. Form the linear system A X = B. This includes eliminating boundary
   //    conditions, applying AMR constraints, and other transformations.
   SparseMatrix A;
   Vector B, X;
   a.FormLinearSystem(boundary_dofs, x, b, A, X, B);

//   A.Print();
//   B.Print();


   // 9. Solve the system using PCG with symmetric Gauss-Seidel preconditioner.
   GSSmoother M(A);
   PCG(A, M, B, X, 1, 200, 1e-8, 0.0);

   // 10. Recover the solution x as a grid function and save to file. The output
   //     can be viewed using GLVis as follows: "glvis -m mesh.mesh -g sol.gf"
   a.RecoverFEMSolution(X, b, x);
//   x.SetSubVector(boundary_dofs, 0.0);
//   innerprodb[step] = a.FullInnerProduct(x,x);
   innerprodb[step] = a.InnerProduct(x,x);
//   length[step] = dir1_tdof_list.Size();
   length[step] = boundary_dofs.Size();
   Vector Y(mesh.GetNV());
//   a.mat->rint();
//   a.ComputeFluxEnergy(x,x);
//   a.mat->Mult(x,Y);
//   a.mat_e->AddMult(x,Y);
//  Y.Print(); 
// cout<<"\n"<<endl;
// B.Print();

//x.Print();

//  x.SetSubVector(boundary_dofs, 0.0);
//  Y.Print();
//  x.Print();
//   double innerproda = a.FullInnerProduct(x,x);
//    innerprodb[step] = InnerProduct(Y,x)*length_average;
//   double energy = 0.5*innerproda - innerprodb;
//   cout << innerproda <<endl;
   }
   for (int i = 0; i<num_step; i++)
   cout << innerprodb[i] <<endl;

   for (int i = 0; i<num_step; i++)
           cout << length[i] << endl;

//   cout << energy <<endl;
//   X.Print();
//   x.Print();
//   x.Save("sol.gf");
//   mesh.Save("mesh.mesh");


   return 0;
}

**Comment by mlstowell** [comment]
Hi, @gzict,

After looking more closely at your example program and your mesh I think I see the problem. The boundary conditions are discontinuous which, in this case, produces a logarithmic singularity in the energy calculation. As the mesh is refined this singularity is better approximated leading to a higher energy. If you alter the boundary conditions so that they become continuous the energy will remain fixed and the code will be able to converge to this fixed energy.

Also, I ran some tests on known solutions with inhomogeneous boundary conditions and the energy calculation produced the correct answer so there does not seem to be a bug in `FullInnerProduct`.

Best wishes,
Mark
