### ISSUE TITLE
How to get total number of vertices from a ParMesh

### ISSUE THREAD

**Issue by YHuiDong** [mfem/mfem#3574]
Hi, 

for the serial code, we get global number of vertices via GetNV().  
May I ask for the ParMesh,  do we have a similar call to get 
the global number of vertices?

Thanks.

**Comment by v-dobrev** [comment]
This is not implemented as a method in ParMesh at the moment. You can compute it with something like this:
```c++
   HYPRE_BigInt GetGlobalNumVertices(ParMesh &pmesh)
   {
      H1_FECollection fec(1, pmesh.Dimension());
      ParFiniteElementSpace fespace(&pmesh, &fec);
      return fespace.GlobalTrueVSize();
   }
```

**Comment by YHuiDong** [comment]
Hi, @v-dobrev ,

thank you very much for this help.  It works now. 

Best wishes.
