### ISSUE TITLE
Use soultion on the coarse ParMesh as initial guess to the solution on the refined mesh ? 

### ISSUE THREAD

**Issue by YHDAUT** [mfem/mfem#3575]
Hi, 

May I sincerely ask in MFEM,  is it possible to use solution coarsex on the corase ParMesh as an initial 
guess for the solution finex in the refined ParMesh by some calling like:

parmesh->coarset2fine(coarsex, finex)

Thank you very much in advance.

**Comment by v-dobrev** [comment]
This illustrated in `ex6`/`ex6p` in AMR context, e.g. after mesh refinement here https://github.com/mfem/mfem/blob/d4bc14a48a1781ae4f7a16855f98c491f1e98389/examples/ex6p.cpp#L340 and FE space update here https://github.com/mfem/mfem/blob/d4bc14a48a1781ae4f7a16855f98c491f1e98389/examples/ex6p.cpp#L355 the solution `x` is interpolated from the old mesh to the new mesh here https://github.com/mfem/mfem/blob/d4bc14a48a1781ae4f7a16855f98c491f1e98389/examples/ex6p.cpp#L356

The interpolation operator (aka the transfer operator) is created when `fespace.Update()` is called and then that operator is used when `x.Update()` is called.

**Comment by YHuiDong** [comment]
Hi, @v-dobrev ,

thanks a lot for pointing out ex6p.cpp.   This helps me a lot and  may take me a while to implement, will report soon ..  Instead of using L2ZienkiewiczZhuEstimator  object as input argument for ThresholdRefiner,  I have a special Estimator and  is thinking how to incorporate this into the code ,  I may need to write a small Estimator class derived from the basic one...

Best wishes

**Comment by YHuiDong** [comment]
Hi,  @tzanio ,

thanks for help.  To simplify the test, I  just run the uniform refinement.   Is it possible by setting:

 L2ZienkiewiczZhuEstimator estimator(*integ, *u, flux_fes, *smooth_flux_fes);
 ThresholdRefiner refiner(estimator);
  
refiner.SetTotalErrorFraction(0.0);

By setting error faction to 0,  I assume that every element will be refined uniformly..  

Thanks...

**Comment by YHuiDong** [comment]
Hi, 

to get uniform refinements,  I try to set refiner.SetTotalErrorFraction(0.0).

 Unfortunately, after two level refinements by calling

refiner.Apply(*pmesh);

 it seems  refiner.Stop() fulfills...  No more refinements are performed.  

Thanks

**Comment by v-dobrev** [comment]
This can happen if the `estimator` returns all 0 estimates for all elements. Currently, if the estimate for an element is 0, it will not be refined.

**Comment by YHuiDong** [comment]
Hi @v-dobrev 

cannot figure out why it fails to do refinement.  If I set refiner.SetTotalErrorFraction(0.0)


 Is there an example to write own ErrorEstimator ?  It might be the reason that my estimator is not well defined.  


Thanks.

**Comment by v-dobrev** [comment]
Here's an example of a simple fake estimator -- it returns local errors equal to 1 for all elements and that should force global refinements every time:
```c++
class FakeErrorEstimator : public ErrorEstimator
{
protected:
   Mesh *mesh; /// not owned
   Vector error_estimates;

public:
   FakeErrorEstimator(Mesh *mesh_) : mesh(mesh_) { }

   /// Get a Vector with all element errors.
   const Vector &GetLocalErrors() override
   {
      error_estimates.SetSize(mesh->GetNE());
      error_estimates = 1.0;
      return error_estimates;
   }

   /// Force recomputation of the estimates on the next call to GetLocalErrors.
   void Reset() override { }
};
```

**Comment by YHuiDong** [comment]
Hi, @v-dobrev 

thank you very much for your kind help.  

Best wishes.

**Comment by YHuiDong** [comment]
Hi,  just tested your code, it works well for uniform 
refinement.  I have adapted the code bit, such 
that every time after mesh refinement, we 
got correct number error estimators.

Thanks. 

class FakeErrorEstimator : public ErrorEstimator
{
protected:
   Mesh *mesh; /// not owned
   Vector error_estimates;

public:
   FakeErrorEstimator(){;}
   FakeErrorEstimator(Mesh *mesh_) : mesh(mesh_) { }
   void setMesh(Mesh *mesh_){mesh=mesh_;}

   /// Get a Vector with all element errors.
   const Vector &GetLocalErrors() override
   {
      error_estimates.SetSize(mesh->GetNE());
      error_estimates = 1.0;
      return error_estimates;
   }

   /// Force recomputation of the estimates on the next call to GetLocalErrors.
   void Reset() override { }
};

**Comment by YHuiDong** [comment]
Hi,  thanks a lot.  I just got very strange error that 

for the total dimension 125 dofs,  using 1, 2, 3 cpus, the code runs well for the uniform refinement (using refiner.Apply(*pmesh)), but fixed stopping tolerance.

However, from 4 cpus on, the code does not run well as expected... 

I try to describe my code below, but, properly this is bit too lengthy:

In the refining loop:
{
     HYPRE_BigInt dimU = ufespace->GlobalTrueVSize();
     HYPRE_BigInt dimP = pfespace->GlobalTrueVSize();

     Array<int> block_offsets(3);
     block_offsets[0] = 0;
     block_offsets[1] = ufespace->GetVSize();
     block_offsets[2] = pfespace->GetVSize();
     block_offsets.PartialSum();

     Array<int> block_trueOffsets(3); 
     block_trueOffsets[0] = 0;
     block_trueOffsets[1] = ufespace->TrueVSize();
     block_trueOffsets[2] = pfespace->TrueVSize();
     block_trueOffsets.PartialSum();

     BlockVector x(block_offsets, mt), rhs(block_offsets, mt);
     BlockVector trueX(block_trueOffsets, mt), trueRhs(block_trueOffsets, mt);

     fform->Update(ufespace, rhs.GetBlock(0), 0);
     gform->Update(pfespace, rhs.GetBlock(1), 0);

      fform->Assemble();
      fform->SyncAliasMemory(rhs);
      fform->ParallelAssemble(trueRhs.GetBlock(0));
      trueRhs.GetBlock(0).SyncAliasMemory(trueRhs);

      gform->Assemble();
      gform->SyncAliasMemory(rhs);
      gform->ParallelAssemble(trueRhs.GetBlock(1));
      trueRhs.GetBlock(1).SyncAliasMemory(trueRhs);

     // assem stiffness matrix
      mVarf->Assemble();  //A
      mVarf->Finalize();

      bVarf->Assemble();  //B
      bVarf->Finalize();

      pVarf->Assemble();  //C
      pVarf->Finalize();

      OperatorHandle A, B, C;
      mVarf->FormSystemMatrix(u_ess_tdof_list, A);
      bVarf->FormRectangularSystemMatrix(u_ess_tdof_list, p_ess_tdof_list, B);
      pVarf->FormSystemMatrix(p_ess_tdof_list, C);
   
      OperatorHandle Bt(B.As<HypreParMatrix>()->Transpose());
   
      Array2D<HypreParMatrix*> blocks(2,2);
      blocks(0,0) = A.As<HypreParMatrix>();
      blocks(1,0) = B.As<HypreParMatrix>();
      blocks(0,1) = Bt.As<HypreParMatrix>();
      blocks(1,1) = C.As<HypreParMatrix>();
      
      HypreParVector trueRhs_g(blocks(1,1)->GetComm(), blocks(1,1)->GetGlobalNumRows(), 
                               trueRhs.GetBlock(1).GetData(), blocks(1,1)->GetRowStarts());

      HypreParVector truex_g(blocks(1,1)->GetComm(), blocks(1,1)->GetGlobalNumCols(),
                              trueX.GetBlock(1).GetData(), blocks(1,1)->GetColStarts());


      double pcgtol=1.0e-6;

      chrono.Clear();
      chrono.Start();
     
      // calling my schur_pcg solver
       schur_pcg(blocks(*,*), 
                blocks(*,*), 
                blocks(*,*), 
                blocks(*,*),
                &trueRhs_g,
                &truex_g, 
                pcgtol);

      chrono.Stop();

      u->MakeRef(ufespace, x.GetBlock(0), 0);
      p->MakeRef(pfespace, x.GetBlock(1), 0);
      u->Distribute(&(trueX.GetBlock(0)));
      p->Distribute(&(trueX.GetBlock(1)));

     refiner.Apply(*pmesh);
     estimator.setMesh(pmesh);

      ufespace->Update();
      pfespace->Update();
      u->Update();
      p->Update();

      mVarf->Update();
      bVarf->Update();
      pVarf->Update();

      fform->Update();
      gform->Update();

      ref_lev++;
}
     
Thanks in advance.

**Comment by YHuiDong** [comment]
Hi,  I just found that in exp6p.cpp example, there is a calling

     a.Counterrevolution(X, b, x)

In my code above, I did not call this function, but calling 

      u->MakeRef(ufespace, x.GetBlock(0), 0);
      p->MakeRef(pfespace, x.GetBlock(1), 0);
      u->Distribute(&(trueX.GetBlock(0)));
      p->Distribute(&(trueX.GetBlock(1)));

May I sincerely ask will this make difference?  

Thanks.

**Comment by YHDAUT** [comment]
Hi, @v-dobrev . @tzanio ,

in my Shur_PCG implementation, I have made operations HypreParVector objects:

      r11*=alpha;
      r1=r0;
      r1-=r11;

However, I assume that the vectors are accumulated,  If I multiply them by a vector,  the vectors 
at the interface of cpus are multiplied more than one time...   Do you think this might be the cause 
of failure of my code for more cpus because of such multiple multiplications?

Thanks..

**Comment by YHDAUT** [comment]
Thank you. The problem is solved now. I did not initialize the vectors correctly before giving them to the pcg solvers...
