### ISSUE TITLE
Collective RAM for MFEM

### ISSUE THREAD

**Issue by shani9383** [mfem/mfem#3576]
Hi,
I'm trying to run a linear elastic isotropic model containing  about 40 million Hex elements. I'm using a modified code of ex2p. Due to the amount of elements, large memory is required. Can you please recommend on large-scale environments with collective RAM that are user friendly with MFEM and GlvIs. 
Thanks
Shani.

**Comment by tzanio** [comment]
You should ideally run in parallel on a distributed memory machine. Depending on the order 40 million elements should work well on 40-400 MPI ranks.
