### ISSUE TITLE
How to use PWCoefficient in a domain integrator 

### ISSUE THREAD

**Issue by YHDAUT** [mfem/mfem#3580]
Hi, 

May I sincerely ask how to use PWCoefficient in a domain inergator:

PWCoefficient coeff;

mVarf->AddDomainIntegrator (new MassIntegrator(irho)).

Here, the coeff is a piecewise function on each tetrahedral,  depending on a tetrahedral diameter size h.  Is there 
a way to realize this in MFEM? 

Thanks a lot.

**Comment by mlstowell** [comment]
Hello, @YHuiDong,

The `PWCoefficient` uses the element attribute number to select an appropriate `Coefficient` object. The intended use is to model a handful of regions in a mesh which have different material properties. It may be possible to tag each tetrahedron with a separate attribute number and create `Coefficient` objects for each one but this would be impractical for most meshes.

I see two options. If you can use the approximate element size as computed from the Jacobian then you can write a custom `Coefficient` class with an `Eval` method that computes your coefficient value from the Jacobian which is available through the `ElementTransformation` object. If you need a more specific calculation for the diameter you may need to compute the diameters in a separate step and store the results in a `GridFunction` (L2 grid functions are handy for such element-wise storage) then write a custom `Coefficient` class, similar to a `GridFunctionCoefficient`, which computes your coefficient value from the pre-computed diameter value.

Best wishes,
Mark

**Comment by YHuiDong** [comment]
Hi Mark @mlstowell 

for my application, it would be sufficient to know approximately the diameter of an tetrahedron.  If I use your first method:

class MyCoefficient : public Coefficient
{
private:

public:
   MyCoefficient(){ ; }
   virtual double Eval(ElementTransformation &T, const IntegrationPoint &ip);
   virtual ~MyCoefficient() { ; }
};

double MyCoefficient :: Eval(ElementTransformation &T, const IntegrationPoint &ip)
{
   T.Jacobian()  ??


    here,  how return approximately the size of an element  from   a Jacobian matrix, Thanks..
  
}

**Comment by mlstowell** [comment]
HI, @YHuiDong,

Have a look at [Mesh::GetElementSize](https://github.com/mfem/mfem/blob/d4bc14a48a1781ae4f7a16855f98c491f1e98389/mesh/mesh.cpp#L76-L96)
which shows three different measures of the size.

Best wishes,
Mark

**Comment by YHuiDong** [comment]
Hi @mlstowell ,

thanks a lot Mark.  it works now with in the  Mesh::GetElementSize

if (type == 0)
   {
      return pow(fabs(J.Weight()), 1./Dim);
   }

Best wishes.
