### ISSUE TITLE
What is the difference in boundary integrators for a linear form?

### ISSUE THREAD

**Issue by tuckerbabcock** [mfem/mfem#3583]
What is the difference between the interfaces for adding boundary integrators to a linear form? Specifically, why is there both a `AddBoundaryIntegrator` and a `AddBdrFaceIntegrator` (and the associated `boundary_integs` and `boundary_face_integs`)?

**Comment by pazner** [comment]
`AddBoundaryIntegrator` is designed for linear form integrators that are defined on conforming (e.g. H1) spaces, and integrate traces over the boundary using the virtual function
```c++
   virtual void AssembleRHSElementVect(const FiniteElement &el,
                                       ElementTransformation &Tr,
                                       Vector &elvect) = 0;
```

On the other hand, `AddBdrFaceIntegrator` is designed for DG-type integrators that are designed to work on both interior and boundary faces, and use the virtual function
```c++
   virtual void AssembleRHSElementVect(const FiniteElement &el,
                                       FaceElementTransformations &Tr,
                                       Vector &elvect);
```

**Comment by tuckerbabcock** [comment]
How do the `el`s differ between the two? Is the `el` in the H1 signature the face element (segment in 2D)? And for the DG signature it is the volume element at the boundary (tri/square in 2D)?

I guess I'm also a bit confused by the inconsistency between the linear and the nonlinear forms, since the nonlinear form only has the `AddBdrFaceIntegrator`. Can you explain why that is?

Thanks!

**Comment by tuckerbabcock** [comment]
Thanks!
