### ISSUE TITLE
Question on SubMesh CreateFromBoundary

### ISSUE THREAD

**Issue by ryanblack129** [mfem/mfem#3584]
Hello,

I am trying to use the SubMesh feature to do the following:

-Extract a boundary surface from a 3D mesh
-On the extracted surface, extract the boundary edge

For my application, I need the the node coordinates on this boundary edge. Below is my attempt at doing this:

```
   // create submesh for inflow surface
   Array<int> inflow_attr_array(mesh->bdr_attributes.Max());
   inflow_attr_array = 0;
   inflow_attr_array[0] = 1;
   SubMesh surface_mesh = SubMesh::CreateFromBoundary(*mesh,inflow_attr_array);

   // now extract boundary edge of inflow surface
   Array<int> inflow_bdr_attr(surface_mesh.bdr_attributes.Max());
   inflow_bdr_attr = 1;
   SubMesh inflow_boundary_mesh = SubMesh::CreateFromBoundary(surface_mesh,inflow_bdr_attr);
```

The above works fine for meshes that are not higher order. However, when I call `mesh->EnsureNodes()` or `mesh->SetCurvature()` prior to the above code, I get the following error (pointing to line 172 in submesh_utils.cpp) when I call CreateFromBoundary() the second time

> Assertion failed: (parent_vdofs.Size() == sub_vdofs.Size()) is false:
 --> internal error
 ... in function: void mfem::SubMeshUtils::BuildVdofToVdofMap(const mfem::FiniteElementSpace&, const mfem::FiniteElementSpace&, const mfem::SubMesh::From&, const mfem::Array<int>&, mfem::Array<int>&)

Any help with this would be greatly appreciated. Also, perhaps there is a another way to get these node coordinates on the boundary edge?

Thanks,
Ryan

**Comment by vladotomov** [comment]
If only the edge node coordinates are needed, you can probably get something through `Mesh::GetBdrElementEdges()`, then `FiniiteElementSpace::GetEdgeDofs()`, and then get the values from the `Mesh::Nodes` function that stores the coordinates.

**Comment by mlstowell** [comment]
I can confirm this error in the serial version of the code but in parallel I see no error. Curious...

**Comment by mlstowell** [comment]
I think I may see the problem but @jandrej will need to confirm. Both `SubMesh` objects share a common parent. So the transfer map attempts to create two mappings from the two sub-meshes back to the common parent. One of these calls to  `SubMeshUtils::BuildVdofToVdofMap` will succeed but the other will fail. The failure is caused by the fact that the elements of the `inflow_boundary_mesh` are not elements or boundary elements of the common parent mesh.

This does not explain why the `ParSubMesh` objects did not produce a failure so I may be on the wrong track. What do you think, @jandrej?

**Comment by ryanblack129** [comment]
Thanks for looking into this and for the workaround. In the meantime, I am able to get the boundary-edge node coordinates using the workaround

**Comment by jandrej** [comment]
> I think I may see the problem but @jandrej will need to confirm. Both `SubMesh` objects share a common parent. So the transfer map attempts to create two mappings from the two sub-meshes back to the common parent. One of these calls to `SubMeshUtils::BuildVdofToVdofMap` will succeed but the other will fail. The failure is caused by the fact that the elements of the `inflow_boundary_mesh` are not elements or boundary elements of the common parent mesh.
> 
> This does not explain why the `ParSubMesh` objects did not produce a failure so I may be on the wrong track. What do you think, @jandrej?

In master we don't support creating "line meshes" e.g. 1D boundary meshes of 2D surface meshes at all.
