### ISSUE TITLE
Is there more detailed tutorial for MFEM

### ISSUE THREAD

**Issue by Wayne901** [mfem/mfem#3590]
Hello,

I'm a rookie for MFEM and try to carry on my research with it. So far from the extensive examples I've learnt 
MFEM's abbility for NURBS, non-conformal adaptive mesh, matrix-free techniques, etc. However, more 
introduction for particular program and new technique is favorable than the comments in example codes
(DEAL.II has a extremely comprehensive documentation but I won't ask for an unlikely one like that).

For example when writing a new bilinear form different other than <u*,u> or <grad u*, grad u>, how to
implement a custom bilinear integral? In examples codes one just call packged Integrator(ElasticityIntegrator, 
DiffusionIntegrator ...) which is convenient but a little abrupt.

Right now I'm considering a frequency domain electromagnetic problem implemented with Nedelec element,
iteratively solved with partial-assembly geometric(h or p) multigrid method, with direct solver(PARDISO or MUMPS) 
for coarsest level mesh.

Any recommendation and MFEM documentation for coding my goal will be helpful. The AWS tutorial and
electromagnetic miniapps are great sources. The miniapps seems packaged many things up so recommendation
for modify it is welcomed as well.

**Comment by mlstowell** [comment]
Hello, @Wayne901,

Unfortunately we do not have a more detailed tutorial available. I don't think we have anything specifically focused on electromagnetic applications either. However, I'd be happy to provide you with advice through an issue like this if you run into any problems.

We certainly do need more detailed documentation about custom integrators. For now, we have a long list of integrators available so you may not need to implement your own. See [this](https://mfem.org/bilininteg/) for details.

Best wishes,
Mark

**Comment by sebastiangrimberg** [comment]
Hi @Wayne901, you may be interested in this project: https://github.com/awslabs/palace, which is built using MFEM for exactly the problem and solution techniques you describe.

**Comment by Wayne901** [comment]
Thanks for your suggestion Sebastian,

The feature that supports port excitation and GMG fullfills my needs, but I guess GMG and AMG preconditioners are for positive linear systems such as electrostatic and magnetostatic problems? Can GMG be applied to time-harmonic problems(though it may not perform well)?
