### ISSUE TITLE
How to get all the vector dof lists for the fespace?

### ISSUE THREAD

**Issue by adam-sim-dev** [mfem/mfem#3594]
I am not clear about the use of

`void GetVDofs(int vd, Array<int> &dofs, int ndofs = -1) const;`

what does the `vd` mean?

Thanks,
Adam

**Comment by jandrej** [comment]
A `vdof` is associated with "vector dimensions". `vd` denotes the "dimension". Take for example a velocity field in 2D. The size of the vector is `dim * ndofs`, so in this case `vdim = spatial_dim`.
