### ISSUE TITLE
overflow in global size

### ISSUE THREAD

**Issue by YHDAUT** [mfem/mfem#3601]
Hi,  I try to run an example with number of dofs 1076890625*2, however, I got the following running error:

Verification failed: (globalNum >= 0) is false:
 --> overflow in global size
 ... in function: void mfem::GatherBlockOffsetData(MPI_Comm, int, int, int, const mfem::Array<int>&, std::vector<int>&, int, std::vector<std::vector<int> >&, std::vector<int>&, std::vector<std::vector<i
nt> >&, HYPRE_BigInt&, HYPRE_BigInt&)
 ... in file:  mfem-4.4/linalg/hypre.cpp:2800..

Shall I reset int to HYPRE_BigInt ?

Thanks

**Comment by v-dobrev** [comment]
In the default build of HYPRE, both `HYPRE_BigInt` (this is the type of `globalNum`) and `HYPRE_Int` are 32-bit, i.e. simply `int`. What you probably need is to build HYPRE so that `HYPRE_BigInt` is 64-bit. You can do that by configuring it with either `--enable-mixedint` or `--enable-bigint`.

**Comment by YHDAUT** [comment]
Hi @v-dobrev ,  after compiling HYPRE,  using --enable-bigint,  I got an error for the piece of code:

Code:
 
  HYPRE_BigInt max_dofs = ...;
  args.AddOption(&max_dofs, "-md", "--max-dofs",
                  "Stop after reaching this many degrees of freedom.");

The error message:

  no matching function for call to ‘mfem::OptionsParser::AddOption(HYPRE_BigInt*, const char [4], const char [11], const char [50]) 

  "Stop after reaching this many degrees of freedom.");

One solution would be just comment out these two lines.  Would it be affect the code?  

Thanks

**Comment by v-dobrev** [comment]
Commenting out `args.AddOption(&max_dofs, ...)` should be fine as long as you set `max_dofs` to the value you want in the source file -- you want be able to set it on the command line.

**Comment by YHDAUT** [comment]
Thank you @v-dobrev .  This helps me a lot.
