### ISSUE TITLE
get a nodal representation of a grid function

### ISSUE THREAD

**Issue by YHDAUT** [mfem/mfem#3602]
Hi, 

may I sincerely ask in MFEM,  is there any simple call from ParGridFunction to a MFEM::Vector ?

Thanks

**Comment by v-dobrev** [comment]
I'm not sure I understand the question. `ParGridFunction` inherits from `Vector`, so it is a type of `Vector`.

Can you clarify what you mean?

**Comment by YHDAUT** [comment]
Thanks @v-dobrev ,  after updating the grid function p in a nested iteration,  I want to extract the vector v from it for my iterative solver.   You are right,  this can be realized by using 

v=*p->GetTrueDofs();

I am not sure if this is a good way to do it.

**Comment by v-dobrev** [comment]
For memory leaks, I'd recommend trying Valgrind, https://valgrind.org/.

**Comment by YHDAUT** [comment]
Hi @v-dobrev ,  thanks a lot for this great hint. I just forget about this tool, will check it.   :)

**Comment by YHDAUT** [comment]
Hi @v-dobrev ,  thanks a lot for your kind help. 

after using Valgrid: 
mpirun -np 4 valgrind --leak-check=yes ./ex5p

I got some messages, one of them is:

*************************************************************************************************
 Conditional jump or move depends on uninitialised value(s)

by 0x192F24: schur_pcg(mfem::HypreParMatrix const*, mfem::HypreParMatrix const*, mfem::HypreParMatrix const*, mfem::HypreParMatrix const*, mfem::HypreParVector const*, mfem::HypreParVector*, double const&)
**************************************************************************************************

Actually, before calling my schur_pcg,  I have initialized the vectors by 

>HypreParVector trueRhs_g(blocks(1,1)->GetComm(), blocks(1,1)->GetGlobalNumRows(), 
>                               trueRhs.GetBlock(1).GetData(), blocks(1,1)->GetRowStarts());

>HypreParVector truex_g(blocks(1,1)->GetComm(), blocks(1,1)->GetGlobalNumCols(),
 >                             trueX.GetBlock(1).GetData(), blocks(1,1)->GetColStarts());

for both the righthand side  and the solution of the Schur-complement equation:

trueRhs comes from  trueRhs.GetBlock(1).GetData() and 
truex_g comes from  trueX.GetBlock(1).GetData()

Does the message tell the above two initilization was not successful?

Thanks

**Comment by YHDAUT** [comment]
Hi @v-dobrev,  

the problems seems solved by adding the correct initialization. 

Thanks.
