### ISSUE TITLE
Retrive iteration number when using HiOp

### ISSUE THREAD

**Issue by ricgross** [mfem/mfem#3609]
Hi everyone,

I have a trivial question I cannot seem to find the answer to. 

When using HiOp to solve an optimization problem, is there a way to keep track of the number of the current "converged" (meaning after the correct step size has been determined) iteration?

More specifically, the HiOp example `ex9` uses a derived class of `OptimizationProblem`. I need to know within that class at which iteration I am currently at, in order to correctly store some data.

Maybe @cnpetra or @vladotomov have some inputs regarding this issue?

In advance, thanks for helping.

Best regards,
Riccardo

**Comment by cnpetra** [comment]
that is definitely possible via the [`iterate_callback`](https://github.com/LLNL/hiop/blob/2ef1cc53f8ee3e10c0d7627cb71dfba15020ae55/src/Interface/hiopInterface.hpp#L446) method of the HiOp's interface. But it not currently supported by MFEM's HiOp wrapper.

@vladotomov I think some changes are needed in MFEM's. Looks like adding a similar method to `mfem::OptimizationProblem` and calling this new method from an overload of `hiop::hiopInterfaceDenseConstraints::iterate_callback` in the HiOp's [adapter](https://github.com/mfem/mfem/blob/00b2a0705f647e17a1d4ffcb289adca503f28d42/linalg/hiop.hpp#L32) would do it.

**Comment by vladotomov** [comment]
Yes this makes sense, I'll look into adding `solution_callback` and `iterate_callback`. These seem somewhat HiOp-specific, especially the argument list. We may have to introduce a HiOp-specific user interface for `OptimizationProblem`.

**Comment by ricgross** [comment]
Hi @vladotomov and @cnpetra,

Thank you for your prompt reply. 

Is there a temporary workaround?

In advance, thanks.

Best regards,
Riccardo

**Comment by vladotomov** [comment]
Try [this PR](https://github.com/mfem/mfem/pull/3614) and let us know. This is very HiOp-specific and I exposed it as is. You'll need to change your `OptimizationProblem` to `HiOpProblem` and implement the callback method.

**Comment by ricgross** [comment]
Hi @vladotomov,

Thank you for your help.

I am still a bit unsure how to retrieve the iteration number, this time most likely due to my shortcomings in programming.

I have added your changes and shifted from `OptimizationProblem` to a `HiOpProblem`. However, by debugging through the code, I noticed that the method `HiopOptimizationProblem::iterate_callback` is never called, hence the method `IterateCallback` does not return any value. It is not entirely clear to me how (or where?) I can call `iterate_callback`.

What am I missing?

In advance, thanks.

Best regards,
Riccardo

**Comment by vladotomov** [comment]
It's expected to be called by HiOp, but we might be missing some setup in `HiopNlpOptimizer::Mult` [here](https://github.com/mfem/mfem/blob/00b2a0705f647e17a1d4ffcb289adca503f28d42/linalg/hiop.cpp#L288), @cnpetra can you take a look?

**Comment by cnpetra** [comment]
@vladotomov everything looks good to me. No setup is necessary. Likely the compiler does not see `HiopOptimizationProblem::iterate_callback` as an override of `hiopInterfaceDenseConstraints::iterate_callback`.


@ricgross can you put a breakpoint in [the default `hiopInterfaceDenseConstraints::iterate_callback` implementation](https://github.com/LLNL/hiop/blob/1bb3107091af3e82013486be00df7723bdd6879e/src/Interface/hiopInterface.hpp#L466)? If it enters there, then `HiopOptimizationProblem::iterate_callback` is not overridden correctly. 

Or maybe you can put a breakpoint in [this function](https://github.com/LLNL/hiop/blob/1bb3107091af3e82013486be00df7723bdd6879e/src/Optimization/hiopNlpFormulation.cpp#L1251) and see if it calls  `hiopInterfaceDenseConstraints::iterate_callback` or `HiopOptimizationProblem::iterate_callback` ?

**Comment by vladotomov** [comment]
@ricgross I was able to see the calls, see this commit for an example use c3572785dfdb8d082238f8332132af05977ee1a4
I ran `examples/hiop/ex9` with
`./ex9 -m ../../data/periodic-segment.mesh -r 3 -p 0 -o 2 -dt 0.002 -opt 2 -tf 0.1`

**Comment by ricgross** [comment]
Hi @vladotomov and @cnpetra,

Sorry for the delayed reply.

I am able to see the calls as well, I had somehow copied the files wrong the first time around. 

Thank you very much for helping.

Best regards,
Riccardo
