### ISSUE TITLE
ParSesquilinearForm and MixedCrossCurlIntegrator

### ISSUE THREAD

**Issue by M8kmyday** [mfem/mfem#3610]
Can the MixedCrossCurlIntegrator be used with a ParSesquilinearForm?  When I try it, I [not unexpectedly] get this error:

Assertion failed: (this->VerifyFiniteElementTypes(trial_fe, test_fe)) is false:
 --> MixedCrossCurlIntegrator:  Trial space must be a vector field in 3D with a curl and the test space must be a vector field
 ... in function: virtual void mfem::MixedVectorIntegrator::AssembleElementMatrix2(const mfem::FiniteElement&, const mfem::FiniteElement&, mfem::ElementTransformation&, mfem::DenseMatrix&)
 ... in file: fem/bilininteg.cpp:485

Since MixedCrossCurlIntegrator is a mixed operator, I expect that it would require a MixedBilinearForm object, but I do not see a "ParMixedSesquilinearForm".

I successfully use ParSesquilinearForm with CurlCurlIntegrator and VectorFEMassIntegrator in a 3D problem.  I am using VectorFEMassIntegrator in an approximate boundary condition, but I need to upgrade it to MixedCrossCurlIntegrator, and that is where I am running into the problem.  For reference, I am using the version of MFEM in mfem-submesh-nd-dev to enable SubMesh functionality with ND spaces for implementing 2D ports on a 3D space.

**Comment by mlstowell** [comment]
Hi, @M8kmyday,

The `MixedCrossCurlIntegrator` must act on an HCurl field but it's range can be either HCurl or HDiv. If you're range is HCurl you should be able to use this integrator with `ParSesquilinearForm`. If you need to use HDiv you'll need a `ParMixedBilinearForm`. You are correct that we do not currently have a `ParMixedSesquilinearForm` (unless @psocratis has added it in some branch and I have forgotten). However, these sesquilinear form classes are little more than wrappers around their real-valued counterparts so I'm sure you could write some custom code to produce an equivalent object.

Best wishes,
Mark

**Comment by M8kmyday** [comment]
Got it.  Thank you.

**Comment by M8kmyday** [comment]
I thought it would be straightforward, but I'm still having issues.  Here is the gist of it in a few lines:

    VectorConstantCoefficient vecNormal(normal);   // normal is a Vec(3)
    ConstantCoefficient one(1.0);

    ND_FECollection *fec_ND_test=new ND_FECollection(1,pmesh->Dimension());       // pmesh is a 3D mesh
    ParFiniteElementSpace *fespace_ND_test=new ParFiniteElementSpace(pmesh,fec_ND_test);

    ParMixedBilinearForm *pmblfTest=new ParMixedBilinearForm(fespace_ND_test,fespace_ND_test);
    pmblfTest->AddBoundaryIntegrator(new MixedCrossCurlIntegrator(*vccNormal),*border_attributes);     // (test 1) fails at Assemble
    //   pmblfTest->AddBoundaryIntegrator(new CurlCurlIntegrator(one),*border_attributes);                  // (test 2) runs
    //   pmblfTest->AddBoundaryIntegrator(new VectorFEMassIntegrator(*vccNormal),*border_attributes);       // (test 3) runs
    pmblfTest->Assemble();

Three AddBoundaryIntegrator tests are tried, two of which work.  The one that fails produces the error at Assembly:

Assertion failed: (this->VerifyFiniteElementTypes(trial_fe, test_fe)) is false:
 --> MixedCrossCurlIntegrator:  Trial space must be a vector field in 3D with a curl and the test space must be a vector field
 ... in function: virtual void mfem::MixedVectorIntegrator::AssembleElementMatrix2(const mfem::FiniteElement&, const mfem::FiniteElement&, mfem::ElementTransformation&, mfem::DenseMatrix&)
 ... in file: fem/bilininteg.cpp:485

All three integrators indicate that the range and domain is ND at https://mfem.org/bilininteg/, so I can't figure out why test 1 fails.  Isn't ND a vector field?

**Comment by mlstowell** [comment]
HI, @M8kmyday,

It fails because it's being used on a boundary where the reference space is not 3D.  I doubt that integrator was designed to work on boundaries. What boundary condition are you hoping to implement?

Best wishes,
Mark

**Comment by M8kmyday** [comment]
The boundary condition I need is the surface integral in:
![Screenshot from 2023-02-13 09-33-01](https://user-images.githubusercontent.com/90462987/232862913-7310f2e4-68c4-45a4-be5e-0ad9b3e4b5f5.png)
My thought is to follow your guidance in #2261; hence, the MixedCrossCurlIntegrator attempt.

**Comment by psocratis** [comment]
HI @M8kmyday,

You might find [this](https://github.com/mfem/mfem/blob/2db9acec152c7971a1e8e2eced3cfdbdfc69309f/examples/maxwell-solver/maxwell-impedanceBC.cpp#L117-L128) useful. This implements impedance BC for Maxwell.

Best,

Socratis

**Comment by M8kmyday** [comment]
Hi Socratis,

With Z=E/H and the FEM solution in E, the impedance calculation needs curl(E) to get H.  Roughly, the code appears to manually implement curl(E) through VectorFunctionCoefficients, then applies boundary integrators on the VectorFunctionCoefficients.  If this assessment is near the mark, then I should be able to adapt that code to implement the boundary condition I need since it also requires curl(E) and my FEM solution is in E.  If none of the existing BilinearForm Operators can be arm-twisted into implementing the needed boundary condition, then I can probably make this manual approach work.  I'm hoping to hear from Mark that there is a way to use an existing BilinearForm operator.

Thanks for the link.

Brian

**Comment by mlstowell** [comment]
Hi, @M8kmyday,

Unfortunately, that surface integral cannot be computed as a bilinear form applied to `E`. The reason is that we only have the boundary degrees of freedom of `E` to work with. What I mean is that we can compute the tangential derivatives of the tangential `E` field.  However, that integral requires the tangential derivatives of the normal component of `E` and the normal derivative of the tangential components of `E` neither of which are available.

This boundary integral is usually handled by supplying a known function in place of `n x Curl E` i.e. a surface current, or as @psocratis suggests, some known relationship between `E` and `H` i.e. an impedance relation.

Best wishes,
Mark

**Comment by M8kmyday** [comment]
Thanks for the background.  Is the limitation in applying the surface integral a limitation of the architecture of MFEM or fundamental to the finite element method in general?

**Comment by v-dobrev** [comment]
If you really need to implement such boundary bilinear term, you should be able to implement it as a `BilinearFormIntegrator` that implements the method:
```c++
   virtual void AssembleFaceMatrix(const FiniteElement &el1,
                                   const FiniteElement &el2,
                                   FaceElementTransformations &Trans,
                                   DenseMatrix &elmat);
```

You can add such `BilinearFormIntegrator` to your `BilinearForm` with the method `BilinearForm::AddBdrFaceIntegrator`.

**Comment by v-dobrev** [comment]
Hi @M8kmyday,

I watched earlier today your talk at the FEM seminar (I missed it originally due to a conflict) and decided to implement the boundary term you need for more general boundary conditions, as posted above and mentioned in your talk.

Note that I have not tested the code below, so let me know if you encounter any issues.

```c++
/** @brief The boundary bilinear form: \int_S Q(x)(n x curl(u)).v dS in 3D where
    both the trial, u, and the test, v, functions are in H(curl). */
/** This integrator should be added to the BilinearForm with the method
    BilinearForm::AddBdrFaceIntegrator(). */
class NCrossCurlBoundaryIntegrator : BilinearFormIntegrator
{
protected:
   Coefficient *Q;

public:
   /// If @a q is NULL, the coefficient is 1.
   NCrossCurlBoundaryIntegrator(Coefficient *q = nullptr)
      : Q(q) { }

   void AssembleFaceMatrix(const FiniteElement &el1,
                           const FiniteElement &el2,
                           FaceElementTransformations &Trans,
                           DenseMatrix &elmat) override;
};

void NCrossCurlBoundaryIntegrator::AssembleFaceMatrix(
   const FiniteElement &el1,
   const FiniteElement &el2,
   FaceElementTransformations &Trans,
   DenseMatrix &elmat)
{
   // Assuming 3D mesh; integrating over a boundary face.
   MFEM_VERIFY(el1.GetDim() == 3, "this integrator works only in 3D!");
   MFEM_VERIFY(Trans.Elem2No < 0, "interior faces are not supported!");
   MFEM_CONTRACT_VAR(el2);

   int nd = el1.GetDof();

   elmat.SetSize(nd);

   Vector n(3);
   DenseMatrix vshape(nd, 3), curl_shape(nd, 3), n_cross_curl(nd, 3);

   const IntegrationRule *ir = IntRule;
   if (ir == nullptr)
   {
      const int ir_order = 2*el1.GetOrder();
      ir = &IntRules.Get(Trans.GetGeometryType(), ir_order);
   }

   elmat = 0.0;
   for (int i = 0; i < ir->GetNPoints(); i++)
   {
      const IntegrationPoint &ip = ir->IntPoint(i);
      Trans.SetAllIntPoints(&ip);
      el1.CalcPhysVShape(*Trans.Elem1, vshape);
      el1.CalcPhysCurlShape(*Trans.Elem1, curl_shape);
      CalcOrtho(Trans.Jacobian(), n);
      real_t w = ip.weight;  // n is already scaled with the surface weight
      if (Q)
      {
         // evaluate Q through element 1
         w *= Q->Eval(*Trans.Elem1, Trans.GetElement1IntPoint());
      }
      n *= w;
      for (int j = 0; j < nd; j++)
      {
         real_t c[3] = { curl_shape(j,0), curl_shape(j,1), curl_shape(j,2) };
         n_cross_curl(j,0) = n[1]*c[2] - n[2]*c[1];
         n_cross_curl(j,1) = n[2]*c[0] - n[0]*c[2];
         n_cross_curl(j,2) = n[0]*c[1] - n[1]*c[0];
      }
      AddMultABt(vshape, n_cross_curl, elmat);
   }
}
```

**Comment by v-dobrev** [comment]
Maybe I misunderstood the actual terms you need to impose the b.c. at the ports -- I assumed you needed the bilinear form
$$\int_S Q(x) [\vec{n} \times (\nabla \times \vec{E})] \cdot \vec{W}\\, dS,$$ however, after looking at the talk more and reading some of the discussion here, I'm not so sure anymore.

My current understanding is that you want to apply the condition $$-\\frac{\partial \vec{E}_t}{\partial \vec{n}}=\gamma \vec{E}_t$$ on the subset of the boundary corresponding to the ports, and therefore, after using the identity $$\vec{n} \times (\nabla \times \vec{E}) = -\\frac{\partial \vec{E}_t}{\partial \vec{n}} + \nabla_t \vec{E}_n,$$ you need the bilinear form $$\int_S Q(x) \nabla_t \vec{E}_n \cdot \vec{W}\\,dS.$$ Is this correct?

**Comment by M8kmyday** [comment]
Hi Veselin,

 

The bilinear form $$\int_S Q(x) [\vec{n} \times (\nabla \times \vec{E})] \cdot \vec{W}\, dS,$$ is the most general formulation needed to complete the construction of the boundary value problem.  It would be applied to all ports, then the DOFs at the driving port would be set to values pulled from 2D port simulations.  I will give the class NCrossCurlBoundaryIntegrator : BilinearFormIntegrator from you prior email a try and let you know how it goes.

 

Given the prior lack of a bilinear form to implement $$\int_S Q(x) [\vec{n} \times (\nabla \times \vec{E})] \cdot \vec{W}\, dS,$$ I have been using the identity $$\vec{n} \times (\nabla \times \vec{E}) = -\frac{\partial \vec{E}_t}{\partial \vec{n}} + \nabla_t \vec{E}_n,$$ to instead implement $$\vec{n} \times (\nabla \times \vec{E}) = \gamma\vec{E}_t + \nabla_t \vec{E}_n.$$  The problem with this substitution is that $\nabla_t \vec{E}_n$ is not directly implementable with MFEM.  However, I did find a way to implement this by solving the 2D wave equation on the port with boundary integrators with $$\gamma\overline{E}_t+\nabla_t E_n=\frac{1}{\gamma}(\nabla_t \times \frac{1}{\mu_r} \nabla_t \times \overline{E}_t – k_{\circ}^2 \epsilon_{cr} \overline{E}_t).$$  This resolves the issue with $\nabla_t \vec{E}_n$, and discussion in my presentation on the slide “On the Neglected Gradient Term” no longer applies and there are no longer issues with TM modes.  This was a very big improvement.

 

There remains the issue of $\gamma$ appearing in the boundary condition, and this leads to an impedance mismatch for any other modes present on the port, such as for differential pairs, when the mode propagation constants are not equal.  I am currently working on that by a more general formulation for S-parameter extraction than I have used so far.  However, the new class NCrossCurlBoundaryIntegrator : BilinearFormIntegrator may address this problem more fundamentally by eliminating $\gamma$ from the boundary condition.

 

Thanks for the new class.  I will try it out.

 

Best Regards,

Brian

**Comment by M8kmyday** [comment]
Hi Veselin,

 

No success on a first try.  I copied your code into my source file and swapped out my boundary integrator, then I get an error on compilation:

 

port.cpp:5685:20: error: `class mfem::ParMixedBilinearForm’ has no member named `AddBdrFaceIntegrator’; did you mean `AddTraceFaceIntegrator’?

5685 | if (isReal) pmblf->AddBdrFaceIntegrator(new NCrossCurlBoundaryIntegrator(),*border_attributes);

      |                    ^~~~~~~~~~~~~~~~~~~~

      |                    AddTraceFaceIntegrator

 

I do not know what a Trace is, but I made the change to

 

if (isReal) pmblf->AddBdrTraceFaceIntegrator(new NCrossCurlBoundaryIntegrator(),*border_attributes);

 

Compiling again, I get the error:

 

port.cpp:5686:99: error: `mfem::BilinearFormIntegrator’ is an inaccessible base of `NCrossCurlBoundaryIntegrator’

5686 | if (isReal) pmblf->AddBdrTraceFaceIntegrator(new NCrossCurlBoundaryIntegrator(),*border_attributes);

 

I added “public” to the class definition:

 

class NCrossCurlBoundaryIntegrator : public BilinearFormIntegrator

 

and then everything compiles fine.  On execution, I get the run-time error:

 

MFEM abort: AssembleFaceMatrix (mixed form) is not implemented for this Integrator class.

... in function: virtual void mfem::BilinearFormIntegrator::AssembleFaceMatrix(const mfem::FiniteElement&, const mfem::FiniteElement&, const mfem::FiniteElement&, mfem::FaceElementTransformations&, mfem::DenseMatrix&)

... in file: fem/bilininteg.cpp:178

 

I am using ParMixedBilinearForm, so perhaps that is a source of problems.

 

Is there anything else I can try?

 

Brian

 

From: ***@***.*** ***@***.***> 
Sent: Monday, July 8, 2024 8:56 AM
To: 'mfem/mfem' ***@***.***>; 'mfem/mfem' ***@***.***>
Subject: RE: [mfem/mfem] ParSesquilinearForm and MixedCrossCurlIntegrator (Issue #3610)

 

  Hi Veselin,

 

The bilinear form $$\int_S Q(x) [\vec{n} \times (\nabla \times \vec{E})] \cdot \vec{W}\, dS,$$ is the most general formulation needed to complete the construction of the boundary value problem.  It would be applied to all ports, then the DOFs at the driving port would be set to values pulled from 2D port simulations.  I will give the class NCrossCurlBoundaryIntegrator : BilinearFormIntegrator from you prior email a try and let you know how it goes.

 

Given the prior lack of a bilinear form to implement $$\int_S Q(x) [\vec{n} \times (\nabla \times \vec{E})] \cdot \vec{W}\, dS,$$ I have been using the identity $$\vec{n} \times (\nabla \times \vec{E}) = -\frac{\partial \vec{E}_t}{\partial \vec{n}} + \nabla_t \vec{E}_n,$$ to instead implement $$\vec{n} \times (\nabla \times \vec{E}) = \gamma\vec{E}_t + \nabla_t \vec{E}_n.$$  The problem with this substitution is that $\nabla_t \vec{E}_n$ is not directly implementable with MFEM.  However, I did find a way to implement this by solving the 2D wave equation on the port with boundary integrators with $$\gamma\overline{E}_t+\nabla_t E_n=\frac{1}{\gamma}(\nabla_t \times \frac{1}{\mu_r} \nabla_t \times \overline{E}_t – k_{\circ}^2 \epsilon_{cr} \overline{E}_t).$$  This resolves the issue with $\nabla_t \vec{E}_n$, and discussion in my presentation on the slide “On the Neglected Gradient Term” no longer applies and there are no longer issues with TM modes.  This was a very big improvement.

 

There remains the issue of $\gamma$ appearing in the boundary condition, and this leads to an impedance mismatch for any other modes present on the port, such as for differential pairs, when the mode propagation constants are not equal.  I am currently working on that by a more general formulation for S-parameter extraction than I have used so far.  However, the new class NCrossCurlBoundaryIntegrator : BilinearFormIntegrator may address this problem more fundamentally by eliminating $\gamma$ from the boundary condition.

 

Thanks for the new class.  I will try it out.

 

Best Regards,

Brian

**Comment by v-dobrev** [comment]
Hi Brian,
I was assuming that you are using `ParBilinearForm`, however, the error message you posted shows that you are using `ParMixedBilinearForm`. Does that mean that your trial (for $\vec{E}$) and test (for $\vec{W}$) spaces are different? I assumed that they are both H-curl conforming, i.e. Nedelec. If that is not the case, what spaces are you using for $\vec{E}$ and $\vec{W}$?

**Comment by M8kmyday** [comment]
Something pushed me to ParMixedBilinearForm, but I do not remember what that is.  Maybe it was an experiment that I didn’t completely back out.  I’ll have to look to see if I can go back to ParBilinearForm.

 

Brian

**Comment by M8kmyday** [comment]
I swapped ParBilinearForm for ParMixedBilinearForm, and everything works fine.  I still have to add “public” to the class definition for NCrossCurlBoundaryIntegrator.

 

Running a straight section of rectangular waveguide, I get convergence difficulties for the 3D E-field solution.  Setting the convergence criteria very loose, I get a solution that shows the new boundary with NCrossCurlBoundaryIntegrator producing a non-physical field that results in a 100% reflection.  The attached screen shots show field plots for the new boundary and the existing boundary using the 2D wave equation solution described earlier.

 

I can think of three scenarios for the result:

1.	Incorrect usage of NCrossCurlBoundaryIntegrator in my code.  It is a very simple substitution to take out the existing boundary integrators and add the new one.  Seems hard to mess up, but possible.
2.	The new NCrossCurlBoundaryIntegrator is not a sufficient boundary condition to solve the problem.  This seems like a real possibility.  The current boundary condition forces the fields to a 2D configuration, while NCrossCurlBoundaryIntegrator does not.  For this problem, the fields in the 3D space are already in 2D configuration since there is no discontinuity, and NCrossCurlBoundaryIntegrator should just continue and support that.  This may be a bad assumption.
3.	There is a problem with NCrossCurlBoundaryIntegrator.  I can’t check that, but the code seems straightforward and compact.  Maybe the attached field plots will give a hint if there is a problem.

 

Brian

 

From: ***@***.*** ***@***.***> 
Sent: Tuesday, July 9, 2024 8:34 AM
To: 'mfem/mfem' ***@***.***>; 'mfem/mfem' ***@***.***>
Cc: 'Mention' ***@***.***>
Subject: RE: [mfem/mfem] ParSesquilinearForm and MixedCrossCurlIntegrator (Issue #3610)

 

Something pushed me to ParMixedBilinearForm, but I do not remember what that is.  Maybe it was an experiment that I didn’t completely back out.  I’ll have to look to see if I can go back to ParBilinearForm.

 

Brian

**Comment by v-dobrev** [comment]
Hi Brian, I don't see any attached plots on GitHub -- maybe you need to copy-paste them directly on GitHub?

**Comment by M8kmyday** [comment]
My internet is down, so I will post the screenshots when it comes up.BrianOn Jul 9, 2024, at 3:32 PM, Veselin Dobrev ***@***.***> wrote:﻿
Hi Brian, I don't see any attached plots on GitHub -- maybe you need to copy-paste them directly on GitHub?

**Comment by M8kmyday** [comment]
Here are the two plots I mentioned.

Current boundary condition using the 2D wave equation boundary:
![mag_E_current_BC](https://github.com/mfem/mfem/assets/90462987/a7ffb55e-f2f4-48e4-9a70-de3ba6b9e67a)

Boundary condition using the NCrossCurlBoundaryIntegrator:
![mag_E_NCrossCurlBoundaryINtegrator](https://github.com/mfem/mfem/assets/90462987/753d80be-878b-4874-93df-447b7e7323ca)

**Comment by M8kmyday** [comment]
Those plots are of |E| with 6th order elements.

**Comment by v-dobrev** [comment]
Hi Brian,

I'm trying to understand what boundary condition you want to impose on the port boundary. The boundary condition types that I understand how to impose all result in a weak formulation where the term $B$: $$B(\vec{E},\vec{W}) = \int_S Q(x) [\vec{n} \times (\nabla \times \vec{E})] \cdot \vec{W}\\, dS$$ is not needed. The b.c. types I'm referring to are:

1. Essential ("Dirichlet"-like) boundary condition: $\vec{E}_t = \vec{E}^{ext}_t$, where $\vec{E}^{ext}$ (or just its tangential component $\vec{E}^{ext}_t$) is given on a subset of the boundary $\Gamma_0 \subset \partial\Omega$. In this case, the test functions, $\vec{W}$, need to be taken to satisfy $\vec{W}_t = \vec{0}$ on $\Gamma_0$, so the term $B(\vec{E},\vec{W})$ is zero and does not appear in the weak formulation. In MFEM, this type of b.c. is imposed by modifying the matrix and the r.h.s. vector -- this is done automatically by one of the `FormLinearSystem` method, e.g. https://github.com/mfem/mfem/blob/988439f60a9902e29572b83dcb2a142eb8da3dbd/fem/bilinearform.hpp#L521-L523
where the essential boundary data is provided by the boundary dofs in the `Vector` `x`.

2. Natural ("Neumann"-like) boundary condition: $\vec{n} \times (\nabla \times \vec{E}) = \vec{F}_t$ where $\vec{F}$ (or just $\vec{F}_t$) is given on part of the boundary $\Gamma_1 \subset \partial\Omega$. The data $\vec{F}_t$ can also be given in the form $\vec{F}_t = \vec{n}\times\vec{G}$. In this case the term $B(\vec{E},\vec{W})$ is known and is moved to the r.h.s. of the weak formulation:

$$B(\vec{E},\vec{W}) = \int_{\Gamma_1} Q(x) \vec{F}_t \cdot \vec{W}\\, dS.$$

3. Mixed ("Robin"-like) boundary condition: $\vec{n} \times (\nabla \times \vec{E}) = \alpha\vec{E}_t + \vec{F}_t$ on part of the boundary $\Gamma_2\subset\partial\Omega$ where $\vec{F}_t$ is a given tangential field. In this case $B(\vec{E},\vec{W})$ is split into two terms, one goes on the l.h.s. and contributes to the matrix and the second one goes to the r.h.s:

$$B(\vec{E},\vec{W}) = \int_{\Gamma_2} Q(x) \alpha \vec{E}_t \cdot \vec{W}\\, dS + ~$$

$$ + \int_{\Gamma_2} Q(x) \vec{F}_t \cdot \vec{W}\\, dS$$

If the port boundary condition that you want to impose does not fall into one of these types, what does it look like on PDE level?

**Comment by M8kmyday** [comment]
By assuming a transmission line or waveguide mode with a dependence of $e^{-\gamma n}$, then with the help of a vector identity
$`$\hat{n}\times\nabla\times\overline{E}=-\frac{\partial\overline{E}_t}{\partial{n}}+\nabla_t E_n=\gamma \overline{E}_t + \nabla_t E_n.$`$
The tangential part of the 2D wave equation at the port is
$`$\nabla_t \times \frac{1}{\mu_r} \nabla_t \times \overline{E}_t - \gamma^2\overline{E}_t-\gamma\nabla_t E_n=k_{\circ}^2 \epsilon_{cr} \overline{E}_t,$`$
so substituting yields an absorbing boundary condition for the port as 
$`$\gamma \overline{E}_t + \nabla_t E_n=\frac{1}{\gamma}(\nabla_t \times \frac{1}{\mu_r} \nabla_t \times \overline{E}_t - k_{\circ}^2 \epsilon_{cr} \overline{E}_t).$`$
This is in the form of a mixed boundary condition, and I find that it works quite well as long as all modes at the boundary have the same $\gamma$.  I am trying to eliminate $\gamma$ from the absorbing boundary condition so that it is equally effective for any mode.

**Comment by v-dobrev** [comment]
Let me see if I understand you correctly: is it true then that (A) you impose natural boundary condition (2 in my list above) given by $\vec{n} \times (\nabla \times \vec{E}) = \vec{F}_t$ on the port where $\vec{F}_t$ is computed by differentiating (on the boundary) a previously computed (somehow, I'm not sure how) $\vec{E}_t$:

$$\vec{F}_t = \frac{1}{\gamma}\left(\nabla_t \times \frac{1}{\mu_r}\nabla_t \times \vec{E}_t - k\_{\circ}^2 \epsilon\_{cr} \vec{E}_t \right)?$$

Or, is it true that (B) you impose the boundary condition

$$\vec{n} \times (\nabla \times \vec{E}) = \frac{1}{\gamma}\left(\nabla_t \times \frac{1}{\mu_r}\nabla_t \times \vec{E}_t - k\_{\circ}^2 \epsilon\_{cr} \vec{E}_t \right)$$

where the r.h.s. uses the tangential component of the unknown $\vec{E}$? I suppose in this case, this b.c. leads to a contribution to the bilinear form and the system matrix, however, I'm not sure how the term $(\nabla_t \times \nabla_t \times)$ is treated on the boundary.

**Comment by M8kmyday** [comment]
I am doing (B).  The r.h.s is implemented with a CurlCurlIntegrator and a VectorFEMassIntegrator on the ParBilinearForm with the AddBoundaryIntegrator method.
