### ISSUE TITLE
Convert/project NURBSFECollection to FEM FiniteElementCollection

### ISSUE THREAD

**Issue by JacobLotz** [mfem/mfem#3612]
I am trying to do a part of my NURBS-based IgA computation in MFEM using FEA. Some background: the idea is to be able to use the `SampleMeshManager` functions for hyper-reduction in [libROM](https://github.com/LLNL/libROM) for evaluating the non-linear part of the reduced equations. This will introduce a small error, but that is problably very small.

I started an idea of an implementation for the projection of a IgA mesh on a FEM mesh and luckily @v-dobrev indicated that this already had been implemented.  For future reference I will quote @v-dobrev his suggestion:

> I'm not sure if this is different but you can already convert (interpolate) NURBS meshes to normal meshes by just calling `Mesh::SetCurvature`. Also, you can convert/interpolate NURBS `GridFunctions,` e.g. by wrapping them as `GridFunctionCoefficient` and then projecting them to another `GridFunction`.

Now I realize that it might be better to convert/project a `NURBSFECollection` to a FEM `FiniteElementCollection`. Does anyone now if something similar as the above is possible for a `FiniteElementCollection` or `FiniteElementSpace`?

**Comment by v-dobrev** [comment]
I don't understand: what do you mean by  _"convert/project a `NURBSFECollection` to a FEM `FiniteElementCollection`"?_

**Comment by JacobLotz** [comment]
Hopefully this will clarify. I am afraid I am mixing some names.

To do a part of the computation in a FEM discretisation instead of an IgA discretisation I currently do the following:

1. I load a NURBS mesh, create a `NURBSFECollection` and with it a `FiniteElementSpace`.

1. I do part of the computation with this `NURBSFECollection` in the `FiniteElementSpace` and generate a result.

1. I copy and convert the NURBS mesh to FEM mesh and create a `H1_FECollection`. 
 
1. With the `H1_FECollection` I create a `FiniteElementSpace`.

1. I do another part of the computation with the last `FiniteElementSpace`. Data goes back and forward between the two `FiniteElementSpace`s I have just created.

My question now in other words would be: Is it possible to skip a part of step 3, creating the FEM mesh, and directly convert the `NURBSFECollection` to a `H1_FECollection`? This should be something as `Mesh::SetCurvature` for meshes, but then for `FiniteElementCollections`. Basically: adding discontinuities in the NURBS shape functions and creating Finite Elements.

**Comment by v-dobrev** [comment]
There is no special rule really that tells you how to "convert" a `NURBSFECollection` to an `H1_FECollection` -- in general, the NURBS basis functions cannot be exactly represented by H1 basis functions of certain order. However, if the weights in the NURBS space are all 1, then the NURBS basis functions are actually just splines and then they can be represented exactly in the H1 FE space of the same order (degree) as the NURBS space.

Basically, it is up to you to choose what order you use when you call `SetCurvature` and when you create the `H1_FECollection`. For example, you can query the order of the NURBS mesh (and/or NURBS space, if that is different) and use that in both places.

If you need exact representation of the NURBS space with reduced, C_0, continuity across elements and the weights in the NURBS space are not 1 (or equivalently some fixed constant) then you'll need to use NURBS objects and reduce the continuity by adding appropriately repeated knots to the knot vectors.

**Comment by JacobLotz** [comment]
@v-dobrev considering the projection of an IgA Gridfunction on a FEM Gridfunction as in  

> Also, you can convert/interpolate NURBS GridFunctions, e.g. by wrapping them as GridFunctionCoefficient and then projecting them to another GridFunction.

I thought of an approach such as below. The IgA gridfunction is wrapped as a `GridFunctionCoefficient` and evaluated in `LinearForm b`. The idea was to use the `GridFunctionCoefficient` just as any other coefficient. 

I fear that an approach as below does not work. From what I understand, this will only work if the `GridFunctionCoefficient` in `LinearForm b` uses the same mesh as the `IntegrationPoint` on which the `GridFunctionCoefficient` is evaluated uppon assembly of `LinearForm b`.

Did you have the same approach in mind?

```
void ProjectIgASolution(ParFiniteElementSpace *FEMfes,
                        GridFunctionCoefficient f_rhs,
                        ParGridFunction &u)
{
   // Define and assemble linear form/rhs
   ParLinearForm b(FEMfes);
   b.AddDomainIntegrator(new DomainLFIntegrator(f_rhs));
   b.Assemble();

   // Define and assemble bilinear form
   ParBilinearForm a(FEMfes);
   a.AddDomainIntegrator(new MassIntegrator());
   a.Assemble();

   // Create linear problem
   Array<int> ess_tdof_list(0);
   HypreParMatrix A;
   Vector B, X;
   a.FormLinearSystem(ess_tdof_list, u, b, A, X, B);

   // Set solver and preconditioner
   HypreBoomerAMG amg(A);
   amg.SetPrintLevel(0);
   HyprePCG pcg(A);
   pcg.SetTol(1e-15);
   pcg.SetMaxIter(250);
   pcg.SetPrintLevel(0);
   pcg.SetPreconditioner(amg);

   // Solve and get solution
   pcg.Mult(B, X);
   a.RecoverFEMSolution(X, b, u);
}

int main() // part of
{
   // We have read and created a NURBS mesh and finite element space
   // IgA Gridfunction (fes is IgA finite element space). This will contain our IgA solution.
   ParGridFunction *u  = new ParGridFunction(fes);

   // We have solved system of equations and we have a solution in u. Now we want to project the solution in u onto a FEM gridfunction

   // Deep copy of mesh (mesh is NURBS mesh)
   meshFEM = new ParMesh(*mesh, true);

   // IgA mesh to FEM mesh and create FEM FESpace
   meshFEM->SetCurvature(order);
   FiniteElementCollection *fecFEM = new H1_FECollection(order, dim);
   ParFiniteElementSpace * fespaceFEM = new ParFiniteElementSpace(meshFEM, fecFEM);

   // IgA Gridfunction coefficient
   GridFunctionCoefficient f_rhs(u);

   // FEM gridfunction
   ParGridFunction uFEM = ParGridFunction(fespaceFEM);

   ProjectIgASolution(fespaceFEM, f_rhs, uFEM);
}
```

**Comment by v-dobrev** [comment]
Your function `ProjectIgASolution` is performing the $L_2$-projection of the `f_rhs` on the space `FEMfes`. This should work for any `Coefficient` sub-class with some assumptions depending on the sub-class. For example, when the `Coefficient` is a `GridFunctionCoefficient` then it has to be on the same mesh as the `FEMfes`. However, the actual `Mesh` objects can be different as long as they have the same element connectivity which is the case in the code snippet you posted. So I expect the code you posted to work. There will be some approximation of the physical space locations of the quadrature points due to the interpolation of the geometry in the conversion from NURBS- to $H^1$-elements in the mesh, however, the error should be on the same order as the order of the $L_2$ projection (as long as the FEM mesh order is the same as the FEM solution space order).

Did you try the above code and it did not work? In principle, I think it should work.

Instead of performing $L_2$ projection, you can also just perform interpolation inside `ProjectIgASolution`: basically that can be done with a single call to `u.ProjectCoefficient(f_rhs)`.

**Comment by JacobLotz** [comment]
@v-dobrev both `ProjectIgASolution` and  `u.ProjectCoefficient(f_rhs)` fail uppon evaluating the `GridFunctionCoefficient`.
I think the following you described is the `else` in `GridFunctionCoefficient::Eval`  and that is what we want to evaluate (and do evaluate).
> However, the actual Mesh objects can be different as long as they have the same element connectivity which is the case in the code snippet you posted.

```ruby
double GridFunctionCoefficient::Eval (ElementTransformation &T,
                                      const IntegrationPoint &ip)
{
   Mesh *gf_mesh = GridF->FESpace()->GetMesh();
   if (T.mesh == gf_mesh)
   {
      return GridF->GetValue(T, ip, Component);
   }
   else
   {
      IntegrationPoint coarse_ip;
      ElementTransformation *coarse_T = RefinedToCoarse(*gf_mesh, T, ip, coarse_ip);
      return GridF->GetValue(*coarse_T, coarse_ip, Component);
   }
}
```

The code fails in the `else` at `Mesh::GetRefinementTransforms()` in `RefinedToCoarse`
```ruby
ElementTransformation *RefinedToCoarse(
   Mesh &coarse_mesh, const ElementTransformation &T,
   const IntegrationPoint &ip, IntegrationPoint &coarse_ip)
{
   Mesh &fine_mesh = *T.mesh;
   // Get the element transformation of the coarse element containing the
   // fine element.
   int fine_element = T.ElementNo;
   const CoarseFineTransformations &cf = fine_mesh.GetRefinementTransforms(); 
   ...
}
```

Where it fails the MFEM verify in

```ruby
const CoarseFineTransformations& Mesh::GetRefinementTransforms()
{
   MFEM_VERIFY(GetLastOperation() == Mesh::REFINE, "");
   ...
}
```
with
```
Verification failed: (GetLastOperation() == Mesh::REFINE) is false:
```
This is problably because a relation between a fine mesh and a courser mesh (before refinement) does not exist. 
I have the idea that this is due to the NURBS origin?

**If I apply a uniform refinement  after `SetCurvature` both approaches work.** 

```
void ProjectIgASolution(ParFiniteElementSpace *FEMfes,
                        GridFunctionCoefficient f_rhs,
                        ParGridFunction &u)
{
            ...
            // Projection to FEM mesh
            meshFEM->SetCurvature(order);
            meshFEM->UniformRefinement(1);
            ...
}
```
But then I have an unfavourable fine mesh.
 An easy (and ugly) fix is to apply one uniform refinement less on the NURBS mesh before creating the FEM mesh with `SetCurvature` and applying a uniform refinement on both afterwards. The problem with this is that for the IgA meshes we usually do not use uniform refinement but a knot insert. So this is unfavourable.

**Comment by v-dobrev** [comment]
Okay, I see. The change to check for a different mesh object in `GridFunctionCoefficient::Eval` is fairly recent (PR #2656) and has this undesired effect. We should be able to tweak the logic there to support the use case you have.

@pazner, the use of `GridFunctionCoefficient::Eval` with a `GridFunction` on different mesh assumes that `T.mesh` is a refinement of the mesh of the `GridFunction` being evaluated. In the case above, `T.mesh`is a copy of the mesh of the `GridFunction` and there are no `RefinementTransforms` in the "fine" mesh as expected by the current implementation of `GridFunctionCoefficient::Eval`. Do you have any ideas how to tweak the logic to support this use case?

**Comment by v-dobrev** [comment]
Maybe we can just add a check if the meshes have the same number of elements?

**Comment by pazner** [comment]
> Maybe we can just add a check if the meshes have the same number of elements?

This seems like the simplest/most straightforward solution, and it should make the behavior exactly compatible with what it was before `GridFunctionCoefficient::Eval` supported refined meshes.

**Comment by v-dobrev** [comment]
Okay, so @JacobLotz, can you try replacing this line
```c++
   if (T.mesh == gf_mesh)
```
with
```c++
   if (T.mesh == gf_mesh || T.mesh->GetNE() == gf_mesh->GetNE())
```
I expect this will fix the issue you saw and we can just add this change in a PR, either a new one or a PR that you are working on.

**Comment by JacobLotz** [comment]
@v-dobrev I am away from office and it seems to be difficult to reproduce this error as I seem to have to little memory in my laptop to use the same input files. I will get back to you as soon as I know!
