### ISSUE TITLE
Concentrated load and cohesive surfaces for solid mechanics problems

### ISSUE THREAD

**Issue by queen333597** [mfem/mfem#3617]
I see how in Example 2 (and other examples) a uniform load on a boundary surface is applied for linear elasticity. Is there a way to apply concentrated load (force applied at one node)?
Also, is there a way to define a certain type of interaction between the two materials (such as cohesive surfaces, frictionless, etc.)?

**Comment by v-dobrev** [comment]
You can apply a point force using a vector delta coefficient, e.g. in `ex2.cpp`/`ex2p.cpp` you can add
```c++
   VectorDeltaCoefficient point_force(dim);
   {
      Vector dir(dim);
      dir = 0.0;
      dir[dim-1] = -1.0e-2;

      Vector loc(dim);
      loc = 0.0;
      loc[0] = 8.0;

      point_force.SetDirection(dir);
      point_force.SetDeltaCenter(loc);
   }
```
and then replace the boundary force added using
```c++
      b->AddBoundaryIntegrator(new VectorBoundaryLFIntegrator(f));
```
with the point force using
```c++
      b->AddDomainIntegrator(new VectorDomainLFIntegrator(point_force));
```

Regarding the handling of interactions between the two materials: I'm not sure what the mathematical description of such interactions is; it may be possible to handle such models but it may not be straightforward.

**Comment by termi-official** [comment]
Depending on the exact formulation you can implement cohesive surfaces, but it will not be the usual implementation with cohesive elements. Basically you can construct [submeshes](https://docs.mfem.org/html/classmfem_1_1SubMesh.html) for each region. AFAIK there is no integrator interface over the interface between submeshes yet, so you can try to use the [transfermap](https://docs.mfem.org/html/classmfem_1_1TransferMap.html) to map your subdomain solutions between the subregions. This is not clean and performance is suboptimal, but, depending on your exact formulation, this can already work.

**Comment by queen333597** [comment]
Thanks for the explanation.
