### ISSUE TITLE
Restart capability with serial examples

### ISSUE THREAD

**Issue by queen333597** [mfem/mfem#3620]
Example 6p demonstrates restarting from a checkpoint. Is it possible to restart a serial simulation? How could that be done?

**Comment by vladotomov** [comment]
Hi @queen333597, you should be able to do it similarly by using the serial mesh constructor:
`Mesh::Mesh(std::istream &input, int generate_edges, int refine, bool fix_orientation)`
Printing the mesh should also use the serial version:
`virtual void Print(std::ostream &os = mfem::out) const`

**Comment by queen333597** [comment]
Thank you very much! That worked perfectly.
