### ISSUE TITLE
Solving nonlinear equations with Newton's method (+fully coupled scheme)

### ISSUE THREAD

**Issue by CINTROINI** [mfem/mfem#3622]
Hi all,

I am currently working on nonlinear system given by the following general form :
 
```
F(u,v) = (F1(u,v),F2(u,v))^T = 0
```

I already solved the case "F(u,v) = F1(u,v)=0"  with a Newton's method following  ex10 but when F is a vector, I don't know how  modify `AssembleElementVector` and `AssembleElementGrad`. 

I don't want to use a partionned scheme but a fully coupled scheme in order to calculate u and v with the same Newton's algorithm.

Do I need to implement a `NonlinearFormIntegrator` associated to F1 and another associated to F2, and afterwards assemble them into a suitable vector or matrix? 

Or, is there specific NonLinear integrator dedicated to BlockVector unknown?

Thanks,

Clément

**Comment by v-dobrev** [comment]
One option is to use `(Par)BlockNonlinearForm`.

Another option is to write a simple class (like `ReducedSystemOperator` in `ex10`/`ex10p` but that does not perform any reduction of the nonlinear system). This simple class can use `(Par)NonlinearForm`s and/or `(Par)BilinearForm`s for its blocks. Depending on the nonlinearities, you may be able to use class `BlockOperator` too.

**Comment by CINTROINI** [comment]
Thanks for your reply. `(Par)BlockNonlinearForm` should do the trick. I test and go back to you if I have futher  any questions.
