### ISSUE TITLE
MFEM with MUMPS and "Out of core factorization and solve" error

### ISSUE THREAD

**Issue by sp3c333** [mfem/mfem#3623]
Hello,

I am enabling the mumps' option : ICNTL(22)=0 -> ICNTL(22)=1 in mumps.cpp.

However after using the following code: 

        a->Assemble();        
        a->FormLinearSystem(ess_tdof_list, u, b, Ah, U, B);
        cout << "mumps_detected" << endl;
        HypreParMatrix* A = Ah.As<ComplexHypreParMatrix>()->GetSystemMatrix();
        cout << "GetSystemMatrix_done" << endl;               
        MUMPSSolver mumps;
        mumps.SetPrintLevel(0);
        //mumps.SetParameters();
        mumps.SetMatrixSymType(MUMPSSolver::MatType::UNSYMMETRIC);
        cout << "SetMatrixSymType_done" << endl;
        mumps.SetOperator(*A);
        cout << "SetOperator_done" << endl;
        mumps.Mult(B, U);
        cout << "Mult_done" << endl;

I get the following error message: 

mumps_detected
GetSystemMatrix_done
SetMatrixSymType_done
           0 : PB in MUMPS_LOW_LEVEL_INIT_OOC_C
           0 : Problem while opening OOC file
 On return from DMUMPS, INFOG(1)=             -90
 On return from DMUMPS, INFOG(2)=               0
SetOperator_done
 On return from DMUMPS, INFOG(1)=              -3
 On return from DMUMPS, INFOG(2)=               3
Mult_done

with infog(1)=-90 corresponding to error in out of core management.

Could you please help me to solve this problem, it seems there is a problem at the initialisation of my "out of core management" ?

Best regards.

**Comment by v-dobrev** [comment]
You may want to try the in-review PR that updates the MUMPS support in MFEM -- PR #3082.
