### ISSUE TITLE
Implementation of HDG

### ISSUE THREAD

**Issue by YHDAUT** [mfem/mfem#3627]
Hi @mfem team, 

may I sincerely ask if there is any HDG implementation in mfem?  I would like to learn and implement it for my particular applications. 

Thanks

**Comment by v-dobrev** [comment]
Take a look at the HDG branch: https://github.com/mfem/mfem/tree/hdg and the examples in `examples/hdg_*.cpp`.

**Comment by YHDAUT** [comment]
Thank you very much @v-dobrev  for pointing out this branch to me.  I will take a close look to this package, it may take a while.

**Comment by YHDAUT** [comment]
Hi @v-dobrev ,

I tried to clone 

https://github.com/mfem/mfem.git

from  https://github.com/mfem/mfem/tree/hdg 

Unfortunately, it seems there is no hdg examples therein.  

I wonder if this is the right repository for hdg ..

Thanks

**Comment by jandrej** [comment]
How about a `git checkout hdg` in your cloned folder?

**Comment by YHDAUT** [comment]
Thanks a lot @jandrej .  Now, I can see those hdg examples in the folder example

May I ask if  these examples are parallel versions.

hdg_advection.cpp
hdg_advectionp.cpp


Unfortunately,  I got the following compiling warnings which seems has problem with SetZeroInintialIterate() 

>hdg_advectionp.cpp: In function ‘int main(int, char**)’:
>hdg_advectionp.cpp:362:43: warning: ‘void mfem::HypreGMRES::SetZeroInintialIterate()’ is deprecated >[-Wdeprecated->declarations]
>  362 |          itsolver->SetZeroInintialIterate();
>      |                                           ^

>In file included from ../linalg/complex_operator.hpp:18,
>                 from ../linalg/linalg.hpp:21,
>                 from ../mfem.hpp:43,
>                 from hdg_advectionp.cpp:34:
>../linalg/hypre.hpp:1308:25: note: declared here
> 1308 |    MFEM_DEPRECATED void SetZeroInintialIterate() { iterative_mode = false; }
>      |                         ^~~~~~~~~~~~~~~~~~~~~~
>mpicxx  -O3 -std=c++11 -I.. -I../../hypre/src/hypre/include -I../../metis-5.1.0/include hdg_poissonp.cpp -o hdg_poissonp >-L.. -lmfem -L../../hypre/src/hypre/lib -lHYPRE -L../../metis-5.1.0/lib -lmetis -lrt
>hdg_poissonp.cpp: In function ‘int main(int, char**)’:
>hdg_poissonp.cpp:375:38: warning: ‘void mfem::HyprePCG::SetZeroInintialIterate()’ is deprecated >[-Wdeprecated->declarations]
>  375 |          pcg->SetZeroInintialIterate();
>      |                                      ^

>In file included from ../linalg/complex_operator.hpp:18,
>                 from ../linalg/linalg.hpp:21,
>                 from ../mfem.hpp:43,
>                 from hdg_poissonp.cpp:39:
>../linalg/hypre.hpp:1244:25: note: declared here
> 1244 |    MFEM_DEPRECATED void SetZeroInintialIterate() { iterative_mode = false; }

**Comment by YHDAUT** [comment]
Hi, 
still some compiling issues with make hdg_poissonp:

mpicxx  -O3 -std=c++11 -I.. -I../../hypre/src/hypre/include -I../../metis-5.1.0/include hdg_poissonp.cpp -o hdg_poissonp -L.. -lmfem -L../../hypre/src/hypre/lib -lHYPRE -L../../metis-5.1.0/lib -lmetis -lrt
hdg_poissonp.cpp: In function ‘int main(int, char**)’:
hdg_poissonp.cpp:376:38: warning: ‘void mfem::HyprePCG::SetZeroInintialIterate()’ is deprecated [-Wdeprecated-declarations]
  376 |          pcg->SetZeroInintialIterate();
      |                                      ^
In file included from ../linalg/complex_operator.hpp:18,
                 from ../linalg/linalg.hpp:21,
                 from ../mfem.hpp:43,
                 from hdg_poissonp.cpp:39:
../linalg/hypre.hpp:1244:25: note: declared here
 1244 |    MFEM_DEPRECATED void SetZeroInintialIterate() { iterative_mode = false; }

I am in the branch hdg and have the newest version by git pull.

Thanks.

**Comment by v-dobrev** [comment]
This is just a warning: there is a typo in the name of the function `SetZeroInintialIterate` which is why it is marked as deprecated now and the new name has the correct spelling: `SetZeroInitialIterate`.

To get rid of the warning just replace `SetZeroInintialIterate` with `SetZeroInitialIterate` in `hdg_poissonp.cpp`.

**Comment by YHDAUT** [comment]
Thank you @v-dobrev .  it stars to run now,  but I got degenerated convergence rates:

mpirun -np 2 hdg_poissonp -o 5 -r 1 -tr 4 -no-vis

-----------------------
level  u_l2errors  order   q_l2errors  order   mean_l2errors  order u_star_l2errors   order
-----------------------
  0   1.16e-06    -               1.06e-05      -             1.63e-10     -             9.04e-08     -      
  1   1.84e-08  5.9756      1.68e-07      5.9785   5.97e-13   8.0955   7.06e-10   6.9993
  2   2.89e-10  5.9923      2.64e-09      5.9938   9.47e-13   -0.6650   5.63e-12   6.9704
  3   6.57e-12  5.4602      1.28e-10      4.3633   3.25e-12   -1.7805   4.76e-12   0.2423

Almost all the convergence degenerates a lot from level 2 to level 3.

Thanks
