### ISSUE TITLE
Relationship between quadrature space, L2 element nodes and integration rules

### ISSUE THREAD

**Issue by termi-official** [mfem/mfem#3629]
Hi everyone!

I tried for quite some time to figure out how the relationship between quadrature space, L2 element nodes and integration rules are, implementation-wise, but I am still not super sure about what guarantees are provided (if any). Let me try to formulate the problem which I have and I can transfer the answer into the docs.

Basically I my problems have some variables on the quadrature points (basically equations which have time derivatives, but no spatial derivatives or "point-wise ODEs"), so my first guess was always that `QuadratureSpace` might be the correct object here in the approximation. However, QuadratureSpace does not play well with AMR. Since I could not find an easy way to fix this with the user-facing part of MFEM I went ahead and tried to use L2 FE collections instead, which I understand as basically as a quadrature space+an attached interpolation operator. This now does also play well with AMR (because we have well-defined interpolations). However, I am not super confident if there is any strong guarantee that an L2 FE does **always** match its corresponding `QuadratureRule` instance. The problem here is that I am able to grab the nodes of the finite element as a quadrature rule via `fe->GetNodes()`, but the weights are empty. With this context given I have some questions:
1. Is `QuadratureSpace` the correct object for the management of equations (and their solutions) at quadrature points?
2. If so, what is the recommended way to transfer the associated solution during refinement, derefinement and rebalancing operations? 
3. How can I get the weights of the canonical quadrature rule associated to an L2 FE? To be more specific, if I have e.g. Lagrange polynomials with GLL nodes, how can I get the GLL integration rule associated to these nodes?
4. If I have `vdim>1` for an element from an L2 collection, then I think the docs for the ordering convention are slightly ambiguous (i.e. https://docs.mfem.org/html/classmfem_1_1Ordering.html#ad543b8eddc91d2d282374bd9cf44818c)
```cpp
#include "mfem.hpp"
#include <iostream>


using namespace std;
using namespace mfem;

int main(int argc, char *argv[]) {
  const char *mesh_file = "../data/inline-segment.mesh";
  int order = 1;

  OptionsParser args(argc, argv);
  args.AddOption(&mesh_file, "-m", "--mesh", "Mesh file to use.");
  args.AddOption(&order, "-o", "--order",
                   "Finite element order (polynomial degree).");
  args.Parse();
  if (!args.Good()) {
    args.PrintUsage(cout);
    return 1;
  }
  args.PrintOptions(cout);

  Mesh *mesh = new Mesh(mesh_file, 1, 1);
  int dim = mesh->Dimension();
  {
    L2_FECollection fec(order, dim);
    FiniteElementSpace fespace(mesh, &fec, 2,
                                mfem::Ordering::byVDIM);

    Array<int> dofs;
    fespace.GetElementVDofs(0, dofs);
    dofs.Print(); // 0 2 1 3
  }
  {
    L2_FECollection fec(order, dim);
    FiniteElementSpace fespace(mesh, &fec, 2,
                                mfem::Ordering::byNODES);

    Array<int> dofs;
    fespace.GetElementVDofs(0, dofs);
    dofs.Print(); // 0 1 16 17
  }
  return 0;
}

```
If I understand correctly, then here the output of `dofs.Print()` on the code snippet above (using 8 1D segments with linear Lagrange ansatz) is of the format:
```
[node=0, vdim=0] [node=0, vdim=1] [node=1, vdim=0] [node=1, vdim=1]
```
However, if my "inner loop" is vdim, then I would expect exactly the output of `mfem::Ordering::byNODES` for the FE space with `mfem::Ordering::byVDIM`,
since
```cpp
for(int node=0; node<nodes; node++) {
    for(int dim=0; dim<vdim; dim++) {
        std::cout << "node=" << node << " dim=" << dim << " dof=" << dofs[node*vdim+dim] << " ";
    }
}
```
what am I missing here?

Thanks in advance for reading all of this!

**Comment by pazner** [comment]
Hi @termi-official,

If I understand correctly, you want to be able to transfer/interpolate between "quadrature spaces" defined on refined/derefined AMR meshes.

If this is correct, then to me it sounds like using an L2 space will be the most straightforward, since it should have all of that functionality built-in.

> 3. How can I get the weights of the canonical quadrature rule associated to an L2 FE? To be more specific, if I have e.g. Lagrange polynomials with GLL nodes, how can I get the GLL integration rule associated to these nodes?

I would do something like this (not so elegant, I know…)

```c++
IntegrationRules irs(0, Quadrature1D::GaussLobatto);
const IntegrationRule &ir = irs.Get(mesh.GetElementGeometry(0),
                                    2*(order+1) - 3);
```

> 4. If I have `vdim>1` for an element from an L2 collection, then I think the docs for the ordering convention are slightly ambiguous (i.e. https://docs.mfem.org/html/classmfem_1_1Ordering.html#ad543b8eddc91d2d282374bd9cf44818c)
> However, if my "inner loop" is vdim, then I would expect exactly the output of `mfem::Ordering::byNODES` for the FE space with `mfem::Ordering::byVDIM`, since […]
> what am I missing here?

I'm not sure I completely understand the question, but the `Ordering` has an effect only on the "global" DOF ordering in the FE space, and not of the element-local ordering of the DOFs returned by `GetElementVDofs`. In particular, `GetElementVDofs` will always return an array where the vdim is the "outer dimension" and the node index is the "inner dimension", regardless of what `Ordering` the space uses. Does that help?

**Comment by termi-official** [comment]
Thanks for the quick response @pazner ! 

> If I understand correctly, you want to be able to transfer/interpolate between "quadrature spaces" defined on refined/derefined AMR meshes.

Yes, I really "just" want to transfer quadrature data during AMR (and understanding guarantees from objects of these classes).


> > 3. How can I get the weights of the canonical quadrature rule associated to an L2 FE? To be more specific, if I have e.g. Lagrange polynomials with GLL nodes, how can I get the GLL integration rule associated to these nodes?
> 
> I would do something like this (not so elegant, I know…)
> 
> ```c++
> IntegrationRules irs(0, Quadrature1D::GaussLobatto);
> const IntegrationRule &ir = irs.Get(mesh.GetElementGeometry(0),
>                                     2*(order+1) - 3);
> ```

Is this guaranteed to always match `fespace.GetFE(element_index)->GetNodes();` and hence the dofs of the (nodal) finite element space? To elaborate, I want abuse the property that for standard nodal Galerkin ansatz the shape and test functions are 1 at their nodes and 0 on all other nodes to "diagonalize" operators (similar to diagonal mass matrices found in spectral element methods).

> > 4. If I have `vdim>1` for an element from an L2 collection, then I think the docs for the ordering convention are slightly ambiguous (i.e. https://docs.mfem.org/html/classmfem_1_1Ordering.html#ad543b8eddc91d2d282374bd9cf44818c)
> >    However, if my "inner loop" is vdim, then I would expect exactly the output of `mfem::Ordering::byNODES` for the FE space with `mfem::Ordering::byVDIM`, since […]
> >    what am I missing here?
> 
> I'm not sure I completely understand the question, but the `Ordering` has an effect only on the "global" DOF ordering in the FE space, and not of the element-local ordering of the DOFs returned by `GetElementVDofs`. In particular, `GetElementVDofs` will always return an array where the vdim is the "outer dimension" and the node index is the "inner dimension", regardless of what `Ordering` the space uses. Does that help?

That definitely helps and clears up some confusion! It also makes sense, now that I think about it. Thanks!

**Comment by pazner** [comment]
> Is this guaranteed to always match `fespace.GetFE(element_index)->GetNodes();` and hence the dofs of the (nodal) finite element space? To elaborate, I want abuse the property that for standard nodal Galerkin ansatz the shape and test functions are 1 at their nodes and 0 on all other nodes to "diagonalize" operators (similar to diagonal mass matrices found in spectral element methods).

I don't know how strong the guarantee is, but I have relied on it in the past (for quads/hexes).

**Comment by termi-official** [comment]
For interested readers, this guarantee is not given for tet.
