### ISSUE TITLE
Is it possible to use custom quadrature rules?

### ISSUE THREAD

**Issue by ataber** [mfem/mfem#364]
Hello, I'm trying to implement a cut-cell-type of element, and in order to do that I need access to add my own custom quadrature points and weights. Does MFEM expose such functionality? Thanks!

**Comment by tzanio** [comment]
Absolutely! See the`intrules.hpp` and `intrules.cpp` files in the `fem/` directory.

**Comment by tzanio** [comment]
Closing this issue now. Feel free to reopen if you have additional questions.
