### ISSUE TITLE
inconsistent norms in linear and nonlinear solvers leads to nonconvergence

### ISSUE THREAD

**Issue by samuelpmishLLNL** [mfem/mfem#3641]
`mfem::GMRESSolver` and `mfem::CGSolver` measure the residual norm after applying the preconditioner, while `mfem::NewtonSolver` (which has no notion of a preconditioner) measure the residual norm directly. This can lead to infinite loops where a newton iterate whose residual is just above the absolute tolerance needs another linear solve, but the krylov method exits immediately because it concludes that residual norm after preconditioning is below the absolute tolerance.

Here's a complete example: https://godbolt.org/z/qeMP1a59T

Is it possible to amend mfem's implementation of these krylov methods to measure absolute residual in a way that is consistent with the nonlinear solvers? Right now, the only workarounds I can think of are
 - set the linear solver absolute tolerance to actual 0.0, so that this incorrect early-exit is avoided, but this prevents users from actually using absolute tolerance as an exit condition.
 - reimplement pcg + gmres in our project

**Comment by v-dobrev** [comment]
It shouldn't be too hard to add support for user-defined stopping criteria. Then we can implement one that uses the residual $\ell_2$-norm (which is what the Newton solver uses) instead of the preconditioned norm.

**Comment by thartland** [comment]
I also have interest in being able to use the residual $\ell_{2}$-norm as the stopping criteria for preconditioned Krylov-subspace methods `mfem::GMRESSolver` and `mfem::MINRESSolver`.

**Comment by v-dobrev** [comment]
The capability to use user-defined stopping criteria in iterative methods is being added in #4483. If interested, please take a look and provide feedback.

Please continue the discussion in #4483.
