### ISSUE TITLE
Bilinear Integrator with two normals

### ISSUE THREAD

**Issue by AlejandroMunozManterola** [mfem/mfem#3643]
Good day, MFEM community,

I'd like to inquire about the implementation of a bilinear form where I have to apply two normals to the DG jump of my field operator. 

For the sake of convenience lets say my operator is a three dimensional Electric Field vector such as [**E**] = [Ex, Ey, Ez], **n** = [nx, ny, nz] and the second normal which varies depending on which dimensional part we're calculating, for example for the x component I'd have to apply a Bilinear Integrator such as:

(**n** · [**E**]) · nx = (nx · [Ex]) · nx + (ny · [Ey]) · nx + (nz · [Ez]) · nx

After using the DGTraceIntegrator as template, I got the doubt on where the scaling depending on the size of the side we're calculating the jump is, I have noticed that in 3D for example, we calculate normals on a specific face through:

`CalcOrtho(Trans.Jacobian(), nor);`

Where I suppose in the nor vector we get as output, the scaling is correctly applied through the Jacobian. But when I apply the two normal operator on sides where the size of the side is not 1.0, I seem to have scaling issues which I have to correct somehow or they cause instability problems. 

Any insight on how to proceed? Is there something I'm missing here? Is there no need to do any correction at all?

Thank you very much,
Alejandro M.

**Comment by vladotomov** [comment]
@AlejandroMunozManterola sorry we missed this, I hope you were able to figure it out.

The returned `nor` is scaled by the measure of the face, so yes, you'd have to correct the magnitude if you use it twice.
