### ISSUE TITLE
Possibility of combining MFEM libraries with other C++ project

### ISSUE THREAD

**Issue by minamdar** [mfem/mfem#365]
Is it possible to combine MFEM libraries with my own C++ project? More specifically, I have a C++/qt project built with qmake. Could you kindly give me some pointers. 

thanks,
m. inamdar

**Comment by jakubcerveny** [comment]
Hi,

I don't use qmake but it would seem you just need to link with libmfem.a
and add the MFEM directory as include path. See for example these answers:
https://stackoverflow.com/questions/1361229/using-a-static-library-in-qt-creator

Jakub

**Comment by minamdar** [comment]
Thank you very much. I will try that. 

best wishes,
mandar

**Comment by AntoineMazuyer** [comment]
Hi,
I use MFEM as a dependency for one other project. Here is a sample of my CMakeLists.txt, on which `MFEM_HOME` is the path to MFEM

```
MESSAGE(STATUS ${MFEM_HOME})
#Here MFEM is built in the build directory, in the root of the mfem project
find_package(MFEM REQUIRED PATHS "${MFEM_HOME}/build")
if(MFEM_FOUND)
    MESSAGE(STATUS "MFEM is found!")
    MESSAGE(STATUS "MFEM include directory ${MFEM_INCLUDE_DIRS}")
    MESSAGE(STATUS "MFEM library directory ${MFEM_LIBRARIES}")

    # Add MFEM include directories to the current ones
    include_directories(SYSTEM ${MFEM_INCLUDE_DIRS})

    # MyLib links with MFEM
    target_link_libraries(MyLib ${EXTRA_LIBS})

    # Add MFEM bin directories to the current ones 
    link_directories(${MFEM_LIBRARY_DIR})
else(MFEM_FOUND)
    message(FATAL_ERROR "You have to set a path for MFEM")
endif(MFEM_FOUND)
```

**Comment by minamdar** [comment]
Thank you.

**Comment by tzanio** [comment]
Thanks for answering this @AntoineMazuyer!
