### ISSUE TITLE
Check whether a shared face is Boundary Element or not

### ISSUE THREAD

**Issue by chikitkin** [mfem/mfem#3650]
Dear MFEM developers,
I found out that if a Boundary Element (triangle) is a shared face in a parallel mesh then one of the MPI ranks tells that this face is boundary element, but the second MPI rank tells that it's not. Namely, for one rank this boundary face is not returned by `ParMesh->GetBdrElementFace`

Is there a simple way to check whether a shared face is boundary element or not? I think it's needed in many cases, for example to implement some error estimators in which at the boundary we should use special formulas.
If there is no simple way, please point some good way to exchange this information via MPI.

Thank you in advance!
Aleks

**Comment by vladotomov** [comment]
@chikitkin sorry we missed this.

I guess you're talking about internal faces that are marked as boundaries. If such face is shared between 2 MPI tasks, and one of the tasks doesn't see it as a boundary, then this sounds wrong. Do you have a small reproducer?

It might help to take a look at https://github.com/mfem/mfem/issues/3755 too.
