### ISSUE TITLE
Is assembled matrix multiplication dependent on the number of processes?

### ISSUE THREAD

**Issue by kvoronin** [mfem/mfem#366]
Hello,

I've got a very simple question. Why in the following code the result (norm of Truevec2) is different for different number of processes?
What the code below does is it creates a simple mass matrix integrator for Hdiv in 3D, assembles it into a HypreParMatrix and multiplies a constant vector of all ones with it.
The norm of the resulting vector is assembled over processes by MPI_Allreduce.
The answer is different for different number of processes, the difference is in the 5-6th digit though the computations are done for double, global size of the matrix is only about 6k. The difference looks too large for rounding errors to create it.
```c++
   FiniteElementCollection * hdiv_coll = new RT_FECollection(0, 3);
   ParFiniteElementSpace * R_space = new ParFiniteElementSpace(pmesh, hdiv_coll);

   ParBilinearForm *Ablock(new ParBilinearForm(R_space));
   Ablock->AddDomainIntegrator(new VectorFEMassIntegrator);
   Ablock->Assemble();
   SparseMatrix * Alocal = &(Ablock->SpMat());
   Ablock->Finalize();

   HypreParMatrix * Aglobal = Ablock->ParallelAssemble();

   Vector Truevec1(Aglobal->Width());
   Truevec1 = 1.0;
   Vector Truevec2(Aglobal->Height());

   // using global matrix
   Aglobal->Mult(Truevec1, Truevec2);

   int local_size = Truevec2.Size();
   int global_size = 0;
   MPI_Allreduce(&local_size, &global_size, 1, MPI_INT, MPI_SUM, MPI_COMM_WORLD);

   double local_normsq = Truevec2 * Truevec2;
   double global_norm = 0.0;
   MPI_Allreduce(&local_normsq, &global_norm, 1, MPI_DOUBLE, MPI_SUM, MPI_COMM_WORLD);
   global_norm = sqrt (global_norm / global_size);

   if (myid == 0)
       std::cout << "Truevec2 norm = " << global_norm << "\n";

   MPI_Finalize();
   return 0;
```
I would be very grateful if someone can help.

Thanks,
Kirill

**Comment by tzanio** [comment]
Hi Kirli,

Have you tried visualizing `Truevec1` as a `ParGridFunction` in `R_space`?

The true degrees of freedom may correspond to different face orientations for different parallel decompositions, so a vector of ones can correspond to different finite element functions.

Hope this helps,
Tzanio

**Comment by kvoronin** [comment]
Thanks, @tzanio, you're right. Using as an input a gridfunction which is projection of a vector coefficient (assembled on true dofs) leads to the same result for any number of processes.
