### ISSUE TITLE
A quick question about obtaining coordinate L2 space

### ISSUE THREAD

**Issue by sungho91** [mfem/mfem#3661]
Hi all,

I have a quick question. Is there any function that can get the x, y, and z coordinates in an L2 grid function?

Best

Sungho

**Comment by pazner** [comment]
Maybe something like this will do what you need:

```c++
L2_FECollection l2_fec(order, mesh.Dimension());
FiniteElementSpace l2_fes(&mesh, &l2_fec, mesh.SpaceDimension());
GridFunction node_gf(&l2_fes);
mesh.GetNodes(node_gf);
```

This will create an L2 grid function and set its nodal values to the mesh coordinates at the corresponding node.

**Comment by sungho91** [comment]
@vladotomov 
Yes, I was trying to find xyz of L2.
So, I used function coefficient and it is working. But it is messy. Do you have a better idea?

@pazner 
Oh, it looks pretty simple. The positions are corresponding to xyz in L2? 

Sungho

   // xyz coordinates in L2 space
   ParGridFunction x_gf_l2(&L2FESpace);
   ParGridFunction y_gf_l2(&L2FESpace);
   ParGridFunction z_gf_l2(&L2FESpace);
   x_gf_l2 = 0.0; y_gf_l2 = 0.0; z_gf_l2 = 0.0;
   FunctionCoefficient x_coeff(x_l2);
   FunctionCoefficient y_coeff(y_l2);
   x_gf_l2.ProjectCoefficient(x_coeff);
   y_gf_l2.ProjectCoefficient(y_coeff);

   if(dim == 3)
   {
      FunctionCoefficient z_coeff(z_l2);
      z_gf_l2.ProjectCoefficient(z_coeff);
   }

   double x_l2(const Vector &x)
   {
      return x(0);
   }

   double y_l2(const Vector &x)
   {
      return x(1);
   }

   double z_l2(const Vector &x)
   {
      return x(2);
   }


But it
