### ISSUE TITLE
Prism and Pyramid elements for H(curl) FES

### ISSUE THREAD

**Issue by sanjeev1407** [mfem/mfem#3666]
Hello,

I wanted to know if MFEM supports prism and pyramid elements for H(curl) finite element spaces. I want to solve maxwell equations for 3D coil configuration where I need to have either prism or pyramid elements.

Thank you.

**Comment by mlstowell** [comment]
Hello, @sanjeev1407,

MFEM does support H(curl) finite elements with prisms in addition to hexahedra and tetrahedra. We have looked at pyramid support but have not yet found a manageable arbitrary order solution.

Best wishes,
Mark

**Comment by sanjeev1407** [comment]
Thanks for the details. Prism will solve my problem.
