### ISSUE TITLE
Interface to MA57 solver

### ISSUE THREAD

**Issue by thartland** [mfem/mfem#3674]
@cnpetra and I are interested in having access MA57 linear solvers for sparse symmetric linear systems from within MFEM. Is it possible to include such an interface?

**Comment by v-dobrev** [comment]
It should be possible. Feel free to propose a PR if you want.

**Comment by tzanio** [comment]
@thartland, are you able to create a PR for this, or do you need help?

**Comment by thartland** [comment]
@tzanio, thanks for the followup message. I should be able to give more thought to this item later this week and early next week. I will likely need help but I will have take an honest look at this before asking for help.

**Comment by tzanio** [comment]
ping: @thartland

**Comment by thartland** [comment]
I have yet to be able to commit enough time to this. When I get more into this I will reach out to the MFEM team if I run into challenges. Thanks all.

**Comment by tzanio** [comment]
Thanks @thartland
