### ISSUE TITLE
Questions of installing mfem examples

### ISSUE THREAD

**Issue by topazus** [mfem/mfem#3677]
Since the mfem example executables can be used for testing, is there any need to use `install()` to install them into some location?

https://github.com/mfem/mfem/blob/0f5d34b2b490819789d6c85546e17724ff37f021/config/cmake/modules/MfemCmakeUtilities.cmake#L94-L98

**Comment by v-dobrev** [comment]
The examples will be installed only if you set `MFEM_ENABLE_EXAMPLES` to `ON`.

For testing (which includes running the unit tests, the examples, and the miniapps) you do not need to set `MFEM_ENABLE_EXAMPLES` to `ON`. Instead, you can build the target `exec` and then run the tests as usual. This is described here (you can also use `ctest` for running the tests): https://github.com/mfem/mfem/blob/0f5d34b2b490819789d6c85546e17724ff37f021/INSTALL#L908-L918

**Comment by topazus** [comment]
Many thanks for poiting out the key points of building instruction file, I did not look through the instructions very carefully.
