### ISSUE TITLE
Issue making the miniapp/navier problem

### ISSUE THREAD

**Issue by sarahcburnett** [mfem/mfem#3678]
Hello, 

This is probably a silly issue on my end but I was hoping you might have ideas on how to resolve it. I installed MFEM on my Mac Os with M1 Ventura 13.0.1. I have successful done `make all` and have all the examples appear and tested they can run. The parallel examples don't appear. I have the visualization working too. What I'm most interested in is miniapp/navier problem but the make file doesn't seem to generate any executables. It tells me "Nothing can be done for `all`." I tried `make clean` then `make` but nothing changes. Let me know if there's some work around. Thanks!

**Comment by pazner** [comment]
Hello @sarahcburnett,

MFEM needs to be configured to use MPI in order to build the parallel examples and miniapps.

You can try running either `make parallel` (or `make pdebug` for the debug build) or `make config MFEM_USE_MPI=YES` before running `make all`.

**Comment by sarahcburnett** [comment]
Thank you for responding promptly. I'm getting closer but it seems I get this error (below) which looks like it's not finding the file in the config directory. There was a 2019 post similar to this but I can't figure what she found in the configuration instructions that fix this. 


```
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C config all
mpicxx -I../../hypre/src/hypre/include get_hypre_version.cpp -o get_hypre_version
get_hypre_version.cpp:12:10: fatal error: 'HYPRE_config.h' file not found
#include "HYPRE_config.h"
         ^~~~~~~~~~~~~~~~
1 error generated.
make[1]: *** [get_hypre_version] Error 1
make: *** [local-config] Error 2
```

**Comment by sarahcburnett** [comment]
I tried 

`make config MFEM_USE_MPI=YES MFEM_DEBUG=NO`

and got an error:

```
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C config all
mpicxx -I../../hypre/src/hypre/include get_hypre_version.cpp -o get_hypre_version
get_hypre_version.cpp:12:10: fatal error: 'HYPRE_config.h' file not found
#include "HYPRE_config.h"
         ^~~~~~~~~~~~~~~~
1 error generated.
make[1]: *** [get_hypre_version] Error 1
make: *** [local-config] Error 2
```
It seems another user had this issue in 2019. I tried to read the installation instructions carefully but I must have missed something.

**Comment by sarahcburnett** [comment]
Thank you for the quick response --I'm sorry for the delay. 
I've been teaching python and was messing up my Anaconda installation so I've waited until I had some free time.

I realize that I didn't have openmp on my computer. I installed openmp, then I had trouble with my files using another version of openmp I had installed with Anaconda. I uninstalled Anaconda and then I was able to install hypre sibling to mfem. Hypre was easy to install. But then it gave me the sibling directory name "hypre-master" when I opened the file. I changed the directory name to "hypre" to match the `HYPRE_DIR = @MFEM_DIR@/../hypre/src/hypre` path in mfem user.mk file. Then I configured and install hypre from it's src folder. I had to do similar things to match file names for metis. But I experimented and did it a different way. I set `MFEM_USE_METIS_5  = YES` then changed things to `METIS_DIR = @MFEM_DIR@/../metis-5.1.0` and `METIS_LIB = -L$(METIS_DIR)/libmetis -lmetislib` in the user.mk file. 
It got pretty far into the installation but then ran me into this error:
```
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C examples
mpicxx  -O3 -std=c++11 -I.. -I../../hypre/src/hypre/include -I../../metis-5.1.0/include ex0p.cpp -o ex0p -L.. -lmfem -L../../hypre/src/hypre/lib -lHYPRE -L../../metis-5.1.0/libmetis -lmetislib
ld: library not found for -lmetislib
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [ex0p] Error 1
make: *** [examples] Error 2
```
Is my metis installed incorrect? I didn't have a directory `lib` or file `metis.h`. I have `libmetis` and `metislib.h`

**Comment by v-dobrev** [comment]
For completeness:
* Some basic building instructions can be found here: https://mfem.org/building (includes basic install instructions for METIS and hypre too).
* For more details, see the `INSTALL` file in the repository: https://github.com/mfem/mfem/blob/master/INSTALL.

**Comment by sarahcburnett** [comment]
Thank you, I appreciate the thorough documentation. I followed the suggested `INSTALL` and just had to customize a few things from `config/defaults.mk`. Everything is working nicely now.
