### ISSUE TITLE
Adding Sundials IDA support to MFEM?

### ISSUE THREAD

**Issue by sbugenha** [mfem/mfem#3684]
Hello All,

I have been working on a problem formulated as a DAE that I have been solving in MFEM using the Sundials IDA solver. I noticed that the IDA solver is not currently implemented in the MFEM environment. I was able to create a wrapper in serial using the CVODE wrapper as a template which seems to work, but my implementation in parallel has been giving me errors. I am not comfortable enough with parallel programming in MFEM and Sundials to be able to troubleshoot this, and I was wondering if there is any chance support for the Sundials IDA solver could be officially added to MFEM?

Thank you very much.

Sincerely,
Scott Bugenhagen

**Comment by sbugenha** [comment]
I did some more debugging and managed to get this working. It was an issue with the SetSVtolerances function that I copied over from the CVODE wrapper. Seems to be working now. Happy to share my code if anyone is interested.

**Comment by v-dobrev** [comment]
Hi @sbugenha, I'm glad you got IDA working! Are you interested in creating a PR to add your IDA wrapper to MFEM?

**Comment by sbugenha** [comment]
Hi @v-dobrev - yes, definitely interested! I can start working on this. I'm somewhat new to this, so I may DM you if I have issues or need clarification on the PR process.
