### ISSUE TITLE
Visualization with GLVis- Probe 

### ISSUE THREAD

**Issue by shani9383** [mfem/mfem#3686]
Hi, 
I'm using GLVis for visualization of my results generated by ex2p.   Is there a way to probe the values from a specific node/element?

Thanks
Shani

**Comment by tzanio** [comment]
Does `miniapps/tools/get-values.cpp` works for you?

**Comment by vladotomov** [comment]
@shani9383 did you build with GSLIB? This miniapp requires it. See `INSTALL`.

**Comment by pazner** [comment]
If you want to interactively check the values at specific points, you can do this in ParaView with, for example, the "Hover Points" functionality.

After saving your solution with `ParaViewDataCollection` (see e.g. example 9), in ParaView you can enable "Hover Points":

<img width="269" alt="hover_points" src="https://github.com/mfem/mfem/assets/11493037/e2b358d5-8004-42f9-b69e-ff4bce9f2b65">

Then, hover over the desired point and it will display the solution value:

<img width="1095" alt="solution" src="https://github.com/mfem/mfem/assets/11493037/89140075-678c-47e6-84fe-bd83679f2b20">

**Comment by shani9383** [comment]
Thank you so much. Ill try it.
