### ISSUE TITLE
Nodes of "L2-conforming" Lagrange polynomials on Tetrahedra

### ISSUE THREAD

**Issue by termi-official** [mfem/mfem#3689]
Hi everyone,

I tried to implement some DG stuff using a full tetrahedral mesh but run into convergence issues - Hexahedrons work fine. I think I can track this down to a difference between the Gauss-Legendre quadrature rule (which seem to have the expected weights and positions) and the placement of the nodes for the Lagrange basis functions (which seem to be weirdly off). For example when comparing the Gauss-Legendre quadrature of order 2 with linear Lagrange polynomials I get
```
Point 0
Element Nodes:0.148543 0.148543 0.148543
Gauss-Legendre Nodes: 0.138197 0.138197 0.138197

Point 1
Element Nodes:0.554371 0.148543 0.148543
Gauss-Legendre Nodes: 0.138197 0.138197 0.58541

Point 2
Element Nodes:0.148543 0.554371 0.148543
Gauss-Legendre Nodes: 0.138197 0.58541 0.138197

Point 3
Element Nodes:0.148543 0.148543 0.554371
Gauss-Legendre Nodes: 0.58541 0.138197 0.138197
```
I also went though the implementation for the node placement of Lagrange polynomials and could not find anything obvious why these should differ - or is it really expected that these nodes are just different ones (I usually never work with Tets)?

If the nodes should match, then my second question on this would be if there exists a general permutation rule on how to permutate the quadrature points such that the index of the quadrature point matches the index of the node?

Thanks in advance!

**Comment by tzanio** [comment]
@v-dobrev, can you help with this?

**Comment by v-dobrev** [comment]
On tets, there is no relation between the nodes in the `L2_TetrahedronElement` (with any `BasisType`) and the quadrature rules on tets defined in `IntegrationRules::TetrahedronIntegrationRule`.

**Comment by termi-official** [comment]
Thanks for the pointer Veselin. Forgive me my ignorance, but now I am not sure what I am misunderstanding here now. I guess my assumption that (analogical to hypercubes) the "canonical" Gauss-Legendre points on tetrahedra can be reconstructed from the internally used product construction via 1D (Gauss-Legendre) points is wrong? If so, may I also ask if there is there some disadvantage in constructing product bases which coincide with the Gauss-Legendre point, if this is even possible?

**Comment by v-dobrev** [comment]
I'm not sure I understand your question: can you clarify what you mean by

> the "canonical" Gauss-Legendre points on tetrahedra

and also by

> the internally used product construction via 1D (Gauss-Legendre) points

**Comment by termi-official** [comment]
With canonical Gauss-Legendre points I refer to the naive construction which are induced by mapping the integral over the reference tetrahedron back to the reference brick (see e.g. the Higher-Order Finite Elements book by Solin, Segeth &Dolezel, proposition 4.2 on page 260):
```math
\int_{tet} f(\xi) d\xi = \int_{brick} \frac{(1-\xi_2)(1-\xi_3)^2}{8} f\left(\frac{(1-\xi_2)(1-\xi_3)}{4}(\xi_1+1)-1 ,\frac{(1+\xi_2)(1-\xi_3)}{2}-1, \xi_3 \right)
```
now transforming the Gauss-Legendre points on this brick back to the tetrahedron is what I refer to.

Regarding the internal construction I refer to 

https://github.com/mfem/mfem/blob/b5491f763085b3cc917fed34a58ee816c1bc0cc9/fem/fe/fe_l2.cpp#L716-L739

with attention to the node placement in line 721: `Nodes.IntPoint(o++).Set3(op[i]/w, op[j]/w, op[k]/w);`
which I could not find in the book above.

**Comment by hughcars** [comment]
Forgive the drive by, but @termi-official If I am understanding you correctly: No, quadrature rules on simplices are not in general constructed from combination of 1D rules on lines. See https://arxiv.org/pdf/1409.1865.pdf for a very interesting paper about how to construct simplex rules whilst respecting all the relevant symmetries. It's an interesting exercise trying to figure out the relevant symmetries for the first 2 or 3 gauss rules on a triangle (or tet) by hand, it pretty quickly starts to get out of hand but is enlightening. With a change of measure, it's even possible to derive the simplest rules on tri/tet using 1D rules in barycentric coordinates, this breaks down very quickly though.

I believe there are some rules that combine the 1D rules to get general simplex rules, which are general. However, they end up losing a lot of in terms of efficiency as the number of points grows at n^D. I think this approach might be what you're implying by transforming from a hex to a tet, I think this is the Conical Stroud approach, but don't hold me to that.

**Comment by termi-official** [comment]
Thanks for the pointer @hughcars . I knew that `polyquad` was a thing, but I have never found time to read the paper, yet. I think I see why it is be not so optimal to construct quadrature rules coinciding with the nodes on tets.
