### ISSUE TITLE
question about miniapps /electromagnetics Joule_solver.cpp, Are you solving **E** are **dE/dt**?

### ISSUE THREAD

**Issue by Asadanees** [mfem/mfem#369]
Dear @tzanio  and @rieben1 , 
in the file  ** joule.cpp**, you mentioned that you are solving **E**
 (https://github.com/mfem/mfem/blob/master/miniapps/electromagnetics/joule.cpp)
**sigma **E  =  Curl B/mu - sigma grad **Phi**.  
But in the file **joule_solver.hpp" before the class **MagneticDiffusionEOperator** you are solving **dE/dt** after spatial discretization.
(https://github.com/mfem/mfem/blob/master/miniapps/electromagnetics/joule_solver.hpp)
dE/dt       = - (M1(sigma) + dt S1(1/mu))^{-1}*(S1(1/mu)*E + sigma Grad P).
could you please tell me?
Are you solving **E** or **dE/dt**?
thanks .
asad anees

**Comment by tzanio** [comment]
@Dan2997925, this for Joule, can you point Anes to a description of the formulation?

**Comment by tzanio** [comment]
See also #370.

**Comment by Dan2997925** [comment]
@Asadanees Thanks for your interest in Joule. Yes it seems the comments are inconsistent, the comments in the *.cpp files are correct, we solve for E and F implicitly.

**Comment by Asadanees** [comment]
@Dan2997925 Thanks for clearing the questions and  cooperation.
I used same ImplicitSolve  approach  for dE/dt as you used in joule Implicitsolve. when I found the absolute error is not right. Than I looked the code carefully. Than, I though/ concluded that you are solving E instead of dE/dt as well as F.
Best wishes.

asad anees
