### ISSUE TITLE
Bug in `ParNCMesh` with p > 2 H1 space on conformal prism mesh

### ISSUE THREAD

**Issue by hughcars** [mfem/mfem#3691]
I have a mesh `p1_prism.msh`, available on branch `cavity-prism-par-ncmesh-bug`, which when run with `ex1p` runs fine, with and without a uniform refinement:
```
mpirun -np 3 ex1p -m ../../data/p1_prism.msh -o 2
```

The initial `p1_prism` mesh as shown by glvis is
<img width="535" alt="Screenshot 2023-05-24 at 10 08 13 AM" src="https://github.com/mfem/mfem/assets/114775781/40a18eea-a8f5-4583-938e-10656b2fed00">
and the uniformly refined mesh is 
<img width="535" alt="Screenshot 2023-05-24 at 10 08 50 AM" src="https://github.com/mfem/mfem/assets/114775781/f067eab9-e385-4e02-9144-a1465854f28c">

Passing the same mesh to `ex6p` however causes a range of issues. If a uniform refinement is done on the serial mesh before `EnsureNCMesh` is called, calling `mpirun -np 3 ex6p -m ../../data/p1_prism.msh -o 2 -h1` (using `-h1` avoids triggering a related bug for RT spaces, see https://github.com/mfem/mfem/issues/3671) gives these error messages:
```
Verification failed: (key >= 0) is false:
 --> R1 index 35 not found.
 ... in function: const NCMesh::MeshId &mfem::NCMesh::NCList::LookUp(int, int *) const
 ... in file: [redact]/mfem/mesh/ncmesh.cpp:3474

Verification failed: (key >= 0) is false:
 --> R0 index 13 not found.
 ... in function: const NCMesh::MeshId &mfem::NCMesh::NCList::LookUp(int, int *) const
 ... in file: [redact]/mfem/mesh/ncmesh.cpp:3474
```
In the initial phase of `BuildParallelConformingInterpolation` where local true dofs are being sent to other ranks [here](https://github.com/mfem/mfem/blob/master/fem/pfespace.cpp#L2509). The `R0` and `R1` in the above error messages are the ranks of the failing processors.

If uniform refinement is instead performed after the call to `EnsureNCMesh`, then [this loop](https://github.com/mfem/mfem/blob/master/fem/pfespace.cpp#L2527) never terminates for rank 2, as ranks 0 and 1 exit the loop, whilst rank 2 is waiting for one more face dof (141) to be delivered from a communication group of rank 1 and rank 2. Sending all of the dofs that rank 1 believes rank 2 needs again, does not work either, so rank 1 and 2 are in disagreement about the sharing of dofs.

These meshes are entirely conformal, as no AMR has occurred yet, and from the running of ex1p, are valid conformal meshes. So the issue appears to be in the interpretation of the mesh by the `ParNCMesh` class, and from that the construction of a finite element space that depends on face dofs. For a P2 prism mesh, the only face dofs have to be on quadrilateral faces, suggesting the issue is there.

Any help/feedback would be appreciated as the `ParNCMesh` class is not the easiest to understand, and it only gets more difficult when interacting with the `ParFiniteElementSpace` class. I've read the [NC mesh paper](https://arxiv.org/abs/1905.04033) but that is primarily concerned with quads/hexes, and reading through https://github.com/mfem/mfem/pull/713 it appears most difficulties were associated with mixed meshes, rather than a purely prism mesh such as this.

**Comment by mlstowell** [comment]
I can confirm this behavior but I haven't looked further into it yet.

**Comment by hughcars** [comment]
Thanks for the response @mlstowell, I'll post any extra information I glean here. I have a few extra ways of triggering similar (and I believe related) issues. Running with 2 ranks, order 2, then rank 0 fails to send identity rows, as the index returned by `UnpackDofs` is an invalid entry into the `face_list` of `NCMesh`. It looks like `ParFiniteElementSpace::UnpackDofs` is inconsistent with `NCMesh::NCList`. Big upside to this particular error is a) Rank 0, so minimal ghosts and b) only two ranks as opposed to the three of above. This then points the finger at `var_face_dofs` or `NCList`, and I am inclined to say it's `var_face_dofs`.

**Comment by hughcars** [comment]
Ok, I think I have possibly identified one issue, but haven't thought of a solution. Basically it looks like the issue is that `UnpackDofs` is assuming that the map `dof -> entity,index,edof` is a one to one map, i.e. each dof entry has a single entity associated. The issue is that for a P2 tri there is no dof, so when `var_face_dofs` table is populated, there will be multiple triangles mapped onto a single dof. 

So when dof 191 (dof 7 in the face dofs) is added, it searches through the Table, and finds the interval `(13, 14, 15)`, `std::lower_bound` then extracts `13` but the real shared face is triangle 14. This then causes the miss when `NCList` is interrogated for the shared face 13, which doesn't exist. This is clearly _an_ issue, but I still think there are others. Reason being, switching to P3 would fix this, (all faces have interior dofs), but there's still a miss there. It does suggests to me however that the NCList->UnpackDofs interface is where the issues lie.

**Comment by tzanio** [comment]
Discussion continued in #3709.
