### ISSUE TITLE
Details on MINRES preconditioning

### ISSUE THREAD

**Issue by thartland** [mfem/mfem#3692]
I want to be sure that I understand how MFEM's preconditioning works. I see in [solvers.cpp](https://github.com/mfem/mfem/blob/master/linalg/solvers.cpp#L1625), that the MFEM::MINRESSolver::Mult has been "Extended to support an SPD preconditioner".

[Right preconditioned MINRES for Singular Systems](https://onlinelibrary.wiley.com/doi/full/10.1002/nla.2277) was one of the best references I could find on preconditioned MINRES solvers. MFEM's preconditioned MINRES solver looks similar to Algorithm 2, page 3 of the attached reference but I want to verify that MFEM is indeed using a right-preconditioned MINRES solver and if it is not I would like to know how the preconditioning is done.

**Comment by pazner** [comment]
Just like with CG, given preconditioner $M$ and matrix $A$, preconditioned MINRES can be viewed as applying MINRES to $M^{-1/2} A M^{-1/2}$ (which preserves symmetry). You can also (equivalently) view this algorithm as applying MINRES in the inner product induced by $M$ to the system $M^{-1} A$ (the preconditioned system $M^{-1} A$ is self-adjoint with respect to this inner product).

**Comment by thartland** [comment]
I see, by transforming $Ax = b$ to $M^{-1/2} A M^{-1/2} \underbrace{M^{1/2}x}_{y} = M^{-1/2} b$ and then minimizing the Euclidean norm of $M^{-1/2} (b - A M^{-1/2} y)$ over all $y$ in the Krylov subspace defined by the matrix $M^{-1/2}AM^{-1/2}$ and vector $M^{-1/2}r_{0}$ for $r_{0}=b-Ax_{0}$ is equivalent to this right-preconditioned MINRES from the reference. So my question about if MFEM uses right preconditioned MINRES isn't entirely relevant there are equivalences between left, right and symmetric preconditioned MINRES and so the distinctions are not entirely meaningful. Thank you Will!
