### ISSUE TITLE
could you explain miniapps/electromagnetics/joule_solver.cpp about dE =0 and dP=0?

### ISSUE THREAD

**Issue by Asadanees** [mfem/mfem#370]
Dear @rieben1 and @tzanio ,
Could you please explain in joule_solver.cpp in the Member function **ImplicitSolve**  (https://github.com/mfem/mfem/blob/master/miniapps/electromagnetics/joule_solver.cpp)
Why you took **dE=0 at line number 564**  and **dP=0 at line number 514 ** in the  **ImplicitSolve**?
Why you did not take **dF=0**.?

Thanks.

asad anees.

**Comment by Dan2997925** [comment]
@Asadanees Yes for consistency we should set dF = 0 inside of ImplicitSolve, just like we do for E.

**Comment by Asadanees** [comment]
Dear @Dan2997925 .
thanks for your cooperations.
Best regards,
asad anees
