### ISSUE TITLE
On the usage of ParBlockNonlinearForm::GetGradient()

### ISSUE THREAD

**Issue by lunep** [mfem/mfem#3702]
Hi, I am using ParBlockNonlinearForm to form and solve a Newton equation. To calculate Jacobi, I use the following code:
   mfem::BlockOperator bOP = pbnlf->GetGradient(trueX); 
where pbnlf is a ParBlockNonlinearForm, trueX is a mfem::Vector

However, I found that after mfem 4.2, i.e., from mfem 4.3, the copy constructor for block operator is deleted: 

   /// Copy assignment is not supported
   BlockOperator &operator=(const BlockOperator &) = delete;

So why do we delete this function after mfem 4.2? And how could I get access to the Jacobi matrix?
Thanks!

**Comment by lunep** [comment]
Well, I find that just use

**Comment by lunep** [comment]
Well, I find that just using
    mfem::BlockOperator& bOP = pbnlf->GetGradient(trueX);
could solve the problem. Thanks for your notice.

**Comment by v-dobrev** [comment]
Yes, the intended use for the result of `pbnlf->GetGradient(trueX)` is to use to to initialize a reference to a `BlockOperator` and not to create a copy of the returned (by reference) object, i.e.
```c++
 mfem::BlockOperator& bOP = pbnlf->GetGradient(trueX);
```
is the intended usage.
