### ISSUE TITLE
Linking mfem and mumps, compilation error

### ISSUE THREAD

**Issue by Tr4l77** [mfem/mfem#3705]
Hello mfem team,

When I try to compile an example with "make ex25p" in which I have enable "mumps_solver=true", I have the following error : 

/opt/rh/devtoolset-7/root/usr/bin/ld: /opt/mfem_etc/mumps-main/build/libdmumps.a(dmumps_load.F.o): undefined reference to symbol '_gfortran_transfer_real_write@@GFORTRAN_1.4'
//lib64/libgfortran.so.3: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[3]: *** [examples/CMakeFiles/ex25p.dir/build.make:109: examples/ex25p] Error 1
make[2]: *** [CMakeFiles/Makefile2:1676: examples/CMakeFiles/ex25p.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:1683: examples/CMakeFiles/ex25p.dir/rule] Error 2
make: *** [Makefile:267: examples/CMakeFiles/ex25p.dir/rule] Error 2

Here is what I did : 
I have build mumps and mfem using cmake on centos 7.
Then to link mfem and mumps I used cmake-gui with MFEM_USE_MUMPS, MFEM_USE_MPI, MFEM_USE_OPENMP.
After manually giving the path to the different libraries, I configured and generated. Then I did "cmake --build buildNew". These steps were achieved without errors. 

If you need more information, I am available.

It would be very appreciated if you could help me to use mfem with mumps.

Best regards.

**Comment by v-dobrev** [comment]
Can you try uncommenting this section:
https://github.com/mfem/mfem/blob/b5491f763085b3cc917fed34a58ee816c1bc0cc9/config/defaults.cmake#L148-L150

The `"mpi_mpifh"` library may need to be replaced if you are NOT using OpenMPI, e.g. with `"mpifort"` if using MPICH.
