### ISSUE TITLE
How to change the basis function of  tetrahedrons ?

### ISSUE THREAD

**Issue by azmmza** [mfem/mfem#3706]
Due to new exposure to MFEM, I am a novice. I don't know where the specific basis functions are described in the MFEM code library, especially for high-order tetrahedrons. 
In the future, I may write higher-order stacked basis functions to implement vector finite elements.
Can anyone help me in which file should I edit？
Please forgive my foolishness, as it is true that I have just started to interact with MFEM and C++

**Comment by mlstowell** [comment]
Hi, @azmmza,

Thank you for your interest in MFEM. I hope you will find it useful.

MFEM is designed to be modular so you shouldn't need to edit any of the MFEM files to add your own basis function types. What you will need to do is write new classes derived from [FiniteElement](https://github.com/mfem/mfem/blob/d0e75c8d0d8b6def5ae22a38e08e81dd8e38c0d8/fem/fe/fe_base.hpp#L232) and [FiniteElementCollection](https://github.com/mfem/mfem/blob/d0e75c8d0d8b6def5ae22a38e08e81dd8e38c0d8/fem/fe_coll.hpp#L26). These can then be passed to existing `FiniteElementSpace` objects and everything else should make use of your new basis functions without modification.

If you want to look  more closely at the existing scalar finite element basis functions you can examine [H1_TetrahedronElement](https://github.com/mfem/mfem/blob/d0e75c8d0d8b6def5ae22a38e08e81dd8e38c0d8/fem/fe/fe_h1.hpp#L105) and [L2_TetrahedronElement](https://github.com/mfem/mfem/blob/d0e75c8d0d8b6def5ae22a38e08e81dd8e38c0d8/fem/fe/fe_l2.hpp#L138) for continuous and discontinuous bases respectively.

To build stacked basis functions for vector finite elements we automate this in the `FiniteElementSpace` objects which can use multiple copies of the same basis to represent the individual vector components. See [ex2](https://github.com/mfem/mfem/blob/d0e75c8d0d8b6def5ae22a38e08e81dd8e38c0d8/examples/ex2.cpp#L121) for an example of this feature.

We would be happy to offer more targeted advice as you continue to explore MFEM.

Best wishes,
Mark
