### ISSUE TITLE
Visualizing Gradient

### ISSUE THREAD

**Issue by denislachapelle** [mfem/mfem#3710]
How to compute and display the gradient of a scalar function on a 2D domain?

I compute the scalar function using code similar to example 27 and the scalar function display properly on glvis.
This is the scalar function display with glvis.
![image](https://github.com/mfem/mfem/assets/45741871/10c5c55f-0f1c-414c-b52d-8f3cd8c31bd5)

From [https://github.com/mfem/mfem/issues/865#issuecomment-484705746](url) I learn how to compute the gradient; the code section is as follow...

FiniteElementSpace fespace_nd(&mesh, fec);
GridFunction dT(&fespace_nd);
DiscreteLinearOperator grad(&fespace, &fespace_nd);
grad.AddDomainInterpolator(new GradientInterpolator);
grad.Assemble();
grad.Finalize();
grad.Mult(u, dT);

The gradient is possibly be in dT but I have no idea how to visualize it. I tried with the code below but it did show something but it is not the gradient.
{
      string title_str = "H1";
      char vishost[] = "localhost";
      int  visport   = 19916;
      socketstream sol_sock(vishost, visport);
      sol_sock.precision(8);
      sol_sock << "solution\n" << mesh << dT
               << "window_title '" << title_str << " Solution'"
               << " keys 'mmc'" << flush;
      }
   

Thank you for your help.
Denis

**Comment by mlstowell** [comment]
Hi, @denislachapelle,

This looks correct to me. I'm curious what was displayed. Note that by default GLVis initially displays only the magnitude of a vector field. To see the vectors themselves you can press the `v` key with the GLVis window active. Pressing `v` repeatedly cycles through a handful of options for scaling and coloring the vectors. Also, note that on 2D plots like this the vectors are drawn in the z=0 plane. Sometimes this places the vectors below the surface plot of the magnitude and you may need to rotate the image to see them.

Best wishes,
Mark

**Comment by denislachapelle** [comment]
Mark,

Here what glvis shows initially...
![image](https://github.com/mfem/mfem/assets/45741871/d3916950-8c7d-49cb-ac57-da6ee9a30081)

If I rotate with the mouse ...
![image](https://github.com/mfem/mfem/assets/45741871/78de24e8-7aaa-4c31-87ca-3f727ea7312f)

It look like if the df/dx is shown on top and df/dy on bottom.

I try v multiple time and nothing happens...

Regards,
Denis

**Comment by mlstowell** [comment]
Hi, @denislachapelle,

That certainly does look incorrect. I suggest double-checking the finite element collection. How is `fec` created? It should be something like:
```
FiniteElementCollection *fec = new ND_FECollection(order, dim);
``` 
You need two different collections to make this work so it might be wiser to give them descriptive names:
```
FiniteElementCollection *fec_h1 = new H1_FECollection(order, dim);
FiniteElementCollection *fec_nd = new ND_FECollection(order, dim);

FiniteElementSpace fespace_h1(&mesh, fec_h1);
FiniteElementSpace fespace_nd(&mesh, fec_nd);
...
DiscreteLinearOperator grad(&fespace_h1, &fespace_nd);
...
``` 
Or something like that.

Best wishes,
Mark

**Comment by denislachapelle** [comment]
Mark,

It look much better now, I was using the same fespace. Now I use 
FiniteElementCollection *nd_fec = (FiniteElementCollection*)new ND_FECollection(order, dim); as you suggest.

This is the initial output produced by glvis...
![image](https://github.com/mfem/mfem/assets/45741871/a85c2800-92da-4054-b14c-ddcad1d0e7b2)

and once I keyin v twice...
![image](https://github.com/mfem/mfem/assets/45741871/d8beb7d8-1e0a-46df-a95f-11c70b140755)

I would like to look have only the arrow shown; I try many key command without success.

But anyway it look very good now.

You support is very apreciated.
Denis

**Comment by mlstowell** [comment]
Hi, @denislachapelle,
 
I'm glad that helped. I'm not sure the magnitude plot can be removed in GLVis. When I need such plots I usually use [VisIt ](https://visit-dav.github.io/visit-website/index.html) and many of my colleagues use [ParaView](https://www.paraview.org). Example 5 would be a good place to see how this can be accomplished.

Best wishes,
Mark

**Comment by v-dobrev** [comment]
You can hide the magnitude surface with the <kbd>e</kbd> key, see the 2D vector section in the GLVis README.md: https://github.com/GLVis/glvis/blob/master/README.md#2d-vector-data.

**Comment by denislachapelle** [comment]
I installed Visit under WSL and it works fine, but difficult to understand initially and the 'e' key in glvis works fine, so for now this is what I will use.

It make me understand the power of Visit; I should use it later !!!

Thank you to both of you,
Denis
