### ISSUE TITLE
The gradient of the scalar function for the right-hand side of the Lamé equation.

### ISSUE THREAD

**Issue by Tomcat4891** [mfem/mfem#3711]
Hello. Could you please tell me how to set a right-hand side for the elasticity equation from Example 2? 
My right-hand side is F=-grad(s). The scalar function s(x,y,z) is given at points of a rectangular grid. 
The grid was created by MakeCartesian3D.

I have tried various ways with grad -LF integrators, but they don't work. I now pre-calculate the gradient via finite differences, and then substitute in the VectorDomainLFIntegrator. It's not beautiful.

Thank you.

**Comment by v-dobrev** [comment]
You should also be able to avoid the assembly of the `(Par)MixedBilinearForm` by using the class `GradientGridFunctionCoefficient` constructed from the scalar `(Par)GridFunction` `s`. To add the minus sign you can then use `ScalarVectorProductCoefficient` with a `double` scaling factor `A = -1.0`.

**Comment by Tomcat4891** [comment]
Hi, Veselin.

Thank you for the advice, it's working great. Mark's method didn't work. Variable s_fg is of GridFunction type, while arguments of function negGrad.Mult(s_gf, F_lf) should be vectors. I think this can be easily corrected, but this method requires assembling the matrix (slow).

Another question I want to ask you. The Right hand side is defined in a file.

1. I don't quite understand how to create a GridFuncion for a table from an X,Y,Z,VAL     ASCII-file. I have read the tips on the forum, but there is no clear explanation (example). 
I would like a simple solution. 

2. Can I automatically create a ParGridFunction from a GridFunction so that the function values are **COPIED** ?

I do like this:
//FiniteElementSpace *sfespace = new ...... 
Vector V;
.....
GridFunction rhs(sfespace,V);  
ParGridFuction *RHS=new ParFridFunction(pmesh,&rhs);  // In this case the values are not copied. partition=NULL
RHS->ProjectGridFunction(rhs);  

It works for one processor, but not for more.
The RHS values are defined incorrectly.

Thank you.
