### ISSUE TITLE
How to interpolate FE function on a 2D square mesh to the upper boundary of a 3D cube mesh

### ISSUE THREAD

**Issue by zhaog6** [mfem/mfem#3714]
Dear all, I'd like to ask an issue with MFEM interpolation. There are a 2D square mesh of 32x32 and a 3D cube mesh of 28x28x28，their finite element spaces are scalar type (such as P1 Lagrangian element). How to interpolate FE function (ParGridFunction) on a 2D square mesh to the upper boundary of a 3D cube mesh?
I tried writing a MWE, but it always incorrect, so I'm not sure if MFEM supports this feature.
```c++
//----------------------
//   Building 2D mesh
//----------------------
int nn = 32;
auto mesh = new Mesh;
*mesh = Mesh::MakeCartesian2D(nn, nn, Element::TRIANGLE);
auto Th = new ParMesh(MPI_COMM_WORLD, *mesh);
int dim = Th->Dimension();

//----------------------
//   Building 3D mesh
//----------------------
int mm = 28;
*mesh = Mesh::MakeCartesian3D(mm, mm, mm, Element::TETRAHEDRON);
auto Th3d = new ParMesh(MPI_COMM_WORLD, *mesh);
delete mesh;
int dim3d = Th3d->Dimension();

//--------------------------------------
//   Building 2D Finite Element Space
//--------------------------------------
int order = 1;
auto fe = new H1_FECollection(order, dim);
auto Vh = new ParFiniteElementSpace(Th, fe);
ParGridFunction uh(Vh);
uh = 0.;

//--------------------------------------
//   Building 3D Finite Element Space
//--------------------------------------
auto feQ = new H1_FECollection(order, dim3d);
auto Qh = new ParFiniteElementSpace(Th3d, feQ);
ParGridFunction qh(Qh);
qh = 0.;

//-------------------------
//   Boundary Conditions
//-------------------------
Array<int> ess_bdr(Th3d->bdr_attributes.Size());
ess_bdr = 0;
ess_bdr[0] = 1;  // temporarily 0 represents the upper boundary

//---------------------------------------------------------------------------
//   Interpolation from 2D Mesh to the Upper Boundary of 3D Mesh
//---------------------------------------------------------------------------
FunctionCoefficient ue(u_exact);
uh.ProjectCoefficient(ue);  // 
GridFunctionCoefficient qe(&uh);
qh.ProjectBdrCoefficient(qe, ess_bdr);
```

**Comment by tzanio** [comment]
@jandrej do you have tools for this as part of `SubMesh`?

**Comment by jandrej** [comment]
Hence the meshes aren't subsets of each other (this is not clear from the description) `SubMesh` can't communicate the dofs between them.

**Comment by zhaog6** [comment]
Thanks a lot, @tzanio @jandrej , indeed, the meshes aren't subsets of each other. For this, I have an idea by combining #3714 with #3729. I feel like I can first interpolate from a general 2D grid (32x32) to the 2D boundary subgrid (28x28) of a 3D grid as @mlstowell and @kmittal2 suggested using the `gslib`, and  then transfer from the 2D boundary subgrid (28x28) to the 3D grid (28x28x28) as your great suggestion of using the `SubMesh` and `Transfer`. Do you think this is feasible?

**Comment by jandrej** [comment]
If you plan to use `gslib` you don't necessarily need the `SubMesh` transfer.

**Comment by kmittal2** [comment]
Hi @zhaog6, as @jandrej said, if you plan to use `gslib` you don't need `SubMesh` here.
You can get the coordinates of the degrees of freedom from your 3D mesh and interpolate at these locations using `FindPointsGSLIB`.  [field-interp](https://github.com/mfem/mfem/blob/master/miniapps/gslib/field-interp.cpp#L273-L359) miniapp shows an example of this.
Note that since you are trying to interpolate from a 2D mesh/gridfunction pair, you will have to transform the 3D coordinates coming out of your 3D mesh to 2D when you use `FindPointsGSLIB`.

**Comment by zhaog6** [comment]
Thank you @jandrej @kmittal2 , this is very helpful to me. I also have a question with the performance improvement in my case. I want to prestore/extract the interpolation matrix so that only sparse matrix-vector multiplication can be performed during time iterations. Is this feasible?

**Comment by zhaog6** [comment]
> Since the meshes aren't subsets of each other (this is not clear from the description) `SubMesh` can't communicate the dofs between them.

Dear Julian @jandrej , I also tried "nested interpolation". I have a question with the feature of the `ParSubMesh`. If I use `ParSubMesh::CreateFromBoundary` to extract a boundary grid, I noticed that the number of elements of the boundary grid is zero in some CPU processes, this will cause the grid not being uniformly refined (use `ParMesh::MakeRefined`) and the problem of not being able to solve in parallel with loading balance on the refined grid. A MWE is as follows:
```c++
//-----------------
//     Parameters
//-----------------
int nn = 8;
int order = 1;

//---------------
//     Mesh
//---------------
/// Build 3D mesh
auto mesh = new Mesh;
*mesh = Mesh::MakeCartesian3D(nn, nn, nn, Element::TETRAHEDRON);
auto Th3d = new ParMesh(MPI_COMM_WORLD, *mesh);
delete mesh;

/// Extract boundary mesh from the 3D mesh
Array<int> bdr(Th3d->bdr_attributes.Size());
bdr = 0;
bdr[0] = 1;
auto ThCoarse = new ParMesh;
*ThCoarse = ParSubMesh::CreateFromBoundary(*Th3d, bdr);

/// Build 2D finer mesh based on the coarse mesh
auto ThFine = new ParMesh;
*ThFine = ParMesh::MakeRefined(*ThCoarse, 2, BasisType::GaussLobatto);
int dim = ThFine->Dimension();

//--------------------------------------
//     Solve equations on the fine grid
//--------------------------------------
/// Finite element space
auto fe = new H1_FECollection(order, dim);
auto VhFine = new ParFiniteElementSpace(ThFine, fe);
/// Variational form
auto vA = new ParBilinearForm(VhFine);
vA->AddDomainIntegrator(new DiffusionIntegrator);
vA->Assemble();
auto vb = new ParLinearForm(VhFine);
ConstantCoefficient one(1.);
vb->AddDomainIntegrator(new DomainLFIntegrator(one));
vb->Assemble();
Array<int> ess_tdofs_list;
VhFine->GetBoundaryTrueDofs(ess_tdofs_list);
/// Solving
HypreParMatrix A;
Vector uhVec, b;
ParGridFunction uh(VhFine);
uh = 0.;
vA->FormLinearSystem(ess_tdofs_list, uh, *vb, A, uhVec, b);
auto amg = new HypreBoomerAMG(A);
auto cg = new CGSolver(MPI_COMM_WORLD);
cg->SetRelTol(1e-8);
cg->SetOperator(A);
cg->SetPreconditioner(*amg);
cg->Mult(b, uhVec);
vA->RecoverFEMSolution(uhVec, *vb, uh);

//-------------------------------------------------
//     Restriction from fine space to coarse space 
//-------------------------------------------------
auto VhCoarse = new ParFiniteElementSpace(ThCoarse, fe);
auto gt = new InterpolationGridTransfer(*VhCoarse, *VhFine);
const Operator& R = gt->BackwardOperator();
ParGridFunction vh(VhCoarse);
R.Mult(uh, vh);

//----------------------------------------------------------------------
//     Transfer the coarse grid (2D ParSubMesh of 3D grid) to 3D grid
//----------------------------------------------------------------------
auto fe3d = new H1_FECollection(order, 3);
auto Vh3d = new ParFiniteElementSpace(Th3d, fe3d);
ParGridFunction wh(Vh3d);
ParSubMesh::Transfer(vh, wh);
```

**Comment by jandrej** [comment]
Refining a `SubMesh` and reusing it for transfer is not well defined. It's not the intended use case since the refined mesh is now detached from the dependency graph of the Vdofs from its parent.

**Comment by zhaog6** [comment]
I see, thank you @jandrej @kmittal2 , I implemented the demo based on GSLIB & MFEM interface for parallel interpolation from 2D to 2D boundary surface mesh of 3D mesh, it works well. I'd like to ask if I can extract the corresponding parallel interpolate matrix (because I want to preallocate it outside of time iterations and only perform sparse matrix-vector multiplication operations during time iterations). Thanks.
