### ISSUE TITLE
Is parallel hp-refinement supported by MFEM so far?

### ISSUE THREAD

**Issue by Wayne901** [mfem/mfem#3715]
Hi, 
I saw an issue in 2019 that local p-refinement hasn't been implemented, 
and in MFEM release 4.3 the serial hp-refinement is supported. 
Do we support parallel hp-refinement for conformal elements so far?

**Comment by tzanio** [comment]
> Do we support parallel hp-refinement for conformal elements so far

Sorry, there is currently no support for this.

**Comment by Wayne901** [comment]
That’s a bit of a pity. Thank you.
