### ISSUE TITLE
mfem-4.5.2 places a non-existent directory /usr/local/include/superlu into /usr/local/share/mfem/config.mk

### ISSUE THREAD

**Issue by yurivict** [mfem/mfem#3721]
With the SuperluDist option "on" mfem-4.5.2 adds this line into ```/usr/local/share/mfem/config.mk```:
> MFEM_TPLFLAGS  =  -I/usr/local/include -I/usr/local/include/superlu

/usr/local/include/superlu doen't exist,superlu-dist-8.1.2:  installs headers into ```/usr/local/include```:
```
$ pkg info -l superlu-dist
superlu-dist-8.1.2_1:
	/usr/local/include/dcomplex.h
	/usr/local/include/dlustruct_gpu.h
	/usr/local/include/gpu_api_utils.h
	/usr/local/include/gpu_wrapper.h
	/usr/local/include/machines.h
	/usr/local/include/psymbfact.h
	/usr/local/include/slustruct_gpu.h
	/usr/local/include/superlu_FCnames.h
	/usr/local/include/superlu_FortranCInterface.h
	/usr/local/include/superlu_ddefs.h
	/usr/local/include/superlu_defs.h
	/usr/local/include/superlu_dist_config.fh
	/usr/local/include/superlu_dist_config.h
	/usr/local/include/superlu_enum_consts.h
	/usr/local/include/superlu_mod.mod
	/usr/local/include/superlu_sdefs.h
	/usr/local/include/superlu_zdefs.h
	/usr/local/include/superlupara_mod.mod
	/usr/local/include/supermatrix.h
	/usr/local/include/util_dist.h
	/usr/local/include/zlustruct_gpu.h
	/usr/local/lib/libsuperlu_dist.a
	/usr/local/lib/libsuperlu_dist.so
	/usr/local/lib/libsuperlu_dist.so.8
	/usr/local/lib/libsuperlu_dist.so.8.1.2
	/usr/local/lib/libsuperlu_dist_fortran.a
	/usr/local/lib/libsuperlu_dist_fortran.so
	/usr/local/lib/libsuperlu_dist_fortran.so.8
	/usr/local/lib/libsuperlu_dist_fortran.so.8.1.2
	/usr/local/libdata/pkgconfig/superlu_dist.pc
	/usr/local/share/doc/superlu-dist/ug.pdf
```

```config/cmake/modules/FindSuperLUDist.cmake``` sets the ```SuperLUDist_LIBRARIES=/usr/local/include/superlu``` which is wrong.

```config/cmake/modules/FindSuperLUDist.cmake``` should detect the actual location of the headers instead of assuming that it has a particular path.

FreeBSD 13.2

**Comment by tzanio** [comment]
@pghysels can you help with this?

**Comment by pghysels** [comment]
I'll look at it tonight

**Comment by pghysels** [comment]
@yurivict do you mean that the `mfem_find_package` routine needs to be improved?
@tzanio perhaps the MFEM CMake expert should look at this.

**Comment by yurivict** [comment]
> do you mean that the mfem_find_package routine needs to be improved?

I think so.

**Comment by v-dobrev** [comment]
@yurivict,

We've discussed this issue before. Please read my post here: https://github.com/mfem/mfem/issues/3171#issuecomment-1337401334.
