### ISSUE TITLE
Function for remesh in MFEM?

### ISSUE THREAD

**Issue by sungho91** [mfem/mfem#3724]
Hi all,

I have a quick question regarding my current work.

I am in need of remeshing my model due to highly deformed elements. During my research, I came across a tool called Rodin, which utilizes mfem and a third-party open-source library called mmg.

Before delving deeper into Rodin, I wanted to inquire whether we have a built-in remeshing function in mfem or any other alternative options available.

Thank you in advance for your assistance.

Best regards,

Sungho

**Comment by kmittal2** [comment]
Hi @sungho91, what kind of geometry/domain are we talking about?
We have some topology preserving methods for mesh improvement (r-adaptivity) where we move the mesh nodes to improve mesh quality ([`pmesh-optimizer` miniapp](https://github.com/mfem/mfem/blob/master/miniapps/meshing/pmesh-optimizer.cpp)). We also have some support for generating body-fitted meshes if the domain boundary is defined as a level-set function ([`pmesh-fitting` miniapp](https://github.com/mfem/mfem/blob/master/miniapps/meshing/pmesh-fitting.cpp)).

Ketan

**Comment by sungho91** [comment]
Hi @kmittal2, thank you for your comments. 

I used square type for mesh and this has hanging nodes because I locally refined the mesh (see att.).

I should go over mesh-optimizer and fitting. Thank you!

Sungho

![mesh](https://github.com/mfem/mfem/assets/40257026/37dcaecb-65d1-4c9f-9612-5d4d53fc629e)

**Comment by sungho91** [comment]
@kmittal2
