### ISSUE TITLE
`Submesh::From::Boundary` for nonconforming mesh

### ISSUE THREAD

**Issue by sebastiangrimberg** [mfem/mfem#3727]
Right now, both the `SubMesh` and `ParSubMesh` constructors don't allow construction from an NC parent mesh (checked in the constructor). Upon first glance, I think that if the use case is `From::Boundary` and the boundary is an external one (all faces have elements only on one side) that this should work just fine. I just want to check my understanding here, and also if there is an easy way to check this for the user in the constructor that the boundary attributes are true external boundaries.

Pinging @jandrej @mlstowell as the experts, thanks!

**Comment by jandrej** [comment]
I think what you are stating here is correct. Iff the `SubMesh` is extracted from a boundary, the conforming and non-conforming cases are equivalent. 

I did not involve a constructor from `NCMesh` since this class is vastly different from the regular `Mesh` and unfortunately requires a separate implementation of `SubMesh`.

**Comment by sebastiangrimberg** [comment]
OK, makes sense. I am just testing out something like the following and it seems to work fine:

```
diff --git a/mesh/submesh/psubmesh.cpp b/mesh/submesh/psubmesh.cpp
index b316d8b41..2a0e264a6 100644
--- a/mesh/submesh/psubmesh.cpp
+++ b/mesh/submesh/psubmesh.cpp
@@ -38,10 +38,8 @@ ParSubMesh ParSubMesh::CreateFromBoundary(const ParMesh &parent,
 ParSubMesh::ParSubMesh(const ParMesh &parent, SubMesh::From from,
                        Array<int> &attributes) : parent_(parent), from_(from), attributes_(attributes)
 {
-   if (Nonconforming())
-   {
-      MFEM_ABORT("SubMesh does not support non-conforming meshes");
-   }
+   MFEM_VERIFY(from == SubMesh::From::Boundary || !Nonconforming(),
+               "ParSubMesh does not support non-conforming meshes with From::Domain");

    MyComm = parent.GetComm();
    NRanks = parent.GetNRanks();
diff --git a/mesh/submesh/submesh.cpp b/mesh/submesh/submesh.cpp
index ac2058c57..2620bfb0f 100644
--- a/mesh/submesh/submesh.cpp
+++ b/mesh/submesh/submesh.cpp
@@ -31,10 +31,8 @@ SubMesh SubMesh::CreateFromBoundary(const Mesh &parent,
 SubMesh::SubMesh(const Mesh &parent, From from,
                  Array<int> attributes) : parent_(parent), from_(from), attributes_(attributes)
 {
-   if (Nonconforming())
-   {
-      MFEM_ABORT("SubMesh does not support non-conforming meshes");
-   }
+   MFEM_VERIFY(from == From::Boundary || !Nonconforming(),
+               "SubMesh does not support non-conforming meshes with From::Domain");

    if (from == From::Domain)
    {
```

As you confirm, this works when the boundary is conforming, and fails in `FinalizeTopology` when a face is nonconforming (which never happens so long as the boundary is not internal to the domain).

**Comment by jandrej** [comment]
I'm not that familiar with the restrictions of NCMesh, can the boundary not have non-conforming elements? In 3D you have quads on the boundary which you can happily refine in a non-conforming manner I thought.

There should be a way to check when `From::Boundary` tries to use an interior boundary. Simply going through the elements and verifying that there's only one face neighbor suffices.

**Comment by sebastiangrimberg** [comment]
See #3766 for a proposed solution.

**Comment by hughcars** [comment]
Fixed in https://github.com/mfem/mfem/pull/4476 for exterior boundary and volume submeshes.
