### ISSUE TITLE
How to interpolate between two 2D non-nested meshes in MFEM

### ISSUE THREAD

**Issue by zhaog6** [mfem/mfem#3729]
Dear MFEM team,

I'd like to interpolate ParGridFunction from one grid to another, and these two grids are parallel distributed and non-nested. What can I do to deal with it in MFEM? Thanks.

**Comment by mlstowell** [comment]
Have you seen our [overlapping grid](https://github.com/mfem/mfem/blob/master/miniapps/gslib/schwarz_ex1p.cpp) miniapp? This shows some of the relevant MFEM capabilities. Ping @kmittal2

**Comment by zhaog6** [comment]
Thank you Mark @mlstowell ,Ketan @kmittal2 , this originates from the issue #3714. I'll try it.

**Comment by kmittal2** [comment]
@zhaog6 closing this issue for now. Discussion continued in #3714.
