### ISSUE TITLE
parallel running ex17p wrong, if change the lambda_c as a GridFunctionCoefficient

### ISSUE THREAD

**Issue by QibangLiu** [mfem/mfem#3732]
Hello, I change the   PWConstCoefficient lambda_c to GridfunctionCoefficient lambda_c in ex17p, then the parallel running does not work, and get "nan" during the iteration. But, the serial running works very well

Below is the code I used to define the lame constant lambda
```c++
ParGridFunction lam_grid(&fespace);
   GridFunctionCoefficient lambda_c(&lam_grid);
    for (int i = 0; i < lam_grid.Size(); i++)
    {
        lam_grid(i) = 1.0;
    }
    lam_grid.ExchangeFaceNbrData();
``` 
is there any clue to solve it? Thanks.

**Comment by psocratis** [comment]
@QibangLiu, 

I suspect that you are using the "wrong" DG space to define the `GridFunction`. If you want to define a piece-wise constant in the domain you can use a **scalar** DG space. The DG space used in ex17p for the discretization is a **vector** FE space (ie. multiple copies of the scalar one). This is given by the argument `dim` in the constructor `ParFiniteElementSpace fespace(&pmesh, &fec, dim, Ordering::byVDIM);` You can define a scalar DG space by omitting the last two arguments.

I hope this helps.

Best,

Socratis

**Comment by QibangLiu** [comment]
Oh, you are right. I forgot the fespace is defined as vector space. Thanks, @psocratis
