### ISSUE TITLE
Appropriate smoothers for H(curl) space

### ISSUE THREAD

**Issue by Wayne901** [mfem/mfem#3736]
Hello my friends,

I'm a novice about the multigrid preconditioners for Nedelec elements. This question
is not totally about MFEM coding, but more on math concepts (sorry if it's not appropriate as an issue here).

I plan to solve a time-harmonic Maxwell's problem with multigrid method. From my best knowledge, there
are 2 crucial challenge (the latter confuse me):

1. Time-harmonic systems itself is indefinite (curlcurlE-k^2E). Given I want to solve EM problem of RF devices
which are small compared to wavelength, this challenge is partially resolved by a dense coarse level.
**2.** Smoothers suitable for Nedelec elements. Traditional smoother for H1 doesn't work due to **large kernel of 
curl-curl operator**, and "... the main difficulty stems from the different scaling of solenoidal
and irrotational fields in the curl-curl problem ..." as mention by [Zaglmayr phd thesis 2006](https://www.numerik.math.tugraz.at/~zaglmayr/pub/szthesis.pdf) .

To my best knowledge, there are 3 categories for H(curl) smoothers:

- The smoothers of Arnold-Falk-Winther (2000) and Hiptmair (1999). They construct a block multiplicative Schwarz preconditioners
   for lowest order level, based on space decomposition w.r.t. vertex patches
![image](https://github.com/mfem/mfem/assets/52063692/12b83510-87fa-4b41-b665-16c0d190aa44)
- Preconditioners of Schöberl (developer of NGSolve & NETGEN) /Zaglmayr ([phd thesis 2006](https://www.numerik.math.tugraz.at/~zaglmayr/pub/szthesis.pdf) & [2010](https://pure.tugraz.at/ws/portalfiles/portal/52568032/1_s2.0_S0045782510002227_main.pdf)). They rearrange dofs according to low-order Nedelec space, high-order gradient space, and high-order non-gradient space. I haven't understand if it's applied to local patches to form block Schwarz preconditioners, or it arranges dofs globally. It's similar to [pMUS](https://ieeexplore.ieee.org/document/1273728) preconditioner in Ansys HFSS.
- Preconditioners based on Hiptmair ([2007](https://en.wikipedia.org/wiki/Hiptmair%E2%80%93Xu_preconditioner)), and Tzanio ([2015](https://library.seg.org/doi/10.1190/geo2015-0013.1)) previously based on deal.II. This kind construct auxiliary space on nodes (and fall into the AMG and AMS class ?)

My biggest question is, which smoother is the most optimal, in case of indefinite Maxwell problem. All Maxwell examples in MFEM apply AMG, but I want to use h- or p-GMG because it allows solving coarsest grid directly (my understanding might be wrong). AMG and AMS preconditioners won't converge.

The second question is, is Nedelec basis functions in MFEM written hierachically? I remember to enable partial assembly for Hcurl space, MFEM chooses a tensor-product Nedelec basis function.

The last problem is, are all above smoothers allow partially assemble? May static condensation ([Tzanio 2017](https://epubs.siam.org/doi/10.1137/17M1132562)) fit into matrix-free FEM?

**Comment by tzanio** [comment]
Hi @Wayne901,

Most of the papers above are for the _definite_ (time-domain) Maxwell case, for which a solver like AMS works really well, see Example 3p.

The _indefinite_ (frequency-domain) case is much more complicated and we really don't have a solver like AMS for it. @psocratis is the expert on this, and can share his experience.

Tzanio

**Comment by Wayne901** [comment]
Well, let me change the questions more simple?

It's known that AMS alone cannot solve the indefinite Maxwell problem. I plan to precondition
the system with p-multigrid first to produce a lowest-order level, then using direct solver or further
precondition with h- or algebraic multigrid. To apply this strategy, I have 2 questions about MFEM

1) **Do Nedelec basis functions in MFEM formulate hierarchically?** I hope to renumber the dofs according
to lowest-order edge dofs, gradient edge dofs, face dofs and cell dofs. In this manner, we won't need
special smoothers for functions in H(curl) space.

2) Then about the coarsest level. Since the indefinite Maxwell is hard to converge, I'd like to directly
solve a coarse system as large as possible (if lowest-order level to big, then project it to a coarser level). 
On the one hand, h-multigrid allows me to construct 2 levels for the lowes-order system and a direct coarse 
level solver, but it requires special smoothers for H(curl) functions. On the other hand, AMS is a good 
smoother for H(curl) functions while it cannot be combined with a direct solver. **Then can I construct 
an H(curl) function-friendly smoother and combine it with h-multigrid?**

Wayne

**Comment by psocratis** [comment]
Hi @Wayne901,

As @tzanio mentioned above the indefinite time-harmonic system is very hard to solve especially in the high-frequency regime. One of the main issues, when you try to use multigrid methods, is the instability of the course system. In other words, the coarse system has to be "fine" enough in order to have discrete stability and when you lack discrete stability the solver will diverge. Therefore, the coarse system is itself very expensive to solve with direct solvers. Having said that, in some cases where the frequency is not so large you can indeed get away with it, as long as you can solve the coarse system (it all depends on the hardware etc). The second issue in multigrid methods is indeed the smoothers because they fail to "smooth" the high-frequency components on the fine grid. There are various other works on the subject, I'll refer you to [this](https://epubs.siam.org/doi/abs/10.1137/16M109781X) review paper that goes over what is out there (even if the paper is for Helmholtz, many of its concepts apply to Maxwell as well). There is some old work of mine in `mfem` implementing the "Source Transfer preconditioner" for Maxwell, however as many other works out there it's very limited to specific geometries and boundary conditions. You can take a look [here](https://github.com/mfem/mfem/tree/DST-maxwell-solver-dev). 

I hope this helps.

Best,

Socratis

**Comment by Wayne901** [comment]
Hi @psocratis,

Fortunately, the problem of my interest is not very "high-frequency" (less than 3~4 wavelength), so the coarse level is solvable with direct methods. But the geometry is intricate so sweeping preconditioners lost their advantage.

As you state, "the second issue in multigrid methods is indeed the smoothers because they fail to 'smooth' the high-frequency components on the fine grid". Sorry to be verbose, but is this failure caused by the large NULL space of Maxwell wave equation, or by the indefinite of both Maxwell's wave equation and Helmholtz equation? If it's the latter, why there are many works on the specific preconditioners of definite Maxwell's equation, like AMS, etc. 

Actually, my biggest concern is by applying a straightforward multigrid preconditioner on H(curl) problems will fail, even a "fine" enough coarse level is solved directly.

Best,
Wayne

**Comment by Wayne901** [comment]
In the case of the Nedelec basis function's formulation, i should open another issue.
