### ISSUE TITLE
Computing principle strains for ex2p

### ISSUE THREAD

**Issue by shani9383** [mfem/mfem#3738]
Hi,
I modified ex2p to compute the strain components. Now I’m a bit lost how to use the strain components to compute the principle strains (eigen values of the strain tensorat each point). I couldn’t find any example for this. Can you please help with an example.
Thanks, Shani.
To find the principle strains I need to:
1.	 compute the following invariants: 
I_1= e11+e22+e33=trace(e)
I_2=e11*e22+e11*e33+e22*e33-(e12)^2-(e13)^2-(e23)^2
I_3=det(e)= e11*(e22*e33-(e23)^2)-e12*(e12*e33-e23*e13)+e13*(e12*e23-e22*e13)
2.	Solve the polynomic equation: (e_p)^3-I_1 *(e_p)^2+I_2* e_p-I_3=0
Where e_p represents the principle strain values.  The largesrt value is e_p1 and the smallest is e_p3.  

My code is:
```c++
// Before the main fun:
class StrainCoefficient : public Coefficient // A Coefficient for computing the components of the strain.
{
protected:
   Coefficient &lambda, &mu;
   GridFunction &u; // displacement
   int ei, ej; // component of the strain to evaluate, 0 <= ei,ej < dim
   DenseMatrix grad; // auxiliary matrix, used in Eval
public:
   StrainCoefficient(GridFunction &_u, Coefficient &lambda_, Coefficient &mu_)
      : u(_u), lambda(lambda_), mu(mu_), ei(0), ej(0) { }
   void SetComponent(int i, int j) { ei = i; ej = j; }
   virtual double Eval(ElementTransformation &T, const IntegrationPoint &ip);
};

// In the main function: 
ParFiniteElementSpace strain_fespace(pmesh, fec);
StrainCoefficient strain_c(x, lambda_func, mu_func);
for (int ei = 0; ei < dim; ei++)
      {
      for (int ej = ei; ej < dim; ej++)
         {
          ParGridFunction strain(&strain_fespace);
          strain_c.SetComponent(ei, ej);
          strain.ProjectCoefficient(strain_c);
          ostringstream strain_name;
          strain_name << "strain" << ei << ej << "." << setfill('0') << setw(6) << myid;
         ofstream strain_ofs(strain_name.str().c_str());
         strain_ofs.precision(8);
         strain.Save(strain_ofs);
        }
// After the main function:
double StrainCoefficient::Eval(ElementTransformation &T,
                               const IntegrationPoint &ip)
{
   MFEM_ASSERT(u != NULL, "displacement field is not set");
   double L = lambda.Eval(T, ip);
   double M = mu.Eval(T, ip);
   u.GetVectorGradient(T, grad);
   if (ei == ej)
   {
      return grad(ei,ei);
   }
   else
   {
      return 0.5*(grad(ei,ej) + grad(ej,ei));
   }
}
```

edited by @jandrej for code readability

**Comment by ddkn** [comment]
I had similar questions earlier, and saw that in issues [3535](https://github.com/mfem/mfem/issues/3535), [3284](https://github.com/mfem/mfem/issues/3284), and []() you really want to inherit from `VectorCoefficient` instead of `Coefficient`. 

I think once you use your _new_ class `StrainVectorCoefficient` you have the $\epsilon$ matrix calculated as `StrainVectorCoefficient.grad` and can grab the components there once evaluated.

While I am working on this in [PyMFEM:184](https://github.com/mfem/PyMFEM/issues/184), you can see the basics there, for a stress. So you would just not calculate `sigma`, but could assign a vector `s` appropriately as components from `grad`.

Where I am unsure is that in the C++ example in my issue, is the ever increasing vector `s`, which _I may_ interpret as all the strains of the _elements_ of the system (**I am not sure so please someone should clarify**), which would make more sense if you have an object with multiple attributes, such as in ex2 and ex17. So maybe that makes sense to extract all the principle strains to save space, but you could just keep appending `grad` over and over.

My issue is trying to solve something else, but starts with the same problem you are having. I think there is more MFEM coders in C++ than there is in PyMFEM, but they are quite similar in execution.

**Comment by shani9383** [comment]
Thanks. I’m actually trying to use LOBPCG to get the Eigenvalues of the strain tensor (ex12p highlights the use of the LOBPCG eigenvalue solver). 
I think my main problem is how to assemble the strain tensor ParGridFunction into a HypreParMatrix that is required for solving the Eigen problem (hope I’m not writing nonsense:) ).

I would appreciate any help, I’m stuck.

class StrainCoefficient : public Coefficient // A Coefficient for computing the components of the strain.
{
protected:
   Coefficient &lambda, &mu;//material properties
   GridFunction &u; // displacement
   int ei, ej; // component of the strain to evaluate, 0 <= ei,ej < dim
   DenseMatrix grad; // auxiliary matrix, used in Eval
   
public:
   StrainCoefficient(GridFunction &_u, Coefficient &lambda_, Coefficient &mu_)
      : u(_u), lambda(lambda_), mu(mu_), ei(0), ej(0) { }


   void SetComponent(int i, int j) { ei = i; ej = j; }

   virtual double Eval(ElementTransformation &T, const IntegrationPoint &ip);
};

//in the main function:

      ParFiniteElementSpace strain_fespace(pmesh, fec);
      StrainCoefficient strain_c(x, lambda_func, mu_func); 
      ParGridFunction sp(&strain_fespace);
      for (int ei = 0; ei < dim; ei++)
      {
         for (int ej = ei; ej < dim; ej++)
         {
            ParGridFunction strain(&strain_fespace);
            strain_c.SetComponent(ei, ej);
            strain.ProjectCoefficient(strain_c);            
            sp += strain; // Accumulate the values in the sp grid function 
        }
    }

    **HypreParMatrix SP = sp.ParallelAssemble(); // How to Create a HypreParMatrix from sp ParGridFunction?**
    
   HypreBoomerAMG *amg = new HypreBoomerAMG(SP);
   if (amg_elast)
   {
      amg->SetElasticityOptions(fespace);
   }
   else
   {
      amg->SetSystemsOptions(dim);
   }

   HyperLOBPCG * lobpcg = new HypreLOBPCG(MPI_COMM_WORLD);
   lobpcg->SetRandomSeed(seed);
   lobpcg->SetOperator(SP);
   lobpcg->SetTol(1e-8);
   lobpcg->SetMaxIter(100);
   lobpcg->SetNumModes(nev);
   lobpcg->SetPreconditioner(*amg);
   Array<double> eigenvalues;
   lobpcg->Solve();
   lobpcg->GetEigenvalues(eigenvalues);

   ParGridFunction E(&strain_fespace);
   
   for (int i = 0; i < nev; i++)
   {
      // Set the constant value of the ParGridFunction to the eigenvalue
      E = eigenvalues[nev - i - 1];  // Reverse the order of eigenvalues
  
      // Create ParaView data collection
      ostringstream E_name;
      E_name << "E_" << setfill('0') << setw(2) << i << "."
             << setfill('0') << setw(6) << myid;

      ofstream E_ofs(E_name.str().c_str());
      E_ofs.precision(8);
      E.Save(E_ofs);
      E_ofs.close();

      ostringstream pd_name;
      pd_name << "E" << i;

      ParaViewDataCollection *E_pd = new ParaViewDataCollection(E_name.str().c_str(), pmesh);
      E_pd->SetPrefixPath("ParaView");
      E_pd->RegisterField(pd_name.str().c_str(), &E);
      E_pd->SetLevelsOfDetail(order);
      E_pd->SetDataFormat(VTKFormat::BINARY);
      E_pd->SetHighOrderOutput(true);
      E_pd->SetCycle(0);
      E_pd->SetTime(0.0);
      E_pd->Save();
      delete E_pd;
   }


After main:

double StrainCoefficient::Eval(ElementTransformation &T,
                               const IntegrationPoint &ip)
{
   MFEM_ASSERT(u != NULL, "displacement field is not set");

   double L = lambda.Eval(T, ip);
   double M = mu.Eval(T, ip);
   u.GetVectorGradient(T, grad);
   if (ei == ej)
   {
      return grad(ei,ei);
   }
   else
   {
      return 0.5*(grad(ei,ej) + grad(ej,ei));
   }
}


Thanks
Shani
