### ISSUE TITLE
6/64 Test  #6: sedov_tests_cuda_uvm Exception: SegFault  0.31 sec

### ISSUE THREAD

**Issue by patrick-njit** [mfem/mfem#3741]
Exception: SegFault in sedov_tests_cuda_uvm. All other tests pass. See the output copied below

```
6/64 Testing: sedov_tests_cuda_uvm
6/64 Test: sedov_tests_cuda_uvm
Command: "/home/patrick/karypis/mfem-4.5.2/build/tests/unit/sedov_tests_cuda_uvm"
Directory: /home/patrick/karypis/mfem-4.5.2/build/tests/unit
"sedov_tests_cuda_uvm" start time: Jun 18 18:22 EDT
Output:
----------------------------------------------------------
INFO: Test filter: ~[Parallel] ~[MFEMData]
Filters: ~[Parallel] ~[MFEMData]
Zones min/max: 4 4
Number of local/global kinematic (position, velocity) dofs: 50/50
Number of local/global specific internal energy dofs: 16/16

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
sedov_tests_cuda_uvm is a Catch v2.13.9 host application.
Run with -? for options

-------------------------------------------------------------------------------
Sedov
-------------------------------------------------------------------------------
/home/patrick/karypis/mfem-4.5.2/tests/unit/miniapps/test_sedov.cpp:2212
...............................................................................

/home/patrick/karypis/mfem-4.5.2/tests/unit/miniapps/test_sedov.cpp:2212: FAILED:
due to a fatal error condition:
  SIGSEGV - Segmentation violation signal

===============================================================================
test cases: 1 | 1 failed
assertions: 1 | 1 failed

<end of output>
Test time =   0.31 sec
----------------------------------------------------------
Test Failed.
"sedov_tests_cuda_uvm" end time: Jun 18 18:22 EDT
"sedov_tests_cuda_uvm" time elapsed: 00:00:00
----------------------------------------------------------
```

**Comment by v-dobrev** [comment]
Can you please provide some more context: cuda device used, compilers, hypre version and config (cuda or no cuda), and mfem config flags.

**Comment by patrick-njit** [comment]
I'm running a NVIDIA GeForce RTX 3060 (driver version 31.0.15.3598). I am compiling mfem with nvcc and gcc with the following flags

`cmake -S . -B build/ -DCMAKE_CUDA_COMPILER=nvcc -DMFEM_USE_CUDA=YES -DMFEM_USE_SUITESPARSE=YES -DMETIS_DIR=~/local`

The compiler versions are as follows 

```
$ /usr/local/cuda/bin/nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Mon_Apr__3_17:16:06_PDT_2023
Cuda compilation tools, release 12.1, V12.1.105
Build cuda_12.1.r12.1/compiler.32688072_0

$ gcc --version
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

The code is running in WSL2, see [here](https://docs.nvidia.com/cuda/wsl-user-guide/index.html) for more information.

**Comment by v-dobrev** [comment]
Can you try adding the flag for your GPU architecture: either `-DCMAKE_CUDA_ARCHITECTURES=86` or `-DCUDA_ARCH=sm_86`? I think `86` is the right version for your hardware based on the info here: https://www.nvidia.com/en-us/geforce/graphics-cards/30-series/rtx-3060-3060ti/ (click Specs -> View Full Specs).

**Comment by patrick-njit** [comment]
I have tried both flags for the GPU architecture separately and get the same seg fault

**Comment by v-dobrev** [comment]
Okay, looking at https://docs.nvidia.com/cuda/wsl-user-guide/index.html#known-limitations-for-linux-cuda-applications, it looks like unified memory (aka UVM) is not supported under WSL2. The example that is failing for you, `sedov_tests_cuda_uvm`, uses unified memory allocations using `cudaMallocManaged`, so it is not a surprise that it fails.

You can simply ignore this failure. You can still use the default (and recommended) CUDA memory allocation mechanism in MFEM which uses `cudaMalloc` for device memory allocations.
