### ISSUE TITLE
Can a boundary element have two sides?

### ISSUE THREAD

**Issue by hughcars** [mfem/mfem#3744]
Given an internal surface, say between two different domain attributes, if you want to introduce an "internal boundary" on this face, should the boundary be introduced once or twice? I.e. should an internal boundary have left and right, or should there be two boundary elements, each with just a left hand side? 

I ask, because within the `NCMesh` structure, there is [this loop](https://github.com/mfem/mfem/blob/master/mesh/ncmesh.cpp#L2489) wherein boundary elements are added by looping first over elements, then faces of those elements. Such an internal boundary is thus visited twice. Thus if a single internal boundary element is added on an initial mesh, then partitioned, the resulting mesh will have different numbers of boundary elements if `EnsureNCMesh(true)` is called before partitioning or not. 

See hughcars/ncmesh-interior-boundary-dev for an example of modifying the `beam-hex.mesh` with an internal boundary that demonstrates this issue in `test_ncmesh.cpp`, along with a fix for the case of conformal faces, wherein the boundary element is only added from the last element to visit it. The fix for a nonconformal face is more involved, and would be achieved by only adding boundary elements on slave faces (to avoid double counting). Before I go ahead with figuring this out however, I wanted to see what the mfem developers philosophical position is on this issue: do boundary elements only have one side? As depending on the answer, the resulting PR would be accepted or rejected.

**Comment by v-dobrev** [comment]
As you probably know, the boundary elements in the `Mesh` class are described separately from the faces and so it is possible to have multiple boundary elements (each with its own, potentially different, attribute) that correspond to the same face. Depending on the context, this may be useful but I'm not sure if anyone is specifically relying on this.

When a `Mesh` is converted to an `NCMesh`, this separate description of the boundary elements is lost. In particular, if an `NCMesh` face corresponds to multiple boundary elements, only the attribute of the last boundary element is stored. Also, the orientation of all boundary elements is lost. (@jakubcerveny can correct me if I'm missing something.)

Depending on what you need, we may need to add some data to the `NCMesh` to store multiple boundary elements per face with their attributes and orientations.

If you do not need multiple boundary elements per face and you do not need to preserve the boundary face orientations (for interior "boundary" elements) then the current `NCMesh` may be sufficient. In this case, to me it makes sense to construct a single boundary element from each face when the face is conforming. When the face is nonconforming, it probably makes most sense to use the refined (slave) side faces as boundary elements and leave the master side out, i.e. do not add it as a boundary element. Both of these cases are the same as what you are suggesting, if I understand you correctly.

**Comment by hughcars** [comment]
Thank you for the response @v-dobrev, indeed that 1:1 mapping from boundary element to face is what I opted for in the end. I have a draft pr (still ironing a few issues with) at https://github.com/mfem/mfem/pull/3746, where I change the discovery of boundary elements for NCMeshes to match this model. Previously the loop would create 2 boundary elements per internal face, but with the changes, it should be only one, and master faces will not be included (as their face data will be captured from all the slave faces).

 I suspect it was just a case of an overlooked corner case that meant the NC behaved differently, so hopefully that PR (once finished) will fix the issue.
