### ISSUE TITLE
Recreate Ex2 mesh in gmsh

### ISSUE THREAD

**Issue by ddkn** [mfem/mfem#3748]
Hello,

I am trying [gmsh](https://gmsh.info/) recreate a mesh for use in [example 2](https://github.com/mfem/mfem/blob/master/examples/ex2.cpp) while using the [beam-tet.mesh](https://github.com/mfem/mfem/blob/master/data/beam-tet.mesh). I haven't had any luck with getting the expected output and I am at a loss here. I did try to create the structure with two volumes as outlined by the example: 

![image](https://github.com/mfem/mfem/assets/13819239/e3279f43-4f28-4492-a6c1-8d2d3a277543)

I have tried changing the following,

* Change the which surface the `ess_bdr` is on
* Change the index of the `pull_force` vector
* Change which direction the beam is created x-dir in the zip file included
* Tried ensuring `Physical Volume` and `Physical Surface` have unique identifiers
* Tried ensuring `Physical Volume` and `Physical Surface` have same identifiers

GLVis shows that there is 3 attributes to interact with as seen below. I also show the output from the example, as well as the expected output from *beam-tet.mesh*

Does anyone have any guidance for using gmsh with mfem? I will be creating a more complicated structure, but was having issues in just replicating the example. Any help would be greatly appreciated.

Cheers,

*PS* I should be on v4.5.2

**untitled.geo** *saved in msh22 format*
```
// Gmsh project created on Thu Jun 22 09:03:42 2023
SetFactory("OpenCASCADE");
//+
Box(1) = {0, 0, 0, 10, 2, 2};
//+
Box(2) = {10, 0, 0, 10, 2, 2};
//+
Physical Surface(1) = {1};
//+
Physical Surface(2) = {8};
//+
Physical Surface(3) = {12, 6, 3, 5, 4, 10, 11, 9};
//+
Physical Volume(4) = {1};
//+
Physical Volume(5) = {2};
```
[untitled.zip](https://github.com/mfem/mfem/files/11834686/untitled.zip)

### Mesh from gmsh
![image](https://github.com/mfem/mfem/assets/13819239/c067c336-e933-4eb9-ae2c-4616f380f401)

![image](https://github.com/mfem/mfem/assets/13819239/bb802d8e-38c0-40ba-aff0-4dae583933d7)

![image](https://github.com/mfem/mfem/assets/13819239/b532b5cd-37f8-4270-af5a-b3a2757f5e48)

![image](https://github.com/mfem/mfem/assets/13819239/8446dc17-9ee8-4fa2-9403-57d7d0bf9c31)

### untitled.msh output from example 2

![image](https://github.com/mfem/mfem/assets/13819239/4b1ed01e-acc6-4dcd-8452-6a230bda747e)

### beam-tet.mesh output from example 2
![image](https://github.com/mfem/mfem/assets/13819239/4ee5da71-ed6c-4b42-91a0-9510e9df09a0)

![image](https://github.com/mfem/mfem/assets/13819239/bb07b23b-3e06-4e36-bca7-79d7b3d571ad)

![image](https://github.com/mfem/mfem/assets/13819239/bf15c721-b797-4983-80de-8ca8c7824304)

**Comment by jandrej** [comment]
You don't generate 3D volume elements as you can see in the last picture. Also make sure to export from Gmsh as ASCII V2.

**Comment by pazner** [comment]
The problem with your mesh is that the two boxes you create are not connected — they are just considered two separate volumes that are adjacent. To "merge" them, you need to use `Coherence`. This will renumber some of the surfaces too. The following gmsh geo file should work for you:

```
SetFactory("OpenCASCADE");
//+
Box(1) = {0, 0, 0, 10, 2, 2};
//+
Box(2) = {10, 0, 0, 10, 2, 2};
//+
Physical Volume(1) = {1};
//+
Physical Volume(2) = {2};
//+
Coherence;
//+
Physical Surface(1) = {1};
//+
Physical Surface(2) = {7};
//+
Physical Surface(3) = {3, 4, 5, 6, 8, 9, 10, 11};
```

**Comment by ddkn** [comment]
Thanks @jandrej and @pazner for responding!

@panzer, Your supplied geo file works great! However, I am at a loss now for another issue. As you said, surfaces become renumbered. But when I use the GUI, I generate

```
SetFactory("OpenCASCADE");                                                                                                                                                                   
//+                                                                                                                                                                                          
Box(1) = {0, 0, 0, 10, 2, 2};                                                                                                                                                                
//+                                                                                                                                                                                          
Box(2) = {10, 0, 0, 10, 2, 2};                                                                                                                                                               
//+                                                                                                                                                                                          
Physical Volume(1) = {1};                                                                                                                                                                    
//+                                                                                                                                                                                          
Physical Volume(2) = {2};                                                                                                                                                                    
//+                                                                                                                                                                                          
Coherence;                                                                                                                                                                                   
//+                                                                                                                                                                                          
Physical Surface(3) = {1};                                                                                                                                                                   
//+                                                                                                                                                                                          
Physical Surface(4) = {7};                                                                                                                                                                   
//+                                                                                                                                                                                          
Physical Surface(5) = {9, 10, 8, 11, 4, 5, 6, 3};
```

Which increases the `Physical Surface` number, such that it continues where `Physical Volume` left off. The only way *I know* how to force the `Physical Surface` numbers is to do this manually in the **geo** file. Is this possible from the GUI?

From @pazner:
> The problem with your mesh is that the two boxes you create are not connected — they are just considered two separate volumes that are adjacent.

To clarify the difference between `Physical Surface` and `Physical Volume`, let's say with the above example diagram with *material 1* and *material 2* are different materials, such as **Aluminum** and **Steel**. Defining `lambda` and `mu` from `mesh.attributes.Max()` is *effectively* assigning material properties to the `Physical Volumes` correct?

**Comment by jandrej** [comment]
> Also, with the 3rd Physical Surface surrounding the beam, that isn't saying the surface is one material but that they are bonded right?

Yes.

> To clarify the difference between Physical Surface and Physical Volume, let's say with the above example diagram with material 1 and material 2 are different materials, such as Aluminum and Steel. Defining lambda and mu from mesh.attributes.Max() is effectively assigning material properties to the Physical Volumes correct?

Yes.

**Comment by pazner** [comment]
> Which increases the `Physical Surface` number, such that it continues where `Physical Volume` left off. The only way _I know_ how to force the `Physical Surface` numbers is to do this manually in the **geo** file. Is this possible from the GUI?

I think if you remove and then re-add the physical surfaces you can do this, however I would suggest just editing the geo file directly. My experience with gmsh is that while the GUI is convenient for some operations, usually at some point you will want to edit the geo files manually.

> To clarify the difference between `Physical Surface` and `Physical Volume`, let's say with the above example diagram with _material 1_ and _material 2_ are different materials, such as **Aluminum** and **Steel**. Defining `lambda` and `mu` from `mesh.attributes.Max()` is _effectively_ assigning material properties to the `Physical Volumes` correct?

In a 3D gmsh mesh, `Physical Surface` will set the attribute numbers for the associated *boundary elements* (triangles) in the MFEM mesh. `Physical Volume` will set the attribute numbers for the associated *volume elements* (tetrahedra) in the MFEM mesh. (There is some more info at the bottom of [this page](https://mfem.org/mesh-formats/)).

Once subsets of the boundary and volume elements are tagged with attribute numbers, physical interpretations (such as boundary conditions, material properties, etc.) can be assigned in the application itself.

**Comment by ddkn** [comment]
Thanks again @pazner for the clarification and help! I will close this issue.

**Comment by ddkn** [comment]
I couldn't find the old post I made, which was actually addressed in issue [2223](https://github.com/mfem/mfem/issues/2223). So I accidentally made this as a duplicate. I am sorry about that and I am referencing the old issue here so others can see it was in error

I had stepped away from this for a few years and had forgotten what I had don. Thanks again @pazner for helping out!
