### ISSUE TITLE
Challenges with Mesh Refinement and Matrix Assembly in AMR Testing: Memory Issues and Crashes

### ISSUE THREAD

**Issue by sungho91** [mfem/mfem#3751]
Hi all,

I'm testing AMR in a time-step loop, so I enforce mesh refinement every ten steps. Then, I update the finite element space, grid function, and mass matrix.

I can see that the mesh is refined at the given time stamp (attached) and values seem correctly mapped.

However, I'm facing a difficulty at the subsequent time step (i.e., time step 11). I'm using a force matrix that is a mixed bilinear form using H1 and L2 space, and this matrix is assembled twice to calculate velocity and energy. The matrix is updated and assembled when the assembling force function is called. It was fine during the first call, but my model crashed during the second call at **Force.Update()**. It seems to be a memory issue (attached), but I haven't found any clues yet.

Any comments would be helpful for me.

Many thanks,
Sungho

![Error_AMR](https://github.com/mfem/mfem/assets/40257026/7a8b74a7-807f-4192-b8ca-ead081ed39d6)

**Comment by psocratis** [comment]
@sungho91, can you send us your code or a minimal example that you see the same failure? 

Thanks,

Socratis

**Comment by sungho91** [comment]
@psocratis Sure. Let me know your email address and I'll touch with you.

**Comment by psocratis** [comment]
> @psocratis Sure. Let me know your email address and I'll touch with you.

@sungho91, you can post your code here if you don't mind

**Comment by sungho91** [comment]
@psocratis 

I don't mind but first I'd introduce an ongoing project temporally called LHOGS (Lagrangian High-Order Geodynamic Solver), which is an MFEM-based geodynamic solver. LHOGS expands the capabilities of MFEM's LAGHOS mini-app. Currently, my solver incorporates constitutive equation, body force, mass scaling, dynamic relaxation, Mohr-Coulomb plasticity, plastic softening, and Winkler foundation. 

Specifically, I modified non-AMR Laghos from scratch.

There is a directory (Test) including a mesh file. You can run the code with this command "../laghos -dim 2 -rs 2 -ms 11 -vs 1 -m ./2d_mesh_local.mesh -visit -rstep 10". You can build my code with hypre, METIS, mfem (see how to build on https://github.com/sungho91/Laghos). 

Thanks.


[20230626_LGHOS_amr_test.zip](https://github.com/mfem/mfem/files/11870182/20230626_LGHOS_amr_test.zip)

**Comment by psocratis** [comment]
@sungho91, thanks for sharing the code. I do see the failure on my side though not at step 10. You might want to compile mfem in debugging mode to ensure that an out of bounds leak is caught. When I do that I see the error below at line `1108`.  Also I believe at lines 1122 and 1123 it should be `==`.  

````
Assertion failed: (dofs.Size() == vc.GetVDim()*dof) is false:
 -->
 ... in function: virtual void mfem::PositiveFiniteElement::Project(mfem::VectorCoefficient &, mfem::ElementTransformation &, mfem::Vector &) const
 ... in file: fem/fe/fe_pos.cpp:39
````

Please reach out if the error persists after fixing the above. If that's the case a stack trace would also be helpful. 

Best,

Socratis

**Comment by sungho91** [comment]
@psocratis Thank you for your help. I found my updated block vector differs from the inner block vector.
After making them be consistent, I resolve the problem. So, I think my problem arose from the different sizes of assigned vectors after adaptive refinement. 

By the way, I haven't touched MFEM itself, but I'm surprised that you got that message.
