### ISSUE TITLE
How is Nedelec basis functions formulated in MFEM formulate?

### ISSUE THREAD

**Issue by Wayne901** [mfem/mfem#3758]
Hi my friends,

Are the Nedelec basis functions in MFEM formulated hierarchically? 
I hope to renumber the dofs according to lowest-order edge dofs, gradient edge dofs, face dofs and cell dofs for preconditioning.
However in this figure from MFEM paper, Nedelec bases don't seem to be hierarchical.
![a90f914e2ff104064c60a1d76c2c46b](https://github.com/mfem/mfem/assets/52063692/a54a5aba-86c9-4f27-ba3e-175ddeb06813)

**Comment by mlstowell** [comment]
Hi, @Wayne901,

No, MFEM does not use hierarchical Nedelec basis functions (or any other hierarchical basis functions to my knowledge). I don't know if we can offer any useful advice but @psocratis may have experience with this.

Best wishes,
Mark

**Comment by InfinityHub** [comment]
Hi @Wayne901  I am figuring something similar to your question. Where did you cite your figure ? 

Hi Mark @mlstowell , I wonder if someone can add an additional section in MFEM's documentation pages for degrees of freedom, e..g, under Documentation > Finite Element.  I've seen so many questions and discussions about how we can customize values at particular degrees of freedom (e.g., boundary conditions). :)

**Comment by Wayne901** [comment]
Hi @InfinityHub,
 
The figure is from [MFEM 2021](https://www.sciencedirect.com/science/article/pii/S0898122120302583).

Thank you @mlstowell. I guess Nedelec bases in MFEM are formulated in a "node" manner to best
utilize the tensor-product property for partial assembly?

Best,
Wayne

**Comment by mlstowell** [comment]
> Hi Mark @mlstowell , I wonder if someone can add an additional section in MFEM's documentation pages for degrees of freedom, e..g, under Documentation > Finite Element. I've seen so many questions and discussions about how we can customize values at particular degrees of freedom (e.g., boundary conditions). :)

HI, @InfinityHub,

That's a good suggestion. We do like to hide some of the details so that we have the freedom to make changes when necessary but there are many aspects that should be better documented.

**Comment by mlstowell** [comment]
> Thank you @mlstowell. I guess Nedelec bases in MFEM are formulated in a "node" manner to best utilize the tensor-product property for partial assembly?
> 
That may be part of the reason these days. I'm not sure but I think this choice predates partial assembly by several years. I believe the Nedelec paper describes the DoFs as integrals of the inner product of the field with a set of tangent vectors. It's my understanding that we choose the nodes ($q_i$) and tangent vectors ($\hat{t}_i$) so that we can compute these integrals with single point quadratures ($DoF_i=\vec{V}(q_i)\cdot\hat{t}_i$) because our Nedelec basis functions satisfy: $\vec{W}_j(q_i)\cdot\hat{t}_i = \delta _{ij}$. This makes projection quite efficient. Of course assembly is much more critical than projection so this reasoning may be outdated.

**Comment by tzanio** [comment]
There are other reasons for using a nodal basis, see for example the recent work on LOR preconditioning: https://arxiv.org/pdf/2203.02465.pdf

**Comment by GKDyah** [comment]
Hi @Wayne901, can I get your email account? I'm newbie here. I want to ask you some questions about precondition in private.

**Comment by Wayne901** [comment]
> Hi @Wayne901, can I get your email account? I'm newbie here. I want to ask you some questions about precondition in private.

Hi @GKDyah ,
I previously used other finite-element frameworks, and I'm new to MFEM too. Why not open a new issue about your problem.
