### ISSUE TITLE
mfem Thread-safe

### ISSUE THREAD

**Issue by vryy** [mfem/mfem#3762]
Hello

I'm using mfem to connect with my FE code. Mfem will provide the FE discretization and shape function values, gradients, etc. Each element in the code contain a "raw" pointer to `mfem::FiniteElement*`. When the shape function is needed, `mfem::FiniteElement::CalcShape` is invoked.

The code runs correctly with single thread. When multithread is used, `mfem::FiniteElement*`starts to give inconsistent results and the analysis does not converge anymore. So, my question is that if `mfem` is thread-safe? and how to ensure consistent result for multithreaded application?

**Comment by vryy** [comment]
This somehow doesn't work. The test code below works for 1 thread (every element has correct size = 8). Meanwhile for more than 1 thread, the sizes are totally different.

Mfem is built with:

     -DMFEM_THREAD_SAFE=YES \
     -DMFEM_USE_OPENMP=YES \

Test code:

    #include "mfem.hpp"
    #include <fstream>
    #include <iostream>
    #include <cmath>
    #include <omp.h>

    using namespace std;
    using namespace mfem;

    int main(int argc, char *argv[])
    {
       // 1. Parse command line options.
       const char *mesh_file = "../data/beam-hex.mesh";
       int order = 1;

       OptionsParser args(argc, argv);
       args.AddOption(&mesh_file, "-m", "--mesh", "Mesh file to use.");
       args.AddOption(&order, "-o", "--order", "Finite element polynomial degree");
       args.ParseCheck();

       // 2. Read the mesh from the given mesh file, and refine once uniformly.
       Mesh mesh(mesh_file);
       // mesh.UniformRefinement();

       // 3. Define a finite element space on the mesh. Here we use H1 continuous
       //    high-order Lagrange finite elements of the given order.
       H1_FECollection fec(order, mesh.Dimension());
       FiniteElementSpace fes(&mesh, &fec);
       cout << "Number of unknowns: " << fes.GetTrueVSize() << endl;

       // 4. Iterate through elements and compute the size using Gauss quadrature
       const double a = 1.0/sqrt(3.0);
       std::vector<std::vector<double>> quad = {
             {-a, -a, -a, 1.0},
             {a, -a, -a, 1.0},
             {a, a, -a, 1.0},
             {-a, a, -a, 1.0},
             {-a, -a, a, 1.0},
             {a, -a, a, 1.0},
             {a, a, a, 1.0},
             {-a, a, a, 1.0},
          };

       int ne = fes.GetNE();
       cout << "Number of elements: " << ne << std::endl;
       cout << "Number of threads: " << omp_get_max_threads() << std::endl;
       #pragma omp parallel for
       for (int i = 0; i < ne; ++i)
       {
          // get the finite element
          const mfem::FiniteElement* fe = fes.GetFE(i);
          mfem::ElementTransformation* etrans = fes.GetElementTransformation(i);

          mfem::IntegrationPoint ip;
          etrans->SetIntPoint(&ip);

          double domain_size = 0.0;
          for (std::size_t j = 0; j < quad.size(); ++j)
          {
             ip.Set(quad[j][0], quad[j][1], quad[j][2], quad[j][3]);

             etrans->Reset();
             const mfem::DenseMatrix& jac = etrans->Jacobian();
             domain_size += quad[j][3]*jac.Det();
          }

          std::stringstream ss;
          ss << "Element " << i << " size: " << domain_size;
          cout << ss.str() << endl;
       }

       return 0;
    }

**Comment by v-dobrev** [comment]
Note that with `MFEM_THREAD_SAFE` enabled, there are still parts that are not fully thread-safe.

The version of `GetElementTransformation` that you are using is not thread safe:
```c++
      mfem::ElementTransformation* etrans = fes.GetElementTransformation(i);
```
Instead, you should create thread-local variable of type `IsoparametricTransformation` and call this version of the method:
https://github.com/mfem/mfem/blob/75d9ac43643feb9039133c25fe83cefcde6ced77/mesh/mesh.hpp#L1285-L1287
