### ISSUE TITLE
Documentation about glvis "Change the vector-to-scalar function" option ("F")

### ISSUE THREAD

**Issue by Tr4l77** [mfem/mfem#3763]
Dear mfem team,

Could you please indicate me what are the functions used by the option from GLvis:  "Change the vector-to-scalar function" ("F") ? It allows to reconstruct the different scalar components of a vector field.
And also where to find these functions ?

Thank you for your consideration.

**Comment by tzanio** [comment]
Hi @Tr4l77,

These conversions in 2D are done in the following functions: 

- https://github.com/GLVis/glvis/blob/master/lib/vsvector.cpp#L269
- https://github.com/GLVis/glvis/blob/master/lib/vsvector.cpp#L348

Here is the essence of the computations.

```c++
VisualizationSceneVector::VisualizationSceneVector(GridFunction &vgf)
{
   mesh = fes->GetMesh();

   solx = new Vector(mesh -> GetNV());
   soly = new Vector(mesh -> GetNV());
   vgf.GetNodalValues(*solx, 1);
   vgf.GetNodalValues(*soly, 2);

   sol = new Vector(mesh -> GetNV());
}

double VecLength(double x, double y)
{
   return sqrt(x*x+y*y);
}

void VisualizationSceneVector::CycleVec2Scalar(int print)
{
   for (i = 0; i < mesh->GetNV(); i++)
   {
      (*sol)(i) = VecLength((*solx)(i), (*soly)(i));
   }
}
```

Hope this helps,
Tzanio

**Comment by v-dobrev** [comment]
See also https://github.com/GLVis/glvis/blob/master/README.md, sections "2D vector data" and "3D vector data".
