### ISSUE TITLE
Interpolating H1 and L2 grid functions in Target Mesh Optimization Implementation.

### ISSUE THREAD

**Issue by sungho91** [mfem/mfem#3765]
Hi all,

I'm currently working on implementing the target mesh optimization paradigm based on pmesh-optimizer.cpp. 

I have a quick question. 

I'm curious whether I need to interpolate my H1 and L2 grid functions to a new mesh generated by TMOP. 
If interpolation is required, which function can transfer those solutions to the new mesh?

Should I simply update the finite space and grid function using Update(), similar to the examples of adaptive mesh refinement (AMR) or something else like Remhos mini app?

Thank you very much.

Sungho

**Comment by vladotomov** [comment]
Yes, if you have `GridFunctions` on the old mesh, they must be moved to the new mesh. Calling `Update()` won't do it. Using some method from _`Remhos`_ is one option, for L2 fields (mass conservative, with some diffusion). Another option is interpolation in physical space, see `/miniapps/gslib/field-interp.cpp`, this would work for both L2 and H1, but requires building with `gslib` (not conservative, but sharp).

**Comment by sungho91** [comment]
Hi @vladotomov,

Thank you for your clarification.
So, what is the meaning of calling Update()? Does it involve refactoring the vector due to changes in size in the grid function after refining or derefining the mesh?

You mentioned that the interpolation algorithm in Remhos works for L2. Could you please explain to me why it is limited to L2 only?

Sungho

**Comment by vladotomov** [comment]
> So, what is the meaning of calling Update()? Does it involve refactoring the vector due to changes in size in the grid function after refining or derefining the mesh?

Yes, it's used with h-adaptivity.  But r-adaptivity is different as the elements have different function values.

> You mentioned that the interpolation algorithm in Remhos works for L2. Could you please explain to me why it is limited to L2 only?

The mathematical algorithm is advection-based, which goes well with L2, while advection with H1 requires stabilization terms. The code is written for L2 spaces (adds face terms) and the L2 structure (eg no overlap between elements) is assumed at many places, for example in the MPI communication.  One option is to go H1 -> L2, use a Remhos method, go L2 -> H1, but somehow take care of the oscillations at the second transfer.

**Comment by sungho91** [comment]
@vladotomov 

I have H1 space (position, velocity, and displacement) and L2 space (density, stress, and some internal variables). 

From my understanding, the position can be represented using TMOP, while the remaining H1 and L2 grid functions can be transferred using interpolation functions.

Therefore, would kind of the best approach be to employ hybrid algorithms, utilizing field-interpolation.cpp for H1 space and Remhos for L2  space?

Many thanks,

Sungho

**Comment by vladotomov** [comment]
It depends what properties should be preserved during the transfer. Coupling between the different fields also must be accounted. Our approach for the full Euler system is [here](https://epubs.siam.org/doi/10.1137/17M1116453), where our goal was to conserve momentum / masses / internal energies. In that case momentum was remapped through advection without any stabilization and without monotonicity treatment, assuming a smooth field. We don't have a publicly available code for H1 advection-remap, but it can be done by looking at _`Remhos`_ and example 9 (it has H1 advection).

**Comment by sungho91** [comment]
I see. 

One last question, speaking of field-interp.cpp, I built mfem with gslib and complied /miniapps/gslib/field-interp.cpp. 
I ran field-interp using those arguments -m1 triple-pt-1.mesh -s1 triple-pt-1.gf -m2 triple-pt-2.mesh written in the code.
In terms of field value, they are hugely different. Almost order of magnitude is different between original and interpolated fields. Does anything come to your mind?

Sungho

**Before interpolation**
![Screenshot from 2023-06-30 16-33-25](https://github.com/mfem/mfem/assets/40257026/ccb3804c-020c-4853-ac64-3f9d9b66b3a4)

**After interpolation**
![Screenshot from 2023-06-30 16-38-07](https://github.com/mfem/mfem/assets/40257026/7a47fb8d-64e4-4f57-aacc-84cfbe781df0)

**Comment by vladotomov** [comment]
Something seems off in your setup. When I run
`./field-interp -m1 triple-pt-1.mesh -s1 triple-pt-1.gf -m2 triple-pt-2.mesh -ft 1`
I see this:
<img width="1193" alt="Screen Shot 2023-06-30 at 4 25 48 PM" src="https://github.com/mfem/mfem/assets/17843342/1b5c6a0e-aa9e-4cc7-acc5-7b9dca73d201">

**Comment by sungho91** [comment]
Hi @vladotomov,

It seems like we used different MFEM. I'm using the latest one "553dc3109..f3a583673".
Also, I found whatever the input is, the source seems to be overwritten by VectorFunctionCoefficient F. 
That's why I got order of magnitude is different between original and interpolated fields.
However, I plotted them with server of glvis. Interpolating works out. I don't know why the overwriting function is includeed in this miniapp. 

Anyway, I'd like to do double check . Can you ask which MFEM did you used for that?

Sungho

src_fes = new FiniteElementSpace(&mesh_1, src_fec, src_ncomp, src_gf_ordering);
func_source = new GridFunction(src_fes);
// Project the grid function using VectorFunctionCoefficient.
VectorFunctionCoefficient F(src_vdim, vector_func);
func_source->ProjectCoefficient(F);

void vector_func(const Vector &p, Vector &F)
{
   F(0) = scalar_func(p);
   for (int i = 1; i < F.Size(); i++) { F(i) = (i+1)*pow(-1, i)*F(0); }
}

![Screenshot from 2023-07-03 12-05-12](https://github.com/mfem/mfem/assets/40257026/27be29c1-5a34-48ab-ad34-a25e0081d025)

**Comment by vladotomov** [comment]
Hi @sungho91,

I just ran it again using the latest `master` branch.
The `vector_func` is used only when the command line doesn't specify an input function, that is, the `-s1` parameter. In my test, I have `-s1 triple-pt-1.gf`.

Try this and let us know if it still doesn't work.

**Comment by sungho91** [comment]
Hi @vladotomov,

Thank you for clarifying.

Now, I am trying to use this algorithm in my code.

In field-interp.cpp, there are lines to conduct interpolation:

```
// Evaluate the source grid function.
Vector interp_vals(nodes_cnt * tar_ncomp);
FindPointsGSLIB finder;
finder.Setup(mesh_1);
finder.Interpolate(vxyz, *func_source, interp_vals, point_ordering);
```

To do that, I need the source and target mesh, respectively.

However, I realized that my original mesh (source mesh) becomes the target mesh after remeshing. So, I have to store the mesh before remeshing, and then I dynamically assign pmesh_old like the following statements. After everything is done, I delete pmesh_old.

```
ParMesh *pmesh_old = nullptr;
pmesh_old = H1FESpace.GetParMesh();
```

However, when I ran the code, I got a segmentation fault. 
To find where the problem was from, I tried to do finder.Setup(pmesh) instead of finder.Setup(pmesh_old), and there was no segmentation fault. So, my problem seems to arise from storing the unmodified mesh.

Do you have any idea about this?

Best regards,

Sungho

**Comment by vladotomov** [comment]
Hi @sungho91,

If you take the mesh pointer and then delete it, then yes, the mesh is gone, and it segfaults. Instead try to make a hard copy of the original mesh, it should work.

Another way to do it, if you're changing the mesh only by node displacements, is to do the gslib interpolation _before_ you move the mesh nodes (that's how I do gslib-based remap).

**Comment by sungho91** [comment]
@vladotomov Thank you 👍
