### ISSUE TITLE
Tetrahedral VS Hexahedral elements in rectangular waveguide

### ISSUE THREAD

**Issue by sp3c333** [mfem/mfem#3773]
Hello MFEM team,

I am reaching to you because I am obtaining strange results when I use tetrahedral mesh with Nedelec to compute the electric field in a rectangular waveguide. However when I use hexahedral mesh, the numerical solution is close to the analytical solution.

**Here is the problem that I am considering (ex25p was adapted):** 
A 3D rectangular waveguide (using inline-hex.mesh or inline-tet.mesh), in which a transverse mode (n=1 & m=1) is considered as the source (on 1 face) by using : " x.ProjectBdrCoefficientTangent(ER_sourceBC, EI_sourceBC, ess_bdr);" every components are equal to zero except EI[1] and EI[2] on the "source face":
EI[1] = -ampli * Beta / h2 * (n * M_PI / b) * sin(m * M_PI / a * x(2)) * cos(n * M_PI / b * x(1));
EI[2] = -ampli * Beta / h2 * (m * M_PI / a) * cos(m * M_PI / a * x(2)) * sin(n * M_PI / b * x(1));                   
A PML at the opposite side of the source, and metallic boundary conditions on every faces except the face used as a source . 

It allows me to get correct results with inline-hex.mesh but unfortunately, when simply switching to inline-tet.mesh, I have strange results appearing : 
Instead of having Ex=c*sin(m*pi/a*z)*sin(n*pi/b*y)*exp(1i*Beta*(xant-x)); with m=n=1
When I use inline-tet.mesh ,I obtain something similar BUT there are wrong values of opposite sign appearing close to the edge before going directly to zero at the edge  .

I am also using : 
    point_mat.SetCol(0, point);
    pmesh->FindPoints(point_mat, elem_ids, ips);              
    ur.GetVectorValue(elem_ids[0], ips[0], vect); 
To do a 1D comparison with analytical results that shows the same results as those seen with GLvis.

If it is not clear, please let me know.

Could you please help me understand what could lead to these different results between tetrahedral and hexahedral elements ?
In an other code I also experienced problem with tetrahedral elements #3670 .

I am still hoping to use mfem to solve much more complex/large problems which will probably require tetrahedral elements.

Thank you for your consideration.

**Comment by mlstowell** [comment]
Hello, @sp3c333,

Sorry for the delayed reply. I suspect this is a symptom of the non-intuitive behavior of Nedelec basis functions as I described in issue #3670.

When looking at fields represented using Nedelec basis functions you should consider the path integrals of those fields. Specifically when you look at an edge in the mesh you should only consider the path integral of the field along that edge. That path integral should be accurate. The components of the field which are not parallel to that edge may be very different to what you might expect but those components don't contribute to this path integral.

If you can attach images of your results I'd be happy to comment more specifically.

Best wishes,
Mark
