### ISSUE TITLE
SetBdrAttribute usage

### ISSUE THREAD

**Issue by AntonIatcenko** [mfem/mfem#3775]
Hello Everyone, 

I am trying to assign boundary attributes "by hand" to each boundary element, but I think I'm misunderstanding how SetBdrAttribute works. As a simple example, when I add 
`cout << pmesh->bdr_attributes.Max() << endl;
pmesh->SetBdrAttribute(1,4);
cout << pmesh->bdr_attributes.Max() << endl;`
to my code, the output is 1 1, i.e. bdr_attributes.Max() does not change. Where did the 4 from SetBdrAttribute(1,4) go?

**Comment by vladotomov** [comment]
Hi @AntonIatcenko, I believe you must call `Mesh::SetAttributes()` to update the internal structures after the manual call to `SetBdrAttribute()`.

**Comment by AntonIatcenko** [comment]
Yes, looks like this works, thank you!

**Comment by AntonIatcenko** [comment]
Yes, looks like this works, thank you!
