### ISSUE TITLE
Matrix-free or partial assembly in elasticity operator

### ISSUE THREAD

**Issue by joconnor819** [mfem/mfem#3779]
Howdy! 

I'm looking at MFEM for solving elasticity problems, and I've been getting errors saying that the elasticity integrator does not work with partial or no assembly. 
I was wondering if there is a simple way to set this up on my end, or what would go into going around this integrator. (Could I use a combination of something like divergence and diffusion integrators to do the same thing? I don't know if these things can be combined.)

Thank you,
Justin

**Comment by jtristano** [comment]
I am also interested in this.  Would love to hear from the community.

Thanks
Joe

**Comment by jandrej** [comment]
You can also look into the [Hooke](https://github.com/mfem/mfem/tree/master/miniapps/hooke) mini app. It's a matrix-free version of solid mechanics with automatic differentiation and user defined materials using PA-like kernels.
