### ISSUE TITLE
How to carry over submesh boundary attributes from parent

### ISSUE THREAD

**Issue by AlejandroMunozManterola** [mfem/mfem#3781]
Good day,

I'm trying to play a bit with the submeshing capabilities in order to implement forced conditions on whatever problem we wish to define in L2 (Discontinuous Galerkin) while also trying to work with the 'Internal Boundary' PRs #3777, #3422.

I have designed the following mesh, with four attributes in total (two domain, two boundary), but consider that this mesh would be part of a bigger mesh for functional purposes:

The first two for the domain have been defined such as:

![imagen](https://github.com/mfem/mfem/assets/84183271/26e66ca6-c14d-4df7-9972-91aa0e886ac3)
![imagen](https://github.com/mfem/mfem/assets/84183271/d848540e-5e0d-4782-a63e-041963659e40)

While the boundaries have been defined such as:

![imagen](https://github.com/mfem/mfem/assets/84183271/54b6cab1-dc5d-4856-afce-c6a1cb029f79)
![imagen](https://github.com/mfem/mfem/assets/84183271/8f836fb6-2ffa-4db6-bfb4-c83e81c47179)

In the parent mesh, I can see that the Parent mesh has two domain attributes (201 and 202) and two boundary attributes (2 and 301), being the ones I've defined. (Calling parent.attribute and parent.bdr_attribute lets use see this)

When creating the submesh through the CreateFromDomain and passing an Array<int> with 201 and 202, the submesh does give both domain attributes back, but when asked about its boundary attributes, all boundaries are set to bdr_attribute 1. Is there a way for the boundary attributes to carry over to the submesh on top of the domain attributes in a relatively trivial way?

Code example:

```c
auto m{ Mesh::LoadFromFile((gmshMeshesFolder() + \"TotalFieldScatteredFieldQuads.msh\").c_str(), 1, 0)};
Array<int> domain_atts(2); domain_atts[0] = 201; domain_atts[1] = 202;
auto sm{ SubMesh::CreateFromDomain(m,domain_atts) };
auto atts = sm.attributes;
auto bdr_atts = sm.bdr_attributes;
```

Thank you very much for your help.

**Comment by jandrej** [comment]
Can you try https://github.com/mfem/mfem/pull/3461?

**Comment by AlejandroMunozManterola** [comment]
> Can you try #3461?

Hello @jandrej, will do so in some weeks. Thanks for pointing that PR it out!
