### ISSUE TITLE
Errors building with SLEPc

### ISSUE THREAD

**Issue by v-dobrev** [mfem/mfem#3793]
It looks like the following line overwrites some of our makefile variables: https://github.com/mfem/mfem/blob/f97a770dcaa7498c93069ca7f27d25d9655acd86/config/defaults.mk#L393-L394 and that causes problems.

Removing this line will probably cause issues when SLEPc is built with extra dependencies (dependencies other than PETSc) becasue `SLEPC_EXTERNAL_LIB` is defined indirectly using variables like `${ARPACK_LIB}`. To get the right expansion we can parse the file `$(SLEPC_VARS)` without including it locally but parsing it in a separate `make` process and printing the required values. This parsing-and-printing can be done easily with a makefile like this:
```make
ifeq ($(FILE),)
  $(error FILE is not set)
endif

include $(FILE)

print-%:
#	$(info $(value $*))
	$(info $($*))
	@true
```

Another potential issue: since the variable `SLEPC_INCLUDE` is defined using the variable `SLEPC_DIR`, it ends up using relative path with the default settings and we get include flags like `-I./../slepc/include`. This may cause issues when building MFEM out-of-source. We should probably just set `SLEPC_DIR` to be an absolute path:
```make
SLEPC_DIR := $(abspath $(MFEM_DIR)/../slepc)
```

**Comment by jetremblay** [comment]
Thanks, I am having a look. Do you have an example of a specific makefile variables that is overwritten?

> Another potential issue: since the variable SLEPC_INCLUDE is defined using the variable SLEPC_DIR, it ends up using relative path with the default settings and we get include flags like -I./../slepc/include. This may cause issues when building MFEM out-of-source. We should probably just set SLEPC_DIR to be an absolute path:

Good point. It seems like PETSc already uses an absolute path from petscvariables. We can add that for SLEPC_DIR.

**Comment by v-dobrev** [comment]
Some of the variable that get overwritten are `HYPRE_LIB`, `METIS_LIB`, `PETSC_LIB` -- these are overwritten by the inclusion of (A) `${PETSC_DIR}/${PETSC_ARCH}/lib/petsc/conf/petscvariables` from (B) `${SLEPC_DIR}/${PETSC_ARCH}/lib/slepc/conf/slepcvariables`. I noticed that some builds of SLEPc do not include A from B (e.g. on macOS) however on a Linux cluster where I was testing, it does.

**Comment by jetremblay** [comment]
I was thinking that the following would work on Linux
```
# Read the variable names in slepc_variables
SLEPC_DEP_TEMP := $(shell sed -n "s/$(SLEPC_LIB_VAR) *= *//p" $(SLEPC_VARS)|sed -n "s/\$${\([^}]*\)}/\1/gp")
# Parse the variables in slepcvariables
SLEPC_DEP := $(foreach dep,$(SLEPC_DEP_TEMP),$(shell sed -n "s/$(dep) *= *//p" $(SLEPC_DIR)/$(PETSC_ARCH)/lib/slepc/conf/slepcvariables))
```

but if the macOS builds work differently, it might not be very portable. Unfortunately I don't have access to macOS so I cannot test that.

**Comment by chapman39** [comment]
I believe this issue is affecting me. I am installing `mfem+petsc+slepc` through spack.
