### ISSUE TITLE
Filling the face information for ParMesh::GetSerialMesh()

### ISSUE THREAD

**Issue by hughcars** [mfem/mfem#3794]
I am attempting to use the `GetSerialMesh` method from ParMesh to serialize a mesh in order to repartition using METIS. This works just fine for p=1 nedelec elements, but for p>=2, there's failures and I notice that the resulting mesh has no generated faces, i.e. `pmesh.GetSerialMesh(0).GetNFaces() == 0` which makes the resulting mesh unusable in a solve. 

Based on the fact it can be dumped to file suggests there is sufficient information to generate the face data, but what would the sequence be to regenerate it from the generated serial mesh? I tried
```
   if (MyRank == save_rank)
   {
      if (Dim > 1)
      {
         serialmesh.el_to_edge = new Table;
         serialmesh.NumOfEdges = serialmesh.GetElementToEdgeTable(*el_to_edge, serialmesh.be_to_edge);
      }
      if (Dim > 2)
      {
         serialmesh.GetElementToFaceTable();
      }
      serialmesh.GenerateFaces();
      serialmesh.Finalize(true);
   }
```
at the end of the `GetSerialMesh` method, but whilst that does populate the faces, there are still many faces left with orientations of `-1`, which causes ND elements to fail.

**Comment by hughcars** [comment]
Thank you for the reply @v-dobrev , `FinalizeTopology(); Finalize()` or `FinalizeMesh()` do fill the faces, in that the number of faces is now non-zero. However the resulting information for each face is still invalid, giving errors such as:
```
Assertion failed: ((0) <= (k) && (k) < (SizeK())) is false:
 --> invalid index k = -1, valid range is [0,6)
 ... in function: const DenseMatrix &mfem::DenseTensor::operator()(int) const
 ... in file: /Users/hughcars/AWS/palace/build/extern/mfem/fem/../linalg/densemat.hpp:1061

Backtrace:
0) [0xa512800104bc5a97]: mfem::mfem_error(char const*)
1) [0xe22e00010589f363]: mfem::DenseTensor::operator()(int) const
2) [0x9d2680010612b777]: mfem::ND_StatelessDofTransformation::GetFaceTransform(int)
3) [0xc840000106129af7]: mfem::ParFiniteElementSpace::Build_Dof_TrueDof_Matrix() const
4) [0x6923800104415dff]: mfem::ParFiniteElementSpace::Dof_TrueDof_Matrix() const
5) [0x3b7b000106166547]: mfem::ParFiniteElementSpace::GetRestrictionMatrix() const
6) [0x2d1900010612eecb]: mfem::ParFiniteElementSpace::GetEssentialTrueDofs(mfem::Array<int> const&, mfem::Array<int>&, int)
```
which leads me to conclude that `FinalizeTopology()` is not recomputing `faces_info` based on the available geometric information. 

It looks like `AddTriangleFaceElement` is getting called within `GenerateFaces()`, but the resulting faces are not being visited twice, so still have `inf2 = -1`. This is all being triggered by a throw [here](https://github.com/mfem/mfem/blob/master/fem/pfespace.cpp#L944) caused by [this line](https://github.com/mfem/mfem/blob/master/fem/pfespace.cpp#L849)

**Comment by v-dobrev** [comment]
I'm not sure what you are doing exactly -- you are showing errors from a parallel FE space methods while before you were talking about a serial mesh. If you look at `Mesh::GenerateFaces()` (which is called by `FinalizeTopology`) you can see that the array `faces_info` is being re-generated based the element connectivity.

One thing to keep in mind is that if you partitioning a `Mesh` into a `ParMesh` using the standard constructor, the serial `Mesh` has to be on all MPI ranks. `GetSerialMesh` creates the serial mesh just in one rank.
