### ISSUE TITLE
Hyperscale grid files are difficult to run (mpirun)

### ISSUE THREAD

**Issue by ojipadeson** [mfem/mfem#3799]
My device has about 128GB of RAM. Can MFEM support models with nearly **one million element** numbers, more than **100,000 boundaries**, and more than **100,000 vertices**?
Can someone briefly say a reasonable estimate of the memory required? Thanks for any replies.

**Comment by pazner** [comment]
Yes, definitely. I can run a simple Poisson problem on a mesh with 1e6 elements on my laptop. I used 8 MPI ranks, and each process used about 150 MB of RAM, so 1.2 GB total. The time to solution was < 4 seconds.

**Comment by ojipadeson** [comment]
I use 4 mpi ranks, and the program quits after the memory is full. It took up about 64GB at the time, and it kept rising. My element is tetrahedron and boundary is triangles. Does the difference in element significantly affect memory usage?

**Comment by pazner** [comment]
What problem/equations are you solving? What order (polynomial degree) finite elements are you using?

**Comment by ojipadeson** [comment]
```/miniapps/electromagnetic/maxwell.cpp```. Only the mesh file was replaced. First order equation.
Run the command as: 
```
mpirun -np 4 ./maxwell -m ../../data/mymesh.mesh -rs 2 -abcs '-1' -dp '-0.3 0.0 0.0 0.3 0.0 0.0 0.1 1 .5 .5'
```

**Comment by pazner** [comment]
The flag `-rs 2` will perform two additional levels of uniform refinement, so if `mymesh.mesh` has 1e6 elements, the mesh used for your computations will have 64x as many elements (perhaps also explaining your 64 GB of memory usage).

**Comment by ojipadeson** [comment]
You are absolutely right. Thank you very much
