### ISSUE TITLE
problem in parallel code of brance maxwell-dev

### ISSUE THREAD

**Issue by Asadanees** [mfem/mfem#380]
Dear @mlstowell and @tzanio.
I have a problem to   compile a parallel code of branch mawell-dev.
I want to compile maxwell solver.
the error is 
./../libmfem.a(mesh.o): In function `mfem::Mesh::GeneratePartitioning(int, int)':
mesh.cpp:(.text+0x293b9): undefined reference to `METIS_PartGraphVKway'
collect2: error: ld returned 1 exit status
makefile:48: recipe for target 'maxwell' failed
make: *** [maxwell] Error 1
thanks 
anees

**Comment by mlstowell** [comment]
Hi, Asad,

This error should not be unique to this branch or this executable.  You should double-check that your configuration files specify the location of your METIS library correctly.  You can also look at the command line that's displayed during compilation to see how METIS is actually be referenced.  You should see something like:
mpicxx  -g -Wall  -std=c++11 -I../.. -I../../../hypre-master/src/hypre/include   -g volta.cpp -o volta volta_solver.o ../common/pfem_extras.o -L../.. -lmfem -L../../../hypre-master/src/hypre/lib -lHYPRE -L../../../metis-4.0.3 -lmetis

Look particularly at the directory just before "-lmetis" and make sure it is correct.

Best wishes,
Mark

**Comment by Asadanees** [comment]
Dear @mlstowell 
Thanks I have fixed it.

Sincerely yours 
Anees
