### ISSUE TITLE
Integrators naming

### ISSUE THREAD

**Issue by denislachapelle** [mfem/mfem#3801]
I would like to understand the naming of the integrators below:

VectorFEDomainLFIntegrator, What is the meaning of FE?

VectorDomainLFIntegrator, What is the meaning of LF?

Thank you,
Denis Lachapelle

**Comment by pazner** [comment]
`VectorFE` means "vector finite element", referring to Nédélec or Raviart-Thomas finite elements.

`LF` stands for linear form.

`VectorDomainLFIntegrator` (and similarly for other "Vector" as opposed to "VectorFE" integrators) operates on vector spaces that are made up of copies of scalar finite elements.

**Comment by denislachapelle** [comment]
Thank you very much it help a lot, there is so much to understand !!!

**Comment by pazner** [comment]
You're welcome. Closing this for now, feel free to re-open if you have other questions.
