### ISSUE TITLE
Discrepancy in error calculation for identical meshes and solutions

### ISSUE THREAD

**Issue by NiklasFreymuth** [mfem/mfem#3802]
Hello,

I'm encountering an issue with the error calculation in pyMFEM when comparing the solutions of two identical meshes. Despite the meshes and solutions being identical, the calculated error is different. I already posted this [issue](https://github.com/mfem/PyMFEM/issues/189) in the pyMFEM repository, but believe that the problem lies on the C++ part and/or my understanding of the codebase.

To summarize:
I create two identical meshes and solve them to get two solutions. I then create GridFunctionCoefficient objects from the solutions and calculate the error using ComputeElementMaxErrors. The error between a solution and itself is 0, as expected. However, the error between the two identical solutions is non-zero.
I've confirmed that the coefficient functions, integration points, and element transformations are identical for the two meshes.
Here's the Python code I'm using:

```python
def main():
    # create 2 meshes
    mesh = get_mesh()
    mesh2 = get_mesh()
    for k in range(6):
        mesh.UniformRefinement()
        mesh2.UniformRefinement()
    
    # solve meshes
    x = solve(mesh)
    x2 = solve(mesh2)
    
    x_coef = mfem.GridFunctionCoefficient(x)
    error = mfem.Vector(mesh.GetNE())
    x.ComputeElementMaxErrors(x_coef, error)
    print("L2 error norm of x->x: ", error.Norml2())
    
    x2_coef = mfem.GridFunctionCoefficient(x2)
    error2 = mfem.Vector(mesh.GetNE())
    x.ComputeElementMaxErrors(x2_coef, error2)
    print("L2 error norm of x->x2: ", error2.Norml2())

def get_mesh():
    from os.path import expanduser, join, dirname
    path = dirname((__file__))
    meshfile = expanduser(join(path, '..', 'data', '../data/star.mesh'))
    mesh = mfem.Mesh(meshfile, 1, 1)
    return mesh
    
def solve(mesh):
    # 1. Set up a function space
    order = 1
    fec = mfem.H1_FECollection(order, mesh.Dimension())
    fespace = mfem.FiniteElementSpace(mesh, fec)

    # 2. Define the solution vector x as a finite element grid function, set to zero
    x = mfem.GridFunction(fespace)
    x.Assign(0.0)

    # 3. Set up the linear form b(.)
    class Source(mfem.PyCoefficient):
        def EvalValue(self, x):
            import math
            # have a gaussian centered at [0.25, 0.75]
            return math.exp(-((x[0] - 0.25) ** 2 + (x[1] - 0.75) ** 2) / 0.01)

    f = Source()
    b = mfem.LinearForm(fespace)
    b.AddDomainIntegrator(mfem.DomainLFIntegrator(f))
    b.Assemble()

    # 4. Define the bilinear form a(.,.)
    one = mfem.ConstantCoefficient(1.0)
    a = mfem.BilinearForm(fespace)
    a.AddDomainIntegrator(mfem.DiffusionIntegrator(one))

    # 5. Create MFEM operators to store the linear system
    A = mfem.OperatorPtr()
    B = mfem.Vector()
    X = mfem.Vector()

    # 6. Define zero boundary conditions
    ess_tdof_list = mfem.intArray()
    ess_bdr = mfem.intArray([1] * mesh.bdr_attributes.Max())  # create arrray of 1s
    fespace.GetEssentialTrueDofs(ess_bdr, ess_tdof_list)

    # 7. Solve the problem
    a.Assemble()
    a.FormLinearSystem(ess_tdof_list, x, b, A, X, B)
    mfem.CG(A, B, X, 0, max_num_iter=800, RTOLERANCE=1e-12, ATOLERANCE=1e-24)

    # 8. Recover the solution as a finite element grid function
    a.RecoverFEMSolution(X, b, x)
    x.fespace = fespace  # keep the fespace around because of function scopes and garbage collection
    return x

def plot_errors(mesh, errors):
    fec = mfem.DG_FECollection(p=0, dim=2)
    fespace_discontinuous = mfem.FiniteElementSpace(mesh, fec)
    error_gf = mfem.GridFunction(fespace_discontinuous)

    # Assuming `errors` is a list or array-like object containing one error value per element
    for i, error in enumerate(errors):
        error_gf[i] = error

    # Send to GLVis
    sol_sock = mfem.socketstream("localhost", 19916)
    sol_sock.precision(8)
    sol_sock.send_solution(mesh, error_gf)
```

The output is:

```bash
L2 error norm of x->x:  0.0
L2 error norm of x->x2:  0.22772834894859287
```
When visualizing the remaining error between `mesh` and `mesh2`, it looks somehow "fragmented".
From left/top to right/bottom: The solution on the mesh, the error when comparing `x` of `mesh` to itself, and the error when comparing `x` to `x2` of `mesh2`.
<img src="https://github.com/mfem/PyMFEM/assets/50029176/dc3f016f-d142-4f00-be4a-8cab1666720f" width="300" style="display: inline-block;">
<img src="https://github.com/mfem/PyMFEM/assets/50029176/487a29ce-c33d-479f-aa89-ea2fd1bd29b1" width="300" style="display: inline-block;">
<img src="https://github.com/mfem/PyMFEM/assets/50029176/82e0c5b5-d01e-4111-afd6-d2f5048c4772" width="300" style="display: inline-block;">

I'm not sure why the error calculation would be different for the two identical meshes and solutions. Any insight into this issue would be greatly appreciated.

Thank you!

**Comment by vladotomov** [comment]
Hi @NiklasFreymuth,

This line
`x.ComputeElementMaxErrors(x2_coef, error2)`
will go over the elements of `mesh` and evaluate `x` and `x2_coef`. But `x2_coef` is defined w.r.t. `mesh2`. So I believe you end up in the `else` below, which is intended for other purposes, and things get mixed up:

```
double GridFunctionCoefficient::Eval (ElementTransformation &T,
                                      const IntegrationPoint &ip)
{
   Mesh *gf_mesh = GridF->FESpace()->GetMesh();
   if (T.mesh == gf_mesh)
   {
      return GridF->GetValue(T, ip, Component);
   }
   else
   {
      IntegrationPoint coarse_ip;
      ElementTransformation *coarse_T = RefinedToCoarse(*gf_mesh, T, ip, coarse_ip);
      return GridF->GetValue(*coarse_T, coarse_ip, Component);
   }
}
```

**Comment by NiklasFreymuth** [comment]
Hi [@vladotomov](https://github.com/vladotomov),

thank you for the quick reply! I see how having different instances of the same mesh would be treated differently here. 

In my application, I want to compare two elements on the same domain by calculating the integrated differences of the solution vectors per element of the first mesh. I.e., for every element in `mesh1`, I'd like to compute how different the (interpolated) solution on this element is when compared to the same space in `mesh2`. Since the functions `ComputeElement{Max,L1,L2}Errors` seem to be designed with identical meshes in mind, is there another way to achieve this?

I tried to map/interpolate the solution vector from one mesh to the vertices of another via `InterpolationGridTransfer` and its `ForwardOperator.Mult()` function, implementing it as follows:

```python
def interpolate(x1, x2):
    fespace1: mfem.FiniteElementSpace = x1.FESpace()
    fespace2: mfem.FiniteElementSpace = x2.FESpace()
    
    # Creating a forward operator to map from fespace1 to fespace2
    transfer = mfem.InterpolationGridTransfer(fespace1, fespace2)
    F = transfer.ForwardOperator()
    
    # Using the forward operator to transfer `x` from `fespace1` to `fespace2`
    x_interp = mfem.Vector(fespace2.GetNDofs())  
    x_interp.Assign(0.0)
    F.Mult(x1, x_interp)

    diff = mfem.Vector(x2.Size())
    diff.Assign(x2)
    diff -= x_interp  
    print(f"\nL2 error norm of x2-x_interp: {diff.Norml2()}")
    return diff
```

However, this yields non-zero results for `diff` even when inputting the same solution vector twice (i.e., invoking `interpolate(x,x)`). Do you have any ideas how I could instead implement such an element-wise comparison?

Thank you in advance for your time and assistance!

**Comment by vladotomov** [comment]
If one mesh is refined version of the other, see #3209

If the meshes are independent, see `/miniapps/gslib/field-diff.cpp`

**Comment by NiklasFreymuth** [comment]
Thank you very much for the reply.

[`/miniapps/gslib/field-diff.cpp`](https://github.com/mfem/mfem/blob/master/miniapps/gslib/field-diff.cpp) seems to be very close to what I am looking for. If I understand the code correctly, it computes a bounding box of the two meshes, discretizes this via a 2d or 3d grid, and numerically integrating the difference between the two meshes by summing over query points that depend on this grid. If this is correct, are "empty" elements of this grid handled efficiently somehow, or does this miniapp get less efficient if the domain contains e.g., a lot of holes?
I also did not find a Python version of this example, the closest being the [`field_interp.py`](https://github.com/mfem/PyMFEM/blob/master/miniapps/gslib/field_interp.py). Did I miss this somewhere? If not, I think the example should be relatively straightforward to transfer to Python. Given that I need it anyways, I would be glad to share it with the community once it is finished.

**Comment by vladotomov** [comment]
You can specify what value will be returned for outside points with `SetDefaultInterpolationValue`, so that differences in holes can be taken into account. I'm not sure if someone did a python version, it would be great to have one.
