### ISSUE TITLE
How to correct perform material data using .vtk format?

### ISSUE THREAD

**Issue by yuber30** [mfem/mfem#3805]
Hello! 
    I am trying to test ex2 using high-order mesh in .vtk format. This file is generated by Gmsh. However, it reports an error that "input mesh should have at least two materials and two boundary attributes!"  
    Looking forward to your reply. Thanks!

# my vtk format
> `#` vtk DataFile Version 2.0
beam-tet, Created by Gmsh 4.9.5 
ASCII
DATASET UNSTRUCTURED_GRID
POINTS 400 double
0 0 0
1 0 0
2 0 0
3 0 0
4 0 0
5 0 0
6 0 0
7 0 0
8 0 0
0 1 0
1 1 0
2 1 0
3 1 0
4 1 0
5 1 0
6 1 0
7 1 0
8 1 0
0 0 1
1 0 1
2 0 1
3 0 1
4 0 1
5 0 1
6 0 1
7 0 1
8 0 1
0 1 1
1 1 1
2 1 1
3 1 1
4 1 1
5 1 1
6 1 1
7 1 1
8 1 1
0 0 0.3333333333333333
0 0 0.6666666666666666
0.3333333333333333 0 1
0.6666666666666666 0 1
0.6666666666666667 0 0.6666666666666667
0.3333333333333334 0 0.3333333333333334
0.6666666666666667 0.6666666666666667 0.6666666666666667
0.3333333333333334 0.3333333333333334 0.3333333333333334
1 0.6666666666666667 1
1 0.3333333333333334 1
0.6666666666666667 0.6666666666666667 1
0.3333333333333334 0.3333333333333334 1
0.3333333333333334 0 0.6666666666666667
0.3333333333333334 0.3333333333333334 0.6666666666666666
0.6666666666666667 0.3333333333333334 0.6666666666666667
0.6666666666666666 0.3333333333333334 0.9999999999999998
0.6666666666666667 0 0
0.3333333333333334 0 0
1 0 0.6666666666666667
1 0 0.3333333333333334
1 0.6666666666666667 0.6666666666666667
1 0.3333333333333334 0.3333333333333334
0.6666666666666667 0 0.3333333333333334
0.6666666666666667 0.3333333333333334 0.3333333333333334
0.9999999999999998 0.3333333333333334 0.6666666666666667
1 0.3333333333333333 0
1 0.6666666666666666 0
0.6666666666666667 0.6666666666666667 0
0.3333333333333334 0.3333333333333334 0
1 1 0.6666666666666667
1 1 0.3333333333333334
0.6666666666666667 0.3333333333333334 0
0.6666666666666667 0.6666666666666667 0.3333333333333334
0.9999999999999998 0.6666666666666666 0.3333333333333334
0 0.6666666666666667 0.6666666666666667
0 0.3333333333333334 0.3333333333333334
0.3333333333333333 1 1
0.6666666666666666 1 1
0 0.6666666666666667 1
0 0.3333333333333334 1
0 0.3333333333333334 0.6666666666666666
0.3333333333333334 0.6666666666666667 0.6666666666666667
0.3333333333333334 0.6666666666666667 0.9999999999999998
0 0.6666666666666667 0
0 0.3333333333333334 0
0.6666666666666667 1 0.6666666666666667
0.3333333333333334 1 0.3333333333333334
0 1 0.6666666666666667
0 1 0.3333333333333334
0.3333333333333334 0.6666666666666667 0.3333333333333334
0 0.6666666666666667 0.3333333333333334
0.3333333333333334 0.9999999999999998 0.6666666666666667
0.6666666666666667 1 0
0.3333333333333334 1 0
0.3333333333333334 0.6666666666666667 0
0.6666666666666667 0.9999999999999998 0.3333333333333334
1.333333333333333 0 1
1.666666666666667 0 1
1.666666666666667 0 0.6666666666666667
1.333333333333333 0 0.3333333333333334
1.666666666666667 0.6666666666666667 0.6666666666666667
1.333333333333333 0.3333333333333334 0.3333333333333334
2 0.6666666666666667 1
2 0.3333333333333334 1
1.666666666666667 0.6666666666666667 1
1.333333333333333 0.3333333333333334 1
1.333333333333333 0 0.6666666666666667
1.333333333333333 0.3333333333333334 0.6666666666666667
1.666666666666667 0.3333333333333334 0.6666666666666667
1.666666666666667 0.3333333333333334 0.9999999999999998
1.666666666666667 0 0
1.333333333333333 0 0
2 0 0.6666666666666667
2 0 0.3333333333333334
2 0.6666666666666667 0.6666666666666667
2 0.3333333333333334 0.3333333333333334
1.666666666666667 0 0.3333333333333334
1.666666666666667 0.3333333333333334 0.3333333333333334
2 0.3333333333333334 0.6666666666666667
2 0.3333333333333333 0
2 0.6666666666666666 0
1.666666666666667 0.6666666666666667 0
1.333333333333333 0.3333333333333334 0
2 1 0.6666666666666667
2 1 0.3333333333333334
1.666666666666667 0.3333333333333334 0
1.666666666666667 0.6666666666666667 0.3333333333333334
2 0.6666666666666666 0.3333333333333334
1.333333333333333 1 1
1.666666666666667 1 1
1.333333333333333 0.6666666666666667 0.6666666666666667
1.333333333333333 0.6666666666666667 0.9999999999999998
1.666666666666667 1 0.6666666666666667
1.333333333333333 1 0.3333333333333334
1.333333333333333 0.6666666666666667 0.3333333333333334
1.333333333333333 0.9999999999999998 0.6666666666666667
1.666666666666667 1 0
1.333333333333333 1 0
1.333333333333333 0.6666666666666666 0
1.666666666666667 0.9999999999999998 0.3333333333333334
2.333333333333333 0 1
2.666666666666667 0 1
2.666666666666667 0 0.6666666666666667
2.333333333333333 0 0.3333333333333334
2.666666666666667 0.6666666666666667 0.6666666666666667
2.333333333333333 0.3333333333333334 0.3333333333333334
3 0.6666666666666667 1
3 0.3333333333333334 1
2.666666666666667 0.6666666666666667 1
2.333333333333333 0.3333333333333334 1
2.333333333333333 0 0.6666666666666667
2.333333333333333 0.3333333333333334 0.6666666666666667
2.666666666666667 0.3333333333333334 0.6666666666666667
2.666666666666667 0.3333333333333334 0.9999999999999998
2.666666666666667 0 0
2.333333333333333 0 0
3 0 0.6666666666666667
3 0 0.3333333333333334
3 0.6666666666666667 0.6666666666666667
3 0.3333333333333334 0.3333333333333334
2.666666666666667 0 0.3333333333333334
2.666666666666667 0.3333333333333334 0.3333333333333334
3 0.3333333333333334 0.6666666666666667
3 0.3333333333333333 0
3 0.6666666666666666 0
2.666666666666667 0.6666666666666667 0
2.333333333333333 0.3333333333333334 0
3 1 0.6666666666666667
3 1 0.3333333333333334
2.666666666666667 0.3333333333333334 0
2.666666666666667 0.6666666666666667 0.3333333333333334
3 0.6666666666666666 0.3333333333333334
2.333333333333333 1 1
2.666666666666667 1 1
2.333333333333333 0.6666666666666667 0.6666666666666667
2.333333333333333 0.6666666666666667 0.9999999999999998
2.666666666666667 1 0.6666666666666667
2.333333333333333 1 0.3333333333333334
2.333333333333333 0.6666666666666667 0.3333333333333334
2.333333333333333 0.9999999999999998 0.6666666666666667
2.666666666666667 1 0
2.333333333333333 1 0
2.333333333333333 0.6666666666666666 0
2.666666666666667 0.9999999999999998 0.3333333333333334
3.333333333333333 0 1
3.666666666666667 0 1
3.666666666666667 0 0.6666666666666667
3.333333333333333 0 0.3333333333333334
3.666666666666667 0.6666666666666667 0.6666666666666667
3.333333333333333 0.3333333333333334 0.3333333333333334
4 0.6666666666666667 1
4 0.3333333333333334 1
3.666666666666667 0.6666666666666667 1
3.333333333333333 0.3333333333333334 1
3.333333333333333 0 0.6666666666666667
3.333333333333334 0.3333333333333334 0.6666666666666667
3.666666666666667 0.3333333333333334 0.6666666666666667
3.666666666666667 0.3333333333333334 0.9999999999999998
3.666666666666667 0 0
3.333333333333333 0 0
4 0 0.6666666666666667
4 0 0.3333333333333334
4 0.6666666666666667 0.6666666666666667
4 0.3333333333333334 0.3333333333333334
3.666666666666667 0 0.3333333333333334
3.666666666666667 0.3333333333333334 0.3333333333333334
3.999999999999999 0.3333333333333334 0.6666666666666667
4 0.3333333333333333 0
4 0.6666666666666666 0
3.666666666666667 0.6666666666666667 0
3.333333333333333 0.3333333333333334 0
4 1 0.6666666666666667
4 1 0.3333333333333334
3.666666666666667 0.3333333333333334 0
3.666666666666667 0.6666666666666667 0.3333333333333334
3.999999999999999 0.6666666666666666 0.3333333333333334
3.333333333333333 1 1
3.666666666666667 1 1
3.333333333333333 0.6666666666666667 0.6666666666666667
3.333333333333333 0.6666666666666667 0.9999999999999998
3.666666666666667 1 0.6666666666666667
3.333333333333333 1 0.3333333333333334
3.333333333333334 0.6666666666666667 0.3333333333333334
3.333333333333333 0.9999999999999998 0.6666666666666667
3.666666666666667 1 0
3.333333333333333 1 0
3.333333333333334 0.6666666666666666 0
3.666666666666667 0.9999999999999998 0.3333333333333334
4.333333333333334 0 1
4.666666666666666 0 1
4.666666666666667 0 0.6666666666666667
4.333333333333334 0 0.3333333333333334
4.666666666666667 0.6666666666666667 0.6666666666666667
4.333333333333334 0.3333333333333334 0.3333333333333334
5 0.6666666666666667 1
5 0.3333333333333334 1
4.666666666666667 0.6666666666666667 1
4.333333333333334 0.3333333333333334 1
4.333333333333334 0 0.6666666666666667
4.333333333333334 0.3333333333333334 0.6666666666666667
4.666666666666668 0.3333333333333334 0.6666666666666667
4.666666666666667 0.3333333333333334 0.9999999999999998
4.666666666666667 0 0
4.333333333333334 0 0
5 0 0.6666666666666667
5 0 0.3333333333333334
5 0.6666666666666667 0.6666666666666667
5 0.3333333333333334 0.3333333333333334
4.666666666666667 0 0.3333333333333334
4.666666666666668 0.3333333333333334 0.3333333333333334
4.999999999999999 0.3333333333333334 0.6666666666666667
5 0.3333333333333333 0
5 0.6666666666666666 0
4.666666666666667 0.6666666666666667 0
4.333333333333334 0.3333333333333334 0
5 1 0.6666666666666667
5 1 0.3333333333333334
4.666666666666668 0.3333333333333334 0
4.666666666666668 0.6666666666666667 0.3333333333333334
4.999999999999999 0.6666666666666666 0.3333333333333334
4.333333333333334 1 1
4.666666666666666 1 1
4.333333333333334 0.6666666666666667 0.6666666666666667
4.333333333333334 0.6666666666666667 0.9999999999999998
4.666666666666667 1 0.6666666666666667
4.333333333333334 1 0.3333333333333334
4.333333333333334 0.6666666666666667 0.3333333333333334
4.333333333333334 0.9999999999999998 0.6666666666666667
4.666666666666667 1 0
4.333333333333334 1 0
4.333333333333334 0.6666666666666666 0
4.666666666666667 0.9999999999999998 0.3333333333333334
5.333333333333334 0 1
5.666666666666667 0 1
5.666666666666666 0 0.6666666666666667
5.333333333333333 0 0.3333333333333334
5.666666666666666 0.6666666666666667 0.6666666666666667
5.333333333333333 0.3333333333333334 0.3333333333333334
6 0.6666666666666667 1
6 0.3333333333333334 1
5.666666666666666 0.6666666666666667 1
5.333333333333333 0.3333333333333334 1
5.333333333333333 0 0.6666666666666667
5.333333333333332 0.3333333333333334 0.6666666666666667
5.666666666666666 0.3333333333333334 0.6666666666666667
5.666666666666667 0.3333333333333334 0.9999999999999998
5.666666666666666 0 0
5.333333333333333 0 0
6 0 0.6666666666666667
6 0 0.3333333333333334
6 0.6666666666666667 0.6666666666666667
6 0.3333333333333334 0.3333333333333334
5.666666666666666 0 0.3333333333333334
5.666666666666666 0.3333333333333334 0.3333333333333334
6 0.3333333333333334 0.6666666666666667
6 0.3333333333333333 0
6 0.6666666666666666 0
5.666666666666666 0.6666666666666667 0
5.333333333333333 0.3333333333333334 0
6 1 0.6666666666666667
6 1 0.3333333333333334
5.666666666666666 0.3333333333333334 0
5.666666666666666 0.6666666666666667 0.3333333333333334
6 0.6666666666666666 0.3333333333333334
5.333333333333334 1 1
5.666666666666667 1 1
5.333333333333333 0.6666666666666667 0.6666666666666667
5.333333333333333 0.6666666666666667 0.9999999999999998
5.666666666666666 1 0.6666666666666667
5.333333333333333 1 0.3333333333333334
5.333333333333332 0.6666666666666667 0.3333333333333334
5.333333333333333 0.9999999999999998 0.6666666666666667
5.666666666666666 1 0
5.333333333333333 1 0
5.333333333333332 0.6666666666666666 0
5.666666666666666 0.9999999999999998 0.3333333333333334
6.333333333333333 0 1
6.666666666666666 0 1
6.666666666666667 0 0.6666666666666667
6.333333333333334 0 0.3333333333333334
6.666666666666667 0.6666666666666667 0.6666666666666667
6.333333333333334 0.3333333333333334 0.3333333333333334
7 0.6666666666666667 1
7 0.3333333333333334 1
6.666666666666667 0.6666666666666667 1
6.333333333333334 0.3333333333333334 1
6.333333333333334 0 0.6666666666666667
6.333333333333334 0.3333333333333334 0.6666666666666667
6.666666666666666 0.3333333333333334 0.6666666666666667
6.666666666666666 0.3333333333333334 0.9999999999999998
6.666666666666667 0 0
6.333333333333334 0 0
7 0 0.6666666666666667
7 0 0.3333333333333334
7 0.6666666666666667 0.6666666666666667
7 0.3333333333333334 0.3333333333333334
6.666666666666667 0 0.3333333333333334
6.666666666666667 0.3333333333333334 0.3333333333333334
6.999999999999999 0.3333333333333334 0.6666666666666667
7 0.3333333333333333 0
7 0.6666666666666666 0
6.666666666666667 0.6666666666666667 0
6.333333333333334 0.3333333333333334 0
7 1 0.6666666666666667
7 1 0.3333333333333334
6.666666666666666 0.3333333333333334 0
6.666666666666666 0.6666666666666667 0.3333333333333334
6.999999999999999 0.6666666666666666 0.3333333333333334
6.333333333333333 1 1
6.666666666666666 1 1
6.333333333333332 0.6666666666666667 0.6666666666666667
6.333333333333333 0.6666666666666667 0.9999999999999998
6.666666666666667 1 0.6666666666666667
6.333333333333334 1 0.3333333333333334
6.333333333333334 0.6666666666666667 0.3333333333333334
6.333333333333332 0.9999999999999998 0.6666666666666667
6.666666666666667 1 0
6.333333333333334 1 0
6.333333333333334 0.6666666666666666 0
6.666666666666667 0.9999999999999998 0.3333333333333334
7.333333333333334 0 1
7.666666666666666 0 1
7.666666666666667 0 0.6666666666666667
7.333333333333333 0 0.3333333333333334
7.666666666666667 0.6666666666666667 0.6666666666666667
7.333333333333333 0.3333333333333334 0.3333333333333334
8 0.6666666666666667 1
8 0.3333333333333334 1
7.666666666666667 0.6666666666666667 1
7.333333333333333 0.3333333333333334 1
7.333333333333332 0 0.6666666666666667
7.333333333333334 0.3333333333333334 0.6666666666666667
7.666666666666666 0.3333333333333334 0.6666666666666667
7.666666666666666 0.3333333333333334 0.9999999999999998
7.666666666666667 0 0
7.333333333333333 0 0
8 0 0.6666666666666667
8 0 0.3333333333333334
8 0.6666666666666667 0.6666666666666667
8 0.3333333333333334 0.3333333333333334
7.666666666666666 0 0.3333333333333334
7.666666666666666 0.3333333333333334 0.3333333333333334
7.999999999999998 0.3333333333333334 0.6666666666666667
8 0.3333333333333333 0
8 0.6666666666666666 0
7.666666666666667 0.6666666666666667 0
7.333333333333333 0.3333333333333334 0
8 1 0.6666666666666667
8 1 0.3333333333333334
7.666666666666666 0.3333333333333334 0
7.666666666666666 0.6666666666666667 0.3333333333333334
7.999999999999998 0.6666666666666666 0.3333333333333334
7.333333333333334 1 1
7.666666666666666 1 1
7.333333333333334 0.6666666666666667 0.6666666666666667
7.333333333333334 0.6666666666666667 0.9999999999999998
7.666666666666667 1 0.6666666666666667
7.333333333333333 1 0.3333333333333334
7.333333333333331 0.6666666666666667 0.3333333333333334
7.333333333333334 0.9999999999999998 0.6666666666666667
7.666666666666667 1 0
7.333333333333333 1 0
7.333333333333334 0.6666666666666666 0
7.666666666666666 0.9999999999999998 0.3333333333333334
CELLS 48 1008
20 0 18 19 28 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51
20 1 0 19 28 52 53 41 40 54 55 56 57 44 45 42 43 58 59 60 50
20 0 1 10 28 53 52 61 62 63 64 42 43 65 66 56 57 67 59 68 69
20 0 18 28 27 36 37 47 46 42 43 70 71 72 73 74 75 49 76 77 78
20 9 0 28 27 79 80 43 42 81 82 83 84 72 73 70 71 85 86 87 77
20 0 10 9 28 64 63 88 89 79 80 42 43 81 82 65 66 90 68 85 91
20 1 19 20 29 55 54 92 93 94 95 96 97 98 99 100 101 102 103 104 105
20 2 1 20 29 106 107 95 94 108 109 110 111 98 99 96 97 112 113 114 104
20 1 2 11 29 107 106 115 116 117 118 96 97 119 120 110 111 121 113 122 123
20 1 19 29 28 55 54 101 100 96 97 56 57 124 125 44 45 103 60 126 127
20 10 1 29 28 62 61 97 96 128 129 65 66 124 125 56 57 130 69 131 126
20 1 11 10 29 118 117 132 133 62 61 96 97 128 129 119 120 134 122 130 135
20 2 20 21 30 109 108 136 137 138 139 140 141 142 143 144 145 146 147 148 149
20 3 2 21 30 150 151 139 138 152 153 154 155 142 143 140 141 156 157 158 148
20 2 3 12 30 151 150 159 160 161 162 140 141 163 164 154 155 165 157 166 167
20 2 20 30 29 109 108 145 144 140 141 110 111 168 169 98 99 147 114 170 171
20 11 2 30 29 116 115 141 140 172 173 119 120 168 169 110 111 174 123 175 170
20 2 12 11 30 162 161 176 177 116 115 140 141 172 173 163 164 178 166 174 179
20 3 21 22 31 153 152 180 181 182 183 184 185 186 187 188 189 190 191 192 193
20 4 3 22 31 194 195 183 182 196 197 198 199 186 187 184 185 200 201 202 192
20 3 4 13 31 195 194 203 204 205 206 184 185 207 208 198 199 209 201 210 211
20 3 21 31 30 153 152 189 188 184 185 154 155 212 213 142 143 191 158 214 215
20 12 3 31 30 160 159 185 184 216 217 163 164 212 213 154 155 218 167 219 214
20 3 13 12 31 206 205 220 221 160 159 184 185 216 217 207 208 222 210 218 223
20 4 22 23 32 197 196 224 225 226 227 228 229 230 231 232 233 234 235 236 237
20 5 4 23 32 238 239 227 226 240 241 242 243 230 231 228 229 244 245 246 236
20 4 5 14 32 239 238 247 248 249 250 228 229 251 252 242 243 253 245 254 255
20 4 22 32 31 197 196 233 232 228 229 198 199 256 257 186 187 235 202 258 259
20 13 4 32 31 204 203 229 228 260 261 207 208 256 257 198 199 262 211 263 258
20 4 14 13 32 250 249 264 265 204 203 228 229 260 261 251 252 266 254 262 267
20 5 23 24 33 241 240 268 269 270 271 272 273 274 275 276 277 278 279 280 281
20 6 5 24 33 282 283 271 270 284 285 286 287 274 275 272 273 288 289 290 280
20 5 6 15 33 283 282 291 292 293 294 272 273 295 296 286 287 297 289 298 299
20 5 23 33 32 241 240 277 276 272 273 242 243 300 301 230 231 279 246 302 303
20 14 5 33 32 248 247 273 272 304 305 251 252 300 301 242 243 306 255 307 302
20 5 15 14 33 294 293 308 309 248 247 272 273 304 305 295 296 310 298 306 311
20 6 24 25 34 285 284 312 313 314 315 316 317 318 319 320 321 322 323 324 325
20 7 6 25 34 326 327 315 314 328 329 330 331 318 319 316 317 332 333 334 324
20 6 7 16 34 327 326 335 336 337 338 316 317 339 340 330 331 341 333 342 343
20 6 24 34 33 285 284 321 320 316 317 286 287 344 345 274 275 323 290 346 347
20 15 6 34 33 292 291 317 316 348 349 295 296 344 345 286 287 350 299 351 346
20 6 16 15 34 338 337 352 353 292 291 316 317 348 349 339 340 354 342 350 355
20 7 25 26 35 329 328 356 357 358 359 360 361 362 363 364 365 366 367 368 369
20 8 7 26 35 370 371 359 358 372 373 374 375 362 363 360 361 376 377 378 368
20 7 8 17 35 371 370 379 380 381 382 360 361 383 384 374 375 385 377 386 387
20 7 25 35 34 329 328 365 364 360 361 330 331 388 389 318 319 367 334 390 391
20 16 7 35 34 336 335 361 360 392 393 339 340 388 389 330 331 394 343 395 390
20 7 17 16 35 382 381 396 397 336 335 360 361 392 393 383 384 398 386 394 399
CELL_TYPES 48
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
CELL_DATA 48
SCALARS material int
LOOKUP_TABLE default
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2

**Comment by pazner** [comment]
VTK meshes don't store boundary attributes/materials, and so they're not well-suited for use with ex2.

Try saving your file in gmsh 2.2 format (and make sure that your boundary has two physical tags/groups.

**Comment by pazner** [comment]
See issues #2223 and #3748 for examples of Gmsh meshes that work with ex2.
