### ISSUE TITLE
Convergence study for an anisotropic Laplace equation

### ISSUE THREAD

**Issue by LeilaSalomon** [mfem/mfem#3808]
Hello,

I would like to perform a mesh convergence study for an anisotropic Laplace equation, where the equation is : 

![image](https://github.com/mfem/mfem/assets/40572513/0f4e4eb4-5c8b-4bb2-a926-ee0e3b250de4)

We impose a Dirichlet condition : 

![image](https://github.com/mfem/mfem/assets/40572513/7d20f6fd-3768-487b-9b01-f5a513a63b78)

on a node and a Neumann condition on the set of boundaries : 

![image](https://github.com/mfem/mfem/assets/40572513/1ff6d51e-dcd5-45fd-bb47-559cdcde3013),

were C is a constant.

It is very simple to compute an analytical solution of the problem. However , I would like to know how can I interpret the convergence of the results. Should we expect a particular convergence order? Depending on the interpolation order ?

Regards,
Leila

**Comment by psocratis** [comment]
@LeilaSalomon, you may want to take a look at `./tests/convergence/rates.cpp` for some examples which compute the expected convergence rate (for smooth solutions) for the Laplace problem.
