### ISSUE TITLE
Non-conservative advection equation (upwind flux)

### ISSUE THREAD

**Issue by LeilaSalomon** [mfem/mfem#3809]
Hello,

I would like to know where can I find a publication that contains a similar case to example 9, where a **non-conservative** advection equation is solved, with a DG formulation (upwind flux).

Regards,

Leila

**Comment by pazner** [comment]
You can take a look at [this paper](https://www.scorec.rpi.edu/~shephard/solution-transfer/Anderson_et_al-2015-International_Journal_for_Numerical_Methods_in_Fluids.pdf), where the conservative discretization is given in equation (9) and the non-conservative form is given in equation (11). Note that in some simple cases, these two formulations are exactly equivalent. But in general (variable velocity fields, curved meshes, etc.), they will differ.

All it comes down to is integrating by parts to move the derivative to the test function or trial function. If the derivative is on the test function, the method will be conservative (set the test function to be identically one to get the time derivative of the total mass), and if the derivative is on the trial function, the method will be constant-preserving.

**Comment by LeilaSalomon** [comment]
Hello,

Thank you for you answer,

I can't seem to link the explanation found in MFEM:

`Integrator` for the DG form :
alpha < rho_u (u.n) {v},[w] > + beta < rho_u |u.n| [v],[w] >,

     One use case for this integrator is to discretize the operator -u.grad(v)
     with a DG formulation. The resulting formulation uses the
     ConvectionIntegrator (with coefficient u, and parameter alpha = -1) and the
     transpose of the DGTraceIntegrator (with coefficient u, and parameters alpha
     = 1, beta = -1/2 to use the upwind face flux, see also
     NonconservativeDGTraceIntegrator).
 
     Another use case for this integrator is to discretize the operator -div(u v)
     with a DG formulation. The resulting formulation is conservative and
     consists of the ConservativeConvectionIntegrator (with coefficient u, and
     parameter alpha = -1) plus the DGTraceIntegrator (with coefficient u, and
     parameters alpha = -1, beta = -1/2 to use the upwind face flux).`

and the paper.

For me, we do not use the same sign for the coefficients alpha and beta in the paper and in the MFEM explanations.
