### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by Tengen-zz** [mfem/mfem#381]
I installed MFEM by guides on the site. But when I try to compilate my program it shows this error:

/usr/bin/ld: cannot find -lmfem
collect2: error: ld returned 1 exit status
CMakeFiles/geolines.dir/build.make:94: recipe for target 'geolines' failed
make[2]: *** [geolines] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/geolines.dir/all' failed
make[1]: *** [CMakeFiles/geolines.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

My system: linux Mint 18.2.

**Comment by tzanio** [comment]
If you have built and installed MFEM with CMake, we provide a `MFEMConfig.cmake` which you should be able to use in your CMake build. If you have built instead in-source with make, then you just need to provide the paths to include `mfem.hpp` and link with `libmfem.a`.

Hope this helps,
Tzanio

**Comment by v-dobrev** [comment]
As an example for using MFEM in another CMake project, take a look at the CMake file in GLVis: https://github.com/GLVis/glvis/blob/master/CMakeLists.txt

**Comment by tzanio** [comment]
Closing this issue. Feel free to re-open if you have further questions.
