### ISSUE TITLE
Exploring CUDA Acceleration: Testing HYPRE and MFEM Integration with CUDA 12.2 on GTX 3080 Ti

### ISSUE THREAD

**Issue by sungho91** [mfem/mfem#3812]
Hello everyone,

I have compiled HYPRE and MFEM with CUDA (CUDA version 12.2; GTX 3080 Ti).
I would like to test this CUDA-supported version. Do we have any examples to test it?

Best regards,

Sungho

**Comment by pazner** [comment]
Example 1 (and its parallel version) support CUDA, you can try out some of the sample runs.

https://github.com/mfem/mfem/blob/541f10f9b44fd52bacde793a08dc19e53a8972ec/examples/ex1p.cpp#L31-L33

Many of the other examples support CUDA as well, look for the `--device` flag or consult the list [here](https://mfem.org/examples/)

**Comment by sungho91** [comment]
@pazner Thank you so much!
