### ISSUE TITLE
Question on using MFEM with Moonolith library

### ISSUE THREAD

**Issue by ryanblack129** [mfem/mfem#3813]
Hello, 

I wanted to ask about using the Moonolith library with MFEM to perform solution transfer between meshes.

I noticed at the end of the doxygen description for `ParMortarAssembler`, it says a local version of the projection would be needed for DG spaces. I was wondering what modifications would be needed to make this work for DG spaces of order  > 0 ?

Thanks,
Ryan

**Comment by zulianp** [comment]
Hello Ryan,

The current implementation of the variational resampling in MFEM is based on the L2-projection, which is a global operation and involves a solution of a linear system of the form` v_dest = D^{-1} B v_source`. Discontinuities in the source field lead to undesirable global effects on the projected field. Typically, a localized version (https://doc.rero.ch/record/291516/files/S100489790000012X.pdf)  would involve some sort of lumping of the mass-matrix `D` by choosing suitable spaces for the Lagrange multiplier, and even if they are an approximation of the L2 projection in our experience, they are more robust. This observation is relevant primarily for DG source and CG destination spaces. My experience with DG as a destination space is minimal, but I think it would require a bit of investigation.

After investigation,  what would need to be done is probably modify the quadrature routines around `AssembleElementMatrix` and some algebra in the `Apply` method. I would be happy to have collaboration around this.

Cheers,
Patrick

**Comment by ryanblack129** [comment]
Hi Patrick,

Sorry for the delay, I was away on vacation.

Thanks so much for the reply, pointing me to the paper, and very kind offer to work with me on this. Currently, I am writing my thesis proposal so that is taking up all my time for the next few weeks. But after I'm done with that, I would love to hear more about what it would take to make this work.

Best,
Ryan
