### ISSUE TITLE
EdgeVertexTable in 2D?

### ISSUE THREAD

**Issue by AntonIatcenko** [mfem/mfem#3818]
I see that in the code documentation and in the [HowTo article ](https://mfem.org/howto/nav-mesh-connectivity/) the GetEdgeVertexTable function is listed only for 3D meshes, but doesn't it work the same in 2D? The implementation code does not use the dim variable anywhere, and looks like it should work the same in 2D (or any other D for that matter). Is it just a documentation glitch, or am I missing something?

**Comment by v-dobrev** [comment]
I think you are right: `GetEdgeVertexTable` should work in any dimension.

@acfisher, @tzanio, if you agree, we should correct the above-mentioned HowTo article: https://mfem.org/howto/nav-mesh-connectivity/.

**Comment by tzanio** [comment]
I agree

**Comment by acfisher** [comment]
Agreed we I think I wrote that one so I'll have a look at the howto.

**Comment by acfisher** [comment]
Fixed it
