### ISSUE TITLE
Multiple builds

### ISSUE THREAD

**Issue by AntonIatcenko** [mfem/mfem#3836]
Hello Everyone, 

Is it possible to have multiple builds of the same version of MFEM on one machine? I have a full parallel build, and I would also like to have a bare-bones serial build. I tried downloading the source again to a different directory and building from there, but I just get 

>make serial -j
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f makefile config MFEM_USE_MPI=NO MFEM_DEBUG=NO \
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C config all
Build destination: <source> [/Applications/HPC/mfem-4.5.2]
/Applications/Xcode.app/Contents/Developer/usr/bin/make 
make[1]: Nothing to be done for `lib'.

The /Applications/HPC/mfem-4.5.2 is the directory of the existing parallel build, and I'm trying to build serial from /Applications/HPC/mfem-4.5.2_serial

**Comment by v-dobrev** [comment]
The default build destination is the source directory, so if you have the MFEM sources in `/Applications/HPC/mfem-4.5.2_serial` and you run `make serial -j` from that directory, then the build directory should be the same as the source which is the same as the current directory.

You can also set explicitly a build directory that is different from the source directory, see https://github.com/mfem/mfem/blob/a15866e212b167ab83d5384e7326cdd3fa0723b2/INSTALL#L158-L175
