### ISSUE TITLE
mesh::Print does not output material attributes for NCMesh

### ISSUE THREAD

**Issue by jtristano** [mfem/mfem#3839]
I have a refined mesh using a modified shaper for plate w/ hole.  When I call mesh::print, the element attributes are not written.  I believe this is because  the NCMesh copy of it's elements does not have the attribute set.  When print is called, it delegates to the ncmesh print and uses it's element definitions not the user mesh.   Please correct me if I'm wrong here.

Thanks
Joe

**Comment by jtristano** [comment]
This seems very similar to https://github.com/mfem/mfem/issues/3247

Would it not be appropriate to extend SetAttributes to go down to the NC Mesh and set the attributes on the leaf nodes of the mesh?

**Comment by v-dobrev** [comment]
The attributes are supposed to be stored in both the `Mesh` and the `NCMesh`, see here for the case of `NCMesh`: https://github.com/mfem/mfem/blob/8a4affef5af84d74c9691f76b49624bdd7199d60/mesh/ncmesh.hpp#L527-L547

After operations on the `NCMesh`, the `Mesh` is re-created from the `NCMesh` and in particular using the attributes stored in `NCMesh`. That said, in the case of rebalancing, it looks like the attributes in the `ParNCMesh` are lost, see #4009. Is it possible that what you see is due to the same issue?

**Comment by jtristano** [comment]
It’s been a while since I looked at this.  From
what I remember, we just refined as with the shaper mini app.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by v-dobrev** [comment]
To address this issue, we'll probably need more specifics. Ideally if you can provide some instructions on how to reproduce the issue, that will be great.

**Comment by jtristano** [comment]
If you run the shaper mini app and perform a non conformal refinement, I believe that the attributes are lost when the mesh is saved.  It's been a while.  If that fails to reproduce the problem, feel free to close this issue.

Once we get NCMesh working with matrix free we will probably revisit this but it wont be for a while

**Comment by dylan-copeland** [comment]
I tried unsuccessfully to reproduce the issue. There may be a problem in some cases, but we may need help to find such cases. Here is what I tried:

1. In `data/star.mesh`, I set the attributes for the first 5 elements to be 2 through 6. 
2. In `shaper.cpp`, I refined elements 0, 5, 10, 15.
3. Running `shaper` through a few iterations on this mesh produces an `NCMesh` with 1100 elements (many local refinements) and correct attributes.

**Comment by jtristano** [comment]
Please try with a hex mesh
________________________________

**Comment by dylan-copeland** [comment]
I just tried the same procedure with `data/fichera.mesh` and `data/toroid-hex.mesh` (which has a hole), and the attribute were still reproduced correctly.

**Comment by jtristano** [comment]
Good to know! Thanks!
Joe
________________________________
