### ISSUE TITLE
ParSubMesh::CreateFromBoundary bug in 2D

### ISSUE THREAD

**Issue by gridfunction** [mfem/mfem#3840]
Hello, 

There is a typo in tests/unit/mesh/test_psubmesh.cpp, line 120
`auto boundary_submesh = ParSubMesh::CreateFromDomain(parent_mesh,
                                                         boundary1);
`
It should be CreateFromBoundary. 

I got the following error when trying to create a 1D psubmesh on the boundary from a 2D mesh:

Assertion failed: ((flags & VALID_HOST)) is false:
 --> invalid host pointer access
 ... in function: const T& mfem::Memory<T>::operator[](int) const [with T = int]
 ... in file: general/mem_manager.hpp:1079

This bug seems to be triggered in line 319-340 of mesh/submesh/psubmesh.cpp 
 
Best,
Guosheng

**Comment by pazner** [comment]
Do the changes in [this branch](https://github.com/mfem/mfem/tree/psubmesh-test-fix) fix it for you?

**Comment by sungho91** [comment]
@gridfunction, Whatever boundary attributes or domain attributes, I've observed submesh is always indicating only the first boundary and domain attributes. Did you observe a similar thing?

**Comment by gridfunction** [comment]
yes. for my purpose, i always use homogenous neumann bdry conditions, so
it's not an issue. If you want mixed boundary segments, i guess you have to
manually do it by yourself.
