### ISSUE TITLE
Hanging node detached issue in NCmesh

### ISSUE THREAD

**Issue by sungho91** [mfem/mfem#3848]
Hello everyone,

I have a quick question regarding nonconforming meshes.

My code reads the mesh file and then performs some uniform and local refinements. Before the local refinement, the code executes the statement "`mesh->EnsureNCMesh(true)`".

After completing these processes, the code generates a parallel mesh using the following lines:

```
ParMesh *pmesh = nullptr;
pmesh = new ParMesh(MPI_COMM_WORLD, *mesh, partitioning);
```

Here, I'm wondering if the pmesh inherently handles nonconforming meshes, or if I'm supposed to explicitly assign NC properties to pmesh again.

I tested the elastoplastic material by applying forces to each side under partial aseembly. The results seem reasonable, but I noticed detached nodes at hanging node points (see att.).

Does anyone have any ideas about this issue?

Best regards

Sungho

![Figure1](https://github.com/mfem/mfem/assets/40257026/871e0498-7b0c-4d67-8a33-a15423b5333b)

**Comment by v-dobrev** [comment]
This gap may be just a visualization artifact -- if all elements are drawn by subdividing its edges into 2 (it looks like that is the case based on some of the more curved edges in the plot) then non-conforming edges are subdivided differently on the master and the slave sides -- the slave side used 2x more straight lines -- which can lead to visual gaps on curved nonconforming edges even if they are just slightly curved. Here's an example:
<img width="207" alt="image" src="https://github.com/mfem/mfem/assets/12926030/aed640d1-b86c-42de-8a01-ee7409d03e91">

**Comment by sungho91** [comment]
@v-dobrev 

I appreciate your explanation. It sounds reasonable.

I encountered a similar issue when using TMOP. After modifying my model (refer to Fig. A and B), I discovered an unconditionally detached node at the hanging-node points (refer to Fig. C). Without invoking TMOP, they remained attached in the same time step.

Do you believe this is comparable to visualization artifacts?

Many Thanks

Sungho

![Figure2](https://github.com/mfem/mfem/assets/40257026/c2376c68-89ea-469f-a164-2022df160cf0)

**Comment by tzanio** [comment]
ping: @vladotomov, @kmittal2

**Comment by vladotomov** [comment]
Hi @sungho91,

TMOP is capable of optimizing nonconforming meshes (there should be no detached nodes) and we have some tests in the `mesh-optimizer` and `pmesh-optimizer` miniapps, for example:
`mpirun -np 4 pmesh-optimizer -m ./amr-quad-q2.mesh -o 2 -rs 1 -mid 9 -tid 2 -ni 200 -bnd -qt 1 -qo 8`

Are you following a similar setup as in those examples? It's hard to say what's wrong only by looking at the pictures.

**Comment by v-dobrev** [comment]
If you have perspective on in ParaView then the gap may also be due to variations in the z-values.

**Comment by sungho91** [comment]
@vladotomov and @v-dobrev 
Thank you for commenting. 

I explored some tests. As @v-dobrev said before, the gap seems to arise from a severe curve between the non-conforming mesh.

TMOP probably drives curved features in fixing the boundary for mesh modification because my model boundary is deformed over time, I don't know how to solve this issue yet. So, I'll get back on the issue again when I resolve this. 

Thank you.
