### ISSUE TITLE
Multi-Point constraint crossing processors #3341

### ISSUE THREAD

**Issue by jtristano** [mfem/mfem#3849]
@vladotomov  --- fyi

              I'd like to reopen this thread @vladotomov  as I'm interested in the same thing

Here's a picture of what @CodingDrRui  is talking about.   You have a finite element mesh with a remote load that is transferred by many rigid (infinitley stiff spars or 1d elements)

When performing structural analysis this trick is used to simplify modeling.

![image](https://github.com/mfem/mfem/assets/136379293/3552ede7-4549-4fce-b346-18af44fc47ba)

I tried to create sample mesh
```
MFEM mesh v1.0

#
# MFEM Geometry Types (see mesh/geom.hpp):
#
# POINT       = 0
# SEGMENT     = 1
# TRIANGLE    = 2
# SQUARE      = 3
# TETRAHEDRON = 4
# CUBE        = 5
#

dimension
3

elements
11
1 5 0 1 10 9 18 19 28 27
1 5 1 2 11 10 19 20 29 28
1 5 2 3 12 11 20 21 30 29
1 5 3 4 13 12 21 22 31 30
2 5 4 5 14 13 22 23 32 31
2 5 5 6 15 14 23 24 33 32
2 5 6 7 16 15 24 25 34 33
2 5 7 8 17 16 25 26 35 34
3 1 35 36
3 1 36 37
4 0 37

boundary
34
3 3 9 10 1 0
3 3 0 1 19 18
3 3 10 9 27 28
1 3 9 0 18 27
3 3 18 19 28 27
3 3 10 11 2 1
3 3 1 2 20 19
3 3 11 10 28 29
3 3 19 20 29 28
3 3 11 12 3 2
3 3 2 3 21 20
3 3 12 11 29 30
3 3 20 21 30 29
3 3 12 13 4 3
3 3 3 4 22 21
3 3 13 12 30 31
3 3 21 22 31 30
3 3 13 14 5 4
3 3 4 5 23 22
3 3 14 13 31 32
3 3 22 23 32 31
3 3 14 15 6 5
3 3 5 6 24 23
3 3 15 14 32 33
3 3 23 24 33 32
3 3 15 16 7 6
3 3 6 7 25 24
3 3 16 15 33 34
3 3 24 25 34 33
3 3 16 17 8 7
3 3 7 8 26 25
2 3 8 17 35 26
3 3 17 16 34 35
3 3 25 26 35 34


vertices
38
3
0 0 0
1 0 0
2 0 0
3 0 0
4 0 0
5 0 0
6 0 0
7 0 0
8 0 0
0 1 0
1 1 0
2 1 0
3 1 0
4 1 0
5 1 0
6 1 0
7 1 0
8 1 0
0 0 1
1 0 1
2 0 1
3 0 1
4 0 1
5 0 1
6 0 1
7 0 1
8 0 1
0 1 1
1 1 1
2 1 1
3 1 1
4 1 1
5 1 1
6 1 1
7 1 1
8 1 1
-2 0 0
-1 0 0

```
And mesh explorer blew up since the mesh did not contain all solid elements.

How would you do this in MFEM and still allow to use the matrix free operator in the hooke mini app?

_Originally posted by @jtristano in https://github.com/mfem/mfem/issues/3341#issuecomment-1698105114_

**Comment by jtristano** [comment]
https://vdocuments.net/rbes-and-mpcs-in-mscnastran-a-rip-roarin-review-of-rigid-elements.html

**Comment by v-dobrev** [comment]
I posted a reply in the original issue: see https://github.com/mfem/mfem/issues/3341#issuecomment-1698640440.
