### ISSUE TITLE
DG Dirichlet Boundary conditions for interior faces

### ISSUE THREAD

**Issue by Heinrich-BR** [mfem/mfem#3853]
Hello, I am trying to apply Dirichlet boundary conditions on an internal surface in a DG implementation. While I can apply such conditions to the boundary of the system, nothing I do seems to apply it to the internal face. For reference, this is how I am trying to implement this, where `bdr_array_V0` and `bdr_array_V1` are the marker arrays for the external boundaries:

``` LinearForm *b = new LinearForm(fespace);
   BilinearForm *a = new BilinearForm(fespace);

   a->AddDomainIntegrator(new DiffusionIntegrator(one));
   b->AddDomainIntegrator(new DomainLFIntegrator(zero));

   a->AddInteriorFaceIntegrator(new DGDiffusionIntegrator(one, sigma, kappa));
   a->AddBdrFaceIntegrator(new DGDiffusionIntegrator(one, sigma, kappa), bdr_array_V1);
   a->AddBdrFaceIntegrator(new DGDiffusionIntegrator(one, sigma, kappa), bdr_array_V0);

   b->AddBdrFaceIntegrator(new DGDirichletLFIntegrator(one, sigma, kappa),bdr_array_V1);
   b->AddBdrFaceIntegrator(new DGDirichletLFIntegrator(zero, sigma, kappa),bdr_array_V0);

   b->AddInteriorFaceIntegrator(new DGDirichletLFIntegrator(one, sigma, kappa));

   a->Assemble();
   a->Finalize();
   b->Assemble();
```

The problematic line is when I add the `DGDirichletLFIntegrator` to `b` and assemble it. I get the following error at runtime:

 `LinearFormIntegrator::AssembleRHSElementVect(...)`

It seems that this functionality is somehow not implemeted? Or perhaps I am using the DG integrators incorrectly, which is possible due to me being new to this. I tried to bypass this issue using the `AddInternalBoundaryFaceIntegrator` method implemented in #3777, but stumbled upon the same problem. All in all, is there an issue with how I implemented the conditions in the code snippet above, and if not, is there a way to implement Dirichlet boundary conditions in interior faces under DG? Thank you!

**Comment by vladotomov** [comment]
Hi @Heinrich-BR, the `DGDirichletLFIntegrator` is not implemented for internal faces (that use info from the 2 sides), it's only implemented for boundary faces (that use only 1 side). The function that aborts is this:

```
void LinearFormIntegrator::AssembleRHSElementVect(
   const FiniteElement &el1, const FiniteElement &el2,
   FaceElementTransformations &Tr, Vector &elvect)
{
   mfem_error("LinearFormIntegrator::AssembleRHSElementVect(...)");
}
```

I'm not sure what you want to achieve, and whether doing it weakly is the best approach, but if you want to use the DG integrator, you'll have to implement the above.
