### ISSUE TITLE
Issue with LinearForm constructor

### ISSUE THREAD

**Issue by aschaf** [mfem/mfem#3855]
Hi,

when using the `LinearForm(FiniteElementSpace *f, LinearForm *lf)` constructor, the member arrays `domain_integs_marker` as well as the `boundary_integs_marker` do not get copied over. Is this intended behavior? Because the `boundary_face_integs_marker` array does get copied.

Thanks and best regards,
Andreas

**Comment by v-dobrev** [comment]
Hi Andreas,

This sounds like a bug/omission -- to me it makes sense to copy the markers as well. Do you want to create a PR to fix this?

Thanks!
Veselin

**Comment by aschaf** [comment]
Hi Veselin,

yes, I will make a PR.

Best, Andreas

**Comment by tzanio** [comment]
@aschaf, was this resolved?

**Comment by aschaf** [comment]
Resolved with #3869
