### ISSUE TITLE
Configuring with cmake from git results in error

### ISSUE THREAD

**Issue by juan42** [mfem/mfem#386]
Using my cmake build script
```
#!/bin/sh

find . CMakeFiles CMakeCache.txt config | xargs | rm -rf

cmake .. \
      -DCMAKE_BUILD_TYPE=Debug \
      -DCMAKE_INSTALL_PREFIX=${HOME}/local/mfem-git \
      -DBUILD_SHARED_LIBS=ON \
      -DMFEM_USE_MPI=ON \
      -DMFEM_USE_SUPERLU=ON \
      -DMFEM_USE_SUNDIALS=ON \
      -DMFEM_USE_NETCDF=ON
```
I get an error because MFEM_GIT_STRING is somehow not set.
```
mfem/general/version.cpp:61:33: error: ‘MFEM_GIT_STRING’ was not declared in this scope
    static const char *git_str = MFEM_GIT_STRING;
```
This seems to be a regression in the cmake build if I am correct.
Although it should be defined in https://github.com/mfem/mfem/blob/master/config/cmake/config.hpp.in#L34.

During the cmake execution the file `MFEMConfig.cmake` is created but with an empty expression for set(MFEM_GIT_STRING "").

I assume the problem is the interface used to access the git version which is not compatible on my git version. This is a CentOS 7 machine with git-1.8.3.1-12.el7_4.x86_64 :-1: .

**Comment by tzanio** [comment]
The `MFEM_GIT_STRING` is a recent addition. @benson31, @v-dobrev can you take a look at this?

**Comment by benson31** [comment]
I recommend upgrading [git to 2.*](https://github.com/git/git).

However, if you don't care about the value of this string, you can pass `-DMFEM_GIT_STRING="MFEMdev"` or something. That will get you through compilation.

**Comment by benson31** [comment]
That said, MFEM should probably have a default value for if it's not set.

Semi-related:
```
set(VARIABLE "")
set(VARIABLE)
unset(VARIABLE)
```
are all equivalent. It's not set to an empty string. It's just unset.

**Comment by v-dobrev** [comment]
This should be easy to fix: it seems that the `-C <dir>` option does not work in older git versions, so it should be replaced with the `WORKING_DIRECTORY` option of `execute_process`. The other thing is to replace `set(${PROJECT_NAME_UC}_GIT_STRING "")` with a non-empty string. I'll make a branch to fix this.

**Comment by juan42** [comment]
Works fine now!
