### ISSUE TITLE
Applying diffusion integrator only for the top Boundary?

### ISSUE THREAD

**Issue by sungho91** [mfem/mfem#3864]
Hi all,

I'd like to adjust and smooth high-frequency tomography (att. fig) on the top boundary after large deformation employing diffusion processes like weathering or erosion. 

I'm thinking of solving div*(grad(nodes on top boundary)) = rate of erosion and the mesh update for top nodes.

Can we take nodes of the top boundary and apply diffusion integrator for the node sets corresponding to the top boundary? 

Best

Sungho

![g3](https://github.com/mfem/mfem/assets/40257026/224b1eaf-2a92-4f36-b529-0ab07a0d727f)

**Comment by pazner** [comment]
Maybe something simpler like [Laplacian smoothing](https://en.wikipedia.org/wiki/Laplacian_smoothing) for the mesh could work?

If not, I think you can use SubMesh to solve a problem like this on the boundary. An example is [here](https://gist.github.com/pazner/56b4b8e84f33b76836d783aedecdf69b).

**Comment by sungho91** [comment]
@pazner Thank you very much. I think this is what I'd like to look for.

**Comment by sungho91** [comment]
@pazner And for some reasons, whatever `bdr_attrs[#]` it is, submesh only indicates the first boundary bdr_attrs[0].

**Comment by pazner** [comment]
I believe `bdr_attrs` should be a list of attributes rather than a marker array.

**Comment by sungho91** [comment]
@pazner meant that not an array of boundary attributes but an array of lists of nodes associated with the boundary?

**Comment by pazner** [comment]
If you want to extract boundary attribute 3, and no other attributes, you should set
```cpp
Array<int> bdr_attrs(1);
bdr_attrs[0] = 3;
```
In other words, `bdr_attrs` should have one entry for each of the attributes you wish to extract.

**Comment by sungho91** [comment]
Thank you @pazner, 

It works now, and I can extract a submesh of the top boundary (att).

I tried to print out the number of elements in the submesh.
`cout << submesh.GetNE() << endl;`
It printed out 0 / 0 / 10 / 0 / 8 / 0 / 8 / 10 / 0.

Since I used 10 processors, it's expected that some processors may not have elements in the submesh. 
This makes sense.

However, a problem arises when I attempt to create a finite element space using `ParFiniteElementSpace sub_fespace(&submesh, &H1FEC);`.

I encountered a segmentation fault. But if I use a single processor or there is no partition of the submesh, the segmentation fault is avoided."

Do you have any idea about this?

![Mesh_submesh](https://github.com/mfem/mfem/assets/40257026/03ba28e2-f16a-4718-8484-3bf60201445e)

**Comment by pazner** [comment]
You might be running into the bug described in #3840. Can you see if the changes in [this branch](https://github.com/mfem/mfem/tree/psubmesh-test-fix) fix the issue for you?

Also, are you compiling/running in debug mode? That might help get some more informative error messages.

**Comment by sungho91** [comment]
@pazner, Yes, that branch works for my problem. Thank you.
It means that the master branch of MFEM has some bug with ParSubMesh?

**Comment by jandrej** [comment]
> @pazner, Yes, that branch works for my problem. Thank you.
> It means that the master branch of MFEM has some bug with ParSubMesh?

Yes, in 1D ParSubMesh with multiple processors, some internal variables were not set correctly.

**Comment by sungho91** [comment]
@jandrej Thank you for clarifying.
