### ISSUE TITLE
electromagnetism

### ISSUE THREAD

**Issue by azmmza** [mfem/mfem#3867]
Dear MFEM Team,
   It took me a while to get to know MFEM, As far as I can tell, MFEM seems to construct high order basis functions by interpolating.  For my personal needs, I may use hierarchical  basis functions to build higher-order basis functions for P-adaptive.
   In electromagnetism,  Take Nedelec Element (Tet) as an example, When order=1, the MFEM basis function is the same as what I need (6 edges vector basis functions).  But when order=3, the hierarchical basis function has 18 edges vec basis, 24 faces vec basis, 3 volmu vec basis. (This includes order=1,2).At this point, I'm not sure if MFEM is also built as a basis function.
  There is also a question, if I program the hierarchical basis function according to the order of mesh nodes in MFEM, do I still need to change the stiffness matrix(CurlCurlIntegrator) and mass matrix(VectorFEMassIntegrator) constructed?

**Comment by tzanio** [comment]
Hi @azmmza, we don't have direct support for hierarchical bases and incorporating these will require additional changes, e.g. when projecting a Coefficient.

That being said, for many applications the basis we have in MFEM is sufficient (and could even be better). Are you sure you need the hierarchical one?
