### ISSUE TITLE
Inf Sup Condition Fluid Dynamics Miniapp 

### ISSUE THREAD

**Issue by JonasBeddrich** [mfem/mfem#3868]
Hello, 

I have a question regarding the fluid dynamics miniapp: 
Doesn't the spatial discretization with PNPN Finite Elements violate the inf-sup condition?  Maybe I missed something, but I'm not sure why this can be ignored here? 

I read through the cited paper of Franco et al. 2020. It confirms that for the Navier-Stokes equation the PNPN FE are used, but does not comment on the inf-sup stability. 

Best wishes, 
Jonas

**Comment by jandrej** [comment]
The PnPn formulation is **not inf-sup stable**, that is correct. However, in practice this doesn't affect the accuracy, speed or viability of the formulation.

**Comment by JonasBeddrich** [comment]
Thank you for the answer. I'm clearly missing some practical experience :sweat_smile:
