### ISSUE TITLE
Quick questions about Remhos mini app

### ISSUE THREAD

**Issue by sungho91** [mfem/mfem#3873]
Hi all,

As far as I understand the concept behind Remhos, this mini app is designed to interpolate an L2 quantity from an old mesh to a new mesh by solving advection. It sounds a degree of similar to the particle tracking method to me.

To accomplish this, we require velocity information, which is essentially the displacement between the old and new meshes, as it manages the fictitious time interval ranging from 0 to 1.

I've been thinking about what happens when the new mesh, generated by TMOP, undergoes significant deformation compared to the old one. 

Examples of Remhos applications, such as Taylor-Green deformation used for mesh motion, demonstrate nearly perfect remapping. This success is attributed to Remhos utilizing time discretization within the interval from 0 to 1 and sub-velocity information for each time step, I think.

However, what if we have a scenario with only constant displacement (velocity) because we don't know the path history between the old and new meshes, is several-time discretization still essential? 
Can we handle significant mesh displacement (velocity) without the need for variable sub-velocity information?

Best,

Sungho

**Comment by vladotomov** [comment]
Hi @sungho91,

The velocity in _`Remhos`_ is always constant (in time). So you're correct, large displacements might be problematic.

**Comment by sungho91** [comment]
Hi @vladotomov,

Thank you for commenting. I was just wondering because I am working on implementing Remhos into my code. 
But it is still great because its theoretical background sounds strong. 

Yes, I'll use Rmehos Github issue page. I just had a bit of concern about not much strong activity of Remhos.
