### ISSUE TITLE
Compatibility with GCC-13.2.0 and OpenMPI-4.1.5

### ISSUE THREAD

**Issue by smjo1021** [mfem/mfem#3876]
Dear MFEM team,

Parallel MFEM was installed with GCC-13.2.0 and OpenMPI-4.1.5 along with Hypre and MeTiS-5. CMake was used to build and install. 

The installation went okay but during the tests, all of the parallel tests get failure (e.g., 95 - performance_ex1p_np=4 (Failed)). I was wondering if the latest version of MFEM is compatible with GCC-13.2.0 and OpenMPI-4.1.5, since I was getting some error in the build of MFEM if I download source tar-ball, instead of cloning the master repository of MFEM. 

* Hypre-2.29.0 was used. MeTiS-5 was taken from https://github.com/mfem/tpls

Any comments will be significantly helpful.

**Comment by v-dobrev** [comment]
Can you run the CMake tests with `ctest --output-on-failure` and post (at least some of) the errors?

**Comment by smjo1021** [comment]
I resolved this issue by following:
- Use Hypre-2.24.0
- Use git clone of MFEM, instead of downloading source tar-ball.
All the tests of MFEM passed with GCC-13.2.0.

Thank you for the support. But I do not understand why source tar-ball gives me the error, unlike the cloning the repo.

**Comment by smjo1021** [comment]
> Can you run the CMake tests with `ctest --output-on-failure` and post (at least some of) the errors?

make was failed with source tar-ball with gcc-13.2.0. So I cannot run "ctest --output-on-failure"
