### ISSUE TITLE
undefined symbol: __libm_feature_flag_x : with Intel & OpenMPI Compiler

### ISSUE THREAD

**Issue by smjo1021** [mfem/mfem#3878]
Dear MFEM team,

I am building MFEM with Intel compiler (oneapi-2023.2.0) with OpenMPI-4.1.5. 
I want to have parallel version of MFEM, so I installed hypre and metis by following the instructions on MFEM documentation.

After I configure MFEM using the dependencies, the installation goes fine without errors.

However, if I "make test", all the tests getting failed with the error message "undefined symbol: __libm_feature_flag_x". 
I have this as my libm:
--> libm: /usr/lib/x86_64-linux-gnu/libm.so /usr/lib/x86_64-linux-gnu/libm.a

A simple and short C++ test code (e.g., hello world) with MPI works okay. 
I have little clue why I have the error "undefined symbol: __libm_feature_flag_x" with MFEM tests. Could someone provide me some insights with this? 

The installation & tests of MFEM went well with GCC dependencies. 
Thank you.

**Comment by tzanio** [comment]
This looks like an issue between the compiler and MPI. Do the hypre examples (i.e. the ones in `hypre/src/examples`) work?
