### ISSUE TITLE
Possible typo in GetBdrElementAdjacentElement2(...)

### ISSUE THREAD

**Issue by Heinrich-BR** [mfem/mfem#3879]
Hi, I've noticed that the `GetBdrElementAdjacentElement2()` function in [mesh.cpp](https://github.com/mfem/mfem/blob/master/mesh/mesh.cpp) returns `Elem1No` as opposed to `Elem2No` of the boundary element in question. 

I imagine this is a typo since at the moment the two functions `GetBdrElementAdjacentElement()` and `GetBdrElementAdjacentElement2()` return exactly the same result (with the exception of the Triangle and Square geometries, where the orientation is reversed, if I understand things correctly.

Now this of course wouldn't be relevant for external boundaries, where the `Elem2No` returned will just be -1, but in cases where one needs to loop over internal boundary attributes and recover the elements on either side, it does become important.

Let me know if indeed this is a typo or if perhaps I've missed something. In case it is a typo, it should be a very quick fix, just changing `Elem1No` to `Elem2No` in the `GetBdrElementAdjacentElement2()` method.

**Comment by pazner** [comment]
Reading the Doxygen comments for those functions, I believe the current behavior is intended (the difference between `GetBdrElementAdjacentElement` and `GetBdrElementAdjacentElement2` is only in the orientation). I would agree that the naming is a bit confusing.

If you have interior faces, you might want to use `Mesh::GetBdrFace` to get the face index, and then `Mesh::GetFaceInformation` to get neighbor information about the face (or e.g. `Mesh::GetFaceElements` to just get the neighboring elements).

**Comment by Heinrich-BR** [comment]
Hi @pazner, thank you for your reply. I think you're right, indeed the Doxygen documentation seems to imply that the difference is only in the orientation. I must say this is a very strange choice of naming convention, especially given it would be useful to have a function that does what I initially thought this one did.

**Comment by v-dobrev** [comment]
I don't have objections to choosing a better name. We can add the new method and deprecate `GetBdrElementAdjacentElement2` for now and remove it later.

**Comment by pazner** [comment]
Sounds like a good plan. How about `GetBdrElementInvertedAdjacentElement`?

**Comment by tzanio** [comment]
I like `InvertedAdjacentElement` 👍

**Comment by v-dobrev** [comment]
I'm not sure `GetBdrElementInvertedAdjacentElement` reflects what the method does -- the "inverted" part is not really about the "adjacent element" as this name suggests.

I think a more precise name is `GetBdrElementAdjacentElementWithInverse{Info,Orientation}` or a bit shorter `GetBdrElementAdjacentElementInv{Info,Ori}`.

**Comment by tzanio** [comment]
Discussion continued in #4034
