### ISSUE TITLE
FormSystemMatrix and ParallelAssemble and reuse of SpMat vs. using parallel data

### ISSUE THREAD

**Issue by juan42** [mfem/mfem#388]
In the sundials examples there are two approaches used. Example ex10p uses ParallelAssemble and then reuses SpMat of the linear operator to compute local matrices and assemble them afterwards in the time dependent jacobian `SparseMatrix *localJ = Add(1.0, M->SpMat(), dt, S->SpMat());`.

In ex16p the hypre matrices Mmat and Kmat are assembled using FormSystemMatrix. In the time dependent jacobian assembly the matrices are used directly to compute M + dt * K.

Is one preferred over the other?

**Comment by Asadanees** [comment]
@juan42 
I think that for matrix assembly and perform BC elimination in ex16p
Used  M->FormSystemMatrix(ess_tdof_list, Mmat). To eliminate boundary condition. 
In example16p compute the Kmat and T matrices at each time step.
I assume that both are different approaches .

**Comment by juan42** [comment]
I was referring to the "reasoning" behind this. Why use one approach vs. the other. Like when building the localJ you also have to deal with local/global distributing to parallel vectors etc.

**Comment by v-dobrev** [comment]
There is no specific reason to prefer one over the other. Maybe some performance analysis can show that one way is slightly faster but I'm not sure. Also, as you mentioned, using the global vectors and matrices approach (as in ex16p) maybe a bit simpler to write.

One difference, which influences what functionality is used in the two approaches, is that ex10p uses a `ParNonlinearForm` to express the nonlinear term, while ex16p treats the non-linearity as a `ParBilinearForm` with a `Coefficient` that depends on the solution. That is why in ex10p, one has to call the `GetLocalGradient` method of `ParNonlinearForm` (one can also use the globally assembled version, `GetGradient`, if the other components that are added to the gradient are also assembled as parallel matrices). In the case of ex16p, we have a `ParBilinearForm`, so we can perform local assembly followed by `FormSystemMatrix` to form a parallel matrix and impose the essential b.c.

**Comment by juan42** [comment]
Thanks again @Asadanees and @v-dobrev.

> There is no specific reason to prefer one over the other. Maybe some performance analysis can show that one way is slightly faster but I'm not sure. Also, as you mentioned, using the global vectors and matrices approach (as in ex16p) maybe a bit simpler to write.

Pretty much what i thought but i needed some justification 👍
