### ISSUE TITLE
Assembling error when using multi processor

### ISSUE THREAD

**Issue by sungho91** [mfem/mfem#3882]
Hi all,

I'm working on implementing one of miniapps, "Remhos", to my code.
So, I called `remapping function (pmesh, x_gf, x_old_gf, e_gf)`, which is remhos, the arguments are the current parallel mesh, its corresponding coordinates, and previous coordinates, and a variable for being mapped. 

On the Remhos side, it makes `ParBilinearForm K_HO` and integrates with `K_HO.AddDomainIntegrator(new ConvectionIntegrator(v_mesh_coeff) `like this way. And then conducting `K_HO.Assemble(0)`.

Now it is really strange. When the remapping function is called for the first time, there is no error. However, at the second time, my code is terminated at the line of `K_HO.Assemble(0)`.

When I ran gdb with my code, I got this message. 

Thread 1 "code" received signal SIGSEGV, Segmentation fault.
0x00005555556f09e9 in mfem::Table::GetRow(int, mfem::Array<int>&) const ().

Also, when I run this with a single processor, there is no error.

Any comments will be helpful to me.

Many thanks.

**Comment by artv3** [comment]
Which assembly type are you using? It feels like the sparse matrix matrix didn't get assembled.

**Comment by sungho91** [comment]
@artv3, Sorry, I don't get the meaning of "assembly type". Can you explain to me what you meant?

I used remap mode (exec_mode == 1) with full assembly and it integrates below the way.

```

GridFunction v_gf(x.FESpace());
VectorGridFunctionCoefficient v_mesh_coeff(&v_gf);
v_gf = 0.0;
add(x, -1.0, x_old, v_gf);  // mesh velocity
K_HO.AddDomainIntegrator(new ConvectionIntegrator(v_mesh_coeff));
auto dgt_i = new DGTraceIntegrator(v_mesh_coeff, -1.0, -0.5);
auto dgt_b = new DGTraceIntegrator(v_mesh_coeff, -1.0, -0.5);
K_HO.AddInteriorFaceIntegrator(new TransposeIntegrator(dgt_i));
K_HO.AddBdrFaceIntegrator(new TransposeIntegrator(dgt_b));
K_HO.KeepNbrBlock(true);
```
`K_HO.Assemble(0);` **the error happned here.** 
`K_HO.Finalize(0);`

**Comment by vladotomov** [comment]
@sungho91 I'd need to see your time loop and how `K_HO` gets updated there.

Note that _`Remhos`_ does the same thing, make sure you follow the setup correctly.

Arturo's question is whether you call any of
`K_HO.SetAssemblyLevel(AssemblyLevel::PARTIAL);`
`K_HO.SetAssemblyLevel(AssemblyLevel::FULL);`

**Comment by sungho91** [comment]
@artv3 , @vladotomov 

I used full assembly but this issue is partially resolved just using partial assembly.
