### ISSUE TITLE
Load rebalancing not possible in ParSubMesh

### ISSUE THREAD

**Issue by Heinrich-BR** [mfem/mfem#3883]
Hello,
I have been working with `ParSubMesh` and stumbled upon a situation: when the domain we pick a `ParSubMesh` from does not have at least one element in every rank of the parent `ParMesh`, we end up with one or several ranks with an empty `ParSubMesh` object, which leads to all kinds of segmentation faults when we try to do anything with it. 

The solution would be to rebalance the load on the ranks by redistributing the submesh equally across ranks. However, the current implementation of `ParSubMesh` seems to only allow for conforming meshes, whereas the `Rebalance()` method is only implemented for nonconforming meshes. Thus, unless there is some method I am unaware of, it seems to be impossible to deal with situations like the one I described above. I was wondering if there is currently a way around this issue (other than dealing only in fully serial meshes), and if not, whether there is any estimate as to when the `Rebalance()` method may be implemented for conforming meshes. Thank you!

**Comment by pazner** [comment]
Not addressing your main point, but everything is generally "supposed to" work with empty mesh partitions. I know that is not currently the case, but if something breaks with an empty partition, it should be considered a bug, and we can try to fix it.

**Comment by Heinrich-BR** [comment]
Hi @pazner, thank you for your response. If you'd like I can open a separate issue so as to keep this one on topic, but I have narrowed down the segmentation faults in empty submeshes to a couple of places in my code:

- When calculating the integration rule order and geometry, I call the `fespace->GetElementTransformation(0)` and `GetFE(0)` methods, which of course segfault since there are no elements to pick. I can work around this by just putting an `if` clause that checks whether this rank has any elements before setting integration rules. This is not such a big issue, but simply for the sake of quality of life maybe these "empty element" methods could return some form of null integration rule without segfaulting just so that users don't need to do rank checks. 

- Perhaps more importantly, my code segfaults when I try to create a `DivergenceFreeProjector` in the empty mesh partition. I admit I haven't yet looked in detail what in the operator is actually causing this, but perhaps you'd like to know this so you can have a look at this potential bug.

**Comment by pazner** [comment]
>
> * When calculating the integration rule order and geometry, I call the `fespace->GetElementTransformation(0)` and `GetFE(0)` methods, which of course segfault since there are no elements to pick. I can work around this by just putting an `if` clause that checks whether this rank has any elements before setting integration rules. This is not such a big issue, but simply for the sake of quality of life maybe these "empty element" methods could return some form of null integration rule without segfaulting just so that users don't need to do rank checks.
>

Yes, I think for now it is better to add the `if` clause. In the long term, I think we want to move away from things like `GetFE(0)`, both because it fails for empty partitions, but also because it will not necessarily be correct for mixed meshes, variable polynomial degrees, etc.

>
> * Perhaps more importantly, my code segfaults when I try to create a `DivergenceFreeProjector` in the empty mesh partition. I admit I haven't yet looked in detail what in the operator is actually causing this, but perhaps you'd like to know this so you can have a look at this potential bug.

It looks like this is caused also by `GetFE(0)`. A fix to this (and related issues) would certainly be welcome.
