### ISSUE TITLE
Quote characters causing link failure

### ISSUE THREAD

**Issue by agcapps** [mfem/mfem#3886]
I built MFEM on Linux with Camp and Umpire.  I built MFEM into Ascent (https://github.com/Alpine-DAV/ascent/), then built Ascent into a large physics simulation code.  I had an error at my final linking step.  The following were included in my link line (lightly edited).  When I turned off Ascent's use of MFEM, the error went away.

`-l"/full/path/to/libcamp.a" -l"/full/path/to/libumpire.a"`

I'm not sure how quotes appeared around library paths, but they broke my build.

**Comment by v-dobrev** [comment]
Can you post the full `cmake` (or `make` if using the GNU make build system) command you use to configure anf build MFEM?

I'm not sure if either of the MFEM build systems (CMake or GNU make) will add the double-quotes you see but I may be wrong. If I have the exact config commands I can try to reproduce the issue and track it down.

**Comment by tzanio** [comment]
ping: @agcapps
