### ISSUE TITLE
MFEM suddenly crashes on cluster (MPI_Barrier problem)

### ISSUE THREAD

**Issue by Maatinski** [mfem/mfem#3888]
Hi all,
I realize this may not be an MFEM problem per se, but I figured I might try to use the expertise of this forum. I've been running MFEM on a cluster we have in our lab, scheduling is done via Slurm. It's been running like a charm for many many months, but all of a sudden, I am not able to run bigger simulations (~15 nodes, 30 processes is what I've been typically doing).
There's two behaviours I am seeing.

**1: The scheduler itself seems to have problems starting the task and throws the following message in the log:**
`/var/slurm/spool/d/job3074653/slurm_script: line 14: module: command not found
[mpiexec@r440-04.nmr.mgh.harvard.edu] HYD_pmcd_pmiserv_proxy_init_cb (pm/pmiserv/pmiserv_cb.c:461): cannot find proxy with ID 4479304
[mpiexec@r440-04.nmr.mgh.harvard.edu] HYDT_dmxu_poll_wait_for_event (tools/demux/demux_poll.c:76): callback returned error status
[mpiexec@r440-04.nmr.mgh.harvard.edu] HYD_pmci_wait_for_completion (pm/pmiserv/pmiserv_pmci.c:160): error waiting for event
[mpiexec@r440-04.nmr.mgh.harvard.edu] main (ui/mpich/mpiexec.c:326): process manager error waiting for completion
`

**2: If the scheduler actually does manage to start, the program crashes as soon as it hits an MPI_Barrier:**
`
Fatal error in PMPI_Barrier: Unknown error class, error stack:
PMPI_Barrier(253)...................: MPI_Barrier(comm=MPI_COMM_WORLD) failed
PMPI_Barrier(239)...................: 
MPIR_Barrier_impl(146)..............: 
MPIR_Barrier_intra_smp(36)..........: 
MPIR_Barrier_impl(146)..............: 
MPIR_Barrier_intra_dissemination(53): Failure during collective
MPIR_Barrier_intra_smp(52)..........: 
MPIR_Bcast_impl(261)................: 
MPIR_Bcast_intra_binomial(178)......: Failure during collective Fatal error in PMPI_Barrier: Unknown error class, error stack:
PMPI_Barrier(253).............: MPI_Barrier(comm=MPI_COMM_WORLD) failed
PMPI_Barrier(239).............: 
MPIR_Barrier_impl(146)........: 
MPIR_Barrier_intra_smp(52)....: 
MPIR_Bcast_impl(261)..........: 
MPIR_Bcast_intra_binomial(178): Failure during collective Fatal error in PMPI_Barrier: Unknown error class, error stack:
PMPI_Barrier(253)...................: MPI_Barrier(comm=MPI_COMM_WORLD) failed
PMPI_Barrier(239)...................: 
MPIR_Barrier_impl(146)..............: 
MPIR_Barrier_intra_smp(36)..........: 
MPIR_Barrier_impl(146)..............: 
MPIR_Barrier_intra_dissemination(43): 
MPID_nem_tcp_connpoll(1795).........: Communication error with rank 9: No route to host
MPIR_Barrier_intra_dissemination(43): 
MPIDI_CH3U_Recvq_FDU_or_AEP(608)....: Communication error with rank 9
MPIR_Barrier_intra_smp(52)..........:
` 

Am I missing something obvious here? I recompiled with the latest version of MFEM (and hypre-2.25.0 and METIS-5.1.0). Again, I know this might not be MFEM specific but but maybe someone has an idea...

As always, big thanks!
Mathias

**Comment by v-dobrev** [comment]
If you are trying to run bigger simulations, maybe you are hitting the 2 billion global unknowns barrier. Have you tried building hypre with `--enable-mixedint` (or `--enable-bigint`)? This should let you run bigger problems.
