### ISSUE TITLE
Does Visit Data Collection Load do the right thing in parallel

### ISSUE THREAD

**Issue by vikramsg** [mfem/mfem#389]
I am trying to load a data file generated by MFEM in parallel. When I try to use the Load present in Data Collection, it seems to load only the data file from the first processor. I do it in the following manner

```
VisItDataCollection dc("CNS");
int cycle = 48400;
dc.Load(cycle);
ParGridFunction *u = dc.GetParField("u");
```

But when I try 

```
cout << u->Size() << endl;
```

it gives me the same size on all processors which is the size of the first process output.

**Comment by mlstowell** [comment]
Hi, @vikramsg,

The DataCollection objects only operate in parallel if they are given a ParMesh object either during construction or with the SetMesh method.  The comment for the VisitDataCollection constructor does say that using Load in this way will not work in parallel.

That being said, what you are attempting seems quite natural to me.  The trouble is that in this case the VisitDataCollection object does not have the MPI communicator so it knows nothing about which rank it is running on or how many ranks there are, etc..  I imagine we could fix this if we provided additional DataCollection and VisitDataCollection constructors which also took the MPI communicator.

Bests Wises,
Mark

**Comment by vikramsg** [comment]
Yes it seems to work now if I make the following change. But does this qualify as a bug or should I just close it.

```
+VisItDataCollection dc("CNS", pmesh);
-VisItDataCollection dc("CNS");
int cycle = 48400;
dc.Load(cycle);
ParGridFunction *u = dc.GetParField("u");
```

**Comment by mlstowell** [comment]
It was documented so let's call it a "limitation" rather than a "bug".

If @aaroncblack and @acfisher, who know these classes much better than I do, don't object I can put together a small pull request to add new constructors with an MPI_Comm argument.  There may be good reasons why such constructors don't exist so I'd be interested to get their input.

Let's keep the issue open, at least until we hear from them.

**Comment by v-dobrev** [comment]
Note that `VisitDataCollection`, as implemented right now, reads the mesh as independent serial meshes on each MPI rank. An alternative to making a new constructor is to add new method (in the base class `DataCollecton`) called `SetMPI_Comm(MPI_Comm)` or something like that. We will need the `MPI_Comm` (not just the rank) later if we want to update `VisitDataCollection` to read a `ParMesh` - there is a switch (set with `SetFormat`) that controls how a parallel mesh is saved and loaded. Saving using the parallel format should work right now. Loading it in a `VisitDataCollection` is not implemented but it should be very easy to add.

**Comment by acfisher** [comment]
The code in there is pretty simple and I can't think of a reason not to add an MPI_Comm.  Feel free to throw me on the review for the pull request.

**Comment by kennyweiss** [comment]
The ``SidreDataCollection`` (which is also derived from ``DataCollection``) has a ``SetComm`` function to allow loading into mfem.  
https://github.com/mfem/mfem/blob/189eb7229beefee522f32f9ef3de6de1a30b08e1/fem/sidredatacollection.hpp#L199-L204

It seems reasonable to make this a virtual function of the ``DataCollection`` base class.

**Comment by cyrush** [comment]
I pondered this a bit while working on the conduit support -- it would be great if the DataCollection base class provided a way to get the mpi comm w/o having to do dynamic casts  to obtain it from an existing ParMesh object.

**Comment by tzanio** [comment]
@vikramsg: does the merge of #395 in `master` address your needs?

**Comment by vikramsg** [comment]
Hi @tzanio. Sorry I have not looked at it but just used the @mlstowell suggested workaround. I will close this issue and maybe have a look at it.
