### ISSUE TITLE
Bug in HypreParMatrixFromBlocks 

### ISSUE THREAD

**Issue by chikitkin** [mfem/mfem#3893]
Dear MFEM community, 

I faced with the following limitation: `HypreParMatrixFromBlocks ` is not applicable when all blocks on some MPI rank are empty. 

```
Verification failed: (nrows > 0 && ncols > 0) is false:
 --> Invalid block in HypreParMatrixFromBlocks
 ... in function: mfem::HypreParMatrix* mfem::HypreParMatrixFromBlocks(mfem::Array2D<mfem::HypreParMatrix*>&, mfem::Array2D<double>*)
```

I think that it's a quite natural situation, since for small mesh and big number of MPI ranks mesh partition produces empty submeshes and consequently empty matrices for Bilinear forms, for instance.
Could you, please, recommend some workaround for this case?
Is it possible to extend `HypreParMatrixFromBlocks ` to this case, or this limitation is critical? I hope that I am able to implement such a modification myself, but I need some hints about how non-empty condition is used in the current implementation.

Thank you in advance!

**Comment by sebastiangrimberg** [comment]
Hi @chikitkin, what version of MFEM are you using? https://github.com/mfem/mfem/pull/3699 should have resolved this exact issue I believe.

**Comment by chikitkin** [comment]
Thanks! I am using 4.3, I shall update to the newest version!

**Comment by chikitkin** [comment]
Sorry)

**Comment by chikitkin** [comment]
I prepared an example to reproduce this error. It occurs even for non-empty blocks. 
[reproduce_bug.zip](https://github.com/mfem/mfem/files/12746656/reproduce_bug.zip)
The mesh is very simple:

**Comment by thartland** [comment]
After removing the `make_unique<>` calls, which is not available in C++11, I was able to run `reproduce_hypre_from_blocks_bug.cpp` with no issue on 1, 2 and 4 MPI processes. If the issue is with hypre then perhaps updating your hypre could help.

**Comment by chikitkin** [comment]
Thanks, @thartland , I' check it once again. Which HYPRE version did you use?

**Comment by thartland** [comment]
Version 2.29.0
