### ISSUE TITLE
Using "iterative_mode" on solvers in ex16p results in memory corruption.

### ISSUE THREAD

**Issue by juan42** [mfem/mfem#390]
I played around with ex16p today and recognized that when you enable iterative_mode you get weird memory corruptions in the ImplicitSolve() call from the ode solver. The initial condition taken from du_dt in
```
ImplicitSolve(const double dt, const Vector &u, Vector &du_dt)
```
contains NaN if you are lucky. I even found pointers to a VisItDataCollection in there on a debug run.

I remember we talked about the functionality of iterative mode some time ago but this is pretty confusing.

**Reproduce**
1. Delete the line 365 in ex16p.
2. GDB with gdb --args ./ex16p -s 1 (backward euler)
3. break at ex16p.cpp:391
4. print the content of du_dt

You could also use valgrind and see the error message blow up.

**Comment by v-dobrev** [comment]
This is not a bug, setting iterative_mode to false is essential part of the algorithm.

**Comment by juan42** [comment]
So this means the solvers assume i have either set this value to an initial guess or manually set it to zero (which iterative_mode = false basically does).

Sorry, I guess this is a misunderstanding from my side. Whats the reasoning behind this?

**Comment by v-dobrev** [comment]
The reason for having the iterative_mode? It gives you more flexibility: if you are using an iterative solver directly in your code and have an initial guess that is better than the zero vector - you can give that to the solver Mult method by initializing the output vector with it. The output vector, in this case, works as input (for the initial guess) as well. On the other hand if you are using the iterative solver inside another solver, e.g. as the Jacobian solver inside Newton iteration, you do not have a way of controlling the initial guess (at least not in the general implementation provided by MFEM), so you must use non-iterative mode.

**Comment by juan42** [comment]
So it would be reasonable to use and set the last solution as initial guess manually (in the time stepping solver) and leave iterative_mode on default (true)?

**Comment by v-dobrev** [comment]
The ode solver method (ImplicitSolve) solves for an increment relative to the previous time state, so starting with zero vector is the best you can do, usually. If you have a guess for the new time state which is better than just the old state, then you can subtract them and use that as initial guess for ImplicitSolve. This will work for backward Euler. For multistage SDIRK methods, setting a better initial guess for ImplicitSolve has to take into account the RK stage as well.

**Comment by juan42** [comment]
Ah now i got the idea!

Thanks for the detailed explanation.

**Comment by v-dobrev** [comment]
You are welcome!
