### ISSUE TITLE
Compiling issue of remhos using the latest mfem

### ISSUE THREAD

**Issue by sungho91** [mfem/mfem#3905]
Hi all,

I found the Remhos seem not to be built with the latest mfem.

Best,

Sungho
![Screenshot from 2023-09-30 09-35-04](https://github.com/mfem/mfem/assets/40257026/af785576-8cb5-4252-bdbb-1331230ad6c9)

**Comment by v-dobrev** [comment]
Thanks for letting us know. This is probably due to #3722 and will need to be addressed in Remhos, I think.

**Comment by v-dobrev** [comment]
@sungho91, see https://github.com/CEED/Remhos/pull/44 for a fix.
