### ISSUE TITLE
MacPorts and FreeBSD pkg

### ISSUE THREAD

**Issue by tenomoto** [mfem/mfem#3906]
Thank you for making MFEM portable across platforms. I noticed that MacPorts has MFEM 4.5.2 and FreeBSD pkg has 4.4.

**Comment by tzanio** [comment]
Thanks for your help with these, @barracuda156 and @yurivict!

**Comment by barracuda156** [comment]
UPD. `MFEM` 4.6 fails for me on the following: https://github.com/mfem/mfem/issues/3931

**Comment by tzanio** [comment]
Thank you, @barracuda156 !

**Comment by tzanio** [comment]
Hi @yurivict, can we discuss what it will take to update the FreeBSD package to 4.6?

If there are a technical issues, we can maybe have a short telecon to clear them out?

**Comment by barracuda156** [comment]
Bump for FreeBSD support, otherwise bot gonna close the issue.
