### ISSUE TITLE
TransferMap::Transfer does not seem to work across multi-generation submeshes

### ISSUE THREAD

**Issue by Heinrich-BR** [mfem/mfem#3911]
Hi,

I've been experimenting with the `SubMesh` feature, in particular creating several generations of submeshes. For instance, suppose we have a "grandparent" mesh, from which we extract a "parent" submesh, from which we extract a "child" submesh. You can certainly create this 3-generation chain. However, it seems that the `Transfer` function for `GridFunction`s between the child and parent submeshes do not work. It does work from the parent to the grandparent, presumably because then we have one `Mesh` object and one `SubMesh`, as opposed to two `SubMesh`es. As an example, consider the following:

```
    Mesh grandparent_mesh(filename, 1, 1);
    Array<int> doms_array;
    doms_array.Append(1);
    doms_array.Append(2);
    SubMesh parent_submesh = mfem::SubMesh::CreateFromDomain(grandparent_mesh,doms_array);

    H1_FECollection H1_Col_parent(order, parent_submesh.Dimension());
    FiniteElementSpace H1FES_parent(&parent_submesh, &H1_Col_parent);
    GridFunction F_parent(&H1FES_parent);
    F_parent = 0.0.;

    Array<int> doms_array_2;
    doms_array_2.Append(1);
    SubMesh child_submesh = SubMesh::CreateFromDomain(parent_submesh,doms_array_2);

    H1_FECollection H1_Col_child(order, child_submesh.Dimension());
    FiniteElementSpace H1FES_child(&child_submesh, &H1_Col_child);
    GridFunction F_child(&H1FES_child);
    F_child = 1.0;
    
    child_submesh.Transfer(F_child, F_parent);
    VisItDataCollection VDC("test_generations", &parent_submesh);
    VDC.RegisterField("F", &F_parent);
    VDC.Save();
```

In theory, the value of 1 everywhere should be transferred from the child submesh to the parent submesh (potentially to be transferred to the grandparent later), however the result of this code on the parent submesh is to just have zero everywhere, i.e. no data was transferred at all.

I believe it would be useful to create a transfer map even when we are extracting a `SubMesh` from something that is already a `SubMesh`. Let me know if perhaps I've missed something.

**Comment by psocratis** [comment]
Hi @Heinrich-BR 

It seems that the above works fine for me (and it should). 
Here is an example with `child GridFunction = 2`, `parent GridFunction = 1` and `grandparent GridFunction = 0` and then transfering from the child to the parent and then to the grandparent. 

<img width="1203" alt="image" src="https://github.com/mfem/mfem/assets/14336752/2921fc74-cb08-4b7d-83e7-a9e9c976f0b1">

**Comment by Heinrich-BR** [comment]
Hi @psocratis, thank you for your response!

This is quite strange, but clearly I'm doing something wrong on my side. I'll investigate this further and let you know if I still can't make it work.
