### ISSUE TITLE
Advection of L2 space variables in a nonconforming mesh

### ISSUE THREAD

**Issue by sungho91** [mfem/mfem#3913]
Hi all,

I'm incorporating Remhos into my code to remap the L2 fields after remeshing. 
I believe the remapping is functioning correctly with the conforming mesh, but I'm encountering some issues with a non-conforming mesh. 

In the case of a conforming mesh, the mesh simply moves, and the field does not move because they are advected together. However, with a non-conforming mesh, the shape of the field is altered, leading to incorrect mapping (see attached image). 

![text2-1](https://github.com/CEED/Remhos/assets/40257026/3d22c631-3f75-483e-945e-56bd366e0d9f)

This is obvious when I use the example of Remhos.
I typed `mpirun -np 8 remhos -m ./data/cube01_hex.mesh -p 10 -rs 1 -o 2 -dt 0.02 -tf 0.8 -ho 1 -lo 4 -fct 2` but I modified element attributes of 1st and 2nd element to two and Remhos like this way. You can see non-conforming mesh and final remapped field is highly distorted. I think advection is prohibited between coarse- and fine-mesh regions.  

```
mesh->EnsureNCMesh(true);
Array<int> refs;

for (int i = 0; i < mesh->GetNE(); i++)
{
if(mesh->GetAttribute(i) >= 2)
{
refs.Append(i);
}
}

mesh->GeneralRefinement(refs, 1);
refs.DeleteAll();
mesh->Finalize(true);
```

![image1-1](https://github.com/CEED/Remhos/assets/40257026/89f3d7eb-c21d-4fc4-a20a-f80aad8e22e0)

Any comments would be greatly appreciated. 

Sungho

**Comment by vladotomov** [comment]
Lets keep the discussion in the [_`Remhos`_ issue](https://github.com/CEED/Remhos/issues/46)
