### ISSUE TITLE
Parallel performance

### ISSUE THREAD

**Issue by ryanblack129** [mfem/mfem#3916]
Hello,

I am running into some performance issues with my application code (simple implicit displacement based nonlinear solid mechanics solver) for my phd thesis research. I am not sure if I have setup the parallel version of some of the data structures correctly or using communication properly. I built my application following as best I could the parallel example problems. Running a quick strong scaling test shows very little speedup (very small problem with ~1024 elements)

<img width="659" alt="image" src="https://github.com/mfem/mfem/assets/56736259/59132244-236f-46fe-8380-09c243ae67b8">

Below are some snapshots of how I setup the parallelization:
I initially setup MPI and Hypre:
```
Mpi::Init(argc, argv);
int num_procs = Mpi::WorldSize();
int myid = Mpi::WorldRank();
Hypre::Init();
```

Setup the parallel mesh
```
ParMesh *pmesh = new ParMesh(MPI_COMM_WORLD, *mesh);
```

Setup parallel mass matrix for example
```
Md_form = new ParBilinearForm(dfes);
Md_form->AddDomainIntegrator(new VectorMassIntegrator(*rho_s_0));
Md_form->Assemble();
Md_form->Finalize();
Mmat = Md_form->ParallelAssemble();
Full_Mmat = new HypreParMatrix(*Mmat); // store full M matrix, non-eliminated
// eliminate essential tdofs from Mmat, i.e. zero out row and col and put 1 on diag
Mmat_e = Md_form->ParallelEliminateTDofs(disp_ess_tdof_list,*Mmat);
```

Interface with GMRES and HypreBoomerAMG
```
amg = new HypreBoomerAMG();
amg->SetElasticityOptions(dfes);
lin_solve = new GMRESSolver(dfes->GetComm());
lin_solve->iterative_mode = false;   
lin_solve->SetAbsTol(lin_atol);
lin_solve->SetRelTol(lin_rtol);
lin_solve->SetMaxIter(lin_maxIt);
lin_solve->SetPrintLevel(lin_pl);
lin_solve->SetPreconditioner(*amg);
```

Clearly there are other things I am doing incorrectly from an efficiency point of view in my application code. Also, I’ve noticed that other application codes built using MFEM use Partial-Assembly. Is there something I can follow to utilize this feature with my custom integrators?

Any help with this would be greatly appreciated, I am new to parallelization and not sure how to begin looking into this. Are there any tools that can be used to identify slow parts of my application code or incorrect use of MFEM data structures? 

Thanks for the help,
Ryan

**Comment by jandrej** [comment]
For strong scaling you should start with your desired maximum problem size. I'll give a crude description of what you should do.

1. Refine your problem so that it fits 1 or 2 nodes. If you deal with a real world application this might need more "minimum" nodes.
2. time the initial rank test
3. refine, rerun, time
4. stop when you see stagnation

If you reach 4. and have <30k-50k dofs per rank you assume you've reached communication overhead. These statements might not be correct for every situation (I don't know your systems architecture etc) but it gives you a good starting point.

**Comment by ryanblack129** [comment]
Hi @jandrej,

Thanks for the reply. I will setup a test like that.

Also, do you have any advice on how to identify slow parts of my application code? I am seeing almost 1-2 orders of magnitude slower than expected.

Thanks,
Ryan

**Comment by jandrej** [comment]
For timing purposes I'd recommend Caliper. 

> I am seeing almost 1-2 orders of magnitude slower than expected.
Compared to what?

**Comment by ryanblack129** [comment]
Thanks, I will look into Caliper.

I've been comparing with the code svFSI from Simvascular.

Thanks,
Ryan

**Comment by ryanblack129** [comment]
Thanks so much, I will update my testing.

Best,
Ryan
