### ISSUE TITLE
Lot's of memory copying Issues running hooke elasticity on GPU w/ Hypre compiled with GPU

### ISSUE THREAD

**Issue by jtristano** [mfem/mfem#3921]
Hello,
I'm running a modified hooke on the gpu with both hypre and mfem built with cuda (Hyper config --with-cuda , mfem built with pcuda).   I see from nvidia nsys that almost 70% of the time is spent in memory shuffling to and from the device in the integrator and my restriction and prolongation operators that go from T->L, L->E, kernel, E->L, L->T

Is there a way to keep this memory on the device?  Are there compiler options that need to be set or some special build flags?  A significant amount of gpu starvation occurs because of the shuffling.   If you need more information from nsys, please let me know

Thanks
Joe

**Comment by joetristano** [comment]
By the way, this is all low order conformal hexahedron in a Cartesian grid

**Comment by jtristano** [comment]
We found our issue!
