### ISSUE TITLE
An issue of solving anisotropic linear elasticity equations

### ISSUE THREAD

**Issue by zhaog6** [mfem/mfem#3923]
Dear MFEM team,

I want to solve linear elasticity equations describing the deformation displacement of anisotropic material, but I found MFEM does not support `ElasticityIntegrator` with `MatrixConstantCoefficient`. What ways are available to solve this problem? Thanks.

**Comment by v-dobrev** [comment]
Hi @zhaog6, sorry for the late reply. You will probably need to implement your own custom anisotropic elasticity integrator. Use `ElasticityIntegrator` as a starting point and let us know if you have questions.

**Comment by zhaog6** [comment]
Dear @v-dobrev , the issue has been resolved and the numerical result meets expectation, thank you.
