### ISSUE TITLE
[Bug] NC Tet number of true dofs varies with partition

### ISSUE THREAD

**Issue by hughcars** [mfem/mfem#3925]
Nonconformal tets fail to account for edge-face constraints introduced by an NC refinement, onto conformal edges. The effect of this is that for some partitionings it is possible to have a global system with a greater number of true dofs than in serial, as the constraint fails to be accounted for. This was uncovered during adaptation and rebalancing during testing of https://github.com/mfem/mfem/pull/3611 and https://github.com/mfem/mfem/pull/3746 but occurs for p1 ND spaces, and p2 H1 spaces (any space with edge dofs). This effect can also be reproduced with a single tet, two processors and a particular partitioning. Such local arrangements can occur in the wild for adapted meshes with many processors.

<img width="723" alt="Screenshot 2023-09-28 at 11 31 26 AM" src="https://github.com/mfem/mfem/assets/114775781/21b9f906-6be8-4696-8fcd-1c118a45dc7c">
<img width="723" alt="Screenshot 2023-09-28 at 11 31 19 AM" src="https://github.com/mfem/mfem/assets/114775781/e4c66204-3354-45c7-82f7-5c8153af4551">

I have a reproducing test and fix in https://github.com/mfem/mfem/pull/3926

**Comment by v-dobrev** [comment]
This is some great investigative work! Thanks for debugging and fixing the issue!

**Comment by tzanio** [comment]
Discussion continued in #3926
