### ISSUE TITLE
Excessive Memory Usage as # Procs Increase Seemingly from `Array<T>::GrowSize`

### ISSUE THREAD

**Issue by j-signorelli** [mfem/mfem#3927]
Hi,

I recognized a potential memory usage issue with what seems to be rooted in `Array<T>::GrowSize`. For a problem with only 1111 nodal DOFs, I attempted to load this using a saved `VisItDataCollection` by `VisItDataCollection::Load` and observed that over 60GB of RAM was being used when running on only 14 processors (excessive # procs for just 1111 nodes but was to test). When running on only 1 processor, this issue did not occur at all. The issue seems to grow worse as number of MPI processors used increases. According to Valgrind, I have no memory leaks in my code but observed the following peak when profiling the heap with massif: (Note that below is a massif.out.* file from only ONE of the fourteen procs I ran with (Command: `mpirun -np 14 valgrind --tool=massif ./test`)

![Screenshot from 2023-10-11 16-18-50](https://github.com/mfem/mfem/assets/116454159/e29a78ab-88f9-446c-b647-6fbc79550c17)

Also wanted to mention: there are only 3 specified bdr_attributes in the mesh. I have noticed by experience as well that the time it takes to load in a VisItDataCollection does seem to grow significantly with number of processors, even if # DOFs remains fixed.

**Comment by pazner** [comment]
Are you using the same number of MPI ranks to write and read the data collection? It could also be useful to upload a representative data collection file (e.g. the one with 1111 DOFs) and some code to reproduce.

**Comment by j-signorelli** [comment]
Hi @pazner , yes same number of MPI ranks to write and read. I updated ex0p.cpp and have reproduced this issue with the attached mesh file.
[CMakeLists.txt](https://github.com/mfem/mfem/files/12874957/CMakeLists.txt)
[ex0p_updated.cpp.txt](https://github.com/mfem/mfem/files/12874958/ex0p_updated.cpp.txt)
[bar.mesh.txt](https://github.com/mfem/mfem/files/12874959/bar.mesh.txt)

**Comment by pazner** [comment]
The issue with your mesh is the use of 2147483647 as an element attribute number. In MFEM, there are arrays whose lengths scale with the maximum value of all attributes. This attribute number in your mesh probably comes from the Pointwise converter, see #3687.

Changing your mesh file so that this attribute is smaller (e.g. `sed 's/2147483647/1/g' bar.mesh > bar_fixed.mesh`) should fix the problem.

**Comment by j-signorelli** [comment]
This was it, thank you so much!
