### ISSUE TITLE
Use of BlockVector in  ODE solver for solving system of equations  might be make problem to get right result of absolute error ((like in Joule Solver miniapp and ex10)

### ISSUE THREAD

**Issue by Asadanees** [mfem/mfem#393]
Dear @tzanio ,  @v-dobrev, @mlstowell , @acfisher  and @Dan2997925 
I have tested and played ODE solver for Joule (miniapp) and quick review ex10 .  Then I used `BlockVector::EB` in member functions `ImplictSolve` and `ODESlver::Step`  to solve the first order couple of maxwell equations (same as used in Joule solver miniapp and ex10). The result of absolute error is no right  when exact solution is known.  But the simulation result is very nice. I shall have to validate code and this will be a Benchmark problem in miniapp for linear and nonlinear case
All of you are  good experienced scientists and know better than me.  But according to my small experienced and tested in mfem, that  the use of BlockVector  in member function 
`TimeDependentOperator::ImplictSolve` and  `ODESolver::Step` might be causes of error.  Because `ODE::Solver` did not solve rightly when we are in using BlockVector in  `Step::(Vector BlockVector, double t, double dt)` and `ImplicitSover::(double t, const Vector &BlcokVector, Vector &K).` if I understood right.
The reasons is that `ImplicitSolve` did not solve the approximate  block vector solutions  rightly. This is logical error. I used `BackwardEuler` and `ImplicitMidPoint` Solver to conclude. ex10 is nonlinear and we could not see this  logcal error easily. 
1. epsilon dE/dt   = Curl 1/mu B  - J  
2.   dB/dt    = - Curl E  
In the absolute error C must be independent of t. When step size is half then absolute error must be half.  You can find the absolute error below.     
- `double err_e  = E.ComputeL2Error(electric_coeff, irs);`
- `double err_b  = B.ComputeL2Error(magnetic_coeff, irs);`  
- ` || E_h - E_ex ||  =err_e =  C * t`
- `|| B_h - B_ex ||  = err_b = C * t`
I propose that to eliminate this error.  we solve first equation for E using ODE solver independently and, than use approximate value of E to solve the second equation for B. Then approximate solution of B to solve first equation for E and so on up to final time step.
 Is this right approach?   
**Either ,we have to develop solver for system of ODE to solve the  system of equations. or use different techniques**

>**I want to fix this issues if it is pointed out rightly. Could you please tell me? Have some expertise with ODESolver in LLNL team? Who will help me to review my code and give suggestions**> .
Please free to ask if you have any questions.

  
Thanks 
asad aneed

**Comment by mlstowell** [comment]
Hi, @Asadanees,

I'm afraid I don't understand the issue.  Are you suggesting there may be a problem with how we use BlockVector in the Joule mini-app?  This mini-app certainly uses the TimeDependentOperator in an unconventional manner so we could have overlooked something.  Or is the problem in example 10 or perhaps in a coupled first order Maxwell solver that you mentioned?

If you suspect there is an issue with one of our codes we would be eager to find and fix it.  Any information you could provide to help us isolate the symptoms would be helpful.  For example which code exhibits the problem?  Are there specific command line options we need to reproduce the problem, etc.?

Thanks,
Mark

**Comment by tzanio** [comment]
Hi @Asadanees, we are pretty sure that Joule and Example 10 are correct so I will close this issue for now. If you are confident that you have found an error, as Mark suggested, please don't hesitate to re-open it.

**Comment by Asadanees** [comment]
Hi @tzanio,
Thanks. Could you please open the issue.
anees

**Comment by Asadanees** [comment]
Hi @mlstowell ,
Thanks for your answer. 
>  First part: Validation of result is a problem

When I used the `BlockVector` aprroches in the member function `Mult`  and `ImplicitSolve` that 
were used in ex10 and Joule solver. Than I am not succeeded to validate the result. The absolute errors are not second order both in space and time for electric field and magnetic flux,  when I was using  `ODESolver::BackwardEulerSolver.` I also tested the code for other `ODESolver` but the situation is more  worse both in space and time.  Then I again studied all the classes `Operator`, `TimeDependentOperator` and `ODESolver`.  Then I found that the problems are using  `BlockVector`  in `Mult` and `ImplicitSolve` member functions  for solving the first order Maxwell equations or any system of equations.  The explicit and Implicit methods in `ODESolver` have member functions `Mult(const Vector &xv, Vector &y) const `and `ImplicitSolve(double dt, const Vector & vx, Vector &dvx_dt)` respectively.  Because  `ODESolver` updated the complete `BlockVector` at each time step instead of solving the first equations for Electric field, then solve second equation for Magnetic Flux using  above calculated of Electric Field and so.
After that tested the `ImplicitSolve` in different approaches using `BlockVector` to confirm the understanding of this problems.  
Then I wrote the ImplicitSolve in different way. I know that the below `ImplicitSolve` solve the first equation for Electric Field rightly. But no solve  second equation for Magnetic Field rightly.
Below is the behavior of absolute error. 
void Maxwell::ImplicitSolve(const double dt, const Vector &EH,  Vector &dEH_t ) 
{

		dEH_t=0.0;

		int Vsize_nd= Nedelec.GetTrueVSize();


		int Vsize_rt= Raviart.GetTrueVSize();	
		
		Array<int> block_offsets(3);
        
        block_offsets[0] = 0;
        
        block_offsets[1] = block_offsets[0]+Vsize_nd;
		
		block_offsets[2] = block_offsets[1]+Vsize_rt;
         
        Vector* ehptr  = (Vector*) &EH;
          
        GridFunction E, H;
          
        E.MakeRef(&Nedelec,   *ehptr,block_offsets[0]);
           
		H.MakeRef(&Raviart, *ehptr,block_offsets[1]);
		   
		GridFunction dE, dH;
		   
		dE.MakeRef(&Nedelec, dEH_t, block_offsets[0]);
		   
		dH.MakeRef(&Raviart, dEH_t, block_offsets[1]);
   
        // Current density 
        
        VectorFunctionCoefficient J(3, Electric_Current);
        
		Current_density=new LinearForm(&Nedelec);
   
		Current_density->AddDomainIntegrator(new VectorFEDomainLFIntegrator(J));
   
		Current_density->Assemble();
		
		
		*Current_density*=-1;
		
		VectorFunctionCoefficient electric_exact(3, ElectricField);
        E.ProjectCoefficient(electric_exact);
		

		
		Conduct->AddMult(E, *Current_density, -1.0);
		
	  
		MB->AddMultTranspose(H, *Current_density, 1);
		
		
   
		 if(N_Solver==NULL)
		 {
		 
		
		 
		 N_Solver= new CGSolver ;
		 
		 N_Solver->iterative_mode = false;
	
		 N_Solver->SetRelTol(Rel_toL);
	
		 N_Solver->SetAbsTol(Abs_toL);
	
		 N_Solver->SetMaxIter(Max_Iter);
	
		 N_Solver->SetPrintLevel(0);
	
		 N_Solver->SetPreconditioner(Nmat_prec);
		 
		 N_Solver->SetOperator(N->SpMat());
		
		}
		N_Solver->Mult(*Current_density, dE);
		//dE=0.0;
		GridFunction h_gf(&Raviart);
		VectorFunctionCoefficient magnetic_exact(3, MagneticField);
  
		//h_gf=0.0;
		MB->Mult(E, h_gf);
		//h_gf*=-1;
		if(R_Solver==NULL)
		{
		
		cout<<"in R_Solver"<<endl;
		
		R_Solver= new CGSolver;
			  
		R_Solver->iterative_mode = false;
	
		R_Solver->SetRelTol(Rel_toL);
	
		R_Solver->SetAbsTol(Abs_toL);
	
		R_Solver->SetMaxIter(Max_Iter);
	
		R_Solver->SetPrintLevel(0);
	
		R_Solver->SetPreconditioner(Rmat_prec);
	
		 R_Solver->SetOperator(R->SpMat()); 
		
		   
		}
		R_Solver->Mult(h_gf, dH);
		dH*=-1.0;
		
		
	}

> Absolute error result for the above ImplicitSolve

Absolute error of electric Field is second order in time, but in space, when refinement level is increase, the error is increase for the electric fields. 
Absolute errors are constant  both in space and time for magnetic field.

> I tested for the `ImplicitSolve` for second approach.
Here `ImplictSolve` solve the both equation similar to Joule and ex10.
But the absolute error is strange for both electric and Magnetic fields.
You could find the result of absolute error below the ImplicitSolve.

void Maxwell::ImplicitSolve(const double dt, const Vector &EB,  Vector &dEB_t ) 

{
	if(Nspmat1==NULL || fabs(dt-dt_A) > 1.0e-12*dt) 

	{
		cout<<"in the implicit solve"<<endl;
		cout<<"gettime="<<dt<<endl;
		this->buildN1(permittivity, 0.666667, dt);
	}

		dEB_t=0.0;

		int Vsize_nd= Nedelec.GetTrueVSize();


		int Vsize_rt= Raviart.GetTrueVSize();	
		
		Array<int> block_offsets(3);
        
        block_offsets[0] = 0;
        
        block_offsets[1] = block_offsets[0]+Vsize_nd;
		
		block_offsets[2] = block_offsets[1]+Vsize_rt;
         
        Vector* ehptr  = (Vector*) &EB;
          
        GridFunction E, B;
          
        E.MakeRef(&Nedelec,   *ehptr,block_offsets[0]);
           
		B.MakeRef(&Raviart, *ehptr,block_offsets[1]);
	
		   
		GridFunction dE, dB;
		   
		dE.MakeRef(&Nedelec, dEB_t, block_offsets[0]);
		   
		dB.MakeRef(&Raviart, dEB_t, block_offsets[1]);
		
		// solve the first equations 
		weakCurl->MultTranspose(B, *E_right);
		
		*E_right+=*Current_Density;
		 if(N_Solver==NULL)
		 {	 
		 N_Solver= new CGSolver ;
		 
		 N_Solver->iterative_mode = false;
	
		 N_Solver->SetRelTol(Rel_toL);
	
		 N_Solver->SetAbsTol(Abs_toL);
	
		 N_Solver->SetMaxIter(Max_Iter);
	
		 N_Solver->SetPrintLevel(0);
	
		 N_Solver->SetPreconditioner(Nmat_prec);
		 
		 N_Solver->SetOperator(*Nspmat1);
		
		}
		N_Solver->Mult(*E_right, dE);
		// Here I find the value of E_right 
		// than use E_ringt to solve the second equation dB/dt = - curl E
		*E_right=dE;
		curl->Mult(*E_right, dB);
		dB*=-1.0;
} 
For the above `ImplicitSolve ` 

> The absolute error for electric field and magnetic field are constants for both in space and time.
Moreover I used another approached for `ImplicitSolve`.

Moreover I have gotten the absolute error constant for Electric Field both in space and time.
Absolute error is  fourth order for magnetic Flux in time for the backward Euler solver, But in space absolute error is increase when refinement level is increase. I used more than five different approached to write a issue.
I got the same result when I used the approach like ex10.
Vector E(EH.GetData() +  0,B_Size);
   Vector H(EH.GetData() + E_Size, B_Size);
   Vector DE_dt(DEB_dt.GetData() +  0, E_Size,);
   Vector dB_dt(DEB_dt.GetData() +E_Size,, B_Size);

https://github.com/mfem/mfem/blob/155a5eb684b116c92cf2106daeb8c3ad7d8beb27/miniapps/electromagnetics/joule_solver.cpp#L401-L553 



>  `BlockVector` uses in `Mult` and `ImplicitSolve`. This is a logical error.  

I found the reasons that I could not validate the result both in space and time, due to BlockVector used in ImplicitSolve.  
This is a only reason that result are not validated both in space and time.  This solver is not perform well for system of equations using BlockVector. 
Could You please tell me? Have you validated the result using `BlockVector` similar method ex10 and joule both in space and time for linear case? 
The solution of problem is either develop a solver for BlockVector or solve the system of equations independently. 
I wholeheartedly appreciate everything you’ve done for me. 
Feel free to contact, if you have any questions.
Best wishes.
Thanks 
anees

**Comment by tzanio** [comment]
Hi @Asadanees, I'd like to help, but I'm not sure I really understand the question... 

@mlstowell and @Dan2997925 do you have any input?

**Comment by Asadanees** [comment]
Hi @tzanio ,
# Could not Validate the  result when using BockVector in `ODESolver`  to solve First order Maxwell equations:
**First:** When I used the `BlockVector` in `'Mult'` and `'ImplicitSolve'`, and did not to validate the result.
When we are using `BackwardEulerSolver, the absolute error should be second order both space and time.  Unfortunately the behavior is strange. Above you can find the detail about result # behavior. 

> _**Secod**_

 there might be a only reason  that I found. Why the result are not validated both in space and time using `BlockVector `  in ODESolver. The `ODESolver` is not perform well to solve the for system of equations using BlockVector. 
Could You please tell me? Have you validated the result using `BlockVector` similar method ex10 and joule both in space and time for linear Maxwell equations (absolute error)?
Could you please tell me if you have a problem to understand.?
Thanks .
Anees

**Comment by tzanio** [comment]
Hi Anees,

The ODE solvers work fine on `BlockVector` objects -- these are just vectors, and we have tested time integration in many cases.

I think your question is really about how to properly discretize time-dependent Maxwell's equations, and I believe @Dan2997925 and @mlstowell are confident in the methods used in the EM miniapps, including Joule and Maxwell.

I'm not sure how else can we help, so I'm closing this issue.

Tzanio

**Comment by Asadanees** [comment]
Hi Tzanio,
My question is not about the discretize of time dependent Maxwell's equations.
All LLNL members have more experience in MFEM than me. But we are discussing  about the correctness and behavior of ODESolver using `BlockVector`.
I am pretty sure that the use of `BlockVector` in ODE solver produce wrong result in absolute error, to solve the system of equations. 
In simple, ODEsolvers produce to wrong result to solve the system of equations usnig BlockVector. 
Because ODESolver updated full vector (BlockVector) at each time step instead of respective vector. 
As you mentioned that you have tested time integration in many cases. Why have ODEsolvers produced wrong result for the system of time integration? 
I am too busy to writing papers and others task of the projects.
please open this issue that I could communicate with you 
Thanks 
Anees
Anees
