### ISSUE TITLE
Getting subsections of a BlockVector

### ISSUE THREAD

**Issue by varchasgopalaswamy** [mfem/mfem#3933]
Hi,

I'm trying to figure out how I might get a nice way to take a subset of the blocks inside a BlockVector. Here's the kind of use-case I'm thinking of: 

```c++
// Create N gridfunctions, not necessarily from the same FE space 
ParGridFunction v1(&fespace); 
ParGridFunction v2(&fespace); 
...
ParGridFunction vN(&fespace); 

// Find block offsets for them
Array block_offsets(N); 
block_offsets[0] = 0; 
block_offsets[1] = v1->ParFESpace()->GetVSize(); 
block_offsets[2] = block_offsets[1] + v2->ParFESpace()->GetVSize(); 
...
block_offsets[N] = block_offsets[N-1] + vN->ParFESpace()->GetVSize(); 

// Create global state BlockVector 

BlockVector global_state(block_offsets, Device::GetMemoryType());

// Make each GF point to a section of the block vector
v1.MakeRef(fespace, global_state, block_offsets[0]); 
...
vN.MakeRef(fespace, global_state, block_offsets[N-1]);

// Get sections of block vector for grid functions  e.g. 4,7, and 10 and do some computations on them 

BlockVector local_state(...)
```

Any idea on how I might go about doing that?

**Comment by vladotomov** [comment]
@varchasgopalaswamy the `BlockVector` assumes that the internal `Vectors` are contiguous in memory, so I don't think this is possible without copying data (or rearranging the `global_state` appropriately and using the view constructor `BlockVector(double *data, const Array<int> & bOffsets);`). You might need something like #3559 for the general case.

**Comment by varchasgopalaswamy** [comment]
My motivation was that I might have various operators that calculate `dXdt` for only some grid functions. I could pass the whole `global_state` into an operator `op->Step(global_state,t,dt)` and calculate `dXdt` with a bunch of zeros in the appropriate places, but it just seemed wasteful, so I wanted to check if there was a way around it!
