### ISSUE TITLE
Solid contacts question

### ISSUE THREAD

**Issue by XuliaDS** [mfem/mfem#3935]
Hello!
This is rather a question than an issue. I have been looking at the examples of elasticity in MFEM but I haven't seen any in which there are two bodies in contact (eg., sliding ball on a plane). Most of the examples consist on a multi-material bar which is conformal at the change-material interface. My question is:
Can MFEM handle two independent meshes with an assigned contact region ? or does it have to always be a conformal single body where each cell has a material assigned? 

Apologies if the question is unclear...

Many thanks !

**Comment by jandrej** [comment]
[Tribol](https://github.com/LLNL/Tribol/tree/develop) is a dedicated library for non-conforming solid contact which has an MFEM interface.

**Comment by XuliaDS** [comment]
great!! thanks!
I just looked at the repo. are there any usage examples ?
