### ISSUE TITLE
Parallel FindPointsGSLIB, boundary normals

### ISSUE THREAD

**Issue by eliasboegel** [mfem/mfem#3936]
Hi,

I would like to write a toy DSMC code using MFEM. Specifically, I would like to use MFEM simply to provide mesh functionality, including finding:

1. Element ID corresponding to a physical coordinate
2. Obtaining the boundary normal at a boundary point at or closest to a given physical coordinate

As I understand, 1) can be done through `FindPointsGSLIB`, and 2) can be done through `GetBdrElementTransformation` and `CalcOrtho`.

- Can I reasonably assume that these methods are thread safe?
- If `FindPointsGSLIB` is called with a vector of points, are the points supplied treated in parallel?
- Is using `FindPointsGSLIB` and `GetBdrElementTransformation`/`CalcOrtho` a reasonable way to perform operations 1) and 2)?

Thanks!

**Comment by vladotomov** [comment]
@eliasboegel it all looks doable, but I'm not sure if `FindPointsGSLIB` is thread-safe, @kmittal2 is the person to comment on that. It works in parallel, and `GetBdrElementTransformation` has a version that doesn't reuse a global variable:

`void GetBdrElementTransformation(int i, IsoparametricTransformation *ElTr);`

**Comment by kmittal2** [comment]
FindPointsGSLIB should be thread safe. I am not sure what you mean by `treated in parallel` but hopefully the following helps. 

- All the communication needed to determine the element (and reference space-coordinates and the owning processor) that each point is inside, is handled internally.
 
- The onus of load balancing the work for finding the vector of points is on the user i.e. all processors should ideally not call `FindPoints` with the same vector of points. It is not a big deal if you do that for a few points and want to have interpolated values available on all processors. But if you have a large number of points, it is best to either distribute the vector of points apriori or define it completely on one of the processors.
