### ISSUE TITLE
Pressure Prediction Step in Incompressible Navier-Stokes Solver

### ISSUE THREAD

**Issue by lmolin3** [mfem/mfem#3937]
Hi all,
I'm currently working on an incompressible unsteady Navier-Stokes solver with pressure correction (the code is based on the NS miniapp). In the segregated approach, one of the steps is a pressure prediction which looks like:

$$ D M^{-1} D^T \overline{p} =  \frac{\alpha}{dt} (D \overline{u} + D_e \overline{u} ) $$

where **D**, **M**, **D^T**  are (negative) VectorDivergence, VectorMass and the last one is just the Transpose of **D**. These matrices are assembled and modified for essential velocity bcs (removed rows/cols for **M** and cols for **D**), and the removed cols from **D** are stored in **D_e**.

I'mnot assembling the operator, but rather planned on solving this with a CG, given the operator $$A=D M^{-1} D^T$$ as a TripleProductOperator, preconditioned with BoomerAMG applied to the pressure mass matrix **Mp**.
Since no dirichlet is applied to the pressure, I wrapped the preconditioner by an OrthoSolver, orthogonalize the rhs and removed the mean from the pressure GridFunction after the computation.

However, I'm still getting unphysical results for the pressure computation, and I was wondering if this is the right way to solve the problem, regardless of the choice of the preconditioner (specifically the use of the TripleProductOperator, and the strategy to remove the nullspace from the pressure solution).

Attached is part of the code for the setup and computation of the pressure.

Thanks for your help!

```c++
   /// ASSEMBLE MATRICES
   int skip_zeros = 0;  // Maintain sparsity pattern of M, K, C the same

   /// 1. Setup and assemble bilinear forms     
   M_form = new ParBilinearForm(ufes);  
   D_form = new ParMixedBilinearForm(ufes, pfes);
   M_form->AddDomainIntegrator(new VectorMassIntegrator());
   D_form->AddDomainIntegrator(new VectorDivergenceIntegrator());
   D_form->Assemble();            D_form->Finalize();
   M = M_form->ParallelAssemble();
   D = D_form->ParallelAssemble();
   *(D) *= -1; 


   /// MODIFY MATRICES for essential velocity BCS
   Me  = M->EliminateRowsCols(vel_ess_tdof);
   De  = D->EliminateCols(vel_ess_tdof);
   Dt = D->Transpose(); 
   Dte = De->Transpose(); 


   // PRECONDITIONER
   // Pressure Schur Complement ( Preconditioned with BoomerAMG with pressure mass matrix Mp)
   Mp_form = new ParBilinearForm(pfes);
   Mp_form->AddDomainIntegrator(new MassIntegrator);
   Mp_form->Assemble(); Mp_form->Finalize();
   Mp = Mp_form->ParallelAssemble();
   invDHDt_pc = new HypreBoomerAMG(*Mp);
   invDHDt_pc->SetPrintLevel(0);
   invDHDt_ortho_pc = new OrthoSolver(pfes->GetComm()); // Wrap preconditioner with OrthoSolver
   invDHDt_ortho_pc->SetSolver(*invDHDt_pc);  


   // SOLVER
   // Velocity correction 
   invM = new CGSolver(ufes->GetComm());
   invM->iterative_mode = false;          // Must keep it to false, since operator of an TripleProductOperator should not be in iterative mode
   invM->SetAbsTol(s4Params.atol);
   invM->SetRelTol(s4Params.rtol);
   invM->SetMaxIter(s4Params.maxIter);
   invM->SetPreconditioner(*invM_pc);
   invM->SetOperator(*M);
   invM->SetPrintLevel(s4Params.pl);

   // Pressure prediction 
   DHDt = new TripleProductOperator(D,invM,Dt,false,false,false); // operator through action: D M^{-1} Dt

   invDHDt1 = new CGSolver(ufes->GetComm());
   invDHDt1->iterative_mode = false;      
   invDHDt1->SetAbsTol(s2Params.atol);
   invDHDt1->SetRelTol(s2Params.rtol); 
   invDHDt1->SetMaxIter(s2Params.maxIter);
   invDHDt1->SetOperator(*DHDt);          
   invDHDt1->SetPreconditioner(*invDHDt_ortho_pc);       
   invDHDt1->SetPrintLevel(s2Params.pl);
   //invDHDt1_ortho = new OrthoSolver(pfes->GetComm()); // Wrap CG with OrthoSolver
   //invDHDt1_ortho->SetSolver(*invDHDt1);  






   /// 2. Solve pressure prediction step

   sw_pres_pred.Start();

   // Assemble rhs  D u_pred - fp
   De->Mult(*u_pred, *rhs_p1);    // fp = - De u_pred,  rhs_p1 = -fp = De u_pred    Modify rhs for pressure   
   D->AddMult(*u_pred,*rhs_p1);   // rhs_p1 += D u_pred 
   *rhs_p1 *= alpha / dt;
   Orthogonalize(*rhs_p1);

   invDHDt1->Mult(*rhs_p1,*p_pred);

   // Remove nullspace by removing mean of the pressure solution (also ensured by the OrthoSolver wrapper for preconditioner)
   p_pred_gf->SetFromTrueDofs(*p_pred);  
   MeanZero(*p_pred_gf);
   p_pred_gf->GetTrueDofs(*p_pred);

   sw_pres_pred.Stop();
```

**Comment by jandrej** [comment]
When you use
$$-DM^{-1}D^T$$
should be equivalent to the continuous operator of
$$(\nabla u, \nabla v)$$
and therefore you can use `DiffusionIntegrator` to represent the operator.

>preconditioned with BoomerAMG applied to the pressure mass matrix Mp.
Since no dirichlet is applied to the pressure, I wrapped the preconditioner by an OrthoSolver, orthogonalize the rhs and removed the mean from the pressure GridFunction after the computation.

This depends highly on the problem. Do you have an enclosed flow?

**Comment by lmolin3** [comment]
Hi @jandrej ,
Thanks for the prompt reply!

I was aware of the analogy with the continuous pressure Laplacian; problem is that this analogy is not always formal, and the “standard” differential splitting techniques introduce boundary layers for the pressure error (and you need to surrogate the bcs which are coupled in the monolithic system), while this does not affect algebraic splitting strategies.
In our case we have an algebraic Chorin-Temam with pressure correction (refs at the end), which basically arises from an approximate LU factorization of the monolithic system (with bcs applied).

Considering keeping the discrete formulation as it is, I was wondering if the iterative solution for the pressure solves with the operator DM-1Dt was formally correct in MFEM.

Regarding the flow, we don't have a specific one, in the sense that the solver would potentially be used for different applications (mainly open flows, but not restricted only to that).


[1] Saleri, Fausto, and Alessandro Veneziani. "Pressure correction algebraic splitting methods for the incompressible Navier--Stokes equations." SIAM journal on numerical analysis 43.1 (2005): 174-194.

[2] Gauthier, Alain, Fausto Saleri, and Alessandro Veneziani. "A fast preconditioner for the incompressible Navier Stokes Equations." Computing and Visualization in science 6 (2004): 105-112.
