### ISSUE TITLE
Incorrect `be_to_bfe` result for boundary element to face integration point mapping

### ISSUE THREAD

**Issue by sebastiangrimberg** [mfem/mfem#3938]
When using `GridFunction::GetValue` or `GetVectorValue` on a boundary element for a discontinuous solution, the integration point is mapped from the boundary element to the attached face, and then to the neighboring domain element to interpolate the solution. The boundary element to face mapping is performed by `be_to_bfe` in `gridfunc.cpp`. I noticed an issue using this method for boundary elements where the result was confusingly permuted unexpectedly between the boundary element and face element. It turns out that this is resolved by accounting for all 6 possible orientations (in the case of a triangle) instead of just the current logic.

That is, modifying:

```
if (o == 2)
{
   fip.x = 1.0 - ip.x - ip.y;
   fip.y = ip.x;
}
else if (o == 4)
{
   fip.x = ip.y;
   fip.y = 1.0 - ip.x - ip.y;
}
else
{
   fip.x = ip.x;
   fip.y = ip.y;
}
```

to:

```
if (o == 0)  // 0, 1, 2
{
   fip.x = ip.x;
   fip.y = ip.y;
}
else if (o == 5)  // 0, 2, 1
{
   fip.x = ip.y;
   fip.y = ip.x;
}
else if (o == 2)  // 1, 2, 0
{
   // Same as before:
   fip.x = 1.0 - ip.x - ip.y;
   fip.y = ip.x;
}
else if (o == 1)  // 1, 0, 2
{
   fip.x = 1.0 - ip.x - ip.y;
   fip.y = ip.y
}
else if (o == 4)  // 2, 0, 1
{
   // Same as before:
   fip.x = ip.y;
   fip.y = 1.0 - ip.x - ip.y;
}
else if (o == 3)  // 2, 1, 0
{
   fip.x = ip.x;
   fip.y = 1.0 - ip.x - ip.y;
}
```

based on the orientation definitions in [`Mesh::GetTriOrientation`](https://github.com/mfem/mfem/blob/master/mesh/mesh.cpp#L5862).

This bit of code seems to date back to https://github.com/mfem/mfem/pull/1194. @mlstowell, as the author there, do you have an explanation of why the original code only accounted for `o = 2` and `o = 4`, but not other orientations? It seems like they would always be required for the vertex permutations. Does the new approach seem correct? I imagine a similar change might need to be made for quads.

If this is indeed the right approach, then I can make a PR. Probably moving this method to be a `static` member of `Mesh` would make sense instead of having it hidden inside of `gridfunc.cpp` since it depends on the orientation definitions. There is probably a good way to test this with a unit test as well that should be part of that PR.

**Comment by tzanio** [comment]
I do want to hear what @mlstowell and @v-dobrev say, but what you have does look like the right solution to me, @sebastiangrimberg.

**Comment by sebastiangrimberg** [comment]
Thanks! After thinking about it some more I think I have a better explanation and am more convinced of the actual issue.

My hypothesis as to why I am uncovering this issue and why it may not have actually been a problem previously: as used in GridFunction, the boundary elements must be true (non-internal) boundary elements attached to a face which only has one neighbor element. By construction this means the boundary element and attached face always have aligned normals and this limits the number of possible orientations to the subset which are handled in the current code. I've been trying to use this approach to evaluate the boundary element -> face element map for INTERNAL boundaries, which is when I uncovered the issue. Probably this use case exposes the need to handle the full (6 for tri, 8 for quad) sets of orientations for the integration point. Correct me if I'm wrong but this sounds plausible to me at least, and I've opened #3943 to handle the general case!

**Comment by v-dobrev** [comment]
@sebastiangrimberg, are you using `GridFunction::GetValue` with interior "boundary" elements? If the field is discontinuous, what side do you expect to get values from?

Generally speaking, this method was not meant to be called for such boundary elements with a discontinuous field since the field is double-valued.

For such cases, there is the method `GridFunction::GetFaceValues` that allows the caller to choose the side they want.

**Comment by sebastiangrimberg** [comment]
No, I'm not using `GetValue` for exactly the reason you mention. But I had code doing a similar transformation from boundary element to face element on an interior face so that I could call `GetFaceValues`, and that's when I ran into the issue. The end result is that this isn't a bug in the original implementation of `be_to_bfe`, but rather just an error in my use of it which goes beyond the expected use. The PR https://github.com/mfem/mfem/pull/3943 is there to handle the general case for anyone looking for similar functionality.

**Comment by v-dobrev** [comment]
Okay, so the purpose of #3943 is not to generalize `GetValue` for interior "boundary" elements but rather to expose the extended functionality of the function `Mesh::TransformBdrElementToFace` that replaces the old, hidden `be_to_bfe`. Is that correct?

**Comment by sebastiangrimberg** [comment]
That's correct! The behavior of `GridFunction` is unchanged (still only intended for exterior boundary elements, since the call to `Mesh::GetBdrFaceTransformations` will fail and there's a side ambiguity in that case anyway).
