### ISSUE TITLE
Cannot retrieve elements attribute values via mesh.attributes.GetData()

### ISSUE THREAD

**Issue by JianboLong** [mfem/mfem#3939]
Hello, 
I'm trying to return a complete list of elemental material attributes (not boundary attributes) in the mesh by calling 
`mesh.attributes.GetData()
`
but got the the following results:
`mesh.attributes==: 0x600002d70000` 
[prints of `cout << "mesh.attributes==: " << mesh.attributes.GetData() << endl;`]

which looks like it's the address of the array "mesh.attributes". The test example is ex31.cpp. 

Other inquiry functions of mesh.attributes, like `mesh.attributes.max()`, work fine.  I checked the online source code of Array class, which `mesh.attributes` belongs to, but didn't find anything suspicious.  Is this caused by something else ?

**Comment by sebastiangrimberg** [comment]
Hi @JianboLong, if I understand your concern, `mfem::Array<T>::GetData()` returns a pointer to the first element of the array, so this is behaving as expected. It looks like you just want access to the `Array` object itself, which is just `mesh.attributes`.

If you want to access the entries of the `attributes` array, you should use the operator overload itself: `mesh.attributes[i]`.

**Comment by JianboLong** [comment]
Hi @sebastiangrimberg 

How can I return at once all of the entries of this `attributes` ?

**Comment by sebastiangrimberg** [comment]
`attributes` is of type `mfem::Array<int>`. A copy of this `Array` can be returned from a function as `return mesh.attributes`, a reference as `return mesh.attributes`, a pointer as `return &mesh.attributes`, or a pointer to the data as `return mesh.attributes.GetData()`. Does one of these fit your need?

**Comment by JianboLong** [comment]
> `attributes` is of type `mfem::Array<int>`. A copy of this `Array` can be returned from a function as `return mesh.attributes`, a reference as `return mesh.attributes`, a pointer as `return &mesh.attributes`, or a pointer to the data as `return mesh.attributes.GetData()`. Does one of these fit your need?

Not really .... what I need is a neat method to get the entries of `mesh.attributes` . Right now, I need to iterate over `mesh.attributes[i]; for i=0, etc ..`  And this is not done inside a function.  I thought the member function GetData() is exactly what I need, but it's not.  Any other suggestions ?  Let's say, I want to pass the entries of `mesh.attributes` to a new `Vector` object, how would you do it ?

**Comment by sebastiangrimberg** [comment]
Perhaps you can provide a prototype of the function you are trying to write in order for me to help you better?

An `mfem::Vector` is typically used to store floating point data, I'm not sure why you would want to copy an `mfem::Array<int>` such as `attributes` into a `Vector`. You could do it, but would need a for loop over the entries to cast the integer values to `double`. If you want to use an `Array` instead, you can use the copy constructor as I said above:

```
mfem::Array<int> mesh_attributes(mesh.attributes);
```

of copy assignment if that is nicer for you:

```
mfem::Array<int> mesh_attributes = mesh.attributes;
```

**Comment by JianboLong** [comment]
Hi @sebastiangrimberg  Sorry,  I forgot to mention that `Vector` is just a general vector, not necessarily the `mfem::vector` type.  Instead of copying the data of an array into another, I guess what I want to do is simpler: is there a quick way (without element-by-element loop) to return all entries of an `mfem:Array<int>` object ? E.g., copying the data of `mesh.attributes` to a vector object (let's say it's int type) of my own.

**Comment by sebastiangrimberg** [comment]
Hi @JianboLong, I think in order to provide any further help here I would need you to provide a minimal working (or not working) example of what you are trying to achieve. Without knowing the available constructors to your vector type, I can't really help. I don't see why looping over the elements of the `mfem::Array` and copying to your type is not a valid solution.

**Comment by JianboLong** [comment]
In the end, I have chosen the loop way to do this ! Thanks for the comments !
