### ISSUE TITLE
Support for binary legacy VTK mesh files

### ISSUE THREAD

**Issue by sethwatts** [mfem/mfem#3941]
This issue is related to #678 

I'm wondering about support for VTK legacy mesh files in binary format. Currently, [it appears](https://github.com/mfem/mfem/blob/25b98cc8ab7b924c68b2686ec5c4c5480cc66259/mesh/mesh_readers.cpp#L1165) that VTK mesh support is limited to ASCII format. However, parsing binary (legacy) VTK files is very similar to parsing the ASCII versions; the only difference is that the node position data and element connectivity and type information are stored as big-endian floats/doubles and ints rather than whitespace delinated text.

Even for modest mesh sizes, the binary format is more compact, and I'm working on developing very large mesh files, so support for binary VTK files would be welcome. I'd be happy to contribute this capability if it's not a current priority.

**Comment by pazner** [comment]
MFEM has fairly comprehensive support for XML VTK (VTU) meshes, including (compressed) binary formats, see [here](https://mfem.org/mesh-formats/#vtk-mesh-formats). Would that be enough for your use-case?

**Comment by sethwatts** [comment]
At the moment, I can write legacy VTK files in binary format, but not the newer XML-based version.

**Comment by pazner** [comment]
In that case, you are correct — MFEM does not support the binary legacy format. Such a contribution would be welcome (and could likely use some of the same helper functions as in the binary XML case).

In the mean time, you could probably use something like [meshio](https://github.com/nschloe/meshio) to do the conversion.

**Comment by pazner** [comment]
Closing for now. Please reopen if there are other issues.
