### ISSUE TITLE
`GradientIntegrator` does not implement `AddMultTransposePA`

### ISSUE THREAD

**Issue by stefanhenneking** [mfem/mfem#3944]
`GradientIntegrator` does not support partial assembly for the transpose operator yet.

Is anyone working on adding PA support?

```
PA Gradient AddMultTransposePA not implemented.
... in function: virtual void mfem::GradientIntegrator::AddMultTransposePA(const Vector &, Vector &) const
... in file: fem/integ/bilininteg_gradient_pa.cpp:826
```

See `ex18` for an example where this transpose operator is used.

**Comment by tzanio** [comment]
Hi @stefanhenneking,

I believe the Mult was originally implemented by @camierjs, but I don't think anyone is working on the transpose. If you'd like to do that, we will certainly welcome a PR.

Tzanio

**Comment by stefanhenneking** [comment]
@tzanio thanks for the info. I've tagged it with `help wanted` for now just in case anyone else is interested in adding this feature in the near term. If not, I will probably work on it some time in the next months myself (in which I'll update this PR then).

**Comment by stefanhenneking** [comment]
I've implemented this but need to do a bit of clean-up and testing before I the submit the PR. I'm closing this issue in the meantime so that no one else is starting to work on it simultaneously and doing redundant work.
