### ISSUE TITLE
DofTransfer between a high order ND parallel fespace and another serial ND fespace with same order

### ISSUE THREAD

**Issue by OliiLee** [mfem/mfem#3946]
Hi all,

I'm realizing the additive schwarz preconditioner based on mfem-4.5. I need to build several submeshes. In my code, one submesh is extracted from the original serial mesh which is the same mesh that the parmesh is built from. Then I build the serial fespace on the submesh and the global parallel fespace on the parmesh. In the algorithm, I need to tranfer a parallel gridfunction(i.e. a parallel vector) build on the global parallel fespace to a gridfunction build on the local serial fespace. I follow the idea in this project [petram](petram/helper/dof_map.py), i.e. compare the Shape or VShape of the fem basis located on the same physical node. And the dof transfer could be expressed with a sparse matrix. 

Things go right with H1 finite element and 1-order ND element. But when I use 2-order ND element, things go wrong. The program output different result when running in palallel.(i.e., result from "mpirun -np 1 program" is obviously different with that from "mpirun -np 4 program"). I think the reason is the shared face orientation of the parallel mesh and the VShape of the basis on the shared face. 

I realize that the mfem class ParSubmesh could be a choice but I want to change my code as little as possible. I'd appreciate any advice.

**Comment by OliiLee** [comment]
After learning some code about the parallel mesh and parallel fespace, I think I can clarify my question. Suppose that I have a 3d serial mesh `mesh` and construct a parallel mesh `pmesh` based on `mesh`. Now I can build 2-order Nedelec finite element space on both `mesh` and `pmesh` respectively, and get `fespace` and `pfespace`. `fespace` is serial and `pfespace` is parallel. Suppose that the program is running on 2 processors. I have some questions. 

1.  For a shared face in `pmesh`, there should be a "same" face in `mesh`. Let's say on rank 0, the k-th face is shared, and there should be a face in `mesh`, indexed by f(k), such that these two faces represent the same physical 2d-domain. But the true basis of `pfespace` on face k might not be the same as the basis of `fespace` on face f(k).  Even more, such basis of `pfespace` might not be linearly represented by basis of `fespace`. This depends on which processor owns face k. Am I right?
2. If the previous assertion is right. Then the mathematical finite element space represented by `fespace` is not equal to that represented by `pfespace`, right?

**Comment by sshiraiwa** [comment]
Hi @OliiLee 
Higher (>1) order ND has two degree of freedoms sit on the same location. When you create a new mesh using a part of mesh (like SubMesh or ParMesh), it is not given that the shape function corresponding to each of two DoFs are not same. A shape determined by two DoFs of the first mesh can be reproduced if you combine corresponding two DoFs properly (linear combination) on the other mesh. If the code stops working on a higher order ND, I would check this linear relationship first.
The code you referred are written to support between ParMesh and ParMesh distributed in a different manner. Thus, there are a few steps which may not be necessary in your situation.

**Comment by OliiLee** [comment]
> Hi @OliiLee Higher (>1) order ND has two degree of freedoms sit on the same location. When you create a new mesh using a part of mesh (like SubMesh or ParMesh), it is not given that the shape function corresponding to each of two DoFs are not same. A shape determined by two DoFs of the first mesh can be reproduced if you combine corresponding two DoFs properly (linear combination) on the other mesh. If the code stops working on a higher order ND, I would check this linear relationship first. The code you referred are written to support between ParMesh and ParMesh distributed in a different manner. Thus, there are a few steps which may not be necessary in your situation.

Hi. 
I noticed this combination a few days ago and fix this in my code. But the results are still problematic. Maybe I should check through my code.
Thanks for applying!

**Comment by hughcars** [comment]
> After learning some code about the parallel mesh and parallel fespace, I think I can clarify my question. Suppose that I have a 3d serial mesh `mesh` and construct a parallel mesh `pmesh` based on `mesh`. Now I can build 2-order Nedelec finite element space on both `mesh` and `pmesh` respectively, and get `fespace` and `pfespace`. `fespace` is serial and `pfespace` is parallel. Suppose that the program is running on 2 processors. I have some questions.
> 
> 1. For a shared face in `pmesh`, there should be a "same" face in `mesh`. Let's say on rank 0, the k-th face is shared, and there should be a face in `mesh`, indexed by f(k), such that these two faces represent the same physical 2d-domain. But the true basis of `pfespace` on face k might not be the same as the basis of `fespace` on face f(k).  Even more, such basis of `pfespace` might not be linearly represented by basis of `fespace`. This depends on which processor owns face k. Am I right?
> 2. If the previous assertion is right. Then the mathematical finite element space represented by `fespace` is not equal to that represented by `pfespace`, right?

1. The basis of a parallel version and serial version should be equivalent, up to a linear relation (in the case of p2 nd dofs here). The reason being that for any shared face, the map from one face orientation to another can always be represented as the action of a 2x2 matrix on those dofs, which is inherently linear. 
2. This will sound a little in the weeds, but the _mathematical_ spaces are identical, but the computational spaces can be subtly different due to the treatment of shared boundaries. The effect of this is that the two processor will both use a different basis on a shared face (as any boundary face (external or shared) always has an outward facing normal). 

This is all handled within the [DofTransformation class](https://github.com/mfem/mfem/blob/master/fem/doftrans.hpp) which is used to perform transformations both from the processor local representation to the element local representation, and also to handle the transformation between two different processor local representations.

The outcome of all this, and where I think you might be getting tangled, is that there isn't a unique orientation of all faces in the mesh, that will be common between serial and parallel. In the interior of any given partition, they likely will be the same, but on any shared boundary, the orientation is non-unique. Even in the interior of a partition,  MFEM defines the orientation of a face from the element that visited it first, as opposed to by a global vertex ordering, as done in other FEM codebases.

**Comment by OliiLee** [comment]
Hi @hughcars Sorry that I'm busy with other things these days. Thanks for the detailed explanation! It's very useful. I believe that I could build such dof transformation from the parallel fespace to serial fespace(and that from parallel fespace to local fespace built on submesh). 

Here is another question. As you said, there isn't a unique orientation of all faces in the mesh. This results in the system matrices being different since they might be built using different basis functions. And this difference has an effect on the iteration numbers when solving the linear system with iterative method (such as CG). I guess it can also affect the convergence of my domain decomposition algorithm. Is there a convenient way in MFEM to handle this difference? I can build the dof transformation by my own and make the system matrix built in serial the same as that built in parallel by applying a congruent transformation, i.e. let `pA = C^T A C`. Here is my code and I wish it helps you to understand what I'm saying. 

```c_cpp
#include "mfem.hpp"

using namespace std;
using namespace mfem;

// Building dof tranformation from parallel fespace to serial fespace.
// The resulting transformation is a sparsematrix for convenience.
SparseMatrix *DofTransfer(FiniteElementSpace *, ParFiniteElementSpace *);

int main(int argc, char *argv[])
{
    Mpi::Init(argc, argv);
    int myrank = Mpi::WorldRank();
    int nranks = Mpi::WorldSize();

    int order = 1;
    int n = 4;
    double s = 1.;
    int dim = 3;

    OptionsParser args(argc, argv);
    args.AddOption(&order, "-o", "--o", "order");
    args.AddOption(&n, "-n", "--n", "divide number");

    args.Parse();
    if (!args.Good())
    {
        if (myrank == 0)
            args.PrintUsage(cout);
        return 1;
    }

    Mesh *mesh = new Mesh(move(
        Mesh::MakeCartesian3D(n, n, n, Element::TETRAHEDRON, s, s, s, false)));

    ParMesh *pmesh = new ParMesh(MPI_COMM_WORLD, *mesh);

    FiniteElementCollection *fec = new ND_FECollection(order, dim);
    ParFiniteElementSpace *pfes = new ParFiniteElementSpace(pmesh, fec);
    FiniteElementSpace *fes = new FiniteElementSpace(mesh, fec);

    ConstantCoefficient one(1.0);
    VectorConstantCoefficient ones(Vector({1.0, 1.0, 1.0}));
    ParBilinearForm *pa = new ParBilinearForm(pfes);
    pa->AddDomainIntegrator(new CurlCurlIntegrator(one));
    pa->AddDomainIntegrator(new VectorFEMassIntegrator(ones));
    pa->AddBoundaryIntegrator(new VectorFEMassIntegrator(ones));
    pa->Assemble();

    BilinearForm *a = new BilinearForm(fes);
    a->AddDomainIntegrator(new CurlCurlIntegrator(one));
    a->AddDomainIntegrator(new VectorFEMassIntegrator(ones));
    a->AddBoundaryIntegrator(new VectorFEMassIntegrator(ones));
    a->Assemble();

    Array<int> ess_tdof_list;
    OperatorHandle pAh, Ah;
    pa->FormSystemMatrix(ess_tdof_list, pAh);
    a->FormSystemMatrix(ess_tdof_list, Ah);

    HypreParMatrix *pA = pAh.As<HypreParMatrix>();
    SparseMatrix *A = Ah.As<SparseMatrix>();

    SparseMatrix *C = DofTransfer(fes, pfes);
    SparseMatrix *Ct = Transpose(*C);
    SparseMatrix *AC = Mult(*A, *C);
    SparseMatrix *CtAC = Mult(*Ct, *AC);
    delete AC;
    delete Ct;

    HYPRE_BigInt rows[2];
    int nrows = pfes->GetTrueVSize();
    rows[0] = pfes->GetMyTDofOffset();
    rows[1] = rows[0] + nrows;

    Array<int> I(nrows + 1);
    I[0] = 0;
    for (int r = 0; r < nrows; ++r)
        I[r + 1] = CtAC->RowSize(r + rows[0]);
    for (int r = 0; r < nrows; ++r)
        I[r + 1] += I[r];
    int nnz = I[nrows];
    Array<HYPRE_BigInt> J(nnz);
    Vector data(nnz);
    for (int i = 0; i < nnz; ++i)
    {
        J[i] = CtAC->GetRowColumns(rows[0])[i];
        data[i] = CtAC->GetRowEntries(rows[0])[i];
    }

    HypreParMatrix pCtAC(MPI_COMM_WORLD, nrows, pfes->GlobalTrueVSize(),
                         pfes->GlobalTrueVSize(), I.GetData(), J.GetData(),
                         data.GetData(), rows, rows);

    // just for linear system solving test, no physical meaning
    Vector B(fes->GetTrueVSize()), pB(pfes->GetTrueVSize());
    Vector U(fes->GetTrueVSize()), pU(pfes->GetTrueVSize());
    B = 1. / pow(n, 3);
    pB = 1. / pow(n, 3);
    U = 0.;
    pU = 0.;

    int print_level = 3;
    double rel_tol = 1e-4;
    int max_iter = 1000;
    if (myrank == 0)
    {
        printf("Serial stiffness matrix cg procedure:\n");
        CGSolver cg;
        cg.SetPrintLevel(print_level);
        cg.SetRelTol(rel_tol);
        cg.SetMaxIter(max_iter);
        cg.SetOperator(*A);
        cg.Mult(B, U);
    }
    MPI_Barrier(MPI_COMM_WORLD);
    if (myrank == 0)
    {
        printf("Parallel stiffness matrix cg procedure:\n");
    }
    {
        CGSolver cg(MPI_COMM_WORLD);
        cg.SetPrintLevel(print_level);
        cg.SetRelTol(rel_tol);
        cg.SetMaxIter(max_iter);
        cg.SetOperator(*pA);
        cg.Mult(pB, pU);
    }
    MPI_Barrier(MPI_COMM_WORLD);
    if (myrank == 0)
    {
        printf("Parallel transformed stiffness matrix cg procedure:\n");
    }
    {
        CGSolver cg(MPI_COMM_WORLD);
        cg.SetPrintLevel(print_level);
        cg.SetRelTol(rel_tol);
        cg.SetMaxIter(max_iter);
        cg.SetOperator(pCtAC);
        pU = 0.;
        cg.Mult(pB, pU);
    }


    delete C;
    delete CtAC;
    delete fec;
    delete fes;
    delete pfes;
    delete pa;
    delete a;
    delete mesh;
    delete pmesh;
    return 0;
}

SparseMatrix *DofTransfer(FiniteElementSpace *fes_dest,
                          ParFiniteElementSpace *fes_src)
{
    int nranks = Mpi::WorldSize();
    int myrank = Mpi::WorldRank();

    int order = fes_dest->FEColl()->GetOrder();
    int nedges = 6;
    int nfaces = 4;
    int nedofs = order;
    int nfdofs = order * (order - 1);

    Array<bool> flag(fes_dest->GetTrueVSize());
    flag = false;

    ND_TetDofTransformation trans(order);

    SparseMatrix T(fes_dest->GetTrueVSize(), fes_src->GlobalTrueVSize());
    for (int el_src = 0; el_src < fes_src->GetNE(); ++el_src)
    {
        int el_dest;
        Vector center_src;
        fes_src->GetParMesh()->GetElementCenter(el_src, center_src);
        for (int j = 0; j < fes_dest->GetNE(); ++j)
        {
            Vector center_dest;
            fes_dest->GetMesh()->GetElementCenter(j, center_dest);
            if (center_src.DistanceTo(center_dest) <= 1e-4)
            {
                el_dest = j;
                break;
            }
        }

        Array<int> dofs_src, dofs_dest;
        fes_src->GetElementDofs(el_src, dofs_src);
        fes_dest->GetElementDofs(el_dest, dofs_dest);

        Array<int> faces, fo_src, fo_dest;
        fes_src->GetParMesh()->GetElementFaces(el_src, faces, fo_src);
        fes_dest->GetMesh()->GetElementFaces(el_dest, faces, fo_dest);

        // edges
        for (int e = 0; e < nedges; ++e)
        {
            for (int i = 0; i < nedofs; ++i)
            {
                int idx = e * nedofs + i;

                double s_src, s_dest;
                int tdof_src =
                    FiniteElementSpace::DecodeDof(dofs_src[idx], s_src);
                int tdof_dest =
                    FiniteElementSpace::DecodeDof(dofs_dest[idx], s_dest);
                int gtdof_src = fes_src->GetGlobalTDofNumber(tdof_src);

                double fac = s_src * s_dest;

                if (flag[tdof_dest])
                    continue;
                flag[tdof_dest] = true;
                if (fes_src->GetLocalTDofNumber(tdof_src) != -1)
                    T.Set(tdof_dest, gtdof_src, fac);
            }
        }

        // faces
        for (int f = 0; f < nfaces; ++f)
        {
            DenseMatrix d_src = trans.GetFaceInverseTransform(fo_src[f]);
            DenseMatrix d_dest = trans.GetFaceInverseTransform(fo_dest[f]);
            for (int i = 0; i < nfdofs / 2; ++i)
            {
                int idx = nedges * nedofs + f * nfdofs + 2 * i;

                Array<int> tdof_dest(2), tdof_src(2), gtdof_src(2);
                Vector s_src(2), s_dest(2);
                for (int j = 0; j < 2; ++j)
                {
                    tdof_src[j] = FiniteElementSpace::DecodeDof(
                        dofs_src[idx + j], s_src[j]);
                    tdof_dest[j] = FiniteElementSpace::DecodeDof(
                        dofs_dest[idx + j], s_dest[j]);
                    gtdof_src[j] = fes_src->GetGlobalTDofNumber(tdof_src[j]);
                }

                d_src.RightScaling(s_src);
                d_dest.RightScaling(s_dest);

                d_dest.Invert();
                DenseMatrix fac(2);
                Mult(d_dest, d_src, fac);

                MFEM_VERIFY(flag[tdof_dest[0]] == flag[tdof_dest[1]],
                            "internal error!");
                if (flag[tdof_dest[0]])
                    continue;
                flag[tdof_dest[0]] = flag[tdof_dest[1]] = true;

                if (fes_src->GetLocalTDofNumber(tdof_src[0]) != -1)
                    T.SetSubMatrix(tdof_dest, gtdof_src, fac);
            }
        }
    }
    T.Finalize();

    struct COO
    {
        int i;
        int j;
        double a;
    };
    MPI_Datatype MPI_COO;
    int block_length[3] = {1, 1, 1};
    MPI_Aint block_disp[3] = {offsetof(COO, i), offsetof(COO, j),
                              offsetof(COO, a)};
    MPI_Datatype types[3] = {MPI_INT, MPI_INT, MPI_DOUBLE};
    MPI_Type_create_struct(3, block_length, block_disp, types, &MPI_COO);
    MPI_Type_commit(&MPI_COO);

    int nnz = T.NumNonZeroElems();
    Array<int> recv_size(nranks), recv_offset(nranks + 1);
    MPI_Allgather(&nnz, 1, MPI_INT, recv_size.GetData(), 1, MPI_INT,
                  MPI_COMM_WORLD);

    recv_offset[0] = 0;
    for (int i = 0; i < nranks; ++i)
        recv_offset[i + 1] = recv_offset[i] + recv_size[i];

    vector<COO> send_buff(nnz), recv_buff(recv_offset[nranks]);
    int offset = 0;
    for (int r = 0; r < T.Height(); ++r)
    {
        int rs = T.RowSize(r);
        int *col_idx = T.GetRowColumns(r);
        double *val = T.GetRowEntries(r);
        for (int c = 0; c < rs; ++c)
        {
            send_buff[offset].i = r;
            send_buff[offset].j = col_idx[c];
            send_buff[offset].a = val[c];
            offset++;
        }
    }

    MPI_Allgatherv(send_buff.data(), nnz, MPI_COO, recv_buff.data(),
                   recv_size.GetData(), recv_offset.GetData(), MPI_COO,
                   MPI_COMM_WORLD);

    SparseMatrix *mat =
        new SparseMatrix(fes_dest->GetTrueVSize(), fes_src->GlobalVSize());
    for (auto it : recv_buff)
    {
        mat->Set(it.i, it.j, it.a);
    }
    mat->Finalize();

    return mat;
}
```

**Comment by hughcars** [comment]
> Hi @hughcars Sorry that I'm busy with other things these days. Thanks for the detailed explanation! It's very useful. I believe that I could build such dof transformation from the parallel fespace to serial fespace(and that from parallel fespace to local fespace built on submesh).
> 
> Here is another question. As you said, there isn't a unique orientation of all faces in the mesh. This results in the system matrices being different since they might be built using different basis functions. And this difference has an effect on the iteration numbers when solving the linear system with iterative method (such as CG). I guess it can also affect the convergence of my domain decomposition algorithm. Is there a convenient way in MFEM to handle this difference? I can build the dof transformation by my own and make the system matrix built in serial the same as that built in parallel by applying a congruent transformation, i.e. let `pA = C^T A C`. Here is my code and I wish it helps you to understand what I'm saying.
> 

In theory such a transfer should work, I'm not sure I really understand why one would want to go from parallel to a serial fe space, unless the serial were defined on a mesh that effectively makes up a sub piece of the parallel mesh. But conditioning on that, you could indeed build matrices C as you described. I would suggest testing you have them correct by projecting a reasonably rapidly varying function onto a p2 ND space on the parallel and serial spaces, then transfer from the parallel to the serial using your operator (which I think should also apply to true dofs if I understand correctly). If they aren't in exact agreement, you made an error, then if doing this all within one of the examples, you can visualize within glvis/find the element in question. From experience debugging/working with these face orientations can be fiddly, so I would suggest avoiding it if you can though. 

At a higher level, I would like to reiterate the point above that `ParSubMesh` sounds fairly ideal for your purposes, I understand your desire to be "minimal" but you're going to end up having to implement (and test (and debug)) a lot yourself, compared to using the ParSubMesh capability that was created with this type of mesh/space manipulation in mind.

**Comment by OliiLee** [comment]
> I can build the dof transformation by my own and make the system matrix built in serial the same as that built in parallel by applying a congruent transformation, i.e. let `pA = C^T A C`
This works. But I'm not sure the reason why my original implementation, i.e. building the dof transformation from parallel fespace to serial sub-fespace directly, doesn't work. There might be undiscovered bugs in my code. I'm going to close this issue now since the current code works. Thanks for the help.
