### ISSUE TITLE
Implementing a cardiovascular outflow b.c.

### ISSUE THREAD

**Issue by ryanblack129** [mfem/mfem#3954]
Hello,

I am trying to apply the following boundary condition that is very common to cardiovascular flow modeling (resistance b.c.), where $\Gamma_a$ is a part of the boundary, $\mathbf{n}$ is the outward normal, $\mathbf{v}$ is the test function, $\mathbf{u}$ is the trial solution, and $R$ is some constant value.

$r(\mathbf{v},\mathbf{u}) = (\int_{\Gamma_a} \mathbf{v} \cdot \mathbf{n} d\Gamma) * R * (\int_{\Gamma_a} \mathbf{u} \cdot \mathbf{n} d\Gamma)$

and its discretization, let $S_{Ai} = \int_{\Gamma_a} N_A n_i d\Gamma$, then

$K_{ik}^{AB} = R*S_{Ai}*S_{Bk}$

where $N_A$ is the shape function corresponding to node $A$. To form this matrix, each node on the boundary $\Gamma_a$ needs to communicate with every other node on that boundary, so element by element formation of this matrix will not work.

My attempt at trying to form this matrix involves computing $S_{Ai}$ using `VectorBoundaryFluxLFIntegrator(1.0)` and `LinearForm->Assemble()` and then constructing a `SparseMatrix` by computing an outer product with the assembled linear form. However, I am struggling with how to do this in parallel? Is it possible to force the entire boundary of interest to exist on a single processor? Is there a better way to form this matrix in parallel?

My understanding is that I will need to form a  `HypreParMatrix` for this matrix to be able to use with my existing parallel code and data structures.

Thanks,
Ryan

**Comment by jandrej** [comment]
Can you provide us with a reference for such boundary condition?

**Comment by ryanblack129** [comment]
Sure, here is a reference for this b.c

https://www.sciencedirect.com/science/article/pii/S0045782505002586

**Comment by ryanblack129** [comment]
Following up on this, one way to approach this could be:

Code an operator that defines the action of this matrix $K_{ik}^{AB}$. Apply the first integral to the input vector ($u_{Bk}$), and then multiply the result with the second integral defining the output vector ($y_{Ai}$). 

1) $q = S_{Bk} u_{Bk}$
2) $y_{Ai} = q * R * S_{Ai}$

The part I am not sure about is how to use this matrix defined only by its mat-vec multiplication with iterative solvers and preconditioners such as HypreBoomerAMG in MFEM?
