### ISSUE TITLE
Question about Deforming Boundaries and Remeshing with TMOP

### ISSUE THREAD

**Issue by sungho91** [mfem/mfem#3955]
Hi all,

I have a quick question.

My problem starts with a rectangular domain, but it must have highly deformed boundaries on the top and bottom surfaces, as well as deforming inner nodes over time (see attached image). So, I need to remesh my mesh continuously to run my model without blowing up.

However, to ensure the shape of my domain, I need to apply fixed boundary conditions for the TMOP method.

As a result, there may be unimproved elements near the top and bottom boundaries (see attached image).

I've heard that a boundary-fitting meshing (mesh-fitting app) approach can be useful for resolving my issue. However, the example you mentioned handles only the inner boundary using different material indicators.

In my case, the problem involves a single material and an arbitrary shape that is not determined analytically.

If you could provide me with any insights or solutions, it would be greatly appreciated.

Many thanks

Sungho

![Figure](https://github.com/mfem/mfem/assets/40257026/2e0d57ad-dc9d-40d9-aab6-607c17b239eb)

**Comment by vladotomov** [comment]
Hi @sungho91, what should the boundary nodes do in this case? (knowing that the initial boundary normals are generally discontinuous across the elements).

**Comment by sungho91** [comment]
When TMOP runs, I'd like the boundary nodes to move tangentially to the arbitrary shape of the left, right, top, and bottom boundaries. So, if the domain is simply a box, the top nodes can move in the x-direction, but their movement follows the first derivative direction if the boundary is a curved shape.

**Comment by vladotomov** [comment]
We have some ongoing work on such methods, but that is not ready yet.

As I wrote above, the main challenge is that the tangential direction is not well-defined if we only use the mesh faces. This requires some form of approximate treatment to improve smoothness, which consequently will not preserve the original discrete surface exactly. Then when remap is involved, one has to decide what to do with the mismatch between the boundaries. So are you willing to tolerate a geometric error? If not, keeping the nodes fixed is probably the best.

**Comment by sungho91** [comment]
Hi @vladotomov,

It's been a long time since I started working on boundary-preserved remeshing on a deformed boundary. I realized that a two-step remeshing approach would resolve this issue.

Figure 1 depicts the standard remeshing process using a free slip condition, resulting in a change in the shape of the domain after remeshing.

However, in Figure 2, the shape of the domain remains unchanged after remeshing. To achieve this, I flatten the top and bottom boundaries, transforming my model into a square domain. I then remesh this model using a free slip condition.

By utilizing both the flattened model and the remeshed model, I interpolate the grid function of coordinates before remeshing, allowing me to find coordinates on the boundary of the deformed shape of the domain. Finally, I update these interpolated values to the mesh and perform a remesh with fixed boundaries.

![Picture1](https://github.com/mfem/mfem/assets/40257026/3261a534-5dd1-4f35-8fe2-1dcc7a0b6415)
Figure 1. Remeshing with freeslip condition.

![MicrosoftTeams-image](https://github.com/mfem/mfem/assets/40257026/5c5e243b-63e9-4004-85fd-6e5a53850140)
Figure 2. Two-step remeshing

**Comment by vladotomov** [comment]
Looks good, but if you detach the treatment of the boundary and the internal nodes, things can tangle quickly, especially with curved meshes.

**Comment by sungho91** [comment]
@vladotomov, 

Yes yes, I've faced the negative Jacobian issue (https://github.com/mfem/mfem/issues/4047). This is strange as this process is technically stretching. However, things tangle eventually. I don't understand why and how to untangle them.
