### ISSUE TITLE
what is exactly going on in saving data with ParaViewDataCollection

### ISSUE THREAD

**Issue by JianboLong** [mfem/mfem#3958]
Hello, 

I'm puzzled by the exact information saved with the mesh when we call ParaViewDataCollection: 
```c++
ParaViewDataCollection *pd = NULL;
   if (paraview)
   {
      pd = new ParaViewDataCollection("folder", &mesh);
      pd->SetPrefixPath(mydir+"path_to_ParaView"); // the path to save Paraview data
      pd->RegisterField("solution", &sol);  // solution field
      pd->SetLevelsOfDetail(order);  // order == 1
      pd->SetDataFormat(VTKFormat::BINARY);
      pd->SetHighOrderOutput(false);
      pd->Save();
   }
``` 
The `mesh` is a tetrahedral mesh, the GridFunction `sol` is constructed over a Nedelec FE space with this mesh:
```c++
FiniteElementCollection *fec = NULL;
fec = new ND_FECollection(order, dim);  // order == 1; dim == 3 (3-D mesh)
FiniteElementSpace fespace(&mesh, fec);
GridFunction sol(&fespace);
``` 

As a result, I expect that the data field would be edge-associated, since my `sol` only has vector values on all the edges of the mesh. However, when viewed from Paraview, this saved vtu file shows the data point mount is 270,744 with each data point having X, Y, Z and magnitude components, whereas the mesh information is:
NO. of cells: 67686; NO. of vertices: 11451; NO. of edges: 79297; NO. of faces: 135533

Can someone make sense of these ? Thanks !

**Comment by tzanio** [comment]
@pazner can confirm, but I don't think ParaView understands H(curl) elements natively

**Comment by JianboLong** [comment]
Thanks for the comments @tzanio ! Do you think GLvis will be better in visualizing this ? For other technical reasons, I haven't been able to compile GLvis on the mac OS I am using. 

Also, regardless, the viewing tools, do you know what exactly the function `RegisterField ` is doing here ?

**Comment by pazner** [comment]
Hi @JianboLong, all ParaView data collections represent grid functions essentially as "DG-type" fields. This is a bit wasteful in terms of the number of points, but it allows for faithful visualization of H(curl), H(div), DG fields.

**Comment by JianboLong** [comment]
Hi @pazner Could you explain more about what kind of data are written to the file when saving the mesh with a H(curl) grid function this way ? The reason I am asking is that, after Paraview visualizing, the vectors (glyphs) of the saved field are very random and not making much sense. 

![Screenshot 2023-10-31 at 11 31 42 AM](https://github.com/mfem/mfem/assets/28963441/cdb552a3-e168-401e-8fdd-016e36b68126)

**Comment by pazner** [comment]
All vector fields are represented the same way in the ParaView data collection, regardless if they are in H(curl), H(div), vector H1, DG, etc. They are represented using point values at nodal points within each element.

Your example does look strange, but it's hard to tell what's causing it. Are you sure your results are correct? If I add ParaView output to ex3 (curl-curl problem using H(curl) elements), the glyphs look fine to me. For example, on the Fichera mesh:

<img width="488" alt="image" src="https://github.com/mfem/mfem/assets/11493037/8a76fe15-1237-4a46-a8be-6a55a0bc4b95">

**Comment by pazner** [comment]
Closing for now. Please re-open if you have further questions.
