### ISSUE TITLE
Converting a VisItDataCollection in serial format from an existing data collection saved in parallel (with pyMFEM). 

### ISSUE THREAD

**Issue by etiennespieser** [mfem/mfem#3960]
Dear MFEM-community,

For post-processing purposes, I want to rewrite some solution saved in VistIt format from parallel to serial using pyMFEM.

My solution has been generated with MFEM v.4.5.2, and I am using pyMFEM with the same version tag to process the data.

Here is the VisItDataCollection containing mesh and a field partitioned in 20 that I use [test_data.zip](https://github.com/mfem/mfem/files/13225710/test_data.zip).

I run my code `pmesh2mesh.py` hereafter using `mpirun --oversubscribe -np 20 python pmesh2mesh.py`.

```
import os
import mfem.par as mfem
from mpi4py import MPI

num_procs = MPI.COMM_WORLD.size
myid = MPI.COMM_WORLD.rank

testDataFolder = '/home/path/to/test_data/'

### import of pmesh
fname = mfem.MakeParFilename(testDataFolder+'/VisIt_volume/cycle_000000/pmesh.', myid)
pmesh = mfem.ParMesh(MPI.COMM_WORLD, fname)

### loading of the pressure field from the VisIt data collection
visit_dc = mfem.VisItDataCollection(testDataFolder+'VisIt_volume/cycle')
visit_dc.SetMesh(MPI.COMM_WORLD, pmesh)
visit_dc.Load(0)
p = visit_dc.GetField("pressure")

### printing additional information on the mesh
mesh_mfem = visit_dc.GetMesh()
mesh_data = mesh_mfem.GetNodes() # .GetTrueVector()  
order = int(mesh_mfem.GetNodalFESpace().FEColl().GetOrder())
dim = mesh_mfem.GetNodes().VectorDim()
dof = int(mesh_data.Size()/dim) # scalar degree of freedom, to be multiplied by number of scalar variables to have total dof
nele = mesh_mfem.GetNE() # .GetGlobalNE()
mesh_point_ordering = mesh_mfem.GetNodes().FESpace().GetOrdering() # "Ordering::byNODES=0" or "Ordering::byVDIM=1"

if myid == 0:
    print("dim="+str(dim))
    print("numb elem="+str(nele))
    print("order="+str(order))
    print("scalar dof="+str(int(dof)))
    print("pmesh_point_ordering ="+str(mesh_point_ordering))

### save the mesh in serial format
if myid == 0:
    folderList = [testDataFolder+'/VisIt_volume_serial/']
    for folderName in folderList:
        if not os.path.exists(folderName):
          os.mkdir(folderName)
MPI.COMM_WORLD.gather(myid, root=0)

pmesh.PrintAsSerial(testDataFolder+'/VisIt_volume_serial/mesh_serial')
mesh = mfem.Mesh(testDataFolder+'/VisIt_volume_serial/mesh_serial')
mesh.SetCurvature(order, False, dim, mesh_point_ordering)

### export the VisIt data collection in Serial format -- fails !
visit_dc_out = mfem.VisItDataCollection(testDataFolder+'/VisIt_volume_serial/cycle', mesh) # choosing 'pmesh' instead of 'mesh' also fails
# visit_dc.SetMesh(MPI.COMM_WORLD, mesh) # enforcing the 'mesh' or 'pmesh' via SetMesh() also throws an error
visit_dc_out.SetLevelsOfDetail(order)
visit_dc_out.RegisterField("pressure", p)
visit_dc_out.SetCycle(0)
visit_dc_out.SetTime(0)
visit_dc_out.SetFormat(mfem.DataCollection.SERIAL_FORMAT)
visit_dc_out.Save() 
```
By choosing `mesh` in the constructor of `visit_dc_out`, the solution saved is serial, but the field saved is wrong. By choosing `pmesh` the solution is correctly saved but in parallel, even though the format has been enforced into serial...

Did anyone encounter this behaviour by the past ?  

I use gcc-12.2.0, openmpi-4.1.5 on ubuntu 22.04 and my python environment has been installed with miniconda3. I do not know if this issue is MFEM or pyMFEM related... I hope I'm posting on the right place !

Many thanks

Étienne

**Comment by sshiraiwa** [comment]
Hi @etiennespieser, I think ParGridFunction::GetSerialGridFunction can be used for this purpose, but this method somehow causing a segfault for me. I am asking this in #3965. Please stay tuned ;D

**Comment by sshiraiwa** [comment]
For now, can you try using ```ParGridFunction::SaveAsSerial```. This one doesn't fail at least in my environment.  Thus, you could save a serial GridFunction and load it, as below. (Ideally, it is better to do it without file access). But, so far I am having a problem of generating a serial GridFunction itself)
```
smesh = pmesh.GetSerialMesh(0)
p.SaveAsSerial(testDataFolder+'/VisIt_volume_serial/pressure_serial', 8, 0)
if myid == 0:
   smesh.Print(testDataFolder+'/VisIt_volume_serial/mesh_serial')
   smesh.SetCurvature(order, False, dim, mesh_point_ordering)

   sp = mfem.GridFunction(smesh, testDataFolder+'/VisIt_volume_serial/pressure_serial')

### export the VisIt data collection in Serial format -- fails !
   visit_dc_out = mfem.VisItDataCollection(testDataFolder+'/VisIt_volume_serial/cycle', smesh) # choosing 'pmesh' instead of 'mesh' also fails
   visit_dc_out.SetLevelsOfDetail(order)
   visit_dc_out.RegisterField("pressure", sp)
   visit_dc_out.SetCycle(0)
   visit_dc_out.SetTime(0)
   visit_dc_out.SetFormat(mfem.DataCollection.SERIAL_FORMAT)
   visit_dc_out.Save() 
```

**Comment by etiennespieser** [comment]
Hi @sshiraiwa,

I tried to follow https://github.com/mfem/mfem/issues/3965, thanks for digging further into the issue and reporting it.

I tried your solution, but my code returned the following error:
```
AttributeError: 'GridFunction' object has no attribute 'SaveAsSerial'
```
It seems that `ParGridFunction::SaveAsSerial` is not yet available in the released version of pyMFEM (I couldn't find it here: https://github.com/mfem/PyMFEM/blob/master/mfem/_par/pgridfunc.i ). Could you please confirm this? (I am eager to be up-to-date with my version of pyMFEM, it's such a nice add-on to MFEM !)

In the meantime, I could figure a way around my problem by using `mfem.FindPointsGSLIB()` to export in parallel the data I needed, and the problem I reported in opening this ticket is no longer an issue for the time being.

**Comment by sshiraiwa** [comment]
Yes. In fact, this was added to MFEM after 4.5.2 release. I am glad that you have a workaround since PyMFEM 4.6 is still in progress. It is in mfem_46_dev. While we still need to go a few steps (https://github.com/mfem/PyMFEM/issues/197), you could try it, if needed in future.

**Comment by etiennespieser** [comment]
OK, thanks for the confirmation. Needless to say, I'll be keeping an eye on pyMFEM as it matures. Good luck with its future developments.
