### ISSUE TITLE
updating of face counts on topology changes of a ParMesh

### ISSUE THREAD

**Issue by rw-anderson** [mfem/mfem#3963]
In order for mesh.GetNFbyType(..) to return correct face counts, nbInteriorFaces or nbBoundaryFaces must be invalidated (set to -1) whenever the mesh topology changes to trigger a recount.  It looks like the ResetLazyData() function is usually called to perform this invalidation.

On a ParMesh object, when Mesh::GeneralRefinement() is called, if the mesh is an ncmesh, this calls the ParMesh version of NonconformingRefinement. There does not appear to be a call to ResetLazyData in this function. There is one in Mesh::NonconformingRefinement, but this is never called when the object is a ParMesh.

This does give incorrect results when mesh.GetNFbyType(...) is called after a refinement operation, when the Mesh is a ParMesh.

It looks like this could be remedied either by adding a ResetLazyData() call to ParMesh::NonconformingRefinement, or by hoisting the calls in Mesh::NonconformingRefinement() and Mesh::LocalRefinement() up to the level of Mesh::GeneralRefinement(). This should then cover all 3 cases.

If there is consensus that what I've written above is correct, I can submit a PR.

**Comment by v-dobrev** [comment]
@rw-anderson, this same issue came up in some debugging we did with @artv3. What you propose seems a good solution -- I think it may be better to add `ResetLazyData()` call to `ParMesh::NonconformingRefinement()` instead of moving the call up to `Mesh::GeneralRefinement()` since this way the protected refinement methods will be correct on their own.

**Comment by rw-anderson** [comment]
This same issue is present in ParMesh::Rebalance(), which also changes face counts. I will submit a PR momentarily.
