### ISSUE TITLE
strange mesh refining error

### ISSUE THREAD

**Issue by JianboLong** [mfem/mfem#3974]
Hello, @tzanio 

I'm using a simple mesh refining method in AMR: (mfem v4.6)

```c++
Mesh pmesh(mesh_file, 1, 1);

 fec = new H1_FECollection(order, dim);  // order = 1; dim = 3
FiniteElementSpace fespace(&pmesh, fec);
if(refine loop begins)
{
       int neles = pmesh.GetNE();
       Vector errors(neles);
        // some error calculation here .....

       // Refine the elements whose error is larger than a fraction of the
       // maximum element error.
       const double frac = 0.5;
      double max_err = errors.Max();    // max_err is 3.54e-4 for the test
       double threshold = frac * max_err;
       { cout << "Refining ..." << endl; }
       pmesh.RefineByError(errors, threshold);
}
``` 
but I keep getting the following strange run-time error:

Verification failed: (GetNE() == 0 || ((Tetrahedron*)elements[0])->GetRefinementFlag() != 0) is false:
 --> tetrahedral mesh is not marked for refinement: call Finalize(true)
 ... in function: virtual void mfem::Mesh::LocalRefinement(const mfem::Array<int>&, int)
 ... in file: /Users/.../myworks/MFEM/mfem-master/mesh/mesh.cpp:9167

This error literally says that `GetRefinementFlag() == 0` ( since `pmesh.GetNE() /= 0` can be easily verified), but I can't figure out why this is happening.

Running examples such as ex6 has no issues. 
Could anyone offer any help ?

Thanks !
mesh_file is (remove .txt to get .vtk file)
[New_MT.vtk.txt](https://github.com/mfem/mfem/files/13323340/New_MT.vtk.txt)

**Comment by hughcars** [comment]
To perform refinement on a tet mesh (based on that error message I assume that), you need to Finalize the mesh first. This will reorder the vertices in each element so the longest is set 0-1, and then set the refinement flag appropriately. If you call `mesh.FinalizeTopology()` then [`mesh.Finalize(true)`](https://github.com/mfem/mfem/blob/master/mesh/mesh.hpp#L903-L917) before building the fespace, I think that should resolve your issue.
