### ISSUE TITLE
Help with Understanding and Deriving `NonlinearFormIntegrator::AssembleElementGrad`

### ISSUE THREAD

**Issue by j-signorelli** [mfem/mfem#3975]
Hello,

I have been working through understanding how to implement my own `NonlinearFormIntegrator` specifically for nonlinear scalar diffusion like $$\nabla \cdot (k(u) \nabla u) = 0$$

I have looked through #2791, #160, #2755, [here](https://mfem.org/nonlininteg/), and the source code for `DiffusionIntegrator` and `MassIntegrator` but still have some confusions:

My main question is: **How is, using the Gateaux derivative for determining the Jacobian, $\delta u$ actually represented in the code?**
  - For #2791, the nonlinearity considered is a $f(u) = e^{\alpha u}$ term in a $(f(u), v)$ inner product. When I take the Gateaux derivative of $f(u)$, I get $F'(u, \delta u) = \alpha e^{\alpha u} \delta u$. However, the code uses $F'(u, \delta u) = \alpha e^{\alpha u} u$; why is this OK to just use $\delta u = u$?
  - Similarly, for a diffusion operator $(\lambda \nabla u , \nabla v)$ represented by `DiffusionIntegrator`, my presumption is that the `AssembleElementGrad` function must implement $(F'(u, \delta u), \nabla v)$. Taking the Gateaux derivative of $f(u)=\lambda \nabla u$ gives me $F'(u, \delta u) = \lambda \nabla \delta u$. However, the code for `DiffusionIntegrator::AssembleElementGrad` simply just calls `DiffusionIntegrator::AssembleElementMatrix`, essentially assuming $\delta u = \phi_i$. Why is this acceptable?

Thank you for any assistance.

**Comment by vladotomov** [comment]
Hi @j-signorelli ,

We have $u = \sum_i u_i \phi_i$ for a FE function $u$. Then derivatives are taken w.r.t. the coefficients $u_i$:

$\frac{\partial F(u)}{\partial u_i} = \frac{\partial F(u)}{\partial u} \frac{\partial u}{\partial u_i} = \frac{\partial F(u)}{\partial u} \phi_i$

Does this help?

**Comment by j-signorelli** [comment]
Hi @vladotomov 

Apologies for taking awhile to respond. Thank you - that is extremely helpful.

So if I understand correctly, for a nonlinear form $(e^{\alpha u}, v)$:
`AssembleElementVector` = $\int_\Omega e^{\alpha u} \phi_j d\vec{x}$
`AssembleElementGrad` = $\dfrac{\partial}{\partial u_i}\left(\int_\Omega e^{\alpha u} \phi_i d\vec{x}\right) = \int_\Omega \alpha e^{\alpha u}\phi_i \phi_j d\vec{x}$

Applying this for a `DiffusionIntegrator`, $(\lambda \nabla u, \nabla v)$:
`AssembleElementVector` = $\int_\Omega (\lambda u_i \nabla\phi_i) \cdot \nabla\phi_j d\vec{x}$
`AssembleElementGrad` = $\dfrac{\partial}{\partial u_i}\left(\int_\Omega (\lambda u_i \nabla\phi_i) \cdot \nabla\phi_j d\vec{x}\right) = \int_\Omega (\lambda \nabla\phi_i) \cdot \nabla\phi_j d\vec{x}$ = `AssembleElementMatrix`

Applying this for a _nonlinear_ diffusion integrator, $(k(u) \nabla u, \nabla v)$:
`AssembleElementVector` = $\int_\Omega (k(u) u_i \nabla\phi_i) \cdot \nabla\phi_j d\vec{x}$
`AssembleElementGrad` = $\dfrac{\partial}{\partial u_i}\left(\int_\Omega (k(u) u_i \nabla\phi_i) \cdot \nabla\phi_j d\vec{x}\right) = \int_\Omega (k'(u) u_k \nabla\phi_k   \phi_i) \cdot \nabla\phi_j d\vec{x} + \int_\Omega (k(u) \nabla\phi_i) \cdot \nabla\phi_j d\vec{x}$

Is my understanding correct now for this?

Thanks again very much.

**Comment by vladotomov** [comment]
Is this in Einstein notation?

**Comment by emorell96** [comment]
@j-signorelli could you post the code you ended up using for the nonlinear diffusion integrator? I am trying to recreate my own but I am afraid I'm a bit lost at how to implement the maths in the class itself.

Thanks!
