### ISSUE TITLE
apply 3d displacement on  boundary nodes of 2d mesh

### ISSUE THREAD

**Issue by hedashua** [mfem/mfem#3977]
Dear MFEM users

I input .msh format model generated by gmsh into the EX2 of MFEM and try to solve it, I want to apply xyz displacement on boundary node, but it seems that the EX2 of MEFM only solves the problems of 2D plane model and 3D solid model. i check sol.gf,  but the node displacement is only in the X and Y directions, which is obviously not what I want.

If possible, please let me know what I need to know, I would be very grateful!

**Comment by tzanio** [comment]
Hi @hedashua,

I am not sure I understand the problem -- are you trying to model a thin 2D plate in 3D? If that's the case, you need shell finite element which we don't currently have in MFEM.

Hope this helps,
Tzanio
