### ISSUE TITLE
It looks like strumpack might leak this memory

### ISSUE THREAD

**Issue by tepperly** [mfem/mfem#3978]
It looks like this patch might plug a potential memory leak in the strumpack wrapper.
```diff
diff --git a/linalg/strumpack.cpp b/linalg/strumpack.cpp
index f0ff11ab4..7c60c4999 100644
--- a/linalg/strumpack.cpp
+++ b/linalg/strumpack.cpp
@@ -82,6 +82,7 @@ STRUMPACKRowLocMatrix::STRUMPACKRowLocMatrix(const HypreParMatrix & hypParMat)
                                      csr_op->data, dist, comm_, false);
    delete[] dist;
 
+   hypre_TFree(hypre_CSRMatrixBigJ(csr_op), hypre_CSRMatrixMemoryLocation(csr_op));
    // Everything has been copied or abducted so delete the structure
    hypre_CSRMatrixDestroy(csr_op);
 }
```
If I understand things correctly, line 62 tells `csr_op` that it no longer owns its data, and this prevents hypre from freeing `csr_op->j`, `csr_op->data` and `csr_op->bigJ`. Assuming that the construction of `A_` on line 81 takes ownership of `j` and `data`, this leaves `BigJ` to be leaked unless it's individually deleted.

I've tried adding this line in my codevelop build of LiDO, and it doesn't seem to cause any valgrind errors.

**Comment by tepperly** [comment]
> Given #3081 is in next for testing, I think it won't be long (fingers crossed) before it is resolved in `master` and will probably beat opening a new PR.

That's terrific!

**Comment by tzanio** [comment]
Thanks for reporting this Tom, we are on it

**Comment by v-dobrev** [comment]
PR #3081 is now merged.
