### ISSUE TITLE
Ray element/face intersections

### ISSUE THREAD

**Issue by pshriwise** [mfem/mfem#3980]
Hi all. I'm a member of the OpenMC development team. We're interested in supporting unstructured mesh particle tracking on arbitrary element types and, as a result, require some robust intersection and element/face bounding routines to support ray tracing operations. 

@tzanio kindly pointed me to the [devilray](https://github.com/LLNL/devil_ray) project which has been subsumed by [Ascent](https://github.com/Alpine-DAV/ascent) during our discussion yesterday as a starting point.

My plan is to contribute intersection and bounding routines back into MFEM to support ours and other ray tracing applications on linear and higher-order elements.

If others are already working on this I'd love to touch base on progress and get involved if that would be helpful to you. I'd also welcome any guidance and feedback that the MFEM community might have on this work!

Related to #666.

**Comment by v-dobrev** [comment]
Hi @pshriwise,

This sounds great! Let us know if you have any questions about MFEM and its internals.

I looked at Devil Ray some time ago. I think they convert the geometry to Bernstein (we call it also "Positive") basis and work with that. Due to the positivity, the control points (we call them also "nodal coordinates", or "nodal dofs") define a bounding polyhedron which is useful for localization in the high-order case.

**Comment by tzanio** [comment]
ping: @mclarsen

**Comment by gridley** [comment]
Paging @owenmylotte

**Comment by owenmylotte** [comment]
@pshriwise Apologies that this slipped under my radar. I've implemented a ray tracing routine using mfem for arbitrary convex polyhedra. It is not very mature yet (probably won't abstract cleanly out of my code, and does not yet make use of the mfem device interface) but I can add you to the repository to see if it may be useful as a starting point. The most relevant functions live in the 'traversal' object, and the most recent version is on the 'c5g7' branch.

**Comment by pshriwise** [comment]
Hi @owenmylotte! Thanks for the notice. I haven't had much time to get this work, so a starting point like this is very welcome. Thank you for the invitation to your repository. I'll be sure to have a look soon.
