### ISSUE TITLE
`LinearForm` or `BilinearForm` sometimes do not assemble boundary integrator in a loop

### ISSUE THREAD

**Issue by dohyun-cse** [mfem/mfem#3983]
Hi, all

I created a boundary integrator `VectorBoundaryDirectionalMassIntegrator` and `VectorBoundaryDirectionalLFIntegrator` to assemble terms that appear in Robin type boundary condition for linear elasticity.

I need to solve the elasticity equation with different coefficient in a loop.
So, in a loop I create `LinearForm` and `BilinearForm`, add integrators, and assemble.
However, it seems that both `LinearForm` and `BilinearForm` does not assemble boundary integrator sometimes.

The minimal example is `examples/issue.cpp` in [this branch](https://github.com/mfem/mfem/tree/bugfix/skip-bdrintegrator).

**Comment by vladotomov** [comment]
Hi @dohyun-cse I looked over the example, but could you be more specific -- which boundary integrators are not assembled?

**Comment by dohyun-cse** [comment]
Hi @vladotomov . Both boundary integrators are not assembled (Specifically, `VectorBoundaryDirectionalMassIntegrator::AssembleFaceMatrix` and `VectorBoundaryDirectionalLFIntegrator::AssembleRHSElementVect` with `FaceElementTransformations` are not called when `a.Assemble()` or `b.Assemble()` are called.

I added logging to each of `AssembleFaceMatrix` and `AssembleRHSElementVect` so that I can ensure that each integrators are called during the assembly. The expected output of the loop at line 320 is:
```
i
4 4 RHSFace
5 4 RHSFace
4 4 LHSFace
5 4 LHSFace
```
where `i` is the iteration counter and each line represent boundary attribute, degrees of freedom, and which function is called.

My machine is MacBook Pro with M1 Max and g++ version
Apple clang version 15.0.0 (clang-1500.0.40.1)
Target: arm64-apple-darwin22.6.0
Thread model: posix

When I run this example, I get the following output.
```
(# Input, # Output) = (1, 1)
0
4 4 RHSFace
5 4 RHSFace

1
4 4 RHSFace
5 4 RHSFace

2
5 4 RHSFace

3
4 4 RHSFace
5 4 RHSFace

4
4 4 RHSFace
5 4 RHSFace

5
5 4 RHSFace

6
4 4 RHSFace
5 4 RHSFace

7
4 4 RHSFace
5 4 RHSFace

8
5 4 RHSFace

9
4 4 RHSFace
5 4 RHSFace
```
As you can see, the integrators added to `a` is not assembled at all, and the integrators added to `b` are not properly assembled at iteration 2, 5, and 8.

**Comment by dohyun-cse** [comment]
Oh, I just found out that I didn't call `mesh.SetAttributes()` after set boundary attributes. It now works as expected.
