### ISSUE TITLE
Bug in Mesh::GetBdrElementAdjacentElement2

### ISSUE THREAD

**Issue by JeremiahDBrown** [mfem/mfem#3985]
There are two distinct mesh functions that appear to be completely identical:
Mesh::GetBdrElementAdjacentElement and Mesh::GetBdrElementAdjacentElement2 seem to do the exact same thing.  I think the last two lines of Mesh::GetBdrElementAdjacentElement2 should be changed from:
`el   = fi.Elem1No;
info = fi.Elem1Inf + ori;`
to
`el   = fi.Elem2No;
info = fi.Elem2Inf + ori;`

**Comment by pazner** [comment]
This function has a strange (bad?) name that doesn't properly communicate its purpose (but the Doxygen comment does explain it). We do intend to improve this. There is some discussion in #3879.
