### ISSUE TITLE
`MapType` question

### ISSUE THREAD

**Issue by stefanhenneking** [mfem/mfem#3986]
If I understand the usage of MapType correctly, then it looks to me there may be a bug in the `MassIntegrator::AssembleElementMatrix2` implementation with `L2` scalar functions. The implementation appears to use shape functions evaluated in the reference domain (`CalcShape`) which for FE `MapType::INTEGRAL` does not apply the Piola transform. Should this be using `CalcPhysShape` instead? Perhaps I am missing something.

https://github.com/mfem/mfem/blob/110bec150762d363452c16c72cea7ab3a3bc6ec7/fem/bilininteg.cpp#L1343-L1344

**Comment by pazner** [comment]
That looks like a bug to me. It should probably be `CalcPhysShape` like in `MassIntegrator::AssembleElementMatrix`.

**Comment by stefanhenneking** [comment]
Thanks @pazner for confirming and for pushing the fix in the PR!

**Comment by tzanio** [comment]
Discussion continued in #3987
