### ISSUE TITLE
Shortcut to create an inner product?

### ISSUE THREAD

**Issue by juan42** [mfem/mfem#399]
Is there a quick way to build an inner product of a specific space between a Vector and the corresponding test function, besides defining a `LinearForm` and using a `GridFunctionCoefficient`?

There are the `GridFunction::Project*` functions, but I'm not sure whether they do the right thing, since i can not spot the integral part in the functions which would make them an inner product.

What i want mathematically is a map from a Vector in "a space" onto a Vector in the finite element space.

**Comment by tzanio** [comment]
Hi Julian,

If you need to approximate a (source) grid function from one space with a (target) grid function from another, then there are two popular options:

## Interpolation
If the source is smooth enough, you can evaluate it at the target degrees of freedom. In MFEM we call this `IdentityInterpolator`, see

https://github.com/mfem/mfem/blob/a9792d2f069cee73c2c5c4bd7020261bb6a943bd/fem/bilininteg.hpp#L2268-L2271

which can be used to construct a `DiscreteLinearOperator`, see

https://github.com/mfem/mfem/blob/a9792d2f069cee73c2c5c4bd7020261bb6a943bd/fem/bilinearform.hpp#L444-L474

This approach is simple and "local" but a) it does not conserve integral ("mass") and b) it may not be well-defined, e.g. when the source has multiple values in the target dofs.

## L2 projection
This requires inverting the mass matrix in the target space with r.h.s corresponding to the integrals (source, target_basis_funcitons).

One way to compute this r.h.s is as you suggested -- define a `GridFunctionCoefficient` for source and use a `LinearForm`.

Another option is to define the mixed mass matrix (source_basis_funcitons, target_basis_funcitons) and multiply it with source. That can be better if you need to do a lot of projections.

Both of the above assume that the source and the target are on the same mesh. When that's not the case, one needs a more general L2 projection that performs element intersection, see https://github.com/mfem/mfem/pull/315

Hope this helps,
Tzanio

**Comment by v-dobrev** [comment]
The short answer is: use a (Par)LinearForm with a GridFunctionCoefficient - this is probably the easiest way right now.

The long answer is: there are various ways to compute an inner product:
* If you have the corresponding bilinear form assembled, you can use BilinearForm::InnerProduct()
https://github.com/mfem/mfem/blob/c251b43828d0c818776213eebb3d7d75a4e364c9/fem/bilinearform.hpp#L175
or BilinearForm::FullInnerProduct()
https://github.com/mfem/mfem/blob/c251b43828d0c818776213eebb3d7d75a4e364c9/fem/bilinearform.hpp#L328
In parallel, if you have the assembled HypreParMatrix - there is no currently shortcut, so you need to use a matvec and then use
https://github.com/mfem/mfem/blob/c251b43828d0c818776213eebb3d7d75a4e364c9/linalg/hypre.hpp#L165
or
https://github.com/mfem/mfem/blob/c251b43828d0c818776213eebb3d7d75a4e364c9/linalg/vector.hpp#L427
* Using the corresponding linear form and wrapping one of the GridFunctions as a GridFunctionCoefficient - this is the option you mentioned.
* Another option is to use a "matrix-free" action, if the BilinearFormIntegrator implements the method AssembleElementVector()
https://github.com/mfem/mfem/blob/c251b43828d0c818776213eebb3d7d75a4e364c9/fem/bilininteg.hpp#L57-L59
(Unfortunately MassIntegrator does not implement that, at the moment.) If this method is implemented, then one can create a (Par)NonlinearForm and perform matrix-free matvec followed by an Euclidian inner product using either
https://github.com/mfem/mfem/blob/c251b43828d0c818776213eebb3d7d75a4e364c9/linalg/vector.hpp#L417
or
https://github.com/mfem/mfem/blob/c251b43828d0c818776213eebb3d7d75a4e364c9/linalg/vector.hpp#L427
* There is another option to compute inner products of the form `1/2 a(u,u)`, if the corresponding BilinearFormIntegrator implements the method GetElementEnergy()
https://github.com/mfem/mfem/blob/c251b43828d0c818776213eebb3d7d75a4e364c9/fem/nonlininteg.hpp#L67-L69
inherited from NonlinearFormIntegrator. (Unfortunately MassIntegrator does not implement that either, at the moment.) If it is implemented, one can construct a (Par)NonlinearForm and call the method GetEnergy()
https://github.com/mfem/mfem/blob/c251b43828d0c818776213eebb3d7d75a4e364c9/fem/nonlinearform.hpp#L76

Generally, computing an inner product has not been something needed often, so there is no convenient interface for it right now.

**Comment by juan42** [comment]
Thank you both for the comprehensive explanations. I think `BilinearForm::InnerProduct()` is convenient enough for me right now.
