### ISSUE TITLE
Is `mfem::MPI` required for a correct program that uses MPI and mfem?

### ISSUE THREAD

**Issue by victor-decaria-nnl** [mfem/mfem#3991]
I am wondering if it is valid to use MPI initialize and finalize calls manually rather than using `mfem::MPI`, or if this could cause unexpected behavior.

I have an mfem based program that uses MPI+CUDA+OpenMP(CPU). The OpenMP portion is a separate library that does not use mfem, and I do not build mfem with OpenMP enabled for now.

I recently heard that for an MPI program that uses threads to be valid, one must use `MPI_Init_thread` instead of `MPI_Init`. Currently, `mfem::MPI` only wraps `MPI_Init`. So from an mfem standpoint, I was wondering if I can manually manage MPI or if I should create a PR that also wraps `MPI_Init_thread`.

**Comment by tzanio** [comment]
This was actually addressed recently in https://github.com/mfem/mfem/pull/3081.

I believe you can just pass `MPI_THREAD_MULTIPLE` as a third argument of `Mpi::Init()`

**Comment by victor-decaria-nnl** [comment]
Thanks @tzanio , that PR has exactly what I wanted so I will close the issue.

**Comment by v-dobrev** [comment]
Just to clarify: the use of `mfem::Mpi` to initialize and finalize MPI is not required -- this class is just for convenience. Using standard `MPI_Init`/`MPI_Init_thread` and `MPI_Finalize` calls should work as well.
