### ISSUE TITLE
`AssembleDiagonalPA` not working correctly with boundary markers

### ISSUE THREAD

**Issue by stefanhenneking** [mfem/mfem#3998]
When using partial assembly with boundary integrators, `AssembleDiagonalPA` ignores boundary attribute markers passed to the integrator. Instead, it assembles the diagonal as if the bilinear form is being integrated over the whole boundary.

Can be reproduced by passing a boundary marker in the unit test "Mass Boundary Diagonal PA" as follows:

```
Array<int> bdr(mesh.bdr_attributes.Size());
bdr = 0; bdr[0] = 1;
...
blf_fa.AddBoundaryIntegrator(new MassIntegrator(coeff), bdr);
...
blf_pa.AddBoundaryIntegrator(new MassIntegrator(coeff), bdr);
```

Related PR that implements PA for boundary integrators #3539 @pazner

**Comment by tzanio** [comment]
Discussion continued in #4067
