### ISSUE TITLE
Incompressible NS equation

### ISSUE THREAD

**Issue by Watchmojo** [mfem/mfem#40]
Hi, 

Here is my code solving the incompressible NS equation using MFEM. A mesh for channel flow is also attached here. I added TIMES, ADD, SUBTRACT in gridfunction class. 
[NS_.zip](https://github.com/mfem/mfem/files/121005/NS_.zip)

This code is NOT fully debugged, but can be a good start if anyone wants to solve NS equation using MFEM. 

Hit: For low Reynolds number (say, Re<100), laminar solution can be obtained from this code. However, whenever the convection term is turned on, the code diverges. I have tried both 2/3 and 3/2 dealiasing methods. Neither of them worked. In Nektar++, spectral vanishing viscosity (SVV) or some smooth methods are implemented. 

Please let me know if anyone is interested to cooperate. Have a good CFD day. 

Thank you,
Frank

**Comment by jakubcerveny** [comment]
Hi Frank, 

I tried running the code but I'm only getting some NaNs with the default options, what is the right way to run it?

Jakub

**Comment by tzanio** [comment]
Hi Frank,

I also gave this a try with mfem-3.0.1 and got naNs:
```
> mpirun -np 4 ns
Options used:
   --mesh ../data/channel.mesh
   --boundary ../data/periodic-cube.bdr
   --order 4
   --Reynolds 2800
   --dt 1
   --nsteps 6
   --print 0
   --solverV 0
   --solverP 0
   --refine 0
   --tol 1e-09
   --fx 0.00412
   --fy 0
   --fz 0
   --visualization
Number of grids: 16464
Finished allocation1111
Finished allocation2222
Finished allocation
Finshed setting up solver
max con=  1.19532e-12
max con=  0
max con=  0
before pressure max_div = 3.8472e-12
istep     = 0  time=  0
Max div.  = nan
Total Time= 2.05728
Viscous   = 1.132
Pressure  = 0.92528
max u     = nan
max v     = nan
max w     = nan
max p     = 4.8209e-13
==========================
```
Is this the right way to run the code? (If not, can you please add some sample runs at the top of the file?)

Cheers,
Tzanio

**Comment by Watchmojo** [comment]
Hi, Tzanio and Jakub,

I had the same problem. You can turn off the convection term by replacing 299 with "if(false){". Without the nonlinear term, I observed correct results.

I suspect that some stabilization approach, such as streamline-upwind/Petrov±Galerkin (SUPG), is needed for high Reynolds number cases. However, I am still surprised about this requirement. Nek5000 is a spectral element method for incompressible flow, and it does not needed this kind of inefficient stabilization approach. Instead, Nek5000 just needs to filter (to one order lower GLL points) after each step. Since MFEM also using GL points, it should not give much difference. I tried filtering after each time step, and failed. 

I noticed that in the GetDerivative function, mpi communication is not conducted and derivatives on the overlapping faces of elements are only averaged with 0.5 weight. What if the neighbor elements have different size? Semtex uses mass to averaging. 

If someone can solve the nonlinear term instability, MFEM will be useful for turbulent simulation. 

Thank you,
Frank

**Comment by Watchmojo** [comment]
Hi, all,

Congratulations to the new release. 

I did notice that ex9 is solving a convective problem with a fixed convection velocity. For this example,  what are the differences between the following method?
1. Construct the advection matrix and uses explicit scheme for time marching.
2. Directly calculate v.grad(u), and let u_new =u_old+(v.grad(u_old))*dt

In my NS solver, I used the second method. Is there a problem here?

Thank you,
Frank

**Comment by tzanio** [comment]
Hi Frank,

Example 9 uses a discontinuous Galerkin formulation (u is discontinuous), which is much more stable for the advection equation than continuous Galerkin. I think you are correct that you need SUPG or other stabilization in the latter case, but another option might be to try DG instead -- is that feasible in this application?

Cheers,
Tzanio

**Comment by Watchmojo** [comment]
Hi Tzanio,

Thank you for your time.

I don't understand why DG can be used for incompressible flow, since incompressible flow is always continuous. 

Regards,
Frank

**Comment by tzanio** [comment]
Hi Frank,

It was just a suggestion. I'm not an expert in Navier-Stokes, so I'm not sure if DG is a good idea there or not :). I do know that for pure advection though, continuous Galerkin is really bad without stabilization.

Hopefully some of our other users can help with this. If the instability is resolved, it will be really nice to add this as one of the example codes (or miniapps) in MFEM.

Thank you for your contribution!
Tzanio

**Comment by Watchmojo** [comment]
Hi, Tzanio

I do know that DG is used for compressible flow in Nektar++ [http://www.nektar.info/]. To my best knowledge, DG is not suitable for incompressible flow. 

I have tried to filter the nonlinear term as in Nek5000 [https://nek5000.mcs.anl.gov/](url), but it does not work. If someone can implement some stabilization approach in MFEM, it would be great.

Thank you,
Frank

**Comment by lindsayad** [comment]
> To my best knowledge, DG is not suitable for incompressible flow.

DG and finite volume methods share similarities, indeed FV can be referred to as a reconstructed Discontinuous Galerkin (rDG) method. And FV is the foundation of most industrial CFD tools such as Star-CCM+/OpenFOAM etc.
