### ISSUE TITLE
How to pass additional cxx flags to the host compiler when CUDA is enabled?

### ISSUE THREAD

**Issue by adam-sim-dev** [mfem/mfem#4006]
Which flags in user.mk should I modify? BASE_FLAGS, OPTIM_FLAGS, DEBUG_FLAGS?

**Comment by v-dobrev** [comment]
You can modify any of the variables you mentoined. You can also use `CPPFLAGS` to just add extra compiler flags, or use `CXXFLAGS` to set all compiler flags overwriting the default.

When CUDA is enabled, and the flag you want to add is not understood by `nvcc` but it is for the host compiler, one should prefix the flag with `$(XCOMPILER)`, e.g. we do that for the flag `-Wall` in the default setting for `DEBUG_FLAGS`:
```makefile
DEBUG_FLAGS = -g $(XCOMPILER)-Wall $(BASE_FLAGS)
```
When CUDA is enabled, `XCOMPILER` will be set to `$(CUDA_XCOMPILER)` which is defined as
```makefile
CUDA_XCOMPILER = -Xcompiler=
```
