### ISSUE TITLE
How to synchronize shared dofs on a processor boundary?

### ISSUE THREAD

**Issue by ryanblack129** [mfem/mfem#4012]
Hello,

I am running into a situation where due to a point search algorithm, I compute the value of a shared dof located on a face/edge on a processor boundary that may not be on the master processor. Is there a way to synchronize the values of shared dofs between the processors that share that face/edge?

Thanks,
Ryan

**Comment by pazner** [comment]
Are you working with $H^1$ spaces? Given a `GridFunction`, I think you can do something like
```cpp
x.SetTrueVector();
x.SetFromTrueVector();
```
which should propagate the true DOF values to every sharing rank.

**Comment by ryanblack129** [comment]
Hi @pazner, 

Thanks for the quick reply. Yes, I am working with $H^1$ spaces. I had tried that but was not able to propagate the dofs values that way. Below is a small test case I ran:

Domain is a unit square. Mesh consists of 4 quads, on 2 processors the mesh is split into the top 2 quads and bottom 2 quads. The top 2 quads are on the master processor that owns the true dofs on the boundary x = 0.5. I manually set the values of the shared dofs on x = 0.5 for the bottom two quads (all set to 1) but it doesn't seem like the values were propagated to the master processor. See below (the first line are the local dofs before calling `SetTrueVector()` and `SetFromTrueVector()`, while the second line is true vector)

Proc containing bottom two quads:
![image](https://github.com/mfem/mfem/assets/56736259/f08ea501-bbae-45ef-8311-71631c63163d)


Proc containing top two quads:
![image](https://github.com/mfem/mfem/assets/56736259/5106504e-4978-4811-af04-cd99e6c8a673)


Domain:
![image](https://github.com/mfem/mfem/assets/56736259/ae24af10-b4f8-4e2a-9a27-393f63427428)

**Comment by pazner** [comment]
Ah, I see — if I understand correctly, you are trying to propagate DOFs from "sharing ranks" to the "master rank". What I describe will only synchronize from master to sharing ranks. Going the other way will be more complicated. It might require digging into the `GroupCommunicator`. Can you say a bit more about your use-case?

**Comment by vladotomov** [comment]
Something similar is done in _`Remhos`_, see [this](https://github.com/CEED/Remhos/blob/126706855c0173781f3fcd590595048d8850441c/remhos_tools.cpp#L457).

**Comment by ryanblack129** [comment]
Thanks so much for the help, I was able to get it working using the code above. I'll close the issue now
