### ISSUE TITLE
GPU support missing for some features

### ISSUE THREAD

**Issue by stefanhenneking** [mfem/mfem#4023]
I noticed the following features are currently only supported on host:

- `(Par)GridFunction::ProjectCoefficient`
- `(Par)GridFunction::ProjectGridFunction`
- `(Par)TransferMap::Transfer`

Is there anything in the works to support these on device? I'm using them within a time-stepping loop and they currently are the bottleneck (forcing DtoH / HtoD copies with Host execution in between).

**Comment by pazner** [comment]
Hi @stefanhenneking,

For `ProjectGridFunction` and `Transfer`, I don't know if there is anything currently in the works, but it would be a great addition, and not too difficult (in the case of meshes with only tensor-product elements, no variable $p$).

For `ProjectCoefficient`, this will depend very much on what type of `Coefficient` you have. For the most general coefficients, we are not set up for GPU acceleration (`Coefficient::Eval` is a host member function). What kind of `Coefficient` are you using?

**Comment by stefanhenneking** [comment]
For `Transfer` I found a simple workaround that performs well in the particular case I currently use where point-wise nodal values are transferred only -- then the mappings are injections or transposed injections which I can pre-compute on host and then transfer once on device (instead of using the `TransferMap` class).

In terms of coefficients, I am using `FunctionCoefficient` and `VectorFunctionCoefficient`.

If I'll only make `ProjectGridFunction` work, then that is fine, too (I only use `FunctionCoefficient` and `VectorFunctionCoefficient` for test cases). For device-computation with `pa` in mfem, I currently need tensor-product and uniform $p$ anyway.

**Comment by pazner** [comment]
For `FunctionCoefficient` and `VectorFunctionCoefficient`, the classes can't really set up for GPU evaluation (the functions would need to be `__host__ __device__`, etc.

You can do something like the following to evaluate functions on device:

```cpp
using RHSFunctionType = double(*)(const double *xyz);

template <RHSFunctionType F>
void ProjectRHS_(QuadratureFunction &qf)
{
   QuadratureSpaceBase &qs = *qf.GetSpace();
   Mesh &mesh = *qs.GetMesh();
   const IntegrationRule &ir = qs.GetIntRule(0);

   auto *geom = mesh.GetGeometricFactors(ir, GeometricFactors::COORDINATES);

   const int dim = qs.GetMesh()->Dimension();
   const int nq = ir.Size();
   const int N = qf.Size();

   const double *d_x = geom->X.Read();
   double *d_q = qf.Write();

   mfem::forall(N, [=] MFEM_HOST_DEVICE (int ii)
   {
      const int i = ii / nq;
      const int j = ii % nq;
      double xvec[3];
      for (int d = 0; d < dim; ++d)
      {
         xvec[d] = d_x[j + d*nq + i*dim*nq];
      }
      d_q[ii] = F(xvec);
   });
}
```

This projects the function onto a `QuadratureFunction`, but you could do the same with a `GridFunction`, using the `IntegrationRule` from `FiniteElement::GetNodes`.

**Comment by stefanhenneking** [comment]
Thanks, I'll try that out!

Closing this issue for now but will reference it if I start working on device support for `ProjectGridFunction` or `Transfer`.
