### ISSUE TITLE
MFEM doesn't compile with current libCEED

### ISSUE THREAD

**Issue by stefanhenneking** [mfem/mfem#4031]
MFEM doesn't compile with the current libCEED version, because of errors:
```
error: identifier "CeedChk" is undefined
```

This recently merged PR is probably the reason: https://github.com/CEED/libCEED/pull/1398

**Comment by tzanio** [comment]
ping: @jeremylt, @sebastiangrimberg

**Comment by sebastiangrimberg** [comment]
See https://github.com/mfem/mfem/pull/4032, I think this should fix it

**Comment by tzanio** [comment]
Thanks for the quick fix, guys!

**Comment by stefanhenneking** [comment]
Thanks!
