### ISSUE TITLE
mesh tangle during deformation

### ISSUE THREAD

**Issue by hedashua** [mfem/mfem#4039]
Dear mfem users:
I have seen in a literature that the linear elasticity method can achieve large mesh deformation, as shown in Figure 1, when the surface mesh is known, the new position of the internal point is calculated by specifying the displacement of the boundary point. I want to transform the pink face in the figure 2 into the yellow one, and Figure 3 is the result of mesh deformation. It can be seen that mesh have tangled. I wonder whether I can prevent this situation by imposing some constraints or other methods.
[A Simplified Mesh Deformation Method Using Commercial Structural Analysis Software.pdf](https://github.com/mfem/mfem/files/13715964/A.Simplified.Mesh.Deformation.Method.Using.Commercial.Structural.Analysis.Software.pdf)
![image](https://github.com/mfem/mfem/assets/103310466/a0308428-e34c-4c23-9a52-562759758cee)
![image](https://github.com/mfem/mfem/assets/103310466/70ae8ac0-36b7-4d45-ad7d-aeb4cc8b8be9)
![image](https://github.com/mfem/mfem/assets/103310466/5662b7c8-4f04-45a2-a7e5-a1e40925141d)

**Comment by kmittal2** [comment]
@hedashua you can try imposing the desired displacement incrementally with mesh optimization after each iteration. Have a look at our [mesh-optimization miniapp](https://github.com/mfem/mfem/blob/master/miniapps/meshing/pmesh-optimizer.cpp) if you want to try this approach.

**Comment by hedashua** [comment]
@kmittal2 thank you very much, it helps me a lot!
