### ISSUE TITLE
Force CMake to link SuiteSparse statically

### ISSUE THREAD

**Issue by Marshdweller** [mfem/mfem#4045]
Hello, everyone

I wonder which piece of the MFEM4.6's CMake-based building systems decides how to link SuiteSparse.
I do
```
cmake -DBLA_VENDOR=OpenBLAS -DCMAKE_LIBRARY_PATH=<path>/OpenBLAS-0.3.25/install/lib -DSuiteSparse_DIR=<path>/SuiteSparse-7.3.1 -DMETIS_DIR=<path>/metis-4.0.3 -DCMAKE_INSTALL_PREFIX=<path>/mfem-4.6/install ../
```
The output indicates that CMake uses shared libraries but I want static ones,

```
-- Looking for SuiteSparse ...
--    in SuiteSparse_DIR = <path>/SuiteSparse-7.3.1
-- SuiteSparse: UMFPACK: <path>/SuiteSparse-7.3.1/lib/libumfpack.so
-- SuiteSparse: KLU: <path>/SuiteSparse-7.3.1/lib/libklu.so
-- SuiteSparse: AMD: <path>/SuiteSparse-7.3.1/lib/libamd.so
-- SuiteSparse: BTF: <path>/SuiteSparse-7.3.1/lib/libbtf.so
-- SuiteSparse: CHOLMOD: <path>/SuiteSparse-7.3.1/lib/libcholmod.so
-- SuiteSparse: COLAMD: <path>/SuiteSparse-7.3.1/lib/libcolamd.so
-- SuiteSparse: CAMD: <path>/SuiteSparse-7.3.1/lib/libcamd.so
-- SuiteSparse: CCOLAMD: <path>/SuiteSparse-7.3.1/lib/libccolamd.so
-- SuiteSparse: config: <path>/SuiteSparse-7.3.1/lib/libsuitesparseconfig.so
```

Your help is appreciated.

Thank you,
M

**Comment by v-dobrev** [comment]
The logic for SuiteSparse is in the file `FindSuiteSparse.cmake` in `config/cmake/modules`. It uses the function `mfem_find_package` defined in `MfemCmakeUtilities.cmake` in the same directory. The names of the component libraries are given in `FindSuiteSparse.cmake` without the prefix `lib` and without extension, e.g. simply `umfpack`. One way to force static libraries is to replace `umfpack` with `libumfpack.a`.

Another option, if you don't want to modify the source code, is to set directly both `SuiteSparse_LIBRARIES` and `SuiteSparse_INCLUDE_DIRS` in the CMake configuration command.

**Comment by Marshdweller** [comment]
Ok, now I see. Thank you @v-dobrev

**Comment by Wayne901** [comment]
Hi, I'd like to use a direct solver in a MFEM code, and encountered an error when building MFEM with suitesparse.
Is MFEM_USE_SUITESPARSE only supported in parallel MPI version of MFEM? I assume so because `cmake -DMFEM_USE_SUITESPARSE=YES ../ ` give me an `METIS not found` error, and METIS is required only in parallel version [here](https://mfem.org/building/#parallel-build-using-metis-5:~:text=make%20all%20%2Dj-,Parallel%20MPI%20version%20of%20MFEM,-Download%20hypre%20and).

Best,
Wayne

**Comment by Marshdweller** [comment]
I believe the on-line manual is not synchronised with the actual build system.  MFEM needs Metis together with SuiteSparse in the non-Mpi configuration. You may check `mfem-4.6/config/modules/FindSuiteSparse.cmake`.  It shouldn't be super difficult to get rid of Metis,  though.

**Comment by Marshdweller** [comment]
For future reference I leave here the Bash script I run to install MFEM-4.6 / SuiteSparse-7.6 / OpenBLAS /Metis in the non-MPI configuration on Ubintu. The static linking of MFEM is enabled as per @v-dobrev suggestion.

```cmake
##########################################
#############   CMake 3.28  ##############  <----------SuiteSparse 7.6+ requires advanced CMake!
##########################################
CMAKE=${DEP_FOLDER}/cmake-3.28.3/build/bin/cmake
if [ "$INSTALL_CMAKE" = true ] ; then
  cd "${DEP_FOLDER}"
  wget -nc https://github.com/Kitware/CMake/releases/download/v3.28.3/cmake-3.28.3.zip
  rm -rf cmake-3.28.3
  unzip cmake-3.28.3.zip -d .
  cd cmake-3.28.3
  mkdir -p build
  cd build
  ../bootstrap -- -DCMAKE_USE_OPENSSL=OFF
  make -j 32
fi

echo ${CMAKE}

##########################################
################ OpenBLAS ################
##########################################
OpenBLAS_PATH=${DEP_FOLDER}/OpenBLAS-0.3.26
if [ "$INSTALL_BLAS" = true ] ; then
  cd "${DEP_FOLDER}"
  wget -nc https://github.com/OpenMathLib/OpenBLAS/archive/refs/tags/v0.3.26.zip
  rm -rf OpenBLAS-0.3.26
  unzip v0.3.26.zip -d .
  cd OpenBLAS-0.3.26
  mkdir -p build
  mkdir -p install
  cd build
  ${CMAKE} ../ -DCMAKE_INSTALL_PREFIX="${OpenBLAS_PATH}/install" -DCMAKE_BUILD_TYPE=Release
  ${CMAKE} --build . --config Release -j 32
  ${CMAKE} --install .
fi

##########################################
################   SuiteSparse ###########
##########################################
SuiteSparse_PATH=${DEP_FOLDER}/SuiteSparse-7.6.0
if [ "$INSTALL_SUITESPARSE" = true ] ; then
  cd "${DEP_FOLDER}"
  wget -nc https://github.com/DrTimothyAldenDavis/SuiteSparse/archive/refs/tags/v7.6.0.zip
  rm -rf SuiteSparse-7.6.0
  unzip v7.6.0.zip -d .
  cd SuiteSparse-7.6.0
  mkdir -p build
  cd build
  #SUITESPARSE_USE_FORTRAN=ON is needed to enable LAPACK interface in libopenblas.a
 #gfortran must be present in the system - because OpenBLAS includes Fortran-based Lapack
  ${CMAKE} -DBLA_VENDOR=OpenBLAS\
          -DCMAKE_LIBRARY_PATH="${OpenBLAS_PATH}/install/lib"\
          -DCMAKE_INSTALL_PREFIX="${SuiteSparse_PATH}"\
          -DSUITESPARSE_USE_CUDA=OFF\
          -DSUITESPARSE_USE_FORTRAN=ON\
          -DBUILD_STATIC_LIBS=ON\
          -DBUILD_SHARED_LIBS=OFF\
          -DSUITESPARSE_USE_OPENMP=OFF\
          -DSUITESPARSE_ENABLE_PROJECTS='suitesparse_config;mongoose;amd;btf;camd;ccolamd;colamd;cholmod;cxsparse;ldl;klu;umfpack'\
          ../
  ${CMAKE}  --build . --config Release -j 32
  ${CMAKE} --install .
fi

##########################################
################   Metis   ###############
##########################################
Metis_PATH=${DEP_FOLDER}/metis-4.0.3
if [ "$INSTALL_METIS" = true ] ; then
  cd "${DEP_FOLDER}"
  wget -nc https://github.com/mfem/tpls/raw/gh-pages/metis-4.0.3.tar.gz
  rm -rf metis-4.0.3
  tar -xzvf metis-4.0.3.tar.gz
  cd metis-4.0.3
  make
fi
##########################################
################   MFEM   ################
##########################################
MFEM_PATH=${DEP_FOLDER}/mfem-4.6
if [ "$INSTALL_MFEM" = true ] ; then
cd "${DEP_FOLDER}"
wget -nc https://github.com/mfem/mfem/archive/refs/tags/v4.6.tar.gz
rm -rf mfem-4.6
tar -xvzf v4.6.tar.gz
cd  mfem-4.6
cd config

# Replace file mfem-4.6/config/modules/FindSuiteSparse.cmake
# to enable static linking as per V. Dobrev suggestion
cat >tmp.txt <<EOL
include(MfemCmakeUtilities)
mfem_find_package(SuiteSparse SuiteSparse SuiteSparse_DIR "" "" "" ""
  "Paths to headers required by SuiteSparse."
  "Libraries required by SuiteSparse."
  ADD_COMPONENT "UMFPACK" "include;suitesparse" umfpack.h "lib" libumfpack.a
  ADD_COMPONENT "KLU" "include;suitesparse" klu.h "lib" libklu.a
  ADD_COMPONENT "AMD" "include;suitesparse" amd.h "lib" libamd.a
  ADD_COMPONENT "BTF" "include;suitesparse" btf.h "lib" libbtf.a
  ADD_COMPONENT "CHOLMOD" "include;suitesparse" cholmod.h "lib" libcholmod.a
  ADD_COMPONENT "COLAMD" "include;suitesparse" colamd.h "lib" libcolamd.a
  ADD_COMPONENT "CAMD" "include;suitesparse" camd.h "lib" libcamd.a
  ADD_COMPONENT "CCOLAMD" "include;suitesparse" ccolamd.h "lib" libccolamd.a
  ADD_COMPONENT "config" "include;suitesparse" SuiteSparse_config.h "lib" libsuitesparseconfig.a)

if (SuiteSparse_FOUND AND METIS_VERSION_5)
  message(STATUS " *** Warning: using SuiteSparse with METIS v5!")
endif()
EOL

  #mfem-4.6/config/tmp.txt ->  cmake/modules/FindSuiteSparse.cmake
  cp tmp.txt cmake/modules/FindSuiteSparse.cmake

cd ..
mkdir -p build
cd build
${CMAKE}  -DBLA_VENDOR=OpenBLAS \
          -DCMAKE_LIBRARY_PATH="${OpenBLAS_PATH}/install/lib" \
          -DSuiteSparse_DIR="${SuiteSparse_PATH}/include;${SuiteSparse_PATH}/lib" \
          -DMETIS_DIR="${Metis_PATH}" \
          -DCMAKE_INSTALL_PREFIX="${MFEM_PATH}/install" \
          -DMFEM_USE_SUITESPARSE=ON \
          ../
${CMAKE} --build . --config Release -j 32
${CMAKE} --install .


fi

```

**Comment by v-dobrev** [comment]
@Wayne901,

Yes, you can use SuiteSparse with a serial MFEM build.

MFEM does not require METIS for its serial build, at least not as a direct dependency. If you configure MFEM with SuiteSparse, and SuiteSparse needs METIS, then, of course, MFEM will need METIS because of SuiteSparse.

The reason you get the message "METIS not found" is because of the assumption we make -- that SuiteSparse was build with METIS. This assumption is made here: https://github.com/mfem/mfem/blob/70941b49b1217b638f4dfbb46b67662f86b54d10/config/defaults.cmake#L125-L126

You can disable this assumption by removing `METIS` from this list, e.g. by setting the flag `-DSuiteSparse_REQUIRED_PACKAGES=BLAS` in your cmake configuration command. Alternatively, you can edit the above file, `config/defaults.cmake`; or yet another way is to copy `config/defaults.cmake` to `config/user.cmake` and then make the changes in the latter file.

If your build of SuiteSparse does depend on METIS, then do not change the variable `SuiteSparse_REQUIRED_PACKAGES`. Instead, specify the path to METIS with the variable `METIS_DIR`.

Looking at recent versions of SuiteSparse, it looks like it now comes with METIS built-in, so I don't think you need to explicitly link with METIS. In other words, removing METIS from `SuiteSparse_REQUIRED_PACKAGES` is probably the right thing to do.

We should probably make this change to be the default, taking into account these latest developments in SuiteSparse.

**Comment by Wayne901** [comment]
Thank you Marshdweller and Dobrev, I followed your cmake script and suggestions, succesfully build MFEM-4.6 without METIS. For future reference, there's no `lib` in my OpenBLAS so I changed the `-DCMAKE_LIBRARY_PATH="${OpenBLAS_PATH}/install/lib"` to `-DCMAKE_LIBRARY_PATH="${OpenBLAS_PATH}/install/lib64"` in the MFEM cmake options. (May I ask what -CMAKE_LIBERARY_PATH means? I'm quite new to cmake file, didn't find it in deafults.cmake).
But unfortunately, MFEM_USE_SUITESPARSE is false in examples. When I use a umfpack solver as `UMFPackSolver umf_solver;`, 
the error `‘UMFPackSolver’ was not declared in this scope` shows. I'll try build mfem in DEBUG mode to see if there's more error info.

**Comment by Wayne901** [comment]
I found the problem, the cmake for a example find the old MFEM I built on my computer.
Although I export the $MFEM_DIR in ~/.bashrc and did the source, cmake still uses the old MFEM library.
I solved it when explicitly set the MFEM_DIR inside CMakeLists.txt.

**Comment by v-dobrev** [comment]
The variable `CMAKE_LIBRARY_PATH` is not specific to MFEM. It is used by any CMake project -- see the CMake documentation here: https://cmake.org/cmake/help/latest/variable/CMAKE_LIBRARY_PATH.html.

**Comment by Wayne901** [comment]
Thank you guys. Your answer helps me a lot.
