### ISSUE TITLE
get the gradient of the potential at one specific point

### ISSUE THREAD

**Issue by denislachapelle** [mfem/mfem#4051]
I have successfully get the voltage potential of a a microstrip. Now I would like to get the gradient of the potential at one specific point. How can I do this?

Thank you for your help.
Denis

**Comment by thartland** [comment]
One potential solution -- first obtain the gradient of the scalar potential with GradientInterpolator as in [ex24p](https://github.com/mfem/mfem/blob/master/examples/ex24p.cpp#L320). Then interpolate the ParGridFunction gradient as in [gslib/field-interp.cpp](https://github.com/mfem/mfem/blob/master/miniapps/gslib/field-interp.cpp).

**Comment by pazner** [comment]
Hi @denislachapelle,

Do you know which mesh element contains your point? If so, you can use `GridFunction::GetGradient` to evaluate the gradient at that point.

Otherwise, I would suggest first using `Mesh::FindPoints` to figure out the element and reference coordinates (or use `FindPointsGSLIB` for a more robust/performant algorithm).

**Comment by denislachapelle** [comment]
@thartland , @pazner ,

Thank you for your answers, in fact I end-up using Mesh::FindPoints and I compute the directional derivative by computing the difference between two GridFunction::GetValue at position p-delta, and p+delta in the desired direction. This may not be an excellent approach but for now it is what I have. I will change to using GetGradient in the next version.

If you feel curious you can look at the code [https://github.com/denislachapelle/mfemelectrostatic/blob/master/electrostatic.cpp](url)

Denis

**Comment by pazner** [comment]
Sounds good. Yes, I agree `GetGradient` will be better than the finite difference directional derivative calculation you're doing now.

Closing this for now. Feel free to re-open if there are other issues.
