### ISSUE TITLE
Parallel mesh with predefined mesh cuts

### ISSUE THREAD

**Issue by thorvath12** [mfem/mfem#406]
Hi,

I would like to create a parallel mesh out of a mesh object. I set the element attributes and I would like to make the cuts so that 1 processor gets exactly the partition with one attribute.

Is there an easy way of doing it? I can manually create the parallel mesh files and load them, but I was hoping for some nicer solutions.

Thanks in advance.
Tamas

**Comment by tzanio** [comment]
Hi Tamas,

If I understand correctly, you can simply use the following parallel mesh constructor:

```
ParMesh(MPI_Comm comm, Mesh &mesh, int *partitioning)
```

Here `partitioning` specify the MPI task that that will own each element of the serial `mesh` object, in your case you want to run in as many processors as number of attributes and  `partitioning[i]` will be the attribute of element `i` (possibly -1 as MPI tasks start from 0). 

Hope this helps,
Tzanio

**Comment by thorvath12** [comment]
Hi Tzanio,

Thanks a lot! It helped.

Regards,
Tamas

**Comment by tzanio** [comment]
Excellent! Let us know if you get some cool results :)
