### ISSUE TITLE
.inp (abaqus) > .mesh (mfem)

### ISSUE THREAD

**Issue by JiriTomcala** [mfem/mfem#407]
Hello,
is there some easy way to convert abacus input file (.inp) to mfem mesh file (.mesh)?
Thanks in advance.
Jiri.

**Comment by juan42** [comment]
If you have access to Cubit/Trelis you can import the Abaqus and export and exodusII file.

**Comment by JiriTomcala** [comment]
Thx a lot. I will try it.

**Comment by tzanio** [comment]
Did that work for you @JiriTomcala?

**Comment by tzanio** [comment]
Closing this issue now. Feel free to reopen if you still have questions...

**Comment by benzwick** [comment]
Are there any plans to add an Abaqus .inp reader (and possibly a writer) in the future? I have a lot of legacy code that uses this format and it would be nice not to convert everything.

**Comment by rcarson3** [comment]
@benzwick I'm not aware of any plans to add an Abaqus reader/writer to MFEM. If someone wanted to champion such a PR I'm sure we'd be open to it. In the mean time, you could look at maybe using a tool like https://github.com/nschloe/meshio to convert your Abaqus meshes over to one of the supported ones such as Exodus, GMSH, TetGen, or VTK.
