### ISSUE TITLE
Add Line heat sinks within control volume while solving a 3D thermal problem

### ISSUE THREAD

**Issue by rvignesh10** [mfem/mfem#4072]
I am trying to solve the 3D steady state heat conduction problem with Dirichlet and Neumann boundary conditions. But additionally, I also have line heat sources/sinks within the 3D solid. The heat source is thin and parameterized with a B-spline but its not included in the thermal solvers mesh. I am not sure how to set it up. Any help is appreciated. Thank you

**Comment by paul-hilscher** [comment]
Specifying a linear form on a line segments is to my knowledge not yet supported in mfem. However you might find [this comment](https://github.com/mfem/mfem/issues/3953#issuecomment-1783210464) helpful for a workaround.

**Comment by tzanio** [comment]
@termi-official, do you have any advice for @rvignesh10 ?

**Comment by termi-official** [comment]
1D-3D coupling is indeed a bit tricky (in every framework). I think easiest way would be to have a 3D mesh with fine elements near the 1D source and give the 1D source a finite thickness. This way you can take all quadrature points in the 3D mesh and search for the nearest 1D element. If the 1D element is smaller than the thickness of the element, then you can compute the source contribution coming from this 1D element. This way you will obtain a sound coupling, but it is a bit costly. Maybe it also needs to be paired with AMR if you need higher precision.

Alternatively you can setup the intersection between your extruded 1D element and the 3D element, such that you resolve the integrals over these, but this is needs a bit more effort in the implementation.

Does that help?
