### ISSUE TITLE
DenseMatrix::Eigenvalues documentation should specify that symmetry is assumed

### ISSUE THREAD

**Issue by gridley** [mfem/mfem#4074]
Hey all,

I'm writing an MFEM-based app (for the first time) and was a bit surprised to see the DenseMatrix::Eigenvalues and related methods appear to assume the matrix in question is SPD. It's nice that the error from LAPACK gets correctly reported, but IMO the documentation should point out that for nonsymmetric matrices, another approach should be used.

Just raising this issue so that others don't spend the unnecessary time discovering this. I will perhaps make a PR to update this documentation some time soon, or have the right LAPACK function get called.

**Comment by tzanio** [comment]
Hi @gridley,

An update to the documentation to point this out will be most welcomed, thanks in advance!

Tzanio
