### ISSUE TITLE
Weak enforcement of a Dirichlet boundary condition

### ISSUE THREAD

**Issue by thartland** [mfem/mfem#4092]
I am interested in a problem that involves solving (simultaneously) for two finite element functions. The first of which is defined over a domain $\Omega$ and the other is defined on the boundary $\partial\Omega$. Towards this end, I decided to first work on the (simpler) Poisson problem wherein the Dirichlet conditions are enforced weakly.

```math
\begin{align*}
\min_{u\in H^{1}(\Omega)}\mathcal{E}(u):=\int_{\Omega}(\frac{1}{2}\nabla u\cdot\nabla u-f \cdot u)\mathrm{d}V\\
\text{ such that } u=u_{\text{DC}} \text{ on } \partial\Omega. 
\end{align*}
```
The solution of this problem is the unique stationary point of the Lagrangian $\mathcal{L}(u,\lambda)=E(u)+\int_{\partial\Omega}\lambda\cdot(u-u_{\text{DC}})\mathrm{d}S$. That is $u,\lambda$ must satisfy

```math
	\begin{align*}
	\int_{\Omega}\nabla u\cdot\nabla \tilde{u}\,\mathrm{d}V+\int_{\partial\Omega}\lambda \,\tilde{u}\mathrm{d}S&=\int_{\Omega}f\,\tilde{u}\,\mathrm{d}V\\
	\int_{\partial \Omega}\tilde{\lambda}\,u\,\mathrm{d}S&=\int_{\partial \Omega}\tilde{\lambda}\,u_{\text{DC}}\,\mathrm{d}S
	\end{align*}
```
for each $\tilde{u},\tilde{\lambda}$ and then after discretizing

```math
\begin{align*}
\begin{bmatrix}
K & B \\
B^{\top} & 0
\end{bmatrix}
\begin{bmatrix}
u \\
\lambda
\end{bmatrix}
&=
\begin{bmatrix}
f \\ 
u_{\text{DC}}
\end{bmatrix}
\end{align*}.
```

I then wrote a code (see [here](https://github.com/mfem/mfem/files/14070481/weakDirichlet.txt)) to try to solve this Poisson problem but the computed solution $u(x,y)$ clearly did not resemble the manufactured solution $u(x,y) = \sin(\pi x)\sin(\pi y)$. I suspect that the source of the issue is that I have used `SubMesh` in a way that is not intended to be used. I am hoping to get clarity on this point and so specifically: 

Do you have any suggestions for how to set up a `MixedBilinearForm` where test functions are from a `FiniteElementSpace` defined over a domain $\Omega$ and the trial functions are from a `FiniteElementSpace` defined over the domain boundary $\partial\Omega$?

**Comment by atallah727** [comment]
Hey @thartland, you can solve this problem with Nitsche's approach whereby `u` is the only unknown given as follows: 
![Picture1](https://github.com/mfem/mfem/assets/95727890/2f260119-f1f2-40b0-8eef-dcaecc05c6bc)
where \gamma is a user defined constant (usually larger than 5) and `h` is the mesh size (you can check the `DGDiffusionIntegrator` in `bilininteg.hpp` for example to see how it is calculated. It is equivalent to what you have, but with
![Picture2](https://github.com/mfem/mfem/assets/95727890/7a55ad70-f90c-4d7f-9cf0-aa143354c1c6)
To assemble the boundary terms, you need to call the `AddBoundaryIntegrator` for your `LinearForm` and `BilinearForm`. If you want to solve the mixed form as in your equations, I would suggest you check `ex5p` which assembles and solves the Darcy equations. One thing though is I would add the following term to your first weak form
![Picture3](https://github.com/mfem/mfem/assets/95727890/33f377b2-e543-4041-a97a-6c9547a3d02b)
for stability reasons.

**Comment by vladotomov** [comment]
Why do you need `SubMesh` and a space on the boundary? Everything seems well defined if you just work on the original mesh.

**Comment by thartland** [comment]
Thanks @atallah727! I wasn't aware that the Lagrange multiplier could be determined from the Nitsche-based solution of the PDE, but that makes sense. I am interested in determining a Lagrange multiplier in the context of an optimization problem, so having the Lagrange multiplier be explicitly present in the problem is important.

@vladotomov, all that is needed is the boundary mass integrator and potentially an operator to restrict to the boundary dofs.  

I was able to resolve this issue [here](https://github.com/mfem/mfem/files/14078340/weakDirichlet3.txt).

Thanks for the input!
