### ISSUE TITLE
MFEM without boundaries

### ISSUE THREAD

**Issue by altineller** [mfem/mfem#4095]
Hello,

My datafile consists of 3d coordinates of vertices, and a list of hexahedrons, but however I have no boundary information.

Is it possible to paint these haxahedrons with a .sol or .gf file

Or, are boundaries in this context necessary?

Best Regards,

**Comment by v-dobrev** [comment]
You can leave the boundary empty by using
```
boundary
0
```
in the mesh file. With such input, MFEM will generate the boundary automatically. Typically, the boundary elements are used for imposing boundary conditions. In addition, in GLVis in 3D, the boundary elements are what is drawn initially when you open a mesh in GLVis.

**Comment by altineller** [comment]
> You can leave the boundary empty by using
> 
> ```
> boundary
> 0
> ```
> 
> in the mesh file. With such input, MFEM will generate the boundary automatically. Typically, the boundary elements are used for imposing boundary conditions. In addition, in GLVis in 3D, the boundary elements are what is drawn initially when you open a mesh in GLVis.

I have discovered boundary 0, and my file loads up, but I am unable to see any of the hexahedron cells since they don't have any boundaries defined. Is there any way to color the hexahedron cells without boundaries being defined?

Is there any view mode that shows individual cells? right now the external boundary is marked with a square, and inside is empty.

best regards,

**Comment by altineller** [comment]
I have modified my backend to generate boundaries for each cell.
