### ISSUE TITLE
How to extract all exterior boundary elements from a 3D given non-confirming mfem mesh

### ISSUE THREAD

**Issue by xujiangping** [mfem/mfem#4096]
Hello,

For a given hexahedron non-confirming mfem mesh, is there a way to extract all exterior boundary elements?  Just in serial case. Your help is highly appreciated!

Best Regards,

**Comment by tzanio** [comment]
Can you clarify what are you trying to do?

In particular are those "exterior boundary elements" the 6 faces of the hexahedron and what computations you need to perform with them?

Tzanio

**Comment by xujiangping** [comment]
I want to perform heat conduction of the 3D object (see the meshes in the uploaded figure). Its exterior boundry contacts with other object (the one in pink).
![Uploading heatconduction.png…]()

**Comment by xujiangping** [comment]
![heatconduction](https://github.com/mfem/mfem/assets/5434580/544005b4-3d57-4819-b215-a0c9b7b78b93)

**Comment by tzanio** [comment]
If those boundary elements are marked with a specific attribute in the mesh file then you can use that attribute in MFEM to e.g. impose boundary conditions or extract the surface as a submesh.

**Comment by xujiangping** [comment]
Thanks for your suggestion!  I will try it.
