### ISSUE TITLE
difference between a .sol and a .gf file

### ISSUE THREAD

**Issue by altineller** [mfem/mfem#4097]
Hello,

Is there a difference between a solution and gridfunction file?

In both files, in a defined FiniteElementCollection values for individual elements are given.

Can we apply some sort of function from a .gf file for the changing of an attribute of the element, such as color?

Best Regards,
C.

**Comment by tzanio** [comment]
Hi @altineller,

The solution is typically a `GridFunction`, so if I understand the questions correctly -- no, there is no difference.

If you have a piecewise-constant L2  `GridFunction`, its values will be plotted as constants over each element and so each value will specify an element "color".

Hope this helps,
Tzanio

**Comment by altineller** [comment]
Thank you. I have reversed the solver file format by trial and error and can now do scalar and vector. Best Regards.
