### ISSUE TITLE
Accessing LinearForm::boundary_integs_marker

### ISSUE THREAD

**Issue by aschaf** [mfem/mfem#4099]
Hi, is there currently a pull request implementing the missing getter-function for the `boundary_integs_marker` array of `LinearForm`? I did not realize that it was missing when I was fixing the constructor. Otherwise I would open a new PR and implement the `GetBLFI_Marker()` function.

Best regards,
Andreas

**Comment by tzanio** [comment]
I don't think there is an existing PR for this. Please feel free to create one, @aschaf!

**Comment by najlkin** [comment]
I have it implemented in [my fork](https://github.com/najlkin/mfem/), so I may do that if you wish 😉

**Comment by aschaf** [comment]
I'm fine with both, I just need to know. Thanks.

**Comment by aschaf** [comment]
@najlkin in which branch of your fork do you have the implementation?

**Comment by najlkin** [comment]
Ok, there were no updates, so I presume you are leaving it on us. I hope I have not discouraged you 😉 . I have made this PR for it: #4132  and I am closing this issue in its favor 🚀 .
