### ISSUE TITLE
Possible bug in ParSubMesh

### ISSUE THREAD

**Issue by ryanblack129** [mfem/mfem#4107]
Hi All,

I recently pulled from the master branch (last weekend) and now the `ParSubMesh` feature appears to not work in parallel. For example, see the multidomain miniapp

1 processor
<img width="566" alt="image" src="https://github.com/mfem/mfem/assets/56736259/492f95ac-4b0d-4fd3-9409-ca9a6f79b044">

5 processors
<img width="536" alt="image" src="https://github.com/mfem/mfem/assets/56736259/4763b082-554f-4f44-8318-f06db2358fda">

Best,
Ryan

**Comment by jandrej** [comment]
Could you try with older checkouts from master with a full rebuild? I'm also bisecting changes and try to reproduce the issue.

**Comment by ryanblack129** [comment]
Sure, no problem. I'll take a look

**Comment by tzanio** [comment]
Discussion continued in #4109

**Comment by tzanio** [comment]
Thanks for catching and reporting this @ryanblack129! Please check if #4109 resolves the issue.

**Comment by ryanblack129** [comment]
No problem, checking over the PR now
