### ISSUE TITLE
Integrating functions that depends on time and space

### ISSUE THREAD

**Issue by Durian-Ice** [mfem/mfem#4111]
Hi,

I am developing a numerical method for time-dependent PDEs. Given a function $f(x,t)$, I need to evaluate the following function $F$ for a fixed $T$:
$F(x) = \int_0^T f(x,t) dt$
where $x$ is in some domain $\Omega$.
I want to discretize this function $F$, so I have to evaluate $F$ at some selected nodes in a domain $\Omega$.
I assume that I would have to define an `std::vector<GridFunction>` to store the discretized $f$ at each time $t$,
and for each node $x$ integrate discretely the `GrdiFunction`s at each time node.
However, I could not find any MFEM resource that documents how to evaluate an integral of a function with respect to time.
I would very much appreciate any resource or comments that help me achieve this.

Best,
William

**Comment by pazner** [comment]
Hello @Durian-Ice,

At what points $t_i \in [0,T]$ do you have the values $f(x,t)$? Are they known at uniformly spaces points (e.g. from time-stepping), or could you evaluate $f(x,t)$ at some quadrature rule for $[0,T]$?

In either case, I would recommend just computing the quadrature approximation
$$\int_0^T f(x,t) \, dt \approx \sum_i w_i f(x,t_i),$$
where $w_i$ are appropriate weights (either from something like Gaussian quadrature or trapezoidal rule, etc.).

Note that you don't need to store $f(x,t_i)$ at every time point $t_i$, you can compute this approximation as a running sum.
