### ISSUE TITLE
how to specify boundaries for Dirichlet boundary conditions in mesh file for mfem

### ISSUE THREAD

**Issue by YHDAUT** [mfem/mfem#4112]
Hi, May I ask how can we specify boundaries which are assigned Dirichlet boundary conditions in the mesh file:

Array<int> u_ess_tdof_list;
Array<int> p_ess_tdof_list;

//elimiting essential boundary condition
ufespace->GetBoundaryTrueDofs(u_ess_tdof_list);
pfespace->GetBoundaryTrueDofs(p_ess_tdof_list);

For my application,   homogeneous Dirichlet boundary 
conditions are assigned on different parts of the boundary 
for ufespace and pfespace.  

Is it possible to specify these two parts in one mesh mesh for mfem? 

Thanks in avance

**Comment by atallah727** [comment]
Hello @YHDAUT,  you need to create "marker arrays" to define the portions of boundary associated with each type of boundary condition. These arrays have an entry corresponding to each boundary attribute.  Placing a '1' in entry i marks attribute i+1 as being active, '0' is inactive. For example, here is an example of a square where we impose Dirichlet conditions on sides 1 and 3:
```
Array<int> dbc_bdr_dir(pmesh->bdr_attributes.Max());
 dbc_bdr_dir = 0;  dbc_bdr_dir[0] = 1; dbc_bdr_dir[2] = 1;
```
Then you would need to call either `EliminateTrialDofs`, `EliminateTestDofs` to eliminate with the columns or rows, respectively, of your `ParMixedBilinearForm` passing `dbc_bdr_dir` as one of the input arguments. For `ParBilinearForm`, you need to call `EliminateEssentialBC`.

**Comment by YHDAUT** [comment]
Hi, @atallah727 . Many thanks  for your kind help. 

If I have two different assignments of Homoegeneous Dirichlet boundary conditions for primal and dual,  e.g., 

//for primal
Array<int> dbc_bdr_dir_primal(pmesh->bdr_attributes.Max());
 dbc_bdr_dir _primal= 0;  dbc_bdr_dir_primal[0] = 1; dbc_bdr_primal[1] = 1;dbc_bdr_primal[3] = 1;

//for dual 
Array<int> dbc_bdr_dir_dual(pmesh->bdr_attributes.Max());
 dbc_bdr_dir _dual= 0;  dbc_bdr_dir_primal[2] = 1; dbc_bdr_primal[2] = 1; dbc_bdr_primal[3] = 1;


Would it be possible to call something like in ex5p, such that both primal and dual 
get their essential dof lists, 

ufespace->GetBoundaryTrueDofs(u_ess_tdof_list);
pfespace->GetBoundaryTrueDofs(p_ess_tdof_list);

When forming the matrix in the mixed form,  we use these lists and  call

 mVarf->FormSystemMatrix(u_ess_tdof_list, A);
 bVarf->FormRectangularSystemMatrix(u_ess_tdof_list, p_ess_tdof_list, B);
 pVarf->FormSystemMatrix(p_ess_tdof_list, C);

For A (priaml) block, the same assignment of Dirichelt boundary conditions for both trial and test,  For C (dual) block, the same for both trial and test as well, and B is mixture..

Thanks

**Comment by atallah727** [comment]
Yes, you can customize the boundary conditions you want to enforce for each bilinear form block. One thing I noticed is in your code you wrote dbc_bdr_dir_primal[1] twice, I think the second instance of it should be doc_bdr_dir_dual.

**Comment by YHDAUT** [comment]
Hi @atallah727  Many thanks.  Yes, there were typos of boundary conditions for the dual. 

One thing I am not sure is how to pass the array dbc_bdr_dir_primal to ufespace in order to 
get u_ess_tdof_list?

is there something like this:

ParFiniteElementSpace *ufespace = new ParFiniteElementSpace(pmesh, fec, dbc_bdr_dir_primal) ?

Thanks..

**Comment by YHDAUT** [comment]
Hi @atallah727 ,   I am not sure if this is correct for including homogeneous boundary conditions correctly:

I have boundaries from a tetrahedral mesh :

boundary
12
3 2 0 3 7
3 2 0 7 4
3 2 1 2 6
3 2 1 6 5 
3 2 0 1 4
3 2 1 5 4
3 2 2 3 6
3 2 6 7 3
1 2 0 1 3 
1 2 1 2 3
2 2 4 5 7
2 2 5 6 7 

Does the integer in the first column indicate the boundary id?  I try to specify the homogeneous boundary conditions as:
 
Array <int> dbc_bdr_dir_primal(pmesh->bdr_attributes.Max());
dbc_bdr_dir_primal= 0; dbc_bdr_dir_primal[1] = 1; dbc_bdr_dir_primal[2] = 1;

where, the elements with index 1 and 2 are assigned as homgeneous dirichlet boundaries.   

Mostlikely, I misunderstand here:  dbc_bdr_dir_primal [*].  Here shall * be the numbering of boundary face? 


I then pass this vector to GetEssentialTrueDofs in order to generate dbc_bdr_dir_primal. 

ufespace->GetEssentialTrueDofs(u_ess_tdof_list, dbc_bdr_dir_primal);


Thanks a lot for your kind help.

**Comment by atallah727** [comment]
Hello @YHDAUT, you just need to pass the `dbc_bdr_dir_primal` to your integrator in order to assemble the relevant boundary terms. If you want a list of those dofs, you can check `ex1p`, but here is the relevant code.
                                                                              
```
   Array<int> ess_tdof_list;
   fespace.GetEssentialTrueDofs(dbc_bdr_dir_primal, ess_tdof_list);
```

**Comment by atallah727** [comment]
> Hi @atallah727 , I am not sure if this is correct for including homogeneous boundary conditions correctly:
> 
> I have boundaries from a tetrahedral mesh :
> 
> boundary 12 3 2 0 3 7 3 2 0 7 4 3 2 1 2 6 3 2 1 6 5 3 2 0 1 4 3 2 1 5 4 3 2 2 3 6 3 2 6 7 3 1 2 0 1 3 1 2 1 2 3 2 2 4 5 7 2 2 5 6 7
> 
> Does the integer in the first column indicate the boundary id? I try to specify the homogeneous boundary conditions as:
> 
> Array dbc_bdr_dir_primal(pmesh->bdr_attributes.Max()); dbc_bdr_dir_primal= 0; dbc_bdr_dir_primal[1] = 1; dbc_bdr_dir_primal[2] = 1;
> 
> where, the elements with index 1 and 2 are assigned as homgeneous dirichlet boundaries.
> 
> Mostlikely, I misunderstand here: dbc_bdr_dir_primal [*]. Here shall * be the numbering of boundary face?
> 
> I then pass this vector to GetEssentialTrueDofs in order to generate dbc_bdr_dir_primal.
> 
> ufespace->GetEssentialTrueDofs(u_ess_tdof_list, dbc_bdr_dir_primal);
> 
> Thanks a lot for your kind help.

the first integer in the boundary column is the boundary marker associated with that boundary edge/face (2D/3D).

**Comment by YHDAUT** [comment]
Thanks. @atallah727 .  It finally works out now...     I forgot to set dbc_bdr_dir_primal[ marker -1] = 1,  and mixed the order of two input arguments in fespace.GetEssentialTrueDofs(dbc_bdr_dir_primal, ess_tdof_list);

Best regards.
