### ISSUE TITLE
rotate a 2d field by 90 degree 

### ISSUE THREAD

**Issue by denislachapelle** [mfem/mfem#4118]
In the issue [1089](https://github.com/mfem/mfem/issues/1089)  @mlstowell wrote "To get the magnetic field from A_z you take its gradient and then rotate it by 90 degrees.".

I successfully get the gradient of the magnetic potential but I can't figure how to rotate by 90.

Can you explain how to rotate by 90 degree?

The gradient is computed using a RT finite element space and shown below. Once rotated I expect the arrow to point in the direction of the magnetic field which is supposed to circulated around the center rectangle having a current of 1A in z direction.
![image](https://github.com/mfem/mfem/assets/45741871/4aa5bca5-d24d-4d06-854d-f38c18e43927)
Thank you very much for your help,
Denis

**Comment by denislachapelle** [comment]
I have tried accessing the data vector of the grid function and swap elements x and y, but the resulting figure is not as expected.

Here D is the gridfunction with the gradient of the magnetic potential.

   Vector Data = D.GetTrueVector();
   {
      int Size = Data.Size();
      int vdim = D.VectorDim();
      assert(Size%vdim==0);
      double temp;
  
      for(int i=0; i<Size; i+=2) {
         temp=Data[i];
         Data[i]=Data[i+1];
         Data[i+1]=temp;
      }
   }
   GridFunction ROT90(&fespace_rt, Data);

**Comment by mlstowell** [comment]
Hi, @denislachapelle,

The rotation is deceptively simple but I should have mentioned how to do this. If A_z is computed as an H1 field then compute its gradient as a Nedelec field. The result should look exactly as you show above. The next step is to just copy the Nedelec DoFs to a Raviart-Thomas vector. In 2D (and only in 2D) these should have the same number of DoFs ordered in the same manner and the basis functions for the RT space (F) are equal to those of the ND space (W) but rotated using $F = \hat{z}\times W$. I may have the direction of the rotation incorrect so double check this and multiply by -1 if necessary.

Best wishes,
Mark

**Comment by mlstowell** [comment]
I should also mention that the reason to compute the gradient as a Nedelec field is that the Nedelec basis functions contain the gradients of the H1 basis functions so no global solve is necessary. The Nedelec gradient can be computed using a `LinearInterpolator` rather than a `BilinearForm` (see https://mfem.org/lininterp/) and no global solve will be necessary.

**Comment by denislachapelle** [comment]
Thank you for your answer. There should be something I get wrong....

I change the code and get the gradient of the potential ok in Nedelec FE space.
![image](https://github.com/mfem/mfem/assets/45741871/4ddf55d2-811f-440b-8ff8-ffb97f3d7c44)

Then I create another fe space based on RT using the following code.

   Vector Data( nd_fespace.GetVSize());
   D.GetTrueDofs(Data);
   RT_FECollection rt_fec(nd_order, dim);
   FiniteElementSpace rt_fespace(&mesh, &rt_fec);
   GridFunction ROT90(&rt_fespace, Data);

Note that D is the gridfunction of the nedelec fe space.

It compile and execute fine but the resulting ROT do not make sense.

Your help is greatly appreciated.
Denis

**Comment by mlstowell** [comment]
I always forget the reason for this but the RT space should use `nd_order-1`.

**Comment by tzanio** [comment]
It is confusing, but the standard terminology for the lowest-order spaces is `RT_0` and `ND_1`

**Comment by denislachapelle** [comment]
Its all work fine now. 

To get the gradient of the scalar field I use the GradientInterpolator as suggested in this issue and from example 24; the code snippet is shown below.

   ND_FECollection nd_fec(nd_order, dim);
   FiniteElementSpace nd_fespace(&mesh, &nd_fec);
   GridFunction D(&nd_fespace);
   DiscreteLinearOperator dlo(&Afespace, &nd_fespace);
   dlo.AddDomainInterpolator(new GradientInterpolator());
   dlo.Assemble();
   dlo.Mult(u, D);

To ratate by 90 degrees I copy the nedelec dofs to a raviart thomas dofs, as explain in this issue; the code is shown below.

   /*
   Note the order of RT FE is nd_order-1.
   */
   Vector Data( nd_fespace.GetVSize());
   D.GetTrueDofs(Data);
   RT_FECollection rt_fec(nd_order-1, dim);
   FiniteElementSpace rt_fespace(&mesh, &rt_fec);
   //Create a GridFunction for rt fe space with the dofs of the nedelec.
   GridFunction ROT90(&rt_fespace, Data);

Thank you for your help.
Denis
