### ISSUE TITLE
Problems with extending Joule example (noisy solution for electric potential)

### ISSUE THREAD

**Issue by Maatinski** [mfem/mfem#4122]
Hi all,
I want to use the Joule example as a starting point to model heating of complex coil geometries such as MRI gradient coils (eventually adding water cooling tubes, either via boundary conditions or more complex water flow modeling, but that's a bit further down the road).  

I've been generating some example meshes representing a simple coil loop with two ports (not too different from the coil.gen example) embedded in a sheet of ABS plastic. The idea is to model how the coil is heating up the ABS sheet, and test whether or not we need to include cooling mechanisms. My assumption is that the Joule example should be suitable to model this, even though the main contribution to the ABS sheet heating would be from heat conduction from the wire itself, rather than through eddy currents. The meshes are generated in Matlab and Tetgen, because ultimately I want to batch model a larger number of coil geometries (i.e., generate the meshes on the fly without too much manual labor).

![meshes](https://github.com/mfem/mfem/assets/63864061/51838989-e149-4785-8ba3-06dac6c18704)

I've been making pretty good progress, but I am seeing an odd behavior in the solution of the electric potential phi, i.e., the solution is very noisy. I tested this with serial and parallel runs but it didn't seem to make a difference. In the image below, I also left out the ABS sheet, i.e., only modeled the coil and the background air. I also used the same material parameters (el. conductivity, etc.) as in the Joule example. Units of the mesh are in meters.

![solution](https://github.com/mfem/mfem/assets/63864061/4c8e2730-ea78-4211-ab9c-d1bd25ad938b)

Any idea what could cause this behavior?

Big thanks,
Maatinksi

**Comment by mlstowell** [comment]
Hi, @Maatinski,
I've seen similar issues with tetrahedral meshes. I suspect this is a symptom of under-resolving the field. Often it is sufficient to increase the basis function order but you may need to refine the mesh outside the coil (the coils itself seems to be much finer).
Best wishes,
Mark

**Comment by paul-hilscher** [comment]
Hey @Maatinski , 

>  representing a simple coil loop with two ports

assuming those two ports are on the lower boundary and part of the coil (not sure what the two red circles are in your screenshot), then I would expect phi to be more gradual.

In my experience of modelling voltage-driven, solid coils one would only solve the electric potential **inside the coil** by specifying one port to V=0 and the other one to V=_Applied Voltage_. When phi is discretized using H1 you should get good results even in first order.

Here, one example how of I would expect the phi potential to look like (in the magnetostatic limit):
<img src="https://github.com/mfem/mfem/assets/118960216/867279c3-217c-49a7-89c0-711313e768b5" width=50% >

**Comment by Maatinski** [comment]
Hi @mlstowell and @paul-hilscher 

Thanks for the comments. I reran this problem with a mesh with better grading, but the results did not improve. I also double checked again that I am correctly defining material and boundary properties (compared to coil.gen) but I don't see a difference.
@paul-hilscher As for the boundary values, I am assigning +1V/-1V to the two wire ports, as in the Joule/coil.gen example. Looking at the phi solution, it does seem like these boundary values are set correctly. 

Mesh-explorer view of coil.gen example and my mesh:
![image](https://github.com/mfem/mfem/assets/63864061/371f745d-2463-4805-9879-d12555b9a833)

Mesh view in Matlab after improving mesh gradient (total of ~2M elements):
![image](https://github.com/mfem/mfem/assets/63864061/380efdbe-ceb1-4cd6-9c2c-8d7aa80fb683)

Solution of phi with order=2 elements:
![image](https://github.com/mfem/mfem/assets/63864061/aefaa35e-6a8a-4147-8ed2-6d820ae588ba)

**Comment by Maatinski** [comment]
A quick follow up: I've been playing with tons of other parameters (grading, element quality, serial vs. parallel runs, etc.) but nothing seemed to help. The one thing I did find though is the following error that occurs when enabling AMR refinement:

`MFEM abort: (r,c,f) = (786,887,956)
 ... in function: int mfem::STable3D::operator()(int, int, int) const
 ... in file: /autofs/space/p41trd3/p41trd3/mfem-4.6.1/general/stable3d.cpp:112`

I found some explanations on here ([#3478](https://github.com/mfem/mfem/issues/3478) [424](https://github.com/mfem/mfem/issues/424)) but I am not sure if I am missing requirements on how the mesh has to be formatted. Any thoughts on this?

Thanks a lot!

**Comment by Maatinski** [comment]
Another quick update:
The error seems to be related to the MFEM mesh version. If I switch from `v1.0` to `v1.x`, i.e., from the format
```
vertices
75685
3
-21.5000000 -33.0000000 -59.3100000
-21.5000000 -33.0000000 -58.3838000
...
```

to

```
vertices
75685
 
nodes
FiniteElementSpace
FiniteElementCollection: H1_3D_P1
VDim: 3
Ordering: 1
 
-21.5000000 -33.0000000 -59.3100000
-21.5000000 -33.0000000 -58.3838000
...
```

the error is gone. I was under the impression that for first-order meshes these two formats would lead to the same mesh, but I may be wrong. Let me know if I'm missing something.

Thanks,
Maatinski

**Comment by Maatinski** [comment]
Hi all,
things are starting to look good, finally able to run this for more complex problems (see below a run on a more representative coil geometry). This was solved for `order = 1` but on a much refined mesh for the wire. Two questions popped up though:

**1. Material attributes:**
I assume the attributes defined in the example correspond to the electrical conductivity `sigma`, thermal conductivity `Tcond`, and heat capacity `Tcap` but I am a bit confused by the values. Even if I convert everything to coherent units (looks like the coil.gen example is more like cm units) the values don't make sense to me. Am I missing something?

**2. Steady state solution:**
Is there any reason why I wouldn't be able to compute a steady-state solution for the heating part (of this would mean moving away from the transient operator)? I was thinking about integrating the Joule heating component for one sinusoidal cycle, and then assuming this quantity to be the constant driving term for heating (maybe scaled by a smaller duty cycle) for the steady-state heat problem. Any thoughts on this would be most welcome.

Thanks,
Maatinski

![gradient_heating](https://github.com/mfem/mfem/assets/63864061/da053acf-81f3-4d84-ad04-1241f426415e)

**Comment by Maatinski** [comment]
Hi all,
sorry that I keep bugging everyone about this. Still trying to figure out how the material values are handled. I tried running this with conventional values for the properties `mu`, `sigma`, `Tcond`, `Tcap`  but the results don't seem to make sense. At the same time the default values don't seem to make sense to me (especially the EM properties):

```
double mu = 1.0;
double sigma = 2.0*M_PI*10;
double Tcapacity = 1.0;
double Tconductivity = 0.01;
```
Also the scaling of thermal properties of the conductive wire relative to air seem odd (metal thermal conductivity should be greater than air, for example):
```
TcondAir   = 1.0e6  * Tconductivity;
TcapAir    = 1.0    * Tcapacity;
```

I am sure I am missing something fairly trivial, but any suggestion or hint would be greatly appreciated.
@mlstowell @tzanio Any thoughts on this?

Big thanks!!

**Comment by mlstowell** [comment]
Hi, @Maatinski,

I agree that the default values appear odd. I did not choose these values so I can only guess why they are set in this manner. I do have two ideas. First, I suspect the values were not chosen to represent a realistic situation but only to produce desired behavior i.e. liberties were taken. Second, I believe the developer was concerned with physical problems involving wires overheating due to induction. With this in mind consider the best case scenario where we can perfectly control the temperature at the surface of the wire (via some active cooling tech). How much heating of the wire is inevitable? Perhaps this was the scenario being modeled or perhaps they just wanted to see a temperature gradient inside the wire for aesthetic reasons. I really cannot say with any certainty.

Best wishes,
Mark

**Comment by Maatinski** [comment]
Hi @mlstowell 
thank you so much for the comment. That makes totally sense. Maybe it's worth adding a comment on this to the `joule` example to avoid confusion (or maybe it's just me who got confused). 
I also just retested this with realistic parameters: I think when I tested this initially I accidentally set incorrect values for the heat capacity (J/g °K rather than J/m^3 °K). Seems to be producing realistic results now.

Big thanks,
Mathias

**Comment by Maatinski** [comment]
Hi @mlstowell and others,
thanks again for the comments. Things are working pretty well now, but there is one piece I am having trouble with. I would like to calculate the total current flowing through either of the coil ports to relate the heating to the current rather than the voltage. Anything looking wrong with the code below? 
(the results don't seem correct, i.e., it's giving me too low of a current amplitude).

As always, big thanks!

```
// E - E-field in HCurlFESpace
// j - Current density in HCurlFESpace

// GET CURRENT DENSITY
//================================
ParBilinearForm ej(&HCurlFESpace);
ej.AddDomainIntegrator( new VectorFEMassIntegrator(*sigma) );
ej.Assemble();
ej.Mult( E, j );

// Or is this done through an Interpolator?
// ParDiscreteLinearOperator ej(&HCurlFESpace, &HCurlFESpace);
// ej.AddDomainInterpolator(new ScalarVectorProductInterpolator(*sigma));
// ej.Assemble();
// ej.Mult( E, j );

// INTEGRATE CURRENT ON PORT 1
//================================
ParLinearForm I_surf_int(&HDivFESpace);
VectorGridFunctionCoefficient Jv_gf(&J_gf);

// mask for the coil port 1
Array<int> bdr_attr(pmesh->bdr_attributes.Max());
bdr_attr = 0;
bdr_attr[0] = 1; // port 1

I_surf_int.AddBoundaryIntegrator(new BoundaryNormalLFIntegrator(Jv_gf), bdr_attr);
I_surf_int.Assemble();

ParGridFunction ones(&HDivFESpace);
ones = 1.0;

double I_port_1 = I_surf_int(ones);
```

**Comment by paul-hilscher** [comment]
> it's giving me too low of a current amplitude)
>// j - Current density in HCurlFESpace

the current for solid coils has two components: the eddy currents ($\sigma \partial_t \vec{A}$) and the coil source current ($\sigma \nabla \phi$). Do you include both ?

**Comment by Maatinski** [comment]
Hi @paul-hilscher ,
Thanks for the comment. Yes, I am including both (using similar workflow as in the `joule` example). The E-field magnitude and the heating power both seem good, I think the problem is in translating the E-field `E` to current density `j` and integration of the current density across the coil port boundary (i.e., something in the code in my previous comment).

**Comment by mlstowell** [comment]
Hi, @Maatinski,

I don't know if this is still an issue but here's how I would do this:

1) Compute J in H(Div) from E in H(Curl) using something like:
```
ParMixedBilinearForm ej(&HCurlFESpace, &HDivFESpace);
ej.AddDomainIntegrator( new VectorFEMassIntegrator(*sigma) );
ej.Assemble();
ParBilinearForm m(&HDivFESpace);
m.AddDomainIntegrator( new VectorFEMassIntegrator );
m.Assemble();
ej.Mult( E, j_dual );

... setup an iterative solver with a diagonal scaling preconditioner or something similar...
m_inverse.Mult(j_dual, J);
```
2) Prepare a linear form to integrate over the port exactly as you show above except use a `VectorCoefficient` which defines a unit normal vector field which pierces the surface of the port in the direction you choose to represent positive current flow. For example if your port is parallel to the yz plane and flow is in the positive x direction, you can use the following:
```
Vector xHatVec(3); xHatVec = 0; xHatVec[0] = 1;
VectorConstantCoefficient xHatCoef(xHatVec);

... setup ParLinearForm and attribute array
I_surf_int.AddBoundaryIntegrator(new BoundaryNormalLFIntegrator(xHatCoef), bdr_attr);
I_surf_int.Assemble();

double I_port_1 = I_surf_int(J);
```

Notes:
If you define J in H(Curl) then the J DoFs on the surface of the wire where sigma has a discontinuity will be lower than expected. This is because those DoFs are computed as a weighted average of the current density inside the wire and outside of it and presumably the current density is virtually zero outside the wire.

Solving for J in the manner I suggest above can be computationally expensive on a large mesh. If you only need J on the port this may seem excessive. Another, less expensive option is to compute J in H(Div) by interpolating E (and sigma). This can be done in various ways; using an interpolator matrix or a VectorGridFunctionCoefficient (then multiply by sigma). If the interpolation option is used I would recommend integrating over a surface which is at least a few elements from the end of the wire not on the end of the wire itself unless the port is part of the outer boundary of the mesh. This again avoids the discontinuity in sigma or any possible edge effects in the E field near the transition out of the end of the wire.


Best wishes,
Mark

**Comment by Maatinski** [comment]
Hi @mlstowell ,
thanks a lot for these suggestions and apologies for the late response; I had to put this aside for a few weeks due to some other deadlines. I will try to implement your suggestions soon and post some updates here.
Thanks a lot,
Mathias

**Comment by mdavids-cfs** [comment]
Hi @mlstowell ,
a quick follow-up to your suggestions above:
I tried to implement what you wrote in your point 1) but I think I may be missing something. `j_dual` looks like I would expect it, but `J` does not seem right, so I assume something is wrong in the code below (this is written in terms of the PyMFEM interface but I assume it's easy to interpret):

```
m = mfem.ParBilinearForm(HDivFESpace)
m.AddDomainIntegrator(mfem.VectorFEMassIntegrator())
m.Assemble()

j = mfem.ParGridFunction(HDivFESpace)
j.Assign(0.0)

# Same tdofs as for scalar potential solve?
ess_tdof_list = mfem.intArray()
ess_bdr = mfem.intArray(pmesh.bdr_attributes.Max())
ess_bdr.Assign(1)
ess_bdr[0] = 0 # Port 1
ess_bdr[1] = 0 # Port 2
HDivFESpace.GetEssentialTrueDofs(ess_bdr, ess_tdof_list)

# Set up operators with correct DoF's
A = mfem.HypreParMatrix()
B = mfem.Vector()
X = mfem.Vector()

m.FormLinearSystem(ess_tdof_list, j_dual, j, A, X, B)

# Preconditioner #2
prec = mfem.HypreDiagScale()
pcg_a1 = mfem.HyprePCG(A)

# Solver parameters
solver_tol = 1e-12
solver_max_iter = 500
solver_print_level = 2

# Set the PCG solver
pcg_a1.SetTol(solver_tol)
pcg_a1.SetMaxIter(solver_max_iter)
pcg_a1.SetPrintLevel(solver_print_level)
pcg_a1.SetPreconditioner(prec)
pcg_a1.Mult(B, X)

J = mfem.ParGridFunction(HDivFESpace)
J.Assign(0.0)
m.RecoverFEMSolution(X,j,J)
```

Anything obviously wrong? I will try to add a screenshot later, but maybe you see something obvious even without screenshot.
Big thanks in advance!

**Comment by mdavids-cfs** [comment]
Ok, I actually found the implementation in `ex34p.cpp` and realized I may have taken one confusing step that introduced some errors. I think it might be working now. I will check some of the quantitative current amplitudes and check if these agree with experiments.
 
https://github.com/mfem/mfem/blob/5f373e8c2a70acb413e0fb2a7c1be8054ab6079e/examples/ex34p.cpp#L620-L652
