### ISSUE TITLE
How to solve strerror_r issue in Cygwin?

### ISSUE THREAD

**Issue by rozerinyildiz23** [mfem/mfem#4124]
I want to run the "make serial -j" comment for MFEM in Windows. I use Cygwin as a terminal.  I follow this page to build MFEM and GLVis : [https://mfem.org/building/](url)
But I got this error:

``
In file included from fem/../mesh/mesh.hpp:25,
                 from fem/fespace.hpp:17,
                 from fem/gridfunc.hpp:16,
                 from fem/kdtree.hpp:16,
                 from fem/kdtree.cpp:12:
fem/../mesh/../general/zstr.hpp: In function ‘std::string strict_fstream::strerror()’:
fem/../mesh/../general/zstr.hpp:88:31: error: ‘strerror_r’ was not declared in this scope; did you mean ‘_strerror_r’?
   88 |    char* p = check_strerror_r(strerror_r(errno, &buff[0], buff.size()), &buff[0],
      |                               ^~~~~~~~~~
      |                               _strerror_r
``
Should I change something in the code as recommended in the error message? Or I need to add a package for this issue in Cygwin? Because in this way,  some of the errors were solved.

**Comment by tzanio** [comment]
Hi @rozerinyildiz23,

This looks like a compiler/C++ version issue. 

What version of MFEM do you use and what is the compiler in your Cygwin setup?

**Comment by rozerinyildiz23** [comment]
I use mfem-4.6 and g++ compiler in Cygwin.

**Comment by tzanio** [comment]
What's the output of `g++ --version`

**Comment by rozerinyildiz23** [comment]
The output is `g++ (GCC) 11.4.0`.

**Comment by tzanio** [comment]
I am not sure why are you getting this error.

It looks like there is `strerror_r` in [Cygwin's newlib](https://github.com/Cygwin/Cygwin/blob/master/newlib/libc/string/strerror_r.c) which is [available in `string.h`](https://github.com/cygwin/cygwin/blob/master/newlib/libc/include/string.h#L92-L109).

That being said, unless you are using compressed streams, you can probably modify that file without adverse effects.

Tzanio

**Comment by v-dobrev** [comment]
I posted a suggestion to try for Cygwin here: https://github.com/mfem/mfem/issues/3823#issuecomment-1942785872, before I saw this.

**Comment by v-dobrev** [comment]
After looking into this, it turns out the issue is the order of header inclusion in `general/kdtree.hpp` -- it does not include `config/config.hpp` before other headers and so the handling of Cygwin in `config/config.hpp` is not used correctly.

To fix the issue, simply add the line
```c++
#include "../config/config.hpp"
```
before the other includes here: https://github.com/mfem/mfem/blob/edcd7ee0ea823add4765d69d8f4b4cd2df843841/general/kdtree.hpp#L12-L21
