### ISSUE TITLE
HypreParMatrix::Threshold leads to memory problems

### ISSUE THREAD

**Issue by gelever** [mfem/mfem#413]
`Threshold` can lead to some memory issues. I'm using hypre-2.10.0b

For example, the following snippet leaks memory. Similar situations can crash the program.
```c++

#include "mfem.hpp"
#include <fstream>
#include <iostream>

using namespace std;
using namespace mfem;

int main(int argc, char *argv[])
{
    int num_procs, myid;
    MPI_Init(&argc, &argv);
    MPI_Comm_size(MPI_COMM_WORLD, &num_procs);
    MPI_Comm_rank(MPI_COMM_WORLD, &myid);

    SparseMatrix A(2, 2); 
    A.Add(0, 0, 1.0);
    A.Add(0, 1, 0.0);
    A.Add(1, 0, 0.0);
    A.Add(1, 1, 2.0);
    A.Finalize();

    HYPRE_Int row_starts[2];
    row_starts[0] = myid * 2;
    row_starts[1] = (myid + 1) * 2;

    HypreParMatrix A_par(MPI_COMM_WORLD, num_procs * 2, row_starts, &A);

    A_par.Threshold(1e-8);
}            
```
Valgrind will show a bunch of errors related to mismatch ```free()``` and ```delete[](void*)```.

**Comment by tzanio** [comment]
Hi @gelever, were you planning to propose a fix? (Asking because you self-assigned the issue.)

**Comment by gelever** [comment]
@tzanio I was not planning a proposal, I'm not sure how to fix it.

**Comment by tzanio** [comment]
Ok, thanks we will fix it :)

**Comment by liruipeng** [comment]
we recently implemented a similar function in hypre: hypre_ParCSRMatrixDropSmallEntries in a branch. it drops small entries based on row norms. maybe can just wrap the hypre function.

**Comment by v-dobrev** [comment]
That may be a better option than the current implementation. It's still good to fix the current implementation and keep it for compatibility with older versions of hypre.

**Comment by tzanio** [comment]
Does using `Destroy()` instead of `hypre_ParCSRMatrixDestroy(A)` in `HypreParMatrix::Threshold` fix the issue?

**Comment by gelever** [comment]
@tzanio 

`Destroy()` and re `Init` no longer leaks.  I'm not sure if this has any side effects:
```
   //ierr += hypre_ParCSRMatrixDestroy(A);
   Destroy();
   Init();

   A = parcsr_A_ptr;

   hypre_ParCSRMatrixSetNumNonzeros(A);
   hypre_MatvecCommPkgCreate(A);

   height = GetNumRows();
   width = GetNumCols();
```
