### ISSUE TITLE
TVD Limiter for Burgers Equation in DG Formulation

### ISSUE THREAD

**Issue by FH-9** [mfem/mfem#4131]
Hi,

I am trying to implement the TVD limiter given by Chen and Shu (2017) for 1D Burgers equation with a periodic mesh. The limiting procedure is as follows:

$\tilde{u}_0^{i} = \bar{u}^{i} - m(\bar{u}^{i} - u_0^{i}, \bar{u}^{i+1} - \bar{u}^{i}, \bar{u}^{i} - \bar{u}^{i-1})$,
$\tilde{u}_k^{i} = \bar{u}^{i} + m(u_k^{i} -\bar{u}^{i}, \bar{u}^{i+1} - \bar{u}^{i}, \bar{u}^{i} - \bar{u}^{i-1})$,
$\tilde{u}_j^{i} = \bar{u}^{i} + \theta (u_j^i - \bar{u}^{i})$ with $\theta = \frac{(\tilde{u}_0^{i} - \bar{u}^{i}) + (\tilde{u}_k^{i} - \bar{u}^{i})}{(u_0^{i} - \bar{u}^{i}) + (u_k^{i} - \bar{u}^{i})}$, $1 \le j \le k - 1 $

where $u_0^{i}, u_k^{i}, u_j^{i}$ are the degrees of freedom for the $i$-th element, $\tilde{u}_0^{i}, \tilde{u}_k^{i}, \tilde{u}_j^{i}$ are their limited values, $\bar{u}^i$ is an element average, and $\bar{u}^{i+1}, \bar{u}^{i-1}$ are the element averages for elements to the right and to the left, respectively, of the given element. $m$ is the minmod function.

As you can see, I need to access the element averages of the neighboring elements. I implemented the scheme following the methodology from #1821 and I get results with small-scale oscillations all over the solution (not limited to the shock). At first, I thought this could be due to an error in parallel implementation but I get the same thing in serial as well. Now my suspicion is that the element indexing could be the problem. I ran the following code to see the indices:
```
if (Mpi::Root())
   {
      const Table& element2element = pmesh->ElementToElementTable();
      Array<int> el2el;
      
      for (int i = 0; i < pmesh->GetNE(); i++)
      {
         element2element.GetRow(i, el2el);
         el2el.Print(cout << "Element " i << " neighbor indices: ");
      }
   }
```
And this is what I am getting:
```
Element 0 neighbor indices: 8 15
Element 1 neighbor indices: 9 14
Element 2 neighbor indices: 10 12
Element 3 neighbor indices: 11 13
Element 4 neighbor indices: 8 12
Element 5 neighbor indices: 9 13
Element 6 neighbor indices: 10 14
Element 7 neighbor indices: 15
Element 8 neighbor indices: 0 4
Element 9 neighbor indices: 1 5
Element 10 neighbor indices: 2 6
Element 11 neighbor indices: 3
Element 12 neighbor indices: 2 4
Element 13 neighbor indices: 3 5
Element 14 neighbor indices: 1 6
Element 15 neighbor indices: 0 7
```

There is no way of telling which neighbor is the left or the right neighbor for a given element. I also expected the indexing to be sequential, in which case I would at least be able to infer the correct ordering.
Is this the expected behavior? I feel like the ordering should have been sequential. Am I missing something? And is there a way to somehow infer whether an element is the left or right neighbor since it's crucial to the scheme?

Elements 7 and 11 in the snippet above, I assume, are the boundary elements for a given MPI rank. This piece of code was run at the beginning of the code before ExchangeFaceNbrData() is ever used. Is that the reason why one neighbor is not seen by these two elements?

When I run a test to see the neighbor indices from a different process inside my LimitSolution() function with ExchangeFaceNbrData() being called just prior to that, I am getting that for the process boundary elements the index of a neighbor in a different process before I subtract pmesh->GetNE() from it is either 16 or 17 (My mesh has 64 elements and I have 4 MPI processes. So 16 elements per process). I understand having 16 since it would be the 0th element (16-16 = 0) in the neighboring process. However, I don't understand how 17 is obtained. I would expect to have 31 (31-16=15) to get the 15th element of the neighboring process. This is all assuming local indexing is used for all MPI ranks. Is my reasoning correct or am I missing something again?

Finally, 16 or 17 is only obtained for the second index (indx2) in the following code:

```
element2element.GetRow(i, el2el);
indx = el2el[0];
indx2 = el2el[1];
```
I would have thought there would be one for each of the el2el entries in case of neighbor elements on different processes. I would appreciate if you could clarify this.

Thank you very much in advance,

Farhad

**Comment by vladotomov** [comment]
Hi @FH-9,

> Is this the expected behavior?

Yes it is; generally the element numbering is not sequential. It might be sequential in serial, when you don't refine the starting 1D mesh. 

> And is there a way to somehow infer whether an element is the left or right neighbor since it's crucial to the scheme?

For a given element, you can find its neighbors, and you can evaluate the upwind velocity at the corresponding faces. This is sufficient to define such differencing schemes. Unless you create a custom mesh, there is no notion of left/right/top/bottom in MFEM, as it assumes general unstructured meshes.

>  Is that the reason why one neighbor is not seen by these two elements?

Yes.

> Is my reasoning correct or am I missing something again?

In `ElementToElementTable()`, for MPI neighbors,  the indexing is offset by the number of local elements. So 16 would be the first neighbor element, 17 would be the 2nd neighbor element.

> Finally, 16 or 17 is only obtained for the second index (indx2) in the following code:

The MPI-neighbors are always at the end of the row since their indices are higher.

**Comment by FH-9** [comment]
Hi @vladotomov,

Thank you very much for clarifications.
I am still not clear on how to access the left and right neighbor averages though. I have defined 2 functions, UpdateParameters(Vector& y) and LimitSolution(Vector& y) which are used at the end of TimeDependentOperator::Mult(). UpdateParameters() gets the grid function for element averages, which is then used to exchange data with face neighbors. LimitSolution() is as follows:
```
void Burgers::LimitSolution(Vector& x) const
{
  Array<int> vdofs;
  Vector el_dofs;
  const Table& element2element = vfes->GetMesh()->ElementToElementTable();
  Array<int> el2el, nbrDofs;
  int indx, indx2;
  Vector nbr_mean1, nbr_mean2;
  double nbr_mean_left, nbr_mean_right;
  double theta, u0, uk;

  ParFiniteElementSpace* fes_0 = sol_mean.ParFESpace();
  
  for (int i = 0; i < fes_0->GetNE(); i++)
  {
    vfes->GetElementVDofs(i, vdofs);
    x.GetSubVector(vdofs, el_dofs);
    element2element.GetRow(i, el2el);
    indx = el2el[0];
    if (indx >= vfes->GetMesh()->GetNE())
    {
      indx -= vfes->GetMesh()->GetNE();
      fes_0->GetFaceNbrElementVDofs(indx, nbrDofs);
      sol_mean.FaceNbrData().GetSubVector(nbrDofs, nbr_mean1);
    }
    else
    {
      fes_0->GetElementVDofs(indx, nbrDofs);
      sol_mean.GetSubVector(nbrDofs, nbr_mean1);
    }
    indx2 = el2el[1];
    if (indx2 >= vfes->GetMesh()->GetNE())
    {
      indx2 -= vfes->GetMesh()->GetNE();
      fes_0->GetFaceNbrElementVDofs(indx2, nbrDofs);
      sol_mean.FaceNbrData().GetSubVector(nbrDofs, nbr_mean2);
    }
    else
    {
      fes_0->GetElementVDofs(indx2, nbrDofs);
      sol_mean.GetSubVector(nbrDofs, nbr_mean2);
    }
   // nbr_mean_left =   nbr_mean1(0); This is where I am stuck
   // nbr_mean_right =   nbr_mean2(0); 

    u0 = el_dofs(0);
    uk = el_dofs(el_dofs.Size() - 1);
    el_dofs(0) = sol_mean(i) - minmod(sol_mean(i) - el_dofs(0),
                                      nbr_mean_right - sol_mean(i),
                                      sol_mean(i) - nbr_mean_left);
    el_dofs(el_dofs.Size() - 1) = sol_mean(i) +
                                  minmod(el_dofs(el_dofs.Size() - 1) - sol_mean(i),
                                  nbr_mean_right - sol_mean(i),
                                  sol_mean(i) - nbr_mean_left);
    theta = (el_dofs(0) - sol_mean(i) +
            el_dofs(el_dofs.Size() - 1) - 
            sol_mean(i)) / 
            (u0 - sol_mean(i) + uk - sol_mean(i));
    for (int k = 1; k < el_dofs.Size() - 1; k++)
    {
      el_dofs(k) = sol_mean(i) + theta * (el_dofs(k) - sol_mean(i)); 
    }
    x.SetSubVector(vdofs, el_dofs);
  }
}
```
Am I on the right track here? I am not sure how to relate nbr_mean1 and nbr_mean2 obtained as above to the left and right averages. Is there any way to achieve this with this code?
Regarding your comment about upwinding at faces, it seems to me to use that I would have to iterate over faces instead of elements. But then how would I perform element-wise operations to limit DOFs at each element since that requires the knowledge of both neighbors at the same time?

Thank you.

**Comment by vladotomov** [comment]
> I am not sure how to relate nbr_mean1 and nbr_mean2 obtained as above to the left and right averages. Is there any way to achieve this with this code?

A fast way to do it in 1D is to check the centers (coordinates) of your elements -- something like:
```
auto Tr = pmesh.GetFaceNbrElementTransformation(e);
auto ip = Geometries.GetCenter(Geometry::SEGMENT);
Tr->Transform(ip, coord);
```
The proper way (for any dimension) would be to use `ElementToFaceTable`, then form `FaceElementTransformations`, which would give you the elements on both sides and the face velocity.

**Comment by FH-9** [comment]
Thanks. That was helpful. I am getting better results now but the small-scale oscillations still persist. I wanted to see what the degrees of freedom are with something like:
```c++
int myrank;
MPI_Comm_rank(MPI_COMM_WORLD, &myrank);
if (i == 2 && myrank == 3)
{
    el_dofs.Print(cout);
}
```

I am seeing sometimes large negative values. I do not understand how this is possible since my initial condition and solutions at any time step are always positive and I am not seeing any large swings in the plot as well. Getting negative values for degrees of freedom doesn't seem right. Or is there something I am missing? And could these negative values be somehow related to the small-scale oscillations that I am getting?  

I have attached the snapshot of the solution at $t = 2$ for $u=0.25 + 0.5 sin(\pi x)$ here.

Thank you.
<img width="312" alt="Screenshot 2024-02-15 at 12 54 39 PM" src="https://github.com/mfem/mfem/assets/148477105/b1abcf4e-8506-4dc7-9257-c6c98c4998ab">

**Comment by FH-9** [comment]
Thank you. That was helpful. The issue can be closed now.
