### ISSUE TITLE
more than three dimensional  FEM ?

### ISSUE THREAD

**Issue by AIBSCT80** [mfem/mfem#4140]
Hi,  May I ask if MFEM can perform fem  higher than three dimension?

Thanks

**Comment by tzanio** [comment]
Not with the official release, but there is a 4D branch: https://github.com/mfem/mfem/tree/4d_dev.

**Comment by AIBSCT80** [comment]
Thanks a lot @tzanio . It seems this branch is about 3 years old.   I saw in the examples: 

ex1_4d.cpp, 
ex3_4d.cpp,
ex4D_DivSkew.cpp

These seem 4D test examples.   

Thank you for pointing out this resources.  It is very helpful!

**Comment by aschaf** [comment]
Hi @AIBSCT80, what is your application of interest for 4D fem?

**Comment by AIBSCT80** [comment]
Thank you aschaf,  This is really a great help. I will try this and report soon. Many thanks.  Is there also a routine to visualize the simulation results on 4D meshes in one of those examples?

**Comment by aschaf** [comment]
I think there are none in the PR, but I recall implementing a visualization routine. I will look for it and post it here.

**Comment by aschaf** [comment]
I found some code, however it only can crudely visualize cuts with the xyz-hyperplane for uniformly spaced points `0 <= x_4 <= T`. Would that be something you need?

**Comment by AIBSCT80** [comment]
Hi Aschaf,  it is not urgent to visualize the solutions.  I first need some time to practice the 4D fem code for the laplace in high dimension. This will take a while.  Many thanks.

**Comment by psaber09** [comment]
Hello @aschaf. I am a graduate student at Penn State, under the supervision of Dr. David Williams. I am looking to add high-order functionality to the 4d_dev branch. Would you be willing to setup a Zoom meeting to further discuss?

**Comment by IdoAkkerman** [comment]
@psaber09 @aschaf FYI: It has been on the back burner a bit but I am still interested as well.
I would be interested in adding 4 NURBS (also the Hdiv and Hcurl variety)

**Comment by aschaf** [comment]
Hi @psaber09, sure. When do you have time? I am in CEST, so I guess we have a 6h difference.

**Comment by psaber09** [comment]
@aschaf, sorry for the delay. Would next week 4pm CEST either Monday, Tuesday or Thursday work?

**Comment by psaber09** [comment]
@aschaf 5pm CEST also works

**Comment by aschaf** [comment]
@psaber09 No problem, however I am quite busy this week, lets aim for next week Wednesday, if that would still work for you.

**Comment by psaber09** [comment]
My advisor is traveling next week and I would like him to be able to attend. Could be meet either May 28th or May 29th?

**Comment by aschaf** [comment]
Sure no problem, lets aim for May 29th at 4pm CST?

**Comment by psaber09** [comment]
@aschaf Great, If you provide an email address I will send a meeting invite with a zoom link.

**Comment by psaber09** [comment]
@aschaf maybe we can communicate easier over email, you can reach me at pfs5290@psu.edu
