### ISSUE TITLE
miniapps navier

### ISSUE THREAD

**Issue by EzinneN** [mfem/mfem#4143]
Hi,

I am trying to modify the navier miniapps to adapt it my problem.

My domain is a quadrangle with an square obstacle inside. I would like to set Dirichlet boundary conditions for the velocity u at the entrance (Inlet, left side of the domain) and for the pressure at the exit (say Outlet at the right side of the domain).

So far, I changed the function vel_shear_ic with the values of my problem and I created a instance Array<int> attr and set 
- attr[0] = 1; //inlet
- attr[2] = 1; //outlet
- attr[3] = 1; //obstacle

I then called the function AddVelDirichletBC like this flowsolver.AddVelDirichletBC(vel_shear_ic, attr) to set the boundary conditions but nothing happens, it seems no calculation is done

Using Partial Assembly
        It   Resid      Reltol
MVIN     0   0.00e+00   1.00e-12
PRES     0   0.00e+00   1.00e-06
HELM     0   0.00e+00   1.00e-08
       Time          dt
1.00000E-03 1.00000E-03
        It   Resid      Reltol
MVIN     0   0.00e+00   1.00e-12
PRES     0   0.00e+00   1.00e-06
HELM     0   0.00e+00   1.00e-08
       Time          dt
2.00000E-03 1.00000E-03
        It   Resid      Reltol
MVIN     0   0.00e+00   1.00e-12
PRES     0   0.00e+00   1.00e-06
HELM     0   0.00e+00   1.00e-08

Because for there are two components for the velocity and only the normal is not equal to 0, I tried to use the function ProjectBdrCoefficientNormal like this  u_ic->ProjectBdrCoefficientNormal(u_excoeff,attr);
But again, nothing happens.

Can you tell me what to change?

**Comment by jandrej** [comment]
It would be most helpful to post a minimal failing example that I can look at. We can iterate from there.

**Comment by EzinneN** [comment]
I was able to fix some parts but there I still have issues to solve my problem and get expected results.

I am writing below the parts I modified:

In the vel_shear_ic procedure, I only consider boundary condition at the Inlet, it is for the velocity. The normal component is set to 1.48 and the tangent component is set to 0. So u=(1.48,0).   

`void vel_shear_ic(const Vector &x, double t, Vector &u)
{
   double xi = x(0);
   double yi = x(1);

   if (xi <= 1e-8){
        u(0) = 1.48;
        u(1) = 0;
    }

}`

In the main file, I realise I do not use the procedure void vel_shear_ic! 

I modified this part:
 
` NavierSolver flowsolver(pmesh, ctx.order, ctx.kinvis);
  flowsolver.EnablePA(true);

   Vector zero_vec(2);
   zero_vec[0] = 1.48;
   zero_vec[1] = 0.0;
   VectorConstantCoefficient Zero_vec(zero_vec);

   Array<int> attr(pmesh->bdr_attributes.Max());
   attr[0] = 1; // Inlet is attribute 1.
 
   ParGridFunction *u_ic = flowsolver.GetCurrentVelocity();
   u_ic->ProjectBdrCoefficientNormal(Zero_vec,attr);`

![Screenshot_20240222_152852](https://github.com/mfem/mfem/assets/104771105/ec91df18-0144-4b91-ac76-bc3173777110)
![Uploading Screenshot_20240222_152852.png…]()

The code is running without error. However, it does not seem like the boundary conditions are properly initialized. For example, if you like I the screenshots, the boundary at t=0 is not the same everywhere along the y axis at x=0 (left border) with values ranging from  4.6e-5 to 1.5e-4. In addition, the values around (or just outside) the circle do not have the same values at the initialization.


![Screenshot_20240222_154433](https://github.com/mfem/mfem/assets/104771105/3d936538-680b-452f-b969-aa78f53fe595)
![Screenshot_20240222_154455](https://github.com/mfem/mfem/assets/104771105/416c9108-18b8-460d-a126-b6bce354f528)

**Comment by jandrej** [comment]
With `ProjectBdrCoefficientNormal` you're projecting the normal component of the coefficient to the boundary. `ProjectBdrCoefficient` is the right thing to use here.

**Comment by EzinneN** [comment]
Thank you very much. I was also able to make some changes, including adding the boundary condition for the pressure (at the outlet) and I started to get some results. 

I modified the code again and was able to get the value conditions I wanted for the boundary conditions for the pressure, I fixed it at 10 at the right boundary (attr[1]=1).

The coordinates of my mesh goes from 0 to 0.06 on the x axis and 0 to 0.024 on the y axis.

The procedures are defined as follows:

``
void vel_shear_ic(const Vector &x, double t, Vector &u)
{
   double xi = x[0];
   double yi = x[1];

   if (xi <= 1e-8){
        u[0] = 1.48;
        u[1] = 0;

    else{
        u[0] = 0.0;
        u[1] = 0;
    }
}


double pres_shear_ic(const Vector &x, double t)
{
   double xi = x(0);
   double p = 0.0;

   if(xi>0.058){
       p=10.0;
    }
   return p;
}

``

And in the main file, I wrote this: 
``
   pmesh->GetBoundingBox(p_min,p_max);
   p_min.Print(std::cout);
   p_max.Print(std::cout);

   NavierSolver flowsolver(pmesh, ctx.order, ctx.kinvis);
   flowsolver.EnablePA(true);


    // Set the initial condition.
   ParGridFunction *u_ic = flowsolver.GetCurrentVelocity();
   VectorFunctionCoefficient u_excoeff(pmesh->Dimension(), vel_shear_ic);
   u_ic->ProjectCoefficient(u_excoeff);

   FunctionCoefficient p_excoeff(pres_shear_ic);
   Array<int> attr_v(pmesh->bdr_attributes.Max());
   Array<int> attr_p(pmesh->bdr_attributes.Max());
   attr_v = 0;
   attr_p = 0;
   attr_v[0] = 1; //inlet is attribute 0
   attr_p[1] = 1; //outlet is attribute 1
   flowsolver.AddVelDirichletBC(vel_shear_ic, attr_v);
   flowsolver.AddPresDirichletBC(pres_shear_ic, attr_p);
``
The issue I have is for the rest of the domain, the pressure and velocity are not set to 0. Can you please tell me how to set them to 0?

In addition, I do not get a results as there is no convergence? Do you know how to fix it?

![Screenshot_20240223_163211](https://github.com/mfem/mfem/assets/104771105/c8c0cdeb-65cc-4136-ab00-39e08b3e44f0)
![Screenshot_20240223_164128](https://github.com/mfem/mfem/assets/104771105/86542595-178e-47b6-a59a-ab3a93d6d64c)
![Screenshot_20240223_164149](https://github.com/mfem/mfem/assets/104771105/4fe0ec8a-27a9-401a-bf4f-f2f256228fa7)

![Screenshot_20240223_164108](https://github.com/mfem/mfem/assets/104771105/8d0d2733-9b02-4bb5-a9cd-6c01110b45c0)

**Comment by jandrej** [comment]
Your problem is not well defined. You have to think about all other boundary conditions as well.

**Comment by jandrej** [comment]
You are setting the dirichlet attribute to zero meaning they're now open boundaries aka you're implying "zero neumann"

**Comment by EzinneN** [comment]
This is what I want to do! I should maybe mention this works with finite volume method. For the velocity, I want Dirichlet BC at the Inlet and the Obstacle and for the pressure, I want Dirichlet BC at the Outlet. The other BC are Neumann BC set to 0. 
attr_v[0]=1;
attr_v[2]=1;
attr_p[1]=1;

But I believe my problem lies in how I initialise the pressure as it is the same everywhere despite the fact I set Dirichlet BC on the outlet. The code is the same as in the previous comments. It seems if I do not set Dirichlet BC for the pressure at the inlet (and thus let Neumann BC be set to 0), the pressure is going to be the same everywhere. I have the same problem also for the velocity.
