### ISSUE TITLE
How to generate the right-hand side using an analytical solution?

### ISSUE THREAD

**Issue by utah2015** [mfem/mfem#4144]
Hi，
       I want to replace the excitation source with the product of a coefficient matrix and an exact solution vector when solving the Maxwell equations. In other words, I would like to obtain the linear system as Ax=b, b=A0x0, where x0 is the exact solution.   How can I achieve this? 
I implemented it in the following way but did not get the correct solution x,
```
a0 = new ParBilinearForm(pfes);
a0->AddDomainIntegrator(new DiffusionIntegrator(*src_cf));
a0->AddBoundaryIntegrator(new MassIntegrator(*src_cf),rbc_bdr);
a0->Assemble();
x0 = new ParGridFunction(pfes);
x0->ProjectCoefficient(*x0_cf);
a0->Mult(*x0,*b);
```

**Comment by v-dobrev** [comment]
You can also take a look at example 27 which illustrates the use of various non-homogeneous b.c. Here's a short description: https://mfem.org/examples/#ex27.

**Comment by utah2015** [comment]
Thanks a lot for your reply.
This bug was caused by my neglect of the handling of the boundary coefficient. I obtained the correct result by modifying the code: 
src_bc_cf = new ProductCoefficient(*src_cf_,*abc);
a0->AddBoundaryIntegrator(new MassIntegrator(*src_bc_cf),rbc_bdr);
