### ISSUE TITLE
Bdr attributes with ParSubMesh

### ISSUE THREAD

**Issue by ryanblack129** [mfem/mfem#4145]
Hello,

I am trying to use the `ParSubMesh` feature to extract a fluid (channel - block and beam) and solid domain (beam) from the following problem setup

![image](https://github.com/mfem/mfem/assets/56736259/38045a75-4778-4009-9e8f-3fe875c2ccae)

Everything seems to work properly in serial, however in parallel I get different results depending on the number of proc. For example, plotting a constant function on the fluid-solid interface (bdr attr 7) on the parent mesh, fluid submesh, and solid submesh

![image (14)](https://github.com/mfem/mfem/assets/56736259/e6cd0e53-28bf-462e-ab91-70f87fa16770)

Zooming in on the parent mesh

![image (15)](https://github.com/mfem/mfem/assets/56736259/6784c540-b484-4cb1-b46b-d0fe9560ec37)

It looks like its missing a few bdr elements in the global mesh and solid submesh, and when I print out the bdr attribute arrays for the submeshes the solid submesh has an extra bdr attribute

![image (11)](https://github.com/mfem/mfem/assets/56736259/b1336be1-d3c2-4feb-b0fe-884ed52c4643)

I am thinking there may be a bug or I am setting something up incorrectly? I've attached a minimal example and the mesh

Thanks,
Ryan

[test_parsubmesh.zip](https://github.com/mfem/mfem/files/14365106/test_parsubmesh.zip)

**Comment by jandrej** [comment]
See https://github.com/mfem/mfem/blob/navier-urans/miniapps/navier/examples/navier_fsi.cpp#L417

**Comment by ryanblack129** [comment]
Thanks so much for pointing me to this, I will take a look and get back to you

**Comment by ryanblack129** [comment]
I've checked through the example and made some updates to my test problem, but still running into the same issue. Perhaps it is an invalid mesh file (I made it in GMSH)?

Would it be possible to share the mesh file for the above example to try out?

**Comment by jandrej** [comment]
Here you go [fsi.msh.zip](https://github.com/mfem/mfem/files/14380506/fsi.msh.zip)

**Comment by ryanblack129** [comment]
Thanks for sending, I setup the same test problem and unfortunately run into the same issues. Everything is fine in serial and up to 4 processors, then when running on 5 processors an extra bdr attribute is generated for the beam

![image](https://github.com/mfem/mfem/assets/56736259/e4f5f26b-8e13-4c40-9dac-79d5dbbb943f)

Resulting in an incomplete fluid-solid interface:
![image](https://github.com/mfem/mfem/assets/56736259/46d7a35e-03ee-4e62-8a39-4b0faf7c5f95)

The element that goes bad turns out to be on a processor boundary (generated using mesh-explorer and default partitioning method)
![image](https://github.com/mfem/mfem/assets/56736259/c17bf949-cc01-4837-b9a4-cdb5fa883523)

**Comment by jandrej** [comment]
The only fluid solid interface attribute for the mesh I posted is attribute 5 (array index 4). What am I missing?

**Comment by ryanblack129** [comment]
I think whats happening is when the solid domain is extracted using ParSubMesh and the bdr attributes are being transferred from parent to submesh, some of the bdr elements labeled 5 are being missed and the code is reaching this line 
https://github.com/mfem/mfem/blob/9a21f59e60b20d8a0cdde2af8d55be75dbc27bb2/mesh/submesh/psubmesh.cpp#L285

and generating an attribute 8. Additionally, I am not sure why this would also effect the parent mesh. Below I am plotting a constant function on the fluid-solid interface (5) using ProjectBdrCoefficient for the solid submesh and the parent mesh for the 5 processor case

solid beam:
![image](https://github.com/mfem/mfem/assets/56736259/97030cc5-58d7-4db1-b468-704a5b1545ba)

parent mesh:
![image](https://github.com/mfem/mfem/assets/56736259/c9daa7a9-a982-46f6-85b9-1e9b2c9b57a1)

**Comment by jandrej** [comment]
Can you provide a small failing example code? You have to be careful how you project those functions.

**Comment by ryanblack129** [comment]
Sure no problem, thanks for looking into this

```
#include "mfem.hpp"

using namespace mfem;
using namespace std;

void func(const Vector &x, double t, Vector &u)
{
   u.SetSize(x.Size());
   u = 0.0;
   
   u(0) = 1.0;
   u(1) = 0.0;
}

void VisualizeField(socketstream &sock, const char *vishost, int visport,
                    const ParGridFunction &gf, const char *title,
                    int x = 0, int y = 0, int w = 400, int h = 400,
                    const char *keys = NULL, bool vec = false);

int main(int argc, char *argv[])
{
   //////////// Initialize and parameters ////////////////
   
   // Initialize MPI and HYPRE.
   Mpi::Init(argc, argv);
   int num_procs = Mpi::WorldSize();
   int myid = Mpi::WorldRank();
   Hypre::Init();

   int order = 1;
   int ser_ref_levels = 0;

   Mesh *mesh = new Mesh("fsi.msh", 1, 1);
   int dim = mesh->Dimension();
   int fsi_num = 4;
   mesh->SetCurvature(order);

   // Refine the mesh to increase the resolution.
   for (int lev = 0; lev < ser_ref_levels; lev++) { mesh->UniformRefinement(); }

   ParMesh *pmesh = new ParMesh(MPI_COMM_WORLD, *mesh);
   delete mesh;
   pmesh->SetAttributes();
   pmesh->EnsureNodes();
   
   // setup attribute arrays labeling fluid and solid elements

   /*
      NOTE: For submesh class, attribute array should be organized like

      attr size = pmesh->attributes.Size()

      Say fluid mesh is labeled 1

      fluid_attr[0] = 1; // in the 0th spot put the label

      Say solid mesh is labeled 2

      solid_attr[1] = 2; // in the 1st spot put the label
   
   */

   Array<int> fluid_attr(pmesh->attributes.Max());
   fluid_attr[0] = 1; // fluid elements are labeled 1

   Array<int> solid_attr(pmesh->attributes.Max());
   solid_attr[0] = 2; // solid elements are labeled 2

   // FSI interface
   Array<int> fsi_attr(pmesh->bdr_attributes.Max());
   fsi_attr = 0;
   fsi_attr[fsi_num] = 1; 

   // Submeshes
   ParSubMesh fluid_mesh = ParSubMesh::CreateFromDomain(*pmesh,fluid_attr);
   fluid_mesh.SetAttributes();
   fluid_mesh.EnsureNodes();
   Array<int> fluid_fsi_attr(fluid_mesh.bdr_attributes.Max());
   fluid_fsi_attr = 0;
   fluid_fsi_attr[fsi_num] = 1;

   ParSubMesh solid_mesh = ParSubMesh::CreateFromDomain(*pmesh,solid_attr);
   solid_mesh.SetAttributes();
   solid_mesh.EnsureNodes();
   Array<int> solid_fsi_attr(solid_mesh.bdr_attributes.Max());
   solid_fsi_attr = 0;
   solid_fsi_attr[fsi_num] = 1;

   if (Mpi::Root())
   {
      std::cout << "--------------\n";
      std::cout << "Fluid Mesh: " << std::endl;
      std::cout << "Bdr attributes = " << std::endl;
      fluid_mesh.bdr_attributes.Print();

      std::cout << "--------------\n";
      std::cout << "Solid Mesh: " << std::endl;
      std::cout << "Bdr attributes = " << std::endl;
      solid_mesh.bdr_attributes.Print();
   }   

   H1_FECollection gfec(order,pmesh->Dimension());
   ParFiniteElementSpace gfes(pmesh,&gfec,pmesh->Dimension());
   ParFiniteElementSpace ffes(&fluid_mesh,&gfec,fluid_mesh.Dimension());
   ParFiniteElementSpace sfes(&solid_mesh,&gfec,solid_mesh.Dimension());

   ParGridFunction global_gf(&gfes);
   global_gf = 0.0;

   ParGridFunction fluid_gf(&ffes);
   fluid_gf = 0.0;

   ParGridFunction solid_gf(&sfes);
   solid_gf = 0.0;   

   ///////////////////////////////////////////////////////////////////////////////////
   socketstream sout, sout2, sout3;
   char vishost[] = "localhost";
   int  visport   = 19916;
   int Ww = 500, Wh = 500; // window size
   int Wx = 0, Wy = 0; // window position

   VectorFunctionCoefficient func_coeff(pmesh->Dimension(),func);
   fluid_gf.ProjectBdrCoefficient(func_coeff,fluid_fsi_attr);

   VisualizeField(sout, vishost, visport, fluid_gf, "Fluid Mesh: Fluid-Solid Interface",
                     Wx, Wy, Ww, Wh, "Rcj");

   solid_gf.ProjectBdrCoefficient(func_coeff,solid_fsi_attr);

   VisualizeField(sout2, vishost, visport, solid_gf, "Solid Mesh: Fluid-Solid Interface",
                     Wx, Wy, Ww, Wh, "Rcj");

   global_gf.ProjectBdrCoefficient(func_coeff,fsi_attr);

   VisualizeField(sout3, vishost, visport, global_gf, "Global Mesh: Fluid-Solid Interface",
                     Wx, Wy, Ww, Wh, "Rcj");
   
   delete pmesh;

   return 0;
}

void VisualizeField(socketstream &sock, const char *vishost, int visport,
                    const ParGridFunction &gf, const char *title,
                    int x, int y, int w, int h, const char *keys, bool vec)
{
   ParMesh &pmesh = *gf.ParFESpace()->GetParMesh();
   MPI_Comm comm = pmesh.GetComm();

   int num_procs, myid;
   MPI_Comm_size(comm, &num_procs);
   MPI_Comm_rank(comm, &myid);

   bool newly_opened = false;
   int connection_failed;

   do
   {
      if (myid == 0)
      {
         if (!sock.is_open() || !sock)
         {
            sock.open(vishost, visport);
            sock.precision(8);
            newly_opened = true;
         }
         sock << "solution\n";
      }

      pmesh.PrintAsOne(sock);
      gf.SaveAsOne(sock);

      if (myid == 0 && newly_opened)
      {
         sock << "window_title '" << title << "'\n"
              << "window_geometry "
              << x << " " << y << " " << w << " " << h << "\n";
         if ( keys ) { sock << "keys " << keys << "\n"; }
         else { sock << "keys maaAc"; }
         if ( vec ) { sock << "vvv"; }
         sock << endl;
      }

      if (myid == 0)
      {
         connection_failed = !sock && !newly_opened;
      }
      MPI_Bcast(&connection_failed, 1, MPI_INT, 0, comm);
   }
   while (connection_failed);
}
```

**Comment by jandrej** [comment]
You're on a recent master branch right?

**Comment by jandrej** [comment]
See https://github.com/mfem/mfem/pull/4151

**Comment by ryanblack129** [comment]
Just updated to the most recent version of master and added in the above changes. Unfortunately, I'm still seeing the same issue. On 5 processors it seems ok now, but I'm still seeing an extra bdr attribute (8) for the solid beam submesh. Also, going to higher number of processors causes similar behavior as before. Below is with 10 proc. 

![image](https://github.com/mfem/mfem/assets/56736259/719b205c-05b9-481a-8756-a97f3ffb9a4c)

Solid submesh:
![image](https://github.com/mfem/mfem/assets/56736259/ece39939-773a-46dc-a90e-e9d37de33940)

Fluid submesh:
![image](https://github.com/mfem/mfem/assets/56736259/14c89148-35d1-4d57-aa99-5e9066a1d2ed)

**Comment by jandrej** [comment]
Try this. You're using the list for submeshes incorrectly.

```
   Array<int> fluid_attr(1);
   fluid_attr[0] = 1;

   Array<int> solid_attr(1);
   solid_attr[0] = 2;
```

**Comment by ryanblack129** [comment]
No luck, still the same result

**Comment by jandrej** [comment]
Now it looks like a Submesh bug to me. I'm trying to figure out how to solve that next week.

**Comment by najlkin** [comment]
Also look here #4128 , internal boundaries are sometimes generated when loading `ParMesh` from files 😮 . By coincidence, it also happened originally with a `ParSubMesh` in #4083 , which was saved to files and then loaded. However, I am not sure about the attributes, so it might not be related...

**Comment by jandrej** [comment]
@ryanblack129 The combination of https://github.com/mfem/mfem/pull/4113 and https://github.com/mfem/mfem/pull/4151 will fix the issues mentioned here.

**Comment by ryanblack129** [comment]
Thank you so much, those PRs fixed the issue for me
