### ISSUE TITLE
Alternate Norm definition for IterativeSolvers

### ISSUE THREAD

**Issue by sethwatts** [mfem/mfem#4146]
In #3448, I asked about solving a positive semi-definite system with a known, low-dimensional null space. The suggested solution was to create a wrapping `Operator` around the system that manually removed the projection of the vector into the null space, i.e., to project into the system range space.

This worked very well for the small problems I was considering at the time, but I have found it does not work as well as the problem size scales. I believe the problem may be due to the fact that `IterativeSolver` implements a non-virtual Euclidean `Norm`function that (implicitly) measures contributions to the residual from the null space of the range space projected `Operator`, which we in general do not expect to decrease.  As a result, the solver uses the specified max number of iterations without converging, although a manual check I do on the projected final residual shows it has an acceptable residual, and therefore should have returned at some earlier iteration.

The cleanest modification, I think, would be to make `IterativeSolver::Norm` virtual so that I can override it in a derived type, e.g. a `class MySpecializedLBFGSSolver : public LBFGSSolver`. Would you agree? If so, I can open a PR making the change.

**Comment by v-dobrev** [comment]
We have something like that in a draft branch, `solver-monitor-controller`, (see diff here: https://github.com/mfem/mfem/compare/master...solver-monitor-controller) that allows derived classes from `IterativeSolverMonitor` to be used to indicate early convergence using any kind of logic they want. We use that to change the stopping criterion of CG to be relative $\ell_2$ norm reduction of the residual. The branch is fairly early draft but I believe it can be extended to `LBFGSSolver` and other iterative solvers to allow more general stopping criteria. Take a look if you want and let us know what you think.

**Comment by sethwatts** [comment]
Thanks for linking that branch. I agree the `HasConverged` method would fix the performance issue I have with taking unnecessary steps by allowing a manual "early" return. On the other hand, the norm values reported (when requested) will be nonsensical - admittedly a lesser concern. 

Could this be an "either or both" fix where I could override the current `Norm` and use standard convergence criteria, and/or use custom criteria?

**Comment by v-dobrev** [comment]
I don't see a problem with making `IterativeSolver::Norm` virtual, if you want to have the option to override it.

**Comment by sethwatts** [comment]
I will open a PR doing this next week. Thank you for the feedback.
