### ISSUE TITLE
Marking / Deleting internal boundaries

### ISSUE THREAD

**Issue by altineller** [mfem/mfem#4147]
Hello,

I have generated my own mesh, but I have internal boundaries. How can I use mfem to delete internal boundaries that is not at the surface of the mesh?

Best Regards,
Can

**Comment by tzanio** [comment]
Hi Can,

Do you have internal "boundary" face elements (which you can just mark with a different attribute and just not include in linear/bilinear forms), or do you have a disjoint mesh that you want to "glue" across such internal boundaries?  

Tzanio

**Comment by v-dobrev** [comment]
Take a look at `Mesh::RemoveInternalBoundaries()`: https://github.com/mfem/mfem/blob/9a21f59e60b20d8a0cdde2af8d55be75dbc27bb2/mesh/mesh.hpp#L1049-L1051

**Comment by altineller** [comment]
I have:

`
cout << "num boundaries: " << meshRead->GetNBE() << endl;
`
`
meshRead->RemoveInternalBoundaries();
`
`
cout << "num boundaries after: " << meshRead->GetNBE() << endl;
`

And got:

> num boundaries: 66528
num boundaries after: 55440

However I am afraid it only removed fraction of internal boundaries. My shape is not complex, consisting of 11088 elements, and for each element, I have generated a boundary, so I have 6x boundaries.

But about 80% of them should be internal boundaries.

How can I test this?

Best Regards,
C.

**Comment by v-dobrev** [comment]
If you call `meshRead->RemoveInternalBoundaries();` does remove more boundary elements? I don't expect it to remove more but if it does, it's sign of an issue with the method.

In any case, if you still see internal boundaries after the call, I suspect that your mesh is not fully connected topologically. I'm not 100% sure, but you may be able to re-connect the mesh (based finding duplicate vertices at the same geometric location) using the methods `Mesh::CreatePeriodicVertexMapping()` (with $\vec{0}$ vector translation) and then merge the duplicated vertices with a call to `Mesh::MakePeriodic(const Mesh &orig_mesh, const std::vector<int> &v2v);`. Actually, `Mesh::CreatePeriodicVertexMapping()` only looks for translated duplicates of vertices of boundary elements, so it may not be sufficient for general duplicate vertex detection -- maybe with small modifications, you can adapt it to that case. 

@pazner, do you think this can work? If it does (with some modifications) we can add such utility method to the library.

**Comment by najlkin** [comment]
Besides that, do you have a distributed mesh, i.e. load it as `ParMesh`? If you do, maybe look here #4128 , there is a known bug 🪲  and its fix 😉 .
