### ISSUE TITLE
free() invalid pointer NewtonSolver destructor

### ISSUE THREAD

**Issue by lmolin3** [mfem/mfem#4148]
Hi,
I'm trying to solve a nonlinear problem with a NewtonSolver. The solver seems to work fine and converges, but whenever the destructor of the NewtonSolver is called I get a `free() invalid pointer` error.

Looking at the call stack, the error seems to occur in the mem_manager.hpp (`if (flags & OWNS_HOST) { delete [] h_ptr; }`) after ~NewtonSolver() invokes ~Vector(), where `data.Delete()` is called. 

The code that is giving me problems is the following:

```
void ImplicitSolve(Vector &b, Vector &x)
{
   // Create BlockVectors to unpack pressure and velocity
   BlockVector xb(x.GetData(), offsets);
   Vector &xu = xb.GetBlock(0);
   Vector &xp = xb.GetBlock(1);

   BlockVector bb(b.GetData(), offsets);
   Vector &bu = bb.GetBlock(0);
   Vector &bp = bb.GetBlock(1);

   // Create newton solver and preconditioner
   CGSolver	linsolve(MPI_COMM_WORLD);
   linsolve.SetPreconditioner(*linsolve_pc);
   linsolve.SetRelTol(lin_params.rtol);
   linsolve.SetAbsTol(lin_params.atol);
   linsolve.SetMaxIter(lin_params.maxiter);

   NewtonSolver newton_solver(MPI_COMM_WORLD);
   newton_solver.SetOperator(*residual);
   newton_solver.SetPreconditioner(linsolve);
   newton_solver.SetRelTol(newton_params.rtol);
   newton_solver.SetAbsTol(newton_params.atol);
   newton_solver.SetMaxIter(newton_params.maxiter);
   newton_solver.SetPrintLevel(newton_params.pl);

   // Apply bcs
   for (auto &vel_dbc : bcs->GetVelDbcs())
   {
      u_gf->ProjectBdrCoefficient(*vel_dbc.coeff, vel_dbc.attr);
   }
   u_gf->GetTrueDofs(xu);
   
   bu.SetSubVector(vel_ess_tdof, 0.0);
   bp = 0.0;
   
   
   newton_solver.Mult(bu, xu); // free(): invalid pointer in ~NewtonSolver() when ~Vector() is called
}
```

**Comment by jandrej** [comment]
https://godbolt.org/z/cbf1xbdPv

works as expected

**Comment by lmolin3** [comment]
I know the NewtonSolver is not the problem, I've used it before and didn't have any problems. I was wondering If you have any idea of where the problem may come from in this case. Thanks again!

**Comment by v-dobrev** [comment]
This looks like memory corruption from somewhere else, not from `NewtonSolver`. Can you try building MFEM in debug mode (option `MFEM_DEBUG=YES`) and run your code? In debug mode, the library performs some additional checks which may catch the issue. If this build runs with the same error, try running the code under valgrind -- that can also help you find memory related issues.

**Comment by v-dobrev** [comment]
My suspicion is that the valgrind + MPI issue is not mfem related. Can you try with a simple "hello world"-like MPI program?

We do nightly tests with valgrind + MPI and they do not show any issues. We do need to use a suppression file for some MPI-related issues and older hypre versions. Here's what it looks like:
```
{
   MPI-related-write
   Memcheck:Param
   writev(vector[...])
   fun:writev
}

{
   MPI-related-syscall
   Memcheck:Param
   sched_setaffinity(mask)
   fun:syscall
}

{
   MPI_Init-memcpy
   Memcheck:Overlap
   fun:memcpy
   fun:pmgr_allgather
   fun:MPID_PSM_Init
   fun:MPID_Init
   fun:MPIR_Init
   fun:main
}

{
   OMPI_Init-param-getsockopt-optlen
   Memcheck:Param
   socketcall.getsockopt(optlen)
   ...
   fun:ompi_mpi_init
   fun:PMPI_Init*
}

{
   OMPI_Init-param-getsockopt-optlen_out
   Memcheck:Param
   socketcall.getsockopt(optlen_out)
   ...
   fun:ompi_mpi_init
   fun:PMPI_Init*
}

{
   OMPI_Init-param-setsockopt-optlen
   Memcheck:Param
   setsockopt(optlen)
   ...
   fun:ompi_mpi_init
   fun:PMPI_Init*
}

{
   OMPI_Init-leak
   Memcheck:Leak
   ...
   fun:ompi_mpi_init
}

{
   OMPI_Finalize-leak
   Memcheck:Leak
   ...
   fun:ompi_mpi_finalize
}

{
   hypre-BoomerAMG-GaussElimSetup
   Memcheck:Overlap
   fun:memcpy
   fun:ompi_ddt_copy_content_same_ddt
   fun:ompi_coll_tuned_allgather_intra_bruck
   fun:PMPI_Allgather
   fun:hypre_GaussElimSetup
   fun:hypre_BoomerAMGSetup
}

{
   hypre-BoomerAMG_GMExpandInterp
   Memcheck:Leak
   match-leak-kinds: definite
   fun:calloc
   fun:hypre_CAlloc
   fun:hypre_BoomerAMG_GMExpandInterp
   fun:hypre_BoomerAMGSetup
}
```
What MPI implementation are you using? I had some issues with OpenMPI v5.0.x but v4.1.x should work fine. I'm not sure about MPICH, or other implementations.

**Comment by lmolin3** [comment]
You were right, the valgrind one was an issue with the MPI implementation. Apparently with the docker image I was working on had Intel MPI (causing troubles), while OpenMPI v4.1 works.
Thanks for the suppression file as well, it'll help spotting the error in the code.
