### ISSUE TITLE
How to compile a single example

### ISSUE THREAD

**Issue by Wayne901** [mfem/mfem#4150]
I'm very new to MFEM. I see how to install mfem directly or through spack. The examples or miniapps are build with "make examples" or "make miniapps". However, i don't see how to cmake && make a single program and wrote a coressponding CMakeList. Any hints on that? (Should MFEM be pointed to libmfem.a in CMakeLists.txt?)

**Comment by v-dobrev** [comment]
If you want to use CMake, Spack will not be very useful -- MFEM's Spack package uses the GNU make build system, for now.

For CMake build instructions, see here: https://github.com/mfem/mfem/blob/9a21f59e60b20d8a0cdde2af8d55be75dbc27bb2/INSTALL#L105-L106

and more details here: https://github.com/mfem/mfem/blob/9a21f59e60b20d8a0cdde2af8d55be75dbc27bb2/INSTALL#L858-L859

**Comment by Wayne901** [comment]
Thank you Dobrev,

Are the CMake build instructions in INSTALL for building mfem or also for a single .cpp code?

**Comment by v-dobrev** [comment]
The instructions are for building the library (default cmake target, `all`), the examples (target `examples`), or all executables (target `exec`) used for testing (these include the examples, miniapps, and unit tests). You can also build individual targets like `ex1` or `ex1p` -- to see all available targets, you can use `make help`, I think.

**Comment by Wayne901** [comment]
I'm clear with it now. Besides this issue helps https://github.com/mfem/mfem/issues/1163 
Thank you.
