### ISSUE TITLE
Gauss-Lobatto Basis Affecting Discontinuous Initial Conditions in DG

### ISSUE THREAD

**Issue by FH-9** [mfem/mfem#4152]
Hi,

When using Gauss-Lobatto basis with DG for linear advection and Burgers equations, I am seeing my discontinuous initial condition has oscillatory behavior. I can see oscillations happening for Burgers at time steps when discontinuities arise if the solution is not limited. However, I do not see how Gauss-Lobatto could cause a change in the initial condition itself with both the advection and Burgers equations. This does not happen with Gauss-Legendre, for example. Is this an issue with the software implementation or a detail about Gauss-Lobatto that I am missing?

Thank you very much,
Farhad

**Comment by jandrej** [comment]
It's relevant how you project your initial condition. Can you show a minimal example?

**Comment by FH-9** [comment]
Hi @jandrej,

Here is a relevant piece of code:
```c++
DG_FECollection* fec = new DG_FECollection(order, dim, BasisType::GaussLobatto);
ParFiniteElementSpace* fes = new ParFiniteElementSpace(pmesh, fec);
VectorFunctionCoefficient u0(num_equations, InitialCondition);
ParGridFunction sol(fes);
sol.ProjectCoefficient(u0);
``` 
Is this enough or is there anything else I should provide?

**Comment by tzanio** [comment]
In this case `ProjectCoefficient` is just an interpolation in the Gauss-Lobatto nodes, which by itself should not introduce oscillations compared to e.g. Gauss-Legandre.

That being said, unless the discontinuity is aligned with the mesh, you should oscillations in both nodal bases. To avoid that, sometimes one can project in the positive Bernstein basis (at the cost of loss of accuracy).

**Comment by vladotomov** [comment]
> detail about Gauss-Lobatto that I am missing?

It has a node right at the element face. Then the elements might get the wrong value at the jump (when aligned), depending on round-off in the interpolation. An element that gets the wrong value will oscillate, due to sharp transition inside. The Gauss-Legendre nodes are all inside, so this doesn't happen.

**Comment by v-dobrev** [comment]
If you use a coefficient class that takes into account the element attributes of the mesh (e.g. `PWConstCoefficient`, `PWVectorCoefficient`) and the attributes are aligned with the jumps in your coefficient, then the projection will work correctly, even in the Gauss-Lobatto basis. You can also define your own derived `VectorCoefficient` class to handle the values based on the element attributes.

**Comment by FH-9** [comment]
Hi,

Thank you @jandrej, @tzanio, @vladotomov, and @v-dobrev for being so responsive!
Apologies for the delayed response.


> That being said, unless the discontinuity is aligned with the mesh, you should oscillations in both nodal bases.

So if the mesh face is aligned with the initial discontinuity, the oscillation is only observed with Gauss-Lobatto due to two overlapping nodes of the face neighbors, which is what I was seeing before. After your explanation, I nudged the discontinuity a little bit away from the face and put it in between the internal Gauss-Legendre nodes, and I can indeed see the oscillation now with Gauss-Legendre as well. Is this what you were conveying with this comment? I hope I didn't miss anything.



> It has a node right at the element face. Then the elements might get the wrong value at the jump (when aligned), depending on round-off in the interpolation. An element that gets the wrong value will oscillate, due to sharp transition inside. The Gauss-Legendre nodes are all inside, so this doesn't happen.

My thoughts exactly. However, after nudging the discontinuity inwards the oscillation still remains with Gauss-Lobatto basis, which is basically the same kind as the one observed when the discontinuity is in between Gauss-Legendre nodes.

So if I understand this correctly there are two sources for those oscillations: One that occurs when there are overlapping nodes with a jump in values like in the case when the discontinuity is at an element face with Gauss-Lobatto, which is very intuitive to me; the other one happens when the discontinuity is internal to the element regardless of the basis type, which I do not quite understand. Could you elaborate on the latter?

In addition, one of the main ideas of DG is to allow for discontinuities at element faces and solve many local Riemann-like problems. Wouldn't then the same interpolation issue with the global discontinuous IC persist locally everywhere in this case as well even in smooth regions where the limiting is not necessary? How come this is not an issue then? Or do those small-scale oscillations still occur but to "eyeball" precision are not significant?



> If you use a coefficient class that takes into account the element attributes of the mesh (e.g. `PWConstCoefficient`, `PWVectorCoefficient`) and the attributes are aligned with the jumps in your coefficient, then the projection will work correctly, even in the Gauss-Lobatto basis. You can also define your own derived `VectorCoefficient` class to handle the values based on the element attributes.

Thank you for pointing me in the right direction! It looks like piecewise coefficients amend the problem. I am a little unclear on the attributes and what exactly "constants keyed off the element attribute numbers" entails. Could you please refer me to a usage case (maybe, a simple code demonstrating basic usage) of piecewise coefficients? 

Thanks once again to everyone for all the explanations!

Best,
Farhad

**Comment by v-dobrev** [comment]
The element attributes are numbers assigned to all elements (and boundary elements) in the Mesh class. They are typically assigned during mesh generation, however, they can be modified in the MFEM application as well.

The sentence "... constants keyed off the element attribute numbers." means that value returned by the coefficient depends on the attribute of the mesh element for which the coefficient is being evaluated. This information is passed to the virtual method https://github.com/mfem/mfem/blob/edcd7ee0ea823add4765d69d8f4b4cd2df843841/fem/coefficient.hpp#L132-L134

in the first argument. For example, the attribute is stored in `T.Attribute`, see https://github.com/mfem/mfem/blob/edcd7ee0ea823add4765d69d8f4b4cd2df843841/fem/coefficient.cpp#L76-L81

The main purpose of `ElementTransformation` is to define the mapping from the reference element to the physical element. For example, the physical location of the reference quadrature point `ip` (the second argument of `Eval`) can be computed like this: https://github.com/mfem/mfem/blob/edcd7ee0ea823add4765d69d8f4b4cd2df843841/fem/coefficient.cpp#L132-L135

**Comment by vladotomov** [comment]
> So if I understand this correctly there are two sources for those oscillations

It's the same source in both cases: you create a discontinuity inside an element, and try to interpolate it with a 2nd order polynomial.This oscillates. Repeat all your tests with P1 and you will see none of that.

> and I can indeed see the oscillation now with Gauss-Legendre as well.

Because now the jump is between the DOFs inside a single element, unlike before.

> Wouldn't then the same interpolation issue with the global discontinuous IC persist locally everywhere in this case as well even in smooth regions 

Smooth regions don't have discontinuous IC.

**Comment by FH-9** [comment]
> The element attributes are numbers assigned to all elements (and boundary elements) in the Mesh class. They are typically assigned during mesh generation, however, they can be modified in the MFEM application as well.
> 
> The sentence "... constants keyed off the element attribute numbers." means that value returned by the coefficient depends on the attribute of the mesh element for which the coefficient is being evaluated. This information is passed to the virtual method
> 
> https://github.com/mfem/mfem/blob/edcd7ee0ea823add4765d69d8f4b4cd2df843841/fem/coefficient.hpp#L132-L134
> 
> in the first argument. For example, the attribute is stored in `T.Attribute`, see
> 
> https://github.com/mfem/mfem/blob/edcd7ee0ea823add4765d69d8f4b4cd2df843841/fem/coefficient.cpp#L76-L81
> 
> The main purpose of `ElementTransformation` is to define the mapping from the reference element to the physical element. For example, the physical location of the reference quadrature point `ip` (the second argument of `Eval`) can be computed like this:
> 
> https://github.com/mfem/mfem/blob/edcd7ee0ea823add4765d69d8f4b4cd2df843841/fem/coefficient.cpp#L132-L135

Thank you very much.
How could one infer the correct element number though? Let's say I have a 1D mesh from 0 to 1 with a discontinuity in the middle, at 0.5. Is there a reliable way of figuring out which element attributes will be to the left or to the right of the discontinuity at any mesh refinement level?

**Comment by FH-9** [comment]
> > So if I understand this correctly there are two sources for those oscillations
> 
> It's the same source in both cases: you create a discontinuity inside an element, and try to interpolate it with a 2nd order polynomial.This oscillates. Repeat all your tests with P1 and you will see none of that.
> 
> > and I can indeed see the oscillation now with Gauss-Legendre as well.
> 
> Because now the jump is between the DOFs inside a single element, unlike before.
> 
> > Wouldn't then the same interpolation issue with the global discontinuous IC persist locally everywhere in this case as well even in smooth regions
> 
> Not sure what you mean, smooth regions don't have discontinuous IC.

Thank you. What I meant was that DG does not enforce continuity across interfaces. Hence, it allows for discontinuities across all interfaces and that is how Riemann problem is introduced. This is true even for smooth regions in the flow.

**Comment by vladotomov** [comment]
> Let's say I have a 1D mesh from 0 to 1 with a discontinuity in the middle, at 0.5. Is there a reliable way of figuring out which element attributes will be to the left or to the right of the discontinuity at any mesh refinement level?

See this [comment](https://github.com/mfem/mfem/issues/4131#issuecomment-1942925486) and discussion (#4131).

**Comment by v-dobrev** [comment]
> How could one infer the correct element number though? Let's say I have a 1D mesh from 0 to 1 with a discontinuity in the middle, at 0.5. Is there a reliable way of figuring out which element attributes will be to the left or to the right of the discontinuity at any mesh refinement level?

The idea is not to look at the element number directly, or at physical coordinates of points inside the element. Instead, you need to create the initial mesh such that the elements to left of 0.5 have one attribute (e.g. 1, attributes are expected to be >= 1) and the ones on the right of 0.5 have a different attribute (e.g. 2). This way checking the attribute is like checking for <= 0.5 or >= 0.5 while avoiding roundoff errors (in the computation of the physical coordinates) and also using the correct value at = 0.5 based on the limit value from the left or the right.

Example of meshes with 2 attributes are: https://github.com/mfem/mfem/blob/master/data/beam-quad.mesh and https://github.com/mfem/mfem/blob/master/data/beam-hex.mesh. In the "elements" section, the first entry in each row is the attribute number. The first line just after "elements" is the number of elements; the lines after that describe the elements. See the description here: https://mfem.org/mesh-format-v1.0 and here: https://mfem.org/mesh-format-v1.x.

Note that when a mesh is refined the attribute of a coarse element is propagated to its children, so the same attribute continues to describe the same physical region after refinement.

**Comment by FH-9** [comment]
Thank you very much!
