### ISSUE TITLE
What does the Trans.Weight() do 

### ISSUE THREAD

**Issue by Wayne901** [mfem/mfem#4154]
I'm trying to understand the AssembleElementMatrix() of BlinearIntegrators.
The evaluation of an entry of mass matrix or stiffness matrix by basis functions on reference cell should be:
![Snipaste_2024-02-25_23-27-16](https://github.com/mfem/mfem/assets/52063692/e61bd25b-6040-4afd-af96-d0cd958ecb3d)
In bilininteg.cpp's MassIntegrator::AssembleElementMatrix(), Trans.Weight() is multiplied by IntegrationPoint.weight(), so I suppose Trans.Weight() returns the determinant of the Jacobian matrix.
However, in bilininteg.cpp's DiffusionIntegrator::AssembleElementMatrix(), Trans.Weight() is divided 
![Snipaste_2024-02-25_23-33-29](https://github.com/mfem/mfem/assets/52063692/844085c6-18f0-4c96-9f1a-bb82a1fef0ce)
What's the physics of Trans.Weight() and why adj(J) is multiplied only once?

**Comment by vladotomov** [comment]
Hi @Wayne901,

> What's the physics of Trans.Weight()

It's the determinant of the Jacobian.

> Trans.Weight() is divided

One inverse cancels the outside `|J|`, one inverse stays.

> why adj(J) is multiplied only once?

It's once per shape function.

**Comment by Wayne901** [comment]
Thank you Tomov. Now I understand there's a inner product between 2 dshapext in Mult_a_AAt().
Let $J^T$ be adj(J), then is
$|J|^{-1}(\nabla{\phi}J^T)(\nabla{\phi}J^T)^T $
equivalent to $|J|(\nabla{\phi}J^{-T})(\nabla{\phi}J^{-T})^T $ ?
I think what I wrote must be some mistake.

**Comment by vladotomov** [comment]
> Let $J^T$ be adj(J)

I don't understand this.

We use $J^{-1} = adj(J) / |J|$.

**Comment by Wayne901** [comment]
Oh ... I misunderstood the definition of the adjacency matrix.
It's clear now, thank you a lot.
