### ISSUE TITLE
Build a MFEM project with an example in qt-creator

### ISSUE THREAD

**Issue by Wayne901** [mfem/mfem#4155]
Hello my friends, i'm learning the basic FEM implementation inside MFEM. Sometimes I want to run a project in Debug mode to see a step-by-step execution in bilinearform.cpp and bilininteg.cpp.
Does someone know how to build MFEM along with one/ several examples in QtCreator? I met errors like 
`fatal error: _config.hpp: No such file or directory`
and
`Failed to start program. Path or permissions wrong?`

**Comment by v-dobrev** [comment]
If looks like you are missing the `make config` step. I typically add that to the "Clean Steps" right after `make clean`. Then to build for the first time run the "clean" steps followed by the "build" steps or simply run the "rebuild" steps -- all of these actions are in the "Build" menu.

**Comment by Wayne901** [comment]
Which step in Qtcreator works as `make config`?
Shall I add some configuration options in the Build Steps then?
![Snipaste_2024-02-27_10-56-19](https://github.com/mfem/mfem/assets/52063692/6cc5f47b-d8b6-4cc5-8c47-30cedf074165)

**Comment by v-dobrev** [comment]
I'm not sure how Qt Creator does this. In terms of CMake, "make config" corresponds to the step that is run first from the build directory: `cmake <source-dir> [options]`. Only after this step, can one run things like `cmake --build . --target all`. See here for more details: https://github.com/mfem/mfem/blob/edcd7ee0ea823add4765d69d8f4b4cd2df843841/INSTALL#L858

**Comment by Wayne901** [comment]
Thank you Dobrev. I'll close this issue.
