### ISSUE TITLE
Add Support for Higher-Order H1 Pyramid Basis Functions

### ISSUE THREAD

**Issue by EdwardPalmer99** [mfem/mfem#4157]
Currently no support for higher-order H1 Pyramid basis functions. See file _fe_coll.cpp_, line 1970.

![Screenshot from 2024-02-27 16-30-10](https://github.com/mfem/mfem/assets/93386624/c67828eb-d0b4-4b84-b8fa-eb165524b2f6)

**Comment by mlstowell** [comment]
Hi, @EdwardPalmer99,

This is still experimental. We currently have two implementations of arbitrary order H1 basis functions on square pyramids in the `pyramid-dev` branch. One of these is taken from "Orientation embedded high order shape functions for the exact sequence elements of all shapes" by Fuentes et al and the other from "Higher-Order Finite Elements for Hybrid Meshes Using New Nodal Pyramidal Elements" by Bergot et al. Most notably they differ in the number of interior degrees of freedom.

Each of these implementations is incomplete and inadequately tested but they can be used for Poisson type problems such as `ex1`, `ex1p`, and `ex11p` where they seem to function as expected.

The work continues...

Best wishes,
Mark

**Comment by EdwardPalmer99** [comment]
Thanks! I had a quick play with the pyramid-dev branch today using the ExodusII writer and reader I've been working on. It appears to work although I need to do a bit more testing.

**Comment by tzanio** [comment]
There have been additional improvements in the `pyramid-dev` branch. @EdwardPalmer99 can you check it and let us know if we can close this issue?

**Comment by EdwardPalmer99** [comment]
Hi, I think so!

I've only had a quick check. My ExodusII reader/writer branches appear to work witih the pyramid-dev branch--we can load my ExodusII pyramid14 test file and then write it out to another file.
