### ISSUE TITLE
UniformRefinement() is anisotropic for periodic-segment.mesh

### ISSUE THREAD

**Issue by Wayne901** [mfem/mfem#4158]
In example 9, when I choose input mesh as `data/periodic-segment.mesh`, the uniform refined mesh is only refined in one direction. Besides, I'd like to see the number of Dofs in one element so I add
`fec_l2 = new DG_FECollection(order, dim);`
`const auto fe_l2 = fec_l2->GetFE(Geometry::SQUARE, order);`
`cout << "Order of finite element L2: " << fe_l2->GetOrder() << endl;`
`cout << "Number of dofs in one element: " << fe_l2->GetDof() << endl;`
When input mesh is `data/periodic-segment.mesh`, there is Segmentation fault calling FiniteElement->GetOrder().
Other mesh inputs seem fine. Is this mesh distinct from others?

**Comment by vladotomov** [comment]
Hi @Wayne901 the `data/periodic-segment.mesh` is a 1D mesh of 1D segments. That's why it gets refined in 1D. Also your element type above must be `Geometry::SEGMENT`.

**Comment by Wayne901** [comment]
Thank you Tomov, I thought it's 2-D mesh cause it's visualized as a rectangle in GLVis ...
