### ISSUE TITLE
Inconsistent large/nan mass matrix entries

### ISSUE THREAD

**Issue by thartland** [mfem/mfem#4159]
I have a simple example code (linked below) where I build a mass matrix associated to a finite element discretization of a displacement field. I am getting inconsistent results. That is, without recompiling if I run the same executable with the same command line arguments, e.g., `./ParTest`, I will sometimes see very large (e.g., `3.96423e+214`) entries in the mass matrix and otherwise the entries are of a reasonable order. With mpi, I consistently see issues with the mass matrix, large entries with `mpirun -np 1 ./ParTest -r 0` and even some `-nan` entries with a little bit of mesh refinement `mpirun -np 1 ./ParTest -r 2`. I pulled the most recent mfem and built it this morning. Attached is the code, I am using the `inline-quad.mesh` from `mfem/data`

[ParTest.txt](https://github.com/mfem/mfem/files/14438483/ParTest.txt)

**Comment by psocratis** [comment]
Hi @thartland, you need to use the `VectorFEMassIntegrator` and not the scalar version of it. 

Socratis
