### ISSUE TITLE
Domainintegrator markers and matrix free gpu

### ISSUE THREAD

**Issue by joetristano** [mfem/mfem#4161]
Hi,
I was playing around with domain integrators with a Helmholtz solver. When I assemble, I can limit computational domain over a given set of markers. This works quite well.

However, when I approach this, with my matrix, free, elasticity solver, I realized that since I'm not assembling anything, I cannot limit the computational domain in this way. According to the hooke minapp, L vec to E vec occurs in the operator. The size of these vectors is determined by the EE space which has no knowledge of the assembly as far as I know..

How would one best leverage the marker capability with a matrix free solver? For instance, on one set of markers I would use a certain kernel and another set of markers, I use a kernel. 

Any thoughts on this would be appreciated.
Thanks in advance,
Joe

**Comment by jandrej** [comment]
Hooke's kernels don't accommodate domain attributes. It's a showcase application and it's up the user to use or modify pieces to fit their needs.

In general matrix free integrators work the same way for attributes as regular integrators do. It's simply a matter of applying the integrators to the marked elements.

**Comment by jtristano** [comment]
When you get the E vectors from the L vectors would you create separate E vectors per Marker or just have one big E vector and apply different kernels based on markers?  If it's the latter, you could experience thread divergence in your kernels, yes?

**Comment by jandrej** [comment]
It's the latter. Yes, in general you will have idling threads.

**Comment by jtristano** [comment]
Thank you!
