### ISSUE TITLE
How to compare Gradient created by serial code to Gradient created by parallel code?

### ISSUE THREAD

**Issue by miaodi** [mfem/mfem#4165]
I found that the gradient is SparseMatrix in NonlinearForm and is HypreParMatrix in ParNonlinearForm. How should I convert one to the other format so that I can compare the gradient from serial code to the gradient from parallel code?

Thank you!

**Comment by v-dobrev** [comment]
On multiple MPI ranks, this will not be that easy.

On one MPI rank, you can get a `SparseMatrix` from the `HypreParMatrix` using `HypreParMatrix::GetDiag(SparseMatrix &diag)`.
