### ISSUE TITLE
Computing the static magnetic field energy

### ISSUE THREAD

**Issue by denislachapelle** [mfem/mfem#4166]
I have compute the static magnetic field of a microstrip and I want to compute the static magnetic field energy. To do so I have to compute the integral of the square of the field over the entire domain. I wrote the code below, but I am not sure about the weights, there is a weight from the integration rule and another weight from the element transformation. Should they both be applied?

The code snippet is shown below. Note the the field is in a GridFunction named ROT90 and the domain is in 2 dimensions.

Thank you for your help.

```c++
double SumSquare=0.0;
Vector VVal(3);
Element *El;   //a pointer to the current element.
IntegrationRule ir;  //integration rule for the current element.
IntegrationRules irs;
ElementTransformation *Trans;
for (int i = 0; i < mesh.GetNE(); i++)
    {
      Trans = mesh.GetElementTransformation(i);
      El = mesh.GetElement(i);
      ir = irs.Get(El->GetGeometryType(), order+2);
      Array<double> Weights(ir.GetNPoints());
      Weights = ir.GetWeights();  //quadrature points weights.
      for(int j=0; j<ir.GetNPoints(); j++)
      {
         Trans->SetIntPoint(&ir.IntPoint(j));
         ROT90.GetVectorValue(i, ir.IntPoint(j), VVal);
         SumSquare+=(VVal[0]*VVal[0]+VVal[1]*VVal[1])*Weights[j]*Trans->Weight();
      }
    }
    cout << "SumSquare = " << SumSquare << endl;
```

**Comment by najlkin** [comment]
Yes, weight of the transformation is the Jacobian, i.e. the factor corresponding to the transformation from the reference space (where the actual integration takes place) to the physical space (where you want the integration to happen). The quadrature weight is then the "partition of unity", i.e. how each point contributes to the whole integral.

Secondly, you may get the weight of the integration point through `ir.IntPoint(j).weight` 👍

**Comment by denislachapelle** [comment]
@najlkin 
Thank you this is a very good explanation and using ir.IntPoint(j).weight improve the code clarity.

**Comment by najlkin** [comment]
Good to hear 😉 , I am closing this.
