### ISSUE TITLE
CutFEM in MFEM

### ISSUE THREAD

**Issue by ryanblack129** [mfem/mfem#4167]
Hello,

I saw the recent MFEM paper on archive (https://arxiv.org/abs/2402.15940) had a CutFEM example. I am considering this kind of approach for an application problem and was wondering if there is an example problem showing how to implement this in MFEM or if its possible to share the example code from the paper?

Thanks,
Ryan

**Comment by federicobetti99** [comment]
Hello,

I am also interested in the CutFEM capabilities provided by MFEM. Could you share with me an example problem where this is implemented?

**Comment by bslazarov** [comment]
Hello, 

We will add an example later this year. I expect it to be ready mid-summer. I will send an update once it is ready to merge.

Best regards, Boyan

**Comment by pantolin** [comment]
Hello,

having CutFEM capabilities in MFEM sounds really cool!

I read in the arXiv paper that there two possibilities for integrating over cut elements were mentioned: algoim or moment fitting.
Will it be possible to directly provide quadrature points and weights for the cut elements?
I have a library that generates them for CAD domains immersed in Cartesian grids and this would be a perfect match.

And a second question, will the CutFEM capabilities work with any type of finite elements including NURBS discretizations?

Thanks!

Pablo

**Comment by bslazarov** [comment]
> I wonder what are the changes you made to the current baseline: is the user just going to be able to pass element-wise quadrature rules to this function? Or is it more complicated than that?

First step marks the elements in the computational domain. For all cut elements, the integration rule has to be replaced with CutFEM integration rule, and finally the discrete system has to stabilized by using ghost penalty. The last step is a bit tricky  for high order discretizations.

**Comment by bslazarov** [comment]
Hello Pablo,

Yes, the cut integration rules provide integration points and integration weights for a given level set coefficient. The geometry should be described implicitly by a level set function. 

For a CAD geometry the fist step would be to generate the level set - such feature will come a bit later. We have the tools, however, we need to unify the interface fist. 

CutFEM integration should work fine with NURBS. 

Best regards, Boyan

**Comment by skbizport** [comment]
Hi

Curious to know status of this. Would be great to see a working example of CutFEM, e.g. for static analysis. 

Regards,
SK

**Comment by tzanio** [comment]
we plan to work on this, and there is already some initial capabilities with the quadrature rules mentioned above

ping: @bslazarov

**Comment by bslazarov** [comment]
Hi, 

We are currently working on two examples - one for diffusion and on for Stokes flow. I hope in 3 months to have them merged.

Best regards, Boyan 

⁣Get BlueMail for Android ​

**Comment by skbizport** [comment]
Thanks for the update. Would there also be example of topology optimization based off CutFEM?

**Comment by skbizport** [comment]
Can you pls point to the CutFEM example? I am looking for ways to apply it to linear static elasticity & thermal simulations, especially for the complex lattice based geometries.

Thx
