### ISSUE TITLE
importing geometry/models 

### ISSUE THREAD

**Issue by Harsh00100** [mfem/mfem#4176]
how to import .cad, .sldworks, .step file into mfem for mesh generation?

**Comment by paul-hilscher** [comment]
You do not import a cad model but the mesh into mfem.

A summary of supported mesh formats can be found [here](https://mfem.org/mesh-formats/).

Depending on your needs various commercial and open source meshes can be used. For example both [netgen](https://docu.ngsolve.org/latest/i-tutorials/unit-4.4-occ/occ.html) and [gmsh](https://gmsh.info/doc/texinfo/gmsh.html) support the import of a step file through their OpenCascade interface and subsequently the creation of a supported mesh.

**Comment by Harsh00100** [comment]
thank you very much for clarification, also can a 3d mesh model be imported to mfem?
thank you for your response and time

**Comment by paul-hilscher** [comment]
>  can a 3d mesh model be imported to mfem? 

Yes! You can see an example [here](https://github.com/mfem/mfem/blob/master/examples/ex0.cpp).

**Comment by Harsh00100** [comment]
thank you
