### ISSUE TITLE
Why is dt updated 3 times in Newmark class

### ISSUE THREAD

**Issue by Wayne901** [mfem/mfem#4177]
Hello, I have some questions about the implementation of the second order ODE solver, the NewmarkSolver class.
Take ex23 the wave equation for example.
In Newmark method, $u(t+\Delta t)$ is updated as
$u(t+\Delta t) = u(t) + \Delta t\frac{du(t)}{dt}+(\frac{1}{2}-\beta)(\Delta t)^2\frac{d^2u(t)}{dt^2}+\beta(\Delta t)^2\frac{d^2u(t+\Delta t)}{dt^2}$.
Substituting it into the scalar wave equation $\frac{d^2u(t+\Delta t)}{dt^2}=c^2\Delta u(t+\Delta t)$ and let $M$ and $K$ be the mass matrix and stiffness matrix, we have following linear system:
$[M+\beta c^2(\Delta t)^2K]\frac{d^2u(t+\Delta t)}{dt^2} = -c^2K[u(t)+\Delta t\frac{du(t)}{dt}+(\frac{1}{2}-\beta)(\Delta t)^2\frac{d^2u(t)}{dt^2}]$.
This is exactly what `NewmarkSolver::Step` does, where `ImplicitSolve` inverts the $[M+\beta c^2(\Delta t)^2K]$ matrix to get $\frac{d^2u(t+\Delta t)}{dt^2}$, then update $u(t+\Delta t)$ and $\frac{du(t+\Delta t)}{dt}$
```
void NewmarkSolver::Step(Vector &x, Vector &dxdt, double &t, double &dt)
{
   double fac0 = 0.5 - beta;
   double fac2 = 1.0 - gamma;
   double fac3 = beta;
   double fac4 = gamma;

   // In the first pass compute d2xdt2 directly from operator.
   if (first)
   {
      f->Mult(x, dxdt, d2xdt2);
      first = false;
   }
   f->SetTime(t + dt);

   x.Add(dt, dxdt);
   x.Add(fac0*dt*dt, d2xdt2);
   dxdt.Add(fac2*dt, d2xdt2);

   f->SetTime(t + dt);
   f->ImplicitSolve(fac3*dt*dt, fac4*dt, x, dxdt, d2xdt2);

   x   .Add(fac3*dt*dt, d2xdt2);
   dxdt.Add(fac4*dt,    d2xdt2);
   t += dt;
}
```
However, the final $t$ would be $t+3\Delta t$. I think this `Step` function only solves `u`, `dudt`, and `d2udt2` at `t+dt`, but `t` is updated for 3 time steps. Is there a reason for this implementation?

**Comment by IdoAkkerman** [comment]
There is a fix to this issue in PR #3480

**Comment by Wayne901** [comment]
Thank you for the quick reply.
Unfortunately, I don't think the time stepping is different from the MFEM 4.6.
Is this the upated `ode.cpp` [here](https://github.com/mfem/mfem/pull/3480/files/f5cf13076b184d3ae30b582a07b4cf2545cf632f#:~:text=x.Add(fac0*dt*dt,dt%2C%20%20%20%20state%5B0%5D)%3B) ?

**Comment by Wayne901** [comment]
Besides, is there any example for time-dependent nonzero Dirichlet boudary condition? `ex23` only applys the zero Dirichlet BC, and it uses 2 different stiffness matrix `Kmat` and `Kmat0`, which is not exactly the same as @v-dobrev said in [#1720](https://github.com/mfem/mfem/issues/1720#:~:text=Here%20are%20some%20notes%20about%20applying%20b.c.%20that%20might%20be%20helpful.). I'm new to MFEM and really stuck here #4174.

**Comment by Wayne901** [comment]
I have a little suggestion/question about `ex23`. When the dirichlet boundary conditions are applied, `dudt` and `d2udt2` should be 0. However when I run the wave euqation example `ex23` and output the `d2udt2` vector in `ImplicitSolver` function, `d2udt2` is not zero at the boundary DoFs. I set `d2udt2`'s boundary entries to 0, and the final result is slightly different to the original code (`./ex23 -m ../../data/disc-nurbs.mesh -r 3 -o 4 -tf 5 --dirichlet`)
Result from original code:
![Wave_d2dut2_notset](https://github.com/mfem/mfem/as
Result when boundary entris of `d2udt2` set to 0:
![Wave_d2dut2_setzero](https://github.com/mfem/mfem/assets/52063692/b454862d-a9ba-4156-a199-4215946a1b20)
sets/52063692/2c5b1400-b150-41fa-b4af-5ba4960a2a0d)

I think the nonzero boundary DoFs in `d2udt2` comes from solving the linear system
$[M+\beta (\Delta t)^2K\frac{d^2u(t+\Delta t)}{dt^2}=-Ku_{ImplicitSolver}$? But why would the solution on boundary entries be nonzero when $u_{ImplicitSolve}$'s are 0 there?

Please let me know if my choice of setting `d2udt2`'s boundary DoFs 0 is correct.

Thank

**Comment by Wayne901** [comment]
I see, I mistake the `SetTime` function. It does not change the input variable, so `dt` is added only once.
