### ISSUE TITLE
Behavior of `GridFunction::ProjectCoefficient(Coefficient &coeff)` in a Vector `FiniteElementSpace` (VDim > 1)

### ISSUE THREAD

**Issue by j-signorelli** [mfem/mfem#4179]
Hello,

I have a hopefully quick question as it has been unclear to me: Is `GridFunction::ProjectCoefficient(Coefficient &coeff)` supposed to project the scalar-valued coefficient onto each component if the `GridFunction` is defined on a vector `FiniteElementSpace` (vdim > 1)? Or just the first component?

When looking at the source code, it seems to me that it should be projecting the scalar coefficient onto each component, as it grabs an elements vdofs:

https://github.com/mfem/mfem/blob/70941b49b1217b638f4dfbb46b67662f86b54d10/fem/gridfunc.cpp#L2346-L2376

But I am not seeing this occur - here is a simple code that shows it only seeming to project onto component 0:

    Mesh mesh = Mesh::MakeCartesian2D(5, 5, Element::TRIANGLE, true, 1.0, 1.0);
    ParMesh pmesh(MPI_COMM_WORLD, mesh);
    mesh.Clear();

    H1_FECollection fec(1, pmesh.Dimension());
    ParFiniteElementSpace fespace(&pmesh, &fec, 2);

    ParGridFunction test_pgf(&fespace);
    ConstantCoefficient coeff(1.0);
    test_pgf.ProjectCoefficient(coeff);
    test_pgf.SetTrueVector();
    test_pgf.GetTrueVector().Print();

Thank you!

**Comment by v-dobrev** [comment]
I think the basic answer is: `GridFunction::ProjectCoefficient(Coefficient &coeff)` is not meant to be used with multi-component (vdim > 1) `GridFunction`s. This also applied to `GridFunction`s that use vector finite elements (like Nedelec or Raviart-Thomas FEs) even when vdim = 1.

Instead, in these cases, use `GridFunction::ProjectCoefficient(VectorCoefficient &vcoeff)`, or (in the case scalar FEs with vdim > 1) `GridFunction::ProjectCoefficient(Coefficient *coeff[])`.

**Comment by j-signorelli** [comment]
@v-dobrev Thank you!
