### ISSUE TITLE
Should d2udt2 be set to 0 when Dirichlet boundary condition is applied?

### ISSUE THREAD

**Issue by Wayne901** [mfem/mfem#4181]
I have a little suggestion/question about `ex23`. When the dirichlet boundary conditions are applied, `dudt` and `d2udt2` should be 0. However when I run the wave euqation example `ex23` and output the `d2udt2` vector in `ImplicitSolver` function, `d2udt2` is not zero at the boundary DoFs. I set `d2udt2`'s boundary entries to 0, and the final result is slightly different to the original code (`./ex23 -m ../../data/disc-nurbs.mesh -r 3 -o 4 -tf 5 --dirichlet`)
Result from original code:
![Wave_d2dut2_notset](https://github.com/mfem/mfem/assets/52063692/2c5b1400-b150-41fa-b4af-5ba4960a2a0d)
Result when boundary entris of `d2udt2` set to 0:
![Wave_d2dut2_setzero](https://github.com/mfem/mfem/assets/52063692/b454862d-a9ba-4156-a199-4215946a1b20)

I think the nonzero boundary DoFs in `d2udt2` comes from solving the linear system
$[M+\beta (\Delta t)^2K]\frac{d^2u(t+\Delta t)}{dt^2}=-Ku_{ImplicitSolve}$? But why would the solution on boundary entries be nonzero when $u_{ImplicitSolve}$'s are 0 there?

Please let me know if my choice of setting `d2udt2`'s boundary DoFs 0 is correct.

Thank

**Comment by Wayne901** [comment]
May someone give some hint on this problem? I'm still confused about it. The different result is not observed when `t_final <= 4`. I set `d2udt2` to 0 after `T_solver` with
```
T_solver.Mult(z, d2udt2);
for (int i = 0; i < ess_tdof_list.Size(); i++)
  d2udt2[ess_tdof_list[i]] = 0.0;
```

**Comment by Wayne901** [comment]
I wrote another wave equation code based on the coupled first-order equations, like `ex10`.
The result at t=5 is same as the `ex23` with `d2udt2` set to 0.

**Comment by IdoAkkerman** [comment]
I have checked the BC values and after zeroing the accelerations the solution values at the BC were of the order `e-105` which is effectively zero.
