### ISSUE TITLE
MPI Fortran library cannot be found when linking in downstream projects when STRUMPACK is enabled

### ISSUE THREAD

**Issue by white238** [mfem/mfem#4191]
I have ran into this on two different platforms on two different projects (Serac and Tribol). Basically when STRUMPACK is enabled the Fortran MPI library is being added to `MFEM_EXT_LIBS` in `config.mk` without being proceeded by the required link directory. This then fails in downstream projects which do not use the MPI compiler wrappers.

Here is the line from the installed `config.mk`, notice the `-lmpi_mpifh`:

```
MFEM_EXT_LIBS  = -Wl,-rpath,/darwin-monterey-skylake/clang-15.0.7/hypre-2.26.0-7pw5gnd7dg4id2c2izl3jem2ebu2obwb/lib -Wl,-rpath,/opt/local/lib/lapack -L/darwin-monterey-skylake/clang-15.0.7/hypre-2.26.0-7pw5gnd7dg4id2c2izl3jem2ebu2obwb/lib -L/opt/local/lib/lapack -lHYPRE -llapack -lblas -Wl,-rpath,/darwin-monterey-skylake/clang-15.0.7/superlu-dist-8.1.2-tug7hmo33eytlamvr5klll2pmqn7cozy/lib -Wl,-rpath,/darwin-monterey-skylake/clang-15.0.7/parmetis-4.0.3-z7aplyooc4amsrzt7kf25zez45jya5f4/lib -L/darwin-monterey-skylake/clang-15.0.7/superlu-dist-8.1.2-tug7hmo33eytlamvr5klll2pmqn7cozy/lib -L/darwin-monterey-skylake/clang-15.0.7/parmetis-4.0.3-z7aplyooc4amsrzt7kf25zez45jya5f4/lib -lsuperlu_dist -lparmetis -Wl,-rpath,/opt/local/lib/lapack -L/opt/local/lib/lapack -llapack -lblas -Wl,-rpath,/darwin-monterey-skylake/clang-15.0.7/metis-5.1.0-eay32llvqx54ksnhbnsnufqoirmommkx/lib -L/darwin-monterey-skylake/clang-15.0.7/metis-5.1.0-eay32llvqx54ksnhbnsnufqoirmommkx/lib -lmetis -Wl,-rpath,/opt/local/lib/lapack -L/opt/local/lib/lapack -llapack -lblas -Wl,-rpath,/darwin-monterey-skylake/clang-15.0.7/sundials-6.7.0-rmlkznks6uqems7qvsb5igcsi2535bnj/lib -L/darwin-monterey-skylake/clang-15.0.7/sundials-6.7.0-rmlkznks6uqems7qvsb5igcsi2535bnj/lib -lsundials_arkode -lsundials_cvodes -lsundials_nvecserial -lsundials_kinsol -lsundials_nvecparallel -lsundials_nvecmpiplusx -Wl,-rpath,/darwin-monterey-skylake/clang-15.0.7/strumpack-7.2.0-6nipalmuka4vuomxjexithcjm3txex2y/lib -L/darwin-monterey-skylake/clang-15.0.7/strumpack-7.2.0-6nipalmuka4vuomxjexithcjm3txex2y/lib -lstrumpack -Wl,-rpath,/opt/local/lib/gcc12 -L/opt/local/lib/gcc12 -lgfortran -Wl,-rpath,/opt/local/lib -L/opt/local/lib -lmpi_mpifh -Wl,-rpath,/darwin-monterey-skylake/clang-15.0.7/parmetis-4.0.3-z7aplyooc4amsrzt7kf25zez45jya5f4/lib -L/darwin-monterey-skylake/clang-15.0.7/parmetis-4.0.3-z7aplyooc4amsrzt7kf25zez45jya5f4/lib -lparmetis -Wl,-rpath,/darwin-monterey-skylake/clang-15.0.7/netlib-scalapack-2.2.0-csnbn2ofsw35nqft3eixqmlfegzxi2wr/lib -L/darwin-monterey-skylake/clang-15.0.7/netlib-scalapack-2.2.0-csnbn2ofsw35nqft3eixqmlfegzxi2wr/lib -lscalapack -Wl,-rpath,/darwin-monterey-skylake/clang-15.0.7/zfp-1.0.0-chn3rigdocmstcdug6pdeqoyaortdemh/lib -L/darwin-monterey-skylake/clang-15.0.7/zfp-1.0.0-chn3rigdocmstcdug6pdeqoyaortdemh/lib -lzfp -Wl,-rpath,/darwin-monterey-skylake/clang-15.0.7/netcdf-c-4.7.4-aop722vvi32nbqyyrpmttvmr3cjec4jk/lib -L/darwin-monterey-skylake/clang-15.0.7/netcdf-c-4.7.4-aop722vvi32nbqyyrpmttvmr3cjec4jk/lib -lnetcdf -Wl,-rpath,/darwin-monterey-skylake/clang-15.0.7/hdf5-1.8.23-5s2e72lbeemy3q434qootqchca5auy6e/lib -L/darwin-monterey-skylake/clang-15.0.7/hdf5-1.8.23-5s2e72lbeemy3q434qootqchca5auy6e/lib -lhdf5_hl -lhdf5 -Wl,-rpath,/darwin-monterey-skylake/clang-15.0.7/zlib-ng-2.1.6-rkvax3kjs6izyuurohpdnrdxgeswnfj5/lib -L/darwin-monterey-skylake/clang-15.0.7/zlib-ng-2.1.6-rkvax3kjs6izyuurohpdnrdxgeswnfj5/lib -lz
```

@btalamini  @ebchin

**Comment by v-dobrev** [comment]
This is normal since MFEM's `make config` does not really try to automate the config process for dependencies. It provides sensible defaults for the variables `<PACKAGE>_OPT` (compile flags) and `<PACKAGE>_LIB` (link flags). If these defaults do not work, the user is expected to define them on the `make config ...` command line or in their `config/user.mk` file (which should be copied from `config/defaults.mk` and then modified where needed).

In the case of STRUMPACK, `STRUMPACK_LIB` uses another variable to configure the MPI+fortran dependence -- `MPI_FORTRAN_LIB`. In your case, it sounds like it will be sufficient to just modify accordingly this variable and leave `STRUMPACK_{OPT,LIB}` as they are.

For example, on my Mac, I modify `MPI_FORTRAN_LIB` by adding the following to my `user.mk`:
```makefile
# Additional Fortran library:
MPI_FORTRAN_LIB += -L$(BREW_DIR)/Cellar/gcc/13.1.0/lib/gcc/13 -lgfortran
```
where `BREW_DIR` is the path to my Homebrew directory.

In your case, you probably just need to add the path to where `libmpi_mpifh.*` is, before `-lmpi_mpifh`. Normally, this path will already be specified on the linking command line, so it is not explicitly needed. However, in your case, the MPI link path probably appears after `-mpi_mpifh`. So maybe a simpler solution is to just move the MPI link path before the MFEM flags.

**Comment by v-dobrev** [comment]
I just realized that you may be using `config.mk` file from the CMake build system where things should be a bit more automated. Are you using CMake to build MFEM?

**Comment by white238** [comment]
`mpi_mpifh` was in the correct directory but no `-L<mpi directory` was being added to the link line.

**Comment by v-dobrev** [comment]
Shouldn't `-L<mpi directory> -lmpi` (or something like that) be added to the link line where you're linking an MPI executable without the MPI compiler wrapper?

If we want to add these flags to `MFEM_EXT_LIBS`, (by setting `MPI_{OPT,LIB}`) we may need a lot of extra logic to figure out what flags are actually added by the MPI wrapper -- it is not always just `-I<mpi dir>/include` and `-L<mpi dir>/lib -lmpi`. It is much more portable to just rely on the MPI wrapper, I think.

Maybe specifically in Spack this is easier to do? Do you know if we can get the needed MPI flags from Spack or the MPI-provider packages in Spack?

**Comment by white238** [comment]
> Shouldn't `-L<mpi directory> -lmpi` (or something like that) be added to the link line where you're linking an MPI executable without the MPI compiler wrapper?

Kind of, it generally adds an absolute path to the MPI libraries (we don't add the Fortran MPI library because we don't explicitly require it) but that isn't the problem. `MPI_EXT_LIBS` adds the Fortran MPI library to the link line w/o the directory to find it. 

> If we want to add these flags to `MFEM_EXT_LIBS`, (by setting `MPI_{OPT,LIB}`) we may need a lot of extra logic to figure out what flags are actually added by the MPI wrapper -- it is not always just `-I<mpi dir>/include` and `-L<mpi dir>/lib -lmpi`. It is much more portable to just rely on the MPI wrapper, I think.

The includes are and the absolute C++ libraries are added by our project but no `-L`'s. 

> Maybe specifically in Spack this is easier to do? Do you know if we can get the needed MPI flags from Spack or the MPI-provider packages in Spack?

Staring at the multiple levels, I think what is happening is the Spack package adds the proper information to `STRUMPACK_LIB` so that MFEM itself builds, but that information is not getting passed to the `config/defaults.mk`|whatever generates the `config.mk`. I could be wrong but I think this line is injecting the `$(MPI_FORTRAN_LIB)` but not the `-L`:

https://github.com/mfem/mfem/blob/ac8858060532274b200b4d121b518138c7ccf9e4/config/defaults.mk#L331

Does the Makefile build system not override that command line `STRUMPACK_LIB` before it generates the outputted `config.mk`? I don't fully understand how your Makefile generates that file w/o more effort.

**Comment by white238** [comment]
When @btalamini gets back I can get the command line from Spack to see if it will show more information of what is going on. I can't reproduce this myself.

**Comment by v-dobrev** [comment]
Just to clarify: the MFEM's spack packages does add the correct path for `-lmpi_mpifh` or, more precisely, what I think is the correct path derived from the MPI package: the MPI prefix + `/lib`. This is done on this line:
```python
                        sp_lib += [ld_flags_from_dirs([mpi.prefix.lib], ["mpi_mpifh"])]
```
([direct link to the above code](https://github.com/spack/spack/blob/c38ef72b0668b02a566ce7f5cee114f776ccc9b6/var/spack/repos/builtin/packages/mfem/package.py#L751-L752))

In this context, the variable `mpi` is defined as:
```python
                    mpi = strumpack["mpi"]
```
([direct link to the above code](https://github.com/spack/spack/blob/c38ef72b0668b02a566ce7f5cee114f776ccc9b6/var/spack/repos/builtin/packages/mfem/package.py#L748))

Judging by the value of `MFEM_EXT_LIBS` posted above, the path `mpi.prefix.lib` resolved to `/opt/local/lib`. Is this not the correct path? Maybe the libraries are in `lib64` sub-directory and not in `lib`? If this is the case, I can fix the code to actually look at the file system to determine the right path.

**Comment by white238** [comment]
Narrowing this down and it is a problem/missing feature in CMake:

https://github.com/spack/spack/issues/24685

We are attempting to allow Spack to build the MPI itself, hopefully this goes well.

Thanks for helping track this down and there is nothing MFEM could do to work around this.
