### ISSUE TITLE
Robin boundary condition for curl operator

### ISSUE THREAD

**Issue by luyucen** [mfem/mfem#4193]
Hi!
I got a question about this Robin boundary condition for the curl operator in 
https://mfem.org/fem_bc/.
Usually in electromagnetism, $n\times(\lambda\nabla\times u +\gamma n\times u)=n\times f$ instead of the one listed in the website $n\times(\lambda\nabla\times u +\gamma u)=n\times f$ is used, as the first-order absorbing boundary condition and impedance boundary condition both take the former form. 
I wonder which one is actually implemented in mfem. I'd appreciate it if any could help me!

**Comment by mlstowell** [comment]
Hi, @luyucen,

I think you are correct. Our documentation seems to be wrong here. MFEM doesn't actually "implement" a Robin boundary condition but we should provide a clearer example of this. The usual approach with the curl-curl operator would be to add a boundary integral to the bilinear form involving a mass-matrix-like integrator and the $\gamma$ coefficient. The usual choice for the mass integrator in this case would be `VectorFEMassIntegrator` which would produce a term $n\times(\gamma n\times\vec{u})$ as you mentioned. However, other mass-like integrators could be provided to produce $n\times(\gamma\vec{u})$ although I don't know why someone would want that.

Thanks for bringing this to our attention. Incidentally, it looks like the Robin BC for the div-div operator is also written incorrectly.

Best wishes,
Mark
