### ISSUE TITLE
Mixed Bilinear Form Integrator for Strong Laplacian in IGA

### ISSUE THREAD

**Issue by michi002** [mfem/mfem#4194]
As far as I saw there is now implementation of bilinear forms involving strong Laplacians.
In the IGA setting, this would make sense for C^1 elements and might be beneficial for least squares problems or the biharmonic equation. 
I am specifically thinking to implement these bilinear forms
```math
a_1(u,v) = \int_{\Omega} \Delta u \, \Delta v \,  dx
```
```math
a_2(u,v) = \int_{\Omega} \Delta u \,   v \,  dx 
```
And this linear form
```math
b(v) = \int_{\Omega} f  \, \Delta v  \, dx
```

Is there interest in this? I would volunteer to implement them, but I might need some help from more advanced MFEM developers on the way. (I have already tweeked MFEM here and there, but never pushed something)

Greetings,
Michael

**Comment by michi002** [comment]
I have started implementing this as a "mfem::MixedDiffusionDiffusion" integrator. 
Right now I encountered two things, where I would need help:
-) I have read the "CONTRIBUTING.md" file and proceeded as stated there. But I cannot push a development branch to the server, as I am only in the users group. What do I need to do to contribute.
-) I did not find much about IGA on the website. Is there a resource, to find out how the "mesh" input files are structured and how MFEM does handly NURBS geometries?

Thanks and greetings,
Michael

**Comment by IdoAkkerman** [comment]
Regarding the mesh documentation I was doubting what to put on the website.
Cox de Boor algorithm and such is a lot of effort to put on the site but not useful.
I did not think about the mesh format... but that is an obvious one.
I will try to write something, perhaps you (@michi002) can help me by judging whether it is clear and useful.

**Comment by bslazarov** [comment]
Hi Michael,

You should be able to contribute now. 

Best regards, Boyan

**Comment by michi002** [comment]
> I opened a related issue #4238 related to the Laplace terms. I have also started a NURBS section on the website, related to the NURBS H(div) and H(curl) PR.
> 
> I have implemented the terms as mention in the issue. I called it`LaplaceLaplaceIntegrator` and `BiHarmIntegrator`as alias.

@IdoAkkerman 
Perfect. I saw your post today, but was on the mobile, so you were first.
Did you already implement this bilinear forms? If yes on which branch?
I would happly help you in improving the documentation, as well as coding the bilinear forms, if it did not happen yet.
Some questions arised in your post:
Do you want to have this operators for H^2 conforming functions (that is what I need), implying that we need C^1 ansatz functions. Do you also want to consider instead of the laplacian operators of the form
$Tu = \nabla \cdot \left( A \nabla u\right)$
wher $A$ is a matrix coefficient with the bilinear form
$a(u,v) = \langle Tu, Tv\rangle$?
This would imply, that we somehow would have to deal with the chain rule for non-constant coefficients.

Greetings,
Michael

**Comment by IdoAkkerman** [comment]
I have not commit yet. I can do that tomorrow after noon.

**Comment by IdoAkkerman** [comment]
I have committed my stuff in  the branch `dev-stab-mini` .

The miniapps in `miniapps/stabilized` are still very rough. But things seem to converge:
For instance:
- `./laplace -b -o 3`  shows the convergence of the Galerkin form for the biharmonic problem. With essential BCs on the solution.
- `./ex_condif -s 1 -o 3` shows the convergence of the SUPS formulation for convection diffusion.

**Comment by michi002** [comment]
@IdoAkkerman did push it to the general mfem repository? I cannot find that branch (also not on the Website).
But maybe I am just to stupid.
And thank you for sharing :)
