### ISSUE TITLE
Troubleshooting mesh ordering issue in Gmsh-generated mesh

### ISSUE THREAD

**Issue by sungho91** [mfem/mfem#4197]
Hi everyone,

I'm testing the use of an external mesh generated by `Gmsh` in my code. I created a mesh with triangles (see att. fig.) and ran a simple model with full assembly. The result was as expected. However, when I tried to run my model with partial assembly, it terminated with an error message.

It seems like there may be an issue with the ordering of elements in the mesh. Perhaps reordering or some other adjustments are required, I think.

Any comments will be helpful for me.

Thanks,

Sungho
```
MFEM abort: Finite element not suitable for lexicographic ordering
 ... in function: mfem::ElementRestriction::ElementRestriction(const mfem::FiniteElementSpace&, mfem::ElementDofOrdering)
 ... in file: fem/restriction.cpp:53
```

![stress_yy](https://github.com/mfem/mfem/assets/40257026/99c5199b-de15-492b-a870-83c566c45176)

**Comment by artv3** [comment]
Hi @sungho91 , mfem does not support partial assembly for simplex elements.

**Comment by sungho91** [comment]
Hi @artv3,

I understand. Why doesn't MFEM support it? Is it due to technical issues or is it fundamentally impossible?

**Comment by v-dobrev** [comment]
It just has not been a priority to add support for partial assembly on triangles/tets but we definitely want to add that.

Depending on what integrator you need, you may be able to use partial assembly on triangles/tets using one of the libCEED backends. @YohannDudouit, can clarify which integrators can use the libCEED backend with simplices. The libCEED library is available here: https://github.com/CEED/libCEED.

**Comment by YohannDudouit** [comment]
@sungho91 Which integrators are you trying to use?

**Comment by sungho91** [comment]
@v-dobrev Thanks for your information. Yes, indeed, many third-party meshers generate triangles/tets, so enabling p-assembly for those elements is super desirable. I'll take a look at libCEED.

@YohannDudouit, my code is based on `Laghos`. So, it uses mass integrators for H1 and L2 spaces, respectively. Also, it uses a force integrator.

**Comment by YohannDudouit** [comment]
@sungho91 The Mass integrator is supported for both H1 and L2, so using the libCEED backend should work there. However, I'm not too familiar with the force integrator, and this would probably need to be implemented using libCEED, I can assist you in doing so if you're interested.
