### ISSUE TITLE
Any plan to add two operators into mfem?

### ISSUE THREAD

**Issue by TangLaoya** [mfem/mfem#42]
Dear Tzanio,

I am glad to hear that new version 3.1 is released and the non-conforming mesh is supported completely. I wish the mfem can be applied in electromagnetic calculation. In this field, two operators are often used:
1) flux
\phi _m = \int_S {N{\bf{B}} \cdot {\bf{\hat n}}dA = } \int_S {NB_n dA}
2) Electromotive Force
\xi = \oint_C {E \cdot d\ell }

Is there any plan to add these two operators into mfem?

Thanks,
Tang Laoya

**Comment by mlstowell** [comment]
Hello, Tang,

This is an excellent question and definitely something we should support.

In theory it would be quite simple to add.  If we have a vector field using Raviar-Thomas basis functions then its flux through a surface is simply a sum of its degrees of freedom on that surface where the individual terms are either added or subtracted according to their orientations with respect to that surface.  Similarly, the contour integral of a vector field using Nedelec basis functions is a sum of the degrees of freedom along the contour where we again must account for orientation.

So to perform these integrals we could express an oriented surface or curve as a vector and compute the integral by taking inner products with these vectors.  MFEM does have a means of tagging surfaces but I don't think it can tag curves (at least not in 3D).  Also, I'm not sure about the orientation of surfaces or curves.

We should look into adding more flexible support for oriented surfaces and curves into our mesh classes.  Once we have that the rest should be easy…

Thanks for the suggestion!
Mark

**Comment by tzanio** [comment]
Hi Tang,

Regarding 1), we do have the class [BoundaryNormalLFIntegrator](http://mfem.github.io/doxygen/html/classmfem_1_1BoundaryNormalLFIntegrator.html) which could be used to compute the integral you want if you set the RT function B to be the VectorCoefficient in that integrator and then sum the entries corresponding to the dofs on the faces of interest (e.g. by marking such faces with a specific attribute).

We also have the similar class [BoundaryTangentialLFIntegrator](http://mfem.github.io/doxygen/html/classmfem_1_1BoundaryTangentialLFIntegrator.html) which could be used to compute 2) in 2D.

However, as Mark pointed out, we do not have support for edge integrators in 3D. We agree that it is a good idea to introduce such a support, and we will probably do that at some point in the future.

One approach for that could be to introduce edges in the "boundary" section of the mesh, which mark with their attributes edge sets that can be integrated over later. This will require some changes in the handling of the mesh, but it should be doable.

Thank you for the good suggestion!
Tzanio

**Comment by TangLaoya** [comment]
Dear Tzanio amd Mark,

Thank you for your kindly reply and your great job!

Tang Laoya
