### ISSUE TITLE
Linear Elasticity material and forces

### ISSUE THREAD

**Issue by mov-rax-rbx** [mfem/mfem#4201]
Hi,

I am solving the Linear Elasticity problem (Von Misses stress and Displacement) and for this I use ElasticityIntegrator. I apply 2 types of force to the model - gravity (VectorDomainLFIntegrator) and force applied to the surface (VectorBoundaryLFIntegrator). I also have a material with the following parameters:

1) Lame parameters (used by ElasticityIntegrator)
2) Density
3) Compressive strength
4) Tensile strength
5) Yield strength 

Could you please advise on how to correctly add these material parameters to Linear Elasticity calculations?

I apologize for the possibly incorrect question - I would be grateful for any help.

Thank you

**Comment by j-signorelli** [comment]
Hi @mov-rax-rbx,

This is more of an elasticity question than an MFEM-related one - the book _Theory and Practice of Finite Elements_ by Ern and Guermond, Section 3.4 outlines well what `ElasticityIntegrator` implements -- it is for linear isotropic elasticity. Density, ultimate compressive and tensile strengths, and yield strength aren't part of the model. A good reference for understanding the elasticity aspect in more detail is _The Linearized Theory of Elasticity_ by Slaughter.

**Comment by mov-rax-rbx** [comment]
@j-signorelli Thank you.
