### ISSUE TITLE
Enzyme for BilinearFormIntegrator

### ISSUE THREAD

**Issue by PinguProgrammer** [mfem/mfem#4217]
Hello! Is there a way to use Enzyme to do automatic differentiation of a `BilinearFormIntegrator` for use in `NonlinearForm`? I noticed ex16p_newton.cpp [here](https://github.com/mfem/mfem/pull/4073) creates a wrapper manually. Instead of using different integrators in`AssembleElementGrad`, can Enzyme AD be used to automatically perform differentiation on calls to `BilinearFormIntegrator::AssembleElementVector`?

**Comment by jandrej** [comment]
In general this is possible, yes. Creating the derivative on an element-vector level is more resource intensive than necessary. We're in the process of creating streamlined interface to allow Enzyme enabled derivatives on the quadrature point level which will be the most efficient and GPU compatible way.

**Comment by PinguProgrammer** [comment]
Thank you!
