### ISSUE TITLE
A typo in the description of the normal vector calculation

### ISSUE THREAD

**Issue by Tomcat4891** [mfem/mfem#4218]
Hello.

What does the variable "n" mean in the following code example? 

[https://mfem.org/howto/outer_normals/](https://mfem.org/howto/outer_normals/)

The components of the normal vector must be stored in the variable "normal".

**Comment by tzanio** [comment]
Good catch, thanks @Tomcat4891.

Fixed in https://github.com/mfem/web/commit/a59f07aef414d9af2e19c87196658de5d5c0547d
