### ISSUE TITLE
Memory allocation issues with `FindPointsGSLIB`

### ISSUE THREAD

**Issue by victor-decaria-nnl** [mfem/mfem#4242]
I've recently been experiencing issues with `FindPointsGSLIB` after migrating to a new OS, specifically for jobs using the CUDA backend. This is weird since my understanding is that gslib is entirely on host. I haven't ruled out that this is an issue with my HPC configurattion, but my GPU jobs run fine if I comment out calls to `FindPointsGSLIB`.

I've included [(gslib_err.tgz)](https://github.com/mfem/mfem/files/14951459/gslib_err.tgz) a minimal program `gslib_error.cpp` which just loads a mesh and looks for a point. For me, this randomly fails for both tet and hex meshes. The meshes are 3D with a cylinder obstacle, linear elements, and around 10-100 thousand nodes. They were made with gmsh.

A sample run is

`./gslib_error -m obstacle-hex.msh2 --device cuda`

About one in five times I get the following error which is within `gslib`.

`ERROR (proc 0000, src/sort_imp.h:497): allocation of 15638880 bytes failed`

I get the same error with `obstacle-tet.msh2` with a different number of bytes. Because this is random, I'm not sure it's reproducible.

This allocation is very small, so I'm guessing gslib is making many such allocations. Are there any measures to reduce the memory footprint of gslib? I've already set `npt_max` to 1. The issue goes away for me when I request an entire node, but I'm not sure why since it shouldn't need that much memory.

Other info:
Host compiler - GCC 10.5.0
OS - RHEL 8
cuda 11.8.0
MPI - mvapich2 2.3.7
GPUs - Nvidia V100, 32 GB

Thank you for any assistance.

**Comment by kmittal2** [comment]
@victor-decaria-nnl, I looked at the driver you shared and I see that the dominant storage cost is coming from the two hash tables that `findpts` constructs during the `setup` phase. In total, they should be requesting about 20 mb for a 3D mesh with 100k elements. While it is not usual to run a 3D problem that big on 1 rank, the amount of memory requested in your driver is not prohibitively high. 

At the moment, the hash table sizes cannot be controlled by the user through the `FindPointsGSLIB` interface, and I will have to look into it.

**Comment by victor-decaria-nnl** [comment]
@kmittal2 Thanks for the response. If all it's requesting is 20 mb, the issue could be with my build or environment somehow.

I build mfem with spack and noticed that it grabs gslib 1.0.7, but there is gslib 1.0.8 available. Should I try the newer one or the latest from master just in case?

I will also try building with `-DPRINT_MALLOCS=1` for debugging. Are there other useful compiler flags for information?

**Comment by victor-decaria-nnl** [comment]
@kmittal2 After some digging, I realized that the issue may be due to my build system. I build mfem as a shared library while gslib is built statically, and I am going to try adding the cflag `-fPIC` to the gslib build. The hpc where I experience this issue is down this week, so I won't be able to update you for a little.

**Comment by kmittal2** [comment]
Sounds good @victor-decaria-nnl, keep us posted.

**Comment by victor-decaria-nnl** [comment]
@kmittal2 @jandrej After a lot of experimentation, I think the issue was with my software stack/environment after all. I've since tried different combinations of compilers, mpi implementations, and cuda versions and I've found some that don't get the gslib error anymore. Not satisfying, but I think we can close the issue.
