### ISSUE TITLE
Question about potential AMR improvements

### ISSUE THREAD

**Issue by Marinovsky** [mfem/mfem#4249]
Hey there! I was reading the MFEM implementation of AMR in https://docs.mfem.org/html/classmfem_1_1ThresholdRefiner.html#a38c1c7e70aa4854dac52e5a076c220e7 and I noticed you were sequentially traversing all the elements in the mesh each time you were going to refine it, so I was wondering if it was possible to refine the mesh in a more efficient way. For instance, I know that Paramesh(https://ntrs.nasa.gov/api/citations/19990110710/downloads/19990110710.pdf) used some sort of hierarchical approach dividing the mesh into half's (similarly to a binary search). Additionally, I was wondering if there were plans to implement AMR with reinforcement learning in MFEM, as shown in this paper from LLNL scientists (https://proceedings.mlr.press/v206/yang23e/yang23e.pdf).

Best Regards,

**Comment by tzanio** [comment]
ping: @jakubcerveny, @rw-andersonm, @tarikdzanic
