### ISSUE TITLE
scale factor for integrators

### ISSUE THREAD

**Issue by Dan2997925** [mfem/mfem#425]
I don't see a way to add a scale factor for integrators when they are added to a bilinear form. Am I missing something?

If A and B are BilinearFormIntegrators, I'd like to form the composite operation alpha A + beta B, where alpha and beta are doubles. 

Note that my BilinearFormIntegrators already have spatially varying Coefficients so what I really want is something like alpha A(f(x)) + beta B(g(x)) where A and B are BilinearFormIntegrators and f(x) and g(x) are coefficients, and alpha and beta are just doubles.

**Comment by mlstowell** [comment]
Hi, Dan,

No, I don't think you're missing something.  I've often thought this would be convenient but it does not currently exist.  The way I've done this in the past is to use the TransformedCoefficient:

double prodFunc(double a, double b) { return a * b; }

ConstantCoefficient alphaCoef(alpha);
TransformedCoefficient alphafCoef(alphaCoef, fCoef, prodFunc);

Best wishes,
Mark

**Comment by v-dobrev** [comment]
Another option could be to extend class [SumIntegrator](https://github.com/mfem/mfem/blob/9ccb8524a1f77f525c0e37116a63fd25769ee709/fem/bilininteg.hpp#L152) with optional scaling constants.

**Comment by Dan2997925** [comment]
Ah OK it looks like TransformedCoefficient will meet my immediate needs.

**Comment by fanronghong** [comment]
Hi @mlstowell ,

If one is `VectorConstantCoefficient`, another is `ConstantCoefficient`, how to form a `TransformedCoefficient`. See below in detail.

```
double Plus(double a, double b) 
{ 
    return a + b; 
}
double Product(double a, double b) 
{ 
    return a * b;
}
int main()
{
    ConstantCoefficient one(1.0);
    ConstantCoefficient two(2.0);
    TransformedCoefficient one_plus_two(&one, &two, Plus);

    double* data = new double [2] {3.0, 3.0};
    Vector three(data, 2); 
    VectorConstantCoefficient three_coeff(three);
    TransformedCoefficient two_product_two(&two, &two, Product); // OK
//    TransformedCoefficient two_product_three(&two, &three_coeff, Product); // compile error

    delete [] data;
}

```
