### ISSUE TITLE
Error when reading a Cubit mesh

### ISSUE THREAD

**Issue by Wayne901** [mfem/mfem#4251]
I export mesh from Cubit as Genesis format (.g) with either `Use Normal Format` or `Use NetCDF4/HDF5 Format`. Reading the mesh in MFEM returns:
```
MFEM abort: Fatal NetCDF error: NetCDF: Unknown file format
 ... in function: void mfem::Mesh::ReadCubit(const char*, int&, int&)
 ... in file: /home/wayne/libs/mfem-4.6-cubit/mesh/mesh_readers.cpp:2860
```
Am I missing something?
[mesh.zip](https://github.com/mfem/mfem/files/14998946/mesh.zip)

**Comment by jandrej** [comment]
You have to export using `Exodus .e` format with the option `Use NetCDF4/HDF5 Format`

**Comment by Wayne901** [comment]
I'm using Coreform Cubit 2022.4 with educational license. Is it different to [Cubit](https://cubit.sandia.gov/2024/03/26/cubit-16-16-released-march-26-2024/)?
