### ISSUE TITLE
How to prevent negative value with Legendre basis?

### ISSUE THREAD

**Issue by sungho91** [mfem/mfem#4267]
Hello all,

I have a quick question. I tried to interpolate a certain value (0.5) in L2 space with 1st order initially using coefficient projection within a certain portion of my domain.

I tested two basis functions: positive (Bernstein polynomials) and non-positive (Legendre polynomials) basis.
The figure shows that using Legendre polynomials results in negative values, but Bernstein does not. I thought that even if Legendre has a non-positive portion, when we sum up all the weights, we obtain a positive result. Is there any way to prevent negative values with Legendre?

The reason why I tried to use Legendre is because I found that  positive basis functions with strain softening show unreasonable behaviors with high-order, I have to conduct more tests though.

Thanks

Sungho

![g1](https://github.com/mfem/mfem/assets/40257026/f29dd500-2f38-446e-adbe-c0c6ef61239a)

**Comment by v-dobrev** [comment]
For best results, I'd suggest using a mesh that is aligned with the discontinuity in the coefficient, if possible. If not possible to use aligned mesh, using the Bernstein basis (at least for the coefficient "projection" step) is the better option to avoid oscillations. With the Legendre basis, the projection is actually just polynomial interpolation, so it is normal to get oscillations around discontinuities of the coefficient. With the Bernstein basis, the "projection" is actually just approximation (1st order), however it is guaranteed to not produce oscillations.

**Comment by v-dobrev** [comment]
Note that the code outside the coefficient projection step can use any basis, just the FE space on which you project the coefficient needs to use Bernstein basis.
