### ISSUE TITLE
Why not directly use the easily computable basis functions? in the question 566

### ISSUE THREAD

**Issue by kaipengliuHIT** [mfem/mfem#4278]
I am currently researching the "nedelec element" for "nurbs versions" for IGA. I carefully read the answer to question #566 and noticed that the Ti matrix only exists in the calculation of shape functions for triangular or tetrahedral elements. Why don't we directly use the simple and easy to calculate basis functions, and why do we need to undergo a transformation。Is it because the basic function of this simple calculation does not meet this condition:f_j(φ_i)=δ_{i,j}?

**Comment by v-dobrev** [comment]
Yes, we need basis functions on individual elements in the mesh that can be easily stitched together globally. This easy with the "nodal" basis `{φ_i}` while with the "easy to evaluate" basis `{ψ_i}` it is not.
