### ISSUE TITLE
Question on triangle orientation

### ISSUE THREAD

**Issue by kvoronin** [mfem/mfem#428]
Hello,

Does one need to have a correspondence between orientation as geometry constants for triangle, orientations, https://github.com/mfem/mfem/blob/9ccb8524a1f77f525c0e37116a63fd25769ee709/fem/geom.cpp#L684 and orientation check provided by GetTriOrientation https://github.com/mfem/mfem/blob/9ccb8524a1f77f525c0e37116a63fd25769ee709/mesh/mesh.cpp#L3493?

For now, I see that, in the first case, {2,0,1} is the third orientation while in the latter it is {1,2,0}. 

Thanks,
Kirill

**Comment by kvoronin** [comment]
I guess it's ok because the only thing which is done with orientations is probably to determine its sign, which is the same for both choices. Is this correct?

**Comment by v-dobrev** [comment]
The connection between the two is given in the comment:
https://github.com/mfem/mfem/blob/9ccb8524a1f77f525c0e37116a63fd25769ee709/mesh/mesh.cpp#L3493-L3498
Some discussion about the orientations is given here:
https://github.com/mfem/mfem/blob/9ccb8524a1f77f525c0e37116a63fd25769ee709/fem/geom.hpp#L138-L142

In the case you mention, `{2,0,1}` is the "forward" orientation, and `{1,2,0}` is the "backward" orientation - these two are inverses of each other.

**Comment by kvoronin** [comment]
Ok, thank you.
