### ISSUE TITLE
The best way to define auxiliary freedoms on part of the region

### ISSUE THREAD

**Issue by Wayne901** [mfem/mfem#4284]
Hi, is there an example to define auxiliary DoFs on part of the mesh region, or only on some boundaries?
One of the case is, for example, the transient wave equation with PML region. Some auxiliary variables representing the time-integral of `u` are required in PML regions. These auxiliary variables are coupled with original freedoms `u`.

**Comment by tzanio** [comment]
The only way to do that currently is through `SubMesh`
