### ISSUE TITLE
suspect gzstream class needs privatized copy constructors

### ISSUE THREAD

**Issue by markcmiller86** [mfem/mfem#429]
I ran into a Klocwork error in a similar version of this code in the VisIt sources. The problem is that the gzstream classes need to create privatized copy constructors to prevent inadvertent copying and then possible double delete of the internal stream pointers they are using. This is a low likelihood of occurrence because C++ doesn't generaly permit copying of iostreams anyways but it would be good to fix.

**Comment by tzanio** [comment]
@markcmiller86, does #438 address this?
