### ISSUE TITLE
NURBSMeshRules::Finalize(Mesh const& mesh) only work on 3D

### ISSUE THREAD

**Issue by kaipengliuHIT** [mfem/mfem#4293]
maybe patchRule->Finalize(mesh); in the NURBS example only works on 3D mesh

**Comment by dylan-copeland** [comment]
Hello @kaipengliuHIT, the example `nurbs_patch_ex1.cpp` currently works only in 3D. The sample runs use the 3D mesh `data/beam-hex-nurbs.mesh`. There is an error message in `DiffusionIntegrator::AssemblePatchMatrix_reducedQuadrature` if the dimension is not 3.

This example demonstrates patch-based integration rules, as opposed to the usual element-based integration used in MFEM. There are computational savings with patch-based integration, more so in 3D than 2D. This is why 3D is the main target for this example. With some further implementation, a 2D example could be supported, and it should be straightforward to do so by following the 3D example.
