### ISSUE TITLE
Map between indices of elements of Mesh and ParMesh

### ISSUE THREAD

**Issue by martemyev** [mfem/mfem#43]
Dear All,

As far as I understand, after I create a ParMesh based on a Mesh, the indices of the elements are rewritten, so that they are local with respect to the process. Am I right? If so, I'm wondering if I can retrieve an element index in the global Mesh based on its local index in ParMesh. The reason why I need this is because for many of my problems I have cell-wise constant coefficients, i.e. they are constant within one grid cell. Therefore, I've created a simple class to work with such coefficients that computes the value of the coefficient based on the ElementNo of a transformation. Now, I faced a situation when I can't use this approach as ElementNo is local w.r.t. each process and the values of the coefficients that go in the assembling procedures are incorrect.

Any hints would be highly appreciated!

Thanks,
Mikhail

**Comment by martemyev** [comment]
To be specific, this is the class that I use as a coefficient

```cxx
class CWConstCoefficient : public mfem::Coefficient
{
public:
  CWConstCoefficient(double *array, bool own = 1)
    : val_array(array), own_array(own)
  { }

  virtual ~CWConstCoefficient() { if (own_array) delete[] val_array; }

  virtual double Eval(mfem::ElementTransformation &T,
                                const mfem::IntegrationPoint&)
  {
    return val_array[T.ElementNo];
  }

protected:
  double *val_array;
  bool own_array;
};
```

Then, I use it like this:
```cxx
int nx = 100; // number of mesh cells in x-direction
int ny = 100; // number of mesh cells in y-direction
double *mu_array = new double[nx*ny];
read_binary_file(filename, mu_array); // fill up the mu array
CWConstCoefficient mu(mu_array);
// then use 'mu' in integrators
```

**Comment by barker29** [comment]
Hi Mikhail,

When I've done similar problems, I've set the attribute of each element (using Element.SetAttribute()) on the serial mesh. Then these attributes (unlike the element numbers) are preserved after parallel mesh partitioning.

Then you can use PWConstCoefficient with your data -  you may even be able to use the PWConstCoefficient.Read() method with your file. 

Hope this helps,

Andrew

**Comment by martemyev** [comment]
Hi Andrew,

Thank you for the idea - this indeed should work. I haven't found Read() method though, but that's not that important.

Thanks,
Mikhail

**Comment by barker29** [comment]
I should have said the Vector.Load() method, and then use the PWConstCoefficient(Vector) constructor.

**Comment by martemyev** [comment]
Ah, right! Thanks a lot!

**Comment by tzanio** [comment]
Another advantage of Andrew's approach is that element attributes are preserved under serial and parallel refinement, including AMR.
