### ISSUE TITLE
Electromagnetic skin effect in different wire shapes, in 2D.

### ISSUE THREAD

**Issue by denislachapelle** [mfem/mfem#4300]
I looked at the examples but I do not find any that compute the current density distribution in a wire according to frequency. When AC current circulate in a wire, the current has a tendency to concentrate on the perimeter of the wire, this is the skin effect. My goal is to use a 2D section of the wire and compute the current density distribution for various frequencies and then of various section shapes.

Is there an example that I can start from? If not can I have some guidance?

Thank you,
Denis

**Comment by EMinsight** [comment]
Maybe use **J**=σ**E**. Get the E from the cross section and multiply by the sigma.

**Comment by aschaf** [comment]
You can take a look at `ex22`. It only needs some minor modifications to get exactly what you need.

**Comment by denislachapelle** [comment]
Thank you for your help, 

In the heading comments of ex22 it is written: "In each case the field is driven by a forced oscillation, with angular frequency omega, imposed at the boundary or a portion of the boundary."

This sentence seems to implied ex22 is simulating in time and the boundary are driven by a sine wave. In the code the boundary are set to 1. I am confused.

For skin effect I was expecting the boundary be fix as example 1 for the current density.

I deducted the equation for the current density in 2D (div grad Jz - i w mu sigma Jz + w^2 eps mu Jz = 0) and it look like problem #1 (case 0), so I will start from there.

Thank you again,
Denis

**Comment by denislachapelle** [comment]
I succeeded, you can close the issue.
Thank you very much,
Denis
