### ISSUE TITLE
Unexpected performance of different preconditioners

### ISSUE THREAD

**Issue by Wayne901** [mfem/mfem#4301]
Hello, I'm seeking a proper preconditioner for the definite Maxwell system produced by electromagnetic problems with implicit time-stepping. I tested my code as well as `ex1p` and `ex3p`, 2 things confuse me:
1. Jacobi preconditioner has the best performance in time than others (SSOR, BoomerAMG, AMS in most time). Shouldn't it be the most ineffective one? The `maxwell` miniapp also apply Jacobi preconditioner for the Symplectic time Integration solver.
2. Jacobi outperforms AMG preconditioner most time. I compared them on a Fichera mesh for `ex3p`, change the `muinv` term from 1e-6 to 1e6. AMG requires less time only when `muinv` is around `1`. However AMG should has better performance as shown in [Parallel Auxiliary Space AMG for H(Curl) Problems](https://www.[osti.gov/servlets/purl/1670552](https://www.osti.gov/servlets/purl/1670552)). 

In my implicit EM solver case `(A = (E,E) + (dt*c_speed)^2(curl E, curl E))`, when frequency is around 1GHz and time step is 1/10 to 1/100 of `1/frequency`, Jacobi preconditioner needs lowest time. But I believe it's not the final solution ...

**Comment by jandrej** [comment]
When choosing a preconditioner you have to think about the matrix structure. In an implicit time dependent formulation your most dominant eigenvalues are determined by a mass-type matrix with a scaled diagonal proportional to the time step chosen. As a result you see that the inverse diagonal (Jacobi) is an efficient preconditioner.

**Comment by najlkin** [comment]
Yes, choice of the preconditioner very much depends on the problem. AMS or similar preconditioners are mainly useful for diffusive cases or hyperbolic with long steps (which get diffusive as well due to numerical effects). For hyperbolic problems with short steps, your solution is just the same profile, but slightly shifted, so there is nothing much to precondition other than a plain integral projection and a cheap Jacobi makes most sense intuitively :wink:

**Comment by Wayne901** [comment]
Thank you jandrej and najlkin, I've checked an article [Wathen](https://people.maths.ox.ac.uk/wathen/preconditioning.pdf) and it seems Jacobi preconditioner is the appropriate one for mass matrix.
I mostly dealt with Poisson and Helmholtz (definite and indefinite) equations before, where Jacobi behaves poorly. Is there any more efficient preconditioner than just Jacobi for a mass-dominated matrix? Or Jacobi could be the final answer.

**Comment by najlkin** [comment]
Even with Jacobi there is a lot to play with, there are multiple parameters of `DSmoother` or you may use different `HypreSmoother` options for Jacobi (or Gauss-Seidel). Feel free to experiment! :wink:

**Comment by Wayne901** [comment]
Thank you @najlkin! I'll compare the performance of different Jacobi settings then.
