### ISSUE TITLE
inconformity of DOF for Nedelec Finite Element Space

### ISSUE THREAD

**Issue by KelvinSkywalker** [mfem/mfem#4303]
when using Nedelec Finite Element Space of first order, I found that the number of DOF is abnormal. 
1. If I union all DOF throughout all element, then the total number of DOF is less than the number counted by MFEM, i.e. function GetNE() would return a bigger number. However as far as I know all DOF of Nedelec Space should belong to some elem.
2. Precisely, if I print the index of the DOF that actually exist in some element, I found that the index would skip likes 25 26 28 29. For example suppose the GetNE( ) tells that the Nedelec Space has 100 DOF, then the index would start from 0  end with 100 but miss some index between.

Here is a simple example using beam-set.mesh

```
#include "mfem.hpp"

#include <fstream>
#include <iostream>

using namespace std;
using namespace mfem;
int main()
{
    const char *mesh_file = "../../mfem/mfem-4.6//data/beam-tet.mesh";
    int order = 1;
    mfem::Mesh mesh(mesh_file, 1, 1);
    int ref_levels =1;
    for (int l = 0; l < ref_levels; l++)
    {
         mesh.UniformRefinement();
    }
    int dim=mesh.Dimension();
    FiniteElementCollection *fec = new ND_FECollection(order, dim);
    FiniteElementSpace *fespace = new FiniteElementSpace(&mesh, fec);
    cout<<"the number of Dof is "<<fespace->GetNDofs()<<endl;
    Array<int> ovo;
    for(int i=0;i<fespace->GetNE();I++)
    {
        Array<int> tdof;
            fespace->GetElementDofs(i,tdof);
        for(int j=0;j<tdof.Size();j++)
        {
            ovo.Union(abs(tdof[j]));
        }
    }
    ovo.Sort();
    cout<<"total dof is "<<ovo.Size()<<endl;
}
```

**Comment by najlkin** [comment]
The line `ovo.Union(abs(tdof[j]));` is wrong, the sign convention of vdofs is that `dof=-1-vdof` :wink:

**Comment by najlkin** [comment]
You may use `FiniteElementSpace::AdjustVDofs()` to do the "absolute" value for you 👍 .

**Comment by KelvinSkywalker** [comment]
OK, thanks a lot !!! It seems to be right now ^ ^

**Comment by najlkin** [comment]
Good to hear :wink:
