### ISSUE TITLE
Custom IntegrationRule for VectorFEMassIntegrator

### ISSUE THREAD

**Issue by Wayne901** [mfem/mfem#4306]
Hello. I plan to test GaussLobatto integration on `ex3`. Most bilinear integrators support an `IntegrationRule` as input, such as `MassIntegrator` and `CurlCurlIntegrator`, but not for `VectorFEMassIntegrator`. Is there a reason for this? If not, I'll create a new integrator then.

**Comment by vladotomov** [comment]
@Wayne901 you can still use `SetIntRule` coming from `NonlinearFormIntegrator::SetIntRule`.

**Comment by Wayne901** [comment]
That's great! Thank you my friend.
