### ISSUE TITLE
Add device tests of Example 14 (DG diffusion)

### ISSUE THREAD

**Issue by v-dobrev** [mfem/mfem#4308]
Since #3904 enabled device support in Example 14, we can now add it as one of the device-enabled tests in the build system, so it can be tested when building with CUDA/HIP and running `make test` or `ctest`.

**Comment by v-dobrev** [comment]
> Good idea. Did I make the correct changes/additions in #4311?

Thanks @pazner! I left a suggestion in the PR discussion.

**Comment by tzanio** [comment]
Discussion continued in #4311
