### ISSUE TITLE
Possible memory leakage of HypreParMatrix

### ISSUE THREAD

**Issue by chunyu79** [mfem/mfem#4312]
I used HypreParMatrix  with an iteration loop like,
`while(*)
{
...
 HypreParMatrix* _KDD  = KDD->ParallelAssemble();
 blocks(1,1)=_KDD;
HypreParMatrix* bigK = HypreParMatrixFromBlocks(blocks);
...
delete _KDD,bigK;
}
`
And the memory usage increased with the iteration.
However, if the matrix is deleted seperately as,
`
delete bigK;
delete _KDD;
`
The memory usage is roughly constant.
The problem is reported here in case someone encounters a similar problem.

**Comment by pazner** [comment]
Hi @chunyu79,

In C++, each delete needs to be its own statement. In your example of `delete x, y;` you are actually using the "[comma operator](https://en.m.wikipedia.org/wiki/Comma_operator)", see the [explanation here](https://stackoverflow.com/questions/3037655/c-delete-syntax).

**Comment by chunyu79** [comment]
Thank you, @pazner . I made a naive mistake.
