### ISSUE TITLE
Evaluating integrals of shape functions in neighboring elements

### ISSUE THREAD

**Issue by FH-9** [mfem/mfem#4315]
Hi,

This is the way I am currently evaluating the integrals of shape functions in neighboring elements (not in the element they belong to):

```c++

for (int k = 0; k < ir->GetNPoints(); k++)
{
    const IntegrationPoint& ip = ir->IntPoint(k);
    Tr_target->Transform(ip, phys_ip);
    Tr_nbr->TransformBack(phys_ip, extrap_ip);
    fe->CalcShape(extrap_ip, shape);
    weight = ip.weight * Tr_nbr->Weight();
    shape *= weight;
    integrand += shape;
}
``` 

To test my results I also compute the integral of Lagrange polynomials directly in the physical space using python and the results are very different.

Is something wrong with my current process? Shouldn't `extrap_ip.x` (in 1D) be either larger than 1 or smaller than 0? Currently that doesn't hold.

Thanks.

**Comment by mlstowell** [comment]
Hi, @FH-9,

In your call to `TransformBack` don't you want to use `phys_ip` rather than `ip`?

Best wishes,
Mark

**Comment by FH-9** [comment]
Yes, indeed.
Apologies, that was a typo.

**Comment by najlkin** [comment]
Hi, @FH-9 , is not it a slight misunderstanding, because you probably want evaluate the basis functions, not shape functions. Basis functions are defined across different elements, but shape functions have support only in a single element. Therefore, shape functions should strictly speaking return zero when evaluated outside the element, but there are no checks for that (not an expected use case), so it will return something, but might not be what you expect...

**Comment by FH-9** [comment]
> Hi, @FH-9 , is not it a slight misunderstanding, because you probably want evaluate the basis functions, not shape functions. Basis functions are defined across different elements, but shape functions have support only in a single element. Therefore, shape functions should strictly speaking return zero when evaluated outside the element, but there are no checks for that (not an expected use case), so it will return something, but might not be what you expect...

I did not know about the distinction between the two. Thanks for pointing that out.
Then yes, I would like the integrals of basis functions on neighboring elements.
Is the method I am currently using wrong then? How could I modify it?

Thank you very much.

**Comment by najlkin** [comment]
For continuous elements, the continuation of the basis function to the neighboring element is the shape function of that respective element for the given shared degree of freedom. So you should not do any extrapolation at all. If what you want is the total integral contribution from the degrees of freedom of an element (and if performance is not important), then you should go over the DOFs of the neighbor and check if their indices coincide with the DOFs of the given element, i.e., if they are shared. If they do, integrate them too using an integration rule on the neighbor.

**Comment by FH-9** [comment]
> For continuous elements, the continuation of the basis function to the neighboring element is the shape function of that respective element for the given shared degree of freedom. So you should not do any extrapolation at all. If what you want is the total integral contribution from the degrees of freedom of an element (and if performance is not important), then you should go over the DOFs of the neighbor and check if their indices coincide with the DOFs of the given element, i.e., if they are shared. If they do, integrate them too using an integration rule on the neighbor.

Thanks for the explanation.
However, I am dealing with discontinuous elements. I am guessing that changes things. Does what I am doing now hold in that case? If not, I would appreciate any pointers on how I could change the code in order to be able to handle discontinuous elements.

**Comment by najlkin** [comment]
In DGs, shape and basis functions coincide, having their support only over a single element, i.e., there are no integral contributions from the neighbors.

**Comment by FH-9** [comment]
> In DGs, shape and basis functions coincide, having their support only over a single element, i.e., there are no integral contributions from the neighbors.

I understand that. However, I need to compute integrals of extrapolated basis functions over neighboring elements. This is commonly done in the context of DG limiters in order to either detect the sharp gradients or limit the solution. I would think that this should be possible with MFEM capabilities. I think I'm in the right direction but I feel like something is missing. That is why I needed some pointers.
Thank you.

**Comment by najlkin** [comment]
You need to define how exactly extrapolated, because it is not matching the definition of your DGs and you probably do not want to evaluate the diverging polynomials of the shape functions really. I think what you want to do formally is definition of a continuous space, which is discretely matching the discontinuous space. That is non-trivial and potentially ambiguous and you cannot expect MFEM to have a simple function for that (even when it is maybe common in DG parlance). However, if you use DGs with a closed basis, having DOFs at the edges, which you want to "share", you may iterate over the edges and instead of checking the indices, you may check if the DOFs have the same position (see `FiniteElement::GetNodes()`).

**Comment by najlkin** [comment]
However, it is an interesting suggestion for a new feature. I would see more logical and straightforward to define a continuous space and then through some method break it down to a "broken" (DG) space, while keeping some DOF map between the two. If you want, you may contribute by it, we (and other users potentially) would be definitely grateful for such feature :wink:

**Comment by najlkin** [comment]
We never do that, all integrations are done in the reference space. Note that `int f(x) dx = int f(x') |J| dx'` , where `x` is in the physical space and `x'` in the reference space 😉 .
