### ISSUE TITLE
【VectorDomainLFIntegrator does not provided enough constructors】

### ISSUE THREAD

**Issue by cglwdm** [mfem/mfem#4317]
The `VectorDomainLFIntegrator` class does not have the following constructor:
`VectorDomainLFIntegrator::VectorDomainLFIntegrator(VectorCoefficient &QF, int oa, int ob)`

But the `DomainLFIntegrator` class does.

Maybe it is good to add this to give the choice to enhance the accuracy of the integrations.

**Comment by najlkin** [comment]
You are right, the order of the integration rule is fixed. Would you add it and make a PR for it? It is a small change and you may try the contribution process on it by yourself 😉 .

**Comment by cglwdm** [comment]
> You are right, the order of the integration rule is fixed. Would you add it and make a PR for it? It is a small change and you may try the contribution process on it by yourself 😉 .

I have pull request!

**Comment by najlkin** [comment]
Great! 😉  I am closing this one in favor of #4320 .
