### ISSUE TITLE
Changes to `socketbuf` result in `SocketStream` objects returning true even if not connected (e.g., to GLVis) 

### ISSUE THREAD

**Issue by cjvogl** [mfem/mfem#4321]
I believe changes introduced between v4.6 and v4.7 are causing the bug where a `SocketStream` object will cast to `true` even if not connected.  This bug can be reproduced in the examples where the following block of code typically exists:
```c++
      char vishost[] = "localhost";
      int  visport   = 19916;
      sout.open(vishost, visport);
      if (!sout)
      {
         cout << "Unable to connect to GLVis server at "
              << vishost << ':' << visport << endl;
         visualization = false;
         cout << "GLVis visualization disabled.\n";
      }
```
see, e.g., such a block starting at [this line](https://github.com/mfem/mfem/blob/acf510594e21c3e2b7b3ba46c67b1d3407ea4837/examples/ex16.cpp#L225).

On a linux machine, the terminal output is
```bash
$ ./ex16
Options used:
   --mesh ../data/star.mesh
   --refine 2
   --order 2
   --ode-solver 3
   --t-final 0.5
   --time-step 0.01
   --alpha 0.01
   --kappa 0.5
   --visualization
   --no-visit-datafiles
   --visualization-steps 5
Number of temperature unknowns: 1361
GLVis visualization paused. Press space (in the GLVis window) to resume it.
step 5, t = 0.05
```
(note, GLVis is not running).  While that is rather innocuous, the bug generates more output on WSL:
```bash
$ ./ex16
Options used:
   --mesh ../data/star.mesh
   --refine 2
   --order 2
   --ode-solver 3
   --t-final 0.5
   --time-step 0.01
   --alpha 0.01
   --kappa 0.5
   --visualization
   --no-visit-datafiles
   --visualization-steps 5
Number of temperature unknowns: 1361
Error in send(): Bad file descriptor
Error in send(): Bad file descriptor
Error in send(): Bad file descriptor
Error in send(): Bad file descriptor
GLVis visualization paused. Press space (in the GLVis window) to resume it.
step 5, t = 0.05
Error in send(): Bad file descriptor
Error in send(): Bad file descriptor
Error in send(): Bad file descriptor
```

Looking at the diff between v4.6 and v4.7, I believe the bug was introduced in https://github.com/mfem/mfem/commit/1e642147ae248ea7e033f96f5a57aeb10e02a177, specifically in how the following block of code (starting at [this line](https://github.com/mfem/mfem/blob/acf510594e21c3e2b7b3ba46c67b1d3407ea4837/general/socketstream.cpp#L141)) continues instead of returning an error code:

```c++
      if (connect(socket_descriptor, rp->ai_addr, rp->ai_addrlen) < 0)
      {
         closesocket(socket_descriptor);
         socket_descriptor = -2;
         continue;
      }
```

**Comment by v-dobrev** [comment]
@cjvogl, thanks for investigating this issue.

I think the `continue` when `connect` fails makes sense now -- `getaddrinfo` returns multiple records we can try to use, while before we had only one option to try from `gethostbyname`.

The problem seems to be that after we check all the records returned by `getaddrinfo` and if they all fail, we still return 0. Instead, I think we should use
```c++
   return (socket_descriptor < 0) ? -1 : 0;
```
Also, we can change the `return -1` to `continue` in the case when `setsockopt` fails inside the `#if defined __APPLE__` section.

**Comment by cjvogl** [comment]
> I think the continue when connect fails makes sense now -- getaddrinfo returns multiple records we can try to use, while before we had only one option to try from gethostbyname.
>
> The problem seems to be that after we check all the records returned by getaddrinfo and if they all fail, we still return 0. 

That makes sense to me!

**Comment by v-dobrev** [comment]
@cjvogl, do you want to try the suggestion and open a PR, or should I do it?

**Comment by cjvogl** [comment]
@v-dobrev, I'll try out the suggestion (thanks for the suggestion!)

**Comment by tzanio** [comment]
Discussion continued in #4322
