### ISSUE TITLE
Strange failure in LOBPCG::Solve()

### ISSUE THREAD

**Issue by mkovaxx** [mfem/mfem#4325]
## Summary

I'm experiencing a rather strange and elusive failure coming from `LOBPCG::Solve()`.

In particular, the failure seems to be related to global state.

## Error Output

```
Verification failed: (!err_flag) is false:
 --> Error during setup! Error code: 256
 ... in function: virtual void mfem::HypreSolver::Setup(const mfem::HypreParVector&, mfem::HypreParVector&) const
 ... in file: linalg/hypre.cpp:4034

--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
```

## Details

In the example code below, there are two functions:
- `compute_displacement()` uses `HyprePCG` (with `HypreBoomerAMG`)
- `compute_eigenmodes()` uses `HypreLOBPCG` (also with `HypreBoomerAMG`)

The failure occurs when both of those functions are called, _and_ in the order above.

When only one of them is called, or when they are called in the opposite order, the failure does not occur.

## Code to Reproduce

Branch to reproduce on v4.7:
https://github.com/mkovaxx/mfem/compare/v4.7...mkovaxx:mfem:repro_lobpcg_failure_v4.7?diff=unified

Branch to reproduce on v4.6:
https://github.com/mkovaxx/mfem/compare/v4.6...mkovaxx:mfem:repro_lobpcg_failure_v4.6?diff=unified

## Full Output

```
lambda: 5.76923e+06
mu: 3.84615e+06
lambda: 5.76923e+06
mu: 3.84615e+06

Solving generalized eigenvalue problem with preconditioning

block size 4

No constraints


Initial eigenvalues lambda   3.79302383078058e+13
Initial eigenvalues lambda   3.89623303887343e+13
Initial eigenvalues lambda   3.91561107726615e+13
Initial eigenvalues lambda   3.97535155522287e+13
Initial residuals 3.406481e+10
Initial residuals 3.440591e+10
Initial residuals 3.485123e+10
Initial residuals 3.551760e+10


Verification failed: (!err_flag) is false:
 --> Error during setup! Error code: 256
 ... in function: virtual void mfem::HypreSolver::Setup(const mfem::HypreParVector&, mfem::HypreParVector&) const
 ... in file: linalg/hypre.cpp:4034

--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
```

**Comment by mlstowell** [comment]
Oh, I forgot to show the output from HyprePCG. If you set the print level to 2 you'll see something like the following:
```
Iters       ||r||_C     conv.rate  ||r||_C/||b||_C
-----    ------------    ---------  ------------ 
    1    1.271104e+01    0.352495    3.524955e-01
    2    8.832897e+00    0.694900    2.449490e-01
    3    7.863157e+00    0.890213    2.180567e-01
    4    8.976724e+00    1.141618    2.489375e-01
    5    1.362136e+01    1.517408    3.777399e-01
    6    2.003127e+01    1.470578    5.554961e-01
    7    2.660074e+01    1.327960    7.376768e-01
    8    3.975854e+01    1.494641    1.102562e+00
    9    6.636014e+01    1.669079    1.840263e+00
   10    1.159455e+02    1.747216    3.215337e+00
   11    2.300191e+02    1.983855    6.378761e+00
   12    4.887783e+02    2.124947    1.355453e+01
   13    1.047534e+03    2.143167    2.904962e+01
   14    1.937653e+03    1.849729    5.373392e+01
   15    3.640353e+03    1.878743    1.009522e+02
   16    5.574089e+03    1.531195    1.545775e+02
   17    1.089281e+04    1.954186    3.020732e+02
   18    2.003481e+04    1.839270    5.555943e+02
   19    3.519839e+04    1.756861    9.761022e+02
   20    6.173170e+04    1.753822    1.711909e+03
   21    1.249866e+05    2.024675    3.466059e+03
   22    3.542020e+05    2.833919    9.822532e+03
   23    5.163013e+05    1.457647    1.431778e+04
   24    6.401169e+05    1.239813    1.775137e+04
   25    1.049374e+06    1.639347    2.910064e+04
   26    1.989593e+06    1.895982    5.517429e+04
   27    3.340518e+06    1.678996    9.263740e+04
   28    6.956915e+06    2.082586    1.929253e+05
   29    4.618615e+07    6.638883    1.280809e+06
```
I believe PCG is stopping because the errors are growing so rapidly.

Best wishes

**Comment by mkovaxx** [comment]
@mlstowell This is really helpful, thank you for the detailed explanation! :)

Is there a way to detect these errors early through the public `hypre` API that doesn't depend on internals such as `hypre_error_flag`?

Seems like the `Solve()` methods returning the error code would be a backwards-compatible way for users to detect these errors early. The return type is `void` right now, so changing that to `int` wouldn't break existing code.

What do you think?

By the way, I found the mistake in my `compute_displacement()` code that made the solve diverge... 😅 

It had the following erroneous line:
```cpp
a_form.FormLinearSystem(dirichlet_bdr_marker, ...);
```

Changing that to the following resolves the problem:
```cpp
a_form.FormLinearSystem(ess_tdof_list, ...);
```

I think the fact that a lot of semantically different things (such as boolean attribute marker arrays, DoF lists, etc.) all use the same `Array<int>` type is pretty error-prone. Seems like this could be mitigated by introducing "strong" type aliases for these semantically different things, e.g. making them thin `struct`s that wrap an `Array<int>`.

**Comment by mlstowell** [comment]
HI, @mkovaxx,

I'm glad you tracked down the solve issue.

For detecting such errors I would recommend looking at the `IterativeSolverMonitor`, see `ex19p` for one way to use it. I have not used this class myself so I'm not familiar with its requirements and limits. If you don't want the residuals printed to the screen at every time step you could use a monitor to print them under certain circumstances. This could be used to detect divergent or stagnated solves. It doesn't look like the monitor could halt the solve (although I could have missed this) but at least it could send a warning of some sort.

Regarding the return type from `Solve`. I can see where that could be useful but the `Solver` class, which introduces this member function, is an abstract class used for both iterative and direct solvers. It may not be obvious how to distill the various possible error conditions down to a useful return value. This is worth discussing with the team.

I like your idea of using strongly typed arguments to some of these error prone functions. This is certainly a breaking change but it's something we could incorporate in the next major release. I'll try to bring this up with the team as well. If you would be interested in starting a "Discussion" on this matter that would be very helpful.

Best wishes,
Mark

**Comment by mkovaxx** [comment]
@mlstowell Thanks for the thoughtful response! I'll look into `IterativeSolverMonitor` to see if that helps.

And yes, I'll start the discussion on tightening type safety around semantically different uses of `Array<int>`.

Have a productive week! :)
