### ISSUE TITLE
Apply double cross of a function by normal vector for Nedelec space.

### ISSUE THREAD

**Issue by Wayne901** [mfem/mfem#4331]
Hello, I'd like to apply a LinearForm on the boundary, with form as 
`integral{W * n x (n x F) dS}`, where `W` is the Nedelec test function and `F` is a vector function, `n` is the normal vector.
From [Linear Form Integrators](https://mfem.org/lininteg/#:~:text=VectorFEBoundaryTangentLFIntegrator) I know 
how to apply a `integral{W * n x F dS}` boundary LinearForm. However, here I need double  
cross product by the normal vector. How to adapt it?

**Comment by Rickbude** [comment]
You should double-check this, but I believe that 

$$\hat{n}\times\hat{n}\times\vec{F} = -F_t,$$

where $F_t$ are the vector component(s) tangential to the wall. After taking the dot product with the vector test function, only the tangential component $W_t$ survives, so:

$$\int_{\partial\Omega}\vec{W}\cdot(\hat{n}\times\hat{n}\times\vec{F})dS = -\int_{\partial\Omega}W_t F_t dS$$

Assuming that MFEM implicitly only integrates the tangential components on the wall (this I am not sure of, see my own question #4281), you might be able to use a `VectorFEDomainLFIntegrator` with coefficient $-\vec{F}$.

**Comment by v-dobrev** [comment]
I think @Rickbude is correct -- $n \times (n \times F)$ is just minus the tangential component of $F$. Also, as he suspected, `VectorFEDomainLFIntegrator` can be used as a boundary integrator in a linear form that is defined on H-curl space and it will compute the dot product of the coefficient with the tangential component of the test function and that is the same as computing the dot product of the tangential components of both, the coefficient and the test function.

@mlstowell, we should probably add this way of using `VectorFEDomainLFIntegrator` as a boundary integrator to the list of the boundary integrators on the MFEM website -- what do you think?

**Comment by Wayne901** [comment]
Thank for your replies @Rickbude  and @v-dobrev and sorry for the late reply.

I get your idea, but in some cases `F` is not just the tangential function.
For example, I try to apply an incident EM plane wave, and it's treat as a source on the outer boundaries.
Say the incident wave is polarized in x-direction as `F = (1, 0, 0) V/m`, and the outer boundary is a sphere. I don't know `F`'s  tangential component then. It's different to the `VectorFEDomainIntegrator` on the boundary where `(W, nxnxE)` is same as `(W, E)` because the shape functions are tangential to the wall.

**Comment by Wayne901** [comment]
Here's the PDEs of time-harmonic Maxwell's wave equation with Dirichlet BC on \Gamma_1 and radiation BC on \Gamma_2, scattered field = total field - incident field
![image](https://github.com/user-attachments/assets/d3430918-cf58-4668-9eac-a42b0356f860)
Here's the final weak formulation,
![image](https://github.com/user-attachments/assets/ed3c4426-7ffe-4f22-9924-3706896cd3c3)

**Comment by Wayne901** [comment]
I think I get it now.

Does it mean that $<W, F>_\Omega$ is same as $<W_t, F_t>_\Omega$, so $<W, n\times n\times F>$ = $<W, -F_t>$ = $<W, -F>$ then?

**Comment by Rickbude** [comment]
This matches with my understanding of how MFEM works yes.

BTW, the fact that $\hat{n}\times\hat{n}\times\vec{F}=-\vec{F}_t$ may not be immediately obvious, but that can be shown using the [vector triple product](https://en.wikipedia.org/wiki/Triple_product#Vector_triple_product):

$$\vec{a}\times(\vec{b}\times\vec{c})=(\vec{a}\cdot\vec{c})\vec{b} - (\vec{a}\cdot\vec{b})\vec{c}$$

Filling in $\vec{a}=\vec{b}=\hat{n}$ and $\vec{c}=\vec{F}$ gives:

$$\hat{n}\times(\hat{n}\times\vec{F})=(\hat{n}\cdot\vec{F})\hat{n} - (\hat{n}\cdot\hat{n})\vec{F} = F_n\hat{n} - \vec{F} = -\vec{F}_t$$
