### ISSUE TITLE
Suggested added feature: OptionsParser taking input from file

### ISSUE THREAD

**Issue by IdoAkkerman** [mfem/mfem#4341]
In my application I would like to be able to store parameters in a file for a part of the simulation, while still be able to give command line parameters. Therefore I would like to have 2 distinct `OptionsParser` objects, one taking the command line options in the usual way, and a second one that can read the options from a file (name of the file could be  command line input). 
My current solution is, to augment the  `OptionsParser` with the following constructor:

```
 OptionsParser(int argc_, std::string argv_[])
      : argc(argc_)
   {
      error_type = error_idx = 0;
      argv = new char*[argc];
      for (int i = 0; i < argc; i++)
      {
         argv[i] = new char[100];
         strcpy(argv[i], argv_[i].c_str());
      }
   }
```
and use that constructor as follows in the application code.
```
   ifstream input(param_file);
   int argc = 0;
   char **argv = new char*[32];
   argv[0] = new char[32];
   strcpy(argv[0], param_file.c_str());
   while (!input.eof())
   {
      argv[argc+1] = new char[32];
      input >> argv[argc+1];
      argc++;
   }
   OptionsParser args(argc, argv);
```
Is there any merit and/or desire to add this constructor to `OptionsParser`.
Shortcuts such as `OptionsParser(std::string filename)` and `OptionsParser(std::ifstream file)` can also be easily devised.

**Comment by fanronghong** [comment]
I think this feature is very necessary when dealing with linear solvers. Many linear solvers, like hypre, have so many parameters (such as AMG).
