### ISSUE TITLE
Error calling CUDA mfem::forall() with MFEM as a third party library

### ISSUE THREAD

**Issue by owenmylotte** [mfem/mfem#4346]
Hello, I'm new here but have been developing a project based on MFEM for some months now.

My project  calls MFEM as a third party library using CMake as the build system.
I include MFEM as below:
`find_package(MFEM REQUIRED)`

after installing MFEM using CMake:
```
cmake -DMFEM_USE_CUDA=YES -DCMAKE_CUDA_ARCHITECTURES=86 ..
cmake --build . -j 15                      # Build MFEM
cmake --build . --target tests -j 15       # Build unit-tests
cmake --build . --target examples -j 15    # Build examples
cmake --build . --target miniapps -j 15    # Build miniapps
ctest --output-on-failure -T test         # Run the tests
sudo cmake --build . --target install         # Install header files
```

I recently parallelized my code, calling mfem::forall.
The content of the code is irrelevant here but I will include a test problem for the sake of completeness.
```
#include mfem.hpp
#include <mfem/general/forall.hpp>

int main(int argc, char **args) {
    // Print the device configuration.
    mfem::Device device("cuda");
    device.Print();

    int size = 100;

    mfem::Vector testVec;

    testVec.SetSize(size);
    testVec = 0.0;

    auto device_ptr = testVec.ReadWrite();

    testVec.GetMemory().PrintFlags();
    mfem::forall(size, [=] MFEM_HOST_DEVICE(int i) {
        device_ptr[i] += 5.0;
    });

    testVec.GetMemory().PrintFlags();
    auto host_ptr = testVec.HostReadWrite();

    testVec.GetMemory().PrintFlags();
    for (int i = 0; i < size; i++) {
        std::cout << host_ptr[i] << std::endl;
    }

    testVec.Destroy();
}
```

My code **runs without errors and gives correct results in the device debug, CPU, and OpenMP configurations** (given that MFEM has been built with -DMFEM_USE_OPENMP=YES). I have profiled the code and verified that the calls go through OpenMP when under this configuration.

Now, I try to build MFEM with CUDA using the above CMake commands.
**The CUDA tests compile, run, and pass without any problems.
The header files are installed and find-able from my project.**

However when building the project, the following error is thrown (along with several others, all of the same flavor):
```
/usr/local/include/mfem/general/forall.hpp: In function ‘void mfem::CuKernel1D(int, BODY)’:
/usr/local/include/mfem/general/forall.hpp:489:18: error: ‘blockDim’ was not declared in this scope
  489 |    const int k = blockDim.x*blockIdx.x + threadIdx.x;
```
showing that the **internal CUDA variables are undefined**.
when I build and open MFEM as a standalone project in CLion, this variable definition points to
`/snap/clion/277/bin/clang/linux/x64/include/__clang_cuda_builtin_vars.h`

 Here is a more complete summary of the relevant CMake script components:
 
```
cmake_minimum_required(VERSION 3.22)
project(myProject VERSION 0.0.01 LANGUAGES CXX CUDA)

set(CMAKE_C_STANDARD 99 CACHE STRING "C++ standard to use.")
set(CMAKE_CXX_STANDARD 17 CACHE STRING "C++ standard to use.")
set(CMAKE_CXX_STANDARD_REQUIRED ON CACHE BOOL "C++ standard to use.")
set(CMAKE_POSITION_INDEPENDENT_CODE ON CACHE BOOL "C++ standard to use.")

include(FetchContent)
include(GNUInstallDirs)

find_package(MFEM REQUIRED)

 target_include_directories(myProject
        PUBLIC
        ${MFEM_LIBRARIES})

target_link_libraries(myProject
        PUBLIC
        ${MFEM_LIBRARIES})
        
        #....

# install and export
```

I've tried changing my function calls to only use the macros instead of calling the functions directly.
I've tried linking the MFEM library target with the CUDA directories:
```
enable_language(CUDA)
set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} --ptxas-options=-v")
target_link_directories(${MFEM_LIBRARIES} INTERFACE ${CMAKE_CUDA_TOOLKIT_INCLUDE_DIRECTORIES})
```
    
as well as some other variations on setting NVCC as the compiler or including the CUDA toolkit and attempting to link it to both my project and MFEM, but I've run out of ideas and am becoming confused (I do not fully understand CMake).
It also seems that my CMake library configuration should not impact the MFEM build process, as including OpenMP internally to my project was not required to build and run the OpenMP configuration.
    
I find it odd that MFEM doesn't export the forall header. (I even tried editing the header export list to include it just to see what would happen. This didn't change anything.)
This made me question whether forall is intended to be called externally at all, but I have found examples of others doing the same in the Github issues and so assume that this is condoned?

This may or may not be more of a CMake question than an MFEM question, but I would greatly appreciate any light that anyone could shed on the issue.

Thanks a lot,
Owen

**Comment by jandrej** [comment]
MFEM requires all files to be compiled with nvcc. Are you sure that your project files that use `mfem_forall` are compiled with nvcc? What's the output of `make VERBOSE=1` of your project.

**Comment by v-dobrev** [comment]
I think @jandrej is right -- all your source files that use `mfem::forall` need to be marked as CUDA sources when `MFEM_USE_CUDA` is true. This can be done with something like this: https://github.com/mfem/mfem/blob/c3eb769a2a316a68fd9a00448e20ca7cff4c8b7c/config/cmake/modules/MfemCmakeUtilities.cmake#L87-L90

Also, to setup the CUDA compilation commands you probably need to add something like this after `find_package(MFEM REAQUIED)`:
```cmake
if (MFEM_USE_CUDA)
    # optional:
    # set(CMAKE_CUDA_HOST_COMPILER ${CMAKE_CXX_COMPILER})
    enable_language(CUDA)
    # set CMAKE_CUDA_ARCHITECTURES on the command line or here:
    # set(CMAKE_CUDA_ARCHITECTURES 70)
    # The following flag is needed by MFEM's `mfem::forall` and other similar functions:
    set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} --expt-extended-lambda")
endif()
```
Regarding linking with CUDA libraries that are needed by MFEM: you don't need to do anything explicit for that -- the `mfem` target already has that information, so all you need to do is tell CMake to link your library or executable with `mfem`.

**Comment by owenmylotte** [comment]
It would seem that this does it!

I had incorrectly assumed that setting the CUDA compiler and it's flags was adequate, but doing something like below gets the job done and the code now compiles with NVCC.

Thanks a lot for the help,
Owen

```
# Macro to set source files language to CUDA
macro(files_to_cuda EXE_SRCS)
    foreach(SRC_FILE IN LISTS ${EXE_SRCS})
        if (MFEM_USE_CUDA)
            set_source_files_properties(${SRC_FILE} PROPERTIES LANGUAGE CUDA)
        endif()
    endforeach()
endmacro()

# Collect all source files in src directory
file(GLOB_RECURSE SRC_FILES "src/*.cpp" "src/*.hpp" "tests/*.cpp" "tests/*.hpp" "main.cpp")

# Apply the CUDA property to all source files if MFEM_USE_CUDA is enabled
files_to_cuda(SRC_FILES)

# Create the library
add_library(myProject STATIC ${SRC_FILES})
```
