### ISSUE TITLE
MFEM for helmoltz equation

### ISSUE THREAD

**Issue by AIBSCT80** [mfem/mfem#4355]
Hi, 

May I ask if there is any example in MFEM for solving Helmholtz equation using absorbing or pml boundary conditions?

**Comment by psocratis** [comment]
Hi @AIBSCT80 ,

Currently, there is no example of Helmholtz with PML (or any other kind of ABC) with standard FEM. However, the following examples are close to what you need:

1. The examples [ex25](https://github.com/mfem/mfem/blob/master/examples/ex25.cpp)/[ex25p](https://github.com/mfem/mfem/blob/master/examples/ex25p.cpp) solve maxwell equations with a PML using the standard FEM formulation.
2. The [pacoustics](https://github.com/mfem/mfem/blob/master/miniapps/dpg/pacoustics.cpp) miniapp solves the Helmholtz equation with PML using the _Ultraweak DPG_ formulation. Note that this is not the standard FEM formulation. 

I would recommend taking a look at the above and trying to write the example yourself. Please let us know if you need any help. 

Best, 

Socratis

**Comment by AIBSCT80** [comment]
@tzanio @psocratis many thanks for the great hints,  this helps me a lot, in particular, the pacoustics seems closer to what I want to implement.  I will take a closer look to this example and may have questions arising during the implementation. Thanks a lot for your time.

**Comment by AIBSCT80** [comment]
Hi,  I tried to run this example:

 mpirun -np 4 pacoustics -o 3 -m meshes/scatter.mesh -sref 0 -pref 7 -theta 0.75 -rnum 10.1 -sc -prob 3

it seems to run now, I got the following results:

  Ref |    Dofs    |    ω    |  Residual  |  Rate  | PCG it |
------------------------------------------------------------
    0 |       3160 | 20.2 π  |  1.568e-01 |   0.00 |     99 | 
    1 |       4048 | 20.2 π  |  1.598e-01 |   0.15 |    216 | 
    2 |       5506 | 20.2 π  |  1.701e-01 |   0.40 |    271 | 
    3 |       6178 | 20.2 π  |  1.527e-01 |  -1.88 |    309 | 
    4 |       8308 | 20.2 π  |  1.636e-01 |   0.47 |    376 | 
    5 |       8980 | 20.2 π  |  1.485e-01 |  -2.49 |    427 | 
    6 |      10120 | 20.2 π  |  1.209e-01 |  -3.45 |    436 | 
    7 |      10450 | 20.2 π  |  1.129e-01 |  -4.23 |    472 | 

The residual deceases, but the rates got negative?  

May I ask is it possible to visualize the solution?

Thanks in advance..

**Comment by AIBSCT80** [comment]
Ok,  the visualization is solved now by setting paraview=true.  Thanks

**Comment by psocratis** [comment]
@AIBSCT80,

negative rate does mean the residual is decreasing. If you want to see rates under uniform refinements you can run with `-theta 0.0` (`theta` controls the the percentage of elements to be refined in the AMR setting). 

Best,

Socratis

**Comment by AIBSCT80** [comment]
@psocratis , 

thanks.  May I ask  would it be possible to have \omega as a function instead of constant in your implementation?  Would it be possible to adapt Ultraweak DPG and PML formulation to this case in your implementation? 

Many thanks.

**Comment by AIBSCT80** [comment]
Hi @psocratis ,    in the lines between 79 and 81, there is PML formulation for the Helmoltz equation.   Would it be possible to provide a reference to this equation? In the line 119,  there is reference for ultra week DPG,  but seems not for PML.  Thank you very much in advance.

**Comment by psocratis** [comment]
> Hi @psocratis , in the lines between 79 and 81, there is PML formulation for the Helmoltz equation. Would it be possible to provide a reference to this equation? In the line 119, there is reference for ultra week DPG, but seems not for PML. Thank you very much in advance.

Here is a [reference](https://doi.org/10.1007/s00466-018-1640-3) for the PML formulation

**Comment by psocratis** [comment]
> at line 969, in function acoustics_solution, the Gaussian_beam case is not
> specified.

The Gaussian beam is specified [here](https://github.com/mfem/mfem/blob/7ace2dedf157cf568c06a6e43e6dfa0673c02f69/miniapps/dpg/pacoustics.cpp#L1133-L1211)

**Comment by AIBSCT80** [comment]
Hi @tzanio @psocratis many many thanks for all your kind supports and reference. This is really a great help for my.   

But, I am still confused about this:

case gaussian_beam:
case pml_beam_scatter:
      {

      }

Here it looks to me gaussian_beam is not specified, but pml_beam_scatter is specified.   Or,  in this case, the gaussian_beam will call  pml_beam_scatter??  

Thank you all in advance.

**Comment by psocratis** [comment]
> Here it looks to me gaussian_beam is not specified, but pml_beam_scatter is specified. Or, in this case, the gaussian_beam will call pml_beam_scatter??

@AIBSCT80 , since there is no `break` between the `gaussian_beam` case and the `pml_beam_scatter` case, both cases will execute the code right after the `pml_beam_scatter` case.

**Comment by AIBSCT80** [comment]
Thank you very much @psocratis    This is clear to me now.  It is the same for pml_plane_wave_scatter and  plane_wave. Both cases will call plane_wave.  Many thanks for your kind support.

**Comment by AIBSCT80** [comment]
Hi @psocratis  I have another question concerning including boundary conditions, at lines 37, 51, 61,  p=p_0 is specified.  It seems we need to provide certain conditions on the boundary, but in the code, actually, I did not see this part.  May I ask did I miss this boundary part in the code, or do we need to specify this condition explicitly?

**Comment by AIBSCT80** [comment]
Hi @psocratis  I tried to adapt the plane_wave in the code, travel from left to right, that shall fulfill homogeneous Helmoltz equation:

`
case plane_wave:
      {
         /*
         real_t beta = omega/std::sqrt((real_t)X.Size());
         complex<real_t> alpha = beta * zi * X.Sum();
         return exp(alpha);
         */
         real_t beta = omega/std::sqrt((real_t)X.Size());
         complex<real_t> alpha = beta * zi * X[0];
         return exp(alpha);
      }
`

I run this example on the square with 

mpirun -np 4 pacoustics -o 2 -m ../../data/inline-quad.mesh -sref 0 -pref 6 -rnum 12 -sc -prob 0

It looks to me no convergence in L2:

`
  Ref |    Dofs    |    ω    |  L2 Error  |  Rate  |  Residual  |  Rate  | PCG it |
----------------------------------------------------------------------------------
    0 |        337 | 24.0 π  |  1.406e+00 |   0.00 |  1.678e-01 |   0.00 |      7 | 
    1 |       1281 | 24.0 π  |  1.420e+00 |   0.02 |  1.752e-01 |   0.06 |      7 | 
    2 |       4993 | 24.0 π  |  1.396e+00 |  -0.03 |  1.898e-01 |   0.12 |     57 | 
    3 |      19713 | 24.0 π  |  1.394e+00 |  -0.00 |  1.089e-01 |  -0.81 |    326 | 
    4 |      78337 | 24.0 π  |  1.395e+00 |   0.00 |  5.317e-02 |  -1.04 |    317 | 
    5 |     312321 | 24.0 π  |  1.395e+00 |   0.00 |  2.541e-02 |  -1.07 |    320 | 
    6 |    1247233 | 24.0 π  |  1.395e+00 |   0.00 |  1.157e-02 |  -1.14 |    307 | 
`
The solution looks not like a plane wave (attached)
![PlaneWave_Problems_PAcoustic](https://github.com/mfem/mfem/assets/7102466/e53bde0a-4158-4e35-9e92-17cde5317531)

Thank you.

**Comment by AIBSCT80** [comment]
Hi, @psocratis @tzanio  It seems I did not set the plane wave correctly.  It is now the following:

 case plane_wave:
      {
         complex<real_t> alpha = -omega/(2.0*M_PI)* X[0];
         return exp(alpha);
      }

The solution looks much better now, but still there are some strange things in the end (attached).

![PlaneWave_Problems_PAcoustic_Improved](https://github.com/mfem/mfem/assets/7102466/97c7edcc-73dd-4c25-9a6c-8536c04967a9)

For this simple example,  the plane wave shall vanish at the end as well, but it seems not.  May I ask is there any other place I need to adapt in the code example?

Thanks

**Comment by psocratis** [comment]
@AIBSCT80, I think you have the solution wrong. It should be `exp( -omega * zi * X[0]);`

You should also compute and replace the gradient inside the `void acoustics_solution_grad(...)` i.e., 

````cpp
      {
         real_t beta = omega/std::sqrt((real_t)X.Size());
         complex<real_t> alpha = -omega* zi * X[0];
         complex<real_t> p = exp(alpha);
         dp[0] = - omega * zi * p;
      }
````

If you want to solve for a generic RHS (not zero) you can change line 511 to compute the non-zero RHS i.e, change it to 
````cpp
   if (prob == prob_type::gaussian_beam || prob == prob_type::plane_wave)
   {
      a->AddDomainLFIntegrator(new DomainLFIntegrator(f_rhs_r),
                               new DomainLFIntegrator(f_rhs_i),
                               TestSpace::q_space);
   }

````

here is the solution to the homogeneous equation with the BC read from the above solution. 

<img width="995" alt="image" src="https://github.com/mfem/mfem/assets/14336752/92488227-51bd-4247-96c0-45f6771b7770">


````
  Ref |    Dofs    |    ω    |  L2 Error  |  Rate  |  Residual  |  Rate  | PCG it |
----------------------------------------------------------------------------------
    0 |        337 | 24.0 π  |  1.393e+00 |   0.00 |  1.740e-01 |   0.00 |      6 |
    1 |       1281 | 24.0 π  |  1.423e+00 |   0.03 |  2.636e-01 |   0.62 |      7 |
    2 |       4993 | 24.0 π  |  1.346e+00 |  -0.08 |  3.627e-01 |   0.47 |     54 |
    3 |      19713 | 24.0 π  |  8.860e-01 |  -0.61 |  2.206e-01 |  -0.72 |    620 |
    4 |      78337 | 24.0 π  |  5.785e-01 |  -0.62 |  1.074e-01 |  -1.04 |   1348 |
    5 |     312321 | 24.0 π  |  2.684e-01 |  -1.11 |  5.707e-02 |  -0.92 |   1752 |
    6 |    1247233 | 24.0 π  |  7.866e-02 |  -1.77 |  2.831e-02 |  -1.01 |   2144 |
````

**Comment by AIBSCT80** [comment]
Thank you @psocratis this is really nice result you have.   I have changed in 

acoustics_solution(const Vector & X)

case plane_wave:
      {
         complex<real_t> alpha = -omega*zi*X[0];
         return exp(alpha);
      }

In  acoustics_solution_laplacian(const Vector & X)

case plane_wave:
      {
         complex<real_t> alpha = -omega * zi * X[0];
         return exp(alpha);
      }

In acoustics_solution_grad(const Vector & X, vector<complex<real_t>> & dp)

   case plane_wave:
      {
         complex<real_t> alpha = -omega* zi * X[0];
         complex<real_t> p = exp(alpha);
         dp[0] = - omega * zi * p;
      }

With command 

mpirun -np 4 pacoustics -o 2 -m ../../data/inline-quad.mesh -sref 0 -pref 6 -rnum 12 -sc -prob 0

I still get the wrong results:


Ref |    Dofs    |    ω    |  L2 Error  |  Rate  |  Residual  |  Rate  | PCG it |
----------------------------------------------------------------------------------
    0 |        337 | 24.0 π  |  1.409e+00 |   0.00 |  1.608e-01 |   0.00 |      7 | 
    1 |       1281 | 24.0 π  |  1.414e+00 |   0.01 |  1.845e-01 |   0.21 |      7 | 
    2 |       4993 | 24.0 π  |  1.380e+00 |  -0.04 |  2.242e-01 |   0.29 |     54 | 
    3 |      19713 | 24.0 π  |  1.340e+00 |  -0.04 |  1.229e-01 |  -0.88 |    383 | 
    4 |      78337 | 24.0 π  |  1.338e+00 |  -0.00 |  5.606e-02 |  -1.14 |    346 | 
    5 |     312321 | 24.0 π  |  1.338e+00 |   0.00 |  2.614e-02 |  -1.10 |    347 | 
    6 |    1247233 | 24.0 π  |  1.338e+00 |   0.00 |  1.187e-02 |  -1.14 |    339 | 

Also the pressure looks to me very strange (enclosed
![PlaneWave_Problems_PAcoustic_Worse](https://github.com/mfem/mfem/assets/7102466/2fbc41df-1f8b-4122-b5ab-f2f49bd81998)
)

This is very confusing.

Thanks

**Comment by AIBSCT80** [comment]
@psocratis ,  It seems if I switch off PML by setting bool with_pml = false,  it will produce the same results as yours (attached):

![Pressure_NoPML](https://github.com/mfem/mfem/assets/7102466/c4b90a70-bc46-42fd-bf44-35975117644b)

The convergence results are the following: 

  Ref |    Dofs    |    ω    |  L2 Error  |  Rate  |  Residual  |  Rate  | PCG it |
----------------------------------------------------------------------------------
    0 |        337 | 24.0 π  |  1.393e+00 |   0.00 |  1.740e-01 |   0.00 |      6 | 
    1 |       1281 | 24.0 π  |  1.423e+00 |   0.03 |  2.636e-01 |   0.62 |      7 | 
    2 |       4993 | 24.0 π  |  1.346e+00 |  -0.08 |  3.627e-01 |   0.47 |     54 | 
    3 |      19713 | 24.0 π  |  8.860e-01 |  -0.61 |  2.206e-01 |  -0.72 |    620 | 
    4 |      78337 | 24.0 π  |  5.785e-01 |  -0.62 |  1.074e-01 |  -1.04 |   1348 | 
    5 |     312321 | 24.0 π  |  2.684e-01 |  -1.11 |  5.707e-02 |  -0.92 |   1752 | 
    6 |    1247233 | 24.0 π  |  7.866e-02 |  -1.77 |  2.831e-02 |  -1.01 |   2144 |

But may I sincerely ask ,  why does it not work when using PML by setting bool with_pml = true.  

How can I test your PML part in your code?  Will PML work for some other examples?

Many thanks.

**Comment by AIBSCT80** [comment]
Hi @psocratis  @tzanio  I tried to test the same example on the 128 cores, I got the following results:

  Ref |    Dofs    |    ω    |  L2 Error  |  Rate  |  Residual  |  Rate  | PCG it |
----------------------------------------------------------------------------------
    0 |       4993 | 24.0 π  |  1.346e+00 |   0.00 |  3.627e-01 |   0.00 |     64 | 
    1 |      19713 | 24.0 π  |  8.860e-01 |  -0.61 |  2.206e-01 |  -0.72 |    698 | 
    2 |      78337 | 24.0 π  |  5.786e-01 |  -0.62 |  1.075e-01 |  -1.04 |   1492 | 
    3 |     312321 | 24.0 π  |  2.688e-01 |  -1.11 |  5.708e-02 |  -0.91 |   1946 | 
    4 |    1247233 | 24.0 π  |  7.985e-02 |  -1.75 |  2.835e-02 |  -1.01 |   1985 | 
    5 |    4984833 | 24.0 π  |  1.961e-02 |  -2.03 |  1.268e-02 |  -1.16 |   2206 | 
    6 |   19931137 | 24.0 π  |  8.216e-03 |  -1.26 |  5.103e-03 |  -1.31 |   1991 | 
    7 |   79708161 | 24.0 π  |  9.768e-03 |   0.25 |  3.492e-03 |  -0.55 |   1839 | 
    8 |  318799873 | 24.0 π  |  8.832e-01 |   6.50 |  5.849e-02 |   4.07 |    592 |

I got similar results as yours up to level 4 (level 6 in yours), but afterwards, it begins to diverge from level 6 to level 8 ??  

Thanks in advance.

**Comment by psocratis** [comment]
@AIBSCT80,

The short answer is that the solution should not depend on the number of cores. However, the preconditioner can indeed be affected by the number of cores and that's why you see a slight increase on the number of iterations in the first few refinements. The "bad" behavior you see in the last two refinements might be caused by an increased condition number (which is often expected). I'll need to investigate this further to have a definite answer.

**Comment by AIBSCT80** [comment]
@psocratis 

Thank very much for the explanations.  It seems to me not a easy problem to get robust preconditioners and solvers for the formulation. I am also very interested in learning more about the solvers.   

There is another issue with your code which I am not so sure about.   Do you think the examples is capable of handling problems with jumping omega in your formula.   I feel like we can replace constantcoefficient by functioncoefficent as in the standard MFEM examples.  In your examples, however this will influence the PML formula.  I am very much appreciated with your comments on this.   Recently, I am studying your implementation, and trying to extend it to such a situation.  Thanks a lot.

**Comment by psocratis** [comment]
@AIBSCT80 , 

Yes, you can try extending this to a variable omega using a `FunctionCoefficient`. The PML stretching happens only in the absorbing boundary and yes you might have to adjust it but I think it's straight forward. I suggest you try to implement it and if you run into issues let us know.

**Comment by AIBSCT80** [comment]
@psocratis  
thanks a lot. This is really good news.  I will be back to you for helps.

**Comment by AIBSCT80** [comment]
@psocratis 

Hi, I tried to replace 

ConstantCoefficient omeg(omega);
ConstantCoefficient omeg2(omega*omega);
ConstantCoefficient negomeg(-omega);

by

MyCoefficientOmega omeg;
MyCoefficientOmega2 omeg2;
MyCoefficientNegOmega negomeg;

where for each, I have overloaded the virtual function 

Eval(ElementTransformation &T, const IntegrationPoint &ip)

and specified the coefficients according to the their positions. 

Do you think this is enough change in the code in order to adapt 
to the varying coefficients. 

I can compile the code, but run into segmentation fault..  

Thank you in advance.

**Comment by AIBSCT80** [comment]
@psocratis 

I made a test of varying omega for the Helmoltz equation with PML.  As you may see, the boundary has some problems (seems not to vanish).  The right hand side is given by  the real and imaginary parts of exp( -omega * zi * X[0]);

**Comment by AIBSCT80** [comment]
@AIBSCT80 @tzanio 
Hi, It looks these strange boundary values are from plane waves 
assigned somewhere in the code, that act as Dirichlet boundary conditions. 
But I am not sure how to identify them. Thanks

**Comment by psocratis** [comment]
@AIBSCT80, with a generic source and a PML formulation you will need to run the example with `-prob 2` so that the RHS and the BCs are not read/computed from an exact/manufactured solution. You generally don't have an exact solution so there is not point in computing the error. With this setting the boundary conditions are set to zero (at the boundary of the PML which is what you want). In addition you'll need to add 2 functions (for real and imaginary parts of your source). Say 
````cpp
real_t source_function_r(const Vector & x)
{
   ... (here you define the real part of the source)
}
real_t source_function_i(const Vector & x)
{
   ... (here you define the imaginary part of the source)
}
````
Then you'll need to modify lines 517-521 to something like 

````cpp
FunctionCoefficient f_source_r(source_function_r);
FunctionCoefficient f_source_i(source_function_i);

if (prob == prob_type::pml_general)
{
   a->AddDomainLFIntegrator(new DomainLFIntegrator(f_source_r),new DomainLFIntegrator(f_source_i),
                               TestSpace::q_space);
}
````

I hope this helps.

Best,

Socratis

**Comment by AIBSCT80** [comment]
@psocratis 
this is really great help.  May I ask, by source,  do you mean \tilde{f} at line 35 for the original Helmoltz equation, or the source f in eqn (1) in the first order system?   Thanks

**Comment by psocratis** [comment]
It doesn't make a significant difference. it's up to you. One is just a scaled version of the other.

**Comment by AIBSCT80** [comment]
@psocratis 

After including your modifications, the code seems to star to run now, as you see in the picture:

![PML_Helmoltz_GivenSource](https://github.com/mfem/mfem/assets/7102466/c0041c71-d2a9-4489-941d-6a0accb6f198)


Thank you very very much for sharing your nice expertise and patience.  Without this,  it could be very hard for me get the code run through.  Many many thanks!

**Comment by AIBSCT80** [comment]
@psocratis

may I sincerely ask if the code will work for input NURBS meshes, which 
may represent my geometry more accurately, like circle?  Many thanks.

**Comment by psocratis** [comment]
@AIBSCT80 , 
The code can definitely work for NURBS meshes like a circle but I expect that you will need a few adjustments. For example, you will need to define the PML in polar coordinates. The current PML implementation assumes a Cartesian domain. 

Best,

Socratis

**Comment by AIBSCT80** [comment]
@AIBSCT80 

thank you.  This sounds not a straight forward, I will give a try and report afterwards.  Many thanks.

**Comment by AIBSCT80** [comment]
@psocratis 
may I sincerely ask, if it is possible to export solution of acoustic pressure at certain positions, e.g., at x1=[-1 : dx : 1] and x2=0 at the grid points.  In there any possibility to get index out of coordinates of grid points, and then by calling, e.g., p_r[índex], we get the pressure at those grid points?   Thanks in advance.

**Comment by AIBSCT80** [comment]
Hi @psocratis 

I encounter a very strange issue when running the example, with larger omega. 

It seems still to run for 64 cores, but with 80, 100 cores, I got errors::


For 64 cores:
Options used:
   --mesh ../../data/MySquare.mesh
   --order 3
   --number-of-wavelengths 10
   --problem 2
   --delta-order 1
   --theta 0
   --serial-ref 3
   --parallel-ref 6
   --static-condensation
   --visualization
   --paraview

  Ref |    Dofs    |    ω    |  Residual  |  Rate  | PCG it |
------------------------------------------------------------
    0 |       9921 | 20.0 π  |  5.499e-02 |   0.00 |     11 | 
    1 |      39297 | 20.0 π  |  8.221e-02 |   0.58 |     24 | 
    2 |     156417 | 20.0 π  |  1.273e-01 |   0.63 |    460 | 
    3 |     624129 | 20.0 π  |  6.446e-02 |  -0.98 |   1263 | 
    4 |    2493441 | 20.0 π  |  9.733e-03 |  -2.73 |   2014 | 




For 80 cores:
```
Verification failed: ((data[j+j*m] - a).real() > 0.) is false:
 --> CholeskyFactors::Factor: The matrix is not SPD
 ... in function: virtual bool mfem::ComplexCholeskyFactors::Factor(int, mfem::real_t)
 ... in file: linalg/complex_densemat.cpp:838

```

For 100 cores:
```
Verification failed: ((data[j+j*m] - a).real() > 0.) is false:
 --> CholeskyFactors::Factor: The matrix is not SPD
 ... in function: virtual bool mfem::ComplexCholeskyFactors::Factor(int, mfem::real_t)
 ... in file: linalg/complex_densemat.cpp:838

```

I was not able to understand this, why change number of cores will make the programming fail. 

Thank you in advance.

**Comment by psocratis** [comment]
@AIBSCT80 , This is probably caused by a numerical roundoff error. You can try compiling MFEM with Lapack so that the factorization uses Lapack instead of the MFEM in-house one, which might be more robust. 

Best,

Socratis

**Comment by v-dobrev** [comment]
You can enable BLAS+LAPACK usage in MFEM with `-DMFEM_USE_LAPACK=ON` for CMake.

**Comment by AIBSCT80** [comment]
@v-dobrev 

many thanks for your help.  

In the mfem cmakelist.txt file,  I saw some lines as:

```
# BLAS, LAPACK                                                                                                                                                                 
if (MFEM_USE_LAPACK)
  find_package(BLAS REQUIRED)
  find_package(LAPACK REQUIRED)
endif()
```

May I ask where shall I put `DMFEM_USE_LAPACK=ON` ?  Can I just put it before the above lines?

After change in the CMakeList,  shall I re-compile the whole mfem ?

Thanks in advance.

**Comment by v-dobrev** [comment]
What I was suggesting was to add `-DMFEM_USE_LAPACK=ON` on the `cmake` command line:
```console
cmake -DMFEM_USE_LAPACK=ON [other-options-that-you-had-before]
```

**Comment by AIBSCT80** [comment]
@v-dobrev 

thank  you very much for clarification.  I  made it in a wrong way by adding this line to the cmakelist file, which did not change anything.  Many many thanks!

**Comment by AIBSCT80** [comment]
Hi @v-dobrev 

in the mfem direcoty mfem-4.7, I tried 

`cmake -DMFEM_USE_LAPACK=ON`

and got the following errors: 
```
CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.



-- CMake version: 3.20.2
-- Loading USER_CONFIG = /mfem-4.7/config/user.cmake (NOTFOUND)
CMake Error at CMakeLists.txt:65 (message):
  MFEM does not support in-source CMake builds at this time.

-- Configuring incomplete, errors occurred!

```

According to online installation, I need to use the following command 

`make parallel -j MFEM_USE_METIS_5=YES METIS_DIR=@MFEM_DIR@/../metis-5.1.0`

for the parallel version. 

Shall I try to use 

`make parallel -j MFEM_USE_LAPACK=YES MFEM_USE_METIS_5=YES METIS_DIR=@MFEM_DIR@/../metis-5.1.0`

It seems this does not work well too.  Many thanks.

**Comment by v-dobrev** [comment]
I thought you use CMake for building MFEM since you mentioned `CMakeLists.txt`.

If you use the GNU make build system then add `MFEM_USE_LAPACK=YES` to you `make` command. Also, you probably will need to specify the locations and names of the BLAS+LAPACK libraries, e.g. by adding the following options on the `make` command line: `LAPACK_LIB="-L<path-to-lapack-library> -l<lapack-library>"`. For example, if you use the OpenBLAS implementation of LAPACK+BLAS, and it is installed in `/opt/openblas/lib/libopenblas.*` then the command line option will be `LAPACK_LIB="-L/opt/openblas/lib -lopenblas"`.

**Comment by AIBSCT80** [comment]
Hi @v-dobrev @psocratis 

I tried to recompile MFEM by 

`make parallel -j MFEM_USE_LAPACK=YES MFEM_USE_METIS_5=YES METIS_DIR=@MFEM_DIR@/../metis-5.1.0 LAPACK_LIB="-L/usr/lib64 -lopenblas" 
`
It seems to work. But I got some error on the first level, not on the other levels:

```
  Ref |    Dofs    |    ω    |  Residual  |  Rate  | PCG it |
------------------------------------------------------------
    0 |       9921 | 20.0 π  |  5.601e-02 |   0.00 |     17 | 
PCG: The operator is not positive definite. (Ad, d) = -9.8903e-08
PCG: The preconditioner is not positive definite. (Br, r) = -1.49584e-09
PCG: Number of iterations: 17
PCG: No convergence!
    1 |      39297 | 20.0 π  |  8.232e-02 |   0.56 |     17 | 
    2 |     156417 | 20.0 π  |  1.273e-01 |   0.63 |    454 | 
    3 |     624129 | 20.0 π  |  6.452e-02 |  -0.98 |   1262 | 
    4 |    2493441 | 20.0 π  |  8.971e-03 |  -2.85 |   2004 | 
```
This is a bit strange error.   Thanks

**Comment by psocratis** [comment]
@AIBSCT80 , 

This is not a strange error, the matrix can become ill-conditioned for these kinds of problems, and sometimes due to roundoff error, the preconditioner loses the positive definiteness (even though in theory and exact arithmetic it has to be positive definite). There is no single and generic fix for these cases. However, you could use GMRES instead of CG to ensure convergence even though it might be slightly slower. 

Socratis

**Comment by AIBSCT80** [comment]
Hi @psocratis 
thanks a lot for the suggestions. I have moved to GMRES, and got the following numbers:

```
 Ref |    Dofs    |    ω    |  Residual  |  Rate  | PGMRES it |
------------------------------------------------------------
    0 |       9921 | 20.0 π  |  5.604e-02 |   0.00 |     18 | 
    1 |      39297 | 20.0 π  |  8.228e-02 |   0.56 |     80 | 
    2 |     156417 | 20.0 π  |  1.273e-01 |   0.63 |    567 | 
    3 |     624129 | 20.0 π  |  6.452e-02 |  -0.98 |   2891 | 
    4 |    2493441 | 20.0 π  |  9.180e-03 |  -2.82 |   6450 | 
    5 |    9967617 | 20.0 π  |  3.339e-03 |  -1.46 |   7177 | 
```
It runs well now, although a bit high number gmres iterations than the pcg iterations required to achieve similar accuracy....

Thanks

**Comment by AIBSCT80** [comment]
Hi @psocratis 

in this example, you have called `Array2D<real_t> length(dim, 2); length = 0.125 ` in case of with_pml=true. but in general. How to select length of PML layer?  Is 0.125 the percentage of the PML layer compared to the whole length?

Thanks

**Comment by AIBSCT80** [comment]
Hi, @psocratis  

may I sincerely ask if it would be possible to use complex omega in the formulation. It seems to me this does not change the code, but I am not totally sure about this.  Thanks.

**Comment by psocratis** [comment]
@AIBSCT80 ,

Yes, you can use complex omega, as long as you appropriately modify the corresponding real and imaginary parts of the coefficients of the PDE.

Best,

Socratis

**Comment by AIBSCT80** [comment]
thanks @psocratis .  This is really a very powerful example code. If I understand it correctly,  if  my coefficient omega=10+i,

currently, I have a my coefficient function 

` double MyCoefficientOmega :: Eval()`

which returns a real value.  

In the case of complex omega,  shall I return complex value like:

```
complex <real_t> MyCoefficientOmega :: Eval()
{
   return zi = complex<real_t> (10, , 1);
}
```

This will  be really convenient, but I am not sure if this is the way how it works.   Thanks a lot !

**Comment by psocratis** [comment]
@AIBSCT80 , 

No that would not work. You would need to create two coefficients one for the real and one for the imaginary part of omega and then pass them to the appropriate integrators. Similar thing is done with the PML integrators in the given example.

Best,

Socratis

**Comment by AIBSCT80** [comment]
thank you @psocratis for clarification.  In this setting, we need to consider the coupling between real and imaginary parts of the coefficients of the FEM solutions, instead of  two decoupled equations in the case of real omega.  I may misunderstand your approach .  Thanks
