### ISSUE TITLE
MFEM for wave equation 

### ISSUE THREAD

**Issue by yangzongW** [mfem/mfem#4357]
Hi,
May I ask if there is any example in MFEM for solving wave equation using pml boundary conditions?I have referred to case 25 on the official website, in which you have used a line source. But I want to use the fluctuation equation to solve the scattered field, this is where I need to set up my background field E^i, and I want to know if I need to have conditional constraints on the background field I set up? Can you explain what is on the right side of the equation in the PML region in the picture?
![IMG_5848](https://github.com/mfem/mfem/assets/129151203/8b13328a-0eb4-4690-9d9a-4dbb395474ac)

**Comment by psocratis** [comment]
Hi @yangzongW ,

In general, you wouldn't have a source inside the PML region. After all, a PML is an artificial absorbing layer surrounding the computational domain to absorb the outgoing waves.  If you want to drive the problem with E_i (the incident wave) a common practice is to have a hole cut in the middle of the domain (that creates a boundary in the middle of the domain) and use a Dirichlet BC on this boundary with boundary values from E_i. This is also demonstrated in [examples/ex25p.cpp](https://github.com/mfem/mfem/blob/master/examples/ex25p.cpp). For additional reading, I would recommend this [paper](https://arxiv.org/pdf/1804.04496). 

I hope this helps.

Best, 

Socratis
