### ISSUE TITLE
Suggestion : Adding safe versions of `Operator` functions.

### ISSUE THREAD

**Issue by victor-decaria-nnl** [mfem/mfem#4358]
Right now, `Operator::Mult(const Vector &x, Vector &y)` and related operations don't have guard rails to make sure that `x` and `y` are the right size. Some derived classes of `Operator` do their own verification, and some don't. This means that it's up to the users to make sure `x` and `y` have the right size by default unless they have extra knowledge of the derived class they're working with.

I think it would reduce cognitive load, make debugging easier and also reduce code to add safe versions of some these operations. For example, something like:

```c++
void Operator::SafeMult(const Vector &x, Vector &y) const
{
   MFEM_VERIFY(x.Size() == width, "input vector is not the correct size.");
   y.SetSize(height);
   Mult(x,y);
}
```
Then the user could reduce
```c++
x.SetSize(A.Width());
y.SetSize(A.Height());
A.Mult(x,y);
```
to
```c++
A.SafeMult(x,y);
```
I think it could help with other mfem functions too, since so many of them use `Operator`. For example, the function:
```c++
void ParGridFunction::ParallelProject(Vector &tv) const
{
   pfes->GetRestrictionMatrix()->Mult(*this, tv);  // could use SafeMult;
}
```
currently does not check if `tv` is the right size, or do the resizing, which may cause a segfault. For the user to do resizing themselves, they have to figure out how to get the size of the fespace in true dofs and set `tv` to that beforehand, whereas the `SafeMult` version does it automatically. I'm not suggesting this should be done everywhere as I'm sure there is code that relies on the current behavior of `Mult`, and also may not be good for performance reasons with something like `DenseMatrix` which is called a lot in hot loops.

Does this seem like a reasonable idea? If so, I could draft up a PR. I also wasn't sure if calling `SetSize` on `y` would have any implications for syncing memory between host and device, and if `SafeMult` would need to be more complicated to account for this.

**Comment by najlkin** [comment]
It is a good suggestion :wink:, but I am not sure we should implement it. It is a basic user's responsibility to ensure that and motivates him/her to consider basic optimizations related to that like preallocating the vectors or so. Secondly, the interface of `Operator` is larger, so it is not really systematic to add another version of only this method. Another thing is that `Safe` is not that much self-explaining really and can be interpreted in different ways, so it would rather confuse users, I think 🤔 . Maybe with a better name, but still I am not sure how many people would use that really. Internal usage is then questionable again and entails some extra overhead. However, I have experienced many segfaults or aborts coming exactly from this, so it might be a good idea to do something about it 💣 😅 . I would rather suggest to systematically go through the code and identify the places that are unguarded (but mind that sometimes that guards are done at a lower level) and add there `MFEM_ASSERT`, which does not entail any performance hit for the production codes :wink:.
