### ISSUE TITLE
Tagging adjacent elements in parallel

### ISSUE THREAD

**Issue by junkudo** [mfem/mfem#436]
Hey,
I have a parallel non-conforming mesh that I’m adapting.  I’m interested in tagging a particular element for refinement and then tagging all adjacent elements (attached through let’s say the element’s vertices) to also be refined.  I first tried accomplishing this by querying the adjacencies available through the pmesh interface (pmesh->GetVertexToElementTable()) but I realize now this does not contain adjacent elements that exist past the partition boundary.  It seems like the underlying pncmesh maintains ghost information but it’s not clear to me how to exactly accomplish what I want.  I’m pretty sure I’ll need to send some MPI messages with some element number encoding/decoding but I’m not really sure where to start?  What’s the most straight forward to accomplish this?
Thanks!

**Comment by v-dobrev** [comment]
The simplest way may be to construct a `ParDiscreteLinearOperator` that connects a piecewise constant space (order zero L2 space) and linear continuous space (order 1 H1 space). To do that, you can define the following `DiscreteInterpolator` class:
```c++
class AdjacencyInterpolator : public DiscreteInterpolator
{
public:
   virtual void AssembleElementMatrix2(const FiniteElement &dom_fe,
                                       const FiniteElement &ran_fe,
                                       ElementTransformation &Trans,
                                       DenseMatrix &elmat)
   { elmat.SetSize(ran_fe.GetDof(), dom_fe.GetDof()); elmat = 1.0; }
};
```
After that you can define the `ParDiscreteLinearOperator` like this:
```c++
   ParMesh *pmesh;
   // define pmesh ...
   L2_FECollection elem_fec(0, pmesh->Dimension());
   H1_FECollection vert_fec(1, pmesh->Dimension());
   ParFiniteElementSpace elem_fes(pmesh, &elem_fec);
   ParFiniteElementSpace vert_fes(pmesh, &vert_fec);
   ParDiscreteLinearOperator vert_elem_oper(&vert_fes, &elem_fes); // maps vert_fes to elem_fes
   vert_elem_oper.AddDomainInterpolator(new AdjacencyInterpolator);
   vert_elem_oper.Assemble();
   HypreParMatrix *vert_elem = vert_elem_oper.ParallelAssemble();
   // use vert_elem ...
   delete vert_elem;
```
You can then use the `ParDiscreteLinearOperator` like this:
```c++
   Vector elem_marker(elem_fes.GetTrueVSize());
   elem_marker = 0.0;
   // set elem_marker(i) to 1.0 if element i is an element whose neighbors you want to find
   Vector vert_marker(vert_fes.GetTrueVSize());
   vert_elem->MultTranspose(elem_marker, vert_marker);
   vert_elem->Mult(vert_marker, elem_marker);
   // if elem_marker(j) is > 0.0 then j is a neighbor of an element you marked above, or
   // j itself was marked above
```

**Comment by junkudo** [comment]
I think you code snippet is missing a `vert_elem_oper.Finalize()` but besides that it seems to work.  Thanks!

**Comment by junkudo** [comment]
Would the issue noted in #385 affect this solution?

**Comment by v-dobrev** [comment]
No, the issue in #385 does not affect this solution - the problem there is with the interpolation weights. Here, the weights are set explicitly to 1 since we only care about the sparsity pattern of the matrix.
