### ISSUE TITLE
Inline Mesh Generation

### ISSUE THREAD

**Issue by AIBSCT80** [mfem/mfem#4361]
Hi, I have a question, is it possible to generate quad mesh using MFEM INLINE  for the area [-10, 10] x [-10, 10] ? So far, I only see examples always starting from 0 ...  Thanks

**Comment by AIBSCT80** [comment]
It seems there is another option: using the mesh format:


MFEM mesh v1.0
#
# MFEM Geometry Types (see fem/geom.hpp):
#
# POINT       = 0
# SEGMENT     = 1
# TRIANGLE    = 2
# SQUARE      = 3
# TETRAHEDRON = 4
# CUBE        = 5
# PRISM       = 6
#

dimension
2

elements
4
1 3 0 1 4 3
1 3 3 4 7 6
1 3 1 2 5 4
1 3 4 5 8 7

boundary
8
1 1 0 1
1 1 1 2
1 1 2 5
1 1 5 8
1 1 8 7
1 1 7 6
1 1 6 3
1 1 3 0

vertices
9
2
-10 -10
0 -10
10 -10
-10 0
0 0
10 0
-10 10
0 10
10 10

**Comment by pazner** [comment]
The inline mesh format doesn’t support that option, but if you want, you can translate the mesh after loading it so that the origin is at the center of the domain (e.g. via `Mesh::Transform`).

**Comment by AIBSCT80** [comment]
thanks.  @pazner  for your help.   It seems the mesh problem is solved now.   It is a good idea to make a mesh translation...
