### ISSUE TITLE
spherical coordinate systems

### ISSUE THREAD

**Issue by huichiayu** [mfem/mfem#4366]
Hi, MFEM development team:

I'm trying to solve a 1D radial diffusion problem. Does MFEM have solvers in spherical coordinate systems? Thank you!

**Comment by v-dobrev** [comment]
We don't have an example of this, however, it's quite simple to implement based on Example 1: one just needs to add the appropriate weights from the spherical change of variables to the coefficients of the bilinear and linear forms. You can find the weights e.g. here: https://en.wikipedia.org/wiki/Spherical_coordinate_system.

**Comment by najlkin** [comment]
You will need some radial weight, i.e. `r|J|`. You may use `CartesianCoefficient` to extract the single radial coordinate and pass it to the `BilinearFormIntegrator` of choice :wink:.

**Comment by huichiayu** [comment]
Hi, Jan:

Thank you for your response. See the embedded 2nd derivative formula of the radial direction.  I think the r^2 in the parenthesis can be treated as a position-dependent coefficient as you mentioned.  However, I don’t know how to deal with 1/r^2 outside the bracket. Any suggestion Many thanks!


***@***.***

Hui-Chia

From: Jan Nikl ***@***.***>
Date: Thursday, June 27, 2024 at 12:39 AM
To: mfem/mfem ***@***.***>
Cc: Yu, Hui-Chia ***@***.***>, Author ***@***.***>
Subject: Re: [mfem/mfem] spherical coordinate systems (Issue #4366)

You will need some radial weight, i.e. r|J|. You may use CartesianCoefficient to extract the single radial coordinate and pass it to the BilinearFormIntegrator of choice 😉.

**Comment by najlkin** [comment]
There cannot be anything "outside the bracket", you need to rewrite the system. You will probably obtain some extra term from the radial divergence and use an extra integrator for that. For the arbitrary powers of radius you may very easily use `FunctionCoefficient` with a C++ lambda function 👍 .
