### ISSUE TITLE
Face and boundary element attributes are inconsistent with NCMesh

### ISSUE THREAD

**Issue by hughcars** [mfem/mfem#4367]
For a serial ncmesh, the face attribute and boundary element attributes can become inconsistent. If the `faces` member of `NCMesh` is made `public` then this test:
```
TEST_CASE("FaceBoundaryElementConsistency", "[NCMesh]")
{
   auto mesh = Mesh("../../data/ref-cube.mesh");

   mesh.EnsureNCMesh(true);
   mesh.UniformRefinement();
   mesh.UniformRefinement();

   const auto &face_to_be = mesh.GetFaceToBdrElMap();
   for (int ipe = 0; ipe < mesh.ncmesh->faces.Size(); ipe++)
   {
      const auto &f = mesh.ncmesh->faces[ipe];
      if (face_to_be[f.index] >= 0)
      {
         CAPTURE(ipe, f.index, face_to_be[f.index]);
         CHECK(f.attribute == mesh.GetBdrAttribute(face_to_be[f.index]));
      }
   }
}
```
will fail on two faces that are boundaries. This basically indicates that the attributes being stored within the `faces` array are not consistent with those of boundary elements. This is likely to cause errors for any deep adaptation with multiple bc attributes.  The errors are for element 7 and local faces 0 and 1.

One fairly unlikely candidate is an indexing error in https://github.com/mfem/mfem/blob/master/mesh/ncmesh.cpp#L1213-L1243. This could be placing `fa` incorrectly. I'm open to any other suggestions. This is currently partially blocking the NC submesh boundary work, as these attributes are used to back out the face->element relations.

**Comment by jandrej** [comment]
Highlighting this as a bug internally.

**Comment by hughcars** [comment]
An inconsistency can be seen for only one UniformRefinement too, cases where the `face.attribute` is not -1, but there is no boundary attribute associated.  
```
TEST_CASE("FaceBoundaryElementConsistency", "[NCMesh]")
{
   auto mesh = Mesh("../../data/ref-cube.mesh");

   mesh.EnsureNCMesh(true);

   auto test_map = [](const Mesh &mesh)
   {
      const auto &face_to_be = mesh.GetFaceToBdrElMap();
      for (int ipe = 0; ipe < mesh.ncmesh->faces.Size(); ipe++)
      {
         const auto &f = mesh.ncmesh->faces[ipe];
         CAPTURE(mesh.GetNE(), ipe, f.index, face_to_be[f.index], f.attribute);
         if (face_to_be[f.index] >= 0)
         {
            CHECK(f.attribute == mesh.GetBdrAttribute(face_to_be[f.index]));
            if (f.attribute != mesh.GetBdrAttribute(face_to_be[f.index]))
            {
               int el, info;
               mesh.GetBdrElementAdjacentElement(face_to_be[f.index], el, info);
               std::cout << "el " << el << " local_face " << info / 64 << std::endl;
            }
         }
         else
         {
            CHECK(f.attribute == -1);
         }
      }
   };


   mesh.UniformRefinement();
   test_map(mesh);
   mesh.UniformRefinement();
   test_map(mesh);
}
```
shows a related failure for a single refinement level, with some faces having attributes when there's no connected boundary element. I might be misinterpreting the data structure, but this is at least surprising to me.
