### ISSUE TITLE
Compilation issue when compiling for GPU -- missing header

### ISSUE THREAD

**Issue by EdwardPalmer99** [mfem/mfem#4376]
- va_start, va_end are undefined in the exodus_writer file when compiling for GPU (Ampere node, CSD3).
- Missing the _cstdarg_ header in exodus_writer.cpp.
- Credit to @Heinrich-BR for spotting this.

**Comment by tzanio** [comment]
Discussion continued in https://github.com/mfem/mfem/pull/4377
