### ISSUE TITLE
Strange behavior with ProjectCoefficient

### ISSUE THREAD

**Issue by bclyons12** [mfem/mfem#4379]
I'm not sure if this is a GLvis plotting issue or something with my mesh/finite element setup. I'm taking a 2D triangular mesh from Gmsh, initializing H1 finite elements onto it, and then initializing the grid function to a 2D diagonal Gaussian. The meshes are generated from modifying [periodic-square.geo](https://github.com/mfem/mfem/blob/master/data/periodic-square.geo). The Gaussian is narrow in one direction and broad in the other. I get these weird ripples in the solution:
![Screenshot 2024-06-28 at 2 26 11 PM](https://github.com/mfem/mfem/assets/1216060/2ad7712b-66ff-46b0-9868-05264a3a9fea)
The ripples get smaller as I increase the resolution, but seemingly not with increased order of the finite element. This last part really surprises me. Here are four cases at two resolutions and two orders. Does anyone have insight into why the finite-element projection looks like this? The high resolution, high order case seems like it should be more than enough to resolve the Gaussian.

Code can be found below

![Screenshot 2024-06-28 at 3 37 28 PM](https://github.com/mfem/mfem/assets/1216060/a065fc15-844b-4c74-9e96-ea363af4e257)
![Screenshot 2024-06-28 at 3 38 26 PM](https://github.com/mfem/mfem/assets/1216060/6e9c38e3-9446-4493-9193-ef7100a23f53)
![Screenshot 2024-06-28 at 3 38 59 PM](https://github.com/mfem/mfem/assets/1216060/df9b5488-f34b-4989-a9b1-4848348e4466)
![Screenshot 2024-06-28 at 3 39 36 PM](https://github.com/mfem/mfem/assets/1216060/df31feac-c50c-4157-a756-b5c47fa41bbc)

### Code
[Meshes.zip](https://github.com/user-attachments/files/16037414/Meshes.zip)
```
#include "mfem.hpp"
#include <fstream>
#include <iostream>

using namespace std;
using namespace mfem;

real_t u0_function(const Vector &x);

int main(int argc, char *argv[])
{
   Mpi::Init();
   Hypre::Init();
   int num_procs = Mpi::WorldSize();
   int myid = Mpi::WorldRank();

   int order = 1;
   const char *mesh_file = "test_100x100.msh";
   
   OptionsParser args(argc, argv);
   args.AddOption(&mesh_file, "-m", "--mesh",
                  "Mesh file to use.");
   args.AddOption(&order, "-o", "--order",
                  "Order (degree) of the finite elements.");
   args.Parse();
   if (!args.Good())
   {
      args.PrintUsage(cout);
      return 1;
   }

   Mesh *serial_mesh = new Mesh(mesh_file, 1, 1);
   int dim = serial_mesh->Dimension();

   ParMesh mesh = ParMesh(MPI_COMM_WORLD, *serial_mesh);
   delete serial_mesh;   

   H1_FECollection fec(order, mesh.Dimension());
   ParFiniteElementSpace fes(&mesh, &fec);

   HYPRE_BigInt size = fes.GlobalTrueVSize();
   if (myid == 0)
   {
      cout << "Order: " << order << endl;
      cout << "Mesh: " << mesh_file << endl;
      cout << "Number of finite element unknowns: " << size << endl;
   }

   // Define solution vector
   FunctionCoefficient u0(u0_function);
   ParGridFunction u(&fes);
   u.ProjectCoefficient(u0);
   HypreParVector *U = u.GetTrueDofs();
   
   char vishost[] = "localhost";
   int  visport   = 19916;
   socketstream sol_sock(vishost, visport);
   sol_sock << "parallel " << num_procs << " " << myid << "\n";
   sol_sock.precision(16);
   sol_sock << "solution\n" << mesh << u;
   sol_sock << "keys cljbPPPPPPP\n" << "pause\n" << flush;

   return 0;
}


// Initial condition
real_t u0_function(const Vector &x)
{
   int dim = x.Size();
   real_t sigma_par = 0.2;
   real_t sigma_perp = 0.013;
   real_t lpar = 0.0;
   real_t center = 0.5;

   Vector X(dim);
   Vector b(dim);
   b(0) = 0.96;
   b(1) = 0.28;

   for (int i = 0; i < dim; i++)
   {
      X(i) = x(i) - center;
      lpar += b(i) * (x(i) - 0.5);
   }
   
   real_t lperp = pow(b(0) * X(1) - b(1) * X(0), 2);
   lperp = sqrt(lperp);
   
   real_t u0  = exp(-(lpar * lpar) / (2.0 * sigma_par * sigma_par));
   u0 *= exp(-(lperp * lperp) / (2.0 * sigma_perp * sigma_perp));

   return u0;
}
```

**Comment by bclyons12** [comment]
Here's are better visualizations of the two meshes:
![Screenshot 2024-06-28 at 2 45 06 PM](https://github.com/mfem/mfem/assets/1216060/7d81b7b3-e540-4b37-afad-5ed3524f97d7)
![Screenshot 2024-06-28 at 3 30 12 PM](https://github.com/mfem/mfem/assets/1216060/c87fccd5-0586-4454-a474-79f4f92120b0)

**Comment by pazner** [comment]
This looks like an artifact of the visualization, have you tried increasing the GLVis element subdivision level using the <kbd>o</kbd> key?

**Comment by bclyons12** [comment]
@pazner Thanks, that's exactly it. It looked like it was only plotting points at the corners of the elements but I didn't know how to change that.
