### ISSUE TITLE
vertices indices are not unique

### ISSUE THREAD

**Issue by jsfeng-fudan** [mfem/mfem#4380]
"I used Gmsh to generate a 2D mesh and then used the Navier solver in MFEM to solve the 2D Navier-Stokes equations. The program compiled without any issues, but when I ran it, the error 'vertices indices are not unique' occurred. How can I resolve this problem?"

the gmsh script is 
lc = 0.1;
Point(1) = {0, 0, 0, lc};
Point(2) = {1, 0, 0, lc};
Point(3) = {1, 0.5, 0, lc};
Point(4) = {0, 0.5, 0, lc};
Point(5) = {1, 0.1, 0, lc};
Point(6) = {2, 0.1, 0, lc};
Point(7) = {2, 0.4, 0, lc};
Point(8) = {1, 0.4, 0, lc};

// Define lines
Line(1) = {1, 2};
Line(2) = {2, 5};
Line(3) = {5, 6};
Line(4) = {6, 7};
Line(5) = {7, 8};
Line(6) = {8, 3};
Line(7) = {3, 4};
Line(8) = {4, 1};

// Define line loops and surfaces
Line Loop(1) = {1, 2, 3, 4,5,6,7,8};
//Line Loop(2) = {5, 6, 7, 8};

Plane Surface(1) = {1};
//Plane Surface(2) = {2};

// Physical groups for boundaries
Physical Line("Walls", 1) = {1,2,3,5,6,7};    // wall
Physical Line("RightInlet", 2) = {4};     // Bottom boundary
Physical Line("LeftInlet", 3) = {8};      // Outlet segment

// Physical group for surfaces
Physical Surface("Domain", 4) = {1};

// Mesh options
Mesh 2;

the cpp code is

#include "navier_solver.hpp"
#include <fstream>

using namespace mfem;
using namespace navier;

using namespace std;

struct NavierContext
{
    int ser_ref_levels = 2;
    int order = 2;
    double kinvis = 1.0 / 40.0;
    double t_final = 1.0;
    double dt = 0.01;
    bool pa = true;
    bool ni = false;
    bool visualization = true;
    bool checkres = false;
} ctx;

void velocity_inlet(const Vector &x, double t, Vector &u)
{
    u = 0.0;
    u(0) = 4*0.3*x(1)*(0.5 - x(1))/(0.41*0.41);
}

double pressure_outlet(const Vector &x, double t)
{
    return 0.0;
}

int main(int argc, char *argv[])
{
	Mpi::Init(argc, argv);
	Hypre::Init();
	
	
	// Parse command-line options.
   OptionsParser args(argc, argv);
   args.AddOption(&ctx.ser_ref_levels, "-rs", "--refine-serial", "Number of times to refine the mesh uniformly in serial.");
   args.AddOption(&ctx.order, "-o", "--order", "Order (degree) of the finite elements.");
   args.AddOption(&ctx.dt, "-dt", "--time-step", "Time step.");
   args.AddOption(&ctx.t_final, "-tf", "--final-time", "Final time.");
   args.AddOption(&ctx.pa, "-pa", "--enable-pa", "-no-pa", "--disable-pa", "Enable partial assembly.");
   args.AddOption(&ctx.ni, "-ni", "--enable-ni", "-no-ni", "--disable-ni", "Enable numerical integration rules.");
   args.AddOption(&ctx.visualization, "-vis", "--visualization", "-no-vis", "--no-visualization", "Enable or disable GLVis visualization.");
   args.AddOption(&ctx.checkres, "-cr", "--checkresult", "-no-cr", "--no-checkresult", "Enable or disable checking of the result. Returns -1 on failure.");
   args.Parse();
   if (!args.Good())
   {
      if (Mpi::Root())
      {
         args.PrintUsage(mfem::out);
      }
      return 1;
   }
   if (Mpi::Root())
   {
      args.PrintOptions(mfem::out);
   }

   // Read the mesh from the Gmsh file
   
   const char *mesh_file = "velp2d.msh";
   Mesh mesh(mesh_file);
    //Mesh mesh("velp2d.msh");
    int dim = mesh.Dimension();

    for (int i = 0; i < ctx.ser_ref_levels; ++i)
    {
        mesh.UniformRefinement();
    }

    ParMesh pmesh(MPI_COMM_WORLD, mesh);
    mesh.Clear();

    //H1_FECollection fec(ctx.order, dim);
    //ParFiniteElementSpace fespace(&pmesh, &fec, dim, Ordering::byVDIM);
	//ParFiniteElementSpace fespace(&pmesh, &fec, dim, Ordering::byVDIM);

    navier::NavierSolver flowsolver(&pmesh, ctx.order, ctx.kinvis);
    flowsolver.EnablePA(ctx.pa);
    flowsolver.EnableNI(ctx.ni);

    ParGridFunction *u_ic = flowsolver.GetCurrentVelocity();
    VectorFunctionCoefficient u_excoeff(pmesh.Dimension(), velocity_inlet);
    u_ic->ProjectCoefficient(u_excoeff);

    Array<int> vel_bdr(pmesh.bdr_attributes.Max());
    vel_bdr = 0;
    vel_bdr[0] = 1; // Inlet

    Array<int> pres_bdr(pmesh.bdr_attributes.Max());
    pres_bdr = 0;
    pres_bdr[2] = 1; // Outlet

    flowsolver.AddVelDirichletBC(velocity_inlet, vel_bdr);
    flowsolver.AddPresDirichletBC(pressure_outlet, pres_bdr);

    double t = 0.0;
    double dt = ctx.dt;
    double t_final = ctx.t_final;
    bool last_step = false;

    flowsolver.Setup(dt);

    for (int step = 0; !last_step; ++step)
    {
        if (t + dt >= t_final - dt / 2)
        {
            last_step = true;
        }

        flowsolver.Step(t, dt, step);

        // if (ctx.visualization)
        // {
            // char vishost[] = "localhost";
            // int visport = 19916;
            // socketstream sol_sock(vishost, visport);
            // sol_sock.precision(8);
            // sol_sock << "parallel " << MPI::WorldSize() << " " << MPI::WorldRank() << "\n";
            // sol_sock << "solution\n" << pmesh << *u_ic << std::flush;
        // }
    }

    MPI_Finalize();

    return 0;
}

**Comment by jsfeng-fudan** [comment]
@v-dobrev, can you help me solve this problem?

**Comment by jsfeng-fudan** [comment]
I got the reason of the vertice index,  that is caused by the gmsh version. When I used   version 4.1 of gmsh, the error appeared, but I got the suitable mesh file using verison 2.2. But there appeared anther error! MFEM abort: Finite element not suitable for lexicographic ordering
 ... in function: mfem::ElementRestriction::ElementRestriction(const mfem::FiniteElementSpace&, mfem::ElementDofOrdering)
 ... in file: fem/restriction.cpp:52

**Comment by pazner** [comment]
As you noted, this is because MFEM does not currently support gmsh v4 mesh files. (You can still output v2.2 format files with the latest version of gmsh).

The other error is likely because your mesh has triangular elements, but partial assembly only works on quad/hex meshes. Try disabling PA in your example.

**Comment by jsfeng-fudan** [comment]
@pazner  Thank you. Now it works well.

**Comment by jsfeng-fudan** [comment]
//#include "mfem.hpp"
#include <fstream>
#include <iostream>
#include "navier_solver.hpp"

using namespace mfem;
using namespace navier;
using namespace std;

struct NavierContext
{
    int ser_ref_levels = 2;
    int order = 2;
    double kinvis = 1.0 / 1.0;
    double t_final = 1.0;
    double dt = 0.01;
    bool pa = false;
    bool ni = false;
    bool visualization = true;
    bool checkres = false;
} ctx;

void velocity_inlet(const Vector &x, double t, Vector &u)
{
    u = 0.0;
    u(0) = 4*0.3*x(1)*(0.5 - x(1))/(0.41*0.41);
}

double pressure_outlet(const Vector &x, double t)
{
    return 0.0;
}

int main(int argc, char *argv[])
{
	Mpi::Init(argc, argv);
	Hypre::Init();
	
	
	// Parse command-line options.
   OptionsParser args(argc, argv);
   args.AddOption(&ctx.ser_ref_levels, "-rs", "--refine-serial", "Number of times to refine the mesh uniformly in serial.");
   args.AddOption(&ctx.order, "-o", "--order", "Order (degree) of the finite elements.");
   args.AddOption(&ctx.dt, "-dt", "--time-step", "Time step.");
   args.AddOption(&ctx.t_final, "-tf", "--final-time", "Final time.");
   args.AddOption(&ctx.pa, "-pa", "--enable-pa", "-no-pa", "--disable-pa", "Enable partial assembly.");
   args.AddOption(&ctx.ni, "-ni", "--enable-ni", "-no-ni", "--disable-ni", "Enable numerical integration rules.");
   args.AddOption(&ctx.visualization, "-vis", "--visualization", "-no-vis", "--no-visualization", "Enable or disable GLVis visualization.");
   args.AddOption(&ctx.checkres, "-cr", "--checkresult", "-no-cr", "--no-checkresult", "Enable or disable checking of the result. Returns -1 on failure.");
   args.Parse();
   if (!args.Good())
   {
      if (Mpi::Root())
      {
         args.PrintUsage(mfem::out);
      }
      return 1;
   }
   if (Mpi::Root())
   {
      args.PrintOptions(mfem::out);
   }

   // Read the mesh from the Gmsh file
   //std::ifstream mesh_file("cavity.msh");
   const char *mesh_file = "velp2d.msh";
   Mesh mesh(mesh_file);
    //Mesh mesh("velp2d.msh");
    int dim = mesh.Dimension();

    for (int i = 0; i < ctx.ser_ref_levels; ++i)
    {
        mesh.UniformRefinement();
    }

    ParMesh pmesh(MPI_COMM_WORLD, mesh);
    mesh.Clear();
    //pmesh.EnsureNodes();
    //H1_FECollection fec(ctx.order, dim);
    //ParFiniteElementSpace fespace(&pmesh, &fec, dim, Ordering::byVDIM);
    //ParFiniteElementSpace fespace(&pmesh, &fec, dim, Ordering::byVDIM);

    navier::NavierSolver flowsolver(&pmesh, ctx.order, ctx.kinvis);
    flowsolver.EnablePA(ctx.pa);
    flowsolver.EnableNI(ctx.ni);

    ParGridFunction *u_ic = flowsolver.GetCurrentVelocity();
    VectorFunctionCoefficient u_excoeff(pmesh.Dimension(), velocity_inlet);
    u_ic->ProjectCoefficient(u_excoeff);
    if(Mpi::Root())
    {
	    cout << "pmesh.bdr_attributes.Max  " << pmesh.bdr_attributes.Max() <<endl;
	    cout << " 1 ---- wall " << endl;
	    cout << " 2 ---- outlet " << endl;
	    cout << " 3 ---- inlet " << endl;
    }
    Array<int> vel_bdr(pmesh.bdr_attributes.Max());

    vel_bdr = 0;
    vel_bdr[2] = 1; // Inlet
    vel_bdr[0] = 1; // Wall

    Array<int> pres_bdr(pmesh.bdr_attributes.Max());
    pres_bdr = 0;
    pres_bdr[1] = 1; // Outlet

    flowsolver.AddVelDirichletBC(velocity_inlet, vel_bdr);
    flowsolver.AddPresDirichletBC(pressure_outlet, pres_bdr);

   ParGridFunction *u_gf = nullptr;
   ParGridFunction *p_gf = nullptr;


    double t = 0.0;
    double dt = ctx.dt;
    double t_final = ctx.t_final;
    bool last_step = false;
    
    
    flowsolver.Setup(dt);

    for (int step = 0; !last_step; ++step)
    {
        if (t + dt >= t_final - dt / 2)
        {
            last_step = true;
        }

        flowsolver.Step(t, dt, step);
	u_gf = flowsolver.GetCurrentVelocity();
        p_gf = flowsolver.GetCurrentPressure();
        // if (ctx.visualization)
        // {
            // char vishost[] = "localhost";
            // int visport = 19916;
            // socketstream sol_sock(vishost, visport);
            // sol_sock.precision(8);
            // sol_sock << "parallel " << MPI::WorldSize() << " " << MPI::WorldRank() << "\n";
            // sol_sock << "solution\n" << pmesh << *u_ic << std::flush;
        // }
	//cout << "solution\n" <<" vel : "<< *u_gf << " pressure :" <<*p_gf << endl;
	//
	Vector v1;
   	v1 = 0.0;
	Vector &vert_coord =v1;


   	pmesh.GetVertices( vert_coord );
   	cout <<setw(6) << u_gf->Size()<< setw(6) << pmesh.GetNV() << endl;
	cout << "step  : " << step  << endl;
   	for( int i =0 ; i< pmesh.GetNV(); i++)
   	{
        	//cout << "{";
        	for( int j = 0; j <pmesh.Dimension() ; j++)
        	{
            cout << fixed <<setprecision(6) << setw(10)<<vert_coord(j*pmesh.GetNV()+i)<<",";
        	}
		cout << "\n";
        	//cout << fixed << setprecision(6) << setw(10) << u_gf[i]<<"}," << endl;
    	}
		Vector node_vel(dim);
		u_gf->GetVectorValue(i, node_vel);
        for (int d = 0; d < node_vel.Size(); ++d)
        {
            cout << setw(10) << node_vel(d);
            if (d < node_vel.Size() - 1)
            {
                cout << ",";
            }
        }
        cout << "\n"	
			
    }
	;
	
	
    cout << " @@@@@@@@@@@@@  run successfully @@@@@@@@@@@@@@@@@ " << endl;
    //MPI_Finalize();

    return 0;
}
@pazner  I want to output the values of velocity and pressure at time t as well as the corresponding nodes coordination. Now I use the method : u_gf->GetVectorValue(i, node_vel);  but the error appeared when compiling. How can I achieve the goal.

**Comment by pazner** [comment]
The function `GridFunction::GetVectorValue` needs an element index and quadrature point. You are passing a vertex index.

You can look at how the function `GridFunction::GetVectorFieldNodalValues` is implemented to see how to do what you want:

https://github.com/mfem/mfem/blob/f5219a2484733ac9507f7ee0692cc7ca5cf5ecd9/fem/gridfunc.cpp#L1255-L1284

**Comment by jsfeng-fudan** [comment]
@pazner Thank your answer!  can you help me modify mycode as above?.  I don't know the input parameter " int comp" meaning, hence,  I can not obtain the right code.

**Comment by jsfeng-fudan** [comment]
The meaning of parameter "comp" is the component of the vector field.  I modify the code as below:
int main(int argc, char *argv[])
{
    Mpi::Init(argc, argv);
    Hypre::Init();
    
    // Parse command-line options.
    OptionsParser args(argc, argv);
    args.AddOption(&ctx.ser_ref_levels, "-rs", "--refine-serial", "Number of times to refine the mesh uniformly in serial.");
    args.AddOption(&ctx.order, "-o", "--order", "Order (degree) of the finite elements.");
    args.AddOption(&ctx.dt, "-dt", "--time-step", "Time step.");
    args.AddOption(&ctx.t_final, "-tf", "--final-time", "Final time.");
    args.AddOption(&ctx.pa, "-pa", "--enable-pa", "-no-pa", "--disable-pa", "Enable partial assembly.");
    args.AddOption(&ctx.ni, "-ni", "--enable-ni", "-no-ni", "--disable-ni", "Enable numerical integration rules.");
    args.AddOption(&ctx.visualization, "-vis", "--visualization", "-no-vis", "--no-visualization", "Enable or disable GLVis visualization.");
    args.AddOption(&ctx.checkres, "-cr", "--checkresult", "-no-cr", "--no-checkresult", "Enable or disable checking of the result. Returns -1 on failure.");
    args.Parse();
    if (!args.Good())
    {
        if (Mpi::Root())
        {
            args.PrintUsage(mfem::out);
        }
        return 1;
    }
    if (Mpi::Root())
    {
        args.PrintOptions(mfem::out);
    }

    // Read the mesh from the Gmsh file
    const char *mesh_file = "velp2d.msh";
    Mesh mesh(mesh_file);
    int dim = mesh.Dimension();

    for (int i = 0; i < ctx.ser_ref_levels; ++i)
    {
        mesh.UniformRefinement();
    }

    ParMesh pmesh(MPI_COMM_WORLD, mesh);
    mesh.Clear();

    navier::NavierSolver flowsolver(&pmesh, ctx.order, ctx.kinvis);
    flowsolver.EnablePA(ctx.pa);
    flowsolver.EnableNI(ctx.ni);

    ParGridFunction *u_ic = flowsolver.GetCurrentVelocity();
    VectorFunctionCoefficient u_excoeff(pmesh.Dimension(), velocity_inlet);
    u_ic->ProjectCoefficient(u_excoeff);
    if(Mpi::Root())
    {
        cout << "pmesh.bdr_attributes.Max  " << pmesh.bdr_attributes.Max() <<endl;
        cout << " 1 ---- wall " << endl;
        cout << " 2 ---- outlet " << endl;
        cout << " 3 ---- inlet " << endl;
    }
    Array<int> vel_bdr(pmesh.bdr_attributes.Max());

    vel_bdr = 0;
    vel_bdr[2] = 1; // Inlet
    vel_bdr[0] = 1; // Wall

    Array<int> pres_bdr(pmesh.bdr_attributes.Max());
    pres_bdr = 0;
    pres_bdr[1] = 1; // Outlet

    flowsolver.AddVelDirichletBC(velocity_inlet, vel_bdr);
    flowsolver.AddPresDirichletBC(pressure_outlet, pres_bdr);

    ParGridFunction *u_gf = nullptr;
    ParGridFunction *p_gf = nullptr;

    double t = 0.0;
    double dt = ctx.dt;
    double t_final = ctx.t_final;
    bool last_step = false;

    flowsolver.Setup(dt);

    for (int step = 0; !last_step; ++step)
    {
        if (t + dt >= t_final - dt / 2)
        {
            last_step = true;
        }

        flowsolver.Step(t, dt, step);
        u_gf = flowsolver.GetCurrentVelocity();
        p_gf = flowsolver.GetCurrentPressure();

        Vector vert_coord;
        pmesh.GetVertices(vert_coord);

        cout << "step: " << step << endl;
        cout << setw(6) << u_gf->Size() << setw(6) << pmesh.GetNV() << endl;

        for (int i = 0; i < pmesh.GetNV(); ++i)
        {
            cout << fixed << setprecision(6);
            for (int j = 0; j < pmesh.Dimension(); ++j)
            {
                cout << setw(10) << vert_coord(j * pmesh.GetNV() + i) << ",";
            }

            cout << "(";
            for (int comp = 0; comp < dim; ++comp)
            {
                Vector nodal_values;
                u_gf->GetVectorFieldNodalValues(nodal_values, comp); // 获取每个分量
                cout << setw(10) << nodal_values(i);
                if (comp < dim - 1)
                {
                    cout << ",";
                }
            }
            cout << ")\n";
        }
    }

    cout << " @@@@@@@@@@@@@  run successfully @@@@@@@@@@@@@@@@@ " << endl;

    return 0;
}
However the error appeared when run :

number of Element : 212
number of Vertex : 132
number of Element : 3392
number of Vertex : 1797
NAVIER version: 0.1
MFEM version: 40700
MFEM GIT: 
Velocity #DOFs: 13970
Pressure #DOFs: 6985
 before  set pa and ni !
pmesh.bdr_attributes.Max  3
 1 ---- wall 
 2 ---- outlet 
 3 ---- inlet 
Adding Velocity Dirichlet BC to attributes 0 2 
Adding Pressure Dirichlet BC to attributes 1 
Setup
Using Full Assembly
        It   Resid      Reltol
MVIN    30   8.16e-28   1.00e-12
PRES    12   5.31e-06   1.00e-06
HELM   210   3.39e-16   1.00e-08
size of u_gf: 13970		number of vertex :1797

step  : 0


MFEM abort: method is not implemented for this class
 ... in function: virtual void mfem::FiniteElement::CalcVShape(mfem::ElementTransformation&, mfem::DenseMatrix&) const
 ... in file: fem/fe/fe_base.cpp:49

**Comment by jsfeng-fudan** [comment]
@pazner "My goal is to obtain the coordinates of each vertex along with the corresponding velocity vv and pressure values. However, I have been unable to modify my code correctly. When I use the method GetVectorFieldNodalValues, the code fails to compile. Could you help me analyze the reason for the error in the code? Thank you very much."
