### ISSUE TITLE
Linking against Spack MFEM package

### ISSUE THREAD

**Issue by Marshdweller** [mfem/mfem#4381]
Hi everyone,

I'm currently working on a project where I need to use the MFEM installed using Spack. 
Unfortunately, the Spack package for MFEM is based on Make, even though the original MFEM supports CMake, meaning CMake has to link a non-cmake libary.

Here’s what I've tried so far using absolute pathes,

```cmake
add_library(mfem STATIC IMPORTED)
set_target_properties(mfem PROPERTIES
  IMPORTED_LOCATION <path>/spack/opt/spack/linux-ubuntu22.04-skylake_avx512/gcc-13.1.0/mfem-4.7.0-dkflc4d3mnvsuqkogrdbarhivwy7b66r/lib/libmfem.a
  INTERFACE_INCLUDE_DIRECTORIES <path>/spack/opt/spack/linux-ubuntu22.04-skylake_avx512/gcc-13.1.0/mfem-4.7.0-dkflc4d3mnvsuqkogrdbarhivwy7b66r/include
  INTERFACE_COMPILE_DEFINITIONS ""
)
target_link_library(<MY_APP> PRIVATE mfem)
```

Can someone help me figure out how to avoid using the absolute Spack path?

Similar question was discussed 4 years ago 
[https://github.com/mfem/mfem/issues/602](https://github.com/mfem/mfem/issues/602)

at that time @v-dobrev 's suggestion was to switch to Makefile, which is not possible for me.

**Comment by Marshdweller** [comment]
OK, so far I have been able to remove the absolute paths using find_library, which returns symlinks to the internals of Spack. However, I’m not sure if my solution is correct (did I reinvent a FindMFEM.cmake?).

```cmake
find_library(MFEM_LIBRARY NAMES mfem REQUIRED)
find_path(MFEM_INCLUDE_DIR NAMES mfem.hpp REQUIRED)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(mfem "MFEM not found" MFEM_LIBRARY MFEM_INCLUDE_DIR)

if(mfem_FOUND AND NOT TARGET mfem::mfem)
  
  add_library(mfem::mfem STATIC IMPORTED)
  set_target_properties(
    mfem::mfem
    PROPERTIES
      INTERFACE_INCLUDE_DIRECTORIES ${MFEM_INCLUDE_DIR}
      IMPORTED_LOCATION ${MFEM_LIBRARY})
endif()

target_link_libraries(<MY_APP> PRIVATE mfem::mfem)
```

**Comment by jandrej** [comment]
> did I reinvent a FindMFEM.cmake

Yes you did. But it looks like a clean solution to me.

**Comment by Marshdweller** [comment]
> > did I reinvent a FindMFEM.cmake
> 
> Yes you did. But it looks like a clean solution to me.

Good 👍 Closing the issue

**Comment by v-dobrev** [comment]
I'll just add one remark: if linking with `libmfem.a` fails due to missing dependencies, it may be easiest to switch to a shared mfem build in spack (i.e. use spec `mfem+shared`) then `find_library(...)` should find `libmfem.so` which should already have all required dependencies linked in.
