### ISSUE TITLE
【Usage】 How to caculate the right hand side (q\nabla T, v)

### ISSUE THREAD

**Issue by cglwdm** [mfem/mfem#4382]
I have two known` Gridfunction` q and T with different  scalar fespaces,  v is associated with a vector fespace: V_fespace, then how to get the vector  (q\nabla T, v) for each v be the basis of V_fespace, someting like `VectorDomainLFIntegrator` .

**Comment by pazner** [comment]
One way of doing it is to define a "coefficient" $\boldsymbol{f} = q \nabla T$, and then use `VectorDomainLFIntegrator` to compute the linear form $(\boldsymbol{f}, \boldsymbol{v})$.

You can represent $q$ as a coefficient using `GridFunctionCoefficient`, and $\nabla T$ using `GradientGridFunctionCoefficient`. Their product can be represented using `ProductCoefficient`.

**Comment by cglwdm** [comment]
Thank you for your reply! But it says: no matching constructor for initialization of 'ProductCoefficient';&nbsp;&nbsp;no known conversion from 'GradientGridFunctionCoefficient' to 'Coefficient &amp;' for 2nd argument;&nbsp;no known conversion from 'GridFunctionCoefficient' to 'real_t' (aka 'double') for 1st argument




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mfem/mfem"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月2日(星期二) 凌晨1:04
***@***.***&gt;;
抄送:&nbsp;"Gang ***@***.******@***.***&gt;;
主题:&nbsp;Re: [mfem/mfem] 【Usage】 How to caculate the right hand side (q\nabla T, v) (Issue #4382)





 
One way of doing it is to define a "coefficient" $\boldsymbol{f} = q \nabla T$, and then use VectorDomainLFIntegrator to compute the linear form $(\boldsymbol{f}, \boldsymbol{v})$.
 
You can represent $q$ as a coefficient using GridFunctionCoefficient, and $\nabla T$ using GradientGridFunctionCoefficient. Their product can be represented using ProductCoefficient.

**Comment by cglwdm** [comment]
I see, it should use&nbsp;ScalarVectorProductCoefficient.
Thank you!



发自我的iPhone


------------------ Original ------------------
From: Will Pazner ***@***.***&gt;
Date: Tue,Jul 2,2024 1:04 AM
To: mfem/mfem ***@***.***&gt;
Cc: Gang Chen ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [mfem/mfem] 【Usage】 How to caculate the right hand side (q\nabla T, v) (Issue #4382)





 
One way of doing it is to define a "coefficient" $\boldsymbol{f} = q \nabla T$, and then use VectorDomainLFIntegrator to compute the linear form $(\boldsymbol{f}, \boldsymbol{v})$.
 
You can represent $q$ as a coefficient using GridFunctionCoefficient, and $\nabla T$ using GradientGridFunctionCoefficient. Their product can be represented using ProductCoefficient.

**Comment by cglwdm** [comment]
> One way of doing it is to define a "coefficient" f=q∇T, and then use `VectorDomainLFIntegrator` to compute the linear form (f,v).
> 
> You can represent q as a coefficient using `GridFunctionCoefficient`, and ∇T using `GradientGridFunctionCoefficient`. Their product can be represented using `ProductCoefficient`.

My question: is this method exact accuracy?

**Comment by pazner** [comment]
Yes, this coefficient should be exact (at a given point, it should evaluate exactly the term $q \nabla T$). In order to compute the integrals in the linear form exactly, you will need to make sure that the quadrature rule used in the integrator is sufficiently accurate to integrate terms of the form $(q \nabla T) v$ (potentially with the additional contribution of the mesh Jacobians).
