### ISSUE TITLE
How to extract solution at certain positions in mfem

### ISSUE THREAD

**Issue by AIBSCT80** [mfem/mfem#4386]
Hi, 
may I sincerely ask, after computation using .mesh format with square element in mfem, is it possible to 
extract solutions at certain positions, e.g., 

if I want to extract solutions at x1=[-2, 2]  and x2=0.  Are there any functions in MFEM, that can maps 
coordinates of positions to indices of solution savings so that we can save solutions at those positions by 
sol [index]?    Thanks.

**Comment by najlkin** [comment]
Hi, this is a classical problem of inversion of the physical coordinates to the reference. The basic approach is [`InverseElementTransformation`](https://docs.mfem.org/4.7/classmfem_1_1InverseElementTransformation.html), ideally when you know the element index, because the mesh is regular or so. Or you may use [the more sophisticated GSLIB](https://mfem.org/howto/findpts/). 😉

**Comment by AIBSCT80** [comment]
@najlkin 

thank you.  It looks not an easy task.  I am not sure if I understand your method correctly.  

Basically,  I only need to extract solution at certain positions (as vertices in the mesh). 

I was thinking that, there might be an easier way to do so.   We have ParMesh, and ParGridFunction .  If the ParGridFunction is defined on the grid vertices,  then by simply checking the position of mesh vertices, we get the index for each grid vertex, then we can extract the solutions at some vertices using their corresponding index.  But I am not sure if the ParGridFunction is defined on vertices.   

I thought MFEM has provided some routines for this kind of applications, but properly not.  Thanks

**Comment by pazner** [comment]
Hi @AIBSCT80,

Are the coordinates at which you want to evaluate the solution completely arbitrary, or are they e.g. mesh vertices?

If they are arbitrary, `Mesh::FindPoints` or `FindPointsGSLIB` (the latter requires the third-party library [gslib](https://github.com/CEED/GSLIB)) can be used to find which elements the points belong to, and what the reference coordinates are. Then, `GridFunction::GetValue` can be used.

If the points are not arbitrary, but instead correspond to mesh vertices or nodal points, then there could be some simpler/more efficient ways.

**Comment by najlkin** [comment]
Where a grid function is defined depends on the type of the finite element. If you can somehow guarantee that the coordinates match the DOFs/vertices (because of some specific meshing, for example) then the situation is easier and you need to just find the DOFs/vertices. Note you may also use `GridFunction::GetNodalValues()` to interpolate/average the elements at the nodes. However, the problem in its full generality is challenging on arbitrary meshes and requires to 1) find the corresponding element and 2) invert the element transformation. Both steps can be easier and quicker if you have some assumptions on the shape of the mesh. If you do not or you are not concerned about performance, you may take one of the paths suggested above. No worries, they are easy to use and work well with the default options for simple meshes 😉 .

**Comment by AIBSCT80** [comment]
@pazner @najlkin 

many many thanks for your detailed helps. I will give a try now, and back as soon as possible.  Thanks

**Comment by AIBSCT80** [comment]
`DenseMatrix pts(3,3);
         pts(0,0)=-0.25;
         pts(1,0)=-0.5;

         pts(0,1)=0;
         pts(1,1)=-0.5;

         pts(0,2)=0.25;
         pts(1,2)=-0.5;

         Array < int > & elem_ids;
         Array< IntegrationPoint > & 	ips;
         bool 	warn = true;
         InverseElementTransformation * 	inv_trans = NULL;
         pmesh.FindPoints(pts, elem_ids, ips, warn, inv_trans);


         Array<double> p_r_selected_val;         
         p_r.GetValues();`

**Comment by pazner** [comment]
I think your matrix `pts` should be of size $2 \times 3$ (rather than $3 \times 3$) since your space dimension is 2.

For each requested point, call `val = p.GetValue(e, ip)` where `e` is the element ID (returned in `elem_ids`) and `ip` is the integration point (returned in `ips`).

**Comment by AIBSCT80** [comment]
@pazner 

many thanks for your quick corrections. 

I have modified the code accordingly:


``

         DenseMatrix pts(2,3);
         pts(0,0)=-0.25;
         pts(1,0)=-0.5;

         pts(0,1)=0;
         pts(1,1)=-0.5;

         pts(0,2)=0.25;
         pts(1,2)=-0.5;

         Array < int >  elem_ids;
         Array< IntegrationPoint >  	ips;
         bool 	warn = true;
         InverseElementTransformation * 	inv_trans = NULL;
         pmesh.FindPoints(pts, elem_ids, ips, warn, inv_trans);


         Array<double> p_r_selected_val(3);         
         for(int i=0; i<3; ++i)
         {
            p_r_selected_val[i]=p_r.GetValue(elem_ids[i], ips[i]);

            cout<<"p["<<i<<"]: "<<p_r_selected_val[i]<<" "<<endl;
         }
``

It runs, but get into memory issue.  I got correct values:

p[0]: 5.4179 
p[1]: -0.61731

but,  i got a running error: 

mpirun noticed that process rank 2 with PID 0 on node clover exited on signal 11 (Segmentation fault).

It seems that some points are not in the cpu ... 

Is there any routine in MFEM to output the data (a global double vector) into one file from all cpus in order to avoid over-writting? 

Thanks

**Comment by pazner** [comment]
If you are running in parallel, then any given MPI rank might not have all the requested points. The return value of `FindPoints` is the number of points found. To write the output to one file, you will want to gather the values to a single rank (e.g. rank 0), and then have that rank save the data to one file.

**Comment by najlkin** [comment]
Just wanted say that 🙂 , `elem_ids` is equal to -2 if the point is not found on the given cpu. You need to serialize the result after the search or the mesh before it.

**Comment by najlkin** [comment]
Btw, I had to read it from the source, we should document `ParMesh::FindPoints`, @pazner 🤔

**Comment by pazner** [comment]
> Btw, I had to read it from the source, we should document `ParMesh::FindPoints`, @pazner 🤔

It should inherit the documentation from `Mesh::FindPoints` (virtual function).

**Comment by najlkin** [comment]
Sure, but that -2 is specific for the parallel version.

**Comment by najlkin** [comment]
Ahh, that is crazy, I did not think someone would do it like that 🤪 But ok, it is at least somehow documented.

**Comment by AIBSCT80** [comment]
@najlkin @pazner 

Thank you very much for a  lot of useful information. 

I saw one sentence just before the 

 virtual int FindPoints

Line 2427 and line 2428:

        @note This method is not 100 percent reliable, i.e. it is not guaranteed 
        to find a point, even if it lies inside a mesh element. */ 

I am bit worried, but I hope it will work in most cases.  Thanks

**Comment by AIBSCT80** [comment]
> If you are running in parallel, then any given MPI rank might not have all the requested points. The return value of `FindPoints` is the number of points found. To write the output to one file, you will want to gather the values to a single rank (e.g. rank 0), and then have that rank save the data to one file.

Thanks a lot @pazner 

Does this also mean that the value at one vertex will only appear once at one of cpus, not in multiple cpus?  That means, the value at one vertex will only be saved once?

**Comment by najlkin** [comment]
As I said, they work fine on simple meshes, no worries 😉 But in general, it is a non-linear, inverse problem, where convergence is not guaranteed.

**Comment by AIBSCT80** [comment]
> As I said, they work fine on simple meshes, no worries 😉 But in general, it is a non-linear, inverse problem, where convergence is not guaranteed.

Thanks for confirmation!  @najlkin

**Comment by najlkin** [comment]
> Does this also mean that the value at one vertex will only appear once at one of cpus, not in multiple cpus? That means, the value at one vertex will only be saved once?

You must call `GetValue()` only on the respective ranks/cpus, i.e., where the index is not -2. This probably causes the segfault. The function `FindPoints()` guarantees it is only one rank/cpu, so serialization should be easy 😉

**Comment by AIBSCT80** [comment]
> > Does this also mean that the value at one vertex will only appear once at one of cpus, not in multiple cpus? That means, the value at one vertex will only be saved once?
> 
> You must call `GetValue()` only on the respective ranks/cpus, i.e., where the index is not -2. This probably causes the segfault. The function `FindPoints()` guarantees it is only one rank/cpu for a point, so serialization should be easy 😉

Thanks for confirmation @najlkin  This really helps a lot.

**Comment by AIBSCT80** [comment]
@najlkin @pazner 

I did a test with return value of  function FindPoints. The code is as following:

``
         DenseMatrix pts(2,3);
         pts(0,0)=-0.25;
         pts(1,0)=-0.5;

         pts(0,1)=0;
         pts(1,1)=-0.5;

         pts(0,2)=0.25;
         pts(1,2)=-0.5;

         Array < int >  elem_ids;
         Array< IntegrationPoint >  	ips;
         bool 	warn = true;
         InverseElementTransformation * 	inv_trans = NULL;
         int npt=pmesh.FindPoints(pts, elem_ids, ips, warn, inv_trans);


         Array<double> p_r_selected_val(npt);   

         cout<<"myid: "<< myid<<"  npt= " << npt<<endl;

``

It is surprising that i got three points for each cpu:

myid: 2  npt= 3
myid: 3  npt= 3
myid: 0  npt= 3
myid: 1  npt= 3

I would expect that some of the cpus do not have 3 points.  This is bit strange to me. It looks to me each cpu hold all 4 points.    Thanks

**Comment by najlkin** [comment]
It is not surprising, it returns the number of globally found points, check the content of the array 😉 .

**Comment by AIBSCT80** [comment]
> If you are running in parallel, then any given MPI rank might not have all the requested points. The return value of `FindPoints` is the number of points found. To write the output to one file, you will want to gather the values to a single rank (e.g. rank 0), and then have that rank save the data to one file.

Would it be a contraction to this,  if every cpu holds all points globally?

**Comment by AIBSCT80** [comment]
> It is not surprising, it returns the number of globally found points, check the content of the array 😉 .

Hi, I try to check the content of the array:

``
     
         for(int i=0; i<npt; ++i)
         {
            p_r_selected_val[i]=p_r.GetValue(elem_ids[i], ips[i]);

            cout<<"p["<<i<<"]: "<<p_r_selected_val[i]<<" "<<endl;
         }
         

``

  The run gets memory issue,  since I used the global number of points instead of local.  Is there any way to get number of local points?  Many thanks

**Comment by najlkin** [comment]
Not this array, this causes the segfault, check `elem_ids`.

**Comment by AIBSCT80** [comment]
> Not this array, this causes the segfault, check `elem_ids`.

Thank you @najlkin 

I try to rewrite the code bit:

``
 int npt=pmesh.FindPoints(pts, elem_ids, ips, warn, inv_trans);
    
         int locpt=0;
         for(int i=0; i<npt; ++i)
         {
           if(elem_ids[i]!=-2)
            {
               locpt++;
            }
         }
         Array<double> p_r_selected_val(locpt);   

         locpt=0;
         for(int i=0; i<npt; ++i)
         {
      
            if(elem_ids[i]!=-2)
            {
               p_selected_val[locpt]=p.GetValue(elem_ids[i], ips[i]);
               cout<<"cpu: "<<myid<<" p_selected_val["<<locpt<<"]: " <<p_selected_val[locpt]<<" "<<endl;
            }
         }
``
Now, I got correct points:

cpu: 0 p_r_selected_val[0]: 5.4179 
cpu: 0 p_r_selected_val[0]: -0.61731 

cpu: 2 p_r_selected_val[0]: -0.354294 

It seems we need to get local points by ourselves.  I hope I understand your method correctly.  Many thanks.

**Comment by najlkin** [comment]
This is correct, but you have thrown away the indices of the points, so you do not know which one is which. Use index `i`.

**Comment by AIBSCT80** [comment]
> This is correct, but you have thrown away the indices of the points, so you do not know which one is which. Use index `i`.

Thanks.  I increment locpt for different points:

``
        for(int i=0; i<npt; ++i)
         {
       
            if(elem_ids[i]!=-2)
            {
               p_selected_val[locpt]=p.GetValue(elem_ids[i], ips[i]);
               cout<<"cpu: "<<myid<<" p_selected_val["<<locpt<<"]: " <<p_selected_val[locpt]<<" "<<endl;
               ++locpt;
            }
         }
``

Now, the index seems correct:

cpu: 0 p_r_selected_val[0]: 5.4179 
cpu: 0 p_r_selected_val[1]: -0.61731 

cpu: 2 p_r_selected_val[0]: -0.354294 


Now, I need to do  MPI_Gather.  Thanks

**Comment by najlkin** [comment]
Yes, gather the solution, but also the indices, otherwise you do not know how to order the data.

**Comment by AIBSCT80** [comment]
> Yes, gather the solution, but also the indices, otherwise you do not know how to order the data.

Yes, thank you very much for the comments. You are right, we need indices to order the data.

**Comment by AIBSCT80** [comment]
@najlkin @pazner 

MPI_Gather seems gather data with the same length in each cpu.  but in our case, the number of points in each cpu may be different.  May I sincerely ask if there is any routine in MFEM can do this job?  Many thanks

**Comment by najlkin** [comment]
You may do it also differently, just filling let us say infinity at the indices of the array, which are not on the given rank, and then call `MPI_Reduce` with minimum operation to get the result.

**Comment by AIBSCT80** [comment]
@najlkin 

many thanks for your nice suggestions.  It seems my problem is solved with MPI_GatherV, where I send all the values from each cpu into the root (with rank 0).  Then write the data and corresponding index to the file so that we got correct ordering of the data.

**Comment by najlkin** [comment]
Good to hear it works 😉 , that is more efficient indeed. I am closing this one.
