### ISSUE TITLE
Bug using mesh refinement and BC's

### ISSUE THREAD

**Issue by starkekr** [mfem/mfem#4388]
### Discussed in https://github.com/orgs/mfem/discussions/4359

<div type='discussions-op-text'>

<sup>Originally posted by **starkekr** June 14, 2024</sup>
I am having trouble with an error in mfem. The problem happens in 3D jobs when using mesh refinement and setting periodic bc's along in a direction along with Dirichlet in others. 

I was able to reproduce my problem in a simple example that doesn't actually perform any solves or mesh refinement operations. I have attached the file below. The code runs fine when I comment out the line pertaining to mesh refinement (line 122) but doesn't work other wise. When it doesn't work, it produces the following error :

MFEM abort: Not implemented.
 ... in function: void mfem::Mesh::GetEdgeTransformation(int, mfem::IsoparametricTransformation*) const
 ... in file: mesh/mesh.cpp:645

[ex1_my_test.cpp.tar.gz](https://github.com/user-attachments/files/15841623/ex1_my_test.cpp.tar.gz)

Like I said, it also only seems to be a problem for 3D jobs. Any help is greatly appreciated.</div>

**Comment by v-dobrev** [comment]
In the attached `.cpp` file, line 122 is empty -- can you check that posted the right version of the source file?

It will be helpful if you can build mfem and your example in debug mode, run it in a debugger, and then post the stack trace when the error occurs.

**Comment by starkekr** [comment]
sorry I meant line 121 (periodic_serial_mesh.EnsureNCMesh(true);). It seems like there is some logic in gridfunc.cpp:2120 that gets called when running with AMR.

Here is the last couple lines run in gdb before it failed along with a stack trace
![image](https://github.com/mfem/mfem/assets/118568957/46a3a54d-78d3-4e77-bfdd-28e8d4bf93ff)

**Comment by v-dobrev** [comment]
Okay, I see the issue -- basically `Mesh::GetEdgeTransformation` does not support periodic meshes at the moment, however it can be added. The support for this case will be similar to the one in `Mesh::GetFaceTransformation` here: https://github.com/mfem/mfem/blob/9343ffad7b64de9ccf29ad23c740bb02d916c3e1/mesh/mesh.cpp#L556-L580

Some of the calls in this block do not have equivalent for edges, so they will need to be added.

One workaround for this can be to replace `ProjectBdrCoefficient` with `ProjectCoefficient`. If you need to preserve the values of the `GridFunction` in the interior then you will need to create an auxiliary `GridFunction`, do the full projection on that `GridFunction`, and then copy the boundary values you need to the original `GridFunction`. The list of the boundary dofs can be obtained using `FiniteElementSpace::GetEssentialVDofs`.

**Comment by v-dobrev** [comment]
Actually, `FiniteElementSpace::GetEssentialVDofs` does not return a list of dofs but a marker array, i.e. a Boolean array where the boundary dofs are marked with a non-zero value.

**Comment by starkekr** [comment]
Thanks, I will try the workaround for the time being!
