### ISSUE TITLE
MFEM program crashes when solving linear static analysis problem when using AddBdrTriangle

### ISSUE THREAD

**Issue by skbizport** [mfem/mfem#4391]
Hi.

I am running into a crash when running an modified version of ex2.cpp example.

Following steps illustrate the sequence: 

1. Create a BREP solid using OCCT
2. Triangulate the solid
3. Use GMSH to generate tetrahedral mesh. Here i am using gmsh::model::addPhysicalGroup() to register set of 'face shapes' for later boundary attribute setup in MFEM  
4. Extract nodes and elements from gmsh 
5. Initialize MFEM mesh by using AddVertex() and AddTet() methods.
6. Use AddBdrTriangle() method to add border surface triangles identified in step 3
7. Run the analysis

This results in a crash with following assert message

**SparseMatrix::Gauss_Seidel_forw(...) #2
Aborted (core dumped)**

If step 6 is skipped, it runs to completion. Clearly, I am not specifying the boundary attribute correctly. 

Can you pls explain how to do this? It would be great to have an example of populating MFEM mesh directly (without reading from an existing gmsh file) along with boundary attributes.

Appreciate any help.

Thx

**Comment by v-dobrev** [comment]
The error message you encounter means that the SparseMatrix has a 0 entry on the diagonal in some row. I'm not sure how this is related to the boundary elements.

One thing that can be an issue is to make sure you use attributes >= 1 in mfem -- I think Gmsh may generate boundary tags starting with 0 and that can be an issue if all boundaries elements are marked with 0 attribute. Note that, by default, example 2 expects at least 2 boundary attributes: 1 and 2. On attribute 1, fixed Dirichlet b.c. is imposed and on boundary 2, the surface force b.c. is imposed. There is a similar assumption about the domain (volume) element attributes -- the example expects two domain attributes, 1 and 2, that cover the whole domain -- see the diagram in the beginning of the source file.

**Comment by skbizport** [comment]
Appreciate the explanation.  I was not creating 2 domain attributes for 2 materials. After converting the problem to single material domain, it worked. 

Thx
