### ISSUE TITLE
Adding heat source to ex16

### ISSUE THREAD

**Issue by karthichockalingam** [mfem/mfem#4392]
Hi,

@nmnobre and I are interested in solving the following equation

$\frac{d u}{d t}=\nabla \cdot(\kappa+\alpha u) \nabla u + Q(u)$

by adding the heat source term at the end. 
I was trying to mimic what was done with the mass term.

```
  ParBilinearForm *M;
  ParLinearForm *Q;

   HypreParMatrix Mmat;
   Vector Qvec;

   delete M;
   M = new ParBilinearForm(&fespace);
   M->AddDomainIntegrator(new MassIntegrator());
   M->Assemble(0); // 
   M->FormSystemMatrix(ess_tdof_list, Mmat);

  delete Q;
  Q = new ParLinearForm(&fespace);
  Q->AddDomainIntegrator(new DomainLFIntegrator());
  Q->Assemble(0); // 
  Q->FormSystemMatrix(ess_tdof_list, Qvec); ?????
```
but I don't believe there is something like ```FormSystemVector``` to form a system vector.
Please let me know how I can proceed next.

Kind regards,
Karthik

**Comment by jandrej** [comment]
You can call `ParLinearForm::ParallelAssemble` if you want the globally assembled parallel vector of the ParLinearForm if that's what you want?

**Comment by karthichockalingam** [comment]
@jandrej thank you for your response. 

Below is my weak form
(dudt, v) = kappa(u) * (Du, Dv) + (f(u), v)
I would like to assemble the source term, should I use ```Vector``` or  ```HypreParVector```
For now, I will assume ```Vector```; is the following code correct?

```
 ParLinearForm *Q;

 Vector Qvec;

  delete Q;
  Q = new ParLinearForm(&fespace);
  Q->AddDomainIntegrator(new DomainLFIntegrator());
  Q->Assemble(0);  
  Q->ParallelAssemble(Qvec);
  Qvec.SetSubVector(ess_tdof_list, 0.0);
```

Instead of 

```
ParBilinearForm *M;
HypreParMatrix Mmat;

 delete M;
 M = new ParBilinearForm(&fespace);
 M->AddDomainIntegrator(new MassIntegrator());
 M->Assemble(0); 
 M->FormSystemMatrix(ess_tdof_list, Mmat);
```

can I do the following?

```
ParBilinearForm *M;
HypreParMatrix Mmat;

delete M;
M = new ParBilinearForm(&fespace);
M->AddDomainIntegrator(new MassIntegrator());
M->Assemble(0); 
M->ParallelAssemble(Mmat)
Mmat.EliminateRowCols(ess_tdof_list);
```

Kind regards,
Karthi.
