### ISSUE TITLE
Can MFEM handle multiple sources at the right hand side of equation

### ISSUE THREAD

**Issue by AIBSCT80** [mfem/mfem#4393]
Hi, 

may I ask if I can use ` FunctionCoefficient` with own defined function as sources, and source does not only depend on the position `x`, but also another parameter `beta`

E.g., 

`  FunctionCoefficient f_source(source_function);`

My source function is defined as 

`real_t source_function_beta(const Vector &x, const double& beta)`

Now, I am going to run a loop for several choices of `beta` :

`double beta[3]={-1,0,1};`

That is I have to assembly my right hand side 3 times and solve the system 
3 times for different `beta`  : 

```
for(int i=0; i<3; ++i)
{
    FunctionCoefficient f_source (source_function_beta);
    a->AddDomainLFIntegrator(new DomainLFIntegrator(f_source_r), new DomainLFIntegrator(f_source_i), TestSpace::q_space);
   // here solve the system with the new right hand side for each beta
}
```

Here I am confused that how can I provide input beta to function `source_function_beta` at each loop. Is it possible in MFEM to make this kind of sources with user provided parameter?  

Many thanks.

**Comment by AIBSCT80** [comment]
Hi, 

the problem is solved,  I just simply run the code as many times as the number of different right hand sides.  This might not be the most efficient way, but it seems to work for the current being.  Thanks.

**Comment by v-dobrev** [comment]
Two possible solutions come to mind:
1. Make `beta` a global variable instead of an explicit paramter of `source_function_beta`; then `beta` can be read inside `source_function_beta` and modified in `main` inside your loop over the different beta values you need to compute with.
2. Make `beta` a variable in your `main` (or another function) and then create the `FunctionCoefficient` using a lambda function (that captures `beta` by reference) instead of using the C-function `source_function_beta`; this will look something like this:
```c++
   // ...
   real_t beta = 1.0;
   FunctionCoefficient f_source([&](const Vector &x) -> real_t
   {
      // copy the computations in `source_function_beta` here -- `beta` can be used as a normal variable
   });
   // ...
   real_t beta_values[3] = {-1,0,1};
   for (int i = 0; i < 3; i++)
   {
      beta = beta_values;
      // use f_source -- it will use the current value of beta
   }
```

**Comment by AIBSCT80** [comment]
@v-dobrev 

many many thanks for your help. Actually, I used your first method.  Beta is declared as a global variable,  and assigned inside the main function, then, I made a loop over all possible betas. After each loop,  beta will be switched to the next value, which will be the new beta in the source function.    This works very well now.  Thank you in advance.
