### ISSUE TITLE
Change some MFEM_ASSERT to MFEM_VERIFY, or report more info's to the users? 

### ISSUE THREAD

**Issue by adam-sim-dev** [mfem/mfem#4396]
For example, it's correctly handled in PCG for the case when the preconditioner is not SPD.

https://github.com/mfem/mfem/blob/988439f60a9902e29572b83dcb2a142eb8da3dbd/linalg/solvers.cpp#L745-L767

While in MINRES, beta is calculated directly as the square root of Dot(v0,q). If the preconditioner is not SPD, Dot(v0,q) will be a negative number. （I am not an expert, I just ran into this case and it is not reported if I have not defined MFEM_DEBUG=YES even though I am using the Debug mode in Visual Studio.）

https://github.com/mfem/mfem/blob/988439f60a9902e29572b83dcb2a142eb8da3dbd/linalg/solvers.cpp#L1693-L1697

**Comment by v-dobrev** [comment]
I agree, in the iterative solvers, it will be better to not use `MFEM_ASSERT`/`MFEM_VERIFY` but to stop the iteration, record an error condition, print a warning/error message (if the solver is configured to do that), and return from the `Mult` method.

@adam-sim-dev, would you like to propose a PR to address this?

**Comment by tzanio** [comment]
Discussion continued in #4401
