### ISSUE TITLE
Face dofs for Periodic meshes

### ISSUE THREAD

**Issue by LeilaGhaffari** [mfem/mfem#4397]
Hi MFEM team,

I've encountered an issue with periodic meshes while using MFEM and I would appreciate your opinion on it.
I'm currently working on adding support for periodic boundary conditions in [Palace](https://github.com/awslabs/palace). Palace uses MFEM for mesh management and [libCEED](https://github.com/CEED/libCEED) for partial assembly. When dealing with a triply periodic cubic mesh in Palace, everything functions smoothly. However, when working with a partially periodic mesh where certain surfaces need to be constrained, I'm facing difficulties in obtaining the indices of degrees of freedom on these boundaries. These indices are necessary for populating the element restriction vector.

The challenge I'm facing differs from MFEM's example ex27, as I only require the dofs on specific boundaries without the need for boundary integration.

From what I understand, MFEM uses a L2 space for periodic meshes and does not directly provide access to face dofs. Is there a method or approach to retrieve this information?

**Comment by pazner** [comment]
Do you have an example mesh that you can share? MFEM treats periodic meshes by "collapsing" the periodic vertices into a single vertex. You can get the degrees of freedom lying on the periodic boundary by placing "internal boundary elements" at the periodic boundary.

**Comment by LeilaGhaffari** [comment]
I am actually interested in retrieving the dofs on the non-periodic boundaries. [This](https://github.com/LeilaGhaffari/palace-lg/blob/lgh/periodic-bc/examples/cube/mesh/cube_periodic_xy.msh) is the mesh I have been testing my implementation with. The corresponding geo file is in the same folder. It is periodic in the x- and y-directions and non-periodic in the z-direction.

I can get access to the dofs of the adjacent elements but I was wondering if there is a restriction matrix or a similar functionality in MFEM that could return the dofs on the boundaries?!

**Comment by pazner** [comment]
In your example mesh, the non-periodic boundaries have boundary attributes 1 and 5. You can get the associated DOFs by calling `FiniteElementSpace::GetEssentialTrueDofs`, for example:

```cpp
Array<int> bdr_is_ess(6);
bdr_is_ess = 0;
bdr_is_ess[0] = 1;
bdr_is_ess[4] = 1;

Array<int> ess_dofs;
fes.GetEssentialTrueDofs(bdr_is_ess, ess_dofs);
```

(Note: since you mentioned MFEM using L2 spaces for periodic meshes, are you trying to get the DOFs associated specifically with the mesh's nodal space, or are you interested in some other space defined on the same mesh?)

**Comment by LeilaGhaffari** [comment]
Thank you, @pazner , for taking the time to examine the mesh and share the code snippet. I tried it, but unfortunately, it didn't work. 

> (Note: since you mentioned MFEM using L2 spaces for periodic meshes, are you trying to get the DOFs associated specifically with the mesh's nodal space, or are you interested in some other space defined on the same mesh?)

Yes, I am interested in the dofs associated with the mesh's nodal space.

I've also considered extracting the point matrices for both the face and its adjacent element. By comparing these matrices, we may be able to identify matching coordinates on the face. This could help us determine the desired dofs. What are your thoughts on this strategy? Do you think it's feasible?

**Comment by LeilaGhaffari** [comment]
I'm still uncertain if this approach is valid, but I proceeded to code it as follows and ran Palace with the mesh file I provided earlier.

```cpp
// Get coordinates of face dofs
int elem_id, face_info;
fespace.GetMesh()->GetBdrElementAdjacentElement(e, elem_id, face_info);
mfem::Geometry::Type face_geom = fespace.GetMesh()->GetBdrElementGeometry(e);
face_info = fespace.GetMesh()->EncodeFaceInfo(
               fespace.GetMesh()->DecodeFaceInfoLocalIndex(face_info),
               mfem::Geometry::GetInverseOrientation(
                  face_geom, fespace.GetMesh()->DecodeFaceInfoOrientation(face_info))
            );
mfem::IntegrationPointTransformation Loc1;
fespace.GetMesh()->GetLocalFaceTransformation(fespace.GetMesh()->GetBdrElementType(e),
                           fespace.GetMesh()->GetElementType(elem_id),
                           Loc1.Transf, face_info);
const mfem::FiniteElement *face_el = fespace.GetTraceElement(elem_id, face_geom);
MFEM_VERIFY(dynamic_cast<const mfem::NodalFiniteElement*>(face_el),
            "Mesh requires nodal Finite Element.");
mfem::IntegrationRule face_ir(face_el->GetDof());
Loc1.Transf.ElementNo = elem_id;
Loc1.Transf.mesh = fespace.GetMesh();
Loc1.Transf.ElementType = mfem::ElementTransformation::ELEMENT;
Loc1.Transform(face_el->GetNodes(), face_ir);
mfem::IsoparametricTransformation face_tr;
face_tr.ElementNo = e;
face_tr.ElementType = mfem::ElementTransformation::BDR_ELEMENT;
face_tr.mesh = fespace.GetMesh();
face_tr.Attribute = fespace.GetMesh()->GetBdrAttribute(e);
mfem::DenseMatrix &face_pm = face_tr.GetPointMat(); // dim x dof
face_tr.Reset();
fespace.GetMesh()->GetNodes()->GetVectorValues(Loc1.Transf, face_ir, face_pm);
//std::cout << std::fixed << std::setprecision(16);
mfem::real_t *face_pm_data = face_pm.GetData(); // column-major storage
for (int m=0; m<face_pm.Height(); m++) {
  for (int n=0; n<face_pm.Width(); n++) std::cout << "face_pm[" <<m<<","<<n<<"] = " << face_pm_data[m*face_pm.Height()+n] << "\t";
  std::cout << std::endl;
}

// Get coordinates of element dofs
mfem::DenseMatrix elem_pm;
const mfem::FiniteElement *fe_elem = fespace.GetFE(elem_id);
const mfem::IntegrationRule &fe_elem_nodes = fe_elem->GetNodes();
mfem::ElementTransformation *T = fespace.GetMesh()->GetElementTransformation(elem_id);
T->Transform(fe_elem_nodes, elem_pm);
mfem::real_t *elem_pm_data = elem_pm.GetData(); // column-major storage
for (int m=0; m<elem_pm.Height(); m++) {
  for (int n=0; n<elem_pm.Width(); n++) std::cout << "elem_pm[" <<m<<","<<n<<"] = " << elem_pm_data[m*elem_pm.Height()+n] << "\t";
  std::cout << std::endl;
}
```
Here is the output for the first boundary element:
```
face_pm[0,0] = 0.25     face_pm[0,1] = 0.25     face_pm[0,2] = 0        face_pm[0,3] = 0.25
face_pm[1,0] = 0.25     face_pm[1,1] = 0        face_pm[1,2] = 0        face_pm[1,3] = 0
face_pm[2,0] = 0        face_pm[2,1] = 0.25     face_pm[2,2] = 0        face_pm[2,3] = 0
elem_pm[0,0] = 0        elem_pm[0,1] = 0        elem_pm[0,2] = 0        elem_pm[0,3] = 0.25     elem_pm[0,4] = 0        elem_pm[0,5] = 0        elem_pm[0,6] = 0        elem_pm[0,7] = 0.25
elem_pm[1,0] = 0.25     elem_pm[1,1] = 0        elem_pm[1,2] = 0        elem_pm[1,3] = 0        elem_pm[1,4] = 0.25     elem_pm[1,5] = 0        elem_pm[1,6] = 0.25     elem_pm[1,7] = 0.25
elem_pm[2,0] = 0        elem_pm[2,1] = 0.25     elem_pm[2,2] = 0        elem_pm[2,3] = 0.25     elem_pm[2,4] = 0.25     elem_pm[2,5] = 0        elem_pm[2,6] = 0        elem_pm[2,7] = 0
```
It seems that the element nodes `0`/`6` and `2`/`5` are identical. Specifically, points `[.25,0,0]` and `[.25,.25,0.25]` are missing from the element. Additionally, the face coordinates do not form a valid boundary element.

I am surely missing something obvious, but I can't seem to find it. Could it be in the way I am retrieving the coordinates from the data vectors? 

Any help would be greatly appreciated.

**Comment by LeilaGhaffari** [comment]
It turns out the issue was indeed in the way I was retrieving the coordinates from the data vectors. Despite the comment suggesting otherwise, I was treating it as row-major storage. Thanks to @hughcars  for catching that!

**Comment by LeilaGhaffari** [comment]
Hi again,

I’ve been testing the implementation in Palace. That trick worked and now I’m trying to use `MakePeriodic` when the user provides a non-periodic mesh and specifies the desired periodic directions. Here’s [the implementation](https://github.com/LeilaGhaffari/palace-lg/blob/39cd4e49e9e1f1cbfd3a5e170fabb3c325e5f5ef/palace/utils/geodata.cpp#L1724-L1738) in Palace:
```cpp
  if (!boundaries.periodic.empty()) {
    mfem::real_t tol = 1E-5 / L0;
    auto periodic_mesh = std::move(mesh);
    for (auto &data : boundaries.periodic)
    {
      std::vector<mfem::Vector> translation;
      mfem::Vector translation_vec(data.translation.size());
      std::copy(data.translation.begin(), data.translation.end(), translation_vec.GetData());
      for (int i = 0; i < translation_vec.Size(); ++i) translation_vec[i] /= L0;
      translation.push_back(translation_vec);
      auto p_mesh = std::make_unique<mfem::Mesh>(mfem::Mesh::MakePeriodic(*periodic_mesh, periodic_mesh->CreatePeriodicVertexMapping(translation, tol)));
      if (p_mesh) periodic_mesh = std::move(p_mesh);
    }
    mesh = std::move(periodic_mesh);
  }
```
The issue I’m encountering is that `MakePeriodic` associates a single face with two boundary elements on periodic surfaces. However, when I use [periodic-cube.mesh](https://github.com/mfem/mfem/blob/master/data/periodic-cube.mesh) provided in the MFEM repo, I don’t see this behavior. Am I missing something in my implementation? Additionally, I’m noticing a peculiar problem where a unique "face to boundary element" mapping appears twice on non-periodic surfaces. Any insights or suggestions would be appreciated. Thanks!

**Comment by hughcars** [comment]
We figured this one out in the end so I'm going to close.
