### ISSUE TITLE
Inconsistency Between MFEM + ParaView for Symmetric Tensor Outputs

### ISSUE THREAD

**Issue by j-signorelli** [mfem/mfem#4398]
For outputting a `QuadratureFunction` with vdim = height*(height+1)/2 (where height is the physical dimension of the problem), as would be used in particular for outputting a symmetric tensor, to ParaView using `ParaViewDataCollection`, MFEM orders components from the symmetric  matrix $T_{ij}$ as:

    00 01 02 11 12 22

or for Cartesian coordinates:

    XX XY XZ YY YZ ZZ

However, ParaView by default just automatically labels any 6-component data set as:

    XX YY ZZ XY YZ XZ

See [here](https://discourse.paraview.org/t/automatic-naming-of-tensor-components/8762/15 ) for more information. I don't believe this automatic labeling is employed for anything else except 6-component data arrays.

This is confusing when, for example, viewing local stress tensors in ParaView and seeing incorrectly labeled stresses. A solution to this could be to update `ParaViewDataCollection::Save` to manually include component labels as 00 01 ... , as can be done as explained [here](https://discourse.paraview.org/t/data-array-multi-component-labelling/8006) when outputting a `QuadratureFunction` specifically with vdim = 6:

https://github.com/mfem/mfem/blob/988439f60a9902e29572b83dcb2a142eb8da3dbd/fem/datacollection.cpp#L965-L987

Does this seem like a reasonable solution? It may make more sense to just include component labels 0 1 2 3 4 5 instead for consistency with non-symmetric tensor outputs. Wanted to get thoughts before implementing any changes, thanks!

**Comment by pazner** [comment]
Wow, I had no idea ParaView automatically labelled components that way (I knew it did it for 3-vectors, but not for 6-component arrays). Thanks for looking into it and reporting this.

We should probably just manually add component labels.
