### ISSUE TITLE
Request for an EasyBuild Configueation file 

### ISSUE THREAD

**Issue by colbrydi** [mfem/mfem#4400]
Hello,  our HPC site uses EasyBuild instead of Spack.  Anyone working on an EasyBuild configuration file?  I started one but am new to both MFEM and Easybuild. <https://github.com/colbrydi/eb_mfem/blob/main/MFEM-4.7-foss-2023a.eb>.  Thanks -- Dirk

**Comment by tzanio** [comment]
I am not aware of anyone working on EasyBuild config file, but that will be welcomed.

In case it is useful here are the MFEM recipes for: 

- [Spack](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/mfem/package.py)
- [Homebrew](https://github.com/Homebrew/homebrew-core/blob/master/Formula/m/mfem.rb)
- [OpenHPC](https://github.com/openhpc/ohpc/blob/3.x/components/parallel-libs/mfem/SPECS/mfem.spec)

**Comment by v-dobrev** [comment]
Hi @colbrydi,

For a minimal parallel build of MFEM, you should enable `-DMFEM_USE_MPI=ON` which (in addition to MPI) will require HYPRE and METIS. It may be best to explicitly add the paths to these with `-DMETIS_DIR=<metis-install-prefix> -DHYPRE_DIR=<hypre-install-prefix>`. In your `.eb` file linked above, I see that you explicitly set `-DMFEM_USE_METIS_5=YES` -- the MFEM CMake build system should auto-detect this setting so you don't need to explicitly add it.

I am not familiar with EasyBuild, so I cannot really help with that.

**Comment by tzanio** [comment]
Hi @colbrydi, 

Were you able to make progress on this?

Tzanio
