### ISSUE TITLE
Why complex DOFs are split

### ISSUE THREAD

**Issue by Marshdweller** [mfem/mfem#4410]
Hi everyone,

What was the rationale behind the design decision to keep complex degrees of freedom (DOFs) as real values followed by imaginary values? I initially liked this approach (especially the block real-valued system matrix), but I've come to realize that fetching a complex value from two separate addresses can make CPU caches inefficient.

I understand that the placement of DOFs (vertex DOFs, followed by edges, faces, and internal DOFs) already doesn't play well with caches, especially in the multithreading context. However, keeping real and imaginary parts separate seems to worsen the situation even more.

Am I overlooking some benefits of such a design?

**Comment by tzanio** [comment]
One of the main reasons is preconditioning -- there are really no good complex-valued preconditioners, while you can often use block real-valued preconditioners for the 2x2 real reformulation.

**Comment by Marshdweller** [comment]
> One of the main reasons is preconditioning -- there are really no good complex-valued preconditioners, while you can often use block real-valued preconditioners for the 2x2 real reformulation.

Got it, thank you!
