### ISSUE TITLE
use multi GPUs to accelerate discontinuous Galerkin time domain method

### ISSUE THREAD

**Issue by wangjinchuan001** [mfem/mfem#4413]
Hi I would like to know whether this software can use multi GPUs i.e. MPI+CUDA to accelerate the discontinuous galerkin time domain method? Thanks

**Comment by YohannDudouit** [comment]
Hi @wangjinchuan001 ,
MPI+CUDA is supported for DG mass, advection, and diffusion operators. You can either use sparse matrices, or matrix-free methods. If you need a very specific operator you might to implement a few things.

**Comment by kaipengliuHIT** [comment]
> Hi @wangjinchuan001 , MPI+CUDA is supported for DG mass, advection, and diffusion operators. You can either use sparse matrices, or matrix-free methods. If you need a very specific operator you might need to implement a few things.

Hello @YohannDudouit  where I can find if the intergrator is supported by CUDA, I see the imformation about GPU on the MFEM offical website but did not find the list of  intergrators supported by CUDA.

And by the way, if I want to implement a intergrators supported by CUDA, what are the things I need to pay attention to？
