### ISSUE TITLE
Can a variational form contain more than two integrators?

### ISSUE THREAD

**Issue by AIBSCT80** [mfem/mfem#4417]
Hi, 

may I ask if it is possible to add different integrators into 
one variational form,  like

`ParBilinearForm *pVarf(new ParBilinearForm(pfespace));`

`pVarf->AddDomainIntegrator(new MassIntegrator(one));`

`pVarf->AddDomainIntegrator(new DiffusionIntegrator(one));`

`OperatorHandle  C;`

`pVarf->Assemble(); `

`pVarf->FormSystemMatrix(p_ess_tdof_list, C);`

In the end, will matrix C contain both  mass and diffusion parts ?

Thanks

**Comment by pazner** [comment]
Yes, all the integrators (domain, boundary, etc.) are summed and assembled into the matrix. You can add as many integrators as you need.

**Comment by AIBSCT80** [comment]
Thank you @pazner .  This is really a great help.  It seems I did it correctly now. Many thanks.
