### ISSUE TITLE
cubit mesh error

### ISSUE THREAD

**Issue by tangqi** [mfem/mfem#4422]
Hi, I had a mesh generated by the attached cubit geo, but mfem does not like it. Any ideas? I am new to cubit. Thanks.

```
$ ./mesh-explorer -m ~/code/icf/geo/sphere.e
Options used:
   --mesh /Users/qtang/code/icf/geo/sphere.e
   --num-proc 0
   --refinement


MFEM abort: Fatal NetCDF error: NetCDF: Invalid dimension ID or name
 ... in function: void mfem::cubit::HandleNetCDFError(const int)
 ... in file: mesh/mesh_readers.cpp:2982
 ```

[cubit01.cub.zip](https://github.com/user-attachments/files/16365549/cubit01.cub.zip)

**Comment by tangqi** [comment]
I tried a simple brick geometry, and it ran into a different error in `HandleNetCDFError`.  I am using Cubit 16.16.1. Is it possible that was related to my version?

**Comment by jandrej** [comment]
You need to define all element blocks and boundaries properly and export as netcdf/hdf5 dataset from cubit. Are you doing that?

**Comment by tangqi** [comment]
Thanks for that! I got it working after defining both blocks and boundaries. 

One more question: how can we make this mesh higher-order?  I am not sure what would be the right process to tune the curvature to correctly resolve each surface at r=r_i. 
![Screenshot 2024-07-24 at 1 27 57 PM](https://github.com/user-attachments/assets/a0239223-b895-4523-a320-e77838943b51)

**Comment by jandrej** [comment]
You choose your element block to be of QUAD9 instead of QUAD4
