### ISSUE TITLE
Boundary Condition E=(1,0,0) for Nedelec elements for tetrahedral meshes

### ISSUE THREAD

**Issue by Marshdweller** [mfem/mfem#4424]
Hi everyone,

I am working on solving the equation `curl curl E + i a E=J` using Nedelec finite element spaces on a tetrahedral mesh. My computational domain is a cube. I need to apply the Dirichlet BC `E=(1,0,0)` on one face of the cube (physically this is a current sheet flowing in the X direction). It seems that neither the examples nor the miniapps provide a direct solution for this scenario. Could anyone provide guidance for it? Thank you

M

**Comment by Rickbude** [comment]
I think `ProjectBdrCoefficientTangent` should do the trick, see the [Gridfunction documentation](https://docs.mfem.org/html/classmfem_1_1GridFunction.html#a4d17e0dfd255b8a2abf659ac67d7fdbc).
