### ISSUE TITLE
Fast Marching Method with adaption

### ISSUE THREAD

**Issue by a-jp** [mfem/mfem#4425]
Hi,

I would like to implement the fast marching method into a code that can perform cell adaption.  My requirements are that in 2D the cells be structured quads that can be refined, and in 3D structured hexs that can be refined.  I must store all my data at nodes, not cell centres.  I need to write to a file that can be read by paraview, with the refinement, and the data at the nodes.  The fast marching method is a unique solution process, really I just want to borrow some functionality from MFEM to do structured AMR refinement on regular shaped cubes, and ensure I can use node storage data and when I write to paraview I can write to a file it will understand without my data being interpolated to the cell centres.

How much of the above if any would be doable in MFEM or even pyMFEM?  Are there any examples that could help me get started with parts of the above?

Thanks

**Comment by tzanio** [comment]
If I understand correctly, all of the above can be done in MFEM with an H1 grid function on an AMR mesh.

Examples 6 or 15 could be good starting points.
