### ISSUE TITLE
Parallel solvers for the wave equation

### ISSUE THREAD

**Issue by AIBSCT80** [mfem/mfem#4427]
Hi, 

may I sincerely ask if there is a parallel version of `Example 23: Wave Problem` .  Would it be possible/easy to extend this to the parallel one?  My problem size get really large, I am looking for a parallel solver for similar problem. Thanks

**Comment by tzanio** [comment]
I don't think this will be too difficult to do -- the changes should be similar to the other serial/parallel pairs of examples.

The original author is @IdoAkkerman, but you can probably try to do that yourself.

**Comment by AIBSCT80** [comment]
@tzanio  thanks a lot for the information.  I will try to do it myself.
