### ISSUE TITLE
Boundary Dof (id) and physical location

### ISSUE THREAD

**Issue by karthichockalingam** [mfem/mfem#4429]
Hello,

I hope my question is simple to answer. We were able to get the physical location of the nodes on the boundary of a 2D Linear Quadrilateral element in H_1 space.  I would like to map the physical location to the corresponding boundary DOF (id) 

```
int bnd_pts = dim * mesh_micro.GetNBE();
Vector vxy( mesh.GetNBE() * dim);

   for (int i = 0; i < mesh.GetNBE(); i++)
   {
      const FiniteElement * elem = fespace_micro.GetBE(i);
      const IntegrationRule & ir = elem->GetNodes();

      FaceElementTransformations * T = mesh_micro.GetBdrFaceTransformations(i);
      DenseMatrix P;
      T->Transform(ir, P);
      
      for (int j = 0; j < ir.Size(); j++)
      {
        //std::cout <<   P(0, j) << "  " << P(1, j) << std::endl;
        vxy((2*i)+j)           = P(0, j);
        vxy(bnd_pts + (2*i)+j) = P(1, j);
      }
   }
```

I understand I can get the boundary DOFs using
```
   Array<int> boundary_dofs;
   fespace.GetBoundaryTrueDofs(boundary_dofs);
```

**Q(1):**
When I get the boundary nodes using

```const IntegrationRule & ir = elem->GetNodes();```

I don't know which boundary Dof (id) it corresponds to.

**Q(2)**

 I would like to evaluate a f(x,y) at the boundary (dof's) physical location and ultimately impose this function as Dirichlet boundary condition using ``` virtual void ProjectBdrCoefficient(VectorCoefficient &vcoeff, const Array<int> &attr);```.  I am not sure how to go about it. 

Does ```vcoeff``` have a one-to-one correspondence to the array in  ```boundary_dofs```?

Thanks a lot!
Karthik.

(cc @nmnobre)

**Comment by vladotomov** [comment]
Please keep the discussion in #4406.
