### ISSUE TITLE
Boundary conditions using the Gradientintegrator in the navier mini app

### ISSUE THREAD

**Issue by JonasBeddrich** [mfem/mfem#4432]
My question is about the do-nothing boundary condition in the Navier mini-app. 

In the last of the three steps, a Helmholtz-type equation is solved to obtain the velocity. The pressure enters using the GradientIntegrator, which, as I understand, implements $\int (\nabla p^{n+1}) \bf{v} \mathrm{d}\Omega,$ where $p$ is the pressure determined in the previous step and $\bf{v}$ is a vector-valued test function. 

The documentation of the mini-app states that not prescribing boundary conditions results in a natural do-nothing boundary condition. As I understand, the natural do-nothing BC arises from partially integrating the diffusion term and the pressure term, namely, $\int \Delta \bf{u} \bf{v} \mathrm{d}\Omega = \int \bf{n} \nabla \bf{u} \bf{v} \mathrm{d}\Gamma - \int \nabla \bf{u}: \nabla \bf{v} \mathrm{d}\Omega,$ where $\bf{u}$ is the velocity and $\bf{n}$ is the outer normal vector, and $\int \nabla p \bf{v} \mathrm{d}\Omega = \int \bf{n} p \bf{v} \mathrm{d}\Gamma - \int p \nabla \cdot \bf{v} \mathrm{d}\Omega,$ and subsequently dropping both boundary terms, equivalent to prescribing $\nu \nabla \bf{u} \cdot \bf{n} - p Id \cdot \bf{n} = 0$. 

Using the GradientIntegrator, the weak formulation still contains the pressure boundary term, and from looking at the implementation of GradientIntegrator, I don't understand how this is handled to obtain a do-nothing boundary condition.

**Comment by jandrej** [comment]
The theory in Navier follows the [derivation in Nek5000](https://nek5000.github.io/NekDoc/theory.html). Along with the [description of their boundary conditions](https://nek5000.github.io/NekDoc/problem_setup/BCs.html#fluid-velocity) this is explained thoroughly.

**Comment by JonasBeddrich** [comment]
@jandrej Thank you for providing these ressources, but my question is directly concerned with implementation in the mfem miniapp. As I understand it, the Gradientintegrator implements $\int \nabla p^{n+1} v \mathrm{d}x$ (in eq. (11) of the [miniapp description](https://mfem.org/fluids/)), which should result in $\nu \nabla u^{n+1} \cdot n = 0$ as BC instead of $\nu \nabla u^{n+1} \cdot n - p^{n+1} I \cdot n = 0$ (eq. (13) of the [miniapp description](https://mfem.org/fluids/) or “O” in [Nek5000BC](https://nek5000.github.io/NekDoc/problem_setup/BCs.html#fluid-velocity)) if the boundary condition is not specified.
