### ISSUE TITLE
Some SWIG Typemap is brokend due to real_t (instead of double)

### ISSUE THREAD

**Issue by sshiraiwa** [mfem/mfem#4433]
For example, this one (https://github.com/mfem/PyMFEM/blob/master/mfem/_ser/sparsemat.i#L102) does not work because
the header files is written as
```
SparseMatrix(int *i, int *j, real_t *data, int m, int n);
```

**Comment by tzanio** [comment]
Hi @sshiraiwa, is this to remember to do something about it on the PyMFEM side, or do you think we should make changes in MFEM?

**Comment by sshiraiwa** [comment]
Closing this. Actually, I didn't realize I opened this in mfem/mfem. My. fault.
To answer Tzanio's question,  a root cause is simply because I can not make SWIG to aware a specific
class method arguments pattern as a target of SWIG type map translation. I am not sure if this is because
I am missing something or SWIG is missing something.
