### ISSUE TITLE
Removing sundials prefix from executable name is breaking some ninja builds

### ISSUE THREAD

**Issue by chapman39** [mfem/mfem#4437]
This recent change in sundials is causing LiDO, a downstream user of MFEM, to be unable to configure mfem as a submodule via CMake with the `-G Ninja` option:

https://github.com/mfem/mfem/commit/1410aef639c436a21b4fca7f0789ab7525469b9e#diff-84e7c3b7b63ab7f0ff38f0c8855c645a0672bba6b1cee68c95026cc4149bb692R42-R47

```cmake
# Remove "sundials_" prefix from exectuable name for consistency with GNU build
# system.
foreach(SRC_FILE ${SUNDIALS_EXAMPLES_SRCS})
  get_filename_component(SRC_FILENAME ${SRC_FILE} NAME)
  string(REPLACE ".cpp" "" TARGET_NAME "${PFX}${SRC_FILENAME}")
  string(REPLACE ${PFX} "" EXE_NAME ${TARGET_NAME})
  set_target_properties(${TARGET_NAME} PROPERTIES OUTPUT_NAME ${EXE_NAME})
endforeach()
```

Removing this block resolves the issue. My guess is Ninja is more strict than other generators. Unfortunately, I have not reproduced this problem with MFEM by itself.

**Comment by chapman39** [comment]
Another thing I should mention is we set `MFEM_ENABLE_EXAMPLES=OFF`, but the examples are still part of the project due to this line. https://github.com/mfem/mfem/blob/master/CMakeLists.txt#L731

**Comment by cjvogl** [comment]
That block of CMake code was added to maintain consistency within MFEM between the GNU and CMake build systems w.r.t. the executables produced. If this is an issue that cannot be reproduced with MFEM itself, can you provide more information about what the configuration issue is?

**Comment by tepperly** [comment]
@chapman39, it seems in mfem's build the executables end up in different directories. Do you have any idea why they end up in the same directory in the LiDO co-develop build?

**Comment by chapman39** [comment]
I discovered the reason both ex9's are put in the same location (`bin`) - it's not related to MFEM, so I will close this issue.
