### ISSUE TITLE
Which solver to use with MixedVectorWeakDivergenceIntegrator?

### ISSUE THREAD

**Issue by denislachapelle** [mfem/mfem#4438]
I would like to know which solver to use with the MixedVectorWeakDivergenceIntegrator domain integrator?

More generally; once I decide which integrators to use for solving a particular problem; how can I find which solver to use?

If there is a textbook covering this topic let me know.

Thank you very much,
Denis

**Comment by tzanio** [comment]
This is not an easy question to answer, and in general different PDE operators require different solver approaches.

`MixedVectorWeakDivergenceIntegrator` corresponds to a rectangular matrix. Can you clarify what is the matrix you are trying to invert?

**Comment by denislachapelle** [comment]
Tzanio,

It is very possible that I ask strange questions or questions with an enormous scope, I am not an expert in FEM, for me its a hobby related somehow to my work, I am an electrical engineer and I would like to learn FEM, especially mfem which seems to be very complete. So, I have successfully compute the voltage potential in a pair of conductors and the the E-field by computing the gradient using the MixedVectorGradientIntegrator, all this in 3D. Now I would like to compute the E-field directly without passing through the voltage scalar potential. So instead of div(grad(u))=0 it become div(E), where E is a vector. Looking at mfem web site I found the following integrator that seems to do what I want..
![image](https://github.com/user-attachments/assets/36531866-3b12-4836-827e-2e5baa4c8933)
 The ultimate goal being to compute the E-field to get the current density J in DC. Then I will use this current density as a source in the conductor but using time harmonic at let say 400Hz to compute the generated H-field and then compute the induced current, which will be in reverse direction compare to the source. This is the proximity effect.
Hope this make sense!
Denis
