### ISSUE TITLE
Verifying correct parallel mfem-3.3.2 build with hypre-2.11.2 and metis-4.0.3 on a Virtual Ubuntu 16.04

### ISSUE THREAD

**Issue by tmmcmanus** [mfem/mfem#444]
Hi,

I am trying to confirm that I properly built a parallel version of mfem-3.3.2.  

I follow the parallel build instructions here: [http://mfem.org/building/](http://mfem.org/building/)

and from within mfem/ run 'make check' and see 'Parallel example [ mpirun -np 4 ex1p ... ]: OK'

However, when I goto mfem/examples/ I note that only two files where created, namely mesh.000000 and sol.000000, which I think is incorrect (in that there should be a mesh/sol file from each processor).

This leads me to believe that mpirun (or my mpicxx )is not behaving properly and is spawning 4 MPI tasks and solving the entire problem 4 times as opposed to utilizing parallel partitioning  (like seen here in Ex1p: [http://mfem.org/parallel-tutorial/#building](http://mfem.org/parallel-tutorial/#building))

Here are the first few line of 'mpirun -np 4 ex1p' from within mfem/examples/ as well:
Options used:
   --mesh ../data/star.mesh
   --order 1
   --no-static-condensation
   --visualization
Options used:
   --mesh ../data/star.mesh
   --order 1
   --no-static-condensation
   --visualization
Options used:
   --mesh ../data/star.mesh
   --order 1
   --no-static-condensation
   --visualization
Options used:
   --mesh ../data/star.mesh
   --order 1
   --no-static-condensation
   --visualization
Number of finite element unknowns: 82561
Number of finite element unknowns: 82561
Number of finite element unknowns: 82561
Number of finite element unknowns: 82561
Size of linear system: 82561
Size of linear system: 82561
Size of linear system: 82561
Size of linear system: 82561

Could this be a build configuration issue related to metis or hypre?

Also, I have been able to build and run other mpi binaries properly, which makes me think this is not a problem unique to this particular virtual machine.

Thanks in advance,

Tim

**Comment by v-dobrev** [comment]
The output you show looks like the result of running 4 separate copies of ex1p at the same time. Can you check your MPI with something like an MPI version of "hello world":
```c++
#include <mpi.h>
#include <iostream>
int main()
{
   MPI_Init(NULL, NULL);
   int myid, nprocs;
   MPI_Comm_size(MPI_COMM_WORLD, &nprocs);
   MPI_Comm_rank(MPI_COMM_WORLD, &myid);
   std::cout << "Hello from rank " << myid << " of " << nprocs << std::endl;
   MPI_Finalize();
   return 0;
}
```
For example, running on 3 processors, I get:
```ascii
Hello from rank 2 of 3
Hello from rank 1 of 3
Hello from rank 0 of 3
```

**Comment by tmmcmanus** [comment]
Veselin,

I copy and save your file as 'test.cpp' and then run 'mpicxx test.cpp' and then run 'mpirun -np 3'.  The output is:

Hello from rank 1 of 3
Hello from rank 2 of 3
Hello from rank 0 of 3

**Comment by v-dobrev** [comment]
Hmm, OK. Can you run `make info` in the  main mfem directory (after building mfem) and paste the result here?

**Comment by tmmcmanus** [comment]
MFEM_VERSION         = 30302 [v3.3.2]
MFEM_GIT_STRING      = 
MFEM_USE_MPI         = YES
MFEM_USE_METIS       = YES
MFEM_USE_METIS_5     = NO
MFEM_DEBUG           = NO
MFEM_USE_GZSTREAM    = NO
MFEM_USE_LIBUNWIND   = NO
MFEM_USE_LAPACK      = NO
MFEM_THREAD_SAFE     = NO
MFEM_USE_OPENMP      = NO
MFEM_USE_MEMALLOC    = YES
MFEM_TIMER_TYPE      = 2
MFEM_USE_SUNDIALS    = NO
MFEM_USE_MESQUITE    = NO
MFEM_USE_SUITESPARSE = NO
MFEM_USE_SUPERLU     = NO
MFEM_USE_STRUMPACK   = NO
MFEM_USE_GECKO       = NO
MFEM_USE_GNUTLS      = NO
MFEM_USE_NETCDF      = NO
MFEM_USE_PETSC       = NO
MFEM_USE_MPFR        = NO
MFEM_USE_SIDRE       = NO
MFEM_CXX             = mpicxx
MFEM_CPPFLAGS        = 
MFEM_CXXFLAGS        = -O3
MFEM_TPLFLAGS        = -I$(MFEM_DIR)/../hypre-2.11.2/src/hypre/include
MFEM_INCFLAGS        = -I$(MFEM_INC_DIR) $(MFEM_TPLFLAGS)
MFEM_FLAGS           = $(MFEM_CPPFLAGS) $(MFEM_CXXFLAGS) $(MFEM_INCFLAGS)
MFEM_LIBS            = -L$(MFEM_LIB_DIR) -lmfem -L$(MFEM_DIR)/../hypre-2.11.2/src/hypre/lib -lHYPRE -L$(MFEM_DIR)/../metis-4.0 -lmetis -lrt
MFEM_LIB_FILE        = $(MFEM_LIB_DIR)/libmfem.a
MFEM_BUILD_TAG       = Linux comp x86_64
MFEM_PREFIX          = ./mfem
MFEM_INC_DIR         = $(MFEM_DIR)
MFEM_LIB_DIR         = $(MFEM_DIR)
MFEM_BUILD_DIR       = .
MFEM_MPIEXEC         = mpirun
MFEM_MPIEXEC_NP      = -np
MFEM_MPI_NP          = 4

**Comment by v-dobrev** [comment]
Is it possible that you have `ex1p` somewhere else in your `PATH`? Try running `mpirun -np 4 ./ex1p`. If that does not help, try adding the line
```c++
   std::cout << "Hello from rank " << myid << " of " << num_procs << std::endl;
```
after the lines
https://github.com/mfem/mfem/blob/bc6b48421ac6506db6fea2f9d6222f145427f8c8/examples/ex1p.cpp#L50-L51
and then run `mpirun -np 4 ./ex1p`. Can you copy the full output from that?

**Comment by tmmcmanus** [comment]
I think I solved it.

For some reason mpicc.mpich and mpicxx.mpich where being used instead of mpicc.openmpi and mpicxx.openmpi.

Now `mpirun -np 4 ex1p` returns:

```
Options used:
   --mesh ../data/star.mesh
   --order 1
   --no-static-condensation
   --visualization
Number of finite element unknowns: 82561
Size of linear system: 82561


 Num MPI tasks = 4

 Num OpenMP threads = 1
```
Thanks for the prompt help though Veselin.

-Tim
