### ISSUE TITLE
Bug in VTK reader or writer?

### ISSUE THREAD

**Issue by mdavids-cfs** [mfem/mfem#4445]
Hi all,
I've been working with MFEM for quite a while (previously contributed under a different name @Maatinski ) and noticed an odd situation with the VTK reader: it seems that the boundary information is getting lost somewhere in the reading process.

I used the `mesh_explorer` miniapp to test this:

1) Read `coil.gen` in `mesh_explorer`, plot boundary, all looks good
2) Export to `.vtk` format, looking at the file it seems the boundary is still saved correctly (varying between 1 and 4)
3) Read `coil.vtk` in `mesh_explorer`, plot boundary, seems like all boundary facets are assigned `attribute = 1`

If I read the mesh in my code, it also shows `pmesh.bdr_attributes.Max() = 1`

Any chance that something is wrong in the VTK reader, or am I missing something?

Thanks a lot!
Mathias

**Comment by pazner** [comment]
The VTK format doesn't really support boundary information. As far as I know, this is a limitation of the format itself, and not something we can do much about in MFEM. I think the VTK and VTU formats are mostly useful for visualization, but other formats are probably better suited for actual computation.

**Comment by mdavids-cfs** [comment]
Ok, thanks for clarifying! That makes a lot of sense! Was hoping to get away with not writing a custom mesh reader/writer for my specific application (trying to import a mixed element `nastran` mesh) but might be easiest to just write a quick converter.

**Comment by pazner** [comment]
Maybe [meshio](https://github.com/nschloe/meshio) could help with this. Apparently it supports Nastran bulk data (.bdf, .fem, .nas) formats.

**Comment by mdavids-cfs** [comment]
Thanks for the hint, @pazner ! For now, I've just written a quick `.nas` importer in python and export the mesh in MFEM `.mesh`. We're dealing with mixed meshes, so some of the other formats (at least the ones I was familiar with) did not work quite well for this... but seems to work now.

**Comment by pazner** [comment]
Sounds good. Closing for now, please re-open if you have any other issues.
