### ISSUE TITLE
Possible issue in 3D in det.cpp?

### ISSUE THREAD

**Issue by rw-anderson** [mfem/mfem#4446]
I'm seeing memory errors in 3D calculations (but not corresponding 2D calculations) in this region of mfem, according to valgrind, which is showing invalid writes.

I can't say I really understand what's going on in this code, but I'm wondering about this snippet
https://github.com/mfem/mfem/blob/cdf9cfe1b670497baa5c1fab99e635fb860e54e6/fem/qinterp/det.cpp#L235-L238

In the 2D code, there appears to be parallel construction with the expressions consistently using "Q1D" and "D1D", e.g.:
https://github.com/mfem/mfem/blob/cdf9cfe1b670497baa5c1fab99e635fb860e54e6/fem/qinterp/det.cpp#L127-L128

But in 3D, they are reversed for part of the expression. 

There's also a similar pattern here, with "D" and "Q" apparently reversed.
https://github.com/mfem/mfem/blob/cdf9cfe1b670497baa5c1fab99e635fb860e54e6/fem/qinterp/det.cpp#L225-L226

Maybe this is ok, I'm not sure, but I thought I'd ask.

**Comment by pazner** [comment]
I agree it looks suspicious. Does reversing Q1D and D1D fix the memory error?

**Comment by v-dobrev** [comment]
The actual values for `MAX_D1D` and `MAX_Q1D` seem to be the same in all cases, so the fact that they switched doesn't matter for correctness. Of course, we should fix the usage to avoid further confusion.

**Comment by rw-anderson** [comment]
> I agree it looks suspicious. Does reversing Q1D and D1D fix the memory error?

It did not, which makes sense given what Veselin said. It's possible the valgrind errors are false positives, too. I will have to keep investigating.

**Comment by tzanio** [comment]
Discussion continued in #4447
