### ISSUE TITLE
ex5 and ex5p do not work with -pa when using square-disc.mesh

### ISSUE THREAD

**Issue by xrfe** [mfem/mfem#4454]
Hi mfem team,
I just realized that the example 5 does not work with square-disc.mesh when enabling partial assembly.
does this example work only for simply connected geometry?

Thanks

**Comment by pazner** [comment]
Partial assembly only current supports tensor-product elements (quadrilaterals and hexahedra). The square-disc mesh is a triangular mesh, so it won't work with PA. You can generate a quad mesh of the same geometry (e.g. in gmsh or another mesh generator) that will work with PA.

(I will also mention that if you are interested in Darcy + partial assembly, there is also miniapps/hdiv-linear-solver/darcy.cpp that illustrates a matrix-free solver for these problems suitable for use with partial assembly. Only quad and hex meshes are supported though.)
