### ISSUE TITLE
`FindPointsGSLIB` behavior when `point_pos` is empty on a rank.

### ISSUE THREAD

**Issue by victor-decaria-nnl** [mfem/mfem#4459]
**Summary :** 
I think find points should account for the possibility of a rank requesting no points. Currently, an assertion in `DistributePointInfoToOwningMPIRanks` fails if a rank didn't request any points.

**Description:**
I've been using the new `FindPointsGSLIB` features `DistributePointInfoToOwningMPIRanks` and `DistributeInterpolatedValues` to transfer boundary values between two meshes that only overlap on a shared boundary, such as a unit square [0,1]^2 and another one translated to the right, [1,2] x [0,1].

My workflow is as follows:
1) Generate list of points (either quadrature or nodal) on boundary of Mesh A.
2) Create a `FindPointsGSLIB` object using mesh B, run `Setup`, `FindPoints`, and  `DistributePointInfoToOwningMPIRanks`.
3) Do custom interpolation
4) Run `DistributeInterpolatedValues` and use values as needed on mesh A

The problem is that in step 1, a rank might not overlap with the boundary of interest and therefore not find any points to request, so the input `point_pos` is empty on that rank. Then `DistributePointInfoToOwningMPIRanks` fails because of an assertion on `points_cnt`.

**Current workaround:**
On a rank that would fail this assertion, request a dummy point that I know is on the mesh, and discard the interpolated result.

The above procedure and workaround is for when mesh A and mesh B use the same `MPI_Comm`, but I think this issue also applies to the more complicated case of mesh A and mesh B using different communicators.

**Comment by kmittal2** [comment]
Thanks for bringing this to our attention @victor-decaria-nnl. I will put in a fix this week.

**Comment by kmittal2** [comment]
Hi @victor-decaria-nnl, please have a look at #4461.

Regarding using meshes with different communicators.. You could use OversetFindPointsGSLIB class which supports functionality for overlapping meshes, but even in that case, the MPI communicator in the constructor must be the union of communicators for both mesh A and B.

**Comment by victor-decaria-nnl** [comment]
OversetFindPointsGSLIB looks like it will work. I have some questions about its usage.

In my case, the communicators for mesh A and B are formed from a comm_split with only two colors. So I will construct with the larger communicator. Would I call setup once from each rank since the meshes are in disjoint groups? something like,
```
if(color == color_A)
   Setup(mesh_A, color_A, ....)
else
   Setup(mesh_B, color_B, ....)
```
And for use with the custom interpolation workflow, if mesh A needs values from mesh B, but mesh B doesn't need values for A, would I do
```
if(color == color_A)
   FindPoints(coords, <point_ids_all_set_to_mesh_B>, ...)
else
   // Does something need to be run from mesh B to avoid hanging?
   FindPoints(<empty_vector>, ....)
```
Thanks

**Comment by kmittal2** [comment]
@victor-decaria-nnl ,

Please have a look at [this](https://github.com/mfem/mfem/blob/master/miniapps/gslib/schwarz_ex1p.cpp) example that usage of `OversetFindPointsGSLIB` for overlapping grids.

The setup and FindPoints call should not be in separate `if-else` blocks. You can create an empty vector for ranks corresponding to mesh B. 

Ketan

**Comment by tzanio** [comment]
@victor-decaria-nnl, did the above ☝️ help?
