### ISSUE TITLE
Div- and curl-conforming spline spaces?

### ISSUE THREAD

**Issue by tmmcmanus** [mfem/mfem#446]
Are there any plans in the future to include support for Div- and curl-conforming spline spaces?  Similar to what is done by Vázquez  in [geoPDEs](https://github.com/rafavzqz/geopdes).

**Comment by tzanio** [comment]
Yes, the first step was https://github.com/mfem/mfem/pull/279.

cc: @IdoAkkerman

**Comment by tmmcmanus** [comment]
Nice.  
I will keep an eye on this.
On a related note, does Hypre have a solver specifically tuned to for coefficient matrices typical of isogeometric analysis?

**Comment by tzanio** [comment]
Not as far as I know.

**Comment by tmmcmanus** [comment]
No worries. I will look more into it.  Thanks for all the info though and I will keep a look out for future implementations of Div- and curl-conforming spline spaces in MFEM.
