### ISSUE TITLE
Incompatible Vectors when doing de-refinement for a time-dependent problem with a right-hand side

### ISSUE THREAD

**Issue by iniyonzima** [mfem/mfem#4463]
Hi MFEM team,

I am using MFEM to model streamer discharges that can occur in electrical devices. To do this, I implemented a simplified model based on the paper "Comparison of Six Simulation Codes for Positive Streamers in Air" (equations (1)-(4) and parameters from section 2 of the paper: https://digital.csic.es/bitstream/10261/214989/4/IAA_2018PSST...27i5002B.pdf). 

The model comprises three PDEs: an advection-diffusion-reaction PDE for the time-dependent distribution of electrons, a PDE for positive ions (neglecting advection and diffusion due to the low mobility of ions), and an electrostatic equation for the electric field distribution. The coefficients of the first two equations depend non-linearly on the electric field obtained by solving the last equation.

The computational domain is approximately 10 cm in size, and I need to use a mesh with a minimum element size on the order of a µm. To efficiently track the wavefront of electrons and positive ions, I plan to use mesh refinement and de-refinement techniques. I am also using very small time steps (of the order of a picosecond) for stability purposes. Currently, I am using an implicit time-stepping scheme.

I successfully implemented an unrefined version of the model, with results that align well with those in the paper. However, I would like to refine/de-refine in order to reduce the computational time. To achieve this, I am combining features from example 15 on mesh refinement, and from example 16 on the use of `TimeDependentOperator` for time integration. I also slightly modified the ImplicitSolve function from example 16 to include a right-hand side represented by a `LinearForm` and that I need, e.g. for equation (2) of the paper. The function currently looks like:

```c++
void AdvectionDiffusionReactionOperator::ImplicitSolve(const double dt, 
                                                       const Vector &u, 
                                                       Vector &du_dt) 
{
   if (!T)
   {
      T = Add(1.0, Mmat, dt, Kmat);
      current_dt = dt;
      T_solver.SetOperator(*T);
   }
   MFEM_VERIFY(dt == current_dt, ""); // SDIRK methods use the same dt
   Kmat.Mult(u, z);
   z.Neg();
   z += F;
   T_solver.Mult(z, du_dt);
}
```

where F is of type `LinearForm`. 

When I set `mesh->EnsureNCMesh(true)` in my main function, there's a size mismatch at the line `z += F;`. It appears that `z` has the size `fes->GetNConformingDofs()` while `F` has the size `fes->GetNVDofs()`, where `fes` refers to the `FiniteElementSpace`.

What would you suggest me to do to get the size of the `LinearForm` right in the case of non-conforming mesh?

Could you also recommend another piece of MFEM code that performs similar simulations as mine ?

**Comment by psocratis** [comment]
> When I set `mesh->EnsureNCMesh(true)` in my main function, there's a size mismatch at the line `z += F;`. It appears that `z` has the size `fes->GetNConformingDofs()` while `F` has the size `fes->GetNVDofs()`, where `fes` refers to the `FiniteElementSpace`.
> 
> What would you suggest me to do to get the size of the `LinearForm` right in the case of non-conforming mesh?
> 
> Could you also recommend another piece of MFEM code that performs similar simulations as mine ?

Hi @iniyonzima ,

When the mesh is non-conforming then there are constraints between dofs. The constrained dofs do not enter the linear system, instead they contribute to the system through the "true" dofs (the constraining dofs). In the code snippet above, I assume that `K` in the assemble matrix, which acts on "true" dofs. Hence its action gives a load vector in the "true dof space". This is not the case for a `LinearForm` . You can look at the diagram [here](https://mfem.org/pri-dual-vec/) to see how you can transfer back and forth depending also if you are dealing with a `GridFunction` or a `LinearForm`. 

I hope this helps.

**Comment by iniyonzima** [comment]
Hi @psocratis ,

Thank you for your answer. The diagram helped me understand how to navigate between dofs and tdofs, and get my code running further. I am still debugging the code and as someone new to advection-diffusion-reaction equations, to the methods used to solve them (stabilization, refinement/de-refinement, etc.) and to MFEM, I may reach out again if I have another question.

**Comment by psocratis** [comment]
@iniyonzima , 
I am glad it works now. I am closing this issue now and you can reach out again if anything else comes up.
