### ISSUE TITLE
Question about computing determinant

### ISSUE THREAD

**Issue by joshia5** [mfem/mfem#4465]
Hello,
I am trying to compute Jacobian and it’s determinant for the finite element shape functions at vertices of elements. 
By my understanding, this is one way to compute determinant for the shape functions of the mesh : https://github.com/mfem/mfem/blob/5f373e8c2a70acb413e0fb2a7c1be8054ab6079e/tests/unit/miniapps/test_tmop_pa.cpp#L452:

```

   for (int i = 0; i < NElems; i++)
   {   
     ElementTransformation *transf = pmesh->GetElementTransformation(i);
     for (int j = 0; j < ir->GetNPoints(); j++)
     {   

       transf->SetIntPoint(&ir->IntPoint(j));
       double j_det = transf->Jacobian().Det();
     }   
   }   

```

How can this be done for a ND or other FEspace of choice, get the element transformation for it and
compute the det. at vertices of elements instead of the integration points?

Please let me know if there are any suggestions.
Thank you.

**Comment by pazner** [comment]
You can get the vertices as an integration rule and then follow the example of the snippet that you posted:

```c++
const IntegrationRule *ir = Geometries.GetVertices(mesh.GetElementGeometry(i));
```

**Comment by joshia5** [comment]
Thanks a lot for your response.
The following snippet results in `segmentation fault:core dumped` at the call to `transf->Jacobian();` (shown for H1 space but segfaults for the other 3 types of FEspaces too)
```
  H1_FECollection fec(order, pmesh->Dimension());
   ParFiniteElementSpace fes(pmesh, &fec, pmesh->SpaceDimension());

   for (int i = 0; i < NElems; i++)
   {   
     const IntegrationRule *ir = Geometries.GetVertices(pmesh->GetElementGeometry(i));
     ElementTransformation *transf = fes.GetElementTransformation(i);
     for (int j = 0; j < ir->GetNPoints(); j++)
     {   
       DenseMatrix jac = transf->Jacobian();
       printf("computed J\n");
       double j_det = transf->Jacobian().Det();
     }
   }
```
I'll run a stacktrace for debugging but if there's something obvious that I am missing here please let me know.
Thanks

**Comment by pazner** [comment]
It looks like you are missing `transf->SetIntPoint(&ir->IntPoint(j));`.

(Also, you can call `transf->Weight()` to get the Jacobian determinant directly).
