### ISSUE TITLE
Question about submesh and boundary integrators

### ISSUE THREAD

**Issue by jvwilliams23** [mfem/mfem#4468]
Hi,

I am working on computing a field on the surface of a sphere, and trying to understand a bit about when to use different integrators. I am wondering why example 35 does not use a Boundary Integrator, but rather a Domain Integrator to compute the boundary field (after getting the boundary Submesh)? I thought it would use a Boundary Integrator, similar to example 27. If we get the boundary as a submesh, then there would not be a 'domain' to do Domain integration on?

Any insight would be greatly appreciated.

Josh

**Comment by hughcars** [comment]
Hi @jvwilliams23,

The SubMesh process creates a mesh from a subdomain of an existing mesh, but once created that mesh is just like any other Mesh. So in your example, once a surface submesh is made from the existing mesh, it is exactly equivalent to a mesh in the D-1 space, hence the use of the domain integrator. So starting with a 3D mesh, if you make a surface submesh, you receive a 2D mesh, on which you can apply domain integrators as if you had made any other 2D Mesh. The SubMesh capability can be thought of as a way of creating a Mesh, but which comes with extra methods for transferring between it and it's parent mesh.

**Comment by jvwilliams23** [comment]
Hi @hughcars,
Thanks for the explanation - it makes perfect sense!
