### ISSUE TITLE
Cubit Mesh Reader Error

### ISSUE THREAD

**Issue by srwopschall** [mfem/mfem#4470]
I have various cubit `.gen` mesh files that were being read successfully when using a version of mfem that did not have the recent changes to the mesh readers. We have updated our version of mfem, which now incorporates those changes to the file reader, and now I get a netcdf error from the cubit mesh file reader indicating an `invalid dimension or name`. Did the mesh file reader update introduce an additional requirement when creating a cubit mesh?

**Comment by jandrej** [comment]
The new mesh reader is more strict to ensure correctness.

**Comment by srwopschall** [comment]
Is there an example of how the strictness changed and how a cubit mesh should now be specified or set up? I cannot easily identify why previously read meshes are no longer being read. I have similarly created meshes and some work and some don't, but there is no discernible difference between the two (e.g. specified element blocks, side sets etc.).

**Comment by jandrej** [comment]
All elements need to belong to an element block and all boundaries need to be assigned to a side set. If you define 2D meshes you have to make sure that those are not defined as SHELL elements (which cubit selects by default!). The export has to reflect those settings. See screenshot.
<img width="273" alt="Screenshot 2024-08-23 at 1 31 28 PM" src="https://github.com/user-attachments/assets/ee682671-0bb2-44fd-adf7-2f923b4a6ed1">

**Comment by srwopschall** [comment]
Thanks @jandrej - I will look into this more. It is possible that my sidesets only include contact faces, which may not be all the faces on the boundaries. Is there any requirement to specify a nodeset(s)?

**Comment by jandrej** [comment]
No requirement on having a nodeset (not supported in mfem AFAIK). You have to assign all faces that are "in contact with void" to a sideset.

**Comment by srwopschall** [comment]
It may be the case that there are other requirements that changed. I took two of my meshes that did not have all of the boundary faces assigned to a sideset, and then assigned all parts of the boundary to a sideset. I tried saving in both Large File Format, and NetCDF4/HDF5 Format, and I still get a mesh reader error. Is there a particular naming convention that now needs to be used for element blocks or sidesets?

**Comment by srwopschall** [comment]
Is there a requirement on having unique integer ids between sidesets and blocks? For now I reverted to a previous version of the mesh_reader.cpp and it works fine.

**Comment by tzanio** [comment]
@srwopschall, can you share an example where you see this issue?

**Comment by tzanio** [comment]
relevant PRs: https://github.com/mfem/mfem/pull/3870, https://github.com/mfem/mfem/pull/4178

**Comment by jandrej** [comment]
See #4487

**Comment by srwopschall** [comment]
I gave Julian a mesh and we worked through the issue. Please give us a heads up when this goes in.

**Comment by tzanio** [comment]
Discussion continued in #4487
