### ISSUE TITLE
How to calculate the normal Derivative of a vector Gridfunction?

### ISSUE THREAD

**Issue by cglwdm** [mfem/mfem#4471]
If z is a vector Gridfunction, how to calculate  the normal Derivative of it on boundary?
Since I have
$\boldsymbol{u}-\frac{\partial \boldsymbol{z}}{\partial \boldsymbol{n}}=\mathbf{0}$
on the boundary, I want to pass the information of $\boldsymbol{z}$ though $\boldsymbol{u}$ to another problem.

**Comment by tzanio** [comment]
Hi @cglwdm,

Do I understand correctly that you have two domains with $z$ being a  field in one of them and you want to pass $\frac{\partial z}{\partial n}$ as a boundary condition to the other domain, like in a fluid-structure interaction problem?

Tzanio
