### ISSUE TITLE
const attribute of TimeDependentOperator::Mult and time dependent right hand side

### ISSUE THREAD

**Issue by jandrej** [mfem/mfem#448]
Hello,

I'm having an issue where I need to update a forcing function according to the current time of the operator before evaluation. With implicit methods i can just call the method AssembleRHS() of my derived operator. Since I'd like to use CVODE, which calls Mult() as a functional iteration in a predictor step (or multiple), it's not possible for me to update the RHS according to the current time.

Is there a workaround for that?

Right now I reassemble the RHS on every call s.t. I conform to the const method, which prevents use of a member function.

**Comment by v-dobrev** [comment]
If I understand you correctly, the issue you have is that `Mult` is a `const` method and you want to update some of the data members in your class (derived from class `TimeDependentOperator`) from inside the `Mult` method. In cases like these, I usually add `mutable` to the data members that I want to change - that will allow you to change them in any `const` method.

**Comment by jandrej** [comment]
This particular case needs to call a non const method. So setting a member variable mutable alone doesn't work.

**Comment by v-dobrev** [comment]
Why not make that method const?

**Comment by v-dobrev** [comment]
I guess you are pointing out that the interface of `TimeDependentOperator` is not quite consistent: `Mult()` is const, while `ImplicitSolve` is not. Is this the issue?

**Comment by jandrej** [comment]
I get why `Mult` is const and `ImplicitSolve` is not. I totally get the design choice here. I haven't thought about using mutable on the variable and just making the `AssembleRHS` method const. That solves the issue I guess :-)

**Comment by v-dobrev** [comment]
I think it makes sense on some level to make both `Mult` and `ImplicitSolve` const methods because in both cases you are asking the `TimeDependentOperator` to evaluate its value for a given moment in time. It should not matter if the evaluation is for explicit or implicit time integration.

It is a minor inconsistency, so I don't think it is a high-priority to fix it.

**Comment by jandrej** [comment]
Thanks for the help!

I'm fine now with the solution.
