### ISSUE TITLE
Applying Dirichlet DG Boundary condition to scalar in L2-space

### ISSUE THREAD

**Issue by danielwardstfc** [mfem/mfem#4481]
Hi.  I've adapted the Darcy problem (ex5) to run an electrostatics case and am trying to implement a Dirichlet boundary condition on $\phi$ ($p$ in ex5).  I'm looking to set $\phi = \xi$, where $\xi$ is a real number, on certain boundaries in a square domain.

I currently have the following bit of code isolating the top and bottom boundaries in my mesh
```
   Array<int> dbc_tb(mesh->bdr_attributes.Max());
   dbc_tb = 0;
   dbc_tb[0] = 1;   // Top boundary
   dbc_tb[1] = 0;   // Right boundary
   dbc_tb[2] = 1;   // Bottom boundary
   dbc_tb[3] = 0;   // Left boundary
```
I believe I can apply the Dirichlet boundary condition $\vec{J} \cdot \vec{n} = 0$ because $J$ is in HDiv space ($J$ is $\vec{u}$ in ex5) using the following
```
BilinearForm *aBilForm(new BilinearForm(R_space));
   aBilForm->AddDomainIntegrator(new VectorFEMassIntegrator(one));
   aBilForm->Assemble();
   // Dirichlet BCs.
   aBilForm->EliminateEssentialBC(dbc_lr, x.GetBlock(0), rhs.GetBlock(0));
   aBilForm->Finalize();
```
where `dbc_lr` is defined as for `dbc_tb` but for the left and right boundaries. I also believe I can apply non-zero conditions using [#77](https://github.com/mfem/mfem/issues/80). 

My issue, however, is that because $\phi$ is in L2 space, and as the [documentation](https://mfem.org/fem_bc/) says that I can't apply a Dirichlet condition to an L2 field, I am a bit stuck.  At the bottom of the same page, under Discontinuous Galerkin Formulations, it says "since DG basis functions have no degrees of freedom associated with the boundary, Dirichlet boundary conditions must be handled differently".  I was wondering whether you may be able to help in the application of a Dirichlet boundary condition for a field in L2 space.

**Comment by pazner** [comment]
With L2/DG spaces, you can definitely apply Dirichlet boundary conditions, but these are not enforced using _essential_ BCs; instead, appropriate terms are added to the linear/bilinear forms, and the BCs are enforced weakly.

For Darcy problems, this is done by adding the correct term to the RHS, see for example the H(div) Darcy miniapp:

https://github.com/mfem/mfem/blob/e50e54e09032301613a8ca46f9168ae2793e3733/miniapps/hdiv-linear-solver/darcy.cpp#L113-L138

For DG discretizations of the Laplacian (i.e. not in mixed form), then the approach is similar; you can look at ex14 for an example.

**Comment by mdavids-cfs** [comment]
@danielwardstfc 
Seems like we might be dealing with a similar problem at the moment, see https://github.com/mfem/mfem/issues/4475. Does it makes sense though to set both non-zero boundary conditions for $\vec{J} \cdot \vec{n} = 0$ and $\phi$ (or where you referring to different boundaries here?)
Did you figure out to solve this?

**Comment by danielwardstfc** [comment]
> @danielwardstfc Seems like we might be dealing with a similar problem at the moment, see #4475. Does it makes sense though to set both non-zero boundary conditions for J → ⋅ n →= 0 and ϕ (or where you referring to different boundaries here?) Did you figure out to solve this?

Hi @mdavids-cfs yes I agree looks similar.  I am setting  $\vec{J} \cdot \vec{n} = 0$ with a natural condition for phi on the left and right boundaries (an insulating condition) and $\phi = 0$ with a natural condition for J on the top and bottom boundaries (a conducting condition) to replicate a Hunt case as I build towards a liquid metal MHD solver.  In my other comment I detail my solution to the boundary condition problem

**Comment by danielwardstfc** [comment]
> With L2/DG spaces, you can definitely apply Dirichlet boundary conditions, but these are not enforced using _essential_ BCs; instead, appropriate terms are added to the linear/bilinear forms, and the BCs are enforced weakly.
> 
> For Darcy problems, this is done by adding the correct term to the RHS, see for example the H(div) Darcy miniapp:
> 
> https://github.com/mfem/mfem/blob/e50e54e09032301613a8ca46f9168ae2793e3733/miniapps/hdiv-linear-solver/darcy.cpp#L113-L138
> 
> For DG discretizations of the Laplacian (i.e. not in mixed form), then the approach is similar; you can look at ex14 for an example.

Thanks for your reply.  Yes, I think I've now solved the problem by adding the `AddBoundaryIntegrator` to the RHS as below

```   
   Array<int> bdr_marker_tb(mesh->bdr_attributes.Max());
   bdr_marker_tb = 0;
   bdr_marker_tb[0] = 1;   // Top boundary
   bdr_marker_tb[1] = 0;   // Right boundary
   bdr_marker_tb[2] = 1;   // Bottom boundary
   bdr_marker_tb[3] = 0;   // Left boundary

   LinearForm *fform(new LinearForm);
   fform->Update(R_space, rhs.GetBlock(0), 0);
   fform->AddDomainIntegrator(new VectorFEDomainLFIntegrator(fcoeff));
   // Dirichlet BC for phi.
   fform->AddBoundaryIntegrator(new VectorFEBoundaryFluxLFIntegrator(phi_dbc_coeff), bdr_marker_tb);
   fform->Assemble();
   fform->SyncAliasMemory(rhs);
```

where `phi_dbc_coeff` is defined

```
FunctionCoefficient phi_dbc_coeff(phi_dbc);
```

and `phi_dbc` is defined

```
real_t phi_dbc(const Vector & x)
{
   return 0.0;
}
```
for a zero Dirichlet boundary condition.
