### ISSUE TITLE
Convert an RT space GridFunction to an ND space GridFunction

### ISSUE THREAD

**Issue by denislachapelle** [mfem/mfem#4482]
I wrote the following code to convert an rt space gridfunction to an nd space gridfunction; but it do not work fine.

   FiniteElementCollection *eFieldNDFec = (FiniteElementCollection *)new ND_FECollection(eFieldOrder, meshDim);
   FiniteElementSpace eFieldNDFESpace(&mesh, eFieldNDFec);
   GridFunction eFieldNDGridFunction(&eFieldNDFESpace);
   eFieldNDGridFunction.ProjectGridFunction(eFieldGridFunction);

The result I get do not make sense.

Here is the RT space gridfunction view with glvis, the range of E-field of four make sense according to what is expected.
![image](https://github.com/user-attachments/assets/7cba5bca-d3bf-42c3-a953-2d71f073c498)

Here is the converted to ND Gridfunction view with glvis:
![image](https://github.com/user-attachments/assets/1f9d7ece-bcb9-43f3-bec2-1ead3807d830)

Note the range is not the same... If I use the log scale of glvis, using "L" I got this:
![image](https://github.com/user-attachments/assets/0fcead19-ffac-4c7b-bc6e-870f57fc2986)
and a cut of the inside which look like what is expected.
![image](https://github.com/user-attachments/assets/9b9951e9-97b2-4c46-accc-9129a9f444fb)

Is it the right way?

They use the same mesh and the same order.
eFieldGridFunction is the rt space gridfunction.

Thank you for your help.
Denis

**Comment by tzanio** [comment]
Hi @denislachapelle,

The two spaces (RT and ND) are not nested, so functions in one of them can not be generally represented in the other. For example any piecewise-polynomial vector field with continuous normal but discontinuous tangential components is representable in some RT space, but not in any ND space.

Are you sure this is what you need to do?

The natural mapping between the two spaces is the curl operator (discrete curl matrix) that maps ND functions into a subspace of RT.

Hope this helps,
Tzanio

**Comment by denislachapelle** [comment]
My goal is to compute the AC current density in a pair of wires, one is square and the other is round. Is start by computing the DC current density in the wires by computing the voltage potential and then the gradient to get the E-field and then compute the current density multiplying by the conductivity.

Then I want (did not work yet) to compute the magnetic vector potential created by the current density, but this time using AC current with the above current density and using time harmonic magnetic vector potential equation, K0 * curl(curl(A)) + K1 A = J.

Then with the magnetic vector potential I will compute the induced reverse voltage and current.

My problem is now resolved, after your comment I start digging more looking at the integrators web page and saw that the MixedVectorGradientIntegrator work on ND space, so I have succeed in computing the DC current density in ND space.

Thank you very much,
Denis Lachapelle

If you want you can have a look at the code: https://github.com/denislachapelle/mfemelectrostatic/blob/master/proximity3d.cpp
