### ISSUE TITLE
Writing / Reading parallel non-conforming meshes

### ISSUE THREAD

**Issue by junkudo** [mfem/mfem#449]
Hey,
I'm trying to write out parallel non-conforming meshes and later read them back in.  I realize after looking at the code that this isn't a supported feature:
```
void ParMesh::ParPrint(ostream &out) const
{
   if (NURBSext || pncmesh)
   {
      // TODO: AMR meshes, NURBS meshes.
      Print(out);
      return;
   }
   ...
}
```

Is there anyway to accomplish this or do I need to store the history of the final adapted mesh to re-create it when I "read" it back in?  
Thanks!
Jun

**Comment by jakubcerveny** [comment]
Hi Jun, 
You are right, this is not implemented yet. It shouldn't be too complex but we need a new file format that would be able to store the member `NCMesh::Element::rank`. We just didn't get to this yet, sorry. 
Jakub

**Comment by tzanio** [comment]
Hi Jun,

We are planning to implement this in the future. To help us prioritize -- how critical is this feature for your application?

Tzanio

**Comment by junkudo** [comment]
Hey,
It would be a feature of convenience for us.  The way MFEM is implemented now, we are forced to store the entire provenance of the current adapted mesh (original mesh + elements adapted) and re-creating it step-by-step when we restart.  It would simplify the workflow if we could simply store the previous adapted mesh and restart from it.
Jun

**Comment by junkudo** [comment]
Hey @tzanio,
Is this something being looked at all in the near future?
CC @Dan2997925

**Comment by tzanio** [comment]
@jakubcerveny, is this on your plan?

**Comment by tzanio** [comment]
Lets add it if you don't mind, I think it will be a useful feature.
