### ISSUE TITLE
How to convert mfem:BlockVector to HypreParVector ?

### ISSUE THREAD

**Issue by AIBSCT80** [mfem/mfem#4490]
Hi, 

I have  a saddle point system:
```text
|  A  B^T | | u | = | f |
|  B  C   | | p |   | g |
```

where,  

```
blocks(0,0) = A.As<HypreParMatrix>();
blocks(1,0) = B.As<HypreParMatrix>();
blocks(0,1) = B.As<HypreParMatrix>()->Transpose();
blocks(1,1) = C.As<HypreParMatrix>();
```

Now I want to set a HypreParVector which equals f = trueRhs.GetBlock(0). 

For this, I use the following: 

```
HypreParVector trueRhs_f(blocks(0,0)->GetComm(), blocks(0,0)->GetGlobalNumRows(), 
                               trueRhs.GetBlock(0).GetData(), blocks(0,0)->GetRowStarts());
```
where 

```
 block_trueOffsets[0] = 0;
 block_trueOffsets[1] = ufespace->TrueVSize();
 block_trueOffsets[2] = pfespace->TrueVSize();
 block_trueOffsets.PartialSum();

MemoryType mt = device.GetMemoryType();
BlockVector  trueRhs(block_trueOffsets, mt);

```

Is this the correct way to assign a mfem vector to hypreparvector?  I got memory issues, unfortunately. 

Many thanks.

**Comment by psocratis** [comment]
@AIBSCT80 can you provide a minimal example reproducing the issue?

**Comment by AIBSCT80** [comment]
@psocratis Thanks.  The problem is now connected with this issue:  [Problem with HypreBoomerAMG #4497](https://github.com/mfem/mfem/issues/4497)

My mini-example is attached below:



`
//                       MFEM Example 5 - Parallel Version
//
// Compile with: make ex5p
//
// Sample runs:  mpirun -np 4 ex5p -m ../data/square-disc.mesh
//               mpirun -np 4 ex5p -m ../data/star.mesh
//               mpirun -np 4 ex5p -m ../data/star.mesh -r 2 -pa
//               mpirun -np 4 ex5p -m ../data/beam-tet.mesh
//               mpirun -np 4 ex5p -m ../data/beam-hex.mesh
//               mpirun -np 4 ex5p -m ../data/beam-hex.mesh -pa
//               mpirun -np 4 ex5p -m ../data/escher.mesh
//               mpirun -np 4 ex5p -m ../data/fichera.mesh
//
// Device sample runs:
//               mpirun -np 4 ex5p -m ../data/star.mesh -r 2 -pa -d cuda
//               mpirun -np 4 ex5p -m ../data/star.mesh -r 2 -pa -d raja-cuda
//               mpirun -np 4 ex5p -m ../data/star.mesh -r 2 -pa -d raja-omp
//               mpirun -np 4 ex5p -m ../data/beam-hex.mesh -pa -d cuda
//
// Description:  This example code solves a simple 2D/3D mixed Darcy problem
//               corresponding to the saddle point system
//
//                                 u - Lapla p = f
//                                 -Lapla u -1.0/rho p  = 0
//
//               with natural boundary condition -p = <given pressure>.
//               Here, we use a given exact solution (u,p) and compute the
//               corresponding r.h.s. (f,g).  We discretize with Raviart-Thomas
//               finite elements (velocity u) and piecewise discontinuous
//               polynomials (pressure p).
//
//               The example demonstrates the use of the BlockOperator class, as
//               well as the collective saving of several grid functions in
//               VisIt (visit.llnl.gov) and ParaView (paraview.org) formats.
//               Optional saving with ADIOS2 (adios2.readthedocs.io) streams is
//               also illustrated.
//
//               We recommend viewing examples 1-4 before viewing this example.

#include "mfem.hpp"
#include <fstream>
#include <iostream>

using namespace std;
using namespace mfem;

// Define the analytical solution and forcing terms / boundary conditions
double uFun_ex(const Vector & x);
double pFun_ex(const Vector & x);
double fFun(const Vector & x);
double gFun(const Vector & x);
double f_natural(const Vector & x);

//mpirun -np 1 valgrind --leak-check=yes ./ex5p >> out

class MyCoefficient : public Coefficient
{
private:
   int     initlevel{0}; 
   ParMesh *pmesh;
   std::vector<double> h{0};
public:
   void setParMesh(ParMesh* mesh){pmesh=mesh;}
   MyCoefficient(const int& lev){ initlevel=lev; }
   void addRefLevl(){initlevel++;}
   virtual double Eval(ElementTransformation &T, const IntegrationPoint &ip);
   virtual ~MyCoefficient() { ; }
};

double MyCoefficient :: Eval(ElementTransformation &T, const IntegrationPoint &ip)
{
  
    return 0.00024414;
}



class FakeErrorEstimator : public ErrorEstimator
{
protected:
   ParMesh *parmesh; /// not owned
   Vector error_estimates;
   ParGridFunction *u;

   Vector local_errors;
   double globl2err;

public:
   FakeErrorEstimator(){;}
   FakeErrorEstimator(ParMesh *parmesh_) : parmesh(parmesh_) { }
   void setMesh(ParMesh *parmesh_){parmesh=parmesh_;}
   void setGridFunction(ParGridFunction* gridfunc){u=gridfunc;}

   /// Get a Vector with all element errors.
   ///*
   const Vector &GetLocalErrors() override
   {
      error_estimates.SetSize(parmesh->GetNE());
      error_estimates = 1.0;
      return error_estimates;
   }
   //*/
   
   

   /// Force recomputation of the estimates on the next call to GetLocalErrors.
   void Reset() override { }
};

int main(int argc, char *argv[])
{
   StopWatch chrono;
   // 1. Initialize MPI and HYPRE.
   Mpi::Init(argc, argv);
   int num_procs = Mpi::WorldSize();
   int myid = Mpi::WorldRank();
   Hypre::Init();
   bool verbose = (myid == 0);

   // 2. Parse command-line options.
   //const char *mesh_file = "../data/star.mesh";
   const char *mesh_file = "../data/cube-tet.mesh";
   int ref_levels = -1;
   int order = 1;
   bool pa = false;
   const char *device_config = "cpu";
   bool nc_simplices = true;
   //bool nc_simplices = false;
   int reorder_mesh = 0;
   HYPRE_BigInt max_dofs = 1215752192; // long int//100000000000;
   bool smooth_rt = true;
   bool restart = false;
   bool visualization = 1;
   bool adios2 = false;

   OptionsParser args(argc, argv);
   args.AddOption(&mesh_file, "-m", "--mesh",
                  "Mesh file to use.");
   args.AddOption(&order, "-o", "--order",
                  "Finite element order (polynomial degree).");
   args.AddOption(&pa, "-pa", "--partial-assembly", "-no-pa",
                  "--no-partial-assembly", "Enable Partial Assembly.");
   args.AddOption(&device_config, "-d", "--device",
                  "Device configuration string, see Device::Configure().");
   args.AddOption(&nc_simplices, "-ns", "--nonconforming-simplices",
                  "-cs", "--conforming-simplices",
                  "For simplicial meshes, enable/disable nonconforming"
                  " refinement");
   args.AddOption(&max_dofs, "-md", "--max-dofs",
                  "Stop after reaching this many degrees of freedom.");
   args.AddOption(&smooth_rt, "-rt", "--smooth-rt", "-h1", "--smooth-h1",
                  "Represent the smooth flux in RT or vector H1 space.");
   args.AddOption(&restart, "-res", "--restart", "-no-res", "--no-restart",
                  "Restart computation from the last checkpoint.");
   args.AddOption(&visualization, "-vis", "--visualization", "-no-vis",
                  "--no-visualization",
                  "Enable or disable GLVis visualization.");
   
   args.Parse();
   if (!args.Good())
   {
      if (verbose)
      {
         args.PrintUsage(cout);
      }
      return 1;
   }
   if (verbose)
   {
      args.PrintOptions(cout);
   }

   // 3. Enable hardware devices such as GPUs, and programming models such as
   //    CUDA, OCCA, RAJA and OpenMP based on command line options.
   Device device(device_config);
   if (myid == 0) { device.Print(); }

   // 4. Read the (serial) mesh from the given mesh file on all processors.  We
   //    can handle triangular, quadrilateral, tetrahedral, hexahedral, surface
   //    and volume meshes with the same code.
   ParMesh *pmesh;

   double h;
   double N0;

   if (!restart)
   {
      // 4. Read the (serial) mesh from the given mesh file on all processors.
      //    We can handle triangular, quadrilateral, tetrahedral, hexahedral,
      //    surface and volume meshes with the same code.
      Mesh mesh(mesh_file, 1, 1);

      if (ref_levels == -1)
      {
         //ref_levels = (int)floor(log(1000./mesh.GetNE())/log(2.)/mesh.Dimension());
         ref_levels = (int)floor(log(4000./mesh.GetNE())/log(2.)/mesh.Dimension());
         //ref_levels = (int)floor(log(10000./mesh.GetNE())/log(2.)/mesh.Dimension());
         //ref_levels = (int)floor(log(100000./mesh.GetNE())/log(2.)/mesh.Dimension());
         //ref_levels = (int)floor(log(1000000./mesh.GetNE())/log(2.)/mesh.Dimension());
         //ref_levels = (int)floor(log(10000000./mesh.GetNE())/log(2.)/mesh.Dimension());
      }

      for (int l = 0; l < ref_levels; l++)
      {
         mesh.UniformRefinement();
         /*
         h=pow(mesh.GetNV(), 1.0/mesh.Dimension());
         h=1.0/(h-1);
         */
      }

      // 5. A NURBS mesh cannot be refined locally so we refine it uniformly
      //    and project it to a standard curvilinear mesh of order 2.
      /*
      if (mesh.NURBSext)
      {
         mesh.UniformRefinement();
         mesh.SetCurvature(2);
      }
      */

      // 6. MFEM supports dynamic partitioning (load balancing) of parallel non-
      //    conforming meshes based on space-filling curve (SFC) partitioning.
      //    SFC partitioning is extremely fast and scales to hundreds of
      //    thousands of processors, but requires the coarse mesh to be ordered,
      //    ideally as a sequence of face-neighbors. The mesh may already be
      //    ordered (like star-hilbert.mesh) or we can order it here. Ordering
      //    type 1 is a fast spatial sort of the mesh, type 2 is a high quality
      //    optimization algorithm suitable for ordering general unstructured
      //    meshes.
      if (reorder_mesh)
      {
         Array<int> ordering;
         switch (reorder_mesh)
         {
            case 1: mesh.GetHilbertElementOrdering(ordering); break;
            case 2: mesh.GetGeckoElementOrdering(ordering); break;
            default: MFEM_ABORT("Unknown mesh reodering type " << reorder_mesh);
         }
         mesh.ReorderElements(ordering);

      }

      // 7. Make sure the mesh is in the non-conforming mode to enable local
      //    refinement of quadrilaterals/hexahedra, and the above partitioning
      //    algorithm. Simplices can be refined either in conforming or in non-
      //    conforming mode. The conforming mode however does not support
      //    dynamic partitioning.
      mesh.EnsureNCMesh(nc_simplices);


      N0=mesh.GetNV();

      // 8. Define a parallel mesh by partitioning the serial mesh.
      //    Once the parallel mesh is defined, the serial mesh can be deleted.
      pmesh = new ParMesh(MPI_COMM_WORLD, mesh);
   }
   else
   {
      // 9. We can also restart the computation by loading the mesh from a
      //    previously saved check-point.
      string fname(MakeParFilename("ex6p-checkpoint.", myid));
      ifstream ifs(fname);
      MFEM_VERIFY(ifs.good(), "Checkpoint file " << fname << " not found.");
      pmesh = new ParMesh(MPI_COMM_WORLD, ifs);
   }

   int dim = pmesh->Dimension();
   int sdim = pmesh->SpaceDimension();

   if(verbose)
   {
      cout<<"dim: "<<dim<<" sdim: "<<sdim<<endl;
   }

   MFEM_VERIFY(pmesh->bdr_attributes.Size() > 0,
               "Boundary attributes required in the mesh.");
   Array<int> ess_bdr(pmesh->bdr_attributes.Max());
   ess_bdr = 1;   

   FiniteElementCollection *fec;

   bool delete_fec;
   if (order > 0)
   {
      fec = new H1_FECollection(order, dim);
      delete_fec = true;
   }
   else if (pmesh->GetNodes())
   {
      fec = pmesh->GetNodes()->OwnFEC();
      delete_fec = false;
      if (myid == 0)
      {
         cout << "Using isoparametric FEs: " << fec->Name() << endl;
      }
   }
   else
   {
      fec = new H1_FECollection(order = 1, dim);
      delete_fec = true;
   }

   ParFiniteElementSpace *ufespace = new ParFiniteElementSpace(pmesh, fec);
   ParFiniteElementSpace *pfespace = new ParFiniteElementSpace(pmesh, fec);
 
   //MyCoefficient mycoeff(0);
   MyCoefficient mycoeff(2);

   FunctionCoefficient fcoeff(fFun);
   FunctionCoefficient gcoeff(gFun);

   FunctionCoefficient ucoeff(uFun_ex);  //  
   FunctionCoefficient pcoeff(pFun_ex);  // 

   MemoryType mt = device.GetMemoryType();
  

   ParLinearForm *fform(new ParLinearForm);
   fform->AddDomainIntegrator(new DomainLFIntegrator(fcoeff));
   ParLinearForm *gform(new ParLinearForm);
   gform->AddDomainIntegrator(new DomainLFIntegrator(gcoeff));


   ParBilinearForm *mVarf(new ParBilinearForm(ufespace));  
   ParMixedBilinearForm *bVarf(new ParMixedBilinearForm(ufespace, pfespace));
   ParBilinearForm *pVarf(new ParBilinearForm(pfespace)); 

   ConstantCoefficient one(1.0);
   ConstantCoefficient zero(0.0);
   ConstantCoefficient half(1.0e-0);

   //zero matrix with only nonzero entries at corresponding Dirichlet positions
   mVarf->AddDomainIntegrator(new MassIntegrator(one));
   mVarf->AddDomainIntegrator(new DiffusionIntegrator(mycoeff));
   
   bVarf->AddDomainIntegrator(new DiffusionIntegrator(half));

   pVarf->AddDomainIntegrator(new MassIntegrator(zero));

   
   ParGridFunction *u(new ParGridFunction);
   ParGridFunction *p(new ParGridFunction);
   
   FakeErrorEstimator estimator;
   estimator.setMesh(pmesh);
   estimator.setGridFunction(p);

   ThresholdRefiner refiner(estimator);
   refiner.SetTotalErrorFraction(0.0);
   //refiner.SetTotalErrorFraction(0.5);

   // for nested iterations
   //int total_ref_levels=2;
   //int total_ref_levels=3;
   int total_ref_levels=4;
   //int total_ref_levels=30;
   //int total_ref_levels=5;
   int ref_lev=0;
   double N1;
 
   // error 
   int order_quad = max(2, 2*order+1);
   const IntegrationRule *irs[Geometry::NumGeom];
   for (int i=0; i < Geometry::NumGeom; ++i)
   {
      irs[i] = &(IntRules.Get(i, order_quad));
   }
   
   Array2D<HypreParMatrix*> blocks(2,2);

   Array<int> u_ess_tdof_list;
   Array<int> p_ess_tdof_list;

   Array<int> block_offsets(3); // number of variables + 1
   Array<int> block_trueOffsets(3); // number of variables + 1
   
   OperatorHandle A, B, C;
   
   HYPRE_BigInt dimU; 
   HYPRE_BigInt dimP;

   //mpirun -np 4 valgrind --leak-check=yes ./ex5p &> ou
   Vector local_errors  ;
   while(ref_lev<total_ref_levels)   
   {
      
      dimU = ufespace->GlobalTrueVSize();
      dimP = pfespace->GlobalTrueVSize();

      if (verbose)
      {
         std::cout << "***********************************************************\n";
         cout<<"Nested Iterations on Level: "<< ref_lev<<endl;
         std::cout << "dim(U) = " << dimU << "\n";
         std::cout << "dim(P) = " << dimP << "\n";
         std::cout << "dim(U+P) = " << dimU + dimP << "\n";
         std::cout << "***********************************************************\n";
      }
      
      block_offsets[0] = 0;
      block_offsets[1] = ufespace->GetVSize();
      block_offsets[2] = pfespace->GetVSize();
      block_offsets.PartialSum();

     
      block_trueOffsets[0] = 0;
      block_trueOffsets[1] = ufespace->TrueVSize();
      block_trueOffsets[2] = pfespace->TrueVSize();
      block_trueOffsets.PartialSum();

      BlockVector x(block_offsets, mt), rhs(block_offsets, mt);
      BlockVector trueX(block_trueOffsets, mt), trueRhs(block_trueOffsets, mt);

      //initialization
      {
         x=0;
         rhs=0;
         trueX=0;
         trueRhs=0;
      }

      fform->Update(ufespace, rhs.GetBlock(0), 0);   
      gform->Update(pfespace, rhs.GetBlock(1), 0);   

      fform->Assemble();
      fform->SyncAliasMemory(rhs);
      fform->ParallelAssemble(trueRhs.GetBlock(0));
      trueRhs.GetBlock(0).SyncAliasMemory(trueRhs);

      gform->Assemble();
      gform->SyncAliasMemory(rhs);
      gform->ParallelAssemble(trueRhs.GetBlock(1));
      trueRhs.GetBlock(1).SyncAliasMemory(trueRhs);


      // assem stiffness matrix
      mVarf->Assemble();  //A
      mVarf->Finalize();

      bVarf->Assemble();  //B
      bVarf->Finalize();

      pVarf->Assemble();  //C
      pVarf->Finalize();

      //elimiting essential boundary condition
      //ufespace->GetBoundaryTrueDofs(u_ess_tdof_list);
      pfespace->GetBoundaryTrueDofs(p_ess_tdof_list);  
      
      // Create Matrix and Vector
      mVarf->FormSystemMatrix(u_ess_tdof_list, A);
      bVarf->FormRectangularSystemMatrix(u_ess_tdof_list, p_ess_tdof_list, B);
      pVarf->FormSystemMatrix(p_ess_tdof_list, C);
   
   
      blocks(0,0) = A.As<HypreParMatrix>();
      blocks(1,0) = B.As<HypreParMatrix>();
      blocks(0,1) = B.As<HypreParMatrix>()->Transpose();
      blocks(1,1) = C.As<HypreParMatrix>();
      OperatorHandle D(HypreParMatrixFromBlocks(blocks));
      
      /*
      HypreParVector trueRhs_g(blocks(1,1)->GetComm(), blocks(1,1)->GetGlobalNumRows(), 
                               trueRhs.GetBlock(1).GetData(), blocks(1,1)->GetRowtarts()); //??
      */

      ///*
      HypreParVector trueRhs_g(blocks(0,0)->GetComm(), blocks(0,0)->GetGlobalNumRows(), 
                               trueRhs.GetBlock(0).GetData(), blocks(0,0)->GetRowStarts());
      //*/
    

      ///*
      HypreParVector r1=trueRhs_g, r2=trueRhs_g;
      r1=0;
      r2=0;
      HypreBoomerAMG A_inv(*blocks(0,0));
      A_inv.SetTol(1e-7);
      A_inv.Mult(trueRhs_g, r1);
      blocks(1,0)->Mult(r1, r2);
      trueRhs_g=r2;
      //*/

      
      N1=pfespace->GlobalTrueVSize();
      
      if(verbose)
      {
         cout<<"N0: "<<N0<<" N1: "<<N1 <<endl;
      }
      
      
      chrono.Clear();
      chrono.Start();

      

      if(verbose)
      {
         //std::cout << "Schur_PCG solver took " << chrono.RealTime() << "s. \n";
         std::cout << "GMRES solver took " << chrono.RealTime() << "s. \n";
      }

      chrono.Stop();

      if (device.IsEnabled()) { trueX.HostRead(); }
      //trueX.GetBlock(1)=truex_g; trueX.GetBlock(0)=truex_g;
      //a.RecoverFEMSolution(X, b, x);
      //pVarf->RecoverFEMSolution(trueX.GetBlock(1), );

      ///*
      u->MakeRef(ufespace, x.GetBlock(0), 0);
      p->MakeRef(pfespace, x.GetBlock(1), 0);
      //*/

      /*
      u->MakeRef(ufespace, trueX.GetBlock(0), 0);
      p->MakeRef(pfespace, trueX.GetBlock(1), 0);
      */
      u->Distribute(&(trueX.GetBlock(0)));
      p->Distribute(&(trueX.GetBlock(1)));

      double err_u  = u->ComputeL2Error(ucoeff, irs);
      double norm_u = ComputeGlobalLpNorm(2, ucoeff, *pmesh, irs);
      double err_p  = p->ComputeL2Error(pcoeff, irs);
      double norm_p = ComputeGlobalLpNorm(2, pcoeff, *pmesh, irs);

      /*
      estimator.setGlobL2Error(err_p/pmesh->GetNE());
      local_errors.SetSize(pmesh->GetNE());
      p->ComputeElementL2Errors(pcoeff, local_errors, irs);
      estimator.setLocL2Error(local_errors);
      */

      if (verbose)
      {
         std::cout << "|| p_h - p_ex ||  = " << err_u  << "\n";
         std::cout << "|| u_h - u_ex ||  = " << err_p  << "\n";
      }

      ///*
      ParaViewDataCollection paraview_dc("Example5P", pmesh);
      paraview_dc.SetPrefixPath("ParaView");
      paraview_dc.SetLevelsOfDetail(order);
      paraview_dc.SetDataFormat(VTKFormat::BINARY);
      paraview_dc.SetHighOrderOutput(true);
      paraview_dc.SetCycle(0);
      paraview_dc.SetTime(0.0);
      paraview_dc.RegisterField("state",u);
      paraview_dc.RegisterField("adjoint",p);
      paraview_dc.Save();
      //*/

      if(dimU >= max_dofs)
      {
         if(verbose)
         {
            cout << "Reached the maximum number of dofs. Stop." << endl;  
         }
         break;
      }

      if(verbose)
      {
         cout <<"#Marked Elements: "<< refiner.GetNumMarkedElements() << endl;
         cout <<"threshold: "<<refiner.GetThreshold()<<endl;
      }

      refiner.Apply(*pmesh);
      //estimator.setMesh(pmesh);
      //estimator.setGridFunction(p);

      ///*
      if (refiner.Stop())
      {
         if (verbose)
         {
            cout << "Stopping criterion satisfied. Stop." << endl;
         }
         break;
      }
      //*/

      ufespace->Update();
      pfespace->Update();
      u->Update();
      p->Update();

      ///*
      if (pmesh->Nonconforming())
      {
         pmesh->Rebalance();

         // Update the space and the GridFunction. This time the update matrix
         // redistributes the GridFunction among the processors.
         ufespace->Update();
         pfespace->Update();
         u->Update();
         p->Update();
      }
      //*/

      mycoeff.addRefLevl();
      
      mVarf->Update();
      bVarf->Update();
      pVarf->Update();

      fform->Update();
      gform->Update();

      ref_lev++;
   }
   
   // 20. Free the used memory.
   delete fform;
   delete gform;
   delete u;
   delete p;
   
   delete mVarf;
   delete bVarf;
   delete pVarf;
   delete ufespace;
   delete pfespace;
   delete fec;

   delete pmesh;


   return 0;
}



double uFun_ex(const Vector & x)
{
   
   double xi(x(0));
   double yi(x(1));
   double zi(0);

   if(x.Size() == 3)
   {
      zi = x(2);
   }

   return sin(M_PI*xi)*sin(M_PI*yi) ;
  //*/

}

// Change if needed
double pFun_ex(const Vector & x)
{
  return 0.0;

}

double fFun(const Vector & x)
{
   
   double xi(x(0));
   double yi(x(1));
   double zi(0);

   if(x.Size() == 3)
   {
      zi = x(2);
   }

   return sin(M_PI*xi)*sin(M_PI*yi) ;
   
}

double gFun(const Vector & x)
{
   
  return 0.0;

}


double f_natural(const Vector & x)
{
   return (-pFun_ex(x));
}



`

running: mpirun -np 4  ./ex5p, I got the following error:

`
Verification failed: (!err_flag) is false:
 --> Error during solve! Error code: 256
 ... in function: virtual void mfem::HypreSolver::Mult(const mfem::HypreParVector&, mfem::HypreParVector&) const
 ... in file: linalg/hypre.cpp:3660
`

This is connected to the BoomerAMG calling:

`
HypreBoomerAMG A_inv(*blocks(0,0));
A_inv.SetTol(1e-7);
A_inv.Mult(trueRhs_g, r1);

`

for which I thought I did not assign the right hand side 
correctly 

`
HypreParVector trueRhs_g(blocks(0,0)->GetComm(), blocks(0,0)->GetGlobalNumRows(), 
                               trueRhs.GetBlock(0).GetData(), blocks(0,0)->GetRowStarts());
`

But I am not sure about this. 

Thank you in advance.

**Comment by psocratis** [comment]
Hi @AIBSCT80, the sample code you provided does not compile. There are many syntax errors.

In any case, the error you are getting is unrelated to the `HypreParVector`. It's caused by the fact that you are doing a single AMG cycle and at the same time you are setting a small desired exit tolerance. The complaint from `Hypre` is that AMG did not converge to the required tolerance which is no surprise. You can either ask AMG to perform more iterations (more cycles) by setting `A_inv.SetMaxIter(...);` or by removing `A_inv.SetTol(1e-7);`.

I hope this helps.

Best,

Socratis

**Comment by AIBSCT80** [comment]
Thank you @AIBSCT80 . After set more iterations, it starts to run without errors. But it does not converge to the required tolerance.  Is this a general issue in Hypre AMG?  What can I do if I want to the AMG solver reach a desired tolerance?  Many thanks.

**Comment by tzanio** [comment]
As @psocratis indicated, this is a solver issue. AMG is an iterative method, so you should either take more iterations or use a looser tolerance.
