### ISSUE TITLE
Some quesitons about the ImplicitSolve() from ex9p

### ISSUE THREAD

**Issue by Wayne901** [mfem/mfem#4491]
Hi there,
The `DG_Solver` in ex9p, as I understood, solve the time-dependent PDE with backward Euler, `(M-dt*K) du_dt = K*u + b`.
However, I can not see the form of `M-dt*K` in `DG_Solver` class's `SetTimeStep()`.
We get a matrix `A=-dt*K` and a diagnoal matrix `A_diag=M_diag-dt*K_diag`, where `A_diag` was not used latter. 
Is the diagonal of `A` linked to `A_diag` through `A->GetDiag(A_diag)`? Why there's no form of `M-dt*K`? I believe mass lumping was not applied in this example so `M` shouldn't be a mere diagonal ...

**Comment by thartland** [comment]
The diagonal of `A` is linked to `A_diag` through `A->GetDiag(A_diag)`. See the comment [hypre.hpp](https://github.com/mfem/mfem/blob/master/linalg/hypre.hpp#L633-L634), which shows that `A_diag` is not a deep copy of the local block diagonal data of `A`. So, `A = Add(-dt, K, 0.0, K)` initially sets `A = -dt*K`, but then by changing `A_diag` [here](https://github.com/mfem/mfem/blob/master/examples/ex9p.cpp#L182) you are also changing `A`. This can be verified by calling `A->Print("filename");` before and after altering `A_diag` with different filenames and you will see that the matrix entries of `A` differ.

You are right that `M` is not a mere diagonal, it seems to comes from [this](https://github.com/mfem/mfem/blob/master/examples/ex9p.cpp#L427) MassIntegrator. It seems to me that a BilinearForm whose assembled matrix is `M - dt*K` is another approach. I am not sure why it wasn't used.

**Comment by Wayne901** [comment]
Thank you @thartland for your explanation. It's very clear.
I'll leave the issue opened so maybe someone could explain why only the diagonal of `M` is used.

**Comment by cjvogl** [comment]
My understanding is that `HypreParMatrix::GetDiag(SparseMatrix &)` sets a reference to the local diagonal **block** of the `HypreParMatrix` (as opposed to strictly the diagonal entries).  Because a DG finite element space is used, the mass matrix `M` consists only of diagonal blocks, so `M_diag` contains the entire `M` matrix (or at least the part that is local to the given MPI rank).

**Comment by Wayne901** [comment]
So when `diag` is a SparseMatrix, `HypreParMatrix::GetDiag(diag)` returns a block diagonal. Thank you @cjvogl.
