### ISSUE TITLE
Accelerate the assemble of ParLinearform

### ISSUE THREAD

**Issue by Wayne901** [mfem/mfem#4492]
Hello my friends,

I try to implement mass lumping for the time-dependent wave equation, similar to ex23.
The ode_solver is ForwardEuler, and it seems the time consumption of solving mass matrix decreases more than 10x (from 23350ms to 1818ms), which is great. Here's the run time of
`Gauss-Legendre Integration`
LF assemble time = 3767.8939ms,
M_solver solve time = 23350.589ms,
Other time in Mult() = 1897.5179ms,
and `Gauss-Lobatto Integration (mass lumping)`
LF assemble time = 3415.9194ms,
M_solver solve time = 1818.6688ms,
Other time in Mult() = 1480.581ms.

The problem is, the incident wave is a gaussian impulse, so the RHS must be assembled in every time step. The runtime of linear solver is so low for mass lumping that the LinearForm's assemble time exceeds it. Is there a way to reduce the assemble time of ParLinearform? The `Mult()` of TimeDependentOperator is shown bellow:

```
void WaveFirstOrderOperator::Mult(const Vector &ep, Vector &dep_dt) const
{
    int sc = height/2;
    Vector e(ep.GetData() +  0, sc);
    Vector p(ep.GetData() + sc, sc);
    Vector de_dt(dep_dt.GetData() +  0, sc);
    Vector dp_dt(dep_dt.GetData() + sc, sc);

    { // f^{n}
        auto t1 = std::chrono::system_clock::now();
        F1Coef->SetTime(t);
        F2Coef->SetTime(t);
        F1->Assemble();
        F1->ParallelAssemble(f1_vec);
        F2->Assemble();
        F2->ParallelAssemble(f2_vec);
        f1_vec *= c_const*c_const;
        f2_vec *= c_const;
        auto t2 = std::chrono::system_clock::now();
        t_lf += std::chrono::duration_cast<std::chrono::nanoseconds>(t2-t1).count();
    }

    auto to1 = std::chrono::system_clock::now();
    de_dt = p;
    z = 0.;
    K_mat->AddMult(e, z);
    B_mat->AddMult(p, z);
    z.Neg();
    z.Add(1.0, f1_vec);
    z.Add(1.0, f2_vec);
    auto to2 = std::chrono::system_clock::now();
    t_other += std::chrono::duration_cast<std::chrono::nanoseconds>(to2-to1).count();

    auto tm1 = std::chrono::system_clock::now();
    M_solver->Mult(z, dp_dt);
    auto tm2 = std::chrono::system_clock::now();
    t_msolver += std::chrono::duration_cast<std::chrono::nanoseconds>(tm2-tm1).count();
    ;
}
```
![2d_scalar_wave](https://github.com/user-attachments/assets/4fad3b7d-bff8-4077-8ca0-a3ffe54d02ab)

**Comment by vladotomov** [comment]
One obvious thing is to combine F1 and F2 into one assembly, avoiding looping over every element / quad point and computing things like detJ twice. Then you can think about partial assembly and other optimizations.

**Comment by Wayne901** [comment]
Thank for your reply.
I have adapted the problem to a 3-D H(curl) version now. F1 and F2 involves boundary integrator `VectorFEBoundaryTangentLFIntegrator` and `VectorFEDomainLFIntegrator` respectively. I added them to one `ParLinearForm` and there's no acceleration.
I guess I can benefit from a customized LinearFormIntegrator that combines both F1 and F2?

**Comment by vladotomov** [comment]
Yes, I meant one integrator (one `Assemble...()` function) to avoid the overhead of iterating twice.

**Comment by pazner** [comment]
If you are either using GPUs or using high-order elements, linear form integrators can be sped up quite a bit by implementing "fast assembly" kernels. These aren't currently implemented for the cases you need (we have `VectorFEDomainLFIntegrator`, but for H(div) instead of H(curl), and don't have `VectorFEBoundaryTangentLFIntegrator` currently).
