### ISSUE TITLE
Does ex18/ex18p: DG Euler Equations support 3D case?

### ISSUE THREAD

**Issue by Terence-iscas** [mfem/mfem#4501]
Hello experts, I noticed in the header file `ex18.hpp` of Example 18 that the `EulerMesh` only supports one-dimensional and two-dimensional meshes among the four cases.

Additionally, the `Laghos` mini-app seems to support three-dimensional moving meshes.

Are there any examples of the **DG Euler equations** that support **three-dimensional non-moving meshes**? (For instance, the simplest unit cube with periodic boundaries.)

P.S. Software version: mfem-4.7.1, hypre-2.31.0, metis-5.1.0

**Comment by dohyun-cse** [comment]
Hi Tian,

`ex18` should work out of the box for 3D examples, but not included in the example problems.
I just made an example on branch `ex18-3D`, so please take a look
The only changes are `ex18.hpp`, adding 3D mesh and initial condition.

Best, Dohyun

**Comment by Tian0214** [comment]
Hi Dohyun,

I would like to appreciate your kind help, that's what I need!

Best Regards, Tian
