### ISSUE TITLE
Cuda-enabled Hypre singleton finalized after CUDA driver is shutting down

### ISSUE THREAD

**Issue by helloworld922** [mfem/mfem#4503]
The Hypre singleton is finalized after the main function returns. This can cause problems with CUDA enabled HYPRE where the order of cleanup can allow the CUDA driver to be cleaned up before HYPRE's internal CUDA objects are freed.

Minimal reproducible example (requires CUDA enabled for HYPRE 2.31.0+ and mfem, tested on Lassen):

```cpp
#include "mfem.hpp"

int main(int argc, char** argv) {
  mfem::Mpi::Init(argc, argv);

  mfem::Hypre::Init();
  
  const char *device_config = "cuda";
  mfem::Device device(device_config);
}
```

Error message:

> CUDA ERROR (code = 4, driver shutting down) at /g/g20/ho37/workspace/code/third-party/hypre/hypre/src/utilities/device_utils.c:148
> CUDA ERROR (code = 4, driver shutting down) at /g/g20/ho37/workspace/code/third-party/hypre/hypre/src/utilities/general.c:256

**Comment by tzanio** [comment]
Discussion continued in #4504
