### ISSUE TITLE
Updating bilinear form iteratively

### ISSUE THREAD

**Issue by MC3JMF** [mfem/mfem#451]
Hello,

I am programming an optimization algorithm for topology optimization of elastic materials. In this application, I need to update the lame coefficients at each iteration of the optimization loop. The Lame coefficients are defined using a PWConstCoefficient as follows

Vector lambda(mesh->attributes.Max());
   lambda = 1.0;
   lambda(0) = lambda(1)*50;
   PWConstCoefficient lambda_func(lambda);
   Vector mu(mesh->attributes.Max());
   mu = 1.0;
   mu(0) = mu(1)*50;
   PWConstCoefficient mu_func(mu);

After assembly the linear and bilinear form and solve the system of equations I update the vector lambda and assembly again

   lambda = 100.0;
   lambda(0) = lambda(1)*50;
   a->Update();
   a->Assemble();

However the result is the same. Is there something that I have missed ?

Thank you in advance !
Jesus

**Comment by jandrej** [comment]
Hi,

I assume `a` is a `BilinearForm` here. The `Update()` method is for updating the finite element space of the operator in case of AMR, it will _not_ reassign your coefficients. You need to rebuild your `BilinearForm` in your loop like
```c++
-> for each new values from optimization algirithm
  delete a;

  -> Update lambda and mu here

  a = new BilinearForm(&fespace);
  a->AddDomainIntegrator(new ElasticityIntegrator(lambda, mu));
  a->Assemble();
```

**Comment by MC3JMF** [comment]
Thanks, that solve the problem.

**Comment by v-dobrev** [comment]
We can also add a method to `PWConstCoefficient` that updates the constants. That way, there will be no need to rebuild the `BilinearForm`. Feel free to submit a PR for this, if you want.

**Comment by v-dobrev** [comment]
The `ElasticityIntegrator` has pointers to the `Coefficient` objects:
https://github.com/mfem/mfem/blob/a8b3b4400dbb5b1c982a72532c76244e71b0367c/fem/bilininteg.hpp#L2014-L2018
so, if they are updated, the integrator does not need to be updated.
