### ISSUE TITLE
Possibly missing dependency for STRUMPACK support (macOS)

### ISSUE THREAD

**Issue by TobiasDuswald** [mfem/mfem#4517]
I have been trying to get MFEM's integrated STRUMPACK solver to run for a few days and it somehow took a lot more effort than I as hoping for. To begin with, it is entirely possible that my problems were due to my systems configuration or my ignorance towards certain config files in the MFEM repository. I still thought I'll bring it up here such that either people with similar problems can find it and/or one can adapt the build system accordingly. Or perhaps there is even a smoother way to resolve this.

## Problem

My directory ~/Software is structured as 
```bash
drwxr-xr-x  24 tobiasduswald  staff   768B Sep 23 16:02 STRUMPACK
drwxr-xr-x   4 tobiasduswald  staff   128B Sep 23 12:15 STRUMPACK-build
drwxr-xr-x  21 tobiasduswald  staff   672B Jul 25 16:48 glvis
drwxr-xr-x  15 tobiasduswald  staff   480B Jul 25 16:30 hypre
drwxr-xr-x  18 tobiasduswald  staff   576B Sep 18 10:54 metis-5.1.0
drwxr-xr-x  34 tobiasduswald  staff   1.1K Sep 23 16:00 mfem
drwxr-xr-x   8 tobiasduswald  staff   256B Jul 25 16:28 tpls
```
I build STRUMPACK with 
```
cd STRUMPACK
git checkout v7.1.4
mkdir build && cd build
cmake -DCMAKE_INSTALL_PREFIX=~/Software/STRUMPACK-build -DSTRUMPACK_USE_OPENMP=OFF -DTPL_ENABLE_BPACK=OFF -DTPL_ENABLE_SCOTCH=OFF -DTPL_ENABLE_PTSCOTCH=OFF -DCMAKE_OSX_ARCHITECTURES=arm64 .. 
make -j 
make install
```
I then build MFEM with
```
cd fem
git checkout v4.7
mkdir build && cd build
cmake -DMFEM_USE_LAPACK=ON -DMFEM_USE_MPI=ON -DMFEM_USE_METIS_5=ON -DMETIS_DIR=../../metis-5.1.0 -DMFEM_USE_STRUMPACK=ON ..
make -j 10
```
with the small change to `config/defaults.cmake`
```diff
diff --git a/config/defaults.cmake b/config/defaults.cmake
index 517051a6f..80196f4cf 100644
--- a/config/defaults.cmake
+++ b/config/defaults.cmake
@@ -154,8 +154,7 @@ set(STRUMPACK_DIR "${MFEM_DIR}/../STRUMPACK-build" CACHE PATH
     "Path to the STRUMPACK library.")
 # STRUMPACK may also depend on "OpenMP", depending on how it was compiled.
 # Starting with v2.2.0 of STRUMPACK, ParMETIS and Scotch are optional.
-set(STRUMPACK_REQUIRED_PACKAGES "MPI" "MPI_Fortran" "ParMETIS" "METIS"
-    "Scotch/ptscotch/ptscotcherr/scotch/scotcherr"
+set(STRUMPACK_REQUIRED_PACKAGES "MPI" "MPI_Fortran" "METIS"
     "ScaLAPACK" "LAPACK" "BLAS" CACHE STRING
     "Additional packages required by STRUMPACK.")
```
This passes fine with `-DMFEM_USE_STRUMPACK=OFF` (obviously), but with STRUMPACK active, the build crashes in the CMAKE  stage. The error returns:
```
-- Looking for STRUMPACK ...
--    in STRUMPACK_DIR = /Users/tobiasduswald/Software/mfem/../STRUMPACK-build
-- STRUMPACK: looking for required package: MPI
-- STRUMPACK: looking for required package: MPI_Fortran
-- STRUMPACK: looking for required package: METIS
-- STRUMPACK: looking for required package: ScaLAPACK
-- Imported ScaLAPACK[RELEASE]: /opt/homebrew/lib/libscalapack.dylib;-L/opt/homebrew/opt/openblas/lib -lopenblas;-L/opt/homebrew/opt/openblas/lib -lopenblas;/opt/homebrew/lib/libmpi_usempif08.dylib;/opt/homebrew/lib/libmpi_usempi_ignore_tkr.dylib;/opt/homebrew/lib/libmpi_mpifh.dylib;/opt/homebrew/lib/libmpi.dylib
-- STRUMPACK: looking for required package: LAPACK
-- STRUMPACK: looking for required package: BLAS
-- Performing Test STRUMPACK_VERSION_OK
-- Performing Test STRUMPACK_VERSION_OK - Failed
CMake Error at /opt/homebrew/Cellar/cmake/3.30.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:233 (message):
   *** STRUMPACK not found. Please set STRUMPACK_DIR. (missing: STRUMPACK_VERSION_OK) 
Call Stack (most recent call first):
  /opt/homebrew/Cellar/cmake/3.30.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:603 (_FPHSA_FAILURE_MESSAGE)
  config/cmake/modules/MfemCmakeUtilities.cmake:590 (find_package_handle_standard_args)
  config/cmake/modules/FindSTRUMPACK.cmake:18 (mfem_find_package)
  CMakeLists.txt:373 (find_package)
```

## Solution

It took me a while to figure out what's wrong but the above output apparently indicates that the build system fails to build a small test program with the STRUMPACK solver. After some digging, I found that STRUMPACK examples use a few different linker flags, and it turns out that when I add `CMAKE_EXE_LINKER_FLAGS` to the `cmake` call for building MFEM 
```
cmake -DCMAKE_EXE_LINKER_FLAGS="-L/opt/homebrew/Cellar/gcc/14.1.0_2/lib/gcc/current -lgfortran" -DMFEM_USE_LAPACK=ON -DMFEM_USE_MPI=ON -DMFEM_USE_METIS_5=ON -DMETIS_DIR=../../metis-5.1.0 -DMFEM_USE_STRUMPACK=ON  ..
```
the library compiles successfully and the examples using STRUMPACK run perfectly fine.

I'm not sure if this is immediately clear that these additional flags are needed, so I wondered if a) there is a simpler way that I don't know that does not require these FLAGS or if b) one should consider adding these flags to the build system?

**Comment by v-dobrev** [comment]
There is a comment about this issue just after the line you edited in `defaults.cmake`: https://github.com/mfem/mfem/blob/8ed11a5c9a1f8af4401562dfd2df354304b36145/config/defaults.cmake#L158-L164

In your case, you can configure STRUMPACK properly with something like:
```cmake
set(STRUMPACK_REQUIRED_LIBRARIES
    "-L/opt/homebrew/Cellar/gcc/14.1.0_2/lib/gcc/current -lgfortran"
    CACHE STRING "Additional libraries required by STRUMPACK.")
```

I don't really see an easy way to automate this in the build system. Do you have any suggestions?

**Comment by TobiasDuswald** [comment]
Oh, I did not see the comment, that would have saved quite a bit of time 🙈 Thanks for pointing that out @v-dobrev .

Regarding the build system, I don't have any suggestions to address that issue for all platforms, I lack insights into the different build systems of the packages. I wonder if it would be possible to make the error message a little more precise? 
```
-- Performing Test STRUMPACK_VERSION_OK
-- Performing Test STRUMPACK_VERSION_OK - Failed
CMake Error at /opt/homebrew/Cellar/cmake/3.30.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:233 (message):
   *** STRUMPACK not found. Please set STRUMPACK_DIR. (missing: STRUMPACK_VERSION_OK) 
Call Stack (most recent call first):
  /opt/homebrew/Cellar/cmake/3.30.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:603 (_FPHSA_FAILURE_MESSAGE)
  config/cmake/modules/MfemCmakeUtilities.cmake:590 (find_package_handle_standard_args)
  config/cmake/modules/FindSTRUMPACK.cmake:18 (mfem_find_package)
  CMakeLists.txt:373 (find_package)
```
It was not trivial for me to conclude that something goes wrong with the fortran compiler here. Anyhow, probably the existence of this issue is already sufficient; if I had the same problem again I'd look for `STRUMPACK_VERSION_OK` in the issues and I'd find this one. From your comment, I'd then understand to set STRUMPACK_REQUIRED_LIBRARIES, and then I'd be good to go.

**Comment by v-dobrev** [comment]
You are right, tracking an issue with a CMake failure like this requires some knowledge of how CMake works. When a test like this fails, there is a log of what happened, somewhere in the CMake directories. However it is not obvious (to me) where to find the log file -- I always have to browse a bit to find the right place. However, once you find the log file, you can see the exact command that failed and how it failed. Also, I think there may be `cmake` options to tell it to print these failure logs on the standard output but I have not used this approach myself.
