### ISSUE TITLE
Zero Jacobian for boundary elements

### ISSUE THREAD

**Issue by Wayne901** [mfem/mfem#4521]
When I get the `FaceGeometricFactors` for 2-D boundaries in 3-D space, the Jacobian matrix is empty. The code is 
```
if (dim == 2)
  const FaceGeometricFactors *face_geom = mesh->GetFaceGeometricFactors(*ir, GeometricFactors::JACOBIANS, FaceType::Boundary, MemoryType);
const auto Jacobian = Reshape(face_geom->J.Read(), Q1D,Q1D,3,2,NE);

```
`Jacobian` is empty (with maximum value around 1e-310). Is there an example where partial assembly is applied, and jacobian matrix of 2-D elements in 3-D is required (Or is PADiffusionSetup2D<3> ever used)? For MassIntegrator only determinant of jacobian is needed.

**Comment by pazner** [comment]
Hmm, it looks like the face Jacobian matrices are not actually computed in the face geometric factors (thanks for reporting this). I suppose this was never implemented — is that correct @YohannDudouit @v-dobrev? If that is the case, we should probably exit with an error message saying that it is not implemented.

If the mesh is a 2D mesh in 3D space, then you would use the regular (non-face) geometric factors. This will give you the Jacobians of 2D elements in 3D space. For example, ex1 on a surface mesh such as star-surf.mesh will work with partial assembly. I don't believe we currently have a case where the face Jacobian matrices are required.

**Comment by Wayne901** [comment]
Thank you @pazner ,
`If the mesh is a 2D mesh in 3D space, then you would use the regular (non-face) geometric factors.` In this case, will the Jacobian be a 3x3 matrix or 3x2 matrix?

**Comment by pazner** [comment]
The Jacobian in this case will be 3x2 (more generally, $\mathrm{sdim} \times \mathrm{dim}$). If you want to solve a diffusion problem on a 2D surface in 3D, you should add the diffusion integrator as a domain integrator not boundary integrator.

**Comment by Wayne901** [comment]
I’m working on a 3-D problem (hexahedral elements), but I need the boundary integral. Though there is partial assembled boundary integral for H1 mass matrix, I'd like to apply mass matrices for Hcurl space, therefore the diffusion operator for boundary elements are required since it's same as Hcurl's mass operator (both need inverse Jacobian). Will it work for this scenario?

**Comment by pazner** [comment]
Are you considering specifically the curl-free subspace of H(curl)? In which case the mass matrix coincides with the diffusion operator.

But yes, I agree that the H(curl) mass integrator on the boundary will require Jacobians, which appear to not yet be implemented with partial assembly.

**Comment by Wayne901** [comment]
Yes, the mass matrix of curl-free subspace is needed. I wonder will it be difficult to implement it by myself (by following the codes of partial assembled diffusion operator). Since `FaceGeometricFactors` is not implemented yet, will `GeometricFactors` on boundary elements work?

**Comment by pazner** [comment]
@YohannDudouit, @v-dobrev, @camierjs any thoughts on computing the Jacobian matrices in the face geometric factors? Is this planned? Should we just error out with a message for now?

**Comment by v-dobrev** [comment]
The tangential derivative computation is actually already implemented in both `FaceQuadratureInterpolator::Eval3D` and `FaceQuadratureInterpolator::SmemEval3D`, however, it is just not written out to the output `Vector &q_der`. This should be easy to add.

There is another small issue to fix in `FaceGeometricFactors::FaceGeometricFactors` -- the size of the `J` vector at each quadrature point should be `vdim x (dim-1)` where `dim` is the (reference-space) dimension of the mesh. This also needs to be corrected in the doxygen description of `J`.
