### ISSUE TITLE
Do the .cmake files define any targets?

### ISSUE THREAD

**Issue by VictorEijkhout** [mfem/mfem#4525]
I would appreciate some explanation on what the `.cmake` files define. In particular do they define a `mfem::mfem` target or such? Or is it `mfem_INCLUDE_DIR`, `MFEM_INCLUDE_DIR` or `Mfem_INCLUDE_DIR` or such? There is a `CMakeLists.txt` in the examples directory, but that is too convoluted for me.

**Comment by helloworld922** [comment]
There is a target called `mfem` which you can link against. At this time the mfem config file doesn't call `find_dependency` on any dependencies, which doesn't appear to matter for some dependencies (MPI, HYPRE, Metis, CUDA, GSLib), but does matter for HIP right now. You can manually find these before mfem for now. Please let us know if you find any others.

Example cmake application which uses mfem:

```cmake
cmake_minimum_required(VERSION 3.8)

project(myapp CXX)

# these five packages are only if you're using HIP
find_package(HIP REQUIRED)
find_package(HIPBLAS REQUIRED)
find_package(HIPSPARSE REQUIRED)
find_package(rocsparse REQUIRED)
find_package(rocrand REQUIRED)

find_package(MFEM REQUIRED)

add_executable(myapp myapp.cpp)

target_link_libraries(myapp
  PUBLIC mfem
)
```

**Comment by v-dobrev** [comment]
I'll just add a bit more info: all CMake variables defined in the exported `MFEMConfig.cmake` can be seen in the template for that file: https://github.com/mfem/mfem/blob/master/config/cmake/MFEMConfig.cmake.in. The exported CMake target, `mfem`, is defined in the files `MFEMTargets.cmake` and `MFEMTargets-*.cmake` which can be found in `<mfem-install-prefix>/lib/cmake/mfem`. The exported version of `MFEMConfig.cmake` is also in that directory.

**Comment by VictorEijkhout** [comment]
I love how self-documenting cmake is :-)

Thanks for the replies.
