### ISSUE TITLE
compilation error in convection-diffusion miniapps

### ISSUE THREAD

**Issue by e-aranda** [mfem/mfem#4529]
I have found the following compilation error:
``convection-diffusion.cpp: In function ‘int main(int, char**)’:
convection-diffusion.cpp:122:20: error: reference to ‘beta’ is ambiguous
  122 |    args.AddOption(&beta, "-beta", "--beta",
``
I have solved commenting the line ` using namespace std;` and using ` std::cout` , ` std::endl`  and `std::min`  where is necessary.

Same problem with `pconvection-diffusion.cpp`

**Comment by tzanio** [comment]
Yes, this is an issue, thanks for reporting it.

Do you want to propose a PR with your fix?

**Comment by e-aranda** [comment]
Ok, this is the PR [fix username std conflict](https://github.com/mfem/mfem/pull/4550/commits/d0b1f760eb49f8dac33f99221ab4b82ca4f82c41)

Thanks

**Comment by tzanio** [comment]
Discussion continued in https://github.com/mfem/mfem/pull/4550
