### ISSUE TITLE
Getting coarse-to-fine mapping for boundary elements during mesh refinement

### ISSUE THREAD

**Issue by kvoronin** [mfem/mfem#453]
Hello,

If I have a mesh which is being refined, is there a simple way to get a relation between coarse boudnary elements (boundary elements before refinement) and fine boundary elements (after refinement). That is, I'd like to know for each coarse boundary element what are the indices of the fine boundary element which appear after its refinement.

I think th desired mapping can be obtained using general relation tables, like
ABE_be = (AE_ABE)^T * (AE_e) * e_be, where "A" stands for coarse elements,  "BE" for boundary elements and small letters are for fine grid entities. Then I can get each of the relation tables quite easily.
But probably one can avoid creating such global structures and implied memory allocation? 

Any advice would be helpful.

Thanks,
Kirill

**Comment by jakubcerveny** [comment]
Hi Kirill,

we have a coarse-fine relation table in the code (see struct CoarseFineTransformations and Mesh::GetRefinementTransforms), but currently only for regular (volume) elements. I think the right solution is to add functionality to deduce boundary coarse-fine relations from the existing volume coarse-fine relations.

The function would loop over all of the (possibly no longer existing) coarse elements in the CoarseFineTransformations struct and look for boundary elements of the child volume elements, linking them back to the original boundary element. Another CoarseFineTransformations struct for the mesh boundary would be created. We however do not have such functionality yet.

I didn't understand the notation in your matrix expression, I would need more details to be able to comment on that.

Thank you,
Jakub

**Comment by kvoronin** [comment]
Hi, @jakubcerveny,

I like your idea. When I asked my question I was afraid that I missed something already existing due to the lack of MFEM knowledge. 

Eventually, I did what I wanted in a brute-force way from the relations between boundary elements and elements on both coarse and fine levels and through relation between elements on the fine and coarse meshes (as described above, probably you don't need my notations, if yes I can explain them). In the end I used some geometrical ordering of the vertices which helped me to impose an order for fine-grid boundary elements which are contained in the coarse grid boundary element.

Later, if necessary, I will try to implement it as you suggested, using CoarseFineTransformations. That way it could be more efficient in terms of memory I guess. Though looping over all coarse elements to find the boundary looks non-optimal in terms of operations (this is actually why I used a relation between boundary elements and elements).

Thanks,
Kirill

**Comment by jakubcerveny** [comment]
The loop over all elements is just a concept, in an actual implementation this could hopefully be avoided. If you ever had the time to contribute this feature we would definitely appreciate it.

I'll close this now, but feel free to reopen if necessary.
