### ISSUE TITLE
SetPreconditioner after SetOperator for LORSolver

### ISSUE THREAD

**Issue by Wayne901** [mfem/mfem#4531]
I'm kind of confuse with the sequence of `SetPreconditioner()` and `SetOperator()` when using a LORSolver<HypreAMS> as preconditiner. 
In my example, setting the operator of lor preconditioner gives less iterations(same as a pure HypreAMS preconditioner when FE's order is 1), such as
```
            CGsolver->SetOperator(*A);
            lor_prec->SetOperator(*A);
            CGsolver->SetPreconditioner(*lor_prec);
```
or
```
            CGsolver->SetPreconditioner(*lor_prec);
            CGsolver->SetOperator(*A);
```
Here `A` is the assembled `OperatorPtr`, and `loc_prec = new LORSolver<HypreAMS>(*a, ess_tdofs);`
However in the plor_solver miniapps the preconditioner is set after operator(here's where I'm confused, i guess the preconditioner's operator is different to A then?), and only in this manner can the lor solver be applied to partial assembled codes. What's the correct procedure?

**Comment by pazner** [comment]
Hi @Wayne901,

If you call `CGSolver::SetOperator` and there is already a preconditioner added to the CG solver, it will in turn call `SetOperator` on the preconditioner.

`LORSolver::SetOperator` ends up calling `SetOperator` on the underlying solver object, so if you call `LORSolver<HypreBoomerAMG>::SetOperator(A)`, where `A` is a `HypreParMatrix`, this will actually rebuild the AMG solver using the given matrix (and not actually doing LOR). This is probably not the correct behavior, and should be changed in the implementation of `LORSolver`.

Does the distinction make sense?

**Comment by Wayne901** [comment]
Yes it makes sense. So calling `SetOperator` after the `SetPreconditioner` is equivalent to an AMG (or AMS, ADS) preconditioner.
I think I'm clear how to set LOR preconditioner properly now.
Thank you @pazner :)
