### ISSUE TITLE
Conformal adaption for Tetrahedron options

### ISSUE THREAD

**Issue by wjhorne** [mfem/mfem#4532]
Hi,

I am interested in building a DG code using MFEM at its core, specifically targeting conformal Tetrahedron adaption. Ideally this would be dynamic where the mesh would be refined or coarsened in the domain throughout a simulation. From what I see glancing through the code and documentation, it seems like I could potentially refine, but not coarsen a mesh. Also dynamic load-balancing would not be available if I stick to conformal. Is this correct? What would be my best option to get as close to this capability as possible using MFEM? 

Some background : I am trying to avoid non-conformal due to my interest in making this method satisfy summation-by-parts (SBP). It is possible to make a SBP non-conformal Tet method, but there are a lot of headaches to it, particularly when I already have to introduce a fair amount of new finite element space work as is.

**Comment by v-dobrev** [comment]
Yes, you are correct: currently, derefinement and rebalancing are only available for nonconforming meshes.

For rebalancing conforming tetrahedral mesh, I think is is possible to gather the parallel mesh on one rank as a serial mesh (if it is not too big) and then redistribute it, however that is not optimal. (I've wanted to add mesh repartitioning for conforming meshes for some time but I still haven't found the time to do it.)

For coarsening, it may be possible to do something by storing all coarse mesh refinements as separate meshes, however I'm not sure if that's actually going to work and how much effort it will require.

**Comment by wjhorne** [comment]
That's good to know. I'll have to rethink my strategy a bit. 

One option that comes to mind is that I do non-conformal with 1 level max difference across faces and then add stitching elements outside of MFEM by hand at non-conformal interfaces to make everything behave as if it were conformal. From there I could project back solutions to MFEM and it would allow me to use AMR with all the bells and whistles as well as plot. I would lose out on the ease of linear system assembly, amongst other things, from MFEM. It also would be kind of funky to book-keep and store everything.

I'll weigh this against committing to full non-conformal. 

As a last question before I dive deeper : Are there good examples of adding new element collections/spaces to MFEM? For the SBP Tets I am considering, everything behaves a bit like Lagrange elements with extra nodes and extra math to evaluate function values at points. So far I have been storing everything as P0 L2 elements with number_of_node vector values and doing all the math custom. I then project to more typical L2 elements so I can use MFEM for plotting, etc. It would be nice to pipe it in more properly to MFEM and get all the functionality

**Comment by hughcars** [comment]
@wjhorne, the technique you're describing involving serialization and then repartitioning the mesh is exactly the one we use in Palace to handle conformal refinement [see here](https://github.com/awslabs/palace/blob/main/palace/utils/geodata.cpp#L3263-L3306). It is effective, but does eventually become a bit of a bottleneck for really large meshes, but generally we operate with high enough P that the solver cost swamps everything else.

**Comment by wjhorne** [comment]
That seems simple enough to implement and worth a shot. Is there any way to coarsen that you have found? I am targeting unsteady calculations that would likely benefit from it.

**Comment by hughcars** [comment]
There is no method for coarsening at present. This is something I really want to add to MFEM however, for essentially the reasons you've outlined, that it's necessary for handling transient amr. 

There are two ways this can be gone about: 1) maintain a refinement tree, so that refinements performed during adaptation can be undone, but no coarsening beyond the initial mesh can be performed (this is akin to the nonconformal amr) or 2) edge collapses, by merging vertices that make up an edge, whole sets of elements can be eliminated. This is a much more powerful technique than the refinement tree, but would come with a few issues, the most thorny of which is avoiding degrading the underlying geometry definition in the case of curved surfaces. Deleting edges within a plane has no impact, but remove them from a curved surface and you're into a world of pain.

Edge primitive algorithms have been the preserve of CFD codes in the past (with their huge desire for anisotropy), but it would be really cool to get one into MFEM.

**Comment by wjhorne** [comment]
That is good to know. The edge primitive algorithm definitely seems along the lines of what would work best for what I have in mind. 

How realistic is it to assume that non-serialized load-balancing and coarsening would come online sometime in the future? I had started an effort to use NC meshes with single level differences at non-conformal interfaces and then add numerical stitching elements along all non-conformal interfaces to make it conformal. I would likely ditch this idea completely if there is some guarantee that things will change down the line.
