### ISSUE TITLE
My gmsh file is not working with mfem example 2.

### ISSUE THREAD

**Issue by NikhilPurbey** [mfem/mfem#4533]
Hello everyone, 

       Here is my gmsh file: 
[newRefinedTestBeam.zip](https://github.com/user-attachments/files/17282629/newRefinedTestBeam.zip)

Basically what I am trying to do is I am trying replicate something similar to beam-tet.mesh file in gmsh and trying to replicate the result shown by ./ex2 file. But whenever I try to use my gmsh file, it does not get solved. I was wondering why that is the case. 

P.S: I am new to FEM packages and FEM concept as a whole.

**Comment by Raghavendra0117** [comment]
Dear @NikhilPurbey ,

The mesh is supposed to have two materials. You can find the following comment in the file "ex2p.cpp"

"This example code solves a simple linear elasticity problem describing a multi-material cantilever beam."

**Comment by NikhilPurbey** [comment]
Hello @Raghavendra0117,

       Thanks for the response. Sorry for lack of clarification. I made some adjustments to ex2.cpp. I made it so that it takes beam with 1 material, and finds the linear elasticity solution. Here is my version of ex2.cpp: 
[ex2.zip](https://github.com/user-attachments/files/17294068/ex2.zip)

I used this modified 1 material beam mesh with the ex2.cpp. 
[beam-tet-test.zip](https://github.com/user-attachments/files/17294096/beam-tet-test.zip)

I was able to get the solution, that looks like this:
![singleMaterialSolution](https://github.com/user-attachments/assets/bd92eaaa-0d7f-44c2-8702-d07228583be7)


But I am not able to get solution with this gmsh generated msh file. 
[newRefinedTestBeam.zip](https://github.com/user-attachments/files/17294139/newRefinedTestBeam.zip)

**Comment by Raghavendra0117** [comment]
Hi @NikhilPurbey ,

The attributes for the boundaries and material are different in the file "newRefined*.msh".

I have modified the file (
[newRefinedTestBeam1.msh.zip](https://github.com/user-attachments/files/17302514/newRefinedTestBeam1.msh.zip)
) with right attributes and it is working fine.

![Untitled](https://github.com/user-attachments/assets/de18995e-9452-4fa7-a512-b31c33b2cbf8)

**Comment by NikhilPurbey** [comment]
Thanks a lot for your help. I understand how it works. One final question I had was how can I make the color bar show up. The one which says which color represents which Value.

Thanks,
Nikhil

**Comment by NikhilPurbey** [comment]
Hi @Raghavendra0117,

Thanks a lot for your help. I understand how it works. One final question I had was how can I make the color bar show up. The one which says which color represents which Value.

Thanks,
Nikhil

**Comment by v-dobrev** [comment]
Hi @NikhilPurbey, in GLVis, you can toggle the color bar with the key `c`.

For more GLVis shortcuts, see https://github.com/GLVis/glvis/blob/master/README.md.

**Comment by NikhilPurbey** [comment]
Thank you @v-dobrev.
