### ISSUE TITLE
DG for wave propagation

### ISSUE THREAD

**Issue by lxx0831** [mfem/mfem#4534]
Hello.
Is there any example of solving two-dimensional elastic wave equations using DG method in MFEM? Or a similar example?

**Comment by v-dobrev** [comment]
I can think of two relevant examples:
* Example 10 solves time-dependent nonlinear elasticity problem using continuous (H1) discretization space for the deformation and the velocity.
* Example 17 solves steady-state elasticity using a DG formulation.

**Comment by lxx0831** [comment]
Thank you for your response. After carefully studying examples 10 and 17, I realized that they are not very helpful for my needs, which I may not have explained clearly. I am interested in simulating the propagation of two-dimensional seismic waves using the Discontinuous Galerkin (DG) method in MFEM. Typically, this involves representing the two-dimensional elastic wave equation as a first-order hyperbolic system of velocity-stress equations, and then solving it using the DG method.
![image](https://github.com/user-attachments/assets/08d640b4-d60d-40f3-bd35-87331b14eb37)
![image](https://github.com/user-attachments/assets/f522d53f-4519-47ed-a0e1-563f069ce103)
![image](https://github.com/user-attachments/assets/e718ee4c-77ae-456a-814a-4eb472b29848)
![image](https://github.com/user-attachments/assets/fe7e3d7e-7e6e-41f0-8435-ba4d90d381e9)
Has anyone used the DG (L2) finite elements in MFEM to study similar problems, such as the propagation of seismic waves? I found that Example 18: DG Euler Equations is similar to the problem I am studying, although it is a nonlinear problem. Could I potentially adapt the code from Example 18 to address my issue? I look forward to your response,Thank you.

**Comment by v-dobrev** [comment]
If your system can be written in conservative form:

$$\frac{\partial u}{\partial t} + \nabla\cdot F(u,t) = \ldots$$

then, yes, it should be possible to at least try the approach from Example 18. However, I'm not sure how well it will work -- it's probably worth searching the literature for papers that have looked at using this approach for the type of problem you are interested in.
