### ISSUE TITLE
Gradient of an L2 / DG solution

### ISSUE THREAD

**Issue by Rickbude** [mfem/mfem#4535]
Hi there,

I am trying to calculate the gradient of a DG solution I obtained from example 14.
My initial thought was to project the gradient using a `GradientGridFunctionCoefficient` onto an RT space, with code like this:

```cpp
RT_FECollection rt_fec(order, dim);
FiniteElementSpace rt_fespace(&mesh, &rt_fec);
mfem::GridFunction gradx(&rt_fespace);
mfem::GradientGridFunctionCoefficient gradx_coeff(&x);
gradx.ProjectCoefficient(gradx_coeff);
```

An example problem is the unit square [0,1]x[0,1], with homogeneous Dirichlet boundary conditions ($u=0$), and the manufactured problem $u(x,y)=\sin(\pi x)\sin(\pi y)$, such that the source term $f(x,y)=2\pi^2\sin(\pi x)\sin(\pi y)$. If I use degree 1 L2 elements, the solution and its gradient look reasonable:

<img src="https://github.com/user-attachments/assets/dd67ee7b-2e47-4c21-9252-aba5a6830f13" height="200" >
<img src="https://github.com/user-attachments/assets/88aba4a1-f04c-4a1c-ba21-0f79a1683089" height="200">

But when I use piecewise constant L2 elements, the gradient becomes 0:

<img src="https://github.com/user-attachments/assets/62102b58-835a-4fb6-9f87-7a5415e51db2" height="200" >
<img src="https://github.com/user-attachments/assets/668266a9-832c-41e0-bce1-d0b7c3fba3e5" height="200">

This makes kind-of sense to me: the gradient of a piecewise constant L2 element is of course 0. But obviously this is not the most optimal approximation of the gradient: clearly there is information about the gradient hidden in the trace jumps. The same problem is encountered when `GridFunction::GetDerivative` is used, as suggested in #2867.

One idea, also suggested in #2867, would be to interpolate the solution onto a H1 space, and then take the gradient. Is this the optimal route? In particular, this sentence from Sun&Wheeler 2005 (Symmetric and Nonsymmetric Discontinuous Galerkin Methods for Reactive Transport in Porous Media, doi: 10.1137/S003614290241708X) struck me as important:

> As a valuable property, DG schemes possess element-wise mass conservation.
 OBB-DG satisfies local conservation strictly, whereas SIPG, NIPG, and IIPG are 
 locally conservative if the concentration jump term is considered as part of the 
computed diffusive flux:

So, apparently, in order to calculate the flux, the concentration jump needs to be taken into account? Is there a simple way of obtaining these jumps? In #2294 it is suggested to "use the jumps as the dofs of RT_0", but I am unsure on how to do that. 

-- Background --

I am mainly looking into this, because I am trying to understand local and global conservation properties of various FEM schemes (see also issue #4086). For that, I am comparing example 0, example 8 and example 14. In all of these I need to calculate the boundary flux in a way that is consistent with the discretization. If I just project the gradient onto an RT space, there is no conservation, so clearly something more sophisticated is needed. But I am not sure if the intermediate step via an H1 projection is the correct way of doing this. Perhaps I need a second solve to compute the numerical flux as a postprocessing step? 

Perhaps a final related question: what is exactly the DG scheme used in example 14? I think SIPG, is that correct?

**Comment by Rickbude** [comment]
Update: I have a sort-of working solution. I project the gradient of the L2 solution onto an RT space, and after that I substract the trace jump multiplied by the stabilization factor: $\kappa [[u_h]]$, as suggested for example in [10.1016/j.apnum.2006.09.010](https://doi.org/10.1016/j.apnum.2006.09.010), eq 27.

Now I get the following as the gradient of the piecewise constant L2 elements shown above:

![image](https://github.com/user-attachments/assets/e9af8b9e-8543-467e-b340-5c5f0e00a4eb)

I used the following bit of code:

```cpp
// 12b. Calculate grad u_h
RT_FECollection rt_fec(order, dim);
FiniteElementSpace rt_fespace(&mesh, &rt_fec);
mfem::GridFunction gradx(&rt_fespace);
mfem::GradientGridFunctionCoefficient gradx_coeff(&x);
gradx.ProjectCoefficient(gradx_coeff);

// 12c. Calculate and subtract kappa * [[u_h]]
mfem::ElementTransformation *face_elem_transf;
mfem::ElementTransformation *transf;
for(int i = 0; i<mesh.GetNumFaces(); i++){

   //Obtain the physical locations of the RT face dofs
   const FiniteElement * elem = rt_fespace.GetFaceElement(i);
   const IntegrationRule & ir = elem->GetNodes();
   ElementTransformation * T = mesh.GetFaceTransformation(i);
   DenseMatrix P;
   T->Transform(ir, P);

   //Get elements left and right of the face of interest
   int elem1 = -1;
   int elem2 = -1;
   mesh.GetFaceElements(i,&elem1,&elem2);

   mfem::Array<int> face_dofs;
   rt_fespace.GetFaceDofs(i,face_dofs);

   mfem::IntegrationPoint ip;
   //Calculate the jumps
   for(int j = 0; j<ir.Size(); j++){

      mfem::Vector pos(P.GetColumn(j),dim);
      double jump = 0.0;

      //Get value for element 1
      if (elem1 >= 0)
      {
         // side 1
         face_elem_transf = mesh.GetElementTransformation(elem1);
         face_elem_transf->TransformBack(pos,ip);
         jump += x.GetValue(elem1,ip);
      }

      if (elem2 >= 0)
      {
         // side 2. Will be skipped if the face is a boundary fce
         face_elem_transf = mesh.GetElementTransformation(elem2);
         face_elem_transf->TransformBack(pos,ip);
         jump -= x.GetValue(elem2,ip);
      }

      //Account for orientation (face_dofs[j] might be negative)
      int index   = (face_dofs[j]<0) ? -face_dofs[j]-1 : face_dofs[j];
      double sign = (face_dofs[j]<0) ? 1.0 : -1.0;
      gradx[index] += sign*kappa*jump;
   }
}
```
Is this a reasonable and robust way of approaching this? Would you foresee any problems with this approach? Is there maybe a more standard way of doing this?

**Comment by pazner** [comment]
One way of doing this is to use the idea in DG of a numerical flux.

Let $V$ be the scalar DG space, and $W = [V]^d$ be the vector-valued DG space.

Let $u : \Omega \to \mathbb{R}$ be given. On a single element $\kappa$, we can consider the $L^2$ projection of $\nabla u$ onto $W$ by finding $\sigma \in W$ such that, for all $\tau \in W$,

$$\int_{\kappa} \sigma \cdot \tau ~ dx = \int_{\kappa} \nabla u \cdot \tau ~ dx.$$

Integrating the right-hand side by parts, you obtain

$$ \int_{\kappa} \sigma \cdot \tau ~ dx = - \int_{\kappa} u \nabla \cdot \tau ~ dx + \int_{\partial \kappa} u \tau \cdot n ~ ds $$

where $n$ is the outward facing normal from $\kappa$.

At this point, since the given $u$ is actually a DG function, we need to introduce a single-valued numerical flux $\hat{u}$ on element interfaces. Replacing $u$ with its numerical flux $\hat{u}$ in the surface integral and summing over all mesh elements, you arrive at

$$ \int_\Omega \sigma \cdot \tau ~ dx = - \int_{\kappa} u \nabla_h \cdot \tau ~ dx + \int_\Gamma \hat{u} [ \tau ]~ds $$

where the jump is defined by $[\tau] = \tau_1 n_1 + \tau_2 n_2$ and $\Gamma$ represents the mesh skeleton.

In MFEM, you can assemble the right-hand side, and solve the system with the (vector) DG mass matrix. As far as I know, MFEM doesn't have built-in integrators that compute exactly the RHS above. You could use something like the following:

<details>
<summary>Code for linear form integrators (click to expand)</summary>

```c++
class DomainLFDivIntegrator : public LinearFormIntegrator
{
private:
   Coefficient &Q;
public:
   DomainLFDivIntegrator(Coefficient &Q_) : Q(Q_) { }

   void AssembleRHSElementVect(const FiniteElement &el,
                               ElementTransformation &Tr,
                               Vector &elvect) override
   {
      const int dim = el.GetDim();
      const int ndof = el.GetDof();

      DenseMatrix dshape(ndof, dim);

      const IntegrationRule *ir = IntRule;
      if (ir == NULL)
      {
         int intorder = 2 * el.GetOrder();
         ir = &IntRules.Get(el.GetGeomType(), intorder);
      }

      elvect.SetSize(ndof * dim);
      elvect = 0.0;

      for (int i = 0; i < ir->GetNPoints(); i++)
      {
         const IntegrationPoint &ip = ir->IntPoint(i);

         Tr.SetIntPoint (&ip);
         real_t w = ip.weight * Tr.Weight() * Q.Eval(Tr, ip);
         el.CalcPhysDShape(Tr, dshape);

         for (int j = 0; j < ndof; ++j)
         {
            for (int d = 0; d < dim; ++d)
            {
               elvect[j + ndof*d] -= w * dshape(j, d);
            }
         }
      }
   }
};

class VectorDGPenaltyIntegrator : public BilinearFormIntegrator
{
protected:
   const double kappa;

   Vector shape1, shape2, nor, nh, ni;
   DenseMatrix jmat, mq, adjJ;

public:
   VectorDGPenaltyIntegrator(const double kappa_) : kappa(kappa_) { }
   virtual void AssembleFaceMatrix( const FiniteElement &el1,
                                    const FiniteElement &el2,
                                    FaceElementTransformations &Trans,
                                    DenseMatrix &full_elmat);
};

class FaceLFAverageNormalIntegral : public LinearFormIntegrator
{
private:
   Coefficient &Q;
public:
   FaceLFAverageNormalIntegral(Coefficient &Q_) : Q(Q_) { }

   void AssembleRHSElementVect(const FiniteElement &el,
                               ElementTransformation &Tr,
                               Vector &elvect) override
   {
      MFEM_ABORT("");
   }

   void AssembleRHSElementVect(
      const FiniteElement &el1,
      const FiniteElement &el2,
      FaceElementTransformations &Tr,
      Vector &elvect) override
   {
      const int dim = el1.GetDim();
      const int ndof1 = el1.GetDof();
      const int ndof2 = (Tr.Elem2No >= 0) ? el2.GetDof() : 0;

      Vector shape1(ndof1);
      Vector shape2(ndof2);
      Vector normal(dim);

      const IntegrationRule *ir = IntRule;
      if (ir == NULL)
      {
         int intorder = 2 * el1.GetOrder();
         ir = &IntRules.Get(el1.GetGeomType(), intorder);
      }

      elvect.SetSize((ndof1 + ndof2) * dim);
      elvect = 0.0;

      for (int i = 0; i < ir->GetNPoints(); i++)
      {
         const IntegrationPoint &ip = ir->IntPoint(i);

         Tr.SetAllIntPoints(&ip);
         const IntegrationPoint &eip1 = Tr.GetElement1IntPoint();

         if (dim > 1) { CalcOrtho(Tr.Jacobian(), normal); }
         else { normal[0] = 1.0; }

         el1.CalcShape(eip1, shape1);

         real_t q = Q.Eval(*Tr.Elem1, eip1);

         if (ndof2)
         {
            const IntegrationPoint &eip2 = Tr.GetElement2IntPoint();
            el2.CalcShape(eip2, shape2);

            const real_t q2 = Q.Eval(*Tr.Elem2, eip2);
            q = 0.5*(q + q2);
         }
         const real_t w = ip.weight*q;

         for (int d = 0; d < dim; ++d)
         {
            const real_t w_d = normal[d] * w;
            for (int j = 0; j < ndof1; ++j)
            {
               elvect[j + d*ndof1] += shape1[j] * w_d;
            }
            for (int j = 0; j < ndof2; ++j)
            {
               elvect[j + d*ndof2 + dim*ndof1] -= shape2[j] * w_d;
            }
         }
      }
   }

   void AssembleRHSElementVect(
      const FiniteElement &el,
      FaceElementTransformations &Tr,
      Vector &elvect) override
   {
      AssembleRHSElementVect(el, el, Tr, elvect);
   }
};
```

</details>

The system is then solved like this:

```c++
GridFunctionCoefficient u_coeff(&u);

FiniteElementSpace vec_fespace(&mesh, &fec, mesh.Dimension());

LinearForm grad_lf(&vec_fespace);
grad_lf.AddDomainIntegrator(new DomainLFDivIntegrator(u_coeff));
grad_lf.AddInteriorFaceIntegrator(new FaceLFAverageNormalIntegral(u_coeff));
grad_lf.AddBdrFaceIntegrator(new FaceLFAverageNormalIntegral(u_coeff));
grad_lf.Assemble();

BilinearForm mass(&vec_fespace);
mass.AddDomainIntegrator(new VectorMassIntegrator);
mass.Assemble();
mass.Finalize();

SparseMatrix &M = mass.SpMat();
DSmoother D(M);

GridFunction grad_u(&vec_fespace);

PCG(M, D, grad_lf, grad_u, 1, 20000, 1e-12, 0.0);
```

**Comment by v-dobrev** [comment]
Another approach that is independent of any DG formulation is to use the so-call weak gradient from L2 to H(div) which is basically the transpose of the divergence, or more precisely it is defined by the same equation as the one above for $\sigma$, however, now both $\sigma$ and $\tau$ are in H(div) conforming space (e.g. using `RT_FECollection`). Both linear forms on r.h.s. are available in MFEM: `VectorFEDomainLFDivIntegrator` and `VectorFEBoundaryFluxLFIntegrator` (only terms at the domain boundary are non-zero), see https://mfem.org/lininteg/.

**Comment by Rickbude** [comment]
Hi @v-dobrev, thanks for chiming in!!

You mean like so?

```cpp
RT_FECollection rt_fec(order, dim);
FiniteElementSpace rt_fespace(&mesh, &rt_fec);
GridFunctionCoefficient u_coeff(&x);

LinearForm grad_lf(&rt_fespace);
grad_lf.AddDomainIntegrator(new VectorFEDomainLFDivIntegrator(u_coeff));
grad_lf.AddBoundaryIntegrator(new VectorFEBoundaryFluxLFIntegrator(u_coeff));
grad_lf.Assemble();

BilinearForm mass(&rt_fespace);
mass.AddDomainIntegrator(new VectorFEMassIntegrator);
mass.Assemble();
mass.Finalize();

SparseMatrix &M = mass.SpMat();
DSmoother D(M);
GridFunction gradx(&rt_fespace);
PCG(M, D, grad_lf, gradx, 1, 20000, 1e-12, 0.0);
```

This once again seems to work okay for higher element orders (let's say degree 2 and higher), but when using `-o 0` the boundary values are clearly incorrect:

![image](https://github.com/user-attachments/assets/56aa6ee3-d101-40e2-8baf-03cae51d4bc3)

**Comment by v-dobrev** [comment]
I suspect the issue is that the coefficient in the `VectorFEDomainLFDivIntegrator` should be `-u`, not `u` because the form implements $l(v) = (Q, \nabla\cdot v)$.

**Comment by Rickbude** [comment]
Hmm yes, I considered this as well. And while it does improve the results a bit, it still doesn't look right:

![image](https://github.com/user-attachments/assets/54480019-a709-42b8-9a7b-d5ac151b1ac5)

**Comment by v-dobrev** [comment]
I don't know if this is still an issue in the code or this is to be expected for `order = 0`. If you can post the code you are running, I can take a quick look for any other issues and try to run it myself to try to figure out if there is still an issue.

**Comment by Rickbude** [comment]
Thank you @v-dobrev, that would be very helpful!

I added all code mentioned throughout this issue to this zip: [issue_4535.zip](https://github.com/user-attachments/files/17370734/issue_4535.zip). I also added the relevant pieces of `CMakeLists.txt` and the mesh that I used (`ref-square.mesh`). You will find three versions of the code:

- `ex14_conservation_test_v1.cpp`: my own attempt, see [this comment](https://github.com/mfem/mfem/issues/4535#issuecomment-2408053710).
- `ex14_conservation_test_v2.cpp`: version with method suggested by @pazner, in [this comment](https://github.com/mfem/mfem/issues/4535#issuecomment-2408233039)
- `ex14_conservation_test_v3.cpp`: version with method suggested by you.

In all these scripts I calculate the error for `u_h` and the error in the Flux. I also calculate the global conservation:

$$\iint_\Omega f dS = \oint_\Gamma \hat{n} \cdot \nabla u dl$$

Only `ex14_conservation_test_v1.cpp` shows a gradient that seems correct for `-o 0`, and that shows global conservation up to machine precision for all orders. But once again I am not convinced of its generality and robustness. I have not tested this approach with unstructured triangular meshes for example.

**Comment by pazner** [comment]
Hi @Rickbude,

First some general comments/questions about approximating the gradient of a DG function that does not necessarily come from a DG discretization of the Laplacian:

Does the method you describe work if you don't have prescribed Dirichlet boundary values for $u$? i.e. if you're given an arbitrary $u_h \in V_h$, does it give you a good approximation to the gradient?

I agree that for piecewise constant data, the values at the boundary will be inaccurate with the method I described unless you can incorporate additional information (just think of it in terms of finite difference stencils — if you want an accurate derivative at the boundary, you will need to use one-sided stencils, which are not really natural to do in the finite element context). If you have additional Dirichlet data they can be incorporated into the numerical flux.

I don't think there's necessarily a "right answer" about whether to use $[L^2]^d$ vs $\mathrm{RT}$. But with DG methods, the flux and the scalar are approximated in $L^2$, so it seemed natural to do the same.

The penalty term is needed to ensure stability of the DG bilinear form, but it is not needed just to recover the gradient.

---

In the case of recovering the flux from the solution $u_h$ of a DG discretization of the Laplacian, there is a well-defined answer to your question. The flux $\sigma_h \in [V_h]^d$ satisfies equation (3.4) from the "unified analysis" paper that you cited in your previous response; since the numerical flux $\hat{u}$ is single-valued, this simplifies to

$$ \int_\Omega \sigma_h \cdot \tau ~ dx = -\int_\Omega u_h \nabla_h \cdot \tau~dx + \int_{\Gamma^0} \hat{u} [\tau] ~ ds. $$

The IPDG method follows by choosing $\hat{u} = \{ u_h \}$ and $`\hat{\sigma} = \{ \nabla_h u_h \} - \mu [ u_h ]`$.

Inserting the numerical flux $\hat{u}$ into the variational form for $\sigma_h$ you obtain the expression that I included in my previous response.

If you are interested in the conservation properties of the method, those are stated in terms of the numerical flux $\hat{\sigma}$ on the element faces (see equation (3.2) of the paper). For the IPDG method, the numerical fluxes are given by the above expression, $`\hat{\sigma} = \{ \nabla_h u_h \} - \mu [ u_h ]`$. I believe these should be expressible in MFEM using the `RT_Trace_FECollection`.

**Comment by Rickbude** [comment]
Thanks @pazner for these insights.

> Does the method you describe work if you don't have prescribed Dirichlet boundary values for $u$?

I have not tried this yet, but I think no. The code I proposed assumes homogeneous Dirichlet boundary conditions at the complete boundary. I suspect that I would need to do something like this for the Interior, Dirichlet and Neumann edges respectively [10.1016/j.apnum.2006.09.010](https://doi.org/10.1016/j.apnum.2006.09.010):

![image](https://github.com/user-attachments/assets/b1918b75-6cf3-48f5-8951-f7baa1627be0)

I did some further testing, and noticed that none of the methods above seem to be able to produce a satisfactory plot of the gradient on a triangular mesh, with piecewise elements. I.e. `-o 0 -r 2`:

<img src="https://github.com/user-attachments/assets/a3ed3d4d-eec8-4c61-8428-1f09ef82f661" height="130" >
<img src="https://github.com/user-attachments/assets/5cf29a26-ab95-4f1c-b92a-22e88d416dad" height="130" >
<img src="https://github.com/user-attachments/assets/fc7ee159-672e-4e37-9ade-6cf69d958b28" height="130" >

With higher order elements the results are better for method 1 and 3. I.e. `-o 2 -r 0`:

<img src="https://github.com/user-attachments/assets/2d17a4b9-f966-4374-b4ce-5fca92ea01fa" height="130" >
<img src="https://github.com/user-attachments/assets/af755bae-8471-4fee-871d-1638415ec998" height="130" >
<img src="https://github.com/user-attachments/assets/70c49a9b-877c-4712-8454-76eb178ad546" height="130" >

None of the methods shows conservation. 

I should mention I keep saying "gradient", but in this case I think I am actually more interested in the flux, because I want to check local and global conservation claims.

In a "real" simulation of the Poisson equation, where we solve for the potential $\phi$, I would be more interested in the electric field $\vec{E}=-\nabla \phi$, which would be input to other physical equations. I wonder how valid it would be to calculate the electric flux $\vec{D}$ first using the expression for the numerical flux you mentioned, and then approximate $\vec{E}=\frac{1}{\epsilon}\vec{D}$. Instead of using the discrete divergence directly for $\vec{E}$, which would be $\vec{0}$ for degree 0 elements.

By the way: the reason I am so interested in piecewise constant $L_2$ elements, is because I want to compare this FEM discretization to an equivalent Finite Volume discretization. Which is, as I understand it, basically the same as a DG formulation with degree 0 elements.

**Comment by pazner** [comment]
FWIW, $p=0$ with IPDG will not generally be convergent (even in $L^2$ norm). You will have to pick the penalty parameter very carefully, and there may be additional restrictions on the mesh. (For $p > 0$, the penalty parameter simply needs to be "sufficiently large", and the mesh can be general). See [this question](https://scicomp.stackexchange.com/questions/35462/p0-elements-for-h1) and the related discussion for more details.

For $p > 0$, basically all of the DG methods (IPDG, LDG, etc.) are conservative in the sense that

$$ \int_{\partial\kappa} \hat{\sigma} \cdot n ~ ds = -\int_{\kappa} f ~ dx $$

for all mesh elements $\kappa$. (If you are seeing problems with conversation in your numerical examples, my guess would be that the way you are computing $\hat{\sigma}$ is not consistent with what is happening inside the DG integrator).

**Comment by Rickbude** [comment]
Hmm in the comments under the very stackexchange post you mentioned, it is said that SIPG, which I suppose is what is used by default in example 14, has convergence of the order $h^{p+1}$. This seems to come from Hartman 2008 [ "Numerical Analysis of Higher Order Discontinuous Galerkin Finite Element Methods"](https://elib.dlr.de/57074/1/Har08b.pdf), eq 264. So then even with $p=0$, first order convergence should be expected, right?

And this is also (I think) what I observe: I do not experience convergence problems in the scalar potential $u_h$ itself with $p=0$, that just works as expected. Only the flux/gradient reconstruction is giving me headaches. 

If the numerical flux is incorrect/inconsistent, what should it be? Note that I am just using the stock example 14: I only added a source in the right-hand side, and I am trying to get a decent approximation of the flux/gradient. So nothing fancy.

**Comment by pazner** [comment]
Indeed the $L^2$ order of convergence for IPDG is $\mathcal{O}(h^{p+1})$. The convergence behavior of various DG methods is summarized in this table:

![image](https://github.com/user-attachments/assets/8c07bebe-70b1-4da2-b6ad-8c53b7a494e5)

However, note that this result holds for $p \geq 1$. The standard reference for these methods is the "unified analysis" paper referenced earlier; see the paragraph above equation (1.2) for the statement of the condition that $p \geq 1$.

The $L^2$ error estimates are derived using the standard duality argument ("Nitsche's trick"), as described in the beginning of section 5.1 of the paper. This argument requires that the piecewise linear interpolant of the true solution lies in the finite element space. For $p = 0$ DG this is not the case, and the argument doesn't go through.

To see an example of lack of convergence, simply change the kappa (penalty parameter) value — by default, MFEM sets $\kappa = (p+1)^2$, so when $p = 0$, $\kappa = 1$. If you override this choice, you should see lack of convergence. (Write out the method in 1D and you will see that it does not make sense except for specially chosen $\kappa$ to recover a finite volume-type method).

**Comment by pazner** [comment]
Closing for now. @Rickbude, please re-open if you have any other questions.
