### ISSUE TITLE
EliminateEssentialBC for shared dofs at vertices

### ISSUE THREAD

**Issue by kvoronin** [mfem/mfem#454]
Hello,

I've got a question on eliminating of essential boundary conditions for linear H1 finite element space.
```
      Cblock = new ParBilinearForm(linearH1_space);
      Cblock->AddDomainIntegrator(new MassIntegrator);
      Cblock->Assemble();
      Cblock->EliminateEssentialBC(ess_bdr, some_x, some_rhs);
      Cblock->Finalize();
      C = Cblock->ParallelAssemble();
```
gives for some (I assume, shared) tdofs diagonal elements in C which equals 2, not 1, when I am using 2 parallel processes. In general, it would give #processes-which-share-this-vertex(=dof). Is this a planned behavior? 

Thanks,
Kirill

**Comment by tzanio** [comment]
Yes, in this case that is expected -- `EliminateEssentialBC` put one on the diagonal in each processor, and `EliminateEssentialBC` will add those together for the Dirichlet dofs that are shared. The same happens with the assembly of the r.h.s, so those particular Dirichlet constraint equations are just rescaled.

This is automatically handled by the `FormLinearSystem` interface.
