### ISSUE TITLE
How to multiply a H1 GridFunction by a PWConstantCoefficient

### ISSUE THREAD

**Issue by denislachapelle** [mfem/mfem#4543]
I have a H1 finite element space GridFunction which one I want to multiply by a PWConstantCoefficient. I can't figure how to do this. I include below some code snippet to show what are the space, coefficient and gridfunction.

I would like to do something like this

u = u * (*c_);

Thank you for your help.
Denis

FiniteElementCollection *fec = NULL;
fec = new H1_FECollection(order, dim);
FiniteElementSpace *fespace = new FiniteElementSpace(mesh, fec);

PWConstCoefficient *c_ = new PWConstCoefficient;
   {
      double CoeffArray[]={0.0, omega_*sigma_, omega_*sigma_, 0.0};
      Vector CoeffVector(CoeffArray, 4);
      c_->UpdateConstants(CoeffVector);
   }

ComplexGridFunction u(fespace);

**Comment by pazner** [comment]
If $u \in H^1$ and $c \in L^2$, then you have for the product $(uc) \not\in H^1$.

You could represent the product in a DG space, or do something like nodal interpolation or $L^2$ projection. What are you trying to achieve?

**Comment by denislachapelle** [comment]
I wrote a program to compute the current density in a pair of wires carrying AC current. The goal is to compute the proximity effect causing current density to move away.

-1/u Div(grad(Az)) + i w s Az - e w^2 Az = J0z
Jinduced = -i w s Az
Jtot = J0 + Jinduced, note J0 is real, Jind is imaginary (90 degree)

u: permeability.
e: permitivity.
s: conductivity.
i: sqrt(-1)

I have computed the magnetic vector potential (A) caused by a current density (J) in a conducting section of the domain. From A the E-field is computed and then the induced current density by multiplying by the conductivity. So A is a GridFunction and the conductivity is a PWConstantCoefficient.

Can you explain a little bit more "DG space, or do something like nodal interpolation or L2  projection"

Thank you,
Denis

**Comment by pazner** [comment]
Given your grid function $A$, you can create a `GridFunctionCoefficient`, and then form a `ProductCoefficient` to represent the product $s A$.

This function can be represented in the DG space of the same order as your H1 space. If you create a DG space and grid function, you can use `GridFunction::ProjectCoefficient` with the `ProductCoefficient` described above to obtain a grid function that represents $sA$.

**Comment by denislachapelle** [comment]
Thank you very much @pazner for your help. Based on your guidance I wrote the following code and it works very well.

Note that u is a ComplexGridFunction.

   GridFunctionCoefficient ACoeffReal(&(u.real())), ACoeffImag(&(u.imag()));
   ProductCoefficient ProdCoeffReal(ACoeffImag, *c_);
   ProductCoefficient ProdCoeffImag(ACoeffReal, *negc_);
   
   FiniteElementCollection *JIndFec = NULL;
   JIndFec = new DG_FECollection(order, dim);
   FiniteElementSpace *JIndFESpace = new FiniteElementSpace(mesh, fec);

   GridFunction JIndGridFunctionReal(JIndFESpace), JIndGridFunctionImag(JIndFESpace);
   JIndGridFunctionReal.ProjectCoefficient(ProdCoeffReal);
   JIndGridFunctionImag.ProjectCoefficient(ProdCoeffImag);

**Comment by pazner** [comment]
Glad it works! Closing for now, feel free to re-open if you have further questions.
