### ISSUE TITLE
Issue with visualizing prisms in Visit (3.3.1)

### ISSUE THREAD

**Issue by christinamigliore** [mfem/mfem#4547]
Hello, I have been running into an issue of visualizing results from the Stix miniapp, found on the branch dh-sheath-bc-dev (stix3d_dh), within Visit. The output from Stix is a 2D mesh that is extruded out into a third direction. Using quads, I haven't had any issues with visit but I tried running a purely triangular mesh (prisms in 3D) and visit instantly crashes with the following attached error. I should note that Glvis works with the triangular solution.
[visit_error.txt](https://github.com/user-attachments/files/17511697/visit_error.txt)

**Comment by mlstowell** [comment]
I was able to reproduce this error in the master branch of MFEM without much of the specialized context that @christinamigliore is using.

To reproduce this open `data/ref-prism.mesh` using `miniapps/meshing/mesh-explorer`. The mesh should of course display correctly and it does. Then use `mesh-explorer` to save the mesh as a Visit Data Collection (keystrokes 'D' followed by 'v'). The resulting data collection cannot be used to display the mesh in VisIt.

@acfisher, I'm not sure where to look next. I would guess it's either the version of MFEM that VisIt is being built with or something in the way VisIt is calling MFEM when it encounters wedge elements.

**Comment by tzanio** [comment]
ping: @cyrush

**Comment by cyrush** [comment]
@mlstowell can you provide the output file you saved from mesh explorer? Then I can test with newer VisIt and debug if necessary.

VisIt 3.3.1 is from 2022, so it is certainty using an older version of mfem.

**Comment by mlstowell** [comment]
Thanks @cyrush! 
[mesh-explorer.tar.gz](https://github.com/user-attachments/files/17528146/mesh-explorer.tar.gz)

**Comment by cyrush** [comment]
@mlstowell thanks, confirming that I can replicate.

**Comment by cyrush** [comment]
@mlstowell -- found the solution, we need to add logic for wedges (aka prisms) to the VisIt plugin.

I also tried adding a case for pyramids, but I saw a crash in MFEM LOR.

Just to make sure I don't have bad example data, can you make me a mesh with a pyramid?

**Comment by cyrush** [comment]
Here is my hand coded example, but if there are any specific ordering constrains (especially with respect to the boundary) I doubt I was lucky enough to get it right:

```
MFEM mesh v1.0

#
# MFEM Geometry Types (see fem/geom.hpp):
#
# POINT       = 0
# SEGMENT     = 1
# TRIANGLE    = 2
# SQUARE      = 3
# TETRAHEDRON = 4
# CUBE        = 5
# PRISM       = 6
# PYRAMID     = 7
#

dimension
3

elements
1
1 7 0 1 2 3 4

boundary
5
1 2 0 1 4
2 2 1 2 4
3 2 2 3 4
4 2 0 3 4
5 3 0 1 2 3

vertices
5
3
0 0 0
1 0 0
0 1 0
1 1 0
0.5 0.5 1
```

**Comment by mlstowell** [comment]
@cyrush, thanks for tracking this down so quickly. We have at least two simple pyramid meshes in the master branch of MFEM. I put together a handful of test meshes containing pyramids. Two of these contain only pyramids the other two have a variety of element types.  
[pyramid-meshes.tar.gz](https://github.com/user-attachments/files/17549775/pyramid-meshes.tar.gz)

**Comment by cyrush** [comment]
@mlstowell thank you

For the Pyramid cases, I am getting a crash when I try to create a refined mesh,

```
1          0x109e25830 mfem::Mesh::MakeRefined(mfem::Mesh&, int, int) + 212
0          0x109e26458 mfem::Mesh::MakeRefined_(mfem::Mesh&, mfem::Array<int>, int) + 2896
```

We are using MFEM 4.6, any chance that 4.7 has improvements related to Pyramid support?

**Comment by mlstowell** [comment]
@cyrush, I should have mentioned there are still limitations to the pyramid support. I would not expect refinement to work.

**Comment by cyrush** [comment]
Thanks -- I will add support for wedges and provide an error message for the pyramid cases for now.

**Comment by mlstowell** [comment]
Thanks again @cyrush. I appreciate your efforts on this.

**Comment by christinamigliore** [comment]
Thank you both, @cyrush and @mlstowell for your help on this!

**Comment by acfisher** [comment]
For future testing I put together a minimal mesh with all of the element types in 3D.  You can find it in the mfem repo data/tinyzoo-3d.mesh.
