### ISSUE TITLE
Fail to build examples using CUDA version mfem

### ISSUE THREAD

**Issue by ErikQ97** [mfem/mfem#4549]
Hi there,

I just installed cuda version mfem with the instructions on the website, specifically the installed version is:

mfem-4.7, hypre-2.31.0 (all cuda version), metis-5.1.0, glvis-4.3.2

However, when I tried to build ex1p, I got following error:

nvcc  -O3 -std=c++11 -x=cu --expt-extended-lambda -arch=sm_89 -ccbin mpicxx -I.. -I../../hypre/src/hypre/include ex1p.cpp -o ex1p -L.. -lmfem -L../../hypre/src/hypre/lib -lHYPRE -lcusparse -lcurand -lcublas -L../../metis-4.0 -lmetis -lcusparse -lrt
/usr/bin/ld: cannot find -lmetis: No such file or directory
collect2: error: ld returned 1 exit status
make: *** [makefile:87: ex1p] Error 1

It seems that there is something wrong with metis, however, what I installed is metis-5.1.0 rather than the metis-4.0 shown in the error message. 

Kindly let me know if you have any ideas about that.

Thank you!

**Comment by artv3** [comment]
I think you may just have change your link like from ``-L../../metis-4.0 `` to ``-L../../metis-5.1.0``

**Comment by ErikQ97** [comment]
Thanks for your hints! 
I think my compiling issue is fixed by 

`make pcuda CUDA_ARCH=sm_89 -j8 MFEM_USE_METIS_5=YES METIS_DIR=@MFEM_DIR@/../metis-5.1.0`

The metis version and direction should be specified during the installing process.
