### ISSUE TITLE
Fail to build examples using METIS

### ISSUE THREAD

**Issue by wonengkanjiannideyanjing** [mfem/mfem#4552]
When I built mfem I used the following command: ~> cd mfem-4.5
~/mfem-4.5> make parallel -j MFEM_USE_METIS_5=YES METIS_DIR=@MFEM_DIR@/../metis-5.1.0 but something went wrong
![图片1](https://github.com/user-attachments/assets/8e5d479c-03cb-4007-a52f-7a24a44c70ce).please how can i solve it

**Comment by vladotomov** [comment]
Did you download METIS from `https://github.com/mfem/tpls`?

You could also try 4.0.3, that's usually less sensitive.

**Comment by v-dobrev** [comment]
Also, you seem to be mixing the build systems: `make parallel ...` is a command for the GNU make build system, however, your screenshot shows output from using CMake. If you built MFEM with `make parallel ...` then to build `ex0`, just use `make ex0` in the `examples` directory.

**Comment by wonengkanjiannideyanjing** [comment]
thanks @v-dobrev
