### ISSUE TITLE
Essential dofs

### ISSUE THREAD

**Issue by Dan2997925** [mfem/mfem#456]
What is the difference between GetEssentialVDofs and GetEssentialTrueDofs? 

I have an H(curl) gridfunction and I want to set all the boundary dofs to be zero. Which of these functions should I use to get the correct dofs?

Note that in serial, on a conforming mesh, I expected these functions to give the same dofs but they don't.

**Comment by v-dobrev** [comment]
The first method returns a marker (boolean) array, i.e. an array that says, for each vdof, if it is essential or not - I think we use -1 as the "true" value. The second one returns an array that lists all essential true dof indices, i.e. the array in this case will be smaller and contain numbers between 0 and the number of (local) essential true dofs minus 1.

If you want to use the result in a method like FormLinearSystem, you need to use the second one.

On the other hand, a GridFunction has the size of the array returned by the first method, so to initialize a GridFunction with zero b.c. you should use the first method, loop over all entries and set to 0 the GridFunction entries that are marked as true.

**Comment by Dan2997925** [comment]
OK thanks, I think I was using get EssentialVDofs incorrectly.
