### ISSUE TITLE
Integration of a scalar Coefficient over a 2D domain

### ISSUE THREAD

**Issue by denislachapelle** [mfem/mfem#4563]
I have a Coefficient which is a scalar over a 2D domain. I wrote some code to integrate the scalar over selected area identified by an attributes. I wrote two functions and each seems to work fine, they gave the same results. I would like to understand why the second one work fine, I was thinking that the test function will be involved and provide different result.

A confused Denis !!!

```c++
double IntScalar1(FiniteElementSpace &fes, Coefficient &coeff, int Attr)
{
   // Integrate the scalar function over the entire domain manually
   double integral_value = 0.0;
   for (int i = 0; i < fes.GetMesh()->GetNE(); i++)  // Loop over elements
   {
      
      if(fes.GetAttribute(i) == Attr)
      {   
       ElementTransformation *trans = fes.GetMesh()->GetElementTransformation(i);
       const FiniteElement &fe = *(fes.GetFE(i));

       // Use a quadrature rule that matches the element's order
       const IntegrationRule &ir = IntRules.Get(fe.GetGeomType(), 2 * fe.GetOrder());

       for (int j = 0; j < ir.GetNPoints(); j++)  // Loop over quadrature points
       {
           const IntegrationPoint &ip = ir.IntPoint(j);
           trans->SetIntPoint(&ip);

           // Evaluate scalar function at the quadrature point in physical coordinates
           double scalar_value = coeff.Eval(*trans, ip);

           // Accumulate the integral (scalar value * weight * Jacobian determinant)
           integral_value += scalar_value * ip.weight * trans->Weight();
       }
   }
   }
   return integral_value;
}
```

```c++
double IntScalar2(FiniteElementSpace &fes, Coefficient &coeff, int Attr)
{
   double integral_value = 0.0;
   int NbrOfAttributes= fes.GetMesh()->attributes.Max();
   if (NbrOfAttributes>0 && Attr<=NbrOfAttributes)
   {
      Array<int> Marker(NbrOfAttributes);
      Marker=0;
      Marker[Attr-1] = 1;

      LinearForm lf(&fes);
      lf.AddDomainIntegrator(new DomainLFIntegrator(coeff), Marker);
      lf.Assemble();
      integral_value= lf.Sum(); // * gf; // dot product product operator of Vector class.
   }
   return integral_value;
}
```

**Comment by pazner** [comment]
Hi @denislachapelle,

The basis functions $\phi_i$ have the property that $\sum_{i=1}^N \phi_i \equiv 1$. Your second code constructs the linear form that is represented by the vector $\int_\Omega f \phi_i ~ dx$, where $f$ is your coefficient. If you sum the entries, you can compute

$$
\sum_{i=1}^N \int_\Omega f \phi_i ~dx = \int_\Omega f  \left(\sum_{i=1}^N \phi_i\right) ~dx = \int_\Omega f ~ dx
$$

and you get the desired result.

**Comment by denislachapelle** [comment]
Thank you for your explanation, I will finish one day to be enlightened !!!

I suspect the more efficient and elegant is the second one using the LinearForm?

**Comment by pazner** [comment]
The second is perhaps more elegant (that may be subjective...), but both versions should be roughly equally efficient (the second actually requires $\mathcal{O}(N)$ storage for the vector whereas the first is $\mathcal{O}(1)$, but this is likely unimportant). The first one also skips entirely elements with different attributes.

You can also try doing this:

```c++
QuadratureSpace qs(fes.GetMesh(), 2*fes.GetMaxElementOrder());
Array<int> attrs(1);
attrs[0] = Attr;
RestrictedCoefficient restr_coeff(coeff, attrs);
return qs.Integrate(restr_coeff);
```

**Comment by denislachapelle** [comment]
I try this code ..

double IntScalar3(FiniteElementSpace &fes, Coefficient &coeff, int Attr)
{
   QuadratureSpace qs(fes.GetMesh(), 2*fes.GetMaxElementOrder());
   Array<int> attrs(2); attrs=0;
   assert(fes.GetMesh()->attributes.Max() >= Attr);
   attrs[0] = Attr;
   RestrictedCoefficient restr_coeff(coeff, attrs);
   return qs.Integrate(restr_coeff);
}

and it fail with this message when qs.Integrate is called.

Assertion failed: (i>=0 && i<size) is false:
 --> Access element 2 of array, size = 2
 ... in function: T& mfem::Array<T>::operator[](int) [with T = int]
 ... in file: /mnt/c/mfem-4.7/general/array.hpp:755

But its ok since I will use IntScalar1 previously discussed above.

**Comment by pazner** [comment]
Can you try this version? I made a mistake in the definition of `attrs`.

```c++
real_t IntScalar3(FiniteElementSpace &fes, Coefficient &coeff, int Attr)
{
   QuadratureSpace qs(fes.GetMesh(), 2*fes.GetMaxElementOrder());
   Array<int> attrs;
   if (fes.GetMesh()->attributes.Size())
   {
      attrs.SetSize(fes.GetMesh()->attributes.Max());
      attrs[Attr-1] = 1;
   }
   RestrictedCoefficient restr_coeff(coeff, attrs);
   return qs.Integrate(restr_coeff);
}
```

**Comment by denislachapelle** [comment]
I tried it and the compilation works fine but the result is near zero (E-19) while the result shall be about 0.000798. Up to you if you want to look at the details the entire file is available here: https://github.com/denislachapelle/mfemelectrostatic/blob/master/proximity2d_iss4563.cpp

On my side I use mfem-4.7 on WSL under Windows 10.

Thank you.

**Comment by pazner** [comment]
Can you share the mesh file too? (I see there are Python scripts to generate the meshes, but it will be easier with the actual .msh file).

**Comment by denislachapelle** [comment]
Here is the mesh file
https://github.com/denislachapelle/mfemelectrostatic/blob/master/mesh/proxroundroundwires2d.msh

and here is the python script generating the mesh file using gmsh api.
https://github.com/denislachapelle/mfemelectrostatic/blob/master/mesh/ProxRoundRoundWires2d.py

and the command is 
./proximity2d -m mesh/proxroundroundwires2d.msh -f 50.35 -o 1 -nd

Denis

**Comment by pazner** [comment]
Sorry, the code I posted had a small bug. I updated it so it should be correct now.

The line

```c++
attrs=0;
```

should come _after_ the line

```c++
attrs.SetSize(fes.GetMesh()->attributes.Max());
```

**Comment by denislachapelle** [comment]
Great it work just fine now.

**Comment by pazner** [comment]
Closing for now. Please re-open if you have other questions.
