### ISSUE TITLE
Question: how to build a multi-refinement operator?

### ISSUE THREAD

**Issue by tepperly** [mfem/mfem#4565]
In the LiDO design optimization suite, we are investigating adding a new adaptive mesh refinement capability. In this context, we start out with a design mesh that remains constant. The true DOFs of a ParGridFunction on the design mesh are the decision variables for a nonlinear program, and the number of decision variables cannot change while the nonlinear program is being solved.

We also have an analysis mesh that starts out as a copy/clone of the design mesh. As the LiDO nonlinear program algorithm progresses, it may refine or derefine the analysis mesh. mfem provides a variety of capabilities to update a ParGridFunction from pre-refinement to post-refinement, and you can get a pointer to an mfem::Operator from the FiniteElementSpace to perform one refinement or derefinement.

To support LiDO's AMR approach, I would like to be able to construct/maintain something that can convert back and forth between a ParGridFunction/ParLinearForm on the design mesh and the corresponding type on the analysis mesh. One idea would be to keep a list of individual update operators, but I don't believe I can create an independent copy (that LiDO owns) of the refinement operators. Presumably, it could get big from a memory perspective.

Is there a good way to construct an operator (or something else) that can convert a ParGridFunction on the design mesh to a ParGridFunction on the analysis mesh where the analysis mesh is refined an arbitrary number of times?

**Comment by v-dobrev** [comment]
In the method `ParFiniteElementSpace::GetTrueTransferOperator`, you can set the type of the `OperatorHandle &` parameter to be `Operator::Hypre_ParCSR` before you call `GetTrueTransferOperator` -- this type is used as an input. The result, stored in the `OperatorHandle &`, will be a `HypreParMatrix *` which will be owned by the `OperatorHandle` -- you can double-check the ownership with `OperatorHandle::OwnsOperator()`. If you save all these `HypreParMatrix`es, then you can use them to transfer true-dof vectors from the design mesh to the analysis mesh. Note that these matrices will need to include the transfer matrices for all refinement, re-balancing, and de-refinement operations on the mesh. It should be possible to multiply these matrices (e.g. using `mfem::ParMult` for `HypreParMatrix`es) and store just the last product -- this may help with the memory footprint to some extend.

For transferring primal true-dof vectors from the analysis mesh to the design mesh, one option is to use an L2 projection operator, which will require a mass matrix solve on the design mesh. The r.h.s. for this solve will be `P_{hH}^t M_h f_h`, where `f_h` is the primal true-dof vector on the fine (analysis) mesh, `M_h` is the mass matrix for the FE space of `f_h`, and `P_{hH}` is the product of all transfer operators described in the previous paragraph -- note that this matrix also depends on the FE space for `f_h`. Instead of assembling `M_h`, one can compute the product `M_h f_h` using a `ParLinearForm` with the appropriate `LinearFormIntegrator`, e.g. `DomainLFIntegrator` for scalar H1 and L2 spaces.

**Comment by tepperly** [comment]
Thanks! I would need to get and store this operator for each individual refinement/derefinement, right?

**Comment by v-dobrev** [comment]
> Thanks! I would need to get and store this operator for each individual refinement/derefinement, right?

Yes. In addition you need to also include the transfer operators after re-balancing, if you are doing re-balancing.

Also, if you are forming the product (composition) of all these matrices (as suggested above), then you don't need to keep the individual matrices -- just the latest product.

**Comment by tepperly** [comment]
It appears that GetTrueTransferOperator does not return a rebalancing matrix.  Looking at the API documentation, it's not clear how I can get a rebalancing matrix that I can multiplier the refine/define matrices in the approach defined above.  The ParFiniteElementSpace::RebalanceMatrix() method is private.

**Comment by v-dobrev** [comment]
I'm sorry, you are right -- `GetTrueTransferOperator` does not handle derefinement and rebalancing, just refinement.

The method that handles all cases (refinement, derefinement, rebalancing) is `ParFiniteElementSpace::Update(bool)` -- this constructs the "update operator", an `Operator` that is stored internally by the `ParFiniteElementSpace`. The update operator can be accessed using one of the methods:
* `const Operator* GetUpdateOperator()` -- it calls `Update(true)`, so `Update` does not need to be called in advance.
* `void GetUpdateOperator(OperatorHandle &T)` -- it does NOT call `Update`, so it must be called in advance.

Note that, the update operator maps primal L-vector (in the FE space before the update) to primal L-vector (in the FE space after the update), i.e. `ParGridFunction`-size to `ParGridFunction`-size `Vector`s.

Depending on the last mesh operation (returned by `mesh->GetLastOperation()`), the type of the update operator is different (this info is as of 11/11/2024 and may change in the future):
* after refinement, the update operator type is either "matrix free" (type `FiniteElementSpace::RefinementOperator`) or `SparseMatrix`; the type is `SparseMatrix` if the FE space method `SetUpdateOperatorType(Operator::Type tid)` is called with parameter `Operator::MFEM_SPARSEMAT` before calling `Update`.
* after derefinement (non-conforming mesh), the update operator is "matrix free" (type `TripleProductOperator`); the three `Operator`s in this triple product are `HypreParMatrix`, `SparseMatrix`, `HypreParMatrix`, so in principle it is possible to multiply them to get a single `HypreParMatrix`.
* after rebalancing (non-conforming mesh), the update operator is a `HypreParMatrix`.

Overall, all the needed operators are available in some form, however, this form may not be the most convenient for what you want to do. Maybe we can add a new method, e.g. `GetTrueUpdateOperator`, that will return the update operators as `HypreParMatrix` that can then be easily multiplied after mesh operations (refinement, derefinement, rebalancing) as I was suggesting before. What do you think?

**Comment by tepperly** [comment]
In looking at the documentation of TripleProductOperator, it seems that the public API doesn't let me get out the three matrix operators, so as a mfem client, I can't really multiply them to get a single operator. It also looks like I can't make a independent copy (i.e., that owns all it's own memory) to maintain a list of Operator's that I can apply in a chain.

I also have not been able to find a public method that multiplies a SparseMatrix by a HypreParMatrix to produce a HypreParMatrix, and this would also be necessary to implement the approach in your latest comment.

Your comment also suggests that the suggested approach is based on internal implementation details that could change without notice suggests that it would be better to have a new public method to return an update matrix in a consistent form regardless of the type of mesh update. We would want something that can return a matrix that LiDO multiply with a HypreParMatrix to produce a HypreParMatrix that LiDO owns in a memory sense.

Getting something like this into an mfem release is likely to take months, right?

**Comment by tepperly** [comment]
I looked over PR #4601, and it looks good. Thanks! I particularly like the amount of documentation for the `ParFiniteElement::GetTrueUpdateOperator` method and how it's explicit about the return value in case of an error.

**Comment by tepperly** [comment]
It's my goal to try this out today.

**Comment by tepperly** [comment]
I was able to build LiDO against the branch for PR #4601 . There were some warnings about deprecated methods unrelated to your change. In the first call to `mfem::ParFiniteElementSpace::GetTrueUpdateOperator`, I get this `MPI_Abort`.
```
(gdb) cont
Continuing.


Verification failed: (Tsm != nullptr) is false:
 --> invalid update (refine) operator type!
 ... in function: void mfem::ParFiniteElementSpace::GetTrueUpdateOperator(OperatorHandle &)
 ... in file: /home/epperly2/current/lido/lido-2.0/smith/serac/mfem/fem/pfespace.cpp:3574


Thread 1 "FieldRefinement" hit Breakpoint 1, 0x00007ffff46d7b98 in PMPI_Abort () from /usr/lib64/mpich/lib/libmpi.so.12
(gdb) 
```

I'm not sure if this is enough to indicate what's going on to you, so here is some more information from my run. I am running a single rank. Here is where the error occurs and the value of Th.
```
(gdb) list
3568	      case Mesh::REFINE:
3569	      {
3570	         if (T.Type() == Operator::Hypre_ParCSR)
3571	         {
3572	            SparseMatrix *Tsm = Th.Is<SparseMatrix>();
3573	            MFEM_VERIFY(Tsm != nullptr,
3574	                        "invalid update (refine) operator type!");
3575	            // Form the product: R_new . Tsm . P_old:
3576	            std::unique_ptr<SparseMatrix> R_T(
3577	               mfem::Mult(*GetRestrictionMatrix(), *Tsm));
(gdb) print Th
$1 = {static not_supported_msg = 0x154d410 <mfem::OperatorHandle::not_supported_msg> "Operator::Type is not supported: type_id = ", 
  oper = 0x0, type_id = mfem::Operator::MFEM_SPARSEMAT, own_oper = false}
(gdb) 
```
Here are the `mfem` methods that I called to make the mesh refinement and update to the par FE space:
```
(gdb) list
81	  input.assignAllValues(0);
82	  EXPECT_NO_THROW(mc->getTypedValue(input, output));
83	  EXPECT_EQ(input.Size(), output.Size());
84	  dataManager.getMesh("analysis_mesh").UniformRefinement();
85	  dataManager.getSpace("analysis_mesh", collectionName, "analysis_space").Update();
86	  EXPECT_NO_THROW(mc->getTypedValue(input, output));
87	  EXPECT_LT(input.Size(), output.Size());
88	  EXPECT_EQ(input.Size(), designSize);
89	  VariableSet vs(MPI_COMM_WORLD, designTrueSize, "x");
90	  auto vso(::std::make_unique<VariableSetOperator>(vs));
(gdb) 
```
In particular, lines 84-85 show the mesh refinement and the request to update the ParFESpace for that refinement. Line 86 is where the LiDO code calls GetTrueUpdateOperator.

Is this information enough to indicate the issue to you, or do I need to dig more at my end.

For the sake of complete feedback, the only changes I needed to make were replacing the call to `GetTrueTransferOperator` with a call to `GetTrueUpdateOperator` and remove `const` from the `mfem::ParFiniteElementSpace&` that `GetTrueUpdateOperator` is called on because it's not a `const` method.

**Comment by v-dobrev** [comment]
One issue that I see is that it seems like you are calling `ParFiniteElementSpace::Update` before the call to `ParFiniteElementSpace::GetTrueUpdateOperator` and this is not allowed -- this is the first note in the doxygen comments of `GetTrueUpdateOperator`.

However, I'm not sure this explains why `Th` holds `NULL` inside the call to `GetTrueUpdateOperator` when the `MFEM_VERIFY` fails -- when `Update(true)` is called earlier in `GetTrueUpdateOperator`, it is supposed to construct `Th`. In the debugger, can you step inside the `Update(true)` call and see why `Th` is not constructed?

**Comment by tepperly** [comment]
I used a ParFiniteElementSpace object that hadn't been updated, and MPI_Abort went away.

**Comment by tepperly** [comment]
I've tested refinement and rebalancing, and they pass the "eyeball norm" test. Visit rendering of the original mesh and the values on the successively refined meshes look identical. I haven't made a derefinement yet.
