### ISSUE TITLE
Basis function for nodes?

### ISSUE THREAD

**Issue by jayjaybillings** [mfem/mfem#457]
I'm looking for an efficient way to get the value of a basis function at each individual node on a mesh. I'm computing a quantity like so
```
a = \sum_{i=1}^{n} a_{i}(t) N_{i}(x)
```
where N represents the nodal basis functions evaluated at 3D point x.

For any given FiniteElement in MFEM, I can call element.CalcShape(...) to get the value of the functions across the element, but is there a simple way to get the nodal basis functions? What I would like to do is something like
```
feSpace.getNode(i).CalcShape(x)
```
or
```
feSpace.getShapeAtNode(i,x)
```

Any suggestions? Thanks in advance!

**Comment by v-dobrev** [comment]
How is the point `x` given? Do you know the element it belongs to and the reference coordinates?

If you do and you compute `a_{i}(t)` for a given `t` and initialize the entries of a `GridFunction` with those values, then you can call the method `GridFunction::GetValue(j, ip)` where `j` is the index of the element that contains `x` and `ip` is the `IntegrationPoint` that specifies the reference coordinates of `x`.

If you just have the physical coordinates of `x` you will need to call something like `Mesh::FindPoints(...)` first.

**Comment by jayjaybillings** [comment]
Thanks @v-dobrev! What's the difference between GridFunction.GetValue() and GridFunction.GetNodalValues()?

**Comment by v-dobrev** [comment]
There are two versions of `GetNodalValues` - one that works for one element and a second one that works with the whole mesh. Both return the values of a GridFunction at the vertices of the mesh. The global one will also perform averaging in the vertices when the GridFunction is not continuous.

On the other hand, `GetValue` works for any point inside a single element.

**Comment by jayjaybillings** [comment]
Very good to know. Thanks @v-dobrev. 

If I understand this correctly, ```GridFunction.CalcShape()``` will give me the total shape function for the element for a point x. What if I want it for the shape function due to only one node? Let's say I have a 1D element with nodes ```i``` and ```j``` on the left and right, and nodal basis functions ```N_{i}(x)``` and ```N_{j}(x)```. Is it possible to compute only ```N_{i}(x)```, for example?

Forgive me if I'm unclear or not keeping up. Still learning MFEM (and loving it!).

**Comment by jayjaybillings** [comment]
Thanks @tzanio. I'll take a look at the mini-app and review this some more.

Yeah, it is a little weird. I'm using MFEM to build a Material Point Method code and I need the values of the nodal basis functions to create the matrix that maps particle positions to nodal basis function values at those positions.

I really appreciate the help from you and @v-dobrev! More soon.

**Comment by jayjaybillings** [comment]
I just had a chance to look at this. I think I misread the documentation for ```fe.CalcShape(...)```. That function computes the all the shapes at ip, which is what I need. GridFunction uses this to retrieve the shapes and then computes the inner product of the two vectors for the element. Does that sound correct?

**Comment by v-dobrev** [comment]
Yes, that is correct.

**Comment by tzanio** [comment]
@jayjaybillings were you able to make progress on this? Do you have any additional questions?

**Comment by jayjaybillings** [comment]
@tzanio Thanks for closing and following up. Apologies for now responding sooner. 

I do not have any additional questions. I think this works for me.

**Comment by tzanio** [comment]
Feel free to reopen anytime :)
