### ISSUE TITLE
Curvilinear edge of high-order mesh is not shown in Glvis

### ISSUE THREAD

**Issue by Wayne901** [mfem/mfem#4577]
For the following geometry (meshed in Cubit with HEX27), I set Sideset 1 on the surface with circule rings (`fig1`), as well Sideset 2 on all exterior boundaries.
I read the `fss_ring_3x8_testCubitBC.e` mesh, saved as 'mesh' as in `ex1p`, and opened 'mesh' file with `glvis`. All the boundaries are linear, not curved (`fig2`).
I thought they are linear mesh, but after I refined the 'mesh' 1 time and opened it again with 'glvis', the edges are refined as a high-order mesh(`fig3`). 
Fig1:
![fss_pec](https://github.com/user-attachments/assets/e2b63322-977d-423e-afbe-ee2e564aed0e)
Fig2:
![mesh_initial](https://github.com/user-attachments/assets/4ccb8897-5c0f-487d-af0a-cbca136e7e31)
Fig3:
![mesh_refined](https://github.com/user-attachments/assets/dc969883-74d1-4fe0-b343-1029b1320885)
Another strange case is, when sidesets are set only on interior surface, not exterior surfaces, the unrefined mesh opened by `glvis` becomes curved. I tried different cases but when exterior surfaces are labeled as boundaries, mesh opened by `glvis` becomes linear:
![mesh_with_no_exterior_boundaries](https://github.com/user-attachments/assets/6c03f5e9-43cd-4a40-8701-be48b5fa2cc8)
I'm using mfem 4.6 (paralleled), glvis 4.2, 1 core. Could this be a bug of `glvis` or Cubit?
Mesh files:
[mesh.zip](https://github.com/user-attachments/files/17687194/mesh.zip)

**Comment by tzanio** [comment]
This may be due to the default level of refinement in GLVis: can you try pressing `o` in the GLVis window?

We improved that in glvis-4.3 which may work correctly for you out of the box.

**Comment by Wayne901** [comment]
Yeah that's exactly the reason. Glvis' default subdivison factor is 3 when boundary sets are small, and is 1 when boundary sets are big. It's merely a visualization problem.
