### ISSUE TITLE
How to enable vectorization on HPC

### ISSUE THREAD

**Issue by Wayne901** [mfem/mfem#4580]
I'm running the partial assembled code on a platform with `avx512` architecture. However the speed is same as on my vmware.
I did following things:
1. build mfem with `cmake -DCMAKE_C_FLAGS="-march=native" -DCMAKE_CXX_FLAGS="-march=native"`  
2. set `option(MFEM_USE_SIMD "Enable use of SIMD intrinsics" ON)` in `user.cmake`. 
3. for my .cpp code, add `target_compile_options(${PROJECT_NAME} PUBLIC "-march=native")` in the CMakeLists.txt.

Am I missing something to run partial assembly code with vectorization?

**Comment by Wayne901** [comment]
Well the `mfem` on server has ___AVX512F__ defined ...
Is vectorization enabled only through `TBilinearForm` as in performance miniapp? I thought it's enabled by default, maybe i misunderstand it

**Comment by v-dobrev** [comment]
Yes, the SIMD vectorization is explicitly used in MFEM only in the `TBilinearForm` and the template classes it is based on -- this is demonstrated in `miniapps/performance` examples.

**Comment by v-dobrev** [comment]
Can you compare the actual compile commands used to build the two executables? You can get these commands if you enable verbose output when running `make` by adding the flag `VERBOSE=1`, e.g. `make VERBOSE=1 exec -j 4` when building MFEM with all example+miniapps+tests.

**Comment by Wayne901** [comment]
After comparing the g++ compilation, I found mine is missing `-O3` flag. 
This problem is addressed by running cmake with
`cmake -DCMAKE_BUILD_TYPE=Release ../source` option or adding
`set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O3")` in `CMakeLists.txt` and run `cmake ../source`.
I only run cmake without the release flags and it's good for other examples. `performance` miniapss must set it explicitly.

Thank you @v-dobrev sincerely, you help me so much.

**Comment by Wayne901** [comment]
I did a more detalied runtime comparison. The server has a lower cpu frequency so it's slower in most cases, but somehow it's faster for non-optimized matrix-free case. Besides, the vectorization with 8 doubles is slower than expected. Any hint about that?
![vectorization_time](https://github.com/user-attachments/assets/d62be672-6cbd-40f5-9979-ac42bcdcc4d1)

**Comment by v-dobrev** [comment]
When you are building your test code and you have `MFEM_USE_SIMD=NO` (I suspect this is the case that you call "1 double"), do you have the compiler flags `-O3`, `-march=native`, and `--param max-completely-peel-times=3`? If you do, the compiler will still try to auto-vectorize the code and can do pretty well. That's probably why this case is not as slow as you might expect.

You can try removing `-march=native` and `--param max-completely-peel-times=3` and see what the effect is. Even without these options, the compiler may still generate some vectorized code but I'm not sure. One has to actually look at the generated code to see if there are any vector (SIMD) instructions.

**Comment by Wayne901** [comment]
I do have those 3 compiler flags even for `MFEM_USE_SIMD=1` case, I'll try removing `-march=native` and `--param max-completely-peel-times=3` then.

But still, the optimized matrix-free code in avx512 is slower than my local computer which only supports 4 double vectorization. Is it reasonable?

**Comment by Wayne901** [comment]
Well I test the result for different compiler flags on CPU architecture, and on different CPUs. Faster runtime on cpu supporting avx512 than avx2 is observed. The only question is the benefit of increasing vectorization from 4 doubles to 8 doubles is not very obvious. I think the DoFs (6.3 million) are not small for 1 process. I really hope to explore the best power of mfem's matrix-free method on our server.
![vectorization2](https://github.com/user-attachments/assets/9c3436ab-0490-4bd4-8fcb-0a7ffc092588)

**Comment by Wayne901** [comment]
There's only H1 and L2 finite elements in `tfe.hpp`. Do `ND` and `RT` elements support vectorization?

**Comment by v-dobrev** [comment]
H(div) and H(curl) support in the templated code is not available in the `master` branch. There is branch that adds such support:: https://github.com/mfem/mfem/tree/pahcurlhdiv-dev. I think it extends the templated code to support `ND` and `RT` elements. However, I'm not sure it is setup to use the SIMD intrinsics classes -- doing that may require some work.

**Comment by Wayne901** [comment]
Got it! Thank you Dobrev.

**Comment by Wayne901** [comment]
Sorry to reopen the issue. Is this content ([GPU supports](https://mfem.org/gpu-support/#:~:text=Maximizing%20the%20main,achieving%20peak%20performance)) related to vectorizations on GPU? Is it supported for Nedelec elements?

**Comment by tzanio** [comment]
Yes, we support Nedelec elements on GPUs. ping: @dylan-copeland
