### ISSUE TITLE
Error building MFEM on Ubuntu 24.04.1

### ISSUE THREAD

**Issue by faizanmohnavi** [mfem/mfem#4587]
It gives the following error:
"
ERROR: Failed building wheel for mfem
Failed to build mfem
ERROR: Could not build wheels for mfem, which is required to install pyproject.toml-based projects
"
Therefore, I tried doing it as it is mentioned on https://github.com/mfem/PyMFEM/blob/master/.github/workflows/release_binary.yml#L10
which gives;
"
../meson.build:85:2: ERROR: Problem encountered: Your Python version is too new. SciPy 1.9 supports Python 3.8-3.11; if you are trying to build from source for the most recent SciPy version you may hit this error as well. Please build from the `main` branch on GitHub instead.
"
What am I doing wrong here? or is it a known issue with MFEM?

**Comment by mdavids-cfs** [comment]
I recommend posting this to the [PyMFEM github](https://github.com/mfem/PyMFEM), if you're trying to build PyMFEM (which compiles MFEM behind the scenes). Also sounds like your python version might be incompatible. I suggest creating a `venv` that uses the right python version as mentioned in the error message, and follow the install instructions in the README.md in the PyMFEM repo
Mathias
