### ISSUE TITLE
Question about calculating the product of piecewise coefficient with a gradient

### ISSUE THREAD

**Issue by emorell96** [mfem/mfem#4593]
Hi,

I am trying to implement a heat loss calculator using MFEM, and I thought everything was going well until I realized that my heat loss values are not realistic or close to the analytical solution.

I am solving for T in - Delta (lambda * T) = 0:

```c++
b = new LinearForm(fe_h1_space);

// set up the equation with no heat generation, i.e. RHS of  - delta (lambda * delta(T)) = 0 is zero.
b->AddDomainIntegrator(new DomainLFIntegrator(zero));

// used for calculating dT
grad = new DiscreteLinearOperator(fe_h1_space , hcurl_dT_space);
grad->AddDomainInterpolator(new GradientInterpolator);

// calculates the heat flux
conductivityMultiplicationForm = new MixedBilinearForm(hcurl_dT_space, flux_hdiv_space);
conductivityMultiplicationForm->AddDomainIntegrator(new VectorFEMassIntegrator(conductivityCoeff)); // conductivityCoeff is a piecewise coefficient.

// LHS
a = new BilinearForm(fe_h1_space);
a->AddDomainIntegrator(new DiffusionIntegrator(conductivityCoeff));


a->Assemble();
b->Assemble();
grad->Assemble();
grad->Finalize();
conductivityMultiplicationForm->Assemble();
conductivityMultiplicationForm->Finalize();
// then I solve with PCG to get T..
// so once T obtained (correctly, T is fine).

grad->Mult(*temperature, *dT); *dT *= -1.0; // we are interested in - conductivity * dT = flux

GridFunction heat_flux(flux_hdiv_space);
// calculate the heat flux
conductivityMultiplicationForm->Mult(*dT, heat_flux);

```

I put this together by kind of adapting the mini volta mini app, specially adapting D, and epsilon.

But the issue I am having is that the heat flux values are all over the place. Indeed to verify the validity of the simulation I ran it with a simple one material case, only one value for lamda, and a simple rectangle of 550mm by 100mm.

Indeed T is fine:
![image](https://github.com/user-attachments/assets/ebab74df-e17e-40c8-87fa-fc00d939fbaf)
as well as dT (the visualization seems to be very zoomed in where I see all the numerical errors) (the analytical value should be 0.2)
![image](https://github.com/user-attachments/assets/b29dd6cf-dc38-4f5f-9b2b-b7ccaec79255)
but the flux (has values all over the place), the value should just be 0.2 multiplied by a constant, which I've set to 1 so that the right norm should be around 0.2 as well.
![image](https://github.com/user-attachments/assets/22767abd-4ff0-4ad8-bede-fb32427477b5)

I don't understand why this is the case, any help with this would be much appreciated. Thank you!

**Comment by pazner** [comment]
Hi @emorell96,

You are attempting to compute the heat flux by multiplying by the conductivity bilinear form. Multiplying by a bilinear form will result in a _dual vector_ (see, for example, the [documentation here](https://mfem.org/pri-dual-vec/)). To recover a primal vector (a grid function), you would need to solve a linear system with the mass matrix.

If you just want to multiply $\nabla T$ by a constant and project onto a grid function, that can more easily be done using a coefficient rather than by solving a variational problem.
