### ISSUE TITLE
How to use `DG_FECollection' on quad mesh with Pk element, not Qk element?

### ISSUE THREAD

**Issue by cglwdm** [mfem/mfem#4594]
As we know that, DG can implement on simplex mesh, quad mesh and other kind of meshes, just using Pk element. For example, when you use P1, you only need 3 dofs on every element, no matter what shape of the element is. However, when I use linine-quad.mesh and `DG_FECollection', the program use Qk instead of Pk. As for `k=1', the dofs is 4 instead of 3.

So my questions is: How to use `DG_FECollection' on quad mesh with Pk element, not Qk element?

**Comment by tzanio** [comment]
Hi @cglwdm,

We don't currently support $P_k$ spaces on quad/hex meshes.

Tzanio

**Comment by cglwdm** [comment]
> Hi @cglwdm,
> 
> We don't currently support P k spaces on quad/hex meshes.
> 
> Tzanio

What‘s the main difficulties? I want to give a try.

**Comment by tzanio** [comment]
Do you have a description of the element you want? Specifically the degrees of freedom?
