### ISSUE TITLE
Issue about GLViS installation-X11R6 obsolete?

### ISSUE THREAD

**Issue by JiananZhangCU** [mfem/mfem#461]
Dear MFEM users and developers,

I am new to MFEM and GLViS and trying to build and install MFEM and GLViS on Ubuntu 16.04.
Following the online tutorial I have built MFEM successfully. To build the GLViS, I have installed the required external packages (X11, GL, GLU, libpng, libtiff, etc.) following the INSTALL file. But I encountered the following errors when I use make to build the GLViS library:
/usr/bin/ld: cannot find -lfreetype
/usr/bin/ld: cannot find -lfontconfig

I guess this error is because the paths to some libraries are not correct, since the following lines exist in the Makefile:
GL_OPTS = -I/usr/X11R6/include
GL_LIBS = -L/usr/X11R6/lib -lX11 -lGL -lGLU
TIFF_OPTS = -DGLVIS_USE_LIBTIFF -I/sw/include
TIFF_LIBS = -L/sw/lib -ltiff

I don't know much about Makefiles, just get a feeling that these indicate the paths for the required libraries. Does everyone know which lines do I need to change for the makefile? And how to change them? 

By the way, when I search online, someone said "X11R6 has been obsolete for quite a while, There is a major compatibility issue between X11R6 and the present X11 version." Is this one of the reasons for my failure? 

Any suggestions and hints will be much appreciated. Thanks in advance.

Jianan Zhang

**Comment by jakubcerveny** [comment]
Hi Jianan,

I think you still miss some dependencies. Try these:

    sudo apt-get install libfreetype6-dev libfontconfig1-dev

The X11R6 paths might be obsolete. Nevertheless, -L is just a suggestion
for the linker where to look, so it shouldn't matter that much.

Hope that helps,
Jakub

**Comment by JiananZhangCU** [comment]
![glvis_build_issue](https://user-images.githubusercontent.com/27965581/38120950-35d34af4-339a-11e8-8ae4-4c7d7ebadee5.png)

**Comment by JiananZhangCU** [comment]
Hi, Jakub, 
Thanks for your reply. I have installed the tow libraries as you suggested, then the previous error disappears, But the building still does not goes successfully, the following error exists:

![glvis_build_issue](https://user-images.githubusercontent.com/27965581/38121049-dadac946-339a-11e8-997e-4f34ea3c7f27.png)

I am not sure where is the problem, Can you kindly show me some hints?

Best
Jianan Zhang

**Comment by v-dobrev** [comment]
Hi @JiananZhangCU,

I see that you are building GLVis v3.3 with MFEM v3.3.2 - there is a small issue with that combination - you should get the latest GLVis from GitHub: first, if you do not have `git` install it with `apt-get` and then run:
```sh
cd ~/
git clone git@github.com:glvis/glvis.git glvis-dev
cd glvis-dev
make MFEM_DIR=../mfem-3.3.2 -j 4
```
The last command assumes that `glvis-dev` and `mfem-3.3.2` are in the same directory - you home directory (`~/`) judging by your sreenshot. The `-j 4` option tells make to use up to 4 jobs for parallel compilation and linking - this will speedup the build.

Let us know if you run into any other issues.

**Comment by JiananZhangCU** [comment]
Hi, Veselin,

It works! The building process run successfully and I got the GLViS executable in my glvis-dev directory. Now I can start investigating the existing examples. Thanks very much! 

By the way, I may run into other issues in using the GLViS in the near future. So I may still need your guys kind help when I am in a trouble. ^_^||

Best regards
Jianan Zhang
