### ISSUE TITLE
Problem with a Mesh constructor

### ISSUE THREAD

**Issue by Tomcat4891** [mfem/mfem#4612]
Hello. 

I have the wrong mesh being created for a two-dimensional grid dim=2, sdim=2.
The following constructor is used

`Mesh(real_t *vertices, int num_vertices,
        int *element_indices, Geometry::Type element_type,
        int *element_attributes, int num_elements,
        int *boundary_indices, Geometry::Type boundary_type,
        int *boundary_attributes, int num_boundary_elements,
        int dimension, int space_dimension = -1);
`

In the three-dimensional case there are no problems. In the two-dimensional case, after writing the mesh to the file, the coordinates of nodes with uninitialized values appear. However, all arrays are initialized correctly.  In addition, I succeeded in creating the mesh using AddTriangle, AddVertex and AddBdrSegment

Perhaps there is some error in the constructor for the two-dimensional case.

**Comment by v-dobrev** [comment]
The issue may be related to the `vertices` array -- it is expected that it defines 3 components, (x,y,z), for each vertex, independent of `dimension` and `space_dimension`. In 2D, you can just use `z=0` for all vertices.

**Comment by Tomcat4891** [comment]
Dear Veselin.

Thank you for the answer. It works. 

I'm confused because the *.mesh file doesn't store the third column in the two-dimensional case.  So I thought only two x and y coordinates were needed. There, pointers of type double are passed and no checks are performed. 

It would be nice if there was information for the two-dimensional case in the comments of this constructor.

**Comment by v-dobrev** [comment]
I added a clarification about this requirement for the `vertices` array in the Doxygen documentation of the constructor in commit 764b863c which is part of PR #4607.
