### ISSUE TITLE
Form compiler and form language in MFEM

### ISSUE THREAD

**Issue by balborian** [mfem/mfem#462]
Are there plans to include in MFEM a form compiler along the lines of FEniCS or Firedrake? Together with a form/variational language that makes writing pde's faster.

**Comment by tzanio** [comment]
I am closing this issue now, but several other folks on the team, e.g. @camierjs, @dmed256 and @sshiraiwa are also interested in this topic, so feel free to reopen if you are planning to work on it.

**Comment by salazardetroya** [comment]
Hello, what's the status of this feature? It would be incredibly useful to not only implement new physics very quickly, but also derive adjoint models for optimization. MFEM could use the UFL domain-specific language (https://arxiv.org/abs/1211.4047) used already by FEniCS, Firedrake, and DUNE. FEniCS and Firedrake also interface easily with Pyadjoint (aka http://www.dolfin-adjoint.org/en/latest/) thanks to both using UFL.

**Comment by camierjs** [comment]
Hi Salazar, this feature has been on our radar for some time now. We are working on trying if such abstraction would allow us to generate our integrators more easily as a first step. If that works, then we'll be able to move toward bridging to UFL directly. Concerning the interface with Pyadjoint, that will need to be synchronized with some internal work on this topic I guess.

**Comment by salazardetroya** [comment]
> Hi Salazar, this feature has been on our radar for some time now. We are working on trying if such abstraction would allow us to generate our integrators more easily as a first step. If that works, then we'll be able to move toward bridging to UFL directly. Concerning the interface with Pyadjoint, that will need to be synchronized with some internal work on this topic I guess.

Nice, is there any branch with some preliminary work available?
