### ISSUE TITLE
Mesh v1.3 Format Issues with Named Attributes

### ISSUE THREAD

**Issue by paul-hilscher** [mfem/mfem#4625]
Hello, 

meshes with named attributes seem to be tested in [`ex39.cpp`](https://github.com/mfem/mfem/blob/master/examples/ex39.cpp) using a `gmsh` file. However trying to use mfem's native format with 
```git
diff --git a/examples/ex39.cpp b/examples/ex39.cpp
index 72698a62b..7b0e5527f 100644
--- a/examples/ex39.cpp
+++ b/examples/ex39.cpp
@@ -50,7 +50,7 @@ using namespace mfem;
 int main(int argc, char *argv[])
 {
    // 1. Parse command-line options.
-   const char *mesh_file = "../data/compass.msh";
+   const char *mesh_file = "../data/compass.mesh";
    int order = 1;
    string source_name = "Rose Even";
    string ess_name = "Boundary";
```
leads to following error:
```
Verification failed: (ident == "boundary") is false:
 --> invalid mesh file
 ... in function: void mfem::Mesh::ReadMFEMMesh(std::istream&, int, int&)
 ... in file: mesh/mesh_readers.cpp:84
```

Based on the code (and some testing) it seems that in contrast to [mesh v13](https://mfem.org/mesh-format-v1.0/#mfem-mesh-v13) and [compass.mesh](https://github.com/mfem/mfem/blob/master/data/compass.mesh) the actual accepted format is
```
attribute_sets
16
"Base"
1 
9
"E Even"
1
16
"E Odd"
1
17
"East"
2
16
17
```

or do I miss something ? 

In case this is a bug I am happy to look into this further.

Thanks and best regards.

**Comment by v-dobrev** [comment]
I suspect that this is a bug in the reader -- the format specification on the website and the file `compass.mesh` seem consistent and make sense to me. Looking at the implementation, the use of `getline(in, ArrayLine);` in `ArraysByName<T>::Load(std::istream &in)` is why the numbers after the name cannot be on the same line. This should be relatively easy to fix.

**Comment by tzanio** [comment]
Discussion continued in #4626
