### ISSUE TITLE
Boundary attributes and Derefinement

### ISSUE THREAD

**Issue by junkudo** [mfem/mfem#463]
Hey,
I'm seeing some inconsistent behavior with the size of my boundary attributes when I perform a de-refinement of the mesh.  

I have a simple executable that
1.) Creates a square mesh
2.) Uniform refines the mesh (via `mfem::Mesh::UniformRefinement`)
3.) Uniformly de-refines the mesh (via `mfem::Mesh::DerefineByError`)

```c++
#include "mfem.hpp"
#include <mpi.h>
#include <iostream>

int main(int argc, char *argv[])
{
   MPI_Init(&argc, &argv);

   // Make a mesh
   mfem::Mesh mesh(10, 10, mfem::Element::QUADRILATERAL, 1,
                   1.0, 1.0);
   mesh.EnsureNCMesh();

   // Make it into a parallel mesh
   mfem::ParMesh pmesh(MPI_COMM_WORLD, mesh);
   std::cout << "After creation : Boundary attribute size: " << pmesh.bdr_attributes.Size() << std::endl;

   // Perform a refinement of every element
   pmesh.UniformRefinement();
   std::cout << "After refinement : Boundary attribute size: " << pmesh.bdr_attributes.Size() << std::endl;

   // Perform a derefinement of every element
   mfem::Vector error_indicator(pmesh.GetNE());
   error_indicator = 0.0; // Zero out indicator to force de-refinement everywhere
   pmesh.DerefineByError(error_indicator, 1.0, 1);
   std::cout << "After derefinement : Boundary attribute size: " <<  pmesh.bdr_attributes.Size() << std::endl;

   MPI_Finalize();
   return 0;
}
```

I'm looking at the size of the mesh's boundary attributes as I perform these operations as I expect them to be the same value all throughout.

The values stays constant as as expected in serial : 
```
$ srun -n 1 ./example
After creation : Boundary attribute size: 4
After refinement : Boundary attribute size: 4
After derefinement : Boundary attribute size: 4
```
However, when I run this code in parallel, the size of the boundary attribute changes after the de-refinement step:
```
$ srun -n 2 ./example
After creation : Boundary attribute size: 4
After creation : Boundary attribute size: 4
After refinement : Boundary attribute size: 4
After refinement : Boundary attribute size: 4
After derefinement : Boundary attribute size: 3
After derefinement : Boundary attribute size: 3
```

Am I doing something wrong?  Thanks for your help!

CCing @Dan2997925 in case you are interested

**Comment by v-dobrev** [comment]
This looks like a bug, we'll look into it.

As a workaround, for now, you can just make a copy of `Mesh::bdr_attributes` in the beginning and use that instead.

Thanks for the bug report.
