### ISSUE TITLE
Issue with visualizing Gmsh mesh using GLViS

### ISSUE THREAD

**Issue by JiananZhangCU** [mfem/mfem#464]
Hi, all,

I want to use glvis to visualize a mesh generated by Gmsh. However, it gives me the following error:
![gmesh_vis_issue](https://user-images.githubusercontent.com/27965581/38152646-baae4174-3436-11e8-854a-c49a30fe80d5.png)

The original mesh is a cuboid like this:
![gmsh_cuboid](https://user-images.githubusercontent.com/27965581/38152719-036c7e94-3437-11e8-97a4-d0d381027536.png)

Anyone got a idea where is the problem? Thanks in advance.

Jianan

**Comment by sshiraiwa** [comment]
Hi,

If I remember correctly, I saw the same thing when I didn’t have
physical entities set in gmsh file. Do you have a block enclosed by
$PhysicalNames and $EndPhysicalNames in your gmsh?

—
S

**Comment by JiananZhangCU** [comment]
Hi, Syun'ichi,

Thanks for the reply. No, I do not have that block in my gmsh file. I got this file directly from Gmsh software, which was used for dealii library (another FEM library which I've been using for a few months). 

Do I need to change the gmsh file myself? Or how? I can also send you the gmsh file for your information if needed.

Best
Jianan

**Comment by jandrej** [comment]
You can set Physical Entities in GMSH when you create the domain. See http://gmsh.info/doc/texinfo/gmsh.html#Elementary-vs-physical-entities

**Comment by stefanozampini** [comment]
This should have been fixed in https://github.com/mfem/mfem/commit/307afc3aee0b3bc656a0238306b0ff5b16811e69

Can you update to mfem 3.3?

**Comment by JiananZhangCU** [comment]
Hi, Julian,

Thanks. I will give it a try to see if the problem can be solved.

**Comment by JiananZhangCU** [comment]
Hi, Stefano,

Thanks for the reply. I am currently using mfem 3.3.2, the one on the MFEM homepage. Does that work in mfem 3.3.2?

**Comment by stefanozampini** [comment]
I guess you should use the development version to get the fix, or apply the
commit on your local version

Il Sab 31 Mar 2018, 15:21 Jianan Zhang <notifications@github.com> ha
scritto:

**Comment by JiananZhangCU** [comment]
Hi, Stefano. I got the development version (with git clone git@github.com:mfem/mfem.git mfem-dev), but the error still exists. May be I will try Julian's suggestion to see how to set Physical Entities in GMSH when I create the domain?

Jianan

**Comment by JiananZhangCU** [comment]
Hi, @jandrej ,

I have tried another 2D Gmsh which contains a block enclosed by $PhysicalNames and $EndPhysicalNames. Now the mesh can be viewed by GLViS, however, the mesh seems to have tree levels, as shown below:
The mesh viewed in Gmsh:
![gmsh_view](https://user-images.githubusercontent.com/27965581/38174460-5d38846c-359b-11e8-989a-532f9a5a8d09.png)

The mesh viewed in GLViS (top view):
![glvis_top](https://user-images.githubusercontent.com/27965581/38174469-77e15384-359b-11e8-9eb0-7f55f917929c.png)

The mesh viewed in GLViS (side view):
![glvis_side](https://user-images.githubusercontent.com/27965581/38174474-8194c3d4-359b-11e8-9816-186612de2892.png)

As can be seen, it seems the original mesh has been divided into three parts. Adding them together is the total mesh. 

Do you have an idea why does this happen?

Thanks
Jianan

**Comment by v-dobrev** [comment]
What you see is the checkerboard-like solution (piece-wise constant on each element) we create in order to display the mesh, so that neighbor elements have different colors.

**Comment by JiananZhangCU** [comment]
Hi, @v-dobrev,
Thank you for the explanation. 

Jianan
