### ISSUE TITLE
Marking mesh nodes and edges in parallel

### ISSUE THREAD

**Issue by thorvath12** [mfem/mfem#4642]
Hello,

I need to assign integers to edges and nodes of 2D meshes, and I run into some parallel issues. In some cases, the different processes would assign a different number for a shared node/edge. I need to get the maximum value out of those and distribute that across all processes sharing the node/edge.

Initially, I was thinking of using a grid function of an H^1 space with order one for the nodes and a grid function of an L^2 space with order zero on the skeleton for the edges, but I could not figure out how to get the maximum values over the shared nodes/edges. Is it possible to do that somehow? Or is there a better way to do this?

I would appreciate any advice you can give me.

Best,
Tamas

**Comment by vladotomov** [comment]
Hi @thorvath12, take a look at the implementation of
`ParGridFunction::ProjectDiscCoefficient(Coefficient &coeff, AvgType type)`. 
You'd need to do `GroupCommunicator::Max` for the reduction over DOFs.

**Comment by v-dobrev** [comment]
Just to add some more details: if you have a `ParGridFunction pgf` you can get a reference to the `GroupCommunicator` using `pgf.ParFESpace()->GroupComm()`. The `GroupCommunicator` can then be used to perform `Reduce` and `Bcast` operations just on the shared dofs of `pgf`. In your case, you can use `Reduce` with reduce operation `GroupCommunicator::Max`, as @vladotomov pointed out. The reduce operation puts the reduced value just on the master rank for that dof, so you need to call `Bcast` if you want that value distributed to all ranks in the shared dof group.

**Comment by thorvath12** [comment]
Thank you! This is exactly what I needed!
