### ISSUE TITLE
How to record the memory usage for one code block?

### ISSUE THREAD

**Issue by adam-sim-dev** [mfem/mfem#4648]
Well, it's not an issue related to mfem itself.

I run my parallel mfem-based application on a shared memory computer with Ubuntu Linux. I want to record the maximum memory usage for one code block like the following:

```
record and print the memory usage on the master rank before the following code block

# the C++ code block, for example, calls the iterative solvers, or, creates a parallel finite element space,...

record and print the memory usage on the master rank after the above code block
```
After searching the web, one possible solution is to open and read the file /proc/meminfo, I find it's not so reliable. Maybe I am doing something wrong. Is there any better solution? Should Caliper work? https://github.com/LLNL/Caliper/issues/493

Thanks.
Best, Adam

**Comment by v-dobrev** [comment]
Using Caliper should work.

Some other options:
* use `getrusage`, see `man getrusage`
* read and parse one of the "proc files": `/proc/self/statm` or `/proc/self/status`, see https://www.kernel.org/doc/Documentation/filesystems/proc.rst
* use `gperftools` for heap profiling, see https://github.com/gperftools/gperftools and the "HEAP PROFILER" section in the README.

**Comment by adam-sim-dev** [comment]
> Using Caliper should work.
> 
> Some other options:
> * use `getrusage`, see `man getrusage`
> * read and parse one of the "proc files": `/proc/self/statm` or `/proc/self/status`, see https://www.kernel.org/doc/Documentation/filesystems/proc.rst
> * use `gperftools` for heap profiling, see https://github.com/gperftools/gperftools and the "HEAP PROFILER" section in the README.

is /proc/self/statm for one process only?

**Comment by v-dobrev** [comment]
The "proc files" are not actual files on the hard drive -- they are generated by the linux kernel when they are read. So the "file" `/proc/self/statm` contains information about the calling process (this is what "self" refers to), so reading this "file" from different processes will give different information.

**Comment by adam-sim-dev** [comment]
> The "proc files" are not actual files on the hard drive -- they are generated by the linux kernel when they are read. So the "file" `/proc/self/statm` contains information about the calling process (this is what "self" refers to), so reading this "file" from different processes will give different information.

Yes, this is what I understand. https://github.com/LLNL/Caliper/blob/165b89ad00d5b235bfdae7215df7afd9a820db0c/src/services/memusage/MemStatService.cpp#L96
Caliper also read this proc file. The "problem" (if it is a problem) is only one process reports this info.

**Comment by adam-sim-dev** [comment]
Maybe I could do what you suggest by myself without using Caliper.

> The "proc files" are not actual files on the hard drive -- they are generated by the linux kernel when they are read. So the "file" `/proc/self/statm` contains information about the calling process (this is what "self" refers to), so reading this "file" from different processes will give different information.

**Comment by v-dobrev** [comment]
Did you build Caliper with `-DWITH_MPI=ON`?

**Comment by adam-sim-dev** [comment]
> Did you build Caliper with `-DWITH_MPI=ON`?

Yes. I call caliper.flush() to print the info. caliper_config = "runtime-report,mem.pages";

**Comment by adam-sim-dev** [comment]
Did I miss mpi-report?

**Comment by v-dobrev** [comment]
I'm not sure what Caliper config will give you the details you are looking for. Maybe try using `event-trace,mem.pages` or `hatchet-region-profile,mem.pages,output.format=json`. You can see the various Caliper config options with `<caliper prefix>/bin/cali-query --help=configs` and then for specific recipes you can see their options with e.g. `<caliper prefix>/bin/cali-query --help=event-trace`.
