### ISSUE TITLE
What are the typical ways of generating *.mesh files for MFEM

### ISSUE THREAD

**Issue by JiananZhangCU** [mfem/mfem#466]
Hi, all,

Thank you all to share this excellent FEM library. I am new to MFEM and after studying it for a few days I got a question about generating the *.mesh files. I have some experience on dealii library and Gmsh software. (I switch to MFEM because MFEM can support tetrahedral elements while dealii cannot).  So my questions about mesh generation are as follows:

(1) What are the typical ways of generating *.mesh files for MFEM? (or how do I create the mesh for my problem?) I guess there should be a manual way with some build-in functions, and an automatic way which can convert the mesh files created by other softwares (NetGen, Gmsh, VTK) to *.mesh files?

(2) If I choose the second way, which software is supported the best? 

(3) Since I have some experience on Gmsh, is it possible and how to convert the *.msh files (created by Gmsh software ) to *.mesh files in order to visualize the solutions (as far as I know, GLViS needs a *.mesh file and a *.gf file for visualization).

I also suggest to add a FAQ part on the homepage or somewhereelse (the question "How do I create the mesh for my problem?" may also be included) to help the new comers to learn MFEM more efficiently.  This is just a suggestion.

Thanks in advance
Jianan

**Comment by jandrej** [comment]
I can just speak for my case and workflow.

2. I generate meshes in Cubit which produces an exodusII file which can be read with mfem.

3. You can use the "mesh-explorer" miniapp in mfem to load a GMSH generated .msh file and visualize it in glvis.

**Comment by JiananZhangCU** [comment]
Thank you @jandrej, I will take a look into the "mesh-explore" miniapp to load a GMSH generated .msh file and visualize it in glvis.
