### ISSUE TITLE
Matrix bandwidth optimization

### ISSUE THREAD

**Issue by Watchmojo** [mfem/mfem#47]
Hi, all,

Will a matrix bandwidth optimization, such as Cuthill–McKee algorithm, make the AMG solver faster? 

Thank you,
Frank

**Comment by tzanio** [comment]
Hi Frank,

Reordering could help with the smoother on the finest grid, but it may be challenging to implement in parallel. I am not aware of any studies how it affects coarsening and the overall AMG performance. My guess is that the differences will be minor for typical diffusion problems.

Maybe Ulrike (cc-ed) knows more about this and can offer further advice.

Cheers,
Tzanio

**Comment by Watchmojo** [comment]
Hi, Tzanio,

Thank you for your information. 

Frank
