### ISSUE TITLE
Use of RestrictedCoefficient with multiple domain mesh

### ISSUE THREAD

**Issue by S-Villar** [mfem/mfem#471]
Hello all,

I am exploring the use of the `RestrictedCoefficient` class (also `VectorRestrictedCoefficient` and `MatrixRestrictedCoefficient`) with a multiple domain mesh. In the documentation I can see that in the constructor `RestrictedCoefficient(Coefficient &_c, Array<int> &attr)` I can specify an integer array of attributes. If I understood correctly, this array of integer has size equal to the number of domain attributes in which the user wants to specify the coefficient to be active, and each element `attr[ i ]` corresponds to the `mesh->attributes[ i ]` integer in which I want the coefficient to be set. 

Using a 2D rectangular mesh generated by GMSH in which I split the domain in two, and having defined 6 physical lines (outer boundaries of the box) and 2 physical surfaces (6 bdr_attributes and 2 attributes), I would expect the following two methods to be equivalent:

- We create a coefficient `Coefficient *C1 = new ConstantCoefficient(1.0)` and apply it to one integrator as `M1->AddDomainIntegrator(new VectorFEMassIntegrator(*C1))` . This coefficient is constant and defined for the whole domain. Then we solve our problem and in this case it converges.
- Similarly if we specify a `RestrictedCoefficient *RC1 = new RestrictedCoefficient(*C1,mesh->attributes)` trying to give this coefficient C1 restriction to domains in array attributes (which are all subdomains in the mesh) using `M1->AddDomainIntegrator(new VectorFEMassIntegrator(*RC1))` the solution does not converge or using further advance solvers I can see a huge discontinuity between both regions. 

I wonder whether the problem is regarding some rules that I didn't follow in the generation of physical domains using GMSH so that MFEM can read them properly or if it is a misunderstanding of the use of RestrictedCoefficient class. 

Could you give me some advice on this issue? I apologize for the inconvenience and thanks a lot in advance.

PS: the mesh has been generated so that there is no physical boundary in the interface between both domains. Maybe it would be needed to define this as a boundary and some special boundary condition between both media. 

Alvaro

**Comment by mlstowell** [comment]
Hi, Alvaro,

I believe the trouble is that the attribute array stored in the Mesh class which you access as mesh->attributes is not suitable for passing to the RestrictedCoefficient class.  Unfortunately this is not well documented.

The Mesh::attributes Array contains the unique element attributes found in the mesh.  These attributes are assumed to have values greater than zero but they need not be contiguous.  For example you could have attributes 1, 10, 20, and 25. These would be stored in an Array<int> object of length 4.

The RestrictedCoefficient takes an Array<int> that could be thought of as defining a mask not a list of attribute values.  Furthermore this array will be accessed using attribute numbers as array offsets (attribute_number-1 actually) so its length is not the number of attributes but rather it should equal the largest attribute number.  For example if our attributes are again 1, 10, 20, and 25 the array passed to RestrictedCoefficient should be of length 25 not 4.  The values stored in this array should be zero if the attribute is not active and non-zero if it is active.

To setup an attribute array (with all attributes activated) for the RestrictedCoefficient you can do the following:
Array<int> attr(mesh->attributes.Max());
attr = 1;
You can then switch individual attributes off by setting the corresponding entry equal to zero if desired.  Or you could set everything to zero and activate individual attributes by setting their entries to 1 as desired.

Best wishes,
Mark

**Comment by tzanio** [comment]
Hi Alvaro,

Were you able to get this to work? 

To further clarify Mark's answer, here is the two-line implementation of this class:
```c++
/// Coefficient defined on a subset of domain or boundary attributes
class RestrictedCoefficient : public Coefficient
{
private:
   Coefficient *c;
   Array<int> active_attr;

public:
   RestrictedCoefficient(Coefficient &_c, Array<int> &attr)
   { c = &_c; attr.Copy(active_attr); }

   virtual double Eval(ElementTransformation &T, const IntegrationPoint &ip)
   { return active_attr[T.Attribute-1] ? c->Eval(T, ip, GetTime()) : 0.0; }
};
```
As you can see the `attr` array you provide to the constructor is being checked at entry element attribute - 1 in the actual evaluation function. Thus you want to provide `attr` that is of size max attribute number - 1, zero it out, and set to one all entries `i-1`, for attributes `i` where you want the coefficient to be active.

**Comment by S-Villar** [comment]
Hello @mlstowell and @tzanio,

I find confusing the fact that the array `attr` size for `RestrictedCoefficient`  has to be equal to `mesh->attributes.Max()`  instead of `mesh->attributes.Size()`. I guess there are some reasons behind this choice which I am not aware of at this point. Now, with your help, I am able to get this to work.

Thank you a lot for the extense clarification,
Regards,
Alvaro

**Comment by mlstowell** [comment]
Hi, Alvaro,

It certainly is counter intuitive.  This is a tradeoff where we gain a little efficiency in time by using a bit more memory.  We want to lookup active attributes in an array because such lookups are virtually immediate.  If the attribute indices don't start at 1 or if there are many missing attributes between 1 and the maximum attribute number then this array will be longer than might be necessary so it requires more memory.  The alternative would be to perform the lookup in a std::set or std::map but this takes O(log(n)) in time.  The number of attributes might be small so log(n) might also be small but we perform this lookup for each element.  As there could be billions of elements these lookup times could add up to something noticeable.

Best wishes,
Mark

P.S.  If this answers your concerns can we close this issue?

**Comment by S-Villar** [comment]
I see! Although counter intuitive it makes a lot of sense. 

Thank you Mark for all these clarifications. Sure, we can close this issue.

Best,
Alvaro
