### ISSUE TITLE
partititioning error

### ISSUE THREAD

**Issue by Dan2997925** [mfem/mfem#473]
I'm getting an error

MFEM_VERIFY((*offsets[i])[0] >= 0 && (*offsets[i])[1] >= 0,"overflow in offsets")

at line 1260 in pmesh.cpp

What does this mean?

**Comment by jakubcerveny** [comment]
Are you solving a big problem with >2G unknowns? Maybe you need to compile
hypre with --enable-big-int.

Jakub

**Comment by Dan2997925** [comment]
Yes it’s a big problem. My mesh is smaller than 2G elements. But it is an elasticity problem so the displacement field could perhaps be exceeding 2G.

When is this function being called? Have I successfully partitioned and distributed and refined the mesh before I get to this point?

I don’t know if we are using –enable-big-int or not I’ll look in to it.

**Comment by jakubcerveny** [comment]
This code is usually called when constructing the FE space, to determine
the DOF partitioning. I would guess the mesh is OK, the space typically
overflows first.

Jakub

**Comment by Dan2997925** [comment]
OK this makes sense. So I would need to rebuild hypre, *and* mfem, right?

**Comment by jakubcerveny** [comment]
That's right.
