### ISSUE TITLE
Diffusion-reaction system equations

### ISSUE THREAD

**Issue by yantingsa** [mfem/mfem#474]
Hi everyone,

I'm really new to MFEM and working on a diffusion-reaction system PDEs. I went through the examples and understood how MFEM works. Currently, I'm working on a simple diffusion-reaction system to do the test. Here is my system:
           -div(D\*grad(u)) = u\*v + f_u
           -div(D\*grad(v)) = -u\*v + f_v
My questions are:
1.  how to implement reaction term (ie, u*v) in bilinear form. 
2.  since the diffusion coefficient "D" has a jump at the interface, is there any specific way in MFEM to handle this kind of discontinuous to achieve better convergence rate?

Thank you so much for all of your help.
Ting

**Comment by v-dobrev** [comment]
Hi Ting,

The reaction term that you have leads to the following form: (after multiplying the first equation by `phi`, the second by `psi`, integrating, and adding them)
```
R((u, v), (phi, psi)) = (u*v, phi) - (u*v, psi)
```
which is actually nonlinear. This means that you probably will need to implement your system using either class `NonlinearForm` (with a `FiniteElementSpace` that has `vdim=2` - combining the `u` and `v` components) or alternatively using class `BlockNonlinearForm` with two blocks that use the same scalar `FiniteElementSpace`. Does this make sense?

Another approach (which is simply one approach for solving the nonlinear system you have) could be to solve the system by freezing `u` and `v` consecutively and iterating. When one of the variables is frozen, the equation for the other one is linear with a coefficient that depends on the frozen variable.

Regarding your second question, it will be best if you can create a mesh that is aligned with the interface you have. Also, if you mark elements in the different sub-domains with different attributes, then you can then use a `PWConstCoefficient` to describe your diffusion coefficient - see mfem example 2 which defines and uses such coefficients.

Let us know if you have any further questions.

**Comment by yantingsa** [comment]
Hi,

Thanks for your reply. Your explanation makes sense for me. But I still got some confusion. If I want to using 
BlockNonliearForm, how do I represent the residual, i.e., 
`F(u) = inner(grad(u), grad(phi))*dx + inner(grad(v), grad(psi))*dx -  inner(u, v)*phi*dx + inner(u, v)*psi*dx - fu*phi*dx - fv*psi*dx`. Should I did something like ex10, writing a class based on `Operator` and using `Mult`? And using `GetGradient` to compute the Jacobian?
I think my current question is I do not really understand how can I write my residual form using NonlinearForm or combined BilinearForm or BlockNonlinearForm. Would I need to update the `NonlinearFormIntegrator:GetElementEnergy`? It would be great if you can give me some idea or example. 
Thanks a lot!
