### ISSUE TITLE
A guide how to add source files into MFEM lib

### ISSUE THREAD

**Issue by kvoronin** [mfem/mfem#478]
Hello,

I'd like to ask how exactly one should add some source files to MFEM to build them into library file (in my own fork of MFEM). For example, I want to write an extension to MFEM and impose some structure on the new files and compile them eventually together with the standard mfem files into the libmfem.

Let's say, I want to add a header testext.hpp and a corresponding testext.cpp (let's say, in a new subfolder test/ of the mfem directory). How I should do that?

Of course, I can add everything into a new example, but it is not very convenient. I should modify the makefile somewhere but I would appreciate if someone tells me exactly how.

I hope I make my question clear enough.

Thanks,
Kirill

**Comment by tzanio** [comment]
Hi Kiril,

If this is supposed to be part of (your fork of) the MFEM library then it should go into one of the main directories, e.g. `fem`. The best way to figure out how to add a file there is to see how the code handles one of the current files, e.g. with `grep -R staticcond`. Specifically, you just need to add `testext.cpp` and `testext.hpp` in `fem` and in and `fem/CMakeLists.txt` and include `testext.hpp` in `fem.hpp` and other appropriate headers.

If this is an extension of MFEM that is part of your application, then you should just build with the rest of your application code in a completely separate directory and link with MFEM.

Hope this helps,
Tzanio

**Comment by tzanio** [comment]
I'm closing this issue now. Feel free to re-open if you have further questions.
