### ISSUE TITLE
Sampling the solution at some point

### ISSUE THREAD

**Issue by gkumar08** [mfem/mfem#482]
Hi,

Is there a way I can sample the solution `GridFunction x` after `a->RecoverFEMSolution(X, *b, x);` at any sample point of my choice? Let's say, for the elastic beam analysis, I want to know the displacement at some point. Or I want to sample the result on a boundary mesh that is different than the boundary of the mesh that was used for analysis. The only relevant function seems to be `x.GetValue(...)`, but that requires me to know which exact element the point belongs too . Is that it or is there an efficient way to do it? 

Thanks in Advance.

**Comment by jandrej** [comment]
If you look at #304 I had a similar question. There is even a code snippet we use for an elasticity solution vector here https://github.com/mfem/mfem/issues/304#issuecomment-334956843.

Hope that helps.

**Comment by gkumar08** [comment]
It did! Thank you very much.
