### ISSUE TITLE
Build submatrix for list of finite elements

### ISSUE THREAD

**Issue by ben-s-southworth** [mfem/mfem#484]
Hi MFEM team,
I would like to build the algebraic submatrix corresponding to a given set of finite element indices (can assume these elements are all on processor). Does MFEM currently have this functionality? E.g., call some routine like `Assemble(Array<int>element_list, SparseMatrix &submat)` that will spit out a sparse matrix corresponding to the element connections in element list? If not, any tips on where to build something like this?
Thanks!

**Comment by tzanio** [comment]
@mlstowell is this something that can be handled with the [entity-sets-dev](https://github.com/mfem/mfem/tree/entity-sets-dev) branch?

**Comment by v-dobrev** [comment]
You should be able to call
```c++
BilinearForm::ComputeElementMatrix(int i, DenseMatrix &elmat);
```
followed by
```c++
BilinearForm::AssembleElementMatrix(
   int i, const DenseMatrix &elmat, Array<int> &vdofs, int skip_zeros);
```
in a loop over the indices `i` that you are interested in.

Then you just need to `Finalize()` the `BilinearForm` and get the `SparseMatrix` with `BilinearForm::SpMat()`.

**Comment by ben-s-southworth** [comment]
@v-dobrev The submatrix data is different when I call
`    for (int i=0; i<10; i++) {
        Array<int> vdofs;
        DenseMatrix elmat;
        bl_form->ComputeElementMatrix(i, elmat);
        bl_form->AssembleElementMatrix(i, elmat, vdofs, 1);
    }
    bl_form->Finalize();
    SparseMatrix test = bl_form->SpMat();
`
compared with building the global matrix via
`  bl_form -> Assemble();
    bl_form -> Finalize();
    SparseMatrix test = bl_form->SpMat();
`
Is that what you had in mind? 

@jakubcerveny I modified the Assemble() routine to do this and I believe it should do the trick. I needed a way to determine which boundary faces are relevant for a set of element indices. I did not see functionality in MFEM for this (e.g., like GetElementFaces(), but for BoundaryFaces?), but our code stores this information anyways , so it should be okay.

**Comment by v-dobrev** [comment]
@ben-s-southworth, yes, was that what you needed?

**Comment by v-dobrev** [comment]
Then you need to add the contributions from the neighbors of the elements you are interested in. You will probably want to zero-out some of the entries in the local matrices coming from the neighbors.

**Comment by tzanio** [comment]
@ben-s-southworth, were you able to get this working?
