### ISSUE TITLE
Seg Fault on pmesh->GetElementEdges()

### ISSUE THREAD

**Issue by ben-s-southworth** [mfem/mfem#485]
Let pfes be a ParallelFiniteElement space with DG elements and pmesh the mesh. The following loop seg faults, where I try to get the edge indices for each element: 

>   `for (int i=0; i<pfes.GetNE(); i++) {`
>       `  Array<int> tempFaces;`
>         `Array<int> tempOr;`
>         `pmesh->GetElementEdges(i, tempFaces, tempOr); `
>         `for (int k=0; k<tempFaces.Size(); k++) {`
> `            std::cout << tempFaces[k]<< ", ";`
>`         }`
>  `       std::cout << "\n";`
>`     } `

I think it may be boundary elements that are problematic, because the loop runs partially if I start at i=100. However, it still seg faults, and the behavior seems undefined in that sometimes the program finishes, or other times it faults at different loop indices. 

Is this expected behavior or a bug? Is there a way to get edge indices for any node?

**Comment by jakubcerveny** [comment]
This part of the code does not seem wrong, would you mind posting the
complete code that leads to the crash?

Jakub

**Comment by ben-s-southworth** [comment]
Found it, bug on my side!
