### ISSUE TITLE
Problems with VisItDataCollection

### ISSUE THREAD

**Issue by jandrej** [mfem/mfem#488]
Hello,

I am saving a GridFunction using `VisItDataCollection` at desired visualization steps. The method is comparable to those in the examples. When I open the files in VisIt and generate a Pseudocolor plot, the rendered solution is very slow and takes around ~30seconds to render the next timestep. The amount of degrees of freedom is just ~35000. This happens on my laptop (Ubuntu 14.04) and a workstation with nvidia gpu (CentOS 7). Other files work fine on those machines with way larger databases.

I can't tell on my own whats wrong here. Are there any other formats I could save my GridFunctions to?

Regards
Julian

**Comment by tzanio** [comment]
What is the [Multires control](https://github.com/CEED/Laghos/issues/10#issuecomment-363780907) set to?

**Comment by cyrush** [comment]
@jandrej would it be possible to give me a copy of the dataset?

**Comment by jandrej** [comment]
Of course. You can download the dataset [here](https://cloud.tf.uni-kiel.de/index.php/s/DRyRcXxMkZQnN2o). Let me know if the link does not work.

**Comment by cyrush** [comment]
@jandrej  Thanks for the data, using VisIt 2.13.1 on my ~4 year old macbook pro, it takes about 5 seconds between timesteps for me. This is plotting a pseudocolor of temperature without any subdivision (no use of multires control). 

Are you using a VisIt release binary, if so can you let me know which one you are using?

**Comment by jandrej** [comment]
This was tested with VisIt 2.13.1 prebuilt release binaries on 
- Lenovo x260 Ubuntu 16.04 with visit2_13_1.linux-x86_64-ubuntu14
- ThinkStation P510 CentOS 7 visit2_13_1.linux-x86_64-rhel7
- Lenovo x250 Windows 7 visit2.13.1_x64.exe

All downloaded yesterday from the nersc.gov mirror. All of those showed the same behavior.

**Comment by cyrush** [comment]
@jandrej thanks! -- I am going to try tonight on another machine and see if I can reproduce.

**Comment by cyrush** [comment]
@jandrej  I tried on a Windows 10 machine, < 10 sec per timestep.  Not quite sure what is going on. 
Can you run VisIt with `-timing` and send me the output logs? cyrush@llnl.gov

**Comment by tzanio** [comment]
@jandrej and @cyrush -- was this also resolved by #490?

**Comment by jandrej** [comment]
@tzanio there is still a noticeable delay in comparison to other formats. Cyrus tracked that down to "multi-res level 0 still does one pass of refinement to map the basis function to the mesh".

Since this is on the VisIt side I will close the issue.

**Comment by cyrush** [comment]
@jandrej @tzanio 
I need to dive deeper, but from what I was seeing the i/o wasn't the issue -- the refinement process was slower than expected. I am going to try to look into this more for a future version of visit.
