### ISSUE TITLE
Problem with ConduitDataCollection and H1 FESpace

### ISSUE THREAD

**Issue by jandrej** [mfem/mfem#490]
Due to my issue in #488 I tried to use the ConduitDataCollection. I encountered the problem that VisIt states the error
```
The Mesh plot of variable "mesh_main" yielded no data.
```
when I try to plot the results of example 2 (which uses H1). Example 9 with DG elements works fine with every protocol I tried.

**Comment by jandrej** [comment]
This was tested with VisIt 2.13.1 prebuilt release binaries on a Lenovo x260 Ubuntu 16.04 with visit2_13_1.linux-x86_64-ubuntu14.

**Comment by cyrush** [comment]
@jandrej can you let me know which mesh you tested as input for example 2? Also, did you just drop  in ConduitDataCollection in place of the current vis logic in example 2?

**Comment by jandrej** [comment]
The mesh is the default mesh `data/beam-tri.mesh`.
I just changed the VisitDataCollection to ConduitDataCollection. It doesn't matter if the protocol is `hdf5` or `conduit_bin`.
```
diff --git a/examples/ex2.cpp b/examples/ex2.cpp
index bb450e7..a57823f 100644
--- a/examples/ex2.cpp
+++ b/examples/ex2.cpp
@@ -246,6 +246,12 @@ int main(int argc, char *argv[])
       sol_sock << "solution\n" << *mesh << x << flush;
    }
 
+   ConduitDataCollection conduit_dc("Example2", mesh);
+   conduit_dc.SetProtocol("conduit_bin");
+   conduit_dc.RegisterField("solution", &x);
+   conduit_dc.Save();
+
+
    // 16. Free the used memory.
    delete a;
    delete b;
```

**Comment by cyrush** [comment]
@jandrej Thanks, I was able to replicate. 

I found a fix for this error, and it will be in Visit 2.13.2 (the next version of VisIt)

**Comment by jandrej** [comment]
@cyrush sounds great!

I will try the latest SVN trunk tomorrow.

**Comment by jandrej** [comment]
@cyrush I built 2.13RC and tried to load the discussed example which now works.

Have you tried my other dataset from issue #488? I'm still having problems with that one. VisIt reports the error
```
The compute engine running on host saga issued the following warning: In domain 0, your nodal variable "mesh_main/temperature" has 770860 values, but it should have 35158.  Some values were removed to ensure VisIt runs smoothly.
```

**Comment by cyrush** [comment]
@jandrej  Can you double check you have the latest from the 2.13RC?

I did test this later in the day yesterday,  ran into this exact issue and committed a fix. 

I used the MFEM convert-dc tool to change your ASCII data to both conduit_bin and conduit_json.

**Comment by jandrej** [comment]
I have only access to the anonymous SVN repo at http://visit.ilight.com/svn/visit/branches/2.13RC
Maybe the repository is not synced yet?
I used the build_visit script from the branch and edited that accordingly. Did I miss something there?

**Comment by cyrush** [comment]
It looks like the commit is there -- to double check, can you look in:  

`src/databases/Blueprint/avtBlueprintFileFormat.C `

`avtBlueprintFileFormat::GetMesh(int domain, const char *abs_meshname)`

You should see:

```
    // check for the mfem case
    if( m_mfem_mesh_map[mesh_topo_name] )
    {
        BP_PLUGIN_INFO("mesh  " << mesh_topo_name << " is a mfem mesh");
        // use mfem to refine and create a vtk dataset
        mfem::Mesh *mesh = avtBlueprintDataAdaptor::MFEM::MeshToMFEM(data);
        res = avtBlueprintDataAdaptor::MFEM::RefineMeshToVTK(mesh, m_selected_lod+1);
        
        // cleanup the mfem mesh
        delete mesh;
    }
```

**Comment by jandrej** [comment]
Confirming that the recent revision of VisIt 2.13RC solves the issue. Thank you for the work!

**Comment by cyrush** [comment]
@jandrej Thanks for reporting helping us work out the issue!
