### ISSUE TITLE
How can evaluate a function over the mesh using mfem?

### ISSUE THREAD

**Issue by CHoudrouge4** [mfem/mfem#491]
#Hello, 
I have a function of the form integral over the domain  of dot product of two functions.

in Latex: 
int_{\Omega} u.g dx.

Is it possible to do this operation (evaluate the function) using mfem?

Thank you in advance.

**Comment by jakubcerveny** [comment]
Hi,

Is this a linear form in a weak formulation, with 'g' a constant function?
If so, you can take a look at Example 1 and the class DomainLFIntegrator,
which can be passed a Coefficient, where the Coefficient can be e.g. a
FunctionCoefficient that evaluates an arbitrary callback you pass.

Hope that helps,
Jakub

**Comment by CHoudrouge4** [comment]
The function is the compliance. so g is the applied force at the boundary (like example 2), and u is the displacement function (the solution of the PDE in example 2).

**Comment by jakubcerveny** [comment]
So you need to integrate a PDE solution times some coefficient over (some part of) the boundary? Correct?

We must have done this but I'm not sure how at the moment, maybe @mlstowell can advise?

Jakub

**Comment by CHoudrouge4** [comment]
![screenshot from 2018-05-11 12-30-59](https://user-images.githubusercontent.com/17670105/39920532-aa69fdc4-5517-11e8-910e-b71866ab860e.png)

Yes, I want to compute the function C (2.7)  where u is the solution of the linear elasticity equation (2,5).

**Comment by sshiraiwa** [comment]
Is f the function of solution?  If not, can you take the vector from LinearFrom
and dot product it with solution vector..?

**Comment by CHoudrouge4** [comment]
f is the force applied on the shape (\Omega). In example two (http://mfem.org/examples/), f is set to zero.
Which linear form ?

**Comment by sshiraiwa** [comment]
I thought,,,
 
Solution u is u = \simga ai ui, where ai is the solution vector and ui is the
basis funciton. Then,,,
 
   \int f u d\omega = \int f \simga ai ui \domega = \simga ai \int f ui \domga

And \int f ui \domga is a vector, we can evaluate Boundary/DomainLFIntegrator

,,,or am I missing the point?

**Comment by tzanio** [comment]
Hi @CHoudrouge4,

If I understand correctly, you want to compute a volume integral (involving `f`) and a boundary integral (involving `g`) for a given displacement field `u`.

In MFEM, you can compute these as a dot product of the `GridFunction` for `u` and a `LinearForm` with two `LinearFormIntegrator` objects for `f` and `g`. 

In the settings of Example 2, the code will look something like:

```c++
GridFunction u(fespace);
// compute u ...

LinearForm *fg = new LinearForm(fespace);
fg->AddDomainIntegrator(new VectorDomainLFIIntegrator(f));
fg->AddBoundaryIntegrator(new VectorBoundaryLFIIntegrator(g));
fg->Assemble();

double C = ((Vector) *fg) * ((Vector) u);
```

Hope this helps.

Tzanio

**Comment by CHoudrouge4** [comment]
Thank you very much.
