### ISSUE TITLE
Updating Mesh after adaptive mesh refinement

### ISSUE THREAD

**Issue by kvoronin** [mfem/mfem#492]
Hello,

I've implemented an adaptive mesh refinement with a user-defined error estimator, following the lines of ex6p.cpp. After each AMR iteration, I also called a visualization routine which depends on the mesh, and, on the edges in particular (el_to_edge and edge number). 
I noticed that after two AMR iterations, edge number (NumOfEdges) is not getting updated (though it is updated after the first one).

How can I fix that?

I noticed that after during first AMR iteration, when GetElementToEdgeTable is called to compute NumofEdges, in the GetVertexToVertexTable call inside, the code goes into the case when edge_vertex doesn't exist, but during the second time the code goes into the part under "if (edge_vertex)". Can it be the reason? Anyway, I don't find any public methods for updating tables in the Mesh class.

EDIT: For ex6p the issue doesn't reproduce itself since there the code goes into nonconforming refinement routine.

Thanks,
Kirill

**Comment by jakubcerveny** [comment]
Hi Kirill, thanks for reporting this, I will look into it tomorrow.

**Comment by v-dobrev** [comment]
What type of elements do you have? Is it triangles or tets?

**Comment by kvoronin** [comment]
@v-dobrev, tets.

**Comment by v-dobrev** [comment]
This looks like an issue that affects both triangles and tets and both in serial and parallel: some of the `Table`s generated on demand are not being destroyed when the mesh is refined. These include `el_to_el`, `face_edge`, and `edge_vertex`. It should be a simple fix for tets in serial: just delete those pointers and set them to `NULL` just before these lines:

https://github.com/mfem/mfem/blob/d9d6807ad7c8e438be8e4a367f886c4bb19f283f/mesh/mesh.cpp#L5996-L5999

In parallel you can do the same here:

https://github.com/mfem/mfem/blob/d9d6807ad7c8e438be8e4a367f886c4bb19f283f/mesh/pmesh.cpp#L2367-L2370

We'll fix this in MFEM in the near future, or if you want to make a PR - that is fine too.

**Comment by kvoronin** [comment]
Thanks for the quick response, @v-dobrev!

Just to be precise, it looks like we need not only to delete the pointers but also set edge_vertex to NULL. Otherwise,  in Mesh::GetVertexToVertexTable() the code will go under edge_vertex still (at least that's what I saw). I guess the reason is that edge_vertex will be reconstructed in between at line 
https://github.com/mfem/mfem/blob/d9d6807ad7c8e438be8e4a367f886c4bb19f283f/mesh/pmesh.cpp#L2139 (for ParMesh, with the similar thing for Mesh)

Whel I set edge_vertex to NULL, your idea works fine.

Thanks,
Kirill

**Comment by v-dobrev** [comment]
Yes, you want to set them to `NULL` after deleting them. For the construction of the vertex-to-vertex `Table` it is not important whether `edge_vertex` is set or not -- what is important is that if it is set, then it reflects the current mesh and not a coarser version of the mesh. I think that's what was happening before.
