### ISSUE TITLE
Ex9 and Ex9p don't work on AMR meshes.

### ISSUE THREAD

**Issue by jakubcerveny** [mfem/mfem#495]
This doesn't work correctly in current master:

`./ex9 -m ../data/amr-quad.mesh -p 1 -r 2 -dt 0.002 -tf 9`

![glvis_s01](https://user-images.githubusercontent.com/1349371/40233567-d203644c-5aa3-11e8-90da-c6892c28109e.png)

**Comment by tzanio** [comment]
I can't reproduce, `./ex9 -m ../data/amr-quad.mesh -p 1 -r 2 -dt 0.002 -tf 9` seems to work fine for me.

**Comment by jakubcerveny** [comment]
I can't reproduce either, even on the machine where I observed this, it must have been some confusion. Closing.
