### ISSUE TITLE
Extending Example 18: DG Euler Equations

### ISSUE THREAD

**Issue by sakupkmnc616** [mfem/mfem#496]
Hello,
 
I am a new user to mfem and would like to use mfem to solve compressible Euler equations. 

Is it possible to extend example 18: DG Euler Equations to implicit time stepping with triangular mesh? If yes, could I get some advise of how to achieve this?

Thanks in advance!

Henry

**Comment by jdahm** [comment]
Hi Henry,

It is certainly possible to extend it to these cases. In fact, the example should be able to work with triangular meshes now, but as far as I can tell there is no periodic mesh that uses triangles included in the MFEM data directory. You could implement a different boundary condition and use a triangular mesh that MFEM provides.

Extending it to implicit time stepping poses no challenges for MFEM, but is beyond the scope of a simple example. Doing so requires computing derivatives of the fluxes, which can become quite a bit of code for a nonlinear system like this. Example 16 (nonlinear scalar diffusion) is a good example to follow of adding implicit time-stepping - the gist of it is that you need to implement `FE_Evolution::ImplicitSolve`.

I hope this helps,
Johann

**Comment by sakupkmnc616** [comment]
Hello Johann,

Thanks for the response!!

Would it be possible to link mfem to Sacado in the Trilinos package to perform automatic differentiation in order to prevent computation of the derivative of the fluxes?

Thanks again!

Henry

**Comment by jdahm** [comment]
Certainly. All you need to provide is a means of obtaining the vector `du/dt` given a scalar timestep `dt`, and an input state vector `u`. How you implement that is entirely up to the application. Inside that method it can certainly call an AD package.

**Comment by stefanozampini** [comment]
You can use petsc and obtain a matrix-free action of the Jacobian, or a
finite-differenced assembly. Just use a PetscOdeSolver , see ex9 in the
petsc subdirectory for an example

Il Ven 18 Mag 2018, 23:46 sakupkmnc616 <notifications@github.com> ha
scritto:

**Comment by sakupkmnc616** [comment]
Hello all,

Thanks for the response!!

If I encounter any problems/issues, I will post them on this discussion thread!

Henry

**Comment by jdahm** [comment]
Glad we could help! I'm closing for now, but feel free to open it again if you have questions.
