### ISSUE TITLE
Questions about GetImplicitGradient method in petsc/example 9

### ISSUE THREAD

**Issue by sakupkmnc616** [mfem/mfem#505]
Hello, I have two questions about the `GetImplicitGradient` method implemented in petsc example 9 (Petsc version of DG Advection). 

Below is the `GetImplicitGradient` method:

![image](https://user-images.githubusercontent.com/18222135/40744288-12110062-6422-11e8-8d43-cebf03b48c70.png)

**Question 1:** I know the following line of code:

`iJacobian = new PetscParMatrix(&M, Operator::PETSC_MATAIJ);`

creates new parallel matrix (for the petsc version). I will like to ask, what does the parameter `Operator::PETSC_MATAIJ` do? Is it a parameter that is use to tell `PetscParMatrix` to perform automatic differentiation? 

The reason for asking is in `GetExplicitGradient`, when the time stepping scheme is implicit, it does something similar, i.e.: 

`rJacobian = new PetscParMatrix(&K, Operator::PETSC_MATAIJ);`

and then it returns `*rJacobian`.

**Question 2:** Is it ok if I get more explanation for the equation below?

`shift*F_du/dt + F_u`

In particular, what is `shift` and what does it do?

**Question 3:** After creating `iJacobian`, it does:

`*iJacobian *= shift`

where is the additional term `F_u` that we are supposed to add (referring to `shift*F_du/dt + F_u`)?

Thanks in advance.

Henry

**Comment by jandrej** [comment]
1. `Operator::PETSC_MATAIJ` is just the matrix type the new PETSc Mat uses.

2. The PETSc manual has more detailed info, but `shift` is a constant which contains terms like `dt` (the timestep) depending on the method used for time integration.

3. I guess @stefanozampini can answer that.

**Comment by sakupkmnc616** [comment]
Hello Julian,

Thanks a lot for the response! I will look at the PETSc manual to get more details on `shift`.

Henry

**Comment by v-dobrev** [comment]
Regarding your 3rd question: here the documentation of `GetImplicitGradient` which briefly describes what the method must do when implemented in derived classes:

https://github.com/mfem/mfem/blob/a7e2df44c6032d558762e0a6a30433ceaf61149b/linalg/operator.hpp#L239-L245

Here, `F = F(x,k,t)` refers to the so-called _implicit_ part of the `TimeDependentOperator`, see the class description:

https://github.com/mfem/mfem/blob/a7e2df44c6032d558762e0a6a30433ceaf61149b/linalg/operator.hpp#L146-L151

In the PETSc version of `ex9p`, the implicit part of the `FE_Evolution` operator is simply `F(u,k,t) = M k` where `M` is the mass matrix, given as input to the `FE_Evolution` constructor, and `k` is just a variable name for `du/dt`. In particular, in this case `dF_du` (denoted in the comment at line 569 as `F_u`) is zero.

**Comment by sakupkmnc616** [comment]
Hello,

Thanks a lot for the response! 

If I have any more questions, I will post on this forum again!

Cheers,

Henry
