### ISSUE TITLE
Modifying example 18: DG Euler Equations to solve 1D sod shock tube problem

### ISSUE THREAD

**Issue by sakupkmnc616** [mfem/mfem#509]
Hello,

I am new to MFEM and am currently trying to solve the 1D sod shock tube problem using code for 2D DG Euler Equations (Example 18).  

My computational domain is [ 0, 1 ] x [ 0, 1 ]. Since I am trying to solve a 1D problem using 2D DG Euler, I impose Dirichlet boundary conditions on x = 0 and x = 1 and periodic boundary conditions on y = 0 and y = 1. 

The Dirichlet B.C.s for the 1D sod shock tube is as follows:
 
At x = 0, den = 1, pres = 1, velX = 0, and
at x = 1, den = 0.125, pres = 0.1 and velX = 0,

(I calculate energy using the formula for pressure described in the link: http://www.csun.edu/~jb715473/examples/euler1d.htm#density)

I have read ex1 and ex2 (serial, parallel and petsc) to see how to incorporate Dirichlet boundary conditions. From what I understand from example 1 and example 2, to enforce the Dirichlet boundary condition is u = 0, we do the following:

```c++
ParGridFunction x(fespace);
x = 0.0;
```

I have the following questions (bold-font the questions to make the post clearer):

**1. How do I modify ex18p (or ex18) to accommodate the above Dirichlet boundary conditions (that depends on the value on the x-axis) for the 1D sod shock tube?**

So far, I have defined a mesh file with two boundary attributes 1 and 2 (to accommodate two Dirichlet boundary conditions) and have periodic nodes on the y-axis. I have also modified the method `InitialConditions` in `ex18.hpp` to accommodate the initial conditions of the 1D sod tube problem. 

To enforce B.C.s, I know I need to do something along the lines of example 2, where I will need to have an array called `ess_bdr` and probably do the following:

```c++
Array<int> ess_tdof_list, ess_bdr(mesh->bdr_attributes.Max());
ess_bdr = 0;
ess_bdr[0] = 1;
ess_bdr[1] = 2;
fespace->GetEssentialTrueDofs(ess_bdr, ess_tdof_list);
```

However, after that, I do not know what variables to set in order to enforce the two different Dirichlet B.C.s that depends on the value on the x-axis. I saw variables like `u_block` (that stores components density, x-momentum, y-momentum, energy), `mom` (momentum grid function) and `sol` (state).  Do I simply set the components of `u_block`? If yes, how do I check for the values of x to determine what values to set for the `u_block` entries?

**Question 2: I noticed that in example 1, when handling B.C.s,** `ess_bdr = 1` **while in example 2,** `ess_bdr = 0`**. Is there a reason why**  `ess_bdr` **is different for examples 1 and 2? Is it related to the mesh we are using for the problem?**

For the sod tube problem, I am using a square/rectangular mesh that is periodic in the y-axis (with Dirichlet B.C. on x = 0 and x = 1). So I have created a mesh that is similar to the mesh in `periodic-square.mesh`. 

Thanks in advance!

Regards,

Henry

**Comment by jandrej** [comment]
You are correct on the general concept of the block vectors used in ex18. They are ordered like `{density, x-momentum, y-momentum, energy}`. The other GridFunctions like `sol` and `mom` are just "shortcuts" carrying references to parts of `u_block`. If you apply your Dirichlet boundary conditions to the corresponding block and make a few changes to the solving process to accept the `ess_bdr` Array, I assume this should work.

Regarding your second question you have to keep in mind that ex1 has just one boundary value (all Dirichlet) while ex2 has mixed boundary conditions. So in ex1 you do `ess_bdr = 1` to set every boundary to of type Dirichlet.

In ex2 you do
```
   ess_bdr = 0;
   ess_bdr[0] = 1;
```
to first set every boundary to _not_ Dirichlet and after that set the boundary 0 to be a Dirichlet boundary.

**Comment by vikramsg** [comment]
This is not a direct answer to your question, but usually imposing Dirichlet conditions directly can be unstable. It is generally recommended to impose Dirichlet conditions weakly. So, here you should be adding a NonLinearForm integrator only on the boundary faces and impose condition like this

U_R = 2*D - U_L

where D is your Dirichlet condition, U_L is the values extrapolated to the face and then getting the flux values as F(U_L, U_R) using the Riemann solver.

**Comment by tzanio** [comment]
@jdahm do you have any advice for @sakupkmnc616 how best to impose Dirichlet and periodic boundary conditions in the DG formulation in ex18.

**Comment by jdahm** [comment]
Yes I do. Sorry to not jump in here sooner.

@vikramsg is correct that imposing boundary conditions in that way is unstable, and furthermore will probably lead to reduced convergence rates depending on the output.

The problem with hyperbolic equations such as Euler is that even if you change the integrator on the external boundary faces, it’s not gauranteed to work. The equations introduce information and remove it from the domain alongcharacteristics, which since this is a nonlinear set of equations, changes and on a given face can go in both directions! So specifying e.g. 2 pieces of information on one boundary might be under- or over-specifying the problem leading to a badly posed discrete system.

The safe (but not always what you want) approach is to impose a state on the other side of a boundary and use a Riemann solver on the interface to compute the flux. This is a weak enforcement, as @vikramsg sugge

**Comment by jdahm** [comment]
The answer above is only straightforward for first-order systems of equations. If you have a second order term (parabolic system), the discretization becomes more difficult.

**Comment by sakupkmnc616** [comment]
Hello all, 

Thanks a lot for the responses! I will work more on it. If I have anymore questions, I will post on this discussion forum.

Cheers,

Henry

**Comment by sayantan-96** [comment]
@sakupkmnc616 
Hello, I'm currently working on the shocktube problem. I have used an inline segment mesh for the 1D domain. Were you able to get the boundary conditions working correctly for the problem? If so can you elaborate a bit on the changes you adapted to ex18 for the boundary conditions
