### ISSUE TITLE
Shape regularity for adaptive tetrahedral meshes

### ISSUE THREAD

**Issue by aschaf** [mfem/mfem#512]
Hello,

it seems that using adaptive mesh refinement on tetrahedral meshes destroys the shape regularity of the mesh. 

In order to avoid any influences from my own code, I modified Example 6 (serial) such that it calls the function `Mesh::PrintCharacteristics(...)` in each AMR iteration and increased the maximum number of dofs up to 500000, i.e.,
```
...
const int max_dofs = 500000;
for (int it = 0; ; it++)
{
   ...
   Vector v1, v2;
   mesh.PrintCharacteristics(&v1, &v2, std::cout);
   ...
}
...
```
I tested the mesh [data/inline-tet.mesh](https://github.com/mfem/mfem/blob/master/data/inline-tet.mesh)  and monitored the behavior of `kappa_min`and `kappa_max` where you can see that `kappa_max` is increasing dramatically during the iterations (c.f. below).
![ex6_kappa_cube](https://user-images.githubusercontent.com/35033720/41221549-b4ae4366-6d64-11e8-866f-37ecd6ef1d75.png)

I tested also a second mesh which i created with NETGEN ([mesh.zip](https://github.com/mfem/mfem/files/2089741/mesh.zip)), a big cube with one smaller cube cut out in a corner. Here, the value of `kappa_max` increases even more than before (c.f. below)
![ex6_kappa_lshape](https://user-images.githubusercontent.com/35033720/41221568-cc1739b8-6d64-11e8-887e-69dc04874728.png)

Best regards,
Andreas

**Comment by v-dobrev** [comment]
Hi Andreas,

Your observation is correct - when using local refinement on tet meshes the algorithm used in MFEM does not guarantee preservation of shape regularity.

The reason for this behavior lies in an implementation choice that simplifies the implementation but has this drawback.

Fixing this issue will require some changes in the code that may not be too hard to make. If you are interested in working on this, I'll be happy to help with figuring out a simple way to fix this.

Alternatively, you may want to try the new PUMI (https://scorec.rpi.edu/pumi) support in MFEM: see e.g. http://mfem.github.io/doxygen/html/pumi_8hpp.html.

**Comment by v-dobrev** [comment]
Also, I forgot to mention,  you can take a look at the PUMI examples in [`examples/pumi`](https://github.com/mfem/mfem/tree/master/examples/pumi).

**Comment by aschaf** [comment]
Hi Veselin,

thank you for the clarification.

For now, I will try to use PUMI, but I can try to fix this issue at some later point as I want to get familiar with the structure behind the MFEM mesh anyways.

Best regards,
Andreas

**Comment by v-dobrev** [comment]
Hi Andreas,

I can suggest the following approach for fixing the issue:

I think the simplest way to fix the refinement algorithm for tetrahedral meshes is to replace the `DSTable` here
https://github.com/mfem/mfem/blob/f950613551edb07f1a075b091062e8d0a3e9d388/mesh/mesh.cpp#L5900-L5902
with a `HashTable<Hashed2>` object. This will require changes in all places where the `DSTable` object, `v_to_v`, is used. This replacement will allow you to insert new pairs of vertices (i.e. new edges) into the `HashTable<Hashed2>` which is not possible with the `DSTable` class when one of the vertices is a newly created vertex (middle of one of the bisected edges). When using a `HashTable<Hashed2>`, there is no need to initialize it with all edges in the starting mesh - only edges that are being refined (bisected) need to be added dynamically. The index of the newly inserted edge can then be used (after adding to it the number of vertices in the starting mesh) as the index for the new vertex in the middle of the bisected edge. With this approach, I think, there is no need for the `middle` array allocated and initialized here
https://github.com/mfem/mfem/blob/f950613551edb07f1a075b091062e8d0a3e9d388/mesh/mesh.cpp#L5906-L5911

Does this make sense?

Do you have another idea about how to fix the issue?

Thanks,
Veselin

**Comment by aschaf** [comment]
Hi Veselin,

thank you for your help I will try to implement this accordingly. 

> Do you have another idea about how to fix the issue?

I have read through the other thread somehow addressing this issue, #259 and also the paper by Arnold et al. referenced therein. If I understood correctly, MFEM's modification only consists of un-marking the Pf type tets and performing at most 3 levels of bisection per tet. This is because `DSTable` is not able to insert newly created vertices/edges. So changing the object to something similar of `std::map<std::pair,int>` would have also been my first approach. 

Best regards,
Andreas
