### ISSUE TITLE
MFEM Attributes when using PUMI meshes

### ISSUE THREAD

**Issue by aschaf** [mfem/mfem#517]
Hello again,

is there some way to have element attributes in MFEM when using PUMI meshes? I have looked in the source file of `mfem::ParPumiMesh` and saw that you just set the attribute to 1. 

Is it possible to assign somehow such an attribute also to the corresponding PUMI mesh elements? I tried using `apf::MeshTag` from PUMI itself to tag the `apf::MeshEntity` objects. But this stops working after refining the mesh, as then some `apf::MeshEntity` objects, I guess the new ones, no longer have this `apf::MeshTag`.

Best regards,
Andreas

**Comment by aschaf** [comment]
Hello Kazem,

thank you for the detailed explanation, the concept is now much more clear to me.

Can you recommend me a way to convert my NETGEN and MFEM meshes to a PUMI model and mesh?

Andreas

**Comment by KazemKamran** [comment]
Andreas, 

 Do you have a CAD model, preferably parasolid, of your problem? It is much cleaner if we start from a CAD model than a mesh. If your geometry is non-trivial then I assume you have a CAD model of that. 

Kazem

**Comment by cwsmith** [comment]
Hello,

Using gmsh you can define your model and mesh and convert them to PUMI formats with classification preserved:
https://github.com/SCOREC/gmshToPumi
With the classification you can define attributes as needed as described by [Kazem](https://github.com/mfem/mfem/issues/517#issuecomment-399274114).
