### ISSUE TITLE
".mesh" mesh with GMSH

### ISSUE THREAD

**Issue by LeilaSalomon** [mfem/mfem#518]
Hello,

I would like to make my own mesh with GMSH. After exporting my mesh to ".mesh", I notice that the mesh file obtained doesnt' look like the standard format used by MFEM and GlVIS. How can I use a good mesh format with GMSH?

Best regards,
Leïla

**Comment by v-dobrev** [comment]
The MFEM `Mesh` class will try to detect various formats it supports. The simplest way is to just try to view the mesh in GLVis: `./glvis -m path/to/file.mesh`. MFEM (and therefore GLVis) should be able to recognize and read linear GMSH meshes.

**Comment by tzanio** [comment]
Hi Leïla,

To add to @v-dobrev's answer -- the Gmsh support was added in this PR: https://github.com/mfem/mfem/pull/51 by @martemyev. For the mesh types that MFEM supports (tri/quad/tet/hex), you should be able to use a Gmsh mesh in ASCII or Binary format. Note that mixed meshes may not be fully supported, so it is probably best to stick with pure tet meshes in 3D.

Let us know if you have any issues.

Tzanio

**Comment by LeilaSalomon** [comment]
After generating a mesh in GMSH, what format does the mesh save in to be recognized by the library? 
The ".mesh" format is not recognized by GLVIS.

**Comment by sshiraiwa** [comment]
Normally, GMSH generate .msh (not .mesh) and GLVIS is supposed
to load it.

**Comment by vikramsg** [comment]
@LeilaSalomon To add to what @sshiraiwa said, GMSH does not output in the MFEM .mesh format. But the native GMSH format .msh is readable in MFEM. I have actually used mixed meshes as well in MFEM and it seems to be fine, but maybe try what @tzanio suggested first.

**Comment by martemyev** [comment]
@LeilaSalomon would you mind sharing the mesh file you're having issues with?

**Comment by LeilaSalomon** [comment]
<img width="476" alt="capture" src="https://user-images.githubusercontent.com/40572513/42151455-5e4fcd94-7ddd-11e8-8842-9a9dea1978ba.PNG">

**Comment by sshiraiwa** [comment]
I am not sure what is going on here, but this format doesn't look like the usual GMSH file I am used to. GMSH in my environment uses $Nodes - $EndNodes instead of $NOD-$ENDNODE. After quick google search, I found $NOD-$ENDNODE might have been used in the legacy file format, but still the  node data in $NOD segment does not make sense. Should it be like this?

$NOD
number-of-nodes
node-number x-coord y-coord z-coord
…
$ENDNOD

**Comment by tzanio** [comment]
This looks like an old Gmsh format, which we do not support: http://gmsh.info/doc/texinfo/gmsh.html#Legacy-formats

Can you use a newer version of Gmsh?

**Comment by LeilaSalomon** [comment]
What is the last version? I thought I had it

**Comment by v-dobrev** [comment]
According to http://gmsh.info/ the latest version is 3.0.6.

You probably exported by accident into "Version 1" format -- this choice is in the "MSH Options" dialog that appears after you choose the filename -- try switching to "Version 2 ASCII".

This applies to version 2.12 of Gmsh but I assume it is not that different in newer versions.

**Comment by LeilaSalomon** [comment]
Can you tell me which command line should I use in GLVis to visualize the "Version 2 ASCII" mesh?

**Comment by tzanio** [comment]
`glvis -m your-file.gmsh`

**Comment by vikramsg** [comment]
@LeilaSalomon It reads only linear meshes. But I hope at some point there will be one built in.

**Comment by LeilaSalomon** [comment]
@vikramsg Ok, so how can I make a mesh with elements of second order can be read by GLVis ?

**Comment by v-dobrev** [comment]
@LeilaSalomon, for second order meshes, try exporting to VTK format. MFEM and GLVis can read second order unstructured VTK meshes.
