### ISSUE TITLE
DerivativeIntegrator does not check the order of integration rule used

### ISSUE THREAD

**Issue by homijan** [mfem/mfem#52]
Dear MFEM developers,

I have had a problem at the line 949  of bilininteg.cpp in the function 
"void DerivativeIntegrator::AssembleElementMatrix2()".
This was due to the order of trial_fe and test_fe was zero for both of them in my particular case, 
and consequently, the construction of integration rule at the line 962 was called with order = -1.
I know that calling the DerivativeIntegrator on constant trial&test functions does not make much sense, but this happened during some tests, where I expected the derivative term to simply disappear, i.e. returns zero. Would you mind to add an easy check that treats this issue?

Thanks,
Milan

**Comment by tzanio** [comment]
Hi Milan,

Can you try the latest release (v3.1)? I think we should be OK with negative quadrature orders now, since the following sets the order to zero: https://github.com/mfem/mfem/blob/master/fem/intrules.cpp#L254

Cheers,
Tzanio

**Comment by tzanio** [comment]
Hi @homijan, did you get a chance to try this with v3.1? -Tzanio

**Comment by homijan** [comment]
Hi Tzanio,

it has solved the problem!
Thanks.

Cheers,
Milan

**Comment by tzanio** [comment]
Thanks, Milan!
