### ISSUE TITLE
Operator Question

### ISSUE THREAD

**Issue by nickwhitman1993** [mfem/mfem#520]
Hi - I have an interesting operator I am dealing with - I am trying to implement a Self-Adjoint Angular Flux transport equation.

![saaf](https://user-images.githubusercontent.com/23174133/42012048-3615f640-7a4b-11e8-9d59-18ee089c0e96.png)

I have a working version of a discrete ordinates (Sn) transport equation (thanks to a colleague) which uses a streaming operator that looks something like this: 

![first-order](https://user-images.githubusercontent.com/23174133/42012055-3b53d794-7a4b-11e8-9890-bec282dc9b3e.png)

EDIT: no negative sign in front of Omega dot Grad psi

Omega is currently passed in as a vector. I believe he handles the operator in two parts (I believe that he mentioned it is handled better this way). It looks something like this:

```c++
  // Add convection term within the zones
  mfem::BilinearFormIntegrator *convection =
      new mfem::ConvectionIntegrator(omega, +1.0);
  convection->SetIntRule(&elIntRule);
  L.AddDomainIntegrator(convection);

  // Upwind fluxes between zones on each face interior to mesh
  // For surface, we need a boundary geometry integration rule and order
  mfem::BilinearFormIntegrator *traceInterior =
      new mfem::DGTraceIntegrator(omega, -1.0, +0.5);
  traceInterior->SetIntRule(&bdrIntRule);

  // MFEM ISSUE: Maybe have the transpose operator pass along the setting of the
  // IntRule
  // to its owned worker.  Or at least throw an error.
  mfem::BilinearFormIntegrator *transInterior =
      new mfem::TransposeIntegrator(traceInterior);
  L.AddInteriorFaceIntegrator(transInterior);

  // Now add the inflow boundary conditions to the matrix and RHSs
  // need to SetIntRule on the DGTraceIntegrator rather than the
  // TransposeIntegrator
  mfem::BilinearFormIntegrator *traceBdr =
      new mfem::DGTraceIntegrator(omega, -1.0, +0.5);
  traceBdr->SetIntRule(&bdrIntRule);
  mfem::BilinearFormIntegrator *transBdr =
      new mfem::TransposeIntegrator(traceBdr);
  L.AddBdrFaceIntegrator(transBdr);
```

My question is this: how would you suggest the implementation of this operator? My only idea right now is to basically do what is done with his code, but twice and adding the constant 1/sigma_T (eventually this might have to be passed in as a vector, data might change in every direction/ordinate...). 

Any comments or directions are greatly appreciated.

**Comment by tzanio** [comment]
@terryhaut, @pgmaginot, @vladotomov or @homijan -- can you help @nickwhitman1993?

**Comment by terryhaut** [comment]
Hi Nick,

I haven't solved the second order version of the transport equation in MFEM before (only the first order discrete ordinates version of transport) That being said, I see at least two possible approaches that I see for doing this. 

The first approach could start from the continuum version of your second order transport equation, and discretize this equation using a H1 function space (spatial derivatives of psi are L2 integrable). In particular, you would write this equation in weak form and then use the diffusion integrator DiffusionIntegrator class to handle the second order term. 

The second approach is more along the lines of what you are suggesting: start from the discretized version of the transport equation that you described in your message (e.g. using DGTraceIntegrator). Then you would do the same derivation as for the continuous version, which corresponds to writing the normal equations for this system and doing some algebraic manipulation. In particular, you would multiply the first order discretized equation by the adjoint of the discrete version of \Omega \cdot \nabla_x (the discrete version should contain the appropriate interior and face boundary terms as well), and then proceed as before. Note that you can convert a parallel bilinearform to a parallel hypre matrix and do the matrix-matrix multiplication. 

Hope this helps! Let me know if you want to discuss further.

**Comment by nickwhitman1993** [comment]
Thank you @terryhaut for your response. I will be in contact again shortly. I would appreciate some further discussion after I have a chance to discuss with my advisor.

**Comment by nickwhitman1993** [comment]
@terryhaut 

I have successfully implemented the second-order operator with a tensor diffusion coefficient (I believe). 

However, in the first-order equation inflow boundary conditions are just needed. In this formulation, I need _outflow_ boundary conditions for every boundary as well as inflow..

It looks like this:

![gif 1](https://user-images.githubusercontent.com/23174133/44054595-d4dc97c2-9ef7-11e8-821e-0302acfb451a.gif)

Where \Omega is a predefined VectorFunctionCoefficient which is passed in to the code. 

Where the first portion is simply for the external source which I define. This already works using a BoundaryFlowIntegrator in which the "inflow" FunctionCoefficient and \Omega direction vector VectorFunctionCoefficient is used.
The second portion is the second condition required to close the second-order formulation. 

Do you know how I might go about implementing the second portion to this as simply as possible? I apologize if I am looking over something simple, but I have tried many different variations.

My current thoughts are to use a ConvectionIntegrator and a BoundaryMassIntegrator but I am not sure..

I believe this boils down to a Dirichlet boundary condition on the inflow boundaries and a Robin or Mixed boundary condition on the outflow boundaries. 

Again, your help is so much appreciated!

**Comment by nickwhitman1993** [comment]
@terryhaut @pgmaginot @vladotomov @homijan

Hi again,

As it turns out, I was able to use DiffusionIntegrator to handle the second order term using a MatrixFunctionCoefficient for the tensor of Omegas (the direction vector). 

However, I have some very interesting boundary conditions that I need to use. For this equation I not only need to specify the inflow boundary conditions for each angle Omega, but the outflow boundary conditions for each Omega as well.. It looks something like this:

![gif 1](https://user-images.githubusercontent.com/23174133/44239968-d367bb80-a170-11e8-9e89-36e7a86f301c.gif)

which should essentially be a Dirichlet boundary condition for the incoming directions and a Robin boundary condition on the outflow direction.

For example - right now I am currently trying to test a problem that is driven by an external source (for each Omega direction) on the left face (i.e. x = 0) (with no internal driving sources or scattering) that should attenuate through the material. The equations then reduce to the left side of the second-order form = 0 (in my first post) but with the given boundary conditions. 

Do you have any recommendations on how to implement this? I currently only have something like this so far:

    //Create tensor for -Grad dot OmegaOmega/sigma_t Grad psi
    mfem::BilinearFormIntegrator *tensor1 =
        new mfem::DiffusionIntegrator(omega_tensor);
    tensor1->SetIntRule(&elIntRule);
    L.AddDomainIntegrator(tensor1);

    mfem::BilinearFormIntegrator *mass = new mfem::MassIntegrator(sigma_t);
    mass->SetIntRule(&elIntRule);
    L.AddDomainIntegrator(mass);

    mfem::LinearFormIntegrator *BndryFlow =
        new mfem::BoundaryFlowIntegrator(inflow, omega, -1.0, -0.5);
    BndryFlow->SetIntRule(&bdrIntRule);
    b.AddBdrFaceIntegrator(BndryFlow); // MFEM 3.2

where the inflow function is defined in another file. 

Do you have any suggestions on how to proceed? I tried my best to work through some of the other examples but to no avail.

I appreciate your time and thanks again for your help!

-Nick
