### ISSUE TITLE
Issue in building MFEM on Vulcan

### ISSUE THREAD

**Issue by Saptarshibh** [mfem/mfem#523]
I am trying to build mfem on Vulcan and I am getting errors. I am following the steps below.
cd config
cp defaults.mk user.mk
Open user.mk in an editor
In place of CXX write CXX = bgxlC
In place of MPICXX write MPICXX = mpixlcxx
OPTIM_FLAGS = -O2
MFEM_USE_MPI         = YES
MFEM_MPIEXEC    = srun
MFEM_MPIEXEC_NP = -n
 
Save File
cd ..
make config USER_CONFIG=config/user.mk
make parallel -j10. 

below is the error I am getting
===============ERRORS================================================

.
mpixlcxx  -O3 -I./../hypre-2.10.0b/src/hypre/include  -c fem/pgridfunc.cpp -o fem/pgridfunc.o
    1500-036: (I) The NOSTRICT option (default at OPT(3)) has the potential to alter the semantics of a program.  Please refer to documentation on the STRICT/NOSTRICT option for more information.
mpixlcxx  -O3 -I./../hypre-2.10.0b/src/hypre/include  -c fem/plinearform.cpp -o fem/plinearform.o
    1500-036: (I) The NOSTRICT option (default at OPT(3)) has the potential to alter the semantics of a program.  Please refer to documentation on the STRICT/NOSTRICT option for more information.
mpixlcxx  -O3 -I./../hypre-2.10.0b/src/hypre/include  -c fem/pnonlinearform.cpp -o fem/pnonlinearform.o
mpixlcxx  -O3 -I./../hypre-2.10.0b/src/hypre/include  -c fem/sidredatacollection.cpp -o fem/sidredatacollection.o
mpixlcxx  -O3 -I./../hypre-2.10.0b/src/hypre/include  -c fem/staticcond.cpp -o fem/staticcond.o
    1500-036: (I) The NOSTRICT option (default at OPT(3)) has the potential to alter the semantics of a program.  Please refer to documentation on the STRICT/NOSTRICT option for more information.
"fem/pfespace.cpp", line 2390.6: 1540-0290 (S) The function template parameter "T" has been found to have two values: "double" and "T".
make[1]: *** [fem/pfespace.o] Error 1
make[1]: *** Waiting for unfinished jobs....
    1500-036: (I) The NOSTRICT option (default at OPT(3)) has the potential to alter the semantics of a program.  Please refer to documentation on the STRICT/NOSTRICT option for more information.
    1500-036: (I) The NOSTRICT option (default at OPT(3)) has the potential to alter the semantics of a program.  Please refer to documentation on the STRICT/NOSTRICT option for more information.
make[1]: Leaving directory `/g/g92/bhowmik1/proxyapps/bgqos_0/Laghos/mfem'
make: *** [parallel] Error 2

**Comment by tzanio** [comment]
Hi Saptarshibh,

Can you try building MFEM with the [CEED/benchmarks](https://github.com/CEED/benchmarks) repository?

See in particular the following files:

https://github.com/CEED/benchmarks/blob/master/machine-configs/vulcan.sh
https://github.com/CEED/benchmarks/blob/master/package-builders/mfem.sh

Tzanio

**Comment by Saptarshibh** [comment]
Thank you Tzanio,
Sure, I am trying to build it with ceed/benchmark.
Regards,
Saptarshi Bhowmik

**Comment by tzanio** [comment]
Hi Saptarshibh, were you able to complete the build?

**Comment by Saptarshibh** [comment]
Hi Tzanio,
Thank you for the help. I was able to build mfem on Vulcan.Thnk you so much.
Reagrds,
Sap Bhowmik
