### ISSUE TITLE
mesh v1.x format

### ISSUE THREAD

**Issue by LeilaSalomon** [mfem/mfem#524]
Hello,

I would like to know how one can get one's own mesh in "mesh v1.x" format.
For example, I would like to use Example 1 with my own mesh, how to do?

Best regards,
Leïla

**Comment by tzanio** [comment]
Hi Leïla,

If you want to use the MFEM format exactly, you can: 1)write one by hand (following the specification) or 2) use one of the tools is `miniapps/meshing`, such as `mobius-strip` or `mesh-optimizer` to generate it.

If your goal is just to use a mesh you already have with MFEM, you can 1) put it in one of the [formats we support](http://mfem.org/meshing/) e.g. VTK, NetGen or Gmsh, 2) convert from that to the MFEM specification, or 3) add a reader for that format in MFEM.

Hope this helps,
Tzanio

**Comment by tzanio** [comment]
Closing. See follow-up in #518.
