### ISSUE TITLE
Support for p-type nonconformity?

### ISSUE THREAD

**Issue by cuneytsert** [mfem/mfem#525]
Does MFEM support p-type nonconforming elements, i.e. geometrically conforming neighboring elements with different orders?

**Comment by jakubcerveny** [comment]
Hi @cuneytsert, this is currently not possible.

**Comment by cuneytsert** [comment]
Thanks for the answer. Are there any plans to implement this?

**Comment by jakubcerveny** [comment]
I think @tzanio or @v-dobrev will be able to answer that.

**Comment by tzanio** [comment]
Hi @cuneytsert, hp-methods are not a focus of our group currently so we don't have near-term plans to support them in the library. Long-term, we are definitely interested in having such support, and the  "conforming matrix" framework in MFEM should naturally support p-type nonconforming elements.

Some MFEM users have already done work in that direction: @vikramsg

**Comment by vikramsg** [comment]
Hi @cuneytsert, 

I have a working implementation for variable p. Unfortunately its a little complex because there were some issues that I simply bypassed such as making it work with AMR just to get it working. I never really cleaned it up to put up a PR.

**Comment by v-dobrev** [comment]
Related previous discussion: #211.
