### ISSUE TITLE
Missing HTML files for ex1 and ex1p

### ISSUE THREAD

**Issue by cuneytsert** [mfem/mfem#527]
When I issue make in the doc folder to generate the documentation files, the links in index.html for ex1 and ex1p turn out to be broken. That is ex1_8cpp_source.html and ex1p_8cpp_source.html files are missing. Links for the other examples are working OK.

**Comment by tzanio** [comment]
Can you pull the latest master and try again?

The current version of https://github.com/mfem/mfem/blob/master/doc/CodeDocumentation.dox links to `examples_2ex1_8cpp_source.html` etc.

**Comment by cuneytsert** [comment]
It is working on the latest master.

**Comment by v-dobrev** [comment]
The Doxygen documentation is also available online: http://mfem.github.io/doxygen/html/index.html
