### ISSUE TITLE
Tag & publish a release of version 3.1.

### ISSUE THREAD

**Issue by goxberry** [mfem/mfem#53]
I'd like to write a package for MFEM in [homebrew-science](https://github.com/Homebrew/homebrew-science) based on the one I wrote in [spack](https://github.com/LLNL/spack/pull/749). Most package managers (including Homebrew) require a tarball, and won't accept packages that don't have one. This tarball can be created via a tagged release of MFEM version 3.1 on GitHub (see instructions [here](https://help.github.com/articles/creating-releases/)). Once a tarball is created, I can add an MFEM package to Homebrew, and update my pull request with an MFEM package in spack.

**Comment by tzanio** [comment]
Hi @goxberry,

Thank you for doing this, we very much appreciate it!

There have actually been a few other mfem/spack efforts at LLNL, but you beat them to the official repo :). Do you mind if I point them to your PR in case they have any additional feedback?

Regarding the releases, we actually strongly prefer to use the goo.gl short links for the tarballs, which you can find e.g. at http://mfem.org/download. For v3.1 the link is http://goo.gl/xrScXn. We understand that this is not the prefered way of doing things, but it is the only way we have to track download stats, which is important for our funding. Can this be made to work with spack and homebrew?

We will be happy to help if we can. Thanks!

Tzanio

**Comment by goxberry** [comment]
You're welcome, Tzanio!

> Do you mind if I point them to your PR in case they have any additional feedback?
Feedback would be great! I'm pretty sure the dependencies in spack could be simplified, and I don't know if it's because I'm running into spack bugs (e.g., cmake) or because I am reasoning about the mfem dependency DAG in spack incorrectly.

> Regarding the releases, we actually strongly prefer to use the goo.gl short links for the tarballs, which you can find e.g. at http://mfem.org/download. For v3.1 the link is http://goo.gl/xrScXn. We understand that this is not the prefered way of doing things, but it is the only way we have to track download stats, which is important for our funding. Can this be made to work with spack and homebrew?

The short link works for homebrew. spack parses supplied URLs, so I think it looks for a file extension at the end. It's probably better to discuss solutions to this issue off-list in order to keep people using the goo.gl short links.

**Comment by tzanio** [comment]
Moving the discussion to email.
