### ISSUE TITLE
Curl of a scalar ?

### ISSUE THREAD

**Issue by LeilaSalomon** [mfem/mfem#532]
Hello,

I wanted to know if MFEM could calculate the curl of a scalar? 
If so, how can I do?

Best regards,

Leïla

**Comment by jcwright77** [comment]
That’s not mathematically defined. Do you mean something like curl a \hat{i}? That is curl of a single component vector? Curl only acts on vectors. Grad acts on scalars. 
-john

**Comment by v-dobrev** [comment]
The curl of a scalar function in 2D can be obtained by rotating its gradient: `(df/dx, df/dy)` -> `(df/dy, -df/dx)`. The gradient of a `GridFunction` can computed with one of the methods: `GetGradient` for a single point in one element, or `GetGradients` for multiple points in one element.

You can also compute the gradient of a `GridFunction` as another (vector) `GridFunction` by constructing and applying a discrete gradient operator - I can explain how to do that, if you want to obtain the grad and then the curl as a `GridFunction`.

Does one of these options work for you?

**Comment by jcwright77** [comment]
That is simply curl f \hat z as I wrote before. “Curl of a scalar” doesn’t mean anything. Can he simply do what I suggested and define the vector as f \hat z and take the curl? That is if that is what he really means since his question is ill defined. 

-john

**Comment by jcwright77** [comment]
Thanks for the explanation @dobrev. I wasn’t aware of that convention. Seems like something that might come up in 2D fluid mechanics. 
@LeilaSalomon let us know if this solution works for you. 
-john

**Comment by tzanio** [comment]
Hi Leïla, were you able to get this working? -Tzanio
