### ISSUE TITLE
Visualization with elements apart

### ISSUE THREAD

**Issue by kvoronin** [mfem/mfem#533]
Hello,

I'd like to visualize a 3D mesh (or a grid function, scalar or vector) from MFEM (in .mfem or any other format which MFEM is using to save a mesh) so that the elements are a little bit apart (with an epsilon of room between them) so that I can see how the mesh looks like inside the domain (without 'e' keystroke which will make all the elements transparent). Or visualize the mesh along the slicing plane (say, produced by 'i' and then rotated). Is it possible via GLVis?

For example, I am looking at http://glvis.org/gallery/, first column, third picture from above, titled as "Unstructured parallel decomposition of a fourth order NURBS mesh of the unit ball obtained in the solution of MFEM's parallel Example 1 on 16 processors."

Thanks,
Kirill

**Comment by tzanio** [comment]
See also the `e) View elements` option of the `mesh-explorer` miniapp (in the `miniapps/meshing` directory) followed by `F3`/`F4` in GLVis.

**Comment by kvoronin** [comment]
Thanks for the advice, @jakubcerveny!

For me, F11/F12 only zooms out/zooms the picture. I've manually set the elements attributes to (all) different values before visualization using SetAttribute(). In the terminal where glvis is running, I see messages like 
VisualizationSceneVector3d::PrepareFlat2() : [min,max] = [0.605352,1.84347] for vector data
and
VisualizationSceneSolution3d::PrepareFlat2() : [min,max] = [-6.20455e-17,1.25992] for scalar data
Can you tell me what is wrong?

**Comment by kvoronin** [comment]
Thanks @tzanio,
Your approach works for me.
