### ISSUE TITLE
eignevalue in DenseMatrix

### ISSUE THREAD

**Issue by tomzzh** [mfem/mfem#535]
Hello,
When I tried to use Eigenvalues in DenseMatrix class, it usually gave me the wrong message "DenseMatrix::Eigensystem
Abort trap: 6"
I have LAPACK installed in my laptop and turned to "YES" in default.mk file under config folder. I am just wondering how I can fix the issue. 
Thank you so much!

**Comment by tzanio** [comment]
Can you provide a simple reproducer that we can test?

**Comment by tomzzh** [comment]
Hello Tzanio,
Thanks for your reply; but what do you mean by reproducer? You want the code?

Thanks!

**Comment by tzanio** [comment]
Yes, I meant a small code that defines the matrix you use, calls `DenseMatrix::Eigensystem` and crashes in the same way that you observe.

**Comment by tomzzh** [comment]
Hello @tzanio,
Thanks for your email!
I have solved the problem by re-make the MFEM library after I changed NO to YES in defaults.mk.

Thank you!
