### ISSUE TITLE
[question] How to compute element centers?

### ISSUE THREAD

**Issue by goxberry** [mfem/mfem#537]
As part of work I'm doing with @mlstowell, I need to compute the center of every element in a `Mesh` -- specifically a `ParMesh`, but maybe this operation is worth doing on other similar types of objects.

It seems like one way to compute this information for an element in a `Mesh` would be to:

- get its `Geometry` type via `Mesh::GetElementBaseGeometry`
- get the center of that `Geometry` using `Geometry::GetCenter` as an `IntegrationPoint`
- get the element transformation from reference to physical(?) space via `Mesh::GetElementTransformation` as an `ElementTransformation`
- then apply the `ElementTransformation` via `ElementTransformation::Transform` to this `IntegrationPoint` to get a `Vector` with the coordinates of the element center

Is this sequence of steps correct? Is there a better or more idiomatic way to get element centers?

**Comment by tzanio** [comment]
Yes, that is the natural way to compute the element center in general. See, e.g. 

https://github.com/mfem/mfem/blob/4a3c6794a08a881c381ff729d91012c465035dc5/examples/pumi/ex2.cpp#L205-L221

**Comment by mlstowell** [comment]
HI, @goxberry ,
I did issue a pull request earlier today to add this functionality to the Mesh class, see branch [elem-center-dev ](https://github.com/mfem/mfem/pull/556).  It has already been approved and I expect it will appear in the next release of MFEM.
Best wishes,
Mark

**Comment by goxberry** [comment]
Thanks @mlstowell!
