### ISSUE TITLE
VectorRestrictedCoefficient::Eval size of Matrix

### ISSUE THREAD

**Issue by sshiraiwa** [mfem/mfem#539]
Hi all
I am having an memory corruption error when using this method. 
In the method,  I am wondering if `M.SetSize(vdim)` in the `else`
block blow should be `M.SetSize(vdim,  ir.GetNPoints())`? 

```c++
void VectorRestrictedCoefficient::Eval(
   DenseMatrix &M, ElementTransformation &T, const IntegrationRule &ir)
{
   if (active_attr[T.Attribute-1])
   {
      c->SetTime(GetTime());
      c->Eval(M, T, ir);
   }
   else
   {
      M.SetSize(vdim);
      M = 0.0;
   }
}
```

**Comment by v-dobrev** [comment]
Yes, I think you are absolutely right. Do you want to make a branch+PR to fix it?

Thanks for the bug report!
