### ISSUE TITLE
Usage of GridFunctionCoefficient

### ISSUE THREAD

**Issue by aasivas** [mfem/mfem#545]
Hi,
I have a question on how to use a GridFunctionCoefficient in DG spaces. The problem I encounter is everything is working very well for single process jobs, but if I try to run on multiple cores I get an error. I tried with ex14p with the modification below to provide minimal working example
```c++
   // 8. Define the solution vector x as a parallel finite element grid function
   //    corresponding to fespace. Initialize x with initial guess of zero.
   ParGridFunction x(fespace);
   ParGridFunction onex(fespace);
   x = 0.0;
   onex = 1.0;
   GridFunctionCoefficient onegf(&onex);

   // 9. Set up the bilinear form a(.,.) on the finite element space
   //    corresponding to the Laplacian operator -Delta, by adding the Diffusion
   //    domain integrator and the interior and boundary DG face integrators.
   //    Note that boundary conditions are imposed weakly in the form, so there
   //    is no need for dof elimination. After serial and parallel assembly we
   //    extract the corresponding parallel matrix A.
   ParBilinearForm *a = new ParBilinearForm(fespace);
   a->AddDomainIntegrator(new DiffusionIntegrator(onegf));
   a->AddInteriorFaceIntegrator(new DGDiffusionIntegrator(onegf, sigma, kappa));
   a->AddBdrFaceIntegrator(new DGDiffusionIntegrator(onegf, sigma, kappa));
```
To run: ```mpirun -np 2 ex14p -m ../data/inline-quad.mesh -o 0```
The error file: [ex14p.txt](https://github.com/mfem/mfem/files/2211734/ex14p.txt)

I am not sure if I am using GridFunctionCoefficient incorrectly, I would really appreciate if you could look into it. Also the MPI error is produced as a result of ```AddInteriorFaceIntegrator```, if I pass a ConstantCoefficient for interior faces while keeping it as a GridFunctionCoefficient for rest, everything works. However, it is not suitable for my application where I have a Picard iteration and I have to use the solution from previous step to create the new bilinear forms.

Best wishes,
Abdullah Ali Sivas

**Comment by v-dobrev** [comment]
I think the solution for this is to call `onex.ExchangeFaceNbrData()`- this will allow elements on the processor boundary to evaluate the `GridFunctionCoefficient` on adjacent elements owned by another processor.

**Comment by aasivas** [comment]
Thanks Veselin. This solved the MPI error. However, I still am not getting the correct result for my problem. I am working on a mwe now, can I keep this issue open until I get it?

**Comment by v-dobrev** [comment]
Sure, we can keep the issue open for now.

**Comment by aasivas** [comment]
Hi again,
I cannot reproduce the error I am getting with pure MFEM 3.4. It must be due to one of the integrators we created for HDG. We can close this issue now. Thanks a lot for your help.
