### ISSUE TITLE
eigenvalue of a generalized eigenvalue problem

### ISSUE THREAD

**Issue by tomzzh** [mfem/mfem#547]
Hi,
Does anyone know if there is a member function under DenseMatrix that can solve generalized eigenvalue problem, i.e. Av=\lambda Sv where A and S are of class DenseMatrix and they are symmetric positive definite and invertible.

Thanks a lot!
Tom

**Comment by mlstowell** [comment]
No, I don't think there is.  Although it wouldn't be difficult to write such a method.  One question would be should this be a member function of DenseMatrix or a "friend" function.

**Comment by tomzzh** [comment]
Hello @mlstowell @tzanio ,
Thanks for your reply! Do you mean I can derive the eigenvalue of the generalized system by using seem existing member functions of the class. I tried $S^{-1}Av=\lambda v$ and then using Eigenvalues of the class DenseMatrix.
My matrix A and S are of size 16 by 16, the problem is the eigenvalues I derived using MFEM are different from what I tested in Matlab using the same matrices A and S(do the same thing---just find eigenvalues of S^{-1}A). Do you have any suggestion on the issue? Thank you so much!

**Comment by mlstowell** [comment]
Hi, @tomzzh,
No, I did not mean that this could be done with existing members of the DenseMatrix class.  The trouble with S^{-1}A is that this matrix is not symmetric but MFEM's DenseMatrix class assumes the matrix will be symmetric when computing eigenvalues.  Consequently, we should not be surprised that Matlab gives a different result.

I do have some code somewhere that computes generalized eigenvalues using MFEM DenseMatrix objects.  I'll try to find it and paste it into a comment.
Mark

**Comment by tomzzh** [comment]
Hello @mlstowell,
Thanks for your code. You mean this code only works for the case A(a in your code) and S(b in your code) are symmetric and there is no other constrain on A and S? I am doing Generalized Multiscale Finite Element and my matrices are systemic for most of cases. I will read and try to test your code. Thanks again.

**Comment by mlstowell** [comment]
Hi, @tomzzh,

LAPACK routines are written in Fortran so they typically don't come with C or C++ compatible header files.  To load Fortran functions from C or C++ you need to declare the functions with their C equivalent argument types.  For the DenseMatrix class this is done near the top of densematrix.cpp where you can paste the following.  Note that the implementation that I posted earlier, everything after the first two lines, should be placed in densematrix.cpp someplace after the declaration of dsygv_. 

extern "C" {
  int   dsygv_  (int *itype, char *jobz, char *uplo, int * n,
		 double *a, int *lda,
		 double *b, int *ldb, double *w,
		 double *work, int *lwork,
		 int *info);
}

**Comment by tomzzh** [comment]
problem solved. Thank you!

**Comment by mlstowell** [comment]
Hi, @tomzzh ,
Glad to hear it worked for you.  I also wanted to let you know that we will be incorporating this code into the next release of MFEM (although I'm not sure when that will take place).
Best wishes,
Mark

**Comment by tomzzh** [comment]
hello @mlstowell ,
Thanks for letting me know and it will be better if the non symmetric versions of eigenvalue problems will also be included.

Thanks again.
