### ISSUE TITLE
BDM elements in MFEM

### ISSUE THREAD

**Issue by kvoronin** [mfem/mfem#548]
Hi all,

Are there anywhere (e.g. in developer's branches) BDM (brezzi-Douglas-Marini) finite elements, arbitrary order, simplicial meshes?

Thanks,
Kirill

**Comment by tzanio** [comment]
I'm not aware of any BDM implementations, is there a reason your prefer them over RT?

**Comment by kvoronin** [comment]
Thanks for the reply, @tzanio!

In general, I am happy with Raviart-Thomas finite elements but I've been told recently that for a particular test (linear transport with a rotating almost discontinuous solution), BDM elements perform much better, RT elements smooth out the solution too much. 
That code (not mine) is in NGSolve, but I was told (not sure) that they don't have Raviart-Thomas finite elements so my idea was to compare the elements in MFEM in my code.

**Comment by issabass** [comment]
Hi,
I hope you are planning to add the implementation of this family (BDM & BDFM), tzanio!

**Comment by tzanio** [comment]
@issabass, adding the BDM family should be doable, but we don't have immediate plans to do that ourselves. (We are always open to contributions though!)

Can I ask why do you prefer BDM to RT?

Tzanio

**Comment by issabass** [comment]
Thank you much, @tzanio!
I am asking this just for comparison purposes.
