### ISSUE TITLE
mat + mat_e of bilinear form

### ISSUE THREAD

**Issue by martemyev** [mfem/mfem#55]
Dear All,

After eliminating bc there is a mat_e sparse matrix such as `mat+mat_e=full_matrix` of the bilinear form. There are functions like FullMult and FullAddMult that use both mat and mat_e in the matrix-vector multiplication. I am wondering if I can get a full sparse matrix. I didn't find anything existing in the library, so I'm thinking about the following options:
```cxx
const SparseMatrix &S = billiear_form.FullSpMat();
```
where
```cxx
SparseMatrix BilinearForm::FullSpMat() const { return mat + mat_e; } // create a full matrix
```
Or maybe, something like this:
```cxx
bilinear_form.RestoreFullMatrix(); // that would involve mat += mat_e
const SparseMatrix &S = bilinear_form.SpMat(); // existing way
```

Thanks,
Mikhail

**Comment by tzanio** [comment]
Hi Mikhail,

Can you provide more details about your use case?

Of the two options you are proposing, I think the second one is better, because it will also enable the use of `FormLinearSystem()`, at least in some case.

Cheers,
Tzanio

**Comment by martemyev** [comment]
Hi Tzanio,

My goal is to compute a dense matrix `D = W^T * S * W`, where `S` is a full matrix of a bilinear form, and `W` is a dense matrix each column `X_i` of which is a solution of the equation `S*X_i = B`, where `i` corresponds to a boundary degree of freedom, i.e. `W = DenseMatrix(fespace.GetVSize(), n_bdr_dofs)`. To solve many equations `S*X_i = B` I use the `FormLinearSystem` function, which creates `mat_e`, eliminates rows and columns corresponding to boundary dofs, and finalizes the matrix, so when I compute `D` using `D = RAP(S, W);`, the `S` matrix is not full, and I need it to be without boundary conditions applied.

Thanks,
Mikhail

**Comment by tzanio** [comment]
Hi Mikhail,

If I understand correctly, `D` is the Schur complement with respect to the boundary? The action of `D` can probably be computed more efficiently than solving the many systems, but if you need the actual dense matrix itself, than I what you are doing is certainly a valid approach.

If you want to restore the full matrix, you probably want to call

```c++
SparseMatrix * Add(const SparseMatrix & A, const SparseMatrix & B);
````

though depending on the sizes, this may not be more efficient than reassembly.

Hope this helps,
Tzanio

**Comment by martemyev** [comment]
Hi Tzanio,

Thank you for the reply. I do need the dense matrix `W` itself, so I need to construct it explicitly. I'm going to follow your advice on the computation of the full matrix using `Add()` function, therefore I created a pull request to get an access to the `mat_e` matrix.

Thank you,
Mikhail
