### ISSUE TITLE
Table determines width by the max entry in the J array

### ISSUE THREAD

**Issue by delyank** [mfem/mfem#550]
This prohibits empty trailing columns in the Table matrix.

Example:

Consider a fface_cface relation (this is a fine face to coarse face relation). In this case, every coarse face contains a fine face so all columns have entries but not all fine faces belong to a coarse face (some are considered "interior" faces for some coarse element) resulting in empty rows. Having empty rows is fine, including trialing empty rows. However, once fface_cface is transposed to obtain cface_fface, the trailing empty columns are not counted. Thus, transposing changes the matrix dimensions. This causes issues in table to table multiplications since the dimensions do not conform (some checks within MFEM fail). Essentially, even cface_fface * fface_cface cannot be performed due to seemingly non-matching dimensions.

It is not clear if a direct fix (i.e., introducing the width of the table explicitly) would be valid and if it might  cause other issues: either in the algorithms or with respect to compatibility with existing user code.

**Comment by v-dobrev** [comment]
Class `Table` does not store a "width" - that is why the `Transpose` function accepts an optional parameter to explicitly set the desired width which becomes the height of the new `Table`, see

https://github.com/mfem/mfem/blob/58f8873b73c2aa272df311fe02896a19d6c07d44/general/table.hpp#L174

The default value for the optional width is `-1` which resorts to scanning for the largest used column index by calling the `Width()` method.

If the default value does not do the right thing, you can specify the width explicitly when transposing.

**Comment by delyank** [comment]
Thank you, Veselin! The problem is the width of the new (after Transpose) table.

For example I have 32000 fine faces and 210 coarse faces. Then, fface_cface is 32000x210, which is correct and, thus, I do not need to explicitly provide the number of columns to Transpose (it will do its thing with no issues). However, once Transpose is called, resulting in cface_fface, cface_fface.Width() would return something like 31000. Thus, cface_fface appears as 210x31000 matrix. Say you want to compute cface_fface * fface_celement, where fface_celement has the correct number of rows (32000). This is a bit strange, although MFEM seems to allow this operation to go through.

It seems that the _ncols_A of Transpose, together with the less strict verification in Mult, can address the majority of ambiguities. In my case, I managed to find a better way of doing what I need, that does not involve any ambiguities.

The question is, should this be done with an explicit width? Usually, one expects Width() to have O(1) complexity and in this case it is O(n).

**Comment by v-dobrev** [comment]
The "width" does not makes sense for all `Table` objects. For example the "element-to-dof" `Table` used by class `FiniteElementSpace` can store negative "column indices" - indicating a sign flip when transitioning between a local dof and a global dof. In this case, class `Table` is not simply a boolean matrix - it is a map from the integers `[0,size)` to an ordered list of integers.

**Comment by delyank** [comment]
I see. In the case you describe, having a "width" field would introduce a different ambiguity. In that case, also, Width() may return strange things that make no sense. In essence, it should be called "number of TYPE II elements", similar to Size() being the "number of TYPE I elements". In your example, this would be the number of dofs (globally). Of course, when Table is not just a boolean matrix, usual matrix operations may make no sense, but they would make sense when it is a boolean matrix, in which case "number of TYPE II elements" would act as "width".

**Comment by jakubcerveny** [comment]
I must say I would also welcome if the Table class stored the width. A couple of times I had to store it outside of the table and it would have definitely made things more streamlined (even if the width didn't make sense or wasn't set in some other cases).

**Comment by v-dobrev** [comment]
@delyank, do you want to make a branch for this?

**Comment by delyank** [comment]
I'll have put it in my plan.

**Comment by tzanio** [comment]
@delyank, I'm closing the issue, but we are still interested in a PR if this remains a concern
