### ISSUE TITLE
Is this possible to calculate from stored results?

### ISSUE THREAD

**Issue by JianhuaQin** [mfem/mfem#555]
Hello everyone,

I am trying to use MFEM as a solid solver to simulate fluid-structure interactions. However, I encountered a problem. 
The results (positions and velocities) have to be stored so that they can be used for last time step. From ex.10 the mesh and velocity will be stored in "deformed.mesh" and "velocity.sol". 
The next thing to do is to read the mesh and velocity from the files. It is easy to read the mesh file by using "./ex10 -m deformed.mesh".  
To read the velocity I write the codes as follows,
```c++
  ifstream ifilev("velocity.sol");
  char linev[100];
   int linenumv=0;
   while(ifilev.good())
    {
        	ifilev.getline(linev,100);
        	//puts(line);
        	istringstream iss(linev);
		if(linenumv>=5) iss>>v[linenumv-5];
       	 	linenumv++;
    }
    //cout<<"linenumv "<<linenumv<<endl;
    ifilev.close();   
    cout<<"linenumv "<<v[1]<<endl;
    v.SetTrueVector();
```
By doing so, I can also read the velocity.

However, I find that the result is incorrect.
If two time steps are calculated by once one time step, the result is

```c++
    lucky@NjustQin:/media/lucky/Matters/FSI/qin/mfem-master/examples$ ./ex10 -m deformed.mesh 
    linenumv 0
    step 0, t = 1, EE = 8.3969e-11, KE = 3.47423e-08, ΔTE = 3.48262e-08
    lucky@NjustQin:/media/lucky/Matters/FSI/qin/mfem-master/examples$ ./ex10 -m deformed.mesh 
    linenumv -7.50197e-07
    step 0, t = 1, EE = 2.59793e-10, KE = 1.38731e-07, ΔTE = 1.04248e-07
```

If two time steps are calculated only once, the result is

```v++
    lucky@NjustQin:/media/lucky/Matters/FSI/qin/mfem-master/examples$ ./ex10 -m deformed.mesh 
    linenumv 0
    step 0, t = 1, EE = 8.3969e-11, KE = 3.47423e-08, ΔTE = 3.48262e-08
    step 1, t = 2, EE = 1.02622e-09, KE = 2.33867e-07, ΔTE = 2.34893e-07
```

Since the results are inconsistent, there must be sth wrong. I wish someone can give me some suggestions on how to solve this.
Thank you for your time.

Best,
Jianhua

**Comment by mlstowell** [comment]
Hello, Jianhua,

I haven't tried this myself but I may have a useful suggestion.  There is a GridFunction constructor that seems to be designed to read the files created by the GridFunction::Save() method.

Perhaps you could try the following:
ifstream ifilev("velocity.sol");
GridFunction new_v(mesh, ifilev);
ifilev.close();

Best wishes,
Mark

**Comment by JianhuaQin** [comment]
#Hi Mark,
@mlstowell Thank you for your suggestion! It is much more convenient to read the velocity now.
U

**Comment by JianhuaQin** [comment]
Hello @tzanio and @mlstowell ,

I tried to solve this problem and I find it is caused by using the incorrect ODE solver,
I used `int ode_solver_type = 15;` in order to save time.
Now `int ode_solver_type = 3;` is chosen and the inconsistent results is negliable.
Thank you again for your help! Sorry for disturbing you.

Best wishes,
Jianhua

**Comment by JianhuaQin** [comment]
Hello everyone,

I tested the code again and I think the problem still exists.
If an implicit solver is used, then the information (position and velocity) from last time step will have influence on the results. That's why I can't stop the calculation and start again.
However, if an explicit solver (e.g. `ForwardEulerSolver`) is chosen, I may only use the information in the current time step. Therefore, it should be possible to continue the calculation and get the same results.

By the way, if I can't solve this problem, is there any other ways to add time-dependent external force?
The external force is obtained from my own fluid solver. This means MFEM and the fluid solver exchanges data mutually.

Best,
Jianhua

**Comment by v-dobrev** [comment]
Hi Jianhua,

In ex10, if you want to restart the computation you will need to save and load the initial, stress free configuration, i.e. the initial mesh. Actually, that is what `HyperelasticOperator` assumes: the stress free configuration is given by the `Mesh` while the current deformation is represented by the second component of the solution vector (the first component is the velocity).

Veselin

**Comment by JianhuaQin** [comment]
@v-dobrev 
Thank you for the suggestion, everything works perfectly now! I think it's time to close this issue!
Thanks again!

Jianhahua
