### ISSUE TITLE
Element DOF ordering

### ISSUE THREAD

**Issue by dylan-copeland** [mfem/mfem#557]
I have a question about element DOF ordering. Suppose a reduced mesh is constructed from an original mesh by selecting a subset of elements. Will FiniteElementSpace::GetElementDofs give element DOF's in the same order on the original and reduced meshes, so that a DOF map can be constructed element-wise for all types of DOF's by just looping over the array of returned DOF indices for the original and reduced meshes? That is, the i-th element DOF on the original mesh should correspond to the i-th element DOF on the reduced mesh, for the same element. I am interested in whether this holds for all types of DOF's (vertex, edge, face, volume).

It appears that although FiniteElementSpace::GetElementDofs is a virtual function, there is only one implementation, in fespace.cpp. There, it seems that the DOF's of all types would be added to the returned array in the same order for the original and reduced mesh. In particular, Mesh::GetElementVertices, Mesh::GetElementEdges, etc. would need to be in the same order, and I think they would be if the reduced mesh elements are created with vertex indices in the original order (via Element::SetVertices). Is this correct, or is there some complication I am missing?

**Comment by v-dobrev** [comment]
If I understand you question correctly -- the answer is yes. The ordering if the dofs in the returned `Array<int>` is the same as the ordering of the basis functions on the reference element.
