### ISSUE TITLE
SaveVTK with ref = 0 and field_data

### ISSUE THREAD

**Issue by kvoronin** [mfem/mfem#558]
Hello,

Could someone explain me please the meaning of "ref" parameter for PrintVTK/SaveVTK for GridFunctions and why ref = 0 is not allowed (if I also want to provide a field name, thus I don't want to use PrintVTK())?
```c++
// S is ParGridFunction* from L^2 finite element space
int ref = 0; // 1;
std::ofstream fp_S("u_test_it0.vtk");
pmesh->PrintVTK(fp_S, ref, true);
std::string field_name_S("u_h");
S->SaveVTK(fp_S, field_name_S, ref);
```
This produces nans in the output file, while with ref = 1 I have more POINTS and values which look correct. Serial code.

Or am I missing something in the way to use these functions?

Thanks,
Kirill

**Comment by v-dobrev** [comment]
The `ref` parameter is short for "refinement factor" - e.g. if you have a quad, it will be subdivided into `ref x ref` small (linear) quads in the saved file. Thus, `ref == 0` does not make sense.

**Comment by kvoronin** [comment]
Thanks, @v-dobrev!
Still, I am not sure I understand why there is no option to call with ref = 0 if I just want to print the grid function as it is.

**Comment by v-dobrev** [comment]
The pair of methods
https://github.com/mfem/mfem/blob/58f8873b73c2aa272df311fe02896a19d6c07d44/mesh/mesh.hpp#L1045
and
https://github.com/mfem/mfem/blob/58f8873b73c2aa272df311fe02896a19d6c07d44/fem/gridfunc.hpp#L385
are meant to work together and support any type of solution (including Nedelec and Raviart-Thomas elements) of any order by subdividing the elements and sampling the solutions at the given refinement factor `ref`. They are intended for visualization purposes in tools that cannot read MFEM's format but can read simple linear VTK meshes with solutions. With these methods, the mesh connectivity is lost - each original element is represented as a connected set of refined elements which is disconnected from the other original elements.

There is a separate version of `PrintVTK` here
https://github.com/mfem/mfem/blob/58f8873b73c2aa272df311fe02896a19d6c07d44/mesh/mesh.hpp#L1038
which saves a mesh in VTK format, "as it is", without loosing the element connectivity, however, it supports only linear or quadratic meshes.

If you are looking for a method `GridFunction::SaveVTK` that saves the solution "as it is" - there is no such method at the moment.

If you clarify what you are trying to do with these VTK files, we can probably suggest an alternative.

**Comment by kvoronin** [comment]
@v-dobrev,

I am doing some adaptive mesh refinement, and I want to print my solution as a GridFunction to the VTK output file which will be later postprocessed for visualization in ParaView.

Did I get it right, that I cannot call GridFunction::SaveVTK without printing in the output file much more points than my GridFunction actually have? If yes, this looks strange to me since I'd like to see exactly the same mesh in ParaView which I was doing AMR at.

**Comment by v-dobrev** [comment]
How about simply using `ref == 1` - that will generate 1 linear element for each original element with a linear approximation for your solution.

**Comment by kvoronin** [comment]
@v-dobrev,
I've misunderstood your previous explanation then. I thought that ref == 1 means that each mesh element will be subdivided as by uniform refinement. 
For me it's fine to have linear interpolation within each element.
Thanks!
