### ISSUE TITLE
MassIntegrator on boundary of domain in DG space

### ISSUE THREAD

**Issue by martemyev** [mfem/mfem#56]
Dear All,

I'd like to compute a matrix of integrals over boundary of a domain K :
M = \int_{\partial K} u v,
where u and v are from the finite element space spanned over discontinuous functions

Here is what I'm trying to do with MFEM:
```
int order = 1;
Mesh mesh(10, 10, Element::QUADRILATERAL, 1, 100, 100);
int dim = mesh.Dimension();
DG_FECollection fec(order, dim);
FiniteElementSpace fespace(&mesh, &fec);
BilinearForm bound_mass(&fespace);
// I tried this:
bound_mass.AddBoundaryIntegrator(new MassIntegrator());
// But it gives a segfault, because it dereferences a NULL pointer in assembling:
// <bilinearform.cpp>
// void BilinearForm::Assemble : 
// if (bbfi.Size())
//   {
//      for (i = 0; i < fes -> GetNBE(); i++)
//      {
//         const FiniteElement &be = *fes->GetBE(i); // Here fes->GetBE(i) return NULL pointer
// Apparently it shouldn't work that way, so I tried:
bound_mass.AddBdrFaceIntegrator(new MassIntegrator());
// but it's not implemented.
```

I've tried to implement `void MassIntegrator:AssembleFaceMatrix` to make the second approach work, but I'm sure I did it wrong:
```cxx
void MassIntegrator::AssembleFaceMatrix(
    const FiniteElement &el1, const FiniteElement &el2,
    FaceElementTransformations &Trans, DenseMatrix &elmat)
{
   int nd1 = el1.GetDof();
   double w;

   elmat.SetSize(nd1);
   shape.SetSize(nd1);

   const IntegrationRule *ir = IntRule;
   if (ir == NULL)
   {
      int order = 2 * el1.GetOrder();

      ir = &IntRules.Get(Trans.FaceGeom, order);
   }

   elmat = 0.0;
   for (int i = 0; i < ir->GetNPoints(); i++)
   {
      const IntegrationPoint &ip = ir->IntPoint(i);
      el1.CalcShape(ip, shape);

      Trans.Face->SetIntPoint(&ip);
      w = Trans.Face->Weight() * ip.weight;
      if (Q)
      {
         w *= Q -> Eval(*Trans.Face, ip);
      }

      AddMult_a_VVt(w, shape, elmat);
   }
}
```

Could you please advise something on that matter?

Thanks,
Mikhail

**Comment by tzanio** [comment]
Hi Mikhail,

You want to extract the `kappa < {h^{-1} Q} [u], [v] >` part of `DGDiffusionIntegrator`, without the `h^{-1} ` scaling. If you call this `DGMassIntegrator`, then you can use it on the boundary with:

```c++
bound_mass.AddBoundaryIntegrator(new DGMassIntegrator());
```

Hope this helps,
Tzanio

**Comment by v-dobrev** [comment]
Hi Mikhail,

There is just a small problem with your implementation: the integration rule `ir` is for the reference face, which correct, but then the integration point 'ip' is used as a volume point in the call `el1.CalcShape`, which is wrong. You need to map `ip` to the correct integration point in the volume element, say `eip`. This can be done using the following:
```
   IntegrationPoint eip;
   Trans.Loc1.Transform(ip, eip);
   el1.CalcShape(eip, shape);
```
This is what we do, e.g. in [`DGDiffusionIntegrator::AssembleFaceMatrix`](https://github.com/mfem/mfem/blob/master/fem/bilininteg.cpp#L1974) and other DG integrators.

Veselin

**Comment by tzanio** [comment]
Hi Mikhail,

Just wondering if you got this working?

Cheers,
Tzanio

**Comment by v-dobrev** [comment]
This will be supported in version 3.2 through `BoundaryMassIntegrator::AssembleFaceMatrix`.
