### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [mfem/mfem#561]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [isockstream::receive](https://github.com/mfem/mfem/blob/b8f02582619f842f30c4fa2e3c9fcdcf9c234335/general/isockstream.cpp#L146 "isockstream::receive function")
- [MagneticDiffusionEOperator::buildA0](https://github.com/mfem/mfem/blob/acd1033e8fba0b7dfdcbd5f5c050b416500ccc19/miniapps/electromagnetics/joule_solver.cpp#L642 "MagneticDiffusionEOperator::buildA0 function")
- [Table::SetDims](https://github.com/mfem/mfem/blob/2d6419f100acefcacad82e6fca2a806a18d038bc/general/table.cpp#L142 "Table::SetDims function")

**Comment by elfring** [comment]
* How can such an update suggestion ever be integrated when it gets marked as “spam” by a MFEM team member?
* Do other developers care more for related software improvements?

**Comment by jakubcerveny** [comment]
This suggestion is valid and can still be "integrated", regardless of the label.

**Comment by tzanio** [comment]
We do not consider this a critical change. If you feel strongly about it, please open a PR.
