### ISSUE TITLE
What is Walk() in SparseMatrix?

### ISSUE THREAD

**Issue by delyank** [mfem/mfem#563]
SparseMatrix has a Walk() method that doesn't seem defined anywhere.

**Comment by tzanio** [comment]
An old function that used to return the the entries of the matrix one-by-one, as in
```c++
while (A.Walk(i,j,a))
{
  // do something with a, the A_ij nonzero entry in the matrix
}
```
The implementation used to be in the header, and it looks like we have deleted it :)

Maybe it is time to delete the declaration too?
