### ISSUE TITLE
Deleting multiple BilinearForms which depend on a single BilinearFormIntegrator

### ISSUE THREAD

**Issue by kvoronin** [mfem/mfem#564]
Hello,

I don't understand one moment in MFEM, so I would be grateful if someone explains to me what I misunderstand.

Let's say, I define a new class which is related to a weak formulation of a problem. It will have BilinearFormIntegrators as a part of it.

Then, I might have several meshes where I want to solve the problem. Then I will have several BilinearForms defined for each of the meshes (and corresponding f.e. spaces). Naturally, I will use the same integrators from a single object for the weak problem, for all meshes (via AddDomainIntegrator, for example).

But then, when I am deallocating memory, BilinearForms for each mesh will try to delete their dlfi, which will point to the same BilinearFormIntegrator.

How should I handle this issue? It looks strange that MFEM doesn't allow that directly (is it?), but what is the workaround? I am thinking of something like manual shared pointers implementation, but this will require some extra work. Or something like implementing copy constructor for BilinearFormIntegrator

Thanks,
Kirill

**Comment by mlstowell** [comment]
Hello, @kvoronin ,

This sounds like an unusual use case but I think we do have a solution.  The BilinearForm class has a constructor that takes a FiniteElementSpace pointer and a BilinearForm pointer.  When this constructor is used the new BilinearForm will copy the BilinearFormIntegrator pointers from the input BilinearForm object to the new object.  This allows you to setup one BilinearForm object for a given mesh and then create a series of related BilinearForm objects for a series of meshes.  The BilinearFormIntegrators will only be deleted by the original BilinearForm object so you must make sure this one is deleted after the others.

I did notice that we do not have such a constructor for MixedBilinearForm objects.  If this is something you need perhaps we should add it.

Best wishes,
Mark

**Comment by mlstowell** [comment]
It does make sense to make these classes consistent with each other.  I'll take a look at adding it.  Thanks for the suggestion.

**Comment by mlstowell** [comment]
FYI: I just added this functionality to [Par]MixedBilinearForm and [Par]LinearForm in pull request #568.  

You may be interested to know that I noticed an error in the existing implementation when the user restricts boundary integrators using marker arrays.  The integrators were being copied but not the marker arrays.  Clearly this would not create the same operators.  The above mentioned pull request also fixes this oversight.

**Comment by kvoronin** [comment]
Thanks, @mlstowell, I will follow your ideas in my code.
Though, I still believe that it is natural to have a single object with integrators and borrow them from it for the bilinear and linear forms (not from other linear forms as in your case).
For example, this allows one (ok, me) to implement a weak formulation of the problem in terms of integrators, as an object in its own right, then add f.e. spaces and create discrete problems on top of it.

**Comment by mlstowell** [comment]
Hi, @kvoronin, MFEM does not currently have this abstraction, as you know, but we're generally open to suggestions.  Can you describe the typical work flow you use with such an object?  Are there specialized methods that such an object can implement more easily?

**Comment by kvoronin** [comment]
Sure, @mlstowell.
My idea was actually to provide a higher level abstraction to build discrete problems. 

Essentially, a weak formulation can be viewed as a matrix array of integrators plus f.e. collections (to describe which spaces the variables belong to), forming an object WeakFormulation. This object can be used to formulate discrete problems for different meshes. 
As soon as a mesh (and probably order of finite elements) is given, WeakFormulation can be used to construct a DiscreteProblem which will store the matrix, the preconditioner, and all the required data (like offsets, pfespaces, pbilinearforms and plinearforms or even error estimators). 
For a DiscreteProblem one can then use main functions like AssembleSystem, Update and Solve, ComputeError.

Then one don't need to write for each pde in each domain a code which assembles the system. All can be done automatically after the WeakFormulation is created (which is very small). Except for the fact that integrators might depend on the problem, but these can be provided (as Coefficients) from another small object.

The way I use it:.
1) Multigrid methods. I create a GeneralHierarchy which stores the hierarchy of meshes and spaces. Using a hierarchy (which can be updated dynamically when the mesh is refined, e.g. in AMR setting) I can take a WeakFormulation and construct a discrete problem at any level I want. As an option, I can construct a discrete problem which will be dynamically updated (re-assembled) as soon as the hierarchy finest mesh is. 
2) AMR setting with multigrid preconditioner (essentially the same as 1), but again it is natural to have a hierarchy of levels which correspond to AMR iterations.
3) Time-slabbing methods, which is a generalized time-stepping, can be a sequential algorithm in time (also can be parallel-in-time as a variant), but at each step we solve a problem with space-time mesh, in a time-slab (may consist of multiple time-steps). This is implemented by deriving new classes which have additional members related to the "cylindrical" structure of the problem, presence of "top" and "bottom" (in terms of time). 
Further step is time-stepping(slabbing) when you have several meshes for each time-slab, say two-grid method. Then you might want to have two discrete problems in each time slab, on the fine and on the coarse mesh. 
Then it actually makes sense to construct ProblemsHierarchy. Again, they are constructed using the single WeakFormulation.

Certainly, all described above can be done in MFEM, but the abstract wrappers make the code simpler, the user doesn't need to think of calling assemble or eliminating boundary conditions every time, it's all done internally, requiring only a few lines of code. 

If you are interested in how the possible implementation can look like, I have it on github in one of my branches (though not finalized yet and not everywhere documented), I can give anyone interested a link to the most current version.

**Comment by mlstowell** [comment]
Thanks, Kirill.  It does sound like a useful abstraction.  I think many on our team are away at a conference next week but I'll try to bring this up at our meeting the following week.
