### ISSUE TITLE
Integration of GridFunction on subdomains

### ISSUE THREAD

**Issue by jandrej** [mfem/mfem#565]
Hello,

in order to compute cost functionals for optimization purposes I'm trying to compute spatial integrals of a GridFunction on certain subdomains. This works fine for the domain itself, but not on boundaries. Basically its
```
\int_{\Omega} u_gf dx
```
and
```
\int_{\Gamma} u_gf ds
```
where the result is a scalar.

This is the version I use for the subdomains in the inside of the domain.

```cpp
double ComputeIntegral(GridFunction *gf, Array<int> &attr) {
  double fval = 0.0;
  ElementTransformation *tr;
  const IntegrationRule *ir = NULL;

  Mesh *mesh = gf->FESpace()->GetMesh();

  for (int i = 0; i < mesh->GetNE(); i++) {
    tr = mesh->GetElementTransformation(i);

    if (ir == NULL) {
      const FiniteElement *el;
      el = gf->FESpace()->GetFE(i);
      ir = &IntRules.Get(el->GetGeomType(), 1 * el->GetOrder() + 1);
    }

    for (int j = 0; j < ir->GetNPoints(); j++) {
      const IntegrationPoint &ip = ir->IntPoint(j);
      tr->SetIntPoint(&ip);
      if (attr[tr->Attribute - 1]) {
        fval += ip.weight * tr->Weight() * gf->GetValue(tr->ElementNo, ip);
      }
    }
  }
  return fval;
}
```

In the boundary version `gf->GetValue` doesn't do the right thing, since it requests `fes->GetElementDofs(i, dofs);`.

```cpp
double ComputeBdrIntegral(GridFunction *gf, Array<int> &attr) {
  double fval = 0.0;
  ElementTransformation *tr;
  const IntegrationRule *ir = NULL;

  Mesh *mesh = gf->FESpace()->GetMesh();

  for (int i = 0; i < mesh->GetNBE(); i++) {
    tr = mesh->GetBdrElementTransformation(i);

    if (ir == NULL) {
      const FiniteElement *el;
      el = gf->FESpace()->GetBE(i);
      ir = &IntRules.Get(el->GetGeomType(), 1 * el->GetOrder() + 1);
    }

    for (int j = 0; j < ir->GetNPoints(); j++) {
      const IntegrationPoint &ip = ir->IntPoint(j);
      tr->SetIntPoint(&ip);
      if (attr[tr->Attribute - 1]) {
        fval += ip.weight * tr->Weight() * gf->GetValue(tr->ElementNo, ip);
      }
    }
  }
  return fval;
}
```

I could implement a method `GridFunction::GetBdrValue` if that is a desired solution or are there other/easier ways to compute the integral on subdomains?

This also effects `GridFunctionCoefficient` if used with a `BoundaryLFIntegrator`.

**Comment by mlstowell** [comment]
Hello, @jandrej ,

I would perform these integrations with LinearForm objects.  For example,

ConstantCoefficient one(1.0);
LinearForm lf_dom(gf->FESpace());
lf_dom.AddDomainIntegrator(new DomainLFIntegrator(one));
lf_dom.Assemble();
double dom_int = lf_dom(*gf);

or
LinearForm lf_bdr(gf->FESpace());
lf_bdr.AddBoundaryIntegrator(new BoundaryLFIntegrator(one));
lf_bdr.Assemble();
double bdr_int = lf_bdr(*gf);

For more general domains you can replace the ConstantCoefficient with indicator functions which are equal to one on the region of interest and zero elsewhere.

Best wishes,
Mark

**Comment by jandrej** [comment]
Actually this is how I implemented them to avoid the per element loops.

Do we care about the `GridFunctionCoefficient` not being able to be used with `GridFunctionCoefficient`?

**Comment by v-dobrev** [comment]
Yes, adding a method `GridFunction::GetBdrValue` and new class `GridFunctionBdrCoefficient` is a good solution.

We can also extend `GridFunctionCoefficient` to detect if the transformation is a boundary transformation - e.g. by comparing `ElementTransformation::GetDimension()` with `GridF->FESpace()->GetMesh()->Dimension()`.

One case to keep in mind is when the `GridFunction` is a discontinuous field. Then `GridFunction::GetBdrValue` will need to use the volume transformation - this approach is already used in the method `GridFunction::GetFaceValues`. To keep things simple, we can require that `GridFunction::GetBdrValue` only supports the case of continuous spaces.

**Comment by mlstowell** [comment]
Hi, @v-dobrev 

I like the idea of making ```GridFunctionCoefficient``` more robust by adding the dimension check that you mention but it could slow down computation (just because these methods are called from within nested loops).  Do you think this would have a noticeable impact?  It would certainly be a good idea to add such a check when debugging is turned on at the very least.

Also, I looked at the ```GridFunction::GetFaceValues``` method but I'm not sure I understand why discontinuous fields lead to a special case.  Are you thinking of boundaries which might include interior faces?

Thanks,
Mark
