### ISSUE TITLE
Implementing a CalcJShape for RT FEM

### ISSUE THREAD

**Issue by aasivas** [mfem/mfem#566]
Hi,

One of the projects I am working on is to implement the (symmetric) IP-DG method in the following paper,
https://link.springer.com/article/10.1007/s10915-006-9107-7
I am studying the current implementation of RT elements. For p=0,1,2, everything is hard-coded (I presume for the performance purposes), for p>2, I mostly understand what is happening, but I can't grasp the role of the matrix T and why we have to solve the linear system T*shape = u to obtain the shape functions. Can you point me to a reference?

Also, since CalcJShape will be an array of dense matrices, I guess it would be better to store it as a DenseTensor. Is this the intended way, or do you use DenseTensors for other purposes?

I will also implement outer product for vectors and a tensor contraction (:, double dot operator). Would you be interested in these as contributions? If that is the case, do you have a style guide? If you are not really interested, I am just going to go wild.

Best, 
Abdullah Ali Sivas

**Comment by v-dobrev** [comment]
Hi Abdullah,

The `T` matrix and its inverse `Ti` (used in `RT_TriangleElement` and `RT_TetrahedronElement`) are used to perform a change of basis from a basis where all basis functions are easy to evaluate at any reference point, to the actual basis used by the finite element (for which we do not have explicit formulas). Unfortunately, we do not have a reference to point you to. However, if you are interested, I can try to summarize it here.

I'm not sure I understand - what do you mean by "CalcJShape"?

Regarding contributions: you can take a look at https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md - e.g. regarding style see the second bullet in the section "Developer Guidelines"/"Code specifics".

Some of the operations that you mention you want to implement are already available in the library - e.g. here:
https://github.com/mfem/mfem/blob/eea8eb2185c5b6368ca2c1c15414344549e67b63/linalg/densemat.hpp#L435-L451

Generally, we welcome any contributions that will be of broader interest, so if there are such operations that you would like to add - you are welcome to make a branch (I believe you already have permissions to make branches) and then create a PR when ready.

Thanks,
Veselin

**Comment by aasivas** [comment]
Hi Veselin,
Thank you for the answer. 
>  However, if you are interested, I can try to summarize it here.

I would really appreciate. As far as I understand, MFEM is using Chebyshev polynomials of the second kind to construct a basis -I don't know if it has a special name-, then T*shape = u when solved gives the Gauss-Legendre basis for simplices. I would love to learn about the relationship there. Is it like interpolating one polynomial to another which is the same by uniqueness but might have a different representation?

I would appreciate this because I need to implement the term \int_{K} \grad\vec{u}:\grad\vec{v}. This is simple for H1 and L2 elements since the jacobian term \grad\vec{\phi} is diagonal for every polynomial in the finite element element space. However, since RT elements are vector-valued to start with -i.e. we don't just concatenate with a zero to make them vector valued-, this is not necessarily true. (Also my reply to > I'm not sure I understand - what do you mean by "CalcJShape"?) So I am implementing a function I currently call CalcJShape to calculate the Jacobian of shape functions. And I don't know if the matrix `T` will affect the Jacobian.

Also since `CalcVShape` returns a `DenseMatrix` of size `dof*dim`, the natural shape for `CalcJShape` would be `dof*dim*dim`. It fits the definition of a rank 3 tensor `DenseTensor`, I thought of using that but I don't know if it would be the best way.

> Some of the operations that you mention you want to implement are already available in the library

I actually noticed this but maybe I should have been clearer. I intend to extend those functions via BLAS calls. For outer product, it would be `xger`. I will write the tensor contraction myself though.

> Regarding contributions: you can take a look at https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md - e.g. regarding style see the second bullet in the section "Developer Guidelines"/"Code specifics".

Awesome. I did not notice this, also I did not know that I had rights to create branches. Will check and do so.

Best wishes,
Abdullah Ali Sivas

**Comment by v-dobrev** [comment]
The term "Jacobian" is usually used to denote the gradient of a deformation map between subsets of `R^n`. When talking about the gradient of a generic vector function (e.g. a velocity field), I wouldn't call it "Jacobian" (of the velocity) - I'd just call it the "gradient" (or the "vector gradient"). That's why I was confused by the name `CalcJShape`. I'd probably use the name `CalcDShape` or `CalcDVShape` but that's something we can decide later.

Regarding the output of `CalcJShape`: I agree, it makes sense to use `DenseTensor` for that.

Regarding the use of `T` and its inverse in `CalcJShape`: using the notation from my previous comment, one can still write `φ_i = S_{i,j} ψ_j` and therefore `∇φ_i = S_{i,j} ∇ψ_j`. Since evaluating `{∇ψ_j}` at a point will give a `DenseTensor` with dimensions `num_dofs x dim x dim`, it will be convenient to add an overload of the `Mult` method in `DenseMatrixInverse` (this type represents the matrix `S`) that applies `S` to a `DenseTensor`, contracting along the first dimension: `B_{i,j,k} = S_{i,t} A_{t,j,k}`.

One important aspect to keep in mind is that the RT basis functions on the physical element, say `{ω_i}`, are obtained from the reference element basis functions `{φ_i}` using the Piola transformation: `ω_i = (1/w) J φ_i` where `w=det(J)` and `J` is the Jacobian of the transformation from the reference element to the physical mesh element. Since for general mesh elements (high-order curved elements, or even for linear quads/hexes) the Jacobian `J` and its determinant `w` vary within the element, computing the gradients of `{ω_i}` will become complicated. That's why you will probably want to assume that your mesh consists of linear simplex elements, so that `J` and `w` remain constant within a mesh element.

Regarding the use of BLAS routines: in the context of mfem, where most of the `DenseMatrix` objects are relatively small, it does not make sense to call BLAS - it will make things slower. The places where it may be appropriate to call BLAS are places where level 3 routines will be used, and even then, only for large sizes.

**Comment by aasivas** [comment]
Thanks for your thorough answer. I am starting to work on it now. It should be easy, I handcoded first few by hand already. I have one additional but simple question, just out of curiosity. I don't understand why the following is true.

>Regarding the use of BLAS routines: in the context of mfem, where most of the DenseMatrix objects are relatively small, it does not make sense to call BLAS - it will make things slower. The places where it may be appropriate to call BLAS are places where level 3 routines will be used, and even then, only for large sizes.

Is this because it is a library call?

**Comment by v-dobrev** [comment]
Yes, I believe the cost of the function call is the main factor - its cost is not negligible when the amount of computations performed by the routine is small.

**Comment by tzanio** [comment]
Hi @aasivas, can you update us on the status of this issue?

**Comment by aasivas** [comment]
Hi Veselin,

Sorry for my late reply. I have been busy for last 4 days. I have `CalcJShape` -temporary name- implemented for triangle elements. I overloaded ``Mult`` for ``DenseMatrixInverse``, but it requires a little bit cleanup. I have a bug in the integrators, right now I am hunting for that. 

I can make an initial commit later today without the integrators then when I fixed them I can push those too.

**Comment by aasivas** [comment]
Here is the initial commit. I included everything, though integrators are not working yet. Rest of it should be functional, I checked for some cases whether I get the expected result and it seems so.

https://github.com/mfem/mfem/tree/mfem-rt

**Comment by tzanio** [comment]
Thank you @aasivas and @v-dobrev for the detailed explanation.

**Comment by fanronghong** [comment]
> The construction of the RT basis on the triangle and tet reference elements follows these steps:
> 
> 1. The "simple to evaluate" basis has two parts (considering the case of triangle):
>    
>    1. `\vec{e}_d λ_i(x) λ_j(y) λ_k(1-x-y)` for `0 <= i,j,k <= p` such that `i+j+k=p` where `p` is the order of the RT space, RT_p, `p=0,1,2,...`; also, for `0 <= d < 2`, `\vec{e}_d` is the unit vector in the `d+1` coordinate direction: `\vec{e}_0=(1,0)^T` and `\vec{e}_1=(0,1)^T`. The 1D basis functions, `{λ_i}`, can be any hierarchical basis for the space of the polynomials of degree `<=` p -- the default in mfem is to use Chebyshev polynomials for `{λ_i}`.
>    2. `(x - x_c, y - y_c)^T  λ_i(x) λ_j(y)` for `0 <= i,j <= p` such that `i+j=p` and where `(x_c, y_c)=(1/3, 1/3)` is the center of the reference triangle in mfem.
> 2. To define the basis used by the finite element, we first define the set of its nodes and associate one "normal" vector with each node. The nodes are split into 2 sets:
>    
>    1. Edge nodes: along the three edges we use any symmetric 1D set of `p+1` distinct points - the default choice in mfem is the set of `p+1` Gauss-Legendre points. With each edge node we associate the normal vector to the edge on which the node lies. These normal vectors have the same length as the edge to which they are orthogonal to - namely, these vectors are one of the following vectors: `(0,-1)`, `(1,1)`, and `(-1,0)`.
>    2. Interior nodes: to define the node locations inside the triangle, we start with any symmetric 1D set of `p` distinct points, say `{a_i}`, with `0 <= a_0 < ... < a_{p-1} <= 1`. The coordinates of the interior nodes are then given by `(a_i / w_{i,j}, a_j / w_{i,j})` for `0 <= i,j < p` and `i+j < p` where `w_{i,j}=a_i + a_j + a_{p-1-i-j}`. Each interior node is used twice - one time with associated "normal" vector `(0,-1)`, and second time with associated "normal" vector `(-1,0)`.
> 3. Given the nodes and their associated "normal" vectors, say `{ν_i}` and `{n_i}`, respectively, we define the functionals `f_i(φ)=φ(ν_i)⋅n_i` where `φ` is any vector function.
> 4. Denote by `{ψ_i}` the set of all "simple to evaluate" basis functions. The finite element basis used by class `RT_TriangleElement` is defined as the set of functions `{φ_i}` in the span of `{ψ_i}` such that `f_j(φ_i)=δ_{i,j}` for all `i,j`.
> 5. Denote by `S` the matrix that expresses the basis `{φ_i}` in terms of the basis `{ψ_i}`: `φ_i = S_{i,j} ψ_j`. Then applying the functional `f_k` to the last equation, for each `i`, we get `δ_{i,k} = S_{i,j} f_k(ψ_j)`, which we can write as `I = S T` where `T` is the matrix with components `T_{j,k} = f_k(ψ_j)`, or renaming the indices: `T_{i,j} = f_j(ψ_i)`. This shows that to compute the values of `{φ_i}` at a point, we can first compute the values of `{ψ_i}` at the same point and then multiply the resulting matrix (of size `num_dofs x 2`) by `S=T^{-1}`. The same procedure can be applied for the divergence values at a point - the only difference is that the divergence values of `{ψ_i}` and `{φ_i}` form a vector of size `num_dofs` instead of a matrix of size `num_dofs x 2`.

Why is the relationship between the "simple to evaluate" basis and Chebyshev polynomials for `{λ_i}` ?

**Comment by v-dobrev** [comment]
Basically, the idea is that the set of functions { `λ_i(x) λ_j(y) λ_k(1-x-y)`, for `0 <= i,j,k <= p` such that `i+j+k=p` } is a basis for the polynomials of degree up to `p` in the variables `(x,y)`.
