### ISSUE TITLE
Problem with making animations with VisIt due to using Dubiner basis 

### ISSUE THREAD

**Issue by sakupkmnc616** [mfem/mfem#570]
Hello, 

I am currently working on a project that involves approximating the solution as a linear combination of orthogonal basis functions on triangular meshes (I use the Dubiner basis) instead of the standard Gauss Legendre basis. 

I am currently testing my code with the DG linear advection equation in example 9. I want to create an animation of my solution from time t = 0 to t = 0.1 seconds. So I played around with VisIt in order to make a video. I set the visit flag to true in order to produce Example00000x directories and mfem_root files to create simulations in VisIt. I did the usual things, i.e Pseudocolor -> selected solution. Then Operators -> Transform -> Elevate and then selected Draw. However, it gave the error:

```
Verification failed: (0 <= b_type && b_type < 6) is false: unknown BasisType: 6
 ... in function: static int mfem::BasisType::Check(int)
 ... at line 39 of file: fem/fe_coll.hpp
```

After seeing this, I switch my basis functions back to Gauss Legendre (default) basis. With that, I was able to create the animation (note that the solution is wrong because my problem expects an orthogonal basis on triangular mesh).  

Hence I suspected that this is an issue from adding and using my implementation of the Dubiner basis. In fe.hpp, in the BasisType class, I added a 6th basis type, Dubiner, and so b_type should be < 7 instead of 6. I tried commenting out the MFEM_ASSERT statement in BasisType::Check(int b_type) but it still didn't work.

Any clue of how to fix this?

Thanks in advance!

Regards,

Henry

**Comment by tzanio** [comment]
Depending on your goals, another option could be to do convert to a known basis using `GridFunction::ProjectGridFunction` just for visualization.

**Comment by sakupkmnc616** [comment]
Hello,

Thanks a lot! I resolved the issue by generating a bunch of screenshots in my ex9.cpp code and then making a video with those screenshots!

Regards,

Henry
