### ISSUE TITLE
BlockMatrix to CSR for STRUMPACKRowLocMatrix

### ISSUE THREAD

**Issue by sshiraiwa** [mfem/mfem#575]
I have a block matrix whose each elements are filled as HypreParMatrix.
In order to use Strumpack, I think I need to either convert it to a single
HypreMatrix to call  STRUMPACKRowLocMatrix (or create a new method
which accept such an input.)

1) Is there an existing routine to do such an conversion.

2) If 1) is No, what is the best way to make an input matrix data to STRUMPACK.
I am wondering if the communication involved in rearranging the matrix
data to fill the combined single HypreParCSRMatrix is problematic. If so, is 
it better to rearrange RHS vector so that the diagonal data doesn't need to 
move?

**Comment by uvilla** [comment]
@sshiraiwa ,

@benson31 implemented a class to convert a `MFEM::BlockOperator` whose entries are `MFEM::HypreParMatrix` objects into a monolithic `MFEM::HypreParMatrix` in the `ParElag` project.

See https://github.com/LLNL/parelag/blob/master/src/linalg/utilities/ParELAG_MonolithicBlockedOperatorFactory.hpp.

I think that this class could be a good start to implement this functionality in MFEM.
