### ISSUE TITLE
`H1_FECollection` doesn't check that `p > 0` in constructor

### ISSUE THREAD

**Issue by goxberry** [mfem/mfem#578]
`H1_FECollection` doesn't check that `p > 0`, so the `operator new` call at https://github.com/mfem/mfem/blob/761a9269c2d01b5a6c60726f34946c8b03b4633b/fem/fe_coll.cpp#L1531 fails, and `std::bad_alloc` is thrown if `p <= 0`. There should probably be a `MFEM_VERIFY(p > 0, "Order of H1 finite element collection must be positive")` call, or something to that effect, within `H1_FECollection::H1_FECollection`, so that users have a better idea of why their code is crashing.

**Comment by mlstowell** [comment]
Good catch, @goxberry .  
It looks like each of the finite element collections make similar assumptions.  We should probably use MFEM_VERIFY in every one of these constructors.

**Comment by goxberry** [comment]
Linking to #579.

**Comment by goxberry** [comment]
Thanks, @mlstowell!
