### ISSUE TITLE
Adding Unit tests for backends

### ISSUE THREAD

**Issue by YohannDudouit** [mfem/mfem#594]
I was thinking that with all the duplicated code that there is in the backends, it would be nice to have a set of tests, unit tests, to verify the different functionalities that a backend has to implement. This could also [speed up development time](https://en.wikipedia.org/wiki/Test-driven_development) for new backends, by seeing which test passes and which fails. Any opinion on this?

**Comment by kennyweiss** [comment]
I strongly support this!

**Comment by tzanio** [comment]
We have unit testing in the `tests` repo in the LLNL BitBucket that are based on [Catch](https://github.com/catchorg) run nightly.

They are probably not as extensive as you have in mind, but @acfisher can point you to them and maybe provide some help. 

The more tests we are adding, the more likely it is for folks to write them :).

**Comment by acfisher** [comment]
I strongly support this as well and will be happy to help get you started with them.  I'm also diving into the backends stuff this week and will write some tests as I see good places for them.  Drop by my office when you get a chance and I'll show you how to get started with our unit testing framework.

**Comment by YohannDudouit** [comment]
I know that unit tests are good and I see how they would speed up development of new backends (or help adding functionalities to an existing one), but I haven't really used them so far. Shall we open a PR where we list all the unit tests we can think of for backends? For the current role of backends (dotProd, Axpby, Assign, Fill...), and their role to come, _e.g._ AMR, DrDobrev-worker based parallelism, `H(div)`, `H(curl)` spaces, complex number computation, etc... That would also clarify what should be in a backend, and what should not.
@acfisher I have lots of errands to do for the coming days, but I'll come discuss this topic with you soon.

**Comment by acfisher** [comment]
Excellent, I look forward to discussing this further.

**Comment by HowJMay** [comment]
Base on what I knew googleTest is a unit test framework that is easy to use.
If possilble, I want to contribute some unit code

**Comment by acfisher** [comment]
@HowJMay we actually have a suite of unit tests up and running in an offline repository based on the Catch++ library.  Perhaps we can put that in a public repo so you and others can contribute.  I'll see if we can do that and let you know.

**Comment by tzanio** [comment]
We have taken an action item on this. Closing for now, but stay tuned...

**Comment by tzanio** [comment]
Unit tests are now part of the repo:

https://github.com/mfem/mfem/tree/master/tests

Please feel free to contribute new ones.
