### ISSUE TITLE
How to develop a Mass matrix, whenever it is  weighted by  a matrix? 

### ISSUE THREAD

**Issue by Asadanees** [mfem/mfem#595]
Dear @acfisher and  @mlstowell ,
I need your help to develop a mass matrix with weight a matrix. 
**{(ε + 3 chi | E (t) |^² I + 2 Chi ^3 A)} ∂E(t)/∂t**   for this case
**chi** and  **ε** are scalars.
**I** is 3 X 3 **unit Matrix**  (Identity unit 3x3 matrix)
 **A** is 3X3 matrix and **E(t)^T** is transpose of **E(t)**.
**|E(t)|^2 = E(t). E(t)^T= E_1^2+E_2^2+E_3^2= > Inner_Product(E(t),E(t))**
**E(t)= (E_1, E_2 , E_3)**  and **E(t)^T= (E_1, E_2 , E_3)^T** 
The matrix **A_3X3**  is obtained in such a way **A= E^T E**.
# **A**  is 3x3 matrix , the entries of matrix are given below

```
           E_1.E_1      E_1.E_2       E_1.E_3         **... first row of A**
      A =  E_1.E_2      E_2.E_2       E_2.E_3         **... second row of A**
           E_1.E_3      E_3.E_2       E_3.E_3         **... third row of A**
```
`MatrixCoefficient *matrix`:
`N= new BilinearForm(&Nedelec);`
`N->AddDomainIntegrator(new VectorFEMassIntegrator(matrix));`
`N->Assemble();`
`N->Finalize();`
`N->FormSystemMatrix(ess_bdr, *Nspmat);`
`matrix={(ε + 3 chi | E (t) |^² I + 2 Chi ^3 A)}`
How can I determine the `MatrixCoefficient ` at each time step?
How can I determine the mass matrix at each time step?
In case, the weight is `VectorCoefficient` than I am successful to developed a mass matrix at each time step. But I do not know in above case.
Thanks,
Asad Anees

**Comment by mlstowell** [comment]
Hi, @Asadanees ,
Coincidentally I just created a pull request #590 a few days ago which could implement these coefficients.  If your electric field is stored as a `GridFunction`, let's call it `gfE`, then you could define a `VectorGridFunctionCoefficient` called `coefE`.  Then you could use `OuterProductCoefficient` from PR #590 to represent your `A` matrix, the `InnerProductCoefficient` could be used for `|E|^2`, etc.

Once you have built your matrix coefficient using these pieces they will automatically use the values stored in `gfE` so just update this grid function and the coefficients will produce new values.  To create a new matrix at each time step you should only need to call `N->Assemble()`, `N->Finalize()` and `N->FormSystemMatrix()`.

The relevant coefficients defined in PR #590 will probably not be available in the master branch of MFEM very soon but feel free to copy them into your application (with a comment stating where they came from if you don't mind).

Best wishes,
Mark

**Comment by mlstowell** [comment]
Hi, @Asadanees ,

I hope you're doing well.  We would like to close this issue if you have no further concerns.

Best wishes,
Mark

**Comment by Asadanees** [comment]
Hi @mlstowell 
I am really grateful to you. 

Best wishes.

anees
