### ISSUE TITLE
Validation of the Neo-Hookean model

### ISSUE THREAD

**Issue by JianhuaQin** [mfem/mfem#597]
Hello everyone,

I am trying to use ex10 these days  to solve time-dependent nonlinear elasticity problems.
Before this issue, I got help in the issue #526  
From that question, I know how to add external forces on the boundary in ex10.
However, I met some problems when doing quantitative comparisons. The results I obtained by using Neo-Hookean model do not agree with the literature.
I wonder whether any of you have done such kind of validations?
I am sorry to ask such kind of questions. Obviously, I love this code and I just want to make everything correct.

Yours sincerely,
Jianhua

**Comment by tzanio** [comment]
Hi @JianhuaQin,

Can you be more specific what you think the issue is? It will be really useful if you can provided a reproducer and description for the problem.

Thanks!
Tzanio

**Comment by JianhuaQin** [comment]
Hello @tzanio ,
Thank you for the reply. You are right, it's difficult to find the problem without the code.

Here is the revised code based on [ex10.zip](https://github.com/mfem/mfem/files/2390986/ex10.zip)

At t = 0.5s, the displacement should be about 0.195 m.
However, the result is 0.087 m.
