### ISSUE TITLE
Initialize Vector data 

### ISSUE THREAD

**Issue by brianmaustin** [mfem/mfem#60]
I've been debugging an application that uses mfem-3.1.
I was tracking down the source of an unused variable using valgrind and found two mfem::Vector functions that allocate, but do not initialize memory:
Vector::Vector (int s)
Vector::SetSize(int s)

Please consider initializing vector data to zero.
It could be as simple as replacing
data = new double[s];
with
data = new double[s]();

**Comment by tzanio** [comment]
Hi @brianmaustin,

Can you describe your use case better -- what's the application and why do you need to access uninitialized vectors?

Can you also clarify your suggestion, I'm not sure I follow...

Cheers,
Tzanio

**Comment by brianmaustin** [comment]
I don't want to use uninitialized Vectors. I want the Vectors to be initialized by their constructor.

I'm using the smoothed agglomerate AMG library (saamge) being developed at LLNL, which depends on mfem. Saamge is giving me vectors that depend on uninitialized data, and I've tracked down that dependency to mfem::Vector::Vector(int). Saamge is still getting right answers because it multiplies the uninitialized vector by zero (which works as long as the values of the uninitialized data do not include NaN ).

Whether this is a bug in mfem or saamge is really a design choice for the mfem developers. Should mfem users expect vectors to be initialized? Or should users be responsible for initializing the vectors themselves? There are valid arguments for either choice. From my current standpoint, I prefer for mfem to do it because that would work whenever a vector is allocated (or resized) - and that could be a lot of places.

My suggestion was simply to initialize the data.
Currently, the Vector constructor allocates its data at vector.hpp:250
<pre><code> data = new double[s];  //data array are NOT initialized. </code></pre>

The most concise way I know to initialize is to add parenthesis to the end of allocation statement
<pre><code> data = new double[s]();   //data[0]=0,..., data[s-1]=0. </code></pre>

Thanks,
Brian

**Comment by brianmaustin** [comment]
Ahh, now I see that in my original post, github interpreted some of my code as markup, and the result very confusing. Sorry! It looks better in the reply.
-Brian

**Comment by tzanio** [comment]
Hi @brianmaustin,

As you have found out, MFEM does not initialize the vectors with zero values. This is a design choice to avoid additional instructions, which will be unnecessary in most cases. This is also far from unique -- as far as I know most numerical libraries have the same policy. In particular, _hypre_, which we depend on in parallel, does not guarantee that its vectors are initialized.

That being said, we recognize your concern and are willing to consider changes to accommodate users like you. These changes could include:

- Improving the documentation of the `Vector` class to clearly state that its entries are not initialized
- Adding an optional parameter to the constructors and methods that change the vector to initialize the new entries to a specified value.

If you are interested in proposing a pull request along these lines, we will be happy to work with you to merge it in.

Cheers,
Tzanio

**Comment by tzanio** [comment]
Hi @brianmaustin,

I was wondering if you had any further thoughts/feedback regarding the above suggestions?

Cheers,
Tzanio

**Comment by tzanio** [comment]
Warnings added in mfem-3.2.
