### ISSUE TITLE
How to use MFEM which is installed through Spack 

### ISSUE THREAD

**Issue by eGredius** [mfem/mfem#602]
Via spack, I installed and built mfem, glvis, hypre, metis, petsc. But I couldn't find any example files in the corresponding mfem directory as the native building tutorial shows. Also the files in the folder looks short of lot of things compared to files extracted from official .tgz file. Could someone help explain how to run what native building tutorial runs using spack-mfem. Thanks a lot in advance!!

**Comment by vladotomov** [comment]
Hi Greg,
I have a spack installation of mfem and I can see all examples and their executables in /examples. Are you sure that the installation completed successfully? Note that I actually installed mfem and the rest through xsdk [https://xsdk.info](url).

**Comment by eGredius** [comment]
Big thanks to both of you!

As @v-dobrev points out, I should've used variants in my original installation. Now I have examples and other stuff. And I follow your @v-dobrev steps ending up with some error about MPI

`[greg-Macmini:08090] PMIX ERROR: UNPACK-PAST-END in file unpack.c at line 206`
`[greg-Macmini:08090] PMIX ERROR: UNPACK-PAST-END in file unpack.c at line 147`
`[greg-Macmini:08090] PMIX ERROR: UNPACK-PAST-END in file client/pmix_client.c at line 228`
`[greg-Macmini:08090] OPAL ERROR: Error in file pmix2x_client.c at line 109`
`An error occurred in MPI_Init`
`on a NULL communicator`
`MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
and potentially your MPI job)`
`[greg-Macmini:08090] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!`
`[greg-Macmini:08091] PMIX ERROR: UNPACK-PAST-END in file unpack.c at line 206`
`[greg-Macmini:08091] PMIX ERROR: UNPACK-PAST-END in file unpack.c at line 147`
`[greg-Macmini:08091] PMIX ERROR: UNPACK-PAST-END in file client/pmix_client.c at line 228`
`[greg-Macmini:08091] OPAL ERROR: Error in file pmix2x_client.c at line 109`
`An error occurred in MPI_Init`
`on a NULL communicator`
`MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort, and potentially your MPI job)`
`[greg-Macmini:08091] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!`
`Primary job  terminated normally, but 1 process returned a non-zero exit code.. Per user-direction, the job has been aborted.`
`mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:`
`  Process name: [[49812,1],1]`
`  Exit code:    1`

Could you please help me explain and deal with this? Thanks in advance!!

**Comment by eGredius** [comment]
> Big thanks to both of you!
> 
> As @v-dobrev points out, I should've used variants in my original installation. Now I have examples and other stuff. And I follow your @v-dobrev steps ending up with some error about MPI
> 
> ```
> [greg-Macmini:08090] PMIX ERROR: UNPACK-PAST-END in file unpack.c at line 206
> [greg-Macmini:08090] PMIX ERROR: UNPACK-PAST-END in file unpack.c at line 147
> [greg-Macmini:08090] PMIX ERROR: UNPACK-PAST-END in file client/pmix_client.c at line 228
> [greg-Macmini:08090] OPAL ERROR: Error in file pmix2x_client.c at line 109
> An error occurred in MPI_Init
> on a NULL communicator
> MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
> and potentially your MPI job)
> [greg-Macmini:08090] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
> [greg-Macmini:08091] PMIX ERROR: UNPACK-PAST-END in file unpack.c at line 206
> [greg-Macmini:08091] PMIX ERROR: UNPACK-PAST-END in file unpack.c at line 147
> [greg-Macmini:08091] PMIX ERROR: UNPACK-PAST-END in file client/pmix_client.c at line 228
> [greg-Macmini:08091] OPAL ERROR: Error in file pmix2x_client.c at line 109
> An error occurred in MPI_Init
> on a NULL communicator
> MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort, and potentially your MPI job)
> [greg-Macmini:08091] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
> Primary job  terminated normally, but 1 process returned a non-zero exit code.. Per user-direction, the job has been aborted.
> mpirun detected that one or more processes exited with non-zero status, thus causing
> the job to be terminated. The first process to do so was:
>   Process name: [[49812,1],1]
>   Exit code:    1
> ```
> Could you please help me explain and deal with this? Thanks in advance!!

This error come up at the last step. Local glvis server is successfully set up.

**Comment by samanseifi** [comment]
My question is how to start coding application with mfem installed with spack? should adding mfem module vis `module load mfem-4.0..` is enough or all the related/depended libraries should be loaded too?

**Comment by v-dobrev** [comment]
The spack build of MFEM uses MFEM's GNU make build system and therefore it is simplest to use GNU make for your project as well. In your `Makefile` you can simply include the `config.mk` file installed in the directory `<MFEM_DIR>/share/mfem/` where `<MFEM_DIR>` is the path returned by the command `spack location -i mfem`. This file defines a number of useful makefile variables that you can use to compile and link your project based on MFEM. As a starting point you can look at the `examples/makefile` in MFEM, e.g. the rule to build an executable from a `.cpp` source is: https://github.com/mfem/mfem/blob/db7fed5b4c4c28c7bab329b841a47d56b34317ec/examples/makefile#L60-L65

If you prefer, you can also use CMake, however, in that case you will need to build MFEM using CMake (not through spack). If you want to try that, take a look at the `INSTALL` file in the main MFEM source directory -- it contains building/installation instructions. Regarding setting up you project with CMake, take a look at issue #1163.

**Comment by samanseifi** [comment]
Thanks. One more thing, maybe I should read more documentation on spack, but let's say I want mfem built with petsc. I want to use Newton-Krylov solvers for example. Does `spack install mfem` will do the job? OR maybe I'm asking how to build mfem with `MFEM_USE_PETSC=YES` with spack.

**Comment by v-dobrev** [comment]
In spack this is typically achieved using variants (see https://spack.readthedocs.io/en/latest/basic_usage.html#variants). Specifically, to build MFEM with PETSc, you can use
```console
spack install mfem+petsc
```
You can see all variants with
```console
spack info mfem
```

**Comment by benzwick** [comment]
I had a similar question today and this it what worked for me with MFEM 4.2 and Spack 0.16:

1. Install MFEM using Spack
   ```
   spack install mfem
   ```

2. Clone MFEM into a separate directory for developing examples and modify the `makefile` by uncommenting the following line:
   ```
   CONFIG_MK = $(MFEM_INSTALL_DIR)/share/mfem/config.mk
   ```

3. Set the MFEM installation directory:
   ```
   export MFEM_INSTALL_DIR=~/opt/spack/opt/spack/linux-centos8-skylake/gcc-8.3.1/mfem-4.2.0-y7dmehi5cjozqwirg2kudm4jsaxwzvp2/
   ```

4. Run `make` in the `examples` development directory (not in the Spack package directory).

**Comment by etiennespieser** [comment]
When MFEM is used within Spack, note that the MPI initialisation sequence and the call to libraries may differ from a standalone use of MFEM.

Code snippet taken from the parallel example `ex1p.cpp` provided along with MFEM are compared below.

For a standalone use of MFEM, MPI and Hypre have to be initialised as,
```
Mpi::Init();
int num_procs = Mpi::WorldSize();
int myid = Mpi::WorldRank();
Hypre::Init();
``` 

 When installed within Spack only MPI has to be initialised (after taking into account of @benzwick's remark ):
```
 MPI_Session mpi;
 int num_procs = mpi.WorldSize();
 int myid = mpi.WorldRank();
```
