### ISSUE TITLE
Grid function with 3D coefficient?

### ISSUE THREAD

**Issue by jayjaybillings** [mfem/mfem#612]
I have a problem where I have computed a 3D vector value at each node on the mesh and I would like to use those values in a grid function to get an interpolated value at a 3D position x. So, for example, for the vector A,
```
A(x) = \sum_{i=1}^{n} A_{i}(x) N_{i}(x)
```
I would like to get back A_x, A_y, A_z as a single mfem::Vector.

If A was 1D and x was 3D, I would just use a regular grid function. Is there a way to use a 3D A_i and get back a 3D vector of the values of A(x)?

**Comment by mlstowell** [comment]
Hi, @jayjaybillings ,
I think what you want is a vector-valued, first order, H1 field.  To create this you'll need a finite element collection, finite element space, and a grid function created like this:
```
   int dim = mesh->Dimension();
   int vdim = 3; // The dimension  of A
   
   H1_FECollection fec(1, dim); // First order finite elements

   // Ordering byVDIM stores values using nodal index in the outer loop and vdim in the inner loop.
   // The other option is Ordering::byNODES.
   FiniteElementSpace fespace(mesh, fec, vdim, Ordering::byVDIM);

   GridFunction A_gf(&fespace);
   ...
   // Fill A_gf with your nodal values
   ...
   // Extract interpolated vector for a given element index, 'i', and reference location, 'ip'.
   Vector A_val(vdim);
   A_gf.GetVectorValue(i, ip, A_val);
```

Best wishes,
Mark

**Comment by jayjaybillings** [comment]
This worked perfect and I'm moving on to using it for some other things. Thanks very much! Closing...
