### ISSUE TITLE
Undefined Reference to Symbol 'GenerateDiagAndOffd'

### ISSUE THREAD

**Issue by PPCT** [mfem/mfem#615]
Hi Guys,
I am building MFEM 3.4 using CMake on Ubuntu 18.04. Hypre and Metis were built successfully prior to MFEM. When building MFEM, the following error occurred (a portion of the build output is listed below)

~/mfem-3.4/build$ make -j 4
Scanning dependencies of target mfem_miniapps_common
[  0%] Built target copy_data
[  1%] Building CXX object miniapps/common/CMakeFiles/mfem_miniapps_common.dir/mesh_extras.cpp.o
[  1%] Building CXX object miniapps/common/CMakeFiles/mfem_miniapps_common.dir/fem_extras.cpp.o
[  1%] Built target exec_prerequisites
[  2%] Building CXX object miniapps/common/CMakeFiles/mfem_miniapps_common.dir/pfem_extras.cpp.o
[ 38%] Built target mfem
Scanning dependencies of target ex9p
[ 39%] Building CXX object examples/CMakeFiles/ex9p.dir/ex9p.cpp.o
Scanning dependencies of target ex17p
[ 40%] Building CXX object examples/CMakeFiles/ex17p.dir/ex17p.cpp.o
Scanning dependencies of target ex13p
[ 41%] Building CXX object examples/CMakeFiles/ex13p.dir/ex13p.cpp.o
[ 41%] Linking CXX executable ex9p
[ 41%] Linking CXX static library libmfem_miniapps_common.a
[ 41%] Built target mfem_miniapps_common
Scanning dependencies of target ex14p
[ 42%] Building CXX object examples/CMakeFiles/ex14p.dir/ex14p.cpp.o
/usr/bin/x86_64-linux-gnu-ld: ../libmfem.a(hypre.cpp.o): undefined reference to symbol 'GenerateDiagAndOffd'
//usr/lib/x86_64-linux-gnu/libHYPRE_parcsr_mv-2.13.0.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
examples/CMakeFiles/ex9p.dir/build.make:102: recipe for target 'examples/ex9p' failed
make[2]: *** [examples/ex9p] Error 1
CMakeFiles/Makefile2:1434: recipe for target 'examples/CMakeFiles/ex9p.dir/all' failed
make[1]: *** [examples/CMakeFiles/ex9p.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

At 42%, the function call to 'GenerateDiagAndOffd' in hypre.cpp was undefined. The 'GenerateDiagAndOffd' function can be found in 'par_csr_matrix.c' as part of hypre_2.11.2.

Any help to fix this problem is highly appreciated.

Thanks,

PCPT

**Comment by v-dobrev** [comment]
It looks like you installed HYPRE directly from the Ubuntu repositories - they perform an installation that differs from the normal HYPRE build. I think they break the single `libHYPRE.a` or `libHYPRE.so` into multiple smaller libraries - e.g. I see `libHYPRE_parcsr_mv-2.13.0.so` in the output you posted above.

For this reason, you will need to explicitly set the compile and link options for HYPRE by setting the CMake variables `HYPRE_INCLUDE_DIRS` and `HYPRE_LIBRARIES` when configuring MFEM. Judging by the above output, you need to make sure `/usr/lib/x86_64-linux-gnu/libHYPRE_parcsr_mv-2.13.0.so` is listed as part of `HYPRE_LIBRARIES`.

Alternatively, you can build HYRPE yourself - that is usually straightforward - see http://mfem.org/building/#parallel-mpi-version-of-mfem. After building HYPRE, you can configure MFEM with the CMake option `-DHYPRE_DIR=/path/to/hypre` where the directory`/path/to/hypre` should contain the `include` and `lib` directories created by the HYPRE build.

Let us know if you have any further questions.

**Comment by andrewbartolo** [comment]
You can also use `LD_PRELOAD` to solve this problem without compiling libHYPRE from source.

For example, on Ubuntu 20.04, I was getting the error "undefined symbol: HYPRE_ParaSailsSolve" for another app that uses libHYPRE (laghos). After installing `libhypre-dev`, the necessary .so file is at `/usr/lib/x86_64-linux-gnu/libHYPRE_core.so`. So, the command becomes

`LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libHYPRE_core.so ./laghos`. A similar setup should work for mfem.
