### ISSUE TITLE
Problem running examples using Hypre compiled for GPU

### ISSUE THREAD

**Issue by davidherreroperez** [mfem/mfem#619]
Hi,

I am trying to run MFEM (3.4) examples using Hypre (2.15) compiled for GPU computing, but three type of segmentation faults are detected as follows:

$ ./ex1p
...
CUDA Error Code[11]: invalid argument
 csr_matrix.c(hypre_CSRMatrixPrefetchToDevice) Line:698
Segmentation fault (core dumped)

$ ./ex2p
...
CUDA Error Code[11]: invalid argument
 vector.c(hypre_SeqVectorPrefetchToDevice) Line:1932
Segmentation fault (core dumped)

$ ./ex10p
...
CUDA Error Code[11]: invalid argument
 gpuMem.c(MemPrefetchSized) Line:224
Segmentation fault (core dumped)

The Hypre code is compiled using the resulting Makefile running "./configure --enable-unified-memory --with-cuda". I am using CUDA compilation tools (V9.2.148) and NVIDIA driver version 396.54. 
Can you give me some advice about the modifications needed to run these examples?

**Comment by v-dobrev** [comment]
Hi @davidherreroperez,

Currently, MFEM (master branch, v3.4 or any earlier version) requires hypre built for CPU.

We are working actively on adding support for GPUs to MFEM including integration with hypre built for GPUs.

**Comment by acfisher** [comment]
We are actively developing this connection and GPU implementations of core MFEM integrators as well.  These new features are planned for release in MFEM 4.0.
