### ISSUE TITLE
Compile error with latest version MFEM

### ISSUE THREAD

**Issue by TangLaoya** [mfem/mfem#620]
Dear all,
Do you have any problem to build the latest version of MFEM in Windows 64bit + Visual Studio 2013? I used CMake to generate solution for VS2013 64bit version and build the solution, the following errors displayed:

Error	158	error C2259: 'mfem::ScalarProductInterpolator::AssembleElementMatrix2::ShapeCoefficient' : cannot instantiate abstract class	E:\mfem\mfem-master\fem\bilininteg.cpp	3075	1	mfem
Error	160	error C2259: 'mfem::VectorInnerProductInterpolator::AssembleElementMatrix2::VDotVShapeCoefficient' : cannot instantiate abstract class	E:\mfem\mfem-master\fem\bilininteg.cpp	3242	1	mfem
Error	157	error C2883: 'mfem::ScalarProductInterpolator::AssembleElementMatrix2::ShapeCoefficient::Eval' : function declaration conflicts with 'mfem::VectorCoefficient::Eval' introduced by using-declaration	E:\mfem\mfem-master\fem\bilininteg.cpp	3068	1	mfem
Error	159	error C2883: 'mfem::VectorInnerProductInterpolator::AssembleElementMatrix2::VDotVShapeCoefficient::Eval' : function declaration conflicts with 'mfem::VectorCoefficient::Eval' introduced by using-declaration	E:\mfem\mfem-master\fem\bilininteg.cpp	3234	1	mfem

Could anyone help me to take a look at it?
Thanks,
Tang Laoya

**Comment by v-dobrev** [comment]
Hi @TangLaoya,

This looks like a compiler issue - our testing through AppVeyor with Visual Studio 2017 seems to work fine.

Do you *have to* use VS 2013? If yes, then I can try to find a workaround - hopefully something simple - let me know if that's the case.

Veselin

**Comment by TangLaoya** [comment]
Dear Veselin,
Thank you very much for your kindly reply. Yes, I have to use VS2013, since the VS2017 is so huge and there is not so much space to install VS2017 in my computer:(

Thanks,
Tang Laoya

**Comment by TangLaoya** [comment]
Dear Veselin,

Just now I rebuilt the project of 'mfem-hertz-dev' branch and there are still the same errors.

Thanks,
Tang Laoya

**Comment by tzanio** [comment]
This is a strange error it comes from the fact that `VectorCoefficient` has 2 `Eval` methods:
```c++
class VectorCoefficient
{
   // ...
   virtual void Eval(Vector &V, ElementTransformation &T, const IntegrationPoint &ip) = 0;
   virtual void Eval(DenseMatrix &M, ElementTransformation &T, const IntegrationRule &ir);
   // ...
};
```
and `ShapeCoefficient` overwrites one, and claims `using` for the other:
```c++
struct ShapeCoefficient : public VectorCoefficient
{
   // ...
   using VectorCoefficient::Eval;
   virtual void Eval(Vector &V, ElementTransformation &T, const IntegrationPoint &ip)
   {
      //...
   }
};
```

Does anyone knows a fix? Maybe the order matters?

Tzanio

**Comment by v-dobrev** [comment]
Hi @TangLaoya,

Moving the structs outside of the methods resolves the issue - I tried it in VS 2013 and it worked.

Veselin

**Comment by TangLaoya** [comment]
Dear Veselin,

Thank you very much for your kindly help. Yes, it works, I have tested both in VS2013 and VS2015. The modified code is attached. I don't know whether it works in other platforms.

Thanks,
Tang Laoya
[bilininteg.zip](https://github.com/mfem/mfem/files/2471122/bilininteg.zip)

**Comment by tzanio** [comment]
@v-dobrev and @mlstowell -- do you think we should make this change in master?

**Comment by mlstowell** [comment]
If this is such a specialized class that it's only useful within this integrator then it should be hidden somehow so as not to pollute the namespace.  If, on the other hand, it could be useful more broadly then we should move it, and `VShapeCoefficient`, to `coefficient.?pp`.

**Comment by v-dobrev** [comment]
I'm fine with integrating this workaround in master. We can put the classes in the namespace `mfem::internal` to hide them.
