### ISSUE TITLE
Modify Contributing.md and using it in a different project

### ISSUE THREAD

**Issue by uvilla** [mfem/mfem#625]
Hi all,

I need to create contributing guidelines for the [hIPPYlib](hippylib.github.io) project of which I am the main developer.

I was wondering if I can use a *opportunely modified* version of the MFEM `Contributing.md` file in my project.

If so, how would you like me to give credits to the authors of the `Contributing.md` file and to the MFEM project for using such resource?

Thank you!

Umberto

**Comment by tzanio** [comment]
Hi Umberto,

I think it is fine to base your `CONTRIBUTING.md` on the one from MFEM. You can mention something like "Adopted from MFEM", but you don't have to IMHO.

Glad to see the progress on hIPPYlib :).

Tzanio
