### ISSUE TITLE
Copying LinearForm objects leads to seg fault

### ISSUE THREAD

**Issue by mlstowell** [mfem/mfem#627]
I happened to notice that the following code leads to a segmentation fault.

```c++
{
   ParLinearForm lf1(fespace_q);
   lf1.AddDomainIntegrator(new DomainLFIntegrator());
   lf1.Assemble();

   ParLinearForm lf2(fespace_q);

   lf2 = lf1;
}
```

The intention was to copy the contents of `lf1`, viewed as a `Vector`, to `lf2`.  What actually happened, as seen in TotalView, was that the vector data was copied as desired but the arrays that contain `LinearFormIntegrator`s were also copied.  When these objects fell out of scope they both attempted to delete the `LinearFormIntegrator`s and caused a segmentation fault.

The question is, do we want `lf2=lf1` to simply copy the vector data or should it copy everything?  I'm not sure we can support the latter without smart pointers or some sort of reference counting.

**Comment by v-dobrev** [comment]
We can define `operator=(const Vector &)` for `(Par)LinearForm` to simply call `Vector::operator=(const Vector &)` -- this is what is done in class `(Par)GridFunction`.

**Comment by mlstowell** [comment]
Yes, that sounds best to me as well.  I'll take care of it.  Thanks!
