### ISSUE TITLE
Coordinates of points associated with DOFs

### ISSUE THREAD

**Issue by martemyev** [mfem/mfem#63]
Dear All,

Is there a way to get coordinates of points associated with degrees of freedom? Can I get them for one finite element only, or can I get all of them? For example, I'd like to print the DOF points and the corresponding value of the solution:
```
DOF (point) | Solution (value)
x | y  | z  | U
```

Thanks,
Mikhail

**Comment by vladotomov** [comment]
You can do FiniteElement::GetNodes( ) followed by ElementTransformation::Transform(...) for each of the integration points.

**Comment by martemyev** [comment]
Hey Vlado,

Thanks for the idea. That should work for one finite element, though. I'm wondering if there is a function that collects all the points in one list eliminating duplicates, if any, i.e. a list which size would coincide with the size of the solution vector. I suspect there is no such a function, but still wanted to make sure.

Thanks,
Mikhail

**Comment by vladotomov** [comment]
Actually there is - it's already done in Mesh::GetNodes(GridFunction &nodes)
You must create a GridFunction for your coordinates and the above will project the positions on it.

**Comment by martemyev** [comment]
That's great! Thanks a lot.

Cheers,
Mikhail

**Comment by martemyev** [comment]
I still don't get how to extract the coordinates from the GridFunction.
Here is a simple example:
```cxx
#include "mfem.hpp"

#include <iostream>

using namespace std;
using namespace mfem;

int main() {
  Mesh mesh(1, 1, Element::QUADRILATERAL, 1); 
  const int dim = mesh.Dimension();
  const int order = 2;
  H1_FECollection fec(order, dim);
  FiniteElementSpace fes(&mesh, &fec);
  GridFunction nodes(&fes);
  mesh.GetNodes(nodes);
  cout << nodes << endl;
  return 0;
}
```
It produces:
```
FiniteElementSpace
FiniteElementCollection: H1_2D_P2
VDim: 1
Ordering: 0

0
1
0
1
0.5
1
0.5
0
0.5
```
I can't quite understand how these coordinates are organized. Any help is highly appreciated.

Thanks,
Mikhail

**Comment by tzanio** [comment]
Hi Mikhail,

The `nodes` are a vector finite element function, so `fes` should be a vector space :). The default ordering is: all `x`-coordinates followed by all `y`-coordinates, etc.

Cheers,
Tzanio

**Comment by martemyev** [comment]
Hi Tzanio,

Thanks! That helped. I'm posting the code for extracting coordinates of nodes for future references:
```cxx
#include "mfem.hpp"
#include <iostream>

using namespace std;
using namespace mfem;

int main() {
  Mesh mesh(1, 1, Element::QUADRILATERAL, 1); 
  const int dim = mesh.Dimension();
  const int order = 2;
  H1_FECollection fec(order, dim);
  FiniteElementSpace fes(&mesh, &fec, dim);
  GridFunction nodes(&fes);
  mesh.GetNodes(nodes);
  const int nNodes = nodes.Size() / dim;
  double coord[dim]; // coordinates of a node
  for (int i = 0; i < nNodes; ++i) {
    for (int j = 0; j < dim; ++j) {
      coord[j] = nodes(j * nNodes + i); 
      cout << coord[j] << " ";
    }   
    cout << endl;
  }
  return 0;
}
```

Cheers,
Mikhail
