### ISSUE TITLE
Grid Function Interpolation:  from coarse mesh to a nested fine mesh

### ISSUE THREAD

**Issue by pratyuksh** [mfem/mfem#636]
Hello,

I have the following scenario:

Let us say we have a sequence of nested meshes M_k, for k=1,2,..n. The finer meshes are obtained by refinement of the coarse meshes. We solve any given PDE on these meshes, say the solutions (Grid functions) are u_k. Now, what I would like to do is interpolate the solution on a coarse mesh to a finer mesh, example - say interpolate u_1 on the coarse mesh M_1 to the finer mesh M_3, giving a new Grid Function. Then I can compute norm(u_1 - u_3) on M_3.
Such an operation is also needed when we compute the error with respect to a reference solution obtained on a refined mesh.

Is there an in-built function which allows for this already? Other suggestions about a better way of doing this are also welcome. :)

Thank you,
Pratyuksh

**Comment by barker29** [comment]
The interpolation operator you're looking for is called the `UpdateOperator` in the `FiniteElementSpace` object. For example this snippet
```c++
mesh->UniformRefinement()
fespace->SetUpdateOperatorType(Operator::MFEM_SPARSEMAT);
fespace->Update();
OperatorHandle uH;
fespace->GetUpdateOperator(uH);
```
will return a handle to a `SparseMatrix` in `uH` that interpolates from the mesh before refinement to the refined mesh. I hope this is enough to get you started.

**Comment by delyank** [comment]
How would this work in 3D for high-order Nedelec spaces (the op doesn't specify a particular space, so I assume the question is general) on tetrahedral meshes? I'm under the impression that this may have issues when the tetrahedral reorientation in the Mesh class is employed, which seems necessary for high-order Nedelec elements.

**Comment by v-dobrev** [comment]
@delyank, yes, high-order Nedelec spaces on tetrahedral meshes are an exception - interpolation from a coarse mesh to a refined mesh will not work properly. There are ways to go around this limitation, if you need such capability.

**Comment by pratyuksh** [comment]
@barker29 @jakubcerveny Thank you for the explanation. So, for _uniform_ refinement it is clear. 

But my question was a bit more general, say we do uniform refinement  + local refinement in some regions, then we have this hierarchy of meshes {M_k}_{k=1,2,..,n}, as mentioned above. I read these meshes, want to interpolate grid functions on FE spaces between these different meshes. How can one do this?

**Comment by jakubcerveny** [comment]
If you save the meshes and then load them again, the connection between the coarse and fine elements is lost. Also, the Space only sees the connection between two levels. What you could do is save the refinement matrices too, and if you need to interpolate across multiple levels, multiply the matrices or apply them in sequence.

**Comment by tzanio** [comment]
Another option that may (or may not) be feasible is to save the u_k, and then have a separate pass of the code that starts at M_1, reads u_1, refines M_1 -> M_2, interpolates u_1 to M_2, reads u_2, refines M_2 -> M_3, interpolates u_1 and u_2 to M_3, reads u_3, etc.

**Comment by tzanio** [comment]
@pratyuksh, were you able to resolve this?

**Comment by pratyuksh** [comment]
@tzanio sorry for the late reply. Yes, it is now resolved, your previous comment was helpful. Thanks.

**Comment by pratyuksh** [comment]
Hello, another question which is connected to this: from the documentation it is clear how I can compute error with respect to the exact solution. But how do compute \norm( u - u_ref )_{H^1}, where "u_ref" is the computed solution after a couple of mesh refinements of the original? Please let me know. I hope it is continue on this thread. Thanks.
