### ISSUE TITLE
GridFunction::ProjectGridFunction check

### ISSUE THREAD

**Issue by rw-anderson** [mfem/mfem#640]
Shouldn't this test be for equality?

https://github.com/mfem/mfem/blob/14808f8cabf832433f8c9a8e329798e6ce3a0f95/fem/gridfunc.cpp#L1101

**Comment by mlstowell** [comment]
Only if you want it to work as expected ;)

Interestingly @vladotomov just issued a pull request, #637, a couple days ago to fix this.

**Comment by rw-anderson** [comment]
Thanks!
