### ISSUE TITLE
Seg fault reading mesh

### ISSUE THREAD

**Issue by Dan2997925** [mfem/mfem#643]
I have an interesting 2D quad mesh, but I get a seg fault when I try to read it. The issue is in function
int Mesh::CheckBdrElementOrientation
in statement
faces_info[be_to_edge[i]]
the problem is that the be_to_edge array has -1's in it!!!

I confirmed that be_to_edge is the correct length it agrees with NumOfBdrElements.

So why does be_to_edge array have a few -1's in it? What does this mean? Is there really something wrong with my mesh, or does the mesh reader make some assumptions about the mesh topology that might be invalid for my cool mesh?

![quadmesh](https://user-images.githubusercontent.com/24529682/47245552-a91fbd80-d3ae-11e8-9ec2-c5187ba465ac.PNG)

**Comment by tzanio** [comment]
Dan, can you give us the mesh file?

**Comment by v-dobrev** [comment]
If `be_to_edge[i]` is `-1`, this means that the two vertices describing that boundary element do not correspond to an edge derived from the elements. For example, in the following mesh
```
0---1---2
|   |   |
|   |   |
3---4---5
```
if you define the `i`-th boundary edge to have vertices `0` and `2` then you will get a `-1` in `be_to_edge[i]`.

**Comment by Dan2997925** [comment]
Hi @junkudo can you take a look at this also in case there is an error in the 2D mesh reader? One thing we can do as a diagnostic is to add a call to 
int mfem::Mesh::EulerNumber2D 
inside the mesh reader class and print the result, this will tell us if the mesh has duplicate nodes.

**Comment by v-dobrev** [comment]
I debugged the issue a little further: the error occurs for boundary element (boundary edge) with index 99 which has vertices 3903 and 3901. On the other hand, the vertex-to-vertex connections (generated from the edges of all elements) contain only the following connections for the vertices 3903 and 3901:
```
vertices connected to vertex 3903: { 413, 7444 }
vertices connected to vertex 3901: { 411, 5971, 5968 }
```

If you want, I can add code to MFEM that will check for such boundary elements and remove them, if found. This should make it possible for you to load the mesh in MFEM.

**Comment by Dan2997925** [comment]
Its working now! The error was with the mesh my apologies for calling this a "bug".
