### ISSUE TITLE
Including petsc.h redefines MPI calls as PETSc macros

### ISSUE THREAD

**Issue by v-dobrev** [mfem/mfem#644]
I noticed that when MFEM is built with PETSc, MPI calls like `MPI_Isend`, `MPI_Irecv` are being replaced with PETSc macros. These macros come from `petsclog.h` which is included by the chian `petsc.h` -> `petscbag.h` -> `petscsys.h` -> `petsclog.h`. The comments inside the header indicate that these macros are intended for internal PETSc use: https://github.com/petsc/petsc/blob/0a42d0a183c9f292d6e79078ae7ca0ad5320b535/include/petsclog.h#L300-L303.

@jedbrown, @stefanozampini, do you know if this is the intended behavior?

**Comment by jedbrown** [comment]
That is intended to log such calls in user code, such as in a residual evaluation callback. Looking at the comment, you could `#define PETSC_HAVE_BROKEN_RECURSIVE_MACRO 1` but we should probably offer a better name for that. Cc: @BarrySmith.

I guess I would have expected that in a package like MFEM, the PETSc headers would not be visible outside of compilation units that specifically use PETSc, but looking at the code, I see that is not the case.

**Comment by v-dobrev** [comment]
Thanks for the feedback, Jed.

We can certainly remove `petsc.h` from the MFEM header `petsc.hpp` and only include it in `petsc.cpp`. However, we still need the declarations of PETSc types and objects (like `PetscInt`, `PetscScalar`, `Vec`, etc) inside `petsc.hpp` -- is there another lightweight PETSc header that we can use there instead of `petsc.h`?

**Comment by jedbrown** [comment]
There are some `include/*types.h` headers, but not for every package. I can add the missing ones, but it isn't in the current release. The forward declarations are all of the form `typedef struct _p_KSP *KSP` if you need.

**Comment by v-dobrev** [comment]
Thanks, Stefano! This is not a big issue, so no rush.

Let me know if I can help in any way.

**Comment by stefanozampini** [comment]
@v-dobrev I have a preliminary version in 
https://github.com/mfem/mfem/commit/432c673fa9a5605a5ceeb9ecbaebc74fdccf8936
This commit is on top of other changes I made in the last weeks: I'll open a PR soon.

If you want to test the new code, you need to use the new petscsytypes.h header file which is currently under PR in PETSc https://bitbucket.org/petsc/petsc/pull-requests/1198/add-header-for-sys-types-used-by-petsc/diff and `#define OLD 0`.

Otherwise, simply compile the source as it is with any PETSc version supported by MFEM

**Comment by v-dobrev** [comment]
Hi Stefano,

I just tested your branch (`stefanozampini/small-additions`) and it worked fine. I tested with PETSc 3.8.4 and 3.10.2.

I think it is better to replace the `OLD` macro with a check for the PETSc version (we need to include `petscversion.h` for that) - e.g. something like
```c++
#if PETSC_VERSION_LE(3,10,2)
```
instead of
```c++
#if OLD
```

Is the branch `stefanozampini/small-additions` ready for a PR?

Thanks a lot for addressing this issue!

**Comment by stefanozampini** [comment]
@v-dobrev The branch is ready (except for the `OLD` thing that I put there just for you to easily test the two cases :-) ). I'll open a PR as soon as I have some time (probably later in the week)

**Comment by v-dobrev** [comment]
Excellent! Thanks Stefano!
