### ISSUE TITLE
ParMesh::PrintAsOne() bug

### ISSUE THREAD

**Issue by Dan2997925** [mfem/mfem#645]
It looks like in ParMesh::PrintAsOne, in the switch statement near line 3996, there is a missing BREAK statement. I can certainly fix this, but I thought the author of this code should confirm the need.

**Comment by tzanio** [comment]
Hi Dan,

Which version of the code is this in? Can you give us the line number here:

https://github.com/mfem/mfem/blob/master/mesh/pmesh.cpp#L3996

**Comment by v-dobrev** [comment]
@Dan2997925, I think I'm the author of that section, and I think you are right -- there should be a break statement at the end of that `case 3`. Here is the exact place I'm referring to (you may need to scroll down in the box to see the end of the section):
https://github.com/mfem/mfem/blob/abe79bb2f398aa26dd005806b8b8883ef085b6f7/mesh/pmesh.cpp#L4097-L4111

**Comment by tzanio** [comment]
Good catch Dan. Can you propose a PR?
