### ISSUE TITLE
Question about filling right hand side of current source

### ISSUE THREAD

**Issue by TangLaoya** [mfem/mfem#648]
What you are describing is precisely what the `(Par)LinearForm` objects are used for.  I assume you can write your current density as a function of position so you can implement:
```void JFunc(const Vector &x, Vector &J);```
Then  you define an MFEM `VectorCoefficient` using this function:
```VectorFunctionCoefficient JCoef(dim, JFunc);```
If `JFunc` cannot be written then you may need to use a `VectorGridFunctionCoefficient` instead (assuming you have a `GridFunction` representation of `J`.)
Then setup the `LinearForm`:
```
LinearForm J(fespace);
J.AddDomainIntegrator(new VectorFEDomainLFIntegrator(JCoef));
J.Assemble(); /// This step performs the integration you mentioned
```
You can look at examples `ex3` and `ex3p` or the `tesla` miniapp for more details.  This scheme assumes that `JFunc` will be evaluated everywhere in the problem domain so it would need to return the zero vector outside of your rectangular region.  This is probably easy enough for a rectangular region but in some cases the region is too complicated.  An alternative is to mark the region containing the current density using a separate volume attribute.  The use a `VectorRestrictedCoefficient` which will only be applied to elements with this attribute.

Best wishes,
Mark

_Originally posted by @mlstowell in https://github.com/mfem/mfem/issues/632#issuecomment-430713638_

**Comment by TangLaoya** [comment]
Dear Mark,
Sorry to bother you again. Do you mean I only need to fill such code?
void JFunc(const Vector &x, Vector &J);
VectorFunctionCoefficient JCoef(3, JFunc);  /// is it correct to set dim=3 for 3-D problem?
LinearForm J(fespace);
J.AddDomainIntegrator(new VectorFEDomainLFIntegrator(JCoef));
J.Assemble(); /// This step performs the integration you mentioned

Now my problem is:
if the current density is defined as
J=100 for the region x=0, 0.04<=y<=0.041, -0.01<=z<=0.01, and J=0 for other region. 
How to fill the function JFunc that definition the current density?

In addition, how to calculate the electric field of any given point (x,y,z)?

Thanks,
Tang Laoya

**Comment by mlstowell** [comment]
Hi, @TangLaoya ,

Yes, the first argument of the `VectorFunctionCoefficient` constructor is the spatial dimension i.e. the length of the vector returned by `JFunc` in this case.

To define the current density you must know the vector value of J at each point in your problem domain.  Some of these vectors can be zero as long as they are of the correct length, 3 in this case.  I expect that you don't actually mean J=100 within that rectangular region.  You probably mean J=(100, 0, 0).  If you look through the examples and miniapps you should find many places where we define such vector functions.  If your wire changes direction you'll need to define J such that it follows the wire from one end to the other.  You won't find any examples in MFEM that are so complicated but you may need to do this.

Best wishes,
Mark

**Comment by TangLaoya** [comment]
Dear Mark,
Thank you very much for your kindly reply. Yes, in that rectangular region J=(100, 0, 0), but I want to try a simplified source assign method--I set the material in coil region to be copper, so that I only need to assign the current density in any one of region's section that is vertical to the vector of current density, therefore, I defined the region to be  x=0, 0.04<=y<=0.041, -0.01<=z<=0.01, is it correct? 

Thanks,
Tang Laoya

**Comment by mlstowell** [comment]
Hi, @TangLaoya ,

I'm not sure that would work.  One thing you could try is to setup a Laplacian problem for the electric potential and set the voltages at the ends of your coil to be fixed constants.  You would then solve `Div(sigma Grad Phi)=0` with `Phi` fixed at 0 and 1 at the ends of your coil and `sigma` equal to some large value in the copper and a comparatively small value outside the copper.  The current density could then be computed as `-sigma Grad Phi`.

Bests wishes,
Mark

**Comment by TangLaoya** [comment]
Dear Mark,
Thank you very much for your kindly reply. But my problem is frequency domain I need to calculate the induction voltage. Can it be solved by Laplacian function?

Thanks,
Tang Laoya

**Comment by mlstowell** [comment]
Hi, Tang,
Yes, if you're frequencies are slow compared to the time it takes for the current density to reach steady state within your wire then you can use a static solution to represent your current density.  If your frequencies are much faster than you'd need to run an eddy current simulation in the time domain to capture the details of the changes in the current density over the course of one period of your oscillation.  If this were necessary you'd have to abandon the idea of solving in the frequency domain.
Mark

**Comment by TangLaoya** [comment]
Dear Mark,
Thank you very much for your kindly reply. Now my goal is to calculate the induction voltage of received coil when transmitted coil's current is AC. I don't understand that 
 _if you're frequencies are slow compared to the time it takes for the current density to reach steady state within your wire then you can use a static solution to represent your current density_

in this case how to calculate the induction voltage?

Thanks,
Tang Laoya

**Comment by mlstowell** [comment]
Hi, Tang,
If your coil is driven by an alternating current then you can also think of that as being driven by an alternating voltage.  That means solving `Div(sigma Grad Phi(x,t))=0` with boundary conditions `Phi(a,t)=0` and `Phi(b,t)=V exp(i omega t)`.  Then `Phi` will have the same oscillatory time dependence so you can factor it out.  This leaves you with `Div(sigma Grad Phi(x))=0` with boundary conditions `Phi(a)=0` and `Phi(b)=V`.  This is a steady state version of the problem which is only valid if the conductivity is high enough (and it sounds like it will be).

Whenever you work in the frequency domain you need to remember that such approximations are only valid when the frequency is slow enough that the object you're studying has time to react to changes in the fields.  For example, currents cannot instantaneously change direction everywhere within a large object.  Changes in the voltages at the ends of the coil take time to propagate along the wire and settle down into a stable current.  The necessary time is related to the length of the wire and its conductivity.  If the frequency is high enough that the period of oscillation drops down to the scale of these reaction times then the frequency domain approximation breaks down.

Best wishes,
Mark

**Comment by TangLaoya** [comment]
Dear Mark,
Thank you very much for your kindly reply. As you suggested, I still need to solve the time-domain equation? But I think it is slow because it is necessary to solve multiple time steps. In addition, after solved the time-domain equation, how to get the induction voltage in the given received coils? Therefore, I still need to build the FEM equations as described in attached document. Now I can form and assemble matrix A, but for the right hand side b, I don't know how to fill it. I am not sure whether it is correct or not to set copper material to coil region and then assign current density ONLY on one section of the region, and therefore, the integration 
_int (dot(N, J), V)_ 
changes to 
_int (dot(N, J), S)_
where _V_ means domain of element and _S_ means the facet of element that is part of the section.

Thanks,
Tang Laoya

**Comment by mlstowell** [comment]
Hi, @TangLaoya ,

I apologize but I cannot open your Word document but perhaps you could convert this to PDF.

There is no time-domain equation if your frequencies are slow enough (and I'm sure they are).  You need to solve `Div(sigma Grad Phi)=0` with constant voltages at the ends of your coil.  This is not a time-domain equation it is a steady state equation (or you can call it an electrostatic equation).

Once you have the solution `Phi` which is computed using an H1 finite element representation you then get the current density right hand side by multiplying this with an operator which computes `-sigma Grad Phi`.  This operator can be computed using MFEM's `MixedVectorGradientIntegrator` and a coefficient which computes `-sigma`.

I'm sorry but I'm not sure what level of detail you require.  Perhaps you could tell me a little about your background.  What experience do you have with finite element software?  What experience do you have with electromagnetic theory?

Best wishes,
Mark

**Comment by mlstowell** [comment]
Hi, @TangLaoya ,

Equation 4 in the attachment which computes the right hand side is what we call a linear form (this is the correct term in finite element jargon.)  In MFEM there are two ways to compute linear forms.  The first is to use a `LinearForm` object as I have mentioned before.  This requires that you know how to write `J` as a function of position.  The second way to compute a linear form is to start with a `GridFunction`.  Equation 1 in the attachment is an example of what we call a `GridFunction`. When you multiply a `GridFunction` by a bilinear form the result is a linear form.  If you solve for `Phi`, as described earlier,  you can then multiply this by `-sigma Grad` (a bilinear form generated using the `MixedVectorGradientIntegrator`) you get a linear form representing `J`.  This is your right hand side vector (once you multiply it by the constants 'i' and 'omega').

Does this make sense?

Best wishes,
Mark

**Comment by TangLaoya** [comment]
Dear Mark,
Thank you very much for your kindly reply. I update the document I studied, in this document I described the background and my questions. Could you please help me to take a look at it?

Thanks,
Tang Laoya
[vector finite element stiff_full.pdf](https://github.com/mfem/mfem/files/2514088/vector.finite.element.stiff_full.pdf)

**Comment by mlstowell** [comment]
Hi, @TangLaoya ,

I understand the physics problem you are trying to solve, that was not my question.  My question was about you, professionally.  What is your professional level of experience?  Are you working for a private company?  Are you a professor?  Are you a student? Are you an amateur?  What is your field of study?  Any information to help me understand who I am speaking to would be useful.

Thank you,
Mark

**Comment by TangLaoya** [comment]
Dear Mark,
Thank you very much for your kindly reply. I am a Ph.D student working on electrical well-logging. Before this I have worked on resistivity well-logging in which the sources and receivers are electrodes, and the field can be solved by Laplacian equation. I have successfully written my own Fortran code to work on it by nodal finite element. Now I am trying to work on induction well-logging in which the sources and receivers are coils. I am still trying to write my own code by vector finite element. However, there are some technology problem in filling source term and doing post-process. I noticed that MFEM is an excellent software which works on general FEM in many fields include electromagnetic field calculation. I wish to study the implement technology from MFEM, but unfortunately, I am very poor in C++ coding so that it is very difficult to understand the code. Therefore, I have to ask very fool questions again and again. Sorry to bother you.

Thanks,
Tang Laoya



I

**Comment by mlstowell** [comment]
Hi, @TangLaoya ,
Now I think I understand.  You are not trying to use MFEM to solve your problem.  You're trying to write your own software based on some of the same ideas.  Your questions make much more sense to me now.

In this case I cannot offer you too much help but I'll be happy to give you hints.  You have probably already found the Nedelec finite element class, `ND_TetrahedronElement`, in `fem/fe.?pp`.  This will show you how we transform the vector-valued basis functions from reference space to physical space.  You should also look in `fem/liniteg.?pp` for the `VectorFEDomainLFIntegrator` class which computes the element integrals for linear forms.

Your other question regarding the computation on an induction voltage has a relatively simple answer (if you define your degrees of freedom in a convenient manner).  Nedelec degrees of freedom can be defined in different ways but the one I prefer (and I'm not sure MFEM uses this method) is to define the degree of freedom on an edge to be the path integral of the electric field along that edge.  With this definition the degree of freedom is equal to the voltage difference between the vertices that terminate the edge.  If you use this definition you can compute the path integral of an electric field by simply adding the degrees of freedom on the edges that define your path.  The only trick is that the orientation of the edges will reverse the direction of the path integral on some edges.  So, keep track of the edge orientations and multiply some of the degrees of freedom by -1 so that the path integrals will all have the same orientation.

Best wishes,
Mark

**Comment by TangLaoya** [comment]
Dear Mark,
Sorry to bother you again. 
Now I have understood how to fill the function JFunc to assign current source for regular shapes such as cylinder coils. However, for some complex shapes, you meant to use function 
'VectorRestrictedCoefficient' to do it. Could you please give me some examples to show how to use this function to assign current on a complex shape, for example, on an irregular loop with region number (or element attribute) 1, with current density J and direction (Jx, Jy, Jz) at (x, y, z)?

Thanks,
Tang Laoya
