### ISSUE TITLE
asking about MFEM

### ISSUE THREAD

**Issue by ozae** [mfem/mfem#65]
mind you if you can help me to add MFEM(finite element method library)to integrate with visual studio 2013?

**Comment by v-dobrev** [comment]
Hi,

The procedure for building MFEM with Visual Stuio is briefly described at the end of the [INSTALL](https://github.com/mfem/mfem/blob/master/INSTALL) file:
```text
Before using another build system (e.g. Visual Studio) it is necessary to create
a proper configuration header file, config/config.hpp, using the template from
config/config.hpp.in:

   cp config/config.hpp.in config/config.hpp

The file config/config.hpp can then be edited to enable desired options.  The
MFEM library is simply a combination of all object files obtained by compiling
the .cpp source files in the source directories: general, linalg, mesh, and fem.
```
Let me know if you have any further questions.

Veselin

**Comment by ozae** [comment]
ya but i can't understand what do we mean by it is necessary to create a proper configuration header file, config/config.hpp, using the template from config/config.hpp.in:
 but simply  do i have to run it in command window?

**Comment by v-dobrev** [comment]
What this means is to copy the file `config.hpp.in` in the `config` directory to a file named `config.hpp` in the same directory. Then edit `config.hpp` to enable MFEM options by un-commenting some of the commented out `#define` lines. The simplest option is to leave this file as it is - that should work too.

**Comment by ozae** [comment]
yes simply when i unzip the file,  config.hpp.in changed to config.hpp. but
what is next? which of the files i have to give in the directories for the
visual studio?

**Comment by v-dobrev** [comment]
The MFEM library is basically combination of all `*.cpp` files from the following directories: `general`, `linalg`, `mesh`, and `fem`. If you want to build an example or miniapp, you just need to link with the library and add the main mfem directory (this is where mfem.hpp is) as an additional include path.

**Comment by martemyev** [comment]
Hi All,

I've recently created a CMakeLists.txt file for configuration MFEM using cmake. My main motivation was that I use Qt Creator IDE on Linux for code development, and this IDE accepts CMake files as project files, and builds the whole tree of project sources, which is very convenient for navigation, debugging, etc. As you know, CMake also generates Visual Studio project files on Windows, so @ozae, you should be able to configure and compile MFEM on Windows relatively easily if you put [CMakeLists.txt](https://gist.github.com/martemyev/d37f5408dd085a24571013784b1d30dc) in the MFEM root directory, and [config.hpp.in_cmake](https://gist.github.com/martemyev/e79ea725a2575fb593e4a95f75ab7717) in the `config` directory. Then simply follow CMake instructions about how to build projects for Visual Studio.
Beware, that I *have not tested* these files on Windows, as I don't currently have an access to it. But that works fine on my Linux machine, so I assume it should so on Windows as well.
Please, let me know if it doesn't work. Any feedback on the files is also highly appreciated.

Cheers,
Mikhail

**Comment by v-dobrev** [comment]
Hi Mikhail,

Thank you for sharing the cmake files. I'll try them on Windows too.

If you are OK with it we can add them to MFEM.

Thanks,
Veselin

**Comment by martemyev** [comment]
Hi Veselin,

Sure thing. Please, feel free to include them in your repository. My only concern is that these files were not tested on different platforms.

Cheers,
Mikhail

**Comment by martemyev** [comment]
Hi Veselin,

Just wondering if you have tried this CMake file on Windows. Also, I updated it a little bit - mainly, I added MFEM_USE_* options in the CMakeLists.txt.

Cheers,
Mikhail

**Comment by v-dobrev** [comment]
Hi Mikhail,

I have not tried the cmake build yet - I just pulled the new version of `CMakeLists.txt`.

Thanks for the update,
Veselin

**Comment by tzanio** [comment]
Hi Mikhail,

Thanks for sending us your CMake file. I like that it does not over-write the current `makefile` files so both build systems can be used side-by-side.

Can the CMake file be extended to support building the examples and miniapps (like `make all`)?

Cheers,
Tzanio

**Comment by trb413** [comment]
Tzanio,

Veselin asked me to take a look, so I'm working on this. I have some
changes I'll push in the branch that will build the whole thing. I've been
offline all weekend; back on Thursday.

Cheers,
Tom

**Comment by tzanio** [comment]
Cool, thanks @trb413!

**Comment by tzanio** [comment]
We have started an internal branch for CMake which should be part of the next major release (3.3), so I'm closing this issue.
