### ISSUE TITLE
Resource ownership within classes should be documented

### ISSUE THREAD

**Issue by goxberry** [mfem/mfem#654]
Specifically, documentation of class members that are pointers or handles should state whether each pointer or handle owns the memory it refers to. For the sake of discussion, I am assuming that the class itself manages its resources correctly — that is, it uses `operator new` and `operator delete` correctly without leaking memory.

This issue can be subtle, because it also applies to containers of pointers. I first encountered the issue of resource ownership when looking at `LinearForm` objects. The members `dlfi`, `dlfi_delta`, `blfi`, and `flfi` seem to own the memory addressed by their elements (each is a container of pointers). The members `fes`, `blfi_marker`, and `flfi_marker` appear to contain non-owning pointers. 

A cursory search suggests the issue of pointer ownership documentation arises in other headers, but I’m not sure an exhaustive listing would be possible without individually inspecting each header — I just looked for headers that had pointer members without any note in the header re: pointer ownership (e.g., `pumi.hpp` was another one), and saw that there were multiple headers lacking pointer ownership documentation.

cc: @v-dobrev

**Comment by tzanio** [comment]
Thank you @goxberry. 

We acknowledge that this is an issue and are working to document ownership and its changes on a case-by-case basis.

**Comment by v-dobrev** [comment]
@tzanio, I already documented the pointer ownerships in the classes `(Par)LinearForm`, `(Par)BilinearForm` in #568, however, I'd like to keep this issue open to remind me, that there are other places where this still needs to be done.

**Comment by tzanio** [comment]
A lot of this was documented in #654, and will be further addressed as we continue to improve the documentation in the future.
