### ISSUE TITLE
LinearForm’s copy constructor might cause a segfault when the copy is deleted

### ISSUE THREAD

**Issue by goxberry** [mfem/mfem#655]
`LinearForm` doesn’t seem to obey the Rule of 3 — it doesn’t define a copy constructor explicitly, so an implicit copy constructor is used. I think this implicit copy-constructor could pose a potential problem because `dlfi`, `dlfi_delta`, `blfi`, and `flfi` will be deep-copied (owing to the copy constructor in `mfem::Array`), but the pointer elements within each of these `Array` objects will be shallow-copied — their addresses will be copied only. Given that each `LinearForm` owns the pointers in each of those `Array`s, it looks like the destructor for the original and the copy will each call `delete` on those pointers, which could cause a segfault. If I’m correct, then an appropriate explicit copy constructor will need to be defined for `LinearForm`. The lack of explicit copy-constructor also suggests that the assignment operators may need re-examining — these are typically implemented using a copy-and-swap idiom, and if the copy operation needs to be rewritten, the assignment operators probably need to be rewritten also.

cc: @v-dobrev, related to #654

**Comment by v-dobrev** [comment]
@goxberry,

I've never considered the implications of the implicit copy ctor and copy assignment operator in class `LinearForm`. I did not think they will be useful -- I guess I was wrong. 😃

I think @mlstowell's PR #568 (which I have not had time to review yet) already addresses some, if not all, of the issues you pointed out. If not, we can certainly add the missing parts.

**Comment by goxberry** [comment]
@v-dobrev I've quickly glanced at #568, and it looks like it implements a deep-copying copy c'tor, which removes the segfault/Rule of 3 issue above. I think the assignment operators would still need to be modified in #568 for consistency with the copy constructor, but doing so via [copy-and-swap](https://stackoverflow.com/questions/3279543/what-is-the-copy-and-swap-idiom) should only require minor changes.

**Comment by v-dobrev** [comment]
@goxberry, I started looking at #568 and I see that it does not provide actual copy constructors.

Let me try to clarify the issue that you are raising: is it (1) the current state of class `LinearForm` can be used in ways that leads to segmentation faults/memory corruption (specifically when using the implicit copy constructor and the implicit copy assignment operator); or is it (2) class `LinearForm` has to provide proper copy constructor, and proper copy assignment operator, so that it can be used safely with STL containers? Clearly, addressing (2) will resolve (1). However, if we are just trying to address (1), we can simply disallow copy construction and copy assignment (by making them private in c++03, or by deleting them in c++11) -- this is simpler than addressing (2).

**Comment by goxberry** [comment]
@v-dobrev You're right, #568 doesn't provide a copy constructor.

I'm raising issue (1). You're right that `LinearForm` need not expose a `public` copy-constructor -- implicitly or otherwise -- unless you want to permit users to write code that requires these operations, like passing a `LinearForm` object by value, or like your example of STL containers. `mfem::Vector` does have a copy constructor and a copy assignment operator, so it's not unreasonable for a user to attempt some operation with `LinearForm` objects that requires copying. I don't have any particular need for copy-constructing or copy-assigning `LinearForm` objects at the moment, so I have no strong opinions on issue (2). I support disallowing those operations or implementing appropriate versions of those operations instead of the implicitly-defined versions. Passing pointers or references instead of passing by value often suffices.

**Comment by v-dobrev** [comment]
Okay, let's just disallow the copy construction and copy assignment in class `LinearForm` (and similar classes like `ParLinearForm`, `BilinearForm`, etc). Later, if the need arises, we can implement proper copy constructors and/or copy assignments.

Does this sound reasonable? If so, I'll make the changes in #568.

**Comment by v-dobrev** [comment]
I believe this issue was resolved in #568 which is now merged.
