### ISSUE TITLE
[RFC] Proposal for Coefficient adapter classes: VectorElementCoefficient and MatrixElementCoefficient

### ISSUE THREAD

**Issue by goxberry** [mfem/mfem#657]
Following @mlstowell's good example, I was wondering if the MFEM team would have any use for the following adapter classes I'm writing for LLNL's design optimization library:

- `VectorElementCoefficient`: subclasses `mfem::Coefficient`; it takes an `mfem::VectorCoefficient` and an integer index `i` as constructor arguments, and its `Eval` method would return element `i` of the `VectorCoefficient`'s `Eval` method
- `MatrixElementCoefficient`: subclasses `mfem::Coefficient`; it takes an `mfem::MatrixCoefficient` and two integer indices `i` and `j` as constructor arguments, and its `Eval` method would return element `(i, j)` of the `MatrixCoefficient`'s `Eval` method

Arguably, these methods could be anti-patterns, but I find it useful to compute `VectorCoefficient`-related quantities like the center of mass or dipole moment as vectors, and `MatrixCoefficient`-related quantities like the moment of inertia or quadrupole moment tensors to avoid indexing mistakes in these computations. However, the design optimization library's design currently favors decomposing vector- and matrix-valued quantities into individual elements, which is why having these adapter classes is useful for us -- we may only want to bound a subset of components in our optimization problems.

**Comment by v-dobrev** [comment]
These two classes (`VectorElementCoefficient` and `MatrixElementCoefficient`) fit into the same theme as #590 - I think we can add them to that branch - unless @mlstowell has any objections.

**Comment by mlstowell** [comment]
No objections.  I think this is a fine idea.  Thanks, @goxberry !

**Comment by tzanio** [comment]
@goxberry, I'm closing this issue, but as indicated above, feel free to add to Mark's branch.
