### ISSUE TITLE
Getting ILU into HYPRE header for MFEM

### ISSUE THREAD

**Issue by vikramsg** [mfem/mfem#659]
Hi,

I am experimenting with the various solvers in MFEM(using Hypre) and I see that ILU is not there in the HYPRE header file even though HYPRE itself has PILUT. Does it mean that what I would need to do would be to create a class for it inside hypre.hpp similar to say PARASAILS. If so, any tips on doing this. Also if there is a branch where this has been done, please do point me to it.

**Comment by v-dobrev** [comment]
Hi @vikramsg,

I'm not aware of a branch that adds an MFEM wrapper for hypre's PILUT solver.

Such a wrapper class should be very similar to the `HypreParaSails` class. Based on what PILUT options you want to expose, you will need to add corresponding methods in the new class.

Note that supporting the `SetOperator` method (in the new class) is a bonus - right now, among the solver classes derived from `HypreSolver`, only `HypreBoomerAMG` supports that virtual method.

Let us know if you have any further questions.

**Comment by tzanio** [comment]
Note that PILUT is no longer supported and the *hypre* team recommends using Euclid instead, see Section 6.14 in the latest user manual.

Alternatively it may be simpler/better to use SuperLU or SRUMPACK, which are already integrated in the code (and actively supported).

**Comment by tzanio** [comment]
STRUMPACK uses low-rank approximation and could be used as a preconditioner. You can reach out to @pghysels for more details if you want.

That being said, it could be useful to also have na interface to Euclid.
