### ISSUE TITLE
File Directory Organization problem

### ISSUE THREAD

**Issue by Skyzerks** [mfem/mfem#663]
Hi!
I'm having a problem of comprehending how I should position the different components for the MFEM to work as a whole. Currently my main directory looks like this:

```
nemo@Skyzerks:/mnt/e/_Workspace/FEM/attempt$ ls
glvis-3.4      hypre-2.11.2         make-4.2         metis-5.1.0         mfem-3.4
glvis-3.4.tgz  hypre-2.11.2.tar.gz  make-4.2.tar.gz  metis-5.1.0.tar.gz  mfem-3.4.tgz
```

The "make" folder corresponts to GNU Make.
Currently I know that the mfem directory worked fine without GNU make, and I was able to build the GLVis meshes and check them out. But I just can't seem to find a way to organize the mfem directory with Metis, Hypre and building it with GNU make.
How should I place these directories for them to correspond to each other and make the GNU Make to do the building?

**Comment by Skyzerks** [comment]
In the MFEM repository I have only the file "config/defaults.mk.in". And all of the variables there are left in this type:

`variable_name = @variable_name@`

Is it normal for it to be like this? 
I get the feeling that the components can't find each other. And thus I assume why the following instructions for metis 5 can't execute:
```
nemo@Skyzerks:/mnt/e/_Workspace/FEM/attempt/metis-5.1.0$ make config
rm -rf build/Linux-x86_64
mkdir -p build/Linux-x86_64
cd build/Linux-x86_64 && cmake /mnt/e/_Workspace/FEM/attempt/metis-5.1.0 -DCMAKE_VERBOSE_MAKEFILE=1 -DGKLIB_PATH=/mnt/e/_Workspace/FEM/attempt/metis-5.1.0/GKlib
/bin/sh: 1: cmake: not found
Makefile:74: recipe for target 'config' failed
make: *** [config] Error 127
```
Where can I set the paths to metis, hypre and etc for mfem to use it?

**Comment by tzanio** [comment]
I think you may be confusing `config/defaults.mk` with `config/config.mk.in`.

See here: https://github.com/mfem/mfem/blob/master/config/defaults.mk.

It also looks like your METIS build didn't succeed because you do not have `cmake` which is required for that release. I will recommend using an older version.

**Comment by Skyzerks** [comment]
In fact my directory is something like this:
```
nemo@Skyzerks:/mnt/e/_Workspace/FEM/attempt$ ls
cmake-3.13.0-rc2         glvis-3.4      hypre-2.11.2         make-4.2         metis-5.1.0         mfem-3.4
cmake-3.13.0-rc2.tar.gz  glvis-3.4.tgz  hypre-2.11.2.tar.gz  make-4.2.tar.gz  metis-5.1.0.tar.gz  mfem-3.4.tgz
```
And that's why i'm asking about "how am I supposed to place each one of them"?
Do I need to put some of them inside the other one?

**Comment by tzanio** [comment]
> Do I need to put some of them inside the other one?

Nope. That's the intended structure.

**Comment by Skyzerks** [comment]
I didn't even saw the .mk files, they were just "makefile" formats for me already in my windows explorer. Thanks for pointing that out for me.
changed some lines in "mfem/config/defaults.mk":
```
MFEM_USE_METIS_5     = YES
HYPRE_DIR = @MFEM_DIR@/../hypre-2.11.2/src/hypre
ifeq ($(MFEM_USE_SUPERLU)$(MFEM_USE_STRUMPACK),NONO)
   ifeq ($(MFEM_USE_METIS_5),NO) .... 
else
METIS_DIR = @MFEM_DIR@/../metis-5.0
METIS_DIR = @MFEM_DIR@/../metis-5.0 #didn't change it
```
I've redone all the previous steps in, addressed in [steps before building metis](http://mfem.org/building/#parallel-build-using-metis-5). But the errors are still there when i try to "make" in metis 5 repository.  
If i missed something crusial in the "defaults.mk" file that I will need, please tell me. Also:
```
# Optional build tag
MFEM_BUILD_TAG = $(shell uname -snm)
```
What does this do?

**Comment by tzanio** [comment]
Did METIS build correctly? Your [previous post](https://github.com/mfem/mfem/issues/663#issuecomment-436328834) showed errors due to missing cmake...

**Comment by Skyzerks** [comment]
It still shows the same errors:
```
nemo@Skyzerks:/mnt/e/_Workspace/FEM/attempt/metis-5.1.0$  make config ; make
rm -rf build/Linux-x86_64
mkdir -p build/Linux-x86_64
cd build/Linux-x86_64 && cmake /mnt/e/_Workspace/FEM/attempt/metis-5.1.0 -DCMAKE_VERBOSE_MAKEFILE=1 -DGKLIB_PATH=/mnt/e/_Workspace/FEM/attempt/metis-5.1.0/GKlib
/bin/sh: 1: cmake: not found
Makefile:74: recipe for target 'config' failed
make: *** [config] Error 127
------------------------------------------------------------------------------
Building METIS requires CMake 2.8, found at http://www.cmake.org/, as
well as GNU make. Assumming CMake and GNU make are installed, two
commands should suffice to build metis:

     $ make config
     $ make
```

**Comment by tzanio** [comment]
A working installation of METIS is a requirement for MFEM :)

I will really recommend using this version instead: http://glaros.dtc.umn.edu/gkhome/fetch/sw/metis/OLD/metis-4.0.3.tar.gz

**Comment by Skyzerks** [comment]
Metis 5 is unstable? Do I lose much from installing the old version?

**Comment by tzanio** [comment]
> Metis 5 is unstable? 
No. You just need to use [CMake](https://cmake.org/) to build it.

> Do I lose much from installing the old version?
There shouldn't be any difference in terms of MFEM performance

**Comment by Skyzerks** [comment]
```
mkdir <mfem-build-dir> ; cd <mfem-build-dir>
cmake <mfem-source-dir>
```
The "source-dir" is the unpacked repo, right? So, what is the "build-dir"?

**Comment by goxberry** [comment]
METIS 5 uses less memory than METIS 4. I believe METIS 4 uses a quadratic-memory algorithm and METIS 5 replaces it with a linear-memory algorithm, but I could be misremembering — the details are in the METIS 5 documentation. In practice, METIS 4 memory usage hasn’t been an obstacle until we started working on meshes with a few million elements, refining them to a few hundred million to a few billion elements. Linking to METIS 5 resolved our out-of-memory errors at scale.

**Comment by tzanio** [comment]
> The "source-dir" is the unpacked repo, right? So, what is the "build-dir"?
> And do I need to be inside the CMake repo to do these operations?

This is just how CMake works. You can do `mkdir build; cd build; cmake ..; make`.

However, you don't need to use CMake to build MFEM. Your issue was that METIS was not building (which is completely independent project) and that version required CMake.

**Comment by Skyzerks** [comment]
I already installed CMake. Also I saw that somewhere there was a hint that I can use the builded CMake version later as a Visual Studio Project (which I have).
So, i need to use `cmake <mfem-source-dir>` in the CMake directory, mfem directory or a new directory, dedicated to the builded with CMake version?

**Comment by tzanio** [comment]
> So, i need to use `cmake <mfem-source-dir>` in the CMake directory, mfem directory or a new directory, dedicated to the builded with CMake version?

New directory, just for the CMake build.

**Comment by Skyzerks** [comment]
Okay, I builded the mfem repo with CMake.
So, from now on I have to link everything to the mfem version builded with CMake?

**Comment by tzanio** [comment]
> So, from now on I have to link everything to the mfem version builded with CMake?

That's preferable.

> Also, do i need CMake and GNU make, or just only one of them will suffice?

You just need one of them
