### ISSUE TITLE
Solving non-linear scalar PDE - Burger's equations

### ISSUE THREAD

**Issue by delcmo** [mfem/mfem#665]
Hi,

I am trying to solve Burger's equations as a learning exercise and implement flux limiters using DG. I looked at example 9 and 18. I modified ex18 to solve for Burger's equations instead of the density equation and set all other fluxes to zero (momentum equations and energy equation). This trick works but is not optimal: I can solve 1-D and 2-D problems. The reason I started from ex18 is that it implements classes to build the domain and interfacial integrators, and a Riemann solver. 

My questions:
1) The class that builds the domain integrator implements `AssembleElementMatrix2`. Should I use the same DomainIntegrator class for a non-linear scalar PDEs, or is it only adapted to non-linear system of PDEs?
2) Same question for `AssembleFaceVector` that computes the numerical flux at the interface.

Thanks,

Marco

**Comment by jdahm** [comment]
Hi Marco,

1. Yes, you should use it in the scalar case. `BilinearFormIntegrator::AssembleElementMatrix2()` can be used either for both linear and nonlinear cases, as long as it is reassembled at every timestep if needed. The way the equations are discretized here, this matrix is actually linear, so it doesn't need to be reassembled. If you're curious, MFEM has nonlinear integrators, but these are usually used in a nonlinear solve, e.g. Burgers' equation with implicit time-stepping.

2. Yes, you should still use `BilinearFormIntegrator::AssembleFaceVector()` for scalar equations.

The domain integral in this case is the same for all equations, so the `AssembleElementMatrix2()` code is the same as what you want to use for Burgers' equation. The difference will come in with the treatment of the face terms, where `num_equation = 1` in your case. As long as you use it with the correct scalar flux for Burgers' equation, it should work.

Hope this helps,
Johann
