### ISSUE TITLE
Printing a HypreParMatrix

### ISSUE THREAD

**Issue by pratyuksh** [mfem/mfem#672]
Hello,

That might be a very stupid question: how does one print a HypreParMatrix? I have not been able to figure it out. Please let me know. Thanks.

**Comment by mlstowell** [comment]
Hi, @pratyuksh ,

This is not a stupid question at all.  Most of MFEM's classes write to an `ostream` object but Hypre objects are different.  These take `char*` strings and use them to build output file names. A HypreParMatrix will take the string that you give it and append the processor ID to create a unique filename for each processor.  For example if you want to write to files named "my_mat.*" you can do the following:
```
string file_prefix = "my_mat";

HypreParMatrix A;

// Fill the matrix somehow
...

A.Print(file_prefix.c_str());
```
This will create files with names:
```
my_mat.00000
my_mat.00001
...
```
The matrix is written to these files with some header information followed by triplets of numbers giving the row index, column index, and value for each non-zero in the sparse matrix.

Best wishes,
Mark

**Comment by pratyuksh** [comment]
@mlstowell Thanks a lot, nicely explained. :)

**Comment by pratyuksh** [comment]
A brief question to complete this thread, how does one create a _copy_ of a given HypreParMatrix?

**Comment by mlstowell** [comment]
Hi, @pratyuksh ,
This is not an operation that we encourage.  We have constructors that take CSR data structures and create a new `HypreParMatrix` from them but these constructors typically share some of those data structures so they don't actually form a copy.  It's also not easy to obtain the necessary data structures from an existing `HypreParMatrix` even if you wanted to copy the necessary arrays before passing them to the appropriate constructor.  I've looked quickly through Hypre and they don't seem to offer a convenient function to copy matrices either.  They do have a 'copy' function but it looks like the target matrix needs to be properly prepared first.

I think I do know of one trick to accomplish a full matrix copy but it would not be the most efficient approach.  MFEM does provide a transpose operation for  Hypre matrices which forms a completely new matrix.  You could use this twice to create a copy and then delete the intermediate transposed matrix.  There is a possibility that this scheme would share the `row_starts` and `col_starts` arrays with the original matrix so there still a chance that this would not be a complete copy.
```
HypreParMatrix A;

// Fill the matrix somehow
...

HypreParMatrix * At = A.Transpose();
HypreParMatrix * Acpy = At.Transpose();
delete At;
```

Best wishes,
Mark

**Comment by v-dobrev** [comment]
Another option is to use the function `Add`:
https://github.com/mfem/mfem/blob/668a7cc3b99d3f376999909913516284b963f532/linalg/hypre.hpp#L490-L494
with the same `A` and `B` and `alpha = 1.0`, `beta = 0.0`.

**Comment by mlstowell** [comment]
I considered suggesting `Add` but I wasn't sure about the `col_map_offd` requirement.  Does this imply that the sparsity pattern of `B` has already been set?

**Comment by v-dobrev** [comment]
@mlstowell, `A` and `B` in this case are the same `HypreParMatrix` (the original), so the conditions to use `Add` are satisfied.

**Comment by mlstowell** [comment]
Oh, I see.  That's a good trick.

**Comment by pratyuksh** [comment]
@mlstowell @v-dobrev Thank you very much for the tips.
