### ISSUE TITLE
 Possible need for a QuadratureFunction type class for matrices/arrays?

### ISSUE THREAD

**Issue by rcarson3** [mfem/mfem#676]
I've currently noticed while working on some development work related to the Exaconstit-dev branch that working with matrices/arrays that lie at quadrature points can be a little awkward. You really need to make sure that you know whether or not you stored the data either in column or row-major order at the quadrature level. In my mind, it would be nice to have possibly a child class of QuadratureFunction that makes dealing with these arrays/matrices a much easier experience where you don't really have to worry about how things are stored. Also, I'd could see adding additional functionality like being able to pull out a specified row or column related to the matrix/array as being a nice feature. I could also see this class potentially mimicking in some ways how the Array2 class is built off the Array class in terms of building this off of the QuadratureFunction class. 

One thing I did see as being a potential painful point would be how to replicate the GetElementValues() function found in the QuadratureFunction class in a nice way, since if you were to think about this data structure would now appear 3D like in nature. 

Now I don't see this as being tough to implement, so I'd be happy to put together an initial prototype of it. However, I first wanted to hear from others and the main developers whether they'd like to see something like this implemented, or if people had additional ideas/thoughts on what this class should look like or be implemented.

**Comment by acfisher** [comment]
Yes, I could see something like this being useful.  Can you put together a quick psuedocode interface that captures what you are looking for and I explore the best way to fit it in and discuss it with the team.

**Comment by rcarson3** [comment]
So here's a rough sketch for what I was thinking that at least initially would be nice to have just to make handling the data a little nicer. Also, I can imagine there being various variations of the below as well.

```
//Name of the class is still completely in the air
//Potential ways to initialize
//I would consider having the tensors stored in column major order to play nice with
//the fact DenseMatrix is also column major order
//One method for where row and cols have same dimensions
QuadratureTensorFunction(qspace, dim)
//One method for where you specify both dimensions
QuadratureTensorFunction(qspace, row_dim, col_dim)
//Other initialization methods would also include where you supplied the initial data as well

//Some potential ways to access the data

//Returns the tensor located at the given quadrature point # and element #
DenseMatrix GetQuadratureTensor(integration_pt, elem_num)
//Returns a  specified column for a tensor located at a specified integration pt, and element #
Vector GetQuadratureTensorColumn(col_num, integration_pt, elem_num)
//Returns  a specified row for a tensor located at a specified integration pt, and element #
Vector GetQuadratureTensorRow(row_num, integration_pt, elem_num)
//A way to access a given point in the QuadratureTensorFunction 
//where i is the row #, j is the column #, k is the quadrature point #, and l is the element #
//I see this being similar to Array3D class () operator.
QuadratureTensorFunction operator() (i,j,k,l)
```

I'm sure some additional utility functions might be useful to have as well like a way to reshape the dimensions of the tensor while preserving the data itself. So, you'd need to make sure the new dimensions are compatible with the old dimensions (num_row_new * num_col_new) = (num_row_old * num_col_old). I feel like there might be a few more nice utility functions to have, but I can't think of them right now.

I hope this kinda gives you better idea for what I could see this class looking like.

**Comment by tzanio** [comment]
Closing this in anticipation of a more detailed discussion in an upcoming PR.
