### ISSUE TITLE
Circular 2D Mesh Creation Issues

### ISSUE THREAD

**Issue by Skyzerks** [mfem/mfem#677]
Hello.
I'm having a problem with creating a 2D circular mesh, similar to [this](https://monosnap.com/file/ZH8BTyBsquwLh9Mr9LZeG2EajHZWxE). I don't understand which of [these](http://mfem.org/mesh-formats) are more suited to make the desired mesh. 
And also are there any mesh generators which can generate meshes that are compatible with MFEM?
Thanks~

**Comment by jandrej** [comment]
> And also are there any mesh generators which can generate meshes that are compatible with MFEM?

See [http://mfem.org/meshing](http://mfem.org/meshing). You can create a circular mesh with GMSH which is free and the format can be loaded directly.

**Comment by Skyzerks** [comment]
So, the meshes, created in GMSH, can be directly used in MFEM?

**Comment by v-dobrev** [comment]
Yes, Gmsh meshes can be used directly in MFEM. There are some restrictions, though, e.g. currently, only linear elements are supported.

**Comment by tzanio** [comment]
In addition to Gmsh, you can also use [Netgen](https://ngsolve.org/) to define such a mesh.

Here is an example, generated with [this input file](https://github.com/tehnick/elmerfem/blob/master/ElmerGUI/samples/in2d/circle.in2d).

![glvis_s01](https://user-images.githubusercontent.com/1278247/48666973-ff048580-ea80-11e8-87bd-db9aee240caa.png)

You will also need [this script](https://github.com/mfem/mfem/issues/107#issuecomment-271013409) to post-process the results.

**Comment by Skyzerks** [comment]
@tzanio how does this string work?
`ng2d_new2old.sh test-netgen-output test.mesh`
So [ng2d_new2old.sh](https://github.com/mfem/mfem/issues/107) is the file that does the convertion,
test-netgen-output is the command that does the convertion,
and the [test.mesh](https://github.com/tehnick/elmerfem/blob/master/ElmerGUI/samples/in2d/circle.in2d) is the file used for conversion? 
But to do this I need to install [Netgen](https://ngsolve.org/) to make this happen?
Did I get that right?

**Comment by tzanio** [comment]
1. Install Netgen
2. Give it the `circle.in2d`  with `Load Geometry`
3. Click on `Generate Mesh`
4. Save the mesh to `circle.ngmesh` with `File/Export Mesh`
5. Convert with `ng2d_new2old.sh circle.ngmesh circle.mesh`

**Comment by Skyzerks** [comment]
I created a mesh using GMSH. But the I get this error when i try use it as it was generated from GMSH:
```
nemo@Skyzerks:/mnt/e/_Workspace/FEM/attempt/mfem-3.4/examples$ ./ex1 -m ../data/circle.msh
Options used:
   --mesh ../data/circle.msh
   --order 1
   --no-static-condensation
   --visualization


MFEM abort: Mesh file not found: ../data/circle.msh

 ... in function: mfem::Mesh::Mesh(const char*, int, int, bool)
 ... at line 2449 of file: mesh/mesh.cpp

Aborted (core dumped)
```
I need to convert it to MFEM version for it to be recognized, right?
Here is the .msh file
[circle_simple.txt](https://github.com/mfem/mfem/files/2592460/circle_simple.txt)
 that i've tried to test. It looks like [this](https://monosnap.com/file/OprIpCCwXSNLMVSlT8oCEC37X6xGY3) in GMSH.
I don't get it, which type of [mesh format](http://mfem.org/mesh-formats/) should I choose. And half of the file I don't undestand on what I should modify in it (lines: 10-13 & 16-79 are the most troublesome to understand for me).

**Comment by Skyzerks** [comment]
Using [issue #518](https://github.com/mfem/mfem/issues/518), i've tried to visualize the mesh. But I got the same error as a result. 
```
nemo@Skyzerks:/mnt/e/_Workspace/FEM/attempt/glvis-3.4$ ./glvis -m ../mfem-3.4/data/circle_simple.msh

       _/_/_/  _/      _/      _/  _/
    _/        _/      _/      _/        _/_/_/
   _/  _/_/  _/      _/      _/  _/  _/_/
  _/    _/  _/        _/  _/    _/      _/_/
   _/_/_/  _/_/_/_/    _/      _/  _/_/_/



MFEM abort: Gmsh file : vertices indices are not unique
 ... in function: void mfem::Mesh::ReadGmshMesh(std::istream&)
 ... at line 926 of file: mesh/mesh_readers.cpp

Aborted (core dumped)
```

**Comment by tzanio** [comment]
Unfortunately this looks like a new version of the Gmsh format that we do not support yet.

Can you try saving in the "Version 2 ASCII" format, following https://github.com/mfem/mfem/issues/518#issuecomment-401987021?

Alternatively you can try translating between the [version 4](http://gmsh.info/doc/texinfo/gmsh.html#MSH-file-format-_0028version-4_0029) and [version 2](http://gmsh.info/doc/texinfo/gmsh.html#MSH-file-format-version-2) formats yourself.

**Comment by Skyzerks** [comment]
I've done an [export ](https://monosnap.com/file/edPmJrefjJMGWvcEpVMszzpW1hZn7p) into a .mesh (Mesh - INRIA Medit) file. And the result is this
[circle_simple.txt](https://github.com/mfem/mfem/files/2593201/circle_simple.txt).
But MFEM doesn't recognize this format, although it seems more close to those meshes I saw in MFEM data folder. The only problem is that I don't know what should I modify for it to work. The problem I'm facing right now is:
```
nemo@Skyzerks:/mnt/e/_Workspace/FEM/attempt/glvis-3.4$ ./glvis -m ../mfem-3.4/data/circle_simple.mesh

       _/_/_/  _/      _/      _/  _/
    _/        _/      _/      _/        _/_/_/
   _/  _/_/  _/      _/      _/  _/  _/_/
  _/    _/  _/        _/  _/    _/      _/_/
   _/_/_/  _/_/_/_/    _/      _/  _/_/_/



MFEM abort: Unknown input mesh format: MeshVersionFormatted 2
 ... in function: void mfem::Mesh::Loader(std::istream&, int, std::__cxx11::string)
 ... at line 2715 of file: mesh/mesh.cpp

Aborted (core dumped)
```

**Comment by tzanio** [comment]
This is not a format we support directly, but here is its edited version in the (low-order) mfem mesh 1.0 format: [circle_simple.mesh.txt](https://github.com/mfem/mfem/files/2593216/circle_simple.mesh.txt).

**Comment by Skyzerks** [comment]
Yes! The visualization [worked](https://monosnap.com/file/9LcDi3xtQ9Pv5Umseh0YnNVjQgf5Hi).
And using example 1 to test the mesh also [worked](https://monosnap.com/file/5shsjYEeevFZslXgwdfOi34jlHLMN2).
Although it's needed to edit the file, at least it works!
Also, I have a question about creating my own example to operate on the mesh. Where can I find some documentation on how to get a quick start on making the program (similar to the programs in the example folder) itself?
Thanks~

**Comment by tzanio** [comment]
> Also, I have a question about creating my own example to operate on the mesh. Where can I find some documentation on how to get a quick start on making the program (similar to the programs in the example folder) itself?

The best thing is to start with one of the [examples](http://mfem.org/examples/) and modify according to your needs. See the [FEM documentation](http://mfem.org/fem/) if you are new to finite elements.
