### ISSUE TITLE
Recommended ways to output QuadratureFunction data to Visit using VisitDataCollection?

### ISSUE THREAD

**Issue by rcarson3** [mfem/mfem#679]
I'm currently trying to output some scalar simulation data that lie at quadrature points using ```VisitDataCollection``` to later visualize them in Visit. It appears based on the ```VisitDataCollection``` class that only nodal data is supported. I've used Equation 13: [https://doi.org/10.1016/0168-874X(94)00054-J](https://doi.org/10.1016/0168-874X(94)00054-J) in the past to project quadrature data to nodal points along with a least squares based method, and I was curious if there was a recommended way to do this in MFEM. I've attempted to emulate what's being done here: [https://github.com/CEED/Laghos/blob/master/laghos.cpp#L374-L386](https://github.com/CEED/Laghos/blob/master/laghos.cpp#L374-L386) to project data from the QuadratureFunction to GridFunctions. However, I can't seem to get it to work. I keep getting run time errors similar to the following:
```
Assertion failed: (dofs.Size() == vc.GetVDim()*Dof)
```

Here's some a snippet of code to give you an idea of what's leading to the above error:
```
    //Do all the typical initialization stuff above
   int dim = pmesh->Dimension();
   int order_v = 1; //Based on a comment in Issue #673 I've also tried this with order_v = 0.

   //I've tried other discontinuous FE spaces as well to see if I can't get it to work
   L2_FECollection l2_fec(order_v, dim);
   ParFiniteElementSpace l2_fes(pmesh, &l2_fec);
   ParGridFunction vonMises(&l2_fes);

   //intOrder is currently hard coded for a hex type element and needs to be updated later
   int intOrder = 2*order+1;
   QuadratureSpace qspace(pmesh, intOrder);
   QuadratureFunction q_vonMises(&qspace, 1);
   //q_vonMises is initialized to 0 and then it's later updated to the current von Mises stress
   //based on converged time step stress values from the simulation

   //After doing lots of computations...
   //This is a child class of the VectorCoefficient and holds a pointer to the quadrature data
   QuadratureVectorFunctionCoefficient *vonMisesStress;
   //Initialize the above class with the q_vonMises QuadratureFunction
   //The error occurs in here
   vonMises.ProjectCoefficient(*vonMisesStress);
```
If you can see anything that I might want to try instead to get this to work let me know. 

Alternatively, if the ```VisitDataCollection``` has the capabilities I'd be okay with averaging the quadrature point data and simply having the average elemental data just being displayed in Visit.

**Comment by jamiebramwell** [comment]
@rcarson3 , could you attach your code for the QuadratureVectorFunctionCoefficient? I have a feeling the problem is that the dimensionality is not set correctly and therefore the projection method fails.

**Comment by rcarson3** [comment]
@jamiebramwell  yep you should be able to see the [relevant header file here](https://github.com/mfem/mfem/blob/exaconstit-dev/miniapps/exaconstit/mechanics_coefficient.hpp) and the rest of the implementation [here](https://github.com/mfem/mfem/blob/exaconstit-dev/miniapps/exaconstit/mechanics_coefficient.cpp). 

I will say that this is an area that @srwopschall and I believe might be an issue, but we're not 100% sure if it didn't also have something to do with our choice of discontinuous FE space for the ParGridFunction that we wanted to project our quadrature data to.

**Comment by jamiebramwell** [comment]
I'm attempting to reproduce your problem, but on first glance it looks like the issue is that `q_vonMises` and `vonMises` are scalars while `vonMisesStress` is a vector. Is that a correct interpretation of your snippet?

**Comment by rcarson3** [comment]
So, ```vonMises``` , ```q_vonMises```, and ```vonMisesStress``` should all be scalar quantities that either lie at the nodes (```vonMises```) or quadrature points (```q_vonMises``` and ```vonMisesStress```).

I'm curious based on your comment though if these lines:

```
   //I've tried other discontinuous FE spaces as well to see if I can't get it to work
   L2_FECollection l2_fec(order_v, dim);
   ParFiniteElementSpace l2_fes(pmesh, &l2_fec);
   ParGridFunction vonMises(&l2_fes);
``` 
are causing the issue. I'm sure this is an issue with me still getting a nice grasp on ```mfem``` but is ```dim``` here not the dimensionality of the space your dealing with but instead the dimensionality of the field variable that you want to create?

**Comment by jamiebramwell** [comment]
The problem is `QuadratureVectorFunctionCoefficient *vonMisesStress`. If it is a scalar, it should be a plain `QuadratureFunctionCoefficient`. I am guessing the error comes from trying to project this vector coefficient onto a scalar `ParGridFunction`. Unfortunately, we don't have this is in the plain MFEM release, but it should be easy to implement. It would be similar to your `QuadratureVectorFunctionCoefficient`, but it would inherit from a `Coefficient` instead of a `VectorCoefficient`.

**Comment by rcarson3** [comment]
Okay thanks! I'll definitely try your suggestion out and see if things work.

**Comment by tzanio** [comment]
@rcarson3, were you able to resolve this? 

If I understand correctly, you can just project your vector coefficient onto a vector grid function, e.g. by changing  `l2_fes` to be (notice the last argument):

```c++
ParFiniteElementSpace l2_fes(pmesh, &l2_fec dim);
```

Alternatively you can extract each component as a scalar coefficient and project those separately.

Also, @kennyweiss has been working on visualizing point cloud data directly, so in the future it may not be necessary to project to a grid function.

**Comment by rcarson3** [comment]
@tzanio I haven't had the chance to try since my last reply. The UMAT support for ExaConstit that we'd mentioned about a few weeks ago in that offline ExaConstit discussion has been drawing most of my attention this week. @srwopschall has been working on this a bit more, and he might be able to weigh in if the above suggestions ended up working.

**Comment by kennyweiss** [comment]
> Also, @kennyweiss has been working on visualizing point cloud data directly, so in the future it may not be necessary to project to a grid function.

This is something that I am hoping to return to in the next few months.  I can prioritize it if there is external interest.  Please let me know.

**Comment by tzanio** [comment]
Thanks @kennyweiss, this will be a really nice feature to have!

**Comment by bslazarov** [comment]
Is QuadratureVectorFunctionCoefficient available in mfem - I cannot find it? I need such a functionality for my projects. Should I implement a general one or I can use one of your implementations?

**Comment by rcarson3** [comment]
@bslazarov I believe the only implementations of that class are currently in the applications ```Cardioid``` and ```ExaConstit```.  I'll put together a PR with this implemented over the next few days. It should be fairly straight forward to add to MFEM with the only changes being an additional helper function added to the ```QuadratureFunction``` class and the ```Coefficient``` classes themselves.
