### ISSUE TITLE
Using MFEM for evolving boundary problems

### ISSUE THREAD

**Issue by tmmcmanus** [mfem/mfem#68]
I looked through the examples on [http://mfem.org/](url) and was wondering if MFEM has ever been used for evolving (free boundary) problems.  For example to model, in real-time, wear or erosion due to an abrasive fluid (the fluid deforms the boundary and then the boundary influences the fluid flow).  I ask, because MFEM offers high-order curvilinear elements and this is something that I may be able to use in my research.  Thanks in advance.

-Tim

**Comment by tzanio** [comment]
Hi Tim,

I am not aware of MFEM being used in such simulations. Maybe one of our users has experience in this area and will like to chime in.

What do you expect from the discretization for these types of problems? We provide a lot of general and powerful FEM tools, but not much yet for connecting different meshes. We are interested in this topic though (e.g. for crack propagation, sliding contact, etc.), and plan to look at it in the future.

We will be happy if you find MFEM useful in your research. Let us know if we can help.

Cheers,
Tzanio

**Comment by tmmcmanus** [comment]
Tzanio,

Thanks for the reply, and apologies beforehand for the long post.

In terms of the discretization, I do not require anything terribly exotic.  At the moment, I am experimenting with simple 2D P1 elements and obtaining satisfactory results to solve my PDEs, but to deal with more complex boundaries (especially non-convex domains which occur in all of my applications), I may have to utilize curvilinear elements as well.  

It is worth pointing out that I am looking at the problem of mesh adaption from the r-adaptive perspective, namely the MMPDE (moving mesh partial differential equation) approach, where the solution of a PDE provides a continuous mapping between a computational domain (\Omega_{c}) and physical domain (\Omega_{p}).  See [analytic_vs_numerical_NS.pdf](https://github.com/mfem/mfem/files/341186/analytic_vs_numerical_NS.pdf) where I solve a modified version of Laplace's equation to produce a simple "smoothed" mesh for sinusoidal deformations along the northern and southern boundaries (here ^{A} is the analytic solution and ^{FEM} is the numeric solution).  Obviously this particular mapping is far from ideal for this particular example (and why this is the case is well understood), but I hope it illustrates the basics of what I would like to do in 2D and the type of deformations I deal with.

Since my last post, I looked more into MFEMS source code (starting from [Example 6: Laplace Problem with AMR](https://github.com/mfem/mfem/blob/master/examples/ex6.cpp)) and it seems that (at least in this particular example) you are effectively using h-adaptivity driven by an error estimator.  I may be able to couple this with my own technique (hr-adaptivity is something we have used in the past as well), but what caught my eye regarding AMR (and I am not 100% sure that MFEM is what is doing this, but I believe you work on both MFEM and BLAST so you may know), can be found halfway down [BLAST](http://computation.llnl.gov/projects/blast).  

To be specific I am talking about the figure that has  the labels: "Lagrangian Phase" and "Remesh/Remap Phase" which, I assume, relates to the "Curvilinear mesh optimization" and "High-order harmonic or inverse-harmonic smoothing algorithms" mentioned on that page.  I am particularly interested in the later of these two and any pointers on how I can access any information regarding this, e.g. source code, or publications, would be greatly appreciated.

Regards,

Tim

**Comment by tzanio** [comment]
Hi Tim,

This all sounds very interesting and relevant to what we do in the "remesh phase" of ALE. We also have a related project (ETHOS) that is looking specifically into high-order mesh optimization and r-adaptivity. Note that these algorithms are in addition to the non-conforming mesh refinement that we typically refer to as AMR, the difference being that the mesh topology is not changed, and that in ALE the mesh motion is prescribed by the physics (momentum conservation).

Unfortunately we don't have anything published on this topic, though we are working on an ALE paper which will include a section on the remesh phase. There is some discussion in one of our talks: http://computation.llnl.gov/projects/blast/ECCOMAS-12.pdf, slides 3-10, but admitedly this is at a fairly high level.

We are hoping to have a website for ETHOS soon, where we plan to add more details and documents regarding these algorithms. We also are planning to include a mesh optimization driver as a miniapp in  one of the upcoming MFEM releases.

Hope this helps,
Tzanio

**Comment by tmmcmanus** [comment]
Tzanio,

This certainly helps, and I look forward to the ETHOS website and the mesh optimization driver miniapp. 

Just to be clear, will the ETHOS project address r-adaptivity as it relates to evolving boundaries (i.e. \Omega (the entire physical mesh, and not individual elements) varies with time)? 

If so, it would be interesting to see how higher-order elements affect r-adaptive methods that rely on the equidistribution principle + Monitor function.  We have experience with using the the inverse-harmonic (Crowley/Winslow) method you describe on slide 9 (for Q1 elements), and have noticed that for particular evolving boundary problems, it performs poorly (for a pre-defined quality metric) and is computationally costly, compared to a Laplacian smoother.  I can elaborate on this further if you'd like.

Regards,

Tim

**Comment by tzanio** [comment]
Hi Tim,

We don't currently plan to look specifically into evolving domains, though if I understand the problem correctly, the tools we are developing can be applied in these settings too. We are not there yet though.

I'll forward this thread to the rest of the ETHOS team, in case they want to add to the discussion.

Cheers,
Tzanio

**Comment by tmmcmanus** [comment]
Tzanio,

I see. To start, I will try and reproduce what I already have coded up in C (PETSc) using the MFEM examples as a guide and If I get it working I will send it in.  In the mean time I will keep my eyes out for the ETHOS site.  Thanks for all the help. 

Regards,
Tim
