### ISSUE TITLE
Dirichlet condition for an elasticity problem

### ISSUE THREAD

**Issue by e-aranda** [mfem/mfem#683]
Hello, I am new at using MFEM and trying to solve an elasticity system imposing Dirichlet boundary values on only one component of the displacement vector, but I can't figure out how to do it. Any help?

Thank you.
Ernesto

**Comment by jakubcerveny** [comment]
Hi Ernesto, in ex2.cpp, on the line `fespace->GetEssentialTrueDofs`, I think you can pass a third argument (`component`) to only fix the specified component of the displacement. 

If you need different components on different boundaries you can call `GetEssentialTrueDofs` for different boundary attributes and then merge the returned DOF lists.

**Comment by AntoineMazuyer** [comment]
Here is an example.

Context : I have a mesh on which I want to block the displacement in the `x` direction on the boundary with index `4` (east boundary). I also want to block the displacement in `z` (or `y` according to the dimension of the problem) on the boundary with index `3` (bottom boundary).
```c++
    // We declare a vector of boundary attribute flags. If flag is 1, then this boundary
    // will have a Dirichlet condition
    mfem::Array<int> ess_bdr_bot(mesh->bdr_attributes.Max());
    mfem::Array<int> ess_bdr_east(mesh->bdr_attributes.Max());
    ess_bdr_bot = 0; // Init with 0 everywhere
    ess_bdr_east = 0; // Init with 0 everywhere
    ess_bdr_bot[3] = 1;
    ess_bdr_east[4] = 1;
    // We then extract the corresponding degree of freedoms and flag them
    mfem::Array<int> ess_tdof_list_bot;
    mfem::Array<int> ess_tdof_list_east;
    fes->GetEssentialTrueDofs(ess_bdr_bot,ess_tdof_list_bot,dim-1); // Block the vertical direction for the bottom boundary
    fes->GetEssentialTrueDofs(ess_bdr_east,ess_tdof_list_east,0); // Block the horizontal direction for the east boundary
    mfem::Array<int> ess_tdof_list;
    ess_tdof_list.SetSize(ess_tdof_list_bot.Size() + ess_tdof_list_east.Size());
    for(int i = 0 ; i < ess_tdof_list_bot.Size() ;i++) {
        ess_tdof_list[i] = ess_tdof_list_bot[i];
    }
    int offset = ess_tdof_list_bot.Size();
    for(int i = 0 ; i < ess_tdof_list_east.Size() ;i++) {
        ess_tdof_list[offset+i] = ess_tdof_list_east[i];
    }
```

I don't know if this is the most straightforward way to do it, but it works

**Comment by jakubcerveny** [comment]
I would probably wrap the functionality to obtain the DOFs into a function and call it twice, and then use Array::Append, but otherwise this looks OK.

**Comment by e-aranda** [comment]
Thanks, Antoine and Jakub. Another question related to components of vectors (maybe I would have to open a new issue?)

I have a grid function defined on vectorial finite element space:

    FiniteElementSpace *fespace = new FiniteElementSpace(mesh, fec,2);
    VectorFunctionCoefficient velocity(2,InitialVelocity);
    GridFunction u(fespace);
    u.ProjectCoefficient(velocity);

and I want to get a grid function of one of its components, I mean, `u = (u1,u2)` and I want `v=u1`

    FiniteElementSpace *newfspace = new FiniteElementSpace(mesh, fec);
    GridFunction v(newfspace);

but using

    u.ProjectVectorFieldOn(v,0)

gives me an error
    FiniteElement::CalcVShape (trans, ...)
       is not implemented for this class!

Any hints?

Thank you!
Ernesto

**Comment by jakubcerveny** [comment]
It will be better to open a new issue.
