### ISSUE TITLE
How to get a gridfunction from a vector component

### ISSUE THREAD

**Issue by e-aranda** [mfem/mfem#684]
Hello,  

I have a question related to components of vectors:

I have a grid function defined on a vectorial finite element space:

    FiniteElementSpace *fespace = new FiniteElementSpace(mesh, fec,2);
    VectorFunctionCoefficient velocity(2,InitialVelocity);
    GridFunction u(fespace);
    u.ProjectCoefficient(velocity);

and I want to get a grid function of one of its components, I mean, `u = (u1,u2)` and I want `v=u1`

    FiniteElementSpace *newfspace = new FiniteElementSpace(mesh, fec);
    GridFunction v(newfspace);

but using

    u.ProjectVectorFieldOn(v,0)

gives me an error. 

    FiniteElement::CalcVShape (trans, ...)
       is not implemented for this class!

I tried writting in other forms, but no luck. Any hints?

Thank you!
Ernesto

**Comment by v-dobrev** [comment]
Hi @e-aranda,

To copy a single component, you can use a loop like this:
```c++
   const int component = 0;
   for (int i = 0; i < v.Size(); i++)
   {
      v(i) = u(fespace->DofToVDof(i, component));
   }
```
You can also avoid the copy and just have `v` simply point to the data inside `u` (this is only possible when `fespace` uses the default `Ordering`, `Ordering::byNODES`):
```c++
   GridFunction v;
   const int component = 0;
   v.MakeRef(newfspace, u, component*newfspace->GetVSize());
```

**Comment by e-aranda** [comment]
Thanks Veselin.
