### ISSUE TITLE
Unexpected behavior with Mesh::ReorderElements() and  mfem::IsoparametricTransformation::GetPointMat()

### ISSUE THREAD

**Issue by junkudo** [mfem/mfem#685]
Hey,
I have a snippet of code that loads up a mfem provided high-order mesh and looks at a single element transformation's point matrix before and after reordering.  I expect the resulting matrix to contain the same set of points : 
```c++
   // Load up high-order quad mesh
   std::string mesh_file = "star-q2.mesh";
   mfem::Mesh mesh(mesh_file.c_str(), 1, 1);

   // Look at elem 0's element transformation's point matrix
   mfem::IsoparametricTransformation * iso_elem_trans;
   iso_elem_trans = dynamic_cast<mfem::IsoparametricTransformation *>(mesh.GetElementTransformation(0));
   assert(iso_elem_trans != NULL);
   iso_elem_trans->GetPointMat().Print();

   // Reorder mesh by switching around last two elements of mesh
   int nelem = mesh.GetNE();
   mfem::Array<int> reordering(nelem);
   for (int i = 0; i < nelem; ++i) {
      reordering[i] = i;
   }
   reordering[nelem - 1] = nelem - 2;
   reordering[nelem - 2] = nelem - 1;

   // Ensure that elem 0 remains elam 0
   assert(reordering[0] == 0);
   mesh.ReorderElements(reordering);

   // Look at elem 0's element transformation's point matrix
   iso_elem_trans = dynamic_cast<mfem::IsoparametricTransformation *>(mesh.GetElementTransformation(0));
   assert(iso_elem_trans != NULL);
   iso_elem_trans->GetPointMat().Print();
```

However, I'm getting the following output : 
```bash
[row +0]
-2.454380e-02 +5.300620e-01 +6.748660e-01 +1.628520e-01
+2.530430e-01 +5.550630e-01 +3.892290e-01 +7.410290e-02
+3.318290e-01
[row +1]
+3.026530e-02 +1.198990e-03 +4.820680e-01 +4.719240e-01
-3.692510e-03 +2.408630e-01 +4.683540e-01 +2.333160e-01
+2.335440e-01
[row +0]
-2.454380e-02 +6.263740e-01 +6.748660e-01 +1.628520e-01
+2.530430e-01 +5.550630e-01 +3.892290e-01 +7.410290e-02
+3.318290e-01
[row +1]
+3.026530e-02 -4.801480e-01 +4.820680e-01 +4.719240e-01
-3.692510e-03 +2.408630e-01 +4.683540e-01 +2.333160e-01
+2.335440e-01
```
which plotted, looks like..
![image](https://user-images.githubusercontent.com/1308006/49110418-4ab5ec80-f242-11e8-839c-cb1fa9ab0040.png)

I suspect that the mesh is incorrectly grabbing a point from another nodal coordinate from another element because something internal to the mesh is not being updated properly during the re-ordering procedure.  Let me know if I'm misunderstanding what I should expect.  I ran into this bug when I was trying to debug an issue with using the `Mesh::FindPoints` routine.

CC @Dan2997925

**Comment by junkudo** [comment]
I'm fairly certain I tried this in my frenzy of attempting different
things.  I'll confirm tomorrow.

**Comment by v-dobrev** [comment]
Actually, there is a bug in `Mesh::ReorderElements`. I created a branch, `mesh-reorder-elem-fix`, and PR (#686) with a fix.

**Comment by junkudo** [comment]
This seems to work for me in both my little test-case and my larger actual use case.  Thanks!  When can I expect this change to be merged into master?  (And then when can I expect to see a new version of mfem after this merge?)

**Comment by tzanio** [comment]
> When can I expect this change to be merged into master? 

In about a week, see https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#masternext-workflow

> (And then when can I expect to see a new version of mfem after this merge?)

We are currently planning the next release to be mfem-4.0, which will be a major release in the first half of 2019. Let us know if you do need an official release before that.
