### ISSUE TITLE
Linear form in H^1_0

### ISSUE THREAD

**Issue by e-aranda** [mfem/mfem#689]

**Comment by v-dobrev** [comment]
Hi Ernesto,

As an alternative to your approach, the non-linear diffusion operator that you have can be expressed in MFEM as a `NonlinearForm` where you need to define the appropriate `NonlinearFormIntegrator`. If you are mainly interested in the action of the operator, your `NonlinearFormIntegrator` just needs to define the virtual method `AssembleElementVector`. The implementation will be similar to the implementation of `DiffusionIntegrator::AssembleElementVector`:
https://github.com/mfem/mfem/blob/87f86d45c927ad5fa001a82c96ec29ca0def37ff/fem/bilininteg.cpp#L517
taking into account the special form of your diffusion coefficient.

With a `NonlinearForm`, you can impose essential b.c. by calling one of its methods: `SetEssentialBC` or `SetEssentialTrueDofs`. What this does is to modify the action of the nonlinear operator (i.e. its `Mult` method) by setting the essential dofs in the output vector to zero.

Hope this helps,
Veselin

**Comment by e-aranda** [comment]
Thank you Mark and Veselin,

with respect to imposing zero boundary conditions, I have multiplied by a `GridFunction` which is 1. inside the domain and 0. on the boundary and it works (I don't know if it is better solution than creating the linear system and then multiplying by the matrix). 

The Marks' suggestion about writing the linear form as $(-\nabla \cdot \vec{f}) v$ does not work for me because I would need more regularity on f and I haven't.

I am very new at MFEM and I don't understand very well Veselin's approach. This `NonlinearForm` would be something equivalent to a bilinear form, I mean, finally would I have a matrix, and then obtain a vector?

On the other hand, would it be possible to write a `LinearFormIntegrator` similar to `DomainLFIntegrator` for the expression  $(\vec{f},\nabla v)$? 

Thank you again.
Ernesto

**Comment by tzanio** [comment]
Hi Ernesto,

I can think of a nonlinear form as a bilinear form with a coefficient that depends on the input, in your case the bilinear form is just diffusion, and the coefficient is "\frac{1}{\sqrt{1+|\nabla u|^2}".

Linear forms produce vectors (right-hand sides), so if you need a matrix you can't use that.

Depending on your application you have two options: 1) use an old value of u in the coefficient, in which case you can just define a `Coefficient` for that and use it with the `DiffusionIntegrator`, or 2) use the current value of u, which will require a `NonlinearForm` and some nonlinear solver to invert it.

Hope this helps,
Tzanio

**Comment by e-aranda** [comment]
Thanks Tzanio,

I have used the first option you comment: create a coefficient  "\frac{1}{\sqrt{1+|\nabla u|^2}" and then build a matrix with a DiffussionIntegrator. But as I want a vector, then I have to multiply the matrix by u. 

Regards,
Ernesto

**Comment by tzanio** [comment]
If you really don't need to solve a system with `a` in your code above, but just need to compute `x` given `u`, then a `LinearForm` could indeed be a better choice.

As you said, you will need to add a `LinearFormIntegrator` for $(\vec{f},\nabla v)$. This is totally doable and you can probably do it yourself if you study `DiffussionIntegrator` and `DomainLFIntegrator`.

**Comment by tzanio** [comment]
I'll close this now, but feel free to reopen if you have further questions.

**Comment by e-aranda** [comment]
Hi,

I have added a `LinearFormIntegrator` for $(\vec{f},\nabla v)$, where $\vec{f}$ is a `VectorCoefficient`.  Now I would like to add a new one for $(\nabla f,\nabla v)$ for a coefficient $f$. I have done in a way that I am not sure if it is the best option. I have created a `VectorCoefficient` from a `GridFunction` U, and defined the `Eval` method for the new `VectorCoefficient` with the `GetGradient` method. Here is the code:

    // Coefficient for gradient evaluation
    class CoeffGrad : public VectorCoefficient
        {
        private:
            GridFunction &U;
        public: 
            CoeffGrad(int d, GridFunction &_u) : VectorCoefficient(d), U(_u) { }
            virtual void Eval(Vector &V, ElementTransformation &T, const IntegrationPoint &ip);
            virtual ~CoeffGrad() { }
        };

    void CoeffGrad::Eval(Vector &V, ElementTransformation &T, const IntegrationPoint &ip)
    {
	    U.GetGradient(T, V);  
    }

and now, I define 

    FunctionCoefficient coefic(analytic); // for some analytic function
    GridFunction U(p1espace);
    U.ProjectCoefficient(coefic);
    CoeffGrad coef(dim,U);

    LinearForm *c;
    c = new LinearForm(p1espace);
    c->AddDomainIntegrator(new MyVecIntegrator(coef));

where `MyVecIntegrator` is the mentioned `LinearFormIntegrator`. 

Is it the best way to do this?
