### ISSUE TITLE
MFEM archive for Windows

### ISSUE THREAD

**Issue by martemyev** [mfem/mfem#69]
Hi All,

Recently, I was trying to help a student to build the MFEM library on a Windows machine. Even though there were some issues with that particular machine, and we ended up building it on Mac, I would like to let you know that even the very first step of obtaining the source code from the mfem.org was an issue. The archive has the .tgz format, which is totally okay if you're on a Unix-like machine, but it turned out that Windows doesn't necessarily have tools to unarchive that. There are, of course, tools like 7-zip and so on, available for Windows, but without admin rights we couldn't install anything.

My suggestion is therefore to have a .zip archive along with .tgz on the main page of mfem.org for those who use Windows machines. As an example, CMake comes as a tar.gz archive for Unix OS, and as a .zip archive for Windows.

Cheers,
Mikhail

**Comment by tzanio** [comment]
Thanks Mikhail,

Let us think about it... maybe we can add another button with a Windows-friendly archive.

While not optimal, one can always download the ZIP file for the master branch on GitHub, https://github.com/mfem/mfem/archive/master.zip.

Cheers,
Tzanio

**Comment by martemyev** [comment]
Hi Tzanio,

Ah, indeed, there is a way to download the zip archive from GitHub. I forgot about it. But anyways, another button with a Win-friendly archive would be also very nice.

Cheers,
Mikhail

**Comment by tzanio** [comment]
BTW, @martemyev, check out the updated http://mfem.org/about page.

**Comment by martemyev** [comment]
@tzanio That's super cool. Thank you guys!
