### ISSUE TITLE
Computing the bounding box of an element

### ISSUE THREAD

**Issue by junkudo** [mfem/mfem#695]
Hey,
I have hopefully what's a pretty simple question.  I'm interested in computing the bounding box of a (potentially higher-order) element.  What's the best way to do that in MFEM?
Thanks!

**Comment by tzanio** [comment]
For high-order elements computing the bounding box is actually not trivial.

One approach is to compute the bounding box on a lattice of points in reference space that is transformed with the element transformation. For very curved elements this may not be exact, but the accuracy approves with the lattice refinement level. See https://github.com/mfem/mfem/blob/903d51e78fab387f2d6c72bb3eed108bc0fd9d1f/mesh/mesh.cpp#L164-L174 in `Mesh::GetBoundingBox`.

A method that guarantees correct (but maybe pessimistic) bounding box is to switch to Bernstein basis for the nodes. @kennyweiss has some experience with that.

**Comment by Dan2997925** [comment]
Does it need to be a box? Is the box aligned with (x,y,z) coord system? Depending upon the application a bounding sphere may work, center of sphere is center of the element, radius of sphere is determined by evaluating the physical coordinates of the vertices and taking the one which is farthest away. If you then really need a box, tyou

**Comment by Dan2997925** [comment]
Ug wasn't finished typing.....
Can then find a box that fits the sphere

**Comment by kennyweiss** [comment]
Elaborating a bit on the second part of @tzanio's answer: The element is contained within the convex hull of its nodes (control points) in the Bernstein basis.  These bases are referred to as ``Positive`` bases in mfem.

So, one approach would be to project the element into a Bernstein basis and then process the element's nodes.  By taking the min and max coordinates of an element's nodes, you can easily find the element's bounding box in physical space.  Following @Dan2997925's answer, one can also fit a sphere or oriented bounding box to these nodes. 

As @tzanio mentioned, this is a conservative estimate of the element's true bounding box.  If necessary, tighter bounds can be obtained by subdividing the element (h-refinement) or increasing its polynomial order (p-refinement).

If you need this for all elements in the mesh, you can use mfem's [GridFunction::ProjectGridFunction()](http://mfem.github.io/doxygen/html/classmfem_1_1GridFunction.html#af50b7ddf2f50767fdbced0e1c4d0981b) to project its nodal grid function.

**Comment by tzanio** [comment]
@junkudo: was this useful? do you have any follow-on questions?

**Comment by junkudo** [comment]
Yeah this was helpful. Thanks!

**Comment by tzanio** [comment]
Great!

I'll close this now, but please let us know if you have additional questions.

Also, feel free to suggest a PR if you write something that could be of general interest (e.g. bounding sphere or convex set).
