### ISSUE TITLE
Axi-symmetric support

### ISSUE THREAD

**Issue by cjoycd** [mfem/mfem#696]
Dear all,

Is there axis-symmetric co-ordinate (Cylindrical  #-- RZ) support readily available in MFEM library. 
Please suggest.

**Comment by tzanio** [comment]
Hi @cjoycd,

There is no simple user-level support for axisymmetric problems, but switching to an axisymmetric formulation is usually not hard -- you have to add the "2 pi r" factors in the bilinear form integrator's Coefficient and transform derivatives appropriately, see for example this paper: https://computation.llnl.gov/projects/blast/CF-12.pdf.

Hope this helps,
Tzanio

**Comment by cjoycd** [comment]
Thanks !, Infact I was particularly interested in the axisymmetric
implementation of the "laghos" miniapp. I will go through the paper.

Regards

**Comment by cjoycd** [comment]
Hi,

Is it planned to implement axisymmetric element support in MFEM in near
future ?

Regarding your answer to modify the coefficients in BilinearForm
Integrators, Can you please more specific in which functions/class it has
to be done, so that the modifications/changes can be a general one for the
users.

Regards

**Comment by cjoycd** [comment]
Dear Mark,
Ok, Thanks!. I am interested in implementing the axisymmetric version of
Laghos using the paper Tzanio mentioned in two temp model for laser driven
dynamics. There, I have to modify the mass & force matrix and to include
few additional terms in artificial viscosity. I was wondering, at least for
this purpose, can we have separate routines defined for mass & force matrix
assembly in which the "r" terms (neglecting the 2*pi factor) are multiplied
(I would also liked to know which routines/modules it could be ideal).
Prior to that, I am interested in the implementation of radiation transport
& electron conduction, where in the first step a flux limited diffusion
(FLD) scheme will be used. Here, also the electron-heat & radiation fluxes
are required to be multiplied with "r". I will see to implement the
diffusion calculation implemented in RZ co-ordinates first. In 3D these are
somewhat straightforward.

Thanks & Regards

-----------------------------------------------------------
*Dr. Sijoy C. D.*       *Scientific Officer (F) *
Computational  Analysis  Division  (CAD)
Bhabha Atomic Research Centre (BARC)
Visakhapatnam, AP, India,  PIN - 530012
Ph: 0891-2892156 (O), 09912640800 (M)
------------------------------------------------------------
