### ISSUE TITLE
 about the class mfem::SparseMatrix

### ISSUE THREAD

**Issue by ShiyangZhang** [mfem/mfem#70]
HI,  SparseMatrix::operator() does not work well when A[i][j] is equal to  0.

Here is the code from line 364-385  of sparsemat.cpp:

double &SparseMatrix::operator()(int i, int j)
{
   int k, end;

   MFEM_ASSERT(i < height && i >= 0 && j < width && j >= 0,
               "Trying to access element outside of the matrix.  "
               << "height = " << height << ", "
               << "width = " << width << ", "
               << "i = " << i << ", "
               << "j = " << j);

   MFEM_VERIFY(Finalized(), "Matrix must be finalized.");

   end = I[i+1];
   for (k = I[i]; k < end; k++)
      if (J[k] == j)
      {
         return A[k];
      }

   **MFEM_ABORT("Did not find i = " << i << ", j = " << j << " in matrix.");**
   return A[0];
}

**Comment by martemyev** [comment]
Hi @ShiyangZhang,

Please, elaborate on how do you think it should work, because to me this is the expected behavior of the method.

Thanks,
Mikhail

**Comment by ShiyangZhang** [comment]
HI @martemyev , Thank you for your reply. when A[i][j] is equal to 0, I think A(i,j) should return 0.0, but 'MFEM abort' occured.
Shiyang

**Comment by martemyev** [comment]
Ah, I see.
The thing is that the method you're referring to:
```cxx
double &SparseMatrix::operator()(int i, int j)
{
   int k, end;

   MFEM_ASSERT(i < height && i >= 0 && j < width && j >= 0,
               "Trying to access element outside of the matrix.  "
               << "height = " << height << ", "
               << "width = " << width << ", "
               << "i = " << i << ", "
               << "j = " << j);

   MFEM_VERIFY(Finalized(), "Matrix must be finalized.");

   end = I[i+1];
   for (k = I[i]; k < end; k++)
      if (J[k] == j)
      {
         return A[k];
      }

   MFEM_ABORT("Did not find i = " << i << ", j = " << j << " in matrix.");
   return A[0];
}
```
is a "set" method, i.e. it modifies the element (i,j) of the matrix. So, if the element (i,j) is 0, it's not in the matrix, and you get a crash when you try to access an non-existing element.

The method you're probably interested in is this one:
```cxx
const double &SparseMatrix::operator()(int i, int j) const
{
   int k, end;
   static const double zero = 0.0;

   MFEM_ASSERT(i < height && i >= 0 && j < width && j >= 0,
               "Trying to access element outside of the matrix.  "
               << "height = " << height << ", "
               << "width = " << width << ", "
               << "i = " << i << ", "
               << "j = " << j);

   MFEM_VERIFY(Finalized(), "Matrix must be finalized.");
   end = I[i+1];
   for (k = I[i]; k < end; k++)
      if (J[k] == j)
      {
         return A[k];
      }

   return zero;
}
```
which is a "get" method, i.e. non-modifying. It's applied to `const` objects only. Therefore, if in your code you have a non-const object of the SparseMatrix class, the first "set" method is called. Here is an example:
```cxx
SparseMatrix &A1 = bilinear_form.SpMat();
double val = A1(0, 0); // calls non-const method, and if (0,0) element was 0, that crashes
const SparseMatrix &A2 = bilinear_form.SpMat();
double val = A2(0, 0); // calls const method, and if (0,0) element was 0, that returns 0
```

Hope that helps.

Mikhail


SparseMatrix

**Comment by ShiyangZhang** [comment]
Dear Mikhail,

It helps and thank you for your reply very much. As I  am not quite familiar with C++,    an additional    "set" method makes me confused. What is the usage of this method?

Thanks very much.

Shiyang.

**Comment by martemyev** [comment]
The "set" method is used when you want to change a value of an existing non-zero element in the sparse matrix. Another example:
```cxx
SparseMatrix &A1 = bilinear_form.SpMat();
A1(0, 0) = new_value; // if (0,0) was non-zero, i.e. it's saved in the A1 matrix, you can change it with the "set" method
const SparseMatrix &A2 = bilinear_form.SpMat();
A2(0, 0) = new_value; // this is not allowed by a compiler, because the A2 is a const object, and you can't change it's state
```

Best,
Mikhail

**Comment by ShiyangZhang** [comment]
Dear Mikhail,

It helps and thank you for your reply very much. but  I do think we have the right to read a 0.0 from a sparse matrix.

Sincerely,
Shiyang

**Comment by martemyev** [comment]
If you have a non-const SparseMatrix object, and you just must read all elements including zeros, which are not saved in there, you can convert your object in the const one temporarily to let the compiler call a proper method for you:
```cxx
SparseMatrix &A1 = bilinear_form.SpMat();
for (int i = 0; i < A1.Height(); ++i)
  for (int j = 0; j < A1.Width(); ++j)
    double val = const_cast<const SparseMatrix&>(A1)(i, j);
```
That should work, but I haven't tried. So, please let me know if that solves your problem.

Best,
Mikhail

**Comment by ShiyangZhang** [comment]
thanks for your method. I test it and it  works well.  As what  I need  now is just check values of A(i,j) for some (i,j) for some simple numerical experiments i did, 'abort' seems  also ok . Thank you.
