### ISSUE TITLE
I want to use mfem as a adaptive mesher for my FVM code

### ISSUE THREAD

**Issue by ztdepztdep** [mfem/mfem#701]
Dear group:
   Could you please give me some suggestions about how to extract the grid infors(cell centers, face center, etc.) from the mfem. so i can use it for my fvm code.
   Regards

**Comment by jakubcerveny** [comment]
Are you interested in regular (conforming) meshes or non-conforming (hanging node) meshes?

**Comment by ztdepztdep** [comment]
Dear sir:
     I need to perform local refinement, so non-conforming meshes is a good choice.

**Comment by jakubcerveny** [comment]
We can locally refine in both cases: for triangles and tetrehedra we do bisection (we make sure there's enough bisections to keep the mesh conforming), for quads and hexes we do hanging nodes through the internal NCMesh class. 

Extracting the complete geometry and topology of the mesh may not be trivial but is definitely possible. Look at the `Mesh` class and functions like `GetVertex`, `GetElement`, `GetFace`. There's also connectivity tables like `ElementToElementTable` (neighbors), `ElementToEdgeTable`, etc. 

In the case of an NC mesh, you could get adjacency of coarse-fine neighbors from the `faces_info` and `nc_faces_info` arrays (they are not public though), or directly from the NCMesh class (`GetFaceList` and similar).

**Comment by ztdepztdep** [comment]
thank you , i will have a try. when i get progress, i will let you know.

**Comment by jakubcerveny** [comment]
I'll close this now but feel free to reopen with more questions.
