### ISSUE TITLE
MFEM periodic mesh usage in linear elasticity example

### ISSUE THREAD

**Issue by rajpradi** [mfem/mfem#702]
Hello,

I am unable to run periodic meshes in linear elasticity example (ex2). Can anyone please help me how to use linear elasticity example (ex2) for periodic meshes?

**Comment by mlstowell** [comment]
Hello, @rajpradi ,

Example 2 has rather particular requirements for its mesh, see the comments at the top of the file.  Does your periodic mesh meet these requirements?

Best wishes,
Mark

**Comment by tzanio** [comment]
Periodicity doesn't really make sense for this problem, see Example 9 for a problem where it does.

**Comment by rajpradi** [comment]
Thank you so much for your response, it really helps me to understand.

Sincerely,
Raj Khawale
