### ISSUE TITLE
Does mfem support refine a seperare cell with a tag .

### ISSUE THREAD

**Issue by ztdepztdep** [mfem/mfem#705]
Dear sir:
      ThresholdRefiner use the error estimator to refine the mesh. I want to refine some cell which is tagged by some user defined indicator. How to obtain this goal.
   Regards

**Comment by v-dobrev** [comment]
The class `ThresholdRefiner` defines an array of marked elements and calls `Mesh::GeneralRefinement`. You can create your own array of marked elements and then call `Mesh::GeneralRefinement` directly.

**Comment by ztdepztdep** [comment]
thank you. I will have a try.

**Comment by ztdepztdep** [comment]
I met "segmentation fault " error.  I have declared a marked_elements in my code, The following is my code. 
`    Array<Refinement> marked_elements(Ncell);
    for (int l = 0; l <Ncell; l++)
      marked_elements[l]=(l,'111');
    mesh->GeneralRefinement(marked_elements);`
  
  I do not know how to find the error.  But the error should be located in the "  mesh->GeneralRefinement(marked_elements);". If i comment is out, the code can run smoothly.
regards

**Comment by jakubcerveny** [comment]
The problem is most likely the statement `marked_elements[l]=(l,'111');` (does that actually compile?) You should do `marked_elements[l] = Refinement(l, 7);` Better yet, you can use the simpler interface that takes an `Array<int>`, which is a simple list of indices of elements to refine.

**Comment by ztdepztdep** [comment]
Thanks, I have generated my first adaptive refined-mesh successfully. I have been tried several packages:SAMRAI, BOXLIB, AMREX,P4est, and finally, i have got my favorite one MFEM.  LOL. 
   This is my first step toward my adaptive-FVM code for the solidification problems based on the phase-field method.

**Comment by ztdepztdep** [comment]
By the way, if my geometries have curved boundary, will the refinement process take care of it. or just put a point in the middle of two neighboring points.

**Comment by jakubcerveny** [comment]
Curved meshes are handled correctly (see e.g. the MFEM logo).

**Comment by ztdepztdep** [comment]
thanks, i will collect the mesh info for my FVM computation.

**Comment by jakubcerveny** [comment]
Derefinement is more tricky and requires some kind of per-element error estimate. You can use the class `ThresholdDerefiner` or the more low-level function `Mesh::DerefineByError`. The latter derefines groups of elements whose sum of errors is less than the given threshold.

**Comment by ztdepztdep** [comment]
I have tried several meshes. It seems that the Mesh::DerefineByError only support the non-conforming tri-meshes. How to derefine it with a conforming tri-mess.

**Comment by v-dobrev** [comment]
At the moment, only meshes that were refined using nonconforming refinement can be derefined.

**Comment by ztdepztdep** [comment]
Thanks . In the mesh file, there is 
coarse_elements
4
3 6 7 8 9
3 19 20 21 22
3 27 28 29 30
3 36 37 38 39

Could you please tell me what is the meaning. is it the father cell?

**Comment by v-dobrev** [comment]
These are the coarse elements that are now refined. Each row contains the refinement type and the indices of the children elements.

**Comment by ztdepztdep** [comment]
Does MFEM provide the info about the refinement history, the relationship between the cell at the refined mesh and its father level.

**Comment by v-dobrev** [comment]
This type of information is stored inside the class `NCMesh`, see e.g. `NCMesh::Element::parent`:
https://github.com/mfem/mfem/blob/4987e1132a8232c2aecc195d9e535bfc83f68f6e/mesh/ncmesh.hpp#L396

A convenient way to access this type of information is to use `NCMesh::GetDerefinementTable()`.

**Comment by ztdepztdep** [comment]
I am conducting conforming mesh refinement with ParMesh, how to get the  the relationship between the cell at the refined mesh and its father level.
 NCMesh::GetDerefinementTable()  is only work for NCMesh.
Regards

**Comment by jakubcerveny** [comment]
You might want to take a look at `Mesh::GetRefinementTransforms` and the struct `CoarseFineTransformations`. Each fine element knows the index of the `parent` element in the old mesh, plus a sub-element transformation (`matrix`).
