### ISSUE TITLE
zero displacement(fixed B.C.)  in only one direction in example 2 (MFEM).

### ISSUE THREAD

**Issue by rajpradi** [mfem/mfem#706]
Hello,
I am facing a problem while fixing one co-ordinate and reamaining other two co-ordinates free. For Example I have tried to make zero displacement in X -cordinates and movements in Y and Z co-ordinates, but I am unable to make that happen. Linear elascticity example (Ex2) demonstrate about fixing the vertex/faces in all co-ordinates not for perticular co-ordinate.  
Can any one please help me to solve my doubt? 
Thank you.

**Comment by jakubcerveny** [comment]
Please see this issue: #683
