### ISSUE TITLE
Non-zero Neumann boundary conditions on part of the boundary

### ISSUE THREAD

**Issue by pratyuksh** [mfem/mfem#708]
Hello

Consider a unit square domain [0,1]^2. At the bottom and top boundaries of the domain, I want to impose non-zero Neumann boundary conditions and zero Dirichlet conditions otherwise. 

I tried to do this as follows:
1) Add boundary attributes in the mesh file.
2) Then in the _LinearForm_, I use AddBdrFaceIntegrator(new NeumannBcIntegrator(u_exact), neumann_bdr_attrib_marker). Here NeumannBcIntegrator is similar to BoundaryNormalLFIntegrator, I had to create the new class because the following function of BoundaryNormalLFIntegrator,  class is not defined:
AssembleRHSElementVect (const FiniteElement &el, FaceElementTransformations &Tr, Vector &elvect)
( I defined this function for my custom class by re-cycling what is given for the BoundaryFlowIntegrator class. )

However, I think I am missing some detail as I do not get the correct result.

Please let me know if there is a smarter way to implement the boundary conditions as such.

**Comment by tzanio** [comment]
Can you provide more details about your discretization? Is it discontinuous Galerkin, H(div)/Raviart-Thomas or something else?

For simple Laplacian discretization with continuous Lagrange elements, non-zero Neumann conditions are imposed with `AddBoundaryIntegrator(new BoundaryLFIntegrator(g))` where du/dn = -g.

**Comment by pratyuksh** [comment]
It is for the Laplace discretization with continuous Lagrange elements. I want to impose non-zero Neumann boundary conditions only on a part of the boundary. I think AddBoundaryIntegrator(new BoundaryLFIntegrator(g)) imposes conditions for the whole boundary, without being selective about the boundary attribute?

**Comment by tzanio** [comment]
@pratyuksh, were you able to resolve this?

**Comment by pratyuksh** [comment]
@tzanio Sorry, I was away for holidays and could not look at it. I will work on it next week. Thanks!

**Comment by pratyuksh** [comment]
@tzanio I was able to get this working, it required adding AddBoundaryIntegrator(new BoundaryLFIntegrator(g), bdr_attr_marker) to the mfem 3.4 release version.

**Comment by tzanio** [comment]
Thanks for the update @pratyuksh.

This function will be available in the next release. (You can also use the master branch between releases -- we test it to make sure it is of release quality).

Tzanio
