### ISSUE TITLE
Vector boundary mass integrator

### ISSUE THREAD

**Issue by e-aranda** [mfem/mfem#709]
I'm trying to implement a spring condition on a boundary for an elasticity problem, which is a Robin boundary condition of the form $M\vec{u} + \sigma(u)\cdot \vec{n} = 0$ resulting in a expression like
$\int_{\partial \Omega} M\vec{u}\cdot{v}$ in the variational formulation. Here $M$ is a SPD matrix.So, I need a BoundaryMassIntegrator for vector functions. Is it implemented in MFEM? How could I implement myself?

**Comment by tzanio** [comment]
You should be able to use simply `AddBoundaryIntegrator(new VectorMassIntegrator(...));`

**Comment by e-aranda** [comment]
Thank you @tzanio, it works well.

**Comment by tzanio** [comment]
Glad to hear that Ernesto. Please don't hesitate to let us know if you need help with anything else.
