### ISSUE TITLE
Boundary integration of VectorGridFunctionCoefficient 

### ISSUE THREAD

**Issue by MC3JMF** [mfem/mfem#710]
Dear MFEM community, 

I have the following question about the usage of VectorBoundaryLFIntegrator with a VectorGridFunctionCoefficient. I'd like to perform an integration of the form:

![untitled](https://user-images.githubusercontent.com/35522233/50479882-241dd980-09d9-11e9-9759-0ef59db0f4fa.png)

in part of the boundary $\partial D_1$. 

I have created a GridFunction in a vectorized finite element space with the values of (x-xt). Using such a GridFunction I have created a VectorGridFunctionCoefficient which I'd like to integate in one part of the boundary (e.g. bdr attribute 3). After reviewing previous issues, I decided to do that using a linear form:

```c++
   H1_FECollection FE_coll(1, 3); // H1 Finite Elements 
   FiniteElementSpace u_space(_mesh, &FE_coll, 3, Ordering::byVDIM);
   ...
   subtract(x , xt  xxt);
   VectorGridFunctionCoefficient c_xxt(&xxt);  
   LinearForm *_L = new LinearForm(&u_space); 
   Array<int> bdr_attr_marker(_mesh->bdr_attributes.Max());
   bdr_attr_marker[2]=1;
   _L->AddBoundaryIntegrator(new VectorBoundaryLFIntegrator(c_xxt));
   _L->Assemble();
```

The result obtained is not what I expected and I wonder if I am using the VectorBoundaryLFIntegrator in a correct form. More precisely, can I use the VectorBoundaryLFIntegrator with a VectorGridFunctionCoefficient? 

Thank you very much in advance!!!

**Comment by tzanio** [comment]
This is all correct, except the integral is performed over the whole boundary.

To restrict the integral to boundary attribute 3, use the new `AddBoundaryIntegrator` method of `LinearForm`: https://github.com/mfem/mfem/blob/master/fem/linearform.hpp#L108-L114.

**Comment by MC3JMF** [comment]
Tzanio, thanks, it works.
