### ISSUE TITLE
Apply gravity force 

### ISSUE THREAD

**Issue by rajpradi** [mfem/mfem#711]
Hello,

First of all, thank you for creating this well structured MFEM software. I am new to this and currently, I am working on linear elasticity example (example 2). In that, I am unable to apply gravity force on specific nodal points/faces? 
Can anyone please help me how can I apply gravity force as a boundary condition?

Thank you very much.

**Comment by tzanio** [comment]
If I understand correctly, you are asking about specifying a volume, not surface force? This could be done by adding a `DomainIntegrator` term to the right-hand side, e.g.

```c++
   VectorFunction VectorArrayCoefficient g(dim);
   for (int i = 0; i < dim-1; i++)
   {
      g.Set(i, new ConstantCoefficient(0.0));
   }
   g.Set(dim-1, new ConstantCoefficient(-1.0)); // or defined as necessary...
   b->AddDomainIntegrator(new VectorDomainLFIntegrator(g));
```
