### ISSUE TITLE
Possible error in PCG Solver

### ISSUE THREAD

**Issue by rcarson3** [mfem/mfem#725]
During some of my testing with a simple linear elastic problem with just 1 hexagonal element using the ExaConstit miniapp, I've found some issues with the PCG solver. 

I've included some outputs from my simulations. The first iteration doesn't run, but the second iteration does even though nothing has changed. The large value for the initial value for the initial value of (Br, r) leads me to believe something isn't getting initialized during that first run.

```
Newton iteration  0 : ||r|| = 407.946
   Iteration :   0  (B r, r) = -3.30482e+07
Newton iteration  1 : ||r|| = 407.946, ||r||/||r_0|| = 1
   Iteration :   0  (B r, r) = 2.93489
   Iteration :   1  (B r, r) = 0.0601064
   Iteration :   2  (B r, r) = 9.77057e-05
   Iteration :   3  (B r, r) = 1.21833e-07
   Iteration :   4  (B r, r) = 2.63079e-10
   Iteration :   5  (B r, r) = 2.84511e-13
   Iteration :   6  (B r, r) = 5.36044e-15
   Iteration :   7  (B r, r) = 2.17134e-29
```

I've done a few test cases, and I haven't run into this issue by increasing the total numbers of elements. Although, I've only done a few basic tests up to 64 elements total. 

I've taken a bit of a further look at the CG solver code, and I'm curious about the use of using (Br, r) as the convergence criterion for the PCG code. I've traditionally seen it as L2 norm of r in most sources such as Ch. 11 Sec. 5 of van Loans Matrix Computations 4th ed. book.

**Comment by tzanio** [comment]
The norm `||r||_B = sqrt((Br, r))` is know as the *preconditioner norm*  and from theoretical standpoint is the most natural norm to measure the residual in PCG.

That norm assumes that B is symmetric and positive definite, which for AMG should be the case if the original matrix is symmetric and positive definite and a convergent symmetric smoother (e.g. l1-GS) is used on all levels.

The fact that you get negative residual on the first iteration means that something is wrong.

Is the original matrix symmetric and positive definite? 

If not, you should use GMRES, not CG. If yes, can you point to the code that defines `B`?

**Comment by tzanio** [comment]
Forgot to mention that *hypre*'s PCG implementation does support measuring the convergence in l2 norm, which is useful when comparing different preconditioners. In MFEM this is available via `HyprePCG::SetResidualConvergenceOptions`.

**Comment by rcarson3** [comment]
Since it's a simple linear elastic problem, the matrix is symmetric and positive definite. I'm currently using a UMAT for the linear elastic portion, so the material tangent stiffness matrix that is used to define B can be found here: [https://web.njit.edu/~sac3/Software.html](https://web.njit.edu/~sac3/Software.html) under the linear elastic UMAT. The matrix is defined on lines: [https://github.com/rcarson3/mfem/blob/exaconstit-dev/miniapps/exaconstit/mechanics_integrators.cpp#L1701-L1778](https://github.com/rcarson3/mfem/blob/exaconstit-dev/miniapps/exaconstit/mechanics_integrators.cpp#L1701-L1778).

As I mentioned in the 1st post, the PCG is getting fed exactly the same data in the next newton iteration and is working which to me is rather odd.

**Comment by tzanio** [comment]
Ok, I'll take a look at the assembly. Can you also point me out to the lines constructing the preconditioner `B`?

I see two other potential issues: 1) the initial guess may differ between the two calls -- that doesn't explain why B is not positive definite, but it could explain the different behavior; 2) if you have boundary conditions everywhere, the one element case may have no free degrees of freedom

**Comment by rcarson3** [comment]
You can find the preconditioner construction here: [https://github.com/rcarson3/mfem/blob/exaconstit-dev/miniapps/exaconstit/mechanics_driver.cpp#L1100-L1126](https://github.com/rcarson3/mfem/blob/exaconstit-dev/miniapps/exaconstit/mechanics_driver.cpp#L1100-L1126). I borrowed these settings from another code base that runs crystal plasticity type problems and is using Hypre. 

I'm applying symmetry boundary conditions which means I'm only enforcing a zero boundary condition normal to the interior face, and then an applied boundary condition normal to the top surface. All of the other DOFs are free to move. 

Also, I've printed out the solution vector before assembly, and it appears they are the same between the two. It's one of the reasons it seems to me that something might not be initialized initially. However, I'm just not sure where, and it doesn't seem like using GCC's AddressSanitizer is picking up on the use of an uninitialized memory type error. 

The interesting thing is after that first iteration it converges to the same solution you get from using GMRES or if you use a more refined mesh with a PCG solver which doesn't suffer from this issue.

**Comment by tzanio** [comment]
Can you try disabling the calls to `HYPRE_BoomerAMGSetRelaxWt` and `HYPRE_BoomerAMGSetOuterWt` and using `HYPRE_BoomerAMGSetRelaxType(h_amg, 8);`?

**Comment by rcarson3** [comment]
Thanks, it seems like that made the difference. 

Although, I'm still curious why the other method wasn't working on the first iteration but worked on the second when in both cases they were provided the exact same ```Ax = b```.

**Comment by tzanio** [comment]
Likely the smoother was not convergent and the two iterations must have started with different initial guesses. (Even if the difference was at round-off error.)

To check what caused the lack of convergence in the smoother, you can try disabling `HYPRE_BoomerAMGSetRelaxWt` and `HYPRE_BoomerAMGSetOuterWt` with `HYPRE_BoomerAMGSetRelaxType(h_amg, 6)` and vice versa.
