### ISSUE TITLE
How to compute a gradient without neighbouring averaging

### ISSUE THREAD

**Issue by pmguilcher** [mfem/mfem#733]
Hello,

From a FE solution, I would like to compute a gradient of the solution on each element, to compare to an analytical solution;
-on the nodes
-at the middle of the edges along a boundary

For the time being, I've used the GetVectorGradient function to evaluate the gradient on the nodes. Since there is only one estimated value per node, I understand that it is an average value which takes into account all the elements shared by this node. For a standard Galerkin formulation, the gradient continuity is not handled between elements, so this averaging procedure is a kind of post-processing, and does not correspond to the 'rough' value.
Is it possible to obtain a gradient value, either on the nodes or the edges of an element, that is specific to this element?

Thank you if you could answer my question.
Pierre

**Comment by tzanio** [comment]
You can use the `GetGradient` method of the `GridFunction` class:

https://github.com/mfem/mfem/blob/e17a73fa8be9242262121bcbbc973e9da59f8354/fem/gridfunc.cpp#L992-L1008

For example something like the following on a quad mesh:

```c++
for (int elem = 0; elem < mesh->GetNE(); elem++)
{
   ElementTransformation *Tr = fes->GetElementTransformation(elem);
   const IntegrationPoint &ip;
   Vector grad;

   ip.Set3(0.5, 0.5, 0.5); // element center
   Tr->SetIntPoint(&ip);
   x.GerGradient(Tr, grad);
   // work with grad...

   ip.Set3(0.5, 0.0, 0.0); // (0,0,0)-(1,0,0) edge center
   Tr->SetIntPoint(&ip);
   x.GerGradient(Tr, grad);
   // work with grad...

   // ...
}
```

**Comment by v-dobrev** [comment]
To add to @tzanio's answer: in general, the center and vertices of any reference element can be accessed using something like this:
```c++
   // Get the ElementTransformation pointer Tr
   // ...

   Geometry::Type geom = Tr->GetGeometryType();
   const IntegrationPoint &center = Geometries.GetCenter(geom);
   // use center

   const IntegrationRule &vert_ir = *Geometries.GetVertices(geom);
   for (int vi = 0; vi < vert_ir.GetNPoints(); vi++)
   {
      const IntegrationPoint &vert = vert_ir.IntPoint(vi);
      // use vert
   }
```

**Comment by pmguilcher** [comment]
Hello,

Thank you so much for your answer, I will try this solution and give you some feedback.
I used the the .ProjectCoefficient method for a GridFunction class, which was maybe wrong.

Pierre

**Comment by pmguilcher** [comment]
It works very well: I checked with an analytical solution, and your proposition gives the right estimation for the gradient on the element.
