### ISSUE TITLE
Working with a Vector L2 Finite Element Space

### ISSUE THREAD

**Issue by pratyuksh** [mfem/mfem#738]
Hello,

I am trying to the implement the DG formulation for the acoustic wave equation in 2D, wherein we have a scalar variable and a vector (of size 2, same as physical space dimension) variable. For the scalar variable it is clear how to build the finiteElementSpace. For the vector variable, I do the following:

fec = new L2_FECollection(deg, ndim);
sfes = new ParFiniteElementSpace(&pmesh, m_fec);
vfes = new ParFiniteElementSpace(&pmesh, m_fec, ndim, Ordering::byVDIM);

Next, I follow the example "ex5p" and try to assemble the VectorFEMassIntegrator. It does not work, it gives the error that function _CalcVShape_ is not implemented. I understand that this function is a member of the class VectorFiniteElement and the manner I have built "vfes", this function is not available. Similar issue for VectorFEDivergenceIntegrator with _CalcDivShape_.

One way I can think of fixing this is to create a new type of VectorFiniteElement and add all the relevant routines. But this seems not so elegant. Is there a smarter way of fixing this issue? Thanks for the help.

**Comment by mlstowell** [comment]
Hello, @pratyuksh,

The "VectorFE" prefix on these integrator names refers to the H(Curl) and H(Div) basis functions which have vector-valued basis functions.  Using the L2 basis functions in this manner creates a vector of scalar-valued basis functions.  To build your mass matrix you should use the VectorMassIntegrator which is specifically designed for this use case.  There is also a VectorDivergenceIntegrator if you need this.

Best wishes,
Mark

**Comment by pratyuksh** [comment]
@mlstowell Thanks, I should have looked at the documentation more closely.
