### ISSUE TITLE
Point Load 

### ISSUE THREAD

**Issue by rajpradi** [mfem/mfem#740]
Hello Sir,
How can we apply point load on hexahedral mesh. I have tried to implement "0" in the second column of boundary and also arranged it in required manner. But, I am unable to visualize it's geometry in GLVis and perform ex2.
Would please suggest me how can I apply point load in linear elasticity model?
I am adding the mesh file, where have I tried to consider point in boundary section for beam-hex.mesh. Please look into it.
Thank you very much.
```txt
# POINT       = 0
# SEGMENT     = 1
# TRIANGLE    = 2
# SQUARE      = 3
# TETRAHEDRON = 4
# CUBE        = 5
dimension
3
elements
8
1 5 0 1 10 9 18 19 28 27
1 5 1 2 11 10 19 20 29 28
1 5 2 3 12 11 20 21 30 29
1 5 3 4 13 12 21 22 31 30
2 5 4 5 14 13 22 23 32 31
2 5 5 6 15 14 23 24 33 32
2 5 6 7 16 15 24 25 34 33
2 5 7 8 17 16 25 26 35 34

boundary
36
1 0 0
3 0 9
3 0 18
3 0 27 
3 0 1 
3 0 10 
3 0 19 
3 0 28
3 0 2 
3 0 11
3 0 20
3 0 29
3 0 3
3 0 12
3 0 21
3 0 30
3 0 4
3 0 13
3 0 22
3 0 31
3 0 5
3 0 14
3 0 23
3 0 32
3 0 6
3 0 15
3 0 24
3 0 33
3 0 7
2 0 16
3 0 25
3 0 34
3 0 8
3 0 17
3 0 26
3 0 35

vertices
36
3
0 0 0
1 0 0
2 0 0
3 0 0
4 0 0
5 0 0
6 0 0
7 0 0
8 0 0
0 1 0
1 1 0
2 1 0
3 1 0
4 1 0
5 1 0
6 1 0
7 1 0
8 1 0
0 0 1
1 0 1
2 0 1
3 0 1
4 0 1
5 0 1
6 0 1
7 0 1
8 0 1
0 1 1
1 1 1
2 1 1
3 1 1
4 1 1
5 1 1
6 1 1
7 1 1
8 1 1
```

**Comment by tzanio** [comment]
Hi @rajpradi, this is an invalid mesh, which appears to be derived from the `beam-hex.mesh` file.

The boundary conditions in MFEM are implemented in the source code, not the mesh. 

Do I understand correctly that you want to apply an elasticity Dirichlet (essential) boundary conditions in a single degree of freedom? If yes, how do you identify that degree of freedom (by its coordinates?)

**Comment by tzanio** [comment]
Hi @rajpradi, were you able to resolve this issue?

**Comment by nghiakvnvsd** [comment]
> Hi @rajpradi, this is an invalid mesh, which appears to be derived from the `beam-hex.mesh` file.
> 
> The boundary conditions in MFEM are implemented in the source code, not the mesh.
> 
> Do I understand correctly that you want to apply an elasticity Dirichlet (essential) boundary conditions in a single degree of freedom? If yes, how do you identify that degree of freedom (by its coordinates?)

Hi @tzanio , I have a same case when I resolve my problem. Do I understand correctly that you want to apply an elasticity Dirichlet (essential) boundary conditions in a single degree of freedom? If yes, how do you identify that degree of freedom (by its coordinates?) this is correctly my question. May you recomend me a solution for it? Thank you very much!!!
