### ISSUE TITLE
How to set create a mesh by hand in mfem?

### ISSUE THREAD

**Issue by ztdepztdep** [mfem/mfem#745]
Dear sir: 
    I want to create a 2-D mesh manually. For example:
    First, I set the coordinates of several vertices, then i create triangles by specifying its three nodes.
    Does mfem support this capability?
Regards

**Comment by vikramsg** [comment]
You can create a mesh this way in GMSH. MFEM reads meshes generated in GMSH.

**Comment by kennyweiss** [comment]
@ztdepztdep -- Is this what you had in mind?

https://github.com/mfem/mfem/blob/b74e81edc3c960749072b6be055187e21124c91b/test/unit-test.code/fem/test_linear_fes.cpp#L399-L413

**Comment by v-dobrev** [comment]
You can also take a look at example 7 which creates a surface mesh (for the unit sphere) on the fly.

**Comment by tzanio** [comment]
See also these past issues: https://github.com/mfem/mfem/issues/677, https://github.com/mfem/mfem/issues/466
