### ISSUE TITLE
Create a GridFunction from values on a mesh

### ISSUE THREAD

**Issue by S-Villar** [mfem/mfem#746]
Dear all,

I have a series coefficients (`Coefficient`, `VectorCoefficient`, `MatrixCoefficient`, etc) and Integrators (`VectorFEDomainLFIntegrator`) that use function coeficients (`FunctionCoefficient`,`VectorFunctionCoefficient`, `MatrixFunctionCoefficient`) that I have defined using analytical functions of position e.g.  using the constructor  `mfem::MatrixFunctionCoefficient::MatrixFunctionCoefficient(int dim, void(*F)(const Vector &, DenseMatrix &),Coefficient *q=NULL)`. 

Now similarly to what it is depicted in #143, instead of defining the functions analytically for the properties used in this function `F`, I would like to read my properties and maps from input files prepared to be evaluated (interpolated) accordingly by my coefficients and integrators.

For instance for the case of the integrator for the linear form in the rhs of my equation where I use `VectorFunctionCoefficient`, I found a hint to how to do this, as I have understood from @mlstowell first comment in #648 :

> If `JFunc` cannot be written then you may need to use a `VectorGridFunctionCoefficient` instead (assuming you have a `GridFunction` representation of `J`.)

I understand that I could use for instance for the  a `GridFunction` representing a source term (in my case also a  current density `J_gf`) and create a `VectorGridFunctionCoefficent` and use it in my integrator as:
```
VectorCoefficient J_vgf = new VectorGridFunctionCoefficient(J_gf);
LinearForm J(fes);
J.AddDomainIntegrator(new VectorFEDomainLFIntegrator(J_vgf));
J.Assemble;
```
Do you see any mistake in this approach? If it was correct, I would like to know how to create such `GridFunctions` from values of properties and quantities given for instance at each of the nodes of the mesh. In case it is incorrect, do you have any hint that could help me solve this issue?

I apologize for the long post.
Thank you in advance!
Best,

Alvaro

**Comment by vladotomov** [comment]
Hi Alvaro,

The approach seems correct.

There are different ways to create a `GridFunction,` but the easiest is to use a `Coefficient`. See `GridFunction::ProjectCoefficient`. Since you mentioned input files, you can, for example, have a function that interpolates the input file values at each point in space, then create a `FunctionCoefficient` using that function, and then project it to a `GridFunction.`

Note that you can use directly the `FunctionCoefficient` that interpolates the file. But going through a `GridFunction,` as above, will avoid the file lookup every time you need the values. There are other ways to avoid that, like storing the file values in memory. I would probably do that.

Note that if the mesh moves during the simulation, the `GridFunction` approach might be incorrect.

Vladimir

**Comment by v-dobrev** [comment]
Hi Alvaro,

If I understand you correctly, you have vertex/nodal values in your input file. In that case you can create a linear continuous `GridFunction` which corresponds exactly to the data you have - the ordering of the values is the same as the ordering of the mesh vertices.

To create a linear continuous `GridFunction` use something like this:
```c++
   Mesh *mesh = new Mesh(mesh_file, 1, 1);
   int dim = mesh->Dimension();
   H1_FECollection lin_fec(1, dim);
   FiniteElementSpace lin_fes(mesh, &lin_fec);
   GridFunction lin_gf(&lin_fes);
   // Read data from file, e.g. using lin_gf.Load()
   GridFunctionCoefficient lin_coef(&lin_gf);
   // Use 'lin_coef' ...
```

Hope this helps,
Veselin

**Comment by S-Villar** [comment]
Hello @vladotomov and @v-dobrev ,

Thank you very much for the quick reply. The first approach suggested by @vladotomov of creating my own interpolating function was the my first thought but as he mentions I see this approach rather inefficient. I was looking for an alternative approach using the functionalities of mfem or some derived classes of my own. I'd rather have a file with the data so that I can load once and then use this object to access the values, for instance, similar to what @v-dobrev suggested. Thanks for the example @v-dobrev. 

However I think the finite element space for this GridFunction should be the same as the one used to construct the LinearForm meaning:

```
Mesh *mesh = new Mesh(mesh_file, 1, 1);
int dim = mesh->Dimension();

FiniteElementCollection *fec_nd = new ND_FECollection(2, dim);
FiniteElementSpace *fes =  new FiniteElementSpace(mesh, fec_nd);

H1_FECollection lin_fec(1, dim);
FiniteElementSpace lin_fes(mesh, &lin_fec);
GridFunction lin_gf(&lin_fes);  
lin_gf.Load(ifstream_lin_gf,lin_gf.Size(),dim);// Not sure about the last dim
GridVectorFunctionCoefficient lin_coef(&lin_gf);
VectorCoefficient J_vgf = new VectorGridFunctionCoefficient(J_gf);

LinearForm J(fes);
J.AddDomainIntegrator(new VectorFEDomainLFIntegrator(J_vgf)); // This is what I mean. 
//Above here J belongs to fes (ND vdim 2) and J_vgf to lin_fes(H1).
// Maybe I need to go from one fespace to another. 
J.Assemble;

```
Appart from these linear forms I do have coefficients that enter in my bilinear integrators as functions and now I'd rather substitute by inputs. I thought the use of gridfunction could be applicable to this but I have not figured out how.

Thanks in advance again,
Best,

Alvaro

**Comment by v-dobrev** [comment]
Hi Alvaro,

In the example I gave, I assumed that your data in the file describes a scalar field, i.e. one value per mesh vertex. It looks like you actually have vector field with 2 (or 3) values per mesh vertex - is that the case?

If that is the case, my example above can be modified as follows:
```c++
   Mesh *mesh = new Mesh(mesh_file, 1, 1);
   int dim = mesh->Dimension();
   H1_FECollection lin_fec(1, dim);
   FiniteElementSpace lin_fes(mesh, &lin_fec, dim, Ordering::byNODES);
   GridFunction lin_gf(&lin_fes);
   lin_gf.Load(ifstream_lin_gf, lin_gf.Size());
   VectorGridFunctionCoefficient lin_coef(&lin_gf);
   // Use 'lin_coef' ...
```
The meaning of the `Ordering::byNODES` parameter (which you may need to switch to `Ordering::byVDIM` depending on your file input) is explained here:
https://github.com/mfem/mfem/blob/3e9a86cecfd422027da0f44c671cf2c630206074/fem/fespace.hpp#L24-L38

On the other hand, if your file was written by MFEM (using `GridFunction::Save`) you can load that file using:
```c++
   GridFunction my_gf(mesh, ifstream_my_gf);
   VectorGridFunctionCoefficient my_coef(&my_gf);
   // Use 'my_coef' ...
```

If none of the above covers your needs, can explain what the contents of your data file is?

Regards,
Veselin

**Comment by S-Villar** [comment]
Hello @v-dobrev ,

Thank you for your kindly replies. I apologize for the confusion. I think I did not explain myself properly in the first message and probably my question comprised two or more questions.

1. Loading of inputs I think its solved and its working as expected. Vesselin I had already loaded using    `GridFunction my_gf(mesh, ifstream_my_gf)` but I didnt know how to create my own files. Now I do, thanks a lot. The main issues were how to choose the FiniteElementSpace and the Ordering. Indeed I had both scalar and vector input files. Scalar (1dim) `Vector`s  for some 2D properites of a scalar and  vectors in 2D for the currents. 

2. Regarding the use of these loaded GridFunctions, with your example yesterday I used  VectorGridFunctionCoefficient properly with this input GridFunction (of vector dim ==2 )  and works. I am not sure if it is applied correctly (lines below) doing the integration of GridFunction expressed at a nodal basis (H1_Col) of dimension 2 to create `LinearForm` on a different `FiniteElementSpace` (ND_Col order 2). 
```
        Mesh *mesh = new Mesh(mesh_file, 1, 1);
	int dim = mesh->Dimension();
	
        FiniteElementCollection *nd_fec = new ND_FECollection(2, dim);
        // FES1 based on order 2,  vector (dim) ND elements. 
	FiniteElementSpace *fes =  new FiniteElementSpace(mesh, nd_fec); 
	H1_FECollection lin_fec(1, dim);
        // FES2 based on order 1,  nodal (dim) elements.
	FiniteElementSpace lin_v_fes(mesh, &lin_fec, dim,Ordering::byNODES);
	GridFunction j_gf(&lin_v_fes);
	j_gf.Load(ifstream_jin_gf,j_gf.Size());
	VectorCoefficient * J_vgf;
	J_vgf = new VectorGridFunctionCoefficient(&j_gf);
	LinearForm J(fes);
	//Below here J's FiniteElementSpace is fes (based on ND_FECollection vdim 2)
	// 		and J_vgf's FiniteElementSpace lin_fes (based on H1_FECollection).
	J.AddDomainIntegrator(new VectorFEDomainLFIntegrator(*J_vgf)); // Is J built correctly?
```

However, some **coefficients** I use are for instance of MatrixCoefficients and all depend on nested C functions of `Vector & x` which depend eventually in analytical functions of `Vector & x` for that parameter.

```
double density(const Vector &x){
		return x(0)*x(1);
		}
void mat_fc(const Vector &x, DenseMatrix &DM)
		{
			DM.Elem(0,0) =-density(x)/6;
			DM.Elem(0,1) =-density(x)/x(0);
			DM.Elem(1,0) =-density(x)/2;
			DM.Elem(1,1) =-x(1)*density(x);
		}
int main(int argc,char *argv[]){
...
MatrixCoefficient  * m_coeff =new MatrixFunctionCoefficient(2,mat_fc);
Bilinear * AA(new BilinearForm(fes);
		AA->AddDomainIntegrator(new VectorFEMassIntegrator(m_coeff));
...
}
```

Now I have `density(x)` loaded in a `GridFunction` as
```
   Mesh *mesh = new Mesh(mesh_file, 1, 1);
   int dim = mesh->Dimension();
   H1_FECollection lin_fec(1, dim);
   FiniteElementSpace lin_fes(mesh, &lin_fec);
   GridFunction density_lin_gf(&lin_fes);
```
How can I use this `density_lin_gf` the data inside a `MatrixFunctionCoefficient`? 

 Thank you so much again and I apologize for the incovenience of my questions.

Best,
Alvaro

**Comment by v-dobrev** [comment]
Hi Alvaro,

Regarding you question about using `J_vgf` in the definition of `J`: I think it should work correctly, even though the spaces used by `J_vgf` and `J` are different.

One remark about your `mat_fc` function - it is better to use `DM(0,0) = ...` instead of `DM.Elem(0,0) = ...` because the `Elem` method is actually a virtual call which is slower.

Regarding your question about using `density_lin_gf` inside a `MatrixFunctionCoefficient`: from your code above it looks like you need the scalar coefficient `density_lin_gf` to simply multiply analytically given matrix function - if that is the case, you can remove the density from `mat_fc` and add `&density_lin_gf` as the third (optional) parameter in the constructor of `MatrixFunctionCoefficient`. This form creates a matrix coefficient that is the product of the given matrix function with the given scalar coefficient (=1 with the default third parameter, `NULL`).

**Comment by S-Villar** [comment]
Hello Veselin,

Thanks a lot for your kindly reply and for the two first comments. 

Regarding the use of `density_lin_gf`, I just gave a simplified example cause my function is a combination of nested C functions that end up depending in parameters as `density_lin_gf`. I did not know that option you give, but the fact is that it could work for the example but not for my real case. My case is not a simple multiplication matrix to coefficient multiplication. In fact there is a combination of various of those parameters. In total my `MatrixFunc tionCoefficient` depends on four different coefficients given as the example `density_lin_gf`.  Before they were C functions so it made it straightforward to evaluate doubles as functions of `Vector & x` as they were described analytically. But now with these functions have to use GridFunctions and evaluate, maybe with method I don't know GridFunction::Eval. I am not sure hiw ti do this and I am looking in the right direction. 

Furthermore the GridFunctions are not used as a matrix to coeff multiplication. Instead a series of C functions are used to make multiple algebraic operations that make every element of `D(i, j)` differently. 

Thank you again so much for your hints and helpful comments.

Best
Alvaro

**Comment by S-Villar** [comment]
Hello @v-dobrev ,

I have seen issue #143, specifically in first reply by @mlstowell, suggests creating my own customized class derived from Coefficient. For instance I am thinking of generating my own MatrixCoefficient derived class called myMatrixFunctionCoefficient as
```
#ifndef MYMATRIXCOEFFICIENT_H_
#define MYMATRIXCOEFFICIENT_H_
#include <fem/coefficient.hpp>
namespace mfem {
class MyMatrixCoefficient: public MatrixCoefficient
{
private:
	void(*Function)(const Vector &, DenseMatrix &, double []);
	Coefficient * Parameters[];
public:
	//Construct a time-independent square matrix coefficient from a set of doubles in an array.
	MyMatrixCoefficient(int dim, void(*F)(const Vector &, DenseMatrix &, double []), Coefficient *p[])
		: MatrixCoefficient(dim)
{
		Function = F;
		Parameters = p;
}
	virtual void Eval(DenseMatrix &K, ElementTransformation &T,const IntegrationPoint &ip);
	virtual ~MyMatrixCoefficient() {};
};
} /* namespace mfem */
#endif /* MYMATRIXCOEFFICIENT_H_ */
```
with eval function that uses an array of pointers to coefficient objects of the form:
`	Coefficient * Density = new GridFunctionCoefficient(density_lin_gf);
`
Then this eval method would use method `GridFunctionCoefficient::Eval` to construct an array of doubles to use function `Function` as : 
```
void MyMatrixFunctionCoefficient::Eval(DenseMatrix &K, ElementTransformation &T,const IntegrationPoint &ip)
{
	size_t n = sizeof(p) / sizeof(Coefficient *);
	double x[3], par[n];
	Vector transip(x,3);
	T.Transform(ip,transip);
	K.SetSize(height,width);
...
par[0] = Density->Eval(T,ip);
... // Eval all coefficients and assign to par GridFunctions at the integration point
	if (Function)
	{
		(*Function)(transip, K, par);
	}
```
Do you think this approach could work? Isn't there a functionality to load these input parameters already in MFEM? 
An alternative to this would be a way to access both `ElementTransformation &T, const IntegrationPoint &ip` to evaluate this GridFunctionCoefficients (that I could set in global scope) from inside the functions  for instance, void(*F)(const Vector &, Dense &) defined in the constructor:

```
MatrixFunctionCoefficient(int dim, void (*F)(const Vector &, DenseMatrix &), Coefficient *q = NULL)
```
I apologize for the incovenience again. Thank you in advance.
Best regards,

Alvaro

**Comment by S-Villar** [comment]
Hello again, 

I also see that I could make use of `MatrixArrayCoefficient`. I would need to create linear continuous GridFunctions, based on those create GridFunctionCoefficients and pass them by pointers to a method MatrixArrayCoefficient::Set(int i, int j, Coefficient * c) { delete Coeff[i*width+j]; Coeff[i*width+j] = c; }.

What do you think?

Thanks a lot again,
Best,
Alvaro

**Comment by v-dobrev** [comment]
Hi @S-Villar,

Deriving your own sub-class of `MatrixCoefficient` should be the most flexible approach - I'd recommend using that. However, the other approaches can work too - there isn't really "one correct solution" here.

**Comment by S-Villar** [comment]
Hello all, 

Just for the sake of explanation in case it would be helpful for anyone that may look for this information, I will explain what I did. 

MFEM has a wide variety of specific ways to create coefficients. In case of the user willing to read inputs as values on a mesh and create a coefficient of any kind, I used the following approach. 

First of all, a simplified approach to the use of `GridFunctionCoefficient`:
1. Create a `GridFunction` associated to a `FiniteElementSpace` based on elements of `H1_FECollection`. 
2. Load the values of the `GridFunction * gf` from a `ifstream` object. Order is that of the vertices of the mesh used.
3. Create a `GridFunctionCoefficient(GridFunction * gf) `. 

In my case I needed to define functions of these parameters and use them as to build coefficients that would constitute the elements of a `MatrixCoefficient`. Currently MFEM has no finite element spaces for matrix-valued according to #753. This seems to be the answer to "why there are no `MatrixGridFunctionCoefficients`". However we can build a `MatrixArrayCoefficient` whose elements are `Coefficient *`, each of them being a `GridFunctionCoefficient` based on a `GridFunction`. 

Furthermore I generated a new derived class from `GridFunctionCoefficient`, `FScaledGFCoefficient` , similar to `mfem::electromagnetics::ScaledGFCoefficient` that can use another coefficient, of any other kind and operate with it.

```
/*
 * FScaledGFCoefficient.h
 */
#ifndef FSCALEDGFCOEFFICIENT_H_
#define FSCALEDGFCOEFFICIENT_H_

#include <fem/coefficient.hpp>

namespace mfem {
class FScaledGFCoefficient: public GridFunctionCoefficient
{
private:
	Coefficient *c;
public:
	FScaledGFCoefficient(GridFunction *gf, Coefficient *C = NULL):GridFunctionCoefficient(gf),c(C){};
	friend int FScaledGFCoefficient_test(const bool testcase);
	virtual double Eval(ElementTransformation &T, const IntegrationPoint &ip);
	void SetC(Coefficient *C){delete c; c = C;}
	virtual ~FScaledGFCoefficient() {}
};
} 
#endif /* FSCALEDGFCOEFFICIENT_H_ */
```
This new class goes with its own `Eval` method, that uses a `Coefficient` of any kind and multiplies it to the `GridFunction` when used in the integration. For instance:
`	 return c->Eval(T,ip)*GridFunctionCoefficient::Eval(T,ip);
`
This `FScaledGFCoefficient::Eval` could be a function of any kind using both `Coefficient`s.

With a series of `FScaledGFCoefficient`s we can create coefficients to be used in the building of any ArrayCoefficient, it being either a `VectorArrayCoefficient` or a `MatrixArrayCoefficient`.

@v-dobrev, what do you think about this coefficient?  Although its rather difficult to create a generalized approach for coefficients, that are also flexible to every specific case,  I think you have done a really good job. However,  I think that there is a lack of documentation on how to use those coefficients and how to create your own coefficients. It would have been helpful for me if it was explained somewhere. I know this is also part of source code development/c++ knowledge but maybe there is a need of improving documentation for mfem. I mean this comment to improve the userfriendlyness of MFEM. I saw mfem::electromagnetism module and studied the source code of MFEM to do this. However, let me know if you can, any flaw you may notice in this approach, and in my new coefficient.

Thanks for the replies and I hope these explanations are helpful for someone. 

Best,
