### ISSUE TITLE
Parallelism in ParMesh

### ISSUE THREAD

**Issue by vivhuff** [mfem/mfem#750]
Hi, 
I'm writing my thesis on parallel patterns in miniapps and the app I'm currently working on (Laghos) heavily relies on mfem and uses it's parallel datatypes and solvers. Unfortunately I'm not very knowledgable in this topic (working with meshes and C++ coding) and have a hard time understanding how the ParMesh datatype works. 

Could someone please give me pointers how a ParMesh is partitioned and parallelized? Especially how the processes communicate with each other and how the data is distributed among them. Or does mfem not handle the actual distribution of the partitions among the nodes?

Thanks for any help.
Vivian

**Comment by jakubcerveny** [comment]
Hi @vivhuff, the ParMesh is typically constructed from a serial Mesh, which is partitioned with Metis. Each element is assigned to one of the MPI ranks. Each processor then only keeps the elements it owns. Shared faces, edges and vertices on the processor boundaries are identified. Each shared entity is assigned a communication group which lists the processors that share the entity. Each comm group has an owner (processor with the lowest MPI rank) responsible for assigning global DOFs to entities in the group. Communication is typically asynchrounous within the groups of nearby processors. A parallel conforming prolongation matrix is created that ties together shared DOFs of neighboring processors. The matrix is used to assemble local stiffness matrix blocks (computed by each MPI rank without communication) into a final parallel matrix. The triple matrix product (P^T*A*P) is done by the hypre library.

I am finishing a paper on non-conforming AMR in MFEM which covers some of these concepts. I can share the manuscript or answer questions.

**Comment by vivhuff** [comment]
Thanks for your reply @jakubcerveny. I think I actually understood your explanation. Just the matrix I will have to look into more since I do not really get what DOFs are. If you do not mind sharing your paper I would gladly come back to that offer when I understand the background of what is actually done better. Since it seems that might also factor into my troubles.

**Comment by jakubcerveny** [comment]
Degrees of freedom or DOFs are unknowns assigned to vertices and (in high order FEM) to edges, faces and element interiors. For example, a quadratic hexahedron has 8 vertex DOFs, 12 edge DOFs, 6 face DOFs and one internal DOF. I can send you the paper if you write me at cerveny1@llnl.gov.
