### ISSUE TITLE
How to get the cell central in mfem?

### ISSUE THREAD

**Issue by ztdepztdep** [mfem/mfem#751]
Dear sir:
     I need cell central to conduct FVM computations, in mfem, how to  get the Vertexes that comprising a cell.  I tried to use   "mesh->ElementToVertexTable()", but mfem doesn't provide this function.
   Could you please give me some suggestions.
Regards

**Comment by jakubcerveny** [comment]
Did you try calling Mesh::GetElementVertices to get vertex indices and then Mesh::GetVertex to get the vertex coordinates?
