### ISSUE TITLE
GridFunction::ProjectCoefficient (MatrixCoefficient &mcoeff)

### ISSUE THREAD

**Issue by S-Villar** [mfem/mfem#753]
Hello all,

Imagine I have a MatrixCoefficient whose DenseMatrix is dimension dim=2. I would like to evaluate such MatrixCoefficient in the nodes of my domain and save it. I have done this using `GridFunction::ProjectCoefficient`. Specifically, for a `Coefficient`  using `GridFunction::ProjectCoefficient (Coefficient &coeff)` and for a `VectorCoefficient` using GridFunction::ProjectCoefficient  ( VectorCoefficient & vcoeff ). However, there is no method for a `MatrixCoefficient`.  

Maybe there is an alternative to this.

Thank you in advance.

Alvaro

**Comment by tzanio** [comment]
Currently we don't have finite element spaces for matrix-valued functions, so direct projection will not make sense.

One option to get around this could be to treat your `MatrixCoefficient` as a `VectorCoefficient` of vector dimension (`vdim`) 4.

**Comment by S-Villar** [comment]
Thank you Tzanio for your reply,

Indeed this is one solution that would make sense. At the end I used a singular coefficient for each matrix element. 

Thank you
