### ISSUE TITLE
[okina] Support for ComputeL2Error grid function method

### ISSUE THREAD

**Issue by artv3** [mfem/mfem#761]
A feature that would be nice to have is support for the ComputeL2Error grid function method when using Okina/Okina memory manager. If I have  GPU capabilities enabled, i.e. 

```c++
config::useCuda();
config::enableGpu(0);
config::SwitchToGpu();
```

I get assertion errors or if i try to switch to the cpu, i.e. 

```c++
config::SwitchToCpu()
```

I get the following error 

```c++
mm::Ptr
```

I'll make a reproducer using example 9.

**Comment by camierjs** [comment]
Switching back to host for the mass CG solver allows to get the right solution.
This solves #762 and #768.
