### ISSUE TITLE
Example of Mixed FE system with handling of Dirichlet boundary conditions.

### ISSUE THREAD

**Issue by Patrick81** [mfem/mfem#77]
Hello,
It would be very helpful if you could provide one example of how to handle boundary conditions in the block system arising from mixed fe problems, such as the Darcy problem. 

Thank you in advance for your answer.
Best regards,
Patrick

**Comment by trb413** [comment]
Hi Patrick,

For Darcy, you can eliminate BCs on the "M" block as usual (ex1, for
instance). For the "B" block, you can eliminate columns using "void
MixedBilinearForm::EliminateTrialDofs(Array<int>,Vector,Vector)". Then take
the transpose to get the (row-eliminated) "B^T" block. But yes, it'd be
good to have an example of this.

Cheers,
Tom

**Comment by tzanio** [comment]
Hi Patrick,

It is not exactly what you asked for, but there is an example of using `EliminateTrialDofs` and `EliminateEssentialBCFromTrialDofs` in the DPG example codes:

https://github.com/mfem/mfem/blob/master/examples/ex8.cpp#L157
https://github.com/mfem/mfem/blob/master/examples/ex8p.cpp#L178

We are also working on support for essential boundary conditions in general `Operator` objects, which will be part of next release (3.2.1).

Hope this helps,
Tzanio
