### ISSUE TITLE
Visualizing boundary attributes / quantities in VisIt

### ISSUE THREAD

**Issue by junkudo** [mfem/mfem#772]
Hey,
Is there an easy / straight-forward approach to be able to visualize boundary/surface-based quantities in VisIt through MFEM?  I'd like to be able to visualize surface loads, face attributes, etc.
Thanks!
Jun
@Dan2997925

**Comment by v-dobrev** [comment]
It may be possible, if the boundary data is saved separately as a surface mesh + grid function. I've never tried that.

Example 7/7p uses a surface mesh - I'll try adding VisIt output there to see if that works. If it does, then we can add a few methods in MFEM that extract the boundary mesh + solution from a 3D mesh + solution.

**Comment by v-dobrev** [comment]
Exporting the surface mesh + solution from example 7 seems to work fine.

**Comment by junkudo** [comment]
Yeah based on some advice from @mlstowell, I made a new mesh composed only of the boundary faces, defined a grid function on that mesh, and then visualized that function.  It works but it was more involved than I would have liked.  I like the idea of implementing some functions in MFEM that does this for me.

**Comment by v-dobrev** [comment]
Okay, let's keep this issue open for now, as a feature request.

**Comment by junkudo** [comment]
@v-dobrev I have some code that does this that I could share.  I just wouldn't know where to put it or how general I can / should make it.

**Comment by v-dobrev** [comment]
One option is to create a small standalone tool that extracts the boundary mesh and solution. If you want, make a branch and put your code in a file in `miniapps/meshing/`. From there we can discuss how to proceed - probably we can move some of the code to `mesh/` and/or `fem/`.

**Comment by junkudo** [comment]
Hey @v-dobrev, here's my kludge at extracting out the boundary mesh from a given mesh.
[Boundary mesh extraction](https://github.com/junkudo/mfem/tree/feature/boundary_mesh_extraction).  I've placed [extract_boundary_mesh.cpp](https://github.com/junkudo/mfem/blob/feature/boundary_mesh_extraction/miniapps/meshing/extract_boundary_mesh.cpp) in `miniapps/meshing`

The main headache is that I'm not aware if `mfem::Mesh` has general addition functions (as opposed to the specific `mfem::Mesh::AddTri(...)` and `mfem::Mesh::AddQuad(...)` routines) and general finalize routines (again as opposed to`mfem::Mesh::FinalizeTriMesh(...)` and `mfem::Mesh::FinalizeQuadMesh(...)`).  I haven't thought about how this works when you actually have a `mfem::ParMesh` as I don't actually know how that abstraction works.  Let me know how to you want to proceed.

**Comment by tzanio** [comment]
@junkudo, do you want to create a pull request for the `feature/boundary_mesh_extraction` branch?

**Comment by junkudo** [comment]
I can.  Did you want to leave it as a stand alone executable?

**Comment by tzanio** [comment]
> Did you want to leave it as a stand alone executable?

Either that or you can make it an option in Mesh Explorer. I don't have a strong preference.

**Comment by junkudo** [comment]
I'm going to get to this tomorrow!

**Comment by tzanio** [comment]
Thanks @junkudo. We will continue the discussion in #930.
