### ISSUE TITLE
Incompatibility with SUNDIALS 4.0.0

### ISSUE THREAD

**Issue by hillyuan** [mfem/mfem#776]
Sundials interface modified after Sundials release 4.0.0.  File arkode_spils.h, which is included in file sundials.cpp, do not exist anymore.

**Comment by v-dobrev** [comment]
Hi @hillyuan,

You are right: currently MFEM only supports v2.7 and v3.x of SUNDIALS. We are working on switching to v4.0.

**Comment by tzanio** [comment]
@gardner48, any progress on the sundials 4.0 support in mfem?

**Comment by gardner48** [comment]
I've worked up two approaches for updating the sundials interfacing and will be sending around a description of the plan in the next day or two to see what sounds best to everyone.

**Comment by tzanio** [comment]
Lets continue this discussion at #923
