### ISSUE TITLE
Invert a block diagonal HypreParMatrix

### ISSUE THREAD

**Issue by martemyev** [mfem/mfem#78]
Hi All,

I'm solving a wave equation where at each iteration I need to solve a system of equations `AX=b`. The SLAE matrix `A` is, however, a block diagonal (for example, if the DG method is used, the SLAE matrix is block diagonal with number of blocks equal to the number of mesh cells, and each block has a size of the number of dofs in that cell). I would like to compute an inverse matrix `A^-1`, so that at each iteration in time I'd need to do only matrix-vector multiplication `X=A^-1 b`. For general sparse matrices this typically doesn't make sense as the inverse of a sparse matrix is dense, but the inverse of a block diagonal matrix is also block diagonal with each block being the inverse of the corresponding block of the original matrix. Therefore, I am wondering if there is an effective approach to implement such an inversion within Hypre/MFEM framework. In case of sequential implementation, I can compute the offsets of the blocks, extract them as dense matrices, invert, and put them back. But I'm interested in parallel implementation, and maybe there is something in Hypre specifically for my task.

Thank you,
Mikhail

**Comment by tzanio** [comment]
How about assembling the inverses of the local stiffness matrices? See https://github.com/mfem/mfem/blob/master/fem/bilininteg.hpp#L132

**Comment by martemyev** [comment]
Hi Tzanio,

Thank you for the suggestion. The inverse integrator is an interesting feature. My SLAE matrix is, however, computed this way: `A = R M R^T`, where `M` is a standard mass matrix, and as far as I understood I can compute the `M^-1` using the inverse integrator, but `R` is some rectangular projection matrix to a coarser space (I work with some multiscale methods), so I don't see how I can compute `A^-1` with that.
I suspect I still can compute the offsets of the block of the diagonal for the parallel matrix `A`, and invert it block by block, but I'm wondering if there is a better approach.
Any idea would be highly appreciated.

Thank you,
Mikhail

**Comment by tzanio** [comment]
Hi Mikhail,

If both `M` and `A` are block-diagonal over the elements, then so must be `R`. If that's the case, can't you compute the element action `R_e M_e R_e^T`, maybe as a special integrator, and then assemble its inverse?

If you are starting with `A`, I can't think of anything better than what you proposed.

Cheers,
Tzanio

**Comment by martemyev** [comment]
Hi Tzanio,

Thank you for the idea! I implemented that initial approach that I had in mind, so I think I'll go with it.

Cheers,
Mikhail
