### ISSUE TITLE
Transport equation with streamline diffusion

### ISSUE THREAD

**Issue by azeiser** [mfem/mfem#781]
I am working on the solution of the transport equation using continuous finite elements with streamline diffusion. As a first simple example I use (a·∇u , v+ h a·∇v) = (f, v+ h a·∇v), u=g on Γ_ on an polygonal domain with a constant vector a. Γ_ is inflow part of the boundary (i.e. a·n<0).

On the one hand, this could be thought of as a Petrov-Galerkin method with trial functions v+ h a·∇v. As far as I can see these are not implemented yet.

On the other hand, one could multiply out the forms. I handled the lhs as a `MixedBilinearForm` with two terms: `MixedDirectionalDerivativeIntegrator` for (a·∇u , v) and` DiffusionIntegrator` for (h a a^T ∇u,∇v). However I do not see how I could handle the term (f, h a·∇v) on the rhs with the current linear form integrators.

What is the best way to solve the equation? I would be grateful for any hints.

Thanks a lot
Andreas

**Comment by v-dobrev** [comment]
Hi Andreas,

I see two options:
1. Implement a new `LinearFormIntegrator` for the term (f, h a·∇v) - if you feel comfortable doing that - I'll be happy to help you. We'll be interested to merge this new integrator into the master MFEM branch.
2. Assemble the term (f, h a·∇v) by first assembling the bilinear form for (a·∇u , v), i.e. using `MixedDirectionalDerivativeIntegrator` in a `MixedBilinearForm`, and then multiplying the transpose of the resulting matrix by the projection of the coefficient f (scaled by h) onto the test space - the projection will be a `GridFunction` on the test space, obtained using the method `GridFunction::Project`.

Let us know if you want to pursue 1, or if you prefer 2 and you have further questions about this approach.

Thanks,
Veselin

**Comment by azeiser** [comment]
Hi Veselin,

thank you for your prompt reply. I am interested in option 1. However I am not an expert in implementing FEM code and I have not looked too deep into the code. How much effort do you expect?  

To keep going on for the moment I tried to implement option 2: With `f` being a coefficient and `a` the bilinear form `MixedDirectionalDerivativeIntegrator`, I assembled the the extra term (f, a·∇v) on the rhs by

    GridFunction f_proj(fespace);
    f_proj.ProjectCoefficient(f);
    Vector B_sd(f_proj.Size());
    a->MultTranspose(f_proj, B_sd);

Now, to include the boundary conditions of the dofs `ess_tdof_list` I set the corresponding dofs in `x` to the boundary values and formed a linear system by adding the term from above with a factor h on the vector `B`:

    Operator *a_elim;
    Vector B, X;
    a->FormLinearSystem(ess_tdof_list, x, *b_f, a_elim, X, B);
    B_sd.SetSubVector(ess_tdof_list, 0.0);
    B.Add(h, B_sd);

To keep the boundary values unchanged I set the corresponding dofs in `B_sd` to zero. Do you agree so far? 

Finally this gives a matrix-free operator `a_elim`. I solved the system with SLI - is it possible to convert `a_elim` into a sparse matrix (like in `BilinearForm::FormLinearSystem`) and use a direct solver? What would you suggest? 

Thank you again for your help.
Andreas

**Comment by tzanio** [comment]
Hi Andreas, 

Sorry for not following up with you earlier. Were you able to find a way to get this working?

Tzanio
