### ISSUE TITLE
'unit_tests' can't pass building

### ISSUE THREAD

**Issue by TangLaoya** [mfem/mfem#784]
Dear all,
I have downloaded the latest version of mfem from here and try to build the whole project by VS2017 in windows 10. I used the cmake to generate VS project (64bit) and didn't modify any default settings. When build the whole solution all projects passed except the one 'unit_tests'. The errors are like the following:
test_quadraturefunc.cpp
3>c:\mfem3.3\config/config.hpp(23): fatal error C1083: Cannot open include file: '_config.hpp': No such file or directory

In addition, I am trying to create a single 'tesla' solution, I added source files 'tesla.cpp' and 'tesla_solver.cpp' into the project, and set include directories where header files located, and included the 'mfem.lib' into linker input. When building this solution, the same errors displayed:
Cannot open include file: '_config.hpp': No such file or directory
tesla.cpp
1>c:\mfem3.3\config\config.hpp(23): fatal error C1083: Cannot open include file: '_config.hpp': No such file or directory

Could anyone help me to take a look at it?

Thanks,
Tang Laoya

**Comment by acfisher** [comment]
It looks like our CMAKE system is not generating the proper hooks for our configuration generated header when used to create the project file.  I've been meaning to get a windows environment up and running, and this will give me the impetus to poke at it in the next few days, so stay tuned.  In the meantime, has anyone else gotten MFEM up and running using Visual Studio?

**Comment by tzanio** [comment]
@acfisher, do you know if the unit tests pass with the CMake build?

**Comment by acfisher** [comment]
@jonesholger took a look at this and is 90% the way to a fix.  If I am not mistaken he is going to create a pull request for it soon.

**Comment by v-dobrev** [comment]
This is a bug in the file `tests/unit/CMakeLists.txt`. The order of the following two `include_directories` commands needs to be switched:
https://github.com/mfem/mfem/blob/ff9819e4953668c38931f8aff27b403f34180af4/tests/unit/CMakeLists.txt#L12-L16

**Comment by v-dobrev** [comment]
By the way, this is not just a Windows issue - it affects all platforms.
