### ISSUE TITLE
Which solver to use for windows desktop app

### ISSUE THREAD

**Issue by CharlesFr** [mfem/mfem#786]
We're looking to start integrating some simulation capabilities in our software, hopefully using Mfem.

As I investigated other options, PETCs was presented as a very fast solution but not compatible with windows. We're currently using Eigen & FEniCS.

Is there an equally fast solver that works with mfem we can easily integrate?

Ps: If you have an example with a simple static heat conduction solver, that'd be very helpful!

**Comment by tzanio** [comment]
Hi @CharlesFr,

Can you give *hypre* a try?  

https://computation.llnl.gov/projects/hypre-scalable-linear-solvers-multigrid-methods/software

It has a CMake build system that works on Windows, and that's what provides the scalable AMG solver in PETSc anyway. It is also deeply integrated with MFEM.

Our heat conduction example, https://mfem.org/examples/#ex16, should work in that case.

Tzanio
