### ISSUE TITLE
Mixed degree of freedom problem

### ISSUE THREAD

**Issue by hillyuan** [mfem/mfem#788]
Considering a model with multiple domains with different dofs. For example, a two-material cantilever beam as given in example 2, but one part as elastical material and another be incompressible nonlinear elasticity as given in example 19, for which an additional variable p should be introduced. Is it possible and how to implement such problems in MFEM?

**Comment by tzanio** [comment]
There is no general functionality for coupling completely independent PDE models, but it is probably possible to implement this depending on your particular situation.

Lets say the mesh is split in two parts M1 and M2 and you have different PDE models, PDE1 and PDE2, in these two parts (with some shared variables).

One (expensive, but simple) way to model the coupling is to define the integrators for PDE1 with zero coefficient in M2, which will assemble a block matrix A1 which is nonzero only on the 1-variables. Similarly assembling the integrators for PDE2 with zero coefficient in M1 gives a block matrix A2 on the 2-variables. Then the overall operator can be defined as the sum of A1 and A2, e.g. (u',p') = A (u, p) can be defined as u1 = A1 u, (u2, p2) = A2 (u, p), u' = u1 + u2, p' = p2.

Hope this helps,
Tzanio

**Comment by hillyuan** [comment]
Dear taznio,

Thanks for your response.

Yes, your suggestion seems quite expensive. 

 I think it is a commonly used function, which could apply in Fluid–structure interaction, XFEM and others.  Do you have any plan to introduce this functionality?

**Comment by tzanio** [comment]
We are generally interested in supporting "different physics in different subdomains", but designing the proper API for that, so it is general but easy to use, have not a near term task for us.

The simplest approach I can think of for your particular case may be to introduce the pressure variable in the elastic portion, and just take into account that it is always zero there. 

Maybe other MFEM users / developers will have simpler suggestions?

**Comment by hillyuan** [comment]
A data structure which allows Mesh with multiple subdomains and FiniteElementCollections maybe needed.
