### ISSUE TITLE
Using a different solver package like PETSc

### ISSUE THREAD

**Issue by juan42** [mfem/mfem#79]
Hi,

are there any intentions in making PETSc solvers available? I guess this should be a more or less trivial addition because you can call BoomerAMG from PETSc and HYPRE itself also has a method to represent a matrix in PETSc format (guessing from the Euclid code).

**Comment by stefanozampini** [comment]
We are currently working on it. My best guess is that it should be available in the new major release

**Comment by juan42** [comment]
@stefanozampini Great. Also good to see familiar faces on this project :+1:
