### ISSUE TITLE
How to obtain a HypreParMatrix from a BlockOperator

### ISSUE THREAD

**Issue by qiuchangkai** [mfem/mfem#790]
Hi, I want to apply the `HypreEuclid` preconditioner to a `BlockOperator,` since `HypreEuclid` explicitly requires a `HypreParMatrix`? Is it implemented yet?

Thanks! 
Changkai

**Comment by mlstowell** [comment]
Hi, @qiuchangkai ,

The short answer is "No", unfortunately.  We do have a special case of this process implemented in a branch called `complex-mfem-dev`.  In this branch you should find the method  `ComplexHypreParMatrix::GetSystemMatrix()` in the file `linalg/complex_operator.cpp`.  This takes the blocks of a 2x2 block matrix and builds from them a single HypreParMatrix which can be passed along to a solver.

If I recall correctly, this method assumes the blocks of the 2x2 system have the same dimensions and it may assume they are square blocks.  It does not assume that the blocks have the same sparsity patterns.  It should be possible to generalize this algorithm to an arbitrary bock operator and I hope it's fairly clear how that could be done.

Best wishes,
Mark

**Comment by tzanio** [comment]
In serial, there is also `BlockMatrix::CreateMonolithic()`.

Another option could be to do a block inverse, but that will require inverting the Schur complement, which will be more complicated.

**Comment by qiuchangkai** [comment]
Thanks, Mark, I will follow your suggestion.

**Comment by qiuchangkai** [comment]
Dear Tzanio, 

I now obtain a single `SparseMatrix` with `BlockMatrix::CreateMonolithic()` in serial. How could I convert it to a `HypreParMatrix?` 

The constructor

`HypreParMatrix(MPI_Comm comm, HYPRE_Int *row_starts, HYPRE_Int *col_starts,
                  SparseMatrix *a); // constructor with 4 arguments, v2`

seems to work, but it shows

`Verification failed: (!HYPRE_AssumedPartitionCheck()) is false:
 --> this method can not be used with assumed partition
 ... in function: mfem::HypreParMatrix::HypreParMatrix(int, int *, int *, mfem::SparseMatrix *)`

The constructor 

`HypreParMatrix(MPI_Comm comm, int nrows, HYPRE_Int glob_nrows,
                  HYPRE_Int glob_ncols, int *I, HYPRE_Int *J,
                  double *data, HYPRE_Int *rows,
                  HYPRE_Int *cols); // constructor with 9 arguments`

is also an option. I am not clear about the `rows` and `cols` arguments.  The following code (in serial) does not work. I guess I am providing wrong `rows` and `cols` to the constructor.

        int nrows = sK->Height();
        HYPRE_Int glob_nrows = nrows;
        HYPRE_Int glob_ncols = nrows;
        int *I = sK->GetI();
        HYPRE_Int *J = sK->GetJ();
        double *data = sK->GetData();
        HYPRE_Int *rows = new HYPRE_Int[nrows];
        HYPRE_Int *cols = new HYPRE_Int[nrows];
        for(int i = 0; i < nrows; i++)
        {
            rows[i] = i;
            cols[i] = i;
        }

Any suggestions? Thanks.

Changkai

**Comment by qiuchangkai** [comment]
I also tried to convert the `SparseMatrix` resulting from `BlockMatrix::CreateMonolithic()` to a `PetscParMatrix`. The error is 

[0]PETSC ERROR: --------------------- Error Message --------------------------------------------------------------
[0]PETSC ERROR: Argument out of range
[0]PETSC ERROR: Column entry number 1 (actual colum 0) in row 0 is identical to previous entry

**Comment by tzanio** [comment]
@qiuchangkai, the second approach is probably what you want. The `rows` and `cols` parameters need to have only 2 entries: `rows[0] = 0; rows[1] = nrows` and similar for `cols`.
