### ISSUE TITLE
Does MFEM include a discretization feature (Tetrahedrons, Hexagons)?

### ISSUE THREAD

**Issue by pierre-leon** [mfem/mfem#791]
We're looking to add FEA simulation capabilities in our software, hopefully using Mfem.
We're already loading STL and STEP files as triangular shell meshs and are looking for a mesh discretization. 
I found references to PMesh or DRACO on the LLNL website but not sure if these are included in MFEM?

**Comment by tzanio** [comment]
Hi Pierre,

We do support a number of external meshing packages for both tetrahedral and hexahedral meshes, bit MFEM does not include a general internal meshing capability. 

Specifically, 
- We support the Gmsh, CUBIT, NETGEN and TrueGrid mesh generators, see https://mfem.org/meshing/
- Can read meshes in VTK and NURBS format (adding readers for new formats is easy), see https://mfem.org/mesh-formats/
- Have some simple internal mesh generation capabilities, see https://mfem.org/examples/#meshing
- Have integration with the PUMI parallel mesh infrastructure, see https://www.scorec.rpi.edu/pumi/

For the case you are describing (an input of STL shell mesh), the simplest way may be to use NETGEN to build a volume mesh which can then be read and used in MFEM. We will be happy to assist in that if you run into difficulties.

Hope this helps,
Tzanio

**Comment by tzanio** [comment]
Closing this, but please feel free to reopen if you have any further questions.
