### ISSUE TITLE
Compute an auxiliary variable J=∆u that involves the boundary condition properly

### ISSUE THREAD

**Issue by tangqi** [mfem/mfem#792]
Dear all,

I want to define an auxiliary variable J=∆u, with u being some solution. Naively, I would let J=-M^{-1}\*K\*U by
```c++
Kmat.Mult(u, z);
z.Neg();
M_solver.Mult(z, j);
```
It works for the case that has no boundary condition. 

But for my problem that is periodic in x and Dirichlet in y, it is apparently wrong. I have replaced terms associated with the true degrees of freedom along the boundary with
```c++
for (int i=0; i<ess_tdof_list.Size(); i++) 
   z(ess_tdof_list[i])=0.0;
```
But the boundary term in K\*U are still missing. I am wondering how to add them back correctly. Do I need to define a boundary integrator? Or is there a better way to do so?

Thanks a lot,
Qi

**Comment by tzanio** [comment]
Hi Qi,

Have you tried using `FormLinearSystem` for `M` and `b=Ku`?

It will reduce the problem to `M_id j_i = b_i - M_id g_d` plus `j_d=g_d`, where `d` are the Dirichlet dofs, and `g_d` are the given Dirichlet conditions.

Hope this helps,
Tzanio

**Comment by tangqi** [comment]
@tzanio Thanks for the suggest. I tried, but for a simple case of g_d=0, it is not working. For instance,

```c++
   Kmat.Mult(u, z);
   z.Neg(); // b=-Ku
   if (true)
   {
        SparseMatrix A;
        Vector B, X;
        M->FormLinearSystem(ess_tdof_list, j, z, A, X, B);

        ofstream myfile1("B.dat");
        B.Print(myfile1, 1000);
   }
   else
   {
        for (int i=0; i<ess_tdof_list.Size(); i++)
              z(ess_tdof_list[i])=0.0; //set Dirichlet condition j_d = 0

        ofstream myfile("z.dat");
        z.Print(myfile, 1000);
   }
```
Two options give me identical z and B, but it is not right. (For the simplest test, I assume u=-y and want to get J=0). 

I suspected that my boundary term is messed up, so I accidentally find the following fix:
```c++
   H1_FECollection fe_coll(order, dim); //dim=2
   FiniteElementSpace fespace(mesh, &fe_coll); 
   LinearForm b(&fespace);
   ...
   VectorArrayCoefficient dudn(dim);
   for (int i = 0; i < dim-1; i++)
      dudn.Set(i, new ConstantCoefficient(0.0));
   {
      Vector dudny(fespace.GetMesh()->bdr_attributes.Max());
      dudny = -1.0; //the normal vector is [0, \pm 1] and dudy=-1
      dudn.Set(dim-1, new PWConstCoefficient(dudny));
   }
   b.AddDomainIntegrator(new VectorBoundaryLFIntegrator(dudn));
   b.Assemble();
   ...
   Kmat.Mult(u, z);
   z.Neg();
   K->FormLinearSystem(ess_tdof_list, u, b, A, X, B);
   z.Add(1.0,B);  //this step is able to remove the wrong term in z
   M_solver.Mult(z, j);
 ```
The above code removes the wrong boundary term in z and give me the correct J. But it looks like I did something crazy, since I have a 1D fespace but I was able to add `VectorBoundaryLFIntegrator`. I tried `BoundaryLFIntegrator`, but I was not able to remove the wrong boundary term. 

I am quite confused. Let me know if you have any suggestion...

Qi

**Comment by tzanio** [comment]
This is actually a little bit tricky, so don't worry that you didn't get it right away :)

I assume your goal is to define J=∆u on discrete level, regardless of any specific boundary conditions that may have been defined on u (or that we may want to impose on J).

To get this, we start from the weak form of J=∆u which is
```
(J, ϕ)_Ω = (∆u, ϕ)_Ω = -(∇u,∇ϕ)_Ω + (∇u.n, ϕ)_∂Ω
```
Discretizing the above we get
```
M J = - K u + B u
```
where `K` and `M` are the regular stiffness and mass matrices, and `B` is the matrix corresponding to the boundary term `(∇u.n, ϕ)_∂Ω`.

This matrix `B` is the tricky part, because it is an integral on the boundary that involves derivatives (∇u) that require information from the interior of the element. This requires a new integrator that is not part of the MFEM distribution. 

I will include a full example in the next post, but given that integrator, here is the relevant code you need to add:

```c++
// Mass and stiffness matrices
BilinearForm *M = new BilinearForm(fespace);
M->AddDomainIntegrator(new MassIntegrator);           //  M matrix
M->Assemble();
BilinearForm *K = new BilinearForm(fespace);
K->AddDomainIntegrator(new DiffusionIntegrator);      //  K matrix
K->AddBdrFaceIntegrator(new BoundaryGradIntegrator);  // -B matrix
K->Assemble();

// z = - ( K - B ) u
Vector z(u.Size());
K->Mult(u, z);
z.Neg();

// J = M^{-1}(- K u + B u)
M_solver.Mult(z, j);
```

@v-dobrev: Should we include `BoundaryGradIntegrator` in the master branch? This type of Laplacian projection seem to be common in fusion discretizations...

**Comment by tzanio** [comment]
Example code  for the J=∆u computation in H1. Put and build in the `examples/` directory.

```c++
// Example for issue 792, see https://github.com/mfem/mfem/issues/792

#include "mfem.hpp"
#include <fstream>
#include <iostream>

using namespace std;
using namespace mfem;

double u_exact(const Vector &x)
{
   return x(0)*x(0)*x(0); // run with -o 2 or higher
   // return x(0);
}

// Integrator for the boundary gradient integral from the Laplacian operator
class BoundaryGradIntegrator: public BilinearFormIntegrator
{
private:
   Vector shape1, dshape_dn, nor;
   DenseMatrix dshape, dshapedxt, invdfdx;

public:
   virtual void AssembleFaceMatrix(const FiniteElement &el1,
                                   const FiniteElement &el2,
                                   FaceElementTransformations &Trans,
                                   DenseMatrix &elmat);
};

void BoundaryGradIntegrator::AssembleFaceMatrix(
   const FiniteElement &el1, const FiniteElement &el2,
   FaceElementTransformations &Trans, DenseMatrix &elmat)
{
   int i, j, ndof1;
   int dim, order;

   dim = el1.GetDim();
   ndof1 = el1.GetDof();

   // set to this for now, integration includes rational terms
   order = 2*el1.GetOrder() + 1;

   nor.SetSize(dim);
   shape1.SetSize(ndof1);
   dshape_dn.SetSize(ndof1);
   dshape.SetSize(ndof1,dim);
   dshapedxt.SetSize(ndof1,dim);
   invdfdx.SetSize(dim);

   elmat.SetSize(ndof1);
   elmat = 0.0;

   const IntegrationRule *ir = &IntRules.Get(Trans.FaceGeom, order);
   for (int p = 0; p < ir->GetNPoints(); p++)
   {
      const IntegrationPoint &ip = ir->IntPoint(p);
      IntegrationPoint eip1;
      Trans.Loc1.Transform(ip, eip1);
      el1.CalcShape(eip1, shape1);
      //d of shape function, evaluated at eip1
      el1.CalcDShape(eip1, dshape);

      Trans.Elem1->SetIntPoint(&eip1);

      CalcInverse(Trans.Elem1->Jacobian(), invdfdx); //inverse Jacobian
      //invdfdx.Transpose();
      Mult(dshape, invdfdx, dshapedxt); // dshapedxt = grad phi* J^-1

      //get normal vector
      Trans.Face->SetIntPoint(&ip);
      const DenseMatrix &J = Trans.Face->Jacobian(); //is this J^{-1} or J^{T}?
      if (dim == 1)
      {
         nor(0) = 2*eip1.x - 1.0;
      }
      else if (dim == 2)
      {
         nor(0) =  J(1,0);
         nor(1) = -J(0,0);
      }
      else if (dim == 3)
      {
         nor(0) = J(1,0)*J(2,1) - J(2,0)*J(1,1);
         nor(1) = J(2,0)*J(0,1) - J(0,0)*J(2,1);
         nor(2) = J(0,0)*J(1,1) - J(1,0)*J(0,1);
      }

      // multiply weight into normal, make answer negative
      // (boundary integral is subtracted)
      nor *= -ip.weight;

      dshapedxt.Mult(nor, dshape_dn);

      for (i = 0; i < ndof1; i++)
         for (j = 0; j < ndof1; j++)
         {
            elmat(i, j) += shape1(i)*dshape_dn(j);
         }
   }
}

int main(int argc, char *argv[])
{
   // 1. Parse command-line options.
   const char *mesh_file = "../data/star.mesh";
   int order = 3;
   bool visualization = 1;

   OptionsParser args(argc, argv);
   args.AddOption(&mesh_file, "-m", "--mesh",
                  "Mesh file to use.");
   args.AddOption(&order, "-o", "--order",
                  "Finite element order (polynomial degree) or -1 for"
                  " isoparametric space.");
   args.AddOption(&visualization, "-vis", "--visualization", "-no-vis",
                  "--no-visualization",
                  "Enable or disable GLVis visualization.");
   args.Parse();
   if (!args.Good())
   {
      args.PrintUsage(cout);
      return 1;
   }
   args.PrintOptions(cout);

   // 2. Read the mesh from the given mesh file. We can handle triangular,
   //    quadrilateral, tetrahedral, hexahedral, surface and volume meshes with
   //    the same code.
   Mesh *mesh = new Mesh(mesh_file, 1, 1);
   int dim = mesh->Dimension();

   // 3. Refine the mesh to increase the resolution. In this example we do
   //    'ref_levels' of uniform refinement. We choose 'ref_levels' to be the
   //    largest number that gives a final mesh with no more than 50,000
   //    elements.
   {
      int ref_levels =
         (int)floor(log(50000./mesh->GetNE())/log(2.)/dim);
      for (int l = 0; l < ref_levels; l++)
      {
         mesh->UniformRefinement();
      }
   }

   // 4. Define a finite element space on the mesh. Here we use continuous
   //    Lagrange finite elements of the specified order. If order < 1, we
   //    instead use an isoparametric/isogeometric space.
   FiniteElementCollection *fec = new H1_FECollection(order, dim);
   FiniteElementSpace *fespace  = new FiniteElementSpace(mesh, fec);
   cout << "Number of finite element unknowns: "
        << fespace->GetTrueVSize() << endl;

   // 5. Determine the list of true (i.e. conforming) essential boundary dofs.
   //    In this example, the boundary conditions are defined by marking all
   //    the boundary attributes from the mesh as essential (Dirichlet) and
   //    converting them to a list of true dofs.
   Array<int> ess_tdof_list;
   if (mesh->bdr_attributes.Size())
   {
      Array<int> ess_bdr(mesh->bdr_attributes.Max());
      ess_bdr = 1;
      fespace->GetEssentialTrueDofs(ess_bdr, ess_tdof_list);
   }

   // Initial function
   GridFunction u(fespace);
   FunctionCoefficient u_func(u_exact);
   u.ProjectCoefficient(u_func);

   if (visualization)
   {
      char vishost[] = "localhost";
      int  visport   = 19916;
      socketstream sol_sock(vishost, visport);
      sol_sock.precision(8);
      sol_sock << "solution\n" << *mesh << u
               << "plot_caption 'Initial Function (u)'" << flush;
   }

   // Mass and stiffness matrices
   BilinearForm *M = new BilinearForm(fespace);
   M->AddDomainIntegrator(new MassIntegrator);           //  M matrix
   M->Assemble();
   BilinearForm *K = new BilinearForm(fespace);
   K->AddDomainIntegrator(new DiffusionIntegrator);      //  K matrix
   K->AddBdrFaceIntegrator(new BoundaryGradIntegrator);  // -B matrix
   K->Assemble();

   // z = - ( K - B ) u
   Vector z(u.Size());
   K->Mult(u, z);
   z.Neg();

   // J = M^{-1}(- K u + B u)
   GridFunction J(fespace);
   GSSmoother GS(M->SpMat());
   PCG(M->SpMat(), GS, z, J, 1, 200, 1e-18, 0.0);

   if (visualization)
   {
      char vishost[] = "localhost";
      int  visport   = 19916;
      socketstream sol_sock(vishost, visport);
      sol_sock.precision(8);
      sol_sock << "solution\n" << *mesh << J
               << "plot_caption 'Projected Laplacian (J)'" << flush;
   }

   // Free the used memory.
   delete K;
   delete M;
   delete fespace;
   delete fec;
   delete mesh;

   return 0;
}
```

**Comment by tangqi** [comment]
Thanks a lot for the help!! @tzanio It works very well. I am trying to understand what you have done and will get back to you if I have some questions. 

--Qi

**Comment by tangqi** [comment]
I think I understand what you did in that class. @tzanio Thanks again for teaching me some finite element! 

1. It appears that normal is currently computed by 
```c++
      if (dim == 1)
      {
         nor(0) = 2*eip1.x - 1.0;
      }
      else
      {
          CalcOrtho(Trans.Face->Jacobian(), nor);
      }
```
2. I just realized that you did not implement the boundary condition in your example. After adding the boundary condition in my MHD code, it gives me small errors.

**Comment by tangqi** [comment]
I want to also follow up with this question as well. I am doing nonconforming AMR now, but `K->Assemble()` apparently gives me a sparse matrix that has a larger size than it should have. I think `AddBdrFaceIntegrator` adds more terms along nonconforming nodes. Could you give me hint on how to fix it? Thanks @tzanio !

**Comment by tangqi** [comment]
I think this is due to a different issue of the block vector in AMR. My true dof and dof are messed up. I will close this one and ask in another issue. Thanks again.

**Comment by tangqi** [comment]
During the process of examining the PetscBCHandler in https://github.com/mfem/mfem/issues/1160, I realize I made a mistake in my implementation. When computing J=∆u as an auxiliary variable, I used an essential boundary condition to form a system to solve J in all my parallel codes. (Although it works fine for most cases through `FormLinearSystem`, since there is no boundary layers) However, the boundary condition should not be imposed as the case in the above simple code. 

Now I would like to change it to not imposing the boundary condition. Here is an example code:
```
void UpdateJ(Vector &vx, ParGridFunction *j)
{
   //Here we solve J=-M^{-1}*K*psi
   int VSize = height/4;
   Vector psi(vx.GetData() +  VSize, VSize);

   ParGridFunction zGf(&fespace);
   K->Mult(psi, zGf);
   zGf.Neg(); // z = -z

   int trueSize=fespace.GetTrueVSize();
   Vector zTmp(trueSize), jTmp(trueSize);
   zGf.GetTrueDofs(zTmp);
   M_solver.Mult(zTmp, jTmp); //Here Mmat is assembled without eliminated the essential boundary

   j->SetFromTrueDofs(jTmp); //recover the grid function from TrueDofs
}
```
For some reason, the above code only works for a single processor, although giving me the correct answer. It fails for multiple processors where solutions are off along partitioned domains. Do I miss something obvious @tzanio @mlstowell ? Thanks!

**Comment by mlstowell** [comment]
Hi, @tangqi ,
The line `K->Mult(psi, zGF)` is not performing any communication it is only multiplying the local portion of `zGF` with `SparseMatrices` containing only element matrices from locally owned elements.  Consequently, `zGF` needs to sum together contributions from different processors before extracting data for `zTmp`.

Technically, `zGF` should not be a `ParGridFunction` since it is a dual vector and not a primal vector, see [Primal and Dual Vectors](https://mfem.org/pri-dual-vec/).  It would be better to create this as a `ParLinearForm` object `zLF`.  Then after `K->Mult(psi, zLF)`, which still leaves an incomplete result in `zLF`, you can sum the various contributions into `zTmp` using 'zLF.ParallelAssemble(zTmp)`.

Best wishes,
Mark

**Comment by tangqi** [comment]
Thanks Mark @mlstowell I just had it fixed by calling the prolongation matrix by myself
```
   const Operator &P= *fespace.GetProlongationMatrix();
   P.MultTranspose(zGf, zTmp);
```
I think I got it right by accident, which is essentially your suggestion. I will use `ParLinearForm` instead. 

I thought such an auxiliary variable is common in finite element, I am wondering if I miss some easier way to implement here.

**Comment by tangqi** [comment]
Your suggestion works fine. Thanks again @mlstowell
