### ISSUE TITLE
ParNCMesh with initial partitioning

### ISSUE THREAD

**Issue by stefanozampini** [mfem/mfem#795]
@jakubcerveny Why is the intial partitioning ignored when constructing a ParMesh from a nonconforming Mesh? Is this just an oversight? or are there any code details that do not permit to do that?

**Comment by stefanozampini** [comment]
@jakubcerveny These are the two fixes I had to make so far to get it working.

https://github.com/mfem/mfem/commit/e93b207273e70d416b5107d23a2107592496204b
https://github.com/mfem/mfem/commit/c7eeca7c51c162baf9a2ea96cfbcc9cdd6006e9f
from branch https://github.com/mfem/mfem/compare/stefanozampini/small-improvements

**Comment by jakubcerveny** [comment]
@stefanozampini the problem with prescribed partitioning is that once you call Rebalance, the mesh is partitioned along an SFC curve and the prescribed partitioning is lost. I was also thinking of supporting at least the initial arbitrary partitioning, but there must have been some issue with that (unfortunately I forgot what it was). Let's test your change and we'll see.

The problem with empty processors in `ParNCMesh::GetConformingSharedStructures` is a bug, thanks for fixing that.

**Comment by stefanozampini** [comment]
What I need to achieve is to replicate a ParMesh across subcommunicators, and I need to have those replicated meshes being split the same.
I also need a sort of master mesh, which is split on the original communicator, but preserving the partitioning of the subcommunicator meshes. This is why I need to specify the initial partition. In such a case, Rebalance() will screw my partitioning. I can add a flag to not consider empty local meshes in the rebalance

**Comment by jakubcerveny** [comment]
Specifying the initial partition is clear and should hopefully work. The last sentence I don't understand though. Empy processors are legal and normal in Rebalance. Do you need to call Rebalance in your case?

**Comment by jakubcerveny** [comment]
If you need the load balancing to work diffently you might consider assigning the elements to the MPI ranks yourself and calling the internal method `ParNCMesh::RedistributeElements`.

**Comment by tzanio** [comment]
Addressed in #756
