### ISSUE TITLE
Any plan to support mesh from Tetgen?

### ISSUE THREAD

**Issue by TangLaoya** [mfem/mfem#796]
Dear all,
Do you have any plan to support mesh from Tetgen? Especially, for the output mesh with region number of every tetrahedron, is there any simple method to fill material of every tetrahedron?

Thanks,
Tang Laoya

The code is attached below:

```c++
void loadmesh_memory(int nnode, double *node, int ntet, int *tet, int *nbr, int nregion, double *elepar, femobjv *out)
{
	/// find boundary information according to neighbor
	/// update the I/O to MFEM 3.4.1
	/// Zhanghong Tang @ 03/12/2019
	/// input:
	/// nnode: number of vertices in mesh
	/// node: coordinates of every node, size: 3*nnode
	/// ntet: number of tetrahedron elements
	/// tet: vertices number of tetrahedron elements, size: 5*ntet, 1-4 column: vertices number; 5 column: region number
	/// nbr: neighbor number of tetrahedron elements
	/// nregion: number of regions
	/// elepar: electromagnetic parameters of every region. Size: 4*nregion
	/// elepar((i-1)*4): region number 
	/// elepar((i-1)*4+1): permittivity
	/// elepar((i-1)*4+2): conductivity
	/// elepar((i-1)*4+3): permeability
	/// 1. form element_indices & element_attributes
	int *p, *e, *ti;
	int *element_indices = new int[4 * ntet];
	int *element_attributes = new int[ntet];
	p = element_indices;
	e = element_attributes;
	ti = tet;
	for (int i = 0; i < ntet; i++)
	{
		for (int j = 0; j < 4; j++)
		{
			*(p++) = ti[j];
		}
		*(e++) = ti[4]; /// 5th column is the region number of the tetrahedron
		ti += 5;
	}
	/// form boundary_indices
	int nbnd = 0;
	for (int i = 0; i < 4 * ntet; i++)
	{
		if (nbr[i] == -1)nbnd++;
	}
	int *boundary_indices = new int[4 * nbnd];
	int *boundary_attributes = new int[nbnd];
	int *bi = boundary_indices, *ba = boundary_attributes, *ni = nbr;
	ti = tet;
	for (int i = 0; i < ntet; i++)
	{
		for (int j = 0; j < 4; j++)
		{
			if (ni[j] == -1)
			{
				for (int k = 0; k < 3; k++)
					*(bi++) = ti[tetfacet[j * 3 + k]];
				*(ba++) = ti[4];
			}
		}
		ni += 4;
		ti += 5;
	}
	femobj *myfemobj = new femobj;
	/// old i/o: from mfem 3.01
	//myfemobj->mesh = new Mesh(nnode, node, ntet, tet, nbnd, bnd, 1, 1);
	/// updated to mfem 3.4.1
	/// the mfem 3.4.1 provide input mesh by array, but the parameters are different
	/// Zhanghong Tang @ 03/12/2019
	//Mesh::Mesh(double *_vertices, int num_vertices,
	//	int *element_indices, Geometry::Type element_type,
	//	int *element_attributes, int num_elements,
	//	int *boundary_indices, Geometry::Type boundary_type,
	//	int *boundary_attributes, int num_boundary_elements,
	//	int dimension, int space_dimension)
	myfemobj->mesh = new Mesh(node, nnode,
		element_indices, Geometry::TETRAHEDRON,
		element_attributes, ntet,
		boundary_indices, Geometry::TRIANGLE,
		boundary_attributes, nbnd,
		3, 3);

	////////////////////////////////////////////////////////////////////////////////////
	/// now the problem is: how to fill material from elepar to every tetrahedron element?
	////////////////////////////////////////////////////////////////////////////////////

	out->obj = myfemobj;
	delete[] element_indices;
	delete[] element_attributes;
	delete[] boundary_indices;
	delete[] boundary_attributes;
}
```

**Comment by tzanio** [comment]
Hi @TangLaoya,

We are always happy to add support for mesh formats that are useful to users, and will certainly consider PRs for Tetgen readers.

If I understand correctly, your question is how to set the element attributes of the volume (tetrahedral) elements?

You can do this with `Mesh::SetAttribute(int elem, int attr)`, see e.g. https://github.com/mfem/mfem/blob/7b0c974fe8591dfd4d421f16c800a9212fb679fe/miniapps/meshing/shaper.cpp#L214-L219

Hope this helps,
Tzanio

**Comment by TangLaoya** [comment]
Dear Tzanio,
Thank you very much for your kindly reply. I think I have already successfully set element attribute in above code when calling 
`new Mesh(node, nnode,
		element_indices, Geometry::TETRAHEDRON,
		element_attributes, ntet,
		boundary_indices, Geometry::TRIANGLE,
		boundary_attributes, nbnd,
		3, 3);
`

As my understanding, the element attribute is element's region number when the domain are divided into different regions with different material proprieties. Now my problem is how to fill every element with the given material parameters according to the element attribute, as shown in above code, the material parameters are given in *elepar.

Thanks,
Tang Laoya

**Comment by tzanio** [comment]
> Now my problem is how to fill every element with the given material parameters according to the element attribute

Can you explain what you mean by "material properties"?

Is this a piecewise-constant coefficient of a bilinear form that has different values in elements with different attributes? If so, take a look at Example 2:

https://github.com/mfem/mfem/blob/7b0c974fe8591dfd4d421f16c800a9212fb679fe/examples/ex2.cpp#L166-L179

**Comment by TangLaoya** [comment]
Dear Tzanio,
Thank you very much for your kindly reply. Suppose I have a domain with 3 regions, numbered 1, 2, and 3. There are 'num_elements' (more than 1 million) elements which are stored in 'element_indices'. Elements' attributes are stored in 'element_attributes', the length of 'element_attributes' is also 'num_elements'. Values of 'element_attributes' are region numbers, 1, 2, or 3. There is also another array 'elepar' stores regions' material properties, size of this array is nregion*4, the context of this array is as follows:
        '/// elepar((i-1)*4): region number 
	/// elepar((i-1)*4+1): permittivity
	/// elepar((i-1)*4+2): conductivity
	/// elepar((i-1)*4+3): permeability'
for example, for this domain with 3 regions, the elepar is as follows:
1 1 0 1
2 3 0.5 1
3 1 0.001 10

Then how to fill these parameters to every element?

Thanks,
Tang Laoya

**Comment by TangLaoya** [comment]
Oh, another issue, the region number could be discontinuous, for example, the region number of 3 regions could be -1 10 2002, but I have a map in the array 'elepar', at this time the array is filled like this:
 -1 1 0 1
10 3 0.5 1
2002 1 0.001 10

Thanks,
Tang Laoya

**Comment by tzanio** [comment]
In this case you can define three`PWConstCoefficient` objects for the permittivity, conductivity and permeability and fill them with the values of the `elepar` array. The region numbers will have to be mapped to positive, consecutive mfem mesh attributes.

**Comment by TangLaoya** [comment]
Ok. I see. So I need to map region number to be positive and continuous again and then do as you suggested. 

Thanks, 
Tang Laoya

**Comment by tzanio** [comment]
Yes, something like:

```c++
// Read in 'elepar'
int attributes[nregion];
Vector permittivity(nregion);
Vector conductivity(nregion);
Vector permeability_inv(nregion);

for (int i = 0; i < nregion; i++)
{
   attributes[i] = elepar[(i-1)*4];
   permittivity(i) = elepar[(i-1)*4+1];
   conductivity(i) = elepar[(i-1)*4+2];
   permeability_inv(i) = 1.0/elepar[(i-1)*4+3];
}

// Replace region numbers with attributes[] when defining MFEM element attribute
// ...

// Define ans use the coefficients
PWConstCoefficient eps(permittivity);
PWConstCoefficient sigma(conductivity);
PWConstCoefficient mu_inv(permeability_inv);

BilinearForm *a = new BilinearForm(fespace);
a->AddDomainIntegrator(new CurlCurlIntegrator(*mu_inv));
a->AddDomainIntegrator(new VectorFEMassIntegrator(*sigma));
```

**Comment by TangLaoya** [comment]
That's great, thank you very much!

Tang Laoya
