### ISSUE TITLE
How to save fields in VTK format?

### ISSUE THREAD

**Issue by ar-valdez** [mfem/mfem#797]
I am a new user of mfem, I have just read the related question #558 therein, where can I find the arguments of the function `PrintVTK()`???

Thanks.-

**Comment by tzanio** [comment]
Hi @ar-valdez,

The arguments are explained here: https://github.com/mfem/mfem/issues/558#issuecomment-408293655

Here is an example of saving a mesh:
https://github.com/mfem/mfem/blob/87f86d45c927ad5fa001a82c96ec29ca0def37ff/miniapps/meshing/mesh-explorer.cpp#L783-L787

And here is an example of saving a mesh with finite element solutions (grid functions) defined on it:
https://github.com/mfem/mfem/blob/e17a73fa8be9242262121bcbbc973e9da59f8354/tests/unit/fem/test_linear_fes.cpp#L172-L174

Please let us know if you have any further questions.
Tzanio

**Comment by ar-valdez** [comment]
Thanks for the answer @tzanio. I will check the arguments of this two functions and let you know if I have future doubts concerning the solution visualization and post-processing.

**Comment by ar-valdez** [comment]
@tzanio  I have been trying to make use of the methods you shared with me before, therein in the example ex1.cpp (the first example) I replace the file stream part see stage 12, with:

`   ofstream omesh("Test.vtk",0); 
   omesh.precision(8); 
   mesh->PrintVTK(omesh); 
   cout << "New VTK mesh file: " << "Test.vtk" << endl;
   x.SaveVTK(omesh,"solution",0);
   cout << "Solution saved in to VTK mesh file: " << "Test.vtk" << endl;
`

And I receive the following compilation error:

`g++  -O3 -I..  Heat.cpp -o Heat -L.. -lmfem -lrt
Heat.cpp: In function ‘int main(int, char**)’:
Heat.cpp:159:31: error: invalid conversion from ‘int’ to ‘std::ios_base::openmode {aka std::_Ios_Openmode}’ [-fpermissive]
    ofstream omesh("Test.vtk",0); 
                               ^
In file included from Heat.cpp:22:0:
/usr/include/c++/5/fstream:697:7: note:   initializing argument 2 of ‘std::basic_ofstream<_CharT, _Traits>::basic_ofstream(const char*, std::ios_base::openmode) [with _CharT = char; _Traits = std::char_traits<char>; std::ios_base::openmode = std::_Ios_Openmode]’
       basic_ofstream(const char* __s,
       ^
makefile:58: recipe for target 'Heat' failed
make: *** [Heat] Error 1
`

Therein How is written the rule to define the 2nd and 3rd argument of the functions PrintVTK and saveVTK?

**Comment by v-dobrev** [comment]
I think the error is from the following part of the line: `ofstream omesh("Test.vtk",0);` -- the second argument is probably not needed, see https://en.cppreference.com/w/cpp/io/basic_ofstream/basic_ofstream (`ofstream` is typdef'd to `basic_ofstream<char>`).

**Comment by ar-valdez** [comment]
@v-dobrev  thanks for your answer, indeed it worked now as expected. The second argument `ofstream omesh("Test.vtk",0);` was not needed.

I followed the available example, in that case you initialize with the second argument.

Anyway it works, thanks for the support.

**Comment by ar-valdez** [comment]
> Hi @ar-valdez,
> 
> The arguments are explained here: [#558 (comment)](https://github.com/mfem/mfem/issues/558#issuecomment-408293655)
> 
> Here is an example of saving a mesh:
> [mfem/miniapps/meshing/mesh-explorer.cpp](https://github.com/mfem/mfem/blob/87f86d45c927ad5fa001a82c96ec29ca0def37ff/miniapps/meshing/mesh-explorer.cpp#L783-L787)
> 
> Lines 783 to 787 in [87f86d4](/mfem/mfem/commit/87f86d45c927ad5fa001a82c96ec29ca0def37ff)
> 
>  const char mesh_file[] = "mesh-explorer.vtk"; 
>  ofstream omesh(mesh_file); 
>  omesh.precision(14); 
>  mesh->PrintVTK(omesh); 
>  cout << "New VTK mesh file: " << mesh_file << endl; 
> And here is an example of saving a mesh with finite element solutions (grid functions) defined on it:
> [mfem/tests/unit/fem/test_linear_fes.cpp](https://github.com/mfem/mfem/blob/e17a73fa8be9242262121bcbbc973e9da59f8354/tests/unit/fem/test_linear_fes.cpp#L172-L174)
> 
> Lines 172 to 174 in [e17a73f](/mfem/mfem/commit/e17a73fa8be9242262121bcbbc973e9da59f8354)
> 
>  mesh.PrintVTK( vtkFs, ref); 
>  scalarGF.SaveVTK( vtkFs, "scalar_gf", ref); 
>  vectorGF.SaveVTK( vtkFs, "vector_gf", ref); 
> Please let us know if you have any further questions.
> Tzanio

@tzanio  I am not able to parse correctly the solution field `x` obtained after doing `a->RecoverFEMSolution(X, *b, x);` (stage 11).

The mesh has 100 nodes, the scalar solution must have 100 dof's. But for some reason more information is passed to `x`. Can you clarify me the content of `x`?
