### ISSUE TITLE
How to use the function 'VectorRestrictedCoefficient' 

### ISSUE THREAD

**Issue by TangLaoya** [mfem/mfem#798]
Dear Mark,
Sorry to bother you again.
In #648 you told me how to assign current source by filling the function JFunc and I have understood, at the same time, you also suggested to use function
'VectorRestrictedCoefficient' when the shape is complex. Could you please give me some examples to show how to use this function to assign current on a complex shape, for example, on an irregular loop with region number (or element attribute) 1, with current density J and direction (Jx, Jy, Jz) at (x, y, z)? 

In addition, can I also use this function to assign material attribution of elements for different regions by this function? How to do?
 
Thanks,
Tang Laoya

**Comment by mlstowell** [comment]
Hello, @TangLaoya ,

If you want to define a current within some regular shape then you can write a function that uses the coordinates to determine if you are inside the region of interest and then returns the value of the current or zero if the coordinates are outside.  If the shape is irregular such a function can be difficult to write.  An alternative is to label the irregular shape with its own attribute number.  The  you can define a `VectorRestrictedCoefficient` which will only be applied your chosen attribute number is found in the present element.  This does not help you determine the value of the current that you should return it only helps to answer the question of wether or not a non-zero current should be returned.  If your shape is irregular and the current density is also irregular then this type of coefficient will not be enough.

Regarding material regions: you may be able to use a PWConstCoefficient to define your material coefficients.  This class can return a different constant value for each element attribute.  See `fem/coefficient.hpp` for more information.

Best wishes,
Mark

**Comment by TangLaoya** [comment]
Dear Mark,
Thank you very much for your kindly reply. Yes, I just need to know how to use 'VectorRestrictedCoefficient ' to filter elements that are in that region of current source. The value and direction of the source of the given point (x,y,z) in known, they are J, (Jx, Jy, Jz). How to filter these elements?
For the 'PWConstCoefficient ', I will try to study at first and if any problem I will ask for your help.

Thanks,
Tang Laoya

**Comment by mlstowell** [comment]
Hello, @TangLaoya ,

To use the `VectorRestrictedCoefficient` you create the object with a `VectorCoefficient` which returns (Jx,Jy,Jz) and an `Array<int>` of length `pmesh->attributes.Max()`.  This array is what we call a "marker array", it contains zeroes for attributes that are set to "off" and ones for those that are "on".  The `Eval` method will use "attribute number - 1" as an index into this array if it finds a 0 it will return a vector of zeroes, if it finds a 1 it will return (Jx, Jy, Jz) from the `VectorCoefficient` that you passed to the constructor.

Best wishes,
Mark

**Comment by TangLaoya** [comment]
Dear Mark,
I am sorry to bother you again but I really don't know how to implement. Suppose there are 4 regions in the whole domain, numbered 1, 2, 3 and 4. Region 1 is the coil where current source is assigned. The mesh and element attribute is know by the following code:
`Mesh *mesh = new Mesh(node, nnode,
		element_indices, Geometry::TETRAHEDRON,
		element_attributes, ntet,
		boundary_indices, Geometry::TRIANGLE,
		boundary_attributes, nbnd,
		3, 3);`


The how to do? Should I write separate function to do this, somewhat like the following function 
`void current_ring(const Vector &, Vector &);`
in tesla.cpp?
`void fillirregularcoil(const Vector &, Vector &)
{
	VectorCoefficient *Current;
	/// how to pass mesh into this function?
	Array<int> marker = Array<int>(mesh->attributes.Max());
	/// suppose region of coil is regcoil, how to pass the region number into this function?
	marker = 0;
	/// should I set the flag like this?
	marker(regcoil) = 1;
	/// what should I do next? 
}
`

Thanks,
Tang Laoya

**Comment by mlstowell** [comment]
Dear, @TangLaoya,
I apologize for not replying sooner.  I don't know how I missed your question, I certainly did not intend to ignore it.

Do you still need help with this or have you found a solution?

Best wishes,
Mark

**Comment by TangLaoya** [comment]
Dear Mark,
Thank you very much for your kindly reply. In fact this problem is still not solved but I am working on another issue. I appreciate you if you can give me an efficient solution.

Thanks,

Tang Laoya
