### ISSUE TITLE
Stokes problem: non-zero Dirichlet boundary conditions for velocity

### ISSUE THREAD

**Issue by rhebergens** [mfem/mfem#80]
Dear all,

I recently started looking at MFEM. To get started with MFEM, I am implementing the Stokes problem starting with Example 5, the Darcy problem. So far I have this working with zero Dirichlet boundary conditions for the velocity, but I am having trouble understanding how to implement non-zero Dirichlet boundary conditions for the velocity. For the zero Dirichlet boundary conditions, I just followed the DPG example and used:

Array<int> ess_bdr(mesh->bdr_attributes.Max());
ess_bdr = 1;   
aVarf->AddDomainIntegrator(new VectorDiffusionIntegrator);
aVarf->Assemble();
aVarf->EliminateEssentialBC(ess_bdr);
aVarf->Finalize();
SparseMatrix &A(aVarf->SpMat());

Now I would like to apply the following 2D velocity boundary condition:

void velocity_bc(const Vector & x, Vector & u)
{
  if (x.Size() == 2)
  {
    double xi(x(0));
    double yi(x(1));
    u(0) =   sin(xi)*cos(yi);
    u(1) = - cos(xi)*sin(yi);
  }    
}

How do I apply this boundary condition to the velocity part of a blockvector where the "block offsets" are given by:

Array<int> block_offsets(3); // number of variables + 1
block_offsets[0] = 0;
block_offsets[1] = Vh_space->GetVSize(); // velocity 
block_offsets[2] = Qh_space->GetVSize(); // pressure
block_offsets.PartialSum();

A similar question was asked here: https://github.com/mfem/mfem/issues/77 which helped for the zero Dirichlet boundary conditions.

Thanks,
Sander

**Comment by v-dobrev** [comment]
Hello Sander,

The first step will be to project your `velocity_bc` to a `GridFunction`:
```c++
GridFunction v(Vh_space);
VectorFunctionCoefficient v_coeff(dim, velocity_bc);
v.ProjectCoefficient(v_coeff);
```
Then, instead of
```c++
aVarf->EliminateEssentialBC(ess_bdr);
```
use [this](https://github.com/mfem/mfem/blob/master/fem/bilinearform.hpp#L253) version of `EliminateEssentialBC`:
```c++
aVarf->EliminateEssentialBC(ess_bdr, v, rhs);
```
This will modify the matrix inside `aVarf` and the `rhs` vector accordingly.

The off-diagonal block of the system, `bVarf` also needs to be modified in a similar way using the methods [`EliminateTrialDofs`](https://github.com/mfem/mfem/blob/master/fem/bilinearform.hpp#L386) and/or [`EliminateTrialDofs`](https://github.com/mfem/mfem/blob/master/fem/bilinearform.hpp#L380) of the `MixedBilinearForm` class.

Regards,
Veselin

**Comment by rhebergens** [comment]
Dear Veselin,

Thank for your response. I implemented your suggestion into the code, but unfortunately I'm still not getting the results I expect. Everything works fine when I have zero Dirichlet boundary conditions.

Would this maybe have to do with me having to set the initial vector equal to the boundary conditions vector? I have my solution block vector:

BlockVector x(block_offsets);
x = 0.0;

and then a call to the solver:

solver.Mult(rhs, x);

I'm assuming that I might need to set the velocity block some how to v?

regards,
Sander

**Comment by v-dobrev** [comment]
Hi Sander,

You can make the `GridFunction` `v` point to the data of the first block of `x`: instead of the definition
```c++
GridFunction v(Vh_space);
```
use this:
```c++
GridFunction v;
v.MakeRef(Vh_space, x.GetBlock(0), 0);
```
The projection part is the same as above. When `rhs` is a `BlockVector`, the elimination part should be
```c++
aVarf->EliminateEssentialBC(ess_bdr, v, rhs.GetBlock(0));
```
-Veselin

**Comment by rhebergens** [comment]
Dear Veselin,

Thanks again for your response. I think it's almost working. What I have now is that with the following line:

bVarf->EliminateTrialDofs(ess_bdr, v, rhs.GetBlock(0));

the solution looks quite bad, but if I comment this line out then the velocity converges suboptimally (pressure doesn't converge). Of course I want to eliminate still the correct columns, so I think I'm doing something wrong here. I looked at the other options for mixed bilinear forms, so 

bVarf->EliminateTestDofs(ess_bdr);
or
bVarf->EliminateEssentialBCFromTrialDofs(ess_bdr, v, rhs.GetBlock(0));

but I don't think either of these should be used for this problem since we want to eliminate the columns, not the rows.

Can you see what I'm missing here?

regards,
Sander

**Comment by v-dobrev** [comment]
Hi Sander,

I think you have a typo in
```c++
bVarf->EliminateTrialDofs(ess_bdr, v, rhs.GetBlock(0));
```
instead of `rhs.GetBlock(0)` you should have `rhs.GetBlock(1)`.

-Veselin

**Comment by rhebergens** [comment]
Hi Veselin,
I think this should be rhs.GetBlock(0) because I'm trying to adjust the velocity boundary conditions while rhs.GetBlock(1) I think modifies the rhs corresponding to the pressure block. I'll keep looking to see if I can find the issue.
regards, Sander

**Comment by v-dobrev** [comment]
Hi Sander,

In `MixedBilinearForm::EliminateTrialDofs`, the size of the second argument, `sol`, needs to be equal to the width of the `MixedBilinearForm`, .i.e. the size of the trial space. The size of the third argument, `rhs`, needs to be equal to the height of the `MixedBilinearForm`, i.e. the size of the test space. Otherwise, the operation does not make sense.

Veselin

**Comment by rhebergens** [comment]
Hi Veselin,
I see what you mean. The solution I'm getting with `rhs.GetBlock(1)` is still incorrect though when using non-zero velocity boundary conditions, so I'm probably making an error elsewhere. I'll keep looking. Thanks.
Sander

**Comment by rhebergens** [comment]
Hi Veselin,

I think I found what is going on. I am currently solving the Stokes equations using the following formulation:

(grad v, grad u) - (div v, p) = (v, f)
-(div u, q) = (q, g)

Looking at the pressure velocity coupling term, its implementation is

`MixedBilinearForm *bVarf(new MixedBilinearForm(Vh_space, Qh_space));`
`bVarf->AddDomainIntegrator(new VectorDivergenceIntegrator);`
`bVarf->Assemble();`
`bVarf->EliminateTrialDofs(ess_bdr, v_boundary, rhs.GetBlock(1));`
`bVarf->Finalize();`
`SparseMatrix & B(bVarf->SpMat());`
`B *= -1.;`
`SparseMatrix *BT = Transpose(B);`

I think that the `B *= -1.;` line is the problem here. My reason to think this is because if I redefine the pressure P = -p and implement 

(grad v, grad u) + (div v, P) = (v, f)
(div u, q) = -(q, g)

where now the pressure velocity coupling term is implemented as

`MixedBilinearForm *bVarf(new MixedBilinearForm(Vh_space, Qh_space));`
`bVarf->AddDomainIntegrator(new VectorDivergenceIntegrator);`
`bVarf->Assemble();`
`bVarf->EliminateTrialDofs(ess_bdr, v_boundary, rhs.GetBlock(1));`
`bVarf->Finalize();`
`SparseMatrix & B(bVarf->SpMat());`
`SparseMatrix *BT = Transpose(B);`

then everything works perfectly. I'm using Taylor-Hood elements (P^2-P^1) and I'm getting rates of convergence of order 3 for the velocity and 2 for the pressure.

I actually want to solve the original formulation though without having to redefine my pressure. I'm assuming that the multiplication of B by -1 is causing trouble somewhere. Do you maybe have a suggestion? Do I need to somehow take care that the boundary conditions in the rhs vector have the correct sign? Does MFEM maybe have a function for this? I saw that for bilinear forms there is the `EliminateEssentialBCFromDofsDiag` function but no such function exists for mixed forms.

regards,
Sander

**Comment by rhebergens** [comment]
Hi Veselin,
I solved my problem.  I simply needed to include the -1 in the mixedform instead of multiplying B by -1, so

`MixedBilinearForm *bVarf(new MixedBilinearForm(Vh_space, Qh_space));`
`ConstantCoefficient m_one(-1.0);`
`bVarf->AddDomainIntegrator(new VectorDivergenceIntegrator(m_one));`
`bVarf->Assemble();`
`bVarf->EliminateTrialDofs(ess_bdr, v_boundary, rhs.GetBlock(1)); `
`bVarf->Finalize();`
`SparseMatrix & B(bVarf->SpMat());`
`SparseMatrix *BT = Transpose(B);`

regards,
Sander

**Comment by v-dobrev** [comment]
Hi Sander,

Good hear you got this working.

It looks like the problem with the previous implementation (where you use coefficient 1 in the `MixedBilinearForm` and then multiply the matrix `B` by -1) is the way the boundary conditions are eliminated. I think that if you move the elimination after switching the sign, `B *= -1.`, then you'll be OK too.

Cheers,
Veselin

**Comment by rhebergens** [comment]
Hi Veselin,
Just tried it out and that works as well - thanks!
regards, Sander

**Comment by CorporalClegg** [comment]
Hi everyone,

I just have similar issues with a "custom example 5". I have modified the Raviart-Thomas FEcollection to a "classical" H1_FECollection one, because I would like to have more controls on the BC and use a custom ViscosityIntegrator (which look like ElasticityIntegrator).
So I try to solve
```
    /// ###########################
    /// # Define the block Matrix #
    /// ###########################
    ///
    ///    D = [ K       Q      ]
    ///        [ Qt  -M/(KK/dt) ]
```
I try to have a prescribed velocity on the "right" side of the beam-hex.mesh of "-1" in the x direction, while the "left side" has prescribed velocity of  0 in the x, y, z direction. I manage to isolate all the concerning dofs in a ``bool_v_ess_dofs`` (which have the size of ``u`` and contains 1 if the dof is fixed) and in a ``v_ess_dofs`` which is a simple list of fixed dofs. I have edited the ``u`` GridFunction with corresponding BC.

```c++
    /// ##########################
    /// # K (viscosity operator)            #
    /// ##########################
    const int skip_zero_entries = 0 ;
    Vector visc_vector( mesh->attributes.Max() ) ;
    visc_vector = 0.0 ;
    visc_vector[0] = visc_top ;
    PWConstCoefficient visc_coeff( visc_vector ) ;
    BilinearForm * k_bil = new BilinearForm( h1_fespace ) ;
    k_bil->AddDomainIntegrator( new ViscosityIntegrator( visc_coeff ) ) ;
    k_bil->Assemble(skip_zero_entries) ;
    k_bil->EliminateVDofs(v_ess_dofs) ;
    k_bil->Finalize(skip_zero_entries) ;
    SparseMatrix &K(k_bil->SpMat());

    /// ######################
    /// # Q (Mixed operator)       #
    /// ######################
    ConstantCoefficient minus_constant_coeff(-1.) ;
    MixedBilinearForm * q_mixbil = new MixedBilinearForm( h1_fespace, l2_fespace ) ;
    q_mixbil->AddDomainIntegrator(new VectorDivergenceIntegrator(minus_constant_coeff)) ;
    q_mixbil->Assemble(skip_zero_entries) ;
    q_mixbil->EliminateEssentialBCFromTrialDofs(bool_v_ess_dofs,u,rhs.GetBlock(1)) ;
    q_mixbil->Finalize(skip_zero_entries) ;
    SparseMatrix & Q(q_mixbil->SpMat());
//    Q *= -1.;
    SparseMatrix *QT = Transpose(Q);

    /// #####################
    /// # M (Mass operator) #
    /// #####################
    BilinearForm * m_mixbil = new BilinearForm( l2_fespace ) ;
    m_mixbil->AddDomainIntegrator(new VectorMassIntegrator(constant_coeff)) ;
    m_mixbil->Assemble() ;
    m_mixbil->Finalize() ;
    SparseMatrix &M(m_mixbil->SpMat()) ;
    M*=(-1./(KK*dt)) ;
```

My right hand side is, in first approach, null everywhere. I have no boundary condition for the pressure maybe it can be a problem ? I think there is a problem because when I want to visualize the output with ``glvis -m folding.mesh -g sol_u.gf -gc 0`` (to see the velocity in the x direction), I observe this 

![screenshot from 2017-01-24 11 18 52](https://cloud.githubusercontent.com/assets/11282274/22241157/89e0c26c-e21e-11e6-9898-b5e8fd313b81.png)

The velocity is not equal to -1 on the right side.
Am I doing this wrong ?

Thank you in advance,

**Comment by juan42** [comment]
You don't have any boundary values prescribed for the velocity in your operator K. If the rhs is 0 on every velocity dof, you just prescribe 0. It looks like you are setting pressure boundary values with
```
    q_mixbil->EliminateEssentialBCFromTrialDofs(bool_v_ess_dofs,u,rhs.GetBlock(1)) ;
```

**Comment by CorporalClegg** [comment]
Hi Juan,

Thank you for your answer.

I do not well understand your answer

My K operator is build using a FESpace build with an ``H1_FECollection`` . The GridFunction ``u`` is defined using the same FESpace, so when I eliminate the Vdofs, it affects the matrix K.

For my Q operator, the FEspace build with ``H1_FECollection`` is the trial space while the one build with ``L2_FECollection`` is the test space.

So when I call
``c++
    q_mixbil->EliminateEssentialBCFromTrialDofs(bool_v_ess_dofs,u,rhs.GetBlock(1)) ;
``
``u`` is the velocity on every dofs and ``rhs.GetBlock(1)`` is the rhs matching with the pressure, is it wrong to do this like this ?

Thank you again,

**Comment by juan42** [comment]
I reviewed a test code of mine and i'm doing nearly the same thing there.
```
  FiniteElementCollection *vel_fecoll(new H1_FECollection(2, dim));
  FiniteElementCollection *pres_fecoll(new H1_FECollection(1, dim));

  FiniteElementSpace *V_space = new FiniteElementSpace(mesh, vel_fecoll, dim);
  FiniteElementSpace *Q_space =
      new FiniteElementSpace(mesh, pres_fecoll, dim - 1);

  Array<int> block_offsets(3); // number of variables + 1
  block_offsets[0] = 0;
  block_offsets[1] = V_space->GetVSize();
  block_offsets[2] = Q_space->GetVSize();
  block_offsets.PartialSum();

  Array<int> ess_bdr(mesh->bdr_attributes.Max());
  ess_bdr = 1;
  Array<int> ess_dof;
  V_space->GetEssentialVDofs(ess_bdr, ess_dof);

  ConstantCoefficient k(0.0);
  VectorFunctionCoefficient bdr_vcoeff(dim, vel_lid_fun);

  BlockVector x(block_offsets), rhs(block_offsets);

  GridFunction x_bdr;
  x_bdr.MakeRef(V_space, x.GetBlock(0), 0);
  x_bdr.ProjectCoefficient(bdr_vcoeff);

  BilinearForm *aVarf(new BilinearForm(V_space));
  MixedBilinearForm *bVarf(new MixedBilinearForm(V_space, Q_space));

  aVarf->AddDomainIntegrator(new VectorDiffusionIntegrator());
  aVarf->Assemble();
  aVarf->EliminateEssentialBC(ess_bdr, x_bdr, rhs.GetBlock(0));
  aVarf->Finalize();

  ConstantCoefficient minus_one(-1.0);
  bVarf->AddDomainIntegrator(new VectorDivergenceIntegrator(minus_one));
  bVarf->Assemble();
  bVarf->EliminateTrialDofs(ess_bdr, x, rhs.GetBlock(1));
  bVarf->Finalize();
```

So maybe something is wrong with your custom integrator?

**Comment by CorporalClegg** [comment]
Hi Juan,

I have managed to solve the problem. The fact was I have inverted two matrices in the block matrix... Next time I will test with the DEBUG flags on ! Now (I think) it works like a charm. (but the solving takes a long time with bigger mesh...).

Other mistake I made was to use ``  aVarf->EliminateEssentialBC(ess_bdr);`` instead of ``  aVarf->EliminateEssentialBC(ess_bdr, x_bdr, rhs.GetBlock(0));`` in your example.

Thank you for your answer !

**Comment by Hemanta822** [comment]
Hello All,

I am new to MFEM and I am trying to change example 5 to Stokes problem. I have been trying to impose a non-homogeneous Dirichlet boundary for the Stokes velocity using Tayloor-Hood elements. I got similar issue as discussed above (Getting optimal convergence rates for the velocity but flat errors for pressure). Following attached is the figure of pressure profile in star mesh. Looking at the figure it seems there is some problem at the sharp vertices of the star mesh. I would greatly appreciate your kind help. Thank you!  


<img width="1190" alt="Screenshot 2024-07-19 at 12 57 02 PM" src="https://github.com/user-attachments/assets/5feb3212-9a45-41e6-9eb0-5faec147e9b5">
