### ISSUE TITLE
How to impose Dirichlet boundary condition at right hand side

### ISSUE THREAD

**Issue by tangqi** [mfem/mfem#806]
Consider a time dependent problem and there are explicit parts and source terms as RHS. How could I impose Dirichlet boundary condition at RHS?

Currently, `MyOperator::Mult` looks like
```c++
   Nv->Mult(w, z); //advection
   if (viscosity != 0.0)
   {
      DRe.AddMult(w, z); //diffusion
   }
   z.Neg();
   for (int i=0; i<ess_tdof_list.Size(); i++)
       z(ess_tdof_list[i])=0.0; //set Dirichlet condition by hand
```
It seems working so far. But I guess there should be a better way...

Thanks,
Qi

**Comment by mlstowell** [comment]
Hello, @tangqi ,

We're going to need a little more information.  Is `MyOperator::Mult` a `TimeDependentOperator::Mult` method for use in an explicit ODE solve?  What spaces do `w` and `z` belong to?

Best wishes,
Mark

**Comment by tangqi** [comment]
@mlstowell Thanks for replying. Yes, it is a `TimeDependentOperator::Mult` and used for an explicit ODE solve. w and z are all H1. So I believe the solver enforces the boundary condition strongly. I also have some source terms as `LinearForm`.

**Comment by mlstowell** [comment]
Hi, @tangqi ,

In that case your ODE solver expects the vector produced by this method to be a `primal vector` like `w` and not a `dual vector` like `z`.  If these terms are unfamiliar see https://mfem.org/pri-dual-vec/ for MFEM's definitions of such things.  The end result is that you should perform a solve, using a mass matrix, to convert the `dual vector`, `z`, into a `primal vector`, call it `y` perhaps.  The Dirichlet boundary condition should then be imposed during this solve.
``
HypreParMatrix M;
Vector Z, Y;
y = 0.0; // Set Dirichlet values in solution vector
m->FormLinearSystem(ess_tdof_list, y, z, M, Y, Z); // Alters matrix and rhs to enforce bc
CG(M, Z, Y); // Compute Y = M^{-1}Z
m->RecoverFEMSolution(Y, z, y);
``
Similar solves are performed in most of the low-numbered example codes so you can look at these to see how to use a preconditioner if desired.  The source terms which you compute as `LinearForms` should simply be added to `z` before the call to `FormLinearSystem`.

Best wishes,
Mark

**Comment by tangqi** [comment]
@mlstowell Thanks again! It works very well. But do I need `FormLinearSystem` each time step even if both my mass matrix and preconditioner are fixed? 

PS, this seems give me the correct answer
```c++
for (int i=0; i<ess_tdof_list.Size(); i++)
   z(ess_tdof_list[i])=0.0; //set Dirichlet condition by hand
M_solver.Mult(z, dwdt);
```

**Comment by mlstowell** [comment]
Hello, @tangqi ,

I'm glad this is helping.  You make a good point.  If the matrix remains the same and you have a homogeneous Dirichlet BC then `FormLinearSystem` is only needed at the first time step.  After that you only need to make sure the appropriate values in `z` are still zero.  If your BC is not homogeneous then you need to modify the rhs using the matrix and the Dirichlet values.  If you ever need this it can be done with `BilinearForm::EliminateEssentialBC` after a call to `BilinearForm::FormLinearSystem` or `BilinearForm::FormSystemMatrix`.

Best wishes,
Mark

**Comment by tangqi** [comment]
Thanks! I was confused by `EliminateEssentialBC` when I was reading some examples. Your explanation is very helpful. --Qi
