### ISSUE TITLE
AMR on periodic meshes

### ISSUE THREAD

**Issue by tangqi** [mfem/mfem#809]
Hi,

I am testing my mesh with ex6. My mesh is periodic in x and Dirichlet in y, which was modified from periodic-square.mesh. See https://github.com/mfem/mfem/blob/tds-mhd-dev/miniapps/mhd/xperiodic-square.mesh 
But `x.ProjectBdrCoefficient(zero, ess_bdr)` gives me issues. It looks like `Nodes->FESpace()->GetBE(i)` in `Mesh::GetBdrElementTransformation` is null. 

A similar mesh is working in https://github.com/mfem/mfem/issues/807. So let me know what I am missing. Thanks!

Qi

**Comment by jakubcerveny** [comment]
I checked the mesh and it seems OK (it even works in `ex1`). 

The problem is that `ProjectBdrCoefficient` calls `FiniteElementSpace::GetBE` on the `L2_T1_2D_P1` nodal space. `GetBE` tries to obtain the segment FE, which is NULL in `L2_FECollection` in 2D. 

To me it looks like a bug. Either `GetBE` should try to obtain the trace finite element (which is defined), or the regular segment FE should be defined in `L2_FECollection`. Which of the two is correct, @v-dobrev, @tzanio ?

**Comment by v-dobrev** [comment]
I think this is caused by the same problem as in #735.

The solution is to implement `Mesh::GetBdrElementTransformation` for meshes with discontinuous nodes - similar to `Mesh::GetFaceTransformation`.

I'll make a branch with the fix and post here when it's ready.

**Comment by v-dobrev** [comment]
@tangqi,

Here is the branch with the fix: https://github.com/mfem/mfem/tree/periodic-mesh-bdr-transform-fix (PR #811).

Give it a try and let me know if you encounter any issues.

**Comment by tangqi** [comment]
@v-dobrev Thanks a lot for the help. The first issue has been well resolved. 

Hi @jakubcerveny I tested ex6 on this mesh. The exact solution is just a quadratic function, which should be a very simple case. But it seems there is something wrong with AMR, maybe with the error estimator. 

If I use P1, it works well and the mesh is refined exactly as what I expect:
![coaseO1](https://user-images.githubusercontent.com/1406660/54968928-0281af00-4f42-11e9-8b54-2de7b47c1d18.png)
At a given AMR iteration, note that the refinement is only along the y direction. It appears to be that way all the time.

However, if I use P2 and starts with a coarse mesh (3x3), it behaves strangely:
![coarseO2first](https://user-images.githubusercontent.com/1406660/54969058-7cb23380-4f42-11e9-8b70-94dd023b5a76.png)

Eventually, the solution becomes off
![coarseO2](https://user-images.githubusercontent.com/1406660/54969066-863b9b80-4f42-11e9-886d-8768f1a49294.png)

If starting with a refined mesh, it is better, albeit still strange:
![fineO2](https://user-images.githubusercontent.com/1406660/54969164-c9960a00-4f42-11e9-94fd-7400299465bf.png)

The increase of dof is very slow in each iteration. So the algorithm is very inefficient. To me, there may be something wrong with error estimator.  -Qi

**Comment by v-dobrev** [comment]
Hi @tangqi,

I think the "issue" is that, with P2 elements, the approximate solution is actually the exact solution and so all error estimates are 0 up to round-off. That is probably the reason for the random refinements - example 6 does not check if the errors are small. You can add a check for that by adding
```c++
   refiner.SetTotalErrorGoal(1e-8);
```
after line 135 in `ex6.cpp`.

Another option could be to use an exact solution that is not in the discrete solution space, e.g. `sin(pi*y)`.

**Comment by tangqi** [comment]
Oops, I was being dumb. Thanks for your explaining.... -Qi

**Comment by v-dobrev** [comment]
If the mesh is periodic across a boundary (e.g. top and bottom in your example) then the periodic boundary is treated as any internal interface and so any hanging nodes on one of the sides will be constrained by the other (master) side.

**Comment by IhCosmo** [comment]
Thank you,

So I don't have to worry about that, right?

**Comment by v-dobrev** [comment]
> Thank you,
> 
> So I don't have to worry about that, right?

Yes, if everything in MFEM works as expected. 🤞 😁
