### ISSUE TITLE
How to implement Lagrange multipliers method?

### ISSUE THREAD

**Issue by hillyuan** [mfem/mfem#810]
Lagrange multipliers method introduce dofs belong to constraints other than any mesh component.  I am wondering if there are any means to define such dofs in MFEM.

**Comment by v-dobrev** [comment]
Currently, all dofs in a `mfem::FiniteElementSpace` are associated with a mesh entity (vertex, edge, face, volume). One approach for adding non-local dofs to a system could be to use a custom bilinear form class that adds such dofs on top of a `mfem::FiniteElementSpace`.

**Comment by tzanio** [comment]
You can also view our implementation of hybridization as a case of imposing Lagrange multipliers. See https://arxiv.org/abs/1801.08914.
