### ISSUE TITLE
Neumann Boundary Condition for Electromagnetic Diffusion Problem(ex3.cpp)

### ISSUE THREAD

**Issue by mortezah** [mfem/mfem#812]
I am trying to generalize ex3.cpp for electromagnetic diffusion problem  `Curl Curl E + E = f` and I need to specify Neumann boundary conditions on some of the boundaries as follows

`Curl E x N = g`

where `N` is the surface normal and `g` is a user-defined vector function.

In the example code (ex3.cpp) all the boundaries are Dirichlet (i.e., `ExN=0`), and I would like to know how to implement the above Neumann boundary condition on top of that.

**Comment by mlstowell** [comment]
Hello, @mortezah ,

Inhomogeneous Neumann boundary conditions can be applied by adding the appropriate surface integral to the right-hand-side vector.  In this example you'll need to add a line near line 125 of ex3.cpp similar to the following:
```
b->AddBoundaryIntegrator(new VectorFEBoundaryTangentLFIntegrator(CurlECoef));
```
or
```
b->AddBoundaryIntegrator(new VectorFEBoundaryTangentLFIntegrator(CurlECoef), nbc_marker);
```
In either case `CurlECoef` is a `VectorCoefficient` which returns the desired value for `Curl E`, the `x N` is handled inside the integrator.  The `nbc_marker` in the second option is an `Array<int>` which controls which portions of the boundary should use this boundary condition.

Best wishes,
Mark

**Comment by mortezah** [comment]
Thanks, @mlstowell for the pointers. That solved my problem. I am closing this issue.

**Comment by mortezah** [comment]
I am reopening this issue since I have a question related to the same topic.

I am trying to generalize the example by adding adaptivity. Do I need to update any of the information related to the boundary conditions after I adapt the mesh? If yes, how can I achieve that, especially for the Neumann boundary conditions?

For my adaptive loop, I am using the same loop in `exp6.cpp` (https://github.com/mfem/mfem/blob/ea9aecce9551f0bfb0e9857a641312f027f06d00/examples/ex6.cpp#L140) with the only difference that I am using an external library (PUMI) to do the adaptation. My code fails at the following line after the mesh is adapted 

`b.Assemble();`

with the following error message

`
Assertion failed: (bdr_marker.Size() == bdr_attr_marker.Size()) is false:                                                                                           --> invalid boundary marker for boundary integrator #0, counting from zero                                                                                ... in function: void mfem::LinearForm::Assemble()
... in file: /users/hakimm2/SCOREC/mfem/fem/linearform.cpp:119
`

I am guessing this is because I may need to update `nbc_marker` (see @mlstowell comment above) after the mesh changes. Any help/insight into this is appreciated.

**Comment by v-dobrev** [comment]
This indicates that the boundary attributes have changed after the refinement - this should not happen. This may be an issue in the MFEM <--> PUMI interface. Maybe @KazemKamran or @cwsmith can comment on this - I'm not sure what happens with the boundary attributes when the mesh is converted from MFEM to PUMI and back from PUMI to MFEM.

**Comment by KazemKamran** [comment]
@mortezah Any process that you do before meshAdapt to apply boundary condition, you should repeat after meshAdapt.  For complicated geometries there is an example that shows the usage of reverse classification to apply boundary condition attribute ( https://github.com/mfem/mfem/blob/master/examples/pumi/ex2.cpp#L176).

**Comment by mortezah** [comment]
Thanks, @v-dobrev, and @KazemKamran for the inputs. I was able to get a working adaptive workflow for ex3.cpp.
