### ISSUE TITLE
Question on degree of freedom ordering and permutations

### ISSUE THREAD

**Issue by tuckerbabcock** [mfem/mfem#814]
I'm trying to add a new finite element collection to add a new element type. I'm wondering if my new collection needs to implement `DofOrderForOrientation`, and if so what it is used for. I see it is used in node reordering, but I'm not sure why this ordering needs to be explicitly defined.

Thanks!

**Comment by jakubcerveny** [comment]
I'm afraid this is necessary. The order for orientation is used in places like `FiniteElementSpace::GetElementDofs`, where the edges/faces are oriented in such a way that the shape functions match between neighboring elements.

**Comment by tzanio** [comment]
Can you share what type of element you are adding? Does it really belong in a collection, i.e. is the trace of the 3D version of the element on element faces related to the 2D version of the element?

**Comment by jehicken** [comment]
I will answer this for Tucker.  I asked him (and three other students) to add summation-by-parts collocation operators to MFEM as part of a class assignment for Prof. Shephard.  They are starting with 2D PDEs; however, to answer your question, for the particular "elements" we are interested in, the 3D operator trace can be represented using collocation nodes (basically cubature nodes) that are coincident with the 2D operators' collocation nodes.  Similarly, the trace of the 2D operators are LGL cubature nodes.

Does that answer your question?

We were interesting in knowing if `DofOrderForOrientation` was needed only for specific use cases (e.g. face integrals in DG schemes) or more generally.  Sounds like the answer is, more generally.

**Comment by v-dobrev** [comment]
If I understand you correctly, you want scalar C^0 elements that use Gauss-Lobatto nodes as degrees of freedom. If that is the case, these are already available using `H1_FECollection`, e.g. see `ex1.cpp`. Or am I missing something?

**Comment by jehicken** [comment]
That is what we would use for tensor-product elements, but do you have an analog to Gauss-Lobatto nodes for triangles?  (Without using a collapsed edge quads.)  The cubature should also be 2p exact for a degree p operator, have all positive weights, and be symmetric.

**Comment by v-dobrev** [comment]
For triangles and tets, I am not aware of a family of quadrature rules that can be uses as nodes for a finite element. Do you know of any such family?

**Comment by v-dobrev** [comment]
The bases we use for triangles and tets, reduce to the 1D Gauss-Lobatto points on the edges (for the default `BasisType` used in `H1_FECollection`).

**Comment by jehicken** [comment]
> I am not aware of a family of quadrature rules that can be uses as nodes for a finite element
Neither am I, but these SBP operators do not need an explicit basis, so they are not quite finite elements.  All we need is the quadrature rule with positive weights; the downside is we need more degrees of freedom per element than a total degree p basis, but we get other things that make the tradeoff attractive.

**Comment by v-dobrev** [comment]
I am not familiar with the "not quite finite elements" that you are referring to, so I cannot really say what will be an easy way to add them to MFEM.

However, going back to the original question: if these elements are similar to scalar C^0 elements, then the code defining the arrays `SegDofOrd`, `TriDofOrd`, and `QuadDofOrd` in class `H1_FECollection` (these are the arrays returned by the method `DofOrderForOrientation` in that class) can probably be re-used (or adapted) for the elements you are implementing. The code where these arrays are generated is in the constructor of `H1_FECollection`. If you are implementing only 2D elements, you only need to define the `SegDofOrd` array.

**Comment by jehicken** [comment]
Ok, great.  Thank you for taking the time to answer our questions.

If you are curious, here are a couple papers on the "not quite finite elements":
[https://www.sciencedirect.com/science/article/pii/S002199911730400X](https://www.sciencedirect.com/science/article/pii/S002199911730400X)
[https://www.sciencedirect.com/science/article/pii/S0021999117308999](https://www.sciencedirect.com/science/article/pii/S0021999117308999)

**Comment by tuckerbabcock** [comment]
I have a follow up question regarding node ordering. Would an ordering like this: 
![mfem_indices_p3](https://user-images.githubusercontent.com/19217934/55766452-c4f14b80-5a42-11e9-8dc0-ad2807c21fc6.png) be allowed? I see that the ordering for the H<sup>1</sup> triangle would have the edge nodes ordered counterclockwise sequentially. My understanding of the `SegDofOrd` array is that it should allow non sequential orderings like the one I've shown. I believe the ordering array for the above image  would be `[1, 0, 2]` and `[2, 0, 1]` in the reverse orientation, but this ordering seems to not work.

Thanks! Tucker

**Comment by jakubcerveny** [comment]
I may not be the best person to answer this (I've never defined a new finite element in MFEM), but from what I understand, the purpose of `SegDofOrd` is to define two DOF orderings corresponding to the two possible orientations of an edge. The only goal is to be able to glue together two neighboring elements correctly (one of them will need to use the reverse ordering on the common edge).

I believe that to get a special ordering (not just a reversal along an edge) of the shape functions themselves, you need to go deeper and define your own `H1_SegmentElement` where `CalcShape` will give you the shapes in the order you want. In the finite element collection, `SegDofOrd` will still perform its unambitious reversal needed to match edge DOFs of two neighbors, regardless of what the shapes actually look like.

**Comment by jakubcerveny** [comment]
On second thought, reordering the edge shapes *should* be possible with `SegDofOrd`. Maybe it's not enough, maybe the ordering within `H1_TriangleElement` would also need to change? (Here I don't understand the `Ti` matrix, is it something similar to `dof_map` in `TensorBasisElement`, @v-dobrev?)

**Comment by vikramsg** [comment]
I am not sure if SBP operators even exist for tets, but I would be very interested is these were implemented for triangles. I have been using tensor product elements using Gauss Lobatto points for getting quads and hexes to be SBP in DG_FECollection.

**Comment by jehicken** [comment]
SBP operators do exist for tets, as long as you are willing to tolerant
more nodes than necessary for a total degree p basis.  We plan to implement
diagonal-norm/mass matrix triangle and tet SBP operators in MFEM over the
summer.

**Comment by vikramsg** [comment]
Thanks. I will be following this development with interest.

**Comment by tuckerbabcock** [comment]
@jakubcerveny I don't think a `SegmentElement` is required, since I modified `FiniteElementForGeometry(Geometry::Type GeomType)` in my new FiniteElementCollection to error if the input was anything other than a triangle, and this works without issue for example 1. When I ran a test case with non-zero Dirichlet boundary conditions I did need a `SegmentElement`, for which I used the existing `H1_SegmentElement` for the lower order SBP cases, since their segment ordering scheme is sequential. For the ordering I've shown I'll have to modify the segment element to be consistent with the above ordering (which I have not yet done). I still don't think this is the problem though, since a segment element was never "asked for" in example 1, and I still had trouble with the above ordering. Regarding the Ti matrix, I'm not exactly sure what it is either, but I didn't construct T since the SBP operators so not have an explicit basis.

**Comment by v-dobrev** [comment]
Hi @tuckerbabcock, I think the ordering you want to use should work. The `SegDofOrd` array for that case should be:
```c++
   // Orientation 0 is just the identity:
   SegDofOrd[0][0] = 0;
   SegDofOrd[0][1] = 1;
   SegDofOrd[0][2] = 2;

   // Orientation 1 tells mfem how to flip the dofs on the edge:
   SegDofOrd[1][0] = 0;
   SegDofOrd[1][1] = 2;
   SegDofOrd[1][2] = 1;
```
As @jakubcerveny suggested, for consistency with this triangle element, you will probably need to define a respective edge element for use in your `FiniteElementCollection`. The difference with the default `H1_SegmentElement` will be just in the ordering of the degrees of freedom and their respective basis functions. The ordering used by `H1_SegmentElement` is:
```ascii
(0)--(2)---(3)---(4)--(1)
```
and in your case it will be
```ascii
(0)--(3)---(2)---(4)--(1)
```
I'm not certain this is absolutely necessary, however, if you need to perform any boundary (i.e. edge) integration or projection (e.g. for Neumann or Dirichlet b.c.), then you definitely will need to define the respective edge element.

**Comment by tuckerbabcock** [comment]
Okay, I'll work on implementing this and let you know if more questions arise. Thanks for the taking the time to answer!

**Comment by tzanio** [comment]
@tuckerbabcock, were you able to make this work?

**Comment by tuckerbabcock** [comment]
Yes! I just was able to implement this. I needed to define a new segment element to be consistent with the ordering, and had misunderstood how to use the `SegDofOrd` array, but now things are working. Thank you so much @tzanio , @v-dobrev, and @jakubcerveny for your detailed replies, I really appreciate the help.
