### ISSUE TITLE
ExchangeFaceNbrData for Raviart Thomas Spaces

### ISSUE THREAD

**Issue by pratyuksh** [mfem/mfem#830]
Hello

I am trying to assemble a flux operator on the interior faces for the Raviart-Thomas spaces. The serial version works correctly. However, I am having issues working with the parallel version.

After some debugging I found that there is some problem with _ExchangeFaceNbrData_
called by R_space, inside the class ParBilinearForm.

As a simple test, I called _ExchangeFaceNbrData_ separately, say after initializing the R_space. But I noticed that calling _GetFaceNbrVSize()_ returns "no. of neighbour dofs" values which are different than when it is being called inside the class ParBilinearForm.

The pfespace is not modified at any point in the code explicitly. So, should one not get the same number of "no. of neighbor dofs" in both cases? If anybody has an idea what could be the problem, please let me know? Thanks!

**Comment by v-dobrev** [comment]
I don't understand - can you be more specific: how do you get the two different values from `GetFaceNbrVSize()`? What are these two different values?

**Comment by pratyuksh** [comment]
@v-dobrev Sorry for being unclear. 

I will explain the problem using an MFEM example itself:

Consider ex5p, I simply insert the snippet:
"""
MPI_Barrier(MPI_COMM_WORLD);
cout << myid << "\t" << R_space->GetFaceNbrVSize() << endl;
R_space->ExchangeFaceNbrData(); //exchange face info
cout << myid << "\t" << R_space->GetFaceNbrVSize() << endl;
"""

at two different positions in the example:

1) after setting up the R_space at the end of step 6.
2) in step 10, after assembling the mass matrix M.

I run the example as: mpirun -np 2 ./ex5p -o 0 -m ../data/square-disc.mesh

In case 1), the snippet prints:
0	-1
1	-1
0	612
1	612

and in case 2), I get:
1	-1
0	-1
1	342
0	522
Additionally, in case 2) the linear solver also does not converge, as if the data has been corrupted.

**Comment by pratyuksh** [comment]
@tzanio Were you able to have a look at this? Thanks.

**Comment by pratyuksh** [comment]
Hello, I think I figured out the problem. There is bug in the _ExchangeFaceNbrData_ in pfespace.cpp:

local dofs indices are obtained using the GetVDofs() function, which are used by ldof_marker. But of course local dof index can be negative for the R_space, leading to invalid memory access for the ldof_marker.

**Comment by v-dobrev** [comment]
Hi @pratyuksh,

Thanks for tracking down this issue! Were you able to fix it and get you code working?

If not, I can create a branch with a fix and it will be great if you can test it in your code.

**Comment by pratyuksh** [comment]
Hello @v-dobrev , I was able to fix my code and get it working.

**Comment by pratyuksh** [comment]
Additionally, I have added some more routines (and will add more) in MFEM files. Is it possible to create a new branch, where I can add these changes? I would like to use this custom version on a cluster later on. Thank you.

**Comment by v-dobrev** [comment]
Hi @pratyuksh, I sent you an invitation that should let you create a branch with your work. When you are ready, you can open a pull request.

**Comment by pratyuksh** [comment]
Hi @v-dobrev I have created a new branch vfe-dev (Vector Finite Element). I will work with this branch and add more routines/fixes that I think would be useful from my work. Is that okay?

I have added the fix we discussed above to this new branch.

**Comment by tzanio** [comment]
Discussion to continue in the PR.
