### ISSUE TITLE
Should the version of Hypre be bumped for MFEMv4.0?

### ISSUE THREAD

**Issue by rcarson3** [mfem/mfem#831]
Currently in MFEM's INSTALL file, the Hypre version used is shown to be 2.10.0b. I've noticed that by building off the newest version of Hypre (v2.16.0) for my miniapp #722, I've been able to see roughly a %15 performance boost on simulations with 250k+ linear hex elements without any other changes made to the code. I haven't run anything smaller yet, so I can't speak on smaller mesh sizes. 

Since I know a version bump is coming for MFEM,  I was wondering if this might also be a good time to look into bumping the version of Hypre to something between v2.10.0b and v2.16.0 in order to take advantage of some of the optimizations that have been introduced into the library.

**Comment by sshiraiwa** [comment]
Can someone please guide me to 2.16 download? https://github.com/LLNL/hypre/releases
shows only 2.15.1….

**Comment by rcarson3** [comment]
It's not up on the LLNL repository yet. I found it on the Hypre team's Github page for Hypre: [https://github.com/hypre-space/hypre](https://github.com/hypre-space/hypre). So, I'm not too sure if they've got some more testing before pushing it to the LLNL repository...

**Comment by v-dobrev** [comment]
The version used in the INSTALL is just for illustration. Most users probably just grab the latest version - at least that is what I'd typically do.

**Comment by sshiraiwa** [comment]
I see. Thank you so much.

**Comment by rcarson3** [comment]
@v-dobrev if that's the case would it be a good idea then to modify the defaults.mk file so that the Hypre directory just points to a hypre folder without a version specified in the directory name rather than one with a specified version name?

So, we would have something like:
```
HYPRE_DIR = @MFEM_DIR@/../hypre/src/hypre
```
rather than it's current value of:
```
HYPRE_DIR = @MFEM_DIR@/../hypre-2.10.0b/src/hypre
```

**Comment by v-dobrev** [comment]
I don't really see what difference that will make, but I'm not against the change.

**Comment by rcarson3** [comment]
It probably doesn't make much of a difference. However, I feel it could make things just a bit smoother for those just starting out with MFEM if the INSTALL file is also updated to tell people to just git clone the LLNL repository of Hypre that way they're also using the latest version of Hypre. 

I know as someone who was a new user of MFEM not too long ago I just downloaded the version listed in the INSTALL file and used that for quite a while just because I initially wasn't familiar with Hypre and didn't know if future versions broke things within MFEM.

**Comment by v-dobrev** [comment]
I see. I can make a branch+PR with these changes, unless you want to do it.

**Comment by tzanio** [comment]
@rcarson3, I think that's a good idea. We just need to run all tests to make sure there are no issues.

**Comment by rcarson3** [comment]
Alright @tzanio and @v-dobrev I can just make the branch+PR with the changes. It shouldn't take too long to do at all.

**Comment by rcarson3** [comment]
@v-dobrev I'm currently running into some issues with Github no longer recognizing my ssh key.... It'll probably take me longer to debug all of this then it would take you to create a branch+PR.

**Comment by v-dobrev** [comment]
Okay, no rush.

**Comment by rcarson3** [comment]
I'm going to go ahead and close this issue, since we now have the PR open.
