### ISSUE TITLE
When should we use Trans.Loc1.Transf and when should we use Trans.Face?

### ISSUE THREAD

**Issue by rhebergens** [mfem/mfem#84]
Hello,

We want to implement an HDG method for the Poisson equation in MFEM. For this we have some questions about how element/face transformations are handled. In particular, when to use IsoparametricTransformation or simply Transform. Consider bilininteg.cpp:

In NormalTraceJumpIntegrator, line 2326, we see `Trans.Loc1.Transf.SetIntPoint(&ip);` and in line 2327, the normal is computed using `CalcOrtho(Trans.Loc1.Transf.Jacobian(), normal);`

In TraceJumpIntegrator, line 2236, we see `Trans.Face->SetIntPoint(&ip)` and in DGDiffusionIntegrator, line 2025, the normal is computed using `CalcOrtho(Trans.Face->Jacobian(), nor);`

When should we use Trans.Loc1.Transf and when should we use Trans.Face?

Any help is very much appreciated.

regards,
Sander and Tamas

**Comment by v-dobrev** [comment]
Hi Sander, Tamas,

The calls in `DGDiffusionIntegrator`:
```c++
Trans.Face->SetIntPoint(&ip);
CalcOrtho(Trans.Face->Jacobian(), nor);
```
compute the scaled normal vector in _physical_ (not reference) space. The scaling is such that the length of `nor` is the same as `Trans.Face->Weight()` which is the weight factor coming from the change of the variables in the face integral from physical to reference space. For example in 3D, `nor` is just the cross product of the two columns of the 3x2 Jacobian matrix.

On the other hand, the calls in `NormalTraceJumpIntegrator`:
```c++
Trans.Loc1.Transf.SetIntPoint(&ip);
CalcOrtho(Trans.Loc1.Transf.Jacobian(), normal);
```
compute the normal vector in reference space. For example, if the face is a triangle, and the first adjacent element is a tetrahedron then `Trans.Loc1.Transf` is the transformation that maps the reference triangle into one of the four faces of the reference tetrahedron. Consequently, `normal` is a vector orthogonal to that face of the reference tetrahedron and its length is the ratio of the area of that face over the area of the reference triangle.

Which computation to use really depends on the integral you want to compute.

Hope this helps,
Veselin

**Comment by rhebergens** [comment]
Dear Veselin,

Thank you for the explanation! Just to make sure I understand this a bit better, was the reason to use 

`CalcOrtho(Trans.Loc1.Transf.Jacobian(), normal)`

in `NormalTraceJumpIntegrator` because w is a test variable in an H(div)-conforming space?

regards,
Sander

**Comment by v-dobrev** [comment]
Hi Sander,

Yes. Roughly speaking, since `w` is mapped using the H(div) Piola transformation, the integral in `NormalTraceJumpIntegrator` can be expressed as an integral on the reference face using the reference normal vector.

Veselin

**Comment by rhebergens** [comment]
Great - all clear now!
thanks,
Sander
