### ISSUE TITLE
Some basic question.

### ISSUE THREAD

**Issue by fanronghong** [mfem/mfem#842]
Hi all, I want to learn MFEM. But before that I want to know about the below questions.

1. Can I implement my own new finite element, not like usual finite elements(Lagrange element, DG, MINI...)

2. If the computation domain is separated into several parts, like 3 parts, I want to use P1 on the 1rt part, P2 on the 2nd part and DG on the 3rd part, and implement interface conditions among them. Can MFEM do that?

3. If MFEM can do above 2 steps, can you give some tips about how to implement them? So I can quickly start to learn MFEM.

Thanks in advance!

**Comment by tangqi** [comment]
If you are considering some multi-domain multi-physics problems, you may be interested in https://github.com/mfem/mfem/issues/788

**Comment by fanronghong** [comment]
Thank you @tangqi . I see that issue but it seems there is no good solution.

**Comment by mlstowell** [comment]
Hi, @fanronghong ,
MFEM does allow you to create your own `FiniteElement` classes, see `fem/fe.hpp`, and you'd also need to implement a `FiniteElementCollection`, see `fem/fe_coll.hpp`, which is responsible for allocating your `FiniteElement` class for each element type in your mesh.  The hard part is the second item.  We currently have no interface for doing this although people have done similar things in MFEM.  Usually the solution is tailored to a particular problem and difficult to generalize and this is the reason it has not become part of MFEM yet.

If you have ideas for how to approach multi-domain problems I'm sure we would be interested to hear them and perhaps work with you to find a general solution.

Best wishes,
Mark

**Comment by fanronghong** [comment]
Thanks @mlstowell , now I have no good idea about how to implement multi-domain problem, but I think it's very interesting and useful. And I find a branch [**block-fem-dev**](https://github.com/mfem/mfem/blob/block-fem-dev/fem/block_fem.hpp#L84), which is for multi-domain problem if I understand right.

**Comment by mlstowell** [comment]
Hi, @fanronghong ,
The [block-fem-dev](https://github.com/mfem/mfem/blob/block-fem-dev/fem/block_fem.hpp#L84) branch is actually designed for multi-physics problems where you have multiple equations that need to be solved in the same domain.  As such it doesn't add new functionality to MFEM but only makes the creation and use of `BlockOperators` more convenient.
Best wishes,
Mark

**Comment by fanronghong** [comment]
Thanks @mlstowell . I got it.
