### ISSUE TITLE
Coordinates associated with DOFs (unknowns in matrix)

### ISSUE THREAD

**Issue by leopoldcambier** [mfem/mfem#846]
Hi,

I'm a bit new to mfem. 
I'm working with example 5 (https://mfem.org/examples/, Darcy problem) and am using mfem to benchmark/study a linear system preconditioner.

To do so, I would like to generate for every row/column in the resulting matrix a (x, y, z) tuple (2D or 3D) of spatial coordinates. 

I tried applying the method from https://github.com/mfem/mfem/issues/63 to both the R_space and W_space fem spaces:

```
FiniteElementCollection *hdiv_coll(new RT_FECollection(order, dim));   
FiniteElementCollection *l2_coll(new L2_FECollection(order, dim));
FiniteElementSpace *R_space = new FiniteElementSpace(mesh, hdiv_coll);
FiniteElementSpace *W_space = new FiniteElementSpace(mesh, l2_coll);

// ...

GridFunction coo_R(R_space);
GridFunction coo_W(W_space);
mesh->GetNodes(coo_R);
mesh->GetNodes(coo_W);
cout << coo_R.Size() << endl;
cout << coo_W.Size() << endl;
```

However, in both cases, I get a vector of length exactly R_space->GetVSize() and W_space->GetVSize(). 
That'd be great, except that since we have dim=2 or dim=3, I would expect the sizes to be different for W_space since it's a scalar field but the coordinates should be a 2D or 3D vector field.

I am surely missing something obvious but I can't find what.
Is this the correct way to do this? Maybe what I'm doing is not very well defined (the unknowns are maybe not nodal values ?)
Any help is very much appreciated.

Thanks

**Comment by rcarson3** [comment]
So, it sounds like you're dealing with an issue somewhat similar to the one I was facing in issue #679.  In my miniapp, I found that the following produced a scalar field for my GridFunction:

```C++
int order_0 = 0;
L2_FECollection l2_fec(order_0, dim);
ParFiniteElementSpace l2_fes(pmesh, &l2_fec);
ParGridFunction var(&l2_fes);
```

I'm probably not the best one to answer your other comment related to the preconditioner/matrix. However, I will say it looks like based on the definition of ```Mesh::GetNodes``` that for the scalar field you won't be getting the answer that you might be expecting back out.

**Comment by tzanio** [comment]
Hi @leopoldcambier,

Can you explain why you need to construct these coordinates? The rows of the matrix correspond to degrees of freedom in the RT and L2 spaces, and the RT ones do not have a direct geometric meaning.

If you are trying to obtain the representations of certain functions, e.g. (x, 0, 0) in the RT space, that can be done with `GridFunction:: ProjectCoefficient`

**Comment by leopoldcambier** [comment]
Hi @tzanio 
Thanks for the help.
The reason is because I want to partition & order the matrix in a very specific way, and having geometric coordinates for row/col helps doing that. But I understand that's not always possible.

**Comment by v-dobrev** [comment]
Here is one way to get the coordinates of the dofs of the RT space (`R_space` in example 5):
```c++
   // Define a multi-component version of R_space to store the coordinates:
   FiniteElementSpace *R_vfes = new FiniteElementSpace(mesh, hdiv_coll, dim);
   GridFunction R_coords(R_vfes);

   DenseMatrix coords, coords_t;
   Array<int> rt_vdofs;
   for (int i = 0; i < mesh->GetNE(); i++)
   {
      const FiniteElement *rt_fe = R_vfes->GetFE(i);
      const IntegrationRule &rt_nodes = rt_fe->GetNodes();
      ElementTransformation *T = mesh->GetElementTransformation(i);
      T->Transform(rt_nodes, coords);
      coords_t.Transpose(coords);
      R_vfes->GetElementVDofs(i, rt_vdofs);
      R_coords.SetSubVector(rt_vdofs, coords_t.GetData());
   }
```
In the resulting `GridFunction`, `R_coords`, the coordinates will be stored using the default ordering, `Ordering::byNODES`, i.e. first all x-coordinates, then all y-coordinates, etc.

**Comment by leopoldcambier** [comment]
Hello Veselin,
Thanks for the help. 
I tried the above for the R_space dof's for the square-disc.mesh, but when plotting the coordinates, I get
![Screen Shot 2019-04-17 at 10 20 21](https://user-images.githubusercontent.com/10196423/56307777-84f12f00-60fa-11e9-9f5b-9397f0c6348e.png)
I suppose that's because of the specific kind of FEM basis functions ?

----

I the end, my end goal is more to be able to find 'meaningful' coordinates for the matrix row/col, to make it easier to order/partition it.
Whether they are strictly geometric or not is not super relevant, but so far, for simple FD or FEM discretization, taking the nodal values has always been a good choice. Nodes connected in the matrix are close in geometric space, that's the important bit.

**Comment by v-dobrev** [comment]
Oh, yes, I forgot that `rt_vdofs` will have negative entries in some cases (encoding a sign flip for a local dof relative to the global one). To fix this, add
```c++
   FiniteElementSpace::AdjustVDofs(rt_vdofs);
```
after the call `R_vfes->GetElementVDofs(i, rt_vdofs)`.

**Comment by leopoldcambier** [comment]
Ho that works so well now ! Thanks so much !

Here is the final code I used for posterity

   ```
// Get coordinates
   // For R
   FiniteElementSpace *R_vfes = new FiniteElementSpace(mesh, hdiv_coll, dim);
   GridFunction R_coords(R_vfes);
   {
      DenseMatrix coords, coords_t;
      Array<int> rt_vdofs;
      for (int i = 0; i < mesh->GetNE(); i++)
      {
         const FiniteElement *rt_fe = R_vfes->GetFE(i);
         const IntegrationRule &rt_nodes = rt_fe->GetNodes();
         ElementTransformation *T = mesh->GetElementTransformation(i);
         T->Transform(rt_nodes, coords);
         coords_t.Transpose(coords);
         R_vfes->GetElementVDofs(i, rt_vdofs);
         FiniteElementSpace::AdjustVDofs(rt_vdofs);
         R_coords.SetSubVector(rt_vdofs, coords_t.GetData());
      }
   }
   // For W
   FiniteElementSpace *W_vfes = new FiniteElementSpace(mesh, l2_coll, dim);
   GridFunction W_coords(W_vfes);
   {
      DenseMatrix coords, coords_t;
      Array<int> wt_vdofs;
      for (int i = 0; i < mesh->GetNE(); i++)
      {
         const FiniteElement *wt_fe = W_vfes->GetFE(i);
         const IntegrationRule &wt_nodes = wt_fe->GetNodes();
         ElementTransformation *T = mesh->GetElementTransformation(i);
         T->Transform(wt_nodes, coords);
         coords_t.Transpose(coords);
         W_vfes->GetElementVDofs(i, wt_vdofs);
         W_coords.SetSubVector(wt_vdofs, coords_t.GetData());
      }
   }
```

I just printed the R_coords and W_coords array to file doing this

```
std::ofstream Rfs("R_coords.txt", std::ofstream::out);
Rfs << R_coords;
Rfs.close();
std::ofstream Wfs("W_coords.txt", std::ofstream::out);
Wfs << W_coords;
Wfs.close();
```

And I could then easily produce this (red are  R_coords and blue are W_coords, and the black lines are edges in the resulting 'D' matrix)

![Screen Shot 2019-04-17 at 13 29 35](https://user-images.githubusercontent.com/10196423/56318884-05bd2480-6115-11e9-9256-b1da99da98a6.png)
