### ISSUE TITLE
working with subdomains and different refinement levels

### ISSUE THREAD

**Issue by munkaka** [mfem/mfem#85]
Hello,
I'm considering to start using mfem, but I would like to know if its possible to do the following. Suppose that I have a coarse mesh and I refine it only in part of the domain. What I would like to do is to be able to work on both levels of refinement separately. For example solving the elliptic problem first on the whole domain on the coarse mesh, then solve it again only where refinement occurs. For the first part what I need is to be able to construct a matrix iterating on elements on the coarsest level of refinement, for the second part the features that I need are building matrices iterating only on elements in a particular subdomain and linear solvers acting on a submatrix. Would that be possible?
Thanks, Giacomo

**Comment by tzanio** [comment]
Hi Giacomo,

What you are asking for is possible, though there are several ways in which it could be done, each of which will require some effort on your part.

To start off, it will be simpler if you copy the coarse level, and refine it in another mesh object. MFEM provides the transfer operators between the coarse and fine meshes, so the data on the two meshes can easily be connected.

When you do the refinement, you want to mark the refined elements with a special attribute. Then you can loop over them and either assemble only those elements in the global matrix (this will require changing the way we assemble integrators), or you loop over them to identify the degrees of freedom in the refined elements and eliminate the rest as essential dofs. Which approach is more appropriate depends on what you expect from the assembly on the coarse-fine interface.

Both approaches will give you a global matrix that includes the refined and unrefined coarse dofs. You can basically treat the latter as essential dofs -- eliminate their rows and columns and put 1 on the diagonal. You can go further and extract the refined sub-matrix and transfer data back and forth between it and the global dofs.

Hope this makes sense. Let us know if you have any questions.

Tzanio

**Comment by munkaka** [comment]
Thank you for the hints! I will try that :)

Enviado do meu iPad

**Comment by tzanio** [comment]
Hi @munkaka, did any of the above approaches worked for you?

**Comment by munkaka** [comment]
Hi, at the end I didn't used mfem since I managed to do it with my existing code. Thanks in any case for the hints and sorry for have taken your time :).
Bests, Giacomo.

**Comment by tzanio** [comment]
It's great that you got it working. Let us know if we can be of any help in the future. -Tzanio
