### ISSUE TITLE
ProductOperator with IterativeSolver in iterative mode

### ISSUE THREAD

**Issue by dylan-copeland** [mfem/mfem#853]
Here is a suggestion to help prevent bugs. I fell into a trap when trying to use an IterativeSolver instance in a ProductOperator. By default, IterativeSolver sets iterative_mode to true in Solver, so that the second argument is used as an initial guess. In ProductOperator, the second argument is a dummy variable (z) that the user cannot (and normally would not) set, which results in undefined values. To debug this, I had to set iterative_mode to false.

An easy way to prevent this would be to set z = 0 in ProductOperator::Mult, which is a small amount of unnecessary overhead in many cases. Another way would be to require the operators in ProductOperator to have iterative_mode == false, but iterative_mode is specific to the Solver class. This approach would require moving iterative_mode up to the Operator class, or checking whether the Operator is a Solver instance, or having a virtual function to check the iterative mode, etc. If code changes are not made, there should be at least a warning in comments.

**Comment by v-dobrev** [comment]
I personally prefer to address this by adding a check in the constructor of `ProductOperator`: check if the input `Operator`s are `Solver`s (with `dynamic_cast`) and set their `iterative_mode` to `false`.

It is probably a good idea to do the same in the classes `RAPOperator` and `TripleProductOperator`.

**Comment by tzanio** [comment]
@dylan-copeland do you want to propose a PR with the above fix?

**Comment by dylan-copeland** [comment]
@tzanio Yes, I will propose a PR with the fix.

**Comment by tzanio** [comment]
great @dylan-copeland, let me know if you need any help

**Comment by tzanio** [comment]
ping @dylan-copeland

**Comment by dylan-copeland** [comment]
I created PR 1087 to address this.

**Comment by v-dobrev** [comment]
Adding a `#` in front of the PR number will turn it into a link: #1087.

**Comment by tzanio** [comment]
Continue the discussion in the PR...
