### ISSUE TITLE
Sample code for creating input on the fly (vertices/nodes, elements etc.) and exporting/printing "matrices"

### ISSUE THREAD

**Issue by dfxh** [mfem/mfem#854]
Can you add a simple wihtout reading any mesh files where one can see in "c++" code howto create nodes/grids/vertices in the code and add elements and material information in C++.
Then export and print matrix data such as stiffness or mass matrices.

**Comment by mlstowell** [comment]
Hi, @dfxh ,
Have a look at `miniapps/meshing/toroid.cpp` to see an example of mesh creation in c++. Any of the example codes could be easily modified to print their matrices to disc. The matrix classes have a `Print` method.  I forget the exact syntax but they either take a filename or a `ostream` to write to.

Best wishes,
Mark

**Comment by tzanio** [comment]
Take a look also at example 7, which creates a mesh and solves a problem on the sphere.
