### ISSUE TITLE
Pentahedral element

### ISSUE THREAD

**Issue by dfxh** [mfem/mfem#856]
Are there Pentahedral elements? If not, could you add them?

**Comment by mlstowell** [comment]
Hi, @dfxh ,
We are in the process of adding wedge elements.  H1 and L2 elements are already available and Nedelec and Raviart-Thomas should be available by the end of the fiscal year.  We are looking at the other pentahedral element, a square pyramid, and we hope to add this as well.  The trouble with pyramids is that they involve rational polynomial basis functions.  MFEM can certainly handle these but they are different enough that they require a little extra thought to implement efficiently and robustly.

Best wishes,
Mark

**Comment by tzanio** [comment]
As Mark said -- prisms are available and we are working on square pyramids. Stay tuned...
