### ISSUE TITLE
Rigid elements

### ISSUE THREAD

**Issue by dfxh** [mfem/mfem#857]
How can one deal with idealized rigid elements? Are there penalty formulations for that?

**Comment by tzanio** [comment]
I'm not sure what exactly are you referring to here. Maybe other folks on the team can help, but it will be good if you can provide more details (ideally in the form of PDE and boundary conditions)

**Comment by dfxh** [comment]
"Commercial" FE codes offer lots of "special" elements to build "complex" systems.
These contain 2-noded elements such as "springs", "dampers" etc. and "rigid" or other "multipoint constraint" elements.
The area of the " rigid element" is any elasticity related problem. The "rigid element" constraints the motion of "n" nodes to that of a master "node" including translation and rotation. Technically done it is either by "elimination" the dependent degrees of freedom of the equation to be solved. After the solution the dependent dof are "added" to the output dataset again. Another option to solve the problem is that you do not remove the dependent dofs of the equation but to add lagrange multiplier.

Beside "rigid" "elements", there are also other "elements" such as multipoint constraings formulation "weighted motion" etc. .

**Comment by tzanio** [comment]
This is still difficult for me to follow, but if I understand correctly you want to impose a constraint on a subset of the degrees of freedom? We do that already for AMR with hanging nodes as well as in the hybridization support (see example 4).

**Comment by tzanio** [comment]
As a general rule, out finite elements are not specific to the problems we apply them to (which vary from solid mechanics, to flow, electromagnetics, etc.) but rather are used to define purely mathematical approximation spaces that could be used to approximate fields in different physics. For example the H(div) elements can be used for the discrete magnetic field, a flux, or in mixed methods.

So maybe the answer to your question is that we don't support "idealized rigid elements" directly but we do support constraints, so maybe implementing them is possible.
