### ISSUE TITLE
Numbering of elements and vertices

### ISSUE THREAD

**Issue by dfxh** [mfem/mfem#860]
Question: Ist it correct that mfem uses "only" compressed numbering scheme of nodes/vertices and elements? 
In other words: vertices/elements start with "index" 0 to n. They are referenced by "index" and not an individual "name" or "id" (int).
E.g.  commercial codes allow vertices (nodes/grids) have an aribtrary number allowing uncompressed ids.

**Comment by jakubcerveny** [comment]
Yes, we only number our vertices, elements, etc., with indices between 0 and N-1.

**Comment by tzanio** [comment]
Such feature could be added as an additional layer on top of the `Mesh` object, but we don't have plans to implement it soon.
