### ISSUE TITLE
Taking derivative of GridFunction

### ISSUE THREAD

**Issue by nickwhitman1993** [mfem/mfem#865]
Hi,

I have a GridFunction and would like to take the derivative. Can I call CalcDShape to do this, or is there another way I need to perform this?

Thanks,

Nick

**Comment by mlstowell** [comment]
Hi, @nickwhitman1993 ,
There are a number of ways derivatives can be obtained in MFEM.  The most appropriate way depends on the situation.  You can use `CalcDShape` to compute the gradients of the basis functions and then combine these results with the values of the degrees of freedom to compute the gradient at a given location within a single element.  This can also be accomplished by using `GridFunction::GetGradient()` which does essentially the same thing.  There is even a `GridFunction::GetDerivative()` method with loops over all elements and performs the above procedure and collects the results in a second `GridFunction` object although I believe this only computes one component of a derivative at a time (it can compute df/dy for example).

If you want to compute an entire `GridFunction` which is the derivative of a given `GridFunction` then you probably want to look at the `DiscreteInterpolator` classes in `bilinteg.hpp`.  These can be used to compute the gradient of an H1 field, the curl of an H(Curl) field, or the divergence of a H(Div) field.  If you need something else, like the curl of an H(Div) field for example, then you may need to compute with in a weak sense using a `BilinearIntegrator` and then solving a linear system to obtain the result.  You can read more about these options on [Linear Interpolators](https://mfem.org/lininterp/) and [`Bilinear Integrators`](https://mfem.org/bilininteg/).

Best wishes,
Mark

**Comment by nickwhitman1993** [comment]
Hi @mlstowell thanks for the reply. 

I do want a "GridFunction" returned that has vector information at every grid point that was on the original "GridFunction", so it sounds to me like the best option is to use the "DiscreteInterpolator". Am I understanding this correctly? The original field is a scalar field.

**Comment by mlstowell** [comment]
Hi, @nickwhitman1993 ,
That is a common but problematic request.  The trouble is that the derivative is discontinuous at element boundaries so we need to perform some sort of averaging of the values computed in neighboring  elements. Normally I would recommend using `MixedVectorGradientIntegrator` to perform the derivative followed by a solve to recover the appropriately weighted `GridFunction` but, as written, this only supports H(Curl) and H(Div) vector fields.  If this sounds like what you need then we could write a specialized integrator to compute your gradient.  I assume your original `GridFunction` is an `H1` scalar field.  Is this correct?

Another option is to use `GridFunction::GetDerivative()` (or a similar function) to compute an approximation to the gradient as a simple average of the values from neighboring elements.  This should be fine for visualization or certain types of post-processing but I'd be hesitant to use this as part of a numerically sensitive algorithm.  If this is part of a numerical algorithm you might want to consider using the H(Curl) representation of the gradient (which is my personal favorite) instead.

Best wishes,
Mark

**Comment by nickwhitman1993** [comment]
@mlstowell 

You are correct, my original `GridFunction` is indeed an `H1` scalar field. It is the output of my solve routine. 

I will indeed use this for an additional algorithm, so I need to be as accurate and careful as possible in the calculation of the gradient. It sounds like a `H(curl)` representation might be the best bet here. 
Are there any further stipulations or restrictions with using a `H(curl)` representation? The end goal is to take the gradient of the `GridFunction` output from my solve and another vector represented similarly at the `GridFunction` points and compute a tensor with that. 

Essentially the end goal of what I am doing is a Fourier's Law calculation where I divide the heat flux by the temperature gradient to obtain a thermal conductivity tensor.

I also have a few questions on how to best represent and calculate the heat flux, but I can save that until we figure out this portion.

Thanks again Mark.

Nick

**Comment by mlstowell** [comment]
Hi, @nickwhitman1993 ,
The `H(Curl)` space is the most natural space for the gradient of an `H1` field.  `H(Curl)` provides a family of vector fields whose tangential components are continuous across element boundaries but whose normal component is discontinuous.  If you think about how `H1` fields are defined as piecewise continuous polynomials their gradients have exactly this type of limited continuity.  What this means is that once you know a field in `H1` you can compute its gradient in `H(Curl)` in a fairly trivial manner (involving only data local to each element).  Specifically, what you do is the following:
```
GridFunction T(fespace_h1);
GridFunction dT(fespace_nd);

DiscreteLinearOperator grad(fespace_h1, fespace_nd);
grad.AddDomainInterpolator(new GradientInterpolator);
grad.Assemble();
grad.Finalize();

grad.Mult(T, dT);
```
This will produce an `H(Curl)` (a.k.a Nedelec or ND) representation of the gradient of `T` which I called `dT`.  This multiplication operation should be very fast and as long as you don't alter the topology of the mesh (by refining it for example) the gradient operator will not need to be rebuilt.

Best wishes,
Mark

**Comment by nickwhitman1993** [comment]
@mlstowell 

Just to clarify, dT would be returned as a GridFunction that contains vector information about the magnitude of the derivative in the x, y, and z directions?

**Comment by mlstowell** [comment]
Hi, @nickwhitman1993 ,
Discrete H(Curl) fields don't actually align with the x, y, and z directions.  They align with the edges of the mesh elements.  In fact the degrees of freedom, for a first order basis, are computed as integrals along a mesh edge of the inner product of your vector field with the tangent vector to that edge.

What this means is that the degrees of freedom themselves are generally not that useful unless you're very interested in path integrals of your vector fields.  To get the vector value at some point within an element you can call `GridFunction::GetVectorValue(i, ip, v)` where `i` is the element index, `ip` is the location inside the element in terms of the reference coordinate system, and `v` is the returned vector value.  The portion of this vector that is tangent to the surface of the element will be continuous across element boundaries, the normal component will be discontinuous.

I'm curious about your computation.  Are you trying to compute point-wise values for the conductivity tensor at each node of a mesh or are you doing homogenization where you're looking for an effective conductivity tensor of a large number of mesh elements?  Also, how do you compute the thermal flux?

Best wishes,
Mark

**Comment by nickwhitman1993** [comment]
@mlstowell 

Thank you for the explanation. 

Really, what it boils down to is that I need to be able to compute the temperature gradient, and the heat flux. The idea I had in mind was to compute the thermal conductivity tensor in general at each node, but the simulations I am running need to estimate a bulk thermal conductivity over the entire length of the problem domain. I am running simulations over nm size widths and trying to extract a bulk thermal conductivity to the macroscale, so the bulk approach _might_ be okay at this point if we are looking at a value(s) over the problem domain.

You ask an interesting question. I am actually simulating heat transport using phonon physics, so I solve for the scalar phonon intensity, call it `I`. `I` is related to temperature via `I = Cv*v_g*T/4pi` where `T` is temperature and the others are constants. My boundary conditions are just Dirichlet boundary conditions based on a temperature (emission), essentially.

I take the approach of solving this problem using the discrete ordinates method (called Sn) where the angular variable is discretized into a quadrature, and I loop over the angles and solve for each angular intensity and then sum the results into a scalar value. This gives me back the scalar phonon intensity, which can then be related to the temperature by the `I = Cv*v_g*T/4pi` equation.

I haven't quite figured out exactly how to compute the heat flux yet, but this is just simply the 1st angular moment of the phonon intensity. I already compute the 0th moment fairly easily by just looping over the converged angular values `scalar value += weight * angular value`, but I haven't quite figured out how to quite format this output yet. This going to be in a follow up question but it looks like this `heat flux [x,y.z] += weight * scalar value * direction vector[x,y,z]`

Additionally, in some previous conversation we had, you helped me write a linear integrator that I needed. I believe we found what was wrong and actually have a successful code at this point using the linear integrator you came up with. I don't know if that specific integrator would be useful, but it could be something added to the code base if desired.

Let me know what I can clarify. Additionally, it might be beneficial to have a phone call too. Let me know if you want to talk further.

Thanks again for your time @mlstowell!

Nick

**Comment by mlstowell** [comment]
Hi, @nickwhitman1993 ,
This sounds like a fascinating project.  I worked on something similar a few years ago trying to compute an effective dielectric tensor for a periodic structure.  This led to problems with spatial dispersion where the tensor depends not only on the frequency of the wave but also its direction of motion.  It's a tricky problem.

It's interesting that you mention computing moments.  I was just experimenting with this in MFEM a couple weeks ago, see branch `moment-dev`.  You can look at `miniapps/common/mesh_extras.cpp` in particular to see how I computed 0-th and 1-st moments of a scalar valued field.  If you need moments wrt an angular coordinate you'd need to alter these functions but I think it wouldn't be too difficult.   If you need advice on computing global integrals like these in MFEM I'd be happy to help.

Regarding your linear integrator: this is something MFEM needs more of.  I've been thinking of adding a larger group of integrators for people to work from.  Honestly, I haven't put much thought into it yet.  The hard part is coming up with a comprehensive family of integrators that cover a wide range of needs but are still easy to understand so that people can find what they need.

Best wishes,
Mark

**Comment by nickwhitman1993** [comment]
@mlstowell 

I would like to try implementing `GridFunction::GetDerivative( )` to obtain directional derivatives of my field. Would you be willing to help me step through how to implement this?

**Comment by mlstowell** [comment]
Hi, @nickwhitman1993 ,
Yes, of course!  I assume you start with an H1 field and you want an H1 representation of the directional derivative.  Is this correct?
Mark

**Comment by nickwhitman1993** [comment]
@mlstowell 
This is correct. I start with an H1 field. I just need to be able to obtain the derivatives in the x, y, z directions at the same points as represented in the H1 field. I was able to code up the current fairly easily, so I just need that last part to be able to make my first estimate of the thermal conductivity.

Out of curiosity, what would the L2 implementation entail? Would this implementation be present at the same grid points as the H1 field? Apologies for my ignorance.

Thanks again Mark, you have been extremely helpful throughout this project!

Nick

**Comment by mlstowell** [comment]
Hi, @nickwhitman1993 ,
My pleasure.  L2 fields are discontinuous so they would not be suitable for obtaining values at H1 grid points (many of which are on element interfaces).  The advantage of L2 representations is that they can be computed locally using only information from a single element at a time.  You essentially loop over the elements and compute the values you need within each element and you're done.

On the other hand if you need values on element interfaces, like many H1 grid points, you need to compute those values using weighted averages for best results. This is done in two stages; integrate the quantity of interest multiplied by each basis function in turn, divide by the integrals of the basis functions multiplied by each other.  In this context the first step is a matrix-vector product and the second is a matrix solve.  Assume you start with your field of interest `u` stored as an H1 `Gridfunction`. 
```
ConstantCoefficient one(1.0);

BilinearForm Dx(h1_fespace);
BilinearForm Dy(h1_fespace);
BilinearForm Dz(h1_fespace);

Dx.AddDomainIntegrator(new DerivativeIntegrator(one, 0));
Dy.AddDomainIntegrator(new DerivativeIntegrator(one, 1));
Dz.AddDomainIntegrator(new DerivativeIntegrator(one, 2));

Dx.Assemble(); Dx.Finalize();
Dy.Assemble(); Dy.Finalize();
Dz.Assemble(); Dz.Finalize();

BilinearForm m(h1_fespace);
m.AddDomainIntegrator(new MassIntegrator(one));
m.Assemble();
m.Finalize();

GridFunction ux(h1_fespace);
GridFunction uy(h1_fespace);
GridFunction uz(h1_fespace);

Vector rhs(h1_fespace.GetVSize());
DSmoother M(m);

Dx.Mult(u, rhs);
PCG(m, M, rhs, ux, 1, 200, 1e-12, 0.0);

Dy.Mult(u, rhs);
PCG(m, M, rhs, uy, 1, 200, 1e-12, 0.0);

Dz.Mult(u, rhs);
PCG(m, M, rhs, uz, 1, 200, 1e-12, 0.0);
``` 
I think something like this should work.  Feel free to ask for clarification if any of this is unclear.

Best wishes,
Mark

**Comment by nickwhitman1993** [comment]
Hi again @mlstowell,

In the context of what you provided above, I was able to implement this into my code with a few changes:


     //Compute Gradient of phi?
      ConstantCoefficient one(1.0);

      BilinearForm Dx(&fes);
      BilinearForm Dy(&fes);
      //BilinearForm Dz(&fes);

      Dx.AddDomainIntegrator(new DerivativeIntegrator(one, 0));
      Dy.AddDomainIntegrator(new DerivativeIntegrator(one, 1));
      //Dz.AddDomainIntegrator(new DerivativeIntegrator(one, 2));

      Dx.Assemble(); Dx.Finalize();
      Dy.Assemble(); Dy.Finalize();
      //Dz.Assemble(); Dz.Finalize();

      BilinearForm m(&fes);
      m.AddDomainIntegrator(new MassIntegrator(one));
      m.Assemble();
      m.Finalize();

      GridFunction ux(&fes);
      GridFunction uy(&fes);
      //GridFunction uz(&fes);

      Vector rhs(fes.GetVSize());
      DSmoother M(m);

      Dx.Mult(phi, rhs);
      PCG(m, M, rhs, ux, 1, 200, 1e-12, 0.0);

      Dy.Mult(phi, rhs);
      PCG(m, M, rhs, uy, 1, 200, 1e-12, 0.0);

      //Dz.Mult(phi, rhs);
      //PCG(m, M, rhs, uz, 1, 200, 1e-12, 0.0);`

Which seems to work - except one minor thing. It doesn't quite like the way I am asking it to implement `DSmoother M(m)`. I have also tried something like `DSmoother M(&m)` but also not quite working.

I get something back at compilation like:

`/nfs/stak/users/whitmann/broom2/src/Broom.cpp:403:20: note: candidates are:
In file included from /nfs/stak/users/whitmann/buildBroomParClang/TPL/include/linalg/linalg.hpp:24:0,
                 from /nfs/stak/users/whitmann/buildBroomParClang/TPL/include/mfem.hpp:35,
                 from /nfs/stak/users/whitmann/broom2/src/Broom.cpp:15:
/nfs/stak/users/whitmann/buildBroomParClang/TPL/include/linalg/sparsesmoothers.hpp:70:4: note: mfem::DSmoother::DSmoother(const mfem::SparseMatrix&, int, double, int)
    DSmoother(const SparseMatrix &a, int t = 0, double s = 1., int it = 1);
    ^
/nfs/stak/users/whitmann/buildBroomParClang/TPL/include/linalg/sparsesmoothers.hpp:70:4: note:   no known conversion for argument 1 from ‘mfem::BilinearForm’ to ‘const mfem::SparseMatrix&’
/nfs/stak/users/whitmann/buildBroomParClang/TPL/include/linalg/sparsesmoothers.hpp:66:4: note: mfem::DSmoother::DSmoother(int, double, int)
    DSmoother(int t = 0, double s = 1., int it = 1)
    ^
/nfs/stak/users/whitmann/buildBroomParClang/TPL/include/linalg/sparsesmoothers.hpp:66:4: note:   no known conversion for argument 1 from ‘mfem::BilinearForm’ to ‘int’
/nfs/stak/users/whitmann/buildBroomParClang/TPL/include/linalg/sparsesmoothers.hpp:55:7: note: mfem::DSmoother::DSmoother(const mfem::DSmoother&)
 class DSmoother : public SparseSmoother
       ^
/nfs/stak/users/whitmann/buildBroomParClang/TPL/include/linalg/sparsesmoothers.hpp:55:7: note:   no known conversion for argument 1 from ‘mfem::BilinearForm’ to ‘const mfem::DSmoother&’
/nfs/stak/users/whitmann/buildBroomParClang/TPL/include/linalg/sparsesmoothers.hpp:55:7: note: mfem::DSmoother::DSmoother(mfem::DSmoother&&)
/nfs/stak/users/whitmann/buildBroomParClang/TPL/include/linalg/sparsesmoothers.hpp:55:7: note:   no known conversion for argument 1 from ‘mfem::BilinearForm’ to ‘mfem::DSmoother&&’
`

From taking a look at some of my other files, it seems like the `DSmoother` argument needs to be a `SparseMatrix`. I added this line: `      SparseMatrix &Q = m.SpMat();
      DSmoother M(Q,1);`
which allowed it to compile, but at run-time I get `Assertion failed: (width == x.Size()) is false: Input vector size (0) must match matrix width (441)
 ... in function: virtual void mfem::SparseMatrix::AddMult(const mfem::Vector&, mfem::Vector&, double) const
 ... at line 485 of file: linalg/sparsemat.cpp
`

Do you have any thoughts on what might need to be done to fix this? Sorry for the lengthy reply. 

Thanks again,

Nick

**Comment by mlstowell** [comment]
Hi, @nickwhitman1993 ,
The thing that jumps out at made is the declaration of `Q` as a reference to a `SparseMatrix`.  Technically `m.SpMat()` returns a `const` reference so `Q` may be a shallow copy (or something worse) of the object that you need.  Try to declare it as:
```
const SparseMatrix &Q = m.SpMat();
```
If that doesn't work we may need to dig deeper.

Best wishes,
Mark

**Comment by nickwhitman1993** [comment]
Hi @mlstowell, sorry for the delay here.

I did try both the const declaration and not. I believe neither was working. I will test this again to ensure what I am telling you is correct and note back here shortly.
Would you have any further thoughts on where we could dig if so?\\

Thanks again,

Nick

**Comment by nickwhitman1993** [comment]
@mlstowell 

I believe I have corrected the error. Please neglect the above message. I do however receive console output, i.e. 
   `Average reduction factor = 0.44786226
   Iteration :   0  (B r, r) = 0.00043460275`
Do you know if I can suppress this?

Nick

**Comment by nickwhitman1993** [comment]
As another note, I keep getting an error in the PCG subroutine:
```
Assertion failed: (IsFinite(nom)) is false: nom = -nan
 ... in function: virtual void mfem::CGSolver::Mult(const mfem::Vector&, mfem::Vector&) const
 ... at line 320 of file: linalg/solvers.cpp
```

Any thoughts?

Nick

**Comment by mlstowell** [comment]
Hi, @nickwhitman1993 ,

The "Average reduction..." messages come from the conjugate gradient solver.  They can be controlled by the fifth argument to the `PCG` function.  Typical values are 0, 1, or 2 with higher values generally yielding more information.  If you want no output at all you can try 0 but -1 might be necessary (I'm afraid this is not well documented).

My guess regarding the NAN is that the solution vectors `ux` and `uy` should be initialized to zero before calling `PCG`.  I believe these are being accessed to compute an initial residual vector (`res = rhs - M*ux` for example) but since they aren't initialized they could be introducing NANs.

Best wishes,
Mark

**Comment by nickwhitman1993** [comment]
Hi again @mlstowell,

I am very delayed in telling you this, but I just wanted to chime in and tell you that I _believe_ everything is working as promised. The issue, I believe, is that I tried to calculate the gradient after every iteration and wasn't clearing the memory somehow. Maybe this helps somewhere down the road.

I wanted to say thank you again for all your help getting this working over the past few months. I sincerely appreciate your time.

Best wishes,

Nick
