### ISSUE TITLE
Modal DG Elements

### ISSUE THREAD

**Issue by ianabel** [mfem/mfem#872]
Is there a plan to include modal DG elements? 

If not, I'll look into building a modal analogue to L2FiniteElementCollection

**Comment by tzanio** [comment]
There is no direct support in `master`, but I think @nourgaliev may have done some work in this direction already.

**Comment by tzanio** [comment]
@ianabel, at any rate we will be interested in having such capability in the library.

**Comment by nourgaliev** [comment]
In my project, we are looking at two types of modal DG - tensor-product Taylor/Legendre based (cuboidal elements) and Dubiner (orthogonal for simplectic elements). It might take a while before this propagates into MFEM.

**Comment by ianabel** [comment]
Right, so I was thinking of Dubiner elements as well, so I'ld be happy to 
help out porting that back into MFEM at some point; once i'm more familiar 
with the MFEM code base.

> In my project, we are looking at two types of modal DG - tenso-product 
> Taylor/Legendre based (cuboidal elements) and Dubiner (orthogonal for 
> simplectic elements). It might take a while before this propagates into 
> MFEM.
>
>
