### ISSUE TITLE
Question properties of elements

### ISSUE THREAD

**Issue by dfxh** [mfem/mfem#873]
I cannot find in the documentation where in the datastructure nonnodal  information of the elements are stored. I am speaking of information such as the thickness of shells as well as material data (e.g. mass density, youngsters modulus, thermal conductivity etc. )

I also did not find the get/set routines to access this data.

**Comment by mlstowell** [comment]
Hi, @dfxh ,
The elements in MFEM are essentially topological objects which are only used to describe how our computational domain is split into manageable chunks.  Perhaps one concession that we make is in providing an element attribute number, see `Element::Set/GetAttribute()`.  This is a positive integer that can be used to group elements together into disjoint groups.  For example this integer can be used to look up material properties from a collection of tables.  You could define a table containing mass densities corresponding to each attribute number and then define a `PWConstCoefficient` coefficient to access this table.

Our focus is not on solid mechanics but on continuum physics where things like material data are often provided by equations of state.  In such cases we compute material properties as non-linear functions of temperature, density, etc..  We typically use our `Coefficient` classes to perform these computations behind the scenes.

Shell elements are something we don't have and I'm not sure how they might be used. It might be possible to define a field on a group of 2D elements which would correspond to the local thickness as a function of position.  This field could then be used in a variety of ways.  Perhaps such a model could be used to perform the same role as shell elements.

Best wishes,
Mark

**Comment by tzanio** [comment]
Hi @dfxh,

As Mark explained, we do not support shell elements, and the material properties are not associated directly with the mesh, see e.g. Example 2.

I'm closing this issue now, but please let us know if you have any further questions.
Tzanio
