### ISSUE TITLE
Center of gravity / inertias

### ISSUE THREAD

**Issue by dfxh** [mfem/mfem#874]
Are there routines to compute total mass, centerfield of gravity, inertia of an element and/or a whole mesh (assembly)

**Comment by mlstowell** [comment]
Hi, @dfxh ,
The short answer is no but this is a great question.  Computing the mass, center or gravity, etc. of the entire mesh just involve computing integrals and FEM methods are all about computing integrals so we can certainly do this.  How it should be done depends on how one represents the mass density, gravitational field, etc..  Typically I like to use `LinearForms` and `GridFunctions` to compute global integrals like this.  The details are not difficult but they do depend on how your fields are represented.

Computing such quantities for individual elements is also not difficult.  A method similar to `GridFunction::ComputeElementLpErrors()` could do this and store the results in a second `Gridfunction`.  We don't have this in the library but it would be simple to implement.

Best wishes,
Mark
