### ISSUE TITLE
How to set time in linear form for time dependent problem?

### ISSUE THREAD

**Issue by tuckerbabcock** [mfem/mfem#876]
Hi, I have a question regarding usage. 

I'm trying to construct a `DomainLFIntegrator` with a time dependent function coefficient. How can I set the time that the function coefficient will be evaluated at? Since the `Coefficient` `Q` is a private member, I can't access it to call `SetTime()` directly, so I'm not sure how to do this. 

Thanks,
Tucker

**Comment by v-dobrev** [comment]
Hi @tuckerbabcock,

For time-dependent problems, I would recommend storing the (time-dependent) linear and/or bilinear forms and their time-dependent coefficients in the same object - typically a user-defined class derived from `TimeDependentOperator`. Then inside the `Mult` (or `ImplicitMult`) method of the user class one can propagate the time from the `TimeDependentOperator` to the time-dependent coefficient before assembly.

If this does not fit your needs, can you explain what your use case is?

**Comment by tzanio** [comment]
See e.g. `HyperelasticOperator` in Example 10.

**Comment by tuckerbabcock** [comment]
Thanks for taking the time to reply. Just to confirm I understand correctly, this would look something like this: 
`void FE_Evolution::Mult(const Vector &x, Vector &y) const
{
	inflow->SetTime(t);
	b.Assemble();
	// y = M^{-1} (K x + b)
	K.Mult(x, z);
	z += b;
	M_solver.Mult(z, y);
}`
Where inflow is the time dependent function coefficient, and b is the linear form. This is a fairly simple modification to example 9 where I've added time varying boundary conditions.
