### ISSUE TITLE
Essential Boundary Conditions  on hole boundary

### ISSUE THREAD

**Issue by Aerokaur** [mfem/mfem#881]
Hello
I want to do pde constrained optimization to get a conformal mesh with laplace equation as pde constraint that I am going to solve using MFEM. My initial mesh is a mesh consisting of triangular elements with square domain with a square hole in it (for which I want to move nodes as the optimization progresses). But I need different boundary conditions at the hole boundaries and main boundaries.  Let say I want u= 1 on hole boundaries and  u=0 on main boundaries. How can I implement this in MFEM ? Any help will be appreciated.
Thanks

**Comment by mlstowell** [comment]
Hi, @Aerokaur ,
There are two schemes that come immediately to mind both start by following `ex1p.cpp`.   Dirichlet BCs are set using the method `ParBilinearForm::FormLinearSystem`.  Its takes whatever values it finds in the `x` argument at the locations specified by `ess_tdof_list` and uses these as the Dirichlet values.    You would want to fill `ess_tdof_list` in the same manner as `ex1p.cpp`.  The difference is in how you should place values in `x`.
1) Define a function which returns 0 near the main boundary and 1 near the hole boundary.  Use this to define a `FunctionCoefficient` which you then project onto `x` before calling `FormLinearSystem`.
2) Label the hole boundary elements with a different attribute number from the main boundary elements.  Define a `PWConstCoefficient` which returns 0 for the main boundary attribute number and 1 for the hole attribute number.

If this isn't clear I can go into more detail.

Best wishes,
Mark

**Comment by Aerokaur** [comment]
I know how to project onto x for boundary but I am not sure how do I distinguish between two boundaries. Is there any way to label different attribute numbers for the two boundaries in MFEM or I should do that before I import my mesh ? My mesh is same to that of square-disc used in examples with the only difference is that instead of disc it is square hole. Thanks for help.

**Comment by Aerokaur** [comment]
I think i got it. Using if conditions should work. 
Thanks

**Comment by mlstowell** [comment]
Hi, @Aerokaur ,
I'm glad that's working.  MFEM does not currently have a way to reassign attribute numbers in an existing mesh (it would be straight forward to write such a code based on vertex coordinates, for example, we just don't have this at the moment).  You would need to modify the mesh before it's read into MFEM.
Best wishes,
Mark

**Comment by rcarson3** [comment]
@mlstowell in #722 we actually added that functionality to change the boundary attribute for a given element.

Overall, the change just required us to add the following lines  to ```mesh/mesh.hpp``` right after ```GetBdrAttribute``` is defined.

```C++
/// Set the attribute of boundary element i
   void SetBdrAttribute(int i, int attr) { boundary[i]->SetAttribute(attr); }
```

It has worked well enough for our needs to relabel the boundary attributes from the auto generated meshes into our own labeling order. 

ExaConstit is still very much a work in progress, so we probably won't be pulled in as a miniapp for some time. So, I'd say if some one wants to add this functionality to the main branch or their own feel free to use our simple function as a starting point.

**Comment by mlstowell** [comment]
@rcarson3 , that's a good point.  Such a method would be useful and simple to add.  However, I was actually thinking of an application level tool.  Something like a program that would scan the interior or boundary elements and reassign their attribute numbers based on the result of some query.  We don't currently have such a tool but I'd love to add one when I get a chance.

**Comment by Aerokaur** [comment]
Thanks for taking your time to help. I may have other questions as I continue with my work.
Thanks again !!!
