### ISSUE TITLE
Error reading msh file from a re-mesher

### ISSUE THREAD

**Issue by tomathew** [mfem/mfem#883]
Hello,
I encounter an error while trying to read a mesh file (.msh) which is a gmsh file re-meshed in a tool, mmg https://www.mmgtools.org/ .

MFEM abort: Non-positive element attribute in Gmsh mesh!
 ... in function: void mfem::Mesh::ReadGmshMesh(std::istream&)
 ... in file: mesh/mesh_readers.cpp:1172

Aborted (core dumped)
__________________________________________________
I enlcose the concerned mesh files too.
[meshFiles.zip](https://github.com/mfem/mfem/files/3112146/meshFiles.zip)
the one named msphere.msh is the re-meshed one.
You can try a general case, if you want to confirm it with of your working .msh files, by:
download the mmg3d_O3 executable from the website and,
$ mmg3d_O3  -in <input>.msh -out <output>.msh [-options]
-options can be found by -h or use -noinsert
 Please let me know if you need more information. 
I don't think this is a bug at mmgtools, as I use their meshes in the platform I am working on.
Regards,
Tom

**Comment by jonesholger** [comment]
Hello @tomathew, thank you very much for your follow-up. We have an effort to update our mesh readers and I have a PR undergoing review that should help, as I was able to read your mesh examples.  https://github.com/mfem/mfem/pull/763. Although, most of the attention was applied
 to gmsh 4.0,4.1 files, I do have a small patch for v2.2 files (see commit https://github.com/mfem/mfem/pull/763/commits/d0ab423582d5b4de65cc8cb3427fea5ad3a5a4ae). So, expect to see these changes in a future release, but I encourage you to apply these changes to your local snapshot, or fetch my branch https://github.com/jonesholger/MFEM/tree/holger/feature/gmshv4. Keep us in the loop as you make progress. Thanks again.


![image](https://user-images.githubusercontent.com/12015127/56681327-f0e51180-667d-11e9-9f6d-8e59f856d587.png)

**Comment by tomathew** [comment]
Dear @jonesholger,
Thank you very much !
Best regards,
Tom
