### ISSUE TITLE
Imposing Boundary Conditions to Raviart-Thomas Spaces

### ISSUE THREAD

**Issue by aschaf** [mfem/mfem#886]
Hi,

is it possible to directly impose the boundary condition `( sigma . n) = g`, for `sigma` an vector field from an RT space and and `n` the normal?

Thanks,
Andreas

**Comment by tzanio** [comment]
Isn't this just inhomogeneous Dirichlet boundary condition as in Example 4?

**Comment by aschaf** [comment]
Hm, right, I somehow overlooked this, thanks.
