### ISSUE TITLE
BoomerAMG options

### ISSUE THREAD

**Issue by aasivas** [mfem/mfem#89]
Hello,

I am quite new to mfem and still learning, so this is a newbie question. I need to change some options for BoomerAMG to use it as a preconditioner, but could not see any mfem function to set them. Is there any way to do it so without changing source files?

Thanks in advance,
Abdullah Ali Sivas

**Comment by v-dobrev** [comment]
Hi Abdullah,

You can typecast the `HypreBoomerAMG` object to `HYPRE_Solver` - the typecast is re-defined to return the direct handle to the hypre object (see [hypre.hpp:750](https://github.com/mfem/mfem/blob/master/linalg/hypre.hpp#L750)), e.g.
```c++
HypreBoomerAMG amg(A);
HYPRE_Solver h_amg = (HYPRE_Solver)amg;
```
After that it is a matter of calling directly the hypre functions to set the options you want, e.g.
```c++
HYPRE_BoomerAMGSetStrongThreshold(h_amg, 0.25);
```

Hope this helps,
Veselin

**Comment by aasivas** [comment]
Hi Veselin,

Thank you for answer, and it helps a lot. I was looking for a direct mfem call so that I even haven't noticed that I could do that. Thanks again.

Best regards,
Abdullah Ali Sivas
