### ISSUE TITLE
Tuning AMS 

### ISSUE THREAD

**Issue by tomathew** [mfem/mfem#891]
Dear all,
It would be great if I can have some help or possible directions in MFEM to tune AMS for my solver. I have a basic parallel solver in 3D, which I believe is correctly coupled to AMS preconditioner. I am adding all the bilinear form with positive co-efficients, and using it a block diagonal preconditioner in AMS (not sure if it's mathematically valid, I'm not a mathematician). I was just seeing what was done in miniapps/electromagnetics/ . 
I have some questions too:
(1). In this work, https://library.seg.org/doi/10.1190/geo2015-0013.1, AMS has been studied on a couple hundreds of processses. Does it scale beyond that ? I read briefly about the scaling and robustness of the preconditioner, but is not happening to me. It would be great if anyone can suggest some options to tune it.
(2). The complexity of the domain dealt in the paper is simple to what I'm working on (X-ray tomographied micro-heterogeneties), can this be a constraint ? And, as it is mentioned it is robust for strong material contrasts, I hope its going to work for high complex index of refraction.
(3). I assume AMS is inheriting the multilevel benefits from AMG, so that it will scale on 1000s of processes, else can you guide me on how to make it scale on 1000s of processes ?
Best Regards,
Tom

**Comment by tzanio** [comment]
> (1). In this work, https://library.seg.org/doi/10.1190/geo2015-0013.1, AMS has been studied on a couple hundreds of processses. Does it scale beyond that ?

Yes absolutely. See for example this paper: https://link.springer.com/chapter/10.1007/978-1-4471-2437-5_13, where scalabilty was shown up to 125,000 cores.

> I read briefly about the scaling and robustness of the preconditioner, but is not happening to me. 

Can you provide additional details? E.g. what  exactly is the PDE, coefficients, boundary conditions, discretization, etc?

> (2). The complexity of the domain dealt in the paper is simple to what I'm working on (X-ray tomographied micro-heterogeneties), can this be a constraint ? And, as it is mentioned it is robust for strong material contrasts, I hope its going to work for high complex index of refraction.

Just like AMG, AMS is robust with respect to the shape of the domain and strong material contrasts. See e.g. the original paper: https://computation.llnl.gov/projects/hypre-scalable-linear-solvers-multigrid-methods/Kolev-2009-par-aux-space.pdf.

> (3). I assume AMS is inheriting the multilevel benefits from AMG, so that it will scale on 1000s of processes, else can you guide me on how to make it scale on 1000s of processes ?

See the answer above :)

**Comment by tomathew** [comment]
Dear @tzanio,
Thank you very much for the feedback. I'll try describe my model the best as I can. The varf of the source-free (\sigma=0) time-harmonic Maxwell equations I am trying to resolve looks the following:
![varf](https://user-images.githubusercontent.com/22793567/56942459-2c1e8f00-6b1b-11e9-90c3-3d18387882fe.png)
Electromagnetic scattering is to be resolved for various complex micro-scale scatterers (total-scattered field formulation) for thermal radiative applications. From the scattered field we derive scattering, extinction etc. among others to be used in the radiative transfer equation at a macro-scale.Complex scatterers can be micro-structures constituting the composite materials for high temperature equipment like thermal barrier coating on the turbine blade of an aircraft (complex structures) for ex. .We deal with complex electric permittivity \epsilon=\epsilon^\prime + 1i* \epsilon^{\prime\prime}, and excitation is a plane wave, exp(ikx).
Bilinear form: linear system in real (attempted in mfem is a block system),
A = [ \row1{C-M1, B+M2}
        \row2{ -(B+M2), C-M1}], where
C = (curl V \cdot curl U)_\Omega
M1 = k^2 (\epsilon^\prime V \cdot U)_\Omega
M2 = k^2 (\epsilon^{\prime\prime} V \cdot U)_\Omega
B = k(V \cdot U)_\Gamma ----> this is truncation by first order absorbing boundary conditions
No Dirichlet conditions, and a corresponding linear form as in the figure above. V,U \in Nedelec basis

AMS is working for me on my work-station, for small problems. It's converging pretty faster, but when attempted on cluster, for the real test-cases, it is converging, but very slowly. I use tetrahedral triangulation. 
I hope I could explain the problem I am trying to solve. I will also take a look into the above papers. 
Thankfully,
Tom

**Comment by tzanio** [comment]
Tom, this problem appears to be indefinite (unless `epsilon' = 0`). 

AMS can not handle the indefinite case. We are working on other approaches for this case, but that's a hard problem...

**Comment by tomathew** [comment]
Dear @tzanio,
Thank you ! Yes, I just read that from the above referred papers. As I said my bad,  I am not from a mathematical background. I came across your paper and read about the mentioned general robustness in all aspects, and just gave it a try. Is there any other silver lining for me in mfem ?
Thankfully,
Tom

**Comment by agrayver** [comment]
You may still try and construct a preconditioner suitable for AMS using definite part of the matrix, that is

```
P = [ \row1{C, B+M2}
        \row2{ -(B+M2), C}]
```
This used to work for me when a problem is 'moderately' (this is difficult to quantify!) indefinite. 

Having said this, the parameters which affect performance of AMS most are cycle type and coarsening settings. Both are problem dependent, but I would play with those first.

**Comment by tomathew** [comment]
Dear @agrayver,
So I tried constructing a block preconditioner 'P = [ \row1{S, 0}, \row2{0, S} ]', where 
'S = C+B+M2'. Earlier on my laptop (8 processes), I used to have good convergence with S = C+M1+B+M2, which degrades to a cluster, but now without M1, I am having a plateau even on 8 processes.
For tuning I found `HYPRE_AMSSetCycleType(*ams, 7);` to work the better for me. Sorry that I couldn't find the appropriate method to tweak the coarsening, than the alpha, beta coarsening options.
Adding an artificial absorption as in https://arxiv.org/abs/1711.03789, can help the convergence sometimes for indefinite problems, do you think this can be a right direction. 
All I see here, contrary to the ORAS, a higher absorption (imaginary part of epsilon) is making the conditioning bad, which is expected as the off-diagonal counterparts become more significant.
I was out of work last week for helping out for an experiment, so couldn't look at this in detail. I'll take a deeper look and get back to you.
If you need more information please let me know, I''ll glad to share more information.
Thanks for the feedback,
Tom

**Comment by tomathew** [comment]
It would be better if I can have some directions to look for or work on, in petsc or hypre or try something new in mfem based on your experience on this. As far as I know ORAS methods will work for me, but is not available in either petsc or hypre. I tried ASM, but shows promise only with significant overlaps (huge memory constraints). All the works I see for BDDC are dealing with definite problems, so I don't know if it will work for me, so haven't tried yet. It seems like I have a doomed problem, which nobody else want to solve, and hence no other directions.
Best regards,
Tom

**Comment by agrayver** [comment]
Can you reduce your problem to a definite one (set M1 = 0) and check that AMS attains reported convergence and scales as expected? One needs to ensure that what you see is because of an indefinite problem and not caused by other technical problems.

**Comment by tomathew** [comment]
Dear @agrayver,
I don't understand if this will make the problem ill-posed, as my material parameters driving the solution is in M1. I tried as you told me as before when dropping M1 from the preconditioner, it was a plateau. Where else can I make a mistake ? I checked the best as I can and the plots for the solvable problems are closer to what is expected. The coefficient are PWConstCoefficients(); and there is no essential dofs. The problem domain is truncated by first-order ABC.
I was just playing around with some Petsc options, and found FieldSplit solvers quite close to AMS, but not scalable, or as efficient.
Best Regards,
Tom

**Comment by stefanozampini** [comment]
> It would be better if I can have some directions to look for or work on, in petsc or hypre or try something new in mfem based on your experience on this. As far as I know ORAS methods will work for me, but is not available in either petsc or hypre. I tried ASM, but shows promise only with significant overlaps (huge memory constraints). All the works I see for BDDC are dealing with definite problems, so I don't know if it will work for me, so haven't tried yet. It seems like I have a doomed problem, which nobody else want to solve, and hence no other directions.
> Best regards,
> Tom

BDDC supports indefinite problems; for slowly varying coefficients it should perform well. For highly varying coefficients, there's some preliminary support for adaptive coarse spaces but I'm not sure it  applies  to your case . 

You mentioned Fieldsplit. What did you try?

**Comment by tomathew** [comment]
Thank you for the suggestion. I briefly looked into this "PCBDDC: A CLASS OF ROBUST DUAL-PRIMAL METHODS IN PETSc," and saw that bddc could be applied to spd, but as you say I will try it. Can you suggest me your relevant article reference that I can read to help implement this with BDDC in PETSc ?
Should I try -ksp_type fetidp ?
Yeah, the fieldsplit was just tried as in PETSc manual it was listed under for solving block matrices. It is not a special thing I tried, it is equivalent to a bjacobi preconditioner with sub_pc_type lu or a block diagonal preconditioner with the C-M1 as preconditioner, which was solved with -ksp preonly. I mentioned it because, it was converging contrary to other methods where I got a plateau. I don't think it is a good option, the only positives that are gained from trying fieldsplit was -ksp_type minres can be good, and the an accurate approximation of C-M1, can help converge faster.
Thank you very much

**Comment by stefanozampini** [comment]
The BDDC code in PETSc supports any kind of linear system: robustness can be only proved for spd.

So, there's a PetscBDDCSolver class in MFEM, that automatically constructs what you need if you have a single block of CurlCurl problem, see e.g. examples/petsc/ex3p.cpp. There's no support for Nedelec for the blockOperator case. Support for the blockOperator case works only with Darcy's like problems, see e.g. examples/petsc/ex5p.cpp.

If you have a block operator, you can still construct a BDDC solver, but then you have to attach the discrete gradient matrices yourself as done here https://github.com/mfem/mfem/blob/master/linalg/petsc.cpp#L2852

**Comment by tomathew** [comment]
If I construct a block diagonal preconditioner with each diagonal block solved by bddc, will it be good ?
Should I try -ksp_type fetidp in PETSc ?

**Comment by tomathew** [comment]
Thank you, I have to deal with sharp material contrast, even problems involving high reflections. So I don't think this scheme is going to work for me. I am working on ORAS techniques that have proven convergence  for indefinite problems
Thanks for the suggestion
