### ISSUE TITLE
MFEM under compiler variability

### ISSUE THREAD

**Issue by mikebentley15** [mfem/mfem#893]
# FLiT Overview

[FLiT](https://github.com/PRUNERS/FLiT.git) is a tool used to measure and locate compiler-induced variability in C++ code.  It does this by providing a C++ floating-point testing framework and by running many compilations.

# FLiT Results with MFEM

All 19 MFEM examples (run on MFEM version 3.4) were converted into FLiT tests and run through 244 compilations.

Here is a table of relative variability of each of the 19 examples from MFEM version 3.4.

| Test |  # variable of 244  |  min rel. err. | mean rel. err. | max rel. err. |
|:-----:|:---:|:----------:|:------------:|:-----------:|
| 1 | 49 | 4.8e-15 | 5.8 e -15 | 1.3 e -14 |
| 2 | 49 | 8.2e-14 | 1.3e-13 | 2.0e-13 |
| 3 | 107 | 1.8e-14 | 2.0e-14 | 2.3e-14 |
| 4 | 109 | 4.9e-10 | 8.5e-10 | 4.4e-9 |
| 5 | 115 | 8.9e-15 | 6.5e-14 | 1.3e-13 |
| 6 | 49 | 5.0e-15 | 7.6e-15 | 2.0e-14 |
| 7 | 55 | 6.5e-16 | 1.1e-15 | 1.9e-15 |
| **8** | **49** | **2.4e-7** | **3.1e-7** | **7.6e-7** |
| 9 | 119 | 1.0e-15 | 4.1e-15 | 1.8e-14 |
| 10 | 117 | 3.3e-11 | 6.8e-11 | 1.2e-10 |
| 11 | 13 | 2.3e-14 | 1.9e-9 | 3.9e-9 |
| 12 | 0 | - | - | - |
| **13** | **12** | **1.84** | **1.92** | **1.97** |
| 14 | 51 | 6.4e-15 | 3.9e-14 | 1.1e-13 |
| 15 | 118 | 3.9e-15 | 1.9e-12 | 7.3e-12 |
| 16 | 49 | 5.2e-16 | 8.4e-16 | 3.4e-15 |
| 17 | 50 | 5.0e-14 | 2.5e-13 | 5.7e-13 |
| 18 | 0 | - | - | - |
| 19 | 55 | 1.2e-9 | 1.8e-9 | 2.2e-9 |

These numbers represent relative error according to the L2 norm.  Noteworthy are tests 12 and 18 had no observed variability by the FLiT tool regardless of the compilation performed.  Also noteworthy is that tests 8 and 13 had a significant relative error.

Relative error is calculated as || baseline - actual || / || baseline ||, where baseline is the mesh from g++ -O0.

## Example 8

We had manually investigated this difference with an older version of MFEM and had isolated the problem to dot product: `vector.cpp` line 90 `mfem::Vector::operator*(double*)`.  With this new version of MFEM, things have changed a bit:

For `g++ -O2 -mavx2 -mfma`, we get the following functions with associated absolute errors (marked as "score"):

- `mfem/linalg/densemat.cpp:3689 mfem::AddMult_a_AAt(double, mfem::DenseMatrix const&, mfem::DenseMatrix&)` (score 7.7e-6)
- `mfem/linalg/densemat.cpp:643 mfem::DenseMatrix::Invert()` (score 6.3e-6)
- `mfem/linalg/densemat.cpp:461 mfem::DenseMatrix::Det() const` (score 4.4e-06)
- `mfem/linalg/densemat.cpp:2975 mfem::Mult(mfem::DenseMatrix const&, mfem::DenseMatrix const&, mfem::DenseMatrix&)` (score 3.7e-6)
- `mfem/linalg/sparsemat.cpp:493 mfem::SparseMatrix::AddMult(mfem::Vector const&, mfem::Vector&, double) const` (score 1.6e-6)
- `mfem/linalg/sparsemat.cpp:571 mfem::SparseMatrix::AddMultTranspose(mfem::Vector const&, mfem::Vector&, double) const` (score 1.6e-6)
- `mfem/linalg/vector.cpp:279 mfem::add(mfem::Vector const&, double, mfem::Vector const&, mfem::Vector&)` (score 3.8e-7)
- `mfem/linalg/densemat.cpp:3480 mfem::AddMultABt(mfem::DenseMatrix const&, mfem::DenseMatrix const&, mfem::DenseMatrix&)` (score 6.6e-8)
- `mfem/linalg/vector.cpp:90 mfem::Vector::operator*(double const*) const` (score 3.0e-8)

For `g++ -O3 -mavx2 -mfma`, we get the exact same list, except `mfem::Vector::operator*()` no longer causes variability.

For `g++ -O3 -funsafe-math-optimizations`, we only get one variability-inducing symbol:

- `mfem/linalg/vector.cpp:90 _ZNK4mfem6VectormlEPKd` -- `mfem::Vector::operator*(double const*) const` (score 3.2e-6)

Note: this is dot product again, but with a much higher variability than that seen with `g++ -O2 -mavx2 -mfma`.

There were 49 total compilations that caused variability.  These are the only three for which example 8 succeeded with symbol bisect.

## Example 13

This was not in the old set of tests and is brand new.  The relative error here is between 183% to 197%.  That is very significant.  All successful bisect runs found only one function to blame, with different scores.  The ones listed below are absolute scores where the L2 norm of the baseline mesh is 5.64.

The one blamed function is:

- `mfem/linalg/densemat.cpp:3689 mfem::AddMult_a_AAt(double, mfem::DenseMatrix const&, mfem::DenseMatrix&)`

The compilations with their L2 norms are:

- `g++ -O3 -mavx2 -mfma` (score 10.9)
- `icpc -O2 -march=core-avx2` (score 10.4)
- `icpc -O3 -march=core-avx2` (score 10.4)
- `g++ -O2 -mavx2 -mfma` (score 10.9)
- `icpc -O3 -fp-model=extended` (score 11.1)
- `icpc -O2 -fp-model=extended` (score 11.1)

I believe this requires further investigation.  At least based on the flags used, AVX2, FMA, and higher precision intermediates are likely culprits (depending on the compilation).  The function in question performs a scalar and matrix multiplication followed by a matrix addition.

`AAt = AAt + a * A * A.transpose()`

where `a` is a scalar, `A` is a matrix, and `AAt` is a matrix.  This is easily vectorizable and capable of utilizing FMA.  Either extreme catastrophic cancellation is occurring or the algorithm itself is numerically sensitive to small variations in this matrix operation.

## Conclusion

I believe these two tests warrant further investigation by the MFEM team to see about making these functions more robust or documenting that particular compiler optimizations are unsafe if using one of these two methods.  I am unsure if other relative errors are sufficiently small to safely ignore effects of compiler optimizations.

**Comment by tzanio** [comment]
This will be discussed in a meeting at LLNL on 11/12/19.
