### ISSUE TITLE
Get DOFs of values at boundaries in DG

### ISSUE THREAD

**Issue by vikramsg** [mfem/mfem#899]
Suppose I have a DG finite element space setup with Gauss Lobatto points and I ensure that the integration for the Mass or derivative matrices are done at the Gauss Lobatto points so that the mass matrix is diagonal. 

The gridfunctions generated on this finite element space therefore have values at the boundaries of the elements, since the Gauss Lobatto points include the boundaries. Is there a way to get the DOF number of the values that are only on the boundaries of each elements?

**Comment by tzanio** [comment]
The interior dofs are numbered last, both on element and global level, so you can just skip them?

**Comment by vikramsg** [comment]
Thanks. I will have a look. Will close this for now and reopen if I have further questions.
