### ISSUE TITLE
Сompare MFEM against other FEM software

### ISSUE THREAD

**Issue by kostyfisik** [mfem/mfem#90]
Hi,

I would like to provide a good comparison of available FEM software for newcomers willing to become a FEM pro. There is a GitHub page [FEA-compare](https://github.com/kostyfisik/FEA-compare)  and a [HTML copy](https://cdn.rawgit.com/kostyfisik/FEA-compare/2e98ff8c84e66f7d8d9ab6c4c61db5e62c6d8d02/table.html) of the comparison table in its current revision with fixed first column and row for ease of exploration. As far as to provide a good feature review of any FEM software you need to master it first, this way I would like to ask any MFEM enthusiast to provide such a profile. 

MFEM looks to be a distinguished player just due to its origin. :) In 
"Performance" section of the documentation I would expect to see plots for weak scaling of e.g. example 3p program, however, I was not able to locate them.

Could anyone provide such a profile for MFEM software? Users of GetFEM++, Deal.II, ElmerFEM, FEniCS and few others had already contributed feature lists for their favorite FEM package. Fill free to provide any data for the same feature as listed or you can provide any new features, that can be important for such a comparison. The preferred way to contribute is a GitHub pull request with a profile (this way it should be easy to combine profiles from several users). The [blank profile](https://github.com/kostyfisik/FEA-compare/blob/master/main-keys.txt) and [filled examples](https://github.com/kostyfisik/FEA-compare/tree/master/profiles) are available. Python script to generate a table using profiles is also provided. If any questions feel free to mention me @GitHub

Best regards,
Konstantin Ladutenko

**Comment by kostyfisik** [comment]
The question tag was not automatically assigned...

**Comment by tzanio** [comment]
Hi Konstantin,

Thanks for reaching out. We don't have the resources for a full reply to your request at the present time, but we will keep it in mind for the future.

Do you plan to make this available anywhere else? It will be nice to update for example the Wikipedia page https://en.wikipedia.org/wiki/List_of_finite_element_software_packages.

Cheers,
Tzanio

**Comment by kostyfisik** [comment]
Good idea. I hope I will have some time to do it on winter vacations! Filled the issue https://github.com/kostyfisik/FEA-compare/issues/5
