### ISSUE TITLE
Interface label for partitioned mesh

### ISSUE THREAD

**Issue by tomathew** [mfem/mfem#901]
Hello,
I would like to know if it's possible to access the interface boundary of partitioned meshes in mfem. Is there exist any examples to look for or any method that returns the interface bdr_attribute of partitioned meshes.
And ...
(1). Are there any examples in any branches in mfem that deal with Schwarz ddm ?
(2). Are there any examples, where an out-of-box Krylov solver is attempted ?
And I hope the restriction operator found in mfem is not related to partitioning, than to adaptivitty. Is it possible to inherit from this to create restriction operators for sub-domains ?
Thankfully,
Tom

**Comment by tomathew** [comment]
Everything is clear for me in the above query, except how to access interface bdr_attribute. I am aware there exist interfacial FE but, I would like to define transmission conditions at the interface when using Nedelec finite elements. 
Any suggestion would be appreciated

**Comment by tomathew** [comment]
Though I mentioned everything is clear, any suggestion or possible direction would be highly appreciated 
Thanks

**Comment by v-dobrev** [comment]
Hi @tomathew,

The set of boundary elements and their boundary attributes are typically independent of the parallel mesh partitioning. If you are referring to the edges (2D) or faces (3D) that form the interface between processors, we call these shared edges/faces in the `ParMesh` class. These shared edges/faces do not have special integer attributes attached to them. What type of operations do you need to perform with these interface elements?

**Comment by tomathew** [comment]
Hello @v-dobrev,
I would like to try a method where Optimized transmission conditions are imposed at the interfaces. Like in Optimized Restricted Additive Schwarz techniques, like the ones in https://hal.archives-ouvertes.fr/hal-01244511/file/DDM_getdp.pdf . I have a plan to try to inherit your iterative solver class to implement these ORAS iterative schemes in mfem or as a PETSCSolver, just to give it a try.
Thanks,
Tom

**Comment by tzanio** [comment]
I'm closing this issue now, but please let us know how it goes @tomathew
