### ISSUE TITLE
SUNDIALS feature request

### ISSUE THREAD

**Issue by ianabel** [mfem/mfem#916]
Hi,

I see @gardner48 is rewriting the sundials interface for Sundials 4/5 compatability.
Currently there's no way to invoke KINSetMAA (enabling Anderson acceleration for KIN_FP/KIN_PICARD) through the MFEM interface. If it's all being rewritten anyway, I won't make a pr against master to enable this (it's a few lines as far as I can tell).

Also -- my current method of using the picard solver interface involves a bit of a hack to provide a linear operator (and just make 'GetGradient' a no-op). The interface in MFEM for providing a linear operator is quite tailored to the newton method. If using one with KIN_PICARD could be streamlined/documented in the next iteration of the interface that would be fantastic.

Happy to code these and provide a patch once the new interface is merged,

Thanks for all the great work on this library!

Ian

**Comment by tzanio** [comment]
@gardner48, can you comment on @ianabel's questions?

**Comment by gardner48** [comment]
@ianabel I'll add a wrapper for `KINSetMAA` in the new Sundials interface (you're right that this will only take a couple of lines to do). In the mean time you can use the `SundialsMem` method to get the KINSOL memory structure and call `KINSetMAA` directly. 

The KINSOL interface was written with a focus on using Newton's method and I've followed this design in the new interface but I'll take a look at making it easier to use the Picard solver. What's your current hack for providing the linear operator?

**Comment by ianabel** [comment]
So, you can't just call KINSetMAA on the object directly, as the KINSOL interface specifies that SetMAA should be called between SetMaxIters and KinInit() so you want to call it inside SetOperator(). I am using a patched branch anyway, so I've patched the old interface.

As for KIN_PICARD, I had a strange hack set up along the following lines, but it doesn't work now. I'm surprised it ever did to be honest:

 I'm feeding a Solver object to KinSolver::SetSolver that has a dummy SetOperator method, which does nothing, and my nonlinear Operator object has 'GetGradient' return a dummy Operator object so KinSolver sets its internal jacobian pointer to the dummy object and then doesn't use it.

I also added a check in LinSysSolve so if we're doing Picard iterations then we just return instead of trying to calculate norms. 

It looks like a little more work to get this working perhaps. Certainly the KINSOL interface will just interpret the linear operator it is given as the one to use in the picard iterations. 

As an alternative, i'm just doing fixed point iterations and directly applying the linear inversion myself.

**Comment by ianabel** [comment]
One more query.  For the new interface, where a linear solver is required (both for newton and Picard), is there a more appropriate class in mfem than Solver? As far as I have discerned, Solver encapsulates the concept of a solver that can solve a *generic* linear problem. However, when interfacing with KINSOL, we are expected to pass a solver that solves only the specific problem at hand (be it muliplication by the inverse Jacobian, or inversion of the linear part of the nonlinear operator in a Picard inversion).

I'm not sure what class would be more appropriate however. Perhaps 'Operator' or something that can return an Operator reference when you set the point at which you want the Jacobian inverted? 

I may be completely off-base, and this may be too awkward within the existing mfem class hierarchy, which i'm only gradually getting to grips with.

**Comment by tzanio** [comment]
@gardner48 and @ianabel -- can we close this or is there an outstanding action item for SUNDIALS and/or MFEM?

**Comment by ianabel** [comment]
Now that Sundials 5.0.0 has been officially released, I'll test this interface out and close the bug hopefully.

**Comment by ianabel** [comment]
Well, given that the new sundials interface doesn't compile without MPI, we can't close this :)

@gardner48 -- there is some initialization done inside if(Parallel()) { .. } blocks that refers to MPI functions without being inside #ifdef MFEM_MPI. I guess most sundials builds will use MPI, and my test rig is a little odd.

**Comment by v-dobrev** [comment]
Thanks for pointing this out -- I guess we forgot to check the serial build + SUNDIALS -- I'll make a PR to fix this.

**Comment by acfisher** [comment]
Good catch, we will have to add serial+SUNDIALS to our testing suite.

**Comment by tzanio** [comment]
@ianabel -- can you check if #1147 with SUNDIALS 5.0 works for you?

**Comment by ianabel** [comment]
Compiles and the KINSolver class works well. 

However, there seems to be a bug in the Anderson Acceleration. Don't know if it's in the interface or sundials itself.

I think we should close this bug and if I can produce a nice minimal test case, I'll raise a new bug.

**Comment by ianabel** [comment]
OK, so it's a quirk of the Anderson Acceleration algorithm itself, and the SUNDIALS implementation is at worst mildly non-robust. :)

I'll bring this up with the KINSol team, and close this.
