### ISSUE TITLE
Use true Dofs to evolve a block system

### ISSUE THREAD

**Issue by tangqi** [mfem/mfem#920]
Hi,
My parallel code works well when I use dofs as unknowns in my BlockVector. But I think I need to change it to using true dofs to define `TimeDepenedentOperator::Mult` because I want to link Mult with petsc and it is easy to use true dofs in the linear/nonlinear solver (so that petsc only deals with linear algebra dofs). But I run into some troubles in mfem.

My following code is working for np=1. 
```c++
   Nv = new ParBilinearForm(&fespace);
   Nv->AddDomainIntegrator(new ConvectionIntegrator(velocity));
   Nv->Assemble(); 
  ...
   Nv->Mult(psi, z); //here psi and z have size of true dofs
```
Apparently, it is not working for multiple processors. So I changed it to
```c++
   Nv = new ParBilinearForm(&fespace);
   Nv->AddDomainIntegrator(new ConvectionIntegrator(velocity));
   Nv->Assemble(); 
   HypreParMatrix Nvmat;
   Nv->FormSystemMatrix(ess_tdof_list, Nvmat);
  ...
   Nvmat.Mult(psi,z);
```
It generates different results even np=1. So I think I probably miss something. (Looks like I missed a boundary term.)

There are several options I could think of
```c++
  z=0.;
  Nv->TrueAddMult(psi, z); 
```
or I could recover GridFunction using `SetFromTrueVector`. Another way is to define a linear form that is equivalent to this operator. I am wondering if there is a better way.

Qi

**Comment by jandrej** [comment]
Hi,

the decision depends on how you use the vectors in the solution process. I can only recommend looking closely at the diagram on [mfem.org/pri-dual-vec](https://mfem.org/pri-dual-vec/) and make your decision based on where you are going to have the least conversion from one to the other.

The parallel [example 16](https://github.com/mfem/mfem/blob/master/examples/ex16p.cpp) defines the `TimeDependentOperator` on the true dofs as you mentioned, but works with assembled matrices.

Avoiding the parallel assembly involves, as you stated, using `TrueAddMult`.

**Comment by tangqi** [comment]
Thanks @jandrej for your suggestion. I get it working by using   
```c++
  z=0.;
  Nv->TrueAddMult(psi, z);
```
Looks like I really need `Nv->TrueMult` but it is not available.  

But I want to follow up your point a little bit. If  I understand your correctly, when I only do `Nv->Assemble()`, I essentially avoid parallle assembly? If it is true, this is very useful as I essentially implement my nonlinear operator through `Nv`. 

Qi

**Comment by jandrej** [comment]
If you use `Nv->Assemble()` and `Nv` is a `ParBilinearForm` you only assemble the matrix on each processor and does not create a parallel assembled matrix. It propagates to the serial method `BilinearForm::Assemble` in most cases.

Using `ParallelAssemble` or `FormLinearSystem` creates your parallel sparse matrix (either in HypreParMatrix or PetscParMatrix format, depending on the choice of the OpType).

**Comment by tangqi** [comment]
Thanks @jandrej . That is great to know!

One quick question: is `M->FormSystemMatrix(ess_tdof_list, Mmat)` identical to `EliminateEssentialBC` plus `ParallelAssemble`? If so, would you recommend one over another?

**Comment by jandrej** [comment]
This is a bit more complicated to answer. `FormSystemMatrix` eliminates the essential boundary conditions on the assembled parallel matrix, while `EliminateEssentialBC` operates on the `ParBilinearForm` directly (and therefore on the local `SparseMat`).

When in doubt, use `FormSystemMatrix` and `FormLinearSystem`. I know this is not always possible.

**Comment by tangqi** [comment]
That is good to know. Thanks again. --Qi

**Comment by tangqi** [comment]
Hi, I have a question related to `MakeTRef`. 

Based on ex10p and petsc/ex10p, I define my own `ReducedSystemOperator` inside my `TimeDependentOperator`. In `ReducedSystemOperator::Mult(const Vector &k, Vector &y)`, for some reason, I have to recover the current solution from the block vector `k` by `gf.MakeTRef(&fespace, k, 0); gf.SetFromTrueVector();` Apparently, I cannot because `MakeTRef` takes in `Vector&` instead of `const Vector&`. By looking at the code, I think I can do the following inside my  `TimeDependentOperator::ImplicitSolve(const double dt, const Vector &vx, Vector &k)`. I think I could link gf with `k` in `ImplicitSolve` and then call `gf.SetFromTrueVector()` in `ReducedSystemOperator` to update the current solution.

So I just want to confirm if `k` in `TimeDependentOperator::ImplicitSolve` is the same as `k` in `ReducedSystemOperator::Mult`. (This should also be independent from one using petsc or mfem nonlinear solver.) Isn't it? Thanks a lot!

Qi

**Comment by v-dobrev** [comment]
Hi @tangqi,

It is probably best not to rely on this type of relation -- that the last argument of `TimeDependentOperator::ImplicitSolve` will be passed as the first argument of `ReducedSystemOperator::Mult` (via the `NewtonSolver::Mult` call).

A better solution is to simply replace `k` with `const_cast<Vector &>(k)` in the call to `MakeTRef` -- since you are not really going to modify the internal true-dof vector of `gf`, this should be safe.

**Comment by tangqi** [comment]
@v-dobrev Thanks a lot for the great suggestion! It is exactly what I need.
