### ISSUE TITLE
'HYPER_config.h' not found

### ISSUE THREAD

**Issue by Heatherms27** [mfem/mfem#924]
I'm trying to build the parallel version of MFEM according to https://mfem.org/building/ specifications.
I installed hypre in the same parent directory as MFEM using the configuration
     ./configure --disable-fortran CC=mpicc
which the only way I could get it to configure and make.

Now I'm running 'make parallel -j' in the mfem-3.4 directory and I'm getting the error:
     /Applications/Xcode.app/Contents/Developer/usr/bin/make -C config all
     mpicxx -I../../hypre-2.10.0b/src/hypre/include get_hypre_version.cpp -o get_hypre_version
     get_hypre_version.cpp:12:10: fatal error: 'HYPRE_config.h' file not found
     #include "HYPRE_config.h"
I also noticed that the path to hypre should only have one leading '../' , not two, but I'm not sure how to change it.

Any ideas how I can fix this?

**Comment by mlstowell** [comment]
Hi, @Heatherms27 ,
I hope you were able to resolve this issue and didn't simply give up on us.
Best wishes,
Mark

**Comment by Heatherms27** [comment]
Oh, I figured it out! I didn't read directions carefully and didn't change the default.mk file

**Comment by BMartins87** [comment]
how do you solve the problem?
I have the same issue

**Comment by Heatherms27** [comment]
My issue was that there is a file called "default.mk" that I forgot to change. It mentions in the configuration instructions to edit your installation paths in this file but I had skipped this step.

**Comment by BMartins87** [comment]
I understood, if you change the folder do mfem instead of mfem-4.0  it works also.
Thank you very much!
