### ISSUE TITLE
Mass matrix for system of equation using DGFEM

### ISSUE THREAD

**Issue by delcmo** [mfem/mfem#925]
Hello,

I am trying to build a mass matrix for a system of equation using DGFEM. Assuming I have a system of N equations, how do I build the mass matrix for the whole system of equations?

I have tried:
```
  mfem::DG_FECollection fec(order, 
                            dim, 
                            mfem::BasisType::Positive);
  mfem::ParFiniteElementSpace vfes(pmesh.get(), 
                                   &fec, 
                                   num_equation,
                                   mfem::Ordering::byNODES);

  mfem::ParBilinearForm m(&dfes);
  m.AddDomainIntegrator(new mfem::MassIntegrator);
  m.Assemble();
  m.Finalize();

```

but I get the following error message:
`Assertion failed: (data && i >= 0 && i < height && j >= 0 && j < width) is false`
Thanks,

Marco

**Comment by vladotomov** [comment]
Where is the definition of `dfes`?

**Comment by delcmo** [comment]
Sorry I meant `mfem::ParBilinearForm m(&vfes);`

Marco

**Comment by v-dobrev** [comment]
Hi @delcmo,

You should use the `VectorMassIntegrator` and use its `SetVDim()` method to set the number of vector components you have -- the same value as in the `ParFiniteElementSpace`.
