### ISSUE TITLE
Static condensation failing in sample runs 

### ISSUE THREAD

**Issue by mlstowell** [mfem/mfem#928]
I was using `autotest` to compare a new branch with master and accidentally found that many, if not all, of the sample runs involving static condensation are failing in the master branch.

For example,
```
mpirun -np 4 ex1p -m ../data/mobius-strip.mesh -o -1 -sc -no-vis
```
fails to converge both in parallel and serial.

Static condensation depends on the trace `FE_Collection` and the `FiniteElementSpace` and impacts matrix construction in the `BilinearForm`.  Beyond that I'm not sure where to look.

Any suggestions would be appreciated.

**Comment by v-dobrev** [comment]
I cannot reproduce the failures. What type of machine and build options do you use?

**Comment by tzanio** [comment]
This also works for me on the host (it hasn't been ported on the device yet, so e.g. `-d cuda` fails)

**Comment by camierjs** [comment]
I can't neither reproduce it, @mlstowell.

**Comment by mlstowell** [comment]
Well, this is odd.  When I initially noticed the problem the code was running on my Mac running macOS Mojave 10.14.5.  This was executed through the `autotest` scripts:
```./autotest -t sample-runs-baseline -b master -r github```
I had just recently upgraded the operating system on this computer so I was suspicious that the new compilers/environment may have been at fault.  I then cloned the latest copy of master on quartz and ran `ex1p` manually.  This produced the same results as `autotest`.  I had a few nonstandard options turned on, such as NETCDF, so I just reran with a more standard configuration, shown below, but the problem persists.
```
MFEM_USE_MPI           = YES
MFEM_USE_METIS         = $(MFEM_USE_MPI)
MFEM_USE_METIS_5       = NO
MFEM_DEBUG             = YES
MFEM_USE_EXCEPTIONS    = NO
MFEM_USE_GZSTREAM      = NO
MFEM_USE_LIBUNWIND     = NO
MFEM_USE_LAPACK        = YES
MFEM_THREAD_SAFE       = NO
MFEM_USE_OPENMP        = NO
MFEM_USE_LEGACY_OPENMP = NO
MFEM_USE_MEMALLOC      = YES
MFEM_TIMER_TYPE        = $(if $(NOTMAC),2,4)
MFEM_USE_SUNDIALS      = NO
MFEM_USE_MESQUITE      = NO
MFEM_USE_SUITESPARSE   = NO
MFEM_USE_SUPERLU       = NO
MFEM_USE_STRUMPACK     = NO
MFEM_USE_GECKO         = NO
MFEM_USE_GNUTLS        = NO
MFEM_USE_NETCDF        = NO
MFEM_USE_PETSC         = NO
MFEM_USE_MPFR          = NO
MFEM_USE_SIDRE         = NO
MFEM_USE_CONDUIT       = NO
MFEM_USE_PUMI          = NO
MFEM_USE_CUDA          = NO
MFEM_USE_RAJA          = NO
MFEM_USE_OCCA          = NO
MFEM_USE_MM            = NO
``` 
These setting appear in my `config/user.mk` file.  Everything else in that file is a direct copy of `config/defaults.mk`.  I have not rebuilt my copies of HYPRE recently (on either platform).  Could that be an issue?

**Comment by mlstowell** [comment]
Another thing that I should have mentioned is the compiler being used on quartz:
```
quartz764{stowell}42: which mpicxx
/usr/tce/packages/mvapich2/mvapich2-2.3-intel-18.0.1/bin/mpicxx
```

**Comment by v-dobrev** [comment]
OK, I was able to reproduce the failure. It only happens with `MFEM_USE_LAPACK=YES`. In the branch `memory-dev` which we plan on merging soon, this is not an issue. In that branch, I reverted some GPU related changes in `densemat.cpp` which are probably the source of the issue.

**Comment by mlstowell** [comment]
Great, thanks Veselin!
