### ISSUE TITLE
How to make an input file for solving structural problem

### ISSUE THREAD

**Issue by hishamop** [mfem/mfem#93]
I am trying to develop a program for solving non-linear structural mechanics problems using the concepts of Finite element and optimisation as part of my research. Previously I was using Matlab for prototype making. Since I'm a beginner in C++ and computational science, I couldn't understand how to use Vtk or other type of mesh format in a structural engineer's perspective., i.e how to input nodes, elements, loading (distributed loads and nodal loads) and boundary conditions (dof). Could anyone please show me an example of an input file which contain quadrilateral plane stress element and load and B.C ?

**Comment by v-dobrev** [comment]
Hello,

I would recommend looking at [Example 2](https://github.com/mfem/mfem/blob/master/examples/ex2.cpp) which can solve linear elastic problems on both 2D and 3D meshes. For example, you can try the following sample run:
```bash
./ex2 -m ../data/beam-quad.mesh
```
The mesh file `../data/beam-quad.mesh` is a 2D beam mesh of quadrilaterals - see http://mfem.org/mesh-formats for a description of the mesh format. The load and B.C. are specified inside the code, see steps 6 (b.c.) and 7 (load).

Hope this helps,
Veselin
