### ISSUE TITLE
Support for HYPRE_MIXEDINT

### ISSUE THREAD

**Issue by stefanozampini** [mfem/mfem#933]
Recent HYPRE 2.16.10 has support for "mixed integers" which is not handled at all by MFEM.
We should at least abort at configure time if HYPRE_MIXEDINT is defined.
This is the set of changes I just added to PETSc https://bitbucket.org/petsc/petsc/commits/df10dfa47f7c91c0063b914b5ef40dc94e48546e?at=master

**Comment by tzanio** [comment]
This is a priority for this year, and on our todo list for MFEM-4.1. Lets move the discussion to #931.
