### ISSUE TITLE
How to generate Parallel Mesh without loading a serial mesh on all MPI processes

### ISSUE THREAD

**Issue by sshiraiwa** [mfem/mfem#934]
First, congratulations to the team for the 4.0 release. 

I have a question about making a parallel mesh. Right now, I load a mesh file to the all MPI
node and call a constructor. This works perfectly fine when the mesh is small and when I
refine it later after ParMesh is made.  However, when the mesh is already large, I ran into the situation in which reading such a large file to every MPI jobs consumed too much memory and therefore I can not take advantage of all CPU cores (even although I know that memory for the serial mesh is freed after ParMesh is generated). What is the good way in this circumstance? For example, is it possible to load a mesh and make a portioning on the root node and distribute it among nodes? Thank you for your advice.

**Comment by mlstowell** [comment]
This is an excellent question but unfortunately I do not know the answer.  It is possible to use the `mesh-explorer` miniapp to read a mesh in serial and generate a partitioning which it writes to a file, `partitioning.txt`.  We have a `ParMesh` constructor that can read a partitioned mesh from a collection of data files but this is different.  The piece that seems to be missing is the code that can read the partitioning file along with the serial mesh file and create a distributed mesh either as a collection of files or in memory as a `ParMesh` object.

Unless someone else knows of a solution that I've missed, I can put something together.

**Comment by sshiraiwa** [comment]
Hi, Mark
Thank you for prompt response. Yes, that is exactly what I was looking for. I am not aware that mesh explorer can generate partitioning.txt.

**Comment by rcarson3** [comment]
@mlstowell I'm wondering if it might also be possible to have that partitioning functionality included in part of the main MFEM library, so we could generate that partitioning at run time on just a single rank. Then you could use a simple ```MPI_Scatter``` or ```MPI_ScatterV``` call to send that partitioning off to everyone.  Afterwards, you could use that information to tell the ```ParMesh``` object creation for each rank what sections does it actually care about while reading in the serial mesh.

**Comment by mlstowell** [comment]
Hi, @rcarson3 ,
Actually the partitioning functionality is already part of MFEM.  The `mesh-explorer` miniapp simply calls the method `Mesh::GeneratePartitioning()`.  The output of this could indeed be scattered amongst the processors as you describe.  The missing piece, as far as I can tell, is the `ParMesh` constructor which would use this partitioning to read the appropriate portion of a serial mesh from disk.  I think this is possible but it is likely to be tedious because the mesh class has separate sections of code in `mesh_reader.cpp` for each mesh file type and each of these would need to be altered to support reading only the local portion of a mesh.
Best wishes,
Mark

**Comment by cwsmith** [comment]
The PUMI interface can load a distributed mesh:

https://github.com/mfem/mfem/blob/edfb62d8c27061a0de2b495eceffcee266b3d2cb/examples/pumi/ex6p.cpp

**Comment by rcarson3** [comment]
I'm curious if this same idea of not loading up the serial mesh on all the processors could also be extended to auto-generated meshes. Within ExaConstit, I need to be able to generate auto-generate a mesh with linear hexahedron elements, and then map data from a voxel data set onto that mesh for certain simulations that I might run. Currently, the voxel data is essentially just an element attribute number but this might change in the future. So, I can't exactly start off with a rough mesh, and then refine it once it's in the ```ParMesh``` format. 

I could see a couple of ways this could be handled so every processor is no longer generating the serial mesh:

- Require the user to do a preprocessing step where the mesh is generated in serial originally and is then saved off in the partitioned format for the number of processors they want to run the job on. You could then read in a distributed mesh using the potential methods talked about above.

- Generate the mesh and partitioning in serial on either a single processor or a single processor per node, and then distribute the necessary info from that mesh out to the other processors which could then be used in a new instantiation function for ```ParMesh```.

- The last option which I imagine might require the most amount of work but could be quite beneficial if one were to want to generate a mesh with tens of millions of elements would be to create a ```ParMesh``` equivalent of the auto generated mesh in serial.

**Comment by vladotomov** [comment]
The second way you mentioned is implemented in the branch pmesh-constr. There is no documentation, as we had to write it quickly to execute a big run. With that, the serial mesh can be constructed only on one task per node (which will help only if each task sees the whole memory space of the node). I believe the new constructors worked in the end.

**Comment by tzanio** [comment]
@sshiraiwa, sorry for the late response.

If I understand correctly you can just use the first approach suggested by @rcarson3.

Specifically, have an "pre-processing" run where you define the parallel mesh and save it with `ParMesh::ParPrint()`, see https://github.com/mfem/mfem/blob/master/mesh/pmesh.hpp#L320. This will generate one file per MPI task. You can then have the "production" run where the parallel mesh is read directly with this constructor: https://github.com/mfem/mfem/blob/master/mesh/pmesh.hpp#L204-L206.

Hope this helps,
Tzanio

**Comment by sshiraiwa** [comment]
All, 

Thank you for your suggestions. I will try the file based approach.

The actual use case is little bit more involved. I have a ParMesh consisting from multiple domains
which are labeled using attributed. Then, I make another mesh object which contains only
one of domains. This is done in parallel, in other word, each process collects the information 
of elements it owns, resolving the face/edge/vertex sharing relationship. But at the very end, in order to redistribute the new mesh uniformly, I am making a new Mesh and converting it to ParMesh. So, ideally, it may be better if I can do the last step w/o involving the file I/O. 
But, on the other hand, since this step happens only once during a pre-processing before the matrix assembly, perhaps having file I/O is not too bad.

Again, thanks a lot.

**Comment by v-dobrev** [comment]
See https://github.com/mfem/mfem/pull/2669.
