### ISSUE TITLE
Error with configuration.ac

### ISSUE THREAD

**Issue by e-aranda** [mfem/mfem#935]
Hi,

I am developing a tool which needs MFEM and I am using autotools for checking libraries and headers. Last version of MFEM gives error with usability of mfem.hpp in a Mac. Essentially the error is:

```
In file included from /Users/earanda/toptimiz3D/include/mfem/mesh/../fem/../general/device.hpp:16:
/Users/earanda/toptimiz3D/include/mfem/linalg/../general/mem_manager.hpp:545:48: error: type 'mfem::MemoryType' cannot be used prior to '::' because it has no members
       MemoryManager::Delete_(h_ptr, flags) == MemoryType::HOST)
```

Version 3.4 worked fine.

Any hint about how to solve this? Thanks in advance

**Comment by e-aranda** [comment]
I have created a minimum example where the problem can be reproduced.
[configtest.zip](https://github.com/mfem/mfem/files/3232929/configtest.zip)
This file contains a folder with a `configure.ac` script. Go to the folder and create tools with
```
autoreconf -i
```
After that, `configure` script can be checked with
```
./configure CPPFLAGS=-I/path/to/mfem/folder LDFLAGS=-L/path/to/mfem/folder
```
In Linux, the last command works well, but in Mac, we have an error.

**Comment by v-dobrev** [comment]
Can you post the compiler line that fails?

**Comment by e-aranda** [comment]
The result of `configure` is:

```
checking mfem.hpp usability... no
checking mfem.hpp presence... yes
configure: WARNING: mfem.hpp: present but cannot be compiled
configure: WARNING: mfem.hpp:     check for missing prerequisite headers?
configure: WARNING: mfem.hpp: see the Autoconf documentation
configure: WARNING: mfem.hpp:     section "Present But Cannot Be Compiled"
configure: WARNING: mfem.hpp: proceeding with the compiler's result
...
configure: error: cannot find mfem.hpp
```
I attach the `config.log`. Errors start at line 466
[config.log](https://github.com/mfem/mfem/files/3235902/config.log)

**Comment by v-dobrev** [comment]
I think the issue may be that you do not enable c++11 support (e.g. using `-std=c++11`) -- this is now required by mfem.

**Comment by e-aranda** [comment]
Thanks Veselin, that was the problem.
