### ISSUE TITLE
Global numbering of mesh elements and conforming vertices in a non-conforming mesh

### ISSUE THREAD

**Issue by cwsmith** [mfem/mfem#939]
I'm calling a parmetis-like interface to our load balancing tool and would like to access 
1) global numbering of leaf mesh elements and 
2) global numbering of conforming vertices in a non-conforming mesh.  

Do these numberings already exist in the `NCMesh` or `ParNCMesh` classes?

In the CEED call today it was mentioned that there is an 'implied' global numbering for mesh elements.  More information on this would be helpful.

Also in the call it was suggested that an H1 linear space could be created to get global numbering of conforming vertices (DOF holders) and that the resulting space provides helper functions to map from local ids to global ids.  There was some concern about this approach as opposed to one that uses the topological data stored for the ncmesh.  Note, at this point we are primarily focused on understanding the partition quality versus assembly and solve execution time and may be willing to accept a less than optimal code path.

**Comment by jakubcerveny** [comment]
The first one is probably easier. The member `NCMesh::Element::index` holds the local leaf index. If added to a global index of the first local element, you should get what you need. The global index of the first element is calculated in `ParNCMesh::Rebalance`, variable `first_elem_global` (see how it is used in the call to `Partition`). This should also be doable with `Mesh` completely from user code, the `Mesh` elements are ordered by `NCMesh::Element::index`.

As for numbering conforming vertices only, there is no such thing explicitly in `ParNCMesh`. The approach with a linear H1 space sounds reasonable. The method `GetGlobalTDofNumber` in `ParFiniteElementSpace` should help here (although off the top of my head I'm not 100% sure).

**Comment by jakubcerveny** [comment]
The 'remote id' is not stored anywhere. You are right that `leaf_glob_order` is probably what you need, it's the original SFC order of leaf elements regardless if they are ghosts or not. Later the ghosts are moved to the back of the array `leaf_elements` so they are not interspersed among regular local elements.

**Comment by jakubcerveny** [comment]
Note that #1058 provides API for global element numbering.

**Comment by cwsmith** [comment]
Nice!  Thank you.  

So, IIIUC, the call syntax for getting the global id of a ghosted element would be:
 `long ghostElmGlobalId = GetGlobalElementNum(ghostElmLocalId)` 
Is that correct?

**Comment by jakubcerveny** [comment]
Oh, I forgot you need ghost elements. I'm afraid #1058 doesn't work for ghost elements :-(

**Comment by tzanio** [comment]
@jakubcerveny -- is this still outstanding? @cwsmith -- do you still need this functionality?

**Comment by cwsmith** [comment]
This functionality is still needed.

My [current code](https://github.com/cwsmith/mfem/commits/cws/engpar) uses `leaf_glob_order` in `pncmesh.cpp`.  When I last worked on this I recall there being a numbering inconsistency that needed resolving.

Does a `L2_FECollection(0, meshDim)`, as created here (#1142):
https://github.com/mfem/mfem/blob/2ac85b13c287f679d28013f3b78dee6fd1d3e863/tests/unit/fem/ptest_tdofs.cpp#L319-L327
globally number both owned and ghost elements?  If so, this seems cleaner than keeping `leaf_glob_order` around.

**Comment by jakubcerveny** [comment]
There are no ghost elements in MFEM other than internally in ParNCMesh. The `L2_Collection` trick will work, but you won't see any ghost elements numbered. For that you need to go inside ParNCMesh and look at `leaf_glob_order` (which is not optimal because this array is temporary and used for something else).

**Comment by cwsmith** [comment]
OK.  Thank you.
