### ISSUE TITLE
Local matrix generation

### ISSUE THREAD

**Issue by jxb3641** [mfem/mfem#94]
Hello,

I am a student working with professor Ludmil Zikatanov here at PSU on a numerically stable finite element discretization of poroelasticity on simplices of dimensions 2 and 3, and I am trying to learn as much as I can about MFEM, as he recommended using MFEM to discretize and solve the resulting system.  Right now, I am having some trouble figuring out how to generate the block matrix that needs to be solved per time step; in particular, I am looking for which class generates the local stiffness matrix for the standard Laplacian, as I need to use this to generate a matrix in the block.  

I would prefer to work with the built-in classes to make this operator naturally rather than generate the SparseMatrix manually, but as I only have the base examples, I am having trouble finding exactly where I would have to adjust the code to generate the SparseMatrices from the FiniteElement classes.  I would greatly appreciate either a more detailed example or explanation of how the FiniteElement and BilinearForm classes interact, particularly which classes deal with generating the SparseMatrices discretizing the bilinear forms.

Thanks!

Juan

**Comment by jakubcerveny** [comment]
Hi Juan,

In ex1.cpp, the line "a->Assemble();" will take you to the method
BilinearForm::Assemble, whose implementation you can inspect. Here, the
local element matrices are obtained with the various calls to
BilinearFormIntegrator::AssembleElementMatrix.

It is perfectly possible to call AssembleElementMatrix (e.g.,
DiffusionIntegrator::AssembleElementMatrix) from your own code.

Hope that helps,
Jakub

**Comment by tzanio** [comment]
Hi Juan, were you able to accomplish you goal? Let us know if you have any further questions..,

**Comment by jxb3641** [comment]
Sorry Tzanio,

I have been travelling and havent had internet for the past few days.  I
was able to get my code to compile but havent had the time to thoroughly
test the new derived class of BilinearFormIntegrator I was coding up yet.
I will be back in the US by Wednesday, so hopefully I can run through some
tests then.

Thanks for the diligence in helping me!

Juan

**Comment by jxb3641** [comment]
Hey Tzanio,

I just started working on getting my example script to run, and have run
into another problem.  My new derived class
('BubbleDiffusionIntegrator', derived from 'DiffusionIntegrator') has
compiled correctly, but now when I try to run an adjusted 'ex1' script
where all I do is change line 142 from this:

a->AddDomainIntegrator(new DiffusionIntegrator(one));

to this:

a->AddDomainIntegrator(new BubbleDiffusionIntegrator(one));

I run into an error at this line: "error: expected type-specifier before
'BubbleDiffusionIntegrator'".  I think the problem is that because i'm
trying to build this example separate of the make library process, it might
not have the proper #include 's required.  Is there an easy way to adjust
the makefile called when building all the examples to make it compile
properly?

Thanks again!

Juan

P.S. Sorry I couldn't attend your talks you gave here at PSU on Monday, I
had some family business I had to attend to back in Puerto Rico.  I would
have loved to hear more about the package, could you send me the slides you
presented?

**Comment by tzanio** [comment]
Hi Juan,

It looks like the source for your `BubbleDiffusionIntegrator` has not been included before `main()`. Is that in `bilininteg.hpp` or another file? If it is in the former, you should be able just to rebuild and link your example with `make your-example-name` in the `examples` directory. In the latter case, make sure that you have included the new source files and headers.

Hope this helps,
Tzanio

**Comment by jxb3641** [comment]
Hey Tzanio,

I got the modified example 1 to work.  Thanks so much for the help! Now I
have to incorporate this new matrix into example 5, as I am working on
poroelasticity, which essentially incorporates examples 2 and 5 into a sole
problem.  I will begin work on this today, hopefully it shouldn't take too
long to assemble, and thanks to your help I feel like I should be able to
make it relatively simply.  Sorry to ask again, but if you prepared slides
for your presentation a week ago here at PSU, i was wondering if you could
send them to me to read through?

Thanks!

Juan Batista

**Comment by tzanio** [comment]
Hi Juan,

Glad to hear you got it working. Can you email me directly and I'll send you some slides.

Cheers,
Tzanio
