### ISSUE TITLE
Integrators for ultra-weak DPG method solving Poisson equation

### ISSUE THREAD

**Issue by ZhichaoPengMath** [mfem/mfem#943]
Dear mfem developers,

We are interested in examining the DPG framework (more general than ex8 and similar with HDG branch) for some plasma applications. 

Before moving to the real application, we want to start from the poisson equation.
              -\Delta u = f with Dirchlet Boundary condition.
Rewrite it into the first order form
                               q+\grad u = 0,
                                   div(q)  = f.
The ultra-weak form of DPG is based on the variational form:
          ( q, \tau) - (u, div(\tau) ) + < \hat{u}, \tau \cdot n > =0,
          -( q, \grad v)  + < \hat{q}, v> = (f,v),
with q \in L^2, u \in L^2, trace term \hat{u}\in H^{1/2} and trace term \hat{q} \in H^{-1/2}.
The trial space for q and u are L^2 and the test space is also L^2. For the test norm of the DPG method, we use
    || (\tau, v) ||_V ^2 := || \tau ||^2 + || div(\tau) ||^2 + ||v ||^2 + ||\grad v ||^2

After looking into the framework, I think we need to implement the following operators:
(1) Face Integrator: <u, [tau \cdot n]>, where tau in L2,
(2) Domain Integrator: (div tau1, div tau2), where tau1 tau2 in L2,
(3) Domain Integrator: (q, \grad v),  where q (vector), v (scalar) are in L2.

Are there any similar operators we could borrow? Any suggestions would be greatly appreciated.

Thank you very much!

Best,
Zhichao Peng

**Comment by psocratis** [comment]
Hi, 

For the operators that involve H^1 and H^1/2, you can follow example 8 and use the L2 space. 
The difficulty is for the (div tau1 , div tau2 ) and the <u, tau \cdot n> integrators. For these you need a broken (discontinuous) version of the H(div) space. This way the normal trace of tau makes sense on the boundary of an element. 
Currently this space is not in the code but I don't think is going to be hard to put there. 
Feel free to try it.

Best, 
Socratis

**Comment by ZhichaoPengMath** [comment]
Hi @psocratis ,

Thanks for your suggestions!

I think  I can use P^k(K) for the test space, since it is a subspace of the broken H(div) and H(1).

Do you think is it a good idea to modify VectorDivergenceIntegrator and use calcDshape, to build (div,div)? And for the \lgl u,[\tau \cdot n] \rgl, I guess I can check the HDG branch and modify NormalTraceJumpIntegrator.

Best,
Zhichao

**Comment by psocratis** [comment]
Hi @ZhichaoPengMath 

For the domain integrators, you can use the existing ones(e.g. (div , div )) but for a modified finite element collection. I think the easiest way is to create a "broken" version of RT elements (look how L2 is done). For the face integrator,  yes you need something similar to the NormalTraceJumpIntegrator but again \tau has to come from this broken space. 
To sum it up I would first start from the implementation of the broken finite element collection and then you probably have every integrator you need.

Hope this helps.

**Comment by ZhichaoPengMath** [comment]
Hi @psocratis,

Thanks again for your suggestions! 

In the 2011 paper, 
               ANALYSIS OF THE DPG METHOD FOR THE POISSON EQUATION∗
by L. DEMKOWICZ AND J. GOPALAKRISHNAN,
a discrete version of broken H(div) space Q^l_div(K) is used for the test space. I think the easiest way to implement this method is to follow what you suggest. 

I am actually following Jay. GOPALAKRISHNAN AND W. QIU's 2013 paper
                 AN ANALYSIS OF THE PRACTICAL DPG METHOD
In (3.3) on page 542 of this paper, I think they use the test space
          V^r=\{ \tau\in (P^r(K,\mathcal{V}) and v \in P^r(K) \}. 
I think this test space can be implemented with the help of L2_FE_collection. 

Do you think I understand everything correctly?

Mimicking VectorDiffusionIntegrator and VectorDivergenceIntegrator, I was able to define the face integrators. To test them, I wrote a code similar with test_2d_bilininteg.cpp, and they seem to work correctly. I also implemented the trace integrator, but I found it is harder to test the Trace Integrator. I may directly couple it with face integrators and test with some manufactured solutions. If you are willing to share any thoughts on how to test the trace integrator, I will be more than grateful.

Thanks for the discussions!

Best,
Zhichao

**Comment by ZhichaoPengMath** [comment]
Hi @psocratis ,

Thanks for the suggestions again.

In L. DEMKOWICZ AND J. GOPALAKRISHNAN's 2011 paper ANALYSIS OF THE DPG METHOD FOR THE POISSON EQUATION∗, Q^{div}_l is used for the test space. I think that space is not supported by the current MFEM work. And your suggestions seem to be the best way to implement it.

In J. GOPALAKRISHNAN AND W. QIU's 2013 paper AN ANALYSIS OF THE PRACTICAL DPG METHOD, their (3.3) suggests to use test space
V^r = \{ (\tau,v) \in the broken space: \tau\in P^r(K; vector), v \in P^r(K) \}.
I am following this paper, and I think the test space can be directly implemented with the help of L2_FECollection. Do you think I understand things correctly? 

Thanks!
Best,
Zhichao

**Comment by ZhichaoPengMath** [comment]
Hi @psocratis,

Thanks a lot for the fruitful discussions with you! 

Now, I finished implementing the DomainIntegrators and the FaceIntegrators. I wrote some 2D tests with manufactured solutions, and the correct results was given. 

Before moving to the real DPG code, I will close the issue for now and make a brief summary here, for the reference of myself and anyone interested in this issue.

(1) Notes on the test space:
I am following J. GOPALAKRISHNAN AND W. QIU's 2013 paper, and the test space is just the standard ``DG" space 
V^r = { (\tau,v) \in the broken space: \tau\in P^r(K; vector), v \in P^r(K) }. Things can be implemented with the help of L2_FECollection.

However, if one follows L. DEMKOWICZ AND J. GOPALAKRISHNAN's 2011 paper, a broken version of 
RT space needs to be implemented, and I guess the best way is to implement the FECollection as @psocratis suggested.

(2) DomainIntegrators can be implemented similar to VectorDivergenceIntegrator based on CalcShape 
and CalcDshape. Note that MFEM's original DivDivIntegrator requires RT space and uses CalcDivShape which is not supported for the L2_FECollection.

(3) FaceIntegrator: <u,[\tau \cdot n]>, can be implemented similar to the local1 of HDGFaceIntegratorDiffusion, which is under the HDG branch. Also, NormalTraceJumpIntegrator requires RT for the test space, so it can not be directly used, however, it is a great reference for our implementation.

(4) HDG branch also provides SkeletonMassIntegrato, SkeletonMassIntegratorRHS and ProjectCoefficientSkeletonDG, which is useful for imposing Dirichlet boundary condition through 
trace terms and designing manufactured solutions. Note that, the original ProjectCoefficient does not seem to work with trace finite element collections for now.

Thanks again for your help @psocratis!

Best,
Zhichao

**Comment by issabass** [comment]
Hello,
Dear @ZhichaoPengMath, have you successfully implemented this?
If so, it would be helpful to provide a minimal working example, please!
Thank you 
zaq

**Comment by ZhichaoPengMath** [comment]
Hello @issabass,
It was long time ago, so I do not remember all the details now. Sample code can be found on my MFEM fork:
https://github.com/ZhichaoPengMath/mfem/blob/master/fem/dpg_integrators.cpp
https://github.com/ZhichaoPengMath/mfem/blob/master/fem/dpg_integrators.hpp

For debugging, I used some manufactured solution, and you can check my tests in https://github.com/ZhichaoPengMath/mfem/blob/master/tests/unit/fem/test_pzc.cpp

One issue I want to mention is that, due to my implementation, < v, [n \cdot \tau ] > only works for the case there is no hanging node in your mesh. As a result, it only works for conforming adaptive mesh refinement (which is good enough for my application). A better implementation is needed, if you want to use non-conforming AMR. 

Just out of curiosity, are you trying to implement some DG code for diffusion equation?

Best,
Zhichao

> Hello,
> Dear @ZhichaoPengMath, have you successfully implemented this?
> If so, it would be helpful to provide a minimal working example, please!
> Thank you
> zaq

**Comment by issabass** [comment]
Dear @ZhichaoPengMath, thank you very much for the reply, for the useful input!
This is insightful and will surely help us set up our approach (SUPG/PSGD , which is similar to yours).
Yes, indeed, in the work we are planning to do; solving the diffusion equation in its first-order form 
represents the first step to accomplish.
Now, I am learning what is already available like your code, the one in HDG branch and 
of course the custom ex5.
Given your remark, "...it only works for conforming adaptive mesh refinement 
(which is good enough for my application)", I am not sure about what we will end up doing.
My hope is that we could implement an approach that works for nonconforming fe. 
But, as I explore the library, I see there is the implementation of RT fe (but not BDM fe).
Anyway, wish me luck and again many thanks indeed.
All the best,
zaq

**Comment by ZhichaoPengMath** [comment]
Dear @issabass,

Thanks for the discussion! I have a few more comments. 

(1) MFEM supports non-conforming AMR. The issue with my code is due to my implementation. 

(2) The troublemaker in my code is as follows. When I tried to implement < v, [n \cdot \tau ] >  on the skeleton, the current element ``thinks" it only has one neighbor sharing the same edge. But, if you end up doing AMR without hanging nodes similar to page 19 of this paper https://arxiv.org/pdf/1806.11000.pdf, my current implementation will be fine.

(3) I think RT is well-supported by MFEM. If the ``bilinear form" you need is already supported by MFEM, I believe that you will not face my issues. 

Good luck and best regards,
Zhichao

**Comment by issabass** [comment]
Dear @ZhichaoPengMath,
Thank you very much for the code, for the paper, for the comments and explanation.
All the best,
zaq
