### ISSUE TITLE
Read mesh from gmsh with ReadGmshMesh();

### ISSUE THREAD

**Issue by ztdepztdep** [mfem/mfem#946]
Dear sir: 
   I output a 3D Tet mesh from gmsh , but how to read in to the mfem with the following api, what is the input for ReadGmshMesh(???).
   
    Mesh *mesh = new mfem::Mesh();
    mesh->ReadGmshMesh(???);

**Comment by cpolindara** [comment]
Hi, i was also having troubles figuring that out. Here's how you do it:

    ifstream my_stream;
    my_stream.open("cube01.msh");
    Mesh *another_mesh = new Mesh(my_stream,1,1);
    my_stream.close();

Cheers,
