### ISSUE TITLE
Error: TETRAHEDRON element is not marked for refinement.

### ISSUE THREAD

**Issue by ztdepztdep** [mfem/mfem#947]
Dear sir:
      I load a 3D mesh from gmsh with all cells are tetrahedron.  I want to do a uniform refinement. but i got the following errors. 

Verification failed: (tet->GetRefinementFlag() != 0) is false:
 --> TETRAHEDRON element is not marked for refinement.
 ... in function: void mfem::Mesh::Bisection(int, const mfem::DSTable&, int*, int*, int*)
 ... at line 6587 of file: mesh/mesh.cpp

**Comment by v-dobrev** [comment]
Can you post the code that you use to load the mesh and to refine it?

**Comment by ztdepztdep** [comment]
thanks, i have sucessfully resolved it. 
`  ifstream file;
  file.open ("./input/cubic0.msh", std::ifstream::in);
  Mesh *mesh = new mfem::Mesh();
  mesh->Load	(file,1,1, true );`
