### ISSUE TITLE
Using mfem for element operations

### ISSUE THREAD

**Issue by gzagaris** [mfem/mfem#95]
Hello,

I am trying to leverage MFEM's basis functions in the context of a different code which has it's own mesh data-structures to do per-element operations. Specifically, I am interested in (a) computing the local coordinates of a given query point, q, with respect to a mesh element, and (b) computing the interpolation weights of the point with respect to the given element (that are computed using the local coordinates).

For example, consider the code snippet below:

```
double  q[2] = { 0.5, 0.5 };               // query point
double x[4] = { 0.0, 1.0, 1.0, 0.0 };  // x-coordinates of a quadrilateral (counter-clockwise)
double y[4] = { 0.0, 0.0, 1.0, 1.0 };  // y-coordinates of a quadrilateral (counter-clockwise)
int cell[4] = { 0, 1, 2, 3 };                 // cell connectivity

// construct MFEM Quad instance
mfem::Quadrilateral quad( cell, 0 ); 
```

That works as expected, but it is not clear how to proceed. 

Looking at the code further, it seems that at a high-level, I need to somehow instantiate a `FiniteElement` object that is associated with a `FiniteElementSpace` instance and then use the `mfem::IsoparametricTransformation`, which seems to do what I want. 

Is there a good example of how to do this, e.g., for Lagrange basis functions? I haven't been able to find anything in the examples that uses MFEM at that lower-level.

Please excuse my ignorance for such a basic question. This is my first attempt to using fem but, after spending quite some time, I am not able to figure out how these classes are meant to work together.

Any hints, comments or suggestions would be greatly appreciated.

I sincerely thank you for your time and help.

Best,
George

**Comment by v-dobrev** [comment]
Hi George,

The easiest way to setup an `IsoparametricTransformation` for linear mesh elements is to use the predefined global FE objects returned by [`Mesh::GetTransformationFEforElementType()`](https://github.com/mfem/mfem/blob/master/mesh/mesh.cpp#L221) and then set the coordinates of the vertices in the `DenseMatrix` returned by the method `GetPointMat()` of class `IsoparametricTransformation`. For example:
```c++
IsoparametricTransformation T;
T.SetFE(&QuadrilateralFE);
DenseMatrix &pm = T.GetPointMat();
pm.SetSize(2, 4); // space_dimension x number_of_vertices
pm(0,0) = 0.0; // x-coordinate, vertex 0
pm(1,0) = 0.0; // y-coordinate, vertex 0
// And so on ...
```
Then the object `T` can be used like this:
```c++
IntegrationPoint pt_reference;
Vector pt_physical;
pt_reference.x = 0.1;
pt_reference.y = 0.2;
// Alternatively, use:
// pt_reference.Set2(0.1, 0.2);
T.Transform(pt_reference, pt_physical);
// Then:
// pt_physical(0) is the physical x-coord
// pt_physical(1) is the physical y-coord
```

Hope this helps,
Veselin

**Comment by gzagaris** [comment]
Thanks, Veselin. That is exactly what I need.  Both `Transform()` and `TransformBack()` work as I would expect.

Would it be too hard to do the same thing for high-order elements as well? 

Thanks again for all your help.

Best,
George

**Comment by v-dobrev** [comment]
Hi George,

The high-order elements are not that much harder - you just need to create the corresponding FE object instead of using the predefined global ones. For example,
```c++
int order = 2;
H1_QuadrilateralElement quad_fe(order);
IsoparametricTransformation T;
T.SetFE(&quad_fe);
DenseMatrix &pm = T.GetPointMat();
pm.SetSize(2, quad_fe.GetDof()); // space_dimension x number_of_dofs
// And so on ...
```
The number of dofs (degrees of freedom) in this case will be 9 and their local ordering is like this
```ascii
3--6--2
|  |  |
7--8--5
|  |  |
0--4--1
```
For other types of elements use the corresponding `H1_XxxElement` from [fem/fe.hpp](https://github.com/mfem/mfem/blob/master/fem/fe.hpp) and the local dof numbering algorithm can be found in the constructor.

Note that for high-order elements, `TransformBack()` is not 100% reliable.

Best,
Veselin

**Comment by gzagaris** [comment]
Perfect! Thanks again Vaselin

**Comment by tzanio** [comment]
@gzagaris, can we close this issue?

**Comment by gzagaris** [comment]
@tzanio, yes this issue can be closed. Thanks again for all your help.
