### ISSUE TITLE
Error in SDIRK23 tableauxs

### ISSUE THREAD

**Issue by ben-s-southworth** [mfem/mfem#950]
In line (406) of ODE.cpp, the SDIRK23 Butcher tableaux is given by
```
// with a = gamma:
//   a   |   a
//  1-a  |  1-2a  a
// ------+-----------
//       |  1/2  1/2
```
This is not correct for an L-stable scheme (which can only be 2nd-order accurate with two stages, but still seems to be an option/parameter). For L-stable it should look like
```
// with a = gamma:
//   a   |   a
//  1    |  1-a  a
// ------+-----------
//       |  1-a  a
```
See 4.1.2., eq (221) here:
https://ntrs.nasa.gov/archive/nasa/casi.ntrs.nasa.gov/20160005923.pdf

**Comment by v-dobrev** [comment]
This method is taken from the books: http://dx.doi.org/10.1007/978-3-540-78862-1 (volume 1) and http://dx.doi.org/10.1007/978-3-642-05221-7 (volume 2). Specifically, see Table 7.2 in the first volume and Table 6.4 in the second volume regarding L-stability.

**Comment by ben-s-southworth** [comment]
Table 7.2 gives the 3rd-order A-stable version, which is correct in MFEM. That Butcher tableaux is specifically from a family of 3rd-order DIRK schemes. Table 6.4 in volume 2 gives the one-parameter family defining two-stage, second-order L-stable schemes, with $gamma = \frac{2\pm\sqrt{2}}{2}$, but that is *not* the same $\gamma$ as in Table 7.2. The $\mathbf{b}$ vector in the Butcher tablueax must depend on $\gamma$ for a stiffly accurate two-stage L-stable scheme.

**Comment by v-dobrev** [comment]
Maybe I do not understand something but I think in both cases `\gamma` stands for the entries on the diagonal of the table which are all the same for SDIRK method.

Also, as far as I understand, there are multiple solutions of the order equations plus the L-stability condition - one is given by the method implemented in mfem, another is the method you mention above.

**Comment by ben-s-southworth** [comment]
Oh, you're right! Actually identical stability function oddly enough. Maybe an equivalent method, because I had read that the 2nd-order stiffly accurate L-stable solution is unique to the \pm, which is what had me confused here.

**Comment by v-dobrev** [comment]
Yes, "stiffly accurate" means that the last two rows of the tableaux are equal -- see the paragraph after proposition 3.8 in chapter IV, volume 2 of the above-mentioned books. This makes the method unique up to the `\pm`.

We can definitely add this "stiffly accurate" version to mfem -- it should be straightforward.
