### ISSUE TITLE
Mesh with holes in native mfem?

### ISSUE THREAD

**Issue by Meddean** [mfem/mfem#954]
Hi there!
As a new user of MFEM, I'd like to know how to create/read meshes (Tri/Tetra) with holes in v1.x format?
I see that the Library does support data mesh generated by different mesh generators but not those produced by, say, TRIANGLE (TETGEN) software, or have I to read/explore more?
Another question, if I need a 2nd order mesh, I should read linear one and MFEM will produce it, right?
I've also to ask for a little explanation as to class COEFFICIENTS/GRIDFUCTION for I do not see well how to define the tensor Permeability_inv, for example, in the case of test ex4/ex5.
Thank you much indeed!

**Comment by v-dobrev** [comment]
Hi @Meddean,

Yes, currently MFEM cannot read TRIANGLE/TETGEN meshes directly. I'm not sure if you can open such meshes with Gmsh or Netgen and export them in Gmsh/Netgen format which MFEM can read. I think it may be possible to perform the conversion in VisIt or ParaView by exporting the mesh in the unstructured ascii VTK format which MFEM can read as well. Alternatively, you can use Gmsh or Netgen to create your mesh.

If you read a linear mesh, MFEM can convert it to quadratic (see the method `Mesh::SetCurvature` or the `'c'` menu option in the miniapp `mesh-explorer` in `miniapps/meshing/`). Note that with this conversion the faces/edges in the mesh will remain straight. If you want to have a quadratic mesh that conforms better to a curved boundary, you need to the generate the curved mesh in the mesh generator - for this case you will want to save your mesh using either the unstructured ascii VTK format or the Cubit (NetCDF) format -- the native Gmsh and Netgen readers in MFEM do not support quadratic (or higher-order) meshes yet.

**Comment by v-dobrev** [comment]
Regarding the tensor permeability: you can define it as `MatrixConstantCoefficient`, `MatrixFunctionCoefficient`, or any other class derived from class `MatrixCoefficient` (including your own custom derived class). Then, when you create the `VectorFEMassIntegrator` in example 5, you can give that `MatrixCoefficient` to the constructor.

**Comment by Meddean** [comment]
Many thanks, @v-dobrev for the detailed response.
Just to see if i get right, the MatrixCoefficient provided will be taken by the code as the actual permeability or rather its inverse? I mean, should i supply matrix or its inverse? 
For the mesh, yes i can convert it to VTK format. I will be checking the miniapps you suggested. Thank you.

**Comment by Meddean** [comment]
And one more question,  does the x (recovered soln ) in ex4 represent only the potential F or  flux too as in ex5? If so, i do not see exactly how to extract it from there. Any hint? Put simply, I wanna apply hybridization as in ex4 to the example ex5. I trivially copied and pasted the 
//9.  Assemble the bilinear form and the corresponding linear system,  ...
I am not sure about the readjustment.

**Comment by v-dobrev** [comment]
> Just to see if i get right, the MatrixCoefficient provided will be taken by the code as the actual permeability or rather its inverse? I mean, should i supply matrix or its inverse?

In example 5, the matrix coefficient should be the inverse permeability.

**Comment by v-dobrev** [comment]
> And one more question, does the x (recovered soln ) in ex4 represent only the potential F or flux too as in ex5? If so, i do not see exactly how to extract it from there. Any hint? Put simply, I wanna apply hybridization as in ex4 to the example ex5. I trivially copied and pasted the
> //9. Assemble the bilinear form and the corresponding linear system, ...
> I am not sure about the readjustment.

Examples 4 and 5 solve different PDEs. In example 4, there is only one unknown (vector) field, denoted by F in the description in the beginning of the file.

Unfortunately, the hybridization used in example 4 cannot be applied directly in example 5. In example 4, there is a single `BilinearForm` to which we apply hybridization, whereas the formulation in example 5 uses 2x2 block form and has one `BilinearForm` and one `MixedBilinearForm`. It is possible to treat this case using class `Hybridization` however it will require some additions in the class to handle properly the terms coming from the `MixedBilinearForm`.

**Comment by Meddean** [comment]
Many thanks, @v-dobrev !
