### ISSUE TITLE
Quick question on Hybridization/statcondensation.

### ISSUE THREAD

**Issue by issabass** [mfem/mfem#955]
Hi, MFEM team!
I am learning fem with your lightweight yet rich lib.
I am interested in the mixed part for general flow problems (Darcy/stokes and alike).
I am studying the hybridization/sc with ex4/ex5. I'd like to know what coefficient shall I call when I put both alpha and beta as matrices? 
Also, was the hybridization technique used in ex4 just to get rid of the indefiniteness in the matrix block? Waht if I wanna compute the flux of that vector-valued function F? I am not familiar with the OO philosophy but excited to learn more with help of MFEM and its team.
Any guidance would be very appreciated. Thank you.

**Comment by tzanio** [comment]
Hi @Meddean,

Sorry for the slow reply. Here are some answers.

> I am studying the hybridization/sc with ex4/ex5. I'd like to know what coefficient shall I call when I put both alpha and beta as matrices?

`MatrixCoefficient`

> Also, was the hybridization technique used in ex4 just to get rid of the indefiniteness in the matrix block?

It was used to reduce the problem size by eliminating the interior (to each element) degrees of freedom, similar to static condensation

> What if I wanna compute the flux of that vector-valued function F? I am not familiar with the OO philosophy but excited to learn more with help of MFEM and its team.

The degrees of freedom in the Raviart Thomas subspace of H(div) are essentially fluxes across faces, so depending on what you need you probably need to just add some of them.

Hope this helps,
Tzanio

**Comment by Meddean** [comment]
Thank you so very much, @tzanio ! 
I was offline for almost a month. Yes, it is indeed helpful.

**Comment by NikolayYavich** [comment]
Hi Tzanio,

Could you please give a tip on how to apply hybridization/condensation in ex5 (Darcy problem)?

Thanks a lot.

**Comment by tzanio** [comment]
@NikolayYavich -- take a look at Section 3.2 in https://arxiv.org/abs/1801.08914
