### ISSUE TITLE
Master is broken on NERSC

### ISSUE THREAD

**Issue by tangqi** [mfem/mfem#956]
The master seems broken on nersc. You should be able to reproduce by
$ make config MFEM_USE_MPI=YES MFEM_DEBUG=YES MPICXX=CC
$ make -j
$ make ex1p
CC  -g -Wall -std=c++11 -I.. -I../../hypre/src/hypre/include ex1p.cpp -o ex1p -L.. -lmfem -L../../hypre/src/hypre/lib -lHYPRE -L../../metis-4.0 -lmetis -lrt

$ srun -n 1 ex1p -m ../data/square-disc.mesh
Assertion failed: (data[i+i*m] != 0.0) is false:
 --> division by zero
 ... in function: void mfem::LUFactors::Factor(int)
 ... in file: linalg/densemat.cpp:3974

bc92fc1a9f4f854729e2daade5653bd1c333ba1d was working fine. But 798ded1f551a5995333fbff37bbba27e2fc31ecf seems cause the issue.

Qi

**Comment by rw-anderson** [comment]
I just cloned from master and the example runs cleanly for me on a vanilla ubuntu box.

One difference in my environment is that I'm not sure what CC is a wrapper for; I used mpic++ from openmp.

**Comment by tangqi** [comment]
Thanks a lot. Yes, it runs fine on my other machines using openmpi. As I said, it's been working fine on nersc until the recent update. CC here is wrapped with the Cray compilers. I believe mpicxx is more problematic on nersc.

**Comment by v-dobrev** [comment]
Hi @tangqi, can you try this commit: dd899e1fb219 -- I do not have access to any nersc machines, so I cannot try it myself. Are you running on cori or some other machine?

**Comment by tangqi** [comment]
Yes, I tried. dd899e1 has no impacts on this. Something in 798ded1 causes the problem. I am running on cori.

I have access to other clusters but it would still be nice if it works on nersc. Let me know if you want me to run some more tests.

**Comment by v-dobrev** [comment]
When you say https://github.com/mfem/mfem/commit/dd899e1fb2193aea6504d0fd782ec25edc41b228 has no impact on this, do you mean it works fine?

The reason, I wanted to check is that https://github.com/mfem/mfem/commit/dd899e1fb2193aea6504d0fd782ec25edc41b228 and https://github.com/mfem/mfem/commit/798ded1f551a5995333fbff37bbba27e2fc31ecf are essentially identical for the file in which you see the error -- `linalg/densemat.cpp`.

**Comment by tangqi** [comment]
Yes, it works fine. 

I open ex1p with totalview. The error comes from initialization
![image](https://user-images.githubusercontent.com/1406660/59323632-bae50680-8c98-11e9-8eec-bfce20a230cd.png)
I am not sure what is going on. Maybe I should avoid to use cray...

**Comment by v-dobrev** [comment]
Hi @tangqi,

I'm trying to understand what is going wrong. Can you try adding the line
```c++
   T.Print(mfem::out, Dof);
```
in the method `H1_TriangleElement::H1_TriangleElement` just before the call (line 7807 in `fem/fe.cpp`)
```c++
   Ti.Factor(T);
```
and post the output? The call `Ti.Factor(T)` performs an LU factorization of the `DenseMatrix` `T`, so I want to make sure `T` is not singular for some reason.

On my laptop, I get the following output from running `./ex1p` with the addition of `T.Print(...)`:
```ascii
[row +0]
+1.000000e+00 -1.000000e+00 -1.000000e+00
[row +1]
-1.000000e+00 +1.000000e+00 -1.000000e+00
[row +2]
-1.000000e+00 -1.000000e+00 +1.000000e+00
...
```

**Comment by tangqi** [comment]
Hi @v-dobrev,  `T` is set and I got the same result as you on nersc. 

I ran more tests. I simply output `data` in `LUFactors::Factor` after each pivoting in LU factorization (before `MFEM_ASSERT(data[i+i*m] != 0.0, "division by zero");`). The result on nersc is
```
 1 -1 -1 -1 1 -1 -1 -1 1
 1 -1 -1 -1 -2 0 -1 -2 0
 1 -1 -1 -1 -2 0 -1 1 0
```
But the correct result should be 
```
 1 -1 -1 -1 1 -1 -1 -1 1
 1 -1 -1 -1 -2 0 -1 0 -2
 1 -1 -1 -1 -2 0 -1 -0 -2
```
It looks like `Swap` does not actually swap `0 -2`. So I simply add
```c++
mfem::out << "after swap " << data[i+j*m]<<" "<<data[piv+j*m]<<endl;
```
after `Swap<double>(data[i+j*m], data[piv+j*m]);`. Then ex1p runs and generate the correct result. The output is
```
 1 -1 -1 -1 1 -1 -1 -1 1
after swap -1 -1
after swap -2 0
after swap 0 -2
 1 -1 -1 -1 -2 0 -1 0 -2
 1 -1 -1 -1 -2 0 -1 -0 -2
```
Now I do not know what is going on... Everything I described happens in `__libc_start_main`.

**Comment by v-dobrev** [comment]
Let me see if I understand you correctly: you just added the print statement:
```c++
mfem::out << "after swap " << data[i+j*m]<<" "<<data[piv+j*m]<<endl;
```
after the `Swap<double>(...)` call and then it works correctly?

If that is the case, it surely looks like a compiler bug. As a possible workaround, what happens if you replace `Swap<double>(data[i+j*m], data[piv+j*m])` with `std::swap(data[i+j*m], data[piv+j*m])`? If this works, we can push it to mfem, as a workaround for the bug.

**Comment by tangqi** [comment]
Yes, what you described is exactly what I found there. 

I think it is a compiler bug, because `std::swap` is also not working. The only thing working is the old  way,
```c++
   double tmp=data[piv+j*m];
   data[piv+j*m]=data[i+j*m]; data[i+j*m]=tmp;
```
