### ISSUE TITLE
Interpolating a ParGridFunction on an unstructured mesh at an arbitrary point

### ISSUE THREAD

**Issue by pratyuksh** [mfem/mfem#957]
The tools that are referenced in this old thread available? Could you please share the code? Thanks!

_______________________________________
Hi Mikhail,

This is not a typical operation with finite elements. Can you provide more details in what context do you need it?

In the most general case, you will have to find a set of nearby elements (e.g. by looking if the point is in their bounding boxes) and invert the mapping for each of them to see if the point is an image of a point inside the reference element (e.g. using Newton). This general algorithm is expensive and we don't have it in the release. We have all the tools for it though, and we'll be happy to help you implement it if that's what you need.

Cheers,
Tzanio

On Oct 15, 2015, at 1:15 PM, martemyev notifications@github.com wrote:

> Hi Tzanio,
> 
> Thank you for your reply! So, the question is - how do I find the mesh element containing my point?
> 
> Thank you,
> Mikhail
> 
> �
> Reply to this email directly or view it on GitHub.

_Originally posted by @tzanio in https://github.com/mfem/mfem/issues/23#issuecomment-148512864_

**Comment by vikramsg** [comment]
I have been doing this with the new class InverseElementTransformation. You can simply loop through the elements and check the value returned by InverseElementTransformation.Transform. If it is inside, then you know both the element and the interior point in reference plane which you can use to Eval to get your value.

**Comment by v-dobrev** [comment]
Just to add to Vikram's answer: you can also try the method `Mesh::FindPoints` which uses the class `InverseElementTransformation`.

**Comment by pratyuksh** [comment]
@vikramsg @v-dobrev Thank you for the answers. I checked the documentation on this, it says that the FindPoints is not 100% reliable, what are the problems expected in the working here?

**Comment by v-dobrev** [comment]
Hi @pratyuksh, for linear meshes with convex elements, this method should be 100% reliable. The problem is when the mesh has very distorted high-order elements. You can always check the number returned by the method to see if all points were found.

**Comment by pratyuksh** [comment]
@v-dobrev Thanks, you can close this thread now.
