### ISSUE TITLE
Public 'rebalance' interface for ParNCMesh

### ISSUE THREAD

**Issue by cwsmith** [mfem/mfem#958]
Could a `ParNCMesh::Rebalance(int* partition_vector)` public member function be provided that takes an array of integers with size `ParNCMesh::NEelements` (locally owned elements) where each entry contains the destination MPI rank for the associated element?  When the function returns the mesh is expected to be redistributed according to the provided element-to-rank assignments.  This function would simplify my work on MS29 a bit and make for cleaner code overall.

@v-dobrev

**Comment by jakubcerveny** [comment]
This should be pretty straightforward. I'd put the overloaded `Rebalance` in `ParMesh` (user's shouldn't interact with `ParNCMesh`) and I'd make it call `ParNCMesh::RedistributeElements`. I can do this next week (Wednesday) unless someone does it quicker.

**Comment by jakubcerveny** [comment]
I started implementing a custom `ParMesh::Rebalance` when I realized one thing: in the current implementation, `ParNCMesh::RedistributeElements` needs to know the final number of local elements so it knows when to stop receiving rebalance messages. With SFC-based partitioning the target number of elements per rank is easy to calculate, but with totally custom rank assignments one would have to have this information up front or try to communicate it, which doesn't look trivial. 

So this is unfortunately more difficult than I thought. What do we want to do? @tzanio @v-dobrev

**Comment by cwsmith** [comment]
The termination detection algorithm described in section 2.2 (Algorithm 1, pg 2) here:
https://scorec.rpi.edu/REPORTS/2015-9.pdf
could be used to avoid the need for the incoming element count.

**Comment by jakubcerveny** [comment]
That looks good, the question is if we can afford a non-blocking barrier (MPI_Ibarrier). We have been trying to avoid barriers, which are slow without HW support. Is that still true @tzanio, @v-dobrev? Perhaps the barrier could be used only if a custom partition is required.

**Comment by Dan2997925** [comment]
What is the motivation for totally custom rank assignments? Maybe some variation of workload per element? For my application every element has same workload, and I'd use your SFC partitioning, and I'd use this capability right away.

**Comment by v-dobrev** [comment]
It looks like the MPI-2 functions: [MPI_Dist_graph_create](https://www.open-mpi.org/doc/v2.1/man3/MPI_Dist_graph_create.3.php) and [MPI_Dist_graph_neighbors_count](https://www.open-mpi.org/doc/v2.1/man3/MPI_Dist_graph_neighbors_count.3.php), and [MPI_Dist_graph_neighbors](https://www.open-mpi.org/doc/v2.1/man3/MPI_Dist_graph_neighbors.3.php) can be useful here.

**Comment by jakubcerveny** [comment]
Those are interesting but it seems like a much bigger hammer than we need. The non-blocking barrier is perfect for determining if all ranks have finished. From what I've heard, the standard barrier is highly optimized on BG/Q so it's possible this will be true for other architectures and the non-blocking version as well. We're probably fine using MPI_Ibarrier, especially if it's just in the case of custom partitioning...

**Comment by cwsmith** [comment]
Have we reached a decision on using the Ibarrier vs the dist graph?  I'd like to move forward with the  dynamic load balancing work.

**Comment by v-dobrev** [comment]
I'm OK with either approach. @jakubcerveny, let me know if there's anything I can help with.

**Comment by jakubcerveny** [comment]
I believe that we concluded that Ibarrier is OK for the special case of custom partitioning. I can look into this (will need to speak with @tzanio about priorities).

**Comment by cwsmith** [comment]
Sounds good.  Thank you. Please let me know if I can help.

**Comment by jakubcerveny** [comment]
The core of the problem is to allow `target_elements = -1` in `ParNCMesh::RedistributeElements`, in which case there would be a switch to an alternate implementation of Step 3 that utilizes the non-blocking consensus algorithm. (Then, `ParNCMesh::Rebalance` could take an optional user-defined partition array.) If anyone wanted to take a shot at this I am of course OK with that.

**Comment by jakubcerveny** [comment]
@cwsmith, I have implemented the custom load balancing, please check out #1021 and let me know if it works for you.

**Comment by cwsmith** [comment]
The new API and demonstration in #1021 looks good to me.  Thank you.

When I get back into this I'll work through #939 then test it out.  I'll close the ticket for now.
