### ISSUE TITLE
Defining a new domain integrator

### ISSUE THREAD

**Issue by kvoronin** [mfem/mfem#96]
Hello,

I am rather new to MFEM and don't know cpp well either, however I am trying to implement a variational setting using MFEM with terms like
\int_\Omega ( ( - grad u, u)^t, **w** ) d\Omega as a bilinear form b(u, **w**) with **w** being a vector function, so the scalar product of two vectors is integrated over the domain Omega, one component of the vectors contain the gradient operator; and a linear form l(**w**) =  \integ_\Omega f div **w** d\Omega, f is a scalar function. 
Since it is not among the standard vector integrators implemented in MFEM, I would like to ask which way is the best to implement such things, for instance, the linear form integrator. Perhaps, a step instruction or a simple example of user-defined linear integrator could help me.

As far a I understand, I should somehow define a new linear form integrator. I see it the following way:
1) I copy the class DomainLFIntegrator and the core member DomainLFIntegrator::AssembleRHSElementVect() to my code and rename them,
2) Redefine somehow the integration rule which is used so as to get some weights for the (f, div **w**) integral element-wise.
But this way seems a little complicated, so I guess there exist something easier.
 
I would appreciate any comments / details.

Thanks,
Kirill

**Comment by tzanio** [comment]
Hi @kvoronin, sorry for the delayed reply. Did you understand how to define the integrators you need?

**Comment by kvoronin** [comment]
Hi @tzanio, yes, with some help of my colleagues I did. Thanks for the reply in any case.

**Comment by tzanio** [comment]
Glad to hear you resolved it. Let us know if you have any questions in the future.
