### ISSUE TITLE
Which function returns the neighboring cells of a cell?

### ISSUE THREAD

**Issue by ztdepztdep** [mfem/mfem#961]
I need the cells neighboring of a cell, which function can resolve this.

**Comment by tzanio** [comment]
See `Mesh::ElementToElementTable()` and how it is used e.g. in `Mesh::GetElementColoring`

https://github.com/mfem/mfem/blob/dd6d3c642a083859eab28e1167d7f5a3bf97b0db/mesh/mesh.cpp#L8407
