### ISSUE TITLE
Memory allocation failed for SetupCtrl

### ISSUE THREAD

**Issue by ztdepztdep** [mfem/mfem#962]
I setup a simple parmesh with
```c++
Mesh *mesh = new mfem::Mesh(20, 20, mfem::Element::TRIANGLE , 1, 10.0, 10.0);
ParMesh *pmesh = new ParMesh(MPI_COMM_WORLD, *mesh);
```
but when i run it with 2 CPUs, it gives me the following errors:

***Memory allocation failed for SetupCtrl: ctrl->tpwgts. Requested size: 713700419292889096 bytes
   Current memory used:         392 bytes
   Maximum memory used:         392 bytes
***Memory allocation failed for SetupCtrl: ctrl->tpwgts. Requested size: 380152571890761736 bytes

**Comment by tzanio** [comment]
This seems to be an error from METIS, but I can't reproduce it. Can you provide a complete example? Which version of METIS are you using?

**Comment by ztdepztdep** [comment]
The full code is here. I use METIS 5.0
`   
#include "mfem.hpp"
#include "mfem/mesh/pmesh.hpp"
#include <fstream>
#include <iostream>
using namespace std;
using namespace mfem;
int main(int argc, char *argv[])
{

 MPI_Init(&argc, &argv);
    int order = 1;
   int num_procs, myid;
     OptionsParser args(argc, argv);
 MPI_Comm_size(MPI_COMM_WORLD, &num_procs);
 MPI_Comm_rank(MPI_COMM_WORLD, &myid);

   Mesh *mesh = new mfem::Mesh(20, 20, mfem::Element::TRIANGLE , 1, 10.0, 10.0);
    ParMesh *pmesh = new ParMesh(MPI_COMM_WORLD, *mesh);
    
    delete mesh;
    MPI_Finalize();
    return 0;
}
`

**Comment by ztdepztdep** [comment]
Thanks , i solved this problem by  using metis4.0
