### ISSUE TITLE
Update repo topics

### ISSUE THREAD

**Issue by hauten** [mfem/mfem#967]
A new page on the LLNL software portal (https://software.llnl.gov/radiuss/) will soon dynamically pull in RADIUSS repos. To achieve this, we need RADIUSS-related repos outside the LLNL org to be tagged with relevant topics. See https://github.com/LLNL/llnl.github.io/issues/17, https://github.com/LLNL/llnl.github.io/issues/151, & https://github.com/LLNL/llnl.github.io/blob/new-home-page/radiuss/README.md for additional context.

MFEM already has `math-physics`. Please also add `radiuss`.

**Comment by tzanio** [comment]
Done. Thanks @hauten!
