### ISSUE TITLE
How to get the ghost cells and exchange data values in  a ParMesh

### ISSUE THREAD

**Issue by ztdepztdep** [mfem/mfem#968]
Dear friends:
     I generated a ParMesh with 5 CPUs for FVM computations. Which function feedback ghost cells infos and how to exchange data values of the ghost cells between different CPUs. 
   Regards

**Comment by vikramsg** [comment]
I am assuming you are using a ParGridFunction to store solution values. In this case ```ExchangeFaceNbrData``` function can be used to exchange data values.

**Comment by ztdepztdep** [comment]
Does ParGridFunction  support storing values in the cell central.

**Comment by vikramsg** [comment]
Although I haven't explored it in this context, I think a P0 DG space should essentially function like a finite volume space. So a grid function defined on a P0 DG space should act like FV.

**Comment by ztdepztdep** [comment]
Thanks dear vikramsg for your feedback.  Another questions, how to obtain the global index of each cell on every CPU, i can only obtain the local index. need i to compute it manually?

**Comment by tzanio** [comment]
@ztdepztdep, can you explain why you need the global index of the elements? You can obtain that from the global matrix, or with `MPI_Scan` (the elements are globally numbered consecutively between MPI ranks) but typically you don't need to manipulate global indices directly -- MFEM does that for you.

**Comment by ztdepztdep** [comment]
Thank you. I am using the MFEM as a mesh processor in my FVM code. so i need the global index of each cell , the global index of  ghost cell is also needed.






At 2019-08-22 04:18:11, "Tzanio Kolev" <notifications@github.com> wrote:


@ztdepztdep, can you explain why you need the global index of the elements? You can obtain that from the global matrix, or with MPI_Scan (the elements are globally numbered consecutively between MPI ranks) but typically you don't need to manipulate global indices directly -- MFEM does that for you.

**Comment by tzanio** [comment]
Maybe @jakubcerveny can help with that, but if you really can't recast your algorithm in DG-like updates, then it may not be straightforward.

**Comment by jakubcerveny** [comment]
Is #1058 something that would help? I'll see if we can merge that PR
