### ISSUE TITLE
L2 Norm error

### ISSUE THREAD

**Issue by ShiyangZhang** [mfem/mfem#97]
Dear all,
I run the example ex5 with
` make ex5
./ex5 -m ../data/beam-tet.mesh`

Ａt the end it says that:

> MINRES converged in 234 iterations with a residual norm of 0.00991258.
> MINRES solver took 0.965648s. 
> || u_h - u_ex || / || u_ex || = 0.00441703
> || p_h - p_ex || / || p_ex || = -0.0019764

Here  -0.0019764 is a negative number,  How this happened?

Best,
Shiyang

**Comment by tzanio** [comment]
Hi @ShiyangZhang, this is due to the fact that some quadrature rules on tetrahedral elements have negative weights. It is rare, but it is possible to get a negative results when you approximate a norm with such a quadrature rule.

**Comment by ShiyangZhang** [comment]
I  get it and thank you for your reply very much.

Best,
Shiyang



Sent from my Mi phone
On Tzanio Kolev <notifications@github.com>, Nov 19, 2016 9:08 AM wrote:

Hi @ShiyangZhang<https://github.com/ShiyangZhang>, this is due to the fact that some quadrature rules on tetrahedral elements have negative weights. It is rare, but it is possible to get a negative results when you approximate a norm with such a quadrature rule.
