### ISSUE TITLE
inheriting linear algebra classes

### ISSUE THREAD

**Issue by tomathew** [mfem/mfem#973]
Hello,
I would like to have a feedback on something which I have asked previously, but this time in a more clear way, may be someone can suggest something this time.
https://github.com/mfem/mfem/issues/901#issue-441390134
In the above query, may be I was asking from domain decomposition happening at a geometric level, but understanding in mfem and Hypre, this is happening at the algebraic level (correct me if I 'm wrong), can anyone refer me to any project or branch or tags, where the aforementioned query can be given a starting point.
I saw the source codes, and it is like a jungle of information, may be somebody can suggest a good example or starting point more appropriate. May be an example, where a specific non-trivial or out-of-box Krylov method is applied in MFEM with Hypre objects. Not something implemented from PETSc to MFEM.
Thanks in advance

**Comment by barker29** [comment]
If I understand correctly, you are asking if there is an example of (geometric) domain decomposition preconditioning in MFEM. If so, I'm afraid the short answer is no.

MFEM (and Hypre) is strongly connected to (algebraic) multigrid solvers, and its examples reflect that. It should be possible to implement something, but I don't think we currently have examples of this.

**Comment by tomathew** [comment]
Thank you for your reply. I was in fact asking about algebraic methods. As this query https://github.com/mfem/mfem/issues/901#issue-441390134 was about using optmized conditions, I was wondering if a similar strategy was already attempted before. Optimized transmission conditions correspond to explicitly imposing some boundary conditions for ex. absorbing boundry conditions in Maxwell's or a Robin condition in general at the interface. This is straight-forward in Geometric DDMs, but in algebraic I think I need to identify elements in local sub-domain matrices shared with a neighbor, or ghost nodes on other processors, etc. I am not sure, to explicit impose these conditions. 
I was wondering anything close enough or similar exists, either in Hypre or some MFEM projects. If No, not a problem. This was just a query.

**Comment by tomathew** [comment]
I found a reliable resource for the time-being at NGSolve. I can try that for now.
Thanks
