### ISSUE TITLE
VTK High Order Mesh Reader Phase-II

### ISSUE THREAD

**Issue by jonesholger** [mfem/mfem#976]
A few ideas for follow on support for VTK High Order

1: XML parsing for vtu ascii
2: binary & compressed file processing
3: Conversion of Gauss-Lobatto High Order MFEM meshes to Closed-Uniform VTK meshes aka vtk writer
4: Confirm Visit Reader (deferrel to MFEM when vtk meshes contain lagrange cells)
5: Implicit Boundary Elements, similar to gmsh; i.e. lower dimension mixed cells are catalogued as boundary elements within the reader.
6: Update DoNodeReorder to support orientation error fixup; i.e. tets beyond order 4; add hex and wedge. Begs the question of whether we should support non-positive Jacobian Det elements at all. 
7: Look into L2 to H1 projections (naive for sure ;), but could be useful for general DoNodeReorder like fixups.
    
Adjunct:
8: Gmsh high order support, using some of the same machinery.

Feel free to close this after review. Just wanted a place to submit some ideas.

**Comment by tzanio** [comment]
See #976 for follow-on VTK high-order mesh reader support.
