### ISSUE TITLE
uniquely counting shared entities in an pncmesh

### ISSUE THREAD

**Issue by cwsmith** [mfem/mfem#977]
I'd like to quantify the communication costs associated with a partition by counting how many mesh entities are duplicated across part (the set of mesh elements assigned to a process) boundaries.  For example, suppose there are two triangles with one common edge (and two common vertices).  If one triangle is assigned to process 0 and the other to process 1, I would want to the 'cut' counting function to return that one edge and two vertices are cut (shared).  

One way to uniquely count these entities is to have information on each process indicating which ranks they exist on so a protocol (e.g., minimum rank) can be defined to determine which process will count which shared entities.

In pncmesh.cpp it appears the necessary information is accessible in the `ParNCMesh::CalculatePMatrixGroups(...)` function:
https://github.com/mfem/mfem/blob/3320cb796c0d862bbf025d0bdc4f6cbcb6fde40d/mesh/pncmesh.cpp#L568-L588

Does `ParNCMesh::CalculatePMatrixGroups(...)`  provide the needed information?  If not, is there another place to look?

**Comment by v-dobrev** [comment]
This information is available at the level of class `ParMesh`. The relevant methods are the following:
https://github.com/mfem/mfem/blob/3320cb796c0d862bbf025d0bdc4f6cbcb6fde40d/mesh/pmesh.hpp#L242-L255

The shared mesh entities are broken into non-overlapping "groups". A group represents a set of processors that share the same entities. Additional information about the groups is contained in the `GroupTopology` associated with the `ParMesh` -- this is the public data member `gtopo`:
https://github.com/mfem/mfem/blob/3320cb796c0d862bbf025d0bdc4f6cbcb6fde40d/mesh/pmesh.hpp#L227

One thing to keep in mind is that when the `ParMesh` holds a non-conforming mesh (i.e. its `pncmesh` pointer is not `NULL`) then the groups describe the so-called "cut" mesh. In the cut mesh, dependent mesh entities are considered independent of their master entity. If the idea is to get some numerical value representing the communication cost, it may be more appropriate to look at the so-called parallel prolongation matrix, e.g. counting the data transfers needed for a mat-vec with it. This prolongation matrix is associated with a `ParFiniteElementSpace` and can be accessed with the method `Dof_TrueDof_Matrix()`:
https://github.com/mfem/mfem/blob/3320cb796c0d862bbf025d0bdc4f6cbcb6fde40d/fem/pfespace.hpp#L271-L273

**Comment by cwsmith** [comment]
@v-dobrev Thank you.  I just pushed an initial, seemingly functional, version of the cut counting code:
https://github.com/cwsmith/mfem/commit/e91b7ba96178b5f08591a239a558bce8f629478c

I read a bit about the prolongation matrix in the AMR paper (https://arxiv.org/pdf/1905.04033.pdf); we'll have discuss more in the next call.
