### ISSUE TITLE
Computing the Lp norm of a coefficient

### ISSUE THREAD

**Issue by e-aranda** [mfem/mfem#978]
I have a coefficient, computed in a certain way, and I would like to compute its L^p norm. I have seen the `ComputeLpNorm` function but I don't understand how it works, because of the 
`const IntegrationRule * | irs[]` parameter in its definition. How could I use the `ComputeLpNorm` function?

**Comment by NoseKnowsAll** [comment]
The local L^p norm is computed differently depending on which type of element you are computing it on. The different integration rules allow you to integrate on different types of elements. If you want to be able to compute on any type of element, try:

```
int order_to_integrate = SET_THIS;
double p = SET_THIS;

const IntegrationRule *irs[Geometry::NumGeom];
for (int i=0; i < Geometry::NumGeom; ++i)
{
    irs[i] = &(IntRules.Get(i, order_to_integrate));
}

double norm = ComputeLpNorm(p, coeff, mesh, irs);
```

If you know what types of elements you have, then you only needs to give the function the `irs` corresponding to those types of elements.

If your mesh is a `ParMesh`, use `ComputeGlobalLpNorm()`, but it's syntactically identical.

**Comment by e-aranda** [comment]
I will always use the centroids of the elements, but the mesh may be different (triangles, quadrilaterals, tetrahedra or hexahedra). 

Instead of a coefficient, I could use a GridFunction defined in an L2 space. Will it be easier to compute the Lp norm for the GridFunction? Is there any function like `ComputeLpNorm` for a `GridFunction`?

Thanks.

**Comment by NoseKnowsAll** [comment]
I'm not sure what you mean when you say you use the centroid of elements - do you mean that you are only considering order 2 polynomials on the different elements? If so, then set `order_to_integrate = 2` in my above code snippet.

I do not know of a direct way to compute the Lp norm for a `GridFunction`, only to compute the Lp error compared to some "exact solution." The signature is: `GridFunction::ComputeLpError(const double p, Coefficient &exsol, Coefficient *weight, const IntegrationRule *irs[])`. 

You can see how you could call this exactly the same as I previously described, except now you need a `Coefficient` describing the "true solution".  Note: `weight` is optional, so `NULL` here would still be valid. If you want to use this to compute the Lp norm of a function, use a `ConstantCoefficient{0.0}` in place of `exsol`. Obviously, this requires more code than simply directly computing the Lp norm of a `Coefficient` if you had your function already defined that way.

**Comment by e-aranda** [comment]
My coefficient is computed from GridFunctions defined in a piecewise constant function space. So in order to compute de Lp norm, I only need to evaluate the coefficient in the centroid of each element. I have tried with `order of integrate = 0` and it seems to work.

**Comment by NoseKnowsAll** [comment]
Ah I see now - and yes order 0 is correct. Glad to hear it worked out.
