### ISSUE TITLE
Installation/Running with lapack and SuiteSparse

### ISSUE THREAD

**Issue by kvoronin** [mfem/mfem#98]
Hello everyone,

Could anyone give me an insight of how to build and run MFEM properly with (latest) netlib lapack and sparsesuite?
What I know/tried by now:
1) Without using (external) lapack and sparsesuite, I can build MFEM and run examples as described at the mfem.org, using the latest releases of hypre and metis.
2) I tried to make MFEM with additional options MFEM_USE_LAPACK=YES MFEM_USE_SUITESPARSE=YES:
"make parallel -j MFEM_USE_METIS_5=YES METIS_DIR=@MFEM_DIR@/../metis-5.1.0 MFEM_USE_LAPACK=YES MFEM_USE_SUITESPARSE=YES" and build ran ok.
But I am not sure when exactly should I modify config.mk and default.mk (like putting YES against the same options, because it is not done during the MFEM building process).
However, when I try to "cd examples; make all" I got the error:
"mpicxx  -O3 -I..  -I../../hypre-2.11.1/src/hypre/include  -I/home/kvoronin/Documents/suitesparse/SuiteSparse/include ex1p.cpp -o ex1p -L.. -lmfem -L../../metis-5.1.0 -lmetis -L../../hypre-2.11.1/src/hypre/lib -lHYPRE -L"/home/kvoronin/Documents/lapack/lapack-3.6.1" -llapack -lrt -L/home/kvoronin/Documents/suitesparse/SuiteSparse/KLU/lib -L/home/kvoronin/Documents/suitesparse/SuiteSparse/lib -lklu -lbtf -lumfpack -lcholmod -lcolamd -lamd -lcamd -lccolamd -lsuitesparseconfig -lrt -L../../metis-5.1.0 -lmetis -L"/home/kvoronin/Documents/lapack/lapack-3.6.1" -llapack
/usr/bin/ld: /home/kvoronin/Documents/lapack/lapack-3.6.1/liblapack.a(xerbla.o): undefined reference to symbol '_gfortran_string_len_trim@@GFORTRAN_1.0'
//usr/lib/x86_64-linux-gnu/libgfortran.so.3: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
makefile:39: recipe for target 'ex1p' failed
make: *** [ex1p] Error 1"
And I could not handle this. I assume something is wrong with lgfortran but adding it random places of the compilation options does not help.

With that, running from the home lapack directory  "make lapack_testing" seems to be fine.

I would appreciate any advice.

**Comment by martemyev** [comment]
Hi @kvoronin,

I had a problem once when I tried to build examples with MFEM_USE_LAPACK=YES, and the solution for my issue was to add '-lblas' to the LAPACK_LIB in the config/defaults.mk. This is already addressed in the 'develop' branch of MFEM, but not in the 'master' (please, see the [pull request](https://github.com/mfem/mfem/pull/74) )
I'm not sure that will solve your problem, though. But you can give it a try.

Cheers,
Mikhail

**Comment by kvoronin** [comment]
Hi @martemyev,

It does help (following anothet advuce from an experienced user I added lgfortran as well to be sure), thank you!

**Comment by martemyev** [comment]
Hi @kvoronin,

Great to hear that!

Cheers,
Mikhail
