### ISSUE TITLE
SuperLU interface is failing with hypre version 2.16.0

### ISSUE THREAD

**Issue by jandrej** [mfem/mfem#983]
Running
```
ex11p -slu
```
crashes with a segfault. This is related to the conversion from a `HypreParMatrix` to `SuperLURowLocMatrix`. I have not investigated further. This is using hypre 2.16.0 and SuperLU_Dist 6.1.1.

I confirmed that hypre 2.10.1 with SuperLU_Dist 6.1.1 works. Also confirmed that hypre 2.15.0 works.

Starting to track it down to
https://github.com/mfem/mfem/blob/878a82cf007b39d62166d73928e060c19fb95d46/linalg/superlu.cpp#L131

`hypre_MergeDiagAndOffd` seems to not return the same thing (comparing 2.15.0 and 2.16.0). Somehow when using 2.16.0 the `colind` pointer is null and therefore the segfault in SuperLU.

**Comment by tzanio** [comment]
Lets continue the discussion in PR #988.
