### ISSUE TITLE
mfem build failed

### ISSUE THREAD

**Issue by RashikShahjahan** [mfem/mfem#984]
Failing with this error:

linalg/ode.cpp: In member function ‘virtual void mfem::SDIRK34Solver::Step(mfem::Vector&, double&, double&)’:
linalg/ode.cpp:440:37: error: ‘M_PI’ was not declared in this `scope`
    const double a = 1./sqrt(3.)*cos(M_PI/18.) + 0.5;
                                     ^~~~
linalg/ode.cpp:440:37: note: suggested alternative: ‘_P’
    const double a = 1./sqrt(3.)*cos(M_PI/18.) + 0.5;
                                     ^~~~
                                     _P
makefile:389: recipe for target 'linalg/ode.o' failed
make[1]: *** [linalg/ode.o] Error 1
make[1]: Leaving directory '/cygdrive/c/Users/rashi/Downloads/mfem-4.0'
makefile:429: recipe for target 'serial' failed
make: *** [serial] Error 2

**Comment by NoseKnowsAll** [comment]
What operating system are you on and how are you compiling MFEM?

Looking into this a little bit myself, I wonder if the following change will work for you:

In `config/config.hpp`, change the following 3 lines:
```
#ifdef _WIN32   
// Macro needed to get defines like M_PI from <cmath>. (Visual Studio C++ only?)
#define _USE_MATH_DEFINES
#endif
```
to simply always `#define _USE_MATH_DEFINES` (i.e. remove the `#ifdef` in your code). Let us know if that works.

**Comment by RashikShahjahan** [comment]
@NoseKnowsAll  I am using Windows 10. Thanks I'll let you know if the changes work.

**Comment by RashikShahjahan** [comment]
I am compiling it using cygwin.

**Comment by RashikShahjahan** [comment]
Still getting the same error.

**Comment by v-dobrev** [comment]
I think I've seen this issue before under cygwin. If I remember correctly, you can replace the option `-std=c++11` with `-std=gnu++11` to get the `M_PI` macro defined.

**Comment by RashikShahjahan** [comment]
@v-dobrev where do I make the change?

**Comment by v-dobrev** [comment]
You can follow the steps here:
https://github.com/mfem/mfem/blob/878a82cf007b39d62166d73928e060c19fb95d46/INSTALL#L132-L134

and specifically, edit the contents of the variable `BASE_FLAGS` which is set to `-std=c++11` by default. You can also directly edit `config/defaults.mk` if you want.

**Comment by RashikShahjahan** [comment]
Now I am getting this error:

```
fem/bilininteg_mass.cpp:811:71: error: return-statement with a value, in function returning 'void' [-fpermissive]
g++   -O3 -std=gnu++11   -c fem/tmop.cpp -o fem/tmop.o
g++   -O3 -std=gnu++11   -c fem/geom.cpp -o fem/geom.o
makefile:389: recipe for target 'fem/bilininteg_mass.o' failed
make[1]: *** [fem/bilininteg_mass.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/cygdrive/c/Users/rashi/Documents/mfem-4.0'
makefile:429: recipe for target 'serial' failed
make: *** [serial] Error 2

```

**Comment by v-dobrev** [comment]
What version of `g++` do you have? You can see the version by running `g++ --version` in a terminal. I'll try to reproduce the error under cygwin -- I was not able to reproduce it under linux or mac os.

In the mean time you can try replacing:
https://github.com/mfem/mfem/blob/4d900b0c5fd6352c92173e74678bcbeeb11c8691/fem/bilininteg_mass.cpp#L811

with
```c++
         default: PAMassApply3D(NE, B, Bt, op, x, y, D1D, Q1D); return;
```
In the output you pasted, I can only see the error in the above line, however, it looks like other lines above that line will produce the same error. If that is the case, you'll need to update them as well.

**Comment by RashikShahjahan** [comment]
I am using g++ 7.4.0

The last error went away but the other errors are still there. Do you want me to post all of them?

**Comment by v-dobrev** [comment]
If all other error are of the same type, then there is no need to post them all. Do you get any other errors that are of a different type?

**Comment by RashikShahjahan** [comment]
They are of the same type. But they have this additional line:

error: no matching function for call to ‘PAMassApply3D(const int&, const mfem::Array<double>&, const mfem::Array<double>&, const mfem::Vector&, const mfem::Vector&, mfem::Vector&, const int&, const int&)’

**Comment by v-dobrev** [comment]
Which file and line is this error from?

**Comment by RashikShahjahan** [comment]
fem/bilininteg_mass.cpp:811:63:

**Comment by RashikShahjahan** [comment]
There is a similar error in a bunch of different lines.

**Comment by v-dobrev** [comment]
Hmm, this call should match the static function defined here:
https://github.com/mfem/mfem/blob/4d900b0c5fd6352c92173e74678bcbeeb11c8691/fem/bilininteg_mass.cpp#L414-L423

I'm not sure what's going on. I'll try to reproduce this error under cygwin and try to find a solution.

**Comment by v-dobrev** [comment]
I was able to reproduce the errors under cygwin.

There is actually no issue at line 811 of `fem/bilininteg_mass.cpp` -- you can revert any changes there.

The real issue actually comes from the first error that the compiler reports -- it does not like the use of `_B` as a name of a function parameter. To fix the issue, rename the variable `_B` to `B_` (for example) -- this variable appears at lines 200, 212, 417, and 429 in `fem/bilininteg_mass.cpp`.

I'll make a pull request tomorrow to fix the issue in the `master` branch.

Thank you for reporting the issue.

**Comment by NoseKnowsAll** [comment]
Today I learned about this: https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier

I had previously been using the equivalent of `_B` in my constructors. Even though this wasn't my code, I'll definitely be switching over to `B_` from now on.

**Comment by RashikShahjahan** [comment]
Thank you mfem was built properly.
