### ISSUE TITLE
Generating meshes in MFEM-v1.x  format

### ISSUE THREAD

**Issue by thengineer** [mfem/mfem#985]
Hello there,

I intend to use your awesome FEM library to run some studies on meshes (higher-order Lagrangian tetrahedral elements defined through isoparametric mapping from reference elements with equidistant nodal spacing) generated with my own mesh generator. 

I've read the [documentation on the mesh v1.x format](https://mfem.org/mesh-format-v1.x/), but there are still some open questions:

1. What is the nodal point distribution in the reference elements? Equidistant, Fekete, ...?
2. What is the rule for node numbering in the reference element (local node numbers)?

Thanks in advance,
Jakob

**Comment by thengineer** [comment]
In the meantime I've written my own interface to the hypre solver, so I no longer need to build upon MFEM, but out of curiosity: Is it possible in MFEM to manually specify the node numbering (eg by writing a custom mesh-reading method) or does MFEM intrinsically depend on the described global node numbering?

**Comment by tzanio** [comment]
Sorry for the delayed response @thengineer.

The nodal point distribution on the reference element depends on the `FiniteElementSpace` of the nodes `GridFunction`. By default it is Gauss-Lobatto, but it could be e.g. non-interpolatory (Bernstein).

The numbering is specific for MFEM, see https://mfem.org/mesh-format-v1.x/#finite-element-spaces. However we are involved with proposing a general high-order format which is independent of the MFEM ordering, see https://github.com/CEED/FMS.

Hope this helps,
Tzanio
