### ISSUE TITLE
What version ranges of MFEM 4.0's dependencies are required to build and install it?

### ISSUE THREAD

**Issue by goxberry** [mfem/mfem#989]
For instance, it's not clear to me from the [INSTALL](https://github.com/mfem/mfem/blob/master/INSTALL) file or the [Travis CI configuration](https://github.com/mfem/mfem/blob/master/.travis.yml) what version ranges are required for some dependencies.

For example, hypre version requirements aren't mentioned at all. I know that the hypre version must be at least 2.14.0 for version 4.0, based on looking at the [mfem spack package](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/mfem/package.py), but this information isn't discussed in any of the documentation, and the Travis CI configuration looks stale because it's using hypre 2.10.0b. I suspect that the hypre version must be more recent for mfem 4.0 -- perhaps hypre 2.16.0?

This information is needed for every dependency, and a user should not have to rely on the spack package to figure it out -- it should be possible to build mfem manually also, and despite having contributed tens of packages to two package managers, I don't have the foggiest idea of what versions of, say, SUNDIALS, I need to install for mfem 4.0. And I work with multiple people on the mfem team on other projects that use mfem. If I were an external user, I'd be even more befuddled.

**Comment by goxberry** [comment]
This information should probably also be backported to whatever maintenance version releases you guys want to support.

**Comment by jandrej** [comment]
Sorry for the late follow up. I will set up a list with compatible and recommended versions.

**Comment by goxberry** [comment]
@jandrej My impression is that later versions are generally preferred. My understanding of the current dependency versions are roughly:

- hypre >= 2.10.0b (conservative lower bound)
- netcdf >= 4.1.3? (based on matchinig NetCDF calls out of `mesh/mesh_readers.cpp` to NetCDF's releases; conservative)
- metis 4.0.3 or 5.1.0 (tight)
- petsc >= 3.8.0 (tight)
- conduit >= 0.3.1 (tight, from the MFEM Spack package)
- zlib >= 1.2.3? (conservative guess based on building on the LC RHEL7 systems)
- unwind >= 1.0 (because this version seems to be the API implemented in macOS, LLVM, and non-GNU libunwind; probably tight)
- LAPACK >= 3.0 (if `linalg/densemat.hpp` is any indication; conservative guess)
- SUNDIALS >= 2.7.0 (based on macros in `linalg/sundials.cpp` & the MFEM Spack package), and I guess < 5.0.0 until #923 lands
- MPI >= 1.2 (a conservative guess, unless there are MPI I/O calls, or one-sided communication)

That still leaves at least:

- SuiteSparse
- SuperLU_Dist
- PUMI
- OpenMP

**Comment by jandrej** [comment]
> hypre >= 2.10.0b (conservative lower bound)

I discovered recent changes in hypre 2.16 which introduce crashes. We know why and discussing a solution soon. I know the website has build instructions with 2.16.0, which should be fixed ASAP.

> petsc >= 3.8.0 (tight)

I will need to check with a coworker which uses petsc regularly.

> SuperLU_Dist

Works with the latest release v6.1.1

I can not speak for the rest and will follow up on my post.

**Comment by goxberry** [comment]
@jandrej If hypre 2.16 causes crashes, will there be an MFEM 4.0.1 bugfix release?

**Comment by jandrej** [comment]
Let me clarify that hypre 2.16 is compatible with mfem and works unless you intend to use the SuperLU interface. I can not give statement if there will be a bugfix release. @tzanio ?

**Comment by goxberry** [comment]
> Let me clarify that hypre 2.16 is compatible with mfem and works unless you intend to use the SuperLU interface. I can not give a statement if there will be a bugfix release.

I added https://github.com/spack/spack/pull/11880/files#diff-feb9d898be8387835581b4d727e70622R196 to the Spack MFEM package to document the version conflict, based on https://github.com/mfem/mfem/issues/983. The lines

```python
    # The MFEM 4.0.0 SuperLU interface fails when using hypre@2.16.0 and
    # superlu-dist@6.1.1. See https://github.com/mfem/mfem/issues/983.
    conflicts('+hypre+superlu-dist',
              when='mfem@4.0.0 ^hypre@2.16.0 ^superlu-dist@6.1.1')
```

should prevent MFEM 4.0.0 from being built using hypre 2.16.0 and SuperLU_Dist 6.1.1 as simultaneous dependencies, but should still permit building MFEM 4.0.0 using hypre 2.16.0 as a dependency in other configurations. If SuperLU_Dist interface failures occur for other versions of SuperLU_Dist with hypre 2.16.0, let me know, and I can change the `conflicts` line accordingly.

**Comment by tzanio** [comment]
We are not currently planning to have a 4.0.1 bugfix release. 

There are several issues with hypre-2.16.0, some of which are crashes like the SuperLU ones, but there is also support for mixed integers, which currently are not supported in the MFEM interface.

Our plan is to address as many of these as possible in the MFEM 4.1.0 release.

**Comment by tzanio** [comment]
@v-dobrev, can we make this part of the Spack package update for CEED-3.0?

**Comment by v-dobrev** [comment]
The CEED PR is https://github.com/spack/spack/pull/15500. I think the main dependencies are there but feel free to add more.

**Comment by tzanio** [comment]
Spack package and dependencies have been updates as part of the ceed-3.0 PR above.

For support of recent hypre releases, see #1276.

We reference specific package versions in the `INSTALL` file when they are critical, e.g. current libCEED integration requires version 0.6 or later, but I don't think it is realistic for us to keep track of all releases. To me it makes much more sense for this to be done in the CI of projects like xSDK which will likely use the Spack packages.

**Comment by goxberry** [comment]
> We reference specific package versions in the INSTALL file when they are critical, e.g. current libCEED integration requires version 0.6 or later, but I don't think it is realistic for us to keep track of all releases.

Agreed. `INSTALL` need only provide suggested dependency versions for the current MFEM version. Information on older releases can be obtained using git.

A single suggested version of each dependency in `INSTALL` is enough to build MFEM without undue guesswork most of the time, and could help create a policy to reduce your support burden: "these are the versions of libraries we will support". The MFEM team can decide whether they want to support any other configurations.

To borrow from the current `INSTALL` file, what I'm looking for is text like "only RAJA v0.10.0+ is supported" or even "only RAJA 0.10.0 is supported" for each library MFEM depends on, including optional dependencies. This information that eliminates guesswork that I -- or any other user -- would need to do to build (or package) MFEM if `INSTALL` omitted that information.

> To me it makes much more sense for this to be done in the CI of projects like xSDK which will likely use the Spack packages.

If the version information suggested above is in `INSTALL`, I don't need to look at the CI to figure out what library versions MFEM needs to build. For this issue, the CI doesn't really matter -- what matters is what's in `INSTALL`.

**Comment by v-dobrev** [comment]
@goxberry, how does #1411 look?

**Comment by goxberry** [comment]
@v-dobrev #1411 looks great! That's exactly what I was looking for. Thank you!

**Comment by tzanio** [comment]
Ok, #1411 looks good to me too
