### ISSUE TITLE
Advices for working with hybrid hexahedral-tetrahedral meshes

### ISSUE THREAD

**Issue by mxncr** [mfem/mfem#99]
Hello everyone,

I would like to work with hybrid hexahedral-tetrahedral meshes in MFEM. At first, I am interested in implementing H1/continuous basis. The configuration at hybrid interfaces is that two tetrahedra can be connected to one hexahedron face. To build a continuous function space from Lagrange finite elements, a solution is to use Qn-basis for hex, a P2n-basis for interface tetrahedra and a Pn-basis for tetrahedra which are not adjacent to hexahedra. Then to add constraints at hybrid interfaces to ensure the continuity.

For more detailed descriptions, there are the following resources:

* Ainsworth, M., Davydov, O., & Schumaker, L. L. (2016). Bernstein-Bézier finite elements on tetrahedral–hexahedral–pyramidal partitions. Computer Methods in Applied Mechanics and Engineering, 304, 140-170.

* Reberol, M., & Lévy, B. (2016). Low-order continuous finite element spaces on hybrid non-conforming hexahedral-tetrahedral meshes. arXiv preprint arXiv:1605.02626.

From the implementation point of view, there are three type of elements at the same time:

* hexahedra (trilinear mappings) with Qn basis
* tetrahedra (linear mappings) with Pn basis
* interface tetrahedra (quadratic mappings) with P2n basis

and 

* continuity constraints that can be enforced using the Restriction/Prolongation matrices.

In MFEM, I define a HexTetMesh class, derived from Mesh, to store the hybrid mesh. By re-writting mfem::Load and mfem::GetElementToFaceTable (the STable3D cannot store triangular and quadrilateral faces at the same ting), it seems ok.

I have more difficulties in deciding how to modify the finite element part. The H1_FECollection returns one finite element per Geometry::Type. But I need two types for tetrahedra (normal and interface) and segment (depending if it is a segment of a normal or interface tetrahedron). I could try to add new geometry types but I am afraid that it would lead to lot of code re-writing.

Another possibility I see is to keep the H1_FECollection but to derive a new FiniteElementSpace that would not use the FECollection but my own functions and data structures. But in this case I am also afraid of the consequences.

Ideally, I would like to:
* not modify the MFEM code, only write new code / derived classes
* write the minimum amount of code

As you are much more familiar with the MFEM code, I would like to hear your insights.  Do you have suggestions on how to proceed ? How would you implement such things ?

Thank you for your help and for providing this awesome library !
Maxence

**Comment by v-dobrev** [comment]
Hello Maxence,

As far as I can tell, working with the type of meshes and spaces you describe, in MFEM, will require extensions inside the library itself. This should not be a problem - we can work with you to add what is necessary, if you are interested in contributing to MFEM. The first thing to do will be to discuss what approach to take.

One approach is what you describe (let’s call it the non-conforming mesh approach): making the `Mesh` class (or a derived class) handle non-conforming faces - a quad on one side and 2 triangles on the other side. I'm not sure that this can be done just in a derived class - I think it will require at least some additions in the `Mesh` class. Of course, one option is to add such support directly in the `Mesh` class.

If we assume that any two tets adjacent to a hex form a pyramid, then another approach I see (let’s call it the conforming mesh approach) could be to add support for pyramids, something that will be generally useful. Then add special type of bisected H1 finite elements on pyramids and bisected quadrature rules to integrate them. Both the FE and the quadrature can call the appropriate existing tetrahedral FEs and quadratures. One drawback in this approach is that face integrals (think DG) will need to distinguish different types of quad faces - one where both adjacent elements are hexes and another where one is hex and the other a pyramid using a bisected basis. This will not be an issue, if the integrant depends only on the trace (e.g. values and/or tangential derivatives). The problematic case is when the integrand depends on, for example, the normal derivative.

In the non-conforming mesh approach, as you pointed out, the question is how to handle different types of tets. One approach, that may be useful more generally, is to extend the `FiniteElementSpace` class to support multiple `FiniteElementCollections`, e.g. based on an array of tags/labels associated with the mesh elements. To support such more general spaces everywhere in the library may require a lot of work and testing. However, starting with support for something simple, like example 1, could be much easier.

In either case, the first step will be to make sure that meshes with mixed types of elements work correctly. I think MFEM v3.2, as is, has problems with such meshes, at least in some cases.

I personally think that the non-conforming approach is probably the better choice, even though adding support for pyramids will also be useful.

Cheers,
Veselin

**Comment by mxncr** [comment]
Hello Veselin,

Thank you for your answer. I am more interested in the non-conforming mesh approach as I want to support the case where the interface tetrahedra do not form a pyramid. It happens when one (or more) tetrahedron is connected to the diagonal of a hex face only by one of his edge (Fig. 1, in the second reference).  

For the moment, I have tried something similar to your non-conforming mesh suggestion:
- A hex-tet mesh class derived of `Mesh`
- A hex-tet finite element space derived of `FiniteElementSpace` that have two `FiniteElementCollection` members

I think it is better to have a separate/derived mesh class as there are additional data-structures that will be queried by the new finite element space (e.g. Is this edge on a hex-diagonal? If so, what is the hex-face id?). My main technical issue is that some member functions of Mesh that I need to modify are not virtual. For the moment I over-write them but eventually it requires explicit pointers in the functions calling them, which involves re-writing the calling functions, etc. I would be happy to contribute and propose changes to the library, but my current approach is very experimental and probably not optimal.

Concerning the derived `FiniteElementSpace`, I have started by re-writing GetXDofs() functions, but some of them are not virtual, so I have the same difficulties than with the derived `Mesh` class. A more fundamental problem arises when enforcing the continuity (building the `cP` matrix): the edge/face DOFs of a order n `H1_FECollection` are not a subset of the order 2n collection (Lobatto nodes). One solution I see is to duplicate the faces and edges shared by two elements of different type. This means different faces and edges that have the same vertices, I am not sure the current data-structures can handle this.

There are small changes in the current library (in the base classes) that would make the extensions easier, but it would probably add some performance overhead for standard meshes. What is your position on this? I perfectly understand that you would prefer to avoid them.

To be more precise, some examples:
- `Mesh::GetFaceBaseGeometry` which assumes all faces are of the same type
- All the DOFs numbering methods in `FiniteElementSpace` assume that all edges have the same number of dofs
- making some base functions virtual

Thank you,
Maxence

**Comment by v-dobrev** [comment]
Hi Maxence,

Sorry for the delay in my reply.

What you suggest seems reasonable, so feel free to create pull request(s) with any suggestions for extensions and modifications.

Regarding the construction of `cP` - the local matrix that maps the dofs from the coarse/master (quad) side to the fine/slave (triangles) side can be computed using a new more general version of the method `FiniteElement::GetLocalInterpolation` - one that supports different types of master and slave elements.

Regards,
Veselin

**Comment by mxncr** [comment]
Hi Veselin,

For the `HexTetMesh`, `HexTetFiniteElementSpace` derived classes to work, I made small changes in the core library that you can see in this [commit](https://github.com/mxncr/mfem/commit/2fbdd3d6bdec55e8873ef352c06f840a991d9aaf). It seems sufficient for my needs for the moment, I will made a pull request later when I am sure nothing else is required. The rest of the HexTet implementation is not open-source as it is currently a mess with unrelated code mixed in, but I hope to release a clean version before the end of my PhD.

Eventually, I stored all the dofs (masters and slaves) in the `edofs, fdofs, bdofs` arrays of the `FiniteElementSpace` (`edofs` is a new array that act exactly as `fdofs, bdofs` but for edges).  Then depending of the context, the other functions retrieve only the master or slave dofs. There are also a mess of arrays that store the local configurations (is this edge on the diagonal of a quad? etc). The continuity is enfored by the `cP, cR` matrices. This implementation works for order one (mix of Q1, P2, P1) and maybe for order two (not sure yet), but I have a hard time debugging the higher orders. Still working on it!

I didn't know about the `GetLocalInterpolation`, I will surely look into it.

This issue can be closed if it is more convenient for the organization of this GitHub repo. I could re-open it later when I have more information, questions or results.

Best regards,
Maxence

**Comment by tzanio** [comment]
Hi Maxence,

It is great to see the progress you are making! I'll close this issue for now, but please don't hesitate to re-open or ask further questions in the future. Please keep us updated -- we are definitely interested in your project.

Tzanio
