### ISSUE TITLE
"make install" error in line 116 of Makefile

### ISSUE THREAD

**Issue by Tdub1229** [mfem/mfem#991]
Not sure what is going on, but I am trying to install MFEM on my house laptop to work from home... got this error. Could there be a dependent error?

[100%] Built target mfem
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/lib/libmfem.a
CMake Error at cmake_install.cmake:41 (file):
  file INSTALL cannot copy file "/home/ed/mfem/mfem-4.0/build/libmfem.a" to
  "/usr/local/lib/libmfem.a".

Makefile:116: recipe for target 'install' failed
make: *** [install] Error 1

**Comment by v-dobrev** [comment]
When you install MFEM using CMake, you can set the installation directory by setting the CMake option `-DCMAKE_INSTALL_PREFIX=/path/to/install/directory`. The default value is defined by CMake and in your case it seems to be `/usr/local`.

**Comment by tzanio** [comment]
@Tdub1229, were you able to resolve this?
