### ISSUE TITLE
How to multiply the CHI_3 with the OuterProductCoefficient  Matrix and Chi_1 with the   InnerProductCoefficient?

### ISSUE THREAD

**Issue by Asadanees** [mfem/mfem#995]
Dear @mlstowell ,
**CHI_1** and  **CHI_3** are scalars.
We want to develop the following matrix at each time step. 
**{CHI_1 | E (t) |^² +  Chi _3 A)} ∂E(t)/∂t**   for this case
I need your help to multiply **CHI_3**  with OuterProductCoefficient and**CHI_1**  with the   InnerProductCoefficient? . 

 **A** is 3X3 matrix and **E(t)^T** is transpose of **E(t)**.
**|E(t)|^2 = E(t)^T. E(t)= E_1^2+E_2^2+E_3^2= > Inner_Product(E(t),E(t))**
**E(t)= (E_1, E_2 , E_3)**  and **E(t)^T= (E_1, E_2 , E_3)^T** 
The matrix **A_3X3**  is obtained in such a way **A=  EE^T**. **A** is an outer product matrix.

`void` `NonlinearOptics::SetMatrix(` const Vector & `Electric_field)`
`delete gfE;
delete N1;
delete Nspmat2;`
`GridFunction *gfE= new GridFunction (&Nedelec);`
`gfE->SetFromTrueDofs(Electric_field);`
`VectorGridFunctionCoefficient *vgf= new VectorGridFunctionCoefficient(gfE);`
`OuterProductCoefficient *outer_product= new OuterProductCoefficient (*vgf, *vgf);`
`double inner_e =InnerProduct(*gfE, *gfE); `
`inner_e*=Chi_1;`
`Coefficient *chi_update = new ConstantCoefficient(inner_e);`
`InnerProductCoefficient *inner_product= new InnerProductCoefficient(*vgf, *vgf);`
`N1= new BilinearForm(&Nedelec);`
`N1->AddDomainIntegrator(new VectorFEMassIntegrator(outer_product));`
`N1->AddDomainIntegrator(new VectorFEMassIntegrator(chi_update));`
`N!->Assemble();`
`N1->Finalize();`
`N1->FormSystemMatrix(ess_bdr, *Nspmat2);`

Thanks,
Asad Anees

**Comment by mlstowell** [comment]
Hello, @Asadanees ,

I hope you are well.

To accomplish this you will need to nest coefficients to make composite functions.  You already have `inner_product` and `outer_product`, this is a good start.  Next you will need to wrap Chi_1 and Chi_3 as Coefficients (I'll assume these are constants but they could be any type of scalar-valued coefficient):
ConstantCoefficient Chi1Coef(Chi_1);
ConstantCoefficient Chi3Coef(Chi_3);

Finally, create the coefficients to be used with the integrators:
ProductCoefficient coef1(Chi1Coef, *inner_product);
ScalarMatrixProductCoefficient coef3(Chi3Coef, *outer_product);

That should be all you need.

Best wishes,
Mark

**Comment by Asadanees** [comment]
Dear @mlstowell,
Hope you are also fine.
Thanks you Mark. Best wishes.
Asad
