### ISSUE TITLE
QuadratureInterpolator::Eval3D fails

### ISSUE THREAD

**Issue by NoseKnowsAll** [mfem/mfem#997]
I found that `QuadratureInterpolator::Eval3D()` fails when you try to give it a large order.

This is a minor bug that I will fix.

**Comment by v-dobrev** [comment]
Is this with cuda device?

With what type of element, FE space order, and number of quadrature points do you see the issue?

**Comment by NoseKnowsAll** [comment]
This was on a simple single-core CPU. I forgot at what order it first becomes noticeable... maybe it was 3? That being said, the issue is within one of the MFEM_FORALL's that can be on a device.

See my pull request #998 - I resolved this issue caused by a small typo.

**Comment by v-dobrev** [comment]
Thanks @NoseKnowsAll. I noticed the PR after I posted my question.

**Comment by NoseKnowsAll** [comment]
Resolved by merge of #998 .
