### ISSUE TITLE
Compute curl of the Electric Field (example 3)

### ISSUE THREAD

**Issue by SamiullahMalik** [mfem/mfem#999]
Dear all,
I am developing an error estimator for the Maxwell problem on a waveguide. The example 3, which uses Nedelec H(Curl) FEM, is closely linked with my project. My question is that after I obtain the solution as a finite element grid function in step # 11, is there a way to compute the curl of the electric field at integration points that I provide? 
The overall goal is to obtain the initial solution field in step # 11, then compute the curl of the field at integration points, and then transfer the curl field to PUMI where it will be an input to the estimator. 

Thanks,
Sami Malik

**Comment by v-dobrev** [comment]
One way is to use the method `GridFunction::GetCurl()`.

**Comment by SamiullahMalik** [comment]
Hi Dobrev, 
Thank you for your answer. I have another question. Is it possible to use the Zienkiwicz-Zhu estimator in mfem on a solution (Electric Field) obtained by using Nedelec H(Curl) FEM. I have seen examples of ZZ estimator on elasticity problems in example 22, and I was wondering if it is possible to use it on a solution of Maxwell equations to get an idea of the error. 
Thanks

**Comment by v-dobrev** [comment]
Take a look at the miniapps in `miniapps/electromagnetics`, e.g. the `tesla` miniapp.

**Comment by azmmza** [comment]
Hi @v-dobrev ,
I would like to know how to compute the curl(curl(E))， because I need to use it in the case of a posteriori error estimation for residuals.(without RT FEM)
